### ISSUE TITLE
User folder can't be mounted if C drive isn't shared

### ISSUE THREAD

**Issue by alebianco** [docker/for-win#10]
### Expected behavior

Folders in the user's space can be mounted in a container without additional configurations.
Folder is mounted with cifs filesystem

### Actual behavior

Mounted folders turns out to be empty unless the C drive is shared
Folder is mounted with tmpfs filesystem

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
90E72802-EF07-4D06-8B68-EC91E23CDBBE/2016-07-29_20-12-28

  - a reproducible case if this is a bug, Dockerfiles FTW

````
> Get-ChildItem .\data\ | Select-Object Name
Name
----
test.sql
> docker run --rm -v /c/Users/alebi/Desktop/db/data:/data alpine ls -la /data
total 4
drwxr-xr-x    2 root     root            40 Jul 29 17:40 .
drwxr-xr-x   25 root     root          4096 Jul 29 17:56 ..

> docker run --rm -v /c/Users/alebi/Desktop/db/data:/data alpine cat /proc/self/mountinfo | Select-String -pattern "/data"

110 90 0:16 /c/Users/alebi/Desktop/db/data /data rw,relatime - tmpfs tmpfs rw
````

  - host distribution and version (Windows version, build number, etc)
````
> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      10586  0
````

### Steps to reproduce the behavior

  1. nothing.

**Comment by rneugeba** [comment]
We are using CIFS/SMB to share the host file system with the container and that requires authentication. Unfortunately, this means that the user has to explicitly enable sharing as documented in the getting started guide:
https://docs.docker.com/docker-for-windows/#/shared-drives

**Comment by alebianco** [comment]
Wouldn't it be enough to share a specific folder? instead of the whole drive?

**Comment by friism** [comment]
@alebianco the sharing is a one-time setup. Otherwise we'd have to pop up the sharing prompt for each `docker run`

**Comment by alebianco** [comment]
ok, i see. it's just that sharing a whole drive when i just need a folder it's a lot. I thought it would be possible to share just the specific folders, and have it done automatically during installation, like it's done on mac (and i guess linux). thanks anyway :)

**Comment by rneugeba** [comment]
We are actively looking into other solutions to make the experience more aligned with Docker for Mac. It's a significant development effort
