### ISSUE TITLE
Docker Destop fails to start

### ISSUE THREAD

**Issue by zaff0** [docker/for-win#10007]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 8208D6E3-E422-494F-983D-0A34E7E9D536/20210105112657

### Expected behavior
Docker Starts up successfully

### Actual behavior
Docker startup fails with Error dialog

### Information
  - Is it reproducible? Yes
  - Is the problem new? Worked up until a month ago
  - Did the problem appear with an update? No
  - Windows Version: 10.0.18363 Build 18363
  - Docker Desktop Version: 3.0.0(50684)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No virtualization

### Steps to reproduce the behavior

  1. Uninstalled existing Docker Version
  2. Removed all remaining docker files
  3. Installed Latest version of Docker Desktop (also tried various previous versions)
  4. Start Docker Desktop
  5. Error Dialog is displayed after a few minutes

**Comment by Z-a-r-a-k-i** [comment]
Same here

**Comment by Rots** [comment]
on a hyper-v installation cleaning wsl2 data fixed it.
