### ISSUE TITLE
Docker for Windows don't start on Windows 10 Educations

### ISSUE THREAD

**Issue by hkirk** [docker/for-win#1001]
### Expected behavior
Docker to start
### Actual behavior
Docker shows dialog about virtualization 

Hardware assisted virtualization and data execution protection must be enabled in the BIOS. See https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization-must-be-enabled

### Information

U:\>docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.30/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

Virtualization is enabled according to Performance tab in Task Manager
### Steps to reproduce the behavior

Start docker.

**Comment by jasonbivins** [comment]
Hi @hkirk  Let's check to make sure you meet all the pre-req's   please run the debug container script located here -  
https://github.com/Microsoft/Virtualization-Documentation/tree/live/windows-server-container-tools/Debug-ContainerHost

**Comment by hkirk** [comment]
Thanks, 

Looks like im missing something, cant read what im missing thought.

PS C:\Users\au181645\Downloads> .\Debug-ContainerHost.ps1
Checking for common problems
Describing Windows Version and Prerequisites
 [+] Is Windows 10 Anniversary Update or Windows Server 2016 1.36s
 [+] Has KB3192366, KB3194496, or later installed if running Windows build 14393 248ms
 [+] Is not a build with blocking issues 25ms
 [-] Has 'Containers' feature installed 17.14s
   Expected: {Enabled}
   But was:  {}
   23:             (Get-WindowsOptionalFeature -Online -FeatureName Containers).State | Should Be "Enabled"
   at <ScriptBlock>, C:\Users\au181645\Downloads\Debug-ContainerHost.ps1: line 23
Describing Docker is installed
 [+] A Docker service is installed - 'Docker' or 'com.Docker.Service'  233ms
 [+] Service is running 32ms
 [+] Docker.exe is in path 2.81s
 [+] Docker is registered in the EventLog service 165ms
Describing User has permissions to use Docker daemon
 [+] docker.exe should not return access denied 73ms
Describing Windows container settings are correct
 [+] Do not have DisableVSmbOplock set to 1 43ms
 [+] Do not have zz values set 41ms
 [+] Do not have FDVDenyWriteAccess set to 1 45ms
Describing The right container base images are installed
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.30/images/json: open //./pipe/docker_engine: The syst
em cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevate
d to connect. This error may also indicate that the docker daemon is not running.
 [-] At least one of 'microsoft/windowsservercore' or 'microsoft/nanoserver' should be installed 535ms
   ValidationMetadataException: The argument is null or empty. Provide an argument that is not null or empty, and then t
ry the command again.
   ParameterBindingValidationException: Cannot validate argument on parameter 'Property'. The argument is null or empty.
 Provide an argument that is not null or empty, and then try the command again.
   at <ScriptBlock>, C:\Users\au181645\Downloads\Debug-ContainerHost.ps1: line 115
Describing Container network is created
 [+] At least one local container network is available 1.35s
 [-] At least one NAT, Transparent, or L2Bridge Network exists 74ms
   Expected {0} to be greater than {0}
   206:       $totalnets | Should BeGreaterThan 0
   at <ScriptBlock>, C:\Users\au181645\Downloads\Debug-ContainerHost.ps1: line 206
 [-] NAT Network's vSwitch is internal 56ms
   Expected: {Internal}
   But was:  {}
   211:       $switchType | Should Be "Internal"
   at <ScriptBlock>, C:\Users\au181645\Downloads\Debug-ContainerHost.ps1: line 211
 [+] A Windows NAT is configured if a Docker NAT network exists 1.53s
 [-] Specified Network Gateway IP for NAT network is assigned to Host vNIC 67ms
   Expected: value to not be empty
   225:       $natGatewayIP | Should Not BeNullOrEmpty
   at <ScriptBlock>, C:\Users\au181645\Downloads\Debug-ContainerHost.ps1: line 225
 [-] NAT Network's internal prefix does not overlap with external IP' 37ms
   Expected {0} to be greater than {0}
   252:         $hostips.Count | Should BeGreaterThan 0
   at <ScriptBlock>, C:\Users\au181645\Downloads\Debug-ContainerHost.ps1: line 252
Showing output from: docker info

Showing output from: docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64

Showing output from: docker network ls

Getting Warnings & errors in the Windows event logs from the last 24 hours
Logs saved to C:\Users\au181645\Downloads\logs_20170815-105434.csv


Getting Docker for Windows daemon logs from the last execution
    Note: More logs are available at C:\Users\au181645\AppData\Local\Docker. Only showing the latest.

**Comment by hkirk** [comment]
Does the debug script it self do anything? I switched containers via this command

    & $Env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchDaemon

and now I can start docker.

Thanks
