### ISSUE TITLE
Unable to use the update installer (2.5.0.1 => 3.0.0)

### ISSUE THREAD

**Issue by saluton-mundo** [docker/for-win#10019]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: N/A
  - [ ] I am using the Docker WSL2 Backend
  - [ ] I am using the Docker Hyper-V Backend

### Actual behavior
When attempting to update Docker for Windows 3.0.0 (50684) to 2.5.0.1 I cannot proceed beyond this:

![image](https://user-images.githubusercontent.com/7760994/103761976-72760200-500f-11eb-9cb7-c915e452a862.png)

Naturally, I cannot kill the System process.

### Expected behavior
Not be blocked by a Windows process running. 

### Information
  - Windows Version: Windows 10 Enterprise 1909, Build 18363.1256
  - Docker Desktop Version: 2.5.0.1
  - WSL2 or Hyper-V backend?  No
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
  1. When clicking the "Update" prompt proceed to use the tool and download the package. It will then try to install and you will receive the "Stop Applications" prompt. The only conflicting process is "System (critical process)" which cannot be killed. Refreshing this screen will not produce a different outcome.

**Comment by saluton-mundo** [comment]
![image](https://user-images.githubusercontent.com/7760994/103762599-7a827180-5010-11eb-8e9a-eee84cd1f369.png)

**Comment by saluton-mundo** [comment]
A workaround is to install manually using the package downloaded from here: https://desktop.docker.com/win/stable/Docker%20Desktop%20Installer.exe

**Comment by ryprice** [comment]
I had the same issue today, and this workaround to disable the hyper-v windows feature, then uninstall/reinstall docker worked for me. https://github.com/docker/for-win/issues/9459#issuecomment-726846540
