### ISSUE TITLE
Latest docker versions are missing for windows.

### ISSUE THREAD

**Issue by Ganeshrockz** [docker/for-win#10034]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
  - [ ] I am using the Docker WSL2 Backend
  - [ ] I am using the Docker Hyper-V Backend

### Actual behavior

We are using a custom Docker Installer that downloads stable versions from https://download.docker.com. The latest Docker engine's version is `20.10.0`. Looks like the version is missing for windows (https://download.docker.com/win/static/stable/x86_64/) whereas the latest ones are present for both mac and linux. Are windows related download files moved to some other server location?

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
Sorry, there are no CLI packages for Windows, only Mac and Linux. There is a roadmap item docker/roadmap#144: feel free to 👍 it to upvote it.
