### ISSUE TITLE
Docker unable to start after upgrade 2.5.0 to 3.0.x

### ISSUE THREAD

**Issue by rickyheijnen** [docker/for-win#10031]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6F3C238B-2EB0-47FB-86DB-7798A1A7D0CF/20210107053146
  - [x] I am using the Docker WSL2 Backend
  - [x] I am using the Docker Hyper-V Backend

Everything worked fine on 2.5.0. After upgrading to 3.0.0 the Docker failed to start. So I downgraded back to 2.5.0. Today I tried again with the 3.0.4 release saying that a bug was fixed that prevented Docker from starting. But unfortunately again I'm unable to start Docker saying:

WSL distro stopped while waiting for Lifecycle server.
  >Stdout:

  >Stderr:
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:838
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:943
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).Execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:883
main.main
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:30
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374
rootfs mountiso version-pack
main.setupRootFS
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:394
main.doRun
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:233
main.run.func1
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:88
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:838
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:943
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).Execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:883
main.main
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:30
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374

**Comment by infacc** [comment]
Same here  #9464.

Not being able to start docker after updating to 3.0.5 led me to another problem (#9772). My solution was to reinstall docker using a windows admin user account.
