### ISSUE TITLE
Kubectl unable to connect to kubernetes after docker desktop upgraded 3.2

### ISSUE THREAD

**Issue by edwin2804** [docker/for-win#10038]
After upgrading docker desktop to 3.2 , kubectl is unable to connect to cluse

Unable to connect to the server: dial tcp 127.0.0.1:6443: connectex: No connection could be made because the target machine actively refused it.

PS C:\kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"windows/amd64"}
Unable to connect to the server: dial tcp 127.0.0.1:6443: connectex: No connection could be made because the target machine actively refused it.

PS C:\ kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
contexts:
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
current-context: docker-desktop
kind: Config
preferences: {}
users:
- name: docker-desktop
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED

**Comment by edwin2804** [comment]
Here is the Diagnosis ID : E66874D7-0D23-4130-90B1-34E4023FE645/20210107151936

**Comment by edwin2804** [comment]
Can someone help me wiith resolution , I tried all options like factory reset , kubernetes reset , setting up environment variable path for config - none has solved the problem

Note : Docker desktop 2.4 perfectly works with no issues , after upgrading to latest version nothing is working.

Even docker command are working only we expose daemon on non TLS option

**Comment by huseyinelci2000** [comment]
I took same notice, like you.

```Shell
PS C:\kubernetes> kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"windows/amd64"}
Unable to connect to the server: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.
```
When I researche on Google, **I found this information**.  It need **.kube/config** files in _your personal folder_ (into C:\Users\XYZ\ )
I checked here and I didn't see thise folder. I think my problem is this. But I didn't find yet about .kube\config setting 
![image](https://user-images.githubusercontent.com/48033398/105611177-babc5080-5d81-11eb-8e61-8c25e069c943.png)

**Comment by huseyinelci2000** [comment]
Yes It was work.
1. I created **.kube/** folder in my personal folder (into C:\Users\XYZ\ .kube)
2. I again install choco  and minikube. After install, when I check .kube folder it creates sa-config file.
3. Run this statement

       c:\Kubernetes>minikube start --driver=docker

My Output is:

      * minikube v1.16.0 on Microsoft Windows 10 Pro 10.0.18363 Build 18363
      * Using the docker driver based on user configuration
      * Starting control plane node minikube in cluster minikube
      * Creating docker container (CPUs=2, Memory=1989MB) ...
      * Preparing Kubernetes v1.20.0 on Docker 20.10.0 ...
        - Generating certificates and keys ...
        - Booting up control plane ...
        - Configuring RBAC rules ...
      * Verifying Kubernetes components...
      * Enabled addons: storage-provisioner, default-storageclass
      
      ! kubectl.exe is version 1.12.0, which may have incompatibilites with Kubernetes 1.20.0.
        - Want kubectl v1.20.0? Try 'minikube kubectl -- get pods -A'
      * Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
4.  Check your minikube status
      `c:\Kubernetes>minikube status`
My Output is:

```
      minikube
      type: Control Plane
      host: Running
      kubelet: Running
      apiserver: Running
      kubeconfig: Configured
      timeToStop: Nonexistent
```

**NOTE:**
It must use **CMD** with **ADMINISTOR**
