### ISSUE TITLE
Restart-Service com.docker.service brakes docker

### ISSUE THREAD

**Issue by andyliddle** [docker/for-win#1004]
### Expected behavior

Docker service restarts and works.

This brakes my powershell scripts which need to restart the service in order to make changes to the daemon.json config file

### Actual behavior

PS C:\WINDOWS\system32> docker info
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.30/info: open //./pipe/docker_engine: The system cann
ot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

### Information

A diagnostic was uploaded with id: 0A8A65C9-CE19-4CB0-9010-7AC0BB6B6832/2017-08-14_18-43-28
Windows 10 Pro, Docker  Version 17.06.0-ce-win19 (stable)

### Steps to reproduce the behavior

1. Install DockerForWindows - Latest Sable
2. Switch to windows containers
1. Restart Docker Service (e.g. Restart-Service com.docker.service)

**Comment by jasonbivins** [comment]
Hi @andyliddle   I can repro this on my system, I'll file an issue for it.

Thanks for posting!

**Comment by friism** [comment]
@andyliddle can you detail what you're trying to achieve at a higher level? Docker for Windows is not currently built for automated scripting.

You might have better luck with a manual install: https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/configure-docker-daemon#manual-installation

You can find stable CE binaries here: https://download.docker.com/win/static/stable/x86_64/
