### ISSUE TITLE
Docker Start-up Concerns (Failed to deploy distro docker-desktop)

### ISSUE THREAD

**Issue by jimmij2** [docker/for-win#10048]
- [x ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: F00603FF-DCC1-4B29-9D22-F3876C3D4731/20210108090131
  - [x ] I am using the Docker WSL2 Backend
  - [x ] I am using the Docker Hyper-V Backend

### Information

  - Windows Version: Windows 10 Pro
  - Docker Desktop Version: 3.0.4.51218
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
"Failed to deploy distro docker-desktop" usually means that WSL 2 is not installed correctly. Please follow these instructions from Microsoft: http://aka.ms/wsl2-install.
