### ISSUE TITLE
Default to windows containers after installation

### ISSUE THREAD

**Issue by laprogs** [docker/for-win#10053]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
  - [ ] I am using the Docker WSL2 Backend
  - [x] I am using the Docker Hyper-V Backend

### Information

I want to develope an app containing a number of servers inside (DLNA-server, Samba server, etc). It should run on Windows 10 desktop. So, I decided to exloit Windows containerization.

I'd really love if that application installed could install Docker for windows without any end-user attenance (it should be transparent for a user that Docker is being installed at all). The only think which blocks is that popup about need of WSL2 installation after docker starts for the first time and also a need to switch docker to Windows containders. An end-user must do that manually that is unwanted because that affects user experience.

The request

Could you please add an option to the Docker installer to use Windows containers by default? That option should be configure throught the command line parameters like: "Docker Desktop Installer.exe" install --quiet --windows-containers

Thank you so much in advance.

  - Windows Version: Windows 10 Pro
  - Docker Desktop Version: The newest
  - WSL2
  - Desktop Windows

### Steps to reproduce the behavior
  1. Install docker for windows
  2. Restart the system
  3. After docker starts a popup is displayed saying that WSL2 should be installed (this is unwanted)

**Comment by laprogs** [comment]
![image](https://user-images.githubusercontent.com/77158757/104046102-3b0e7d80-51e8-11eb-815e-ae9b14b35d4e.png)

**Comment by stephen-turner** [comment]
Thanks for the feedback. I think this is mostly covered by docker/roadmap#80. Feel free to go and give that issue a thumbs-up, it hasn't had much interest so far.
