### ISSUE TITLE
Docker commands are very slow

### ISSUE THREAD

**Issue by colin-sim-myob** [docker/for-win#10074]
Docker commands in PowerShell and Command Prompt are extremely slow (e.g. `docker images` take 30 secs).
  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: DBF6224E-AC3C-44D6-BAB9-63A4CB4BD8D3/20210112001900
  - [x] I am using the Docker WSL2 Backend
  - [x] I am using the Docker Hyper-V Backend

### Actual behavior
Any docker command (e.g. `docker`, `docker images`, `docker ps -a` take at least 30 secs to execute.

### Expected behavior
All docker commands to complete reasonably quickly.

### Information
I have Docker for Windows running without issues for the last 6 months. Starting yesterday (11-Jan-2021) every docker command takes a very long time to run. I have restarted docker desktop, clean and purged data, and reset to factory defaults  - none of which helped.

  - Windows Version: Windows 10 Build 18363.1256
  - Docker Desktop Version: 20.10.2, build 2291f61
  - WSL2 or Hyper-V backend? WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

**Comment by christianfeurer** [comment]
I'd like to vote for reopen of this issue. I'm having the same issue when using wsl2. The access from my windows command prompt to the docker daemon takes longer than the hardcoded 20 seconds timeout. I'm suggesting to make this timeout configurable to overcome the slow windows to linux connection.
