### ISSUE TITLE
Cannot login to docker via powershell, or access images via Kitematic

### ISSUE THREAD

**Issue by lostllama** [docker/for-win#1007]
### Expected behavior

Login: Successful login.
Kitematic: Images downloaded.

### Actual behavior

Login error:
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:55308->[::1]:53: read: connection refused

Kitematic error:
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:33653->[::1]:53: read: connection refused"}

### Information

Docker v17.06.0-ce-win19 (12801)
Tried with two DNS servers to see if it's a DNS isuse.
I'm in Japan.

Our ISP is Asahi Net, although I've tried on the building network, which uses OCN as an ISP, and the issue is the same. Is Japan blocked?

OK, so it seems that uninstalling Docker, removing all traces of its existence from the registry, files, etc. and then reinstalling it has solved my issue. I'm curious as to how a Docker installation that was working just fine ended up broken like this.

### Steps to reproduce the behavior

Docker error: Run "docker login" from PowerShell
Kitematic error: Try to download any image (dotnet, hello-world-nginx, etc.)

**Comment by jasonbivins** [comment]
Hi @lostllama   Without a Diagnostic ID, we can't really tell much - and  you mentioned that you cleaned all the files.  Try posting a fresh diagnostic, there's a chance that the previous errors are still there in the logs.    Right click the Docker icon >> Diagnose and Feedback

Was this the first time you tried Docker Login , or was it working before and then stopped?

**Comment by lostllama** [comment]
Diagnostic id is B258654D-04F9-494C-9F43-8B514E3411E0/2017-08-16_12-15-47

Docker had previously been working fine. I hadn't used it for about a month
or two until yesterday, and then I needed to create an image from one of
the repository images (dotnet), and I received these errors. The first one
I received in Kitematic, and then I tried to use the command line via
Powershell and got the login error.

**Comment by MCPx** [comment]
My team is also started having this issue. One person's docker login still works for the same private repo, using the same version of docker (17.06.0-ce-win19 (12801)).

Diagnostic Id for one that is failing: 5F13E470-0626-4DCD-A6C1-0A5AC6D0004C/2017-08-18_10-19-00
Diagnostic Id for one that still successfully logs in: DFB9B52F-2A3D-4036-BE7B-6B679DF66FA4/2017-08-18_10-29-45

**Comment by hsteinshiromoto** [comment]
I am having the same problem as @lostllama:

`Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:45765->[::1]:53: read: connection refused`

**Comment by tullydwyer** [comment]
Was getting the same error... Windows 10. I did a reset to factory defaults and login was fixed?

```
docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: xxxxx
Password:
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:42463->[::1]:53: read: connection refused
```

Same with AWS.

```
Error response from daemon: Get https://xxxxxx.dkr.ecr.us-east-1.amazonaws.com/v2/: dial tcp: lookup xxxxx.dkr.ecr.us-east-1.amazonaws.com on [::1]:53: read udp [::1]:42425->[::1]:53: read: connection refused
```

![image](https://user-images.githubusercontent.com/7508115/35315125-6b91a070-0116-11e8-94af-ab9d950327f1.png)

**Comment by rn** [comment]
It looks like the DNS server is configure to be `localhost` and configured to use IPv6.

`IPCONFIG /ALL` should confirm the DNS servers and you can check with `netstat -abno` if anything is listening on localhost port 53 (ie if potentially a DNS server is running locally.

**Comment by lostllama** [comment]
@rn No and no. I know this was a while ago, but I distinctly remember trying different DNS servers (Google, router which uses Google, OpenDNS). And I definitely don't have a DNS server running locally. The fact that removing all traces of Docker and reinstalling it seems to fix it suggests that it certainly is not related to basic network configuration, but a problem internal to Docker.

**Comment by ncthernane** [comment]
Hi everyone, i'm new to docker.
Can anyone help me out with my issues please. I have successfully installed docker but when i login my docker account through windows powershell, it will give me this error.
Error response from daemon: Get https://registry-1.docker.io/v2/: read tcp 10.4.21.235:62406->35.169.231.249:443: wsarecv: An existing connection was forcibly closed by the remote host.

Hoping someone could help me out. Thanks in advance.
