### ISSUE TITLE
Switching to Windows Containers errors

### ISSUE THREAD

**Issue by JonCubed** [docker/for-win#1008]
### Expected behavior
Should be able to switch to windows containers and it works

### Actual behavior
Switching causes Docker for Windows to crash. Once switched I cannot switch back to Linux Containers

### Information

  - Diagnostic ID: 15A4D0EF-25DE-48D2-B3ED-E67A002549BF/2017-08-15_16-29-58
  - `docker version`:

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.30/version: open //./pipe/docker_engine: The system
annot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated t
 connect. This error may also indicate that the docker daemon is not running.
```

  - Windows 10 Pro (BuildNumber: 15063)

### Steps to reproduce the behavior

  1. Install Docker for windows
  2. Click `Switch to Windows Containers...` in whale systray context menu

**Comment by ManoMarks** [comment]
I have the same issue:
E32C97F5-7DA6-4441-B622-154CC9DE121D/2017-08-17_15-30-26

**Comment by JonCubed** [comment]
So I think I've managed to figure what is going on here.

when I run `docker network inspect nat` I should expect to see

```
[
    {
        "Name": "nat",
        ...
        "Scope": "local",
        "Driver": "nat",
        ...
        "IPAM": {
            "Driver": "windows",
            "Options": null,
            "Config": [
                {
                    "Subnet": "0.0.0.0/0",
                    "Gateway": "0.0.0.0"
                }
            ]
        },
        ...
    }
]
```

but instead I was seeing

```
[
    {
        "Name": "nat",
        ...
        "Scope": "local",
        "Driver": "nat",
        ...
        "IPAM": {
            "Driver": "windows",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        ...
    }
]
```

This was discovered by running [Debug-ContainerHost.ps1](https://github.com/MicrosoftDocs/Virtualization-Documentation/tree/live/windows-server-container-tools/Debug-ContainerHost) and failing ***Specified Network Gateway IP for NAT network is assigned to Host vNIC*** test and then looking through script to see what the test was really looking at.

So I think for some reason the docker container configuration reverted to bridge mode.

I'm not very knowledgable about docker networks so don't know if there is a better way to reconfigure them but I used the [WindowsContainerNetworking-LoggingAndCleanupAide.ps1](https://github.com/MicrosoftDocs/Virtualization-Documentation/tree/live/windows-server-container-tools/CleanupContainerHostNetworking) to fix the issue.

```
PS C:\> .\WindowsContainerNetworking-LoggingAndCleanupAide.ps1 -Cleanup -ForceDeleteAllSwitches
```

**Comment by friism** [comment]
cc @kallie-b

**Comment by hinell** [comment]
Check out if windows container feature is enabled in the win features.

**Comment by JonCubed** [comment]
@hinell for me it was
