### ISSUE TITLE
Docker Desktop is crashing after an normal restart and it's not working anymore

### ISSUE THREAD

**Issue by jdaibello** [docker/for-win#10099]
I installed NodeJS, Yarn and VS Code (some extensions too - Docker included) and I restarted my computer to include VS Code PATH variables. So, Docker Desktop is crashing when the Windows is started.

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
  - [x] I am using the Docker WSL2 Backend
  - [ ] I am using the Docker Hyper-V Backend

### Actual behavior
Docker Desktop is crashing when starting.

`System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\jpedr\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: O serviço não pode ser iniciado porque está desativado ou não tem dispositivos ativados associados.

 stderr: 
   em Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) na C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:linha 146
   em Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__17.MoveNext() na C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:linha 169
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() na C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:linha 78
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__25.MoveNext() na C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:linha 99
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() na C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:linha 29
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() na C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:linha 67
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() na C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:linha 92
`

### Expected behavior
Docker Desktop should start normally.

### Information

  - Windows Version: Windows 10 Pro 20H2 version
  - Docker Desktop Version: Latest stable available in the website. I installed Docker Desktop today.
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Start the computer

**Comment by stephen-turner** [comment]
This error means that WSL 2 is not properly installed. You should be able to sort it out by following Microsoft's instructions at https://aka.ms/wsl2-install.

**Comment by jdaibello** [comment]
I think it was because my antivirus, I have WSL 2 installed but my antivirus warned me about a possible vulnerability and I reversed the Kaspersky's decision to solve the problem and now Docker Desktop is working fine. Anyway, thank you for your help, Stephen

**Comment by stephen-turner** [comment]
Ah, good, that's useful to know.
