### ISSUE TITLE
Feature Request: Please bundle a newer build of docker-credential-ecr-login

### ISSUE THREAD

**Issue by TBBle** [docker/for-win#10105]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
  - [x] I am using the Docker WSL2 Backend
  - [ ] I am using the Docker Hyper-V Backend

### Actual behavior

The `docker-credential-ecr-login.exe` bundled with Docker Desktop is 0.4.0, and predates https://github.com/awslabs/amazon-ecr-credential-helper/pull/201, which means that using it with, e.g., a `credentials_process` fails unless env-vars are set.

See https://github.com/awslabs/amazon-ecr-credential-helper/issues/232 for details and the workaround.

### Hoped-for behaviour

The `docker-credential-ecr-login.exe` bundled with Docker Desktop is built from newer source than 0.4.0, and includes https://github.com/awslabs/amazon-ecr-credential-helper/pull/201, hence removing the need to worry about setting env-vars.

There hasn't _been_ an upstream release of this utility since 0.4.0, but [not much has changed since](https://github.com/awslabs/amazon-ecr-credential-helper/compare/v0.4.0...master). In fact, this is the only changelog-worth feature since then. So I'm hoping just building the latest master tree is fine.

Otherwise, this can wait for an 0.5.0 release, whenever that happens: https://github.com/awslabs/amazon-ecr-credential-helper/milestone/3

**Comment by stephen-turner** [comment]
Thanks, @TBBle. We do generally wait for official releases of our upstream components: do you have any idea when the 0.5.0 (or 0.4.1?) release will be made?

**Comment by TBBle** [comment]
I don't know, it's been a long time since the last release (January 2020) so I thought the project was idled. However, there was some renewed activity from a few maintainers in December, including creating an [0.5.0 milestone](https://github.com/awslabs/amazon-ecr-credential-helper/milestone/3) albeit without a target date.

Perhaps @samuelkarp or @kzys can clarify the current and intended state?

**Comment by TBBle** [comment]
[Amazon ECR Credential Helper - Release v0.5.0](https://github.com/awslabs/amazon-ecr-credential-helper/releases/tag/v0.5.0) has been released, so this should be unblocked now.

**Comment by stephen-turner** [comment]
Great, thanks for letting us know.

**Comment by stephen-turner** [comment]
We've bumped it in our code, it will be in the next release.

**Comment by TBBle** [comment]
Ooops, forgot to close this. docker-credential-ecr-login 0.5.0 was included in [Docker Desktop 3.2.0](https://docs.docker.com/docker-for-windows/release-notes/#docker-desktop-320).
