### ISSUE TITLE
docker command extremely slow after upgraded to newer version

### ISSUE THREAD

**Issue by gduan2000** [docker/for-win#10112]
[Logfile.zip](https://github.com/docker/for-win/files/5823975/Logfile.zip)

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
  - [ ] I am using the Docker WSL2 Backend
  - [x] I am using the Docker Hyper-V Backend

### Actual behavior
Ever since I upgraded the docker desktop version, the docker command became extremely slow. With version 3.1.0, it took 42 seconds for "**docker version**" to respond. I had to roll back to 2.5.0.1, it improved to 11 seconds. Still, that's way more than before I upgraded the version, which was within a second.
I tried disabling IP6, disabling NetBios in IP4 properties, reinstalling Hyper-V, reinstalling docker desktop, which some other posts suggested. None of them worked. Then I installed ProcessMonitor, I found something strange - docker.exe took a lot of time to load com.docker.cli.exe. The full log file is attached => [Logfile.zip](https://github.com/docker/for-win/files/5823976/Logfile.zip)

15:45.0 | docker.exe | 392 | ReadFile | C:\Program   Files\Docker\Docker\resources\bin\com.docker.cli.exe | SUCCESS | Offset: 0, Length: 4,096, Priority:   Normal
-- | -- | -- | -- | -- | -- | --
15:45.0 | docker.exe | 392 | ReadFile | C:\Program Files\Docker\Docker\resources\bin\com.docker.cli.exe | SUCCESS | Offset: 4,096, Length: 4,096
15:45.0 | docker.exe | 392 | ReadFile | C:\Program Files\Docker\Docker\resources\bin\com.docker.cli.exe | SUCCESS | Offset: 8,192, Length: 4,096
15:45.0 | docker.exe | 392 | ReadFile | C:\Program Files\Docker\Docker\resources\bin\com.docker.cli.exe | SUCCESS | Offset: 12,288, Length: 4,096
15:45.0 | docker.exe | 392 | ReadFile | C:\Program Files\Docker\Docker\resources\bin\com.docker.cli.exe | SUCCESS | Offset: 16,384, Length: 4,096

This went on and on until 53Mb com.docker.cli.exe was fully loaded, Then it executed "**com.docker.cli.exe version**", and the result came through. Why did docker.exe take so much time to read com.docker.cli.exe? This was the behavior for both v3.1.0 and v2.5.0.1, the newer version took longer to load the cli exe.
### Expected behavior
"**docker version**" to respond within or around a second.
### Information

  - Windows Version: Windows 10 Enterprise, 10.0.17763 Build 17763
  - Docker Desktop Version: 2.5.0.1
  - WSL2 or Hyper-V backend?  Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Laptop, 32G ram, i5.

### Steps to reproduce the behavior

  1. uninstall docker desktop, 
  2. install newer version docker desktop,
  3. start docker desktop
  4. run command "docker version"
  5. stare at the screen for 11 seconds

**Comment by gduan2000** [comment]
any suggestions? please help

**Comment by sklibanov** [comment]
Same issue exactly, with Windows 10 Enterprise build 19041.804. ProcessMonitor reports the same as OP.

Has anyone on the Docker team reproduced this issue?
