### ISSUE TITLE
Docker for Windows / WSL2 crashes when exposing a large range of ports

### ISSUE THREAD

**Issue by BryanDollery** [docker/for-win#10124]
I'm trying to run k3d and I want to expose all the standard nodeports in the range 30000-32767 (over 2.5k ports), but docker crashes when I use a range over around a thousand ports. I have run some experiments, and it does see to be related to the size of the port range.

This can be replicated easily:

```
docker run -it --rm -p 30000-32000:30000-32000 alpine sh
```

But this:

```
docker run -it --rm -p 30000-31000:30000-31000 alpine sh
```
has no problems at all.  It's quite frustrating really.

I am running Windows 10 pro and Docker Desktop for Windows, both fully updated.

Client: Docker Engine - Community
 Cloud integration: 1.0.4
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:32 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

```
Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:23 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

TIA

**Comment by simonferquel** [comment]
I am looking at it, I can't say it is a good practice to expose such a range with the way Desktop works though.

**Comment by simonferquel** [comment]
I have a fix for this but:
- creating the container is very slow
- what it does under the hood is that it creates 2k listeners on Windows, and 4k on the Linux side... which consumes a lot of RAM. I don't think this approach is good.

**Comment by BryanDollery** [comment]
**Good practice**: This isn't a production platform. It's a local development platform, and what's good practice in that respect? Surely there are too many variants to pick out good-practice. Opening a million ports isn't good practice in corporate production environments, but this is a windows laptop being used for development and training. Also, unfortunately, this is the port range kubernetes requires by default. So, if I want to use K3D, or KinD, or any other kubernetes in a container approach, then I have to expose this port-range.

One alternative is restricting the range in docker and making the node-port assignments explicit in my k8s yaml descriptors, but this is a slow road to hell. Another alternative is reconfiguring kubernetes default port-range, but again that's a slow road to hell, and isn't so easy with things like K3D (in fact, I don't think it's possible with K3D). 

I could always not use those solutions and go with the Docker for Windows K8S implementation, but I am developing training-courses for a bunch of students and need a platform-independent solution -- my tutorial scripts all start with the K3D configuration so that we're all on the same page with the same platform, then I don't have to deal with dozens of people asking why it doesn't work for them.

**RAM**: personally, my dev laptop has 40GB of ram, so it's not likely to adversely affect me. If it adversely affects a developer then they can simply not use it. Maybe there would be some need for a warning in the docs about memory consumption relating to port-ranges, but 'resources use memory' should be a pretty obvious thing, no?

**Speed**: If I'm opening 2.5k ports then I don't really expect the container to start that rapidly. I have a 12-thread cpu though, so if it is possible to spread that work across multiple-threads then it might be quicker. Again, a line in the docs warning people that this might be slow would probably be enough. Once I have the container running I tend to leave it running for days anyway, so the startup time isn't really significant. Unless you're talking about 10 hours, then I'd be worried :)

**Opinion** I think that implementing a fix for this with a 'let the buyer beware' warning label would be fine, assuming that all you're doing is expanding a couple of arrays to allow more entries and that it will not adversely affect anything else. If a dev has a laptop that can handle it, then fine, and if they haven't then they simply can't use that capability.

**Comment by simonferquel** [comment]
We have a fix inbound, but as you mentioned above, it won't be fast.
Another solution could be to try to use the Load balancer implementation we use in our Docker Desktop k8s distribution. I never tried to use it on k3d, so it comes with absolutely no guarantee.

You can look at its definition with `kubectl get pod/vpnkit-controller -n kube-system -o yaml`. What it does is that it talks to the Windows or Mac host to expose services of type "LoadBalanced" to the host. If you manage to make it work, it could even be a very good way to explain the differences between a port exposed in LoadBalanced mode (e.g. exposed externally) or in NodePort (exposed within the cluster LAN only).

**Comment by BryanDollery** [comment]
Thanks for that, @simonferquel. I'll keep an eye open for the fix and I'll definitely try out that load-balancer.
