### ISSUE TITLE
docker new windows update

### ISSUE THREAD

**Issue by Nasirah231** [docker/for-win#10126]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
  - [ ] I am using the Docker WSL2 Backend
  - [ ] I am using the Docker Hyper-V Backend

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by SHAKOTN** [comment]
@Nasirah231 Download 3.1.0 Docker(most recent version from here - https://docs.docker.com/docker-for-windows/install/) and install it. Worked for me

**Comment by Nasirah231** [comment]
> @Nasirah231 Download 3.1.0 Docker(most recent version from here - https://docs.docker.com/docker-for-windows/install/) and install it. Worked for me

okay noted thank you!
