### ISSUE TITLE
[WSL2] - Ping docker containers private IP from windows

### ISSUE THREAD

**Issue by ricardojmf** [docker/for-win#10128]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
  - [x] I am using the Docker WSL2 Backend
  - [ ] I am using the Docker Hyper-V Backend

Currently I have my usual linux containers running on WSL2 with Docker Desktop integration. And I need to access the containers private IP from windows.
Unfortunately they are not rachable neither from windows or wsl.

### Information

  - Windows Version: Windows 10
  - Docker Desktop Version: 3.1.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. Start containers on WSL terminal
  2. ping containers on windows CMD terminal

**Comment by jones1008** [comment]
I think this is the same problem as in #9113

**Comment by jones1008** [comment]
BTW: [https://github.com/docker/for-win/issues/5538#issuecomment-611126380](https://github.com/docker/for-win/issues/5538#issuecomment-611126380) this helped me with a similar problem...
You define a "free" loopback IP from the IP range `127.0.0.1/8` to the `ports` part in your `docker-compose.yml`. For example:
```yaml
services:
  apache:
    image: httpd
    ports:
      - 127.55.0.1:80:80
```
Then you can access your application with the IP `127.55.0.1` from the host machine. Note that a ping on all IPs in the loopback range `127.0.0.1/8` works, so I'm not sure if that helps in your case...

**Comment by ricardojmf** [comment]
Thank you I'll try it :)!
