### ISSUE TITLE
[Windows10] Docker desktop is not working on startup after I changed setting for "command prompt"

### ISSUE THREAD

**Issue by bugsoft337** [docker/for-win#10132]
Hi, it's my first time to write this kind of report, I am so nervous lol.

Actually I know how to avoid seeing this problem but I think I need to report about this error.

I met an error reporting dialog window during docker desktop is starting up after I changed one thing for a Command Prompt application.

[FYI]
1. I was using Docker desktop without any problem until today morning.
2. And I needed to change one setting for Command Prompt application of windows 10, because I was following someone's instruction for studying.
3.  I just turned  on "Legacy Console Mode" option of the Command Prompt application, and I've got the situation that the docker desktop application keeps showing an error dialog(crash reporting).
4. I did not know at the first time that changing command prompt's options is affected to this situation. But, somehow I realized maybe that setting I changed before could affect to this situation.
5. I restored the setting to not using "Legacy Console Mode" and the Docker desktop application has stopped showing error after that.

  - [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
  - [ ] I am using the Docker WSL2 Backend
  - [ ] I am using the Docker Hyper-V Backend

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
Thanks for the report, @bugsoft337. Which version of Docker Desktop are you using? We had some problems with the legacy console before (#9770) but I thought they were fixed in the latest version.

**Comment by bugsoft337** [comment]
Oh, it's 3.1.0(51484)Thank you for your replying.Sent from my Bell Samsung device over Canada's largest network.
-------- 원본 이메일 --------발신: Stephen Turner <notifications@github.com> 날짜: 21/1/19  오후 7:00  (GMT+09:00) 받은 사람: docker/for-win <for-win@noreply.github.com> 참조: bugsoft337 <bugsoft337@gmail.com>, Mention <mention@noreply.github.com> 제목: Re: [docker/for-win] [Windows10] Docker desktop is not working on startup after I changed setting for "command prompt" (#10132) 
Thanks for the report, @bugsoft337. Which version of Docker Desktop are you using? We had some problems with the legacy console before (#9770) but I thought they were fixed in the latest version.

**Comment by bugsoft337** [comment]
Sent from my Bell Samsung device over Canada's largest network.
-------- 원본 이메일 --------발신: Stephen Turner <notifications@github.com> 날짜: 21/1/19  오후 7:00  (GMT+09:00) 받은 사람: docker/for-win <for-win@noreply.github.com> 참조: bugsoft337 <bugsoft337@gmail.com>, Mention <mention@noreply.github.com> 제목: Re: [docker/for-win] [Windows10] Docker desktop is not working on startup after I changed setting for "command prompt" (#10132) 
Thanks for the report, @bugsoft337. Which version of Docker Desktop are you using? We had some problems with the legacy console before (#9770) but I thought they were fixed in the latest version.

**Comment by stephen-turner** [comment]
Ah yes, I've reproduced it now. Docker Desktop with the WSL backend cannot run if legacy console mode is set.

Thank you for the report. @usha-mandya we should add this to the docs somewhere: the WSL page? or the FAQ?
