### ISSUE TITLE
WSL 2: Dynamically mapped host ports don't work

### ISSUE THREAD

**Issue by strarsis** [docker/for-win#10131]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F166FABC-3C4A-4865-8FBB-E011F90B5C52/20210118220906
  - [x] I am using the Docker WSL2 Backend
  - [ ] I am using the Docker Hyper-V Backend

### Actual behavior
Dynamic ports are not accessible (Connection refused), only ports explictily mapped to the Docker host are accessible.
This had worked in previous Docker for Desktop releases.

### Expected behavior
Dynamic ports are mapped to the Docker host in a way that they can be used (no Connection refused)

### Information
  - Windows Version: 10.0.19042 Build 19042
  - Docker Desktop Version: 3.0.4 (51218)
  - WSL2 or Hyper-V backend?  WSL 2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
  1. Run a container with dynamically assigned host port.
  `docker-compose.yml`:
  ```yml
version: '3.7'

services:

  whoami:
    image: "containous/whoami"
    ports:
      - "80"
      - "8008:80"
  ````
  
  2. Start the container setup, notice that the dynamically assigned port is not reachable, but the explicitly assigned host port can be reached (in this example port 8008):
  Find out dynamic port: `docker-compose ps`
  a) Try to request from that dynamic port:  `wget localhost:<dynamic port>` (Connection refused)
  b) Try to request from the explictly mapped port: `wget localhost:8008` (should work)

**Comment by stephen-turner** [comment]
@strarsis Thanks for the report, but I can't reproduce the issue. With your example compose file, I can listen successfully on both ports.

**Comment by strarsis** [comment]
@stephen-turner: What can I do to help with debugging the issue? I could do a full restart and Docker purge, maybe this helps.

**Comment by strarsis** [comment]
@stephen-turner: Alright, a reboot of the system (and a Docker for Desktop update that became available right afterwards) fixed the issue.

**Comment by stephen-turner** [comment]
Very strange. Glad it sorted itself out though.
