### ISSUE TITLE
Docker for Windows update keeps enabling Hyper-V even when configured not to use it

### ISSUE THREAD

**Issue by tyntas** [docker/for-win#10148]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics - _not applicable_
  - Diagnostics ID: - _not applicable_
  - [x] I am using the Docker WSL2 Backend
  - [ ] I am using the Docker Hyper-V Backend

### Actual behavior
Docker for Windows is configured to use WSL and working well.
An update is being run.
Update enables Hyper-V

### Expected behavior
I think that either the update should ask before updating or check it's own configuration to know if HyperV should be enabled during the update.

### Information

  - Windows Version: 1909 (build 18363.1256), but i don't think it matters
  - Docker Desktop Version: 3.0, 3.0.1, 3.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Non-virtualized, bare metal

### Steps to reproduce the behavior

  1. Install clean Docker for Windows 3.0.x
  2. Configure it to use WSL2 as a backend
  3. Disable Hyper-V features on Windows
  4. Run Docker for Windows update to a newer version (e.g. 3.1)
  5. Find the update enabling HyperV during run

**Comment by stenvix** [comment]
Confirmed on windows 10:1909 docker 3.0

**Comment by weflower** [comment]
Confirmed for me, too. In fact I came here to report this issue 👍🏼 

In my org we have 3+ people using Docker Desktop, and some of them are less technical. So we're discussing whether to use the WSL2 feature, since Hyper-V needs to be re-disabled after each Docker for Win update.
