### ISSUE TITLE
System.InvalidOperationException: Failed to deploy distro docker-desktop to C:\Users\user\AppData\Local\Docker\wsl\distro: exit code: -1  stdout: Error: 0xffffffff

### ISSUE THREAD

**Issue by shikhar-yadav-by** [docker/for-win#10157]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
  - [x] I am using the Docker WSL2 Backend
  - [x] I am using the Docker Hyper-V Backend

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
This means that WSL 2 isn't correctly installed. You can follow Microsoft's instructions at http://aka.ms/wsl2-install to fix it.
