### ISSUE TITLE
https://download.docker.com/win/static/stable/x86_64/docker-17.06.1-ce.tgz zip file has wrong extension

### ISSUE THREAD

**Issue by rgl** [docker/for-win#1015]
the https://download.docker.com/win/static/stable/x86_64/docker-17.06.1-ce.tgz file is really a zip file, can you change its extension?

**Comment by friism** [comment]
@andrewhsu is looking into it, thanks for letting us know

**Comment by friism** [comment]
@rgl this is now fixes, thanks for reporting.

**Comment by friism** [comment]
You can see the available download here: https://download.docker.com/win/static/stable/x86_64/

The archive you want is this one I think: https://download.docker.com/win/static/stable/x86_64/docker-17.06.1-ce.zip
