### ISSUE TITLE
Docker Desktop v3.1.0 introduces a random ~10s delay when POSTing data with Go

### ISSUE THREAD

**Issue by charlesgiroux** [docker/for-win#10159]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - [X] I am using the Docker WSL2 Backend
  - [ ] I am using the Docker Hyper-V Backend

### Actual behavior
Using Docker Desktop v3.1.0 and the official Golang image, the Golang HTTP client "net/http" induces a random ~10 seconds lag when posting data. Sometimes the script below will complete in the expected amount of time, but mostly takes 10 seconds.

Noticed the bug when using 3rd party APIs for Mailgun (timing-out) and Stripe.

**My current solution is to use Docker Desktop v3.0.4.**

### Expected behavior
The script main.go below should complete in 100-300ms. 

### Information

Using Docker Desktop 3.1.0 for Windows WSL2 (Ubuntu-18.04):
- Cleaned / Purged data, reset to factory, bug **still** present.
- Tried with different Golang images: "golang:1.14.4", "golang:1.14.4-alpine" and "1.15.7", bug **still** present.
- Turned-off Windows 10 Virus & Threat protection + Firewall & network protection, bug **still** present.
- Tested internet connection for normal speeds 400mb/s, everything normal.
- Ran a similar test as below, but with the standard https Nodejs package and did not encounter this issue in v3.1.0...
- Uninstalled v3.1.0 and reinstalled, bug **still** present.
- Uninstalled v3.1.0 and installed v3.0.4, bug **no longer** present (same docker images).
- Ran the same as below on both Windows and MacOS (both using v3.1.0), bug only present on Windows.
- Ran the same script (main.go below) in WSL2 outside docker, bug was **not** present.

### Docker setup / Go script

Command: docker-compose -f docker-compose.yml up test

docker-compose.yml
```
version: '3'
services:
    test:
        container_name: my_go_test
        build: ./test
```

./test/Dockerfile
```
FROM golang:1.15.7

COPY ./src /testme/api
WORKDIR /testme/api
CMD go run main.go

```

./test/src/main.go
```
package main

import (
	"bytes"
	"log"
	"net/http"
	"time"
)

var client *http.Client

func init() {
	client = &http.Client{
		Timeout: time.Second * 30,
	}
}

func main() {
	log.Println("Running...")
	start := time.Now()
	res, err := client.Post(
		"https://RANDOM-URL", // any URL even if it goes 404
		"application/json",
		bytes.NewBuffer([]byte(`{"test": "sloooowww"}`)))

	if err != nil {
		log.Println(err)
	}
	defer res.Body.Close()
	elapsed := time.Since(start)
	log.Printf("HTTP POST took: %s", elapsed) // should be between 100-300ms, but randomly takes 10-11s.
}
```

**Comment by stephen-turner** [comment]
The time I've seen symptoms like this before is when there's some sort of corporate security product inserting itself on the network connection. Could that be the case with you? Although I realise that wouldn't explain why it was different with different versions with Docker.

**Comment by charlesgiroux** [comment]
@stephen-turner  I forgot to mention: I tried turning-off Windows 10 Virus & Threat protection + Firewall & network protection. This is not a corporate environment, but an at-home LAN (not connected to any corporate env).

**Comment by stephen-turner** [comment]
Hmmm, not that then. I tried to run the program myself to see if I could reproduce the problem but it crashed:
```
my_go_test | 2021/01/21 16:45:03 Running...
my_go_test | 2021/01/21 16:45:13 Post "https://RANDOM-URL": dial tcp: lookup RANDOM-URL on 127.0.0.11:53: read udp 127.0.0.1:45010->127.0.0.11:53: i/o timeout
my_go_test | panic: runtime error: invalid memory address or nil pointer dereference
my_go_test | [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x647dde]
```

**Comment by charlesgiroux** [comment]
Yeah, just change RANDOM-URL to any real url.

**Comment by charlesgiroux** [comment]
With URL https://google.com, I get: 
![image](https://user-images.githubusercontent.com/7256808/105385360-45197e80-5be1-11eb-9ba1-25e89a1fb574.png)

**Comment by stephen-turner** [comment]
I can't reproduce it. I'm consistently seeing 200ms or so.

**Comment by charlesgiroux** [comment]
Thanks for the info Stephen. I'll have to figure out what's going on with my setup.

**Comment by stephen-turner** [comment]
The weird thing is that there's not much new between 3.0.4 and 3.1.0. We do have a new Debian-based distro instead of Alpine, but that shouldn't affect this.

**Comment by charlesgiroux** [comment]
Okay...I ran: 
sudo apt update (177 packages to be updated, ooops)
sudo apt dist-upgrade

That seems to have fixed my issue.

**Comment by stephen-turner** [comment]
Strange. I still don't understand what was going on, but I'm glad you managed to fix it.
