### ISSUE TITLE
Docker failed to start

### ISSUE THREAD

**Issue by Varun2706** [docker/for-win#10165]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
  - [ ] I am using the Docker WSL2 Backend
  - [ ] I am using the Docker Hyper-V Backend

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mriffault** [comment]
Same problem here, here is my Diag ID : 470442B7-277E-4808-A3F8-7433F988A312/20210121103146

**Comment by LuddeEklund** [comment]
Same problem, I use Win10/WSL2/ Ubuntu

**Comment by mriffault** [comment]
I followed https://github.com/docker/for-win/issues/6822#issuecomment-643563276 and it fixed the docker startup issue (until I restart?... will see...)
