### ISSUE TITLE
Docker desktop 3.1.0 Bad UI

### ISSUE THREAD

**Issue by ssanri** [docker/for-win#10160]
After updating latest Docker for Windows, UI changes on dashboard made any sense at all. When logs of container is displayed, section tabs which was placed as sidebar initially, moved to top of the window ( Logs, inspect, stats, command line, stop, restart, delete ) which ideally makes sense, But when scroller is created in wrong container that makes top bar to disappear when scrolling bottom of the logs. each time when you want to restart container, you need to scroll all the way up, click restart then scroll back to bottom of the logs to see it. very inconvenient. I think it makes more sense to make top action bar sticky so it won't scroll with the log page. 

![image](https://user-images.githubusercontent.com/53793378/105247241-7abb5a80-5b42-11eb-8fe8-423b06dd6420.png)

![image](https://user-images.githubusercontent.com/53793378/105247286-8c9cfd80-5b42-11eb-9013-787c9236e841.png)

**Comment by johannesspohr** [comment]
Exactly my thoughts. In addition to that, before the update, you had a selection of containers in the docker-compose stack you're currently running on the left, which was very useful. Now you have to go back to the overview (by clicking "Containers / Apps", otherwise you'd have to scroll all the way to the top of the log to go back), where the scroll and expansion state is not remembered, open your docker-compose stack and finally select the other container.
I reverted to following logs in the terminal again, since this makes it unusable for me.

**Comment by stephen-turner** [comment]
Thanks for the report. The top bar shouldn't scroll with the logs, that's a bug. We'll fix it.

**Comment by ssanri** [comment]
and would love to see back button on top to take you back to group view instead of container groups. 

1 ![image](https://user-images.githubusercontent.com/53793378/105360399-88b2bf00-5bc6-11eb-9cf1-93fe8bcf6a93.png)

2 ![image](https://user-images.githubusercontent.com/53793378/105360450-95cfae00-5bc6-11eb-972d-10b5e49d8a65.png)

3 ![image](https://user-images.githubusercontent.com/53793378/105360516-aaac4180-5bc6-11eb-82a5-e46fedb3fa1a.png)

Clicking back button on 3rd image should take you to 2nd. currently goes all the way to initial view ( 1st )

**Comment by olympien13** [comment]
Hi, 
In addition to that pb I have a another one. Where is located the "LOGS" "STATS" and "INSPECT" tabs in my case ?
The name of my container is very long. Is there any link ? or is it a BUG too ?
Thanks 
![image](https://user-images.githubusercontent.com/20594171/105743451-d28c0400-5f3c-11eb-9389-317d46e279fb.png)

**Comment by stephen-turner** [comment]
Thanks, @olympien13, checking that one too.

**Comment by stephen-turner** [comment]
This is fixed in versions 3.2.0 and 3.2.1. Closing the ticket now.
