### ISSUE TITLE
Error occur trying to install W2L for Linux Kernel on VMware( Win 10) 

### ISSUE THREAD

**Issue by fiontsl** [docker/for-win#10162]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 91EA6939-5C8B-47FC-8070-D19ED3B4BC48/20210121041108
  - [x] I am using the Docker WSL2 Backend
  - [ ] I am using the Docker Hyper-V Backend

### Actual behavior
After installing W2L as prompted and followed step 4 and 5 to install and run W2L and restarted the VWware, an error occurrs whenever the container needs to run with Docker, or whenever I start the Docker.

### Expected behavior
Docker works and runs

### Information

  - Windows Version: Windows 10
  - Docker Desktop Version: latest as of today
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Yes, VMware

### Steps to reproduce the behavior

  1. Open VMware on Mac. Installed VS, run a solution that has Linux container. VS asks to install WSL2. Follow the link provided and download and install WSL2. Run docker and the issue occurs.
  2. ...

**Comment by stephen-turner** [comment]
Sorry, Docker Desktop is not supported in a virtual environment. It's out of our control whether it works or not: it requires Hyper-V to run inside the VM.

**Comment by StefanScherer** [comment]
@fiontsl You needed nested virtualization to be enabled, as you  mentioned VMware your *.vmx file should contain `vhv.enable = "TRUE"` to enable it. But I can't help you further if it doesn't work for you. :-)
