### ISSUE TITLE
Failed to set version to docker-desktop: exit code: -1

### ISSUE THREAD

**Issue by MrTanXin** [docker/for-win#10178]
- [✔] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [✔] I have uploaded Diagnostics
  - Diagnostics ID:63A1577F-72B4-4E7D-9857-F7B67A170912/20210122013804
  - [ ] I am using the Docker WSL2 Backend
  - [✔] I am using the Docker Hyper-V Backend

### Actual behavior
        System.InvalidOperationException:
        Failed to set version to docker-desktop: exit code: -1
         stdout: 
        N�S/ec�v�c6R�S��n0傁�O(udk�R����_{��y(u�e�v�c6R�S0

### Expected behavior
        docker can be run 
### Information

  - Windows Version: Windows 10 Enterprise Edition 20H2
  - Docker Desktop Version: 3.1.0
  - WSL2 or Hyper-V backend?  I have tried both Hyper-v and WSL2，all failed with same reason
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Double click docker icon
  2. Error
  3. me  :(

**Comment by stephen-turner** [comment]
WSL 2 is not installed correctly. You can follow Microsoft's instructions at http://aka.ms/wsl2-install to fix it.

**Comment by MrTanXin** [comment]
But I can run WSL2 correctly and I can run old version Docker correctly 
I try to follow Microsoft instructions to fix it but it cannot work too.

**Comment by MrTanXin** [comment]
I reinstall the Win10 and fix it already, thanks a lot

**Comment by stephen-turner** [comment]
Good, thanks.
