### ISSUE TITLE
Docker desktop 3.1.0 distro stopped

### ISSUE THREAD

**Issue by LuddeEklund** [docker/for-win#10172]
I use Win10 and WSL2. Can not figure out the problem.

WSL distro stopped while waiting for Lifecycle server.
  >Stdout:

  >Stderr:
2021/01/21 13:22:34 resolving /mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-wsl-cli.iso...
2021/01/21 13:22:34 copying...
Error: mounting wslCLIDest: open /mnt/host/wsl/docker-desktop-data/isocache/5f5bdf9bf2df3c62a0e3fd08e2400aaac464026abe96ac53dad3d0ba237ff671.iso: input/output error
2021/01/21 13:22:34 open /mnt/host/wsl/docker-desktop-data/isocache/5f5bdf9bf2df3c62a0e3fd08e2400aaac464026abe96ac53dad3d0ba237ff671.iso: input/output error
mounting wslCLIDest
main.doRun
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:230
main.run.func1
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:88
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:842
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:950
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).Execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:887
main.main

  - [X ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
  - [X ] I am using the Docker WSL2 Backend
  - [ ] I am using the Docker Hyper-V Backend

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by cpbotha** [comment]
I am experiencing exactly this issue.

None of the following helped:

- Re-install of docker desktop 3.3.2.
- `wsl --unregister` of docker-desktop and docker-desktop-data
- `/mnt/host/wsl/docker-desktop-data/isocache/` on docker-desktop is empty

My diagnostics ID is `C7186D28-9ED3-44CF-997E-CB131F53E677/20210504081156`

```
WSL distro stopped while waiting for Lifecycle server.
  >Stdout:

  >Stderr:
2021/05/04 08:21:28 resolving /mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-wsl-cli.iso...
2021/05/04 08:21:28 copying...
Error: mounting wslCLIDest: open /mnt/host/wsl/docker-desktop-data/isocache/dd36760f97a28ebd13840be9a0dbfdd702508e04e50c6993eee95c463c17b81d.iso: input/output error
2021/05/04 08:21:28 open /mnt/host/wsl/docker-desktop-data/isocache/dd36760f97a28ebd13840be9a0dbfdd702508e04e50c6993eee95c463c17b81d.iso: input/output error
mounting wslCLIDest
main.doRun
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:236
main.run.func1
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:91
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:842
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:950
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).Execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:887
main.main
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:33
runtime.main
	/usr/local/go/src/runtime/proc.go:225
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1371
```

**Comment by LuddeEklund** [comment]
There are issues updating Docker on windows, old files are not removed. An easy answer, which worked for me, is to use CCleaner to remove old files. Hope that solves your issue.

**Comment by cpbotha** [comment]
In my case, docker's WSL2 mode started working again after:

- I attempted to switch back to the Hyper-V, at which point I had to enable the feature (it was not enabled), and then switched to Hyper-V.
- I finally switched back to WSL2 without a hitch.

**Comment by cpbotha** [comment]
> There are issues updating Docker on windows, old files are not removed. An easy answer, which worked for me, is to use CCleaner to remove old files. Hope that solves your issue.

Thanks for reporting back! Hopefully your ccleaner tip or my hyper-v switcheroo helps someone else in the future!
