### ISSUE TITLE
Windows Dashboard Window Resize Bug

### ISSUE THREAD

**Issue by Tobias-Keller** [docker/for-win#10170]
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
  - [ x] I am using the Docker WSL2 Backend
  - [ ] I am using the Docker Hyper-V Backend

### Actual behavior
Docker Dashboard Window cant be resized on the top left corner, or on the top where no icons are.

### Expected behavior
The user should be able to resize the window on every site/corner

**Comment by MihajloNesic** [comment]
Some on MacOS

**Comment by MihajloNesic** [comment]
Same on MacOS

**Comment by Aoa77** [comment]
This is still an issue. A minor annoyance, but it seems like it should be something easy to fix or improve.
