### ISSUE TITLE
[Question] Will kubernetes get removed in future?

### ISSUE THREAD

**Issue by Luk164** [docker/for-win#10176]
Relating to kubernetes [officially dropping support for docker as a runtime](https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/), will docker desktop remove/deprecate the feature? If so, will an alternative (like docker swarm) be added as a replacement?

**Comment by stephen-turner** [comment]
No, Kubernetes will not be removed as a result of this. Docker and Mirantis have announced that we will maintain dockershim, which is the component that we need. https://www.mirantis.com/blog/mirantis-to-take-over-support-of-kubernetes-dockershim-2/
