### ISSUE TITLE
Docker with WSL integration fails to start with exit code 1

### ISSUE THREAD

**Issue by ad-on-is** [docker/for-win#10183]
As of today, Docker with WSL integration suddenly fails to start.

Docker 3.1.0
Windows 10 Build 21292

My setup is as follows.

- I have a file located at `D:\WSL\Disks\userA.vhdx`
- Then I mount it into wsl
 ```
Mount-VHD -Path "D:\WSL\Disks\userA.vhdx"
Start-Sleep -Seconds 5
wsl --mount \\.\PHYSICALDRIVE5 -p 5
```

- Inside my WSL distro (Ubuntu 20.10) the `/home/usera` folder points to `/mnt/wsl/PHYSICALDISCDRIVE5/usera`

For some reason Docker doesn't like that setup anymore. It all used to work until now.

**Comment by weflower** [comment]
Make sure that Hyper-V wasn't re-enabled with a Docker update. There's a separate issue open for that, but it was the root of my Docker failing to start too.
