### ISSUE TITLE
Docker hv-sock (vsudd) is not reachable

### ISSUE THREAD

**Issue by tneward** [docker/for-win#1019]
### Actual behavior

Installed Docker for Windows. Start Docker for Windows. After a period of time, get the "An error occurred" dialog with the message reading "Docker hv-sock proxy (vsudd) is not reachable".

### Information

Diagnostic ID: C1BD6CDD-340E-4975-87C8-6B3118B7ED8C/2017-08-18_14-04-00
This is a brand-new image of Windows10. Native host (no Parallels or VirtualBox). Nothing else installed (except for Chrome and a few other small apps like Notepad++ that I would assume have no impact).

Docker install turned on Hyper-V and restarted.

In the Hyper-V console, I can see the MobyLinuxVM being created--it runs for a while, then stops and is removed. This happens a few (2? 3? I haven't watched super-carefully because I have other things to do at the moment :-) ) times and the net result is Hyper-V is empty of all entries.

Windows "ver.exe" reports Version 10.0.14393

Logfile attached: [log.txt](https://github.com/docker/for-win/files/1235678/log.txt)

Happy to assume user error, or that this is a dupe, but honestly, there's so many issues with this as the subject I can't tell what would be a duplicate and what isn't. (Some of them are old, too, and earlier attempts to following some of the solutions there seemed to pollute my install, which was what led to the re-imaging of the machine in the first place.)

**Comment by ctmcisco** [comment]
For anyone following this ticket:

Try the following:

1. Switch or stay on Windows Containers.
2. Disable the "Start when Windows starts" setting.


![image](https://user-images.githubusercontent.com/14852041/37053107-e9a96bd8-2140-11e8-9bdf-b264980b6127.png)

3. Exit Docker application
4. restart docker services via PowerShell

get-service *docker* | Restart-Service -Force -Verbose

5. Launch Docker , Run as Admin
6. Swtich to Linux Containers.

TEST:

Reboot Windows 10
Launch Docker 
Does it work?

You can also parse the docker log in PowerShell for troubleshooting:

cat C:\Users\USERPROFILE\AppData\Local\Docker\log.txt -tail 10 -wait
