### ISSUE TITLE
Docker build failed for LCOW (diagnostics id 63D55BDE-0082-4486-AD62-F4A17C5C544D/20210125140153)

### ISSUE THREAD

**Issue by hassanalbudairi** [docker/for-win#10209]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
  - [x] I am using the Docker WSL2 Backend
  - [x] I am using the Docker Hyper-V Backend

### Actual behavior
failed to build any new LCOW images
### Expected behavior
build success
### Information

  - Windows Version: Windows Pro 10 Ver 1909 (OS build 18363.1316)
  - 
  - Docker Desktop Version:
  - Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:14:16 2020
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:26:48 2020
  OS/Arch:          windows/amd64
  Experimental:     true 
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

The deamon config is
{ "registry-mirrors": [], "insecure-registries": [], "debug": true, "experimental": true }

and my dockerfile is
FROM ubuntu:latest ENV DEBIAN_FRONTEND noninteractive RUN apt-get update && \ apt-get install -y python3 python3-dev python3-pil hugin-tools ADD generate.py /generate.py ENTRYPOINT ["python3", "/generate.py"]

I got the following error

The command '/bin/sh -c apt-get update &&     apt-get install -y python3 python3-dev python3-pil hugin-tools' returned a non-zero code:4294967295:failed to shutdown container:container c783e98680ab347d24f3c5df76cbd19b18e9c6a2652e649715d5f89d6ace5429 encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The virtual machine or container with the specified identifier is not running. (0xc0370110): subsequent terminate failed container c783e98680ab347d24f3c5df76cbd19b18e9c6a2652e649715d5f89d6ace5429 encountered an error during hcsshim::System::waitBackground:failure in a Windows system call: The virtual machine or container with the specified identifier is not running. (0xc0370110)

**Comment by stephen-turner** [comment]
If it's an hcsshim issue, then the problem must be in the upstream engine, so could you please re-file this ticket at https://github.com/moby/moby. (Sorry, I would move it if I could, but the project is not part of the docker org, so it's not possible).
