### ISSUE TITLE
docker build ssh forwarding support

### ISSUE THREAD

**Issue by slide333333** [docker/for-win#10216]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
  - [x] I am using the Docker WSL2 Backend
  - [ ] I am using the Docker Hyper-V Backend

### Actual behavior
Trying `docker build --ssh default .` (https://docs.docker.com/develop/develop-images/build_enhancements/#using-ssh-to-access-private-data-in-builds) does not work. Tried to use the `ssh-agent` from Windows 10 OpenSSH as well as from git for windows. Any connection to the `ssh-agent` when building image results in "error fetching identities: communication with agent failed"

### Expected behavior
It should work or be CLEARLY documented somewhere that it is not supported for Windows (with WSL2 backend and/or Hyper-V backend)! 

### Information
Windows 10
Docker Desktop 3.1.0 (51484) with WSL Backend
Somehow related to: https://github.com/docker/for-win/issues/167

### Steps to reproduce the behavior

  1. Dockerfile: 
     ``` 
     #syntax=docker/dockerfile:1.2
     FROM debian:latest
     RUN apt-get update && apt-get install -y openssh-client
     RUN --mount=type=ssh ssh-add -L
     ```
  2. `set DOCKER_BUILDKIT=1`
  3. run ssh-agent (git bash): eval `ssh-agent -s`
  3. docker build --ssh default .
```
 => ERROR [3/3] RUN --mount=type=ssh ssh-add -L                                                                                                                                                                                    2.3s
------
 > [3/3] RUN --mount=type=ssh ssh-add -L:
#10 1.632 error fetching identities: communication with agent failed
------
executor failed running [/bin/sh -c ssh-add -L]: exit code: 1
```

**Comment by krisklau** [comment]
Any updates on this?
