### ISSUE TITLE
Issue in running docker after installing on windows 10 

### ISSUE THREAD

**Issue by MehulKChaudhari** [docker/for-win#10211]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
  - [x] I am using the Docker WSL2 Backend
  - [x] I am using the Docker Hyper-V Backend

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...
All the pre-requisites are check and are working fine, I have installed docker for windows, and when I was trying to  run the command "docker run hello-world" in the command prompt  I got this error. I have searched on google and github issues also but I couldn't find any suitable solution for me, 

## #The error is : C:\Program Files\Docker\Docker>docker run hello-world
docker: error during connect: This error may indicate that the docker daemon is not running.: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/create: open //./pipe/docker_engine: The system cannot find the file specified.

###I have tried to on off the Bois virtualization permission,  and the subsystem for Linux in windows features, and run commands in PowerShell in admin mode  " "C:\Program Files\Docker\Docker\DockerCli.exe" -SwitchDaemon" 
and some other commands

**Comment by stephen-turner** [comment]
Possibly the network connection between the program and the docker daemon is being blocked by some corporate security software.

**Comment by MehulKChaudhari** [comment]
ohh, What can I do to resolve this?

**Comment by stephen-turner** [comment]
If it is corporate security software that is the problem, you will need to talk to your IT department.

**Comment by MehulKChaudhari** [comment]
No, Its my personal laptop. I am a student. I have a Virtualbox installed is that a problem ?

**Comment by stephen-turner** [comment]
VirtualBox installed isn't a problem, but VirtualBox running might be because it can't run with Hyper-V or WSL 2.

Are you trying to use the Hyper-V or WSL 2 backend? Is Hyper-V or WSL 2 successfully running?

**Comment by MehulKChaudhari** [comment]
yes WSL 2 is running successfully

**Comment by massimilianolili** [comment]
Hi, I have tried with the latest version of Docker Desktop, i have the same problem

**Comment by MehulKChaudhari** [comment]
Hey @massimilianolili,  I have resolved this issue by installing WSL 2, Then making that WSL 2 as a default, then running PowerShell in admin mode and used the command " dism.exe /Online /Enable-Feature:Microsoft-Hyper-V /All", reinstall docker then restart your system, Probably your good to go.

**Comment by MehulKChaudhari** [comment]
@stephen-turner Hey, Thank you soo much for the help, I have resolved the issue.

**Comment by stephen-turner** [comment]
Great, thanks for letting us know.

**Comment by MehulKChaudhari** [comment]
Sir, I am a beginner as you will have known, Could help me find some beginner friendly issues?, I would love to contribute to the community.

**Comment by stephen-turner** [comment]
Thanks for the offer. Why don't you join our community slack channel? https://www.docker.com/docker-community. There are lots of people there who are looking for community help, and you will get a good idea of the sort of questions people are asking.

**Comment by MehulKChaudhari** [comment]
I have already joined it, Which channel should I ask for help

**Comment by stephen-turner** [comment]
#docker-desktop-win is a good one for Docker Desktop. For more general questions, then #general.

**Comment by MehulKChaudhari** [comment]
Oh okay
