### ISSUE TITLE
Docker W10 WSL GPU support not working

### ISSUE THREAD

**Issue by corticalstack** [docker/for-win#10218]
- [X] I have tried with the latest version of Docker Desktop
  - [X ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
  - [X] I am using the Docker WSL2 Backend
  - [X] I am using the Docker Hyper-V Backend

### Actual behavior
I have followed the instructions as per:
[Docker for Windows GPU](https://docs.docker.com/docker-for-windows/wsl/)

This included updating windows install for windows insider dev preview ring
Updating GPU driver (GTX 1080) - driver version is 465.21
Updating WSL kernal
Ensuring Docker Windows on experimental

When I execute:
`docker run --rm -it --gpus=all nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -gpu -benchmark`

I get error message:
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request: unknown.`

### Expected behavior
Expect to get the CUDA benchmark screen as shown in the link above

### Information

  - Windows Version: 10.0.19041
  - GPU - GTX 1080
  - GPU Driver - 465.21
  - WSL updated from https://www.catalog.update.microsoft.com/Search.aspx?q=wsl
  - Docker Desktop Version: 3.1.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

Many thanks for any support

**Comment by stephen-turner** [comment]
@simonferquel Any ideas?

**Comment by simonferquel** [comment]
From the information you gave it seems you did not update to the insider build (19041 is the current GA windows version)

**Comment by corticalstack** [comment]
> From the information you gave it seems you did not update to the insider build (19041 is the current GA windows version)

My bad - double-checked, 10.0.21296 is now installed. Running the following now shows the benchmark along with GPU specs:
`docker run --rm -it --gpus=all nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -gpu -benchmark`

And running below:
`docker run --rm -it --gpus=all pytorch/pytorch:latest`

followed by:
`python -c 'import torch; print(torch.cuda.is_available())'`

returns True, indicating other packages like sentence_transformers which I need for my research will now work. 

So happy, been pulling my hair out trying different docker images, installing drivers, going back to Ubuntu in VM to compare etc. And dont need to go back to W10/Ubuntu dual boot either.

Thanks so much Docker For Win team for making this happen!

**Comment by simonferquel** [comment]
Very happy to see this feature helping to solve real problems :). Let us know if somethings don't work as expected!

**Comment by corticalstack** [comment]
> Very happy to see this feature helping to solve real problems :). Let us know if somethings don't work as expected!

Just a follow-up. Is there a roadmap date for when W10 WSL GPU will be available from W10 GA (not in preview/dev ring)? Thanks

**Comment by simonferquel** [comment]
That is a question for Microsoft! (you might want to reach @craigaloewen on Twitter)
