### ISSUE TITLE
docker-win "Not enough memory to start Docker"

### ISSUE THREAD

**Issue by MironAtHome** [docker/for-win#1021]
### Expected behavior
Docker starts normally

### Actual behavior
Docker complains of not being able to start with message "Not enough memory to start Docker".

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
--- what?
  - a reproducible case if this is a bug, Dockerfiles FTW
--- you know, I got better things to do...
  - page URL if this is a docs issue or the name of a man page
--- yeah, URL...
  - host distribution and version (Windows version, build number, etc)
--- any suggestion, what you really want... 
there is version "Windows 10"
there is version "10.0.14393 N/A Build 14393"
there is version of kernel.dll, nt.dll... heck knows what you need guys. Print out instructions and steps to get the data you need. Or I will be guess till second coming.

### Steps to reproduce the behavior
Yeah... 50 bucks an hour on w2 and I will be working with steam coming out of my ears, sugar factory boys with lasso.

  1. ...
  2. ...

**Comment by friism** [comment]
How much memory is free on your machine? Currently, Docker needs 2GB to start the VM that powers Docker Linux containers.

**Comment by MironAtHome** [comment]
1.8 GB
Is there knob to lower memory demand on start?

**Comment by MironAtHome** [comment]
Steps to resolve the trouble...

Thanks to Julien Corioland
https://blogs.msdn.microsoft.com/jcorioland/2016/10/13/getting-started-with-windows-containers/
provides steps
article "Cloud Computing, Architecture, Containers and DevOps !" 

1. On windows 10 in elevated PowerShell
Enable-WindowsOptionalFeature -Online -FeatureName containers -All
2. Check 
Get-WindowsOptionalFeature  -Online -FeatureName "Microsoft-Hyper-V"
and add if needed "Microsoft-Hyper-V"
3. In docker task bar options switch to using Windows containers.
4. Using Windows Task Manager end task for docker service -> start service

Thanks to author of next issue above for the detailed log and the comment by friism. Apparently in the default installation docker is trying to start Linux VM with 2GB of RAM and apparently my hardware configuration wasn't satisfactory to this requirement. I am not certain this will resolve all outstanding issues, but finally getting prompt "Docker is running" was a good starting point.
