### ISSUE TITLE
Include mips64le binfmt support on image

### ISSUE THREAD

**Issue by bltavares** [docker/for-win#10223]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
  - [x] I am using the Docker WSL2 Backend
  - [ ] I am using the Docker Hyper-V Backend

### Actual behavior

The current image of the system is capable of emulating many different architecture, except for MIPS.

The following Dockerfile present us an error message.

```dockerfile
FROM mips64le/debian:10
RUN echo 1
```

```
$ docker build .

Sending build context to Docker daemon   2.56kB
Step 1/5 : FROM mips64le/debian:10
 ---> 355719e0927e
Step 2/5 : RUN echo 1
 ---> [Warning] The requested image's platform (linux/mips64le) does not match the detected host platform (linux/amd64) and no specific platform was requested
 ---> Running in 32cabebf3251
standard_init_linux.go:219: exec user process caused: exec format error
The command '/bin/sh -c echo 1' returned a non-zero code: 1
```

The warning notifies that we are trying to run a mips64le image on an amd64 system, but not much more. Running with `buildx` also causes errors.

```
$  docker buildx build --platform linux/mips64le .

[+] Building 0.3s (5/7)
 => [internal] load build definition from Dockerfile                                                                                                   0.0s
 => => transferring dockerfile: 281B                                                                                                                   0.0s
 => [internal] load .dockerignore                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                        0.0s
 => [internal] load metadata for docker.io/mips64le/debian:10                                                                                          0.0s
 => CACHED [1/4] FROM docker.io/mips64le/debian:10                                                                                                     0.0s
 => ERROR [2/4] RUN echo 1                                                                                                                             0.3s
------
 > [2/4] RUN echo 1:
#5 0.255 standard_init_linux.go:219: exec user process caused: exec format error
------
error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c echo 1]: exit code: 1
```

Running `buildx ls` we can see all the platforms already availble on Docker for Windows, sadly, without MIPS.

```
$ docker buildx ls

NAME/NODE DRIVER/ENDPOINT STATUS  PLATFORMS
default * docker
  default default         running linux/amd64, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/arm/v7, linux/arm/v6
```

It would be amazing to be able to run MIPS containers from Docker for Windows, to help with embedded development and testing - not only running on cross-compilation.

### Expected behavior

Running `docker run --platform linux/mips64le mips64le/debian:10 echo hello world` would work just like running `docker run --platform linux/ppc64le ppc64le/debian:10 echo hello world`

### Information

  - Windows Version: Windows 10 - Version 2004 - Build 21296.1000
  - Docker Desktop Version: 3.1.0 (51484)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1.  `docker run --platform linux/mips64le mips64le/debian:10 echo hello world`

**Comment by stephen-turner** [comment]
I see you've also filed this upstream, which is the right place for it, so I'm going to close this copy.
