### ISSUE TITLE
Docker for Desktop Update 3.1.0 breaks docker-compose in WSL2, error: docker-credential-desktop.exe not found

### ISSUE THREAD

**Issue by ipa-bak** [docker/for-win#10243]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
  - [x] I am using the Docker WSL2 Backend
  - [ ] I am using the Docker Hyper-V Backend

### Actual behavior

Running any "docker-compose build" command fails with a strack trace:
```
Building ---censored---
Traceback (most recent call last):
  File "bin/docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 126, in perform_command
  File "compose/cli/main.py", line 302, in build
  File "compose/project.py", line 468, in build
  File "compose/project.py", line 450, in build_service
  File "compose/service.py", line 1125, in build
  File "docker/api/build.py", line 261, in build
  File "docker/api/build.py", line 308, in _set_auth_headers
  File "docker/auth.py", line 301, in get_all_credentials
  File "docker/auth.py", line 287, in _get_store_instance
  File "docker/credentials/store.py", line 25, in __init__
docker.credentials.errors.InitializationError: docker-credential-desktop.exe not installed or not available in PATH
[556] Failed to execute script docker-compose
```

The WSL2 integrations seems to be set up correctly:
```
me@BN1478:~$ which docker-compose
/usr/bin/docker-compose
me@BN1478:~$ ls -l /usr/bin/docker-compose
lrwxrwxrwx 1 root root 56 Jan 28 15:20 /usr/bin/docker-compose -> /mnt/wsl/docker-desktop/cli-tools/usr/bin/docker-compose
me@BN1478:~$ which docker
/usr/bin/docker
me@BN1478:~$ ls -l /usr/bin/docker
lrwxrwxrwx 1 root root 48 Jan 28 15:20 /usr/bin/docker -> /mnt/wsl/docker-desktop/cli-tools/usr/bin/docker
me@BN1478:~$ ls /mnt/wsl/docker-desktop/cli-tools/usr/bin -l
total 163396
-rwxr-xr-x 1 root root 71633288 Dec 28 17:15 com.docker.cli
-rwxr-xr-x 1 root root 58667008 Jan 13 10:33 docker
-rwxr-xr-x 1 root root 12218968 Jan 13 10:34 docker-compose
-rwxr-xr-x 1 root root 13725696 Jan 13 10:34 hub-tool
-rwxr-xr-x 1 root root 11071848 Jan 13 10:34 notary
me@BN1478:~/seronet-project/svp-preference-elicitation$ grep -e docker /proc/mounts
/dev/sdc /mnt/wsl/docker-desktop-data/isocache ext4 rw,relatime,discard,errors=remount-ro,data=ordered 0 0
none /mnt/wsl/docker-desktop/shared-sockets/guest-services tmpfs rw,nosuid,noexec,noatime,mode=755 0 0
none /mnt/wsl/docker-desktop/shared-sockets/host-services tmpfs rw,nosuid,noexec,noatime,mode=755 0 0
/dev/sdb /mnt/wsl/docker-desktop/docker-desktop-proxy ext4 rw,relatime,discard,errors=remount-ro,data=ordered 0 0
/dev/loop0 /mnt/wsl/docker-desktop/cli-tools iso9660 ro,relatime,nojoliet,check=s,map=n,blocksize=2048 0 0
tmpfs /mnt/wsl/docker-desktop-data/tarcache/entries/docker.tar/5eca6dbab59bc2d33b958409b703bf85fcb128c18f37599456decc851c8f89a5/containers/services/docker/tmp tmpfs rw,relatime 0 0
overlay /mnt/wsl/docker-desktop-data/tarcache/entries/docker.tar/5eca6dbab59bc2d33b958409b703bf85fcb128c18f37599456decc851c8f89a5/containers/services/docker/rootfs overlay rw,relatime,lowerdir=/containers/services/docker/lower,upperdir=/containers/services/docker/tmp/upper,workdir=/containers/services/docker/tmp/work 0 0
me@BN1478:~$ losetup                                                        
NAME SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE                                                                         DIO LOG-SEC
/dev/loop1
             0      0         1  1 /24b7ecc1e793b393f584a479e9f8d3767648a5472962e7a1c822e4885564ef4e.iso               0     512
/dev/loop0
             0      0         1  1 /mnt/host/wsl/docker-desktop-data/isocache/9577ec96a2cf7cef19768ca35f970619deadb08fa029d770ea10aadac1ef2d71.iso
                                                                                                                       0     512

```

### Expected behavior

docker-compose is able to execute docker in order to build images and run containers.

### Information

* [x] Problem is reproducible.  Can be reproduced with the most simple compose file, e.g. the one from the docker desktop tutorial 
* [x] Problem is new
* [x] Problem appeared with update to 3.1.0.  
    Identical setup on the same machine worked shortly before update and failed after update.  No other known changes have been made between the working state before the update and the failing state after the update

- Windows Version: Windows 10 Enterprise 1909, Build: 18363.1256
- Docker Desktop Version: 3.1.0.51484
- Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:  No

### Steps to reproduce the behavior
  1. Use the docker-compose file from the docker desktop tutorial and try to build the application

### work-around:
Manually edit the user's ```~/.docke/config.json``` and change the key ```credsStore``` to the empty string ``` "" ```
However, this change is regularly overridden by docker.

### Further observations

I think two distinct problem manifest themselves here:
1. The Docker Desktop update process silently changed the credential store setting in the user's docker configuration.  
    This should never happen.  The user's configuration should only be update with explicit consent of the user.
2. The user's configuration is updated to a credential store method, which is not available inside the WSL2 environment.  It is only available in the native windows environment (a ```docker-desktop-credentials.exe``` exists in the windows install path of Docker Desktop).

A further problem is, that as long as the ```credsStore``` key in the user's ```~/.docke/config.json``` is set to ```desktop.exe```, the  ```docker login``` command fails with a segmentation fault:
```
me@BN1478:~$ docker login
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x5606bdccb406]

goroutine 1 [running]:
github.com/docker/cli/cli/command.ConfigureAuth(0x5606bf70de80, 0xc0003b8820, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5606bf67d201, 0xc000292
b20, 0xc000577968)
        /go/src/github.com/docker/cli/cli/command/registry.go:128 +0x46
github.com/docker/cli/cli/command/registry.runLogin(0x5606bf70de80, 0xc0003b8820, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/docker/cli/cli/command/registry/login.go:123 +0x223
github.com/docker/cli/cli/command/registry.NewLoginCommand.func1(0xc000320840, 0x5606c07185c8, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/cli/cli/command/registry/login.go:45 +0xcc
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc000320840, 0xc0005842f0, 0x0, 0x0, 0xc000320840, 0xc00
05842f0)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:850 +0x462
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0002542c0, 0xc0005842f0, 0x1, 0x1)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:958 +0x34b
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:895
main.runDocker(0xc0003b8820, 0x5606bf67ff80, 0xc000010020)
        /go/src/github.com/docker/cli/cmd/docker/docker.go:287 +0x1d3
main.main()
        /go/src/github.com/docker/cli/cmd/docker/docker.go:298 +0xf3
```

**Comment by mbomb007** [comment]
This issue is super inconvenient, and it still happens every time I restart Docker.

**Comment by martin-tarjanyi** [comment]
Not sure if I have the same issue. But for me only removing the `credsStore` field helped and only until the next docker restart.

**Comment by mbomb007** [comment]
https://github.com/docker/compose/issues/7495

I think that the following are possible solutions:

- `docker logout`
- https://github.com/docker/compose/issues/7495#issuecomment-749088941
- Edit config.json and add `"auths": {}`

**Comment by gostega** [comment]
Would be really nice for Docker to add support for using the windows credential manager in WSL2, like how `git` does: `git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-manager.exe"`
I can't find any official or unofficial mentions of this.

**Comment by adrianlyons** [comment]
This issue has plagued me for the last few days in combination with another issue with node that for some reason requires me to restart wsl.
I can fix it with the credstore change but docker always resets it and setting the file to read only causes docker to crash on start.
Why is docker overriding a configuration file set by the user every start? I've also noticed that it causes problems with other configurations you can set in the file as based on my googling around the problem.

I'd say there are two issues here:

- WSL2 integration needs some work
- config.json should not be overridden on docker start.
