### ISSUE TITLE
Please help me!

### ISSUE THREAD

**Issue by myonaingwinn** [docker/for-win#10249]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
  - [ ] I am using the Docker WSL2 Backend
  - [ ] I am using the Docker Hyper-V Backend

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by MehulKChaudhari** [comment]
have you checked all the prerequisites? If yes try this step if you are using windows 10 home version 1909 and build 18363 and above. 

1) Run PowerShell in admin mode and run this command `dism.exe /Online /Enable-Feature:Microsoft-Hyper-V /All` this command will enable virtualization on your system. 
2) install WSL 2 and make It default using the command `wsl --set-default-version 2` 
3) then reinstall docker and then restart your system,

You are good to go.

**Comment by myonaingwinn** [comment]
Thanks for caring bro,
I turned on my firewall services after installation and it works.
Anyway, Thanks bro,
Have a nice day!

**Comment by MehulKChaudhari** [comment]
ohh nice, Welcome :)
