### ISSUE TITLE
Docker working issue with windows home

### ISSUE THREAD

**Issue by kotelawalaonly** [docker/for-win#10258]
My docker desktop does not show the advanced option under resources.
Windows version is home.
 

  - [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
  - [x] I am using the Docker WSL2 Backend
  - [ ] I am using the Docker Hyper-V Backend

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
Several options don't apply with the WSL 2 backend. The documentation makes clear which ones you should and shouldn't see. Or are you seeing / not seeing something that is different from what the documentation describes?
