### ISSUE TITLE
list of old versions to download | Ability to download old releases

### ISSUE THREAD

**Issue by hinell** [docker/for-win#1026]
Inspired by [for-mac#1120 ](../../../docker/for-mac/issues/1120) issue. 
There should be a quick and cheap way to downgrade docker version to older one
so that it would be possible to avoid emerging bugs and waiting for their resolution.

**Comment by chvndb** [comment]
Does anyone have a 17.06 edge (support for Windows Server 2016) installer lying around they can share? I am currently blocked due to #1025.

**Comment by Lucas-C** [comment]
Another link on the official website listing several old versions to download:
https://download.docker.com/win/static/stable/x86_64/

**Comment by cowlinator** [comment]
This is the page you are looking for:
https://docs.docker.com/docker-for-windows/release-notes/
It contains download links for all previous versions down to 1.12.0

**Comment by sonic1981** [comment]
The links here are useful but this should be on the main official site

**Comment by sonic1981** [comment]
I've added a issue onto the docker web page git hub to try and make this more obvious https://github.com/docker/docker.github.io/issues/10191

**Comment by stephen-turner** [comment]
Old version links are listed in the release notes, so closing this issue.
