### ISSUE TITLE
Docker failed to start Windows 10 - home

### ISSUE THREAD

**Issue by rtata01263611** [docker/for-win#10276]
![DockerStartError](https://user-images.githubusercontent.com/76165250/106675992-15c12500-6584-11eb-9e6d-e55fe3ee7a54.JPG)

**Comment by 1dropaflame** [comment]
you have to click the link and continue the install!

**Comment by Marq91** [comment]
you need to update the kernel as mentioned

**Comment by stephen-turner** [comment]
Closing this ticket, the instructions are in the error message.
