### ISSUE TITLE
Error response from daemon: Bad response from Docker engine

### ISSUE THREAD

**Issue by caveligh** [docker/for-win#1028]
### Expected behavior
Open Docker at startup
### Actual behavior
Don't open Docker
### Information
Error response from daemon: Bad response from Docker engine

   en Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning) en C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\DockerDaemonChecker.cs:línea 63
   en Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) en C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:línea 252
   en Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions) en C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:línea 182
   en Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) en C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:línea 47
   en Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) en C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:línea 145

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
29903BD4-0ACD-4760-9102-BD4A9D92F294/2017-08-22_08-23-22
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. Docker indicated an update was available. 
  2. Accept the update

**Comment by arvindshmicrosoft** [comment]
I have the same issue after trying to update to 17.07 ce rc3 today. I am using Win2016 as the host (with Linux containers) and the latest diagnostic is 843F08C3-6717-4F1C-8BB2-00A69CABD94C/2017-08-22_14-50-20.

**Comment by snoerenberg** [comment]
I've the same problems since 1-2 weeks after an update.
reinstalling including restarts does not help:

44E4BE80-0BC9-403B-9ECE-958524EE2A09/2017-08-30_07-06-35

**Comment by sdktr** [comment]
Same here

B2F7BFF4-67A8-43AD-8478-09B53210B404/2017-09-01_15-25-53

**Comment by snoerenberg** [comment]
Same with new update

44E4BE80-0BC9-403B-9ECE-958524EE2A09/2017-09-02_23-36-06

**Comment by snoerenberg** [comment]
Hi, when I start "Docker for Windows" as administrator it works.
Found here: https://github.com/docker/for-win/issues/1040
Or revert to:
`choco uninstall docker-for-windows
choco install docker-for-windows --pre --version=17.06.1.12818-edge`

**Comment by adragoset** [comment]
Same here verified today win our development windows server crashed and burned  from an unrelated failure .  Reinstalled today on server 2016. Docker will only start now if run as administrator. Cannot issue commands to docker unless running from an elevated command prompt. Additionally Docker will fail when pulling containers from an insecure registry with some form of segmentation fault… Once the pull fails docker has to be restarted as the daemon goes rouge after. Lots of regressions after the latest two releases of edge.
[docker_log.txt](https://github.com/docker/for-win/files/1278870/docker_log.txt)

**Comment by impankratov** [comment]
Same here, wish I wouldn't update to the latest version
`CE25C17D-4273-41FC-ADE7-E1371AD9C4F3/2017-10-02_18-32-02`

**Comment by dannybritto96** [comment]
D576239E-3746-40AE-AF71-50439F18D2A3/2017-10-03_22-17-24

**Comment by DarkDrim** [comment]
2D03D5FC-4C47-4787-92C0-F132E62F9AEA/2017-10-03_20-39-24

**Comment by Shadowman4205** [comment]
20D4CF94-865C-456E-AE2E-B0D956AF54042017-10-04_12-03-24 
So any solution???

**Comment by pilere** [comment]
even with reinstall ...  even with administrator ....
docker doesn't work anymore ...
2E0DC554-B7A0-49DA-8544-53A70E4FD1EB/2017-10-04_14-18-38

**Comment by mexanichp** [comment]
Same for me: E39AF7DD-2531-40FC-A711-02275CF783BE/2017-10-04_15-27-49

**Comment by dmitrywicked** [comment]
same for me: 1FDCF257-3EB2-4113-BA96-ABD0C2960798/2017-10-04_15-50-04

**Comment by mexanichp** [comment]
As a workaround found this, just downgrade version helped me!

https://github.com/docker/for-win/issues/1148#issuecomment-333677117

**Comment by java-ipgray** [comment]
This happens to me many times in windows 10 when I switch from Windows Container to Linux Container or vice versa ... all i did is... just restarted the computer and the docker is back to normal.

**Comment by sebi** [comment]
Same issue here. Docker for Windows suddenly stops working and responds with `Error response from daemon: Bad response from Docker engine` on the command line. This happens unpredictably every now and then, **multiple times a day**. Really frustrating user experience overall.

Diagnostics:
> 5D8919B2-2B29-4FF6-9101-959A402C2A56/2018-02-05_10-02-03

**Comment by Kira-Lappo** [comment]
I got the issue with ```docker build``` command, ```docker run``` works well

**Comment by stumpdk** [comment]
Same experience here. Running Docker for Windows, it is starting fine, but suddenly stops with message "Error response from daemon: Bad response from Docker engine".
Diagnostic id:  28DD3868-64B6-4EEA-BACE-63759F8DCC13/2018-03-20_21-16-29

Windows 10 build 16299.
Docker 17.12.0-ce-win47 (15139)

**Comment by mnboos** [comment]
Same here...
