### ISSUE TITLE
Docker Desktop Services depends on lanmanserver

### ISSUE THREAD

**Issue by cchepelov** [docker/for-win#10288]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F1C3123A-4CA5-40FA-9680-07BB92D2A2C6/20210203154922
  - [x] I am using the Docker WSL2 Backend
  - [ ] I am using the Docker Hyper-V Backend

### Actual behavior

* Docker Desktop requires Docker Desktop Service to start
  *  Docker Desktop Service requires the LanmanServer service to start
      * LanmanServer being disabled due to Corporate Security Policy, DDS fails to start and DD simply closes 

### Expected behavior

* Docker Desktop Service does _not_ require the LanmanServer service to start
   * Docker Desktop successfully runs

### Information

This is not new, and has been happening since after 2.0.0.3.

This keeps happening, despite promises made e.g. here https://www.docker.com/blog/new-filesharing-implementation-in-docker-desktop-windows/ ("_The new version c**an’t conflict with organisation-wide security policies**_") (emphasis in the source material)

This is a follow-up on https://github.com/docker/for-win/issues/7608 (and many others)
Multiple issues have been raised in the past, and summarily closed after 30 days, despite the original issue being still very much active.

  - Windows Version: 10.0.18363.1256
  - Docker Desktop Version: 3.1.0 (51484)
  - WSL2 or Hyper-V backend?  WSL2 as far as I know
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: NO

### Steps to reproduce the behavior
  1. ... Disable Lanmanserver and enforce this using Group Policies (GPO) 
         * (optional) refuse to even acknowledge the legitimacy of starting Lanmanserver on a developer's box 
         * (optional) threaten or imply threats to terminate whoever wants to bring the topic of perhaps sometimes allowing  Lanmanserver to start again
         * observe that the Lanmanserver service is disabled and there is nothing the user (developer) can do about it
  2. ... start Docker Desktop

**Comment by stephen-turner** [comment]
As explained in the other issue you link to, it does require the Lanman server service. We use it for named pipes. This will not change.

The sentence you quoted is out of context. That refers to the new filesharing solution not going over Samba any more. Clearly an organisation can construct a security policy that blocks Docker or any other program.

**Comment by cchepelov** [comment]
Thank you for your clarification.

"_We use it for named pipes_" should be in a FAQ, if it isn't already. 

Please  consider using another IPC mechanism if at all possible, given the amount of distrust Lanmanservice earned within security-conscious organisations. It would be easier to advocate for starting a "something" usually disabled, if that "something" was only tasked with named pipes. Unfortunately the perceived attack surface of Lanmanservice is much, much larger.

It would be helpful if Docker Desktop printed an error message in the case Lanmanserver/Docker Desktop Service can't start, explaining exactly that (directly or via a link). Currently, it just exits silently, which is bound to cause a recurrence of similar issues (spelling all that out in the hope that this helps the future disappointed would-be user figure out what happens)

**Comment by cchepelov** [comment]
(would AF_UNIX stream sockets work now that Windows supports them?)
