### ISSUE TITLE
Windows 10 Host running nanoserver container but container can't ping host or access internet

### ISSUE THREAD

**Issue by markoueis** [docker/for-win#1029]
I'm using nat for the network type. I can connect to the container using docker exec. Container can't access internet or ping host. Container has ip. 

Diagnostic uploaded
20F268B9-2D23-4E97-97AE-2DCA00749AEF/2017-08-22_13-05-01 

I'm not exactly sure if the diagnostics uploaded contain everything you need to help me debug. Let me know what else is needed.

### Expected behavior
I expect my nanoserver container to be able to ping the host and access the internet through my host.

### Actual behavior
PS C:\> ping 172.25.240.1

Pinging 172.25.240.1 with 32 bytes of data:
Request timed out.
Request timed out.

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu: 
20F268B9-2D23-4E97-97AE-2DCA00749AEF/2017-08-22_13-05-01 

  - host distribution and version (Windows version, build number, etc)
Windows 10 version 1703 Build 15063.540

### Steps to reproduce the behavior

1. Install docker for windows 10
2. pull and run microsoft/nanoserver
3. ping 8.8.8.8

**Comment by markoueis** [comment]
If i run docker pull ubuntu:16.04 and try to access the internet through that it works fine. It seems to be only windows containers problem

**Comment by markoueis** [comment]
Containers can ping each other but can't ping host

**Comment by markoueis** [comment]
I uninstalled docker + hyperv + containers and reinstalled everything and still it doesn't work

**Comment by victor-rds** [comment]
@markoueis same problem here, reinstalled everything, still no luck.
Pure Hyper-V can access without problems, docker using Linux based images also working perfectly.
I also can't ping my internal network
