### ISSUE TITLE
Issues when running docker on windows

### ISSUE THREAD

**Issue by stepkans** [docker/for-win#10305]
I am getting this error when I run this command or any command >> docker run -d -p 80:80 docker/getting-started

docker: error during connect: This error may indicate that the docker daemon is not running.: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/create: open //./pipe/docker_engine: The system cannot find the file specified.
See 'docker run --help'.

Screenshot >>> https://prnt.sc/ycu79s

  - [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: A30B021D-23E9-4150-86F3-C1D289FADB8F/20210205052144
  - [ ] I am using the Docker WSL2 Backend
  - [ ] I am using the Docker Hyper-V Backend

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by sanchez** [comment]
I have also started to receiving the same issue. It begun becoming an issue for me today and the only difference I can think of between yesterday and today was I had some windows updates I installed on my machine. The updates that were installed are as follows:

- https://support.microsoft.com/en-us/topic/february-9-2021-kb4601050-cumulative-update-for-net-framework-3-5-and-4-8-for-windows-10-version-2004-windows-server-version-2004-windows-10-version-20h2-and-windows-server-version-20h2-7d61f856-72ce-7f4c-7e43-76f8aadf2aca
- https://support.microsoft.com/en-us/topic/february-9-2021-kb4601319-os-builds-19041-804-and-19042-804-87fc8417-4a81-0ebb-5baa-40cfab2fbfde
