### ISSUE TITLE
Docker increasingly unstable then fails to start on Windows 10

### ISSUE THREAD

**Issue by adamfarquhar** [docker/for-win#10308]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
  - [x] I am using the Docker WSL2 Backend
  - [ ] I am using the Docker Hyper-V Backend

### Actual behavior
Docker has become increasingly unstable with use and now does not start. By unstable, I mean that my Windows 10 machine freezes up and must be rebooted while running a docker container. Then the machine froze shortly after Docker started. Now Docker won't start. I've purged and deleted files via the Docker GUI and rebooted but it still refuses to start.

Environment info from log file:

Version: 3.1.0 (51484)
Started on: 2021/02/05 10:28:05.577
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 2004
Build: 21301
BuildLabName: 21301.1000.amd64fre.rs_prerelease.210123-1645

**Comment by maxshugar** [comment]
I'm having the same issue!

**Comment by survivant** [comment]
I have also some issue since I installed build 21301 .  same setup as describe in the issue.
