### ISSUE TITLE
intermittent issue: "Unsupported signal: <nil>. Discarding.." pending to the return from "docker run" on latest windows docker from master.dockerproject.org

### ISSUE THREAD

**Issue by bingbing8** [docker/for-win#10303]
- [X ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
  - [ ] I am using the Docker WSL2 Backend
  - [ ] I am using the Docker Hyper-V Backend

### Actual behavior
This is an intermittent issue. Sometimes, "unsupported signal: <nil>. Discarding.." is pending to the return from "docker run" on latest windows docker from master.dockerproject.org
### Expected behavior
no pending message
### Information

  - Windows Version: it repros on any version of host both server and client.  server2019, Windows Server 1909, Windows Server 1903, Windows Server 20H2, Windows Server 2004
  OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19042 N/A Build 19042
  - Docker Desktop Version: 
  Client: Docker Engine - Community
 Version:           master-dockerproject-2021-02-03
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        70a00157f1
 Built:             Wed Feb  3 23:58:43 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          master-dockerproject-2021-02-03
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       8d31795
  Built:            Thu Feb  4 00:08:25 2021
  OS/Arch:          windows/amd64
  Experimental:     true
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Yes, inside a VM. did not repro on physical machine
  output from systeminfo:
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

### Steps to reproduce the behavior

  1. docker pull mcr.microsoft.com/windows/nanoserver:20H2-KB4598242
20H2-KB4598242: Pulling from windows/nanoserver
2ddfbf39b1d8: Already exists
Digest: sha256:b0a754e60c8fdf311b29db7d871452a431c4b86ae4730450b6fe320da533e31e
Status: Downloaded newer image for mcr.microsoft.com/windows/nanoserver:20H2-KB4598242
mcr.microsoft.com/windows/nanoserver:20H2-KB4598242
  2. C:\>docker run --isolation hyperv --rm mcr.microsoft.com/windows/nanoserver:20H2-KB4598242 cmd /k echo hello
hello

C:\>Unsupported signal: <nil>. Discarding.

C:\>docker run --rm mcr.microsoft.com/windows/nanoserver:20H2-KB4598242 cmd /k echo hello
hello

C:\>Unsupported signal: <nil>. Discarding.

**Comment by stephen-turner** [comment]
Does this happen on other containers or just that one? If it's just that one container, it should probably be reported to Microsoft rather than us.

**Comment by bingbing8** [comment]
It happens on other containers too.

**Comment by james-cxx** [comment]
This issue is not unique to Windows.  I'm seeing this same message in a pure linux environment when running scripts via ssh where the remote `.sh` script is calling `docker run`, e.g. `ssh somehost "./myscript.sh"`

**Comment by sachet-synapsefi** [comment]
try interpreters. maybe it is using python2 vs python3 vs pypy from your `scripts.sh` file.

**Comment by vadim-kovalyov** [comment]
Have exact same issue as above on Linux agent in Azure Pipeline when trying `docker run` via `ssh` on an internal host.

**Comment by logopk** [comment]
Update to 20.10.5, solved my issues

**Comment by bingbing8** [comment]
The message still show on bits master-dockerproject-2021-05-04

**Comment by AmirHosseinSaadatmand** [comment]
I had this issue. this error occurred because of CMD runtime error in my Dockerfile.

**Comment by bingbing8** [comment]
the error still show at master-dockerproject-2021-05-09
Docker Engine - Community

**Comment by MPLew-is** [comment]
The version you posted is older than [the fix](https://github.com/docker/cli/pull/2986), which just got merged last week. Try updating to a newer version and check if you still see the error.

**Comment by bingbing8** [comment]
@MpLew-is  I downloaded the latest from https://master.dockerproject.org/. Which is master-dockerproject-2021-05-09.
Where can I download the latest version?

**Comment by MPLew-is** [comment]
Nightly builds aren’t available anymore (contrary to [the documentation](https://docs.docker.com/engine/install/binaries/#install-static-binaries)), and 20.10.7 hasn’t been released yet so you’ll probably have to build from source yourself.

**Comment by bingbing8** [comment]
@MPLew-is, that is good. Could you help me to confirm the official way to get latest released version of docker for windows? or any other way? Thanks!
Install-Module -Name DockerMsftProvider -Repository PSGallery -Force
Install-Package -Name docker -ProviderName DockerMsftProvider -Force

**Comment by MPLew-is** [comment]
Sorry, I don't deal with Docker for Windows at all, I'm just following this issue since I've been having the same problem on Linux.
