### ISSUE TITLE
Failed to set version to docker-desktop: exit code: -1

### ISSUE THREAD

**Issue by jmawebco** [docker/for-win#10348]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 667A58B7-E455-4DE3-82C0-01BC3D6F84CA/20210209171313

### Actual behavior
Docker fails to start 
### Expected behavior
Docker to start properly
### Information

  - Windows Version: 10 Enterprise
  - Docker Desktop Version: Latest
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
This error means that WSL 2 is not installed correctly. Please follow Microsoft's instructions at https://aka.ms/wsl2-install
