### ISSUE TITLE
Containers not running using Docker for Windows

### ISSUE THREAD

**Issue by tommychandz** [docker/for-win#10343]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 330315D8-8F8A-4AEE-B0E4-41EED5A6A248/20210209053533

### Actual behavior
When I opened the Docker for Windows, it said that No Containers Running
### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
I'm a bit confused, have you started any containers? It's normal to get the message "No Containers Running" the first time you run the program.

**Comment by tommychandz** [comment]
Yes, i got No Containers Running

how to get it working ?

just for your information : 

it says 

No containers running
Try running a container: Copy and paste this command into your terminal and then come back

docker run -d -p 80:80 docker/getting-started

**Comment by tommychandz** [comment]
![docker](https://user-images.githubusercontent.com/78782982/107391680-87bcdf80-6b2b-11eb-8f82-45df5a77376f.png)
here is the pic of my Docker...

**Comment by stephen-turner** [comment]
Yes, this is normal. Try typing the command that it says into a terminal and you will create a container.

If you're new to Docker, I also recommend the Quick Start Guide (and the tutorial that it launches). You can find that in the whale menu (in the system tray).

**Comment by tommychandz** [comment]
where i can start typing ?
because i dont see the place that i can type.

but the problem solved

i just reinstalled it again, because the first the I installed Docker, my WSL 2 wasn't ready...

i mean the Installation not yet 100% so the tutorial didnt show up

**Comment by stephen-turner** [comment]
You can type docker commands into any PowerShell or cmd.exe terminal.
