### ISSUE TITLE
Docker fails to start in Windows 10

### ISSUE THREAD

**Issue by nathannis** [docker/for-win#1035]
### Expected behavior
docker will start running

### Actual behavior
docker is starting takes several minutes and then fails.  Trying to start docker again gives the same result.

### Information
AA96-157C6A4A3B55/2017-08-24_14-27-16 is a diagnostic ID that I uploaded explicitly from the Diagnose & Feedback menu.  In the steps to reproduce will be another more recent one from when I reproduced the issue.

This was happening before I installed the latest version, and continues after installing the latest version.

Reset to Default settings does not help
**Docker version**

```
Client:
 Version:      17.07.0-ce-rc4
 API version:  1.31
 Go version:   go1.8.3
 Git commit:   fe143e3
 Built:        Tue Aug 22 22:24:28 2017
 OS/Arch:      windows/amd64
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.31/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

**Information about my computer**
```
OS Name	Microsoft Windows 10 Pro
Version	10.0.14393 Build 14393
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	XXXXXXX
System Manufacturer	LENOVO
System Model	20FN002KUS
System Type	x64-based PC
System SKU	LENOVO_MT_20FN_BU_Think_FM_ThinkPad T460
Processor	Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz, 2808 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date	LENOVO R06ET38W (1.12 ), 6/1/2016
SMBIOS Version	2.8
Embedded Controller Version	1.08
BIOS Mode	Legacy
BaseBoard Manufacturer	LENOVO
BaseBoard Model	Not Available
BaseBoard Name	Base Board
Platform Role	Mobile
Secure Boot State	Unsupported
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.14393.1378"
User Name	XXXXXXXXXXXXX
Time Zone	Central Daylight Time
Installed Physical Memory (RAM)	16.0 GB
Total Physical Memory	15.4 GB
Available Physical Memory	10.4 GB
Total Virtual Memory	17.8 GB
Available Virtual Memory	12.2 GB
Page File Space	2.38 GB
Page File	C:\pagefile.sys
A hypervisor has been detected. Features required for Hyper-V will not be displayed.	
```

call stack 
```Error response from daemon: Bad response from Docker engine
   at Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\DockerDaemonChecker.cs:line 63
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 252
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 123
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
```

### Steps to reproduce the behavior

  Turn on my computer, See "Docker is starting..." icon in my system tray (bottom right).  Eventually it will fail.  Docker system tray icon will be RED.  Right click icon, quit docker.  Run Docker for Windows and icon will come back as "Docker is starting...".  Eventually it will fail (again)
Another crash report submitted...
013B727D-C5BC-419D-AA96-157C6A4A3B55/2017-08-24_14-33-02

**Comment by nathannis** [comment]
I believe this might be the same as other issues, like #1027

**Comment by nathannis** [comment]
[log.txt](https://github.com/docker/for-win/files/1250055/log.txt)

[DebugInfo-2017-08-24_14-33-02.txt](https://github.com/docker/for-win/files/1250056/DebugInfo-2017-08-24_14-33-02.txt)

**Comment by nathannis** [comment]
There are some log files I am willing to upload if necessary

**Comment by hinell** [comment]
Have you tried to start it as administrator?

**Comment by nathannis** [comment]
Trying to start Docker as administrator (start menu -> search docker -> Right click "Docker for Windows" -> Run as Administrator)  seems to have the same result

Error:
013B727D-C5BC-419D-AA96-157C6A4A3B55/2017-08-27_11-14-34

Docker icon in system tray is still Red and says 
Error response from daemon: Bad response from Docker engine

Running the command line as administrator yields the same result as before 

```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>docker info
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.31/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

C:\WINDOWS\system32>docker version
Client:
 Version:      17.07.0-ce-rc4
 API version:  1.31
 Go version:   go1.8.3
 Git commit:   fe143e3
 Built:        Tue Aug 22 22:24:28 2017
 OS/Arch:      windows/amd64
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.31/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

C:\WINDOWS\system32>
```

FYI I have been running docker on this machine without problems for at least a year on the "beta" versions and installing docker updates whenever they pop up.

**Comment by ebriney** [comment]
We just release a new version (17.09.0-ce-rc2-win29) that should fix the issue.
Can you test it and close the issue if it works?

**Comment by nathannis** [comment]
It is now working again.  Thanks.

docker version
Client:
 Version:      17.09.0-ce-rc2
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   363a3e7
 Built:        Thu Sep 14 01:52:49 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.0-ce-rc2
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   363a3e7
 Built:        Thu Sep 14 01:58:47 2017
 OS/Arch:      linux/amd64
 Experimental: true
