### ISSUE TITLE
DOCKER-USER and DOCKER iptables chains not installed for WSL2

### ISSUE THREAD

**Issue by robinlacey** [docker/for-win#10355]
Docker Desktop does not install DOCKER-USER and DOCKER chains as documented: https://docs.docker.com/network/iptables/

### Steps to reproduce the behavior
  1. Install Docker Desktop 
  2. Check iptables by running `sudo iptables -S` or `sudo iptables -L` inside WSL2 
  3. No DOCKER or DOCKER-USER chains: 

**Note** : added `"iptables": true` to Docker engine config to be be certain even though it should be enabled by default.

**Comment by stephen-turner** [comment]
The very first two words of the page you link to are "On Linux, ...". It's not applicable on a Windows machine.
