### ISSUE TITLE
Docker will not start

### ISSUE THREAD

**Issue by zazen000** [docker/for-win#10356]
- [ x] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 1CF49FB9-E2FB-46FA-BAF9-058B2CBC1D2C/20210210191746

### Actual behavior
System.InvalidOperationException: Failed to deploy distro docker-desktop to C:\Users\mount\AppData\Local\Docker\wsl\distro
- folder is empty

### Expected behavior
Program should start

### Information

  - Windows Version: Windows 10 Pro v. 1909
  - Docker Desktop Version: Don't know, latest download
  - WSL2 or Hyper-V backend?  both
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Steps to reproduce the behavior

  1. ...click on Docker Desktop icon
  2. ...

**Comment by stephen-turner** [comment]
It looks like you haven't set up WSL 2. Please follow Microsoft's instructions at http://aka.ms/wsl2-install
