### ISSUE TITLE
Issue installing Docker Desktop in virtualized VM windows

### ISSUE THREAD

**Issue by c5232936** [docker/for-win#10369]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
Docker Desktop is not supported in a virtualised environment. It's out of our control whether it works or not: it depends whether the outer hypervisor supports Hyper-V or WSL 2 running inside.
