### ISSUE TITLE
Docker on Windows takes 12min to start

### ISSUE THREAD

**Issue by LukaPivk** [docker/for-win#10363]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 7A1606B2-F3F3-4720-9CCB-D25D16FFB668/20210211090947

### Actual behavior

If I have Ethernet cable connected to my PC and turn on my PC docker start with normally.
if I only have Wi-Fi connection docker takes 12min to start up 

### Expected behavior

In both cases docker should start normally

### Information

  - Windows Version:
  - Docker Desktop Version: 3.1.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

Things I tried so far:
- Reinstall WSL2
- Reinstall ubuntu distro
- Reinstall docker
- Try docker 2.5.0.1
- Disabling Wi-Fi
- Disabling Ethernet
- Making bridge over Wi-Fi and Ethernet 
- Enable Hyper-V
- Remove and add 

### Steps to reproduce the behavior
  1. Reboot a PC with Ethernet cable disconnected
  2. Start Docker
  3. Takes 12min to start

**Comment by mazahner** [comment]
Same issue here!
