### ISSUE TITLE
On Windows 10 WSL2 it's completely  unusable

### ISSUE THREAD

**Issue by 0x80085** [docker/for-win#10368]
- [x ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

Dockes does not work at all with WSL2 it either hangs in starting or appears to be started but doesn't accept commands or crashes when trying to create pipes

This WSL2 is even worse than just using hyper V

1 It's a PITA to install, if you even manage to get it right
2 the troubleshooting docs are plain terrible
3 There is NO, literally 0 reasons to move to this. Its way slower, the config is terrible, the docker dashboard is plain useless, and WSL2+docker takes a million days to install (and then it just doesn't even work)

 How is gods name is this the preferred way to run docker on windows?
 
 It was already terrible but somehow there was a need to it layer with a even more unusable and immature technology so to break docker-for-win even further?.
 
 This is just terrible, I refuse to believe people thought this is a good way to 
 
### Expected behavior

It just installs and works properly and I don't have to shed bloody tears or wait 30mins for a docker commands to even give me output or some error logs.

### Information

  - Windows Version: win0
  - Docker Desktop Version: latest
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Steps to reproduce the behavior

  1. Try and install it 
  2. try and run  it
  3. you are now 2 months further and have started taking heavy anti-depressants as a result of a burn out
  4. Just looking at a whale prompts you to collapse into a fetal position and start crying like a child
  
  2020, this is the state of windows development environments. Take a good look at it and walk away now you still can.

**Comment by stephen-turner** [comment]
I'm closing this ticket because it's doesn't contain anything actionable, it's just a rant.
