### ISSUE TITLE
docker - pi-consensus

### ISSUE THREAD

**Issue by 130384** [docker/for-win#10373]
I use docker to run blockchain block with pi network, I want to report this error in pi-consensus section. Please help and how to fix it !

self.flush()

File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 64, in flush

self.stream.flush()

IOError: [Errno 5] Input/output error

Traceback (most recent call last):

**Comment by stephen-turner** [comment]
This looks like a problem in the Pi code, not in Docker Desktop.
