### ISSUE TITLE
Docker not starting on Windows 10  it stays on "Docker is starting....." Forever.

### ISSUE THREAD

**Issue by dhartitrivedi** [docker/for-win#1037]
### Expected behavior
Docker should start
### Actual behavior
Docker is starting......
### Information

A diagnostic was uploaded with id: B858BE2B-0EA6-47EA-984F-EF814684E7CF/2017-08-24_17-50-01

After 2 hours
A diagnostic was uploaded with id: B858BE2B-0EA6-47EA-984F-EF814684E7CF/2017-08-24_20-07-14

Docker does not start. I have tried re-installing docker and everything related on my windows 10 professional version. The only last thing I have not tried is re-image my windows machine. I would really like to avoid it as I have so many other software running fine without any issue.

System Info:
Windows 10 PRO
Intel Core i5-2410M 2.30 GHz
System Type: 64 bit, x64 based processor
Version 1607
OS Build 14393.1593

### Steps to reproduce the behavior

  1. Click on docker icon to start
  2. Docker remains in docker is starting state

**Comment by FFLSH** [comment]
I had a similar issue because VSTS build agent services were started on system startup and were locking something the docker processes needed, although in my case Docker did crash after a while. Maybe try stopping all services except system services and see if it works then.

**Comment by dhartitrivedi** [comment]
Thank you for response. I tried everything and I am thinking it is not going to work on my machine due to OS platform and multiple things I am unable to pin point after trying various solutions. I have started using docker tool box and much happier now.
