### ISSUE TITLE
Unable to run docker gpu for wsl2, getting  OCI runtime create failed

### ISSUE THREAD

**Issue by AnuragYadav171** [docker/for-win#10379]
Steps followed from : https://docs.docker.com/docker-for-windows/wsl/

root@DESKTOP-5A67SBM:/home/anurag# docker run --rm -it --gpus=all nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -gpu -benchmark
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request: unknown.
root@DESKTOP-5A67SBM:/home/anurag#
root@DESKTOP-5A67SBM:/home/anurag#
root@DESKTOP-5A67SBM:/home/anurag# sudo docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request: unknown.

**Comment by stephen-turner** [comment]
Do you have the correct Insiders build of Windows?

**Comment by AnuragYadav171** [comment]
Hi Stephen,

Thanks for your response !

After getting the latest Insiders build (21K), I am able to access gpu from docker within wsl2.
Also had to install CUDA-driver 460 within ubuntu wsl2 and add below lines to mount cgroup
sudo mkdir /sys/fs/cgroup/systemd
sudo mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd
(not sure why had to mount cgroup additionally )
Is it the usual approach or I am missing some standard approach ?

However I am not able to access GPU from docker desktop (outside wsl2).
Is GPU support from Docker Desktop containers still not available, or I am missing something.?

Appreciate your efforts !

**Comment by stephen-turner** [comment]
No, it's not available on Hyper-V, only WSL 2.

**Comment by stephen-turner** [comment]
https://docs.docker.com/docker-for-windows/wsl/#gpu-support should give sufficient steps for installing it.
