### ISSUE TITLE
[Error] [WSL2] [Docker] [Ubuntu 20.04 LTS] WSL distro stopped while waiting for Lifecycle server.

### ISSUE THREAD

**Issue by geneno99** [docker/for-win#10374]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  
  - Diagnostics ID:  DF0A297F-1CD2-4489-B031-8249ACF49205/20210213102214

### Actual behavior
>WSL distro stopped while waiting for Lifecycle server.
  >Stdout:

  >Stderr:
2021/02/13 10:22:10 resolving /mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-wsl-cli.iso...
Error: mounting wslCLIDest: stat /mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-wsl-cli.iso: no such file or directory
2021/02/13 10:22:10 stat /mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-wsl-cli.iso: no such file or directory
mounting wslCLIDest
main.doRun
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:230
main.run.func1
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:88
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:842
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:950
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).Execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:887
main.main
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:30
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374
### Expected behavior
- This my first time seeing this error after restarting my machine so the docker must run although I enabled docker to start automatically after opening my machine

### Information

  - Windows Version: Windows 10 Home Single Language
  - Docker Desktop Version: Latest version
  - WSL2 or Hyper-V backend?  WSL 2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

**Comment by kratkyzobak** [comment]
Hi,
had same issue, uninstalling latest Windows update (https://support.microsoft.com/cs-cz/topic/february-9-2021-kb4601319-os-builds-19041-804-and-19042-804-87fc8417-4a81-0ebb-5baa-40cfab2fbfde) solved it. Hope it will help you too.

**Comment by geneno99** [comment]
Solved by doing --wsl-shutdown and
