### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by NUNIDEcainiao** [docker/for-win#10381]
Version: 3.1.0 (51484)
Sha1: 04f280b1648e29845ae5734cfcc14796c92f3de2
Started on: 2021/02/14 15:17:40.135
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 2009
Build: 19042
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\ProgramData\DockerDesktop\service.txt
CommandLine: "C:\Program Files\Docker\Docker\com.docker.service"
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[15:17:40.231][DockerService     ][Info   ] Starting service
[15:17:41.321][DockerService     ][Info   ] Stopping service

**Comment by NUNIDEcainiao** [comment]
Component CommunityInstaller.AutoStartAction failed: 尝试执行未经授权的操作。
   在 CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()

**Comment by chenmenghui** [comment]
> 
> 
> Component CommunityInstaller.AutoStartAction failed: 尝试执行未经授权的操作。
> 在 CommunityInstaller.InstallWorkflow.d__29.MoveNext()
> --- 引发异常的上一位置中堆栈跟踪的末尾 ---
> 在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> 在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> 在 CommunityInstaller.InstallWorkflow.d__23.MoveNext()



> 
> 
> Component CommunityInstaller.AutoStartAction failed: 尝试执行未经授权的操作。
> 在 CommunityInstaller.InstallWorkflow.d__29.MoveNext()
> --- 引发异常的上一位置中堆栈跟踪的末尾 ---
> 在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> 在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> 在 CommunityInstaller.InstallWorkflow.d__23.MoveNext()

我也遇到过这样的问题，之后把联想电脑管家卸载掉就可以装了~~~

**Comment by apple-ouyang** [comment]
> > Component CommunityInstaller.AutoStartAction failed: 尝试执行未经授权的操作。
> > 在 CommunityInstaller.InstallWorkflow.d__29.MoveNext()
> > --- 引发异常的上一位置中堆栈跟踪的末尾 ---
> > 在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> > 在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> > 在 CommunityInstaller.InstallWorkflow.d__23.MoveNext()
> 
> > Component CommunityInstaller.AutoStartAction failed: 尝试执行未经授权的操作。
> > 在 CommunityInstaller.InstallWorkflow.d__29.MoveNext()
> > --- 引发异常的上一位置中堆栈跟踪的末尾 ---
> > 在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> > 在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> > 在 CommunityInstaller.InstallWorkflow.d__23.MoveNext()
> 
> 我也遇到过这样的问题，之后把联想电脑管家卸载掉就可以装了~~~

我没卸载，关闭之后就能安装了。我的天，垃圾联想管家，我还去关闭power服务。

**Comment by NUNIDEcainiao** [comment]
天啊原来是这个原因，垃圾联想管家，害我重开了一个Linux

**Comment by wanjinhang** [comment]
害的我好苦啊
