### ISSUE TITLE
Docker won't start containers after win 10 shutdown and power up.

### ISSUE THREAD

**Issue by relnah** [docker/for-win#1038]
### Expected behavior
After shuting down win 10 normally and with a working docker running, docker should be running as normal after powering up win 10.

### Actual behavior
Starting containers fails with: Error response from daemon: Cannot restart container my_container: driver failed programming external connectivity on endpoint my_container (782f444833c57027050a58f8c0302473f76d9029a50944960d13c6ed940a4392): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:49161:tcp:172.17.0.2:1521: input/output error

docker compose up hangs.

Restart of docker engine will make it work again.

### Information

Diagnostic ID 18D5608F-3086-460D-BD15-84F84F2C55D6/2017-08-25_08-09-32

Docker info:
Version 17.06.1-ce-win24 (13025)
Channel: stable
54dc09c

Win 10 info:
Edition: Windows 10 Enterprise x64
Version: 1703
OS Build: 15063.540
CPU: Inter Core i7-6600U 2.6GHz
RAM: 16 GB

### Steps to reproduce the behavior

  1. Start windows. Start docker and check "Start docker when you login".
  2. Confirm docker is working as normal.
  3. Do normal shutdown of windows.
  4. Start up windows.
  5. Confirm that docker has started.
  6. Try starting a container. This fails with above mentioned problems.
  7. Restart Docker. Starting containers work again.

**Comment by relnah** [comment]
Still having this issue after latest docker and latest Win 10.
Disgnostic id: 18D5608F-3086-460D-BD15-84F84F2C55D6/2017-10-26_08-42-13
Docker version:
Version 17.09.0-ce-win33 (13620)
Channel: stable
8c56a3b

Win version:
Win 10 info:
Edition: Windows 10 Enterprise x64
Version: 1709
OS Build: 16299.19
CPU: Inter Core i7-6600U 2.6GHz
RAM: 16 GB

**Comment by shillner** [comment]
Hi, having the same issue on my machine. Settings are nearly identical to the ones of @relnah.
After shutdown or logout with running Docker for Windows the next docker startup is pretty fast but containers won't start. Only restarting docker helps at this point.

**Comment by DirtyJerz** [comment]
It seems the containers are still running ($docker ps) but the ports are no longer exposed (netstat -an). This is kinda frustrating and makes a multi-user or consecutive-session scenario inoperative.

**Comment by DirtyJerz** [comment]
Upon further review, if I disconnect the container form the network ($docker network disconnect bridge <containerName>)  and reconnect ($docker network connect bridge <containerName>) the port is remapped to the host and the container is accessible.

**Comment by relnah** [comment]
Same issue after latest update:
Version 17.09.1-ce-win42 (14687)
Channel: stable
3176a6a

diag id:
18D5608F-3086-460D-BD15-84F84F2C55D6/2018-01-09_07-41-17

**Comment by relnah** [comment]
And still here:
Version 17.12.0-ce-win47 (15139)
Channel: stable
9c692cd

Error response from daemon: Cannot restart container xxxxx: driver failed programming external connectivity on endpoint xxxxx (bb96658514789875b9aabda58ee4312d26cabab216c516f34bcf34075b1db9a0): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:49161:tcp:172.17.0.2:1521: input/output error

Diag:
18D5608F-3086-460D-BD15-84F84F2C55D6/2018-01-18_07-58-02

**Comment by kbeaskoetxea** [comment]
Exactly the same issue here, I have to restart it whenever I shut down - power up my PC.

Docker info:
Version 17.12.0-ce-win47 (15139)
Channel: stable
9c692cd

Win 10 info:
Edition: Windows 10 Pro
Version: 1709
OS Build: 16299.192
CPU: Inter Core i5-7200U 2.5GHz
RAM: 12 GB

**Comment by fiture** [comment]
Same issue.

```
Error response from daemon: Cannot restart container xxx: driver failed programming external connectivity on endpoint lite (b7974e1da9cef2c73e75dcb7f6452cb753675e1c63feab82a4ccb433a5c337fe): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:8000:tcp:172.17.0.2:8000: input/output error
```

**Comment by smiron** [comment]
6 months later and I still have this issue. Hope they go bankrupt FFS

**Comment by jenspettersson** [comment]
Same issue here. Shutting down Windows 10 with Docker For Windows running, but not set as "Start docker on login".

After restart I start Docker for Windows manually and my containers that should start automatically starts (a RabbitMQ container). However, it's not accessable and if I try to restart I get the same "driver failed programming..." error... I have to stop Docker for Windows and start it again.

**Comment by dongshengYoung** [comment]
when i sign out docker ,then sign in, the container can't 

just quit docker and restart docker ,the container goes well.

my OS is win10

maybe restarting docke is a helpful way to solve problems of windows

**Comment by Diedzz** [comment]
same here, always have to restart docker after loging in to Win.

**Comment by LeslieMurphy** [comment]
Is this a Docker issue, or a Hyper-V issue?  Not sure. 

See https://forums.docker.com/t/overlay-network-broken-after-resuming-from-sleep/37376

**Comment by jannik2b** [comment]
same problem here

**Comment by Christowiak** [comment]
same problem here

**Comment by fcavaco** [comment]
same problem here

**Comment by ramzgt** [comment]
I have the same issue as well. Frustrating.

**Comment by tkallevik** [comment]
I also have the same problem.

**Comment by Christowiak** [comment]
i have found a solution on a other thread. i dont now the thread, but the problem relies on the **hybrid shutdown mode** from the lastest win 10 updates. After disable it under energy options, the problem is solved for me.

**Comment by kkajdd** [comment]
Still it didn't work. The workaround is to restart the docker after win10 boot up and this resolved the issue.

**Comment by fiture** [comment]
As @Christowiak  say, Turn off  `fast startup` works for me.
**Uncheck** `Turn on fast startup` and enjoy!
Control Panel > Hardware and Sound > Power Options > System Settings
![windows 10 fast startup](https://i.imgur.com/AJrjkTk.png)

**Comment by quayal** [comment]
I have the same issue, only that I can't see any containers; docker ps returns nothing

**Comment by cchance27** [comment]
docker ps -a your containers are probably stopped still you''ll need to start them unless you set them to auto-restart

**Comment by kbeaskoetxea** [comment]
Yep. As @Christowiak said, I turn off Windows' fast startup and it goes fine.

**Comment by relnah** [comment]
Turning off OS features on my computer just to get Docker to work normally isn't really a soulution. A temporary workaround perhaps. So the issue is still valid.

**Comment by ruifigueira** [comment]
I couldn't find any UI to disable the hybrid shutdown mode as @Christowiak pointed out, so I went directly to regedit and created a `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\DisableAutomaticRestartSignOn` key (`DWORD` type) with value 1 and it seems to be working fine now.

More details on that property can be found in [Winlogon Automatic Restart Sign-On (ARSO)
](https://docs.microsoft.com/en-us/windows-server/security/windows-authentication/winlogon-automatic-restart-sign-on-arso).

**Comment by LindaLawton** [comment]
> C:\Development>docker run -p 5001:5000 --name Ids1 --env ASPNETCORE_ENVIRONMENT=Development" -d ids
>
> bd50f2c5c8f967516807f9fe417c08e7961d38dddbbe1ad8cd7762ecf213c2e2
>
> docker: Error response from daemon: driver failed programming external connectivity on endpoint Ids1 (bfe54f7fc6cbbf29cf817ff4bce57013d3d4cdbfae0431ee5ddaf65179c4e9d6): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:5001:tcp:172.17.0.2:5000: input/output error.

**Comment by 99linesofcode** [comment]
For those of you who struggle to find the option to enable / disable `fast startup` like @ruifigueira. Its there but a tad hidden. No need to regedit 😉 

1. Go to `Control Panel`
1. Find `Power Options`
1. Click on `Choose what the power button does` in the sidebar on the left.
1. Click on `Change settings that are currently unavailable` to allow checking / unchecking options under `shutdown settings`
1. Toggle `Turn on fast startup`

**Comment by ruifigueira** [comment]
@99linesofcode, thanks a lot! It is now working properly at last (my `regedit` "solution" was no good for me after all...)

Here's a screenshot of steps described by @99linesofcode :

![image](https://user-images.githubusercontent.com/1374559/39572039-988064fc-4ec5-11e8-91cc-606fab2f5a9f.png)

**Comment by andrei-ivanov** [comment]
Any chance for a proper fix?

**Comment by johngeoffrey** [comment]
Yes it's good to have a work around but a proper solution would be best

**Comment by ljay79** [comment]
Hi there.

Ich have the same issue on my Windows 10 Pro host with Docker for Windows.
Fast startup is already and has been always active for me.

I do always have to restart Docker right after first windows host startup :(

Docker info:
```
Containers: 6                                                                            
 Running: 0                                                                              
 Paused: 0                                                                               
 Stopped: 6                                                                              
Images: 15                                                                               
Server Version: 18.03.1-ce                                                               
Storage Driver: overlay2                                                                 
 Backing Filesystem: extfs                                                               
 Supports d_type: true                                                                   
 Native Overlay Diff: true                                                               
Logging Driver: json-file                                                                
Cgroup Driver: cgroupfs                                                                  
Plugins:                                                                                 
 Volume: local                                                                           
 Network: bridge host macvlan null overlay                                               
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog           
Swarm: inactive                                                                          
Runtimes: runc                                                                           
Default Runtime: runc                                                                    
Init Binary: docker-init                                                                 
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88                             
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871                                   
init version: 949e6fa                                                                    
Security Options:                                                                        
 seccomp                                                                                 
  Profile: default                                                                       
Kernel Version: 4.9.87-linuxkit-aufs                                                     
Operating System: Docker for Windows                                                     
OSType: linux                                                                            
Architecture: x86_64                                                                     
CPUs: 2                                                                                  
Total Memory: 7.768GiB                                                                   
Name: linuxkit-00155da1310d                                                              
ID: DJSI:5VFP:BERB:BHD5:UNW6:JE6A:ZNML:TEBF:JGGW:4VIA:BEMN:6MH3                          
Docker Root Dir: /var/lib/docker                                                         
Debug Mode (client): false                                                               
Debug Mode (server): true                                                                
 File Descriptors: 19                                                                    
 Goroutines: 36                                                                          
 System Time: 2018-07-06T06:49:53.8050135Z                                               
 EventsListeners: 1                                                                      
Username: ljay                                                                           
Registry: https://index.docker.io/v1/                                                    
Labels:                                                                                  
Experimental: false                                                                      
Insecure Registries:                                                                     
 127.0.0.0/8                                                                             
Live Restore Enabled: false                                                              
```

**Comment by wa-daniel-fahl** [comment]
BUMP as this is still unsolved.

**Comment by casenjo** [comment]
Same issue on Win 10 Pro with Hyper-V enabled :(

**Comment by andrei-ivanov** [comment]
The project probably has a ton of bugs so this one is left as a very low priority.

**Comment by marcelloromani** [comment]
So the issue seems to be that docker is not playing nicely with the fast boot option (or vice-versa).

**Comment by gotzmann** [comment]
I've experienced the same trouble with Docker CE 18.06 on my Windows 10 Pro

```
Cannot start service ethereum: driver failed programming external connectivity on endpoi
g userland proxy: mkdir /port/tcp:0.0.0.0:10044:tcp:172.18.0.3:8334: input/output error
```

**Comment by relnah** [comment]
Still same issue in Version 18.06.0-ce-win72 (19098).
Docker was working fine. Shut down computer. Start computer. Oracle db container listed as running but not able to connect to it. Restarting container gives this message:

Error response from daemon: Cannot restart container oracle: driver failed programming external connectivity on endpoint oracle (7aee0cf5a8816888d42f76aa2ae15de6026be1ee8f82f92654fecad98a273e46): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:49161:tcp:172.17.0.2:1521: input/output error

Diagnostics ID: 18D5608F-3086-460D-BD15-84F84F2C55D6/20180823075357

Win 10 Enterprise
1709
16299.547

**Comment by saspeed** [comment]
cheer up, tomorrow we celebrate the first anniversary of @relnah opening this issue^^

**Comment by sriharisahu** [comment]
Affects me too.

```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:28 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:13:46 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by znmeb** [comment]
If you search this repo's issues for `driver failed programming external connectivity on endpoint` you will find 24 issues, 11 open and 13 closed. As far as I'm concerned Docker Compose on Windows 10 Pro is not a supportable product. 

For small-scale desktop operations, I suspect PowerShell scripting is a better option than wrestling with a broken Docker Compose. For full-strength DevOps development, now that Docker for Windows ships Kubernetes, I'm planning to migrate my workflow to Kubernetes.

**Comment by RichardBruskiewich** [comment]
I encountered the same problem on my Windows 10 workstation but couldn't find the "Fast Startup" setting. Brainstorming a bit, I thought I'd check the Docker for Windows service startup configuration. The service was set to "Automatic" but I noticed that "Automatic (Delayed Start, see [)"](https://stackoverflow.com/questions/11015189/automatic-vs-automatic-delayed-start/11015576#11015576) was an option, so I chose that instead. That setting delays the startup for about 2 minutes or so after the last regular automatic service is started during boot up.  This setting seemed to fix the problem so I surmise that once Windows 10 is properly initialized, the Docker for Windows service can truly start normally.

**Comment by IanIsFluent** [comment]
> I encountered the same problem on my Windows 10 workstation but couldn't find the "Fast Startup" setting. Brainstorming a bit, I thought I'd check the Docker for Windows service startup configuration. The service was set to "Automatic" but I noticed that "Automatic (Delayed Start, see [)"](https://stackoverflow.com/questions/11015189/automatic-vs-automatic-delayed-start/11015576#11015576) was an option, so I chose that instead. That setting delays the startup for about 2 minutes or so after the last regular automatic service is started during boot up. This setting seemed to fix the problem so I surmise that once Windows 10 is properly initialized, the Docker for Windows service can truly start normally.

Tried this first - but no effect. Trying switching off fast startup now.

**Comment by jasonbivins** [comment]
We have made some recent changes to the Hyper-V detection on startup - and have seen issues in the past where Hyper-V wasn't starting up with Windows.  Please make sure your Hyper-V is set to auto-start.


```bcdedit /set hypervisorlaunchtype auto```

**Comment by IanIsFluent** [comment]
> We have made some recent changes to the Hyper-V detection on startup - and have seen issues in the past where Hyper-V wasn't starting up with Windows. Please make sure your Hyper-V is set to auto-start.
> 
> `bcdedit /set hypervisorlaunchtype auto`

Already was. Sorry.

**Comment by relnah** [comment]
@jasonbivins 
This is what bcdedit reports as current settings:
hypervisorlaunchtype    Auto

So it is already set and doesn't solve my issue I'm affraid.

**Comment by LindaLawton** [comment]
Didnt help either.

**Comment by Pyroseza** [comment]
Do they realise that this is basically everyone on Windows 10 with the problem?

Why does a `docker-compose down` or `docker stop my_container` not work???
Surely it should clean up after itself...

**Comment by idurant** [comment]
Same issue here. I was attempting to docker run Jenkins when this happened. Looking at `docker ps -a` shows things are being created but can not run 😞

**Comment by basovic88** [comment]
I've got exactly the same issue here.

`Error starting userland proxy: mkdir /port/tcp:0.0.0.0:5432:tcp:172.17.0.2:5432: input/output error.`

With:
- Windows 10 Pro version 1803 build 17134.285
- Docker version 18.06.1-ce, build e68fc7a

A restart of the docker service is the work around.

**Comment by StanislavBogatov** [comment]
I think this moment should at least be added to the official docker documentation, i only found a solution right in this issue report (restarting docker is the way to go).

**Comment by jasonwilliams** [comment]
Related: https://github.com/docker/for-win/issues/1752
Related: https://github.com/docker/for-win/issues/2722

Is anyone fixing this? There seem to be a few issues around the same problem?
I don't want to turn off fast startup

**Comment by andrei-ivanov** [comment]
They are probably waiting for everyone to switch to Linux 😂

**Comment by znmeb** [comment]
Sadly, I don't know the internals of everything, but here's what I suspect is happening.

When you shut Windows down, it sends a signal to all the processes that warns them to save their work and exit gracefully. If they don't do so, eventually Windows will time out and nuke the process. Since Docker for Windows is running as a Linux guest in Hyper-V, I'm assuming Hyper-V catches this signal and cleans up its own act. 

But does it send a signal to the Moby Linux guest VM warning *it* of the impending shutdown? And does the Moby Linux guest catch the signal and clean up / exit gracefully?

**Comment by xenogew** [comment]
### Same Problem found w/ docker-compose
Expected behavior
    *  all containers start again with created properly after containers stop -> computer restart
Actual behavior
    *  the containers that have port binding defined throw error and won't start
Information

    Diagnostic ID: 757E1038-9468-430D-A9F0-F885E0CCDC8B/20181016115627 (It might not has anything refer to problem because I do workaround method to make them run properly again)
    `docker-compose up` -> `docker-compose stop` -> Docker shutdown -> Windows shutdown -> Windows startup -> Docker startup -> `docker-compose start` -> port bind containers ERROR
    Host: Windows 10 Pro 64 bit version 1809 (10.0.17763.55)
    Docker Community 18.06.1-ce-win73 (19507) channel stable b0f14f1
    Docker Compose: 1.22.0

Steps to reproduce the behavior

    `docker-compose up`
    `docker-compose stop`
    Docker shutdown
    Windows shutdown
    Windows startup
    Docker startup
    `docker-compose start`
    port bind containers ERROR

**Comment by relnah** [comment]
Issue still active in latest release... disabling fast boot is not an option. Don't want to hurt the rest of my computer 'cause of docker.
Updated docker.
Started docker.
Running fine.
Windows shut down.
Windows startup
Docker says it's running but does not work.

Error response from daemon: Cannot restart container mycontainer: driver failed programming external connectivity on endpoint mycontainer (130bd48c6e88133f7089baf17b0c9cf207281078626e65106e492884362e8ce9): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:49161:tcp:172.17.0.2:1521: input/output error

Diag id: 18D5608F-3086-460D-BD15-84F84F2C55D6/20181120080028

Restart of docker still restores it to normal but is a real pain to have to do each day.

**Comment by relnah** [comment]
Bypassed IT-department and updated to latest Windows 10 Enterprise. Same issue :(
Edition: Windows 10 Enterprise
Version 1809
OS build 17763.134

Docker diag id: 18D5608F-3086-460D-BD15-84F84F2C55D6/20181122101449

**Comment by longhf** [comment]
This problem may caused by a new feature of win10, See the answer from biscuit314 in this thread [https://stackoverflow.com/questions/40668908/running-docker-for-windows-error-when-exposing-ports]  Stop all running docker containers before shutdown your computer, this method help me solved this problem.

**Comment by Hans-kovit** [comment]
Experiencing the same problem ... Very dissapointing ... Upgraded my windows Home to Pro JUST so I could use Docker on my windows machine as well and not have to put my laptop on my desk, every time I work from home.  Restarting will only work only 50% of the times, the other 50% it will report not being able to (re)start for not having enough memory (yeah right, 8Gb is not enough eh ?) ... Annoying as fook.

**Comment by LindaLawton** [comment]
Putting all of your containers into a docker swarm seams to work.   They start up fine after a reboot.

```
docker swarm init
docker network create --driver overlay mynetwork
docker service create --name elasticsearch --network mynetwork -p 9200:9200 -p 9300:9300 --mount type=bind,src=c:/mynetwork/elasticsearch,dst=/usr/share/elasticsearch/data docker.elastic.co/elasticsearch/elasticsearch:6.4.3
docker service create --name kibana --network mynetwork -e ELASTICSEARCH_URL=http://elasticsearch:9200 -e xpack.security.enabled=false -p 5601:5601 docker.elastic.co/kibana/kibana-oss:6.4.3
docker service create --name rabbit --network mynetwork --hostname my-rabbit -p 5672:5672 -p 8080:15672 rabbitmq:3-management
docker service create --name redis --network mynetwork -p 6379:6379 redis
docker service create --name mongo --network mynetwork --hostname my-mongo -p 27017:27017 --mount type=volume,src=mongodb,dst=/data/db mongo:3.6
```

**Comment by bvkeersop** [comment]
Same problem here.
Restarting docker works but it's annoying to have to do this every time.

**Comment by sinanaltaii** [comment]
I have the same issue with Parallels Windows 10 
OS Name:   Microsoft Windows 10 Pro
OS Version:  10.0.17134 N/A Build 17134

**Comment by tinywook** [comment]
I had the issue and the solution for me was to share my C:. I have all my containers on a project drive D: so I didnt see a need to have C: shared. I shared it and this allowed me to start compose with 0 issue.

**Comment by ItorSnow** [comment]
> As @Christowiak say, Turn off `fast startup` works for me.
> **Uncheck** `Turn on fast startup` and save. enjoy!
> Control Panel > Hardware and Sound > Power Options > System Settings
> ![windows 10 fast startup](https://camo.githubusercontent.com/e4fb76b741a2d05573ae89c6fdd18bc61ec53a8e/68747470733a2f2f692e696d6775722e636f6d2f414a726a6b546b2e706e67)

Work for me. 
Thnks.

**Comment by Roemer** [comment]
Turning off `fast startup` works for me as well. Although it is now found behind the `Choose what the power buttons do` button:
![image](https://user-images.githubusercontent.com/393641/51892634-d8c56500-23a2-11e9-865c-cd4033ea2410.png)
![image](https://user-images.githubusercontent.com/393641/51892642-df53dc80-23a2-11e9-94a9-29490da39493.png)
![image](https://user-images.githubusercontent.com/393641/51892654-e67aea80-23a2-11e9-877f-b32a5e06ff81.png)

**Comment by krzysztofantczak** [comment]
Yea, it doesn't help. In my case, exactly the same issue started after updating windows to 1809.

**Comment by danlz** [comment]
> Yea, it doesn't help. In my case, exactly the same issue started after updating windows to 1809.

Check the fast startup setting again.
It seems that updates activate it.

**Comment by twothe** [comment]
Same issue for me. Removing fast restart is not an option in my case.

I would love to see a fix for this issue.

**Comment by deanpodgornik** [comment]
Looking forward to an update that will remove this issue. It's quite frustrating (removig fast startup is not an option).

**Comment by juniormayhe** [comment]
Disabling fast startup is not helping me here. It suddenly stopped working and cannot start nothing on port 2181. Also restarting nor resetting  Docker for Windows is working anymore. Other suggestions like experimental features, either disable or enable also don't work. 

```
$ docker run --rm -d --name zookeeper --network app-tier -p 2181:2181 -p 3888:3888 zookeeper:latest
5622d5049698953fc0600436e9310852e6170ea4c86a8fbe3a7cd9351be85b76
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: driver failed programming external connectivity on endpoint zookeeper (a69f4b0749595f9c8ee5182a4c76432b46ac735d18660eae60a91adf97c2880f): Error starting userland proxy: Bind for 0.0.0.0:2181: unexpected error Permission denied.
```

**Comment by NestorDR** [comment]
Hello. I share a solution that works for me.
I wrote a batch file of commands to stop and restart Docker and its containers.
I programmed its automatic execution in the windows task scheduler to be executed at system startup.

I list below the instructions of batch file: restartDocker.cmd 
I hope you find it useful. Greetings

:Reset Docker and Containers
@echo off
cls

echo Wait for Docker to finish start...
timeout /t 150
docker ps --no-trunc -s -a

:STOP
echo.
echo Stopping my containers (one stop line for each container)...
docker stop <putHereContainerName>
echo.
echo Stopping Docker...
net stop com.docker.service
taskkill /im "Docker*" /f

:START
echo.
echo Starting Docker...
net start com.docker.service
start "" "C:\Program Files\Docker\Docker\Docker for Windows.exe"
echo.

echo Wait for Docker to finish start...
:WAIT
tasklist /fi "imagename eq Docker for Windows.exe" |find ":" > nul
if %ERRORLEVEL%==0 goto WAIT
timeout /t 75

echo Starting my containers (one start line for each container)...
docker start <putHereContainerName>

:SHOW
echo.
docker ps --no-trunc -s

:END
echo.

**Comment by jeacott1** [comment]
@NestorDR there's already a reset docker button, how is this different?

**Comment by NestorDR** [comment]
@jeacott1 this is different because it automates the restart of Docker, without the need for you to do it on demand.
As it is a batch file, with scheduled execution after Windows startup, you would not be forced to manually restart Docker.
Only you will have to wait a little longer, for the instructions [timeout /t ] of the batch file.

**Comment by mfoulds** [comment]
@NestorDR thanks for this. If we were to disable Docker's automatic startup on login in Docker Settings, then could we run your script instead, but without having to wait for Docker to stop?

**Comment by Tiberriver256** [comment]
Easier methods for managing the "fast startup" mode via cmd.exe / PowerShell:

## Turn on
```
REG ADD "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Power" /V HiberbootEnabled /T REG_dWORD /D 0 /F
```

## Turn off
```
REG ADD "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Power" /V HiberbootEnabled /T REG_dWORD /D 1 /F
```

## More Information / Other methods
https://www.tenforums.com/tutorials/4189-turn-off-fast-startup-windows-10-a.html

**Comment by NestorDR** [comment]
@mfoulds The problem arises because Docker does not stop formally at shutdown Windows, so the Docker must be started, in order to stop it formally.

**Comment by StefanScherer** [comment]
We're currently working on several issues and have a first [edge preview](https://download-stage.docker.com/win/edge/36384/Docker%20Desktop%20Installer.exe) to download which solves the problem with the "fast startup" mode in our test environment. It even restarts containers after a reboot and login that were started with the restart option eg. `docker run -d -p 80:80 --restart always nginx`.
I would love to hear your feedback if and how it helps in your environment.

**Comment by mcopjan** [comment]
Unfortunately unable to install on Microsoft Windows Server 2016 Standard (10.0.14393 Build 14393), it says" Docker Desktop requires Windows 10 Pro or Enterprise version 15063 to run." :(
Currently using 2.0.0.3 (31259)

**Comment by nrjohnstone** [comment]
Downloading and trailing right now...

**Comment by nrjohnstone** [comment]
and after leaving some docker containers running, shutting down pc for 6 hours then restarting I get a crash from docker on starting (replicated multiple times)

error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

   at Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning)
   at Docker.Backend.BackendNamedPipeServer.<Run>b__8_4(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

Lucky at this point of using docker on windows for the last 3 years I've become apathetic to announcments and new versions of docker solving anything.

**Comment by mikeparker** [comment]
@mcopjan Docker Desktop is for developer machines, not Windows Server. For Windows Server please see Docker Enterprise for Windows Server -> https://docs.docker.com/install/windows/docker-ee/

@nrjohnstone can you confirm Docker Desktop is set to startup on boot and not disabled in the windows startup tasks. Can you then check the status of your whale icon in your systray (if its broken, it will be red. If its not started at all it won't be there.) Assuming all this is fine can you then upload your log file or a diagnostic? The error message you posted just says docker isn't running, so diagnosing that will need more info. Thanks!

**Comment by mcopjan** [comment]
@mikeparker thanks, I installed docker EE on WS 2016, problem is I cannot switch into linux containers (I assume it is not supported?) So I am still stuck with Docker for Windows experiencing the reported issue.

**Comment by nrjohnstone** [comment]
@mikeparker I can confirm the following 
After the install everything works and there is a Hyper-V machine "DockerDesktop" running.
After a reboot, the Hyper-V machine is still there, and running, but Docker Desktop starts, the whale icon in the system tray does it's thing for about 2-3 minutes then I get the error with the docker daemon not running.

I have to uninstall and revert back to the build from last year that I've been running as I don't really have the time to be a beta tester for this scenario.

I guess it's back to force killing docker to restart on every windows login again.

**Comment by graham73may** [comment]
@nrjohnstone 
I have this exact issue and was really hoping you were going to come back with some good news! 

I don't know if you will find either of these less painful than force killing docker:
1. Quit docker before shutting down. 
Or
2. When you boot up... let the whale do it's thing. When it thinks it's ready, right click and hit restart docker. 

The other annoying thing I've not managed to find a work around for is if I'm using docker and shut my laptop... Then open my laptop a bit later, the whole machine has effectively crashed and windows starts up from scratch instead of waking from sleep. (this only happens if docker is running, fine if it's not).

**Comment by luisbodra** [comment]
Hi, I am a user of Brazil and have experienced an error in my attempts to install [nwabap751] from the command line of my Linux container Ubuntu into Docker. The message appears on my screen:
  ==================================================================

PS C:\INST> docker run -p 8000:8000 -p 44300:44300 -p 3300:3300 -p 3200:3200 -h vhcalnplci --name nwabap751 -it nwabap751 /bin/bash
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: driver failed programming external connectivity on endpoint nwabap751 (89538c9c2ae1ab2541f308b6bd64cbff4024dc4ad773aa2096026a9a28bc76f4): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:44300:tcp:172.17.0.2:44300: input/output error.
PS C:\INST>
  ==================================================================
 How can I solve this problem? Why it happens? Can you help me? Thanks for your help.

**Comment by wasmup** [comment]
For me, Solved by Docker Restart, Error:
> docker: 
> Error response from daemon: driver failed programming external connectivity on endpoint pg1 (ee2507e963bb1effee71270ed0151d7e1c92cbb32615e0b176f4852892c4c596): 
> Error starting userland proxy: mkdir /port/tcp:0.0.0.0:5432:tcp:172.17.0.2:5432: input/output error.
> 

docker version
```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by domix90** [comment]
> i have found a solution on a other thread.
> 
> > #573
> 
> The problem relies on the **hybrid shutdown mode** from the lastest win 10 updates. After disable it under energy options, the problem is solved for me.

This one worked for me.

**Comment by relnah** [comment]
After upgrade to latest stable Docker my case now works without any workarounds, like disabling OS features.

I select to have Docker start on start up, I create a container with --restart unless-stopped.
Confirm that container is accessible and running ok.
Shut down windows.
Start windows.
Wait for Docker to automatically start.
Confirm that container is running ok and is accessible.

I'm running linux containers.

Version info:
{
  "id": "",
  "date": "2019-08-16 06:11:41.1555453 +0000 UTC",
  "os": "Windows 10 Enterprise 10.0.18362",
  "os_label": "win/18362",
  "app_version": "2.1.0.1",
  "app_channel": "stable",
  "engine_version": "19.03.1",
  "compose_version": "1.24.1",
  "kubernetes_version": "v1.14.3",
  "credhelper_version": "0.6.3",
  "notary_version": "0.6.1",
  "vpnkit_version": "218f01482560cba2fa863f9ad872ad51d1e717fc"
}

Thanks for the fix ;)

**Comment by welshronaldo** [comment]
This also seems to be working for me without workarounds in 2.1.0.1 now. Good job! 👍

**Comment by Vespira** [comment]
Restart didn't worked for me (tried multiple way to restart Docker), neither did disabling the "Experimental features" (as it were already disabled, anyway). We tried so much things, but we ended up doing a "Reset to factory" from Docker Desktop GUI, and magically, it worked again.

But man, I hate it when docker network or something have a corrupted state, it happens way too often. Plus, the issue that I have to effectivly restart Docker at each Windows start, but here, changing the shutdown strategy, like other users suggested, to "not fast startup" did the trick.

**Comment by relnah** [comment]
2.1.0.1 fixed it. Has been working well for a couple of weeks.

**Comment by Vespira** [comment]
I'm was already in version 2.1.0.1 (build 37199) when I had the issue I described earlier. So it has to be something else. I'll create an issue if I have the problem again anyway.

**Comment by nickof** [comment]
Still the same issue on 2.1.0.1 (build 37199)

**Comment by Viir** [comment]
docker run fails on Windows 10:
```
Error response from daemon: driver failed programming external connectivity on endpoint drtsgame-test-container (7597b6ceadc7356f20b918b1c46c648f1cabf99df3f82ef79093cf337d5ac9cb): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:443:tcp:172.17.0.2:443: input/output error.
```

docker version:
```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
Note about Docker version: The docker installer keeps hanging, see https://github.com/docker/for-win/issues/1172#issuecomment-516861001

**Comment by Illutax** [comment]
Had an similar error. Restarting the system fixed it for me.

Apparently the system tried at some point an shutdown but it was interrupted. While trying to shutdown the OS stopped some services or driver required for docker.

**Comment by andrebacaglini** [comment]
> As @Christowiak say, Turn off `fast startup` works for me.
> **Uncheck** `Turn on fast startup` and save. enjoy!
> Control Panel > Hardware and Sound > Power Options > System Settings
> ![windows 10 fast startup](https://camo.githubusercontent.com/e4fb76b741a2d05573ae89c6fdd18bc61ec53a8e/68747470733a2f2f692e696d6775722e636f6d2f414a726a6b546b2e706e67)

Disabling fast startup worked for me!

**Comment by hyperniklas** [comment]
You know that services usually don't work UNLESS you send telemetry data and it will refuse to start. I have this exact problem now and ask a simple question: **Please, can you remove all telemetry so I can run docker?**
