### ISSUE TITLE
Docker fails to start on Amazon EC2 running windows Server

### ISSUE THREAD

**Issue by nsmith1024** [docker/for-win#10395]
- [X ] I have tried with the latest version of Docker Desktop
  - [X ] I have tried disabling enabled experimental features
  - [X ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

Try to run docker on Amazon EC2 instance running windows server

### Expected behavior

Docker should work

### Information

  - Windows Version: Windows Server 2019
  - Docker Desktop Version: 3.1.0
  - WSL2 or Hyper-V backend?  Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Amazon EC2 instance running Windows Serer

### Steps to reproduce the behavior

1. Try to run docker on Amazon EC2 instance running windows server

The Virtual Machine Management Service failed to start the virtual machine 'DockerDesktopVM' because one of the Hyper-V components is not running (Virtual machine ID AB43920A-A86E-4063-A281-CE6B16707803).

**Comment by stephen-turner** [comment]
Thank you for the report. Unfortunately Docker Desktop is not supported in a
virtualised environment (see https://docs.docker.com/docker-for-windows/install/#whats-included-in-the-installer and https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-desktop-in-nested-virtualization-scenarios). It's out of our control whether it works or not: it depends whether the outer hypervisor can fully run Hyper-V or WSL 2. Sometimes enabling nested virtualisation in the outer hypervisor makes it work, but there are no guarantees.
