### ISSUE TITLE
First install on Win10 VM; fails to launch with dianotsic id 256F7CE0-77CA-4D35-BA49-859A4AEB57B6/20210215215958

### ISSUE THREAD

**Issue by Bolter11** [docker/for-win#10394]
- [x ] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features
  - [ ]x I have uploaded Diagnostics
  - Diagnostics ID: 256F7CE0-77CA-4D35-BA49-859A4AEB57B6/20210215215958

### Information

  - Windows Version:Windows 10 Home 19042.804
  - Docker Desktop Version: 3.1.0.51484
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:  Running on win 10 VM

### Steps to reproduce the behavior

  1. Install Docker Desktop
  2. Launch

**Comment by stephen-turner** [comment]
Thank you for the report. Unfortunately Docker Desktop is not supported in a
virtualised environment (see https://docs.docker.com/docker-for-windows/install/#whats-included-in-the-installer and https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-desktop-in-nested-virtualization-scenarios). It's out of our control whether it works or not: it depends whether the outer hypervisor can fully run Hyper-V or WSL 2. Sometimes enabling nested virtualisation in the outer hypervisor makes it work, but there are no guarantees.
