### ISSUE TITLE
WSL 2

### ISSUE THREAD

**Issue by DrewRidley** [docker/for-win#10408]
- [ x ] I have tried with the latest version of Docker Desktop
  - [ x ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: Unable to upload due to an internal server error.

### Actual behavior

GPU is not detected in the target docker container, despite the GPU benchmark on the guide successfully detecting my GPU.

### Expected behavior

GPU (with paravirtualization) is detected in the target docker container.

### Information

  - Windows Version: 21313.1000
  - Docker Desktop Version: 
  - WSL2 or Hyper-V backend? WSL2  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Follow guide here to install WSL 2 backend and enable paravirtualization. https://docs.docker.com/docker-for-windows/wsl/
  2. Execute the following command to verify paravirtualization is enabled. `docker run --rm -it --gpus=all nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -gpu -benchmark`
  3. Pull the following container and attempt to run it: `sudo docker run --ipc=host --gpus all -it ultralytics/yolov5:latest`
  4. Witness the following error:

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use 'nvidia-docker run' to start this container; see
   https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker .

**Comment by stephen-turner** [comment]
If the benchmark in step 2 works then it looks like everything is plumbed through to the containers correctly, which would suggest that the bug is in the ultralytics/yolov5 container not in Docker Desktop.
