### ISSUE TITLE
debian apt install fails with "Bad header line Bad header data" when building an image

### ISSUE THREAD

**Issue by ouanixi** [docker/for-win#10421]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: FC80887A-01B5-47E8-8C5A-83F136B527F4/20210218223945

When running `docker build -t myimage .` it fails at the  `RUN apt install google-chrome-stable` step with `Bad header line Bad header data` 

### Actual behavior
building the image fails with
```
..................
.................
#8 22.32 Get:142 http://deb.debian.org/debian buster/main amd64 libglx0 amd64 1.1.0-1 [30.0 kB]
#8 22.39 Get:143 http://deb.debian.org/debian buster/main amd64 libgl1 amd64 1.1.0-1 [91.1 kB]
#8 22.46 Get:144 http://deb.debian.org/debian buster/main amd64 x11-utils amd64 7.7+4 [202 kB]
#8 22.53 Get:145 http://deb.debian.org/debian buster/main amd64 x11-xserver-utils amd64 7.7+8 [168 kB]
#8 22.53 E: Failed to fetch http://deb.debian.org/debian/pool/main/c/colord/libcolord2_1.4.3-4_amd64.deb  Bad header line Bad header data [IP: 199.232.54.132 80]
#8 22.53 E: Failed to fetch http://deb.debian.org/debian/pool/main/l/lm-sensors/libsensors-config_3.5.0-3_all.deb  Bad header line Bad header data [IP: 199.232.54.132 80]
#8 22.53 E: Failed to fetch http://deb.debian.org/debian/pool/main/libg/libglvnd/libglvnd0_1.1.0-1_amd64.deb  Bad header line Bad header data [IP: 199.232.54.132 80]
#8 22.53 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
#8 22.53 Fetched 129 MB in 21s (6005 kB/s)
------
executor failed running [/bin/sh -c apt install -y google-chrome-stable]: exit code: 100
```

### Expected behavior
The image to build succesfully.

### Information

The odd thing about this is when I build the same container (minus the install step of chrome) and then exec into it, I can sucessfully install chrome but only if I force apt to use IPv4 via `Acquire::ForceIPv4=true`. And if I force IPv4 in the `RUN` step in Dockerfile, the build fails with the same error.

  - Windows Version: Windows 10 Home, Build 19042.804
  - Docker Desktop Version: 3.1.0(51484)
  - WSL2 or Hyper-V backend?  WSL2 Backend
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Running inside an Ubuntu 20.04 LTS wsl distro

### Steps to reproduce the behavior

  1. Open a WSL session (I'm using using Ubuntu 20.04 via Windows Terminal)
  2. Try to build a docker image with the following Dockerfile
  ```
FROM python:3.8

# install google chrome
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
RUN apt -y update
RUN apt install -y google-chrome-stable
```
3. The above step should fail with the Bad header error described on the previous sections. Now Try building the same dockerfile without the last RUN command (comment out the `RUN apt install -y google-chrome-stable`.
4. Run the container with a bash session `docker run -it container_name /bin/bash`
5. From within the container try running `apt install -y google-chrome-stable`. This should fail with the same error.
6. From within the container try running `apt -o Acquire::ForceIPv4=true install -y google-chrome-stable`. This would succeed.
7. Edit the Dockerfile by replacing the last line with `RUN apt -o Acquire::ForceIPv4=true install -y google-chrome-stable` and try building it again. This would fail with the same Bad Headers Line error.

**Comment by stephen-turner** [comment]
IPv6 support in Docker Desktop is not complete. This is documented, but there is an item on our roadmap to request to fix it if you want to vote for it: it hasn't got much traction yet. docker/roadmap#156.

**Comment by ouanixi** [comment]
Hi @stephen-turner thanks for the quick response. 

How come `apt -o Acquire::ForceIPv4=true install -y google-chrome-stable` works when I run it from inside a running container, but not when it's part of the build stage in `RUN apt -o Acquire::ForceIPv4=true install -y google-chrome-stable` ?
