### ISSUE TITLE
Possible bug in Installation file for Docker Desktop For Windows v3.1.0 (51484)

### ISSUE THREAD

**Issue by PortMacOnline** [docker/for-win#10426]
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID:
6CF205FF-CDDD-4CE1-8E9D-DE09686F184B/20210220015655

and

6CF205FF-CDDD-4CE1-8E9D-DE09686F184B/20210220033014

### Actual behavior
Program is breaking because of incorrect path to .docker 
### Expected behavior
Program to work!
### Information

  - Windows Version: - 10 Home 20H2 19042.804 
  - Docker Desktop Version: - 3.1.0 (51484)
  - WSL2 or Hyper-V backend?  - WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: - No

### Steps to reproduce the behavior

  1. ... Docker installation file has installed some files and folders in Users/Terry/.docker and some in Users/Terry/AppData/.docker
  2. ... Docker is looking for the ca.pem file in the wrong folder!
![Docker-Fail](https://user-images.githubusercontent.com/7662890/108582978-8e98ed00-738a-11eb-95b2-b8aea085b290.png)

**Comment by PortMacOnline** [comment]
**UPDATE:** Just re-installed the program using the default settings, same result. This is **not** user error, there is no user input, so the problem is in the installation script itself. When I checked, the ca.pem file doesn't exist in either directory.

[log.txt](https://github.com/docker/for-win/files/6052916/log.txt)

**Comment by aramosgarci** [comment]
Same error on a clean install Win 10
