### ISSUE TITLE
cant set ports on ubuntu image.

### ISSUE THREAD

**Issue by cfw34683** [docker/for-win#10433]
Click these checkboxes after submitting, or place an "x" in them.
  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4D4F7AA3-2076-4899-AA40-76B8FA191A10/20210220163828

Actual behavior
not showing the ability to list ports

Expected behavior
should allow the ability to list ports

Information

Please, help us understand the problem.  For instance:
  - Is it reproducible? yes
  - Is the problem new? no
  - Did the problem appear with an update? no 
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.

  - Windows Version: 10 20H2
  - Docker Desktop Version: latest 
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: NO

Steps to reproduce the behavior

docker pull ubuntu:latest
go to docker desktop and click images on left hand side
click run on ubuntu line
click down arrow for "OPTIONAL SETTINGS"
I am able to fill in container and volumes. 
I can not list any ports as shown in picture. >>  https://i.ibb.co/mqtSnFC/Screenshot-2021-02-20-114309.png

Thank you
![Screenshot 2021-02-20 114309](https://user-images.githubusercontent.com/44150081/108602621-e7f42280-7370-11eb-997d-9d6dcfc6b58e.png)

**Comment by stephen-turner** [comment]
The Ubuntu image doesn't expose any ports, so there is nothing to connect to.
