### ISSUE TITLE
Docker doesn't upgrade

### ISSUE THREAD

**Issue by fayep** [docker/for-win#1043]
### Expected behavior
When answering "yes" to the prompt to continue with the install, the install continues
### Actual behavior
Installation cancelled is received whether yes or no is clicked.
### Information
Docker was installed using the download from the website, which always goes through.
This may be an artifact of having had old versions of docker on here, I've upgraded from before the versioning changed.  I suspect that installing a newer version hasn't reset this flag.
I have attempted to uninstall docker from the uninstall settings and that makes no difference - if there is no Docker listed in Apps & Features then it still says Msi based installation found.
By finding and running the installer exe manually from a console:
```
[12:28:52.169] [InstallHandler] Not run as admin, relaunching with UAC prompt
[12:28:56.712] [InstallHandler] No d4w installation found
[12:28:56.725] [InstallHandler] Using embedded package
[12:28:56.876] [InstallWorkflow] Using package: res:d4w
[12:28:56.878] [InstallWorkflow] Downloading
[12:28:57.256] [InstallWorkflow] Exracting manifest
[12:28:57.285] [InstallWorkflow] Checking prerequisites
[12:28:57.310] [InstallWorkflow] Msi based installation found, prompting user
[12:28:59.843] [InstallWorkflow] Uninstalling msi based installation, with special flag
[12:28:59.915] [InstallWorkflow] MSI Uninstall failed
```
If you can point me to the logs for the MSI Uninstall or give me info to trigger manually, I'm happy to see what happens.  I suspect that I have bad registry data, but it would be good to know how the "Msi based installation" is found
### Steps to reproduce the behavior
1) Install docker from website
2) Upgrade appears in docker
3) Attempt to install upgrade.  Fails.
4) repeat from 1.

**Comment by beiriannydd** [comment]
Other things I've tried.  Downloading InstallDocker.msi and repairing it, then running this, removing it then running this.  All give the same result.

**Comment by luke-barnett** [comment]
I'm having the same issue described here.

I've run the script from here:

https://success.docker.com/KBase/How_to_completely_remove_Docker

Restarted my machine and when going to install again fresh, it is asking me if I want to do an upgrade. Hitting either yes or not results in a canceled installation.

**Comment by selner** [comment]
I was having the same issue described here.  

However, I did manage to work around the issue by running the legacy MSI installer for the stable channel instead from  https://download.docker.com/win/stable/InstallDocker.msi.

**Comment by kamkie** [comment]
I also have this problem and now msi installer is not working (17.09)

**Comment by Dante-101** [comment]
Same here. The .msi installer is just 256 KB in size. It is a bug from the build system or has Docker shifted to online installers?

**Comment by gtardif** [comment]
This .msi installer has been replaced by another one a couple of versions ago (hence the small .msi you have that should just get you to the new installer). 
You should try downloading the installer form here : 
https://download.docker.com/win/stable/Docker%20for%20Windows%20Installer.exe

**Comment by kauhat** [comment]
Here's what happens when I run the LightweightInstaller executable for `17.09.0-ce-win33`  on my work machine. It happens whether Docker is installed or not.

The most recent version I have installed is `17.06.2-ce-win27` from the MSI installer.

```
PS C:\Users\jack.fletcher\Downloads> & '.\Docker for Windows Installer.exe'
PS C:\Users\jack.fletcher\Downloads> [16:28:35.210] [InstallHandler] No d4w installation found
[16:28:35.214] [InstallHandler] Using embedded package
[16:28:35.334] [InstallWorkflow] Using package: res:d4w
[16:28:35.335] [InstallWorkflow] Downloading
[16:28:40.026] [InstallWorkflow] Exracting manifest
[16:28:40.067] [InstallWorkflow] Checking prerequisites
[16:28:40.089] [InstallWorkflow] Msi based installation found, prompting user
[16:28:41.013] [InstallWorkflow] Uninstalling msi based installation, with special flag
[16:28:41.091] [InstallWorkflow] MSI Uninstall failed
```

This is on 10 Pro x64, build no. 15063.608. Let me know if there's anymore details I can provide.

I've uploaded diagnostic report `606F2D48-4906-4849-9504-A14C638AC446/2017-10-06_16-33-36` from the installable 17.06 version if that helps!

**Comment by Jefiozie** [comment]
Having the same issue when upgrading to `17.09-CE-win34 (13622) `
- Used the new installer as mentioned by @gtardif .. didn't work,
- removed all stuff via powershell script , no success. 

Cannot find anything on my HDD or in the Register any workaround or things I missed to fix this.?

**Comment by fayep** [comment]
My output is identical to Kauhat's and this is the same behavior as the ordinary upgrade (except you only get to see the installation cancelled window) and not the log output. How do we manually uninstall because even if I use add-remove software, it still passes the "MSI based installation found" check (perhaps the check is in error, or the uninstall is leaving artifacts behind?)

**Comment by abobwhite** [comment]
What is going on here!? I haven't been able to cleanly upgrade Docker on Windows since it first became available. Back in June I was able to manually cleanup some registry keys and it worked, now I get the same results as the folks above. How can something so basic go being broken for so long? Most of 2017....

**Comment by jmail** [comment]
Same issue my side - I am having this issue since July I think. I finally removed all but there are still some entries and infos on the machine so installer knows docker was installed and asking for upgrade - what a mess. I can't work with my customer as they only work on dockers

**Comment by Jefiozie** [comment]
@jasonbivins Any updates on this issue? Or a workaround to fix the issue?

Thanks 👍

**Comment by jasonbivins** [comment]
Hi @Jefiozie 
Look for this registry key and remove it if it exists. Then try to install using the legacy .msi
``` Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall ```

**Comment by Jefiozie** [comment]
Hi @jasonbivins  Thanks for your reply.

What key should I look for the `docker` key?  I don't see that one in my registry.
Thanks.

**Comment by pjmolina** [comment]
Hi @jasonbivins 
Tried your approach:
- Removed registry key: `{C482546D-67BB-41BD-8E28-A71A002BC146}`
- Tried yo reinstall with the same result: **installation cancelled**.

Could you provide a explicit link to the legacy .msi installer you are referring? 
Any other key to delete or workaround to force a clean install?

Thanks

**Comment by Jefiozie** [comment]
Hi @jasonbivins 

Missed the key but the comment of @pjmolina helped me. 
Same result as him by the way so this was not enough apparently.

**Comment by bbqduc** [comment]
I had this issue as well and was able to resolve with thanks to this https://forums.docker.com/t/cannot-uninstall-docker-for-windows/15661/23 wonderful comment! 

In my case Process Monitor showed the installer reading `HKCR\Installer\UpgradeCodes\9CA3F2E62DBFCA74DB9BD0384695C460`. Deleting that manually solved the problem for me. Not sure if the key will be different on other machines.

**Comment by Jefiozie** [comment]
@bbqduc Thanks this resolved the issue for me!

**Comment by jmail** [comment]
@bbqduc Thanks - that resolved my problem as well

**Comment by pjmolina** [comment]
@bbqduc Thank you! Your dirty hack works here also! ;-)

**Comment by phantase** [comment]
@bbqduc  Thanks, solved my problem also, except that after reinstalling Docker, Avast just removed it (IDP.Generic treat), I had to add an exception to Docker to have it working.

**Comment by tiggi7** [comment]
Thi worked also for me.
Thanks a lot.

**Comment by sachin-gupta** [comment]
As per @bbqduc and [wonderful comment here](https://forums.docker.com/t/cannot-uninstall-docker-for-windows/15661/23) and following steps this issue is solved after failing 100 times 😄 

- Export backup of registry key *HKCR\Installer\UpgradeCodes\9CA3F2E62DBFCA74DB9BD0384695C460* (*was same on my computer*)
- Open regedit.exe in windows and delete entire registry key group
- Download **Edge Release** *full installer only* from site (*comes with weekly patches*) 
- Disable all firewall and antivirus, Stop docker from taskbar and windows service from services.msc
- Open command print and run `.\"Docker for Windows.exe"` and it should complete setup

**Comment by jasonbivins** [comment]
Hi @sachin-gupta 
Thanks for putting that together ! I'll make sure it makes it into a KB in the next few days

**Comment by giphoo** [comment]
@bbqduc it work for me. thank you!!!

**Comment by svassaux** [comment]
I have started on a new machine, I had not those keys people are referring to and thus I can't remove them. installer fails. Nothing to remove.

**Comment by abobwhite** [comment]
@sachin-gupta OMG thank you! I have been fighting this for months. Your steps worked perfectly!

**Comment by udif** [comment]
I've also reached this registry key independently and hit this github issue only after googling 9CA3F2E62DBFCA74DB9BD0384695C460 just to be sure.  
My original problem was the the docker installer decided I already have the latest version, even though it was uninstalled.  
For the record, as it may help other people, here is how I got here:
1. I ran https://docs.microsoft.com/en-us/sysinternals/downloads/procmon and captured events while running the installer, then stopped capturing (CTRL+E).
2. I then filtered all events but the successfull registry operations coming from the Docker install process, who did not return a NAME NOT FOUND result.
3. I searched for 'docker' within the remaining results, and nuked any registry entry found, each time rerunning the installer to see if it would succeed.
4. After removing all docker registry entries, it at least tried installing something, but then got the 'install aborted' message. I then browsed the entries looking for entries with a long unique hex ID.  This is when I found 9CA3F2E62DBFCA74DB9BD0384695C460 .
5. After googling it and finding it here, I nuked it too, and solved my problem.

Hope this may help people with future problems.

**Comment by odboy** [comment]
> I had this issue as well and was able to resolve it thanks to this https://forums.docker.com/t/cannot-uninstall-docker-for-windows/15661/23 wonderful comment!
> 
> In my case Process Monitor showed the installer reading `HKCR\Installer\UpgradeCodes\9CA3F2E62DBFCA74DB9BD0384695C460`. Deleting that manually solved the problem for me. Not sure if the key will be different on other machines.

thank you so much!!! it works...
