### ISSUE TITLE
Kubernetes stuck at 'Starting' with Docker Desktop on Windows 10

### ISSUE THREAD

**Issue by KNikovv** [docker/for-win#10440]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:  Diagnostics could not finish (Uploaded the content)
[diagnosticsContent.txt](https://github.com/docker/for-win/files/6020674/diagnosticsContent.txt)

### Actual behavior
Kubernetes is stuck at 'Starting' state
### Expected behavior
.. 
### Information

  - Windows Version: 1909 (OS Build 18363.1316)
  - Docker Desktop Version: 3.1.0
  - WSL2 or Hyper-V backend?  WSL
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by pjhavariotis** [comment]
Unfortunately, I have the same problem!
Diagnostics ID = 32FEDC2E-30E7-48C5-9BEF-82794B0D2906/20210226073702

Windows Version: **1909 (OS Build 18363.1316)**
Docker Desktop Version: **LATEST**
WSL2 or Hyper-V backend? **WSL2**

**Comment by saadzimat430** [comment]
same problem. Docker seems to be doing nothing about this bug.
Tried a bunch of solutions for days, still no result.
The weird thing is when I do "kubectl cluster-info", it seems to be working properly.
