### ISSUE TITLE
Docker for windows HyperX dialog - text is editable.

### ISSUE THREAD

**Issue by jakub-szczepaniak** [docker/for-win#1044]
### Expected behavior
It should not be possible to add/edit the text in the Docker HyperX dialog

### Information
 
Version 17.06.1-ce-win24 (13025)
Channel: stable
54dc09c

### Steps to reproduce the behavior

  1. Run Docker for Windows with Hyper X not enabled on your system.
     Dialog box with message about Hyper X not enabled appears.
  2. Try to hit letters on the keyboard.
  3. Observe
![image](https://user-images.githubusercontent.com/7815188/29774610-5ee08992-8c02-11e7-817e-b6d4036c1d6a.png)

cosmetic issue.

**Comment by gtardif** [comment]
This is fixed with Docker For Windows 17.07.0 released today
