### ISSUE TITLE
docker-compose 1.27 is outdated (the latest version is 1.28)

### ISSUE THREAD

**Issue by AndreyMZ** [docker/for-win#10450]
### Problem description

According to <https://docs.docker.com/compose/release-notes/>, docker-compose 1.28.0 was released on 2021-01-20.
According to <https://docs.docker.com/compose/install/>, the only way to install docker-compose on _Windows_ is installing _Docker Desktop for Windows_.

But the latest version of _Docker Desktop for Windows_ still contains docker-compose 1.27. The update is needed.

----

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: **not needed**

### Actual behavior

> Compose: 1.27.4

### Expected behavior

> Compose: 1.28.3

or newer.

### Information

  - Windows Version: **10**
  - Docker Desktop Version: **3.1.0 (51484)**
  - WSL2 or Hyper-V backend? **Hyper-V**
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: **no**

### Steps to reproduce the behavior

  1. Click _About Docker Desktop_.
  2. Look at the _Composer_ version.

**Comment by stephen-turner** [comment]
It will be included in the next release of Docker Desktop. We haven't had a release since compose 1.28 was released.
