### ISSUE TITLE
Docker crashed at startup

### ISSUE THREAD

**Issue by Polda18** [docker/for-win#10455]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 20A7F0A7-DDBD-40DE-B5A6-0338ADA4EE36/20210223085309

### Actual behavior
Crashed, without any obvious reason.

### Expected behavior
Well, start up and work, obviously.

### Information

  - Windows Version: Windows 10 Insider Preview, build 21313.1000
  - Docker Desktop Version: 3.1.0
  - WSL2 or Hyper-V backend? : WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No, physical Windows machine

### Steps to reproduce the behavior

  1. Start Docker Desktop
  2. And it crashes

It may or may not crash, I don't know what led to the crash, but I did nothing but just start up my computer, which has Docker Desktop being automatically started up as well. What happened may solely be bug of WSL2, but since it offered diagnostics, I reported it.

**Comment by enjoyindehradun** [comment]
My docker is not started up, giving error logs. and also localhost is not configured http://localhost:8080 and https://localhost:4343 for both. I am using windows 10
