### ISSUE TITLE
cannot restart docker-composer in the Dashboard of Docker Desktop

### ISSUE THREAD

**Issue by bp-Li** [docker/for-win#10464]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
After running ```docker-compose -f .\dev-docker-compose.yml up -d``` to start docker, you cannot restart docker-composer in the Dashboard of Docker Desktop
error:
Cannot stop Docker Compose application. Reason: Command failed: docker-compose --project-directory "E:\work\inner\xxx" stop Can't find a suitable configuration file in this directory or any parent. Are you in the right directory? Supported filenames: docker-compose.yml, docker-compose.yaml

### Expected behavior
can restart docker-composer normally in the Dashboard of Docker Desktop

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by bp-Li** [comment]
Did not use "Use WSL 2 based engine"

**Comment by bp-Li** [comment]
Did not use ```Use WSL 2 based engine```

**Comment by Diluka** [comment]
the same issue when remove compose in dashboard

if use `-f` to specify  other file and the folder not contains `docker-compose.yml`, `docker-compose.yaml`, `compose.yml`, `compose.yaml`. the dashboard can't execute any commands on compose.

so the dashboard doesn't recognize the `-f` option
