### ISSUE TITLE
Docker fails on install 

### ISSUE THREAD

**Issue by carye98** [docker/for-win#10469]
- [ x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID:  
C864F39D-E7A8-4279-A157-6F11FABD6BDF/20210224151538

### Actual behavior
When installing the latest Docker for windows desktop. it fails to complete setup

### Expected behavior
Docker to be installed successful

### Information

  - Windows Version:
  - Docker Desktop Version: 3.1.0
  - WSL2 or Hyper-V backend?  WSL 2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Steps to reproduce the behavior

  1. ... Install Docker 3.1.0
  2. ...  Screenshot attached
[log.txt](https://github.com/docker/for-win/files/6037243/log.txt)
![screen Capture](https://user-images.githubusercontent.com/62721514/109028652-066b5e00-7690-11eb-8432-21b0982b883f.JPG)

**Comment by stephen-turner** [comment]
It appears that you haven't installed WSL 2 correctly, which Docker Desktop uses. Please follow Microsoft's instructions at https://aka.ms/wsl2-install. If it's set up correctly, then the command wsl -l -v should show a version 2 distro.
