### ISSUE TITLE
"No containers running" after Windows 10reboot

### ISSUE THREAD

**Issue by kayest** [docker/for-win#10460]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Docker was running great. After rebooting my Windows 10 machine, I can't get it to function properly. The Docker Dashboard is open with a red rectangle at bottom left, in the middle of the Dashboard it reads "No containers running", and nothing is clickable, not even the close (x). 

Now, as I was typing this, the Docker Dashboard just went blank with only the blue header across the top of the dashboard. Nothing in that blue header is responding (Docker logo, Upgrade button, gear icon, bug icon, my name, minimize, maximize or close. 

Next, I right-clicked on the icon in the icon tray and clicked "Troubleshoot", but nothing happens. I tried clicking the other icons and nothing happens. This is on a freshly rebooted PC, by the way. 

Since I can't close it, I have to go to Task Manager to close. When I click on Container List everything closes, but the white tray icon is still there. When I hover over it, it says "Docker is up-to-date". 

When I was finally able to reopen Docker Dashboard, it shows the original view again, with the red rectangle at the bottom. Still nothing is clickable: Containers/Apps, Images, Explore more in the Docker Docs", and all the icons in the header.

*** UPDATE ***
Now the Docker Dashboard is responding to clicks, but there red rectangle at the bottom is still there and says "FAILED TO START" on hover. The Troubleshoot page doesn't help. I don't want to risk clean/purge data or reset to factory defaults. Still my containers do not appear (No containers running). Despite changing a few settings, the "Apply & Restart" button is never enabled.

Also, I tried the solution here (https://github.com/docker/for-win/issues/7353), but my issue doesn't appear the same. When I open PowerShell and type "Start-VM -Name DockerDesktopVM", it changes state to "Running", yet my Docker Dashboard doesn't change and still doesn't show containers. 

So I went to PowerShell and tried to launch it this way, but no success:

```
PS C:\WINDOWS\system32> docker run -dit --name author -e "AEM_RUNMODE=-Dsling.run.modes=author,crx3,crx3tar,dev" -p 4502:8080 -p 30303:58242 aemdesign/aem
docker: Error response from daemon: open \\.\pipe\docker_engine_linux: The system cannot find the file specified.
See 'docker run --help'.
PS C:\WINDOWS\system32>
```

### Expected behavior
Docker Docker should run where I can start my aemdesign/aem container. 

### Information

  - Windows Version:
  - Docker Desktop Version: Docker version 20.10.2, build 2291f61
  - WSL2 or Hyper-V backend? Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Rebooting PC will reproduce the problem.
  2. ...

**Comment by kayest** [comment]
Is there anything I could have done to get a response to my issue above? I'm once again faced with this exact same issue after rebooting my Windows 10 PC.

**Comment by maxiride** [comment]
Likely a duplicate of #4495

**Comment by sajidmanzar** [comment]
If you have Anaconda or XAMPP installed and running in your computer then uninstall first then try to run Docker. Because of both run on localhost.
