### ISSUE TITLE
Docker with WSL2 on has bad performance with mounted local volumes

### ISSUE THREAD

**Issue by denisvmedia** [docker/for-win#10476]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

When working with a large number of small files (like Symfony cache), it takes too much time to generate the cache, and also sporadically fails to delete a temporary directory saying something like `Failed to remove directory "/var/www/html/var/cache/de~/twig": rmdir(/var/www/html/var/cache/de~/twig): Directory not empty.`. Also mysql 8 refuses to start if the directory is mounted from the local host (and I have a reason to do that this way) saying `[Server] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive`. No solution (apart using a managed volume or switching back to Hyper-V) worked for me.

### Expected behavior

I expect mounted/bound local volumes to work the same way without issues like it used to be in the Hyper-V mode. Or even faster (as the option hint says).

### Information

  - Windows Version: Windows 10, Version 1909 (OS Build 18363.1379)
  - Docker Desktop Version: v20.10.2
  - WSL2 or Hyper-V backend?  WSL2 backend (no problems with the Hyper-V backend)
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no.

### Steps to reproduce the behavior

  1. [This](https://github.com/eko/docker-symfony) repository can be used to install Symfony.
  2. `docker-compose up -d`
  3. `docker-compose exec php bin/console cache:clear`

I will expect the cache to be clearer, but most likely it will die because it can't delete a directory. If it succeeds one time, give it another try. It will show that it's unreliable.

P.S. [Such problem existed long](https://github.com/docker/for-win/issues/394) time ago with Hyper-V backed Docker (I also reported it). But later you somehow solved it. Now it's back again with WSL2.

**Comment by stephen-turner** [comment]
Are your files stored in your Windows filesystem or your Linux filesystem? We strongly recommend the latter: see https://docs.docker.com/docker-for-windows/wsl/#best-practices.

**Comment by stephen-turner** [comment]
To be clear, in WSL 2 mode, we don't manage the file sharing, the operating system does it.

**Comment by denisvmedia** [comment]
Unfortunately, I can't do that nor I want to do this, since adding files to a linux filesystem has its own problems (fs events for example). See [this](https://github.com/microsoft/WSL/issues/4739). 

P.S. I can live with slow performance of mounted volumes, but it's broken... Do you think it's the OS itself where it's broken?

**Comment by stephen-turner** [comment]
I'm not quite sure what you mean about the filesystem events because that's one of the reasons why we recommend keeping your files on the Linux side of the fence: so that the containers see the filesystem events when the files change.

I haven't heard of a correctness issue. I wonder if the application itself might time out the operation if it got too far behind, so I think I would like to see a simpler example using only filesystem primitives to pinpoint where the failure occurs. Also whether it can be reproduced in WSL 2 independent of Docker.

**Comment by denisvmedia** [comment]
As of FS events, what is a problem is that file changes are not catchable on the side of Windows - i.e. your host OS and thus IDE will not detect that a file was changed on the remote (and Linux FS is here a remote FS idiomatically). There is a solution with VSCode, but what if you use something else?

Also, as I mentioned in the related thread at Microsoft is that I tend to trust to my physical FS, but I don't trust the FS inside the VM, especially considering that it wasn't me who explicitly created the volume.

> whether it can be reproduced in WSL 2 independent of Docker.

My competence is not enough here, unfortunately :(
