### ISSUE TITLE
com.docker.cli": executable file not found in %PATH%

### ISSUE THREAD

**Issue by brink668** [docker/for-win#10470]
After installing Docker on Windows I received this "com.docker.cli": executable file not found in %PATH%"

The fix for me was during the install a ";" semicolon was prefixed in the environmental path variable.  I had to delete this "prefixed ;" semincolon.

**Comment by stuartmacfarlane** [comment]
Confirmed this also fixed the issue for me, there was an extra semicolon at the start of the system path variable:

![image](https://user-images.githubusercontent.com/10659784/109504885-f1c60600-7a93-11eb-977d-15a4886c29ca.png)
