### ISSUE TITLE
Failed to restart

### ISSUE THREAD

**Issue by shjellvik** [docker/for-win#10487]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 19AC40D5-C52B-4450-87EB-D0B08C25D111/20210226143257

### Actual behavior
Install and initial startup ok. After a while stops responding and then fails to restart. Docker cli commands hangs indefinitely.
### Expected behavior
Restart should be quick and without failure. Docker cli commands should not hang.
### Information

  - Windows Version: 10.0.19041
  - Docker Desktop Version: 3.1.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

Suspect Trend Antivirus to cause problems. Have tried advice given in https://docs.docker.com/engine/security/antivirus/, but it still fails.

**Comment by t0mm00re** [comment]
I also have this problem, assume it's the same one that keeps cropping up similar to: #7263

**Comment by shjellvik** [comment]
Tried the suggested exclusions in https://github.com/docker/for-win/issues/7263#issuecomment-733843115, but still it will not work. We also run Trend Apex One corporately, but some settings are left open for the user.

**Comment by shjellvik** [comment]
Trend Apex One Security Agent is not best of friends with Docker Desktop currently. I have tried to tweak with the exceptions settings for this security software and many times it seemed to work for a while. Then next day it had frozen again. Today it still works, perhaps because I put dockerd.exe as a trusted program in addition to exceptions for serveral of the programs under C:\Program Files\Docker\Docker\resources.  Anyway the problem cause seems to be the security software and not Docker Desktop.
