### ISSUE TITLE
Docker desktop fails to start

### ISSUE THREAD

**Issue by vmato** [docker/for-win#10480]
- [ x ] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features
  - [ x ] I have uploaded Diagnostics
  - Diagnostics ID: D1CB7CA-4154-40A6-B4A1-343F481B3C61/20210226000943

### Actual behavior

WSL distro stopped while waiting for Lifecycle server.
  >Stdout:

  >Stderr:
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:842
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:950
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).Execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:887
main.main
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:30
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374
rootfs mountiso version-pack
main.setupRootFS
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:398
main.doRun
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:235
main.run.func1
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:88
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:842
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:950
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).Execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:887
main.main
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:30
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374

### Expected behavior

Start normally

### Information

  - Windows Version: Windows 10 19042.804
  - Docker Desktop Version: 3.1
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: N

### Steps to reproduce the behavior

Update docker desktop to v3.1

**Comment by lostpebble** [comment]
Getting the same behaviour on 3.1.0. It just says "Docker is starting" forever. Also using WSL2.

It worked the first time, on a fresh install. But now it refuses to start.

**Comment by rob-baldwin** [comment]
Thank you @lostpebble, you're update about the compressed folder solved my issue as well.

Given the number of issues being reported about this issue, it might be a good idea to have this solution in a more prominent place.
