### ISSUE TITLE
Contexts are not being created

### ISSUE THREAD

**Issue by rfire12** [docker/for-win#10488]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 7BA2D5F7-BDEE-4A87-9445-2729FDD5C816/20210227021142

### Actual behavior
When I try to create a context, I get the following: 
`"docker context create" requires exactly 1 argument.`
### Expected behavior
The context should be created after executing the command.
### Information

  - Windows Version: **2004 version 10.0.19041**
  - Docker Desktop Version: **3.1.0**
  - WSL2 or Hyper-V backend?  **WSL2**
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: **No**

### Steps to reproduce the behavior
1. Go to WSL
2. Paste the following command:  `docker context create ‐‐docker "host=ssh://user@remotemachine" remote`
3. After running the command, a message appears saying that docker requires exactly 1 argument, even though it is being supplied.

### Additional info
- Creating the context without any arguments, creates the context. But if you try to update it passing some arguments, the same error message will appear, and the context won't be updated.
- This is not happening on linux. The command works right away on it.

**Comment by stephen-turner** [comment]
You have some stray control characters between "create" and "docker". If you retype it, it will work.
