### ISSUE TITLE
Docker Desktop WSL Distro crashes

### ISSUE THREAD

**Issue by santhoshjanan** [docker/for-win#10482]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:5E9D7089-CDD6-435E-9413-9489FCD9C433/20210226042140

### Actual behavior
Start Docker
### Expected behavior
Docker desktop crashes
### Information
Keeps on crashing. tried multiple times. This was happening earlier also. but on the second start, it used to work.
  - WSL2 backend?  

### Steps to reproduce the behavior
  1. Just starting the docker itself will crash it.

**Comment by nvborisenko** [comment]
The following commands makes docker live at least
```
wsl --unregister docker-desktop-data
wsl --unregister docker-desktop
```

Not sure what is impact, may be you will loose images/containers.
