### ISSUE TITLE
Upgrade Kubernetes to 1.20.4

### ISSUE THREAD

**Issue by juergenzimmermann** [docker/for-win#10490]
- [X] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Kubernetes 1.19.3 is included in Docker Desktop 3.1.0. Kubernetes 1.20.4 is available, and also a beta for Kubernetes 1.21: https://github.com/kubernetes/kubernetes/releases

### Expected behavior
Using the same Kubernetes release in both the development and the production environment is desirable.

### Information
  - Windows Version: Windows 10 Enterprise 2004 Build 19041
  - Docker Desktop Version: 3.1.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

**Comment by stephen-turner** [comment]
Thanks for the heads-up. We did upgrade to 1.20 internally, but we had some regressions with it that we haven't yet managed to fix, so at the moment we're still on 1.19.
