### ISSUE TITLE
Failed to set version to docker-desktop: exit code: -1

### ISSUE THREAD

**Issue by abracadaber** [docker/for-win#10493]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 7F846A2D-AA07-49B3-9224-B484E34127D5/20210228084655

### Actual behavior
I have got Error window with crash report about  **Failed to set version to docker-desktop: exit code: -1** with unprintable characters from docker's(?) stdout.

### Expected behavior
Docker desktop up and running.

### Information

  - Windows Version: Windows 10 Pro (Id: 2009, Build: 19042)
  - Docker Desktop Version: 3.1.0 (51484)
  - WSL2 or Hyper-V backend?  wsl2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Steps to reproduce the behavior

  1. Start Docker desktop
  2. Get Error window

**Comment by stephen-turner** [comment]
It appears that you haven't installed WSL 2 correctly, which Docker Desktop uses. Please follow Microsoft's instructions at https://aka.ms/wsl2-install. If it's set up correctly, then the command wsl -l -v should show a version 2 distro.

**Comment by abracadaber** [comment]
WSL2 was installed and docker used to work well before yesterday. The promblem has gone after complete reinstall WSL's ubuntu. Closing this issue.
