### ISSUE TITLE
WSL2 integration does not support --net=host

### ISSUE THREAD

**Issue by jbcpollak** [docker/for-win#10509]
This is a continuation of https://github.com/docker/for-win/issues/6736.

[ x]  I have tried with the latest version of my channel (Stable or Edge): yes, stable
[ ]  I have uploaded Diagnostics Diagnostics ID:

### Expected behavior
When running a container with --net=host inside a WSL2 environment, I can access the ports of the service it runs, at least from within the WSL2 environment.

### Actual behavior
The ports of the service running inside the container are not reachable, neither from within the WSL2 environment nor from Windows.

### Information
Windows Version: 10.0.19042.804
Docker Desktop Version: 3.1.0 (51484)
Docker version 20.10.2, build 2291f61
Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Usecase

In my case, I am running ROS (specifically the roscore and some ros nodes) within a docker container, and then I'd like to connect to them from the host. The problem with ROS is that it dynamically assigns ports both within the host and container in an unknow range of ports

As mentioned in: https://github.com/docker/for-win/issues/6736#issuecomment-630015038
> Docker daemon runs inside an isolated network namespace with WSL2 backend. --net=host means "run my container in the network namespace where docker daemon runs", which is not the same as your distro's.
> To workaround that, you should explicitly expose ports (using -p flag). Exposed ports are tunelled to both the main WSL2 network namespace and windows host.

This makes sense, but unfortunately it makes running legacy applications that need free form host-container port interactions impossible. 

As @roelofberg mentioned, this is also an issue for TFTP and other protocols:

> When operating a TFTP server (or similar protocols) inside docker --net=host was quite handy. TFTP is a UDP protocol, the tftp server is reached on one certain port (69) and then connects back to the sender by any arbitrary port the sender chose. The back-connection does not happen in my experiments when I don't allow the outbound ports to be reached. Defining an arbitrary port range with tens of thousands of ports with the -p option (if this would even help) is something I'd like to avoid. For such protocols --net=host was an apropriate solution. However, in WSL2 I haven't seen it running yet.

Is there any way to revert to the previous behavior or work around this short of switching up the architecture of our applications themselves (which in the case of ROS1 or TFTP I suspect is not likely to happen)?

**Comment by stephen-turner** [comment]
No, sorry, as explained by @simonferquel in the previous ticket, there is no way to achieve this in the WSL 2 architecture. He already gave the best workarounds in that ticket.
