### ISSUE TITLE
Windows container cannot resolve host.docker.internal, but Linux container can.

### ISSUE THREAD

**Issue by chambersDon** [docker/for-win#10504]
My windows docker container cannot resolve host.docker.internal, but it's working with Linux containers.
I am on version 20.10.2.  Could this be bug [1976 ](https://github.com/docker/for-win/issues/1976)reported for version 18?  

My application gives this runtime error:
`System.Net.Sockets.SocketException: No such host is known`

I've tried pinging host.docker.internal.
```
C:\app>ping host.docker.internal 
Ping request could not find host host.docker.internal. Please check the name and try again.

Here is my dockefFile:
```
FROM mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019
ARG source
WORKDIR /app
COPY ${source:-SampleApp/obj/Docker/publish} .
ENTRYPOINT ["C:\\app\\SampleApp.exe"]
```

I also get the error with the command below, which is easier to reproduce:
docker run -d mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019 ping host.docker.internal

I am Hyper-V backed.
**Docker version**
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:14:16 2020
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:26:48 2020
  OS/Arch:          windows/amd


I've tried this on two machines with the same result.

Diagnostics Bundle: C:\Users\CTCRRM~1\AppData\Local\Temp\1\AF0D2985-D97C-43EA-AD43-31EADA397DA0\20210301155047.zip
Diagnostics ID:     AF0D2985-D97C-43EA-AD43-31EADA397DA0/20210301155047 (uploaded)

**Comment by mikedennis** [comment]
I'm having similar problems. Inside my container:
``` 
C:\inetpub\wwwroot>nslookup host.docker.internal
Server:  UnKnown
Address:  172.30.192.1

*** UnKnown can't find host.docker.internal: Server failed

C:\inetpub\wwwroot>ping host.docker.internal
Ping request could not find host host.docker.internal. Please check the name and try again.
```
The image I am using is: mcr.microsoft.com/dotnet/framework/aspnet:4.7.2-windowsservercore-ltsc2019

Docker Desktop on Win10 - DockerEngine v20.10.2

**Comment by damonsential** [comment]
Running into this issue as well:

`docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.9
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:14:53 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:26:56 2021
  OS/Arch:          windows/amd64
  Experimental:     true`

**Comment by doggy8088** [comment]
This issue was been tracking here: https://github.com/docker/for-win/issues/1976
