### ISSUE TITLE
'RUN mv' instruction removes file instead of moving it

### ISSUE THREAD

**Issue by FFLSH** [docker/for-win#1051]
Given a directory structure such as:

```
C:/
└ dist/
    └ config/
       └ settings.json
         Dockerfile
```
And a Dockerfile such as:

```
FROM microsoft/iis

COPY . C:/src

RUN powershell mv "C:/src/config/settings.json" "C:/"
```

When you run `cd C:/dist; docker build -f config/Dockerfile .` and examine the contents of the resulting image, the directory is:

```
C:/
└ src/
    └ config/
       └ Dockerfile
```

Whereas, due to the `RUN` instruction, it should be 

```
C:/
└ settings.json
  src/
    └ config/
       └ Dockerfile
```

It appears that the `mv` command in the `RUN` instruction is doing the first part in removing the file from the source location, but not the second part of creating the file in the destination. So we end up with the file just being removed from the container. I'm filing this in `docker/for-win` instead of the `microsoft/iis-docker` repo as this seems like a permissions issue just from gut feeling. I've looked through the container's event logs using `get-eventlog -logname application` but there is nothing readily apparent that is related to this issue.

Workaround is to use `cp` and `rm` instead.

**Comment by benmccallum** [comment]
@FFLSH , OMFG this is ridiculous!!!

I've been pulling my hair out all afternoon trying to figure out why a `File.Move` from a dotnet global tool would "succeed" but the file was "never moved". Turns out I was probably experiencing what you were. 

This, plus no globbing support is really killing docker for me.
