### ISSUE TITLE
[3.2.0] Enabling Kubernetes is hanging

### ISSUE THREAD

**Issue by juergenzimmermann** [docker/for-win#10512]
- [ X] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics

### Actual behavior
When I click _Enable Kubernetes_ and then _Apply & Restart_ within the _Settings_ dialogue then Docker Desktop is hanging.

### Expected behavior
Enabling Kubernetes should work as in 3.1.0

### Information
I uninstalled 3.1.0 and removed the files and directories in `$env:LOCALAPPDATA`, `$env:APPDATA`, `C:\Program Files`, and `C:\ProgramData`. Then I made a fresh install of Docker Desktop 3.2.0.

  - Windows Version: Windows 10 Enterprise 2004
  - Docker Desktop Version: 3.2.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior
Install 3.2.0 and try to enable Kubernetes.

**Comment by wwirt** [comment]
I was able to resolve the issue by stopping Docker, renaming the `pki` folder in C:\Users\$USER\AppData\Local\Docker (`%LocalAppData%\Docker`), and then restarting Docker. The first time you start up Docker it may recreate the files and cause the engine to stall so you may have to restart it again.

This may be an issue with installing the certificates used by Kubernetes, causing the heath checks to fail.

**Comment by juergenzimmermann** [comment]
After uninstalling and installing the new release Docker Desktop _3.2.1_, the issue is gone.
