### ISSUE TITLE
Running nvidia-smi crashes with WSL with gpu support

### ISSUE THREAD

**Issue by ashaw596** [docker/for-win#10524]
Running `docker run --rm -e NVIDIA_VISIBLE_DEVICES=all nvidia/cuda:11.0-base nvidia-smi ` causes the error

> docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "nvidia-smi": executable file not found in $PATH: unknown.

Other nvidia container calls work correctly

**Comment by stephen-turner** [comment]
Have you followed all the instructions at https://docs.docker.com/docker-for-windows/wsl/#gpu-support including being on the latest Insiders build of Windows?

**Comment by ashaw596** [comment]
I have followed all those instructions. In nvidia's website it says.
`nvidia-smi is now supported but in order to use it, please copy it to /usr/bin and set appropriate permissions with the below commands:
cp /usr/lib/wsl/lib/nvidia-smi /usr/bin/nvidia-smi
chmod ogu+x /usr/bin/nvidia-smi`

**Comment by stephen-turner** [comment]
I wonder if it's related to this Nvidia bug: NVIDIA/nvidia-docker#1409
