### ISSUE TITLE
Docker run crashes if Dockerfile contains at least 40 instructions

### ISSUE THREAD

**Issue by apetres** [docker/for-win#1052]
### Expected behavior

Image built from Dockerfile having at least 40 instructions can be run by _docker run_

### Actual behavior

Docker crashes:
```
PS C:\tmp\docker> docker run test
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container 1bd90ba869185b1f96b476135f13d45dacd8b1768b85be7d0d3273b979064902 encountered an error during Start: failure in a Windows system call: The compute system exited unexpectedly. (0
xc0370106).
```

### Information

  - Diagnostic ID: 64ED47AF-047A-4425-86A4-627DFDE197DC/2017-08-30_16-56-14
  - Docker version: 17.06.0-ce-rc4
  - OS: Windows 10 Version 1607, build 17393.1593
  - Dockerfile:
```
FROM microsoft/windowsservercore

RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
```

If I remove one line, the resulted image can be run successfully. Also if there are more RUN instructions, the _build_ command fails with the same error message.
May be related to https://github.com/docker/for-win/issues/902

### Steps to reproduce the behavior

  1. Build using the Dockerfile above: _docker build -t test ._
  2. Run the image created: _docker run test_
  3. Get the error message

**Comment by kavinkumar** [comment]
I'm facing this exact same issue. I'm using microsoft/mssql-server-windows-developer as base for building my image. The microsoft/mssql-server-windows-developer dockerfile has 14 instructions and the dockerfile i wrote has 30 instructions. Since total number of instructions is 44, the resulting image from my dockerfile, fails to create a container with the exact same error. On removing minimum of 4 instructions from my dockerfile, the resulting image is able to create containers successfully.

Quick fix for this issue, would be appreciated.

**Comment by danyalKhaliq10p** [comment]
Exact same error here as well . Only sometimes it works but most of the time the error 
"The compute system exited unexpectedly" , don’t know if its related to memory or something else .
any help would be highly appreciated .

**Comment by aemery** [comment]
Same issue here as well. In my case, 31 steps in the was the limit. Trying to run this container in a swarm failed repeatedly until one was able to boot after a variable number of retries. Adding a 32nd step to the dockerfile broke the docker build.

Both the run and the build failed with the same error as mentioned in the original post.

**Comment by cowlinator** [comment]
I am experiencing the same issue with version 17.09.1-ce (not using swarm).
My limit is 29 instructions.  Adding `RUN echo Hello` as the 30th instruction causes the image to be un-runnable with the error `docker: Error response from daemon: container 6f2931442322d478140200fd43ba0bf2c8bc492be0cbfd31cc7f5e1238778384 encountered an error during Start: failure in a Windows system call: The compute system exited unexpectedly. (0xc0370106).`

**Comment by omerglam** [comment]
Been experiencing the same problem, i was able to circumvent the issue by combining commands to a single RUN instruction like so:

`
FROM microsoft/windowsservercore

RUN echo Hello && \ 
 echo Hello && \ 
 echo Hello && \ 
 echo Hello && \ 
	.
	.
	.
 echo Hello && \ 
 echo Hello && \ 
 echo Hello 
`

**Comment by omerglam** [comment]
Been experiencing the same problem, i was able to circumvent the issue by combining commands to a single RUN instruction like so:

```
FROM microsoft/windowsservercore

RUN echo Hello && \ 
 echo Hello && \ 
 echo Hello && \ 
 echo Hello && \ 
	.
	.
	. 
 echo Hello && \ 
 echo Hello && \ 
 echo Hello && \ 
 echo Hello 
 ```

**Comment by yusuf-gunaydin** [comment]
It seems like the issue is related with Windows versions.

I can reproduce the issue on:

```
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.16299 Build 16299
```

But it works successfully on:

```
OS Name	Microsoft Windows Server 2016 Standard
Version	10.0.14393 Build 14393
```

**Comment by evmurphy** [comment]
Does anyone know if redesigning your docker file to use multi-stage builds can bypass this issue? I haven't implemented multi-stage builds in my project yet but a simple test was promising.
The following Dockerfile reproduced the error - `Error response from daemon: container 087743584ab919adfb237b7feb8f72b15fbe3207d7f034f4025099f62dd64cde encountered an error during Start: failure in a Windows system call: The compute system exited unexpectedly. (0xc0370106).` as expected:
```
FROM microsoft/windowsservercore

RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
RUN echo Hello
```

But the image ran successfully after adding another stage to the Dockerfile before the last RUN command:

```
...
...
...
RUN echo Hello

FROM microsoft/windowsservercore

RUN echo Hello
```

**Comment by jhowardmsft** [comment]
This is another instance of https://github.com/moby/moby/issues/32838#issuecomment-356420442 where the utility VM is crashing.

**Comment by JensNordenbro** [comment]
Is there any estimates on when this will be solved?

**Comment by thaJeztah** [comment]
Based on https://github.com/moby/moby/issues/32838#issuecomment-399622268, this is not a bug in Docker but a platform (Windows) issue; that comment contains information about versions of Windows and/or the base image that's used to resolve the issue.

**Comment by apetres** [comment]
I cannot reproduce it anymore. What I did is (probably not all of them are needed):
- used base image _microsoft/windowsservercore:1709_KB4284819_
- updated Windows to _1803_
- updated Docker to _18.06.1-ce_
