### ISSUE TITLE
Docker Desktop hangs after some time

### ISSUE THREAD

**Issue by SebastianKrog** [docker/for-win#10531]
- [x ] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 255C0A7-4ED7-853A-5FC48D630E1E/20210303092751

### Actual behavior
After bootup Docker Desktop starts and correctly lists images and containers. Containers can be started, stopped etc. without a problem.
Docker runs as espected, also in CLI from both PowerShell and the Ubuntu terminal.

After some time (minutes), Docker Desktop stops responding to commands. It will not start, stop or restart images. It gives the error "(HTTP code 500) server error - i/o timeout" after each press. Restarting docker does not work and the only way to gain control is to reboot the system.

![Udklip](https://user-images.githubusercontent.com/4109/109823046-da278280-7c37-11eb-9733-eea903aca64f.PNG)

Running docker through the cli will hang on any command that actually connects to the daemon (ie. `docker --version` is fine but `docker ps`, `docker info` or `docker run` will hang). By hang, it will just wait indefinitely. Sometimes it will resume after minutes, other times it will just never resume, and still other times (rearely) it will fail with a timeout or connection error.

![cli_hang_ps](https://user-images.githubusercontent.com/4109/109823487-42766400-7c38-11eb-8352-80b559a26353.PNG)
![cli_hang_ubuntu](https://user-images.githubusercontent.com/4109/109823490-44d8be00-7c38-11eb-917e-72bdbbfe1736.PNG)

Any docker containers that were already running work without a problem. E.g. having a rocker/rstudio container running on port 8787 will still connect and work as espected even if Docker Desktop is giving i/o timeout errors and the docker cli hangs.

![container_works](https://user-images.githubusercontent.com/4109/109823788-89fcf000-7c38-11eb-9957-bfc56b6c432d.PNG)

This seems more prone to happen in the middle of a `docker pull` -- here it will hang in the middle of downloading an image. Often, there will be no error or restart. It will just wait at e.g. 187 mb / 267 mb indefinitely and never resume. This then coincides with Docker Desktop giving the above errors.

### Expected behavior
Docker Desktop doesn't randomly hang.

### Information

  - Windows Version: Windows 20H2 version 19042 
  - Docker Desktop Version: 3.2.0 (have also tried 3.1.0, 3.0.4 and 2.5.X)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

I have only recently started using Docker Desktop and this issue has been here since I initially installed it. I have tried multiple versions of Docker. Also tried on both Ubuntu 20.04 and 18.04 on WSL2.

This seems related to #8981 and possibly #9122 . Those two reports are from Hyper-V setups, though. I am also running on a corporate PC with Trend Micro anti virus software that I cannot disable (unknown if related).

Other issues that I have thought might be related but I cannot recognize: there are no connection errors between WSL and the internet, no DSL errors and no connection/DSL errors from within containers.

### Steps to reproduce the behavior

  1. Start Docker Desktop
  2. Wait for it to hang
  3. Or start a `docker pull` on a big image, which sometimes seems to trigger it(?)

**Comment by SebastianKrog** [comment]
So seems to be more related to #9122 than i thought. Running version 2.3.0.5 without any issues.

**Comment by matt-psaltis** [comment]
Possibly seeing the same here with just Windows defender, no other AV software been near this machine. Same version and symptoms as OP.

**Comment by matt-psaltis** [comment]
For me ruled out Windows Defender and Macrium Reflect (was thinking VSS snapshots).

**Comment by t-huebner** [comment]
Exactly the same here. Windows 10, WSL 2, **Trend Micro** which I can't disable.

- Every release after 2.3.0.5 doesn't work reliably. 
- I tried 3.2.2 -> hangs after a few seconds
- After uninstall an reinstall 2.3.0.5 everything works like a charm.

Tested under Windows 10 (build 2004 and 20H2 - makes no difference).

**Comment by t-huebner** [comment]
Same issue with Docker 3.3.0

**Comment by TommyRush** [comment]
I get this too with Docker 3.3.1 and I also have Tend Micro

**Comment by t-huebner** [comment]
We disabled trend micro for testing purposes and now Docker works fine even with versions >= 2.4. A permanent solution is still being sought. Until then, we will have to switch to Docker 2.3.

**Comment by TommyRush** [comment]
For what it's worth, I think for me it started happening when the Firewall was enabled in Trend Micro. The antivirus part running for a while without issue for me. But, I immediately had problems using docker when I asked if I could have a firewall on my computer, which was when Trend Micro's was enabled. At some point we are going to try turning it off and using the Windows built in firewall to see if that helps. 

I am also using Docker 2.3 right now as a short term fix.

**Comment by t-huebner** [comment]
We've excluded the following files from behavior and real-time file scan:

c:\ProgramData\Docker\cli-plugins\docker-app.exe
c:\ProgramData\Docker\cli-plugins\docker-buildx.exe
c:\ProgramData\Docker\cli-plugins\docker-scan.exe
c:\Program Files\Docker\Docker\resources\com.docker.backend.exe
c:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe
c:\Program Files\Docker\Docker\resources\com.docker.proxy.exe
c:\Program Files\Docker\Docker\resources\com.docker.wsl-distro-proxy.exe
c:\Program Files\Docker\Docker\resources\docker.exe
c:\Program Files\Docker\Docker\resources\dockerd.exe
c:\Program Files\Docker\Docker\resources\snyk.exe
c:\Program Files\Docker\Docker\resources\vpnkit.exe
c:\Program Files\Docker\Docker\resources\vpnkit-bridge.exe
c:\Program Files\Docker\Docker\resources\cli-plugins\docker-app.exe
c:\Program Files\Docker\Docker\resources\cli-plugins\docker-buildx.exe
c:\Program Files\Docker\Docker\resources\cli-plugins\docker-scan.exe
c:\Program Files\Docker\Docker\resources\bin\com.docker.cli.exe
c:\Program Files\Docker\Docker\resources\bin\docker-compose.exe
c:\Program Files\Docker\Docker\resources\bin\docker-credential-desktop.exe
c:\Program Files\Docker\Docker\resources\bin\docker-credential-ecr-login.exe
c:\Program Files\Docker\Docker\resources\bin\docker-credential-wincred.exe
c:\Program Files\Docker\Docker\resources\bin\hub-tool.exe
c:\Program Files\Docker\Docker\resources\bin\kubectl.exe
c:\Program Files\Docker\Docker\resources\bin\notary.exe
c:\Windows\System32\Vmms.exe
c:\Windows\System32\Vmwp.exe
c:\Windows\System32\Vmsp.exe
c:\Windows\System32\Vmcompute.exe

It seems to work now! Can someone try this out and confirm?

**Comment by t-huebner** [comment]
My docker setup (3.3.1) is still working fine with Trend Micro Apex One and those exception settings above.

**Comment by TommyRush** [comment]
Thank you, we added the same exceptions and Docker 3.3.1 seems to be find with Trend Micro running now. We also stopped using Trend as a firewall, but I think it was your exceptions that fixed it.

**Comment by t-huebner** [comment]
That's nice to hear!

Here are some links concerning the exceptions:
- https://docs.docker.com/engine/security/antivirus/  (official docker recommendation, I think not enough...)
- https://docs.microsoft.com/en-US/troubleshoot/windows-server/virtualization/antivirus-exclusions-for-hyper-v-hosts (see section "Process")
- https://github.com/docker/for-win/issues/7263 (some of Docker's binaries were mentioned here, I've just extended the list)
