### ISSUE TITLE
Dashboard, Settings, and Others Not Appearing from System Tray Menu

### ISSUE THREAD

**Issue by ezatoptum** [docker/for-win#10534]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 74B118C1-A3AB-4490-9760-4E480147F7C9/20210303174506

### Actual behavior
Left click Moby in System Tray, menu appears.  But most choices like Dashboard, Settings, About, etc.  do not appear when clicked.  Just see blue spinning circle icon for a second or two. 
Docker and Kubernetes are working despite being unable to access any Docker Desktop UI screen.

### Expected behavior
Dashboard to appear after clicking choice from system tray menu.  Same for all menu choices.

### Information

  - Windows Version: 1909 (18363.1316)
  - Docker Desktop Version: 3.2.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mwinkler** [comment]
same issue here...
