### ISSUE TITLE
Upgrading Docker removes Docker from the system path

### ISSUE THREAD

**Issue by sgreenmsft** [docker/for-win#1053]
After *upgrading* to Docker version 17.06.1-ce-win24 (13025), docker.exe's location is removed from the system path.

This causes problems for users and systems that rely on Docker being in the path.

**Comment by jasonbivins** [comment]
Hi @sgreenmsft 

We did notice this as an issue on a couple of builds - and a reboot seems to have fixed it.
Are you still seeing this problem with your users?

**Comment by andrew-s** [comment]
Literally just had this with the latest update, it got removed from the system path but didn't get added again (just manually added it back in for the moment).
