### ISSUE TITLE
Docker does not start, it hangs in the state 'Docker is Starting'

### ISSUE THREAD

**Issue by melihtt** [docker/for-win#1054]
### Expected behavior
I can start docker on Windows 10

### Actual behavior
When I try to start Docker, it does not start. it freezes.

### Information

  - Diagnostic ID: 18A3C39A-27CD-4886-903B-0244DF086446/2017-08-31_19-39-51
  - a reproducible case: When I restart docker service, When I restart computer, When I reinstall docker
  - host distribution and version (Windows 10 Enterprise, Version 1607,  build number: 14393.1480)
  - Windows features
       Containers [off]
       Hyper-V[on]
         
  - Result of the command 'docker version':
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:48:20 2017
 OS/Arch:      windows/amd64
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.30/version: open //./pipe/docker_engine: The system c
annot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to
 connect. This error may also indicate that the docker daemon is not running.
    - Result of the command 'docker ps':
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.30/containers/json: open //./pipe/docker_engine: The
system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run ele
vated to connect. This error may also indicate that the docker daemon is not running.

### Steps to reproduce the behavior

  1. Install docker
  2. Start docker
  2. Docker is in the state "Docker is starting" but it doesn't start. It seems to be in freeze state.

**Comment by jasonbivins** [comment]
Hi @melihtt
According to the logs -   The Docker for Windows service isn't running or able to run. Try starting the service manually, and then checking event viewer for an error that's hopefully more helpful.   It might be a kerberos issue - as I am seeing this in the logs coming from windows event viewer:  
``` NtpClient was unable to set a domain peer to use as a time source because of discovery error. NtpClient will try again in 15 minutes and double the reattempt interval thereafter. The error was: The entry is not found. (0x800706E1)```

**Comment by melihtt** [comment]
Docker for Windows service is running. 

![image](https://user-images.githubusercontent.com/17677658/30002494-602c77d8-90b3-11e7-87b2-57e4f1566d2b.png)

I have restarted it and check Event Viewer, Everythign seems ok.

![image](https://user-images.githubusercontent.com/17677658/30002517-bfb83e4e-90b3-11e7-8f79-9433f21f9005.png)
![image](https://user-images.githubusercontent.com/17677658/30002519-c2b7be62-90b3-11e7-881a-143f1a552680.png)

When I try a docker command, following error occurs. 

```
> docker ps
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.30/containers/json: open //./pipe/docker_engine: The
system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run ele
vated to connect. This error may also indicate that the docker daemon is not running.
```
when I try dockerd command, this error occurs. 

```
> dockerd
dockerd : The term 'dockerd' is not recognized as the name of a cmdlet, function, script file, or operable program. Che
ck the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ dockerd
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (dockerd:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

It seems somehow dockerd is not started or it is not registered to system so docker could not find it. 
Docker window service seems running. I assume dockerd is this Windows service for Windows platforms. am I wrong? Should I make any configuration to make dockerd commnd works.

With this symphtons, what shall I try next?

**Comment by melihtt** [comment]
I have realised that The antivirus program (Kaspersky) listed Docker.Service as 'Low Restricted', but Docker for Windows is listed as 'Trusted' as shown below. 

![image](https://user-images.githubusercontent.com/17677658/30005229-65d31f06-90e6-11e7-81c0-3e0eb3246211.png)

Low Restricted means everything is allowed except for building into operating system modules

Its a work computer and KAspersky is managed by a policy, So I could not changed Docker.Service reputation on Kaspersky. 

Should Docker.service run properly even at 'Low Restricted' mode(interfering operaing system modules are not allowed) ? Could it be the problem that preventing Docker to start?

**Comment by melihtt** [comment]
One more finding, it may give you a hint.

Docker is using Linux containers, but There is no virtual machine listed in Hyper-V Manager. 

![image](https://user-images.githubusercontent.com/17677658/30006156-d6cbbc36-90fa-11e7-863d-631f38873539.png)

**Comment by jasonbivins** [comment]
@melihtt    That is strange that the MobyLinuxVM is missing  - let's try to create it manually to see if Kaspersky is affecting it.

``` powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -create ```

**Comment by melihtt** [comment]
@jasonbivins , I have disabled Kaspersky and same problem occured. But, today I have downloaded recent updates and problem disappered. My current docker version Version 17.06.2-ce-win27 (13194). With this version problem is resolved. thanks a lot.

**Comment by Danrrodrigues** [comment]
**Work for me in powersheell in 17/10/2018**

 **It looks like Hyper-V didn't get installed correctly either**
Try to remove them, then install manually to see if that helps. Make sure you run powershell as an admin

- Disable-WindowsOptionalFeature -FeatureName microsoft-hyper-v -online
  - (wait, sometimes until now you have decided, if not, continue)
  - restart-computer
- Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All
 - restart-computer 
- Enable-WindowsOptionalFeature -Online -FeatureName Containers -All

or

 - run MOFCOMP %SYSTEMROOT%\System32\WindowsVirtualization.V2.mof in powershell 
 - restarting the Hyper-V Management service
