### ISSUE TITLE
Client tells me to upgrade, even though I have a PRO Dockerhub account.

### ISSUE THREAD

**Issue by nicekiwi** [docker/for-win#10548]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 89396005-4EBB-4852-AA2E-64493029B34C/20210304221314

### Actual behavior
Shows me options to upgrade my account. Even though I have paid for a PRO account.
![image](https://user-images.githubusercontent.com/738975/110036674-3c9c9200-7da2-11eb-892e-321b5cbdf9a7.png)
![image](https://user-images.githubusercontent.com/738975/110036961-a87efa80-7da2-11eb-89c9-372975bef15d.png)

### Expected behavior
Should not show those options, should recognize my account plan status.

### Information

  - Windows Version: Windows 10 Pro - 20H2 - 19042.844
  - Docker Desktop Version: 3.2.0 (61504)
  - WSL2 or Hyper-V backend? N/A
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No.

### Steps to reproduce the behavior

  1. Log into the app with Dockerhub ID.
  2. Look for "Upgrade" button.

Also affects the MacOS app.

**Comment by stephen-turner** [comment]
@nicekiwi Do you have 2FA enabled on your Docker account?

**Comment by nicekiwi** [comment]
@stephen-turner yes I do.

**Comment by StefanScherer** [comment]
Thanks for confirming. We're tracking this issue internally and will work on a fix that you can see your correct plan in Docker Desktop.

**Comment by stephen-turner** [comment]
@fungiboletus I think this is now fixed, could you try again? (No need to download a new version of Desktop, the fix was on the Hub side).

**Comment by nicekiwi** [comment]
@stephen-turner confirmed the client no longer says I'm on the Free plan, though I have a "Pro Plan" and it now says I have a "Team Plan".

**Comment by stephen-turner** [comment]
Are you part of a paid team as well? The team would take priority over an individual Pro account.

**Comment by nicekiwi** [comment]
@stephen-turner ah, yes I am :) sweet.
