### ISSUE TITLE
Docker for windows will not work with hyper-v

### ISSUE THREAD

**Issue by tatmanblue** [docker/for-win#1055]
### Expected behavior
Docker for windows works with hyper-v

### Actual behavior
I installed docker for windows and kitematic per instructions.  when I run kitematic I get this error: "VirtualBox is not installed. Please install it via the Docker Toolbox."   

I followed some direction at sites like "
https://docs.docker.com/machine/drivers/hyper-v/#2-set-up-a-new-external-network-switch-optional" and I was able to create docker machine using command line.  however, kitematic still errors.  I had to manual set environment variables and paths to get it work.

I deleted all of hyper-v images, switch etc.  Deleted C:\Users\mr250210\.docker, delete c:\program files\docker and uninstalled docker for windows, removed all environment variable settings. 

I reinstalled docker for windows and now still cannot get kitematic to work with hyper-v.   a hyper-v image is created but I have other problems now.  keep reading.

I am also have problems with default docker commands like:
d:\>docker
'docker' is not recognized as an internal or external command,
operable program or batch file.

d:\>docker-machine
'docker-machine' is not recognized as an internal or external command,
operable program or batch file.

### Steps to reproduce the behavior

see "Actual behavior" above
![image](https://user-images.githubusercontent.com/20169657/29941947-6be62420-8e51-11e7-8aba-1902fdf88c1d.png)
![image](https://user-images.githubusercontent.com/20169657/29942002-9c1fee00-8e51-11e7-8b35-6496d795a287.png)

**Comment by jasonbivins** [comment]
Hi @tatmanblue 
One of our devs put together a great wiki on [Kitematic](https://github.com/docker/kitematic/wiki/Common-Issues-and-Fixes) that has some troubleshooting and reset scripts included. From what you mention above though - I'd start here.
```If using Docker Toolbox on Windows, check that the account running Kitematic has set DOCKER_TOOLBOX_INSTALL_PATH = C:\Program Files\Docker Toolbox (or whatever the actual path is). If you installed as admin, this is likely not set for your user account.```
