### ISSUE TITLE
Docker Desktop freezes/high CPU usage when disconnected from internet

### ISSUE THREAD

**Issue by camerondurham** [docker/for-win#10563]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 8FFF4EB5-8CDF-4625-8CDA-3C36D7F64533/20210306022000

### Actual behavior

Open Docker Desktop when disconnected from the internet and use the application's
Image/Containers tabs and adjust settings as needed.

### Expected behavior

Docker Desktop freezes when switching from tabs and **Container List** process consumes extra CPU and listed as having **Very High** power usage. Docker Desktop freezes for approximately 3 minutes before becoming usable again. 

### Information

  - I have been able to reproduce 3 times: twice with experimental features enabled, once with experimental features disabled (I can try again)
  - Is the problem new? I am unsure if this is new, I have searched through existing issues and have not sound anything similar. I have not thoroughly searched through closed issues.
  - Did the problem appear with an update? Yes, although I have not used previous versions of Desktop frequently without an internet connection

I have not experienced any issues with the Docker backend. The Docker Engine seems to function normally while the Docker Desktop GUI is frozen. Additionally, the Docker Desktop application seems to function normally as soon as I re-connect to the internet. This behavior seems unusual and unintended, I would expect to be able to use the Docker Desktop application whether I'm connected to the internet or not. Please correct me if that assumption is incorrect.

**Windows Version**
  - Edition	Windows 10 Education
  - Version	20H2
  - OS build	19042.804
  - Experience	Windows Feature Experience Pack 120.2212.551.0

  - Docker Desktop Version: 3.2.1 (61626)
  - WSL2 backend
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Steps to reproduce the behavior

  1. Disconnect PC from internet
  2. Restart computer (may not be necessary)
  3. Open Docker Desktop
  4. Attempt to switch to **Container/Apps** or **Images** tabs
  5. Attempt to open **Settings** menu

Screenshot of Task Manager showing high CPU/power usage by Docker Desktop processes. Screenshot taken after selecting **Containers/Apps** tabs while disconnected from internet.
![screenshot of Task Manager](https://user-images.githubusercontent.com/17013462/110192102-fa467580-7de0-11eb-8c2b-c5f8b0fba1f3.png)

Screenshot of Task Manager and frozen/unresponsive Docker Desktop app, showing high CPU/power usage

![Screenshot 2021-03-05 163921](https://user-images.githubusercontent.com/17013462/110192158-3ed21100-7de1-11eb-9a35-583021f67ac9.png)

**Comment by famod** [comment]
I am seeing a variation of this:
- Docker Desktop is auto-starting when Windows comes up (and I logged in)
- Connect via Cisco AnyConnect (which does still allow Internet access, btw!)
- Open Dashbaord, Settings or whatever -> hangs!

After some time (mostly ages), it will become responsive again.

If I start Docker Desktop (mainly the backend) _after_ I have connected to VPN, the Dashboard is immediately responsive.

**Comment by stephen-turner** [comment]
Thanks for the report, @camerondurham. I have reproduced this and raised an internal ticket.

**Comment by famod** [comment]
@araisch I have to confirm what you are seeing.
The pattern I described previously stopped working for me as well at some point. So there is no workaround, only patience/luck and anger management. 😉

**Comment by stephen-turner** [comment]
This issue is fixed in version 3.2.2, which we have just released.

**Comment by famod** [comment]
@stephen-turner thanks a lot, much better now!

**Comment by skyd0me** [comment]
I'm on version 3.2.2 and nothing changed for me.
Also tried to connect to VPN before starting Docker but nothing really changed.

Container page shows "No containers running" but docker ps shows me 3 running containers.

![image](https://user-images.githubusercontent.com/18167556/113248982-3ecd1000-92be-11eb-8220-38bd4bb8c10c.png)

Images page shows nothing but docker images command shows me > 20 images.

![image](https://user-images.githubusercontent.com/18167556/113249088-6b812780-92be-11eb-862b-39db199d4ce7.png)

The resource consumption is very low.

![image](https://user-images.githubusercontent.com/18167556/113248929-2bba4000-92be-11eb-902a-0a5471dbe317.png)
