### ISSUE TITLE
Project name is ignored when restarting a stack deployed via docker-compose and specified project name

### ISSUE THREAD

**Issue by jonl-percsolutions-com** [docker/for-win#10564]
- [X ] I have tried with the latest version of Docker Desktop
  - [ X] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

The directory name is used when starting a previously started stack.

### Expected behavior

The project name specified via the -p/--project-name switch should be honored

### Information

  - Windows Version: 10
  - Docker Desktop Version: 3.1.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior
  1. Start a docker stack via docker-compose.yaml callign docker-compose -p or docker stack -p from the cli.
  2. Attempt to restart the stack from the docker desktop containers / apps menu
  3. docker windows does not include the name of the stack in Docker Desktop will recreate the stack with the project name as the directory name, giving duplicate containers.

Example, I deployed a stack from a directory called deploy with a project name of ossalabs4, I attempted to restart the stack from from docker desktop.  When this happens, it renames the project deploy.

![image](https://user-images.githubusercontent.com/6088906/110192359-8b2a4a80-7dfb-11eb-816d-3f84cca3c733.png)

**Comment by stephen-turner** [comment]
@jonl-percsolutions-com Thanks for the report. I found that the Stop and Delete buttons also fail: they attempt to stop/delete the instances with the directory name. I've raised an internal ticket.

**Comment by stephen-turner** [comment]
This is now fixed in Docker Desktop 3.3.0.
