### ISSUE TITLE
Failure when upgrading from 3.0.0 to 3.1.0

### ISSUE THREAD

**Issue by ThisLimn0** [docker/for-win#10562]
- [x ] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
When starting the Docker installer from an already installed Docker 3.0.0 environment the Docker 3.1.0 installer fails almost instantly.

### Expected behavior
The Docker installer should install Docker.
### Information
Stack:
Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei CommunityInstaller.UninstallWorkflow.<ProcessAsync>d__14.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei CommunityInstaller.InstallWorkflow.<PerformUninstall>d__27.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei CommunityInstaller.InstallWorkflow.<UninstallAsync>d__30.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()

The problem is reproducible for me when i redownload the installer.
Current Docker Version (uninstalled): 3.0.0
Windows: 20H2 19042.844

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. Uninstall Docker 3.0.0 via Windows Settings
  2. Download Docker windows 3.1.0 Installer
  3. Watch it fail installing instantly
![docker0](https://user-images.githubusercontent.com/67125885/110190602-639ba800-7e24-11eb-9c3c-7084daf179da.png)
![docker1](https://user-images.githubusercontent.com/67125885/110190605-65656b80-7e24-11eb-877e-5464da2d1714.png)

**Comment by tschirmer** [comment]
Same issue here with 3.2.1

![image](https://user-images.githubusercontent.com/3872130/110559730-78fc3380-8190-11eb-8e4e-51e7c0b883f9.png)
