### ISSUE TITLE
When enabling Kubernetes, it's stuck forever at "Starting..."

### ISSUE THREAD

**Issue by saadzimat430** [docker/for-win#10571]
- [ yes ] I have tried with the latest version of Docker Desktop
  - [ yes ] I have tried disabling enabled experimental features
  - [ yes ] I have uploaded Diagnostics
  - Diagnostics ID: BD5756A0-34AD-49DD-9E5C-09B178A75AB9/20210307131814

### Information

  - Windows Version: Windows 10 Pro
  - Docker Desktop Version: 3.1.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by phudson** [comment]
And me. In my case, it was started, but things hung and re-starting never works.

**Comment by jimbrig** [comment]
have the same issue

**Comment by jimbrig** [comment]
> have the same issue

Was able to fix this by enabling Hyper-V extra feature on windows.

**Comment by phudson** [comment]
> 
> 
> And me. In my case, it was started, but things hung and re-starting never works.

I uninstalled everything, deleted any Docker folders left over and re-installed from tehw ebsite. Which installled 3.1.0

This worked.

This morning, Docker updated to 3.2.1 and now the Kubernetes is in "starting..." indefinitely.

So looks like a bug in 3.2.1

(I have Hyper-V enabled, so in my case, it's not that)

**Comment by saadzimat430** [comment]
I recommend using **Minikube** to avoid this problem.

**Comment by phudson** [comment]
> This morning, Docker updated to 3.2.1 and now the Kubernetes is in "starting..." indefinitely.
> 
> So looks like a bug in 3.2.1

I did Clean/Purge data, then reset to factory defaults, then I was able to start Kubernetes with 3.2.1

**Comment by JukkaKeisala** [comment]
My work machine Win 10 Enterprise the update went well and Kubernetes 1.19.7 was there.

In my home machine, Win 10 Home, the update went well but Kubernetes is stuck at Starting...

**Comment by subhayughosh** [comment]
Same issue. Tried fixing it through all the suggested methods, nothing works.

**Comment by santosh835** [comment]
In my case this issue was because of the corporate proxy..when kubernetes
starting for the first time..it downloads required files in order to
start...and corporate proxy was preventing it from download..tried without
connecting to company vpn and it worked

**Comment by michaelvdnet** [comment]
I see this behaviour after resetting the kubernetes cluster from the interface.

Looking into the cluster I can see the `kube-controller-manager` hang in a CrashLoopBackoff with the following error:

`F0314 15:35:33.861926 1 controllermanager.go:244] error building controller context: failed to wait for apiserver being healthy: timed out waiting for the condition: failed to get apiserver /healthz status: Get "https://192.168.65.4:6443/healthz?timeout=32s": x509: certificate is valid for 10.96.0.1, 0.0.0.0, 192.168.65.3, 127.0.0.1, not 192.168.65.4`.

Reinstalling worked the previous time but it isn't really feasible doing that every time.
