### ISSUE TITLE
Win10 Docker One container can't mapping three ports to host, only one port mapping success.

### ISSUE THREAD

**Issue by TotalAnnihilation** [docker/for-win#10573]
- [Yes] I have tried with the latest version of Docker Desktop
  - [No] I have tried disabling enabled experimental features
  - [No ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
I want mapping 3 ports for aria2, but only 1 port mapping success
### Expected behavior
3 ports mapping success
### Information

  - Windows Version: 
  - Win10 18362.53
  - Docker Desktop Version: 
  - 3.1.0（51484）
  - WSL2 or Hyper-V backend?  
  - Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:
  - No，just my PC

  1. I use cmd to create the aria2 container like this:
docker run -d --name aria2 -v G:\download:/mnt -v G:\aria2:/config -e PGID=0 -e PUID=0 -p 10001:6800 -p 10002:16881 -p 10003:8080  --restart always auska/docker-aria2 

  2. check the port in docker like this:
C:\Users\Administrator>docker ps -a
CONTAINER ID   IMAGE                COMMAND                  CREATED          STATUS          PORTS                                                                                                                                     NAMES
a863569e3ad7   auska/docker-aria2   "/init"                  32 minutes ago   Up 20 minutes   0.0.0.0:10001->6800/tcp, :::10001->6800/tcp, 0.0.0.0:10003->8080/tcp, :::10003->8080/tcp, 0.0.0.0:10002->16881/tcp, :::10002->16881/tcp   aria2

3. But cheak the port in host like this:
  TCP    0.0.0.0:9999           WIN-20210201WNK:0      LISTENING
  TCP    0.0.0.0:10003          WIN-20210201WNK:0      LISTENING
  TCP    0.0.0.0:10808          WIN-20210201WNK:0      LISTENING

Only port 10003 is good, 10001&10002 is not work.

I try many times , and it can't work success.

Thank you for help me.

**Comment by stephen-turner** [comment]
This was fixed in 3.2.0. Do a Check for Updates to get the latest version.
