### ISSUE TITLE
docker desktop win10

### ISSUE THREAD

**Issue by sabrabano0** [docker/for-win#10587]
docker run --rm -it --gpus=all nvcr.io/nvidia/k8s/cuda-sample:nbody nobody -gpu -benchmark
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request: unknown.

**Comment by stephen-turner** [comment]
Have you got the correct version of Windows? GPU support is only on the Insiders channel at the moment. See https://docs.docker.com/docker-for-windows/wsl/#gpu-support for all prerequisites.

**Comment by sabrabano0** [comment]
i havd activated my programe insider of windows, install cuda wsl driver on windows
but still not  change

**Comment by sabrabano0** [comment]
i also have done this  step by step :
https://medium.com/@dalgibbard/docker-with-gpu-support-in-wsl2-ebbc94251cf5
but still same error

**Comment by stephen-turner** [comment]
It might be this Nvidia bug: NVIDIA/nvidia-docker#1409
