### ISSUE TITLE
Unresponsive UI and high CPU load with Docker Desktop 3.2.1

### ISSUE THREAD

**Issue by monosoul** [docker/for-win#10591]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `B367CC21-9E84-4A2D-870B-86BE9FB0E1B8/20210309083701`

### Actual behavior
Docker Desktop UI doesn't respond to mouse clicks and creates high CPU load.

### Expected behavior
Docker Desktop UI responds to mouse clicks and doesn't create high CPU load.

### Information

I got the issue for the first time when I've updated to Docker Desktop 3.2.1. A reboot didn't solve it, so I decided to reinstall docker. I uninstalled it completely and then installed again, but it didn't help.

I get unresponsive UI when I try to open the main window (having container list), or when I try to open the settings screen. The about screen works fine.

When I open the main window, it doesn't show any containers in the list even if there are some. Considering that and high CPU usage, my guess is: there's an endless loop somewhere there.

  - Windows Version: `19042.844`
  - Docker Desktop Version: `3.2.1 (61626)`
  - WSL2 or Hyper-V backend?  `WSL2`
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: `No`

### Steps to reproduce the behavior

  1. Install Docker Desktop version 3.2.0
  2. Update to version 3.2.1
  3. Get unresponsive UI

**Comment by stephen-turner** [comment]
@monosoul Maybe a silly question, but were you running without a network connection? The only bug we've seen like this is when the computer running Docker Desktop is disconnected.

**Comment by JanHildenbrandBosch** [comment]
> 
> 
> @monosoul Maybe a silly question, but were you running without a network connection? The only bug we've seen like this is when the computer running Docker Desktop is disconnected.

I'm having similar issues. I do have network connection, but behind a proxy & vpn. Could be something broken with the proxy integration/awareness? It seemed the container also couldn't connect over the proxy, which works perfectly fine with the same setup in version 3.1.0.

**Comment by monosoul** [comment]
@stephen-turner I was running with a network connection.

Although, like @JanHildenbrandBosch I do have a proxy/VPN software running as well (ZScaler to be more precise). Once I disabled it, the UI became responsive again.

Since we're at it, I actually have a question. ZScaler does SSL inspection by acting as a proxy for SSL connections, replacing actual endpoint SSL certificates with it's own one. For this to work properly, I have to manually add ZScalers CA certificate to Windows' keychain. The question is: does Docker Desktop for Windows uses the OS's keychain? Or does it have it's own keychain where I also need to add the certificate?

**Comment by rutixx** [comment]
Similar problem here:

Win 10 prof, 10.0.19041.867
WSL2
using Check Point VPN and and my companies proxy

I had to deinstall 3.2.1 and return to 2.5.0.1. 
If you I installing any previous 3.x.x you will be forced to update to 3.2.1. immediatly!
This is really bad.

Is there any better workaround for rolling back an update and keep this previous version?

**Comment by monosoul** [comment]
@rutixx I've rolled back to 3.1.0

For Docker Desktop to upgrade you have to allow it to elevate privileges with user access control. Just press "No" there and run Docker again, it won't ask for upgrade until the next run.
![image](https://user-images.githubusercontent.com/5037832/110768971-fd65b980-8257-11eb-83b0-fd1be4d37193.png)

**Comment by fire015** [comment]
@monosoul I have the same issue as you with ZScaler, once I disable internet security the UI is much more responsive!

**Comment by monosoul** [comment]
@fire015 unfortunately it's not up to me to disable it 😞

**Comment by rutixx** [comment]
> @fire015 unfortunately it's not up to me to disable it 😞 I can only sort of disable it by creating a firewall rule to block it, but that would also disable the private network for me.

Same for me. Unforunatly serveral things have been changed on my local machine during the last days. So it is difficult to find the real cause:
1. Perform Windows updates to become ready for wsl2
2. Windows update corrupted Trend Micro, it was not running without noticing this.
3. I switched to wsl2 and everything was fine, my machine was faster than ever before
4. On the same day, when the IT guys reactivated Trend Micro, Docker updated itself to 3.2.1 :-(
5. After that I encountered the problems described here

**Comment by JasonCubic** [comment]
same issue here.  Docker 3.2.1, unresponsive ui, win 10 1909, on corporate vpn that is often slow.

**Comment by mathysd** [comment]
I had the same issue. Updating to 3.2.2 (61853) seems to have resolved this issue for me.

**Comment by JanHildenbrandBosch** [comment]
Issue persisted for me in 3.2.2 but updating the proxy to `host.docker.internal` was ultimately the fix (https://github.com/docker/for-win/issues/10619). Not sure, whether it is a combination of the update or was always 'just' a proxy issue.

**Comment by monosoul** [comment]
I can confirm that updating to 3.2.2 has fixed the issue for me as well

**Comment by stephen-turner** [comment]
Ah yes, thanks. We fixed it in 3.2.2. We missed closing this ticket because the release notes link to #10563, which is the same issue.
