### ISSUE TITLE
make shell cursor blink

### ISSUE THREAD

**Issue by whyzdev** [docker/for-win#106]
### Expected behavior
Shell cursor should blink when moving by left/right arrow keys .

### Actual behavior
Cursor in docker container shell (e.g. ubuntu image) does not blink. So it's hard to see where the cursor is when moving with left/right arrow keys. However in Vim, for example, the cursor blinks.

### Information
Same as above in Windows 10 cmd.

### Steps to reproduce the behavior
cmd or powerhshell (but not e.g. mingw in git) 
docker run -it <image> /bin/bash
or,
docker exec -it <container> /bin/bash
enter some commands
press up key tosome  previous command, and then move cursor with left/right array.
vim some file, where the cursor indeed blinks.

**Comment by rneugeba** [comment]
My cursor is blinking in interactive mode when using powershell and cmd and the cursor keys work

Are you using ConEmu by any chance? See: https://github.com/docker/docker/issues/13817 and https://github.com/docker/docker/pull/25578

**Comment by whyzdev** [comment]
You are right. I realize that the cursor eventually shows up and blinks at somewhere in the command line. It is just slow, after left/right array keys are released. The problem happens when keeping press the arrow keys for moving the cursor. This is in cmd when docker run/exec containers with some images i tried. It's not ConEmu unlike the other two issues.

**Comment by rneugeba** [comment]
Thanks for getting back. Can this issue be closed?
Thanks

**Comment by whyzdev** [comment]
sure. let's close it. Thanks,
