### ISSUE TITLE
Docker host directory mount empty volume :(

### ISSUE THREAD

**Issue by edoko** [docker/for-win#1060]
### Expected behavior

docker run and open the my host directory, it has remote files...

### Actual behavior

docker run -v /c/users/koma/wordpress/www:/usr/share/nginx/www -p 8080:80 -p 2222:22 -p 9091:9091 --name wp-docker -d wluns32/blaaaaa:latest

But, my host directory is empty. no files...

### Information

  - E7C88219-D2F4-4AA4-9BAA-4A27326A3D97/2017-09-02_12-05-22
  

  - Client:
 Version:      17.07.0-ce
 API version:  1.31
 Go version:   go1.8.3
 Git commit:   8784753
 Built:        Tue Aug 29 17:41:05 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.07.0-ce
 API version:  1.31 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   8784753
 Built:        Tue Aug 29 17:46:50 2017
 OS/Arch:      linux/amd64
 Experimental: true

 - OS: Windows 10 PRO
 I use Hyper-V and shared C drive volume.

### Steps to reproduce the behavior

  1. Install stable or edge available from https://docs.docker.com/docker-for-windows/install/.
  2. Run As Administrator. Loads in Linux container mode by default

**Comment by edoko** [comment]
> [13:47:23.599][ApiProxy       ][Info   ] Rewrote mount /c/Users/koma/wordpress/mysql:/var/lib/mysql (volumeDriver=) to /c/Users/koma/wordpress/mysql:/var/lib/mysql
[13:47:23.600][ApiProxy       ][Info   ] Rewrote mount /c/Users/koma/wordpress/mysql:/var/run/sshd (volumeDriver=) to /c/Users/koma/wordpress/mysql:/var/run/sshd
[13:47:23.600][ApiProxy       ][Info   ] Rewrote mount /var/lib/docker/volumes/679f7dcbc190eb8e3ca564f5bf4ef87abcc88c498751f7966445e124ad676e72/_data:/usr/share/nginx/www (volumeDriver=) to /var/lib/docker/volumes/679f7dcbc190eb8e3ca564f5bf4ef87abcc88c498751f7966445e124ad676e72/_data:/usr/share/nginx/www
[13:47:23.619][ApiProxy       ][Info   ] Failed to read proxies/http from snaphshot p9p.MessageRerror{Ename:"No such file or directory"}

**Comment by edoko** [comment]
2nd: I try to uninstall all docker and images, and re-install docker beta.
but, it has same error.
It is empty direcotry.

E7C88219-D2F4-4AA4-9BAA-4A27326A3D97/2017-09-02_21-32-10

**Comment by edoko** [comment]
Docker Info :

> Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.07.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 3addd840653146c90a254301d6c3a663c7fd6429
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.41-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: moby
ID: V6JX:UFW4:PTWF:BDXB:D4UH:JOE6:XSRI:3F2Q:FUT7:3XDI:IDTR:VEGT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 26
 Goroutines: 37
 System Time: 2017-09-02T12:40:36.2650969Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by jmvbxx** [comment]
I believe I'm having the same issue:
docker-compose:
```
version: "3"
services:
    db:
        build: ./mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: <password>
         volumes:
            - data:/var/data_test
volumes:
    data:
```
I found an blog that suggested `./data` instead of `data` but still no luck.

`data` has a folder with several flies but `/var/data_test` is empty on the container.

**Comment by jmvbxx** [comment]
My issue was resolved by correcting the permissions
