### ISSUE TITLE
After Upgrade from Docker 3.2.0 / 3.1.0 to Latest (3.2.1) Java stops functioning inside container.

### ISSUE THREAD

**Issue by jfixemer** [docker/for-win#10604]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 03DA4F02-8C4F-49CA-B3B9-EA5C553B257A/20210310132655

### Actual behavior
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0xef2f0660, pid=1249, tid=0xaa15bb40
#
# JRE version: OpenJDK Runtime Environment (8.0_181-b13) (build 1.8.0_181-b13)
# Java VM: OpenJDK Server VM (25.181-b13 mixed mode linux-x86 )
# Problematic frame:
# J 89 C2 java.lang.String.hashCode()I (55 bytes) @ 0xef2f0660 [0xef2f0580+0xe0]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /data/cjf002/astro/build/snmp/common/icd/hs_err_pid1249.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
qemu: uncaught target signal 6 (Aborted) - core dumped
/bin/sh: line 1:  1249 Aborted                 java -jar /usr/share/java/saxon.jar -versionmsg:off ...
```
### Expected behavior
XLST is run and outputs transform successfully.

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible?  Yes -- 
 I had this problem after I upgraded to 3.2.1
 I uninstalled Docker Desktop, reinstalled with the 3.1.0 installer, everything worked. 
 It wanted to upgrade to 3.2.1, I allowed it and the issue came back.
This operation within containers for the SAME IMAGE also works fine on RHEL7 + Docker, RHEL8 + Podman, AWS EC2 + Docker

  - Is the problem new?  Yes It is new in 3.2.1  I did not observe it in 3.1.0 or 3.2.0
  - Did the problem appear with an update? Yes
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.
  I cannot provide a docker file as it is for RHEL7.  
  CentOS7, with java-1.8.0, saxon.jar

  - Windows Version: Windows 10 Pro
  - Docker Desktop Version: 3.2.1
  - WSL2 or Hyper-V backend?  WSL
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior
I'm sorry I don't have time to craft a trimmed down, non-proprietary example container.

  1. Run Java saxon based XSLT in Container on Docker Desktop 3.1  (works)
  2. Run Java saxon based XSLT in (same container after restart) Docker Desktop 3.2.1 (fails).
  3. Delete container, start new container from image on 3.2.1 -- fails

**Comment by StefanScherer** [comment]
Thanks @jfixemer for the report. 
Could you try the command described in this ticket https://github.com/docker/for-win/issues/10594#issuecomment-794359992 to disable 32bit emulation? This sounds related.

**Comment by Spidey01** [comment]
Seeing this on Docker Desktop for Windows 3.2.1 when using docker run to launch a build process that invokes java, along with my C/C++ compile performance drop to about 1/10th normal speed.

In my case however, I'm using i386/debian:stretch as a base image for a build environment used for building 32-bit software.

**Comment by jfixemer** [comment]
I and a peer have confirmed that running the command from #10594 'fixes' the issue.  (also had to restart containers, but kept all the volumes so that is not a big deal)

I will further confirm that we are running i686 (aka 32bit) Java because we do some JNI with legacy 32bit libraries.

Thanks for the quick response and useful workaround.
