### ISSUE TITLE
701C7151-8F4F-4E64-BFFA-CBA3D3876348/20210310031735

### ISSUE THREAD

**Issue by QYO4869** [docker/for-win#10602]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by oqy4869** [comment]
> * [ ]  I have tried with the latest version of Docker Desktop
> * [ ]  I have tried disabling enabled experimental features
> * [ ]  I have uploaded Diagnostics
> * Diagnostics ID:
> 
> ### Actual behavior
> ### Expected behavior
> ### Information
> * Windows Version:
> * Docker Desktop Version:
> * WSL2 or Hyper-V backend?
> * Are you running inside a virtualized Windows e.g. on a cloud server or a VM:
> 
> ### Steps to reproduce the behavior
> 1. ...
> 2. ...
