### ISSUE TITLE
Drive is unshareable

### ISSUE THREAD

**Issue by alarksharma** [docker/for-win#1061]
### Expected behavior
Docker should work

### Actual behavior
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: Drive is unshareable.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
An error occurred. Exiting...

### Information

Please find attached the Docker log file with also contains docker build and OS build information

[Dockerlog.txt](https://github.com/docker/for-win/files/1272144/Dockerlog.txt)

**Comment by jasonbivins** [comment]
Hi @alarksharma 
What drives do you have shared out currently?
![image](https://user-images.githubusercontent.com/28021664/30489330-f96dad54-9a04-11e7-9dfb-2370ec1f9126.png)

 I do see in the logs that it is trying to mount a couple of volumes, but failing 
```[17:20:24.068][ApiProxy       ][Info   ] Rewrote mount C:/src/symnxt/cloudops:/chef (volumeDriver=) to /C/src/symnxt/cloudops:/chef
[17:20:24.068][ApiProxy       ][Info   ] Rewrote mount C:/florence/DockerSetupScript/icsdev:/icsdev (volumeDriver=) to /C/florence/DockerSetupScript/icsdev:/icsdev
[17:20:24.068][ApiProxy       ][Info   ] Drive is unshareable```

**Comment by alarksharma** [comment]
I have shared C drive.
"C:/florence/DockerSetupScript/icsdev" is a folder in C drive.
