### ISSUE TITLE
Docker Desktop for Windows crashed during Windows startup

### ISSUE THREAD

**Issue by danielkang674** [docker/for-win#10618]
- [x ] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 75EC4944-41E8-45EB-A8A3-591AE267F151/20210311042730

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. Just suddenly happened when I booted up my computer from shut down.

**Comment by zcajiayin** [comment]
If you are a windows 10 pro user, jsut disable (uncheck) WSL 2 and docker desktop will use Hyper-v as backend. It will resolve this issue.

![image](https://user-images.githubusercontent.com/29399076/111270752-355f6900-866b-11eb-8620-d30ed95a99d8.png)
