### ISSUE TITLE
An error occured while running Docker 

### ISSUE THREAD

**Issue by ErnestGulbis** [docker/for-win#10625]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F43724D8-4EAB-45C3-AFB1-6B1492C7B62C/20210311144305
[diagnostics[1].log](https://github.com/docker/for-win/files/6123976/diagnostics.1.log)

### Actual behavior
An error occured while running Docker 

### Expected behavior
Docker Desktop is up-and-running
### Information

  - Windows Version: Windows 10 Pro (installed on VirtualBox machine)
  - Docker Desktop Version: 3.2.1 (61626)
  - WSL2 or Hyper-V backend? WSL2 installed 
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: virtualized Windows (VirtualBox)

### Steps to reproduce the behavior

  1. An error occured while running Docker (System.InvalidOperationException:)

**Comment by stephen-turner** [comment]
Thank you for the report. Unfortunately Docker Desktop is not supported in a virtualised environment (see https://docs.docker.com/docker-for-windows/install/#whats-included-in-the-installer and https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-desktop-in-nested-virtualization-scenarios). It's out of our control whether it works or not: it depends whether the outer hypervisor can fully run Hyper-V or WSL 2. Sometimes enabling nested virtualisation in the outer hypervisor makes it work, but there are no guarantees.
