### ISSUE TITLE
docker.exe is not compatible Windows 64-bit

### ISSUE THREAD

**Issue by duongphuhiep** [docker/for-win#1062]
### Expected behavior
"docker version" must to return the version

### Actual behavior
![image](https://user-images.githubusercontent.com/1638594/30004081-e918ceec-90c8-11e7-97c9-7a21973a7195.png)

### Information
Windows 10 Pro 64 bit (Dell XPS 8500)
![image](https://user-images.githubusercontent.com/1638594/30004085-02bcad3c-90c9-11e7-89e4-920bc5306c3c.png)

### Steps to reproduce the behavior
- install [Docker for windows stable](https://download.docker.com/win/stable/Docker%20for%20Windows%20Installer.exe)
- then run docker.exe

**Comment by friism** [comment]
![image](https://user-images.githubusercontent.com/126104/30122788-9ae31f34-92e4-11e7-8c79-453fe0d32f3d.png)

`docker.exe` is a 64bit binary, I checked using this method: https://superuser.com/a/889267/4581

Can you try to re-install? Maybe your install got corrupted

**Comment by duongphuhiep** [comment]
thanks
it works fine now after re-install - Version 17.06.2-ce-win27 (13194)
