### ISSUE TITLE
Issue in starting docker desktop in windows 10

### ISSUE THREAD

**Issue by minesh1988** [docker/for-win#10628]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by auscampbell** [comment]
I am having the exact issue. Any update?

**Comment by minesh1988** [comment]
after restart and few retry, it works now.  Also as part of diagnosis I had factory reset docker deamon, not sure if  retry fixed the issue or  factory reset
