### ISSUE TITLE
Whale system tray icon disappearing/not accessible in 3.2.0+

### ISSUE THREAD

**Issue by rfay** [docker/for-win#10627]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

I keep finding my test runners with inaccessible system tray icon. This means I can't manage docker desktop, see it's version, or any of those things. This seems to have started happening in 3.2.0 and is still in 3.2.1.

### Expected behavior

When docker desktop is running, the system tray icon should be accessible/visible.

Sometimes I can *run* docker desktop and get to the main window. BUT, the main window is missing many features. I want to

* Know what version it's running
* Be able to restart
* Do everything that's on the system tray menu

### Information

  - Windows Version Windows 10 Home/Pro:
  - Docker Desktop Version: 3.2.0/3.2.1
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

Unfortunately I don't know how to reproduce it, I'm just seeing it regularly.

**Comment by stephen-turner** [comment]
Thanks for the report, Randy. That's very odd, we haven't had any other reports of this. When you say "inaccessible" do you mean that the whale is absent, or that it's present but not clickable, or what?

**Comment by rfay** [comment]
It's not there. I don't know if it's invisible or what... but it's not there.

**Comment by rfay** [comment]
@stephen-turner I think I know what's happening here. When one of these auto-updates happens, or even if somebody says "go ahead and update", the icon disappears, sometimes for a long time. This can happen on both Windows and Mac. It eventually comes back and says "OK, give me root to install"

**Comment by stephen-turner** [comment]
Interesting. We haven't observed that, but as you know we're about to change that behaviour anyway. The update code has all been rewritten, so let's see if this bug persists after that.

**Comment by rfay** [comment]
I think this may be an artifact of screen-sharing software. It just happened to me, and when I went to the physical machine the icon was there. Closing for now, will reopen if I see it again.
