### ISSUE TITLE
"Error during connect" when running 'docker info' and 'docker ps' commands

### ISSUE THREAD

**Issue by epatter1** [docker/for-win#1063]
### Expected behavior

For "docker info"
"Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0 " ... ...

For "docker ps"
"CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS"

### Actual behavior
"error during connect: Get http://... ... The system cannot find the file specified. In the default configuration on Windows, the docker client must be run elevated to connect  (which it IS!). The error may also indicate the docker daemon is not running."

### Information

Tried this, but did not work:
https://success.docker.com/KBase/Docker_for_Windows_fails_with_a_daemon_not_running_message

Please advise!

### Steps to reproduce the behavior

  1. Open powershell as admin
  2. Type "docker info" or "docker ps"

**Comment by bp2012gs** [comment]
I was getting the same issue.  Not sure if this will work for you or not.  Double click to open icon from Desktop.  This will probably time out, but will put a little docker icon in the system tray down by the clock.  Right click on the icon and select "Switch to Windows container".  This should prompt you to restart.  Once restarting try running the commands again.  It worked for me, hope it helps you.

**Comment by jasonbivins** [comment]
Hi @epatter1 
Are you seeing this every time you try to use Docker?
