### ISSUE TITLE
Windows does not support host IP addresses in NAT settings, after update (3.1.0 -> 3.2.1)

### ISSUE THREAD

**Issue by mskorb** [docker/for-win#10638]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features

### Actual behavior
After upgrading Docker desktop from 3.1.0 to 3.2.1, all services cannot be stared, building docker-copose ended with result:
"Cannot start service (servicename): failed to create endpoint (endpointname) on network (networkname): Windows does not support host IP addresses in NAT settings" 

### Expected behavior
Docker-compose should build containers with services properly

### Information

  - Windows Version: 10
  - Docker Desktop Version: 3.2.1
  - WSL2 or Hyper-V backend?  WSL2

**Comment by stephen-turner** [comment]
Closing as dupe of #10552.
