### ISSUE TITLE
Docker 3.2.1 Install crash get credential unabled

### ISSUE THREAD

**Issue by falistra** [docker/for-win#10639]
System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\consulenteced\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Impossibile avviare il servizio. Il servizio è disabilitato oppure non è associato ad alcun dispositivo attivo.

  - [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
It appears that you haven't installed WSL 2 correctly, which Docker Desktop uses. Please follow Microsoft's instructions at https://aka.ms/wsl2-install. If it's set up correctly, then the command wsl -l -v should show a version 2 distro.
