### ISSUE TITLE
Issue when running dockerd.exe

### ISSUE THREAD

**Issue by IDKLOLSS** [docker/for-win#10644]
When I run dockerd.exe I get `time="2021-03-13T09:58:03.258831800-06:00" level=info msg="Starting up"
time="2021-03-13T09:58:03.259832200-06:00" level=warning msg="Running experimental build"
time="2021-03-13T09:58:03.260832700-06:00" level=debug msg="Listener created for HTTP on npipe (//./pipe/docker_engine)"failed to start daemon: a required service is not installed, ensure the Containers feature is installed: Access is denied.` How can I fix this?

Thanks

**Comment by AstralDestiny** [comment]
![image](https://user-images.githubusercontent.com/20157872/111058040-ba733400-8459-11eb-836d-42dc4ff864d6.png)

Do you have this enabled?

**Comment by IDKLOLSS** [comment]
> ![image](https://user-images.githubusercontent.com/20157872/111058040-ba733400-8459-11eb-836d-42dc4ff864d6.png)
> 
> Do you have this enabled?

I don't see it as an option

**Comment by AstralDestiny** [comment]
> > ![image](https://user-images.githubusercontent.com/20157872/111058040-ba733400-8459-11eb-836d-42dc4ff864d6.png)
> > Do you have this enabled?
> 
> I don't see it as an option

As you said you have Windows Home Edition... You could try to use WSL2 if you have that option.

**Comment by stephen-turner** [comment]
Why are you running dockerd.exe yourself anyway? You should let Docker Desktop set up everything for you.
