### ISSUE TITLE
Docker crashes on startup after new update 3.2.1

### ISSUE THREAD

**Issue by charlottelopez11** [docker/for-win#10641]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BE74FB55-E4DA-448C-B44D-D4877A756A83/20210312134616

### Actual behavior
1. Crashes on Startup
2. Failed to Restart

### Expected behavior
Docker to start on login successfully with Hyper-V.

### Information
This is a new problem that occured with an update to v3.2.1
  - Windows Version: 10 Enterprise
  - Docker Desktop Version: 3.2.1
  - WSL2 or Hyper-V backend?  Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: NO

### Steps to reproduce the behavior
  1. Power on Desktop
  2. Docker Desktop starts on login
  3. Docker Desktop stops
  4. Docker Hyper-V stops
  5. Right Click on Docker icon > Restart Docker
  6. Docker Error: Failed to restart

  - [x] I have tried uninstalling and reinstalling previous and latest version don't work anymore either
  - [x] I have tried factory resets
  - [x] I have tried restarting docker 
  - [x] I have tried disabling & enabling hyper-v 
![image](https://user-images.githubusercontent.com/58523839/110952796-9fe37280-8314-11eb-8543-44dc377e4790.png)

**Comment by traverjc** [comment]
Similar issue?? Upgraded installation "successful" but Docker never completely starts up (systray whale says "Docker is starting..."). Tried uninstalling/reinstalling latest. No error displayed. Can't get to Settings--just hangs.

**Comment by charlottelopez11** [comment]
Yes @traverjc, 

Docker on Windows automatically updates latest version on next login. The automatic update caused issues with my docker not running and continuously failing to run on login or restart.

**Steps:**

1. Uninstall Docker

2. Download & Install previous version you had on your machine
- downgraded from 3.2.1 -> 3.1.0
- https://docs.docker.com/docker-for-windows/release-notes/

3. Modify Settings as needed

4. Go to Docker Desktop Installer
- example: C:\Users\user\AppData\Local\Docker Desktop Installer
- Delete contents in that folder to disable auto update

**Comment by traverjc** [comment]
Thanks @charlottelopez11! Worked for me and I'm back in business

**Comment by adelara** [comment]
Mine is saying in a red banner: "Internal server error" so I'm taking this route and downgrading too. Thanks for the pointer.

**Comment by adelara** [comment]
Ok, reinstalling and deleting those files got me back in business again. I noticed that it wanted to upgrade so I had to keep an eye on that directory and delete the files several times.
Not the icon on the taskbar just has an exclamation mark saying it will upgrade but I keep watching that directory and it seems to have calmed down. Back in business, thank you charlottelopez11
