### ISSUE TITLE
Add multi-select option in Docker Desktop for Windows

### ISSUE THREAD

**Issue by RoyAtanu** [docker/for-win#10640]
**This is a Feature Request**

**What** : As an user, I should be able to multi select images/containers in Docker Desktop for Windows

**Why** : When we want to delete multiple images/containers all at once via Docker Desktop, we have to go to each of them and delete. Plus each delete operation also opens confirmation popup, which is one more extra click to do the job.

**Why UI is important when I have CLI** : We can surely cleanup all the images/containers via command line much faster. But UI is more convenient and faster (with a multi-select option) when you want to delete a large number of items selectively (Select All -> Uncheck the one you don't want to delete -> Delete the rest with one click)

**Comment by stephen-turner** [comment]
Thanks for the feedback. We have this on our backlog, but no target date at the moment.
