### ISSUE TITLE
Docker desktop does not start, nothing happens, I can't find any explicit log to the matter

### ISSUE THREAD

**Issue by Miminoux** [docker/for-win#10655]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F84AD095-E7CE-4D91-9DDB-B615B5092C4E/20210315113517

### Actual behavior
When I launch docker-desktop, nothing happens. I can see the white whale in the systray bar for 2 seconds then it disappears silently. No error message is displayed, nothing. 

### Expected behavior
Well, I expect Docker Desktop to launch or at least to tell me what is wrong. 

### Information
The case seems to be happening on many of my colleagues's computer too. 
For what I could investigate, I am surprised not to find any wsl distro registered like docker-desktop dans docker-desktop-data. Actually, I have been having this problem for quite long now, I was used to Docker for windows v2, then I upgraded then this happened, then I uninstalled everything, deleted every single directory with name "Docker" I could find (C:\users\me\.docker, in my AppData too roaming and local), wsl --unregister the 2 docker-desktop "distros" and re-installed the latest version of Docker Desktop I have been leaded to from google which surprisingly is 3.1 and not 3.2. I don't expect a major difference in 3.2 but I'll do the full install from it. 
From what I read, if the WSL distro do not exist, launching docker desktop should create them but it is not the case, I can't find the reason why. And I didn't find a command to create them anew to see if it helps. Cuz if it soesn't change a thing, it might not be the principal matter, I hope you see what I mean...

  - Windows Version: windows 10 - 2004
  - Docker Desktop Version: 3.1.0
  - WSL2 or Hyper-V backend?  I think it's WSL but since nothing happens, I'm not even sure
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no, on my laptop.

Something important related to my environment : I am forced to use "secure execution" with AppLocker GPO. Anyway, it should be correctly configured an let me execute everything under C:\Program files as long as I dont try to write there and only in my user directory. If appLocker would be the problem, I would expect some log saying something went wrong (Permission Denied is the most common mesasge in this case) but obvisouly I don't. Before you ask, I am not allowed to disable this security, I can only add execptions to directories, binaries, etc. but I don't see what could block Docker Desktop from executing and neiher did I find any log related to the matter. 

### Steps to reproduce the behavior
I'm not sure it is reproductible but whatever I can do, it doesn't work.

The good thing is I don't have any important data in the docker desktop on my laptop. I can ruin it all and start again.

**Comment by PrapatsaraNaksuth** [comment]
> ปัญหาจะเก่าลงหลังจากไม่มีการใช้งาน 90 วัน
> ทําเครื่องหมายปัญหาว่ามีความสดใหม่พร้อมความคิดเห็น
> ปัญหาเก่าจะถูกปิดหลังจากไม่มีการใช้งานเพิ่มเติม 30 วัน`/remove-lifecycle stale`
#11448 /PrapatsaraNaksuth/Docker Community Slack #docke
