### ISSUE TITLE
Docker consistently fails Windows 10 initialization

### ISSUE THREAD

**Issue by DanielAtKrypton** [docker/for-win#10651]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4D169ED3-E4E0-4F58-9264-3FA6F5B29655/20210314155422

### Actual behavior
At least once in every 3 Windows initialization, Docker fails to initialize.

### Expected behavior
Normal Docker Desktop initialization

### Information

  - Windows Version: Build 21332
  - Docker Desktop Version: 3.2.1
  - WSL2 or Hyper-V backend?  I have both enabled but the problem happens in Windows host machine
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Steps to reproduce the behavior

  1. Restart Windows
  2. Restarting manually Docker Desktop fixes red whale in System tray area.

- [ ]

**Comment by dgmdevelopment** [comment]
Having same issue in 3.2.1, only workaround has been to restart WSL, then Docker Desktop.  

In powershell, 

```wsl --shutdown```

```wsl``` 

Then restart Docker Desktop.   I tried downgrading to 3.2.0 but it says an update will automatically be applied when Docker restarts.

**Comment by GuillaumeRossolini** [comment]
I've had this issue at some point, not sure if because of software upgrades or because I kept changing my stack.
Anyway, uninstalling Docker Desktop, rebooting and reinstalling fixed the issue in my case.
Cheers

**Comment by DanielAtKrypton** [comment]
I have another crash report: 4D169ED3-E4E0-4F58-9264-3FA6F5B29655/20210316035842

**Comment by DanielAtKrypton** [comment]
Turning off Hyper-V auto start of one FreeBSD Virtual Machine of mine did the trick. I believe Docker devs have to look for working with Hyper-V virtual machines in tandem with Docker Desktop in order to solve this apparent bug.

**Comment by DanielAtKrypton** [comment]
Did the trick until today. There is yet another crash report: 4D169ED3-E4E0-4F58-9264-3FA6F5B29655/20210316151237. This time there was no virtual machine automatically started.

**Comment by DanielAtKrypton** [comment]
Yet another: 4D169ED3-E4E0-4F58-9264-3FA6F5B29655/20210320214204

**Comment by DanielAtKrypton** [comment]
Yet another today after Windows update: 4D169ED3-E4E0-4F58-9264-3FA6F5B29655/20210321051010
