### ISSUE TITLE
Failed to start Docker desktop

### ISSUE THREAD

**Issue by odlarhg** [docker/for-win#10658]
How can I fix the error I get when I start Docker Desktop?

Hi, I am new to Docker and have installed it because I need to run an application that is configured to work under a docker container.

I have installed Docker version 20.10.2 and have configured the application that I need to use. The application works fine when I install it, but every time I turn off my computer and then go back into windows, Docker Desktop shows an error window with the attached log. How can I correct this error?

System.ArgumentException:
Unable to create an instance of Docker.App: Unable to create an instance of Docker.ApiServices.Update.UpdateCheckTimer: Unable to create an instance of Docker.ApiServices.Update.Updater: Unable to create an instance of Docker.Notifications.BackgroundUpdateWatcher: Se produjo una excepción en el destino de la invocación.
   en Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) en C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:línea 89
   en Docker.Core.Di.Singletons.Get(Type type, Int32 depth) en C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:línea 51
   en Docker.Core.Di.Singletons.Get[T]() en C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:línea 28
   en Docker.Program.Run(IReadOnlyCollection`1 args) en C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Desktop\Program.cs:línea 340

  System.ArgumentException:
  Unable to create an instance of Docker.ApiServices.Update.UpdateCheckTimer: Unable to create an instance of Docker.ApiServices.Update.Updater: Unable to create an instance of Docker.Notifications.BackgroundUpdateWatcher: Se produjo una excepción en el destino de la invocación.
     en Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) en C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:línea 89
     en Docker.Core.Di.Singletons.Get(Type type, Int32 depth) en C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:línea 51
     en System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
     en System.Linq.Buffer`1..ctor(IEnumerable`1 source)
     en System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
     en Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) en C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:línea 83
  
     System.ArgumentException:
     Unable to create an instance of Docker.ApiServices.Update.Updater: Unable to create an instance of Docker.Notifications.BackgroundUpdateWatcher: Se produjo una excepción en el destino de la invocación.
        en Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) en C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:línea 89
        en Docker.Core.Di.Singletons.Get(Type type, Int32 depth) en C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:línea 51
        en System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
        en System.Linq.Buffer`1..ctor(IEnumerable`1 source)
        en System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
        en Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) en C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:línea 83
     
         System.ArgumentException:
         Unable to create an instance of Docker.Notifications.BackgroundUpdateWatcher: Se produjo una excepción en el destino de la invocación.
            en Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) en C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:línea 93
            en Docker.Core.Di.Singletons.Get(Type type, Int32 depth) en C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:línea 51
            en System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
            en System.Linq.Buffer`1..ctor(IEnumerable`1 source)
            en System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
            en Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) en C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:línea 83
         
              System.Reflection.TargetInvocationException:
              Se produjo una excepción en el destino de la invocación.
                 en System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
                 en System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
                 en Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) en C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:línea 83
              
                    System.Runtime.InteropServices.COMException:
                    No se pudo recuperar el generador de clases COM para el componente con CLSID {1ECCA34C-E88A-44E3-8D6A-8921BDE9E452} debido al siguiente error: 80070422 No se puede iniciar el servicio, porque está deshabilitado o porque no tiene dispositivos habilitados asociados a él. (Excepción de HRESULT: 0x80070422).
                       en Docker.Notifications.BackgroundUpdateWatcher..ctor(ISystrayNotifications systray) en C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Desktop\Notifications\BackgroundUpdateWatcher.cs:línea 12

If I log into PowerShell as an administrator and try to view the version of Docker, the following message is displayed.

error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect.: Get http: //%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version: open //. / pipe / docker_engine: The system cannot find the file specified.

And when I run Docker Desktopo I get this error.

**Comment by mat007** [comment]
From your logs it looks similar to #11273
