### ISSUE TITLE
Update requires administrator privileges

### ISSUE THREAD

**Issue by wabuMike** [docker/for-win#10666]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Running "update and restart" requires administrator privileges

### Expected behavior
The installation of minor or patch updates should be possible without having to provide administrator privileges.

### Information

Due to security considerations, the company I work for doesn't provide its employees with administrator privileges. That's why automatic update, which is integrated into Docker Desktop, is not possible.

  - Windows Version: 10 20H2
  - Docker Desktop Version: 3.2.1
  - WSL2 or Hyper-V backend?  WSL
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No. Running on metal desktop/laptop

### Steps to reproduce the behavior

Switch to a user without administrator privileges and click on Docker Desktop "update and restart".

**Comment by stephen-turner** [comment]
Sorry, it does require admin privileges because it is integrated into the OS at the systems level not just an application on top. There's nothing we can do about this.
