### ISSUE TITLE
Docker Desktop daemon fails to start on Windows 10

### ISSUE THREAD

**Issue by wpfeiffe-arbfile** [docker/for-win#10676]
- [**x** ] I have tried with the latest version of Docker Desktop
  - [**x** ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics - **I am unable to get docker to the point where I can upload diagnostics.**
  - Diagnostics ID:

### Actual behavior
**Docker fails to start up when Docker Desktop is run (or at start up if configured)**

### Expected behavior
**Docker starts up when Docker Desktop is run (or at start up if configured)**

### Information
  - Is it reproducible? **Yes**
  - Is the problem new? **Yes**
  - Did the problem appear with an update? **Yes**
  - Windows Version: **10 Enterprise, version 1803, OS build 17134.2087**
  - Docker Desktop Version: **3.0.4-3.2.2**
  - WSL2 or Hyper-V backend?  **Hyper-V**
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: **No**

> **It appears that the Docker Desktop is having trouble communicating with the Hyper-V VM.  But it does attempt to shut it down when it recognizes no http response coming back.  Not sure what to make of that**

Backed down to 2.5.0.1 and that also locked up on use.

### Steps to reproduce the behavior

  1. Install Docker Desktop on a comparably configured system
  
[service.txt](https://github.com/docker/for-win/files/6152214/service.txt)
[log.txt](https://github.com/docker/for-win/files/6152216/log.txt)
[install-log.txt](https://github.com/docker/for-win/files/6152219/install-log.txt)

**Comment by Techlearner71** [comment]
I'm just having all around issues with my PC  today. first of all I cant seem to sign in here lol. Just to get the ball rolling in the right direction
Secondly I am having problems starting dockerd and running it. The Daemon that is. Any suggestions?
