### ISSUE TITLE
The upgrade button shows up for paying organizations if you don't login again

### ISSUE THREAD

**Issue by fungiboletus** [docker/for-win#10686]
### Actual behaviour

![image](https://user-images.githubusercontent.com/45740/111446561-d3efd680-870c-11eb-95a2-e8e981400fcf.png)

I can see this button whenever I start docker windows, but my organization is actually a paying customer. If I logout and login again, the upgrade button disappear. 

### Expected behaviour

The upgrade button shouldn't be displayed for paying customers.

### Information

  - Windows Version: 20H2
  - Docker Desktop Version: 3.2.2
  - WSL2 or Hyper-V backend? : WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

**Comment by stephen-turner** [comment]
Can you clarify? Are you're seeing it before you're logged in, or are you already logged in when you see it?

**Comment by fungiboletus** [comment]
I'm already logged in when I see it.

**Comment by stephen-turner** [comment]
One more question, do you have 2FA enabled or not? I ask because they go through different code paths.

**Comment by fungiboletus** [comment]
No problem 🙂 Yes, I do have 2FA enabled.

**Comment by stephen-turner** [comment]
OK, thanks, in that case I think I know what the problem is. We have a ticket open for it internally, though I don't have a fix date for it yet.

**Comment by stephen-turner** [comment]
@fungiboletus I think this is now fixed, could you try again? (No need to download a new version of Desktop, the fix was on the Hub side).

**Comment by fungiboletus** [comment]
Hello, yes it is fixed for me. Thanks and have a nice day !

**Comment by stephen-turner** [comment]
Great, thanks for confirming.
