### ISSUE TITLE
Dashboard doesn't store sort order

### ISSUE THREAD

**Issue by ThePlenkov** [docker/for-win#10684]
Hi!

Docker desktop app doesn't store sort order for containers: 

![image](https://user-images.githubusercontent.com/6381507/111441298-7c9b3780-8707-11eb-8719-67cc8bd2176b.png)

It's enough just to switch between Containers and Images to see this.

Could you please add this small feature which currently takes so much time for manual sorting? Thank you!

Here is a similar issue for Mac which was close but it looks like still relevant:
https://github.com/docker/for-mac/issues/4249

**Comment by stephen-turner** [comment]
Yes, thanks. We have this on our internal backlog, but we should have a ticket here too. I've reopened the Mac one too.
