### ISSUE TITLE
Enable Kubernetes , its stack on starting 

### ISSUE THREAD

**Issue by shaibarlev** [docker/for-win#10687]
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: EA40ED5F-E603-4373-9BA6-DDE22561FA34/20210317071408

### Actual behavior
After enable Kubernetes , its stack on starting 
### Expected behavior
Finish the starting process
### Information

Please, help us understand the problem.  For instance:
  - Is it reproducible? Yes
  - Is the problem new? Yes , 
  - Did the problem appear with an update? yes , after upgrade to 3.2.1
  - Windows Version:
Edition	Windows 10 Pro Insider Preview
Version	Dev
Installed on	‎11/‎03/‎2021
OS build	21332.1010
Serial number	095812354753
Experience	Windows 10 Feature Experience Pack 321.5601.0.3
  - Docker Desktop Version: 3.2.1 and 3.2.2
  - WSL2 or Hyper-V backend?   WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior
  1. Just enable Kubernetes, and see it stack

**Comment by austonpramodh** [comment]
I tried the steps stated in the [comment](https://github.com/docker/for-win/issues/3799#issuecomment-566950792).

In addition to those, I deleted pki folder from `C:\Users\<username>\AppData\Local\Docker\pki` before starting the docker, and it worked.

Steps - 
1. Quit docker desktop
1. Delete C:\ProgramData\DockerDesktop
1. Delete  C:\Users\<username>\AppData\Local\Docker\pki
1. Start up docker desktop
1. Wait a few minutes before k8s light turns green
