### ISSUE TITLE
Insecure-registries configuration no more works after Docker Desktop 3.2.1 update

### ISSUE THREAD

**Issue by ivvater** [docker/for-win#10690]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
insecure-registries configuration added into daemon.json file and docker desktop reloaded. Worked fine before 3.2.1 update. After the update when trying to build the container got this errors:
=> ERROR [internal] load metadata for registry.mydomain.local:5000/tools/php:7.3-dev-unit1.22.0

failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to do request: Head https://registry.mydomain.local:5000/v2/tools/php/manifests/7.3-dev-unit1.22.0
: http: server gave HTTP response to HTTPS client
### Expected behavior
It worked perfectly fine before the update
### Information

  - Windows Version: 20H2
  - Docker Desktop Version: 3.2.2
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: NO

### Steps to reproduce the behavior

  1. add insecure registry configuration in the daemon.json file
  2. restart docker desktop
  3. try to build

**Comment by stephen-turner** [comment]
This might be to do with switching to buildkit as the default. Can you try switching back to the old builder using the instructions at https://docs.docker.com/docker-for-windows/release-notes/#docker-desktop-320?

**Comment by ivvater** [comment]
@stephen-turner thanks a lot!
It works again.
Maybe we can add this information to the release notes?

**Comment by stephen-turner** [comment]
Which information? I don't think we can list the exact symptoms, because that will be specific to each container/Dockerfile.
