### ISSUE TITLE
Docker Desktop WSL distro stopped after windows start up.

### ISSUE THREAD

**Issue by legoracer18** [docker/for-win#10700]
- [x ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 9A4236CC-224C-442F-8F31-04415C42EB7B/20210318134007

### Actual behavior

Says the Docker Desktop WSL distro stopped at windows start up.

### Expected behavior

It doesn't error out during windows start up.

### Information

  - Windows Version: Windows 10 Pro Version 20H2
  - Docker Desktop Version: 3.2.2 (61853)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Turn on Windows machine.
  2. After login, the error popup shows up.

**Comment by developerJJJ** [comment]
![wsl2](https://user-images.githubusercontent.com/43630709/111716890-4e9a2c80-889a-11eb-882b-099120fe4d13.PNG)
check this one

**Comment by legoracer18** [comment]
My settings match that image, still doesn't work.

**Comment by developerJJJ** [comment]
Did you try initialization?

**Comment by legoracer18** [comment]
What do you mean by initialization? I had this working for a couple days before this error showed up.

**Comment by legoracer18** [comment]
So looking at some more error logs and found that it's trying to go to `/mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-wsl-cli.iso` but it really should be going to `/mnt/c/Program Files/Docker/Docker/resources/wsl/docker-wsl-cli.iso`. The difference is the `/host/` folder. Not sure why it's trying to go to that location, or how to change it.
