### ISSUE TITLE
Unable to expose Docker API on 127.0.0.1:2375,[::1]:2375 on Windows 10

### ISSUE THREAD

**Issue by aPSopt** [docker/for-win#10701]
I launched and installed the Docker on the Windows 10. 
When I set up the chaeckbox "Expose daemon on tcp://localhost:2375 without TLS" and press the "Apply & Restart" button I received the followed message:
`
Unable to expose Docker API on 127.0.0.1:2375,[::1]:2375 on Windows 10. The port is already in use by another program.`

Ok, then I go to look who used the port and see that nobody uses this port.
I think this bug should be fixed ASAP.

**Comment by TylerJaacks** [comment]
I still have this issue any news on this issue?

**Comment by eliassal** [comment]
HI, I ahve the same issue, any response or solution you found?

**Comment by andreasvogt89** [comment]
Hello guys, i had the same issue with win10.  This sloved it for me #3546

**Comment by herbertboy** [comment]
> 
> 
> Hello guys, i had the same issue with win10. This sloved it for me #3546

Unluckily that didn't work for me, it seems that the 2375 is not in any reserved port range. I started having this issue after upgrading to the latest docker for win version 3.5.1

**Comment by martinfrankjr** [comment]
@herbertboy, same here. Docker install was a nightmare for me, now every update it seems there is an issue.

**Comment by yo0x** [comment]
Same here, i hope someone can throw some light here

**Comment by yeahan** [comment]
I have the same problem, and is not the case of #3546.
I checked the pid, find it was a process from `com.docker.proxy.exe` who has taken the port 2375. 
what does this exe file do? Can I just kill it?

**Comment by bwoods89** [comment]
I am also experiencing this issue and seeing that `com.docker.proxy` is taking the port

**Comment by herbertboy** [comment]
Just a quick update, I've updated to 3.5.2 version and the issue is still there. Let's see if they fix it. It's funny though that docker wants to use a port that is already using it lol

**Comment by Alkaidcc** [comment]
I have the same problem, It seems that `com.docker.proxy.exe` is taking the port

**Comment by liayn** [comment]
Still persists for me as well. Port is *not* reserved by windows. `com.docker.proxy.exe` is listening on that very port.
"Expose daemon ... without TLS" is *enabled*.

**Comment by CoderShiun** [comment]
I also got that error, but I think you can ignore it because after a while everything is up again.

**Comment by srNext** [comment]
Can confirm what others wrote here. Same issue, exact same error message.
I've updated my Docker Desktop to the latest version about ten days ago and ever since had this issue.

Checked the version with
`Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\* | select DisplayName,DisplayVersion | where {$_.DisplayName -like "Docker*"}`
and it currently states
DisplayName    DisplayVersion
Docker Desktop 3.5.1

Can also confirm that it's Docker itself that blocks the port with `com.docker.proxy`
For anybody who wants to check
`Get-Process -Id (Get-NetTCPConnection -LocalPort 2375).OwningProcess`

Saw that I have 3.5.2 available now so I will probably run that today but since others already wrote that it doesn't fix the issue I'm not expecting much from it.

**Comment by kohlerdominik** [comment]
Just confirming that the issue is also there in 3.5.2. It startet for me after the update to 3.5.2. The symptoms are the same.
```
Get-Process -Id (Get-NetTCPConnection -LocalPort 2375).OwningProcess

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    189      17    27284      24812       0.25   7028   1 com.docker.proxy
```

I'm actually using the open port actively and it works fine, so it's probably more of a display bug.

**Comment by MangoIceCup** [comment]
It sames just a dummy warning. As `com.docker.proxy.exe` really listen on ::1 2375. And I can telnet ::1 2375

**Comment by ronkpunk** [comment]
Same issue for me with Docker Desktop (installed months ago and updated till latest) + WSL 2 on Win10.
No luck with #3546 and with same issues described before (docker proxy listening on 2375 port).

I've finnally try to uninstall Docker Desktop, reboot Win and re-install Docker Desktop from fresh new installer and it seems works now.

I've tried also to reboot to check if somethings goes wrong with docker proxy and it seems has no problem now.

Maybe docker proxy wasn't uninstalled/updated during my last update so the newer version had problem to prepare the environment.

I hope this help someone

**Comment by lukos** [comment]
I managed to get into the Settings and disable "Expose Docker on port 2375 without TLS" and now the engine starts. Seems like a critical bug that has been present for 4 months, which isn't really great!

**Comment by Susan123456789** [comment]
Same issue.  Sometimes I can access the API and sometimes I can't (usually I can't).  I don't know why sometimes it works and sometimes it doesn't.  Very frustrating.  Any workaround would be appreciated.

**Comment by angelwancy** [comment]
Had the same issues after upgraded to the latest Docker for Desktop v20.10.7  

I didn't enable expose daemon to tcp://localhost:2375

Tried to reinstall the minikube then solved the issue :) Can also use kubectl get pods

Forgot the fundamentals that on WSL2 we have to install minikube or chocolatey first

**Comment by doublenb** [comment]
Same problem. Docker 3.5.2, `com.docker.proxy.exe` is already using the port when the "Expose daemon on tcp://localhost:2375 without TLS" setting is enabled.

**Comment by twenty-zhang** [comment]
Same problem. But I can still use it normally. What is the effect of this error?
docker desktop: 3.5.2(66501)
Engine version: 20.10.7

**Comment by mendhak** [comment]
I tried following [this comment](https://github.com/docker/for-win/issues/10701#issuecomment-880474097) - uninstall, reboot, reinstall.  Sadly I get the same problem.  Docker complains about 2375 but is able to work anyway.  

I do need the expose 2375 checkbox, so disabling it isn't an option for me. 

Please can someone from Docker have a look and address this issue please, it seems to be causing a lot of confusion.

**Comment by lamihax** [comment]
+1

**Comment by ryserCar** [comment]
Same issue but with Hyper-V, not using wsl at all

**Comment by Rouche** [comment]
Same Issue, disabled Hyper-V, no go. Using WSL 2. Expose without TLS. no go.

**Comment by srNext** [comment]
Meanwhile I've updated my Docker Desktop installation to 3.5.2 and as already expected that changed nothing.
Found no clear explanation nor workaround for this. The message just annoys me every day.

I think many people already confirmed the issue by now so it would be great if somebody from Docker could actually confirm it, show some official awareness about the problem and tell us if it is being worked on.

**Comment by doublenb** [comment]
In a dupe of this issue - #11517 - it seems a workaround is downgrading to 3.4.0 

See this comment - https://github.com/docker/for-win/issues/11517#issuecomment-871930780

Obviously not the right way to fix this, but should help until Docker fixes this issue.

**Comment by zachsa** [comment]
You can download older versions of Docker Desktop here: https://docs.docker.com/docker-for-windows/release-notes/

**Comment by mendhak** [comment]
If someone has Docker Pro/Team, maybe they could fill out a [support request](https://hub.docker.com/support/desktop/)? 

According to the [readme](https://github.com/docker/for-win#support) this repo is looked at on a 'best effort' basis.

**Comment by morcoGreen** [comment]
I had the same problem right after update.
Uninstalled - downloaded new installer from docker site and installed with it - issue was fixed

**Comment by mashhadi-afiniti** [comment]
I had the same problem right after the update.
Re-installed docker - **Still the same issue exists**

it's really alarming that so many months have passed and no one has resolved this issue!

**Comment by Nymph2333** [comment]
Same problem in Windows Server 2019

**Comment by herbertboy** [comment]
it seems that 3.6.0  version fixes this issue. I've updated yesterday and so far no more warning on that port.

**Comment by mashhadi-afiniti** [comment]
> it seems that 3.6.0 version fixes this issue. I've updated yesterday and so far no more warning on that port.

Hearing this I downloaded 3.6.0 excitedly but ironically the installer failed and it uninstalled my already running docker as well while updating.
I then went to the website and downloaded the latest version 4.* and that one failed to install too. 

I went back to version 3.5 and installed that, so back to the same problem with 2 hours of my life wasted that I will never get back.

**Comment by navossoc** [comment]
I can confirm it works on 3.4.0, 3.6.0 and 4.0.0.

**Comment by mashhadi-afiniti** [comment]
- Uninstalled Docker, removed all registries related to Docker (you can use 3rd party apps like CCleaner etc) 
- Restarted the system 
- Downloaded and installed 3.5 version. 

Seems to be working fine for now.

**Comment by efuncarlos** [comment]
i user 3.6.0 still won't work

**Comment by mashhadi-afiniti** [comment]
> i used 3.6.0 still won't work

- Uninstall docker hub 
- Restart your system 
- Go to :  [Docker Older Releases](https://docs.docker.com/desktop/windows/release-notes/#docker-desktop-352) and download Docker 3.5.2 (66501)
- Install it.

I tried this on 2 of my systems and it worked.

**Comment by hamidrezaabroshan** [comment]
I have this issue too.

**Comment by mathmul** [comment]
Running Docker Desktop 4.4.4 (73704) and I have the same issue in Feb 2022.

Everything worked well yesterday and no update in between. All I did was restart my computer.

**Comment by mathmul** [comment]
This worked for me:
- Uninstall Docker Desktop
- Use CCleaner to cleanup Registry
- Restart PC
- Download & Install Docker Desktop
- Restart PC
- In Docker go to settings and check the expose daemon option (already having DOCKER_HOST="tcp://127.0.0.1:2375" in SysVars)
- Save & Restart Docker

Those restarts probably weren't necessary, but it worked. For now...
