### ISSUE TITLE
Internet Explorer is deprecated for GitHub so please don't embed it

### ISSUE THREAD

**Issue by heaths** [docker/for-win#1070]
### Expected behavior

When update for Docker for Windows appears, clicking on a link for the changelog should open in a new window using the default browser.

### Actual behavior

Changelog opens in an embedded window using the Internet Explorer web view, which:
1. Is not (or will not) be supported by GitHub.
2. Doesn't scale and means we have to scroll around just to read a single sentence.

![screenshot](https://user-images.githubusercontent.com/1532486/30123515-22426ed8-92e7-11e7-8da8-ac493f03477d.png)

### Information

From latest install:
* Version 17.06.2-ce-win27 (13194)
* Channel: stable
* 428bd6c

There is no associated diagnostics ID (not a daemon or client issue).

### Steps to reproduce the behavior

  1. Get notified of update available.
  2. Click on a link to see the changelog of programs listed (this time it was Docker CE and Docker Machine).

**Comment by AustinWise** [comment]
This also has the effect that if you click on any link in the release notes, you can't go back to finish reading them.

**Comment by heaths** [comment]
/lifecycle frozen

Just change the release notes to a link and ShellExecute it. Simple and fixes the problem.

**Comment by gtardif** [comment]
This has been fixed in 17.12.0 release

**Comment by heaths** [comment]
Thanks for updating the issue.
