### ISSUE TITLE
Problem about tab Stellar-dummy when running Node of Pi Network

### ISSUE THREAD

**Issue by valiant67** [docker/for-win#10717]
When I click tab Stellar-dummy, it have code error http 500...

  - [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B85EB15A-DB71-429C-885B-8E2B60118659/20210320010501 

### Information

  - Windows Version: Windows 10.0.19041(Microsoft Windows Pro N for Workstations)
  - Docker Desktop Version: 3.2.2
  - WSL2 or Hyper-V backend?  WSL2 and Hyper-V normal running
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: inside a virtualized Windows
![Screenshot (18)](https://user-images.githubusercontent.com/80993882/111857537-c765bb00-8964-11eb-9911-753737040941.png)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by valiant67** [comment]
I don't know tab Stellar-dummy do not running when I open Node is normal or not? I see blockchain and incoming and outgoing connection is still good?

**Comment by stephen-turner** [comment]
The message says that you have something else already using the same port.

I don't think your problem is a Docker Desktop problem, you should probably contact the Pi Network.

**Comment by valiant67** [comment]
Thank you for your support! May be Node used same port with Stellar-dummy.

Vào 20:43, T.2, 22 Th3, 2021 Stephen Turner ***@***.***> đã
viết:
