### ISSUE TITLE
Docker does not restart automatically after update anymore

### ISSUE THREAD

**Issue by heaths** [docker/for-win#1071]
### Expected behavior

After updating, Docker for Windows starts automatically like it used to.

### Actual behavior

After updating, Docker for Windows no longer automatically starts and you have to remember to do it or, of course, running containers will not be restarted (if so configured).

### Information

 From latest install:

* Version 17.06.2-ce-win27 (13194)
* Channel: stable
* 428bd6c

There is no associated diagnostics ID (not a daemon or client issue).

### Steps to reproduce the behavior

  1. Get notified of update for Docker for Windows
  2. Install the update
  3. Run a `docker` command; get error that daemon not running
  4. Start Docker for Windows manually

**Comment by friism** [comment]
cc @ebriney - I think this is because of some security-related updates, no?

**Comment by ebriney** [comment]
Yes, because if we launch the GUI from the installer, it runs with admin rights

**Comment by friism** [comment]
Thanks - @mstanleyjones we should try to document this.

Closing this issue.

**Comment by mstanleyjones** [comment]
@gbarr01 can you please file and assign yourself this issue in the docs repo, and add a link to this issue in that one? We need to clarify that you need start the Docker daemon manually on Windows now.

**Comment by heaths** [comment]
There is a simple workaround for this that we do for the Visual Studio Installer to launch VS from an elevated window: run it via explorer (an oft-used workaround, actually):
```
explorer.exe "%ProgramFiles%\Docker\Docker\Docker for Windows.exe"
```

**Comment by friism** [comment]
thanks @heaths - would that work for us @ebriney ?

**Comment by heaths** [comment]
Just tried it using an elevated command prompt to start `Docker for Windows.exe` and verify with an elevated Process Explorer it indeed was given access to full privileges (elevated). When started with (and I had the command line above wrong) `%WINDIR%\explorer.exe "%ProgramFiles%\Docker\Docker\Docker for Windows.exe"` it had only its normal privileges as compared to when run via the *Start* menu.

The only caveat is that its parented to that `explorer` process, as opposed to the one that owns any other process started from _Start_ or the _Startup_ folder. Seems like a small price to pay.

**Comment by ebriney** [comment]
Thanks @heaths,  I will try that.

**Comment by heaths** [comment]
Is it worth reopening this issue while you repro what I did?

**Comment by heaths** [comment]
Where can I find the installer on GitHub? I've looked around at a few possible repos to no avail. I'm happy to add this capability myself. We use the same technique in the Visual Studio Installer and have heard no complaints that it doesn't work. It's actually a common practice to route through explorer.exe.

**Comment by friism** [comment]
@heaths thanks for offering your help - unfortunately, the installer is not on GitHub

**Comment by heaths** [comment]
Any particular reason you ditched MSI? I was a long-time developer on the WiX toolset (mostly back when it was an internally-managed OSS project) and would be happy to contribute open and easy authoring if you're interested. It takes care of service issues (since the recent  upgrade doesn't seem to be upgrading people very well), file contention issues (files in use), etc.
