### ISSUE TITLE
docker 3.2.2 pod kube-controller-manager-docker-desktop goes to CrashLoopBackOff

### ISSUE THREAD

**Issue by hvojdani** [docker/for-win#10718]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BA2AB641-B364-41E8-8888-21B51F996D2D/20210320052718

### Actual behavior
after updating docker desktop, docker runs ok but  kubernetes setting page stuck at starting.
pod kube-controller-manager-docker-desktop goes to CrashLoopBackOff
with exit code 255 with many restarts

tired resetting kubernetes cluster but no success,

port 10257 was blocked by firewall 
also disabled firewall to allow all ports to be access able  and again got CrashLoopBackOff.
I think something is wrong with readiness probe or liveness probe of pod
Liveness probe failed: Get "https://127.0.0.1:10257/healthz": dial tcp 127.0.0.1:10257: connect: connection refused
logs of pod:
`
W0320 05:54:50.101986       1 controllermanager.go:628] fetch api resource lists failed, use legacy client builder: Get "https://192.168.65.4:6443/api/v1?timeout=32s": x509: certificate is valid for 10.96.0.1, 0.0.0.0, 192.168.65.3, 127.0.0.1, not 192.168.65.4
F0320 05:55:00.118384       1 controllermanager.go:244] error building controller context: failed to wait for apiserver being healthy: timed out waiting for the condition: failed to get apiserver /healthz status: Get "https://192.168.65.4:6443/healthz?timeout=32s": x509: certificate is valid for 10.96.0.1, 0.0.0.0, 192.168.65.3, 127.0.0.1, not 192.168.65.4
goroutine 1 [running]:`

### Expected behavior
pod behaves normally and kubernetes state changed to running.
### Information

  - Windows Version: 20h2 19042.867 
  - Docker Desktop Version: 3.2.2
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior
I had 3.0.4 and a working cluster
updated to 3.2.2 then after update kubernetes stock on starting

**Comment by sev-g** [comment]
I had the same exact issue just now and apparently it was fixed by resetting docker to factory settings and enabling the Kubernetes cluster again.

**Comment by hvojdani** [comment]
no success, still have crashLoopBack

**Comment by ijaouani** [comment]
Having exactly the same issue. The workaround from @sev-g works for me but the root issue still need to be adressed.

Seems to be related to #10674 and #10571

**Comment by hvojdani** [comment]
deleting pki folder and restarting docker worked for me [https://github.com/docker/for-win/issues/10674#issuecomment-801176458](url)
