### ISSUE TITLE
Can't delete container (and therefore images) associated with removed WSL instance

### ISSUE THREAD

**Issue by cesarvarela** [docker/for-win#10730]
So I hade a couple of WSL instances that I just deleted, and now I want to clean up the docker images list but I'm getting the following error:
![image](https://user-images.githubusercontent.com/1172479/111938023-d86b1500-8aa7-11eb-9990-2c94e5ac7e92.png)

The Ubunutu WSL is no more on my system. But I still should be able to remove the container and its images.

**Comment by StefanScherer** [comment]
@cesarvarela Well, to shut down the compose containers from the dashboard it calls `docker-compose down` to cleanup everything it needs the `docker-compose.yml`, but that file is also gone with the Ubuntu distro. 🤔  
The only thing that you can do with the dashboard is to open the "server" compose app with the small triangle symbol, then you can see all containers. These containers can be removed from the dashboard and finally the "server" app will also disappear.
