### ISSUE TITLE
Dependency on WSL2 in Hyper-V mode: 10 minute startup failures.

### ISSUE THREAD

**Issue by dougheitkamp** [docker/for-win#10734]
- [ X] I have tried with the latest version of Docker Desktop
  - [ X] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Docker in Hyper-V mode uses WSL2 if WSL2 was ever installed.  If WSL2 was removed, as a feature, Docker will continue to attempt to use WSL2, even in Hyper-V mode.

### Expected behavior
Docker in Hyper-V mode should not use WSL2 when WSL2 is no longer installed.

### Information
  - Windows Version: Windows 10 Enterprise v1909
  - Docker Desktop Version: 3.2.2
  - WSL2 or Hyper-V backend?  Was WSL2, now Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

I assume that this is reproduceable.  I've spent too much time on this issue (and I'm finally stable), so I didn't attempt to recreate the entire flow.

### Steps to reproduce the behavior

  1. Run for years in Hyper-V mode, happily.  Upgrading along the way.
  2. Install WSL2 (to improve the Docker or not).
  3. I'm uncertain on the timing of what happened to trigger the conditions.  These three all happened at roughly the same time:
  3.a. Docker Upgraded itself.
  3.b. Installed all of the components for WSL2 that Docker wanted
  3.c. I attempted to Run docker in WSL2 mode.
  4. At this point Docker wouldn't start.  After 10 minutes (which corresponds to the 600 seconds in my settings file), the startup finally fails.  The experience during this period was horrible, by the way.  I couldn't access the settings page to change mode.
  5. After attempting many solutions online to attempt to fix the slow/no startup, I found in my computer security logs that our IT department was blocking WSL2 from performing some actions.  Specifically, my McAfee log had this entry: MYDOMAIN\ME ran C:\Windows\System32\wsl.exe, which attempted to access the process LxssManagerProxyStub.dll, violating the rule "Executing Windows Subsystem for Linux", and was blocked. For information about how to respond to this event, see KB85494.
  6. The fix seemed simple enough... don't run in WSL2 mode.  (Renewed emphasis on poor experience on not being able to access settings for 10 minutes.)  Went to the settings file and turned off everything that looked like it was WSL2.  Restart Docker.
  7. Docker SAYS it's in Hyper-V mode, but Docker Desktop still doesn't start up (10 minute failure, still).  
  8. Uninstall docker desktop, removed everything in the file system I could find that was related to Docker and Docker Desktop, disabled WSL2 as a feature.  Removed the Docker container in Hyper-V manager.
  9. At this point, I think I'm clean.
  10. Reinstall Docker Desktop for Windows (version 3.0.2, which promptly upgraded itself to 3.2.2).
  11. Unchecked all boxes related to WSL2.
  12. Docker STILL does not start up.
  13. Investigated the Docker logs.  IT IS ATTEMPTING TO USE WSL2 LIBRARIES AND EXE!  I wish I kept the log files, but I didn't, because that would have been handy now.  (In other news, I'm getting WAY behind on what I should be getting done.)  I don't know what I missed that Docker thought it could use WSL2.  A registry setting maybe?
  14. Uninstalled Docker.
  15. Restarted Windows again (I'm probably over 20 restarts in this "adventure".)
  16. Went to https://docs.docker.com/docker-for-windows/release-notes/
  17. Did a browser find for WSL2.
  18. Found the newest release that DIDN'T mention it.
  19. Installed Docker 2.1.0.5.  (the newest that didn't mention WSL2)
  20. I'm running
  21. I disabled upgrades (until my patience returns and/or our IT support department gets back to me on WSL2 and McAfee).
 
Hopefully this helps someone else get over startup issues, but I really feel that Docker Desktop has a bug at step 13.  I should be able to have WSL2 on my machine and run Docker Desktop in Hyper-V mode without a dependency on WSL2, and I should be able to run Docker 3.2.2 (not 2.1.0.5) after previously using WSL2, but no longer wishing to (either by choice or by force - McAfee).

**Comment by stephen-turner** [comment]
Thanks for the report. There is certainly no intent to use WSL 2 when it's in Hyper-V mode. You should be able to switch back and forth freely.
