### ISSUE TITLE
Docker for Windows fails to start with System.InvalidOperationException

### ISSUE THREAD

**Issue by alesana-san** [docker/for-win#10732]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 10826697-C84B-496C-A81A-5CAAC50370B4/20210322083507

### Actual behavior

Docker for Windows fails to start with the following message:
````
System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\Roman.Shiryaev\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: 5 
````
![image](https://user-images.githubusercontent.com/35428099/111968418-2dd80e00-8b0a-11eb-98b0-ec67428f8d17.png)

### Expected behavior

Docker for Windows starts up successfully

### Information

  - Windows Version: Windows 10 20H2 (Build 19042.867)
  - Docker Desktop Version: 3.2.2 (61853)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Install Docker for Windows
  2. Install WSL 2 Package
  3. Restart Docker for Windows

**Comment by alesana-san** [comment]
I guess this happens because of some antivirus software as the machine is corporate but I can't see the exact reason why it fails.

**Comment by alesana-san** [comment]
I found #6640 but I see nothing that uses 53 port

**Comment by stephen-turner** [comment]
This error generally means that you haven't installed WSL 2 correctly, which Docker Desktop uses. Please follow Microsoft's instructions at https://aka.ms/wsl2-install. If it's set up correctly, then the command wsl -l -v should show a version 2 distro.

**Comment by alesana-san** [comment]
Thanks for the explanation! I hadn't installed OS and that's why I got erros. After installing OS (Ubuntu, in my case) Docker for Windows started sucessfully.
