### ISSUE TITLE
Failed to deploy distro docker-desktop to AppData\Local\Docker\wsl\distro: exit code: -1  stdout: The system cannot find the path specified.

### ISSUE THREAD

**Issue by srinuSG** [docker/for-win#10739]
- [yes ] I have tried with the latest version of Docker Desktop
  - [yes ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:  8BE4A522-F40F-4AFE-A155-FD180575AF96/20210323112940

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
It appears that you haven't installed WSL 2 correctly, which Docker Desktop uses. Please follow Microsoft's instructions at https://aka.ms/wsl2-install. If it's set up correctly, then the command wsl -l -v should show a version 2 distro.
