### ISSUE TITLE
Fresh install - Docker Failed to Start

### ISSUE THREAD

**Issue by mmeier** [docker/for-win#1073]
### Expected behavior
Docker to Start

### Actual behavior
Error message "Unable to stop: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.
at <ScriptBlock>, <No file>: line 79"

### Information

  - Diagnostic ID: 92D7F0AA-51E1-40E4-9540-899335FA5E4D/2017-09-06_20-03-03

New install of Windows 10.
Installed docker with the installer, and got the error message when I tried to start it.
Clicked on the "Reset to factory defaults" and tried again.
Uninstalled and reinstalled Docker.
Same results.

### Steps to reproduce the behavior

  1. Install docker using the Docker for Windows Installer
  2. Install with defaults
  3. Double click on the Docker for Windows icon that appears on the desktop
  4. Error Windows appears

**Comment by jasonbivins** [comment]
Hi @mmeier 
There are a few Windows components in the pre-reqs that sometimes need to run first to complete configuration. You can install them manually to make sure everything is good - and then we can proceed with Docker from there.

Warning - You will lose any docker containers or images. As always, please run a full backup before making any changes.
These steps can be done through the Windows control panel, or using the below Powershell commands with elevated privileges.
• Uninstall Docker, Hyper-V, and if installed - the Windows containers feature. Then reboot.
• Enable Hyper-V
     • Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All
• Reboot, then enable the containers feature.
     • Enable-WindowsOptionalFeature -Online -FeatureName Containers -All
• Install Docker

**Comment by metya** [comment]
ok. i did it and it's works. 
thanks.

**Comment by sinlov** [comment]
I did it, but not work!
[more info see](https://github.com/docker/for-win/issues/1066#issuecomment-328160269)

**Comment by sinlov** [comment]
Finally fix by re-install full `Windows 10 pro`
because

- OS from `Window 10 Home update to Pro`
- Hyper-V can not use

Must re-install full package Windows to fix this

**Comment by jasonbivins** [comment]
Hi @sinlov 
Windows 10 Home doesn't support Hyper-V, so Docker will not run on it. 

Thanks!
