### ISSUE TITLE
Docker Windows and WSL2 timeout

### ISSUE THREAD

**Issue by MartinDahlKilt** [docker/for-win#10745]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BB720F90-0635-4D42-BF8D-3882D5E55F51/20210324095656

### Actual behavior
After a while docker becomes unresponsive and will eventually timeout.
It is not possible to start new containers.

In WSL2 it writes the following error message after a long wait:
<code> docker: Error response from daemon: Ports are not available: unable to list exposed ports: Get "http://unix/forwards/list": context deadline exceeded (Client.Timeout exceeded while awaiting headers).</code>

In Windows I get the following message:
<code> Error response from daemon: i/o timeout </code>

### Expected behavior
Docker should continue to work, and it should be possible to start new containers.

### Information
Seems to happen more or less random - but it always happens after aprox 1 hour.
It is not possible to use the "Restart Docker..." option, as the restart fails.
The problem seems to go away (for a while) if I manually quit and restart Docker.

I recently updated Docker from 3.0.x to 3.2.x 
I recently also updated Windows to the 20H2 release.
I'm not sure at which point the problem started. 

  - Windows Version: Microsoft Windows [Version 10.0.19042.867] (20H2)
  - Docker Desktop Version: 3.2.2 (61853)
  - WSL2 or Hyper-V backend: WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior
I have no clear method of reproducing this issue, it seems to just happen after a while.
Although it seems to happen more frequently when I'm connected to a VPN - could also just be that I normally connect to a VPN when I'm doing some serious work :)

**Comment by jarvis-99** [comment]
I am facing the same issue.  Its happening randomely and I have tried to access docker from both WSL2 and Powershell.

I am using WSL2 as the backend.  Windows 10 20H2 (OS Build: 19042.806) and Docker Desktop Version: 3.2.2.
