### ISSUE TITLE
Error System.InvalidOperationException:

### ISSUE THREAD

**Issue by TheCrackers** [docker/for-win#10743]
Windows version 2004 PRO
Docker version : Latest
I dont know why,i just installed docker and i cant run the docker command in cmd or powershell,the diagnostic id is CD5B6BCC-3D4A-4720-B1F2-B309432AE2A0/20210324091320

**Comment by TheCrackers** [comment]
Oh and here is the log file 
[log.txt](https://github.com/docker/for-win/files/6195774/log.txt)

**Comment by stephen-turner** [comment]
It appears that you haven't installed WSL 2 correctly, which Docker Desktop uses. Please follow Microsoft's instructions at https://aka.ms/wsl2-install. If it's set up correctly, then the command wsl -l -v should show a version 2 distro.
