### ISSUE TITLE
Docker error (windows 10)

### ISSUE THREAD

**Issue by sevak-crypto** [docker/for-win#10752]
C:\WINDOWS\system32>docker run -d -p 80:80 docker/getting-started
docker: error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect.: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/create: open //./pipe/docker_engine: The system cannot find the file specified.
See 'docker run --help'.

**Comment by excitedbox** [comment]
it would be so easy for an error message to tell you what to do but instead it says to run a help command which is not helpful one bit.

**Comment by maxxiaobao** [comment]
@sevak-crypto hi, did you resolve this isssue. I got this error as well :(

**Comment by sevak-crypto** [comment]
Hi, no sadly not
