### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by anasvikh** [docker/for-win#10777]
- [x] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: F6A0C112-30E0-41BA-B2D6-D9E6EE103F4A/20210329151200

### Actual behavior

error when running docker engine:
System.InvalidOperationException:
Failed to deploy distro docker-desktop-data to C:\Users\avikhlyaeva\AppData\Local\Docker\wsl\data: exit code: -1
 stdout: @5<O 

### Expected behavior

started docker

**Comment by stephen-turner** [comment]
It appears that you haven't installed WSL 2 correctly, which Docker Desktop uses. Please follow Microsoft's instructions at https://aka.ms/wsl2-install. If it's set up correctly, then the command wsl -l -v should show a version 2 distro.
