### ISSUE TITLE
Docker on WIN 10 Pro - crashes on start

### ISSUE THREAD

**Issue by gwd999** [docker/for-win#10780]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:  E9D7EA0B-C5B5-4DDD-8C1C-0F0F88795E5E/20210330094808

### Actual behavior
Install DOCKER Desktop 
Restart Computer 
Docker is configured to start on Windows startup
Docker informs: "An error occurred" (ie does NOT start, attempt to start "manually" -> same error) 

### Expected behavior
Install DOCKER Desktop 
Restart Computer 
No error occurs when Docker starts

### Information

  - Windows Version: WINDOWS 10 Pro  Version 10.0.19042 Build 19042
  - Docker Desktop Version: 3.2.2 (61853)
  - WSL2 or Hyper-V backend?  WSL2 
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Install Docker Desktop (for Windows) 
  2. Restart Computer 
  3. After starting Windows - Docker starts with OS -> Error 
  4. Same error also appears when started from START menu

**Comment by alexpas10** [comment]
Same issue for me. 
Docker Desktop crashed on start.
Reinstalling didn't help.
Diagnostics ID:     9B3C6E64-57C7-4B22-9473-A56C87FF277B/20210402194158

%LocalAppData%\Docker\log.txt:
[log.txt](https://github.com/docker/for-win/files/6251083/log.txt)
