### ISSUE TITLE
No longer able to map local folders

### ISSUE THREAD

**Issue by lostllama** [docker/for-win#1078]
### Expected behavior

Local folder maps

### Actual behavior

Local folder doesn't map. Instead, a persistent folder maps.

For example, if I launch docker with the following command:

`docker run -it -v c:/users/john:/mnt/john ubuntu:16.04`

and then, within the container, run `ls`, it will show that the directory is empty, despite it being my user directory on Windows. Now, if I type `touch test` to create a file called test, and then terminate the container, and re-run the docker run command above and run `ls` again, test will still exist in the folder. I can see it's persistent between runs, but it is not a folder I have access to within the file system (I created a unique filename within the container, searched for it on Windows, found nothing).

In the previous version (17.06.1), I was able to map folders as above without issues. Now I'm completely unable to map folders in any meaningful way.

### Information

B258654D-04F9-494C-9F43-8B514E3411E0/2017-09-08_15-32-25

Looking through the log I can see: `Rewrote mount c:/users/john:/mnt/john (volumeDriver=) to /c/users/john:/mnt/john`, which I'm guessing is maybe where the failure is coming from.

If I try with '\' rather than '/', I then see `Rewrote mount c:\users\john:/mnt/john (volumeDriver=) to /c/users/john:/mnt/john`

- I've just installed the older version (link below) and the same command maps the correct folder.

### Steps to reproduce the behavior

0. Replace `c:/users/john` with an applicable folder on your file system.
1. Run `docker run -it -v c:/users/john:/mnt/john ubuntu:16.04`
2. Within the container run: `cd /mnt/john` and then `ls` - it's empty.
3. Still within the container, run: `touch test` and then run `ls` to confirm that the file has been created.
4. Exit the container.
5. Run `docker run -it -v c:/users/john:/mnt/john ubuntu:16.04`
6. Within the container run: `cd /mnt/john` and then `ls` - you should see one file, `test`.

**Comment by lostllama** [comment]
For anyone with the same issue, I found the previous installer here: [https://download.docker.com/win/stable/13025/Docker%20for%20Windows%20Installer.exe](https://download.docker.com/win/stable/13025/Docker%20for%20Windows%20Installer.exe)

**Comment by lostllama** [comment]
@jasonbivins Is this a bug or do I need to change the way I do things for the latest Docker release?

**Comment by jasonbivins** [comment]
Hi @lostllama     I'll test this on my environment and get back to you.   Thanks!

**Comment by ariovistus** [comment]
I swear I ran into this on wednesday. Reverted my docker install, then today upgraded it again to test for an unrelated bug, and now I can't reproduce it. Currently I have 17.09.0-ce, build afdb6d4, before it was 17.09.0-ce, don't know build
