### ISSUE TITLE
docker run --pull not available in WSL2 client

### ISSUE THREAD

**Issue by pdinin** [docker/for-win#10795]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
In Ubuntu-20.04 (WLS2),   "docker run --pull" fails as --pull is an unknown flag
It is available in the CMD and PS environments 
 
### Expected behavior
Within  Ubuntu-20.04 (WLS2), able to execute "docker run --pull always" flag
### Information

  - Windows Version: Windows 10 Version	10.0.18363 Build 18363
  - Docker Desktop Version:
  - # docker version
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Fri Dec 18 12:15:19 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
  - WSL2 or Hyper-V backend?  WLS2 - Ubuntu-20.04
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. in WSL2 window:   docker run --pull always

**Comment by stephen-turner** [comment]
Can't repro. It's working fine for me, and also we use the same CLI for WSL 2 as Hyper-V. Are you sure you are using the CLI we distribute and haven't apt-get'ted a different one?

**Comment by pdinin** [comment]
Thanks for taking a look.

Deinstalled Docker for Windows
apt remove docker* in WSL2
Re-installed Docker for Windows
I am now getting the correct docker client

**Comment by stephen-turner** [comment]
Great, thanks for letting us know.
