### ISSUE TITLE
Enabling K8s on docker desktop stuck on starting

### ISSUE THREAD

**Issue by amruta-d** [docker/for-win#10807]
Expected behavior
Kubernetes cluster should start

Actual behavior
Kubernetes keeps indicating that it is starting

Information
Running docker for windows 10, with docker version Docker version 19.03.5, build 633a0ea. I enabled Kubernetes and it is just stuck on starting.

Diagnosis ID: 0B530861-B6BE-42C5-8192-4E8CEEC1109E/20210401212028

Steps to reproduce the behavior
Open Docker settings
Click enable on the kubernetes tab

**Comment by peZhmanParsaee** [comment]
You should see logs that is located in this file:

```
C:\Users\[YOUR USER]\AppData\Local\Docker\log.txt
```

Usually the problem is mentioned in the end lines of this file.

**Comment by bluebasslab** [comment]
After upgrading my K8s cluster is also stuck in starting.  The log file shows this - msg="Error while setting up kubernetes: cannot expose the external port: listen tcp 127.0.0.1:6443: bind: An attempt was made to access a socket in a way forbidden by its access permissions.. Retrying in 1s"

Any ideas on ways to fix this?  Thanks in advance!
