### ISSUE TITLE
"." shorthand directory mounted volumes are empty in Container

### ISSUE THREAD

**Issue by f3ndot** [docker/for-win#1080]
### Expected behavior

I can see the contents of the directory either explicitly with full path or with the `.` shorthand to refer to current working directory.

### Actual behavior

Only explicit full path works. Using `.` shows empty in container.

### Information

  - Diagnostic ID `4DFE61D3-E8FC-41B6-9A21-20041A237711/2017-09-09_09-30-45`
  - Windows 10, latest
  - Docker for Windows, `Docker version 17.06.2-ce, build cec0b72`
  - Windows C: and D: drive both set to shared
  - Similar in nature to https://github.com/docker/for-win/issues/25 but I'm sure is a different cause.

### Steps to reproduce the behavior

  1. Explicit full path works:
      ```
      PS C:\Users\Justin> docker run --rm -v C:\Users\Justin\:/data alpine ls /data
      AppData
      Application Data
      Code
      ...
      PS C:\Users\Justin>
      ```
  2. But using the relative `.` style, which is used in my team's `docker-compose.yml` file, does not:
      ```
      PS C:\Users\Justin> docker run --rm -v .:/data alpine ls /data
      PS C:\Users\Justin>

**Comment by f3ndot** [comment]
Some more details:

```
PS C:\Users\Justin> docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 57
Server Version: 17.06.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.41-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: moby
ID: 5JRX:P7OY:CXB2:IKPY:OU5C:XPGP:Z2GI:M2HR:Q75A:2Q4F:Q4ID:KV6O
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 15
 Goroutines: 26
 System Time: 2017-09-09T13:50:59.1291414Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by liyo** [comment]
Same issue here.

**Comment by Lucas-C** [comment]
This may be related to https://github.com/moby/moby/issues/34997

**Comment by Lucas-C** [comment]
It's really sad that id doesn't work with `docker run -v` nor `docker stack`,
but `docker-composer` makes the necessary file path conversion and it all works fine.
