### ISSUE TITLE
Containers with --platform=linux always return with exit code -1 on Windows Containers

### ISSUE THREAD

**Issue by bdegreve** [docker/for-win#10813]
- [X] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features  
         (no because I need the experimental feature to use `--platform linux`)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

`docker run --platform linux ...` always exits with exit code -1, even if the process it ran inside the container exited successfully.

### Expected behavior

If the process in the container exits successfully, I expect docker run to exit successfully as well.

### Information

  - Windows Version: 10 2004 build 19041.868
  - Docker Desktop Version: 3.2.2
  - WSL2 or Hyper-V backend? Hyper-V I guess, it's Windows Containers on Windows Pro.
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Switch to Windows Containers
  2. Open a powershell prompt
  3. Run `docker run --rm hello-world`
  4. Run `echo $LastExitCode`. This will print `0`.
  5. Run `docker run --rm --platform linux hello-world`
  6. Run `echo $LastExitCode`. **This will print `-1`.**
  7. Switch to Linux Containers
  8. Run `docker run --rm --platform linux hello-world`
  9. Run `echo $LastExitCode`. This will print `0` again.

**Comment by stephen-turner** [comment]
Thank you for the ticket. Unfortunately Linux Containers on Windows are now deprecated, and no further work will be done on them. See https://docs.docker.com/engine/deprecated/#linux-containers-on-windows-lcow-experimental.

**Comment by bdegreve** [comment]
@stephen-turner Thanks for letting me know, but this feature allowed me to run both Windows and Linux containers without having to swap between modes.  I.e. my Docker Desktop daemon was always in Windows containers mode, but this `--platfrom linux` swich allowed me to run Linux containers regardless.  Will this still be possible somehow?

**Comment by stephen-turner** [comment]
We don't have a solution for that right now, but we are aware of the use case and we do have a roadmap item at https://github.com/docker/roadmap/issues/79 that you can vote for.

Unfortunately LCOW (which was contributed by external developers, not our own employees) never reached a level of quality we were happy with, which is why it never graduated from experimental, and we haven't built another solution yet.
