### ISSUE TITLE
I cannot run docker on my virtual machine

### ISSUE THREAD

**Issue by rgabrielconstantin** [docker/for-win#10812]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by rgabrielconstantin** [comment]
B7001422-8804-4F75-A66A-8C39E1C80ABC/20210402074125

**Comment by stephen-turner** [comment]
See https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-desktop-in-nested-virtualization-scenarios
