### ISSUE TITLE
Unable to connect to a IPv6 listener with host.docker.internal

### ISSUE THREAD

**Issue by leobastiani** [docker/for-win#10820]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 463CA6FE-57D8-4251-BAF9-E2B283F65F5C/20210403031902

### Actual behavior
It's not possible to connect to a java application running on host within a docker container.
### Expected behavior
Be able to connect to a java application like it's possible to connect with any other application.
### Information
  - Is it reproducible? Yes.
  - Windows Version: 20H2 19042.662
  - Docker Desktop Version: 3.2.2 (61853)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

Here is my first post on stackoverflow when I thought it's an issue with docker. https://stackoverflow.com/questions/66894825/docker-container-is-not-able-to-connect-to-my-java-application-listening-on-host
Then I found it works on Ubuntu but it fails on Windows.

1. docker-compose.yml:
```yml
version: "3.8"
services:
  ssh:
    image: rastasheep/ubuntu-sshd
    ports:
      - "2222:22"
```

2. connect to it and install netcat
```bash
docker-compose up -d
ssh root@localhost -p 2222 # password is root
apt update && apt install -y netcat
```

3. run a netcat server on the host
```bash
nc -v -l 127.0.0.1 8080
```
4. try to connect to it. you will be able to connect successfully
```bash
nc -v host.docker.internal 8080
```
5. start any java application (an example is written below)
```bash
java ./Server.java
```
6. try to connect to it and see "Connection refused"
```bash
nc -v host.docker.internal 8080
```

### Some screenshots

![image](https://user-images.githubusercontent.com/8663061/113466376-b8c1de00-9411-11eb-8768-d1a2041f518a.png)
![image](https://user-images.githubusercontent.com/8663061/113466380-be1f2880-9411-11eb-8eaa-70c1dc4da9da.png)
![image](https://user-images.githubusercontent.com/8663061/113466382-c1b2af80-9411-11eb-9581-07e3fa524ca7.png)

### Server.java

```java
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.net.InetAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.net.UnknownHostException;

public class Server implements AutoCloseable {
  private final ServerSocket server;

  public Server(String host, int port, int backlogConnectionQueueLength)
      throws UnknownHostException, IOException {
    InetAddress inetAddress = InetAddress.getByName(host);
    System.out.println("inetAddress: " + inetAddress);
    server = new ServerSocket(port, backlogConnectionQueueLength, inetAddress);
    System.out.println(Thread.currentThread() + " Created Server");
  }

  public static void main(String[] args) {
    try (Server server = new Server("localhost", 8080, 50)) {
      server.start();
    } catch (IOException e) {
      System.out.println(e);
    }
  }

  public void start() {
    System.out.println(Thread.currentThread() + " Server Ready: " + server);
    while (true) {
      acceptAndHandleClient(server);
    }
  }

  private void acceptAndHandleClient(ServerSocket server) {
    System.out.println(Thread.currentThread() + " Waiting for Incoming connections...");
    try (Socket clientSocket = server.accept()) {
      handleNewClient(clientSocket);
    } catch (IOException e) {
      e.printStackTrace();
    }
  }

  private void handleNewClient(Socket clientSocket) throws IOException {
    System.out.println(Thread.currentThread() + " Received Connection from " + clientSocket);
    BufferedReader is = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));
    PrintStream os = new PrintStream(clientSocket.getOutputStream());
    // echo that data back to the client, except for QUIT.
    String line = null;
    while ((line = is.readLine()) != null) {
      System.out.println(Thread.currentThread() + " Server Got => " + line);
      if (line.equalsIgnoreCase("QUIT")) break;
      else {
        System.out.println(Thread.currentThread() + " Server echoing line back => " + line);
        os.println("Response: " + line);
        os.flush();
      }
    }
    System.out.println(Thread.currentThread() + " Server Closing Connection by Sending => Ok");
    os.println("Ok");
    os.flush();
    is.close();
    os.close();
  }

  public void close() throws IOException {
    server.close();
  }
}
```

**Comment by leobastiani** [comment]
Tested on Docker for Mac here (sorry it is in Portuguese) https://www.facebook.com/groups/806364762728291/permalink/4136934296337971/?comment_id=4139144289450305&reply_comment_id=4142867015744699
Tested on Ubuntu on my worker mate's pc and it worked
It just fails on Windows

**Comment by leobastiani** [comment]
I just realized how to solve it, When I executed `lsof -i :8080` it was marked as a IPv6 type. Then I executed the following command to run the server
`java -Djava.net.preferIPv4Stack=true ./Server.java`
Finally `lsof -i :8080` showed a IPv4 type and then I could connect to it from the container

**Comment by stephen-turner** [comment]
Glad you solved it. IPv6 support is not yet complete. This is documented at https://docs.docker.com/docker-for-windows/troubleshoot/#networking-issues. There is an issue on docker/roadmap that you can vote for if this is important to you.
