### ISSUE TITLE
(WSL2) docker build "output clipped, log limit 1MiB reached"

### ISSUE THREAD

**Issue by fcharron83** [docker/for-win#10839]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
When performing lengthy `docker build` operations using `DOCKER_BUILDKIT=1` (but **not `buildx`**), the command stops outputting logs with the _output clipped, log limit 1MiB reached_ message, until the build is over.

### Expected behavior
Allow customization of this 1MiB log limit setting either via a config file, or the _Docker Desktop - Docker Engine_ settings page.

### Information

  - Windows Version: **Windows 10 Enterprise, version 20H2 (OS Build 19042.867)**
  - Docker Desktop Version: **3.2.2 (61853)**
  - WSL2 or Hyper-V backend?  **WSL2**
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: **No, native Windows**

Problem is reproducible, and AFAIK is not new.

A similar issue has been opened for [docker buildx](https://github.com/docker/buildx/issues/484), but I am not running buildx because it is experimental and I am in a production environment.

### Steps to reproduce the behavior

  1. Start a lengthy `DOCKER_BUILDKIT=1 docker build...` operation that produces a lot of output logs on stdout/stderr (no flags except `--tag` and `--file`)
  2. Notice the _output clipped, log limit 1MiB reached_, and the absence of output afterward

**Comment by stephen-turner** [comment]
Thanks for the ticket. Unfortunately there's nothing we can do in Docker Desktop about this, as these components are all just upstreams to us. You could file a ticket in moby/moby (which owns docker build) but actually it's probably easier just to ask on the existing buildx ticket.
