### ISSUE TITLE
System.InvalidOperationException

### ISSUE THREAD

**Issue by CheolmanBae** [docker/for-win#10830]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by joaomliborio** [comment]
When i try to run docker show up a error message and not run. 
Can someone help me ?
<img width="518" alt="Docker" src="https://user-images.githubusercontent.com/74684301/113631554-02900b80-9640-11eb-9e5f-f50455bbfe51.PNG">
