### ISSUE TITLE
Error with starting Docker

### ISSUE THREAD

**Issue by jeschild1** [docker/for-win#10844]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 13A103CB-F0EB-4E70-8ACE-9249180642BA20210406070755

### Actual behavior
Started Docker Desktop and encountered error message:-
System.InvalidOperationException:
Failed to set version to docker-desktop: exit code: -1
 stdout: The attempted operation is not supported for the type of object referenced.

### Information

  - Windows Version: Windows 10 Home, Version 20H2, OS Build 19042.906, Windows Feature Experience Pack 120.2212.551.0
  - Docker Desktop Version: Docker Engine v20.10.5
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No.

### Steps to reproduce the behavior

1. Launch PowerShell with Admin Rights
2. Run command: dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
3. Run command: dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
4. Download and install WSL2 Linux kernel update package for x64 machines.
5. Run command in PowerShell: wsl --set-default-version 2
6. Restart PC
7. Install Docker Desktop (with default setting)
8. Start Docker Desktop and encounter error message reported above

**Comment by stephen-turner** [comment]
It still looks like WSL 2 is not fully installed. What does `wsl -l -v` show?

**Comment by StewartKUK** [comment]
I am having the same problem,  wsl -l -v shows a perfectly OK WSL 2 setup, and has not been a problem until today. The container I use does not anyway use WSL 2.
I am seeing several people all having the same problems as I am, each with different tickets. Everything was working fine until today. I have not made any changes to the configuration of the machine either.

**Comment by stephen-turner** [comment]
Interesting. No Windows updates in that time?

**Comment by StewartKUK** [comment]
If you don't have anything useful to add to the problem, try keeping quiet. If its the windows update, then it would be useful to know what in Docker it is breaking and why. Is it a Windows bug that has been squashed, and now it is breaking the code that has had workarounds written and is now now broken, or, has Microsoft broken Windows somehow.
I said 'I' had not changed any configuration... Does not mean that Windows did not install an update.

**Comment by stephen-turner** [comment]
@StewartKUK I am trying to narrow down the possible cause, and that tone is not acceptable in this repository.

**Comment by StewartKUK** [comment]
> 
> 
> @StewartKUK I am trying to narrow down the possible cause, and that tone is not acceptable in this repository.

I was reacting to your tone. As it happens my issue has resolved itself. Maybe another update (C++) to correct an earlier update. Although there was also a small disk problem that that chkdsk fixed. So, good luck and try to use more words next time, it might prevent the possibility that someone might think you were being sarcastic.
