### ISSUE TITLE
Docker container exited (139) emmidiatly after running

### ISSUE THREAD

**Issue by ptahery** [docker/for-win#10845]
Hi,

I have a problem with docker container for "qiicr/dcmqi".
After running it exits immediately with exited (139). I tried all the below commands but they don't work.

        docker run qiicr/dcmqi
        docker run -dit --name my_dcmqi qiicr/dcmqi
        docker run -dit qiicr/dcmqi
        docker run -it qiicr/dcmqi:latest
        docker run -i qiicr/dcmqi
        docker run -it qiicr/dcmqi
        docker run -it qiicr/dcmqi bash -c "tail -f /dev/null"

I would be grateful if you help me.
Best.

**Comment by stephen-turner** [comment]
Do you get the same problem with other containers? If not, it is a problem with the container, not with Docker.

**Comment by ptahery** [comment]
Thanks for your reply.
I have this problem only with this container.
Best.

**Comment by stephen-turner** [comment]
Thanks for your reply. In that case, you should talk to the container author about it.

**Comment by thaJeztah** [comment]
The image is based on a _very_ old version of CentOS, which could be the culprit; https://github.com/QIICR/dcmqi/blob/3d01c021dcce4c770f901f0b8f4ee3652a8ecb69/docker/dcmqi/Dockerfile#L1
