### ISSUE TITLE
Docker and Visual Studio Error: Cannot load Newtonsoft.Json Version = 9.0.0.0

### ISSUE THREAD

**Issue by ac22345** [docker/for-win#10840]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: AD88085F-EF05-4AFB-B6F7-58FCCF97BE87/20210405175821

### Actual behavior
I am using Docker with Visual Studio Community 2019. Below is my configuration for Docker:
Version: 3.2.2 (61853)
Engine: 20.10.5
Compose: 1.28.5
Kubernetes: v1.19.7
Notary: 0.6.1
Credential Helper: 0.6.3
Synk: v1.432.0

I keep receiving an error that says "The PrepareForLaunch task has failed unexpectedly. System.IO.FileNotFoundException: Could not load file or assembly Newtonsoft.Json version:9.0.0.0

I am using Visual Studio Community 2019, with Newtonsoft 12.0.3 installed. I have narrowed the bug down to Docker because the code compiles when built without Docker, and I have gone through the code and made a binding redirect, checked the references, etc. and there is no reason, in the code, that it should not run.

When I installed Docker, despite having Windows Pro, it prompted me to install WSL. I did, and I configured it according to the directions online, but still the error did not change. I cleaned and purged the data in Docker, and still the issue persisted. I also switched it from a Linux container to a Windows container, because by default it set to Linux, and that did not change the error. 

### Expected behavior
It should build my application.

### Information
 
  - Windows Version: Windows 10 Pro
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  I tried both, the error occured no matter which one I used
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: I am using Docker Desktop

### Steps to reproduce the behavior

Unsure of where to find Docker file that reproduces issue
1. Download Visual Studio Community 2019
2. Install latest version of Docker
3. Build w/ Docker

**Comment by stephen-turner** [comment]
"The PrepareForLaunch task has failed unexpectedly" is a Visual Studio error, not ours. So unless you can demonstrate an error message without using Visual Studio, I suggest you file a ticket in the https://github.com/microsoft/DockerTools repo.
