### ISSUE TITLE
Failed to restart

### ISSUE THREAD

**Issue by Frederic1971** [docker/for-win#10852]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 35E59141-65BB-4CB0-BD07-E1910379E8E9/20210407104622

### Information

  - Windows Version:10
  - Docker Desktop Version: 3.2.2
  - WSL2 or Hyper-V backend?  WSL2 (Hyper-V deactivated)
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...when I start Docker Desktop, the icon becomes red with an error message "Failed to restart"
System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\fbacheli\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Le fichier spécifié est introuvable.
  2. ...

**Comment by stephen-turner** [comment]
Thanks for the ticket. This error usually means that you haven't installed WSL 2 correctly, which Docker Desktop uses. Please follow Microsoft's instructions at https://aka.ms/wsl2-install. If it's set up correctly, then the command wsl -l -v should show a version 2 distro.
