### ISSUE TITLE
Feature request: Add option to configure 127.0.01 for host.docker.internal instead of the local endpoint.

### ISSUE THREAD

**Issue by Scherlac** [docker/for-win#10856]
This topic is applicable on docker desktop community (Windows). (Hyper-V and WSL2)

My current configuration is:

    Windows version: 1909
    Docker: 2.4.0.0 (48506)
    Engine: 19.03.13

I have local proxy to bypass corporate proxy (with domain authentication)

### Actual behavior

The following entries are added to the hosts file (windows: system32/drivers/etc) automatically:

    # Added by Docker Desktop
    192.168.21.129 host.docker.internal
    192.168.21.129 gateway.docker.internal

The following environment setting works for host:

    http_proxy="http://127.0.0.1:3128" 

The following environment setting works for container:

    http_proxy="http://host.docker.internal:3128" 

### Expected behavior

I would like to have the same string for http_proxy on host and inside the container. Preferably: 

     http_proxy="http://host.docker.internal:3128"

### Information

On host with VPN connection the host network is often routed to corporate network. The docker local endpoint (`host.docker.internal`) is not reachable, only the `127.0.0.1` address is reachable. So we need to configure local proxy on `127.0.0.1:3128`. That means on the host the correct proxy settings is `127.0.0.1:3128` but inside of the container it is accessed using `host.docker.internal:3128`. 
  
Currently I add the following line to the hosts file (windows: system32/drivers/etc) to accommodate easy proxy configuration:

    # Deprecated hostname:
    127.0.0.1 docker.for.win.localhost

The following environment setting works for host and for containers too:

    http_proxy="http://docker.for.win.localhost:3128" 

### Proposal 

We shall add a new option as follows:

- The name of the option should be: "Enable VPN conform hosts file configuration."
- This option should only override the hosts file's entry on the host. 
- In case the option is enable the following line should be replaces:

from:

    192.168.x.x host.docker.internal

to: 

    127.0.0.1 host.docker.internal

**Comment by mg-christian-axelsson** [comment]
+1 for visibility on this.
I get hit by this every time I reboot (monthly or so) and each time I have forgotten what I needed to do to be able to connect to my containers from within the WSL2 environment.

**Comment by mg-christian-axelsson** [comment]
Closely related to #10420
