### ISSUE TITLE
mounted volume within docker doesn't contain data

### ISSUE THREAD

**Issue by bakkenkl** [docker/for-win#1086]
### Expected behavior
I'm using Xibo within Docker.  This used to work, so I'm sure its something I've done, but I'm not experienced enough with Docker to figure it out.  The 'windows' directory /xibo/shared/cms/web/userscripts is mounted into /var/www/cms/userscripts.  And it looks like it when I do a 'mounts' within docker.  The 'mount' command returns (along with lots of other mounts): 
tmpfs on /var/www/cms/web/userscripts type tmpfs (rw,relatime)

### Actual behavior
The docker userscripts directory is empty

### Information
 7AA1A7C5-F3CE-46B8-A33E-3A508694F490/2017-09-12_19-07-05

Running Windows 10 Pro, all latest updates, latest Xibo, etc.

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by lostllama** [comment]
Is this the same as [my issue](https://github.com/docker/for-win/issues/1078) ?
