### ISSUE TITLE
Docker Crashes Everyday.

### ISSUE THREAD

**Issue by postsaurav** [docker/for-win#10863]
- [X ] I have tried with the latest version of Docker Desktop
  - [ X] I have tried disabling enabled experimental features
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID: 12DB0E1A-710B-46E5-9CBA-F55FFC570E33/20210408044408

### Information

  - Windows Version: Windows 10.
  - Docker Desktop Version: 
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem?
