### ISSUE TITLE
"Company" metadata missing from dockerd.exe

### ISSUE THREAD

**Issue by forderud** [docker/for-win#10866]
"Company" name metadata is missing from `dockerd.exe`. This is causing problems for my company's ability to whitelist the executable, so that it's allowed to run on a security-hardened system using [Digital Guardian](https://digitalguardian.com/).

  - [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

dockerd.exe does _not_ contain any "Company" name metadata.

### Expected behavior

dockerd.exe does contain "Docker Inc" in "Company" name metadata.

### Information
  - Windows Version: 1909 (Windows 10 enterprise 64bit)
  - Docker Desktop Version: 3.2.2 (61853)
  - WSL2 or Hyper-V backend? N/A
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior
* Download *Sigcheck* from https://docs.microsoft.com/en-us/sysinternals/downloads/sigcheck
* Run `sigcheck64.exe "c:\Program Files\Docker\Docker\resources\dockerd.exe"` and observe the following:
```
        Verified:       Signed
        Signing date:   14:07 13-Mar-21
        Publisher:      Docker Inc
        Company:        n/a
        Description:    n/a
        Product:        Docker Engine
        Prod version:   20.10.5
        File version:   20.10.5
        MachineType:    64-bit
```

**Comment by stephen-turner** [comment]
Thanks for the report, @forderud, I've raised this with the team that builds this component.

**Comment by forderud** [comment]
Gentle reminder. Any update on adding "Company" metadata to dockerd.exe, so that it becomes more compatible with security hardened setups?

**Comment by stephen-turner** [comment]
Sorry about that. I did forward it to the correct team before: I've pinged them again.

**Comment by stephen-turner** [comment]
@forderud In the immediate term, can you base your allow-list on the Publisher field instead? I have to admit I'm not 100% sure of the difference between these fields (maybe you know more?) but a bit of Googling suggests that more people trust the Publisher.

**Comment by forderud** [comment]
> @forderud In the immediate term, can you base your allow-list on the Publisher field instead? I have to admit I'm not 100% certain of the difference between these fields (maybe you know more?) but I think the publisher comes from the signing process whereas the company name is just arbitrary metadata. Certainly a bit of Googling suggests that people recommend checking the publisher rather than the company.

Already tried, but my request was declined by my company's IT department that manages the Digital Guardian setup.

**Comment by forderud** [comment]
Gentle reminder. Any progress on this issue?

**Comment by forderud** [comment]
I just checked with the latest Docker desktop 4.12.0, and the **problem still remains** there. Therefore, can you please reopen this issue?
