### ISSUE TITLE
Cannot perform reverse DNS lookups within containers on Windows WSL2

### ISSUE THREAD

**Issue by brenc** [docker/for-win#10876]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 0F6E490E-1E45-4A54-8C92-55DD98FEE722/20210409045054

### Actual behavior

I've been developing on remote Docker on Linux installations for a while now. Recently I've been transitioning to local development on my Windows desktop. One thing I noticed right away is that reverse DNS lookups in containers on Docker Desktop for Windows appear to be broken:

```
# In a Debian WSL2 terminal:
$  docker run -it --rm alpine ash
/ # apk update && apk add bind-tools
...

# Using the container's DNS server doesn't work:
/ # dig -x 8.8.8.8

; <<>> DiG 9.16.11 <<>> -x 8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 18337
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;8.8.8.8.in-addr.arpa.          IN      PTR

;; Query time: 0 msec
;; SERVER: 192.168.65.5#53(192.168.65.5)
;; WHEN: Fri Apr 09 04:55:23 UTC 2021
;; MSG SIZE  rcvd: 38


# Querying the authoritative nameserver directly works:
/ # dig @ns1.google.com -x 8.8.8.8

; <<>> DiG 9.16.11 <<>> @ns1.google.com -x 8.8.8.8
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 28072
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;8.8.8.8.in-addr.arpa.          IN      PTR

;; ANSWER SECTION:
8.8.8.8.in-addr.arpa.   86400   IN      PTR     dns.google.

;; Query time: 40 msec
;; SERVER: 216.239.32.10#53(216.239.32.10)
;; WHEN: Fri Apr 09 04:58:44 UTC 2021
;; MSG SIZE  rcvd: 73


# Querying my local DNS server directly works:
/ # dig @192.168.80.2 -x 8.8.8.8

; <<>> DiG 9.16.11 <<>> @192.168.80.2 -x 8.8.8.8
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3180
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;8.8.8.8.in-addr.arpa.          IN      PTR

;; ANSWER SECTION:
8.8.8.8.in-addr.arpa.   64339   IN      PTR     dns.google.

;; Query time: 0 msec
;; SERVER: 192.168.80.2#53(192.168.80.2)
;; WHEN: Fri Apr 09 05:37:03 UTC 2021
;; MSG SIZE  rcvd: 73


# Forward resolution works:
/ # dig dns.google

; <<>> DiG 9.16.11 <<>> dns.google
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53491
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;dns.google.                    IN      A

;; ANSWER SECTION:
dns.google.             592     IN      A       8.8.4.4
dns.google.             592     IN      A       8.8.8.8

;; Query time: 30 msec
;; SERVER: 192.168.65.5#53(192.168.65.5)
;; WHEN: Fri Apr 09 05:09:48 UTC 2021
;; MSG SIZE  rcvd: 60
```

I've tried several different IP addresses and container images all with the same result.

Reverse lookups work from the Debian WSL2 host. This all works inside containers on my Docker on Linux installations as well.

DNS resolution inside containers on Windows appears to be working as expected otherwise. The only thing not working is reverse lookups.

### Expected behavior

Should be able to perform reverse DNS lookups in a container on Windows.

### Information

This is a fresh reinstallation of Docker Desktop on this system as of tonight. I have never noticed this before but this is the first time I'm running an application on Docker Desktop for Windows that needs to perform reverse DNS lookups.

  - Windows Version: Microsoft Windows 10 Pro for Workstations 10.0.19042 Build 19042
  - Docker Desktop Version: Docker version 20.10.5, build 55c4c88
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

I believe I covered this above.

**Comment by stephen-turner** [comment]
Thanks for the report, @brenc. Does it only fail in Alpine containers, or does it also fail if you use, say, an Ubuntu container? We have fixed some bugs recently caused by differences between the DNS in Alpine and glibc distros, but maybe there's still something missing.

**Comment by brenc** [comment]
@stephen-turner reverse DNS lookups also fail in Ubuntu, Debian, etc.

**Comment by stephen-turner** [comment]
OK, thanks, in that case it must be our DNS implementation. @djs55 can you have a look please?

**Comment by brenc** [comment]
This is still an issue with `Docker version 20.10.7, build f0df350`.

/remove-lifecycle stale

**Comment by brenc** [comment]
/remove-lifecycle stale

```$ docker -v
Docker version 20.10.11, build dea9396```
