### ISSUE TITLE
Docker Dashboard does not display containers and images

### ISSUE THREAD

**Issue by FlorentDev** [docker/for-win#10880]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A86F6433-9B7B-4EEE-B815-522B3E9D4EDE/20210409100916

### Actual behavior
The Docker Dashboard does not display the container and the images in the UI

### Expected behavior
Running and stopped container should be list in the UI. Same for the images in the correct section

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible? Always, Docker Dashboard doesn't work since several versions
  - Is the problem new? No
  - Did the problem appear with an update? Yes
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.
    All docker images and containers

  - Windows Version:
  - Docker Desktop Version: 3.2.2
  - WSL2 or Hyper-V backend?  Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No, local machine

### Steps to reproduce the behavior
For all docker containers and images:
- The command line "docker ps" or "docker ps -a" or "docker images" show me stopped and running containers and available images
- The Docker Dashboard is completly empty

**Comment by qferr** [comment]
Same problem

**Comment by BenHarris** [comment]
My containers do appear, but my images tab is empty. I'm using WSL2 on Windows 10. It has probably been like this for a week or two.

**Comment by BenHarris** [comment]
Now running 3.3.1 and still experiencing the same problem. @FlorentDev @qferr - did either of you find a solution?
