### ISSUE TITLE
Cannot download the docker

### ISSUE THREAD

**Issue by syj193** [docker/for-win#1088]
### Expected behavior
downloading docker
### Actual behavior
After installation of docker for Windows
Error says unable to stop:~~~ "ErrorActionPreference"~~~cannot load Hyper-V
Diagnostic ID-4EC67112-2FFC-4846-B9DC-C18273E3A7D2/2017-09-13_18-27-29

My Window version is 10
Please understand some languages are in Korean.
Here is the log file

Unable to stop: 기본 설정 변수 "ErrorActionPreference" 또는 일반 매개 변수가 Stop으로 설정되어 있으므로 실행 중인 명령이 중지되었습니다. 모듈 디렉터리에 올바른 모듈 파일이 없으므로 지정한 모듈 'Hyper-V'을(를) 로드하지 못했습니다.
위치: <ScriptBlock>, <파일 없음>: 79번째 줄
   위치: Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) 파일 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:줄 177
   위치: Docker.Backend.ContainerEngine.Linux.DoStop() 파일 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:줄 280
   위치: Docker.Backend.ContainerEngine.Linux.Stop() 파일 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:줄 146
   위치: Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) 파일 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:줄 47
   위치: Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) 파일 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:줄 145  

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jasonbivins** [comment]
Hi @syj193 
Are you able to start and connect to any other VMs using Hyper-V manager?

**Comment by syj193** [comment]
I some how heard that Docker is not available on Windows 10 Home.
So I am trying do download Docker through the toolbox..
