### ISSUE TITLE
Group *docker-users* seems to be ignored with version 3.3.0

### ISSUE THREAD

**Issue by iBrotNano** [docker/for-win#10881]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

The command `docker` only shows *Access denied* when I try it with a non administrative user. The user is added at the group *docker-users*. The configuration works with version 3.2.2. I have checked it by deinstalling 3.3.0 and installing 3.2.2.

Doing a factory reset doesn't help.

`docker` works fine if i use it with an admin account.

### Expected behavior

Docker should work with a non admin account if it is added to the group *docker-users*.

### Information

  - Docker Desktop Version: 3.3.0
  - WSL2 or Hyper-V backend?  Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Steps to reproduce the behavior

  1. Login with a non admin account.
  2. Open a command line (cmd or powershell) and try `docker`.

**Comment by stephen-turner** [comment]
Thanks, we'll look into it.

**Comment by sidereal** [comment]
I'm seeing similar behaviour in my wsl2 setup since i updgraded to 3.3.0. I get a crash during startup when using a non-admin account in the docker-users group, but it's fine using an admin account.

uploaded a crash log with diagnostic ID > l9FF7A6E1-CB62-4B15-8723-C7F6E0A1480E/20210410125744

**Comment by mitchlgary** [comment]
I'm seeing the same behavior as well on Windows Home, WSL2, Docker Desktop 3.3.0.  Uploaded crash report 991771D2-C652-493E-8243-AA52DDE95567/20210411134111

**Comment by algra4** [comment]
I have also the same problem, diagnostic id  : C4B8F0DE-9E64-4E94-9471-2ED610A396AB/20210412062105

**Comment by gottschd** [comment]
Hello,

I'm facing the same problem. Uninstalling 3.3.0 and installing again 3.2.2 fixed the problem (temporarily). 
However, Docker Desktop will download and install the update 3.3.0 again automatically.

I appreciate the work you are doing, sure. However, with 3.3.0, i'm not able to do my work anymore. To be more exact, i'm blocked because of the update.

How about revoking the version 3.3.0 for now, so users can at least uninstall 3.3.0 and install 3.2.2?
It would help to be able to work again until a fix is available.

Thank you.

**Comment by stephen-turner** [comment]
Detailed repro steps in #10891.

**Comment by stephen-turner** [comment]
@gottschd As a workaround, we believe that downloading the installer directly from https://hub.docker.com/editions/community/docker-ce-desktop-windows/ should work.

**Comment by gottschd** [comment]
> 
> 
> @gottschd As a workaround, we believe that downloading the installer directly from https://hub.docker.com/editions/community/docker-ce-desktop-windows/ should work.

Thx, i will try the installer

**Comment by algra4** [comment]
> @gottschd As a workaround, we believe that downloading the installer directly from https://hub.docker.com/editions/community/docker-ce-desktop-windows/ should work.

Unfortunately, for me, this does not work. Docker forces me to install the latest version (so the 3.3.0)

**Comment by stephen-turner** [comment]
Right, but the 3.3.0 full installer (instead of the delta) should install successfully.

**Comment by C0untZero** [comment]
Can confirm that the full installer workaround works!
For anyone wanting to try this you can make sure you have the correct installer version po opening the exe prop > details - it should be 3.3.0.62916.

Thanks for the quick workaround @stephen-turner !

**Comment by gottschd** [comment]
> Right, but the 3.3.0 full installer (instead of the delta) should install successfully.

The installer you mentioned installs 3.2.2 for me, not 3.3.0. In other words, when downloading [https://desktop.docker.com/win/stable/Docker%20Desktop%20Installer.exe](https://desktop.docker.com/win/stable/Docker%20Desktop%20Installer.exe)
the installer window shows 3.2.2 in the headline. 
After that, some minutes later, the update is fetched and in systray a notification appears, telling me that an update will be installed upon the next time i start Docker Desktop:
![grafik](https://user-images.githubusercontent.com/25016222/114391992-78442c00-9b98-11eb-89e8-1b294f25b6bc.png)

I assume for this situation the same error will appear again.

**Comment by gottschd** [comment]
> 
> 
> Can confirm that the full installer workaround works!
> For anyone wanting to try this you can make sure you have the correct installer version by opening the exe properties > details - it should be 3.3.0.62916.
> 
> Thanks for the quick workaround @stephen-turner !

Thx for the hint with checking the version. I will give it a try later.

**Comment by C0untZero** [comment]
> > Right, but the 3.3.0 full installer (instead of the delta) should install successfully.
> 
> The installer you mentioned installs 3.2.2 for me, not 3.3.0. In other words, when downloading [https://desktop.docker.com/win/stable/Docker%20Desktop%20Installer.exe](https://desktop.docker.com/win/stable/Docker%20Desktop%20Installer.exe)
> the installer window shows 3.2.2 in the headline. 
> After that, some minutes later, the update is fetched and in systray a notification appears, telling me that an update will be installed upon the next time i start Docker Desktop:
> ![grafik](https://user-images.githubusercontent.com/25016222/114391992-78442c00-9b98-11eb-89e8-1b294f25b6bc.png)
> 
> I assume for this situation the same error will appear again.
> 

Try the download link from the release notes
https://docs.docker.com/docker-for-windows/release-notes/#docker-desktop-330
https://desktop.docker.com/win/stable/amd64/Docker%20Desktop%20Installer.exe

**Comment by gottschd** [comment]
> @gottschd Try the download link from the release notes
> https://docs.docker.com/docker-for-windows/release-notes/#docker-desktop-330
> https://desktop.docker.com/win/stable/amd64/Docker%20Desktop%20Installer.exe

@C0untZero 
Yes, with these links i successfully get the 3.3.0 installer (according the version from the *.exe) and after installing 3.3.0 directly the startup issue does not occur anymore.

Thx.

**Comment by krrico** [comment]
> @gottschd Try the download link from the release notes
> https://docs.docker.com/docker-for-windows/release-notes/#docker-desktop-330
> https://desktop.docker.com/win/stable/amd64/Docker%20Desktop%20Installer.exe

When you already downloaded the incremental update and cannot install the version 3.3.0 with the full installer since you are on the latest version already you can do the following to be able to run the full installer:

* run regedit as administrator
* got to _Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Docker Desktop_
* set **Version** to something lower than **62916**
* run the full installer which now thinks an old version is installed

This fixed the problem for me without de-installing Docker Desktop and with all my images and containers still available.

**Comment by gottschd** [comment]
> This fixed the problem for me without un-installing Docker Desktop and with all my images and containers still available.

Thx. 

Just to add my observations:
When uninstalling (the updated and non-starting) 3.3.0 and installing directly 3.3.0 (with the latest 3.3.0 installer, see above) ... my images, config (like insecure regsitries, wtc) were not lost..... Yep, everything was still there.

**Comment by StefanScherer** [comment]
We figured out that there is an issue with the updater from 3.2.2 to 3.3.0 when you start Docker Desktop with a non-administrative account. We have disabled the updater now.

The only effect the users of version 3.2.2 will see is that it will download the full 3.3.0 installer when you "Check for Updates", but this way the update works fine.

For users that currently can't start Docker Desktop 3.3.0 due to the update, please download the installer from our [Docker desktop 3.3.0 release notes](https://docs.docker.com/docker-for-windows/release-notes/#docker-desktop-330) page.

Thank for you patience!

**Comment by kingmotley** [comment]
Same issue, and can confirm reinstalling with the full 3.3.0 installer fixed it.

**Comment by algra4** [comment]
> > > Right, but the 3.3.0 full installer (instead of the delta) should install successfully.
> > 
> > The installer you mentioned installs 3.2.2 for me, not 3.3.0. In other words, when downloading [https://desktop.docker.com/win/stable/Docker%20Desktop%20Installer.exe](https://desktop.docker.com/win/stable/Docker%20Desktop%20Installer.exe)
> > the installer window shows 3.2.2 in the headline. 
> > After that, some minutes later, the update is fetched and in systray a notification appears, telling me that an update will be installed upon the next time i start Docker Desktop:
> > ![grafik](https://user-images.githubusercontent.com/25016222/114391992-78442c00-9b98-11eb-89e8-1b294f25b6bc.png)
> > 
> > I assume for this situation the same error will appear again.
> > 
> 
> @gottschd Try the download link from the release notes
> https://docs.docker.com/docker-for-windows/release-notes/#docker-desktop-330
> https://desktop.docker.com/win/stable/amd64/Docker%20Desktop%20Installer.exe

Thank ! It works for me 😃

**Comment by bevin0708** [comment]
Reinstalling from Release Notes page worked for me

**Comment by kitakou0313** [comment]
I had same problem, but reinstalling from https://desktop.docker.com/win/stable/Docker%20Desktop%20Installer.exe enabled me using docker without `Run as administrator` ! Thank you for your supporting!

**Comment by minettiandrea** [comment]
I'm falling in the same situation, auto-update to 3.3.0 and access denied.
Tryng to run the installer again, dowloaded from the release notes I get a message that is already at the latest version.
I'm a bit scared to uninstall the version that I have since I'm working on some databases stuff that is in the docker volume, by uninstalling I will lose my volumes as well?
Thank you

**Comment by krrico** [comment]
> 
> I'm falling in the same situation, auto-update to 3.3.0 and access denied.
> Tryng to run the installer again, dowloaded from the release notes I get a message that is already at the latest version.
> I'm a bit scared to uninstall the version that I have since I'm working on some databases stuff that is in the docker volume, by uninstalling I will lose my volumes as well?
> Thank you

See my answer above for how to re-install an already installed version:

> * run regedit as administrator
> * go to _Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Docker Desktop_
> * set **Version** to something lower than **62916**
> * run the full installer which now thinks an old version is installed

**Comment by mat007** [comment]
The fix has now been released with Docker Desktop 3.3.1. I’ll go ahead and close this issue. Thanks!
