### ISSUE TITLE
Failed to build docker image# 8072C157-BED6-4379-BE4C-EF1784DC05FF/20210412091243

### ISSUE THREAD

**Issue by ankur5289** [docker/for-win#10899]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ankur5289** [comment]
Actual behavior :Docker image build up fails in first step  using the below command :

docker build --tag dss .

Expected behavior :Image should get built up
Information
Windows Version: 1990 windows 10
Docker Desktop Version: 3.2.2
WSL2 or Hyper-V backend? WSL2
Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Yes on windows 10 VDI
Steps to reproduce the behavior
...
...

**Comment by stephen-turner** [comment]
What was the error message? And do other `docker` commands work?
