### ISSUE TITLE
Creating Diagnostic is long while CPU has room to spare

### ISSUE THREAD

**Issue by tebeco** [docker/for-win#10902]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 01A048BE-946F-4977-BF59-D435FEA6B778/20210412104800

### Actual behavior
Creating diagnostic takes up to 2 minutes seem to use max ~10% CPU on 16Core (which is 1 to 2 Core usage)
(without the upload)

here is what the CPU look like with ~80 Edge tab open and few container running:
Note that after the Diag, Docker still uses ~16%, which mean the diagnostic was barely using CPU but it was rather the DB running as a container that was using it

### Expected behavior
Not sur it's possible but it would require code change to parallelize the code responsible for the Diag generation

### Information
* SSD NVMe drive (Sequential Read: Up to 3GB/s. / Sequential Write: Up to 1.6GB/s. / Random Read: Up to 240K IOPS. / Random Write: Up to 210K IOPS.), so it's suppose to be able to handle Disk access if the slow path is I/O on disk
* i9-9980
* 32GB ram (more than 12 to spare before the run)

### Steps to reproduce the behavior

  1. start CPU profiler
  2. run diagnostic
  3. stop CPU profiler
  4. look for idle time

**Comment by stephen-turner** [comment]
I'm not too worried by this. I expect diagnostics collection to take some CPU if only to compress it, and it's (hopefully!) a rare operation.

**Comment by tebeco** [comment]
I was curious about what is taking a long time if the CPU seems to be waiting to do stuff
