### ISSUE TITLE
Docker startup failed with latest update 4/12

### ISSUE THREAD

**Issue by bevin0708** [docker/for-win#10904]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B9C538FE-11A1-4034-9ABD-7CADEA1A7A59/20210412141006

### Actual behavior
Startup Failed
### Expected behavior
Dockers Should start
### Information

  - Windows Version: Edition	Windows 10 Enterprise 20H2 OS build	19042.906 - Windows Feature Experience Pack 120.2212.551.0

  - Docker Desktop Version: 3.3.0. (62916)
  - WSL2 or Hyper-V backend?  Hyper-V due to VPN issue
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by joshralph93** [comment]
@bevin0708  I've had this same issue too this morning following the update to 3.3.0, but managed to work around the issue by uninstalling docker for windows and reinstalling from [https://docs.docker.com/docker-for-windows/release-notes/](https://docs.docker.com/docker-for-windows/release-notes/)
I'm not sure if this can cause any data to be lost though, but I'm yet to find anything missing.
Hope that helps!

**Comment by bevin0708** [comment]
Thanks for the tip. Yes, I was able to completely remove and reinstall Docker.
