### ISSUE TITLE
[Dev Environments]: Gettings Started open in weird boxed WebView inside a Docker Window

### ISSUE THREAD

**Issue by tebeco** [docker/for-win#10901]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:01A048BE-946F-4977-BF59-D435FEA6B778/20210412104800

### Actual behavior
Clicking the Video attempt to 
* open a Docker window
* which contain a WebView
* which start a new "Profile" (in Chromioum)
* which, as a link to Youtube and Google, need GDPR Constent
* which redirect to ...... 

The window 
* can't be resized
* can't be drag and drop
* can't be closed (`Alt+F4` works though)

![image](https://user-images.githubusercontent.com/2266487/114382119-488f2700-9b8c-11eb-912a-25abd9106651.png)
![image](https://user-images.githubusercontent.com/2266487/114382398-9ad04800-9b8c-11eb-8af5-0e3efeeac7a2.png)
![image](https://user-images.githubusercontent.com/2266487/114382412-9e63cf00-9b8c-11eb-9ce9-4f9ce80a9ae8.png)

the video is `Unlisted` Is that intended ?
![image](https://user-images.githubusercontent.com/2266487/114382426-a28fec80-9b8c-11eb-9798-21728d878480.png)

### Expected behavior
1. Open the Tab in user default browser (`Process.Start` + `ShellExecute` => will use scheme mapper and then default to "default browser" for free)
2. Allow to copy the Youtube link directly

### Steps to reproduce the behavior
  1. Open Docker
  2. Go to "Dev Environments"
  3. Click the video

**Comment by stephen-turner** [comment]
Thanks for the report, @tebeco. @glours could you take a look please?

**Comment by glours** [comment]
Yes sure!

**Comment by tebeco** [comment]
An unclear part of my question is :
_Is it intended for the video to be unlisted ?_

I suppose it made sense at some point in time when the video had to be done before the release of such feature, but shouldn't it be listed / public once released ?
