### ISSUE TITLE
[3.3.0] Despite removal of forced Auto-Update, "Docker Desktop Installer.exe" is still being run upon every startup

### ISSUE THREAD

**Issue by Harti** [docker/for-win#10913]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics 
  - Diagnostics ID: D761E6F0-74F4-42B6-BB05-655224447F29/20210413065149

### Actual behavior
Whenever I run "C:\Program Files\Docker\Docker\Docker Desktop.exe" (version 3.3.0), either automatically on startup or manually, it will actually run "C:\Users\{redacted}\AppData\Local\Temp\{randomly generated folder}\Docker Desktop Installer.exe" first. 

From an initial mini-inquiry with limited information this [seems to be unintentional](https://github.com/docker/roadmap/issues/183#issuecomment-817920089).

### Expected behavior
When I start Docker Desktop 3.3.0+, then the Installer executable is only called if the user explicitly chose to update their software via a prompt in the UI. Without detours, the Docker Desktop application is started.

### Information
- The problem has existed since the introduction of auto-updates (https://github.com/docker/roadmap/issues/183, https://github.com/docker/for-win/issues/10035), but I hoped it would not persist through 3.3.0.
- Back then, I believe I pressed "Restart and update" (or something along those lines), and that is when that behavior started.
- I have uninstalled Docker Desktop 3 since, and installed 2.5 in its stead
- I upgraded to 3.3 yesterday by downloading the installer manually from [the release notes page](https://docs.docker.com/docker-for-windows/release-notes/#docker-desktop-330), so I suppose this would account to being a "clean" install, but maybe there's a file or registry entry still causing the installer to be run.

The issue renders me unable to use Docker at all. This is due to a Windows Security Policy blocking the execution of the Installer.exe under the AppData directory. Without the installer being run, there is no successful internal "there are no updates, go on" check, and without that the software won't start. The Docker tray icon (without containers) is visible for a second, then vanishes.
There should either be a failover mechanism such as "if the installer didn't run, then attempt to run Docker Desktop anyway", or the Installer.exe shouldn't be run blockingly upon startup but rather in a background thread after the application booted.

Version info:
  - Windows Version: Win 10 / 20H2 (OS Build 19042.867)
  - Docker Desktop Version: 3.3.0
  - WSL2 or Hyper-V backend?  Both
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior
1. Install Docker Desktop 3.3.0.
2. Run the Desktop shortcut, or "C:\Program Files\Docker\Docker\Docker Desktop.exe" directly

Although it's probably only visible through the source code.

Thank you!

Best Regards,
Harti

**Comment by Harti** [comment]
@stephen-turner Sorry für @-ing you, though after your initial [acknowledgement](https://github.com/docker/roadmap/issues/183#issuecomment-817920089) I'm curious about the silence on this. Do you have any updates for me?

**Comment by stephen-turner** [comment]
@Harti I agree that you might have a stray pending download left lying around. In PowerShell, try
```Get-BitsTransfer```
to list the downloads. If there are any,
```Get-BitsTransfer | Remove-BitsTransfer```
will remove them all.

**Comment by Harti** [comment]
@stephen-turner this helped resolve my issue, thank you so much!

**Comment by stephen-turner** [comment]
Good news x 2 ! Thanks for letting us know.
