### ISSUE TITLE
Cant run dockers containers in IDE after update Docker.

### ISSUE THREAD

**Issue by githubjeka** [docker/for-win#10919]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - WSL2

After auto update Docker and auto restart Windows tonight my IDE cant up docker containers.

After the examination, I found out the reason - `docker-machine.exe` was removed from $PATH

![image](https://user-images.githubusercontent.com/874234/114665328-94191080-9d05-11eb-9952-c0095585d9d5.png)

Expect a large influx of people https://docs.docker.com/machine/install-machine/  and https://github.com/docker/docker.github.io/issues/12513 :)

#### 1. RUN in gitbash.exe

```bash
base=https://github.com/docker/machine/releases/download/v0.16.0 && mkdir -p "$HOME/bin" &&  curl -L $base/docker-machine-Windows-x86_64.exe > "$HOME/bin/docker-machine.exe" &&   chmod +x "$HOME/bin/docker-machine.exe"
```

#### 2. COPY
After install, copy file from `$HOME\bin\docker-machine.exe` to `"c:\Program Files\Docker\Docker\resources\bin\docker-machine.exe"`

![image](https://user-images.githubusercontent.com/874234/114666595-1ce47c00-9d07-11eb-8b46-8b7ba500dab9.png)

**Comment by stephen-turner** [comment]
Thanks for the report. Docker Machine was removed 15 months ago in version 2.2.0.0 (https://docs.docker.com/docker-for-windows/release-notes/#docker-desktop-community-2200) so I'm not expecting a huge influx now. It can still be downloaded separately.

**Comment by githubjeka** [comment]
Thanks, I had two attempts to find the changelog in program and https://hub.docker.com/editions/community/docker-ce-desktop-windows/, but I couldn't.

It's strange how I worked for 15 months in a row. Computer rebooted 4 times definitely due to Windows updates, at the same time the docker was updated several times 😕

**Comment by githubjeka** [comment]
I also remembered, two weeks ago, I installed clean Windows and had Docker and IDE installed there. How it works there, there was no need to install Docker Machine separately, I need to go there and figure it out ...

**Comment by githubjeka** [comment]
Now I'm near another computer and here the docker machine is not installed, but in the IDE it is simply not used and everything works.

![image](https://user-images.githubusercontent.com/874234/114762762-bc872600-9d6a-11eb-9475-4ce752ccd3ba.png)

Thank you and sorry to bother you.
