### ISSUE TITLE
simultaneous keyboard presses breaks terminal connection

### ISSUE THREAD

**Issue by dcrawford1** [docker/for-win#1092]
It might just be a problem on my machine, but just wondering if anybody else has this issue.  I can reproduce it from pretty much any docker image.  So within powershell I run: `docker run --rm -it alpine:3.6 sh`.  Then within the shell session if I press any 2 keys on the keyboard simultaneously.  It might take a couple of attempts, but eventually the terminal session will disconnect and the powershell console window no longer responds or echos back keyboard input.

Running the latest 17.06.2.  Windows 10 Creator Update.  Pretty much everything is standard Docker for Windows.

**Comment by jasonbivins** [comment]
Hi @dcrawford1 

You're definitely not the only one affected by this!   I've already got this in our internal issue tracker, but I don't have an ETA on a fix.  I'm going to go ahead and close this as a duplicate, this has been reported already as an issue here: https://github.com/docker/for-win/issues/934


Thanks!
