### ISSUE TITLE
Any Help please 

### ISSUE THREAD

**Issue by Bordeianu18** [docker/for-win#10936]
Good day everyone. 
In not good in It and coading, and i try to instal docker on my computer but i have some problems.

I enable the virtualization in bios and even if i do that i receive this eror : Hardware assisted virtualization and data execution protection must be enabled in the BIOS. See https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization
I use this for PI cryptocurency, its says that docker is succesfuly instaled, but docker deamon is not properly working.

I also enable the hyper v and still not working. 

I add my diagnostic id.

  - [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 461C0CAA-9A60-44C1-B2AA-0A3141782B70/20210415142505

### Information

  - Windows Version:10 
  - Docker Desktop Version:new 
  - WSL2 or Hyper-V backend?  hyper v
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: i dont know

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by VincentVanBork** [comment]
Hey did you check out if your hardware/processor supports virtualization?
Github is not a place to ask for help in installation. However you could try to update your information at least. 
Windows version - win+r and type in winver
Docker Desktop version - you can run this  Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\* | select DisplayName,DisplayVersion | where {$_.DisplayName -like "Docker*"}
virtualized machine - did you create any virtual machines on your computer? and install there Docker for Windows ? or maybe you are using system created in the cloud eg. Azure ? If answer is no then it is not virtualized Windows
