### ISSUE TITLE
Docker Desktop 3.3.0 for Windows 10 Not starting Automatically

### ISSUE THREAD

**Issue by romit7** [docker/for-win#10941]
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 67713380-13E0-48C7-9861-3E5B4D2F84E4/20210416120506

### Actual behavior
Docker desktop for windows not starting when restarted my PC. This happened after an update
Even restarting the Docker for desktop windows service is not helping.
Even going to settings of the docker desktop, the screen just goes on loading…so not able to hit the ‘Apply and Restart’ button.

When I do the docker version below is the output

```
$ docker version
Client: Docker Engine - Community
Cloud integration: 1.0.12
Version: 20.10.5
API version: 1.41
Go version: go1.13.15
Git commit: 55c4c88
Built: Tue Mar 2 20:14:53 2021
OS/Arch: windows/amd64
Context: default
Experimental: true
error during connect: This error may indicate that the docker daemon is not running.: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version: open //./pipe/docker_engine: The system cannot find the file specified.
```
### Expected behavior
The docker desktop should start automatically when I restarted my PC
### Information

  - Windows Version: 10 Enterprise, Version 1909, OSBuild 18363.1316
  - Docker Desktop Version: 3.3.0
  - WSL2 or Hyper-V backend?  -WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Virtualized Windows

### Steps to reproduce the behavior

  1. Docker Desktop is not running when I restarted the windows. 
  2. This happened after the update.
  3. When clicking on settings of  the docker desktop icon in taskbar , the page goes on loading....... so not able to click on any button - like "`Apply and Restart`' .
  4. Diagnostic ID : 67713380-13E0-48C7-9861-3E5B4D2F84E4/20210416120506

**Comment by m-unkel** [comment]
As a temporary workaround: Docker can be started by running the following command after reboot:
"C:\Program Files\Docker\Docker\DockerCli.exe" -SwitchLinuxEngine
