### ISSUE TITLE
Docker was removed from the system instead of updating, and after installation, you cannot turn off auto-updates

### ISSUE THREAD

**Issue by TalosDx** [docker/for-win#10948]
At startup, the docker refreshed and deleted all the data that I had been collecting for the whole day in order to fix one very complex bug.
Besides:
* THOUGH, THE DOKER DIDN'T ASK ME WHETHER I WANT TO UPDATE.
* Can't turn off docker auto-updates

Windows 10 Pro
Using only for yourself, no enterprise development

And please tell me, how can I get back my data that you deleted without asking my permission?

Note:
I don't want to receive any more updates for your app.
You spoil my mental and physical health, I almost had a heart attack 

![2021-04-16_18-45-15](https://user-images.githubusercontent.com/9301662/115049948-efa0f500-9ee3-11eb-9db7-e5ec47d54234.jpg)

**Comment by stephen-turner** [comment]
Auto-updates have been removed in version 3.3.0. From now on you will now get reminders to update, but can choose the actual time.

Also, updating doesn't normally destroy any data. I don't know what happened there without knowing the whole story of where the data was stored and what exactly you did.

**Comment by TalosDx** [comment]
Removed everything in the code related to updates and compiled my docker.
I hope you don't mind? Yes? Because you didn't mind deleting all my data
