### ISSUE TITLE
Error on start after of automatic update

### ISSUE THREAD

**Issue by lexuzieel** [docker/for-win#10950]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 49829F11-4055-4DB9-A340-57B7462CA36B/20210417095147

### Actual behavior

Error on start after of automatic update

```
System.ComponentModel.Win32Exception:
Access is denied
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Docker.ManagedProcesses.ManagedProcess.StartProcess(String fileName, String arguments, String currentDirectory, IDictionary`2 envVariables, CancellationToken stopToken) in C:\workspaces\PR-15633\src\github.com\docker\pinata\win\src\Docker.Desktop\ManagedProcesses\ManagedProcess.cs:line 121
   at Docker.ManagedProcesses.ManagedProcess.Start(String arguments, String currentDirectory, IDictionary`2 envVariables) in C:\workspaces\PR-15633\src\github.com\docker\pinata\win\src\Docker.Desktop\ManagedProcesses\ManagedProcess.cs:line 49
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__26.MoveNext() in C:\workspaces\PR-15633\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 148
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-15633\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15633\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15633\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
```

Resetting to factory defaults **does not** fix the problem.

### Expected behavior

No error

### Information

  - Windows Version: Windows 10 Education (10.0.19041 Build 19041)
  - Docker Desktop Version: 3.3.1 (63152)
  - WSL2 or Hyper-V backend? WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Boot up Windows
  2. Trigger automatic upgrade from previous version (it got triggered automatically)

**Comment by geekonthepc** [comment]
+1 for me.

Downgrading to 3.2.2 is the only workaround for me at the moment.

**Comment by stephen-turner** [comment]
Thanks for the report. I think this is the same as #10881. Although the bug is fixed in 3.3.1, you will still see it when upgrading from a buggy version.

The workaround is to download the full installer from https://www.docker.com/products/docker-desktop, instead of the delta installer that the updater gives you by default. If you get a complaint that 3.3.1 is already installed, then follow this workaround: https://github.com/docker/for-win/issues/10881#issuecomment-819689995.

**Comment by mat007** [comment]
What does this powershell command output
```
.\icacls.exe 'C:\Program Files\Docker\Docker\resources\docker.exe'
```
?

**Comment by geekonthepc** [comment]
@stephen-turner Thanks for your response. I spent most of this morning doing completely clean installs of both DD 3.3.1 and 3.3.0 on Windows - I removed all Docker related files in AppData\Local, AppData\Roaming, ProgramData and Program Files. Neither version would run after starting - I just got a frozen GUI after launching for about 2 minutes then "It looks like there is an error with docker desktop, restart it to fix it".
Repeating this with 3.2.2 is now working fine. 

@mat007 
C:\Program Files\Docker\Docker\resources\docker.exe NT AUTHORITY\SYSTEM:(I)(F)
                                                    BUILTIN\Administrators:(I)(F)
                                                    BUILTIN\Users:(I)(RX)
                                                    APPLICATION PACKAGE AUTHORITY\ALL APPLICATION PACKAGES:(I)(RX)
                                                    APPLICATION PACKAGE AUTHORITY\ALL RESTRICTED APP PACKAGES:(I)(RX)

**Comment by mat007** [comment]
@geekonthepc I guess you ran the command with 3.2.2 installed, right?
Permissions look right, but that file was moved to `resources/bin` in 3.3.

Do you run Docker Desktop with a non-admin user by the way?

**Comment by geekonthepc** [comment]
@mat007 Sorry Matt, yes I did! I'm reluctant to try going back now as I've lost too much time today :D
I run it as an admin user.

**Comment by mat007** [comment]
No worries, thanks anyway!

> I run it as an admin user.
That’s useful information as #10881 was experienced by users running as non-admin.

You were seeing the same stacktrace as the OP, right?

**Comment by lexuzieel** [comment]
> 
> 
> What does this powershell command output
> 
> ```
> .\icacls.exe 'C:\Program Files\Docker\Docker\resources\docker.exe'
> ```
> 
> ?

```
PS C:\Windows\system32> icacls.exe 'C:\Program Files\Docker\Docker\resources\docker.exe'
C:\Program Files\Docker\Docker\resources\docker.exe: The system cannot find the file specified.
Successfully processed 0 files; Failed processing 1 files
```

Checking the folder I don't see `docker.exe` there.

Checking the `docker` script file instead results in:

```
PS C:\Windows\system32> icacls.exe 'C:\Program Files\Docker\Docker\resources\docker'
C:\Program Files\Docker\Docker\resources\docker NT AUTHORITY\SYSTEM:(I)(F)
                                                BUILTIN\Administrators:(I)(F)
                                                BUILTIN\Users:(I)(RX)
                                                APPLICATION PACKAGE AUTHORITY\ALL APPLICATION PACKAGES:(I)(RX)
                                                APPLICATION PACKAGE AUTHORITY\ALL RESTRICTED APPLICATION PACKAGES:(I)(RX)

Successfully processed 1 files; Failed processing 0 files
```

I managed to solve the issue by removing & installing docker 3.3.1 using the installer from the site.

**Comment by mat007** [comment]
> Checking the folder I don't see docker.exe there.

It’s in the `bin` sub-folder: `icacls.exe C:\Program Files\Docker\Docker\resources\bin\docker.exe`.

> I managed to solve the issue by removing & installing docker 3.3.1 using the installer from the site.

OK fair enough, this should fix the file permissions indeed.

**Comment by mat007** [comment]
@lexuzieel are you running Docker Desktop with an admin or non-admin user?

**Comment by lexuzieel** [comment]
> 
> 
> @lexuzieel are you running Docker Desktop with an admin or non-admin user?

I believe as an admin. In the task manager it is run under my profile & my profile is in `Administrator` and `docker-users` groups.
