### ISSUE TITLE
Exposing a service as Loadbalancer or NodePort does not work if SessionAffinity is configured

### ISSUE THREAD

**Issue by KDSBest** [docker/for-win#10952]
As requested in https://github.com/kubernetes/kubernetes/issues/95484#issuecomment-707284974 (comment) I'll open this.

#What happened:
On Docker for Windows with activated Kubernetes I defined a deployment with a replica set of 5 and a matching service of type LoadBalancer (or NodePort). The service configures a SessionAffinity.
Curl fails with curl: (52) Empty reply from server

Same as this issue, but it got closed due to inactivity.
This still is an issue:

https://github.com/docker/for-win/issues/9028

Please reopen the initial issue. I have the same issue.

**Comment by stephen-turner** [comment]
As I said on the original ticket, I believe this is a Kubernetes issue not a Docker issue.
