### ISSUE TITLE
Unable to open the daemon.json config file (Access Denied)

### ISSUE THREAD

**Issue by metu** [docker/for-win#1095]
### Expected behavior
Able to open and edit the daemon.json config file.
### Actual behavior
'Access is denied' error is thrown when trying to open the file in notepad/ notepad++/ Code Writer/ (any text editor) while having the text editors opened as Administrator.
### Information
My first time trying to use docker.

I'm trying to change the directory where the container images are saved to by editing the daemon.json file as specified in the https://docs.docker.com/engine/admin/#configure-the-docker-daemon link.

### Steps to reproduce the behavior

Enable Windows feature 'Containers'
Restart
Install Docker for windows (v17.06.2-ce)
Navigate to the daemon.json file (C:\ProgramData\Docker\config)
Try opening the file.

[log.txt](https://github.com/docker/for-win/files/1303279/log.txt)

**Comment by ebriney** [comment]
Thanks @metu for the feedback. You must use the settings menu -> daemon -> advanced to do that.
We have change that in the next version and you will be able to edit it directly.

**Comment by metu** [comment]
Thanks @ebriney for the prompt response!

**Comment by vikmn** [comment]
I still get this issue with docker-17.10.0-ce. Also tried doing it throught the settings menu -> daemon --> advanced and still get the same error. I have also tried manually editing the file too but any changes to the json file are being wiped out.

**Comment by metu** [comment]
mmmhhh... @vikmn Editing the file through the settings interface worked for me. However I think I may have altered the security of the file by changing the ownership of the file to my user as well, by right clicking on the file and selecting Properties and then selecting the Security tab and then Advanced (Properties -> Security -> Advanced). I then clicked on Change next to the Owner title and proceeded to enter my username.

![image](https://user-images.githubusercontent.com/3936159/32275251-3264c2c2-bf13-11e7-989f-5609e72976d1.png)

**Comment by vikmn** [comment]
Thanks @metu. Your suggestion above helped .However in addition to that i also had to give the local admin group which i am part of permissions on the folder.

**Comment by jorisscheppers** [comment]
I had to take ownership of the file and enable permission inheritance to be able to edit the file, both with the Docker GUI and external tools.
