### ISSUE TITLE
Kubernetes Cluster Crash - Rook installation

### ISSUE THREAD

**Issue by chrispduck** [docker/for-win#10967]
### Overview
I tried to install the kubernetes package [rook-ceph](https://github.com/rook/rook/tree/release-1.6) to enable the use of persistent volume storage within my Kubernetes Cluster. 
The Docker for Desktop Kubernetes cluster ceases to function after applying rook-ceph yaml files, with basic kubernetes commands such as ` kubectl get pods ` timing out or returning internal errors (see below). 

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C81EE779-F7B6-4878-B10F-49C9F8B9E747/20210419154605

### Actual behaviour
After applying the appropriate rook-ceph YAML files, the kubectl command stopped working
```
$ kubectl get pods
Unable to connect to the server: net/http: TLS handshake timeout
```

this later turned into
```
$ kubectl get pods 
Error from server (InternalError): an error on the server ("") has prevented the request from succeeding
```

However, the docker command `docker ps` outputs as normal.
### Expected behaviour
Even if the yaml files are bad, the launched pods should crash rather than docker.

### Information
 The problem has also been reproduced on both the Windows setup below, and a version of Docker for Desktop Mac 
  - Windows Version: Windows 10 Enterprise, version: 20H2
  - Docker Desktop Version: v20.10.5
  - WSL2 or Hyper-V backend?  HyperV (WSL 1) 
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

Note: the Mac error produced
```
Fatal Error
Docker daemon failed to start
2021-04-19T14:58:51Z dockerd time="2021-04-19T14:58:51.349982263Z" level=warning msg="Falling back to default propagation for bind source in daemon root" container=dddc0da7a1f740a2bb4976ab717dab9b0c38323b99660b382af5fd10159222c2 source=/
```

### Steps to reproduce the behaviour
  1. kubectl apply -f https://raw.githubusercontent.com/rook/rook/v1.6.0/cluster/examples/kubernetes/ceph/crds.yaml -f https://raw.githubusercontent.com/rook/rook/v1.6.0/cluster/examples/kubernetes/ceph/common.yaml -f https://raw.githubusercontent.com/rook/rook/v1.6.0/cluster/examples/kubernetes/ceph/operator.yaml

  2. kubectl apply -f https://raw.githubusercontent.com/rook/rook/v1.6.0/cluster/examples/kubernetes/ceph/cluster-test.yaml

**Comment by djmcgreal-cc** [comment]
The version of Docker for Mac affected was as below. Whilst broken, I couldn't get docker.app itself to stay open for long, it would crash with different _Fatal error_s. I'm afraid I only captured one of them:
> 2021-04-19T14:58:51Z dockerd time="2021-04-19T14:58:51.349982263Z" level=warning msg="Falling back to default propagation for bind source in daemon root" container=dddc0da7a1f740a2bb4976ab717dab9b0c38323b99660b382af5fd10159222c2 source=/

I couldn't get a Diagnostics output, as the swirly went on swirling indefinitiely.

![Screenshot 2021-04-20 at 11 09 46](https://user-images.githubusercontent.com/49211421/115378870-eb692600-a1c8-11eb-99dd-605500afd870.png)
