### ISSUE TITLE
Docker desktop installed but not running

### ISSUE THREAD

**Issue by xxl4tomxu98** [docker/for-win#10969]
- [x ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 12C25E7C-C7F3-4C34-BFEF-0C24BA0187EC/20210419174555

### Information

  - Windows Version: 1909
  - Docker Desktop Version: 3.3.1
  - WSL2 or Hyper-V backend?   WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: onedrive?

### Steps to reproduce the behavior

  1. docker is installed and not running

**Comment by carlos-vicente** [comment]
Also have this issue with version 3.3.0 and 3.3.1

**Comment by abrueck** [comment]
Sounds like it's the same problem as #10958

**Comment by AssadIKhan** [comment]
Still Facing issue 
It looks like there is an error with Docker Desktop, restart it to fix it
