### ISSUE TITLE
Docker Won't Start and Settings Page Doesn't Open

### ISSUE THREAD

**Issue by nheminger** [docker/for-win#10978]
- [ X] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Restart computer, open docker GUI. Click settings, loading animation spins and nothing opens.
### Expected behavior
Able to view settings page.
### Information

  - Windows Version: Windows 10 Enterprise
  - Docker Desktop Version: 3.3.1
  - WSL2 or Hyper-V backend?  Not sure, I can't open settings to check what it is in.
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by rbalaine** [comment]
Hello,

Please read the existing issues before opening a new one, this bug have been reported several times already... https://github.com/docker/for-win/issues/10958
https://github.com/docker/for-win/issues/10941

You can "Clean / Purge data" for WSL2 or Hyper-V to fix it

**Comment by nheminger** [comment]
Thanks @rbalaine , I missed those. The clean / purge allowed me to see the page again and Docker is running again.
