### ISSUE TITLE
"vpnkit socket connections keep growing". netstat -ano shows vpnkit does not close socket connections to a container ActiveMQ after windows client process exits

### ISSUE THREAD

**Issue by SteveShell** [docker/for-win#10981]
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: DA7E9AC2-3176-4185-A51A-00CCE01FE57A/20210420162439

### Actual behavior
12100 is vpnkit
12780 is Docker Desktop Backend
61616 is ActiveMQ port running in Docker Container.

  TCP    192.168.0.21:56635     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:56636     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:56789     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:56791     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:56792     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:56799     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:56800     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:56831     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:56949     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57026     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57112     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57116     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57119     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57125     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57129     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57132     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57134     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57140     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57146     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57171     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57191     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57223     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57247     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57257     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57293     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57298     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57317     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57350     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57377     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57418     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57434     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57467     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57493     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57508     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57620     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57631     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57640     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57689     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57705     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57726     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57731     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57736     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57806     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57887     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:57993     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:58094     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:58195     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:58345     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:58408     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:58467     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:58608     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:58709     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:58803     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:58905     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:59008     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:59119     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:59218     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:59321     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:59414     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:59516     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:59649     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:59706     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:59802     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:59905     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:60012     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:60101     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:60207     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:60319     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:60414     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:61616     192.168.0.21:56635     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:56636     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:56789     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:56791     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:56792     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:56799     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:56800     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:56831     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:56949     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57026     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57112     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57116     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57119     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57125     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57129     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57132     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57134     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57140     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57146     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57171     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57191     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57223     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57247     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57257     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57293     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57298     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57317     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57350     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57377     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57418     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57434     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57467     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57493     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57508     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57620     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57631     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57640     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57689     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57705     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57726     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57731     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57736     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57806     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57887     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:57993     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:58094     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:58195     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:58345     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:58408     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:58467     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:58608     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:58709     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:58803     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:58905     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:59008     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:59119     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:59218     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:59321     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:59414     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:59516     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:59649     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:59706     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:59802     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:59905     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:60012     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:60101     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:60207     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:60319     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:60414     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:61770     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:61864     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:61958     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:62050     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:62108     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:62168     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:62245     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:62305     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:62363     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:62418     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:62419     TIME_WAIT       0
  TCP    192.168.0.21:61616     192.168.0.21:62475     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:62477     TIME_WAIT       0
  TCP    192.168.0.21:61616     192.168.0.21:62530     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:62586     ESTABLISHED     12780
  TCP    192.168.0.21:61616     192.168.0.21:62587     ESTABLISHED     12780
  TCP    192.168.0.21:61770     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:61864     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:61958     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:62050     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:62108     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:62168     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:62245     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:62305     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:62363     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:62418     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:62475     192.168.0.21:61616     ESTABLISHED     12100
  TCP    192.168.0.21:62530     192.168.0.21:61616     ESTABLISHED     12100

Stopping the Containers goes to TIME_WAIT

netstat -ano | grep 616
  TCP    127.0.0.1:56456        127.0.0.1:63616        TIME_WAIT       0
  TCP    192.168.0.21:56635     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:56636     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:56789     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:56791     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:56792     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:56799     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:56831     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:56949     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57026     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57112     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57116     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57119     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57125     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57129     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57132     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57134     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57140     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57146     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57171     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57191     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57223     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57247     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57257     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57293     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57298     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57317     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57350     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57377     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57418     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57434     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57467     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57493     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57508     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57620     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57631     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57640     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57689     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57705     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57726     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57731     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57736     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57806     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57887     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:57993     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:58094     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:58195     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:58345     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:58408     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:58467     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:58608     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:58709     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:58803     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:58905     192.168.0.21:61616     TIME_WAIT       0
  TCP    192.168.0.21:59008     192.168.0.21:61616     TIME_WAIT       0
  
  Quit Docker Desktop, vpnkit exits, all connections are cleaned up.
  
### Expected behavior
Socket connections should be closed when the client windows side client exits.

### Information

  - Windows Version:
    -- Windows 10 Pro
    -- 20H2
    -- 4/‎15/‎2021
    -- 19042.928
  - Docker Desktop Version:  3.3.1  (63152)
  - WSL2 or Hyper-V backend?    Hyper-V or WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:  No, Native Windows OS

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
Thanks for the report, we'll have a look. How are you launching the containers: with a compose file?

**Comment by stephen-turner** [comment]
Could be the same as https://github.com/docker/for-mac/issues/5611

**Comment by djs55** [comment]
@SteveShell thanks for your report. I can reproduce something similar locally where the TCP connection is only half-closed when the process on the host exits. This leaves the process in the container still connected, believing it can still write. I've added a ticket to our backlog.
