### ISSUE TITLE
Docker version upgradation to 3.3.1 stuck

### ISSUE THREAD

**Issue by prayagsingh** [docker/for-win#10982]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
I got a notification to update the Docker Desktop to the latest version and then I restarted it to proceed with updates but It stuck when doing the **Deploying component: Create docker-users group** operation for 2 hours and I had to forcefully stop it using Task Manager. Now the current scenario is I'm unable to install any of the previous versions also. I tried `3.3.0`, `3.2.2` and the result is same i.e stuck at the same point. 

### Expected behavior
It is supposed to update the docker desktop version successfully.

### Information

  - Windows Version: `Edition: Windows 10 Pro for Workstations, Version: 20H2, OS build: 19042.870`
  - Docker Desktop Version: 3.3.1
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Update the Docker Desktop version to the latest version.
  2. Please find below the SS. 
  
![Screenshot (622)](https://user-images.githubusercontent.com/8455114/115443449-e8098500-a230-11eb-9613-a3717aa2051f.png)

Result of command `icacls.exe 'C:\Program Files\Docker\Docker\resources\bin\docker.exe'`
```
 BUILTIN\Administrators:(I)(F)
                                                        BUILTIN\Users:(I)(RX)
                                                        APPLICATION PACKAGE AUTHORITY\ALL APPLICATION PACKAGES:(I)(RX)
                                                        APPLICATION PACKAGE AUTHORITY\ALL RESTRICTED APP PACKAGES:(I)(RX)

Successfully processed 1 files; Failed processing 0 files
```

**Comment by prayagsingh** [comment]
I tried `3.21`, `3.2.0` also the result is the same. hung at the same stage.

**Comment by prayagsingh** [comment]
Restarting the machine worked for me.

**Comment by stephen-turner** [comment]
So are you unstuck now? Shall I close the ticket?

**Comment by prayagsingh** [comment]
@stephen-turner sorry, I forgot to close it earlier.
