### ISSUE TITLE
Unable to upgrade docker

### ISSUE THREAD

**Issue by pradeepram80** [docker/for-win#10984]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Unable to install Docker 3.2.2. I get the error attached
![image](https://user-images.githubusercontent.com/10824237/115452142-4ad03180-a1db-11eb-8bbe-b61553894045.png)
Previously I tried uninstalling an older version by removing docker from windows add/remove program features. The uninstallation freezes after running for hours and still shows up as installed

### Information

  - Windows Version: Windows 10
  - Docker Desktop Version: 3.2.2
  - WSL2 or Hyper-V backend?  Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: VM

### Steps to reproduce the behavior

  1. Downloaded windows installer for Docker from the website
  2. Run the installer throws the error shown above

**Comment by pradeepram80** [comment]
I changed the windows registry folder : 
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall

as mentioned in this issue : https://github.com/docker/for-win/issues/1371

This resulted in further progress in installation of Docker than before. However, it ended with the following failure:
![image](https://user-images.githubusercontent.com/10824237/115456371-52dea000-a1e0-11eb-8197-402670d51c7f.png)

My C:\Program Files\Docker folder is still empty. And when I try to uninstall, it now shows two versions of Docker:
![image](https://user-images.githubusercontent.com/10824237/115456540-81f51180-a1e0-11eb-823d-67eb4b10ace3.png)

First one is version 3.2.2 and the next is 3.3.1

Any help is appreciated!

**Comment by xiaojiaohu** [comment]
![微信图片_20210421100308](https://user-images.githubusercontent.com/31126493/115486225-ca680a00-a288-11eb-977e-7298ecc7b4b6.png)
i have the same question。
my docker can not start ,so i update,but dont't work

**Comment by wouterpotters** [comment]
same issue here (win10)
