### ISSUE TITLE
VpnKitBridge still waiting 

### ISSUE THREAD

**Issue by tmumford** [docker/for-win#10997]
- [ x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: D3175FF0-9AC1-4E1A-AAC1-BDA09AAC59FC/20210421193207

### Actual behavior
The log.txt is filling with same 2 lines:

[13:34:33.448][VpnKitBridge      ][Info   ] msg="windows: still waiting for transfused, http-proxy-control, filesystem-event, filesystem-test after 5m50.0012712s"
[13:34:33.448][VpnKitBridge      ][Info   ] msg="guest: still waiting for ssh-auth, osxfs-data after 5m50.0020342s"

### Expected behavior
Hoping not to have the log fill with these messages.

### Information

  - Windows Version: Win 10 Pro 18363
  - Docker Desktop Version: 3.3.1
  - WSL2 or Hyper-V backend?   WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Steps to reproduce the behavior

  1. I am able to reproduce on a factory default installation.
  2. Once the engine is started the lines in the log get written.

**Comment by stephen-turner** [comment]
@tmumford Thanks for the report. Coincidentally we made an internal fix for this yesterday, so it will be in the next version.

**Comment by lppsuixn** [comment]
hi,when the next version relsese?

**Comment by tmumford** [comment]
It looks like Version: 3.3.2 resolves this issue. Thank you!
