### ISSUE TITLE
All images/containers keep disappearing and settings screen hangs - daily

### ISSUE THREAD

**Issue by mike-loux-planview** [docker/for-win#10994]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 8B30576A-13C5-474A-9A0A-B49518A89ACD/20210421140630

### Actual behavior

My images and containers have been disappearing daily after a reboot (I shut my system down at night).
Going into the settings screen hangs with the endless spinning cursor.
I have had to rebuild them from scratch every day since updating to 3.3.0 and beyond, often after reinstalling or purging data.

### Expected behavior
Images and containers should still be present after a reboot.
Settings screen should not hang. 

### Information

  - Windows Version: Windows 10 Version 1909 (OS Build 18363.1440)
  - Docker Desktop Version: 3.3.1
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Install Docker Desktop.
  2. Build a bunch O'containers and images
  3. Log off for the night
  4. Power on in the morning
  5. Bunch O'containers and images are gone.
  6. Attempt to go into settings.  
  7. Watch the spinny cursor for several seconds.
  8. Pound keyboard in frustration.
  9. Contemplate murder.

**Comment by mike-loux-planview** [comment]
Additional info when I tried doing `docker service ls` from my PS 7 session:
```PowerShell
error during connect: This error may indicate that the docker daemon is not running.: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/services?status=true: open //./pipe/docker_engine: The system cannot find the file specified.
```

**Comment by yos10** [comment]
I have the same problem. I'm not sure if it will work for you but this works for me.

1. Quit Docker Desktop.
2. Open Git Bash or terminal app you are using then type ```wsl --shutdown```
3. Restart Docker Desktop.

**Comment by abrueck** [comment]
Seems to be the same problem as #10958

**Comment by mike-loux-planview** [comment]
> I have the same problem. I'm not sure if it will work for you but this works for me.
> 
> 1. Quit Docker Desktop.
> 2. Open Git Bash or terminal app you are using then type `wsl --shutdown`
> 3. Restart Docker Desktop.

Tried that.  Didn't do anything, sadly.

**Comment by mike-loux-planview** [comment]
> Seems to be the same problem as #10958

Not quite.  In the case of that issue, restarting the service/app fixed the problem for them.  In my case, it does not.  I have to purge my data (and then, of course, reinstall my images and containers from scratch, which...not to put too fine a point on it...sucks).

**Comment by mike-loux-planview** [comment]
Well, I did a complete factory reset the other day, because I found myself needing to do some docker things, and then installed the latest and greatest version (3.5.2), and the problem seems to have...gone away.  That's always fun.  
So, yeah, I guess I will close this, but...I'm not really feeling a warm fuzzy about it basically being ignored.  Oh wellsies.
