### ISSUE TITLE
Docker fails to start

### ISSUE THREAD

**Issue by theangrydev** [docker/for-win#1099]
### Expected behavior
Docker starts

### Actual behavior
Docker fails to start:

```
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID 0E891202-3007-4991-B315-FAA72C4558B1)
at Start-MobyLinuxVM, <No file>: line 291
at <ScriptBlock>, <No file>: line 386
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 247
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 123
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
```

### Information
  - Diagnostic ID: 66FA77E5-5210-4C68-B85D-056DE9570D16/2017-09-17_12-16-07
  - Operating System: Windows 10 Pro Version 10.0.15063 Build 15063
  - Docker Version: 17.06.2-ce-win27 (13194) Channel: stable 428bd6c
  - Hyper-V is enabled
  - I followed the suggestions in https://github.com/docker/for-win/issues/27 but they did not fix the issue for me

### Steps to reproduce the behavior

  1. Install docker
  2. Wait for the tray icon to fail

**Comment by jasonbivins** [comment]
Hi @theangrydev 
Can you take a look at your hosts file? There are a lot of strange entries there according to our log.

Can you also open up Hyper-V manager - and see if you can both start and connect to any other VM's listed there?

**Comment by theangrydev** [comment]
The host file entries are for ad blocking and blocking known malware sites. I will try with a clean host file and see what happens.

In Hyper-V manager I do not have any other VM listed there to start.

**Comment by theangrydev** [comment]
Here is a new Diagnostic ID where I had a clean host file: 66FA77E5-5210-4C68-B85D-056DE9570D16/2017-09-19_21-07-14

**Comment by theangrydev** [comment]
I tried starting a http://www.damnsmalllinux.org/ ISO and I got similar behavior. I have a https://www.asus.com/uk/Motherboards/Z97A/  and according to the manual http://dlcdnet.asus.com/pub/ASUS/mb/LGA1150/Z97-A/E9378_Z97-A_UG_V2_WEB.pdf I have "Execute Disable Bit" and "Intel Virtualization Technology" both enabled in the BIOS.

**Comment by friism** [comment]
If you cannot start normal Hyper-V VMs neither then you'd want to get that sorted first...

**Comment by theangrydev** [comment]
@friism sure, this issue still serves as useful documentation for other people that undoubtedly will encounter the same root cause over time and arrive here e.g. via a search engine. I will update this if I find a fix.

**Comment by koppor** [comment]
It happened here after upgrading to the latest version today. Before the update, everything was fine. Diagnostic id: ADA85CF0-3345-4B7B-B586-9B7F39F95C3B/2018-01-09_15-52-12

**Comment by theangrydev** [comment]
For me the issue is definitely to do with Hyper-V, I have still not been able to get any Hyper-V VM working and am starting to suspect a motherboard issue.

**Comment by koppor** [comment]
@theangrydev On two machines, it stopped working. With a Docker update (Version 17.12.0-ce-win47 (15139), 9c692cd), on one machine, it worked again. Now, I only have one broken machine. Thus, I don't think, it's the motherboard. 😇

**Comment by koppor** [comment]
@theangrydev In the second machine, I installed "Docker edge", currently Docker version 18.01.0-ce, build 03596f5. With the hint of https://github.com/docker/for-win/issues/67#issuecomment-245837060, I got it to work there, too. So, maybe, this could also be an option for you and this issue can be closed?

**Comment by koppor** [comment]
Now, it stopped working. I get following output. I cannot find `Paths.cs` to dive into which Path is not accessible.  Diagnostic id `ADA85CF0-3345-4B7B-B586-9B7F39F95C3B/2018-01-23_09-16-39`.

```
Der Dateiname konnte durch das System nicht zugeordnet werden.

   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   bei Docker.Core.Paths.get_TmpD4W() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\Paths.cs:Zeile 21.
   bei Docker.Core.Paths.get_BackendInfoFile() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\Paths.cs:Zeile 47.
   bei Docker.Backend.BackendInfo.Load() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\BackendInfo.cs:Zeile 38.
   bei Docker.Backend.Features.Installer.CheckInstalledFeatures(Feature[] features) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\Features\Installer.cs:Zeile 32.
   bei Docker.Backend.ContainerEngine.Linux.CheckInstallation() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:Zeile 326.
   bei Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:Zeile 130.
   bei Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:Zeile 47.
   bei Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:Zeile 145.
```

**Comment by koppor** [comment]
OK, one more update. No correlation to Office 2016 installation. I uninstalled docker and used [chocolatey](http://chocolatey.org/) to install docker 17.09.0.13620. Right after the installation, everything works. In case, I encounter issues, I will comment again.

    choco install docker-for-windows --version 17.09.0.13620
    choco pin add -n docker-for-windows

**Comment by theangrydev** [comment]
I just used the "Switch to Windows containers..." button in Version 17.12.0-ce-win47 (15139) and was able to docker run hello-world successfully.

**Comment by dmarkhas** [comment]
FYI same issue on 18.03.1-ce-win65; without checking "Use Windows Containers" in the installation step, it fails on Windows 10.
