### ISSUE TITLE
"docker pull" fails in windows 10

### ISSUE THREAD

**Issue by stickybit1754** [docker/for-win#1100]
### Expected behavior

`docker pull ubuntu` 

### Actual behavior

while running docker pull, I'm getting the following error. 
```
PS C:\Users\nik> .\docker.exe pull ubuntu
Using default tag: latest
latest: Pulling from library/ubuntu
no matching manifest for windows/amd64 in the manifest list entries
```

I can however pull `hello-world` successfully. 

### Information

```

PS C:\Users\nik> docker version
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:57:19 2017
 OS/Arch:      windows/amd64

Server:
 Version:      master-dockerproject-2017-09-16
 API version:  1.32 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   c5c0702
 Built:        Sat Sep 16 23:52:06 2017
 OS/Arch:      windows/amd64
 Experimental: false
PS C:\Users\nik>

```

```
PS C:\Users\nik> docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 2
Server Version: master-dockerproject-2017-09-16
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 16281 (16281.1000.amd64fre.rs3_release.170829-1438)
Operating System: Windows 10 Pro Insider Preview
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 15.86GiB
Name: NIK
ID: I6I2:5C2W:ROAR:3J5Y:445D:XY2V:7MIR:C5K4:5F62:W54E:DCKI:2I6T
Docker Root Dir: C:\lcow
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 17
 System Time: 2017-09-17T16:31:00.0714441-08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### from docker daemon :
```
DEBU[2017-09-17T16:33:14.337154100-08:00] Calling POST /v1.32/images/create?fromImage=ubuntu&tag=latest
DEBU[2017-09-17T16:33:14.338122300-08:00] Trying to pull ubuntu from https://registry-1.docker.io v2
DEBU[2017-09-17T16:33:15.492984800-08:00] Pulling ref from V2 registry: ubuntu:latest
DEBU[2017-09-17T16:33:15.492984800-08:00] docker.io/library/ubuntu:latest resolved to a manifestList object with 6 entries; looking for a os/arch match
DEBU[2017-09-17T16:33:15.496976500-08:00] no matching manifest for windows/amd64 in the manifest list entries
INFO[2017-09-17T16:33:15.515001900-08:00] Attempting next endpoint for pull after error: no matching manifest for windows/amd64 in the manifest list entries
```
### Steps to reproduce the behavior

Followed steps in the tutorial [here](https://tutorials.ubuntu.com/tutorial/tutorial-windows-ubuntu-hyperv-containers#0)

**Comment by jasonbivins** [comment]
Hi @stickybit1754 
can you try to pull alpine instead of ubuntu to see if you get better results?

**Comment by friism** [comment]
@stickybit1754 please follow the Docker tutorial here: https://blog.docker.com/2017/09/preview-linux-containers-on-windows/

In this case the problem is that step 9 requires adding the `--experimental` flag when starting `dockerd.exe`. I recommend you let the Canonical people aware of this omission.

**Comment by stickybit1754** [comment]
@friism Thank you - The `--experimental` flag did work! 🙏

**Comment by b4dnewz** [comment]
for me with experimental flag is not working:
```
docker pull mysql
Using default tag: latest
latest: Pulling from library/mysql
no matching manifest for windows/amd64 in the manifest list entries
```

**Comment by alexandrev** [comment]
Same issue as @b4dnewz. I've followed the instructions and add the --experimental but same outcome.

**Comment by AlekseyAndreev** [comment]
Hello,
I have similar issue with "docker pull rabbitmq"
Using default tag: latest
latest: Pulling from library/rabbitmq
no matching manifest for windows/amd64 in the manifest list entries

**Comment by b4dnewz** [comment]
hi @AlekseyAndreev in your case I think you should see [this](https://github.com/docker-library/rabbitmq/issues/198#issuecomment-332287428) issue on rabbitmq and change to a linux based OS (for now) I guess.

**Comment by nphmuller** [comment]
Also same issue over here. Maybe a problem with the latest version from the master branch?

### Version:
```
Client:
 Version:      master-dockerproject-2017-10-16
 API version:  1.34
 Go version:   go1.8.4
 Git commit:   1401d5d
 Built:        Mon Oct 16 23:47:51 2017
 OS/Arch:      windows/amd64

Server:
 Version:      master-dockerproject-2017-10-16
 API version:  1.34 (minimum version 1.24)
 Go version:   go1.8.4
 Git commit:   f2afa26
 Built:        Mon Oct 16 23:51:43 2017
 OS/Arch:      windows/amd64
 Experimental: true
```
### Info
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: master-dockerproject-2017-10-16
Storage Driver: windowsfilter (windows) lcow (linux)
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 15.89GiB
Name: EyeXS-ski
ID: JPSZ:4QC5:YWGB:IIVC:BDOI:LTGP:UEBV:XZ2P:GICB:D7ND:MI6R:WDUL
Docker Root Dir: C:\lcow
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 17
 System Time: 2017-10-17T22:02:46.0718009+02:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by cuckopl** [comment]
For me it was this
![image](https://user-images.githubusercontent.com/8525055/31989482-afa3a2d6-b972-11e7-8890-dc8a1cc9bc7a.png)

**Comment by thadG** [comment]
I had similar problems using docker on Windows10

The error was :
 ""Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Failed to create the virtual hard disk. The system failed to create 'C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx'.""

I removed docker from Windows and also found the file 'MobyLinuxVM.vhdx' located at 'C:\Users\Public Documents\Hyper-V\Virtual hard disks\ was corrupted.  It's memory size was 6,569,023KB. I deleted MobyLinuxVM.vhdx.  After reloading a Docker, I restarted the computer.

The restart reloaded  'MobyLinuxVM.vhdx' located at 'C:\Users\Public Documents\Hyper-V\Virtual hard disks\ and now it was only 4,096 KB now. This was a good sign.

I right clicked on the  'Docker for Windows' icon and ran it as an administrator, but I still had the same error. I restarted the computer again.  After the restart, Docker started to work again.

**Comment by ezaurum** [comment]
In my case, I just remove and reinstall. It works.

**Comment by htatjana** [comment]
Thanks @ezaurum, reinstalling worked for me too

**Comment by DemocracyDrops** [comment]
Same as cuckopl for me. Swapping to Linux containers did the trick

**Comment by MJBlack23** [comment]
@cuckopl's solution worked for me also.  Cheers!

**Comment by upardhi** [comment]
Swap to Linux container it will solve I used same trick.

**Comment by tudorift** [comment]
Sequence of steps that worked for me:
- quit docker
- deleted 
- 'C:\Users\Public Documents\Hyper-V\Virtual hard disks\MobyLinuxVM.vhdx
- restart windows
- start docker and reset configuration. (antivirus turned off - it was restricting access to hosts file) 
- checked "experimental " option
After that it worked fine with both windows and linux conatiners.
It may be over-provisioning since I am quite new on this .

**Comment by jgprogram** [comment]
Checking experimental option in docker deamon options resolved the problem.

![2018-08-29_12h09_58](https://user-images.githubusercontent.com/5750770/44781613-2c7a1b00-ab85-11e8-95f5-3e4fa5fadf21.png)

**Comment by edgnets** [comment]
I had the same issue and after try many of the tips on this page without success I figure out that I have to **run the windows command console as Administrator**!

**Comment by JVimes** [comment]
Reboot fixed the "no matching manifest" error for me.

**Comment by ahmedofali** [comment]
Sign out this worked for me

**Comment by SagarPatilOnGit** [comment]
@jgprogram  Thanks, this worked for me for pulling redis image on windows 10.

**Comment by lovezyg** [comment]
@jgprogram thank you very much，have a nice day!

**Comment by rax115** [comment]
Unable to find image 'hello-world:latest' locally
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: Get https://registry-1.docker.io/v2/library/hello-world/manifests/latest: unauthorized: incorrect username or password.




Once you log in successfully 


PS C:\WINDOWS\system32> docker login
Authenticating with existing credentials...
Stored credentials invalid or expired
Log in with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username (xxxxx@xxx.com): xxxx
Password:
Login Succeeded




PS C:\WINDOWS\system32> docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
1b930d010525: Pull complete
Digest: sha256:2557e3c07ed1e38f26e389462d03ed943586f744621577a99efb77324b0fe535
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/﻿

**Comment by ChiragMakkar13** [comment]
> Checking experimental option in docker deamon options resolved the problem.
> 
> ![2018-08-29_12h09_58](https://user-images.githubusercontent.com/5750770/44781613-2c7a1b00-ab85-11e8-95f5-3e4fa5fadf21.png)

Worked For ME

**Comment by jmslick** [comment]
.

**Comment by muriloao** [comment]
thansk @cuckopl 
works for me
