### ISSUE TITLE
Docker service will not start until you Clean/Purge data in Docker Desktop 3.3.0

### ISSUE THREAD

**Issue by wesleymusgrove** [docker/for-win#11002]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C1AE0BD3-60C0-4061-83DB-38D6CBA4AEB3/20210422130911

### Actual behavior
Docker does not start and cannot be restarted.  The "Restart" button on Docker Desktop is disabled.  When you click the cog wheel to go to the general settings view, there is an infinite spinner that never goes away, so you can't access any of the settings.  The only way I have been able to get past this and get Docker to start is by clicking the Bug button in the top menu bar, clicking "Clean/Purge data", and selecting all the checkboxes.  Immediately Docker starts up and Docker Desktop returns to normal behavior until the next time I restart my computer.

### Expected behavior
Docker would start normally without having to Clean/Purge data in Docker Desktop.

### Information
  - Windows Version:  Windows 10 Enterprise 20H2
  - Docker Desktop Version:  3.3.0
  - WSL2 or Hyper-V backend?  Happens on both
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:  No

### Steps to reproduce the behavior
1. Updated Docker Desktop from 2.5.1 to 3.3.0
2. Start Docker Desktop.
3. Docker service will not start.
4. Clean/Purge data through Docker Desktop's Troubleshoot view.
5. Docker service starts.
6. Docker Desktop returns to normal behavior.

### Screenshots ###
After opening Docker Desktop, Docker service is stopped and will not start:
![image](https://user-images.githubusercontent.com/1711791/115720314-94875c00-a342-11eb-9096-de53d470b6da.png)

Can't click "Restart":
![image](https://user-images.githubusercontent.com/1711791/115720253-833e4f80-a342-11eb-9b03-d3a9386181e5.png)

Infinite spinner on the settings page:
![image](https://user-images.githubusercontent.com/1711791/115720380-a23ce180-a342-11eb-814b-70c5ae0563aa.png)

Clean/Purge data allows Docker service to start:
![image](https://user-images.githubusercontent.com/1711791/115720434-b08afd80-a342-11eb-8776-a09c4adbf57d.png)

Docker service starts:
![image](https://user-images.githubusercontent.com/1711791/115720639-dfa16f00-a342-11eb-82f7-6be4a07c7079.png)

Docker service has been started and Docker Desktop runs normally after Clean/Purge data:
![image](https://user-images.githubusercontent.com/1711791/115720761-fa73e380-a342-11eb-8c84-af10666a4656.png)

**Comment by abrueck** [comment]
Seems to be the same problem as #10958

**Comment by okafor-chidimma** [comment]
The same issue with me. Please help

**Comment by okafor-chidimma** [comment]
> The same issue with me. Please help

I was able to resolve mine by signing out of my account in docker desktop GUI. I know this is not an ideal fix but that solved it for me. My docker start automatically now and my images and stopped containers are persisited.
