### ISSUE TITLE
After the recent Windows update Docker version 3.3.0 and 3.3.1 crashes on windows 

### ISSUE THREAD

**Issue by xdatanext** [docker/for-win#11012]
- [x ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

Docker crashes with the Error window with the following stack

System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\nabin\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: The parameter is incorrect.

 stderr: 
   at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\PR-15595\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 146
   at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__17.MoveNext() in C:\workspaces\PR-15595\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 169
--- End of stack trace from previous location where exception was thrown ---

### Information

  - Windows Version: Windows 10 Pro,  OS Build 21364.1, Windows 10 Feature Experience Pack 321.9601.0.3
  - Docker Desktop Version: 3.3.0 and 3.3.1 
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1.  Update windows to  Windows 10 Pro,  OS Build 21364.1, Windows 10 Feature Experience Pack 321.9601.0.3
  2. . Install Docker for Desktop 
  3. Run the Docker ..... upon login ...Fails everytime with the same message

**Comment by stephen-turner** [comment]
This error means that WSL 2 is not set up correctly. Presumably the Windows update broke it in some way. Try following Microsoft's instructions at https://aka.ms/wsl2-install to reinstall WSL 2.

**Comment by onomatopellan** [comment]
Build 21364 has as peculiarity the new GUI feature for WSL2. Some people are having problems so you can try [disabling GUI support](https://github.com/microsoft/WSL/issues/6839#issuecomment-824601356).

**Comment by xdatanext** [comment]
This fixed the issue. Thanks
