### ISSUE TITLE
Docker Desktop does not start

### ISSUE THREAD

**Issue by singhvi** [docker/for-win#11011]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Docker desktop does not start, including the daemon etc. I can only see the "dashboard" (for the UI).

### Expected behavior
Docker (and the daemon) should startup normally whenever the machine is restarted.

### Information
When I start (or restart) my laptop many times (and always off late) the docker desktop does not start. I cannot even open the setting page (the circular pointer keeps rotating for ever). The only way I can get docker to start up is to either click on the "clean/purge data" button or the "reset to factory defaults" button to get docker to startup again!

Using docker CLI I see the below error - 
> PS> docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.12
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:14:53 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true
error during connect: This error may indicate that the docker daemon is not running.: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version: open //./pipe/docker_engine: The system cannot find the file specified.

  - Windows Version: Windows 10
  - Docker Desktop Version: 3.3.1
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No. Running this locally.

### Steps to reproduce the behavior
Restarting the machine results in docker not starting!

Diagnostics ID: 203C8AEF-B430-4616-A7B7-ACBCCC55DBC5/20210422180324

**Comment by abrueck** [comment]
Seems to be the same problem as #10958
