### ISSUE TITLE
Docker crashing after a while of not using the program, might be an antivirus issue

### ISSUE THREAD

**Issue by VXsz** [docker/for-win#11010]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 2276138A-5C86-48E8-A4AA-4E436695502D/20210422174322

### Actual behavior
It just crashes with this log whenever I try to use it, I haven't launch it in about ~1 month or maybe less since I don't use it often. the front end works normally (the gui and such) but its red since the backend crashed or something

This might be a problem with an antivirus, Kaspersky, since some said it started to happen after installing it, something about firewalls so I'm not might quite sure, altho this can be totally not the case and something other caused it

And to add, the `distro` folder doesn't have any files inside, if that matters

### Expected behavior
Desktop docker launches normally

### Information

  - Windows Version: 20H2 (OS Build 19042.928)
  - Docker Desktop Version: V20.10.5
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Directly on my own machine

### Steps to reproduce the behavior

  1. Launching the program
  2. The WSL2 backend starts launching
  3. Crash report pops up

**Comment by stephen-turner** [comment]
It's quite likely a problem with the security software. Lots of security software either blocks the back end from starting, or blocks the communication between the front end and the back end. If you can, I would advise trying to turn security software off temporarily to test whether that makes the problem go away.
