### ISSUE TITLE
Installation forking infinitely

### ISSUE THREAD

**Issue by brostone51** [docker/for-win#1102]
### Expected behavior
The installation completes, either with error or succesfully.

### Actual behavior
The installation asks for permission to install, then starts 100s of processes visible in task manager that crash the system.

### Information
Attempting installation on Windows 10 Enterprise Version 10.0.14393 Build 14393

### Steps to reproduce the behavior
  1. Download the docker installer
  2. Start the installer
  3. Provide permission for it to execute
  4. Get fork bombed.

**Comment by brostone51** [comment]
Update: I was able to get the installer ran correctly after conferring with my company's IT department. It appeared that due to insufficient user permissions on my machine, the network was blocking access to some installers.

Leaving the issue open, as the installer should probably fail in this case rather than create processes.

**Comment by bobveznat** [comment]
This blew up my machine this morning as well. I'm sure that my corp policy was going to prevent the install but I wanted to try it anyway. Thankfully I found some powershell (Stop-Process -name "Docker for Windows Installer") to save myself from a power cycle (my IT policy is such that I cannot reboot my machine, I'd have no choice but to pull the power cord).

Anyway, the installer should fail better.
