### ISSUE TITLE
Unable to run GPU container on Windows Insider

### ISSUE THREAD

**Issue by Tyrubias** [docker/for-win#11024]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

When attempting to run the command `docker run --rm -it --gpus=all nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -gpu -benchmark`, I receive the following error:

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: requirement error: unsatisfied condition: cuda>=11.2, please update your driver to a newer version, or use an earlier cuda container: unknown.
```

### Expected behavior

I expect to reproduce the example [in the Docker Desktop WSL 2 backend documentation](https://docs.docker.com/docker-for-windows/wsl/).

### Information

  - Windows Version: `Insiders build 21364.1000`
  - Docker Desktop Version: `3.3.1`
  - WSL2 or Hyper-V backend?  **WSL2 backend**
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: **No**

### Steps to reproduce the behavior

  1. Install the latest Windows Insider dev build.
  2. Install the beta Nvidia driver.
  3. Install Docker Desktop v3.3.1
  4. Attempt to run the example (both in WSL2 and Powershell)

**Comment by onomatopellan** [comment]
Should be fixed in a future update. For a workaround see https://github.com/NVIDIA/nvidia-docker/issues/1409#issuecomment-778089784

**Comment by stephen-turner** [comment]
Thanks, @onomatopellan, I'll close this in favour of the Nvidia ticket.
