### ISSUE TITLE
Docker fails to start on windows 10 pro x64

### ISSUE THREAD

**Issue by devkev16** [docker/for-win#1103]
### Expected behavior

Docker starts

### Actual behavior

Docker fails to start

### Information

  - Diagnostic ID: E813ABAE-8ECA-4C08-8786-A682BC8CC817/2017-09-19_10-26-13

### Steps to reproduce the behavior

  1. Start docker

Further information: If you kill docker.service using task manager first and start docker afterwards everything works as expected.

OS version no.: 1607
Build: 14393.1715

Would be nice if one can fix this, after a few weeks it's getting annoying to kill docker.service first everytime before I can use docker :)

Feel free to request additional information!

**Comment by jasonbivins** [comment]
Hi @devkev16 
Do you have Docker set to start when Windows starts?

**Comment by devkev16** [comment]
Hi @jasonbivins, 

I tried both: to start docker with windows and to start docker separetely, both approaches fail.

**Comment by devkev16** [comment]
Hi,

today I've updated to 17.09.0-ce-win33 (13620) and the problem is fixed now. 

Thanks for your great work!
