### ISSUE TITLE
running inside a virtualized VMware Workstation

### ISSUE THREAD

**Issue by teamwebmaker** [docker/for-win#11031]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. running inside a virtualized VMware Workstation

**Comment by teamwebmaker** [comment]
![image](https://user-images.githubusercontent.com/47903952/115992697-134cf500-a5e0-11eb-9c62-f8431cf6ee30.png)

**Comment by stephen-turner** [comment]
Thank you for the report. Unfortunately Docker Desktop is not supported in a virtualised environment (see https://docs.docker.com/docker-for-windows/install/#whats-included-in-the-installer and https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-desktop-in-nested-virtualization-scenarios). It's out of our control whether it works or not: it depends whether the outer hypervisor can fully run Hyper-V or WSL 2. Sometimes enabling nested virtualisation in the outer hypervisor makes it work, but there are no guarantees.
