### ISSUE TITLE
Win Docker Desktop Version: 3.3.1 Failed to deploy distro docker-desktop to  C:\Users\...

### ISSUE THREAD

**Issue by rnwolf** [docker/for-win#11039]
- [ y] I have tried with the latest version of Docker Desktop
  - [ y] I have tried disabling enabled experimental features
  - [ y] I have uploaded Diagnostics
  - Diagnostics ID: 358724CB-78C8-4663-8B22-CA0ACC609EF5/20210426072141

### Actual behavior

Docker Desktop Error screen displayed.
Red docker-desktop icon in the windows overflow icons taskbar window.

### Expected behavior

Clean startup, no error screen, blue docker-desktop icon in the windows overflow icons taskbar window.

### Information

  - Is it reproducible? Yes
  - Is the problem new? Yes. Did update to Docker Desktop a few days ago.
  - Did the problem appear with an update? Yes

  - Windows Version: Version	10.0.19042 Build 19042
  - Docker Desktop Version: 3.3.1
  - Docker version 20.10.5, build 55c4c88
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Bootup computer
  2. Docker Error screen comes up after a couple of minutes

**Comment by andybak** [comment]
Maybe this is why the forced updates are a bad idea? For many of us "getting work done" is more important than "help Docker debug its releases"

**Comment by TimHess** [comment]
I have the same problem with same backend and versions of Windows/Docker. Uninstalling and reinstalling docker desktop from a fresh download did not work.

Diagnostics ID: 87C70356-7665-468C-BBDC-D3D49D020F46/20210427193811

**Comment by TimHess** [comment]
In my case, LxssManager got disabled somehow, which prevented WSL from working at all. I definitely didn't do that, so maybe some corporate group policy went wrong. In any case running this command got me up and running: `sc config LxssManager start=auto`

**Comment by rnwolf** [comment]
Here is another diagnostic ID: 358724CB-78C8-4663-8B22-CA0ACC609EF5/20210505062354
Hopefully it will help with trouble shooting.
