### ISSUE TITLE
docker desktop 3.3.1 can't start on window 10

### ISSUE THREAD

**Issue by onemoretime** [docker/for-win#11032]
- [X] I have tried with the latest version of Docker Desktop: v3.3.1
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 445B8E3A-62C5-4BFC-B263-550ABFCEF2E0/20210425102338

### Actual behavior
Docker Desktop failed to start, docker daemon unreachable, unable to access to settings (via dashboard), docker commandlines failed

### Information

  - Windows Version: 19041.928
  - Docker Desktop Version: 3.3.1
  - WSL2 or Hyper-V backend?:  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. restart service or restart host
  2. commandlines failed ("error during connect: This error may indicate that the docker daemon is not running.")

**Comment by mbgrabbe** [comment]
I'm having this same problem, and my specs are identical.  Docker 3.3.1 isnt working in windows10 and is also unavailable to WSL2, which breaks my local development process.  I found that uninstalling the latest version of docker and re-installing a prior release (I chose v3.2.0) solves the problem, but docker quickly upgrades itself and the problem starts over again.

**Comment by onemoretime** [comment]
Links for old versions (from https://docs.docker.com/docker-for-windows/release-notes/):

- v3.3.0: https://desktop.docker.com/win/stable/amd64/62916/Docker%20Desktop%20Installer.exe
- v3.2.0: https://desktop.docker.com/win/stable/amd64/61504/Docker%20Desktop%20Installer.exe

**Comment by chanan** [comment]
I have the same problem with 3.3.1, downgrading as @onemoretime suggested to 3.3.0 fixed my problem

**Comment by abrueck** [comment]
Seems to be the same like probleme #10958

**Comment by mattcobley** [comment]
Interestingly I have the same problem on 3.3.0. I have to reset to factory defaults to be able to use it at all. I have tried switching to Hyper-V from WSL2 after doing this, but on rebooting get the same problem again.

**Comment by rodneymandap** [comment]
I do have the same problem with 3.3.1. The only fix I know right now is to reset to defaults every time docker doesn't start after startup which is kinda annoying now since the images that I built are gone and I have to rebuild it again. Another workaround without losing build images, I end the process of the stopped Docker, and sometimes it works.

**Comment by onemoretime** [comment]
Solved with v3.3.3.
Thanks

**Comment by mattcobley** [comment]
I get the same issue with 3.3.3, sadly, so I'm still having to reset to factory defaults every time I start up.

**Comment by mbgrabbe** [comment]
@mattcobley , I noticed the same thing this morning.  @onemoretime , how about you?

**Comment by rodneymandap** [comment]
Mine works fine. 
![image](https://user-images.githubusercontent.com/16484186/117989772-2a753c00-b36f-11eb-987a-5f46a284f36a.png)

**Comment by onemoretime** [comment]
All is working again: downloaded last installer, installed over previous installation. I recovered all my containers and datas (images, volumes, ...)
