### ISSUE TITLE
Missing menu options after an upgrade

### ISSUE THREAD

**Issue by 09miller09** [docker/for-win#11047]
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID:
594A2E03-279F-4511-AB9E-62149224D717/20210426210333
### Actual behavior
Right click menu on tray icon only has two options, Dashboard and settings. Also I only have 3 options under the Resource setting selection. PROXIES, NETWORK, and WSL INTEGRATION. Also it no longer autostarts. 

### Expected behavior
The things mentioned above should work.

### Information

  - Windows Version:
  - Docker Desktop Version:3.3.1
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:No

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by 09miller09** [comment]
The only way I could get the deamon started is to issue a "DockerCli.exe -SwitchLinuxEngine" command. I have tried reinstalling and resetting settings to default and installing older versions, with no luck

**Comment by kevindragon** [comment]
> The only way I could get the deamon started is to issue a "DockerCli.exe -SwitchLinuxEngine" command. I have tried reinstalling and resetting settings to default and installing older versions, with no luck

So did I.

![image](https://user-images.githubusercontent.com/409478/116176657-14e3fd80-a745-11eb-93b3-3fd4f5603bda.png)

**Comment by stephen-turner** [comment]
We think there might be a race condition during startup between logging in and constructing the menu. Could you try running `docker logout` from the command line and then restarting Docker Desktop?

**Comment by SetTrend** [comment]
@stephen-turner:

That seems to work for me. I logged out (which closed Docker Desktop) and then started Docker Desktop again.

Does this perhaps shed some light on the situation?

**Comment by 09miller09** [comment]
Thanks for the response. That did restore the right click menu and the auto
start.

I think there may still be a problem as I seem to be missing the first
2(maybe 3) settings under the "Resources" section in Settings. (this is
after the fix)

i.e. I can't set the disk size used for images.
[image: image.png]

**Comment by stephen-turner** [comment]
@09miller09 If you are using WSL 2 or Windows containers, most of those resource limits are controlled by Windows not us. Our documentation lists which ones you should and shouldn't continue to see.

**Comment by stephen-turner** [comment]
Anyone who's suffering from this bug, if you want you can try this internal build. We hope it fixes it: https://desktop-stage.docker.com/win/stable/amd64/64468/Docker%20Desktop%20Installer.exe.

**Comment by mattcobley** [comment]
Thank you, running `docker logout ` worked for me.

**Comment by bevin0708** [comment]
`docker logout `worked

**Comment by bevin0708** [comment]
problem still exists. Happens a few times a week.
`docker logout` seems to be the workaround
