### ISSUE TITLE
Docker doesn't start - "Binary stream '0' does not contain a valid ..."

### ISSUE THREAD

**Issue by backlunddb2** [docker/for-win#1105]
### Expected behavior
start docker

### Actual behavior
docker doesn't start

### Information
A diagnostic was uploaded with id: 2C8B8575-3569-47BF-BEC4-4419143DD34B/2017-09-19_15-23-22
[log.txt](https://github.com/docker/for-win/files/1314475/log.txt)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jasonbivins** [comment]
Hi @backlunddb2 
Can you restart the Docker.for.Windows service - the error you're getting indicates that we cant connect to it.
