### ISSUE TITLE
Docker Desktop 3.3.1 missing snyk

### ISSUE THREAD

**Issue by henrickgoldwurm** [docker/for-win#11061]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 5AF835F3-A9B8-4575-972F-BD99E902D985/20210428143633

### Actual behavior
Running `docker scan --version` returns
> failed to get snyk version: could not find Snyk binary

### Expected behavior
`docker scan --version` should return the snyk version and `docker scan <image id>` should scan images for vulnerabilities

### Information

  - Windows Version: Windows 10 Pro Build 19042
  - Docker Desktop Version: 3.3.1
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Nope

I woke up to a new version of Docker Desktop, tried to scan my docker image, and ran into this error.

### Steps to reproduce the behavior

  1. Update to Docker Desktop 3.3.1
  2. Run `docker scan --version` in WSL2 (works in CMD/PS)
  3. Watch it fail :(

**Comment by stephen-turner** [comment]
Hmmm, that's strange, I'm running the same version and docker scan is working fine. Also we haven't had any other reports of it. I'm not sure what to suggest other than reinstalling it.

**Comment by henrickgoldwurm** [comment]
Oh, no! Now it just keeps crashing on startup. I uploaded the crash report and here is the ID: 5AF835F3-A9B8-4575-972F-BD99E902D985/20210428173039. I think this is similar to the other reports so feel free to mark this one as a duplicate now.

I'll just install the previous version for now.

**Comment by s-yurama** [comment]
it's crashing, too. 😢 

**note: when you did follow solution, you need re-build containers **
i could start docker for desktop after i used clean/purge data from trouble shooting section.

> you need re-build containers
**and this is important.**
if you get follow error while docker-compose up and building
```
failed to get console mode for stdout: The handle is invalid.
```
plz read, this is reported in https://github.com/docker/compose/issues/8186
then, i recommend you get downgraded version ( ex v3.0.x ) from
https://docs.docker.com/docker-for-windows/release-notes/

**Comment by henrickgoldwurm** [comment]
I tried rolling back to older version and I'm running into the same issue on pretty much every version. It works fine in Command Prompt, but `docker scan` fails on Ubuntu WSL2.

@stephen-turner Am I missing something I need to do for it to work in WSL2?

**Comment by MarkFarmiloe** [comment]
Hi,
I'm also using WSL2 and have v 3.3.1 of Docker Desktop.
From WSL bash prompt: 
`docker scan getting-started` lead to
Docker Scan relies upon access to Snyk, a third party provider, do you consent to proceed using Snyk? (y/N)
y
failed to get DockerScanID: bad status code "404 Not Found"

Apparently I wasn't logged in to docker.
Logged in then tried again and went straight to:
could not find Snyk binary

Can I manually install the synk binary?
Is the failure to get DockerScanID the problem?

**Comment by MarkFarmiloe** [comment]
Partial answer to my questions:
Ran `docker scan --reject-license` then `docker login` then `docker scan`
Got consent request again and answered y with no DockerScanID problem this time.
But `docker scan getting-started` still produces 'could not fin Snyk binary'.
So my first question still stands - is there a way to install the binary manually (if it is meant to be installed locally of course)?
