### ISSUE TITLE
docker upgrade wipes k8  

### ISSUE THREAD

**Issue by bklooste** [docker/for-win#11069]
When docker decides to upgrade ( id rather it didnt)  it often wipes/resets its kubernets cluster sometimes the checkbox is removed sometimes not but k8 containers have been deleted. 

This infuriating because it can take a significant amount of time to rebuild a local k8 environment  ( dashboard , metrics , istio etc etc) . Dashboard is especially painfull due to all the security.

  - [X ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

**Comment by stephen-turner** [comment]
We can't do anything about the Kubernetes upgrade process, but we no longer try and upgrade the Kubernetes cluster during a Docker Desktop upgrade. Instead we leave it at its old version, and let the user upgrade it when convenient.
