### ISSUE TITLE
Access is denied when opening a PSSession with localhost

### ISSUE THREAD

**Issue by rosberglinhares** [docker/for-win#1106]
### Expected behavior

Inside a container, `Enter-PSSession -ComputerName 'localhost'` should starts an interactive session with the container itself.

### Actual behavior

The following error message is shown:

>Enter-PSSession : Connecting to remote server _ContainerName_ failed with the following error message : Access is denied. For more information, see the about_Remote_Troubleshooting Help topic.

### Information

- The same command works if using the container IP:

>PS C:\> Enter-PSSession -ComputerName 172.21.230.45
>[172.21.230.45]: PS C:\Users\ContainerAdministrator\Documents>

- I have already tried connecting through a specific user, but the same error happens:

```powershell
docker run -d --name ContainerTest microsoft/iis
docker exec -it ContainerTest powershell
net user UserTest P@ssTest /ADD
net localgroup administrators UserTest /add
Set-Item 'WSMan:\localhost\Client\TrustedHosts' * -Force
$username = '172.30.95.69\UserTest'
$password = 'P@ssTest' | ConvertTo-SecureString -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential($username, $password)
Enter-PSSession -ComputerName '172.30.95.69' -Credential $credential
```

- I have also tried to set permissions for the session configuration, as said in the following link, but the error continues to happen:

https://blogs.technet.microsoft.com/heyscriptingguy/2010/11/18/use-powershell-to-set-security-permissions-for-remoting/

My environment is:

- Windows Server 2016 Datacenter Version 1607 (Build 14393.1593)
- Docker:
  - Client:
 Version:      17.09.0-ce-rc2
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   363a3e7
 Built:        Thu Sep 14 01:52:49 2017
 OS/Arch:      windows/amd64

  - Server:
 Version:      17.09.0-ce-rc2
 API version:  1.32 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   363a3e7
 Built:        Thu Sep 14 02:02:39 2017
 OS/Arch:      windows/amd64
 Experimental: true

### Steps to reproduce the behavior

`docker exec -it <ContainerName> powershell`
`Enter-PSSession -ComputerName 'localhost'`

**Comment by jasonbivins** [comment]
Hi @rosberglinhares 
Try ```docker.for.win.localhost``` - localhost doesn't translate through the NAT networks.

**Comment by rosberglinhares** [comment]
Hi @jasonbivins, thank you for anwsering,
Being more clear, I am inside a container and want to connect with the container itself using localhost instead of the IP.
I have a PowerShell DSC script that will be copied from the host to the container and executed there. This copy is being done when building the container image through a Dockerfile, so I can't force a static IP in this moment (I guess), and it would be great if I could put localhost in the deploy package (ConfigurationData.psd1 file).
Any idea? Thanks!
