### ISSUE TITLE
New install of Docker for Windows shows nothing under remote repositories

### ISSUE THREAD

**Issue by TitanArchon** [docker/for-win#11062]
- [ X] I have tried with the latest version of Docker Desktop
  - [X ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version: Server 2019
  - Docker Desktop Version: ?? Engine version is v20.10.5
  - WSL2 or Hyper-V backend?  No
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. ... Go to Images on the left hand side
  2. ... Select Remote Repositories
![Capture](https://user-images.githubusercontent.com/30101327/116432863-f0f0ec80-a816-11eb-80f9-53b9a43171fd.PNG)

**Comment by stephen-turner** [comment]
The remote repositories lists your own images on Hub. Do you have any? If you push an image to Hub, it should show up there.

**Comment by TitanArchon** [comment]
I must be expecting something incorrect. I think i figured it out by just using the up and installing via powershell. Im new to this so i was probably asking a derp question. I'll close it. Thanks Stephen for your willingness to help my friend.

**Comment by stephen-turner** [comment]
It wasn't a stupid question, the functionality you were expecting is a feature request that we have heard from other people, it's just not what that tab does at the moment.

**Comment by TitanArchon** [comment]
> It wasn't a stupid question, the functionality you were expecting is a feature request that we have heard from other people, it's just not what that tab does at the moment.

Well thank you very much. I do appreciate the kind words. I try to minimize me asking things like this because i get flamed haha. Everything is working perfectly and I am enjoying the software immensely on my home media server!
