### ISSUE TITLE
Trying to run Docker on a Windows 10 VM (i.e. in the cloud managed by my company).  How do I 'ensure virtualization is enabled in the BIOS" of a Windows 10 VM?

### ISSUE THREAD

**Issue by johntaylorpa** [docker/for-win#11079]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by johntaylorpa** [comment]
I installed a fresh copy of Docker (many times) and restarted my Windows 10 VM.  Docker fails to start with an error message of "System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\taylorjo\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.

For information please visit https://aka.ms/wsl2-install"

**Comment by stephen-turner** [comment]
Hi, have a look at https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-desktop-in-nested-virtualization-scenarios.
