### ISSUE TITLE
Docker uses a lot of CPU, even without any containers

### ISSUE THREAD

**Issue by Algorytm** [docker/for-win#11080]
- [x] I have tried with the latest version of Docker Desktop (I had)
  - [ ] I have tried disabling enabled experimental features
There is no possibility to enable experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4274DDB8-D3C7-43C9-AB28-C9F87803743A/20210429151051

### Actual behavior
Empty docker uses a lot of CPU, even without any containers and after the cleanup and fresh install (I have reinstalled WSL and docker)

### Expected behavior
Calm down docker please

### Information

  - Windows Version: 
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.21364 N/A Build 21364
  - Docker Desktop Version: 
  - 3.3.1
  - WSL2 or Hyper-V backend?  
  - WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:
  - No

### Steps to reproduce the behavior
Just run docker 

https://i.ibb.co/89YHSgh/docker-cpu.png

**Comment by therealdandecker** [comment]
Can we bump this? If I leave Docker running on WSL2 my CPU sits at 100% all day, on an i7. Even with a .wslconfig file to limit resources it’s still way more than running Docker Engine on Linux.
