### ISSUE TITLE
Add support for routing mesh

### ISSUE THREAD

**Issue by mariusin79** [docker/for-win#1109]
### Expected behavior

Not needing to specify --endpoint-mode dnsrr --mode=global and -published mode=host and the ability to use the --replicas switch

### Actual behavior

Does not work. the article https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/swarm-mode#publish-ports-for-service-endpoints states that the routing meash feature is "coming soon", can't seem to find any more info on it though.

**Comment by friism** [comment]
It's in the RS3 builds (16278) and you can use it with preview builds of Docker EE: https://download.docker.com/components/engine/windows-server/preview/docker-17.10.0-ee-preview-1.zip

**Comment by mariusin79** [comment]
Any news on when this will hit the Docker community edition? The absence of the routing mesh combined with our inability to trap SIGINT is making it difficult for us to create a smooth continuous deployment experience.

**Comment by friism** [comment]
Docker Community Edition is not supported - and shouldn't be used for production - on Windows Server. Unfortunately you'll be limited to testing this with the preview builds...

**Comment by friism** [comment]
@Vacant0mens we don't have a public timetable to share just yet.

We skipped 17.09 EE because we're working on a big release that includes Kubernetes: https://blog.docker.com/2017/10/kubernetes-docker-platform-and-moby-project/

You can read more about the preview releases here: https://docs.docker.com/engine/installation/windows/ee-preview/

**Comment by Vacant0mens** [comment]
Thanks @friism ! 
I'm pretty excited for the next couple versions to be released! 👍

**Comment by gaui** [comment]
Having the same problem with Windows Server 1709 and latest EE 18.01 TP.

```PS C:\ProgramData\docker\config> docker info | sls Vers
Server Version: 18.01.0-ee-1-tp5
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)```

**Comment by Vacant0mens** [comment]
@friism or @jasonbivins : I see this was changed to `status\4-fix-released-beta` 
what version was this change merged to?

**Comment by rofr** [comment]
@friism I installed the preview on an azure 1709 vm following the standard powershell installation method:
```
Install-Module DockerProvider
Install-Package Docker -ProviderName DockerProvider -RequiredVersion preview
```
docker info excerpt:
```
Server Version: 17.06.3-ee-1-tp6
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows Server Datacenter
```
I assume tp6 means technical preview but 17.06 doesn't support mesh routing ( according to https://docs.docker.com/install/windows/ee-preview/) so which version is required for mesh routing and can I obtain it?

**Comment by friism** [comment]
No, that's an error cc @carlfischer1 @johnstep

**Comment by rofr** [comment]
@friism thank you. What's an error? The documentation or the resulting installed version?

**Comment by rofr** [comment]
```
PS C:\Users\rofr> find-package docker -provider DockerProvider -allversions

Name                           Version          Source           Summary
----                           -------          ------           -------
Docker                         1.12.2-cs1       Docker           Contains the CS Docker Engine for use with Windows ...
Docker                         1.13.1-cs6       Docker           Docker for Windows Server 2016
Docker                         17.03.2-ee-6     Docker           Docker for Windows Server 2016
Docker                         17.03.0-ee       Docker           Contains Docker EE for use with Windows Server 2016...
Docker                         17.03.1-ee       Docker           Contains Docker EE for use with Windows Server 2016...
Docker                         17.06.2-ee-6     Docker           Docker for Windows Server 2016
Docker                         17.06.2-ee-6     Docker           Docker for Windows Server 2016
Docker                         17.06.2-ee-6     Docker           Docker for Windows Server 2016
Docker                         2.0.0-ee-1-tp6   Docker           Docker for Windows Server 2016
Docker                         17.06.2-ee-6     Docker           Docker for Windows Server 2016
Docker                         17.06.1-ee-1-rc4 Docker           Docker for Windows Server 2016
```

**Comment by rofr** [comment]
The 2.0.0-ee-1-tp6 package is the one installed but the version reported by docker is 17.06.3-ee-1-tp6

**Comment by gaui** [comment]
This EE Windows versioning is a total mess. There's no way to understand it and keep track of it.

**Comment by carlfischer1** [comment]
@rofr sorry for the confusion

`PS C:\> Install-Package docker -Provider DockerProvider -RequiredVersion preview`

should now result in the current EE Preview build being installed
```
PS C:\> docker version
Client:
 Version:      17.10.0-ee-preview-3
 API version:  1.33
 Go version:   go1.8.4
 Git commit:   1649af8
 Built:        Fri Oct  6 17:52:28 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.10.0-ee-preview-3
 API version:  1.34 (minimum version 1.24)
 Go version:   go1.8.4
 Git commit:   b8571fd
 Built:        Fri Oct  6 18:01:48 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

**Comment by Vacant0mens** [comment]
Is 17.10.0-ee-preview-3 the version that should be supporting mesh routing? And is it just for Windows Sever 1709? Or is it also available for standard Windows Server 2016 (core as well)?

**Comment by Vacant0mens** [comment]
What version of Docker for Windows will have Mesh Routing as officially supported?

**Comment by kkbruce** [comment]
Hi Sir

I look for this blog ( https://blogs.technet.microsoft.com/virtualization/2017/09/26/dockers-ingress-routing-mesh-available-with-windows-server-version-1709/ )

Can I just use Docker EE Preview version?
Have any plan for release Ingress mode to Docker EE release version?

I try Docker EE 18.03.1-ee-2 with Server Core 1803 hosts, but Ingress mode seem don’t work.

**Comment by kkbruce** [comment]
Hi guys, 

I have a good news from https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/824

>  Routing mesh and VIP service discovery are supported in Docker engine EE 18.03.1
