### ISSUE TITLE
Docker for Desktop in Windows 10 Home not starting up.

### ISSUE THREAD

**Issue by gansven** [docker/for-win#11099]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by gansven** [comment]
[log.txt](https://github.com/docker/for-win/files/6409559/log.txt)

**Comment by onomatopellan** [comment]
Can you open cmd and post the output of `wsl.exe -l -v` ?

**Comment by mrmadhat** [comment]
#10958
