### ISSUE TITLE
Crash on start after upgrading to 1.12.1-stable on Windows 10

### ISSUE THREAD

**Issue by alvesman** [docker/for-win#111]
### Information

log file
[log.txt](https://github.com/docker/for-win/files/500249/log.txt)

**Comment by dgageot** [comment]
Hi @alvesman Could you try to reset to factory defaults and see if it fixes the issue?

**Comment by dgageot** [comment]
In fact, I'm going to close this as a duplicate of https://github.com/docker/for-win/issues/81

**Comment by alvesman** [comment]
Yes, I've reseted to factory defaults. Same behavior.
Thanks, I'll keep watching [https://github.com/docker/for-win/issues/81](url)
