### ISSUE TITLE
Docker for Desktop in Windows 10 Pro not starting up

### ISSUE THREAD

**Issue by jhy871167495** [docker/for-win#11100]
[log.txt](https://github.com/docker/for-win/files/6409812/log.txt)

  - [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by abrueck** [comment]
Sounds like it's the same problem as #10958
