### ISSUE TITLE
Docker for windows linux containers takes very long time to execute

### ISSUE THREAD

**Issue by kpramesh2212** [docker/for-win#1111]
### Problem:
I created a DB2 11 database image using Docker for windows

The following is my Dockerfile

FROM ubuntu:16.04
RUN /data/db2/db2.sh

### db2.sh script
dpkg --add-architecture i386 && apt-get -y update && \
apt-get -y install binutils libaio1 libnuma1 file rpm libstdc++6 libpam0g libpam0g:i386 libstdc++6:i386 supervisor net-tools && apt clean all && \
/data/server/db2setup -r /data/db2/db2server.rsp && \
groupadd db2iadm1 && groupadd db2fadm1 && \
useradd -m -g db2iadm1 -p db2inst1 db2inst1 && useradd -m -g db2fadm1 -p db2fenc1 db2fenc1 && \
/opt/ibm/db2/V11.1/instance/db2icrt -s ese -u db2inst1 db2inst1 && \
/opt/ibm/db2/V11.1/adm/db2licm -a /data/db2/db211ese.lic && \
cp /data/supervisord.conf /etc/supervisor/ && \
cp /data/db2/db2.conf /etc/supervisor/conf.d/ && \
cp /data/db2/reconfig.sh /home/db2inst1/ && \
rm -rf /tmp/* /root/* && \
printf "done"

The image was created successfully

Then used this image to create a container and then create a database in docker for windows

docker run -idh database.com --privileged=true --name database database bash
Then inside the container 
when I run the 
su - db2inst1
db2 create db testdb  --> This takes very long time(more than 10mins) to execute and it either fails or hangs

However when the **same image** is transferred to a docker running on a Linux machine (Ubuntu or RHEL server)
When I run 
su - db2inst1
db2 create db testdb --> Takes less than one min to execute and it completes successfully

### Expected behavior
Same as how it works in linux 

### Actual behavior
Docker for Windows 10 takes long time to execute a db2 database create command and either hangs or fails 

### Information
Docker version: Docker for windows Stable build (downloaded on 21-SEP-2017)

Windows Edition:  Windows 10 Enterprise
Version: 1703
OS Build: 15063.608

### Steps to reproduce the behavior
Please read the problem description 

Please let me know if you need any-other information.

**Comment by friism** [comment]
Did you try assigning additional memory and CPUs to Docker for Windows? It's in advanced settings.

**Comment by kpramesh2212** [comment]
Hi 
Sorry for the delayed response
Yes in Windows i set the option to 8GB and 4 core processor in the advanced settings

But still the same problem.

Regards
Ramesh
