### ISSUE TITLE
How to quit Docker Desktop from command line or programatically?

### ISSUE THREAD

**Issue by chdw** [docker/for-win#11111]
I use Docker Desktop with WSL2 on Windows 10.
It works fine. And I can quit Docker Desktop by right click NotifyICon and click context menu  

But I want to quit it by command line or programatically.
How can I do this?

**Comment by LasseEnvall** [comment]
Powershell:

$isrunning = Get-Process "Docker Desktop" -ErrorAction SilentlyContinue
if ($isrunning) {
    $isrunning.CloseMainWindow()
    $isrunning | Stop-Process -Force
  }
