### ISSUE TITLE
WSL distro stopped while waiting for Lifecycle server.

### ISSUE THREAD

**Issue by GhafirDer** [docker/for-win#11120]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ondrovic** [comment]
Having the same thing happening attached is my log file
[log.txt](https://github.com/docker/for-win/files/6421701/log.txt)
