### ISSUE TITLE
Docker does not start on Windows start (does after a Restart)

### ISSUE THREAD

**Issue by EdSF** [docker/for-win#11121]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 03A5B091-BB4B-4108-AB63-0C26AECF731C/20210504140701

### Actual behavior

_Behavior described here occurs **if** you have Docker set to run after login (automatically)_

Docker desktop _seems_ to be running (icon on task bar). However, no containers are started. No errors are reported. The only indication that something is wrong:

- the `docker` icon in Windows task bar does not show the ship/whale "sails"/blows (?) 
![image](https://user-images.githubusercontent.com/636166/117827431-d448b180-b225-11eb-970b-47df2a9c0f38.png) 

- if you have Windows Notifications set for Docker (I do), it will **not** pop a notification as it normally does (not verbatim:

  > "docker wsl2...is starting"

- On the `Troubleshoot` section of Docker Desktop, the `Restart Docker Desktop` button is _disabled_ (you can't restart )  
![image](https://user-images.githubusercontent.com/636166/117827261-acf1e480-b225-11eb-9eee-80db4a2d82a3.png)

- The Settings section is stuck on a spinning wheel  
![image](https://user-images.githubusercontent.com/636166/117826826-51bff200-b225-11eb-9550-2db71a2194ad.png)

### Workarounds:
1. Start Docker Desktop **manually** (not when you log in)  by unchecking the option in settings  and just start Docker Desktop like any other app
![image](https://user-images.githubusercontent.com/636166/118281906-91374a00-b482-11eb-9798-4be49b9e345c.png)

2. However, If it's already started , and you can't do the above because the settings tab is "stuck" (see above spinning wheel), you can try:
    - Restart Windows - this _usually_ "fixes" the issue (no other action needed to get everything going as it normally should)
    - If restarting doesn't work, or you don't want to do a Windows restart, stop and restart **Docker** manually via `Windows Task Manager`
      - stop `docker.exe` and `Docker.Service`  
  ![image](https://user-images.githubusercontent.com/636166/117830155-35718480-b228-11eb-80ca-0cc3307ce45b.png)
      -  the above are the _only_ processes I can personally see when Docker fails - there are quite a few more _when it runs successfully (eg. `Docker Desktop Backend`, etc)_ 
      - Start `Docker Desktop` **manually** (via Programs, Cortana, Windows search, etc). Go through the prompts (elevated privileges, start Docker Service, etc)

### Expected behavior

Docker should normally startup with all containers running

### Information

  - Windows Version:     
     ```
    Edition	Windows 10 Pro
    Version 20H2
    Installed on 3/‎20/‎2021
    OS build 19042.928
    Experience Windows Feature Experience Pack 120.2212.551.0
    ```

  - Docker Desktop Version: ~~`3.3.1 (63152)`~~ `3.3.3 (64133)`
  - Docker Engine Version: ~~`v20.10.5`~~ `v20.10.6`
  - WSL2 or Hyper-V backend?  `WSL2`
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Start Windows 10 (cold start, not on any "standby" mode)
  2. There is no "step 2" (**if you have Docker running automatically after login)**, the issue already manifests at this point. A Windows `Restart` will "fix" (although this could be a couple of restarts) or _manually_ stop/start via `Windows Task Manager`

**Comment by wami4262** [comment]
**Same behavior:**

- Windows Version:
```
Edition Window 10 Enterprise
Version 20H2
Installed on 3/4/2021
OS build 19042.928
Experience Windows Feature Experience Pack 120.2212.551.0
```
- Docker Engine version `20.10.6, build 370c289`
- Docker Desktop version `3.3.2 (63878)`
- WSL2 or Hyper-V backend? `WSL2`
- Are you running inside a virtualized Windows e.g. on a cloud server or a VM: `No`

**My solution:**

- Stop all tasks related to "Docker Desktop" in task manager
- Start "Docker Desktop" app manually
- Commit message to start "Docker Desktop Service"

I suppose, the "Docker Desktop Service" hangs on startup and as a result Docker Desktop App is not able to work properly.

**Comment by kr99** [comment]
I am seeing this issue as well.  Extremely frustrating.
