### ISSUE TITLE
Docker Desktop 3.3.2 Fails to Start on Win10 with WSL2 Backend

### ISSUE THREAD

**Issue by bscheetz** [docker/for-win#11130]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: No diagnostics ID because Docker did not recognize this as a crash

### Actual behavior
Docker desktop tries to start, but fails to and is inaccessible via WSL (also via powershell).

### Expected behavior
Docker desktop successfully starts and is accessible via WSL.

### Information
 
  - Windows Version: 10.0.19041
  - Docker Desktop Version: 3.3.2
  - WSL2 or Hyper-V backend?  WLS2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No, on a laptop
 - I am using a Ryzen 5900HS.  Docker desktop works properly on my Intel machines.

### Steps to reproduce the behavior

  1. Install WSL2 (following instructions here https://docs.microsoft.com/en-us/windows/wsl/install-win10)
  2. Download and install Docker Desktop 3.3.2
  3. Restart machine
  4. Run Docker Desktop

The tail of the log is below:

[09:49:28.991][SystrayNotifications][Info   ] Docker is starting
[09:49:28.991][LinuxWSL2Engine   ][Info   ] Terminating lingering processes and wsl distros and patching host file
[09:49:28.995][LoggingMessageHandler][Info   ] [4a10815d] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[09:49:29.076][WSL2Provisioning  ][Info   ] Checking docker-desktop
[09:49:29.079][WSL2Provisioning  ][Info   ] deploying WSL distro docker-desktop to C:\Users\{user}\AppData\Local\Docker\wsl\distro
[09:49:29.274][LoggingMessageHandler][Info   ] [4a10815d] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 500 InternalServerError (took 281ms)

**Comment by beefpatty8888** [comment]
For me, it turns out to have been a firewall issue. I had installed TinyWall, and after uninstalling it, Docker Desktop now seems to start up correctly. I was hoping to avoid having to uninstall TinyWall since programs seem to automatically create their own rules in Windows Firewall to allow incoming traffic.

**Comment by beefpatty8888** [comment]
I recently found out that Docker Desktop now adds host entries in C:\Windows\System32\drivers\etc\hosts . In Tinywall, under Manage -> General -> "Prevent Modifications To Hosts File" is checked by default. Unchecking this option in Tinywall now seems to allow Docker Desktop to add the necessary host entries and allow Docker to startup on boot.

For reference, the host entries that Docker Desktop adds are:
``` 
# Added by Docker Desktop
192.168.88.12 host.docker.internal
192.168.88.12 gateway.docker.internal
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
```
