### ISSUE TITLE
After uninstalling docker desktop, I can't install it again. The installer doesn't work.

### ISSUE THREAD

**Issue by bugoverdose** [docker/for-win#11133]
### Expected behavior
Docker Desktop app should be installed when I run the installer. 

### Actual behavior
The installer asks me "Do you want to replace your current version of Docker Desktop 3.1.0 (51484) with this new one 3.3.2 (63878)?". When I click "Yes", the installer tries to install the app but fails. If I click "No", the installation process gets canceled.

### Information
- Windows Version: 10
- Docker Desktop Version: 3.3.2 (63878)
- WSL2 (Ubuntu)
- Are you running inside a virtualized Windows: No.
* I think the previous version of docker desktop app wasn't deleted properly in my computer. So I've tried to delete everything related to docker on both Linux and Windows sides, but nothing changed.

### Steps to reproduce the behavior
1. Delete your current docker desktop app.
2. Try to install the app again with the installer from the website (https://hub.docker.com/editions/community/docker-ce-desktop-windows).

**Comment by RomanKornev** [comment]
![image](https://user-images.githubusercontent.com/5807561/118645683-e7402080-b7e7-11eb-9ef7-f1ece6220254.png)
```
Component CommunityInstaller.EnableFeaturesAction failed: 
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
```

**Comment by 89z** [comment]
https://github.com/docker/for-win/issues/11133
https://github.com/docker/for-win/issues/9758
https://github.com/docker/for-win/issues/9780

**Comment by 89z** [comment]
To anyone getting this error:

~~~
Component CommunityInstaller.EnableFeaturesAction failed
~~~

The fix for me was enabling this service:

~~~
Windows Modules Installer
~~~

Note I used a tool [1] to do this, but I think you can also just use the normal Service App.

1. https://github.com/WereDev/Wu10Man

**Comment by kadoohh** [comment]
I have the same error.

**Comment by 89z** [comment]
Scumbag robot.
