### ISSUE TITLE
Docker for Windows Server Insider @build 16287 install fails on Docker EE docs

### ISSUE THREAD

**Issue by twobombs** [docker/for-win#1113]
### Expected behavior
Succesful installation of Docker for windows on Windows Server Core Insider 16287

https://docs.docker.com/engine/installation/windows/docker-ee/#install-docker-ee

Step 3 : Register-PackageSource -ProviderName DockerMsftProvider -Name Docker -Location https://download.docker.com/components/engine/windows-server/index.json

### Actual behavior

Program 'Register-PackageSource' failed to run: No such interface supportedAt line:1 char:1
+ Register-PackageSource -ProviderName DockerMsftProvider -Name Docker  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ Register-PackageSource -ProviderName DockerMsftProvider -Name Docker  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

# Reproduce

Install Windows Core Insider 16287 
https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewserver

Run the Docs @ https://docs.docker.com/engine/installation/windows/docker-ee/#install-docker-ee

**Comment by friism** [comment]
You might have to use this provider: https://www.powershellgallery.com/packages/DockerMsftProviderInsider/1.0.0.2

**Comment by twobombs** [comment]
tnx for the link, yet fails in similar fashion. 

___________________________

PS C:\Windows\system32> Install-Module -Name DockerMsftProviderInsider -Force
Program 'Install-Module' failed to run: No such interface supportedAt line:1 char:1
+ Install-Module -Name DockerMsftProviderInsider -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ Install-Module -Name DockerMsftProviderInsider -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

PS C:\Windows\system32> Register-PackageSource -ProviderName DockerMsftProviderInsider -Name Docker -Location https://do
wnload.docker.com/components/engine/windows-server/index.json
Program 'Register-PackageSource' failed to run: No such interface supportedAt line:1 char:1
+ Register-PackageSource -ProviderName DockerMsftProviderInsider -Name  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ Register-PackageSource -ProviderName DockerMsftProviderInsider -Name  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed 

_________________________________________

Methinks that step 2 killed it all ( Unregister-PackageSource -ProviderName DockerMsftProvider -Name DockerDefault -Erroraction Ignore )

**Comment by jasonbivins** [comment]
Hi @twobombs we had some connectivity issues with the DockerMsftProvider - I just tested and was able to use it - can you try again?

**Comment by twobombs** [comment]
Now it downloads, yet only installs the client part, pipe error on the server part with docker -v . No container role AFAIK. Will look around to install that separate. Its one step further though. ( yes, error below is when starting docker as an elevated administrator powershell user )

____________

PS C:\Users\Administrator> docker container run hello-world:nanoserver
C:\Program Files\Docker\docker.exe: error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.30/containers/create: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
See 'C:\Program Files\Docker\docker.exe run --help'.
PS C:\Users\Administrator> docker version
Client:
 Version:      17.06.2-ee-3
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   915cbaa
 Built:        Thu Sep 21 23:01:20 2017
 OS/Arch:      windows/amd64
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.30/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
PS C:\Users\Administrator>

**Comment by twobombs** [comment]
update: works now. not everything was installed correctly. after 2 reboots al functionality was installed correct. tnx for the fix. next bug is staring me in the face though, but that is for another time  :)

PS C:\Users\Administrator> docker version
Client:
 Version:      17.06.2-ee-3
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   915cbaa
 Built:        Thu Sep 21 23:01:20 2017
 OS/Arch:      windows/amd64
Server:
 Version:      17.06.2-ee-3
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   915cbaa
 Built:        Thu Sep 21 23:10:04 2017
 OS/Arch:      windows/amd64
 Experimental: false
PS C:\Users\Administrator> docker container run hello-world:nanoserver
Unable to find image 'hello-world:nanoserver' locally
nanoserver: Pulling from library/hello-world
bce2fbc256ea: Pull complete
b0b5e40cb939: Pull complete
87377cdc7dd1: Pull complete
7d840042f15f: Pull complete
Digest: sha256:09084a40d44e22bd468beb17ca48a85f7b23c1ee07e68e7ea1df6827e38205f7
Status: Downloaded newer image for hello-world:nanoserver
C:\Program Files\Docker\docker.exe: Error response from daemon: container 0ee867b009b8fa5c8bf2bbdf42497d04d5429f0ecb02be21fc06bf2830e6420c encountered an error during CreateContainer: failure in a Windows system call: The operating system of the container does not match the operating system of the host. (0xc0370101) extra info: {"SystemType":"Container","Name":"0ee867b009b8fa5c8bf2bbdf42497d04d5429f0ecb02be21fc06bf2830e6420c","Owner":"docker","IsDummy":false,"VolumePath":"\\\\?\\Volume{fdda2455-7d71-49eb-b37f-42920ca89fc7}","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\docker\\windowsfilter\\0ee867b009b8fa5c8bf2bbdf42497d04d5429f0ecb02be21fc06bf2830e6420c","Layers":[{"ID":"13302f61-ec2c-5aa4-9804-890d411ab48e","Path":"C:\\ProgramData\\docker\\windowsfilter\\06ec9cc708651198cdb1b936a50b64f8f8f6ed20b39795cc86e61b9697bfd6ba"},{"ID":"45ebb0c0-e774-54e3-9586-1697dadd993e","Path":"C:\\ProgramData\\docker\\windowsfilter\\eb123854602360e2b01e3df4ef4d4f1aaa6f4042d905047fa75e3c09123c2486"},{"ID":"1efe42f2-36df-5703-af2d-88b80caef9e6","Path":"C:\\ProgramData\\docker\\windowsfilter\\8dc310111ff980dc7207216b0971706735cec19ccbc27f6b5bb3399a947728b0"},{"ID":"ec3efc25-c45f-5ebb-84d8-ceff5a69ac54","Path":"C:\\ProgramData\\docker\\windowsfilter\\7810fee89bee2c84ab9ce5f109df2d2fcff31b08025b9f5474e48d416805a4bd"}],"HostName":"0ee867b009b8","MappedDirectories":[],"HvPartition":false,"EndpointList":["47c20586-b153-4ab7-8e20-4df2b7425b8f"],"Servicing":false,"AllowUnqualifiedDNSQuery":true}.

**Comment by jasonbivins** [comment]
Hi @twobombs since nanoserver is a Windows image - make sure you're in Windows container mode - or you could run the linux version . ``docker run hello-world ```
