### ISSUE TITLE
Faile to launch in : an error occured 

### ISSUE THREAD

**Issue by djibal** [docker/for-win#11140]
# Docker: An error occurred 
`Failure-to-launch 
`

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...
![Shot029 (2)](https://user-images.githubusercontent.com/81055330/117446570-2b077000-af34-11eb-8341-f584352f381b.png)

**Comment by stephen-turner** [comment]
The solution is in the screenshot.
