### ISSUE TITLE
it wont open after starting the pc 09D7C22D-40CD-4226-A306-7F35269FF417/20210508141641

### ISSUE THREAD

**Issue by NickSpirit21** [docker/for-win#11146]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:09D7C22D-40CD-4226-A306-7F35269FF417/20210508141641

### Information

  - Windows Version:20H2
  - Docker Desktop Version:3.3.3
  - WSL2 or Hyper-V backend?  HyperV
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:Virtualized Windows

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by NickSpirit21** [comment]
i installed in order to use pi nodes but it wont start due to problem
id:09D7C22D-40CD-4226-A306-7F35269FF417/20210508141641

**Comment by stephen-turner** [comment]
Please read https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-desktop-in-nested-virtualization-scenarios
