### ISSUE TITLE
Docker installer failing with .net error

### ISSUE THREAD

**Issue by cbrherms** [docker/for-win#1114]
### Expected behavior

docker for windows installs or updates correctly

### Actual behavior

Docker installer silently crashes with no visible error on win10 with .net 4.7.02552

### Information

`Faulting application name: Docker for Windows Installer (1).exe, version: 1.0.105.0, time stamp: 0x59bff01b
Faulting module name: d3d9.dll, version: 10.0.16281.1000, time stamp: 0xecaf3c26
Exception code: 0xc0000005
Fault offset: 0x00000000000198cf
Faulting process ID: 0x319c
Faulting application start time: 0x01d3330d4118c136
Faulting application path: D:\Downloads\Docker for Windows Installer (1).exe
Faulting module path: C:\WINDOWS\SYSTEM32\d3d9.dll
Report ID: 0745d5f9-ffd5-4316-b9e6-2ec354e22ae5
Faulting package full name: 
Faulting package-relative application ID: `

`Application: Docker for Windows Installer (1).exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FF8EE5C98CF`

**Comment by circlechu** [comment]
sucks

**Comment by cbrherms** [comment]
Forgot to close this. Issue was with rivatuner statistics tuner trying to hook in to the installer. Added exception and installer ran fine.

**Comment by circlechu** [comment]
Fixed? just happening today, i downloaded the latest version on official website. it's windows 7, does it works for windows 7 or you it works for windows 10 only?

**Comment by cbrherms** [comment]
It wasn't an issue with the installer but rather another app I had trying to overlay on the window. 
If your error does not mention the d3d9.dll file then it is potentially caused by something else
