### ISSUE TITLE
Upgrade to 3.3.3  failed due to com.docker.service is being used by another process

### ISSUE THREAD

**Issue by hantsy** [docker/for-win#11144]
- Windows Version: 10 
  - Docker Desktop Version: 3.3.1 
  - WSL2 or Hyper-V backend?  WSL
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: WSL/Ubuntu

Upgrade to 3.3.3 failed.

Unpacking failed: The process cannot access the file 'C:\Program Files\Docker\Docker\com.docker.service' because it is being used by another process.

**Comment by ThePlenkov** [comment]
I have same issue #10774

**Comment by workpebojot** [comment]
Just open **Task Manager**, and find **Docker.Service** and click **End Task**
