### ISSUE TITLE
Broken taskbar context menu

### ISSUE THREAD

**Issue by flopun** [docker/for-win#11152]
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 26F69FBF-77C9-4D7E-8516-EC5217DD961B/20210514121207

### Actual behavior
Taskbar menu is incomplete
### Expected behavior
Full taskbar menu
### Information
Resetting to factory defaults did not help
-->
  - Windows Version:10
  - Docker Desktop Version: 3.3.3
  - WSL2 or Hyper-V backend?  no
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no
![Screenshot](https://user-images.githubusercontent.com/51449861/117588388-54d2b980-b123-11eb-9fa5-5b6e0d30da2c.png)

**Comment by tjgalama** [comment]
I got the same problem here. I can't switch to Linux containers anymore.

**Comment by STotev** [comment]
Same for me, but I have even bigger issue. My daemon didn't start and now I can't seem to be able to quit from the context menu nor by killing tasks from the Task Manager.

**Comment by tjgalama** [comment]
@flopun, I noticed that there are several new issues regarding V3.3.3 without a full description or uploaded Diagnostics. 
Without this, a decent analysis is hard (if not impossible) for responders.

**Comment by flopun** [comment]
Added diagnostics ID as @tjgalama suggested.
