### ISSUE TITLE
Cannot build Linux image on with Windows containers

### ISSUE THREAD

**Issue by SetTrend** [docker/for-win#11168]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: F9C61679-70F2-4888-B1A0-BB9182F5AFBD/20210510211500

### Actual behavior

I cannot build a Linux container on Windows next to Windows containers.

### Expected behavior

According to [the docs](https://devblogs.microsoft.com/premier-developer/running-docker-windows-and-linux-containers-simultaneously/), I should be able to build and run both, Linux and Windows, containers along to each other.

### Information

  - Windows Version: Windows 10x64, v20H2
  - Docker Desktop Version: 
   ```
   Client: Docker Engine - Community
    Cloud integration: 1.0.12
    Version:           20.10.5
    API version:       1.41
    Go version:        go1.13.15
    Git commit:        55c4c88
    Built:             Tue Mar  2 20:14:53 2021
    OS/Arch:           windows/amd64
    Context:           default
    Experimental:      true

   Server: Docker Engine - Community
    Engine:
     Version:          20.10.5
     API version:      1.41 (minimum version 1.24)
     Go version:       go1.13.15
     Git commit:       363e9a8
     Built:            Tue Mar  2 20:26:56 2021
     OS/Arch:          windows/amd64
     Experimental:     false
  ```
  - WSL2 or Hyper-V backend?
    WSL 2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:
    Yes, VMware Workstation

### Steps to reproduce the behavior
```batch
docker build --force-rm=true --platform=linux
  -t 'oracle/database:18.4.0-xe' -f 18.4.0\Dockerfile.xe .

ending build context to Docker daemon  260.6kB
Error response from daemon: unsupported os linux
```

**Comment by stephen-turner** [comment]
Thanks for the ticket. That is Microsoft's documentation, not ours, and is out of date. Unfortunately we had to remove LCOW. It was only ever experimental, and never reached a level of quality we were happy with. See https://docs.docker.com/engine/deprecated/#linux-containers-on-windows-lcow-experimental.

We do have a roadmap item for supporting Windows and Linux containers simultaneously, which you're welcome to vote for: docker/roadmap#79.
