### ISSUE TITLE
Docker Daemon Consistently Fails to Start After Reboot

### ISSUE THREAD

**Issue by ShaneF67** [docker/for-win#11169]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: EADA4CF6-A8F1-4AF7-AD63-93F03F5D7834/20210510221914

### Actual behavior
Docker does not start correctly (it appears the daemon does not start).
The Docker application will start and the icon is in the task bar, but only the whale is visible. The service never starts.
The settings page is inaccessible (it is stuck on the spinner).

### Expected behavior
Docker starts normally with Windows.

### Information

  - Windows Version: Windows 10 Enterprise Version 1909 (OS Build 18363.1500)
  - Docker Desktop Version: Tried installing 3.3.1, 3.3.2 and 3.3.3 the issue is on all versions
  - WSL2 or Hyper-V backend?  Currently WSL2 but I tried both
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No
  - I have scoured the past issues and forums but nothing suggested works.
  - I do not have any experimental features installed. I re-installed three different versions of Docker today so I am on factory settings.
  - I tried removing all files related to Docker (including AppData) before re-installing.
  - This issue only appeared in the past two weeks, Docker was running fine for two years before that.
  - If I Clear/Purge data, Reset to Factory Defaults or run this in powershell '& 'C:\Program Files\Docker\Docker\DockerCli.exe' -SwitchDaemon', Docker will restart successfully and work. But the next time I reboot my computer the issue returns. This is not an option for me though as it deletes all of my images and containers.

### Taskbar Icon
![image](https://user-images.githubusercontent.com/11586314/117736458-3de0a580-b1bd-11eb-9095-9092c2625565.png)

### Settings Page
![image](https://user-images.githubusercontent.com/11586314/117736496-56e95680-b1bd-11eb-9fea-8636e212ac67.png)

### Log file
[log.txt](https://github.com/docker/for-win/files/6455481/log.txt)

### Steps to reproduce the behavior

  1. Restart computer and Docker does not start successfully.

**Comment by wami4262** [comment]
I think, this is the same issue as mentioned here: https://github.com/docker/for-win/issues/11121#issuecomment-832514369

**Comment by marcrobertscamao** [comment]
I think it is also a duplicate of #11162 and #11167 but this one was a little clearer in the description

**Comment by wami4262** [comment]
Might be the same issue: https://github.com/docker/for-win/issues/11174

**Comment by ShaneF67** [comment]
I managed to work around this issue with a combination of comments from this ticket https://github.com/docker/for-win/issues/10958

Comments: #https://github.com/docker/for-win/issues/10958#issuecomment-831306519 #https://github.com/docker/for-win/issues/10958#issuecomment-833259325

Summary:
1. Download the installer (3.3.2) and run it manually (as opposed to using chocolatey)
2. When prompted un-select "install wsl components" and "create link on desktop"
3. Then, start docker desktop and everything runs as it used to 🤷🏻‍♀️

and this:
I found what was the problem for my docker desktop start. By default docker wanted to sign in to my dockerhub account and for some reason related to my proxy (I sometimes use my company vpn sometimes not) it failed . In dashboard I signed out from docker hub and now docker starts

**Comment by belucha** [comment]
Solved!
Thanks to @ShaneF67 I just signed out and my docker started immediately. So this was the only problem.

**Comment by shivaanmotilal** [comment]
The fix that @belucha mentioned works, signing out of your docker account on docker desktop and then signing back in restarts the daemon. In future they should probably add restart of docker on starting up docker desktop; instead of leaving it running in the background with daemon not started.
