### ISSUE TITLE
[GoBackendClient   ][Error  ] Error sending new login: Docker.Core.DockerException: unable to ping backend API: The operation has timed out.

### ISSUE THREAD

**Issue by kazutsugu** [docker/for-win#11174]
- [ x ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ x ] I have uploaded Diagnostics
  - Diagnostics ID: D2191AD7-EFE2-4942-96F6-D8FD268B2670/20210511084633

### Actual behavior
Auto start is enable. However, after each signing out/in, any cli command returns
error during connect: This error may indicate that the docker daemon is not running.

FYI. I can get out this with the Reset to factory defaults.
But even after resetting to default, a signing out/in puts it back again to the daemon-not-starting state.

### Expected behavior
The daemon starts automatically and docker cli becomes available.

### Information

  - Windows Version: Windows 10 Enterprise: Version 10.0.18363 Build 18363
  - Docker Desktop Version: 3.3.3 (64133)
  - WSL2 or Hyper-V backend?  Hyper-V was originally enabled, which then disabled to try WSL. But the issue persists.
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. The problem happens with a freshly installed desktop 3.3.3
  2. ...

[log.163.txt](https://github.com/docker/for-win/files/6459687/log.163.txt)

**Comment by kazutsugu** [comment]
Encountered the issue first with 3.3.1. Updating to 3.3.3 did not help. Going back to 3.2.2, the last 3.2 version, did help i.e. now docker desktop comes up to the usable state. So, I guess I will stay with this version until this issue (seems to me to have been experienced and reported accordingly by many users) is looked at.

**Comment by kazutsugu** [comment]
Right after the previous post, I realized that now the update is not an option, but forced. My installation was brought back to the not-functioning 3.3.3. shorturl.at/bpIL1 reads: (there is) _**an option to disable that if you pay them for a Team plan.**_ Is this some sort of start-free-but-end-up-paying business??

**Comment by EdSF** [comment]
> Is this some sort of start-free-but-end-up-paying business??

Nope. It's an incredibly helpful piece of software, built by people just like you and me (smarter than me for sure, since I can't write this stuff), who devote time creating and maintaining it, offered by a _business_, just like any other, with a free _version_.
