### ISSUE TITLE
Docker fails to run under WSL Hyper-V after 3.3.3 update

### ISSUE THREAD

**Issue by bevin0708** [docker/for-win#11176]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
** Docker fails to run under WSL 1, after update to 3.3.3 **
Docker run command from WSL (Ubuntu)fails with the following message.
    The command 'docker' could not be found in this WSL 1 distro.
    We recommend to convert this distro to WSL 2 and activate
    the WSL integration in Docker Desktop settings.
    
    See https://docs.docker.com/docker-for-windows/wsl/ for details.

This worked with 3.3.2 and works when running on windows.

### Expected behavior

Docker run should start a container.

### Information
 docker run --name builder lambci/lambda:build-java11
  - Windows Version: 10.0.19042 N/A Build 19042
  - Docker Desktop Version: 3.3.3
  - WSL2 or Hyper-V backend?  Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. start WSL (Ubuntu 20.04.2 LTS)
  2. docker run --name builder lambci/lambda:build-java11

**Comment by oscarmparedes** [comment]
Hi!
Please try this:
`# turn off all wsl instances such as docker-desktop
wsl --shutdown
notepad "$env:USERPROFILE/.wslconfig"
[wsl2]
memory=1GB   # Make sure you have enough memory`

**Comment by bevin0708** [comment]
The issue is caused by a new script file introduced with Docker 3.3.3 in the windows bin folder that searches for the binary file.
This file named "docker" and prevents WSL 1 from executing Docker.

```
$ uname -r
4.4.0-19041-**Microsoft**
```
In this case, the script always prints this message and terminates.

```
#!/usr/bin/env sh
#
# Copyright (c) Docker Inc.

binary=$(basename "$0")
case "$(uname -r)" in
    *microsoft* )
        # WSL 2
        if [ -f "/usr/bin/$binary" ]; then
            # It seems this script ran before the integration added the real binary.
            # Run the real binary for the user.
            set -e
            "/usr/bin/$binary" "$@"
        else
            echo
            echo "The command '$binary' could not be found in this WSL 2 distro."
            echo "We recommend to activate the WSL integration in Docker Desktop settings."
            echo
            echo "See https://docs.docker.com/docker-for-windows/wsl/ for details."
            echo
            exit 1
        fi
        ;;
    *Microsoft* )
        # WSL 1
        echo
        echo "The command '$binary' could not be found in this WSL 1 distro."
        echo "We recommend to convert this distro to WSL 2 and activate"
        echo "the WSL integration in Docker Desktop settings."
        echo
        echo "See https://docs.docker.com/docker-for-windows/wsl/ for details."
        echo
        exit 1
        ;;
    * )
        # No WSL, maybe MINGW, try Windows exe which should also be in PATH
        "$binary.exe" "$@"
        ;;
esac
```


Can someone confirm that this resolves the issue
