### ISSUE TITLE
Diagnostic ID:  54AF0361-A8A5-4538-A3C2-B86810D1E783/2017-09-22_18-16-15

### ISSUE THREAD

**Issue by gswinkels** [docker/for-win#1117]
freshly installed Docker ... fails to start

**Comment by tizmagik** [comment]
Also just installed, had the same issue. I submitted a log/separate issue in #1121

**Comment by jasonbivins** [comment]
Hi @gswinkels 
Hyper-V is a requirement of Docker for Windows - and it is not included with Windows 10 home editions.  You'll need to upgrade to Win 10 Pro ,Enterprise, or Education editions -  but you might be able to take advantage of our legacy solution Docker Toolbox.

https://docs.docker.com/docker-for-windows/install/#what-to-know-before-you-install

https://docs.docker.com/toolbox/overview/
