### ISSUE TITLE
Server execution failed

### ISSUE THREAD

**Issue by paul-8235d9** [docker/for-win#11182]
- [ x] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 14647985-016B-4B96-9F98-EF2DDBCF90FD/20210511201143

### Actual behavior
System crashes during startup. Reset to factory does not resolve issue.
### Information

  - Windows Version: Currently on build 21376.1 These crashes also happened with 21370.1 and 21343.1
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. System reboot with docker set to startup.
  System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\Paul\AppData\Local\Docker\wsl\distro: exit code: 1
 stdout: 
 stderr: Server execution failed
  2. ...

**Comment by stephen-turner** [comment]
This error usually means that you haven't installed WSL 2 correctly, which Docker Desktop uses. Please follow Microsoft's instructions at https://aka.ms/wsl2-install. If it's set up correctly, then the command wsl -l -v should show a version 2 distro.
