### ISSUE TITLE
Crash when starting up program

### ISSUE THREAD

**Issue by anhsuper** [docker/for-win#11197]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 25D13BD0-42A8-4482-A518-7996A8C7C2B4/20210513092718

### Actual behavior
Open docker
### Expected behavior
Crash
### Information

  - Windows Version: Windows 10 Home Single Language version 20H2
  - Docker Desktop Version: 3.3.3
  - WSL2 or Hyper-V backend?  WSL
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: None

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Calrain** [comment]
I am also having this problem.

Have been using Docker on my Windows 10 machine for well over a year, and the 3.3.3 upgrade has corrupted my Docker installation, to the point that the installer doesn't install the Docker service, and starting the Docker Desktop app only results in a crash as soon as the WSL2 support popup appears.

Manually running `dockerd.exe` in an Administrator Privilege command window works, and the API is listening on `//./pipe/docker_engine' but the Docker Desktop app shuts down.
