### ISSUE TITLE
System.InvalidOperationException: Failed to deploy distro docker-desktop to C:\Users\NishchaySk\AppData\Local\Docker\wsl\distro: exit code: -1  stdout: {Application Error}

### ISSUE THREAD

**Issue by nishchaysk98** [docker/for-win#11193]
System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\NishchaySk\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: {Application Error}

Diagnostic Id
77D19D80-B9C1-4662-A80D-87DE8C1ABA90/20210513040736

**Comment by stephen-turner** [comment]
It appears that you haven't installed WSL 2 correctly, which Docker Desktop uses. Please follow Microsoft's instructions at https://aka.ms/wsl2-install. If it's set up correctly, then the command wsl -l -v should show a version 2 distro.

**Comment by nishchaysk98** [comment]
worked thanks
