### ISSUE TITLE
Can't get GPU support with WSL2

### ISSUE THREAD

**Issue by michaelitvin** [docker/for-win#11208]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Trying to run a GPU enabled container such as:
`docker run --gpus all nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -gpu -benchmark`

I get this error:

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request: unknown.
ERRO[0025] error waiting for container: context canceled
```

Running `docker run hello-world` works fine.

### Expected behavior
Run without errors:)

### Information

  - Windows 10 Pro (version 20H2 build 19042.985)
  - Docker Desktop 3.3.3 (64133), engine 20.10.6, compose 1.29.1
  - WSL2 with Ubuntu 20.04
  - Nvidia driver 470.14 + CUDA 11.3
  - Geforce RTX 2070 Max-Q
  - Running on a local laptop

### Steps to reproduce the behavior

  1. Install the above versions of things
  2. Run any GPU enabled container, such as `docker run --gpus all nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -gpu -benchmark`

**Comment by Oleg26Dev** [comment]
I receive the same error message in the similar environment:
```
PS D:\_Docker>
               docker run --rm -it --gpus=all nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -gpu -benchmark
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request: unknown.
PS D:\_Docker>

```

**Comment by michaelitvin** [comment]
According to [this answer](https://superuser.com/questions/1649151/cant-get-gpu-support-for-docker-with-wsl2), it seems that the Win10 build version isn't sufficient, and needs to be upgraded using the Windows Insider Program.
