### ISSUE TITLE
Docker for Windows Update Menu Does Not Work -- Cannot Update

### ISSUE THREAD

**Issue by maplion** [docker/for-win#11216]
- [ x ] I have tried with the latest version of Docker Desktop
  - [ x ] I have tried disabling enabled experimental features
  - [ x ] I have uploaded Diagnostics
  - Diagnostics ID: EB934DB9-ED5C-445C-9DC6-C5906AEE4C8F/20210515234535

### Actual behavior

I am being auto-prompted to install Docker Desktop Version 3.3.3 (64133) - May 6 2021.  When I try to click "Download Update", it freezes the window and nothing happens and all other links (the "X" and the "See what's new") stop functioning as well.  As a result, I am not able to update and then am frequently met with the "Update ready to download" window that I can't interact with.

### Expected behavior

I Expect when the "Update ready to download" window appears that I can click "Download update" and begin updating Docker Desktop.

### Information
This is a relatively new problem (assuming with the last update), as I have had Docker Desktop installed since March and done at least one other upgrade.
  - Windows Version: 10.0.19043 Build 19043
  - Docker Desktop Version: 3.3.0 (62916)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

**Comment by stephen-turner** [comment]
Hmm, I don't have an explanation for that, but you could download the update directly from https://www.docker.com/products/docker-desktop
