### ISSUE TITLE
Issue reporting template claims "issues" without a diagnostics ID cannot be debugged

### ISSUE THREAD

**Issue by Chealer** [docker/for-win#11241]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: None

### Actual behavior
This is not a behavioral bug.

### Expected behavior
This is not a behavioral bug.

### Information
When reporting an issue in Docker Desktop, the ticket template starts with a comment which contains:

> Issues without a clear title, description, and diagnostics ID cannot be debugged,
> and will be closed. See https://docs.docker.com/docker-for-windows/troubleshoot/#diagnose-and-feedback
> for how to generate a diagnostics ID either from inside the app or from the command
> line.

Obviously, a diagnostics ID is never required to debug an issue (even for issues which are bugs). While I am sure diagnostic data facilitates solving behavioral bugs, this should be rewritten in a less misleading (and ideally more constructive) phrasing, in order to prevent losing contributors.

  - Windows Version: Not applicable
  - Docker Desktop Version: Not applicable
  - WSL2 or Hyper-V backend?  Not applicable
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Not applicable

### Steps to reproduce the behavior
[Start reporting an issue](https://github.com/docker/for-win/issues/new)

**Comment by stephen-turner** [comment]
You're right that not every bug requires a diagnostics id, depending how easy it is to reproduce. However, over half the tickets we get do not contain even the most minimal information -- often they are only a title like "crashed" with no further information -- and we do want to discourage them. And very often a bug is more difficult to reproduce than the reporter imagines: even if they are seeing it every time, it doesn't mean that someone else will.

Having said that, feel free to open a PR to improve the wording. But it must at least strongly encourage a diagnostics id for any bug, and warn that bugs without one are likely to be closed.

**Comment by Chealer** [comment]
It is clear that lots of report lack information, and diagnostics help with that. On the other hand, providing a diagnostics ID can be prohibitively costly, so there should be a balance.

The simplest fix would be to change...

> Issues without a clear title, description, and diagnostics ID cannot be debugged, and will be closed.

...to...

> Issues without a clear title and description cannot be debugged, and will be closed. Such issues and those without a diagnostics ID will be closed.

But I would encourage to use this opportunity for a more complete review of this part, and to remove the statement according to which "issues" without a diagnostics ID will be closed. Ideally, that fragment should read something like:

> The more precise and clear the report, the easier it is to understand and solve the issue, and the more likely the issue is to be worked on. The title and description are the most important determiners of clarity. Diagnostics greatly facilitate debugging.

But the current statement describes a reality I don't know enough to recommend specific wording. It could be that the current statement describes a reality, and that the first step would be to change that reality, which goes beyond this ticket's scope.

**Comment by stephen-turner** [comment]
I'm interested why you say that providing a diagnostics ID is prohibitively costly. It's just a single button in the UI, or a single CLI command.

**Comment by Chealer** [comment]
Hi @stephen-turner ,
> I'm interested why you say that providing a diagnostics ID is prohibitively costly. It's just a single button in the UI, or a single CLI command.

I wrote it **can** be prohibitively costly. The interface does make it smooth if you work for Docker and already have a Docker ID. On the other hand, even with the UI polish, if you are new to Docker and work on a computer with private data, for example if you work for a security organization, you'll probably need to:

1. Create a Docker ID
2. Learn about Docker's personal data handling
3. Either inspect the large amounts of information collected, or read the collector's source, or find some reliable assessment that the collection is sufficiently safe, or reproduce the issue in an environment without sensitive information

This could easily increase the cost of reporting by an order of magnitude.

**Comment by stephen-turner** [comment]
Apologies for the delay, but I've now reworded the issue template. Hopefully it's more accurate now. Thanks for the suggestion.

**Comment by Chealer** [comment]
My pleasure @stephen-turner , thanks to you
