### ISSUE TITLE
Docker Failed to Initialize

### ISSUE THREAD

**Issue by GenDemo** [docker/for-win#11257]
HI

My docker doesnt want to launch. It updated last week, and now it doesn't want to initialize.
I cant get it to open to try some of the steps that are suggested on the site.
And dont tell me "there isn't enough information" and close the ticket - that does not help!

  - [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
@GenDemo Sorry, I know you don't want me to say this, but there really isn't enough information. You haven't even given the error message, let alone a diagnostics id. There is nothing here to enable us to investigate any issue.

**Comment by GenDemo** [comment]
Dont worry. I got it fixed.

What I sent is what the docker UI suggests to send as an error diagnostic. You guys then perhaps need to look at the automated diagnostic that is generates and suggests. And all it says is ‘failed to initialise’ ... what rlse can I tell you.

Kind Regards,

Andries van Wyk
Sent from Outlook<https://aka.ms/qtex0l> for iOS
________________________________
