### ISSUE TITLE
Docker import does not work correctly in Windows Server 2019

### ISSUE THREAD

**Issue by soroshsabz** [docker/for-win#11269]
### Actual behavior
I want to import docker image file to my windows server 2019 from my windows 10 docker, when I run below command

`docker import .\testcoreservice.tar
`
I see below error

```
docker : Error response from daemon: re-exec error: exit status 1: output: hcsshim::ProcessBaseLayer
cannot find the path specified.

\\?\C:\ProgramData\docker\windowsfilter\d4dd79e55f1d583ebf579f6a33778ecae1d954b35606d5d0037870e154bbcbfb: The system
cannot find the path specified.
    + CategoryInfo          : NotSpecified: (Error response ...path specified.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

```

### Expected behavior

import correctly my docker image

### Information

  - Windows Version: Windows Server Datacenter Version 2009 (OS Build 19042.985)
  - Docker Client: Docker Application (Docker Inc., v0.8.0)
  - WSL2 or Hyper-V backend?  no, I use `Windows Server Datacenter Version 2009 (OS Build 19042.985)`
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: yes

**Comment by stephen-turner** [comment]
Sorry, this issue tracker is only for Docker Desktop. Support for Docker EE on Windows Server is provided by Microsoft.

**Comment by soroshsabz** [comment]
@stephen-turner Where is the location for ask my question and problem for Docker EE on Windows Server?

**Comment by stephen-turner** [comment]
Sorry, I'm not sure, because it's Microsoft support not us.
