### ISSUE TITLE
Docker Desktop won't start after reboot on version 3.3.X

### ISSUE THREAD

**Issue by Pat-Ayres** [docker/for-win#11279]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 879EF74A-3DA6-4270-AE5F-89BE7528F0A7/20210522192914

### Actual behavior
On Reboot Docker Desktop runs, but is stopped and cannot be used. If I force close it in task manager and restart it I get the message "It looks like there is an error with Docker Desktop, restart it to fix it".  

If I do a factory reset it fixes the issue until my next reboot.  I have tried uninstalling and reinstalling completely and that did not fix the issue.

### Expected behavior
Docker Desktop starts correctly and I am able to use it without forcing factory reset after rebooting my computer.

### Information

  - Windows Version: 21H1 19043.985 (Insiders Beta)
  - Docker Desktop Version: 3.3.3
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Pat-Ayres** [comment]
after downgrading to 3.2.2 the issue is no longer present, but every time I restart it tries to force me to update

**Comment by wumeizhi** [comment]
as same as mine

**Comment by wami4262** [comment]
Same here https://github.com/docker/for-win/issues/11121

**Comment by ThePlenkov** [comment]
happenned to me as well, I was able to fix this with this button 
![image](https://user-images.githubusercontent.com/6381507/120216983-01dab680-c238-11eb-88e6-7e6701469df2.png)

Luckily is just images/containers - so all settings stayed not touched

**Comment by Pat-Ayres** [comment]
I am now on 3.5.1 and no longer experiencing this issue.
