### ISSUE TITLE
Docker 3.3.3 crash on win10 wsl2 backend

### ISSUE THREAD

**Issue by domjesus** [docker/for-win#11270]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 812D13FB-E7A4-47A5-8494-3D9FC4930195/20210521162506

### Information

  - Windows Version: 10
  - Docker Desktop Version: 3.3.3
  - WSL2 or Hyper-V backend?  wsl2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:virtualized windows

### Steps to reproduce the behavior

The docker crashes when wsl2 starts show error: Failed to deploy distro docker-desktop to C:\Users\domje\AppData\Local\Docker\wsl\distro: exit code: -1  stdout: Error: 0x80041001

My note had a hdd, yesterday I change for a ssd and then the error starts to occur.

**Comment by stephen-turner** [comment]
This error usually means that you haven't installed WSL 2 correctly, which Docker Desktop uses. Please follow Microsoft's instructions at https://aka.ms/wsl2-install. If it's set up correctly, then the command wsl -l -v should show a version 2 distro.
