### ISSUE TITLE
Unable to mount C drive: 10.0.75.1 (10.0.75.1:445) open

### ISSUE THREAD

**Issue by sytou** [docker/for-win#1128]
### Expected behavior
Share drive C
### Actual behavior
Can't share drive C
### Information
Diagnostic Id =4D552922-0C5E-494B-825D-C1B264C14D7B/2017-09-26_13-25-51
Version 17.06.2-ce-win27 (13194)
Channel: stable
428bd6c
### Steps to reproduce the behavior
docker run --rm -v c:/Users:/data alpine ls /data

**Comment by jasonbivins** [comment]
Hi @sytou 
We use port 445 through Windows File and printer sharing to connect to the drives via Samba and CIFS - Make sure you're allowing File and Printer Sharing (NB-Session-In) and File and Printer Sharing (SMB-In) through your local firewall.

**Comment by sytou** [comment]
Crash report send this morning
4D552922-0C5E-494B-825D-C1B264C14D7B/2017-09-27_10-58-16

**Comment by sytou** [comment]
Firewall parameters
![parametres-firewall](https://user-images.githubusercontent.com/12085103/30914832-3472bd7e-a395-11e7-9acb-d632ef12610e.png)

**Comment by jasonbivins** [comment]
Hi @sytou    Have you tried switching to the edge channel to see if the latest build helps?

Here's the error from the new logs, it's the same as before

```mount error(112): Host is down
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
mount: mounting //10.0.75.1/C on /c failed: Invalid argument```

**Comment by sytou** [comment]
Sorry @jasonbivins but i open new issue because Docker doesn't start anymore. Crash report send.

**Comment by prajapatin** [comment]
After lot of struggle, I was able to get rid of this error. Please follow below steps if none of the resolution works mentioned on this thread.

Navigate to C:\Users\Public\Documents\Hyper-V (it will ask administrative permission)
Click on folder "Virtual hard disks"
Here you will find "MobyLinuxVM.vhdx", just right click on it and goto context menu "Share with -> Advanced sharing settings..."
There you just go ahead and enable sharing under Public folder sharing blade and that's it. Once you have saved this settings, go ahead and enable sharing drive through docker command or through docker UI (settings)
