### ISSUE TITLE
When i update to 3.3.3 , i can't start my containers not until i downgrade it to 3.3.1 .

### ISSUE THREAD

**Issue by wumeizhi** [docker/for-win#11281]

**Comment by apquirogajr** [comment]
Similar issue after updating today to 3.3.3.  Shutdown my containers updated, rebooted, and now Docker Desktop will not finish startup.

Tried the below as suggested in prior issues:

```
stop Docker Desktop
stop WSL (wsl --shutdown)
unregister the docker-desktop distro (which contains binaries, but no data) with wsl --unregister docker-desktop
restart Docker Desktop
```

still not starting up.

Rolled back to 3.3.2 and instant startup.

**Comment by jloic** [comment]
same for me, had to downgrade. The spinner keeps showing on the dashboard, no error message.

**Comment by WesDowney** [comment]
When seeing the settings page hang, running the following in Powershell gets it back for me
`cd "C:\Program Files\Docker\Docker"`
`./DockerCli.exe -SwitchDaemon`

After that, my WSL frequently will still not show under Docker Desktop > Settings > Resources. Usually will work after a fresh install and then breaks after a reboot. I noticed @apquirogajr 's happens after a reboot too.

**Comment by bnapora** [comment]
How did you downgrade?  After downgrade were your existing container's still available?

**Comment by WesDowney** [comment]
One way to downgrade is to uninstall Docker Desktop and install an earlier release from the Docker Desktop releases page.

**Comment by wumeizhi** [comment]
> How did you downgrade? After downgrade were your existing container's still available?

i backup containers and uninstall docker desktop 3.3.3 .
then download 3.3.1 on official webside and install it .
