### ISSUE TITLE
Crash during Boot. Windows Desktop WLS 

### ISSUE THREAD

**Issue by GiuseppeLeviBo** [docker/for-win#11282]
Docker has crashed during boot. Not recoverable. I was forced to uninstall the system and reinstall it.
The only thing done was to create an UBUNTU container. Install Apache and net-utils, ping, ip in the container.
The host was rebooted while the container was running but this on my opinion should not be a problem for the whole docker desktop.

**Comment by GiuseppeLeviBo** [comment]
The crash report upload has the id 0647DD7F-CD9F-4768-BBAE-5C9EC76742BB/20210523082008

**Comment by devilmind81** [comment]
Same issue here.
I have done a troubleshootin steps and obtain:
Unable to list goroutine stacks: fetching goroutine stacks: Get "http://vsock/diagnostics/goroutines": open \\.\pipe\dockerBackendApiServer: The system cannot find the file specified.

and wsl command returns

>wsl
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore

What is missing...before update is working fine. help me pls

**Comment by wizonesolutions** [comment]
Workaround seems to be to run:

`& 'C:\Program Files\Docker\Docker\DockerCLI.exe' -SwitchDaemon`

wait for it to start, and then run the command again.

I don't know why, though, and I can't find any documentation on `DockerCLI.exe`.

Source: https://stackoverflow.com/questions/59912069/docker-for-windows-hangs-while-trying-to-see-settings/67091896#67091896

**Comment by devilmind81** [comment]
Thank you for reply @wizonesolutions  but is not working for me.
I see the docker icon in the system try and soon disappear...
Those are the logs after run .\com.docker.diagnose.exe" gather -upload to create a zip file.


[stacks.err.txt](https://github.com/docker/for-win/files/6533777/stacks.err.txt)
[port-forward.err.txt](https://github.com/docker/for-win/files/6533779/port-forward.err.txt)
[events.err.txt](https://github.com/docker/for-win/files/6533780/events.err.txt)
[diagnostics.log](https://github.com/docker/for-win/files/6533781/diagnostics.log)

I'm stuck
