### ISSUE TITLE
Cancellation token triggered before we finished reading from the stream.

### ISSUE THREAD

**Issue by louagej** [docker/for-win#11293]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [V] I have uploaded Diagnostics
  - Diagnostics ID: BC63EC2F-5CE4-4FCE-8582-8B35D93217C6/20210525072223

### Actual behavior

Docker doesn't start anymore

### Expected behavior

Docker to start

### Information

  - Windows Version: 20H2
  - Docker Desktop Version: 3.3.3.64133
  - WSL2 or Hyper-V backend?  Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: VM

### Steps to reproduce the behavior

  1. With the same Windows Version and Docker version, restarting Docker

**Comment by cwilby** [comment]
Also experiencing the same issue - 799C8AD2-D217-4AB1-AECE-FA9BFB5DA7F2/20210611155022

**Comment by cwilby** [comment]
Haven't been able to get any docker containers back up and running due to this..

Google-fu brings up "Re-install docker desktop" or "downgrade to Hyper-V"

a) I don't want to lose the performance benefits of WSL2.
b) I'm wary of re-installing docker desktop as I don't want to lose the `docker-desktop-data` distribution contents.

**Comment by cwilby** [comment]
Managed to start the containers again. It was one of:

- Hypervisor may not have been running as I had [installed Virtualbox](https://docs.docker.com/docker-for-windows/troubleshoot/#hypervisor-enabled-at-windows-startup).  I ran `bcdedit /set hypervisorlaunchtype auto` and restarted windows.

- I also did this:
```
wsl --shutdown
wsl --unregister docker-desktop
shutdown -r -t 1
```

The hypervisor seems more likely as I had tried the second solution multiple times.

**Comment by edwardtew** [comment]
I am also seeing this issue 
Docker Desktop 3.5.2
Windows 10 Enterprise
Diagnostics log **44079AE5-0EFB-42CB-B39A-64D810FACE74/20210715010529**

**Comment by elijahmontenegro** [comment]
Is there no solution to this? I've tried everything.

**Comment by ramanmittal** [comment]
Also facing the same issue. It has taken 2 days.

**Comment by edwardtew** [comment]
Within the .docker folder the "contexts" folder seems to be getting corrupted. 
If I delete it, it gets re-created as a folder and then some point later gets changed again to a junction so that the WSL back end can access it (I think) when this happens the docker engine cannot be restarted.

The settings cannot be changed through the desktop app either.

**Comment by elijahmontenegro** [comment]
Apparently, 3.5.1 is very unstable according to some people and I found in this issue the fix was either to downgrade or upgrade to a pre-release version of 3.6.0. I did just that, and now Docker runs and no cancellation token error.  Below is the post that resolved this issue for me.

https://github.com/docker/for-win/issues/11601#issuecomment-879464955
> @voycey I've got a developer build which should work around this problem: https://desktop-stage.docker.com/win/stable/amd64/66555/Docker%20Desktop%20Installer.exe In this build the "invalid character" error is logged but isn't fatal, so hopefully the app should start. This build will also add some `docker context inspect` commands to the diagnostics.
> 
> If you get a chance to try it, let me know if it helps! If you still have problems, please upload a fresh set of diagnostics and quote the ID here. It might also help as a workaround to take a backup of `.docker` in your home directory and then delete it, in case there are some corrupt files in there.

**Comment by strarsis** [comment]
+1, same issue. Docker can't be used right now. I can faintly remember that I updated the NVIDIA drivers. But can this really be the cause for this? Hyper-V works fine, BlueStacks (also Hyper-V) work as usual, no issues. Can the GPU driver really be so much connected to Docker that it hinders its startup?

**Comment by strarsis** [comment]
@djs55, @elijahmontenegro: Yes! Installing this beta/staging/dev release of Docker for Desktop (https://github.com/docker/for-win/issues/11601#issuecomment-879464955) fixed the issue, it is starting up correctly now.

**Comment by dan-silver** [comment]
Interesting.. I installed docker desktop version 3.6.0 provided by @djs55 and I'm still seeing the error that started this week. Is there a way to view more logs to see if this is the same issue?
![image](https://user-images.githubusercontent.com/1266893/126706573-9c77e2af-9d78-4898-b57a-3a735ed91cff.png)

**Comment by strarsis** [comment]
@dan-silver: I also completely purged Docker for Desktop, maybe this additional step is necessary?

**Comment by djs55** [comment]
@dan-silver there may be a problem like a circular symlink in $HOME/.docker/contexts. Perhaps try deleting that directory before trying a factory reset.

**Comment by franciscomesa** [comment]
> Its been a journey but I've found according to some the fix was either to downgrade or upgrade to a pre-release version.
> 
> I did just that, and now Docker runs with no error. Below is the post that resolved this issue for me.
> 
> Hope it helps.
> 
> [#11601 (comment)](https://github.com/docker/for-win/issues/11601#issuecomment-879464955)
> 
> > @voycey I've got a developer build which should work around this problem: https://desktop-stage.docker.com/win/stable/amd64/66555/Docker%20Desktop%20Installer.exe In this build the "invalid character" error is logged but isn't fatal, so hopefully the app should start. This build will also add some `docker context inspect` commands to the diagnostics.
> > If you get a chance to try it, let me know if it helps! If you still have problems, please upload a fresh set of diagnostics and quote the ID here. It might also help as a workaround to take a backup of `.docker` in your home directory and then delete it, in case there are some corrupt files in there.

Worked for me.

**Comment by xhava** [comment]
> 
> 
> Interesting.. I installed docker desktop version 3.6.0 provided by @djs55 and I'm still seeing the error that started this week. Is there a way to view more logs to see if this is the same issue?
> ![image](https://user-images.githubusercontent.com/1266893/126706573-9c77e2af-9d78-4898-b57a-3a735ed91cff.png)

same error here ;(

**Comment by zBugi** [comment]
I deleted the file $HOME/.docker/contexts and tried to make a factory reset and got an error: 050AAC60-D1B1-47AB-A9C2-604DBF8EFAAF/20210730070240

**Comment by pedrounes1** [comment]
> @dan-silver there may be a problem like a circular symlink in $HOME/.docker/contexts. Perhaps try deleting that directory before trying a factory reset.

This works for me. 

I had already tried to uninstall Docker and reinstall countless times, deleting docker from registry... Right now I was considering format my computer (again) only to solve this issue.

Thank you very much

**Comment by tolisset** [comment]
how do I delete the directory $HOME/.docker/contexts?

**Comment by pedrounes1** [comment]
> how do I delete the directory $HOME/.docker/contexts?

If you are using windows, you can find this folder on %USERPROFILE% (C:/Users/<your_username>)/.docker/contexts. It's a hidden folder.

**Comment by ericdmachado** [comment]
> > @dan-silver there may be a problem like a circular symlink in $HOME/.docker/contexts. Perhaps try deleting that directory before trying a factory reset.
> 
> This works for me.
> 
> I had already tried to uninstall Docker and reinstall countless times, deleting docker from registry... Right now I was considering format my computer (again) only to solve this issue.
> 
> Thank you very much

I was going the same way, but I created a new windows account and ran the docker and it worked. Then I understood that it was something in the settings. 

Tks @dan-silver

**Comment by goostleek** [comment]
I'm still struggling with the issue. None of the above suggestions worked for me.

Diagnostic id: `8CEC404D-0CFC-4E48-A514-943132D2D870/20210811132755`

**Comment by goostleek** [comment]
In my case, the issue was related to https://github.com/docker/for-win/issues/11601 and upgrading to 3.6.0 solved the problem for me 🎉.

**Comment by hellooops** [comment]
> @dan-silver there may be a problem like a circular symlink in $HOME/.docker/contexts. Perhaps try deleting that directory before trying a factory reset.

Just like you said, I renamed the context folder after the docker desktop is stopped, then restart it, everything got work again

**Comment by pranchan007** [comment]
This issue happens so frequently (Hyper V). Generally, after multiple attempt of restart, sometimes it works or a factory reset or data purge is required which is a pain as we lose entire project setup. I thought version 3.6.0 has addressed it, but doesn't look so.

@djs55 I could not find any symlink under <my_home_dir>/.docker/contexts, however next time this happens, I'll give it a try. Thanks for the suggestion. However, still wondering if this permanently fixes the issue or we may need to do it again.

**Comment by Haider-Ali-Dev** [comment]
Please help I cannot reset or do anything, I get this error on windows 10
```
System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\ali07\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: The system cannot find the file specified.

```

**Comment by adrianosantostreina** [comment]
It's necessary  to choose: Docker Desktop or VirtualBox, both does not works in same environment.

If you enable Hyper-V, VirtualBox crash and Docker works, else disable Hyper-V then VirtualBox works and Docker Desktop crash.

**Comment by pedrounes1** [comment]
> It's necessary to choose: Docker Desktop or VirtualBox, both does not works in same environment.
> 
> If you enable Hyper-V, VirtualBox crash and Docker works, else disable Hyper-V then VirtualBox works and Docker Desktop crash.

First of all: I don't use VirtualBox, so I have 0 property to talk about.

I had read about it in the past and according to [this](https://docs.oracle.com/en/virtualization/virtualbox/6.0/admin/hyperv-support.html) and [this](https://us.informatiweb.net/tutorials/it/virtualization/virtualbox-use-virtualbox-and-hyper-v-at-the-same-time.html) you can use VirtualBox 6.0 on Win10 with Hyper-V enabled.

**Comment by adrianosantostreina** [comment]
I'm sorry, I didn't mean to cause discomfort, that wasn't the intention. Just inform. An excellent week for you.
