### ISSUE TITLE
"No access token in response" when login in with MFA in Docker Desktop (Windows)

### ISSUE THREAD

**Issue by yooakim** [docker/for-win#11306]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: As I am unable to login to Docker Desktop I am not able to submit diagnostics

### Actual behavior
When I try to login with my Docker hub account with MFA enabled, Docker Desktop (Windows) shows "No access token in response" 
![image](https://user-images.githubusercontent.com/862546/119640147-99936b80-be18-11eb-8dbf-a17882445507.png)

### Expected behavior
I should be able to login using my Docker Hub account and MFA.

### Information

I can use the account to login to the Docker Hub website, so the account, password and MFA token works. 

  - Windows Version: Microsoft Windows 10 Pro, 10.0.19043 Build 19043
  - Docker Desktop Version: 3.3.3
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No
  - Docker version:

      Client:
       Cloud integration: 1.0.14
       Version:           20.10.6
       API version:       1.41
       Go version:        go1.16.3
       Git commit:        370c289
       Built:             Fri Apr  9 22:49:36 2021
       OS/Arch:           windows/amd64
       Context:           default
       Experimental:      true
      
      Server: Docker Engine - Community
       Engine:
        Version:          20.10.6
        API version:      1.41 (minimum version 1.12)
        Go version:       go1.13.15
        Git commit:       8728dd2
        Built:            Fri Apr  9 22:44:56 2021
        OS/Arch:          linux/amd64
        Experimental:     false
       containerd:
        Version:          1.4.4
        GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
       runc:
        Version:          1.0.0-rc93
        GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
       docker-init:
        Version:          0.19.0
        GitCommit:        de40ad0
      

### Steps to reproduce the behavior

  1. Start Docker Desktop
  2. Login

**Comment by stephen-turner** [comment]
Are you still seeing this? We thought we'd fixed it a couple of days ago.

**Comment by stephen-turner** [comment]
Oh yes, I can reproduce it, it looks like it's come back. We'll get it sorted.

**Comment by yooakim** [comment]
Sad to say that the issue is still there today @stephen-turner - I just teste again and the issue persist.

**Comment by yooakim** [comment]
A related question, if I may?

Do you have any plans to support hardware tokens such as Yubico YubiKeys? (FIDO U2F)?

**Comment by stephen-turner** [comment]
On your other question, we have a request for this on our roadmap repo: docker/roadmap#108. Feel free to give it a 👍, it hasn't got much traction yet.

**Comment by yooakim** [comment]
Thanks @stephen-turner , I'm happily logged in again.
