### ISSUE TITLE
After Windows reboot, links to docker in /mnt/wsl/docker-desktop/cli-tools disappear

### ISSUE THREAD

**Issue by rfgunion** [docker/for-win#11308]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3FE70423-E0FA-4001-BCCF-2B0D0ACD831A/20210526141919

### Actual behavior
I am unable to run docker commands in WSL2 after a Windows system reboot

### Expected behavior
I should be able to run docker commands

### Information
I had Docker Desktop working with my Ubuntu 20.04 WSL2 distribution.  I rebooted the Windows system, and when it came back up I found I was unable to run any docker commands from the Ubuntu shell:
`docker ps

The command 'docker' could not be found in this WSL 2 distro.
We recommend to activate the WSL integration in Docker Desktop settings.

See https://docs.docker.com/docker-for-windows/wsl/ for details.
`

I found this was because the directory /mnt/wsl/docker-desktop/cli-tools was empty.  Issue [7836](https://github.com/docker/for-win/issues/7836) appears similar, however it was closed because the issue was supposedly fixed in version 2.4.0; I am running 3.3.3.64133.

I'm not doing anything complex, just attempting to run containers (honestly, Docker hasn't worked long enough on this machine to try anything much more complicated than `docker run centos:7`).  The only mounts I'm specifying are:
`-v /home:/home -v /sys/fs/cgroup:/sys/fs/cgroup:ro`

After restarting Docker Desktop, it crashed and produced the diagnostics ID listed above.  I tried "Reset to factory defaults", and it crashed again with this diagnostic ID: 3FE70423-E0FA-4001-BCCF-2B0D0ACD831A/20210526143104

  - Windows Version: 1909 Windows 10 Enterprise
  - Docker Desktop Version: 3.3.3.64133
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No, this is on a laptop

**Comment by mswietochowski** [comment]
I just had a similar issue, Docker Desktop showing no containers, freezing in settings, WSL can't find `docker` CLI. I did not try restarting just the Docker Desktop, but found this workaround:

1. From Windows Task Manager I stopped every Docker-thing: Docker Desktop, Docker Desktop Backend, Docker.Service. 
2. Started Docker Desktop app. When it prompted about starting Docker.Serivce, I allowed. There was UAC prompt for starting the service.
3. Problem gone.
