### ISSUE TITLE
Docker Desktop settings is pending and it is not possible to restart

### ISSUE THREAD

**Issue by Agos88** [docker/for-win#11304]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: AC0BAF0A-C1F6-43A4-8D5D-0596F96BF6FA/20210526074007

### Information

  - Windows Version: Windows 10 Enterprise 10.0.19041
  - Docker Desktop Version: 
  - WSL2 or Hyper-V backend? WSL1 
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. Open Docker Desktop 
  2. Docker stopped
  3. Settings pending

**Comment by micdenny** [comment]
- Diagnostics ID: 73F66CE1-EECA-43F5-90A9-C85CFAF20EE3/20210526095259

seams the same problem I'm having:

![image](https://user-images.githubusercontent.com/1633595/119639840-47eae100-be18-11eb-8740-67c6c2f99ae2.png)

this suddenly happened today, after a reboot, I've already tried to uninstall completely, removing all the docker folder in appdata, programdata, ecc... also removed some docker registry key, but nothing, even with a clean installation, docker won't start

I have WSL2 and is working fine with a couple of distro (ubuntu & kali).

I see this process running (along with `Docker Desktop.exe`):

![image](https://user-images.githubusercontent.com/1633595/119640293-c182cf00-be18-11eb-93ca-c4c086f7d5b8.png)

### Information

  - Windows Version: **Microsoft Windows 10 Pro 10.0.19042**
  - Docker Desktop Version: **3.3.3**
  - WSL2 or Hyper-V backend?  **WSL2**
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: **No**

**Comment by micdenny** [comment]
here I found a stable workaround https://github.com/docker/for-win/issues/11302#issuecomment-848534447

**Comment by Agos88** [comment]
thanks @micdenny at the moment I downgrade to version 2.5.0.1 and it's working fine

**Comment by kingsumos** [comment]
Try running vpn-bridge manually, check https://github.com/docker/for-win/issues/11300#issuecomment-848183873
