### ISSUE TITLE
Docker engine cannot be started after rebooting PC unless it is reset to factory defaults

### ISSUE THREAD

**Issue by FLAMESpl** [docker/for-win#11303]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 0B6044BC-B6EC-4087-B010-005B1A93D25B/20210526062257

### Actual behavior
  - Docker engine cannot be started after rebooting PC unless it is reset to factory defaults

### Expected behavior
  - Docker engine can be started without resetting to factory defaults

### Information
  - It is reproducible every time
  - This problem appeared after I updated from version 2.x to 3.3.3
  - Windows version 1909
  - Hyper-V backend
  - Windows is NOT virtualized

**Comment by icellus** [comment]
me too

**Comment by FLAMESpl** [comment]
bump

**Comment by FLAMESpl** [comment]
bump
