### ISSUE TITLE
Docker Engine fails to start

### ISSUE THREAD

**Issue by kingsumos** [docker/for-win#11300]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 451E4284-F706-484F-B3D8-C1C10764534B/20210525180941

### Actual behavior
Docker Engine not starting up

### Expected behavior
Docker Engine up and running

### Information

  - Windows Version: Version	10.0.19041 Build 19041
  - Docker Desktop Version: 3.3.3
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

Problem suddenly starts happening for no reason, tried to reinstall Docker but not luck.
Log shows VpnKitBridge error:
[15:01:39.878][VpnKitBridge      ][Error  ] Process died
also, log output is full with errors like blow:
[15:01:55.685][LinuxWSL2Engine   ][Info   ] GET failed with Get "http://unix/forwards/list": dial unix /run/host-services/backend.sock: connect: no such file or directory
[15:01:55.985][LinuxWSL2Engine   ][Info   ] GET failed with Get "http://unix/forwards/list": dial unix /run/host-services/backend.sock: connect: no such file or directory
[15:01:56.286][LinuxWSL2Engine   ][Info   ] GET failed with Get "http://unix/forwards/list": dial unix /run/host-services/backend.sock: connect: no such file or directory
[15:01:56.587][LinuxWSL2Engine   ][Info   ] GET failed with Get "http://unix/forwards/list": dial unix /run/host-services/backend.sock: connect: no such file or directory
[15:01:56.889][LinuxWSL2Engine   ][Info   ] GET failed with Get "http://unix/forwards/list": dial unix /run/host-services/backend.sock: connect: no such file or directory

### Steps to reproduce the behavior

Start / Restart Docker... it never starts

The "vpnkit-bridge.exe.log" log file shows the following error:

time="2021-05-31T08:22:35-03:00" level=info msg="[C:\\Program Files\\Docker\\Docker\\resources\\vpnkit-bridge.exe --disable ssh-auth,osxfs-data,transfused,filesystem-event,filesystem-test,http-proxy-control --addr stdio --wsl-distro docker-desktop host]"
time="2021-05-31T08:22:35-03:00" level=info msg="pid: 19256; globalOpts: addr=stdio, bootstrapHost=gateway.docker.internal, useKernelCmdline=false, wslDistro=docker-desktop, verbose=false, pidFile=, suffix=, only=, disable=ssh-auth,osxfs-data,transfused,filesystem-event,filesystem-test,http-proxy-control"
**time="2021-05-31T08:22:35-03:00" level=fatal msg="read |0: file already closed"
goroutine 1 [running]:
main.main()
	C:/workspaces/3.3.x/src/github.com/docker/pinata/common/cmd/vpnkit-bridge/main.go:51 +0x5b1**

WORKAROUND:
- manually start vpnkit-bridge.exe using a command prompt, see also https://github.com/docker/for-win/issues/11300#issuecomment-848183873

**Comment by kingsumos** [comment]
The docker engine starts If I manually run vpnkit-bridge.exe (by opening a command prompt the  run "C:\\Program Files\\Docker\\Docker\\resources\\vpnkit-bridge.exe" --disable ssh-auth,osxfs-data,transfused,filesystem-event,filesystem-test,http-proxy-control --addr stdio --wsl-distro docker-desktop host

Below is the vpnkit-bridge.exe command output

`Microsoft Windows [Version 10.0.19041.985]
(c) Microsoft Corporation. All rights reserved.

C:\Users\A477336>C:\\Program Files\\Docker\\Docker\\resources\\vpnkit-bridge.exe --disable ssh-auth,osxfs-data,transfused,filesystem-event,filesystem-test,http-proxy-control --addr stdio --wsl-distro docker-desktop host
'C:\\Program' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\A477336>"C:\\Program Files\\Docker\\Docker\\resources\\vpnkit-bridge.exe" --disable ssh-auth,osxfs-data,transfused,filesystem-event,filesystem-test,http-proxy-control --addr stdio --wsl-distro docker-desktop host
time="2021-05-25T15:58:36-03:00" level=info msg="[C:\\\\Program Files\\\\Docker\\\\Docker\\\\resources\\\\vpnkit-bridge.exe --disable ssh-auth,osxfs-data,transfused,filesystem-event,filesystem-test,http-proxy-control --addr stdio --wsl-distro docker-desktop host]"
time="2021-05-25T15:58:36-03:00" level=info msg="pid: 11508; globalOpts: addr=stdio, bootstrapHost=gateway.docker.internal, useKernelCmdline=false, wslDistro=docker-desktop, verbose=false, pidFile=, suffix=, only=, disable=ssh-auth,osxfs-data,transfused,filesystem-event,filesystem-test,http-proxy-control"
INFO[0000] [/usr/bin/vpnkit-bridge --disable ssh-auth,osxfs-data,transfused,filesystem-event,filesystem-test,http-proxy-control --pid-file=/run/vpnkit-bridge.pid --addr=stdio guest]
INFO[0000] pid: 101; globalOpts: addr=stdio, bootstrapHost=gateway.docker.internal, useKernelCmdline=false, wslDistro=, verbose=false, pidFile=/run/vpnkit-bridge.pid, suffix=, only=, disable=ssh-auth,osxfs-data,transfused,filesystem-event,filesystem-test,http-proxy-control
INFO[0000] guest: backend: polling for remote service
INFO[0000] guest: socks: polling for remote service
INFO[0000] guest: dns/tcp: polling for remote service
INFO[0000] guest: docker-proxy: polling for remote service
INFO[0000] guest: dns/udp: polling for remote service
INFO[0000] guest: gui: polling for remote service
INFO[0000] guest: filesystem: polling for remote service
INFO[0000] guest: vpnkit: polling for remote service
INFO[0000] guest: vpnkit-data: polling for remote service
INFO[0000] guest: ntp: polling for remote service
time="2021-05-25T15:58:36-03:00" level=info msg="windows: docker: polling for remote service"
                                                                                             time="2021-05-25T15:58:36-03:00" level=info msg="windows: debug-shell: polling for remote service"
                                                                       INFO[0000] guest: backend: remote service is responding, publishing locally on /run/host-services/backend.sock
INFO[0000] guest: dns/tcp: remote service is responding, publishing locally on /run/host-services/dns.tcp.sock
INFO[0000] guest: socks: remote service is responding, publishing locally on /run/host-services/socks.sock
INFO[0000] guest: docker-proxy: remote service is responding, publishing locally on /run/host-services/docker.proxy.sock
INFO[0000] guest: dns/udp: remote service is responding, publishing locally on /run/host-services/dns.udp.sock
INFO[0000] guest: gui: remote service is responding, publishing locally on /run/host-services/gui-api.sock
time="2021-05-25T15:58:36-03:00" level=info msg="windows: wsl2-cross-distro-service: polling for remote service"
                                                                                                                INFO[0000] guest: filesystem: remote service is responding, publishing locally on /run/host-services/filesystem.sock
time="2021-05-25T15:58:36-03:00" level=info msg="windows: diagnosticd: polling for remote service"
                                                                                                  INFO[0000] guest: vpnkit: remote service is responding, publishing locally on /run/host-services/vpnkit.sock
INFO[0000] guest: vpnkit-data: remote service is responding, publishing locally on /run/host-services/vpnkit-data.sock
INFO[0000] guest: ntp: remote service is responding, publishing locally on /run/host-services/ntp.udp.sock
INFO[0000] guest: all remote services are running
time="2021-05-25T15:58:36-03:00" level=info msg="windows: volume-contents: polling for remote service"
                                                                                                      time="2021-05-25T15:58:36-03:00" level=info msg="windows: lifecycle-server: polling for remote service"
                                                                                     time="2021-05-25T15:58:36-03:00" level=info msg="windows: mutagen: polling for remote service"
                                                           time="2021-05-25T15:58:36-03:00" level=info msg="windows: wsl2-bootstrap-expose-ports: polling for remote service"
                                                     time="2021-05-25T15:58:36-03:00" level=info msg="windows: log: polling for remote service"
                       time="2021-05-25T15:58:36-03:00" level=info msg="windows: wsl2-cross-distro-service: remote service is responding, publishing locally on \\\\.\\pipe\\dockerWSLCrossDistroService"
                                                                                 time="2021-05-25T15:58:36-03:00" level=info msg="windows: wsl2-bootstrap-expose-ports: remote service is responding, publishing locally on \\\\.\\pipe\\dockerWsl2BootstrapExposePorts"
                        time="2021-05-25T15:58:36-03:00" level=info msg="windows: log: remote service is responding, publishing locally on \\\\.\\pipe\\dockerMemlogdq"
                                               time="2021-05-25T15:58:38-03:00" level=info msg="windows: debug-shell: remote service is responding, publishing locally on \\\\.\\pipe\\dockerDebugShell"
                                                                                time="2021-05-25T15:58:38-03:00" level=info msg="windows: diagnosticd: remote service is responding, publishing locally on \\\\.\\pipe\\dockerDiagnosticd"
                                                                                                                  time="2021-05-25T15:58:38-03:00" level=info msg="windows: mutagen: remote service is responding, publishing locally on \\\\.\\pipe\\dockerMutagen"
                    time="2021-05-25T15:58:38-03:00" level=info msg="windows: lifecycle-server: remote service is responding, publishing locally on \\\\.\\pipe\\dockerLifecycleServer"
                                                               time="2021-05-25T15:58:38-03:00" level=info msg="windows: volume-contents: remote service is responding, publishing locally on \\\\.\\pipe\\volumeContents"
                                                                                                  time="2021-05-25T15:58:46-03:00" level=info msg="windows: still waiting for docker after 10.0028817s"
                                                                               time="2021-05-25T15:58:47-03:00" level=info msg="windows: docker: remote service is responding, publishing locally on \\\\.\\pipe\\docker_engine_linux"
                                                                                                              time="2021-05-25T15:58:47-03:00" level=info msg="windows: all remote services are running"
`

**Comment by kingsumos** [comment]
Anyone knows where vpnkit-bridge.exe logs are stored so I can investigate a little b more this issue?

**Comment by FLAMESpl** [comment]
@kingsumos 
It is my output after running above command:

time="2021-05-31T12:24:44+02:00" level=info msg="[C:\\Program Files\\Docker\\Docker\\resources\\vpnkit-bridge.exe --disable ssh-auth,osxfs-data,transfused,filesystem-event,filesystem-test,http-proxy-control --addr stdio --wsl-distro docker-desktop host]"
time="2021-05-31T12:24:44+02:00" level=info msg="pid: 13164; globalOpts: addr=stdio, bootstrapHost=gateway.docker.internal, useKernelCmdline=false, wslDistro=docker-desktop, verbose=false, pidFile=, suffix=, only=, disable=ssh-auth,osxfs-data,transfused,filesystem-event,filesystem-test,http-proxy-control"
Error: not a connection to a mulitplexer; received bad magic string 'There is no distribution w'
time="2021-05-31T12:24:44+02:00" level=fatal msg="not a connection to a mulitplexer; received bad magic string 'T\x00h\x00e\x00r\x00e\x00 \x00i\x00s\x00 \x00n\x00o\x00 \x00d\x00i\x00s\x00t\x00r\x00i\x00b\x00u\x00t\x00i\x00o\x00n\x00 \x00w\x00'"

I am using Hyper-V for docker

**Comment by kingsumos** [comment]
> @kingsumos
> It is my output after running above command:
> 
> time="2021-05-31T12:24:44+02:00" level=info msg="[C:\Program Files\Docker\Docker\resources\vpnkit-bridge.exe --disable ssh-auth,osxfs-data,transfused,filesystem-event,filesystem-test,http-proxy-control --addr stdio --wsl-distro docker-desktop host]"
> time="2021-05-31T12:24:44+02:00" level=info msg="pid: 13164; globalOpts: addr=stdio, bootstrapHost=gateway.docker.internal, useKernelCmdline=false, wslDistro=docker-desktop, verbose=false, pidFile=, suffix=, only=, disable=ssh-auth,osxfs-data,transfused,filesystem-event,filesystem-test,http-proxy-control"
> Error: not a connection to a mulitplexer; received bad magic string 'There is no distribution w'
> time="2021-05-31T12:24:44+02:00" level=fatal msg="not a connection to a mulitplexer; received bad magic string 'T\x00h\x00e\x00r\x00e\x00 \x00i\x00s\x00 \x00n\x00o\x00 \x00d\x00i\x00s\x00t\x00r\x00i\x00b\x00u\x00t\x00i\x00o\x00n\x00 \x00w\x00'"
> 
> I am using Hyper-V for docker

For your case the command line is different, see I have a "--wsl-distro" parameter. For Hyper-V this parameter makes no sense at all, the correct parameters are shown in the "vpnkit-bridge.exe.log" log file (find this file in %APPDATA%/Roaming\Docker\log\host).
OFC trigger Restart Docker to update the log file and discover the correct parameters, once you find this info follow this way:
1. In docker menu click 'Docker Docker...'
2. Wait more or less 1 minute
3. Start the vpnkit-bridge.exe command line
4. If the Docker Dashboard is opened, close it and then reopen (to see if Docker can list the containers/images)

**Comment by kingsumos** [comment]
BTW, this is why Docker Engine isn't starting:

time="2021-05-31T08:22:35-03:00" level=info msg="[C:\\Program Files\\Docker\\Docker\\resources\\vpnkit-bridge.exe --disable ssh-auth,osxfs-data,transfused,filesystem-event,filesystem-test,http-proxy-control --addr stdio --wsl-distro docker-desktop host]"
time="2021-05-31T08:22:35-03:00" level=info msg="pid: 19256; globalOpts: addr=stdio, bootstrapHost=gateway.docker.internal, useKernelCmdline=false, wslDistro=docker-desktop, verbose=false, pidFile=, suffix=, only=, disable=ssh-auth,osxfs-data,transfused,filesystem-event,filesystem-test,http-proxy-control"
**time="2021-05-31T08:22:35-03:00" level=fatal msg="read |0: file already closed"
goroutine 1 [running]:
main.main()
	C:/workspaces/3.3.x/src/github.com/docker/pinata/common/cmd/vpnkit-bridge/main.go:51 +0x5b1**

**Comment by kingsumos** [comment]
some random comment

**Comment by kingsumos** [comment]
Problem still there after updating to v3.4.0 (65384)
vpn-bridge.exe is crashing, log output:
C:\Users\xxxxxxx\AppData\Roaming\Docker\log\host\vpnkit-bridge.exe.log

time="2021-05-31T08:22:35-03:00" level=fatal msg="read |0: file already closed"
goroutine 1 [running]:
main.main()
	C:/workspaces/3.3.x/src/github.com/docker/pinata/common/cmd/vpnkit-bridge/main.go:51 +0x5b1

**Comment by kingsumos** [comment]
The problem is caused by the "vpnkit-bridge.exe" Working Directory with must be set to %HOMEPATH%
Looks like vpnkit-bridge.exe is started in the wrong directory! 

Workaround:
1. Rename "vpnkit-bridge.exe" to "vpnkit-bridge-orig.exe"  (C:\Program Files\Docker\Docker\resources\)
2. Compile the attached autohotkey script as "vpnkit-bridge.exe"
3. Copy the new "vpnkit-bridge.exe" to C:\Program Files\Docker\Docker\resources\
[vpnkit-bridge.txt](https://github.com/docker/for-win/files/6650534/vpnkit-bridge.txt)

**Comment by kingsumos** [comment]
REMARKS:
- this issue is related to vpn-bridge.exe failing to start due to wrong directory, reinstalling docker doesn't solves the issue!
- it happens in v3.3.4 as well
- the issue isn't related to missing wsl distro, all required distros are up and running:

C:\Users\Sumo>wsl --list
Windows Subsystem for Linux Distributions:
openSUSE-Leap-15-1 (Default)
openSUSE-Leap-15.2
docker-desktop-data
docker-desktop

**Comment by kingsumos** [comment]
Someone can please confirm if this is a known problem and if I can just wait for a fix? Maybe @stephen-turner?

**Comment by kingsumos** [comment]
Several people reporting docker startup issues day by day, could their issues be related to %HOMEPATH% as described above?

**Comment by kingsumos** [comment]
issue is still there, docker v2.5.2

**Comment by kingsumos** [comment]
bump

**Comment by kingsumos** [comment]
only solution for this issue is still the one described here:
https://github.com/docker/for-win/issues/11300#issuecomment-848183873 
tested in v3.5.2
or
automate the vpnbridge launch using autohotkey

**Comment by kingsumos** [comment]
Same problem using v3.6.0
vpnbridge fails to start, needs to be stated on %HOMEPATH%

**Comment by rbluethl** [comment]
Getting the same error. Docker for Windows is so freaking unstable, it's a total headache. Need to reinstall literally every two weeks because of random, unsolvable errors. Now I'm getting exactly this... what is wrong with this tool?
