### ISSUE TITLE
Docker fails to start on login

### ISSUE THREAD

**Issue by acnicholls** [docker/for-win#11302]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 05F341A2-6DFF-444C-AA88-450E428B39DF/20210526014102

### Actual behavior
After Windows boot and login, Docker Notification Icon is only partially complete, and hovering over the icon makes it disappear.  Attempting to run `docker xxx` commands within WSL distro fail with `command not found`

### Expected behavior
Docker should run just fine after boot and login

### Information

  - Windows Version: Win10 Pro v21H1 OS Build: 19043.985
  - Docker Desktop Version: 3.3.3
  - WSL2 or Hyper-V backend?   WSL2 Ubuntu 20.04.2 LTS
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no
Issue started on May 11, 2021 after installing `Windows Update KB5003173` and `.NET Core 3.1.15 Security Update for x64 Client`.  Installing Win10 v21H1 on May 21, 2021 did not fix this issue.
  - looking at the Windows Application Log shows these two entries, everyday since May 11, 2021
```
Event ID: 1026
Source: .NET Runtime
Task Category: None
Application: Docker Desktop.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.UnauthorizedAccessException

Exception Info: Docker.Core.HttpBadResponseException
   at Docker.Core.Logging.HttpClientExceptionInterceptor+<InterceptResponseAsync>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Logging.LoggingMessageHandler+<SendAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Net.Http.HttpClient+<FinishSendAsyncBuffered>d__58.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Docker.Core.BackendAPI.BackendAPIClient+<UpdateHostsAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Docker.Core.TaskExtension+<Forget>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
```
Event ID: 1000
Source: Application Error
Task Category: (100)
Faulting application name: Docker Desktop.exe, version: 3.3.3.64133, time stamp: 0x89ea8de2
Faulting module name: KERNELBASE.dll, version: 10.0.19041.964, time stamp: 0x812662a7
Exception code: 0xe0434352
Fault offset: 0x0000000000034b89
Faulting process id: 0x470c
Faulting application start time: 0x01d7519c62861e6f
Faulting application path: C:\Program Files\Docker\Docker\Docker Desktop.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 06457583-5d1a-4068-b79c-f3e3b4f38dad
Faulting package full name: 
Faulting package-relative application ID: 
```

### Steps to reproduce the behavior
1) Boot Windows
2) Login
3) attempt to right-click the docker notification icon or start WSL CLI and enter any docker command

### Possibly related to
#11282 
#11292 
#11300

**Comment by petedev01** [comment]
I am not sure what changed recently with either Docker or Windows updates, but it looks like this is broken for a lot of us, given how many similar issues I see posted in the last day.

I don't see any errors in Event Viewer > Application log, like the ones you noted above. (Even after restarting the PC)
My log file shows errors from earlier today about failures to ping the backend and timing out, but that error seems to have stopped.  Now the Docker Desktop > Settings page is just hung on the spinning loading icon and I can't find an error anywhere.

**Comment by fatihdogmus** [comment]
I first downgraded to 3.2.2 which is the last working version for me, both 3.3.1 and 3.3.2 was broken. But I couldn't stay on 3.2.2 because automatic updates are forcing me to download 3.3.3(Thanks docker!). So I downgraded to 2.5.0.1, which is the last version that the forced automatic updates were not present. Everything seems to be fine, but I had to do one last data purge for everything to work. Now, there seems to be no problem and since there are no major changes from 2.5.0.1 to 3.3.3, and more importantly, it works, I think I'm going to stick on that version for a while 🙂

To donwload 2.5.0.1, you can find it in [here](https://docs.docker.com/docker-for-windows/release-notes/#docker-desktop-community-2501)

**Comment by FLAMESpl** [comment]
Considering forced update feature I think we can call 2.5.0.1 a latest stable version.

**Comment by kingsumos** [comment]
Try running vpn-bridge manually, check this: https://github.com/docker/for-win/issues/11300#issuecomment-848183873

**Comment by acnicholls** [comment]
> 
> 
> Try running vpn-bridge manually, check this: [#11300 (comment)](https://github.com/docker/for-win/issues/11300#issuecomment-848183873)

All I have to do is use the Start Menu's Docker Desktop icon and it all starts fine after that.  This is an unnecessarily complex workaround.  I even have the menu option pinned to start so I don't have to hunt for it.

**Comment by kingsumos** [comment]
> > Try running vpn-bridge manually, check this: [#11300 (comment)](https://github.com/docker/for-win/issues/11300#issuecomment-848183873)
> 
> All I have to do is use the Start Menu's Docker Desktop icon and it all starts fine after that. This is an unnecessarily complex workaround. I even have the menu option pinned to start so I don't have to hunt for it.

So it's clear this issue isn't related to #11300 
(it's not even a workaround)

I have suggested this because someone market #11300 as related/dup
