### ISSUE TITLE
Can not start Docker

### ISSUE THREAD

**Issue by nguyenthanhdam** [docker/for-win#11310]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:8A6E7FD9-F3E5-4CFE-9FC5-6E2F3F803FCC/20210527033031

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ag143** [comment]
I am also facing same issue, let me know which is stable docker version for windows 10
