### ISSUE TITLE
Im new to this plz help docker,kubernater and daremon is not stating !!!!

### ISSUE THREAD

**Issue by awfulsamz** [docker/for-win#11323]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 942D4C67-E467-47B4-B0F3-123B1EA3FE7C/20210528063104

### Actual behavior
error during connect: This error may indicate that the docker daemon is not running.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/create": open //./pipe/docker_engine: The system cannot find the file specified.

### Expected behavior
error during connect: This error may indicate that the docker daemon is not running.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/create": open //./pipe/docker_engine: The system cannot find the file specified.
### Information

  - Windows Version:  win10 home 64-bit operating system, x64-based processor
  - Docker Desktop Version: v20.10.6
  - WSL2 or Hyper-V backend?   wsl2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no
![Screenshot 2021-05-28 121500](https://user-images.githubusercontent.com/74722833/119941602-73073900-bfae-11eb-9aa4-4d1cd3b36a3e.png)
![Screenshot 2021-05-28 121620](https://user-images.githubusercontent.com/74722833/119941661-8914f980-bfae-11eb-949e-5aad8a8618cb.png)
![Screenshot 2021-05-28 121500](https://user-images.githubusercontent.com/74722833/119941699-929e6180-bfae-11eb-91a6-93a06d2b76d6.png)
![Screenshot 2021-05-28 121620](https://user-images.githubusercontent.com/74722833/119941704-93cf8e80-bfae-11eb-8463-638d1022cece.png)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
This error usually means that you haven't installed WSL 2 correctly, which Docker Desktop uses. Please follow Microsoft's instructions at https://aka.ms/wsl2-install. If it's set up correctly, then the command `wsl -l -v` should show a version 2 distro.
