### ISSUE TITLE
docker daemon is not ruining

### ISSUE THREAD

**Issue by onyidocker** [docker/for-win#1132]
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...
[docker file issues.docx](https://github.com/docker/for-win/files/1337018/docker.file.issues.docx)

**Comment by jasonbivins** [comment]
![image](https://user-images.githubusercontent.com/28021664/31039473-e1b3a022-a54b-11e7-92e8-f4fe77c02506.png)
