### ISSUE TITLE
Docker Deskto Fails to Start from Clean Install

### ISSUE THREAD

**Issue by allout58** [docker/for-win#11329]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 309E1695-C5DD-47A7-8C53-30F080B15213/20210528191957

### Actual behavior
Docker Desktop fails to start, not even bringing up the window most of the time. When the window does appear, an alert pops up saying Docker desktop ran into an issue and to restart Docker Desktop. Hovering over the alert closes the Docker Desktop window.

### Expected behavior
Docker desktop to function

### Information
  - Windows Version: 10.0.19042 Build 19042
  - Docker Desktop Version:  unknown, however just reinstalled, so should be latest
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

This just started occurring within the past several days, only noticed today but used docker maybe a week ago. I did install Oracle VirtualBox yesterday, however, on my previous computer, VirtualBox and Docker Desktop coexisted just fine.
I have restarted my computer several times, uninstalling both VirtualBox and Docker Desktop, then reinstalling Docker Desktop to no avail.

### Steps to reproduce the behavior

  1. Install Docker Desktop
  2. Open Docker Desktop

**Comment by kingsumos** [comment]
Check if this works:
https://github.com/docker/for-win/issues/11300#issuecomment-848183873

**Comment by allout58** [comment]
After booting my computer today after the weekend, Docker Desktop just _magically_ works, with no changes from me. I'll leave this open, as it seems like many other people are having the same issue, so maybe my diagnostic id will be useful.

**Comment by allout58** [comment]
On rebooting today, it started failing again. I'll try the thing in 11300

**Comment by kingsumos** [comment]
check if vpnkit-bridge.exe is failing for the same reason shown in #11300 , log file:
%APPDATA%\Roaming\Docker\log\host\vpnkit-bridge.exe.log

**Comment by allout58** [comment]
Looks like it's waiting on a bunch of things, I killed it after 2 minutes though
