### ISSUE TITLE
VPNKit is alerting via malwarebytes after latest update.  

### ISSUE THREAD

**Issue by DanRegalia** [docker/for-win#11337]
Just a quick question... I just updated, and now the vpnkit is throwing all kinds of errors... 
Trojan, Compromised, all RTP connections... and for the record, I don't have anything running in my docker right now.  Just thought I'd let y'all know and try to figure out why/where all these websites are, and why they are alerting via malware bytes.
![image](https://user-images.githubusercontent.com/32274594/120075457-ef5d5300-c066-11eb-8038-93a4223eb488.png)
![image](https://user-images.githubusercontent.com/32274594/120075471-fb491500-c066-11eb-8eb4-d0b6617f5e4e.png)
![image](https://user-images.githubusercontent.com/32274594/120075475-0308b980-c067-11eb-95f6-f180fe8fb222.png)
![image](https://user-images.githubusercontent.com/32274594/120075480-0bf98b00-c067-11eb-992f-6406d1c9c94f.png)

**Comment by StefanScherer** [comment]
Hi @DanRegalia 
Thanks for the heads-up. I've tried latest malwarebytes trial 4.4.0 with Docker Desktop 3.3.3 and couldn't see any threats detected.
I'm closing this ticket, but feel free to comment if there are any updates to share.
