### ISSUE TITLE
Docker Failed to Start on Windows 10 Pro

### ISSUE THREAD

**Issue by EricJiBest** [docker/for-win#1134]
### Expected behavior
Docker starts succesfully
### Actual behavior
Failed to start
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
     5B473853-B044-4DF3-AA8E-AD239E811C31/2017-09-27_10-59-26
  - a reproducible case if this is a bug, Dockerfiles FTW
     [log.txt](https://github.com/docker/for-win/files/1337675/log.txt)
  - page URL if this is a docs issue or the name of a man page
    n/a
  - host distribution and version (Windows version, build number, etc)
     Edition windows 10 pro
     Version 1703     
     OS Build 15063.632

### Steps to reproduce the behavior

  1. Download docker for windows stable version
  2. Install it on windows 10 pro. After it is done, and restart machine, Docker is failed to start.
  3. Below are the error info on the log file:
      [09:23:24.273][NamedPipeServer][Error  ] Unable to execute Start: Unable to launch process: 1260    
     at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings) in 
     C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 247
     at Docker.Backend.ContainerEngine.Linux.Start(Settings settings) in 
    C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 123
    at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in 
    C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
     at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in 
    C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

**Comment by SOftEngrAtta** [comment]
i am also facing this issue

**Comment by gmsantos** [comment]
It happens with me too. #1148

**Comment by DarkGhostHunter** [comment]
Same here.

**Comment by BrizzleRocker** [comment]
https://github.com/docker/for-win/issues/1075

**Comment by jasonbivins** [comment]
We pushed new versions last week to help with the startup issues, can you please try the latest Stable version and let me know if you still have problems?

**Comment by mchalep** [comment]
Same here.

**Comment by Maikel-Nait** [comment]
This fixed the issue for me
[Fix error managing Hyper-V Server 2012 R2 from Windows 10](https://community.spiceworks.com/how_to/122307-fix-error-managing-hyper-v-server-2012-r2-from-windows-10)
