### ISSUE TITLE
Docker daemon is not starting at all

### ISSUE THREAD

**Issue by Jigsaw5279** [docker/for-win#11353]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 156FEAE3-3BCC-4403-B72B-A4DF22996186/20210601072053

### Actual behavior

Docker daemon is not starting.
 - Icon in Taskbar shows the "off" icon
 - Settings will not load, restart option is disabled
 - Trying to start a container results in: docker: error during connect: This error may indicate that the docker daemon is not running.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/create": open //./pipe/docker_engine: Das System kann die angegebene Datei nicht finden. (System can not find the given file)

### Expected behavior

Docker starting up

### Information

If I understand the logs correctly, the last time the daemon started was before the update on May 3rd.
It's reproducible as that it persists after every restart. Did not try re-installing yet, as I don't want to lose data yet

  - Windows Version: Windows 10 Enterprise 1909 (Build 18363.1556)
  - Docker Desktop Version: 3.3.3
  - WSL2 or Hyper-V backend?  WSL2 
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Trying to start Docker

**Comment by Jigsaw5279** [comment]
Seems to be the same issue as #11350

**Comment by kingsumos** [comment]
check #11300

**Comment by kingsumos** [comment]
Yes, in your case 'docker-desktop' is missing... not sure if you can recover from this situation without loosing data.
(probably your containers are stored inside 'docker-desktop-data' distro, not sure)
