### ISSUE TITLE
Docker Desktop won't start after Windows restart (Windows Server 2019 & Hyper-V)

### ISSUE THREAD

**Issue by Mquirmbach** [docker/for-win#11355]
- [x ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 7F5B7DEA-4FF3-4BCA-9723-832C67E11448/20210601133128

### Actual behavior
Docker Desktop with Linux container not starting. Error: "Cancellation token triggered before we finished reading from the stream"

### Expected behavior
Docker Desktop starts with Linux containers.

### Information

  - Windows Version: Windows Server 2019
  - Docker Desktop Version: 3.3.3 (64133), Engine 20.10.6
  - WSL2 or Hyper-V backend?:  Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: yes

Hi!

We have Docker Desktop running on a Windows Server 2019-VM (it has to be a Windows Server machine in our use case, no desktop system allowed) on VMWare. Nested virtualization etc. is activated.
It worked without problems with version 2 of Docker Desktop. But since we upgraded to Version 3 Docker won't start after it was stopped.
When I freshly install Docker Desktop and load my images everything works. After that when we have to restart the Windows host Docker won't start again. The error message is "Cancellation token triggered before we finished reading from the stream".
The only thing that works so far is to completely re-install Docker Desktop. This is driving me crazy as I cannot figure out what the problem might be.

Some more peculiar things I noticed:
 - The Docker Desktop Backend Service won't start at all if the Windows Server has no internet connection (which it normally doesn't have).
 - The Backend Service doesn't start on it's own when the Windows Server host is restarted. I have to start it myself.
 - When the underlying Hyper-V VM "DockerDesktopVM" starts I see a lot of "Loaded bpfilter_umh pid XXXX write fail -32" -errors in it's boot screen. Than exactly after 112 seconds it shuts down and I get the Docker Desktop error message mentioned above.
 - After the installation of Docker Desktop the Windows Host has a virtual network "vEthernet (nat)" created. But this network disappears after a couple of days. Is that only needed for Docker Desktop with Windows containers?

I already tried to just delete the Hyper-V VM, manually create the "vEthernet (nat)"-network and to disable the "control flow guard (CFG)" on vmcompute.exe as mentioned [here](https://github.com/docker/for-win/issues/3440)... To no avail..!
 
Any help is much appreciated! I don't understand why it works right after install but not a couple of days later when we restart the host for maintenance.
Many thanks in advance!

**Comment by Mquirmbach** [comment]
Nobody's got any ideas how to solve this issue? :(

**Comment by jahanarun** [comment]
I am surprised that you got Docker Desktop installed on Server edition. 
From what I understood, DD is supported only for Windows 10.

**Comment by Mquirmbach** [comment]
Hi, thanks for your answer!
Well, DD installs and runs without any problems on Windows Server 2019 (which in itself is based on Windows 10 1809). So that's no deal-breaker, and I don't see why it should be one.
But, all of the sudden, after a couple of days (I don't know exactly how long it takes), I won't start anymore. Once stopped, DD won't restart. I have to install it all over again.
Does nobody know why or what the error messages mean ("Cancellation token triggered before we finished reading from the stream")?

**Comment by jahanarun** [comment]
Cancellation token is something that is used in asynchronous programming using dotnet. 
Maybe some pieces of DD are written in dotnet. Cancellation token is typically sent by the managing thread to stop a long-running worker thread.

It's difficult to debug without actually seeing the issue.
I will try installing in Server 2019 and see if I can recreate it.

**Comment by Mquirmbach** [comment]
Hi Everyone!
Any news on this? Thanks!
