### ISSUE TITLE
Most Windows opened by Docker cannot be Minmized

### ISSUE THREAD

**Issue by fourpastmidnight** [docker/for-win#1135]
### Expected behavior
Standard Windows window behavior: the ability to (at least) minimize/restore windows.

### Actual behavior
Only a Close button is available. This does not follow good Windows UI/UX guidelines.

### Desired Outcome
Allow Docker windows to be minimized, such as the Error and Docker Update windows.

**Comment by jasonbivins** [comment]
Hi @fourpastmidnight 

I updated the current enhancement request with your comments.  Thanks!

**Comment by fourpastmidnight** [comment]
Thank you. I searched for something but didn't find anything! I look forward to improvements!!
