### ISSUE TITLE
Installing version 3.3.3 leads to crash on start

### ISSUE THREAD

**Issue by ManfredLange** [docker/for-win#11350]
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: BD5A15A8-2B44-443D-91BC-C2B67188BF92/20210531200910

### Actual behavior

I had version 3.2.2 of Docker Desktop for Windows installed. It prompted me in the last few days to upgrade to version 3.3.3. I accepted the upgrade several times but it never went ahead for no apparent reason.

I then downloaded the installer for version 3.3.3 manually and started it manually as well. It went as usual except that at the end Docker Desktop for Windows reported an error "Docker Desktop WSL distro stopped" with the additional info of "WSL distro stopped while waiting for Lifecycle server." Apparently it cannot find the file `docker-wsl-cli.iso` on the mount from C-drive. 

I have attached the entire error output as a text file to this issue in case this is not included in the diagnostics. I've been using WSL2 for quite some time and it ran very stable until this issue. I suspect this to be either a one-off (to be determined) or a rather small thing that causes it.

### Expected behavior

An upgrade with default settings should not lead to an error.

### Information

  - Windows Version: Microsoft Windows 10 Pro, version 10.0.19042 Build 19042.
  - Docker Desktop Version: 3.3.3
  - WSL2 or Hyper-V backend? WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no
  - Is it reproducible? I don't know yet, I'll amend this report if there are further observations that may be relevant
  - Is the problem new? yes, never seen before
  - Did the problem appear with an update? yes, when upgrading to 3.3.3

### Steps to reproduce the behavior

  1. Uninstall prior Docker Desktop for Windows version
  2. Install version 3.3.3 of Docker Desktop for Windows
  3. Same error occurs.

**Comment by ManfredLange** [comment]
Further to this: When I run the command
```
wsl - l --verbose
```
only `docker-desktop-data` is shown after the upgrade to 3.3.3.

From memory I believe there were two Docker related entries, one for the data and one for the engine.

**Comment by ManfredLange** [comment]
I've uploaded another crash report for this issue with diagnostic id BD5A15A8-2B44-443D-91BC-C2B67188BF92/20210531204715

**Comment by ManfredLange** [comment]
In a further attempt to resolve this issue, the following steps helped in my case:

1. Uninstall Docker Desktop for Windows
2. Reboot Windows
3. Install Docker Desktop for Windows version 3.3.3

It appears as if something in the upgrade process is not quite right as the reboot seems to have made a difference. Without the reboot Docker crashed because it could find the file `docker-wsl-cli.iso` even though it is reported as being extraced from the installer package during the installation process.

I'll leave this issue open in case others experience the same problem.

**Comment by Seenko** [comment]
A friend of mine was suddenly having issues with his Docker Desktop, didn't matter what version was being used (`3.3.3`, `3.2.2`, `2.5.0.1`). Even completely after removing Hyper-V and WSL2 and then trying with one or the other nothing budged.

Eventually we tracked down to a Windows Update (`KB5003254`), after uninstalling it and restarting the computer, everything went back to normal. If anyone bumps into this thread while trying to figure out what is going on,, maybe this can help your.

**Comment by ManfredLange** [comment]
@Seenko Looks as if `KB5003254` is not installed in my environment, so that seem to confirm in my environment what you are observing in your environment.

Good to know to keep an eye on when that Windows update comes through. Thank you!

**Comment by daffodilistic** [comment]
Putting in a note that Docker `3.3.3` does not initialize and run for my Windows machine (Win 10 Pro 19043.1023), and I did not have `KB5003254` installed. Had to downgrade to `3.2.2`, but the auto-update will push Docker to install `3.3.3` on restart...but thankfully that can be avoided by saying "No" to the UAC prompt ;-)

**Comment by kingsumos** [comment]
Check #11300

**Comment by ccicchitelli** [comment]
I too have had 3.3.3 REPEATEDLY prompt to install and then never do anything when I click the install and upgrade button. This happens on my personal Win10 machine and work Mac x64 machine.
