### ISSUE TITLE
after system reboot, no containers appears; after restart Docker, keeps crashing

### ISSUE THREAD

**Issue by moudrick** [docker/for-win#11368]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C9CCFC2C-4263-4AE6-9DB6-9A3B1E06BC79/20210603062925

### Actual behavior

after system reboot, no containers appears
aster restart Docker, keep getting this crash

### Expected behavior

after system reboot, all previously created containers appear and properly start

### Information

  - Windows Version: [Version 10.0.17763.1971]
  - Docker Desktop Version: 3.3.3 (64133)
  - WSL2 or Hyper-V backend?  Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by MondoGarza** [comment]
I am having same issue

Information:
- Windows Server 2019 Standard: [Version 10.0.17763.17763]
- Docker Desktop Version: 3.4.0 (65384)
- Engine: 20.10.7
- WSL2 or Hyper-V backend? Hyper-V
- Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Yes, VM

Restart works sometimes and when it does it gives me the following error after a random amount of time usually 30min to 1hr:
"Error response from daemon: open \\.\pipe\docker_engine_linux: The system cannot find the file specified."
