### ISSUE TITLE
lcow driver cpu/memory settings

### ISSUE THREAD

**Issue by crashtua** [docker/for-win#1137]
Is there some information how to limit and/or configure cpu and memory limits for LCOW driver?
I picked up info from https://blog.docker.com/2017/09/docker-windows-server-1709/. Containers are started and working fine, but looks like all containers limited to 2 cores and 800 mb of memory.

**Comment by friism** [comment]
cc @patricklang @jhowardmsft

**Comment by jhowardmsft** [comment]
Many things are still not yet hooked up while the feature is being actively developed. I believe there's an issue stating this missing piece already open in moby/moby.

**Comment by crashtua** [comment]
@jhowardmsft is there some info where I can follow development process and see what is already implemented, and what in progress? I guess it is moby/moby repository?
btw, thanks all for reply :)

**Comment by friism** [comment]
The epic is here: https://github.com/moby/moby/issues/33850

I'm not sure resource constraints are listed there, maybe @patricklang can add that
