### ISSUE TITLE
docker doesn't start after windows restart. Also the option to restart is disabled.

### ISSUE THREAD

**Issue by shwetima04** [docker/for-win#11371]
![image](https://user-images.githubusercontent.com/68337177/120642758-eae3d080-c492-11eb-923d-44a3074bdd31.png)

**Comment by Pau-git-hub** [comment]
I have the same problem. I have to select the option 'Clean / Purge data
Data selected will be removed.' to docker restart it. Then I lose my containers of the previous day.
