### ISSUE TITLE
can

### ISSUE THREAD

**Issue by williamtrine97** [docker/for-win#11370]
E7235A6F-D094-497E-BC8F-6398E7A258A6/20210603091957 : Diagnostic ID

System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\Panagiotis\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: ��  

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information
stderr: 
   σε Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) στο C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:γραμμή 146
   σε Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__17.MoveNext() στο C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:γραμμή 169
--- Τέλος ιχνηλάτησης στοίβας από προηγούμενη θέση όπου δημιουργήθηκε μια εξαίρεση ---
   σε System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   σε System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   σε Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() στο C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:γραμμή 78
--- Τέλος ιχνηλάτησης στοίβας από προηγούμενη θέση όπου δημιουργήθηκε μια εξαίρεση ---
   σε System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   σε System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   σε Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__26.MoveNext() στο C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:γραμμή 102
--- Τέλος ιχνηλάτησης στοίβας από προηγούμενη θέση όπου δημιουργήθηκε μια εξαίρεση ---
   σε System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   σε System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   σε Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() στο C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:γραμμή 29
--- Τέλος ιχνηλάτησης στοίβας από προηγούμενη θέση όπου δημιουργήθηκε μια εξαίρεση ---
   σε System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   σε System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   σε Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() στο C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:γραμμή 67
--- Τέλος ιχνηλάτησης στοίβας από προηγούμενη θέση όπου δημιουργήθηκε μια εξαίρεση ---
   σε System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   σε Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() στο C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:γραμμή 92
--- Τέλος ιχνηλάτησης στοίβας από προηγούμενη θέση όπου δημιουργήθηκε μια εξαίρεση ---
   σε System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   σε System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   σε Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() στο C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:γραμμή 69
--- Τέλος ιχνηλάτησης στοίβας από προηγούμενη θέση όπου δημιουργήθηκε μια εξαίρεση ---
   σε System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   σε System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   σε Docker.Engines.Engines.<StartAsync>d__21.MoveNext() στο C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:γραμμή 101

  - Windows Version: windows 10 Enterprise
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  tried both, But WSL2 is
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: nope

### Steps to reproduce the behavior
 here is a screenshot of it
![dockererror](https://user-images.githubusercontent.com/84841702/120622893-e3f39880-c467-11eb-8cb3-f2fe097df1c8.png)

  1. .2..
  2. .3..

**Comment by williamtrine97** [comment]
damn, first time posting it here and the description i made is so ugly, ;/

i hope someone knows what this error is about so i can fix it

**Comment by stephen-turner** [comment]
This error usually means that you haven't installed WSL 2 correctly, which Docker Desktop uses. Please follow Microsoft's instructions at https://aka.ms/wsl2-install. If it's set up correctly, then the command wsl -l -v should show a version 2 distro.

**Comment by williamtrine97** [comment]
Um so, thanks for messaing me, but it doesn’t work, I get same error for some reasin, weird… lol
