### ISSUE TITLE
Docker-Desktop for Windows, using Windows Containers, available on tls, started as a service is not possible

### ISSUE THREAD

**Issue by jonl-percsolutions-com** [docker/for-win#11396]
- [X ] I have tried with the latest version of Docker Desktop
  - [ X] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics

### Actual behavior

Docker Desktop:

- Only starts at user login
- Automatically defaults to WSL containers
- Can only be exposed on port 2375 insecurely
- none of the above can be configured it seems

### Expected behavior

- Able to configure docker daemon for starting as a service before user login.
- Able to be configured to start in Hyper-V containers 
- Able to be configured to expose tls port 2376 with a self created client cert, just like on linux.

### Information

I have a need to run windows containers against a remote machine without having to login to the desktop every time to start the service.

**Comment by stephen-turner** [comment]
Correct, Docker Desktop only works for interactive use. It's also not supported on Windows Server: if that's what you're using, you might want to look into Docker Engine EE which is included in Windows Server.
