### ISSUE TITLE
Docker Desktop for Windows on WSL2 Does not Start

### ISSUE THREAD

**Issue by kk-sdsu** [docker/for-win#11397]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6E8EFBB9-D437-4D70-9DA7-02E7BB17B653/20210607210718

### Actual behavior
Docker Desktop does not run after being started up at login, when started up manually, or when started up manually and run as administrator.

### Expected behavior
Docker Desktop should start running and should display my images and containers.

### Information
  - Is it reproducible? I've reproduced it on my machine multiple times
  - Is the problem new? Yes, I just switched to WSL2 backend last week.
  - Did the problem appear with an update? No, it is the same version of docker desktop before I switched to WSL2
  - Windows Version: Windows 10 20H2 19042.985
  - Docker Desktop Version: Docker version 20.10.6, build 370c289
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No, native windows.

### Additional Information
 - This happened last week as well, but I resolved it by going to the Troubleshoot section and clicking "Reset to factory defaults." This worked, but it was horribly inconvenient as it cleaned out all of my VMs. For fear of this happening again I just didn't quit docker or turn off my machine for the rest of the week. Alas, the issue has come back when I booted my machine up today. Would really prefer not to have to clean out all my images and containers again.

### Steps to reproduce the behavior
  1. Run Docker Desktop as Administrator
  2. Open the Docker Dashboard and verify that in the bottom left the docker status is gray and says "Stopped."
  3. Open PowerShell
  4. Run "docker container ls"
  5. Receive "error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json": open //./pipe/docker_engine: The system cannot find the file specified."

![DockerStoppedDaemonNotRunning](https://user-images.githubusercontent.com/25672852/121095974-27bb0a80-c7a6-11eb-8fea-3d27e039b5fa.png)

**Comment by Thysk** [comment]
I am also having this same issue!
What I have found is not a fix, but can at least get you working before there is a fix.
-Go to debug section
-Clean/Purge data
-tick Hyper-V
-click delete

This seems to somehow kick something in the system to working and my docker works after that and doesnt touch my containers etc. The problem with this is that it needs to be done every time I restart or turn on the laptop, from sleep it seems fine!

**Comment by kk-sdsu** [comment]
Thank you! That is a much better work around! Not even sure why there would be Hyper-V data. Only reasonable explanation I can think of would be that the Docker uninstallation process didn't remove all the Hyper-V data/settings/config when I uninstalled Docker to make the switch to WSL2.
