### ISSUE TITLE
Windows host: COM Port cannot be opened in windows server core container

### ISSUE THREAD

**Issue by Ageraluon** [docker/for-win#1139]
### Expected behavior
When running a windows server core container and passing an existing COM port as parameter, it should be possible to open and access the Port from within the container

### Actual behavior
The COM port can be seen from within the container but not accessed.

### Information

- Windows host: Windows Server 2016
- Docker Version: 
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:57:19 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:47 2017
 OS/Arch:      windows/amd64
 Experimental: false

### Steps to reproduce the behavior

  1. Switch to Docker for Windows
  2. Locate an existing COM port from your device manager - here COM3 is used
  3. run `docker run -it --device  //./COM3://./COM3 microsoft/windowsservercore powershell`
  4. in powershell, confirm that COM ports are listed:
       `PS> [System.IO.Ports.SerialPort]::getportnames()`
         `--> COM3`
   5. When trying to open the port, the resulting error indicates however that the port cannot be found:
```
PS> $port= new-Object System.IO.Ports.SerialPort COM3,9600,None,8,one
PS> $port.open()
```

```
Exception calling "Open" with "0" argument(s): "The port 'COM3' does not exist."
At line:1 char:1
+ $port.Open()
+ ~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : IOException

```

**Comment by riverar** [comment]
COM3 in this case is just a symlink to an actual device in the Device namespace. The code to enumerate serial ports is dumb in the sense it doesn't follow the symlink, hence the results you see. You'll have to get the \Device\[...] into the container too, which isn't something Docker supports. (But you can tinker with your Windows Container silo configuration. Out of scope for this bug.)

Not sure this is a bug.

**Comment by Ageraluon** [comment]
Thank you for the notification, does any written documentation about changing the windows Container silo configuration exist? If yes, I'd agree to close this issue as non-supported

**Comment by riverar** [comment]
@Ageraluon Official docs? Nope. Unofficial docs? Sure! Check out my post https://withinrafael.com/2017/10/24/windows-container-app-compat-access-com-ports-from-windows-server-container/ 😄

**Comment by riverar** [comment]
Doesn't seem appropriate to auto-close issues that haven't been acknowledged in some official capacity.
/lifecycle frozen

**Comment by Ageraluon** [comment]
Right you are, I'd love to see this being officially supported. I still think device support is quite essential for a lot of applications and this is a quite severe limitation for many projects here.

**Comment by rn** [comment]
This is not a feature the Docker for Windows application can support as this would be a feature of the upstream docker support on Windows, so I'm closing this issue here.

I would suggest to open a feature request on https://github.com/moby/moby as this is where at least some of this work would be carried out.
