### ISSUE TITLE
Unable to Share C Drive

### ISSUE THREAD

**Issue by DiJu519** [docker/for-win#114]
### Expected behavior

Would be able to Share C Drive using Settings > Share Drive
### Actual behavior

UI asks for Credentials, Hangs for a bit
### Information
- 851AEEB8-7FE4-423D-BB53-655B70B251FE/2016-09-29_17-04-20
- Windows 10, Docker Version 1.12.2-rc1-beta27 build 7450
  - Cisco VPN is Active

> [17:00:42.220][SambaShare     ][Error  ] Unable to mount C drive: mount error(115): Operation in progress
> Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
> mount: mounting //10.0.75.1/C on /c failed: Invalid argument

In file explorer, \10.0.75.1\C just hangs, but \localhost\C works.

**Comment by PetaPetaPeta** [comment]
I'm getting this issue as well.

**Comment by rneugeba** [comment]
@DiJu519 thanks for your report.

Do you know if the VPN changes your firewall settings, in particular if it blocks port 445? Could you check with `Get-NetFirewallRule –DisplayGroup "File and Printer Sharing"` (from an elevated powershell) or add the output with and without VPN to the issue?

**Comment by Cuchulain** [comment]
Yes, the problem may be a firewall. I use "Kaspersky Internet Security" with its own firewall module and when I disable this, Docker disk sharing began work :)

**Comment by vshantharaj** [comment]
Had a similar issue (windows firewall) disabling worked!!!

**Comment by JimmyHannon** [comment]
Same issue for me. Disabling my firewall solves the problem. But of course i don't want to disable it completely. So i tried adding a rule to allow all connections on 445 but that doesn't work. Any suggestions for adding a specific rule to the firewall?

**Comment by vshantharaj** [comment]
Probably still not the best solution - but i just enabled/allowed inbound traffic on local address- 10.0.75.1 (all ports)

looking for a better rule to enable the same

**Comment by rneugeba** [comment]
@Cuchulain thanks for testing. Is there a way you can add custom rules to the "Kaspersky Internet Security"? It should be sufficient to allow inbound traffic on port 445 on 10.0.75.1 from 10.0.75.2.

@JimmyHannon @vshantharaj on my system in "Windows Firewall with Advanced Security", under Inbound Rules, I have a Standard Rule ("File and Printer Sharing (SMB-In)") enabled for Public/Private profile for local subnet. This is a standard rule which is enabled by default when file sharing is enabled, AFAIK.

**Comment by JimmyHannon** [comment]
Thanks @vshantharaj. After figuring out how to add this custom rule on my firewall (ESET Smart Security) it worked.

**Comment by rneugeba** [comment]
@JimmyHannon thanks for reporting back

@Cuchulain any updates from your side?

We can't really fix this issue for any given firewall software, but should update the documentation accordingly.. Maybe we can also add a test to see if the required ports are open. @dgageot WDYT?

**Comment by DiJu519** [comment]
@rneugeba  Sorry for the delay in getting back to you.

Attached is the output of the command, with VPN On

[output.txt](https://github.com/docker/for-win/files/536667/output.txt)

**Comment by BarnumD** [comment]
I am having a similar issue where we turn on our VPN client and have 'A firewall is blocking file sharing between windows and the containers.'  If we turn the vpn client off, no issue.  As far as I know the client makes no changes to the windows firewall.  Also, we had the virus scanner disabled during both tests.  We do have a rule in the firewall allowing 445 from 10.0.75.0/24

**Comment by davidebbo** [comment]
I'm having this issue as well. Interestingly, the Docker installer (beta channel) did add the inbound rule to the firewall:

![image](https://cloud.githubusercontent.com/assets/556238/20465610/db9db510-af15-11e6-8e30-7bfdf066c74b.png)

Yet this doesn't work. Even more puzzling, I tried to briefly completely disable the Windows Firewall, and I was still getting the same error. This makes me think that there is something going on beyond the firewall that's preventing this.

**Comment by pmsousa** [comment]
I'm having the exact same problem. Beta channel, the inbound rule was added by the installer to the firewall and even with the firewall turned off (for test purpose only) the message was the same:

**A firewall is blocking file Sharing between Windows and the containers**

Like @davidebbo previous message, something else is blocking sharing. 3 days ago -Saturday, 19th -  this was working fine!

A diagnostic was uploaded with id: 54FF1DE0-4325-47F8-80E1-0EECE6EF6B4A/2016-11-22_09-36-45

**Comment by gorbunovav** [comment]
@davidebbo @pmsousa I had the same error message even with the firewall disabled.

Try to share the drive manually in Windows and check, that you can access 

`//10.0.75.1/[Drive Letter]`

If it doesn't work - check, that file sharing is enabled for the docker interface location (Public network by default) and try to remove, then add back 'File and Printer Sharing for MS Networks' in 'vEthernet (DockerNAT)' network adapter's properties.

(I've also moved interface to the 'Private network' segment:

`Set-NetConnectionProfile -InterfaceAlias "vEthernet (DockerNAT)" -NetworkCategory Private`

in the PowerShell)

**Comment by pmsousa** [comment]
@gorbunovav I already tried both ways: sharing manually the C drive and setting the network profile to Private. Actually, I had the exact same idea to change via PoSh...
When I try to Publish a container with VS17 the error message states clearly that the shared drive is not defined on Docker for Windows settings and if I try to turn it on, the Docker for Windows removes my manually created share and complains about the Firewall!!! :(

Bummer, I have a public presentation today and I would really love to show this feature working! That's the problem with working with Beta versions...

**Comment by gorbunovav** [comment]
@pmsousa the point of sharing manually was to check, that the share is available on the same interface, where Docker VM is looking for it: \\10.0.75.1\[Drive Letter] (so don't try to share in Docker, just try to open it in Explorer)

you can also try to debug the issue from inside of the container:
http://docker-saigon.github.io/post/Docker-Beta/#private-registries:ebf9573d6838c40027746e9d7482622a

then try to ping host & mount:
`mount -t cifs //10.0.75.1/C /C -o username=<username>,password=<password>,noperm`

**Comment by denisvmedia** [comment]
@gorbunovav thank you, it worked for me.

**Comment by wendelmax** [comment]
You can change the status of the docker network in the settings center of Kaspersky to trusted.
10.0.75.1/24 (vEthernet (DockerNAT)) -->> trusted

**Comment by peterhorvath** [comment]
Hi Guys,

I've the latest docker for windows and can't start the sharing.
It says firewall is blocking it.
I see the rules added to the firewall by default DockerSmbMount.
And even thought i am on a domain machine my domain profile is windows firewall turned off.

Is there a way to figure out what is blocking. I have ESET and McAfee but none is saying it would block anything. I am on windows 10 enterprise edition 64bit.

**Comment by rneugeba** [comment]
@peterhorvath can you add your details to #345. Looks more appropriate. Could you also add a diagnostics ID.

**Comment by rneugeba** [comment]
I'm going to close and lock this issue. We added some documentation regarding firewalls and have other issues open with more specific firewall issues. If you still have an issue and it is not yet tracked in one of the more specific ones, please create a new issue.
thanks
