### ISSUE TITLE
[WARNING] GCP line ignored (image not found): RuntimeError: A GCP file was provided, but no valid GCP entries could be used.

### ISSUE THREAD

**Issue by LeonBotha** [docker/for-win#11405]
Hi, 

Your help would be much appreciated since I've tried everything, even re-installed Windows 10.

When running a project without any GCP file, everything works.
The moment any option of processing (Default) and other setting, is used
the process halts shortly after the images are uploaded.
The log file shows that the GSP line was ignored .... for every line of the GCP file, produced by
the GCP Editor Pro,
and in the following processing it says a GCP file was provided, but valid entries could be used.

[WARNING] GCP line ignored (image not found): 
RuntimeError: A GCP file was provided, but no valid GCP entries could be used.

Is my install faulty in any way, I use the WSL2 procedure ??

Your help is much appreciated !!!

**Comment by LeonBotha** [comment]
Oops, forgot to =say I am talking about WebODM & Docker.

**Comment by stephen-turner** [comment]
It sounds like this is a problem with the container, not with Docker software.
