### ISSUE TITLE
visual studio 2017 docker-compose missing files 

### ISSUE THREAD

**Issue by jamason** [docker/for-win#1141]
### Expected behavior
Visual Studio 2017 and Dockers for Windows on Windows 10.
VS version: 15.3.5
Docker version: 17.06.2-ce
Docker-Compose version: 1.14
When adding Docker Support to project
expected docker-compose.vs.debug.yml and docker-compose.vs.release.yml to be included under docker-compose.yml along with docker-compose.override.yml
### Actual behavior
the two files are missing
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ... Have Windows 2016 VM and several Windows 10 VM that have same issue
  2. ...

**Comment by friism** [comment]
Please open this on the issue tracker for Visual Studio: https://github.com/Microsoft/DockerTools
