### ISSUE TITLE
Docker Desktop is not starting

### ISSUE THREAD

**Issue by rlinaresr** [docker/for-win#11415]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3295EEAA-E7F1-4934-BC13-F849CD181B3B/20210609141857

### Actual behavior

Docker for desktop is not starting. Unable to create an instance of Docker.App: Unable to create an instance of Docker.ApiServices.Update.UpdateCheckTimer.

### Expected behavior

Docker start without problems

### Information

  - Windows Version: Windows 10 Pro 21H1 19043.1052
  - Docker Desktop Version: 3.3.3 (64133)
  - WSL2 or Hyper-V backend?
    WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior
  1. Start Docker Desktop

**Comment by mat007** [comment]
From your logs it looks similar to #11273
