### ISSUE TITLE
Error docker pull in my repositories

### ISSUE THREAD

**Issue by Orazure** [docker/for-win#11418]
- [X] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID:6087322B-255C-400F-99CD-87465752DBEE/20210609210758
![Captureddd](https://user-images.githubusercontent.com/25532437/121430894-fe060d00-c978-11eb-8957-afba65ab7c53.PNG)

### Information

  - Windows Version:20H2
  - Docker Desktop Version: 20.10.7,
  - WSL2  
 

### Steps to reproduce the behavior

 I can't pull an image in my repositories, 
i have tried "docker login " "docker logout" but with not succeeded 
![image](https://user-images.githubusercontent.com/25532437/121429033-c26a4380-c976-11eb-9956-0557d107eaec.png)

**Comment by prayzzz** [comment]
I think I encounter the same issue.

* Windows 21H1
* Docker Desktop 3.4.0
* Docker Engine 20.10.7
* WSL 2

`docker login` on my registry succeeds.
Pulling images from there fails with the status `401 Unauthorized`.

I assume the credentials aren't properly shared to the running docker daemon?

So far I haven't found a workaround.
