### ISSUE TITLE
on restart docker doesn't cleanly start

### ISSUE THREAD

**Issue by AartBluestoke** [docker/for-win#11428]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: none able to be generated to begin with, able to be generated after a restart: EB28399E-DDB7-4075-B9E8-C4A24DC23BA6/20210610235233
![image](https://user-images.githubusercontent.com/1892829/121610723-f7bb8200-ca99-11eb-99cc-24cd8ccb04af.png)

### Actual behavior
After a reboot of windows (this one was an automated restart last night, for installing patches) the docker front end starts, but not the back end:
![image](https://user-images.githubusercontent.com/1892829/121610759-0e61d900-ca9a-11eb-90bd-ae3ffa80ca37.png)
All i can do is use task manager to kill the Docker Desktop background service.
Starting docker Desktop from the start menu then starts cleanly, but starts the WSL2 containers, indicating that is the earlier problem:
![image](https://user-images.githubusercontent.com/1892829/121610996-9cd65a80-ca9a-11eb-954b-59a493ed2de2.png)

### Expected behavior
When you start Docker with your computer, it works.
### Information

  - Is it reproducible?
  -- I only notice it after restarts that try to preserve running processes (windows update restarts), but i haven't been tracking this, i just notice this after sometimes after i log into the computer.
  - Is the problem new?
  -- I have seen this a few times now

  - Windows Version: 10, latest patches.
  - Docker Desktop Version: latest (i update at any prompt, docker isn't telling me there is any new.)?
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Bare Metal (Laptop)

**Comment by stephen-turner** [comment]
@AartBluestoke Please try the latest version, 3.4. We think this bug is fixed.
