### ISSUE TITLE
New VSCode window opens when opening Docker Desktop UI

### ISSUE THREAD

**Issue by camerondurham** [docker/for-win#11421]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 8FFF4EB5-8CDF-4625-8CDA-3C36D7F64533/20210610030122

### Actual behavior

After updating to Docker Desktop version 3.4.0, when I open a Docker Desktop dashboard, a new window of Visual Studio Code opens and is closed when I close the dashboard. This also happens when I open the *About Docker Desktop* window.

![Docker-VSCode-Open-At-Once](https://user-images.githubusercontent.com/17013462/121458116-a60ddd00-c95d-11eb-8283-f533f4d10d67.gif)

Please see the Information section for my system configuration. Below is a screenshot of my settings:

![image](https://user-images.githubusercontent.com/17013462/121458351-0ac93780-c95e-11eb-9c84-c22e9ab44e13.png)

![image](https://user-images.githubusercontent.com/17013462/121458382-1a488080-c95e-11eb-8b17-ba07e9b81ae6.png)

> Note that the image above shows the setting `experimental: true`. I've tried disabling this experimental settings and this error still occurs.

### Expected behavior

**Only** the Docker Desktop window opens. Apologies if this is related to VSCode, but since the VSCode window opens from opening Docker Desktop, it seems that the program is somehow being opened from the Desktop UI application.

### Information

  - Windows Version:
    -  Windows 10 Education
    - Version	21H1
    - Installed on	‎11/‎10/‎2020
    - OS build	19043.1052
    - Experience	Windows Feature Experience Pack 120.2212.3740.0

  - Docker Desktop Version: 3.4.0 (65384)
  - WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: **no**

### Steps to reproduce the behavior

  1. Update to Desktop version 3.4.0
  2. Have VSCode installed
  3. Open a Docker Desktop Dashboard (or About Docker Desktop window) from the start menu or taskbar Docker icon

**Comment by abrueck** [comment]
Same here

**Comment by stephen-turner** [comment]
Hmmm, this is very strange, we can't reproduce it here.

**Comment by camerondurham** [comment]
I tried re-installing Docker just to test but the issue still happens. I'll try to look on Microsoft bug reports since this might be an issue with a Windows Insider Preview build I'm using.

**Comment by camerondurham** [comment]
Reinstalling VSCode resolved this issue for me. This may not be required but I had installed VSCode just for my user but when reinstalling chose to install system wide.

**Comment by stephen-turner** [comment]
Thanks for letting us know. It's still a mystery to me how it happened but I'm glad it's fixed for you.
