### ISSUE TITLE
[WSL2] Docker backend engine failed to start at boot, can't be restarted 

### ISSUE THREAD

**Issue by p1-ra** [docker/for-win#11442]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 35A6D868-F77A-4EB5-A24C-166842F636DD/20210613105511

### Actual behavior
After installing Docker Desktop (with WSL2 backend), the software start to fail to start its backend at boot and it is impossible to manually trigger a restart of it.

After install, generally the first reboot of the host do not provoke an issue, the docker backend properly start. But at next reboot it usually fail to start.

- Restarting the "Docker Desktop Service" from the services manager, do not resolve the issue
- Removing the WSL2 existing docker-desktop, docker-desktop-data do not resolve the issue, even after reboot
- The Docker Desktop parameters UI is inaccessible, it freez on it (Got that screen for 30+min then I give up):
![image](https://user-images.githubusercontent.com/18233250/121803506-502d8380-cc42-11eb-89e9-f197cf1ef1c5.png)

In fact the only mitigation I've found is to uninstall then install again Docker Desktop. Wich it really not convenient to do after each PC reboot.

### Expected behavior
- Docker WSL2 backend properly start at boot
- Docker WSL2 backend can be easly restarted if needed

### Information
 - The probleme appeared since the last update
 - Please note the some of the gathered debug information are useless, `.\com.docker.backend.exe gather` needs to be run as a privileged user, which is not my day to day user
   - As exemple, the debug contains the output of `wsl.exe -d docker-desktop dmesg`: (of the privileged user)  
    ```
    There is no distribution with the supplied name.
    ```
    Which do not correspond at all of the context of my current user, which is running Docker Desktop:
    ```
    (...)
    [  962.696501] WSL2: Performing memory compaction.
    [  973.748097] EXT4-fs (sdc): mounted filesystem with ordered data mode. Opts: discard,errors=remount-ro,data=ordered
    [  973.773435] FS-Cache: Duplicate cookie detected
    [  973.773438] FS-Cache: O-cookie c=000000003205393d [p=000000001f4c1a30 fl=222 nc=0 na=1]
    [  973.773438] FS-Cache: O-cookie d=00000000835ed124 n=0000000079c7761e
    [  973.773439] FS-Cache: O-key=[10] '34323935303334363533'
    [  973.773441] FS-Cache: N-cookie c=00000000f8c443ce [p=000000001f4c1a30 fl=2 nc=0 na=1]
    [  973.773442] FS-Cache: N-cookie d=00000000835ed124 n=0000000068f39b8f
    [  973.773442] FS-Cache: N-key=[10] '34323935303334363533'
    [  973.786296] init: (1) ERROR: UpdateTimezone:97: Europe/Paris timezone not found. Is the tzdata package installed?
    [  973.786300] init: (1) ERROR: InitEntryUtilityVm:2425: UpdateTimezone failed
    ```

  - Windows Version: Windows 10 Pro 19042
  - Docker Desktop Version: 3.3.3.64133
  - WSL2 or Hyper-V backend: Yes
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No, I'm running on a Lenovo ThinkPad T470s Laptop

### Steps to reproduce the behavior
  1. Install docker Desktop with WSL2 support
  2. Reboot
  3. Reboot
  
  
  Thanks in advance

**Comment by p1-ra** [comment]
Jfi, solved by disabled all boot start and manually starting it, simple but efficient 😄

**Comment by J0F3** [comment]
I have similar issues since version 3.3.2. When docker start after the boot it crashes somehow and when I hover over the Docker Icon in the taskbar it dispers. I have also disabled the "start at login" and start it later on when I need it. 

But since Version 3.3.2 something is definitively bugged. When I downgrade to Version 3.3.1 again the problems are gone.

**Comment by kingsumos** [comment]
check this
https://github.com/docker/for-win/issues/11300#issuecomment-848183873

**Comment by p1-ra** [comment]
> check this
> [#11300 (comment)](https://github.com/docker/for-win/issues/11300#issuecomment-848183873)

I had tried your workaround, on my side, when starting vpnkit-bridge.exe manually with your arguments: 
```
\vpnkit-bridge.exe" --disable ssh-auth,osxfs-data,transfused,filesystem-event,filesystem-test,http-proxy-control --addr stdio --wsl-distro docker-desktop host
```

It hanged indefinitely, waiting some services to be ready (do not remember which ones exactly)
