### ISSUE TITLE
Failed to start Docker Desktop after upgrade to 3.4.0 (65384)

### ISSUE THREAD

**Issue by DesKonstantin** [docker/for-win#11455]
System.Threading.Tasks.TaskCanceledException:
Cancellation token triggered before we finished reading from the stream.
   в HttpOverStream.ByLineReader.<ReadLineAsync>d__0.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в HttpOverStream.Client.DialMessageHandler.<SendAsync>d__9.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Docker.Core.IPC.Client.<SendAsync>d__4.MoveNext() в C:\workspaces\PR-15906\src\github.com\docker\pinata\win\src\Docker.Core\IPC\Client.cs:строка 41
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Docker.ApiServices.LifecycleClient.<DockerStartAsync>d__4.MoveNext() в C:\workspaces\PR-15906\src\github.com\docker\pinata\win\src\Docker.ApiServices\LifecycleClient.cs:строка 84
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Docker.LinuxkitDaemonStartup.<StartAsync>d__5.MoveNext() в C:\workspaces\PR-15906\src\github.com\docker\pinata\win\src\Docker.Desktop\LinuxkitDaemonStartup.cs:строка 30
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__26.MoveNext() в C:\workspaces\PR-15906\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:строка 178
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() в C:\workspaces\PR-15906\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:строка 20
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() в C:\workspaces\PR-15906\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:строка 29
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() в C:\workspaces\PR-15906\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:строка 38
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() в C:\workspaces\PR-15906\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:строка 69
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Docker.Engines.Engines.<RestartAsync>d__26.MoveNext() в C:\workspaces\PR-15906\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:строка 266

  - [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
146CB1B3-345B-4C62-9386-2CF15EFFC744/20210616081455
### Information

  - Windows Version: 
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 2009
Build: 19043
  - Docker Desktop Version:
 3.4.0 (65384)
  - WSL2 or Hyper-V backend?  
WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by StefanScherer** [comment]
Hi @DesKonstantin thanks for the report. Have you tried to reset to factory defaults? Does it then start?

**Comment by DesKonstantin** [comment]
> 
> 
> Hi @DesKonstantin thanks for the report. Have you tried to reset to factory defaults? Does it then start?

Hi. After reset to factory defaults Docker was started
