### ISSUE TITLE
3.4.0, WSL2: docker-compose is linked to V2 instead of V1 although experimental feature is disabled

### ISSUE THREAD

**Issue by famod** [docker/for-win#11457]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

After upgrading from 3.3.3 to 3.4.0, in WSL2 Ubuntu 20.04:
```
$ ls -la /usr/bin/docker-compose
lrwxrwxrwx 1 root root 56 Jun 16 12:18 /usr/bin/docker-compose -> /mnt/wsl/docker-desktop/cli-tools/usr/bin/docker-compose
```
Which will effectively trigger Compose V2.

### Expected behavior

Must instead be linked to `/mnt/wsl/docker-desktop/cli-tools/usr/bin/docker-compose-v1` because experimental feature "User Docker Compose V2" is **not** active!

### Information

In plain Windows, V1 is used, which is even more proof that there is a bug in WSL2 handling.
In 3.3.3 I did not have this problem.

I have restarted Docker and pruned data but that did not solve the problem.

Winver: 20H2 (Build 19042.985)
Ubuntu 20.04.2 LTS

*Workaround*: 
```
sudo ln -fs /mnt/wsl/docker-desktop/cli-tools/usr/bin/docker-compose-v1 /usr/bin/docker-compose
```

### Steps to reproduce the behavior

With 3.4.0, in WSL2 dist, call `docker-compose --help` and you will see that V2 is used (e.g. examples say "docker compose" instead of "docker-compose").
Or just call `docker-compose --version`.

**Comment by famod** [comment]
I was able to solve that inconsistency (WSL2 vs. plain Windows) via `docker-compose disable-v2`, see also: https://docs.docker.com/compose/cli-command/

**Comment by StefanScherer** [comment]
Alright, thanks. I couldn't reproduce it. Maybe the next time try to change the experimental setting, then save it, then apply it again and apply it again. Maybe the sync didn't work once.

**Comment by famod** [comment]
> Maybe the next time try to change the experimental setting, then save it, then apply it again and apply it again.

I also did that. The only thing that brought it back into sync is `disable-v2`.
