### ISSUE TITLE
Docker failed to initialize / The operation has timed out on VPN

### ISSUE THREAD

**Issue by EricHripko** [docker/for-win#11468]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - ~I have uploaded Diagnostics~
  - Diagnostics ID: _Unable to upload since Docker Desktop refuses to start_

### Actual behavior
Starting _Docker Desktop_ with VPN connected results in the following error:
![Timed out](https://user-images.githubusercontent.com/707679/122371819-11f0d680-cf58-11eb-8ba9-5ec2464b8a5f.png)

If I leave the dialogue (after roughly 5 minutes), _Docker Desktop_ does start and future quit-and-start-again cycles appear to work fine.

Furthermore, _Docker Desktop_ starts up just fine without VPN connected.

### Expected behavior
- Expected _Docker Desktop_ not to display a "fatal error" dialogue since it appears to eventually start fine 
- Expected _Docker Desktop_ to wait less before starting

### Information

  - Windows Version: _21H1 (OS Build 19043.1052)_
  - Docker Desktop Version: _3.4.0 (65384)_
  - WSL2 or Hyper-V backend?  _WSL2 backend_
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: _No_

### Steps to reproduce the behavior
  1. Connect to a VPN or use any other software that disallows direct (without proxies) access to the web
  2. Start _Docker Desktop_
  3. Observe the behaviour described above

**Comment by steffenb91** [comment]
same problem for me, did a fresh reinstall with latest version. for me it doesn´t matter if connected to a vpn or not.
Windows 10 Enterprise , Version 1803 (Hyper-V Backend)
