### ISSUE TITLE
Hyper-v module is not availible for Windows 10 home

### ISSUE THREAD

**Issue by babobski** [docker/for-win#1146]
### Expected behavior
Wanted to install docker, but I'm unable to load the 'Hyper-v' module.
Searched how to enable the hyper-v module.

But I came to the sad conclusion I cannot install hyper-v on Windows 10 home edition.
The Microsoft documentation say's the following:

> The Hyper-V role **cannot** be installed on Windows 10 Home.

### Information

* Windows 10 home edition
* For diagnostic information look [here](https://github.com/docker/for-win/issues/65#issuecomment-333297562)
* And the [official Microsoft documentation](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v) about installing hyper-v

**Comment by sevcham** [comment]
You need Windows 10 Pro edition. 

I too had this issue, so purchased a Pro key. It's the only option.

**Comment by friism** [comment]
The older Docker Toolbox product will work without Hyper-V: https://docs.docker.com/toolbox/toolbox_install_windows/

**Comment by mattn** [comment]
You are not active for developing Docker Toolbox?

https://github.com/docker/toolbox/pull/724
