### ISSUE TITLE
Docker (with WSL 2 backend) fails to start on first start since version 3.3.2

### ISSUE THREAD

**Issue by J0F3** [docker/for-win#11462]
- [ x ] I have tried with the latest version of Docker Desktop
  - [ x ] I have tried disabling enabled experimental features (was never enabled)
  - [ x ] I have uploaded Diagnostics
  - Diagnostics ID: 44FAC8B3-5BB2-4A37-9D85-C41CF49CFFEC/20210616191344

### Actual behavior

After boot and login the first time Docker (with WSL 2 backend) is started (manually or by auto start after login), Docker almost immediately crashes. The Docker Icon in the Taskbar stops moving and does not show any container and when hovering over the icon with the mouse it disappears. Also the docker commands are not available in Windows or WSL.

The second time Docker is startet it normally starts then successfully.

### Expected behavior

After boot and login the Docker should start normally. Either by starting manually through start menu or by auto start. 

### Information

  - Is it reproducible? 
  Yes, after every reboot.
  - Is the problem new? 
  Relatively. After the Update from Version 3.3.1 to Version 3.3.2 the problem has started. Now even with Version 3.3.4 the problem still exists. I have also tested with Version 3.3.1 again and then the problem is gone. But after updating again to any Version >3.3.2 the problem is there again. 
  - Did the problem appear with an update? 
  Yes. The first time after updating to Version 3.3.2

  - Windows Version: 21H1 19043.1052
  - Docker Desktop Version: 3.4.0 (65384)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No.

### Steps to reproduce the behavior
  1. Boot computer
  2. Login
  3. Start Docker

**Comment by kingsumos** [comment]
check #11300

**Comment by J0F3** [comment]
@kingsumos Thx, but it looks like we have different issues. For me docker is actually starting but only on the second attempt. Furthermore after a failed start attempt the only log I have ist `com.docker.backend.exe.log`. So it looks like the error in my case occurs even earlier before `vpnkit `ever gets startet.

**Comment by J0F3** [comment]
After completely re-installed my machine the issue was gone.
