### ISSUE TITLE
Kubernetes on Docker Desktop does not recognize local images

### ISSUE THREAD

**Issue by sathishc58** [docker/for-win#11484]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:  E166DCD8-CECB-4B85-95FA-09D521E4AF14/20210619101355

### Actual behavior

I am trying to deploy Windows Container image on the following software stack

`Windows 10 Enterprise + Docker Desktop + Embedded Kubernetes in docker desktop`

Due to some reason `'embedded kubernetes'` does NOT recognize `'local images'` no matter whatever `--image-pull-policy` was set

Docker images

```
PS C:\WINDOWS\system32> docker images
REPOSITORY                             TAG        IMAGE ID       CREATED        SIZE
myimg                                  final      90c09acbfc59   15 hours ago   5.45GB
```

Kubectl run using Windows image

```
PS C:\WINDOWS\system32> kubectl run --image=myimg:final tskuberun


Pod output

Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  25s                default-scheduler  Successfully assigned default/tskuberun to docker-desktop
  Normal   BackOff    23s (x2 over 24s)  kubelet            Back-off pulling image "myimg:final"
  Warning  Failed     23s (x2 over 24s)  kubelet            Error: ImagePullBackOff
  Normal   Pulling    9s (x2 over 25s)   kubelet            Pulling image "myimg:final"
  Warning  Failed     8s (x2 over 25s)   kubelet            Failed to pull image "myimg:final": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.65.5:53: no such host
  Warning  Failed     8s (x2 over 25s)   kubelet            Error: ErrImagePull
```

However, when I execute docker run it pulled the local image. Following worked as expected

`PS C:\WINDOWS\system32> docker run myimg:final`

On further investigation, I observed that 'Docker desktop' refers to local images in case had I selected option "Switch to Linux Containers"

Kubectl run for Linux image (Success scenario)

```
PS C:\WINDOWS\system32> kubectl run --image=wphp --image-pull-policy=IfNotPresent lntest

PS C:\WINDOWS\system32> kubectl describe pod/lntest

Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  40s               default-scheduler  Successfully assigned default/lntest to docker-desktop
  Normal   Pulled     2s (x4 over 39s)  kubelet            Container image "wphp" already present on machine
  Normal   Created    2s (x4 over 39s)  kubelet            Created container lntest
  Normal   Started    2s (x4 over 39s)  kubelet            Started container lntest
```

It appears that this issue occurs only for `'Windows containers'` ie Docker desktop does NOT refer local images had I selected option `'Switch to Windows Containers'`

I googled for the answer but most of the links were related to Unix flavors and Minikube.

Only few links were related to Docker desktop + embedded kubernetes, but unfortunately none resolved the issue

### Expected behavior

Embedded Kubernetes on Docker desktop should refer `'local images'` first instead of pulling it

### Information

  - Windows Version:  Windows 10 Enterprise
  - Docker Desktop Version:  3.4.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:  No

### Steps to reproduce the behavior

  1.  Install Docker Desktop and Enable Kubernetes on Windows
  2.  Select option 'Switch to Windows Container' on Docker Desktop
  3.  Create a Windows docker image and store it locally
  4.  Execute `'kubectl run --image=myWinImage --image-pull-policy=IfNotPresent testWindows"` 
  5.  Embedded Kubernetes on Docker desktop should refer the local image instead of pulling it

**Comment by trungutt** [comment]
@sathishc58 Kubernetes is only available for Linux containers: if you switch to Windows Container, in the settings you won't see the Kubernetes section anymore.
