### ISSUE TITLE
Please help me understand the problem

### ISSUE THREAD

**Issue by Falahi-A** [docker/for-win#11485]
Hi , I'm new in using Docker for windows app. I have cloned a docker composer git repository to run and provide me some rest api services. After cloning the repository, I try to run it by ( docker-compose up ) command in Windows PowerShell. when i do that, I get an error related to Mongo db, it says that can't read property db of null  and unable to connect to database. Besides when I try to call apis, I get this error : 

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>TypeError: Cannot read property &#39;collection&#39; of undefined<br> &nbsp; &nbsp;at MongoDBClient.all (/app/utils/mongodb/client.js:57:24)<br> &nbsp; &nbsp;at ProductService.&lt;anonymous&gt; (/app/service/product.js:160:64)<br> &nbsp; &nbsp;at step (/app/service/product.js:44:23)<br> &nbsp; &nbsp;at Object.next (/app/service/product.js:25:53)<br> &nbsp; &nbsp;at /app/service/product.js:19:71<br> &nbsp; &nbsp;at new Promise (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at __awaiter (/app/service/product.js:15:12)<br> &nbsp; &nbsp;at ProductService.getUsers (/app/service/product.js:156:16)<br> &nbsp; &nbsp;at UserController.&lt;anonymous&gt; (/app/controller/product.js:63:67)<br> &nbsp; &nbsp;at step (/app/controller/product.js:44:23)</pre>
</body>
</html>

I expect apis to work correctly. could you help me diagnose the problem please.
This is my Diagnostics Id: 116BF641-B734-4BB4-9AB0-15F52A38A962/20210619085549.
I attach the screenshot of my error I get, when I use docker-compose up commend as well, may it help you to understand my issue better.

![Screenshot (1)](https://user-images.githubusercontent.com/78015852/122639479-596d9300-d10f-11eb-8037-d55fc966d29c.png)

**Comment by trungutt** [comment]
Closed because not related to Docker Desktop itself. Please report your question on https://www.docker.com/docker-community
