### ISSUE TITLE
Regression:  Hyper-V : Mounting `v1` and `v2` in my container creates a `v1v2` on my host

### ISSUE THREAD

**Issue by jeremyVignelles** [docker/for-win#11482]
- [X] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
I have a web server docker container that needs to mount two folders from the same directory:
- `v1` is mounted to `/app`
- `v2` is mounted to `/appv2`

Since the latest docker for windows update, I now have a third empty folder named `v1v2` that is created next to the `v1` and `v2`, that can't be removed while the container is running (at least on my real production container, not with the command below it seems), and that is recreated every time I start the container
![image](https://user-images.githubusercontent.com/3399355/122573506-2663ca80-d04f-11eb-9795-1e0852f90d2a.png)

### Expected behavior
No folder should be created, as it always did before the update.

### Information
  - Windows Version: 20H2 (19042.1052)
  - Docker Desktop Version: 3.4.0 (engine 20.10.7, compose: 1.29.2)
  - WSL2 or Hyper-V backend?  Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Create a folder that contains two folders : `v1` and `v2`
  2. Open a powershell in the folder that contains both folders
  3. Run this command: `docker run -it -v ${PWD}/v1:/app -v ${PWD}/v2:/appv2 alpine`
  4. See the `v1v2` folder created on the host machine
  5. See that 'app' and 'appv2' are properly mounted in the container

Note: This doesn't happen if the mountpoints are named `appv1` and `appv2`... It seems to happen because `app` is a substring of `appv2`

**Comment by stephen-turner** [comment]
Hmmm, this is very weird, but what is even weirder is that I can't reproduce it despite your very clear instructions.

**Comment by jeremyVignelles** [comment]
Well, I can repro 100% of the time on my machine (just tried again). What else can I do to help ?
I don't remember what specific things I have in my configuration, but I can at least tell you this:
- I moved the machine to my D: drive, and I'm mounting my folders from that D: drive
- I'm logging in to windows with an Azure AD account.

**Comment by mat007** [comment]
What shell are you using?

**Comment by jeremyVignelles** [comment]
I just tried in my documents folder (in C:), same issue. I forgot to mention that my coworker also has the issue on its machine.

I made the repro with PowerShell, but I'm usually running my app with a `docker compose up` inside a git bash.

**Comment by jeremyVignelles** [comment]
Just asked a friend to test on his machine : This doesn't seem to happen with the WSL2 backend.
I also want to emphasize that it didn't happen before the last update (I was up-to-date before). Did anything change recently around mount points ?

**Comment by stephen-turner** [comment]
Ah, I was testing on WSL 2, maybe that's the difference. I don't have Hyper-V on my machine.

**Comment by StefanScherer** [comment]
Thanks @jeremy-castile for the report.
I can reproduce it when Docker Desktop uses the Hyper-V backend.
We're investigating.

**Comment by StefanScherer** [comment]
I've tried it again with version 3.5.2 which has been released today and I couldn't reproduce it.
Please check for updates and install the latest version.

**Comment by jeremyVignelles** [comment]
I'm still on 3.5.1, but cannot reproduce either. Closing this as it seems to be resolved. Thanks !
