### ISSUE TITLE
Docker Desktop is crashing after updating Windows 10 to Build 21390 (Windows Insider's, Dev channel)

### ISSUE THREAD

**Issue by odiraneyya** [docker/for-win#11498]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 1760FC61-C8B4-4F03-B12A-5B4C767816B0/20210621094900

### Actual behavior

Docker Desktop crashes on startup.

### Expected behavior

Docker Desktop starts normally.

### Information

  - Is it reproducible? Yes. 
  - Is the problem new? After joining the Windows Insider's program and updating WSL to get benefit of WSLg, the GUI support for Linux apps. That was when Docker Desktop stopped working.
  - Windows Version: Build 21390
  - Docker Desktop Version: Build 65384
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

Just open the frikkin' app :-)

**Comment by sc0ttwad3** [comment]
+1 same issue.  Arrrgh.

The prior build of Win10 Insiders had this same problem when v3.3.3 came out. Then v3.4.0 came out and fixed the problem.
Now Win10 Insiders updated to the latest build 21390, and now v3.4.0 has this same problem again.

**Comment by odiraneyya** [comment]
@sc0ttwad3 Thank you for the suggestion. In my case I did reset my Docker Desktop right away which lead to clearing the caches, I also switched to the Hyper-V backend and adjusted my memory settings after I was running out of memory. The engine started but I still had errors (some strange HTTP error/exception). Even when the engine started with Hyper-V I still could not run containers. Weird errors were showing.

Today I switched back to WSL2 and reset docker again and things are totally working. I am surprised. I am able to pull and run containers with no problems whatsoever. Somewhat confusing. Thanks!

**Comment by tebeco** [comment]
same here, but i did not tried to toy with `\\wsl$\docker-desktop-data\isocache` as the `docker-desktop` instance was apparently deleted

This may be on not unrelated but anyway I managed to solve it doing WSL2 instance reset + killing all docker process / reset.
Details here:
https://github.com/docker/for-win/issues/11523#issuecomment-868292099

**Comment by Neeraj-LTI** [comment]
Can anyone help me with installing the Docker Desktop on Windows? I had all the prerequisites correctly set up but as soon as I launch the installer it unpacks all the files and then failed with the error.

Component CommunityInstaller.ServiceAction failed: Failed to start service: **The service did not respond to the start or control request in a timely fashion
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()**

Please provide any help or direction for moving forward.

[Docker_Windows_Error.docx](https://github.com/docker/for-win/files/6752087/Docker_Windows_Error.docx)
