### ISSUE TITLE
Docker Desktop not working on Windows VM

### ISSUE THREAD

**Issue by prashantkasbe** [docker/for-win#11499]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Docker Desktop is installed on Windows VM.
While start Docker Desktop I get error: Failed to start the virtual machine 'DockerDesktopVM' because one of the Hyper-V components is not running.

### Expected behavior
Docker Desktop should start

### Information

Please, help us understand the problem.  For instance:
  - Is it reproducible? Yes
  - Is the problem new? Yes
  - Did the problem appear with an update? Its first time installed and experienced
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.

  - Windows Version: Windows 10 Enterprise
  - Docker Desktop Version: 2.2.0.0(42247)
  - WSL2 or Hyper-V backend?  Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Yes

### Steps to reproduce the behavior

  1. Starting Docker Desktop
[log.txt](https://github.com/docker/for-win/files/6685917/log.txt)

**Comment by StefanScherer** [comment]
Thank you for the report. Unfortunately Docker Desktop is not supported in a virtualised environment (see https://docs.docker.com/docker-for-windows/install/#whats-included-in-the-installer and https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-desktop-in-nested-virtualization-scenarios). It's out of our control whether it works or not: it depends whether the outer hypervisor can fully run Hyper-V or WSL 2. Sometimes enabling nested virtualisation in the outer hypervisor makes it work, but there are no guarantees.
