### ISSUE TITLE
Cannot start container in Docker for Windows build 27.

### ISSUE THREAD

**Issue by cerebrate** [docker/for-win#115]
### Expected behavior

A container should be started from the chosen image.

### Actual behavior

Container does not start, giving error as follows:

"Create container failed with error: container bb9ac81141335921cbea705cb3f965352fdf43ae3c0b464db2e0b51ce449ca66 encountered an error during Start failed in Win32: The JSON document is invalid. (0xc037010d)"

### Information

  Diagnostic ID: 80ECCE05-123D-490A-81F8-465ECEA6F335/2016-09-30_03-04-45

  Hosted on Windows 10 insider preview, build 14936.

### Steps to reproduce the behavior

  1. Install Docker for Windows beta 27 and switch to Windows containers.
  2. Pull the microsoft/nanoserver image (The issue, though, also happens with other images such as microsoft/windowsservercore.): docker pull microsoft/nanoserver
  3. Attempt to start a container using the image: docker run Microsoft/nanoserver

**Comment by naeemsarfraz** [comment]
I'm getting the same issue, I installed build 14936 yesterday and began to see this error. My logs from the docker logs:

[00:31:15.250][WindowsDockerDaemon][Info   ] time="2016-09-30T00:31:15.249815100+01:00" level=error msg="libcontainerd: failed to start container: container 470199c47d093d343d6604460aabd273702bf33ae63acd77c4dc99d3bdbf714d encountered an error during Start failed in Win32: The JSON document is invalid. (0xc037010d)" 
[00:31:15.257][WindowsDockerDaemon][Info   ] time="2016-09-30T00:31:15.250316000+01:00" level=error msg="Create container failed with error: container 470199c47d093d343d6604460aabd273702bf33ae63acd77c4dc99d3bdbf714d encountered an error during Start failed in Win32: The JSON document is invalid. (0xc037010d)" 
[00:31:15.401][WindowsDockerDaemon][Info   ] time="2016-09-30T00:31:15.401336600+01:00" level=error msg="Handler for POST /v1.24/containers/470199c47d093d343d6604460aabd273702bf33ae63acd77c4dc99d3bdbf714d/start returned error: container 470199c47d093d343d6604460aabd273702bf33ae63acd77c4dc99d3bdbf714d encountered an error during Start failed in Win32: The JSON document is invalid. (0xc037010d)"

**Comment by dgageot** [comment]
@naeemsarfraz Can you make sure you have all the latest Windows updates? See here: Microsoft/Virtualization-Documentation#358

**Comment by naeemsarfraz** [comment]
@dgageot I haven't had chance to look through that link yet as I needed to get things up and running for a demo yesterday. So this is what I did:
- Restored the previous build of windows and tried the tooling, result: still broken with the same error
- Cleared the c:\ProgramData\docker folder, a couple of directories couldn't be removed so I renamed them
- Re-installed Docker for Windows: same result, still failing

Linux containers works find but when you switch to Windows containers I wasn't able to run a container with a new error being reported:
`docker: Error response from daemon: container 48465da53f47156755cc6a7c7bd48a0f5a76db9fb9c6c77d52a481ffb9412d10 encountered an error during Start failed in Win32: The system cannot find the path specified. (0x3): Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.`

I found this and tried stopping Docker for Windows, starting the daemon manually using `dockerd -D --bridge "none"`. Now I can run a windows container but I have no IP for the container so can't get through to a website running on the container. However I can powershell into the container so I ran `wget http://localhost:9999` and got a enough of a response to demo.

P.S. Apologies this isn't as detailed as it should be, got very limited time today to spend on this.

**Comment by taylorb-microsoft** [comment]
We have tracked down a bug that results in the error: "Start failed in Win32: The JSON document is invalid. (0xc037010d)" that would effect Windows Insiders.

Users running Windows 10 Anniversary update (build 10.0.14393) should be unaffected.  Those with latter builds 10.0.14931/10.0.14936 will see this error.  We've fixed the bug and it's progressing though the inner rings - once I know the build # it's fixed in I'll update.

**Comment by cerebrate** [comment]
Appears to work again under 14942, FWIW.

**Comment by friism** [comment]
Closing this issue for now - with 1.12-cs2 (bundled in Docker for Windows beta28) shouldn't exhibit this problem (and is working on insider-build machine). Please re-open if you've upgraded both Windows 10 and Docker for Windows and am still seeing this problem.

**Comment by prochnowc** [comment]
I have still this issue with Windows 10.0.16299

**Comment by themultiplexer** [comment]
@prochnowc Yeah me too. But only with the 1803-image.
