### ISSUE TITLE
Doesn't start after the latest upgrade (17.09.0-ce-win32 (13529) Channel: stable)

### ISSUE THREAD

**Issue by patrik-martinko** [docker/for-win#1150]
### Expected behavior

Running Docker for Windows

### Actual behavior

Docker for Windows doesn't start absolutely

### Information

Diagnostic ID: B4900F60-55D8-4EC2-A554-1F9B52408CDC/2017-10-02_15-23-17

### Steps to reproduce the behavior

  1. Run Docker for Windows

How can I downgrade? I can't work on my projects after the latest update :(

**Comment by willsilvano** [comment]
Same here!

**Comment by albre404** [comment]
Here too.
![dock](https://user-images.githubusercontent.com/1794121/31093132-b8b8e4cc-a77e-11e7-8b43-a89f98c27f39.png)

**Comment by DarkGhostHunter** [comment]
Workaround: https://github.com/docker/for-win/issues/1148#issuecomment-333677117

**Comment by efvincent** [comment]
same here. diagnostic id: 1FD2F03D-FEC0-4C18-826F-5095B6EAEAEC/2017-10-02_20-51-16

**Comment by Catch21** [comment]
Same as albre404's pic above. The only off the beaten track piece I can think of is I installed on my D: drive (in my case, non-SSD for non-critical apps), the update seemed to install to C: drive instead. 

OS: Windows 10 Pro Insider Preview Edition: Professional Id: 1703 Build: 16278 (and there have been no recent updates to this or anything else)

Worked fine until this last update.

**Comment by albre404** [comment]
@DarkGhostHunter's Workaround did it for me.

Back to working again
