### ISSUE TITLE
"Too many colons" error when bind mounting a folder into Windows container

### ISSUE THREAD

**Issue by karolz-ms** [docker/for-win#11500]
### Prereqs
Docker Desktop build 65713 or newer (3.5 series)
VS Code 1.57 or newer
Docker VS Code 1.13 or newer
Windows 10

### Repro steps
1. Set Docker Desktop container mode to Windows
1. Create and open a .NET MVC or console project in VS Code.
1. Do "Add Docker files to workspace" with Windows OS selected.
1. Make sure the Dockerfile uses `aspnet:5.0` tag, not `aspnet:5.0-focal` tag (change if necessary)
1. Debug this project with "Docker .NET Core Launch" configuration.

### Expected
Should be able to debug normally

### Actual
Error from Docker:

```
docker: Error response from daemon: mount denied:
the source path "\\Users\\AzureTest\\Desktop\\test\\mvctest:C:\\app:rw"
too many colons.
See 'docker run --help'.
```

This problem does NOT happen with Docker Desktop ver 3.4.0

@v-ruizh FYI

**Comment by StefanScherer** [comment]
Thanks @karolz-ms for the report. We're investigating the problem.

I can reproduce the problem with a simpler setup:
1. Switch to Windows Containers
2. Open a PowerShell terminal
3. Create a test folder in the users home directory, eg. `mkdir app` and go into that directory `cd app`
3. Run `docker run -v "$(pwd):C:\app:rw" mcr.microsoft.com/dotnet/aspnet:5.0

I see a similar error
```
docker: Error response from daemon: mount denied:
the source path "\\Users\\Stefan Scherer\\app:C:\\app:rw"
too many colons.
See 'docker run --help'.
```

**Comment by thaJeztah** [comment]
@StefanScherer does it work if the path includes a drive-letter? `C:\\Users\\Stefan Scherer\\app:C:\\app:rw"` ?

**Comment by StefanScherer** [comment]
@thaJeztah The `$(pwd)` has the absolute path including the drive letter. We internally remove it to analyse the pathes and it unfortunately will be used to print the error.

**Comment by StefanScherer** [comment]
Here is a simpler repro command which makes it more clear.

```
$ docker run -v "C:\Users:C:\test:rw" mcr.microsoft.com/dotnet/aspnet:5.0
docker: Error response from daemon: mount denied:
the source path "\\Users:C:\\test:rw"
too many colons.
See 'docker run --help'.
```

**Comment by mat007** [comment]
Thanks @karolz-ms good catch!
This has been fixed on master now.
Here is the latest build in case you wanted to double check: https://desktop-stage.docker.com/win/stable/amd64/66013/Docker%20Desktop%20Installer.exe

**Comment by karolz-ms** [comment]
@mat007 thank you for quick turnaround! Will let you know if we find anything else, hopefully not.

**Comment by karolz-ms** [comment]
@v-ruizh confirmed build 66013 fixes the problem 😌
