### ISSUE TITLE
Istio cannot be installed anymore

### ISSUE THREAD

**Issue by juergenzimmermann** [docker/for-win#11516]
- [ x] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features
  - [ -] I have uploaded Diagnostics _Don't know how to do that_
  - Diagnostics ID: N/A

### Actual behavior
Installation fails for Istio 1.9.x and 1.10.x with a timeout message:
```
✘ Egress gateways encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the conditionsystem/istio-ingressgateway
Deployment/istio-system/istio-egressgateway
✘ Ingress gateways encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the condition
Deployment/istio-system/istio-ingressgateway
```

### Expected behavior
No timeout as with Docker Desktop 3.3.3

### Information
  - Is it reproducible? Yes, just try to install Istio with `istioctl install --verify --set profile=demo --set values.global.jwtPolicy=first-party-jwt --skip-confirmation`
  - Is the problem new? Yes. It worked with Docker Desktop 3.3.3
  - Windows Version: Windows 10 Enterprise 21H2
  - Docker Desktop Version: 3.5.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior
Just try to install Istio with `istioctl install --verify --set profile=demo --set values.global.jwtPolicy=first-party-jwt --skip-confirmation`

**Comment by trungutt** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
