### ISSUE TITLE
Failed to deploy distro docker-desktop

### ISSUE THREAD

**Issue by mtnrbq** [docker/for-win#11515]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 86BF4D82-A4F1-4A08-B05C-127DA431B37F/20210624042219

### Actual behavior
Docker desktop fails to start after installation.
Does not appear to be able to save the docker-desktop distro

### Expected behavior
Docker desktop starts and runs

### Information

  - Windows Version: Windows 10 Pro, insiders build 21390
  - Docker Desktop Version: 3.4.0
  - WSL2 or Hyper-V backend?   WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No 

### Steps to reproduce the behavior

  1. Install docker desktop - either through standard downloaded file, or using chocolatey
  2. Run docker desktop

**Comment by stephen-turner** [comment]
It appears that you haven't installed WSL 2 correctly, which Docker Desktop uses. Please follow Microsoft's instructions at https://aka.ms/wsl2-install. If it's set up correctly, then the command wsl -l -v should show a version 2 distro.

**Comment by mtnrbq** [comment]
wsl -l -v
  NAME      STATE           VERSION
* Ubuntu    Running         2

**Comment by mtnrbq** [comment]
@stephen-turner - as above, using Ubuntu on WSL2 on v2
