### ISSUE TITLE
Unable to expose Docker API on port 2375 after 3.5.0 update

### ISSUE THREAD

**Issue by sweptsquash** [docker/for-win#11517]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: AF41B2A1-2801-422A-9E0D-3CBB8AA7469B/20210624111619

### Actual behavior

Docker for Desktop updated to 3.5.0 and presented the error: "Unable to expose Docker API on 127.0.0.1:2375,[::1]:2375. The port is already in use by another program"

### Expected behavior

Docker API shared on port 2375 correctly after performing update.

### Information
  - Windows Version: Windows 10 21H1 - 19043.1081
  - Docker Desktop Version: 3.5.0 (66024)
  - WSL2 or Hyper-V backend?  Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior
  1. Upgrade an existing Docker for Desktop 3.4.0 to 3.5.0 with Kubernetes and file-share enabled with a Hyper-V backend
  2. Can also be replicated with a clean install of Docker for Desktop 3.5.0

I found a similar issue and followed [these steps](https://github.com/docker/for-win/issues/3171#issuecomment-459205576) in #3171 even changing the startport to 2375 fails to resolve the issue for me.

**Comment by oyvindstegard** [comment]
Seeing the same issue after upgrade to Docker desktop 3.5.1.
Despite the warning however, the port seems to work and Docker CLI tools (from WSL) are able to connect.
I've tested the following interfaces and they all work as `DOCKER_HOST`:
- `tcp://0.0.0.0:2375`
- `tcp://[::1]:2375`
- `tcp://127.0.0.1:2375`

**Comment by heeen** [comment]
I just noticed that tcp://localhost:2375 will fail but tcp://127.0.0.1:2375 works

**Comment by BePo65** [comment]
Same for me. Checking the open ports shows that the port 2375 is taken by docker desktop service. Is this warning a fake ?-)

Returning to Docker desktop 3.4.0 solves problem without any further modifications (so probably the configuration of other programs should not be the problem).

**Comment by rwalravens** [comment]
Having same issue since Docker Desktop 3.5.x
OS Windows 10 1909 (18363.1621) with WSL2.

**Comment by darksupremo** [comment]
same here, 3.5.1

**Comment by Ali-Shaikh** [comment]
Same on 3.5.1

**Comment by holzs** [comment]
same here, 3.5.1

**Comment by heeen** [comment]
I believe the port did not work for me until I performed the workaround steps mentioned in the other issue.

**Comment by shaunmlowry** [comment]
This only fails for me when using Windows containers.  I see the warning re: exposing the port on startup.

Previously I was able to manage and run both linux and windows containers from WSL1 by connecting to the TCP port - now I can only manage linux containers from WSL1.  When I try to do anything docker-related from WSL1 with docker for desktop in windows container mode it seems to fall back to looking at the linux pipe:
```
$ docker image ls
Error response from daemon: open \\.\pipe\docker_engine_linux: The system cannot find the file specified.
```
switching to Linux containers, everything works as expected

**Comment by AntonKrug** [comment]
"Returning to Docker desktop 3.4.0 solves problem without any further modifications (so probably the configuration of other programs should not be the problem)."

Is that possible for non-premium users?

**Comment by sweptsquash** [comment]
> "Returning to Docker desktop 3.4.0 solves problem without any further modifications (so probably the configuration of other programs should not be the problem)."
> 
> Is that possible for non-premium users?

I was able to return to `3.4.0` by downloading the specific release from the [Windows Release Notes Page](https://docs.docker.com/docker-for-windows/release-notes/) so far it hasn't asked me to update or forced the update.

**Comment by AntonKrug** [comment]
Thank you very much, I was struggling to find the download page with specific releases, not just the latest/greatest.

**Comment by mdeggers** [comment]
Has anyone tried 3.6.0 to see if it addresses this issue. I didn't see anything obvious in the release notes.

**Comment by rwalravens** [comment]
> Has anyone tried 3.6.0 to see if it addresses this issue. I didn't see anything obvious in the release notes.

Yes, the warning does not appear anymore.

**Comment by sweptsquash** [comment]
I too can also confirm that the `3.6.0` update resolves this issue. Thank you all for commenting, happy days that the issue has been resolved :)
