### ISSUE TITLE
Kubernetes stuck in 'Starting ...' phase

### ISSUE THREAD

**Issue by rorytorneymf** [docker/for-win#11527]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 0BAA159B-EFEB-470C-BF58-E36D0BC979D2/20210625135712

### Actual behavior
Kubernetes is stuck in 'Starting ...' phase

![image](https://user-images.githubusercontent.com/55391479/123436361-74844b00-d5c6-11eb-9840-1bb25a8d9e19.png)

Eventually, it will go to Failed To Start:

![image](https://user-images.githubusercontent.com/55391479/123439008-350b2e00-d5c9-11eb-8a77-4d7104bea72b.png)

I have added the diagnostic ID above, in the `C:\Users\Me\AppData\Local\Docker\log.txt` I see these ERRORs:

```
[14:55:09.373][GoBackendProcess  ][Error  ] msg="(2f5ee10d) c5bfa3ee-VolumePKG C<-S No response GET /settings (539.5µs): Get \"http://ipc/settings\": open \\\\.\\pipe\\dockerBackendApiServer: The system cannot find the file specified.[[STACK]]"
...
[14:55:16.172][VpnKit            ][Error  ] vpnkit.exe: Starting to watch : EINVAL
[14:55:16.172][VpnKit            ][Error  ] vpnkit.exe: Failed to watch hosts file : invalid argument
...
[14:55:16.172][VpnKit            ][Error  ] vpnkit.exe: While watching /etc/resolv.conf: ENOENT
...
[14:55:16.173][VpnKit            ][Error  ] vpnkit.exe: Pipe.listen: caught (Failure "Failed to connect vmnet device")
...
[15:05:27.365][GoBackendProcess  ][Error  ] msg="(d2fcc80b) 582c85a3-KubernetesHDL C<-S No response POST /kubernetes/start (10m0.0081748s): Post \"http://ipc/kubernetes/start\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)[[STACK]]"
...
[15:15:27.370][GoBackendProcess  ][Error  ] msg="(ac4ec9f5) 582c85a3-KubernetesHDL C<-S No response POST /kubernetes/start (10m0.0058221s): Post \"http://ipc/kubernetes/start\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)[[STACK]]"
...
[15:15:27.470][GoBackendProcess  ][Error  ] msg="error trying to start kubernetes:No response"
```

### Expected behavior
Kubernetes starts successfully

### Information

  - Windows Version: 
      OS: Windows 10 Enterprise
      Edition: Enterprise
      Id: 2004
      Build: 19041
      BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
  - Docker Desktop Version: 3.4.0 (65384)
  - Docker Engine Version: 20.1.7
  - Kubernetes Version: v1.21.1
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No
  - VPN? Tried with VPN on and VPN off

### Steps to reproduce the behavior
1. Settings > Kubernetes > Enable Kubernetes

### What I've tried
Most of the things listed here (deleting config files/dirs, restarting docker and PC, making sure /etc/hosts contains `docker-desktop' and is in plain ascii format, purging data):

https://stackoverflow.com/questions/57711639/docker-for-windows-stuck-at-kubernetes-is-starting-after-updating-to-version-2

### Other settings

![image](https://user-images.githubusercontent.com/55391479/123437412-8ca89a00-d5c7-11eb-8f7e-976de4c57214.png)

![image](https://user-images.githubusercontent.com/55391479/123437472-9b8f4c80-d5c7-11eb-9dcb-22867456d085.png)

![image](https://user-images.githubusercontent.com/55391479/123437508-a518b480-d5c7-11eb-9eab-fb1900fa7340.png)

![image](https://user-images.githubusercontent.com/55391479/123437612-c5487380-d5c7-11eb-87e1-097e42c94413.png)

![image](https://user-images.githubusercontent.com/55391479/123437643-ced1db80-d5c7-11eb-885c-cf97243f041a.png)

![image](https://user-images.githubusercontent.com/55391479/123437687-dabd9d80-d5c7-11eb-895e-6a5e1a66fc35.png)

![image](https://user-images.githubusercontent.com/55391479/123437721-e315d880-d5c7-11eb-81e6-7475f3a0f495.png)

**Comment by scrocquesel** [comment]
Having the same issue

The container k8s_kube-apiserver_kube-apiserver-docker-desktop_kube-system_532ed943fcdf0459293643165eb3af97_63 is stopping with 

````
Flag --insecure-port has been deprecated, This flag has no effect now and will be removed in v1.24.

I0625 22:48:14.941508 1 server.go:629] external host was not specified, using 192.168.65.4

Error: [service-account-issuer is a required flag, --service-account-signing-key-file and --service-account-issuer are required flags]
```

**Comment by axeldeau** [comment]
On the version 3.5.2 the vpnkit-controller container fails with:

```
2021/08/11 15:14:25 Starting kube-vpnkit-forwarder...
E0811 15:14:25.992992 1 reflector.go:205] github.com/moby/vpnkit/go/cmd/kube-vpnkit-forwarder/main.go:49: Failed to list *v1.Service: services is forbidden: User "system:serviceaccount:kube-system:vpnkit-controller" cannot list resource "services" in API group "" at the cluster scope
E0811 15:14:25.992992 1 reflector.go:205] github.com/moby/vpnkit/go/cmd/kube-vpnkit-forwarder/main.go:49: Failed to list *v1.Service: services is forbidden: User "system:serviceaccount:kube-system:vpnkit-controller" cannot list resource "services" in API group "" at the cluster scope
log: exiting because of error: log: cannot create log: open /tmp/kube-vpnkit-forwarder.vpnkit-controller.unknownuser.log.ERROR.20210811-151425.1: no such file or directory
```

It really looks like a permission issue.

**Comment by stellirin** [comment]
I also had the issue on API Server with `service-account-issuer is a required flag` (but on macOS Big Sur). Reset of Kubernetes was not enough, I had to do a full factory reset of Docker.
