### ISSUE TITLE
System Failure in a Windows System Call - Cant find a specific file

### ISSUE THREAD

**Issue by krowickin** [docker/for-win#11522]
### Major  Minor  Build  Revision
                                                                         -----  -----  -----  --------
                                                                           10     0      14393  0 
==========================================================================================
                                                                               Docker Version:
Client: Mirantis Container Runtime
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        105e9a6
 Built:             05/17/2021 16:36:02
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Mirantis Container Runtime
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       1a7d997053
  Built:            05/17/2021 16:34:40
  OS/Arch:          windows/amd64
  Experimental:     false
==========================================================================================

==========================================================================================
                                                                                   Error:
docker: Error response from daemon: container 84b51d55fc5b40f2ce36cd7a0ec2b8682ee7812f76292bb7c9c4890b5900f15c encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The system cannot find the
file specified. (0x2) extra info: {"CommandLine":"dotnet wrld.dll server.urls http://localhost:4300","WorkingDirectory":"C:\\app","Environment":{"COMPLUS_NGenProtectedProcess_FeatureEnabled":"0"},"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}.
==========================================================================================
### Dockerfile
FROM mcr.microsoft.com/dotnet/framework/sdk:3.5 AS build
WORKDIR /app
# Copy csproj and restore
COPY  /*.csproj ./
RUN dotnet restore
# Copy everything else and build
COPY . . 
RUN dotnet publish -c release -o out
# Build runtime image
FROM mcr.microsoft.com/dotnet/framework/runtime:3.5 AS runtime
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "wrld.dll", "server.urls", "http://localhost:4300"]
==========================================================================================

**Comment by stephen-turner** [comment]
This bug tracker is for Docker Desktop, but it appears you are using Mirantis Container Runtime, so you need to go to Mirantis for support.
