### ISSUE TITLE
I/O errors writing large files to bind-mounted NTFS volumes

### ISSUE THREAD

**Issue by jonscheiding** [docker/for-win#1154]
### Actual behavior

Error message when writing large files to bind-mounted NTFS filesystems:

```
dd: closing output file '/data/test.data': Input/output error
```

### Information

  - Diagnostic ID: 8529DFA3-1774-4DE8-B8E1-8B4193687162/2017-10-02_15-15-59
  - Docker for Windows Community Edition, Version 17.09.0-ce-win32 (13529) stable a94cf27
  - Host: Windows 10 Pro, Version 1703 (OS Build 15063.632)

### Steps to reproduce the behavior

```
docker run --rm -v "//K:/data" ubuntu dd if=/dev/urandom bs=1M count=1000 of=/data/test.dat
```

If K: is an NTFS partition, this command fails with the above error message.

On my system, if I change the command to use `count=100`, it works pretty reliably.  If I change it to `count=200`, it seems to be about 50/50.  Anything above `count=300` fails reliably.

If K: is a FAT32 partition, the command seems to work reliably (this does not provide a workaround for me due to FAT32's file and volume size limitations).

No clues in Docker's `log.txt`, or Windows Event Viewer.

Possibly duplicate or related to #661.

**Comment by jonscheiding** [comment]
Note that this error behavior manifests in various other ways.  I can do any of the following:

```
dd if=/dev/urandom bs=1M count=1000 of=/test.data
cp /test.dat /data
rsync /test.dat /data
tar -zcf /data/test.dat.tar.gz /test.dat
```

All of these will fail with variations of the cited error message.

**Comment by jonscheiding** [comment]
Following along #661, I tried re-mounting the volume from within the container, setting `cache=none` instead of `cache=strict`:

```
docker run --rm -v "//K:/data" -it --privileged --pid=host ubuntu bash
# umount /data
# mount -t cifs //10.0.75.1/K /data -o rw,relatime,vers=3.02,sec=ntlmssp,cache=none,username=<host-username>,domain=<host-domain>,password=<host-password>,uid=0,noforceuid,gid=0,noforcegid,addr=10.0.75.1,file_mode=0755,dir_mode=0755,iocharset=utf8,nounix,serverino,mapposix,nobrl,mfsymlinks,noperm,rsize=16384,wsize=57344,echo_interval=60,actimeo=1
```

The `dd` command works reliably for me after doing that.  It's not really useful as a "real-life" workaround though.

**Comment by jonscheiding** [comment]
Note: I seemingly can no longer reproduce this issue as of Docker for rWindows version 17.12.0-ce-win47.

**Comment by alebianco** [comment]
thanks for the heads-up @jonscheiding 
i'll try that version over the weekend

**Comment by alebianco** [comment]
no joy for me 😞 @jonscheiding 

```
PS > docker -v
Docker version 17.12.0-ce, build c97c6d6
PS > docker run --rm -v E:/out:/out alpine sh -c "dd if=/dev/ur
andom of=random.bin bs=1048576 count=300 && cp random.bin /out/random.bin"
300+0 records in
300+0 records out
cp: error writing to '/out/random.bin': I/O error
```

**Comment by jonscheiding** [comment]
Cannot reproduce any more on recent version of Docker.

- Docker for Windows Community Edition, Version 18.06.0-ce-win32 (19098) stable 5513f91
- Host: Windows 10 Pro, Version 1709 (OS Build 16299.492)

**Comment by davclark** [comment]
FWIW - I'm able to reproduce with a 20GB file, which I understand is also around the limits of what contemporary browsers will tolerate. Using this modified version of @jonscheiding's command:

    > docker run --rm -v "//C/Users/<me>/Desktop:/data" ubuntu dd if=/dev/urandom bs=1M count=20000 of=/data/test.dat 
    dd: closing output file '/data/test.dat': Input/output error

**Comment by mfasold** [comment]
I see the exact same issue with the current Docker CE release (2.0.0.0-win81 (29211), reproducing this on two Windows 10 Pro (Version 1804) systems. I was never able to write files of size 300 MB. 

I'd by curious about technical details explaining the origins of this limit. Needless to say that being able to write files bigger than 200 MB to NTFS bind-mounts would be more than useful.

**Comment by mfasold** [comment]
Just one comment that might be helpful for other users. The issue is still there. I some use cases the issue might be circumvented it by copying the files in and out the Moby VM using "docker cp". Also, Linux Container on Windows (LCOW) uses a different approach to mounting the host filesystem into the container (using 9p) and has no file size limit. However, it is even slower.

**Comment by AlbughdadiM** [comment]
I am facing the same issue working on large files (satellite images). I created a Dockerfile based on Ubuntu 16.04 image and I added all the dependencies needed to run the code.The docker containers run smoothly on Ubuntu 16.04. Once I switch to Windows 10, the I/O error happens randomly (I mean one image can be correctly written to the shared volume and in another run it doesn't). It is also quite annoying since when the error happens, a corrupted output file is produced. Has anyone found a solution for this persisting problem?

**Comment by soumer** [comment]
Same issue for me when trying to copy 1.4GB mkv file to bind mount NTFS volume.
Docker version: 19.03.4, build 9013bf5
Windows 10 Pro Version	10.0.18362 Build 18362

**Comment by sphadley** [comment]
I would be interested to see if the problem still persists on the new wsl2 based docker, but I havent had time to test. It seems reasonable the the new plan9 based file system logic might improve things.

**Comment by cellescent** [comment]
I've been struggling with this for a few weeks, using an Ubuntu-based image on a Windows 10 host; recently, files even as small as a 1.06 GB CSV can't reliably be transferred. As noted above, it creates corrupted output. Sometimes, restarting the container, or even resetting Docker Desktop to factory settings and starting fresh, will make it work for awhile. I've been trying to figure out if there's anything I'm doing that makes it start failing again. No luck identifying a particular pattern as of yet.
