### ISSUE TITLE
Docker desktop failing at the startup

### ISSUE THREAD

**Issue by carbonrider** [docker/for-win#11552]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Docker desktop doesn't start.

### Expected behavior
Docker desktop must start normally.

### Information
If I start Docker desktop, it shows that docker desktop is starting and then throws the following error.
![image](https://user-images.githubusercontent.com/5756215/123762473-7872de80-d8e0-11eb-9dbf-bd8fb2b3aae7.png)

  - Windows Version: 10
  - Docker Desktop Version: 3.4.0.65384
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No. Running on Windows Desktop

executing wsl -l -v lists following
![image](https://user-images.githubusercontent.com/5756215/123762664-a6f0b980-d8e0-11eb-9bf5-7e61d9a79838.png)

The problem is intermittent. I have to restart machine multiple times to start docker desktop normally.

### Steps to reproduce the behavior

There are no specific steps. It just fails to start the docker engine.

Find attached exception stack trace.

[docker_log.txt](https://github.com/docker/for-win/files/6731752/docker_log.txt)

Crash report has been uploaded and following is the diagnostic id
60F49650-D1DA-4916-8C2B-FA4CDDE9BE2C/20210629081247

**Comment by mackdrama1017** [comment]
So am I

**Comment by rohitsathish** [comment]
Me too. Even uninstalling and reinstalling an old version doesn't solve the problem.
