### ISSUE TITLE
Cannot set "allow-nondistributable-artifacts" in advanced config

### ISSUE THREAD

**Issue by kevinbosman** [docker/for-win#1156]
### Expected behavior
Should be able to configure all valid daemon options in the json docker daemon configuration file box in the Advanced section of the Docker Windows Settings/Daemon page, as per the settings at https://docs.docker.com/engine/reference/commandline/dockerd/#on-windows

### Actual behavior
Attempting to add `"allow-nondistributable-artifacts"` to the daemon page in the Settings dialog disables the "Apply" button (greyed out, unclickable) and says in red beneath the edit box:

```
"allow-nondistributable-artifacts" : Invalid Option
```

Further, this `Invalid option` problem occurs for all of the following settings taken from the full example at https://docs.docker.com/engine/reference/commandline/dockerd/#on-windows:

 - `data-root`
 - `max-concurrent-downloads`
 - `max-concurrent-uploads`
 - `shutdown-timeout`
 - `allow-nondistributable-artifacts`

### Information
  - Docker Community Edition Version 17.09.0-ce-win32 (13529), Channel: stable, a94cf27
  - Windows 10 x64 v1709

### Steps to reproduce the behavior

  1. Right click on the Docker icon in system tray
  2. Select "Settings..."
  3. Select "Daemon"
  4. Toggle to "Advanced"
  5. Add any of the above settings into the json file edit box (with correct syntax, valid value, etc)
  6. Observe the greyed out "Apply" button and red text `Invalid option` message

**Comment by kevinbosman** [comment]
Note that this problem still exists in Version 17.09.0-ce-win33 (13620).

To workaround, I needed to take ownership of `C:\ProgramData\Docker\config\daemon.json`, change file permissions, and add the `allow-nondistributable-artifacts` entry manually into that file.

**Comment by andyliddle** [comment]
This use to work in previous version, and without this option we cannot push windows containers to docker registry which brakes out development.

**Comment by friism** [comment]
@andyliddle why can't you push without this setting? Docker Trusted Registry, Docker Hub and the open source registry all work with this.

**Comment by andyliddle** [comment]
@friism ,  As far as i know this is the only way to include foreign layers with your image to a private docker registry.   As both our Live and Development platforms do not have internet access, we need todo this because we need to provide the microsoft/nanoserver image as they cannot get it from the internet.

**Comment by kevinbosman** [comment]
This issue is resolved in Docker Edge Version 17.11.0-ce-win40 (14328).
I cannot say which specific edge release resolved the issue.
