### ISSUE TITLE
Docker for Windows cannot start

### ISSUE THREAD

**Issue by djbingham** [docker/for-win#1157]
### Expected behavior
Docker for Windows should start successfully.

### Actual behavior
Docker for Windows fails to start, showing the following error: "Error response from daemon: Bad response from Docker engine"

### Information
  - Diagnostic ID: 3C8215B0-EFB3-4C45-8628-855CA552984E/2017-10-03_12-27-16
  - Host distribution and version: Windows 10 Pro (version: 1703, OS Build: 15063.608)

This issue started immediately after allowing Docker to update to the latest version this morning.

In my efforts to get it working, I have tried the following (all resulting in the same error when starting Docker for Windows):

- Restart Windows
- Reset Docker to factory defaults
- Uninstall Docker for Windows, then install from scratch with a fresh download of the latest stable release from https://docs.docker.com/docker-for-windows/install/

I attempted to upload a crash report from the error window, but this caused Avast to detect a threat in powershell.exe, which was automatically moved to the virus chest. I tried uploading another crash report after re-installing Docker for Windows, again triggering Avast to detect a threat in powershell.exe.

When I was re-installing Docker, Avast detected a threat in Docker itself early in the installation process, moving (I think, although I didn't make a note of which file) the Docker Service file to the virus chest. I restored that and re-ran the installer, which then complained of not being allowed access to C:\Program Files\Docker\Docker\com.docker.service (this is the file I think I remember Avast messing with). To get around that, I restarted my computer, disabled Avast and then ran the installer, which worked. I've since re-enabled Avast, of course.

At the end of all the above, I still have Docker for Windows failing to start, showing the message "Error response from daemon: Bad response from Docker engine". When I quit Docker for Windows, it popped up saying "Docker for Windows service is not running, would you like to start it?" - I clicked yes, then the app closed fully. The same message appears when starting, but that's normal.

I have just got a different error message when starting Docker again: "Unable to start Docker for Windows service: 2". This time, I disabled Avast before sending the crash report, and so didn't get the powershell warning and the report sent successfully ID above).

Crash report diagnostic ID: 3C8215B0-EFB3-4C45-8628-855CA552984E/2017-10-03_12-45-43

### Steps to reproduce the behavior

  1. Allow automatic update of Docker for Windows to latest version, as of approx. 11am UTC on 3rd September 2017
  2. Attempt to start Docker for Windows

**Comment by djbingham** [comment]
I've just restarted my computer and again got the more recent error when starting Docker for Windows:

Unable to start Docker for Windows service: 2
   at Docker.WPF.BackendClient.CheckService() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:line 296
   at Docker.WPF.BackendClient.SendMessage(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:line 150
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 91
   at Docker.Actions.<>c__DisplayClass16_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 77
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

This time the crash report sent even with Avast running.

Diagnostic ID: 3C8215B0-EFB3-4C45-8628-855CA552984E/2017-10-03_13-00-31

**Comment by djbingham** [comment]
Apologies, it seems I duplicated an already-reported issue (in several threads from the past 18 hours or so). I found the suggestion of installing a specific older version (which I hadn't realised was available as a direct download before). That has at least got Docker for Windows working for me on an older version:

https://github.com/docker/for-win/issues/1148#issuecomment-333677117

**Comment by antdimot** [comment]
Hi I have the same problem. What is the link of the older version for Docker for Windows?

**Comment by gtardif** [comment]
Hi @djbingham, @antdimot, we're having a hard time reproducing this crash ; from your logs the vpnkit.exe process dies and is causing this crash.
Could you try the following builds and let us know if things are working better with one or both of them : 
https://download-stage.docker.com/win/pr/13599/Docker%20for%20Windows%20Installer.exe
https://download-stage.docker.com/win/pr/13601/Docker%20for%20Windows%20Installer.exe
(ignore updates that might get proposed)

*Warning: This version will not auto-update properly to newer versions. It's only meant for testing. 
You must uninstall the version you have currently installed before you install this test version. 
(You might want to backup your MobyLinuxVM from Hyper-V Manager)*

**Comment by djbingham** [comment]
Hi, @gtardif.

Avast is blocking those installers from running, saying that each is "a very rare file". Since very rare files usually contain viruses, it automatically sent the file off for detailed analysis, which is expected to take over 2 and a half hours. I'm not running an installer that my anti-virus thinks is likely to be dangerous.

I'll retry v17.06.2.1319402 (the one that worked for me the other day): https://download.docker.com/win/stable/13194/Docker%20for%20Windows%20Installer.exe

**Comment by gtardif** [comment]
Hi @djbingham, I understand, thanks for your help anyway. We are preparing a candidate release, this should be available soon on the public channel.

**Comment by neliodv** [comment]
Exactly same problem here

**Comment by djbingham** [comment]
I noticed just now that the auto-update was showing a higher version number, with release notes indicating a fix for this issue. I accepted the update and Docker seems to be working fine for me now :smile:

@gtardif and the whole Docker team: thank you very much for the attention and fix.

**Comment by neliodv** [comment]
Thanks @djbingham and Thanks @gtardif and the entire Docker Team.

**Comment by willsilvano** [comment]
Updating to new release now it works! Thanks! @gtardif
