### ISSUE TITLE
Docker for Windows Update Problem

### ISSUE THREAD

**Issue by senrabdet** [docker/for-win#1158]
### Expected behavior
Get message that there is a docker for windows update; wizard way through update, expect update to go in and be done.
### Actual behavior
Update fails to go in; docker won't start; try re-installs, system restores, no joy.  Get message to do factory restore that will wipe existing VM.  Backup VM, try re-install, no joy.  Deleted docker folder in ProgramFiles, installed from scratch, and voila.  Not unique, docker for windows updates have problems about half of the time.
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)
Windows 10 Pro 14393.1715
### Steps to reproduce the behavior

  1. ...get docker message there is an update, with description of issues fixed or enhancements, potentially a kernel update
  2. ...follow the wizard
3....update fails with message....this time, alternatives given included try again or factory reset.
4....tried to download and install from scratch, no joy.  Docker wasn't showing up in programs and features.
5...Eventually, by hand deleted Docker folder in ProgramFiles....then fresh install worked.  Had backed up MobyVM, and fresh install allowed me to continue using that VM where all my containers are (whew).

**Comment by DarkGhostHunter** [comment]
Welcome to the club! [Workaround](https://github.com/docker/for-win/issues/1148#issuecomment-333677117)

**Comment by jgraycs** [comment]
@senrabdet how were you able to hand delete the files? My machine isn't letting me, even though I'm an Administrator:

```
PS C:\Program Files\Docker\Docker\resources\bin> Remove-Item -Force docker.exe
Remove-Item : Access is denied
```

**Comment by jgraycs** [comment]
@DarkGhostHunter appreciate the workaround suggestion. Unfortunately for me, it can't get it to work. The two files left behind by the update process also block a re-installation of 17.06 for me.

**Comment by DarkGhostHunter** [comment]
@jgraycs Try to disable AV or add an exception for that folder. You can also try to restart using only with Microsoft Services enabled and try to delete again.

I had the same problem with Kaspersky some time ago. AV disabled, uninstalled, AV enabled, no problems at all.

**Comment by jgraycs** [comment]
Thanks for the quick reply! I was able to delete the files by going into Safe Mode, so it might have been AV-related. Anyway, after doing that, I was able to run the installer and it completed. Good grief, these updates are too hard, two in a row have now failed for me....
