### ISSUE TITLE
Docker for Windows with mount crashes after shutdown

### ISSUE THREAD

**Issue by DelegenDocker** [docker/for-win#1159]
### Expected behavior
Docker containers with Shared Folders & **mount** load normally after Windows **shutdown**.
### Actual behavior
Docker containers with Shared Folders & **mount** crash the docker service after Windows shutdown.
When performing a Windows **restart** the problem doesn't reproduced, only when performing a **shutdown**.
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu. 
Here's the crash error: [error.txt](https://github.com/docker/for-win/files/1352162/error.txt)
Here's the log: [log.txt](https://github.com/docker/for-win/files/1352165/log.txt)

  - host distribution and version (Windows version, build number, etc)
Version: 17.06.2-ce-win27 (13194)
Channel: stable
Sha1: 428bd6ceae2994bd2fc2a72ec122507abe2cf526
Started on: 2017/10/02 14:55:04.220
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1607
Build: 14393
BuildLabName: 14393.693.amd64fre.rs1_release.161220-1747
### Steps to reproduce the behavior
1. Create a linux based container with mount to a shared drive
2. Run the container
3. Shutdown the OS
4. Turn on the computer
5. Wait for the docker service to load
6. Get a docker crash error

**Thank you all,
David.**

**Comment by jasonbivins** [comment]
Hi @DelegenDocker 
It looks like you're on an older version from the stable channel - can you try updating to the latest stable build?

**Comment by DelegenDocker** [comment]
Hello @jasonbivins 

We'll check that and keep you updated.

Thanks,
David.

**Comment by DelegenDocker** [comment]
Hello @jasonbivins 

Per your suggestion I've upgraded the Docker for Windows on the same host and tried to reproduce the problem, and at seems to reproduce with the same errors.

I've attached the new log file.

Thanks,
David.
[log.txt](https://github.com/docker/for-win/files/1366859/log.txt)

**Comment by DelegenDocker** [comment]
Hi @jasonbivins 

[This](https://github.com/docker/for-win/issues/941#issuecomment-324535767) solution has solved our problem, but i believe that this should be fixed on Docker side as well.

Thanks,
David.
