### ISSUE TITLE
Kubernetes on Docker Desktop hangs in state "Starting"

### ISSUE THREAD

**Issue by Monte-Christo** [docker/for-win#11592]
- [ X] I have tried with the latest version of Docker Desktop
  - [ X] I have tried disabling enabled experimental features
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID: FE7BBBCB-C23E-44A5-940F-F7126DAC88B2/20210703180736

### Actual behavior

I joined my docker-desktop K8s cluster to Azure Arc. Everything works just fine, I can monitor the cluster in Azure, I can deploy apps via GitOps, I can visit the website running on the local cluster, I can kill pods and they are restarted automatically.

When I reboot the PC, Docker Desktop starts up, but K8s is stuck forever (12 hours and going) in state "Starting". 

Resetting the K8s cluster does not help. Only resetting the entire Docker Desktop installation to factory settings made K8s start again. I reconnected the cluster to Azure Arc, and upon another reboot, K8s hangs again in state "Starting".

### Expected behavior
K8s starts up normally.

### Information

  - Windows Version: 20H2, Build 19042
  - Docker Desktop Version: 3.5.1 (66090)
  - WSL2 or Hyper-V backend?  Both
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No, Lenovo P52, 6 cores, 64 GB RAM

I don't think the problem has to do with Azure Arc per se, but it occurs with other workloads and configurations as well. 

The script to join the cluster to Azure Arc is taken from here:
 https://github.com/microsoft/azure_arc.git
azure_arc\azure_arc_k8s_jumpstart\kind\

The app deployed via GitOps is from here:
https://github.com/likamrat/hello_arc.git

### Steps to reproduce the behavior

  1. Clone azure_arc and hello_arc repos
  2. log into Azure
  3. create resource group ArcTest
  4. az provider register --namespace Microsoft.Kubernetes 
    az provider register --namespace Microsoft.KubernetesConfiguration 
    az provider register --namespace Microsoft.ExtendedLocation
    az extension add --name connectedk8s
    az extension add --name k8s-extension
    az extension add --name customlocation
  5. az connectedk8s connect --name docker-desktop --resource-group ArcTest --location westeurope
  6. Edit deployment script parameters in azure_arc_k8s_jumpstart\kind\gitops\helm\az_k8sconfig_helm_kind.sh
    Run deployment script > . .\az_k8sconfig_helm_kind.sh
    See new namespace ‘prod’:>  kubectl get namespaces
    Look at pods in ‘prod: >’ kubectl get pods -n prod
7. Go to demo app web site: http://localhost:80. Working site appears.
8. Reboot 
9. K8s fails to start

**Comment by rohitsathish** [comment]
Facing the same issue

**Comment by metrocoding** [comment]
Diagnostics ID: 8DF3BCBB-7702-4DBB-9C3F-4C8E164C5111/20210825053215
same issue here
latest docker desktop on MacOs BigSur
docker version: 3.6.0(67351)
kubernetes: v1.21.3
