### ISSUE TITLE
Starting microsoft/nanoserver hangs and docker ps hangs

### ISSUE THREAD

**Issue by lbroekhuizen** [docker/for-win#116]
### Expected behavior
Starting the container from kitematic
Start docker cli.
Show running container with docker ps

### Actual behavior
Container hangs in stage starting
docker ps hangs.

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
00DE5373-1382-415E-9896-9FB98E5C1C95/2016-09-30_12-31-30
  - a reproducible case if this is a bug, Dockerfiles FTW
Plain dockerfiles from github, microsoft/nanoserver.
Docker beta
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by dgageot** [comment]
Hello @lbroekhuizen Thank you but the bug report. Yes, we know this issue. It's a shame but until you get Windows update KB3192366, windows containers won't work.

Here's the extract from Beta27 Changelog:
```
Windows Container support relies on the Windows 10 container feature, which is **experimental**
at this point.  Windows 10 Pro (1607, build number 14393) requires update `KB3192366`
(soon to be released via Windows Update) to fully work. Some insider builds may not work.
```

**Comment by friism** [comment]
Also see here: https://github.com/Microsoft/Virtualization-Documentation/issues/358

I'm closing this issue since we can't fix it in Docker for Windows and it's tracked by the Microsoft guys.
