### ISSUE TITLE
Unhandled .NET Framework exception after Docker Desktop installation

### ISSUE THREAD

**Issue by Artonus** [docker/for-win#11607]
- [ X] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID: 34585D1F-E6C6-4FB6-A04A-5755C3954FED/20210706192929

### Actual behaviour
After the fresh installation of Docker Desktop and logging in, the user is greeted with the following error. 
[dockerError.txt](https://github.com/docker/for-win/files/6772397/dockerError.txt)
![DockerError](https://user-images.githubusercontent.com/34897359/124656971-2e6e9780-dea2-11eb-98b2-62757b775583.png)
The error occurs after the fresh installation of the latest version of the Docker Desktop without installing needed files for the WSL2. Only WSL1 present on the system. After opening the Docker Desktop it shows the following message: 
> Docker Engine stopped...

### Expected behaviour
Docker Desktop starts normally.
  - Windows Version: 20H2 19042.1052
  - Docker Desktop Version: 3.5
  - WSL2 or Hyper-V backend?  No
  - Are you running inside a virtualized Windows, e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior
behaviour
  1. Install Docker Desktop excluding WSL2 support
  2. Log out
  3. Log in 
  4. Wait for the error while the system initializes

**Comment by msweetnam** [comment]
same thing happened to me..  I installed fresh install of Docker Desktop for Windows (what ever the latest is as of this writing).. onto Windows version 10.
After the install, it requires a reboot, so i reboot and i get the following error on windows startup (and docker starts but says "Docker Engine Stopped"

System.NullReferenceException: Object reference not set to an instance of an object.
at Docker.Core.Features.Features.d__16.MoveNext() in C:\workspaces\PR-16024\src\github.com\docker\pinata\win\src\Docker.Core\Features\Features.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()...

**Comment by lorenrh** [comment]
I believe this is duplicate of #11601 ?

**Comment by djs55** [comment]
@Artonus Thanks for the diagnostics. The failure seems to be:
```
[21:30:01.546][GoBackendProcess  ][Fatal  ] msg="unable to start fileserver: unable to listen on 4099: A socket operation encountered a dead network."
[21:30:01.550][GoBackendProcess  ][Error  ] Process died
```
According to the `settings.json`:
```
  "wslEngineEnabled": true
```
which requires WSL 2. I think the "dead network" error refers to the lack of hypervisor sockets, due to the lack of Hyper-V, because WSL 2 is not installed.

Could you either install WSL 2 or Hyper-V? If you want to use Hyper-V you can edit `AppData\Roaming\Docker\settings.json` to switch `wslEngineEnabled` to `false`.
