### ISSUE TITLE
image operating system "windows" cannot be used on this platform (Docker already set to windows containers)

### ISSUE THREAD

**Issue by strophanthus** [docker/for-win#1161]
### Expected behavior
Pull image in to created docker environment
### Actual behavior
Error: image operating system "windows" cannot be used on this platform. I expect that my created environment is set to linux? I'm not sure how to change that, or if that is the issue. 
### Information

  - Diagnostic ID: 74BEBBBA-C436-4473-A8BE-FBC3C25662A3/2017-10-03_15-13-53

### Steps to reproduce the behavior

  1. Install Docker
  2. Switch to Windows Containers
  3. docker-machine create -d hyperv --hyperv-virtual-switch "NAVSWITCH" devpreview
  4. docker-machine env devpreview
  5. Execute the listed commands
  6. docker run -m 3G -e ACCEPT_EULA=Y navdocker.azurecr.io/dynamics-nav:devpreview

**Comment by friism** [comment]
Don't use `docker-machine` if you're just using Docker for Windows. You don't have to do:

```
docker-machine create -d hyperv --hyperv-virtual-switch "NAVSWITCH" devpreview
docker-machine env devpreview
```

**Comment by strophanthus** [comment]
Okay, seems I need to do more reading. thanks
