### ISSUE TITLE
Ok, could you file an issue on https://github.com/docker/docker/issues ? Networking with Windows containers is handled in the Core docker project

### ISSUE THREAD

**Issue by Scherlac** [docker/for-win#11610]
Ok, could you file an issue on https://github.com/docker/docker/issues ? Networking with Windows containers is handled in the Core docker project

_Originally posted by @simonferquel in https://github.com/docker/for-win/issues/474#issuecomment-278329786_

**Comment by Scherlac** [comment]
Why is it not docker / for-win topic? Can you please give us feedback, will this issue addressed? Is the issue on radar?

**Comment by stephen-turner** [comment]
It doesn't belong in this repository because the relevant code is not in Docker Desktop, and indeed the Windows container code in the upstream engine was not even written by Docker engineers. Anyway, I see that you've discovered the upstream ticket, which is the one to follow.
