### ISSUE TITLE
WSL distro stopped while waiting for Lifecycle server

### ISSUE THREAD

**Issue by jolsen71** [docker/for-win#11618]
I know there are a number of other tickets reporting this issue or similar to this issue, but I am reporting this potential duplicate anyway since it happening on a fresh install and with the latest version (as of right now of Docker, which is 3.5.1.0) and the other tickets seem to differ in details.

WSL distro stopped while waiting for Lifecycle server.
  >Stdout:

  >Stderr:
2021/07/07 19:37:41 resolving /mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-wsl-cli.iso...
2021/07/07 19:37:41 copying...
Error: mounting wslCLIDest: open /mnt/host/wsl/docker-desktop-data/isocache/98b11d9b24b425a822c7f8ecf6d59a1091b9b60533781b9a00d80e4ffc6adb62.iso: input/output error
2021/07/07 19:37:41 open /mnt/host/wsl/docker-desktop-data/isocache/98b11d9b24b425a822c7f8ecf6d59a1091b9b60533781b9a00d80e4ffc6adb62.iso: input/output error
mounting wslCLIDest
main.doRun
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:230
main.run.func1
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:94
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:850
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:958
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).Execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:895
main.main
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:36
runtime.main
	/usr/local/go/src/runtime/proc.go:225
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1371

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
D53423D6-2110-4B5B-9169-8E5FFABDA3E2/20210707193743

### Actual behavior

After upgrading from 3.3.x to 3.5.x (maybe before, since I've rarely used Docker lately), trying to launch docker failed with it immediately closing and not displaying any messages.

I uninstalled Docker and reinstalled it fresh, and this time when launching Docker I actually received an error message with the ability to report it.

### Expected behavior

Successful launch of Docker and able to use the software.

### Information
  - Is it reproducible?
  Yes, every time I launch docker this happens.
  - Is the problem new?
  It didn't happen the last time I ran docker before today, which was probably a few months ago.
  - Did the problem appear with an update?
  Most likely, but I don't know which Docker update it maybe have been or Windows update.

  - Windows Version: 21H1 19043.1052
  - Docker Desktop Version:  3.5.1.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:
No running docker on the host machine, but a WSL2 Ubuntu instance is also running on the host machine.

### Steps to reproduce the behavior
  1. launch the Docker app by clicking the icon in the Windows Start menu.

**Comment by jolsen71** [comment]
As I continued to try to poke around and troubleshoot things, at some point it seems like my WSL subsystem unexpectedly restarted and then Docker was able to successfully start up. I don't know if the issue is now permanently fixed or if it will be temperamental.

**Comment by lorenrh** [comment]
Thanks for the report. As you seem to have found a fix, I'm closing this. But if the problem persist, don't hesitate to open a new issue.

**Comment by jolsen71** [comment]
To make sure this experience doesn't happen to someone else, perhaps as past of the install/upgrade process, Docker should say a include a prompt stating host machine reboot may is (or may be) required for proper operation. It may also be something to check for on Docker launch?
