### ISSUE TITLE
LCOW Error: failed to start service utility VM

### ISSUE THREAD

**Issue by GabrielTK** [docker/for-win#1162]
### Expected behavior
The linux container starts on Docker EE for Windows Server
### Actual behavior
```
PS C:\Users\Administrador.WIN-T21MTN4RQAH> docker run -ti
busybox sh -f
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
03b1be98f3f9: Extracting  715.2kB/715.2kB
C:\Program Files\Docker\docker.exe: failed to register layer: failed to start service utility VM (applydiff 9655b0c669797710f936bd4722e9d0b564fc9382e03f80914cb970daefc3fe56): container 9655b0c669797710f936bd4722e9d0b564fc9382e03f80914cb970daefc3fe56_svm encountered an error during CreateContainer: failure in a Windows system call: Os dados são inválidos. (0xd) extra info: {"SystemType":"container","Name":"9655b0c669797710f936bd4722e9d0b564fc9382e03f80914cb970daefc3fe56_svm","Layers":null,"HvPartition":true,"HvRuntime":{"ImagePath":"C:\\Program Files\\Linux Containers","LinuxInitrdFile":"initrd.img","LinuxKernelFile":"bootx64.efi"},"ContainerType":"linux","TerminateOnLastHandleClosed":true}.
See 'C:\Program Files\Docker\docker.exe run --help'.
```
### Information

 
```
docker version
Client:
 Version:      17.06.2-ee-3
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   915cbaa
 Built:        Thu Sep 21 23:01:20 2017
 OS/Arch:      windows/amd64

Server:
 Version:      master-dockerproject-2017-10-01
 API version:  1.34 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   1e94a48
 Built:        Sun Oct  1 23:54:29 2017
 OS/Arch:      windows/amd64
 Experimental: true


PS C:\Users\Administrador.WIN-T21MTN4RQAH> docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: master-dockerproject-2017-10-01
Storage Driver: windowsfilter (windows) lcow (linux)
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.447.amd64fre.rs1_release_inmarket.161102-0100)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 5.874GiB
Name: WIN-T21MTN4RQAH
ID: P32O:XBNP:TYAU:SPZC:U74I:G32T:44TO:G2BB:3O3I:A4JW:ALT4:I7FU
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### Steps to reproduce the behavior

  1. Install with [this](https://blog.docker.com/2017/09/docker-windows-server-1709/) instructions.
  2. Run any linux image.

**Comment by jasonbivins** [comment]
Hi @GabrielTK 
Since you're trying to use LCOW - you'll need to upgrade to Windows Server build 1709  (you're on 14393)  
https://blog.docker.com/2017/09/docker-windows-server-1709/

**Comment by GabrielTK** [comment]
Ok. And... Is Hyper-V needed? (My CPU doesn't have SLAT, so I had docker installed through PowerShell)

On Oct 5, 2017 12:27 AM, "Jason Bivins" <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi @GabrielTK<https://github.com/gabrieltk>
Since you're trying to use LCOW - you'll need to upgrade to Windows Server build 1709 (you're on 14393)
https://blog.docker.com/2017/09/docker-windows-server-1709/

**Comment by funky81** [comment]
Hi @GabrielTK , have you found the issues and resolve it ? 
Because I'm having the same problems with my hyperv on nested esxi 6.
just curious how to solve this

**Comment by putz612** [comment]
I am getting this same issue as well.  Has anyone found a way around this?

**Comment by GabrielTK** [comment]
Nothing yet. But, I don't have SLAT on my PC, so I thought that was the cause. But, it used to work when I used ESXI 6.

**Comment by funky81** [comment]
As I check, HyperV VM work fine within nested Hypervisor (through ESXi 6 which I'm using right now)
but why docker can't use it? I see in the latest build of docker and dockerd, VM already created but somehow it didnt worked and there's no log error for this.

**Comment by ormico** [comment]
Getting same error on Windows 1709. Trying to build containers though a TeamCity Build Server Agent

**Comment by DevOpsTry** [comment]
Same issue on windows 17650 
any follow up ?

**Comment by red00dragon** [comment]
I Have still the same problem with Windows 1809. 
How can this issue be solved?

**Comment by jennings1716** [comment]
I m having the same issue. I want to run linux containers on the Windows 2019 VM.

**Comment by hhoangnl** [comment]
Yep, same issue here. Running 1809

**Comment by mojimi** [comment]
Same issue, running windows server 17763 on aws ec2

**Comment by edobarnes** [comment]
Same issue on 1809
