### ISSUE TITLE
After Windows 10 upgrade docker won't start

### ISSUE THREAD

**Issue by passtet** [docker/for-win#11625]
- [] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6233ECF2-AD87-4B96-9E40-A6CE2ACFCE99/20210708131043

### Actual behavior
Error:
![image](https://user-images.githubusercontent.com/5439132/124928370-36e0e280-e008-11eb-9705-ee5a9dc4a185.png)

### Expected behavior
Docker starts normaly

### Information

  - Windows Version: 10
  - Docker Desktop Version: 19.03.13, build 4484c46d9d
  - WSL2 or Hyper-V backend?  Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: not inside other VM just a standard laptop with Windows 10 Pro Desktop

### Steps to reproduce the behavior

  1. Start Docker

**Comment by lorenrh** [comment]
I believe your Docker Desktop version is quite old, therefore I suggest you try the latest release of [Docker Desktop](https://docs.docker.com/docker-for-windows/release-notes/#docker-desktop-352).
