### ISSUE TITLE
Docker Desktop errors on start with System.TimeoutException

### ISSUE THREAD

**Issue by pxslip** [docker/for-win#11628]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BD5AC1BE-DA28-4014-AE52-96E007E89BD8/20210708234230

### Actual behavior

Docker throws a `System.TimeoutException` when trying to start after a reboot

### Expected behavior

Docker starts normally

### Information

This is the third time that a working docker desktop for windows installation has failed for me. I believe the sequence of events required to reproduce this are:

1. Install most recent docker for desktop
2. Move the docker-desktop-data vhd file to another drive (based on this post https://dev.to/kimcuonthenet/move-docker-desktop-data-distro-out-of-system-drive-4cg2)
3. Use docker normally for a period of time
4. Update docker to a newer version using the built-in updater
5. Restart the computer
6. Profit? (More accurately see Docker fail to start)

A .NET error window also appeared with the below log messages at the linked pastebin - https://pastebin.com/Y17yy9Wh

**Comment by EmilyParker24** [comment]
I am having the same problem. No progress so far

**Comment by alexb5** [comment]
I have the same problem.
