### ISSUE TITLE
Docker Session timeout on Start. Linux and WSL2 backend fails to connect 

### ISSUE THREAD

**Issue by EmilyParker24** [docker/for-win#11642]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F5D2CD48-678D-4EA5-A055-4E09571BA225/20210711223346

### Actual behavior
Docker engine in linux container running wsl2 backend hold onf "Docker Engine Starting" for 10 minutes until System.TimeoutException

### Expected behavior
Docker engine starts normally

### Information
  - Is it reproducible? - Likely
  - Is the problem new? - Unsure, similar to others but no workarounds have worked
  - Did the problem appear with an update? - yes, windows security update (end restart) as well as docker desktop windows 3.5.2 update
  - Windows Version: Windows 10 Enterprise 1909
  - Docker Desktop Version: 3.5.1, 3.5.2, and tried 3.3.3
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

Additional Info:
logs show this repeating until timeout with some variation in the rows between:
[LinuxWSL2Engine][info]GET failed with Get "http://unix/forwards/list": dial unix /run/host-services/backend.sock: connect: no such files or directory
(I can add entire log in a comment if helpful)
I have tried-
downgrading- did nothing
Purging data- times out
factory reset - times out
disconnecting/reconnecting wsl
switching to windows container- starts, but cannot switch back to linux, and I need linux for my project
anything that I've found for other similar problems

### Steps to reproduce the behavior

  1. Update windows
  2. Open Docker Desktop

**Comment by lorenrh** [comment]
It appears that you haven't installed WSL 2 correctly, which Docker Desktop uses. Please follow Microsoft's instructions at https://aka.ms/wsl2-install. If it's set up correctly, then the command wsl -l -v should show a version 2 distro.

**Comment by EmilyParker24** [comment]
@lorenrh I do not believe that is the issue, as my WSL list output has been consistent from when it was initially working until now. I have since uninstalled and reinstalled all of WSL 2 and the issue still remains with no changes. My WSL -l -v returns the following:
Name                              State      Version
Ubuntu                        Running   2
docker-desktop-data  Running   2
docker-desktop           Running  2

New Diagnostic ID: 
F5D2CD48-678D-4EA5-A055-4E09571BA225/20210712140127

Upon closer log file inspection after the timeout error, I see the following error: 

[GoBackendProcess  ][Error  ] msg="(e28f9597) f5af7774-VolumePKG C<-S No response GET /settings (0s): Get \"http://ipc/settings\": open \\\\.\\pipe\\dockerBackendApiServer: The system cannot find the file specified.[[STACK]]"

which is the first error to show up. After that then 
[07:39:29.152][VpnKitBridge      ][Error  ] Process died
Then all the WSL errors

Before any errors I see the following warnings:

[9:23.364][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[07:39:23.364][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[07:39:23.366][SettingsLoader    ][Warning] Failed to fetch settings from backend, retrying in 1 sec

Which makes me feel it has something to do with those more so than wsl, especially since wsl has been running fine in the background the entire time

Full Log file:
[log.txt](https://github.com/docker/for-win/files/6802019/log.txt)

**Comment by lorenrh** [comment]
Can you try to go to `\\wsl$\docker-desktop-data\isocache` in Windows explorer and remove all the files in there, and then restart Docker Desktop ?

I believe this issue https://github.com/docker/for-win/issues/8748 seems a bit similar to the problem you are experiencing.

**Comment by EmilyParker24** [comment]
Thank you so much, that fixed it!!
