### ISSUE TITLE
I had a Problem with Docker engine to start

### ISSUE THREAD

**Issue by Jithu-ch** [docker/for-win#11659]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Jithu-ch** [comment]
Docker engine has stopped

**Comment by stakx** [comment]
Same here. Started happening after upgrading to Docker 3.5.2. I posted some more repro info including [a Docker log file](https://github.com/docker/for-win/files/6806923/log.txt) over at https://github.com/docker/for-win/issues/11661#issuecomment-878857672.
