### ISSUE TITLE
Does Docker engine support Linux Containers on Windows Server 2019?

### ISSUE THREAD

**Issue by arkoppan** [docker/for-win#11679]
Does Docker engine support Linux Containers on Windows Server 2019?

The DockerMsftProvider does not have a package to install dockercli.exe to switch to Linux Containers.

Dockercli is also not available in MS DockerProvider module.

Found that Linux Containers on Windows has been deprecated with the latest version of Docker (20.10).

======================
Deprecated Engine Features | Docker Documentation
https://docs.docker.com/engine/deprecated/#linux-containers-on-windows-lcow-experimental

Linux containers on Windows (LCOW) (experimental)
Deprecated in Release: v20.10
The experimental feature to run Linux containers on Windows (LCOW) was introduced as a technical preview in Docker 17.09. While many enhancements were made after its introduction, the feature never reached completeness, and development has now stopped in favor of running docker natively on Linux in WSL2.
Developers who want to run Linux workloads on a Windows host are encouraged to use Docker Desktop with WSL2 instead.
=======================

Tried to install WSL2 on Windows Server 2019 but having lot of issues to get Docker to work with Linux Containers.

Is this feature to run Linux Containers on Windows Servers supported yet?

**Comment by stephen-turner** [comment]
No, sorry, there is no support for Linux containers on Windows Server. We would recommend using a Linux server instead, which would be a technically much simpler solution.

**Comment by arkoppan** [comment]
Thank you for the confirmation.
