### ISSUE TITLE
Docker does not start

### ISSUE THREAD

**Issue by subprime** [docker/for-win#1167]
### Expected behavior
Docker shall start if Windows starts.

### Actual behavior
On each boot docker can't start. The Error response is:

```
Error response from daemon: Bad response from Docker engine

   bei Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\DockerDaemonChecker.cs:Zeile 63.
   bei Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:Zeile 252.
   bei Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:Zeile 123.
   bei Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:Zeile 47.
   bei Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:Zeile 145.
```

I have the same behavior on my company laptop?!

### Information

  - Diagnostic ID: 5BE713F8-211F-4B90-9D47-C9860BBB53BA/2017-10-04_19-09-27
  - Docker Version: Version 17.09.0-ce-win32 (13529), Channel: stable, a94cf27
  - Host Informations: Windows 10 Professional x64

**Comment by subprime** [comment]
Note; If i switch to windows containers then docker starts. If i switch back then not.

**Comment by liuluheng** [comment]
meet the same problem

**Comment by stasburn** [comment]
Seems problem in new Docker for Windows service, so I can suggest next workaround:
go to Services
change Docker for Windows service user from LocalSystem to some administrator. 
It works ;)

**Comment by ikawka** [comment]
+1 here

**Comment by aaronsturm** [comment]
They're testing out fixed releases in this issue https://github.com/docker/for-win/issues/1148#issuecomment-334490322

**Comment by subprime** [comment]
@aaronsturm Thanks. It seems to work.
