### ISSUE TITLE
How to disable WSL2 to all users on Docker Desktop?

### ISSUE THREAD

**Issue by sasith2** [docker/for-win#11682]
I need to disable the wsl2 for all the users
I do not want them to do it alone
I'm looking for a setting that will disable WSL2
For the software to load with HYPERV

**Comment by stephen-turner** [comment]
You can modify this directly in the settings file, AppData\Roaming\Docker\settings.json (the setting is "wslEngineEnabled").

But I'm interested to know your reasons for preferring Hyper-V. WSL 2 is generally a superior solution in our experience. What is making you prefer Hyper-V?

**Comment by sasith2** [comment]
We use citrix vdi
And they not support WSL2 yet

בתאריך יום ה׳, 15 ביולי 2021, 17:34, מאת Stephen Turner ‏<
***@***.***>:

**Comment by stephen-turner** [comment]
I see. That's weird that they would support Hyper-V but not WSL 2. I could understand supporting neither, as nested virtualization is complicated, but I would have thought if Hyper-V works then WSL 2 would.
