### ISSUE TITLE
Cannot Start Any version of Docker on WSL2

### ISSUE THREAD

**Issue by KOGI** [docker/for-win#11685]
This started with https://github.com/docker/for-win/issues/11568 and not being able to run 3.5.1 immediately after upgrading. I finally got back on the road by downgrading all the way to 3.3.3. Worked fine for a couple weeks and then just randomly decided to stop working again. I've tried upgrading back to 3.5.2, 3.5.1, 3.4.0, and even completely uninstalling and freshly installing 3.3.3 again. NONE of them will start. I'm completely dead in the water at this point.

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: **58DA0264-ED3E-4556-A271-7A77ADBB4F08/20210715173413**

### Actual behavior
Cannot start any version of docker desktop on WSL2

### Expected behavior
Able to start any version of docker desktop on WSL2

**Comment by stephen-turner** [comment]
If you can't get any version to work, even versions that have worked before, then maybe WSL 2 is corrupt. Have you tried uninstalling and reinstalling WSL 2?

**Comment by Michael-Brooks** [comment]
> 
> 
> If you can't get any version to work, even versions that have worked before, then maybe WSL 2 is corrupt. Have you tried uninstalling and reinstalling WSL 2?

I'm also having issues but it seems to be a problem with .NET. I tried downgrading .NET but I'm not sure if I did it correctly. I also downgraded Docker to different versions and reinstalled WSL2 and the Virtual Machine Platform with the exact same issue.

My issue was closed but it can be seen here #11681

**Comment by KOGI** [comment]
> If you can't get any version to work, even versions that have worked before, then maybe WSL 2 is corrupt. Have you tried uninstalling and reinstalling WSL 2?

I didn't completely uninstall it because I'm not prepared to lose my Ubuntu installation/environment along with it. However, I did update the WSL2 kernel, but it didn't help the problem.

**Comment by lorenrh** [comment]
Can you try to go to `\\wsl$\docker-desktop-data\isocache` in Windows explorer and remove all the files in there, and then restart Docker Desktop ?

**Comment by KOGI** [comment]
@lorenrh I managed to get things working over the weekend before you posted this. Although, I'm not 100% sure what the fix was, I _believe_ it was resetting the virtual network adapter that did the trick (`Restart-NetAdapter -Name "vEthernet (WSL)"`)

I will definitely keep your suggestion in my back pocket, though, if something like this ever happens again!

**Comment by lorenrh** [comment]
I'm glad you have it working now. I'll close this ticket for now, but if you experience any other issue feel free to open a fresh ticket.
