### ISSUE TITLE
Cannot install docker for windows on windows 10 pro

### ISSUE THREAD

**Issue by vasuse7en** [docker/for-win#1168]
### Expected behavior
Should Install on windows 10 pro
### Actual behavior
![image](https://user-images.githubusercontent.com/16218127/31190693-753aac26-a959-11e7-9439-b6b69ee51204.png)

### Information
After executing the installer following message is shown
![image](https://user-images.githubusercontent.com/16218127/31190723-928a59fc-a959-11e7-8c0b-36921c372ea0.png)

### My windows version
![image](https://user-images.githubusercontent.com/16218127/31191586-4208bd2c-a95c-11e7-90ab-afc03a55ef99.png)

### Steps to reproduce the behavior

  1. ... Download the Installer from https://store.docker.com/editions/community/docker-ce-desktop-windows
  2. ... Execute the installer

**Comment by jasonbivins** [comment]
Hi @vasuse7en 
It looks like you're on an early build (10240) of Windows 10 and you'll need to upgrade to at least build [10586](https://docs.docker.com/docker-for-windows/install/#what-to-know-before-you-install)
