### ISSUE TITLE
Doesn't work on windows 11 (beta).

### ISSUE THREAD

**Issue by ahmetcanpolat** [docker/for-win#11691]
hello everyone it's like early for windows 11 but i am a bit of a curious developer, i needed to install docker for my laravel project i finished the installation but after restart it didn't work

I gave up on uploading, thanks anyway.

**Comment by Michael-Brooks** [comment]
It has worked with Windows 11 before the end of this week but something has broken with an update. I can comment here once I've confirmed the fix.

**Comment by maikebing** [comment]
https://github.com/microsoft/WSL/issues/7508

**Comment by maikebing** [comment]
https://github.com/docker/getting-started/issues/207
