### ISSUE TITLE
Unable to login in Docker Desktop

### ISSUE THREAD

**Issue by M-C-K** [docker/for-win#11697]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Unable to login using Docker Desktop
### Information

  - Windows Version: Windows 10
  - Docker Desktop Version:v20.10.7
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by M-C-K** [comment]
I am able to login in the website, but no the Desktop

**Comment by lorenrh** [comment]
have you tried to login from the CLI or the UI?

**Comment by M-C-K** [comment]
thanks..it is fixed
