### ISSUE TITLE
No switch to windows containers in docker for win beta 27

### ISSUE THREAD

**Issue by kksat** [docker/for-win#117]
### Expected behavior

docker --version
Docker version 1.12.2-rc1, build 45bed2c, experimental
(27 beta)

right mouse Click on docker icon in tray - menu option to switch to windows docker containers.

### Actual behavior

right mouse Click on docker icon in tray -  NO menu option to switch to windows docker containers.

### Information
A diagnostic was uploaded with id: ECA7C915-7564-4ADD-8988-5E4E6D9325ED/2016-09-30_20-46-39

### Steps to reproduce the behavior
right mouse Click on docker icon in tray -  NO menu option to switch to windows docker containers.
docker is running

**Comment by dgageot** [comment]
Hi @kksat which version of windows 10 do you have? Windows containers are only supported on  buildNumber >= 14372

**Comment by dgageot** [comment]
@kksat Can you make sure you have all the latest Windows updates? See here: Microsoft/Virtualization-Documentation#358

**Comment by kksat** [comment]
Thank you, @dgageot. I have build lower than 14372. i will update my windows 10.
