### ISSUE TITLE
Docker Desktop doesn't start anymore

### ISSUE THREAD

**Issue by vincent-lg-ma** [docker/for-win#11712]
\

  - [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 5BB17405-39A9-4F31-8DBE-5B156B791B6F/20210719162120

### Actual behavior

After installing Docker Desktop for Windows, I used it for a few minutes in WSL to create a simple container.  Docker then stopped working.  Uninstalling, reinstalling Docker doesn't do anything.  Purging data, through the Docker troubleshoot options or manually when Docker has been removed (the personal data in C:\Users\...\AppSettings and the ones in Program Files) doesn't do any good.

Right now, Docker Desktop doesn't start with the system.  When I click on the Docker Desktop icon on my desktop, the dashboard opens.  The status of Docker is "starting".  And this lasts a minute before Docker gives up:

> Docker Engine failed to start...

Resetting Docker to "factory default" doesn't do any good either.  I'm not sure what to do.

### Expected behavior

It would be nice if Docker started, to be sure.  I have used it numerous times on Windows and never saw this kind of behavior.

### Information

  - Windows Version: 10 Pro (10.0.19041, Build 19041)
  - Docker Desktop Version: 20.10.7, build f0df350
  - WSL2 or Hyper-V backend? WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no
  - Is it reproducible? yes, on my machine, so probably no
  - Is the problem new? no
  - Did the problem appear with an update? possibly a Windows update as others have reported similar issues

### Steps to reproduce the behavior

As stated, I cannot produce a consistent sep of steps that would create the same issue for any other machine.

Thank you for your time,

**Comment by rowanfuchs** [comment]
I'm experiencing the same issue
