### ISSUE TITLE
Unable to install Docker in Window 10 Enterprise

### ISSUE THREAD

**Issue by kamalakannan-87** [docker/for-win#1171]
### Expected behavior
Installation Should complete
### Actual behavior
Installation is stuck in "Unpacking files:resources/qemu-img/COPYING
### Steps to reproduce the behavior

  1. Download latest stable version of docker for window
  2. double click the downloaded file

**Comment by kamalakannan-87** [comment]
![issue](https://user-images.githubusercontent.com/29631685/31214157-9e22b264-a9c7-11e7-8dba-bd3567dc5975.png)

**Comment by jasonbivins** [comment]
Hi @kamalakannan-87 

We pushed new releases on the Edge and Stable channels this weekend specifically to target startup and installation/upgrade issues.
Can you try the new version and let me know if it's still getting stuck?
https://docs.docker.com/docker-for-windows/install/

**Comment by sampleapp** [comment]
same issue with latest Stable or Edge with docker for windows exe installation. However legacy msi installer working fine. Also Edge installation files has virus warning by Symantic. 
![capture](https://user-images.githubusercontent.com/23718223/32981834-a8cd912e-cca0-11e7-8038-d479b0bc04c9.PNG)

**Comment by mayu2085** [comment]
same issue with 17.12.0-ce-47 version
![image](https://user-images.githubusercontent.com/28859809/36939328-413064d8-1f2f-11e8-90f3-673d2ee4fdd9.png)

**Comment by alejunco** [comment]
I've been trying to install docker for windows since last week. Disable "Real-time protection" in "Virus & threat protection settings" after that you can turn it back on if you want. Good luck
