### ISSUE TITLE
New `desktop-linux` / `desktop-windows` contexts cause problems when switching OS mode

### ISSUE THREAD

**Issue by bwateratmsft** [docker/for-win#11721]
- [x] I have tried with the latest version of Docker Desktop (I'm on 3.5.2)
  - [x] I have tried disabling enabled experimental features N/A
  - [x] I have uploaded Diagnostics N/A
  - Diagnostics ID: N/A

### Actual behavior
1. Start Docker Desktop for Windows on Linux containers mode.
2. Run `docker context ls`. There's two by default as of 3.5.0, `default` and `desktop-linux`.
3. Switch to `desktop-linux` with `docker context use desktop-linux`.
4. Switch to Windows containers.
5. Attempt any `docker ...` command. You get the error: `Current context "desktop-linux" is not found on the file system, please check your config file at C:\Users\username\.docker\config.json`. Even `docker context use desktop-windows` does not work, with the same error.
6. Switch back to Linux containers. The error *still* persists, even though this context does exist now!

The only way I've found to make the error go away is to manually edit `~/.docker/config.json` by setting the context to `default`.
Note: You can reproduce the same behavior if you go from Windows containers -> Linux containers with `desktop-windows`.

This reproduces every time.

### Expected behavior
1. Switching from Linux to Windows containers or vice versa should automatically switch from `desktop-linux` to `desktop-windows` or vice versa.

### Information

  - Windows Version: 21H1
  - Docker Desktop Version: 3.5.2
  - WSL2 or Hyper-V backend: WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

**Comment by bwateratmsft** [comment]
Found this while investigating microsoft/vscode-docker#3054.

**Comment by stephen-turner** [comment]
@djs55 Is this the thing you fixed already?

**Comment by bwateratmsft** [comment]
@lorenrh mentions at the end of that issue that the fix is released in 3.5.2; I can repro this in 3.5.2 so I'm guessing it's related but not the same.

**Comment by stephen-turner** [comment]
OK, we'll have another look at it.

**Comment by djs55** [comment]
Thanks for the detailed repro steps, I think I understand what's going on. In a previous version we automatically switched people from `default` to `desktop-linux` (and `desktop-windows`) but this caused some problems where software assumed the use of `default`. We took out the automatic switch in the latest release to fix this, but now, if you *have* manually switched to `desktop-linux`, you get stranded there if Desktop is switched to Windows containers.

I think we need to adjust the logic to
- leave people who don't care on `default` (to minimise interactions with software which isn't yet context-aware)
- for people who have "opted-in" to the new contexts by `docker context use desktop-...` we should keep them up-to-date by switching them automatically (as you suggest)

I'll add a ticket to our backlog for this!

**Comment by trungutt** [comment]
The official 4.1.0 release is out with a fix included, so I close this ticket
