### ISSUE TITLE
Docker integration does exit -1, if WSL distro default user is not root

### ISSUE THREAD

**Issue by R-Rudolf** [docker/for-win#11726]
- [ x ] I have tried with the latest version of Docker Desktop
  - [ x ] I have tried disabling enabled experimental features
  - [ x ] I have uploaded Diagnostics
  - Diagnostics ID: D620D509-D9FE-4F6D-894C-5E288E38FA3D/20210721090252

### Actual behavior
When starting or restarting docker for windows, it fails to integrate with my imported wsl distro.
"WSL integration with distro xxx unexpectedly stopped with exit code 1."
The docker commands, like `docker ps` do not work, instead, the following error message is received:
"Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"

This issue only appears if I edit /etc/wsl.conf file, and add a default user, other than root.

### Expected behavior
I can use my imported distro image with docker integration, even if I have a default user.

Have some additional guidance on user permissions for the default user for docker integration to work.
This guide would be the best place for that info:
https://docs.docker.com/docker-for-windows/wsl/

### Information

It is reproducible if I change the default user with the /etc/wsl.conf file, if I remove it, it is resolved.

  - Windows Version: Version	10.0.19042 Build 19042
  - Docker Desktop Version: 3.5.2 (66501)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Steps to reproduce the behavior
Inside WSL distro (myDistro), expected to have docker integration:
```
useradd -m -u 1001 -p 7y/m6raU1wRE2 -s /bin/bash foobar
adduser foobar wheel
adduser foobar sudo

echo "[user]" >> /etc/wsl.conf
echo "default = foobar" >> /etc/wsl.conf
```
On windows:
`wsl --shutdown ; wsl --shutdown`
Restart Docker for Windows.

**Comment by R-Rudolf** [comment]
Found some workaround:
 - Add default user to the docker group.
 - Initiate docker integration manually, with elevated permissions:
 `sudo /mnt/wsl/docker-desktop/docker-desktop-proxy --distro-name myDistro --docker-desktop-root /mnt/wsl/docker-desktop`
 
 Without the elevation, it writes the error:
 "FATA[0000] open /run/docker-desktop-proxy.pid: permission denied"

**Comment by lacafjh** [comment]
> Found some workaround:
> 
> * Add default user to the docker group.
> * Initiate docker integration manually, with elevated permissions:
>   `sudo /mnt/wsl/docker-desktop/docker-desktop-proxy --distro-name myDistro --docker-desktop-root /mnt/wsl/docker-desktop`
> 
> Without the elevation, it writes the error: "FATA[0000] open /run/docker-desktop-proxy.pid: permission denied"

I am trying to solve that but there seems no file in `/mnt/wsl/docker-desktop`. Should l create those files manually?
