### ISSUE TITLE
Docker Desktop crash at login

### ISSUE THREAD

**Issue by sanderv** [docker/for-win#11732]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Docker is set to startup at login. It crashes within a few seconds. After closing, reopening the Docker Desktop app starts without a glitch.

### Expected behavior
Starts up at login without errors.

### Information

  - Windows Version:
  - Docker Desktop Version: 3.5.2 (66501)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Virtualized Windows

### Steps to reproduce the behavior

  1. Log in
  2. Observe crash report

**Comment by sanderv** [comment]
I also tried the suggested 'reset to defaults', but the day after it crashed again.

**Comment by Apidwalin** [comment]
[Docker Data Processing Agreement 2021.pdf](https://github.com/docker/for-win/files/6865332/Docker.Data.Processing.Agreement.2021.pdf)

**Comment by lorenrh** [comment]
Thank you for the report. Unfortunately Docker Desktop is not supported in a virtualised environment (see https://docs.docker.com/docker-for-windows/install/#whats-included-in-the-installer and https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-desktop-in-nested-virtualization-scenarios). It's out of our control whether it works or not: it depends whether the outer hypervisor can fully run Hyper-V or WSL 2. Sometimes enabling nested virtualisation in the outer hypervisor makes it work, but there are no guarantees.
