### ISSUE TITLE
Kubernetes stops accepting connections on 6443 port periodically

### ISSUE THREAD

**Issue by izhovkin** [docker/for-win#11731]
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 73605DB5-E83B-4D79-8084-1FEF34C5C049/20210722051341

### Actual behavior
Periodically when accessing kubernetes using kubectl I get error "The connection to the server kubernetes.docker.internal:6443 was refused". Docker itself seems to work fine - docker CLI commands like docker ps works correctly and show running k8s containers. I also can't connect to my services deployed in k8s.
Restarting Docker helps, but after some time issue appears again.
### Expected behavior
kubectl should connect without problems.
### Information
  - Windows Version: 20H2 (OS Build 19042.928)
  - Docker Desktop Version:  3.5.2 (66501)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

After restarting Docker I see in Windows process com.docker.backend.exe listens on port 6443.
But when issue appears I see no process listening on port 6443. I suppose something happens with com.docker.backend.exe process, maybe it crashed.

### Steps to reproduce the behavior
No steps, issue appears sporadically.

**Comment by dave-b-code** [comment]
+1, have been suffering from this issue 'connectex: No connection could be made because the target machine actively refused it.'. Usually occurs for me when I have 100+ pods and relatively high I/O.

**Comment by thomastomanek** [comment]
Also seeing this on 3.5.2. It happens every few hours.

**Comment by cculver** [comment]
I wanted to report that I'm seeing strange behavior as well. The docker backend stops listening on ports on the IPv4 stack a few hours (random timing) after I start my containers. IPv6 is unaffected. I can't get them to start listening again on IPv4 until I restart my containers.

**Comment by cculver** [comment]
Also, I downgraded to 3.5.0 and the issue persisted. I downgraded to 3.4.0 and the issue is no longer present.
