### ISSUE TITLE
docker system prune deletes Default Switch and HvsiIcs on windows

### ISSUE THREAD

**Issue by AceHack** [docker/for-win#1174]
### Expected behavior
docker system prune only deletes container networks not built in Hyper-V networks

### Actual behavior
docker system prune actually deletes built in Hyper-V networks in windows Default Switch and HvsiIcs

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
CB980F31-37E6-4F94-8622-E16E6ADBFA2A/2017-10-05_11-16-09
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)
Windows 10 Enterprise Build 16299.rs3_release.170922-1354
Docker 17.09.0-ce, build afdb6d4

### Steps to reproduce the behavior

  1. run docker system prune
  2. see that Default Switch and HvsiIcs are deleted

**Comment by kamkie** [comment]
it is very annoying

**Comment by kallie-b** [comment]
@jmesser81

**Comment by christianacca** [comment]
Please reopen as this is still a problem. 

Thanks

## Docker version

Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:51 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     true

## System info

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17134 N/A Build 17134
