### ISSUE TITLE
Docker Engine dies when Service Fabric local cluster starts

### ISSUE THREAD

**Issue by ericmaia** [docker/for-win#1175]
I don't know if this is a Docker issue or a Service Fabric issue, or a Hyper-V limitation?

### Expected behavior
Microsoft Service Fabric SDK local cluster and Docker Engine will run simultaneously so Service Fabric can deploy a container into the local cluster.

### Actual behavior
Docker For Windows (using Windows containers) works until Service Fabric local cluster is started. Once the local cluster is started and connected, Docker returns the error "Error response from daemon: open \\.\pipe\docker_engine_windows: The system cannot find the file specified."

### Information

  - Diagnostic ID: 66EE82B1-541B-422A-A4DA-A8E5F365095D/2017-10-05_12-01-46
  Docker CE 17.09.0-ce-win32 (13529)
 Windows 10 Enterprise
Service Fabric Tools 1.6.20170504.1

### Steps to reproduce the behavior

I have created a Service Fabric Container project in Visual Studio using the Service Fabric SDK and I am trying to publish it to my local cluster for testing. It includes a Windows container that I have successfully built and run in Docker. Service Fabric is unable to load the image, and after more testing I noticed that Docker was broken.

  1. Start Docker and confirm that it is running (e.g. run "docker images" in console)
  2. Start Service Fabric local cluster and wait until it gives notification that the cluster is started and it has connected to the cluster.
  3. Try to use Docker (e.g. run "docker images" in console)
  4. Get response "Error response from daemon: open \\.\pipe\docker_engine_windows: The system cannot find the file specified."
 5. Stop Service Fabric local cluster and wait for notification that it is stopped.
 6. Restart Docker in Docker Settings
 7. Try to use docker and confirm that it is running.

**Comment by RajeetN** [comment]
Service Fabric does not support containers deployment on Windows 10.

**Comment by ericmaia** [comment]
OK, thanks, that was not clear from the documentation.

**Comment by ffigu002** [comment]
I am getting this exact same problem running Windows Sever 2016 on hyper-V

**Comment by RajeetN** [comment]
Does it have docker 17.03 ee installed?

**Comment by ffigu002** [comment]
Hi RajeetN, I'm using the following version, along with the error after spinning up the Service Fabric Cluster

Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64
Error response from daemon: open \\.\pipe\docker_engine_windows: The system cannot find the file specified.

**Comment by RajeetN** [comment]
SF requires ee version of docker on windows. minimum required is 17.03ee. We will update the documentation to reflect that. @ericmaia the documentation below has a note saying windows 10 is not currently supported.

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-containers-overview

**Comment by ffigu002** [comment]
@RajeetN Ohh okay, I see that. Thanks for the reply.

**Comment by softarch74** [comment]
@rajeetN where is it documented about using Docker EE vs CE? 

CE will install on Win Svr 2016 too, and the docs say to use the CE (Docker for Windows) variant.

Is it a bug in the docs?

**Comment by Orental5** [comment]
I have the problem on windows 2016 with docker ee version 17.06.2-ee-10, with SF 6.2 ver.

is there any solution for this problem?

**Comment by danny156** [comment]
@Orental5 same here.
Any one can help ?

**Comment by Orental5** [comment]
@danny156 The problem was solved by installing Docker for windows
