### ISSUE TITLE
Docker Desktop Can Not Start  After Update

### ISSUE THREAD

**Issue by ArslanAhmet** [docker/for-win#11759]
- [ X] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Docker Desktop Can Not Start after Update
### Expected behavior
Docker Desktop Start Normally
### Information
It is reproducible
The problem appears with an update(3.5.2).

  - Windows Version: Windows 10 Enterprise 19043.1110
  - Docker Desktop Version: 3.5.2
  - WSL2 or Hyper-V backend?  WSL2 
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Virtualized Windows 

### Steps to reproduce the behavior
  1. Starting Docker Desktop
  2. Docker Desktop hangs and says that "Docker Engine starting..."
 Log Content:
[log.txt](https://github.com/docker/for-win/files/6878214/log.txt)

**Comment by lorenrh** [comment]
Thank you for the report. Unfortunately Docker Desktop is not supported in a virtualised environment (see https://docs.docker.com/docker-for-windows/install/#whats-included-in-the-installer and https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-desktop-in-nested-virtualization-scenarios). It's out of our control whether it works or not: it depends whether the outer hypervisor can fully run Hyper-V or WSL 2. Sometimes enabling nested virtualisation in the outer hypervisor makes it work, but there are no guarantees.

**Comment by ArslanAhmet** [comment]
> Thank you for the report. Unfortunately Docker Desktop is not supported in a virtualised environment (see https://docs.docker.com/docker-for-windows/install/#whats-included-in-the-installer and https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-desktop-in-nested-virtualization-scenarios). It's out of our control whether it works or not: it depends whether the outer hypervisor can fully run Hyper-V or WSL 2. Sometimes enabling nested virtualisation in the outer hypervisor makes it work, but there are no guarantees.

Sorry for the wrong information for the environment. I do not use virtualized environment, I just installed it on my computer. It is native.
