### ISSUE TITLE
Failed to deploy distro docker-desktop.. Logon failure: the user has not been granted the requested logon type at this computer.

### ISSUE THREAD

**Issue by FabianPiconeDev** [docker/for-win#11755]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3851BF9C-1225-4C40-8333-FB937F556F7A/20210726110626

```
System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\fbp\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Logon failure: the user has not been granted the requested logon type at this computer.
```

### Actual behavior
Docker for desktop fails to start

### Expected behavior
Docker for desktop should start

### Information
  - Is it reproducible? Yes, when I quit docker, and start to boot docker.
  - Is the problem new? Yes
  - Did the problem appear with an update? No
  - Windows Version: 10.0.19043 Build 19043
  - Docker Desktop Version: 3.5.2
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior
  1. Start docker for desktop

**Comment by FabianPiconeDev** [comment]
Fixed temporary manually by restarting the service `Hyper-V Host Compute Service`. Maybe should docker try to restart it by himself, or would it be a problem?

**Comment by FabianPiconeDev** [comment]
Happened again after PC reboot, and after some hours were passed before trying to start docker for win. Here a screen with another error popup (Microsoft .NET Framework) that appears overlayed to the docker for win error, which hinders me to interact with docker for win.

![again](https://user-images.githubusercontent.com/4472725/127851992-85267a09-96e4-4d5b-8126-d22128f7ed9b.PNG)

**Comment by greenmooseSE** [comment]
Got the same issue after windows update and resolved it by removing/adding Hyper-V windows features and re-installing Docker Desktop (see [link](https://medium.com/@kobexu1999/how-to-resolve-docker-not-been-granted-logon-failure-0x80070569-8e6e1acdee88))
