### ISSUE TITLE
Updater window steals focus

### ISSUE THREAD

**Issue by knighty** [docker/for-win#1179]
### Expected behavior

Updater does not steal focus

### Actual behavior

Updater steals focus when the window pops up.

### Information

  - Diagnostic ID: FA3ACBA3-9A26-4A6A-B5BA-EA4ED6A42914/2017-10-06_09-55-56
  - Windows 10 Pro
  - Version 17.06.2-ce-win27 (13194)

### Steps to reproduce the behavior

  1. Be playing a fullscreen game or doing anything else on your computer
  2. Proceed to be quite annoyed when the updater window steals focus and kicks you out of the game.

**Comment by jasonbivins** [comment]
Hi @knighty   I reported this as an enhancement request, I'll go ahead and close this one out.

Thanks!
