### ISSUE TITLE
docker-compose ports: does not listen on loopback (localhost, 127.0.0.1)

### ISSUE THREAD

**Issue by AceHack** [docker/for-win#1180]
### Expected behavior
docker-compose up will expose any ports: on the yml files on localhost and 127.0.0.1 (loopback)
docker run -p will expose ports on loopback

Please see supporting documentation as to why this is expected behavior given I have the Windows Creators Update.  This is stated as supported directly in Microsoft's and Docker's own documentation.

https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-networking
nat – containers attached to a network created with the 'nat' driver will receive an IP address from the user-specified (--subnet) IP prefix. **Port forwarding / mapping from the container host to container endpoints is supported.**

https://docs.docker.com/engine/examples/dotnetcore/#build-and-run-the-docker-image
**Go to localhost:8080 to access your app in a web browser.**
If you are using the Nano Windows Container and **have not updated to the Windows Creator Update** there is a bug affecting how Windows 10 talks to Containers via “NAT” (Network Address Translation). You must hit the IP of the container directly. You can get the IP address of your container with the following steps: 
Run docker inspect -f "{{ .NetworkSettings.Networks.nat.IPAddress }}" myapp
Copy the container ip address and paste into your browser. (For example, 172.16.240.197)

### Actual behavior
docker-compose up only exposes ports: on the actual host external IP or host machine name
docker run -p only exposes ports: on the actual host external IP or host machine name

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
CB980F31-37E6-4F94-8622-E16E6ADBFA2A/2017-10-05_21-56-20
  - a reproducible case if this is a bug, Dockerfiles FTW
[rabbitmq-nanoserver-insider.zip](https://github.com/docker/for-win/files/1361329/rabbitmq-nanoserver-insider.zip)
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)
Windows 10 Enterprise Build 16299.rs3_release.170922-1354
Docker 17.09.0-ce, build afdb6d4

### Steps to reproduce the behavior

  1. Run docker in windows mode
  2. Build the attached docker file of rabbitmq on windows nano server
  3. Run the attached up.cmd or docker-compose up command or docker run -p
  4. Try to browse to https://localhost:62334 and it does not work
  5. Try to browse to https://{HostMachineNameOrHostExternalIP}:62334 and it works

**Comment by friism** [comment]
@AceHack the .NET Core example that you reference is using Linux containers, where localhost works.

**Comment by AceHack** [comment]
@friism it says If you are using the **Nano Windows Container** that is a windows container.  It says localhost will work as long as you have the creators update.

**Comment by AceHack** [comment]
@friism It also says this examples works on both windows and Linux.

Add the text below to your Dockerfile for either Linux or Windows Containers. The tags below are multi-arch meaning they will pull either Windows or Linux containers depending on what mode is set in Docker for Windows. Read more on switching containers.
