### ISSUE TITLE
Docker Desktop will not start after Windows 11 update

### ISSUE THREAD

**Issue by lofbacke** [docker/for-win#11805]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D546E9F4-8C1F-48CE-A431-189457BE23FB/20210731170524

### Actual behavior
When I start my computer after upgrading from Windows 10 to Windows 11, Docker Desktop fails to start and displays the following error message:
![image](https://user-images.githubusercontent.com/52764594/127747604-85d5ba0b-25a0-4f5b-b6aa-7dd2d593fe2b.png)
![image](https://user-images.githubusercontent.com/52764594/127747614-0efed9fc-52f2-4a78-b25d-58a7b201cdb4.png)

### Expected behavior
Docker Desktop should start successfully.

### Information
This issue is reproducible every time I restart my computer or attempt to start Docker Desktop manually. Docker Desktop was working fine before the Windows update, but started failing immediately after the update was installed.

  - Windows Version: Windows 11 Home (build 22000.100)
  - Docker Desktop Version: 3.5.2
  - WSL2 or Hyper-V backend? WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

Here is the full text of the error message:
```
WSL distro stopped while waiting for Lifecycle server.
  >Stdout:

  >Stderr:
2021/07/31 17:16:31 resolving /mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-wsl-cli.iso...
Error: mounting wslCLIDest: stat /mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-wsl-cli.iso: no such file or directory
2021/07/31 17:16:31 stat /mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-wsl-cli.iso: no such file or directory
mounting wslCLIDest
main.doRun
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:230
main.run.func1
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:94
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:850
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:958
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).Execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:895
main.main
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:36
runtime.main
	/usr/local/go/src/runtime/proc.go:225
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1371
```

Please note: The files that it says do not exist, do in fact exist.

I have attempted to resolve this issue using solutions from the following thread, which seems to be describing the same error, but on Windows 10. None of them have worked.
https://github.com/docker/for-win/issues/6727

### Steps to reproduce the behavior
  1. Using a machine running Windows 10, update to Windows 11
  2. When your computer starts for the first time (and every time afterwards), Docker Desktop will fail to start.

**Comment by maartenvantjonger** [comment]
Same here. As a workaround (if you don't need WSL) you can disable WSL integration by setting  `"wslEngineEnabled": false` in the config file at `C:\Users\<username>\AppData\Roaming\Docker\settings.json`

**Comment by ryanmuhammad** [comment]
update the kernel by typing `wsl --update`, then restart the wsl.
it fixed that problem

**Comment by janlonden** [comment]
What ryanmuhammad suggested solved the problem for me. Just remember to run your terminal as administrator.

**Comment by jking777** [comment]
Same here.  And ryanmuhammad's solution also worked for me.  Thanks!

**Comment by raad-orfali** [comment]
Same for me. the solution didn't solved it also it will effect wsl2 as I start getting mount error and ubuntu is not working till I install Docker Desktop
Win Ver: Windows 11 Pro Version 21H2 (OS Build 20000.100)
Docker Version: 3.5.2

**Comment by mitchross** [comment]
Same issue

**Comment by lofbacke** [comment]
@ryanmuhammad's solution worked for me. Thanks everyone!

**Comment by alokverma75** [comment]
Yes, I too was facing same issue with windows 11 upgrade same version. And wsl --update worked like a charm. Thanks for the solution.

**Comment by fdepierre** [comment]
Thanks works `wsl --update `works for me with docker 3.6.0 but not 4.0.0

**Comment by XinglingL** [comment]
Sorry I have a problem, I did wsl --update, and I restarted the computer which I thought would restart wsl2 as well, but it did not work. And using wsl --update gave me the following picture. I tried to restart wsl2 with LxssManager, but when I opened Docker Destop, it still shows that Docker fails to initialize, like the following picture. What should I do now? Thank you so much.
![1](https://user-images.githubusercontent.com/90158692/132142556-c33d57c6-e519-42e0-9504-d01d09026e79.PNG)
![2](https://user-images.githubusercontent.com/90158692/132142557-262ed5e9-50d4-4b2d-91e7-8328f8768a1c.PNG)

**Comment by GrantBrontoli** [comment]
I'm having the same issue @XinglingL

**Comment by claudiomulas** [comment]
I've solved using Hyper-V. To use it from powershell (with admin rights)

`Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All`

**Comment by beecars** [comment]
Encountered same issue with Windows 11 Insider Preview and Docker 4.0.1.

Used `wsl --update` in as indicated above, but also had to re-install Docker 4.0.1 to remedy the error.

**Comment by PeterJohnson** [comment]
Updated wsl, re-installed Docker 4.0.1, and enabled Hyper-V.  None have solved the issue for me (Windows 11 22000.194).

**Comment by svdbrg** [comment]
My problem to this was I didn't have a Linux distro installed in WSL2. Installed Ubuntu from the store and Docker started right away.

**Comment by Samuel-Bie** [comment]
For some reason i dont know th https://github.com/docker/for-win/issues/12099#issuecomment-916276739 have Solved this issue.
