### ISSUE TITLE
Install instructions regarding...don't....

### ISSUE THREAD

**Issue by JadianRadiator** [docker/for-win#11810]
Install instructions regarding Git and Docker Desktop's Dev Environment don't say you have to restart to finish installing Git.
This was the cause of #11533
@trungutt this is not an issue with programming nor code.
It is an issue of inaccurate documentation.
Code/program is fine, it's how the documentation was written that's the issue.
There is no diagnostic info as it's purely human-error on writing the _documentation_, **_NOT_** the code.
Because of that, diagnostic info won't help you look into it.
Because again, the issue is purely human-error in writing the documentation.
The program/code doesn't have any issues.
It's the _writing of the documentation_ that this issue is about, _**NOT**_ the code.

P.S.
I'm assuming this is still an issue since @trungutt closed the original post of this without actually reading it.
I'm not that bad at describing stuff.
And @trungutt can't be dense enough to not understand it... if he actually read it.

**Comment by lorenrh** [comment]
Thanks for your report. This is an issue tracker for reporting problems with the software, for documentation requests there's https://github.com/docker/docker.github.io.

Would you mind sharing the link to the documentation, so it's easier for us to track down?
