### ISSUE TITLE
开机后首次启动不成功

### ISSUE THREAD

**Issue by easygoto** [docker/for-win#11819]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
    - [x] Use Docker Compose V2
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

- 开机后, 点击启动 Docker Desktop, 一直保持着这种状态, 必须要退出再启动一次, 才能成功

![image](https://user-images.githubusercontent.com/29568241/128110370-59de8f79-c9d3-4d70-a177-c60daea43bc6.png)

### Information

  - Windows Version: Windows 10 专业版 19043.1110
  - Docker Desktop Version: Docker version 20.10.7, build f0df350
  - WSL2 or Hyper-V backend?  : I use Hyper-V backend
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no, only hyper-v

### Steps to reproduce the behavior

  1. 开机
  2. 点击启动 Docker Desktop

**Comment by Mohsin0911** [comment]
same problem is with me
