### ISSUE TITLE
Inactive TCP sockets disconnect when using Docker for Windows with WSL 2 backend

### ISSUE THREAD

**Issue by wyckster** [docker/for-win#11839]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `1BF16841-F73A-4A1C-B8F4-82B2DC2C8CF8/20210805175845`
 - Docker version 20.10.7, build f0df350

#### Summary

When a client application (running in Docker for Windows with WSL 2 backend) connects with a TCP socket server application on the same host, if the connection is left inactive for a period of 5-7 minutes, the connection gets disconnected.

#### Steps to Reproduce

I can reproduce this issue with __no code of my own__.

Docker (using WSL 2) must be installed on the Windows 10 machine.

In this repro, we test a TCP connection: the server app is running natively (bare metal) in Windows on the host, but the client is running in a Docker container (same host though.)

In Windows, on the host, I start up an echo server.  You can use [PavelBansky/EchoTool](https://github.com/PavelBansky/EchoTool), but it doesn't matter--any TCP socket server will do.  In this case I started an echo server with:

<pre>
echotool /p tcp /s 8002
</pre>

Then I run a Docker container (e.g. `ubuntu`) and install telnet, and then telnet to the echo server running on the host.  (Substitute the IP of the host machine as required. `10.0.0.123` is shown in this example.)

<pre>
C:\> docker run --rm -it ubuntu
root@67d6d6f9cced:/# apt update && apt-get install telnet -y
Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
...
root@67d6d6f9cced:/# telnet
telnet> o 10.0.0.123 8002
Trying 10.0.0.123...
Connected to 10.0.0.123.
Escape character is '^]'.
</pre>

#### Expected Results

I expect the client to connect to the server and stay connected indefinitely, without being disconnected.  I am able to reproduce the expected results if WSL 2 is not involved:

* By running the client directly on the host (not in Docker).
* By running the client in Docker on another platform or architecture (e.g., NVIDIA Jetson Nano - ARM Linux).

I am also able to reproduce the expected results if Docker is not involved:

* By installing an ubuntu distro for WSL 2 (just get it from the Windows store), and telnet running in that distro.

In the non-WSL 2 scenario, the expected results can also be achieved provided the connection remains nominally idle (no data sent):

* Using different server applications.  (Any TCP socket server will work.)
* Using different client applications.  (Any TCP socket client app will work.)

#### Actual Results

The client gets disconnected from the server after a period of roughly 6 minutes.

**client**

<pre>
telnet> o 10.0.0.123 8002
Trying 10.0.0.123...
Connected to 10.0.0.123.
Escape character is '^]'.
Connection closed by foreign host.
</pre>

**server**

<pre>
Waiting for TCP connection on port 8002. Press any key to exit.

Client 10.0.0.123:51656 accepted at 11:21:43 AM

Session closed by peer.
Waiting for TCP connection on port 8002. Press any key to exit.
</pre>

I can only reproduce this when the client is connected from a Docker container hosted on Windows using WSL 2.  But in that scenario, it reproduces 100% of the time.  All versions of Windows I've tried are reproducing this:  e.g.:  `Version 20H2 (OS Build 19042.1110)`, `Version 21H1 (OS Build 19043.985)`.  This happens on a variety of different physical systems with different kinds of network adapters.

#### More Info

I also noticed that if I connect *multiple* clients (from multiple Docker containers), then after about 6 minutes of inactivity, **all** clients will be disconnected *simultaneously*.  In other words, it's not that each connection is being dropped after 6 minutes of its own inactivity, in which case I would have expect staggered disconnections, it's that after about 6 minutes of inactivity **all** inactive connections are disconnected together.

If a new connection is formed immediately after disconnecting, then the period is extremely consistent: About 6 minutes and 30 seconds.

I also notice that if I just connect from telnet from my ubuntu distro running on WSL 2, then the connection can successfully remain open indefinitely, suggesting that it's not WSL 2 alone that is to blame.

---

To me, this seems to be related to Docker on WSL 2 backend.  It is my understanding that sockets can remain connected indefinitely.  If they can't, then why can I perform this test and observe indefinite connections on all other Docker platforms except WSL 2?  Could it be a bug?  Why are inactive sockets being disconnected when using Docker on WSL 2?  How can I fix or prevent this?

**Comment by jasonatball** [comment]
@wyckster do you know the version of the WSL kernel you had? According to the [WSL2-Linux-Kernel releases](https://github.com/microsoft/WSL2-Linux-Kernel/releases) it would have been either the initial release [linux-msft-wsl-5.10.16.3](https://github.com/microsoft/WSL2-Linux-Kernel/releases/tag/linux-msft-wsl-5.10.16.3) or [linux-msft-wsl-5.10.43.3](https://github.com/microsoft/WSL2-Linux-Kernel/releases/tag/linux-msft-wsl-5.10.43.3). Since then there has been a number of releases but the release notes don't specifically address this issue.

**Comment by ryanatball** [comment]
I can recreate using the exact method described above (Windows 10 host running echotool, ubuntu container running telnet).

**Comment by ryanatball** [comment]
Additional information:
1. Can confirm if you reconnect immediately after the socket is closed, it will reoccur exactly every 6 minutes and 30 seconds.
2. This issue does not occur if the tcp server is in Docker (with a port forwarded to it), and the client is on the Windows host.
3. The disconnects stop if other containers are running in Docker with active TCP connections between them.   Other containers with none or inactive TCP connections do not prevent the disconnects.

**Comment by ryanatball** [comment]
I have submitted an internal ticket to Docker Desktop support number 82533
