### ISSUE TITLE
docker-compose can't start | shared volumes | WSL2

### ISSUE THREAD

**Issue by Gildraen** [docker/for-win#11844]
Hi, i just installed docker on my windows 11
So i installed WSL2 too and then tryied to run a simple docker-compose file inside my ubuntu and here is what i get : 

Error response from daemon: path /home/gildraen/lab/tbe_app/front is mounted on / but it is not a shared mount

on linux i never had this error, and can't find any suitable solution. any tips or already answered somewhere ?

**Comment by Gildraen** [comment]
Ok i managed with using sudo. So it may be some permissions problem..

**Comment by Gildraen** [comment]
Ok, even i can make this work using sudo, how could i use docker-compose with volume with my own user ?

**Comment by entn-at** [comment]
Same problem, it seems to be caused by docker-compose v2.0.0-rc1 which is included in the recent Docker for Windows update.
My temporary solution was to download docker-compose v1.29.2 (https://github.com/docker/compose/releases/tag/1.29.2) and use that meanwhile.

**Comment by Gildraen** [comment]
Here is what i found that made the problem resolve : 

mount --make-shared /

simple and easy ^^
