### ISSUE TITLE
Docker with WSL2 use high amount of RAM (We can do better no?)

### ISSUE THREAD

**Issue by MahefaAbel** [docker/for-win#11863]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features

### Actual behavior
Docker with WSL 2 => Use high RAM.
- On launch, it use 2Go
- When launch one simple image, it use ~4Go or 5Go
- When launch two, three or four images, it cas use 10Go (I have 16Go RAM)

### Expected behavior
It use a RAM but not so hight like describe in #Actual behavior

### Information

  - Windows Version: 19043.923
  - Docker Desktop Version: 20.10.7
  - WSL2 or Hyper-V backend?  => WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Just start docker
  2. Then, run some image (One, two, three or four)
  3. And bam.... **Docker + Vemm** use **more than 10Go**

### Personnal thinking
  1. It may be not a bug, but it is a PROBLEM
  2. I hope you are considering it as a problem
  3. If (or when) the decision-maker of docker project is aware that it is a problem, as a technical lead or developer I can help the team if need (there are many people good as I am or more, I want help because docker is a very good product, except it's RAM consumption)
  4. It's a shame that the new and the recommanded backed (wsl 2) by docker it self is problematic (high RAM consumption)

We can do better no ? I think we can use too much less RAM for the functionnality

**Comment by stephen-turner** [comment]
In WSL 2 mode, the amount of RAM used is controlled by Windows, not by Docker. But we do give a link in the settings explaining how to limit it in your WSL 2 configuration.
