### ISSUE TITLE
Unable to use docker login

### ISSUE THREAD

**Issue by whunsicker** [docker/for-win#11866]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID:  1A8F36DE-9923-4356-A1C0-DD2609AECD83/20210810120405

### Actual behavior
Log into docker repo

### Expected behavior
Receiving the below error:
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### Information

  - Windows Version:  20H2
  - Docker Desktop Version: 3.5.2 (66501)
  - WSL2 or Hyper-V backend?  Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No, physical Dell laptop

### Steps to reproduce the behavior

  1.  open Powershell or GitBash
  2. docker login or docker login (internal-repo)

previous version 2.3 worked fine with both commands
after upgrading to 3.3 the commands started generating this error:  Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Attempts to fix so far:
-- Reset to factory defaults
-- Restarting docker
-- Reinput config parameters
-- use API key rather than password
-- set DNS to 8.8.8.8

Pending attempts:
-- trying to get with my network team to implement the proxy settings described in https://stackoverflow.com/questions/23111631/cannot-download-docker-images-behind-a-proxy

I have validated this behavior only affects our Windows systems.  When I load Docker 3.3 on my Mac, it connects to the Docker Hub and my internal docker repo just fine.
--

**Comment by simonm3** [comment]
/remove-lifecycle stale
I also have this issue. Cannot login from windows.
