### ISSUE TITLE
Docker for Windows

### ISSUE THREAD

**Issue by CXdur** [docker/for-win#1186]
### Docker doesn't start

I constantly receive the error "Hardware assisted virtualization and data execution protection must be enabled in BIOS. However, they both are enabled and I've done a lot of troubleshooting here. I recently switched from an Intel i5 to a Ryzen 5, and I haven't gotten docker to work on the Ryzen. I'm not really sure why. 

### Information

-   Diagnostics ID:
-   B0E34DDA-4054-426C-9080-1C142B2AEDFE/2017-10-07_16-49-46
-   Windows 10 Pro, all windows updates as of 07.10.2017
-   AMD Ryzen 5 1600 Six-Core

### Steps to reproduce the behavior

It happens every time I try to launch docker.

**Comment by jasonbivins** [comment]
Hi @CXdur   Can you check your BIOS settings and make sure SVM is enabled as well?

**Comment by CXdur** [comment]
Hey @jasonbivins, thanks for your reply. It has been enabled, I just verified now.

**Comment by CXdur** [comment]
Hey, after the new Windows 10 Creator Fall update or what it was called, suddenly Docker started to work. It's even a lot faster now (I thought perhaps my previous CPU & RAM was the reason for that so upgraded it only to not have Docker working with the new CPU). It works now anyway, thanks for your support!
