### ISSUE TITLE
Docker Desktop failing to start consistently, and starts very slowly when it does start

### ISSUE THREAD

**Issue by dpramik-mim** [docker/for-win#11869]
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Docker Desktop fails to fully start.

### Expected behavior
Docker Desktop starts up in a timely manner, and fully starts the Docker engine.

### Information

  - Windows Version: Server 2019 Datacenter
  - Docker Desktop Version: 3.5.2 (66501)
  - WSL2 or Hyper-V backend?  Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

After upgrading to 3.5.2, Docker Desktop has failed to successfully start up consistently. Even when Docker Desktop does start up successfully, it can take anywhere between 15-20 minutes to do so. Sometimes even when Docker Desktop is running, the Docker Engine does not seem to be started properly and docker commands will fail.

This has not been reproducible on other machines. On a similar environment on the same version, Docker Desktop will start up fine and starts quickly.

Logs from the diagnostic tool are attached. Some things that stick out are a significant amount of connection timeouts when starting, and messages of Docker stopping and restarting.

[dockerLog.txt](https://github.com/docker/for-win/files/6963275/dockerLog.txt)

**Comment by StefanScherer** [comment]
Thanks for the report. Unfortunately Windows Server 2019 doesn't meet the system requirements for Docker Desktop https://docs.docker.com/docker-for-windows/install/#system-requirements
If you need more help, please have a look at the https://docs.docker.com/docker-for-windows/troubleshoot/
I'm going to close this ticket.
