### ISSUE TITLE
Tip of the week contains imprecise wording

### ISSUE THREAD

**Issue by lmroil** [docker/for-win#11860]
- [x] I have tried with the latest version of Docker Desktop

### Actual behavior

There is a TIP OF THE WEEK:

> Are your images secure?
>
> Using open source components in your container images can introduce vulnerabilities. Run “docker scan” to secure your images using Snyk.

### Expected behavior

The explanation says "third party components" instead of "open source components", since closed source components have the same risk of containing security vulnerabilities.

**Comment by StefanScherer** [comment]
Thanks for giving us feedback on our tips of the week.
We've forwarded the suggestion to the team to consider the different wording. 
I'm going to close this ticket.
