### ISSUE TITLE
Feature request: Let the user chose the installation folder

### ISSUE THREAD

**Issue by odupuy** [docker/for-win#11876]
In 2021, not being able to chose the installation directory of a program should be something of the past.

I am (finally) upgrading to W10, switching Docker Toolbox for Docker Desktop 3.5.2.
I install it and it creates all sorts of problems in my scripts and makefiles.
The reason is the space in the name C:\Program(space)Files\Docker\Docker\resources\bin\docker.
This breaks a lot of things especially when your scripts must support Windows, Unix, Mac.

**Why cannot we chose the install folder like in any other application?**
- Some corporate developer machines only allow installs to specific directories. 
- Spaces may be an issue
- You may have a faster disc as D: vs the default C:
- Your C: can be full

I am [not the only one stuck here, many have the problem](https://www.google.com/search?q=docker+desktop+windows+change+installation+directory). (google search)
I am trying various tricks like the linked folder of this [post](https://forums.docker.com/t/docker-installation-directory/32773/6) with `mklink /J "C:\Program Files\Docker" "c:\Programs\Docker"`  then I have to set the proper PATH order but I still have some other issues related to the location.

**Please, keep the things simple for all the users, just let the user chose the installation folder that he needs.**  

And BTW why cannot we chose as well the other directories? (see post upper).

  - [x] I have tried with the latest version of Docker Desktop
  - [N/A] I have tried disabling enabled experimental features
  - [N/A] I have uploaded Diagnostics

### Actual behavior
The program installs in C:\Program Files\Docker. No choice!

### Expected behavior
I want having the choice of the folder. Same disk or another disk.

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible? Yes
  - Is the problem new? Not sure
  - Did the problem appear with an update? No

  - Windows Version: W10
  - Docker Desktop Version: 3.5.2
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior
There is simply no choice in the installer UI or on the CLI to select an installation folder.

**Comment by StefanScherer** [comment]
Thanks for the feature request. Please vote up https://github.com/docker/roadmap/issues/94, as you can see there is not really much demand for this and therefore it's unlikely we will implement that in the near future. 
You can run `docker` without using the full path to it, because this folder is added the the PATH variable.
I'm going to close this ticket, please follow the roadmap ticket.

**Comment by odupuy** [comment]
The issue is not about running docker without the PATH if the resources/bin folder is already in your path.
It is about the integration with tools, scripts which have to run on all of Mac, Unix, Windows.
Having a space in the path name is a problem in my case for a makefile.
I would have saved hours if the installation program was flexible.
But I will put my comments in 94.
Thanks
