### ISSUE TITLE
Please help me install docker for window

### ISSUE THREAD

**Issue by lehoang1212** [docker/for-win#11877]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 8F903D5E-B3B9-48A4-92A0-792F46E480DF/20210811152017

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by StefanScherer** [comment]
There seems to be a problem with WSL 2 itself. You could remove both docker-desktop and docker-desktop-data distros and try again. Or run a factory reset in Docker Desktop troubleshooting UI.

```
22:20:16.416][WSL2Provisioning  ][Error  ] Failed to deploy distro docker-desktop to C:\Users\Admin\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: This operation returned because the timeout period expired.
```

You could update to 3.6.0 and try the new diagnostic tool. https://docs.docker.com/docker-for-windows/troubleshoot/#experimental-self-diagnose-tool
