### ISSUE TITLE
docker system df fails with error getting build cache usage: failed to get usage

### ISSUE THREAD

**Issue by magicwerk** [docker/for-win#11884]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 4C913480-9AED-40C9-8C56-CB12AC7A3ECD/20210812233945

### Actual behavior

>docker system df
Error response from daemon: error getting build cache usage: failed to get usage for 9tgtwq07c56zgkmys92om90ll: error creating overlay mount to /var/lib/docker/overlay2/r5oljfbd1gdjhqtlufzewrnkm/merged: too many levels of symbolic links

### Expected behavior

>docker system df
should work

### Information

As this seems to be related to the build cache, I tried
>docker builder prune -a
but it did not help.
Upgrading to Docker Desktop 3.6.0 did not help neither.

How can I get it working againg?
Do the ids reported in the error message help somehow to find a corrupt object which could then be removed?

**Comment by cdalexndr** [comment]
I get similar error, could be related to this:
`Error response from daemon: error getting build cache usage: failed to get usage for zcxs57s3yy2h03lfbkpr5pvgq: stat /var/lib/docker/overlay2/f4yh03il1wowladtgxx2o5sje: no such file or directory`

**Comment by StefanScherer** [comment]
It looks like the filesystem got corrupted. I'm not sure if you can fix it manually. Try "Troubleshot"-> "Clean/Purge Data".
