### ISSUE TITLE
docker desktop can not list images

### ISSUE THREAD

**Issue by StevenLeiZhang** [docker/for-win#11881]
Diagnostics ID: 32A46E5F-5968-4904-A3C4-30005E6E32EA/20210812093509
docker desktop version:  3.5.2(66501)
System: windows 10
I moved  default virtual disk file from disk C to D(follow this post  [https://stackoverflow.com/questions/62441307/how-can-i-change-the-location-of-docker-images-when-using-docker-desktop-on-wsl2](url)  ), docker worked well before upgrade. 
After upgrading docker desktop to 3.5.2, it can not list local images, but "docker images" command works well in command line.
Another issue is k8s fails to  start

**Comment by StefanScherer** [comment]
I'm glad you could solve it on your own, yes that's the way to fix corrupt disk data.
