### ISSUE TITLE
Cancellation token triggered before we finished reading from the stream.

### ISSUE THREAD

**Issue by RawrBear** [docker/for-win#11887]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 5810597F-0AB7-459F-925B-59735ADBC835/20210813035819

### Actual behavior
Docker Desktop starts up, starts WSL 2 and then stops. An error pops up with .NET Framework error: Cancellation token triggered before we finished reading from the stream.

Here is the details log from that error: https://pastebin.com/3dFYmzwc

### Expected behavior
Docker Desktop to run and function without errors.

### Information
  - Is it reproducible? As of this morning, yes, every time I run Docker. Not sure how to reproduce on another system.
  - Is the problem new? Yes, as of this morning.
  - Did the problem appear with an update? No. I've updated nothing at all on the system since last night wehen Docker was working.

  - Windows Version: Windows 10 Home 
  - Docker Desktop Version:  3.5.1 and 3.5.2
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No, Windows installed on bare metal.

### Additional Fixes Tried
Downgraded Docker from 3.5.2 to 3.5.1
Deleted everything inside AppData Local and Roaming that is related to Docker
Attempted to reinstall .NET framework but it's already latest version
Rebooted and shut down multiple times
Checked Virtualization in Bios and it is active 

### Additional Notes
Fresh install of Windows, still the same error after fresh install of Docker and WSL2

**Comment by StefanScherer** [comment]
It looks like there is a problem with the underlying WSL 2. In the logs I can see `unable to query WSL distros: exit status 4294967295`

Try the wsl command as shown in https://docs.docker.com/desktop/windows/wsl/ if it lists distros. Have you installed and successfully running another WSL distro in WSL 2 mode?
Maybe your machine or BIOS settings doesn't meet the WSL 2 requirements.
