### ISSUE TITLE
can't restart docker after upgrading

### ISSUE THREAD

**Issue by YUY2020** [docker/for-win#11885]
Dear Sir,

I can't restart docker after upgrading and got the following error:

System.ServiceProcess.TimeoutException:
Time out has expired and the operation has not been completed.
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(Settings settings, String args, Dictionary`2 env) in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 208
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.<GetExecutor>b__0(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()

  - [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by marianob85** [comment]
Got same exception when updating to version 3.6 from 3.5.2
I've notice that problem is related with  data-root settings. With fresh install it works without problem, but when I change option  to: "data-root": "E:/Docker" it start once, then after OS restart it's always crash. 

`System.ServiceProcess.TimeoutException: Time out has expired and the operation has not been completed.
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(Settings settings, String args, Dictionary`2 env) in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 208
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.<GetExecutor>b__0(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()`

**Comment by YUY2020** [comment]
Hi Mariusz,

Thanks for your quick reply.

I got another question. There is a button "Reset to factory defaults" in this page.
What does "factory defaults" mean here? Is it possible that we can revert it back to the last version (before upgrading) but not factory defaults? So that I still can use my Docker at the last version.

Thanks.


***@***.***


Thanks.

Kind regards,

YuYang

**Comment by marianob85** [comment]
> Hi Mariusz, Thanks for your quick reply. I got another question. There is a button "Reset to factory defaults" in this page. What does "factory defaults" mean here? Is it possible that we can revert it back to the last version (before upgrading) but not factory defaults? So that I still can use my Docker at the last version. Thanks. ***@***.*** Thanks. Kind regards, YuYang From: Mariusz Brzeski ***@***.***> Sent: Friday, 13 August 2021 4:25 PM To: docker/for-win ***@***.***> Cc: Yu Yang ***@***.***>; Author ***@***.***> Subject: Re: [docker/for-win] can't restart docker after upgrading (#11885) Got same exception when updating to version 3.6 from 3.5.2 I've notice that problem is related with data-root settings. With fresh install it works without problem, but when I change option to: "data-root": "E:/Docker" it start once, then after OS restart it's always crash. System.ServiceProcess.TimeoutException: Time out has expired and the operation has not been completed. at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout) at Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(Settings settings, String args, Dictionary2 env) in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 208 at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.b__0(Object instance, Object[] methodParameters) at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary2 arguments, CancellationToken cancellationToken) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext() - You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdocker%2Ffor-win%2Fissues%2F11885%23issuecomment-898222192&data=04%7C01%7Cyu.yang%40rhipe.com%7Caee86b617e5d46f2bb7f08d95e231c0c%7C163bf6f48cd641ce945e17b752c89b01%7C0%7C0%7C637644327176414161%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cHDs9d6a%2FPeSMbtTlFiWeDwvZPTaLrX2Q9l25GK954U%3D&reserved=0>, or unsubscribe<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ3GI3R3V24S7V3HQFWMJODT4S3EHANCNFSM5CCYCMIQ&data=04%7C01%7Cyu.yang%40rhipe.com%7Caee86b617e5d46f2bb7f08d95e231c0c%7C163bf6f48cd641ce945e17b752c89b01%7C0%7C0%7C637644327176424115%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GY1RWyzz9VdMyhi9wo6vJ3a3pdgJRuvhZvtfh6Ugi3g%3D&reserved=0>. Triage notifications on the go with GitHub Mobile for iOS<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cyu.yang%40rhipe.com%7Caee86b617e5d46f2bb7f08d95e231c0c%7C163bf6f48cd641ce945e17b752c89b01%7C0%7C0%7C637644327176424115%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=frYqNWf3meUc8gWrH3TNfY5uJbmy8GU213nsRYkYhko%3D&reserved=0> or Android<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cyu.yang%40rhipe.com%7Caee86b617e5d46f2bb7f08d95e231c0c%7C163bf6f48cd641ce945e17b752c89b01%7C0%7C0%7C637644327176434070%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=q9g5CRtJj%2BKKeZ2eQpRsWY5QkaLUuTCloTDxhE9cqdM%3D&reserved=0>. Yu Yang Technical Consultant ***@***.*** +61 2 8350 8413 Expertise that Empowers rhipe is an ISO/IEC 27001:2013 certified organisation This email is intended solely for the use of the addressee. It may contain information that is confidential or subject to legal professional privilege. If you receive this email in error please immediately notify the sender and delete the email. Please consider the environment before printing this e-mail.

I don't know. I uninstalled version 3.6, clear all docker data on disk, and then I'v installed older version 3.5.2. 
What's more interesting both containers ( windows/linux ) are not working with 3.6

**Comment by RaKuNbg** [comment]
I have the same problem after upgrading docker yesterday to 3.6.0

So the only solution in the moment seems to be to go back to version 3.5.2 or wait for the experts of the docker team to have the issue fixed, correct?
Does anyone know how fast the docker team is investigating problems like this?
Until now it seems that nobody of the team has seen the post yet?!?

**Comment by permadsenaalborg** [comment]
I have the same issue after upgrading to 3.6.0. Even after uninstalling and installing 3.5.2 Docker fails to start!

**Comment by IosifZ** [comment]
Same issue on my side, Hyper-V:

9343F838-26F4-4BC0-A1FB-B21B16BFF69D/20210815185455

**Comment by nea** [comment]
Same Hyper-V issue on my side here. On reboot/first-time start it crashes completely.
Restarting it afterwards then seems to work.

**Comment by YUY2020** [comment]
Go to: C:\ProgramData\Docker\panic.log
Untick the Read-only at the property of the file.
It works from my side.

**Comment by etterli** [comment]
> Got same exception when updating to version 3.6 from 3.5.2
> I've notice that problem is related with data-root settings. With fresh install it works without problem, but when I change option to: "data-root": "E:/Docker" it start once, then after OS restart it's always crash.
> 
> `System.ServiceProcess.TimeoutException: Time out has expired and the operation has not been completed. at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout) at Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(Settings settings, String args, Dictionary`2 env) in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 208
> at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.b__0(Object instance, Object[] methodParameters)
> at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()`

Exactly the same for me. I can reproduce the issue as follows:

- Start Docker without a data-root setting
- Switch to Windows containers (if not yet)
- Add "data-root": "D:\\docker" to deamon.json (C:\ProgramData\Docker\config)
- Restart Docker
=> Docker is running fine as expected
- Reboot Windows
- Docker crashes with the quoted error

When removing the data-root configuration Docker can start up without problems. It is then possible to define a different data-root location (e.g. D:\\docker2) and everything works until Windows is rebooted again.

So there seems to be a problem accessing the new created data-root "file system" after an reboot?

**Comment by un1r8okq** [comment]
> Go to: C:\ProgramData\Docker\panic.log
> Untick the Read-only at the property of the file.
> It works from my side.

This worked for me! Thanks @YUY2020 😍

**Comment by anwar0206** [comment]
> Go to: C:\ProgramData\Docker\panic.log
> Untick the Read-only at the property of the file.
> It works from my side.

Thanks @YUY2020, it worked like a charm. You saved my weeks of efforts
