### ISSUE TITLE
docker run nanoserver locks up docker engine

### ISSUE THREAD

**Issue by ezeeetm** [docker/for-win#119]
### Expected behavior
I am trying to reproduce the behavior demonstrated here https://youtu.be/85nCF5S8Qok?t=15m29s.
`docker run -it nanoserver cmd`
which (in the video) opens an interactive session with a nanoserver container as expected

### Actual behavior 
I am running in Docker for Windows (switched to Windows Engine/containers)
`docker run -it microsoft/nanoserver:latest cmd`
This results in a blinking cursor that locks up the Docker Engine (requires reset via settings >reset)

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
E3C98FF6-92CC-4217-82EE-CDDAE2A11FC4/2016-09-30_20-58-12

  - host distribution and version (Windows version, build number, etc)
Windows 10 build 14393 (log attached)

[log.txt](https://github.com/docker/for-win/files/504039/log.txt)

**Comment by friism** [comment]
Can you make sure you have all the latest Windows updates? See here: https://github.com/Microsoft/Virtualization-Documentation/issues/358

**Comment by ezeeetm** [comment]
@friism there was one update.  Applied it and now I can run nanoserver containers.  Thank you.

Crazy note:  the first time I ran nano (with cmd as my entrypoint) I was in my host filesystem.  dir returned all the files in my host system home dir (c:\users\my user\).

I tried to reproduce with both cmd and powershell, no luck.  Any idea what might cause that...it was kind of interesting/cool?
