### ISSUE TITLE
Docker Desktop fails to start after Update to Version 3.6.0

### ISSUE THREAD

**Issue by RaKuNbg** [docker/for-win#11904]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  ==> not possible because docker desktop doesn't start
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6EDD1183-56C1-45C7-A677-9337EB6ECCA1/20210816052513

### 
Updated Docker to Version 3.6.0 last thursday
After shut down my computer and new start up on friday docker doesn't start any more.

### Information

  - Windows Version:
  Version	10.0.19042 Build 19042
  - Docker Desktop Version: 
  3.6.0
  - WSL2 or Hyper-V backend?
  I don't know ==> where can I see it  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:
  Local notebook with windows

### Steps to reproduce the behavior
I don't know - perhaps
  1. Install docker Version 3.6.0 and reboot the system

**Comment by RaKuNbg** [comment]
Dear @mikeparker, Dear @stephen-turner, 
sorry to bother you (not sure if one of you is the right person to ask but perhaps you can forward my question).
Is there anybody (beside the robot) monitoring the issues in this repository?
There are more and more postings, that there seems to be a problem with docker 3.6.0 not starting on windows.
At least for me this problem is really urgent, because all of my development environments are running on docker and so I can't work in the moment.
Thanks in advance for a feedback.

Best regards
Rainer

**Comment by IosifZ** [comment]
> Dear @mikeparker, Dear @stephen-turner,
> sorry to bother you (not sure if one of you is the right person to ask but perhaps you can forward my question).
> Is there anybody (beside the robot) monitoring the issues in this repository?
> There are more and more postings, that there seems to be a problem with docker 3.6.0 not starting on windows.
> At least for me this problem is really urgent, because all of my development environments are running on docker and so I can't work in the moment.
> Thanks in advance for a feedback.
> 
> Best regards
> Rainer

I was able to stable my environment by uninstalling Docker and then installing an older version prior to the force updates one. I've unckhecked "Check for updates" option and now I am ok. Not a solution but a workaround.

**Comment by RaKuNbg** [comment]
Hi @IosifZ 
thanks for your feedback.
I also uninstalled version 3.6.0 and reinstall version 3.5.2.
After that I rebooted my system - (as the first errror occured only after a reboot).
It looked good in the first moment, and docker was running. But when I tried to switch from Linux to Windows Containers, I ran into the error mentioned here
https://github.com/docker/for-win/issues/11901
and here
https://github.com/docker/for-win/issues/11899

**Comment by IosifZ** [comment]
Here's my current version. 
![Screenshot_20210816-193900__01](https://user-images.githubusercontent.com/53576878/129598832-8958baf9-8afe-4c35-bf66-a1f4d80df360.jpg)
2.5.2 gave other issues, that is why I've decided to go further back. I hope it's going to help you.

**Comment by RaKuNbg** [comment]
HI @IosifZ 
here https://github.com/docker/for-win/issues/11899 is a workaround for the current version 3.6.0

**Comment by IosifZ** [comment]
> HI @IosifZ
> here #11899 is a workaround for the current version 3.6.0

The previous version caused Docker to start in 12 minutes since the reboot of the PC. That panic.log would just get me pass that issue and back into the late start issue.
For the moment I believe that is best to stick with this ancient version until some more problems are cleared up.

**Comment by slonopotamus** [comment]
See https://github.com/docker/for-win/issues/11934#issuecomment-901668502 for possible workaround.

**Comment by IosifZ** [comment]
> > HI @IosifZ
> > here #11899 is a workaround for the current version 3.6.0
> 
> The previous version (3.5.2) caused Docker to start in 12 minutes since the reboot of the PC. That panic.log solution for 3.6.0 would just get me pass the Docker not starting issue and back into the slow start issue.
> For the moment I believe that the best course for me would be to stick with this ancient version until some more problems are cleared up. Most likely I will upgrade to the last version 3.x of Docker for windows when version 4.x is released :)

Yesterday I wanted to give 4.0 a change. So I've upgraded from 2.4.0 ending up with the same message. So 3.5.2 brought a 12 minutes delay after reboot of the PC, and stating 3.6 I am not able to use any other newer version. Is anyone paying attention to all these issues?
