### ISSUE TITLE
No feedback for button presses on Windows Docker Desktop

### ISSUE THREAD

**Issue by dajtxx** [docker/for-win#11903]
- [x ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

Buttons in the UI are 'flat' and have no indication they are a button. Hovering over most of them gives a tooltip which is a clue, but the button itself does not highlight.

Clicking the button gives no indication anything is happening or that the click was registered.

This is particularly infuriating with the stop button, but it's annoying over the entire interface.

### Expected behavior

I expect buttons to look like they're are some sort of clickable control. If you won't do that I expect an interactive widget to at least change appearance when the mouse is over it to show it is clickable.

Once I have clicked it I expect to see some indication it is working.

**Comment by StefanScherer** [comment]
Thanks @dajtxx for the feedback. I'll forward this internally to our design team.
