### ISSUE TITLE
System.ServiceProcess.TimeoutException: Time out has expired and the operation has not been completed.

### ISSUE THREAD

**Issue by ederbond** [docker/for-win#11915]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 560E0449-E4F0-4A5F-957C-D02FA849A68E/20210817050156

### Actual behavior
Throwing exception when Docker desktop starts to initialize the docker engine.
### Expected behavior
No exception
### Information

  - Windows Version: 
        Edition	Windows 10 Pro
        Version	21H1
        Installed on	‎8/‎16/‎2021
        OS build	19043.1165
        Experience	Windows Feature Experience Pack 120.2212.3530.0

  - Docker Desktop Version: 3.6.0 (67351)
   
  - WSL2 or Hyper-V backend?  Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No, I'm running on my real local machine.

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by TomasSlaman** [comment]
I'm experiencing the same issue and have some additional information when the issue started occuring.

The issue started occuring right after installing Visual Studio Preview 2022 Update 3.1, was working fine with Update 2.1

1. Re-installing Docker did not resolve anything.
2. Disabling/ enabling Hyper-V again also did not resolve the issue.

Any ideas/ solutions are very welcome.

**Comment by TomasSlaman** [comment]
Some additional info;

Tried these solutions (which did not resolve anything).
1. Restarting computer.
2. Re-installing docker
3. Using previous docker version (3.5.2)
4. Disabling and re-enabling Hyper-V
5. Praying

No luck, can't use docker at all because of it, quite troublesome.

**Comment by askrivileva** [comment]
Same to me. Tried everything @TomasSlaman described.

**Comment by TomasSlaman** [comment]
@askrivileva @ederbond There is a solution available in this issue; https://github.com/docker/for-win/issues/11899

In short; 
1. Go to C:\ProgramData\Docker
2. Right click on panic.txt -> Properties
3. Uncheck 'Read-Only'

**Comment by askrivileva** [comment]
Thanks @TomasSlaman . Works now.

**Comment by robertfsegal** [comment]
Adding a note here as well was having docker startup issues for Windows containers only (Linux was fine) and turning off the read only property on **panic.log** fixed this issue.

Same steps as @TomasSlaman indicated [above](https://github.com/docker/for-win/issues/11915#issuecomment-900269657) but for clarity the file to modify is **panic.log** or at least for me it is.

Docker specs...

- Docker Engine v20.10.8
- Windows 10 Pro 
- Version - 21H1
- Installed On - 2020-06-12
- OS Build - 19043.1165
- Experience - Windows Feature Experience Pack 120.2212.3530.0

**Comment by thaJeztah** [comment]
This issue with panic.log permissions has been resolved in Docker Desktop 4.1.0 and up; https://github.com/docker/for-win/issues/11899. Let me go ahead and close this one
