### ISSUE TITLE
Docker freezes when trying to switch to Windows Containers

### ISSUE THREAD

**Issue by jwbrewster** [docker/for-win#11925]
- Diagnostics ID:  FEAB3F0B-07A0-461C-8192-96159CB98C12/20210818133631

### Actual behavior
When I right-click and select Switch to Windows Containers, Docker times out and freezes.  I've also tried doing it via the command line and get the same result.  

### Expected behavior
Docker should restart in Windows container mode

### Information
  - Is it reproducible?  Yes
  - Is the problem new?  No
  - Did the problem appear with an update?  Initial install
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.
-->
  - Windows Version: 10 Pro 10.0.19042 Build 19042
  - Docker Desktop Version: 3.6.0 (67351)
  - WSL2 or Hyper-V backend?   WSL2 I believe, Hyper-V is also installed and virtualization enabled in bios
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior
1. Start a fresh install of Docker Deskop for WIndows
2. Right click in system tray docker icon and select "Switch to Windows Containers"

This worked *once* somewhere in the middle of my attempts over the last few weeks, so I know it can work - but I cannot get it to work again.   Thanks!

Also, I've tried with both "Use the WSL2 based engine" on and off, have tried re-installing the hyper-v feature, and double checked that virtualization is on in the bios

This may help as well... after I get the error, and the daemon isn't running, when I try and clean and delete everything, I get a different set of errors, seen here:  FEAB3F0B-07A0-461C-8192-96159CB98C12/20210818134321

**Comment by jwbrewster** [comment]
I found this on another post, and it SEEMS to have resolved the problem:

@askrivileva @ederbond There is a solution available in this issue; ##11899

In short;

Go to C:\ProgramData\Docker
Right click on panic.txt -> Properties
Uncheck 'Read-Only'

**Comment by msilva1610** [comment]
It worked for me. Thanks so much.
