### ISSUE TITLE
Docker Desktop is stuck at "starting"

### ISSUE THREAD

**Issue by manuesperon** [docker/for-win#11932]
- [x ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Is the problem new? Yes
  - Did the problem appear with an update? No, this happened before I updated, and persisted after updating.

  - Windows Version: 10 Home
  - Docker Desktop Version: Docker version 20.10.8, build 3967b7d
  - WSL2 or Hyper-V backend?  Hyperv

The DIagnostics tool is also stuck forever.

I've found several posts about this but they were either closed despite being unsolved or the solution offered didn't work for me.

![image](https://user-images.githubusercontent.com/24298023/130008161-b2385bf0-8766-4f85-8524-fa16fe3c3064.png)

**Comment by MicahBCode** [comment]
Same problem here still present....

**Comment by manuesperon** [comment]
> Same problem here still present....

Hey there, this solved it for me: https://github.com/docker/for-win/issues/8204#issuecomment-683377496
Hope it helps!

**Comment by MicahBCode** [comment]
Not solving the problem for me. @manuesperon
