### ISSUE TITLE
Docker 3.6.0. not working on Windows 10 pro -- fresh installation

### ISSUE THREAD

**Issue by anandbohra** [docker/for-win#11936]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Docker for windows gives error
### Expected behavior
Docker for windows should run
### Information

  - Windows Version: Windows 10 pro version 21H1 os build 19043.1165
  - Docker Desktop Version: 3.6.0 (67351)
  - WSL2 or Hyper-V backend?  linux docker working but when right click and select switch to windows container this error come
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: running on personal laptop

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by anandbohra** [comment]
installed Windows 10 pro & downloaded latest docker, but when my visual studio core application try to run docker get this error

**Comment by RossVertizan** [comment]
@anandbohra  What message are you seeing?

I have just run the Docker Desktop installation process and it failed, this is what I see beneath Installation failed in the Docker Desktop 3.6.0 installation window:
```text
Component CommunityInstaller.ServiceAction failed: Failed to delete service: The specified service has been marked for deletion
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
```
Is this GitHub for Docker or Docker Desktop?  Am I filing this issue in the correct place?

**Comment by anandbohra** [comment]
I created new Dot net core project in visual studio 2019, let VS install docker & do all steps, again it failed with below message.


Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
docker run -dt -v "C:\Users\BohraBros\onecoremsvsmon\16.11.1196.0:C:\remote_debugger:ro" -v "D:\Anand\From Home\LearnDotNetCore\LearnDotNetCore:C:\app" -v "D:\Anand\From Home\LearnDotNetCore:c:\src" -v "C:\Users\BohraBros\AppData\Roaming\Microsoft\UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro" -v "C:\Users\BohraBros\AppData\Roaming\ASP.NET\Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro" -v "C:\Users\BohraBros\.nuget\packages\:c:\.nuget\fallbackpackages" -e "DOTNET_USE_POLLING_FILE_WATCHER=1" -e "ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true" -e "ASPNETCORE_ENVIRONMENT=Development" -e "ASPNETCORE_URLS=https://+:443;http://+:80" -e "NUGET_PACKAGES=c:\.nuget\fallbackpackages" -e "NUGET_FALLBACK_PACKAGES=c:\.nuget\fallbackpackages" -P --name LearnDotNetCore --entrypoint C:\remote_debugger\x64\msvsmon.exe learndotnetcore:dev /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /fallbackloadremotemanagedpdbs /timeout:2147483646 /LogDebuggeeOutputToStdOut 
docker: error during connect: This error may indicate that the docker daemon is not running.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/create?name=LearnDotNetCore": open //./pipe/docker_engine: The system cannot find the file specified.
See 'docker run --help'.
A non-critical error occurred while getting the container(s) ready. Your project(s) will continue to function normally. The error was: Docker command failed with exit code 127.
docker: error during connect: This error may indicate that the docker daemon is not running.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/create?name=LearnDotNetCore": open //./pipe/docker_engine: The system cannot find the file specified.
See 'docker run --help'.
If the error persists, try restarting Docker Desktop.

**Comment by anandbohra** [comment]
docker for linux / wsl2 is working when I right click on whale icon and select Switch to windows containers.... it failed with error & that windows gives me upload crash Report button that auto created this ticket


System.ServiceProcess.TimeoutException:
Time out has expired and the operation has not been completed.
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(Settings settings, String args, Dictionary`2 env) in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 208
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.<GetExecutor>b__0(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()

**Comment by elfenix** [comment]
I'm also seeing this on a fresh windows 10 install - with previously added and working WSL2 config.

Stack Trace:
Component CommunityInstaller.ExecAction failed: Process InstallerCli.exe exited with code 1
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()

Username on this PC does include a .  (C:\Users\first.last\ form)

Maybe related to #11514 ?

**Comment by elfenix** [comment]
I was able to work around by installing 3.5.2

**Comment by anandbohra** [comment]
Please share link to download 3.5.2
Fed up with docker error 

Hope this version allow me to start my docker journey

**Comment by RossVertizan** [comment]
Link to [3.5.2](https://desktop.docker.com/win/stable/amd64/66501/Docker%20Desktop%20Installer.exe).

To find other versions of Docker Desktop search for Docker Desktop Release Notes.

**Comment by anandbohra** [comment]
same issue with Docker 3.5.2
![image](https://user-images.githubusercontent.com/6223597/130314849-242cf993-03db-4466-988e-76569245d3df.png)
![image](https://user-images.githubusercontent.com/6223597/130314851-07ad0d12-8255-49a7-987c-d1a06a4bbaeb.png)
![image](https://user-images.githubusercontent.com/6223597/130314906-94721a10-6040-403a-ab7d-1c667a5afdc7.png)

**Comment by Jossec101** [comment]
I also had to rollback to 3.5.2..

**Comment by anandbohra** [comment]
in my case even V 3.5.2 gave same error.

**Comment by RossVertizan** [comment]
@anandbohra Have you tried rebooting your Windows machine and then trying the installation process again.  This is what I had to do. 
The Docker Desktop installation process seems to frequently get hung up on services that are running and it can't stop.
Though having said that I am a little confused, the screenshots you have posted show the Docker Desktop running, albeit in a crashed state.
My advice is to:
  1. Reboot your machine
  2. Start no other processes (allow automatic ones to start, but don't launch any other tools)
  3. Run the Docker Desktop installation process
  4. If it fails, try and determine the service/process that is stopping the installation and using the services app try and stop the process and try again.
  5. If all fails post a clear description of the failure here
by this point, it has always worked for me, so I claim no expertise, so no promises.

**Comment by anandbohra** [comment]
I upgraded my machine from Win 10 Home to Pro by buying license & did fresh installation.
You are correct Docker is installing but only supporting WSL2, there is no option for selecting HyperV
I enabled hyper V & added container in windows add features.

Docker is working fine but the moment I build VS19 project that needs Docker for Windows it shows tantrum,
these error screenshot appears if I right click Whale icon & select switch to Windows Containers... the error comes.


I did lots of restart & machine is upto date with all updates from microsoft

**Comment by RossVertizan** [comment]
Is there a reason you can't use WSL2?

**Comment by georgebv** [comment]
Same thing here - I am on Windows 10, version 20H2 (OS Build 19042.1110) and I cannot install Docker Desktop 3.6.0, it fails. Whenever it updates 3.5.2 to 3.6.0 the update fails and, instead of rolling back, Docker decides to uninstall itself. This happens on our existing Windows machines where we have been using docker for years and on brand new machines. I have WSL2 installed and enabled, it works like a charm with version 3.5.2.

My error is exactly the same as the one @RossVertizan has

**Comment by RossVertizan** [comment]
@georgebv  - except that in my case I managed to install 3.6.0 after rebooting.  I can't help more than that, because that's all I did.

**Comment by kjczarne** [comment]
I have an identical issue on two separate Windows computers, one with Win 10 Pro and one with Windows Server 2019. If I `Remove-Service com.docker.service` on either computer, I get:

```
Component CommunityInstaller.ServiceAction failed: Failed to start service: The service did not respond to the start or control request in a timely fashion
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
```

This has broken all my CI workflows. Restarting the PCs doesn't help, removing the service, rolling back to 3.5.0 and clearing `C:\ProgramData\DockerDesktop` does not help either.

**Comment by kjczarne** [comment]
I was able to work around this issue by setting `ServicesPipeTimeout` to a higher limit in `regedit`. See: https://github.com/docker/for-win/issues/6091#issuecomment-830132367

**Comment by RossVertizan** [comment]
Just a quick note.  I installed Docker Desktop 4.0.0 yesterday and had exactly the same issue as reported previously.  Again it was fixed by a machine reboot and then installing Docker Desktop.

**Comment by anandbohra** [comment]
After installing Docker 4.0.0 & then updated to 4.0.1 Docker for Windows is starting but When I run my VS2019 code (sample project) getting below error
CTC1014	Docker command failed with exit code 1.
