### ISSUE TITLE
Docker Desktop fails to launch

### ISSUE THREAD

**Issue by Abid-Sarwar** [docker/for-win#11942]
- [ x] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 03C94531-97AA-4C0E-AAD1-C795D84552B1/20210819150955

### Actual behavior

Error when launching Docker Desktop:

System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\p-sarwara\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine]

Arguments for running Linux binaries:

    If no command line is provided, wsl.exe launches the default shell.

    --exec, -e <CommandLine>

        Execute the specified command without using the default Linux shell.

    --

        Pass the remaining command line as is.

Options:

    --distribution, -d <Distro>

        Run the specified distribution.

    --user, -u <UserName>

        Run as the specified user.

Arguments for managing Windows Subsystem for Linux:

    --help

        Display usage information.

    --install [Options]

        Install additional Windows Subsystem for Linux distributions.

        For a list of valid distributions, use 'wsl --list --online'.

        Options:

            --distribution, -d [Argument]

                Downloads and installs a distribution by name.

                Arguments:

                    A valid distribution name (not case sensitive).

                Examples:

                    wsl --install -d Ubuntu

                    wsl --install --distribution Debian

    --set-default-version <Version>

        Changes the default install version for new distributions.

    --shutdown

        Immediately terminates all running distributions and the WSL 2

        lightweight utility virtual machine.

    --status

        Show the status of Windows Subsystem for Linux.

    --update [Options]

        If no options are specified, the WSL 2 kernel will be updated

        to the latest version.

        Options:

            --rollback

                Revert to the previous version of the WSL 2 kernel.

Arguments for managing distributions in Windows Subsystem for Linux:

    --export <Distro> <FileName>

        Exports the distribution to a tar file.

        The filename can be - for standard output.

    --import <Distro> <InstallLocation> <FileName> [Options]

        Imports the specified tar file as a new distribution.

        The filename can be - for standard input.

        Options:

            --version <Version>

                Specifies the version to use for the new distribution.

    --list, -l [Options]

        Lists distributions.

        Options:

            --all

                List all distributions, including distributions that are

                currently being installed or uninstalled.

            --running

                List only distributions that are currently running.

            --quiet, -q

                Only show distribution names.

            --verbose, -v

                Show detailed information about all distributions.

            --online, -o

                Displays a list of available distributions for install with 'wsl --install'.

    --set-default, -s <Distro>

        Sets the distribution as the default.

    --set-version <Distro> <Version>

        Changes the version of the specified distribution.

    --terminate, -t <Distro>

        Terminates the specified distribution.

    --unregister <Distro>

        Unregisters the distribution and deletes the root filesystem.

 stderr: 
   at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 146
   at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__17.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 169
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__26.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 178
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92

### Expected behavior

Docker launches successfully using WSL2 backends

### Information

  - Windows Version: 10.0.19043
  - Docker Desktop Version: 3.5.2
  - WSL2 or Hyper-V backend?  WSL2, Windows containers are fine
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Azure D8s_v3 W10

### Steps to reproduce the behavior
03C94531-97AA-4C0E-AAD1-C795D84552B1/20210819150955 debug info

https://docs.microsoft.com/en-us/windows/wsl/install-win10 followed steps here and then re-installed docker.

Launch docker with WSL2 Backend

**Comment by stephen-turner** [comment]
If you upgrade to 3.6, there is an experimental self-diagnosis program included: see https://docs.docker.com/desktop/windows/troubleshoot/#experimental-self-diagnose-tool. It would be good to know what output that produces and whether it solves the problem.

**Comment by Abid-Sarwar** [comment]
Hi Stephen, thanks for the response. I've updated to 3.6, unfortunately the same problem persisted.

The self diagnostics file is attached.

[self-diagnose.txt](https://github.com/docker/for-win/files/7030833/self-diagnose.txt)

version:
![image](https://user-images.githubusercontent.com/60890248/130425874-4422c7a2-2a28-45c8-86e1-fa4e415f78d5.png)

**Comment by stephen-turner** [comment]
Interesting, so it reports "WSL Distribution docker-desktop is missing".

What does `wsl -l -v` say?

**Comment by Abid-Sarwar** [comment]
Only the default Ubuntu Distro is visible

![image](https://user-images.githubusercontent.com/60890248/130429956-ef59a083-4eaa-47aa-8c5a-7f9acffae83f.png)

**Comment by RiaanAspelingSage** [comment]
I think it might have the same issue. I've run the command: 

& 'C:\Program Files\Docker\Docker\resources\com.docker.backend.exe' check

And received the following output:

time="2021-08-23T12:18:10+02:00" level=error msg="while parsing JSON from C:\\Users\\myuser\\AppData\\Roaming\\Docker\\settings.json: json: cannot unmarshal bool into Go struct field Content.proxyHttpMode of type string"
time="2021-08-23T12:18:10+02:00" level=fatal msg="while parsing JSON from C:\\Users\\myuser\\AppData\\Roaming\\Docker\\settings.json: json: cannot unmarshal bool into Go struct field Content.proxyHttpMode of type string"

Checking the content of the settings.json file, the value for proxyHttpMode is a boolean set to false. I've tried changing it to "" or null and even true. But received different errors.

What solved it for me was just renaming the settings.json file to settings.json.bak. The Docker Desktop then started normally.

**Comment by Abid-Sarwar** [comment]
I tried this but the value was set to "system" in the original file and after renaming it. Also ran the check command and the only error I can see is:

time="2021-08-23T11:57:02+01:00" level=fatal msg="starting port-forwarding control server on \\\\.\\pipe\\dockerVpnKitControl: open \\\\.\\pipe\\dockerVpnKitControl: Access is denied."

**Comment by stephen-turner** [comment]
@RiaanAspelingSage I think your issue is different.

@Abid-Sarwar I think the problem might be that you only have WSL 1, you need WSL 2. The Microsoft doc you cited before has instructions about this.

**Comment by Abid-Sarwar** [comment]
@stephen-turner I have followed the instructions there and definitely have WSL2. This was working at one point and wsl -l -v listed both WSL2 Docker Distributions , it's almost as it stopped working over night.  

I know this was working on v2.5.1, but I've tried rolling back to that version but now it has the same issue. I've uninstalled all components of WSL/Docker and then re-installed but this issue is persistent.

Latest WSL2 Kernel: 
![image](https://user-images.githubusercontent.com/60890248/130457618-ba3482b3-21f3-4d5d-9777-3d6ec3ae7262.png)

Subsystem:
![image](https://user-images.githubusercontent.com/60890248/130457712-d3e35717-c868-4045-a5c0-7bc8f83c4def.png)

Virtualization:
![image](https://user-images.githubusercontent.com/60890248/130457778-e539a6bc-a035-44f8-8ea0-5d9ba4020ae8.png)

I'm stuck! :(

**Comment by Abid-Sarwar** [comment]
Hi @stephen-turner, thanks for your support with this but I've found the culprit! Thanks to an issue on the WSL page. I'll leave it here for anyone to review in case they run into this issue.

Its actually an issue with WSL itself and a security patch. After uninstalling **_KB5005033_** and rebooting. Docker launched successfully with WSL2 Containers  https://github.com/microsoft/WSL/issues/7332

**Comment by Abid-Sarwar** [comment]
Hi @stephen-turner, thanks for your support with this but I've found the culprit! Thanks to an issue on the WSL page. I'll leave it here for anyone to review in case they run into this issue.

Its actually an issue with a security patch. After uninstalling KB5005033 and rebooting. Docker launched successfully with WSL2 Containers microsoft/WSL#7332

**Comment by stephen-turner** [comment]
Ah, great, glad you solved it, and thanks for the pointer to that KB.

**Comment by licanhua** [comment]
@Abid-Sarwar Are you using Windows server or Edition Windows 10 Enterprise for Virtual Desktops?

**Comment by Abid-Sarwar** [comment]
Windows 10 Enterprise for Virtual Desktops, v10.0.19043
