### ISSUE TITLE
Unspecified/Unknown whether volume is bind-mounted from the Linux filesystem upon creating a named volume on WSL2.

### ISSUE THREAD

**Issue by KyryloKaralyus** [docker/for-win#11940]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics

### Actual behavior
Unknown
### Expected behavior
named volume bind-mounted from the Linux filesystem rather than remounted from windows host 
### Information
I'm trying to install on WSL2 with local (for persistent data) [ named volume](https://youtu.be/p2PH_YPCsis?t=202) with `-v myname`  as opposed to host volume `-v /mnt/c/users:/users`  (which is not recommended by wsl), or `-v ~/my-project:/sources <my-image>`  [(which is recommended by wsl](https://docs.docker.com/desktop/windows/wsl/#best-practices)) or anynomous volume with -v /var/lib/mysql/data  ;
So when I'm trying to do that, is named volume bind-mounted from the Linux filesystem rather than remounted from windows host ? Or do I need to explicitly state -v ~/my-project:/sources <my-image>  for volume to be bind-mounted from Linux filesystem ?

  - Windows Version: 10, latest update
  - Docker Desktop Version: latest
  - WSL2 or Hyper-V backend?  WSL2, latest version
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior
  1. docker run -d --name timescaledb -p 5432:5432 -e POSTGRES_PASSWORD=password -v somename:/var/lib/postgresql/data timescale/timescaledb-postgis:latest-pg12

**Comment by stephen-turner** [comment]
Yes, the files for the named volume live in the WSL 2 filesystem, so they are fast to access. Does that answer your question?

**Comment by KyryloKaralyus** [comment]
It does, thank you ! Would be great to add this clarification to docs.
