### ISSUE TITLE
Docker for windows fails to start after clean install

### ISSUE THREAD

**Issue by ofaurax** [docker/for-win#1195]
### Expected behavior
Start

### Actual behavior
"An error occured"
```
Unable to stop: L’exécution de la commande s’est arrêtée, car la variable de préférence « ErrorActionPreference » ou le paramètre courant a la valeur Stop : Le module « Hyper-V » spécifié n'a pas été chargé, car aucun fichier de module valide n'a été trouvé dans un répertoire de module.
à <ScriptBlock>, <Aucun fichier> : ligne 79
   à Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) dans C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:ligne 177
   à Docker.Backend.ContainerEngine.Linux.DoStop() dans C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:ligne 279
   à Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) dans C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:ligne 122
   à Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) dans C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:ligne 47
   à Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) dans C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:ligne 145
```

### Information

  - Diagnostic ID 5AC7ADBF-9610-43A7-8ABA-66F658D7377E/2017-10-10_12-33-23
  - Windows 10 Famille, Version 1703, OS version 15063.632

### Steps to reproduce the behavior

  1. Install on latest Windows 10 64bits
  2.Try to start docker for windows

**Comment by jasonbivins** [comment]
Hi @ofaurax 
It does look like there's an issue with Hyper-V - specifically with the VMSP service.

I did find a Microsoft article that is supposed to fix this issue - but please be careful as it does involve a registry change.  I tested it here on my machine and didn't have any problems afterwards from the registry change.
https://support.microsoft.com/en-us/help/2013544/error-message-when-you-manage-a-vhd-file-in-windows-server-2008-a-virt

**Comment by sylvainlecoy** [comment]
I have exactly the same issue on Windows 10 64bits.

**Comment by sebcaps** [comment]
Got the same issue; applied fix suggested by @jasonbivins  but still failed to start docker...
@ofaurax  did you finally  manage to start your docker ??

**Comment by khalilbenaissa10** [comment]
Got the same issue also, did any one find a solution ?

**Comment by vpontin** [comment]
IF you have Win10 Home, you are out of luck, since Hyper-V isnt supported in this system:
https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v
