### ISSUE TITLE
D7948237-5A98-4E9E-AFB9-9BC8E94F206B/20210820141910

### ISSUE THREAD

**Issue by guang098** [docker/for-win#11953]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
The new experimental self-diagnose tool (https://docs.docker.com/desktop/windows/troubleshoot/#experimental-self-diagnose-tool) reports:

3 failures detected
1 : is WSL installed?
    Failed with: exit status 4294967295
The Docker engine runs inside a WSL environment. Therefore WSL must be installed.

2 : are WSL distros installed?
    Failed with: WSL Distribution docker-desktop is missing
The Docker engine uses several WSL distributions. Therefore these must be installed.

3 : does the bootloader have virtualization enabled?
    Failed with: hypervisorlaunchtype is set to off in the bootloader
The Docker engine runs inside a Linux VM. Therefore Windows must boot with the Microsoft Hypervisor enabled.
Please run:
 bcdedit /set hypervisorlaunchtype auto

Maybe these will help you.
