### ISSUE TITLE
Docker FAILS to start after clean install

### ISSUE THREAD

**Issue by J-Lmb** [docker/for-win#11966]
![image](https://user-images.githubusercontent.com/39498415/130373750-5823ca39-65db-4efb-85f0-cfc92809fb7d.png)

Coula anybody assist with the error above. Docker does not seems to start on Windows.

**Comment by stephen-turner** [comment]
The answer is at the link on your screenshot.

**Comment by J-Lmb** [comment]
I requested help because I have gone through that link and the resources found did not help.

**Comment by stephen-turner** [comment]
In what way? Are you saying that those items are already enabled in the BIOS and it's being misdiagnosed?
