### ISSUE TITLE
Docker Failed to Initialize : Docker Desktop is Shutting Down. 

### ISSUE THREAD

**Issue by zedd9165** [docker/for-win#11967]
- [x ] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

When running the application upon starting the docker desktop app, it shows me the error as mentioned in the subject and it doesnt start. 

### Expected behavior

Should start running upon opening the application. 

### Information

  - Windows Version:
  - Docker Desktop Version: 21h1 (OS BUILD 19043.1165)
  - WSL2 or Hyper-V backend?  
    Enabled 
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:
    Not

### Log

```
[08:30:52.220][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[08:30:52.527][IPCClient         ][Info   ] (5c1e7562) 8fa11c3c-GoBackendClient-CSharp C->S BackendAPI GET /ping
[08:30:52.527][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[08:30:52.829][IPCClient         ][Info   ] (ef48f141) 8fa11c3c-GoBackendClient-CSharp C->S BackendAPI GET /ping
[08:30:52.829][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[08:30:53.134][IPCClient         ][Info   ] (65b865ae) 8fa11c3c-GoBackendClient-CSharp C->S BackendAPI GET /ping
[08:30:53.134][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[08:30:53.453][IPCClient         ][Info   ] (407e7f0b) 8fa11c3c-GoBackendClient-CSharp C->S BackendAPI GET /ping
[08:30:53.453][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[08:30:53.765][IPCClient         ][Info   ] (5eb08221) 8fa11c3c-GoBackendClient-CSharp C->S BackendAPI GET /ping
[08:30:53.765][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[08:30:54.067][IPCClient         ][Info   ] (aa9cb83b) 8fa11c3c-GoBackendClient-CSharp C->S BackendAPI GET /ping
[08:30:54.067][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[08:30:54.380][IPCClient         ][Info   ] (eaec7f63) 8fa11c3c-GoBackendClient-CSharp C->S BackendAPI GET /ping
[08:30:54.380][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[08:30:54.693][IPCClient         ][Info   ] (8f125368) 8fa11c3c-GoBackendClient-CSharp C->S BackendAPI GET /ping
[08:30:54.693][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[08:30:55.008][IPCClient         ][Info   ] (b2e7f848) 8fa11c3c-GoBackendClient-CSharp C->S BackendAPI GET /ping
[08:30:55.008][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[08:30:55.321][IPCClient         ][Info   ] (92c48810) 8fa11c3c-GoBackendClient-CSharp C->S BackendAPI GET /ping
[08:30:55.321][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
```

**Comment by Ogulcan-Ozdemir** [comment]
I am facing same problem after updating 3.6.0. Docker cli seems working though.

**Comment by zedd9165** [comment]
> I am facing same problem after updating 3.6.0. Docker cli seems working though.

I just found a solution to solve it. Go to C drive , Users, Select your user, App data, Roaming and then delete the Docker folder. You shall be able to start docker again.

**Comment by franciscosamuel** [comment]
For what it's worth, I also started having the same issue after using the auto updater to update to 3.6.0 (67351) and reinstalling also solved the problem.

**Comment by Wiki1991** [comment]
> > I am facing same problem after updating 3.6.0. Docker cli seems working though.
> 
> I just found a solution to solve it. Go to C drive , Users, Select your user, App data, Roaming and then delete the Docker folder. You shall be able to start docker again.

Useful!

**Comment by kimberglund** [comment]
> > I am facing same problem after updating 3.6.0. Docker cli seems working though.
> 
> I just found a solution to solve it. Go to C drive , Users, Select your user, App data, Roaming and then delete the Docker folder. You shall be able to start docker again.

This worked for me. Thanks!

**Comment by Ogulcan-Ozdemir** [comment]
> 
> 
> > I am facing same problem after updating 3.6.0. Docker cli seems working though.
> 
> I just found a solution to solve it. Go to C drive , Users, Select your user, App data, Roaming and then delete the Docker folder. You shall be able to start docker again.

It works me too thanks.

**Comment by zachjonesnoel** [comment]
@mikependon tried it and it didn't be of a good help for me.

**Comment by triynko** [comment]
Docker 4.0 doesn't start at all. Weird to force an upgrade, ask to pay for it, and it breaks the installation and halts all work.
![image](https://user-images.githubusercontent.com/1005113/131710871-8c87ba49-c39a-4942-acc8-fc42f1a9ecce.png)

**Comment by triynko** [comment]
After a factory reset, now it just hangs at this screen. Doesn't time out. Just stays at this screen forever. It's been a half hour.
![image](https://user-images.githubusercontent.com/1005113/131710998-1587d33e-1c89-4f9a-a364-9f7c946361fa.png)

**Comment by triynko** [comment]
Every time I click the taskbar icon to try to interact with it, it just launches more processes:
![image](https://user-images.githubusercontent.com/1005113/131711675-49e8f25c-e3d7-4713-ad38-e46878810236.png)

**Comment by letsjustfixit** [comment]
> 
> 
> > I am facing same problem after updating 3.6.0. Docker cli seems working though.
> 
> I just found a solution to solve it. Go to C drive , Users, Select your user, App data, Roaming and then delete the Docker folder. You shall be able to start docker again.

^^ that helps. Thanks @zedd9165 !
"Copy-paste"able command (asks for confirmation):

`RMDIR /S %USERPROFILE%\AppData\Roaming\Docker`

shut up just do it (no confirmation):

`RMDIR /S  /Q %USERPROFILE%\AppData\Roaming\Docker`

**Comment by jhirschibar** [comment]
> > I am facing same problem after updating 3.6.0. Docker cli seems working though.
> 
> I just found a solution to solve it. Go to C drive , Users, Select your user, App data, Roaming and then delete the Docker folder. You shall be able to start docker again.

Not sure how you found this, but it worked for me as well! Thanks!!

**Comment by sugendran** [comment]
For anyone investigating. This is what shows up in the logs
```
time="2021-09-11T14:56:43+10:00" level=fatal msg="while parsing JSON from C:\\Users\\sugen\\AppData\\Roaming\\Docker\\settings.json: json: cannot unmarshal bool into Go struct field Content.proxyHttpMode of type string"
main.main()
	common/cmd/com.docker.backend/main.go:69 +0x31b
```

deleting just the settings.json file the fixes it

**Comment by ser-art** [comment]
> > I am facing same problem after updating 3.6.0. Docker cli seems working though.
> 
> I just found a solution to solve it. Go to C drive , Users, Select your user, App data, Roaming and then delete the Docker folder. You shall be able to start docker again.

Worked for me, Thank you!

**Comment by onyxmaster** [comment]
Even better, removing only the the `"proxyHttpMode": ...` line from `settings.json` helps.

**Comment by zachjonesnoel** [comment]
> Even better, removing only the the `"proxyHttpMode": ...` line from `settings.json` helps.

Thanks @onyxmaster let me try this. 

@ser-art and @sugendran it worked for a while and the issue resurfaced after restarting Docker. So just check if after restarting Docker if its working well.

**Comment by StefanScherer** [comment]
Thanks @zedd9165 for reporting this. And thanks @onyxmaster for the workaround.
> Even better, removing only the the "proxyHttpMode": ... line from settings.json helps.

Indeed, we can reproduce the problem. 
Docker Desktop normally migrates old settings on startup, for the `proxyHttpMode` setting it works eg. for updates 3.2.2 -> 3.5.2, but stopped working for updates 3.2.2 -> 3.6.0 or higher. We're working on a fix for a future version.

**Comment by koichirok** [comment]
In my case, it seems that there was a `Docker Desktop.exe` that was not working properly.

```
% tasklist.exe | grep -i docker
com.docker.service            6652 Services                   0     34,556 K
Docker Desktop.exe           13344 Console                    1     54,400 K
```

Executing `taskkill.exe -F -IM:Docker Desktop.exe` and restarting `Docker Desktop` solved my problem.

**Comment by jgmurx** [comment]
> C:\Users\<username>\AppData\Roaming\Docker\

Had the same issue.
For some reason: C:\Users\<username>\AppData\Roaming\Docker\settings.json was empty. I had renamed it from settings.json to _removed_settings.json the Docker succesfully started, and it has created new settings.json

**Comment by Advik-B** [comment]
Same here, ive tried all the methords, still no

**Comment by Chefz** [comment]
You can also go to your user folder and delete .docker folder, and then restart Docker Desktop
It works for me

**Comment by isaac-infotrend** [comment]
Also ensure that the .docker dotfolder within your windows home directory %USERPROFILE%/.docker is not a hidden folder.
