### ISSUE TITLE
Docker Desktop crashes when using Windows Containers

### ISSUE THREAD

**Issue by ChrisBaker812** [docker/for-win#11968]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6CEED37B-4CBD-485F-988E-B9D3C4357CD5/20210823073956

### Actual behavior
Switch to Windows Containers - this causes a timeout error, option to Quit Docker Desktop - pressed quit. Remove readonly flag from programdata/docker/panic.log file, and docker starts without error using Windows Containers. Restart computer and Docker Desktop crashes with same issue, causing the need to change the readonly flag once again. 

### Expected behavior
Docker desktop should switch to and from Windows and Linux containers without a .net exception and restarting the computer should not cause Docker Desktop to crash when Windows starts.

### Information

  - Windows Version: Windows 10 21H1
  - Docker Desktop Version: 3.6
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: N

### Steps to reproduce the behavior

1 . Switch to Windows Containers. 
2. Remove readonly flag from programdata/docker/panic.log file. 
3. Restart computer and Docker Desktop crashes.

**Comment by ChrisBaker812** [comment]
Just in case this helps as a workaround (after trying several proposed fixes after a google search) I have created a scheduled task that, when I log-in, uses powershell to delete the Panic.log file. This has the effect that DD recreates the file and thus everything works as expected.

I have 2 other machines that have DD on and neither of them exhibit this behaviour, but I can't see why there is a difference as they are setup in exactly the same way.  

Hope the above helps someone.

**Comment by mkschl** [comment]
I just did these steps and it worked:

1. Stop Docker desktop
2. Delete ProgramData/docker/panic.log
3. Restart Docker Desktop
4. Switch to Windows Containers

**Comment by ChrisBaker812** [comment]
Sorry, perhaps I wasn't clear. I have 3 systems all setup in the same way. On my main machine, when I set "Use Windows Containers" I get an error (timeout exception), I click the Quit button. only on that onw machine, the other 2 work without exception. If I then either delete the Panic.log file OR uncheck the readonly checkbox and re-run DD, then it works without an issue. However, if I reboot the machine I have the same exception the file is readonly again and I have to go through the whole process again. 

Hence why I have had to take the above steps as a work around (create a Scheduled task to delete the file at startup).

The other 2 machines work as expected i.e. they don't crash at machine startup when "Use Windows Containers" is selected and the Panic.log file IS readonly.

**Comment by marcusschroeder** [comment]
We had a similar problem. We downgraded to Docker Desktop 3.5.2. for now, since 3.6.0 doesn't seem stable at this point.

**Comment by ChrisBaker812** [comment]
I tried downgrading, but that didn't work either.

**Comment by ChrisBaker812** [comment]
Except they don't work! As when you reboot windows the error returns and you have to perform that step everytime, which is, to me, a little annoying. So I thought I'd share how I managed to fix it permamantly, but would like to know why I had to perform this step.
