### ISSUE TITLE
Docker Image is pulled from docker hub but does not run - Windows

### ISSUE THREAD

**Issue by ArashMasroor** [docker/for-win#11979]
Hi,
I am new to Docker CE.
So I started through this link introduced by Microsoft:
https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/run-your-first-container

My Windows Server 2019 version is: Microsoft Windows [Version 10.0.17763.2114]

`PS C:\Users\Administrator.WIN-KC35LF8V1J1> docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  cluster: Manage Mirantis Container Cloud clusters (Mirantis Inc., v1.9.0)
  registry: Manage Docker registries (Docker Inc., 0.1.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 1
 Server Version: 20.10.6
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Standard Version 1809 (OS Build 17763.2114)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 16GiB
 Name: SRVCI34-SITE022
 ID: 5EAL:GY73:TBWG:DK5D:IOAU:37BR:LKDR:KR5C:2JEW:R7FX:D35J:SKRQ
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false`

command **docker pull mcr.microsoft.com/windows/nanoserver:1809** works just fine, but when I go to run the image using below command,It fails: 
**docker run -it mcr.microsoft.com/windows/nanoserver:1809 cmd.exe**

`PS C:\Users\Administrator.WIN-KC35LF8V1J1> docker run -it mcr.microsoft.com/windows/nanoserver:1809 cmd.exe
Unable to find image 'mcr.microsoft.com/windows/nanoserver:1809' locally
1809: Pulling from windows/nanoserver
bc8517709e9c: Pull complete
Digest: sha256:bf497134e6b9f1c0b0bcd677cff79f7fae6e545e5a6bf0198676b3b6eede1a64
Status: Downloaded newer image for mcr.microsoft.com/windows/nanoserver:1809
docker: Error response from daemon: container 7a72ec5f556552051b6b10b451ec87c9075e8836d5440a9787fd3fa35546ad69 encountered an error during hcsshim::System::Start: context deadline exceeded.`

**Comment by stephen-turner** [comment]
This bug tracker is for Docker Desktop, not Docker engine. Docker engine bugs should be reported at https://github.com/moby/moby. Thank you.
