### ISSUE TITLE
Crash when switching to Windows containers

### ISSUE THREAD

**Issue by heinrichvermeulen** [docker/for-win#11978]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 791148D9-01B2-4B4F-B8D1-9F6E14CD49C4/20210823230231

### Actual behavior
Crashes.

### Expected behavior
Switch to Windows containers

### Information
  - Windows Version: Windows 10 Enterprise
  - Docker Desktop Version: 3.6.0 (67351)
  - WSL2 or Hyper-V backend?  Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No, straight on Win10 PC

### Steps to reproduce the behavior
  1. Installed a fresh copy of the latest Docker Desktop (3.6.0)
  2. Once installation is complete, run Switch to Windows containers.
  3. Get error
  4. Uploaded log file with all the details.
  5. Tried this process 3 times - same result.

[log.txt](https://github.com/docker/for-win/files/7035363/log.txt)

**Comment by StefanScherer** [comment]
Thanks for the report. We track this issue in #11899 and there's a workaround to remove the panic.log file (or make it writable). I'll close this duplicate ticket.
