### ISSUE TITLE
Docker Desktop crashes when switching to Windows images

### ISSUE THREAD

**Issue by activegregb** [docker/for-win#11976]
- [x] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: A0898511-B0B5-4A95-8B70-165FEBFD5E96/20210823155248

### Actual behavior

Service crashes after switching from linux containers to windows containers once I attempt to launch a windows container from within Ubuntu 20.04 on WSL1.  I'm using docker-ce 20.10.8~3-0~ubuntu-focal within the WSL1 OS.

### Expected behavior

I should be able to launch Windows images from within Ubuntu on WSL1 as long as the docker daemon on port 2375 is set for Windows.

### Information
<Please, help us understand the problem.  For instance:
  - Is it reproducible?
  - Is the problem new?
  - Did the problem appear with an update?
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.
-->

I'm launching interactive Windows docker containers from within Ubuntu 20.04 on WSL1. 

In 3.5.x, this stopped working.  Even when the service was set to Windows containers, the clients disallowed non-linux images/containers.

This appears to have been corrected in 3.6.0 and I was able to run some windows images on Friday.  Today the service crashes when I try to switch to Windows images from Linux and then attempt to use it.

  - Windows Version:
  - Docker Desktop Version: 3.6.0
  - WSL2 or Hyper-V backend?  WSL2 backend
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Set docker for desktop to use linux containers.
  2. Switch to Windows containers.
  3. Observe crash

**Comment by StefanScherer** [comment]
Thanks for the report. We track this issue in #11899 and there's a workaround to remove the panic.log file (or make it writable). I'll close this duplicate ticket.
