### ISSUE TITLE
Crash when switching to Windows containers

### ISSUE THREAD

**Issue by cabadam** [docker/for-win#11977]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 67AC50EB-958C-47CD-A7BB-7FEBE809CFE2/20210823194448

### Actual behavior

Switching from Linux to Windows containers in Docker Desktop for Windows 3.6.0 crashes.

### Expected behavior
Docker remains functional and able to launch windows containers.

### Information

  - Windows Version: 2004 (19041.1110)
  - Docker Desktop Version: 3.6.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Have docker desktop up and running in Linux mode.
  2. Verify from the command line that docker is responding (ex: docker info returns information about the server).
  3. Use the UI to switch to Windows container mode.
  4. Wait while Docker attempts to switch.  Eventually the UI crashes.
  5. Repeat the docker info command and note it now fails:
ERROR: error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/info": open //./pipe/docker_engine: The system cannot find the file specified.

**Comment by StefanScherer** [comment]
Thanks for the report. We track this issue in #11899 and there's a workaround to remove the panic.log file (or make it writable). I'll close this duplicate ticket.
