### ISSUE TITLE
switching to windows containers crashes docker desktop

### ISSUE THREAD

**Issue by ferkulat** [docker/for-win#11981]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 5C01790C-03F5-418A-B3B6-4336DD494AE6/20210824082213

### Information

  - Windows Version: Windows 10 Business 20H2 19042.1110
  - Docker Desktop Version: 3.6.0
  - Hyper-V backend  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Steps to reproduce the behavior

  1. after updating Docker Desktop to 3.6.0 it was not able to access C:\ProgramData\Docker\config\daemon.json
  2. resetting to factory defaults set it back to linux containers and WSL2
  3. creating manually directory   C:\ProgramData\Docker\config
  4. switching to windows containers made docker crash
  5. disabling WSL2 based engine did not solve it
  5. even tried with uninstalling and installing Docker Desktop 3.5.1. led to the same result

It might be that a recent windows update could also be the reason. Because Docker Desktop 3.5.1 on windows containers worked before.
But the crash happened after updating and restarting docker Desktop.

The crash report is from using Hyper-V backend, but WSL2 backend did not help. Switching to windows containers crashes.

 crash report diagnostic ID: 5C01790C-03F5-418A-B3B6-4336DD494AE6/20210824082213

**Comment by StefanScherer** [comment]
Thanks for the report. We track this issue in #11899 and there's a workaround to remove the panic.log file (or make it writable). I'll close this duplicate ticket.
