### ISSUE TITLE
Docker is giving error while switching to windows 

### ISSUE THREAD

**Issue by srinivasbanny** [docker/for-win#11985]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by elliottmatt** [comment]
Same as https://github.com/docker/for-win/issues/11987

**Comment by stephen-turner** [comment]
Resolve as dupe
