### ISSUE TITLE
Windows 10 wsl command line suddenly gives error

### ISSUE THREAD

**Issue by Thadir** [docker/for-win#1198]
### Expected behavior
docker login should give a sucses
### Actual behavior
I get an error when pulling in images or doing adocker login Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:47203->[::1]:53: read: connection refused
### Information
Updated to the newest stable. And sudenly my linux subsystem for windows connectino to docker keeps spamming: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:47203->[::1]:53: read: connection refused.

Work around to revert was going back to the previus stable build.  i sended the diagonse & Feedback but did not copy the id. If needed I can reproduce.

### Steps to reproduce the behavior

  1. Update to newest docker stable version
  2. Do a docker login on your WSL or Powershell interface.

**Comment by jlory** [comment]
Had the same issue on the latest stable version, I think the problem lies in how docker detects your DNS servers, just changing the DNS servers in the Network tab and not use automatic settings fixed the issue. At work we can't use 8.8.8.8 and I guess it's what docker is using / confused about.
