### ISSUE TITLE
docker starting screen appears for longer time and then its hsows the crash report

### ISSUE THREAD

**Issue by kesavdj** [docker/for-win#11983]
< 
[log-docker.txt](https://github.com/docker/for-win/files/7039128/log-docker.txt)
[
[log-docker.txt](https://github.com/docker/for-win/files/7039132/log-docker.txt)
](url)
Please, help us understand the problem.  For instance:
  - Is it reproducible? yes i tried installing new version too but its tops inthe "docker engine starting"
  - Is the problem new?
  - Did the problem appear with an update? no
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.
-->
  - Windows Version:Windows 10 Enterprise
  - Docker Desktop Version:3.3.3 (64133)
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
It appears that you haven't installed WSL 2 correctly, which Docker Desktop uses. Please follow Microsoft's instructions at https://aka.ms/wsl2-install. If it's set up correctly, then the command wsl -l -v should show a version 2 distro.
