### ISSUE TITLE
3.6 Appears to be Completely Broken

### ISSUE THREAD

**Issue by GLStephen** [docker/for-win#11990]
3.6 install completes but every starts fails with various messages about "Package Not Installed" and similar messaging. No amount of marking files readonly and vice versa, as mentioned here: https://github.com/docker/for-win/issues/11987, resolves it. Only resolution was to downgrade back to 3.5.2 via the release notes.

https://docs.docker.com/desktop/windows/release-notes/

I'm unsure if the resolution here would have worked, but may try and upgrade and test later: https://github.com/docker/for-win/issues/11967

**Comment by Nazarii77** [comment]
100% agree!
