### ISSUE TITLE
Docker Desktop Stuck on Docker Engine Starting

### ISSUE THREAD

**Issue by jgrunwal** [docker/for-win#11996]
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 170FE473-8D86-4EC3-A3B1-BD940341216B/20210825164137

### Actual behavior
- Docker Desktop hangs on "Docker Engine starting..." indefinitely. Unable to modify any settings or run either the Clean / Purge data tool or the Reset to factory defaults tool.

### Expected behavior
- Docker Desktop starts normally

### Information

  - Windows Version: Windows 10, version 20H2, os build 19042.1165
  - Docker Desktop Version: 3.6.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Restart PC
  2. Start Docker Desktop

**Comment by MicahBCode** [comment]
@fp-jcorriveau Not working for me. Don't even have any panic.log

**Comment by fp-jcorriveau** [comment]
@MicahBCode Does your folder C:\ProgramData\Docker have sufficient right? 
If you access the folder in a file explorer, you might have a popup 

```
[Window title]
Docker

[Main instruction]
You do not have the required permissions to access this folder.

[Content]
Click Continue to permanently access this folder.

[Continue] [Cancel]
```

You need to click `Continue` and then make sure the folder has `write` access.

Note that there is a new version of Docker Desktop (4.0) and it seems the fix the issue (for me at least)

**Comment by MicahBCode** [comment]
@fp-jcorriveau When I access the folder using Windows File Explorer no popup appears. Other than that I can see all the files and so on. I checked the rights of the folder. It's set to partly read-only like so:
![image](https://user-images.githubusercontent.com/56562388/132132206-de76bc8c-d658-4c8f-8e19-deebc3f164b6.png)
When removing that checkbox and saving the checkbox is being set back automatically when opening the rights of the folder right away again.

**Comment by blakehawkins** [comment]
I resolved for myself this by right-clicking the docker-desktop status bar menu and doing the following things:

1. Update to 4.0.0
2. Prune system data (hung forever)
3. Reset factory defaults (crashed)
4. Restarted docker desktop

**Comment by MicahBCode** [comment]
Didn't work for me @blakehawkins

**Comment by barasimumatik** [comment]
Have a look at #12369. 

Solved the problem for me at least
