### ISSUE TITLE
Failed to start VM "MobyLinuxVM", Hyper-V component not running

### ISSUE THREAD

**Issue by Kassius509** [docker/for-win#12]
### Expected behavior
MobyLinuxVM starts and allows Docker to run successfully.

### Actual behavior
Docker crashes, error states that MobyLinuxVM failed to start, because one of the Hyper-V components is not running. 
Attempted to start MobyLinuxVM in the Hyper-V manager and it failed presenting the same error. 

### Information
  - Diagnostic ID from "Diagnose & Feedback" in the menu.
B34992D5-8A0F-4444-B97E-799CE74D37C0/2016-07-29_20-17-51
  - host distribution and version (Windows version, build number, etc)
Edition: Windows 10 Pro
Version: OS Build: 10586.494
Processor: Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz 
Installed Ram: 16.0 GB
*Note: Windows is currently not activated. Would this cause the issue?*

### Steps to reproduce the behavior

  1. Install Docker for Windows
  2. Restart Computer
  3. Docker attempts to start on startup and fails.

**Comment by rneugeba** [comment]
This looks like an issue with the Hyper-V installation:
```
[20:15:27.513][NamedPipeServer][Error  ] Unable to execute Start: Failed to start VM "MobyLinuxVM": 'MobyLinuxVM' failed to start.

Failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running.

'MobyLinuxVM' failed to start. (Virtual machine ID 353F839D-6D53-4B6B-A4AB-D62F6EF1CDD9)

The Virtual Machine Management Service failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running (Virtual machine ID 353F839D-6D53-4B6B-A4AB-D62F6EF1CDD9).    at System.Management.Automation.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
[20:15:27.599][NamedPipeClient][Error  ] Unable to send Start: Failed to start VM "MobyLinuxVM": 'MobyLinuxVM' failed to start.

Failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running.

'MobyLinuxVM' failed to start. (Virtual machine ID 353F839D-6D53-4B6B-A4AB-D62F6EF1CDD9)

The Virtual Machine Management Service failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running (Virtual machine ID 353F839D-6D53-4B6B-A4AB-D62F6EF1CDD9).
```

Ah, I see you are running this in qemu and or KVM. Unfortunately, this is not a supported configuration as we have no control over the quality of support for the required nested virtualisation in either.

**Comment by Kassius509** [comment]
Thx for the info!
