### ISSUE TITLE
docker start up failing 

### ISSUE THREAD

**Issue by tommurphy6** [docker/for-win#12015]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: EF8159A1-510B-4621-BF1B-E535732CAC34/20210827123823

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by tommurphy6** [comment]
Thanks for the feedback Mike
Regards

**Comment by mathemaphysics** [comment]
I'm having similar issue. No solution yet.

**Comment by soroshsabz** [comment]
ITNOA

I have same problem with version 4.0.0

related to #12066
