### ISSUE TITLE
Failed to start with an error message

### ISSUE THREAD

**Issue by Vilican** [docker/for-win#12027]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: D7E728B6-91BF-4C9B-8461-83D28F0F1EED/20210828162020

### Actual behaviour

When starting Docker desktop, after a while in the "starting" state, an error happens.

### Information

  - Windows Version: Windows 11 (build 22000.160)
  - Docker Desktop Version: 3.6.0 (67351)
  - WSL2 or Hyper-V backend? WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behaviour

Start Docker desktop and wait.

**Comment by stephen-turner** [comment]
I think WSL 2 is not installed. Try following Microsoft's instructions at https://aka.ms/wsl2-install.
