### ISSUE TITLE
Hyper-V isolation with bind mount appears to hold unnecessary file locks on container host

### ISSUE THREAD

**Issue by nickwesselman** [docker/for-win#12028]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 953333DF-EA30-47EC-A977-EEAE6AE356DE/20210830154356

### Actual behavior
I'm seeing behavior myself and [reported by others](https://stackoverflow.com/questions/66752750/visual-studio-build-fails-while-copying-files-to-the-bin-directory-due-to-file-l) that a bind mount in a Windows container w/ Hyper-V isolation can result in files seemingly being locked by the Hyper-V VM, even though there is no process on the container which is locking them. This is definitely a change in a recent Docker (or Windows?) version update, as this worked just fine previously.

In my case running `dotnet watch` in the container, the initial build of the mounted source works. After a file change, `dotnet watch` will kill the running app, and attempt to rebuild. The subsequent builds all fail however:

> CSC : error CS2012: Cannot open 'C:\src\obj\container\Debug\net5.0\dotnet-docker-lock-issue.dll' for writing -- 'The process cannot access the file 'C:\src\obj\container\Debug\net5.0\dotnet-docker-lock-issue.dll' because it is being used by another process.' [C:\src\dotnet-docker-lock-issue.csproj]

Using sysinternals `handle`, I see no processes on the container which have locks on this path.

```
PS C:\> handle64 -accepteula C:\src\obj\

Nthandle v4.22 - Handle viewer
Copyright (C) 1997-2019 Mark Russinovich
Sysinternals - www.sysinternals.com

No matching handles found.
```

However there is a lock on the container host:

```
PS C:\> handle64.exe C:\dev\dotnet-docker-lock-issue\obj\

Nthandle v4.22 - Handle viewer
Copyright (C) 1997-2019 Mark Russinovich
Sysinternals - www.sysinternals.com

vmwp.exe           pid: 17640  type: File          35DC: C:\dev\dotnet-docker-lock-issue\obj\container\Debug\net5.0\d377a3cb-bad4-4c2d-8e66-e6a46db6ba2c_dotnet-docker-lock-issue.dll
```

Why does the Hyper-V process have this lock?

I've created a simple example which reproduces the behavior [in this repository](https://github.com/nickwesselman/dotnet-docker-lock-issue).

### Expected behavior
Killed processes in a Windows container don't continue to hold file locks.

### Information

  - Windows Version: 21H1 (OS Build 19043.985)
  - Docker Desktop Version: 3.60 (67351)
  - WSL2 or Hyper-V backend?  Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior
Documented [in this repository](https://github.com/nickwesselman/dotnet-docker-lock-issue)

**Comment by jelovac** [comment]
Hi,

I think I have the same issue.

Running latest Windows 10 + Ubuntu (WSL2) + Docker for Windows.

The directories inside Ubuntu which get bind mounted inside Docker containers become locked.

This is the message I've been getting when I try to remove them:

```
rm: cannot remove 'persistence/db_mysql': Device or resource busy
```

All running containers are stopped but files and directories are still locked.

**Comment by stephen-turner** [comment]
Thanks for the ticket, but could you please open an issue on https://github.com/moby/moby instead? The Windows container code is upstream of us, and is not maintained by Docker engineers. Sorry, I would move the ticket myself but it's not possible because it's not within the docker github org.

PS If you know which version of Docker was working, it would be interesting to roll back in order to determine whether the bug was due to a Docker engine update or a Windows update. My guess is that the latter is more likely, but it could be either.

**Comment by nickwesselman** [comment]
Moved to moby/moby#42803
