### ISSUE TITLE
Diagnostics ID: 20CFDC0A-2B55-49A1-85AD-1F1325F0A832/20210901025040

### ISSUE THREAD

**Issue by cwcoga123** [docker/for-win#12047]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:20CFDC0A-2B55-49A1-85AD-1F1325F0A832/20210901025040

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
The error message says "Hardware assisted virtualization and data execution protection must be enabled in the BIOS. See https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization". So I think that's the answer.
