### ISSUE TITLE
Reopening : Docker failed to initialize.

### ISSUE THREAD

**Issue by zachjonesnoel** [docker/for-win#12041]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:  [log.1.txt](https://github.com/docker/for-win/files/7084005/log.1.txt)

### Information

  - Windows Version: Win 10
  - Docker Desktop Version: 3.6.0
  - WSL2 or Hyper-V backend?   Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

 - Start the Docker Windows app. After a while, it shows up the pop-up. 
![image](https://user-images.githubusercontent.com/12515425/131505013-06f0d1e2-bbec-4271-9456-68d82407df6f.png)
- Tried clearing AppData and that also didn't help.

In reference to Issue [#11967](https://github.com/docker/for-win/issues/11967) and [#11711](https://github.com/docker/for-win/issues/11711), tried the solutions none of them work.

**Comment by Wyren** [comment]
Same issue here. I tried the installer and got this.
![image](https://user-images.githubusercontent.com/9673909/132012956-1f8df06f-64c2-43eb-bdfc-d1e53b911ce2.png)

**Comment by kowsalya30g** [comment]
same error here could anyone help on the above error please

**Comment by Wyren** [comment]
I uninstalled 3.60 and installed 4.0, works fine again. For those that have this option.

**Comment by zachjonesnoel** [comment]
After doing a reinstallation with v4.0 I didn't get the error but the desktop app is taking forever to load.

**Comment by kowsalya30g** [comment]
I m having 4.0 only but again why I m getting same error

**Comment by kowsalya30g** [comment]
could anyone please help me on this ?
