### ISSUE TITLE
Unable to expose Docker API on port 2375 after 4.0 upgrade

### ISSUE THREAD

**Issue by mdeggers** [docker/for-win#12043]
- [X ] I have tried with the latest version of Docker Desktop
  - [X ] I have tried disabling enabled experimental features
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID: 66079FCB-D1BC-4470-847B-FFD35462261E/20210831172636

### Actual behavior
Unable to expose Docker API on port 2375
### Expected behavior
Able to use tools like NetBeans to browse Docker images and containers on port 2375
### Information

  - Windows Version: Windows 10 Pro 19043.1165
  - Docker Desktop Version: 4.0.0 (67817)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Update from 3.6.0
  2. Accept new user agreements
  3. Restart system
  4. Warning received that API is not exposed
  5. Verified by trying to browse to that port with NetBeans 12.4
  6. Local Docker offline

**Comment by djs55** [comment]
Hi @mdeggers thanks for your report.

Could you run an elevated cmd/powershell and run the following command:
```
 netstat -baon
```
Let me know if there are any lines which mention port :2375 in the list.

**Comment by mdeggers** [comment]
> Hi @mdeggers thanks for your report.
> 
> Could you run an elevated cmd/powershell and run the following command:
> 
> ```
>  netstat -baon
> ```
> 
> Let me know if there are any lines which mention port :2375 in the list.

There was nothing on port 2375 with or without Docker desktop running, according to both netstat with an administrator shell, or TCPView.

When Docker had been running and complained about port 2375, I tried to connect to it via NetBeans. At that point there was a dangling SYN from NetBeans to port 2375 as shown by netstat / TCPView.

It looks like something has changed in netsh. The following command:

netsh interface ipv4 show excludedportrange protocol=tcp

reports the following lines (in part):

Protocol tcp Port Exclusion Ranges

| Start Port | End Port |
|------------|----------|
| 2280 | 2379 |
| 2380 | 2479 |

It appears that something has modified the excluded ports. I will try to remove the impacted port from exclusion and restart Docker. This will probably address the issue, but then it remains for me to see why my system changed.

**Comment by mdeggers** [comment]
This seems to be a local problem.

I did the following (which is dangerous)

- netcfg -d (can be dangerous)
- reboot
- netsh int ipv4 add excludedportrange protocol=tcp startport=2375 numberofports=1
- start docker

Docker now uses port 2375. This shows up in TCPMon as:

com.docker.proxy.exe	23932	TCP	127.0.0.1	2375	0.0.0.0	0	LISTENING										
com.docker.proxy.exe	23932	TCPV6	[0:0:0:0:0:0:0:1]	2375	[0:0:0:0:0:0:0:0]	0	LISTENING										

I do not know how the ports got blocked, but this is apparently a local issue and not a Docker issue. Please feel free to close this report.

I'll post on the forum first, next time.

Sorry for the noise.

**Comment by djs55** [comment]
@mdeggers thanks for getting back to us so quickly. I'm glad you've resolved your immediate problem. I'll close the ticket but feel free to open another one if you hit another problem.
