### ISSUE TITLE
Docker crashed with .net exception

### ISSUE THREAD

**Issue by Vigu84** [docker/for-win#12046]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Vigu84** [comment]
.

**Comment by Vigu84** [comment]
3E589DCE-B6A5-4716-A850-1D05FE5AB3C8/20210901000718

**Comment by stephen-turner** [comment]
It looks like WSL 2 isn't installed. Please follow Microsoft's instructions at https://aka.ms/wsl2-install

**Comment by Vigu84** [comment]
Weird as it was i stalled and docker was running well before the crash as i have ubuntu sub linux system running well too. Will check it again. I am on windows 11 beta by the way
