### ISSUE TITLE
Accessing junction-ed directory inside a --volume mount

### ISSUE THREAD

**Issue by compulim** [docker/for-win#1205]
### Expected behavior

In a Windows container, accessing junction-ed directory inside a `--volume` mount will fail with `The file cannot be accessed by the system.`

### Actual behavior

Able to traverse a junction-ed folder.

Or if that's technically impossible, please made it possible to workaround by able to run `mklink.exe` inside the container (which currently fail with "Access is Denied" or similar).

When listing the junction-ed folder inside the container, it will list the original junction on the host, i.e. something starts with `C:\`, instead of `\\?\ContainerMappedDirectories\`.

```
10/11/2017  11:44 AM    <JUNCTION>     xyz [C:\xyz]
```

### Information

In my scenario, I use `npm link` (which use directory junction on Windows) to link to a package under `node_modules`. When running in my container, Node.js failed to load files inside that package because when it traverse the junction-ed folder, it failed.

Docker version:

```
Version 17.09.0-ce-win33 (13620)
Channel: stable
8c56a3b
```

### Steps to reproduce the behavior

  1. Create a folder, namely, `C:\abc`
  2. Create another folder, namely, `C:\xyz`
  3. Inside `C:\abc`, run `mklink /J C:\xyz xyz`
  4. Run a Docker container with `--volume C:\abc:C:\abc`
  5. Start the Docker when Command Prompt
  6. Run `CD C:\abc\xyz`

It will fail with `The file cannot be accessed by the system.`

**Comment by augi** [comment]
I can confirm that I have exactly the same issue.

**Comment by hacst** [comment]
Is "Actual" and "Expected" behavior swapped in this report?

**Comment by kastnerp** [comment]
I can confirm that this is still an issue with v2.2.0.5.
