### ISSUE TITLE
Display Docker for Windows version somewhere in the UI

### ISSUE THREAD

**Issue by valentijnscholten** [docker/for-win#12051]
I have tried only Docker for Windows 3.6.0 as 4.0.0 won't start on my machine

### Actual behavior
Docker for Windows version not displayed anywhere

### Expected behavior
An easy way to check the Docker for Windows version. Some of the ways from https://stackoverflow.com/questions/60167878/how-to-check-the-docker-desktop-installed-version don't work anymore.
Feels a bit weird to go into the Windows Registry or some Powershell oneliners to find out the installed version of Docker for Windows.

### Information
  - Windows Version: Windows 10
  - Docker Desktop Version: 3.6.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Disclaimer
I looked everywhere and found similar questions using google. Still I might just be blind :-)

**Comment by stephen-turner** [comment]
It's in the About box (right-click on the whale).

**Comment by valentijnscholten** [comment]
@stephen-turner should that work on 3.6.0? The only two whales I see don't have an about box:
![image](https://user-images.githubusercontent.com/4426050/131716586-5855a461-22a5-4bcc-ae89-0c38e6a8d8e7.png)
![image](https://user-images.githubusercontent.com/4426050/131716622-890fb100-02c6-4511-84b4-a70b03cd24b7.png)

**Comment by stephen-turner** [comment]
Sorry, not that whale. I should have been explicit. The whale in the system tray.

**Comment by valentijnscholten** [comment]
omg, why didn't I look there... And why did nobody mention it on stackoverflow :-)
