### ISSUE TITLE
Restarted machine, now causes Docker not to start

### ISSUE THREAD

**Issue by lalku** [docker/for-win#12056]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
CDAB3179-FBCF-4261-94D9-2A6CC8993392/20210901220455
### Information

  - Windows Version: 10 Enterprise
  - Docker Desktop Version: 4.0.0 (67817)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Restart Windows
  2. ...

**Comment by MicahBCode** [comment]
Same problem here on Windows 10 Professional 21H1 with WSL2 and Ubuntu latest LTS version redist

**Comment by lalku** [comment]
Updated to version 4 and still will not start. Here is the Diagnostics ID after the upgrade - CDAB3179-FBCF-4261-94D9-2A6CC8993392/20210901223304

**Comment by lalku** [comment]
It runs fine when running Linux containers but fails as soon as I switch to Windows containers. New Diagnostics ID - CDAB3179-FBCF-4261-94D9-2A6CC8993392/20210901230045

**Comment by lalku** [comment]
Resetting everything back to the defaults, got it working again. Downside is you loose all your images.

**Comment by lalku** [comment]
The error is back as soon as you restart your machine, new diags id - CDAB3179-FBCF-4261-94D9-2A6CC8993392/20210903182455

**Comment by lalku** [comment]
Do NOT set a value for 'data-root' in the docker engine config. Once the value was removed, it started fine, even after reboot.

**Comment by MicahBCode** [comment]
@lalku Where to find that setting?

**Comment by lalku** [comment]
It is in the Docker Engine settings; the file is located at C:\ProgramData\Docker\config\daemon.json. Make sure there are no property for 'data-root'

**Comment by MicahBCode** [comment]
I don't even have a config folder inside the Docker folder

**Comment by lalku** [comment]
That is probably because the windows container path of docker was not able to successfully start

**Comment by MicahBCode** [comment]
@lalku I'm running on WSL2 but Windows containers didnt work either

**Comment by lalku** [comment]
> @lalku I'm running on WSL2 but Windows containers didnt work either

For me it started working after I reset the settings. But started failing as soon as I set the data-root property so I had to remove that setting to at least have a working docker until all of this can get fixed.
