### ISSUE TITLE
docker for windows 10

### ISSUE THREAD

**Issue by bjtruden** [docker/for-win#12062]
### Information

  - Windows Version: 10 Pro
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior
C:\Program : The term 'C:\Program' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

  1. ...
  2. ...

**Comment by bjtruden** [comment]
I don't know wich is the solution.

**Comment by olivierchatry** [comment]
You need to put the command between double quote : `"C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe"`, this should help.
