### ISSUE TITLE
Error After restart the system. "Time out has expired and the operation has not been completed"

### ISSUE THREAD

**Issue by Avinchandsanaya** [docker/for-win#12064]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Avinchandsanaya** [comment]
![image](https://user-images.githubusercontent.com/84490702/131798486-2151f711-15be-4af9-b433-f62556c2ae68.png)

**Comment by soroshsabz** [comment]
ITNOA

I have the same issue

related to #12066

**Comment by soroshsabz** [comment]
How to resolve this issue?
