### ISSUE TITLE
Docker restart on a windows container fails 

### ISSUE THREAD

**Issue by ankgupta067** [docker/for-win#1206]
### Expected behavior
docker restart should start the container 
### Actual behavior
i get below  error when i do so

Error response from daemon: Cannot restart container happy_mclean: container e72d79c348dda75d17b9d1805049a4338c67fd5b53a2bf1427db88ad526c3351 encountered an error during CreateContainer: failure in a Windows system call: The handle is invalid. (0x6)
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. create a container like below- 
 docker run -itd microsoft/aspnetcore
  2. attach to container -
docker attach  happy_mclean

3. perform some operations and exit.

4. try to restart same container-
docker restart  happy_mclean

and i get above error as mentioned.

**Comment by jasonbivins** [comment]
Hi @ankgupta067 
I was able to reproduce this using both the container name and ID - I'll go ahead and report it internally.


Thanks!
