### ISSUE TITLE
Installing update to Docker Desktop 4.0 fails due to issues with WSL integration

### ISSUE THREAD

**Issue by jankenr** [docker/for-win#12076]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 61DAA879-BE2C-4A81-9F7F-A8498C36E68E/20210903125604
  

### Information

  - Windows Version: 10 PRO 20H2
  - Docker Desktop Version: 4.0.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Start upgrading via context menu from Docker Desktop 3.6.0
  2. At one moment the error will pop up
    **Docker Desktop - Ubuntu**
    _WSL integration with distro Ubuntu unexpectedly stopped with exit code 1. Do you want to restart?

Restarting does not help and will throw the exact same error

**Comment by igorovic** [comment]
Same issue for me.

**Comment by m1stermanager** [comment]
same issue here

**Comment by igorovic** [comment]
I was able to make it work following these steps:

Remove all content in:
- C:\Users\igorovic\AppData\Local\Docker\
- C:\Users\igorovic\AppData\Roaming\Docker\

Then re-install Docker desktop

**Comment by soroshsabz** [comment]
ITNOA

@igorovic I try to remove all content in `%appdata%` (Docker Desktop, docker)

related to #12066

**Comment by m1stermanager** [comment]
i had to uninstall/reinstall ubuntu to get this back on track. i'm not sure what, but something was screwed up somewhere along the lines. 

one thing I did notice, even after everything was crashed, was that in windows, if i did a `docker ps` I could see a docker-compose service running that I only had ever run from within WSL/ubuntu.... I never even cloned that repository in windows... I don't know if something was just totally messed up at the docker-compose level and it was crashing docker for me
