### ISSUE TITLE
Docker-Desktop for windows10  start  error

### ISSUE THREAD

**Issue by lnetx** [docker/for-win#12089]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:2004
  - Docker Desktop Version:4.0.0
  - WSL2 or Hyper-V backend?   wsl2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by soroshsabz** [comment]
ITNOA

I have similar problem in another windows version

related to #12066
