### ISSUE TITLE
Docker fail to initialize 

### ISSUE THREAD

**Issue by omengxiang** [docker/for-win#12087]
Version: 4.0.0 (67817)
Sha1: b4ba07e5012ed59fa9cd29eed856660d42b80859
Started on: 2021/09/06 11:43:27.941
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 2009
Build: 19043
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\Users\xinggui\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[11:43:28.089][GUI               ][Info   ] Starting...
[11:43:28.459][GUI               ][Info   ] An instance is already running. Launching the container view.
[11:43:28.549][GUI               ][Warning] Launching the dashboard failed: 操作已超时。
[11:43:28.555][GUI               ][Error  ] System.Exception:
Docker Desktop is shutting down.
   在 Docker.Program.Run(IReadOnlyCollection`1 args) 位置 C:\workspaces\PR-16319\src\github.com\docker\pinata\win\src\Docker.Desktop\Program.cs:行号 216
![无标题](https://user-images.githubusercontent.com/12413056/132158402-67fb6697-607c-42eb-bcd7-3debf80e1730.png)

**Comment by IosifZ** [comment]
Yesterday I wanted to give 4.0 a change. So I've upgraded from 2.4.0 ending up with the same message. So 3.5.2 brought a 12 minutes delay after reboot of the PC, and stating 3.6 I am not able to use any other newer version. Is anyone paying attention to all these issues?

**Comment by wookiehangover** [comment]
I think I found a fix to this: when I tailed `AppData/Local/Docker/log.txt` during startup, I saw a JSON parse exception for `AppData/Roaming/Docker/locked-directories`. I checked that file and it was, in fact, not a valid JSON file. Replacing the contents of that file with and empty object `{}` allowed docker desktop (v4) to start. Hope this helps.

**Comment by stefaneidelloth** [comment]
The comment of wookiehangover  helped me to find the error message

[15:35:46.982][GoBackendProcess  ][Fatal  ] msg="while parsing JSON from C:\\Users\\projekt-la-eis\\AppData\\Roaming\\Docker\\settings.json: json: cannot unmarshal bool into Go struct field Content.proxyHttpMode of type string"

I adapted settings.json by removing the line that contains "proxyHttpMode"
=> Docker was able to start

**Comment by omengxiang** [comment]
只能采用最笨的办法解决这个问题了：
1. 备份好历史环境如下：
C:\Users\xinggui\.docker
C:\Users\xinggui\AppData\Local\Docker
C:\Users\xinggui\AppData\Roaming\Docker
C:\Users\xinggui\AppData\Roaming\Docker Desktop
2. 卸载Docker
3. 重新安装Docker
4. 替换历史环境，问题解决。

**Comment by omengxiang** [comment]
> Yesterday I wanted to give 4.0 a chance. So I've upgraded from 2.4.0 ending up with the same message. So 3.5.2 brought a 12 minutes delay after reboot of the PC, and stating with 3.6 I am not able to use any other newer version. Of course that I've uninstalled each version before installing a new one. Is anyone paying attention to all these issues?

我遇到的问题跟你的一模一样，现在只能卸载了重新安装。
