### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by aleparedes28** [docker/for-win#12092]
- [ x ] I have tried with the latest version of Docker Desktop
  - [ x  ] I have tried disabling enabled experimental features
  - [  x ] I have uploaded Diagnostics
  - Diagnostics ID:
  - C8ABCEB7-8598-4137-AF61-2B0BB4250BCF/20210907002421

### Information

  - Windows Version: Windows 10
  - Docker Desktop Version: The newest
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: VM

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by DaleyKD** [comment]
Not sure if this will help or not: https://stackoverflow.com/questions/39684974/docker-for-windows-error-hardware-assisted-virtualization-and-data-execution-p
