### ISSUE TITLE
Docker failed to initialize

### ISSUE THREAD

**Issue by sSNMDSs** [docker/for-win#12100]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by sSNMDSs** [comment]
Diagnostics ID: 996F528D-B07D-466F-91D7-E040F561C60F/20210907232059

**Comment by soroshsabz** [comment]
ITNOA

I have the same problem

related to #12066
