### ISSUE TITLE
Dashboard system tray icon looks blurry

### ISSUE THREAD

**Issue by abarani** [docker/for-win#12104]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: -

Dashboard system tray icon becomes blurry after switching monitors that use different DPI scaling.

### Actual behavior

![docker-systray-icon-blurry](https://user-images.githubusercontent.com/2650264/132488419-9aabf4e5-3078-4cd9-b9b5-f52ac4a20c42.png)

### Expected behavior

![docker-systray-icon-expected](https://user-images.githubusercontent.com/2650264/132488941-e242d7c5-28cc-4fa1-8520-7f7f8f140b0b.png)

### Information

  - Windows Version: Windows 10 21H1 (19043.1165)
  - Docker Desktop Version: 4.0.0 (67817)
  - WSL2 or Hyper-V backend? -
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: -

### Steps to reproduce the behavior

  1. Start Docker Desktop
  2. Change Windows DPI scaling from eg 250% to 100% and back to 250%

**Comment by SmallhillCZ** [comment]
At least you have some icon, mine disappeared completely with 4.0.0 ;)

**Comment by abarani** [comment]
/remove-lifecycle stale

Issue is still present in version 4.3.1.

**Comment by StefanScherer** [comment]
Thanks for the report @abarani, we are aware of this and we plan to have it fixed in 4.4.0.
