### ISSUE TITLE
Error while pulling hello-world image from WIndows Docker

### ISSUE THREAD

**Issue by DhruboB** [docker/for-win#1210]
### Expected behavior
Image should be pulled successfully for further running the same.
### Actual behavior
Throwing Error

### Information
System Win 10 64 bit
Docker version 17.09.0-ce, build afdb6d4
Date 13-Oct-17 

>docker pull hello-world
Using default tag: latest
latest: Pulling from library/hello-world
bce2fbc256ea: Extracting [==================================================>]  252.7MB/252.7MB
b0b5e40cb939: Download complete
87377cdc7dd1: Download complete
7d840042f15f: Download complete
**failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage C:\ProgramData\Docker\windowsfilter\5e3829b00802b5c9f7cd52a83af2b1b7e5e098562a343525f0e0e4a3459a9f28\UtilityVM: The process cannot access the file because it is being used by another process.**

### Steps to reproduce the behavior

  1. Install Windows Docker in Win 10 64 bit system
  2. run Docker
  3. trigger docker pull hell-world command

**Comment by jasonbivins** [comment]
Hi @DhruboB 
Do you have any AV utilities, or backup software running that could be scanning the ProgramData\Docker\WindowsFilter folder ?   This location is where Windows images are downloaded and unpacked to.
