### ISSUE TITLE
DD0012 network checks failed: failed to ping host: exit status 1

### ISSUE THREAD

**Issue by flybyray** [docker/for-win#12113]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D3430A1E-A72A-4D6D-B7FF-B7C4510A9463/20210910113410

### Actual behavior

```
[FAIL] DD0012: is the VM networking working? network checks failed: failed to ping host: exit status 1
```

### Expected behavior

```
[PASS] DD0012: is the VM networking working? 
```

### Information

  - Windows Version: 10.0.19043.1202
  - Docker Desktop Version: 4.0.0 (67817)
  - WSL2 or Hyper-V backend?  : WSL2 
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Steps to reproduce the behavior

  1. Install docker
  2. open powershell run `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

**Comment by jpruiz114** [comment]
Any updates on this?

**Comment by flybyray** [comment]
Oh sorry missed that. I would close this. I had detected an issue with DNS from ISP ( especially with a private registry ). After consulting ISP support documents i found how to fix it.
