### ISSUE TITLE
Crash when restarting after upgrade to version 4

### ISSUE THREAD

**Issue by ManfredLange** [docker/for-win#12115]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BD5A15A8-2B44-443D-91BC-C2B67188BF92/20210911121742

### Actual behavior

Docker Desktop crashes when restarting after upgrading to version 4.0.0.

### Expected behavior

No crash, of course.

### Information

  - Windows Version: 10
  - Docker Desktop Version: 4.0.0 (67817)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Steps to reproduce the behavior

  1. ...
  2. ...

### Further notes

I then uninstalled version 4.0.0 and installed 3.6.0 again. At the moment this is just showing "Docker Engineering Starting..." without finishing. I don't know yet, what version 4.0.0 did to break an older version, too. I'll investiget further in the next few days. At the moment version 4.0.0 feels as if it's again one of the botched versions...

**Comment by jneal-afs** [comment]
Same issue. Upgraded this morning and Docker now says "Docker Engine Starting..." indefinitely even after resetting to factory defaults.

**Comment by BraINstinct0** [comment]
Same issue here on Windows 11 Build 22000.18x.

**Comment by jneal-afs** [comment]
Okay, I completely uninstalled Docker, restarted Windows, and then installed it again (same v4 67817 build) and now it works for me 🤷‍♂️

**Comment by BraINstinct0** [comment]
Will try and report.

**Comment by ManfredLange** [comment]
Solved with the steps suggested by Jason ( @jneal-afs ) which are:

1. Uninstall any Docker Desktop for Windows version you may have
2. Reboot your computer
3. Install the desired version, e.g. Docker Desktop for Windows version 4.0.0 which is the latest as of writing

As a side note: The automated update feature of Docker Desktop for Wndows at present doesn't appear to work reliably -or- the user experience in how it is presented is not yet where it probably should be to be seamless. Even if it requires a reboot, if that was indicated in the notice before the install/upgrade starts, that'd be fine. As a developer I can then decide at what time I want to apply the update. It looks as if a little more work is required to get the upgrade experience ironed out.

**Comment by soroshsabz** [comment]
@ManfredLange  my problem is not resolved with reinstalling Docker

related to #12066
