### ISSUE TITLE
Docker Desktop 4.0.0 fails to start after install on Windows 11

### ISSUE THREAD

**Issue by BraINstinct0** [docker/for-win#12116]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A3106AFD-A692-4681-AE56-E18D63A12004/20210911140206

### Actual behavior
After installing the 4.0.0 version, trying to start Docker desktop  fails.
![image](https://user-images.githubusercontent.com/29201475/132950908-35f462d2-25ea-4d65-b150-213fccbc4846.png)

### Expected behavior
Successful deployment.
### Information

  - Windows Version: Windows 11 Home 21H2 22000.184 Windows Experience Pack 1000.22000.184.0
  - Docker Desktop Version: 4.0.0
  - WSL2 or Hyper-V backend?: WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Install Docker Desktop 4.0.0
  2. Try running Docker Desktop.

**Comment by ManfredLange** [comment]
I don't have Windows 11 just yet but perhaps the approach that solved this issue on Windows 10 may work for Windows 11 as well. For more details have a look at it here: https://github.com/docker/for-win/issues/12115

**Comment by BraINstinct0** [comment]
Oddly enough, that approach worked flawlessly for me too.
Thx for the pointers, Closing this issue.

Summary for future viewers:  a Complete uninstall, reboot, and a clean install may solve the issue, even on Windows 11.
