### ISSUE TITLE
Docker Desktop Not Working

### ISSUE THREAD

**Issue by suleymanyalcin** [docker/for-win#12123]
Docker Desktop Not Working 4.0.0.0

  - [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by soroshsabz** [comment]
ITNOA

I have the same problem

related to #12066
