### ISSUE TITLE
Issue with Docker : Crashes when tried starting

### ISSUE THREAD

**Issue by azeezullah002** [docker/for-win#12120]
![image](https://user-images.githubusercontent.com/33311660/132990113-036e34df-bb10-4220-b1d9-d3dd0718359d.png)

[log.txt](https://github.com/docker/for-win/files/7149661/log.txt)

  - [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by soroshsabz** [comment]
ITNOA

I have the same problem

related to #12066 
related to #12158
