### ISSUE TITLE
Docker Desktop 3.6.0/4.0.0 fails to start

### ISSUE THREAD

**Issue by ksh7393** [docker/for-win#12133]
- [X ] I have tried with the latest version of Docker Desktop
  - [X ] I have tried disabling enabled experimental features
  - [X ] I have uploaded Diagnostics
  - Diagnostics ID:A2ACAEB9-4CC7-4159-881F-AFAB196FC649/20210914061608

### Actual behavior
Docker failed to start

### Expected behavior
Docker should start without errors
### Information

  - Windows Version: WIndows 10 (Version 20H2, OS Build 19042.1165)
  - Docker Desktop Version:3.6.0 and 4.0.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Start Docker Desktop after installation

**Comment by soroshsabz** [comment]
ITNOA

I have the same problem

related to #12066

**Comment by ksh7393** [comment]
@soroshsabz Did you get any solution working?

**Comment by soroshsabz** [comment]
@ksh7393 No I don't have any solution. :(

**Comment by soroshsabz** [comment]
I have one solution in #12066
