### ISSUE TITLE
Docker startup issue- Docker engine failed to start

### ISSUE THREAD

**Issue by vjha010** [docker/for-win#12131]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A5C5CDDE-E3E6-4237-8EC2-2034178C146A/20210914045857
 

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by soroshsabz** [comment]
ITNOA

I have the same problem

related to #12066 
related to #12158
