### ISSUE TITLE
Docker Desktop crashed unexpectedly.

### ISSUE THREAD

**Issue by theshubh77** [docker/for-win#12138]
### Steps to reproduce the behavior

 1. I just opened Docker Desktop and it crashed. I've also submitted a crash report.

**Comment by soroshsabz** [comment]
ITNOA

I have same problem

related to #12066 
related to #12158

**Comment by theshubh77** [comment]
> ITNOA
> 
> I have same problem
> 
> related to #12066
> related to #12158

It solved for me by disabling "Use legacy console" option in windows command prompt.

**Comment by soroshsabz** [comment]
@theshubh77 I check this option for me, but my option is uncheck, and Docker Desktop still not working and failed on start.
