### ISSUE TITLE
Very slow/frozen communication/upload when using the “external” Docker host IP from within the Docker Host with WINDOWS CONTAINERS

### ISSUE THREAD

**Issue by CESARDELATORRE** [docker/for-win#1214]
### .NET Framework code for repro on a WINDOWS CONTAINER
Code for repro available at this Github repo:
https://github.com/CESARDELATORRE/PoCSlowUploadFilesWinContainer

### Expected behavior
Communication/upload should be pretty similar in performance when using the internal container IP compared to using the external Docker Host IP, when running the app's in a browser from within the Docker Host machine.

### Actual behavior
a. If using the Windows Container IP, performance is right
b. If using the Docker Host IP remotely, with a browser from a remote client machine, performance is right
c. BUG: If using the Docker Host IP with a browser from within the Docker Host (Windows 10 with Windows Containers), there's a bug in networking which causes upload communication to be very slow or even freeze..

### REPRO STEPS
Using Windows 10 and Visual Studio 2017 15.3 or later. VS is not really needed but shows, when debugging, that communication is not reaching the Web API controller (Or taking too long).

Successful execution when using the internal Windows Container IP
1.	Open solution 
2.	Set a breakpoint at HomController::UploadImage() like here:
![image](https://user-images.githubusercontent.com/1712635/31630196-cbcf3d80-b26a-11e7-9aec-931d9d5866f3.png)
3.	Run with F5
4.	Running the app with the Windows Container’s IP (used by default by Visual Studio), click on “Upload Image”, select the large image named “CESARDL_Blog_Header.png”. Then, hit “Open”.
![image](https://user-images.githubusercontent.com/1712635/31630236-e6661790-b26a-11e7-939d-69f824dfc058.png)
5.	You’ll see that you get into the breakpoint immediately, and you run the code with no issues:
![image](https://user-images.githubusercontent.com/1712635/31630257-ef0036c4-b26a-11e7-832a-929851de6507.png)
6.	Continue the execution. Everything runs fast as expected.

**ISSUE: Very slow/frozen communication/upload when using the “external” Docker host IP from within the Docker Host with WINDOWS CONTAINERS**

1.	Instead of using the internal Windows Container, you want to use the external Docker host IP. You can configure that by mapping the internal Windows Container’s port to and external Docker host’s port in the external network (specified at the docker-compose.override.yml file):

![image](https://user-images.githubusercontent.com/1712635/31630301-108e6694-b26b-11e7-9a00-d4d49be971d2.png)

2.	Therefore, if you do an ipconfig, you can see your network adapter IP, in my case “10.121.122.162” 
![image](https://user-images.githubusercontent.com/1712635/31630317-1c914740-b26b-11e7-9fc2-fd9e283ef237.png)

3.	 Now, I can run the app through the machine’s (Docker Host) IP:
![image](https://user-images.githubusercontent.com/1712635/31630343-2debcb5a-b26b-11e7-9856-a912f2679eef.png)
OK, the app is running now through the machine’s network adapter IP...

4.	If I upload the light image (“NETLogo.jpg”), it goes OK and takes less than half second to upload the image and get to the breakpoint.

![image](https://user-images.githubusercontent.com/1712635/31630419-6297e24e-b26b-11e7-971a-9fb5c27fb454.png)

It takes just less than half second to get to the breakpoint:
![image](https://user-images.githubusercontent.com/1712635/31630436-6d8f0704-b26b-11e7-9944-4ae3b447ef89.png)

5.	**ISSUE/BUG**: However, if I select to upload the heavier image “CESARDL_Blog_Header.png” (148KB, which is NOT so big...), then it takes “forever” and looks like a BUG:
a.	Refresh the Browser page
b.	Upload image by clicking on the button, but this time select the “CESARDL_Blog_Header.png” image

![image](https://user-images.githubusercontent.com/1712635/31630483-8e62560c-b26b-11e7-8649-55a3a99b3c63.png)

THE EXECUTION NEVER REACHES THE BREAKPOINT. 
At this point, I stopped after it reached 15 minutes of waiting...

IMPORTANT NOTE: It looks like this is an issue with the internal networking at the Docker Host when running the app in the browser from within the Docker Host, because if I run the application from a remote machine's browser, through the same real IP of the network adapter previously used, then the app works OK and runs fast when uploading the image.

**Comment by friism** [comment]
cc @jmesser81 @kallie_b  - I think this might be a limitation with the implementation in Windows, but not sure

**Comment by JMesser81** [comment]
Please note that the Docker for Windows network datapath goes through VPNKit maintained by @rn. I do not believe VPNKit uses WinNAT (Windows platform component) but I could be wrong. Not sure how host communication works with VPNKit

**Comment by friism** [comment]
@JMesser81 vpnkit is not in the datapath for Windows containers.

**Comment by JMesser81** [comment]
@friism - ah, thanks for clarifying. I thought this was a Linux container. We do have another issue (https://github.com/moby/moby/issues/34355 ) which may be related. I'm checking...

**Comment by rogersillito** [comment]
I'm seeing what looks like the same issue, although downloading is the issue in my case.   This is a blocking issue for me, as I need to host containers on the same machine that hosts a web server those containers need to access:

### Steps to reproduce: 
1. On the host, install [http-server](https://www.npmjs.com/package/http-server#installing-globally) via npm.
2. copy 3 files of increasing size (3KB, 10KB, 90KB) into a directory, and execute `http-server` in that directory on the host.
3. note the base url http-server creates
4. in a powershell session on the host run: 
   `get-date ; Invoke-WebRequest -Method Get -Uri http://192.168.0.1:8080/small.png -OutFile .\deleteme.tmp ; get-date` 
   _(substituting the ip/port http-server is running on - and, for each file, the name of the files copied in step 2)_:
   * each file downloads almost immediately
5. run the same commands in a powershell session running in a container _within a different host_ (I had to open a port on the firewall):
   * each file downloads almost immediately
6. run the same commands in a powershell session running in the container **within the same host**:
   * the 3KB file downloads with a slight delay, the 10KB file downloads within 2-3 seconds, **the 90KB file downloads very slowly/stalls**

I've replicated the issue on two separate host/container OS combinations with similar for requests across and within hosts:

* Host = 10.0.17134.1 (windows 10), Container = 10.0.17134 (nanoserver)
* Host = 10.0.16299.492 (windows 10), Container = 10.0.16299.192 (windows server core)

**Comment by richardgavel** [comment]
@rogersillito Has a very similar situation to mine. I have Windows Docker containers hosting IIS which are supposed to hit a SQL Server running on the host. I created some powershell to run a basic SQL command on the database. It runs in 5ms on the host (using localhost). But run from within the container, using host.docker.internal, it takes so longer it even hits timeouts.

The weird thing is, it only hits this situation when I try and hit resources ON the container host. If I hit a SQL Server NOT on the host, then performance is the same from the host and from within the container.
