### ISSUE TITLE
Cannot stop Docker Compose application. Reason: Error invoking remote method 'compose-action': Error: spawn C:\Windows\system32\cmd.exe ENOENT

### ISSUE THREAD

**Issue by yooakim** [docker/for-win#12155]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 8B2EA6F7-4A97-48C4-9FB6-3E355C996E1E/20210916130539

### Actual behavior

When I try to stop the application started via Docker Compose I the the error:

```
Cannot stop Docker Compose application. Reason: Error invoking remote method 'compose-action': Error: spawn C:\Windows\system32\cmd.exe ENOENT
```

Here's a screen recording:
![docker-desktop-issue](https://user-images.githubusercontent.com/862546/133618045-9584cfb5-dc3f-4d36-bf12-cf904a0a5a66.gif)

### Expected behavior
I expected the app to be stopped.

### Information

The app was created from the [appwrite.io](https://appwrite.io/) getting started guide. 

  - Windows Version: 10.0.22000
  - Docker Desktop Version: 4.0.1
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

**Comment by mozaffari** [comment]
same

**Comment by bmadzinski** [comment]
I had that same problem and the fix was:
1. restart each docker container (I did this using CLI).
`docker container ls -a`
`docker container restart <container_id>`
1. After that check if all of them are running, if not log ones that exited.
`docker container logs <container_id>`
1. Look for some errors, in my case there was one config file missing.

**Comment by FwZtheone** [comment]
Hello, i've had the same when i changed the name folder where was my docker-compose. i had to change the old name folder

**Comment by levi956** [comment]
how do you restart the server again? I tried to restart the server, but that error occurs

**Comment by islamov-ildar** [comment]
@levi956 I run "docker-compose start" from dir where has appwrite folder. Try Quit Docker Desktop (in Windows), and then try run/stop server.
![image](https://user-images.githubusercontent.com/39472576/161838197-18992cd9-45a9-4586-b09b-23ff6691b816.png)

**Comment by arnay07** [comment]
Thank you it worked for me. All you have to do is go inside `appwrite` directory and `docker-compose start` to start or `docker-compose stop` to stop
