### ISSUE TITLE
Error: Firewall blocking Docker drive sharing

### ISSUE THREAD

**Issue by TuomoLi** [docker/for-win#1215]
Expected behavior
Tried to share C-drive

Actual behavior
No matter if I try via Powershell or Docker's Shared Drives menu, I get the same error: firewall blocks file sharing.

Information
A diagnostic was uploaded with id: D273EFE0-4C6A-4558-8B65-7F2C252217C8/2017-10-17_13-43-27

I have tried uninstalling and reinstalling file sharing for Docker's NIC. Also tried disabling all firewalls (windows & Symantec) running on the computer as well as creating firewall rules to allow file sharing and traffic between 10.0.75.1 and .2 and port 445.

**Comment by jasonbivins** [comment]
Hi @TuomoLi 
There are a couple of things you can try here: https://success.docker.com/article/Error-_A_firewall_is_blocking_file_sharing_between_Windows_and_the_containers
