### ISSUE TITLE
Docker Desktop will not start after auto-upgrade from 3.3.2 to 4.0.1

### ISSUE THREAD

**Issue by jkcraig** [docker/for-win#12160]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:  BE3D6C5D-D72D-4F52-BE96-7B049E4F3666/20210918020055

### Actual behavior
After starting Docker Desktop with Administrative privileges, the icon appears in the system tray for several seconds, then disappears.
### Expected behavior
Docker Desktop should start without error.
### Information

  - Windows Version:  Windows 10 Version 20H2 (OS Build 19042.1237)
  - Docker Desktop Version:  4.0.1
  - WSL2 or Hyper-V backend?  WSL 2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:  no

### Steps to reproduce the behavior

  1. Start Docker Desktop
  2. Docker icon temporarily shows in system tray, then disappears.  Log file attached

[log.txt](https://github.com/docker/for-win/files/7189026/log.txt)

**Comment by longqua69** [comment]
Hi @jkcraig ,

I used to have the same error and resolved it by this way: #11822
Hope it can help.
