### ISSUE TITLE
Docker desktop versions 4.0.1 to 3.5.1 fail to start on desktop restart.

### ISSUE THREAD

**Issue by aravindanvenkataraju** [docker/for-win#12168]
Docker Desktop was not starting up on windows start-up. I've downgraded the versions from 4.0.1 all the way back to 3.5.1 and all these versions have the same error on start-up. 

After, I go to Troubleshoot -> Clean/Purge Data -> select WSL 2 -> Delete; Then, the service starts running.

I have to repeat this every time after I start desktop.

  - [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: - The screen shows Diagnose failed.

### Actual behavior
Docker Desktop service did not start.
### Expected behavior
Docker Desktop has to start-up successfully 

### Information

  - Windows Version: Microsoft Windows 11 Home Insider Preview - Version - 10.0.22458 Build 22458
  - Docker Desktop Version: 4.0.1 to 3.5.1 (I have not checked older versions). The log files I am attaching are for version 3.5.1
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Double Click Docker Desktop after windows startup
  2. Dashboard shows error : "Docker Engine Stopped"
  3. Click Troubleshoot-> Clean/Purge Data -> select WSL 2 -> Delete, then go to dashboard:
  4. Service is running.
 
Log file from <user>\AppData\Local\Docker\log.txt
[log.txt](https://github.com/docker/for-win/files/7193054/log.txt)

**Comment by ahiggins1039** [comment]
This also happens to me since Windows 11 update.

I have to do a reinstall Docker, every time.

I'm using Docker 4.1.0 (68531)
