### ISSUE TITLE
Fails on startup - Win11 - Docker 4 - WSL2

### ISSUE THREAD

**Issue by deflektor** [docker/for-win#12167]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D390E642-5E37-4B83-B2E1-1B4D71985CE3/20210919154600

### Actual behavior
Startup - renders after waiting long time period with an error - after latest 2 updates.
### Expected behavior
Startup - no additional steps necessary
### Information
Problem is new after latest update. No dockerfile is started, only service
  - Windows Version: 10.0.22000
  - Docker Desktop Version: 4.0.1
  - WSL2  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. Cold start pc
  2. autostart service docker

**Comment by BinarySwami-10** [comment]
hello i also faced same issues , seems like your docker installation has entered invalid state . to resolve most problems for docker on windows which prevent docker from starting i have made scripts which do config reset, have you checked my latest pull request from my fork? try running those scripts and tell if problem is solved or persists. thank you.
