### ISSUE TITLE
Docker Desktop Crash on start up

### ISSUE THREAD

**Issue by DeNuwe007** [docker/for-win#12176]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 624E9A9F-2FC0-4488-80C6-AFAC2FD77A7C/20210921120430

### Actual behavior
Docker Desktop Crash on start up

### Expected behavior
Docker Desktop should start

### Information

  - Windows Version: Windows 10 Pro (19043)
  - Docker Desktop Version: Latest
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Start Docker Desktop

**Comment by BinarySwami-10** [comment]
hello i also faced same issues , seems like your docker installation has entered invalid state . to resolve most problems for docker on windows which prevent docker from starting i have made scripts which do config reset, have you checked my latest pull request from my fork? try running those scripts and tell if problem is solved or persists. thank you.
