### ISSUE TITLE
Image tag text gets truncated on container list window

### ISSUE THREAD

**Issue by mjamro** [docker/for-win#12185]
### Actual behavior

In the Docker desktop app on "Container list" window contains information about containers with name of the image next to the name of the container. The name of the image gets truncated, even if there is enough space to fill it.

### Expected behavior

Tag of image is displayed correctly when there is enough empty space for it.

### Information

![image](https://user-images.githubusercontent.com/1384600/134464612-38449e23-fc9f-4fbc-b2aa-3ff739e0c857.png)

### Steps to reproduce the behavior

Create a container from an image with a log tag name.

**Comment by gregsdennis** [comment]
This also happens on the image details screen

![image](https://user-images.githubusercontent.com/2676804/150030333-00ed6133-7d2a-4feb-ba8b-f02333508007.png)

And there's no hover support.  There's no way that I can select or copy the image name.
