### ISSUE TITLE
Bug: "Update ready to download" prompt continues to show daily after accepting via "Download update"

### ISSUE THREAD

**Issue by NickCraver** [docker/for-win#12188]
While having Docker 4.0.0 installed (Windows 10 and 11 - I've seen it on both), I was repeatedly prompted with this to update to 4.0.1:
![image](https://user-images.githubusercontent.com/454813/134499992-9919407b-01d4-4d3c-993e-7d761dd04c89.png)

I didn't dismiss the update, I selected "Download update", but the prompt always returned the next day. It _looks_ like the daily upgrade prompt didn't care that it was queued perhaps.

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 58974218-8DF6-46EE-BBC3-DBC315700DBE/20210923113308

### Actual behavior

"Download update" was selected and prompt disappeared (though sometimes this was delayed 5-30 seconds). The next morning, and every one after, prompt was presented again, identically. After a week or so I gave up and did the update (not just download) via the system tray (successfully):

![image](https://user-images.githubusercontent.com/454813/134500425-9e93572a-d620-463f-aa4a-eda368caa260.png)

### Expected behavior

When download is selected, prompt disappears and download proceeds...and maybe even prompts me to do the install right then (it should be clearer that it's restarting *Docker* and not *your computer* in the wording. In any case, I wouldn't expect the same prompt daily as if I've taken no action.

Side notes in diagnosing this:
- There's no version indicator I can find in the main Dashboard UI - it seems to _only_ be available in the system tray -> About.
- There's no indicator an upgrade is desired in the main Dashboard UI - again this seems to only be present in the system tray icon and presence of the "Update and restart" option in the right click menu (again, "Update and restart Docker" would be MUCH clearer here and lower the bar).
  - There's a lot of confusion verbiage around this in the main UI as well (I know this is a software bug and that's a product decision, but still reporting it as a friction point): for example there's an "Upgrade" button, always, to a Team plan. There's an upgrade button under the name dropdown. But there's no "Update" indicator...and usages of both these words when really pushing the product upgrade is confusing. Given one of the stated goals of all the prompts is to have users upgrade and not support older versions...this friction matters and is going against the goals, so reporting it here.

### Information
  - Windows Version: Windows 11 (22000.184)
  - Docker Desktop Version: 4.0.0 (upgrading to 4.0.1)
  - WSL2 or Hyper-V backend?: WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Nope, physical machine

### Steps to reproduce the behavior
Unfortunately I don't have repro steps here as it's not a user-initiated action. I hope the attached diagnostic logs have some info to help this. If not, and I see this again on the next upgrade, I'd appreciate what steps if any I can help perform or data I can help capture to find the cause. Happy to help.

Y'all are building an awesome thing, I'm only reporting some friction points to help make it better.

**Comment by StefanScherer** [comment]
Thanks @NickCraver for the diagnostics. I'll have a look to find out what caused this problem on Windows.

**Comment by StefanScherer** [comment]
Thanks, the logs are very helpful to understand how we can improve the update process.

And yes, the delay of 5-30 seconds before the popup closes is another bug. We're looking into this as well.

**Comment by trungutt** [comment]
We found a way to reproduce this bug on our side and we'll try to include a fix for next release

**Comment by joe0BAB** [comment]
Please try version 4.2.0 which should fix the problem. Feel free to reopen if the problem still occurs.
