### ISSUE TITLE
Report an issue

### ISSUE THREAD

**Issue by GiovanyAngel** [docker/for-win#12189]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by GiovanyAngel** [comment]
error

**Comment by BinarySwami-10** [comment]
hello i also faced same issues , to resolve most problems for docker on windows which prevent docker from starting i have made scripts, have you checked my latest pull request from my fork? try running those scripts and tell if problem is solved or persists. thank you.
