### ISSUE TITLE
Docker Compose should not default to v2 when Desktop is in Windows containers mode

### ISSUE THREAD

**Issue by karolz-ms** [docker/for-win#12196]
Since Compose v2 does not support Windows containers (as of today), Docker Desktop should not default to ("translate") invocations of `docker-compose` into Compose v2 (`docker compose`) when Docker Desktop is running in Windows containers mode.

This was discussed with @nebuk89 
@bigmorty @chuxel FYI

**Comment by BigMorty** [comment]
We still want to get this change in please.

/remove-lifecycle stale

**Comment by mat007** [comment]
I think this was [implemented](https://github.com/docker/compose/pull/8818) and released in [Desktop 4.1.1](https://docs.docker.com/desktop/windows/release-notes/#upgrades-3): in Windows container mode Desktop is supposed to always fall back to Compose V1.

**Comment by karolz-ms** [comment]
Yep, thanks for doing the change and [verifying that it solves the issue]( https://github.com/docker/compose/pull/8818#pullrequestreview-789156319) 🤗
