### ISSUE TITLE
Docker Desktop - Error invoking remote method 'docker-stop-container': Error: (HTTP code 500) server error - open \\.\pipe\docker_engine_linux: The system cannot find the file specified

### ISSUE THREAD

**Issue by RS1968** [docker/for-win#12192]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 2D21EB95-D186-4111-A7DB-1543204231C5/20210924090641

### Actual behavior
When I start docker and my container, everything is fine first. But when I let it be for a while, the whole docker doesn't seem to work anymore. Then myy container isn't running anymore but looks like it runs. And when I click to stop it a error message pops up.
Only restarting whole docker will solve the problem. 

### Expected behavior
Docker runs, my container runs.

### Information

  - Windows Version: Windows Server 2019 Essentials

  - Is it reproducible?:
Yes, everytime i restart docker it works for a while. But I don't now exactly for how long. 

  - Is the problem new?:
  A few updates before it worked fine. I waited for new updates, but the problem didn't solve with them.  
  
  - Did the problem appear with an update?:
  Yes, see answer before. But can't tell exactly which. 
  
  
  - Docker Desktop Version: 
  4.0.1
  
  - WSL2 or Hyper-V backend? :
  Hyper-V
  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: 
No

- I updated the Windows Server. 
- I reinstalled Docker several times. 
- I installed the newest NET-Framework.
- I started docker with Admin rights.

### Steps to reproduce the behavior
I don't know exactly what to do here.

  1. Run docker
  2. start conteiner
  3. wait for a while
  4. Container won't work anymore. When I click to stop the container, it shows an error, see screenshot below.
  5. Only a restart of docker will reset the issue. 
  
![error_docker](https://user-images.githubusercontent.com/26972794/134652310-c727974b-353a-402a-acfe-9066e44c4ef9.png)

**Comment by BinarySwami-10** [comment]
hello i also faced same issues , seems like your docker installation has entered invalid state . to resolve most problems for docker on windows which prevent docker from starting i have made scripts, have you checked my latest pull request from my fork? try running those scripts and tell if problem is solved or persists. thank you.

**Comment by RS1968** [comment]
> hello i also faced same issues , seems like your docker installation has entered invalid state . to resolve most problems for docker on windows which prevent docker from starting i have made scripts, have you checked my latest pull request from my fork? try running those scripts and tell if problem is solved or persists. thank you.

Doesn't work for me. Same error as before.
