### ISSUE TITLE
LCOW no matching manifest in Docker for Windows 17.10-rc1 running on Windows 10 1709

### ISSUE THREAD

**Issue by caleblloyd** [docker/for-win#1219]
I followed the steps at https://blog.docker.com/2017/09/docker-windows-server-1709/ and installed Docker for Windows with LCOW from here: https://download.docker.com/win/lcow/Docker%20for%20Windows%20Installer.exe

I am running Fall Creator's Update 1709:

![image](https://user-images.githubusercontent.com/2414837/31693713-2be1d36e-b36e-11e7-9ed3-44476159b6f7.png)

I have LCOW enabled in Docker for Windows:

![image](https://user-images.githubusercontent.com/2414837/31693736-4ea4f106-b36e-11e7-956e-bd709924748b.png)

### Expected behavior

I expect to get a shell when I run this comand:

```
> $Env:LCOW_SUPPORTED=1
> docker run --rm -it busybox sh
```

### Actual behavior

I just get an error complaining about architecture:

```
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: no matching manifest for windows/amd64 in the manifest list entries.
```

### Information

`docker info` output:

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: master-dockerproject-2017-10-16
Storage Driver: windowsfilter (windows) lcow (linux)
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 31.94GiB
Name: rog
ID: ILLK:KH7P:ARY4:MIAD:4WX7:IBKP:M7D3:YV4R:5BVP:F4BH:AZII:6VHB
Docker Root Dir: C:\ProgramData\Docker\lcow
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 27
 System Time: 2017-10-17T19:09:36.0858943-04:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by jasonbivins** [comment]
Hi @caleblloyd 
I wasn't able to reproduce this on my machine, can you provide a Diagnostic ID?  Right click the Whale icon - choose Diagnose and Feedback

**Comment by rn** [comment]
can you try adding:
```
$env:LCOW_API_PLATFORM_IF_OMITTED="linux"
```
to the environment where you start the `dockerd`. a week back a PR got merged to `moby/moby` which requires this, so depending on which version of docker you are picking up you may have to specify it.

There will be more changes in the future and I typically keep my instructions up to date here:
https://gist.github.com/rn/6bfade1ba98e22691cb287cc8c23609b

**Comment by stalb** [comment]
I had the same problem and tried rn's suggestion : 
`[Environment]::SetEnvironmentVariable("LCOW_API_PLATFORM_IF_OMITTED", "linux", "Machine")`

It solved the pb for me...

**Comment by JamesChan** [comment]
I also have this pb

**Comment by rn** [comment]
@JamesChan does setting the env variable fix it for you?

**Comment by caleblloyd** [comment]
New edge version ` master-dockerproject-2017-10-27` seems to not require the env variable

**Comment by JamesChan** [comment]
It seems that it still does not work with master-dockerproject 10-27 from LCOW channel. @rn setting for env didn't resolve it for me.

**Comment by puco** [comment]
Same issue, env variable does not help as well.

```
Version 17.11.0-ce-rc2-win37 (13978)
Channel: edge
19d223a
```

**Comment by rn** [comment]
@puco `docker run --rm -ti alpine` works for me with the latest edge (`Version 17.11.0-ce-rc2-win37 (13978)`) without setting any env variable etc.

```
PS C:\Program Files\Docker\Docker\resources\bin> docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.11.0-ce-rc2
Storage Driver: windowsfilter (windows) lcow (linux)
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17025 (17025.1000.amd64fre.rs_prerelease.171020-1626)
Operating System: Windows 10 Pro Insider Preview
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 15.85GiB
Name: DESKTOP-67CQHNQ
ID: JF2B:LDLX:TZZ6:EJ7D:NFS2:5DXH:OIKG:IHK3:7ZS4:CKPH:2UQ6:TBJJ
Docker Root Dir: C:\ProgramData\Docker\lcow
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 28
 System Time: 2017-11-03T17:09:42.6869936Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

It also works with ` master-dockerproject-2017-11-02` which you don't need to use since you seem to be using Docker for Windows.

What's your windows build number?

**Comment by raupie** [comment]
Same error. Disabled `Enable Linux containers on Windows` setting in options and now my docker-compose up -d is now working. 1709 windows build. Using WSL.

**Comment by axelfontaine** [comment]
Definitely still an issue with the latest edge release. Env var workaround doesn't work either, as already mentioned earlier on this thread.

**Comment by rn** [comment]
we moved the LCOW support to it's own repo and now the README there as well as the releases should be used. Can you try: https://github.com/linuxkit/lcow

The release was tested last week with the instructions in the readme

**Comment by leilei8814** [comment]
I think for many people it's because you are typing 'docker run ....' directly, the fix is to use give the path of docker.exe directly, it works for me...
