### ISSUE TITLE
Occasional port 80 already in use

### ISSUE THREAD

**Issue by mclougke** [docker/for-win#122]
### Expected behavior

load container, servicing port 80 / localhost:nnnnn
### Actual behavior

Stopping httpd: G[  OK  ](98)Address already in use: make_sock: could not bind to address [::]:80
(98)Address already in use: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
Unable to open logs
### Information
- Diagnostic ID from "Diagnose & Feedback" in the menu.
  A diagnostic was uploaded with id: 766992FD-3C95-4EE6-BB5F-38BBF547A4C4/2016-10-03_16-11-40
- a reproducible case if this is a bug, Dockerfiles FTW
  https://hub.docker.com/r/appcontainers/mediawiki/
- page URL if this is a docs issue or the name of a man page
- host distribution and version (Windows version, build number, etc)
  windows 10 Docker version 1.12.1-stable (7135) 995236d
### Steps to reproduce the behavior
1. load
2. stop, updated various app (php) files, start
3. repeat

Occurs about every 20 restarts

**Comment by dgageot** [comment]
@mclougke we couldn't reproduce your issue nor does it look like other people face the same problem. Can you confirm you still have the issue with more recent versions?

**Comment by mclougke** [comment]
I did reproduce it a few times, but it does require a fair bit of
unloading/reloading containers etc. I am no longer using docker, so you can
close the issue
thanks
