### ISSUE TITLE
Pull nano image failed with error "failed to register layer: re-exec error:..."

### ISSUE THREAD

**Issue by birdemily** [docker/for-win#1220]
### Expected behavior
Pull microsoft/nanosever successfully
### Actual behavior
Detail as below:
PS C:\Docker\testConsole> docker pull microsoft/nanoserver
Using default tag: latest
latest: Pulling from microsoft/nanoserver
bce2fbc256ea: Already exists
b0b5e40cb939: Extracting [==================================================>]  141.8MB/141.8MB
failed to register layer: re-exec error: exit status 1: output: failed to find link target for 'Files\Windows\System32\DriverStore\FileRepository\mshdc.inf_amd64_2e8db38129bb3260\atapi.sys' -> 'Files\Windows\System32
\drivers\atapi.sys'

### Information
I checked my system. In the folder "C:\Windows\System32\DriverStore\FileRepository", there is a sub-folder named "mshdc.inf_amd64_5c72b5c7f1ffa83d" but the error message try to find "mshdc.inf_amd64_2e8db38129bb3260". 

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
4DFC6199-2D27-4659-9960-9037E0D889A9/2017-10-18_16-27-09
  - host distribution and version (Windows version, build number, etc)
PS C:\Docker\testConsole> docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:50:27 2017
 OS/Arch:      windows/amd64
 Experimental: true

### Steps to reproduce the behavior
My pc crashed before, so i uninstall docker then re-install. For the first time i install docker, i remember i can pull nanosever. But it failed after i re-install.

**Comment by jasonbivins** [comment]
Hi @birdemily 
The files it's looking for are actually located in C:\ProgramData\Docker\WindowsFilter
It looks like it might be looking for part of an old image - can you try to remove the image, and then repull it?  ``` docker image rm -f microsoft/nanoserver ```

**Comment by birdemily** [comment]
Hi, @jasonbivins 
Thanks for the reply. I tried but it failed with the same error. 

PS C:\WINDOWS\system32> docker image rm -f microsoft/nanoserver
Error: No such image: microsoft/nanoserver
PS C:\WINDOWS\system32> docker images
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
consletest2                   latest              6da8da1f80b9        21 hours ago        10.4GB
testconsole                   latest              6da8da1f80b9        21 hours ago        10.4GB
microsoft/windowsservercore   latest              ce27208ad678        8 days ago          10.4GB
PS C:\WINDOWS\system32> docker image rm -f microsoft/nanoserver
Error: No such image: microsoft/nanoserver
PS C:\WINDOWS\system32> docker pull microsoft/nanoserver
Using default tag: latest
latest: Pulling from microsoft/nanoserver
bce2fbc256ea: Already exists
b0b5e40cb939: Extracting [==================================================>]  141.8MB/141.8MB
failed to register layer: re-exec error: exit status 1: output: failed to find link target for 'Files\Windows\System32\D
riverStore\FileRepository\mshdc.inf_amd64_2e8db38129bb3260\atapi.sys' -> 'Files\Windows\System32\drivers\atapi.sys'
