### ISSUE TITLE
Logs stop updating

### ISSUE THREAD

**Issue by jazomand** [docker/for-win#12210]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
On docker desktop, if the logs have a lot of output, it will eventually stop updating. The containers will continue to run normally and I can access the logs from the terminal, but on docker desktop will stop the output of new text.

### Expected behavior
The LOGS/terminal output shouldnt have a limit or have a configurable limit at least.

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible? Yes
  - Is the problem new? No
  - Did the problem appear with an update? No, its been like this for the past couple of years. I just never reported the issue.
  - Windows Version: Microsoft Windows [Version 10.0.19043.1237]
  - Docker Desktop Version: 4.0.1 (68347)
  - WSL2 or Hyper-V backend?: WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

**Comment by lorenrh** [comment]
Hi there! 
I'm not quite sure I undertand the issue. The logs stop updating from where?
