### ISSUE TITLE
Windows 11 wsl2 can't run, but it did three days ago，Tips：Docker Engine starting...

### ISSUE THREAD

**Issue by Dolorousxz** [docker/for-win#12261]
version：
windows11 22000.194
docker desktop Today's latest edition

Windows 11 can't run, but it did three days ago，Tips：Docker Engine starting...

logs：[11:01:57.731][LinuxWSL2Engine   ][Error  ] msg="(e921380a) 0299aed1-cross-distro S->C af3884a3-WslIntegrationService-CSharp GET /check (156.4μs): can't access specified distro mount service: stat /run/guest-services/distro-services/ubuntu.sock: no such file or directory[[STACK]]main.StartCrossDistroServer.func2({0xc0cf20, 0xc000486a80})\n\t/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/cross-distro-service.go:58 +0x412\n"

**Comment by StefanScherer** [comment]
Hi @Dolorousxz 
This looks like this issue, we have an internal build with a fix https://github.com/docker/for-win/issues/12229#issuecomment-937434033 and we're working on a patch release.

**Comment by gitvadim** [comment]
Check if [this ](https://github.com/docker/for-win/issues/12263#issuecomment-940824731) helps. It helped me with the same error on Win10 at least.
