### ISSUE TITLE
Cert issue after recent windows and related software update on company machine

### ISSUE THREAD

**Issue by jpierson** [docker/for-win#12265]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `670B87D9-802C-477F-B8BA-31EA5656FA35/20211012142309`

### Actual behavior

Certificate error when starting up Docker Desktop.

```
Docker.Core.DockerException:
time="2021-10-12T10:23:02-04:00" level=error msg="cannot create kubernetes PKI: error creating PKI assets: failed to write or validate certificate \"apiserver-kubelet-client\": failure loading apiserver-kubelet-client certificate: failed to load certificate: the certificate has expired"
```

### Expected behavior

Docker Desktop should startup as normal without error.

### Information

  - Windows Version: 1909
  - Docker Desktop Version: 2.4.0.0 (48506)
  - WSL2 or Hyper-V backend?  Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Start Windows
  2. Login

**Comment by stephen-turner** [comment]
Does a newer version of Docker Desktop fix that? That one is rather old.
