### ISSUE TITLE
Docker fails to initialize

### ISSUE THREAD

**Issue by geoffreykirui** [docker/for-win#12263]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...
![dacker fail](https://user-images.githubusercontent.com/45674489/136812109-9136ac34-1380-4861-a8df-957fe38ce407.png)

**Comment by gitvadim** [comment]
I had the same issue with Linux containers literally yesterday. It appeared that my WSL distro was in stopped state and did not want to run for whatever reason. I had to do this to make it work:

1. run `wsl --unregister {distro_name}` in admin shell to uninstall the stuck distro (it will remove the distro and all customizations that you applied to it'
2. install the distro again through the store (it will say installed, but click that button again to reinitialize the distro)
3. In admin powershell run `Get-Process | Where-Object { $_.Name -like '*docker*' } | Stop-Process -Force` to kill the lingering docker processes
4. Start docker again

**Comment by FelipeAlves99** [comment]
Had same issue after last update (Docker version 20.10.8, build 3967b7d) and deleting setting.json in (% appdata% / Docker / setting.json) with all docker processes terminated in task manager resolved for me. It does not delete any container or image.

Don't really know the source of the problem.
