### ISSUE TITLE
Mount binding not working on windows - Operation not permitted

### ISSUE THREAD

**Issue by jmacera95** [docker/for-win#12268]
### Actual behavior
I have an Airflow containerized app running on windows based on Apache Airflow official .yaml --> https://airflow.apache.org/docs/apache-airflow/stable/docker-compose.yaml with just a few changes as shown below:
![image](https://user-images.githubusercontent.com/74208045/137127381-ee8eb4fe-852d-4fe5-a23e-3f7062bc1a71.png)
Docker file:
![image](https://user-images.githubusercontent.com/74208045/137127445-53795452-ea01-41ec-b245-ffbf25bf9fc4.png)
I have a dag which pulls from a github repository within a subdirectory of the volumes so I can have access through my local machine and then run a docker container with the DockerOperator mounting the directory corresponding to the repo and run the .py inside the new container. 
![image](https://user-images.githubusercontent.com/74208045/137128228-a88639e1-2015-4583-9d1f-0baf6966053c.png)
![image](https://user-images.githubusercontent.com/74208045/137128431-90a35f40-44b0-4c60-84b3-ac269bae6062.png)
I've commented some lines to debug the error. 
Although the container is created and the directory is mounted, I hit an "Operation not permitted" error when trying to accesing the file or running it.
![image](https://user-images.githubusercontent.com/74208045/137130167-f9a2ccfb-cedd-4d34-99e3-3a6c257087ba.png)

### Expected behavior
Could be able to read, write and run the mounted files. 

### Information

  - Is it reproducible? Yes
  - Is the problem new? Is the first time I try something like this but I found previous errors related --> https://github.com/docker/for-win/issues/6016
  - Did the problem appear with an update? No
 
  - Windows Version: Windows 10 pro
  - Docker Desktop Version: 4.1.0
  - WSL2 or Hyper-V backend?   WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: On my local machine

**Comment by lislon** [comment]
I think I have same issue here:

- Desktop 4.2.0.
- Windows 10 pro
- `$(gin).WindowsBuildLabEx`: `19041.1.amd64fre.vb_release.191206-1406`

Repro steps:
1. Start parent docker:
  ```
  PS> docker run -it --rm -v "//var/run/docker.sock:/var/run/docker.sock" docker sh
  ```
2. Start child docker (inside parent docker):
```
# docker run -it --rm -v /c/myfolder:/data:rw alpine sh
```
3. Try to write something inside child docker:
```
# touch /data/test.txt

touch: /data/test.txt: Operation not permitted
```
