### ISSUE TITLE
Docker Engine Fails to Restart when upgrading from 4.1.0 to 4.1.1

### ISSUE THREAD

**Issue by ManfredLange** [docker/for-win#12278]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E03C3250-BFC7-4690-90B1-B0B777945A10/20211017023606

### Actual behavior

Docker Engine hangs with message "Docker Engine starting..." but does not complete.

### Expected behavior

Docker Engine should just start.

### Information

  - Windows Version: Windows 10 Professional
  - Docker Desktop Version: 4.1.1
  - WSL2 or Hyper-V backend? WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

  - This is reproducible and possibly the same problem as for the upgrades to all prior 4.x versions

### Steps to reproduce the behavior

  1. Install Docker 4.1.0 (upgrading from earlier versions may have the same problem)
  2. Run installer for Docker 4.1.1 to upgrade
  3. Start Docker Desktop
  4. Message "Docker Enginer starting..." is shown but it never completes

![image](https://user-images.githubusercontent.com/1130812/137608522-7fdc02da-dfab-4b57-af5b-ce60212dc5fa.png)

**Comment by ManfredLange** [comment]
The following steps helped in this case:

1. Uninstall version 4.1.1 (or whatever version you have)
2. Install version 4.1.1

It'd be great to get this upgrade issue resolved. If I count correctly this is the third upgrade with this problem. It's a bit of a nuisance.

**Comment by ManfredLange** [comment]
This is likely to be a similar issue as previously report for a prior version. More details at https://github.com/docker/for-win/issues/12226

**Comment by OzKron** [comment]
I also have the same issue
[https://github.com/docker/for-win/issues/12279](url)
Or something similear
Tried rebooting/ uninstall/ install
Nothing helped

**Comment by ManfredLange** [comment]
> 
> 
> I also have the same issue [https://github.com/docker/for-win/issues/12279](url) Or something similear Tried rebooting/ uninstall/ install Nothing helped

@OzKron The URL appears to be broken ...
