### ISSUE TITLE
docker-credential-desktop.exe fails on WSL, interrupting docker compose pull

### ISSUE THREAD

**Issue by Hazmi35** [docker/for-win#12273]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
`docker-credential-desktop.exe` found in `/usr/sbin/docker-credential-desktop.exe` which is a symbolic link to `/mnt/wsl/docker-desktop/cli-tools/usr/bin/docker-credential-desktop.exe` throws `/usr/sbin/docker-credential-desktop.exe: Invalid argument` even when executing it from the terminal without any arguments

### Expected behavior
It should work the same way as in Windows, for example, executing `docker-credential-desktop.exe help` on Windows would show the help info, and doesn't throw any errors like in WSL

### Workaround
I managed to bypass the WSL-version of `docker-credential-desktop.exe` to use the one on `C:\Program Files\Docker` with `$  sudo ln -sF /mnt/c/Program\ Files/Docker/Docker/resources/bin/docker-credential-desktop.exe /usr/local/bin`, and then reopening your terminal

### Information

  - Windows Version: **Windows 11 Build 22000.258**
  - Docker Desktop Version: **4.1.1**
  - WSL2 or Hyper-V backend?  **WSL2**
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: **No**

### Steps to reproduce the behavior

  1. Install the latest Docker Desktop for Windows
  2. Use the WSL2 Backend
  3. Enable WSL Integration
  4. Open your WSL Terminal
  5. Try `docker pull ubuntu`, it somehow works but throws `/usr/sbin/docker-credential-desktop.exe: Invalid argument`
  6. Try using docker-compose `docker compose pull` with docker-compose.yml like this:
```
services:
  bot:
    image: "ubuntu"
    restart: unless-stopped
version: "2.4"
```
  It would fail. Also, this happens on the docker-compose v1 as well.
```
/usr/sbin/docker-credential-desktop.exe: Invalid argument
[+] Running 0/0
 ⠋ bot Pulling                                                                                                     0.0s
error getting credentials - err: exit status 1, out: ``
```

**Comment by StefanScherer** [comment]
Thanks @Hazmi35 for the report. One question: How did you install WSL on Windows 11, maybe the preview from the Microsoft Store ?
If yes, this is exactly what we also found out. 
For now it is recommended to use the WSL optional Windows feature instead until a fix for WSL will be released in the Microsoft Store.

**Comment by Hazmi35** [comment]
This is probably fixed in https://github.com/microsoft/WSL/releases/tag/0.48.1, I'll close this issue.
