### ISSUE TITLE
Docker doesn't start Window 10 Pro

### ISSUE THREAD

**Issue by lpignotti** [docker/for-win#1228]
### Expected behavior
docker ps run without error
### Actual behavior
>docker ps
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/containers/json: open //./pipe/docker_engine: Impossibile trovare il file specificato. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

### Information

 Diagnostic ID 0ED4FAA3-37C7-4CC7-8567-F853400A8438/2017-10-20_00-01-15
 Window 10 Pro Version 1703 Buld OS 15063,483

### Steps to reproduce the behavior

  1. check "What to know before you install" and everything it's ok
  2. run as Administrator "Docker for Windows Installer.exe"
  3. Installer didn't ask me to authorize Docker.app but installation succeeded
  4. >docker run hello-world
C:\Program Files\Docker\Docker\resources\bin\docker.exe: error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engin
e/v1.32/containers/create: open //./pipe/docker_engine: Impossibile trovare il file specificato. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker
 daemon is not running.
See 'C:\Program Files\Docker\Docker\resources\bin\docker.exe run --help'.

**Comment by compulim** [comment]
Do you see Docker in the [system tray](https://docs.docker.com/docker-for-windows/#docker-settings)? If no, run "Docker for Windows" application first, then `docker.exe` should work.

**Comment by lpignotti** [comment]
@compulim 
Yes, I see Docker but doesn't work

I'm following this thread #1075

**Comment by fschaal** [comment]
You might need to run powershell as admin.

**Comment by lpignotti** [comment]
@fschaal 
I did every single action as admin in powershell

**Comment by lpignotti** [comment]
@jasonbivins 
Hi Jason, I read #871 and I notice that my PC name is long 12 characters but I'm on domain so the full name is 12characters+domain_name.

Could be this my docker startup error? 
Whether this is my error you can guess that I can't remove domain from my pc.
So how can i solve this issue?

Thanks

**Comment by lpignotti** [comment]
@jasonbivins 
Hi Jason, can you help me?
Do you need more infos or something like that?
Diagnostic ID is correct?
I don't know how to solve this problem.

Thanks

**Comment by jedmao** [comment]
Same issue here. Computer name is only 9 characters long. Docker icon is NOT in the system tray and won't be there no matter how many times I try to start "Docker for Windows".

More details at https://github.com/docker/for-win/issues/1338#issuecomment-346909642

**Comment by jasonbivins** [comment]
Hi @lpignotti 
It looks like the Docker for Windows service can't start- I see this error in the logs
``` [23:36:16.107][ErrorReportWindow][Info   ] Open logs
[23:39:35.726][WindowsDaemon  ][Info   ] Avvio della sessione 1 - 2017-10-19T21:39:34.656871400Z in corso.
[23:40:22.412][WindowsDaemon  ][Info   ] Pianificazione del riavvio del servizio di protezione software per le ore 2117-09-25T21:40:22Z completata. Motivo: RulesEngine.
[23:51:18.002][WindowsDaemon  ][Info   ] Stato Windows Defender aggiornato in SECURITY_PRODUCT_STATE_SNOOZED.
[23:51:18.024][WindowsDaemon  ][Info   ] Stato Windows Defender aggiornato in SECURITY_PRODUCT_STATE_SNOOZED.```
``

**Comment by lpignotti** [comment]
Hi @jasonbivins 

I turned off Windows Defender and I tried to run Docker.

Finally it works!!! 

```
PS C:\WINDOWS\system32> docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.
```

Thank you!!

**Comment by tswiftma** [comment]
I'm seeing this same error trying to run Docker but unfortunately I can't turn off Windows Defender due to corporate polices. Any other workarounds? This seems like a really bad bug.
