### ISSUE TITLE
Docker Desktop Stop working suddenly

### ISSUE THREAD

**Issue by kennedy** [docker/for-win#12286]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `CB085057-24EE-496C-A46D-EBF6F285432C/20211019002058`

### Actual behavior

1. Start Docker Desktop
2. Engine starting
3. Engine never finishes

### Expected behavior

1. Start Docker Desktop
2. Engine starting
3. Engine finish in about 1 minutes

### Information
  - Is it reproducible? Everytime
  - Is the problem new? Yes, it was working a 2-3 days ago
  - Did the problem appear with an update? Most likely? Windows updates automatically
  - Windows Version: 21H1 - 19043.1288
  - Docker Desktop Version: 4.1.1
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Start Docker Desktop
  2. Engine starting

**Comment by Ronkiro** [comment]
Just an addition, i had a problem with WSL. This may be related
