### ISSUE TITLE
Docker Desktop suddenly fails at startup

### ISSUE THREAD

**Issue by dprevato** [docker/for-win#12280]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: AE3A316E-C23E-4ECE-9ADC-26ED54D06420/20211017071358

### Actual behavior
At startup. docker fails and this dialog appears:
![image](https://user-images.githubusercontent.com/13785877/137617883-e89e2f8f-8dbb-4729-9f70-0fdd07bad7dc.png)

### Expected behavior
A normal startup of Docker

### Information

  - Windows Version: Windows 11 Pro version 21H2 - OS build 22000.258 - Experience Windows Feature Experience Pack 1000.22000.258.0
  - Docker Desktop Version: 4.0.1.68347
  - WSL2 or Hyper-V backend?  YES, WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: NO

The problem is NOT related to any change in configuration, and AFAIK is not related to automatic upgrades either. Till yesterday, Docker worked like a charm.

### Steps to reproduce the behavior

I have no idea how to reproduce the problem. As i said, Docker has been working without any problem and without any change in configuration for months.

**Comment by OzKron** [comment]
AFE27455-5407-4D65-A449-1D29447359D2/20211017123304 I also got Diagnostics ID
