### ISSUE TITLE
Docker Desktop starts takes forever

### ISSUE THREAD

**Issue by ezequieldelucaey** [docker/for-win#12304]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features. Couldn't disable as the options are greyed out as docker never starts
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: AC0FCAD6-6E84-4746-844F-671515740811/20211025102856 (uploaded)
### Actual behavior
Docker Engine Starting message appears when open Docker Desktop. Checked Windows Services (Docker Desktop Service is running)
### Expected behavior
Docker starts normally
### Information
  - Is it reproducible? N/A
  - Is the problem new? Yes
  - Did the problem appear with an update? Yes
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.
-->
  - Windows Version: 10.0.19042.1288
  - Docker Desktop Version: 4.1.1
  - WSL2 or Hyper-V backend?  Windows HyperV Enabled. Install Linux Subsystem (Ubuntu) with wsl
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

For the error of diagnostic I attempted the following:
[FAIL] DD0003: is the Docker CLI working? exit status 1
tried running docker ps -a
Error response from daemon: open \\.\pipe\docker_engine_linux: The system cannot find the file specified.
What I tried DockerCli.exe -SwithLinuxEngine
Error still appears
[FAIL] DD0004: is the Docker engine running? Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.

[FAIL] DD0011: are the LinuxKit services running? failed to ping VM diagnosticsd with error: Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.

[FAIL] DD0029: is the WSL 2 Linux filesystem corrupt? exit status 1
Disable HypeV
Disable Linux Subsystem
Uninstall Linux Virtual Machine
Restart Machine
Enable/Install mentioned below
Error still appears
also tried
wsl --shutdown
Error still appear
[FAIL] DD0005: is the user in the docker-users group? The specified domain either does not exist or could not be contacted.
Manually check the group and the user is present
[FAIL] DD0009: is the vpnkit API responding? open \\.\pipe\dockerVpnKitDiagnostics: The system cannot find the file specified.

[FAIL] DD0012: is the VM networking working? network checks failed: Post "http://ipc/check-network-connectivity": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.

I also tried reinstall from scratch with AntiVirus and Firewall disabled running with admin rights

**Comment by rkschamer** [comment]
The issue might also relate to https://github.com/docker/for-win/issues/11996

I'm experiencing the same issue and just uploaded diagnosis data: 146A922C-A213-4836-93FD-EDC62717D31F/20211103192801

**Comment by RoFz** [comment]
> The issue might also relate to #11996
> 
> I'm experiencing the same issue and just uploaded diagnosis data: 146A922C-A213-4836-93FD-EDC62717D31F/20211103192801
> 
> I can confirm that downgrading to version 4.0.1 solves the issue. I'll use this as workaround and hope that it will get fixed with future releases.

Same issue. Downgrading to 4.0.1 solves it.

**Comment by rkschamer** [comment]
I just can confirm that upgrading to Docker Desktop 4.2.0 solved the issue for me. Also WSL connection is working fine.

**Comment by soroshsabz** [comment]
ITNOA

My problem is not resolved with upgrading to 4.2.0 :(
