### ISSUE TITLE
Pulling image fails...parameter is incorrect

### ISSUE THREAD

**Issue by chriscatilo** [docker/for-win#1231]
### Expected behavior
pull image of microsoft/nanoserver
### Actual behavior
docker pull microsoft/nanoserver
Using default tag: latest
latest: Pulling from microsoft/nanoserver
bce2fbc256ea: Extracting [==================================================>]  252.7MB/252.7MB
b0b5e40cb939: Download complete
failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer C:\ProgramData\Docker\windowsfilter\81a7a060668
c6b4d174f9b059c89431ff8874e5e91f3d0810e9d65e6d24068c0: The parameter is incorrect.
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
711388DE-6CAB-4CA3-AA4E-6219223960B4/2017-10-20_21-33-52
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)
docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:50:27 2017
 OS/Arch:      windows/amd64
 Experimental: false
docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.09.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 15063 (15063.0.amd64fre.rs2_release.170317-1834)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 31.71GiB
Name: CUBE-PC
ID: TEAC:LINU:VSB5:KAWW:3I6U:FMF3:6ZYN:ZUGV:ZGZU:6WCC:4QUT:6QAV
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 22
 System Time: 2017-10-20T21:44:48.3349056+01:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

### Steps to reproduce the behavior

  1. docker pull microsoft/nanoserver (fails)
  2. also run Debug-ContainerHost.ps1 with results attached.
[debug-containerhost results.txt](https://github.com/docker/for-win/files/1403267/debug-containerhost.results.txt)

**Comment by chriscatilo** [comment]
PS: I've turned off Windows Defender via the local group policy and that hasn't solved the problem.

**Comment by compulim** [comment]
Are you running Docker in "Windows containers" mode or "Linux containers" mode? You need Windows containers mode to pull and run `microsoft/nanoserver`.

You can see how to switch between modes [here](https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers).

**Comment by chriscatilo** [comment]
Hi @compulim , I'm running Windows containers. The error is happening on my desktop running Windows 10 Enterprise Build 15063 with the latest stable version of docker without Win Defender. I've just installed the same version on my laptop running Windows 10 Pro Build 15063 with Win Defender, but this one pulls the nanoserver successfully. I am at a loss.

**Comment by MacDennis76** [comment]
The solution as provided by @artisticcheese worked for me. See: https://github.com/docker/for-win/issues/737

I first disabled Windows Defender and then I enabled and disabled BitLocker. Only then I was able to pull & exact the image. Weird. This was on an updated Windows 10 Pro OS and Docker 17.09.0-ce without the experimental features.

**Comment by Icehunter** [comment]
I have no options to use bitlocker since I'm using a bootcamp; my laptop is domain joined to our corp net and this just recently started happening. I'm not sure what info I can provide to get a solution though.
