### ISSUE TITLE
Docker Desktop is Starting for a very long time.

### ISSUE THREAD

**Issue by yuusakuri** [docker/for-win#12312]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:BDE977B5-27A2-4760-8C4B-3D4C4797003C/20211107095911

### Actual behavior
Docker Desktop is Starting for a very long time.

### Expected behavior
docker desktop becomes Running.

### Information

  - Windows Version: 10.0.19041
  - Docker Desktop Version: 4.1.1
  - WSL2 or Hyper-V backend?  Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

I couldn't reproduce it, but I changed the display language and system locale just before.

**Comment by allenyllee** [comment]
I have the same issue, here is my diagnostics ID: A0793936-403E-47CA-8B26-301982E4529C/20211107100910

**Comment by allenyllee** [comment]
I can confirm that downgrade to 4.1.0.0 solve this issue.

**Comment by fredericdalleau** [comment]
@allenyllee  can you check what's in your wsl distro `cat /var/lib/docker-desktop/mounts.data` ? Could you try renaming this file to `mount.data.old` and starting Docker desktop? Note that your containers mountpoint would point to empty directories. 

@yuusakuri it seems you are using a network drive located on the internet. Can you try disabling it?

**Comment by allenyllee** [comment]
I can confirm that update from 4.1.0.0 to 4.5.1 (74721) through update process is OK, no need to uninstall current version. 

wsl kernel version: 5.10.60.1
