### ISSUE TITLE
docker close without any message after start

### ISSUE THREAD

**Issue by bluelovers** [docker/for-win#12311]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

Diagnostics Bundle: C:\Users\User\AppData\Local\Temp\2257C922-C889-47FF-89C3-8892E82272B4\20211025201824.zip
Diagnostics ID:     2257C922-C889-47FF-89C3-8892E82272B4/20211025201824 (uploaded)

### Actual behavior

Docker Desktop close without any message after start

### Expected behavior

Docker Desktop is keep alive

### Information

  - Windows Version:

![image](https://user-images.githubusercontent.com/167966/138765673-8686d3a7-10a5-4735-bc96-6ea39df3e32d.png)

  - Docker Desktop Version:

![image](https://user-images.githubusercontent.com/167966/138765851-5db47ef5-396b-4898-927a-a7b5926f66f4.png)

  - WSL2 or Hyper-V backend?  WSL2 
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Steps to reproduce the behavior

  1. start Docker Desktop
  2. Docker Desktop will close after few time pass

**Comment by afashi** [comment]
I have the same problem.

**Comment by BroHui** [comment]
Same problem borther me.

**Comment by BroHui** [comment]
I'm thinking about this problem cause by .Net framework 5, try uninstall high version of .NET framwork on your pc.

**Comment by arshcaria** [comment]
I'm having the same issue.
You can try these workarounds:

- install the 3.2.2 version (and disable auto update with [this](https://github.com/RektInator/kill-docker-auto-update))
or
- keep the 4.x version and add a login program task in Windows Task Scheduler to start the program twice automatically.
