### ISSUE TITLE
WSL2 Integration with Ubuntu 20.04 stop working

### ISSUE THREAD

**Issue by mkuivi** [docker/for-win#12321]
- [ x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Cannot use docker inside wls2

### Expected behavior
Should be able to use docker inside wsl2

### Information

  - Windows Version: Windows 10 Enterprise - 21H1, build 19043.1288
  - Docker Desktop Version: 20.10.8, build 3967b7d
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:  Not in the cloud and not VM

### Steps to reproduce the behavior

I installed the Desktop version and it was working for a while. It stopped working for no reason.
On the WSL Ubuntu 20.04, the command **which docker** returns */mnt/c/Program Files/Docker/Docker/resources/bin/docker*. It should return something like */usr/bin/docker*

When I run command **docker** in wsl, I get 
```
The command docker could not be found in this WSL 2 distro.
We recommend to activate the WSL integration in Docker Desktop settings.

See https://docs.docker.com/desktop/windows/wsl/ for details.
```

But I have the WSL2 integration enabled in the settings. I have uninstalled and reinstall multiple times with no luck.

I found out that the *cli-tools* is at */mnt/wsl/docker-desktop/cli-tools/* is empty on the command line. When I open file explorer, I can see there are folders and files inside. Hence some thing is wrong somewhere.

From powershell,   **wsl -l -v**
```
  NAME                   STATE           VERSION
* Ubuntu-20.04           Running         2
  docker-desktop-data    Running         2
  docker-desktop         Running         2
```

**Comment by Rafeqm** [comment]
Any solution to this yet? I'm having the same problem too.

**Comment by mkuivi** [comment]
**Diagnostics ID**: 190E76DA-85FB-45BC-BB0C-E2E779081F89/20211102025249

**Comment by mkuivi** [comment]
I have tried this steps already and did not work. 
Also tried many times to uninstall -> reboot -> install -> reboot -> and active docker-desktop and did not work.

**Comment by rcribeiro** [comment]
> -> re

Let me help you. How is the best mean to contact you?

**Comment by mkuivi** [comment]
> 
> 
> > -> re
> 
> Let me help you. How is the best mean to contact you? I mean 101 help

Thanks. Do you have any other thins that can be tried?
The main issue I see is **ls -l /usr/bin/ | grep docker** does display the expected info
```lrwxrwxrwx 1 root   root          56 Nov  1 20:37 com.docker.cli -> /mnt/wsl/docker-desktop/cli-tools/usr/bin/com.docker.cli
lrwxrwxrwx 1 root   root          48 Nov  1 20:37 docker -> /mnt/wsl/docker-desktop/cli-tools/usr/bin/docker
lrwxrwxrwx 1 root   root          56 Nov  1 20:37 docker-compose -> /mnt/wsl/docker-desktop/cli-tools/usr/bin/docker-compose
lrwxrwxrwx 1 root   root          59 Nov  1 20:37 docker-compose-v1 -> /mnt/wsl/docker-desktop/cli-tools/usr/bin/docker-compose-v1
lrwxrwxrwx 1 root   root          71 Nov  1 20:37 docker-credential-desktop.exe -> /mnt/wsl/docker-desktop/cli-tools/usr/bin/docker-credential-desktop.exe
lrwxrwxrwx 1 root   root          50 Nov  1 20:37 hub-tool -> /mnt/wsl/docker-desktop/cli-tools/usr/bin/hub-tool
```

but the files does not exist. For example
**ls -l  /mnt/wsl/docker-desktop/cli-tools/usr/bin/docker**
_ls: cannot access '/mnt/wsl/docker-desktop/cli-tools/usr/bin/docker': No such file or directory_

**Comment by mkuivi** [comment]
Email is the best option to contact me.

**Comment by mkuivi** [comment]
I think I might have found the  issue. I created a script that will run at Windows Start up. When this script starts, it also starts _wsl_. But from what I have tested so far, looks like **docker-desktop** needs to start before **wsl** start.

Once I disabled the script, and rebooted the computer, it started working once I start _docker-desktop_ before _wsl_. So far so good. Will get back to you if starts again.

**Comment by MetalOoze05** [comment]
> I think I might have found the issue. I created a script that will run at Windows Start up. When this script starts, it also starts _wsl_. But from what I have tested so far, looks like **docker-desktop** needs to start before **wsl** start.
> 
> Once I disabled the script, and rebooted the computer, it started working once I start _docker-desktop_ before _wsl_. So far so good. Will get back to you if starts again.

Hey, I am also having the same issue so can you share the script with me if possible?

**Comment by mkuivi** [comment]
The script I have running was what created the problem. Hence I just disabled the script.

From what I have learned so far, you need to make sure docker-desktop starts before **wsl**. If **wsl** is running, stop it. Start docker-desktop first.
run **wsl -l -v** to make sure all everything is stopped. The start docker-desktop. Y

**Comment by JosueNicholson** [comment]
I am having the same problem. I already tried reinstall docker-desktop, reinstall ubuntu 18.04 distro. Nothing works. Also, I ensured my distros are wsl2. However, docker-desktop seems not recognizing neither ubuntu 18.04 or debian distros as wsl2.

**Comment by mkuivi** [comment]
Try this and see if helps
https://github.com/docker/for-win/issues/12321#issuecomment-957959866

**Comment by martijn10kb** [comment]
I am having the same issue, but this helped me: #12321 (comment). Although I couldn't restart docker from tray. But needed to close it in taskmanager and then start it again.

**Comment by martijn10kb** [comment]
Somehow, after every windows restart this issue pops up again for.

Today I cant even resolve it with the way I always did.. Solution doesnt work for me anymore :/

**Comment by hellorayza** [comment]
I tried it for a long time, in many ways. Findally, I took an extreme approach.

step1.Uninstall all ubuntu.
step2.Clear mechine file
step3.Check VirtualMachinePlatform and Microsoft-Windows-Subsystem-Linux
step4.Check wsl in powshell:
```
$ wsl -l -v  
# to ensure no ubuntu and only belows
docker-desktop         Running         2
docker-desktop-data    Running         2
```
step5.Check docker desktop: 
	  Resources > WSL Integration > no ubuntu
step6.powershell admin:  
```
$ wsl.exe --update
This change will take effect on the next full restart of WSL. To force a restart, please run 'wsl --shutdown'.
Kernel version: 5.10.102.1
$ wsl --shutdown
$ wsl --list --running
Windows Subsystem for Linux Distributions:
docker-desktop (Default)
```
step7.MS store :
	download ubuntu
step8.docker desktop: 
	Resources > WSL Integration >  Enable ubuntu
   Apply & Restart. Note it won't be restart itself,you need right click from tray to Restart
step9.Ubuntu:
```
$ docer --version
  Docker version 20.10.14, build a224086
```

**Comment by JohoDo** [comment]
I ahve the same issue since a long time, however I'm irritated that I could solve it with wsl --shutdown and restarting docker desktop.
This is because I always start docker before opening wsl distros in windows terminal, so I ruled that one out earlier. My sequence is VPN -> Docker -> WSL.
I need to check if the default distribution gets loaded when logging in, since as a workaround I installed Ubuntu18.04, where docker integration worked without issues.

**Comment by HollisTech** [comment]
What docker desktop appears to do when it 'connects' to a wsl instance is to attempt to insert its own version of the docker utilities by first mounting /mnt/wsl/docker-desktop on that wsl instance and then linking various exes in /usr/bin to the docker exes in /mnt/wsl/docker-desktop.  So for example:
lrwxrwxrwx 1 root   root           56 Oct 16 19:06  docker-compose -> /mnt/wsl/docker-desktop/cli-tools/usr/bin/docker-compose

If there is an existing install of docker on the wsl instance then this can result in a broken install on that wsl instance.  For example, on one of my wsl instances the docker exe is what was installed by me, but docker-compose is a symlink to the stuff docker desktop inserted.

Also, if there is no existing docker install on that wsl instance, and docker desktop is not connected, then attempts to use docker on that instance will fail.

This all seems like **A Really Bad Idea**, but that is just my opinion. Why not just require a docker install on any wsl instance that needs to run docker?

**Comment by JohoDo** [comment]
This issue is still happening even on absolutely fresh installations. Just because no one reports it any further it doesnt mean that it magically disappeared.

**Comment by martijnenco** [comment]
I cant reopen it though :/

**Comment by JohoDo** [comment]
Thanks for trying though 🙇
