### ISSUE TITLE
Mounting WSLg Paths without using a system distro

### ISSUE THREAD

**Issue by jnewberry0502** [docker/for-win#12325]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B9BC8A91-929E-49DB-989E-3510A4F2D54D/20211030233111

### Actual behavior
When running in CMD
```
docker run -v /tmp/.X11-unix:/tmp/.X11-unix -it ubuntu
ls /tmp/.X11-unix
(no files)
```

When running in an Ubuntu distro
```
docker run -v /tmp/.X11-unix:/tmp/.X11-unix -it ubuntu
ls /tmp/.X11-unix
(X0 shows up)
```

### Expected behavior
Running in CMD
```
docker run -v /tmp/.X11-unix:/tmp/.X11-unix -it ubuntu
ls /tmp/.X11-unix
Should see X0 (as seen when running in a Ubuntu Distro)
```

I want to be able to use WSLg without having to run my commands in Ubuntu. When I login to the docker-desktop wsl instance, I can see the X0 file in /tmp/.X11-unix.

`
wsl -d docker-desktop
ls /tmp/.X11-unix/
(X0 shows up)
`

Is there a way to mount files directly from the docker-desktop wsl instance, or is there some virtual file system that doesn't allow this?

### Information
  - Is it reproducible? Yes, tested on several Win11 machines
  - Windows Version: Win11 21H2 22000.282
  - Docker Desktop Version: 4.1.1
  - WSL2 or Hyper-V backend? WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

**Comment by JKocerka** [comment]
It's possible that it's related to #12323. 

If it's the same case, please comment, maybe we can put more attention to this issue.
