### ISSUE TITLE
Docker fails to start with Linux containers. Error: Binary stream "0" does not contain valid BinaryHeader.

### ISSUE THREAD

**Issue by MosterAndMonk** [docker/for-win#1232]
### Expected behavior
Upon starting Docker on Windows 10 Pro, Docker starts with no issues -- displays message "Docker is up and running!"
### Actual behavior
Upon starting Docker on Windows 10 Pro, Docker displays a window with following error message.

>"Binary stream "0" does not contain valid BinaryHeader. This may be due to invalid flow, or due to changes in the object version between serialization and serialization. In Docker.Core.Pipe.NamedPipeClient.Send (String action, Object[] parameters) position C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs: line 36 At Docker.Actions.<>c__DisplayClass25_0.b__0 () position C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs: line 285 At Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1 () position C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs: line 59 "

Issuing **docker info** command from the command line results in the following error message

>error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

### Information

  - Diagnostic ID 8301DF91-91DE-4022-B390-2F0AF64E7C04/2017-10-21_08-08-42
  - Windows 10 Pro -- Version 1703, Build 10.0.15063
  - Docker -- Version 17.09.0-ce-win34 (13622), Channel: edge, 9171a03
  - Same is true with latest version of Docker available from stable channel
  - Only happens with Linux containers

### Steps to reproduce the behavior
1.Installed Docker
2.Started Docker, the error ocurred.

**Comment by lDarki** [comment]
Install and Unintall File and Printing sharing service worked for me. Try it.
![image](https://user-images.githubusercontent.com/14332713/31879731-9d9a3a18-b7de-11e7-97a7-b4cc0b4596e6.png)

**Comment by albamoro** [comment]
My adapter was missing both the "Client for Microsoft Networks" & "File and Printer Sharing for Microsoft Networks". Reinstalling both fixed the issue. Can't tell if just one of them would have been enough.

**Comment by mablae** [comment]
@sandangel Same here windows insider 17093

**Comment by albamoro** [comment]
@sandangel, you'll probably have figured this one by now. If I remember correctly: Control Panel\Network and Internet\Network Connections > (Select the appropriate network here) > Right Click -> Properties > Install

**Comment by sandangel** [comment]
@albamoro I have already installed File and Printer... and it was not included in Microsoft service list to install. so I guess I have to uninstall it first. But when I try to uninstall, the error show up as described above.

**Comment by jerrulususu** [comment]
@sandangel Same problem with you... File and Printer Services already installed. Uninstall it will cause an error as described above... Have you figured out how to make docker works?

**Comment by sandangel** [comment]
@jerrulususu yes, I have figured out. I deleted Windows and install Linux.

**Comment by shahujvaln** [comment]
@lDarki Thanks for this. It's working now.

**Comment by tonytronics** [comment]
@IDarki thanks this works for me also

**Comment by GokulRG** [comment]
I am facing the same issue and all my print and sharing services and everything is enabled.

**Comment by IonelLupu** [comment]
@shahujvaln @tonytronics who is @idarki?

**Comment by EvgeniiRay** [comment]
> @shahujvaln @tonytronics who is @idarki?

This was me :) I've changed a nickname but seems like github didn't manage to change it in comments.
