### ISSUE TITLE
can't use Windows container with "process isolation" without installed "hyper-v features"

### ISSUE THREAD

**Issue by Andrysky** [docker/for-win#12338]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features - not applicable - did not include
  - [ ] I have uploaded Diagnostics - it does not come out to collect since it collects information by WSL

### Actual behavior
![image](https://user-images.githubusercontent.com/5894390/139838088-9ed1d859-26b2-4772-b53d-732e36fa1342.png)

### Expected behavior
docker-desctop work

### Information
  - Windows Version: win 10 20H2 
  - Docker Desktop Version: 4.1.1 (69879)
  - process isolation
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: yes in vm

### Steps to reproduce the behavior
I do not have hyper-v features installed, I want to use process isolation - virtualization is not required for it.
  "exec-opts": [
    "isolation=process"
  ]
but I can not switch to windows containers as you require (although you should not) hyper-v

**Comment by Andrysky** [comment]
hi, are you planning to fix this?

**Comment by Andrysky** [comment]
Reopen please

**Comment by StefanScherer** [comment]
Thanks for your interest in process isolation mode for Windows Containers. We have a roadmap ticket https://github.com/docker/roadmap/issues/151 where you can vote up this feature and share your use-case. Thank you.
