### ISSUE TITLE
Unknown Error on Sign in behind corporate firewall

### ISSUE THREAD

**Issue by id8314** [docker/for-win#12342]
Docker Desktop for Windows version 20.10.8

Working behind a corporate firewall I set up PX proxy server [https://github.com/genotrance/px](https://github.com/genotrance/px) and set docker Resources->Proxies to use it (in my case http://127.0.0.1:3131/).

From the command line everything works fine e.g.;
docker login
docker pull
docker push
...

The problem occurs when using Sign in on the dashboard. It always returns "Unknown error" regardless of using correct credentials or intentionally wrong ones.

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:  0417C56E-C497-4BFB-BF9E-E4FBA5A4E238/20211104100219  (Diagnosing from the terminal)
  - If using dashboard: Cannot upload diagnostics. Reason: Error invoking remote method 'desktop-go-backend': Error: {"message":"Internal Server Error"}

### Actual behavior
Sign in on the dashboard. It always returns "Unknown error" regardless of using correct credentials or intentionally wrong ones.
### Expected behavior
Successful Sign in or invalid credentials message
### Information
  - Windows Version: 10 20H2 and 11 21H2
  - Docker Desktop Version: 20.10.8
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior
  1. Get behind corporate proxy server
  2. Configure proxy server: PX proxy server [https://github.com/genotrance/px](https://github.com/genotrance/px) and set docker Resources->Proxies to use it (in my case http://127.0.0.1:3131/).
  3. Configure docker proxies
  4. Sign in on dashboard

**Comment by NormanEdance** [comment]
Same.

Docker Desktop v.4.1.1
Engine: 20.1.8

**Comment by NormanEdance** [comment]
Boiis from information security department resolved my issue by adding exception for docker address. 🎉
