### ISSUE TITLE
Docker doesn't start. Unable to provide diagnostic ID

### ISSUE THREAD

**Issue by joseraeiro** [docker/for-win#12346]
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: I'm unable to provide a diagnostic ID due to the fact that when running
   
`PS C:\> & "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" gather -upload`

I receive the following 

`time="2021-11-05T11:41:16Z" level=info msg="ipc.NewClient: d31fcf96-com.docker.diagnose -> \\\\.\\pipe\\dockerBackendV2 com.docker.service.exe [[STACK]]goroutine 1 [running, locked to thread]:\ngithub.com/docker/pinata/win/backend/pkg/service.NewClientForPath(...)\n\tC:/workspaces/PR-16591/src/github.com/docker/pinata/win/backend/pkg/service/service.go:26\ngithub.com/docker/pinata/win/backend/pkg/service.NewClient(...)\n\tC:/workspaces/PR-16591/src/github.com/docker/pinata/win/backend/pkg/service/service.go:20\ngithub.com/docker/pinata/common/pkg/diagkit/gather/diagnose.init()\n\tC:/workspaces/PR-16591/src/github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/ipc_windows.go:23 +0x132\n"
time="2021-11-05T11:41:16Z" level=info msg="unable to query WSL distros: exit status 0xffffffff"
Gathering diagnostics for ID 067AF7F6-D75C-4FED-9769-FF005E4BBEFC/20211105114116 into C:\Users\Jose\AppData\Local\Temp\067AF7F6-D75C-4FED-9769-FF005E4BBEFC\20211105114116.zip.
This may take up to 15 minutes.
time="2021-11-05T11:41:16Z" level=info msg="Triggering Linux sysrq via a unix socket: \\\\.\\pipe\\dockerDiagnosticd" type=unixsock
[SKIP] DD0028: is there available VM disk time="2021-11-05T11:41:16Z" level=warning msg="/sysrq failed: Post \"http://unix/sysrq\": open \\\\.\\pipe\\dockerDiagnosticd: The system cannot find the file specified." type=unixsock
space?
time="2021-11-05T11:41:16Z" level=info msg="Start gathering list of 112 elements (timeout=15m0s)" type=list
time="2021-11-05T11:41:16Z" level=info msg="Gathering DiagKit" type=list
time="2021-11-05T11:41:16Z" level=info msg="Gathering BackendGatherer" type=list
time="2021-11-05T11:41:16Z" level=info msg="Gathering system" type=list
time="2021-11-05T11:41:16Z" level=info msg="Executing: [powershell -NoProfile -Command &{ $(Get-WmiObject Win32_OperatingSystem) | ConvertTo-json -Depth 1 }]"
time="2021-11-05T11:41:18Z" level=info msg="Executing: [powershell -NoProfile -Command &{ $(Get-WmiObject Win32_ComputerSystem) | ConvertTo-json -Depth 1 }]"
error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json": open //./pipe/docker_engine: The system cannot find the file specified.
time="2021-11-05T11:41:19Z" level=info msg="Executing: [powershell -NoProfile -Command &{ $(Get-WmiObject Win32_Processor) | ConvertTo-json -Depth 1 }]"
time="2021-11-05T11:41:21Z" level=info msg="Executing: [powershell -NoProfile -Command &{ $(Get-WmiObject Win32_BaseBoard) | ConvertTo-json -Depth 1 }]"
time="2021-11-05T11:41:22Z" level=info msg="Executing: [powershell -NoProfile -Command &{ Get-Item 'Registry::HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion' }]"
time="2021-11-05T11:41:23Z" level=info msg="Executing: [powershell -NoProfile -Command &{ Get-MpComputerStatus }]"
time="2021-11-05T11:41:25Z" level=info msg="Executing: [powershell -NoProfile -Command &{ $PSVersionTable }]"
time="2021-11-05T11:41:26Z" level=info msg="Gathering ProcessGatherer" type=list
time="2021-11-05T11:41:26Z" level=info msg="Gathering tasklist /V" type=list
time="2021-11-05T11:41:26Z" level=info msg="Executing: [tasklist /V]"
time="2021-11-05T11:41:27Z" level=info msg="Gathering Get-Process | Select-Object Handles,Name,NPM,PM,SI,VM,WS | ConvertTo-Json -Depth 1 (timeout 1m30s)" type=list
time="2021-11-05T11:41:27Z" level=info msg="Executing: [powershell -NoProfile -Command &{ Get-Process | Select-Object Handles,Name,NPM,PM,SI,VM,WS | ConvertTo-Json -Depth 1 }]"
time="2021-11-05T11:41:28Z" level=info msg="Gathering Get-Service | ConvertTo-Json -Depth 1 (timeout 0s)" type=list
time="2021-11-05T11:41:28Z" level=info msg="Executing: [powershell -NoProfile -Command &{ Get-Service | ConvertTo-Json -Depth 1 }]"
[SKIP] DD0018: does the host support virtualization?
time="2021-11-05T11:41:30Z" level=info msg="Gathering Get-WindowsOptionalFeature -Online | ConvertTo-Json (timeout 45s)" type=list
time="2021-11-05T11:41:30Z" level=info msg="Executing: [powershell -NoProfile -Command &{ Get-WindowsOptionalFeature -Online | ConvertTo-Json }]"
2021/11/05 11:41:33 exit status 0xffffffff`

Also, the Support feature of the Desktop App is also broken, being unable to perform the diagnostic and returning the message 

`"Cannot process diagnostics. Reason:" Error invoking remote method 'desktop-go-backend': Error: {"message":"Internal Server Error"}`

### Information

  - Windows Version: Windows 10
  - Docker Desktop Version: Docker version 20.10.8, build 3967b7d
  - WSL2 or Hyper-V backend? Not sure.
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Yes, in VMWare Player

### Steps to reproduce the behavior

See above.

**Comment by Ogulcan-Ozdemir** [comment]
Hi I am facing same issue. However I am running Windows directly my machine not in VM and wsl2 docker backend has been activated.
