### ISSUE TITLE
Docker Desktop Engine fails to start

### ISSUE THREAD

**Issue by marco3479** [docker/for-win#12347]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:  AA0A98E8-8C88-48DD-9B8F-8D40DAFB8A37/20211105132704 (uploaded)

### Actual behavior
The Docker Desktop fails to start.

### Expected behavior
Docker Desktop should start.

### Information

  - Windows Version: Windows 10.0.19043
  - Docker Desktop Version: 4.1.1
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: virtualized Windows

### Steps to reproduce the behavior

  1. Install
  2. Try to run
  3. Fails to run

**Comment by soroshsabz** [comment]
ITNOA

this problem is very common, and unfortunately Docker does not fix it.

related #12066 
related #12346 
related #12158 
related #12270
