### ISSUE TITLE
Feature request: suppress "Welcome" dialog on startup

### ISSUE THREAD

**Issue by domenic** [docker/for-win#1234]
### Expected behavior

When I boot up my computer, it doesn't contain popups telling me about things I've set it to run in the background.

### Actual behavior

I get a very large popup explaining that "Docker is now up and running!" and that I can "Open your favorite terminal and start typing Docker commands." and "Discover Docker Cloud Services" and so on. This is annoying and not helpful; I just want a nice background service that doesn't get in my way.

### Information

Windows Fall Creators Update

### Steps to reproduce the behavior

1. Install Docker for Windows
2. Restart your computer
3. See dialog; be frustrated
4. Repeat steps 2-3 indefinitely for your entire Docker-using career

**Comment by jasonbivins** [comment]
Hi @domenic   This is entered in already as a pending enhancement request - I went ahead and updated the existing one with your comments.  Thanks!
