### ISSUE TITLE
Error grabbing logs: EOF

### ISSUE THREAD

**Issue by whitecolor** [docker/for-win#1235]
OS: Windows 10 WSL (Ubuntu)
Docker for windows: Version 17.09.0-ce-win33 (13620)
Compose `1.17.0-rc1` / `1.16.1` (installed on WSL)

When starting containers **periodically** get the error `Error grabbing logs: EOF`
![image](https://user-images.githubusercontent.com/736697/31863834-1a03b5f2-b708-11e7-912b-97b0c1bc381c.png)

Any suggestions what may be the problem?

There is a like issue in docker for mac https://github.com/docker/for-mac/issues/1984

**Comment by friism** [comment]
Do you have a testcase (docker image / Dockerfile / docker-compose.yml) that we can use to reproduce the problem?

**Comment by whitecolor** [comment]
Unforchinatly no, It is a fluent error. And it started to happen after the update to latest docker-for-win.

Here is a message in docker engine:
https://github.com/moby/moby/blob/147443a42665419d8b3c2047a7d345440bfb63c0/api/server/httputils/write_log_stream.go#L43

I thought maybe there are some clues what should be wrong for this message to appear.

**Comment by whitecolor** [comment]
Forget to mention this error happens on following command `docker-compose logs --tail 10 --follow [services]` just after `docker-compose up -d [services]` executed, so maybe this is just because service didn't make it start yet?

**Comment by shin-** [comment]
@whitecolor FWIW, other reports[1][2] of the same message seem to suggest it's an issue with the `--tail` flag specifically. A possible workaround for the time being might be to avoid using that option.



[1] https://github.com/dokku/dokku/issues/2898
[2] https://github.com/chainpoint/chainpoint-node/commit/73170a57a42242e157c798e64a6de202be3720c6

**Comment by whitecolor** [comment]
@shin- Ok, thanks for the notice. Isn't there any specific issue to track this?

**Comment by shin-** [comment]
To my knowledge you are the first one to actually report it upstream.

**Comment by whitecolor** [comment]
So should I create an issue in [moby](https://github.com/moby/moby/issues) or where?

**Comment by whitecolor** [comment]
This actually happens to me even without `--tail` flag.

**Comment by alex73630** [comment]
I've got the same issue after starting a container based on `debian:8` that compile an nginx server then start it.
I tried to build it on Windows 10 (using docker-machine instead of the default daemon) and on a Debian 9 VM using the latest version of Docker and Docker Compose and both are returning `Error grabbing logs: EOF`
Here is a Gist with some code on how my docker-compose is setup : https://gist.github.com/alex73630/8f77e35c0257ef86886a381ee7a84ee2

**Comment by alex73630** [comment]
After some testings, it appears that Docker send this error if I try to start my nginx as a service without sending anything in the bash console.
Set nginx to stay in foreground and `echo`-ing something prevent the error to be sent and my container stays up and working.
This is my CMD line that allows my container to work
`CMD echo "Starting nginx." && ./sbin/nginx -g 'daemon off;'`
`-g 'daemon off;'` sets nginx to run in foreground.

**Comment by andyneff** [comment]
I'm having this problem too, and I'm using Linux

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:49 2017
 OS/Arch:      linux/amd64
 Experimental: false

docker-compose version 1.17.0-rc1, build a0f95af
docker-py version: 2.5.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```


If I `logs` just the one container, when I restart it `docker-compose logs` just disconnects (ends). However, if I `docker logs` on multiple containers, that's when I get `Error grabbing logs: EOF`

**Confirmed** if I don't used `--tail`, it all works. However, I'm logging many dockers, some of which have thousands of lines stored.

I'm not able to reproduce it with a simple `declare -i x=0; while :; do echo $$x; sleep 1; x+=1; done` container, but my actual setup reproduces it every time.

**Comment by grofit** [comment]
I got this issue when using Kitematic with docker for windows.

**Comment by dagnelies** [comment]
Got the same problem here, sporadically.

**Comment by thaJeztah** [comment]
Sounds like this may be fixed through https://github.com/moby/moby/pull/36305 (it's not in a release yet)

**Comment by andyneff** [comment]
Confirmed, appears to be working in windows with docker 18.06.1, docker-compose 1.22.0.

When I restart multiple containers, as long as I don't restart all of them, it appears to work correctly. When restarting all containers, `docker-compose logs` disconnects (ends).
