### ISSUE TITLE
Switch to XXX containers menu item contains ellipses, but does not wait for further user input

### ISSUE THREAD

**Issue by grydholt** [docker/for-win#1236]
### Expected behavior
Any menu item ending in ellipses must wait for user confirmation as per https://msdn.microsoft.com/en-us/library/windows/desktop/dn742392(v=vs.85).aspx
### Actual behavior
The 'Switch to XXX containers...' menu item performs the switch immediately.
### Information

  - 2017-10-05 17.09.0-ce-win33 "17.09.0-ce-win33"
  - Windows 10 Pro

### Steps to reproduce the behavior

  1. Select the 'Switch to Windows containers...'
  2. The action is immediately performed.

**Comment by jasonbivins** [comment]
Hi @grydholt  I entered this in as an enhancement request for you, I'll go ahead and close this one out.

Thanks!

**Comment by nlwillia** [comment]
Just to beat the horse a bit further...  If you don't already have the necessary Windows components installed, Docker then wants to do something that it warns might restart automatically.  If you cancel this, then Docker exits.  To get back to Linux you have to ignore the popup and click Switch to Linux in the context menu which is not at all intuitive.  So via accidental click or curiosity you can go from having a working setup to a broken one or need to reboot.
