### ISSUE TITLE
Win11 Double-clicking on the docker installer will report an error: Unable to load DLL 'msi.dll': Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))...

### ISSUE THREAD

**Issue by xBLACKICEx** [docker/for-win#12362]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version: Windows 11 Pro Insider Preview 22499.1000
  - Docker Desktop Version: Docker Desktop 4.2.0(70708)
  - WSL2 or Hyper-V backend?  wsl2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

![image](https://user-images.githubusercontent.com/51036094/141389478-12a5fda3-9d30-4f35-8b89-ed2976c8e64d.png)

https://user-images.githubusercontent.com/51036094/141388636-3b7b3110-556b-43fc-9fca-ee815e0ddf5f.mp4
---
I have this problem when I double-click to start, and I don't know if it's a Windows(I've tried updating windows but still have this problem.) or Docker Desktop issue. Here to report it.

By the way I successfully installed and started a container later.

**Comment by nganivet** [comment]
+1, having the same issue.

**Comment by sergey-v9** [comment]
I had the same error.
Accidentally I had a folder named `MSI.dll` in my download directory (from which I've launched the Docker installer). Deleting this folder did the solution. (actually, that was me created that folder times ago)

You could check all the paths from which DLL loader tries to load files - maybe it has unnecessary items with the name `msi.dll.`

**Comment by nganivet** [comment]
@sergey-v9 nice find ... alas did not work for me: same error when installing from an empty folder. I however was successful launching the installer as an Administrator (rather than launching as normal and accepting the elevated privilege prompt).

**Comment by wanmaoor** [comment]
try to run it as administraor
