### ISSUE TITLE
Docker desktop stuck at "Docker engine is starting"

### ISSUE THREAD

**Issue by rassasamine** [docker/for-win#12369]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F765CB11-D57A-43BF-A758-CCB88C58A2C0/20211115112034

### Actual behavior
Docker desktop stuck at "Docker engine is starting".

![Screenshot 2021-11-15 123901](https://user-images.githubusercontent.com/25062510/141776881-c8082931-731c-4626-b508-e79f0fb6a4ab.png)
![Screenshot 2021-11-15 123712](https://user-images.githubusercontent.com/25062510/141776632-10155350-293e-4474-9f07-aa4538eaf2a5.png)
![Screenshot 2021-11-15 123746](https://user-images.githubusercontent.com/25062510/141776634-51a2ed9f-2865-4744-813f-ccf12e1ef1b7.png)

### Expected behavior
Docker should start successfully.

### Information
  - Is it reproducible? not sure.
  - Is the problem new? yes.
  - Did the problem appear with an update? yes, after windows latest update.
  - Windows Version: windows 11 pro version 21H2 (build 22000.318)
  - Docker Desktop Version: 4.2.0
  - WSL2 or Hyper-V backend?   WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior
Start Docker Desktop.

**Comment by pranavgvrk** [comment]
Facing similar issue on Windows 10 20H2.
This problem is appearing after 4.2.2 update
Diagonastics ID: DB18B431-81AB-443C-8513-0E3BE3C60770/20211119070234

**Comment by Andi1217** [comment]
I had the same issue. For me setting the wsl-Version to 2 helped, at least for now:

wsl --set-default-version 2
Net stop com.docker.service
Net start com.docker.service

Somehow it might got changed back to wsl 1?

**Comment by ggirard07** [comment]
Same issue on my side. Fixed it by updating WSL from `5.4.72` to `5.10.60.1`.
Run `wsl --update` from an elevated command prompt.

**Comment by barasimumatik** [comment]
Thanks @ggirard07! This was driving me crazy 😄

My version of Docker Desktop (4.3.1) was just stuck on starting (never failed). Essentially unresponsive.

I killed all Docker-related processes with the Task Manager and updated wsl like @ggirard07 suggested, and after `wsl --shutdown` and starting Docker Desktop it worked. 

I use WSL2 and while I don't know the kernel version I had, the current (`5.10.60.1`) seems to do the trick!

**Comment by sreepriyadeepak2021** [comment]
The solution work for both Docker starting and Docker stopping issues. I updated wsl to 5.10.102.1
