### ISSUE TITLE
Docker Desktop 4.2.0 (70708): vi stuck, not working

### ISSUE THREAD

**Issue by 4lkaid** [docker/for-win#12360]

**Comment by soroshsabz** [comment]
Please add more details

**Comment by 4lkaid** [comment]
Enter the container and use vi to open any file, it will be stuck, as follows:
![图片](https://user-images.githubusercontent.com/24668096/141421371-0d94f9d5-e7da-4278-a5c5-94b58786e2aa.png)
![图片](https://user-images.githubusercontent.com/24668096/141421442-2e9253f0-46e7-4d1a-81c7-166ca4a78351.png)
If vim is installed, using vim to open any file is also like this
