### ISSUE TITLE
How to fix it?

### ISSUE THREAD

**Issue by dinhduc2402** [docker/for-win#12364]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by thaJeztah** [comment]
Please provide the information that's requested in the issue template when submitting a ticket.

I'll close this ticket, because no details were provided.
