### ISSUE TITLE
Docker Engine won't start | Failed to set version to docker-desktop: exit code: -1

### ISSUE THREAD

**Issue by lenzmaxi** [docker/for-win#12375]
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 7353D6F0-7D32-45F1-9C72-72AB4E2C8AAA/20211116073317

### Actual behavior
Docker Engine will not start and displays following error message: 
System.InvalidOperationException:
Failed to set version to docker-desktop: exit code: -1
 stdout: The attempted operation is not supported for the type of object referenced.

### Expected behavior
Docker Engine starts

### Information
I had Docker installed (working) for a couple of weeks. Now I need it again and it won't start. Reinstalled it multiple times. I tried enabling WSL and the Pathvariables are fine aswell.
  - Windows Version: 10.0.19043
  - Docker Desktop Version: 4.2.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Steps to reproduce the behavior

  1. start Docker
  2. ...

**Comment by delsoft** [comment]
same error here
