### ISSUE TITLE
Docker issue

### ISSUE THREAD

**Issue by shankarajmeera** [docker/for-win#12372]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by shankarajmeera** [comment]
docker issue

**Comment by mattwelke** [comment]
Need more details added to this issue. You should answer the questions in the template you used.

**Comment by thaJeztah** [comment]
yes, let's close this one
