### ISSUE TITLE
Installed docker for desktop , docker engine not starting

### ISSUE THREAD

**Issue by Zuleikha** [docker/for-win#12378]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3CF295F6-5709-463F-94D3-4EE9B63398B1/20211116161344

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by soroshsabz** [comment]
ITNOA

I have the same problem

related to #12066 
related to #12158 
related to #12270

**Comment by soroshsabz** [comment]
@Zuleikha Please answer the template questions
