### ISSUE TITLE
Docker Desktop not starting up after windows 10 update to 21H1

### ISSUE THREAD

**Issue by sreenath-dressler** [docker/for-win#12382]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:  3FAA7B6C-A1E5-4949-BBBC-5AC2B2278972/20211117054314

### Actual behavior
Docker desktop not starting up
### Information

  - Windows Version: 10 21H1
  - Docker Desktop Version: Docker version 20.10.2, build 2291f61
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. The docker desktop application crash with error unable to start

**Comment by Gabriellavoura** [comment]
Same issue.

### Information
   * Windows Version: 10.0.19044 Build 19044
   *  Docker Desktop Version:  20.10.10, build b485636
   *  WSL2 or Hyper-V backend? WSL2
   *  Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

Error message:
Docker failed to initialize
Cancellation token triggered before we finished reading from the stream.

**Comment by waqas-ali-pk** [comment]
Same issue. 

Windows update  **10 21H1** is devil here. 👎
