### ISSUE TITLE
Docker Desktop for Windows Update 4.1.1 Uninstalled Docker and Wiped Out My Containers

### ISSUE THREAD

**Issue by kk-sdsu** [docker/for-win#12388]
- [ x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Docker Uninstalls
### Expected behavior
Docker should have updated...
### Information
 N/A
  - Windows Version: Version	10.0.19042 Build 19042
  - Docker Desktop Version: unknown for certain, but likely was 4.1.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No, running on a Surface Book 2

### Steps to reproduce the behavior
  1. Let Docker Desktop perform an update
  2. Docker uninstalls itself instead

**Comment by kk-sdsu** [comment]
I reinstalled docker with version 4.1.1 then upgraded to 4.2.0 and it found all of my containers again. So just in case this happens to others you may not be completely SOL.

**Comment by StefanScherer** [comment]
Thanks. I'm glad you have your containers back. I'm closing this ticket.
