### ISSUE TITLE
How to disable gRPC?

### ISSUE THREAD

**Issue by GF-Huang** [docker/for-win#12384]
It breaks my mysql container. I can't start my database anymore, so I can't backup/export my data.

references: 
- [Mysql not starting in a docker container on MacOS after docker update](https://stackoverflow.com/a/64150016/3907561)
- https://github.com/laradock/laradock/issues/2732#issuecomment-722479614

![image](https://user-images.githubusercontent.com/4510984/142242195-3859f4dd-161d-44d9-9cd1-354e5db096fe.png)

![image](https://user-images.githubusercontent.com/4510984/142242237-79c4c68e-1636-48de-aa6a-f7c2c1cfcf62.png)

![image](https://user-images.githubusercontent.com/4510984/142242305-04fe45ae-23f2-4ce7-a9cc-87b3cc991c9e.png)

# MySQL container logs:

```
2021-11-17T16:31:46.877808Z 0 [Warning] [MY-010159] [Server] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive

2021-11-17T16:31:49.554236Z 1 [ERROR] [MY-011087] [Server] Different lower_case_table_names settings for server ('2') and data dictionary ('0').

2021-11-17T16:31:49.554506Z 0 [ERROR] [MY-010020] [Server] Data Dictionary initialization failed.

2021-11-17T16:31:49.554792Z 0 [ERROR] [MY-010119] [Server] Aborting
```

**Comment by yanwuguangjun** [comment]
same question

**Comment by yanwuguangjun** [comment]
mysql its can't work   fixit hurry hurry

**Comment by GF-Huang** [comment]
I found what cause this issue. Before upgrade, I use Hyper-V Linux container as backend which is Linux file system, the MySQL 8 initialize the `lower_case_table_names` parameter with `0` at Linux/Unix by default. After upgrade, I use WSL2 as backend, which is Windows file system, and Windows file system is **case insensitive**, this is the opposite of Linux file system. At Windows file system, MySQL need to set `lower_case_table_names` to `2`, so this creates a conflict.

# Solution
Change the MySQL mounted folder to **case sensitive**, in my case volumes is `./data/dbdata:/var/lib/mysql`, so I navigate to `dbdata` folder in command line, then run `fsutil.exe file setCaseSensitiveInfo ./ enable`, done. Try again to launch your MySQL container, it should be work. 

Hope this help you.

Notes:
You can run `fsutil.exe file setCaseSensitiveInfo ./ disable` to turn it back to **case insensitive**, and `fsutil.exe file queryCaseSensitiveInfo ./` to query the case sensitive info.

references: 
- https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_lower_case_table_names
- https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html
