### ISSUE TITLE
my mysql   can't run   after  update

### ISSUE THREAD

**Issue by yanwuguangjun** [docker/for-win#12386]
my mysql   can't run   after  update

log`

mysql-srv           | 2021-11-18T04:35:13.552434Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
mysql-srv           | 2021-11-18T04:35:13.557872Z 1 [ERROR] [MY-011087] [Server] Different lower_case_table_names settings for server ('2') and data dictionary ('0').
mysql-srv           | 2021-11-18T04:35:13.558069Z 0 [ERROR] [MY-010020] [Server] Data Dictionary initialization failed.
mysql-srv           | 2021-11-18T04:35:13.558239Z 0 [ERROR] [MY-010119] [Server] Aborting
mysql-srv-dongjiao  | 2021-11-18T04:35:13.900647Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.27)  MySQL Community Server - GPL.`

**Comment by yanwuguangjun** [comment]
use  this  version to use

**Comment by dreamfalcon** [comment]
Same problem here with several services:
Docker is reserving several ports on the 3xxx range:

`netsh int ipv4 show excludedportrange protocol=tcp

Protocol tcp Port Exclusion Ranges

Start Port    End Port
----------    --------
      1587        1686
      1687        1786
      1787        1886
      1887        1986
      1987        2086
      2180        2279
      2468        2567
      2568        2667
      2702        2801
      2802        2901
      2902        3001
      3002        3101
      3307        3406
      3407        3506
      5357        5357
      5985        5985
     47001       47001
     50000       50059     *`

**Comment by avalanchus** [comment]
The same problem 
Docker Desktop 4.2.0 (70708)
for the umpteenth time I scold myself for not turning off auto-update, the second time I come across a raw version of docker
