### ISSUE TITLE
Hyper-v and dockerdesktopvm still maintained?

### ISSUE THREAD

**Issue by icsy7867** [docker/for-win#12389]
Random (hopefully) quick question.

My org doesn't allow WSL/WSL2 for security and we have a lot of users using docker desktop with WSL2 enabled.  We are trying to figure out the best alternatives.

The online docs don't talk about the Hyper-v backend much (at least the tab that says Hyper-v and windows containers is misleading to me).  However it looks like the hyper-v backend seems reasonable.  Alternatively we will most likely just get the users to setup an Ubuntu or rhel VM and run docker that way (although this does remove the nice gui).

However someone mentioned on Reddit that the Hyper-v backend virtual machine is no longer maintained or updated.  Is there any truth to this?  If the DockerDesktopVM is EOL that is even more reason to go to a dedicated Linux VM.  If so I was hoping there was some documentation to this effect.  Im one of the sysadmins who unfortunately has to enforce out policies and documentation could go a long way.

**Comment by stephen-turner** [comment]
Thanks for the question. This is not the case. The default is WSL 2 because it's more performant but the Hyper-V backend is still maintained too.

I would be interested in what security concerns you have with WSL 2 compared to a VM.

**Comment by icsy7867** [comment]
Great to hear!  WSL2 is forbidden per policy above my head.  But I believe the biggest transgression is that WSL2 bypasses the windows firewall which makes a lot of people nervous from an IT standpoint.

However, Im having multiple conversations across the organization about options. I appreciate your reply!

But I have another question.  Because of several fairly complex requirements, even our virtual machines require fairly strict compliance.  I am also working on configuring an ubuntu VM.  I have enabled the docker engine tcp to docker socket, And successfully deployed containers to this VM from docker desktop using the DOCKER_HOST environment variable.  However docker desktop is still starting/deploying the "DockerDesktopVM" and checking and relying on this VM to start.

Is there any documentation on setting up an alternate host to use with docker desktop?

**Comment by stephen-turner** [comment]
Replied in docker/for-win#12397
