### ISSUE TITLE
Docker EE on Server 2019 and LCOW with Transparent Networking

### ISSUE THREAD

**Issue by mastertIT** [docker/for-win#12385]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: docker EE does not have this feature

### Actual behavior
` docker container start krill
Error response from daemon: container f92fc773c09c9c5e1a99af70289b34138debf76b28d92e3687a523bca7e54734 encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: Unspecified error (0x80004005)
[Event Detail: failed to link resolv.conf file for adapter e9d45d47-37c9-40ca-ad54-f76de5427e86: link /etc/resolv.conf /tmp/base/etc/resolv.conf: invalid cross-device link Stack Trace:
github.com/Microsoft/opengcs/service/gcs/oslayer/realos.(*realOS).Link
        /go/src/github.com/Microsoft/opengcs/service/gcs/oslayer/realos/realos.go:232
github.com/Microsoft/opengcs/service/gcs/core/gcs.(*gcsCore).configureAdapterInNamespace
        /go/src/github.com/Microsoft/opengcs/service/gcs/core/gcs/networking.go:57
github.com/Microsoft/opengcs/service/gcs/core/gcs.(*gcsCore).ExecProcess
        /go/src/github.com/Microsoft/opengcs/service/gcs/core/gcs/gcs.go:369
github.com/Microsoft/opengcs/service/gcs/bridge.(*Bridge).execProcess
        /go/src/github.com/Microsoft/opengcs/service/gcs/bridge/bridge.go:585
github.com/Microsoft/opengcs/service/gcs/bridge.(*Bridge).(github.com/Microsoft/opengcs/service/gcs/bridge.execProcess)-fm
        /go/src/github.com/Microsoft/opengcs/service/gcs/bridge/bridge.go:236
github.com/Microsoft/opengcs/service/gcs/bridge.HandlerFunc.ServeMsg
        /go/src/github.com/Microsoft/opengcs/service/gcs/bridge/bridge.go:68
github.com/Microsoft/opengcs/service/gcs/bridge.(*Mux).ServeMsg
        /go/src/github.com/Microsoft/opengcs/service/gcs/bridge/bridge.go:139
github.com/Microsoft/opengcs/service/gcs/bridge.(*Bridge).ListenAndServe.func2.1
        /go/src/github.com/Microsoft/opengcs/service/gcs/bridge/bridge.go:315
runtime.goexit
        /usr/lib/go/src/runtime/asm_amd64.s:2361 Provider: 00000000-0000-0000-0000-000000000000]
Error: failed to start containers: krill`

### Expected behavior
successfully connecting and starting container with transparent network
### Information

  - Windows Version: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.2300)
  - Docker Desktop Version: Server Version: 20.10.8 Storage Driver: windowsfilter (windows) lcow (linux)
  - WSL2 or Hyper-V backend?  HyperV
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Yes (vSphere 7 SSE4.2)

### Steps to reproduce the behavior

  1. ...configure docker to run in LCOW Hyperv backed mode
  2. ...run linux container with transparent network

**Comment by mastertIT** [comment]
#3596

**Comment by mastertIT** [comment]
#1492

**Comment by stephen-turner** [comment]
This bug tracker is only for Docker Desktop. Docker EE is now owned by Mirantis not Docker Inc.
