### ISSUE TITLE
"Docker Engine starting" hangs when Upgrading from 4.1.1 to 4.2.0

### ISSUE THREAD

**Issue by ManfredLange** [docker/for-win#12390]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics => I'd love to upload diagnostics, but this feature is broken, too.
  - Diagnostics ID: No available because that feature is broken as well. Clicking the button "Upload to get a Diagnostic ID" does not lead to displaying a diagnostics ID.

### Actual behavior

After upgrading from Docker Desktop version 4.1.1 to version 4.2.0 Docker displays a message "Docker Engine starting" but never finishes.

While "Diagnosing..." completes, clicking the button "Upload to get Diagnostic ID" appears to be without function, so is broken, too.

### Expected behavior

Docker should just start and not hang after upgrade.

Clearly, this has been a recurring problem for several upgrades now with little to no progress.

### Information

  - Windows Version: Wndows 10 Pro, Version 10.0.19042 Build 19042
  - Docker Desktop Version: 4.2.0
  - WSL2 or Hyper-V backend? WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

1. Install Docker Desktop for Windows 4.1.1
2. Upgrade to Docker Desktop for Windows 4.2.0
3. => "Docker Engine starting" hangs

### Additional Information:

I ran the self-diagnose tool *after* the upgrade and the relevant result is:

```
[FAIL] DD0032: do Docker networks overlap with host IPs? network acme_acme has subnet 172.19.0.0/16 which overlaps with host IP 172.19.240.1
```
Interestingly, the network `acme_acme` was created by Docker Desktop versoin 4.1.1 prior to the upgrade, so the virtual network was created by Docker and the IP address was assigned by Docker when I started a container and Docker picked some foldername as the name for the application and network, hence `acme_acme`.

The host IPv4 address is 192.168.86.63. However, `ipconfig` reports an IPv4 address of 172.19.240.1 for WSL and this does in fact overlap with the IP address that Docker assigned to the network `acme_acme`. So the failed test of the self-dignose tool is correct. However, it's an issue created by Docker itself which should be handled by the upgrade process, i.e. either by fixing the IP address range for the virtual network in Docker (`acme_acme` in this case) during the upgrade or by rolling back the upgrade and providing instructions to remove any virtual networks prior to upgrading.

I'll try the workaround that usually worked in the past by completely removing Docker then installing version 4.2.0. I'll report findings here.

**Comment by ManfredLange** [comment]
Uninstalling version 4.2.0 via "Add/Remove Programs", then re-installing fresh doesn't work either and leads to the same result.

**Comment by ManfredLange** [comment]
Stopping WSL with `wsl --shutdown` then starting Docker Desktop once more has fixed the problem in my environment.

This is was the sequence I used:
1. Docker Desktop version 4.1.1 was installed
2. Upgrade to Docker Desktop version 4.2.0 => starting engine hangs
3. Uninstall version 4.2.0
4. Reinstall version 4.2.0 => starting engine hangs
5. `wsl --shutdown`
6. Docker continues automatic start as part of step 4
7. all images, containers, volumes, virtual networks are gone

There was no reboot of Windows in this process. I did restart WSL2, though, in step 5.

**Comment by ManfredLange** [comment]
Nope, still not fixed. Now I'm getting the error message 

```
The command docker' cannot be found in this WSL2 distro.
```

Clearly, the upgrade process is broken.

**Comment by ManfredLange** [comment]
This following recipe appears to work:

1. Before upgrading remove all Docker resources, i.e., images, containers, virtual networks, volumes, etc. using the command `docker system prune`
2. Uninstall current version of Docker Desktop for Windows
3. Stop WSL using command `wsl --shutdown`
4. Install desired version of Docker Desktop for Windows

Having spent at least half an hour each time there was an upgrade in the last several months, I won't use the upgrade process going forward. As I see it, it's simply broken. The feature should be removed and only re-added once rigourous testing ensures that it works reliably.

Note, this is just my experience. I can't speak for others. If upgrading works for you, fantastic!

**Comment by maxwellhertz** [comment]
This also happened to me and I had to uninstall v4.2.0 then reinstall the previous version. It totally sucks😒.

**Comment by fishmi** [comment]
Unfortunately the same problem with me, Docker startup ends with an error message on Windows 10.
I uninstalled Docker several times, deleted all files that obviously belonged to Docker. Executed the from Manfredlange recommended commands.

Error message after waiting about 5 minutes:
--------------------------------------------------------------------------------------------------
System.TimeoutException:
Timeout für den Vorgang wurde überschritten.
   bei System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
   bei System.Threading.Tasks.Task.Execute()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei HttpOverStream.NamedPipe.NamedPipeDialer.<DialAsync>d__8.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei HttpOverStream.Client.DialMessageHandler.<SendAsync>d__9.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Docker.Core.IPC.Client.<SendAsync>d__5.MoveNext() in C:/workspaces/master-merge/src/github.com/docker/pinata/win/src/Docker.Core/IPC/Client.cs:Zeile 37.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Docker.Core.HttpClientExtensions.<GetJsonAsync>d__0`1.MoveNext() in C:/workspaces/master-merge/src/github.com/docker/pinata/win/src/Docker.Core/HttpClientExtensions.cs:Zeile 16.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Docker.ApiServices.LifecycleClient.<GetDockerStateAsync>d__4.MoveNext() in C:/workspaces/master-merge/src/github.com/docker/pinata/win/src/Docker.Engines/LifecycleClient.cs:Zeile 49.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei Docker.Engines.LinuxkitDaemonStartup.<WaitAsync>d__5.MoveNext() in C:/workspaces/master-merge/src/github.com/docker/pinata/win/src/Docker.Engines/LinuxkitDaemonStartup.cs:Zeile 60.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__29.MoveNext() in C:/workspaces/master-merge/src/github.com/docker/pinata/win/src/Docker.Engines/WSL2/LinuxWSL2Engine.cs:Zeile 190.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:/workspaces/master-merge/src/github.com/docker/pinata/win/src/Docker.ApiServices/StateMachines/TaskExtensions.cs:Zeile 29.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:/workspaces/master-merge/src/github.com/docker/pinata/win/src/Docker.ApiServices/StateMachines/StartTransition.cs:Zeile 67.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:/workspaces/master-merge/src/github.com/docker/pinata/win/src/Docker.ApiServices/StateMachines/StartTransition.cs:Zeile 92.

I hope this helps to isolate the problem.

**Comment by fishmi** [comment]
I'm now back to 4.1.1 and then nothing worked.
The reason was the missing path variable on system32. After I have added this 4.1.1. works.
Let's see if I still update now.

**Comment by ManfredLange** [comment]
@fishmi Interesting: Error messages in German. Not very helpful as it makes searching for resolutions much harder.

In the past the following recipe (different to above) helped in some cases of Docker upgrade issues as well:
1. Uninstall Docker
2. Reboot Windows
3. Install desired version of Docker
4. Reboot Windows
5. Start Docker (unless it automatically starts)

Another practice that I started was keeping the installer within reach from the working version, i.e. "last known good". Having this and the installer of the desired version downloaded already, speeds up the process somewhat.

Going forward I'm likely to just uninstall the current version, reboot, then install the newer version. It's costing me between 30 minutes and an hour to fix a screweed up upgrade. Unistall, reboot, install is - although annoying - just a few minutes.

I acknowledge that dealing with both Windows and WSL(2) in an installer is a big challenge for any tool, Docker included. However, I'm hoping that eventually the upgrade process still becomes more reliable. After all, isn't an upgrade nothing more than a shortcut for the uninstall-install cycle?

**Comment by berney** [comment]
Classic Docker for Win, every new release for the last 3 or so for me has hit some bug where its broken, won't start, and need to uninstall/reinstall clean to get Docker working again. https://github.com/docker/for-win/issues/12229 was the last one I hit. This time I searched for bugs before blindly updating, think I'll wait for 4.2.1 if they don't force the update (and breakage) on me.

**Comment by shasderias** [comment]
Encountered a similar issue when upgrading to 4.2.0 - Docker Engine hanging on start-up with "Docker Engine starting".

Fortunately, an abbreviated version of ManfredLange's workaround worked:
(1) Close Docker Engine
(2) Execute ```wsl --shutdown```
(3) Restart Docker Engine

All containers, networks and volumes appear to be intact.

Thanks ManfredLange, saved me at least an hour >.>

**Comment by johanvanhelden** [comment]
Can anyone confirm if this is still an issue in 4.3.2? For now I am stuck on 4.1 until this is resolved.

**Comment by ManfredLange** [comment]
It seems that the combination of the Windows host, WSL2 and Docker is a huge challenge for getting the upgrade process rock-solid. I just went through another update "experience" from version 4.3.1 to 4.3.2 and reported an issue and its resolution here: https://github.com/docker/for-win/issues/12463 

My suspicion is that each of the three elements (host, WSL2 and Docker) can be in different states throughout the upgrade process.

For the time being I am no longer using the upgrade process. Instead I completely uninstall my current Docker version, then restart WSL2 (all distros!) and if needed even the host. Only once I'm satisfied that it's now in a non-Docker "state", I attempt installing the new Docker version. It's more time consuming but it certainly beats spending an hour on resolving a stuffed up Docker installation.

@johanvanhelden  While certainly not guaranteed, the recipe I added for resolving the issue I observed may help in your case, too. That recipe can be found here: https://github.com/docker/for-win/issues/12463#issuecomment-1000589220 . Effectively, it mirrors what @shasderias has shared in his comment above.

**Comment by allenyllee** [comment]
> Can anyone confirm if this is still an issue in 4.3.2? For now I am stuck on 4.1 until this is resolved.

@johanvanhelden I can confirm that update from 4.1.0.0 to 4.5.1 (74721) through update process is OK, no need to uninstall current version. But try at your own risk.

wsl kernel version: 5.10.60.1

**Comment by johanvanhelden** [comment]
> > Can anyone confirm if this is still an issue in 4.3.2? For now I am stuck on 4.1 until this is resolved.
> 
> @johanvanhelden I can confirm that update from 4.1.0.0 to 4.5.1 (74721) through update process is OK, no need to uninstall current version. But try at your own risk.
> 
> wsl kernel version: 5.10.60.1

Thanks @allenyllee , I can also confirm everything works flawlessly (4.1 > 4.5.1 without an uninstall)! Finally a stable release. And it seems to start up much faster as well.
