### ISSUE TITLE
System.InvalidOperationException: Failed to set version to docker-desktop: exit code: -1

### ISSUE THREAD

**Issue by NickLi829** [docker/for-win#12395]
- [ x ] I have tried with the latest version of Docker Desktop
  - [ x ] I have tried disabling enabled experimental features
  - [ x ] I have uploaded Diagnostics
  - Diagnostics ID: 7207904B-B6F1-4A06-A868-0E61C9A6EBB4/20211123135919

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. System.InvalidOperationException:
Failed to set version to docker-desktop: exit code: -1
  2. ...

**Comment by NickLi829** [comment]
I fix it by myself
On CMD 
netsh winsock reset

**Comment by StefanScherer** [comment]
Thanks @NickLi829 for reporting back. So it seems it was a hick-up in Windows.
