### ISSUE TITLE
docker network rm NETWORK fails HNS failed with error: The parameter is incorrect

### ISSUE THREAD

**Issue by jcolebrand** [docker/for-win#1239]
docker network create -d transparent --gateway 10.31.0.01 --subnet=10.31.0.0/16 -o com.docker.network.windowsshim.interface="Ethernet" backend

    docker network ls

see it is there

    docker network rm backend

fails with `HNS failed with error : The parameter is incorrect.`

    docker network ls 

only see nat, null

restart docker service

    docker network ls

see a new random network with just the hash for the name (ex: b3631004b54cb3e6c36f004eee21d7a239357e23b84141f6085d37ae048c491d)

try to re-add with the same above command and get that the network already exists

Remove the network now by ID.

can re-add

----

This is on Docker for Windows 
Version 17.09.0-ce-win33 (13620)
Channel: stable
8c56a3b

**Comment by jasonbivins** [comment]
Hi @jcolebrand  I'm setting this up to repro - but had a quick question:  Are you restarting the Docker service, or Docker completely?  Can you provide the specific command or even a screenshot?

**Comment by jcolebrand** [comment]
![screen shot 2017-10-30 at 3 02 53 pm](https://user-images.githubusercontent.com/472825/32192894-8ab53056-bd83-11e7-909f-fcdba31b4f5d.png)

**Comment by jcolebrand** [comment]
@jasonbivins I realized I forgot to say this was on Windows 2016 standard.
