### ISSUE TITLE
In some cases we see fewer files than expected

### ISSUE THREAD

**Issue by Gemorroj** [docker/for-win#12405]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 63E162AC-95CD-4C62-B51A-1C55154AEF83/20211129095423

### Actual behavior
Show only 1 file in directory

### Expected behavior
Show all files in directory (~40)

### Information
In some cases on `docker-win + alpine linux` mc/php/some other soft show fewer files than expected.
Here an example: https://github.com/Gemorroj/php-directoryiterator-bug

  - Windows Version: 10x64 (21H1)
  - Docker Desktop Version: 4.2.0 (70708)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior
```
git clone https://github.com/Gemorroj/php-directoryiterator-bug.git
cd php-directoryiterator-bug
docker-compose up --build --remove-orphans --force-recreate -d
docker-compose exec php sh
php test.php
```
or
```
git clone https://github.com/Gemorroj/php-directoryiterator-bug.git
cd php-directoryiterator-bug
docker-compose up --build --remove-orphans --force-recreate -d
docker-compose exec php sh
apk add mc
cd src/Repository
ls
mc
```

**Comment by StefanScherer** [comment]
Thank you for the report and the repro steps. I am able to reproduce the problem on WSL 2, regardless if I clone the GH repo on Windows and spin it up or do the same inside an Ubuntu distro.

**Comment by Gemorroj** [comment]
still an actual problem
