### ISSUE TITLE
Unable to run Docker on Windows

### ISSUE THREAD

**Issue by SPNAGitHub** [docker/for-win#12404]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Error while trying to launch.

### Expected behavior
To Run without exception

### Information
![DockerError](https://user-images.githubusercontent.com/94884546/143824826-c02d98a2-593e-4394-bb36-ea4c5407b4c0.PNG)

  - Windows Version: **Windows 10 Enterprise**
  - Docker Desktop Version: **4**
  - WSL2 or Hyper-V backend?  : **WSL2**
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: **NO**

**Comment by waqas-ali-pk** [comment]
Facing same issue on Windows 10 professional. Have you found some workaround for this?

**Comment by SPNAGitHub** [comment]
> Facing same issue on Windows 10 professional. Have you found some workaround for this?

Not yet. Working on it.

**Comment by soroshsabz** [comment]
ITNOA

I have the same problem

related to #12066 
related to #12158 
related to #12270
