### ISSUE TITLE
Docker Desktop 4.2.0 Volume DATA view Save As option breaks 

### ISSUE THREAD

**Issue by jsolderitsch** [docker/for-win#12407]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:73F7948D-CD00-4E52-ACBF-A63554AA4A3C/20211129205438

### Actual behavior
I can no longer use the Save As feature from the DATA view of a Docker Volume to export (save as) a file from a Docker container that has the volume associated with it. This behavior started when I had a file path that had a space character in the name. Before I tried this name style, the Save As option from the DATA view worked.

I see a Red Striped error message:

Cannot destructure property 'filepath' of '(intermediate value)' as it is undefined

Now, even when the file path to which I want to Save As the file to does NOT have a space in it, I can't Save as the file. I get the same error message.

### Expected behavior

The Save As option from the Docker Desktop Volume DATA view should work as it did originally. I should not see an error message,

### Information

  - Windows Version: 20H2 (OS Build 19042.1348)
  - Docker Desktop Version: Docker Desktop 4.2.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

Actually, the file path with a space character is not an issue. This is a problem with 4.2.0 in general...

  1. Create a Windows filepath where one of the folders on the path has a space character in the name. (NOT NECESSARY)
  2. Use the Save As... option to try and export a file from a container that has the volume associated with it.
  3. See the error as attached.
  4. 
![Screen Shot 2021-11-29 at 4 09 03 PM](https://user-images.githubusercontent.com/23091236/143943877-bb693159-6e1b-488d-a854-69b6d3bfcaff.png)

**Comment by jsolderitsch** [comment]
I removed my entire Docker Desktop install and then re-installed it and recreated the volume and container where I met the error. I expected that I then could use Save As... again from the Desktop Volume data view as long as there were no space characters on the file path. I was WRONG. I still get the filepath error. WTF.

**Comment by jsolderitsch** [comment]
I am also running Docker Desktop 4.2.0 on my Mac (running Big Sur). This is an Intel Mac Powerbook.

The Save As option was running just fine there from the DATA view of the Volume interface. Now I am getting the same error there too.
<img width="1445" alt="Screen Shot 2021-11-29 at 5 11 38 PM" src="https://user-images.githubusercontent.com/23091236/143950940-ad96c2ab-dd58-47af-b3e5-c88a74faf086.png">

**Comment by jsolderitsch** [comment]
I am no longer sure that a file path with a space character on it is needed to provoke the problem. Perhaps it's version 4.2.0 in general?

**Comment by jsolderitsch** [comment]
On the PC, I reverted to Docker Desktop 4.1.1 and the Save As problem goes away. Even when there is a space character on the path. I am going to change the issue title if I can.

**Comment by jsolderitsch** [comment]
The auto-assigned label is wrong -- it should be version/4.2.0

**Comment by StefanScherer** [comment]
Thanks @jsolderitsch for the report. I can reproduce it even without spaces in the path. We're looking into it.

**Comment by trungutt** [comment]
@jsolderitsch The new release 4.3.0 is out and has a fix with it
