### ISSUE TITLE
Is it not possible to run Linux and Windows docker containers simultaneously?

### ISSUE THREAD

**Issue by jt0dd** [docker/for-win#12415]
Based on [Microsoft's documentation,](https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/run-your-first-container) in order to run a Windows containers:

If you see an error message that says `no matching manifest for linux/amd64 in the manifest list entries`, make sure Docker isn't configured to run Linux containers. To switch to Windows containers in Docker, right-click the Docker icon, and select Switch to Windows containers. To use the command line to switch between containers, run & $Env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchDaemon.

This seems problematic (I just tried it and got the error mentioned) since I want to run a test lab with Windows and Linux boxes interacting on a network. Is docker not capable of this or have I perhaps misunderstood something?

**Comment by StefanScherer** [comment]
Hi @jt0dd thanks for the feedback. We have a roadmap ticket where you can show interest by adding a thumbs up and comment your use case. https://github.com/docker/roadmap/issues/79

I'm going to close this ticket. Thanks.
