### ISSUE TITLE
Windows 11, WSL2 installed via Microsoft Store Preview, Can only run docker-compose using sudo

### ISSUE THREAD

**Issue by Zeebzog** [docker/for-win#12421]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
docker-compose -f <file> up -d --build <subcomponent of docker compose file>

docker-compose takes forever, or hangs on:

[internal] load metadata for docker.io/lbrary/arangodb:3.8.1

For the example I have just run the entire build takes 115.3s

Most of this time is taken on:

[internal] load metadata for docker.io/lbrary/arangodb:3.8.1 115.2s

I have had this up to 900+s and stopped it because of the time taken.

### Expected behavior

If run under sudo:

sudo docker-compose -f <file> up -d --build <subcomponent of docker compose file>

then the build above takes 1.3s

with the [internal] load metadata for docker.io/lbrary/arangodb:3.8.1 taking the 1.3s

### Information

  - Windows Version: Windows 11 Pro vs 10.0.22000
  - Docker Desktop Version: 4.3.0
  - Docker Engine Version: v20.10.11
  - WSL2 or Hyper-V backend?  WSL2, installed by preview on Microsoft store
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No either directly in Ubuntu or from VSCode terminal

### Steps to reproduce the behavior
 Any dockerfile will work

**Comment by HollyIT** [comment]
I can confirm this. Been fighting this problem for a couple of weeks now. Only way to pull or build is by using sudo. I've checked the logs and there are no errors present either.
