### ISSUE TITLE
Cannot connect to Pod IP when windows hns service restarted

### ISSUE THREAD

**Issue by kais271** [docker/for-win#12425]
## Expected Behavior
Connections can be automatically restored.

## Current Behavior
When hns service restarted:
1. The pod still running and hold that IP, but hnsendpoints has been removed and is not automatically re-create.
2. The calico-felix logging 'Failed to look up one or more HNS endpoints; will schedule a retry', and that pod cannot to connect.

## Possible Solution

N/A

## Steps to Reproduce (for bugs)

1.Have k8s windows node and a running pod
2.hnsdiag.exe list endpoints
3.on windows node restart hns service
4.hnsdiag.exe list endpoints
![image](https://user-images.githubusercontent.com/19722587/145150663-7049a098-d45e-49fb-865c-b9df4b894284.png)

## Your Environment

* Calico version: **3.20.2**
* Orchestrator version (e.g. kubernetes, mesos, rkt): **kubernetes v1.21.4**
* Operating System and version: **Windows server 2022**

**Comment by stephen-turner** [comment]
This bug tracker is for Docker Desktop.

**Comment by kais271** [comment]
Add info,
Docker version: Dokcer EE 20.10.7
@stephen-turner Hi sir, how should I track or report this issue ?

**Comment by stephen-turner** [comment]
I believe this is all Microsoft software, but I don't know how they prefer to receive reports.

**Comment by kais271** [comment]
Got it. Thank you so much,
