### ISSUE TITLE
Docker in unusable state / uninstall can't remove VM and Images

### ISSUE THREAD

**Issue by FWI-95** [docker/for-win#12429]
- [ ] I have tried with the latest version of Docker Desktop - cannot do as docker is not functional
  - [ ] I have tried disabling enabled experimental features - cannot do as docker is not functional
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: not possible

![Diagnostics](https://user-images.githubusercontent.com/46918703/145190517-36596f17-f6fc-4c17-9167-66c09331866c.png)

### Actual behavior
Docker is trying to remove VM and Images when uninstalling, but can't so the uninstaller is stuck in this state and docker cannot be reinstalled.

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/46918703/145187008-99c77f4a-577b-41c7-a603-58e6130ac20e.png)

### Expected behavior
Docker uninstalling itself so I can reinstall it.
### Information

I had around 20 containers on my computer where one container wouldn't start anymore. I tried removing it, but the "windowsfilter" error left the container in a dead state. As this happens more often I tried to do my routine to uninstall docker and get a fresh install. So I removed every docker and image with a Powershell Script, which left two containers unremovable.
This time now the uninstaller cant get over the part of removing everything, because I think it has to do with the same error I had before.
Apparently I now can't try to manually remove my containers because my installation is broken and no docker command is executed correctly.

Multiple restarts, docker sevice-restarts and DaemonSwitches didn't fix my problem.

![RemoveContainersFailing](https://user-images.githubusercontent.com/46918703/145187282-1e72c56a-5099-4330-9089-dcb9d314fc5e.png)
(Powershell ISE is in Administrator mode)

![2021-12-08 10_57_10-Process Explorer Search](https://user-images.githubusercontent.com/46918703/145188227-0dfed8a8-5c5b-4918-a0b5-a55d053c585c.png)

"Sandbox" is one layer of the image which is used in the broken container

  - Windows Version: Windows 10 Business Version 2004 (Build 19041.1348)
  - Docker Desktop Version: 4.3.0
  - WSL2 or Hyper-V backend?  Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: physical notebook

**Comment by FWI-95** [comment]
Update: After a few updates more and deactivating "Container" + "Hyper-V" in Windows Features, the wizard was able to uninstall docker. A fresh install is now working correctly.

I don't know if this issue can therefore be closed, if you want do as you please.

**Comment by lorenrh** [comment]
Thanks for the report, if this issue happens again don't hesitate to open a fresh issue!
