### ISSUE TITLE
The image packettpbuildpacks/builder created almost 42 years ago

### ISSUE THREAD

**Issue by afattahi54** [docker/for-win#12439]
- Windows Version: 10
  - Docker Desktop Version:  Docker Desktop 4.3.0 (71786) 
  - WSL2 or Hyper-V backend?  WSL2
  - Pack version : 0.23.0+git-0db2c77.build-3056

### Steps to reproduce the behavior
1- Create an spring boot application 
2- Run pack build test --builder paketobuildpacks/builder:base
3- Open docker desktop, then select imagesimages ... I see packettpbuildpacks/builder  Created almost 42 years ago

Here is screen shot

![image](https://user-images.githubusercontent.com/5003703/145703434-4bee7503-3455-459e-83c0-1c3385a57ecf.png)

The image inspect in docker dektop shows this

![image](https://user-images.githubusercontent.com/5003703/145703640-9feeac94-daf6-4e0c-a092-93488d5c10c2.png)

The ``docker inspect paketobuildpacks/builder:base`` seems to work correctly

**Comment by bcchagas** [comment]
@afattahi54 according to this issue, it's a feature not a bug: https://github.com/buildpacks/pack/issues/931
