### ISSUE TITLE
Docker ignores USER instruction in Dockerfile

### ISSUE THREAD

**Issue by philipp-kolesnikov** [docker/for-win#1243]
### Expected behavior
Container should be started under user specified in USER instruction in Dockerfile

### Actual behavior
Container is started under root

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
 6A59EDC8-9E9F-401F-B8A5-FE549A042C71/2017-10-25_12-08-05
  - host distribution and version (Windows version, build number, etc)
Docker version 17.10.0-ce-win36 (13788) with LCOW support enabled on Windows 10 Pro 1709 (16299.19)
### Steps to reproduce the behavior

  1. docker run --rm -ti memcached:alpine
Output: can't run as root without the -u switch

  2. docker run --rm -ti memcached:alpine sh
  3. whoami
Output: root

Dockerfile can be found here: https://github.com/docker-library/memcached/blob/master/alpine/Dockerfile and it contains "USER memcache" instruction.

**Comment by friism** [comment]
This should probably be opened in moby/moby, cc @jhowardmsft @patricklang

**Comment by TJ-Liu** [comment]
@jhowardmsft @PatrickLang
I am still seeing this issue. Is there any solution for it?
