### ISSUE TITLE
File not found on Startup because AppData Folder is on a different Drive

### ISSUE THREAD

**Issue by Jebsta** [docker/for-win#12432]
- [X] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
I get an error that the files for docker were not found in "C:\Users\Jebsta\AppData\Roaming\Docker" because this Folder doesn't exist because my %Appdata% variable is set to the D: Drive
### Expected behavior
It just start's
### Information
I have my Users Folder (including the AppData stuff) set to an other Drive than the C drive because of SSD size limitations back in the say (128 GB was very small) and the path didn't change since then.
Maybe it would be nice if the references in the Code would go to %AppData% instead of %UserProfile% because on my system (and some others for sure) those variables are on different disks

### Steps to reproduce the behavior
  1. Have your %AppData% Varibale set to anything different than "C:\Users\Username\AppData\Roaming"
  2. Install Docker Desktop
  3. receive Error on Startup of Discord Desktop

### How i got arround this error
  1. copied the files form AppData on D:  onto AppData on C (which is not used by other programms)
  2. killed all Docker Desktop Tasks
  3. start the programm (it works)

**Comment by kzrnm** [comment]
I have the same problem.
I solve the error by symboliclink.

```powershell
cd "C:\Users\Username\AppData\Roaming"
New-Item -Type SymbolicLink -Name Docker -Value "D:\AppData\Roaming\Docker"
```
