### ISSUE TITLE
Update 4.3.1 is reported as Trojan by Windows Defender

### ISSUE THREAD

**Issue by StarLightPL** [docker/for-win#12447]
Current Windows 10 build. Update 4.3.1 is blocked and reported by Windows Defender as Trojan:Script/Oneeva.A!ml . It is triggered by the tempfile created in Appdata/Local/Temp by the installer.

```
Manifest extraction failed: Operation did not complete successfully because the file contains a virus or potentially unwanted software.

   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__24.MoveNext()
```

  - [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Update gets reported as a virus while unpacking

### Expected behavior
Update completes

### Information
  - Did the problem appear with an update? Yes
  - Windows Version: 21H1 build 19043.1348
  - Docker Desktop Version: 4.3.0->4.3.1
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

I uploaded the update to virustotal, as well as scanned it with Avast, no threat detected. It is probably Windows Defender false positive. Machine was then scanned with ESET, no threats found.

### Steps to reproduce the behavior
Trying to install downloaded update, everytime there's a false positive from Windows Defender.

**Comment by StefanScherer** [comment]
Thanks for the report @StarLightPL and for checking with other tools. 
I can reproduce the problem with activated threat protection on Windows 11. We‘re also sure it‘s a false positive in our delta updater 4.3.0 -> 4.3.1. 
We‘ll report it as false positive to the virus scan vendor. 
We found out that a manual update with the full installer works, we‘ll look into the issue to help with the built-in update process.

**Comment by StefanScherer** [comment]
The report was successful, but we don't know which antivirus database version it will be in. Therefore we now force a full installer download for the update 4.3.0 -> 4.3.1. This fixes the built-in update experience, but the download is bigger.
