### ISSUE TITLE
Copying text from the Docker Desktop tutorial does not work

### ISSUE THREAD

**Issue by AntonioRedondo** [docker/for-win#12444]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

It is not possible to copy text from the Docker Desktop for Windows tutorial, nor from the blue buttons, nor from the terminal.

![image](https://user-images.githubusercontent.com/5444421/146058279-02389374-763c-47c3-b01a-18a2a234e51b.png)

### Expected behavior

It should be possible to copy text from both the button and the terminal since this would be useful to run the commands in your onw CLI or to paste the commands somewhere else.

### Information

  - Windows Version: Windows 10 21H2 19044.1348
  - Docker Desktop Version: 4.3.1 (72247) 
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Steps to reproduce the behavior

  1. Start Docker Desktop for Windows.
  2. Start the tutorial (I don't know how to do this. It seems once you close the tutorial there is no way to open it again).
  3. Try to copy text from the blue buttons or the embedded terminal. It will not work.

**Comment by mat007** [comment]
We have released Docker Desktop 4.6.0, with a fix for this issue, see https://docs.docker.com/desktop/windows/release-notes/
