### ISSUE TITLE
Unable to connect to the server: dial tcp 127.0.0.1:6443: connectex: No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by RiteshKo** [docker/for-win#12448]
Hey, a newbie in the Docker/Kubernetes world needs some guidance

I am getting the below error when running the kubectl commands:
Unable to connect to the server: dial tcp 127.0.0.1:6443: connectex: No connection could be made because the target machine actively refused it

This started happening after the latest docker desktop update. In the older versions we used to see Enable Kubernetes option in the Docker desktop. 

Docker Desktop version: 4.3.1 (72247)
Windows OS: Windows 11 Home

In some of the same issues raised here couple of suggestions were to check kube config file but in my case that is also present.

Below commands are used:
kubectl get nodes
Unable to connect to the server: dial tcp 127.0.0.1:6443: connectex: No connection could be made because the target machine actively refused it.

kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"windows/amd64"}
Unable to connect to the server: dial tcp 127.0.0.1:6443: connectex: No connection could be made because the target machine actively refused it.

kubectl apply -f .\deployment.yml
Unable to connect to the server: dial tcp 127.0.0.1:6443: connectex: No connection could be made because the target machine actively refused it.

kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
contexts:
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
current-context: docker-desktop
kind: Config
preferences: {}
users:
- name: docker-desktop
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED

Context is set as docker desktop
kubectl config get-contexts
CURRENT   NAME             CLUSTER          AUTHINFO         NAMESPACE
*         docker-desktop   docker-desktop   docker-desktop

**Comment by EGNSIUR** [comment]
hey, did you find solution?

**Comment by MustaphaOULKHALF** [comment]
run minikube start

**Comment by MustaphaOULKHALF** [comment]
run the following command : 
minikube start

**Comment by MustaphaOULKHALF** [comment]
> hey, did you find solution?
run the following command :
minikube start

**Comment by vennki** [comment]
This issue predominantly occurs when the docker desktop and kubernetes are not running. Please run docker desktop and wait till both docker engine and kubernetes are up and running.

**Comment by AshwinNema** [comment]
> This issue predominantly occurs when the docker desktop and kubernetes are not running. Please run docker desktop and wait till both docker engine and kubernetes are up and running. Once the docker engine and kubernetes are running. please execute the commands. For example: kubectl get nodes

This helped. Thank you

**Comment by Abuhurairaa** [comment]
This really helped.

**Comment by Abuhurairaa** [comment]
> This issue predominantly occurs when the docker desktop and kubernetes are not running. Please run docker desktop and wait till both docker engine and kubernetes are up and running. Once the docker engine and kubernetes are running. please execute the commands. For example: kubectl get nodes

This help me a lot.

**Comment by Frenzaahh** [comment]
This worked for me:

-start Docker desktop
-open Powershell in administrator mode
-run the following commands
$minikube delete
$minikube start --driver=docker
