### ISSUE TITLE
Error response from daemon: Get "https://registry-1.docker.io/v2/": remote error: tls: handshake failure

### ISSUE THREAD

**Issue by brandon8696** [docker/for-win#12443]
Using the most up to date version of Docker Desktop 4.3.1. I am new to using Docker, but this was the method of testing left by our old developer. 

Upon researching a ton on this error myself, it seems like way back in Docker 18.09, they broke everything with certifications, and haven't bothered to fix it ever since. 

I am not super familiar with Docker, but I think I have reduced my slew of errors down to this one issue. Basically what is happening is every time I try to compose my containers, it throws that error: 

Error response from daemon: Get "https://registry-1.docker.io/v2/": remote error: tls: handshake failure

I was silly and thought I could just hit run on the containers in the Desktop client, but it turns out that action does not properly compose the containers with the proper configuration. I could really use the assistance to get past this major hurtle. I can't really start developing if I don't have a test environment haha.

**Comment by lorenrh** [comment]
Thanks for your report, would you mind sharing a diagnostics ID? You can do so following the instructions here: https://docs.docker.com/desktop/windows/troubleshoot/#diagnose-and-feedback
