### ISSUE TITLE
Double-clicking tray icon leads to double docker window opened

### ISSUE THREAD

**Issue by Wasenshi123** [docker/for-win#12451]
This is perhaps just a minor bug with no effect on productivity, but I will report it anyway so that you know it exists.

  - [x ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
When double-click the tray icon, docker window will show up as double windows (appear to be 2  windows and need to be closed 2 times) (clicking/double-clicking further more doesn't spawn more)

### Expected behavior
docker window should only spawn once, since that should be the original intended behavior.

### Information

  - Windows Version: 10
  - Docker Desktop Version:  4.3.1
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. launch docker desktop (if not)
  2. double-click the docker icon from system tray

**Comment by Robban1980** [comment]
Have the same issue when clicking the icon in the start menu.

**Comment by JamesMahy** [comment]
Also same issue on desktop

**Comment by EduardoAule** [comment]
Hello
Same here, https://github.com/docker/for-win/issues/12686#issue-1213181053
