### ISSUE TITLE
Display release notes link after upgrade Docker Desktop

### ISSUE THREAD

**Issue by luizcarlosfaria** [docker/for-win#12461]
Today,

when has a new version of Docker Desktop, I can click it to view release notes.

Sometimes I've installed before read that.

Now I can't see this link without search on google.

Software Updates page on Docker Desktop is a good pannel to communicate features that still comming, and features that as part of paid subscription.

**Comment by StefanScherer** [comment]
Thanks for your feedback!
Yes, we're planning to add the release highlights to the Software Updates page in the next release.
