### ISSUE TITLE
Courgette.log file created on the desktop

### ISSUE THREAD

**Issue by AlbertoFabbri93** [docker/for-win#12468]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Docker Desktop creates a file called `courgette.log` on the desktop every time it upgrades.

### Expected behavior
The log file should not be created on the desktop.

### Information

  - Windows Version: Windows 11 Home, 22000.376
  - Docker Desktop Version: 4.3.2
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by SebastienPittet** [comment]
Same here!

- Windows Version : Windows 10 Pro, OS Build 19044.1415
- Docker Desktop Version: Docker Desktop 4.3.2 (72729)
- WSL2
- diagnose output below:

[362:16:17:16.622][I] ipc.NewClient: 17c2e309-com.docker.diagnose -> \\.\pipe\dockerBackendV2 com.docker.service.exe
[goroutine 1 [running, locked to thread]:
[win/backend/pkg/service.NewClientForPath(...)
[       win/backend/pkg/service/service.go:26
[win/backend/pkg/service.NewClient(...)
[       win/backend/pkg/service/service.go:20
[common/pkg/diagkit/gather/diagnose.init()
[       common/pkg/diagkit/gather/diagnose/ipc_windows.go:23 +0x13b
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.

**Comment by fourofspades** [comment]
Been trying to work out what the hell has been doing this for a long time.  Concerned about low level trojans and all sorts of other nasties.

Thanks Docker for wasting my time.  Clearly your "engineers" have never heard of %temp%

**Comment by deltaepsilon** [comment]
So glad this isn't just me.

**Comment by Omniwot** [comment]
Same issue here

**Comment by bhagerty** [comment]
Thanks for opening this issue! What a silly bug!

**Comment by baterflyrity** [comment]
Having this bug since the origin. Recent February update still bring new empty *courgette.log* file.

**Comment by PascalMagnard** [comment]
Same here, courgette.log on Windows 10 desktop after each Docker upgrade.

**Comment by aschkenasy** [comment]
just happened to me although it created it only in the running containers root

**Comment by SalehEssamSaleh** [comment]
Same here!

- Windows 10 Pro 21H2 19044.1645
- Docker Desktop Version: 4.5.1
- WSL2

so I should remove it or what should I do! 
and there is any way to make Docker liter!
Because my laptop i3 second-generation 6GB RAM and 500 GB HHD
which is already super old and I need to use Docker for studying purposes.
So any ideas and thank you a lot.

**Comment by guydumais** [comment]
Same here:
Docker Desktop 4.7.1 (77678)
Windows 11

**Comment by KoNyan2612** [comment]
Same here:
Docker Desktop 4.8.2 (79419)
Windows 11

**Comment by Xtr102** [comment]
Same issue here. Though it only created it in the running container root.

**Comment by SubaruSama** [comment]
Possible related: https://chromium.googlesource.com/chromium/src/+/32352ad08ee673a4d43e8593ce988b224f6482d3/courgette/courgette_tool.cc#434

In some part of the code or during the update, it launches some chromium. Any Engineer from Docker can confirm this?

**Comment by drewbritton** [comment]
It's comforting to know that this is just a harmless side effect of applying Docker desktop updates. But I have to admit I still find the totally empty courgette.log file appearing on my desktop a bit ominous...

**Comment by solarpolar** [comment]
Still happening - and must send this issue on github a heap of traffic!

**Comment by linghengqian** [comment]
- I have the impression that `courgette` is `Google`'s differential algorithm in `Chrome/Chromium`, which is used for incremental updates to the `Chrome` browser. But I still don't understand why this problem persists, as it persists in `Docker Desktop 4.13.0 (89412)`.

**Comment by Jens-G** [comment]
Still happening. 

File is created by some courgette64.exe (located in Docker program folder) and that looks indeed pretty much like 
* https://www.chromium.org/developers/design-documents/software-updates-courgette/
* https://chromium.googlesource.com/chromium/src/courgette/+/HEAD

**Comment by julbra** [comment]
It's 2023 and we still get this empty courgette.log haunting millions of desktops after every single update.

**Comment by yooakim** [comment]
Same issue as everyone else here. Still happening.

**Comment by baterflyrity** [comment]
Seems docker team officially dont give a crap about windows community.

**Comment by Trystan-SA** [comment]
Did I just yelled at my colleagues for this?

**Comment by changetol8** [comment]
I had the same issue by last update

**Comment by thaJeztah** [comment]
👋 I work at Docker, but not on this part of the code, but I stumbled upon this ticket and checked with the team (asked them to have a look). It looks like they have a fix for this (it's currently being reviewed).

The `courgette.log` is indeed part of the "delta updater", and in some cases it may write this file. So the good news is that there should be no reason for concern about the file, but it definitively shouldn't end up on your Desktop 😅 (more so, because the filename is rather "weird" and because of that, difficult to associate with "Docker Desktop").

The fix that's being reviewed will disable these logs, and should end up in the next (4.19) release of Docker Desktop.

**Comment by maxcleme** [comment]
Closing this issue because a fix has been released in Docker Desktop 4.19.0. See the [release notes](https://docs.docker.com/desktop/release-notes/) for more details.
