### ISSUE TITLE
Windows PC reboots with a blank screen after enabling Virtualization in BIOS

### ISSUE THREAD

**Issue by azakero** [docker/for-win#12472]
- [y ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

After enabling Virtualization from BIOS, PC rebooted with a blank screen. Then I had to open up the PC and put the ram in different slot and somehow went into the BIOS and disabled Virtualization. After doing that, PC started working normally. 

### Expected behavior

Install Docker and not boot with a blank screen after enabling Virtualization

### Information

  - Windows Version: Windows 10 Pro, Version 21H2, OS Build 19044.1415
  - Docker Desktop Version: 4.3.2
  - WSL2 or Hyper-V backend?  I chose WSL2 while installing Docker Desktop
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Local Machine

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
It doesn't sound like this has anything to do with Docker. We do require virtualization to be turned on, but if your PC won't boot with that BIOS setting, that's a problem with the PC or the OS.
