### ISSUE TITLE
Docker fails to start even if hardware assisted virtualization enabled

### ISSUE THREAD

**Issue by roblon** [docker/for-win#12478]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: Diagnose Fail, see picture

### Actual behavior

Docker desktop fails to start throwing following error: Hardware assisted virtualization and data execution protection must be enabled in the BIOS.

Even if Hardware assisted virtualization is enabled, please have a look at the snapshots.

### Expected behavior
Docker starts correctly

### Information

  - Windows Version: Windows 10 Enterprise
  - Docker Desktop Version: 4.3.2 (72729) 
  - WSL2 or Hyper-V backend? Enabled
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: NO

![TaskManager](https://user-images.githubusercontent.com/92030361/148194092-488cb494-0ed6-4d83-b3ba-d6a5e996c7b7.PNG)
![Features](https://user-images.githubusercontent.com/92030361/148194097-397a4272-89c4-4741-95fd-0009f4964fa5.PNG)
![Docker](https://user-images.githubusercontent.com/92030361/148194114-ba901616-80e7-4779-b543-fca0a1d092d0.PNG)
![DiagnoseFail](https://user-images.githubusercontent.com/92030361/148196466-de6bdd0e-81d3-46e6-b7c7-afddc5077914.PNG)

### Steps to reproduce the behavior

  1. Docker fail to start just on my mashine

**Comment by StefanScherer** [comment]
Thanks for the report. We haven't seen this before. Docker Desktop relies on what the Win32 API returns. You could check it by running this PowerShell command

```powershell
(Get-CimInstance -ClassName Win32_ComputerSystem).HypervisorPresent
```

It should return `True` to make Docker Desktop work.

You could try the self-diagnose tool or create diagnostics from the command line as shown in https://docs.docker.com/desktop/windows/troubleshoot/#diagnosing-from-the-terminal

I don't have a better suggestion what is missing on your machine. 🤔

**Comment by roblon** [comment]
Hello @StefanScherer 

Power shell returns: 
PS C:\Users\xxxx> (Get-CimInstance -ClassName Win32_ComputerSystem).HypervisorPresent
False

**Comment by StefanScherer** [comment]
Thanks, yes that `False` confirms why Docker Desktop shows the error popup. 😢 

But I have no idea why it isn't `True` on your machine. 🤷 
Have you tried running a WSL 2 distro? Does this work, do you see a running wsl distro when you run `wsl.exe -l -v`?
