### ISSUE TITLE
Bind mounts via docker compose fail

### ISSUE THREAD

**Issue by AdrianDeWinter** [docker/for-win#12475]
For some time now, creating windows continers with bind mounts via compose has been throwing errors for me.

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 80BC1E23-AE4A-4A16-8E91-52D1BACB4C5F/20211231062135
### Actual behavior
Running this file via `docker compose up` leads to the following error:
`Error response from daemon: hcsshim::CreateComputeSystem 6176b288543e2a9103f20e46eeaec6545613a83740d274cbdb1c5c769f84de62: The request is not supported.`
### Expected behavior
For the contaienr to start up normally as it used to
### Information
I have a simple compose file for demonstration purposes that attempts to launch a windows nanoserver container with a bind mount:
```Dockerfile
services:
  test_service:
    image: mcr.microsoft.com/windows/nanoserver:ltsc2022
    container_name: test_container
    entrypoint: cmd.exe
    volumes:
      - type: bind
        source: C:\test
        target: C:\test
```

Interestingly, the same bind works fine if i create it via docker run:

`docker run --rm --entrypoint cmd.exe -it --mount type=bind,source="C:\test",target=C:\test mcr.microsoft.com/windows/nanoserver:ltsc2022`

The Problem seems to have apeared with the November 2021 Windows patch day, though i cant be quite certain.

  - Windows Sever 2022 Build 10.0.20348.405
  - Docker Desktop 4.3.2 (72729)
  - process isolation container model
  - not virtualized

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
```
PS C:\Program Files\Docker\Docker\resources> ./com.docker.diagnose.exe check
[365:07:15:51.773][I] ipc.NewClient: 8db6b445-com.docker.diagnose -> \\.\pipe\dockerBackendV2 com.docker.service.exe
[goroutine 1 [running, locked to thread]:
[win/backend/pkg/service.NewClientForPath(...)
[       win/backend/pkg/service/service.go:26
[win/backend/pkg/service.NewClient(...)
[       win/backend/pkg/service/service.go:20
[common/pkg/diagkit/gather/diagnose.init()
[       common/pkg/diagkit/gather/diagnose/ipc_windows.go:23 +0x13b
time="2021-12-31T07:15:52+01:00" level=info msg="unable to query WSL distros: exit status 0xffffffff"
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[SKIP] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0023: is the Containers Windows Feature enabled?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.
```
### Steps to reproduce the behavior

  1. create above mentioned dockerfile
  2. create the directory C:\test
  3. run `docker compse up`

I have, of course, gone through all the settings and also reinstalled Docker Desktop. My issue seems quite similar to [this issue](https://github.com/microsoft/hcsshim/issues/649) from the hscsim github page.

**Comment by Onjahh** [comment]
#12411  #12407

**Comment by stephen-turner** [comment]
An hcsshim error is from the upstream Windows container implementation, so https://github.com/microsoft/hcsshim is probably the right place to report it, as with the issue you have linked. (That part of the code was not written by Docker engineers). Thank you.
