### ISSUE TITLE
what is LCOW? Storage Driver: windowsfilter (windows) lcow (linux) ? Maybe It is a new thing?

### ISSUE THREAD

**Issue by khs1994** [docker/for-win#1248]
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by friism** [comment]
* https://blog.docker.com/2017/09/preview-linux-containers-on-windows/
 * https://blog.docker.com/2017/09/docker-windows-server-1709/

**Comment by khs1994** [comment]
Thanks

**Comment by ericblade** [comment]
... can someone explain t he difference between "lcow" and how it operates prior to "lcow"?

**Comment by friism** [comment]
@ericblade 

 * https://blog.docker.com/2017/09/preview-linux-containers-on-windows/
 * https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/linux-containers

**Comment by ericblade** [comment]
None of these documents explains how that is any different from how it works currently.

**Comment by friism** [comment]
@ericblade When running Linux containers with Docker for Windows and not using LCOW, all the Linux containers run in a unitary VM configured by Docker for Windows. Docker daemon run in this VM, on Linux.

Using LCOW, each container runs in its own minimal hypervisor (VM) managed by Docker and Windows. The Docker daemon runs only on Windows.

**Comment by ericblade** [comment]
... so, overall, that should probably use more, if not significantly more, resources than the current version, it sounds like, and it wouldn't surprise me if it caused significantly worse networking issues than the Windows version already suffers from :(  was hoping for an improvement :-)

**Comment by rlpowell** [comment]
The normal setup is that all docker stuff runs in a Linux VM; this is bad because you have to allocate RAM for that VM and the whole thing is taken up no matter what you're doing.

What LCOW *should* do is allow docker to only use the resources it's actually using, which would mean much *less* resource usage normally.  However, see https://github.com/docker/for-win/issues/1357
