### ISSUE TITLE
Docker buildx invalid character

### ISSUE THREAD

**Issue by kwiksilver3441** [docker/for-win#12492]
- [ x] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID:
3b2162a1-7f98-4f91-8860-2d4328762d70/20220110190906
### Actual behavior
Docker buildx any command results in "error: invalid character '\x00' looking for beginning of value'
### Expected behavior
To use docker buildx. Works fine on linux when I manually download everything. Just not when it's included with docker desktop
### Information

  - Windows Version: 11 latest
  - Docker Desktop Version: 4.3.2 latest
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:
No
### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
Appears then disappears. 
### Steps to reproduce the behavior

I just run 'docker buildx ls', but most docker buildx commands don't work properly. The only ones that don't report the same error, are ones that have other issues, like not naming something in docker buildx create, etc
  1. Powershell, (admin or not)
  2. docker buildx ls

**Comment by homiedopie** [comment]
@kwiksilver3441 - I managed to fix mine by removing a file from `~/docker/contexts/meta` which has garbage/binary values.

Reference:
- https://stackoverflow.com/questions/46843711/docker-error-grabbing-logs-invalid-character-x00-looking-for-beginning-of-v
