### ISSUE TITLE
Windows not booting anymore after enabling Linux containers for Windows

### ISSUE THREAD

**Issue by luca-moser** [docker/for-win#1250]
### Expected behavior
The Windows machine should boot correctly after turning on "Linux containers for Windows".

### Actual behavior
The Windows machine is stuck in a "Automatic Repeair" loop. The machine never gets to the login screen and abords midway when booting. The automatic repair is never executed.

### Information
As I can't start the machine correctly, I can't read out this information.
But I think I downloaded 17.10.0-ce-win36 or something like that. (Edge branch).

* Windows 10 Insider Build (no idea which build number)

### Steps to reproduce the behavior
I upgraded from a previous Docker version and then enabled  the "Linux containers for Windows" feature.

**Comment by luca-moser** [comment]
The system is completely bricked.

* I can't use safe mode to enter the OS.
* Disabling driver signature enforcment doesn't fix the issue.
* Disabling early launch anti-malware protection doesn't fix the issue.
* Using the recovery tool a rollback to the previous Windows build isn't working.
* Manually copying Windows.old data to the right places doesn't fix the issue.
* Disabling intel virtualisation in the BIOS doesn't fix the issue.
* bcdedit hypervisorlaunchtype to off doesn't fix the issue.

....At the current state only re-installing Windows my only option.

**Comment by friism** [comment]
cc @jhowardmsft @patricklang

**Comment by jasonbivins** [comment]
@luca-moser  - do you remember if you actually able to check the box in the GUI ?  the Windows build you're should have kept it from being enabled.

![image](https://user-images.githubusercontent.com/28021664/32155986-0fa7e600-bd11-11e7-8428-91247a93b77a.png)

**Comment by luca-moser** [comment]
@jasonbivins 
A dialog directly after the Docker update asked me whether I want to enable LCOW.

Note: Maybe I had a totally different Windows build then I thought I had. All I know is, that I was on an insider branch, but I can't even tell in which ring I was. So I am pretty sure it was something `>=1709`.
