### ISSUE TITLE
Docker service/daemon failing on Windows 10 Pro

### ISSUE THREAD

**Issue by hongooi73** [docker/for-win#12505]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 2C652E00-51B8-495D-982C-165E78DE7CF7/20220121023707

### Actual behavior

I'm unable to do anything with Docker. Eg a simple `docker image ls` fails with "Error response from daemon: open \\.\pipe\docker_engine_linux: The system cannot find the file specified." Ditto for `docker build` or anything else.

Looking at the log file `Appdata\local\Docker\log.txt`, I see a ton of lines like

```
[13:41:09.442][IPCClient         ][Info   ] (9838390c) ba0928f5-WslIntegrationService-CSharp C->S WSLCrossDistroService GET /check
[13:41:15.680][GoBackendProcess  ][Info   ] [021:13:41:15.680][W] 9f71a556-PauseHDL /pause/events server not replying: Get "http://ipc/pause/events": open \\.\pipe\dockerProcd: The system cannot find the file specified.
[13:41:18.340][VpnKitBridge      ][Info   ] [021:13:41:18.340][I] windows: still waiting for devenv-volumes, wsl2-bootstrap-expose-ports, diagnosticd, debug-shell, wsl2-cross-distro-service, lifecycle-server, mutagen, procd, log, volume-contents, docker after 20.0129125s
[13:41:19.436][WslIntegrationService][Warning] HttpOS Client: connection timed out.
```
repeating over and over again.

### Expected behavior

No errors should occur.

### Information

The last time I used docker was actually before the Christmas break (around a month ago), and everything worked fine. I'm not sure if the system or Docker updated since then.

  - Windows Version: Win 10 Pro 19043.1466
  - Docker Desktop Version: 4.4.3 (73365)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

Very big output, first error is

```
[FAIL] DD0031: does the Docker API work? error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine_linux/v1.24/containers/json?limit=0": open //./pipe/docker_engine_linux: The system cannot find the file specified.
[FAIL] DD0004: is the Docker engine running? Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
```

**Comment by hongooi73** [comment]
Resetting Docker seems to have cleared it up, albeit at the cost of nuking all my images.

**Comment by uberhacker** [comment]
After an upgrade to 4.4.3, I am unable to launch also.  Resetting to the default settings did not help.  I'm now dead in the water.  Log attached.  
[log.txt](https://github.com/docker/for-win/files/7919984/log.txt)

**Comment by 39digits** [comment]
In case it helps you get working again - I've had some odd behaviour since upgrading in December from 4.2.x to this latest version.  Docker-related BSOD, constant Application Log from DockerService for PowerEvents every 5 seconds whether Docker Desktop is running or not, com.docker.proxy-wsl throwing errors when shutting down Windows...

I uninstalled 4.4.3 and installed 4.2.0 again and everything has been stable since.  You can get the older versions on the [Docker Releases](https://docs.docker.com/desktop/windows/release-notes/) page.

**Comment by uberhacker** [comment]
Thanks for the tip @39digits!  Unfortunately, 4.2.0 is not working for me either.  I should note that this all started in combination after the latest Windows updates for this month.  I thought it might have been Kaspersky Anti-Virus but uninstalling that didn't make a difference.  It was also interesting after uninstalling 4.4.3 and attempting to reinstall 4.3.2, there was a .NET error that I needed to fix with NetFxRepairTool.exe.  Of course, after executing the repair tool, I needed to apply another Windows update.  I must have rebooted 10 times during all this over a period of 5 hours.  It's getting to the point now that something breaks after EVERY Windows update.  Gotta <3 "progress". LoL

**Comment by mawilson1234** [comment]
> In case it helps you get working again - I've had some odd behaviour since upgrading in December from 4.2.x to this latest version. Docker-related BSOD, constant Application Log from DockerService for PowerEvents every 5 seconds whether Docker Desktop is running or not, com.docker.proxy-wsl throwing errors when shutting down Windows...
> 
> I uninstalled 4.4.3 and installed 4.2.0 again and everything has been stable since. You can get the older versions on the [Docker Releases](https://docs.docker.com/desktop/windows/release-notes/) page.

Same issue here, and the only way I could fix it was reinstalling 4.2.0; anything newer doesn't work.

**Comment by 39digits** [comment]
I've added a comment to the issue I created #12507 but in summary I reinstalled Windows 11 Pro from the Recovery Images provided by Microsoft for my Surface Laptop 4.  Then over the span of 2-3 weeks created Recovery Points, installed a tool/service I required, worked to see if any BSOD occur, repeat.

The moment I installed Docker Desktop (4.5.1 at the time) I had a BSOD within less than a day after more than a fortnight of clean use.

There is definitely something unstable at the moment.

**Comment by uberhacker** [comment]
@39digits:  I feel your pain.  One thing I noticed after every update was the LxssManager service stopped working.  The only way I was able to get this going again was to disable and reenable the Windows Subsystem for Linux feature.  Unfortunately, it requires 2 reboots but it has worked on several occasions to get Docker Desktop to launch (at least on Windows 10 Pro).  Windows 11 might behave differently.  More information here: https://www.thewindowsclub.com/wslregisterdistribution-failed-with-error-0x80070422

**Comment by jamalwsilva** [comment]
Similar problem here with Win11 (OS param contains a wrong value) after switching to Windows containers:

```
Version: 4.8.1 (78998)
Sha1: 6db2e804ec208b579edfe3a4947e2cf4222dec87
Started on: 2022/05/15 20:51:29.682
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Home Single Language
Edition: CoreSingleLanguage
Id: 2009
Build: 22000
BuildLabName: 22000.1.amd64fre.co_release.210604-1628
File: C:\Users\jamal\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 

[2022-05-15T20:51:30.161656700Z][com.docker.backend.exe][I] ipc.NewClient: 0220712f-PauseHDL -> \\.\pipe\dockerProcd procd
[2022-05-15T20:51:30.161656700Z][GoBackendProcess  ][Info   ] [common/cmd/com.docker.backend/internal/handlers.NewProcdHandler(0xc00036c6c0)
[2022-05-15T20:51:30.161656700Z][GoBackendProcess  ][Info   ] [	common/cmd/com.docker.backend/internal/handlers/pause.go:25 +0xab
[2022-05-15T20:51:30.161656700Z][GoBackendProcess  ][Info   ] [main.makeConfig(0xc000486000, 0xff?, 0x13750086300?)
[2022-05-15T20:51:30.161656700Z][GoBackendProcess  ][Info   ] [	common/cmd/com.docker.backend/main.go:462 +0xd09
[2022-05-15T20:51:30.161656700Z][GoBackendProcess  ][Info   ] [main.run()
[2022-05-15T20:51:30.161656700Z][GoBackendProcess  ][Info   ] [	common/cmd/com.docker.backend/main.go:189 +0x6d6
[2022-05-15T20:51:30.161656700Z][GoBackendProcess  ][Info   ] [main.main()
[2022-05-15T20:51:30.161656700Z][GoBackendProcess  ][Info   ] [	common/cmd/com.docker.backend/main.go:97 +0x1d

[2022-05-15T20:51:37.003692200Z][ExtensionManagerProcess][Info   ] 2022/05/15 17:51:37 forwarding extension sockets done
[2022-05-15T20:52:00.437272400Z][com.docker.backend.exe][W] 0220712f-PauseHDL /pause/events server not replying: Get "http://ipc/pause/events": open \\.\pipe\dockerProcd: O sistema não pode encontrar o arquivo especificado.
[2022-05-15T20:52:30.705463000Z][com.docker.backend.exe][W] 0220712f-PauseHDL /pause/events server not replying: Get "http://ipc/pause/events": open \\.\pipe\dockerProcd: O sistema não pode encontrar o arquivo especificado.
```

**Comment by JerryBluesnow** [comment]
any solution on the issue?

**Comment by bwalocha** [comment]
anyone?

**Comment by Pdzly** [comment]
This issue still persists on 4.13.1 

[2022-11-07T09:02:28.696644000Z][com.docker.backend.exe][W] 7cecf3be-PauseHDL /pause/events server not replying: Get "http://ipc/pause/events": open \\.\pipe\dockerProcd: Das System kann die angegebene Datei nicht finden.
[2022-11-07T09:02:58.714148300Z][com.docker.backend.exe][W] 7cecf3be-PauseHDL /pause/events server not replying: Get "http://ipc/pause/events": open \\.\pipe\dockerProcd: Das System kann die angegebene Datei nicht finden.
[2022-11-07T09:03:28.731510400Z][com.docker.backend.exe][W] 7cecf3be-PauseHDL /pause/events server not replying: Get "http://ipc/pause/events": open \\.\pipe\dockerProcd: Das System kann die angegebene Datei nicht finden.


I have reinstalled docker desktop and wsl (2) multiple times ( of course restarted) this is f*cking annoying

**Comment by sergio11** [comment]
@Pdzly Did you fix the issue? I have the same error related to \.\pipe\dockerProcd. I've reinstalled Docker Desktop several times.

**Comment by HeathLoganCampbell** [comment]
This issue still persists on 4.15.0,This issue still persists on 4.15.0,
I have downloaded [4.2.0](https://docs.docker.com/desktop/release-notes/#420) but it now requires Windows Pro (Currently I have Windows 10 Home)

**Comment by SKJoy** [comment]
Soon to celebrate the first birthday for this issue! One year! And anyone with any fix/work around to this?

**Comment by SKJoy** [comment]
Ok, looks like this is not a bug, at least for me (but Docker could have been intuitive);

Symptom: Log: 7964d072-PauseHDL /pause/events server not replying

Resolution:

1. Uninstall Docker (I manually cleaned the AppData Local/Roaming paths too for Docker folder);
2. Installed Docker 4.2.0 from the Docker release page (using elevated command prompt);
3. It started alright with an error prompt stating my WSL 2 installation was incomplete due to an outdated Linux kernel (or somewhat like that), with link to the Microsoft HotFix update;
4. Applied the WSL 2 update;
5. Docker started running just as expected;
6. From settings, I updated Docker to the latest version;

... and looks like my system and Docker latest are happily living ever after :)

Wish: Docker latest releases could have prompted with the WSL 2 issue to have my 3 hours of pain :( Even the 1+ year older Docker was able to trap it!

**Comment by DonMatron** [comment]
Just faced this issue while installing 4.16.1.  As @SKJoy said, the problem here was old version of the WSL2 kernel.

Here is my workaround:

- Open Settings > Update & recovery > Windows Update
- Click on "Advanced options"
- Enable "Receive updates for other Microsoft products when you update Windows"
- Returning to the previous page in Settings, click "Check for updates".

After the reload everything went well.

**Comment by dkattan** [comment]
> Just faced this issue while installing 4.16.1. As @SKJoy said, the problem here was old version of the WSL2 kernel.
> 
> Here is my workaround:
> 
> * Open Settings > Update & recovery > Windows Update
> * Click on "Advanced options"
> * Enable "Receive updates for other Microsoft products when you update Windows"
> * Returning to the previous page in Settings, click "Check for updates".
> 
> After the reload everything went well.

This worked for me. I pressed Check for updates which triggered a bunch of updates to start installing even though I didn't tell it to start installing, and after a few of them installed Docker Desktop started without me doing anything.

**Comment by oliverkoenig** [comment]
Solved!

Same issue (server not replying: Get "http://ipc/pause/events": open \\.\pipe\dockerProcd) and Docker Desktop on Windows stuck with "docker desktop starting...".

My working solution was:

In system tray Docker context menu: 
1. Switch to Windows containers
2. Restart
Afterwards I switched back to Linux containers and Restart again, and it still worked, so I don't know if the "Switch to Windows containers" made a difference.

**Comment by http600** [comment]
> Solved!
> 
> Same issue (server not replying: Get "http://ipc/pause/events": open \.\pipe\dockerProcd) and Docker Desktop on Windows stuck with "docker desktop starting...".
> 
> My working solution was:
> 
> In system tray Docker context menu:
> 
> 1. Switch to Windows containers
> 2. Restart
> 
> Afterwards I switched back to Linux containers and Restart again, and it still worked, so I don't know if the "Switch to Windows containers" made a difference.

What a life saver!!
