### ISSUE TITLE
Docker proxy settings no longer respected since 4.4.2

### ISSUE THREAD

**Issue by jaredrussell** [docker/for-win#12516]
Since Docker Desktop 4.4.2 proxy settings entered through `Settings -> Resources -> Proxies` no longer seem to be respected. 

**Steps to reproduce**

- Install Docker Desktop 4.3.2
- Set the HTTP and HTTPS proxy server settings to some random host (i.e. `http://foo:1234`)
- Click "Apply and restart"
- Run `docker info` -> the proxy settings will appear in the result
- Run a command such as `docker pull alpine` -> you will get an error because the proxy server doesn't exist
- Update to any 4.4.x version (repro'd in 4.4.2, 4.4.3 and 4.4.4)
- Ensure the proxy settings are still defined
- Run `docker info` again -> the proxy settings _do not_ appear in the results
- Run `docker pull alpine` -> the image will be successfully pulled

This behaviour is not related to the upgrade process and has been repro'd in a clean install of 4.4.4.

---

For reference when you _are_ using real proxy this issue manifests itself with error messages such as:
```
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**Comment by PhillipVoyle** [comment]
This looks to have been reported here https://github.com/docker/for-win/issues/12503

**Comment by jaredrussell** [comment]
> This looks to have been reported here #12503

Can't believe I missed that!
