### ISSUE TITLE
Windows Firewall Security Policy preventing network connectivity in Hyper-V guests and Windows containers with Hyper-V "internal" virtual switches

### ISSUE THREAD

**Issue by JustinChristensen** [docker/for-win#12517]
I've been trying to track down why I can't establish network connectivity using the default NAT network when in Windows containers mode on my domain-joined corporate workstation for a while now. I think I've figured it out, and I was hoping that Microsoft may be able to provide some guidance on what the expected behavior should be for the interaction between Security Policy, Windows Firewall, the Host Networking Service, Internet Connection Sharing, and Hyper-V's virtual switches. 

This impacts both Docker for Windows and Hyper-V generally. 

Specifically what is happening is that when the Security Policy "Apply Local FIrewall Rules" is set to "No" in the public profile, local firewall rules that Internet Connection Sharing and the Host Networking Service adds to permit DHCP and DNS for Hyper-V guests are no longer applied. This means that attempts to broadcast for DHCP and DNS queries in the guest Hyper-V VM (or container) are then blocked by Windows Firewall. 

I've tested this in isolation on a Windows 10 Pro VM in Azure, with only this specific Security Policy configured through the Local Security Policy snap-in.

I've got a gist where I've been tracking my notes on this [here](https://gist.github.com/JustinChristensen/77b1496331a59940342c577233046a49). I've used netsh to capture the network events that prove that this is the case, and you can see what filters are making the allow/deny decisions with these files:

Apply Local Firewall Rules: Yes
[DHCP Broadcast Allow](https://gist.github.com/JustinChristensen/77b1496331a59940342c577233046a49#file-netevent-dhcp-allow-txt)
[DNS Allow](https://gist.github.com/JustinChristensen/77b1496331a59940342c577233046a49#file-netevent-dns-allow-txt)

Apply Local Firewall Rules: No
[DHCP Broadcast Deny](https://gist.github.com/JustinChristensen/77b1496331a59940342c577233046a49#file-netevent-dhcp-deny-txt)
[DNS Deny](https://gist.github.com/JustinChristensen/77b1496331a59940342c577233046a49#file-netevent-dns-deny-txt)

You can see from this that when this security policy is either not configured or set to Yes, that the local rules that the Host Networking Service and ICS add permit the traffic. 

Now, in corporate environments administrators are typically wont to set this Security Policy to No, and then to configure and maintain a list of static inbound firewall rules that get distributed to workstations via policy updates. What I'm wondering from Microsoft is:
1. Are these local rules that ICS and the Host Networking Service adds to support Hyper-V networking supposed to be clobbered by this security policy? Or should they be a special case? That is, is it by design that that security policy prevents these Windows services from doing what they need to do to support Hyper-V networking?
2. If that is working as intended, what would be the right way to configure security policy to allow these services to apply their local firewall rules? From what I see, those rules are dependent on local system state like security identifiers and interface identifiers, (which allows them to be more narrowly scoped), and so maintaining another static firewall rule in the list wouldn't necessarily be an effective solution. Should there be another security policy callout somewhere that says something like "Disallow local firewall rules, except for those added by Windows Services X, Y, and Z"?
3. Is there documentation out there somewhere that details how this interaction between Hyper-V, Windows Firewall, HNS, ICS, and this Security policy is supposed to work that I just missed in my search?

I apologize that this isn't narrowly scoped to just Docker For Windows, but Docker depends on quite a number of other Windows subsystems, and I was hoping that someone monitoring this issue tracker might be able to get this report in front of the right people internally to help me address what seems like a potential oversight in the design of that Security Policy.

**Comment by JustinChristensen** [comment]
![image](https://user-images.githubusercontent.com/1304220/151099710-4091c205-a224-4831-a36e-3883f655583a.png)

**Comment by JustinChristensen** [comment]
@stephen-turner :point_up:

**Comment by stephen-turner** [comment]
You said this is a Hyper-V issue not a Docker Desktop issue? So you need to report it to Microsoft, not us. We just trust the OS.

**Comment by JustinChristensen** [comment]
@stephen-turner 

Right, but to function in Windows Containers mode Docker relies heavily on Hyper-V as an upstream dependency for all of it's networking needs (and more), and this ticket was more about asking you guys what the right avenue to get this feedback in front of the right people in Microsoft would be, because I assume you work closely with the teams that manage these subsystems within Windows. 

If there were no way to submit feedback to Docker about how their direct dependencies completely break their software it'd be impossible to count on Docker working in any scenario.

Fair enough, though.

**Comment by stephen-turner** [comment]
We don't actually have a close link with those people. We do with the WSL 2 team, but not Hyper-V or networking. It's sufficiently mature that we don't generally get bug reports against it.

**Comment by JustinChristensen** [comment]
Got it. Thanks again for responding.
