### ISSUE TITLE
Docker Desktop Installer not starting

### ISSUE THREAD

**Issue by mvakili** [docker/for-win#12510]
- [x] I have downloaded the latest version of the Docker installer
  - [x] I have enabled Hyper-V feature
### Actual behavior
Docker Desktop installer does not start at all. 
When I click on the installer file nothing appears and no process starts.
When I run the docker installer from CMD (as Administrator) I get the following error:
```
Unhandled Exception: System.MissingMethodException: Method not found: 'Void NLog.Targets.FileTarget..ctor(System.String)'.
   at Docker.Core.Logger.Initialize(String filename, ConsoleMode consoleMode)
   at CommunityInstaller.Program.GetLogManager()
   at CommunityInstaller.Program.Run(String[] args)
   at CommunityInstaller.Program.Main(String[] args)
```
### Expected behavior
Docker installer should start.

### Information

  - Windows Version: Windows 10 Enterprise Build 19041
 
### Steps to reproduce the behavior

  1. Download Docker Desktop Installer from https://docs.docker.com/desktop/windows/install/
  2. Run CMD as administrator
  3. Run "Docker Desktop Installer.exe" from CMD

**Comment by ClaudioSousa14** [comment]
I have the same problem. Did you fix it?

**Comment by mvakili** [comment]
Yes, it has been fixed for me. but have no idea how it got solved.

The steps I followed are:
1. Reset windows from Windows 10 Settings menu (Didn't work out)
2. Removed files and folders in %HOMEPATH% that belonged to installed applications (Not sure if it helped)
3. Removed find and folders in my C (system) drive other than windows files and folders

The installer started to work after these steps. still not sure what was the cause of the problem.

**Comment by thematrixincendies** [comment]
Also had the same problem on Win 10 Pro 21H2. I was able to solve it by downloading NLog v4.7.15 and adding the .netstandard 2.0 assembly to the GAC. After that, the installation immediately started.

**Comment by L1ncx** [comment]
I encounter this in windows 11 Enterprise. After running the Docker Desktop Installer.exe

System.MissingMethodException: Method not found: 'Void NLog.Targets.ConsoleTarget.set_DetectConsoleAvailable(Boolean)'.
   at Docker.Core.Logger.Initialize(String filename, ConsoleMode consoleMode)
   at CommunityInstaller.Program.GetLogManager(ConsoleMode consoleMode)
   at CommunityInstaller.Program.Run(String[] args)
   at CommunityInstaller.Program.Main(String[] args)

**Comment by batterybae** [comment]
I had the same issue and spent many hours on it. I was finally able to resolve it after looking at this thread:
https://stackoverflow.com/questions/61811392/error-installing-docker-desktop-for-windows-10

There was an NLog folder part of C:\Windows\Microsoft.NET\assembly\GAC_MSIL and I deleted it. 
Immediately after that I was able to start the docker installer on version 4.11.0

**Comment by rios0rios0** [comment]
> I had the same issue and spent many hours on it. I was finally able to resolve it after looking at this thread: https://stackoverflow.com/questions/61811392/error-installing-docker-desktop-for-windows-10
> 
> There was an NLog folder part of C:\Windows\Microsoft.NET\assembly\GAC_MSIL and I deleted it. Immediately after that I was able to start the docker installer (version 4.11.0)

It worked! Thank you a lot!!!
