### ISSUE TITLE
Upgrade process fails, leaving Docker unusable

### ISSUE THREAD

**Issue by shawmanz32na** [docker/for-win#12521]
This has happened to me for the last 4 upgrades or so, although I can't provide exactly which version the behavior started.

When Docker upgrades itself, the installation process appears to stop halfway through. Docker does not restart automatically, and it appears that Docker is no longer installed.
![image](https://user-images.githubusercontent.com/5596570/151570143-c137a981-abd1-4cdf-ae9e-c0eff8d09989.png)

I've recovered from this situation each time by downloading the current Docker installer and run it. After reinstalling, all my images and containers are still available.

  - [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics - _not possible, Docker isn't installed/running_
  - Diagnostics ID: 

### Actual behavior

Instead of updating, Docker uninstalls itself.

### Expected behavior

Docker updates to the latest version.

### Information

This has happened to me for the last 4 upgrades or so, although I can't provide exactly which version the behavior started.

Here's the install log:
[install-log.txt](https://github.com/docker/for-win/files/7959647/install-log.txt)

  - Windows Version: Windows 10 Pro Windows 10 Pro (Build 19043)
  - Docker Desktop Version: 4.4.3 (73365)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

[docker-diagnose.txt](https://github.com/docker/for-win/files/7959760/docker-diagnose.txt)

### Steps to reproduce the behavior

From a user's perspective:
1. The Docker icon in the system tray shows the exclamation icon and hovering over it says that there's an update that will apply next time Docker is restarted.
2. Restart Windows (OR Open Docker and click "Apply Update" - the behavior is the same)
3. Sign back in to Windows
4. A UAC prompt appears for Docker. Select the Admin user and enter the Admin password
    - Per company policy, the actual Windows User I use does not have any admin abilities. There is a separate Administrator account for me to use when elevation is needed. I don't know if this matters for this issue, but seems to be an atypical thing to do, so I've mentioned it.
5. The Docker installer window pops up and scrolls a bunch of text like its doing something. It then closes.
6. Docker _does not_ restart and _is not_ available in the start menu to run.

**Comment by aawilson** [comment]
I'm having this issue today (the installer consistently hangs on `Unpacking file: System.Threading.Thread.dll`), but with the additional complication that downloading the installer manually from the website does _not_ resolve the issue, leaving me with no usable docker installation.
