### ISSUE TITLE
Personal Access Tokens cannot be used in Docker Desktop

### ISSUE THREAD

**Issue by anttikes** [docker/for-win#12526]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 8F855A8A-575A-4D0E-AFF0-C7EE82AAE94B/20220201103135

### Actual behavior
I have previously created a Personal Access Token on Docker Hub that allows "Read & Write" permission to my account. I copy-pasted the generated password to a Notepad document and verified that it matches what the Docker Hub showed.

### Steps to reproduce the behavior
1. Open Docker Desktop
2. Click 'Sign in'
3. Browser is opened
4. I enter my user name
5. I enter the password of the Personal Access Token
6. I click "Sign in"
7. I receive an error "Something went wrong"

### Expected behavior
I expect that signing in with Personal Access Tokens works without problems.

### Information
The problem can be reproduced every time. I have an open session in my browser for Docker Hub in another tab, and the first time I pressed 'Sign in' from Docker Desktop it actually tried to use this existing session for signing in. I do not want to do that as I want to limit what Docker Desktop can do on my behalf.

Windows Version: Windows 10 Pro, 10.0.19044 Build 19044
Docker Desktop Version: 4.4.4 (73704)
WSL2 or Hyper-V backend?  WSL2
Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

**Comment by nicks** [comment]
Hi @anttikes ! Thanks for reporting. You say: "I do not want to do that as I want to limit what Docker Desktop can do on my behalf." Can you share a little bit more about what you're trying to prevent Docker Desktop from doing?

Long-term, we're talking about making changes to how login works in Docker Desktop. e.g., how we might decouple logging in for identity from logging in for registry access for multiple registries. There are a few different idea for what this might look like but no concrete proposals yet. So I'd be curious to hear what you're trying to do!

We currently have no plans to allow you to log in from the UI with a Personal Access Token, so I'm going to close this ticket. You can still log in to the engine with the CLI.
