### ISSUE TITLE
Docker Desktop is shutting down.

### ISSUE THREAD

**Issue by fteklitz-mpg** [docker/for-win#12523]
Docker Desktop is shutting down.  See log for specifics
[log.txt](https://github.com/docker/for-win/files/7965258/log.txt)

************************************************************************************
*READ ME FIRST*

This repository is for reporting bugs with the Docker Desktop for Windows software,
which we respond to on a best-effort basis.

Do *not* paste logfiles into github issues: upload diagnostics instead, which are
only visible to Docker engineers.

Support requests in this repository (i.e., trouble installing or using the
software) will be ignored, but personalized support is available to Docker Pro and
Team customers at https://hub.docker.com/support/desktop/, and community support is
available from the Docker community Slack (https://www.docker.com/docker-community).

Issues without sufficient detail to debug them will be closed. They generally need
a clear title and description, steps to reproduce, and a diagnostics ID. See
https://docs.docker.com/docker-for-windows/troubleshoot/#diagnose-and-feedback for
how to generate a diagnostics ID either from inside the app or from the command line.
************************************************************************************

-->

  - [ x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Docker Desktop is shutting down. 

### Expected behavior
Expect application to work

### Information

  - Windows Version: Windows 10 Pro
  - Docker Desktop Version: 4.4.4 (73704)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Steps to reproduce the behavior
try to open Docker Desktop
A reproducible case, Dockerfiles with reproduction inside is best.
-->

  1. ...
  2. ...

**Comment by fteklitz-mpg** [comment]
Also tried doing a CLI command from VS Code powershell >>docker ps

Got the following message:

error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json": open //./pipe/docker_engine: The system cannot find the file specified.

Docker on VS Code also failed to connect

**Comment by fteklitz-mpg** [comment]
PS C:\Program Files\docker\docker\resources> .\com.docker.diagnose.exe
[030:12:32:35.596][I] ipc.NewClient: 06883a7c-com.docker.diagnose -> \\.\pipe\dockerBackendV2 com.docker.service.exe
[goroutine 1 [running, locked to thread]:
[win/backend/pkg/service.NewClientForPath(...)
[       win/backend/pkg/service/service.go:40
[win/backend/pkg/service.NewClient({0x106e8be, 0x13}, {0x0, 0x0, 0x0})
[       win/backend/pkg/service/service.go:29 +0xe8
[common/pkg/diagkit/gather/diagnose.init()
[       common/pkg/diagkit/gather/diagnose/ipc_windows.go:23 +0x11f

**Comment by fteklitz-mpg** [comment]
docker run --rm -it amazon/aws-cli                                                                              docker: error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/create": open //./pipe/docker_engine: The system cannot find the file specified.

**Comment by fteklitz-mpg** [comment]
I reloaded Docker Desktop.  It shows up on the Task menu, but does not bring up the UI.  See attached 

![Screenshot 2022-01-30 142312](https://user-images.githubusercontent.com/91699997/151714265-14541c64-1387-4abe-aa9e-e501cbe612eb.png)

**Comment by maunzCache** [comment]
Just wanted to express that i have the same issue. It started in 4.4.3 but continues on 4.4.4 as i manually updated today. From the changelog maybe its related to https://github.com/docker/for-win/issues/12500

**Comment by maunzCache** [comment]
Fix: Manually remove this file `<HOME>\AppData\Roaming\Docker\locked-directories`

I additionally run C:\Program Files\Docker\Docker\resources\com.docker.backend.exe
and closed it gracefully.

After that it worked for me though i haven't tried a reboot.

**Comment by goldenboy1991** [comment]
> Fix: Manually remove this file `<HOME>\AppData\Roaming\Docker\locked-directories`
> 
> I additionally run C:\Program Files\Docker\Docker\resources\com.docker.backend.exe and closed it gracefully.
> 
> After that it worked for me though i haven't tried a reboot.
> 
> Edit: Yes, works after a reboot as well

thanks, this is working for me

**Comment by lenomatos** [comment]
> AppData\Roaming\Docker\locked-directories

This is working for me

**Comment by GustaveRw** [comment]
> 

It worked after so long
