### ISSUE TITLE
Docker Desktop still displays "Switch to Windows containers..." after switching it to Windows containers

### ISSUE THREAD

**Issue by v-lianch** [docker/for-win#12538]
**Docker Desktop:** 4.5.0
**OS:** Win10 21H2/Win 11 21H2
**Regression from:** Previous release (4.4.4)

**Repro Steps:**
1. Install Docker Desktop 4.5.0.
2. Right click Docker Desktop icon from task bar.
3. Click "Switch to Windows containers...".
4. Click "Switch" when "Switch to Windows containers" dialog pops up.
5. After switching is finished, right click Docker Desktop icon from task bar again, check whether it displays "Switch to Linux containers..." or not.

**Expect:**
It displays "Switch to Linux containers...".
![image](https://user-images.githubusercontent.com/65064509/152947708-6a8b72ee-0d59-424a-9dfb-b8ebaa828196.png)

**Actual:** 
It still displays "Switch to Windows containers...".
![image](https://user-images.githubusercontent.com/65064509/152947300-affca592-35a7-4e4c-a7fc-2055ce1ba528.png)

**More info:** 
1. It actually switches to Windows containers successfully even though it still displays "Switch to Windows containers...".
2. At this time, we **cannot switch it back to Linux containers** by Docker Desktop menu.
3. This issue doesn't reproduce on 4.4.4.

**Comment by bwateratmsft** [comment]
As a workaround, you can switch back to Linux containers by running `"C:\Program Files\Docker\Docker\DockerCli.exe" -SwitchDaemon`

**Comment by StefanScherer** [comment]
It's fixed in the official DD 4.5.0 (74594) release. Thanks for the feedback!
