### ISSUE TITLE
Daemon setings page shows "Basic" after every restart

### ISSUE THREAD

**Issue by cs96and** [docker/for-win#1253]
### Expected behavior
After Docker For Windows starts up, the Daemon Settings page should be switched to "Advanced" if a custom daemon.json file is being used.

### Actual behavior
The Daemon settings page is always switched to "Basic" after Docker For Windows is started.

### Information
  - Diagnostic ID from "Diagnose & Feedback" in the menu.
34087118-3FF9-4C83-914B-50E2622F0FC9/2017-10-27_11-33-54
  - host distribution and version (Windows version, build number, etc)
Windows 10 Pro Version 1703 (OS Build 15063.674)
Version 17.09.0-ce-win33 (13620)

### Steps to reproduce the behavior

  1. Open the Docker Settings, and navigate to the Daemon page.
  2. Flick the switch to "Advanced", and enter a custom daemon.json
  3. Click Apply.
  4. Quit Docker
  5. Re-start Docker.
  6. Open Daemon settings page again, and the switch has gone back to "Basic".

Note that after a restart, even though the switch is set to "Basic" it will still be using your custom settings.

**Comment by thaJeztah** [comment]
ping @ebriney

**Comment by ebriney** [comment]
This is the same behaviour on mac, we can change that, I agree.
All the more so now you can edit the `daemon.json` file manually.
