### ISSUE TITLE
Docker does not work after installation

### ISSUE THREAD

**Issue by Thomas61197** [docker/for-win#12545]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features. I can't disable experimental settings bc I cannot access the settings.
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 538D3065-88EA-4B67-99F2-547648A8D2C2/20220211132529

### Actual behavior
When open the app it says docker stopped working...
setting page doesn't load.
Running the following from cmd gets me:
d:\Users\ThomasBoer\big_data>docker pull mtasnim/jupyter-pyspark-duckdb
Using default tag: latest
error during connect: This error may indicate that the docker daemon is not running.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/images/create?fromImage=mtasnim%2Fjupyter-pyspark-duckdb&tag=latest": open //./pipe/docker_engine: The system cannot find the file specified.

Getting this on startup after installing docker for some reason:
[startup_docker.txt](https://github.com/docker/for-win/files/8048978/startup_docker.txt)

![image](https://user-images.githubusercontent.com/56155415/153605808-5282df6c-e7cf-489e-b32f-276f6c7daabd.png)

![image](https://user-images.githubusercontent.com/56155415/153605982-229bd006-1fa7-4b5b-b161-7bed226c155b.png)

### Expected behavior
It working as it should.

### Information

  - Windows Version: 
Edition	Windows 10 Home
Version	21H1
Installed on	‎9/‎28/‎2020
OS build	19043.1526
Experience	Windows Feature Experience Pack 120.2212.4170.0

  - Docker Desktop Version: 
  d:\Users\ThomasBoer\big_data>docker version
error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version": open //./pipe/docker_engine: The system cannot find the file specified.
Client:
 Cloud integration: v1.0.22
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:44:07 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
diagnostics ID:
538D3065-88EA-4B67-99F2-547648A8D2C2/20220211132529

### Steps to reproduce the behavior

  1. Install docker
  2. sign out
  3. sign in
  4. start docker
  5. exit docker
  6. uninstall docker
  7. restart computer
  8. run docker installer as administrator
  9. run docker as administrator
  10. clean / purge data - all
  11. reset docker to factory settings
  12. restart computer

**Comment by mccaa25** [comment]
I am having the same issue. I can run lines in powershell to switch the daemon and this gets docker running and I can access the settings but cannot enable WSL2 integration. That option is still greyed out. I am on windows build 19044.1526, (so meets the 2004 minimum.)

**Comment by mccaa25** [comment]
These commands in powershell as administrator will get docker running but will not allow to use wsl2 based engine:
Step 1> cd "C:\Program Files\Docker\Docker"
Step 2> ./DockerCli.exe -SwitchDaemon

**Comment by leolnid** [comment]
I am having the same issue. And done the same steps :(

**Comment by mccaa25** [comment]
I went to release notes for Docker Desktop for Windows and downloaded 4.4.2, uninstalled 4.5.0 and installed 4.4.2 as administrator (not sure if this was necessary), and now it works fine. Spent 6 hours trying to get 4.5.0 to work. Clearly there is a bug in 4.5.0!

**Comment by mccaa25** [comment]
Im happy with 4.4 at this point. If it works. it is better than 4.5

**Comment by mccaa25** [comment]
** one point to note though, when I run 4.4.2 it does say there is an update to 4.4.4 so it might be worth grabbing this one if you want to roll back to an older one. I haven't tried updating to this but I think the problem occurs with 4.5, so 4.4.4 might be safe. 4.4.2 definitely works for me.

**Comment by mccaa25** [comment]
**Ok well, it "tricked" me into downloading 4.5.0 because it said it was going to update to 4.4.4,
However this time, 4.5.0 worked immediately. The WSL integration box is grayed out but this time it is checked! Before it was unchecked.

**Comment by RaczoOBY** [comment]
I'm having the same issue. Any updates about @mccaa25 ?

**Comment by mccaa25** [comment]
Yeah. After I downloaded 4.4.2 it worked on the first try (well second try but basically all I did was restart it. There was some different error the first time and i clicked continue or ignore or try again or something. Anyways, it just then started. The WSL2 integration option box was still grayed out but it was selected so I didnt need to change it anyways. Then I did try to update to 4.4.4 but it actually installed 4.5.0. But it worked fine and my container was still there and working fine. So it seems that by installing 4.4.2 and then updating to 4.5.0 worked ok.

**Comment by Thomas61197** [comment]
> I went to release notes for Docker Desktop for Windows and downloaded 4.4.2, uninstalled 4.5.0 and installed 4.4.2 as administrator (not sure if this was necessary), and now it works fine. Spent 6 hours trying to get 4.5.0 to work. Clearly there is a bug in 4.5.0!

this worked for me, thank you so much!

**Comment by mccaa25** [comment]
Did you install the earlier version which can be found in release notes? I
did 4.4.2. And then actually ended up updating to 4.5.0 from there after
running it successfully for a bit. And now 4.5.0 worked too.

**Comment by rahul3v** [comment]
Just go to the config file at `C:\Users\<username>\AppData\Roaming\Docker\settings.json`, and set  `"wslEngineEnabled": true`
that will fix this issue for `v4.5` :)

**Comment by mccaa25** [comment]
Great. Thanks.

**Comment by WapnerSensefarm** [comment]
> **FIX :** Just go to the config file at `C:\Users\<username>\AppData\Roaming\Docker\settings.json`, and set `"wslEngineEnabled": true` that will fix this issue for `v4.5` :)

Thank you @rahul3v , this fixed it for me 😊

**Comment by anuatreya** [comment]
> **FIX :** Just go to the config file at `C:\Users\<username>\AppData\Roaming\Docker\settings.json`, and set `"wslEngineEnabled": true` that will fix this issue for `v4.5` :)

Thank you @rahul3v, this issue fixed for me too :)

**Comment by mat007** [comment]
Hi, indeed there is an issue in Desktop 4.5.0 that defaults to disable the WSL 2 backend even for Windows Home where it’s the only one that should be available.

We will be releasing a Desktop 4.5.1 to fix this, but in the meanwhile [the fix](https://github.com/docker/for-win/issues/12545#issuecomment-1037225140) suggested by @rahul3v is correct.

**Comment by rahul3v** [comment]
Thank you for all those great emojis, I appreciate that :)

**Comment by mat007** [comment]
We have released Docker Desktop 4.5.1 to address this, see https://docs.docker.com/desktop/windows/release-notes/#docker-desktop-451

**Comment by stephanierifai** [comment]
[rahul3v](https://github.com/rahul3v) Thank you for helping folks while we worked to address this! Wondering if you would be open to chatting with us a bit more about Docker Desktop and how you use it day to day so we can continue to expand our use cases for test coverage. If so feel free to drop me a line at steph.rifai@docker.com and we can find a time.

If anyone else on this thread is interested in giving feedback, also feel free to reach out!
