### ISSUE TITLE
Inconsistent handling of insecure-registries between build and pull

### ISSUE THREAD

**Issue by crowne** [docker/for-win#12547]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: DA69F136-1880-46C7-88EB-80FAF110A06D/20220212070836

### Actual behavior
I am running an insecure registry-mirror, correctly configured in daemon.json (shown below).

I am building a custom keycloak image, the Dockerfile refers to the base image as follows:

`FROM mirrorhost.intra.net:30084/redhat/ubi8-minimal`

The build fails with error:
failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to do request: Head "https://mirrorhost.intra.net:30084/v2/redhat/ubi8-minimal/manifests/latest": http: server gave HTTP response to HTTPS client

However I can pull the image:
docker pull mirrorhost.intra.net:30084/redhat/ubi8-minimal

And after that the build succeeds.

If I remove the host and port from the reference in the Dockerfile then the build works,
although I get a different hash/image-id because it fetches directly from dockerhub and not from the mirror.
`FROM redhat/ubi8-minimal`

### Expected behavior
If I can pull then image then I would expect the build to be able to resolve it similarly without failing.

### Information

  - Windows Version: 10.0.19044 Build 19044
  - Docker Desktop Version: 4.4.4 (73704)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
Diagnostics were uploaded DA69F136-1880-46C7-88EB-80FAF110A06D/20220212070836

#### Dockerfile
``` Dockerfile
# based on https://github.com/keycloak/keycloak-containers/blob/main/server/Dockerfile
FROM mirrorhost.intra.net:30084/redhat/ubi8-minimal

ENV KEYCLOAK_VERSION 16.1.1
ENV JDBC_POSTGRES_VERSION 42.2.5
ENV JDBC_MYSQL_VERSION 8.0.22
ENV JDBC_MARIADB_VERSION 2.5.4
ENV JDBC_MSSQL_VERSION 8.2.2.jre11

ENV LAUNCH_JBOSS_IN_BACKGROUND 1
ENV PROXY_ADDRESS_FORWARDING false
ENV JBOSS_HOME /opt/jboss/keycloak
ENV LANG en_US.UTF-8

ARG GIT_REPO
ARG GIT_BRANCH
ARG KEYCLOAK_DIST=https://github.com/keycloak/keycloak/releases/download/$KEYCLOAK_VERSION/keycloak-$KEYCLOAK_VERSION.tar.gz

USER root

RUN microdnf update -y && microdnf install -y glibc-langpack-en gzip hostname java-11-openjdk-headless openssl tar which && microdnf clean all

ADD src/main/container/tools /opt/jboss/tools
RUN /opt/jboss/tools/build-keycloak.sh

COPY target/keycloak-mjh-*.jar /opt/jboss/keycloak/standalone/deployments/

USER 1000

EXPOSE 8080
EXPOSE 8443

ENTRYPOINT [ "/opt/jboss/tools/docker-entrypoint.sh" ]

CMD ["-b", "0.0.0.0"]
```

#### daemon.json
``` json
{
  "bip": "192.168.1.1/24",
  "builder": {
    "gc": {
      "defaultKeepStorage": "20GB",
      "enabled": true
    }
  },
  "debug": false,
  "experimental": false,
  "features": {
    "buildkit": true
  },
  "insecure-registries": [
    "mirrorhost.intra.net:30084"
  ],
  "registry-mirrors": [
    "http://mirrorhost.intra.net:30084"
  ]
}
```

**Comment by slonopotamus** [comment]
You should report this to https://github.com/moby/moby instead.
