### ISSUE TITLE
Docker build on windows of MSYS hangs

### ISSUE THREAD

**Issue by LewisPringle** [docker/for-win#12543]
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID:94D8C98C-EA49-4C6A-858B-4E902A336922/20220210160818

### Actual behavior
docker build hangs
### Expected behavior
docker build doesn't hang
### Information

  - Windows Version: windows 11 21H2 - 22000.493)
  - Docker Desktop Version: 4.4.4 (73704)
  - WSL2 or Hyper-V backend?  using windows containers (so probably hyerpv backend)
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
[041:11:09:49.574][I] ipc.NewClient: 1bb60ee1-com.docker.diagnose -> \\.\pipe\dockerBackendV2 com.docker.service.exe
[goroutine 1 [running, locked to thread]:
[win/backend/pkg/service.NewClientForPath(...)
[       win/backend/pkg/service/service.go:40
[win/backend/pkg/service.NewClient({0xe1e8be, 0x13}, {0x0, 0x0, 0x0})
[       win/backend/pkg/service/service.go:29 +0xe8
[common/pkg/diagkit/gather/diagnose.init()
[       common/pkg/diagkit/gather/diagnose/ipc_windows.go:23 +0x11f
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0023: is the Containers Windows Feature enabled?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.
### Steps to reproduce the behavior

  1. Download dockerfile (whole directory) from https://github.com/SophistSolutions/Stroika/tree/6383303/DockerBuildContainers/Windows-MSYS-VS2k19 (mostly just need dockerfile)
  2. docker build -f Windows-MSYS-VS2k19/Dockerfile -t sophistsolutionsinc/stroika-buildvm-windows-msys-vs2k19 .

the first part - installing visual studio works fine, but the part installing msys docker - hangs. This worked fine until a few days ago. It maybe releated to changes in that version of msys, windows, or a new docker update (I think it was the new docker update).

NOTE - this is the SAME issue as https://github.com/docker/for-win/issues/8910 - which you have CLOSED errantly, and left no obvious way for me to re-open.

Note also - the workaround suggested in 8910: installing procman and finding what file its infinite looping on, and deleting it - does appear to work (though not sure this is a good answer).

**Comment by LewisPringle** [comment]
Additional details on my steps to workaround the problem ( from https://stroika.atlassian.net/browse/STK-766)

run MSYS shell as administrator

cd /c/ProgramData/Docker/tmp

wait for hang (after you see:

~~~

atabase directory: /var/lib/pacman/:: Do you want to remove unused repositories? [Y/n]removing unused sync repositories...

~~~

look for directory like 

   hcs338366986 (sole directory - if multiple still not hung)

rm -rf  hcs338366986/Files/'$Recycle.Bin

**Comment by slonopotamus** [comment]
I believe this should be reported to https://github.com/moby/moby/ instead of current repo.
