### ISSUE TITLE
Windows image build reports "There is not enough space on the disk"

### ISSUE THREAD

**Issue by hatboyzero** [docker/for-win#12556]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

A Docker build operation for a Windows image fails on COPY, indicating that there is not enough space on the disk.

```
PS D:\Projects\Redacted> docker build --build-arg GAME_VERSION=0.0.0.0-t redacted.azurecr.io/redacted:0.0.0.0 .
Sending build context to Docker daemon  25.01GB
Step 1/19 : ARG AGENT_IMAGE=redacted.azurecr.io/redacted:latest
Step 2/19 : FROM $AGENT_IMAGE
 ---> 4252c452fb99
Step 3/19 : ARG PRODUCT_PATH="."
 ---> Using cache
 ---> 0e1e694ea72f
Step 4/19 : COPY "$PRODUCT_PATH\\Assets" "C:\\Assets"
failed to copy files: failed to copy directory: write \\?\Volume{d2590663-ff1a-44f8-a9d4-add96999f286}\Assets\redacted: There is not enough space on the disk.
PS D:\Projects\Redacted> 
```

### Expected behavior

The docker build operation completes the Docker Windows image build, or at least manages to execute the COPY operation without reporting that there is not enough space on the disk.

### Information

  - Windows Version: Windows 10 Pro 20H2
  - Docker Desktop Version: 4.4.4 (73704)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

**Comment by hatboyzero** [comment]
[docker.diagnosis.txt](https://github.com/docker/for-win/files/8064036/docker.diagnosis.txt)

**Comment by slonopotamus** [comment]
There is a bug in Docker itself, you cannot COPY more than 20GB in Windows containers. It was fixed in https://github.com/moby/moby/pull/41636, but that fix isn't present in any released Docker version.
