### ISSUE TITLE
An error occurred (Docker is stopping... 4.5.1)

### ISSUE THREAD

**Issue by code-grey** [docker/for-win#12559]
- [x ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: CE233117-6EBC-4ADE-A299-1A03F0D71509/20220215151347

### Actual behavior
Throws an error saying that failed to deploy distro docker-desktop with this error code: 0x80041002
### Expected behavior
Docker Should start normally without any error
### Information

  - Windows Version: Meets the requirements
  - Docker Desktop Version: 4.5.1
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
1 : The test: are WSL distros installed?
    Failed with: WSL Distribution docker-desktop is missing

The Docker engine uses several WSL distributions. Therefore these must be installed.

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by judexco** [comment]
![image](https://user-images.githubusercontent.com/30628190/154758241-8cf2f4eb-4ea3-4838-8e32-b81ef1cab5c5.png)

i have similar issue pls help to resolve

**Comment by justinjeffery-ipf** [comment]
4.5.1 also gives me the same issue.

**Comment by code-grey** [comment]
> 
> 
> 
>   - [x ] I have tried with the latest version of Docker Desktop
>   - [ ] I have tried disabling enabled experimental features
>   - [x ] I have uploaded Diagnostics
>   - Diagnostics ID: CE233117-6EBC-4ADE-A299-1A03F0D71509/20220215151347
> 
> ### Actual behavior
> Throws an error saying that failed to deploy distro docker-desktop with this error code: 0x80041002
> ### Expected behavior
> Docker Should start normally without any error
> ### Information
> 
>   - Windows Version: Meets the requirements
>   - Docker Desktop Version: 4.5.1
>   - WSL2 or Hyper-V backend?  WSL2
>   - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No
> 
> ### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
> 1 : The test: are WSL distros installed?
>     Failed with: WSL Distribution docker-desktop is missing
> 
> The Docker engine uses several WSL distributions. Therefore these must be installed.
> 
> ### Steps to reproduce the behavior
> 
> 
>   1. ...
>   2. ...
> 

It got fixed automatically in a Windows update. (Most probably in KB5010342)
