### ISSUE TITLE
Settings screen error on loading, Docker Settings Page issue | Not able to run Docker with error "Docker Desktop stopped

### ISSUE THREAD

**Issue by sarvesh4** [docker/for-win#12552]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 06F24A13-A8E7-4FFD-A55B-F6FD851F1C8D/20220213185037

### Actual behavior
Settings page is stuck in a never ending circle of a loading box. Docker never really starts after installing

### Expected behavior
Settings page should load also Docker should be starting

### Information

  - Windows Version: 11
  - Docker Desktop Version:  Docker version 20.10.12, build e91ed57
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. ...
![image](https://user-images.githubusercontent.com/11473444/153770244-2261cd14-19c8-4025-9f33-751efd9b36a0.png)

  2. ...
  
![image](https://user-images.githubusercontent.com/11473444/153770263-1779c5ed-c24e-4d2f-a50c-8466e895aec9.png)

**Comment by bitjerry** [comment]
Me too
Windows 10
Docker version 20.10.12, build e91ed57
Hyper-V

**Comment by jarodpeachey** [comment]
I'm having the same issue, Windows 10 with WSL2

**Comment by junace123** [comment]
me too is there any solutions???  Windows 10 
l had updated windows and redownloaded docker but didn't solved

**Comment by mat007** [comment]
Looks similar to #12545?
