### ISSUE TITLE
Docker Settings Page issue | Not able to run Docker with error "Docker Desktop stopped..." 

### ISSUE THREAD

**Issue by ra2g** [docker/for-win#12551]
- [X ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID:
D52A1726-7BE8-42F5-A66C-E5888C5C6F6A/20220213155215

### Actual behavior
Settings page is stuck in a never ending circle of a loading box

### Expected behavior
Settings page should load correctly and allow the user to access various tabs etc.,

### Information
Looks similar to this issue:
1. https://github.com/docker/for-mac/issues/4239#issue-557076088 (Was for MacOS)
2. https://github.com/docker/for-win/issues/6211 (Windows user)

I have tried all the possible resolutions provided such as:
1. Uninstalling and reinstalling Docker
2. Linux Kernel update (WSL)
3. Ubuntu uninstall and reinstall

Settings page load error:
![image](https://user-images.githubusercontent.com/99606291/153765419-5dfb4802-d152-4701-b5f0-c9951dd3b153.png)

Restart Docker Desktop not working from GUI:
![image](https://user-images.githubusercontent.com/99606291/153765438-70a2af29-45f2-4ae4-bc9d-603293dffe7a.png)

Landing page when Docker is initialized
![image](https://user-images.githubusercontent.com/99606291/153765491-259372e8-a67e-4c81-92a0-dc60117b65c2.png)

-->
  - Windows Version: 10.0.19043 Build 19043
  - Docker Desktop Version: 4.5.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Flygrounder** [comment]
I am experiencing the same issue as you.

Diagnostics: [link](https://pastebin.com/iENyuJ23)

**Comment by mat007** [comment]
Hi, thanks for reporting, and sorry about the inconvenience, I’ll close this issue in favor of #12545 which has a temporary [workaround](https://github.com/docker/for-win/issues/12545#issuecomment-1037225140) until we release Desktop 4.5.1
