### ISSUE TITLE
Docker on Windows Insider build 17025

### ISSUE THREAD

**Issue by yrest** [docker/for-win#1255]
Hello there, have tried reinstalling both stable and edge versions. Last thing I have done is docker factory reset.

### Expected behavior
"docker run" should execute the container.

### Actual behavior
fails to start in powershell

### Information

  - Diagnostic ID:  F96E25DF-D984-4430-A57B-A7DB36931DA2/2017-10-27_16-11-23
  - a reproducible case cannot be presented as it is from private repository
  - Windows 10 Insider preview build 17025.

getting the following error
docker : C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container 28a36b152c6ba0051cd4e0111a45add54cdec08bcd133cbd2b2bac2da2375b4e 
encountered an error during CreateContainer: failure in a Windows system call: The description string for parameter reference (%1) could not be found.

**Comment by friism** [comment]
@guillaumerose you've fixed this, right?

**Comment by yrest** [comment]
To clarify, my issue seems to be with Windows container, because nginx runs ok.

**Comment by yrest** [comment]
Also, as an example the following script 

$imageNameTag = "microsoft/nanoserver"
docker rm nanoserver -f
docker pull $imageNameTag
docker run -m 2G --name nanoserver `
           --hostname nanoserver `
           $imageNameTag

fails with 

docker : C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container 1baf32671e1e1048d228f5003582bfee00f0b603b799af788933701eca1342f1 
encountered an error during CreateContainer: failure in a Windows system call: The description string for parameter reference (%1) could not be found. (0x3ab6) extra 
info: {"SystemType":"Container","Name":"1baf32671e1e1048d228f5003582bfee00f0b603b799af788933701eca1342f1","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPat
h":"C:\\ProgramData\\Docker\\windowsfilter\\1baf32671e1e1048d228f5003582bfee00f0b603b799af788933701eca1342f1","Layers":[{"ID":"839d976c-4930-5f74-98de-65e9bfdedbe0","Pat
h":"C:\\ProgramData\\Docker\\windowsfilter\\9f119183a3f92c8823da15d234e374832089dbf0734cefc1bd1b5017620a9f7c"},{"ID":"126f858e-5acc-5d0a-b13a-786497ebc6e7","Path":"C:\\P
rogramData\\Docker\\windowsfilter\\ef92f9ce0346c13ad2759e106529ee1a40684158e162f695f8bd2dcf7c8b664c"}],"MemoryMaximumInMB":2048,"HostName":"nanoserver","HvPartition":tru
e,"EndpointList":["94657f07-670b-4dd5-a7f4-b1c30dacfebe"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\9f119183a3f92c8823da15d234e374832089dbf0734ce
fc1bd1b5017620a9f7c\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}.
At C:\Docker\nanoserver.ps1:4 char:1
+ docker run -m 2G --name nanoserver `
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Program File...NSQuery":true}.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by little-eyes** [comment]
I have the same problem when running docker build and docker run.

docker: Error response from daemon: container 6b6c482be54743fc946ca9b1debc5a4a7b297517b1eb2502c8d3734a1c1d91ba encountered an error during CreateContainer: failure in a Windows system call: The description string for parameter reference (%1) could not be found. (0x3ab6) extra info: {"SystemType":"Container","Name":"6b6c482be54743fc946ca9b1debc5a4a7b297517b1eb2502c8d3734a1c1d91ba","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"F:\\Hyper-V\\Docker\\windowsfilter\\6b6c482be54743fc946ca9b1debc5a4a7b297517b1eb2502c8d3734a1c1d91ba","Layers":[{"ID":"7ee95063-bac3-555a-99ba-7e5ee12addfc","Path":"F:\\Hyper-V\\Docker\\windowsfilter\\2af3d6e1387a611a599183776f394f87f16e4054f39fa480dc23a1de07d7a976"},{"ID":"0c871bda-9acf-5aed-9e44-7fbbb0038956","Path":"F:\\Hyper-V\\Docker\\windowsfilter\\e6409f2499a22d3eaed414307705d58e69288730eb09c916ecff268adb3d8382"},{"ID":"204ac590-8979-5c8c-a550-1b8455e32955","Path":"F:\\Hyper-V\\Docker\\windowsfilter\\1a6176e89e50f955e9baba0c1fc545963b028d38155fbb63b91a15419a94c6e6"},{"ID":"67d496cd-9034-59fc-b0cd-71b67f04d704","Path":"F:\\Hyper-V\\Docker\\windowsfilter\\aa1ea39e69e634c513096df0bec096f1b9f0b371e6ed69fab4adffd7a2612cd1"},{"ID":"26ca8b5b-5aa0-5e19-b248-89f15474ff72","Path":"F:\\Hyper-V\\Docker\\windowsfilter\\86976611aec984480951afb89e0b9856013b161fbab458826252e84ab2cc2904"},{"ID":"ef17e589-d6d8-5224-9d79-6023ecea7f25","Path":"F:\\Hyper-V\\Docker\\windowsfilter\\870f8cfe46d3a18d7e1d5aae9d621ce8dfd9f06d8365aa372e7d762d6e9dc563"},{"ID":"8800a1d3-20d1-53aa-9db1-2262fc8c6759","Path":"F:\\Hyper-V\\Docker\\windowsfilter\\92a6bb4fb978a508efdf6695a5ac86f93dfc18833046e650de5744a1342576da"},{"ID":"1972158c-8d98-5192-8301-69ba2798745f","Path":"F:\\Hyper-V\\Docker\\windowsfilter\\7a676be5b6d31ce45367d95f240c8ebb11e65d2c697cd0d1fade7e6b4ffb1002"},{"ID":"ab08037b-6c00-5d46-b8ed-f34f5ba25dbe","Path":"F:\\Hyper-V\\Docker\\windowsfilter\\35d2c8c54dadd44bc1742863279505c7b456d46ca0f2621b29638f12edeef30e"},{"ID":"4bb243ce-c66e-57c4-abd6-cb7b0d557772","Path":"F:\\Hyper-V\\Docker\\windowsfilter\\b79340361e6ed71629b8ddcb6350ef4be66273adce04e89be527ffe822be2d6c"},{"ID":"58243e8e-cdaf-5fbd-81ec-2354a3cd70f3","Path":"F:\\Hyper-V\\Docker\\windowsfilter\\bf91b910ed80af216ed7c65fac26b29b7f8d9e7f78e040a7518fbb2846c75561"},{"ID":"8b85d20c-c335-52f4-8c23-ed732fdeb909","Path":"F:\\Hyper-V\\Docker\\windowsfilter\\040eb837b68b3a9d843e104219a3170644cb56aab5029f1d12feb79070750283"}],"HostName":"6b6c482be547","HvPartition":true,"EndpointList":["50e3487b-d6f9-4893-b417-86331c50ea45"],"HvRuntime":{"ImagePath":"F:\\Hyper-V\\Docker\\windowsfilter\\bf91b910ed80af216ed7c65fac26b29b7f8d9e7f78e040a7518fbb2846c75561\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}.

---
$ docker info                                                               
Containers: 1                                                               
 Running: 0                                                                 
 Paused: 0                                                                  
 Stopped: 1                                                                 
Images: 7                                                                   
Server Version: 17.09.0-ce                                                  
Storage Driver: windowsfilter                                               
 Windows:                                                                   
Logging Driver: json-file                                                   
Plugins:                                                                    
 Volume: local                                                              
 Network: ics l2bridge l2tunnel nat null overlay transparent                
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog            
Swarm: inactive                                                             
Default Isolation: hyperv                                                   
Kernel Version: 10.0 17025 (17025.1000.amd64fre.rs_prerelease.171020-1626)  
Operating System: Windows 10 Enterprise Insider Preview                     
OSType: windows                                                             
Architecture: x86_64                                                        
CPUs: 8                                                                     
Total Memory: 23.93GiB                                                      
Name: jilli-dev                                                             
ID: 4CPZ:B75Z:WHIU:EZ35:HGOF:ELWP:QZXQ:WDNV:STUT:VWXI:RH7Y:JZQT             
Docker Root Dir: F:\Hyper-V\Docker                                          
Debug Mode (client): false                                                  
Debug Mode (server): true                                                   
 File Descriptors: -1                                                       
 Goroutines: 27                                                             
 System Time: 2017-11-02T21:34:13.1133139-07:00                             
 EventsListeners: 0                                                         
Registry: https://index.docker.io/v1/                                       
Experimental: true                                                          
Insecure Registries:                                                        
 127.0.0.0/8                                                                
Live Restore Enabled: false

**Comment by yrest** [comment]
I can see there was an update released today and when my docker tried installing that, it failed with docker.exe access denied. On a side note, last few versions never succeeded updating, always failing so I need to download it and manually install.
Anyhow, I managed to download Edge channel and installed 
Version 17.11.0-ce-rc2-win37 (13978)
Channel: edge
19d223a

Run the following
$imageNameTag = "microsoft/nanoserver"
docker rm nanoserver -f
docker pull $imageNameTag
docker run -m 2G --name nanoserver `
           --hostname nanoserver `
           $imageNameTag

and get same error

docker : C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container 3ba46239f3916c08558563d901d78ff22816cc51d03ab0e50986b109ff1555c8 
encountered an error during CreateContainer: failure in a Windows system call: The description string for parameter reference (%1) could not be found.

Is it the latest version or should I attempt stable CE?

Diagnostic id F96E25DF-D984-4430-A57B-A7DB36931DA2/2017-11-03_09-44-45

**Comment by shawngib** [comment]
Interesting, I have the same problem with Edge version. I have uninstalled and reinstalled. 

Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 8
Server Version: 17.11.0-ce-rc2
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17030 (17030.1000.amd64fre.rs_prerelease.171027-1609)
Operating System: Windows 10 Enterprise Insider Preview
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 7.927GiB
Name: MYSURFACEBOOK
ID: 2JGG:IROP:5JPV:EHJR:6CD3:DVYU:3B2D:GEMG:7QJZ:SEEP:WW5L:2GGZ
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 28
 System Time: 2017-11-03T13:40:43.5153939-04:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by ducke** [comment]
Same problem here:
`C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container d5006811989a9fd88ea7f76ee6fc5faa5c926a1eaa80bed7be1221caf68c73a5 encountered an error during CreateContainer: failure in a Windows system call: The description string for parameter reference (%1) could not be found. (0x3ab6) extra info: {"SystemType":"Container","Name":"d5006811989a9fd88ea7f76ee6fc5faa5c926a1eaa80bed7be1221caf68c73a5","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\d5006811989a9fd88ea7f76ee6fc5faa5c926a1eaa80bed7be1221caf68c73a5","Layers":[{"ID":"496cb896-cfc5-5a16-8490-eb1c3cb829fe","Path":"C:\\ProgramData\\Docker\\windowsfilter\\7093eea5a9df556b79a65eb304775abc6e10ec39be40d55f1ea0375176e04c69"},{"ID":"d8d27ae6-f2fd-51e3-bf9d-3c36211db62c","Path":"C:\\ProgramData\\Docker\\windowsfilter\\a6068870d5de4464abe6d23a70095e24a7763a3ff31fe526bfbd1bebfb01cf5e"},{"ID":"90bea18c-8ad7-55dd-a9a2-666c3a9d18f4","Path":"C:\\ProgramData\\Docker\\windowsfilter\\3fceede37f5b1a5de0b743bd94795f29af0133b48129b457deb8ba5545536169"}],"HostName":"d5006811989a","HvPartition":true,"EndpointList":["2fbe3158-e6b5-4f99-a0f6-b259a874cd22"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\a6068870d5de4464abe6d23a70095e24a7763a3ff31fe526bfbd1bebfb01cf5e\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}.`
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 3
Server Version: 17.09.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17025 (17025.1000.amd64fre.rs_prerelease.171020-1626)
Operating System: Windows 10 Pro Insider Preview
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 15.87GiB
Name: DESKTOP-3N5U8KK
ID: OWT5:Y4BL:AGEF:4HPW:XJOT:ZM6U:TIXR:AG6A:DH7O:EMTR:SWV3:6CLM
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 29
 System Time: 2017-11-05T21:52:53.7143538+01:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

![image](https://user-images.githubusercontent.com/708405/32419072-986fb25c-c274-11e7-9d5c-23adbb98eb78.png)

**Comment by ducke** [comment]
Found a solution!
Need to pull special images from Microsoft.
`microsoft/nanoserver:1709`
or
`microsoft/windowsservercore:1709`

**Comment by yrest** [comment]
IMHO MS fundamentally messed up something.

1709: Pulling from microsoft/nanoserver
407ada6e90de: Pulling fs layer
ad09b0550b6c: Pulling fs layer
ad09b0550b6c: Verifying Checksum
ad09b0550b6c: Download complete
407ada6e90de: Verifying Checksum
407ada6e90de: Download complete
407ada6e90de: Pull complete
ad09b0550b6c: Pull complete
Digest: sha256:88729c1cbf6a2df6967dccd14f13bbc1bb5219e3f644761c036e706ed0f0c609
Status: Downloaded newer image for microsoft/nanoserver:1709
docker : C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container 28c710f304dd46f8bff7deb20b74a677441e2a8c59a1aafe7d70898ab53ef523 
encountered an error during CreateContainer: failure in a Windows system call: The description string for parameter reference (%1) could not be found.

**Comment by yrest** [comment]
This issue has now rolled into https://github.com/docker/for-win/issues/1302

**Comment by santiagovm** [comment]
@ducke pulling `microsoft/nanoserver:1709` did not help, same error

**Comment by JackUkleja** [comment]
I'm also having this issue on microsoft/nanoserver:1709 running on Win10 17025

**Comment by sweikelt** [comment]
same problem here.....i just wanted to use docker the first time and i thought i'm doing something wrong...b

**Comment by yrest** [comment]
@sweikelt , thanks for your feedback! Please upvote https://aka.ms/Tvn78u in FBH to make them aware of the issue.

**Comment by kevinbosman** [comment]
I've been seeing the same symptoms since upgrading to 17025 on the slow ring. Changing between Stable/Edge, and completely uninstalling, rebooting, reinstalling makes no difference.

There's an error in the EventLog under Hyper-V-Compute for each failure with Id 12000: `Failed to create the Virtual Machine for Hyper-V Container` with ErrorMessage `%%2147778582` and ErrorCode `0x80048016`

I ran `Debug-ContainerHost.ps1` from https://github.com/MicrosoftDocs/Virtualization-Documentation/tree/master/windows-server-container-tools/Debug-ContainerHost and got a single error:
```
 [-] A Windows NAT is configured if a Docker NAT network exists 618ms
   Expected {0} to be greater than or equal to {1}
   221:        $winnatCount | Should Not BeLessThan $natCount
   at <ScriptBlock>, C:\Users\kevin\Downloads\Debug-ContainerHost.ps1: line 221
```

`Get-NetNat` returns nothing.

So as suggested I ran `New-NetNat -Name nat -InternalIPInterfaceAddressPrefix 172.25.32.0/20` (this was the subnet returned by `docker network inspect nat`). That errors immediately as follows:
```
New-NetNat : You were not connected because a duplicate name exists on the
network. If joining a domain, go to System in Control Panel to change the computer
name and try again. If joining a workgroup, choose another workgroup name.
At line:1 char:1
+ New-NetNat -Name nat -InternalIPInterfaceAddressPrefix 172.25.32.0/20
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_NetNat:root/StandardCimv2/MSFT_N
   etNat) [New-NetNat], CimException
    + FullyQualifiedErrorId : Windows System Error 52,New-NetNat
```

My PC definitely does not have a duplicate name on our local network, so this is something else.

I have not been able to proceed further. Any suggestions?

**Comment by gh2k** [comment]
@kevinbosman I've got exactly the same issue, but I'm sure if maybe this should be a separate issue?

**Comment by yrest** [comment]
@gh2k , when you execute "docker run", what do you get?

**Comment by gh2k** [comment]
@yrest `docker run` what? I can `docker run -ti microsoft/windowsservercore:1709 powershell` and it works, including ping access to outside. (e.g. `ping 8.8.8.8` works)

**Comment by yrest** [comment]
@gh2k , docker run anything :)
for me, since 17025, no matter what I try for Windows containers, I always get the same error : 

PS C:\WINDOWS\system32> docker run -ti microsoft/windowsservercore:1709 powershell
docker : C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container 1f712c2fc8b16b737157e5e5b53ba382b707dbcfce8ed736d4f5bf1068b2a9db 
encountered an error during CreateContainer: failure in a Windows system call: The description string for parameter reference (%1) could not be found. (0x3ab6) extra

**Comment by jonstelly** [comment]
I'm getting this when running a `docker build .` and it happens on the 'mkdir site;' line.  If I comment that out, the image builds fine.  This is a simple base image I use for other IIS images, so if I remove the mkdir, this base image creates fine, but in those images, if I try to mkdir, I get the same error.

```
FROM microsoft/aspnet

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN mkdir c:\site;

COPY ./msdeploy/ ./msdeploy/

```

**Comment by yrest** [comment]
On 17046 the following worked for me.


This is a bug in Windows and we have a fix coming in the next flight... As a workaround you can temporarily disable our cloning optimization by creating a registry key and rebooting or restarting the vmcompute service. reg ADD "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Virtualization\Containers" /v TemplateVmCount /t REG_DWORD /d 0 

But be sure to delete the key after you take the next flight or your container starts will remain slower...
--

**Comment by jonstelly** [comment]
That also works for me on 17025.  Thanks for that.

**Comment by 9Rune5** [comment]
My build server runs on Windows Server 2016... What to do there?

**Comment by ryankmcintyre** [comment]
Worked here, too. Thanks @yrest !

**Comment by HollisTech** [comment]
yrest hack works. Thanks!

**Comment by knilecrack** [comment]
Yeah it works on 17025. well played.
