### ISSUE TITLE
Docker desktop not running after update

### ISSUE THREAD

**Issue by chemarev** [docker/for-win#12562]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E4848F34-C0AA-48AF-86FF-889C12D3A48B/20220217035951

### Actual behavior
Error window with:
```
An error occurred

System.InvalidOperationException:
System.InvalidOperationException:
Failed to set version to docker-desktop: exit code: -1
 stdout: @54?@8=OB0O 

stderr: 
   в Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) в C:\workspaces\PR-17296\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:строка 146
   в Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() в C:\workspaces\PR-17296\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\WSL2Provisioning.cs:строка 81
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__28.MoveNext() в C:\workspaces\PR-17296\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:строка 178
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() в C:\workspaces\PR-17296\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:строка 29
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() в C:\workspaces\PR-17296\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:строка 67
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() в C:\workspaces\PR-17296\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:строка 92
```

### Expected behavior
Run Docker with Docker Desktop

### Information

  - Windows Version: 10 Pro 20H2
  - Docker Desktop Version: 4.5.1 (74721)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
```
Please investigate the following 1 issue:

1 : The test: is WSL installed?
    Failed with: exit status 0xffffffff

The Docker engine runs inside a WSL environment. Therefore WSL must be installed. Try running `wsl --status`.
```

### Steps to reproduce the behavior

  1. Install WSL2
  2. Update Docker Desktop to 4.5.1

P.S. Today I've got the message to install WSL2 for something needs of Docker Linux Kernel (or something like this). After downloading and installing I've got the situation above.
P.P.S. Diagnostic failed with test of WSL installation, but I can run it in command line.

**Comment by laurazard** [comment]
Could you share the output of the command `wsl -l -v`?

**Comment by ghost23** [comment]
I have the same problem. Output of wsl -l -v for me is:

```
  NAME            STATE           VERSION
* Ubuntu-20.04    Running         2
```

If I tried to start Docker Desktop and could not see anything happening and THEN run `wsl --shutdown` I immediately see the Docker Desktop client popping up and saying "Docker Desktop stopped ..."

**Comment by chemarev** [comment]
Sorry for answer delay. I have solved this problem, so now the output of the command `wsl -l -v` shows me `Debian` as well as `docker-desktop`. On the problem moment it was the same output as that of @ghost23.

[The advice that helped me](https://github.com/microsoft/WSL/issues/4177#issuecomment-597736482)

I really have Proxifier on my computer. As I understand the problem was connected with communication between  `winsock` and `wsl2`.
