### ISSUE TITLE
Docker CE is hanging when attempting to run any Windows container

### ISSUE THREAD

**Issue by lanovoy** [docker/for-win#1256]
### Expected behavior
With Windows containers selected executing docker run hello-world:nanoserver should output a message to the console and exit back to the command line.
### Actual behavior
docker run hello-world:nanoserver  is hanging without any output for hours.
### Information

Diagnostic ID 
57BD81D5-5C62-48E8-9277-F24A3A436160/2017-10-27_18-54-51
Consistently reproducible for the whole team trying to run Windows containers using Windows Server 2016 and with both stable and edge versions of the Docker. 

The Linux containers are properly working. 

Windows Server 2016 Standard Ver. 1607 (OS Build 14393.1770) with all latest patches.

### Steps to reproduce the behavior

  1. With Docker for Windows switch to the Windows containers.
  2. Run powershell as Administrator
  3. Execute docker run hello-world:nanoserver

**Comment by friism** [comment]
Does it work if you remove Docker for Windows and install the windows-only daemon? https://docs.docker.com/engine/installation/windows/docker-ee/

**Comment by lanovoy** [comment]
@friism Yes, I've tried docker EE as well with the same results.
Now actually I just was able to run the windows container using --isolation=hyperv. So looks like Hyper-v Windows Containers do actually work. Any ideas what can be wrong with the non-hyper-v?

**Comment by friism** [comment]
No, please post more details here (eg. runtime environment, etc.)

Please also open a support case with Microsoft support - Docker EE on Windows Server is supported jointly with Microsoft

**Comment by lanovoy** [comment]
@friism Thank you for your assistance. What exactly do you mean by the runtime environment?

docker info:

Containers: 39
 Running: 0
 Paused: 0
 Stopped: 39
Images: 3
Server Version: 17.10.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1770.amd64fre.rs1_release.170917-1700)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 15.91GiB
Name: EPPLGDAW0245
ID: YACN:6AMC:DBKE:W42E:MPZN:4NK2:YGWD:X2OX:D75K:JNCA:Y3ZZ:7OQU
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 36
 System Time: 2017-10-28T10:32:40.9668517+02:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

docker version:

Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:00:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:09:12 2017
 OS/Arch:      windows/amd64
 Experimental: true


Detailed system info (dxdiag) [https://pastebin.com/1C7RffE1](url)

**Comment by lanovoy** [comment]
So installed Win Server 2016 as Hyper-v VM, enabled nested virtualization on the host, added Hyper-v role and Containers feature inside the VM, installed Docker CE (Edge), switched to Windows Containers and tried to execute docker run hello-world:nanoserver - it works. So there is something wrong with the host machine... Could be related to Symantec Endpoint Protection, but unfortunately I cannot uninstall it by the company rules.

**Comment by lanovoy** [comment]
SEP is the reason as a matter of fact. Have to update it to 14.0 RU1 in order to fix. Closing the issue.

**Comment by friism** [comment]
Awesome, thanks for following up

**Comment by Drewster727** [comment]
I know this is an old issue, but I'm running Windows Server 1903 and having this exact issue.
We have SEP 14.2 RU1 installed, and no matter what exclusion rules I set in SEP it forces docker to a slowwwwww crawl. Some commands for docker never seem to come back.
Any ideas?
