### ISSUE TITLE
Docker fails to check for updates when running Docker as Admin on non-admin user account

### ISSUE THREAD

**Issue by ROBYER1** [docker/for-win#12563]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics - Diagnostics upload failed, see here: https://github.com/docker/for-win/issues/12564
  - Diagnostics ID: FAILED

### Actual behavior
Fresh install of Docker for Windows 10, installed as admin but while logged in as a non admin user on my work laptop. When launching docker, I get errors about Docker not being able to update (see screenshot below) and manually checking for update fails too. Seems to be an issue with Docker not being tested on non-admin accounts which are common in most IT development fields.

![Docker Error](https://user-images.githubusercontent.com/10745594/154475467-c74dc9e9-91a2-4c7a-9cce-879e4cd78fb0.png)

Once I ran the self-diagnostics tool command below, the Software update screen showed an update but trying to Download the update produced the same error as before 
![image](https://user-images.githubusercontent.com/10745594/154475408-0e4e963c-0f4b-4d7a-906a-d20a8ec62ab1.png)

Trying to run the diagnostics in the diagnostic/support section gives this wonderful error
![dockerre](https://user-images.githubusercontent.com/10745594/154475543-6fb4fbab-b1a4-45a8-a338-b60462ae1f4d.jpg)

### Expected behavior
Docker for Windows should be able to run the update check service when on a non admin account. Any request to update should just pop up an admin prompt, right now seems to be broken and even if an update is detected, it cannot be installed.

### Information

  - Windows Version: 10 Version 10.0.19044 Build 19044
  - Docker Desktop Version: Docker Desktop 4.4.4 (73704) 
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No, brand new laptop clean installs and have tried reinstalling many times + uninstall and clean install Docker.

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

[PASS] DD0027: is there available disk space on the host?
[SKIP] DD0028: is there available VM disk space?
[FAIL] DD0031: does the Docker API work? error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine_linux/v1.24/containers/json?limit=0": open //./pipe/docker_engine_linux: The system cannot find the file specified.
[FAIL] DD0004: is the Docker engine running? Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[FAIL] DD0011: are the LinuxKit services running? failed to ping VM diagnosticsd with error: Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.

[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0023: is the Containers Windows Feature enabled?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?

### Steps to reproduce the behavior

1. Use a laptop or PC with Windows 10 where the local user is not admin, but there is also an admin account on the device which you have the password to do admin prompts.
2. Download Docker for Windows and install it as admin (run as administrator)
3. Restart the device to make sure it's all set up, run Docker for Win
4. Try to check for updates in the Software updates menu

**Comment by laurazard** [comment]
Hi @ROBYER1,

Did you log out as the admin account before logging in as the non-admin account? As it is, it is not expected for docker to work when being run from one account and accessed from the other.
