### ISSUE TITLE
sudo service docker start in WSL2

### ISSUE THREAD

**Issue by Shadow-XT** [docker/for-win#12566]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
docker: unrecognized service

### Expected behavior
* Starting Docker : docker

### Information

  - Windows Version: Windows11 Pro
  - Docker Desktop Version: Docker Desktop 4.5.1 (74721)
  - WSL2 or Hyper-V backend?   WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: virtualized Windows

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
[050:18:45:20.259][I] ipc.NewClient: 55e54ab5-com.docker.diagnose -> \\.\pipe\dockerBackendV2 com.docker.service.exe
[goroutine 1 [running, locked to thread]:
[win/backend/pkg/service.NewClientForPath(...)
[       win/backend/pkg/service/service.go:42
[win/backend/pkg/service.NewClient({0x12df112, 0x13}, {0x0, 0x0, 0x0})
[       win/backend/pkg/service/service.go:31 +0xd0
[common/pkg/diagkit/gather/diagnose.init()
[       common/pkg/diagkit/gather/diagnose/ipc_windows.go:23 +0x11f

### Steps to reproduce the behavior

┌─[shine@Shadow]-[~]
└─[$]⚡ sudo service docker start                                                                    

[sudo] shine 的密码：
docker: unrecognized service

**Comment by slonopotamus** [comment]
Why do you expect such command should work?

**Comment by Shadow-XT** [comment]
I've seen elsewhere that if it's normal, typing this command 'sudo service docker start' will get this result，

But obviously, this will happen as long as I use the combination of "service" and "docker"

**Comment by slonopotamus** [comment]
Why don't you just follow [Docker Desktop documentation](https://docs.docker.com/desktop/windows/)? It nowhere talks about `sudo service docker start`.

**Comment by laurazard** [comment]
Hi @Shadow-XT,

To achieve what you are looking for you should follow the documentation [here](https://docs.docker.com/desktop/windows/wsl/), specifically [this part](https://docs.docker.com/desktop/windows/wsl/#install) pertaining to WSL2 integration.
