### ISSUE TITLE
Docker Images Not showing after PC Restart 

### ISSUE THREAD

**Issue by manikantareddy944** [docker/for-win#12571]
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version: Windows 10 pro 21H1 32GB RAM 
  - Docker Desktop Version: 20.10.12, build e91ed57
  - WSL2 or Hyper-V backend?   : NO 
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
[052:16:08:29.790][I] ipc.NewClient: e2c16540-com.docker.diagnose -> \\.\pipe\dockerBackendV2 com.docker.service.exe
[goroutine 1 [running, locked to thread]:
[win/backend/pkg/service.NewClientForPath(...)
[       win/backend/pkg/service/service.go:40
[win/backend/pkg/service.NewClient({0xece8be, 0x13}, {0x0, 0x0, 0x0})
[       win/backend/pkg/service/service.go:29 +0xe8
[common/pkg/diagkit/gather/diagnose.init()
[       common/pkg/diagkit/gather/diagnose/ipc_windows.go:23 +0x11f
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[WARN] DD0033: does the host have Internet access? unable to fetch http://docker.com/
segment 2022/02/21 16:09:19 ERROR: sending request - Post "https://api.segment.io/v1/batch": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
segment 2022/02/21 16:09:19 ERROR: 1 messages dropped because they failed to be sent and the client was closed

Please note the following 1 warning:

1 : The check: does the host have Internet access?
    Produced the following warning: unable to fetch http://docker.com/

If the host does not have Internet access then containers will also not have Internet access.

The lack of Internet access could be caused by
- physical disconnection: check your ethernet cable or Wifi network
- the local network firewall policy: check with your IT department if access to docker.com is expected to work
- a VPN (or lack of one): try again with or without the VPN running

### Steps to reproduce the behavior

A reproducible case, Dockerfiles with reproduction inside is best

Currently Iam pulling docker images from organisation JFrog artifactory where we store our docker images and i pulled the image and created a docker image and created a container and running fine but when i REBOOT MY PC 

i cannot able to see the docker images- empty 

and 
docker ps --- no containers showing 

docker ps -a -- showing the exited containers and when i start container using the Container ID i can able to run the containers but why docker images are not storing ???

**Comment by manikantareddy944** [comment]
Currently Iam pulling docker images from organisation JFrog artifactory where we store our docker images and i pulled the image and created Steps to reproduce the behavior
<!--
A reproducible case, Dockerfiles with reproduction inside is best


Currently Iam pulling docker images from organisation JFrog artifactory where we store our docker images and i pulled the image and created a docker image and created a container and running fine but when i REBOOT MY PC 

i cannot able to see the docker images- empty 

and 
docker ps --- no containers showing 

docker ps -a -- showing the exited containers and when i start container using the Container ID i can able to run the containers but why docker images are not storing ??? a docker image and created a container and running fine but when i REBOOT MY PC 

i cannot able to see the docker images- empty 

and 
docker ps --- no containers showing 

docker ps -a -- showing the exited containers and when i start container using the Container ID i can able to run the containers but why docker images are not storing ???

**Comment by manikantareddy944** [comment]
Currently Iam pulling docker images from organisation JFrog artifactory where we store our docker images and i pulled the image and created Steps to reproduce the behavior
A reproducible case, Dockerfiles with reproduction inside is best


Currently Iam pulling docker images from organisation JFrog artifactory where we store our docker images and i pulled the image and created a docker image and created a container and running fine but when i REBOOT MY PC 

i cannot able to see the docker images- empty 

and 
docker ps --- no containers showing 

docker ps -a -- showing the exited containers and when i start container using the Container ID i can able to run the containers but why docker images are not storing ??? a docker image and created a container and running fine but when i REBOOT MY PC 

i cannot able to see the docker images- empty 

and 
docker ps --- no containers showing 

docker ps -a -- showing the exited containers and when i start container using the Container ID i can able to run the containers but why docker images are not storing ???

**Comment by laurazard** [comment]
Hi @manikantareddy944,

is the output of `docker images` also empty?

**Comment by manikantareddy944** [comment]
The output also empty

**Comment by manikantareddy944** [comment]
I was searching everywhere but I couldn’t able to resolve it
