### ISSUE TITLE
Docker Desktop 4.5.1 GUI not showing in Windows 10 after upgrade from 4.4.4

### ISSUE THREAD

**Issue by adpe** [docker/for-win#12575]
- [x] I have tried with the latest version of Docker Desktop
- [ ] I have tried disabling enabled experimental features
- [x] I have uploaded Diagnostics
- Diagnostics ID: DA1D3F06-7A1D-42B1-B884-8536A4E98A4A/20220222143635

### Actual behavior

Docker Desktop is running, but the GUI is not showing up. Before also the tray-icon was missing, but with the mentioned workaround https://github.com/docker/for-win/issues/12573#issuecomment-1047817338 it was possible to fix that.

### Expected behavior

Docker Desktop GUI is accessible.

### Information

It is all working as expected, but after upgrading from 4.4.4 to 4.5.0 or 4.5.1 it's broken. I'm using Windows 10 Version 21H1 (Build 19043.1466) with the WSL2 engine.

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

![image](https://user-images.githubusercontent.com/9467708/155153772-6a1d4f87-370e-4469-92dc-ad3b0aa475fd.png)

### Steps to reproduce the behavior

  1. Install Docker Desktop 4.4.4
  2. Verify all it's working as expected.
  3. Upgrade to Docker Desktop 4.5.0 or 4.5.1 (it doesn't matter in my case)

**Comment by adpe** [comment]
For me, running a `wsl --shutdown` made the GUI and tray-icon appearing... Don't know exactly if this will help others as well. I'm using the new build from https://github.com/docker/for-win/issues/12573#issuecomment-1050682593.

**Comment by benlumia007** [comment]
i just tested, assuming @adpe is correct, i just install docker from the official site, but i needed to do a wsl --shutdown and the stystem tray and the GUI popped up.

**Comment by benlumia007** [comment]
i also found that everytime if the computer is restarted for  any reason, the docker system tray does not come back even if you start the application at start up. to fix this issue, wsl --shutdown is required. this is for build 75084

**Comment by benlumia007** [comment]
i believe i fixed this by uninstalling ubuntu 20.04 LTS for wsl and installing it, and now it works.

**Comment by StefanScherer** [comment]
Thanks for the feedback. We're investigating further, but yes it looks like wsl on your machine is a bit broken. In rare cases we also see that running wsl.exe commands just hang.

**Comment by benlumia007** [comment]
@adpe 

well that's a bummer, i guess it only works when it wants to work lol and is all different for people. I'm on Windows 10 and Windows 11 so i guess it all depends from here. I believe the other ticket has a new build just now, maybe try that.

**Comment by adpe** [comment]
As in this https://github.com/docker/for-win/issues/12573#issuecomment-1057728342 mentioned it solved my problem.
