### ISSUE TITLE
/mnt/wsl/docker-desktop/cli-tools/ is empty

### ISSUE THREAD

**Issue by Growiel** [docker/for-win#12578]
- [X ] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 447FA6A0-0957-4D09-A92F-DADAB1FD553E/20220223093045

### Actual behavior

Nothing mounts into /mnt/wsl/docker-desktop/cli-tools/:

![image](https://user-images.githubusercontent.com/5228735/155293007-3d712ef5-7427-416c-8a22-5fa60fbf5798.png)

### Expected behavior

To have all the needed files for Docker for work

### Information

  - Windows Version: Windows 10 21H2 (22000.527)
  - Docker Desktop Version: 4.5.1 (74721)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

![image](https://user-images.githubusercontent.com/5228735/155293357-dd479933-789c-4ad4-96ac-af7e1a548c6a.png)

### Steps to reproduce the behavior

None really, just start WSL and see that it doesn't work. I've been using for about a year without any issue, it suddendly went away one morning, and never came back.

I uninstalled a bunch of times and tried every trick I could find online, but to no avail.

Right now i'm using a very dirty workaround:

`alias dockere="'/mnt/c/Program Files/Docker/Docker/resources/bin/docker.exe'"`

It seems to work just fine, but I don't know the side effects and would prefer it to work normally.

Thanks.

**Comment by laurazard** [comment]
Hi @Growiel,

Can you check [this documentation page](https://docs.docker.com/desktop/windows/wsl/#install) and ensure all the integration is configured correctly, restart Docker Desktop, and see if it's working? You can also try running `wsl --shutdown` to see if it helps.

**Comment by real-tintin** [comment]
I'm having the same issue (Docker Desktop 4.5.1 (74721)). What I have tried:

- Reinstalling Docker Desktop
- Following https://github.com/docker/for-win/issues/12321#issuecomment-957959866 (related to this?)

**Comment by RJFoster** [comment]
I get this every time my computer restarts. Docker Desktop 4.7.1 (77678); Windows 10

After wasting a couple of hours of trying https://github.com/docker/for-win/issues/12321#issuecomment-957959866 with variations and mucking around on the WSL Integration settings page and different encantations eventually it works again. Last time the following steps worked, but who knows on the next restart:

1. Close any terminal windows
2. Shutdown Docker Desktop from the tray
3. `wsl -t` any remain distros
4. Check `wsl -l -v` until everything is stopped
5. `wsl -s docker-desktop` - in the hope this will mean it will start before Ubuntu and the integration will work
6. `wsl --shutdown`
7. Stop the docker service from the control panel
8. Restart docker desktop (start the service when prompted)

**Comment by djs55** [comment]
I've made a developer build of Desktop which has a workaround for a very similar-sounding problem. If you have a dangling symlink from `/usr/bin/docker` to `/mnt/wsl/docker-desktop/cli-tools/` and the `cli-tools` directory is empty, try this build and let me know if it makes any difference: https://desktop-stage.docker.com/win/main/amd64/80248/Docker%20Desktop%20Installer.exe If it still doesn't work, please upload diagnostics and post the diagnostics ID here.

Thanks!

**Comment by deborahgu** [comment]
@djs55: thank so much! I've been pinned to Docker 4.4.4 for ages, because I've had this broken behaviour since then, and none of the workarounds have worked persistently.  This is the first time I've been able to be on a current version since then. ♥

**Comment by clytras** [comment]
@djs55 that installer seems to work, though I had to uninstall Dcoker Desktop before using this installer, because I've had already installed the latest version, thus I now have lost all of my containers and volumes!

This issue is so frustrating; everytime that I restart Windows I face the exact same problem with WLS not being able to recognize docker. Hopefully now with that installation I won't face again that issue after restarting Windows and with new Docker Desktop updates.

**Comment by clytras** [comment]
> This issue is so frustrating; everytime that I restart Windows I face the exact same problem with WLS not being able to recognize docker. Hopefully now with that installation I won't face again that issue after restarting Windows and with new Docker Desktop updates.

This still happens on every single restart of Windows and after updating Docker desktop.
Today I updated to Docker Desktop 4.10.1 and I spent 2 hours just to make WSL Ubuntu work again.
This SO answer helps https://stackoverflow.com/a/65904006/1889685, but it does not work straight away.

I'm also trying to get the diagnostics, but it's stuck there showing just "Diagnosing...". I'll leave it and when it finishes I'll update my comment here.

**Comment by ffyuanda** [comment]
Having the same issue right now, tried all the solutions suggested above but nothing works.

**Comment by deborahgu** [comment]
@djs55 is your fix ever going to get merged into production Docker? I'm still having to use your install; periodically I try upgrading and I always run into the same problem. (`docker` now works on wsl2 ubuntu with newest docker desktop from `/bin`, but `kubectl` is nowhere to be found and the cli-tools directory is empty)

**Comment by clytras** [comment]
After I switched to a new Ubuntu 22.04 WSL2 installation, I'm no longer experiencing this issue.
Even now that I checked the old 20.04 WLS2 that was having this problem, it works out of the box after every installation and after each restart/shutdown!
