### ISSUE TITLE
Docker Desktop does not start properly on Win 10 Pro after Update or Uninstall/Reinstall

### ISSUE THREAD

**Issue by AnonymousJavaDev** [docker/for-win#12587]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6C914518-ED42-42D1-8178-1A589EE00C11/20220227222711

### Actual behavior

Docker for Windows will not start after update.  Attempted uninstall and reinstall twice with reboots and purging of config files to attempt to get back to clean state.

### Expected behavior

I expect to be able to start the docker desktop application and have a GUI and tool tray icon appear.  I usually use docker through Visual Studio Code for keeping code dependencies contained into a container environment and not polluting my machine.

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible?   YES.  No matter how many times I try to start it does not.  Start as Administrator or not makes no difference.
  - Is the problem new?  YES.  Docker was working fine yesterday through VSCode.  I greedily clicked "Update" in Docker and got this as a result.
  - Did the problem appear with an update?  YES.
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.
  - Windows Version:    Windows 10 Pro (21H1, build 19043.1526)
  - Docker Desktop Version: Latest  (docker --version at command line returns 20.10.12 build e91ed57)
  - WSL2 or Hyper-V backend?  I think WSL2...
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:  NO.

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

[PASS] DD0027: is there available disk space on the host?
[SKIP] DD0028: is there available VM disk space?
[FAIL] DD0031: does the Docker API work? error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine_linux/v1.24/containers/json?limit=0": open //./pipe/docker_engine_linux: The system cannot find the file specified.
[FAIL] DD0004: is the Docker engine running? Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[PASS] DD0016: is the LinuxKit VM running?
[FAIL] DD0001: is the application running? Docker is not running
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[FAIL] DD0025: are WSL distros installed? WSL Distribution docker-desktop is missing
[PASS] DD0026: is the WSL LxssManager service running?
[FAIL] DD0029: is the WSL 2 Linux filesystem corrupt? exit status 0xffffffff
[PASS] DD0015: are the binary symlinks installed?
error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json": open //./pipe/docker_engine: The system cannot find the file specified.
[FAIL] DD0003: is the Docker CLI working? exit status 1
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[FAIL] DD0007: is the backend responding? failed to ping com.docker.backend with error: Get "http://ipc/ping": open \\.\pipe\dockerBackendApiServer: The system cannot find the file specified.

  1. Windows Services seems to think that the "Docker Desktop Service" is running fine as Local System.
  2. I get no tooltray icon.
  3. I get no gui.
  4. VScode cannot start or reconnect to containers.
  5. When I try to start Docker I used to get a GUI that stated Docker is shutting down, but now I get nothing.

**Comment by AnonymousJavaDev** [comment]
I'm getting all kinds of logged errors.

In C:\Users\USERNAME\AppData\Local\Docker\log.txt
...[18:56:48.568][GUI][Warning] Failed to configure docker scan: System.UnauthorizedAccessException: Access to the path 'C:\Users\USERNAME\.docker\scan\config.json' is denied.

This file does exists and is readable by both my user and System Administrators.

[18:56:49.904][GoBackendProcess  ][Info   ] notifying bugsnag: saving JSON: open C:\Users\USERNAME\.docker\scan\config.json: Access is denied.
[18:56:49.908][GoBackendProcess  ][Info   ] [058:18:56:49.908][W] failed to send bugsnag report: bugsnag/payload.deliver: Post "https://notify.bugsnag.com": dial tcp: lookup notify.bugsnag.com: getaddrinfow: The requested name is valid, but no data of the requested type was found.
[18:56:49.908][GoBackendProcess  ][Info   ] bugsnag.Notify: bugsnag/payload.deliver: Post "https://notify.bugsnag.com": dial tcp: lookup notify.bugsnag.com: getaddrinfow: The requested name is valid, but no data of the requested type was found.
[18:56:49.909][GoBackendProcess  ][Info   ] [058:18:56:49.908][F] saving JSON: open <HOME>\.docker\scan\config.json: Access is denied.
[18:56:49.909][GoBackendProcess  ][Info   ] [main.reportIfFatal({0x23e3160, 0xc0001176b0}, {0x0, 0x21a4b82, 0xe})
[18:56:49.909][GoBackendProcess  ][Info   ] [	common/cmd/com.docker.backend/main.go:502 +0x98
[18:56:49.909][GoBackendProcess  ][Info   ] [main.main()
[18:56:49.909][GoBackendProcess  ][Info   ] [	common/cmd/com.docker.backend/main.go:95 +0x34b
[18:56:49.926][GoBackendProcess  ][Error  ] Process died

Again, this file exists..

This log file contains a lot of lines with "the specified file does not exists" Info lines.

**Comment by KnownAsMomoVV** [comment]
same issue [https://github.com/docker/for-win/issues/12577](url)

**Comment by AnonymousJavaDev** [comment]
I have verified that both Hyper-V and WSL2 both work perfectly fine.

**Comment by AnonymousJavaDev** [comment]
Okay I am up and running again.  I am not at all sure that these steps are necessary.  These are simply the steps that I took to get back to running again.

1.  Uninstall Docker.
2. Delete the following directories:

- C:\Users\USERNAME\AppData\Local\docker
- C:\Users\USERNAME\AppData\Local\docketDesktop
- C:\Users\USERNAME\AppData\LocalLow\docker
- C:\Users\USERNAME\AppData\LocalLow\docketDesktop
- C:\Users\USERNAME\AppData\Roaming\docker
- C:\Users\USERNAME\AppData\Roaming\docketDesktop
- C:\ProgramData\Docker
- C:\ProgramData\DockerDesktop
- C:\Program Files\Docker 

3.  Then I edited the registry and basically did a find for "docker" and deleted anything that showed up.  Some registry entries would not delete.  Just move on without spending too much time here.  
4. Reboot.
5. Redownload the Docker Desktop Installer.
6. I moved it to a local drive from a Onedrive (because I'm paranoid).
7. Installed, accepted all the defaults (both the install components for WSL2 option and the install desktop icon option).
8. It actually started up fine and asked me to accept the EULA and log in.


SUCCESS????  

Docker, please fix the upgrade/installer to make sure it cleans out any old cruft (or does the right thing to not clobber user altered settings.).

If you are still reading, I hope at least one other person has found this useful.  Be Careful and I hope it works for you.
