### ISSUE TITLE
Docker Desktop crashing when clicking on containers

### ISSUE THREAD

**Issue by doougal** [docker/for-win#12598]
- [X ] I have tried with the latest version of Docker Desktop - This has only occurred since the latest update
  - [ X] I have tried disabling enabled experimental features
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID:EE4B598F-9DD7-4C52-BB73-90C3AD1C88AF/20220310070850

### Actual behavior
Clicking on a running container crashes docker desktop.

### Expected behavior
Clicking on a running container would show the logs, inspect, stats tab etc.

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible? Yes
  - Is the problem new? Yes
  - Did the problem appear with an update? Yes
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best. Docker Desktop issue
 
  - Windows Version: 
Edition	Windows 10 Home
Version	21H2
Installed on	‎21/‎03/‎2021
OS build	19044.1586
Experience	Windows Feature Experience Pack 120.2212.4170.0

  - Docker Desktop Version: Docker Desktop 4.5.1 (74721)
  - WSL2 or Hyper-V backend?   WSL
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of ``
C:\Users\d0oug>"C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check
[069:20:24:38.672][I] ipc.NewClient: 21bf0767-com.docker.diagnose -> \\.\pipe\dockerBackendV2 com.docker.service.exe
[goroutine 1 [running, locked to thread]:
[win/backend/pkg/service.NewClientForPath(...)
[       win/backend/pkg/service/service.go:42
[win/backend/pkg/service.NewClient({0x8cf112, 0x13}, {0x0, 0x0, 0x0})
[       win/backend/pkg/service/service.go:31 +0xd0
[common/pkg/diagkit/gather/diagnose.init()
[       common/pkg/diagkit/gather/diagnose/ipc_windows.go:23 +0x11f
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0015: are the binary symlinks installed?
[FAIL] DD0003: is the Docker CLI working? exec: "docker": executable file not found in %PATH%
[FAIL] DD0013: is the $PATH ok? unable to find docker executable on PATH
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: is the $PATH ok?
    Failed with: unable to find docker executable on PATH

The directory containing the docker CLI tools must be on the $PATH
However, C:\Program Files\Docker\Docker is on the PATH, as well as C:\ProgramData\DockerDesktop\version-bin

### Steps to reproduce the behavior
Have a container in docker desktop list
Click container

**Comment by passedpawn1986** [comment]
Also seeing this issue with the latest update. I can click the drop down arrow as a workaround which won't cause it to crash.

**Comment by starsparrow** [comment]
Similar to, but not _exactly_ like this report, I have a composed docker app. Clicking the arrow on the compose group expands to show me the individual containers, and I can click on the individual containers to see the logs just fine. The root node's Start/Stop/Delete controls work fine as well. However, if I click elsewhere in the main area for the composition, Docker Desktop exits.

![image](https://user-images.githubusercontent.com/8523104/161144679-75576832-923b-4b67-b088-419a566240ee.png)
