### ISSUE TITLE
Occasionally causes taskbar to flicker

### ISSUE THREAD

**Issue by Ning-Qing** [docker/for-win#12594]
Docker desktop occasionally causes the icon to the right of the Windows 11 taskbar to flicker after running.
docker desktop 4.51
windwos 11 Pro 21H2 22000.527
![image](https://user-images.githubusercontent.com/49117063/156288026-0b7b9999-4104-4873-8bbe-6135e579184f.png)

**Comment by cherrol** [comment]
I have the same problem. After opening Docker Desktop for a while, it causes the taskbar to flicker. After closing Docker Desktop, it is normal.
