### ISSUE TITLE
Downloads for old versions

### ISSUE THREAD

**Issue by DeltaWhy** [docker/for-win#126]
Is there any way to download the installer for a previous version? I'm unable to use 1.12.1 due to issue #130. Additionally, this would be helpful in the future for ensuring the same version of Docker is running in development and in production.

Edit: I checked again and it looks like the issue I'm having with 1.12.1 is different from #81. I created a new issue.

**Comment by dgageot** [comment]
Closing. Duplicate of https://github.com/docker/for-win/issues/162
