### ISSUE TITLE
docker cp creates a nested subdirectory if one already exists

### ISSUE THREAD

**Issue by olegkhar** [docker/for-win#12603]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features

### Actual behavior
C:\var\tmp contains both 'hello.txt' and 'tmp\hello.txt'

### Expected behavior
C:\var\tmp would contain hello.txt and nothing else.
*or*
C:\var\tmp contains tmp\hello.txt, but not hello.txt

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
Not applicable.

### Steps to reproduce the behavior

1. Create a directory on the host, C:\var
2. Inside a running Linux container, run `touch /var/tmp/hello.txt`
3. In a terminal, run `docker cp <id>:/var/tmp C:\var\tmp`
4. Run exactly the same command again

**Comment by slonopotamus** [comment]
Your expectation is wrong.

From `docker cp` [documentation](https://docs.docker.com/engine/reference/commandline/cp/):

> SRC_PATH specifies a directory + DEST_PATH exists and is a directory +
SRC_PATH does not end with /. (that is: slash followed by dot) = the source directory is copied into this directory

**Comment by olegkhar** [comment]
Thanks for the explanation!
