### ISSUE TITLE
Unable to launch docker for windows 10

### ISSUE THREAD

**Issue by Theyrealone** [docker/for-win#1261]
### Expected behavior
Docker starts
### Actual behavior
Unable to create an instance of Docker.App: Unable to create an instance of Docker.WPF.ClientConfig.DockerLogin
at Docker.Core.di.Singletons.NewInstance(Type type, Int32 depth) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 78
at Docker.Core.di.Singletons.Get(Type type, Int32 depth) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 44
at Docker.Core.di.Singletons.GetT in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 27
at Docker.Program.Run(IReadOnlyCollection`1 args) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Program.cs:line 166
### Information
  Suddenly unable to launch docker for windows 10, tried reinstalling and I cannot execute factory reset, the program crashes
### Steps to reproduce the behavior
???

**Comment by osya** [comment]
I have the same issue. I tried to move C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx on another drive. After I copying it (not moved yet) and change path in Docker settings this error becomes appears every time I tried to start Docker for Windows. Reinstalling Docker for Windows and Reset to Factory settings does not help. Under another Windows account it works. Please advise

**Comment by Theyrealone** [comment]
Issue solved, as suggested by @osya I tried to start docker in another user on the same computer, and it worked.
I later tried to access the .docker folder C:\Users\$Username\.docker of the problem user and It threw an error.
after deleting that .docker folder, docker seem to start.

A better error message would be much more helpful.
