### ISSUE TITLE
How to run docker in docker

### ISSUE THREAD

**Issue by mwoodpatrick** [docker/for-win#12619]
I'm running WSL-2 (Ubuntu) on windows 11 and docker integrated into the distribution. I have a Jenkins container and want to run docker from within the container. What is the correct way to do this? Is this documented somewhere?

I tried:

```
curl https://get.docker.com/ > dockerinstall && chmod 777 dockerinstall && ./dockerinstall
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18617  100 18617    0     0   114k      0 --:--:-- --:--:-- --:--:--  113k
# Executing docker install script, commit: 93d2499759296ac1f9c510605fef85052a2c32be
```
But got:

```
WSL DETECTED: We recommend using Docker Desktop for Windows.
Please get Docker Desktop from https://www.docker.com/products/docker-desktop
```

**Comment by apm963** [comment]
A good way to run docker in docker is to use a single docker daemon and access it by bind-mounting the `docker.sock`. I don't exactly know how you have your Jenkins container running but a typical `docker run` command would look like this:

```sh
docker run -it --name my-container -v /var/run/docker.sock:/var/run/docker.sock my-image
```

From there you can simply run `docker` cli commands. Make sure to have the docker cli package installed. Here is a full example using an alpine image.

```sh
# From your host (WSL shell)
docker run -it --name dind -v /var/run/docker.sock:/var/run/docker.sock alpine:latest /bin/sh
# From within the Alpine container
apk add --no-cache docker-cli
docker info # should show info from your host
docker run hello-world
```

You may find this article helpful https://www.tiuweehan.com/blog/2020-09-10-docker-in-jenkins-in-docker/ for a Jenkins-specific setup. Please be aware of any security implications involved when exposing the docker daemon via socket or TCP.
