### ISSUE TITLE
Login Failed! lookup login.docker.com: no such host

### ISSUE THREAD

**Issue by chuoke** [docker/for-win#12626]
Login Failed!
Post "https://login.docker.com/oauth/token": dial tcp: lookup login.docker.com: no such host

![image](https://user-images.githubusercontent.com/17611457/160286032-4596790a-580b-4e98-a2a1-1570f0330215.png)

**Comment by alanhzh** [comment]
I have the same problem:
![image](https://user-images.githubusercontent.com/4001312/165438681-a6927df9-78c2-4de4-b061-89542ee9bccf.png)

**Comment by BGE-faith** [comment]
> I have the same problem: ![image](https://user-images.githubusercontent.com/4001312/165438681-a6927df9-78c2-4de4-b061-89542ee9bccf.png)

Is your OS a mac M1?

**Comment by scott7rj** [comment]
Same thing here. Using Debian. It was fine before 4.12.0(85629) update
![Screenshot from 2022-09-14 09-41-24](https://user-images.githubusercontent.com/8083275/190156923-0ec24003-c536-410b-aa8f-867b215236ee.png)
