### ISSUE TITLE
Docker 100% disk usage, running in Windows 10

### ISSUE THREAD

**Issue by JonasGao** [docker/for-win#12624]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B940829C-5017-448E-B027-B65EAA7AF49A/20220326111648

### Actual behavior
![Screenshot 2022-03-26 175329](https://user-images.githubusercontent.com/4549584/160237108-afef7875-ffd1-477a-95e3-75f577ff2923.png)
![Untitled](https://user-images.githubusercontent.com/4549584/160238065-22301859-041a-4efe-b711-93136e24526e.png)

### Expected behavior
Normal disk read usage。

### Information

  - Windows Version: Windows 10 Pro 21H2 (19044.1620)
  - Docker Desktop Version: 3.3.3
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

I don't have the check command here. And i used `./com.docker.diagnose.exe gather -upload`

```
C:\Program Files\Docker\Docker\resources> ./com.docker.diagnose.exe check
"check" is not valid command.

USAGE: com.docker.diagnose.exe [options] COMMAND [options]

Gather and upload diagnostics bundles for Docker Desktop.
Commands:
  gather
  upload
  check-hypervisor

Options:
  -path string
        Local path prefix where to store the diagnostics bundle.

Run 'com.docker.diagnose.exe COMMAND help' for more information on the command

Common use cases:
- Generate a diagnostics bundle and upload:
    com.docker.diagnose.exe gather -upload
  This will print a diagnostics ID you can supply for further troubleshooting.

- Generate a local diagnostics bundle to upload later:
    com.docker.diagnose.exe gather
  This will print a diagnostics ID you can use to upload with.
    com.docker.diagnose.exe submit <ID>

- Generate a local diagnostics bundle:
    com.docker.diagnose.exe gather <file>
  This will generate a local bundle in <file>.zip.

If -path is specified, place the diagnostics bundle in that directory. Otherwise the sstem default temporary directory will be used.
```

### Steps to reproduce the behavior

  1. docker compose up -d (My docker-compose at the bottom)
  2. wait about 15 minutes
  3. disk usage 100%

### Other informations:

![Screenshot 2022-03-26 175705](https://user-images.githubusercontent.com/4549584/160237381-2044338b-5dc5-47a8-b810-d07574acf468.png)

![Screenshot 2022-03-26 172805](https://user-images.githubusercontent.com/4549584/160237387-37126a77-daf7-4162-9e93-c456ec591402.png)

![image](https://user-images.githubusercontent.com/4549584/160237436-fdc9a550-ad89-4198-9900-7ec816cfbd04.png)

![image](https://user-images.githubusercontent.com/4549584/160237457-dd0ee5e3-86d0-42af-9434-9dfd10dcc58c.png)

### My docker-compose.yaml

```yaml
version: "3.1"
services:
  core:
    image: dreamacro/clash:v1.10.0
    restart: always
    ports:
      - 9090:9090
      - 7890:7890
      - 7891:7891
    volumes:
      - 'clash-config:/root/.config/clash'
volumes:
  clash-config:
    external: true
```

The volume **clash-config** contains my private configuration, please tell me a private way if you want

**Comment by hellorayza** [comment]
Does it have anything to do with VirtualMachinePlatform?
I find docker desktop work well even if did not enable VirtualMachinePlatform...
It won't 100% disk usage but docker command useless in wsl , ref [WSL2 Integration with Ubuntu 20.04 stop working](https://github.com/docker/for-win/issues/12321#)...
I've had 100% disk  usage problems twice...
The problem caused the WSL running extremely slowly
