### ISSUE TITLE
Docker Desktop fails to start in some cases due to an incorrect WSL command

### ISSUE THREAD

**Issue by andreas-ateles** [docker/for-win#12622]
- [x] I have tried with the latest version of Docker Desktop
  - [x] ~I have tried disabling enabled experimental features~ Not applicable
  - [x] ~I have uploaded Diagnostics~ Not applicable
  - Diagnostics ID: Impossible, Docker Desktop doesn't start

### Expected behavior

Docker Desktop starts when executing it. The UI/tray icon is available.

### Actual behavior

When Docker Desktop is starting it runs the command:

    wsl.exe bash -ic "printenv KUBECONFIG"

And it just gets stuck there, never proceeding further. No UI or tray icon is ever shown.

Here's a screenshot of the process tree when this is happening:

![screenshot](https://user-images.githubusercontent.com/19323772/160089941-5b84acf6-6ad2-40d3-9bc7-1594191b2b86.png)

### The issue

The problem with the command is that bash is ran in interactive mode (the `-i` flag), while it's run as a non-interactive command/shell.
And anything needing interaction in ones `.bashrc` will just wait and hang since there is no way for the user to interact with it.

### Solution

The `-i` flag to the bash command should be removed. As the shell is non-interactive, and should not be flagged as interactive.

### Background

In my case I'm using [`keychain` to automatically add SSH keys to WSL2][2]. This asks for the key passphrase when bash starts interactively. So it (Docker Desktop in my case) just gets stuck there and is unable to continue. (As a workaround for this it's possible to add a `timeout` to the interactive command to kill it after some time, but it shouldn't be needed in the first place.)

### `kubernetes-client/javascript`?

While researching the issue the only place that Google was able to find this command was in [`kubernetes-client/javascript`][1].

So I was assuming that it's coming from there and opened [an issue there][3]. But this assumption could be wrong, and they might just be doing a similar thing.

### Information

  - Windows Version: 10 pro, x64
  - Docker Desktop Version: 4.6.1
  - WSL2
  - Not virtualized Windows

[1]: https://github.com/kubernetes-client/javascript/blob/master/src/config.ts#L314 
[3]: https://github.com/kubernetes-client/javascript/issues/788
[2]: https://devblogs.microsoft.com/commandline/sharing-ssh-keys-between-windows-and-wsl-2/

**Comment by greglnye** [comment]
I have this same problem with Docker Desktop 4.7.0 (77141)
Since I don't use Kubernetes functionality, my workaround is to identify and kill (using sysinternals Process Explorer) the 'wsl.exe bash -ic "printenv KUBECONFIG"' process at which point the Docker Desktop icon appears in the tray and the GUI becomes available for use.
As a Docker Pro user, I have raised a support ticket for this.

**Comment by StefanScherer** [comment]
Thanks @andreas-ateles and @greglnye I finally found this public issue. Thanks for explaining and the linked ticket.
For now the workaround is to create an empty file in the windows users home directory `.kube/config`.
We're looking to either update the npm package or find another permanent solution.

**Comment by mat007** [comment]
Hi! We have just released Docker Desktop 4.9.0 including a fix for this issue.
Thanks!

**Comment by joshsleeper** [comment]
awesome, really glad to finally have this fix in @mat007.

for the curious, any chance of linking to the actual commit/PR that fixed the issue?

**Comment by mat007** [comment]
Sorry @joshsleeper, the code isn’t publicly available.

**Comment by joshsleeper** [comment]
Womp womp, that's a bummer. Thanks for clarifying though!

**Comment by brantac** [comment]
Docker Desktop is failing to start for me as well. When I click to open the app, it opens the app window, and then the status message goes from "Docker Desktop starting" to "Docker Desktop quit..." in a fews seconds, and it shuts down. This problem started after I updated the app this week, on June 28th.

Also, when I run ```docker version``` on Windows Powershell, the message I get is:
```
error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version": open //./pipe/docker_engine: The system cannot find the file specified.
Client:
 Cloud integration: v1.0.25
 Version:           20.10.16
 API version:       1.41
 Go version:        go1.17.10
 Git commit:        aa7e414
 Built:             Thu May 12 09:17:07 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true
```

I already tried some tips that I found, such as running ```& 'C:\Program Files\Docker\Docker\DockerCli.exe' -SwitchDaemon```, but it didn't fix the issue.
