### ISSUE TITLE
Intermittent DNS issues with Windows containers  

### ISSUE THREAD

**Issue by haiduc32** [docker/for-win#12638]
This will be a long explanation of the issue and the investigations that were performed, so best grab a coffee first.

  - [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features

### Actual behavior
Running this powershell in a Windows container, results in 1-3 timed out responses: for ($i=0;$i -lt 100;$i++) {nslookup google.com}

### Expected behavior
No DNS requests should fail.

### Information
The issue original issue is that our applications (.net core in windows containers in a kubernetes cluster) intermittently fail with the error: "No such host is known" when communicating with various resources (other services, database, etc).

We managed to reproduce the issue on a dev machine by running the powershell script in a windows container: for ($i=0;$i -lt 100;$i++) {nslookup google.com}

To exclude any issues with our work environment, I took this to a beefy vanilla machine (my personal gaming pc), with no prior docker installed. Installed Docker, activated Hyper-V, ran the container and the script, and same issue. In depth details bellow. 

  - Windows version: 20H2 10.0.19042.1586 (reproduces on different versions of windows)
  - Docker version: 20.10.13 (on earlier versions as well)
  - Docker image: mcr.microsoft.com/windows/servercore:10.0.19042.1586
  - Hyper-V (AFAIK)

### Steps to reproduce the behavior

  1. Run the docker command to start the container and enter interactive mode

```
docker run -it mcr.microsoft.com/windows/servercore:10.0.19042.1586 cmd
```
After starting the container, run `powershell` to switch to powershell. 

2. First thing I ran the following powershell scripts inside the container, on my setup, to set Google DNS servers, as the default DNS server wasn't working. In our work setup we also inject custom DNS servers, but it should not be related as I'll explain below :

```
get-netadapter "Ethernet" | Set-DnsClientServerAddress -ResetServerAddresses

$network = (get-netadapter).name | Select-Object -Last 1
Set-DnsClientServerAddress -InterfaceAlias $netwowrk -ServerAdresses ("8.8.8.8","8.8.4.4")
```
3. Next, after confirming with `ipconfig /all` that only the Google DNS servers are used, I run the following powershell script:
```
for ($i=0;$i -lt 100;$i++) {nslookup google.com}
```
On my setup, almost all the time, the script pauses 3 times, for 2 seconds each time, and in that case I see **DNS request timed out.**. On the work setup, it's about once in two runs. 

4. To confirm that it's not a Google DNS issue, I run the same script `for ($i=0;$i -lt 100;$i++) {nslookup google.com}` from the host machine, with no timeouts. (repeated the test multiple times with no timeouts).

5. After lots of head scratching, time to pull out the big boys tools, namely Wireshark. First, investigate the packets for the **Ethernet adapter vEthernet (nat)** (I'll share the capture if it's deemed useful, but for the sake of already long issue, I'm skipping it). To best of my knowledge, this is the adapter that the container communicates with. Here we see DNS UDP packets that are sent, but don't have a reply packet. 

> Sidenote: It's not necessarily just the DNS UDP that don't get a reply, I suspect there might be some other packets that don't get a reply in time, and blocks nslookup; but ATM I can not confirm.

6. Now that we know there are packets lost, let's check if those packets reach our physical network interface. I run Wireshark on my physical network interface, and filter only DNS A type packets `dns.qry.name == "google.com" && dns.qry.type == 1`. Run the script again in the container. I can see 198 packets filtered (request/reply). So only 99 out of 100 DNS requests reached physical interface (I did check that all requests have a response). 

**Notice** that I mentioned earlier that there are usually 3 timeouts but in this Wireshark I usually see just 1 missing request/response because of the Wireshark filter. So far that's the one type of packet I identified for sure as missing in action, but there are more types that I can't put my finger on.

### Conclusions

Based on that research I draw the conclusion that some DNS (and maybe not only DNS) UDP packets get lost between the vEthernet NAT interface and the physical ethernet interface. 

### Questions
Is the network problem part of docker? I don't know and hope someone to confirm or point out that it needs to be raised an issue in another place.

Can I investigate something further? I'm not a network guy, and best I can do is reading Wireshark logs, but how the routing behind is done or what is involved is all black-box to me.

**Comment by stephen-turner** [comment]
Thanks for the detailed report, @haiduc32.

@djs55 Is Docker code on the network or DNS path at all in the case of Windows containers, or is this an OS thing that should be reported at https://github.com/microsoft/Windows-Containers?

**Comment by djs55** [comment]
A great report, thanks @haiduc32 . Docker code is not on the network path -- so I recommend replicating the issue over on https://github.com/microsoft/Windows-Containers . IIRC the networking is setup by the "Host Networking Service" and I believe there is a "Hyper-V Virtual Switch" between the vEthernet NAT interface and the physical ethernet interface. Perhaps the switch is dropping packets (but really shouldn't since the load is not very high).

**Comment by haiduc32** [comment]
thanks, also reported it at: https://github.com/microsoft/Windows-Containers/issues/217

**Comment by stephen-turner** [comment]
Thanks, @djs55, I'll close this copy.
