### ISSUE TITLE
Unable to access repository via host.docker.internal

### ISSUE THREAD

**Issue by MichalStehlikCz** [docker/for-win#12630]
We use access to remove container repository (Nexus) via ssh tunnel running on localhost:60177 of host machine.

Up to 4.5.1, it was possible to add "insecure-registries": ["host.docker.internal:60177"] to docker engine configuration and use
docker login host.docker.internal:60177
and docker connected to repository successfully.

After upgrade to 4.6.1, it fails with
Authenticating with existing credentials...
Login did not succeed, error: Error response from daemon: login attempt to http://host.docker.internal:60177/v2/ failed with status: 503 Service Unavailable

We verified that it is linked with Docker Desktop version, not with availability of remote repository.

Diagnostics ID 9BCECD8C-5035-4ACD-9548-605B1F798ABB/20220328081633
Running on Windows 10 Pro with WSL2 backend

**Comment by AetheWu** [comment]
I had the same problem on macos12.3 , docker for mac v4.6.1

**Comment by erachkov** [comment]
Same issue Windows 10pro and docker v4.6.1 any update?

`PS C:\WINDOWS\system32> docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: lrachkov
Password:
Error response from daemon: Get "https://registry-1.docker.io/v2/": Service Unavailable
PS C:\WINDOWS\system32>`
