### ISSUE TITLE
Docker CE for Windows does not install on Windows 10 Pro

### ISSUE THREAD

**Issue by daniel-leicht** [docker/for-win#1263]
### Expected behavior
Docker CE for Windows should install on Windows 10 Pro

### Actual behavior
Docker CE for Windows says "_Docker for Windows requires Windows 10 Pro or Enterprise version 10586, or Windows server 2016 RTM to run_" even though my system **does** run Windows 10 Pro.

### Information
I downloaded the most recent Stable version (as of 29.10.2017).
The output of "_Get-WmiObject Win32_OperatingSystem | fl *_" is:

```
PSComputerName                            : DESKTOP-IH5GHC4
Status                                    : OK
Name                                      : Microsoft Windows 10 Pro|C:\Windows|\Device\Harddisk0\Partition2
FreePhysicalMemory                        : 3041360
FreeSpaceInPagingFiles                    : 1615764
FreeVirtualMemory                         : 3764856
__GENUS                                   : 2
__CLASS                                   : Win32_OperatingSystem
__SUPERCLASS                              : CIM_OperatingSystem
__DYNASTY                                 : CIM_ManagedSystemElement
__RELPATH                                 : Win32_OperatingSystem=@
__PROPERTY_COUNT                          : 64
__DERIVATION                              : {CIM_OperatingSystem, CIM_LogicalElement, CIM_ManagedSystemElement}
__SERVER                                  : DESKTOP-IH5GHC4
__NAMESPACE                               : root\cimv2
__PATH                                    : \\DESKTOP-IH5GHC4\root\cimv2:Win32_OperatingSystem=@
BootDevice                                : \Device\HarddiskVolume1
BuildNumber                               : 10240
BuildType                                 : Multiprocessor Free
Caption                                   : Microsoft Windows 10 Pro
CodeSet                                   : 1252
CountryCode                               : 1
CreationClassName                         : Win32_OperatingSystem
CSCreationClassName                       : Win32_ComputerSystem
CSDVersion                                :
CSName                                    : DESKTOP-IH5GHC4
CurrentTimeZone                           : 120
DataExecutionPrevention_32BitApplications : True
DataExecutionPrevention_Available         : True
DataExecutionPrevention_Drivers           : True
DataExecutionPrevention_SupportPolicy     : 2
Debug                                     : False
Description                               :
Distributed                               : False
EncryptionLevel                           : 256
ForegroundApplicationBoost                : 2
InstallDate                               : 20170308180105.000000+120
LargeSystemCache                          :
LastBootUpTime                            : 20171029131006.488134+120
LocalDateTime                             : 20171029180940.234000+120
Locale                                    : 0409
Manufacturer                              : Microsoft Corporation
MaxNumberOfProcesses                      : 4294967295
MaxProcessMemorySize                      : 137438953344
MUILanguages                              : {en-US}
NumberOfLicensedUsers                     :
NumberOfProcesses                         : 134
NumberOfUsers                             : 2
OperatingSystemSKU                        : 48
Organization                              :
OSArchitecture                            : 64-bit
OSLanguage                                : 1033
OSProductSuite                            : 256
OSType                                    : 18
OtherTypeDescription                      :
PAEEnabled                                :
PlusProductID                             :
PlusVersionNumber                         :
PortableOperatingSystem                   : False
Primary                                   : True
ProductType                               : 1
RegisteredUser                            : USER
SerialNumber                              : 00180-19311-99535-AAOEM
ServicePackMajorVersion                   : 0
ServicePackMinorVersion                   : 0
SizeStoredInPagingFiles                   : 1638400
SuiteMask                                 : 272
SystemDevice                              : \Device\HarddiskVolume2
SystemDirectory                           : C:\Windows\system32
SystemDrive                               : C:
TotalSwapSpaceSize                        :
TotalVirtualMemorySize                    : 9715652
TotalVisibleMemorySize                    : 8077252
Version                                   : 10.0.10240
WindowsDirectory                          : C:\Windows
Scope                                     : System.Management.ManagementScope
Path                                      : \\DESKTOP-IH5GHC4\root\cimv2:Win32_OperatingSystem=@
Options                                   : System.Management.ObjectGetOptions
ClassPath                                 : \\DESKTOP-IH5GHC4\root\cimv2:Win32_OperatingSystem
Properties                                : {BootDevice, BuildNumber, BuildType, Caption...}
SystemProperties                          : {__GENUS, __CLASS, __SUPERCLASS, __DYNASTY...}
Qualifiers                                : {dynamic, Locale, provider, Singleton...}
Site                                      :
Container                                 :

```

**Comment by jasonbivins** [comment]
Hi @daniel-leicht 
Running Windows Updates should take care of the issue for you - it looks like you're on an early build of Windows 10

```BuildNumber                               : 10240
BuildType                                 : Multiprocessor Free
Caption                                   : Microsoft Windows 10 Pro```

**Comment by friism** [comment]
Correct, Windows 10 build `10240` is not supported.

**Comment by ramganesh19** [comment]
I am on below version, but still get error
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.10586 Build 10586

Error Message
"Docker for Windows requires Windows 10 Pro or Enterprise version 10586, or Windows server 2016 RTM to run"

**Comment by CoolHandDev** [comment]
I am in the same boat as ramganesh19.  My machine is running on Windows 10 Version 1511 (OS Build 10586.1176) and Docker install is giving me the same message.

**Comment by meirkr** [comment]
Same for me.
My installed Version:	10.0.10586 Build 10586
And still get that error:
"Docker for Windows requires Windows 10 Pro or Enterprise version 10586, or Windows server 2016 RTM to run"

**Comment by meirkr** [comment]
https://forums.docker.com/t/unable-to-install-docker-on-windows-10/37542
Quote:
"
It’s seem to be new with the last version.
Thus, I went to get an old release (https://docs.docker.com/docker-for-windows/release-notes/#docker-community-edition-17091-ce-win42-2017-12-11-stable14), took the one **from the 6th october** and it installs fine.

Hope it helps you.
Jonathan
"
That really helps!
The direct download link to the one which works:
https://download.docker.com/win/stable/13620/Docker%20for%20Windows%20Installer.exe

**Comment by jasonbivins** [comment]
Windows 10 Pro and Enterprise are supported, as long as it is `BUILD 14393` or greater.  `10.0.14393`

There are Hyper-V features that Docker relies on that were not added until this build.  Please run Windows updates

**Comment by xmariachi** [comment]
Happening on: 

SystemDirectory : C:\WINDOWS\system32
Organization    : Hewlett-Packard
BuildNumber     : 16299
Version         : 10.0.16299

**Comment by smartaamee** [comment]
It's still happening even with the build ver. **10.0.15063** installed already. Checked the win. updates already and it's already up to date. Tried to install the following docker version which is supposed to be stable:

Version 17.09.0-ce-win33 (13620)
Channel: stable
8c56a3b

When hover over to the docker icon, it says ' Can't Update'. And when tried to manually update it then the following exception gets displayed:

Unable to stop: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.
at <ScriptBlock>, <No file>: line 79
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 177
   at Docker.Backend.ContainerEngine.Linux.DoStop() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 279
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 122
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

Please help.

**Comment by jasonbivins** [comment]
Hi @smartaamee 
You're seeing a different error, try running this command to see if there's an issue with Hyper-V
`Import-Module Hyper-V`

**Comment by smartaamee** [comment]
Hi @jasonbivins 
Ran that above cmd on PS console but still getting some exceptions:

Import-Module : The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.
At line:1 char:1
+ Import-Module Hyper-V
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (Hyper-V:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

Note:
My OS ver is: Import-Module : "Win. 10 Home" and have never installed Hyper-V on this OS before.

**Comment by thaJeztah** [comment]
@smartaamee it's not supported on Windows 10 Home; see https://docs.docker.com/docker-for-windows/install/#what-to-know-before-you-install. Home edition does not have the requirements that Docker for Windows needs to run

**Comment by smartaamee** [comment]
Ah ok... Sure, that makes perfect sense. Thanks @thaJeztah , appreciated.

**Comment by knightcube** [comment]
Getting the same error as @ramganesh19 and @meirkr  - 
Docker for Windows requires Windows 10 Pro or Enterprise version 10586, or Windows server 2016 RTM to run. How do i resolve it?

**Comment by ctelles-cwi** [comment]
Hello! I have the same problem.
Docker for Windows requires Windows 10 Pro or Enterprise version 10586, or Windows server 2016 RTM to run. 
The version of my Windows is 10 Pro build 10586. I've covered OS updates, but the problem persists.
How do i resolve it?

**Comment by gtardif** [comment]
@knightcube @ctelles-cwi The error message in the installer you're running is out of date ; you now need to have windows 10 build 14393 or greater (or windows server 2016) for Docker For Windows. (See https://docs.docker.com/docker-for-windows/install/#what-to-know-before-you-install).

**Comment by j2l** [comment]
Anniversary update (14393) breaks other VR apps in my case. I won't install it.

October 6th version didn't make it too, despite I'm with Win 10 Entreprise 1511.10586
Name                                      : Microsoft Windows 10 Entreprise|C:\Windows|\Device\Harddisk1
BuildNumber                               : 10586
BuildType                                 : Multiprocessor Free
Caption                                   : Microsoft Windows 10 Entreprise

Too bad.

**Comment by lucasnahuel2** [comment]
I'm getting the same error, even though I'm on Windows 10 Pro 10586:

```
BuildNumber                               : 10586
BuildType                                 : Multiprocessor Free
Caption                                   : Microsoft Windows 10 Pro
```
In my case, installing 6th october version seems to do the trick (https://download.docker.com/win/stable/13620/Docker%20for%20Windows%20Installer.exe). But I'd really like to have the chance to be updated with the newest versions 😢

**Comment by jasonbivins** [comment]
@lucasnahuel2   That version had a bug that allowed it to skip the prerequisites check
You'll need to be on Windows build 14393 or higher
https://docs.docker.com/docker-for-windows/install/#what-to-know-before-you-install

**Comment by anyfreenick** [comment]
I have the same error. though I have 10586 build
See [screenshot](https://clip2net.com/s/3RnRnCu)

**Comment by aMaZing0x41** [comment]
Why is this issue closed? Several people are still reporting this. I am getting the same behavior as @anyfreenick on Windows 10 Ent.

**Comment by friism** [comment]
Can you upgrade to a more recent windows version than 10586? If not, consider using Docker Toolbox instead.

**Comment by karlkras** [comment]
The error in the installation attempt clearly states:
`Docker for Windows requires Windows 10 Pro or Enterprise version 10586, or Windows server 2016 RTM to run`
and my system is:
`OS Name	Microsoft Windows 10 Enterprise`
`Version	10.0.10586 Build 10586`

Why are you asking for us to install a more recent version? If it is no longer supported that message should be updated accordingly.

**Comment by Gentinmen** [comment]
I just got a product key from <a href="http://www.vanskeys.com/">www.vanskeys.com</a>. it worked perfectly. I'm so excited to share my experience here. their customer service is 1st class and I will definitely be recommending the site and I will be using the site again.

**Comment by Stevanen** [comment]
I just got a product key from <a href="http://www.vanskeys.com/">www.vanskeys.com</a>. it worked perfectly. I'm so excited to share my experience here. their customer service is 1st class and I will definitely be recommending the site and I will be using the site again.

**Comment by yw5aj** [comment]
+1 on updating the error message during installation.

**Comment by apsferreira** [comment]
+1 on updating the error message during installation.

**Comment by andrewpsp** [comment]
I'm pretty disappointed after going through the trouble to update my system and read numerous docker references to run into this thread of multiple users have the exact same issue on the equivalent build and higher 

``` 
BuildNumber                               : 10586
BuildType                                 : Multiprocessor Free
Caption                                   : Microsoft Windows 10 Pro
```

**Comment by andrewpsp** [comment]
Upon further inspection it would appear the reason I'm getting this issue is the kernel requires x86-64 GPU but only the i686 CPU is being detected.  

[](https://ibb.co/iMMFgc)

**Comment by rn** [comment]
@andrewpsp as mentioned above the minimum supported build of windows is 14393 and you seem to be running on 10586 (one of the releases had a wrong error message in the version check)

**Comment by imroopeshkumar** [comment]
Version: 10.0.17134 Build 10.0.17134 still facing this issue.

**Comment by selvaganprofile** [comment]
I am also facing the same issue

**Comment by adamdecaf** [comment]
I have the same issue. 

Versions: 
- Docker for Windows: `18.06.1-ce-win-73`
- Windows: `10.0.16299 Build 16299`

**Comment by akshathsramesh** [comment]
I have the same issue as well.

Versions:
Docker for windows: 18.06.1-ce-win73
Windows 10 Home : Version 1803 Build: 17134.254

**Comment by thaJeztah** [comment]
Windows 10 Home is unfortunately not supported, as it does not have the features required for Docker to run (see https://docs.docker.com/docker-for-windows/install/#what-to-know-before-you-install).

**Comment by akshathsramesh** [comment]
@thaJeztah Thank you. Had missed this point.

**Comment by adamdecaf** [comment]
@thaJeztah Thanks. Could we get the UI to say that?

**Comment by mat007** [comment]
@adamdecaf it actually does: `Docker for Windows requires Windows 10 Pro or Enterprise (…)`.

**Comment by sharabiania** [comment]
Same issue on `Version 1511 (OS Build 10586.1540)`

**Comment by hakimwd** [comment]
recently i had the issue with docker cant connect...

what i did:
1) open power shell in admin privilege
2) navigate to docker program folder, in my case it is : "C:\Program Files\Docker Toolbox"
3) run start.sh command while in same power shell: ./start.sh
4) close current power shell.
5) re-open power shell in admin privilege
6) run 'docker info' or 'docker run hello-world' to test whether docker run.
7) docker success message appear :)

**Comment by elvitos-peterson** [comment]
> Thus, I went to get an old release (https://docs.docker.com/docker-for-windows/release-notes/#docker-community-edition-17091-ce-win42-2017-12-11-stable14), took the one **from the 6th october** and it installs fine.

This Worked for me.

**Comment by antim00** [comment]
Docker Desktop requires Windows 10 Pro or Enterprise version 15063 to run.
my Get-WmiObject Win32_OperatingSystem | fl * gives below result:

PSComputerName                            : LAPTOP-NJ5TER25
Status                                    : OK
Name                                      : Microsoft Windows 10 Home Single
                                            Language|C:\WINDOWS|\Device\Harddisk0\Partition3
FreePhysicalMemory                        : 3154680
FreeSpaceInPagingFiles                    : 3506044
FreeVirtualMemory                         : 5512432
__GENUS                                   : 2
__CLASS                                   : Win32_OperatingSystem
__SUPERCLASS                              : CIM_OperatingSystem
__DYNASTY                                 : CIM_ManagedSystemElement
__RELPATH                                 : Win32_OperatingSystem=@
__PROPERTY_COUNT                          : 64
__DERIVATION                              : {CIM_OperatingSystem, CIM_LogicalElement, CIM_ManagedSystemElement}
__SERVER                                  : LAPTOP-NJ5TER25
__NAMESPACE                               : root\cimv2
__PATH                                    : \\LAPTOP-NJ5TER25\root\cimv2:Win32_OperatingSystem=@
BootDevice                                : \Device\HarddiskVolume1
BuildNumber                               : 17134
BuildType                                 : Multiprocessor Free
Caption                                   : Microsoft Windows 10 Home Single Language
CodeSet                                   : 1252
CountryCode                               : 1
CreationClassName                         : Win32_OperatingSystem
CSCreationClassName                       : Win32_ComputerSystem
CSDVersion                                :
CSName                                    : LAPTOP-NJ5TER25
CurrentTimeZone                           : 330
DataExecutionPrevention_32BitApplications : True
DataExecutionPrevention_Available         : True
DataExecutionPrevention_Drivers           : True
DataExecutionPrevention_SupportPolicy     : 2
Debug                                     : False
Description                               :
Distributed                               : False
EncryptionLevel                           : 256
ForegroundApplicationBoost                : 2
InstallDate                               : 20180616115439.000000+330
LargeSystemCache                          :
LastBootUpTime                            : 20190913091454.500000+330
LocalDateTime                             : 20190913213418.604000+330
Locale                                    : 0409
Manufacturer                              : Microsoft Corporation
MaxNumberOfProcesses                      : 4294967295
MaxProcessMemorySize                      : 137438953344
MUILanguages                              : {en-US}
NumberOfLicensedUsers                     :
NumberOfProcesses                         : 220
NumberOfUsers                             : 2
OperatingSystemSKU                        : 100
Organization                              :
OSArchitecture                            : 64-bit
OSLanguage                                : 1033
OSProductSuite                            : 768
OSType                                    : 18
OtherTypeDescription                      :
PAEEnabled                                :
PlusProductID                             :
PlusVersionNumber                         :
PortableOperatingSystem                   : False
Primary                                   : True
ProductType                               : 1
RegisteredUser                            : Windows User
SerialNumber                              : 00327-30526-45469-AAOEM
ServicePackMajorVersion                   : 0
ServicePackMinorVersion                   : 0
SizeStoredInPagingFiles                   : 3538944
SuiteMask                                 : 784
SystemDevice                              : \Device\HarddiskVolume3
SystemDirectory                           : C:\WINDOWS\system32
SystemDrive                               : C:
TotalSwapSpaceSize                        :
TotalVirtualMemorySize                    : 11790732
TotalVisibleMemorySize                    : 8251788
Version                                   : 10.0.17134
WindowsDirectory                          : C:\WINDOWS
Scope                                     : System.Management.ManagementScope
Path                                      : \\LAPTOP-NJ5TER25\root\cimv2:Win32_OperatingSystem=@
Options                                   : System.Management.ObjectGetOptions
ClassPath                                 : \\LAPTOP-NJ5TER25\root\cimv2:Win32_OperatingSystem
Properties                                : {BootDevice, BuildNumber, BuildType, Caption...}
SystemProperties                          : {__GENUS, __CLASS, __SUPERCLASS, __DYNASTY...}
Qualifiers                                : {dynamic, Locale, provider, Singleton...}
Site                                      :
Container                                 :

**Comment by karlkras** [comment]
You can't use docker on a windows 10 home os
