### ISSUE TITLE
Docker compose up does not rebuild containers when images have changed

### ISSUE THREAD

**Issue by jamesmusik** [docker/for-win#12635]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 54A6C73A-A78D-4255-89C7-D1F959263A5C/20220330213254

### Actual behavior
When running docker compose up, existing containers with images that have changed continue running as is without any rebuild.

### Expected behavior
If the images for an existing container have changed, docker compose up should rebuild and (re)start that container.

### Information

Please, help us understand the problem.  For instance:
  - Is it reproducible? Yes, it has happened every time an image has updated for me since updating to 4.6.1 (or maybe 4.6)
  - Is the problem new? Yes, it appears to have started when I updated to 4.6.1 (76265)
  - Did the problem appear with an update? Yes, see above

  - Windows Version: Windows 11 Pro Build 22581
  - Docker Desktop Version: 4.6.1 (76265)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.

### Steps to reproduce the behavior

  1. Start containers with docker compose up
  2. Pull updated images with docker compose pull
  3. Run docker compose up

**Comment by dallasbeek** [comment]
Also encountering similar issue.  Make code change and execute below to rebuild service.  Container does not contain code changes.  Reverting to version 4.5.1.

`docker-compose up -d --build hub.api`

**Comment by jamesmusik** [comment]
4.7.0 updates compose to 2.4.1, so that presumably fixes this issue. I'll update when I can verify.

**Comment by jamesmusik** [comment]
Yes, this is fixed in 4.7.0
