### ISSUE TITLE
Docker Desktop integration with Ubuntu 20.04 fails Windows 11 - missing softlink

### ISSUE THREAD

**Issue by DavidCozens** [docker/for-win#12642]
- [ x] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 6DC138F2-0678-4895-9ECF-6CAEAE8805AD/20220402110815

### Actual behavior

> $ docker
>
> The command 'docker' could not be found in this WSL 2 distro.
> We recommend to activate the WSL integration in Docker Desktop settings.
>
> For details about using Docker Desktop with WSL 2, visit:
>
> https://docs.docker.com/go/wsl2/

The above comes from a script, which checks uname

> $ uname -r
> 5.10.102.1-microsoft-standard-WSL2

It then fails to run docker from /usr/bin because there is a directory rather than a soft link to the executable.

### Expected behavior

docker executable runs and gives usage summary

#### Is it reproducible?

Every time I start my laptop it repeats

#### Is the problem new?

I think it came in on an update either of windows, ubuntu or docker desktop, but I'm not certain. This is a relatively new PC and docker-compose works, I may not have noticed.

#### Did the problem appear with an update?

I can't be certain that I have seen this work on windows 11

  - Windows Version:: 11
  - Docker Desktop Version: : 4.6.1
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No, physical laptop

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

PS C:\> & "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check
[2022-04-02T11:17:39.101756600Z][com.docker.diagnose.exe][I] ipc.NewClient: ef2d5c18-com.docker.diagnose -> \\.\pipe\dockerBackendV2 com.docker.service.exe
[goroutine 1 [running, locked to thread]:
[win/backend/pkg/service.NewClientForPath(...)
[       win/backend/pkg/service/service.go:42
[win/backend/pkg/service.NewClient({0x13f14c4, 0x13}, {0x0, 0x0, 0x0})
[       win/backend/pkg/service/service.go:31 +0xd0
[common/pkg/diagkit/gather/diagnose.init()
[       common/pkg/diagkit/gather/diagnose/ipc_windows.go:23 +0x11f
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.

#### Steps to reproduce the behavior

From startup this is what I observe in the ubuntu dirstro (which is my default and only distro ).

> $ ls -l /usr/bin | grep docker
> drwxr-xr-x 2 root   root        4096 Apr  2 09:07 com.docker.cli
> drwxr-xr-x 2 root   root        4096 Apr  2 11:45 docker
> lrwxrwxrwx 1 root   root          56 Apr  2 11:45 docker-compose -> /mnt/wsl/docker-desktop/cli-tools/usr/bin
docker-compose
> lrwxrwxrwx 1 root   root          59 Apr  2 11:45 docker-compose-v1 -> /mnt/wsl/docker-desktop/cli-tools/usr/bin/docker-compose-v1
> lrwxrwxrwx 1 root   root          71 Apr  2 11:45 docker-credential-desktop.exe -> /mnt/wsl/docker-desktop/cli-tools/usr/bin/docker-credential-desktop.exe
> lrwxrwxrwx 1 root   root          50 Apr  2 11:45 hub-tool -> /mnt/wsl/docker-desktop/cli-tools/usr/bin/hub-tool

The docker and com.docker.cli folders are empty

If I restart docker desktop the soft links are removed, if I'm quick I can remove the docker directory, but it is created again as part of the docker desktop startup.

#### Other information

I have had a problem with the mcafee firewall preventing com.docker.wsl-distro-proxy.exe from starting. I have disabled the firewall for now.

**Comment by DavidCozens** [comment]
One further piece of information

> /mnt/wsl/docker-desktop/cli-tools//usr/bin/com.docker.cli

and

> /mnt/wsl/docker-desktop/cli-tools//usr/bin/docker

are both present, accessible and operate as expected. It is just the symlinks in /usr/bin that are not created and empty directories exist instead.

**Comment by DavidCozens** [comment]
This looks superficially like the original report in issue #7311

**Comment by djs55** [comment]
Do you happen to have any containers with bind-mounts like `-v /usr/bin/docker:/...`? It's possible there is a race between a container startup and the symlink creation. Unfortunately `docker run -v /usr/bin/docker:/...` will `mkdir /usr/bin/docker` if it doesn't already exist (IMHO undesirable behaviour but we have to be careful to change it in case people are relying on it).

**Comment by DavidCozens** [comment]
Hi Scott,

Yes I do, that could be it.

Regards Dave

(sent from my iPhone)

**Comment by DavidCozens** [comment]
Hi Scott,

Possibly too soon I do have bind mounts but not referencing /usr/bin/docker

Regards Dave

(sent from my iPhone)
