### ISSUE TITLE
Delete images does not remove the image source folder

### ISSUE THREAD

**Issue by tuan-lm97** [docker/for-win#12643]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
When remove images from Docker Desktop Images panel, the image being remove, but the actual source folder in disk is not remove/delete
### Expected behavior
The source folder of images should be delete when delete images
### Information

  - Windows Version: 10.0.19043 Build 19043
  - Docker Desktop Version: Docker Desktop 4.6.1 (76265)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Follow Docker Desktop getting started tutorial
  2. Successfully made the dockertutorial image and container.
  3. Check to see getting-started folder inside where ever you install the image
  4. Remove dockertutorial container, then remove dockertutorial image
  5. Check to see getting-started folder is still there

**Comment by stephen-turner** [comment]
Sorry, we're not going to do this. I can see the attraction for the getting started tutorial, but for real work I think people would be very upset if we removed their source code when the image was deleted.
