### ISSUE TITLE
Update Docker Container from Win 10 to Win 11

### ISSUE THREAD

**Issue by DjPercy** [docker/for-win#12651]
Hello,
After doing an update from Win 10 to Win 11 I can't start my Docker containers, I get the following error:

Error calling remote method 'docker-start-container': error: (HTTP code 500) server error - container 9f4c37c1e0de8e55dbb746592428548c19253b056ceba805aa5619651846effc encountered an error during hcsshim::System::Start: failure in a Windows system call: the container operating system does not match the host operating system. (0xc0370101]

Is it possible to perform an OS update for the Docker container?

  - [ X] I have tried with the latest version of Docker Desktop
  - [ X] I have tried disabling enabled experimental features
  - [ X] Diagnose Failed

  - Windows Version: WIN  11
  - Docker Desktop Version: 4.6.1 (76265) 
  - WSL2 or Hyper-V backend?  WSL2

**Comment by stephen-turner** [comment]
Thanks for the ticket. All hcsshim errors come from the container code in Windows, not from Docker. So you should report it at https://github.com/microsoft/Windows-Containers instead.
