### ISSUE TITLE
Windows 10 node cannot join swarm as manager in no of three possible scenarios

### ISSUE THREAD

**Issue by 1605200517** [docker/for-win#1265]
### Expected behavior

It is possible to attach a Windows 10 node to an existing swarm as master using the following scenarios:
- A. Join as worker and get promoted
- B. Join directly as manager
- C. Init swarm and other member join

### Actual behavior
A. Joining is OK (node gets name "moby"); updating a global service (default nginx as test) produces a local Windows Docker container of it. Promoting results however in the error listed below.
B.  Error as listed below.
C. Doesn not work either. Error: Error response from daemon: Timeout was reached before node joined. 

### Error

Swarm: error
 NodeID:
 Error: manager stopped: can't initialize raft node: rpc error: code = Unknown desc = could not connect to prospective new cluster member using its advertised address: rpc error: code = Unavailable desc = grpc: the connection is unavailable

### Information

Docker info:
```
Containers: 137
 Running: 1
 Paused: 0
 Stopped: 136
Images: 355
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: error
 NodeID:
 Error: manager stopped: can't initialize raft node: rpc error: code = Unknown desc = could not connect to prospective n
ew cluster member using its advertised address: rpc error: code = Unavailable desc = grpc: the connection is unavailable
 Is Manager: false
 Node Address: 192.168.65.2
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.49-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 22.99GiB
Name: moby
ID: JROS:QB2L:VWSQ:WXKY:JTGN:YAT6:MGXU:JNFW:Q4HU:JF2S:OSP4:VBN6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 53
 System Time: 2017-10-30T06:20:17.2773984Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
Docker info (also, all of swarm node run this same Docker version):

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64
Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by thaJeztah** [comment]
Looking at

```
could not connect to prospective new cluster member using its advertised address
```

and (from the output of `docker info`):

```
 Node Address: 192.168.65.2
```


Did you join the node using `--advertise-addr` ? It looks like the swam manager was not able to connect to your local daemon; make sure that you use `--advertise-addr` to provide the public IP-address where the daemon is reachable, and that the required ports and protocols are open between the nodes; https://docs.docker.com/engine/swarm/swarm-tutorial/#the-ip-address-of-the-manager-machine

<img width="1031" alt="screen shot 2017-10-30 at 11 03 59" src="https://user-images.githubusercontent.com/1804568/32165130-0f56a596-bd62-11e7-8a61-928b747dee09.png">

**Comment by PeiSeng** [comment]
So is there any solution for this?

**Comment by aasten** [comment]
Same trouble. Does anybody know the solution?
