### ISSUE TITLE
LCOW Container fails with "No hypervisor is present on this system" even when Hyper-V Installed

### ISSUE THREAD

**Issue by caleblloyd** [docker/for-win#1266]
## The bug

I have Hyper-V Installed on my Windows 10 Pro Version 1709 system:

![image](https://user-images.githubusercontent.com/2414837/32171260-ef21af1e-bd4d-11e7-9817-19d80715477f.png)

I have LCOW enabled in the Docker For Windows Settings.

I try to start a Linux Container: `docker run --rm -it alpine sh`

Fails with a "No hypervisor is present on this system" error:

```
PS C:\WINDOWS\system32> docker run --rm -it alpine sh
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
b56ae66c2937: Extracting [==================================================>]  1.991MB/1.991MB
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: failed to register layer: failed to start service utility VM (a
pplydiff 0b53d850529f0498c0cd71c0b5785809394dde33c7f3484af32327004d46715f): container 0b53d850529f0498c0cd71c0b578580939
4dde33c7f3484af32327004d46715f_svm encountered an error during CreateContainer: failure in a Windows system call: No hyp
ervisor is present on this system. (0xc0351000) extra info: {"SystemType":"container","Name":"0b53d850529f0498c0cd71c0b5
785809394dde33c7f3484af32327004d46715f_svm","Layers":null,"HvPartition":true,"HvRuntime":{"ImagePath":"C:\\Program Files
\\Linux Containers","LinuxInitrdFile":"initrd.img","LinuxKernelFile":"bootx64.efi"},"ContainerType":"linux","TerminateOn
LastHandleClosed":true}.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
```

### Information

```
PS C:\WINDOWS\system32> docker version
Client:
 Version:      master-dockerproject-2017-10-27
 API version:  1.34
 Go version:   go1.8.4
 Git commit:   54e1378
 Built:        Fri Oct 27 23:49:01 2017
 OS/Arch:      windows/amd64

Server:
 Version:      master-dockerproject-2017-10-27
 API version:  1.34 (minimum version 1.24)
 Go version:   go1.8.5
 Git commit:   2613c3d
 Built:        Fri Oct 27 23:52:54 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

**Comment by shadow1163** [comment]
did you tried to switch to Linux containers and try again? Your docker server is windows containers now.

**Comment by caleblloyd** [comment]
I am trying to use LCOW, which is Linux Containers on Windows. I am pretty sure that requires an edge build with LCOW checked in settings and "Windows Containers" mode.

**Comment by jasonbivins** [comment]
Hi @caleblloyd   Can you pull the image if you uncheck LCOW, and then switch to Linux containers mode?

**Comment by caleblloyd** [comment]
seems to be fixed in the latest edge version

**Comment by jacobrillema** [comment]
This is causing similar issues for me running on Docker Edge version 17.11.0-ce, build 1caf76c. It was working earlier in November on Edge now it does not want to run here recently.

docker: failed to register layer: failed to start service utility VM (applydiff 3d6fdc8ebaac2c8d2ec3dcb3021b4641f27ee9eb96b6fc76f1b22ada5c0df657): container 3d6fdc8ebaac2c8d2ec3dcb3021b4641f27ee9eb96b6fc76f1b22ada5c0df657_svm encountered an error during CreateContainer: failure in a Windows system call: No hypervisor is present on this system. (0xc0351000) extra info: {"SystemType":"container","Name":"3d6fdc8ebaac2c8d2ec3dcb3021b4641f27ee9eb96b6fc76f1b22ada5c0df657_svm","Layers":null,"HvPartition":true,"HvRuntime":{"ImagePath":"C:\\Program Files\\Linux Containers","LinuxInitrdFile":"initrd.img","LinuxKernelFile":"bootx64.efi"},"ContainerType":"linux","TerminateOnLastHandleClosed":true}.
See 'docker run --help'.

**Comment by qiangli** [comment]
still having this issue for 17.12.0 ce-rc4-win44.

+ docker build --rm -t dhnt/bash .
Sending build context to Docker daemon  56.32kB
Step 1/14 : FROM ubuntu:16.04
16.04: Pulling from library/ubuntu
50aff78429b1: Extracting [==================================================>]  42.74MB/42.74MB
f6d82e297bce: Download complete
275abb2c8a6f: Download complete
9f15a39356d6: Download complete
fc0342a94c89: Download complete
failed to register layer: failed to start service utility VM (applydiff dae316b26447cb413b6be75d2857d021b148e8ad2fa2574fd70497f5dbd2f629): container dae316b26447cb413b6be75d2857d021b148e8ad2fa2574fd70497f5dbd2f629_svm encountered an error during CreateContainer: failure in a Windows system call: No hypervisor is present on this system. (0xc0351000) extra info: {"SystemType":"container","Name":"dae316b26447cb413b6be75d2857d021b148e8ad2fa2574fd70497f5dbd2f629_svm","Layers":null,"HvPartition":true,"HvRuntime":{"ImagePath":"C:\\Program Files\\Linux Containers","LinuxInitrdFile":"initrd.img","LinuxKernelFile":"bootx64.efi"},"ContainerType":"linux","TerminateOnLastHandleClosed":true}

**Comment by bardware** [comment]
> I have Hyper-V Installed on my Windows 10

Is Hyper-V enabled or disabled through a call to `bcdedit`?
