### ISSUE TITLE
Docker does not allow empty password field when sharing disk in Settings

### ISSUE THREAD

**Issue by IgorMaksymov** [docker/for-win#1267]
### Expected behavior
Docker should share disk when password field is empty.

### Actual behavior
When password is empty, OK button is inactive.
I was able to share disk only after protected my windows user with password and provided that password in Docker.

### Steps to reproduce the behavior

  1. try to share disks to Docker within windows user, that is not password protected.
  2. try to share disk in settings menu
  3. leave password field empty
  4. OK button will stay inactive

**Comment by jasonbivins** [comment]
Hi @IgorMaksymov  The GUI is working as designed here, but I can reproduce your use case.  I went ahead and entered this in as an enhancement request for you instead of a bug report.

Thanks!

**Comment by friism** [comment]
Please also see my response here: https://github.com/docker/for-win/issues/616#issuecomment-319856195

And note that these problems will go away as we transition to Linux-Containers-On-Windows (LCOW): https://blog.docker.com/2017/09/preview-linux-containers-on-windows/

You can try LCOW in the latest edge installs if you have an up-to-date Windows 10 install.
