### ISSUE TITLE
Docker installation clears hosts file

### ISSUE THREAD

**Issue by FLAMESpl** [docker/for-win#12676]
### Actual behavior

Docker installation or update clears hosts file and inserts docker part:

```
# Added by Docker Desktop
192.168.0.120 host.docker.internal
192.168.0.120 gateway.docker.internal
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
```

### Expected behavior

Hosts file is not cleared

### Information

  - Windows Version: 10.0.18363 Build 18363
  - Docker Desktop Version: any
  - WSL2 or Hyper-V backend?: Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Steps to reproduce the behavior
  1. install or update docker for windows

**Comment by micdenny** [comment]
happened to me as well

![image](https://user-images.githubusercontent.com/1633595/189327921-bf2a0e4e-99e6-47c7-9221-ca0e76015105.png)

version: 4.12.0 (85629)

don't know if happened with this very latest version or slightly before.
