### ISSUE TITLE
kube config lost after upgrade

### ISSUE THREAD

**Issue by brl0** [docker/for-win#12690]
First of all, thanks for this project, it has made a truly remarkable impact.

Unfortunately, after updating Docker recently, all contexts in my ~/.kube/config file were lost!

Some version info:
Docker desktop 4.7.1 (77678), Windows 11 (22H2 22598.200), WSL 2 Ubuntu

I didn't even click the reset cluster button, but at any rate, considering that config file is shared by other tools and applications, I would think Docker should never be removing config for other unrelated clusters.

I should have had a personal backup, but don't, so let me know if it turns out that the installer backed stuff up before overwriting/deleting, although I am not expecting or assuming that to be the case.

Thanks in advance for any assistance.

**Comment by StefanScherer** [comment]
Thank you for the report.
We apologise for any inconvenience.
Docker Desktop tries to sync this file between WSL 2 and Windows side. Could you tell a bit more where you had the ~/.kube/config file, only in WSL 2 distros? Only on Windows? Is it empty now or what was inside after you lost all contexts?
We're looking into it once we have further details. Thank you.
