### ISSUE TITLE
Prevent desktop icon in unattended quiet install

### ISSUE THREAD

**Issue by blindzero** [docker/for-win#12699]
### Actual behavior
Whenever calling Docker Desktop Windows installer with --quiet a desktop icon is placed.

### Expected behavior
I want to have an option to pass not to place a desktop icon.

**Comment by StefanScherer** [comment]
Thanks for the feature request. I suggest to open a ticket in https://github.com/docker/roadmap/issues and explain what you want to have changed in our product. If we get enough thumbs up I think this would make a nice improvement.
