### ISSUE TITLE
Windows Docker Container stats returning JSON that doesn't adhere to Engine API spec

### ISSUE THREAD

**Issue by rwmajor2** [docker/for-win#12698]
- [X] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID:  E587EE71-D79A-4750-9A24-7D4316E08EEF/20220406134133

### Actual behavior
When using the Docker Engine API in a browser to get stats of a Docker container, the format is as follows. The problem is the **memory_stats[stats]** object does not adhere to the API. Thus, the version of the Docker Java client we are using does not know how to process this bogus set of key/value pairs.
{
"read": "2022-04-06T13:36:40.1069069Z",
"preread": "2022-04-06T13:36:39.1026392Z",
"pids_stats": {
"current": 2,
"limit": 18446744073709551615
},
"blkio_stats": {
"io_service_bytes_recursive": null,
"io_serviced_recursive": null,
"io_queue_recursive": null,
"io_service_time_recursive": null,
"io_wait_time_recursive": null,
"io_merged_recursive": null,
"io_time_recursive": null,
"sectors_recursive": null
},
"num_procs": 0,
"storage_stats": {},
"cpu_stats": {
"cpu_usage": {
"total_usage": 731750739000,
"usage_in_kernelmode": 650894342000,
"usage_in_usermode": 80856396000
},
"system_cpu_usage": 2728044410000000,
"online_cpus": 4,
"throttling_data": {
"periods": 0,
"throttled_periods": 0,
"throttled_time": 0
}
},
"precpu_stats": {
"cpu_usage": {
"total_usage": 731750205000,
"usage_in_kernelmode": 650893808000,
"usage_in_usermode": 80856396000
},
"system_cpu_usage": 2728040380000000,
"online_cpus": 4,
"throttling_data": {
"periods": 0,
"throttled_periods": 0,
"throttled_time": 0
}
},
"memory_stats": {
"usage": 335872,
"stats": {
"active_anon": 0,
"active_file": 0,
"anon": 135168,
"anon_thp": 0,
"file": 0,
"file_dirty": 0,
"file_mapped": 0,
"file_writeback": 0,
"inactive_anon": 135168,
"inactive_file": 0,
"kernel_stack": 98304,
"pgactivate": 132,
"pgdeactivate": 0,
"pgfault": 22079475,
"pglazyfree": 0,
"pglazyfreed": 0,
"pgmajfault": 0,
"pgrefill": 0,
"pgscan": 0,
"pgsteal": 0,
"shmem": 0,
"slab": 181424,
"slab_reclaimable": 0,
"slab_unreclaimable": 181424,
"sock": 0,
"thp_collapse_alloc": 0,
"thp_fault_alloc": 0,
"unevictable": 0,
"workingset_activate": 0,
"workingset_nodereclaim": 0,
"workingset_refault": 0
},
"limit": 8346218496
},
"name": "/jjnq76e4mr",
"id": "909a444f67f1420c293f6b346bcf144f98577915f2ddf789890d05a0c9edd0c3",
"networks": {
"eth0": {
"rx_bytes": 12286,
"rx_packets": 173,
"rx_errors": 0,
"rx_dropped": 0,
"tx_bytes": 0,
"tx_packets": 0,
"tx_errors": 0,
"tx_dropped": 0
}
}
}

### Expected behavior
This is what it should look like:
{
"read": "2022-04-06T13:26:57.1016155Z",
"preread": "2022-04-06T13:26:56.0965394Z",
"pids_stats": {
"current": 27
},
"blkio_stats": {
"io_service_bytes_recursive": [{
"major": 8,
"minor": 0,
"op": "Read",
"value": 0
}, {
"major": 8,
"minor": 0,
"op": "Write",
"value": 3837952
}, {
"major": 8,
"minor": 0,
"op": "Sync",
"value": 2072576
}, {
"major": 8,
"minor": 0,
"op": "Async",
"value": 1765376
}, {
"major": 8,
"minor": 0,
"op": "Discard",
"value": 0
}, {
"major": 8,
"minor": 0,
"op": "Total",
"value": 3837952
}],
"io_serviced_recursive": [{
"major": 8,
"minor": 0,
"op": "Read",
"value": 0
}, {
"major": 8,
"minor": 0,
"op": "Write",
"value": 69
}, {
"major": 8,
"minor": 0,
"op": "Sync",
"value": 62
}, {
"major": 8,
"minor": 0,
"op": "Async",
"value": 7
}, {
"major": 8,
"minor": 0,
"op": "Discard",
"value": 0
}, {
"major": 8,
"minor": 0,
"op": "Total",
"value": 69
}],
"io_queue_recursive": [],
"io_service_time_recursive": [],
"io_wait_time_recursive": [],
"io_merged_recursive": [],
"io_time_recursive": [],
"sectors_recursive": []
},
"num_procs": 0,
"storage_stats": {},
"cpu_stats": {
"cpu_usage": {
"total_usage": 21258958000,
"percpu_usage": [6075962900, 7006205800, 8176789300, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
"usage_in_kernelmode": 5820000000,
"usage_in_usermode": 10350000000
},
"system_cpu_usage": 83977300000000,
"online_cpus": 3,
"throttling_data": {
"periods": 2786,
"throttled_periods": 0,
"throttled_time": 0
}
},
"precpu_stats": {
"cpu_usage": {
"total_usage": 21257640400,
"percpu_usage": [6075482700, 7005805700, 8176352000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
"usage_in_kernelmode": 5820000000,
"usage_in_usermode": 10350000000
},
"system_cpu_usage": 83974300000000,
"online_cpus": 3,
"throttling_data": {
"periods": 2785,
"throttled_periods": 0,
"throttled_time": 0
}
},
"memory_stats": {
"usage": 373698560,
"max_usage": 377634816,
"stats": {
"active_anon": 0,
"active_file": 0,
"cache": 2703360,
"dirty": 135168,
"hierarchical_memory_limit": 6442450944,
"hierarchical_memsw_limit": 12884901888,
"inactive_anon": 349003776,
"inactive_file": 2568192,
"mapped_file": 405504,
"pgfault": 230835,
"pgmajfault": 0,
"pgpgin": 137280,
"pgpgout": 51451,
"rss": 348868608,
"rss_huge": 0,
"total_active_anon": 0,
"total_active_file": 0,
"total_cache": 2703360,
"total_dirty": 135168,
"total_inactive_anon": 349003776,
"total_inactive_file": 2568192,
"total_mapped_file": 405504,
"total_pgfault": 230835,
"total_pgmajfault": 0,
"total_pgpgin": 137280,
"total_pgpgout": 51451,
"total_rss": 348868608,
"total_rss_huge": 0,
"total_unevictable": 0,
"total_writeback": 0,
"unevictable": 0,
"writeback": 0
},
"limit": 5143318528
},
"name": "/e0fd183d6b914b6a8cbcff88498895c6",
"id": "cef66e760322932c763982db881f3030506ebbfc2574456b1766f31993c906f8",
"networks": {
"eth0": {
"rx_bytes": 202237,
"rx_packets": 1161,
"rx_errors": 0,
"rx_dropped": 0,
"tx_bytes": 5007124,
"tx_packets": 1101,
"tx_errors": 0,
"tx_dropped": 0
}
}
}

### Information

  - Windows Version:  Windows 10, Windows Server with MCR
  - Docker Desktop Version:   4.7.1
  - WSL2 or Hyper-V backend?    Hyper V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:  No

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by StefanScherer** [comment]
Thanks for the report. Unfortunately we can't read the diagnostics. Which version of Docker Desktop are you running?
And out of curiosity what are you trying to achieve with the Docker Java library?
I'm not an expert about the internals of Docker Desktop, but I assume we need the different data for a reason. Maybe the Java library should just support these keys?

**Comment by nicks** [comment]
My understanding is the memory_stats stuff is VERY low-level, and in this case it's directly reading off the cgroup. And this was something that changed in cgroup v1 vs cgroup v2.
https://www.kernel.org/doc/Documentation/cgroup-v2.txt
https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt
so this is expected behavior.
