### ISSUE TITLE
Docker doest start, distro stopped unexpectedly

### ISSUE THREAD

**Issue by amiralam0** [docker/for-win#12705]
- [x ] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: A9DF5E7E-1C0D-4357-BEAA-2F600F297E15/20220507091526

### Actual behavior
When I start docker, it failed to start giving me an error that the distro stopped unexpectedly
### Expected behavior
When I open docker, it should start normally
### Information
I tried latest version of docker, tried with different Ubuntu versions, nothing worked

  - Windows Version:
  - Windows 10 21H2 19044
  - Docker Desktop Version:
  - tried 3 different versions: latest, 4.7.1.0, 3.6.0.0(current version)
  - WSL2 or Hyper-V backend?  
  - WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:
  - no

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
I cant produce the output as the problem is with the starting of docker
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by StefanScherer** [comment]
We saw that the total memory of the machine is only 8GB, so it depends what other programs are already running to make it work. Does running a WSL2 distro work at all?

**Comment by amiralam0** [comment]
i just formatted my c drive and reinstalled the windows, it works now
