### ISSUE TITLE
Docker stop working in wsl console 

### ISSUE THREAD

**Issue by Machalkas** [docker/for-win#12707]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: FE85FA16-F2D7-4A03-A771-D03E005D1042/20220508131136

### Actual behavior

Suddenly, docker stops working in wsl console
![image](https://user-images.githubusercontent.com/52866342/167302878-551038e7-7cbe-4384-a8af-35a30752fbf4.png)
but I still can run it in PowerShell
![image](https://user-images.githubusercontent.com/52866342/167302852-3b6d2aae-d5c8-47be-8fec-e06021292e65.png)

I tried to update and reinstall Docker Desktop, but it didn't help.
My WSL integration is terned on
![image](https://user-images.githubusercontent.com/52866342/167303091-92f882ea-f444-4323-8b64-0f8c32b16836.png)
![image](https://user-images.githubusercontent.com/52866342/167303108-f81a5934-a2b2-4233-a129-db502590200f.png)

### Information

  - Windows Version: Home 10.0.19044
  - Docker Desktop Version:  4.8.0 (78933) 
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Machalkas** [comment]
I installed the Debian distributive, and Docker works fine on it. I think that reinstalling Ubuntu will solve the problem, but I wonder if there is any way to fix this problem without reinstalling the system?

**Comment by StefanScherer** [comment]
Thank you for the report.
Have you tried to untick all WSL integration checkboxes, stop Docker Desktop, then start it again and enable the integration again?
Have you tried another WSL distro or stopping wsl at all? You could try this with `wsl.exe --shutdown` and see if the quick restart of the WSL VM helps getting it going again.

**Comment by Machalkas** [comment]
Hello, @StefanScherer! Yes, I try to shutdown wsl, but it doesn't solve the problem. I try Debian distro and it works fine. But I want to find out is the any way to fix the problem without reinstalling distro?

**Comment by Machalkas** [comment]
Reinstalling Ubuntu solved a problem. This is cinde sad, because I initially wanted to solve the problem without reinstalling the distro.
