### ISSUE TITLE
Docker works but dockerd command is not available on Windows and WSL2

### ISSUE THREAD

**Issue by Anutrix** [docker/for-win#12700]
I was trying [run multiple daemons in same host](https://docs.docker.com/engine/reference/commandline/dockerd/#run-multiple-daemons) and faced this issue.

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 86E71BB9-9F3C-412E-8387-E10B17F9F0BD/20220504170817

### Actual behavior
Windows PowerShell:
```
> dockerd
dockerd: The term 'dockerd' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```
WSL2:
```
❯ dockerd
zsh: command not found: dockerd
❯ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```

### Expected behavior
`dockerd` command should work on Windows and WSL.

### Information
  - Is it reproducible? Yes.
  - Is the problem new? Not sure.
  - Did the problem appear with an update? I don't think so.
  - Windows Version: Windows 11 Pro 22000.652
  - Docker Desktop Version: 4.7.1 (77678)
  - Docker Enginer Version: 20.10.14
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
```
[2022-05-04T17:04:56.726234200Z][com.docker.diagnose.exe][I] ipc.NewClient: 7fed5b1b-com.docker.diagnose -> \\.\pipe\dockerBackendV2 com.docker.service.exe
[goroutine 1 [running, locked to thread]:
[win/backend/pkg/service.NewClientForPath(...)
[       win/backend/pkg/service/service.go:42
[win/backend/pkg/service.NewClient({0x108dbdb, 0x13}, {0x0, 0x0, 0x0})
[       win/backend/pkg/service/service.go:31 +0xd0
[common/pkg/diagkit/gather/diagnose.init()
[       common/pkg/diagkit/gather/diagnose/ipc_windows.go:23 +0x11f
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.
```

### Steps to reproduce the behavior

  1. Open a PowerShell or WSL2 terminal.
  2. Try any `dockerd` commands.

**Comment by thaJeztah** [comment]
This is expected; the docker daemon runs within Docker Desktop's VM when running Docker Desktop on Windows (and macOS); is there a specific need why you need access to the daemon CLI?

**Comment by Anutrix** [comment]
> This is expected; the docker daemon runs within Docker Desktop's VM when running Docker Desktop on Windows (and macOS); is there a specific need why you need access to the daemon CLI?

Yes. As I mentioned earlier I need multiple docker daemons in same host.

**Comment by Anutrix** [comment]
It was closed by mistake. Sry for the trouble.

**Comment by thaJeztah** [comment]
That's not a supported setup for Docker Desktop itself (and multiple daemons on the same host can cause other issues, as noted in that documentation you linked to); in that case you could try to create a manual setup where you install the Linux packages inside WSL2 (but you may need some special setup to make that work, as I don't think systemd is available on WSL2, and other things may be missing)

**Comment by Anutrix** [comment]
Since the documentation says it is experimental and the solution will available in the future, I thought it would be supported at some point.

Also, Windowsfilter option and LCOW (Linux Containers on Windows) options on same page seems let us use dockerd on Windows anyway. Maybe extending this support for WSL2 might work.

In any case, Thx. I'll try manual setup via Linux package installation inside WSL2 like you recommended.

For the exact use case, I wanted a way to run docker inside docker(DinD) using by mounting the sock file method but with 2nd daemon's sock for isolation. Only other non-privileged option seems to be sysbox runtime which I'm trying to avoid.

**Comment by thaJeztah** [comment]
>  I thought it would be supported at some point.

Not likely; there's many pitfalls in running multiple daemons (for example IPtables configuration, networking configuration in general, but also things like AppArmor, and multiple daemons using the same containerd (and with the same namespace). It's _possible_ (to some extend) to make it work, but not for the faint of heart.

> For the exact use case, I wanted a way to run docker inside docker(DinD) using by mounting the sock file method

In that case, you're not running docker-in-docker; it's only the CLI that runs in a container, but the daemon runs on the host.

Depending on your use-case, you _can_ run multiple "actual" docker-in-docker instances on the same machine. For example, using the following compose-file;

```yaml
services:
  docker:
    image: docker:20.10-dind
    privileged: true
    command: "--tls=false"
    volumes: 
      - "/var/lib/docker"
    environment:
      - "DOCKER_TLS_CERTDIR="
      - "DOCKER_HOST=tcp://0.0.0.0:2375"
  client:
    image: docker:20.10-dind
    command: docker version
    environment: 
      - "DOCKER_HOST=tcp://docker:2375"
    deploy:
      replicas: 0
```

That compose file starts a container with a docker daemon running. It also defines a client container (in this case also using the same image, but any image with the `docker` cli would do). That container has `0` instances by default, but your can do a `docker compose run` to start a container from it;

Start the docker daemon in the background;

```bash
docker compose up -d
[+] Running 2/2
 ⠿ Network dind_default     Created                                                                                                                                                                    0.0s
 ⠿ Container dind-docker-1  Started                                                                                                                                                                    0.4s
```

Use `docker compose run` to start the "client" container, which connects with the docker-in-docker daemon in the other container in the compose stack;

```bash
docker compose run -it client sh
/ # docker version
Client:
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:40:57 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:46:12 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

All data is stored in an anonymous / temporary volume (but you can use a named volume for it if it needs to be re-used)

**Comment by thaJeztah** [comment]
I don't think this will be fixed; docker desktop provides a single daemon installed in a VM; running multiple daemons directly on the host is considered "experimental", and not something that would be provided by docker desktop. (other than the docker-in-docker approach example I described above).

That said, you can open a ticket in the public roadmap, describing your use-case; https://github.com/docker/roadmap
