### ISSUE TITLE
Empty folder created for mounted volume

### ISSUE THREAD

**Issue by Namyalg** [docker/for-win#12706]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

I am trying to mount a volume to a container, a folder is created in the docker container, but the contents of the folder are empty

I have followed the steps : 

1.  `docker pull alpine`
2.  Contents of the folder `test_dir` that needs to be pushed
![image](https://user-images.githubusercontent.com/53875297/167256456-9525fe9a-4ac2-4789-bfed-b8d9be72027a.png)
3. `docker run -v test_dir:/test_dir -it  alpine`
4. Contents of `test_dir` in the container
![image](https://user-images.githubusercontent.com/53875297/167256597-9f66015d-9979-4ad9-b451-1d9f1972f77b.png)

### Expected behavior

The expected behavior is, being able to list the files in the folder mounted in the container

### Information

  - Windows Version: 10
  - Docker Desktop Version:4.7.1 
  - WSL2 or Hyper-V backend?  WSL2 backend

**Comment by StefanScherer** [comment]
Hello, 
Using `test_dir` on the left side tells Docker to create a named volume called `test_dir`. You can verify this by running `docker volume ls`.

To specify that it's a local directory, provide the full local path. In your case it should look like this:

```
docker run -v E:\sample\test dir:/test_dir -it alpine
```

**Comment by Namyalg** [comment]
thank you, this solved the problem
