### ISSUE TITLE
[wsl2] docker-credential-wincred.exe: Access is denied.

### ISSUE THREAD

**Issue by markbaas** [docker/for-win#12713]
- [ x ] I have tried with the latest version of Docker Desktop
  - [ x ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
When running the following command in wsl2: 
```
aws ecr get-login-password --region aws-region --profile default | docker login --username AWS --password-stdin 123456.dkr.ecr.aws-region.amazonaws.com
```
I get:
```
Error saving credentials: error storing credentials - err: exit status 1, out: `error getting credentials - err: fork/exec C:\Program Files\Docker\Docker\resources\bin\docker-credential-wincred.exe: Access is denied., out: 
```

### Expected behavior

I can login.

### Information
  - Is it reproducible? 
 Happens usually.
  - Is the problem new?
 Happens since a few weeks.
  - Did the problem appear with an update?
 Not sure

  - Windows Version: Windows 11 Pro (22000.613)
  - Docker Desktop Version: 4.7.1 (77678)
  - WSL2
  - No virtualization, directly on laptop.

**Comment by kamil-jakubowski** [comment]
Same problem here, after upgrading Windows 10 -> 11.
WSL2 ubuntu 20.04
Docker Desktop 4.8.2 (79419)
I successfully logged in Docker Desktop, but it seems that docker is not signed in on WSL2 Ubuntu.

When I try to pull images from Hub:
```
docker-compose up -d
[+] Running 0/1
 ⠦ mysql Pulling                                                                                                   5.6s
error getting credentials - err: exit status 1, out: `error getting credentials - err: fork/exec C:\Program Files\Docker\Docker\resources\bin\docker-credential-wincred.exe: Access is denied., out: ```
```

Trying to login:
```
 docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: ******
Password:
Error saving credentials: error storing credentials - err: exit status 1, out: `error getting credentials - err: fork/exec C:\Program Files\Docker\Docker\resources\bin\docker-credential-wincred.exe: Access is denied., out: ```
```

**Comment by markbaas** [comment]
yes, that works each time you restart docker, but problem returns.

**Comment by vlitvinovv** [comment]
Same problem for me. Do somebody has solution?
