### ISSUE TITLE
Error installing/upgrading to Docker 4.8.1 or 4.8.2

### ISSUE THREAD

**Issue by mikeazores** [docker/for-win#12711]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

When running the installation file, got the message "Docker installation failed" with the following details:

![image](https://user-images.githubusercontent.com/9259573/167608728-95187d4b-7683-47fb-9219-7d47c56b3314.png)

### Expected behavior

Docker should update my current installed version (3.5.2) to 4.8.1

### Information

  - Windows Version: 10 21H2 Build 1944.1645
  - Docker Desktop Version: 4.8.1
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

Gathering diagnostics for ID 6486C8D3-74FC-46BF-97C7-3EAF8FC3E9F3/20220510103737 into C:\Users\xxxx\AppData\Local\Temp\6486C8D3-74FC-46BF-97C7-3EAF8FC3E9F3\20220510103737.zip.
This may take up to 15 minutes.
time="2022-05-10T12:37:37+02:00" level=info msg="Triggering Linux sysrq via a unix socket: \\\\.\\pipe\\dockerDiagnosticd" type=unixsock
time="2022-05-10T12:37:37+02:00" level=warning msg="/sysrq failed: Post \"http://unix/sysrq\": open \\\\.\\pipe\\dockerDiagnosticd: The system cannot find the file specified." type=unixsock
time="2022-05-10T12:37:37+02:00" level=info msg="Start gathering list of 114 elements (timeout=15m0s)" type=list
time="2022-05-10T12:37:37+02:00" level=info msg="Gathering DiagKit" type=list
time="2022-05-10T12:37:37+02:00" level=info msg="Gathering BackendGatherer" type=list
time="2022-05-10T12:37:37+02:00" level=info msg="ipc.NewClient: e26178f8-DiagkitPKG -> \\\\.\\pipe\\dockerBackendApiServer [[STACK]]github.com/docker/pinata/common/pkg/backend.NewClientWithPath(...)\n\tC:/workspaces/3.5.x-merge/src/github.com/docker/pinata/common/pkg/backend/client.go:45\ngithub.com/docker/pinata/common/pkg/backend.NewClient(...)\n\tC:/workspaces/3.5.x-merge/src/github.com/docker/pinata/common/pkg/backend/client.go:51\ngithub.com/docker/pinata/common/pkg/diagkit/gather.BackendGatherer.Gather(0x113f8f8, 0xc000040360, 0x1141bd8, 0xc000290140)\n\tC:/workspaces/3.5.x-merge/src/github.com/docker/pinata/common/pkg/diagkit/gather/backend.go:36 +0x6c\ngithub.com/docker/pinata/common/pkg/diagkit/gather.(*Gatherers).Gather.func1(0xc0003ee310, 0x1141bd8, 0xc000290140, 0xc000004498, 0x113f8f8, 0xc000040360, 0xc00007e0c0)\n\tC:/workspaces/3.5.x-merge/src/github.com/docker/pinata/common/pkg/diagkit/gather/gather.go:89 +0x136\ncreated by github.com/docker/pinata/common/pkg/diagkit/gather.(*Gatherers).Gather\n\tC:/workspaces/3.5.x-merge/src/github.com/docker/pinata/common/pkg/diagkit/gather/gather.go:86 +0x225\n"
time="2022-05-10T12:37:37+02:00" level=info msg="(00e72f17) e26178f8-DiagkitPKG C->S GET /diagnostics/goroutines"
time="2022-05-10T12:37:37+02:00" level=error msg="(00e72f17) e26178f8-DiagkitPKG C<-S No response GET /diagnostics/goroutines (0s): Get \"http://ipc/diagnostics/goroutines\": open \\\\.\\pipe\\dockerBackendApiServer: The system cannot find the file specified.[[STACK]]"
time="2022-05-10T12:37:37+02:00" level=info msg="(b50e8855) e26178f8-DiagkitPKG C->S GET /ping"
time="2022-05-10T12:37:37+02:00" level=error msg="(b50e8855) e26178f8-DiagkitPKG C<-S No response GET /ping (0s): Get \"http://ipc/ping\": open \\\\.\\pipe\\dockerBackendApiServer: The system cannot find the file specified.[[STACK]]"
time="2022-05-10T12:37:38+02:00" level=info msg="(317114a2) e26178f8-DiagkitPKG C->S GET /ping"
time="2022-05-10T12:37:38+02:00" level=error msg="(317114a2) e26178f8-DiagkitPKG C<-S No response GET /ping (894.3µs): Get \"http://ipc/ping\": open \\\\.\\pipe\\dockerBackendApiServer: The system cannot find the file specified.[[STACK]]"
time="2022-05-10T12:37:38+02:00" level=info msg="(ee039e8e) e26178f8-DiagkitPKG C->S GET /ping"
time="2022-05-10T12:37:38+02:00" level=error msg="(ee039e8e) e26178f8-DiagkitPKG C<-S No response GET /ping (786.3µs): Get \"http://ipc/ping\": open \\\\.\\pipe\\dockerBackendApiServer: The system cannot find the file specified.[[STACK]]"
time="2022-05-10T12:37:39+02:00" level=info msg="(09c3e3b4) e26178f8-DiagkitPKG C->S GET /ping"
time="2022-05-10T12:37:39+02:00" level=error msg="(09c3e3b4) e26178f8-DiagkitPKG C<-S No response GET /ping (425µs): Get \"http://ipc/ping\": open \\\\.\\pipe\\dockerBackendApiServer: The system cannot find the file specified.[[STACK]]"
time="2022-05-10T12:37:39+02:00" level=info msg="(e6a4ddc5) e26178f8-DiagkitPKG C->S GET /ping"
time="2022-05-10T12:37:40+02:00" level=error msg="(e6a4ddc5) e26178f8-DiagkitPKG C<-S No response GET /ping (615.9µs): Get \"http://ipc/ping\": open \\\\.\\pipe\\dockerBackendApiServer: The system cannot find the file specified.[[STACK]]"
time="2022-05-10T12:37:40+02:00" level=info msg="(7552031b) e26178f8-DiagkitPKG C->S GET /ping"
time="2022-05-10T12:37:40+02:00" level=error msg="(7552031b) e26178f8-DiagkitPKG C<-S No response GET /ping (0s): Get \"http://ipc/ping\": open \\\\.\\pipe\\dockerBackendApiServer: The system cannot find the file specified.[[STACK]]"
time="2022-05-10T12:37:41+02:00" level=info msg="(0b072076) e26178f8-DiagkitPKG C->S GET /ping"
time="2022-05-10T12:37:41+02:00" level=error msg="(0b072076) e26178f8-DiagkitPKG C<-S No response GET /ping (850.3µs): Get \"http://ipc/ping\": open \\\\.\\pipe\\dockerBackendApiServer: The system cannot find the file specified.[[STACK]]"
time="2022-05-10T12:37:41+02:00" level=info msg="(b7694618) e26178f8-DiagkitPKG C->S GET /ping"
time="2022-05-10T12:37:41+02:00" level=error msg="(b7694618) e26178f8-DiagkitPKG C<-S No response GET /ping (565.8µs): Get \"http://ipc/ping\": open \\\\.\\pipe\\dockerBackendApiServer: The system cannot find the file specified.[[STACK]]"
time="2022-05-10T12:37:42+02:00" level=info msg="(02a9dcf4) e26178f8-DiagkitPKG C->S GET /ping"
time="2022-05-10T12:37:42+02:00" level=error msg="(02a9dcf4) e26178f8-DiagkitPKG C<-S No response GET /ping (829.7µs): Get \"http://ipc/ping\": open \\\\.\\pipe\\dockerBackendApiServer: The system cannot find the file specified.[[STACK]]"
time="2022-05-10T12:37:42+02:00" level=info msg="(023fa43e) e26178f8-DiagkitPKG C->S GET /ping"
time="2022-05-10T12:37:42+02:00" level=error msg="(023fa43e) e26178f8-DiagkitPKG C<-S No response GET /ping (845µs): Get \"http://ipc/ping\": open \\\\.\\pipe\\dockerBackendApiServer: The system cannot find the file specified.[[STACK]]"
time="2022-05-10T12:37:43+02:00" level=info msg="(e001fddf) e26178f8-DiagkitPKG C->S GET /ping"
time="2022-05-10T12:37:43+02:00" level=error msg="(e001fddf) e26178f8-DiagkitPKG C<-S No response GET /ping (0s): Get \"http://ipc/ping\": open \\\\.\\pipe\\dockerBackendApiServer: The system cannot find the file specified.[[STACK]]"
time="2022-05-10T12:37:43+02:00" level=info msg="(0d2eb476) e26178f8-DiagkitPKG C->S GET /ping"
time="2022-05-10T12:37:43+02:00" level=error msg="(0d2eb476) e26178f8-DiagkitPKG C<-S No response GET /ping (0s): Get \"http://ipc/ping\": open \\\\.\\pipe\\dockerBackendApiServer: The system cannot find the file specified.[[STACK]]"
time="2022-05-10T12:37:44+02:00" level=info msg="(50550e48) e26178f8-DiagkitPKG C->S GET /ping"
time="2022-05-10T12:37:44+02:00" level=error msg="(50550e48) e26178f8-DiagkitPKG C<-S No response GET /ping (0s): Get \"http://ipc/ping\": open \\\\.\\pipe\\dockerBackendApiServer: The system cannot find the file specified.[[STACK]]"

### Steps to reproduce the behavior

  1. Currently I have Docker for Windows v. 3.5.2 with WSL2 enabled and with the Docker distribution moved to my drive D:\ (using wsl --export and --import
  2. I'm trying to update my current docker version from 3.5.2 to latest 4.8.1
  3. If I download the installer and run it, I get the message stated before
  4. If I try to use the "Update and restart" from Docker icon in windows taskbar, I got a notification stating Docker will download in background and the upgrade will be applied after restart docker. After waiting several minutes, I try to restart and install the new version nothing happens (no error message and still in the same 3.5.2 version)

So, I'm stuck in version 3.5.2, Also tried with 4.8.0 with the same results.

**Comment by Namyalg** [comment]
I face the same issue

**Comment by mikeazores** [comment]
Tried to upgrade to Docker 4.0.1 (from 3.5.2) thinking the upgrade would be less dramatic and I get this error:

![image](https://user-images.githubusercontent.com/9259573/169003543-d04cb9b1-4ea9-4f9f-b919-6992d1adcc8d.png)

I do not know what to do. Any advice would be much appreciated. Thanks

**Comment by mikeazores** [comment]
I was able to install Docker Desktop 4.9.0. My steps:

Install it normally
It showed an error about symlinks:
![image](https://user-images.githubusercontent.com/9259573/173029607-1854a41a-df7d-4ae0-a697-cfa97ec46cdf.png)
Removed the symlinks and update Docker Desktop again and it did the trick.

I no longer have this issue.
