### ISSUE TITLE
docker run hello-world hangs

### ISSUE THREAD

**Issue by avrensburg** [docker/for-win#1271]
### Expected behavior
When running docker in Windows Container mode the hello-world sample and all other containers never start. 
### Actual behavior
hangs or freezes. 

![image](https://user-images.githubusercontent.com/31923756/32241743-9db444d4-be79-11e7-88a0-a22ec964d58d.png)

### Information
  - Diagnostic ID = E0FCA5C3-B17D-4881-9A5B-0F1482E365FE/2017-10-31_20-15-45
  - host distribution and version (Windows version, build number, etc) : 
     Microsoft Windows 10 Enterprise 2016 LTSB 
     Version 10.0.14393 
     Build 14393

### Steps to reproduce the behavior
docker run hello-world hangs

**Comment by mccormickt12** [comment]
I am seeing the same behavior for all container images
Docker version: 17.09.0-ce
Windows: Microsoft Windows 10 Enterprise 2016 LTSB Build 14393

on the docker event stream I only see a container create and container attach event and then it hangs.  Ive tried the images hello-world, microsoft/nanoserver and nanoserver/iis and they have all behaved the same for me.

**Comment by lawrencengan** [comment]
I have encountered the same problem that the hello-world program hangs after my laptop is rebooted and docker is up and running in Linux container mode. I have to quit docker and restart it manually to get the hello-world program working again. No setting needs to be changed. Hope this help.

**Comment by anied** [comment]
Sounding off that restarting docker _did_ resolved the issue for me.

**Comment by brobits** [comment]
this is still an issue. /remove-lifecycle stale /lifecycle frozen
