### ISSUE TITLE
Really Annoying messages after deleting images, containers.

### ISSUE THREAD

**Issue by jonathanorrego** [docker/for-win#12719]
In docker desktop (windows).
After delete something like a container, a big "toast" message confirming success will appear.
I have to wait till it disappear or  or go manually and click the "X" after deleting each image.
If I just don't close the message, then the message is above the menu and I cant click the menu.
When I delete 3 or more images I just cant navigate to other section to continue deleting.

**Comment by laurazard** [comment]
Hi @jonathanorrego! Thanks for reporting. The toaster message you mentioned in the issue has been removed, and the next release of Docker Desktop no longer has this issue.

Thanks!
