### ISSUE TITLE
Docker Desktop ignores manual proxies

### ISSUE THREAD

**Issue by dandrzejewski** [docker/for-win#12714]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Docker Desktop ignores manual proxy settings set through the UI.

### Expected behavior
Docker Desktop should honor manual proxy settings set through the UI.

### Information

  - Windows Version: 11, 21H2
  - Docker Desktop Version: 4.8.1
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

This is reproducible for me every time.  The problem has happened for me in every version after 4.6.0.

### Steps to reproduce the behavior

  1. Configure http and https proxies in Docker Desktop
  2. Try to pull an image
  3. Note that it fails.

This issue occurs for me in 4.8.1 and I had to roll all the way back to 4.6.0 to make this work.

**Comment by dandrzejewski** [comment]
Since this has been a long-standing issue, I'm happy to provide any other details as needed.  I can move back up to 4.8.1 to do any testing you might need, but for now I've got to stick with 4.6.0 so I can get work done.

**Comment by StefanScherer** [comment]
Thanks for the feedback. It's sad that you had to rollback to an older version. And thanks for your offer to help testing, this will help our team.
With 4.8 we improved reading the OS level proxy settings and we plan to deprecate the manual proxy settings in the future.
I'd like to get in touch with you to understand how you use proxies, why you need manual proxy settings. We can discuss here or you could reach out to me via mail stefan.scherer@docker.com or a DM in our community Slack. Thank you.

**Comment by glindsay78** [comment]
Having the same issue and had to downgrade to 4.7.1 for it to work. Happy to help also Stefan if you need another guinea pig. thanks for looking into this.

**Comment by laurazard** [comment]
Hi @dandrzejewski, thanks for submitting this issue! I think we've identified the problem, could you test [this build](https://desktop-stage.docker.com/win/main/amd64/79160/Docker%20Desktop%20Installer.exe) and let me know if the issue is resolved? @glindsay78 same for you :)

Thanks!

**Comment by paulchambers** [comment]
Same issue here and the test build has resolved it and is honoring the manual proxy settings again.

3.7.1 and 3.9.0 both working as expected. 3.8.1 broken.

**Comment by dandrzejewski** [comment]
> we plan to deprecate the manual proxy settings in the future

I would caution against this, some of us work in complex proxy environments and it may be necessary to manually set proxies at various times.

I'll test the provided build shortly and provide feedback - thanks for the quick response to this!

**Comment by laurazard** [comment]
Thanks for the feedback @dandrzejewski. If you care, there's a roadmap item [here](https://github.com/docker/roadmap/issues/339) where you can leave further feedback that we are looking at.

**Comment by dandrzejewski** [comment]
Everything seems to be working except the extensions marketplace - that does not appear to load.

**Comment by glindsay78** [comment]
> Hi @dandrzejewski, thanks for submitting this issue! I think we've identified the problem, could you test [this build](https://desktop-stage.docker.com/win/main/amd64/79160/Docker%20Desktop%20Installer.exe) and let me know if the issue is resolved? @glindsay78 same for you :)
> 
> Thanks!

Yes this build is working for me. Thanks!

**Comment by StefanScherer** [comment]
@dandrzejewski Thanks for raising this. Indeed, we encountered an issue that the extensions marketplace isn't reachable behind a proxy at the moment. The team is working on it.

**Comment by awynnejo** [comment]
Same issue here, 4.8.1 broken but 4.9.0 has resolved it.

**Comment by mat007** [comment]
Hi, we have just released Docker Desktop 4.8.2 with a fix. Thanks!
