### ISSUE TITLE
Illegible Check Report Due to Bad Choice of Font Colors

### ISSUE THREAD

**Issue by cmoher3** [docker/for-win#12727]
I can't even begin to read the Diagnose Check report because it's dark red lettering on a dark blue background. Not sure why those colors were chosen or how it's gone this far without a wave of complaints.

**Comment by cmoher3** [comment]
I can't read the diagnose report due to almost zero contrast between red font and blue backdround,

**Comment by laurazard** [comment]
Hi @cmoher3, thank you for your report. Do you mean the output of the command `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`, or something else?

**Comment by cmoher3** [comment]
Yes I think so. Can you please include my original message and not just your reply ? Expect delays in my reply by a few days. I am just on the verge of departing on transcontinental airflights. Thanks.
________________________________

**Comment by cmoher3** [comment]
OK just reading this in the GitHub now and yes that is correct. I get a deep dark red font on a deep dark blue background.  A very strange and illegible choice of colors.

**Comment by cmoher3** [comment]
Mark Allen, representing EDX, a significant corporate client of yours, is also monitoring this trouble report. We are really dragging here and I hope it's not because I do not have a paid account. EDX certainly does and has an interest in seeing this issue resolved. An update would be great. I'll ask Mr. Allen to open a report also, with this request appended to it.

**Comment by laurazard** [comment]
If you are referring to the command line output of the diagnostics command as you confirmed, it's important to realize that the background color is not controlled by us. Depending on what operating system you are using, what terminal emulator, and your own configuration, it's possible to change the background color (also depending on dark mode vs light mode, etc). If the background does not have a lot of contrast against our output, I would suggest you change the background color, or save the output to a text file and view it there.

**Comment by cmoher3** [comment]
Well I reinstalled everything and the next time, I got more legible colors. I was not in any sort of night mode so i don't know what is going on. Can you tell me where I can post the diagnostic report so I can get this working ? EDX is also anxious to see it resolved as they have thousands of students who may run into the same issues. Thank you.
________________________________

**Comment by laurazard** [comment]
You can find instructions as how to gather and upload the diagnostics [report here](https://docs.docker.com/desktop/mac/troubleshoot/#diagnosing-from-the-terminal). Please follow those steps, and then feel free to open another issue in this repository, following the template it suggests, and fill in the `diagnostics id` there so we can take a more in depth look. Something that would also be useful would be if you were to upload screenshots of the screens you are having accessibility issues with.

**Comment by cmoher3** [comment]
I just get an empty zip file after running the diagnostics with those instructions. I have added a screen grab from the PowerShell after this first screen shot.

[cid:2b67f384-2859-45b9-ae86-a598acc5fc15]
[cid:36de7eaa-bd89-4dee-92bd-ce95ecb9e2d0]
________________________________
