### ISSUE TITLE
Double 4.8.0 release notes

### ISSUE THREAD

**Issue by ShadowSpade** [docker/for-win#12720]
- [x ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

double 4.8.0 release notes on the website

### Expected behavior

not double 4.8.0 release notes on the website

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by StefanScherer** [comment]
It's fixed.
