### ISSUE TITLE
Error response from daemon: Get "https://registry-1.docker.io/v2/": proxyconnect tcp: dial tcp 192.168.65.1:3128: connect: connection refused

### ISSUE THREAD

**Issue by onlookor** [docker/for-win#12725]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Docker aborts pulling the image with the following exception:
`D:\docker\dockerfiles\busybox\shanghai-utf>docker pull busybox
Using default tag: latest
Error response from daemon: Get "https://registry-1.docker.io/v2/": proxyconnect tcp: dial tcp 192.168.65.1:3128: connect: connection refused`
### Information

  - Windows Version: Windows 10 Pro, 21h2, 19044.1706
  - Docker Desktop Version: 4.8.1 (78998)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

>[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[FAIL] DD0012: is the VM networking working? network checks failed: failed to ping host: exit status 1
[2022-05-16T03:00:42.385871900Z][com.docker.diagnose.exe][I] ipc.NewClient: a9083c1b-diagnose-network -> \\.\pipe\dockerDiagnosticd diagnosticsd
[common/pkg/diagkit/gather/diagnose.runIsVMNetworkingOK()
[       common/pkg/diagkit/gather/diagnose/network.go:34 +0xdd
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x152f8a0)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x152f8a0)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2?, 0x152f8a0)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x152f8a0, 0xc0004dd730)[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0xcb00000012?, 0xc0004dd730)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0xefa960?, 0xc00025f890)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x152fea0, 0xef4300?, {0xc00025fb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1cb
[main.checkCmd({0xc0000963b0?, 0xc0000963b0?, 0x4?}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:132 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:98 +0x27f
[2022-05-16T03:00:42.385871900Z][com.docker.diagnose.exe][I] (eae45802) a9083c1b-diagnose-network C->S diagnosticsd POST /check-network-connectivity: {"ips":["10.210.48.237","192.168.112.1","172.18.16.1"]}
[2022-05-16T03:00:42.922728300Z][com.docker.diagnose.exe][W] (eae45802) a9083c1b-diagnose-network C<-S dbc73aa1-diagnosticsd POST /check-network-connectivity (536.8564ms): failed to ping host: exit status 1

[FAIL] DD0032: do Docker networks overlap with host IPs? network concourse-ci_default has subnet 172.18.0.0/16 which overlaps with host IP 172.18.16.1
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 2 issues:

1 : The test: is the VM networking working?
    Failed with: network checks failed: failed to ping host: exit status 1
VM seems to have a network connectivity issue. Please check your host firewall and anti-virus settings in case they are blocking the VM.
2 : The test: do Docker networks overlap with host IPs?
    Failed with: network concourse-ci_default has subnet 172.18.0.0/16 which overlaps with host IP 172.18.16.1
>
### Steps to reproduce the behavior

  Switch the "Manual proxy configuration" on and off, it behaves the same.
  In other words, the behavior exactly the same as [ Error response from daemon: Get https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp 127.0.0.1:8080: connect: connection refused #9400 ](https://github.com/docker/for-win/issues/9400), except for the proxy ip 192.168.65.1 and port 3128, not same as its 127.0.0.1:8080.

### Follow up
The command `docker info` outputs this:

> HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
>
Then I looked up my ~/.docker/ config.json. Below is its all whole content:
`{
  "auths": {},
  "credsStore": "desktop",
  "currentContext": "default",
  "stackOrchestrator": "swarm"
}
`
And no "proxy" thing in my daemon.json.
So my question is, Who, and how, tucked the piece of proxy config into my docker?

**Comment by onlookor** [comment]
The command `docker info` outputs this:

> HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
Then I looked up my ~/.docker/ config.json. Below is its all whole content:
`{
  "auths": {},
  "credsStore": "desktop",
  "currentContext": "default",
  "stackOrchestrator": "swarm"
}
`
So my question is, Who, and how, tucked the piece of proxy config into my docker?

**Comment by koraysaritas** [comment]
I have the same problem. The strange thing is that I can pull images if I switch to Windows containers.

**Comment by koraysaritas** [comment]
> Hi! Thank you both for the information and the reports, it's really useful for us to figure out the issue! In 4.8, we shipped a feature that enables Docker Desktop to use the proxy you have configured at the OS level. However, at the same time we also had a regression where Docker Desktop stopped respecting manual proxy configuration, which we've fixed in this internal build:
> 
> * [Mac Intel](https://desktop-stage.docker.com/mac/main/amd64/79243/Docker.dmg)
> * [Mac M1](https://desktop-stage.docker.com/mac/main/arm64/79243/Docker.dmg)
> * [Windows](https://desktop-stage.docker.com/win/main/amd64/79243/Docker%20Desktop%20Installer.exe)
> 
> @onlookor @koraysaritas could you try that build and let us know if it solves your issue? Thanks!

I have completely removed the Docker Desktop from my computer and installed the version that you have shared. Unfortunately the problem continues on my PC.

I ran diagnostics on Docker 4.9.0 and just uploaded the report with Diagnostics ID: E3E4939F-D005-497D-9B2C-01E989237B4D/20220517103937

**Comment by onlookor** [comment]
> 

I found the same proxy config in docker desk 4.8.1 for mac, it works fine in Mac Intel.
I'll try your internal build later.

**Comment by onlookor** [comment]
> Hi! Thank you both for the information and the reports, it's really useful for us to figure out the issue! In 4.8, we shipped a feature that enables Docker Desktop to use the proxy you have configured at the OS level. However, at the same time we also had a regression where Docker Desktop stopped respecting manual proxy configuration, which we've fixed in this internal build:
> 
>     * [Mac Intel](https://desktop-stage.docker.com/mac/main/amd64/79243/Docker.dmg)
> 
>     * [Mac M1](https://desktop-stage.docker.com/mac/main/arm64/79243/Docker.dmg)
> 
>     * [Windows](https://desktop-stage.docker.com/win/main/amd64/79243/Docker%20Desktop%20Installer.exe)
> 
> 
> @onlookor @koraysaritas could you try that build and let us know if it solves your issue? Thanks!

I find the same proxy config in ver 4.8.1 for mac. It's a Mac Intel, docker pull works fine.
I'll try your internal build later.

**Comment by onlookor** [comment]
> Hi! Thank you both for the information and the reports, it's really useful for us to figure out the issue! In 4.8, we shipped a feature that enables Docker Desktop to use the proxy you have configured at the OS level. However, at the same time we also had a regression where Docker Desktop stopped respecting manual proxy configuration, which we've fixed in this internal build:
> 
>     * [Mac Intel](https://desktop-stage.docker.com/mac/main/amd64/79243/Docker.dmg)
> 
>     * [Mac M1](https://desktop-stage.docker.com/mac/main/arm64/79243/Docker.dmg)
> 
>     * [Windows](https://desktop-stage.docker.com/win/main/amd64/79243/Docker%20Desktop%20Installer.exe)
> 
> 
> @onlookor @koraysaritas could you try that build and let us know if it solves your issue? Thanks!
And I'm sure the OS level proxy is closed with netsh command.

**Comment by Misiu** [comment]
I can't pull images from dockerhub 😢 

```
PS C:\Windows\system32> docker pull rabbitmq
Using default tag: latest
Error response from daemon: Get "https://registry-1.docker.io/v2/": unable to connect to HTTP proxy 127.0.0.1:8888
PS C:\Windows\system32>
```

**Comment by jakesco** [comment]
I'm also having the same issue. I tried upgrading to 4.9.0, but still have the same problem. 
Diagnostics ID: 5A252C79-37B1-4AE3-B9CD-971065D55A50/20220606193908

More than just not being able to pull images from DockerHub, existing images on my machine don't seem to have any network connectivity. They can connect to each other, but not out to the internet. 

The output of the docker health check mentions a network connectivity issue related to anti-virus or firewall. We've tried disabling all anti-virus and firewalls on the machine but are still experiencing the problem.

I've tried a full re-install of both Docker Desktop and WSL. Our IT staff have also tried a fresh install on a new test machine but they run into the same issue.

As an experiment, I have been able to get `docker-ce` running normally in Ubuntu 20.04 in WSL2 (outside of Docker Desktop).

**Comment by onlookor** [comment]
> I have the same problem. The strange thing is that I can pull images if I switch to Windows containers.

Hi, here's something maybe you would be interested in ...
[[Docker on windows fails to pull linux images behind proxy](https://github.com/docker/for-win/issues/894#)
#894](https://github.com/docker/for-win/issues/894)

**Comment by hitinder** [comment]
This error is still active. Tried so many things but nothing works TBH.

Using v4.10.1 (82475)

![image](https://user-images.githubusercontent.com/9841229/179304367-e9450d59-f4a3-4a98-a3e5-7091d48996cf.png)
