### ISSUE TITLE
Disabling Extensions keeps the background process running

### ISSUE THREAD

**Issue by shochdoerfer** [docker/for-win#12723]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

I have disabled Docker Extensions because of some intensive CPU & RAM usage. I restarted Docker Desktop and even rebooted but the background process is still active and consuming CPU & RAM.

### Expected behavior

I would have expected the background process not to start when I disable it via the settings. Not sure though what's the purpose of that process.

### Information

  - Windows Version: Windows 10 (Version 21H1; Build 19043.1706)
  - Docker Desktop Version: 4.8.1 (78998)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Disable Docker Extension in the settings, restart Docker Desktop & Windows
  2. Check the running processes in Task Manager to see that the Docker Desktop Extension process is still running

**Comment by laurazard** [comment]
Hi @shochdoerfer, thank you for your report! For this issue in particular, we're aware and are shipping a fix in the next release of Docker Desktop.

Thank you!
