### ISSUE TITLE
Docker desktop settings is not loading in windows 10

### ISSUE THREAD

**Issue by shankar55** [docker/for-win#12735]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...
![Capture](https://user-images.githubusercontent.com/41586715/169469045-efd0ab99-402b-46bc-b40b-df63900908ca.PNG)

**Comment by laurazard** [comment]
Hi @shankar55, thanks for reporting this issue! For us to be able to investigate this, we need some more data. Please follow [these instructions](https://docs.docker.com/desktop/mac/troubleshoot/#diagnosing-from-the-terminal) and file another ticket with the diagnostics id/more data so we can follow up. Thank you!

**Comment by shankar55** [comment]
Hi @laurazard, thanks for your reply, the issue has been resolved by uninstalling the installation files and reinstalling the docker desktop again from the start.
