### ISSUE TITLE
Unable to switch to Windows Containers on Windows 11 Home

### ISSUE THREAD

**Issue by ramganesh19** [docker/for-win#12736]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 404AAC03-654F-4E20-A51B-508CBE81D98D/20220521001918 

### Actual behavior
I am on Windows 11 Home, 10.0.22000 Build 22000
Docker Desktop for Windows 4.8.2 79419
Desktop client still show "Switch to Windows Container" after click on few times and I dont see it toggling between Linux and Windows conatiners
I tried the same with command line still no difference in behavior.

### Expected behavior
I hoping the menu to change "Switch to Linux container" after I click on "Switch to Windows Container" and vice versa
### Information

  - Windows Version: Windows 11 Home, 10.0.22000 Build 22000
  - Docker Desktop Version: Windows 4.8.2 79419
  - WSL2 or Hyper-V backend?  WSL2 
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
PS C:\Users\ramg1> & "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[FAIL] DD0023: is the Containers Windows Feature enabled? required Windows Feature not installed: Containers
[2022-05-21T00:34:04.525505500Z][com.docker.diagnose.exe][I] ipc.NewClient: 494e1f27-com.docker.diagnose -> \\.\pipe\dockerBackendV2 com.docker.service.exe
[win/backend/pkg/service.NewClientForPath(...)
[       win/backend/pkg/service/service.go:44
[win/backend/pkg/service.NewClient({0xc2a6df, 0x13}, {0x0, 0x0, 0x0})
[       win/backend/pkg/service/service.go:33 +0xd0
[common/pkg/diagkit/gather/diagnose.checkWindowsFeature({{0xc2238d?, 0x1194038?}, {0xc2238d?, 0x1?}})
[       common/pkg/diagkit/gather/diagnose/features_windows.go:11 +0x51
[common/pkg/diagkit/gather/diagnose.glob..func6()
[       common/pkg/diagkit/gather/diagnose/dockerd_windows.go:9 +0x35
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x11a18e0)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x11a18e0)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x4?, 0x11a18e0)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x3, 0x11a18e0, 0xc00034b730)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x11a1760?, 0xc00034b730)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x11a17e0?, 0xc00034b730)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0xcb00000012?, 0xc00034b730)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0xb6a960?, 0xc0002df890)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x11a1f60, 0xb64300?, {0xc0002dfb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1cb
[main.checkCmd({0xc0000963b0?, 0xc0000963b0?, 0x4?}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:132 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:98 +0x27f
[2022-05-21T00:34:04.525505500Z][com.docker.diagnose.exe][I] (20727e3d) 494e1f27-com.docker.diagnose C->S com.docker.service.exe POST /windowsfeatures/check: [{Name:Containers Description:Containers}]
[2022-05-21T00:34:04.736351200Z][com.docker.diagnose.exe][I] (20727e3d) 494e1f27-com.docker.diagnose C<-S b7f5d27a-ServiceAPI POST /windowsfeatures/check (210.8457ms): {"NotAvailable":[{"Description":"Containers","Name":"Containers"}],"NotEnabled":[]}

[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: is the Containers Windows Feature enabled?
    Failed with: required Windows Feature not installed: Containers

The Containers Windows Feature is needed to use Windows OSes inside containers.

PS C:\Users\ramg1>
### Steps to reproduce the behavior

  1. Click on Switch to Windows Container and keep repeating

**Comment by laurazard** [comment]
Hi @ramganesh19, thanks for your report! As per [Microsoft documentation here](https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=Windows-Server), for working with Windows containers, on Windows 10/11:
> - One physical computer system running Windows 10 or 11 Professional or Enterprise with Anniversary Update (version 1607) or later.
> - [Hyper-V](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/reference/hyper-v-requirements) should be enabled.
Unfortunately, Hyper-V is not officially supported on Windows 10/11 Home editions.
