### ISSUE TITLE
Volume mount case sensitivity and duplication

### ISSUE THREAD

**Issue by bzier** [docker/for-win#1273]
### Expected behavior
Mounting a volume to a path as a part of `docker run` should take precedence over a volume being 'exposed' or created as a result of the Dockerfile.

### Actual behavior
The path specified is case-sensitive (despite Windows being case-insensitive) resulting in two volumes being mounted to the same path within the container, one which was created with a unique ID as a result of the specification in the Dockerfile, one which was named as a part of the `docker run` command.

### Information

  - a reproducible case if this is a bug, Dockerfiles FTW
    using the Dockerfile for TeamCity [here](https://github.com/JetBrains/teamcity-docker-minimal-agent/blob/master/windowsservercore/Dockerfile)
    line 17 is specified as `VOLUME C:/BuildAgent/conf`
    the (generalized) run command is:
    ```
    docker run -dit 
        --name SomeName
        -e SERVER_URL="https://teamCityServer:9999/"
        -e AGENT_NAME="SomeName"
        --mount source="my-custom-volume-name",target=C:\BuildAgent\conf
        repo/custom-team-city-image:1.0.0
    ```

  - host distribution and version (Windows version, build number, etc)
    `Docker version 17.06.1-ee-1, build 4dd6e94`
    ```
    Windows Server 2016 Datacenter
    ------------------------------
    Major  Minor  Build  Revision
    -----  -----  -----  --------
    10     0      14393  0
    ```

### Steps to reproduce the behavior

  1. Expose a `VOLUME` in the Dockerfile using mixed-case (e.g. `VOLUME C:/BuildAgent/conf`) (also worth noting, in this case forward-slashes are used, but that may or may not make a difference)
  2. Run a container from the image specifying a named volume mount to the same location as specified above using the same case (e.g. `--mount source="my-custom-volume-name",target=C:\BuildAgent\conf`) (also worth noting, in this case back-slashes were used, but that may or may not make a difference)
  3. Run `docker volume ls` and note that two volumes were created, one with the name specified in step 2, and one with a unique ID
  4. Run `docker inspect <container ID>` to see the two mounts both pointing to the same container path; however, also note that the case of the generated mount is now all lower-case (also, the destination path back-slashes are escaped):
```
"Mounts": [
    {
        [...]
        "Destination": "C:\\BuildAgent\\conf",
        [...]
        "Destination": "c:\\buildagent\\conf",
        [...]
    }
]
```

Please feel free to let me know if you need any more information, or a more specific example. I haven't reproduced this outside of the context mentioned above, but I believe it would be fairly easy to do an isolated repro. If that would be helpful, please let me know.

**Comment by bzier** [comment]
Oh I also forgot to mention that changing the mount switch to lower case (`--mount source="my-custom-volume-name",target=c:\buildagent\conf`) results in the desired outcome. The destination matches the definition in the Dockerfile and only one volume gets created...the named one specified in the run command.

**Comment by bzier** [comment]
As far as I know this is still an issue. I don't have the ability to repro it on the machine I'm using at the moment, but will re-test as soon as I can and post back here.

**Comment by rn** [comment]
This does not look like an issue with the Docker for Windows application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place.
Thanks
