### ISSUE TITLE
Switching from "local" to "remote repositories" clears the search field, but not the results list

### ISSUE THREAD

**Issue by SIMULATAN** [docker/for-win#12738]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [ ] ~~I have uploaded Diagnostics~~

*note: I didn't upload Diagnostics seeing as this seems like an UX issue and not a technical one*

### Actual behavior
When in the "images" section, you can search for local images.
Once you switch to "remote repositories" and back the search field will be cleared, but the result list still only shows the search results.

![gif recording](https://user-images.githubusercontent.com/63104422/169640327-d003514b-d451-4fef-bbee-dd5b94de20aa.gif)

### Expected behavior
Either both elements get cleared, or none.

### Information

  - **Windows Version:** Windows 10 Pro 21H2
  - **Docker Desktop Version:** 4.8.2 (79419)
  - **WSL2 or Hyper-V backend?** WSL2
  - **Are you running inside a virtualized Windows e.g. on a cloud server or a VM:** no

### Steps to reproduce the behavior

  1. Go to the "Images" section (in the left sidebar)
  2. Type in the name of an image in the search field
  3. Switch to "remote repositories" and back
  4. The search field is empty, but the list below only shows the results for the query

**Comment by laurazard** [comment]
Hi @SIMULATAN, thanks for your report! I'm going to create an internal ticket to track this bug, thank you :)

**Comment by maxcleme** [comment]
This issue has been fixed in latest release, please consider updating to latest version and give us your feedback!

[4.10.0 Release notes](https://docs.docker.com/desktop/release-notes/#docker-desktop-4100)
