### ISSUE TITLE
A solution that worked for me from the front-end: Go to docker desktop --> Troubleshoot --> Clean / Purge data --> click on wsl 2 and delete.

### ISSUE THREAD

**Issue by alimumtaz205** [docker/for-win#12743]
A solution that worked for me from the front-end: Go to docker desktop --> Troubleshoot --> Clean / Purge data --> click on wsl 2 and delete. 

Once removed, the docker deamon restarted and it worked fine.
![image](https://user-images.githubusercontent.com/32958585/163249939-a963dbf4-cf48-44be-8187-428d717b1faf.png)

_Originally posted by @ajay16bharadwaj in https://github.com/docker/for-win/issues/12576#issuecomment-1098376203_

**Comment by laurazard** [comment]
Hi @alimumtaz205, thanks for submitting an issue! Since this isn't strictly an issue, it can be confusing for people looking at the issues list without context. I'm going to close this issue but keep your comment in the other one.
