### ISSUE TITLE
Docker Desktop Installer.exe –backend=wsl-2 Is Not Working

### ISSUE THREAD

**Issue by bretboss** [docker/for-win#12746]
I am trying to automate the installation of Docker Desktop and some Linux containers on Windows 11 Enterprise but am unable to default Docker to use WSL 2.

According to the [Docker Desktop Installer documentation](https://docs.docker.com/desktop/windows/install/) the --backend=wsl-2 parameter should setup Docker to run using WSL2. But when I launch “Docker Desktop.exe” for the first time it shows the error: “Required Windows features(s) not enabled: Hyper-V. Switch to WSL 2 base engine?” This stops automation and requires manual entry before installing the Linux containers.

A log file entry in c:\program data\Docker Desktop\install-log-admin.1.txt appears to know that WSL 2 is desired as it has this entry:

> Selected backend mode: wsl-2

The Powershell script I am using to run the installer is the following:

`Start-Process -Wait -NoNewWindow -FilePath "Docker Desktop Installer.exe" -ArgumentList "install --backend=wsl-2 --quiet --accept-license " -ErrorAction Stop;`

But if I launch the installer manually/interactively and keep the default options then Docker Desktop is setup to use WSL 2 and doesn’t display this error.

[I posted this to Docker forum and another engineer was able to reproduce it.](https://forums.docker.com/t/docker-desktop-installer-exe-backend-wsl-2-is-not-working/124854)

Is there a workaround?

Note: Docker Desktop Version: 4.8.2

Things I’ve tried that have failed:
- Using command-line instead of PowerShell

**Comment by mat007** [comment]
Hi @bretboss and thanks for reporting.
From your description that sounds like a bug: I have created an internal ticket in our backlog to have someone take a look.

**Comment by bretboss** [comment]
In the meantime, is there any workaround?
For example, is there any configuration file value I can have the automation modify and then restart docker-desktop so that it will launch using WSL 2?

**Comment by maroschutte** [comment]
I ran into the same issue. My windows version is windows 10 enterprise and the docker desktop version is 4.9.0

I don't have a workaround yet, but perhaps the settings in C:\Users\myuserid\AppData\Roaming\Docker\settings.json could help, it contains a wslEngineEnabled entry

**Comment by maroschutte** [comment]
Thanks, adding "wslEngineEnabled": true to C:\ProgramData\DockerDesktop\install-settings.json before starting docker desktop for the first time did the trick.

**Comment by ebriney** [comment]
Here is a build with a fix: https://desktop-stage.docker.com/win/main/amd64/80802/Docker%20Desktop%20Installer.exe
Can you test it @bretboss ?

**Comment by maroschutte** [comment]
Hi, I'm not 'bretboss', but I've tested this new build and it works fine without the trick of adding to the install-settings.json file. I've tried both a --quiet install and a normal. Also works without providing --backend=wsl-2, so it seems wsl2 is really the default now.

Details of what I did:
- quit docker desktop
- uninstall docker desktop
- remove
  - <home>/.docker
  - <home>/appdata/local/Docker
  - <home>/appdata/roaming/Docker
  - <home>appdata>roaming/Docker Desktop
  - C:/ProgramData/DockerDesktop
  - C:/Program Files/Docker (because uninstall leaves the cli-plugins folder. is that intended ?)
- Docker Desktop Installer.exe install --accept-license --backend=wsl-2

In my second try the install command was:
- Docker Desktop Installer.exe install --accept-license --quiet

**Comment by bretboss** [comment]
@ebriney Yes, your build fixed the issue.
Thank you!

**Comment by fallmake** [comment]
@maroschutte doesn't work for me. 4.9.1.81317, _--quiet_, with/without _--backend=wsl-2_ and without Hyper-V installed gives me an error dialog "Required Windows feature(s) not enabled: Hyper-V. Switch to WSL 2 based engine?". WSL 2 running/all fine. After switchting to it via the button in the dialog everything's fine. WSL2 wasn't set as default and it seemed that the backend parameter is being ignored.

**Comment by bretboss** [comment]
@fallmake You need to use 4.10.0.80802 which @ebriney provided a link to a few messages up.

**Comment by bretboss** [comment]
Has this been rolled into a normal release yet (4.10.0 or 4.10.1)?

**Comment by mat007** [comment]
@bretboss yes this was released with 4.10.0.
I’m not quite sure why this missed [the release notes](https://docs.docker.com/desktop/release-notes/#docker-desktop-4100), I’ll open a PR to fix that.

**Comment by mat007** [comment]
We’ve added it back to the release notes, closing this issue then now.
