### ISSUE TITLE
docker pull ... Error response from daemon: Get "https://registry-1.docker.io/v2/": ...

### ISSUE THREAD

**Issue by lfthiang** [docker/for-win#12750]
## Diagnostics ID 

  - [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 26624E28-712F-4563-B4F6-7768405E55A1/20220526011441

### Actual behavior
Unable to docker pull images (or access network).

### Expected behavior
Should be able to docker pull images.

### Information
  - Is it reproducible? 
Yes

  - Is the problem new?
No.
I first had the issue in Mar with Docker Desktop for Windows 4.5.1
See https://forums.docker.com/t/docker-run-hello-world-get-https-registry-1-docker-io-v2-service-unavailable/122531
I am still having issue with the current version 4.8.2 (79419) 

  - Did the problem appear with an update?
No. I was using Docker Desktop 4.5.1 with no issue. It just appears one day. 
Please refer to my post on Docker forum https://forums.docker.com/t/docker-run-hello-world-get-https-registry-1-docker-io-v2-service-unavailable/122531
From what I know, there was no Windows update & I did not change any software either.
  
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.
Please see steps to reproduce the behaviour below.

  - Windows Version: 
Windows 10 Education version 21H2 OS build 19044.1586

  - Docker Desktop Version: 
4.8.2 (79419) 

  - WSL2 or Hyper-V backend?  
WSL2

  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: 
No. Running native on my laptop

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[FAIL] DD0005: is the user in the docker-users group? The specified domain either does not exist or could not be contacted.
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[FAIL] DD0012: is the VM networking working? network checks failed: failed to ping host: exit status 1
[2022-05-26T01:41:54.285207400Z][com.docker.diagnose.exe][I] ipc.NewClient: b0531f5d-diagnose-network -> \\.\pipe\dockerDiagnosticd diagnosticsd
[common/pkg/diagkit/gather/diagnose.runIsVMNetworkingOK()
[       common/pkg/diagkit/gather/diagnose/network.go:34 +0xdd
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1251960)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1251960)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2?, 0x1251960)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1251960, 0xc000079730)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0xcb00000012?, 0xc000079730)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0xc1a960?, 0xc00025f890)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x1251f60, 0xc14300?, {0xc00025fb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1cb
[main.checkCmd({0xc0000a63b0?, 0xc0000a63b0?, 0x4?}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:132 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:98 +0x27f
[2022-05-26T01:41:54.285207400Z][com.docker.diagnose.exe][I] (795d3539) b0531f5d-diagnose-network C->S diagnosticsd POST /check-network-connectivity: {"ips":["172.17.64.1","192.168.16.1","192.168.199.1","192.168.52.1","192.168.10.115"]}
[2022-05-26T01:41:54.838944900Z][com.docker.diagnose.exe][W] (795d3539) b0531f5d-diagnose-network C<-S 46c4b8e0-diagnosticsd POST /check-network-connectivity (553.7375ms): failed to ping host: exit status 1

[FAIL] DD0032: do Docker networks overlap with host IPs? network bridge has subnet 172.17.0.0/16 which overlaps with host IP 172.17.64.1
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 3 issues:

1 : The test: is the user in the docker-users group?
    Failed with: The specified domain either does not exist or could not be contacted.

The current user must be member of the docker-users group. Press the Win + R keys to open Run, type lusrmgr.msc into Run, followed by Enter to open Local Users and Groups.

2 : The test: is the VM networking working?
    Failed with: network checks failed: failed to ping host: exit status 1

VM seems to have a network connectivity issue. Please check your host firewall and anti-virus settings in case they are blocking the VM.

3 : The test: do Docker networks overlap with host IPs?
    Failed with: network bridge has subnet 172.17.0.0/16 which overlaps with host IP 172.17.64.1

If the subnet used by a Docker network overlaps with an IP used by the host, then containers
won't be able to contact the overlapping IP addresses.

Please try configuring the IP address range used by networks: in your docker-compose.yml.
See https://docs.docker.com/compose/compose-file/compose-file-v2/#ipv4_address-ipv6_address

#### Notes on the diagnostic results
   - Failed with: The specified domain either does not exist or could not be contacted.
I am not on my corporate network when I ran the diagnostic tool.

   - Failed with: network bridge has subnet 172.17.0.0/16 which overlaps with host IP 172.17.64.1 
I had tried changing the subnet range by adding the following lines to daemon.json via Settings > Docker Engine. This diagnostic is gone but I still have the "docker pull" problem.
```
"default-address-pools":
  [
    {"base":"10.10.0.0/16","size":24}
  ]
```

### Steps to reproduce the behavior
 ```
C:\>docker pull python:3-slim
Error response from daemon: Get "https://registry-1.docker.io/v2/": unable to connect to 52.72.255.218:443. Do you need an HTTP proxy?

C:\>docker run hello-world
Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": unable to connect to 54.144.118.70:443. Do you need an HTTP proxy?.
See 'docker run --help'.
```

**Comment by lfthiang** [comment]
I have just updated to **version 4.9.1**. The issue persists. All details are the same as my original post. 
I have uploaded new Diagnostics.

- **Diagnostics ID: 26624E28-712F-4563-B4F6-7768405E55A1/20220620004411**

### Output of & "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check
```
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[FAIL] DD0005: is the user in the docker-users group? The specified domain either does not exist or could not be contacted.
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[FAIL] DD0012: is the VM networking working? network checks failed: failed to ping host: exit status 1
[2022-06-20T00:41:22.409642700Z][com.docker.diagnose.exe][I] ipc.NewClient: a4cfd38d-diagnose-network -> \\.\pipe\dockerDiagnosticd diagnosticsd
[common/pkg/diagkit/gather/diagnose.runIsVMNetworkingOK()
[       common/pkg/diagkit/gather/diagnose/network.go:34 +0xdd
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1b57960)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1b57960)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2?, 0x1b57960)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1b57960, 0xc00047d730)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0xcb00000012?, 0xc00047d730)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0x151cdc0?, 0xc0002df890)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x1b57f60, 0x1516760?, {0xc0002dfb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1cb
[main.checkCmd({0xc00006c3d0?, 0xc00006c3d0?, 0x4?}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:132 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:98 +0x27f
[2022-06-20T00:41:22.410186500Z][com.docker.diagnose.exe][I] (fb34b844) a4cfd38d-diagnose-network C->S diagnosticsd POST /check-network-connectivity: {"ips":["192.168.199.1","192.168.52.1","192.168.10.115","172.28.112.1","172.20.80.1"]}
[2022-06-20T00:41:22.958674500Z][com.docker.diagnose.exe][W] (fb34b844) a4cfd38d-diagnose-network C<-S 6b99ceac-diagnosticsd POST /check-network-connectivity (548.488ms): failed to ping host: exit status 1

[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 2 issues:

1 : The test: is the user in the docker-users group?
    Failed with: The specified domain either does not exist or could not be contacted.

The current user must be member of the docker-users group. Press the Win + R keys to open Run, type lusrmgr.msc into Run, followed by Enter to open Local Users and Groups.

2 : The test: is the VM networking working?
    Failed with: network checks failed: failed to ping host: exit status 1

VM seems to have a network connectivity issue. Please check your host firewall and anti-virus settings in case they are blocking the VM.
```

### Steps to reproduce the behavior
```
C:\>docker run -d -p 80:80 docker/getting-started
Unable to find image 'docker/getting-started:latest' locally
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": unable to connect to 3.86.127.18:443. Do you need an HTTP proxy?.
See 'docker run --help'.

C:\>docker pull python:3-slim
Error response from daemon: Get "https://registry-1.docker.io/v2/": unable to connect to 52.203.34.165:443. Do you need an HTTP proxy?
```

**Comment by lfthiang** [comment]
Update to **version 4.10.0 (82025)**. The issue persists. All details are the same as my original post.
**New Diagnostics ID:** 26624E28-712F-4563-B4F6-7768405E55A1/20220705015220

### Output of & "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check
```
C:\>"C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check
[2022-07-05T01:54:41.229917400Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[FAIL] DD0014: are the backend processes running? 1 error occurred:
        * vpnkit.exe is not running


[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[FAIL] DD0012: is the VM networking working? network checks failed: failed to ping host: exit status 1
[2022-07-05T01:54:54.808987700Z][com.docker.diagnose.exe][I] ipc.NewClient: b25fe5e7-diagnose-network -> \\.\pipe\dockerDiagnosticd diagnosticsd
[common/pkg/diagkit/gather/diagnose.runIsVMNetworkingOK()
[       common/pkg/diagkit/gather/diagnose/network.go:34 +0xd9
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x158f7e0)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x158f7e0)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2?, 0x158f7e0)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x158f7e0, 0xc00062d730)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0xcb00000012?, 0xc00062d730)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0xf44620?, 0xc00061f890)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x158fde0, 0xa5da297400000010?, {0xc00061fb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1cb
[main.checkCmd({0xc00008a230?, 0xc00008a230?, 0x4?}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:133 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:99 +0x288
[2022-07-05T01:54:54.809707400Z][com.docker.diagnose.exe][I] (c98a346b) b25fe5e7-diagnose-network C->S diagnosticsd POST /check-network-connectivity: {"ips":["192.168.199.1","192.168.52.1","10.110.129.214","172.19.208.1","172.28.0.1"]}
[2022-07-05T01:54:55.361148400Z][com.docker.diagnose.exe][W] (c98a346b) b25fe5e7-diagnose-network C<-S f0d41bec-diagnosticsd POST /check-network-connectivity (548.4627ms): failed to ping host: exit status 1

[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 2 issues:

1 : The test: are the backend processes running?
    Failed with: 1 error occurred:
        * vpnkit.exe is not running



Not all of the backend processes are running.

2 : The test: is the VM networking working?
    Failed with: network checks failed: failed to ping host: exit status 1

VM seems to have a network connectivity issue. Please check your host firewall and anti-virus settings in case they are blocking the VM.
```


### Steps to reproduce the behavior
```
C:\>docker run -d -p 80:80 docker/getting-started
Unable to find image 'docker/getting-started:latest' locally
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": unable to connect to 44.207.96.114:443. Do you need an HTTP proxy?.
See 'docker run --help
```

**Comment by iorabi** [comment]
@ lfthiang Thanks for keeping this issue alive. Our team is also facing the same problem with docker desktop

**Comment by lfthiang** [comment]
@iorabi

No problem. If possible, you may wish to upload your diagnostics data and post your diagnostic ID so that the Docker team has more data to troubleshoot.

How to upload diagnostics and get diagnostics ID: https://docs.docker.com/desktop/windows/troubleshoot/#diagnose-and-feedback

**Comment by lfthiang** [comment]
Update to **version 4.10.1 (82475)**. The issue persists. All details are the same as my original post.
New **Diagnostics ID**: 26624E28-712F-4563-B4F6-7768405E55A1/20220720054158

### Output of & "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check
```
C:\>"C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check
[2022-07-20T05:43:24.131410300Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[FAIL] DD0014: are the backend processes running? 1 error occurred:
        * vpnkit.exe is not running


[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[FAIL] DD0012: is the VM networking working? network checks failed: failed to ping host: exit status 1
[2022-07-20T05:43:39.788421800Z][com.docker.diagnose.exe][I] ipc.NewClient: 6821731a-diagnose-network -> \\.\pipe\dockerDiagnosticd diagnosticsd
[common/pkg/diagkit/gather/diagnose.runIsVMNetworkingOK()
[       common/pkg/diagkit/gather/diagnose/network.go:34 +0xd9
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x17ff7e0)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x17ff7e0)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2?, 0x17ff7e0)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x17ff7e0, 0xc00026f730)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0xcb00000012?, 0xc00026f730)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0x11b4620?, 0xc00061f890)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x17ffde0, 0xec?, {0xc00061fb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1cb
[main.checkCmd({0xc00008a230?, 0xc00008a230?, 0x4?}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:133 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:99 +0x288
[2022-07-20T05:43:39.788959700Z][com.docker.diagnose.exe][I] (907238d7) 6821731a-diagnose-network C->S diagnosticsd POST /check-network-connectivity: {"ips":["192.168.208.1","192.168.199.1","192.168.52.1","10.110.129.214","172.19.208.1"]}
[2022-07-20T05:43:40.336303500Z][com.docker.diagnose.exe][W] (907238d7) 6821731a-diagnose-network C<-S bf42488e-diagnosticsd POST /check-network-connectivity (547.3437ms): failed to ping host: exit status 1

[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 2 issues:

1 : The test: are the backend processes running?
    Failed with: 1 error occurred:
        * vpnkit.exe is not running



Not all of the backend processes are running.

2 : The test: is the VM networking working?
    Failed with: network checks failed: failed to ping host: exit status 1

VM seems to have a network connectivity issue. Please check your host firewall and anti-virus settings in case they are blocking the VM.
```

### Steps to reproduce the behavior
```
C:\>docker run -d -p 80:80 docker/getting-started
Unable to find image 'docker/getting-started:latest' locally
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": unable to connect to 44.194.5.25:443. Do you need an HTTP proxy?.
See 'docker run --help'.
```

### Additional tests done
Ref: https://forums.docker.com/t/docker-run-hello-world-get-https-registry-1-docker-io-v2-service-unavailable/122531/21?u=lfthiang
> dockerthrowaway123: This probably doesn’t apply to most of you, but we found that one of our clients had a DLP software solution (Forcepoint / Websense) that was causing this problem.

With reference to the above post in Docker forum, I have tried disabling Forcepoint, reinstall Docker, reboot but the problem still persists.

**Comment by lfthiang** [comment]
I have resorted to reformat and reinstall my laptop, then Docker Desktop 4.10.1 works.  That means it is not an issue with my company's security software, network, etc.

Pray hard that it continues to work for me. 

Leave this issue open as there are still others with the issue. Ref: https://forums.docker.com/t/docker-run-hello-world-get-https-registry-1-docker-io-v2-service-unavailable/122531/21?u=lfthiang

**Comment by HB9HIL** [comment]
I'm an amateur radio enthusiast. There is something called the HAMNET. It's a world wide network for radio amateurs. The IP Address range is within the Ampr Net (44.*.*.*)

I was running an VPN in my Router which prevented my system to ask 1.1.1.1 for the correct IP adress because it was wrong routed. Disabled the VPN and docker works fine. 

DNS of https://registry-1.docker.io/v2/
https://dnschecker.org/#A/registry-1.docker.io

For this is an IP Range Problem.  "https://registry-1.docker.io/v2/" is part of the AMPR Net which is used by some other organisations. And because IPv4 Adresses will be sold out some day we should never forget to implement IPv6 for the future in out networks :-D 

So here it was a VPN Problem. 

Check your VPN Configs.

**Comment by lfthiang** [comment]
Hi @HB9HIL,

Thanks for sharing your experience.

> I was running an VPN in my Router which prevented my system to ask 1.1.1.1 for the correct IP address because it was wrong routed. 

I had tried it on my corporate network and home network, and the problem persisted. 
* I do not any VPN on my home network.
* I'm not using 1.1.1.1 for DNS on my corporate network.

In my previous follow-up post, I had re-formatted my laptop and now it works on both networks mentioned. 

I left this issue open as there are follow ups on my post on docker forum for this issue; I.e. other folks with similar issue.
Ref: https://forums.docker.com/t/docker-run-hello-world-get-https-registry-1-docker-io-v2-service-unavailable/122531/21?u=lfthiang


Thanks again for your suggestion.

**Comment by sooryaprakash99** [comment]
Hi, I am using the latest version of docker desktop 4.11.1 in my Windows 10 laptop. I am also facing this error and not able to fix this issue. I have tried with older versions and with different networks. But I am always getting the same error.

Error response from daemon: Get "https://registry-1.docker.io/v2/": unable to connect to 3.215.51.67:443. Do you need an HTTP proxy?

**Comment by PeriklisICES** [comment]
Facing the same issue on Windows 2022 server with docker desktop.
None of the workarounds have had any effect whatsoever.
https://docker-pinata-support.s3.amazonaws.com/incoming/3/EEE9E7E0-4920-4698-8CFF-E35ACA84E7DE/20230117123232.zip
