### ISSUE TITLE
docker pull 'hangs' when using WSL2 on Windows 11

### ISSUE THREAD

**Issue by pvanberlo** [docker/for-win#12757]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BAF83B6D-C847-420C-99E4-F45E94CB2D1D/20220601070607

### Actual behavior

Using WSL2 integration, any attempt to pull images will result in an apparent "freeze". Deleting the .docker/config.json file resolves the issue. It is possible to break/CTRL-C out of the running docker process, but this further causes networking to not be available for a little while on the system. After some time things will resolve itself.

### Expected behavior

Docker pulls images successfully without delays.

### Information

  - Windows Version: Windows 11 21H2 (22000.708)
  - Docker Desktop Version:  4.8.2 (79419)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

Deleting config.json solves the issue, which would suggest it's potentially related to fetching credentials using 'desktop.exe'. Everything worked before, but in the mean time I've updated to the latest version of Docker Desktop, and a more recent (insider) version of Windows was installed as part of the Windows Insider "Release Preview" channel. Of course whenever Docker Desktop recreates config.json the issue occurs again.

I am unsure if this is a Docker issue or a Windows 11 issue!

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.

### Steps to reproduce the behavior

  1. Run (within Linux on WSL2) docker run hello-world
  2. Seemingly hangs forever if the hello-world image is not already available locally

**Comment by GuillaumeDeconinck** [comment]
I have the same issue, likely linked to https://github.com/docker/for-win/issues/10247

**Comment by sjohnsonaz** [comment]
I found a potential workaround.  In Docker Desktop:

* Go to **Settings**
* Expand **Resources**
* Select **WSL INTEGRATION**
* Ensure **Enable integration with my default WSL distro** is checked
* Toggle on any distros you are using

I did this and the build time significantly reduced.
