### ISSUE TITLE
Docker bind mount fails to propagate inotify events from the host to container

### ISSUE THREAD

**Issue by aguedeney** [docker/for-win#12766]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: No error was detected

### Actual behavior
I run a Linux container (Alpine Linux 3.16) on Docker for Windows:

The inotify file events CREATE, DELETE, and MODIFY does not propagate from host into container.

This works for Docker Linux distributions, and MacOS (although DELETE event is not working for MacOS see https://github.com/docker/for-win/issues/12766)

### Expected behavior
When changing files outside container (on the host) bind mount point, I expect CREATE, DELETE, and MODIFY events to propagate inside the container.

### Information

  - Windows Version: Windows 10 Pro latest (I always keep up-to-date)
  - Docker Desktop Version: 4.9.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Laptop - no virtualization for host.

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.
### Steps to reproduce the behavior

  1. ... Inside a simple linux container with a bind-mount, then run inotifywait -m <bind mount point>
  2. ... Now, outside the container, change directory to bind mount and create, modify, or delete a file
  3.

**Comment by nicks** [comment]
are you binding a folder from the wsl filesystem or the windows filesystem? This sounds a lot like this issue: https://github.com/microsoft/WSL/issues/4739

**Comment by aguedeney** [comment]
As noted: "WSL2 or Hyper-V backend? WSL2" in the issue.  I do believe it is the same, HOWEVER, I thought this was fixed with WSL2.  I mean it worked with WSL1.

**Comment by nicks** [comment]
Nope, it worked with WSL1, but the WSL team removed support for it in WSL2. 

My understanding is that when using WSL2, you should always move your files to the Linux filesystem. 

The WSL team has prioritized making the Linux filesystem in WSL2 really fast and robust. The downside is that if you try to use WSL2 with the Windows filesystem, the experience will be much slower and buggier. 

I think that's probably the right technical decision, since there's a good workaround to make the experience nice again (read: move your files to the Linux filesystem, as this comment points out: https://github.com/microsoft/WSL/issues/4739#issuecomment-571256769)
