### ISSUE TITLE
 Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp 54.144.118.70:443: connect: connection refused. See 'docker run --help'.

### ISSUE THREAD

**Issue by tushar087** [docker/for-win#12763]
- [ ] I have tried with the latest version of Docker Desktop : version used : 3.6.0
  - [x] I have tried disabling enabled experimental features : yes it is disabled
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
docker pull results in docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp 54.144.118.70:443: connect: connection refused.
### Expected behavior
Docker pull should result in pulling an image from dockerhub. It should not use a proxy when the checkbox for proxy is not enabled, ie not set to "Manual proxy configuration"
### Information

  - Windows Version: Window 10 Enterprise version 1809 OS build 17763.1098
  - Docker Desktop Version: 3.6.0
  - WSL2 or Hyper-V backend?  Hyper-V backend
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: on a standalone machine

### Steps to reproduce the behavior
Install Docker desktop with version mentioned.
Leave settings for proxy in docker as default, manual is not enabled.
Try to pull an image : docker run -d -p 80:80 docker/getting-started

Information : no proxy settings is done as proxy is not used for connecting with internet.

![image](https://user-images.githubusercontent.com/47808291/172232728-97151b21-047d-4913-9a1e-956d7cbbd0c0.png)

**Comment by jakesco** [comment]
I am also experiencing this issue. 

- [x] I have tried with the latest version of Docker Desktop : version used : 4.9.0 
- [x] I have tried disabling enabled experimental features
- [x] I have uploaded Diagnostics

Diagnostics ID: 5A252C79-37B1-4AE3-B9CD-971065D55A50/20220606193908

### Information

- Windows Version: Window 10 Enterprise Version 20H2 OS Build 19042.1706
- Docker Desktop Version: 4.9.0
- WSL2 or Hyper-V backend? WSL2
- Are you running inside a virtualized Windows e.g. on a cloud server or a VM: on a standalone machine

This is affecting all of our developer machines. It seems to have started after a recent windows 10 security update, but rolling back the security update hasn't fixed the issue. 

We experience the same issue with both the WSL2 and Hyper-V backend.

The output of the docker health check mentions a network connectivity issue related to anti-virus or firewall. We don't have a proxy and we've tried disabling all anti-virus and firewalls on the machine but are still experiencing the problem. 

I've tried a full re-install of both Docker Desktop and WSL. Our IT staff have also tried a fresh install on a new test machine but they run into the same issue. 

I have been able to get `docker-ce` running normally in Ubuntu 20.04 in WSL2 (outside of Docker Desktop). 

I'll also mention that we have had Docker Desktop running fine for several months prior to this. The connectivity issue started end of May.

**Comment by jelenaprodanovicfis** [comment]
@jakesco @tushar087 Did you manage to resolve this issue?

**Comment by tushar087** [comment]
No ,issue still open
