### ISSUE TITLE
PI CHAT ROOMS

### ISSUE THREAD

**Issue by SIFUNEILJOHN** [docker/for-win#12772]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by thaJeztah** [comment]
I suspect this was opened accidentally

**Comment by SIFUNEILJOHN** [comment]
Why's still not working? My chatroom is still muted?

**Comment by SIFUNEILJOHN** [comment]
Why is still muted my chatroom can you help me PICORE TEAM @nicksieger
