### ISSUE TITLE
Images view: Make columns resizable

### ISSUE THREAD

**Issue by TobiasWenzel** [docker/for-win#12777]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics

### Actual behavior

The columns in the Images table of the Docker Desktop UI are not resizable. This results in long image names/repositories being cut off, as can be seen in this example:

![image](https://user-images.githubusercontent.com/10582928/173307981-0b8b2466-eb99-4ba1-952f-5cbd7488b8dc.png)

The columns scale with the window, which can be maximized. But this is still not sufficient for the names of the Docker images which we create. They have a namespace prefix in them and basically all images in the table only show the namespace. There is no quick way to find out in a list of 20-30 images which row in the table is which image. This makes the Docker Images view completely useless for us.

### Expected behavior

Similar to the Containers table in the most recent Docker Desktop version 4.9.0, the columns in the Images table should also be resizable.

### Steps to reproduce the behavior

  1. Open the Docker Desktop UI and go to the Images view.
  2. Try to resize the columns of the Images table --> this is not possible.

**Comment by nicks** [comment]
thanks for reporting! Yes, I think updating this screen to use the new table component is on our roadmap.

**Comment by TobiasWenzel** [comment]
This was implemented in the meantime, thanks! 👍
