### ISSUE TITLE
Kubernetes stuck 'starting' after upgrade to 4.9.0

### ISSUE THREAD

**Issue by crowne** [docker/for-win#12781]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: DA69F136-1880-46C7-88EB-80FAF110A06D/20220616071511

### Actual behavior
After clicking the "Enable Kubernetes" checkbox, the status never gets past starting

### Expected behavior
I expect kubernetes to be installed and started.

### Information

  - Windows Version: Windows 10 version 21H2
  - Docker Desktop Version: 4.9.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[FAIL] DD0005: is the user in the docker-users group? The specified domain either does not exist or could not be contacted.
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: is the user in the docker-users group?
    Failed with: The specified domain either does not exist or could not be contacted.

The current user must be member of the docker-users group. Press the Win + R keys to open Run, type lusrmgr.msc into Run, followed by Enter to open Local Users and Groups.

... I checked the recommendation above, and my user is a member of the docker user group,
I don't know why the diagnostic tool produces this error.

### Steps to reproduce the behavior

  1. Uninstall docker
  2. Install docker desktop 4.9.0

I have also uninstalled and tried to go back to version 4.8.2
but I'm still not getting past the starting status.

**Comment by markdbuck** [comment]
Starting yesterday, I could not get k8s cluster to start successfully. After 10 minutes or so, the k8s status would turn red and i got an error that k8s failed to start. After uninstalling/reinstalling Docker 4.9.0, k8s would still not start. I uninstalled one more time. But this time before reinstalling, I deleted the C:\Users\MarkBuck\AppData\Local\Docker directory. I reinstalled Docker 4.9.0 and then was able to start k8s successfully. It might work for you.
One additional tidbit. I looked in the log.txt file in C:\Users\MarkBuck\AppData\Local\Docker and noticed that there was an expired certificate error when k8s tried to start. I think deleting the C:\Users\MarkBuck\AppData\Local\Docker forced the recreating of the certificate which may have been the key to successfully restarting k8s.

**Comment by crowne** [comment]
@markdbuck thanks, that gave me a hint.  
It seems like the cause of the problem which I was experiencing was due to my KUBECONFIG environment variable being set up for multiple cluster configs :  
KUBECONFIG=C:\Users\user.name\.kube\config;C:\Users\user.name\.kube\azdevtst.config;C:\Users\user.name\.kube\rketest.config

To get Kubernetes re-installed I had to delete/rename the .kube directory in my user home dir
and I also removed the environment variable KUBECONFIG

It seems like a bug with the install process which doesn't recognise multiple config files in environment variable.
