### ISSUE TITLE
Docker Desktop kept polling VM memory usage in the background, resulting in high CPU usage

### ISSUE THREAD

**Issue by garyng** [docker/for-win#12780]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: -

Seems like Docker Desktop kept calling `powershell` to get the VM memory usage:
![image](https://user-images.githubusercontent.com/4453664/173675749-dfd3f9ee-b1f4-4559-ba3c-260c38105b44.png)

![image](https://user-images.githubusercontent.com/4453664/173675812-9ffd6a55-4b98-4240-b6ee-0b3818d03fa5.png)

```
powershell "(Get-Counter -Counter \"\Hyper-V Dynamic Memory VM(DockerDesktopVM)\Average Pressure\", \"\Hyper-V Dynamic Memory VM(DockerDesktopVM)\Physical Memory\", \"\Hyper-V Hypervisor Virtual Processor(dockerdesktopvm:*)\% Guest Run Time\").CounterSamples.CookedValue"
```

This results in constant high CPU usage.

### Information
  - Windows Version: Windows 10 21H2 19044.1708
  - Docker Desktop Version: 4.9.0
  - WSL2 or Hyper-V backend?  HyperV
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: bare metal

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
-

### Steps to reproduce the behavior

1. Open Docker Desktop
2. Check CPU usage

**Comment by nicks** [comment]
Thanks for the report! We're investigating this.

**Comment by Abi79** [comment]
Hi @trungutt , I am not OP but I can confirm the fix worked on our side.

**Comment by maxcleme** [comment]
This issue has been fixed in latest release, please consider updating to latest version and give us your feedback!

[4.10.0 Release notes](https://docs.docker.com/desktop/release-notes/#docker-desktop-4100)
