### ISSUE TITLE
After updating Docker for Desktop, my WSL2 Distro no longer can find the docker command, despite integration with the distro is enabled and was working prior to updating.

### ISSUE THREAD

**Issue by IP14Y3RI** [docker/for-win#12783]
I have just updated to Docker Desktop 4.9.0 from Docker Desktop 4.8.*. 

I have followed [this](https://docs.docker.com/desktop/windows/wsl/) tutorial back when I was on 4.8.*, I could open my terminal, connect to the Ubuntu 20.04 distro and run docker commands such as `docker images` .

Now that I have updated to 4.9.0 (80466), and restarted my PC, I no longer can run docker commands through bash, despite having walked through the steps in the tutorial multiple times, having uninstalled and reinstalled Docker Desktop and having walked through the same steps yet another time. 

Under Settings > General, the checkbox 'Use the WSL2 Based Engine' is enabled. 
Under Settings>Resources>WSL Integration, the checkbox Enable Integration with my default distro is enabled.
Under the same tab, 'Enable integration with additional distros' slider is also turned on, and I tried turning it on/off again, restarting the docker client, and trying again. Nothing works. 

When I open powershell and run `wsl.exe -l -v` I get:
```
 wsl.exe -l -v
  NAME                   STATE           VERSION
* Ubuntu-20.04           Running         2
  docker-desktop         Running         2
  docker-desktop-data    Running         2
```
which implies I am indeed using WSL2 and not some other version.

I get the following error in bash: 
```
The command 'docker' could not be found in this WSL 2 distro.
We recommend to activate the WSL integration in Docker Desktop settings.

For details about using Docker Desktop with WSL 2, visit:

https://docs.docker.com/go/wsl2/
```
I havent changed anything that could have lead to this behaviour besides from updating the Docker client.

**Comment by emmanuelolvera** [comment]
Same problem, I got it working just by restarting the distro. Run this command on the distro terminal:

`cd /mnt/c/ && cmd.exe /c start "Rebooting WSL" cmd /c "timeout 5 && title "$WSL_DISTRO_NAME" && wsl -d $WSL_DISTRO_NAME" && wsl.exe --terminate $WSL_DISTRO_NAME`

**Comment by SturmB** [comment]
I'm running into a similar issue. Docker and WSL seem to work fine normally. However, if I shut down Docker Desktop to save on resources for a little while, then start it back up again, the "link" between it and WSL is never restored. `docker -v` in WSL returns "The command 'docker' could not be found in this WSL 2 distro. […]" I must do a complete reboot of my computer since even `wsl -t Ubuntu` in Powershell does _not_ terminate WSL.

**Comment by emmanuelolvera** [comment]
@SturmB try the command above to fully restart the WSL distro, this should be ran from within the distro not PS

**Comment by SturmB** [comment]
> @SturmB try the command above to fully restart the WSL distro, this should be ran from within the distro not PS

I did try that before posting and it didn't restart the distro. As it turns out, I had another, smaller Windows Terminal window hidden behind others that was keeping WSL alive. Oops. 😅
