### ISSUE TITLE
Docker Desktop doesnt start- starting, stopping, quit on GUI

### ISSUE THREAD

**Issue by sibay** [docker/for-win#12782]
- [ x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
After Installing Docker Desktop for win version 4.9 (80967)
Docker Desktop doesnt startup correctly, the GUI windows opens an displays this:
"Docker Desktop starting"
"Docker Desktop stopping"
"Docker Desktop quit"

After the "quit" the GUI window closes itself. Restarting doesn't help

### Expected behavior

Normal startup of docker.

### Information

  - Windows Version: Windows 10 Pro 21H2 Build 19044.1766
  - Docker Desktop Version: 4.9 (80967)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no, running on bare metal desktop.

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

Sorry, i deinstalled the version and replaced it with 4.8.2. ( i had to work)  No diagnose available.

### Steps to reproduce the behavior

  1. Update from 4.8.1 via update buttonto 4.9 
  2. "Blank screen" propblem occures: https://github.com/docker/for-win/issues/12759
  3. Install from here  https://desktop-stage.docker.com/win/main/amd64/80967/Docker%20Desktop%20Installer.exe
  4. Start Docker Desktop
  5. "starting, stopping, quit"

**Comment by ydjadii** [comment]
I'm facing the same issue on Windows 10, Docker Desktop 4.9.1 with WSL2 integration

**Comment by nimdasx** [comment]
same here, windows 11, docker desktop 4.9.1, wsl2

**Comment by FDeghy** [comment]
same, win 11 docker 4.9.1

**Comment by JiyongShi** [comment]
same, win 11 docker 4.9.1

**Comment by joundso** [comment]
Same here, Win10 21H2, docker 4.9.1. Only downgrading to `4.8.2` worked for me: https://docs.docker.com/desktop/release-notes/#docker-desktop-482 
Reinstalling WSL2, Hpyervisor, Docker and removing all Docker settings (`C:\Users\<user>\.docker`, `%appdata%\Docker Desktop` and `%appdata%\Docker`) did NOT work.

**Comment by sreid99** [comment]
I've had some success starting the latest Windows docker desktop (4.9.1)  using the method to fix a WSL / LxssManager "stopping" issue mentioned here : https://github.com/microsoft/WSL/issues/7096#issuecomment-1116166142.

**Comment by richard-hobbs** [comment]
I have the same problem as above  (sibay)
Docker Desktop Version: 4.9 (80967) wouldn't work at all

I reverted back to 4.8.2 (79419) which worked until I restarted/shut down my computer.
Windows 10 home
21H2 (OS Build 19044.1766)

Diagnostic ID

18A92A56-25FA-4A80-8590-913B92A6A5C2/20220623132207

**Comment by joundso** [comment]
Deinstalling Docker and selecting "Hyper-V" instead of the recommended "WSL" Backend during re-installation solved the problem for me. Even after restarting the computer, docker is working in the current version 4.9.1 now.

**Comment by derbengale** [comment]
The issue was not fixed yet.. Im facing the same problem

**Comment by draz1c** [comment]
> The issue was not fixed yet.. Im facing the same problem. I just remembered that between installation and now I did something that may caused the issue: From this guide (german) https://stadt-bremerhaven.de/windows-11-so-bekommt-man-mehr-gaming-performance/ I deactivated the Virtual Maschine Platform of Windows. Did this cause the issue? It may apply to others too.

That may be it, last day I was playing with a Virtual Machine on Virtualbox that needed to have Hyper-V and Virtual Machine Platform of Windows disabled. Once I finished, I re-enabled and restarted the computer (to have WSL2 working).

Now I wanted to use Docker and I was facing the same issue here, and `/mnt/wsl/docker-desktop/cli-tools/` was empty too so I downloaded Docker Desktop again and now It works.
