### ISSUE TITLE
Docker Windows Installation Hung

### ISSUE THREAD

**Issue by cnich123** [docker/for-win#1278]
### Expected behavior
Successful Docker installation
### Actual behavior
![image](https://user-images.githubusercontent.com/26116192/32336238-04536bc4-bfac-11e7-8cb8-f9aa1e05456e.png)
![image](https://user-images.githubusercontent.com/26116192/32336253-0ddc08c2-bfac-11e7-8fcd-0b5e387bb046.png)

### Information

I am not sure why the installation won't complete. I have tried both the stable and edge installations. Any ideas? Let me know what other information I can provide.

### Steps to reproduce the behavior

  1. Run installer

**Comment by jasonbivins** [comment]
Hi @cnich123 
What is your windows build number? - can you send me the results of the ``` winver ``` command?

**Comment by mutemule** [comment]
FWIW, I'm having exactly the same trouble on my system. `winver` tells me I'm on `Version 1709 (OS Build 16299.125)`.

Note that just before it starts removing, it *very* briefly shows `Rollbacking...` in the status at the top, then moves to `Removing files...`.

**Comment by mutemule** [comment]
This issue seems to be related to https://github.com/docker/for-win/issues/1417.

Poking around a bit more, I see that the installer starts the Docker service, which then immediately fails for some reason. From Event Log -> Windows Logs -> System:

> The Docker for Windows Service service terminated unexpectedly.  It has done this 1 time(s).

```
 <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
   <System>
    <Provider Name="Service Control Manager" Guid="{555908d1-a6d7-4695-8e1e-26931d2012f4}" EventSourceName="Service Control Manager" /> 
    <EventID Qualifiers="49152">7034</EventID> 
    <Version>0</Version> 
    <Level>2</Level> 
    <Task>0</Task> 
    <Opcode>0</Opcode> 
    <Keywords>0x8080000000000000</Keywords> 
    <TimeCreated SystemTime="2018-01-13T06:42:24.722038000Z" /> 
    <EventRecordID>10003</EventRecordID> 
    <Correlation /> 
    <Execution ProcessID="1008" ThreadID="15080" /> 
    <Channel>System</Channel> 
    <Computer>ComputerName</Computer> 
    <Security /> 
    </System>
   <EventData>
    <Data Name="param1">Docker for Windows Service</Data> 
    <Data Name="param2">1</Data> 
  
  <Binary>63006F006D002E0064006F0063006B00650072002E0073006500720076006900630065000000</Binary> 
  </EventData>
</Event>
```
