### ISSUE TITLE
Docker Desktop logs you out on re-launch and updates

### ISSUE THREAD

**Issue by NiklasBr** [docker/for-win#12793]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 1C242C51-1D24-4B67-9E9F-B6CD01EB2136/20220623085117

### Actual behavior

Most of the time when closing and re-opening the app, and all of the time when updating it the logged in status ("upgrade plan" and "sign in" buttons) reverts to the logged out status.

Imagine if you had to sign in to Slack or Outlook every time you launched those apps.

### Expected behavior

I should remain logged in every time the app launched or updated (baring something like AD changes or invalidated session from the Accounts Settings).

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
```powershell
PS C:\Users\nikbr> & "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[FAIL] DD0005: is the user in the docker-users group? The specified domain either does not exist or could not be contacted.
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: is the user in the docker-users group?
    Failed with: The specified domain either does not exist or could not be contacted.

The current user must be member of the docker-users group. Press the Win + R keys to open Run, type lusrmgr.msc into Run, followed by Enter to open Local Users and Groups.
```

### Steps to reproduce the behavior

  1. No Dockerfiles needed, just plain Docker Desktop.
  2. WSL2
  3. No virtualisation, just plain Windows 10 Pro on a PC.
  4. Be logged in with with a paid plan.
  5. Install an update, e.x. 4.8.0 to 4.8.1 or 4.9.0 to 4.9.1

**Comment by Adam-Al-Rahman** [comment]
When I updated the docker desktop to a v4.9.1 now whenever I start my device docker desktop launch itself and ask me to update again.

**Comment by Wnzebkhan** [comment]
Ever since updating to 4.9.x, the symbolic links in my WSL2 distro are broken every time I restart my pc, and I need to get lucky if I want to be able to use docker through the bash terminal.

**Comment by NiklasBr** [comment]
This issue is specificially about this part:

**Comment by Adam-Al-Rahman** [comment]
> This issue is specifically about this part: ![image](https://user-images.githubusercontent.com/279826/175502591-9aa4644d-1826-45a6-b7cc-6fe838982ec2.png)

It is the same issue that I'm facing.

**Comment by NiklasBr** [comment]
Currently on v4..11.1 and this is still an issue.

**Comment by MihaelaStoica** [comment]
Closing as duplicate of https://github.com/docker/for-win/issues/12745
