### ISSUE TITLE
Not able to switch to windows containers...docker menu item on Windows Home 10 build 19044

### ISSUE THREAD

**Issue by vinodkca** [docker/for-win#12790]
- [x ] I have tried with the latest version of Docker Desktop 4.9.1
  - [x ] I have tried disabling enabled experimental features
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 87BBBEC1-14F4-42F4-8DFE-CE936AD6A8B0/20220622043414 

### Actual behavior
I am able to run linux containers on win home 10 . I did turn on these windows features after i enabled Containers, Hyper-V and Windows System for linux

I am able to start Docker and see linux container but i am not able to switch to windows containers by right on menu item for docker on taskbar.  I even tried .\dockercli.exe --SwitchDaemon but when i run docker version it only show linux/amd64 and not windows/amd64 

### Expected behavior
Right click on docker item on task bar and clicking menu item s**witch to windows containers should change to windows** even though it is windows home 10 because I have enabled windows features Containers and Hyper-V on my computer.
power shell when you run **docker version**
should show my server to be windows.amd64 after the container has switched.

### Information
I did turn on these windows features after i enabled Containers, Hyper-V and Windows System for linux on **WINDOWS Home 10** Version 21H2

**Comment by StefanScherer** [comment]
Windows 10 Home does not have the Containers feature. I'm going to close this issue.

**Comment by vinodkca** [comment]
Hi Stefan,
That is incorrect. U can install Containers on Win Home  through bach file.
-Vinod

**Comment by vinodkca** [comment]
Hi Stefan,
That is incorrect. U can install Containers on Win Home  through batch
file.Docker for windows claims it works for all version of window home. I
installed Containers and i can see on my Windows features.
From
Vinod ,California USA
