### ISSUE TITLE
Windows 11 with WSL2 default distro - on computer startup Docker stops and quits

### ISSUE THREAD

**Issue by 01011011** [docker/for-win#12794]
We have been facing this issue from last week and with the latest version of Docker 4.9.1 where every time computer is restarted Docker fails to start.  We need to restart multiple times docker, and eventually it starts, while many times it does not.

After it starts, we run the diagnostics and there are no issues with the docker.
![docker-stopped](https://user-images.githubusercontent.com/20220724/174670694-dc7d5112-fdc1-422a-a36f-1f667e92bfbb.png)
![docker-starting](https://user-images.githubusercontent.com/20220724/174671480-317f22b5-daf0-4f9c-8dee-6e6c12b06839.png)
![docker-stopping](https://user-images.githubusercontent.com/20220724/174671504-85f049fe-aad6-486b-ac33-5313e2319f63.png)

![docker-quit](https://user-images.githubusercontent.com/20220724/174670701-ab8f51b8-5641-4400-ac67-c7a4bd774dae.png)

It never starts the first time.  After I start it second or sometimes third time, it works.

This has been happening with the latest build.

**Comment by 01011011** [comment]
awesome, thanks.  Please let me know if there is a bug already reported and what is the tracking on it.

**Comment by StefanScherer** [comment]
@01011011 I've shared a link to an internal build here: https://github.com/docker/for-win/issues/12784#issuecomment-1165519134

Seems it improves the situation, but not fully fixes it. You could give it a try and give feedback. Thank you.

**Comment by gabrielsoldani** [comment]
I've had the same issue for a week now. As a workaround, deleting `%AppData%\Docker\settings.json` fixes it, but it happens again next time the Docker Engine is restarted.
