### ISSUE TITLE
No images displayed in Docker Desktop GUI. using CLI can still display

### ISSUE THREAD

**Issue by 50Death** [docker/for-win#12801]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
No images displayed in Docker Desktop GUI
![image](https://user-images.githubusercontent.com/30155715/176080938-30460416-53bb-441b-b01b-0ff88836a190.png)

Latest Version：
![image](https://user-images.githubusercontent.com/30155715/176082119-6c6c3f09-ba9d-48e3-97f2-d0f0b1532d29.png)

### Expected behavior
displayed every images, easy to organize
### Information

  - Windows Version: **Windows 10 21H1**
  - Docker Desktop Version: **tried 4.8.1(78998) and 4.9.1 (81317)**
  - WSL2 or Hyper-V backend?  **WSL2**
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: **NO**

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
```cmd
PS C:\Program Files\Docker\Docker\resources> .\com.docker.diagnose.exe check
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.
```
### Steps to reproduce the behavior
1. just open Docker Desktop GUI
2. I can't see any images displayed in GUI
3. but I can still see them in console output.
![image](https://user-images.githubusercontent.com/30155715/176080938-30460416-53bb-441b-b01b-0ff88836a190.png)

![image](https://user-images.githubusercontent.com/30155715/176081023-b316eab0-484d-4b44-ae6c-dc44b59170d8.png)

**Comment by xiaoxinw** [comment]
I have the same issue here, and it can not even start right now

**Comment by xiaoxinw** [comment]
> I have the same issue here, and it can not even start right now

I have to restart my laptop, then it seems working right now, you can try to restart yours.

**Comment by trungutt** [comment]
We're trying to address this issue in next release

**Comment by trungutt** [comment]
Could you please confirm that the issue still persists with 4.10.0?

**Comment by 50Death** [comment]
Still persists. I update to 4.10.0, it didn't fixed. Then I reboot my PC, still can not see any images.

![image](https://user-images.githubusercontent.com/30155715/177130856-8e13e96e-0a1f-4a7f-b2a0-6cbc7ee46975.png)
![image](https://user-images.githubusercontent.com/30155715/177130967-660138de-5fb5-4fc0-ba8d-7086d6f42e83.png)

Diagnostics:
```powershell
PS C:\Program Files\Docker\Docker\resources> .\com.docker.diagnose.exe check
[2022-07-04T10:55:12.534814300Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[FAIL] DD0014: are the backend processes running? 1 error occurred:
        * vpnkit.exe is not running


[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
segment 2022/07/04 18:55:17 INFO: response 401 401 authenticationrequired – <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

...(ellipsis 401 response of my company's HTTP proxy, I can access to internet)

</html>
segment 2022/07/04 18:55:17 ERROR: 1 messages dropped because they failed to be sent and the client was closed

Please investigate the following 1 issue:

1 : The test: are the backend processes running?
    Failed with: 1 error occurred:
        * vpnkit.exe is not running



Not all of the backend processes are running.
```

I‘m not quite sure what `vpnkit.exe` do, so I tried to run a container with `-p 8635:8635` param. The container worked fine.

Maybe I should remove the data and make a full reinstallation.

**Comment by foxydevloper** [comment]
Same issue is happening for me. This happened ever since I changed the `data-root` field in `C:\ProgramData\Docker\daemon.json`, and I haven't seen any images in Docker Desktop since. Even after I deleted the `daemon.json` file
