### ISSUE TITLE
Market Place and Extension Not available or showing

### ISSUE THREAD

**Issue by Equinox07** [docker/for-win#12808]
### Actual behavior
I update my Docker Desktop to v4.9.1
Instead of Docker Desktop starting, it displays Docker Desktop stopping.
After a couple to Docker Desktop restart, it started running.
The Market Place and Extension also fails to load as it loads usually on the Sidebar.

### Expected behavior
Docker Desktop to start running normally after update
The Market Place to load with the extensions I have installed.

### Information
  - Windows Version: 21H2
  - Docker Desktop Version: Docker Desktop 4.9.1 (81317)
  - WSL2 or Hyper-V backend?  Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

**Comment by trungutt** [comment]
Would you mind upload a diagnostic and a screenshot?

**Comment by benja-M-1** [comment]
Thank you very much @Equinox07 for reporting this! Closing and reopening the dashboard should fix the issue.

@trungutt I reproduced it with the mac version as well. I will have a look later today.

**Comment by benja-M-1** [comment]
This issue is similar to https://github.com/docker/extensions-sdk/issues/193.

The issue should be resolved since Docker Desktop 4.12. I am closing it.
