### ISSUE TITLE
Standalone LCOW daemon instructions from blog post don't work

### ISSUE THREAD

**Issue by jonstelly** [docker/for-win#1280]
### Expected behavior
Follow [these blog instructions](https://blog.docker.com/2017/09/preview-linux-containers-on-windows/), should start a new LCOW dockerd process that's able to run linux images

### Actual behavior
New dockerd process still tries to pull windows images:

`docker -H "npipe:////./pipe//docker_lcow" pull busybox`

results in:

```
Using default tag: latest
latest: Pulling from library/busybox
no matching manifest for windows/amd64 in the manifest list entries
```

### Information

```
C:\windows\system32> docker -H "npipe:////./pipe//docker_lcow" version
Client:
 Version:      17.11.0-ce-rc2
 API version:  1.34
 Go version:   go1.8.4
 Git commit:   d7062e5
 Built:        Wed Nov  1 22:08:18 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.11.0-ce-rc2
 API version:  1.34 (minimum version 1.24)
 Go version:   go1.8.5
 Git commit:   d7062e5
 Built:        Wed Nov  1 22:18:42 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

```
C:\windows\system32> docker -H "npipe:////./pipe//docker_lcow" info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.11.0-ce-rc2
Storage Driver: windowsfilter (windows) lcow (linux)
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 12
Total Memory: 63.91GiB
Name: assemble
ID: 4AFH:YATG:SJID:5MEA:ALFW:VURV:UX5K:HDFR:P654:WXBP:Z2FT:ST6V
Docker Root Dir: C:\Code\docker\linuxkit
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 17
 System Time: 2017-11-03T12:38:32.3510999-05:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
### Steps to reproduce the behavior

Follow [these blog instructions](https://blog.docker.com/2017/09/preview-linux-containers-on-windows/).

I've tried this with both the dockerd.exe used in the blog article and the current docker for windows edge version (17.11.0-ce-rc2) and get the same results.

**Comment by friism** [comment]
I installing the Edge variant of Docker for Windows. The latest version has LCOW setup integrated out of the box

**Comment by jonstelly** [comment]
It does, but I'm trying to figure out if I can run LCOW on my Team City build agents and the Docker for Windows system-tray/interactive-user-logon dependency isn't going to work on build servers.

Is there something missing from the blog article?  Like needing to do something else besides setting the LCOW_SUPPORTED environment variable?

**Comment by rn** [comment]
@jonstelly there are still a number of LCOW related PRs on the moby/moby repositories and during this time it's a moving target. Since the blog post a PR got merged which requires another env variable to be set before the daemon is started. I'm using:
```
$env:LCOW_SUPPORTED=1
$env:LCOW_API_PLATFORM_IF_OMITTED="linux"
Remove-Item c:\lcow -Force -Recurse; mkdir c:\lcow
.\dockerd.exe -D --experimental --data-root c:\lcow
```

and then can just access it directly with `docker` without having to set the `-H` bit. This only works if this is the only docker daemon running.

Since this is a preview and still very much in flux I won't recommend using it for anything other than experimenting with it

**Comment by jonstelly** [comment]
Fantastic, thanks for the pointer and I'll try that out first thing Monday.  I appreciate that it's a moving target and experimental, it's just such a useful feature.  My hope is that I can use lcow and not need dedicate Linux boxes somewhere just for build purposes.

Thanks a ton.  I'll close this issue and try to add a comment on that blog after I test it out.

**Comment by thaJeztah** [comment]
@rn should the blog be updated to match the current state?

**Comment by rn** [comment]
@thaJeztah I have no idea how to do that and it's a moving target. I think @friism might know how to update...

**Comment by friism** [comment]
Updated: https://blog.docker.com/2017/09/preview-linux-containers-on-windows/

**Comment by thaJeztah** [comment]
Thanks! Let me close this issue then 👍
