### ISSUE TITLE
Docker Desktop 4.10.0 (82025) causes PyCharm 2022.1.3 "Launching skeleton generator" task stuck

### ISSUE THREAD

**Issue by ythuang** [docker/for-win#12805]
after updating to Docker Desktop 4.10.0 (82025), "Launching skeleton generator" task is stuck, 
reverting to 4.9.1 resolves the issue.
PYCharm version is 2022.1.3

  - [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
After launching pycharm project with docker base interpreter "launching skeleton generator" task is stuck forever
### Expected behavior
background task should complete successflly

### Information

  - Windows Version: Win10 21H2
  - Docker Desktop Version: 4.10.0 (82025)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[SKIP] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[FAIL] DD0014: are the backend processes running? 2 errors occurred:
	* com.docker.wsl-distro-proxy.exe is not running
	* vpnkit.exe is not running

[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: are the backend processes running?
    Failed with: 2 errors occurred:
	* com.docker.wsl-distro-proxy.exe is not running
	* vpnkit.exe is not running

Not all of the backend processes are running.

### Steps to reproduce the behavior

  1. Create a pycharm with docker based python interpreter
  2. launch pycharm, background task "Launching skeleton generator" is stuck

**Comment by jayemes** [comment]
same issue here, also the terminals created from the docker service don't accept input

**Comment by nicks** [comment]
Here's the issue in the pycharm issue tracker:
https://youtrack.jetbrains.com/issue/PY-55096/PY-stuck-at-Launching-Skeleton-Generator-macOS-Docker

Hard to say what the bug is without more info from the pycharm team about what's hanging exactly, might be an issue with their client code or might be some subtle undocumented interaction between the two.

**Comment by Opdoop** [comment]
Same problem, solved following @ckkz-it to downgrade Docker Desktop 4.9.1.

**Comment by adeegoda** [comment]
Yes I'm facing the same issue with the release 4.10.1 release and PyCharm 2022.1.4 (Professional Edition)

**Comment by jayemes** [comment]
This update fixed it for me:
PyCharm 2022.2 (Professional Edition)
Build #PY-222.3345.131, built on July 27, 2022

**Comment by nicks** [comment]
Thanks @jayemes ! Closing
