### ISSUE TITLE
ARG variables set after the first FROM are subsequently ignored

### ISSUE THREAD

**Issue by rbairwell** [docker/for-win#12815]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID:
    Pre-upgrade (4.9.1) : B1188D61-075A-4A58-ABAC-8FBE89C64CF2/20220703150229
   Post-upgrade (4.10.,0): B1188D61-075A-4A58-ABAC-8FBE89C64CF2/20220703154641

### Actual behavior
Docker build fails to build [multi-stage build](https://docs.docker.com/develop/develop-images/multistage-build/) image when either the provider or image name in the second or subsequent FROM statement is a ARG variable.

```
PS > docker build --no-cache --progress=plain -f Dockerfile .
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM debian:bullseye-slim AS firstimage
 ---> abc589ebc613
Step 2/3 : ARG SECOND_IMAGE="latest"
 ---> Running in 9846749d0872
Removing intermediate container 9846749d0872
 ---> e7557fa8d22d
Step 3/3 : FROM alpine:${SECOND_IMAGE}
invalid reference format
```

### Expected behavior
Docker to build both images as detailed in the Dockerfile.

I can build the image from the attached Docker file if I either:

- Remove the comment from line 2 making it just `ARG SECOND_IMAGE="latest"` (the fact the second ARG remains "active" doesn't matter - it is totally ignored, even if it has a different value set)
- Change line 6 so instead of using the ARG, the image name is "hardcoded" - but this causes problems in my build process.

#### Windows Version

**PS > systeminfo /fo csv | ConvertFrom-Csv | select OS\*,Hotfix\*,Hyper\* | Format-List**
```
OS Name              : Microsoft Windows 10 Pro
OS Version           : 10.0.19044 N/A Build 19044
OS Manufacturer      : Microsoft Corporation
OS Configuration     : Standalone Workstation
OS Build Type        : Multiprocessor Free
Hotfix(s)            : 13 Hotfix(s) Installed.,[01]: KB5013887,[02]: KB5000736,[03]: KB5003791,[04]: KB5014666,[05]: KB5006753,[06]: KB5007273,[07]: KB5009636,[08]:    
                       KB5011352,[09]: KB5011651,[10]: KB5014032,[11]: KB5014035,[12]: KB5014671,[13]: KB5005699
Hyper-V Requirements : A hypervisor has been detected. Features required for Hyper-V will not be displayed.
```

#### Docker Desktop Version:

**PS > docker -v**
`Docker version 20.10.17, build 100c701`

**Docker Desktop version (from UI)**
`Docker Desktop 4.10.0 (82025)`

(Also experienced problem on:
**PS > docker -v**
`Docker version 20.10.16, build aa7e414`

**Docker Desktop version (from UI)**
`Docker Desktop 4.9.1 (81317) `
)
#### WSL or Hyper-V backend?
WSL:

**PS > wsl --status**
```
Default Distribution: Alpine
Default Version: 2

Windows Subsystem for Linux was last updated on 26/03/2022
WSL automatic updates are on.

Kernel version: 5.10.102.1
```

**PS >  wsl -l -v**
```
  NAME                   STATE           VERSION
* Alpine                 Running         2
  docker-desktop-data    Running         2
  docker-desktop         Running         2
```

#### Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

No:. Standard Win10 Pro Desktop machine

#### Is it reproducible?
Yes, 100%

#### Is the problem new?
It's existed for at least, to my knowledge and experience, in 2 Docker Desktop releases so far - but looking at https://github.com/docker/for-win/issues/12685 , it may have been since April 2022.

#### Did the problem appear with an update?
No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
**PS > & "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check**
```

[2022-07-03T23:31:18.705348300Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[FAIL] DD0014: are the backend processes running? 1 error occurred:
        * vpnkit.exe is not running


[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[FAIL] DD0032: do Docker networks overlap with host IPs? network bridge has subnet 172.17.0.0/16 which overlaps with host IP 172.17.0.1
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 2 issues:

1 : The test: do Docker networks overlap with host IPs?
    Failed with: network bridge has subnet 172.17.0.0/16 which overlaps with host IP 172.17.0.1

If the subnet used by a Docker network overlaps with an IP used by the host, then containers
won't be able to contact the overlapping IP addresses.

Please try configuring the IP address range used by networks: in your docker-compose.yml.
See https://docs.docker.com/compose/compose-file/compose-file-v2/#ipv4_address-ipv6_address

2 : The test: are the backend processes running?
    Failed with: 1 error occurred:
        * vpnkit.exe is not running
```

### Steps to reproduce the behavior

```yaml
# Dockerfile
#ARG SECOND_IMAGE="latest"
FROM debian:bullseye-slim AS firstimage

ARG SECOND_IMAGE="latest"
FROM alpine:${SECOND_IMAGE}
```

Then in either Powershell 7.2.5, Command Prompt or even "git bash":

`docker build --no-cache --progress=plain -f Dockerfile `
results in the error.

**Comment by rbairwell** [comment]
My mistake - I believe this is documented here: https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact

> ....
> FROM instructions support variables that are declared by any ARG instructions that occur before the first FROM.
> ...

**Comment by maltalex** [comment]
> It's existed for at least, to my knowledge and experience, in 2 Docker Desktop releases so far - but looking at https://github.com/docker/for-win/issues/12685 , it may have been since April 2022.

Would just like to point out that unlike this issue, #12685 uses a second `ARG` command after the `FROM` which should work according to the documentation:

> An ARG declared before a FROM is outside of a build stage, so it can’t be used in any instruction after a FROM. **To use the default value of an ARG declared before the first FROM use an ARG instruction without a value inside of a build stage**
