### ISSUE TITLE
Why latest version docker desktop has old version docker compose? How to update docker compose?

### ISSUE THREAD

**Issue by Kalinin-Andrey** [docker/for-win#12814]
Docker Desktop current release notes:
![image](https://user-images.githubusercontent.com/8151806/177052883-cdd00f3d-af72-48cf-838d-62fce0509d8b.png)

I just updated the version of docker desktop, but docker compose is still old?
![image](https://user-images.githubusercontent.com/8151806/177052970-f059fbfc-ffd1-43bb-b0a1-cbb7ed43e266.png)

How to update docker compose?

**Comment by trungutt** [comment]
Hi @Kalinin-Andrey could you please check that your settings uses compose v2?

<img width="779" alt="Compose" src="https://user-images.githubusercontent.com/18528548/177273762-3382083a-7b74-48db-929a-f0eae201fdb3.png">

**Comment by Kalinin-Andrey** [comment]
Hi, @trungutt,
yes, please:
![image](https://user-images.githubusercontent.com/8151806/177603570-5de1b1e8-4e8b-4cd5-a87d-199f1de059e0.png)

**Comment by Kalinin-Andrey** [comment]
Just now, Docker Desctop reported that new updates are available. Composer has been updated in this last update. I have a problem removed, but it is strange that she was.

![image](https://user-images.githubusercontent.com/8151806/177603965-a426e3ff-337e-49fa-b990-8fbfe17514de.png)

In any case, thanks!

**Comment by trungutt** [comment]
yes it's weird. I close the ticket, feel free to reopen it again in case the issue happens again
