### ISSUE TITLE
Horizontal resizing of Docker Desktop for Windows broken with most recent version v4.10.0 (82025)

### ISSUE THREAD

**Issue by Mnikley** [docker/for-win#12816]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics

### Actual behavior
Horizontal resizing of GUI does not work below a certain window height after upgrading to the most recent version using WSL 2 backend

### Expected behavior
Window should resize

### Information
Introduced after upgrading to most recent version v4.10.0 (82025) 

  - Windows Version: Windows 11 Version 21H2
  - Docker Desktop Version: 4.10.0 (82025)
  - WSL2 or Hyper-V backend?  WSL 2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Open Docker Desktop for Windows
  2. Try to horizontally resize the windows by clicking anywhere below the horizontal rule after "Dev Environments" on the left side, or by clicking anywhere below the header of the container items on the right side

**Comment by nicks** [comment]
Thanks for reporting! This is on our radar. We need to resolve some versioning issues with the underlying windows windowing library we use.

**Comment by 7af03dec0b** [comment]
It is not possible to resize the application window by grabbing the edge of the window (vertical or horizontal), maximizing the window by double-clicking on the header does not work. The only way to resize the application window is by grabbing the corner of the window and maximizing the window using the header icon. 
This is not a major bug, but it would be nice if the application respected the operating system's windowing convention.

**Comment by gavin-timbrell** [comment]
We've just released [Docker Desktop 4.11.0](https://docs.docker.com/desktop/release-notes/#docker-desktop-4110) which includes a fix for this.
