### ISSUE TITLE
[UPDATER] Updater text is not accurate, show 4.9.1 but update to latest (4.10.1 today)

### ISSUE THREAD

**Issue by tebeco** [docker/for-win#12822]
- [x] I have tried with the latest version of Docker Desktop
  that cannot be done because it's the updater itself
- [x] I have tried disabling enabled experimental features
  that is not related to experimental features but the updater
- [x] I have uploaded Diagnostics
  - Diagnostics ID: `01A048BE-946F-4977-BF59-D435FEA6B778/20220706095837`

### Actual behavior

Factory Reset: still the same
Clicking `Update` does download and install 4.10.1

![image](https://user-images.githubusercontent.com/2266487/177524329-7618dccd-0ba2-46f0-9b61-0b58c90b951e.png)
![image](https://user-images.githubusercontent.com/2266487/177526965-0ffc01f4-6846-47b9-b200-867f3aea8b3e.png)

### Expected behavior
The UI should re-check and invalidate it cache.

### Information
I had 4.8.1 installed and did not update to 4.9.x due to known bugs
Just restarted today and it's still hinting at 4.9.x instead of 4.10.x
### Information
  - Is it reproducible?
    - hard to tell (see at the end)
  - Is the problem new?
    - probably not / hard to tell
  - Did the problem appear with an update?
    - probably with all update
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.
    - it's about the installer itself
  - Windows Version: `Microsoft Windows [Version 10.0.25151.1010]`
  - Docker Desktop Version: `4.8.2 (79419)`
  - WSL2 or Hyper-V backend?  `wsl 2`
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
```
❯ & "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.
```

### Steps to reproduce the behavior
* install docker 4.8.1
* make it detect and maybe download 4.9.1 locally
* close it
* release 4.10.x later
* re-run docker desktop
* it still say it want to install 4.9.1
* if you click `Update` it will install 4.10.1

**Comment by stephen-turner** [comment]
Hmmm, I think this is because of the way we roll out updates gradually, so that if there are any serious bugs we haven't caught in our own testing, we can stop the deployment before it reaches too many people. Whereas if you go to the web page, you will just see the latest. But something is still wrong because it's offering you 4.9.1 but actually downloaded 4.10.1, so the logic seems to be inconsistent.

**Comment by tebeco** [comment]
> But something is still wrong because it's offering you 4.9.1 but actually downloaded 4.10.1, so the logic seems to be inconsistent

yea that's exactly what i tried to described

I'm pretty sure i had 4.9.0 or 4.9.1 detected and maybe even downloaded, but not installed weeks ago

that version is probably cached locally and not invalidated locally

**Comment by andrei-z-albu** [comment]
Closing this issue as a fix has been pushed with the new release of Docker Desktop 4.12.0. See [release notes](https://docs.docker.com/desktop/release-notes/) for more details.

**Comment by EbrahimAnesi** [comment]
g
