### ISSUE TITLE
docker-compose search doesn't work

### ISSUE THREAD

**Issue by wodyjowski** [docker/for-win#12828]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

When running compose with more that one container search doesn't filter containers grouped by compose.
For example if I input "test" and container with that name exists inside compose - application will show me grouping with every container (even those with completly different name).
If I input "xxx" and there is no container named that way - application won't show me any containers.

![image](https://user-images.githubusercontent.com/22776798/177995980-0e03a7d8-0d95-4b93-bc22-9e3a6f8afb11.png)
![image](https://user-images.githubusercontent.com/22776798/177996010-fd162c9c-afff-44c2-8241-22242f272bf5.png)
![image](https://user-images.githubusercontent.com/22776798/177996035-8a6da176-6a33-4e6b-9712-1a70953ad703.png)

### Expected behavior

I should be albe to filter containers inside compose (it worked that way before you slightly changed list design recently).

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[FAIL] DD0005: is the user in the docker-users group? Nie można odnaleźć nazwy użytkownika.
[PASS] DD0007: is the backend responding?
[FAIL] DD0014: are the backend processes running? 1 error occurred:
        * vpnkit.exe is not running

[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 2 issues:

1 : The test: is the user in the docker-users group?
    Failed with: Nie można odnaleźć nazwy użytkownika.

The current user must be member of the docker-users group. Press the Win + R keys to open Run, type lusrmgr.msc into Run, followed by Enter to open Local Users and Groups.

2 : The test: are the backend processes running?
    Failed with: 1 error occurred:
        * vpnkit.exe is not running

Not all of the backend processes are running.

### Steps to reproduce the behavior

  1. Start docker-compose with more that one container.
  2. Input name of one of containers from compose into search field
  3. Container list won't be filterd

**Comment by wodyjowski** [comment]
I just wanted to mention that my company pays for the license but I'm not allowed to send you this amount of diagnostic data.

**Comment by nicks** [comment]
Thanks for reporting! We're currently investigating some improvements for the container search. We agree that the way it interacts with compose isn't quite right currently.

**Comment by trungutt** [comment]
Hi @wodyjowski could you please try out this custom build to see if the problem still persists?

https://desktop-stage.docker.com/win/main/amd64/83190/Docker%20Desktop%20Installer.exe

Thanks in advance

**Comment by gavin-timbrell** [comment]
We've just released [Docker Desktop 4.11.0](https://docs.docker.com/desktop/release-notes/#docker-desktop-4110) which includes a fix for this.
