### ISSUE TITLE
Docker desktop can't start without deleting settings.json

### ISSUE THREAD

**Issue by zidanlastone** [docker/for-win#12820]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 7E8548BC-687D-44EC-972A-5F659B5DBC7C/20220706020616

### Actual behavior
 Docker can't start without deleting settings.json
### Expected behavior
 Docker desktop start can start without deleting settings.json and can start on startup
 
### Information

  - Docker Desktop Version: 4.9.0 (80466)
    Sha1: aa788ca27351e444d97c65939647a173078b4086
    Started on: 2022/07/06 01:30:54.591
    Resources: C:\Program Files\Docker\Docker\resources 
    OS: Windows 10 Pro
    Edition: Professional
    Id: 2009
    Build: 19044
  - WSL2 or Hyper-V backend? WSL2  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no
  

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

1 : The test: is the native API responding?
    Failed with: failed to ping tray application with error: Get "http://ipc/ping": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
    
  [2022-07-06T01:47:00.992885900Z][com.docker.diagnose.exe][I] ipc.NewClient: abb1f226-diagnose -> \\.\pipe\dockerBackendNativeApiServer CSharpAPI
[common/pkg/gui.NewClientForPath({0x10e3a8d?, 0xc00009f890?}, {0xc00009f8c0?, 0x11f3010?})
[       common/pkg/gui/client.go:60 +0x3d
[common/pkg/gui.NewClient({0x10e3a8d, 0x8})
[       common/pkg/gui/client.go:47 +0x5a
[common/pkg/diagkit/gather/diagnose.glob..func10()
[       common/pkg/diagkit/gather/diagnose/ipc.go:40 +0x25
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x16674e0)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x16674e0)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2?, 0x16674e0)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x16674e0, 0xc000357730)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0xcb00000012?, 0xc000357730)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0x102cdc0?, 0xc00035f890)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x1667f60, 0x1026760?, {0xc00035fb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1cb
[main.checkCmd({0xc0000403f0?, 0xc0000403f0?, 0x4?}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:132 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:98 +0x27f

**Comment by trungutt** [comment]
Hi @zidanlastone in case without `settings.json`, Docker Desktop will create a new `settings.json` on startup. Could you please make diff  between the old deleted one vs the newly created one? That will probably gives you some hint on the issue

**Comment by zidanlastone** [comment]
settings that causing docker cant start.
`{
  "acceptCanaryUpdates": false,
  "activeOrganizationName": "",
  "analyticsEnabled": true,
  "autoDownloadUpdates": false,
  "autoStart": false,
  "cpus": 2,
  "credentialHelper": "docker-credential-wincred.exe",
  "customWslDistroDir": "",
  "dataFolder": "C:\\ProgramData\\DockerDesktop\\vm-data",
  "deprecatedCgroupv1": false,
  "disableHardwareAcceleration": false,
  "disableTips": false,
  "disableUpdate": false,
  "diskSizeMiB": 65536,
  "diskTRIM": true,
  "displayRestartDialog": true,
  "displaySwitchWinLinContainers": true,
  "displayed18362Deprecation": false,
  "displayedElectronPopup": [],
  "displayedTutorial": true,
  "enableIntegrationWithDefaultWslDistro": true,
  "exposeDockerAPIOnTCP2375": false,
  "extensionsEnabled": true,
  "filesharingDirectories": [],
  "firstLaunchTime": 1657071906,
  "integratedWslDistros": [],
  "kubernetesEnabled": false,
  "kubernetesInitialInstallPerformed": false,
  "lastLoginDate": 0,
  "latestBannerKey": "",
  "licenseTermsVersion": 2,
  "lifecycleTimeoutSeconds": 600,
  "memoryMiB": 2048,
  "onlyMarketplaceExtensions": false,
  "openUIOnStartupDisabled": false,
  "overrideProxyExclude": "",
  "overrideProxyHttp": "",
  "overrideProxyHttps": "",
  "proxyHttpMode": "system",
  "settingsVersion": 17,
  "showExtensionsSystemContainers": false,
  "showKubernetesSystemContainers": false,
  "skipUpdateToWSLPrompt": true,
  "skipWSLMountPerfWarning": false,
  "socksProxyPort": 0,
  "swapMiB": 1024,
  "swarmFederationExplicitlyLoggedOut": false,
  "tipLastId": 27,
  "tipLastViewedTime": 1657072919460,
  "updateAvailableTime": 1657093533733,
  "updatePopupAppearanceTime": 0,
  "updateSkippedBuild": "",
  "useCredentialHelper": true,
  "useNightlyBuildUpdates": false,
  "useVirtualizationFramework": false,
  "useVirtualizationFrameworkVirtioFS": false,
  "useVpnkit": true,
  "useWindowsContainers": false,
  "vpnKitMaxPortIdleTime": 300,
  "vpnKitTransparentProxy": false,
  "vpnkitCIDR": "192.168.65.0/24",
  "wslEnableGrpcfuse": false,
  "wslEngineEnabled": true
}
`

newly created settings after deleting old one and open docker
`{
  "acceptCanaryUpdates": false,
  "activeOrganizationName": "",
  "analyticsEnabled": true,
  "autoDownloadUpdates": false,
  "autoStart": false,
  "cpus": 2,
  "credentialHelper": "docker-credential-wincred.exe",
  "customWslDistroDir": "",
  "dataFolder": "C:\\ProgramData\\DockerDesktop\\vm-data",
  "deprecatedCgroupv1": false,
  "disableHardwareAcceleration": false,
  "disableTips": false,
  "disableUpdate": false,
  "diskSizeMiB": 65536,
  "diskTRIM": true,
  "displayRestartDialog": true,
  "displaySwitchWinLinContainers": true,
  "displayed18362Deprecation": false,
  "displayedElectronPopup": [],
  "displayedTutorial": true,
  "enableIntegrationWithDefaultWslDistro": true,
  "exposeDockerAPIOnTCP2375": false,
  "extensionsEnabled": true,
  "filesharingDirectories": [],
  "firstLaunchTime": 1657296432,
  "integratedWslDistros": [],
  "kubernetesEnabled": false,
  "kubernetesInitialInstallPerformed": false,
  "lastLoginDate": 0,
  "latestBannerKey": "",
  "licenseTermsVersion": 2,
  "lifecycleTimeoutSeconds": 600,
  "memoryMiB": 2048,
  "onlyMarketplaceExtensions": false,
  "openUIOnStartupDisabled": false,
  "overrideProxyExclude": "",
  "overrideProxyHttp": "",
  "overrideProxyHttps": "",
  "proxyHttpMode": "system",
  "settingsVersion": 17,
  "showExtensionsSystemContainers": false,
  "showKubernetesSystemContainers": false,
  "skipUpdateToWSLPrompt": true,
  "skipWSLMountPerfWarning": false,
  "socksProxyPort": 0,
  "swapMiB": 1024,
  "swarmFederationExplicitlyLoggedOut": false,
  "tipLastId": 0,
  "tipLastViewedTime": 0,
  "updateAvailableTime": 0,
  "updatePopupAppearanceTime": 0,
  "updateSkippedBuild": "",
  "useCredentialHelper": true,
  "useNightlyBuildUpdates": false,
  "useVirtualizationFramework": false,
  "useVirtualizationFrameworkVirtioFS": false,
  "useVpnkit": true,
  "useWindowsContainers": false,
  "vpnKitMaxPortIdleTime": 300,
  "vpnKitTransparentProxy": false,
  "vpnkitCIDR": "192.168.65.0/24",
  "wslEnableGrpcfuse": false,
  "wslEngineEnabled": true
}
`

**Comment by zidanlastone** [comment]
there's no modification by myself. it's generated by docker. every I want to run docker, I need to delete the settings or change the show tips to true.

**Comment by siehienp20** [comment]
I am having a similar issue. Unless I delete the json and restart, Docker dekstop gets stuck on "Docker Engine Starting". The updater will not proceed past "Stopping VM and prepping update" for update 4.10.1 either. If I delete the json to update, the update crashes before fully installing
