### ISSUE TITLE
WORKDIR influences other Dockerfiles

### ISSUE THREAD

**Issue by AnnabellBrocker** [docker/for-win#12837]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Having two separated environments, named here env1 and env2:
env1: C:\Users\XXXX\Documents\YYYY\ZZZZ\DDDD
env2: C:\Users\XXXX\Documents\Docker\Ubuntu-20.04

In env1 I have a docker-compose.yml with 3 containers. In env2 I have a dockerfile.
The dockerfile from env2 includes the command `WORKDIR /home/jovyan/ABCD`. When building the image of env2 and starting the container, I get into the directory `/home/jovyan/ABCD` which is what to be intended.
Now when building all docker images in env1 via `docker-compose build` and starting all containers via `docker-compose up` and going into one of the the containers, I also get into the directory `/home/jovyan/ABCD` which should not happen as the command  `WORKDIR /home/jovyan/ABCD` is not related to this container.

### Expected behavior
WORKDIR should not influence other images/containers

### Information
  - Windows Version: Windows 10 Pro, Version 21H2
  - Docker Desktop Version: Docker Desktop 4.10.1, Docker Version 20.10.17
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Steps to reproduce the behavior
  1. In C:\Users\XXXX\Documents\Docker\Ubuntu-20.04:
    -  `docker build --tag ubuntu .`
    -  `docker run --name="ubuntu" --rm --interactive --tty  --publish 8888:8888 ubuntu`
    - Getting into directory `/home/jovyan/ABCD`
  2. In C:\Users\XXXX\Documents\YYYY\ZZZZ\DDDD:
    - `docker-compose build` => building 3 images
    - `docker-compose start` => starting 3 container, named now cont1, cont2, cont3
    - `docker exec -it cont1 /bin/bash  ` => Getting into directory `/home/jovyan/ABCD` (Not intended!!!)
    - `docker exec -it cont2 /bin/bash  ` =>Getting into default directory (Intended!!!)

**Comment by nicks** [comment]
:thinking: What does the Dockerfile for cont1 look like?

From the repro steps, my guess is that you're writing a new `ubuntu` image with workdir `/home/jovyan/ABCD`, and then building on top of that image in step (2). If that's the case, this is what I would expect to happen.

**Comment by nicks** [comment]
Yes, this is the behavior I would expect, because your cont1 dockerfile is building on the new image.

**Comment by AnnabellBrocker** [comment]
@nicks Could maybe explain me why it behaves like this.

Both are closed containers in themselves. If you build the image of env2 first and then that of env1, then env1 should not be influenced by env2 because it does not build on it. Or is the problem that I named env2 as ubuntu? Then it would make sense. So when renaiming env2 to something else than ubuntu, this should not happen again, right?
