### ISSUE TITLE
Can we have an option to minimize to the tray when minimized? 

### ISSUE THREAD

**Issue by U-4-E-A** [docker/for-win#12839]
Rather than only having the option to have it remain in the toolbar, can we have an option to hide it to the tray when minimized please? This would free up space in the toolbar. Thanks.

**Comment by trungutt** [comment]
Could you please be more explicit about the issue? A screen recording and steps to reproduce the problem would be really appreciated

**Comment by U-4-E-A** [comment]
Example using Microsoft Outlook: -
https://www.youtube.com/watch?v=pcXY4JcNapA&ab_channel=Excel%2CWordandPowerPointTutorialsfromHowtech

**Comment by U-4-E-A** [comment]
Is this not happening then?
