### ISSUE TITLE
Docker Desktop 4.10.1 - installation time is incredibly long

### ISSUE THREAD

**Issue by ThePlenkov** [docker/for-win#12835]
Hi! 

Did you change something in the installer? 

Installation time is enormously long. It literally installs 1 file per second

I'm quite confident - this is not because of my PC - as cpu, disk  and memory consumption stay normal 

It looks like Windows is trying to do something else on each file..

**Comment by siehienp20** [comment]
My installer is stuck on "Closing VM and Prepping Update"

**Comment by nicks** [comment]
Sorry to hear this. I haven't heard other reports of installs this slow, though we can leave this open for a bit to see if others chime in.

"1 file per second" triggers my spidey sense of "you have an anti-virus scanner that's misbehaving" (e.g., on every file, it's making some public request to the internet to see if that file could be a virus, and that request got slower for some reason).

**Comment by ThePlenkov** [comment]
that's what I thought about too.. But question is - did something changed in the installation - or is it definitely my OS issue =) I don't know yet - waiting for a next version update to see this again

**Comment by trungutt** [comment]
@ThePlenkov As far as I know, there's nothing changed in the installation recently. It's a bit hard to tell what's happening there, I also tried to install Docker Desktop on a slow Windows machine but couldn't have something like 1 file per second install. I close the issue, we're trying to release out a new version in a couple of days. Please feel free to open the issue again if it still persists with the new one
