### ISSUE TITLE
Docker always 'Failed to initialise' unless it was installed as Admin

### ISSUE THREAD

**Issue by easyTree** [docker/for-win#12831]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features -> none were enabled
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Docker always 'Failed to initialise' unless it was installed as Admin

### Expected behavior
Docker should behave correctly after installation regardless of whether the installer was run as Admin

### Information

  - Windows Version: 21H1 19043.1766
  - Docker Desktop Version: 4.10.1
  - WSL2 or Hyper-V backend?:  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
It's fixed/worked-around now so I've skipped this step.

### Steps to reproduce the behavior

  1. Download the installer for Windows
  2. Double-click to install
  3. After install, double-click the shortcut
  4. Witness the error dialog which appears immediately, much quicker than the standard UI generally appears.
  5. Uninstall
  6. Reboot
  7. Install as Admin
  8. Note that it now starts
  10. the end.

**Comment by trungutt** [comment]
Hi @easyTree thanks for reporting. I cannot reproduce that on my side. 

Please note that even if Docker Desktop doesn't start, you still have possibility to make a diagnostic from the terminal https://docs.docker.com/desktop/windows/troubleshoot/#diagnosing-from-the-terminal. Could you please do that for all your issues?

**Comment by easyTree** [comment]
I worked-around the problems - the diagnostic would not reflect the error situation as I've moved the ball forwards.
