### ISSUE TITLE
Docker Desktop 4.10.1 - Executing command and retrieving STDOUT/STDERR now fails

### ISSUE THREAD

**Issue by scott-parillo** [docker/for-win#12838]
Our current architecture leans on the Docker.DotNet library to execute commands within out functional tests and obtain the STDOUT/STDERR streams. We just updated Docker Desktop for Windows from 4.9.x to the latest 4.10.1 and 1 specific Docker.DotNet API that has been working since the beginning of the year is now failing.

Here's the actual logic in this API that now throws an exception:

https://github.com/stefanprodan/dockerdash/blob/master/src/Docker.DotNet/Microsoft.Net.Http.Client/HttpConnectionResponseContent.cs#L43

This issue is 100% reproducible on 4.10.1 but never fails on 4.5.x-4.9.x. We don't believe the problem is with the Docker.DotNet API _unless_ Docker has introduced a breaking change. Could somebody chime in?

Windows Version:
  - Docker Desktop Version: 4.10.1
  - WSL2 backend
  - Running from a physical Windows 10 workstation 21H2 (OS Build 19044.1806)

Message: 
System.InvalidOperationException : cannot hijack chunked or content length stream

  Stack Trace: 
HttpConnectionResponseContent.HijackStream()
<MakeRequestForHijackedStreamAsync>d__60.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
TaskAwaiter.ThrowForNonSuccess(Task task)
TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
<StartWithConfigContainerExecAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
TaskAwaiter.ThrowForNonSuccess(Task task)
TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
<StartAndAttachContainerExecAsync>d__7.MoveNext()
<11 more frames...>
TaskAwaiter.ThrowForNonSuccess(Task task)
TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
TaskAwaiter`1.GetResult()
GenericAdapter`1.BlockUntilCompleted()
NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
AsyncToSyncAdapter.Await(Func`1 invoke)
TestMethodCommand.RunTestMethod(TestExecutionContext context)
TestMethodCommand.Execute(TestExecutionContext context)
<>c__DisplayClass1_0.<Execute>b__0()

**Comment by nicks** [comment]
Thanks for reporting! Unfortunately, the stack trace and code pointer you gave us doesn't have any information about what Docker API you're calling. In fact, there's nothing here to suggest it's even making a Docker HTTP request, just that SOME HTTP request is failing.

Can you post a repro case with more details?

**Comment by BrunoJuchli** [comment]
Looks to me this might be caused by https://github.com/dotnet/Docker.DotNet/issues/554
