### ISSUE TITLE
WIndows 10 - Unable to launch Docker desktop

### ISSUE THREAD

**Issue by debasis-katalyst** [docker/for-win#12841]
- [X ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Does not bring any new window or User interface

### Expected behavior
I am waiting to get a toolbox

### Information
I have installed docker
PS C:\Users\debasisc> docker --version
Docker version 20.10.17, build 100c701
PS C:\Users\debasisc>

This means I should be able to run docker commands from Powershell.

But I am unable to launch the user interface from Windows Start command.
I find "Docker desktop", but nothing happens when I run that.

Is there anything different such as "Docker Toolbox" for Windows. Cannot seem to find that installation.

**Comment by imb4dm4n** [comment]
try this out: https://blog.csdn.net/cwg2552298/article/details/126171906?spm=1001.2014.3001.5502
