### ISSUE TITLE
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount257633285/Dockerfile: no such file or directory

### ISSUE THREAD

**Issue by tejasphadtare7193** [docker/for-win#12842]
- [ - ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

I have placed the Dockerfile in the right directory, also the name is right. Please find below screenshots.

<img width="946" alt="image" src="https://user-images.githubusercontent.com/103625721/179161546-2faa053f-8a6b-49ad-97fa-a6f5f35c107f.png">

VScode:

<img width="877" alt="image" src="https://user-images.githubusercontent.com/103625721/179161850-52a06be9-774d-4bb2-a3d7-5e2c8e110694.png">

**Comment by nicks** [comment]
🤔 sorry to hear you're having trouble. in your first screenshot, you're building the directory C:\Users\name\Recipe. In your second screenshot, your Dockerfile is in C:\Users\name\Recipe\recipe_api. 

I agree the error message is bad here, but it's telling you that there's no Dockerfile in `C:\Users\name\Recipe`. Did you intend to `docker build` from the recipe_api directory?

**Comment by WUTONK** [comment]
Obviously, this is a problem for win. I'm sorry to report the mac problem, but I also encountered a similar situation. The difference is that my terminal directory and dockerfile are the same, but I still have this problem
<img width="832" alt="截屏2022-09-07 23 45 05" src="https://user-images.githubusercontent.com/76605143/188921687-4f86540b-7739-4f5a-bdcd-75dcb4ffe7aa.png">

**Comment by WUTONK** [comment]
I tried to add `-f .docker` to the command to specify the docker build file, and this problem was solved ;)
