### ISSUE TITLE
Docker Desktop 4.10.1 destroyed my Windows 10 hosts 

### ISSUE THREAD

**Issue by hantsy** [docker/for-win#12847]
Windows 10, Docker Desktop 4.10.1.

When I upgraded to 4.10.1, I found some service(eg. Glassfish) does not work as expected on my laptop. After searching a lot of pages, I try to check the hosts file(C:\Windows\System32\drivers\etc\hosts).

```
# Added by Docker Desktop
192.168.18.158 host.docker.internal
192.168.18.158 gateway.docker.internal
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
```

My default hosts file was replaced with this, it is terrible. 

And it seems Docker Desktop will write this hosts when system is starting up.

**Comment by tcgunel** [comment]
same, also hosts file is now can't be edited as administrator.

**Comment by micdenny** [comment]
happened to me as well

![image](https://user-images.githubusercontent.com/1633595/189327881-b9bb3d5a-7bf8-4d7a-b22e-344638bb600d.png)

**Comment by somms** [comment]
This error happened again after updating to v4.11.1
