### ISSUE TITLE
Docker failed to initialize

### ISSUE THREAD

**Issue by Dikachi-Dev** [docker/for-win#12846]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version: Windows 10 version 21H2
  - Docker Desktop Version: 4.10.1.0
  - WSL2 or Hyper-V backend?  Hyper-V backend
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Run Docker after Installation 
  2. ...

**Comment by nicks** [comment]
Hi! This issue doesn't have enough information for us to investigate the problem, so I'm going to close for now.
