### ISSUE TITLE
Docker Feedback Dialog text overlaps

### ISSUE THREAD

**Issue by marklechtermann** [docker/for-win#1285]
### Expected behavior
Docker Feedback Dialog shown up.
### Actual behavior
Docker Feedback Dialog shown up, but the text overlaps.
(see Attachment)

![dockerfeedback](https://user-images.githubusercontent.com/17832679/32426349-13be983e-c2ba-11e7-9792-f636992794a5.png)

**Comment by jasonbivins** [comment]
Hi @marklechtermann   
We're using this thread to track the issue - so I'll go ahead and close yours as a duplicate.
You'll be able to follow it here: https://github.com/docker/for-win/issues/1277

Thanks for taking the time to report it!
