### ISSUE TITLE
Can't stop/remove docker-compose containers group when override file is in the same directory

### ISSUE THREAD

**Issue by dylanh724** [docker/for-win#12850]
- [x ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
False-positive error with incorrect information pops up, informing me that I cannot delete because the "directory name" [of docker desktop cli, itself] is invalid.

### Expected behavior
Container is deleted.

### Information
* This issue already exists as a 100% duplicate (but expired) of this post - see [](https://github.com/docker/for-win/issues/11445)
* Error: "Cannot remove Docker Compose application. Reason: fork/exec: C:\Program Files\Docker\Docker\resources\bin\docker.exe  The directory name is invalid."
  * I can copy+paste this in "RUN" and works np - it's a valid name using standard dev naming conventions.
  * I noticed that the path is \Docker\Docker, when it should actually be \docker\Docker (note the CaSe): If this is using wsl to get to the path, maybe this is the issue since bash is case sensitive?
  * I'm on Win11

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
"Please specify a command." 
Sorry, I'm out of time - this test request step is too vague to explore deeper.

### Steps to reproduce the behavior
See https://github.com/docker/for-win/issues/11445

**Comment by trungutt** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?

**Comment by dylanh724** [comment]
@trungutt Which info, specifically, are you seeking that you can't find between this ticket and https://github.com/docker/for-win/issues/11445 ?
