### ISSUE TITLE
The Docker DeskTop is crushed when i first start in windows.But it is good running next time.

### ISSUE THREAD

**Issue by 10-SH** [docker/for-win#12854]
### Information

  - Windows Version: Window 11 enterprise
  - Docker Desktop Version:  4.10.1 (82475)
  - WSL2 or Hyper-V backend?  : WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Windows application log

Application: Docker Desktop.exe
Framework version: v4.0.30319
Exception: System.UnauthorizedAccessException

Exception: Docker.Core.HttpBadResponseException
    Docker.Core.Logging.HttpClientExceptionInterceptor+<InterceptResponseAsync>d__0.MoveNext()
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    Docker.Core.IPC.Client+<SendAsync>d__5.MoveNext()
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    System.Net.Http.HttpClient+<FinishSendAsyncBuffered>d__58.MoveNext()
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    Docker.Core.BackendAPI.ServiceAPIClient+<UpdateHostsAsync>d__5.MoveNext()
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    Docker.Core.TaskExtension+<Forget>d__0.MoveNext()
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
    System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
    System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
    System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by zh199225** [comment]
I have the same problem, did you solve it?
Windows Version: Windows 10 x64 21H2 19044.1889
Docker Desktop Version: 4.11.1.0

**Comment by K2ouMais** [comment]
I am having the same behaviour for over a year.

The Docker team is doing nothing about this... It doesnt matter how many issues I open, I never got an answer.

https://github.com/docker/for-win/issues/12813

**Comment by K2ouMais** [comment]
This is still relevant 😭
