### ISSUE TITLE
Docker confusingly fails to work with some reserved file names during COPY

### ISSUE THREAD

**Issue by val-krylov** [docker/for-win#12867]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics

Problem:
Docker confusingly fails to work with some reserved file names during COPY while both Windows and Linux can work with them.

### Actual behavior

1. Create file `some_directory/NUL` in your build context.
2. Use `COPY some_directory /anywhere` in your `Dockerfile`.
3. Run `docker build .`

Result: `error from sender: GetFileInformationByHandle some_directory\NUL: Incorrect function.`

### Expected behavior

Just copy (or give correct error report).

### Information
  - Windows Version: Windows 10 [Version 10.0.19043.1826]
  - Docker Desktop Version: 4.10.1 (82475)
  - Engine: 20.10.17

### Steps to reproduce the behavior

Dockerfile:
1. Create file `some_directory/NUL` in your build context.
2. Create `Dockerfile`:
```
FROM scratch
COPY some_directory /somewhere
```
3. Run `docker build .`

### Also

Original `NUL` was created by `Makefile` bundled with Cosmos SDK. Hard-to-notice bug without any consequnces (until docker COPY).

**Comment by nicks** [comment]
Ahhhh I remember the first time I learned about this!

From: https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file

> Do not use the following reserved names for the name of a file:
>
> CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9.

i.e., this isn't really a Docker issue. Most Windows tools and APIs will cryptically break if you try to use `NUL` as a file name.

**Comment by nicks** [comment]
Oh, here's the great computer history explanation: https://devblogs.microsoft.com/oldnewthing/20031022-00/?p=42073

**Comment by val-krylov** [comment]
> i.e., this isn't really a Docker issue. Most Windows tools and APIs will cryptically break if you try to use `NUL` as a file name.

And anything that carefully works with current APIs will work just fine.

Anyway, being not able to copy such files MAY be ok (as I mentioned in issue). But messages like `Incorrect function` with `NUL` being appended to directory name are very misleading. They look like off-by-one bugs somewhere deep inside docker.
