### ISSUE TITLE
WSL2 documentation at https://docs.docker.com/desktop/windows/wsl/ needs to be updated

### ISSUE THREAD

**Issue by glerzing** [docker/for-win#12864]
### Obsolete prerequisite?
In the section Prerequisites, there is a line that suggests to Download and install the "Linux kernel update package" and points to the step 4 of Windows's WSL2 manual installation. 
It looks like most of the time, the command `wsl --install` (c.f. https://docs.microsoft.com/en-us/windows/wsl/install) should just be enough. The manual installation is just for "older build of Windows", and asking to make this step 4 of the manual installation, if not necessary, adds confusion.

### Obsolete screenshots
Here is a screenshot currently in https://docs.docker.com/desktop/windows/wsl/ :

![image](https://user-images.githubusercontent.com/47578089/180659488-1fc608c9-9729-45c5-975f-31e466576cac.png)

And here is a screenshot from my version :

![image](https://user-images.githubusercontent.com/47578089/180659547-01d2d4fc-5d53-424e-bb94-8e1bfc8198d4.png)

Since the option "Use the WSL 2 based engine (Windows Home can only run the WSL 2 backend)" looks now inevitable, the section "Install" might not be relevant anymore.

**Comment by nicks** [comment]
Hi! We appreciate the screenshots!

Many Docker users are on old versions of Windows, or on Windows Pro (which gives you a choice between WSL2 and Hyper-V). Yeah, there's always a struggle writing instructions that work for lots of user environments and screenshots will never capture every variant. So this is working as intended.
