### ISSUE TITLE
Solution for WGL2 == null

### ISSUE THREAD

**Issue by Kordedekehine** [docker/for-win#12860]
<!--
Go to your browser settings->systems->Use hardware acceleration when available. Relaunch the User hardware acceleration, then reboot your laptop, or better still restart the browser. Then re-open your docker app. Boom!! Its working

**Comment by trungutt** [comment]
Hi @Kordedekehine this is on our radar, a fix is in progress and will be in the next release

**Comment by Kordedekehine** [comment]
@trungutt weldone
