### ISSUE TITLE
Hidden launch to tray

### ISSUE THREAD

**Issue by XEGARE** [docker/for-win#12872]
Hello. This is not a bug. I would like to suggest a small improvement. In the settings add - hidden launch to tray. When I start the computer, I see the Containers window and I have to close it every time.

**Comment by trungutt** [comment]
You could start Docker Desktop without having the Containers window opened, by uncheck this option from Settings here

<img width="590" alt="Screen Shot 2022-07-29 at 2 45 28 PM" src="https://user-images.githubusercontent.com/18528548/181763608-99af12dd-df28-4795-9e73-96935a98e884.png">

**Comment by XEGARE** [comment]
> You could start Docker Desktop without having the Containers window opened, by uncheck this option from Settings here
> 
> <img alt="Screen Shot 2022-07-29 at 2 45 28 PM" width="590" src="https://user-images.githubusercontent.com/18528548/181763608-99af12dd-df28-4795-9e73-96935a98e884.png">

Really

Thanks!
