### ISSUE TITLE
Docker for Windows on virtualized Windows should use docker daemon on host machine

### ISSUE THREAD

**Issue by youfoundkris** [docker/for-win#1287]
### Expected behavior
When using Docker for Windows on a Windows virtual machine the Docker for Windows software should provide the option to use the docker installation of the host machine. It should not matter if that host machine is a Linux, Mac or Windows installation. 

### Actual behavior
It is not possible to configure Docker for Windows on the virtual machine to use the docker installation on the host machine.

### Information

N/A

### Steps to reproduce the behavior

N/A

**Comment by friism** [comment]
You can run Docker over HTTP/TCP, that way you can share access to Docker to a VM. Details here: https://docs.docker.com/engine/security/https/
