### ISSUE TITLE
windows 10 19044 build docker 4.11 wsl distros not imported

### ISSUE THREAD

**Issue by fpirim** [docker/for-win#12870]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

Docker desktop won't install wsl images. (docker-desktop & docker-desktop-data)

### Expected behavior

wsl -l -v (sub systems should be listed docker-desktop & docker-desktop-data)

### Information

  - Windows Version: 19044
  - Docker Desktop Version: 4.11
  - WSL2 or Hyper-V backend? WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. clean install Docker Desktop (deleting .docker, Local and Rooming Docker directories)
  2. waiting docker service initialize wsl 
  3. start docker-desktop
  4. com.docker.backend processes start over and over again

com.docker.backend.exe log content

![image](https://user-images.githubusercontent.com/7191354/181700911-802808fc-3010-498c-9e1d-aa8b48b94adc.png)

**Comment by nicks** [comment]
thanks for reporting. can you upload a diagnostics id?
https://docs.docker.com/desktop/troubleshoot/overview/#diagnose-from-the-terminal

```
C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe gather -upload
```
