### ISSUE TITLE
The "Install required Windows components for WSL 2" does not appear during installation.

### ISSUE THREAD

**Issue by Shin-ichi-Takayama** [docker/for-win#12884]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - I have not completed the installation.

### Actual behavior
`Install required Windows components for WSL 2` is not displayed during installation.

![キャプチャ](https://user-images.githubusercontent.com/104180422/183623697-0d26397c-9e20-4ab7-98da-178fc69498b0.PNG)

### Expected behavior
`Install required Windows components for WSL 2` is displayed during installation.
It was displayed on other desktop PCs. Same Windows and Docker for Desktop version.

### Information

  - Windows Version:Windows10 21H2
  - Docker Desktop Version:4.11.1
  - WSL2 or Hyper-V backend?:WSL2  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:No

**Comment by nicks** [comment]
I believe we just changed the wording here. "Use WSL 2" does the same thing.
