### ISSUE TITLE
Docker login fails with: Error saving credentials: error storing credentials - err: exit status 1, out: `error getting credentials - err: exit status 1, out: A specified logon session does not exist. It may already have been terminated.

### ISSUE THREAD

**Issue by cove** [docker/for-win#12888]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A2EEE9FB-BD78-46AA-8D75-EDA70D4B251F/20220810234244

Docker login command fails while trying to store credentials.

### Actual behavior

Run from a jenkins job:
```
docker run --rm -v C:\Users\build/.aws:/root/.aws -e AWS_DEFAULT_REGION -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY amazon/aws-cli ecr get-login-password | docker login --username AWS --password-stdin xx.dkr.ecr.us-east-1.amazonaws.com
Error saving credentials: error storing credentials - err: exit status 1, out: `error getting credentials - err: exit status 1, out: `A specified logon session does not exist. It may already have been terminated.``
```
### Expected behavior

When not run from Jenkins:
```
C:\J\ws\OS>docker run --rm -v C:\Users\build/.aws:/root/.aws -e AWS_DEFAULT_REGION -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY amazon/aws-cli ecr get-login-password | docker login --username AWS --password-stdin x.dkr.ecr.us-east-1.amazonaws.com
Login Succeeded
```

### Information
  - Problem is reproducible.
  - Not sure if it's new or now.
  - Not sure if it's related to an update.

 - Windows Version:  Microsoft Windows [Version 10.0.19044.1826]
 - Docker Desktop Version: v4.11.1
 - WSL2
 - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No, native hardware.

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

```
C:\J\ws\OS>"C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check
[2022-08-10T23:49:23.491783000Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[FAIL] DD0014: are the backend processes running? 1 error occurred:
        * vpnkit.exe is not running


[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: are the backend processes running?
    Failed with: 1 error occurred:
        * vpnkit.exe is not running

Not all of the backend processes are running.
```

### Steps to reproduce the behavior

  1. Create a Jenkins job to run a shell command
  2. Run the following command or any docker login command
```
  docker run --rm -v C:\Users\build/.aws:/root/.aws -e AWS_DEFAULT_REGION -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY amazon/aws-cli ecr get-login-password | docker login --username AWS --password-stdin x.dkr.ecr.us-east-1.amazonaws.com
```

Also this appears to be related:
https://github.com/docker/cli/issues/2682

**Comment by Quiketembleke** [comment]
C:\J\ws\OS>"C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check
[2022-08-10T23:49:23.491783000Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[FAIL] DD0014: are the backend processes running? 1 error occurred:
        * vpnkit.exe is not running


[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: are the backend processes running?
    Failed with: 1 error occurred:
        * vpnkit.exe is not running

Not all of the backend processes are running.

**Comment by cove** [comment]
This is a fresh install, what would a vpn service have to do with it?

**Comment by cove** [comment]
Replacing `wincred` with `ecr-login` it doesn't happen, so it's a bug in `wincred` it looks like since `ecr-login` doesn't have the same issue.

**Comment by nicks** [comment]
Sorry to hear you're having trouble.

AFAICT, this error message means that you have Docker Desktop configured to store passwords in the Windows native credential manager, but something about your Windows native credential manager is broken. Ya, switching to use ecr-login is a good workaround.

I'm going to close this because you have a good workaround. But long-term I do think Docker should do more here to help you resolve these kinds of "broken credential manager" issues.

**Comment by cove** [comment]
I don't believe this has anything to do with my specific setup, but is a bug in wincred. it's lame to leave the straightforward use case broken to even using the product, but ok I guess.

**Comment by Quiketembleke** [comment]
Perfecto, seguiré usando Enviado desde mi teléfono-------- Mensaje original --------De: cove ***@***.***>Fecha: vie., 12 ago. 2022 0:13Para: docker/for-win ***@***.***>Cc: Quiketembleke ***@***.***>, Comment ***@***.***>Asunto: Re: [docker/for-win] Docker login fails with: Error saving credentials: error storing credentials - err: exit status 1, out: `error getting credentials - err: exit status 1, out: A specified logon session does not exist. It may already have been terminated. (Issue #12888)
I don't believe this has anything to do with my specific setup, but is a bug in wincred. it's lame to leave the straightforward use case broken to even using the product, but ok I guess.
