### ISSUE TITLE
Docker Desktop 4.11.1 Failed to Install

### ISSUE THREAD

**Issue by rwilliams3088** [docker/for-win#12891]
- [x] I have tried with the latest version of Docker Desktop

### Actual behavior

When I attempt to install the latest version of Docker Desktop (4.11.1), the installation fails with the following error:

```
Component CommunityInstaller.EnableFeaturesAction failed: Not found 
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
```

![image](https://user-images.githubusercontent.com/106355404/184457081-77997e3a-d811-4190-ad42-afb7176284ef.png)

### Expected behavior
Docker Desktop installs and runs normally

### Information
My previous installation of Docker Desktop was refusing to come up and was getting some permissions error it looked like. I decided to go ahead and try a fresh install (running as admin) but now the installer is failing...

**Comment by Sjeiti** [comment]
Same happened today after a failed automatic update (don't remember what the original version was, not old). 

The automatic update silently failed and Docker was gone. Downloaded the installer for 4.11.1 and got the same error.
Installers for the previous versions 4.11.0, 4.10.1 and 4.5.1 are now giving the same errors. Guessing the failed update broke something.

**Comment by ERasheed21** [comment]
Has anyone been able to resolve this? Having the same issue.

**Comment by CyberCyclistMSN** [comment]
I am still having this issue and searching for a solution.  The powershell cmdlets mentioned above didn't work for me.

**Comment by CyberCyclistMSN** [comment]
This worked for me.  If fixes corrupted WMI repositories.

Put this script into a .bat file.  Run it as administrator.
Restart Windows
Reinstall Docker

echo on
cd /d c:\temp
if not exist %windir%\system32\wbem goto TryInstall
cd /d %windir%\system32\wbem
net stop winmgmt
winmgmt /kill
if exist Rep_bak rd Rep_bak /s /q
rename Repository Rep_bak
for %%i in (*.dll) do RegSvr32 -s %%i
for %%i in (*.exe) do call :FixSrv %%i
for %%i in (*.mof,$.mfl) do Mofcomp -s %%i
net start winmgmt
goto End

:FixSrv
if /I (%1) == (wbemcntl.exe) goto SkipSrv
if /I (%1) == (wbemtest.exe) goto SkipSrv
if /I (%1) == (mofcomp.exe) goto SkipSrv

:SkipSrv
goto End

:TryInstall
if not exist wmicore.exe goto End
wmicore /s
net start winmgmt

:End
