### ISSUE TITLE
INOTIFY Events not supported in WSL2 to improve performance ...

### ISSUE THREAD

**Issue by aguedeney** [docker/for-win#12898]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

See Docker bind mount fails to propagate inotify events from the host to container #12766

While I'm fine with Docker's decision to NOT SUPPORT INOTIFY events using WSL2 and opt'd for performance in filesystem.  It may render some linux tools useless when using a bind mount.  It maybe a future consideration.

Personally, I found a programmatic workaround to INOTIFY on Windows using a Linux container.

I want others to clearly note this is NOT supported using WSL2.

**Comment by nicks** [comment]
thanks for reporting! ya, I'm going to mark this as a duplicate. 

If you are interested in this feature, your best bet is to put a thumbs-up on the upstream WSL2 feature request (https://github.com/microsoft/WSL/issues/4739). As I noted on the https://github.com/docker/for-win/issues/12766, it's really more of a WSL2 issue.

**Comment by aguedeney** [comment]
Thanks for the reference @nicks
