### ISSUE TITLE
failed to deploy distro docker-desktop to c:\users\user\appdata\local\docker\wsl\distro: : error: 0xffffffff

### ISSUE THREAD

**Issue by rizkyhaksono** [docker/for-win#12892]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information
  - Windows Version: Windows 11
  - Docker Desktop Version: v.4.10.1
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Virtualized Windows

### Steps to reproduce the behavior

  1. Installed docker.
  2. And then restarted my laptop and suddenly get pop up like that. I tried everything but didn't work out.

**Comment by saber13812002** [comment]
> không liên kết với docker được

means: cant link to docker

ok please describe more about solution please

**Comment by donhuvy** [comment]
![image](https://user-images.githubusercontent.com/1328316/210910602-55b8e15d-a774-4000-a173-fa8a1832a1fb.png)
