### ISSUE TITLE
Unfortunate typos/layout in the feedback dialog

### ISSUE THREAD

**Issue by rfulwell** [docker/for-win#1289]
### Expected behavior
No typos
### Actual behavior
Poor formatting and a typo on the feedback dialog
### Information

  - Diagnostic ID: 3C4B2C56-F216-4110-B274-B83C25FE289F/2017-11-06_09-32-30
  - host distribution and version (Windows version, build number, etc)
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: false

### Steps to reproduce the behavior

  1. Use Docker enough to trip the feedback dialog
  2. Observe typo/layout in the dialog (see attached)
![dockertypo](https://user-images.githubusercontent.com/470472/32454837-402ef97a-c2d5-11e7-9660-3347e590100a.png)

**Comment by jasonbivins** [comment]
Hi @rfulwell    Thanks for pointing that out!
Here's the thread we're tracking the issue on - you'll be able to follow it there. I'll go ahead and close this one.
https://github.com/docker/for-win/issues/1277

Thanks!
