### ISSUE TITLE
docker desktop launch with .Net runtime error

### ISSUE THREAD

**Issue by zh199225** [docker/for-win#12900]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version: windows 10 x64 21H2, 19044.1889
  - Docker Desktop Version: 4.11.1
  - WSL2 backend
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

When I launchthe docker desktop application first time, the Dashboard window of the docker desktop will crash after a few seconds, and the process "docker desktop.exe" will crash. But, when I launch the docker desktop application again, it will work correctly. And if I reboot the system, or restart the "Docker Desktop Service", the problem will come up again. 

_Here the Windows Event:_

```
Log Name: Application
Source: .NET Runtime
Date: 2022/8/15 21:55:24
Event ID: 1026
Task Category: None
Level: Error
Keywords: Classic
User: N/A
Computer: LAPTOP-ASUS
Description:
Application: Docker Desktop.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.UnauthorizedAccessException

Exception Info: Docker.Core.HttpBadResponseException
at Docker.Core.Logging.HttpClientExceptionInterceptor+d__0.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
at Docker.Core.IPC.Client+d__5.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
at System.Net.Http.HttpClient+d__58.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
at Docker.Core.BackendAPI.ServiceAPIClient+d__5.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
at Docker.Core.TaskExtension+d__0.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
at System.Threading.ThreadPoolWorkQueue.Dispatch()

Log Name: Application
Source: Application Error
Date: 2022/8/15 21:55:25
Event ID: 1000
Task Category: (100)
Level: Error
Keywords: Classic
User: N/A
Computer: LAPTOP-ASUS
Description:
Faulting application name: Docker Desktop.exe, version: 4.11.1.0, time stamp: 0xd8bf3811
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1889, time stamp: 0xe9ede6d6
Exception code: 0xe0434352
Fault offset: 0x0000000000034fd9
Faulting process id: 0x4554
Faulting application start time: 0x01d8b0aea546a631
Faulting application path: C:\Program Files\Docker\Docker\Docker Desktop.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 81dc1484-093f-476c-9b5c-cb844c7a298f
Faulting package full name:
Faulting package-relative application ID:
```

https://user-images.githubusercontent.com/5519191/184903252-22fcce23-e694-4c12-b748-13890ab24a31.mp4

**Comment by rwilliams3088** [comment]
+1 Had the same thing happen to me. Then I tried to uninstall + reinstall - but now the install fails (https://github.com/docker/for-win/issues/12891)

**Comment by iGwkang** [comment]
应用程序: Docker Desktop.exe
Framework 版本: v4.0.30319
说明: 由于未经处理的异常，进程终止。
异常信息: System.UnauthorizedAccessException

异常信息: Docker.Core.HttpBadResponseException
   在 Docker.Core.Logging.HttpClientExceptionInterceptor+<InterceptResponseAsync>d__0.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   在 Docker.Core.IPC.Client+<SendAsync>d__5.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   在 System.Net.Http.HttpClient+<FinishSendAsyncBuffered>d__58.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   在 Docker.Core.BackendAPI.ServiceAPIClient+<UpdateHostsAsync>d__5.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   在 Docker.Core.TaskExtension+<Forget>d__0.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   在 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   在 System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   在 System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by iGwkang** [comment]
将 `Use the WSL 2 based engine` 取消勾选（系统要打开hyper-v），然后重启电脑。
重启电脑后将 `Use the WSL 2 based engine` 再次勾选。
重启电脑 不会出现崩溃了。
至少我是这么操作的

**Comment by zh199225** [comment]
> 将 `Use the WSL 2 based engine` 取消勾选（系统要打开hyper-v），然后重启电脑。 重启电脑后将 `Use the WSL 2 based engine` 再次勾选。 重启电脑 不会出现崩溃了。 至少我是这么操作的

我试了，还是不行。奇怪的是我另一台电脑，同样的系统同样的docker desktop，连装的软件都差不多，以前也这样，但有一天突然就没这个问题了。
麻烦你试一下重启docker desktop service服务后再启动docker desktop会不会崩溃呢。

**Comment by zh199225** [comment]
我试了，还是不行。奇怪的是我另一台电脑，同样的系统同样的docker desktop，连装的软件都差不多，以前也这样，但有一天突然就没这个问题了。
麻烦你试一下重启docker desktop service服务后再启动docker desktop会不会崩溃呢。

&nbsp;


　
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月24日(星期三) 下午5:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [docker/for-win] docker desktop launch with .Net runtime error (Issue #12900)





 
将 Use the WSL 2 based engine 取消勾选（系统要打开hyper-v），然后重启电脑。
 重启电脑后将 Use the WSL 2 based engine 再次勾选。
 重启电脑 不会出现崩溃了。
 至少我是这么操作的
