### ISSUE TITLE
Switch to Windows containers isn't visibile in the Docker context menu

### ISSUE THREAD

**Issue by NickGraham101** [docker/for-win#12912]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 451C3C2E-4BDA-4BBB-839B-2F69186A73B8/20220819091503

### Actual behavior
When I right click the Docker app in the Windows system tray the context menu doesn't list the `Switch to Windows containers` option.  This has previously been available to me on this machine.  I've reviewed the [System Requirements](https://docs.docker.com/desktop/install/windows-install/) and am running Windows 10 Pro 21H2 build 19044.1889 with Containers and Hyper-V features enabled.

![image](https://user-images.githubusercontent.com/34914709/185588378-2fbfa84e-17e4-4362-aa14-60a35e3b6f0e.png)

### Expected behavior
The `Switch to Windows containers` option is available in the context menu.

### Information

  - Windows Version: Windows 10 Pro 21H2 build 19044.1889
  - Docker Desktop Version: 4.11.1
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Right click Docker in system tray, `Switch to Windows containers` isn't visible

**Comment by nbowes24** [comment]
I'm also missing this after a recent update.

Information
Windows Version: Windows 10 Pro 21H2 build 19044.1766
Docker Desktop Version: 4.11.1
WSL2 or Hyper-V backend? Hyper-V
Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Yes

Diagnostics ID: D55368F1-122D-4F67-908C-8136260733D8/20220819104430

**Comment by nicks** [comment]
Thanks for reporting. I checked your diagnostic ID, and it seems like your DD is having trouble loading settings. I'm going to file a bug internally to investigate. If you restart docker desktop, does the menu item appear?

**Comment by NickGraham101** [comment]
Thanks for the response @nicks. I've restarted DD and quit and reopened it a few times with no luck.  I've also restarted my laptop several times since reporting the issue and still can't see the menu item.

**Comment by Cinorid** [comment]
I also have this problem, for me this problem is usually solved by restarting DD a few times.

**Comment by Cinorid** [comment]
It seems that this problem has been solved in version 4.12.0

**Comment by NickGraham101** [comment]
Upgrading to 4.12.0 fixed this for me as well
