### ISSUE TITLE
Windows 10 "C:\Program Files\Docker\Docker\resources\com.docker.backend.exe" handles growth

### ISSUE THREAD

**Issue by jrobbins-LiveData** [docker/for-win#12916]
- [ x] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 21B93265-B0F7-436B-94B1-5819A587337D/20220820000156

### Actual behavior
OS Name	Microsoft Windows 10 Pro
Version	10.0.19044 Build 19044

According to taskmanager, this process `"C:\Program Files\Docker\Docker\resources\com.docker.backend.exe" -addr unix:\\.\pipe\dockerBackendApiServer -native-api` is leaking OS handles on my PC at a rate of approximately 50,000 handles a day, despite doing very little with Docker.  In fact, the handles count increments even when I am doing nothing with Docker.
### Expected behavior

I'd expect the OS handles count to ebb and flow with activity, but reach some sort of stable high water mark.

### Information

  - Windows Version: OS Name	Microsoft Windows 10 Pro Version	10.0.19044 Build 19044
  - Docker Desktop Version: Docker Desktop 4.11.1 (84025) is currently the newest version available.
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:  No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
[2022-08-20T00:17:53.164550600Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[FAIL] DD0014: are the backend processes running? 1 error occurred:
        * vpnkit.exe is not running

[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: are the backend processes running?
    Failed with: 1 error occurred:
        * vpnkit.exe is not running

Not all of the backend processes are running.

### Steps to reproduce the behavior
Simply running `"C:\Program Files\Docker\Docker\resources\com.docker.backend.exe"` without running any Docker jobs is enough to see the OS handles count grow in taskmanager.

**Comment by dlmcpaul** [comment]
I have noticed the same issue.

Using https://github.com/randomascii/blogstuff/tree/main/FindZombieHandles you can see lots of zombie processes taking up thousands of handles.

The main System process eventually spends a lot of time trying to process these handles.

**Comment by mwm-twx** [comment]
I've seen this recently as well. Sysinternals RAMMap shows thousands of `wsl.exe` processes which each have a 36K page table and ballooned my page table total to more than 5G. `wsl.exe --shutdown` was unable to cull those `wsl.exe` processes, but restarting Docker Desktop did clear them out. I restarted last week, so this buildup is happening fairly quickly.

**Comment by CorrodedCoder** [comment]
Also have just seen com.docker.backend.exe handle leak continuously increasing until Windows 10 operating system performance was impacted, as stated above (count had reached 170,000 handles for that one process).

**Comment by hernandp** [comment]
I confirm this.  Analyzed using WinDbg memory dump. Over 40K Handles on my system, causes NTOSKRNL!KeBalanceSetManager to be called repeatedly due to memory pressure,   system performance impacted. 

Twitted over this https://twitter.com/indiocolifa/status/1568215828822196225

**Comment by nicks** [comment]
does the problem persist if you upgrade to Docker Desktop v4.12? This sounds a lot like - https://github.com/docker/for-win/issues/12877

**Comment by CorrodedCoder** [comment]
Will give it a try - apologies I didn't realise there was an update available.

**Comment by dlmcpaul** [comment]
Yes it looks like the docker backend is no longer leaking handles with 4.12
