### ISSUE TITLE
DockerDeskopVM errors

### ISSUE THREAD

**Issue by GeorgeS2019** [docker/for-win#12919]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

Windows 11
Docker Windows v4.11.1
  
Within Hyper-V Manager, connect **DockerDesktopVM**:

![vmconnect_AaO2xZI9ph](https://user-images.githubusercontent.com/49812372/185752820-fca2a1b1-e022-4178-9fb1-b5aa5d96d153.gif)

Output of & "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check

![image](https://user-images.githubusercontent.com/49812372/185753099-013cd373-7aae-4f3c-b1e9-5ceb317206e4.png)

![Docker_Desktop_u1eCbkWslD](https://user-images.githubusercontent.com/49812372/185753232-d1c5d0c0-cf7e-4117-acb0-7c350272c6ba.gif)

**Comment by avbentem** [comment]
You left a link to this issue to https://forums.docker.com/t/cant-get-past-docker-for-mac-needs-privileged-access-to-install-its-networking-components-and-links-to-the-docker-apps/42518 but lacking any description there, that one did not make it through review. Also, as this very GitHub issue just says "Solved" I've no idea what you were trying to say.

**Comment by GeorgeS2019** [comment]
It seems my Windows 11 has an inappropriate conflicting user account. Once I address that, the problem is gone.
