### ISSUE TITLE
Docker hv-sock proxy (vsudd) is not reachable

### ISSUE THREAD

**Issue by 13lt** [docker/for-win#1292]
### Docker on Esxi

hi i cant run linux conteriner there is some error, here log file
[log.txt](https://github.com/docker/for-win/files/1449183/log.txt)

please help me,   Windows Containers working properly, but Linux containers can't

**Comment by jasonbivins** [comment]
Hi @13lt   
Since you're on the 1709 build of Windows, you might be able to take advantage of the new LCOW functionality for your Linux containers

![image](https://user-images.githubusercontent.com/28021664/32525259-96e634e6-c3f1-11e7-86f6-0b3708916ada.png)

**Comment by 13lt** [comment]
i have Version 17.09.0-ce-win33 (13620)  - stable version, 

there is no that functionality, 

i don't want use Edge Version in prodaction, is there any other way?

**Comment by xvladxtremal** [comment]
Try delete KB4048955 update, in my case, it solved.

**Comment by dzivkovi** [comment]
Thank you for helping me fix the problem after Windows 10 update tonight! Someone should let the Microsoft know their last update prevents Docker from starting correctly....

**Comment by 13lt** [comment]
i install Cleanup 1709 Version Windows, there is no any installed update, but there is same error again

**Comment by xvladxtremal** [comment]
Again does not work for me. No updates were installed, only a reboot.

**Comment by ctmcisco** [comment]
For anyone following this ticket:

Try the following:

1. Switch or stay on Windows Containers.
2. Disable the "Start when Windows starts" setting.


![image](https://user-images.githubusercontent.com/14852041/37053107-e9a96bd8-2140-11e8-9bdf-b264980b6127.png)

3. Exit Docker application
4. restart docker services via PowerShell

get-service *docker* | Restart-Service -Force -Verbose

5. Launch Docker , Run as Admin
6. Swtich to Linux Containers.

TEST:

Reboot Windows 10
Launch Docker 
Does it work?

You can also parse the docker log in PowerShell for troubleshooting:

cat C:\Users\USERPROFILE\AppData\Local\Docker\log.txt -tail 10 -wait

**Comment by rn** [comment]
@13lt we do not support running Docker for Windows in a Windows VM. See https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-for-windows-in-nested-virtualization-scenarios
