### ISSUE TITLE
Unable to sign after update

### ISSUE THREAD

**Issue by Misiu** [docker/for-win#12927]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
After updating the Docker desktop from 4.7.0 (77141) to 4.11.1 (84025), I cannot sign to the Docker desktop.
I get this error:

> Post "https://login.docker.com/oauth/token": proxyconnect tcp: dial tcp 127.0.0.1:8888: connectex: No connection could be made because the target machine actively refused it.

### Expected behavior

After the update, I should be able to sign in without problems.

### Information

  - Windows Version: 10
  - Docker Desktop Version: 4.11.1 (84025)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

[2022-08-23T09:40:05.506950800Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[FAIL] DD0014: are the backend processes running? 1 error occurred:
        * vpnkit.exe is not running

[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: are the backend processes running?
    Failed with: 1 error occurred:
        * vpnkit.exe is not running

Not all of the backend processes are running.

but when I run powershell command `Get-Process "*vpnkit*"`
I get this list:
![image](https://user-images.githubusercontent.com/1741838/186126500-b34c6f4e-8145-4d96-a06a-d05f308bf91d.png)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jazdw** [comment]
I've been trying to figure out a Docker issue and it seems like everyone (and myself also) gets "vpnkit.exe is not running", have a look through the issues.

**Comment by Misiu** [comment]
I'm still on 4.7.0 (77141) because of this issue.

**Comment by Misiu** [comment]
why this is closed?
/remove-lifecycle stale

**Comment by Misiu** [comment]
Update:
I uninstalled the previous version and did a standard install of the new version (4.15.0 (93002)) and I didn't have to log in to my docker account (I was already logged in), so for now, everything works.
