### ISSUE TITLE
Copying Docker Desktop logs converts space character to non-breaking space

### ISSUE THREAD

**Issue by jacrosby** [docker/for-win#12922]
- [ x] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

Copying logs from "Copy to Clipboard" button in Docker Desktop converts the space character (Hex 0x20) to non breaking space (Hex 0xc2 0xa0). This means SQL statements (for example), copied from the logs don't work anymore if there are spaces in a field name.

### Expected behavior

Space characters should be retained as space characters and not converted to non breaking spaces.

### Information

To reproduce, , and . 

  - Windows Version: 10
  - Docker Desktop Version: 4.11.1
  - WSL2 or Hyper-V backend?  WSL 2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Copy logs from Docker Desktop to a text editor, e.g. Notepad++ 
  2. Select "Show All Characters"
  3. It will become apparent that the space character is not a "normal" space character

**Comment by joe0BAB** [comment]
Hi @jacrosby! Thanks for reporting this. I can reproduce the issue and created an internal ticket. Hope to come back to you soon about this.

**Comment by joe0BAB** [comment]
@jacrosby would you mind re-testing with latest 4.12 release? It should fix the issue.

**Comment by jonathon-avant** [comment]
Thanks for the fix, it worked!

**Comment by joe0BAB** [comment]
Great! Thanks for confirming!
