### ISSUE TITLE
Docker installation failed on Windows 10 x64bits

### ISSUE THREAD

**Issue by khadija-kaimous** [docker/for-win#12920]
I cannot install the Docker Desktop Installer.exe file on my system Windows 10x64bit 8Go

    Component CommunityInstaller.EnableFeaturesAction failed: Non trouvé 
           à CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
        --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
           à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           à CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()

I tried many solutions but still don't know the reason

**Comment by CyberCyclistMSN** [comment]
I am having this exact same issue and have been trying to find a solution.  I'll post if I find a solution and keep checking to see if anyone else has.

**Comment by CyberCyclistMSN** [comment]
This worked for me.  If fixes corrupted WMI repositories.

Put this script into a .bat file.  Run it as administrator.
Restart Windows
Reinstall Docker

echo on
cd /d c:\temp
if not exist %windir%\system32\wbem goto TryInstall
cd /d %windir%\system32\wbem
net stop winmgmt
winmgmt /kill
if exist Rep_bak rd Rep_bak /s /q
rename Repository Rep_bak
for %%i in (*.dll) do RegSvr32 -s %%i
for %%i in (*.exe) do call :FixSrv %%i
for %%i in (*.mof,$.mfl) do Mofcomp -s %%i
net start winmgmt
goto End

:FixSrv
if /I (%1) == (wbemcntl.exe) goto SkipSrv
if /I (%1) == (wbemtest.exe) goto SkipSrv
if /I (%1) == (mofcomp.exe) goto SkipSrv

:SkipSrv
goto End

:TryInstall
if not exist wmicore.exe goto End
wmicore /s
net start winmgmt

:End
