### ISSUE TITLE
With Docker Desktop 4.11.1 for Windows kubernetes does no longer start

### ISSUE THREAD

**Issue by pmayweg** [docker/for-win#12925]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E2553B2C-DA32-4AE0-B249-8CB3931E1524/20220822125808

### Actual behavior
Kubernetes would start

### Expected behavior
Kubernetes does not start. Removed the Kubernetes configuration, rebooted, still does not start.

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible? yes
  - Is the problem new? yes
  - Did the problem appear with an update? I think 4.11.1
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.
  Just plain docker has this problem.
  Removing the kubernetes, reboot and adding did not help. I see 6 containers running, k8s_etcd_etcd-docker-desktop_kube-system, k8s_kube-scheduler_kube-scheduler-docker-desktop_kube-system, k8s_POD_etcd-docker-desktop_kube-system, k8s_POD_kube-scheduler-docker-desktop_kube-system,k8s_POD_kube-controller-manager-docker-desktop_kube-system and k8s_POD_kube-apiserver-docker-desktop_kube-system
  - Windows Version: 10 21H2 August patch level
  - Docker Desktop Version: 4.11.1
  - WSL2 or Hyper-V backend?  WSL
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
[2022-08-22T13:09:22.979852000Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[FAIL] DD0014: are the backend processes running? 1 error occurred:
        * vpnkit.exe is not running

[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: are the backend processes running?
    Failed with: 1 error occurred:
        * vpnkit.exe is not running

Not all of the backend processes are running.

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by AndrewCushing** [comment]
Any update on this? I'm getting the same behavior, and the same output from the diagnostic tool - saying
```
[FAIL] DD0014: are the backend processes running? 1 error occurred:
* vpnkit.exe is not running
```
However, in Powershell:
```
PS C:\> Get-Process "*vpnkit*"

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    110      10    19800      20368       0.06  20268   2 com.docker.vpnkit
    233      15    27692      18588       1.98   6520   2 vpnkit-bridge
```
So it looks like it is running, unless there's some other vpnkit processes supposed to be running too.

Any help would be much appreciated.
