### ISSUE TITLE
Slim.Ai Extension Documentation Leading to 404 Page

### ISSUE THREAD

**Issue by nugrahayoga** [docker/for-win#12924]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Opening Slim.Ai documentation, redirected to https://www.slim.ai/docs/docs/docker-desktop-extension.html (there's a double docs on the url, leading to 404 page.

### Expected behavior
Opening Slim.Ai documentation, redirected to https://www.slim.ai/docs/docker-desktop-extension.html

### Information

  - Windows Version: Windows 11 (Build 22000.856)
  - Docker Desktop Version: Docker Desktop 4.11.1 (84025)
  - WSL2 or Hyper-V backend?  WSL
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Open Docker for Windows Dashboard
  2. Click on Extension Page, Manage Extension, Marketplace
  3. Click on Slim.Ai extension, Details, Documentation, this will be opening 404 error page.

**Comment by nicks** [comment]
Thanks for reporting!

**Comment by joshviney** [comment]
Thanks for the bug report. We (Slim.ai) made an update this morning to properly handle the docs URL.

**Comment by nicks** [comment]
thanks @joshviney ! Ya, I can confirm that the url redirects to the right place now :joy:

**Comment by nugrahayoga** [comment]
You're welcome! Can confirm that the problems is fixed. Thank you for your quick response.
