### ISSUE TITLE
docker desktop is not running 

### ISSUE THREAD

**Issue by kunreddyshyam3** [docker/for-win#12932]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by kunreddyshyam3** [comment]
pls anyone help me to get out of this issue

**Comment by SorenCSorensen** [comment]
Same, but it worked for a while - I am on Windows 10 Home, so windows containers is not available, do I need to have a running Linux VM in WSL or whatever when I start up Docker Desktop for Windows?

Here's my diagnosis 3D8667EA-4399-4CA3-8CEF-90A5738CD9DC/20220912003751
