### ISSUE TITLE
Docker Desktop is not starting

### ISSUE THREAD

**Issue by gauravrladani** [docker/for-win#12934]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F9F38F43-FEC2-4563-8375-ED676A09CDFF/20220826055659

### Actual behavior
It is not starting and getting stuck on the landing screen "Docker Desktop starting..."

### Expected behavior
It should start normally

### Information

  - Windows Version: Windows 11 Version 21H2 (OS Build 22000.856)
  - Docker Desktop Version: 4.11.1
  - WSL2 or Hyper-V backend?  WSL2?
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
[FAIL] DD0031: does the Docker API work? error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine_linux/v1.24/containers/json?limit=0": open //./pipe/docker_engine_linux: The system cannot find the file specified.
[FAIL] DD0004: is the Docker engine running? Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[FAIL] DD0011: are the LinuxKit services running? failed to ping VM diagnosticsd with error: Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.
Error response from daemon: open \\.\pipe\docker_engine_linux: The system cannot find the file specified.
[FAIL] DD0003: is the Docker CLI working? exit status 1
[FAIL] DD0014: are the backend processes running? 1 error occurred:
        * vpnkit.exe is not running
[FAIL] DD0009: is the vpnkit API responding? open \\.\pipe\dockerVpnKitDiagnostics: The system cannot find the file specified.
[FAIL] DD0012: is the VM networking working? network checks failed: Post "http://ipc/check-network-connectivity": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.
[FAIL] DD0032: do Docker networks overlap with host IPs? error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine_linux/v1.24/networks": open //./pipe/docker_engine_linux: The system cannot find the file specified.

Please investigate the following 3 issues:

1 : The test: are the backend processes running?
    Failed with: 1 error occurred:
        * vpnkit.exe is not running

Not all of the backend processes are running.

2 : The test: is the VM networking working?
    Failed with: network checks failed: Post "http://ipc/check-network-connectivity": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.

VM seems to have a network connectivity issue. Please check your host firewall and anti-virus settings in case they are blocking the VM.

3 : The test: are the LinuxKit services running?
    Failed with: failed to ping VM diagnosticsd with error: Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.

### Steps to reproduce the behavior
Start the docker for windows and it gets stuck.

**Comment by gauravrladani** [comment]
It's resolved after uninstalling docker desktop v4.11.1, and installing the older version of docker (v4.9.1).
It seems to be the problem with the new version of docker desktop i.e. v4.11.1.

**Comment by gauravrladani** [comment]
@spagu you can find all builds on this page: https://docs.docker.com/desktop/release-notes/#docker-desktop-491

**Comment by Fred707** [comment]
I'm also getting this on Windows 10 Enterprise OS Build 19042. 1889 . Every time I try to upgrade Docker to the latest(v4.11.1) it stops loading. Downgrading to 4.9.1 works as per the other comments.

Note: I am running in Windows mode, since my current project uses Windows containers. I did not have this issue when running in Linux mode, so perhaps it's related?

**Comment by SirMishaa** [comment]
See https://github.com/docker/for-win/issues/12978#issuecomment-1266687576 for "solution"

**Comment by david-engelmann** [comment]
[I was able to find a solution that doesn't require rolling back the version and documented in this comment](https://github.com/docker/for-win/issues/13020#issuecomment-1283055393)

**Comment by david-engelmann** [comment]
[Updated approach to try before uninstalling your main wsl distro](https://github.com/docker/for-win/issues/13020#issuecomment-1285447765)
