### ISSUE TITLE
Fail to run command "docker run -d redis" for Docker Desktop 4.12.0 on "Windows Container"

### ISSUE THREAD

**Issue by v-mengwe** [docker/for-win#12936]
**OS Version:** Win10 21H2/Win11 21H2
**Docker Desktop:** 4.12.0(85335)
**Regression:** Preview Release

**Repro Steps:**

1. Make sure the docker for desktop mode is "**Windows Container**".
2. Open the D4W dashboard and switch to Docker Engine tab, update the value of "experimental" from "**false**" to "**true**".
3. Open command prompt or Windows Powershell as Administrator.
4. Start an arbitrary Windows container via command "docker run -d redis".
5. Check whether succeeds to run the command "docker run -d redis".

**Expect:**
Succeed to run the command "docker run -d redis".

**Actual:**
Fail to run command "docker run -d redis" with an error. 
![image](https://user-images.githubusercontent.com/62053665/187420112-6457337b-a4c8-41c4-b619-f8abadcb1dae.png)
![image](https://user-images.githubusercontent.com/62053665/187420151-48c1ff25-425c-4e47-9cce-bf0aaa0428ed.png)

**More info:**
1. This issue **doesn't reproduce** on Docker for desktop 4.11.1 (84025).
2. This issue **doesn't reproduce** on Linux container.
3. This issue also reproduces for below commands on Windows container:
    > docker run -d -P wordpress
    > docker run -d -P ghost

**Comment by nicks** [comment]
Thank you for reporting! We're investigating...

**Comment by v-mengwe** [comment]
Verified on the latest build 4.12.0 (85629), this issue doesn't reproduce for mow.

**Comment by nicks** [comment]
Thanks for following up!

**Comment by v-mengwe** [comment]
There is a confusion, this issue reproduces for now. We reopen this issue. Change the value of "experimental" from "false" to "true" and the restart Docker Desktop can't fix this issue.
![image](https://user-images.githubusercontent.com/62053665/189077816-9da6610f-75bb-49ea-bc67-42a67c0182c0.png)

**Comment by v-mengwe** [comment]
@nicks Do you have any updates?

**Comment by nicks** [comment]
oops sorry i misunderstood the original issue.

I believe this is currently expected behavior. I've confirmed it works the same way on 4.11.0.

If you have Docker Desktop in Windows Container mode, you won't be able to pull or run any new linux images.

Adding the ability to do this may be on the roadmap in the future, see this discussion: https://github.com/docker/roadmap/issues/79
