### ISSUE TITLE
Docker Compose will not start only the requested service, it will start all

### ISSUE THREAD

**Issue by william00179** [docker/for-win#12947]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features

### Actual behavior
When running `docker compose start <container name>` all containers are being started.

### Expected behavior
Only the container name provided will start (unless there is a needs)

### Information
Updated to the latest version of Docker in order to resolve the recently fixed memory issue with WSL.

Right after that update this problem started to happen. 

I have a docker file with ~15 services in it, I only want to start my postgres container so run the command via the CLI. I see output that docker is starting all my containers.
  - Windows Version: Version	10.0.19044 Build 19044
  - Docker Desktop Version: 4.12.0 (85629) 
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

**Comment by ridgebacktom** [comment]
Can confirm. This bug also exists for the macOS version.
