### ISSUE TITLE
microsoft windows sql server express image doesnt run out of the box on Azure Windows container 1709 VM

### ISSUE THREAD

**Issue by douglaswaights** [docker/for-win#1294]
### Expected behavior
The container should run for pulled image microsoft/mssql-server-windows-express  latest in Azure in Windows Server with containers 1709 VM template.

### Actual behavior
It doesn't.

dafbcbb023dc225cd6e8c912c285160dd29c6da7ba665159476ca955b9572b6d
C:\Program Files\Docker\docker.exe: Error response from daemon: container dafbcbb023dc225cd6e8c912c285160dd29c6da7ba665159476ca955b9572b6d encountered an error during CreateContainer: failure in a Windows system call: The operating system of the container does not match the operating system of the host. (0xc0370101) extra info: {"SystemType":"Container","Name":"dafbcbb023dc225cd6e8c912c285160dd29c6da7ba665159476ca955b9572b6d","Owner":"docker","IsDummy":false,"VolumePath":"\\\\?\\Volume{c5e8da7e-9bff-4953-88ee-5abcbdf1cb8c}","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\docker\\windowsfilter\\dafbcbb023dc225cd6e8c912c285160dd29c6da7ba665159476ca955b9572b6d","Layers":[{"ID":"78629f44-78ca-5605-8891-62481c4c026c","Path":"C:\\ProgramData\\docker\\windowsfilter\\e73d49f430997fa8fa10a3f299e3272acda3c81c4d512c16c422c925a4460d0f"},{"ID":"caa5ece4-ffbe-59c5-815b-48d60bede463","Path":"C:\\ProgramData\\docker\\windowsfilter\\4e227b75935112acd227f10743ec971f6197d433158032edc06f5e07e9571466"},{"ID":"4a1388c7-c0c9-5e64-986c-f63e56cc1ece","Path":"C:\\ProgramData\\docker\\windowsfilter\\52884b20dcfb822b7c08a0c9dcc7ae2ece7160aa07058c7ad502e9ebd3e4b2e1"},{"ID":"ff74ec4c-2a10-5510-ab02-51007c5573f5","Path":"C:\\ProgramData\\docker\\windowsfilter\\1c0d34a9c3341e70e2f76f48831ddb0412e463faf8a834630be6ffaab9b952d8"},{"ID":"20c79eb6-5409-50bd-b548-b1ec37c63d69","Path":"C:\\ProgramData\\docker\\windowsfilter\\94927c4c08d08411c51803f3a81c12e2695264e36680f8c65ac2d3371a76c385"},{"ID":"3f197aa4-dddb-50ca-94ff-2916cecdb429","Path":"C:\\ProgramData\\docker\\windowsfilter\\dcf34026f5ac2a03117a92453020b81fe4af6ec67ec81e0625b5a0a2012bec14"},{"ID":"33d27449-3460-580a-8699-f2e07886f914","Path":"C:\\ProgramData\\docker\\windowsfilter\\ae0a5ecea0844741b43efbc77da51c53073fa938d4e8c8bd449cbea42edeeb42"},{"ID":"8c724baa-f6aa-5cba-a0a9-0e031e9cb344","Path":"C:\\ProgramData\\docker\\windowsfilter\\0ba1753b4379f10ac4e1bb806908d8ac0a3a3d17f9b1159646549cc3cd18bb99"},{"ID":"e2f297fd-d524-53db-9da7-80e691821bc7","Path":"C:\\ProgramData\\docker\\windowsfilter\\d7b056010e6df6d480e45120253a4f0453f0fe58ee2bc325aeaa9960eb9376f2"},{"ID":"5559f63e-b4a1-5387-b64a-5192df40189c","Path":"C:\\ProgramData\\docker\\windowsfilter\\c255746f545ba5cb454735747fb459715dd31a6e5c6c15d98ca56cb9d96913b1"},{"ID":"1435c5ca-a346-5d80-a4e8-e9572779c5ec","Path":"C:\\ProgramData\\docker\\windowsfilter\\a2e291ca35e2c25505583869f46ecc922071f740344a5d3d381178ec35723a97"},{"ID":"afd7f326-b5aa-5639-ba49-7be057fdfdcd","Path":"C:\\ProgramData\\docker\\windowsfilter\\16ee71b5a1417c3d2f5a09d8ff20ce138bc40bcce6da7b158c11e9285af8a9bd"},{"ID":"3201d5c4-44ab-54bc-91cc-85beba8b94e6","Path":"C:\\ProgramData\\docker\\windowsfilter\\1f194dc935774080baca78e15c918a6955218984f6e0c025a65d89e1a52c1d42"},{"ID":"aae13308-2906-5274-a33b-169877e8593a","Path":"C:\\ProgramData\\docker\\windowsfilter\\a13c7a760c83d544a1bb51e63e1c9e7c25cb149301c278800a4204ebd5ac3abf"}],"HostName":"dafbcbb023dc","MappedDirectories":[],"HvPartition":false,"EndpointList":["c65bfd83-2259-4ce3-8093-8f0094f1a0ca"],"Servicing":false,"AllowUnqualifiedDNSQuery":true}.

### Information
This is the out of the box setup. 

In Azure choose a new VM
Windows Server, version 1709 with Containers and then pull the latest microsoft/mssql-server-windows-express image. The same problem happens with developer version of windows sql server image.

It works fine on my local dev machine running Windows 10 1709

Here is docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 17.06.1-ee-2
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows Server Datacenter
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 3.5GiB
Name: sdm2016
ID: 3TS2:DDTD:WAGS:2SFI:ER2W:BHR4:TDIN:FRIS:P2D3:LXNJ:AXPI:YTUK
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

### Steps to reproduce the behavior

  1. Create a new Windows Server version 1709 with Containers VM in Azure
  2. RDP in to the VM
  2. pull the latest microsoft/mssql-server-windows-express image
  3. docker run -d -p 1433:1433 -e sa_password=Somepass0rd -e ACCEPT_EULA=Y microsoft/mssql-server-windows-express

Thanks
Doug

**Comment by friism** [comment]
For 1709, you're gonna need 1709-based containers unless you use Hyper-V isolation. Details here: https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility

I'd get in touch with the SQL Server guys to provide 1709-based images, or you can build your own. The Dockerfiles are here: https://github.com/Microsoft/mssql-docker/blob/master/windows/mssql-server-windows-developer/dockerfile

**Comment by douglaswaights** [comment]
Thanks for the info! - i hadn't realised this scenario needed hyper-v isolation

**Comment by amandeepdhindsa** [comment]
@friism  Thanks for the info. It would be great if you could provide 1709 based containers for sql server express. I am running under nested virtualization and do not have the luxury of enabling it from the host.
