### ISSUE TITLE
> I solved this by deleting wsl how? go to setting apps search for linux it should pop up if its installed then click uninstall going to start menu type windows features then click on the following containers, hyper v, virtual machine platform, windows hypervisor platform, it will ask you to restart once the above are checked one more thing go setting apps startup apps find docker turn on on start up

### ISSUE THREAD

**Issue by Atlas-Night-Out** [docker/for-win#12952]
> I solved this by deleting wsl how? go to setting apps search for linux it should pop up if its installed then click uninstall going to start menu type windows features then click on the following containers, hyper v, virtual machine platform, windows hypervisor platform, it will ask you to restart once the above are checked one more thing go setting apps startup apps find docker turn on on start up
> 
> let me know if this fixes the issue my specs = windows 10 pro on amd chip

_Originally posted by @cliveapple in https://github.com/docker/for-win/issues/12949#issuecomment-1238041117_

**Comment by Atlas-Night-Out** [comment]
I'm not understanding you saying go to wsl Apps search has I see none of this on a windows 10 pro or where are you meaning?

**Comment by cliveapple** [comment]
Hi did you install wsl?
find out by running wsl in the search bar next to the windows logo
should pop up with the linux icon

**Comment by cliveapple** [comment]
[https://www.linkedin.com/posts/clive-hunt-788171178_docker-activity-6972880940293312513-E06r?utm_source=share&utm_medium=member_deskto](url)
