### ISSUE TITLE
Not able to start Docker

### ISSUE THREAD

**Issue by Sashko-Milushev** [docker/for-win#12965]
- [x ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: FF85938B-43F5-405B-9A19-DB09CF9FA592/20220914133711

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. I am not able to start using Docker Desktop. I have enabled containerization from my BIOS. And tried these commands in the Power Shell:
  2. dism.exe /Online /Enable-Feature:Microsoft-Hyper-V /All
  3. bcdedit /set hypervisorlaunchtype auto

**Comment by SirMishaa** [comment]
See https://github.com/docker/for-win/issues/12978#issuecomment-1266687576 for "solution"

**Comment by david-engelmann** [comment]
@Sashko-Milushev [I was able to find a solution that didn't involve rolling back and documented in this comment](https://github.com/docker/for-win/issues/13020#issuecomment-1283055393)
