### ISSUE TITLE
DockerCli.exe -SharedDrives no longer lists shared drives

### ISSUE THREAD

**Issue by danegsta** [docker/for-win#12973]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

Running DockerCli.exe -SharedDrives outputs a warning `unknown shorthand flag: 'S' in -SharedDrives` and no shared drive list

### Expected behavior

Running DockerCli.exe -SharedDrives outputs a list of drives that have been shared

### Information

  - Windows Version: Windows 10 21H2 19044.2006
  - Docker Desktop Version: 4.12.0
  - WSL2 or Hyper-V backend?  Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

1. Open a command prompt and run `"%ProgramFiles%\Docker\Docker\DockerCli.exe" -SharedDrives`
2. Check that you get a warning instead of a list of drives that have been shared with Docker for Windows

This particular change breaks a prerequisite check that Docker Tools for Visual Studio 2022 and 2019 use to determine if Docker file sharing was configured for a Hyper-V based Linux runtime.

**Comment by christophermclellan** [comment]
Hi @danegsta, thanks for flagging this. Could you share a diagnostic id when you get a moment ? https://docs.docker.com/desktop/troubleshoot/overview/#diagnose-from-the-terminal

**Comment by christophermclellan** [comment]
Thanks for that @danegsta. 

Hey @thaJeztah, I wonder whether you have any context on why `%ProgramFiles%\Docker\Docker\DockerCli.exe" -SharedDrives` seems to no longer function in v4.12.0 of Desktop ? cc @sam-thibault

**Comment by thaJeztah** [comment]
I think `DockerCli.exe` here is a binary that Docker Desktop ships (it's not the `docker` CLI, but named confusing).

**Comment by christophermclellan** [comment]
Ah, sorry @thaJeztah.

@danegsta - we've got a ticket for this now and are assigning to a colleague to fix it for the next release of Desktop.

**Comment by sam-thibault** [comment]
This command was restored in Docker Desktop 4.14.0.

**Comment by chelnak** [comment]
Hey @danegsta, are you still relying on this CLI for Visual Studio?
