### ISSUE TITLE
Docker 4.12.0 works only for linux

### ISSUE THREAD

**Issue by QuAzI** [docker/for-win#12970]
Can't use it for Windows and GUI shows Linux settings even if switched to Windows
![image](https://user-images.githubusercontent.com/1897605/191027770-e3f6adc1-d9cc-410d-9631-e11e53a738fa.png)

**Comment by kevinsullivan** [comment]
What an utterly irresponsible, amateurish, disgraceful action on the part of the Docker team. Do you folks have any real software engineers working there? THIS IS UNACCEPTABLE.

**Comment by thenik** [comment]
🤣 wow, looks like I have to wait with update....

**Comment by SirMishaa** [comment]
See https://github.com/docker/for-win/issues/12978#issuecomment-1266687576 for "solution"

**Comment by QuAzI** [comment]
Updater still switches Docker to Linux version, even on update 4.16.1 => 4.16.3
