### ISSUE TITLE
Docker Desktop cannot start

### ISSUE THREAD

**Issue by Brightlaz** [docker/for-win#12975]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 8E410953-F0F5-4E18-A957-FCCF509BE625/20220922121157

### Actual behavior
I am new to docker destop, I downloaded the software but is not opening
### Expected behavior
It was supposed to open
### Information

  - Windows Version: windows 10
  - Docker Desktop Version: Docker version 20.10.17, build 100c701
  - WSL2 or Hyper-V backend?   
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
Hyper-V could not be detected. Check whether Hyper-V has been installed and set to start on boot, and check that the host has been rebooted.   
### Steps to reproduce the behavior
open

  1. ...
  2. ...

**Comment by SirMishaa** [comment]
Please use [this issue](https://github.com/docker/for-win/issues/12978) for update to make life easier for developers.

**Comment by Brightlaz** [comment]
Check out this link, I provided a solution on how I resolved this issue, for anyone who has the same issue, feel free to check it out
[https://github.com/docker/for-win/issues/12978#issuecomment-1256725334]
