### ISSUE TITLE
Docker Desktop: Empty logs display during container running

### ISSUE THREAD

**Issue by cfbsks** [docker/for-win#12986]
I have tried the latest version(4.12.0) in Windows 10 and 11. Sometimes, when containers run normally, I click Containers-specific container-logs. It supposed to show me the logs, however, it's completely empty. Then I use the `docker logs specific-container-name` in command line terminal, it just work well.
The problem happens randomly, and it may disappear after reboot.

**Comment by vcvitaly** [comment]
The same on Mac OS

**Comment by DemonIaS** [comment]
The same for me on Mac, just a random

**Comment by vcvitaly** [comment]
Just observed this on Docker for Windows, is it possible for someone to look into this? Given that I experienced it on both Windows and Apple machines I can't believe that there are no other people with the same issue. How can I provide some diagnostic info?

When this issue happens, `docker logs <servicename>` works in console. But trying to open Terminal for the container doesn't work as well. It seems like nothing related to console io works after the issue occurs. Restarting Docker Desktop helps until I navigate to some container logs and back to dashboard a few times.

Docker team, please advise what info do you need to work on this.

**Comment by vcvitaly** [comment]
Still relevant. In case there is someone who can take a look, I just uploaded diagnostics:
23612A29-368D-478E-A867-C40667BE7C93/20230123192847

This is for Docker for Mac, but I can provide diagnostics for Windows as well.

@cfbsks @DemonIaS have you found the way to fix it or just restart the app when it happens?

**Comment by Han-aorweb** [comment]
same here. nothing show up in the log section.

**Comment by cfbsks** [comment]
@vcvitaly It comes randomly and restart usually work.

**Comment by joaofrca** [comment]
Hi, same issue here, mac M1 chip too. Any clue how to solve this? I'm running the version 4.17.0.

**Comment by vcvitaly** [comment]
I filed an issue to Docker Support through the contact form, let's see if they can help.

**Comment by DemonIaS** [comment]
I'm using 4.17.0 (99724) and during latest few months didn't get these troubles with logs anymore. I don't know what exactly happened: Docker update, MacOS update, or something else.

**Comment by nachocodexx** [comment]
Hi, same issue in version 4.24.0 I'm just installed a few minutes ago.

**Comment by elektracodes** [comment]
Found out about it too. When I was in 4.23.0 it worked fine. Set up a coworker's docker in 4.24.0 he could not see the logs. I updated and lost the logs too.

**Comment by plg-swisslog** [comment]
seems to be working for me in 4.24.1
