### ISSUE TITLE
Unable to create: The execution of the command has stopped because the preference variable "ErrorActionPreference" or the current parameter has the value Stop: Hyper-V has not found any virtual switch with the name "DockerNAT". to New-Switch, <No files>

### ISSUE THREAD

**Issue by Thonio** [docker/for-win#1298]
Hello ! I have this issues, I know that there are already the same issues but the difference is in the logs

I just try to start Docker but I have this message.
This is my log
[log.txt](https://github.com/docker/for-win/files/1453801/log.txt)

Thanks !

**Comment by jasonbivins** [comment]
Hi @Thonio    Try to recreate the MobyLinux VM manually - or if you're able, switch Docker to Windows container mode in the GUI to see if that helps.
``` 

powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -destroy
powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -create  ```

**Comment by Thonio** [comment]
Hello @jasonbivins ! Due to the urgency of the project I had to find something else so I went to Docker Toolbox but thank you for your answer !

**Comment by jasonbivins** [comment]
Hi @Thonio  
If you haven't created any Docker networks, then you can use this script to reset your networking to try to clear out any non-functioning or duplicate networks.

https://github.com/MicrosoftDocs/Virtualization-Documentation/tree/master/windows-server-container-tools/CleanupContainerHostNetworking

**Comment by luxel** [comment]
We met the same issue, and resolved it by manually creating an "Internal" virtual switch named "DockerNAT" in Hyper-V management console.

P.S. We did some digging in the docker script MobyLinux.ps1, and found out that the execution of Hyper-V/New-vmswitch command was failing. We tried to manually run Hyper-V/New-vmswitch in powershell, and it said method not found.

**Comment by Thonio** [comment]
oh, ok!
In my case it's due to internal problem, to solve it I re-install my OS (not sure if it solve all the time) so I close this issues, thx dude!
