### ISSUE TITLE
Docker Desktop ignores my proxy settings

### ISSUE THREAD

**Issue by VladPxC** [docker/for-win#12989]
### Actual behavior
Can't pull images behind a corporate proxy.
The proxy settings via Docker Desktop seem to be ignored.
### Expected behavior
I am able to pull images behind a corporate proxy after setting up the proxy settings via Docker Desktop 

### Information
  - Windows Version: Windows 10 Pro 21H2
  - Docker Desktop Version: 4.12.0
  - WSL2 

After installing Docker Desktop, I had set up the proxy configuration via Docker Desktop (Settings -> Resources -> Proxies) and the configuration file under "C:\Users\<USER>\.docker\config.json". The login worked for me, but I could not pull an image from the Docker registry using Docker Desktop. On PowerShell I also got "Error response from daemon: Get "https://registry-1.docker.io/v2/": Proxy Authentication Required" when I tried to pull an image. And also when I tried to log in.
I also tried setting the user variables/system variables HTTP_PROXY, HTTPS_PROXY and NO_PROXY and restarted Docker several times. 

### Solution / Workaround:
It works if I set the system variables AND disable the proxy settings on Docker Desktop. 

Note: Even when this constalltion works. The command "docker info" outputs 
![image](https://user-images.githubusercontent.com/105706438/192745856-f8842705-7268-431b-907a-e6f1febb831c.png)
 where HTTP Proxy and HTTPS Proxy both should be taken from the config.json but are ignored. Only the No Proxy setting is used correctly.
 
So please take a look at the related code paths and fix this problem. By investigating a lot of time a read several bug reports regarding the proxy settings over the past years. It is a software that is used by many professional companies and therefore the proxy settings cannot be neglected.

**Comment by rogersjw** [comment]
I have the exact same issue even inside WSL2 using Docker Desktop for Windows with WSL2 backend. I have not found a combination of env settings and docker settings that work behind a corporate proxy. The config.json is not working.

**Comment by paulchambers** [comment]
Same issue for me. 

4.10.1 is the last version where proxy behavior works as expected. 

This is a critical blocker issue for users on a corporate network and it's very disappointing to have to spend time checking each version to see if proxy support has been broken or fixed.
