### ISSUE TITLE
how to persist the data among different docker containers

### ISSUE THREAD

**Issue by vibhutibindal** [docker/for-win#1299]
i want to create a docker container for MySQL and using my own script.sql file. I am using the command
  docker run --restart=always \
-e MYSQL_ROOT_PASSWORD=pw \
-e MYSQL_USER=username \
-e MYSQL_PASSWORD=pw \
-e MYSQL_DATABASE=databasename \
-v $PWD/db-dump:/docker-entrypoint-initdb.d \
-p 3306:3306 \
--name containername  mysql
where db-dump contains the file script.sql.when i am exiting the container and starting a new container it is not persisting the data and creating a new volume.How can i use the same volume among different containers.

**Comment by ebriney** [comment]
Hi @vibhutibindal, I think you can use [docker volumes](https://docs.docker.com/engine/admin/volumes/volumes/)
