### ISSUE TITLE
Unable to start Docker engine

### ISSUE THREAD

**Issue by 645418484** [docker/for-win#12990]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 8FC665D4-6BDB-4D04-8F53-7508E2B9F580/20220929011626
   use linux containers    wsl2 or hyperf Both are enabled

   I tried to use window containers  But it didn't work

I mistakenly killed the Docker Desktop process before this problem occurred and it could not start again
He worked well before that

Please, I need some help

**Comment by 645418484** [comment]
It may help that I found such errors in the journal
```
[2022-09-29T01:16:10.201656500Z][WSL2Provisioning  ][Error  ] Failed to terminate distro: exit code: -1
 stdout: 
NX[(WwQ	g?c?O?v
T?y?vR^0

```

**Comment by dikos1337** [comment]
Same problem after I updated windows 11 to version 22Р2 and the wsl kernel to 5.15.57.1-microsoft-standard-WSL2

**Comment by AliAS-86** [comment]
I am having similar issue with docker, it became unresponsive when I try to docker run a new container and when an I tried to reboot the docker desktop it got stuck at stopping the engine, I still didn't update the Win11 to 22H2 yet

Diagnosis ID: C8DFB75C-A853-490B-B0BF-6E848F075CC7/20221001224019

**Comment by SirMishaa** [comment]
See https://github.com/docker/for-win/issues/12978#issuecomment-1266687576 for "solution"

**Comment by 645418484** [comment]
> See [#12978 (comment)](https://github.com/docker/for-win/issues/12978#issuecomment-1266687576) for "solution"

So that solves my problem Thank you very much :)
