### ISSUE TITLE
Docker desktop saves DNS config to daemon.config but loads it from windows-daemon.json

### ISSUE THREAD

**Issue by dotcom9** [docker/for-win#13009]
### Actual behavior
Docker saves IP config in daemon.json
Docker applies IP config from windows-daemon.json in container

### Expected behavior
Docker applies IP config from the same file to which it saved it

### Information

  - Is it reproducible? Yes
  - Is the problem new? Yes
  - Did the problem appear with an update? v20.10.17
  - Windows Version: 10.0.19044
  - Docker Desktop Version:v20.10.17
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0023: is the Containers Windows Feature enabled?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[FAIL] DD0014: are the backend processes running? 1 error occurred:
        * vpnkit.exe is not running

[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: are the backend processes running?
    Failed with: 1 error occurred:
        * vpnkit.exe is not running

Not all of the backend processes are running.

### Steps to reproduce the behavior

1. Open docker desktop settings
2. Click on Docker Engine tab
3. Enter valid setting, eg. "dns": [ 8.8.8.8 ]
4. Click Apply and Restart
5. Open and observe content of C:\Users\<username>\.docker\daemon.json
6. Open and observe content of C:\Users\<username>\.docker\windows-daemon.json
7. Start a container
8. Open container in terminal
9. Run ipconfig /all command
10. Observe DNS IP address

**Comment by nicks** [comment]
Hi! Can you clarify:
- Is Docker Desktop running in Windows container mode or Linux containers mode?
- What container are you running in step (7)?

I believe the way this is expected to work is:
- daemon.json affects containers that run linux
- windows-daemon.json affects containers that run windows
And which one it modifies depends on which mode you're in.

**Comment by dotcom9** [comment]
It is running in Windows container mode.

![image](https://user-images.githubusercontent.com/4866561/195530727-bb4d920d-7b8c-4165-9286-bfd9b80e89d0.png)

Any container from my compose project (eg. mssql-server-windows-developer)
There are only windows containers in my application. The host on which docker-desktop is running is Windows 10.
