### ISSUE TITLE
Docker closes down WSL 2 backend unexspectedly over and over keeps running docker but shuts down pi node over and over won't keep it running won't restart it, I have to restart docker then everything repeats.

### ISSUE THREAD

**Issue by woolrab6** [docker/for-win#13006]
<x

************************************************************************************
*READ ME FIRST*
x
This repository is for reporting bugs with the Docker Desktop for Windows software,
which we respond to on a best-effort basis.

Do *not* paste logfiles into github issues: upload diagnostics instead, which are
only visible to Docker engineers.
x
Support requests in this repository (i.e., trouble installing or using the
software) will be ignored, but personalized support is available to Docker Pro and
Team customers at https://hub.docker.com/support/desktop/, and community support is
available from the Docker community Slack (https://www.docker.com/docker-community).
x
Issues without sufficient detail to debug them will be closed. They generally need
a clear title and description, steps to reproduce, and a diagnostics ID. See
https://docs.docker.com/docker-for-windows/troubleshoot/#diagnose-and-feedback for
how to generate a diagnostics ID either from inside the app or from the command line.
************************************************************************************

-->x

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:0xA7e2E99e453227C892ac315C73ccaa7ab5378f77
x
### Information

  - Windows Version: home 10 pro
  - Docker Desktop Version:4.12.0 (85629)
  - WSL2 or Hyper-V backend?  yes
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: I think It started beta and for some reason it seems I can do both not sure. I know I'm in a cloud but think there is access to VM.

### Steps to reproduce the behavior

  1. ...just start docker and pi node 
  2. ...in 3 or 4 hrs it will shut down node and notification will pop about backend

**Comment by david-engelmann** [comment]
[I've created an issue with the same error and more info, I made it in the vscode remote dev repo](https://github.com/microsoft/vscode-remote-release/issues/7381)
