### ISSUE TITLE
I had this same issue. My problem was that I had the Docker CLI installed directly on WSL.

### ISSUE THREAD

**Issue by DanielTobi0** [docker/for-win#13008]
I had this same issue. My problem was that I had the Docker CLI installed directly on WSL.

I switched docker for windows back to Hyper-V, then uninstalled the Docker CLI from WSL. After turning back on WSL integration everything worked.

_Originally posted by @joshward in https://github.com/docker/for-win/issues/6494#issuecomment-628092012_
      

Kindly elaborate on this....make it clearer

**Comment by nicks** [comment]
Hi! I think this was posted as a new issue by mistake. Closing...
