### ISSUE TITLE
Error: GetResourcePath: BaseFS of container ... with exec command

### ISSUE THREAD

**Issue by xeurun** [docker/for-win#13002]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C82985AB-787A-4898-9DEC-1149834A60BF/20221006080219

### Actual behavior

In WSL2 (Ubuntu) with enabled containerd experimental feature is enabled in Docker i'm get error `GetResourcePath: BaseFS of container ... is unexpectedly nil` when try execute `docker-compose exec` command (but it work not with all containers)

### Expected behavior

`docker-compose exec` command correctly works for any containers

### Information

  - Windows Version:
  ```
Edition		Windows 11 Pro Insider Preview
Version		22H2
Installed on	10/‎4/‎2022
OS build	25211.1010
Experience	Windows Feature Experience Pack 1000.25211.1010.0
  ```
  - Docker Desktop Version:  
  `v.4.12.0`
  - WSL2 or Hyper-V backend?
  `WSL2`
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:
`  No.`

Similar problem: https://github.com/microsoft/vscode-remote-release/issues/7214#issuecomment-1252630378

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

```
[2022-10-06T10:12:09.620756200Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[FAIL] DD0014: are the backend processes running? 1 error occurred:
        * vpnkit.exe is not running
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[FAIL] DD0012: is the VM networking working? network checks failed: failed to ping host: exit status 1
[FAIL] DD0032: do Docker networks overlap with host IPs? network bridge has subnet 172.17.0.0/16 which overlaps with host IP 172.17.80.1
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
```

### Steps to reproduce the behavior

  1. make file `docker-compose.yaml`
  ```
  services:
      test:
          user: root
          image: php:8.0.22-fpm-buster
  ```
  2. run `docker-compose up -d` & `docker-compose exec test bash` (`docker exec -ti ... bash` also didnt work)

**Comment by NameLessKnight** [comment]
is there have any solution,i don't want use polling anymore

**Comment by chmely** [comment]
Disabling the experimental feature `Use containerd for pulling and storing images` solved it for me

**Comment by xeurun** [comment]
v.4.13.0 it worked, closing the issue.
