### ISSUE TITLE
When Docker running, host internet slow and Google services (in any browser) stop working

### ISSUE THREAD

**Issue by AustinWinstanley** [docker/for-win#1300]
### Expected behavior

N/A

### Actual behavior

As soon as I start Docker for Windows, Google.com, Google Search (even in DuckDuckGo with !g), Google Inbox, and YouTube completely stop working in all browsers on host machine (tested Chrome, Firefox, Edge, Brave) and the internet response for other pages seems very slow, even though a test from fast.com still shows 220 Mbps. It seems like some kind of DNS issue. Every other website works, just slowly. Only (all) Google services completely fail. And the responses from the website running inside the Docker Ubuntu container are extremely slow (5 - 30 second response time).

### Information

- Network Settings
![docker-network](https://user-images.githubusercontent.com/4576933/32563835-e1a32c4c-c477-11e7-867c-a598ada50839.png)

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
509A0038-E541-475B-801E-93ECA9B2EA39/2017-11-08_11-24-03

  - a reproducible case if this is a bug, Dockerfiles FTW
https://github.com/CadyIO/create-wp-app/tree/master/files/docker

Can be tested using this npm modules with:

```
npm i -g create-wp-app
create-wp-app dockertester
cd dockertester
npm i
npm run start
```

OR

```
yarn global add create-wp-app
create-wp-app dockertester
cd dockertester
yarn
yarn start
```

  - page URL if this is a docs issue or the name of a man page
N/A

  - host distribution and version (Windows version, build number, etc)

Docker version 17.09.0-ce, build afdb6d4
docker-compose version 1.16.1, build 6d1ac219

Windows 10 Pro
Version 1709
Build 16299.19

Image: Ubuntu:Latest

Network router is set to Google NameServers for DNS  (8.8.8.8, 8.8.4.4)

Network connecting speed test is 220 Mbps

### Tried

- Setting /etc/resolv.conf to Google NameServers (8.8.8.8, 8.8.4.4)

### Steps to reproduce the behavior

  1. Start Docker on Windows
  2. Start a Docker Container
  3. Search Google in any browser

**NOTE** Mac and Linux host behavior works fine with the same setup

**Comment by jasonbivins** [comment]
Hi @AustinWinstanley 
Do you only see this with Ubuntu  images?
Can you run ```docker network ls ``` and share the results?

**Comment by octavian-git** [comment]
I have the exact same issue.
Docker version: Version 17.09.0-ce-win33 (13620) 8c56a3b

Output of `docker network ls`
` docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
95eee5ee1e47        bridge              bridge              local
0c52d6182fa0        host                host                local
1834d90704a1        none                null                local`

**Comment by AustinWinstanley** [comment]
Confirmed that this is happening on all images. It actually starts occurring as soon as Docker is started, before any images have even been created or started.

```
PS E:\Projects> docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
10b7baa3c843        bridge              bridge              local
4cb3f051e553        host                host                local
ca72c5e3f64b        none                null                local
```

I tried completely uninstalling Docker and all of it's files and removing all Network Adapters, then reinstalling Docker. Same problem.

It's pretty frustrating because when Docker is running, I can't access any Google sites and accessing the sites running in the containers is excruciatingly slow, to the point of being unusable.

**Comment by cbarlow1993** [comment]
I'm having a similar issues. The internet might slow down for a period of time, DNS resolution takes up to a minute and then seems to go back to normal. 
```
docker --version
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:22 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:29 2017
  OS/Arch:      linux/amd64
  Experimental: true
```

**Comment by swicken** [comment]
I am having this issue as well. As soon as docker is installed and running with Hyper V enabled my initial DNS resolution takes forever. Once it starts going it seems fine. If you let the machine sleep or sit for a while then the problem reoccurs.

Anyone have any solutions?

**Comment by ejo** [comment]
Same here; docker version output is identical to cbarlow1993 above. I have run docker network prune and it looks like i have no unused or spurious networks running, just the base (host, bridge, none) and one more shared by my containers in my single current docker-compose project. (incidentally their status is currently paused; this problem happens whether they are running or paused).

Main symptom for me is at initial windows startup, my first action is often to open Chrome, and I've found that it takes around a full minute or so to actually get any WAN URL to respond. Sometimes there's the "downloading proxy script" message which never happened before installing docker for windows. Other times it's just a long long wait and then finally (often after a forced refresh) pages will load and work as normal.

**Comment by philipkaare** [comment]
It happens for me too, with the most recent docker version.

**Comment by naishu** [comment]
Even I have the same issue. Whenever I Start docker, google sites doesn't load and there is an intermittent network outage

**Comment by ejo** [comment]
I had to go to my system's network properties and switch the options from automatic proxy detection back to no proxies at all. That worked.

But I don't really recommend staying with Docker for Windows, for other reasons that were more than enough to make the decision for me. I've gone back to doing my linux development in a VM when I'm in a place where I need to use a Windows host system. And other times I'm on my Linux-native laptops.

**Comment by AustinWinstanley** [comment]
It appears that the workaround suggested by @ejo works. Go To **Settings -> Network & Internet -> Proxy** and turn off **Automatically detect settings**.

There was still a hiccup or two, but Google services are again available. Thanks!

![proxy](https://user-images.githubusercontent.com/4576933/38149141-fc025ce0-341e-11e8-9285-d78397b36074.png)

**Comment by nbgucer** [comment]
I have the same issue with the latest Docker for Windows client:
**Docker version 18.09.1, build 4c52b90**

While Docker is running, I cannot access to any Google services, but other sites works well, as well as Docker APIs. 

Here is my Docker info:
```
C:\Users\bguce>docker info
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 15
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155de84017
ID: JN5H:UTI4:UKSG:T2EL:IAG4:3SOF:ZBFR:KEYG:WHGX:ZV5A:T2NX:JFJ7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 46
 System Time: 2019-02-01T13:45:59.8878542Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

And my docker network ls is:
```
C:\Users\bguce>docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
7257f32fd33d        bridge              bridge              local
81dbea6f770f        host                host                local
6a2677ba764d        none                null                local
```

I have tried the method @AustinWinstanley suggested, but it has not helped.

_As an additional note: **Check Point End Point Endpoint Security VPN** is installed but not running while testing this issue._

**Comment by yaakovbg** [comment]
Had also the problem, I have disabled the network on my computer that was holding the network to docker(named dockerNAT).
solved the problem. 

On the other hand, if I want to be able to access the containers straight through their internal ip's, I wont be able through the host.

Hope I was clear enough...
