### ISSUE TITLE
Docker for Windows won't start Win 10

### ISSUE THREAD

**Issue by emilvw** [docker/for-win#1301]
### Expected behavior
1. Open Docker for windows interface
2. Running Docker tray application

### Actual behavior
Nothing happens at all. MobyLinuxVM is not created.
The only entry in the log file 
`
Version: 17.09.0-ce-win33 (13620)
Channel: stable
Sha1: 8c56a3b0e1bf39569b048201110bf1005e4b3ac9
Started on: 2017/11/08 13:59:01.504
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1607
Build: 14393
BuildLabName: 14393.1770.amd64fre.rs1_release.170917-1700
File: C:\Users\enadzhafov\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[13:59:01.761][GUI            ][Info   ] Starting...
[13:59:01.857][GUI            ][Error  ] An instance is already running. Exiting.
`
There is no running instance
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)
Windows 10 Pro
Version 1607
OS Build 14393.1770

### Steps to reproduce the behavior

  1. Install docker-ce-17.06.2-ce

### Attempts to resolve
1. uninstalled/reinstalled 
2. Removed all related folders in ProgramData, Programs, AppData etc
3. Applied the latest Win updates
4. Disable/Re-enable virtualization in windows features
5. The debug info attached  

[debug_info.txt](https://github.com/docker/for-win/files/1455180/debug_info.txt)

**Comment by neuki** [comment]
I have the same problem, but docker-ce-17.06.2-ce is the latest version that work's on my Windows. If i upgrade to a higher version e.g. 17.12.0-ce-win46 (15048) "Docker for Windows.exe" doesn't start. 

Logfile:
Version: 17.12.0-ce-win46 (15048)
Channel: stable
Sha1: 0ac7325e4f480d6458b9d4ef12b50d8fcf782fae
Started on: 2018/01/13 09:52:28.554
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1709
Build: 16299
BuildLabName: 16299.15.amd64fre.rs3_release.170928-1534
File: C:\Users\neuki\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[09:52:28.632][GUI            ][Info   ] Starting...
[09:52:28.648][GUI            ][Error  ] An instance is already running. Exiting.

Can somebody help?

**Comment by emilvw** [comment]
After further research, I discovered that the Mutex name was conflicting with another tray application. In my case it was  **Thunderbolt software** 
If  in your case the **Thunderbolt software** is not installed, try to exit tray applications one by one to see which one fixes the issue. 

Ideally the following code should include the **docker** string to avoid the collisions

`mutexName = string.Format("Global\\{0}", Assembly.GetExecutingAssembly().GetType().GUID);`

**Comment by ctartamella** [comment]
I can confirm this was indeed the issue for me.  Razer Synapse version 3 at a minimum seems to conflict.

**Comment by DeekyJay** [comment]
Confirming as well. I lost a day of work because of Razer Synapse v3. 😞
