### ISSUE TITLE
Docker Desktop fails to start up after fresh install. com.docker.backend keeps crashing

### ISSUE THREAD

**Issue by katomilis** [docker/for-win#13027]
- [ X] I have tried with the latest version of Docker Desktop
  - [ X] I have tried disabling enabled experimental features
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID: 
[diagnose.txt](https://github.com/docker/for-win/files/9847081/diagnose.txt)
[log.txt](https://github.com/docker/for-win/files/9847082/log.txt)

### Actual behavior
Docker Desktop remains invisible, keeps starting up crashed backend service.

### Expected behavior
Docker Desktop starts up
### Information
I just installed Docker Desktop for the first time. Tried version 4.13, 4.12 and 4.11.1.
These are the logs of 4.11.1.
I reinstalled Docker Desktop multiple times and rebooted in between installs.

  - Windows Version: Windows 10 Home
  - Docker Desktop Version: 4.11.1
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
[diagnose.txt](https://github.com/docker/for-win/files/9847081/diagnose.txt)

**Comment by mklueh** [comment]
Same here. Reboot did not help

**Comment by viceice** [comment]
only seeing this on 4.13

https://gist.github.com/viceice/ab813debab2040ea3eb6070d08a284d0

**Comment by jweslley** [comment]
It seems the solution for now is reinstalling. It worked for me but I lost all images/volumes :/  https://github.com/docker/for-win/issues/13025#issuecomment-1286883888

**Comment by MattiasDC** [comment]
> It seems the solution for now is reinstalling. It worked for me but I lost all images/volumes :/ [#13025 (comment)](https://github.com/docker/for-win/issues/13025#issuecomment-1286883888)

Reinstalling didn't work for me
