### ISSUE TITLE
Download update button not working to upgrade from 4.12.0 to 4.13.0

### ISSUE THREAD

**Issue by aboe026** [docker/for-win#13023]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Nothing happens after I click the "Download update" button
### Expected behavior
When I click the "Download update" button, the update begins to download.
### Information

  - Windows Version: Windows 11 Enterprise 10.0.22621
  - Docker Desktop Version: 4.12.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
[2022-10-20T14:26:40.349745600Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[FAIL] DD0014: are the backend processes running? 1 error occurred:
        * vpnkit.exe is not running

[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: are the backend processes running?
    Failed with: 1 error occurred:
        * vpnkit.exe is not running

Not all of the backend processes are running.
### Steps to reproduce the behavior

  1. Start with version 4.12.0 of Docker Desktop for Windows
  2. Go to the "Settings" -> "Software updates" page in the Docker Desktop for Windows UI
  3. Click the "Download update" button
  4. Observe nothing happens

I have observed this behavior on both my work and personal computers now.

**Comment by valiko-ua** [comment]
The same problem.

Additional minor note: clicking Check For Update button (or whatever it is called) does not give any clue if the check is/was performed. Some text below the button would be helpful to understand that the check started, in progress and finished.

**Comment by pcaversaccio** [comment]
same problem

**Comment by fraggenstein** [comment]
same issue - I willl add that the automatic update doesn't appear to be happening either

**Comment by AchimGrolimund** [comment]
Same Issue on Win11 Docker 4.12.0

**Comment by lgmorand** [comment]
+1 

Win11 Docker 4.12.0

even checking "Automatically download new updates in background." does not do anything

**Comment by dlorenzonespereira** [comment]
Same issue too

**Comment by rimelek** [comment]
Try to restart Docker Desktop before updating.

It was slow for me too and I thought it would never download the update. I stopped Docker Desktop and realized I was on VPN. I thought it was the problem so I disconnected from the VPN, started Docker Desktop again and tried to update again. It took some time but not as much as I waited previously. Eventually Docker Desktop downloaded the new version and I could finish the update process.

My OS is also Windows 11 and I don't know if it mattered but I have a WSL 2 preview version so it could also be the problem in my case.

**Comment by viceice** [comment]
restart doesn't help me. did two times. no network traffic at all and no VPN.

using stock wsl on win 11

**Comment by NiklasBr** [comment]
Experiencing the same issue on two separate Windows 10 computers. Multiple full restarts has not helped.

**Comment by viceice** [comment]
manual update to 4.13.0 totally broke docker.

**Comment by pcaversaccio** [comment]
tagging someone from the docker team @stephen-turner to make them aware of this issue.

**Comment by viceice** [comment]
Here's a gist with log

https://gist.github.com/viceice/ab813debab2040ea3eb6070d08a284d0

**Comment by mat007** [comment]
Hi, thanks for reporting this.
Can anyone experiencing this behaviour [create and upload diagnostics](https://docs.docker.com/desktop/troubleshoot/overview/#diagnose), please?

**Comment by lgmorand** [comment]
@mat007 Are you sure the self diag will check the fact that a button from the UI does not do anything ? For example, docker+k8s are running perfectly fine for me. Just the update is broken

**Comment by NiklasBr** [comment]
Diagnostics ID `1C242C51-1D24-4B67-9E9F-B6CD01EB2136/20221024094218`

Clicked the **Download update** button, waited about 15 seconds and then started the diagnostics.

**Comment by mat007** [comment]
@lgmorand it’s not the self diags I’m interested in, but the full diagnostics which contain all logs and some config probes of the machine.

@NiklasBr thanks, I’ll have a look!

**Comment by n0v1** [comment]
Same issue on Windows 10. Diagnostics ID: `EAA354F5-868D-4F8C-BE85-2DC29AE77745/20221024094919`.

**Comment by dlorenzonespereira** [comment]
Here is mine, Window 11 with WSL 2: F3D8ABB4-DB9E-453D-AD9A-2DD2C5CCDB82/20221024095749

**Comment by mat007** [comment]
Thanks for the diagnostics. We think we have found the issue, and are working on figuring out the best way to fix it.

**Comment by mat007** [comment]
We believe this should be fixed now.
You will have to quit and relaunch Docker Desktop, and after that the update should work.

Sorry about this.

**Comment by lgmorand** [comment]
@mat007 it seems to work !

**Comment by ThomasTosik** [comment]
Also works for me now.

**Comment by dlorenzonespereira** [comment]
@mat007 The update worked, but now Docker shows an error saying that has failed to start

I created a new Diagnostics ID: `F3D8ABB4-DB9E-453D-AD9A-2DD2C5CCDB82/20221024114909`

**Comment by pcaversaccio** [comment]
me too:
![image](https://user-images.githubusercontent.com/25297591/197519464-da40ac99-f36f-451b-9920-24d5894c61b8.png)

**Comment by mat007** [comment]
@dlorenzonespereira @pcaversaccio and everyone experiencing a failure to start with the new 4.13.0 version, can you open a separate issue please?

**Comment by mat007** [comment]
I’m going to close this one as the update itself is now fixed.
Feel free to comment if you experience the original issue again.
Thanks!

**Comment by lgmorand** [comment]
to be clear: it seems that the 4.13 is working fine (clean install). What it not working is 4.13 after an in-place update.

**Comment by pcaversaccio** [comment]
@mat007 please see here the issue: https://github.com/docker/for-win/issues/13025. Please help us out here - this whole upgrade experience is a nightmare for me so far - right now nothing works anymore locally for me (after rebooting 2 my computer)

**Comment by lgmorand** [comment]
@pcaversaccio 

Step 1: uninstall (take 30sec)
Step 2: install 4.13 (3 min)

you'll lose existing content but at least you'll have a working docker 4 win
