### ISSUE TITLE
Docker on Windows Insider build 17035

### ISSUE THREAD

**Issue by yrest** [docker/for-win#1302]
Hi folks, exactly the same behaviour as ten builds ago, reported on https://github.com/docker/for-win/issues/1255 
I think it is MS issue, but obviously they will never admit that. 
Can you see / do something on your side please?

to be precise, the following script 

$imageNameTag = "microsoft/nanoserver"
docker rm nanoserver -f
docker pull $imageNameTag
docker run -m 2G --name nanoserver `
           --hostname nanoserver `
           $imageNameTag

fails with 

docker : C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container c3fa787356445118807ab18d1d96aee151ba456ca996d70aa25ed318cefc980f 
encountered an error during CreateContainer: failure in a Windows system call: The description string for parameter reference (%1) could not be found. 

on 

Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 17.11.0-ce-rc2
Storage Driver: windowsfilter
 Windows: 
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17035 (17035.1000.amd64fre.rs_prerelease.171103-1616)
Operating System: Windows 10 Pro Insider Preview
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 15.92GiB
Name: ip
ID: FO5A:33Z4:RRV4:POY6:W5IQ:3U6T:OL6W:54UL:LAYR:ZDI2:KE7O:VBKY
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 32
 System Time: 2017-11-08T22:25:03.6108641Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by taylorb-microsoft** [comment]
This is a bug in Windows and we have a fix coming in the next flight... 
As a workaround you can temporarily disable our cloning optimization by creating a registry key and rebooting or restarting the vmcompute service. 
reg ADD "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Virtualization\Containers" /v TemplateVmCount /t REG_DWORD /d 0

But be sure to delete the key after you take the next flight or your container starts will remain slower...

**Comment by sepanc** [comment]
The registry hack worked even with the latest Windows 1709 creators update. I wasted almost a day trying to figure out why Windows Containers were not working, but the Linux mode worked.
