### ISSUE TITLE
Docker desktop wont start on boot up

### ISSUE THREAD

**Issue by dzekos7** [docker/for-win#13036]
Docker desktop wont start with windows boot up. It stopped and quit in 2-3 seconds. How do i fix this?

**Comment by david-engelmann** [comment]
[Similar Issue](https://github.com/docker/for-win/issues/13040). What version of Docker Desktop are you using?

**Comment by dzekos7** [comment]
> [Similar Issue](https://github.com/docker/for-win/issues/13040). What version of Docker Desktop are you using?

The latest
