### ISSUE TITLE
Docker failed to initialize: Docker desktop is shutting down

### ISSUE THREAD

**Issue by tamer-m-bayoumi** [docker/for-win#13032]
Version: 4.13.0 (89412)
Started on: 2022/10/24 20:37:07.139
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 2009
Build: 19044
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[2022-10-24T20:37:07.240216000Z][GUI               ][Info   ] Starting...
[2022-10-24T20:37:07.255842300Z][GUI               ][Warning] Failed to configure docker scan: System.UnauthorizedAccessException: Access to the path 'C:\Users\%User%\.docker\scan\config.json' is denied.

**Comment by GijsCalis** [comment]
Could you help the team and other users out by posting your diagnotics data?
See for instructions: https://docs.docker.com/desktop/troubleshoot/overview/
or just when you installed in the default location:
`"C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" gather -upload`
and then post the diagnostics ID in this issue.

**Comment by tamer-m-bayoumi** [comment]
Kindly note even the diagnostics data failed to be gathered as attached and the app screen failure too

<img width="957" alt="Docker issue" src="https://user-images.githubusercontent.com/24669463/198082281-85ccc744-a015-4097-8497-d925f8da1cf4.PNG">

**Comment by tamer-m-bayoumi** [comment]
This issue was solved by unhiding the ".docker" folder under the user folder in C drive
