### ISSUE TITLE
Installer comes with outdated CLI binaries

### ISSUE THREAD

**Issue by CybotTM** [docker/for-win#13038]
- [X] I have tried with the latest version of Docker Desktop

### Actual behavior
```
$ docker-compose version
Docker Compose version v2.2.2
```
### Expected behavior
```
$ docker-compose version
Docker Compose version v2.12.0
```
According to https://docs.docker.com/desktop/release-notes/#docker-desktop-4130

### Information

  - Docker Desktop Version: 4.13 (earlier versions too, also had it with 4.11.1 and earlier)

### Steps to reproduce the behavior

```
$ wget https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe
$ mkdir extracted
$ 7zz  x Docker\ Desktop\ Installer.exe -oextracted
...
FileVersion: 4.13.0.89412
...
$ mkdir iso
$ 7zz x extracted/resources/wsl/docker-wsl-cli.iso -oiso
$ chmod ugo+x iso/usr/bin/docker-compose
$ iso/usr/bin/docker-compose version
Docker Compose version v2.2.2
```

Related to #12928

**Comment by mat007** [comment]
`docker-compose` is not compose, but a small wrapper which shells out to the real compose binary.
The compose binary, in the ISO, is `usr/local/lib/docker/cli-plugins/docker-compose`.

You must have an old v2.2.2 `docker-compose` binary in the paths, possibly?

**Comment by CybotTM** [comment]
Hi @mat007 ,

thanks for your reply, you are right.

This is a little bit confusing. But it solved my issue.

Thank you.

**Comment by StefanScherer** [comment]
I just found an useful command to find out from which folder the compose CLI plugin is loaded:

```
$ docker info --format '{{range .ClientInfo.Plugins}}{{if eq .Name "compose"}}{{.Path}}{{end}}{{end}}'
/usr/local/lib/docker/cli-plugins/docker-compose
```
