### ISSUE TITLE
Docker Desktop could not get installed.

### ISSUE THREAD

**Issue by BrandynYu** [docker/for-win#13031]
Dear Support,

One of my team members could not get Docker Desktop installed on his Windows 10 laptop. (https://hub.docker.com/orgs/mtogovcanada/) 

Here is the log file attached.
[log.txt](https://github.com/docker/for-win/files/9853147/log.txt)

Thank you.

**Comment by BrandynYu** [comment]
Actually, it is installed but it stuck on Docker Desktop starting... screen.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/116581444/197572149-bfa330fa-41f8-4d9f-9384-bb86cf606f50.png)

**Comment by david-engelmann** [comment]
[I've discussed the resolution in this comment](https://github.com/docker/for-win/issues/13020#issuecomment-1285447765), Many have observed this behavior with the recent updates
