### ISSUE TITLE
failed to pull request

### ISSUE THREAD

**Issue by rjit17** [docker/for-win#1304]
I tried to pull my own container but while pulling I am getting the below error after few downloading steps
Docker command to pull the container 

`docker pull rjit17/gal:0.1`

**_Error Message:_** 

`failed to register layer: re-exec error: exit status 1: output: Failed to OpenForBackup failed in Win32: open \\?\C:\ProgramData\Docker\windowsfilter\f910b7c899af1f3438d60824ad74c631046c31307b037be1e1647b4c27e46def\usr\share\man\man7\pam.7.gz: The file exists. (0x1f) \\?\C:\ProgramData\Docker\windowsfilter\f910b7c899af1f3438d60824ad74c631046c31307b037be1e1647b4c27e46def\usr\share\man\man7\pam.7.gz`

### Information about the OS and Docker version

OS: Windows 10 Pro
Edition: Professional
Docker version 17.09.0-ce, build afdb6d4

### Steps to reproduce the behaviour

`  Docker pull rjit17/gal:0.1`

**Comment by msaxbury** [comment]
Some people have created file exclusions in Symantec Endpoint Protection and the problem is resolved, however, it did not work for me on Server 2016 Datacenter version.
https://github.com/moby/moby/issues/34807
