### ISSUE TITLE
Docker desktop failed to install

### ISSUE THREAD

**Issue by myviti** [docker/for-win#13045]
I am not able to install any version of docker desktop package on my windows 64 bit enterprise 16 GB machine.
Logs..

Component CommunityInstaller.EnableFeaturesAction failed: 
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at [CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
[install-log-admin.txt](https://github.com/docker/for-win/files/9921009/install-log-admin.txt)

**Comment by 79rpm** [comment]
Same here, Docker Desktop 4.13.1 on windows 10. It just stopped working from one day to another couple of months ago. I can't reinstall it now, I am getting the Installation failed pop-up with the following message:

Component CommunityInstaller.EnableFeaturesAction failed: Not found 
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()

It has been a pretty frustrating issue because Docket Desktop used to work before. Please help!

**Comment by reitzmichnicht** [comment]
If you rename/remove the %APPDATA%/Docker folder it works again for me

**Comment by myviti** [comment]
@reitzmichnicht can you give me resolution to original issue?

**Comment by 79rpm** [comment]
> If you rename/remove the %APPDATA%/Docker folder it works again for me

I have tested this and the situation is the same; the installation reports the same issue as above. What else can we provide the Docker team with? This is a long-dragging issue spread across the web. What steps would be to scrape Docker from Windows 10 so we can try a clean install?

**Comment by david-engelmann** [comment]
I had similar issues, [see if the steps laid out in this comment help](https://github.com/docker/for-win/issues/13020#issuecomment-1285447765)

**Comment by HollisTech** [comment]
I upgraded w11 to  22H2 and then docker to 4.13.1.  Docker was busted on install. I shutdown all wsl vms and uninstalled docker and then re-installed docker. It was still semi-busted but the install at least completed. I then started following @david-engelmann 's recipes as noted above (https://github.com/docker/for-win/issues/13045#issuecomment-1303990126) and docker was less busted but one of my persistent containers would not start, complaining about not being able to find docker.sock (the container was Cadvisor which needs this.) 

After uninstall/re-install only the 'default' wsl instance was enabled for docker integration. As my persistent containers are sourced from the default wsl instance (ubuntu 20.04),  I assumed that was sufficient, as that is what the docs say, but after I also set my ubuntu 20.04 instance as explicitly enabled for wsl integration, everything worked as expected.

**Comment by 79rpm** [comment]
I followed @david-engelmann steps, and it did not help. I finally found this here: https://programmersought.com/article/29075200559/

@echo on 
cd /d c:\temp 
if not exist %windir%\system32\wbem goto TryInstall 
cd /d %windir%\system32\wbem 
net stop winmgmt 
winmgmt /kill 
if exist Rep_bak rd Rep_bak /s /q 
rename Repository Rep_bak 
for %%i in (*.dll) do RegSvr32 -s %%i 
for %%i in (*.exe) do call :FixSrv %%i 
for %%i in (*.mof,*.mfl) do Mofcomp %%i 
net start winmgmt 
goto End 


:FixSrv 
if /I (%1) == (wbemcntl.exe) goto SkipSrv 
if /I (%1) == (wbemtest.exe) goto SkipSrv 
if /I (%1) == (mofcomp.exe) goto SkipSrv 
%1 /RegServer 


:SkipSrv 
goto End 


:TryInstall 
if not exist wmicore.exe goto End 
wmicore /s 
net start winmgmt 
:End 


I ran the attached script and rebooted Linux. I re-installed Docker Desktop, and it came back.

**Comment by 79rpm** [comment]
Could we have someone from the Docker team looking into this?

**Comment by JJC-code** [comment]
Same issue for me.
Is anybody able to help with issue?

**Comment by DeepBhat** [comment]
Same problem here. Tried all of the suggestions above, nothing really worked. Anyone have anything?

**Comment by JJC-code** [comment]
No suggestions, I created the new issue with detailed description, I hope somebody is going to take a look at it soon
https://github.com/docker/for-win/issues/13288

**Comment by Skittikorn** [comment]
Is this official website? any answer?
