### ISSUE TITLE
Can't find documentation - Db2 Developer Community Edition.

### ISSUE THREAD

**Issue by backlunddb2** [docker/for-win#1305]
### Expected behavior
HTML-page describing Db2 Developer Community Edition under Docker
### Actual behavior
Can't find the page - please tell me the URL
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jasonbivins** [comment]
Hi @backlunddb2 
Is this the page you were looking for?  https://hub.docker.com/r/ibmcom/db2express-c/

**Comment by backlunddb2** [comment]
Thanks for your reply - but no cigar!
      
      I am actually looking for the page describing Docker and Db2 Developer Community Edition.
        
        Best regards,
        
        Peter
        
      
    On 2017-11-09 18:34, Jason Bivins
      wrote:
    
    
      Hi @backlunddb2
        Is this the page you were looking for? https://hub.docker.com/r/ibmcom/db2express-c/
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/docker/for-win","title":"docker/for-win","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/docker/for-win"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jasonbivins in #1305: Hi @backlunddb2 \r\nIs this the page you were looking for?  https://hub.docker.com/r/ibmcom/db2express-c/"}],"action":{"name":"View Issue","url":"https://github.com/docker/for-win/issues/1305#issuecomment-343231237"}}}
    
    
    -- 

+--------------------------------+---------------------------------+
| Peter G Backlund               | E-mail:  BacklundDB2@telia.com  |
+--------------------------------+---------------------------------+
| Phone:   0046(0)70 - 764 7554  | Skype:   BacklundDB2            |
+--------------------------------+---------------------------------+
| May - September                | October - April                 |
+------------------------------------------------------------------+
| Råsundavägen 94                | Calle Alella 55, Apt 2B         |
| S-169 57  SOLNA   	         | 03185 Torrevieja                |
| Sweden                         | Spain                           |
+--------------------------------+---------------------------------+
|          Playing with DB2 since 1981 ... and forever!            |
+------------------------------------------------------------------+

**Comment by jasonbivins** [comment]
https://www.ibm.com/developerworks/data/library/techarticle/dm-1602-db2-docker-trs/index.html

**Comment by backlunddb2** [comment]
Hi Jason,
      
      now we are on the right subject, but still  not the document a
      used and lost...
      I used it for installing  Db2
          Developer Community Edition under Docker.
        The document was coming from Docker...
      
      Peter
    
    On 2017-11-09 18:54, Jason Bivins
      wrote:
    
    
      https://www.ibm.com/developerworks/data/library/techarticle/dm-1602-db2-docker-trs/index.html
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/docker/for-win","title":"docker/for-win","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/docker/for-win"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jasonbivins in #1305: https://www.ibm.com/developerworks/data/library/techarticle/dm-1602-db2-docker-trs/index.html"}],"action":{"name":"View Issue","url":"https://github.com/docker/for-win/issues/1305#issuecomment-343236909"}}}
    
    
    -- 

+--------------------------------+---------------------------------+
| Peter G Backlund               | E-mail:  BacklundDB2@telia.com  |
+--------------------------------+---------------------------------+
| Phone:   0046(0)70 - 764 7554  | Skype:   BacklundDB2            |
+--------------------------------+---------------------------------+
| May - September                | October - April                 |
+------------------------------------------------------------------+
| Råsundavägen 94                | Calle Alella 55, Apt 2B         |
| S-169 57  SOLNA   	         | 03185 Torrevieja                |
| Sweden                         | Spain                           |
+--------------------------------+---------------------------------+
|          Playing with DB2 since 1981 ... and forever!            |
+------------------------------------------------------------------+

**Comment by backlunddb2** [comment]
Found it!
      
      This was the document I was looking for
      
    "https://store.docker.com/images/db2-developer-c-edition/plans/124ad32d-aca4-4731-b282-87b94e876e42?tab=instructions"
      
      Best regards,
      
      Peter
    
    On 2017-11-09 20:50, Peter Backlund
      wrote:
    
    
      
      Hi Jason,
        
        now we are on the right subject, but still  not the document a
        used and lost...
        I used it for installing  Db2 Developer Community Edition under
          Docker.
          The document was coming from Docker...
        
        Peter
      
      On 2017-11-09 18:54, Jason Bivins
        wrote:
      
      
        https://www.ibm.com/developerworks/data/library/techarticle/dm-1602-db2-docker-trs/index.html
        —
          You are receiving this because you were mentioned.
          Reply to this email directly, view it on GitHub, or mute the thread.
        
          
            
            
          
          
        
        {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/docker/for-win","title":"docker/for-win","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/docker/for-win"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jasonbivins in #1305: https://www.ibm.com/developerworks/data/library/techarticle/dm-1602-db2-docker-trs/index.html"}],"action":{"name":"View Issue","url":"https://github.com/docker/for-win/issues/1305#issuecomment-343236909"}}}
      
      
      -- 

+--------------------------------+---------------------------------+
| Peter G Backlund               | E-mail:  BacklundDB2@telia.com  |
+--------------------------------+---------------------------------+
| Phone:   0046(0)70 - 764 7554  | Skype:   BacklundDB2            |
+--------------------------------+---------------------------------+
| May - September                | October - April                 |
+------------------------------------------------------------------+
| Råsundavägen 94                | Calle Alella 55, Apt 2B         |
| S-169 57  SOLNA   	         | 03185 Torrevieja                |
| Sweden                         | Spain                           |
+--------------------------------+---------------------------------+
|          Playing with DB2 since 1981 ... and forever!            |
+------------------------------------------------------------------+

    
    
    -- 

+--------------------------------+---------------------------------+
| Peter G Backlund               | E-mail:  BacklundDB2@telia.com  |
+--------------------------------+---------------------------------+
| Phone:   0046(0)70 - 764 7554  | Skype:   BacklundDB2            |
+--------------------------------+---------------------------------+
| May - September                | October - April                 |
+------------------------------------------------------------------+
| Råsundavägen 94                | Calle Alella 55, Apt 2B         |
| S-169 57  SOLNA   	         | 03185 Torrevieja                |
| Sweden                         | Spain                           |
+--------------------------------+---------------------------------+
|          Playing with DB2 since 1981 ... and forever!            |
+------------------------------------------------------------------+
