### ISSUE TITLE
Docker Desktop 4.13.1 SSO login broken

### ISSUE THREAD

**Issue by tehautanop** [docker/for-win#13062]
- [ X ] I have tried with the latest version of Docker Desktop
  - [ X ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
After upgrade or install of Docker Desktop 4.13.1 (to a Win10 Azure Virtual Desktop client w/ nested virtualization) cannot login using SSO.  I get the redirect to browser to login using my organization email and once it is submitted  - Docker Desktop tries to verify my credentials and fails with below errors. Does not create access-token, refresh-token etc in Windows Credential manager. 

Prior install of Docker Desktop 4.12.0 was working fine with same Docker Hub account & credentials and proxy. Access-token, refresh-token are created and everything works.

### Expected behavior
Obviously expecting the SSO login to go through as it does with prior installs (f.e. version 4.12.0) that worked fine.

### Information
Problem reproduced in a similar AVD setup, with our without prior Docker Desktop install.

### Steps to reproduce the behavior
  1. Docker Desktop 4.12.0 install on AVD, SSO login is working, everything fine.
  2. Upgrade to Docker Desktop 4.13.1 on AVD, SSO doesn't work anymore, "no such host" 
  
  Case 1 - with proxy set correctly in Docker Desktop client  and working, prior to 4.13.1
    Login Failed:
    Post "https://hub.docker.com/v2/access-tokens/desktop-generate": dial tcp: lookup hub.docker.com: no such host

  Case 2 - using set system proxy which works w/ basically with everything on the desktop client
    Login Failed:
    Post "https://login.docker.con/oauth/token": dialing login.docker.com:443: no HTTPS proxy: resolving host login.docker.com: lookup login.docker.com: no such host

#### Errors 

Clip from Electron****.log file related to login action:

> 2022-11-10T09:49:16.430Z info 	Response for POST /registry/open-login
> 2022-11-10T09:49:16.430Z info 	""
> 2022-11-10T09:49:19.233Z info 	received SSE data: { type: 'CodeReceived', restricted: false }
> 2022-11-10T09:49:19.235Z info 	rebuilding menu items with licenseHasBeenAccepted: true and loginRestricted: false
> 2022-11-10T09:49:19.620Z info 	received SSE data: {
>   type: 'UserdataReceived',
>   username: 'tehautan',
>   email: '[texxx.hauxxx@xx.xxx](mailto:texxx.hauxxx@xx.xxx)’,
>   restricted: false
>  }

Clip from com.docker.backend.exe.log file from the same time-period:

>  [2022-11-10T09:49:19.224938600Z][com.docker.backend.exe][W] using admin settings proxy (locked), will retry with default proxy: Post "https://login.docker.com/oauth/token": dial tcp: lookup login.docker.com: no such host
>  [2022-11-10T09:49:19.225937400Z][com.docker.backend.exe][I] HTTP 18 CONNECT login.docker.com:443: connecting via http://xxxxx.xxx.xx:8x8x
>  [2022-11-10T09:49:19.282390700Z][com.docker.backend.exe][W] fetching stats: parsing cpu usage counter value: strconv.ParseFloat: parsing "0,0365343725067306": invalid syntax
>  [2022-11-10T09:49:19.285191900Z][com.docker.backend.exe][I] HTTP 18 CONNECT login.docker.com:443: proxying to login.docker.com:443
>  [2022-11-10T09:49:19.617668300Z][com.docker.backend.exe][I] received tokens after swapping the authorization code at: 2022-11-10 11:49:19.6176683 +0200 EET m=+1727.337316501
>  [2022-11-10T09:49:19.617668300Z][com.docker.backend.exe][I] fetched tokens for: tehautan, expiry at 2022-11-10 12:49:19.6176683 +0200 EET
>  [2022-11-10T09:49:19.637660100Z][com.docker.backend.exe][W] retrying http call: Post "https://hub.docker.com/v2/access-tokens/desktop-generate": dial tcp: lookup hub.docker.com: no such host
>  [2022-11-10T09:49:19.640553500Z][com.docker.backend.exe][W] retrying http call: Post "https://hub.docker.com/v2/access-tokens/desktop-generate": dial tcp: lookup hub.docker.com: no such host
>  [2022-11-10T09:49:19.641851600Z][com.docker.backend.exe][W] retrying http call: Post "https://hub.docker.com/v2/access-tokens/desktop-generate": dial tcp: lookup hub.docker.com: no such host
>  [2022-11-10T09:49:19.644457700Z][com.docker.backend.exe][I] opening url in browser: https://hub.docker.com/logout?client_id=GuD3IQ7y0c9D7alvatTuvsT5V5BAjvwv
>  [2022-11-10T09:49:20.208773900Z][com.docker.backend.exe][I] user logged out, online features will be disabled
>  [2022-11-10T09:49:20.209340200Z][com.docker.backend.exe][I] entitlement: {PlanName:personal Desktop:{Enabled:false} Logged:false}
>  [2022-11-10T09:49:20.211905700Z][com.docker.backend.exe][I] admin controls manager received new entitlement:{"Logged":false,"desktop":{"enabled":false},"plan_name":"personal"}
>  [2022-11-10T09:49:20.212905900Z][com.docker.backend.exe][W] (3fb6eb3c) a3b8d53b-BackendAPI S->C 23a99ed0-URLSchemeHandlerCMD POST /registry/complete-login (1.0302689s): Post "https://hub.docker.com/v2/access-tokens/desktop-generate": dial tcp: lookup hub.docker.com: no such host
[common/cmd/com.docker.backend/internal/handlers/login.go:513 github.com/docker/pinata/common/cmd/com.docker.backend/internal/handlers.(*RegistryHandler).LogInFromURL()
[common/pkg/ipc/server.go:180 github.com/docker/pinata/common/pkg/ipc.(*server).wrapHandlerFunc.func1()
>  [2022-11-10T09:49:20.213914000Z][com.docker.backend.exe][I] a3b8d53b-BackendAPI /proxy-control --> [2022-11-10T11:49:20.213914000+02:00] (ae020fe8) proxy  : {"Locked":false,"Restricted":false}
>  [2022-11-10T09:49:20.214905900Z][com.docker.backend.exe][I] User has logged out so pausing backround Registry Access Management policy refresh

**Comment by tehautanop** [comment]
[PASS] DD0027: is there available disk space on the host?
[SKIP] DD0028: is there available VM disk space?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0020: is the Hyper-V Windows Feature enabled?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[FAIL] DD0006: is the Docker Desktop Service responding? failed to ping com.docker.service with error: Get "http://ipc/ping": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[2022-11-22T13:25:13.020834400Z][com.docker.diagnose.exe][I] ipc.NewClient: 1d461b0f-diagnose -> \\.\pipe\dockerBackendV2 Service
[common/pkg/diagkit/gather/diagnose.glob..func13()
[	common/pkg/diagkit/gather/diagnose/ipc_windows.go:14 +0x8b
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0xde4c60)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0xde4c60)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2?, 0xde4c60)
[	common/pkg/diagkit/gather/diagnose/run.go:142 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0xde4c60, 0xc0006c3ab8)
[	common/pkg/diagkit/gather/diagnose/run.go:151 +0x87
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0xde4960, 0xc0006c3ab8)
[	common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
[common/pkg/diagkit/gather/diagnose.walkOnce(0x7829c0?, 0xc00046fc20)
[	common/pkg/diagkit/gather/diagnose/run.go:137 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0xde4960, 0x0?, {0x0, 0x0, 0x0})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x1d4
[common/pkg/diagkit/gather.(*SelfDiagnose).Trigger(0xdf18b0)
[	common/pkg/diagkit/gather/diagnose.go:32 +0x6e
[created by main.gatherCmd
[	common/cmd/com.docker.diagnose/main.go:247 +0x9bf
[2022-11-22T13:25:13.021841500Z][com.docker.diagnose.exe][I] (d08f425b) 1d461b0f-diagnose C->S Service GET /ping
[2022-11-22T13:25:14.040018500Z][com.docker.diagnose.exe][W] (d08f425b) 1d461b0f-diagnose C<-S NoResponse GET /ping (1.0181675s): Get "http://ipc/ping": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[FAIL] DD0012: is the VM networking working? network checks failed: failed to lookup hub.docker.com: lookup hub.docker.com on 192.168.65.5:53: no such host
[2022-11-22T13:25:14.115366300Z][com.docker.diagnose.exe][I] ipc.NewClient: 98a2db37-diagnose-network -> \\.\pipe\dockerDiagnosticd diagnosticsd
[common/pkg/diagkit/gather/diagnose.runIsVMNetworkingOK()
[	common/pkg/diagkit/gather/diagnose/network.go:34 +0xd9
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0xde4360)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0xde4360)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2?, 0xde4360)
[	common/pkg/diagkit/gather/diagnose/run.go:142 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0xde4360, 0xc0005fbab8)
[	common/pkg/diagkit/gather/diagnose/run.go:151 +0x87
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0xde4960, 0xc0005fbab8)
[	common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
[common/pkg/diagkit/gather/diagnose.walkOnce(0x7829c0?, 0xc00046fc20)
[	common/pkg/diagkit/gather/diagnose/run.go:137 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0xde4960, 0x0?, {0x0, 0x0, 0x0})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x1d4
[common/pkg/diagkit/gather.(*SelfDiagnose).Trigger(0xdf18b0)
[	common/pkg/diagkit/gather/diagnose.go:32 +0x6e
[created by main.gatherCmd
[	common/cmd/com.docker.diagnose/main.go:247 +0x9bf
[2022-11-22T13:25:14.124947700Z][com.docker.diagnose.exe][I] (4c035a13) 98a2db37-diagnose-network C->S diagnosticsd POST /check-network-connectivity: {"ips":["10.71.6.240","172.22.48.1"]}
[2022-11-22T13:25:14.214324100Z][com.docker.diagnose.exe][W] (4c035a13) 98a2db37-diagnose-network C<-S 8163305d-diagnosticsd POST /check-network-connectivity (92.3849ms): failed to lookup hub.docker.com: lookup hub.docker.com on 192.168.65.5:53: no such host
[SKIP] DD0030: is the image access management authorized?
[WARN] DD0033: does the host have Internet access? unable to fetch http://docker.com/
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0020: is the Hyper-V Windows Feature enabled?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?
2 failures detected
1 : is the Docker Desktop Service responding?
    Failed with: failed to ping com.docker.service with error: Get "http://ipc/ping": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
The Docker Desktop Service is needed to start the Docker engine. Open the list of Services and configure the Docker Desktop Service to start automatically.

2 : is the VM networking working?
    Failed with: network checks failed: failed to lookup hub.docker.com: lookup hub.docker.com on 192.168.65.5:53: no such host
VM seems to have a network connectivity issue. Check your host firewall and anti-virus settings in case they are blocking the VM.

self-diagnose took 34.4315685s

**Comment by haxorof** [comment]
I bumped into login issues directly after I installed and started Docker Desktop 4.14.1. Got these "no such host" errors because the UI application do not pick up my Windows 10 system proxy configuration and I sit behind a corporate proxy. Proxy configuration I have in Windows are using a PAC-file. 

As workaround I created a batch script where I explicitly set environment variables HTTP_PROXY, HTTPS_PROXY and NO_PROXY before I start Docker Desktop. After that I can login and update checks works in the UI.

**Comment by tehautanop** [comment]
Proxy was set in settings.json (or admin-settings.json, tried that aswell) after the install.
HTTP_PROXY, HTTPS_PROXY are set for user, and have worked until version 4.13.x

I tested the install of 4.14.1 setting the HTTP_PROXY, HTTPS_PROXY system variables with 
http://<domain account id>:<domain account pwd>@<server>:<port>/

This isn't good progression on the proxy handling... it seems that Docker software developers screw up the proxy handling every now and then, this isn't the first time.

Thx @haxorof for the tip, appreciate it !

**Comment by lewisboon** [comment]
I think this issue should remain open?

I tried starting `Docker Desktop.exe` from cmd with HTTP_PROXY and HTTPS_PROXY set (in cmd, not globally) and it did not work. We also use a PAC file and have a fairly complicated set up. We definitely don't want to set HTTP_PROXY and HTTPS_PROXY globally.

**Comment by tehautanop** [comment]
We've had proxy set in settings.json and in 'User Variables' but having it also in the 'System Variables' was new.  It seems that Docker is forgetful with the proxy handling - it works for couple of version releases and then it's broken once again.  During the past year it's been broken 3-4 times already. I looked at current 'docker / for-win' issues, looks pretty grim regarding the proxy handling. 

And why didn't they make the proxy prompt dialog set as TopMost so that it won't be buried under all the other windows?
