### ISSUE TITLE
Docker for Windows update notification window too large to fit on screen

### ISSUE THREAD

**Issue by larsiwer** [docker/for-win#1307]
### Expected behavior
The update notification window is small enough so it fits on the screen and all buttons can be reached using the mouse without resizing/repositioning the window

### Actual behavior
The update notification is too large to completely fit on the screen
Screenshot: https://1drv.ms/i/s!Ar55RZHNBAUGhtsLmvwNDmjDw-lsCg

### Information
- Diagnostic ID: 963968BD-2925-46BA-B247-29C4B8292E5B/2017-11-09_11-14-05
- Windows 10 Enterprise build 17035
- Use a high-dpi monitor (2560x1440 pixels) set to 200% scaling factor.

### Steps to reproduce the behavior
Wait for a new update notification
Screenshot: https://1drv.ms/i/s!Ar55RZHNBAUGhtsLmvwNDmjDw-lsCg

**Comment by jasonbivins** [comment]
Hi @larsiwer 
Thanks for reporting this!  I've updated the existing bug report with your comments, and I'll go ahead and close this issue.
