### ISSUE TITLE
[WSL 2] Computer freezes after running docker pull

### ISSUE THREAD

**Issue by BalmungSan** [docker/for-win#13077]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B164AC52-3FBA-418B-BDA0-3629AB3C3F19/20221117190040

### Actual behavior

Computer freezes after running `docker pull` from my **WSL 2** instance _(**Ubuntu** `20.04`)_; the `pull` doesn't seem to even start at all.
By freezing I mean that I can't close any open terminal, be it **WSL**, **CMD** or **Powershell**. I can't open any new program, already opened programs partially work; e.g. **Chrome** is able to keep accessing opened pages, but I can't open a new page. And I am forced to shut down the computer via hardware.

Using **TaskManager** _(opened before running the command)_ doesn't show a high load of either component; actually, the opposite.

### Expected behavior

The image is being pulled and my PC keeps working.

### Information

Using the **EventViewer** I can find some errors happing close to the `pull` time; but actually a couple of minutes before _(maybe when the **Docker** service started)_. The exact origins are: `Hyper-V-StorageVSP` & `Hyper-V-Worker`

I am not sure if this can be reproduced on other PCs. However, it always happens on my PC. Even after a couple of re-installs and data purges. Also, running the diagnostics tool shows that everything is okay.

While it has been a while since the last time I used **Docker** on this PC _(around a month)_, in that time three important updates happened:

1. **Windows**:

```
Edición	Windows 10 Pro
Versión	22H2
Se instaló el	‎8/‎06/‎2020
Compilación del SO	19045.2311
Experiencia	Windows Feature Experience Pack 120.2212.4190.0
```

2. **WSL 2**: 

````
Versión de WSL: 1.0.0.0
Versión de kernel: 5.15.74.2
Versión de WSLg: 1.0.47
Versión de MSRDC: 1.2.3575
Versión de Direct3D: 1.606.4
Versión DXCore: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Versión de Windows: 10.0.19045.2311
````

3. **DockerDesktop**: `4.14.1` _(91661)_

**Comment by tintruong-ss** [comment]
Having the same issue, I even tried to completely remove Docker and WSL and reinstall them to latest version but still no hope....

**Comment by mgarber-ops** [comment]
I've been experiencing the exact same issues. I'm going through the procedures on exporting my pre-existing WSL distro and re-installing Docker Desktop & WSL from scratch and will let yall know if that did the trick... As alluded above I'm also sensing a recent WU caused this behavior.

**Comment by mgarber-ops** [comment]
> I've been experiencing the exact same issues. I'm going through the procedures on exporting my pre-existing WSL distro and re-installing Docker Desktop & WSL from scratch and will let yall know if that did the trick... As alluded above I'm also sensing a recent WU caused this behavior.

Looks like a re-install didn't do the trick. Going to have to look into rolling back some updates and see if that does the trick :\

**Comment by skiptyler008** [comment]
Facing same exact issue, no recovery, have to perform hard shutdown of pc.
Anyone able to resolve this issue, any pointers ?

**Comment by mgarber-ops** [comment]
Personally I ended up just using Docker solely in WSL without docker desktop

**Comment by skiptyler008** [comment]
> Personally I ended up just using Docker solely in WSL without docker desktop

is this for wsl2? Can u share a link to do that , thanks

**Comment by mgarber-ops** [comment]
> > Personally I ended up just using Docker solely in WSL without docker desktop
> 
> is this for wsl2? Can u share a link to do that , thanks

https://nickjanetakis.com/blog/install-docker-in-wsl-2-without-docker-desktop
