### ISSUE TITLE
Ao iniciar o docker ele da erro e sai

### ISSUE THREAD

**Issue by MicaildeJunior** [docker/for-win#13072]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by YouveGotMeowxy** [comment]
https://github.com/docker/for-win/issues/13040
