### ISSUE TITLE
How to start Docker Desktop automatically without user interaction?

### ISSUE THREAD

**Issue by cheme75** [docker/for-win#13096]
I'm frustrated I cannot seem to find an answer, Docker Desktop is setup to start automatically and display the dashboard. Docker Desktop is in the windows auto-start. However, Docker Desktop doesn't start automatically. the com.docker.service does start, but not the dashboard. When I start Docker through the desktop shortcut,  Docker always pops-up a dialog box whether to start the Docker service even when running it with admin privileges. It requires clicking on the Start button which then looks to be issuing a net command to actually get the dashboard/gui interface to launch and run. Can't this be fully automatic?

_Originally posted by @nikur in https://github.com/docker/for-win/issues/7704#issuecomment-660047025_

**Comment by nikur** [comment]
The following worked for me: I created a task to start Docker Desktop "at system startup" using the Windows Task Scheduler. Instead of running the task in the context of the "SYSTEM" user, I selected a "normal" user account but activated the "Run with highest privileges" option. That did the trick.
