### ISSUE TITLE
Clean up button on Image tab doesn't shows up all the time

### ISSUE THREAD

**Issue by mathias22osterhagen22** [docker/for-win#13091]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
The clean up button do not show up (I made it appear one time by rebooting the software).
![image](https://user-images.githubusercontent.com/60438474/203578152-b714ecd7-694f-4b0e-907f-b7af44d10920.png)

### Expected behavior
Display the clean up button all time
![image](https://user-images.githubusercontent.com/60438474/203578008-94cbc856-8ff0-4562-b118-fd7bf03e5b55.png)

### Information

  - Windows Version: 21H2 22000.1219
  - Docker Desktop Version: v4.14.1
  - WSL2 or Hyper-V backend?   WSL2 
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
```
🐦  .\com.docker.diagnose.exe  check
[2022-11-23T14:59:48.771196500Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0002: does the bootloader have virtualization enabled?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[FAIL] DD0005: is the user in the docker-users group? The user name could not be found.
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?

Please investigate the following 1 issue:

1 : The test: is the user in the docker-users group?
    Failed with: The user name could not be found.

The current user must be member of the docker-users group. Press the Win + R keys to open Run, type lusrmgr.msc into Run, followed by Enter to open Local Users and Groups.

```
### Steps to reproduce the behavior

  1. Start docker desktop
  2. Go to `Images` tab

**Comment by stephanierifai** [comment]
Hi @mathias22osterhagen22 !

Thanks so much for this feedback. We've moved the functionality so that you don't need to enable clean up mode to get the multi select checkboxes and delete them. On the images tab you can delete by selecting some or all of the images a filter it using the filter next to the search box. Please let me know if that solves the problem for you and If you have any additional feedback on this change/how we can improve the experience.
<img width="1106" alt="Screen Shot 2022-11-23 at 11 22 41 AM" src="https://user-images.githubusercontent.com/85884197/203598018-b982cfcb-8bfb-4720-981b-43b9e8ae2599.png">

**Comment by mathias22osterhagen22** [comment]
Hi @stephanierifai , 
Thank you for your answer, it's clear.
Then could you add a filter to select image without tag ? 
![image](https://user-images.githubusercontent.com/60438474/203967116-81531329-aab4-4197-b87a-ad35ab375c68.png)
