### ISSUE TITLE
docker hv-sock proxy (vsudd) is not reachable windows 10 enterprise N

### ISSUE THREAD

**Issue by drv62** [docker/for-win#1309]
### Expected behavior
Docker starting

### Actual behavior
Docker is unable to start and posts the error

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
A362C6DF-7BFB-4CCA-B2AC-E609729ABA5D/2017-11-09_18-18-51

Hyper V seems to be running fine as I am able to run a Windows VM that I had.

**Comment by jasonbivins** [comment]
Hi @drv62 
It looks like the MobyLinuxVM isn't getting created properly.  Do you know if Docker will start in Windows container mode?

Let's create the VM manually with this command to see if there is an error.
``` powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -create ```

**Comment by drv62** [comment]
The powershell command to create the VM manually worked when I ran as administrator in the "C:\Program Files\Docker\Docker\resources\" folder.  I can then use HyperV to start it and it shows as running with 23% CPU usage, but I can't connect to it!

Switching to Windows Containers does change the log quite a bit - but it ends up with failing to start with basically the same error message.  I think you are on the right track - something with MobyLinuxVM is not starting correctly.

[16:07:09.797][Moby           ][Info   ] [    0.000000] console [ttyS0] enabled
[16:07:09.806][Moby           ][Info   ] [    0.000000] allocated 4194304 bytes of page_ext
[16:07:10.646][Moby           ][Info   ] [    0.000000] tsc: Fast TSC calibration failed
[16:07:10.656][Moby           ][Info   ] [    0.000000] tsc: Unable to calibrate against PIT
[16:07:10.662][Moby           ][Info   ] [    0.000000] tsc: HPET/PMTIMER calibration failed

**Comment by jasonbivins** [comment]
@drv62 
We disable the integration services for the MobyLinuxVM - but not for other images. You mentioned that it fails in Windows container mode too? Can you send over a fresh diagnostic ID now that you have those entries in the log.
Is it possible for you to create a test VM then both start and connect to it?

**Comment by drv62** [comment]
I tried switching to Windows Containers again and this appears to have worked - I think I exited last time before the switch completed.  Thanks for your help.
