### ISSUE TITLE
Please stop opening the dashboard after restarting Docker Desktop

### ISSUE THREAD

**Issue by polys** [docker/for-win#13098]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
The dashboard opens after manually restarting Docker Desktop.

### Expected behavior
It should respect the "Open Docker Dashboard at startup" setting (which is off) and not open.

### Information

  - Windows Version: 10 (21H2)
  - Docker Desktop Version:  4.14.1 (91661)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:  No

### Steps to reproduce the behavior

  1. Right-click the tray icon and click Restart
  2. The dashboard shows up

**Comment by nicks** [comment]
Note that Desktop has two ways to open startup: "Start Docker Desktop when you log in" and "Open Docker Dashboard at startup". Can you double check that you have _both_ unchecked?

**Comment by polys** [comment]
I don't see why "Start Docker Desktop when you log in" has anything to do with this, but I do have it enabled.
I want Docker Desktop to run on startup, but don't what the dashboard to show up.
What I'm asking here is to also stop it from showing up when I manually restart Docker Desktop, not my laptop.

**Comment by MihaelaStoica** [comment]
This has been fixed in Docker Desktop [4.27.2](https://docs.docker.com/desktop/release-notes/#:~:text=to%20light%20mode.-,4.27.2,-2024%2D02%2D08)
