### ISSUE TITLE
Docker container cannot start and exit automatically

### ISSUE THREAD

**Issue by tingting081** [docker/for-win#13103]
Hi Tech,

I ran an Image "maestsi/metontiime" and established a container in a docker on our lab computer. I started the container, but it quickly exited automatically. I uninstalled and reinstalled. The issue persists. However, the docker container runs good in my personal laptop.

May I ask how I can solve this problem?

Thanks,
Tingting

**Comment by luismendes070** [comment]
Install Windows Subsystem for Linux in the Microsoft Store

https://devblogs.microsoft.com/commandline/the-windows-subsystem-for-linux-in-the-microsoft-store-is-now-generally-available-on-windows-10-and-11/
