### ISSUE TITLE
GPU doesn't work in docker but works in WSL host.

### ISSUE THREAD

**Issue by ch3rub1m** [docker/for-win#13100]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
docker run --rm -it --gpus=all nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -gpu -benchmark
Error: only 0 Devices available, 1 requested.  Exiting.

### Expected behavior
Get correct response.

### Information

  - Windows Version: Windows 10 Home 22H2 19045.2251
  - Docker Desktop Version: v4.14.1
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0002: does the bootloader have virtualization enabled?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?
No fatal errors detected.

### Steps to reproduce the behavior
  1. docker run --rm -it --gpus=all nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -gpu -benchmark
 
I have installed Nvidia Driver in windows, and cuda, cudnn in WSL, and it works well without docker.
However, if I run cuda-sample in docker it fails.
it's wired that I ran the nvidia-smi in docker it can get the information of GPU. But cuda-sample fails.
In another case, Tensorflow reports: CUDA_ERROR_NO_DEVICE and kernel driver is not found.
Tried many solutions many times.

**Comment by jkovacs-dev** [comment]
I am having the same issue.  Windows driver version 531.29.  Works fine in WSL, but attempting to start any docker containers which use the GPU just hang.  Have re-installed docker desktop multiple times, re-installed the nvidia driver multiple times, (even downgrading to an earlier version) nothing seems to work.

**Comment by jkovacs-dev** [comment]
Uploaded Diagnostics.  Diagnostic ID: 0B5D7290-7805-4106-992C-86FB8A9B967C/20230323025344

**Comment by vovea** [comment]
> I am having the same issue. Windows driver version 531.29. Works fine in WSL, but attempting to start any docker containers which use the GPU just hang. Have re-installed docker desktop multiple times, re-installed the nvidia driver multiple times, (even downgrading to an earlier version) nothing seems to work.
> 
> /remove-lifecycle stale

I had the same issue yesterday. When adding the '--gpus all' flag, the container would never come up. What broke it for me was updating Docker Desktop to 4.17.1. After downgrading to 4.17.0 it started working again.

**Comment by nicks** [comment]
i think the 4.17.1 issue is different than this report, and being tracked here: https://github.com/docker/for-win/issues/13324
