### ISSUE TITLE
Typo in diagnose.exe ouput "sstem" instead of "system"

### ISSUE THREAD

**Issue by AbitFishy** [docker/for-win#13107]
- [ x] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics (I think it's not needed in this situation)
  - Diagnostics ID:

### Actual behavior

Run command in powershell `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe"`
Last line of output reads:
> If -path is specified, place the diagnostics bundle in that directory. Otherwise the **_sstem_** default temporary directory will be used.

Bold and italic by me

### Expected behavior

The word "sstem" I believe should be "system"

### Information

  - Windows Version: Windows 10 Home 22H2
  - Docker Desktop Version: 4.14.1 (91661)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Steps to reproduce the behavior

  1. Run command `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe"` in powershell

**Comment by trungutt** [comment]
@AbitFishy Thanks a lot for spotting that
