### ISSUE TITLE
Unable to install Docker Desktop 4.15.0

### ISSUE THREAD

**Issue by Mishiacode** [docker/for-win#13114]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by JohnCOsborne** [comment]
I am having issues installing 4.15 as well -- with both WSL and Hyper V


![db8a5cd6-cda6-4a46-babd-77f3035765bb](https://user-images.githubusercontent.com/14142986/212346572-17620acb-0cb9-4be1-9d12-8126700fac93.jpg)
