### ISSUE TITLE
Installing extensions fails

### ISSUE THREAD

**Issue by armpogart** [docker/for-win#13119]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `0A68724E-887B-49BF-BAAB-6D709A480C98/20221210163714`

### Actual behavior

While trying to install any extension from desktop app, I get error message: `Failed to install extension: the local image you are trying to install has been modified and is different from the published image IMAGE_NAME`

### Expected behavior

Expecting extension to be installed successfully

### Information

  - Windows Version: Windows 10 22H2 (build 19045.2311)
  - Docker Desktop Version: 4.15.0 (93002)
  - WSL2 or Hyper-V backend?  WLS2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

```shell
[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0002: does the bootloader have virtualization enabled?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?
No fatal errors detected.
```

### Steps to reproduce the behavior

  1. ...
  2. ...

### Additional info
Tried to uninstall Docker Desktop and install latest (mentioned) version again and it doesn't help.

**Comment by revinant2121** [comment]
I ran into this problem as well after a few hours looking at the structure of the program on my system ive identified the problem as a mismatch between the local extension config files and what it finds when it refrences the internet for the extensions i fixed this issue by removing all of the docker related config files as well as all config files related to kubrenetes than uninstalling and reinstalling docker desktop i need to check functionality but it looks like its working so far will update after ive confirmed full functionality has been restored

**Comment by revinant2121** [comment]
After reviewing functionality in my docker desktop image it seems as though everything is up to spec i dont know if my solution will help everyone with this problem but it may be a good solution as for the devs it may be in your best intrest to add removing the config files to the uninstall script to stop issues like this in the future
