### ISSUE TITLE
Secrets bug known from earlier Docker version

### ISSUE THREAD

**Issue by 1605200517** [docker/for-win#1312]
Exactly same behaviour as in:
https://github.com/moby/moby/issues/32822

with

Version 17.09.0-ce-win33 (13620)
Channel: stable
8c56a3b

**Comment by thaJeztah** [comment]
Can you post a minimal docker-compose file to illustrate the problem?

Note that the issue you linked to was due to an incorrect docker-compose file (i.e, the secret was not defined in the compose file), and the fix was to improve the error message

**Comment by thaJeztah** [comment]
let me close this one, as no additional info was provided
