### ISSUE TITLE
High 100% (CPU wv-process) usage on W10 with last version of Docker w/o any app running!

### ISSUE THREAD

**Issue by andy-soft** [docker/for-win#13133]
Hello just installed docker, on the last version into w10
after trying the hello world, and deleting the docker file, unmounting everything, I noted my CPU was strangely slow, I have AMD Zen 6 vCPUs  (12 threads) 
I dug around and found a vmmem process (displayed in red by Process Explorer by Mike Russinovich)
The process was protected, so I could not stop it
Susp[ecting Ransomware o r VIRUS, it was not there, so I uninstalled docker, and the process was gone!

Processor	AMD Ryzen 5 2600 Six-Core Processor               3.40 GHz
Installed RAM	16,0 GB
System type	64-bit operating system, x64-based processor
Edition	Windows 10 Pro
Version	21H2
Installed on	‎29/‎1/‎2021
OS build	19044.2364
Experience	Windows Feature Experience Pack 120.2212.4190.0
Processor	AMD Ryzen 5 2600 Six-Core Processor               3.40 GHz
Installed RAM	16,0 GB
System type	64-bit operating system, x64-based processor

WTF happens with the docker installation on Windows 10

**Comment by cimchd** [comment]
Same here with Docker Desktop v14.15.0 on Windows 11 (Intel i7 CPU). I limited my RAM to 32GB with .wslconfig (64 RAM in total) and it consumes all 32GB after some time, especially when I run docker compose build.

**Comment by cforce** [comment]
Similar and more temporary issue on my machine as well..  CPU consumption is in no relation to the task 


>wsl --status --debug
Default Distribution: Ubuntu
Default Version: 2

>wsl --version
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.2486


```
[wsl2]
memory=16GB
#processors=2
nestedVirtualization=true
localhostForwarding=true
debugConsole=true
pageReporting=true
kernelCommandLine=intel_iommu=on iommu=pt kvm.ignore_msrs=1 kvm-intel.nested=1 kvm-intel.ept=1 kvm-intel.emulate_invalid_guest_state=0 kvm-intel.enable_shadow_vmcs=1 kvm-intel.enable_apicv=1
swap=0

[network]
#generateResolvConf = false

[interop]
enabled = true
appendWindowsPath = false

# Automatically mount Windows drive when the distribution is launched
[automount]
crossDistro = true
enabled = true
root = /

```
