### ISSUE TITLE
Docker desktop crashes on startup. WSL Distribution docker-desktop is missing

### ISSUE THREAD

**Issue by Andrewdee92** [docker/for-win#13140]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Docker Desktop crashes on start up. 

Running the docker diagnose tool suggests that the WSL2 is enabled and installed however the WSL Distribution docker-desktop is missing.

Running a wsl -l -v command shows that no distributions are installed. 

Docker diagnose log attached. 

### Information

  - Windows Version: Microsoft Windows 10 Professional Version	10.0.19045 Build 19045
  - Docker Desktop Version: Docker version 20.10.21, build baeda1f
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Virtual Machine

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

[dockerdiagnoselog.txt](https://github.com/docker/for-win/files/10296238/dockerdiagnoselog.txt)

**Comment by dkijkuit** [comment]
This happened to me on a fresh install of Windows. I didn't install WSL manually but I did choose to install docker-desktop with wsl support. After the install of docker-desktop it wouldn't start showing the exact same message as you got. I found out WSL didn't have any distro's installed. So I installed Ubuntu manually. On startup I got the message thatbthe kernel was outdated so I updated the kernel using: 

[https://learn.microsoft.com/en-us/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package](url)

Then WSL would start working properly again. I re-installed docker-desktop, rebooted the machine and now it works.
