### ISSUE TITLE
'operation not permitted' on mounted folder if container is start by other users

### ISSUE THREAD

**Issue by nerotix** [docker/for-win#13155]
### Actual behavior
I'm having a weird issue with Docker for Windows. If another user connects to the container that I ran (docker run) with the mounted folder from Windows, they are unable to do things to that folder inside the container, for example a simple 'ls' command says 'operation not permitted'. To further clarify, I ran the following command to deploy a container:

`docker run --name test -ti -d -v D:\docker_share:/docker_share kalilinux/kali-rolling`

Me and others are able to access everything inside the docker container and everyone can also do 'ls' or create files in that shared folder. However, when I log off or reboot/shutdown the system, and another user open Docker Desktop (starts the container that I created with the docker run command), the container will automatically start again (as intended) but now when a user tries to access the same shared folder within the container, they get 'operation not permitted' errors, even a simple 'ls' command gives the error.

So in short; if I created the container with a mounted shared folder, but someone else starts the container, no one can anything on the mounted shared folder inside the container. If they stop the container and I start it again (the creator of the container), everything works as intended.

I've tried multiple things, --mount instead of -v, changing permissions of the shared folder on the host (Windows). Nothing seems to change anything.

So an extra example:

> user1 creates the container with the docker run command as shown above
> user1 stops the container
> user2 starts the container
> user2 or user1 tries to 'ls -la' inside the container on the mounted folder
> user2 or users1 receives error 'operation not permitted'

### Expected behavior
Everyone able to use the shared mounted folder within the container, regardless of who started the container.

### Information
Docker Desktop is running on Windows 2019 version 1809 (Build 17753).
Using WSL1 since WSL2 isn't available for this build of Windows.

### Steps to reproduce the behavior
1. create a folder and use a 'docker run' command (as shown above) that mounts that folder within the container (I tried -v and --mount);
2. stop the container and start it with a different user that executed the 'docker run' command;
3. bash into the container as a different user that executed the 'docker run' command;
4. perform the 'ls -la' command and you should receive the error 'operation not permitted'.

**Comment by Asisranjan** [comment]
Hi @nerotix 
how do you fix this issue

Thanks
Asisranjan Nayak
