### ISSUE TITLE
Issue starting Docker (17.09.0-ce-win33 (13620)) on Windows 10 Pro x64

### ISSUE THREAD

**Issue by CardcaptorRLH85** [docker/for-win#1315]
### Expected behavior
Docker starts.
### Actual behavior
Docker fails with the following error:
```
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID 6A4EBD9D-301B-4003-AD0B-FE95BCE07952)

'MobyLinuxVM' failed to start worker process: %%3228369022 (0xC06D007E). (Virtual machine ID 6A4EBD9D-301B-4003-AD0B-FE95BCE07952)
at Start-MobyLinuxVM, <No file>: line 291
at <ScriptBlock>, <No file>: line 386
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 246
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 182
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
```
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
`C73C7219-C289-4F4D-A62D-037655584702/2017-11-11_22-29-33`
  - Windows 10 Pro 1709 (OS Build 16299.19) 64-bit

### Steps to reproduce the behavior

I can't be certain that the issue on my _other_ system is with Docker or the Insider Preview version of Windows on that system (Windows 10 Pro 1709 build 17025.1000 64-bit) but, this issue is reproducible there (Diagnostic ID: 66B8A284-F379-48FD-A489-A918E764542C/2017-11-11_22-48-22) by simply installing Docker and having it try to start its VM.

**Comment by rawveg** [comment]
I have precisely this issue myself too. 

Diagnostic ID: 83289F63-9ACC-47D9-8856-572FE85FDB5E/2017-11-13_09-30-48

**Comment by dylanBehetre** [comment]
Same : 

Diagnostic ID : 901D1485-A892-41DF-8B6F-51A7C171AF99/2017-11-14_09-28-54

**Comment by mirro-orrim** [comment]
Same here:

Diagnostic ID: 2CE7997E-A810-4894-AAB2-E3F51B0E057E/2017-11-22_14-55-40
...
Version: 17.09.0-ce-win33 (13620)
OS: Windows 10 Pro
Id: 1709
Build: 16299
BuildLabName: 16299.15.amd64fre.rs3_release.170928-1534

**Comment by mirro-orrim** [comment]
For me, it was a Sophos issue:

https://community.sophos.com/products/intercept/early-access-preview/f/intercept-x-for-windows/97613/hyper-v-do-not-start-virtual-machines-windows-10-pro-1709/356481#pi2151=1

**Comment by CardcaptorRLH85** [comment]
I like Sophos but, their logging leaves much to be desired.  If it's blocking something, why am I not being informed?  Thanks for the info mirro-orrim, this fixed my issue as well!
