### ISSUE TITLE
Docker not loading

### ISSUE THREAD

**Issue by tigerwillca** [docker/for-win#13175]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by tigerwillca** [comment]
docker not loading

**Comment by p1-0tr** [comment]
Hi @tigerwillca , sorry for any inconvenience you may be encountering. The information provided in the ticket is insufficient to debug. So I'm closing it. However this issue may be related to - https://github.com/docker/for-win/issues/13184 . If that is not the case, please follow instructions here - https://docs.docker.com/desktop/troubleshoot/overview/#diagnose-from-the-terminal - and reopen this ticket with diagnostics, or open a new one.
