### ISSUE TITLE
Windows10 Shared Drivers Unable to mount C drive: firewall is blocking

### ISSUE THREAD

**Issue by pptztf** [docker/for-win#1317]
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. docker -> Settings...-> Shared Drivers
  2. checked "C"dirve
  3. Apply
  4.
![20171114025306](https://user-images.githubusercontent.com/12016294/32743324-08981bb4-c8e7-11e7-8d31-d6c23c44ca3e.jpg)

**Comment by knieschraube** [comment]
Same issue.

**Comment by jasonbivins** [comment]
Hi @pptztf 
This could be caused by a few things - see here for troubleshooting tips

https://success.docker.com/article/Error-_A_firewall_is_blocking_file_sharing_between_Windows_and_the_containers

**Comment by pptztf** [comment]
I found the cause of the problem, the problem of the setup, In my local security policy of IPSec ,I disabled the port 445.
