### ISSUE TITLE
Containers page showing "An error occured." after the last container stopped :)

### ISSUE THREAD

**Issue by AntonTrapp** [docker/for-win#13185]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6E345532-9D13-4FD2-AC4C-269EBE0383D9/20230121053813

### Actual behavior

If I stop all containers the containers page in docker desktop shows "an error occured".

### Expected behavior

On the containers page: show an empty page or show something like "no containers running" when all are stopped.

### Information

Starting Docker Desktop, it's showing some containers, some running, some not, everything fine. When I stop the containers (from a wsl2 session) after the last container the error message popus up.

So: It's just the wrong text - could probably confuse new users who could start to search for issues...

  - Windows Version: 22H2 / 22621.1105
  - Docker Desktop Version: v4.15.0
  - WSL2
  - Windows running natively on a AMD Ryzen

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

```
...
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?
No fatal errors detected.
```

### Steps to reproduce the behavior

Just an example:

  1. kubernetes with k3d in wsl2, start cluster
  2. open Docker Desktop, showing the containers
  3. stop the container
  4. Docker Desktop will show the correct status until the last container has stopped, after that "An error occured."

**Comment by trungutt** [comment]
Hi @AntonTrapp would you mind trying out the latest version (4.16.2) to see if this issue persists?
