### ISSUE TITLE
One container thinks the port is in use on startup.

### ISSUE THREAD

**Issue by knipper6554** [docker/for-win#13189]
This container, mapped to port 82, will not start unless I change the port to something besides 82, bring the container up, then change it back to 82, and restart container and everything is happy, until next start.  

It's an annoyance since I have a workaround but I would like to fix it.

The container thinks port 82 is in use but it's not.  If it was, my workaround would not work.

**Comment by trungutt** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place.
Thanks
