### ISSUE TITLE
Cannot run apt-get update on Windows 11

### ISSUE THREAD

**Issue by tadashi-seprev** [docker/for-win#13195]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: ED0D3757-33C2-49DC-800D-2AE7E71B3F9E/20230126115500

### Actual behavior
Upon building a container using a Dockerfile, when the command "apt-get update" is run, I get a series of errors, like the following on Debian buster:
#0 0.179 Err:1 http://deb.debian.org/debian buster InRelease
#0 0.179   403  Forbidden [IP: 199.232.114.132 80]
#0 0.192 Err:2 http://deb.debian.org/debian-security buster/updates InRelease
#0 0.192   403  Forbidden [IP: 199.232.114.132 80]
#0 0.205 Err:3 http://deb.debian.org/debian buster-updates InRelease
#0 0.205   403  Forbidden [IP: 199.232.114.132 80]
#0 0.207 Reading package lists...
#0 0.211 E: The repository 'http://deb.debian.org/debian buster InRelease' is not signed.
#0 0.211 E: Failed to fetch http://deb.debian.org/debian/dists/buster/InRelease  403  Forbidden [IP: 199.232.114.132 80]
#0 0.211 E: Failed to fetch http://deb.debian.org/debian-security/dists/buster/updates/InRelease  403  Forbidden [IP: 199.232.114.132 80]
#0 0.211 E: The repository 'http://deb.debian.org/debian-security buster/updates InRelease' is not signed.
#0 0.211 E: Failed to fetch http://deb.debian.org/debian/dists/buster-updates/InRelease  403  Forbidden [IP: 199.232.114.132 80]
#0 0.211 E: The repository 'http://deb.debian.org/debian buster-updates InRelease' is not signed.

### Expected behavior
Successful completion of apt-get update

### Information
This issue presents itself on two different machines running Windows 11. On Windows 10, apt-get update runs normally.
An additional information is that my network has a firewall with SSL inspection. However, I believe that if the SSL inspection was the root cause of the issue, it should arise on Windows 10 as well.

  - Windows Version: Windows 11 Pro Version 22H2 Build 22621.1105
  - Docker Desktop Version: 4.16.2
  - WSL2 or Hyper-V backend?  Hyper-V (same issue using WSL2 backend)
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Running on physical desktop

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
[2023-01-26T12:07:23.387978800Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0020: is the Hyper-V Windows Feature enabled?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0038: is the connection to Docker working?
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0020: is the Hyper-V Windows Feature enabled?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?
No fatal errors detected.

### Steps to reproduce the behavior
Simple Dockerfile for reproduction:

FROM debian:10
SHELL ["/bin/bash", "-c"]
RUN apt-get update

**Comment by keifgwinn** [comment]
I believe it is your ssl inspection, as it's denying requests on http. I couldn't replicate and I don't have any firewalls inspecting.
```

❯ docker run -it debian:buster bash -c 'apt-get update; apt-get upgrade -y'
Unable to find image 'debian:buster' locally
buster: Pulling from library/debian
ac7f2e1c7586: Pull complete
Digest: sha256:bb8c62f9f540a5f5f49f7ed5caae0e2889f999cd14553f2aaccaf1fa4fcb998d
Status: Downloaded newer image for debian:buster
Get:1 http://deb.debian.org/debian buster InRelease [122 kB]
Get:2 http://deb.debian.org/debian-security buster/updates InRelease [34.8 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [56.6 kB]
Get:4 http://deb.debian.org/debian buster/main amd64 Packages [7909 kB]
Get:5 http://deb.debian.org/debian-security buster/updates/main amd64 Packages [425 kB]
Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [8788 B]
Fetched 8556 kB in 7s (1217 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  libtasn1-6
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 52.0 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://deb.debian.org/debian-security buster/updates/main amd64 libtasn1-6 amd64 4.13-3+deb10u1 [52.0 kB]
Fetched 52.0 kB in 1s (42.0 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
(Reading database ... 6677 files and directories currently installed.)
Preparing to unpack .../libtasn1-6_4.13-3+deb10u1_amd64.deb ...
Unpacking libtasn1-6:amd64 (4.13-3+deb10u1) over (4.13-3) ...
Setting up libtasn1-6:amd64 (4.13-3+deb10u1) ...
Processing triggers for libc-bin (2.28-10+deb10u2) ...
```

**Comment by MMarsch** [comment]
I am having the same issue. 

Windows 10 Enterprise
version 22H2
build 19045.2486

**Comment by kolserdav** [comment]
I also have this problem in Windows 10 Pro.
