### ISSUE TITLE
Dockey Desktop on windows after install coming ...Desktop stopped

### ISSUE THREAD

**Issue by sravanilearner** [docker/for-win#13193]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by sravanilearner** [comment]
Diadnostics ID - 16F473D1-80FE-41F6-94B9-5490717FF1FC/20230125005941
using a VM( windows)
windows 10
 64-bit
docker desktop version downloaded is 20.10.22

**Comment by todorinskiz** [comment]
See https://github.com/docker/for-win/issues/13184

**Comment by mat007** [comment]
Possibly a duplicate of #13165?
