### ISSUE TITLE
Docker Failed to initialize 

### ISSUE THREAD

**Issue by YoushaKhan** [docker/for-win#13194]
I am using Docker version 20.10.17, build 100c701 on windows 10.

![docker](https://user-images.githubusercontent.com/86527559/214768122-ac688cc6-6e59-4e32-8dd9-121cbc9573fa.png)

Docker fail to initialize. I have seen many resolution steps to  solve this problem but why docker wsl-2 daemon stop working and docker fail to initialize  I have encountered this problem many times even though it is resolve I need to know what cause this error

**Comment by Usama-Tariq4312** [comment]
Hi, i have encountered same problem many time but there is no satisfying answer for why docker deamon expires. in your case i guess this MCAFEE antivirus running on back can cause docker deamon to expire

**Comment by todorinskiz** [comment]
See https://github.com/docker/for-win/issues/13184
