### ISSUE TITLE
Setting the proxy inside a container doesn't give internet access

### ISSUE THREAD

**Issue by ovidiub13** [docker/for-win#1319]
### Expected behavior
Internet access available.

### Actual behavior
No internet access available.

### Information

 - Host: Windows Server 2016 Datacenter
 - Docker version: 17.09.0-ce-win33 (13620)

### Steps to reproduce the behavior

 1. Docker engine is set with the proxies in the format: `http://<domain>:<port>` from the Proxies tab.
 2. Starting a container with the command: `docker run --rm -ti microsoft/windowsservercore:10.0.14393.1770 powershell.exe`
 3. Setting the proxy with any (all) of the commands:
    - `set HTTP="http://<domain>:<port>"`
    - `set HTTPS="https://<domain>:<port>"`
    - `netsh winhttp set proxy proxy-server="http=http://<domain>:<port>;https=http://<domain>:<port>"`
 4. Testing for internet access: ` Invoke-WebRequest -Uri https://dist.nuget.org/win-x86-commandline/v4.1.0/nuget.exe  -OutFile C:\nuget.exe`

**Comment by yooakim** [comment]
Did you try to ping an external IP?, not using Invoke-WebRequest ?

**Comment by ovidiub13** [comment]
I tried. I get a timeout.

**Comment by yooakim** [comment]
Not sure if this is relevant but the DNS cache in Windows is agressive so within the image it is a good practice to disable the Windows DNS Cache. 
```PowerShell
Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters' -Name ServerPriorityTimeLimit -Value 0 -Type DWord
```

**Comment by ovidiub13** [comment]
The DNS get's resolved, because it uses the DNS that Docker provides. When I try to ping something, the domain get's resolved, but the destination does not get reached.

**Comment by friism** [comment]
cc @kallieb

**Comment by ovidiub13** [comment]
Any news on this?

**Comment by HendrikFW** [comment]
I'm facing the same issue.

**Comment by aemery** [comment]
dogtail9's fix here worked for me: https://forums.docker.com/t/connect-to-the-internet-from-a-windows-container-behind-a-http-proxy/41307/8

I think that it should be supported by Docker without the user having to modify the registry by hand. While the workaround works, it's still not a production level solution in my opinion.

**Comment by EMCP** [comment]
Facing same issue, and would love to see this work in the nanoserver as well.. seems the workaround described is only for the beefier 10GB containers

**Comment by vkopichenko** [comment]
Why was this issue silently closed?

**Comment by ovidiub13** [comment]
It wasn't silently. M$ made it absolutely clear that they don't care about this. From what I gather, this is not a Docker problem but a Windows problem. Most CLI apps (commands) don't have support of a global proxy setting, and you need to manually specify the proxy to each command.
