### ISSUE TITLE
Docker Desktop API proxy high CPU usage

### ISSUE THREAD

**Issue by AzuNoldus** [docker/for-win#13201]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
com.docker.proxy.exe is constantly using around 12% CPU on my laptop. Then fans go nuts. The proxy in Docker Desktop is not enabled.
### Expected behavior
No CPU is used when docker is idle. What is thus API proxy and how to switch it off?
### Information

  - Windows Version: 11 Pro; 22H2; OS build 22621.1194
  - Docker Desktop Version: 4.16.2 (95914)
  - WSL2 or Hyper-V backend?  Running windows containers
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No.
  - 
- Not sure if it is reproducible. 
- The problem is new to me.
- Just installed the latest version of Docker Desktop.
### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
PS C:\Program Files\Docker\Docker\resources> .\com.docker.diagnose.exe check
[2023-01-30T10:46:07.943714200Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0002: does the bootloader have virtualization enabled?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.checkWindowsFeature({{0x149b9c2?, 0xc0004ee0a0?}, {0x149b9c2?, 0xc0004ee040?}})
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/features_windows.go:19 +0x1d9
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.glob..func6()
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/dockerd_windows.go:11 +0x35
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1a4b640)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.Run.func1(0x1a4b640)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x4?, 0x1a4b640)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:142 +0x77
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x3, 0x1a4b640, 0xc00059f728)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:151 +0x87
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x1a4b4c0, 0xc00059f728)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1a4b540, 0xc00059f728)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x1a4bcc0, 0xc00059f728)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkOnce(0x13de8a0?, 0xc00035f890)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:137 +0xcc
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.Run(0x1a4bcc0, 0x93bd065400000010?, {0xc00035fb20, 0x1, 0x1})
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:16 +0x1d4
main.checkCmd({0xc0001163b0?, 0xc0001163b0?, 0x4?}, {0x0, 0x0})
        github.com/docker/pinata/common/cmd/com.docker.diagnose/main.go:138 +0x105
main.main()
        github.com/docker/pinata/common/cmd/com.docker.diagnose/main.go:102 +0x27f
### Steps to reproduce the behavior

  1. Install Docker Desktop
  2. Switch to Windows containers
  3. Observer high CPU usage by Docker Desktop API proxy.

**Comment by m1lhaus** [comment]
Hi @AzuNoldus, I faced exactly the same issue today on a clean PC. It turned out that the deamon was not running and this was just a side effect. It turned out that Windows features Container and HyperV were not enabled. That latter might not be needed, but I remember I always had both of them turned on in past. Once I turned them on, restarted PC, all works. 

I also remember that docker desktop showed a dialog first time you switched to Windows container on a fresh PC saying something about some Windows features must be enabled, you clicked ok and then you had to restart your PC. This didn't happen this time. I had to only logout (probably due to docker-users group) and that was it. Maybe that is the regression, who knows :-/

**Comment by AzuNoldus** [comment]
Hi @m1lhaus,
I indeed did not have the Containers feature enabled on my new machine... Enabled that fixed the issue.

Strange that after couple of times of reinstalling Docker Desktop I also kind "fixed" the high CPU problem. However when it updated to 4.16.3 the problem surfaced again.
Anyways, thanks!
