### ISSUE TITLE
WSL integration with distro Ubuntu unexpectedly stopped with exit code 1

### ISSUE THREAD

**Issue by Flygrounder** [docker/for-win#13202]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: F7FA35B7-4B3F-496F-9150-E929F097EDF5/20230130100547

### Actual behavior
Sometimes when I use `docker ps` I get a notification "WSL integration with distro Ubuntu unexpectedly stopped with exit code 1. Do you want to restart it?". If I press "Restart", it starts working again for some time. If I don't, any further docker commands fail to connect to docker socket. 
Some observations:
1. `docker ps` command, that triggers this, succeeds.
2. docker commands in PowerShell work, so it seems to be just WSL integration problem.  

### Expected behavior
WSL integration should always work.

### Information

  - Windows Version: 11 with all available updates installed.
  - Docker Desktop Version:  4.16.2 (95914)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
<details>
[2023-01-30T10:15:14.377299900Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0002: does the bootloader have virtualization enabled?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0038: is the connection to Docker working?
[FAIL] DD0014: are the backend processes running? 1 error occurred:
        * com.docker.wsl-distro-proxy.exe is not running

[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?

Please investigate the following 1 issue:

1 : The test: are the backend processes running?
    Failed with: 1 error occurred:
        * com.docker.wsl-distro-proxy.exe is not running

Not all of the backend processes are running.
</details>

### Steps to reproduce the behavior

  1. Start computer and wait for a while
  3. Run `docker ps`

**Comment by codebymikey** [comment]
Similar issue. Diagnostics ID: 24AF0EF3-7B29-4AD0-B9EA-EDA52FD83BC7/20230131141930

**Comment by resried** [comment]
I have something similar, whenever my network changes (Host-IP-Adress or just Network disconnect, not 100% sure). 
Also, Bug #13222 might be the same problem.

**Comment by intositeme** [comment]
Am also having the same issue, but happens every 5-10mins.

**Comment by codebymikey** [comment]
This might be related to a breaking change from running `wsl --update` and going up to 1.1.0, resulting in certain ports disconnecting after a while.

I eventually uninstalled Docker for Windows, downgraded back to 1.0.3, and I'm now running Docker directly from inside the distro. Downgrading also addressed some of my high CPU usage issues.

https://github.com/microsoft/WSL/issues/9508#issuecomment-1412614502

**Comment by intositeme** [comment]
> Currently on 1.0.3.

Ended up running docker directly from inside distro as well, so far 12hrs and it's still up.

**Comment by p1-0tr** [comment]
hi @Flygrounder and @codebymikey , thanks for reporting your issue and sorry for the inconvenience. Having inspected the attached diagnostics I believe the host name set in your WSL distro is causing DD to erroneously terminate the integration. I've prepared a fix for this issue. If you are willing to give a dev build a go this - https://desktop-stage.docker.com/win/main/amd64/97769/Docker%20Desktop%20Installer.exe - build contains the fix. Please let me know if it helps.

**Comment by p1-0tr** [comment]
hi @codebymikey 

> I'm curious though, which host name in particular was causing the issue?

`-` and `desktop` among others.

> And is there a reason you're not part of the @docker organization? It initially made me wary of installing the binary you linked to since you weren't flagged as a maintainer 😅

Hmm, good question, I am part of the org, perhaps something about my profile settings is preventing it from being displayed. I'll check. Thanks for bringing that to my attention :)

**Comment by chaizeg** [comment]
Closing this issue because a fix has been released in Docker Desktop `4.17.0` . See the [release notes](https://docs.docker.com/desktop/release-notes/) for more details.

**Comment by azern32** [comment]
I got the same problem too

![Image](https://github.com/user-attachments/assets/0228996c-346b-48bd-bdb8-5f539a6ce8e8)

![Image](https://github.com/user-attachments/assets/00e3ccf4-080d-45b5-b96f-118cfc7bcfac)
The problem start after I did an upgrade for the docker desktop yesterday

**Comment by YuraGB** [comment]
@azern32 
> [@zingmars](https://github.com/zingmars) try command
> 
> ```
> wsl -l -v
> ```
> 
> to figure out the default distro and its vesions, for me the docker-desktop distro was correct wsl version, but wasnt default. and then change default distro to docker-desktop
> 
> ```
> wsl -s docker-desktop
> ```
