### ISSUE TITLE
Windows 10 MySQL docker image not creating host volume defined in -V 

### ISSUE THREAD

**Issue by davoutuk** [docker/for-win#1321]
I'm trying to start up a Docker container on my Windows 10 desktop that links a volume to a folder on my 'D' drive.

The docker-compose.yml file...

`version: '4'

services:  
  # Name of the service as Docker will reference.
  mysqlDb:

    image: mysql:latest

    environment:
      MYSQL_ROOT_PASSWORD: "pascal01"
      MYSQL_DATABASE: "eis-swot"

    ports:
      - 3306:3306

    volumes:
      - d:/ian/data/eis-swot:/var/lib/mysql
      
      `
Every starts ok, but the D drive folder is empty.  Any ideas how to fix this??

**Comment by johnrom** [comment]
@davoutuk I just happened past this, and if you are using Docker for Windows in "Linux Containers" mode, you should use:

```
volumes:
  - /d/ian/data/eis-swot:/var/lib/mysql
```

You can tell you are in Linux Container mode by right-clicking the Docker icon in your toolbar, and one of the options should say "Switch to Windows Containers"
