### ISSUE TITLE
fashing on windows 11

### ISSUE THREAD

**Issue by tomgor** [docker/for-win#13225]
I am runing docker desktop on win11, I got a prop: my screen will flashing all time in which  windows i focused, that cause I can't type in IDEA  or other editor, I lost my  cursor sometime, someone who can tell me what happend?

**Comment by kevinpearce** [comment]
Agree with the Flashing statements - completely unusable.
It seems to take precedence away from the window being worked in = impossible to type, doesn't matter which other software is being used.
Same effect whether Docker Desktop minimised to tray or displayed.

Havent used Docker Desktop before, current setup = Win10 (using WSL2, not HyperV)
First installed @ 4.16.2 - came here and saw reports of issues so rolled back to 4.15.0.
Both show same issues.
