### ISSUE TITLE
Cannot run container using a port used by windows

### ISSUE THREAD

**Issue by franzmoca** [docker/for-win#13229]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: ADE3F616-E27A-4F58-8006-E724DF2DEF70/20230207154910

### Actual behavior
I try to start a container using a port already used on my windows system (e.g. postgresql), the container exits immediately with an error (e.g. could not bind IPv4 address "0.0.0.0": Address already in use )

### Expected behavior
I expect the container to start successfully even if the port on windows is already used

### Information
Previously this was working correctly, now to properly start a postgres db on docker I have to shutdown the windows service first. I didn't notice when exactly it stopped working, so I don't know if this is caused by an update of Docker Desktop.
I also tried to disinstall and reinstall docker for desktop again without any success

  - Windows Version: 11 Pro (22621.1250)
  - Docker Desktop Version: 4.16.3 (96739)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
[2023-02-07T15:46:34.052872500Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0002: does the bootloader have virtualization enabled?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0038: is the connection to Docker working?
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?
No fatal errors detected.

### Steps to reproduce the behavior

  1.  Try to start a postgres contailer:
      docker run --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -d postgres
  2. The container exits unless I stop first the local postgres instance I have running on Windows.

**Comment by danchitnis** [comment]
This is also the root cause of the issue [here](https://github.com/docker/for-win/issues/13216). I verified by changing the RDP port on Windows from 3389 -> 3390, so it didn't conflict with xrdp 3389 inside the container. This is unexpected behaviour.

**Comment by franzmoca** [comment]
Version 4.17.0 seems to have fixed the issue

**Comment by Hassan-Adel** [comment]
it happened with as well I got for PostgresQL on Docker: 4.17.0
