### ISSUE TITLE
Support Unattended/Silent Installation

### ISSUE THREAD

**Issue by brandonroyal** [docker/for-win#1322]
### Expected behavior
Be able to install Docker for Windows using a unattended/silent installation process.

```
C:\> Docker_for_Windows.exe /qn
```

For enterprise customers deploying Docker for Windows, there is no automated deployment capability.  This is an issue for customers looking to centrally manage client software deployments.

### Actual behavior
Not currently supported

### Impact
Liberty Mutual

**Comment by grumpydev-net** [comment]
+1

**Comment by jasonbivins** [comment]
For the .exe installer you can use "Docker for Windows Installer.exe" install --quiet
I haven't found any other options for this one
The .mis installer has install flags that are documented if you right click the installer itself and choose properties

**Comment by krtrego** [comment]
"Docker for Windows Installer.exe" /SILENT
and
"Docker for Windows Installer.exe" /VERYSILENT

will both do unattended installs.

"Docker for Windows Installer.exe" /?
Will output the available command line parameters.

**Comment by chriskuech** [comment]
@jasonbivins suggestion works; however, how can we customize the installation?  I can't seem to find any documentation on the exe's arguments.  Example switches I would like: whether to autoreboot, whether to use linux or windows containers, etc.

**Comment by speculatrix** [comment]
I'm writing a simple (hopefully) puppet module to install Docker CE on Windows Server 2016 x64, but of course when the MSI starts it demands interactive input.
I'd really love to know all the installation parameters I can use to fully automate the MSI.

**Comment by speculatrix** [comment]
p.s. I tried looking at the properties of the MSI and there was nothing of interest. here's what I see if I run manually:

C:\Windows\Temp>[17:46:10.394] [InstallHandler] No d4w installation found
[17:46:10.396] [InstallHandler] Using embedded package
[17:46:10.445] [InstallWorkflow] Using package: res:d4w
[17:46:10.446] [InstallWorkflow] Downloading
[17:46:12.281] [InstallWorkflow] Exracting manifest
[17:46:12.313] [InstallWorkflow] Checking prerequisites
[17:46:14.539] [InstallWorkflow] Prompting for optional features
[17:46:20.077] [InstallWorkflow] Rollbacking component LightweightInstaller.ExtractManifestStep
[17:46:20.078] [InstallWorkflow] Rollbacking component LightweightInstaller.DownloadStep

I tried command line parameters like -h --help /h /help but couldn't get anything sensible

**Comment by chriskuech** [comment]
FYI you shouldn't install CE on Windows Server, as Server gives away EE for free, and we've faced issues using CE on Server.

**Comment by jonstelly** [comment]
@chriskuech is there an equivalent for docker EE to the docker CE Edge release and does it have a similar release cadence?  I saw an anouncement about the docker EE beta for Kubernetes support, but it seems like it was a 1-off and was invite only.  I remember seeing some comment in a guide about installing a preview builds using the docker package provider, but the handful of times I checked it never had anything newer than stable.

I'm looking to set up a Server 2016 development environment since CE being limited to Hyper-V isolation is pretty painful (memory allocation and general build performance) but the EE stable releases seem to get pretty outdated with the rapid pace that Docker on Windows is moving.

Any guidance?

**Comment by cschertzmsft** [comment]
Wondering if anything is happening with this.   Need a good option to silent install and know when it is done.

**Comment by chriskuech** [comment]
Can this be reopened?  The need isn't any less than before

**Comment by speculatrix** [comment]
chriskuech+=1

**Comment by davelindquist-egistix** [comment]
After two years, we still do not have this feature?  This seems ridiculous...

This is a must-have for any environment that tries to script things -- for example, if you are setting up machines via saltstack.

Can we PLEASE have this added?

**Comment by NicolaFera** [comment]
Need this option also since we need to automate the installation on Docker and 40+ machines.

**Comment by whiteHeX** [comment]
+1 this really should be actioned for enterprise users deploying via SCCM.

**Comment by SleyAI** [comment]
+1
I need this aswell!

**Comment by stephen-turner** [comment]
We announced at the last DockerCon that this will be a feature of Docker Desktop Enterprise.

**Comment by bajjurisanthosh** [comment]
HI Stephen,

I am supposed not to comment on the closed issue, but we are actually trying to run the Docker msi with following arguments 
/quiet /norestart /IAcceptlicenseTerms
Can we able to get this added in the community edition?

**Comment by stephen-turner** [comment]
I am not a product manager and I'm not going to speculate on future features, but I will note that it's currently one of the main differentiating features in the enterprise edition.

**Comment by bajjurisanthosh** [comment]
> I am not a product manager and I'm not going to speculate on future features, but I will note that it's currently one of the main differentiating features in the enterprise edition.

Thanks for the quick response. Appreciate it!

**Comment by damienvanrobaeys** [comment]
I had the same issue. I have checked the commandlne used in the chocolatey package, see below:
https://chocolatey.org/packages/docker-desktop/2.0.0.3

You can display the ps1.
This one uses the following command: "install --quiet"

**Comment by speculatrix** [comment]
> > I am not a product manager and I'm not going to speculate on future features, but I will note that it's currently one of the main differentiating features in the enterprise edition.
> 
> Thanks for the quick response. Appreciate it!

"quick"? LOL!!

**Comment by damienvanrobaeys** [comment]
Scripted install is a feature of the Enterprise version :-(
https://github.com/docker/for-win/issues/3923

**Comment by jeromehains** [comment]
I don't know if that help but it work using Powershell. You just need to replace the $install_path and $log_path 

start-process -FilePath "$install_path\Docker for Windows Installer.exe" -ArgumentList "install --quiet" -RedirectStandardOutput "$log_path\docker.log" -Wait

**Comment by davelindquist-egistix** [comment]
I can confirm that the above "powershell" actually works for silent install.

You don't have to use powershell -- you can simply do:

`"Docker for Windows Installer.exe" install --quiet`

This works great for scripting from SaltStack, for example.

**Comment by prosndguy** [comment]
if you want to set the settings automatically you can overwrite the settings file:

C:\Users\WINUSER\AppData\Roaming\Docker\settings.json
