### ISSUE TITLE
windows hibernate triggers issues : command not found: docker  & ERROR: docker endpoint for "default" not found

### ISSUE THREAD

**Issue by cforce** [docker/for-win#13238]
Each time after hibernate i need to restart docker service so it works again and i don't get 
"command not found: docker". After docker restart in the same shell it starts to work.
The directly afetwards i get "ERROR: docker endpoint for "default" not found" when executing any docker cmd and i need to manually delete ctx metadata

e.g
 rm -r ~/.docker/contexts/meta/fe9c6bd7a66301f49ca9b6a70b217107cd1284598bfc254700c989b916da791e
 
>docker --version
Docker version 20.10.22, build 3a2c30b

>systeminfo | findstr /B /C:"OS Name" /B /C:"OS Version"
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19045 N/A Build 19045 

C:\temp> wsl --version
WSL version: 1.1.2.0
Kernel version: 5.15.83.1
WSLg version: 1.0.49
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.2486

**Comment by bjtho08** [comment]
I have the same issue. Are you perchance using the `Cisco AMP for Endpoints`/`Cisco Secure Client`?

**Comment by cforce** [comment]
No, i don't . The issue is related to hibernate/suspend - afterwards those issues are happening

**Comment by cforce** [comment]
Because of this bug - i started to migrate to  podman / podman desktop.
* https://podman.io/docs/installation
* https://podman-desktop.io/
