### ISSUE TITLE
Docker.Core.HttpBadResponseException: {"message":"2 errors occurred:\n\t* provisioning docker WSL distros: running wsl-bootstrap version set in main distro: exit status 1\n\t* checking if isocache exists: CreateFile \\wsl$\docker-desktop-data\isocache\: The network name cannot be found.\n\n"}

### ISSUE THREAD

**Issue by Baolong-chao** [docker/for-win#13236]
Docker.Core.HttpBadResponseException:
{"message":"2 errors occurred:\n\t* provisioning docker WSL distros: running wsl-bootstrap version set in main distro: exit status 1\n\t* checking if isocache exists: CreateFile \\\\wsl$\\docker-desktop-data\\isocache\\: The network name cannot be found.\n\n"}

**Comment by JanEngelhardt** [comment]
Doing a `wsl --update`
and updating to the latest docker-desktop version fixed it for me.

**Comment by onwike** [comment]
@LeoChenZM Can you attempt a wsl --shutdown as well and let me know what happens afterwards?

**Comment by LeoChenZM** [comment]
> @LeoChenZM Can you attempt a wsl --shutdown as well and let me know what happens afterwards?

Ah, I fixed it at last. I found a very secret blog that tells me to run a command `netsh winsock reset` via CMD with admin role.
It's amazing, hope it will work for others.

**Comment by LedbetterBlog** [comment]
> 

Thank you very much for your method. I will write a blog to spread it

**Comment by LedbetterBlog** [comment]
> > @LeoChenZM Can you attempt a wsl --shutdown as well and let me know what happens afterwards?
> 
> Ah, I fixed it at last. I found a very secret blog that tells me to run a command `netsh winsock reset` via CMD with admin role. It's amazing, hope it will work for others.

Thank you very much for your method. I will write a blog to spread it！

**Comment by lmy54321** [comment]
> > @LeoChenZM Can you attempt a wsl --shutdown as well and let me know what happens afterwards?
> 
> Ah, I fixed it at last. I found a very secret blog that tells me to run a command `netsh winsock reset` via CMD with admin role. It's amazing, hope it will work for others.

Thank you ,i met the same  issue and fixed by your method.

**Comment by yodayuuki55** [comment]
> > @LeoChenZM Can you attempt a wsl --shutdown as well and let me know what happens afterwards?
> 
> Ah, I fixed it at last. I found a very secret blog that tells me to run a command `netsh winsock reset` via CMD with admin role. It's amazing, hope it will work for others.

Thanks for your method, i fixed it after rebooting my machine.

**Comment by huyantao** [comment]
> 

Thank you, i fixed it with your method.

**Comment by jamiematrix** [comment]
Got this issue a few hours ago. Had been working on a DDEV site fine and went to update WSL as there was an update available. Now getting the same error when Docker starts up.

I've restarted, run `netsh winsock reset`, checked `wsl --update` and as far as I know I have latest Docker installed.

I've tried to browse the directory the error is complaining about (\\wsl$\docker-desktop-data) but cannot access it. I can get into \\wsl$\docker-desktop and \\wsl$\Ubuntu

**Comment by ElvisJin** [comment]
It worked for me. Thanks.

**Comment by pangjunchi** [comment]
Thank you,I also fixed it

**Comment by poolye** [comment]
> Ah, I fixed it at last. I found a very secret blog that tells me to run a command `netsh winsock reset` via CMD with admin role. It's amazing, hope it will work for others.

Thank you very much, It worked for me.

**Comment by Rosebud-Bob** [comment]
Thanks, i fixed the problem
