### ISSUE TITLE
Docker.Core.HttpBadResponseException: {"message":"1 error occurred:\n\t* provisioning docker WSL distros: running wsl-bootstrap version set in main distro: exit status 0xffffffff\n\n"}

### ISSUE THREAD

**Issue by dugudongfangshuo** [docker/for-win#13231]
Docker.Core.HttpBadResponseException:
{"message":"1 error occurred:\n\t* provisioning docker WSL distros: running wsl-bootstrap version set in main distro: exit status 0xffffffff\n\n"}

**Comment by p1-0tr** [comment]
hi @dugudongfangshuo , thanks for reporting the issue. Please try updating your WSL installation, `wsl --update` on the CLI. If that fails, please follow https://docs.docker.com/desktop/troubleshoot/overview/#diagnose-from-the-terminal and submit a diagnostic ID.
