### ISSUE TITLE
WSL2/Hyper-V endless memory usage

### ISSUE THREAD

**Issue by DreamUpstream** [docker/for-win#13239]
On both WSL2 and Hyper-V, Docker uses the maximum available ram (16gb or whatever I set in the settings/wslconfig) and freezes up. Have no idea why. Wiped my ssd, reinstalled windows, fresh install of docker and fresh container rebuild.

Latest WSL2
Latest Windows updates
Latest Docker (4.16.3)

**Comment by YouveGotMeowxy** [comment]
Might have a container that likes to eat a bunch of ram. You can view container resource usage and see.

**Comment by nchj** [comment]
it looks like same with me ,at  #13227

**Comment by PetterS** [comment]
Uses 20GB of memory and crashes repeatedly when simply pulling (not running) `ghcr.io/pytorch/pytorch-nightly:83e8426-cu11.6.2`

**Comment by DreamUpstream** [comment]
Whoops, I had a cyclic dependency in a few of my containers that when they were loading up PHP-Laravel did not detect it and drew dependency graph till infinity therefore freezing up the memory.

Make sure to use docker stats and debug your containers first!
