### ISSUE TITLE
Can you add command options for scripted installation such as a silent install?

### ISSUE THREAD

**Issue by grumpydev-net** [docker/for-win#1323]
### Expected behavior
Given an the stable or edge executable
When running executable with -silent option
Then should install without user prompts requested.

### Actual behavior
UI driven installation. Command line with no options.

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
N/A

  - a reproducible case if this is a bug, Dockerfiles FTW
N/A
  - page URL if this is a docs issue or the name of a man page
N/A
  - host distribution and version (Windows version, build number, etc)
Docker for Windows Installer.exe - Windows 10
### Steps to reproduce the behavior
N/A

**Comment by friism** [comment]
Dupe: https://github.com/docker/for-win/issues/1322
