### ISSUE TITLE
docker.compose works on Mac but has "permission" issues on Windows

### ISSUE THREAD

**Issue by najlaaugust** [docker/for-win#13247]
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

docker.compose hangs on create container. There's an error shown in the log file.

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by najlaaugust** [comment]
![image](https://user-images.githubusercontent.com/19152946/219584952-1a6cdc2d-5cdb-48f6-9d8e-3c08a6120ec4.png)

**Comment by najlaaugust** [comment]
This worked for me: 
![image](https://user-images.githubusercontent.com/19152946/219684466-27bf249b-8666-4108-9afa-39840043a7f7.png)

**Comment by YouveGotMeowxy** [comment]
Sorry, I don't have an answer, but it may be helpful to post at: https://github.com/docker/compose
