### ISSUE TITLE
Docker Desktop Won't Shut down

### ISSUE THREAD

**Issue by YouveGotMeowxy** [docker/for-win#13245]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

right click the tray icon, click Shut Down DD, the tray icon does the usual animation, the apps shows the shutting down notice ... and that's it ... never shuts down.

![image](https://user-images.githubusercontent.com/39491297/219145918-ee110625-56b3-4f4d-b338-18e5d071dbe2.png)

### Expected behavior

You click "shut down" and it shuts down ...

### Information

  - Windows Version: 10 x64
  - Docker Desktop Version: 4.16.3
  - WSL2 or Hyper-V backend?  wsl2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

**Comment by nchj** [comment]
it seems similar to me ,at issue  #13227
