### ISSUE TITLE
Run Docker without Docker Desktop?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [docker/for-win#13249]
I haven't had access to any of my containers for 3+ weeks now and no matter how much help I ask for here I really get nowhere, there's a massive lack of support from both the company and community, and it really seems that DD is highly untested before releasing for update, so I'm wondering if it's possible to completely uninstall Docker Desktop and install Docker alone within WSL, basically as if I were just running a regular Ubuntu machine and running Docker in it?

If so, is there some way to "migrate" all my current stuff so that I don't lose anything, and are there any caveats/cons to running it that way vs. running it with DD?

**Comment by mloskot** [comment]
You can try install Docker Engine only. On Windows 10/11, you can go for the Windows Admin Center option, then install Containers extension which will get you Docker w/o the Docker Desktop, see 
https://learn.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment

**Comment by zolij** [comment]
> I haven't had access to any of my containers for 3+ weeks now and no matter how much help I ask for here I really get nowhere, there's a massive lack of support from both the company and community, and it really seems that DD is highly untested before releasing for update, so I'm wondering if it's possible to completely uninstall Docker Desktop and install Docker alone within WSL, basically as if I were just running a regular Ubuntu machine and running Docker in it?

You can run docker itself in WSL2, similar you run it on a linux. Only differences that you have to start the dockerd service manually or from script.
