### ISSUE TITLE
Windows server 2016 server VPS - Could not start MobyLinuxVM

### ISSUE THREAD

**Issue by DutchITWorks** [docker/for-win#1325]
### Expected behavior
Docker starting

### Actual behavior
Docker does not start (stays red)

### Information
Error message (Dutch): De Virtual Machine Management-service kan de virtuele machine MobyLinuxVM niet starten, omdat een van de Hyper-V-componenten niet actief is (virtuelemachine-id 34549E85-0B1D-48FC-BC5C-CD376336FB7F).

Error message (English):  Virtual Machine Management-service could not start MobyLinuxVM, because one of the Hyper-V components is not active.

Diagnostic ID:  0815F852-CE18-4373-A0BA-CCD4A167E984/2017-11-15_10-12-45

Stacktrace (Dutch):
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Kan MobyLinuxVM niet starten.

De virtuele machine MobyLinuxVM kan niet worden gestart omdat een van de Hyper-V-componenten niet actief is.

Kan MobyLinuxVM niet starten. (Virtuelemachine-id 34549E85-0B1D-48FC-BC5C-CD376336FB7F)

De Virtual Machine Management-service kan de virtuele machine MobyLinuxVM niet starten, omdat een van de Hyper-V-componenten niet actief is (virtuelemachine-id 34549E85-0B1D-48FC-BC5C-CD376336FB7F).
at Start-MobyLinuxVM, <No file>: line 315
at <ScriptBlock>, <No file>: line 410
   bij Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:regel 261
   bij Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:regel 131
   bij Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:regel 47
   bij Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:regel 145

Winver.exe info: 
Microsoft Hyper-V server 2016
Microsoft windows server version 1607, machine build 14393.1770

### Steps to reproduce the behavior

  1. Install Docker ce (also tried the edge version)
  2. Let docker enable hyper-V -> reboot
  3. When starting docker the message pops up.

**Comment by friism** [comment]
If you're on some VPS, then that may not support nested virtualization. Can you start _any_ Hyper-V VM on that machine?

**Comment by DutchITWorks** [comment]
Indeed, I tried adding a new VM, and got the exact same message (Though the provider claimed it was supported). Oké going for azure container service now, that ought to work.
