### ISSUE TITLE
DOCKER BUILD fails, when project being build is under OneDrive for Business path

### ISSUE THREAD

**Issue by TDabasinskas** [docker/for-win#1328]
### Expected behavior
`DOCKER BUILD` command should work when launched from any local path (including a OneDrive for Business path).

### Actual behavior
`DOCKER BUILD` fails with an unclear error when the DOCKERFILE is located on a OneDrive for Business folder.

#### Operating System
```
Platform      : Win32NT
ServicePack   :
Version       : 10.0.16299.0
VersionString : Microsoft Windows NT 10.0.16299.0
```

#### Docker
```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

### Steps to reproduce the behavior

1. Have a project with DOCKERFILE under `C:\Projects`, which is being build successfully.
2. Move the folder under `C:\OneDrive\OneDrive - Company\Projects\Project\`.
3. Navigate to ``C:\OneDrive\OneDrive - Company\Projects\Project\`` via command line.
4. Run `docker.exe build --pull --tag "project:1.0.0" .`
5. Receive error `unable to prepare context: unable to evaluate symlinks in context path: readlink C:\OneDrive\OneDrive - Company: The process cannot access the file because it is being used by another process.`

To my understanding, there's some bug, as the error message itself seems flawed:

- It says the file is being used by some other process, when it is really not (OneDrive application is stopped, there are no opened handles to that path from the OS side).
- The path inside the error message is `C:\OneDrive\OneDrive - Company`, while it should be `C:\OneDrive\OneDrive - Company\Projects\Project\`. For some reason, it seems that not the full path is parsed.

I've been hosting the projects inside the OneDrive for Business folder for quite some time, and `DOCKER BUILD` was working OK initially. Not sure, but the issue might have started recently. It might be after Windows 10 Fall upgrade, or some Docker for Windows update.

Any idea what might be causing the described behavior?

Thanks in advance.

**Comment by enyalius1** [comment]
I concur, I just ran across this myself. I assume that Docker is detecting that one drive is active and thus syncing the files somewhere but I wouldn't think that it would affect the build as the file isn't changing at the time the build is executed.

**Comment by JimmyHannon** [comment]
Same problem for me. I had it working previously but i think it fails since i recently executed the fall creators update of windows 10.

**Comment by xposix** [comment]
I also reported this issue on #1290, can we link the tickets somehow?

**Comment by TDabasinskas** [comment]
Hi @xposix,

Somehow I've missed your issue when doing the initial search of the problem prior reporting it. Since yours is older, I guess it makes sense closing this one as duplicate of yours.

**Comment by TDabasinskas** [comment]
Clsoing as a duplicate of #1290

**Comment by sampaioletti** [comment]
For anyone who comes across this, I posted a possible workaround in #1290 that is working for me
