### ISSUE TITLE
Docker Desktop issue

### ISSUE THREAD

**Issue by erhanyap** [docker/for-win#13282]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by whitehorsesoft** [comment]
Please describe the issue itself

**Comment by erhanyap** [comment]
Problem is resolved with upgrading the system with latest Windows upgrades. Downloaded/installed nearly 15 different upgrades from Windows. And issue resolved. Thanks
