### ISSUE TITLE
Switching tabs in settings loses changes

### ISSUE THREAD

**Issue by DeltaWhy** [docker/for-win#133]
### Expected behavior

Clicking 'Apply' in settings should apply all changes I've made.
### Actual behavior

Clicking 'Apply' only applies settings on the current tab. There is no warning when switching tabs that changes will be lost. As a result, the VM has to be restarted multiple times instead of just once when I am finished changing all the settings.

**Comment by dgageot** [comment]
Thank you @DeltaWhy for the bug report. You are right, the behaviour should be improved.

**Comment by jasonbivins** [comment]
we have an open pinata issue for this - closing this one
