### ISSUE TITLE
visual bug in window "run a new container" field Volumes with text HOST PATH, the column name overlaps the address

### ISSUE THREAD

**Issue by stasevich741** [docker/for-win#13304]
1) image in use (container is running)
2) images screen, click run button -> select optional settings
3)part Volumes, field host path -> click three dots menu->choose random folder on computer
the column name overlaps the address

 
https://user-images.githubusercontent.com/71151867/225302301-27c9778f-c9fe-41f0-ab48-fbba0bec7285.mp4
https://recordit.co/89a02Nv3oj
https://recordit.co/K7JtE8ELlr

yesterday updated for latest version
it repeatable
dokcer v 4.17.0
{
Выпуск	Windows 10 Домашняя
Версия	22H2
Дата установки	‎03.‎09.‎2020
Сборка ОС	19045.2604
Взаимодействие	Windows Feature Experience Pack 120.2212.4190.0
}

**Comment by lorenrh** [comment]
We have released Docker desktop 4.21.1, containing a fix for this issue, please see https://docs.docker.com/desktop/release-notes/
