### ISSUE TITLE
docker run hello-world hangs forever

### ISSUE THREAD

**Issue by mhartfield** [docker/for-win#1332]
### Expected behavior
Running "docker run hello-world" should produce output as specified her: https://docs.docker.com/docker-for-windows/#explore-the-application-and-run-examples

### Actual behavior

Typing "docker run hello-world" in either cmd or Windows PowerShell results in the prompt hanging forever.

### Information

Diagnostic ID: 93154160-DF64-43B9-9F78-DC5A318AF3E4/2017-11-16_17-04-15

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. Run 'docker run hello-world' from a Windows 10 command prompt
  2. Observe the prompt hang forever.

**Comment by jasonbivins** [comment]
Hi @mhartfield 
It looks like Docker isn't running - do you see the Whale icon in your systray?

**Comment by mhartfield** [comment]
Yes, I do (I right clicked to generate the diagnostic report). I'll make sure it's running, thanks.

**Comment by mhartfield** [comment]
I reset Docker to factory settings and restarted, then issued 'docker login' from the command line to log in to my docker account, and the problem disappeared.  I'm not sure what I changed from default settings but the problem is resolved.

**Comment by lawrencengan** [comment]
I have encountered the same problem that the hello-world program hangs after my laptop is rebooted and docker is up and running.  I have to quit docker and restart it manually to get the hello-world program working again.  No setting needs to be changed.  Hope this help.

**Comment by maximogiordano** [comment]
It helps indeed!

**Comment by fibonaccho** [comment]
None from this solutions works for me.

**Comment by sergio-domingues** [comment]
Same here.
Running on Windows 10 and latest version of Docker
