### ISSUE TITLE
Docker on Windows insider build 17040

### ISSUE THREAD

**Issue by yrest** [docker/for-win#1333]
Exactly the same symptoms as https://github.com/docker/for-win/issues/1302 and https://github.com/docker/for-win/issues/1255

Is it the case that MS will not support Docker on W10? Was there announcement I missed?

Running 
$imageNameTag = "microsoft/nanoserver"
docker rm nanoserver -f
docker pull $imageNameTag
docker run -m 1G --name nanoserver `
           --hostname nanoserver `
           $imageNameTag

on 

Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 17.11.0-ce-rc3
Storage Driver: windowsfilter
 Windows: 
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17040 (17040.1000.amd64fre.rs_prerelease.171110-1506)
Operating System: Windows 10 Pro Insider Preview
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 15.92GiB
Name: ip
ID: RXTU:H7CK:TCKK:6AH2:J73J:JDWP:Q42F:IMJY:NAFX:JDCX:PDNB:E25T
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 29
 System Time: 2017-11-17T10:16:16.5625042Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

And getting

Digest: sha256:df59b79514786730283cd2df9dbcfdde086454cdbcefbe5e90e142f4d2e97d25
Status: Downloaded newer image for microsoft/nanoserver:latest
docker : C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container 2ae9ca3e8854f625377a2d6e48bda9cb25e41d5080f6408c7d95108153f54ef4 
encountered an error during CreateContainer: failure in a Windows system call: The description string for parameter reference (%1) could not be found. (0x3ab6) extra

**Comment by friism** [comment]
I'm also on 17040 and cannot reproduce:

```
docker run microsoft/nanoserver hostname
ff0746087713
```

Maybe you can try some of the images that more closely match your host os: https://hub.docker.com/r/microsoft/nanoserver-insider/tags/

**Comment by yrest** [comment]
@friism , thanks for reply Michael! 
All Windows containers fail for me since 17025. 
I only use nanoserver to test it, but for development I use private repos.

There was just an update released for docker and I tried what you suggested.

Digest: sha256:1f71a9dce9cc3f9a0dc4f1a0a00e74700ddc41c4798a09846fc777e99b28d7de
Status: Downloaded newer image for microsoft/nanoserver-insider:latest
docker : C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container 71de69bbd19181423536c923c92b1f228908931f0e5b711a0ce45e769809397a 
encountered an error during CreateContainer: failure in a Windows system call: The description string for parameter reference (%1) could not be found. (0x3ab6) extra 

PS C:\WINDOWS\system32> docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 17.11.0-ce-rc4
Storage Driver: windowsfilter
 Windows: 
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17040 (17040.1000.amd64fre.rs_prerelease.171110-1506)
Operating System: Windows 10 Pro Insider Preview
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 15.92GiB
Name: ip
ID: RXTU:H7CK:TCKK:6AH2:J73J:JDWP:Q42F:IMJY:NAFX:JDCX:PDNB:E25T
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 29
 System Time: 2017-11-17T23:09:15.7258888Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

All other VMs on hyper-v work no problem.

On a side note, updating Docker always fails because dockerd.exe is locked by svchost.exe and I have to manually install new version.

Is there anything else you can suggest to try besides reinstalling the machine?

**Comment by stormcrow79** [comment]
Hi @yrest 

I've had the same problem on the same range of Insider builds. Tried completely removing Docker, Windows Containers and Hyper-V, rebooting and then reinstalling everything with no success. Linux containers work fine.

At first I thought it was related to the compatability note (https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility) but the same issue affects :latest and :1709, and the error is different to the one at that link "failure in a Windows system call: The operating system of the container does not match the operating system of the host")

C:\Users\gavinm>docker info
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 2
Server Version: 17.09.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17040 (17040.1000.amd64fre.rs_prerelease.171110-1506)
Operating System: Windows 10 Pro Insider Preview

**Comment by yrest** [comment]
Thanks @stormcrow79 ! 
Have you submitted your experience to MS? 
Check https://aka.ms/X3x0za 
I have tried reaching them on Twitter a number of times, but to no avail.

The error message in the latest builds am getting, has nothing to do with containers, I believe, because there is no actual description...

**failure in a Windows system call: The description string for parameter reference (%1) could not be found**

Surely there must be a way to find out what that "parameter reference" is?

**Comment by stormcrow79** [comment]
Error persists after upgrade to 17.11.0-ce on Windows 10.0.17040.1000

**Comment by quangkieu** [comment]
@yrest 
https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility#errors-from-mismatched-versions
According to that document I think you have to pull and run the correct version of the base container as the "lastest" which is their default tag is using for LTS Windows.
When I run `docker run -it microsoft/nanoserver:1709 cmd`, I do not have that error anymore.
