### ISSUE TITLE
Docker magically shutting down

### ISSUE THREAD

**Issue by gustavozantut** [docker/for-win#13382]
I was doing nothing, with docker on and suddenly, another surprise, before that, i received a message that wsl has broken.

![image](https://user-images.githubusercontent.com/60036627/231339865-4157469a-8917-4ccd-8cd7-81b3ffa4cadc.png)

each update is a new surprise, a few days ago all gpu's failing and now wsl total failure! Amazing!!!

maybe next update fixes it :D

have you ever tried to test things before release?

**Comment by Nightwalk2001** [comment]
I had the same problem, before it was frequent host network errors, now it always crashes wsl
 I'm fed up, I'm going to try podman
