### ISSUE TITLE
Docker Desktop Hanging: Fix

### ISSUE THREAD

**Issue by barnjamin** [docker/for-win#13386]
Posting this for the next person to come along.

Similar issue to all of these:
https://github.com/docker/for-win/issues/13375
https://github.com/docker/for-win/issues/13353
https://github.com/docker/for-win/issues/13372
https://github.com/docker/for-win/issues/13359
https://github.com/docker/for-win/issues/13357
https://github.com/docker/for-win/issues/13351

# Fix

Run:
```sh
wsl.exe --update --pre-release
```

On my machine this installed `WSL version: 1.2.1.0`

Installed v4.18.0 of docker-desktop and it started fine

Found solution from
https://github.com/microsoft/WSL/issues/9868

**Comment by makuepfer** [comment]
Did the WSL update and Docker Desktop 4.11.0 started up again. Kubernetes with WSL backend is operating.

**Comment by kgkoutis** [comment]
It worked but all containers and images are gone I see

**Comment by maikebing** [comment]
https://github.com/docker/for-win/issues/13340

**Comment by memetrusidovski** [comment]
finally this fixed it. i've been spending hours on this. unbelievable. good lesson in backing up data

**Comment by memetrusidovski** [comment]
still isnt working. the above solution only switches me to windows containers. WSL and Docker still not working at all. Have tried everything i can find. is it possible to rollback to my previous version of WSL that worked?

**Comment by maikebing** [comment]
![image](https://user-images.githubusercontent.com/3445167/232208263-f9fea48a-cc52-40cd-8678-1131226b8c26.png)

**Comment by maikebing** [comment]
```
1 : The test: is the VM time synchronized?
    Failed with: parsing time output: 2023-04-15T11:01:45+00:00: parsing time "2023-04-15T11:01:45+00:00" as "2006-01-02T15:04:05UTC": cannot parse "+00:00" as "UTC"

The VM time must be in sync with the host, otherwise Docker Desktop will not work correctly.

Ensure you are using a modern WSL 2 kernel (see "wsl --update"). If this problem persists,
try manually synchronizing the VM clock with "sudo hwclock -s".

2 : The test: is the WSL 2 Linux filesystem corrupt?
    Failed with: [   15.045125] EXT4-fs error (device sdc): ext4_put_super:1188: comm Xwayland: Couldn't clean up the journal

If the WSL 2 Linux filesystem is corrupt then Docker Desktop cannot start.
There is a known issue fixed in Windows Insider builds which can cause filesystem corruption, see:
https://github.com/microsoft/WSL/issues/5895 .

Try running "wsl --shutdown" to stop your WSL Virtual Machine. When it restarts it will
run a filesystem check and hopefully fix the problem.
```

**Comment by maikebing** [comment]
```
C:\Users\mysti>wsl --version
WSL 版本： 1.2.2.0
内核版本： 5.15.90.1
WSLg 版本： 1.0.51
MSRDC 版本： 1.2.3770
Direct3D 版本： 1.608.2-61064218
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows 版本： 10.0.22621.1555
```

**Comment by memetrusidovski** [comment]
still doesnt work. and every time i reset wsl docker crashes again in ubuntu. i've tried deleting everything from WSL, Ubuntu, Docker, Docker Desktop, Windows Terminal. still nothing. I got it to pull images in ubuntu but it crashes everytime i close it anyway

**Comment by memetrusidovski** [comment]
i've literally tried everything i can find for the last 3 days. is there any fix coming for this? does anyone have a way to delete everything and rollback to the old versions that worked. i've tried deleting everything and reinstalling old versions and still nothing. It worked perfectly fine before it auto updated.

**Comment by aignermax** [comment]
> i've literally tried everything i can find for the last 3 days. is there any fix coming for this? does anyone have a way to delete everything and rollback to the old versions that worked. i've tried deleting everything and reinstalling old versions and still nothing. It worked perfectly fine before it auto updated.

for me every upgrade of WSL or every Windows Update gets Docker back to work for a day or so. Remember to manually start/restart the docker service and restart WSL and then start docker desktop and give it some time (one Minute or so) to start. Sometimes I closed it too early as it started up faster in the past..

**Comment by maikebing** [comment]
```
应用程序: Docker Desktop.exe
Framework 版本: v4.0.30319
说明: 由于未经处理的异常，进程终止。
异常信息: System.NullReferenceException
   在 Docker.Program.Run(System.Collections.Generic.IReadOnlyCollection`1<System.String>)
   在 Docker.Program.Main(System.String[])

```

**Comment by LeviPesin** [comment]
This doesn't fix the issue for me.

**Comment by aignermax** [comment]
have you tried
`wsl --update --pre-release`
already?
this should fix the issue for now
