### ISSUE TITLE
memory requirements for mobylinux/boot2docker too high to wield swarm

### ISSUE THREAD

**Issue by lusitania** [docker/for-win#134]
### Expected behavior
Startup memory and memory demand of idle VM in the order of an alpine container, below 100MB. This order of memory usage is vital for spawning multiple (reads at least 3) nodes in order to test a modestly complex, distributed application on an average developer machine (with 4 or 8 GB of RAM).

### Actual behavior
Minimum configurable memory 1 GB via GUI. Memory demand of idle VMs at about 650 MB.

### Information

  - Diagnostic ID: 5B7AC43B-CA65-42E7-98A8-B482CA7FC66D/2016-10-07_11-41-37
  - a reproducible case if this is a bug, Dockerfiles FTW: N/A, its a feature request
  - page URL if this is a docs issue or the name of a man page: N/A
  - host distribution and version: Windows 10 Pro 1607, 14393.187

### Steps to reproduce the behavior

  1. get yourself a notebook with 4GB of RAM
  1. (try to) spawn 3 VMs with default iso
```
#done in cygwin, similar with CMD
for i in {1..3}; do docker-machine create -d hyperv --hyperv-memory 700 --hyperv-virtual-switch docker --hyperv-disk-size 1000 --swarm node-$i; done
```

**Comment by friism** [comment]
Thanks for opening. You can test single-node swarm with Docker for Windows by running `docker swarm init`.

If, for some reason, you need to test multi-node swarms and your laptop does not have enough memory, I recommend using docker-machine and a cloud provider like Digital Ocean, AWS or Azure.

**Comment by lusitania** [comment]
really? that's it?

 - a single-node swarm is irrelevant. having only a manager doesn't do anything.
 - why do you need over 1/2GB of RAM for a service of 50MB on idle? even my hoster's rescue image is below 200MB of utilisation.
 - i believe it was your founder, solomon hykes, who talks a lot about enabling people. by saying "go elsewhere, pay someone" you are breaking your own mantra.

sorry for expecting better of you

**Comment by friism** [comment]
If you think there ways to make Boot2docker use less memory, feel free to open an issue on that project or consider contributing a patch: https://github.com/boot2docker/boot2docker
