### ISSUE TITLE
A timeout occured while waiting for a WSL integration agent to become ready.

### ISSUE THREAD

**Issue by Mnish55** [docker/for-win#13425]
This can occur when starting after an abrupt termination. To work around the issue, please terminate WSL (wsl --shutdown) and start Docker Desktop again. If the issue persists please collect diagnostics and submit an issue (https://docs.docker.com/desktop/troubleshoot/overview/#diagnose-from-the-terminal).

how to solve this problem.

**Comment by LeviPesin** [comment]
Solution described in https://github.com/docker/for-win/issues/13426.

**Comment by Mnish55** [comment]
Thank you so much. problem solved
