### ISSUE TITLE
Docker For Windows hangs system on Windows container run command

### ISSUE THREAD

**Issue by robstanner** [docker/for-win#1342]
### Expected behavior
Run the command 'docker container run microsoft/windowsservercore hostname'
Should return with hostname output

### Actual behavior
The following error came back:

container 8270256991ee57c50713d1b70ffb26c10aa57d1edd5be4c8605709b0271401e0 encountered an error during Start: failure in a Windows system call: Call was canceled by the message filter. (0x80010002)

This also caused entire system to hang once the error came back and would not respond.  Had to do a force reboot to get back in.

Information about the system:

Docker info output:
PS F:\> docker info
Containers: 3
Running: 0
Paused: 0
Stopped: 3
Images: 3
Server Version: 17.09.0-ce
Storage Driver: windowsfilter
Windows:
Logging Driver: json-file
Plugins:
Volume: local
Network: ics l2bridge l2tunnel nat null overlay transparent
Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 15063 (15063.0.amd64fre.rs2_release.170317-1834)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 7.91GiB
Name: ILNCMU-D171447
ID: S2T4:KY2J:RXOZ:HWUN:65LL:EHLB:3INZ:SFAZ:EOVY:OZAZ:G6LZ:OUO6
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
File Descriptors: -1
Goroutines: 22
System Time: 2017-11-14T10:53:12.2781634-06:00
EventsListeners: 0
Http Proxy: http://http-proxy.ntrs.com:443
Https Proxy: http://http-proxy.ntrs.com:443
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
127.0.0.0/8
Live Restore Enabled: false

Docker version output:
PS F:\> docker version
Client:
Version:      17.09.0-ce
API version:  1.32
Go version:   go1.8.3
Git commit:   afdb6d4
Built:        Tue Sep 26 22:40:09 2017
OS/Arch:      windows/amd64

Server:
Version:      17.09.0-ce
API version:  1.32 (minimum version 1.24)
Go version:   go1.8.3
Git commit:   afdb6d4
Built:        Tue Sep 26 22:50:27 2017
OS/Arch:      windows/amd64
Experimental: true

Docker Log from system:
[log.23.txt](https://github.com/docker/for-win/files/1487811/log.23.txt)

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
48233AEA-9D9A-4130-8390-EC47011503ED/2017-11-20_07-38-46
(This was run after the reboot as system is frozen after error returns)
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...Run the command 'docker container run microsoft/windowsservercore hostname'
  2. ...Should return with hostname output

**Comment by jasonbivins** [comment]
Hi @robstanner 
Were you running the command in CMD or in Powershell?
In CMD you can see the size of the layers as they are being pulled. Even though the layers are compressed, it might seem to hang while downloading since it's a pretty hefty image - see below. It also looks like you're behind a proxy, so there may be some tweaking needed on that end to avoid timeouts

This command might help as well with the larger images like this - commands are pretty zippy after the image has been pulled.  ``` docker pull microsoft/windowsservercore ```

![image](https://user-images.githubusercontent.com/28021664/33110812-8f1dfcf8-cf18-11e7-9002-ed834fce49ac.png)

**Comment by robstanner** [comment]
Appreciate the quick reply back.  Just did some more testing over the last 2 days and we have isolated it as an issue with an admin rights application running in the background.  We are working on trying to figure out which process is being blocked.  Thanks again and closing this.

**Comment by pranabesh-saha** [comment]
> Appreciate the quick reply back. Just did some more testing over the last 2 days and we have isolated it as an issue with an admin rights application running in the background. We are working on trying to figure out which process is being blocked. Thanks again and closing this.

Would you mind to detail how the issue was resolved? I had the same problem and still searching for a solution. I am using a Win 2019 VM running in AWS cloud

**Comment by neersighted** [comment]
Unlocked per the reporters request.
