### ISSUE TITLE
Severe memory usage (15GB) without any Containers running

### ISSUE THREAD

**Issue by hexxone** [docker/for-win#13433]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A82E282D-736C-4FCE-BFE5-DA80FEBC9ED7/20230426122158

### Actual behavior

Docker Desktop is consuming about 15GB of RAM on Windows 10 without any running Containers or Plugins.

![image](https://user-images.githubusercontent.com/5312542/234575078-f505baa8-a792-4af4-9db5-ec8f38240169.png)

The RAM usage start at about 2GB and gets worse, with every hour my PC is running and every container I start and remove.

The Containers are nothing unusual, just some custom C# ASP Net Core API and PostgresDb.

### Expected behavior

Docker Desktop should clean up the WSL memory usage when it removes Containers.

### Information

- reproducable by normally working for a Day and starting & stopping containers 1-2 times / hour.
- the problem is known for a long time, but it seems nothing has improved for a while.

  - Windows Version: 10 (latest updates)
  - Docker Desktop Version:  4.18.0
  - WSL2 or Hyper-V backend:   WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: NO

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

- https://pastebin.com/uey92N86

seems to contain some errors, but I dont know why/what they mean..?

Besides the excessive RAM usage everything seems to work.

**Comment by tboby** [comment]
I'm getting similar behaviour, the docker-desktop wsl instance seems to be taking all available memory (8GB) in my case.

If I run `echo 3 > /proc/sys/vm/drop_caches` in the instance it fairly rapidly releases, but it starts to leak as soon as I use docker.

**Comment by RouisIbra** [comment]
Even with containers running it shouldn't use that much RAM.

**Comment by nogenem** [comment]
It should have the HIGHEST priority lol Seriously, i'm losing all will to use this tool cause i'm getting really infuriated by this bug and its not even a new bug, it seems to be a thing for a long time already...

**Comment by samuk190** [comment]
> It should have the HIGHEST priority lol Seriously, i'm losing all will to use this tool cause i'm getting really infuriated by this bug and its not even a new bug, it seems to be a thing for a long time already...

its been there for more than 3 years, I remember in 2019 having that bug, and i came back use windows as main OS, and still same bug.. what worked for me is using docker with hyper v, but i sacrifice some ram being used all time because its reserved.

**Comment by samuk190** [comment]
UPDATE GUYS! MICROSOFT RELEASED A FIX ON LATEST PRERELEASE
USE LATEST WSL PRE-RELEASE AND ENABLE
 [experimental]
autoMemoryReclaim=true

Docker-desktop now use less memory, but I choose to use docker inside wsl natively to get rid of other problems xD 

I think this issue can be closed now

**Comment by samuk190** [comment]
![image](https://github.com/docker/for-win/assets/19878001/288b5a43-2487-49f1-9e7d-7f88326c5036)
Before was using 10gb, now its using only 1.8GB  
WSL Pre-release!

**Comment by hexxone** [comment]
> USE LATEST WSL PRE-RELEASE AND **ENABLE**
> [experimental]
> autoMemoryReclaim=true

Nice! Thanks.
Even though it seems they are just calling `sudo -S echo 3 > /proc/sys/vm/drop_caches` automatically now, it seems to do the trick ^^

[Here is the direct link](https://github.com/microsoft/WSL/releases/tag/1.3.10) for anyone looking :)

I hope they merge that into upstream ASAP - will close it then

**Comment by WiseNil** [comment]
I confirm WSL 1.3.10+ with `autoMemoryReclaim` fixed the issue. I recommend using 1.3.11 not 1.3.10 tho

**Comment by hwang63130** [comment]
It seems this issue only affect Docker Desktop and I switched to Podman (both running under WSL2+Win10Pro) and the issue is gone. 
Therefore, I still believe this is a Docker bug instead of a MS bug.

**Comment by hexxone** [comment]
I can no longer reproduce more than 3gb memory usage in idle. 
So I guess the issue seems solved for now on Windows 10 with WSL2. 

Cheers everyone!
