### ISSUE TITLE
Cannot pull images after installation

### ISSUE THREAD

**Issue by mklinke** [docker/for-win#1343]
### Expected behavior
The command `docker-compose ... pull` downloads new images.

### Actual behavior
After an update to the latest edge version (see below for details) today, the command (still) fails with the following error:

```
> docker-compose ... pull
Pulling [...]... (just one line)
ERROR: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

A Docker restart usually resolves the problem. However, Docker for Windows in a freshly booted session is not usable. I need to restart Docker everytime.

The problem may be related to #911. As I have been waiting for a fix for months(!), I am trying with a new issue here. Three of my colleagues that are also using the Windows version have this problem, too.

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
AD61243F-14D3-4A8C-8180-A7095A745683/2017-11-20_15-29-17
  - a reproducible case if this is a bug, Dockerfiles FTW
Just any docker-compose file that references an image that has not been downloaded yet.
  - page URL if this is a docs issue or the name of a man page
N/A
  - host distribution and version (Windows version, build number, etc)
Windows Version:
```
 Microsoft Windows 10 Pro               
 10.0.15063 Nicht zutreffend Build 15063
```

Docker Version:
```
Version 17.11.0-ce-rc4-win39 (14244)
Channel: edge
e557194
```

### Steps to reproduce the behavior

  1. Start Windows
  2. Try to do anything with Docker -> Docker fails
  3. Restart Docker -> Docker works

**Comment by mklinke** [comment]
Turning off Docker autostart didn't help either. Still have to restart once after the initial start no matter how long I wait till starting Docker for the first time.
Latest Diagnostic: AD61243F-14D3-4A8C-8180-A7095A745683/2017-11-21_13-17-43

**Comment by subliz** [comment]
I have the same issue and restarting Docker after startup solves the issue. But every time you login to windows, you should restart docker which is not comfortable.

**Comment by Krimsar** [comment]
Still happens on my machine (Windows 10 Pro / 1709 / 16299.371) with Docker Version 18.03.1-ce-win65 (17513)

```
PS C:\Windows\system32> docker run -d -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer --restart always
Unable to find image 'portainer/portainer:latest' locally
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
```

My network takes a few seconds to become available upon starting the machine. Could it be that docker daemon choses the wrong interface in such a case? How can I determine which interface the daemon is using?

**Comment by Krimsar** [comment]
Still happening with Docker Version 18.06.0-ce-win72 (19098)
