### ISSUE TITLE
Cannot access internet from container

### ISSUE THREAD

**Issue by Tanhe** [docker/for-win#1344]
### Expected behavior
After installing Docker for Windows (Hyper-V w/ MobyLinux), executing containers should be able to access the Internet.

### Actual behavior
```
λ docker run -it alpine ping www.google.com
PING www.google.com (172.217.5.228): 56 data bytes
^C
--- www.google.com ping statistics ---
5 packets transmitted, 0 packets received, 100% packet loss
```

### Information
  - What's interesting, and you can see from the output, that the DNS resolution works.
  - Diagnostic ID: 1D64579D-CDD1-4471-A7A7-8BFC8686BD10/2017-11-20_10-05-14
  - Windows 10 Enterprise 10.0.14393 Build 14393

### Steps to reproduce the behavior

Install Docker (Docker version 17.09.0-ce, build afdb6d4)
`docker run -it alpine ping www.google.com`
Regular ping results

As an aditional note...everything was working until the latest update.

**Comment by jasonbivins** [comment]
Hi @Tanhe   I wasn't able to repro this one on either the edge or stable channels.

One thing I did notice is that there actually were a few DNS errors in your logs related to your corporate DNS - can you try using a fixed DNS with Docker?
![image](https://user-images.githubusercontent.com/28021664/33059098-d6c06d7e-ce60-11e7-88a9-4041c71d38ae.png)

**Comment by Tanhe** [comment]
So I tried again and DNS has always worked ok. It seems that just ping and in fact all ICMP doesn't work. After I changed the DNS setting I found the following line in my logs:

`vpnkit.exe: Unexpected exception Permission denied setting up user-space ICMP socket: ping will not work`

**Comment by jasonbivins** [comment]
Do you know if your network admins have restricted ICMP traffic?  It's pretty common to disable it to prevent basic ddos attacks.

**Comment by mrbrazzi** [comment]
The same issue here!!!... my linux containers can't connect to internet on Docker for Windows.

I have:
![image](https://user-images.githubusercontent.com/1132397/60845701-26909580-a1ab-11e9-8d5d-10c9ab80d3af.png)

![image](https://user-images.githubusercontent.com/1132397/60845582-ce599380-a1aa-11e9-836f-cade00755b83.png)

docker-compose.yml
```
version: '3'

volumes:
  node_modules: {}

services:
  angular:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - '4200:4200'
```

when I try to run a container, I got the following error:
```
Deploying 'Compose: docker-compose.yml'...
docker-compose up -d
Creating volume "app_node_modules" with default driver
Building angular
Step 1/11 : FROM node:latest
 ---> 0601b4151f1d
Step 2/11 : RUN mkdir -p /app/node_modules && chown -R node:node /app
 ---> Using cache
 ---> e09d5f1b954d
Step 3/11 : WORKDIR /app
 ---> Using cache
 ---> 39025b4cc2fe
Step 4/11 : USER node
 ---> Using cache
 ---> c8c87c59d531
Step 5/11 : ENV PATH /app/node_modules/.bin:$PATH
 ---> Using cache
 ---> 856fc1a34548
Step 6/11 : RUN npm cache clean --force
 ---> Using cache
 ---> aaf7c0a5ff5d
Step 7/11 : COPY package.json .
 ---> Using cache
 ---> 8535217a5666
Step 8/11 : RUN npm install @angular/cli@7.3.9
 ---> Running in 76ccd6416848
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/@angular%2fcli failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2019-07-08T22_11_27_102Z-debug.log
Service 'angular' failed to build: The command '/bin/sh -c npm install @angular/cli@7.3.9' returned a non-zero code: 1
Failed to deploy 'Compose: docker-compose.yml': `docker-compose` process finished with exit code 1
```
