### ISSUE TITLE
 kubernets nvidia gpu resource don't detect

### ISSUE THREAD

**Issue by maoyuanpeng** [docker/for-win#13458]
docker-desktop kubernets engine don't detect nvidia gpu.

kubectl describe nodes docker-desktop
...
Capacity:
  cpu:                32
  ephemeral-storage:  1055762868Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             98176808Ki
  pods:               110

but docker engine can use nvidia gpu.  

nvidia-smi:
Thu May  4 18:32:55 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 528.24       Driver Version: 528.24       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:1A:00.0 Off |                  N/A |
|  0%   36C    P8    11W / 310W |    971MiB /  8192MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
....

**Comment by milas** [comment]
GPU support is not enabled out of the box in Docker Desktop's Kubernetes integration.

NVIDIA has documentation that's a good resource: https://docs.nvidia.com/datacenter/cloud-native/kubernetes/install-k8s.html

The short version for Docker Desktop is to add the following to the Docker Engine daemon configuration (Settings > Docker Engine):
```json
"default-runtime": "nvidia",
"runtimes": {
  "nvidia": {
        "path": "/usr/bin/nvidia-container-runtime",
        "runtimeArgs": []
  }
}
```
<img width="928" alt="Docker Desktop Engine settings showing a valid configuration with the NVIDIA container runtime set as default" src="https://user-images.githubusercontent.com/841263/236252802-6971cece-4537-45d9-9264-6d48e4e7585b.png">

NOTE: This will change the default runtime for _ALL_ Docker containers run, not just those in Kubernetes as they share the same underlying instance of the Docker Engine.

After applying, which will restart Docker Engine and Kubernetes, you should be able to run workloads that use the GPU:
```shell
kubectl run --rm -it --image="nvidia/cuda:11.4.0-base" --restart=Never nv-debug nvidia-smi
```

**Comment by maoyuanpeng** [comment]
`kubectl run --rm -it --image="nvidia/cuda:11.4.0-base" --restart=Never nv-debug nvidia-smi`
after run that, I can see the right output for nvidia-smi.
use `kubectl describe nodes docker-desktop`, i still can't see nvidia gpu resource.
