### ISSUE TITLE
Docker Desktop not opening after so many tries, & not able to sign in also.

### ISSUE THREAD

**Issue by Saha-7** [docker/for-win#13455]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version: 10
  - Docker Desktop Version:  23.0.5, build bc4487a
  - WSL2 or Hyper-V backend?  Hyper-V backend
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. ...
![docker 1](https://user-images.githubusercontent.com/104014464/235949421-4232ce63-6a09-49a7-b0b1-01b4d479c82e.png)

  2. ...
![docker 2](https://user-images.githubusercontent.com/104014464/235949439-2850091b-490c-46f2-a38f-bedc51686a06.png)

**Comment by MihaelaStoica** [comment]
Closing this ticket, as there is not enough information to investigate further.
