### ISSUE TITLE
Docker Desktop 4.19.0 does not embed the k8s version as claimed in release notes

### ISSUE THREAD

**Issue by ParkerM** [docker/for-win#13457]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
The [release notes for 4.19.0](https://docs.docker.com/desktop/release-notes/#4190) list Kubernetes v1.26.3 under the Upgrades section along with a link to the changelog for v1.26.3. However, Docker Desktop 4.19.0 appears to embed Kubernetes v1.25.9 instead.

### Expected behavior
Docker Desktop 4.19.0 should embed Kubernetes v1.26.3

Or, more generally, Docker Desktop should embed the same Kubernetes version as claimed by the release notes.

### Information

  - Windows Version: Windows 10 Pro
  - Docker Desktop Version: 4.19.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Steps to reproduce the behavior

  1. Install (or upgrade) Docker Desktop 4.19.0
  2. Open k8s in the settings menu: it says v1.25.9. Resetting _does_ upgrade an existing cluster to 1.25.9, but not to 1.26.3.
    - Also note the `componentsVersion.json` file that's unpacked to `C:\Program Files\Docker\Docker\resources` during installation. This file contains an entry `"KubernetesVersion": "v1.25.9"`, which is why I believe this is a packaging error rather than a local issue.

**Comment by MihaelaStoica** [comment]
Thanks for reporting this! It is a mistake in the release notes, which we will rectify soon.

**Comment by MihaelaStoica** [comment]
The release notes have been updated, the kubernetes version included with Docker Desktop 4.19 is v1.25.9.
