### ISSUE TITLE
Docker failed to enable Hyper-V.

### ISSUE THREAD

**Issue by krishseshadri** [docker/for-win#1345]
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by krishseshadri** [comment]
Uploaded diagnostic with the ID: 56C3EC2B-2DD3-42FD-AD33-4EDB1B20BFB6/2017-11-20_11-55-31

**Comment by krishseshadri** [comment]
What I have done so far,
1. Upgraded the Windows 10 Home to Windows PRO and recently upgraded to Windows Enterprise
2. Changed the BIOS setting to support VM
3. Downloaded the stable Docker for Windows 
4. When its attempting to start, it fails with the message, Docker failed to enable Hyper-V
5. I tried several options like disabling the Hyper-V feature and manually enabling it, still the issue persists.

Any help is appreciated.

**Comment by jasonbivins** [comment]
Hi @krishseshadri   It looks like there's bad data in your System ENV
Can you run this in Powershell - then verify that these paths exist ? Check the SQL one especially
``` echo $env:PSModulePath ```

You mentioned that you upgraded Windows twice - whenever possible I prefer to do a fresh install over an upgrade.  Would it be possible for you to do a clean install of Windows Enterprise?

**Comment by jasonbivins** [comment]
Hi @krishseshadri It looks like there's bad data in your system variables - specifically the PSModulePath
Let's make sure Powershell is functional first by running the below commands
Import-Module Hyper-V

then verify that the paths listed by this one exist Check the SQL one especially

echo $env:PSModulePath

You mentioned that you upgraded Windows twice - whenever possible I prefer to do a fresh install over an upgrade. Would it be possible for you to do a clean install of Windows Enterprise?

**Comment by krishseshadri** [comment]
You are right Jason. I did a fresh install of Windows Enterprise, Also PowerShell Upgrade to 6.0.
Stopped DockerWindows, Stopped Hyper-V from the app&features, Installed Docker Windows again.
This time docker picked-up and started Hyper-V and started the service successfully.
