### ISSUE TITLE
Docker desktop stuck during installation of update form version 4.18.0 (104112) to latest version 4.19.0 (106363)

### ISSUE THREAD

**Issue by Emmanuel-Adom** [docker/for-win#13467]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Clicked the update button to receive latest update. 
After many hours, docker desktop gets stuck installing updates. 
Restarted docker but "Update to latest" button on top left of docker desktop shows as though update was not previously initiated or has not installed.
"Update to latest" button is clicked again but update and installation is not successful.
Situation is same after several restarts.

### Information

  - Windows Version: Windows 11 Home 22H2 22621.1635
  - Docker Desktop Version: 4.18.0 (104112)
  - WSL2 or Hyper-V backend?  No
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by michaelp** [comment]
How can I help diagnose this issue? I experience the same issue. 
`com.docker.diagnose.exe` complains on 
 
``` 
Failed with: failed to ping com.docker.service with error: Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
 ```

**Comment by michaelp** [comment]
@Emmanuel-Adom, reinstall the docker-desktop application using the official installer. Don't forget to choose the "replace the existing version with the 4.19 ...." in the process. This solves the problem.

**Comment by Emmanuel-Adom** [comment]
Thank you @michaelp. 
Your suggestion solved the problem.
Grateful.

**Comment by judgej** [comment]
Same for me - Windows 11 Pro (upgraded from 10), with same Docker Desktop version. Installer here https://docs.docker.com/desktop/install/windows-install/ took five minutes, no reboots needed, and now back on track. Thank you.
