### ISSUE TITLE
Gateway Timeout on Windows 8 using docker-toolbox

### ISSUE THREAD

**Issue by cjcarvajal** [docker/for-win#1346]
### Expected behavior
I install Docker Toolbox on my Windows 8 PC following the instructions on [this page](https://docs.docker.com/toolbox/toolbox_install_windows/), I have completed all the steps, now I'm verifying the installation using `docker run hello-world` the output should be:
```
<$ docker run hello-world
 Unable to find image 'hello-world:latest' locally
 Pulling repository hello-world
 91c95931e552: Download complete
 a8219747be10: Download complete
 Status: Downloaded newer image for hello-world:latest
 Hello from Docker.
 This message shows that your installation appears to be working correctly.

 To generate this message, Docker took the following steps:
  1. The Docker Engine CLI client contacted the Docker Engine daemon.
  2. The Docker Engine daemon pulled the "hello-world" image from the Docker Hub.
     (Assuming it was not already locally available.)
  3. The Docker Engine daemon created a new container from that image which runs the
     executable that produces the output you are currently reading.
  4. The Docker Engine daemon streamed that output to the Docker Engine CLI client, which sent it
     to your terminal.

 To try something more ambitious, you can run an Ubuntu container with:
  $ docker run -it ubuntu bash

 For more examples and ideas, visit:
  https://docs.docker.com/userguide/
```
### Actual behavior
The actual output is:
```
C:\Program Files\Docker Toolbox\docker.exe: error during conn
92.168.99.100:2376/v1.33/containers/create: Gateway Timeout.
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.
```

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - Docker version 17.10.0-ce, build f4ffd25, Windows 8.1 Pro
  - I'm running behind a proxy, I have configured the environment varibles and included in NO_PROXY the ip that's throwing the error:

Running:

```
docker-machine ssh default
sudo vi /var/lib/boot2docker/profile
```

Got this output:

```
export "HTTP_PROXY={myProxy}
export "HTTPS_PROXY={myProxy}
export "NO_PROXY=10.*,localhost,192.168.*,172.16.*,172.17.*,172.18.*,172.19.*,172.20.*,172.21.*,172.22.*,172.23.*,172.24.*,172.
27.*,172.28.*,172.29.*,172.30.*,192.127.38.*,200.3.147.*,192.177.1.24,200.1.124.
5,200.1.124.6,192.177.1.24"
```    

### Steps to reproduce the behavior

  1.  Just run all the steps [here](https://docs.docker.com/toolbox/toolbox_install_windows/) behind a proxy, you'll get the error on Step 3: Verify your installation.

**Comment by cjcarvajal** [comment]
A little disappointed about this issue without solutions, I finally end with a Mac machine to be able to work with docker.

**Comment by rn** [comment]
This issue was closed because it was inactive and there was no response within 30 days after the initial comment by the bot. We don't have resource to look at all the issues in time, but offered to keep the issue open by adding a comment (this is quite common practise).

Anyway, this tracker is for the Docker for Windows application, which uses Hyper-V. Docker Toolbox is a different solution, allowing you to run on systems without Hyper-V.  The repository for Toolbox is here: https://github.com/docker/toolbox
