### ISSUE TITLE
Uninstalling docker for windows leaves a bunch of trash on disk

### ISSUE THREAD

**Issue by ryudice** [docker/for-win#1347]
### Expected behavior
Uninstallling docker for windows removes the C:/ProgramData/Docker/windowsfilter folder

### Actual behavior
The C:/ProgramData/Docker/windowsfilter is left behind with messed up permissions that make it undeletable

### Information
When trying to remove the folder youself you get access denied, not even taking ownership of the files seems to work.

### Steps to reproduce the behavior

  1. Install docker for windows
  2. Install a windows container image
  3. Uninstall Docker for windows
  4. Go to C:/ProgramData/Docker/windowsfilter
  5. Try to delete the folder and permissions are messed up.

**Comment by curtis-g** [comment]
I am also experiencing this. Also when trying to re-install Docker for Windows the installation fails with Access Denied to the folder specified in OP's question.

I have tried renaming the folder but the issue persists. Any news on a fix or this?
![dockerforwindowsinstallfail](https://user-images.githubusercontent.com/11981305/33371016-485f6aac-d4f1-11e7-88be-76ff55cfa935.PNG)

**Comment by sagittarius-rbrisley** [comment]
This is still a problem on the latest version. You can get around it by running docker-ci-zap https://github.com/jhowardmsft/docker-ci-zap but nobody should have to :-)

**Comment by logischdenker** [comment]
Same on my side - I cannot delete the trash Docker leaves on disk after uninstalling. Are there working work arounds besides using that docker-ci-zap tool?

**Comment by potatoqualitee** [comment]
ditto D:
