### ISSUE TITLE
Docker's config file is reset upon Windows application restart

### ISSUE THREAD

**Issue by MarkHarrisCanterbury** [docker/for-win#13478]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
When the Docker desktop application is restarted in Windows the .docker/config.json file is overwritten, so that the "credsStore" key's value is changed to "desktop.exe".

### Expected behavior
When the Docker desktop application is restarted in Windows, the .docker/config.json file is not changed.

### Information
  - Windows Version: 10.0.19045
  - Docker Desktop Version: 4.19.0 (106363)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
[2023-05-11T03:54:54.557590100Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[SKIP] DD0002: does the bootloader have virtualization enabled?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[SKIP] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[SKIP] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
<3>WSL (1773) ERROR: UtilTranslatePathList:2803: Failed to translate P:\bin
<3>WSL (1773) ERROR: UtilTranslatePathList:2803: Failed to translate P:\bin
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
<3>WSL (1776) ERROR: UtilTranslatePathList:2803: Failed to translate P:\bin
<3>WSL (1776) ERROR: UtilTranslatePathList:2803: Failed to translate P:\bin
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0038: is the connection to Docker working?
[FAIL] DD0014: are the backend processes running? 1 error occurred:
        * com.docker.vpnkit.exe is not running

[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[FAIL] DD0009: is the vpnkit API responding? open \\.\pipe\dockerVpnKitDiagnostics: The system cannot find the file specified.
[PASS] DD0010: is the Docker API proxy responding?
[SKIP] DD0006: is the Docker Desktop Service responding?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?

Please investigate the following 1 issue:

1 : The test: are the backend processes running?
    Failed with: 1 error occurred:
        * com.docker.vpnkit.exe is not running

Not all of the backend processes are running.

### Steps to reproduce the behaviour
  1. Start Ubuntu WSL and Docker Desktop app in Windows
  2. In WSL, change the ~/.docker/config.json file's "credsStore" key value to "ecr-login"
  3. Restart Docker Desktop app
  4. ~/.docker/config.json file's "credsStore" key value is changed to "desktop.exe"

**Comment by linbjo** [comment]
I'm having the same problem, using version 4.20.0. It's also not only that the credStore value is changed. The entire ~/.docker/config.json file in WSL is wiped and replaced, i.e. it contains _only_ `"credStore": "desktop.exe"` after a Docker Desktop restart.

Version 4.19.0 did make it so the credStore value in the _Windows_ config.json file isn't modified on restart, but obviously the same fix didn't apply to WSL.

**Comment by tab10** [comment]
I have the same problem. Every time I try to build a Docker/Docker Compose project, it fails with EOF or similar. This only happens when calling Docker from Ubuntu WSL (I'm running Docker Desktop on Windows 11 natively). No problems building the same dockers from a Windows-based terminal

Every time I restart Docker Desktop or my computer, it resets the ~/.docker/config.json to be:
```json
{
  "auths": {},
  "credsStore": "desktop.exe"
}
```
I'm logged out of DockerHub via Docker Desktop, as that is writing to the auths key. I do add windows paths to the WSL paths (via enableinterop flag in the WSL Ubuntu config. I use the secretservice credsStore on WSL, so I change it to that and all docker build commands works fine again in WSL.

Possibly something related to resetting this would help us?
https://stackoverflow.com/questions/55188020/how-to-force-docker-login-command-to-ignore-existing-credentials-helper

**Comment by MihaelaStoica** [comment]
This issue has been fixed in Docker Desktop 4.27. See [release note](https://docs.docker.com/desktop/release-notes/#:~:text=Fixed%20a%20bug%20where%20the%20credentials%20store%20configuration%20would%20reset%20on%20app%20restart%20with%20the%20WSL%20integration.%20Fixes%20docker/for%2Dwin%2313529.).
