### ISSUE TITLE
Windows BSODing with DPC_WATCHDOG_VIOLATION error

### ISSUE THREAD

**Issue by DenMesh** [docker/for-win#13483]
I've recently upgraded from Win 7 to Win 10. The upgrade was "in-place" (i.e. a literal upgrade and not a fresh install). It was successful and the system was working flawlessly.

Several days later I installed Docker Desktop (4.19) with WSL2 backend. As soon as I tried running a container with docker-compose, I got a BSOD woth DPC_WATCHDOG_VIOLATION. Over the next two days I tried re-installing Docker Desktop several times with different backends and enabled Windows components without any luck. To be fair, it may not be an issue with Docker Desktop, as I got a similar crash trying to run docker in WSL.

Any help will be greatily appreciated!

System info:
Windows 10 Pro 22H2 build 19045.2965
Intel Core i7-2600K CPU
32 GB RAM

**Comment by ctalledo** [comment]
Hi @DenMesh, thanks for reporting. 

I looked briefly in the Docker Desktop issues but did not find any similar problem. 

Googling around I did find some reports of DPC_WATCHDOG_VIOLATION on WSL2, but none related to Docker Desktop.

As this is a Windows BSOD, please file the issue on the [WSL Github page](https://github.com/microsoft/WSL/issues). 

Thanks.
