### ISSUE TITLE
Unexpected WSL Error

### ISSUE THREAD

**Issue by Mesut-Doner** [docker/for-win#13494]
I just install Docker Desktop to my pc for first time. I have got this error when run Docker Desktop.  I updated my wsl and it is most recent version now. did uninstalling Docker Desktop and restarting pc etc. But all didnt work. 
Error:
An unexpected error was encountered while executing a WSL command. Common causes include access rights issues, which occur after waking the computer or not being connected to your domain/active directory.

**Comment by ctalledo** [comment]
Hi @mesut-dnr, sorry to hear. Could you please provide a bit more info so we can root-cause:

1) WSL version in your host (`wsl --version`).

2) If possible upload a diagnostics bundle; see [here](https://docs.docker.com/desktop/troubleshoot/overview/#diagnose-from-the-terminal) for instructions.

Thanks.
