### ISSUE TITLE
v1.12.2-rc1 shouldn't require more permissions than stable to share drives

### ISSUE THREAD

**Issue by lusitania** [docker/for-win#135]
### Expected behavior
1.12.1 stable was fine with a user in group Guests to share a drive. (Members of group Guests are not allowed to log in locally on my machine.)

### Actual behavior
1.12.2-rc1 requires a user in group Users to share drives.

### Information

  - Diagnostic ID: 5B7AC43B-CA65-42E7-98A8-B482CA7FC66D/2016-10-07_11-41-37
  - host distribution and version: Windows 10 Pro 1607, 14393.187

### Steps to reproduce the behavior

  1. create a user, join it with Guests
  2. chose a drive to share and (try to) apply

Access requirements should follow the least-privileges paradigm. Secure by default. Please don't walk this road backwards.

**Comment by rneugeba** [comment]
@dgageot could you take a look?

**Comment by simonferquel** [comment]
@rneugeba I'll take a look at it, I'm pretty sure it is related to the new credential checks we do.
Thanks for the feedback !

**Comment by simonferquel** [comment]
@lusitania can you confirm that:
- the user in question is not the special "Guest" account, just a member of the Guests group
- the Guests group is denied log on locally
- There is no other restriction on the Guests group ?

If this is the case, it should be fixed in an upcoming beta (maybe not the really next one, but soon :) )

**Comment by lusitania** [comment]
* yes, the user is *not* the built-in user Guest (which is blocked) but a custom user added to Guests
* yes, the Guests group is added to Security Settings\Local Policies\User Rights Assignments\Deny log on locally
* other than those changes mentioned above Groups has its default configuration. however, i don't know of potential transitiv effects (some settings applying to something which influences Guests)

**Comment by simonferquel** [comment]
Can you try the latest beta ? It should just work for your scenario now :)

**Comment by lusitania** [comment]
Indeed, it does. Thanks
