### ISSUE TITLE
unable to start docker 5D695B9E-993F-40F5-B853-A8BA7B5227C0/20230529075609

### ISSUE THREAD

**Issue by adarshab1** [docker/for-win#13513]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by lorenrh** [comment]
It seems you are using an old version of Docker Desktop (4.12.0 ). Can you try installing the latest version? I'll close the issue for now, but if the problem persists with the newest version available, please open a fresh ticket !
