### ISSUE TITLE
Windows Fall Creators update breaks git tools

### ISSUE THREAD

**Issue by jsmouret** [docker/for-win#1351]
Hello,

I'm not sure if it is the right place to report this as it is a mix of Windows, Docker and Git tools,
but, well, here we go.

### Expected behavior

Git tools used to work.

### Actual behavior

After installing Window Fall Creators update, any tools will return an exit code of 3221225794.

### Information

```
$ docker info
...
Default Isolation: hyperv
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
...

$ docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:50:27 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

### Steps to reproduce the behavior

- Install Windows Fall Creators update (1709)

- Copy this to git.inf to have git tools added to the PATH
```
[Setup]
PathOption=CmdTools
BashTerminalOption=ConHost
```

- Build this Dockerfile (use --no-cache to avoid getting old results prior to the update)
```
FROM microsoft/windowsservercore
ADD "https://github.com/git-for-windows/git/releases/download/v2.15.0.windows.1/Git-2.15.0-64-bit.exe" git_setup.exe
COPY git.inf .
RUN git_setup.exe /LoadInf=git.inf /silent /norestart

# Use any git tools, 'rm' in this example
RUN rm git_setup.exe git.inf
```

- The output is:
```
Sending build context to Docker daemon  3.072kB
Step 1/5 : FROM microsoft/windowsservercore
 ---> ce27208ad678
Step 2/5 : ADD "https://github.com/git-for-windows/git/releases/download/v2.15.0.windows.1/Git-2.15.0-64-bit.exe" git_setup.exe

 ---> 2dcf2eccd2a7
Step 3/5 : COPY git.inf .
 ---> 8bff85a64863
Step 4/5 : RUN git_setup.exe /LoadInf=git.inf /silent /norestart
 ---> Running in ef05d7319013
 ---> 81e2e592cf34
Removing intermediate container ef05d7319013
Step 5/5 : RUN rm git_setup.exe git.inf
 ---> Running in 418e60629e15
The command 'cmd /S /C rm git_setup.exe git.inf' returned a non-zero code: 3221225794
```

**Comment by atrauzzi** [comment]
@jsmouret - I think our issues might be the same. I'm trying to figure out how best to proceed as well: https://github.com/git-for-windows/git/issues/1403

**Comment by jsmouret** [comment]
My workaround was to avoid installing the Windows Fall Creators update :)

**Comment by jsmouret** [comment]
Still happening with:
* Git 2.16.2
* Docker 18.03.0-ce
* Windows 10.0.16299

**Comment by rn** [comment]
I don't understand this part of the dockerfile:
```
# Use any git tools, 'rm' in this example
RUN rm git_setup.exe git.inf
```

The comment does not seem to match the command or does `rm.exe` (or `rm.com` comes as part of the git tools installation (`rm` is not a build in for `cmd.exe`)?

It may be possible that the fit tools installation is not added to the path and hence `rm` fails. Can you check the path and or set it manually?

In any case this does not look a Docker for Windows (the application) issue.

**Comment by jsmouret** [comment]
`rm` comes with the git tools installation which also correctly sets the path.

The weird part is that it worked before the windows fall update.
Feel free to close the bug if it is too unrelated.
I wasn't sure where to report it as it is a combination of docker/windows/git.

**Comment by rn** [comment]
This doesn't look directly related to the Docker for Windows application, so I'm closing this, but do let us know if you find a solution. Thanks

**Comment by julioas09** [comment]
Im experiencing the same behaviour when trying to install ARR inside a container

`RUN ARRv3_setup_amd64_en-us.exe /Q`

This worked perfectly until recently.

**Comment by srbhklkrn** [comment]
@julioas09 where you manage to solve the issue?

**Comment by julioas09** [comment]
Yeah, it turns out the build agent OS revision did not match the container base image revision. This is a must in Windows Server 2016 hosts.
