### ISSUE TITLE
pull microsoft/nanoserver:  failed to register layer ... The parameter is incorrect

### ISSUE THREAD

**Issue by Grub01** [docker/for-win#1353]
### Expected behavior

Image is pulled successfully.

### Actual behavior

Using default tag: latest
latest: Pulling from microsoft/nanoserver
bce2fbc256ea: Already exists
53a0ccfb7e6f: Extracting [==================================================>]    148MB/148MB
failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage \\?\C:\ProgramData\Docker\windowsfilter\e0a5b94af328d914c4e1464bde041dd55ac7be12caf5f71a2c61b5c469daa1bb\UtilityVM: The parameter is incorrect.

### Information

  - Diagnostic ID: EFCE180F-9228-4226-AF73-E517F9A68227/2017-11-22_15-28-08.
  - Windows 10 15063.726. 
  - Latest cumulative update: KB4048954

On 4 out of 4 laptops, docker pull microsoft/nanoserver is now failing with this error.
2 of those laptops were able to pull a nanoserver image one month  ago, but now cannot pull the latest.

On one of those laptop (which also has a few images built on top of an older nanoserver) I can build new images and pull images from our private repo, but just cannot pull the latest nanoserver (or anything else built on it).

I've read the many posts related to this error and have tried:
- disabling bitlocker
- turning off bitlocker
- re-enabling bitlocker
- disabling anti-virus (F-Secure)

What else can I try?

**Comment by Grub01** [comment]
On a whim, I shut off a third party service (not AV). And I could pull it again. I'll take the problem up with them.

**Comment by friism** [comment]
In case other users stumble on this, could you share what software caused
the problem?
-- 
http://friism.com/
(650) 318-1051
Sapere aude

**Comment by Grub01** [comment]
I'll have to check with them first - but I may be able to share 'in general' what feature of the software was the problem
