### ISSUE TITLE
Docker on Windows insider build 17046

### ISSUE THREAD

**Issue by yrest** [docker/for-win#1354]
I probably should give up at this stage...
Continuing from https://github.com/docker/for-win/issues/1255 and https://github.com/docker/for-win/issues/1302 and https://github.com/docker/for-win/issues/1333 
Fourth consecutive flight, seriously?
Reported to https://aka.ms/Dm84v8 

Running
$imageNameTag = "microsoft/nanoserver-insider"
docker rm nanoserver -f
docker pull $imageNameTag
docker run -m 1G --name nanoserver `
           --hostname nanoserver `
           $imageNameTag

on 
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 17.11.0-ce
Storage Driver: windowsfilter
 Windows: 
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17046 (17046.1000.amd64fre.rs_prerelease.171118-1403)
Operating System: Windows 10 Pro Insider Preview
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 15.92GiB
Name: ip
ID: RXTU:H7CK:TCKK:6AH2:J73J:JDWP:Q42F:IMJY:NAFX:JDCX:PDNB:E25T
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 24
 System Time: 2017-11-22T22:49:08.624834Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

of 
Client:
 Version:      17.11.0-ce
 API version:  1.34
 Go version:   go1.8.4
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:30:11 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.24)
 Go version:   go1.8.5
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:34:19 2017
 OS/Arch:      windows/amd64
 Experimental: true

Getting
Digest: sha256:1f71a9dce9cc3f9a0dc4f1a0a00e74700ddc41c4798a09846fc777e99b28d7de
Status: Image is up to date for microsoft/nanoserver-insider:latest
docker : C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container cff8904f7602c40dcdc52a1e8beb0c4ccc801f8b030dc5fd9be59a0d8b60d497 
encountered an error during CreateContainer: failure in a Windows system call: The description string for parameter reference (%1) could not be found. (0x3ab6) extra

**Comment by knilecrack** [comment]
I have similar issue as well on insider preview : 170025

On docker edge. I have one VM(windows server 2016) in VMware and it works just fine.

`C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container 22a7d2899fb93034e3b5bf3f1dc20fa6348932abd8afad310e6c0faf6f63d30a encountered an error during CreateContainer: failure in a Windows system call: The description string for parameter reference (%1) could not be found. (0x3ab6) extra info: {"SystemType":"Container","Name":"22a7d2899fb93034e3b5bf3f1dc20fa6348932abd8afad310e6c0faf6f63d30a","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\22a7d2899fb93034e3b5bf3f1dc20fa6348932abd8afad310e6c0faf6f63d30a","Layers":[{"ID":"8e8c5365-9e46-5a55-acfd-a8a66cca4771","Path":"C:\\ProgramData\\Docker\\windowsfilter\\2758de565f3681deb6925fd7155ec31fc947d0201650eff26600c56986278a22"},{"ID":"203a3620-ad65-5494-b311-7c709b44866b","Path":"C:\\ProgramData\\Docker\\windowsfilter\\3935ce80d48141d6b194353a2d83f2596fd7c5637473b9ef20e7e1483d1a2c92"},{"ID":"d8f2618e-63c5-55b6-acc5-2fb473f5383d","Path":"C:\\ProgramData\\Docker\\windowsfilter\\ee89200cc0ceb5bd3ccf054b1b0446a24c7f092b0666645d1beb828e4ffe15be"},{"ID":"c74e97df-e25c-5153-b228-26e8d61be780","Path":"C:\\ProgramData\\Docker\\windowsfilter\\1f1535b706c6706e65209068c3cd122ac1a7fa5d208b5b4cb8e74776ce2c1270"}],"HostName":"22a7d2899fb9","HvPartition":true,"EndpointList":["1b6cab3f-3f59-4cdb-b0d2-ba56baa426ec"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\ee89200cc0ceb5bd3ccf054b1b0446a24c7f092b0666645d1beb828e4ffe15be\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}.`

**Comment by quangkieu** [comment]
@knilecrack 
https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility#errors-from-mismatched-versions
According to that document I think you have to pull and run the correct version of the base container as the "lastest" which is their default tag is using for LTS Windows.
When I run docker run -it microsoft/nanoserver:1709 cmd, I do not have that error anymore.
