### ISSUE TITLE
Unexpected error was encountered while executing a WSL command

### ISSUE THREAD

**Issue by mfb1909** [docker/for-win#13559]
### Description

I get the following error message:

An unexpected error was encountered while executing a WSL command. Common causes include access rights issues, which occur after waking the computer or not being connected to your domain/active directory.
Please try shutting WSL down (wsl --shutdown) and/or rebooting your computer. If not sufficient, WSL may need to be reinstalled fully. As a last resort, try to uninstall/reinstall Docker Desktop. If the issue persists please collect diagnostics and submit an issue (https://docs.docker.com/desktop/troubleshoot/overview/#diagnose-from-the-terminal).

### Reproduce

- Opening the docker app

- Any "docker run" command produces the following error:
docker: error during connect: this error may indicate that the docker daemon is not running: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/create": open //./pipe/docker_engine: The system cannot find the file specified.
See 'docker run --help'.

### Expected behavior

To be able to run a docker container

### docker version

```bash
Client:
 Version:           23.0.1-rd
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        393499b
 Built:             Fri Feb 10 16:56:32 2023
 OS/Arch:           windows/amd64
 Context:           default
error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version": open //./pipe/docker_engine: The system cannot find the file specified.
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     C:\Users\MeganBorland\.docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.14.0
    Path:     C:\Users\MeganBorland\.docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.19
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  v0.12.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
ERROR: error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/info": open //./pipe/docker_engine: The system cannot find the file specified.      
errors pretty printing info
```

### Diagnostics ID

01CD5916-4883-44EF-A4E6-1BC95D755B96\20230621094218

**Comment by lorenrh** [comment]
This seems like a duplicate of https://github.com/docker/for-win/issues/13549

**Comment by mfb1909** [comment]
> This seems like a duplicate of #13549

What was the solution?

**Comment by mfb1909** [comment]
UPDATE: I have uninstalled Docker Desktop and did a factory reset on Rancher. Everything now works as expected

**Comment by ngothankphuong** [comment]
can you show me how to reset on Rancher, thanks

**Comment by eraykaraman** [comment]
any solution?

**Comment by MiskuDD** [comment]
Have the same issue.

**Comment by Acvmw** [comment]
Also having that issue

**Comment by mfb1909** [comment]
> can you show me how to reset on Rancher, thanks
Go on Troubleshooting, then Factory Reset is the red button :) 

![image](https://github.com/docker/for-win/assets/72493286/3c114110-3e1c-4ce7-8369-2fcfd17ea470)

**Comment by Kilvny** [comment]
**For everyone struggling, I've been in this place, and the steps I followed:**

1. wsl --shutdown 
2. first of all make sure you have `wsl -s <myDistro>` by running wsl -l  _(e.g. Ubuntu you should fond the default set to Ubuntu)_
3. wsl  ~ -e zsh
4. sudo nano /etc/pam.d/chsh
5. Replacing

- `auth       required   pam_shells.so`
with
- `auth       sufficient   pam_shells.so`


then `exit` and rerun wsl 

I hope you find this helpful

**Comment by gornication** [comment]
PS C:\Users\Administrator> wsl --list
`Windows Subsystem for Linux has no installed distributions.`
PS C:\Users\Administrator> wsl -s Ubuntu
`There is no distribution with the supplied name.`
PS C:\Users\Administrator> wsl --list --online
```
The following is a list of valid distributions that can be installed.
NAME                                   FRIENDLY NAME
Ubuntu                                 Ubuntu
Debian                                 Debian GNU/Linux
kali-linux                             Kali Linux Rolling
Ubuntu-18.04                           Ubuntu 18.04 LTS
Ubuntu-20.04                           Ubuntu 20.04 LTS
Ubuntu-22.04                           Ubuntu 22.04 LTS
OracleLinux_7_9                        Oracle Linux 7.9
OracleLinux_8_7                        Oracle Linux 8.7
OracleLinux_9_1                        Oracle Linux 9.1
openSUSE-Leap-15.5                     openSUSE Leap 15.5
SUSE-Linux-Enterprise-Server-15-SP4    SUSE Linux Enterprise Server 15 SP4
SUSE-Linux-Enterprise-15-SP5           SUSE Linux Enterprise 15 SP5
openSUSE-Tumbleweed                    openSUSE Tumbleweed
```
PS C:\Users\Administrator> wsl --install Ubuntu
```
Ubuntu is already installed.
Launching Ubuntu...
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370102
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/enablevirtualization
Press any key to continue...
PS C:\Users\Administrator>
```

**Comment by SimonHolzknecht** [comment]
Hi, don't know if this thread is still active but I encountered the same issue with "ensure virtualization is enabled".

After many different approaches I tried what was advertised in https://learn.microsoft.com/en-us/windows/wsl/troubleshooting#error-0x80370102-the-virtual-machine-could-not-be-started-because-a-required-feature-is-not-installed:

- execute "bcdedit /enum | findstr -i hypervisorlaunchtype" (administator cmd console)
- if you see "hypervisorlaunchtype Off", type "bcdedit /set hypervisorlaunchtype Auto"
- restart the computer

Though I would share as this issue drove me insane as everything seemed to be enabled...

**Comment by XiuXiang-GitHub** [comment]
> 您好，不知道该线程是否仍处于活动状态，但我遇到了与“确保启用虚拟化”相同的问题。
> 
> [经过许多不同的方法后，我尝试了https://learn.microsoft.com/en-us/windows/wsl/troubleshooting#error-0x80370102-the-virtual-machine-could-not-be-started-because-](https://learn.microsoft.com/en-us/windows/wsl/troubleshooting#error-0x80370102-the-virtual-machine-could-not-be-started-because-a-required-feature-is-not-installed)中宣传的内容[未安装所需功能](https://learn.microsoft.com/en-us/windows/wsl/troubleshooting#error-0x80370102-the-virtual-machine-could-not-be-started-because-a-required-feature-is-not-installed)：
> 
> * 执行“bcdedit /enum | findstr -i hypervisorlaunchtype”（管理员cmd控制台）
> * 如果您看到“hypervisorlaunchtype Off”，请键入“bcdedit /set hypervisorlaunchtype Auto”
> * 重新启动计算机
> 
> 尽管我会分享，因为这个问题让我发疯，因为一切似乎都已启用......

解决了，万分感谢

**Comment by ryanpanta** [comment]
> Hi, don't know if this thread is still active but I encountered the same issue with "ensure virtualization is enabled".
> 
> After many different approaches I tried what was advertised in https://learn.microsoft.com/en-us/windows/wsl/troubleshooting#error-0x80370102-the-virtual-machine-could-not-be-started-because-a-required-feature-is-not-installed:
> 
> * execute "bcdedit /enum | findstr -i hypervisorlaunchtype" (administator cmd console)
> * if you see "hypervisorlaunchtype Off", type "bcdedit /set hypervisorlaunchtype Auto"
> * restart the computer
> 
> Though I would share as this issue drove me insane as everything seemed to be enabled...

Thx my man!!!!

**Comment by praveen-1624** [comment]
bcdedit /enum | findstr -i hypervisorlaunchtype is auto but still unable to install docker or hypervisor
