### ISSUE TITLE
Docker Desktop issue

### ISSUE THREAD

**Issue by amufeetha** [docker/for-win#13556]
### Description

Unable start docker desktop

### Reproduce

open decker desktop
docker pull rabbitmq:3.11.18-management
error during connect: this error may indicate that the docker daemon is not running: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/images/create?fromImage=rabbitmq&tag=3.11.18-management": open //./pipe/docker_engine: The system cannot find the file specified.

### docker version

```bash
4.19.0 (106363)
```

### docker info

```bash
Engine: 23.0.5

Compose: v2.17.3

Credential Helper: v0.7.0

Kubernetes: v1.25.9
```

### Diagnostics ID

2A112ADC-0A6E-4A36-800A-707C8F48A459/20230620123453

**Comment by lorenrh** [comment]
The command you are looking for is probably `docker image pull  rabbitmq:3.11.18-management`. There doesn't seem to be an error with Docker Desktop, so I'll close this issue.
