### ISSUE TITLE
Docker Desktop 4.20.1 cannot pull image

### ISSUE THREAD

**Issue by CitrixMing** [docker/for-win#13553]
### Description

我在windows系统是通过启用hyper-v安装了docker desktop 4.20.1，无法拉取镜像，提示提取映像配置时出错：尝试次数=6后下载失败：使用直接连接拨打production.cloudflare.docker.com:443：连接到104.18124.25:443：拨号tcp 104.18124.25:443：connectex：连接尝试失败，因为连接方在一段时间后没有正确响应，或者由于连接的主机没有响应而建立的连接失败

### Reproduce

C:\Users\hp>docker pull nginx
Using default tag: latest
[2023-06-18T11:45:51.913416100Z][docker-credential-desktop][W] Windows version might not be up-to-date: The system cannot find the file specified.
latest: Pulling from library/nginx
5b5fe70539cd: Retrying in 1 second
441a1b465367: Retrying in 1 second
3b9543f2b500: Retrying in 1 second
ca89ed5461a9: Waiting
b0e1283145af: Waiting
4b98867cde79: Waiting
4a85ce26214d: Waiting
error pulling image configuration: download failed after attempts=6: dialing production.cloudflare.docker.com:443 with direct connection: connecting to 104.18.124.25:443: dial tcp 104.18.124.25:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

### Expected behavior

I tried to delete all containers and uninstall Docker to reinstall, but still couldn't pull the image. And even if you enter an image in the search bar of Docker Desktop, you cannot find it

### docker version

```bash
C:\Users\hp>docker version
Client:
 Cloud integration: v1.0.33
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:53:15 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.20.1 (110738)
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:52:17 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
C:\Users\hp>docker info
Client:
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.5
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.19
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  v0.12.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.49-linuxkit-pr
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.938GiB
 Name: docker-desktop
 ID: 80c3fe7c-ffc4-4a2f-8c2b-c700dbfcc55b
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### Diagnostics ID

80c3fe7c-ffc4-4a2f-8c2b-c700dbfcc55b

**Comment by KTXKIKI** [comment]
我也是   不知道是不是国内镜像源服务器出问题了

**Comment by CitrixMing** [comment]
我想应该是的，还有个现象是docker desktop中的搜索栏里面无法到镜像了，不知道你的是否也是这样的

**Comment by KTXKIKI** [comment]
一样  拉不下来  只能翻墙  挂vpn  而且挂vpn也下不下来  一直断   下好几百回才拉镜像下来   不知道docker官方hub的问题还是国内  镜像源服务器的问题   docker官方有没有什么办法通知一下他们

**Comment by CitrixMing** [comment]
看报错信息production.cloudflare.docker.com:443是docker镜像部署在cloudflare上的节点问题吧，我稍晚点尝试联系一下Docker Team看看

**Comment by staoran** [comment]
截至目前还是不行

**Comment by dyx0226** [comment]
目前还是不行,有其他的nginx镜像源推荐吗

**Comment by geekyouth** [comment]
十万火急，项目无法上线，国内源全都试了超时

**Comment by staoran** [comment]
翻墙吧，换源不生效，还是一样解析到 cloudflare

**Comment by CitrixMing** [comment]
服务应该是恢复了，现在可以正常拉取镜像了。但是官网无法访问

**Comment by trungutt** [comment]
Sorry we could not help as we could not understand the issue

**Comment by wyx040821** [comment]
我通过修改镜像源解决了问题：
{
"max-concurrent-downloads": 10,
"max-concurrent-uploads": 5,
"default-shm-size": "1G",
"debug": true,
"experimental": false,
"registry-mirrors":[
"https://x9r52uz5.mirror.aliyuncs.com",
"https://dockerhub.icu",
"https://docker.chenby.cn",
"https://docker.1panel.live",
"https://docker.awsl9527.cn",
"https://docker.anyhub.us.kg",
"https://dhub.kubesre.xyz"
]
}
 #参考这篇教程：https://www.cnblogs.com/lxzcloud/p/18354640

**Comment by bryanxtong** [comment]
> 我通过修改镜像源解决了问题： { "max-concurrent-downloads": 10, "max-concurrent-uploads": 5, "default-shm-size": "1G", "debug": true, "experimental": false, "registry-mirrors":[ "https://x9r52uz5.mirror.aliyuncs.com", "https://dockerhub.icu", "https://docker.chenby.cn", "https://docker.1panel.live", "https://docker.awsl9527.cn", "https://docker.anyhub.us.kg", "https://dhub.kubesre.xyz" ] } #参考这篇教程：https://www.cnblogs.com/lxzcloud/p/18354640

Thanks. I tried in docker desktop and It works.

Docker Desktop-> Settings-> Docker Engine,  and paste the text below

{
  "builder": {
    "gc": {
      "defaultKeepStorage": "20GB",
      "enabled": true
    }
  },
  "debug": true,
  "default-shm-size": "1G",
  "experimental": false,
  "max-concurrent-downloads": 10,
  "max-concurrent-uploads": 5,
  "registry-mirrors": [
    "https://x9r52uz5.mirror.aliyuncs.com",
    "https://dockerhub.icu",
    "https://docker.chenby.cn",
    "https://docker.1panel.live",
    "https://docker.awsl9527.cn",
    "https://docker.anyhub.us.kg",
    "https://dhub.kubesre.xyz"
  ]
}

**Comment by YasonGF** [comment]
> 我通过修改镜像源解决了问题： { "max-concurrent-downloads": 10, "max-concurrent-uploads": 5, "default-shm-size": "1G", "debug": true, "experimental": false, "registry-mirrors":[ "https://x9r52uz5.mirror.aliyuncs.com", "https://dockerhub.icu", "https://docker.chenby.cn", "https://docker.1panel.live", "https://docker.awsl9527.cn", "https://docker.anyhub.us.kg", "https://dhub.kubesre.xyz" ] } #参考这篇教程：https://www.cnblogs.com/lxzcloud/p/18354640

我也是镜像源的问题
