### ISSUE TITLE
Docker wont run

### ISSUE THREAD

**Issue by Ronardminer** [docker/for-win#13554]
### Description

Docker Engine wont run and stop.

### Reproduce

docker run

### Expected behavior

Docker should run after clicking

### docker version

```bash
same
```

### docker info

```bash
same
```

### Diagnostics ID

01075F7B-9EF7-45D2-9614-8D9CC4270C19/20230618143030

**Comment by p1-0tr** [comment]
hi @Ronardminer, thanks for reporting the issue and sorry for the inconvenience. It seems that one of the WSL distros Docker Desktop relies on is missing its drive. Could you unregister that distro `wsl --unregister docker-desktop-data` and try running Docker Desktop again?

**Comment by lorenrh** [comment]
We have released Docker desktop 4.21.1, containing a fix for this issue, please see https://docs.docker.com/desktop/release-notes/
