### ISSUE TITLE
Docker Desktop on start throws exception and stops running when running in user context

### ISSUE THREAD

**Issue by PretoPlasma** [docker/for-win#13555]
### Description

When starting fresh installed docker desktop on windows 10 (21H2) the program throws the following exception:

![image](https://github.com/docker/for-win/assets/107237119/c03d1cc8-311b-4f58-9293-13bb1b08ebfe)

wsl2 ist installed correctly because it works fine with rancher desktop.
rancher desktop is stopped before trying to execute docker desktop.
The user executing the program is member of the local docker-user group.

So prerequisites should be fulfilled.

Running docker desktop as admin does not lead into this issue.
So I assume that something goes wrong with a standard user being assigned to the docker-user group whilst executing the program.

### Reproduce

Start docker desktop with an windows account with user previlege and member of the local docker-users group.
After launching the program the spinner appears after that the exception modal.
After closing the exception modal the program terminates.
Then wsl -l -v does not deliver any response. OS needs a restart to get wsl running again.

### Expected behavior

The program should launch without exceptions. It should start wsl and offer normal program functions.

### docker version

```bash
Client:
 Cloud integration: v1.0.33
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:53:15 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.20.1 (110738)
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:52:17 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     C:\Users\...\.docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.6.1
    Path:     C:\Users\...\.docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.19
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  v0.12.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 5.10.16.3-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 24.75GiB
 Name: docker-desktop
 ID: 7ff29af1-2b90-4331-ba5c-5be65c2fe5b7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### Diagnostics ID

can not be generated.

### Additional Info

The Diagnostics ID can not be generated because the program terminates before having the ability to start the appropriate function.

**Comment by p1-0tr** [comment]
hi @PretoPlasma, thanks for reporting the issue and sorry for the inconvenience. I suspect there may be some adverse interaction between DD and Rancher. The first thing I would check is the output of `wsl -l -v --all`, most importantly which distro is set as the default one. If it is a Rancher specific distro, change the default to a regular one (e.g. Ubuntu/Debian/...), or alternatively edit `%userprofile%\AppData\Roaming\Docker\settings.json` such that 

    "integratedWslDistros": [],
    "enableIntegrationWithDefaultWslDistro": false,
 
 If that does not help you can gather diagnostics without DD running, to do that follow - https://docs.docker.com/desktop/troubleshoot/overview/#diagnose-from-the-terminal .

**Comment by PretoPlasma** [comment]
@p1-0tr thanks for your quick reply. Updating my settings.json with the given values made the trick!
I can now use docker desktop as non-admin user! Many thanks!

**Comment by lorenrh** [comment]
Thanks for your report, I'll close the issue now that it's solved for you!
