### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by PierrunoYT** [docker/for-win#13565]
### Description

Using default tag: latest
Error response from daemon: error creating temporary lease: write /var/lib/desktop-containerd/daemon/io.containerd.metadata.v1.bolt/meta.db: read-only file system: unknown

### Reproduce

Tried to setup AutoGPT

### docker version

```bash
Newest
```

### docker info

```bash
idk
```

### Diagnostics ID

idk

**Comment by bsousaa** [comment]
There is not enough detail in this issue that hints to the presence of a bug in Docker Desktop. I'm closing for now but feel free to open a new issue in case you are facing a potential bug. 

For paid or community support check https://github.com/docker/for-win for more details.
