### ISSUE TITLE
RAM/memory allocation with LCOW/windows containers?

### ISSUE THREAD

**Issue by rlpowell** [docker/for-win#1357]
### Expected behavior

I expected LCOW mode to give my containers access to all of my Windows' box's RAM.

### Actual behavior

The RAM appears to be capped to 1G, per /proc/meminfo

Also, there is no longer anything in the Docker Settings to change it.

### Information

B20175AC-8170-4955-8409-C1846A7F82E7/2017-11-24_12-20-54

```
C:\Users\rlpowell>systeminfo | findstr em
System Boot Time:          2017-11-24, 11:51:51
System Manufacturer:       LENOVO
System Model:              20AQCTO1WW
System Type:               x64-based PC
System Directory:          C:\WINDOWS\system32
System Locale:             en-us;English (United States)
Total Physical Memory:     7,901 MB
Available Physical Memory: 4,486 MB
Virtual Memory: Max Size:  17,071 MB
Virtual Memory: Available: 7,411 MB
Virtual Memory: In Use:    9,660 MB
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

C:\Users\rlpowell>docker run -it rlpowell/shell head /proc/meminfo
MemTotal:         995516 kB
MemFree:          828124 kB
MemAvailable:     763408 kB
Buffers:            2668 kB
Cached:            20488 kB
SwapCached:            0 kB
Active:            15280 kB
Inactive:          10580 kB
Active(anon):      12572 kB
Inactive(anon):    10572 kB

C:\Users\rlpowell>docker run -it rlpowell/shell free -g
              total        used        free      shared  buff/cache   available
Mem:              0           0           0           0           0           0
Swap:             0           0           0

C:\Users\rlpowell>docker run -it rlpowell/shell free -m
              total        used        free      shared  buff/cache   available
Mem:            972         113         808          20          50         745
Swap:             0           0           0
```

### Steps to reproduce the behavior

Run any linux contain in Windows Container mode.

**Comment by rlpowell** [comment]
This appears, at first glance, to be equivalent to https://github.com/Microsoft/opengcs/issues/145 , which is linked from https://github.com/moby/moby/issues/33850 .

(Which is unfortunate, as several of my compilation steps require 2G just to show up, so I can't test LCOW at all ;_; )

**Comment by liquidboy** [comment]
I encountered this limitation when trying to use Node in a LCOW container  where node was trying to go above 2GB and hitting an "out of memory exception".  I was using Node in a LCOW as a build agent.  Please let us increase this hard limit above 2GB

**Comment by fizxmike** [comment]
Any update on this? I'm launching a java app in a container and it freaks out that it "sees" only ~900 MB available and dies (of course things work find on linux docker host).

The closest answer I got was in this [cryptic post](https://github.com/aws/amazon-ecs-agent/issues/1144#issuecomment-353654710) mentioning JOB_OBJECT_LIMIT_JOB_MEMORY, but I don't know how to implement, my Windows Foo is very weak.

FYI, I'm running windows server 1709 and docker (17.10.0-ee-preview-3)

**Comment by bloodybeet** [comment]
Could someone please provide an estimate for when we can run LCOW with +2GB RAM? We would very much like to use LCOW mostly to be able to bind to localhost whilst still using linux containers (or has anyone found out how to do that with the MobyLinux VM?)

**Comment by icenine457** [comment]
Also looking for this issue to be fixed, as I'm containerizing a ASP.Net application using SQL Server, which requires 2 GB RAM to run.

**Comment by greyphoenix** [comment]
+1 for this.

**Comment by pccruiser** [comment]
+4096 for this!

Same situation. Want to use SQL Linux in a container while also testing asp.net application that requires windows. No reason this can't be done other than an arbitrary memory limit! I have 32GB of RAM so that is very frustrating!!

**Comment by jimpriest** [comment]
Just ran into this myself.  Not enough memory.

**Comment by KwalityKoder** [comment]
This is a massive blocker for us. We have a Linux container running WildFly that needs (and gets 3Gb) when Docker for Windows is running in Linux Container mode.
Switching Docker for Windows to Windows Container mode, I can see (using cat /proc/meminfo) that the same container is only given less than 1Gb of memory, and WildFly consequently dies.

**Comment by bloodybeet** [comment]
I almost can't believe how much of a blocker this is for real-world usage
for so long for so many of us. As if it's being witheld on purpose, to fix
some other issues first?

Op wo 21 nov. 2018 om 19:22 schreef Mark Hemingway <notifications@github.com

**Comment by SteveTownsendBway** [comment]
My experience is that this can be worked around by building your own dockerd using the master branch merged (locally) into the pull here https://github.com/moby/moby/pull/37296 that **fixes** this issue. The merge to master is pending but I could not wait. I am now able to _docker run --memory 6144m_ for example. 
In my case this was needed to get Linux SQL Server up and running: needs 2GB, but without fix, hard limit is 1GB.

**Comment by KwalityKoder** [comment]
@SteveTownsendBway We plan to use docker-compose to run our Linux containers via LCOW. 
Will https://github.com/moby/moby/pull/37296 fix this issue for docker-compose too?
Will the docker-compose mem_reservation: flag suddenly start working again? Or will a new PR be required for docker-compose?

**Comment by DecisionSystems** [comment]
Problem for us as well.  Trying to run .Net Framework container alongside Linux container on Windows 10 Build 17134 and latest Docker with LCOW enabled. Let a guy experiment please!

**Comment by SteveTownsendBway** [comment]
I don’t know Mark. Maybe the implementor or code reviewer can comment.

**Comment by qbikez** [comment]
> Will the docker-compose mem_reservation: flag suddenly start working again? Or will a new PR be required for docker-compose?

After applying moby/moby#37296, `mem_limit` in docker-compose works. `mem_reservation` still gives an error: "invalid option: Windows does not support MemoryReservation".

**Comment by sreejith-mq** [comment]
As other people have mentioned, this is pretty much covered under moby/moby#37296.  According to the latest comment on that thread, the feature is now part of docker nightly builds.  However no ETA on when this will be part of edge/stable of CE or EE

**Comment by idontsov** [comment]
Any update?

**Comment by AAATechGuy** [comment]
faced similar issue today. 
![image](https://user-images.githubusercontent.com/3484074/115107475-dfa70680-9f1f-11eb-86d6-a85f422813c4.png)
