### ISSUE TITLE
How to change the language?

### ISSUE THREAD

**Issue by xyxyn** [docker/for-win#13587]
### Description

How to change the language?
docker desktop: Version 4.21.1 (114176)

### Reproduce

docker desktop: Version 4.21.1 (114176)

### docker version

```bash
docker desktop: Version 4.21.1 (114176)
```

### docker info

```bash
docker desktop: Version 4.21.1 (114176)
```

### Diagnostics ID

docker desktop: Version 4.21.1 (114176)

**Comment by trungutt** [comment]
Hey @xyxyn for now Docker Desktop only supports English. Feel free to reopen a new item in our public roadmap https://github.com/docker/roadmap

**Comment by xyxyn** [comment]
thanks
