### ISSUE TITLE
docker for windows desktop update not verified

### ISSUE THREAD

**Issue by suiluj** [docker/for-win#13595]
### Description

I tried to update my docker desktop but the update was not verified. In the past it was always verified if I remember correctly. So I did not update

### Reproduce

windwos docker desktop gui click on download update ... update and restart

You're currently on version 4.20.1 (110738). The latest version is 4.21.1 (114176).

install process asks for admin permission but it does show up and unknown origin and not verified.

### Expected behavior

verified organization

### docker version

```bash
a
```

### docker info

```bash
b
```

### Diagnostics ID

d

**Comment by lorenrh** [comment]
Thanks for the report, this should be fixed now! 

Could you try to remove the downloaded update with 
`Get-bitstransfer –allusers | remove-bitstransfer`, restart Docker Desktop, and try the update again?

**Comment by suiluj** [comment]
Thanks. I cleaned the old download with your command and the new one was certified/verified Docker Inc.

Perfect! This was fast. ;) And I felt more secure to install the update. :)
