### ISSUE TITLE
Docker Desktop is unable to detect a Hypervisor.

### ISSUE THREAD

**Issue by fsromero** [docker/for-win#13596]
### Description

I get this message to directs me to:
https://docs.docker.com/desktop/windows/troubleshoot/#virtualization
But this doesn't solve anything
![image](https://github.com/docker/for-win/assets/127243756/2035c1ce-f500-4e4b-9260-94c6ac564365)

### Reproduce

1. Open Docker

### Expected behavior

It should open

### docker version

```bash
4.21.1
```

### docker info

```bash
-
```

### Diagnostics ID

3C074094-B27E-4C6B-B9BA-1A17CBD7F491/20230711170819

**Comment by trungutt** [comment]
Thanks for reporting! This looks like it's tracked by https://github.com/docker/for-win/issues/13575
