### ISSUE TITLE
Docker Desktop is unable to detect a Hypervisor. Hardware assisted virtualization and data execution protection must be enabled in the BIOS.

### ISSUE THREAD

**Issue by Kanishkasingla** [docker/for-win#13590]
### Description

Docker Desktop is unable to detect a Hypervisor. Hardware assisted virtualization and data execution protection must be enabled in the BIOS.

### Reproduce

try running docker

### docker version

```bash
4.21.1
```

### docker info

```bash
info
```

### Diagnostics ID

6021B1F9-EA4A-4552-8BBC-E52372B406B7/20230708113851

**Comment by Priyanshu88** [comment]
I am also facing Same error and below pops-up. I tried stackoverflow solutions but issue did not resolve and do not have options of Hyper -V components in my windows features on or off. I am using Windows 11 Home currently.
![image](https://github.com/docker/for-win/assets/86107841/563e4f1d-2799-416c-bb25-9aec4d3ce739)

**Comment by lorenrh** [comment]
seems like a duplicate of https://github.com/docker/for-win/issues/13575

**Comment by Priyanshu88** [comment]
Issue https://github.com/docker/for-win/issues/13575 is not solved yet.

**Comment by Priyanshu88** [comment]
Hey @Kanishkasingla, Try the approach which I mentioned here: https://github.com/docker/for-win/issues/13575#issuecomment-1636668544
