### ISSUE TITLE
Error grabbing logs: invalid character '\x00' looking for beginning of value

### ISSUE THREAD

**Issue by lamusjc** [docker/for-win#13597]
### Description

Hello, I have constantly had this error, in fact, I had it before, but I thought that with the new version of Docker 4.21.1 it would be solved.

Sometimes I reset the container every 24 hours, and sometimes, sometimes not, but sometimes when the computer reboots, and tries to start the container I get this error ""Error grabbing logs: invalid character '\x00' looking for beginning of value "I don't know exactly what exact moment it happens, but it has a lot to do with the reboot, and also when the computer is idle.

I wish it could be to solve it. Thank you.

### Reproduce

docker run <container>

### docker version

```bash
Client:
 Cloud integration: v1.0.35
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:53:15 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.21.1 (114176)
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:52:17 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
```

### docker info

```bash
Client:
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.19.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.6
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  0.16.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 3
  Running: 1
  Paused: 0
  Stopped: 2
 Images: 3
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.49-linuxkit-pr
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 10
 Total Memory: 7.771GiB
 Name: docker-desktop
 ID: 85a0d2fd-e5ea-4194-adf6-05897950cfe9
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### Diagnostics ID

4B94FDD1-ED81-4127-983C-7DECF9E44A1C/20230712071401

**Comment by lamusjc** [comment]
This error occurs when I restart the computer, once when Windows starts and there is the login screen, wait a few minutes for the screen to go black, when docker-compose resets to this "black screen" state and login, I get this super weird error:


Error grabbing logs: invalid character '\x00' looking for beginning of value


I think it is related to the Docker Desktop, but I don't know if you have any idea about this?

**Comment by lamusjc** [comment]
Ok, I know what happens, when the container is running, I reset the computer, I leave the home screen absent, after a few minutes that error appears.

**Comment by trungutt** [comment]
Hey @lamusjc could you please attach a screenshot for us to know what's happening?

Also, if you can share minimul reproduction steps (which indicates the compose app you're using for example), that might be helpful

**Comment by lamusjc** [comment]
> Hey @lamusjc could you please attach a screenshot for us to know what's happening?
> 
> Also, if you can share minimul reproduction steps (which indicates the compose app you're using for example), that might be helpful

Hello, thanks for answering.

I don't have a screenshot, because I removed Docker Desktop, and started using WSL 2 (I used Hyper-V before), and I stopped getting this error, also, I can show you the code I use for docker-compose is the following:

```
version: '3'
services:
   restarter:
     container_name: restart_container
     image:docker:cli
     volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
     command: ["/bin/sh", "-c", "while true; do sleep 86400; docker restart stream; done"]
     restart: unless-stopped
```

Basically what I do is reset it every 24 hours, but for testing, I used 10 seconds, and when I used this reset every time the PC was absent, or sometimes it gave this error, I do it to free up RAM in the container.

**Comment by lamusjc** [comment]
Well, the error stopped appearing when using WSL 2 instead of Hyper-V, so I'll consider this thread solved.
