### ISSUE TITLE
shared devices should be shared paths

### ISSUE THREAD

**Issue by lusitania** [docker/for-win#136]
All my docker stuff lives deep inside my home folder, neatly separated from any confidential content. 
### Expected behaviour

Windows shares should only provide access to "secured areas" rather than exposing the whole disk. Security models should be multi-layered, in this case: shares level, user account level and folder permissions.
### Actual behaviour

The whole disk is exposed on the shares level. A secured user account has to be provided by the system's owner. Folder permissions are not reduced according to least-privileges.
### Information
- Diagnostic ID: 5B7AC43B-CA65-42E7-98A8-B482CA7FC66D/2016-10-07_11-41-37
- host distribution and version: Windows 10 Pro 1607, 14393.187
### Steps to reproduce the behavior
1. create a dedicated, limited user
2. share a folder

**Comment by dgageot** [comment]
@lusitania FWIW, you can already create a dedicated user that has access to only a sub-folder, not the whole C drive. Then you can use that user's pwd to share the drive in Docker for Windows UI

**Comment by lusitania** [comment]
@dgageot I am aware of this, however, this is not the idea of [least privileges](https://en.wikipedia.org/wiki/Principle_of_least_privilege).

**Comment by jasonbivins** [comment]
Entered as an enhancement request - issue #7424
