### ISSUE TITLE
Docker engine faild to work

### ISSUE THREAD

**Issue by ibrahimAli-dev** [docker/for-win#13605]
### Description

when open docker not working

### Reproduce

docker not working

### Expected behavior

docker not strat

### docker version

```bash
version 20.10.17
```

### docker info

```bash
Docker not run
```

### Diagnostics ID

1603FECA-702E-4C90-B7B8-BF3E8AE37CD6/20230716224445

### Additional Info

bug

**Comment by lorenrh** [comment]
We don't have enough information to investigate this issue, so I'm closing this. If the issue persists, feel free to open a fresh issue with detailed information
