### ISSUE TITLE
Failed to use docker cli on fresh install

### ISSUE THREAD

**Issue by wbehrens-on-gh** [docker/for-win#13608]
### Description

After a fresh install of the command line tools and adding myself to the docker group I can't do anything.

### Reproduce

1. Install from https://download.docker.com/win/static/stable/x86_64/docker-24.0.2.zip
2. Add user to docker group with `net localgroup docker-users %USERNAME% /add` 
3. run `dockerd.exe --register-service` 
4. restart the machine
5. run `docker ps`

```
error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json": open //./pipe/docker_engine: Access is denied.
```

### Expected behavior

See a (empty) list of running containers

### docker version

```bash
Client:
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:53:15 2023
 OS/Arch:           windows/amd64
 Context:           default
error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version": open //./pipe/docker_engine: Access is denied.
```

### docker info

```bash
Client:
 Version:    24.0.2
 Context:    default
 Debug Mode: false

Server:
ERROR: error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/info": open //./pipe/docker_engine: Access is denied.
errors pretty printing info
```

### Diagnostics ID

N/A

**Comment by lorenrh** [comment]
Could you try downloading a recent version of Docker Desktop on Windows?
See https://docs.docker.com/desktop/install/windows-install/

Closing this for now, if the issue persists in the newest version, feel free to open a new issue.

**Comment by wbehrens-on-gh** [comment]
@lorenrh I'm not using docker desktop, I'm using just the cli tools as this needs to run on a build helper for a cd/ci system

**Comment by lorenrh** [comment]
Right, well this issue tracker is for Docker Desktop, so can't really help out :/
