### ISSUE TITLE
Docker CLI hints writes to STDERR

### ISSUE THREAD

**Issue by asoldo11** [docker/for-win#13602]
### Description

With latest Docker for Desktop version, there is a new option to show CLI hints when executing docker cli commands. Problem is that these hints are not written into STDOUT, but in STDERR, which is confusing. 

For example, when docker pull <IMAGE_ID> is performed and when successful, basic info related to that image is displayed in STDOUT. But, at the same time, STDERR contains hint to try docker scout.

### Reproduce

When hints are turned on:

1. $ docker pull busybox:latest 2>errors.txt
latest: Pulling from library/busybox
Digest: sha256:2376a0c12759aa1214ba83e771ff252c7b1663216b192fbe5e0fb364e952f85c
Status: Image is up to date for busybox:latest
docker.io/library/busybox:latest

2. $ cat errors.txt

[1mWhat's Next?
[0m  View summary of image vulnerabilities and recommendations → [36mdocker scout quickview busybox:latest[0m

When hints are turned off:

1. $ docker pull busybox:latest 2>errors.txt
latest: Pulling from library/busybox
Digest: sha256:2376a0c12759aa1214ba83e771ff252c7b1663216b192fbe5e0fb364e952f85c
Status: Image is up to date for busybox:latest
docker.io/library/busybox:latest

2. $ cat errors.txt

### Expected behavior

When hints are turned on, they should be displayed into STDOUT, not STDERR. For instance, docker pull should look like:

1. $ docker pull busybox:latest 
latest: Pulling from library/busybox
Digest: sha256:2376a0c12759aa1214ba83e771ff252c7b1663216b192fbe5e0fb364e952f85c
Status: Image is up to date for busybox:latest
docker.io/library/busybox:latest

What's Next?
  View summary of image vulnerabilities and recommendations → docker scout quickview busybox:latest

### docker version

```bash
Client:
 Cloud integration: v1.0.35
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:53:15 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.21.1 (114176)
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:52:17 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.19.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.6
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  0.16.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 36
  Running: 35
  Paused: 0
  Stopped: 1
 Images: 12
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 5.15.90.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 15.52GiB
 Name: docker-desktop
 ID: d93b0112-f7ba-4d6e-8462-062e7e70e549
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

### Diagnostics ID

7497BA27-F923-47A7-9382-C46B6B16D0A3/20230714133935

**Comment by lorenrh** [comment]
This is a behaviour intended by default, you can disable then by setting `DOCKER_CLI_HINTS=false`.

**Comment by thaJeztah** [comment]
Yes, STDERR is by convention used for "informational" output, such as progress output, or informational messages (hints in this case), in addition to "error messages".

This allows errors and informational output to be redirected, and keeps STDOUT reserved for "program output", which allows that output to be used for piping to other commands (`docker <some-command> | <some other binary consuming the output>`).

**Comment by asoldo11** [comment]
Ok, thank You for clarification. We will than turn off hints to mitigate our problems.
