### ISSUE TITLE
Docker Engine Not Starting on Windows 11

### ISSUE THREAD

**Issue by andresalbertomoralesmitre** [docker/for-win#13636]
### Description

When attempting to start the Docker Engine on Windows 11, the engine fails to initialize properly and remains in a non-operational state. This issue prevents users from utilizing containerization technology and the associated benefits it offers.

Actual Behavior:
The Docker Engine fails to start on Windows 11, rendering the Docker Desktop application unusable.

### Reproduce

1. Install Docker Desktop on a machine running Windows 11.
2. Launch Docker Desktop from the desktop shortcut or the Start menu.
3. Observe the Docker Desktop UI attempting to start the Docker Engine.
4. Notice that the Docker Engine fails to start and remains in a stopped state.

### Expected behavior

The Docker Engine should start successfully on Windows 11, allowing users to create and manage containers.

### docker version

```bash
request returned Internal Server Error for API route and version http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version, check if the server supports the requested API version
Client:
 Cloud integration: v1.0.35-desktop+001
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:36:24 2023
 OS/Arch:           windows/amd64
 Context:           default
```

### docker info

```bash
Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.20.2-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.6
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  0.20.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
ERROR: request returned Internal Server Error for API route and version http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/info, check if the server supports the requested API version
errors pretty printing info
```

### Diagnostics ID

38CB5CCF-073F-42FC-98D5-E001F8C19500/20230807183135

**Comment by bsousaa** [comment]
From your diagnostics: 
[WARN] DD0023: is the Containers Windows Feature enabled? required Windows Feature not installed: Containers

Are you running with WSL2 or Hyper-V backend?

See [System Requirements on Windows](https://docs.docker.com/desktop/install/windows-install/).

**Comment by andresalbertomoralesmitre** [comment]
It pops up an error message:

Docker Desktop : Windows container not supported

Windows container are not supported by your windows version, Check documentation for minimum requirements. 

![image](https://github.com/docker/for-win/assets/131017905/bc32c7d2-9d4c-47b8-9371-32270e3f1539)


My windows version is:
Windows version is Microsoft Windows 11 Home Single Language, with a system version of 10.0.22621 and a build of 22621.

Additional info:
![image](https://github.com/docker/for-win/assets/131017905/619c43cd-ee49-48e4-91ea-ab839520ff6a)

**Comment by p1-0tr** [comment]
hi @andresalbertomoralesmitre , could you edit `%userprofile%\AppData\Roaming\Docker\settings.json` to change `"useWindowsContainers": true,` -> `"useWindowsContainers": false,` and let me know if that helps?

**Comment by andresalbertomoralesmitre** [comment]
That worked @p1-0tr  thank you so much!

**Comment by ghost** [comment]
You are a genius p1-0tr, but i needed to do the opposite. false->true

**Comment by zhengcaifeng** [comment]
vim  ~/.docker/daemon.json
modify  engine  into 
"registry-mirrors": [
 " https://hub-mirror.c.163.com"
  ]
​

**Comment by joreilly86** [comment]
> hi @andresalbertomoralesmitre , could you edit `%userprofile%\AppData\Roaming\Docker\settings.json` to change `"useWindowsContainers": true,` -> `"useWindowsContainers": false,` and let me know if that helps?

Thank you so much, I was chasing this solution for a while!

**Comment by H0sin** [comment]
**_please update docker if wsl is on_**

![Image](https://github.com/user-attachments/assets/1dc82733-310a-4e71-a789-d5fa2182d126)
