### ISSUE TITLE
Docker is not able to mount share into container

### ISSUE THREAD

**Issue by arkasai** [docker/for-win#1363]
### Expected behavior
Docker should mount share into the started container to access files from hard disk. Example command:
docker run -i -v C:\src:/src ubuntu
### Actual behavior
Logfile says the smb mount command got a "Permission denied" from the active directory.
### Information
Diagnostic ID: 15167426-A92D-4CFA-87F4-BFC478F6623D/2017-11-27_18-25-41

Windows used:
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.14393 Build 14393
Hardware Abstraction Layer	Version = "10.0.14393.1378"

As far as I can strip this down our Active-Directory has been set up with very high security settings which enforce a authentication which is not working with Docker. Is there any possible workaround for that?

**Comment by arkasai** [comment]
Will there be an answer somewhen or do we need some more information?

**Comment by arkasai** [comment]
Just updated to the new edge version (17.12.0-ce-rc2-win41 (14746)) but no change. It's still not working to connect my local drive via share or volume mechanism.

**Comment by pradhyu** [comment]
I am having the same trouble. The container that i had windows volume mounted to is not showing up inside container any more.

**Comment by arkasai** [comment]
/remove-lifecycle stale

Maybe some additional update for this issue. It seems that the problem is smb encryption. If that option is enabled via domain-policy shares cannot be connected on Windows 10.

Possible workaround for this issue is to disable the smb encryption via following power-shell command run as administrator priviledges: Set-SmbServerConfiguration -EncryptData 0 -Force
