### ISSUE TITLE
Docker Desktop Unexpected WSL error

### ISSUE THREAD

**Issue by Meakoala** [docker/for-win#13637]
### Description

Fresh install and first time open then get this error
![image](https://github.com/docker/for-win/assets/141302175/ad53b9e4-6393-415a-b2c4-d524014d81af)

### Reproduce

1. try error suggestion 
 - shutdown wsl 
 - reboot 
 - reinstall
2. try self-diagnose
 - result
![image](https://github.com/docker/for-win/assets/141302175/68142815-23e6-4215-b05c-f1d11a4682e3)

### Expected behavior

Start and Run Docker Desktop as normal fresh install should.

### docker version

```bash
error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version": open //./pipe/docker_engine: The system cannot find the file specified.
Client:
 Cloud integration: v1.0.35-desktop+001
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:36:24 2023
 OS/Arch:           windows/amd64
 Context:           default
```

### docker info

```bash
Client:
 Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.20.2-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.6
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  0.20.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
ERROR: error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/info": open //./pipe/docker_engine: The system cannot find the file specified.
errors pretty printing info
```

### Diagnostics ID

320244C3-6450-42BD-BB90-A7F0C0386CA9/20230808094504

### Additional Info

Run on Windows 10 Pro 22H2

**Comment by p1-0tr** [comment]
hi @Meakoala, thanks for reporting the issue and sorry for the inconvenience. It looks like WSL is failing because you've got "legacy console mode" enabled. This link describes how to enable that mode - https://learn.microsoft.com/en-us/windows/console/legacymode#using-legacy-console-mode - where the instruction asks to check the `Use legacy console` check box, please uncheck it. Once you've done that try running Docker Desktop again.

**Comment by Meakoala** [comment]
> hi @Meakoala, thanks for reporting the issue and sorry for the inconvenience. It looks like WSL is failing because you've got "legacy console mode" enabled. This link describes how to enable that mode - https://learn.microsoft.com/en-us/windows/console/legacymode#using-legacy-console-mode - where the instruction asks to check the `Use legacy console` check box, please uncheck it. Once you've done that try running Docker Desktop again.

It work fine now. Thanks you.
