### ISSUE TITLE
unable to calculate image disk size

### ISSUE THREAD

**Issue by Lewellyen81** [docker/for-win#13646]
### Description

docker desktop starts
in volumes tab is the circle spinning
error: unable to calculate image disk size appears
docker engine stops

### Reproduce

start docker

### Expected behavior

mount volumes

### docker version

```bash
Client:
 Cloud integration: v1.0.35-desktop+001
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:36:24 2023
 OS/Arch:           windows/amd64
 Context:           default
```

### docker info

```bash
Client:
 Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.20.2-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.6
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  0.20.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe
```

### Diagnostics ID

C029748E-A571-4CD1-921A-F026FADDB7C7/20230815004627

### Additional Info

info::
running on a QNAP 251+ in a Windows 10 VM created with virtualization station.
seems that docker has a problem to create the virtual volume.

**Comment by Lewellyen81** [comment]
[dockerlog.txt](https://github.com/docker/for-win/files/12358269/dockerlog.txt)

seems to be a connection problem?

**Comment by bsousaa** [comment]
Is WSL installed? What's the output of `wsl --status`?

**Comment by Lewellyen81** [comment]
sure it is...
status says:

Standard-Distribution: Ubuntu
Standardversion: 2

**Comment by bsousaa** [comment]
If you update the WSL VM `wsl --update`?

**Comment by Lewellyen81** [comment]
newest version is installed

what about this line in the log?
`[2023-08-16T09:15:01.069203100Z][GoBackendProcess][I] [starting] running WSL command "wsl.exe --import docker-desktop <HOME>\\AppData\\Local\\Docker\\wsl\\distro C:\\Program Files\\Docker\\Docker\\resources\\wsl\\wsl-bootstrap.tar --version<INT>" failed with output "Beim Vorgang ist eine ZeitÃ¼berschreitung aufgetreten, da von dem virtuellen Computer oder Container keine Antwort empfangen wurde. \r\nError code: Wsl/Service/HCS_E_CONNECTION_TIMEOUT\r\n": exit status <HEX>`

**Comment by ctalledo** [comment]
Looking at the diagnostics bundle, it seems Docker Desktop fails to boot when it tries to list the WSL distros on the host:

```
[2023-08-15T00:37:05.826546400Z][com.docker.backend.exe.ipcstream][I] cea59e89-BackendAPI /engine/state --> [2023-08-15T02:37:05.811179300+02:00] (b208df00) engine failed to start : dockerd failed to start: starting WSL engine: 2 errors occurred:
        * provisioning docker WSL distros: getting WSL distro list: listing WSL distros: context deadline exceeded
```

During the diagnosis bundle capture, the script that collects WSL info also fails in the exact same way:

```
wsl.exe -l -v
context deadline exceeded
```

So this appears to be a problem with WSL per-se, not in Docker Desktop.
