### ISSUE TITLE
WSL Integration Issue

### ISSUE THREAD

**Issue by godreborn** [docker/for-win#13642]
### Description

wsl integration isn't working after the latest windows install.  docker still works in the distros, but the ones in question like Arch and Debian are not highlighted.  I had issues with a screensaver, but I do not know if they're related somehow.

### Reproduce

basically, just update to the latest windows, and see if all distros are highlighted when integrated.  I do not know if this is a problem, but I have five of them installed.

### Expected behavior

I expect all distros to be highlighted like it's actually working.

### docker version

```bash
4.22.0 (117440)
```

### docker info

```bash
not sure what to put here, sorry.
```

### Diagnostics ID

CED63D72-024F-4BE3-AF38-CE259A03C10E/20230810231101

**Comment by bsousaa** [comment]
This is not clear to me... what do you mean by highlighted? Please add a screenshot

**Comment by godreborn** [comment]
> This is not clear to me... what do you mean by highlighted? Please add a screenshot

![image](https://github.com/docker/for-win/assets/13548481/fc80d16f-8e68-4ad3-92c5-362c3c1f1416)

the distros, showing that they're integrated with docker, sometimes shows that they're disabled after a restart.  docker still works in those distros despite that, but it's random which distros show that docker is enabled.  I think it's a bug of some sort either with docker or windows.

**Comment by godreborn** [comment]
nm, it seems to have corrected itself.  it now shows all of the distros being enabled whenever I restart.

**Comment by bsousaa** [comment]
Thanks, I'm closing the issue for now. Feel free to comment here if it happens again and I will re-open.
