### ISSUE TITLE
Issue on Docker Desktop installation

### ISSUE THREAD

**Issue by leoTozzi99** [docker/for-win#13664]
### Description

I'm trying to install Docker Desktop on my pc and i have this message.
Component CommunityInstaller.EnableFeaturesAction failed: 
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()

I tried the solutions already present on the docker forum but none worked. How can I solve this problem?

### Reproduce

I had docker desktop up and running, at any moment it stopped working. I tried to uninstall it but now I can't even install it anymore

### docker version

```bash
I'm trying to install Docker Desktop 4.14.0 (but I have the same issue trying to install the latest version)
```

### docker info

```bash
..
```

### Diagnostics ID

.

**Comment by MihaelaStoica** [comment]
@leoTozzi99 Since the installation of any version is failing, it suggests some left-over from a previous installation. You could check if there is a Docker Desktop registry key in HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall and remove it, then try installing again.

**Comment by leoTozzi99** [comment]
@MihaelaStoica Thanks a lot, but I had already done this cleanup and I've already tried other solutions found on the internet (reinstalling wsl for example)...I've been stuck on this problem for days

**Comment by jason-bivins** [comment]
Hi @leoTozzi99   Can you make sure nested virtualization is enabled?  https://docs.docker.com/desktop/troubleshoot/topics/#virtualization-must-be-turned-on

**Comment by leoTozzi99** [comment]
Hi @jason-bivins i confirm that nested virtualization is enabled...

**Comment by adlernscs50** [comment]
I don't have VM/HyperV or whatever it's called supported on my hardware. So, no way to use Docker. Even with WSL 1. WSL 2 need virtualization too.

**Comment by leoTozzi99** [comment]
I think I have found the key to the problem. In an old installer, such as 4.3.0, there is a check box which says Install required Windows components for WSL2. If you uncheck it, everything will be fine but the check box no longer exists in newer installer.
