### ISSUE TITLE
curl: (60) SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by sg-schaudhuri** [docker/for-win#13671]
### Description

I am using Docker v24.0.5 on Windows. The container is running Debian GNU/Linux 11 (bullseye).
If I do a curl -vvv https://www.google.com in the terminal I get the below error:
(airflow)curl -vvv https://www.google.com
*   Trying 142.250.105.104:443...
* Connected to www.google.com (142.250.105.104) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

### Reproduce

Install docker desktop
docker-compose up airflow-init (airflow 2.6.3)
docket-compose up -d

### Expected behavior

Should have a successful connection

### docker version

```bash
OS: Debian GNU/Linux 11 (bullseye)
Created via: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html 

Machine on which docker is installed:
Windows 10 Enterprise: 22H2
```

### docker info

```bash
Dockerfile:

FROM apache/airflow:2.6.3
USER root
COPY requirements.txt /
RUN apt-get update \
 && apt-get install -y --no-install-recommends ca-certificates

RUN update-ca-certificates

USER airflow
RUN pip install --no-cache-dir "apache-airflow==${AIRFLOW_VERSION}" -r /requirements.txt --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org
```

### Diagnostics ID

31432188-2112-45D8-A6D8-099EB49F4EC9/20230907220040

**Comment by nicks** [comment]
what server certificate does it show if you use `curl -vv --insecure`?

seems unlikely this is a docker issue; more likely that you're behind some sort of firewall / proxy that's MITM-ing the connection and returning a self-signed cert that your container doesn't have access to.

**Comment by sg-schaudhuri** [comment]
I executed curl -vv https://www.google.com --insecure and got the below results:

* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=www.google.com
*  start date: Sep  3 02:18:40 2023 GMT
*  expire date: Sep 17 02:18:40 2023 GMT
*  issuer: C=US; ST=California; O=Zscaler Inc.; OU=Zscaler Inc.; CN=Zscaler Intermediate Root CA (zscloud.net) (t) 
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.

What I interpreted from this is -
Original cert was issuer: C=US; O=Google Trust Services LLC; CN=GTS CA 1C3
Zscaler is changing the cert to C=US; ST=California; O=Zscaler Inc.; OU=Zscaler Inc.; CN=Zscaler Intermediate Root CA (zscloud.net) (t)

So, does that mean I need to have the cert "Zscaler Intermediate Root CA (zscloud.net) (t) " in Docker? If yes, how to do that?

**Comment by nicks** [comment]
good news! zscaler has a doc on this - https://help.zscaler.com/zia/adding-custom-certificate-application-specific-trust-store. Check out the Docker section.

**Comment by sg-schaudhuri** [comment]
here are the steps to resolve this -
In Firefox hit https://www.google.com
View certificate >> and download the chain .pem cert
In Docker container get the cacert.pem by using Python:
import certifi
print(certifi.where())
append the certificate chain obtained from Firefox at the end of what certify gave
copy this new pem to /usr/local/share/ca-certificates/cert_custom.pem
update env variable REQUESTS_CA_BUNDLE=/usr/local/share/ca-certificates/cert_custom.pem in docker-compose
