### ISSUE TITLE
[Error  ] fatal: Error starting daemon: The docker daemon requires build 14393 or later of Windows Server 2016 or Windows 10

### ISSUE THREAD

**Issue by TomasZaleckis** [docker/for-win#1368]
### Expected behavior
I have installed Docker For Windows (stable version). I am trying to start Docker For Windows and it is crashing with error: Time out has expired and the operation has not been completed.

### Actual behavior
In the log.txt I can see the error being repeated:

[Error  ] fatal: Error starting daemon: The docker daemon requires build 14393 or later of Windows Server 2016 or Windows 10

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
7837E6F5-4C34-4208-9FB6-DEF23350592E/2017-11-28_17-49-00

  - host distribution and version (Windows version, build number, etc)
Edition: Windows 10 Enterprise
Version: 1511
OS Build: 10586.1176

### Steps to reproduce the behavior

1. Start Docker.
2. Get Error:
![image](https://user-images.githubusercontent.com/29660558/33335554-53816214-d465-11e7-8c66-92f125142331.png)

**Comment by jasonbivins** [comment]
Hi @TomasZaleckis  it looks like you'll need to run Windows Updates, as you're on an older Windows build.  Docker requires some Hyper-V features that weren't included until build 14393
```
host distribution and version (Windows version, build number, etc)
Edition: Windows 10 Enterprise
Version: 1511
OS Build: 10586.1176
