### ISSUE TITLE
Docker Desktop crashes when shutting down Windows 11 PC

### ISSUE THREAD

**Issue by cyclr-adrian** [docker/for-win#13697]
### Description

Since installing version `4.23.0` whenever I restart or shutdown my Windows 11 PC I get the following message:
![image](https://github.com/docker/for-win/assets/95350065/24634600-e4dc-46d6-8c97-00e78827d2dd)

### Reproduce

Shutdown PC

### Expected behavior

The app doesn't prevent the PC from shutting down.

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.4
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:32:48 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.23.0 (120376)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:32:16 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.7
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  0.24.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 6
  Running: 4
  Paused: 0
  Stopped: 2
 Images: 12
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.90.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.617GiB
 Name: docker-desktop
 ID: bb0b8762-2fd9-41a5-b789-828f30327f0b
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

919FCDBC-B719-4A2D-AE7B-58D4FDFE7637/20230921082918

**Comment by robertlarkins** [comment]
I'm also getting this issue on Windows 10, even after an uninstall/reinstall.

**Comment by cyclr-adrian** [comment]
I tried installing version `4.24.0` to see if that fixed the issue but the issue still happens.

**Comment by MichalGow** [comment]
Does happen to me also. Windows 11 Pro for Workstations, 22H2, OS build 22621.2361 with Docker v4.24.0.

**Comment by AB-xdev** [comment]
Possible workaround until the problem is fixed:
Set ``HKEY_CURRENT_USER\Control Panel\Desktop\AutoEndTasks`` to ``1``.
This [force closes all apps that prevent shutting down/rebooting](https://www.tomshardware.com/how-to/auto-end-tasks-windows).

**Comment by glen-84** [comment]
@bsousaa Please prioritize this issue, it's very annoying.

**Comment by bsousaa** [comment]
@glen-84 the issue was raised and prioritised a few days ago. I'll update the thread as soon as I get news.

**Comment by ebriney** [comment]
Hello. I can reproduce it on 4.23.0. We changed the main program recently, it fixed the issue for me.
Can you try this build and confirm it's working for you too: https://desktop-stage.docker.com/win/main/amd64/123939/Docker%20Desktop%20Installer.exe

**Comment by nguyenvanminhtuan** [comment]
It works for me @ebriney

**Comment by lrebosio** [comment]
Hey @ebriney, it works for me too! Thanks!

**Comment by ebriney** [comment]
Good news!

**Comment by KyleRicardo** [comment]
Is this bug fixed officially? It's so f-ing annoying and upsetting.

**Comment by glen-84** [comment]
@ebriney When will the fix be released?

**Comment by JPustkuchen** [comment]
Any update here @bsousaa? This is bad for the environment 😆 Machines aren't shutting down anymore ;)
And this wasn't easy to find because of the logo displayed! I would have expected a docker logo in that case?

**Comment by xanather** [comment]
Happening to me.

**Comment by bsousaa** [comment]
@JPustkuchen keep an eye on Docker Desktop 4.25 which should release pretty soon.

**Comment by mukki182** [comment]
@bsousaa thanks, 4.25.0 solved it for me 👍

**Comment by hungtrinh** [comment]
Oh my god, my windows 11 22H2 won't boot after installing the latest docker, I can only run system restore to recover

**Comment by MattLichter** [comment]
Still happening for me on Docker Desktop for Windows 4.26.1.  We have unattended CI machines that take OS updates overnight but fail to restart.  We return in the morning to a Windows environment without Docker or any other apps running.  I guess the shutdown times out and Windows explorer resumes.  We have to remote into each machine and manually reboot.
