### ISSUE TITLE
Docker can not run successful

### ISSUE THREAD

**Issue by heyixiaoran** [docker/for-win#1369]
Win:  Win 10 preview X64 17025 
VS:    n15.4.4   ASP.NET Core 2.0
Docker: 17.09.0-ce-win33 (13620)

I just create a ASP.NET Core Web application .then run .

Severity	Code	Description	Project	File	Line	Suppression State
Error		Building webapplication1
Creating dockercompose15859295141947246194_webapplication1_1 ... 
Creating dockercompose15859295141947246194_webapplication1_1
[1A[2K
Creating dockercompose15859295141947246194_webapplication1_1 ... [31merror[0m
[1B
ERROR: for dockercompose15859295141947246194_webapplication1_1  Cannot start service webapplication1: container 43a78fe14a47c9e67beab7f1bf7b0bf16f7383ec5bb2d73804634a0b4dad443a encountered an error during CreateContainer: failure in a Windows system call: The description string for parameter reference (%1) could not be found. (0x3ab6) extra info: {"SystemType":"Container","Name":"43a78fe14a47c9e67beab7f1bf7b0bf16f7383ec5bb2d73804634a0b4dad443a","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\43a78fe14a47c9e67beab7f1bf7b0bf16f7383ec5bb2d73804634a0b4dad443a","Layers":[{"ID":"61447002-00eb-53f0-be18-0c9587ea34da","Path":"C:\\ProgramData\\Docker\\windowsfilter\\efe8e0899c1272f08d1a48d6aa8635b9ec8f0e0de5efed4991481db65b050c20"},{"ID":"4f52eadf-0298-57f3-872d-a11c7a89a01d","Path":"C:\\ProgramData\\Docker\\windowsfilter\\f7b1b82e81c9ebbc90c169ffccefc5e18ae8526f1bfb57b90d7b55aceb74645d"},{"ID":"28e6980c-2232-5f57-b91b-16a4936c2ba2","Path":"C:\\ProgramData\\Docker\\windowsfilter\\31b494b27e3e0e3c8bac91f156a20cdc5dfed685f6b2067d2d568a4d0b4d43b6"},{"ID":"ed061cff-7828-5c14-995d-e1be8bb24bd8","Path":"C:\\ProgramData\\Docker\\windowsfilter\\e71bc1c76e351053473f45b763ad053cda39fd52330e7bc3bfbf15006152897c"},{"ID":"52181528-f9a4-59d4-a96d-f4ad4a22e80e","Path":"C:\\ProgramData\\Docker\\windowsfilter\\aa33e31dc6ad25e06c10babb5c8cfe19bed28d44b8c9e7ece4bceed7417d6c01"},{"ID":"4c9a4b3c-0d33-5761-9355-016d4ee53797","Path":"C:\\ProgramData\\Docker\\windowsfilter\\2702c6f05b1170e83cbf63fcae9367942e83897aeea6cba7f4324aac72aa8b94"},{"ID":"25c45eb1-91f1-5d90-88fa-cc3c0a01fb0f","Path":"C:\\ProgramData\\Docker\\windowsfilter\\a71f41e51d3f691578fc0e2d14c457f0f2258d82e5b1b70c263775abbad6409c"},{"ID":"1b15eaf8-3b49-508d-8932-f97724048dcd","Path":"C:\\ProgramData\\Docker\\windowsfilter\\359dcb9438fb9cdc827e3b97565cac137eed43ed288a435678f457c9656bc3e2"},{"ID":"990b21f4-566d-5932-9ef9-08eb52c1d69f","Path":"C:\\ProgramData\\Docker\\windowsfilter\\48c61499914f23e0424bd8d069c5cce9914ecc02139b6dc2a63c2162bb90ae05"},{"ID":"8b919d74-4ddf-50b7-8041-b5bda00c4fb4","Path":"C:\\ProgramData\\Docker\\windowsfilter\\c3bde5f8b45beff1c929eb3e6ba3daaa1f6367cd8d66ec1f1a6d1648ba3bbce5"},{"ID":"aceaf86f-0485-559f-85e8-4863497c6810","Path":"C:\\ProgramData\\Docker\\windowsfilter\\f4ac6b4f18e4aabdbf73a4d9fe762919410c3ba54b36e06e2462098cd41df6a1"},{"ID":"fdbabbca-48e0-5bf8-8518-ebcc781d68f8","Path":"C:\\ProgramData\\Docker\\windowsfilter\\764159a1616d350e9026cabbd1f3a1b544971e0314ce85ba072d1983b68848a8"},{"ID":"3877fb13-3933-5e5f-8fe9-46cbefbec031","Path":"C:\\ProgramData\\Docker\\windowsfilter\\e587bf10e513d5070b6de81c9fc08b91e62791cde733a60c19fde591263e68e6"},{"ID":"cbad42c2-3727-500e-9294-cfa7f5664624","Path":"C:\\ProgramData\\Docker\\windowsfilter\\67002d14dc99094f34c018381900cd63f4be2ad94823de90d1c8313f6e2dffc9"},{"ID":"cc8666fa-ebde-55f2-b8fe-b546dbcc04b5","Path":"C:\\ProgramData\\Docker\\windowsfilter\\acaf072150ad69a11a1b5f4493aa1c678433d9f56123f98a4efa0f583d51f330"},{"ID":"d0b326c8-a947-56af-8bea-e46eec29629b","Path":"C:\\ProgramData\\Docker\\windowsfilter\\39688daaa3c5e75c0216151b7d093312e10ac70cb70935ce5704c8919bf167b3"}],"HostName":"43a78fe14a47","MappedDirectories":[{"HostPath":"c:\\users\\heyix\\source\\repos\\webapplication1\\webapplication1","ContainerPath":"c:\\app","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\users\\heyix\\onecoremsvsmon\\15.0.26919.1","ContainerPath":"c:\\remote_debugger","ReadOnly":true,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\program files\\dotnet\\sdk\\nugetfallbackfolder","ContainerPath":"c:\\.nuget\\fallbackpackages","ReadOnly":true,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\users\\heyix\\.nuget\\packages","ContainerPath":"c:\\.nuget\\packages","ReadOnly":true,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}],"HvPartition":true,"EndpointList":["add748a8-2822-4e05-9440-dcb138512ebf"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\acaf072150ad69a11a1b5f4493aa1c678433d9f56123f98a4efa0f583d51f330\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}
ERROR: for webapplication1  Cannot start service webapplication1: container 43a78fe14a47c9e67beab7f1bf7b0bf16f7383ec5bb2d73804634a0b4dad443a encountered an error during CreateContainer: failure in a Windows system call: The description string for parameter reference (%1) could not be found. (0x3ab6) extra info: {"SystemType":"Container","Name":"43a78fe14a47c9e67beab7f1bf7b0bf16f7383ec5bb2d73804634a0b4dad443a","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\43a78fe14a47c9e67beab7f1bf7b0bf16f7383ec5bb2d73804634a0b4dad443a","Layers":[{"ID":"61447002-00eb-53f0-be18-0c9587ea34da","Path":"C:\\ProgramData\\Docker\\windowsfilter\\efe8e0899c1272f08d1a48d6aa8635b9ec8f0e0de5efed4991481db65b050c20"},{"ID":"4f52eadf-0298-57f3-872d-a11c7a89a01d","Path":"C:\\ProgramData\\Docker\\windowsfilter\\f7b1b82e81c9ebbc90c169ffccefc5e18ae8526f1bfb57b90d7b55aceb74645d"},{"ID":"28e6980c-2232-5f57-b91b-16a4936c2ba2","Path":"C:\\ProgramData\\Docker\\windowsfilter\\31b494b27e3e0e3c8bac91f156a20cdc5dfed685f6b2067d2d568a4d0b4d43b6"},{"ID":"ed061cff-7828-5c14-995d-e1be8bb24bd8","Path":"C:\\ProgramData\\Docker\\windowsfilter\\e71bc1c76e351053473f45b763ad053cda39fd52330e7bc3bfbf15006152897c"},{"ID":"52181528-f9a4-59d4-a96d-f4ad4a22e80e","Path":"C:\\ProgramData\\Docker\\windowsfilter\\aa33e31dc6ad25e06c10babb5c8cfe19bed28d44b8c9e7ece4bceed7417d6c01"},{"ID":"4c9a4b3c-0d33-5761-9355-016d4ee53797","Path":"C:\\ProgramData\\Docker\\windowsfilter\\2702c6f05b1170e83cbf63fcae9367942e83897aeea6cba7f4324aac72aa8b94"},{"ID":"25c45eb1-91f1-5d90-88fa-cc3c0a01fb0f","Path":"C:\\ProgramData\\Docker\\windowsfilter\\a71f41e51d3f691578fc0e2d14c457f0f2258d82e5b1b70c263775abbad6409c"},{"ID":"1b15eaf8-3b49-508d-8932-f97724048dcd","Path":"C:\\ProgramData\\Docker\\windowsfilter\\359dcb9438fb9cdc827e3b97565cac137eed43ed288a435678f457c9656bc3e2"},{"ID":"990b21f4-566d-5932-9ef9-08eb52c1d69f","Path":"C:\\ProgramData\\Docker\\windowsfilter\\48c61499914f23e0424bd8d069c5cce9914ecc02139b6dc2a63c2162bb90ae05"},{"ID":"8b919d74-4ddf-50b7-8041-b5bda00c4fb4","Path":"C:\\ProgramData\\Docker\\windowsfilter\\c3bde5f8b45beff1c929eb3e6ba3daaa1f6367cd8d66ec1f1a6d1648ba3bbce5"},{"ID":"aceaf86f-0485-559f-85e8-4863497c6810","Path":"C:\\ProgramData\\Docker\\windowsfilter\\f4ac6b4f18e4aabdbf73a4d9fe762919410c3ba54b36e06e2462098cd41df6a1"},{"ID":"fdbabbca-48e0-5bf8-8518-ebcc781d68f8","Path":"C:\\ProgramData\\Docker\\windowsfilter\\764159a1616d350e9026cabbd1f3a1b544971e0314ce85ba072d1983b68848a8"},{"ID":"3877fb13-3933-5e5f-8fe9-46cbefbec031","Path":"C:\\ProgramData\\Docker\\windowsfilter\\e587bf10e513d5070b6de81c9fc08b91e62791cde733a60c19fde591263e68e6"},{"ID":"cbad42c2-3727-500e-9294-cfa7f5664624","Path":"C:\\ProgramData\\Docker\\windowsfilter\\67002d14dc99094f34c018381900cd63f4be2ad94823de90d1c8313f6e2dffc9"},{"ID":"cc8666fa-ebde-55f2-b8fe-b546dbcc04b5","Path":"C:\\ProgramData\\Docker\\windowsfilter\\acaf072150ad69a11a1b5f4493aa1c678433d9f56123f98a4efa0f583d51f330"},{"ID":"d0b326c8-a947-56af-8bea-e46eec29629b","Path":"C:\\ProgramData\\Docker\\windowsfilter\\39688daaa3c5e75c0216151b7d093312e10ac70cb70935ce5704c8919bf167b3"}],"HostName":"43a78fe14a47","MappedDirectories":[{"HostPath":"c:\\users\\heyix\\source\\repos\\webapplication1\\webapplication1","ContainerPath":"c:\\app","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\users\\heyix\\onecoremsvsmon\\15.0.26919.1","ContainerPath":"c:\\remote_debugger","ReadOnly":true,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\program files\\dotnet\\sdk\\nugetfallbackfolder","ContainerPath":"c:\\.nuget\\fallbackpackages","ReadOnly":true,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\users\\heyix\\.nuget\\packages","ContainerPath":"c:\\.nuget\\packages","ReadOnly":true,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}],"HvPartition":true,"EndpointList":["add748a8-2822-4e05-9440-dcb138512ebf"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\acaf072150ad69a11a1b5f4493aa1c678433d9f56123f98a4efa0f583d51f330\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}
Encountered errors while bringing up the project..

For more troubleshooting information, go to http://aka.ms/DockerToolsTroubleshooting	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets	349

**Comment by jasonbivins** [comment]
Hi @heyixiaoran 
You mentioned that you build this on the Windows 17025 preview - does your image run on this machine, or are you trying to run it on another machine?
There are some new Windows build requirements as of the Windows 1709 release - please see here:
https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility

**Comment by heyixiaoran** [comment]
@jasonbivins 
I try to run a project which can run on other computer. It still failed. same error message. 
The docs's link. I don't understand. So I see some link .I found this.
[](https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/insider-known-issues)
I just command first . Now I can run. Thank you
