### ISSUE TITLE
Docker push fails with "The system cannot find the path specified" error

### ISSUE THREAD

**Issue by jelledruyts** [docker/for-win#1370]
### Expected behavior

docker push (v17.11 on edge channel, using LCOW) should work fine

### Actual behavior

Push goes into a few retries and then fails.

```
The push refers to repository [docker.io/jelledruyts/busybox]
0271b8eebde3: Pushing [==================================================>]  3.408MB/3.408MB
open \tmp\2cfcef25612fd89fbad50a4c77226a67b7f8f0418cb53b4a811afbaf497f6ceb-mount\bin\[: The system cannot find the path specified.
```

### Information

Diagnostic ID: B896AFDB-C46F-4CC5-AED3-6E096A519DDF/2017-11-29_14-30-57
Version: Docker for Windows v17.11.0-ce using LCOW

### Steps to reproduce the behavior

  1. c:\docker pull busybox
  2. c:\docker tag busybox:latest jelledruyts/busybox:latest
  3. c:\docker push jelledruyts/busybox:latest

**Comment by stalb** [comment]
I have also this problem to push images.
I don't have the pb using jelledruyts instructions, but with modified images.

**Steps to reproduce the behavior:** 
1) Create a modified images (simple dockerfile copying a non empty file - see attached files
2) push image

**Step 1:** 
```
PS D:\test> docker build -t stalb/essai:test .
Sending build context to Docker daemon  3.072kB
Step 1/2 : FROM busybox
latest: Pulling from library/busybox
0ffadd58f2a6: Pull complete
Digest: sha256:bbc3a03235220b170ba48a157dd097dd1379299370e1ed99ce976df0355d24f0
Status: Downloaded newer image for busybox:latest
 ---> 6ad733544a63
Step 2/2 : COPY test.txt test.txt
 ---> c894da5651a5
Successfully built c894da5651a5
Successfully tagged stalb/essai:test
```
**Step 2:** 
```
PS D:\test> docker push stalb/essai:test
The push refers to repository [docker.io/stalb/essai]
0f0ac15fce27: Pushing [==================================================>]  262.7kB/262.7kB
0271b8eebde3: Mounted from stalb/itac
open \tmp\d7af56a4429e7a5bccbe1caed9f4ddad1fa48fba6a6a45ccf5db9e4dee190617-mount\test.txt: Le chemin d’accès spécifié est introuvable.
```
Attached files : [test.zip](https://github.com/docker/for-win/files/1535724/test.zip)

Docker version (I had also this problem with previous version) : 
```
Client:
 Version:      master-dockerproject-2017-12-05
 API version:  1.35
 Go version:   go1.9.2
 Git commit:   ea854237
 Built:        Tue Dec  5 23:49:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      master-dockerproject-2017-12-05
 API version:  1.35 (minimum version 1.24)
 Go version:   go1.9.2
 Git commit:   c7dd58f
 Built:        Tue Dec  5 23:52:43 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

Docker info:
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 6
Server Version: master-dockerproject-2017-12-05
Storage Driver: windowsfilter (windows) lcow (linux)
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 7.891GiB
Name: XXXXXX
ID: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Docker Root Dir: C:\ProgramData\Docker\lcow
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 26
 System Time: 2017-12-06T16:46:42.846979+01:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by seb-dataworks** [comment]
Same issue for me with Docker 17.12.0-ce-rc3. Makes it pretty much unusable right now for me.

Docker info:

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 13
Server Version: 17.12.0-ce-rc3
Storage Driver: windowsfilter (windows) lcow (linux)
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 15.93GiB
Name: *****
ID: *********************
Docker Root Dir: C:\ProgramData\Docker\lcow
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 26
 System Time: 2017-12-21T11:00:41.6174883+01:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by ImranKamaluddin** [comment]
Hello,

I am experiencing a similar issue when try to push an image to a private repository on Docker Hub.

Here is my test Dockerfile:-:

# Dockerfile to build Ubuntu image with SSH

# Set base image
FROM ubuntu

# Install OpenSSH Server
RUN apt-get update && apt-get install -y openssh-server
RUN mkdir /var/run/sshd
RUN echo 'root:Docker!' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]

# Install Network Utils
RUN apt-get update
RUN apt-get install net-tools
RUN apt-get -y install dnsutils

 
Using the following command to build an image :-

         docker build -t <mydocker_Repository>:ubuntutest . 

and then to push the image to my private repository on Docker Hub:- 

        docker push <mydocker_Repository>:ubuntutest 

When I try the above procedure, I consistently get the following error:-

"open \tmp\08749566094e421a6e77c6629fd157624086e80a03e8fa9e7200534c97b633f2-mount\etc\ld.so.cache: The system cannot find the path specified."

OS Version = Windows 10 version 1709
OS Build = 16299.125
Docker Version = 17.12.0-ce-rc4-win44 (14896)

**Comment by tomconte** [comment]
I switched off LCOW and was able to push.

**Comment by ImranKamaluddin** [comment]
Thanks, that worked. Is this expected behaviour?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by stalb** [comment]
I think the correct behavior for docker on windows is to be able to push when lcow is enabled.

**Comment by seb-dataworks** [comment]
I agree with @stalb, the push should work even (or especially?!) when LCOW is enabled.

**Comment by ImranKamaluddin** [comment]
I shall try again with the latest Docker Edge build

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by stalb** [comment]
I've tried with docker version 18.01.0-ce-win48 (15285) and also with version master-dockerproject-2018-01-23 (version post re-coalescence of lcow et wcow daemon stores)  and still no joy

**Comment by liquidboy** [comment]
is this being looked at?! I get this with 18.0.0-ce-rc2-win51 (15631) EDGE ..  I'm trying to use LCOW on with WCOW and a linux image that im trying to push to a remote registry

C:\Users\xxxxxxxx>docker push xxxx.xxxx.com/xxxx/test/nginx
The push refers to repository [xxxx.xxxx.com/xxxx/test/nginx]
a103d141fc98: Layer already exists
73e2bd445514: Pushing [==================================================>]  65.27MB/65.27MB
2ec5c0a4cb57: Retrying in 1 second
open \tmp\484c19b590a69f8fb16e34309a587dca8f05af83759fa136a0c0148f1b8245d8-mount\etc\apt\sources.list: The system cannot find the path specified.

**Comment by bhummerstone** [comment]
Tested this on Version 18.02.0-ce-win52 (15732) Edge and it worked fine. Platform is Windows 10 v1709

**Comment by stalb** [comment]
Have you tried to push a linux image or a windows image ?
A priori the problem seems to be specifically related to docker LCOW ( Linux Containers on Windows).

On my side, I still have this problem with docker LCOW with docker 18.02.0-ce-win52 (15732) on windows 10pro 1709 (16299.248).

**Comment by bhummerstone** [comment]
The plot thickens: I pulled the busy box image from Docker hub, then pushed it back to my own public repo on Docker Hub and it worked fine. However, trying to push it to my Azure Container Registry failed with this same error.

**Comment by Abhilash-John** [comment]
Even I'm also facing the same issue on running command :  docker push myDocRepo/first:version1                               
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17134
Docker Version:          18.03.1-ce, build 9ee9f40
Error:
open \tmp\bc51e8d27ccc140e5d0c0d9307562d1bbe0bc3203462736abc5d4acfb70a3d77-mount\root\.cache\pip\http\0\5\d\a\7\05da787f0f46aefc719aed41f7cce94c7777c55d5e064b4c1354b5fd: The system cannot find the path specified.

**Comment by stalb** [comment]
I don't have this problem anymore with docker version 18.05.0-ce-win67 (18263)

```
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:12:05 2018
 OS/Arch:      windows/amd64
 Experimental: true
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.10.1
  Git commit:   f150324
  Built:        Wed May  9 22:29:00 2018
  OS/Arch:      windows/amd64
  Experimental: true
```

**Comment by bhummerstone** [comment]
Same as @stalb: seems to work fine on 18.05.0-ce
