### ISSUE TITLE
Docker Desktop GUI and tray icon not showing

### ISSUE THREAD

**Issue by JarvisChang1997** [docker/for-win#13717]
### Description

Docker desktop is only running in the background, GUI and tray icon are not displayed.
Every time I click on Docker desktop icon, tray icon shows up for only two seconds and then disappears.

I have reinstalled several times and installed different versions but it does not solve the problem.

Windows version: `Windows server 2019`

### Reproduce

1. install Docker desktop
2. run Docker desktop

### Expected behavior

 Docker desktop GUI and tray icons display on desktop.

### docker version

```bash
docker version does not work.

`docker --version`
Docker version 24.0.6, build ed223bc
```

### docker info

```bash
docker info does not work.
```

### Diagnostics ID

C684243A-373D-4BCE-84D5-6EAB89B56C9F/20231003090141

**Comment by bsousaa** [comment]
could you share a video showing the issue?

**Comment by bsousaa** [comment]
Just noticed that you are running Docker Desktop on Windows Server 2019 which is not supported. See https://docs.docker.com/desktop/faqs/windowsfaqs/

I will close the issue for now, but feel free to add additional comments.

**Comment by bsousaa** [comment]
Also, system requirements on Windows https://docs.docker.com/desktop/install/windows-install/#system-requirements
```
Windows 11 64-bit: Home or Pro version 21H2 or higher, or Enterprise or Education version 21H2 or higher.
Windows 10 64-bit: Home or Pro 21H2 (build 19045) or higher, or Enterprise or Education 21H2 (build 19045) or higher. 
```

**Comment by JarvisChang1997** [comment]
@bsousaa 
But I was using Docker Desktop on windows server 2019 and it was working fine, just these days it suddenly doesn't work.
If Windows Server 2019 is not supported, then I shouldn't have been able to use it before.

**Comment by thaJeztah** [comment]
Not supported means exactly that; it may work (and you're lucky), or it may break, but Docker doesn't doesn't support it, and doesn't test or validate if it works. tickets reported for it are out of scope because of that.

**Comment by bsousaa** [comment]
Probably related and impacting other Windows versions: https://github.com/docker/for-win/issues/13718
