### ISSUE TITLE
How to remove Docker for Windows if installer is broken

### ISSUE THREAD

**Issue by evil-shrike** [docker/for-win#1371]
I had some old version of Docker on my machine. When I run Uninstaller it prompted for some temp missing msi (like tmp7.msi) and as it couldn't find it uninstalling didn't work.

A new version (latest 17.09.0-ce-win33) installer detects an installed Docker and prompts to replace it. But it means it just run uninstaller which fails. So the new version installer also fails (Installation canceled).

I tried to remove manaully everything related to Docker on machine. I searched through the machine registry and remove all keys that had "Docker" in its name.

Then I removed all folders related to Docker that I found ("docker" and ".docker").

But the new installer still won't install and continues detecting an installed version. Whether I answer Yes/No to its question "Do you want to replace you current version of Docker for Windows with this new one 17.09.0-ce-win33 (13620)?" the installer canceled and won't proceed. 

So I'm simple unable to install a Docker on the machine. 

What else should I remove/delete to completely remove Docker from my machine?

Is there any way to force the installer to install?

**Comment by jasonbivins** [comment]
Hi @evil-shrike   There are a couple of things you can try - 
the easiest would be to look in the registry for the uninstall value and remove it. Look for anything that mentions Docker here:
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall

If that doesn't help, you can download the MSI version of the installer, and use the Repair or Uninstall flags - https://download.docker.com/win/stable/InstallDocker.msi
``` installdocker.msi -uninstall ```

**Comment by evil-shrike** [comment]
@jasonbivins  
>Look for anything that mentions Docker here:
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall

There's nothing there as I removed everything in registry related to "Docker" trying to clean up my system. As so uninstalling also doesn't work. 

I run normal install with msi-installer from https://download.docker.com/win/stable/InstallDocker.msi
But it silently fails.
I added logging: `msiexec /i InstallDocker.msi /li log.txt`
And here's the log - https://gist.github.com/evil-shrike/f36c36388059cf5cf6eefb734303f1d0

**Comment by evil-shrike** [comment]
This is the most meaningful records in the log that I found:
```
MSI (s) (E4:10) [20:33:35:726]: Invoking remote custom action. DLL: C:\WINDOWS\Installer\MSI79D4.tmp, Entrypoint: CAQuietExec
MSI (s) (E4:98) [20:33:35:726]: Generating random cookie.
MSI (s) (E4:98) [20:33:35:728]: Created Custom Action Server with PID 21992 (0x55E8).
MSI (s) (E4:A8) [20:33:35:760]: Running as a service.
MSI (s) (E4:A8) [20:33:35:761]: Hello, I'm your 32bit Elevated Non-remapped custom action server.
CAQuietExec:  Downloading
CAQuietExec:  Download failed.
CAQuietExec:  One or more errors occurred.
CAQuietExec:  Error 0x80070001: Command line returned an error.
CAQuietExec:  Error 0x80070001: QuietExec Failed
CAQuietExec:  Error 0x80070001: Failed in ExecCommon method
CustomAction QtExecDeferredInstallProperty returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 20:35:15: InstallFinalize. Return value 3.
MSI (s) (E4:7C) [20:35:15:856]: Note: 1: 2265 2:  3: -2147287035 
MSI (s) (E4:7C) [20:35:15:857]: User policy value 'DisableRollback' is 0
MSI (s) (E4:7C) [20:35:15:857]: Machine policy value 'DisableRollback' is 0
```

So it seems that installer tries to download something (as "CAQuietExec:  Download failed" )?
I tried to capture traffic with Fiddler and didn't see anything from msiexec.

**Comment by kambbado** [comment]
Check this posting from @AlphaGit [https://github.com/docker/for-win/issues/349#issuecomment-326774327]()
 The script worked for me

**Comment by evil-shrike** [comment]
@kambbado thanks, but I already tried to run this script (saw it on the [forum](https://forums.docker.com/t/cannot-uninstall-docker-for-windows/15661) ). It failed for me but I manually removed everything that it removes.

**Comment by jasonbivins** [comment]
@evil-shrike   Under C:\windows\installer do you see a folder named  {C482546D-67BB-41BD-8E28-A71A002BC146}

**Comment by evil-shrike** [comment]
@jasonbivins Nope

**Comment by jasonbivins** [comment]
I'm seeing this in the logs you posted - try looking for {155B5EBF-EF5B-48B7-8A3E-D5D4B8BCA61E} under Windows/Installer
You mentioned that you removed Docker manually - Did you clear out the Docker files from the hidden C:\Programdata folder?
```
MSI (c) (28:60) [20:33:35:377]: PROPERTY CHANGE: Adding PackageCode property. Its value is '{155B5EBF-EF5B-48B7-8A3E-D5D4B8BCA61E}'.
MSI (c) (28:60) [20:33:35:377]: Product Code passed to Engine.Initialize:           ''
MSI (c) (28:60) [20:33:35:377]: Product Code from property table before transforms: '{C482546D-67BB-41BD-8E28-A71A002BC146}'
MSI (c) (28:60) [20:33:35:377]: Product Code from property table after transforms:  '{C482546D-67BB-41BD-8E28-A71A002BC146}'
MSI (c) (28:6 ```

**Comment by evil-shrike** [comment]
@jasonbivins I can't see such folder, 
here's what I have under Windows\Installer:
![image](https://user-images.githubusercontent.com/1203230/33396521-d0df85e8-d559-11e7-8428-f8805f8fd5b9.png)

Here's what under ProgramData:
![image](https://user-images.githubusercontent.com/1203230/33396563-ef8537e0-d559-11e7-84a3-b9d21eac030b.png)

**Comment by evil-shrike** [comment]
@jasonbivins holy shit! Removing that key does the trick. Installer didn't found any installed Docker anymore and proceeded. Thanks so much.

I believe the installer should have an options "force replace" with which it does its best to (re)install.

**Comment by AnjolaA** [comment]
@jasonbivins That worked like a charm for me too, after weeks of being Dockerless. Thanks 💯

**Comment by nisarggandhewar** [comment]
how to uninstall docker from windows10.
I go to control panel and click docker to uninstall but below screen appears and not able to uninstall it.
how much time it takes to uninstall I almost wait for 1 hr but still it is not uninstall.
![dockker](https://user-images.githubusercontent.com/43102697/85403209-9cd40680-b57a-11ea-9c6b-83729ec9814e.png)

**Comment by simoncalvin** [comment]
> 
> 
> how to uninstall docker from windows10.
> I go to control panel and click docker to uninstall but below screen appears and not able to uninstall it.
> how much time it takes to uninstall I almost wait for 1 hr but still it is not uninstall.
> ![dockker](https://user-images.githubusercontent.com/43102697/85403209-9cd40680-b57a-11ea-9c6b-83729ec9814e.png)

I was able to get past this issue by manually stopping the Docker Desktop service and restarting the installation.
