### ISSUE TITLE
Docker Desktop logs not working

### ISSUE THREAD

**Issue by dvelaren** [docker/for-win#13714]
### Description

Docker Desktop logs not working. It just outputs a black screen.

![image](https://github.com/docker/for-win/assets/2531157/c61ea611-7f9f-41e1-b77f-a2b8cf49828d)

I tried using a terminal with the logs command and it works correctly...
```sh
docker logs CONTAINER_ID
```

### Reproduce

1. Launch docker compose project.
2. Click on container to check logs
3. Logs are empty

### Expected behavior

Docker Desktop should display the same logs as the terminal outputs

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:32:48 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.24.0 (122432)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:32:16 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.5
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.22.0-desktop.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.8
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.0.7
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.123.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 15.23GiB
 Name: docker-desktop
 ID: c403d072-2518-42e5-b3d6-e35c73ebaead
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

3646F389-833E-45D5-868E-EB814285F3DA/20230930170807

**Comment by ricardojr** [comment]
+1. This is happening for me as well.

**Comment by nachocodexx** [comment]
Here, the same issue :/

**Comment by SrinidhiChandrasekaran** [comment]
Same here.

Diagnostics ID: 59527D77-8DB9-425E-8103-C2B849DDABC7/20231002060312

**Comment by pinkfloydx33** [comment]
Same as well but logs _are_ reported via Logs Explorer plugin, `docker logs` and `docker compose logs`

**Comment by FrancescoD3V** [comment]
I confirm, this problem occurs on both Windows 10 and Windows 11 PCs. I also tried on two PCs with different installations, both using WSL and Hyper-V. Same problem, this way it's really difficult to know the status of the various containers

**Comment by MickBelker** [comment]
> Same as well but logs _are_ reported via Logs Explorer plugin, `docker logs` and `docker compose logs`

This proofs that logs are arriving in Docker Desktop.
However, the behavior of the container logs view has changed.
I can sometimes see all log entries in ONE LINE.
And HTTP logs updating at the bottom.

Looks like a line break conversion issue, putting all console output to ONE line.

**Comment by FrancescoD3V** [comment]
This is probably the case, I downgraded to version 4.23.0 (120376) and the output worked again

**Comment by MickBelker** [comment]
I know, this is not the solution, but just a workaround and a proof that line end definition has a bug here:
Having java.util.logging, and bending the output to force additional WINDOWS line breaks, I can see the logs (formatting is still mangled, but appearing and readable):

java.util.logging.SimpleFormatter.format = %1$tF %1$tL %4$-7s [%4s] - %5$s %n\r\n

The \r\n at the end is doing the magic.
Please fix picking up the correct line breaks from the system asap.

**Comment by bsousaa** [comment]
We are working on a fix. Meanwhile you can use the Log Explorer Extension

**Comment by FrancescoD3V** [comment]
Thanks, let us know when the fix comes out

**Comment by bsousaa** [comment]
You can download 4.24.1 at https://docs.docker.com/desktop/release-notes/#4241

**Comment by FrancescoD3V** [comment]
Thanks for the instant patch, I confirm that the problem has been resolved by downloading version v4.24.1 😎

**Comment by MickBelker** [comment]
It's now fixed and working as before, great!
A huge applause to the developers reacting lightning fast on a bug with big impact on developer community!

**Comment by shift3385** [comment]
Esta versión es compatible con la compilación de Windows 19042??

**Comment by Turab** [comment]
This problem persists in 4.38 and 4.39 versions (latest currently).

**Comment by umi2002** [comment]
I am also seeing this problem on 4.39
