### ISSUE TITLE
Docker Desktop causes "This app is preventing shutdown" issue in Windows 10

### ISSUE THREAD

**Issue by mmarinchenko** [docker/for-win#13734]
### Description

This started happening after upgrading to version **4.23.0**. Versions **4.24.0** and **4.24.1** also cause this issue.

If DD is running when I try to restart or shut down Windows 10, I see the following message on the blue screen (not BSOD, just a normal "shutdown" screen):

_Closing 1 app and shutting down_
_To go back and save your work, click Cancel and finish what you need to._

_![WFAppIcon](https://github.com/docker/for-win/assets/21952330/a15667dd-8bf0-4374-bda7-211d615b478f) This app is preventing shutdown._

Unfortunately, there is no "Show in Task Manager" button on this screen. It also does not display the process name. Only the general Windows Forms icon.

But it's definitely caused by DD, because if I quit it first, then this issue won't occur. I also checked this with the clean DD v4.24.1 installation and collected diagnostic data.

### Reproduce

1. Take Windows 10 (Home edition with WSL2 in my case).
2. Install Docker Desktop v4.23.0 or higher.
3. Launch Docker Desktop.
4. Try shutting down or restarting Windows.

### Expected behavior

Shutting down Windows should be done without issues.

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:32:48 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.24.1 (123237)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:32:16 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.5
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.22.0-desktop.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.8
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.0.7
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.90.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 23.47GiB
 Name: docker-desktop
 ID: dd723bf7-0b1e-4b6b-a889-9de89489c827
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

`56BB853F-02BC-4B80-AECB-0750CCF80A8E/20231012070531`

### Additional Info

I moved VHDX files to the D: drive and disabled the experimental features in DD settings. I'm not sure if this is relevant.

**Comment by AntoineBW** [comment]
Same on Windows 11

**Comment by oom-** [comment]
Same on Windows 11 with vanilla install.
If Docker is installed and running, its impossible to shut down Windows. (No issue when Docker is not on the machine). It happens on 4 of my machines...

**Comment by mmarinchenko** [comment]
### Additional info

When I click _Cancel_ on the blue screen to return to the desktop, I see **3** docker processes in the Task Manager:

|Process|Command Line|
|---|---|
|com.docker.build|`com.docker.build`|
|docker|`docker.exe serve --address npipe:////./pipe/dockerCliApi`|
|Docker Desktop|`"C:\Program Files\Docker\Docker\Docker Desktop.exe" -Autostart`|
---
Dumps: https://1drv.ms/u/s!Akrd5HCAtt1BjDlbGAmTQVeEUwOF

**Comment by bsousaa** [comment]
I'm closing this issue in favour of https://github.com/docker/for-win/issues/13697 to keep discussions in one place. Let me know if you think this is a different issue and I will re-open.
