### ISSUE TITLE
Docker Desktop installer requires McAfee to be disabled 

### ISSUE THREAD

**Issue by Tom01098** [docker/for-win#13738]
### Description

Docker Desktop installer will not install while McAfee AV is running.
![image](https://github.com/docker/for-win/assets/7976946/eee877ed-e928-4e19-ad8d-89455f3e5bb6)

### Reproduce

1. Have McAfee AV installed.
2. Attempt to upgrade Docker Desktop to latest version.

### Expected behavior

Installation should not require McAfee AV to be disabled.

### docker version

```bash
Client: Docker Engine - Community
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:32:16 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Desktop
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:32:16 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.5
    Path:     /usr/local/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.22.0-desktop.2
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /usr/local/lib/docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.8
    Path:     /usr/local/lib/docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-scan
  scout: Docker Scout (Docker Inc.)
    Version:  v1.0.7
    Path:     /usr/local/lib/docker/cli-plugins/docker-scout

Server:
 Containers: 3
  Running: 1
  Paused: 0
  Stopped: 2
 Images: 10
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.90.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 15.58GiB
 Name: docker-desktop
 ID: 0b8000f2-aa82-4609-a8b4-d615ee9be45f
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

4036A451-A9DE-4A6B-AB96-CBEB9580AC35/20231013193936

**Comment by vbayana** [comment]
Tom01098,

Below article helped me to overcome this problem.  All you need to do is disable your MCAfee firewall for few minutes until docker desktop installation completes.  Hope this help you!

https://www.mcafee.com/support/?articleId=TS101322&page=shell&shell=article-view

**Comment by mawielgos** [comment]
Having the same issue updating from 4.24.1 to 4.24.2. I'm running Docker for Windows  on Win11 with McAfee LiveSafe 1.11.279. I tried disabling the Windows Defender Firewall and no luck with the update.

What is the update doing that McAfee is blocking?

**Comment by vbayana** [comment]
in my case McAfee firewall was blocking my docker installer to download installation files from it's server.  It worked for me on Win10, when I turned off MCAfee firewall and retried resuming installation.

**Comment by vbayana** [comment]
Follow the video link "windows https://youtu.be/RCLCpGpZVGw" to disable MCAfee firewall to resume installation.  Post installation do enable it back.

**Comment by mawielgos** [comment]
This video does not apply to McAfee LiveSafe on Windows 11, The Firewall works together and is controlled by Windows 11 Defender now. There is no way to disable the Firewall **within** McAfee in the Windows 11 version, you must do it through Windows Defender in Control Panel.

In any case, disabling the Firewall did not solve this issue for me.  I tried running the MSI as Administrator and that didn't work either.

I'm still unclear on why the Docker Installation would want to have Virus Protection disabled? I've installed Docker updates on Windows 11 and McAfee before with no issues. What's changed?

**Comment by nikolamilojica** [comment]
In my case, this is a privilege issue. Docker desktop update needs those services stopped, and those are system services.

**Comment by Tom01098** [comment]
> Tom01098,
> 
> Below article helped me to overcome this problem. All you need to do is disable your MCAfee firewall for few minutes until docker desktop installation completes. Hope this help you!
> 
> https://www.mcafee.com/support/?articleId=TS101322&page=shell&shell=article-view

Thank you for the link! Unfortunately I am not willing to disable my firewall to download software, especially software I'll run as administrator. As @mawielgos points out, this wasn't the case prior to 4.24.2, so whatever has changed to hit firewall issues should be looked at!

**Comment by one0410** [comment]
I just turn off real-time protection for 15 minutes in Mcafee lifesafe.
So that I can update docker desktop from 4.24.1 to 4.24.2 finally.

**Comment by mawielgos** [comment]
in addition to what @one0410 replied, I also had to close all browser windows, McAfee doesn't completely "go away" until it Browsing protection is not needed.

Still wondering what the update could possibly be doing that McAfee doesn't like.

**Comment by Kuwarii** [comment]
I had to disable the McAfee LiveSafe service from the registry, reboot and then install the Docker update. Once done restart McAfee again, pain in the ass really!

**Comment by Bhalddin** [comment]
@Tom01098 , you are right! Docker should not ask for anti-virus or firewall to be disabled as a condition for installation.

**Comment by REDIDSOFT** [comment]
Hello everyone, I had to permanently disable real-time protection and the firewall, restart the computer and keep the browser closed during the installation. Once installed, I turned the antivirus settings back on.

**Comment by Mennovankapel** [comment]
I have the same problem when upgrading to Docker 4.25.0.
All the above solutions do not work for me

**Comment by Tom01098** [comment]
This issue persists with the current latest version 4.25.0.

**Comment by jlainezs** [comment]
Found same issue in 2.24.1 to 2.24.2 update and now with the 2,24,2 to 2.25.0 update.
I solved it with the steps @JRAVILES pointed, but I did the update using the new version installer instead of using the update feature.

**Comment by mawielgos** [comment]
It appears to be fixed in the 2.25.2 update, I had no issues installing this update

**Comment by BaptisteCrouzet** [comment]
Hi,
Here is the solution that worked for me (sorry french UI).

* Inside the menu on the left go on "Account", then general parameters
![image](https://github.com/docker/for-win/assets/26898487/c9f4a165-5407-4136-b135-2fd2487812bc)

* Under "Access protection", uncheck the checkbox for "Use access protection", then apply
![image](https://github.com/docker/for-win/assets/26898487/d888e7fe-a7b0-49d3-8193-18137b224531)

* Update docker-desktop

* Check again the checkbox for "Use access protection", then apply

**Comment by Tom01098** [comment]
This appears to be fixed in the current version of Docker Desktop for Windows, so I'm happy to close this out :)
