### ISSUE TITLE
LCOW: Simple build failing in Windows Insider build 17046

### ISSUE THREAD

**Issue by diddledan** [docker/for-win#1374]
### Expected behavior

Simple build should complete successfully when using `docker build .` under **Linux containers on Windows** mode in the same way it does in normal mode.

### Actual behavior

Simple build (see `Dockerfile` below) fails when the system is using **Linux containers on Windows** mode with the message:

```plain
PS C:\Users\dllewellyn\Documents\lcow-error> docker build .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM alpine:3.6
 ---> 053cde6e8953
Step 2/2 : RUN addgroup -S app
 ---> Running in 1de7fcbdfc03
The command '/bin/sh -c addgroup -S app' returned a non-zero code: 4294967295
```

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.

FC920A3E-2F36-4F11-AC14-3878AD9C852C/2017-12-01_01-04-02

Notably:

```plain
[00:59:10.718][WindowsDaemon  ][Warning] unable to get exit code for process [error=process 546 in container 806ac8bdf13bf3456dc54fdd0395c198916109e8b4e7db007a31848f16107abf encountered an error during ExitCode: failure in a Windows system call: The compute system exited unexpectedly. (0xc0370106) module=libcontainerd namespace=moby container=806ac8bdf13bf3456dc54fdd0395c198916109e8b4e7db007a31848f16107abf process=init]
```

  - a reproducible case if this is a bug, Dockerfiles FTW

```dockerfile
FROM alpine:3.6

RUN addgroup -S app
```

  - page URL if this is a docs issue or the name of a man page

N/A

  - host distribution and version (Windows version, build number, etc)

Windows 10 Insider Preview Build 17046

### Steps to reproduce the behavior

  1. create `Dockerfile` with above content
  2. ensure **Linux containers on Windows** is enabled in settings
  3. run `docker build .` this fails for me
  4. for comparison switch off **Linux containers on Windows** in settings and re-run the build; it should now succeed

**Comment by rn** [comment]
I cannot repo this and your test works fine for me:
```
docker build .
Sending build context to Docker daemon  828.9MB
Step 1/2 : FROM alpine:3.6
3.6: Pulling from library/alpine
1160f4abea84: Pull complete
Digest: sha256:42c18571af45ffc440bd5127de9ad604f1683e4799dbf7bf588aaee8f95c18f1
Status: Downloaded newer image for alpine:3.6
 ---> e2cd449cde75
Step 2/2 : RUN addgroup -S app
 ---> Running in c057ec5ac561
Removing intermediate container c057ec5ac561
 ---> 07d0413e8052
Successfully built 07d0413e8052
```


However, we have seen intermittent failures with LCOW, which IIRC show the same error you are seeing. Does it always fail for you or just sometimes?

**Comment by alamont** [comment]
I have the same problem on the Windows 10 Build. It only affects building containers. Running is fine.

**Comment by gtaspider** [comment]
Did anyone found a soulution to this? Its gets stranger: even this returns the non-zero code
```
FROM debian:jessie
RUN exit 0

```
returns
```
PS C:\docker\images\test> docker build -t test .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM debian:jessie
 ---> 5dd74d62fab8
Step 2/2 : RUN exit 0
 ---> Running in 2fe64ef0a747
The command '/bin/sh -c exit 0' returned a non-zero code: 4294967295
```

**Comment by rn** [comment]
I've filed https://github.com/moby/moby/issues/36682 and this is a known issue. Closing it here as the moby/moby repository is a better place to track
