### ISSUE TITLE
Docker Desktop Stuck in Deploying component: Use WSL 2 instead of Hyper-V (recommended)

### ISSUE THREAD

**Issue by Garreta11** [docker/for-win#13752]
### Description

I´m trying to download Docker Desktop 4.24.2 for Windows 11. 

Everytime I try to download it, the installer is stuck in Deploying component: Use WSL 2 instead of Hyper-V (recommended).

<img width="723" alt="Captura de pantalla 2023-10-23 155949" src="https://github.com/docker/for-win/assets/5541044/569c6f8e-ecbc-4b26-aace-0855cefe722d">

any idea?

### Reproduce

1. Install Docker Desktop Installer from: https://docs.docker.com/desktop/install/windows-install/

2. Open the installer

3. The installer is stucked in Deploying component: Use WSL 2 instead of Hyper-V (recommended)

### docker version

```bash
Version: 4.24.2
```

### docker info

```bash
Client:
```

### Diagnostics ID

682369C5-4897-4C0F-8CB5-986BA9481404/20231023155954

**Comment by RGB16** [comment]
facing same

**Comment by Garreta11** [comment]
> facing same

let me know if you manage to solve the problem. Thanks

**Comment by Garreta11** [comment]
> facing same

Hi @RGB16 ,
I managed to install it. Basically I had to check Windows Subsystem for Linux before installing it.

Like it says here:
https://docs.docker.com/desktop/troubleshoot/topics/#virtualization

![image](https://github.com/docker/for-win/assets/5541044/40591e87-143e-4a40-ab3e-373250a8f93a)

Hope it helps you.

**Comment by Garreta11** [comment]
solved

**Comment by HYLMW** [comment]
Why have I turned on the above options and still stuck on this interface？

<img width="893" height="854" alt="Image" src="https://github.com/user-attachments/assets/48478022-fc2d-4561-b156-e3d011dfcc30" />

**Comment by RonRadtke** [comment]
For anyone who has trouble with turning on e.g. Virtual Machine Platform:
Start-Process 'Docker Desktop Installer.exe' -Wait -ArgumentList 'install', '--accept-license', '--backend=hyper-v', '--always-run-service'
That switches the default to hyper-v instead of WSL 2.
For some reason this can also be the problem when docker is stuck in other Deploying component steps, like adding user to the group

**Comment by stock-ds** [comment]
For reference:
I had to uninstall VMware and all .net in order to be able to enable Virtual Machine Platform. Doing these 2 things allowed me to enable the Virtual Machine Platform successfully.
