### ISSUE TITLE
[Unstable] There is no "Switch to Linux containers..." or "Switch to Windows containers..." option in the menu on Docker Desktop 4.25.0

### ISSUE THREAD

**Issue by v-mengwe** [docker/for-win#13761]
**OS Version:** Win10 22H2/Win11 23H2
**Docker Desktop:** 4.25.0(126336)
**Regression:** 4.24.2

**Repro Steps:**

1. Install Docker Desktop 4.25.0.
2. Right click the Docker Desktop icon.
3. Check whether there is "Switch to Linux containers..." or "Switch to Windows containers..." option in the menu.

**Expect:**
There is "Switch to Linux containers..." or "Switch to Windows containers..." option in the menu.
![image](https://github.com/docker/for-win/assets/62053665/b7d4fd80-1a42-44fb-ac23-bde1507ca5a3)

**Actual:**
There is no "Switch to Linux containers..." or "Switch to Windows containers..." option in the menu.
![image](https://github.com/docker/for-win/assets/62053665/d90217ab-e5db-44d6-b5bc-414af4381ca2)

**More Info:**
This is an unstable issue, we verified this issue on 11 machines, 7 of them reproduced.

**Comment by gitmgk** [comment]
same +1 , Install Docker Desktop 4.25.0 ,  "Switch to Windows containers"  or  "Switch to Linux containers" no shown option in the menu.

I am uninstall with Revo Uninstaller Pro : Docker Desktop 4.25.0 , windows registry , all file ... , install Docker Desktop 4.25.0 , both switch OK  .

**Comment by nogov** [comment]
+1. The same happened after update to 4.25.0

**Comment by lkelly93** [comment]
+1

**Comment by Florian2145** [comment]
+1. DockerCli.exe is missing since 4.25.0

**Comment by Rhynier** [comment]
+1 on this issue and DockerCli.exe being missing. Windows 11 Enterprise.

**Comment by stevenxi** [comment]
+1 v4.25.0

**Comment by dmduggan** [comment]
Found this workaround in the [release notes](https://docs.docker.com/desktop/release-notes/#4250).

> Switch to Windows containers option in the tray menu may not show up on Windows. As a workaround, edit the settings.json file and set "displaySwitchWinLinContainers": true.

The file can be found at `$env:APPDATA\Docker\settings.json`.

**Comment by amrutha95** [comment]
+1 On windows 11

**Comment by qtqgyt** [comment]
+1 Windows 11 Pro; just created a issue abt it

**Comment by qtqgyt** [comment]
Can I change using the command line or something?

**Comment by qtqgyt** [comment]
+1 Windows 11 Pro

**Comment by qtqgyt** [comment]
Found a workaround; thanks to @dmduggan (with a few modifications.) As he said, in %APPDATA%\Docker\settings.json, first stop docker; set "displaySwitchWinLinContainers": false; then start docker; stop it again; and set "displaySwitchWinLinContainers": true. 
![image](https://github.com/docker/for-win/assets/104375741/6cf971a1-f44d-4e5b-bbf5-eb82e496da60)

**Comment by VadymPatuk** [comment]
> Found a workaround; thanks to @dmduggan (with a few modifications.) As he said, in %APPDATA%\Docker\settings.json, first stop docker; set "displaySwitchWinLinContainers": false; then start docker; stop it again; and set "displaySwitchWinLinContainers": true. ![image](https://user-images.githubusercontent.com/104375741/279843078-6cf971a1-f44d-4e5b-bbf5-eb82e496da60.png)

Same issue here. Thanks for solution 👍🏻

**Comment by JustAnotherLars** [comment]
+1

**Comment by mmbednarz** [comment]
+1

**Comment by paulh-utilita** [comment]
+1 for me, even worse is with the workaround for the json file which I was able to update, I then cannot start the docker desktop service again as it doesn't work when dealing with a non-admin user (constant request for admin creds to then start said service) so I guess only way at present would have been to go back to a previous version of Docker Desktop till this is resolved.

**Comment by mmbednarz** [comment]
There also doesn't seem to be a working method for changing the engine via the command line right now.
Previously, this was possible using dockecli.exe, which has not been available since version 4.25.

**Comment by dmduggan** [comment]
A workaround for DockerCli.exe being removed is to used contexts.

```
PS C:\> docker context ls
NAME                TYPE                DESCRIPTION                               DOCKER ENDPOINT                               KUBERNETES ENDPOINT   ORCHESTRATOR
default *           moby                Current DOCKER_HOST based configuration   npipe:////./pipe/docker_engine
desktop-linux       moby                Docker Desktop                            npipe:////./pipe/dockerDesktopLinuxEngine
desktop-windows     moby                Docker Desktop                            npipe:////./pipe/dockerDesktopWindowsEngine
```

There are three ways to take advantage of this:
1. Use `docker context use` to select the context.
2. Use the `DOCKER_CONTEXT` environment variable to select the context.
2. Use the docker endpoint from above directly using the `DOCKER_HOST` environment variable.

I think you'll have to manually switch to the other OS once using the settings.json workaround from my previous comment. After that you should be able to switch back and forth (I personally use option 2).

**Comment by rostacik** [comment]
I tried with Podman on my box and it did the job so maybe until fixed will work for you too

**Comment by mmbednarz** [comment]
Changing docker context works for me for my scenario. Thanks.

**Comment by lorenrh** [comment]
We've released a new version of Docker Desktop containing a fix for this issue, you can see [the release notes](https://docs.docker.com/desktop/release-notes/)! I'll close this issue for now, but if the issue persists, feel free to open a new issue!

**Comment by voreille** [comment]
Docker v4.25.1 and Windows 10 22H2, the option is still missing

**Comment by ttwmf** [comment]
in %APPDATA%\Docker\settings.json, set "useWindowsContainers": false.

**Comment by IhabKa** [comment]
Hi Guys,
I came accross this posts after i was trying to find a way how to switch from Linux container to Windows container
So, after many research i find the solution after upgrading my Windows 11 home to pro and voila!!!
I now have the button :)

**Comment by ghlouwho** [comment]
On win 10 Pro - Docker Desktop vV4.32.2 - "Right click the Docker Desktop icon." ... I do not get any list as shown at the beginning of this posting, let alone any switch options.  WSL2 installed. How the heck do I run a windows container?

**Comment by RimDammak** [comment]
+1

**Comment by mathieugouin** [comment]
I still have the issue on `Windows 11 IoT Enterprise`.

On my PC, the file was: `settings-store.json`, but I tried the steps above without success.

**Comment by MoritzBlessing** [comment]
Same here nothing seems to help, any ideas?

**Comment by ghlouwho** [comment]
After you open Docker, here is a little white docker icon that is created on the taskbar.  If not there click the up arrow "Show hidden icons", and it should be there.  Right click that and you will then see a menu of items that you can select, one will be "switch to windows containers".

One more tip.  Don't use the upper right hand "X" to exit out of Docker.  If you do you will either have to open task manager to kill Docker tasks, and\or reboot your system to get Docker to run again.  Instead on the bottom left, clock on the three ..., to quit.

**Comment by sibeliuz** [comment]
Wrtiting this to settings-store.json doesn NOT work on Windows10 22H2: "DisplaySwitchWinLinContainers": true,

**Comment by FerrymanLYF** [comment]
嘿，兄弟们，卸载重装就有这个选项了，你们试试
