### ISSUE TITLE
Docker for Windows on Windows Subsystem for Linux

### ISSUE THREAD

**Issue by aarkmon** [docker/for-win#1379]
### Expected behavior
```
docker.exe run --rm -it hello-world
Hello from Docker!
```

### Actual behavior
```
docker.exe run --rm -it hello-world
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'
```

### Information

  - Diagnostic ID: `D4426A11-BD7E-4123-9D08-98FAD6931E2F/2017-12-04_02-58-59`
  - Windows 10 Pro version 1709 build 16299.98
  - Docker version 17.11.0-ce, build 1caf76c

### Steps to reproduce the behavior

  1. `Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux`
  2. Get Ubuntu from Microsoft Store
  3. Run Ubuntu
  4. `docker.exe run --rm -it hello-world`

**Comment by jasonbivins** [comment]
Hi @aarkmon   
It looks like out of the box - you aren't able to attach to a container interactively using Ubuntu through the WSL.  The ``` -it ``` option causes the error. 
This tool may help - but I have not had the time to verify it myself yet
https://github.com/jstarks/npiperelay

**Comment by aarkmon** [comment]
Thanks a lot @jasonbivins. It works for me! 😃
