### ISSUE TITLE
Update to 4.26.0 broke docker on WSL2 (Ubuntu 20.04) in Win11

### ISSUE THREAD

**Issue by lino-alves** [docker/for-win#13824]
### Description

I updated Docker Desktop to version 4.26.0 and now I can't run any command due to required GLIBC versions.

My environment is WSL2 with Ubuntu 20.04 in Windows 11.  
GLIBC version is 2.31 as reported by `ldd --version`

### Reproduce

1. Update Docker Desktop to 4.26.0
2. Run any docker command, for example `docker images`
3. Command fails with:

```
/mnt/wsl/docker-desktop/cli-tools/usr/bin/com.docker.cli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /mnt/wsl/docker-desktop/cli-tools/usr/bin/com.docker.cli)
/mnt/wsl/docker-desktop/cli-tools/usr/bin/com.docker.cli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /mnt/wsl/docker-desktop/cli-tools/usr/bin/com.docker.cli)
```

### docker version

```bash
Docker Desktop 4.26.0 (130397)

(From Windows GUI, since I can't run any docker command at the moment)
```

### docker info

```bash
As reported, I can't run the command to get this information.
```

### Diagnostics ID

064C2D86-1176-4703-8490-BE38EA47BFF7/20231205080614

**Comment by wg485733** [comment]
same here.
[update] looks that everyone is suggesting update OS, which is probably not a viable option for a lot of people. I personally use a CentOS 8 WSL as the backend, and it requires manual build of glibc to get it to work. I don't see any warning about compatibility in the release note, so I highly doubt this is expected at all.

**Comment by blankse** [comment]
We had here the same error. Upgrade to Ubuntu 22.04 fixed the error, because there is a newer GLIBC version.
`sudo do-release-upgrade`

**Comment by sinhada** [comment]
Same here with Debian 11

**Comment by sinhada** [comment]
> Same here with Debian 11

I've just upgraded to debian 12 to have GLIBC at the version required.
It worked, docker works again.

Links if you need to : 

[Debian Upgrade](https://wiki.debian.org/DebianUpgrade)

**Comment by Nosamdaman** [comment]
I'm also having this issue, and updating to 22 is not an option for me given other constraints with my environment.

**Comment by MihaelaStoica** [comment]
Thank you for reporting this issue, and apologies for the disruption it has caused. 
We are investigating it and will report back when we have more details.

**Comment by EliiseS** [comment]
I had the same issue on debian 10

I got it fixed thanks @sinhada, because upgrading to debian 12 also worked for me. 

I ran however into this issue while upgrading: [How did I fix «/usr/bin/perl: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory» in Debian 10 (Buster)? - df.tips](https://df.tips/t/topic/1843/2)

This also broke all of my sudo commands (sudo, su, ect), so I had to re-enter WSL with `wsl --user root` to be able to execute the above commands.

Now docker and sudo both work again 😄

**Comment by hgaia** [comment]
I'm experiencing this problem on Windows 11, I've already updated using the Debian documentation, and the same error still appears when I try to start the project on Docker desktop
```
/mnt/wsl/docker-desktop/cli-tools/usr/bin/com.docker.cli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /mnt/wsl/docker-desktop/cli-tools/usr/bin/com.docker.cli) 
/mnt/wsl/docker-desktop/cli-tools/usr/bin/com.docker.cli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /mnt/wsl/docker-desktop/cli-tools/usr/bin/com.docker.cli)
```
any other suggestions?

**Comment by sinhada** [comment]
> I'm experiencing this problem on Windows 11, I've already updated using the Debian documentation, and the same error still appears when I try to start the project on Docker desktop
> 
> ```
> /mnt/wsl/docker-desktop/cli-tools/usr/bin/com.docker.cli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /mnt/wsl/docker-desktop/cli-tools/usr/bin/com.docker.cli) 
> /mnt/wsl/docker-desktop/cli-tools/usr/bin/com.docker.cli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /mnt/wsl/docker-desktop/cli-tools/usr/bin/com.docker.cli)
> ```
> 
> any other suggestions?

Well all I know is that you can check the GLIBC version with this command 
`ldd --version`

Maybe it depends on the distro you chose when you updated your Debian.

**Comment by hgaia** [comment]
I managed to solve the problem by updating the packages with the debian lib and with the compando to update ubuntu

sudo apt update && sudo apt full-upgrade
restart Ubuntu
sudo do-release-upgrade

thank you @sinhada 

$ ldd --version
ldd (Ubuntu GLIBC 2.35-0ubuntu3.4) 2.35

**Comment by agarzon** [comment]
Having the same problem WSL Debian 11, everything is updated the problem persists.

**Comment by tashi-dev** [comment]
Same issue, WSL2 Ubuntu 20.04.

**Comment by mwu2018** [comment]
Upgrading WSL2 to use Ubuntu 22.04 solved my problem. See https://askubuntu.com/questions/1428423/upgrade-ubuntu-in-wsl2-from-20-04-to-22-04

**Comment by tashi-dev** [comment]
Be mindful, when upgrading the Ubuntu Distro, WSL2 does not update name, though it is updated to 22.04 the name still says 20.04 if you check via poweshell. You need to do `lsb_release -a` on the ubuntu terminal.
Got upgraded to 23.04 due to the name confusion and doing it twice. Seems to have fixed the original issue.

**Comment by RaoXuntian** [comment]
encountering the same issue on wsl2 Ubuntu 18.04 in win 11. I tried to re-install docker-cli and it worked. Below are steps that ChartGPT taught me how to install docker in wsl.

--------------------
ChatGPT Today at 2:37 PM
It looks like Docker may not be installed in your WSL 2 distribution. To install Docker, you can follow these steps:

1. Update the package index and install the necessary dependencies:

```
sudo apt update
sudo apt install apt-transport-https ca-certificates curl gnupg lsb-release
```

2. Add the Docker GPG key:

```
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
```

3. Add the Docker repository to your system:

For Ubuntu 20.04:

```
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
```

For Ubuntu 18.04:

```
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu bionic stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
```

4. Update the package index again and install Docker:

```
sudo apt update
sudo apt install docker-ce docker-ce-cli containerd.io
```

After installing Docker, you should be able to run the `docker` command in your WSL 2 terminal.

**Comment by reloxx13** [comment]
So what do i do now? Docker failed (again), OS update is not possible.
How to downgrade docker desktop now?

**Comment by MihaelaStoica** [comment]
> So what do i do now? Docker failed (again), OS update is not possible. How to downgrade docker desktop now?

@reloxx13 To downgrade Docker Desktop, you would need to uninstall the current version and then install an older one, like 4.25.2, for which you can find the download link in the release notes [here](https://docs.docker.com/desktop/release-notes/#4252).

**Comment by mathieupotier** [comment]
Hi there for WSL2 with Debian distro :
Upgrading from debian 11 (bullseye) to debian 12 (bookworm) fixed the issue for me in a WSL2 context.

but definitely : debian 11 is still LTS and should be supported ... waiting for a fix

**Comment by MihaelaStoica** [comment]
Thanks again for the report!
We have identified the problem and we aim to include a fix in a new Docker Desktop release next week.

**Comment by chaoszh** [comment]
Before the bug is fixed, there may only be one solution to downgrade Docker Desktop to version 4.25.2. Which works for me.

https://docs.docker.com/desktop/release-notes/#4252

**Comment by bulutmf** [comment]
Wow, this broke my setup too, not a good way to release version without a support for older versions.

**Comment by ultrait-sistemas** [comment]
Thank you @RaoXuntian your report worked ok

**Comment by rokln** [comment]
- same on Win 10 / Ubuntu 20.04 LTS
- fixed it by upgrading the to 22.04 LTS
- don't forget to to reconfigure 'WSL Integration' within Docker Desktop settings to point to the correct distro

**Comment by SonGokussj4** [comment]
Ubuntu 18 here, yesterday updated docker and now GLIBC problem.
Will be trying to update to Ubuntu 22 today.

Edit: It helped

**Comment by nikolaipulkkinen** [comment]
> Ubuntu 18 here, yesterday updated docker and now GLIBC problem. Will be trying to update to Ubuntu 22 today.

It might be easier to downgrade to 4.25 and wait for Docker to fix this issue in the next release

**Comment by chaoszh** [comment]
> Before the bug is fixed, there may only be one solution to downgrade Docker Desktop to version 4.25.2. Which works for me.
> 
> https://docs.docker.com/desktop/release-notes/#4252

It is quite annoying that even though I unchecked the auto-update option, my docker desktop tried to pull updates everytime it is restarted. I think it is another bug or is it my misbehavior?

![image](https://github.com/docker/for-win/assets/33629609/45134690-9fc3-4325-972a-934f59b700dc)

**Comment by MihaelaStoica** [comment]
@chaoszh If Docker Desktop performed the auto check for update despite the setting being disabled, then that sounds like a bug. Could you please open a separate ticket with a Diagnostics ID?

**Comment by jmto-cambri** [comment]
Really annoying to upgrade things and then later notice oh, this latest release has this big caveat but is still offered it to everyone. Maybe couple of days more would have gotten the fixed release, but now it was annoying extra work.

But lesson learned. Always also look at the "Release notes" link, not just what the app shows as it has no mention that oh btw, if you have like Ubuntu LTS older than 22.04, you are sol. 

![image](https://github.com/docker/for-win/assets/127502429/43ace564-70f2-4b14-a11a-2e51a5311767)

**Comment by jmto-cambri** [comment]
Also as now I did went and did that.. now there's no option like close that.. and check updates again, if the fixed version is released. Maybe it forgets that in restart, maybe it doesn't..

**Comment by thaonx** [comment]
> Before the bug is fixed, there may only be one solution to downgrade Docker Desktop to version 4.25.2. Which works for me.
> 
> https://docs.docker.com/desktop/release-notes/#4252

How to downgrade to 4.25.2 @chaoszh ?

**Comment by chaoszh** [comment]
> > Before the bug is fixed, there may only be one solution to downgrade Docker Desktop to version 4.25.2. Which works for me.
> > 
> > https://docs.docker.com/desktop/release-notes/#4252
> 
> How to downgrade to 4.25.2 @chaoszh ?
> 

just uninstall 4.26 and install again from https://docs.docker.com/desktop/release-notes/#4252

**Comment by Lovening** [comment]
After updating to 4.26.1 this problem is solved in my wsl2

**Comment by lino-alves** [comment]
Yes, just updated now and the issue is solved in 4.26.1.

**Comment by JAlbertoGonzalez** [comment]
This solved the problem on my **WSL Debian 11.8**: **Upgrade to Debian 12**


Error after trying `docker compose up -d`

```
/mnt/wsl/docker-desktop/cli-tools/usr/bin/com.docker.cli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /mnt/wsl/docker-desktop/cli-tools/usr/bin/com.docker.cli)
/mnt/wsl/docker-desktop/cli-tools/usr/bin/com.docker.cli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /mnt/wsl/docker-desktop/cli-tools/usr/bin/com.docker.cli)
```

Solution:

```
sudo su

echo "deb http://deb.debian.org/debian/ bookworm main
deb http://deb.debian.org/debian/ bookworm-updates main" > /etc/apt/sources.list && \
apt update -y && \
apt upgrade -y && \
apt dist-upgrade -y && \
apt autoremove -y && \
exit
```

[Source](https://gist.github.com/bramtechs/50d724a33d37278d7ca003c6119c8fea)

**Comment by reloxx13** [comment]
Thanks for fixing.    
Please nuke breaking releases like this next time to avoid further spreading of the issue.

**Comment by nextchar** [comment]
Still facing the issue. WSL2, Ubuntu-22.04 LTS and Docker Desktop 4.26.1 (131620)

/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found

/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found

**Comment by 1714080902120** [comment]
Me too, with the latest docker version 4.26.1

**Comment by MihaelaStoica** [comment]
> Still facing the issue. WSL2, Ubuntu-22.04 LTS and Docker Desktop 4.26.1 (131620)
> 
> /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found
> 
> /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found

@nextchar, I cannot reproduce the issue with Ubuntu-22.04 and Docker Desktop 4.26.1. What docker command returns these errors, and are there any more details to the error, like "required by ..."? 
Also, what is the GLIBC version in your Ubuntu-22.04 distro, as reported by `ldd --version`?

**Comment by millsoft** [comment]
so the problem still exists. I just downgraded to Docker 4.25.2 and my docker is working now properly. (in WSL2).
How to downgrade:

- in your docker desktop, disable auto updates.
- download installer from here: https://docs.docker.com/desktop/release-notes/#4252
- launch the installer like so: `"Docker Desktop Installer.exe" install --disable-version-check`

**Comment by MihaelaStoica** [comment]
If anybody still experiences this issue with Docker Desktop 4.26.1, please give us some details, as suggested here:

>  What docker command returns these errors, and are there any more details to the error, like "required by ..."?
> Also, what is the GLIBC version in your Ubuntu-22.04 distro, as reported by ldd --version?
