### ISSUE TITLE
Docker Desktop 4.25.2 fails to start w/o internet and "Send usage statistics" feature enabled

### ISSUE THREAD

**Issue by netrusov** [docker/for-win#13825]
### Description

Tried to launch Docker Desktop while my routers were in reboot and got the following error

![image](https://github.com/docker/for-win/assets/6795441/4675eed2-93b5-488a-aece-0972562b9f21)

While inspecting the logs at first I thought that `wsl.exe --update --web-download` was causing the error, but I've also stumbled across several connection issues to api.segment.io and notify.bugsnag.com

I've connected to the internet, launched Docker, disabled "Send usage statistics", disconnected from all networks again, then restarted Docker Desktop (through Quit + Start cycle) and it started w/o issues

### Reproduce

1. Enable "Send usage statistics" feature
2. Quit Docker Desktop
3. Disconnect from all networks
4. Start Docker Desktop

### Expected behavior

Docker Desktop should start without issues

### docker version

```bash
Client: Docker Engine - Community
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:32:16 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Desktop
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:32:16 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.5
    Path:     /usr/local/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.0-desktop.1
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /usr/local/lib/docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.9
    Path:     /usr/local/lib/docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-scan
  scout: Docker Scout (Docker Inc.)
    Version:  v1.0.9
    Path:     /usr/local/lib/docker/cli-plugins/docker-scout

Server:
 Containers: 7
  Running: 0
  Paused: 0
  Stopped: 7
 Images: 22
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.133.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 23.44GiB
 Name: DESKTOP-H0I3HE5
 ID: 50d800ac-a151-48d5-8c6e-9d859b0a7946
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### Diagnostics ID

9547ED51-5410-421A-8CBA-194923E26594/20231205085114

### Additional Info

Here's a clean log of failed startup:  [com.docker.backend.exe-usage-stats-enabled.log](https://github.com/docker/for-win/files/13557534/com.docker.backend.exe-usage-stats-enabled.log)

**Comment by netrusov** [comment]
just saw that Docker Desktop 4.26.0 update is available, so I checked this version too. unfortunately, I'm still able to reproduce the issue

**Comment by neonima** [comment]
Hi @netrusov thanks for reporting this - I've tried on a W11 with the latest update of Docker Desktop - What wsl distro are you using? I can see a few linux commands are not found in the diag you've send, that might be a clue to help me replicate the issue

**Comment by netrusov** [comment]
at the moment of submitting this issue I was using Ubuntu 20.04, which I've upgraded to 22.04 (through `do-release-upgrade`) later because of this bug: https://github.com/docker/for-win/issues/13824

I don't beleive the problem is with the distro, it fails way before trying to setup integration with it

**Comment by KatTomrushka** [comment]
Hi @netrusov Unfortunately, after quite a few attempts by different teams, we couldn't replicate this but we think the issue might not be related to usage statistics all. Rather the file encoding (1252) might mess up the WSL command parsing.
Regardless, we are currently working on a feature to support usage statistics cache so that in case of any errors, we can recover the data at subsequent successful startups.

**Comment by netrusov** [comment]
@KatTomrushka I think you're right. tried to reproduce the same on my laptop but with no success. I have exactly the same errors in the log, but Docker starts just fine.

It looks like this can only happen under certain conditions and I was just "lucky" to encounter this problem, should have checked on another device first.

I'm closing the issue then, thanks for your help 👍
