### ISSUE TITLE
Docker Desktop - Unexpected WSL error | WSL Distribution docker-desktop is missing

### ISSUE THREAD

**Issue by ToshiNamura** [docker/for-win#13845]
### Description

Hello, I have encountered a problem running docker-desktop. Which I haven't been able to solve for two days now.

### Error message:
![image](https://github.com/docker/for-win/assets/86116871/399be6ac-fde5-4070-904e-18279e96c740)
An unexpected error was encountered while executing a WSL command. Common causes include access rights issues, which occur after waking the computer or not being connected to your domain/active directory.

Please try shutting WSL down (wsl --shutdown) and/or rebooting your computer. If not sufficient, WSL may need to be reinstalled fully. As a last resort, try to uninstall/reinstall Docker Desktop. If the issue persists please collect diagnostics and submit an issue (https://docs.docker.com/desktop/troubleshoot/overview/#diagnose-from-the-terminal).

I have tried all the suggested solutions from: #13273 but it didn't help in any way.

- I have tried with the latest version of Docker Desktop
- I have tried disabling enabled experimental features
- I have uploaded Diagnostics

### Error details:

- wsl -l -v --all
```
    NAME      STATE           VERSION
 * Ubuntu     Stopped        2
```

- wsl --status
```
 Default distribution: Ubuntu
 Default version: 2
 The Windows subsystem for Linux was last updated on 12/14/2023
 Automatic WSL updates are enabled.
 Kernel version: 5.10.102.1
```

- com.docker.diagnose.exe gather LOG: 
[com.docker.diagnode.exe.gather.log.txt](https://github.com/docker/for-win/files/13689630/com.docker.diagnode.exe.gather.log.txt)

- com.docker.diagnose.exe check LOG: 
[com.docker.diagnode.exe.check.log.txt](https://github.com/docker/for-win/files/13689642/com.docker.diagnode.exe.check.log.txt)

- An important element that I noticed is that the docker system does not create its own distributions: "docker-desktop" and "docker-desktop-data". this is stated in the "com.docker.diagnode.exe.check.log.txt "at the very end:

```
 Please investigate the following 1 issue:
 1 : The test: are WSL distros installed?
     Failed with: WSL Distribution docker-desktop is missing
```
* At the same time, the WSL system itself has been updated to the latest version and the distribution works fine: "Ubuntu".

### Information
- Windows Version: Windows 10 Pro 64bit 22H2
- Docker Desktop Version: 4.26.0
- WSL2 or Hyper-V backend? WSL2
- Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Reproduce

install docker-desktop
run docker-desktop

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:08:44 2023
 OS/Arch:           windows/amd64
 Context:           default
```

### docker info

```bash
Client:
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.0-desktop.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.3-desktop.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  0.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.10
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.2.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe
```

### Diagnostics ID

8ebc137b-1e6c-4817-b50f-f8841de18370/20231215201821

**Comment by ToshiNamura** [comment]
### Added:
 - I forgot to mention it. Initially, docker-desktop worked fine, but after resetting Windows to factory settings, completely reinstalling the system and cleaning the disks - this problem arose.

**Comment by ToshiNamura** [comment]
### Closed:
 - I managed to solve the problem by using the bypass from the comment: 
 https://github.com/docker/for-win/issues/13580#issuecomment-1619667316

 - The problem was that the WSL was not being updated correctly for some reason, constantly damaging the WSL system files. I downloaded the latest version and installed it from: [https://github.com/microsoft/WSL/releases](url)
 
  - Now everything is working and functioning perfectly!
 
### Thank you very much, n0v1!

**Comment by yogesh-debug** [comment]
In Windows 10-11
Below steps works for me

```
1 bcdedit /set hypervisorlaunchtype auto
2 shutdown /r /t 0
```

**Comment by anhquan911** [comment]
Enable hyper v on windows 11. Finally.

**Comment by aitechguy0105** [comment]
Same Error occured 
I followed ToshiNamura's guide, install wsl reinstall docker, but all things didn;t work.
Please help me.

**Comment by Nil7x** [comment]
@aitechguy0105 Uninstall docker desktop and reinstall it. Uncheck recommended WSL when reinstalling. On my computer, I can successfully open docker desktop, and then check WSL integration in the settings and apply&restart. :)

**Comment by sxyy123** [comment]
> @aitechguy0105卸载docker桌面并重新安装。重新安装时取消选中推荐的 WSL。在我的电脑上，可以成功打开docker桌面，然后在设置中勾选WSL集成并应用并重启。 :)

It works, thank you

**Comment by danbran99** [comment]
I solved the problem of my side ... I had windows 11 home... I upgraded for windows 11 pro for 100$. I uninstalled and reinstalled all the features related to wsl and it works. I suspect you need a pro version of windows.

**Comment by berkay-repos** [comment]
> ### Closed:
> * I managed to solve the problem by using the bypass from the comment:
>   [After update on Docker, WSL 2 does not work correct #13580 (comment)](https://github.com/docker/for-win/issues/13580#issuecomment-1619667316)
> * The problem was that the WSL was not being updated correctly for some reason, constantly damaging the WSL system files. I downloaded the latest version and installed it from: [https://github.com/microsoft/WSL/releases](url)
> * Now everything is working and functioning perfectly!
> 
> ### Thank you very much, n0v1!

Updating WSL through the link you provided solved the problem for me too. I've been struggling with this error for so long. Thank you so much! 🙏🙏🙏

**Comment by wmdzkey** [comment]
I also encountered the same problem.
Perhaps it's my network problem, and trying the above methods and running "wsl -- update" in PS is ineffective
The final solution is to find the offline update package for WSL,
After installing the latest version of WSL, version 4.28.0 of Docker Desktop was successfully launched.
Download address:
https://github.com/microsoft/WSL/releases

**Comment by AmosSpark** [comment]
> @aitechguy0105 Uninstall docker desktop and reinstall it. Uncheck recommended WSL when reinstalling. On my computer, I can successfully open docker desktop, and then check WSL integration in the settings and apply&restart. :)

@Nil7x Thank you, docker engine got running when I did not check the use WSL (recommended) when installing docker. But when I try to check "Use the WSL 2 based engine" in docker>settings>general, it crashed. I unchecked and it got running again.

**Comment by OFD16** [comment]
> In Windows 10-11 Below steps works for me
> 
> ```
> 1 bcdedit /set hypervisorlaunchtype auto
> 2 shutdown /r /t 0
> ```

thats works for me also i think i updated wsl version

**Comment by AmosSpark** [comment]
finally, it was that port 53 was taken. So I followed this comment without starting wsl: https://github.com/microsoft/WSL/issues/4364#issuecomment-760495585
and then set up wsl with this: https://kind.sigs.k8s.io/docs/user/using-wsl2/#setting-up-wsl2

**Comment by kao-yu** [comment]
> > @aitechguy0105卸载docker桌面并重新安装。重新安装时取消选中推荐的 WSL。在我的电脑上，可以成功打开docker桌面，然后在设置中勾选WSL集成并应用并重启。 :)
> 
唉，弄了一整天终于这个方法成功了，谢谢你

**Comment by RinzeSAMA** [comment]
> 卸载 docker desktop，然后重新安装。重新安装时取消选中建议的 WSL。在我的计算机上，我可以成功打开 docker desktop，然后在设置中检查 WSL 集成并应用并重新启动。:)

Thanks for your advices

**Comment by soto320** [comment]
In Windows 10-11 Below steps works for me

1 bcdedit /set hypervisorlaunchtype auto
2 shutdown /r /t 0

**Comment by ajay311517104001** [comment]
In my case, Installing any one of the linux destro sorted this issue In windows 11, 

open windows powershell in admin mode and run "wsl --install Ubuntu"

Just in case if you're not able to install Ubuntu follow these steps

1. Enable the virtualization technology in BIOS (AMD) , for Intel there must be a equivalent VM option to enable.
2. Windows Desktop Search -> Turn windows feature on or off -> check the "Windows subsystem for linux"
3.now try installing the Ubuntu with this command "wsl --install Ubuntu"

After following these steps, linux destro installation should be successful . Try opening the docker app again it should work fine!

**Comment by ArmanShirzad** [comment]
hey guys ,  for me this worked

1- even though virtualization is enabled in bios u might wanna toggle it if the hypervisor is grayed like the attached sc
restart> disable virtualization> restart again and enable it > go windows features and turn on all the features including the hyporvisor which is now accessible 
2- type hyper v manager in windows search and u ll be able to see a gui app like the screenshot 
3- its ok if task manager doesnt show hyper v enabled  dont panic!

use the below commands to check if things are smooth.
1-  Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V-All  | expected output{FeatureName      : Microsoft-Hyper-V-All
DisplayName      : Hyper-V
Description      : Provides services and management tools for creating and running virtual machines and their
                   resources.
RestartRequired  : Possible
State            : Enabled
CustomProperties :
}

2- Get-Service -Name vmcompute | expected output {Status   Name               DisplayName
------   ----               -----------
Running  vmcompute          Hyper-V Host Compute Service}

3- make sure u have wsl and ubuntu installed  and set to version 2 \wsl --set-default-version 2
[![Image](https://github.com/user-attachments/assets/7d67bc9a-6229-46ab-9547-89eb106cfed8)
![Image](https://github.com/user-attachments/assets/54017b6c-3949-4a75-a636-aeeabc4861fd)
![Image](https://github.com/user-attachments/assets/5640fc71-327d-46a3-a5a1-16ee8fafbd41)
](url)
and finally run docker desktop and enjoy

**Comment by KoushikReddy24** [comment]
If you couldn't run docker desktop with WSL even after trying all the above steps, then you can simply do that with the help Hyper-V. Choose Hyper-V instead of WSL. You can do that from the popup that you get while installing docker desktop. Uncheck the "Use WSL 2 instead of Hyper-V" option.

![Image](https://github.com/user-attachments/assets/61bfd706-44f6-4976-a226-b7753e3afc8f)
