### ISSUE TITLE
Cannot run tilt / k8s certificate expires

### ISSUE THREAD

**Issue by accu4x** [docker/for-win#13850]
### Description

Hey there! I'm running tilt / k8s on windows 10 machine, using docker desktop (latest version) with wsl

Today, I got this fun error
`Error: unable to create controller manager: Get "https://127.0.0.1:56505/api?timeout=32s": x509: certificate has expired or is not yet valid: current time 2023-12-19T13:27:45-05:00 is after 2023-12-19T13:38:20Z`

I tried the following - but nothing seems to work (with each item, I stop docker, perform the action, then restart docker):

- Deleted the pki folder in AppData/Local
- I reset the k8s stack
- I purged all data in docker
- I un-installed and re-installed docker - desktop

Despite all of this, the certificates in pki look the same. I've seen references to kubeadm (which can reset all of my certificates) but I cannot seem to download in such a way that I can access via powershell.

I do have Ubuntu installed on my machine, but I don't believe it is accessing the same system resources as the WSL. 

Is there a way to reset all the certificates in windows (with either a way within powershell)?

### Reproduce

running tilt up spawns the errror

### Expected behavior

I would think that deleting the pki folder and then restarting kubenertes client would generate with a new certificate, but it does not

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:08:44 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.26.1 (131620)
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:02 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.25
  GitCommit:        d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.0-desktop.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.3-desktop.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  0.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.10
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.2.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 18
  Running: 18
  Paused: 0
  Stopped: 0
 Images: 11
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc version: v1.1.10-0-g18a0cb0
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.133.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 11.68GiB
 Name: docker-desktop
 ID: 159ea6fb-622d-4b34-be30-b32488c537cc
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

e3dfa1a2-bfd4-435f-9028-4507f0945f18/20231219182749

**Comment by nicks** [comment]
can you also post `tilt doctor`?

**Comment by accu4x** [comment]
Tilt: v0.30.11, built 2022-11-07
System: windows-amd64
---
Docker
- Host: npipe:////./pipe/docker_engine
- Server Version: 24.0.7
- API Version: 1.43
- Builder: 2
- Compose Version: v2.23.3-desktop.2
---
Kubernetes
- Env: unknown
- Context: aware-dev-01-admin
- Cluster Name: aware-dev-01
- Namespace: default
- Container Runtime: containerd
- Version: v1.26.3
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-out
- Machine: 805a58ace4fe955d0113ede6ec1a2c1d
- Repo:

**Comment by accu4x** [comment]
Ah-Ha! I fixed it. It turns out that I needed to upgrade tilt to the latest version.
