### ISSUE TITLE
Application Error We've reported this to our error tracker.  TypeError: A.map is not a function

### ISSUE THREAD

**Issue by ghost** [docker/for-win#13883]
### Description

Application Error
We've reported this to our error tracker.

TypeError: A.map is not a function

### Reproduce

Application Error
We've reported this to our error tracker.

TypeError: A.map is not a function

### Expected behavior

Application Error
We've reported this to our error tracker.

TypeError: A.map is not a function

### docker version

```bash
Application Error
We've reported this to our error tracker.

TypeError: A.map is not a function
```

### docker info

```bash
Application Error
We've reported this to our error tracker.

TypeError: A.map is not a function
```

### Diagnostics ID

Application Error We've reported this to our error tracker.  TypeError: A.map is not a function

### Additional Info

Application Error
We've reported this to our error tracker.

TypeError: A.map is not a function

**Comment by lorenrh** [comment]
Hello, with the information we have we cannot investigate the issue. I'll be closing this, but if the problem still persists, you can open a fresh issue with a diagnostics bundle following the [troubleshoot guide](https://docs.docker.com/desktop/troubleshoot/overview/#diagnose)?
