### ISSUE TITLE
Docker desktop does not update its host entry when there are network changes

### ISSUE THREAD

**Issue by milesjoe09** [docker/for-win#13916]
### Description

when Docker desktop is first installed and configured it puts an entry into the host file (C:\Windows\System32\drivers\etc\hosts) of:
X.X.X.X host.docker.internal
if there are any subsequent changes to the network (the hosts LAN private IP changes), Docker Desktop does not update this entry.

meaning if I change from my home WIFI network to my mobile hotspot my Windows host machine IP address changes from 10.1.1.1 to 192.168.1.1 and host.docker.internal no longer resolves to the correct IP Address.

I have tried  restarting Docker Desktop and WSL, a full reboot of the host machine, and Docker Desktop never updates the hosts entry. 

### Reproduce

1. install docker desktop and resolve host.docker.internal to your machine IP with something lie ping
2. change your host machine IP, either with DHCP changes on your local network or by switching to a different network, and you will see that host.docker.internal is still resolving to the old IP, due to the entry in the hosts file.

### Expected behavior

Seeing as Docker desktop writes the entry into the hosts file (C:\Windows\System32\drivers\etc\hosts), I would expect it to keep updated.. with something like a polling mechanism. or maybe just docker desktop re-writes the entry when it starts up, so a restart of Docker Desktop would update the entry. 

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:32:48 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.25.2 (129061)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:32:16 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.5
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.0-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.9
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.0.9
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 7
  Running: 7
  Paused: 0
  Stopped: 0
 Images: 60
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.133.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 7.607GiB
 Name: UK-L1P0YST3
 ID: 966a6d41-1199-4438-a705-ac2615429c47
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### Diagnostics ID

N/A

**Comment by MihaelaStoica** [comment]
@milesjoe09 Do you have the setting  `Add the *.docker.internal names to the host's /etc/hosts file` enabled? It's in General settings, under `Use the WSL 2 based engine` (see [docs](https://docs.docker.com/desktop/settings/windows/#:~:text=Add,and%20your%20containers.)). 
When this is enabled, Docker Desktop updates the hosts file when started, so quitting and restarting Docker Desktop should be enough for the hosts file to be updated with the new IP address.

**Comment by milesjoe09** [comment]
thanks for this.. looks like an upgrade of Docker desktop unticked this setting... have re-enabled 
thanks :-)
