### ISSUE TITLE
container encountered an error during Start: failure in a Windows system call: The compute system exited unexpectedly.

### ISSUE THREAD

**Issue by erichexter** [docker/for-win#1391]
### Expected behavior
start a container using docker run, I expect the container to start or give me some information about what I need to fix in the container.  I went through the logs and event log and cannot determine why the container is unable to start. 

### Actual behavior
 Error response from daemon: container 939d8316f152f202f2f52ae093e6495789ae57626f0f71c76ac4b51997083ec7 encountered an error during Start: failure in a Windows system call: The compute
system exited unexpectedly. (0xc0370106).

### Information

9D2E90D2-2CA3-4E3F-BB6B-4B024BC4A180/2017-12-06_21-26-39

https://gist.github.com/erichexter/07aec102b3a7769c64380e8028a3e0cd

### Steps to reproduce the behavior

  1. ... build container
  2. ... run container using docker run quarterspot/all-in-one

**Comment by erichexter** [comment]
I believe the root cause of this was mapping a volume as a parent directory to IIS websites.

**Comment by agtokty** [comment]
@erichexter did you find a way for this problem ? 

I still getting an error for the following volume settings in docker-compose file. 

```
    volumes:
      -  ./V/PS/ModulData/:C:/inetpub/wwwroot/moduledata
```

## error : 
command :  `docker-compose up -d`
```
Recreating netcadbase2_base_1 ... error

ERROR: for netcadbase2_base_1  Cannot start service base: container 1765c7de53a6bd4add02e3a3b64fbf9366fe70792f2b3b5abc0f057cd2f61382 encountered an error during Start: failure in a Windows system call: The compute system exited unexpectedly. (0xc0370106)

ERROR: for base  Cannot start service base: container 1765c7de53a6bd4add02e3a3b64fbf9366fe70792f2b3b5abc0f057cd2f61382 encountered an error during Start: failure in a
Windows system call: The compute system exited unexpectedly. (0xc0370106)
ERROR: Encountered errors while bringing up the project.

```

 **.env** file :  
`COMPOSE_CONVERT_WINDOWS_PATHS=0`

```
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:06:28 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.4
  Git commit:   0520e24
  Built:        Wed Mar 21 23:21:06 2018
  OS/Arch:      windows/amd64
  Experimental: true
```

But it's working on a folder other than inetpub/wwwroot.

**Comment by asyowish** [comment]
I met the same issue, but don't know how to resolve it so far.
