### ISSUE TITLE
Docker Desktop claims service is not running

### ISSUE THREAD

**Issue by bstordrup** [docker/for-win#13954]
### Description

My Docker Desktop will not start - it claims that the service is not running and either hangs when trying to start the service or just exits.

But the service is running, and Docker Desktop briefly shows the list of images before blanking out.

![image](https://github.com/docker/for-win/assets/43523397/1a1ec630-8283-4c26-9626-26fb5251f70a)

![image](https://github.com/docker/for-win/assets/43523397/37ad68f7-f4f3-468f-811c-b7bf72f2e617)

### Reproduce

Just trying to open Docker Desktop.

### Expected behavior

Docker Desktop to be running

### docker version

```bash
docker version
error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version": open //./pipe/docker_engine: The system cannot find the file specified.
Client:
 Cloud integration: v1.0.35+desktop.11
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:13:02 2024
 OS/Arch:           windows/amd64
 Context:           default
```

### docker info

```bash
docker info
Client:
 Version:    25.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.6-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.24
    Path:     C:\Program Files\Docker\cli-plugins\docker-debug.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.22
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.5.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
ERROR: error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/info": open //./pipe/docker_engine: The system cannot find the file specified.
errors pretty printing info
```

### Diagnostics ID

EAFB0F61-ACC0-4E9B-92B8-CE78C796DD5E/20240307065520

### Additional Info

Docker Desktop version is 4.28.0

**Comment by zakkoo** [comment]
> ### Description
> My Docker Desktop will not start - it claims that the service is not running and either hangs when trying to start the service or just exits.
> 
> But the service is running, and Docker Desktop briefly shows the list of images before blanking out.
> 
> ![image](https://private-user-images.githubusercontent.com/43523397/310773278-1a1ec630-8283-4c26-9626-26fb5251f70a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MDM2OTUsIm5iZiI6MTcwOTgwMzM5NSwicGF0aCI6Ii80MzUyMzM5Ny8zMTA3NzMyNzgtMWExZWM2MzAtODI4My00YzI2LTk2MjYtMjZmYjUyNTFmNzBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA5MjMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzNzNkNWQzN2YzZjY5M2YzMDk2YzAzOGNiOWViODBlMzZlMWQzNmIxZGFhOTNlZmJmZDkxZGU1Y2U1OTRmMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BTs8x7D3Me_n4kw-cQadhhNiVY2gpU_WlUdAPTT8JjE)
> 
> ![image](https://private-user-images.githubusercontent.com/43523397/310774676-37ad68f7-f4f3-468f-811c-b7bf72f2e617.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MDM2OTYsIm5iZiI6MTcwOTgwMzM5NiwicGF0aCI6Ii80MzUyMzM5Ny8zMTA3NzQ2NzYtMzdhZDY4ZjctZjRmMy00NjhmLTgxMWMtYjdiZjcyZjJlNjE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA5MjMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllYjMyZTFhNzAzMDdhMjMyYTk2Y2NlOGRmNjM1YTZmZGFjNzQ1NGM0NTFhNjg3ODY3ZGM2MzBjYTk2OGE2MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eveBhE59D2L_-jezB1UypBqVTjPQO6RVweKHK_sesQ8)
> 
> ### Reproduce
> Just trying to open Docker Desktop.
> 
> ### Expected behavior
> Docker Desktop to be running
> 
> ### docker version
> ```shell
> docker version
> error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version": open //./pipe/docker_engine: The system cannot find the file specified.
> Client:
>  Cloud integration: v1.0.35+desktop.11
>  Version:           25.0.3
>  API version:       1.44
>  Go version:        go1.21.6
>  Git commit:        4debf41
>  Built:             Tue Feb  6 21:13:02 2024
>  OS/Arch:           windows/amd64
>  Context:           default
> ```
> 
> ### docker info
> ```shell
> docker info
> Client:
>  Version:    25.0.3
>  Context:    default
>  Debug Mode: false
>  Plugins:
>   buildx: Docker Buildx (Docker Inc.)
>     Version:  v0.12.1-desktop.4
>     Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
>   compose: Docker Compose (Docker Inc.)
>     Version:  v2.24.6-desktop.1
>     Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
>   debug: Get a shell into any image or container. (Docker Inc.)
>     Version:  0.0.24
>     Path:     C:\Program Files\Docker\cli-plugins\docker-debug.exe
>   dev: Docker Dev Environments (Docker Inc.)
>     Version:  v0.1.0
>     Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
>   extension: Manages Docker extensions (Docker Inc.)
>     Version:  v0.2.22
>     Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
>   feedback: Provide feedback, right in your terminal! (Docker Inc.)
>     Version:  v1.0.4
>     Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
>   init: Creates Docker-related starter files for your project (Docker Inc.)
>     Version:  v1.0.1
>     Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
>   sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
>     Version:  0.6.0
>     Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
>   scout: Docker Scout (Docker Inc.)
>     Version:  v1.5.0
>     Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe
> 
> Server:
> ERROR: error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/info": open //./pipe/docker_engine: The system cannot find the file specified.
> errors pretty printing info
> ```
> 
> ### Diagnostics ID
> EAFB0F61-ACC0-4E9B-92B8-CE78C796DD5E/20240307065520
> 
> ### Additional Info
> Docker Desktop version is 4.28.0

exact same behavior

**Comment by zakkoo** [comment]
Experiencing the same issue here. Upon clicking "Start service," the application freezes, and my CPU utilization spikes significantly. The Task Manager reporting a 15% CPU usage and the system remains unresponsive throughout.

**Comment by bstordrup** [comment]
![DockerDesktopWillNotStart](https://github.com/docker/for-win/assets/43523397/79a01bd3-dc6d-4dab-8168-08fe6757d87d)

Note that the Docker Desktop GUI actually get to display the list of images, but then exits because it claims the service is not started.

And UI specifies in the lower left corner that docker engine is running.

When executing the `docker version` command, it reports failure trying to open the pipe `//./pipe/docker_engine`, but there is no pipe with that name. Instead, there is a `docker_engine_windows` pipe being listened to from the `dockerd.exe` process.

Also when executing `docker version`, it reports: `in the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect`. The docker client - is that the `docker` being called here? If so, this is being done in a cmd window with elevated privileges.

**Comment by bstordrup** [comment]
Hmmm. Just noticed that starting the WSL distro `docker-desktop-data` fails and exits.

Trying to start it on an elevated command prompt results in the following:

```
wsl --distribution docker-desktop-data
<3>WSL (11) ERROR: CreateProcessParseCommon:711: Failed to translate C:\Program Files\Docker\Docker
<3>WSL (11) ERROR: CreateProcessParseCommon:757: getpwuid(0) failed 2
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\Microsoft\jdk-21.0.2.13-hotspot\bin
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\WINDOWS\system32
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\WINDOWS
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\WINDOWS\System32\Wbem
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\WINDOWS\System32\WindowsPowerShell\v1.0\
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\WINDOWS\System32\OpenSSH\
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\Microsoft SQL Server\150\DTS\Binn\
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files (x86)\Microsoft SQL Server\150\Tools\Binn\
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\Microsoft SQL Server\150\Tools\Binn\
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\Azure Data Studio\bin
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\LINQPad6
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Tools\NuGet
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Tools\Git
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\dotnet\
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\Microsoft SQL Server\140\Tools\Binn\
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\LINQPad7
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\ProgramData\chocolatey\bin
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\WINDOWS\system32
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\WINDOWS
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\WINDOWS\System32\Wbem
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\WINDOWS\System32\WindowsPowerShell\v1.0\
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\WINDOWS\System32\OpenSSH\
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\Docker\Docker
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files (x86)\Microsoft SQL Server\160\Tools\Binn\
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\Microsoft SQL Server\160\Tools\Binn\
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\Microsoft SQL Server\160\DTS\Binn\
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files (x86)\Microsoft SQL Server\160\DTS\Binn\
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\nodejs\
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\TortoiseSVN\bin
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\PowerShell\7\
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\Calibre2\
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\GitHub CLI\
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\Docker\Docker\resources\bin
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\Git\cmd
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Users\Benny.Tordrup\AppData\Local\Programs\Python\Launcher\
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Users\Benny.Tordrup\AppData\Local\Programs\Python\Python39\Scripts\
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Users\Benny.Tordrup\AppData\Local\Programs\Python\Python39\
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Users\Benny.Tordrup\scoop\shims
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Users\Benny.Tordrup\AppData\Local\Programs\Python\Python311\Scripts\
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Users\Benny.Tordrup\AppData\Local\Programs\Python\Python311\
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Users\Benny.Tordrup\AppData\Local\Microsoft\WindowsApps
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\Azure Data Studio\bin
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Users\Benny.Tordrup\.dotnet\tools
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Users\Benny.Tordrup\AppData\Local\Programs\Microsoft VS Code\bin
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\MongoDB\Tools\100\bin
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Tools\Polaris\bin
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Users\Benny.Tordrup\AppData\Local\GitHubDesktop\bin
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate c:\Users\Benny.Tordrup\AppData\Roaming\Python\Scripts
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files (x86)\Rico Suter\NSwagStudio\
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Users\Benny.Tordrup\.dotnet\tools
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Users\Benny.Tordrup\AppData\Roaming\npm
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Git\Personal\dotnet\dotnet_sdk\artifacts\tmp\Debug\.dotnet\tools
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Git\Visma\VismaBusiness\VismaBusiness\Bin
<3>WSL (11) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Git\Visma\VismaBusiness\VismaBusiness\.repo\bin
Processing fstab with mount -a failed.
Failed to mount C:\, see dmesg for more details.
Failed to mount G:\, see dmesg for more details.
Failed to mount H:\, see dmesg for more details.

<3>WSL (11) ERROR: CreateProcessEntryCommon:334: getpwuid(0) failed 2
<3>WSL (11) ERROR: CreateProcessEntryCommon:505: execvpe /bin/sh failed 2
<3>WSL (11) ERROR: CreateProcessEntryCommon:508: Create process not expected to return
```

**Comment by bstordrup** [comment]
This is really weird. Found a thread on docker community that mentioned fixing it by deleting the `%appdata%\Docker\settings.json` [1]. Did not do exactly that, but renamed it. And this solved the issue!

The weird thing is that the only differences were 3 settings:
- autoStart: was `true` in old version and `false` in new version
- requireVmnetd: was `false` in old version and `true` in new version
- useWindowsContainers: was `true` in old version and `false` in new version

Of these, I can only imagine the requireVmnetd setting having some impact, but not sure why.


1. https://forums.docker.com/t/solved-docker-failed-to-start-docker-desktop-for-windows/106976/7?u=bennytordrupvisma

**Comment by bstordrup** [comment]
@zakkoo, try the suggestion, I just posted.

**Comment by bstordrup** [comment]
Closing issue since I got it working.

**Comment by zakkoo** [comment]
@bstordrup 

> @zakkoo, try the suggestion, I just posted.

I renamed the `%appdata%\Docker\settings.json` file and started Docker. The json file was then recreated. Unfortunately I still got the error. I then proceeded to change the values to "old" in the newly created json file
```
autoStart: true
requireVmnetd: false
useWindowsContainers: true
```

That did also not help. I will now try to reinstall Docker.

**Comment by karman-docker** [comment]
@bstordrup com.docker.service is needed only if you are running Docker Desktop in Windows container mode or if you are using Hyper-V as backend. Since you mentioned in your new settings.json you changed useWindowsContainers to false, that would remove the dependency on com.docker.service and hence you were able to start Docker Desktop.

Can I know if you have Beyond Trust installed on your system ? I have seen Beyond Trust policy interfering and impacting Docker Desktop functionality. Few errors I see in your diagnostics were observed when Beyond Trust policy was resulting a similar issue.

**Comment by karman-docker** [comment]
@zakkoo can you provide a diagnostics from your system and also let us know if you have Beyond Trust installed ?

**Comment by bstordrup** [comment]
@karman-docker how will I know mø is it part of Windows or something additional. Also, the machine is company managed, so there might be something, I do not control.

**Comment by karman-docker** [comment]
@bstordrup you will have to check with your IT team, I don't know if we can easily find out from task manager looking for process name matching/containing  'beyond trust"

**Comment by bstordrup** [comment]
@karman-docker ok. I will check Monday.

**Comment by bstordrup** [comment]
Looked through my running processes - none appear as "beyond trust"

**Comment by henryroach** [comment]
As workaround I set startup as manual for both docker services and after rebooting and running Docker Desktop, there is no warning about docker services not running but everything works.
<img width="436" alt="image" src="https://github.com/docker/for-win/assets/16500454/4e14021c-fa8e-43ac-b3bf-06406bfdc3b8">

**Comment by bstordrup** [comment]
The issue was not experienced at startup, but occurred long after start out
of the blue.

fre. 22. mar. 2024 08.47 skrev Jindřich Šváb ***@***.***>:

**Comment by MikeAtBS** [comment]
Removing settings.json worked for me (I'm using Windows containers)
