### ISSUE TITLE
Docker automatically starts even when it is disabled in startup apps on windows 11 machine

### ISSUE THREAD

**Issue by pankaj-2503** [docker/for-win#13973]
### Description

Whenever I  boot up my pc docker desktop starts automatically even when it is disabled in startup apps in my pc

### Reproduce

NA

### Expected behavior

It should open manually

### docker version

```bash
Version- 4.27.1
```

### docker info

```bash
NA
```

### Diagnostics ID

NA

**Comment by MihaelaStoica** [comment]
This issue has been fixed in Docker Desktop 4.27.2 and 4.28.0. See [release notes](https://docs.docker.com/desktop/release-notes/#:~:text=Fixed%20a%20bug%20with%20the%20dashboard%20being%20shown%20at%20startup).
(same as https://github.com/docker/for-win/issues/13887)
