### ISSUE TITLE
No hypervisor is present on this system.

### ISSUE THREAD

**Issue by jacobrillema** [docker/for-win#1398]
### Actual behavior
![2017-12-07_22-13-28](https://user-images.githubusercontent.com/3656296/33749613-b558d4e8-db9c-11e7-88b6-050623513a7e.png)

Client:
 Version:      17.11.0-ce
 API version:  1.34
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:37:39 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.24)
 Go version:   go1.8.5
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:34:19 2017
 OS/Arch:      windows/amd64
 Experimental: true

docker: failed to register layer: failed to start service utility VM (applydiff 7e4ab85e20fbb3c2210ec83e7f07c0fb2e3048e916255d804f08b178afcff4cb): container 7e4ab85e20fbb3c2210ec83e7f
07c0fb2e3048e916255d804f08b178afcff4cb_svm encountered an error during CreateContainer: failure in a Windows system call: No hypervisor is present on this system. (0xc0351000) extra i
nfo: {"SystemType":"container","Name":"7e4ab85e20fbb3c2210ec83e7f07c0fb2e3048e916255d804f08b178afcff4cb_svm","Layers":null,"HvPartition":true,"HvRuntime":{"ImagePath":"C:\\Program Fil
es\\Linux Containers","LinuxInitrdFile":"initrd.img","LinuxKernelFile":"bootx64.efi"},"ContainerType":"linux","TerminateOnLastHandleClosed":true}.
See 'docker run --help'.

### Information
![2017-12-07_21-40-54](https://user-images.githubusercontent.com/3656296/33748638-9a7f2190-db97-11e7-914a-4f37c5367bea.png)

### Steps to reproduce the behavior

  1. Install latest Docker for Windows Edge build.
  2. docker run --rm -it alpine sh

**Comment by jasonbivins** [comment]
Hi @jacobrillema 
Was this working on a recent version, and stopped after the upgrade to the latest Docker build?
Can you share the results of the docker info command?

**Comment by vortechs2000** [comment]
Seeing the same thing after upgrading to Docker 17.12.0-ce-rc4.  This had been working with 17.11...I have hyper-v installed but disabled via `bcdedit /set hypervisorlaunchtype off` so that I can run a different VM infrastructure.

**Comment by jacobrillema** [comment]
I was able to get it working again with latest updates on the edge version. See below for version information. However not sure if this update fixed it or in between version's I had to disable hyperv and re-enable it again and wondering if that fixed it. I can confirm what @vortechs2000 is seeing as well that we get the "not present error" even if hyperv is installed but turned off via bcdedit. 

```
docker info
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 2
Server Version: 17.12.0-ce
Storage Driver: windowsfilter (windows) lcow (linux)
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 3.922GiB
Name: 
ID: XUFK:G7U4:6QX3:QEQ7:IMD3:KANT:5FI4:PSGB:S6AS:IUWJ:2KAU:WU76
Docker Root Dir: C:\ProgramData\Docker\lcow
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 25
 System Time: 2018-01-05T15:29:36.9571214-05:00
 EventsListeners: 1
Username: 
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
```
 docker version
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:11:19 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.24)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:15:52 2017
  OS/Arch:      windows/amd64
  Experimental: true
```

**Comment by bardware** [comment]
> This had been working with 17.11

Is this version available somewhere?

**Comment by dmcghee** [comment]
I'm also seeing this error. I've confirmed that hyper visor is installed, and I can confirm that my sample containers were working with docker for windows version 18.03.0-ce-win59 (16762). Just downloaded docker edge, and I'm still seeing the same error when trying to run a sample container. I'm going to try a hard reboot to see if that helps...

**Comment by nazymko** [comment]
Same issue , neither stable neither edge versions not working on Windows. Hyper-V - enabled  and steps from https://success.docker.com/article/manually-enable-docker-for-windows-prerequisites executed 

`{"SystemType":"Container","Name":"7f8df08120e6a4d1a93697d80e7c3309a3d94a5837f842b342eac30b4462ca85","Owner":"docke
  r","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\7f8df08120e6a4d1a93697d80e7c3309a3d94a5837f842b342eac30b4462ca85","Layers":[{"ID":"223e2be9-
  4581-5252-b41a-cc839b4aa727","Path":"C:\\ProgramData\\Docker\\windowsfilter\\eba5fc2b1066af09af4977fd8bd084110b3ffc09d097e98a4bf98ec5855d124f"},{"ID":"70085dd0-f11c-590d-8d38-a1f20dcb9b
 `

**Comment by Farham0** [comment]
same here
