### ISSUE TITLE
Windows Server 2016 - Azure cannot create NAT internal network plugin not found

### ISSUE THREAD

**Issue by dguimbellot** [docker/for-win#1400]
### Expected behavior
docker-compose up creates simple NAT internal network

### Actual behavior
ERROR: compose.cli.errors.log_api_error: plugin not found

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ... azure portal
  2. ... create windows server 2016 datacenter - with containers
(download docker-compose!!, submitted feedback to azure on this bad image, but not easy to directly correlate like we can do here in github)

3. docker-compose up 
PS C:\devops> docker-compose up
docker-compose : Creating network "devops_test" with driver "NAT"
At line:1 char:1
+ docker-compose up
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Creating networ...th driver "NAT":String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
plugin not found

PS C:\devops> docker-compose --version
docker-compose version 1.17.1, build 6d101fb0

PS C:\devops> docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
9c45c50dafe9        nat                 nat                 local
a750e67ca6d3        none                null                local

PS C:\devops> type .\docker-compose.yml
version: "3"
networks:
    test:
        driver: nat
services:
    web:
        image: agilecraft/agilecraft-app:latest
        ports:
            - "80:8000"
        depends_on:
            - db
        environment:
            DB_SERVER: db
            DB_CATALOG: AgileCraft
            DB_USERNAME: howie
            DB_PASSWORD: ****
        networks:
            - test            
            
    db:
        image: microsoft/mssql-server-windows-express
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: ****
            ACCEPT_EULA: "Y"
  
        networks:
            - test

**Comment by jasonbivins** [comment]
Hi @dguimbellot  
It looks like the error is coming from trying to create a second NAT network on a Windows server, which you can't really do on Windows.  Docker already creates one on Install, so you can't add anymore.
``` PS C:\devops> docker network ls
NETWORK ID NAME DRIVER SCOPE
9c45c50dafe9 nat nat local
a750e67ca6d3 none null local ```
 Please see here for more information or troubleshooting infohttps://blogs.technet.microsoft.com/virtualization/2016/05/25/windows-nat-winnat-capabilities-and-limitations/

**Comment by rn** [comment]
This issue tracker is for the Docker for Windows application, which runs on Windows 10. To get help with Docker on Windows Server please see http://success.docker.com/article/where-to-get-help-with-windows.
Thanks
