### ISSUE TITLE
Error saving credentials: error storing credentials - err: fork/exec /usr/bin/docker-credential-desktop.exe: exec format error, out: ``

### ISSUE THREAD

**Issue by ReneshMLal** [docker/for-win#14039]
### Description

I am using WSL Ubuntu, and when I try to perform "docker login", I get an error 
"Error saving credentials: error storing credentials - err: fork/exec /usr/bin/docker-credential-desktop.exe: exec format error, out: ``"
![image](https://github.com/docker/for-win/assets/109696345/1ba0e0d1-4fbb-4213-89fe-65a4f2a96cae)

**Comment by naivedeveloper95** [comment]
how did you fix it? I am getting the same error.

![image](https://github.com/docker/for-win/assets/15083393/c72025f6-4ae5-49d8-b715-4110ec2e24cc)

**Comment by ReneshMLal** [comment]
I uninstalled the docker desktop and installed it again, I did all the configurations for WSL and it worked.

**Comment by pwood-cyb** [comment]
Just in case anyone else runs into this error, following [this StackOverflow answer](https://stackoverflow.com/a/46893613/6327358)'s suggestion solved the problem for me.

**Comment by ItsPouria** [comment]
> Just in case anyone else runs into this error, following [this StackOverflow answer](https://stackoverflow.com/a/46893613/6327358)'s suggestion solved the problem for me.

yes this is the answer. running `rm -rf ~/.docker/config.json` worked for me.

**Comment by luizcarlosfaria** [comment]
Removing `credsStore` json node from  `~/.docker/config.json` solves to me.

## Before
```
{
  "auths": {
    "my-private-registry-address": {
      "auth": "authkey"
    }
  },
  "credsStore": "desktop.exe"
}
```

## After
```
{
  "auths": {
    "my-private-registry-address": {
      "auth": "authkey"
    }
  }
}
```

**Comment by cajytam** [comment]
> Removing `credsStore` json node from `~/.docker/config.json` solves to me.
> 
> ## Before
> ```
> {
>   "auths": {
>     "my-private-registry-address": {
>       "auth": "authkey"
>     }
>   },
>   "credsStore": "desktop.exe"
> }
> ```
> 
> ## After
> ```
> {
>   "auths": {
>     "my-private-registry-address": {
>       "auth": "authkey"
>     }
>   }
> }
> ```

It worked for me, thank you!
