### ISSUE TITLE
Docker Unexpected error

### ISSUE THREAD

**Issue by Amulya2528** [docker/for-win#14034]
### Description

running engine: waiting for the VM setup to be ready: starting WSL engine: bootstrapping in the main distro: starting wsl-bootstrap: context canceled
docker engine is not running.

### Reproduce

1. run docker as administrator and its showing the above error.

### Expected behavior

Docker engine should run

### docker version

```bash
20.10.
```

### docker info

```bash
did wsl --shutdown and restarted, even then got the same error.
```

### Diagnostics ID

A300B799-05AD-44E7-ADB7-EB3BF6C757E4/20240425093032

**Comment by hblovo** [comment]
Getting back to an old version might  help because I just saw your problem recently based on the error information.

**Comment by interplexed** [comment]
For me this appeared after upgrading Docker Desktop to v4.29.0 (latest) on Windows 11 23H2 (22631.3447) within the last week.  After the error message, re-running the program results in the same error message.  Using task manager to shutdown all docker-related processes and re-run, appears to work.  
FWIW, it feels like a timeout based on internet connection.  I'm setting my laptop to hibernate with it's not-so-great VPN connection up... it's as if when I disconnect the VPN, Docker Desktop loads normally.  
Diagnostics ID: 57D5AE4A-0D1B-4ABD-9746-CB4530A08E0D/20240428084301

**Comment by samir-puranik** [comment]
I am also experiencing the same issue. Diagnostics ID: 49DC9064-604D-494C-ACB0-236581DCA481/20240429165804

```
docker --version
Docker version 26.0.0, build 2ae903e

wsl --list
Windows Subsystem for Linux Distributions:
docker-desktop-data (Default)
docker-desktop
```

**Comment by samir-puranik** [comment]
> Getting back to an old version might help because I just saw your problem recently based on the error information.

Tried this and confirming that this works. I uninstalled 4.29.0 and re-installed 4.28.0 and now it's working again

**Comment by liumudj** [comment]
回退到之前版本有效

**Comment by liumudj** [comment]
https://docs.docker.com/desktop/release-notes/#docker-desktop-community-2501

**Comment by romancristinel** [comment]
Disabling the auto start on system start (via Task Manager / Startup apps) for Docker Desktop fixed it for me .

**Comment by senina4** [comment]
**This work for me:**
```
wsl --unregister docker-desktop 
```
Restart Docker Desktop

### (edited: this command won't delete your data)

**Comment by xszefo** [comment]
@senina4 , it also works for me, thanks! :)

**Comment by smartercow** [comment]
> **This work for me:**
> 
> ```
> wsl --unregister docker-desktop
> wsl --unregister docker-desktop-data
> ```
> 
> Restart Docker Desktop

Same

**Comment by SoraMakes** [comment]
had the same problem. 

```
wsl --unregister docker-desktop
wsl --unregister docker-desktop-data
```

didn't solve the problem for me, but downgrading to 4.28.0 did.

**Comment by senina4** [comment]
> **This work for me:**
> 
> ```
> 
> wsl --unregister docker-desktop
> 
> wsl --unregister docker-desktop-data
> 
> ```
> 
> Restart Docker Desktop

**Because you uninstall docker desktop (I guess).**

**Comment by clairmont32** [comment]
I had a really hard time cleanly uninstalling 4.28.0 on Windows 11 Enterprise and subsequently installing 4.29.0. 
```
wsl --unregister docker-desktop
wsl --unregister docker-desktop-data
```
worked for me!

**Comment by fathyelshemy** [comment]
> I am also experiencing the same issue. Diagnostics ID: 49DC9064-604D-494C-ACB0-236581DCA481/20240429165804
> 
> ```
> docker --version
> Docker version 26.0.0, build 2ae903e
> 
> wsl --list
> Windows Subsystem for Linux Distributions:
> docker-desktop-data (Default)
> docker-desktop
> ```

thanks @samir-puranik  it works for me

**Comment by floris-xlx** [comment]
> wsl --unregister docker-desktop-data

works for me too, thanks b

**Comment by SoraMakes** [comment]
> had the same problem.
> 
> ```
> wsl --unregister docker-desktop
> wsl --unregister docker-desktop-data
> ```
> 
> didn't solve the problem for me, but downgrading to 4.28.0 did.

Could now solve it for me. Looks like i had some docker binaries installed in my main WSL Disto (potentially i installed them manually some time in the past, no idea) and they now caused problems. I am not sure if i actually had to do the unregister part, but these are the steps i used to fix the problem for me

- winget remove Docker.DockerDesktop
- in wsl: apt remove docker*
- wsl --unregister docker-desktop (docker-desktop-data was already deleted by uninstalling Docker Desktop)
- winget add Docker.DockerDesktop
- reboot
- after starting Docker Desktop the first time it told me something failed and I should do wsl --shutdown -> wsl --shutdown

now after the next start of DockerDesktop it seems to work

**Comment by senina4** [comment]
When I uninstall Docker desktop docker-desktop-data didnt remove

**Comment by fjh1997** [comment]
> **This work for me:**
> 
> ```
> wsl --unregister docker-desktop
> wsl --unregister docker-desktop-data
> ```
> 
> Restart Docker Desktop

warning！this will clean all your images and containers

**Comment by xelmirage** [comment]
> I had a really hard time cleanly uninstalling 4.28.0 on Windows 11 Enterprise and subsequently installing 4.29.0.
> 
> ```
> wsl --unregister docker-desktop
> wsl --unregister docker-desktop-data
> ```
> 
> worked for me!

works for me!

**Comment by xrzm** [comment]
> **这对我来说是工作：**
> 
> ```
> wsl --unregister docker-desktop
> wsl --unregister docker-desktop-data
> ```
> 
> 重启 Docker Desktop

this work for me ,thanks

**Comment by nikosvil** [comment]
> **This work for me:**
> 
> ```
> wsl --unregister docker-desktop
> wsl --unregister docker-desktop-data
> ```
> 
> Restart Docker Desktop

Had the same issue on 4.32.0, those commands fixed it. Thanks!

**Comment by nikolausmoll** [comment]
> > **This work for me:**
> > ```
> > wsl --unregister docker-desktop
> > wsl --unregister docker-desktop-data
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Restart Docker Desktop
> 
> warning！this will clean all your images and containers
yeah, I don't know why the warning is not part of the original post... 

anyway, did not solve it for me for Docker Desktop 4.33.1 (162079) - have to start the Docker software manually, but that sucks.

**Comment by lorenrh** [comment]
4.34.0 has been released with a fix for this issue, more information o the [release notes](https://docs.docker.com/desktop/release-notes/).

I'll be closing this issue, but if the problem persists please open a fresh issue!

**Comment by andreaswrife** [comment]
The issue persists.

Updated from 4.33.1, being plagued with the the #13806 error. 
Now with 4.34.0 I get this issue. #14034 
Although the release notes indicate that this bug is fixed.

I have tried the `wsl --unregister` quickfix without success.

I am gonna play around with it a bit more, see if there is some setting I've changed..

**Comment by vaibhavPH** [comment]
> 4.34.0 has been released with a fix for this issue, more information o the [release notes](https://docs.docker.com/desktop/release-notes/).
> 
> I'll be closing this issue, but if the problem persists please open a fresh issue!

not fixed for me even in docker desktop `4.3.4`

**Comment by andrea-reale** [comment]
Hey all - thanks for reporting that the problem persists with 4.34. Unfortunately, the fix introduced in 4.34 had itself a bug. Please, take a look at for a possible workaround https://github.com/docker/for-win/issues/14294#issuecomment-2324427416.


Since this issue is now closed, **please use #14294 for any further communication** (and remember to include diagnostics!).

**Comment by jeaneigsi** [comment]
> **This work for me:**
> 
> ```
> wsl --unregister docker-desktop
> wsl --unregister docker-desktop-data
> ```
> 
> Restart Docker Desktop

work perfectly thanks

**Comment by java43wuyi** [comment]
I reinstalled docker and followed Microsoft's instructions https://learn.microsoft.com/en-us/windows/wsl/install to install and start wsl2, then restarted docker. If there are any problems during the installation, check the Microsoft website https://learn.microsoft.com/en-us/windows/wsl/troubleshooting#installation-issues for solutions

**Comment by Carlos-vargs** [comment]
> > **This work for me:**
> > ```
> > wsl --unregister docker-desktop
> > wsl --unregister docker-desktop-data
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Restart Docker Desktop
> 
> warning！this will clean all your images and containers

too late 😔

**Comment by PatchFact** [comment]
For me the solution was disabling "use legacy mode" for cmd.exe. In my case, I had set up a shortcut to run a terminal command on startup which had this enabled and it affects all terminals (properties -> options -> legacy mode).

You might have enabled this feature at some point before if none of the above fixes worked for you.

**Comment by ackvf** [comment]
> > > **This work for me:**
> > > ```
> > > wsl --unregister docker-desktop
> > > wsl --unregister docker-desktop-data
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Restart Docker Desktop
> > 
> > 
> > warning！this will clean all your images and containers
> 
> too late 😔

Is it possible to reattach the images back to avoid the loss?

**Comment by brazeiro63** [comment]
The issue:
running engine: waiting for the VM setup to be ready: starting WSL engine: bootstrapping in the main distro: running wsl-bootstrap: exit status 0xffffffff

Is still present.

Docker Desktop v4.38.0
Diagnostic ID: 3710D364-1E7E-42DA-9D7D-C1DBAAE334D1/20250213155646

Edição	Windows 10 Pro
Versão	22H2
Instalado em	‎06/‎08/‎2023
Compilação do SO	19045.5487
Experiência	Windows Feature Experience Pack 1000.19061.1000.0

**Comment by Nesemis** [comment]
> For me the solution was disabling "use legacy mode" for cmd.exe. In my case, I had set up a shortcut to run a terminal command on startup which had this enabled and it affects all terminals (properties -> options -> legacy mode).
> 
> You might have enabled this feature at some point before if none of the above fixes worked for you.

It worked for me. I checked 'Use legacy console' for hiding the terminal console for autorunning Syncthing, but now it made docker not work. If I disable legacy console, now the Syncthing terminal shows. Kinda annoying
