### ISSUE TITLE
docker pull not working in case of any windows image

### ISSUE THREAD

**Issue by satyaki1008** [docker/for-win#1403]
### Expected behavior
docker pull works

### Actual behavior
error appears after image extraction is done
**ERROR**-"ead9f4ead3c5: Download complete
failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage C:\ProgramData\Docker\windowsfilte
r\27502a3b916d06696f8bb4c0128170ae874d3a81e36622febe07d92ee4c35c20\UtilityVM: The process cannot access the file because
 it is being used by another process."

### Information
I am running docker for windows edge version(17.11 ce version) on my windows 10 pro.After docker is started,I am not being able to pull any windows image.After extraction,it shows this error.Can any help?

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...install docker for windows edge version (17.11 ce) on windows 10 pro
  2. ...docker pull microsoft/windowsservercore
![docker2](https://user-images.githubusercontent.com/33922657/33804873-041c067a-ddd4-11e7-8b64-9a39855c962d.PNG)

**Comment by jasonbivins** [comment]
Hi @satyaki1008 do you have any other Windows containers running?

**Comment by satyaki1008** [comment]
none.This is my first image that I was going to pull.

**Comment by jasonbivins** [comment]
@satyaki1008 
Typically I see this error when there is a container running that has some of the files in one of the layers locked, or when there is some sort of file scan going on.  
Try making sure that your Anti-virus isn't scanning the C:\Programdata\Docker\ folder, and if you're using VSS, try disabling it for this folder too

**Comment by satyaki1008** [comment]
Well many of the online issues related to this is pointing towards a possible anti virus problem.
