### ISSUE TITLE
wont start

### ISSUE THREAD

**Issue by ellic052** [docker/for-win#1404]
### Actual behavior
wont start
**### Information**
Command failed: C:\Program Files\Docker Toolbox\docker-machine.exe -D create -d virtualbox --virtualbox-memory 2048 default,Docker Machine Version: 0.13.0, build 9ba6da9,Found binary path at C:\Program Files\Docker Toolbox\docker-machine.exe,Launching plugin server for driver virtualbox,Plugin server listening at address 127.0.0.1:50192,() Calling .GetVersion,Using API Version 1,() Calling .SetConfigRaw,() Calling .GetMachineName,(flag-lookup) Calling .GetMachineName,(flag-lookup) Calling .DriverName,(flag-lookup) Calling .GetCreateFlags,Found binary path at C:\Program Files\Docker Toolbox\docker-machine.exe,Launching plugin server for driver virtualbox,Plugin server listening at address 127.0.0.1:50196,() Calling .GetVersion,Using API Version 1,() Calling .SetConfigRaw,() Calling .GetMachineName,(default) Calling .GetMachineName,(default) Calling .DriverName,(default) Calling .GetCreateFlags,(default) Calling .SetConfigFromFlags,(default) Calling .PreCreateCheck,(default) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --version,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | 5.2.2r119230,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: wmic computersystem get hypervisorpresent,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | HypervisorPresent ,(default) DBG | TRUE ,(default) DBG | ,(default) DBG | },Error with pre-create check: "This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)",open C:\Users\Server\.docker\machine\machines\default\default\Logs\VBox.log: The system cannot find the path specified.,notifying bugsnag: [Error with pre-create check: "This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)"],
  - Diagnostic ID from "Diagnose & Feedback" in the menu.
357593E0-93A5-4495-B0A2-A2164A6EB409/2017-12-10_04-27-56

  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by shubhamj-cuelogic** [comment]
Facing the same issue

C:\Program Files\Docker\Docker\Resources\bin\docker-machine.EXE,Launching plugin server for driver virtualbox,Plugin server listening at address 127.0.0.1:2050,() Calling .GetVersion,Using API Version 1,() Calling .SetConfigRaw,() Calling .GetMachineName,(flag-lookup) Calling .GetMachineName,(flag-lookup) Calling .DriverName,(flag-lookup) Calling .GetCreateFlags,Found binary path at C:\Program Files\Docker\Docker\Resources\bin\docker-machine.EXE,Launching plugin server for driver virtualbox,Plugin server listening at address 127.0.0.1:2055,() Calling .GetVersion,Using API Version 1,() Calling .SetConfigRaw,() Calling .GetMachineName,(default) Calling .GetMachineName,(default) Calling .DriverName,(default) Calling .GetCreateFlags,(default) Calling .SetConfigFromFlags,(default) Calling .PreCreateCheck,(default) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --version,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | 5.1.26r117224,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: wmic computersystem get hypervisorpresent,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | HypervisorPresent ,(default) DBG | TRUE ,(default) DBG | ,(default) DBG | },Error with pre-create check: "This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)",open C:\Users\ownser\.docker\machine\machines\default\default\Logs\VBox.log: The system cannot find the path specified.,notifying bugsnag: [Error with pre-create check: "This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)"],
