### ISSUE TITLE
zsh completion in WSL won't be removed after Docker Desktop quits

### ISSUE THREAD

**Issue by timsu92** [docker/for-win#14056]
### Description

Before version 4.27.0, booting up Docker Desktop creates zsh completion symlinks, and removes them after Docker Desktop quits.
In version 4.30.0, issue #13910 is closed because we now able to see the working link. However, since this symlink isn't removed after quitting Docker Desktop, every new login shell shows warning regarding "no such file or directory". The symlink should be removed.

### Reproduce

1. Open Docker Desktop in Windows
2. See the working `/usr/share/zsh/vendor-completions/_docker` is linked to `/mnt/wsl/docker-desktop/cli-tools/usr/share/zsh/vendor-completions/_docker` in WSL (Ubuntu 22.04 in my case)
3. Turn off Docker Desktop
4. See the link is linking to file which doesn't exists since the `cli-tools` iso file is ejected
5. Even if I reboot my WSL distro, the broken link still exists

### Expected behavior

The link `/usr/share/zsh/vendor-completions/_docker` is removed so that zsh won't try to read the disappeared completion file.

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.13
 Version:           26.1.1
 API version:       1.45
 Go version:        go1.21.9
 Git commit:        4cf5afa
 Built:             Tue Apr 30 11:46:57 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Desktop
 Engine:
  Version:          26.1.1
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.9
  Git commit:       ac2de55
  Built:            Tue Apr 30 11:48:28 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.31
  GitCommit:        e377cd56a71523140ca6ae87e30244719194a521
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    26.1.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0-desktop.1
    Path:     /usr/local/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.0-desktop.2
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.29
    Path:     /usr/local/lib/docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /usr/local/lib/docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.23
    Path:     /usr/local/lib/docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     /usr/local/lib/docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.1.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.8.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-scout
WARNING: Plugin "/usr/local/lib/docker/cli-plugins/docker-scan" is not valid: failed to fetch metadata: fork/exec /usr/local/lib/docker/cli-plugins/docker-scan: no such file or directory

Server:
 Containers: 4
  Running: 0
  Paused: 0
  Stopped: 4
 Images: 4
 Server Version: 26.1.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e377cd56a71523140ca6ae87e30244719194a521
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 5.15.133.1-microsoft-standard-WSL2+
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 14
 Total Memory: 18.55GiB
 Name: docker-desktop
 ID: 25c46d5a-6b55-4f13-aebf-ccef15c98c0b
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///var/run/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

FF4C7E49-D421-4A90-9D9C-999CFD04870A/20240507131108

### Additional Info

My shell is zsh `zsh 5.8.1 (x86_64-ubuntu-linux-gnu)`
OS: Ubuntu 22.04
WSL: version 2
Windows: 11 23H2

Before updating to 4.30.0, I ran `docker completion zsh > .zfunc/_docker` and added `fpath+=~/.zfunc` in `~/.zshrc` as a workaround when the completion was broken in the previous versions.

**Comment by timsu92** [comment]
I'm trying to reinstall Docker Desktop by doing this:
1. Totally remove Docker Desktop by running uninstaller and then delete leftovers, especially `~/.zfunc/__docker`
2. Download and install Docker Desktop
3. Open and quit Docker Desktop
4. Reopen zsh in WSL
5. Type `docker <tab>` and see this error three times: `(eval):1: command not found: __docker`

Only if I run this that completion works:
```sh
# put completion file under this path since I have `fpath+=~/.zfunc`
# set up in my `.zshrc`, so that this workarounds this
docker completion zsh > ~/.zfunc/__docker
```

**Comment by timsu92** [comment]
This problem seems to be fixed in version `4.32.0` or the previous one. Thanks devs!

**Comment by JosephKings7** [comment]
Hi. My case is the next: I just installed Docker Desktop for the first time in Windows 11; Of course, it is the current version of the software and when I tested it and followed the tutorial for beginners, while at the same time updating it, in a period of 2 days WSL and Ubuntu 22.04.3 were installed on the system without having executed these facilities still. The problem is that when I check the installed distros (with wsl --list --verbose) and that should appear in Configuration -> WSL Integration Resources, only Ubuntu appears and nothing else: This Ubuntu 22.04.3 distro does not appear; What can I do about it? Thanks for your help.

**Comment by timsu92** [comment]
Sorry, I don't quite understand your question. Are you asking why you installed Docker Desktop but its distro isn't listed in `wsl -l -v`?

If so, what's your Windows version? Windows Home can only run on the WSL2 backend, while Windows Pro may have other options, IDK.

**Comment by JosephKings7** [comment]
Best regard. I already resolved it. Now I need to know if after having executed all of the following:

![Screenshot 2024-07-25 090144](https://github.com/user-attachments/assets/b4bae7e7-28ec-42d6-9e8d-706313416438)

to start and launch a new Laravel project from scratch on/with Docker Desktop, should I have installed (previously, of course) Php and MySql? I thought that Docker and everything mentioned above installed everything included, since this; 

![image](https://github.com/user-attachments/assets/775d0931-7748-4ef2-a9c6-cb528e8a2c9c)

and it doesn't go from here; & this:

![image](https://github.com/user-attachments/assets/c2a25c01-b338-41d8-bb3a-1c25d81ef885)

happen, without allowing me to execute the ./vendor/bin/sail artisan migrate command to finish the installation of said project. 

Thank you

**Comment by timsu92** [comment]
I guess your question relates to your project's setup, especially your program `sail`. It doesn't look like related to Docker itself nor my title, and I have no idea what's `sail`.
Sorry, I can't help you🥲 Maybe try consulting the project you found?
