### ISSUE TITLE
I can't open docker

### ISSUE THREAD

**Issue by missreyyo** [docker/for-win#14084]
### Description

I can't open docker from the installing. 

### Reproduce

![image](https://github.com/docker/for-win/assets/88316928/bbb2faea-aee5-4719-91e4-694c2b45cde5)

### docker version

```bash
Docker version 26.1.1, build 4cf5afa
Edisyon	Windows 10 Education
Sürüm	22H2
Yüklenme tarihi	‎11.‎04.‎2023
İS derlemesi	19045.4412
Deneyim	Windows Feature Experience Pack 1000.19056.1000.0
```

### docker info

```bash
error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.45/version": open //./pipe/docker_engine: Sistem belirtilen dosyayı bulamıyor.
Client:
 Cloud integration: v1.0.35+desktop.13
 Version:           26.1.1
 API version:       1.45
 Go version:        go1.21.9
 Git commit:        4cf5afa
 Built:             Tue Apr 30 11:48:43 2024
 OS/Arch:           windows/amd64
 Context:           default
```

### Diagnostics ID

E9E75BC9-D6C1-4A76-9E98-667414EF7B84/20240521103620

**Comment by karman-docker** [comment]
Refer to this known issue mentioned in Docker Desktop 4.30 release notes.

"When starting Docker Desktop as a non-admin user, the following error connect ENOENT \\.\pipe\errorReporter might be triggered if the user is not a member of the docker-users group. This can be resolved by adding the user to the docker-users group. Before starting Docker Desktop, make sure to sign out and then sign back in and unregister docker-desktop distribution if that was created, using wsl --unregister docker-desktop."

Hopefully you will be able to resolve it.

**Comment by missreyyo** [comment]
Thanks for it. I solved.
