### ISSUE TITLE
Error on first run: An unexpected error occurred: connect ENOENT \\.\pipe\errorReporter

### ISSUE THREAD

**Issue by nbiancolin** [docker/for-win#14098]
### Description

Clean install of docker on my laptop, no idea why its giving this error.  Turned on WSL and installed docker,  but it seems like the daemon didn't install / cant start? Any assistance would be appreciated, thank you in advance!

### Reproduce

1. Run docker installer
2. Reboot system
3. Attempt to run

### Expected behavior

should start the docker desktop window, instead throws an error

### docker version

```bash
error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.45/version": open //./pipe/docker_engine: The system cannot find the file specified.
Client:
Cloud integration: v1.0.35+desktop.13
Version:           26.1.1
API version:       1.45
Go version:        go1.21.9
Git commit:        4cf5afa
Built:             Tue Apr 30 11:48:43 2024
OS/Arch:           windows/amd64
Context:           default
```

### docker info

```bash
Client:
Version:    26.1.1
Context:    default
Debug Mode: false
Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.0-desktop.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.29
    Path:     C:\Program Files\Docker\cli-plugins\docker-debug.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.23
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.8.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe
 
Server:
ERROR: error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.45/info": open //./pipe/docker_engine: The system cannot find the file specified.
errors pretty printing info
```

### Diagnostics ID

A252FB34-FFE2-41F6-8C07-EC465F52E9DD/20240527150543

**Comment by voonyee** [comment]
Hi, 
Thanks for reporting this. In our release note 4.30.0: https://docs.docker.com/desktop/release-notes/#4300
Known issues -> [For Windows](https://docs.docker.com/desktop/release-notes/#for-windows-2)

> When starting Docker Desktop as a non-admin user, the following error connect ENOENT \\.\pipe\errorReporter might be triggered if the user is not a member of the docker-users group. This can be resolved by adding the user to the docker-users group. Before starting Docker Desktop, make sure to sign out and then sign back in and unregister docker-desktop distribution if that was created, using wsl --unregister docker-desktop.

The errors could happen if you are trying to run Docker Desktop as a non-admin user and you have not added that user to docker-users group (which is created during DD install). So you will have to add the user to the docker-users group and logout from Windows and login back.

You can find the instructions to add the user to docker-users group here: https://docs.docker.com/desktop/install/windows-install (search for docker-users). After that, logout and login (this is Windows host logout/login) are needed for the effect changes to docker-users group.

**Comment by nbiancolin** [comment]
This ended up being the issue! Don't know how I was unable to find the fix. Thank you!

**Comment by ryan81g** [comment]
I added a review. 
Leave the lib folder in this case. It is the final product. We could add a process to build on github, but I don't think that is really necessary or cost effective.

**Comment by hosford42** [comment]
@nbiancolin It would help to generate an error message that communicates this effectively. Glad I stumbled across this GitHub issue early on in my web search for a solution. Others may not be so fortunate.

**Comment by hosford42** [comment]
Also, it turns out Windows Home doesn't have the setting in Computer Management, "Local Users and Groups > Groups > docker-users", claimed by the install instructions you linked to, https://docs.docker.com/desktop/install/windows-install/. For the next person who runs into this, better instructions can be found here: https://superuser.com/a/1588031/2023441.
