### ISSUE TITLE
Docker Desktop 4.30.0 GUI Issue Unable to expand container folders with modified files. 

### ISSUE THREAD

**Issue by net2devcrypto** [docker/for-win#14112]
### Description

When modifying files inside a container, when trying to access the folder again it auto closes preventing access to the files. You'll have to switch tabs log - inspect - bind - files and retry and after many retries it works for that instance then goes back to the issue. 

### Reproduce

Find the video with issue recorded attached to the ticket

https://github.com/docker/for-win/assets/98722289/60ec593e-0c7f-49aa-87cd-2911c45389b3

### Expected behavior

Folders should expand normally when browsing container files regardless of being modified or not.

### docker version

```bash
Server: Docker Desktop 4.30.0 (149282)
 Engine:
  Version:          26.1.1
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.9
  Git commit:       ac2de55
  Built:            Tue Apr 30 11:48:28 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.31
  GitCommit:        e377cd56a71523140ca6ae87e30244719194a521
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    26.1.1
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0-desktop.1
    Path:     /Users/rcardona/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.0-desktop.2
    Path:     /Users/rcardona/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.29
    Path:     /Users/rcardona/.docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /Users/rcardona/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.23
    Path:     /Users/rcardona/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     /Users/rcardona/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.1.0
    Path:     /Users/rcardona/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/rcardona/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.8.0
    Path:     /Users/rcardona/.docker/cli-plugins/docker-scout

Server:
 Containers: 15
  Running: 14
  Paused: 0
  Stopped: 1
 Images: 16
 Server Version: 26.1.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e377cd56a71523140ca6ae87e30244719194a521
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.26-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 7.655GiB
 Name: docker-desktop
 ID: e029fbd6-2b8b-40ba-b838-14ea646a41ec
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///Users/rcardona/Library/Containers/com.docker.docker/Data/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

E701224E-DE01-4AD5-AC94-A94392F4FC33/20240605012815

**Comment by net2devcrypto** [comment]
As info it happens on both Mac and Windows.

**Comment by voonyee** [comment]
hi @net2devcrypto thanks for reporting this. I have tried to modify files inside a container via the below method.

1. Using Docker Desktop UI> Container tab> Go to Files tab> Right-click and click on Edit File.
2. Execute into the container by running the command below to edit the file via "vi".
`$docker exec -it <container_name> sh`

I am running Docker Desktop 4.30.0 on Mac. 

But, I did not experience what you shared in the video. Can you share how you "modifying files inside a container" so that we can reproduce it from our end?

**Comment by DannyRichardsonWG** [comment]
I have the issue too. It seems like the Docker Desktop UI gets confused about the state of the directory being expanded or not. 

I found I can replicate it consistently on our nginx reverse proxy. 

Here's a video


https://github.com/docker/for-win/assets/86000734/4572f026-6661-444a-8798-ddc3265dc187


Steps:

1) Intentionally make a mistake in the config file (putting the X at the end of the line) and save the file using Control+S
2) Restarting the container
3) Quickly undo the mistake and save again.
4) You can see the folder closes and now is unable to be expanded again

There's definitely other triggers for this behaviour but this happens for me consistently. 

Usually I can resolve by going back to the containers menu, closing the Docker Desktop UI and the restarting the service in task bar but this doesn't always work. The Docker UI has to be closed though or the bug remains.

![image](https://github.com/docker/for-win/assets/86000734/3dbfaa49-9e46-4a3a-90d1-bd1f76bfd699)

**Comment by JL00001** [comment]
I been having the same issue. I tried downgrading back to 4.30.0, 4.29.0, and 4.28.0 with no luck on fixing it.

**Comment by net2devcrypto** [comment]
> hi @net2devcrypto thanks for reporting this. I have tried to modify files inside a container via the below method.
> 
>     1. Using Docker Desktop UI> Container tab> Go to Files tab> Right-click and click on Edit File.
> 
>     2. Execute into the container by running the command below to edit the file via "vi".
>        `$docker exec -it <container_name> sh`
> 
> 
> I am running Docker Desktop 4.30.0 on Mac.
> 
> But, I did not experience what you shared in the video. Can you share how you "modifying files inside a container" so that we can reproduce it from our end?

Thank you for your quick response to this issue!
Sure thing, here's the full video recreating the issue.

https://github.com/docker/for-win/assets/98722289/44c25903-75b7-430a-9962-72118f264ab2

**Comment by net2devcrypto** [comment]
This time is Windows, to confirm its happening on both Mac and PC.

**Comment by stephenfuqua** [comment]
## Another reproduction

Someone trying to reproduce this situation might not see it occur on first attempt.

I was able to edit a file 10 minutes ago through the user interface (navigate into directory, right click file, choose Edit). Worked great. Restarted the container.

Needed to edit again - now the UI is stuck, as described above.

Environment: Windows 11, running Docker Desktop v4.30.0.

**Comment by rensrongen** [comment]
I can confirm this is still happening. Restarting DD doesn't fix it.

Environment: Windows 11 running Docker Desktop v4.31.1.

**Comment by harryfinn101** [comment]
I have it as well

Restarting DD doesn't fix it.

Docker Desktop 4.31.1 (153621) - Windows 11

**Comment by ianOsborne** [comment]
I have also been able to reproduce the issue, perhaps this screen shot can be of use?
![image](https://github.com/user-attachments/assets/4b181897-3b36-4a56-bfa9-bf611fd60947)
I don't believe it shows this error normally, but after playing around with trying to start the container with it the folder open, was able to produce it. Not sure if this helps, but hopefully it provides a clue!

**Comment by johannes-isaksson** [comment]
Happens to me too, Windows 11 Pro, DD v4.33.1. It worked normally for a while, then I opened a file for editing and at some point after that this behavior started manifesting. It only affects the folder containing the file I previously opened (which is the /tmp folder). Other folders open fine.

A variant of the workaround suggested in https://github.com/docker/for-win/issues/14204 occasionally works for me: Highlight the tmp folder, hold spacebar, and as the subfolders flash on and off, click on the subfolder I want to open. Sometimes this causes the issue to disappear. Chanting and making sacrifices to the moon gods may also be effective.

**Comment by landism** [comment]
Docker Desktop 4.34.0 contains a fix for this issue.

**Comment by EliasDerHai** [comment]
Great - maybe needs some proper tests so it's guranteed to not break again. Kind of wild imo that the fundamental purpose of the file-tree is just completely unusable for alot of users because of this bug and there's not even an error toast or code...

**Comment by net2devcrypto** [comment]
I can confirm the issue has been resolved. Docker 4.34.1 works great! Thanks Docker Dev's!

**Comment by unseensenpai** [comment]
I was able to access files while container is not running but created. This last patch fixed issue about while running. How about not running containers?

![Image](https://github.com/user-attachments/assets/0c04b364-c9b4-4954-8f7a-f4814f908bdf)
