### ISSUE TITLE
WSL Probleme when trying to start docker it stucks at the loading page and ends with showing an error !!!

### ISSUE THREAD

**Issue by bachriotmane** [docker/for-win#14121]
### Description

The error :

deploying WSL2 distributions
provisioning docker WSL distros: ensuring main distro is deployed: deploying "docker-desktop": importing WSL distro "Échec de la configuration du réseau (networkingMode Nat). Pour désactiver la mise en réseau, définissez «wsl2.networkingMode=None » dans C:\\Users\\Lenovo\\.wslconfig\r\nError code: Wsl/Service/RegisterDistro/CreateVm/ConfigureNetworking/HNS/0x80041002\r\n" output="docker-desktop": exit code: 4294967295: running WSL command wsl.exe C:\WINDOWS\System32\wsl.exe --import docker-desktop <HOME>\AppData\Local\Docker\wsl\main C:\Program Files\Docker\Docker\resources\wsl\wsl-bootstrap.tar --version 2: Échec de la configuration du réseau (networkingMode Nat). Pour désactiver la mise en réseau, définissez «wsl2.networkingMode=None » dans <HOME>\.wslconfig
Error code: Wsl/Service/RegisterDistro/CreateVm/ConfigureNetworking/HNS/0x80041002
: exit status 0xffffffff
checking if isocache exists: CreateFile \\wsl$\docker-desktop-data\isocache\: The network name cannot be found.

I'm triyng from 4 days with this probleme and it does not get solved I tried many things 

- Reinstall docker , Reinstall WSL , Upgrade WSL to version 2 (It does not work so I'm working with WSL version 1), Avive and Discative Hyper-v,Container, Windows Susystem for Linux 

That what I get when I ran the commande WLS -- install :
In CMD ;

C:\Users\Lenovo>WSL --install
Ubuntu est déjà installé.
Lancement de Ubuntu...
root@DESKTOP-OR7CG4G:~#

Please if there is any suggestion but I think that the probleme could be due to some Network Issues !

### Reproduce

docker run

### docker version

```bash
Client : last version of docker
```

### docker info

```bash
Client : I do nt know what to put in this input
```

### Diagnostics ID

1C42AAB6-CAB4-49EF-BEF7-57827E1F80F0/20240608113428

### Additional Info

No

**Comment by jpbriend** [comment]
Hi @bachriotmane ,
> Upgrade WSL to version 2 (It does not work so I'm working with WSL version 1)

This is your main issue: Docker Desktop requires to have WSL2. It can not work using WSL 1 only.
