### ISSUE TITLE
Docker for Windows 17.09.1-ce-win42 will not install.

### ISSUE THREAD

**Issue by lurch83** [docker/for-win#1412]
### Behavior
I have Windows 10 Enterprise Version 10.0.10586 Build 10586 and Docker will not install.

### Information
The error message indicates that I do not have the correct version of Windows 10. Underneath is a partial screen capture that shows the version I have.

![image](https://user-images.githubusercontent.com/2362604/33869138-629cda52-df5b-11e7-8a9a-1524eda290d4.png)

The output of `[System.Environment]::OSVersion.Version` in Powershell is

```
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      10586  0
```

### Steps to reproduce the behavior

  1. Downloaded the latest Stable version of Docker for Windows and attempted to install. Disabled Anti Virus software as well.

**Comment by jasonbivins** [comment]
Hi @lurch83  I'll file an enhancement request to see if we can make the language a little clearer here in line with the new Windows versioning scheme.

Your Windows 10  install is on Build 10586, and will need to be updated to at least build 14393.  If you're not restricted by policy in your environment, running Windows updates usually takes care of it.
