### ISSUE TITLE
win 10 network error

### ISSUE THREAD

**Issue by RobinKamps** [docker/for-win#14130]
### Description

After updating to 4.31.1 an envoy container can not reach / resolve domains which are in the win host file (e.g, local.dev 127.0.0.1).
Resulting in error: ```immediate connect error: Network is unreachable```.
Downgrading to 4.30 resolves the issue.

### Reproduce

-

### docker version

```bash
4.31.1
```

### docker info

```bash
-
```

### Diagnostics ID

-

**Comment by TomHenshall** [comment]
I had a similar issue with my redis instance running on the host PC. The container wasn't able to resolve gateway.docker.internal correctly. Also downgrading to 4.30 resolved this issue

**Comment by akerouanton** [comment]
Thanks for reporting @RobinKamps. Could you add the output of `docker info` to your original message, and provide a working reproducer (smallest possible) please?

**Comment by TomHenshall** [comment]
It sounds a lot like this issue [Issue 7332](https://github.com/docker/for-mac/issues/7332)

**Comment by RobinKamps** [comment]
After installing docker win desktop 4.35.1 and edit a config file, it works as intendend.

Needed to edit `C:\Users\[USERNAME]\AppData\Roaming\Docker\settings-store.json`, set `IPv4Only` to `true` , than restart docker desktop.
