### ISSUE TITLE
Automatic Update Moved Storage Location and Won't let me move back.

### ISSUE THREAD

**Issue by jreed-cartago** [docker/for-win#14149]
### Description

So I started Docker on Windows today and the Desktop said there's an upgrade so as usual I tell it to upgrade and restart. Upon restart I find that ALL of my images and containers are missing. When I first installed Docker I manually moved the data for Docker Desktop to a different partition because the default was in a partition that was small and only for OS related items and not the data from docker. So as I looked through the settings after not finding my images and containers I found that it moved the disk location back to the default and did not take over my original settings.

Next when I attempted to change the directory back to my desired location I'm prevented from doing so as it throws an error. I even emptied the folder by moving all the old data to a different location and it again throws a error and ignores my request to change to the directory.

### Reproduce

1. Update Docker to 4.31.1
2. Find no containers and no images that were there prior to upgrade
3. Look into settings and see that the docker data file is returned to a default directory instead of the one previously configured
4. Attempt to move the directory back and get this error 
![image](https://github.com/docker/for-win/assets/72963764/6eb14117-d261-4c08-85f2-1dc2971f8770)
5. Create a new directory in case the error is because the directory isn't empty, get same error.

### Expected behavior

That the upgrade maintains my configurations, or at least warns me when there are major changes to important configurations so I'm not wasting my work time attempting to correct the problem.

### docker version

```bash
Client:
 Version:           26.1.4
 API version:       1.45
 Go version:        go1.21.11
 Git commit:        5650f9b
 Built:             Wed Jun  5 11:29:54 2024
 OS/Arch:           windows/amd64
 Context:           desktop-linux

Server: Docker Desktop 4.31.1 (153621)
 Engine:
  Version:          26.1.4
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       de5c9cf
  Built:            Wed Jun  5 11:29:22 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.33
  GitCommit:        d2d58213f83a351ca8f528a95fbd145f5654e957
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    26.1.4
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.1-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.1-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.32
    Path:     C:\Program Files\Docker\cli-plugins\docker-debug.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.24
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.2.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.9.3
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 26.1.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d2d58213f83a351ca8f528a95fbd145f5654e957
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.153.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 15.5GiB
 Name: docker-desktop
 ID: 4acde8ca-0553-4937-8198-065c53289da1
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=npipe://\\.\pipe\docker_cli
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

FF3A525D-7391-4AB4-B004-C52D87894150/20240620090207

**Comment by andrea-reale** [comment]
Hi there,

I am sorry for the poor experience with your update. This seems to be an occurrence a known issue #14126 that occurs when the `docker-desktop-data` WSL2 distribution was moved to a different location manually.

Be reassured that unless you have either uninstalled, factory reset Docker Desktop or manually unregistered the `docker-desktop-data` distribution, your data is not loss.

You can install the development build [shared at this link](https://github.com/docker/for-win/issues/14126#issuecomment-2163504585) that will fix the problem.

I hope that helps.

**Comment by jreed-cartago** [comment]
Thank you for the prompt response. Thankfully I didn't do any resets and I can see that my original virtual drive has its last known size. I'll give the dev build a try.

**Comment by jreed-cartago** [comment]
Dev build works great. Thanks for the help.
