### ISSUE TITLE
DockerNAT Network adapter disappeared in 17.09.1-ce-win42 (14687)

### ISSUE THREAD

**Issue by jmeijrink** [docker/for-win#1415]
### Expected behavior
There is a network adapter present containing the term DockerNAT on which the Ports of the containers are exposed. We used the following powershell to identify the NAT IP: 
$dockerNatInterfaces = Get-NetAdapter | Where-Object { $_.Name.Contains("DockerNAT") } | Get-NetIpAddress | Where-Object { $_.AddressFamily -eq "IPv4" }

### Actual behavior
The network adapter is gone.
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
A diagnostic was uploaded with id: 9AA5990B-528F-4928-9E35-DB288D16AD54/2017-12-12_10-14-16

  - host distribution and version (Windows version, build number, etc)
Windows: 10 Enterprise, Version 1709, Build 16299.15
Docker: Version 17.09.1-ce-win42 (14687), Channel: stable, 3176a6

Reproduction
Upgrade from previous version to above mentioned version.

**Comment by ebriney** [comment]
Hi @jmeijrink .
It is supposed to be here, on my machine from a fresh install, I got:
```
> Get-NetAdapter | Where-Object { $_.Name.Contains("DockerNAT") } | Get-NetIpAddress | Where-Object { $_.AddressFamily -eq "IPv4" }


IPAddress         : 10.0.75.1
InterfaceIndex    : 76
InterfaceAlias    : vEthernet (DockerNAT)
AddressFamily     : IPv4
Type              : Unicast
PrefixLength      : 24
PrefixOrigin      : Manual
SuffixOrigin      : Manual
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore
```

**Comment by jmeijrink** [comment]
Hi @ebriney,

We can indeed fix the issue by:
1. Uninstall Docker for Windows
2. Reboot (we performed a Shut down and Power-On)
3. Install Docker for Windows

Without Step 2, the adapter also does not re-appear. Maybe it would also be fixed by a regular restart, but we did not test that.

We've seen this issue on both machines that we upgraded to the new version. On one machine we fixed it with the above, on the second machine we did not apply it yet, but expect it can be fixed in a similar way.

**Comment by ebriney** [comment]
@jmeijrink : Weird, I'll try with an update from 17.09 to check. Did you upgrade your windows to 1709 in between? Some users reported issues with hyper-V related to network.

**Comment by jmeijrink** [comment]
Hi @ebriney, yes we did. Both of us,

**Comment by ironicnet** [comment]
Same problem here: 
Version 17.12.0-ce-win46 (15048).

Diagnostic ID: 3620BF05-00DD-4890-9C3B-B08921B3A9F3/2018-01-30_13-00-23

**Comment by cforce** [comment]
same here. I beg i don't have to reinstal. Why is there no command /pshekk?) to recreate that?

**Comment by LeonardAB** [comment]
I had similar case but it turned out that docker is using different address (not sure why).
To find out, type `docker inspect nat` and see the gateway address. That should be your Docker NAT.
