### ISSUE TITLE
not runing

### ISSUE THREAD

**Issue by derickobro** [docker/for-win#14152]
### Description

not responding

### Reproduce

1

### Expected behavior

not running

### docker version

```bash
4.1.3
```

### docker info

```bash
true
```

### Diagnostics ID

A0CB6DA8-450B-46CC-9851-C957FA8D6820/202406

### Additional Info

NOT RUNING

**Comment by lorenrh** [comment]
Hello there!

We don't have enough information to investigate the issue, so I'm closing this. However, you can try to use the latest Docker Desktop from https://docs.docker.com/desktop/release-notes/
