### ISSUE TITLE
Windows upgrade installer creates dozens of processes when user rights are insufficient

### ISSUE THREAD

**Issue by Hyruu** [docker/for-win#1416]
### Expected behavior
Docker should start only one instance of the LightweightInstaller process, which should send an error message if it fails due to insufficient user rights.

### Actual behavior
Dozens and dozens of LightweightInstaller processes are created before being destroyed silently after ~15s

### Information
Bug tested on Windows 10

### Steps to reproduce the behavior
1. Attempt to upgrade Docker while providing a non-admin account
2. No failure message appear, but dozens of LightweightInstaller processes are being created and visible in the Task Manager

**Comment by jpblanton** [comment]
I had the same issue, except instead of deleting themselves they simply sat and ate up all of my memory.
