### ISSUE TITLE
No /etc/hostname on LCOW using php:5.5-fpm

### ISSUE THREAD

**Issue by jorrit** [docker/for-win#1418]
### Expected behavior

(LCOW disabled)

```
C:\...\> docker run --rm -ti php:5.5-fpm cat /etc/hostname
05e8b54a1ddd
C:\...\>
```

### Actual behavior

(LCOW enabled)

```
C:\...\> docker run --rm -ti php:5.5-fpm cat /etc/hostname
C:\...\>
```

The image seems to matter, `debian:jessie` doesn't have this problem. The `php:5.5-fpm` is quite old, but I think it may interest the Docker for Windows developers that there is a difference between LCOW off and on.

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
`FAD55326-F220-44BC-AE18-8184F4B4B1E9/2017-12-12_13-26-08`
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)
Windows 10 1709
Server Version: 17.11.0-ce

**Comment by thaJeztah** [comment]
ping @pradipd PTAL

**Comment by pradipd** [comment]
@djs55 Can you triage?
