### ISSUE TITLE
Thanks for the latest update!

### ISSUE THREAD

**Issue by GinoPane** [docker/for-win#1420]
Just wanted to say, that the latest update was great (so far). Docker now starts from the first time (it failed to start previously and worked fine only after the first failure), and the start is very fast (Win10).

**Comment by jasonbivins** [comment]
Hi @GinoPane   Thanks for the feedback!

**Comment by GinoPane** [comment]
Unfortunately after a few days of working without failures, it started to fail to start again. It starts only after second attempt.
