### ISSUE TITLE
Cannot start Docker v4.33.0 on Windows 10 due to this error: "deploying WSL2 distributions... ensuring data disk is available"

### ISSUE THREAD

**Issue by PhuongNQK** [docker/for-win#14228]
### Description
Since 4.31.0, Docker Desktop seems to not working properly. It is very hard to start it because it just stops immediately. Here is the error:

![docker-desktop-can't-start](https://github.com/user-attachments/assets/b23980d2-90eb-4aa6-bd18-175eac66a5f9)

### Reproduce

Start Docker Desktop and get the error.

```
deploying WSL2 distributions
ensuring data disk is available: exit code: 4294967295: running WSL command wsl.exe C:\WINDOWS\System32\wsl.exe --mount --bare --vhd E:\Docker\DockerDesktopWSL_02\DockerDesktopWSL\disk\docker_data.vhdx: Failed to attach disk '\\?\E:\Docker\DockerDesktopWSL_02\DockerDesktopWSL\disk\docker_data.vhdx' to WSL2: Access is denied. 
Error code: Wsl/Service/AttachDisk/MountVhd/HCS/E_ACCESSDENIED
: exit status 0xffffffff
checking if isocache exists: CreateFile \\wsl$\docker-desktop-data\isocache\: The network name cannot be found.
```

### Expected behavior

Docker Desktop should start and work.

### docker version

```bash
Client:
 Version:           27.1.1
 API version:       1.46
 Go version:        go1.21.12
 Git commit:        6312585
 Built:             Tue Jul 23 19:57:57 2024
 OS/Arch:           windows/amd64
 Context:           desktop-linux
```

### docker info

```bash
Client:
 Version:    27.1.1
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.1-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.1-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.34
    Path:     C:\Program Files\Docker\cli-plugins\docker-debug.exe
  desktop: Docker Desktop commands (Alpha) (Docker Inc.)
    Version:  v0.0.14
    Path:     C:\Program Files\Docker\cli-plugins\docker-desktop.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.25
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.3.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.11.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
ERROR: error during connect: Get "http://%2F%2F.%2Fpipe%2FdockerDesktopLinuxEngine/v1.46/info": open //./pipe/dockerDesktopLinuxEngine: The system cannot find the file specified.
errors pretty printing info
```

### Diagnostics ID

D6A7276A-C34B-46C1-B850-DD09EF3EB246/20240730082144

**Comment by CafeSua29** [comment]
did u find any solution ?

**Comment by PhuongNQK** [comment]
Hi @CafeSua29, yes, I found the cause and forgot to update this. 

Cause:
Somehow each time Windows restarts, permissions on the data disk file (i.e. `E:\Docker\DockerDesktopWSL_02\DockerDesktopWSL\disk\docker_data.vhdx` in my case - see the logs in my description above) are reset to those for a default user. Even if I start Docker using Administrator privileges, the issue still occurs. 

Fix:
Give the current user (or any user that you want to use) Full Control on the data disk file. Here is how you can do that: https://v2cloud.com/tutorials/how-to-change-folder-permissions-on-windows-2016.

This issue is closed for me.

**Comment by Jatinn517** [comment]
> did u find any solution ?

For me it worked after I run "wsl --update" command on powershell

**Comment by ozgurkk** [comment]
> > did u find any solution ?
> 
> For me it worked after I run "wsl --update" command on powershell

The solution worked for me on a Windows 11 Pro with a fresh install of 4.35.1 (173168).

**Comment by omnio-thomas-kelly** [comment]
> > did u find any solution ?
> 
> For me it worked after I run "wsl --update" command on powershell

Yep, after some other attempt it turned out wsl --update fixed it

**Comment by 8ternity** [comment]
I use Chat GPT to see the eroor, Chat GPT has recommend to try this fix and worked 👍 

Run CMD in Administrator Rights;

> wsl --list --verbose
If you see version, OK go to next step 👍 

wsl --set-default-version 2
and
wsl --update

Close Docker, Restart The APP, now mine has worked well after this.

**Comment by thisaraCX** [comment]
> > did u find any solution ?
> 
> For me it worked after I run "wsl --update" command on powershell

I had to restart after this command but this worked.

**Comment by Hassan2deeb** [comment]
i have same issue:
i run 
`wsl --update`
the out:
`Checking for updates...
No updates are available.
Kernel version: 5.10.102.1`
and not working,

i downloaded the wsl using:
`wsl --install -d ubuntu`   first time and install it, then i downloaded ubuntu and ubuntu for windows from microsoft store,
and same problem

**Comment by Hassan2deeb** [comment]
> > did u find any solution ?
> 
> For me it worked after I run "wsl --update" command on powershell

what was the kernal version?
what is the latest kernal version?
i want to be sure that the command is updating succecfully

**Comment by sanset** [comment]
> > did u find any solution ?
> 
> For me it worked after I run "wsl --update" command on powershell

This worked for me as well docker v4.38

**Comment by Zeddddd** [comment]
Turn off Hyper-V and done

**Comment by samhatre-fadv** [comment]
> > > did u find any solution ?
> > 
> > 
> > For me it worked after I run "wsl --update" command on powershell
> 
> The solution worked for me on a Windows 11 Pro with a fresh install of 4.35.1 (173168).

it worked for me, this is the easiest solution

**Comment by 8ternity** [comment]
You Funny, Hyper-V is required for any virtualization.

Like mentioned in previous answer, its fixed.

**Comment by benjamindassonville** [comment]
> Hi [@CafeSua29](https://github.com/CafeSua29), yes, I found the cause and forgot to update this.
> 
> Cause: Somehow each time Windows restarts, permissions on the data disk file (i.e. `E:\Docker\DockerDesktopWSL_02\DockerDesktopWSL\disk\docker_data.vhdx` in my case - see the logs in my description above) are reset to those for a default user. Even if I start Docker using Administrator privileges, the issue still occurs.
> 
> Fix: Give the current user (or any user that you want to use) Full Control on the data disk file. Here is how you can do that: https://v2cloud.com/tutorials/how-to-change-folder-permissions-on-windows-2016.
> 
> This issue is closed for me.

this work for me ty

**Comment by niteshSutradhaR** [comment]
> Hi [@CafeSua29](https://github.com/CafeSua29), yes, I found the cause and forgot to update this.
> 
> Cause: Somehow each time Windows restarts, permissions on the data disk file (i.e. `E:\Docker\DockerDesktopWSL_02\DockerDesktopWSL\disk\docker_data.vhdx` in my case - see the logs in my description above) are reset to those for a default user. Even if I start Docker using Administrator privileges, the issue still occurs.
> 
> Fix: Give the current user (or any user that you want to use) Full Control on the data disk file. Here is how you can do that: https://v2cloud.com/tutorials/how-to-change-folder-permissions-on-windows-2016.
> 
> This issue is closed for me.

--- Thank you for figuring out the core issue

**Comment by DJentBoiiii** [comment]
> Hi [@CafeSua29](https://github.com/CafeSua29), yes, I found the cause and forgot to update this.
> 
> Cause: Somehow each time Windows restarts, permissions on the data disk file (i.e. `E:\Docker\DockerDesktopWSL_02\DockerDesktopWSL\disk\docker_data.vhdx` in my case - see the logs in my description above) are reset to those for a default user. Even if I start Docker using Administrator privileges, the issue still occurs.
> 
> Fix: Give the current user (or any user that you want to use) Full Control on the data disk file. Here is how you can do that: https://v2cloud.com/tutorials/how-to-change-folder-permissions-on-windows-2016.
> 
> This issue is closed for me.

Ur a lifesaver. Thx
