### ISSUE TITLE
Cannot connect to exposed ports after upgrade

### ISSUE THREAD

**Issue by ori-n** [docker/for-win#1423]
Hi,

I upgraded today docker version and from the upgrade I cannot connect to exposed ports.
I'm still not sure if it is related to the upgrade or to other issues in my windows machine.
Below are the docker version details.

Thanks,
Ori

Version: 17.09.1-ce-win42 (14687)
Channel: stable
Sha1: 3176a6af014bdb1346ed31371a717e87e656e2b7
Started on: 2017/12/13 14:27:15.816
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1607
Build: 14393
BuildLabName: 14393.1770.amd64fre.rs1_release.170917-1700

**Comment by mattmeye** [comment]
+1

Diagnostic ID: D2B39E64-75F7-49B9-8D70-B5D6692D137B/2018-01-10_12-44-18
