### ISSUE TITLE
Does not exist docker-desktop-data

### ISSUE THREAD

**Issue by mofanfan** [docker/for-win#14264]
### Description

After installing Docker Desktop 4.33.0 or 4.33.1, I found that the docker-desktop-data distribution was missing using the wsl -l -v command. Is this a bug? I also tried installing version 4.32 and everything worked fine.

### Reproduce

1. Uninstall the old version
2. Install version 4.33.0 or higher
3. Start Docker Desktop
4. Open PowerShell and enter: wsl -l -v

### docker version

```bash
none
```

### docker info

```bash
none
```

### Diagnostics ID

none

**Comment by pinkfloydx33** [comment]
This is the new behavior for `4.30` and later:

> Installations of Docker Desktop version 4.30 and later no longer rely on the docker-desktop-data distribution; instead Docker Desktop creates and manages its own virtual hard disk (VHDX) for storage. (note, however, that Docker Desktop keeps using the docker-desktop-data distribution if it was already created by an earlier version of the software).

[Source](https://docs.docker.com/desktop/wsl/best-practices/?uuid=B47127DF-0E16-4933-A684-D10BB77DA33C)

That's assuming you've done a new installation. I'm just wondering if there's a way to migrate from docker-desktop-data to the new built-in VHDX management without uninstalling  / losing things

**Comment by mofanfan** [comment]
> This is the new behavior for `4.30` and later:
> 
> > Installations of Docker Desktop version 4.30 and later no longer rely on the docker-desktop-data distribution; instead Docker Desktop creates and manages its own virtual hard disk (VHDX) for storage. (note, however, that Docker Desktop keeps using the docker-desktop-data distribution if it was already created by an earlier version of the software).
> 
> [Source](https://docs.docker.com/desktop/wsl/best-practices/?uuid=B47127DF-0E16-4933-A684-D10BB77DA33C)
> 
> That's assuming you've done a new installation. I'm just wondering if there's a way to migrate from docker-desktop-data to the new built-in VHDX management without uninstalling / losing things

Thanks for all your help

**Comment by chekkan** [comment]
The volumes are now stored at the path `/mnt/docker-desktop-disk/data/docker/volumes/<volume_name>/_data` in the `docker-desktop` distribution if you are using the WSL 2 integration.

```
 wsl -d docker-desktop ls /mnt/docker-desktop-disk/data/docker/volumes/<volume_name>/_data
```

**Comment by oktesting** [comment]
> This is the new behavior for `4.30` and later:
> 
> > Installations of Docker Desktop version 4.30 and later no longer rely on the docker-desktop-data distribution; instead Docker Desktop creates and manages its own virtual hard disk (VHDX) for storage. (note, however, that Docker Desktop keeps using the docker-desktop-data distribution if it was already created by an earlier version of the software).
> 
> [Source](https://docs.docker.com/desktop/wsl/best-practices/?uuid=B47127DF-0E16-4933-A684-D10BB77DA33C)
> 
> That's assuming you've done a new installation. I'm just wondering if there's a way to migrate from docker-desktop-data to the new built-in VHDX management without uninstalling / losing things

I am wondering the same thing. Is there no actual official docs about migrating this? :((

**Comment by vinayduba** [comment]
Helpful

**Comment by PureJoyMind** [comment]
> The volumes are now stored at the path `/mnt/docker-desktop-disk/data/docker/volumes/<volume_name>/_data` in the `docker-desktop` distribution if you are using the WSL 2 integration.
> 
> ```
>  wsl -d docker-desktop ls /mnt/docker-desktop-disk/data/docker/volumes/<volume_name>/_data
> ```

can I export docker-destop and import in another location without breaking docker? I did so with debian and all was fine. I'm trying to move all my wsl stuff to another drive rather than C.

**Comment by awilkins** [comment]
Finding this annoying because I'm doing Elasticsearch exercises that ingest the container logs and it's now much harder to access them from a normal WSL distro or even from Windows because this VHDX isn't mounted anywhere visible outside of the `docker-desktop` distro.
