### ISSUE TITLE
Why is the Docker release for windows named stuff like win40, win41, win42?

### ISSUE THREAD

**Issue by LordMike** [docker/for-win#1426]
It seems really odd to me that the releases are targeting win40, win41 etc. Is this an error in the build script that just increments stuff?

I would expect to install on win32. Just like any other piece of software...

Bonus: I can't find the releases on google by their build and version numbers. It's almost like the only place I learn of their existence, is through the update notifications.

**Comment by friism** [comment]
This is the build Docker release build number, it's not related to `win32`.
