### ISSUE TITLE
Swarm stack having issues reading external networks from compose file

### ISSUE THREAD

**Issue by gjonespf** [docker/for-win#1427]
### Expected behavior
Docker stack should be deployed

### Actual behavior
Stack deploy gives error message:
json: cannot unmarshal array into Go value of type types.NetworkResource

```
docker stack deploy --compose-file docker-compose.yml build
json: cannot unmarshal array into Go value of type types.NetworkResource
```

### Information

Docker details:
Version: 17.12.0-ce-rc2-win41 (14746)
Channel: edge
Sha1: 0f8a7d28d0782c2f51fe684ba18ed9beb4ff6a48

Host:
OS: Windows 10 Pro
Edition: Professional
Id: 1607
Build: 14393
BuildLabName: 14393.1794.amd64fre.rs1_release.171008-1615

Had thought this may be a revision to compose format, but I don't see any changes here:
https://docs.docker.com/compose/compose-file/#external-1

Due to the fact no previous installers exist, I can't even revert to work around this bug.  Reverting to stable and redeploying the stack works successfully first time.

### Steps to reproduce the behavior

Simple stack compose and setup here:
https://gist.github.com/gjonespf/c244afb2daad50b56a7d7aad485b09e4

  1. Grab stack compose and setup script
  2. Run setup.sh

**Comment by clemenko** [comment]
This issue shows up in Docker for Mac as well. 
Docker version 17.12.0-ce-rc2, build f9cde63 (Edge Channel)
