### ISSUE TITLE
vpnkit.exe dies due to whitespace in username

### ISSUE THREAD

**Issue by oafx** [docker/for-win#1429]
Hi, i don't know much about how docker on windows internally works so I don't even know if this is the right place to submit this issue. If there is additional information required I'll do my best to help.

I've upgraded to the latest version of docker for windows today and since then I noticed that docker isn't able to connect to the internet / pull images from the registry. Digging around a bit in the docker logs it seems like docker makes a call to `vpnkit.exe` which fails because my username contains first and lastname seperated by a whitespace.

### Expected behavior
Docker pulling images

### Actual behavior
```
Step 1/9 : FROM python:alpine3.6
ERROR: Service 'mycontainer' failed to build: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:55852->[::1]:53: read: connection refused
```

### Information

Log:
```
[18:07:42.418][VpnKit         ][Info   ] vpnkit.exe: too many arguments, don't know what to do with
[18:07:42.418][VpnKit         ][Info   ]             `mylastname\AppData\Roaming\Docker\resolv.conf'
[18:07:42.418][VpnKit         ][Info   ] Usage: vpnkit.exe [OPTION]... 
[18:07:42.418][VpnKit         ][Info   ] Try `vpnkit.exe --help' for more information.
[18:07:42.426][VpnKit         ][Error  ] Process died
```

### Steps to reproduce the behavior
I suppose..
  1. create a user with a whitespace in the username.. e.g. 'user name'
  2. try to build an image

**Comment by oafx** [comment]
upon further investigation of my problems it appears that this only happens if i have switched LCOW on and off before

**Comment by dmsean** [comment]
I'm experiencing this as well in 17.11 and 17.12

**Comment by oafx** [comment]
As further note: I wasn't able to work around this by simply switching to stable or reinstalling. It appears to be (at least in my case) necessary to uninstall and install an older docker version without LCOW i.e. 17.09.0-ce-win32 and then upgrade again with LCOW disabled

**Comment by rn** [comment]
this should be fixed. closing
