### ISSUE TITLE
17.12.0-ce-rc2-win41 doesn't install on Windows 10 Enterprise version 10586

### ISSUE THREAD

**Issue by davidgaulin** [docker/for-win#1430]
### Expected behavior

Docker should install on Windows 10 Enterprise version 10586

### Actual behavior

Docker doesn't install and returns an error message saying "Docker for Windows requires Windows 10 Pro or Enterprise version 10586, or Windows server 2016 RTM to run"

### Information

Usefull information from my windows box:
PS> Get-WmiObject Win32_OperatingSystem | fl *
...
PSComputerName                            : DEV-W10VAMI08
Status                                    : OK
Name                                      : Microsoft Windows 10 .
..
BuildNumber                               : 10586
BuildType                                 : Multiprocessor Free
Caption                                   : Microsoft Windows 10 Enterprise
CodeSet                                   : 1252
...
OSArchitecture                            : 64-bit
OSLanguage                                : 1033
OSProductSuite                            : 256
OSType                                    : 18
ProductType                               : 1
...
Version                                   : 10.0.10586
WindowsDirectory                          : C:\WINDOWS
Scope                                     : System.Management.ManagementScope
...

### Steps to reproduce the behavior

  1. Start installer

**Comment by friism** [comment]
This is a dupe, please see my response here: https://github.com/docker/for-win/issues/1421#issuecomment-351444793
