### ISSUE TITLE
Upgrade gets stuck in "Stopping VM and preparing for update" state

### ISSUE THREAD

**Issue by OriYosefiMSFT** [docker/for-win#1431]
### Expected behavior
Update to 17.11.0-ce-win40 succeeds
### Actual behavior
Update starts but gets stuck in "stopping VM and preparing for update" stage. 
Closing windows doesn't work
restarting and trying again doesn't work.
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)
![image](https://user-images.githubusercontent.com/20298239/34016126-9e9aec58-e0d5-11e7-8a0f-5c734ceb99c0.png)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jhaagmans** [comment]
I have had the exact same issue for about a month now. Docker will not start, update or allow uninstalling. I have tried killing all running Docker processes and running the installer from scratch, but no cigar. Were you able to fix this properly or should I consider some kind of manual uninstall?

**Comment by blackspy21** [comment]
Same issue when trying to upgrade to 2.1.0.2.

Is this issue getting any priority at all?

**Comment by fahimtran** [comment]
I'm not sure how detailed my solution has to be, but it seems like when I went to Program and Features in Windows Settings and turned on Hyper-V, it fixed this issue.

**Comment by ianmaddox** [comment]
Same problem here trying to go from 2.1.0.2 to 2.1.0.5. Initially installed with choco, so I suspect something nonstandard happened there, but it looks like people have been experiencing this issue off and on since 2016 so perhaps it's deeper.

**Comment by ianmaddox** [comment]
I made a bunch of changes that eventually worked after several false steps and reboots. The installer bundled with 2.1.0.2 and 2.1.0.5 managed to wreck my system to the point where I had to do a snapshot restore, so I do not recommend a traditional uninstall.

The following steps worked for me:
1. Turn on the following Windows Features:
   Hyper-V
   Containers
   Windows Hypervisor Platform
1. Open Hyper-V Manager and stop any Docker instances you see
1. Download and install the latest Docker Desktop
   I used 2.2.0.3 (42716)
1. When prompted, allow the installer to remove the old version

**Comment by ant-1** [comment]
Same problem for me.
Since 2.2 version, update and uninstall are failing.

Looks like udpate and uninstall requires to stop/remove VM while they can't

Contacted slack channel #docker-desktop-win, didn't get no answer

/remove-lifecycle stale

**Comment by GertjanMonkeyProof** [comment]
Just got this when trying to upgrade from 2.2.0.3 to 2.3.0.3.
Above fixes did nothing to resolve the issue.

**Comment by Crono1981** [comment]
Just happened while updating to 2.3.0.4

**Comment by stanspotts** [comment]
Yup, 2.3.0.4 and same results on two different laptops.

**Comment by AivarasAukselis** [comment]
I have the same on 2.3.0.5

**Comment by GeertHuls** [comment]
Same happend on my machine after running docker on WSL2.

Before updating, switch back to Hyper-V, then run the update and everything works fine. Must be a bug in the installer I guess...

**Comment by JanairAlves** [comment]
Para mim resolveu, executando o comando `Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All` no PowerShell como admin, logo após reiniciando o W10 e atualizando o Docker.

https://docs.microsoft.com/pt-br/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v

**Comment by Amemiyaa** [comment]
The following steps worked for me: Disabling the VMM in BIOS, save and restart

**Comment by doijao** [comment]
Assuming your Docker  update window is still running, Follow the instruction below:

1. Click Start Windows
2. Type Hyper-V Manager
3. Open Hyper-V Manager
4. On the left window pane, select your computer name
5. In the right window pane (Actions), click the Stop Service, then click Turn off
6. Then Start Service again
7. You should see DockerDesktopVM tab
8. Under DockerDesktopVM Click the Turn Off
9. Go back to your docker update window and click refresh

Your docker update should continue installing
