### ISSUE TITLE
Docker Desktop uninstaller is blank white screen

### ISSUE THREAD

**Issue by pcgeek86** [docker/for-win#14324]
### Description

I can't run Docker, so I need to uninstall it and re-install it. It doesn't start up when I try to launch it.

So now I am trying to uninstall Docker Desktop from my system, and all I get is a white screen. I can't see any controls / buttons to continue the uninstall process.

![image](https://github.com/user-attachments/assets/ff6a38ee-f0d9-4f4c-b5e3-f0db81108eaa)

### Reproduce

1. Open `appwiz.cpl`
2. Select **Docker Desktop** to uninstall
3. Confirm UAC prompt
4. Observe white window pop up

### Expected behavior

Docker Desktop uninstaller should show controls to manage uninstallation

### docker version

```bash
4.33.1 (161083)
```

### docker info

```bash
4.33.1 (161083)
Windows 11
```

### Diagnostics ID

I can't generate this

### Additional Info

I can't run Docker Desktop to get any additional info

**Comment by pcgeek86** [comment]
I fixed the issue and posted here: https://forums.docker.com/t/cannot-uninstall-docker-for-windows/15661/52

![image](https://github.com/user-attachments/assets/9745b51a-a8e5-4595-aad0-53e14fd31f89)

I had a similar problem, where the uninstaller screen went completely white. There was no button to continue the uninstaller process.

I had a major Intel wifi driver problem, that forced me to use the System Restore function in Windows 11 - yes, one of those rare times where System Restore is absolutely necessary. After doing the System Restore, my wifi driver was fixed, but Docker Desktop was completely broken. It wouldn’t launch.

To fix this, I deleted the `c:\Program Files\Docker` directory and deleted the `HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall\Docker Desktop` registry key.

That allowed me to run the latest Docker Desktop installer and successfully install it from scratch.

After that, I had to unregister the old WSL distributions according to [this link](https://github.com/docker/for-win/issues/14034).

```
wsl --unregister docker-desktop
wsl --unregister docker-desktop-data
Then I restarted Docker Desktop, and my Docker Engine is back up and running!
```

**Comment by gabrieljablonski** [comment]
@pcgeek86 thanks for posting it!

Docker just made me lose about a day's worth of work troubleshooting my WSL environment, after Docker completely bricked it when upgrading to latest version. Thankfully I didn't lose any data.

Curiously, my solution was also to use System Restore to bring WSL back to life, but then it was Docker that stopped working just as it did for you.

Following your steps fixed it, so thanks for sharing.

**Comment by pcgeek86** [comment]
@gabrieljablonski love to hear it, brother!! That's why I try to make sure I post solutions when I figure them out. I'm glad you found this. 😊
