### ISSUE TITLE
Unable to run -> docker run hello-world

### ISSUE THREAD

**Issue by hemantshelar** [docker/for-win#1432]
### Expected behavior

'**docker run hello-world**' should download image 'hello-world:latest', if not found locally

### Actual behavior
Getting below error message

C:\WINDOWS\system32>docker run hello-world
Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.

### Information
  - Diagnostic ID from "Diagnose & Feedback" in the menu.
       id: EB1D68EE-4199-45BC-BA43-AD68A58159FE/2017-12-15_09-34-23 
  - host distribution and version (Windows version, build number, etc)
C:\WINDOWS\system32>docker version
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:22:26 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:28:28 2017
 OS/Arch:      linux/amd64
 Experimental: true
  
OS: Windows 10 Pro ( Version 1709 - OS Build 16299.125 )

Hyper-V Manager
Microsoft Corporation
Version: 10.0.16299.15

### Steps to reproduce the behavior

  1. Open command prompt
  2. type : docker run hello-world

**Comment by hemantshelar** [comment]
Found solution in [this thread](https://github.com/moby/moby/issues/22635).

![capture](https://user-images.githubusercontent.com/21121167/34019896-2cb34b66-e185-11e7-9443-e5badf4f1573.PNG)

Thanks.

**Comment by hemantshelar** [comment]
Issue was with configuration.

**Comment by sl5net** [comment]
@hemantshelar what you changed there?
you set a static configuration? was it dynamic bevore? please ecplain your solution

**Comment by girimedi** [comment]
@sl5net. It was static upon installation on mine. I just had to add the DNS (it was empty after installing docker) and it worked.
