### ISSUE TITLE
Container can not be started on Windows Server 1709 VM

### ISSUE THREAD

**Issue by Cybage2011** [docker/for-win#1433]
### Expected behavior
 With Windows Server 1709, i should be able to create and run containers.
### Actual behavior
I am able to create the containers but not able to run the containers. It hang for indefinite time.
### Information

- important info
   I am trying all this on VM of Windows Server 1709. The base machine is Windows Server 2016 with all 
  latest updates.

- host machine details - 
             Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
            Operating System: Windows Server Standard
             OSType: windows
              Architecture: x86_64
              CPUs: 1
             Total Memory: 8GiB

 - The output by executing WindowsContainerNetworking-LoggingAndCleanupAide.ps1 without any parameter is uploaded at [PreCleanupState_PMGDDPGX.zip](https://github.com/docker/for-win/files/1561611/PreCleanupState_PMGDDPGX.zip)
 -The output by executing Invoke-WebRequest https://aka.ms/Debug-ContainerHost.ps1 -UseBasicParsing | Invoke-Expression is uploaded at
[DebugContainerHost.txt](https://github.com/docker/for-win/files/1561651/DebugContainerHost.txt)
- The log generated by above command is uploaded at
[logs_20171214-211052.zip](https://github.com/docker/for-win/files/1561657/logs_20171214-211052.zip)

### Steps to reproduce the behavior

  1. Pull microsoft/aspnetcore:2.0.0-nanoserver:1709
  2. use the Docker Run command to start the container.
  3. new container is created but does not start. the process is hangs.
  4. terminate the process and see the created containers by using docker ps -a command.
  5. We can see the created contaienr.

**Comment by jasonbivins** [comment]
Hi @Cybage2011 
I've seen similar behaviour before with Powershell, and had better results using CMD since it displays differently, can you try again in CMD to see if you get a more helpful message?

**Comment by Cybage2011** [comment]
HI @jasonbivins 

Tried with CMD, no difference in output. Do you need any other information?

**Comment by alefesta** [comment]
couple of questions:
 is nested virtualization enabled? (https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/nested-virtualization)
also do you have the same behavior with windowsservercore images?

**Comment by Cybage2011** [comment]
Yes, as per some blog i have enabled nested virtualization by running following two Powershell commands. WS1709 is the name of my VM.

Set-VMProcessor -VMName WS1709 -ExposeVirtualizationExtensions $true
Get-VMNetworkAdapter -VMName WS1709 | Set-VMNetworkAdapter -MacAddressSpoofing On

I also tried with microsoft/windowsservercore image. As expected, it gives error "The operating system of the container does not match the operating system of the host".
