### ISSUE TITLE
Unable to start Docker Engine: no sd* disk in /sys/block with wwid ...

### ISSUE THREAD

**Issue by Squamto** [docker/for-win#14345]
### Description

I had Docker Desktop installed previously and wanted to install it again, but after the installation it does not start and prints the following wsl error:
```
error spotted in wslbootstrap log: "[2024-10-03T13:02:42.148308300Z][wsl-bootstrap][F] no sd* disk in /sys/block with wwid ending by c217422c1c39a382f072c2f9: file does not exist"
```

I already tried reinstalling it a few weeks later, including the wls distro, but nothing changed.
During the install a few weeks ago it spammed me with Admin requests and would not stop until I denied it. But today it did not do that.

### Reproduce

Install Docker Desktop and run it.

### docker version

```bash
Client:
 Version:           27.2.0
 API version:       1.47
 Go version:        go1.21.13
 Git commit:        3ab4256
 Built:             Tue Aug 27 14:17:17 2024
 OS/Arch:           windows/amd64
 Context:           desktop-linux
error during connect: Get "http://%2F%2F.%2Fpipe%2FdockerDesktopLinuxEngine/v1.47/version": EOF
```

### docker info

```bash
Client:
 Version:    27.2.0
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.2-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.2-desktop.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.34
    Path:     C:\Program Files\Docker\cli-plugins\docker-debug.exe
  desktop: Docker Desktop commands (Alpha) (Docker Inc.)
    Version:  v0.0.15
    Path:     C:\Program Files\Docker\cli-plugins\docker-desktop.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.25
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.3.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.13.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
ERROR: error during connect: Get "http://%2F%2F.%2Fpipe%2FdockerDesktopLinuxEngine/v1.47/info": open //./pipe/dockerDesktopLinuxEngine: The system cannot find the file specified.
errors pretty printing info
```

### Diagnostics ID

B1A17C9A-C68A-4FC0-BB28-C7CE0FD5C809/20241003125850

**Comment by andrea-reale** [comment]
Hi @Squamto, I am sorry to hear that Docker Desktop is not working for you.

From your diagnostics I see that you are running your WSL2 using a relatively old (presumably custom) build of the linux kernel (Linux version 4.19.84-microsoft-custom+). 

Could you please confirm whether that's the case and verify if you still face the same issue when using the default WSL2 kernel? Custom kernels are normally configured using the `.wslconfig` file (see [official docs](https://learn.microsoft.com/en-us/windows/wsl/wsl-config)). 

(I recommend to quit Docker Desktop and to perform a `wsl --shutdown` after updating the kernel config)

**Comment by Squamto** [comment]
Yes, that is probably it. I completely forgot about that. I am currently unable to try it, but it sounds promising.

**Comment by Antracen** [comment]
Did you resolve this? I have the same issue and haven’t seen anyone else having it.

**Comment by bamancio-futura** [comment]
I got this error and after reading @andrea-reale 's comment my solution was to update my wsl with `wsl --update`.  It worked as expected after the update.

**Comment by Squamto** [comment]
I deleted the `.wslconfig` in my home directory and that resolved the issue.
