### ISSUE TITLE
Unable to run containers in Windows arm64

### ISSUE THREAD

**Issue by AndriusAndrulevicius** [docker/for-win#14368]
### Description

After installing the latest Docker Desktop (x86_64) tried running a container (hello-world) to test if everything works, but it fails with an error: "docker : docker: Error response from daemon: hcs::CreateComputeSystem 224a238e7736d678f2abfa2096c7619f7b7e8edb2f568791bca7b38077f5a9ed: hcsshim: timeout waiting for notification."

### Reproduce

Download and install latest Docker Desktop (x86_64).
Start Docker Desktop
Switch to windows containers using terminal "& $Env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchDaemon".
Following https://docs.docker.com/docker-hub/quickstart/ pulled and tried running a container (docker run hello-world) - got the error.
Tried running a container with Hyper-V isolation (docker run --isolation hyperv hello-world) - same error.

### docker version

Client:
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:42:27 2024
 OS/Arch:           windows/amd64
 Context:           desktop-windows

Server: Docker Desktop 4.34.3 (170107)
 Engine:
  Version:          27.2.0
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.21.13
  Git commit:       3ab5c7d
  Built:            Tue Aug 27 14:16:14 2024
  OS/Arch:          windows/amd64
  Experimental:     false

### docker info

Client:
 Version:    27.3.1
 Context:    desktop-windows
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.2-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.2-desktop.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.34
    Path:     C:\Program Files\Docker\cli-plugins\docker-debug.exe
  desktop: Docker Desktop commands (Alpha) (Docker Inc.)
    Version:  v0.0.15
    Path:     C:\Program Files\Docker\cli-plugins\docker-desktop.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.25
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.3.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.13.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 3
  Running: 0
  Paused: 0
  Stopped: 3
 Images: 1
 Server Version: 27.2.0
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 26100 (26100.1.arm64fre.ge_release.240331-1435)
 Operating System: Microsoft Windows Version 24H2 (OS Build 26100.2033)
 OSType: windows
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.57GiB
 Name: Surface7
 ID: 83fb4f2e-6f00-4379-9765-1a8de76d1fc9
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: false
 Labels:
  com.docker.desktop.address=npipe://\\.\pipe\docker_cli
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

### Diagnostics ID

10601BD3-C2B5-4E1F-9D69-07FEDA37197F/20241016202239

### Additional Info

Changing settings to use WSL 2 didn't help

**Comment by vvoland** [comment]
Running an x86 Docker Desktop on arm64 won't do the trick here because Windows Containers are not supported on Windows for ARM64. There's nothing we can do on the Docker side without Windows support.
