### ISSUE TITLE
Docker won't start while Folding@Home or BOINC is Running

### ISSUE THREAD

**Issue by RoBorg** [docker/for-win#1436]
### Expected behavior
Docker starts up

### Actual behavior
Docker won't start, with the error: `Docker hv-sock proxy (vsudd) is not reachable`

### Information
Docker fails to start up if [Folding@Home](http://folding.stanford.edu/) is running.
Exiting Folding@Home then starting Docker and re-launching F@H works.

### Steps to reproduce the behavior

  1. Boot up with F@H and Docker both running on startup

**Comment by jasonbivins** [comment]
Hi @RoBorg 

How much system memory do you have allocated to Folding?

**Comment by RoBorg** [comment]
Hi @jasonbivins 

You don't allocate memory to F@H - it's just a regular program that runs at low CPU priority.
Looking at my system right now, it's only using about 500Mb - my system has 32GB.

I've done a little more experimentation.
I have an 8-core CPU (4 real cores with hyperthreading).
F@H uses 2 cores to folding on my 2 GPUs, leaving 6 cores to fold CPU workloads.

Cores allocated to F@H CPU folding:
6 - Docker won't start
5 - Docker won't start
4 - Docker starts - took a long time, lots of "[DockerDaemonChecker][Error  ] Docker daemon is not running" in the logs
3 - Docker starts OK

To me it looks like Docker is being starved for CPU when it starts up, but I'm not sure why that would be as everything F@H does is at Low priority, and as far as I can see, all the Docker stuff runs at Normal.

**Comment by jasonbivins** [comment]
@RoBorg 
Docker will pre-allocate memory when you're in linux container mode, and if it has more assigned than is currently free, it will fail to start. 

What settings do you have here?
![image](https://user-images.githubusercontent.com/28021664/34223903-face7da6-e58e-11e7-8be4-6f2e790c1a1c.png)

**Comment by RoBorg** [comment]
@jasonbivins 
My settings are the same as your screenshot - 2 CPUs and 2048 MB.
I have plenty of free memory - and it will start up with F@H running, but I need to have at least 3 CPU cores not assigned.

![image](https://user-images.githubusercontent.com/702158/34250922-42d3951c-e636-11e7-8819-e1610176b9d3.png)

**Comment by RoBorg** [comment]
Additional info: It's not just Folding@Home that does it - BOINC (another distributed computing platform that uses 100% CPU but at low priority) has the same effect.
