### ISSUE TITLE
Docker 17.12.0.-ce-rc2 dns suffix not propagated anymore

### ISSUE THREAD

**Issue by JohannesBeranek** [docker/for-win#1437]
### Expected behavior
DNS Suffix is propagated from host to container when using internal network

### Actual behavior
DNS Suffix is not propagated anymore

### Information
Seems this got broken in the latest edge upgrade, as it was working for me before. Also, switching back to stable (  17.09.1-ce-win42 (14687) ) fixed the issue for me.
Tried other things without success:
- switch off experimental features
- change network to public in hyper-v 
- removed and readded docker networks
- reboot (dozen of times actually)
- reinstall docker edge
- rebuild container (also dozen of times)

### Steps to reproduce the behavior

  Get a private network with a DNS Suffix and try nslookup/ping/... to a host with only the machine name part of the domain instead of a the full domain (FQDN still works, so it's definitely only DNS Suffix), e.g. "ping example.internal.network" works, "ping example" does not work.

On docker edge, /etc/resolv.conf is missing the "search ..." entry, docker stable has it.

**Comment by ebriney** [comment]
Thanks for the report @JohannesBeranek .
We did a fix for the next edge release.

**Comment by JohannesBeranek** [comment]
@ebriney thanks, unfortunately I've got the same issue with the stable version since today (docker update was somewhere this week). Will try with nightly in the meantime as I guess your fix should be in there if it's to come in the next edge version.

**Comment by ebriney** [comment]
Edge is fixed, I will investigate on stable but I don't think the code has moved.
Can you push a diag?

**Comment by Spotypop** [comment]
Hello, @ebriney 
Same issue here on 17.12.0-ce-win47 (15139), 
I dont know in which version @JohannesBeranek ran into the problem.
Can you guys tell me version that dns suffixes do propagate succesfully?
Thanks.

**Comment by Spotypop** [comment]
Happens on 18.02.0-ce-rc2-win51 (15631) as well.
