### ISSUE TITLE
Docker pull stuck at "Download completed" for 30 minutes without reporting any error and no image was pulled.

### ISSUE THREAD

**Issue by awidjaja** [docker/for-win#1440]
### Expected behavior

1. Less than 5 minute
2. Image is pulled
3. Any error is reported

### Actual behavior

1. it seems to be doing nothing for 30 mins while showing "Download Completed"
2. Image is never pulled
3. No error reported. No error in any log file on the host. 

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.

> F2099E05-3DBA-47DC-974B-B993D6042D1E/2017-12-18_12-07-42

  - a reproducible case if this is a bug, Dockerfiles FTW

> docker pull node

  - page URL if this is a docs issue or the name of a man page

> docker docs doesn't show any way to debug or check log of docker pull

  - host distribution and version (Windows version, build number, etc)

> OS Name: 	Microsoft Windows 10 Pro x64
Version:	10.0.16299 Build 16299
Processor: 	Intel(R) Core(TM) i7-3687U CPU @ 2.10GHz, 2101 Mhz, 2 Core(s), 4 Logical Processor(s)
Installed Physical Memory (RAM)	4.00 GB
Drive: C:\ on SSD ( 9 GB free space ) 

### Steps to reproduce the behavior

  1. docker pull node

Edit: it worked just now when I tried again, maybe there was downtime on the registry. 
Still I would like to keep the a feature request to simply report the error to the screen or on the log file on the host when the build or pull failed.

**Comment by jasonbivins** [comment]
since this was added to moby as an enhancement request, i'll go ahead and close this one out
