### ISSUE TITLE
Docker Desktop 4.35.1 crash on start

### ISSUE THREAD

**Issue by johanhammar** [docker/for-win#14410]
### Description

I upgraded Docker Desktop from 4.34.2 to 4.35.1 and now Docker Desktop won't start anymore

The `monitor.log` contains the following

```
[2024-11-07T08:19:24.853306500Z] panic: runtime error: invalid memory address or nil pointer dereference
[2024-11-07T08:19:24.853306500Z] [signal 0xc0000005 code=0x0 addr=0xc8 pc=0x14273b4]
[2024-11-07T08:19:24.853306500Z] 
[2024-11-07T08:19:24.853306500Z] goroutine 1 [running, locked to thread]:
[2024-11-07T08:19:24.853306500Z] github.com/docker/pinata/common/cmd/com.docker.backend/internal/engines/engine.(*Paths).Initialize(0xc000887908)
[2024-11-07T08:19:24.853306500Z] 	github.com/docker/pinata/common/cmd/com.docker.backend/internal/engines/engine/paths.go:124 +0xab4
[2024-11-07T08:19:24.853306500Z] main.initBackend({_, _}, _)
[2024-11-07T08:19:24.853306500Z] 	github.com/docker/pinata/common/cmd/com.docker.backend/backend.go:160 +0xfc9
[2024-11-07T08:19:24.853306500Z] main.runBackend()
[2024-11-07T08:19:24.853306500Z] 	github.com/docker/pinata/common/cmd/com.docker.backend/backend.go:62 +0x110
[2024-11-07T08:19:24.853306500Z] main.main()
[2024-11-07T08:19:24.853306500Z] 	github.com/docker/pinata/common/cmd/com.docker.backend/main.go:18 +0x19c
[2024-11-07T08:19:24.861509200Z] backend shutdown after signal
```

Downgrading to Docker Desktop to 4.34.2 works and I can start Docker Desktop again

### Reproduce

1. Start Docker Desktop
2. Docker Desktop not started
3. Check monitor.log

### Expected behavior

Docker Desktop should start

### docker version

Cannot run docker since Docker Desktop won't start

### docker info

Cannot run docker since Docker Desktop won't start

### Diagnostics ID

Cannot generate an ID since Docker Desktop won't start

### Additional Info

Windows 11 Version 23H2 (OS Build 22631.4391)

WSL version: 2.3.24.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.22631.4391

**Comment by Scelestan** [comment]
check "BE9AFAAF-F68B-41D0-9D12-84760E6B8740/20190905152051"

**Comment by johanhammar** [comment]
Can you provide more details? What is "BE9AFAAF-F68B-41D0-9D12-84760E6B8740/20190905152051"?

**Comment by diesoto** [comment]
Hi Johan. How can I downgrade to 4.34.2?

**Comment by pl4nty** [comment]
@diesoto this worked for me: `winget install Docker.DockerDesktop --version 4.34.2 --force --custom "--disable-version-check"`

**Comment by johanhammar** [comment]
> Hi Johan. How can I downgrade to 4.34.2?

Does this mean you have the same problem?

**Comment by benfreke** [comment]
I had a similar issue. Docker Desktop would just hang and wouldn't start and couldn't run anything on Docker Desktop 4.35.

While looking for `monitor.log`, I found the cache directory in `AppData/Roaming/Docker Desktop/Cache/Cache_Data`. 

Once I'd cleared that out, everything worked as it should.

**Comment by diesoto** [comment]
> [@diesoto](https://github.com/diesoto) this worked for me: `winget install Docker.DockerDesktop --version 4.34.2 --force --custom "--disable-version-check"`

The downgrade was successful, but it didn't work for me, because I think the upgrade broke my ext4.vhdx

**Comment by diesoto** [comment]
> I had a similar issue. Docker Desktop would just hang and wouldn't start and couldn't run anything on Docker Desktop 4.35.
> 
> While looking for `monitor.log`, I found the cache directory in `AppData/Roaming/Docker Desktop/Cache/Cache_Data`.
> 
> Once I'd cleared that out, everything worked as it should.

Great idea. I did it. Didn't work for me either.

**Comment by johanhammar** [comment]
The Docker support helped me 🙏 . The following instructions worked for me

1.	Uninstall Docker Desktop. 
2.	Delete the following folders (please note that this will delete all images, volumes, and Docker-related files on your system): 
o	C:\ProgramData\Docker 
o	C:\Program Files\Docker 
o	C:\Users\<your user name>\AppData\Local\Docker 
o	C:\Users\<your user name>\AppData\Roaming\Docker 
3.	Reinstall Docker Desktop and check if it resolves the issue. https://docs.docker.com/desktop/release-notes/#4351 

Something probably got corrupted during the installation

**Comment by Scelestan** [comment]
sorry it's the checksum it have a problem when you provide your question

Le mar. 12 nov. 2024 à 07:51, Johan Hammar ***@***.***> a
écrit :
