### ISSUE TITLE
Docker Desktop Crashes When Running  Using WSL2

### ISSUE THREAD

**Issue by MrHemlock** [docker/for-win#14418]
### Description

I am attempting to install Docker Desktop.  When prompted, I have "Use WSL 2 instead of Hyper-V" checked, as it recommends.  However, when I run Docker Desktop, I get an error:

`running engine: waiting for the Docker API: engine linux/wsl failed to run: starting WSL engine: error spotted in wslbootstrap log: "[2024-11-11T21:19:03.345466300Z][wsl-bootstrap][F] no sd* disk in /sys/block with wwid ending by 2dc8686d0c338df62b504a5a: file does not exist"`

If I uninstall and reinstall with that option unchecked (so using Hyper-V instead), I'm able to used Docker as intended.  

WSL is up to date, I've made sure my Windows is up to date and I'm using 11 Pro on version 24H2, I've made sure to use the most recent installer, I've done factory reset, I've uninstalled using Revo and removed any and all remaining files associated with Docker then reinstalled, I've removed the WSL image, done `wsl --shutdown`, removed any other distro installed in my WSL, added a fresh Ubuntu to see if that was the problem, my default is version 2 for WSL....  I'm sure I'm missing a few.  

While I can just use Hyper-V, I would love to be able to use the recommended option of WSL 2.  I'm just completely out of ideas.

### Reproduce

Install a fresh copy of Docker Desktop with "Use WSL 2 instead of Hyper-V" selected. 
Open Docker Desktop
Receive error message: 
`running engine: waiting for the Docker API: engine linux/wsl failed to run: starting WSL engine: error spotted in wslbootstrap log: "[2024-11-11T21:19:03.345466300Z][wsl-bootstrap][F] no sd* disk in /sys/block with wwid ending by 2dc8686d0c338df62b504a5a: file does not exist"`

### Expected behavior

Being able to open Docker Desktop and use the WSL 2 backend

### docker version

```bash
Client:
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:42:27 2024
 OS/Arch:           windows/amd64
 Context:           desktop-linux
```

### docker info

```bash
Client:
 Version:    27.3.1
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.37
    Path:     C:\Program Files\Docker\cli-plugins\docker-debug.exe
  desktop: Docker Desktop commands (Alpha) (Docker Inc.)
    Version:  v0.0.15
    Path:     C:\Program Files\Docker\cli-plugins\docker-desktop.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.27
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.3.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.14.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
ERROR: Get "http://%2F%2F.%2Fpipe%2FdockerDesktopLinuxEngine/v1.47/info": context canceled
errors pretty printing info
```

### Diagnostics ID

FFEDC579-9B0F-4330-BDB1-7CF0582C6251/20241111211926

### Additional Info

A note on the `docker version` and `docker info` command outputs.  I was only able to get information for the Client sections.  Server either never showed up or hung, making me have to CTRL+C to end the process.

**Comment by MrHemlock** [comment]
Figured out the problem.  WSL 2 was apparently pointing to a custom kernel for no friggin' reason.  Clearing that out fixed it.

**Comment by RJFoster** [comment]
@MrHemlock I'm having the same issue, what was the actual fix? Did you have a kernal setting in your .wslconfig that you removed?

**Comment by RJFoster** [comment]
For future travellers, seems I'm actually encountering https://github.com/docker/for-win/issues/14453
