### ISSUE TITLE
Docker with LCOW still asks for Hyper-V

### ISSUE THREAD

**Issue by digulla** [docker/for-win#1441]
### Expected behavior

Install Docker, enable LCOW, docker starts even when Hyper-V is disabled.

### Actual behavior

When running ""C:\Program Files\Docker\Docker\Docker for Windows.exe", I get a dialog saying:

"Hyper-V and Containers features are not enabled."

### Information

$ docker version
Client:
 Version:       17.12.0-ce-rc3
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    80c8033
 Built: Thu Dec 14 00:39:41 2017
 OS/Arch:       windows/amd64
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.35/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

Background: I need to run VirtualBox on my computer, so I can't enable Hyper-V. I was hoping the new Docker Edge build with LCOW would allow me to run Docker natively.

**Comment by rn** [comment]
LCOW relies on Hyper-V as it spins up a Hyper-V utility VM per container, so this won't fix.

**Comment by digulla** [comment]
A pity. I was hoping Docker would switch to the new Windows Subsystem for Linux from the app store (https://www.microsoft.com/en-us/store/p/ubuntu/9nblggh4msv6).

**Comment by rn** [comment]
WSL is unlikely to be complete enough to run a full docker. See also https://dockercon.docker.com/watch/U7Bxp66uKmemZssjCTyXkm where John Starks explains why

**Comment by bardware** [comment]
Scot Hanslmann has a [blog](https://www.hanselman.com/blog/DockerAndLinuxContainersOnWindowsWithOrWithoutHyperVVirtualMachines.aspx)
A reader comments 
```
You do need hyper-v installed, but you can prevent it from being enabled with 
'bcedit /set hypervisorlaunchtype off' and a reboot. After that, the check in docker will succeed, 
but you can run vmware or another vm subsystem.
````
Can you try that?

**Comment by bardware** [comment]
I tried it, must be `bcdedit`

**Comment by bardware** [comment]
I call `docker pull ...`  and end up with:
```
failed to register layer: failed to start service utility VM (applydiff 40466208618b9c802f39127a3a02cef183df6519f87cfc8bff387cfed5664492): container 40466208618b9c802f39127a3a02cef183df6519f87cfc8bff387cfed5664492_svm encountered an error during CreateContainer: failure in a Windows system call: No hypervisor is present on this system. (0xc0351000) extra info: {"SystemType":"container","Name":"40466208618b9c802f39127a3a02cef183df6519f87cfc8bff387cfed5664492_svm","Layers":null,"HvPartition":true,"HvRuntime":{"ImagePath":"C:\\Program Files\\Linux Containers","LinuxInitrdFile":"initrd.img","LinuxKernelFile":"bootx64.efi"},"ContainerType":"linux","TerminateOnLastHandleClosed":true}
```

**Comment by billybooth** [comment]
Yes, that comment on the Hanselman blog made me optimistic as well about LCOW without hyper-v, but I don't know where that reader is coming from.  With `hypervisorlaunchtype off` under LCOW, I get `Error response from daemon: failed to start service utility VM (createreadwrite): CreateComputeSystem [...]: No hypervisor is present on this system.`
