### ISSUE TITLE
images gone and docker-compose suck

### ISSUE THREAD

**Issue by jan4984** [docker/for-win#1442]
### Expected behavior
pulled images not deleted and not hung in docker-compose

### Actual behavior
images deleted, docker-compose hung

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.

2198F492-1E4B-4E42-92FD-6C1914D3BD73/2017-12-18_19-27-49

  - a reproducible case if this is a bug, Dockerfiles FTW

```dockerfile
FROM golang:1.9.2

RUN apt-get update
RUN apt-get install libopus-dev -y

RUN go get github.com/stretchr/testify/assert
RUN go get github.com/gorilla/mux

ADD . /go/src/git/ogo/run/opuscodec
#for windows docker client, symbol link destroyed so we build again
RUN rm /go/src/git/ogo/run/opuscodec/deps/ubuntu/lib/libopus.so.0
RUN rm /go/src/git/ogo/run/opuscodec/deps/ubuntu/lib/libopus.so
RUN ln -s -T /go/src/git/ogo/run/opuscodec/deps/ubuntu/lib/libopus.so.0.5.2 /go/src/git/ogo/run/opuscodec/deps/ubuntu/lib/libopus.so.0
RUN ln -s -T /go/src/git/ogo/run/opuscodec/deps/ubuntu/lib/libopus.so.0.5.2 /go/src/git/ogo/run/opuscodec/deps/ubuntu/lib/libopus.so

ENV GOBIN go

RUN cd /go/src/git/ogo/run/opuscodec/cmd/webserver/ && bash test.sh
RUN go build /go/src/git/ogo/run/opuscodec/cmd/webserver/server.go

RUN rm -rf /go/src/git

ENV PORT 5555

CMD ["/go/server"]
```

  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

windows 10, 17.09.1-ce-win42 (14687)

### Steps to reproduce the behavior

  1. change dockerfile a lot 
  2. docker-compose up
  3. do step 1 and 2 again and again

**Comment by jan4984** [comment]
add more info: `docker-compose up` display `building xxxx` and hung.  `docker image ls` list nothing but column headers.

**Comment by jasonbivins** [comment]
Does restarting Docker help?

**Comment by jan4984** [comment]
@jasonbivins no. even restart windows and reinstall docker for win not help. but I can pull images and run `docker build .`, `docker-compose up` still hangs.
