### ISSUE TITLE
Docker Desktop - Unexpected WSL error

### ISSUE THREAD

**Issue by lonla26** [docker/for-win#14436]
### Description

Docker engine failed to start.

### Reproduce

The bug happens everytime I launch docker desktop.

### docker version

```bash
Client:
    Version:4.36.0
```

### docker info

```bash
Client:
   Context: default
   Debug mode: false
```

### Diagnostics ID

928A1C8E-C92E-4521-9A24-61468B970E3B/20241119221007

### Additional Info

deploying WSL2 distributions
ensuring main distro is deployed: deploying "docker-desktop": importing WSL distro "L'opération n'a pas pu être démarrée car une fonctionnalité requise n'est pas installée. \r\nCode d’erreur\u00a0: Wsl/Service/RegisterDistro/CreateVm/HCS/HCS_E_SERVICE_NOT_AVAILABLE\r\n" output="docker-desktop": exit code: 4294967295: running WSL command wsl.exe C:\Windows\System32\wsl.exe --import docker-desktop <HOME>\AppData\Local\Docker\wsl\main C:\Program Files\Docker\Docker\resources\wsl\wsl-bootstrap.tar --version 2: L'opération n'a pas pu être démarrée car une fonctionnalité requise n'est pas installée. 
Code d’erreur : Wsl/Service/RegisterDistro/CreateVm/HCS/HCS_E_SERVICE_NOT_AVAILABLE
: exit status 0xffffffff
checking if isocache exists: CreateFile \\wsl$\docker-desktop-data\isocache\: The network name cannot be found.

**Comment by amyavari** [comment]
I have same issue, after updating from 4.35.1 to 4.36.0, docker engine fails to start.
I'm using Window 11 64bit, WSL2 Ubuntu.

**Comment by lonla26** [comment]
Issue resolved after uninstalling docker and wsl, downloading the last version of windows (windows update) and reinstalling docker and wsl.

**Comment by saran001** [comment]
Hi all, I'm also getting the same issue after upgrading my Docker Desktop to 4.36. Docker Desktop is unable to integrate with my WSL2 Ubuntu 20.04.

**My Windows machine specifications:**

Edition	Windows 10 Enterprise
Version	22H2
OS build	19045.5011

**Error Message:***

![Image](https://github.com/user-attachments/assets/9df581e1-6935-4e87-b7d9-86b393d615d8)
