### ISSUE TITLE
Docker Desktop is not starting after Upgrade on Windows 11

### ISSUE THREAD

**Issue by hereiamravi** [docker/for-win#14478]
### Description

Docker Desktop is not starting after Upgrade on Windows 11. looks like no work around as such for now. please loook into this asap

diagnostics id : AFA08CA1-2311-4C9D-A8F2-2BEE8A427348/20241210173141

deploying WSL2 distributions
ensuring data disk is available: exit code: 4294967295: running WSL command wsl.exe C:\WINDOWS\System32\wsl.exe --mount --bare --vhd <HOME>\AppData\Local\Docker\wsl\disk\docker_data.vhdx: Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine]

Arguments for running Linux binaries:

    If no command line is provided, wsl.exe launches the default shell.

    --exec, -e <CommandLine>

        Execute the specified command without using the default Linux shell.

    --

        Pass the remaining command line as is.

Options:

    --cd <Directory>

        Sets the specified directory as the current working directory.

        If ~ is used the Linux user's home path will be used. If the path begins

        with a / character, it will be interpreted as an absolute Linux path.

        Otherwise, the value must be an absolute Windows path.

    --distribution, -d <Distro>

        Run the specified distribution.

    --user, -u <UserName>

        Run as the specified user.

    --system

        Launches a shell for the system distribution.

Arguments for managing Windows Subsystem for Linux:

    --help

        Display usage information.

    --install [Options]

        Install additional Windows Subsystem for Linux distributions.

        For a list of valid distributions, use 'wsl --list --online'.

        Options:

            --distribution, -d [Argument]

                Downloads and installs a distribution by name.

                Arguments:

                    A valid distribution name (not case sensitive).

                Examples:

                    wsl --install -d Ubuntu

                    wsl --install --distribution Debian

            --no-launch, -n

                Do not launch the distribution after install.

    --mount <Disk>

        Attaches and mounts a physical disk in all WSL2 distributions.

        Options:

            --bare

                Attach the disk to WSL2, but don't mount it.

            --type <Type>

                Filesystem to use when mounting a disk, if not specified defaults to ext4.

            --options <Options>

                Additional mount options.

            --partition <Index>

                Index of the partition to mount, if not specified defaults to the whole disk.

    --set-default-version <Version>

        Changes the default install version for new distributions.

    --shutdown

        Immediately terminates all running distributions and the WSL 2

        lightweight utility virtual machine.

    --status

        Show the status of Windows Subsystem for Linux.

    --unmount [Disk]

        Unmounts and detaches a disk from all WSL2 distributions.

        Unmounts and detaches all disks if called without argument.

    --update [Options]

        If no options are specified, download and install WSL from the Microsoft Store.

        Options:

            --rollback

                Revert to the previous version of the WSL 2 kernel.

            --inbox

                Only update the inbox WSL 2 kernel. Do not install WSL from the Microsoft Store.

            --web-download

                Download the most recent version of WSL from the internet instead of the Microsoft Store.

Arguments for managing distributions in Windows Subsystem for Linux:

    --export <Distro> <FileName>

        Exports the distribution to a tar file.

        The filename can be - for standard output.

    --import <Distro> <InstallLocation> <FileName> [Options]

        Imports the specified tar file as a new distribution.

        The filename can be - for standard input.

        Options:

            --version <Version>

                Specifies the version to use for the new distribution.

    --list, -l [Options]

        Lists distributions.

        Options:

            --all

                List all distributions, including distributions that are

                currently being installed or uninstalled.

            --running

                List only distributions that are currently running.

            --quiet, -q

                Only show distribution names.

            --verbose, -v

                Show detailed information about all distributions.

            --online, -o

                Displays a list of available distributions for install with 'wsl --install'.

    --set-default, -s <Distro>

        Sets the distribution as the default.

    --set-version <Distro> <Version>

        Changes the version of the specified distribution.

    --terminate, -t <Distro>

        Terminates the specified distribution.

    --unregister <Distro>

        Unregisters the distribution and deletes the root filesystem.

: exit status 0xffffffff
checking if isocache exists: CreateFile \\wsl$\docker-desktop-data\isocache\: The network name cannot be found.[diagnostics.log](https://github.com/user-attachments/files/18083736/diagnostics.log)

### Reproduce

docker desktop failed to start.
attached diagnostics logs in the comments.
Steps to produce:
OS : Windows 11
upgrade docker.
open the docker desktop.

### docker version

```bash
Docker version 27.3.1, build ce12230
PS C:\Users\bravi> docker version
Client:
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:42:27 2024
 OS/Arch:           windows/amd64
 Context:           desktop-linux
error during connect: Get "http://%2F%2F.%2Fpipe%2FdockerDesktopLinuxEngine/v1.47/version": open //./pipe/dockerDesktopLinuxEngine: The system cannot find the file specified.
```

### docker info

```bash
Docker version 27.3.1, build ce12230
PS C:\Users\bravi> docker version
Client:
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:42:27 2024
 OS/Arch:           windows/amd64
 Context:           desktop-linux
error during connect: Get "http://%2F%2F.%2Fpipe%2FdockerDesktopLinuxEngine/v1.47/version": open //./pipe/dockerDesktopLinuxEngine: The system cannot find the file specified.
```

### Diagnostics ID

AFA08CA1-2311-4C9D-A8F2-2BEE8A427348/20241210173141

**Comment by andrea-reale** [comment]
Hi @hereiamravi,

it looks like you are running a rather old version of Microsoft WSL. The issue should disappear once you update WSL to the latest version. 

Please update wsl either by running  `wsl.exe --update --web-download`, or by updating it from the Microsoft store, or by downloading Microsoft's installer [here](https://github.com/microsoft/WSL/releases/tag/2.3.26). After the update, you should be able to verify that you're on the latest version via `wsl.exe --version`. 

---

Closing this as this is a duplciate of https://github.com/docker/for-win/issues/14447 . Feel free to open a different issue if you are still experiencing problems, after having verified that you are now running the latest (2.3.26) WSL version.

**Comment by hereiamravi** [comment]
Thanks it worked
