### ISSUE TITLE
Unable to pull windows images - error on connect to pipe after download layers

### ISSUE THREAD

**Issue by alefesta** [docker/for-win#1448]
### Expected behavior
docker pull microsoft/windowsservercore 
on Windows 10 Pro should result in having windows image saved locally.
Linux images work fine.
### Actual behavior
After docker pull the image layers start to be downloaded.
Download ends without error but instead of being expanded an erorr is throwed:
Error response from daemon: open \\.\pipe\docker_engine_windows: The system cannot find the file specified.
no image is shown after.

### Information

  - Diagnostic ID 0DF6909D-A425-470E-ABCE-5E2B07D5F9D7/2017-12-19_10-01-53
  - host distribution and version : 
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:22:26 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:32:40 2017
 OS/Arch:      windows/amd64
 Experimental: true

Channel: stable
Sha1: 3176a6af014bdb1346ed31371a717e87e656e2b7
Started on: 2017/12/19 08:10:52.000
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1709
Build: 16299
BuildLabName: 16299.15.amd64fre.rs3_release.170928-1534

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jasonbivins** [comment]
Hi @alefesta 
It looks like there might be some files left over after uninstalling/reinstalling.

Can you make sure that the Docker for Windows service is installed?

**Comment by alefesta** [comment]
sorry for the delay but no luck...I've tried to unistall everything again.
Removed manually everything from 
C:\program files \docker
c:\programdata\docker
c\users\afesta\appdata\roaming\docker
c\users\afesta\appdata\local\docker
any tmp file
but when I do reinstall (rebooted also the machine after) and I try to pull any windows image download is succesfull but no image after..
What are the files left you are referring to?

**Comment by alefesta** [comment]
fixed it. I had LCOW_SUPPORTED = 1 as fixed enviroment variable, it was probably due an early implementation of the ubuntu hyperv containers support experiment I did. Even removing docker for win the variable was not removed and this caused the error everytime. Removing the variable made the trick.
