### ISSUE TITLE
All links to Docker Desktop 4.37.1 return 403 error

### ISSUE THREAD

**Issue by asvishnyakov** [docker/for-win#14490]
### Description

All links to download Docker Desktop 4.37.1 listed [there](https://docs.docker.com/desktop/release-notes/) returns the following error message:

> 403 Forbidden
Code: AccessDenied
Message: Access Denied
RequestId: SYVZ6Y13B5CQN2B4
HostId: sfeDhR0oUFcl+eRuLbfhROyTpse6S4AsfudGmio+XI8v6YTl24adXRKOYnJ723ofCu06FdKMhbE=

### Reproduce

Try to download Docker Desktop 4.37.1 from any link available [here](https://docs.docker.com/desktop/release-notes/)

### Expected behavior

Should be able to download

### docker version

```bash
N/A
```

### docker info

```bash
N/A
```

### Diagnostics ID

N/A

**Comment by LewisRye** [comment]
Also having this issue, guess I will be staying on 4.37.0 for now...

**Comment by thaJeztah** [comment]
Thanks for reporting; it looks like the build numbers in the URL were not updated to the right one, and the pull request to fix those was still pending;

- https://github.com/docker/docs/pull/21670

I just merged that fix and deployed it, so the links should now work

**Comment by asvishnyakov** [comment]
@thaJeztah Thank you, now it's working

**Comment by thaJeztah** [comment]
Good to hear, thanks again for reporting!
