### ISSUE TITLE
docker-compose.exe and docker-machine.exe do not exist.

### ISSUE THREAD

**Issue by davidshq** [docker/for-win#145]
### Expected behavior

docker-compose and docker-machine to exist.

### Actual behavior
docker-compose and docker-machine don't seem to exist.

### Information

  - Diagnostic ID: 741DEED0-67F4-4993-A5C2-82E18E346788/2016-10-13_00-24-16
  - Windows 10 Version 1607 OS Build 14393.321

### Steps to reproduce the behavior

  1. Downloaded InstallDocker.msi
  2. Ran InstallDocker.msi
  3. Check c:\program files\docker for files, only docker.exe and dockerd.exe exist.

**Comment by rneugeba** [comment]
the binaries should be in `C:\Program Files\Docker\Docker\resources\bin` and you PATH should be set accordingly. This will only work in new shells opened after installing Docker for Windows and only if you don't completely reset your PATH in your init files.

Could you check if the files are there?
thanks
