### ISSUE TITLE
windows 10 suddenly cannot work with dial tcp 192.168.*.*:2376: connectex: No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by zzclynn** [docker/for-win#1451]
### Expected behavior
docker info    should show the information on windows 10
### Actual behavior
show:
could not read CA certificate "C:\\Users\\Administrator\\.docker\\ca.pem": open C:\Users\Administrator\.docker\ca.pem: T
he system cannot find the file specified.

after copy ca.pem from "C:\\Users\\Administrator\\.docker\\machine\\certs\\ca.pem" to the above place 
it shows:
error during connect: Get https://192.168.41.29:2376/v1.32/info: dial tcp 192.168.41.29:2376: connectex: No connection could be made because the target machine actively refused it.

### Information
   docker --version
   Docker version 17.09.1-ce, build 19e2cf6
   I can ran docker build, docker run the day before yesterday, however, today I got this port 2376 problem, uninstall-> install, install docker toolbox, did not solve the problem.
   I did not make any changes those day on my windows 10 environment. 
   I checked the Expose daemon on tcp://localhost:2375 withoud TLS checkbox,
   Tried to add   "hosts": ["0.0.0.0:2375","0.0.0.0:2376"] in the configure file, but it showed "hosts": Cannot be used in Docker for Windows.
   Help~ Help~ Help~

### Steps to reproduce the behavior

  1. docker info
  2. copy ca.pem 
  3. docker info

**Comment by jasonbivins** [comment]
Hi @zzclynn  Were you trying to use Docker machine, or trying to use SSH in Windows?

Please see here for a bit more information around the certs, and for a script that should help you create them.  https://github.com/MicrosoftDocs/Virtualization-Documentation/tree/master/windows-server-container-tools/DockerTLS

**Comment by zzclynn** [comment]
@jasonbivins, Thanks.  I tried to build docker image by dockerfile-maven plugin in Java project, and it worked 2 days ago, today I came back to rework something, and it showed me this.  So, there is no SSH, it might call Docker machine?

**Comment by zzclynn** [comment]
@jasonbivins  the method in your link did not work for me, thanks.

**Comment by zzclynn** [comment]
For me, it looks like the docker server is not running, the docker client however,is running.
And there is a button switch to windows container in the setting bar, once I clicked that, I got this error.

`超时时间已到而操作尚未完成。
   在 System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   在 Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(String args, Dictionary`2 env) 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:行号 138
   在 Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:行号 201
   在 Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions) 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:行号 79
   在 Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:行号 47
   在 Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:行号 145`

And I have report the crash with diagnostic id:
9BC164E3-A4DC-4991-83BC-0BD0632B0CEC/2017-12-21_17-09-05

Still No clue what's going wrong.
