### ISSUE TITLE
Named pipe mounting does not work for windows containers.

### ISSUE THREAD

**Issue by yusuf-gunaydin** [docker/for-win#1457]
### Expected behavior
Named pipe: "\\.\pipe\docker_engine" should be opened in container.

### Actual behavior
\\.\pipe\docker_engine is not opened. Therefore, docker commands inside container fail with output

    Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.31/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
    FC19846E-F26E-4F68-9178-0AE8317D7E8E/2017-12-22_16-58-15

### Steps to reproduce the behavior

Additional information and repro can be found in this stackoverflow question: 
https://stackoverflow.com/questions/47938910/docker-windows-container-mounting-named-pipe

**Comment by ralsu091** [comment]
+1 I'm having the same issue:
```
Client:
 Version:       18.03.0-ce-rc1
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    c160c73
 Built: Thu Feb 22 02:34:04 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce-rc1
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.4
  Git commit:   c160c73
  Built:        Thu Feb 22 02:41:20 2018
  OS/Arch:      windows/amd64
  Experimental: true
```

**Comment by yusuf-gunaydin** [comment]
Closing as this is tracked by https://github.com/moby/moby/issues/36562.
