### ISSUE TITLE
Docker not starting on W10 Insider Preview 17063

### ISSUE THREAD

**Issue by tdroenner** [docker/for-win#1458]
### Expected behavior
Docker starts as usual.

### Actual behavior
Unable to create File System Image
   bei Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:Zeile 36.
   bei Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:Zeile 95.
   bei Docker.Actions.<>c__DisplayClass18_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:Zeile 81.
   bei Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:Zeile 59.
### Information

Diagnostic-ID: 
46919F58-4A29-4D8C-AC41-0CD2C20AF914/2017-12-23_00-07-31
Version 17.12.0-ce-rc4-win44 (14896)
Channel: edge
f23de3e
W10 Insider Preview 17063

### Steps to reproduce the behavior

  1. Upgade to 17063 Insider Preview and launch Docker for Windows

**Comment by tdroenner** [comment]
Still present with latest Edge release:
Unable to create File System Image
   bei Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:Zeile 36.
   bei Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:Zeile 95.
   bei Docker.Actions.<>c__DisplayClass20_0.<ResetToDefault>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:Zeile 154.
   bei Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:Zeile 59.

**Comment by nstrelow** [comment]
Please fix this. We need this. Is there no workaround?
I want to use Linux containers on Windows.

**Comment by Kevinrob** [comment]
My workaround is to rollback to previous Windows version. Just WOW how it's easy now 👍 (17046).
And Docker work again.

**Comment by misenhower** [comment]
I ran into this issue on today's update to the stable channel (version 17.12.0-ce-win46 2018-01-09). The previous stable channel version (17.09.1-ce-win42 2017-12-11) was working properly under 17063.

I was able to fix this by downgrading to the 17.09.1 release. For anyone else looking for the previous version's installer, you can find it [here](https://download.docker.com/win/stable/14687/Docker%20for%20Windows%20Installer.exe).

You'll have to manually uninstall the newer version of Docker first, but after installing the older version things are working again for me for now. (Of course this release doesn't have LCOW or anything else from the newer edge builds.)

Also, I found another reference to the "Unable to create File System Image" issue [here](https://github.com/moby/moby/issues/35854), not sure if that's related.

**Comment by tdroenner** [comment]
I can confirm that a downgrade to Docker 17.09.1 is working.

**Comment by ztolley** [comment]
Another here with same issue

**Comment by djensen47** [comment]
18 days with no resolution? So angry and sad.

**Comment by djensen47** [comment]
@tdroenner Where did you find the older version of Docker??

**Comment by djensen47** [comment]
I can also confirm that 17.09.1 is working.

Here's a link to 17.09.1: https://download.docker.com/win/stable/14687/Docker%20for%20Windows%20Installer.exe

**Comment by aaronpowell** [comment]
Seems like the problem isn't with Docker, but Windows itself - https://github.com/moby/moby/issues/35854

I foolishly updated to the latest stable as well so it looks like I'll have to downgrade and keep an eye on update prompt :(.

**Comment by allenstecat** [comment]
I will see what I can find out internally about this.  I am going to test upgrading to a canary windows build to see if that fixes this as well.

**Comment by jasonbivins** [comment]
Windows 17063 did break a few things for Docker - but it's expected to be fixed in the next insider release
https://blogs.windows.com/windowsexperience/2017/12/19/announcing-windows-10-insider-preview-build-17063-pc/#8u4SZFHchBmH2swz.97

**Comment by marfillaster** [comment]
If you're on 17.09.1 on Windows Insider 17074, skip 17.12.0-ce-win47

**Comment by dannyk81** [comment]
Windows Insider Build 17074 [released](https://blogs.windows.com/windowsexperience/2018/01/11/announcing-windows-10-insider-preview-build-17074-pc/#FlAiSKWLDf8klift.97), but seems like the issue is still there.

I did a test anyway and can confirm that at least for me the issue is still there.

**Comment by marfillaster** [comment]
17.09.1 works on 17074. You may need to uninstall 17.12.0 if you've recently upgraded.

**Comment by ATGardner** [comment]
anybody tried 17.12.0-ce-win47 (15139) on 17074?

**Comment by tdroenner** [comment]
Look two posts above. In short: not working.

**Comment by mishrsud** [comment]
Exact same issue as described in the original issue text, Windows insider 1709
As posted in the thread above, docker 17.09.1: is the only version that works!! https://download.docker.com/win/stable/14687/Docker%20for%20Windows%20Installer.exe

**Comment by strattas** [comment]
Same issue here. 17.09.1 works.

**Comment by ATGardner** [comment]
Just updated windows to 17083. Docker 17.12 and Docker edge 18.01 still doesn't work.
Reverted to Docker 17.09 again.

**Comment by pbering** [comment]
Also the same on 17083 and 18.02.0-ce-rc1-win50 (15489)

**Comment by hajekj** [comment]
Same on 17093...

**Comment by nstrelow** [comment]
those f**** a**holes

**Comment by dannyk81** [comment]
I was curious and tried the latest edge on 17093, but seems like I'm hitting a different issue now:
```
[12:56:48.147][Notifications  ][Error  ] Binary stream '0' does not contain a valid BinaryHeader. Possible causes are invalid stream or object version change between serialization and deserialization.
```

Has anyone else noticed that? or you get the same error as before?

Fallback to 17.09.1 still works 😅

**Comment by PatrickLang** [comment]
That's right. I did more digging and the fix in 17093 was incomplete. Full logs at 

https://github.com/docker/for-win/issues/1514#issuecomment-364227039

**Comment by dannyk81** [comment]
Thanks @PatrickLang, hope next release will fix this :)

**Comment by EmpeRoar** [comment]
@misenhower  Thanks, downgrading fixed my issue.

**Comment by Viper007Bond** [comment]
Nope, still fails with 17101.

**Comment by nstrelow** [comment]
Hopes still up for 17604, will test later

**Comment by nstrelow** [comment]
Hopes still up for 17604, will test later

**Comment by marfillaster** [comment]
Fail to start on Edge 18.02.0-ce-win52 2018-02-08  (Insider 17101)

    E461D0ED-8196-4916-B58B-675C3DBB3A64/2018-02-15_18-23-52

**Comment by nstrelow** [comment]
On 17604 with 17.12.0-ce-win47 or 18.02.0-ce-win52:
```
Binary stream '0' does not contain a valid BinaryHeader. Possible causes are invalid stream or object version change between serialization and deserialization.
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 95
   at Docker.Actions.<>c__DisplayClass18_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 81
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```

**Comment by marfillaster** [comment]
@nstrelow, related https://github.com/docker/for-win/issues/558#issuecomment-326935707
 The network service is missing and even this [solution](https://social.technet.microsoft.com/Forums/ie/en-US/52586559-0e80-4b6a-906a-5f9279264f87/file-and-printer-sharing-for-microsoft-networks-is-missing?forum=winserver8gen) fails. A group policy prevents re-install of said driver. [Someone](https://github.com/docker/for-win/issues/558#issuecomment-365796027) is also on the same track.

**Comment by nstrelow** [comment]
I see, I cannot reinstall the shared files and printers service, uninstall fails with 0x80071779.

**Comment by pbering** [comment]
Confirmed working again on build 17107! :)

**Comment by Viper007Bond** [comment]
Working with Docker 17.12.0-ce-win47 (15139) as well.

**Comment by mi-hol** [comment]
fixed in Windows build 17107.1000

**Comment by tdroenner** [comment]
confirmes

**Comment by dannyk81** [comment]
@ATGardner see [this](https://github.com/docker/for-win/issues/1514#issuecomment-366351913) comment

17604 doesn't have the fix

**Comment by seffyroff** [comment]
Docker For Windows Edge  18.03.0-ce-rc1-win54 16164 working with Linux Containers on Windows Skip ahead build 17604 here :) Hooray for patience and nice work people!

**Comment by shahujvaln** [comment]
See #1232 for a fix.  That worked for latest version as well.

**Comment by shahujvaln** [comment]
@djensen47 Check all older versions @ https://docs.docker.com/docker-for-windows/release-notes/
