### ISSUE TITLE
Java API - Executing a program from within a shell script fails on Windows 10

### ISSUE THREAD

**Issue by billhab** [docker/for-win#146]
### Expected behavior
Program invoked from a shell script executes properly

### Actual behavior
Program invoked within a shell script works with CLI
Program invoked within a shell script fails when invoked using Java API CreateContainer/StartContainer.

Inconsistent behavior.  Either case works fine if docker is running under Linux but fails under Windows 10.  When it fails the return code is 1 or 127 depending on the phase of the Moon. 

Special Note: 
Debugging this type of issue with Docker is a real pain.  Once the container exits there is no way to see what happened.  This is especially the case when executing things with the Java API.  You can't go back into the failed container to figure out what happened.  Attaching to an exited container is not possible and starting it again doesn't help because it exits before you can attach. 

### Information

A diagnostic was uploaded with id: A793F06A-2BB2-4848-AECB-269265A747E3/2016-10-14_09-41-11
Windows 10  Pro

### Steps to reproduce the behavior

  1. Create a Linux image 
  2. Create a small shell script (SH or BASH) which does nothing but executes JavaJDKpath/bin/java -version
  3.  Run the script from the CLI ( docker run -it image script
      The Java version will appear on the console.
  4. Run the same script from a Java program that creates the container using .cmd(script) and start   the container.  The script will fail with a return code 1.

**Comment by friism** [comment]
That sounds very strange...

Are you sure the Java program using `.cmd(script)` manages to successfully create the container? If so, it'll be visible (even after exiting) with `docker ps -a`. If you find your container in that ps output, you can get the logs (even though it's stopped) with `docker logs <container-id>`

**Comment by billhab** [comment]
friism 
Using docker logs was a good tip.  I checked and had a permission error because the user was not permissioned to run the script.  So I changed the program to use root and re-ran it.  This time the return code was 127.  Looking at the logs again it complained that the java JDK folder didn't exist even though it appears as a mounted volume when I inspect the container.  When I run the same script through the docker CLI with the same JDK mounted using the -v option it works.  So maybe mounts in the Java API are not working.

**Comment by friism** [comment]
Thanks for following up.

You can use `docker inspect <stopped-container-id>` to see mounts.

Closing this for now since I don't think it's a Docker for Windows issue, feel free to re-open.

**Comment by billhab** [comment]
Problem is how the host path is defined in the Java API.  If you don't specify a drive letter for Windows docker the mount fails silently.  As a Windows user I would expect Docker to honor the current drive (which it doesn't).  A nice 'gotcha'.  The CLI -v option is very specific so the mount happens correctly.  Unfortunately docker is not consistent so I have to include OS testing so the same code can make allowances based on where it is running.

**Comment by friism** [comment]
@billhab can you provide more details on the inconsistency, perhaps with an example?
