### ISSUE TITLE
Windows binaries?

### ISSUE THREAD

**Issue by rgl** [docker/for-win#1460]
In the past I was downloading them from https://download.docker.com/win/static/, but the latest versions are not there anymore. Where are they now?

**Comment by friism** [comment]
Please follow the installation instructions here: https://docs.docker.com/engine/installation/windows/docker-ee/

If you want to test new features, we also have preview releases: https://docs.docker.com/engine/installation/windows/ee-preview/

**Comment by rgl** [comment]
Thank you, I will try those! But I was really looking for the CE version. Do you known why isn't it available anymore?

**Comment by rageshkrishna** [comment]
Is there an official source for static Docker binaries on Windows? I need to be able to include the docker binary in one of my images, so what's the best place to get it from? I'm only interested in having the docker client available in the image, so the full installer is really irrelevant to my scenario.

**Comment by meta-brajesh-jaishwal** [comment]
https://download.docker.com/win/static/stable/x86_64/ 
Above is for windows, others are available as well.

**Comment by rgl** [comment]
@meta-brajesh-jaishwal those are old releases. In the meantime I've started publishing them at https://github.com/rgl/docker-ce-windows-binaries-vagrant/releases

**Comment by lmakarov** [comment]
At the moment the following binaries are available for Mac:
https://download.docker.com/mac/static/stable/x86_64/

```
docker-17.06.0-ce.tgz  2018-05-03 07:13  5.5M
docker-17.06.1-ce.tgz  2018-05-03 07:13  5.5M
docker-17.06.2-ce.tgz  2018-05-03 07:13  5.5M
docker-17.09.0-ce.tgz  2018-05-03 07:13  5.7M
docker-17.09.1-ce.tgz  2018-05-03 07:13  5.7M
docker-17.12.0-ce.tgz  2018-05-03 07:13  5.9M
docker-17.12.1-ce.tgz  2018-05-03 07:13  5.9M
docker-18.03.0-ce.tgz  2018-05-03 07:13  10M
docker-18.03.1-ce.tgz  2018-05-03 07:13  10M
```

And the following binaries are available for Windows:
https://download.docker.com/win/static/stable/x86_64/

```
docker-17.06.0-ce.zip  2018-05-03 07:13  16M
docker-17.06.1-ce.zip  2018-05-03 07:13  16M
docker-17.06.2-ce.zip  2018-05-03 07:13  16M
docker-17.09.0-ce.zip  2018-05-03 07:13  17M
```

The [comment](https://github.com/docker/for-win/issues/1917#issuecomment-378972095) from @carlfischer1 mentions Docker EE release cycle for Windows Sever as the reason why Windows binaries are not yet available. That does not explain why the Mac binaries are up-to-date, but Windows are not.

We are using these in automated install scripts, which are used on Mac and Windows and are now broken on Windows of we decide to update to docker-18.03.1-ce.

Can the available versions please be matched? (by adding the Windows binaries, not removing the ones for Mac 😄)

**Comment by olljanat** [comment]
@carlfischer1 Docker 18.03.1-ee-1 have been released but still latest CE version here https://download.docker.com/win/static/stable/x86_64/ is 17.09.0-ce.

What is reason for that?

**Comment by olljanat** [comment]
FYI. It looks to be that starting from 18.09.0 CE and EE are once again same package.

So you can find link to metadata file on PowerShell module https://github.com/OneGet/MicrosoftDockerProvider/blob/master/DockerMsftProvider.psm1#L21

and inside of that you can see 18.09.0 version binaries can be downloaded from https://dockermsft.blob.core.windows.net/dockercontainer/docker-18-09-0.zip


but still note that normal users should use https://www.docker.com/products/docker-desktop instead of that.

**Comment by Drewster727** [comment]
@olljanat any idea where we can get >19.03.5 for windows? I used to be able to get it from:
`https://download.docker.com/components/engine/windows-server/<version>/docker-<version>.zip`
e.g.
https://download.docker.com/components/engine/windows-server/19.03/docker-19.03.5.zip

However, 19.03.9 was released just recently and it's not there. I have server-side machines that I don't want the desktop experience on, just the engine...

**Comment by olljanat** [comment]
@Drewster727 I would guess that after [Mirantis acquired Docker Enterprise business](https://www.mirantis.com/company/press-center/company-news/mirantis-acquires-docker-enterprise/) there is no clear process how to release those Docker enterprise binaries for Windows so no one is actually doing it.

**Comment by Drewster727** [comment]
Well, things are looking up...
@olljanat thanks -- guess I'll keep waiting?
We don't pay for enterprise features, we just want the executables/binaries to run things server-side...

**Comment by olljanat** [comment]
@Drewster727 EE version on Windows actually does not contain any extra features but they just test those extra carefully before release so those versions lacks behind. I just checked that 19.03.5 looks to be latest EE version currently. Are you looking for some specific bugfix? Only difference between 19.03.5 and 19.03.8 is just couple of bugfixes which are listed on here https://docs.docker.com/engine/release-notes/
