### ISSUE TITLE
unable to start docker

### ISSUE THREAD

**Issue by wasif-balol** [docker/for-win#1470]
### don't have enough memory to start docker

my docker isn't working showing the error that don't have enough memory, although iv'e set my memory to 1024 mb and 1 cpu in advanced setting but still it's not working
![capture](https://user-images.githubusercontent.com/30393180/34456095-48251e9c-edb0-11e7-9e69-2395f044829c.PNG)

**Comment by jasonbivins** [comment]
Hi @wasif-balol   How much free memory and CPU do you have available? Can you share the results of a `docker info` command?
