### ISSUE TITLE
Unable to install with windows10 ent10586

### ISSUE THREAD

**Issue by sunwu51** [docker/for-win#1474]
### Expected behavior
Install docker in win10

### Actual behavior
can not install docker

### Information
![tim 20180102215333](https://user-images.githubusercontent.com/15844103/34485810-64fc0cd4-f007-11e7-8d0b-e48d0e6f5a8b.png)

My windows is Enterprise version 10586, but  still tell me that. What's wrong with my pc?

**Comment by jasonbivins** [comment]
Hi @sunwu51 
This warning is actually incorrect, and we're in the process of updating it, but the documentation has been updated.    Docker for Windows requires build Windows 10 14393 or later.   https://docs.docker.com/docker-for-windows/install/#what-to-know-before-you-install

**Comment by sunwu51** [comment]
@jasonbivins Thanks. I update my windows to 1709 today. It works  :)
