### ISSUE TITLE
Docker for Windows Fails to Start

### ISSUE THREAD

**Issue by mrgrew** [docker/for-win#1475]
### Expected behavior

Docker starts

### Actual behavior

Docker displays

>  "An error occurred"
> Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID 6C78DAAF-3A2F-40C7-A53B-B9190034EB9B)
> 
> 'MobyLinuxVM' failed to start worker process: %%3228369022 (0xC06D007E). (Virtual machine ID 6C78DAAF-3A2F-40C7-A53B-B9190034EB9B)
> at Start-MobyLinuxVM, <No file>: line 291
> at <ScriptBlock>, <No file>: line 386
>    at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 245
>    at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 122
>    at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
>    at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

### Information

  - Diagnostic ID: D9CCEF81-3734-48ED-BB1E-1F6C3618F5E2/2018-01-02_12-10-06
  - Contents of log file:
[log-D9CCEF81-3734-48ED-BB1E-1F6C3618F5E2.txt](https://github.com/docker/for-win/files/1598204/log-D9CCEF81-3734-48ED-BB1E-1F6C3618F5E2.txt)
  - Following message appears in my System Event Log:
Log Name:      System
Source:        Microsoft-Windows-DNS-Client
Date:          1/2/2018 12:22:52 PM
Event ID:      8012
Task Category: (1028)
Level:         Information
Keywords:      
User:          NETWORK SERVICE
Computer:      nybd-gwiley.drf.corp
Description:
The system failed to register pointer (PTR) resource records (RRs) for network adapter
with settings:

           Adapter Name : {DBB303A5-7AEA-464B-BE6D-B63522709B57}
           Host Name : nybd-gwiley
           Adapter-specific Domain Suffix : drf.corp
           DNS server list :
             	10.200.40.240, 10.200.40.134, 10.232.72.21, 10.232.72.22
           Sent update to server : 10.200.40.240:53
           IP Address :
             10.200.41.23

The reason that the system could not register these RRs was because the DNS server refused the update request. The cause of this could be (a) your computer is not allowed to update the adapter-specified DNS domain name, or (b) because the DNS server authoritative for the specified name does not support the DNS dynamic update protocol.

To register the DNS pointer (PTR) resource records using the specific DNS domain name and IP addresses for this adapter, contact your DNS server or network systems administrator.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-DNS-Client" Guid="{1C95126E-7EEA-49A9-A3FE-A378B03DDB4D}" />
    <EventID>8012</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>1028</Task>
    <Opcode>0</Opcode>
    <Keywords>0x4000000000000000</Keywords>
    <TimeCreated SystemTime="2018-01-02T17:22:52.459265800Z" />
    <EventRecordID>2795</EventRecordID>
    <Correlation />
    <Execution ProcessID="1432" ThreadID="3036" />
    <Channel>System</Channel>
    <Computer>nybd-gwiley.drf.corp</Computer>
    <Security UserID="S-1-5-20" />
  </System>
  <EventData>
    <Data Name="AdapterName">{DBB303A5-7AEA-464B-BE6D-B63522709B57}</Data>
    <Data Name="HostName">nybd-gwiley</Data>
    <Data Name="AdapterSuffixName">drf.corp</Data>
    <Data Name="DnsServerList">	10.200.40.240, 10.200.40.134, 10.232.72.21, 10.232.72.22</Data>
    <Data Name="Sent UpdateServer">10.200.40.240:53</Data>
    <Data Name="Ipaddress">10.200.41.23</Data>
    <Data Name="ErrorCode">9005</Data>
  </EventData>
</Event>

### Steps to reproduce the behavior

I had VirtualBox installed when I first got this error. I uninstalled VirtualBox but get the same problem so I don't think it's relevant but I thought it worth mentioning.

  1. Uninstall Docker
  2. Disable Hyper-V
  3. Reboot
  4. Enable Hyper-V
  5. Reboot
  6. Install Docker for Windows
  7. Start Docker for Windows

**Comment by jasonbivins** [comment]
Hi @mrgrew 
Let's drop the MobyLinuxVM, and then recreate it to see if we get a more specific error:
`
powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -destroy
powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -create `

**Comment by mrgrew** [comment]
Using a Command Prompt as Administrator I could create the MobyLinuxVM:

> C:\Program Files\Docker\Docker\resources>powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -destroy
> Script started at 12:59:13.069
> Module loaded at 12:59:14.519
> VM MobyLinuxVM does not exist
> Destroying Switch DockerNAT...
> Removing VM MobyLinuxVM...
> Delete VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
> 
> C:\Program Files\Docker\Docker\resources>powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -create
> Script started at 12:59:30.852
> Module loaded at 12:59:32.302
> Creating Switch: DockerNAT...
> Switch created.
> Set IP address on switch
> Creating VM MobyLinuxVM...
> Setting CPUs to 2 and Memory to 2048 MB
> Attach VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
> Connect Internal Switch DockerNAT
> Attach DVD .\mobylinux.iso
> Disabled Guest Service Interface
> Enabled Heartbeat
> Disabled Key-Value Pair Exchange
> Enabled Shutdown
> Enabled Time Synchronization
> Disabled VSS
> VM created.

Starting that VM using Hyper-V, however, yields the following:
![image](https://user-images.githubusercontent.com/8267130/34533242-62edffa8-f087-11e7-9845-c1c3dcf67437.png)

**Comment by mrgrew** [comment]
I tried enabling WMI since I noticed it was disabled. That didn't solve the issue.
![image](https://user-images.githubusercontent.com/8267130/34622306-a5adc78a-f21a-11e7-802c-cd80be2fa8ba.png)

**Comment by mrgrew** [comment]
Much to the chagrin of my help desk, I uninstalled Sophos. Now I can start Docker so I'll close this issue.

If there's anything that can be done to enable Docker to work with Sophos that would be great.

**Comment by mrgrew** [comment]
The early access version of [HitmanPro.Alert](https://community.sophos.com/products/intercept/early-access-preview/f/intercept-x-for-windows/97613/hyper-v-do-not-start-virtual-machines-windows-10-pro-1709/356481#356481) enabled me to start Docker with Sophos installed.
