### ISSUE TITLE
Unabe to see the Docker white whale Icon in system tray..

### ISSUE THREAD

**Issue by VenkateshSrini** [docker/for-win#1481]
### Expected behavior
When I start the docker by double clicking on window for Docker. There is no response. Also I do not see the white whale icon that indicates the successful start of Docker in notification area. Because of that I'm completely handicapped as I could not see the settings or switch to windows container
### Actual behavior
After success start the white windows whale icon should appear in the notification area.
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
Unable to access that as Whale icon is not appearing in System tray 
  - a reproducible case if this is a bug, Dockerfiles FTW
Yes reproducible

  - host distribution and version (Windows version, build number, etc)
Windows 10 Enterprise Version 1607, OS Build 14393.1066
-Docker version
Docker version 17.09.1-ce, build 19e2cf6

Please help asap I' struck completely

### Steps to reproduce the behavior

  1. ...Double click on docker for windows icon
  2. ...Nothig happens
  3. Open power shell and type docker --version we are able to see the docker is installed

**Comment by jasonbivins** [comment]
Hi @VenkateshSrini  You mentioned a docker  --version command is successful - can you post the results of the Docker info command?

**Comment by VenkateshSrini** [comment]
Hi,

I get the below error

error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/info: open //./pipe/docker_engine: The system cann
ot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to co
nnect. This error may also indicate that the docker daemon is not running.

**Comment by dvanlunen** [comment]
I found this was fixed just by logging in as an administrator user

**Comment by VenkateshSrini** [comment]
Oh yeah that was reason. Now it is working

**Comment by Thorbenl** [comment]
But i am running on my windows as an admin. stil dont ssee anything in the tray..so frustrating really

**Comment by rn** [comment]
@Thorbenl that's just the CLI and it's not able to talk to the daemon so Docker for Windows did not start. Can you check in Task Manager (or process explorer) for processes and services with `docker`/`Docker` in their name?  It's also best to open a new issue and you may want to include the logs from `%HOME%\AppData\Local\Docker`.

**Comment by mmeyer429** [comment]
Same issue here

Logs:
```
Version: 18.03.0-ce-win59 (16762)
Channel: stable
Sha1: d70d80d72f97d4adf1bdc82c699610faa38d7220
Started on: 2018/04/07 16:44:15.235
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1709
Build: 16299
BuildLabName: 16299.15.amd64fre.rs3_release.170928-1534
File: C:\Users\Martin\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[16:44:15.333][GUI            ][Info   ] Starting...
[16:44:15.345][GUI            ][Error  ] An instance is already running. Exiting.
```
I also did try:

restarting the service
closing every docker service/process
restarting my machine
setting the service start as manual, disabled the startup options and run everything manually

desktop icon did not work when double clicking or using run as an Administrator for all those different use cases.

docker version output:

```
docker --version
Docker version 18.03.0-ce, build 0520e24
```

**Comment by mmeyer429** [comment]
running  `C:\Windows\system32>docker version` has this output:
```
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:06:28 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.37/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

**Comment by Pete1138** [comment]
Was able to fix this by disabling Hyper-V in Windows

**Comment by andrewcassidy** [comment]
@Pete1138 what if you are using hyper-v since you are running linux containers on windows

**Comment by anjannath** [comment]
I am having the same issue, does docker use electron for the system tray? do i need to have electron installed in my system for it to work?

**Comment by FantomX1** [comment]
version 2.1.0.4 2019 November, the same problem, what seems to help was simply uninstalling and reinstalling it

**Comment by babcorj** [comment]
> Was able to fix this by disabling Hyper-V in Windows

Disabling Hyper-V prevents Docker from running on Windows. However, the following steps did work in my scenario: disable Hyper-V, restart, enable Hyper-V, restart.

**Comment by lovedeep-singh** [comment]
Im having same issue , tried the versions 18.09.3 and 19.03.1 but no luck at all.

 Version:           18.09.3
 API version:       1.39
 Go version:        go1.12
 Git commit:        774a1f4eee
 Built:             Mon Mar  4 10:36:44 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

Any help will be appreciated.
