### ISSUE TITLE
Impossible to share C drive

### ISSUE THREAD

**Issue by krl91** [docker/for-win#1482]
### Expected behavior
to have access to my C drive on Docker

### Actual behavior
Firewall detected, but we stop all firewall

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu. : 23189DF0-62D0-45EA-AD46-E69B8A1F312A/2018-01-03_17-25-02
  - Version 17.09.1-ce-win42 (14687)
  - host distribution and version Last Windows 10

### Steps to reproduce the behavior

  1. ... go on Docker Settings
  2. ...Shared Drive
  3. Select C
  4. Press Apply
  5. Write my Windows password
  6 I''ve got the message with or without Firewall "Firewall detected: A firewall is blocking file Sharing between Windows and the containers. See documentation for more info". Documentation don't help, I tried all

**Comment by andrdru** [comment]
Same issue after update windows to 1709 (16299.125)
Firewall is disabled, so I don't get any notifications. Drives not sharing regular way.

Docker diagnostic id:
D8B85783-1FD2-468B-9D4B-41681073A291/2018-01-04_00-45-17

"Reset" -> "Reset to factory defaults..." fix this in my case.

**Comment by krl91** [comment]
Thank you andrdru,
I also tryied to do a "Reset to factory defaults..;" but it didn't fix my case.
New Diagnostic ID: 23189DF0-62D0-45EA-AD46-E69B8A1F312A/2018-01-04_11-12-56

**Comment by j0hnth0m** [comment]
Having the same issue trying to use linux containers on Windows 10.

Try all of following guidence listed here: https://success.docker.com/article/Error-_A_firewall_is_blocking_file_sharing_between_Windows_and_the_containers

A diagnostic was uploaded with id: 924DB5F0-00BE-48E1-A308-8662CDF05E04/2018-01-09_10-52-29.

Resetting to factory defaults did not fix the issue.

**Comment by krl91** [comment]
Ok I solve the problem: bitdefender (enterprise version) changed somithing in the firewall. Now it works well
