### ISSUE TITLE
unable to install docker in windows 10

### ISSUE THREAD

**Issue by loganathan1983** [docker/for-win#1483]
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. download and install docker community version for windows,
  2. straight away telling the popup not supported in windows home edition. I installed virtual box also. anyway to install in my laptop.?

**Comment by KLD** [comment]
did u find a way?
