### ISSUE TITLE
Stack Overlay Network Subnet Creation Doesn't Exclude Host's Subnet(s)

### ISSUE THREAD

**Issue by Vacant0mens** [docker/for-win#1484]
### Expected behavior
Upon creation of a stack, the `[stackname]_default` network subnet should not be assigned to the same subnet as the host's physical connection, nor should the stack network's subnet be included in the host's subnet.

### Actual behavior
`[stackname]_default` network sometimes will be assigned the same subnet as the host's external network subnet, or as a subnet that is included in the host's subnet. This upsets routing between the applications/containers and external resources (like a database) because a potential duplicate IP would be available inside the stack, and would respond first to a `WHO HAS [IP]` request from the application.

### Information
To avoid routing problems, a dynamically-created stack/overlay network should avoid setting the stack network subnet to be the same as or included in the any of the host's subnets.

This is as of Windows Server 1709 updated to December's patches, and Docker version 17.06.2-ee-6.

### Steps to reproduce the behavior

  1. create a stack using compose file with no specified settings for networking
  2. deploy stack
  3. on the host run: `docker service inspect [stackname]_[servicename]` under `"VirtualIPs"`
  4. also on the host, run: `ipconfig`

when the host's `Ethernet0` adapter is set like this (`ipconfig`):
```
   IPv4 Address. . . . . . . . . . . : 10.0.230.162
   Subnet Mask . . . . . . . . . . . : 255.255.0.0
```
The subnet setting is not available via `docker network inspect [stackname]_default` when the network is created automatically (which it should be), but `docker container inspect [containercreatedbystack]` shows:
```
            "Networks": {
                "125app_default": {
                    "IPAMConfig": {
                        "IPv4Address": "10.0.0.85"
                    },
---snip---
                    "Gateway": "",
                    "IPAddress": "10.0.0.85",
                    "IPPrefixLen": 24,
---snip---
                }
            }
```
and `docker service inspect [stackname]_[servicename]` shows:
```
            "VirtualIPs": [
                {
                    "NetworkID": "sg7ly5mtrpnhzvavfaytxsn0c",
                    "Addr": "10.0.0.5/24"
                }
            ]
```

**Comment by Vacant0mens** [comment]
ping @jasonbivins

**Comment by coltonbh** [comment]
Same issue on AWS using a docker stack. Our EC2 instance running docker is at 10.0.2.5/16 and the RDS db instance is at 10.0.3.xx. When I create an overlay network with docker the subnet sometimes gets assigned to 10.0.3.0/16 and then any containers on that network can't access the db as they look on their local network for the 10.0.3.xx host and can't find it. I've had to manually define the subnets for all networks used in the stack to be something other than 10.0.0.0/16. Would be great if docker could omit subnets in use on the machine so overlay networks don't inadvertently pick up the same subnet as outside resources and block access to containers on that overlay.

**Comment by Littlejd1997** [comment]
+1

**Comment by Vacant0mens** [comment]
I'm really curious why this wasn't part of the original design. Network conflicts are a pretty standard problem.

**Comment by coltonbh** [comment]
@Vacant0mens - That will work. Thanks for the janky patch. But as soon as you run docker system prune (or any other variant to clean up unused containers/networks/etc..) you'll blow away the network. Running `prune` commands is a pretty basic part of maintaining the docker engine so it's a shame to loose that. Mostly noting this so it's clear there's no good solution to this issue yet that doesn't break other functionality in docker.

**Comment by Vacant0mens** [comment]
Ah, yes. that's true. didn't think about that. 
I'm only ever using Stacks, so i've only ever been running `container prune` or `image prune`. 
How many `* prune` commands are there anyway?

**Comment by jasonbivins** [comment]
When you create the network - add a label of something like dont prune or don't delete
Then when you run the prune commands - use the label != flag to skip it when you prune
`docker network prune --filter label!= dontpruneme`

**Comment by Vacant0mens** [comment]
@jasonbivins is there a fix in the works for this?

**Comment by rn** [comment]
This issue tracker is for the Docker for Windows application, which runs on Windows 10. To get help with Docker on Windows Server please see http://success.docker.com/article/where-to-get-help-with-windows.
Thanks

**Comment by Vacant0mens** [comment]
@rn this doesn't seem like it's isolated to Windows Server. It seems like a functional problem in libnetwork inside Docker. @Littlejd1997 said he sees this problem on Linux as well. Also, i referenced a proposal for blacklisting IP ranges earlier, so it would be inappropriate to close this issue until that proposal is resolved.

**Comment by robertofabrizi** [comment]
This is nasty and in no way restricted to Windows, it happens on CentOS 7.4 on my Azure machines too. From this docker-compose.yml: 

 ```
 my-service:
    image: mycr.azurecr.io/my-img:2.5.0.6
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - type: volume
        source: my-conf
        target: /opt/docker/conf
        volume:
          nocopy: true
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - my-overlay-network
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "20"
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
networks:
  my-overlay-network:
```
    
Guess what subnet is used when deploying that via docker stack? That this overlay is created:
```
"IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.0.0/24",
                    "Gateway": "10.0.0.1"
                }
            ]
        },
        ...
        "Peers": [
            {
                "Name": "089040bebfc1",
                "IP": "10.0.0.4"
            },
            {
                "Name": "c2c0807b298e",
                "IP": "10.0.0.5"
            }
        ]
```

So the overlay network uses the subnet 10.0.0.0/24, but as you can see the two Azure VMs are on that exact same subnet, so a container might get the ip 10.0.0.4, which is actually one of the host's ip.

Docker version 18.03.1-ce, build 9ee9f40

**Comment by cabloo** [comment]
@robertofabrizi @Vacant0mens you guys are on the wrong issue tracker then, only bugs specific to Docker **for Windows** should be reported here.

**Comment by Vacant0mens** [comment]
@cabloo , if you read my original post, you'd see that i originally posted in the correct tracker. However, you're right that this issue has expanded to cover other sections of the `/docker` github project.

There is already a related issue open in `/docker/libnetwork` [here](https://github.com/docker/for-win/issues/1476) but it doesn't quite cover the scope of the issue. My complaint is that Docker should just automatically exclude the host's subnet, but it doesn't. And from the comments on this issue as well as the one i linked, it's becoming a bigger and bigger problem.
