### ISSUE TITLE
Docker stuck in starting state

### ISSUE THREAD

**Issue by kapil-ms** [docker/for-win#1485]
### Expected behavior
Docker starts normally

### Actual behavior
Docker stuck in starting state

### Information

  - Diagnostic ID - 5FCA997A-E879-44D9-846C-3A47BB231D03/2018-01-03_16-28-33
  - Windows 10 Enterprise, Version 1709, Build 16299.125

### Steps to reproduce the behavior

  1. Start Docker

**Comment by jasonbivins** [comment]
Hi @kapil-ms 

I see WMI and VMMS errors in the logs, try restarting Windows and then trying again.  You might have to re-run the installer after the reboot

**Comment by Mohjive** [comment]
I have the same issue of Docker stuck in starting. I have uninstalled and installed docker several times, and disabled->rebooted->enabled->rebooted containers and hyper-v in-between, without success.

- Diagnostic ID: CE301292-97BC-4C39-8D2F-57C208534839/2018-02-05_17-32-07
- Windows 10 Professional, Version 1709, Build 16299.192

**Comment by rlyawesome** [comment]
I also have the same issue on Win 10 Pro. I have looked through other issues and nobody solved it. Still waiting for a version where this problem will be fixed.

**Comment by binhudakhalid** [comment]
****

**Comment by shaulbehr** [comment]
FWIW, #metoo

**Comment by shaulbehr** [comment]
FYI, the problem on my side was an internet filtering package I had installed. When I disabled the filtering, Docker worked fine.
