### ISSUE TITLE
Unable to run containers with LCOW on Windows 10 17063

### ISSUE THREAD

**Issue by aaronpowell** [docker/for-win#1486]
I'm cross-posting this issue https://github.com/moby/moby/issues/35854 from the Moby issue register as it's likely more applicable here.

Here's the info provided by @AaronFriel:

## Description
Docker run fails on Windows 10 17063 with an error like the following:

```
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
ca4f61b1923c: Extracting [==================================================>]     985B/985B
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: failed to register layer: failed to start service utility VM (applydiff 8b4eeacde0dc4072a5918229fbb1f72220a52e3b5467d2231850e18e841162ba): container 8b4eeacde0dc4072a5918229fbb1f72220a52e3b5467d2231850e18e841162ba_svm encountered an error during CreateContainer: failure in a Windows system call: Not enough memory resources are available to complete this operation. (0xe) extra info: {"SystemType":"container","Name":"8b4eeacde0dc4072a5918229fbb1f72220a52e3b5467d2231850e18e841162ba_svm","Layers":null,"HvPartition":true,"HvRuntime":{"ImagePath":"C:\\Program Files\\Linux Containers","LinuxInitrdFile":"initrd.img","LinuxKernelFile":"bootx64.efi"},"ContainerType":"linux","TerminateOnLastHandleClosed":true,"MappedVirtualDisks":[{"HostPath":"C:\\ProgramData\\Docker\\lcow\\lcow\\scratch\\8b4eeacde0dc4072a5918229fbb1f72220a52e3b5467d2231850e18e841162ba.vhdx","ContainerPath":"/tmp/scratch","CreateInUtilityVM":true,"AttachOnly":false}]}.
```

I have 30+ GB of free memory, so I suspect this error is incorrect.

## Steps to reproduce the issue:

1. Install Windows 10 insider build 17063
2. ???
3. `docker run -it --rm hello-world`

## Describe the results you received:

An error containing the string "failure in a Windows system call: Not enough memory resources are available to complete this operation."

## Describe the results you expected:

No error.

## Additional information you deem important (e.g. issue happens only occasionally):

I have the following optional features installed which may impact the bug:

* Containers
* Hyper-V
* Windows Defender Application Guard

## Output of `docker version`:

```
Client:
 Version:       17.12.0-ce-rc3
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    80c8033
 Built: Thu Dec 14 00:39:41 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.12.0-ce-rc3
  API version:  1.35 (minimum version 1.24)
  Go version:   go1.9.2
  Git commit:   80c8033
  Built:        Thu Dec 14 00:49:52 2017
  OS/Arch:      windows/amd64
  Experimental: true
```

## Output of `docker info`:

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 9
Server Version: 17.12.0-ce-rc3
Storage Driver: windowsfilter (windows) lcow (linux)
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17063 (17063.1000.amd64fre.rs_prerelease.171213-1610)
Operating System: Windows 10 Enterprise Insider Preview
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 47.89GiB
Name: Ziggurat
ID: TK72:ZTYN:PHJI:GSHZ:KAUW:LJKJ:VSBI:E7JO:WT33:YIKJ:VCQL:XMXA
Docker Root Dir: C:\ProgramData\Docker\lcow
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 28
 System Time: 2017-12-20T17:50:44.268761-06:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

## Additional environment details (AWS, VirtualBox, physical, etc.):

OS: Windows 10 Enterprise
CPU: Core i7-6700k (no overclock)
Memory: 48GB

**Comment by aaronpowell** [comment]
I've been trying to investigate this myself as well. I'm wanting to test older Docker Edge builds so that I can see if I can determine when the issue was introduced, but I can't find where to download them from.

## Current work-around

Roll back to Docker Stable

**Comment by drlukeangel** [comment]
i am as well having the same issue.
A diagnostic uploaded with id: 27C5217B-32C1-4BEE-9DF3-C3B0ED913008/2018-01-04_09-56-48

**Comment by ungikim** [comment]
Insider Build 17063 has an issue running Linux containers with Docker Community Edition for Windows (edge)

<https://blogs.windows.com/windowsexperience/2017/12/19/announcing-windows-10-insider-preview-build-17063-pc/>

**Comment by aaronpowell** [comment]
Can confirm that this works in build 17083.
