### ISSUE TITLE
Error response from daemon: container 290fe4519b7a71b7035d250d2  ed9d09826f662225424f9b70dcae0e4db4b2675 encountered an error during CreateContainer: failure in a Windows system call: A  connection could not be established with the Virtual Machine hosting the Container. (0xc0370108)

### ISSUE THREAD

**Issue by Angr1st** [docker/for-win#1489]
### Expected behavior
Container starts running.

### Actual behavior
Error Message : 

> C:\Program` Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container 290fe4519b7a71b7035d250d2
> 
> ed9d09826f662225424f9b70dcae0e4db4b2675 encountered an error during CreateContainer: failure in a Windows system call: A
> 
> connection could not be established with the Virtual Machine hosting the Container. (0xc0370108) extra info: {"SystemTy
> 
> pe":"Container","Name":"290fe4519b7a71b7035d250d2ed9d09826f662225424f9b70dcae0e4db4b2675","Owner":"docker","IgnoreFlushe
> 
> sDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\290fe4519b7a71b7035d250d2ed9d09826f66222542
> 
> 4f9b70dcae0e4db4b2675","Layers":[{"ID":"cdb6bbee-87f5-5ab0-92df-283e25d82f81","Path":"C:\\ProgramData\\Docker\\windowsfi
> 
> lter\\4ca81a668c1fcccfc4fcb3a8c5873997e030b51f2a5017e53eb7967616a1e3f2"},{"ID":"c7712b56-a7e6-54e6-a3ca-e6ba76403590","P
> 
> ath":"C:\\ProgramData\\Docker\\windowsfilter\\5c0b1c5010da5560002515a4f7c44300a29d3a19a300863b37e33390c7fa1c8a"},{"ID":"
> 
> 1cc06fd7-56c3-5ada-b303-0f63180cd76e","Path":"C:\\ProgramData\\Docker\\windowsfilter\\a45f3e8f16e24de1c37c41f525e2a86dd1
> 
> b75df33f3b98c8a1a149db48c36f77"},{"ID":"23b21021-b021-5b61-ab5d-f6e46e07b468","Path":"C:\\ProgramData\\Docker\\windowsfi
> 
> lter\\c85daec844e90893c8dbb82b739d09dc525dbc9583a0d6a8a1c382edf53a869b"},{"ID":"14672112-1eb3-56fc-90b4-ee35987e11a8","P
> 
> ath":"C:\\ProgramData\\Docker\\windowsfilter\\64db7de996fb988c9fb64cfcc877acf377d351bac72dc471f32057416879c63b"},{"ID":"
> 
> d0b1265f-aeb7-596c-bac3-56895988731f","Path":"C:\\ProgramData\\Docker\\windowsfilter\\a834dd38a9f87b810cda526025c8ac26b9
> 
> 37f96ae50210e3dad2faea1c59cbca"},{"ID":"eddc1f0d-c176-57ff-9174-044b1f89b3c1","Path":"C:\\ProgramData\\Docker\\windowsfi
> 
> lter\\16ce3740dd9ffa3cda674f0aa8c4177b823c8b14fe65d43507003bd18b00ec44"},{"ID":"eb201821-5679-5e3e-9f10-ab07c5a1a6ac","P
> 
> ath":"C:\\ProgramData\\Docker\\windowsfilter\\5073d90fb69cf4c45956b634d191bcda59d88b18144263459677fa713a81d95d"},{"ID":"
> 
> 99080140-bf41-5707-a817-d27f7cfc9c75","Path":"C:\\ProgramData\\Docker\\windowsfilter\\9e7a400277a31a733794e04e2e82fffc2c
> 
> a6ad2359d478d982e7160783f5723e"},{"ID":"5f983a21-97ae-5f21-a16c-f18fad54411f","Path":"C:\\ProgramData\\Docker\\windowsfi
> 
> lter\\cae7aa5900408a1ba408f8b5c4cf652ac1b79f464ad951f24543e57a9264a6a0"},{"ID":"7deaea59-54d6-58ef-800f-7a332de5ac85","P
> 
> ath":"C:\\ProgramData\\Docker\\windowsfilter\\97a23eca75e5b8200e9f9c55ea76a6c9b4cce33dd95fefa947007898abb5b3a5"},{"ID":"
> 
> 5e918267-ed63-5269-aff4-94293541fc3f","Path":"C:\\ProgramData\\Docker\\windowsfilter\\301b43e8a15d10fdc0a2cb55c59f1d4042
> 
> f946a92ad784d697d3ad5e6a16e84e"},{"ID":"e6a24662-912a-5775-bb57-d6d08f819390","Path":"C:\\ProgramData\\Docker\\windowsfi
> 
> lter\\5b6e5fc28eb4e347d788ea0558f476104138c0cbb9fbfd4fe5ef27e3731c6cff"},{"ID":"9d7eed28-9053-5f49-8ac9-5b18a845519d","P
> 
> ath":"C:\\ProgramData\\Docker\\windowsfilter\\f160f0b752e856d7b73161353c2f927692e7c96038b79feaf8920d812f9a2536"},{"ID":"
> 
> 732c9d97-1ddf-551f-9a7b-06d9f4634755","Path":"C:\\ProgramData\\Docker\\windowsfilter\\fc21432369d6f2f9dadeab4469f05f4d02
> 
> 6a60b8686060c49b6334cc8e093e4b"},{"ID":"c2adc53f-095a-554f-ae0f-e6535229b538","Path":"C:\\ProgramData\\Docker\\windowsfi
> 
> lter\\1e566ca6b4dc2061898444a1f4e914e4583fd841494cfbdf7aa195b92e6f56fa"},{"ID":"6b6bcc88-ad48-5262-b5c5-8093f1dcdcb2","P
> 
> ath":"C:\\ProgramData\\Docker\\windowsfilter\\ce1014fcb242b1e6c4068e18fcda75ab953414ae159806ea6d733d4412348772"},{"ID":"
> 
> 9138fdda-f771-5365-8e59-7171704d24fa","Path":"C:\\ProgramData\\Docker\\windowsfilter\\1d8c64c016887d0221dc30615902b7a945
> 
> 7a773bf74e22f7817bd76f3cccea21"},{"ID":"2a28943b-e30c-53a9-86a3-a4b22aac8757","Path":"C:\\ProgramData\\Docker\\windowsfi
> 
> lter\\3443a75be692bb5b831fa136671e8a7cbcc080b9a1add803d1577f4d789955ab"},{"ID":"aaebc26a-5eb8-57a1-bc2b-def69853af00","P
> 
> ath":"C:\\ProgramData\\Docker\\windowsfilter\\48988331d0cf706a1179165a25eaee75e4c4169cfd15fc4a77be0b3f20bebb33"},{"ID":"
> 
> f7bede04-b5e1-5b66-9d76-88fd471ff5c4","Path":"C:\\ProgramData\\Docker\\windowsfilter\\98f06ea4c780c281b25d081ee642cbc1fb
> 
> fa0077b6bfe0c027d53e47bbed4a80"}],"MemoryMaximumInMB":3072,"HostName":"290fe4519b7a","MappedDirectories":[{"HostPath":"d
> 
> :\\es-data","ContainerPath":"c:\\data","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}]
> 
> ,"HvPartition":true,"EndpointList":["0b48b8b6-2dfb-42f4-a533-ae586bfce73e"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\D
> 
> ocker\\windowsfilter\\48988331d0cf706a1179165a25eaee75e4c4169cfd15fc4a77be0b3f20bebb33\\UtilityVM"},"AllowUnqualifiedDNS
> 
> `Query":true}.

`
### Information
I build this Docker Image using VSTS and the Hosted Queue VS2017. I am trying to get Elasticsearch running inside a Windows Container and get this Container running on a Azure Windows VM.

> OS Name	Microsoft Windows Server 2016 Datacenter	
> Version	10.0.14393 Build 14393

 If I build this Image using VSTS and my local Desktop as build agent It runs on my machine. 

> OS Name	Microsoft Windows 10 Education	
> Version	10.0.16299 Build 16299	

Diagnostic ID 4FAC9FC8-0D10-47E6-B2DE-2E244DD5A6BA/2018-01-04_15-09-14

[Dockerfile](https://github.com/Angr1st/elasticsearch-windows/blob/master/elasticsearch/windowsservercore/Dockerfile) used: 

```
 # escape=`
 FROM openjdk:8-jdk-windowsservercore-ltsc2016
 SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
 
 # Elasticsearch
 ENV ES_VERSION="6.1.1" `
     ES_SHA1="58c90d988adac0b00ea4f2936aaae96fae63a2f00c2c1617efe53f86eccad669f92f7cec691dde81592ff3228922f98619289af103e125bf9c2ad6e1f7c16700" `
     ES_HOME="C:\elasticsearch"
 
 RUN Invoke-WebRequest -outfile elasticsearch.zip "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$($env:ES_VERSION).zip" -UseBasicParsing; `
     #if ((Get-FileHash elasticsearch.zip -Algorithm sha1).Hash -ne $env:ES_SHA1) {exit 1} ; `
     Expand-Archive elasticsearch.zip -DestinationPath C:\ ; `
     Move-Item c:/elasticsearch-$($env:ES_VERSION) $env:ES_HOME; `
     Remove-Item elasticsearch.zip
 
 VOLUME C:\data
 
 # REMARKS - DNS and mount tweaks needed for Windows
 RUN Set-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters' -Name ServerPriorityTimeLimit -Value 0 -Type DWord; `
     Set-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\DOS Devices' -Name 'G:' -Value '\??\C:\data' -Type String    
 
 HEALTHCHECK --interval=5s `
  CMD powershell -command `
     try { `
      $content = (iwr -useb http://localhost:9200/_cat/health).Content; `
      $health = $content.Split(' ')[3]; `
      if ($health -eq 'green' -or $health -eq 'yellow') { return 0 } `
      else { return 1 }; `
     } catch { return 1 }
     
EXPOSE 9200 9300
WORKDIR C:\elasticsearch
COPY config ./config
 
SHELL ["cmd", "/S", "/C"]
CMD ".\bin\elasticsearch.bat"
```

Docker Info:

> Containers: 1
> 
> Running: 0
> 
> Paused: 0
> 
> Stopped: 1
> 
> Images: 4
> 
> Server Version: 17.09.1-ce
> 
> Storage Driver: windowsfilter
> 
> Windows:
> 
> Logging Driver: json-file
> 
> Plugins:
> 
> Volume: local
> 
> Network: ics l2bridge l2tunnel nat null overlay transparent
> 
> Log: awslogs etwlogs fluentd json-file logentries splunk syslog
> 
> Swarm: inactive
> 
> Default Isolation: process
> 
> Kernel Version: 10.0 14393 (14393.1944.amd64fre.rs1_release.171129-2100)
> 
> Operating System: Windows Server 2016 Datacenter
> 
> OSType: windows
> 
> Architecture: x86_64
> 
> CPUs: 2
> 
> Total Memory: 8GiB
> 
> Name: emea-app-005
> 
> ID: B2Q6:NZRZ:JWU4:TTMY:BK6R:T2WD:SNCH:2YRA:E7K2:CKSS:ZK7W:QCII
> 
> Docker Root Dir: C:\ProgramData\Docker
> 
> Debug Mode (client): false
> 
> Debug Mode (server): true
> 
> File Descriptors: -1
> 
> Goroutines: 23
> 
> System Time: 2018-01-04T16:09:41.54109Z
> 
> EventsListeners: 0
> 
> Registry: https://index.docker.io/v1/
> 
> Experimental: true
> 
> Insecure Registries:
> 
> 127.0.0.0/8
> 
> Live Restore Enabled: false

### Steps to reproduce the behavior

1. open powershell 
2, run command : docker run -d -p 9200:9200 -p 9300:9300 -m 3GB --name elasticsearch angr1st/elasticsearch-windows:78

**Comment by Angr1st** [comment]
I just wanted to add that after changing the build server to a Windows Server 2016 Machine it worked on the Azure VM adding one GB of memory.
After updating to 17.12.0-ce-win47 (15139). My Container stopped running again but with no real error.
My guess is that it had to do with this [Version Compatibility](https://docs.microsoft.com/de-de/virtualization/windowscontainers/deploy-containers/version-compatibility)

**Comment by rn** [comment]
This issue tracker is for the Docker for Windows application, which runs on Windows 10. To get help with Docker on Windows Server please see http://success.docker.com/article/where-to-get-help-with-windows.

Also, this looks like a potential issue with the upstream docker windows container implementation so I'm closing this issue. You may also open an issue on https://github.com/moby/moby instead as that is the more appropriate place.
Thanks
