### ISSUE TITLE
Sharing a volume with multiple containers not working

### ISSUE THREAD

**Issue by billhab** [docker/for-win#149]
### Expected behavior
Container A and Container B, running at the same time, share the same Java home volume. 

### Actual behavior
Container A mounts the volume successfully and Java home can be used.
Container B mounts the volume but access to Java home results in directory not found. 

### Information
   - Docker Beta 27
   - host distribution and version (Windows version, build number, etc)
    Windows 10 Pro

### Steps to reproduce the behavior

From Java API
1. Create container A with mount to Java home on the host. 
2. Create container B with mount to Java home on the host. 
3. Start container A to run a script which does a java -version. 
4. Start container B to run a script which does a java -version
5. Container A works. 
6. Container B failed with directory/file not found.

**Comment by simonferquel** [comment]
Hi,
Could you provide a list of command lines for the repro ?

**Comment by billhab** [comment]
This was all done in Java code.  I changed the code to minimize the mounts and it started working.  Is there a limit to the number of mounts per container or a limit on the total number?

**Comment by friism** [comment]
@billhab no, I don't think there's a limit on the number of mounts.

If you have time, it'd be useful if you could provide a repro just using Docker commands. This will rule out issues with Java, and will help us debug.

**Comment by simonferquel** [comment]
Seems to me the problem came from the Java code and not from Docker for Windows. I've marked the issue as "Will be closed" so if we don't receive more feedback on this, we'll close it in a few days

**Comment by dgageot** [comment]
Sorry, I'm going to close the issue as it seems more like an issue with code than with D4W. Feel free to reopen in case there's still an issue!
