### ISSUE TITLE
Cannot access google related sites when Docker for Windows is running (network slow)

### ISSUE THREAD

**Issue by amdoyle1047** [docker/for-win#1490]
### Expected behavior
I should be able to access my gmail accounts and google docs accounts and all other google sites
### Actual behavior
My browser(s) will time out when Docker for Windows is running and I am trying to access any google related site such as my email, google docs, google search, etc.
### Information
This happens from all browsers. When I kill Docker For Windows process, I get access to all the google related sites back.
  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. Start Docker for Windows as administrator or not as administrator
  2. Try to go to https://www.google.com or any google related site like gmail, google docs, etc and the sites timeout

**Comment by jasonbivins** [comment]
Hi @amdoyle1047 
What do you have under Network settings in the GUI for DNS?   
![image](https://user-images.githubusercontent.com/28021664/34624822-9d02b55a-f224-11e7-968f-2c44414d14c4.png)

**Comment by amdoyle1047** [comment]
What it turned out to be causing the routing issues, is a permanent route
created in power shell. It routed to Docker 10.0.75.0, but was causing
routing issues on a few developers laptops. When docker was running, the
network issues started to happen. We first deleted the permanent route, and
the network problems with Docker running went away. But, our system engine
created a new permanent route for us to create, with a better submask, that
does not cause issues when running Docker. So, the problem is solved now.
It was not really a Docker issue after all. It was the permanent route we
created to go to Docker.

Annette Doyle
