### ISSUE TITLE
LCOW Unable to create transparent network

### ISSUE THREAD

**Issue by BrianAdams** [docker/for-win#1492]
I was not able to create a transparent network, getting the parameter is incorrect message instead.  Eventually it just worked once.  I deleted the network and attempted to recreate it again. Tried using a different name for the network. Neither attempt would work.

### Expected behavior
When creating a transparent network, the system should return the id for the created network

### Actual behavior
`Error response from daemon: HNS failed with error : The parameter is incorrect.`

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
` 223BC9C0-EB44-461A-A58F-F3A0A2B4C38C/2018-01-05_08-26-19`

  - host distribution and version (Windows version, build number, etc)
Windows 10 Pro: Version	10.0.16299 Build 16299

### Steps to reproduce the behavior

  1. `docker network create -d transparent tlan`

**Comment by jasonbivins** [comment]
Hi @BrianAdams 
Usually this means that there is a duplicate network, or some orphan pointers that weren't deleted with an old network.  MS has a script here that will clean those up, but please be advised that this will delete  non-system networks that have been created. https://github.com/MicrosoftDocs/Virtualization-Documentation/tree/live/windows-server-container-tools/CleanupContainerHostNetworking

**Comment by BrianAdams** [comment]
Tried running the CleanupContainerHostNetwork script.  Did not help in the ability to create a transparent network.  Did put the networking in the odd state with a null adapter.

In standard docker mode:
>C:\Users\brian>docker network ls
```
NETWORK ID          NAME                DRIVER              SCOPE
77be5c33e98e        bridge              bridge              local
484a006877e8        host                host                local
38a0c658fa48        none                null                local
```

in lcow mode:
```
NETWORK ID          NAME                DRIVER              SCOPE
20561d4c3c5d        Default Switch      ics                 local
4972aadbdeec        nat                 nat                 local
24d6ef6e0922        none                null                local
```
