### ISSUE TITLE
Cannot login to insecure registry in windows

### ISSUE THREAD

**Issue by steve-thibault** [docker/for-win#1493]
### Expected behavior
docker login docker_registry_test.er-docker-privatereg:80
Username: icsbuildmanager
Password: 
Login Succeeded

### Actual behavior
 docker login http://docker_registry_test.er-docker-privatereg:80
Username: icsbuildmanager
Password:
Error response from daemon: Get https://docker_registry_test.er-docker-privatereg:80/v2/: http: server gave HTTP response to HTTPS client
### Information
Diagnostic ID: 5060D042-F737-48CC-A119-DF2B7B77DA23/2018-01-05_15-24-19
  - Diagnostic ID from "Diagnose & Feedback" in the menu.

Install docker for windows stable as of 5-Jan-2018
Configure an insecure registry
add that registry to all of the docker daemon.json files on the system, including under ProgramData\docker\config and userprofile\.docker\

Restart docker
Try to login to the insecure registry.

  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jasonbivins** [comment]
Hi @steve-thibault 
What shows up here in the GUI under Settings > Daemon

![image](https://user-images.githubusercontent.com/28021664/34744538-89bc15b0-f55b-11e7-9f45-4d43d4e1631f.png)

**Comment by steve-thibault** [comment]
I had to blow up the system since I sent the support request. I had 
colleagues that ran into issues and after recreating the windows 10 
system, things were better for them, I can say the same. Not perfect, but 
better. I get time-outs starting the daemon now sometimes, and I'm trying 
to build the image again.

Can we keep this dialog open as I try to get the image created?

Steve

Steve Thibault  
Sr. Software Engineer  


[T] 508-482-4171  
[F] +1 508 482 3373  
[M] 508-377-8336  
[W] www.waters.com
[E] steve_thibault@waters.com
Waters Corporation  
34 Maple Street  
Milford  
MA 01757  
USA
