### ISSUE TITLE
could not start docker on windows 10 from Macbook pro

### ISSUE THREAD

**Issue by allenpansoftware** [docker/for-win#1495]
### Expected behavior
Start Docker on Windows 10 
### Actual behavior
Docker pop up an error message says: Hardware assisted virtualization and data execution protection must be enabled in the BIOS. See https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization-must-be-enabled
### Information
My Hyper-V is enabled for windows 10 on Macbook pro(2017 version). I don't think the error message make sense for my case.

  - Diagnostic ID from "Diagnose & Feedback" in the menu. 
Diagnostic Id: 4ED4AA0B-3CB3-4818-9207-C2D887A259B6/2018-01-08_16-53-39

  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ... boot windows 10 from bootcamp
  2. ...Start Docker ... error message occurs.

**Comment by jasonbivins** [comment]
Hi @allenpansoftware 
Can you start and then connect to any VM's other than the MobyLinux VM in Hyper-V  ?

**Comment by kadircanercetin** [comment]
Hi I got the same error.
My System informations ;  windows 10 (bootcamp) on Macbook pro(2017 version).

![capture](https://user-images.githubusercontent.com/5362679/34950148-3b8504ca-fa0a-11e7-9807-6267571568db.JPG)

**Comment by Coldwine** [comment]
This issue is still a problem. Hyper-V is not the problem here, but Virtualization, which needs to be enabled in Bios, which is kind of a Problem on Macbooks.
