### ISSUE TITLE
One pre-requisite is not fullfilled (Windows 10 Pro version 10586) - when it actually is fullfilled

### ISSUE THREAD

**Issue by bkaminnski** [docker/for-win#1498]
### Expected behavior

Docker for Windows installs correctly.

### Actual behavior

Docker for Windows does not install with a message: "Docker for Windows requires Windows 10 Pro or Enterprise version 10586, or Windows server 2016 RTM to run". I have Windows 10 Pro, 10586 build.

### Information
This is the result of running "Get-WmiObject Win32_OperatingSystem | fl *" in PowerShell in Admin mode. 

Most important parts:

```
Name                                      : Microsoft Windows 10 Pro|C:\WINDOWS|\Device\Harddisk0\Partition2
BuildNumber                               : 10586
```

Full output ("XXXXXXXXXXXX" in places I do not want to share):

```
PSComputerName                            : XXXXXXXXXXXX
Status                                    : OK
Name                                      : Microsoft Windows 10 Pro|C:\WINDOWS|\Device\Harddisk0\Partition2
FreePhysicalMemory                        : 11781612
FreeSpaceInPagingFiles                    : 4980736
FreeVirtualMemory                         : 16323472
__GENUS                                   : 2
__CLASS                                   : Win32_OperatingSystem
__SUPERCLASS                              : CIM_OperatingSystem
__DYNASTY                                 : CIM_ManagedSystemElement
__RELPATH                                 : Win32_OperatingSystem=@
__PROPERTY_COUNT                          : 64
__DERIVATION                              : {CIM_OperatingSystem, CIM_LogicalElement, CIM_ManagedSystemElement}
__SERVER                                  : PCBAKA
__NAMESPACE                               : root\cimv2
__PATH                                    : \\PCBAKA\root\cimv2:Win32_OperatingSystem=@
BootDevice                                : \Device\HarddiskVolume1
BuildNumber                               : 10586
BuildType                                 : Multiprocessor Free
Caption                                   : Microsoft Windows 10 Pro
CodeSet                                   : 1250
CountryCode                               : 48
CreationClassName                         : Win32_OperatingSystem
CSCreationClassName                       : Win32_ComputerSystem
CSDVersion                                :
CSName                                    : XXXXXXXXXXXX
CurrentTimeZone                           : 60
DataExecutionPrevention_32BitApplications : True
DataExecutionPrevention_Available         : True
DataExecutionPrevention_Drivers           : True
DataExecutionPrevention_SupportPolicy     : 2
Debug                                     : False
Description                               :
Distributed                               : False
EncryptionLevel                           : 256
ForegroundApplicationBoost                : 2
InstallDate                               : 20160723005318.000000+120
LargeSystemCache                          :
LastBootUpTime                            : 20180108155844.484562+060
LocalDateTime                             : 20180108162100.010000+060
Locale                                    : 0415
Manufacturer                              : Microsoft Corporation
MaxNumberOfProcesses                      : 4294967295
MaxProcessMemorySize                      : 137438953344
MUILanguages                              : {en-US}
NumberOfLicensedUsers                     : 0
NumberOfProcesses                         : 157
NumberOfUsers                             : 5
OperatingSystemSKU                        : 48
Organization                              : XXXXXXXXXXXX
OSArchitecture                            : 64-bit
OSLanguage                                : 1033
OSProductSuite                            : 256
OSType                                    : 18
OtherTypeDescription                      :
PAEEnabled                                :
PlusProductID                             :
PlusVersionNumber                         :
PortableOperatingSystem                   : False
Primary                                   : True
ProductType                               : 1
RegisteredUser                            : Windows User
SerialNumber                              : 00331-20090-16546-AA267
ServicePackMajorVersion                   : 0
ServicePackMinorVersion                   : 0
SizeStoredInPagingFiles                   : 4980736
SuiteMask                                 : 272
SystemDevice                              : \Device\HarddiskVolume2
SystemDirectory                           : C:\WINDOWS\system32
SystemDrive                               : C:
TotalSwapSpaceSize                        :
TotalVirtualMemorySize                    : 21687356
TotalVisibleMemorySize                    : 16706620
Version                                   : 10.0.10586
WindowsDirectory                          : C:\WINDOWS
Scope                                     : System.Management.ManagementScope
Path                                      : \\XXXXXXXXXXXX\root\cimv2:Win32_OperatingSystem=@
Options                                   : System.Management.ObjectGetOptions
ClassPath                                 : \\XXXXXXXXXXXX\root\cimv2:Win32_OperatingSystem
Properties                                : {BootDevice, BuildNumber, BuildType, Caption...}
SystemProperties                          : {__GENUS, __CLASS, __SUPERCLASS, __DYNASTY...}
Qualifiers                                : {dynamic, Locale, provider, Singleton...}
Site                                      :
Container                                 :
```

### Steps to reproduce the behavior

  1. Download latest stable or edge release (downloaded just before issuing the problem) from https://store.docker.com/editions/community/docker-ce-desktop-windows
  2. Run installer
  3. Installation fails with the reported message.

**Comment by jasonbivins** [comment]
Hi @bkaminnski  
Docker actually requires Windows build 14393 or greater - we're working on the typo in the installer gui, but you'll need to update your Windows to proceed.
https://docs.docker.com/docker-for-windows/install/#what-to-know-before-you-install

**Comment by lucasrangit** [comment]
Is "Windows 10 Home" still not supported?

**Comment by thakurarun** [comment]
> Hi @bkaminnski
> Docker actually requires Windows build 14393 or greater - we're working on the typo in the installer gui, but you'll need to update your Windows to proceed.
> https://docs.docker.com/docker-for-windows/install/#what-to-know-before-you-install

NOT UPDATED YET.
Please correct the info. message.
![docker issue](https://user-images.githubusercontent.com/5906747/45479845-3004c900-b765-11e8-9d06-8ba7f8ad99ee.JPG)

**Comment by wisehackermonkey** [comment]
Same issue as listed in op.
What I tried. 
- enabling hyper-v to see if that changed anything. no change.
- updating windows (the version in photo is my updated version)
Any thoughts?

---
photo of my system and the error
![](https://i.imgur.com/G8ua9B3.png)

Results of command "Get-WmiObject Win32_OperatingSystem | fl *" as described in op.

PSComputerName                            : ORAN
Status                                    : OK
Name                                      : Microsoft Windows 10 Home|C:\WINDOWS|\Device\Harddisk0\Partition3
FreePhysicalMemory                        : 4047540
FreeSpaceInPagingFiles                    : 1310720
FreeVirtualMemory                         : 4925388
__GENUS                                   : 2
__CLASS                                   : Win32_OperatingSystem
__SUPERCLASS                              : CIM_OperatingSystem
__DYNASTY                                 : CIM_ManagedSystemElement
__RELPATH                                 : Win32_OperatingSystem=@
__PROPERTY_COUNT                          : 64
__DERIVATION                              : {CIM_OperatingSystem, CIM_LogicalElement, CIM_ManagedSystemElement}
__SERVER                                  : ORAN
__NAMESPACE                               : root\cimv2
__PATH                                    : \\ORAN\root\cimv2:Win32_OperatingSystem=@
BootDevice                                : \Device\HarddiskVolume1
BuildNumber                               : 17134
BuildType                                 : Multiprocessor Free
Caption                                   : Microsoft Windows 10 Home
CodeSet                                   : 1252
CountryCode                               : 1
CreationClassName                         : Win32_OperatingSystem
CSCreationClassName                       : Win32_ComputerSystem
CSDVersion                                : 
CSName                                    : ORAN
CurrentTimeZone                           : -480
DataExecutionPrevention_32BitApplications : True
DataExecutionPrevention_Available         : True
DataExecutionPrevention_Drivers           : True
DataExecutionPrevention_SupportPolicy     : 2
Debug                                     : False
Description                               : laptop
Distributed                               : False
EncryptionLevel                           : 256
ForegroundApplicationBoost                : 2
InstallDate                               : 20190211170528.000000-480
LargeSystemCache                          : 
LastBootUpTime                            : 20190211212001.500000-480
LocalDateTime                             : 20190211214405.762000-480
Locale                                    : 0409
Manufacturer                              : Microsoft Corporation
MaxNumberOfProcesses                      : 4294967295
MaxProcessMemorySize                      : 137438953344
MUILanguages                              : {en-US}
NumberOfLicensedUsers                     : 
NumberOfProcesses                         : 181
NumberOfUsers                             : 2
OperatingSystemSKU                        : 101
Organization                              : 
OSArchitecture                            : 64-bit
OSLanguage                                : 1033
OSProductSuite                            : 768
OSType                                    : 18
OtherTypeDescription                      : 
PAEEnabled                                : 
PlusProductID                             : 
PlusVersionNumber                         : 
PortableOperatingSystem                   : False
Primary                                   : True
ProductType                               : 1
RegisteredUser                            : 
SerialNumber                              : 00325-96311-29524-AAOEM
ServicePackMajorVersion                   : 0
ServicePackMinorVersion                   : 0
SizeStoredInPagingFiles                   : 1310720
SuiteMask                                 : 784
SystemDevice                              : \Device\HarddiskVolume3
SystemDirectory                           : C:\WINDOWS\system32
SystemDrive                               : C:
TotalSwapSpaceSize                        : 
TotalVirtualMemorySize                    : 9573604
TotalVisibleMemorySize                    : 8262884
Version                                   : 10.0.17134
WindowsDirectory                          : C:\WINDOWS
Scope                                     : System.Management.ManagementScope
Path                                      : \\ORAN\root\cimv2:Win32_OperatingSystem=@
Options                                   : System.Management.ObjectGetOptions
ClassPath                                 : \\ORAN\root\cimv2:Win32_OperatingSystem
Properties                                : {BootDevice, BuildNumber, BuildType, Caption...}
SystemProperties                          : {__GENUS, __CLASS, __SUPERCLASS, __DYNASTY...}
Qualifiers                                : {dynamic, Locale, provider, Singleton...}
Site                                      : 
Container                                 :

**Comment by wisehackermonkey** [comment]
Alternate Solution:

install docker toolbox

Windows 10 home doesnt come with hyper-v, only windows 10 pro,edu,...
this means my system can run the docker but i would have to upgrade to windows 10 pro. 

as mentioned here install docker toolbox instead of docker ce
https://forums.docker.com/t/installing-docker-on-windows-10-home/11722/2

TL:DR
install docker toolbox, and call it a day
https://docs.docker.com/toolbox/toolbox_install_windows/
