### ISSUE TITLE
Volume mapping making directories out of files

### ISSUE THREAD

**Issue by Zowie** [docker/for-win#1501]
### Expected behavior

A volume mapping in my `docker-compose.yml` results in the exact structure of the directory I map, being available at the specified location on the container.

### Actual behavior

There are two things I noticed that make volumes unusable.

Where test.txt is a file containing just text:

```
$ cat foo/test.txt
foo-bar
```

**First anomaly**
One is that when mapping like so:

```
volumes:
  - ./foo/test.txt:/tmp/bar/test.txt
```

This results in:

```
root@4bcddba897fb:/# ls -al /tmp/bar/
total 8
drwxr-xr-x 3 root root 4096 Jan  8 18:42 .
drwxrwxrwt 1 root root 4096 Jan  8 18:42 ..
drwxr-xr-x 2 root root   40 Jan  8 18:40 test.txt <---- this is a directory
root@4bcddba897fb:/#
```

**Second anomaly**

When mapping like this:

```
volumes:
  - ./foo/:/tmp/bar/
```

This too, results in `test.txt` being a directory:

```
root@68261d5fe72a:/# ls -al /tmp/bar/
total 4
drwxr-xr-x 3 root root   60 Jan  8 18:40 .
drwxrwxrwt 1 root root 4096 Jan  8 18:53 ..
drwxr-xr-x 2 root root   40 Jan  8 18:40 test.txt <---- this is a directory
root@68261d5fe72a:/#
```

#### Diagnostic ID from "Diagnose & Feedback" in the menu:
`593582E2-E26C-4493-B394-6D772C00E3F4/2018-01-08_10-57-37`

#### a reproducible case if this is a bug:
https://github.com/Zowie/compose-win-volume-bug

#### host distribution and version (Windows version, build number, etc):
Windows 10 Pro, Version 1709 (OS Build 16299.125)

### Steps to reproduce the behavior

  1. Clone https://github.com/Zowie/compose-win-volume-bug

  2. Test 1: Run `docker-compose run test bash`
  3. Run `ls -al /tmp/bar/`

  4. Test 2: Run `docker-compose run test2 bash`
  5. Run `ls -al /tmp/bar/`

**Comment by thaJeztah** [comment]
Do you have a shared drive set up? https://docs.docker.com/docker-for-windows/#shared-drives

Bind-mounts are created from the host where the daemon runs, which (on Docker for Windows) is inside a VM. When using the `-v <host-path>:<container-path>` option is used for a bind-mount, docker will look for `<host-path>` on the host where the daemon runs; if that path does not exist, it will create a directory on that location (as it doesn't know if you wanted to mount a _file_ or a _directory_; a _directory_ is the default).

If you don't have a shared drive set-up, docker won't be able to access that path from your host, thus won't find the path inside the VM (thus creates a directory).

To prevent docker from _creating_ the path if it cannot find it (and produce an error instead), use the `--mount` option instead of `-v`. The `--mount` flag uses a different syntax, which can be found on this page; https://docs.docker.com/engine/admin/volumes/bind-mounts/#start-a-container-with-a-bind-mount

**Comment by Zowie** [comment]
Thanks for the quick reply @thaJeztah. I have a shared drive set up indeed, and the path I'm using in the volume mapping is inside of this drive (`C`). 

I'm wondering whether what you say is applicable though 🤔 . I'm using docker compose (which seems to default to using volumes instead of mounts) and this has been fine earlier December 2017. It was only mid December that this problem started on some of the Win10 machines of my co workers.

Also, I can imagine the mapping of the file specifically (`./foo/test.txt:/tmp/bar/test.txt`) leading to the file being created as a directory like you say, since it's also created as a directory on the host machine initially because it's not found there. But how would you explain the same result when using the volume mapping `./foo/:/tmp/bar/`, leading to `test.txt` being created as a directory too? This would have to imply that `test.txt` is available on the host machine for the docker daemon since it's not explicitly defined in the volume mapping right? I also tried running `docker-compose down -v`, and then running only `docker-compose run test2 bash` (containing the directory reference only, and not to `test.txt`) to make sure I'm not dealing with any smart volume mapping logic that uses an existing volume of which the host paths overlap.

I tried reproducing it with Docker only using `docker run -it -v %cd%/foo:/tmp/bar nginx bash`, and got this result:

```
total 4
drwxr-xr-x 3 root root   60 Jan  8 18:56 .
drwxrwxrwt 1 root root 4096 Jan  8 21:16 ..
drwxr-xr-x 2 root root   40 Jan  8 18:56 test.txt <--- still a directory
root@9d8a0bbc6aea:/#
```

Also, the following command described on the `Shared Drives` section in the Docker app works for me: `docker run --rm -v c:/Users:/data alpine ls /data`. This outputs, as expected: 

```
Zowie
```

For reference, I tried doing the same on my Mac (`docker run -it -v $(pwd)/foo:/tmp/bar nginx bash`). This results in:

```
root@8c81fe42659c:/# ls -al /tmp/bar/
total 8
drwxr-xr-x 3 root root   96 Jan  8 21:13 .
drwxrwxrwt 1 root root 4096 Jan  8 21:15 ..
-rw-r--r-- 1 root root    8 Jan  8 21:13 test.txt
root@8c81fe42659c:/#
```

I might be missing something here! But the above behaviour including the fact that it has been working fine for quite a while leads me to think this is an actual issue. Tomorrow I have access to other Windows 10 machines, on which I will try to reproduce the same issue using the above commands. Will post any findings here.

**Comment by thaJeztah** [comment]
> I'm using docker compose (which seems to default to using volumes instead of mounts

In this context, I meant It's a mount if you're mounting a path from your host (I.e., not a "named volume")

If you `docker inspect` the container, do the paths in the inspect output look ok; do they match the paths on your host (including case (upper/lower)?

**Comment by Zowie** [comment]
I inspected the container after running `docker run -it -v %cd%/foo:/tmp/bar nginx bash`. This seems OK as far as I can see. But I'm not 100% sure.

The path is `/C/Users/Zowie/development/multichat/test/foo:/tmp/bar` and
`echo %cd%` returns `C:\Users\Zowie\development\multichat\test`. A discrepancy is `/C/` vs `C:\`..

The complete output of `docker inspect`:

[docker-inspect-output.txt](https://github.com/docker/for-win/files/1613190/docker-inspect-output.txt)

**Comment by Zowie** [comment]
I have tested again on another Windows 10 machine. I found the following:

When running step 1, 2, and 3 from 'Steps to reproduce the behavior', `/tmp/bar/test.txt` is a directory again. However, when I run step 1, 4, and 5 (without running step 2 first), the result is an empty directory `/tmp/bar/`, so no `test.txt` at all.

Same setup on Mac, and no problems..

**Comment by Zowie** [comment]
I looked into the issue more, and after the following steps:

- Install `17.09.0-ce-win33 (13620)`
- Try to run the project, docker notifies about not being able to access the shared drive
- Turn off firewall completely
- Run project -> works!
- Install `17.12.0-ce-win46 (15048)` again
- Firewall still turned off
- Still works :)

Then, on another Win10 machine where we had the same issue, after installing `17.09.0-ce-win33 (13620)` there it prompted for username and password in order to access the shared drive. After this, the volume mapping worked as expected too.

I think you were right @thaJeztah, but the reason appears to be that `17.12.0-ce-win46 (15048)` doesn't ask for access to the drive nor does it notify about not being able to access it while  keeping `C:\` marked as a shared drive. It appeared as if Docker had access to the drive looking at the app itself, though its behaviour (create a dir) indicated it didn't.

**Comment by thaJeztah** [comment]
Oh, that's interesting: not sure if that's a known issue (I'm not on Windows myself, so don't have first-hand experience with that; Docker for Mac uses different functionality than Windows for the shared drive).

Happy to hear though that you managed to get things working 👍

**Comment by this-Mathieu** [comment]
This thread helped me a lot. I was helping a co-worker with a similar issue. I was looking at the files being copied and they were directories, not files. The fix we ended up doing was this.

1. Go to Docker Application
2. Go to Shared Drives Tab
3. Uncheck C drive. Apply.
4. Check C drive. Apply. Login.

Everything worked after that.

**Comment by KalebMills** [comment]
This is still an issue. Facing this with version `2.2` trying to copy `.sql` files into `/docker-entrypoint-initdb.d` in the lastest official `postgres` image.

**Comment by anuraj** [comment]
I am also facing the same issue. My script files are treated as directories

**Comment by stilren** [comment]
I am having the same issue trying to map my ngnix.conf file locally. Instead a folder called ngnix.conf is created in the host and there is an error message about trying to map a directory to a file. ("Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type") 

docker-compose:
`volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf`

I tried reentering my credentials when sharing my drive (c)

Using docker desktop 2.1.0.3 (38240)
Engine: 19.03.2

**Comment by lkurzyniec** [comment]
I follow @this-Mathieu steps and received docker error. This resolved my problem: https://stackoverflow.com/questions/42203488/settings-to-windows-firewall-to-allow-docker-for-windows-to-share-drive/

**Comment by kawa-studio** [comment]
I have the same problem when deploying my code on Digital Ocean with docker-machine

**Comment by thaJeztah** [comment]
@kawa-studio see my comment above https://github.com/docker/for-win/issues/1501#issuecomment-356080631

> Bind-mounts are created from the host where the daemon runs, which (on Docker for Windows) is inside a VM. When using the `-v <host-path>:<container-path>` option is used for a bind-mount, docker will look for `<host-path>` on the host where the daemon runs; if that path does not exist, it will create a directory on that location (as it doesn't know if you wanted to mount a _file_ or a _directory_; a _directory_ is the default).

If you're trying to bind-mount files from your local machine, that won't work if the daemon is running remotely (on DigitalOcean), because it will look for those files on the remote machine, not your local one.
