### ISSUE TITLE
Installer issue - environment path variable

### ISSUE THREAD

**Issue by jasonterando** [docker/for-win#1505]
### Expected behavior
Installer should add/update directory where binaries are installed (i.e. %ProgramFiles%\Docker\Docker\resources\bin) to the Path environment variable

### Actual behavior
Installer set Path environment variable to "%ProgramFiles%\Docker\Docker\Resources\bin" (note the capitalization difference with the letter "R").  This prevents launching CLI utilities (docker, docker-compose) from the command line (without specifying full path).

Easy workaround is to go into Control Panel, and update System Environment Variable Path to have capitalization match.

### Information

  - Windows 10 Professional
  - Docker Community Version 17.12.0-ce-win45 (15017)

### Steps to reproduce the behavior

  1. Have previous Docker version installed
  2. Run Update when prompted
  3. In my case, the install got "stuck" when removing files, not sure if this is related or not (I had to close the installer, re-download and run)
  4.  Second install attempt worked fine, with the exception of the slightly wrong directory being added to the Path environment variable described above
  5.  In my case, launching "docker" or "docker-compose" from the command line (without path) did not work
  6.  Updating the directory to use a lower case "r" in the path allowed me to run CLI utilities without path

**Comment by dashesy** [comment]
not that docker usually cares about issues with docker-for-windows, but the path it added was to `c:\Program Files\DockerDesktop` while the binaries are installed in `c:\Program Files\Docker`.

**Comment by brianharwell** [comment]
This should be reopened as this is still an issue
