### ISSUE TITLE
Docker Edge on Windows 10 launches containers without IP addresses

### ISSUE THREAD

**Issue by xdestiny** [docker/for-win#1507]
### Expected behavior
When a simple webserver container is started and port 80 is exposed he host should become reachable at localhost:80 or 127.0.0.1:80.

### Actual behavior
The browser cannot connect to the address. An inspection shows that the container has been launched without asigning an IP address.

### Information

  - No other processes are occupying port 80 or prohibit asigning the address
  - This happens with the latest edge release but does not with the latest stable channel release 
  - The edge version was installed on the 9th of January. I seem to be unable to get the version information at this moment.

### Steps to reproduce the behavior

  1. Install docker edge
  2. run a docker image of a webserver like Apache or nginx that exposes port 80
  3. try accessing the default page in your browser

**Comment by djs55** [comment]
Thanks for your report. I can't reproduce this myself unfortunately.

Could you launch a powershell window and
```
docker run -d -p 80:80 nginx
docker ps # should show the port forward
curl http://localhost:80
```
to verify that it's not working with `nginx`?

Following that, could you log into the VM with
```
docker run -it --privileged --pid=host justincormack/nsenter1
```
and then check for the port exposure processes
```
ps uax | grep vpnkit-expose-port
```
and check for a port forward listed here
```
ls /var/vpnkit/port
```
Thanks!

This could be related to #1506

**Comment by xdestiny** [comment]
Let me close this. It wasn't related to the edge version but the stable channel (that somehow show the edge icon since the last update) and I am trying a step by step repdroduction of this issue.
