### ISSUE TITLE
Docker 'edge' icon on 'stable' channel after upgrade

### ISSUE THREAD

**Issue by bzier** [docker/for-win#1508]
### Expected behavior
Icon corresponds to current release channel.

### Actual behavior
Docker icon shows 'edge' icon despite being on the 'stable' channel.

### Information
After upgrading to the latest version of Docker (17.12.0-ce-win46 15048), the Windows taskbar icon changed to the icon with the 'edge' text. I have always been on the 'stable' channel.

![image](https://user-images.githubusercontent.com/714528/34736535-24b93964-f528-11e7-828d-34bd1421dca9.png)

**Comment by DeadPixelz01** [comment]
How is this still an issue? I would've thought an issue this small would have been patched by now.

**Comment by bsienn** [comment]
Even Installing the new Stable installer shows edge icon instead of regular.

Please have the Stable and Edge installer names prefixed as well.

**Comment by bzier** [comment]
Closing, as this was resolved in `17.12.0-ce-win47 15139`. Thanks for the quick turn-around.
