### ISSUE TITLE
Misleading error message when HyperV won't start under Bootcamp

### ISSUE THREAD

**Issue by jamescrowley** [docker/for-win#151]
### Expected behavior

When Docker for Windows provides an error message, it should be relevant to the capabilities of the machine.

### Actual behavior

I receive a message stating "Hardware assisted virtualization and data execution protection must be enabled in the BIOS" when opening Docker for Windows on a bootcamp-ed Windows running on a MacBook Pro. MacBook's don't have BIOS and I can't enable hardware assisted virtualization. It was pretty hard finding the problem with this error message, until I tried starting HyperV directly myself.

The issue itself is with HyperV and MacBooks which only seems to be solvable by booting into OS X first, and then 'soft' re-booting into Windows. 

It would be helpful if the error message pointed users to this solution or a FAQ.

### Steps to reproduce the behavior

  1. Install Docker for Windows on Windows under Bootcamp
  2. Cold boot machine straight into windows
  3. Start Docker for Windows

**Comment by dgageot** [comment]
Thanks @jamescrowley could you provide a diagnostic id?

**Comment by rneugeba** [comment]
closing as the issues has been idle for 12 days and requested information was not provided. Please re-open if the issue persists and you have an update. Thanks

**Comment by kuncevic** [comment]
I just had same issue and this one seams to be helped https://stackoverflow.com/questions/39684974/docker-for-windows-error-hardware-assisted-virtualization-and-data-execution-p
I run powershell with admin rights:
`dism.exe /Online /Enable-Feature:Microsoft-Hyper-V /All`
which is seams seams to be equal to running:
`bcdedit /set hypervisorlaunchtype auto`
then it seams to be working after I restarted.

**Comment by kuncevic** [comment]
However sometimes the error popup just appears after windows starts. So had to restart(sometime like multiple times) to get it working.
@dgageot any thoughts?
