### ISSUE TITLE
Docker accidentally update me to edge

### ISSUE THREAD

**Issue by softwarevamp** [docker/for-win#1513]
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by dweggemans** [comment]
I have the same. I'm 100% sure I wasn't on edge and after the update I am.

**Comment by grhm** [comment]
See also #1508 (Docker 'edge' icon on 'stable' channel after upgrade)

**Comment by thaJeztah** [comment]
Let me close this one in favour of https://github.com/docker/for-win/issues/1508 as it seems to be the same issue 👍
