### ISSUE TITLE
Docker Community Edition 17.12.0-ce-win46 2018-01-09 (Stable) shared drives not mounting

### ISSUE THREAD

**Issue by andriusjakas** [docker/for-win#1516]
### Expected behavior
docker run --rm -v c:/Users/<user forlder>:/data alpine ls /data
Should list user home dir files

### Actual behavior
Empty list

### Information
Docker Community Edition 17.12.0-ce-win46 2018-01-09 (Stable)
Shared Drives not mount

Version: 17.09.0-ce-win33 (13620)
Channel: stable

Works fine, same machine

**Comment by davgothic** [comment]
I'm having the same issue and have uploading a diagnostic. When I attempt to share my C drive it prompts me for my credentials, then the check mark next to the drive to share becomes unchecked.

Docker Version: Version 17.12.0-ce-win46 (15048)
Diagnostic ID: E877303D-CB51-43DD-B313-987973F0C7CB/2018-01-10_14-22-47

**Comment by vturcotte** [comment]
Re-installing docker and rebuilding images worked around. Only re-building images may work.

**Comment by g105b** [comment]
I'm having the same issue. This started when I upgraded to 17.12 this morning (the one advertised as being built on LinuxKit).

I uninstalled Docker, disabled Hyper-V, rebooted, downloaded and installed Docker which prompted Hyper-V to be reenabled, ran `docker run --rm -v c:/Users/:/data alpine ls /data` and ... still an empty list.

Any idea of a workaround? I would like to downgrade until stable becomes _stable_, is this possible?

**Comment by marcelonyc** [comment]
My containers created prior to the upgrade today are not mounting volumes as well. If I create a new container with a mounted volume it works. I noticed that the Source definition after the upgrad eis different.

Before

 "Mounts": [
            {
                "Type": "bind",
                **"Source": "/c/admin",**
                "Destination": "/home/admin",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
After
 "Mounts": [
            {
                "Type": "bind",
                **"Source": "/host_mnt/c/admin",**
                "Destination": "/home/admin",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }

Short of rebuilding all my containers, I have not found a solution.

**Comment by Shamus03** [comment]
Getting a similar issue.  Diagnostic ID: 0A0E6B8B-F2DE-441D-9C8E-F521F0F17F1B/2018-01-11_15-07-25

**Comment by dikey94** [comment]
same here

**Comment by JaronrH** [comment]
Latest release "Fixes" the issue.  However, I still had to re-create all my containers.

**Comment by tsmd** [comment]
Settings -> Reset -> Reset to factory defaults...
works for me.

**Comment by hoegge** [comment]
Happy I held of the 17.12 update. Only have to live with the famous "17.10-have-to-restart-docker-after-each-boot-to-make-it-run-bug." I know it is a community edition, but seems like there is very little focus on making it a stable solution and seems to be no real support from Docker (at least no solutions suggest either here or in the forums from docker employees). There has been a big breaking issue for the last three release of Docker for Win. One would assume that the paid EE is the same software with the same bugs so it would probably not help paying.

**Comment by The-Alchemist** [comment]
`docker run --rm -v c:/Users/:/data alpine ls /data` would hang for me without enabling C as a shared drive:

![docker for windows-shared drives](https://user-images.githubusercontent.com/812287/35042186-8c753656-fb55-11e7-95fe-44ae81a01b17.png)

Now it works!

**Comment by andygarfield** [comment]
Resetting to factory defaults did not work for me.
```
[18:07:59.578][SambaShare     ][Error  ] Unable to mount C drive: 10.0.75.1 (10.0.75.1:445) open
rm: can't remove '/c': No such file or directory
rm: can't remove '/C': No such file or directory
umount: can't unmount /host_mnt/c: Invalid argument
mount error(5): I/O error
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
mount: mounting //10.0.75.1/C on /host_mnt/c failed: Invalid argument
```

**Comment by giohappy** [comment]
Facing the same issue. Window 10 and Docker 18.03.1-ce-win65 (17513)

**Comment by g105b** [comment]
Please comment what build version of Windows 10 Pro you're using, still interested in knowing about when this issue is resolved and Docker becomes usable on Windows again.

**Comment by giohappy** [comment]
Windows 10.0.16299 build 16299.
Resettings the credential seems to solve the issue, at least for the moment. I will have to verify on the long term.

![image](https://user-images.githubusercontent.com/571129/41851684-fcbb00a2-7888-11e8-91da-edc6ce75bccb.png)

**Comment by andygarfield** [comment]
Resetting credentials does not work for me unfortunately.

**Edition:** Windows 10 Pro
**Version:** 1709
**OS Build:** 16299.492

**Comment by stephanecot** [comment]
Work for me.

**Comment by php-coder** [comment]
Resetting credentials did the trick, thanks!

**Comment by happya** [comment]
same issue win10 pro

**Comment by datocrats-org** [comment]
> Latest release "Fixes" the issue. However, I still had to re-create all my containers.

yep same

**Comment by g105b** [comment]
This never fixed for me.

I mean, I might start auto-closing some issues on my repos, that's one way of getting the bug count down!
