### ISSUE TITLE
[17.12.0-ce-win46] Cannot connect to the Docker daemon at tcp://localhost:2375. Is the docker daemon running?

### ISSUE THREAD

**Issue by edrevo** [docker/for-win#1518]
### Expected behavior
I have my daemon exposed on tcp://localhost:2375 without TLS. I can access it from WSL (I'm using [this setup](https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly)). In my workflow, one of my docker containers runs a docker client that communicates with the docker daemon, since it launches new containers (`"docker -H {{ docker_host }} secret rm {{ item }}`). This worked with the previous version (I _think_ it was 17.9?) of docker for-win.

### Actual behavior
"Cannot connect to the Docker daemon at tcp://localhost:2375. Is the docker daemon running?"

### Information

  - Diagnostic ID from "Diagnose & Feedback": E84F3A3E-6FDF-443A-BE95-4E3E965777A6/2018-01-10_09-36-35
  - Windows 10 1703 (15063.850)

**Comment by nickjj** [comment]
I am using Docker v17.12 with the same set up and for me, the following things work:

- Talking to the Docker daemon through WSL normally
- Volume mounting in the Docker socket to a running container, install the Docker client and run Docker commands inside of the container which reflect back to the Docker host

What value are you using for `{{ docker_host }}`?

**Comment by edrevo** [comment]
Cannot repro with newer builds. Closing
