### ISSUE TITLE
Trouble with docker save for Windows containers

### ISSUE THREAD

**Issue by ManoMarks** [docker/for-win#152]
### Expected behavior

`docker save microsoft/nanoserver -o ns.tar` should create the `ns.tar` file
### Actual behavior

On Windows 10 pro, fully updated this is the result:

`PS C:\Users\Mano Marks\Code\images> docker save microsoft/nanoserver -o ns.tar
Error response from daemon: open C:\ProgramData\Docker\windowsfilter\f54e9f119ae2d95d2b15118c6d9fc251648ae030b78d7934a8a
6bfd8d31a350b\bcd.bak: The system cannot find the file specified.`
### Information:

Diagnostic ID: 8933275A-5908-48B5-91BD-6EFD64746CE2/2016-10-17_21-17-47
### Steps to reproduce the behavior
1. `docker pull microsoft/nanoserver`
2. `docker save microsoft/nanoserver -o ns.tar`

cc @friism who was able to have it work just fine on Windows Server 2016

**Comment by dgageot** [comment]
@friism Anything you are aware of?

**Comment by friism** [comment]
It's working on my machine, both WS2016 and Windows 10.

@ManoMarks what's `docker version`?

**Comment by ManoMarks** [comment]
Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 05:27:08 201
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 201
 OS/Arch:      windows/amd64

I did try another Windows machine and it worked just fine. Not sure the difference.

**Comment by dgageot** [comment]
@ManoMarks Can you try with latest Beta 31?

**Comment by ManoMarks** [comment]
Seems to be working fine now

**Comment by dgageot** [comment]
@manomarks neat. I'm closing the issue then
