### ISSUE TITLE
Wrong docker icon

### ISSUE THREAD

**Issue by BorntraegerMarc** [docker/for-win#1528]
Upgraded to Version 17.12.0-ce-win46 (15048)
Channel: stable
0ac7325

and now suddenly the docker icon looks like this: 
![image](https://user-images.githubusercontent.com/7549295/34813527-9865fa9a-f6aa-11e7-996f-bea0d68a221e.png)

The "edge" in the icon should not be there....

**Comment by bsienn** [comment]
Even Installing the new Stable installer shows edge icon instead of regular.

**Comment by grhm** [comment]
Possible duplicate of #1508

**Comment by BorntraegerMarc** [comment]
Definitely a duplicate. Closing this issue...
