### ISSUE TITLE
Downloading / Updating docker stable but Edge gets installed

### ISSUE THREAD

**Issue by bsienn** [docker/for-win#1529]
### Expected behavior
Docker stable
### Actual behavior
Docker Edge
### Information
I got an update prompt and updating installs Edge instead of stable.
Uninstalled Edge re downloaded and Installed stable but still edge gets installed 
### Steps to reproduce the behavior

  1. Go To [https://download.docker.com/win/stable/Docker/for/Windows/Installer.exe](https://download.docker.com/win/stable/Docker%20for%20Windows%20Installer.exe)
  2. Install Docker stable just to realize you get Docker Edge

**Comment by markchagers** [comment]
+1

**Comment by QAnders** [comment]
Yeah, me too and my images are not working it seem...

**Comment by bsienn** [comment]
Just saw the [THIS](https://github.com/docker/for-win/issues/1528) issue and seems I jumped early to wrong assumption. The installer is indeed stable release just the icon is of edge.

Check `About` section of the docker and it shows stable release. 
Right click docker in taskbar and click about.

**Comment by bsienn** [comment]
Closing this to support the above mentioned issue.
