### ISSUE TITLE
Docker startup infinite loop

### ISSUE THREAD

**Issue by Thadir** [docker/for-win#1536]
### Expected behavior
Docker starts up
### Actual behavior
Startup takes for ever (like it seems to be starting up for more then a hour @ the moment of writing.
### Information

  - 423E21A8-01B7-4D08-8597-BADA17BA4765/2018-01-12_13-31-15

### Steps to reproduce the behavior
Update docker, and try starting it.

**Comment by jasonbivins** [comment]
Hi @Thadir 
I do see several tasks that are hung up from the logs, but I'm not seeing much that might have caused the hangups. Have you tried rebooting Windows and trying again?
