### ISSUE TITLE
Installation fails when com.docker.cloud.proxy.exe is running

### ISSUE THREAD

**Issue by mklinke** [docker/for-win#1537]
### Expected behavior
Auto-Updater suggests new version and installation succeeds.

### Actual behavior

Auto-Updater suggests new version and installation fails:

Der Zugriff auf den Pfad "com.docker.cloud.proxy.exe" wurde verweigert.
   bei System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   bei System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   bei LightweightInstaller.UninstallWorkflow.<ProcessAsync>d__7.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei LightweightInstaller.InstallWorkflow.<ProcessAsync>d__18.MoveNext()

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

### Workaround

Kill the process com.docker.cloud.proxy.exe manually and retry the installation.

**Comment by jasonbivins** [comment]
Hi @mklinke 
That is actually our  TCP connection to Windows - do you know if you had any containers or large tasks running at the time?
