### ISSUE TITLE
Latest stable versino of Windows 10 cannot launch latest stable version of Docker CE

### ISSUE THREAD

**Issue by zimiarh** [docker/for-win#1539]
### Expected behavior
Download and install the stable version of Docker for Windows. And run the Docker normally without any error.

### Actual behavior
I just updated my Docker for Windows an hour ago. After that, whenever I start it, it says 

> Docker doesn't support your Windows version. Check documentation for minimum requirements

Then I uninstalled Docker and go to the official website to download a stable version, which should be  **17.12.0-ce-win46** for now according to the site. However, when I run the downloaded setup file, it says that it is installing **17.12.0-ce-win47**, which is probably a nightly build that I cannot launch with my current Windows version.

When I click the "About Docker" from the context menu of the Docker taskbar item, it says its version is **Version 17.12.0-ce-win47 (15139)**. However, it claims that its channel is **stable**, which is conflicting with how the official site states.

So:
1. What is the exact latest stable version?
2. Is it expected that the latest stable version of Windows 10 cannot run the latest stable version of Docker?
3. If the answer from the previous question is yes, then which Docker version should I use and where I can get a installation file for it?

### Information

Windows 10 version 1709, no more updates available currently
Docker 17.12.0-ce-win47 (15139)

**Comment by Addisco** [comment]
I have a similar issue and switched to the edge channel. Actually switching to the edge channel replaces the current stable version 17.12.0-ce-win**47** with 17.12.0-ce-win**45**.
I'm wondering why the stable channel has a newer version than then edge channel.

**Comment by jasonbivins** [comment]
Hi @zimiarh   The latest stable version is 17.12.0-ce-win47  - which was released this morning.
Can you run the Winver command in CMD and post a screenshot of the versioning Window?

**Comment by zimiarh** [comment]
Hi @jasonbivins , here is the screenshot.
![winver](https://user-images.githubusercontent.com/35001061/34901230-6c4e08f0-f842-11e7-9257-7327d5df23ba.PNG)
Sorry for that the information is not in English but I am too lazy to switch my Windows locale/language to English. Basically it says my windows is `Version 1709 (OS build 16299.192)`

As a side note, I downloaded docker 17.09.0-ce-win33 from the official site, and it runs smoothly so far.

**Comment by JohnathanKong** [comment]
Just got the same error message. It's unfortunate because I was really looking forward into a docker integration

![image](https://user-images.githubusercontent.com/11951977/36955047-021a606c-1ff4-11e8-9f92-87aecd654f84.png)

**Comment by limpep** [comment]
Hi, I am getting the same error on 16299.248.

**Comment by JohnathanKong** [comment]
update came through for docker, been too busy to remove it from my system, and I'm still having the same problem. Windows version hasn't changed from 22 days ago and here's the latest docker version that was installed on my system today

![image](https://user-images.githubusercontent.com/11951977/37971068-1410f2a2-31a3-11e8-83c3-5c3e53656bb1.png)

**Comment by Zontir** [comment]
Hello, today I tried to install docker for the first time and I'm having the same error. 
![screenshot_6](https://user-images.githubusercontent.com/22550119/38042853-758a202c-3283-11e8-8a5c-d320f52dc2d9.png)

**Comment by shank8** [comment]
My company is finally using microservices for our web infrastructure and I wanted to start using Docker, but I cannot get it running properly either:

![image](https://user-images.githubusercontent.com/1467599/38155729-1f63e1d6-342e-11e8-8484-937f7060c94e.png)

![image](https://user-images.githubusercontent.com/1467599/38155749-40b0f522-342e-11e8-9c32-85dc78854c4e.png)

**Comment by fleming4** [comment]
Same Issue:
![image](https://user-images.githubusercontent.com/8812082/38646745-0f5fc042-3d9e-11e8-8cee-7d8d1bf8527e.png)

![image](https://user-images.githubusercontent.com/8812082/38646791-40d6064a-3d9e-11e8-8eaf-da59709c727a.png)

**Comment by MikhailTymchukDX** [comment]
Same issue for me. Occured after restart for VS 2017 update.

![image](https://user-images.githubusercontent.com/17080984/38877949-847f03e6-4268-11e8-90fb-dcab46724e4c.png)

Removing and installing docker back solves this issue.
Keep in mind, that this vanishes all your docker settings and images!

**Comment by fleming4** [comment]
@MikhailTymchukDX I have uninstalled and reinstalled multiple times and I continue to get the same error.

**Comment by vgriffin** [comment]
Windows 10 Pro, Version 1709 (OS Build 16299.371)
18.03.0-ce-win59 ("stable")
18.04.0-ce-win62 (edge)

It fails using Linux and Windows containers. I've tried reboots and multiple downloads.

This is my first download of Docker

**Comment by vgriffin** [comment]
I found the logs and figured out that Hyper-V had to be enabled. Docker can run now. It would be helpful for the installation info to include Hyper-V as a requirement. It would also be helpful if the error message pointed to the log files

**Comment by haumacher** [comment]
@vgriffin said "I found the logs ...". That's fine for you. Even better would be if you could provide some info where you found them to help others with the same problem to gain speed...

**Comment by haumacher** [comment]
@vgriffin The following would have saved me the day:

I found the logs in `C:\Users\<my-name>\AppData\Local\Docker\log.txt`. This file contains an error:
```
[12:43:09.357][Linux          ][Error  ] Failed to start: Unable to stop: Der ausgeführte Befehl wurde beendet, da die Einstellungsvariable "ErrorActionPreference" oder ein allgemeiner Parameter auf "Stop" festgelegt ist: Das angegebene Modul "Hyper-V" wurde nicht geladen, da in keinem Modulverzeichnis eine gültige Moduldatei gefunden wurde..
bei <ScriptBlock>, <Keine Datei>: Zeile 81. Let's retry
[12:43:09.656][Installer      ][Info   ] Checking for features: Hyper-V, Containers
[12:43:09.661][PowerShell     ][Info   ] Run script...
[12:43:12.794][Installer      ][Error  ] Unable to check for available feature Hyper-V: Das System kann die angegebene Datei nicht finden.

[12:43:12.794][PowerShell     ][Info   ] Run script...
[12:43:14.489][Installer      ][Error  ] Unable to check for available feature Containers: Das System kann die angegebene Datei nicht finden.

[12:43:14.489][Installer      ][Error  ] Feature(s) not available: Hyper-V, Containers
```
I then followed the instructions at https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v saying to enable "Hyper-V" using the tool  
"Turn Windows Features on or off" in the category "Apps & Features".

But this did not work either with the incomprehensible error code `0x80070002` "The system cannot find _the_ specified file". I then tried to "repair" Windows Update using the tool "Windows Update Troubleshooter" as described here: https://support.microsoft.com/en-ph/help/4027322/windows-update-troubleshooter.

After a reboot I was able to install the feature "Hyper-V" and after another reboot docker started like a charm.

**Comment by bradisbell** [comment]
Even with Hyper-V enabled, installed, and with Docker previously running on it, current builds of Docker do not work.

**Comment by haumacher** [comment]
@bradisbell Ok, that's interesting, I yesterday downloaded a fresh Docker (Version 18.03.1-ce-win65 (17513) Channel: stable 93354b3) and installed it on a new PC with Windows 10 Pro Version 1803 Build 17134.48. After a hard time installing Hyper-V it is now working. At least these version numbers sound higher that in the original report.

**Comment by ahuglajbclajep** [comment]
I also encountered `0x80070002`, but in safe mode I was able to turn on Hyper-V.
Now it works normally.

**Comment by TysvdHeuvel** [comment]
Over the issue only occurs when i'm not in the office. I run Windows 10 Enterprise. And when working remote (as almost always) by default I get the "Docker doesn't support your Windows version. Check documentation for minimum requirements" error. 
But, if I open a VPN connection before starting docker, so that i'm connected to the company domain, then Docker starts just fine. After starting Docker I can close the connection, and everything keeps working.
