### ISSUE TITLE
DFW Docker Build: Symlinks under build context root folder are not being handled properly

### ISSUE THREAD

**Issue by BillyDJr** [docker/for-win#1541]
### Expected behavior
For purposes of a "docker build", a file or folder that has been symlinked to the build context root folder should be consumed as a child of that root folder (just as if it had been copied there instead of symlinked). This is how it used to work in Version 17.09.0-ce-win33 (13620)

### Actual behavior
Instead of using the link at face value, docker build seems to be traversing the symlink and trying to use the target of the link instead. This results in a message like this one: 
> COPY failed: CreateFile \\?\C:\ProgramData\Docker\tmp\docker-builder306461501\Program Files (x86)\Windows Kits\10\Debuggers\x64: The system cannot find the path specified. 

I first noticed this regression in version 17.12.0-ce-win46 (15048)

### Information
  - Diagnostic ID from "Diagnose & Feedback" in the menu.
 FFEE5B54-77D8-4E7E-A089-BFA753C38307/2018-01-12_11-09-01

  - a reproducible case if this is a bug, Dockerfiles FTW
See "Steps to reproduce the behavior."

  - page URL if this is a docs issue or the name of a man page
N/A
  - host distribution and version (Windows version, build number, etc)
Windows 10 Pro. Version 1709 (OS Build 16299.192)

### Steps to reproduce the behavior

  1. Create (or choose an existing) target folder outside your build context. Then symlink it to your build context folder using "mklink /D [link] [target]".  For example, in my case, I was symlinking the WinSdk folder on my system, as follows: 
>mklink /D winsdk "C:\Program Files (x86)\Windows Kits\10\Debuggers\x64"

  2. Run a docker build using a dockerfile similar to the simplified one shown here:
>FROM [any image will do]
>COPY winsdk winsdk/

**Comment by kriskomar-scentsy** [comment]
I'm having a similar issue. No file ops from within Dockerfile will work on build. "RUN mkdir c:\inetpub\wwwroot -Force" produces:
 ---> Running in df725fbbc3e0
container df725fbbc3e096e6e7424154916ab2db0b58e05e004ceb7f11251f6b514e9b2b encountered an error during CreateContainer: failure in a Windows system call: winapi error #3221226536 (0xc0000428) extra info: {"SystemType":"Container","Name":"df725fbbc3e096e6e7424154916ab2db0b58e05e004ceb7f11251f6b514e9b2b","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\df725fbbc3e096e6e7424154916ab2db0b58e05e004ceb7f11251f6b514e9b2b","Layers":[{"ID":"2443d91d-43b4-5e39-9273-74611fd990a8","Path":"C:\\ProgramData\\Docker\\windowsfilter\\296883f7e93082766768a6f6d14f94e605aee729b3ca0dbc8c09e9c123dc7637"},{"ID":"397ca1b8-ab73-581a-8378-7de661551ec7","Path":"C:\\ProgramData\\Docker\\windowsfilter\\c742e86bf9c2153c1c34c4fb4b2824609bebe1cc284e5b440fc51d428d67f058"},{"ID":"39ef6fbe-3dd4-5da7-b49e-5649f9b7d003","Path":"C:\\ProgramData\\Docker\\windowsfilter\\848379bf256c85f8d3a238f21ec4f2d0767cd5513f066e39b2f55f1c2da89278"},{"ID":"c513f516-d5ed-58bc-997f-5ffbb559f5aa","Path":"C:\\ProgramData\\Docker\\windowsfilter\\c1da2468419e6576c0b64972fea9bc28a7a86c5af37b8e9eceb99d155f748a1b"},{"ID":"0e53de7b-f887-54ab-a3fe-650396c10086","Path":"C:\\ProgramData\\Docker\\windowsfilter\\c065d39a7d8c494801935ddf92256f3e93302d54bf78c76bc8ded395a88cd97b"}],"HostName":"df725fbbc3e0","HvPartition":true,"EndpointList":["ff72d1e6-91d4-4bb3-9f6a-10964145f009"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\c1da2468419e6576c0b64972fea9bc28a7a86c5af37b8e9eceb99d155f748a1b\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}
