### ISSUE TITLE
"Unknown shorthand flag" error is displayed for chained commands

### ISSUE THREAD

**Issue by sskorol** [docker/for-win#155]
### Expected behavior
Docker allows executing chained commands like `rm` with `ps` in `powershell`.
### Actual behavior
`unknown shorthand flag: 'a' in -aqf` error is displayed (see steps). If we remove `a` flag, the same error will point to `q` flag.
### Information

  - Diagnostic ID: 3B7C330D-8F81-4A02-8E61-95882CAAC6B3/2016-10-18_21-58-23
  - Host distribution and version (Windows 10 Pro):
```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```

### Steps to reproduce the behavior
```
docker rm -vf $(docker ps -aqf "status=exited")
```
Note: standalone `docker ps -aqf "status=exited"` command works fine.

**Comment by simonferquel** [comment]
You have to note that "docker" here is not a Powershell commandlet but in executable.
To do what you want to achieve, you might want to write:
`(& docker ps -aqf "status=exited") | ForEach-Object { docker rm -vf $_ }`
The `(& <...>)` syntax capture the output of an executable to a powershell list of strings, so that we can "Foreach-Object" it.

**Comment by sskorol** [comment]
@simonferquel thanks for clarification!

**Comment by indcoder** [comment]
@sskorol  Your command had worked for me in my powershell.


`docker rm $(docker ps -aqf "status=exited")`
eee46a07e350
66e44ad3febb
a6f470628e29
1e268a73f16d
50811ffac869
ee6931df24cc
4fba5a32c5f7
b9a11a6437d6
062fcd4cfe6d
d45d978c80f8
a00465cf2cab
84c2637d31ee

@simonferquel But what I noticed is that this same command that used to work in command prompt is now failing with the same error as Sergey mentioned in his original issue.

```
docker rm $(docker ps -aqf "status=exited")
unknown shorthand flag: 'a' in -aqf
See 'docker rm --help'.
```

Tested in the cmder terminal too and the same issue 


```
λ docker rm $(docker ps -aqf status=exited)
unknown shorthand flag: 'a' in -aqf
See 'docker rm --help'.
```

**Comment by maestroh** [comment]
This command works in cmder
`docker ps -aq | xargs -n 1 docker rm`

**Comment by starcraft0429** [comment]
same issue
```
λ docker rmi $(docker images -a -q)
unknown shorthand flag: 'a' in -a
See 'docker rmi --help'.
```

**Comment by yadavvineet** [comment]
> same issue
> 
> ```
> λ docker rmi $(docker images -a -q)
> unknown shorthand flag: 'a' in -a
> See 'docker rmi --help'.
> ```

This is not a bug. I believe this is how cmd and poweshell handles the command. Poweshell is more inclined towards scripting, and supports "sort of" scripting syntax. 

you may switch to powershell, and it works correctly.
