### ISSUE TITLE
Installer freeze.

### ISSUE THREAD

**Issue by aplicus** [docker/for-win#1550]
### Expected behavior
finished instalation

### Actual behavior
instalator freeze
![scan](https://user-images.githubusercontent.com/4818430/34910544-e1dc8b1c-f8b7-11e7-87ea-fec6f8d52163.JPG)

### Information

  - I have Windows 10 Pro
- latest docker install file

### Steps to reproduce the behavior

  1. Just start instalator
2. See picture. It always freeze on the same step -> Removing files

**Comment by standus** [comment]
I tried install docket toolbox and there is another instalaotr error.
![scan2](https://user-images.githubusercontent.com/4818430/34910621-60fef10e-f8b9-11e7-8095-4c38c507897e.JPG)

**Comment by Lucas-C** [comment]
cf. also https://github.com/docker/for-win/issues/1417
Maybe this issue can be close if related to AV

**Comment by addshore** [comment]
I also had this issue, after a few attempts of stopping the install and trying again it eventually worked.

**Comment by zjhong** [comment]
Always removing files。

I tried many version recently

**Comment by zjhong** [comment]
So the “solution” I have found is that you need to uninstall, reboot and then install from new. Upgrade functionality has never worked and I have never ever been able to upgrade Docker never ever by just selecting Upgrade when the app says there is an update available. When I don;t reboot it just hangs as reported. Every. Time.

https://forums.docker.com/t/installer-for-windows-10-hangs/36944/4

**Comment by Lucas-C** [comment]
I wasn't upgrading. I was installing a new version

**Comment by phil11b** [comment]
I had this problem with a clean install of 2.0.0.31259. I noticed that Controlled Folder Access was blocking an update which appeared to cause the installation to lock-up. Allowing "Docker for Windows Installer.exe" through controlled folder access and restarting the installation fixed the problem.
