### ISSUE TITLE
Please stop putting a docker icon on the desktop

### ISSUE THREAD

**Issue by atrauzzi** [docker/for-win#1551]
It's small, it's simple, but it's just such an inconvenience every time I update (which happens often enough).

![image](https://user-images.githubusercontent.com/115199/34913344-b082709c-f8bf-11e7-9f02-f594f39df77b.png)

If you really want the option, make it a checkbox in the installer **that defaults to off**.

**Comment by taylorb-microsoft** [comment]
+1 (didn’t bother me enough to open an issue but I dislike desktop icons)

**Comment by pbering** [comment]
+1

**Comment by 10Dev** [comment]
I like Desktop Icons. It is one of the actual purposes of the Windows Desktop, organization.

Given the increasing rather arrogant trend by installers to not present a choice for custom install locations and to arbitrarily decide to park the install in one or more arcane locations determined most often by very subjective criteria, the automatic provisioning of a Desktop Icon often comes as a welcome relief.

By all means, make it a choice, but more importantly make the install location a choice as well.

**Comment by atrauzzi** [comment]
Another update, another desktop icon to delete.  Seriously, I don't need this every time I update!

![image](https://user-images.githubusercontent.com/115199/38141745-3ce95a44-33ff-11e8-86a9-98a67750386d.png)

**Comment by rn** [comment]
The latest "edge" release (`18.04.0-ce-rc2-win61 (17070)`) now has the option to not create the icon on the desktop and an in-app update should not recreate the desktop icon if you have previously removed it. This should also be a available in the next stable release. Closing this issue, please let us know if the above is not working for you.

![screen shot 2018-04-10 at 13 06 05](https://user-images.githubusercontent.com/3338098/38556074-486f64e8-3cc0-11e8-9ba8-3ad44747a792.png)

**Comment by atrauzzi** [comment]
🌟 🎊 😮 🎉 🎉 😮 🎊 🌟 

Thank you!

_(I still say that checkbox should be off by default for new installs, this isn't Windows 3.1, but so long as it doesn't recreate, that's a start.)_
