### ISSUE TITLE
Unable to persist the "Shared" drive checkbox and error in log "Unable to mount D drive"

### ISSUE THREAD

**Issue by Lucas-C** [docker/for-win#1555]
![mobyissuesharingdrive](https://user-images.githubusercontent.com/925560/34944032-4db52f00-f9fe-11e7-93b6-91f2182d3ef1.gif)

### Expected behavior
- _Docker For Windows_ interface persists the "Shared" checkbox in the "Shared Drives" tab
- no Error logs

### Actual behavior
- the checkbox gets unchecked when I click on the "Apply" button (cf. GIF above)
- I see the following error logs in `service.txt`:
```
[12:13:14.344][ApiProxy       ][Info   ] time="2018-01-15T12:13:14+01:00" msg="proxy << POST /v1.35/containers/abd86a49080d5655c8437813daeb037b2fb1dd80fd677633c550009d611c16e0/wait?condition=removed\n"
[12:13:14.347][SambaShare     ][Error  ] Unable to mount D drive: 10.0.75.1 (10.0.75.1:445) open
rm: '/D' is a directory
ln: /D/d: File exists

[12:13:14.347][SambaShare     ][Info   ] Removing share D
[12:13:14.372][NamedPipeServer][Info   ] Mount done in 00:00:03.6797020.
[12:13:14.379][NamedPipeServer][Info   ] Version()
[12:13:14.379][NamedPipeServer][Info   ] Version done in 00:00:00.
[12:13:14.380][NamedPipeServer][Info   ] GetDefaultVhdxPath()
[12:13:14.382][NamedPipeServer][Info   ] GetDefaultVhdxPath done in 00:00:00.0020000.
```
I also have plenty of those lines:
```
[Moby           ][Info   ] [ 1807.338051] CIFS VFS: BAD_NETWORK_NAME: \\10.0.75.1\D
```

### Information

  - Diagnostic ID: CF59AB71-081A-4F94-A0B7-4231DEFF0DEF/2018-01-15_14-17-14
  - host distribution and version:
    * Windows 10 Enteprise N v1703 OS v15063.850 64bits
    * Docker Version 17.12.0-ce-win47 (15139) Channel: stable 9c692cd

**Comment by Lucas-C** [comment]
I tried to "Reset credentials" and even restarted my computer, but the issue persists.

I haven't found any issue mentioning the "rm" & "ln" commands nor the "CIFS VFS: BAD_NETWORK_NAME" lines that appear in this log (but plenty mentioning the "Unable to mount" message)

**Comment by Beztix** [comment]
Hi,
had the same problem, I just manually uninstalled Docker 17.12 and installed Docker 17.09 and now everything seems to work again - not the best kind of fix but at least it works again :/

**Comment by Lucas-C** [comment]
Thank you @Beztix !
I tried to install this older version : Docker 17.06.2-ce-win27 (13194)
https://download.docker.com/win/stable/13194/Docker%20for%20Windows%20Installer.exe

But no luck, same "hanging" behaviour of the installer :(

**Comment by Eneuman** [comment]
Are you using a Azure Id or Microsoft Live Id as login to your computer?
(If so, you need to create a local account and use that one to setup drive sharing)

**Comment by Lucas-C** [comment]
No, I do not use such kind of ID as login

**Comment by Wosniak** [comment]
I´m facing with the same behaviour on version 18.03.0-ce-win59 (16762), but with a different log message:

[10:41:54.048][SambaShare     ][Error  ] Unable to mount D drive: 10.0.75.1 (10.0.75.1:445) open
rm: cannot remove '/d': Is a directory
rm: cannot remove '/D': No such file or directory
umount: /host_mnt/d (//10.0.75.1/D) unmounted
mount.cifs kernel mount options: ip=10.0.75.1,unc=\\10.0.75.1\D,noperm,iocharset=utf8,nobrl,mfsymlinks,vers=3.02,sec=ntlmsspi,user=<user>,domain=ARCHER,pass=********
ln: failed to create symbolic link '/d/d': File exists

Any enlightment on this?
