### ISSUE TITLE
Docker doesn't restart after update

### ISSUE THREAD

**Issue by shawmanz32na** [docker/for-win#1558]
### Expected behavior

I expect, when I install an update that Docker prompts me to install while Docker is already running, that Docker will restart itself after the update, so that I am left in the same state I was before the update.

### Actual behavior

Docker will be running, I'll be prompted with the update, I'll update, and then Docker will not restart. I then have to restart my machine so that Docker will be automatically started on system start.

### Information

  - **Windows version**
    Windows 10 Pro Version 1709 (OS Build 16299.192)

### Steps to reproduce the behavior

  1. Be working away happily as a clam, using many Docker containers to save time and sanity
  2. Get prompted by Docker to install a new Docker version
  3. Install the new Docker version by following the prompts
  4. Try to go back to what you were doing. Alas, Docker is no longer running.

**Comment by martineza79** [comment]
You will have to restart the computer for Docker to start again.

**Comment by shawmanz32na** [comment]
@martineza79 I understand that I have to restart the machine to get Docker to start again. That's the issue. I'd like it if Docker would just restart itself after the update without me having to turn the whole machine off. Just like Chrome, Java, Atom, VS Code, many more...

**Comment by shawmanz32na** [comment]
@sergey-malechko This issue only adresses having to restart the machine to restart Docker after a Docker update. If Docker hasn't restarted after restarting your computer, I expect you're experiencing a different problem.

**Comment by sergey-malechko** [comment]
yes, this is a different problem. It is not related to machine restarting. Could you help how to fix it ?
