### ISSUE TITLE
Include download links for all Docker versions in the Release Notes

### ISSUE THREAD

**Issue by shawmanz32na** [docker/for-win#1559]
This has been discussed multiple times in [docker/for-mac](https://github.com/docker/for-mac) - see docker/for-mac#444, docker/for-mac#1053, docker/for-mac#1120, docker/for-mac#1448

It happens that from time to time, there are issues on the current stable version of Docker. When this happens and the issues are being triaged, we need a way to download the last (working) version of Docker to install and get back to work. On the [Release Notes](https://docs.docker.com/docker-for-windows/release-notes), some versions (17.09.0-) have a "Download" link, while others (17.09.1+) don't. I'd like to see the Release Notes updated to have "Download" links for all versions, and, realistically, I'd hope there'd be a (automated?) process to make sure that future updates to the Release Notes always include a "Download" link.

Additionally, it appears that all stable releases can be downloaded from `https://download.docker.com/win/stable/[build-number]/Docker for Windows Installer.exe`, but the build numbers of the various versions are not listed in the Release Notes (or anywhere else I could find, for that matter). If you could provide the build number of each version on the Release Notes page, we could figure out the URL. That said, a direct link would be much preferred.

### Information

  - **Page URL**
    https://docs.docker.com/docker-for-windows/release-notes

**Comment by dennisbolderman** [comment]
The same issue here with Docker for Mac. I used the automatic upgrade this morning and none of my containers will work now. I've spend the last 2 hours finding out how to download and install the previous (working!) version, without any success. If the previous installers can be simply downloaded with the build number, how hard is it to provide a listing for these downloads?

**Comment by aaronup** [comment]
FYI @dennisbolderman, https://docs.docker.com/docker-for-mac/release-notes then find the previous release on the list to the right, it will contain a download link

**Comment by lystor** [comment]
Each release Docker for Windows f*ck us and we can't rollback due to absent download links to previous versions.

Please fix this problem or your customers will continue to hate you, Docker Inc.

Thank you

**Comment by franklinyu** [comment]
I guess the guy who manually updates those links is on holiday… So currently it is only possible to downgrade further to 17.09.0.

**Comment by IvanLinos** [comment]
Hi,
There still no way to find the build number for edge releases and so, downgrading to a given version.
This last 18.02.0-ce-mac53 release totally broke my environment, but 18.02.0-ce-rc1-mac50 worked like charm! Why dont you provide download links for edge releases???
We would need at least a way to identify the build number so we can use the download link as:
https://download.docker.com/mac/edge/BUILDNUMBER/Docker.dmg

**Comment by shawmanz32na** [comment]
At some point, https://docs.docker.com/docker-for-windows/release-notes/ has been updated with download links for all recent versions. This may mean that this issue can be closed, but you may also want to leave it open as a placeholder for automating the addition of the download link during the release process.

Thanks for the links!

**Comment by akimd** [comment]
The links are in the release notes.
- https://docs.docker.com/docker-for-mac/release-notes/
- https://docs.docker.com/docker-for-mac/edge-release-notes/
- https://docs.docker.com/docker-for-windows/release-notes/
- https://docs.docker.com/docker-for-windows/edge-release-notes/

**Comment by Yensan** [comment]
@akimd 
Thank you for links you listing above. But I still can't download it. 
Which link I use is:  https://download.docker.com/mac/stable/15353/Docker.dmg

**Comment by franklinyu** [comment]
@Yensan Docker for Mac 1.13.1 is over a year ago. I guess they won’t keep old version that long.

**Comment by Yensan** [comment]
however, I got it by https://download.docker.com/mac/stable/1.13.1.15353/Docker.dmg
They have kept it, actually.

**Comment by franklinyu** [comment]
What do you mean by "last one Docker for Mac"? `1.x.x` series? How is that significant?

**Comment by Yensan** [comment]
@franklinyu 
After Docker for Mac  1.13.1, they released Docker CE for Mac.

**Comment by thaJeztah** [comment]
That's only a name change; Docker CE 17.03.0 was released from the 1.13.2 codebase

Could you explain your concern with using the Docker CE versions?

**Comment by Yensan** [comment]
@thaJeztah  I just want use docker demon, but it let me login [docker hub](https://hub.docker.com) !
First, not everyone want a Hub account. For me, download images and use container is all. I want keep my tools as simple as possible. Life is hard and short, I just want my knife easier.  😆 
Second, for some oversea Internet reasons, I can't get an useful Hub service. Waiting for network is unbearable.

**Comment by thaJeztah** [comment]
@Yensan you can skip the login page that's shown the first time you startup Docker for Mac the first time; or do you mean something else? You can download Docker for Mac 18.06 from the changelog, e.g. 
https://download.docker.com/mac/stable/26399/Docker.dmg (Docker Community Edition 18.06.0-ce-mac70)

**Comment by Yensan** [comment]
@thaJeztah  Thank you. I downloaded docker 13, satisfied and happy.
