### ISSUE TITLE
Problem starting docker

### ISSUE THREAD

**Issue by donut87** [docker/for-win#156]
### Information

  - Diagnostic ID: A9ABE01C-504B-4B17-A4F0-1ED5A4EF1DF3/2016-10-19_14-24-33
  - Log:

Exception 0xc000001d 0x0 0x0 0x18000890c
PC=0x18000890c

syscall.Syscall(0x7ffad4c7dc40, 0x2, 0x270, 0x3, 0x0, 0x274, 0x0, 0x0)
        /usr/local/go/src/runtime/syscall_windows.go:163 +0x5c
github.com/Microsoft/go-winio.setFileCompletionNotificationModes(0x270, 0x203, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/zsyscall.go:88 +0x70
github.com/Microsoft/go-winio.makeWin32File(0x270, 0xc08202f6e8, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/file.go:76 +0xf8
github.com/Microsoft/go-winio.DialPipe(0xc0820a5048, 0x16, 0xc08202f870, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/pipe.go:186 +0x81d
github.com/docker/go-connections/sockets.DialPipe(0xc0820a5048, 0x16, 0x773594000, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/go-connections/sockets/sockets_windows.go:12 +0x54
github.com/docker/go-connections/sockets.ConfigureTransport.func2(0xced7b0, 0x3, 0xc0822fd920, 0x19, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/go-connections/sockets/sockets.go:29 +0x6e
net/http.(*Transport).dial(0xc0820a8780, 0xced7b0, 0x3, 0xc0822fd920, 0x19, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:662 +0x9d
net/http.(*Transport).dialConn(0xc0820a8780, 0x0, 0xcea578, 0x4, 0xc0822fd920, 0x19, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:765 +0x1e44
net/http.(*Transport).getConn.func4(0xc0820a8780, 0x0, 0xcea578, 0x4, 0xc0822fd920, 0x19, 0xc082306f60)
        /usr/local/go/src/net/http/transport.go:709 +0x6d
created by net/http.(*Transport).getConn
        /usr/local/go/src/net/http/transport.go:711 +0x269

goroutine 1 [select]:
github.com/docker/engine-api/client/transport/cancellable.Do(0x152d708, 0xc0823084c0, 0x152db70, 0xc0822fc5c0, 0xc0820527e0, 0xc0822f18c0, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:56 +0x4a4
github.com/docker/engine-api/client.(*Client).sendClientRequest(0xc082306a80, 0x152d708, 0xc0823084c0, 0xce69e0, 0x4, 0xd696f0, 0x12, 0xc0822f18c0, 0x152da70, 0xc0822d9c00, ...)
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/engine-api/client/request.go:106 +0x510
github.com/docker/engine-api/client.(*Client).sendRequest(0xc082306a80, 0x152d708, 0xc0823084c0, 0xce69e0, 0x4, 0xd696f0, 0x12, 0xc0822f18c0, 0xc0b0a0, 0xc0822fc9e0, ...)
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/engine-api/client/request.go:75 +0x2e3
github.com/docker/engine-api/client.(*Client).post(0xc082306a80, 0x152d708, 0xc0823084c0, 0xd696f0, 0x12, 0xc0822f18c0, 0xc0b0a0, 0xc0822fc9e0, 0x0, 0xc61b68, ...)
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/engine-api/client/request.go:38 +0xbb
github.com/docker/engine-api/client.(*Client).ContainerCreate(0xc082306a80, 0x152d708, 0xc0823084c0, 0xc0822d0c80, 0xc0822f2a80, 0xc0820284a0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/engine-api/client/container_create.go:35 +0x28e
github.com/docker/docker/api/client/container.createContainer(0x152d708, 0xc0823084c0, 0xc0820665a0, 0xc0822d0c80, 0xc0822f2a80, 0xc0820284a0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/docker/docker/api/client/container/create.go:182 +0x46e
github.com/docker/docker/api/client/container.runRun(0xc0820665a0, 0xc0820674d0, 0xc0822b1fb0, 0xc0822d3900, 0x0, 0x0)
        /go/src/github.com/docker/docker/api/client/container/run.go:159 +0x8f4
github.com/docker/docker/api/client/container.NewRunCommand.func1(0xc0822ed200, 0xc0822fc8a0, 0x1, 0x2, 0x0, 0x0)
        /go/src/github.com/docker/docker/api/client/container/run.go:54 +0x148
github.com/spf13/cobra.(*Command).execute(0xc0822ed200, 0xc0822fc780, 0x2, 0x2, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/src/github.com/spf13/cobra/command.go:593 +0x705
github.com/spf13/cobra.(*Command).ExecuteC(0xc0820698c0, 0xc0822ed200, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/src/github.com/spf13/cobra/command.go:683 +0x563
github.com/spf13/cobra.(*Command).Execute(0xc0820698c0, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/src/github.com/spf13/cobra/command.go:642 +0x34
github.com/docker/docker/cli/cobraadaptor.CobraAdaptor.run(0xc0820698c0, 0xc0820665a0, 0xc0820081c8, 0x3, 0xc082004360, 0x2, 0x2, 0x0, 0x0)
        /go/src/github.com/docker/docker/cli/cobraadaptor/adaptor.go:118 +0x266
github.com/docker/docker/cli/cobraadaptor.CobraAdaptor.Command.func1(0xc082004360, 0x2, 0x2, 0x0, 0x0)
        /go/src/github.com/docker/docker/cli/cobraadaptor/adaptor.go:126 +0x93
github.com/docker/docker/cli.(*Cli).Run(0xc0822f0d20, 0xc082004350, 0x3, 0x3, 0x0, 0x0)
        /go/src/github.com/docker/docker/cli/cli.go:81 +0x352
main.main()
        /go/src/github.com/docker/docker/cmd/docker/docker.go:72 +0x4b1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:116 +0x139
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x1f
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x3e

goroutine 6 [select]:
net/http.(*Transport).getConn(0xc0820a8780, 0xc0820527e0, 0x0, 0xcea578, 0x4, 0xc0822fd920, 0x19, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:714 +0x4f6
net/http.(*Transport).RoundTrip(0xc0820a8780, 0xc0820527e0, 0xc0820a8780, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:314 +0x7f0
net/http.send(0xc0820527e0, 0x15244e0, 0xc0820a8780, 0x0, 0x0, 0x0, 0xc082308640, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:260 +0x6be
net/http.(*Client).send(0xc0822f1440, 0xc0820527e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:155 +0x18c
net/http.(*Client).doFollowingRedirects(0xc0822f1440, 0xc0820527e0, 0xe69938, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:475 +0x8ab
net/http.(*Client).Do(0xc0822f1440, 0xc0820527e0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:191 +0x1eb
github.com/docker/engine-api/client/transport/cancellable.Do.func1(0x152db70, 0xc0822fc5c0, 0xc0820527e0, 0xc082306f00)
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:49 +0x3c
created by github.com/docker/engine-api/client/transport/cancellable.Do
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:52 +0x106

goroutine 8 [syscall, locked to thread]:
syscall.Syscall6(0x7ffad4c76bf0, 0x5, 0x274, 0xc08234bf54, 0xc08234bf58, 0xc08234bf60, 0xffffffff, 0x0, 0x1, 0x1, ...)
        /usr/local/go/src/runtime/syscall_windows.go:174 +0x5c
github.com/Microsoft/go-winio.getQueuedCompletionStatus(0x274, 0xc08234bf54, 0xc08234bf58, 0xc08234bf60, 0xffffffff, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/zsyscall.go:76 +0xb1
github.com/Microsoft/go-winio.ioCompletionProcessor(0x274)
        /go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/file.go:127 +0x7c
created by github.com/Microsoft/go-winio.initIo
        /go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/file.go:55 +0xb3
rax     0x0
rbx     0x111fe08
rcx     0x270
rdi     0x21e000
rsi     0xc08202f5f8
rbp     0x0
rsp     0x8fd88
r8      0x1
r9      0x0
r10     0x270
r11     0x13a4720
r12     0x2
r13     0xe66316
r14     0x3
r15     0x8
rip     0x18000890c
rflags  0x10246
cs      0x33
fs      0x53
gs      0x2b
### Steps to reproduce the behavior

  1. Install docker under windows 10
  2. open power shell
  3. type docker run ubuntu

**Comment by rneugeba** [comment]
Thanks for reporting. This issue was reported by a different user a couple of days ago as: https://github.com/docker/for-win/issues/140

this appears to be a upstream issue which is tracked in these two issues:
https://github.com/docker/docker/issues/27423
https://github.com/Microsoft/go-winio/issues/34
so I'm closing this in favour of the upstream issues.

**Comment by rneugeba** [comment]
@donut87 you may want to add your details to the issues I referenced.

**Comment by donut87** [comment]
I will do that. Thank you for the quick response.
