### ISSUE TITLE
Docker 17.12.0-ce-win47 (15139) not starting on Windows 10 Pro Build: 16299

### ISSUE THREAD

**Issue by ramanuj011** [docker/for-win#1563]
### Expected behavior
Start Docker for window
it should start docker for window
### Actual behavior
Starting fails with following error in log:
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[08:54:52.515][GUI            ][Info   ] Starting...
[08:54:52.531][GUI            ][Error  ] An instance is already running. Exiting.
### Information
Log:
Version: 17.12.0-ce-win47 (15139)
Channel: stable
Sha1: 9c692cd5b38166289573183371647d915f300292
Started on: 2018/01/16 08:54:52.031
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1709
Build: 16299
BuildLabName: 16299.15.amd64fre.rs3_release.170928-1534
File: C:\Users\ramakuma\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[08:54:52.515][GUI            ][Info   ] Starting...
[08:54:52.531][GUI            ][Error  ] An instance is already running. Exiting.

------------------------------------------------------------------------------------
**docker version**
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:22 2017
 OS/Arch:       windows/amd64

**Docker version 17.12.0-ce, build c97c6d6**

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...Install docker for windows on Windows 10 Pro Edition: Professional
      Id: 1709
     Build: 16299
     BuildLabName: 16299.15.amd64fre.rs3_release.170928-1534
  2. ...Start Docker for windows, it will fail.

**Comment by mborra** [comment]
I have the same issue, how I can to downgrade to old version?

Thanks

**Comment by felipeowen** [comment]
Also experiencing this issue.

It seems to be limited to Linux Containers though. To reproduce limitation:
1. When Docker is attempting to start, but before it fails, right click icon
2. Click "Switch to Windows Containers..." -- it will fail still, so...
3. Quit docker. 
4. Start docker again (in windows containers)
5. It will start.

That said, if you switch back to Linux containers, it will crash again.

**Comment by rrashmi1** [comment]
I also experienced same issue yesterday downloading recent upgrade. I dint check what @felipeowen has done. Sounds like this may work too. I downgraded the docker version by downloading old version which was stable for windows. 

Thanks

**Comment by BMarinov** [comment]
I have the exact same issue. 

Windows 10 Pro, Version 1709, 16299.192

The service seems to be running, but when I stop it I get an error (1067). None of the installers seems to be starting or showing up any window. I cannot uninstall or upgrade docker, tried older versions (up to 17.03) as well. Had to revert to Docker v 1.x

**Comment by morohe** [comment]
I have same issue too.
Maybe, this is Bad Mutex naming in "Docker for Windows.exe".

**Comment by morohe** [comment]
OK, I tested previous Docker,
Docker Community Edition 17.06.2-ce-win27 2017-09-06 (Stable)
(https://docs.docker.com/docker-for-windows/release-notes/)
is works for me.

**Comment by rrashmi1** [comment]
Hi

I think it  is old and stable version. I was working on 17.12 and dint work on windows 10. 


Please let me know if there are any improvements in recent release.


Thanks,
Rashmi

**Comment by stevenobird** [comment]
Same issue here - using Docker Community Edition 17.06.2-ce-win27 2017-09-06 (Stable) works.

**Comment by Drazke** [comment]
Same issue, got back to version 17.06.2-ce-win27 2017-09-06 (Stable) untill it's fix.

**Comment by rodrigoscna** [comment]
I was having the same issue here, but turns out that it was some kind of conflict with the Razer Synapse 3.
I simply closed it and now it works. I don't know if it's the only software that's conflicting with this version, but for me it worked!

**Comment by damianpowell** [comment]
Yep. Razer Synapse was the culprit for me too. Thanks, Rodrigo.

**Comment by Drazke** [comment]
Thank @rodrigoscna. It was the same for me.

**Comment by jehadassaf** [comment]
I wasted an entire day trying to figure out the issue. Thank you @rodrigoscna - fixed by exiting and uninstalling Razer Synapse. Docker started immediately after that (18.03.0-ce-win59 (16762))

**Comment by vedmichv** [comment]
I have the same issue and the solution just exit from Razer Synapse! 
Thank you @rodrigoscna!

**Comment by z0nekill** [comment]
I've been dealing with this issue for weeks now.. surely this is on Docker as it seems to be the only application conflicting with Synapse no? as a temp fix it's all good - but having Synapse uninstalled is not a practical solution moving forward?

@rodrigoscna good find btw - this was honestly doing my head in.

**Comment by z0nekill** [comment]
[#1301](https://github.com/docker/for-win/issues/1301) Same issue here - mutex naming conflict causing Docker to think it's already started. When it's actually detecting Razor Synapse and/or potentially Intel Thunderbolt running.

Solution:
Close Synapse & all running tasks _or_ uninstall (sad for your fancy Keyboard colors).
Restart Docker for Windows.

**Comment by hajimurtaza** [comment]
Expected Behaviour: Docker daemon should be running with latest version of docker

Actual Behaviour:

```
PS C:\WINDOWS\system32> Stop-Service docker
>> dockerd --unregister-service
>> dockerd -H npipe:// -H 0.0.0.0:2375 --register-service
>> Start-Service docker
dockerd : The term 'dockerd' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:2 char:1
+ dockerd --unregister-service
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (dockerd:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

dockerd : The term 'dockerd' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:3 char:1
+ dockerd -H npipe:// -H 0.0.0.0:2375 --register-service
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (dockerd:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\WINDOWS\system32> docker --version
Docker version 19.03.5, build 633a0ea
PS C:\WINDOWS\system32>
```
