### ISSUE TITLE
docker for windows lost it's eyes

### ISSUE THREAD

**Issue by godcong** [docker/for-win#1564]
Description

Steps to reproduce the issue:

install the newest docker
(Version 17.12.0-ce-win46 (15048)
Channel: stable
0ac7325)
start docker
Describe the results you received:
the docker status icon on the lower right corner, it's eyes not found

Describe the results you expected:
the docker status icon on the lower right corner, saw it's eyes

Additional information you deem important (e.g. issue happens only occasionally):

Output of docker version:
Client:
Version: 17.12.0-ce
API version: 1.35
Go version: go1.9.2
Git commit: c97c6d6
Built: Wed Dec 27 20:05:22 2017
OS/Arch: windows/amd64

Server:
Engine:
Version: 17.12.0-ce
API version: 1.35 (minimum version 1.12)
Go version: go1.9.2
Git commit: c97c6d6
Built: Wed Dec 27 20:12:29 2017
OS/Arch: linux/amd64
Experimental: true

Additional environment details (AWS, VirtualBox, physical, etc.):
window 10 prefessional

**Comment by godcong** [comment]
chinese has an idiom: bring the painted dragon to life by putting in the pupils of its eyes
i think the docker's eye is very important for it.

**Comment by friism** [comment]
Closing, the change is aligned with general use of the Docker logo and trademarks.

**Comment by godcong** [comment]
残念...
