### ISSUE TITLE
[Notifications  ][Error  ] Docker hv-sock proxy (vsudd) is not reachable

### ISSUE THREAD

**Issue by xiaoweizha** [docker/for-win#1566]
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. Diagnostic ID：E349D196-BFAE-427A-BE1F-21475AA7EE9A/2018-01-17_15-42-55
  2. docker version:Version 17.09.0-ce-win33 (13620)

**Comment by punmin** [comment]
solved it after set NameServer="reachable dns" in ...\Docker\settings.json

**Comment by awidjaja** [comment]
@punmin 
where is the full path of the settings.json file?

**Comment by jabassou-accenture** [comment]
@awidjaja 

C:\Users\[USER NAME]\AppData\Roaming\Docker\settings.json

**Comment by ctmcisco** [comment]
For anyone following this ticket:

Try the following:

1. Switch or stay on Windows Containers.
2. Disable the "Start when Windows starts" setting.


![image](https://user-images.githubusercontent.com/14852041/37053107-e9a96bd8-2140-11e8-9bdf-b264980b6127.png)

3. Exit Docker application
4. restart docker services via PowerShell

get-service *docker* | Restart-Service -Force -Verbose

5. Launch Docker , Run as Admin
6. Swtich to Linux Containers.

TEST:

Reboot Windows 10
Launch Docker 
Does it work?

You can also parse the docker log in PowerShell for troubleshooting:

cat C:\Users\USERPROFILE\AppData\Local\Docker\log.txt -tail 10 -wait

**Comment by rn** [comment]
@xiaoweizha I can't access the diagnostics. The upload may have failed due to firewall issues. Could you attach the logs to this issue?
Thanks
