### ISSUE TITLE
[Error] Unable to mount C drive: 10.0.75.1 (10.0.75.1:445) open

### ISSUE THREAD

**Issue by joe-gb** [docker/for-win#1569]
### Expected behavior
C drive should share

### Actual behavior
C drive does not share (D drive does)

### Information
48EE9B4D-1088-439D-A9A3-A86380892F35/2018-01-17_09-15-30

[09:14:17.146][SambaShare     ][Error  ] Unable to mount C drive: 10.0.75.1 (10.0.75.1:445) open

### Steps to reproduce the behavior
Open menu
>Shared drives
>Tick C drive
>Apply
>Enter password
>OK

**Comment by Eneuman** [comment]
Are your using a Microsoft Live Id or Azure Id to login to your computer? 
If so, you need to create a local account and then use that one to setup shared drives.

**Comment by joe-gb** [comment]
Nope, just a normal local admin account. tried a new one too.

**Comment by iciuperca** [comment]
D74D1B19-35BD-4EA1-9652-DB6AC2BDDA78/2018-02-02_12-30-00

Seems that as soon as I change any settings and hit apply my D drives becomes un-mountable. C drive seems fine. 

Resetting to factory defaults "solves" it, but as soon as I try to change anything and hit Apply the problem comes back.
