### ISSUE TITLE
docker commands hung/frozen on windows

### ISSUE THREAD

**Issue by mazad01** [docker/for-win#1579]
### Expected behavior
docker commands should run

### Actual behavior
most docker commands hang. i.e
PS C:\WINDOWS\system32> docker stats
PS C:\WINDOWS\system32> docker run -it microsoft/windowsservercore

### Information
  - Running docker 17.06.2-ee-6
  - Windows Server 2016 Standard 14393 as a hyper-v virtual machine under a Windows Server 2012r2 baremetal

**Comment by jasonbivins** [comment]
Hi @mazad01 
Since you're using Docker EE - you are entitled to support directly through Microsoft, and they will escalate to us if necessary.   I'll go ahead and close this one out, but please let us know if you continue to have issues.
