### ISSUE TITLE
Docker image rm sometimes leaves layers behind

### ISSUE THREAD

**Issue by davidmatson** [docker/for-win#1580]
### Expected behavior
Layers used only by this image are removed.

### Actual behavior
Layers used only by this image are still stored in C:\ProgramData\Docker\windowsfilter\ and C:\ProgramData\Docker\image\windowsfilter\layerdb\sha256\.

In this case, the layers were deleted from C:\ProgramData\Docker\image\windowsfilter\distribution\diffid-by-digest\sha256 and C:\ProgramData\Docker\image\windowsfilter\distribution\v2metadata-by-diffid\sha256
but I have seen cases where these directories are also not cleaned up.

### Information
I'm running Docker Community Edition 17.12.0-ce-win47 (15139) on Windows 10 1709.
Diagnostic ID: DEF60AD9-E6D5-4F8D-B336-CCE3B89FD713/2018-01-18_12-02-31

### Steps to reproduce the behavior

  1. docker run on an image, and then exit the container.
  2. docker container prune -f
  3. Immediately do docker image rm <imageid> (of the image run in step 1)

The following error message appears, and the folders mentioned above are not cleaned up (and apparently there is no way to clean up other than manually deleted the orphaned folders):
Error response from daemon: rename C:\ProgramData\Docker\windowsfilter\064796a25f21d50a78c0960827128160ffc39bc82ddb9b195da42338aa5ee255 C:\ProgramData\Docker\windowsfilter\064796a25f21d50a78c0960827128160ffc39bc82ddb9b195da42338aa5ee255-removing: Access is denied.

Should there at least be some kind of command to find orphaned layers and delete them?

**Comment by davidmatson** [comment]
Please re-open this issue.  I added the /remove-sicefycle stale comment as requested, but it didn't work.

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place?
