### ISSUE TITLE
docker images does not list all local images

### ISSUE THREAD

**Issue by ilias** [docker/for-win#1591]
### Expected behavior
docker images should report both 'alpine' and 'Microsoft/nanoserver:1709' images

### Actual behavior
Docker images reports only platform Linux images and not both Linux and windows

### Information

PS C:\temp> **docker images**
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
alpine              latest              3fd9065eaf02        11 days ago         6.55MB

PS C:\temp> **docker run -it alpine ls -la /**
total 56
drwxr-xr-x    1 root     root          4096 Jan 21 14:13 .
drwxr-xr-x    1 root     root          4096 Jan 21 14:13 ..
drwxr-xr-x    2 root     root          4096 Jan  9 19:37 bin
drwxr-xr-x    5 root     root           360 Jan 21 14:13 dev
drwxr-xr-x    1 root     root            60 Jan 21 14:13 etc
drwxr-xr-x    2 root     root          4096 Jan  9 19:37 home
drwxr-xr-x    5 root     root          4096 Jan  9 19:37 lib
drwxr-xr-x    5 root     root          4096 Jan  9 19:37 media
drwxr-xr-x    2 root     root          4096 Jan  9 19:37 mnt
dr-xr-xr-x  117 root     root             0 Jan 21 14:13 proc
drwx------    2 root     root          4096 Jan  9 19:37 root
drwxr-xr-x    2 root     root          4096 Jan  9 19:37 run
drwxr-xr-x    2 root     root          4096 Jan  9 19:37 sbin
drwxr-xr-x    2 root     root          4096 Jan  9 19:37 srv
dr-xr-xr-x   13 root     root             0 Jan 21 14:13 sys
drwxrwxrwt    2 root     root          4096 Jan  9 19:37 tmp
drwxr-xr-x    7 root     root          4096 Jan  9 19:37 usr
drwxr-xr-x   11 root     root          4096 Jan  9 19:37 var

PS C:\temp> **docker run -it microsoft/nanoserver:1709 cmd /s /c dir c:**
 Volume in drive C has no label.
 Volume Serial Number is 1C7F-993E

 Directory of C:\

09/29/2017  06:29 AM             1,894 License.txt
01/02/2018  10:23 PM    <DIR>          Users
01/21/2018  08:14 AM    <DIR>          Windows
               1 File(s)          1,894 bytes
               2 Dir(s)  21,212,254,208 bytes free

PS C:\temp> **docker ps -a**
CONTAINER ID        IMAGE                       COMMAND              CREATED              STATUS
 PORTS               NAMES
af1fa5a15c53        microsoft/nanoserver:1709   "cmd /s /c dir c:"   18 seconds ago       Exited (0) 16 seconds ago
                     unruffled_rosalind
df732180565c        alpine                      "ls -la /"           About a minute ago   Exited (0) About a minute ago
                     optimistic_aryabhata

PS C:\temp> **docker version**
Client:
 Version:       18.01.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    03596f5
 Built: Wed Jan 10 20:05:55 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.01.0-ce
  API version:  1.35 (minimum version 1.24)
  Go version:   go1.9.2
  Git commit:   03596f5
  Built:        Wed Jan 10 20:20:36 2018
  OS/Arch:      windows/amd64
  Experimental: true

PS C:\temp> **docker info**
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 3
Server Version: 18.01.0-ce
Storage Driver: windowsfilter (windows) lcow (linux)
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 15.85GiB
Name: ilias-yoga920
ID: I3BR:5SCF:VRER:CDRL:TRVP:YGPK:OE5L:MUTA:Z572:DWIO:VDFN:TZHY
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 25
 System Time: 2018-01-21T08:15:26.3607989-06:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

PS C:\temp> docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
alpine              latest              3fd9065eaf02        11 days ago         6.55MB

-----------------------
A diagnostic was uploaded with id: 2ACC4234-573A-40FD-A2C4-42A5C8ECF4DB/2018-01-21_08-28-31

**Comment by carlfischer1** [comment]
This is expected behavior using LCOW without https://github.com/moby/moby/pull/34859. Docker for Windows 18.02 will be the first version with that PR (or until then you can try a master build).

**Comment by ilias** [comment]
Thanks, I will try the mater build.

**Comment by jhowardmsft** [comment]
Yes, this is now fixed in master

**Comment by rn** [comment]
closing
