### ISSUE TITLE
Docker does not start

### ISSUE THREAD

**Issue by ankurmalik1978** [docker/for-win#1602]
On start, i get following error:
 create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
381770C4-7A9B-44FE-A067-B2E3246A2472/2018-01-23_23-11-28

**Comment by duprefm** [comment]
Same for me
