### ISSUE TITLE
Docker hv-sock proxy (vsudd) is not reachable

### ISSUE THREAD

**Issue by JohnLozano** [docker/for-win#1603]
### Expected behavior
Docker launches and is ready for me to use.
### Actual behavior
Startup hangs before reporting an error.
### Information
Diagnostic id:
B223B14F-615E-4EFB-953F-513B8A0A11AB/2018-01-23_17-43-41

Version: 18.01.0-ce-win48 (15285)
Channel: edge
Sha1: ee2282129dec07b8c67890bd26865c8eccdea88e
Started on: 2018/01/23 17:40:08.898
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1709
Build: 16299
  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. After computer startup, hit win key open start menu and search for Docker for Windows.
  2. Launch the Docker For Windows exe
  3. Wait around for docker to start.......
  4. Watch the world crash and burn.....

Totally understand that this may end up being a clone, but after reviewing other open/closed issues with the same title as this one, none reported this happening with 18.01.0-ce-win48-edge, or using Windows 10 pro.

I attempted fixes detailed in other issues, short of a full re install, with no luck.

**Comment by JohnLozano** [comment]
Revert to 17.06.2-ce-win27 (13194) using old installer. Seems the latest installer breaks the startup.

Found my problem similar to the issue below.
#1514

**Comment by ishaan18** [comment]
+1 Diagnostic ID: 162A18DD-324D-425C-A2BB-3E4F8690F002/2018-01-24_17-05-46

**Comment by froron** [comment]
I tried all of these things, and this is what worked for me/happened to me:
( running on Windows 10 Enterprise, latest version with all updates done )
- I finally downgraded docker to 17.06.2-ce-win27 from 17.12.0-ce-win47
- All seemed to work fine until I restarted the laptop. The error message was back.
- Tried running Docker for Windows as administrator (didn't help)
- Looked at the access rights for the Hyper-V folder in public (didn't help)
- I then logged out of docker cloud and tried to restart Docker for Windows as an administrator. For some reasons this worked, and docker is back up and running (version 17.06.2)

I tried to restart the laptop again and it started up fine (this time not running as administrator, and still not logged in to docker cloud).

**Comment by tannerchung** [comment]
@froron where did you get the 17.06.2-ce-win27 install file? And did you just run it or did you have to uninstall what was on your system?

**Comment by froron** [comment]
@tannerchung I found it in another thread, someone linked it. I uninstalled what was on the system before installing that. But after a day the error message was back. I then tried to go to the edge version of Docker. Still got the error. I then uninstalled that version. Restarted the computer! Installed the latest stable version. Think I restarted the computer again. I then started Docker for Windows in admin mode. Now it has been running for two days. :) Keeping my fingers crossed. You have to run the command line commands in admin mode as well.

**Comment by ctmcisco** [comment]
This works for STABLE and EDGE

Try the following:

1. Switch or stay on Windows Containers.
2. Disable the "Start when Windows starts" setting.


![image](https://user-images.githubusercontent.com/14852041/37053107-e9a96bd8-2140-11e8-9bdf-b264980b6127.png)

3. Exit Docker application
4. restart docker services via PowerShell

get-service *docker* | Restart-Service -Force -Verbose

5. Launch Docker , Run as Admin
6. Swtich to Linux Containers.

TEST:

Reboot Windows 10
Launch Docker 
Does it work?

You can also parse the docker log in PowerShell for troubleshooting:

cat C:\Users\USERPROFILE\AppData\Local\Docker\log.txt -tail 10 -wait

**Comment by SQLGeordie** [comment]
I am running a different version but getting the same error as this thread, tried various solutions (apart from reverting to previous version) offered but none seem to work. Windows containers are fine, Switch to Linux and it won't start :(

Version: 17.12.0-ce-win47 (15139)
Channel: stable
Started on: 2018/03/18 22:27:23.128
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1709
Build: 16299

Can anyone tell me where I can get a previous version from to test?

**Comment by kingaj12** [comment]
I just did basically what @ctmcisco recommended, except for step 3.  If we couple that with @froron experience, then it seems like the following trick works: 
* Switch off "Start Docker when you log in"
* Shut down Docker
* Restart it as Adminstrator

Now when I have to reboot (not very often with Windows 10), I restart Docker manually.  It seems to work fine now.

**Comment by rn** [comment]
I've looked at all supplied diagnostics in this issue and other "Docker hv-sock proxy (vsudd) is not reachable" and they seem to fall into three categories:

- Running Docker for Windows inside a Windows 10 VM. This is problematic as we have no visibility of your Windows VM configuration and activity on the host. Because of that we can't support this configuration. See also https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-for-windows-in-nested-virtualization-scenarios
- The Linux VM is very slow booting. Please take a look at: https://github.com/docker/for-win/issues/1995
- There was a linux kernel crash of some sort. Please take a look at: https://github.com/docker/for-win/issues/1994

If you have provided a diagnostics ID, I've added you to the relevant issue, so I'm closing this issue.
