### ISSUE TITLE
Docker doesn't start

### ISSUE THREAD

**Issue by ukluk** [docker/for-win#1609]
BF251725-1FC8-460F-8CFE-4D8E4FC46DFD/2018-01-24_17-08-37

But then if I restart it works. I don't believe it is connectivity

**Comment by nytope** [comment]
I got the same issue since I installed docker a week ago.
I did a diagnostic after restarting docker : 52AB30D4-59AA-4709-B29B-EF2A69C22F8A/2018-01-25_09-24-15

I also link with this comment my log file.
[log.zip](https://github.com/docker/for-win/files/1663154/log.zip)

**Comment by petegore** [comment]
Same behavior this morning. Error at start : 
```
Error response from daemon: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

Runs after restarting from the reset menu.

**Comment by muhammadfahad38765** [comment]
same issue here happening....
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.35/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

**Comment by davidrahusen** [comment]
same here :(

**Comment by JurassCZ** [comment]
Same here...
