### ISSUE TITLE
entropy support for pre-Ivy Bridge machines

### ISSUE THREAD

**Issue by justincormack** [docker/for-win#161]
See https://forums.docker.com/t/low-entropy-for-linux-containers-on-windows-host/21958/16 there are still machines around without `rdrand` support.

We could create an hvsock and feed randomness from the host potentially.

Or use haveged https://github.com/harbur/docker-haveged but needs network access.

**Comment by ocafebabe** [comment]
I was reading this thread about low entropy with Docker containers: http://stackoverflow.com/questions/26021181/not-enough-entropy-to-support-dev-random-in-docker-containers-running-in-boot2d

And one of the proposed solution is to mount  /dev/urandom from the host as /dev/random into the container! Would it be possible to mimic this in Docker for Windows?

**Comment by justincormack** [comment]
@ocafebabe no, because you could not cross mount a device from one OS to another, even if there was one.

**Comment by ocafebabe** [comment]
@justincormack ok thanks!

**Comment by jasonbivins** [comment]
Ivy-bridge CPU's have been marked end of life for a while now - I don't think this is an issue anymore
there is also no corresponding pinata issue to add support for this.
