### ISSUE TITLE
Latest Edge Release (18.01.0-ce) CLI is very slow

### ISSUE THREAD

**Issue by slafave** [docker/for-win#1610]
### Expected behavior
Running docker, docker-compose, etc. cmds have no noticeable latency

### Actual behavior
Running docker, docker-compose, etc. cmds have very noticeable latency, sometimes as much as 1.0 second.  Any CLI cmd.  Even something as simple as "docker ps".  The more you run the same cmd, the faster it returns, until it is almost as fast as the stable release.  If you wait even just 1 minute, the same cmd is back to hanging up to 1 sec.  Any cmd run for the first time will hang briefly before returning.

I'm reasonably certain this did **not** happen on the previous Edge release -> 17.12.0-ce-win45 2018-01-05 (Edge)

### Information

  - Diagnostic ID: A5DA733E-F0E6-4FCE-9066-01021758BEA2/2018-01-24_18-49-07
  - Windows 10 Enterprise 1709 16299.192
  - Edge Version 18.01.0-ce-win48 (15285)

### Steps to reproduce the behavior

  1. Install latest Stable release - 17.12.0-ce-win47 2018-01-12 using Linux containers
  2. Run any docker cmd like "docker ps" - response returns immediately
  3. Switch to Edge Version 18.01.0-ce-win48 (15285), using Linux containers (but not LCOW)
  4. Run any docker cmd like "docker ps" - response takes up to 1 sec to return

**Comment by josja** [comment]
Noticed it too, I was in the process of optimising CPU load for some containers, then I casually updated Docker Edge :)

Information:
- Diag ID: 0B4CB049-BB4B-42C0-9264-AA9990330117
- Apple OSX 10.13.2
- Edge 18.02.0-ce-rc1-mac50 (22256)

Reproduce:
- ```sudo docker-compose stop```
- Update Docker to Edge 18.02.0-ce-rc1-mac50 (22256)
- ```sudo docker-compose up``` / ```sudo docker-compose stop```

also stopping takes ages now.

But my containers are running smoothly on idle around 4% CPU. Just using docker or docker-compose is very sluggish.

**Comment by jtsalten** [comment]
Same happens to me with last edge version: 18.02.0-ce-rc1-win50 (15489)

**Comment by slafave** [comment]
agreed, issue still present in latest edge version: 18.02.0-ce-rc1-win50 (15489)

**Comment by hgati** [comment]
me too, edge version 18.02.0-ce-rc2-win51 (15631)

**Comment by pushamaku** [comment]
Same here..

Version 17.12.0-ce-win47 (15139)

**Comment by EberliAugusto** [comment]
Same on 18.03.0-ce-win59, running on windows 10. Using PowerShell.

**Comment by ramonmata** [comment]
Same here: Windows 10 PowerShell and CMD

Version 18.03.1-ce-win65 (17513)
Channel: stable
93354b3

**Comment by sadeghhp** [comment]
Docker version 18.03.1-ce, build 9ee9f40
very slow on every simple command like "docker -v"
