### ISSUE TITLE
Failed to install: Windows version not compatible

### ISSUE THREAD

**Issue by hollerbach** [docker/for-win#1620]
### Expected behavior

After installing Docker, on an updated Windows 10 Pro, everything should be operational. 

### Actual behavior

Docker is running, the LinuxVM is operational in the Hyper-V but...

![image](https://user-images.githubusercontent.com/1547092/35474721-53cad41a-0379-11e8-9fb1-b71f18a03411.png)

Every command respond with the same message:

C:\Users\holle> docker --version
Failed to install: Windows version not compatible. Check documentation for minimal requirements.

### Information

  - Diagnostic ID: 2D54774F-605C-4895-A71E-DAE5AA42E132/2018-01-27_11-56-40
  - host distribution and version:

![image](https://user-images.githubusercontent.com/1547092/35472646-44468b2a-035a-11e8-812a-b7f7efe9b804.png)

![image](https://user-images.githubusercontent.com/1547092/35474779-1c91cc0a-037a-11e8-8685-d777cef04024.png)

![image](https://user-images.githubusercontent.com/1547092/35472680-ca343642-035a-11e8-8275-9017ef507c76.png)

### Steps to reproduce the behavior

  1. ... Installed and tryed to run
  2. ...Removed everything (docker and hyper-v) and installed again. Same error.

**Comment by hollerbach** [comment]
![image](https://user-images.githubusercontent.com/1547092/35472680-ca343642-035a-11e8-8275-9017ef507c76.png)

**Comment by jasonbivins** [comment]
Hi  @hollerbach   What version/build of Windows 10 are you running?

**Comment by hollerbach** [comment]
hi...

![image](https://user-images.githubusercontent.com/1547092/35758037-059fb7da-0859-11e8-8c3b-f293e3a91924.png)

**Comment by sheridp** [comment]
I am also seeing this on Windows 10 Enterprise, 64bit (which was previously upgraded from Windows 7)

**Comment by nabeddev** [comment]
I also have the same problem, I can't install docker on my machine!
![image](https://user-images.githubusercontent.com/36706856/36562860-f3f9a126-1820-11e8-9c89-a93421e1b926.png)
My OS information:
![image](https://user-images.githubusercontent.com/36706856/36562978-626e8928-1821-11e8-9c2d-08c34e75f248.png)

**Comment by hollerbach** [comment]
@jasonbivins, anything about this issue ?

**Comment by insideAAC** [comment]
Same here with Win10 that was upgraded from Win7 .
On anothe System that has been upgraded from Win7 it is working fine.
