### ISSUE TITLE
18.02.0-ce windows containers not working

### ISSUE THREAD

**Issue by 4c74356b41** [docker/for-win#1622]
### Expected behavior
Windows and Linux containers working together
### Actual behavior
Cannot use Windows containers:
```
C:\ProgramData\Docker>  docker pull microsoft/nanoserver:1709
1709: Pulling from microsoft/nanoserver
407ada6e90de: Pulling fs layer
711a33cda32c: Pulling fs layer
image operating system "windows" cannot be used on this platform
```
### Information

Diagnostic ID: E1C05864-9E57-4D59-A590-E825F08FF7F3/2018-01-27_23-53-04
Case:
```
docker pull microsoft/powershell --platform Linux - works
docker pull microsoft/powershell --platform Windows - Invalid platform Windows
docker pull microsoft/nanoserver:1709 - image operating system "windows" cannot be used on this platform
```
Host:
```
Windows 10, 16299.192
Docker 18.02.0-ce-rc1-win50 (15489), channel edge 8b4cf93
```

Experimental option is set

**Comment by ansonlin** [comment]
1. Enable LCOW features
2. Enable Experimental option
3. Switch to Windows Containers

**Comment by 4c74356b41** [comment]
it will probably strike you as shocking, but 18.02.0-ce-rc1-win50 has got no lcow option. but switching to Windows containers did the trick
