### ISSUE TITLE
cannot run docker after install

### ISSUE THREAD

**Issue by lgh06** [docker/for-win#1624]
### Actual behavior
Error.
An error occurred.
### Information
C49B1A1E-5ECC-42A8-B6E7-998AF304F3DF/2018-01-29_00-30-53

外部组件发生异常。
   在 HVFiles.Connect(SafeSocket* , _GUID* , _GUID* , Int32 )
   在 HVFiles.Connect(SafeSocket* , _GUID* partition, _GUID* service) 位置 c:\gopath\src\github.com\docker\pinata\win\src\vendor\hvsock_cpp\includes\transport\connect.h:行号 23
   在 Docker.Win32Helpers.HVSockConnectivity.CheckConnectivity(Guid vmId, Guid serviceId) 位置 c:\gopath\src\github.com\docker\pinata\win\src\docker.win32helpers\hvsockconnectivity.cpp:行号 21
   在 Docker.Backend.HvSockChecker.WaitForConnectivity(Guid vmId, Guid serviceId, TimeSpan timeout) 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HVSockChecker.cs:行号 26
   在 Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId) 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:行号 291
   在 Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:行号 260
   在 Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:行号 130
   在 Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:行号 47
   在 Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:行号 145

**Comment by pedoc** [comment]
+1

**Comment by hsb0307** [comment]
i have the same problem too
