### ISSUE TITLE
Failed to switch because your Windows version is not compatible

### ISSUE THREAD

**Issue by mikebolland** [docker/for-win#1628]
### Expected behavior

Switch to Linux containers

### Actual behavior

Receive popup box "Failed to switch because your Windows version is not compatible"

![image](https://user-images.githubusercontent.com/34680015/35507736-ab2ad10c-04e5-11e8-9db0-f8d06a0b4637.png)

### Information

Diagnostic ID: ABCB-48B6-9F37-2A1FAA6FCC73/2018-01-29_11-15-27
Windows 10 Pro N 1709 Build 16299.192

### Steps to reproduce the behavior

  1. ... Click docker systray icon
  2. ... Click switch to linux containers

**Comment by mjhoffman65** [comment]
I'm running into this too

**Comment by anvinh** [comment]
I have the same issue. Window 10 Pro. I will try to reinstall Docker and see what happens then

**Comment by jasonbivins** [comment]
@mikebolland 
Can you submit another diagnostic please?  The one you posted got truncated somehow

**Comment by mikebolland** [comment]
@jasonbivins sure 0A48A31F-ABCB-48B6-9F37-2A1FAA6FCC73/2018-02-06_08-41-03

**Comment by wayne** [comment]
I can confirm this behavior as well, Windows 10 Pro and have reinstalled a few times trying edge and nightly etc... I also confirmed that under task manager performance CPU that virtualization is enabled.

**Comment by jasonbivins** [comment]
@mikebolland   It looks like Hyper-V might not be starting up right - can you open up Hyper-V manager and see if you can start and connect to any VM's ?

`Virtual machine 'MobyLinuxVM' could not be started because the hypervisor is not running.`

**Comment by Donil** [comment]
I had the same issue, because of "Hardware Accelerated Execution Manager", after update it to version 7 the docker works correct, but the android emulators (with hardware accelerator support) does not.

**Comment by AllamSudhakara** [comment]
I have this issue and could not resolve after reinstalling. Is this resolved? Could somebody please provide me details on how to resolve this issue?

**Comment by alexgman** [comment]
running into the same thing with this version of windows:

![image](https://user-images.githubusercontent.com/4227695/40377969-d6da66ca-5db7-11e8-89b9-b541b4c6040c.png)

**Comment by JDelekto** [comment]
@alexgman I had this problem as well and even though Hyper-V was enabled, I determined that virtualization was not enabled in my BIOS.  If you go to the Task Manager, and go to the "Performance" tab, look down in the lower right and ensure that "Virtualization" is set to "Enabled".   If it is not enabled, then determine where to enable Intel Virtualization in your BIOS, enable it, verify it is enabled when you boot back into Windows in the Task Manager.  It should work for you then.

**Comment by josephricafort** [comment]
I'm on Windows 10 Pro and experiencing the same thing, was this already resolved?

**Comment by JDelekto** [comment]
@josephricafort, have you checked to make sure both Hyper-V were running and that your computer's BIOS had virtualization enabled? In my case, Hyper-V was running (which I thought would have required the correct BIOS settings), but it was not configured in the BIOS.

This may be more of a configuration issue (I am using Windows 10 Pro Version 1803, OS Build 17134.48) and once I enabled this in the BIOS, the feature worked just fine.  Another note: I am using the latest stable (not edge) release of Docker.

**Comment by Arenaxe** [comment]
I faced with the same issue. 
OS: Microsoft Windows 10 Enterprise 10.0.15063 Build 15063
Docker: Version 18.03.1-ce-win65 (17513)

**Comment by mike-aungsan** [comment]
Having the same issue.

**Comment by thinhbk** [comment]
Having the same issue here, systeminfo:
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.14393 N/A Build 14393

Docker CE version: 
> docker --version
Docker version 18.03.1-ce, build 9ee9f40

**Comment by amitku43** [comment]
I am also having the same issue. Have it been resolved for anyone?

**Comment by fachilles** [comment]
Did anyone get the official solution until now?

**Comment by shasu01** [comment]
Hi I am trying to get around this issue. Any solutions?

**Comment by dermeister0** [comment]
@shasu01 
Probably Hyper-V does not work on your PC. It may be turned off.

**Comment by pluczak99** [comment]
Hyper-V is enabled, experimental features in Settings of Docker are enabled too. That annoying message still gets displayed on WIn 10 Enterprise x64 (with all current updates).

This stuff is extremely annoying. I use Docker on a laptop with WIn 10 E x64 as the primary OS and it forces me to use 2nd boot SSD for Linux images.

Does Docker give a sh*t? It doesn't seem so since it's been 10 months since the original posting. Docker, please do give a sh*t.

**Comment by pluczak99** [comment]
> Did anyone get the official solution until now?

Yeah, the official solution is "we pretend there is no problem" (or possibly, "you users are too dumb to use Docker properly so we'll just respond with silence for all those newbies who can't RTFM". 

Seriously, Nov 30 2018 - Win 10 Enterprise x64 with all current updates - same dumb message.

**Comment by pluczak99** [comment]
![image](https://user-images.githubusercontent.com/29517725/49265850-25003180-f454-11e8-83c6-a53ee34ac055.png)

**Comment by gabrieljoelc** [comment]
I believe these are some similar but closed issues: #1905 and #2336

**Comment by gabrieljoelc** [comment]
I was able to get past this error by using the solution in https://github.com/docker/for-win/issues/1905#issuecomment-378401509. I enabled the Intel CPU virtualization in the BIOS and successfully switch to the Linux engine.

**Comment by hshivhare** [comment]
This issue can be resolved by disabling and then reenabling Hyper-V.

**Comment by DSMP** [comment]
use this commands in cmd: 
`bcdedit /set hypervisorlaunchtype auto `
and restart computer
if not help try in power shell
`Disable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V-All`
then restart computer.

For fast resolve type this command both in cmd and PS then restart once.

I think it's something wrong on "turn windows features on or off" and its checked or not, but its not disabling and not enabling hyper-v correctly. So use thease commands to enabling and disabling hyper-v.

**Comment by nomansadiq11** [comment]
**Solved by enable the virtualization from BIOS**, I don't remember when I disabled this.

**Comment by chiragch** [comment]
Open Control Panel.
Click on Programs.
Click on Turn Windows features on or off.
A Windows Features pop-up box appears and you'll need to check the Hyper-V option. ...
Click OK.
restart your computer

**Comment by DSMP** [comment]
@Chiragch

Its not always work. For me its not. To definitly disabling u should do what i describe two posts above.
