### ISSUE TITLE
Allow changing vhdx path

### ISSUE THREAD

**Issue by Thog** [docker/for-win#163]
It would be nice to be able to change the path of the MobyLinuxVM virtual drive on the GUI instead of having to tweak it under PowerShell...

**Comment by ctaggart** [comment]
@Thog How do you tweak it currently under PowerShell?

My C: drive is out of space and I want to use `G:\Hyper-V\Virtual hard disks\MobyLinuxVM.vhdx` instead of `C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx`, but it keeps getting reset in Hyper-V after I change it.

**Comment by Thog** [comment]
@ctaggart I have used the [Hyper-V API](https://technet.microsoft.com/fr-fr/library/hh848559.aspx?f=255&MSPPError=-2147217396) provided to remove and readd the VHDX disk but I think that you can use the Hyper-V GUI to do that more easily

**Comment by rneugeba** [comment]
The VHDX is created in the default path for system, which can be queried in an elevated powershell with:
```
(get-vmhost).VirtualHardDiskPath
```

You can set the default location to a different path by using:
```
Set-VMHost -VirtualHardDiskPath <path>
```

If you then perform a factory reset or un-install/re-install Docker for Windows it does use the new path. The setting also persists across reboots.

Note, this causes all newly created VMs VHDXs being placed in the new path, but may work as a workaround for now.

/cc @SaschaNaz

**Comment by SaschaNaz** [comment]
Thank you for posting the workaround. I'm curious how Docker can reset my VM setting when I change vhdx path for MobyLinuxVM, not default one. I think Docker must be saving the path somewhere to do this.

**Comment by rneugeba** [comment]
We just release Beta33 which has a new settings option in the advanced tab to change the location of the VHDX file. Closing this issue

**Comment by joaociocca** [comment]
@rn workaround solved here, but the GUI option does nothing =(
