### ISSUE TITLE
qemu no kvm support

### ISSUE THREAD

**Issue by Mathiasdm** [docker/for-win#1630]
### Expected behavior

qemu in a Linux container can be started with kvm support like: qemu-system-x86_64 --enable-kvm
One of our benchmarks runs in ~15 seconds.

### Actual behavior

qemu cannot start with kvm support: "Could not access KVM kernel module: No such file or directory"
One of our benchmarks takes ~4-5 minutes.

### Information

- Docker version: Version 17.12.0-ce-win47 (15139)

### Comments

I think resolving this performance problem requires adding kvm to the Alpine Linux host kernel (I don't know how doable that is).

**Comment by rn** [comment]
For this to work nested virt needs to be enabled in Hyper-V (https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/nested-virtualization). We are looking into enabling it but the technology is complex and it's not clear how mature it is.ccccccgnddfgdvthhlucvrhtibdhfngdtjlegvcnkkku

**Comment by trinhpham** [comment]
Reactivate this to ask if we can support such kind of image: [docker-android](https://github.com/budtmo/docker-android)

/remove-lifecycle stale
/lifecycle frozen
