### ISSUE TITLE
Cannot enable Hyper-V and Containers Feature

### ISSUE THREAD

**Issue by ctjoumas** [docker/for-win#1631]
### Expected behavior
Docker for Windows has all services started, starts up, and runs properly

### Actual behavior
Cannot enable Docker services after install

### Information

  - I tried installing Docker for Windows already and was not able to get it to work. I've uninstalled and re-installed, and things seem to maybe be a bit different as there is no reboot during installation, but I'm not sure if that happened the first time I installed or not.
  - My user is in the Administrators group
  - Virtualization is enabled
  - Running Windows 10 Enterprise, version 1709, OS Build 16299.125
  - After running through steps below, in the turn features on/off window, "Containers" remains unchecked and under Hyper-V, "Hyper-V Platform" is checked, but "Hyper-V Management Tools" is unchecked. As stated in step 7 below, I can enable these manually here and it will do something and ask me to reboot, but the unchecked items I listed here remain unchecked upon my computer restarting

### Steps to reproduce the behavior

  1. Install docker for windows (Stable) - 17.12.0-ce-win47 (it unpacks files and installs)
  2. Installation Succeeded message appears; click Close button
  3. Start Docker ("Docker is starting..." message appears in the task bar)
  4. Message pops up stating "Hyper-V and Containers features are not enabled. Do you want to enable them for Docker to be able to work properly? Your computer will restart automatically." I click OK.
  5. Click OK
  6. After 30 seconds or so, a dialog pops up stating "An error occurred. Docker failed to enable Hyper-V and Containers. Please enable those features manually for Docker to be able to work properly. To enable hyperV, follow the instructions here: https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v"
  7. I've tried the PowerShell option, the DISM option, and the turn features on/off option. Each option does "something" and then asks to reboot and when i do, docker is attempted to be started when windows returns and we go back to step 4 above.

**Comment by 10Dev** [comment]
Just passing by, but off the top of my head, you don't have a Docker technical issue, just a poorly worded error message that is pointing you in the wrong direction and should be fixed.

You have a Hyper-V not working issue which could be CPU missing SLAT, Group Policy prevention, BIOS setting, corrupt Windows Install etc.

**Comment by ctjoumas** [comment]
Yea, I think you're exactly right. That's the conclusion I've come to. I believe it may be a group policy issue but so far nothing I've tried has fixed it. I may need to bite the bullet and re-install my OS. Thanks.

**Comment by martinandersen3d** [comment]
Any solution to this?

I have also VirtualBox Installed and it says it wont work after reboot :(

**Comment by ViniciusAtaide** [comment]
Just got by this issue and resolved by myself, the Hyper-V manager in windows showed that MobyLinuxVM was installed but wasn't on, so I started manually the VM and then Docker was started sucessfully, hope I could help.

**Comment by ctjoumas** [comment]
Glad you were able to resolve it! My problem is Hyper-V isn't getting installed... so as 10Dev mentioned, it's not a Docker issue, but a Hyper-V issue. I am out of ideas though :)

**Comment by GunayAnach** [comment]
Had exactly same issue with Windows 10 today. Seems like an update **KB4074588** didn't get installed and was preventing container and Hyper-V Features to be installed as well. 

Try to runs this in admin CMD
**`SC config trustedinstaller start=auto`**

Of course I assume you have already tried the following:
- You have Virtualization supported Windows 10 version (PRO, etc)
- You PC hardware supports virtualization. If not sure run `systeminfo` in admin CMD and you should see at the bottom all virtualizations marked as **Yes**
- Enabled Virtualization (Hyper-V, etc) in your BIOS
- [Microsoft's guide to enable virtualization manually](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v") if Docker fails to enable it for you
- If you are connected to Active Domain (company computer/network) there are no policies preventing virtualization

**Comment by chowdam** [comment]
am facing same issue...tried all options....any one please help me.....

**Comment by paulvi** [comment]
@chowdam Create new issue and reference this.

**Comment by thegulshankumar** [comment]
I had Hyper-V enabled, was still getting error. This is how I fixed it -

**Solution**
1. Open CMD as administrator
2. Enter below command
`bcdedit /set HypervisorLaunchType auto`
3. Restart System.

This worked for me. Tip Source: https://youtu.be/UeSdC5xhOoQ?t=35
