### ISSUE TITLE
Windows Docker container does not have internet acces due to proxy

### ISSUE THREAD

**Issue by danielhalati** [docker/for-win#1633]
Hello all,

I am trying to use a Docker Windows image: microsoft/windowsservercore.
I need to install chocolatey to be able to install several tools. For any Powershell command that I type I need to provide the proxy setting and some of the commands does not have proxy settings as arguments.

I want to be able to use commands with some proxy settings defined globally. Setting HTTP_PROXY or HTTPS_PROXY has no effect.

**Comment by McCzarny** [comment]
Here You can find solution:
`https://github.com/McCzarny/windowsservercore_proxy`

**Comment by danielhalati** [comment]
Thanks for the reply. This works.
