### ISSUE TITLE
Unable to start docker on windows preview 17074

### ISSUE THREAD

**Issue by dnelly** [docker/for-win#1635]
### Expected behavior
Docker to run normally
### Actual behavior
It fails with an error at computer started up and will never run.

### Information

  - Diagnostic ID BCD76875-2ED0-4004-90F0-DAEDF90F4A84/2018-01-30_10-27-36

### Steps to reproduce the behavior

  1. Update to lastest windows preview build 17074 
  2. Install docker

**Comment by Johannestegner** [comment]
Same issue as with last preview build and latest docker versions. Go back to 17.09.1 and it will run fine though. :'(

**Comment by dnelly** [comment]
That's unfortunate because I liked this version.

**Comment by jasonbivins** [comment]
hi @dnelly   If you have the Docker whale icon in your systray - right click it and switch to Windows containers and see if it starts up that way.
