### ISSUE TITLE
Unable to share C drive

### ISSUE THREAD

**Issue by baerrar1** [docker/for-win#1637]
### Expected behavior
C drive is shared.

### Actual behavior
C drive is not shared. 

The log file contains lots of CIFS related error messages:
08:27:35.169][Moby           ][Info   ] [  875.879999] CIFS VFS: No username specified
[08:27:35.192][Moby           ][Info   ] [  875.898187] CIFS VFS: SMB3 encryption not supported yet
[08:27:35.223][Moby           ][Info   ] [  875.926096] CIFS VFS: SMB3 encryption not supported yet
[08:27:35.258][Moby           ][Info   ] [  875.950051] CIFS VFS: SMB signature verification returned error = -13
[08:27:35.276][Moby           ][Info   ] [  875.985131] CIFS VFS: SMB signature verification returned error = -13
[08:27:35.296][Moby           ][Info   ] [  876.002247] CIFS VFS: cifs_put_smb_ses: Session Logoff failure rc=-13
[08:27:35.314][Moby           ][Info   ] [  876.022740] CIFS VFS: cifs_mount failed w/return code = -13

If I enter "run --rm -v c:/Users:/data alpine ls /data" I'm asked for the credentials again. After credentials are entered I get the following error message:
docker: Error response from daemon: An error occured while sharing drive.

### Information

  - Diagnostic ID: E8A678AA-1BFB-4A88-B88E-0E7DD81F2347/2018-01-31_08-15-37
  - Docker version
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:22 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:29 2017
  OS/Arch:      linux/amd64
  Experimental: true

- Windows version:
  OS Name:                   Microsoft Windows 10 Enterprise
  OS Version:                10.0.14393 N/A Build 14393

### Steps to reproduce the behavior
1. Open the Docker settings dialog
2. Select Shared Drives
3. Select the C drive and click on apply
4. Dialog pops up asking for my credentials. 
5. After credentials are entered the UI is disabled for a while. 
6. After is enabled again the C drive is not checked in the dialog

**Comment by drobert8584** [comment]
Same issue : 

Informations : 
Diag : F12E0B1B-C970-4AD4-A772-D3458955A274/2018-01-31_11-22-40
Version: 17.12.0-ce-win47 (15139)
Channel: stable
Sha1: 9c692cd5b38166289573183371647d915f300292
Started on: 2018/01/31 11:16:08.085
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1709
Build: 16299
BuildLabName: 16299.15.amd64fre.rs3_release.170928-1534
File: C:\Users\Damien\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe"

**Comment by fjordBob** [comment]
Same issue here as @baerrar1 described.

**Comment by jochenvanwylick** [comment]
+1

**Comment by baerrar1** [comment]
Finally I figured out what the root cause for the problem was - actually it's what the error message "SMB3 encryption not supported yet" says. On my machine SMB encryption was enabled, This can easily be check in the powershell via the command Get-SmbServerConfiguration. Disabling the encryption is done via Set-SmbServerConfiguration -EncryptData 0.

**Comment by kal** [comment]
Just in case anyone else finds this issue via Google as I did, I had the same symptoms described here. But the fix was slightly different. The fix for me was to enable SMB2 via `Set-SmbServerConfiguration -EnableSMB2Protocol $true`

**Comment by m4rc77** [comment]
@baerrar1 you saved my day, thanks a lot! We were searching for more than a week why were unable to mount volumes into docker under Win10. 
The `Set-SmbServerConfiguration -EncryptData 0` command solved the issue.

**Comment by maruthihr** [comment]
> Finally I figured out what the root cause for the problem was - actually it's what the error message "SMB3 encryption not supported yet" says. On my machine SMB encryption was enabled, This can easily be check in the powershell via the command Get-SmbServerConfiguration. Disabling the encryption is done via Set-SmbServerConfiguration -EncryptData 0.

I had the same issue and was resolved by disabling encryption. What does this mean in terms of security particularly in the corporate setup?

**Comment by miroslavvojtus** [comment]
\reopen

Disabling of encryption is definitely not an option. If the host uses sharing extensively on confidential data having any kind of un-encrypted communication is unacceptable vulnerability to any (especially corporate) environment.

Please update how the sharing is done to support standard corporate setup.

1. We have allowed only SMB3 sharing - Docker Desktop uses SMB1 & SMB2 somehow as I had to enable it
1. We have enforced SMB encryption by group policy - Docker Desktop does not support encrypted sharing

❗️ **Reducing security is NO GO for a lot of users** ❗️

**Comment by pnilesh1** [comment]
In my case i restarted the desktop docker and then i tried to share it and it worked for me.
