### ISSUE TITLE
Docker cannot connect to Hyper-V container

### ISSUE THREAD

**Issue by mikeywashere** [docker/for-win#164]
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

371e06e9-329b-4548-b3f0-9c00854ff8f3

### Steps to reproduce the behavior

![image](https://cloud.githubusercontent.com/assets/12192549/19623651/c5ffdd0a-9886-11e6-92ab-ee3a64c0e8dc.png)

Just trying to start docker. Same error every single time.
[log.txt](https://github.com/docker/for-win/files/546128/log.txt)

**Comment by simonferquel** [comment]
Some insider preview builds have their Hyper-V / Container support broken. I suggest you retry with the latest stable (anniversary update)

**Comment by rneugeba** [comment]
Microsoft have a tool https://github.com/Microsoft/Virtualization-Documentation/blob/master/windows-server-container-tools/Debug-ContainerHost which checks for common/known problems. Could you try that?
Thanks

**Comment by rneugeba** [comment]
Closing this issue as the requested information has not been supplied. Please re-open if the `Debug-ContainerHost` utility mentioned above suggests it should work but it doesn't. Thanks
