### ISSUE TITLE
swarm service starts and shuts down immediately

### ISSUE THREAD

**Issue by dreamflame51** [docker/for-win#1643]
Hi there!

I'm having a problem with swarm service creation on Windows 2016.
0ot6e2og9tdrw5f8a4p43pjeg
overall progress: 0 out of 1 tasks
1/1: starting  [============================================>      ]
verify: Detected task failure

service just keeps restarting.
There are 3 nodes in a swarm, but I cannot start a service even on single.

docker swarm init --advertise-addr=10.11.91.130 --listen-addr=10.11.91.130:2377
docker swarm join --token SWMTKN-1-4615lwxk8wbklyj8v3jebkeo1efaxko8lqgmiexmh3pwla2knf-5zv9pjmv0ph4q1iyza9i0zn2y 10.11.91.130:2377
docker network create -d overlay sma_net
docker service create --name sma --endpoint-mode=dnsrr --network=sma_net  microsoft/windowsservercore cmd

There seems to be a fatal error while creating a container, but as I am all new to swarm and docker I'm not sure where to start troubleshooting.
Attaching part of the log and docker info.

Thanks!

[dockerInfo.txt](https://github.com/docker/for-win/files/1685393/dockerInfo.txt)
[log.txt](https://github.com/docker/for-win/files/1685388/log.txt)

**Comment by jasonbivins** [comment]
Hi @dreamflame51 
Can you check to make sure Hyper-V is functioning correctly?  Just make sure you can start any VM, and then connect to it.  
It could also be related to AV scanning on the C:\programdata\docker folder.

`encountered an error during CreateContainer: failure in a Windows system call: Server execution failed (0x80080005) extra info: `

**Comment by dreamflame51** [comment]
Hi @jasonbivins
Thanks for the answer! 
I think it does for I was able to create 300+ docker containers with a run command and those were working fine, but not the swarm.
AV is a possible thing!I'll try to add and exception for this folder once I'm back in the office.

**Comment by dreamflame51** [comment]
@jasonbivins
I've added exceptions to AV, still no luck. then checked if I could run VM on my Hyper-v, there was an error that some component is not running. I searched online and found this:
https://www.settlersoman.com/how-to-installrun-hyper-v-host-as-a-vmnested-on-vsphere-5-or-6/
It did it's trick, I was able to run a VM then.

Still unable to run the service denied access to images.
Even though docker login was done and image exists locally
 
Attaching log.
[log.txt](https://github.com/docker/for-win/files/1689068/log.txt)

**Comment by wijnandhonselaar** [comment]
Hi @dreamflame51 
I'm in the same boat. Windows containers are running without issues when spinning them up using `docker run`, but placing ANY Windows container in a Swarm results in endless failure. 
Windows 10 Enterprise 1709
Problem occurs using either Docker 18.02.0-ce-rc2 or 17.12.0-ce.

**Comment by dreamflame51** [comment]
what log is saying? anything in common with mine?

**Comment by dreamflame51** [comment]
[14:59:15.791][WindowsDaemon  ][Info   ] debug: FIXME: Got an API for which error does not match any expected type!!!: errors:
denied: requested access to the resource is denied
unauthorized: authentication required
 [module=api error_type=errcode.Errors]
[14:59:15.792][WindowsDaemon  ][Error  ] Handler for GET /v1.30/distribution/dreamflame51/sma:latest/json returned error: errors:
denied: requested access to the resource is denied
unauthorized: authentication required

anything similar?

**Comment by wijnandhonselaar** [comment]
How do I get the whole error from: `docker stack ps stack_name`? I can only read: `HMS failed with error : An ad...`

**Comment by dreamflame51** [comment]
Cannot you just check it in the docker log file? default location: C:\Users\admin1\AppData\Local\Docker\

**Comment by dreamflame51** [comment]
yeah, you have issue with networking.
check the solution below, who knows, maybe might work for you.
https://github.com/docker/for-win/issues/1585#issuecomment-362891777

**Comment by rn** [comment]
This issue tracker is for the Docker for Windows application, which runs on Windows 10. To get help with Docker on Windows Server please see http://success.docker.com/article/where-to-get-help-with-windows.
Thanks
