### ISSUE TITLE
Update to another channel confirmation box with identical versions can be displayed

### ISSUE THREAD

**Issue by AlekseyMartynov** [docker/for-win#1646]
Screenshot:

![untitled-1](https://user-images.githubusercontent.com/4426185/35696653-164f69ce-0799-11e8-9882-79d4053f1270.png)

**Comment by jasonbivins** [comment]
Hi @AlekseyMartynov 
Can you please provide more details on how you got this box to popup so that I can try to repro?

**Comment by AlekseyMartynov** [comment]
- Make sure the Edge channel is current
- Click "You can switch to another version" from settings
- Don't touch the select box, click Install
