### ISSUE TITLE
Docker seems to conflicting with my external sound card

### ISSUE THREAD

**Issue by mrdj07** [docker/for-win#1647]
I run Docker for Windows on my Windows 10 machine, and Docker works pretty flawlessly.

The issue I have is relative to sound... But not within docker.

Let's say I have Google Music open, enjoying a couple of tunes. Everything works fine as long as Docker is not running, like not running at all. If Docker is running and sound is in use, the moments Docker seems to be 'executing' something, the music/sound cuts off. If I'm playing a youtube video while this happens, it's like if the video would be buffering. But it's not ! This problem is not related to the browser, or the internet connection. Having an mp3 open on the default Windows media player will do the same.

I have an external sound card, a Focusrite Scarlet 2i4, 1st generation. The interesting thing is that this does NOT happen when USB headphones are in use. This exclusively happens when I am using my Focusrite soundcard.

  - 253F69D1-35C5-48C0-9217-11138593B207/2018-02-01_20-23-57

**Comment by mrdj07** [comment]
As of today, this does not seem like an issue anymore.

**Comment by rn** [comment]
@mrdj07 thanks for reporting back. It does seem to have been a very weird issue and Docker for Windows is certainly not doing anything special. We just use normal Hyper-V VMs and go no-where near sound cards and the like.

Glad the issue is fixed for you
