### ISSUE TITLE
Cannot run a container after fresh install on Windows 10 if Docker Toolbox was installed before

### ISSUE THREAD

**Issue by apupier** [docker/for-win#165]
### Expected behavior

- no error when launching docker run hello-world on a fresh install
- alert user that some environment variables are set that will prevent the usage of docker

### Actual behavior

fail to execute basic command docker run hello-world

### Information

  - 1A75BB5B-FE64-4BCE-AB42-09775FB3F977/2016-10-23_14-50-46
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - Windows 10 - Docker Version 1.12.1-stable (build: 7135) 995236d

The log file: [log.txt](https://github.com/docker/for-win/files/546345/log.txt)
the only line in error is

`[14:50:53.997][VpnKit         ][Error  ] com.docker.slirp.exe: TCP 192.168.65.2:42546 > 104.239.220.248:80 proxy failed with flow proxy b: Connection refused`

### Steps to reproduce the behavior

  1. Install Docker Toolbox
  2. Install Docker for windows
  3. try docker run hello-world
  4. error:

> docker run hello-world
docker: An error occurred trying to connect: Post https://10.1.2.2:2376/v1.24/containers/create: dial tcp 10.1.2.2:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond..
See 'docker run --help'.

Workaround: remove all environment variables related to Docker toolbox

**Comment by rneugeba** [comment]
@apupier thanks for your report. Do you, by any chance, have the  `DOCKER_HOST` environment variable set? If so, could you unset it and try again? Unlike Docker Toolbox, with Docker for Windows you don't need to have any environment variables set, except for the PATH.

**Comment by apupier** [comment]
@rneugeba Thanks!! it was that, I had several environment variables set. I remove dal lof them and it works. I will rename the issue.

**Comment by rneugeba** [comment]
Glad it is now working for you (and it was an easy fix). Thanks for renaming the issue, it might help other users to find it.

This is actually documented in the troubleshoot documentaion section under: https://docs.docker.com/docker-for-windows/troubleshoot/#/unset-dockerhost
It's not very prominent as we don't seem to have many users reporting an issue with it anymore.

I'll close this issue for now

**Comment by kuntalakrishna** [comment]
> @apupier thanks for your report. Do you, by any chance, have the `DOCKER_HOST` environment variable set? If so, could you unset it and try again? Unlike Docker Toolbox, with Docker for Windows you don't need to have any environment variables set, except for the PATH.

Thank god.. you saved my day..
