### ISSUE TITLE
Docker fogets shared drives after restart if they are not present

### ISSUE THREAD

**Issue by tomasfejfar** [docker/for-win#1650]
### Steps to reproduce
* file based BitLocker encrypted filesystem (say `Q:`)
* when I log to windows in I need to fill the password for that drive. 
* drive is displayed and accessible
* I share the drive in Docker for Windows UI
* I can mount volumes from `Q:` to docker containers
* I restart

### Expected behavior
* I can still mount volumes from `Q:` to docker containers after restart

### Actual behavior
* I cannot. Docker complains that the drive is not shared. 
* the checkbox in UI is still checked, so uncheck, check, apply is needed. 

### Information

I suspect the issue might be that the drive is not available when DfW is starting.

**Comment by pgayvallet** [comment]
We are indeed only trying to mount the shared drives at app startup ad when updating the shared drive, So If the drive if not present at app boot, if will not be available until re-enabled from the options.

**Comment by pgayvallet** [comment]
Created internal issue for this one. We still have to discuss if we really do want to permanently watch for mount/dismount event to handle this case.

**Comment by tomasfejfar** [comment]
I understand that this may not be a very common issue. I would be quite happy with a workaround - for example, ability to (re)mount it from CLI would be enough.

**Comment by tomasfejfar** [comment]
JFYI it did not happen again yet with latest stable Docker for Windows.

**Comment by GANG-CHEN-1** [comment]
@tomasfejfar  have you got any workaround or solution to share C or D drives on Windows by command line?

**Comment by tomasfejfar** [comment]
Yes actually it was the case that I used https://github.com/Disassembler0/Win10-Initial-Setup-Script and I disabled some of the required services. I think the main problem was disabled Samba v1 share (which is default) though. DfW (or rather the linux and CIFS in the VM) could not use the "new" Samba version. Enabling legacy Samba fixed the issue for me.
