### ISSUE TITLE
Connection from Win10 - Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by syncgw** [docker/for-win#1652]
Installed / deinstalled docker a couple of time (with reboot in between).

Cmd: `docker login`
```
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

Diagnostic ID: 3E445919-9789-4ABC-BD0B-EBFF46F9D614/2018-02-03_16-25-02
Tried 8.8.8.8 and 8.8.4.4 as DNS - did not help
No Proxy in place.
Microsoft Windows [Version 10.0.16299.192]
WLAN: Connection rate (MBit/s)  : 433.3

 ```
Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:22 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:29 2017
  OS/Arch:      linux/amd64
  Experimental: true
```

**Comment by syncgw** [comment]
I check checked a couple of issues regarding this topic. **Seems this is a real connection timing problem.** Would be great if this can be fixed.

You have always to update `C:\Windows\System32\drivers\etc\hosts`. Ping server to get the IP address...

- Started  with `docker search redis`

`Error response from daemon: Get https://index.docker.io/v1/search?q=redis&n=25: dial tcp: lookup index.docker.io on 192.168.65.1:53: read udp 192.168.65.3:52420->192.168.65.1:53: i/o timeout`

**Quick solution:** Add the following line to `hosts`: `52.3.153.154 index.docker.io`

- Tried  `docker run hello-world`

```
Unable to find image 'hello-world:latest' locally
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
```
**Quick solution:** Add all server which appears in different error messages to `hosts`: 

```
52.3.153.154	index.docker.io
34.200.28.105 	registry.docker.io
52.20.146.203 	registry-1.docker.io
54.152.209.167 	auth.docker.io
52.222.149.24	dseasb33srnrn.cloudfront.net
```

- Coming back to my initial problem `docker login`

```
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

```
**Quick solution:** Since `registry-1.docker.io` is already in my `hosts` this approach did not solve all of my problems :-( ...

**Comment by tylenh** [comment]
Thanks, adding the ip's in the hosts file sorted this challenge for me

**Comment by jonasf** [comment]
For me unblocking C:\Program Files\Docker\Docker\resources\vpnkit.exe in my company mandated F-Secure firewall did the trick.

**Comment by hawkeagle** [comment]
does docker community support ipv6?

**Comment by kitingChris** [comment]
One of my collegues had the very same issue. The current solution that seems to work is to set the DNS to 8.8.8.8 (or 9.9.9.9 or any other public DNS if you do not want google) in the Networks tab of the Docker Settings.

[https://docs.docker.com/v17.09/docker-for-windows/#network](https://docs.docker.com/v17.09/docker-for-windows/#network)
