### ISSUE TITLE
Client.Timeout on docker login, docker run hello-world

### ISSUE THREAD

**Issue by ajhoddinott** [docker/for-win#1655]
### Expected behavior

docker login should prompt for username and password then login.
docker run hello-world should pull hello-world and run it.

### Actual behavior

docker login:
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

docker run hello-world:
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).

The docker task tray menu shows me logged in.

I have tried disabling IPv6, manually setting my network adapter DNS to 8.8.8.8, and setting the Docker Network settings DNS Server to Fixed: 8.8.8.8 as suggested on Stack Exchange and elsewhere. Nothing has any effect.

### Information

Diagnostic ID: 390230A0-AE6F-486D-AE2C-5B72441339E7/2018-02-04_16-22-29

### Steps to reproduce the behavior

  1. Install Docker for Windows 17.12.0-ce-win47, wait for it to finish Starting.
  2. Open PowerShell and run docker login or docker run hello-world.

**Comment by MoOFueL** [comment]
Same issue, nothing from forum posts, reddit, SO, SE helped

**Comment by jasonbivins** [comment]
Hi @ajhoddinott 
It looks like you're using a Mac, are you running through parallels or using another type of VM ?
Do you have a MobyLinuxVM running under Hyper-V ?

**Comment by ajhoddinott** [comment]
No, there is no VM involved. The hardware happens to be made by Apple, but this is a native Windows 10 install booted directly.

**Comment by ajhoddinott** [comment]
Also, to answer your second question, yes, I do. And Docker shows itself as running, and on the task tray menu I am shown logged in, so it seems at least the UI is able to access the network in some form.

![2018-02-06_105242](https://user-images.githubusercontent.com/771460/35837948-2ee3269c-0b2c-11e8-9dea-83b2ebcf4a89.png)
![2018-02-06_105248](https://user-images.githubusercontent.com/771460/35837949-2f09e55c-0b2c-11e8-8058-7902cf2df0af.png)
![2018-02-06_105313](https://user-images.githubusercontent.com/771460/35837950-2f2e16f2-0b2c-11e8-8131-f98962b5ce1d.png)

**Comment by SimSonic** [comment]
I've resolved this by updating to the latest Edge version.
But a lot of time spent to resolve this.

**Comment by ajhoddinott** [comment]
Hi @SimSonic, can you expand on what you mean by “the latest Edge version”?
I’m running Fall Creators Update (16299), fully current according to Windows Update as of 2 minutes ago. My Edge is version 41.16299.15.0.

**Comment by SimSonic** [comment]
I mean for me the problem has gone after updating Docker for Windows up to 18.02.0-ce-rc2-win51 (15631).
Windows 10 x64 also 16299

**Comment by ajhoddinott** [comment]
Hi @SimSonic, thanks for that pointer. Sorry for completely misconstruing what you meant by Edge!
I can confirm that it is fixed for me too after installing Version 18.02.0-ce-rc2-win51 (15631).

**Comment by LeslieMurphy** [comment]
For me, stopping Docker then restarting it fixed this issue.   I did not reboot Windows 10 or restart HyperV - just exited the Docker Daemon and restarted it
