### ISSUE TITLE
Can't run docker on Win10_17074

### ISSUE THREAD

**Issue by heyixiaoran** [docker/for-win#1657]
### Expected behavior
       Docker can run successful
### Actual behavior
       Docker run failed
### Information
  - Before update Windows 10 . Docker can run successful. But after update 17074 . Docker can not run again.  Docker stable and edge both are failed.

  - Unable to create File System Image
   在 Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:行号 36
   在 Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:行号 75
   在 Docker.Actions.<>c__DisplayClass16_0.<Start>b__0() 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:行号 61
   在 Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:行号 59
 
 - Windows 10 Build_17074.rs_prerelease_flt.180116-1539
 -  Diagnostic id : 10F59CBE-8E69-4425-8689-E6ABA220F249/2018-02-05_11-30-47

**Comment by shawntian** [comment]
right click the docker icon，switch to windows containers，hava a trye!

**Comment by heyixiaoran** [comment]
@shawntian  It works . Thank you . But how can I use Linux container ?  Will it fix in next version ?

**Comment by jasonbivins** [comment]
Hi @heyixiaoran   It looks like there might be a stuck config file from a previous install. Can you Rename the `c:\programdata\docker\lcow\config` folder to `config.old` and try again?

[09:36:09.474][Installer      ][Warning] Error while deleting C:\ProgramData\Docker\lcow\config\daemon.json : δ���ҵ�·����C:\ProgramData\Docker\lcow\config\daemon.json����һ���֡�

**Comment by heyixiaoran** [comment]
@jasonbivins Hi. I'm sorry. I can't find C:\ProgramData\Docker\lcow . no lcow folder. I find two daemon.json in C:\ProgramData\Docker\tmp-d4w and C:\ProgramData\Docker\config .  No config.old .  This happened after update win10 . Before update is ok.  Now windows container is ok .  Just  Linux container failed. I try to remove docker and install a new version . It's also failed.

**Comment by psychohamster** [comment]
I can report the same issue happening here - both stable and edge cannot start after update to 17074. I also don't have c:\programdata\docker\lcow\config, but I do have docker\config with a file dated as of the fresh installation inside. Tried renaming it with same results as before. 
I'd be happy to collect more data if you can point me in the right direction.

**Comment by psychohamster** [comment]
I've managed to change the stack trace of the error slightly, though still related it seems - 

> Unable to create File System Image
>    at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
>    at Docker.Actions.<>c__DisplayClass27_0.<SwitchDaemon>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 335
>    at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
> 
Uploaded a new crash report to id: 0DEFF734-A048-4641-B0C8-B6B69684311F/2018-02-08_12-48-23

**Comment by heyixiaoran** [comment]
I find docker VM disappeared.   But I try to install docker.  Still same

**Comment by heyixiaoran** [comment]
@shawntian @jasonbivins @psychohamster 
This fixed in edge version 18.03.0-ce-rc1-win54(16164) . After install this version. The MobyLinuxVM come back. Linux container can work.

**Comment by rn** [comment]
this looks like a dup of #1540 which turned out to be a Windows bug. You either need to be on insider build 17104+ or try the latest edge release of Docker for Windows.
