### ISSUE TITLE
no matching manifest for windows/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by shawntian** [docker/for-win#1658]
### Expected behavior
it would be download and install mysql image,but not.
### Actual behavior
CMD prompt `no matching manifest for windows/amd64 in the manifest list entries.`
### Information
`PS C:\Users\shawn> docker search mysql`
`NAME                                                   DESCRIPTION                                     STARS               OFFICIAL            AUTOMATED`
`mysql                                                  MySQL is a widely used, open-source relation…   5657                [OK]`
`mariadb                                                MariaDB is a community-developed fork of MyS…   1755                [OK]`
`mysql/mysql-server                                     Optimized MySQL Server Docker images. Create…   389                                     [OK]`
`hypriot/rpi-mysql                                      RPi-compatible Docker Image with Mysql          78`
`zabbix/zabbix-server-mysql                             Zabbix Server with MySQL database support       75                                      [OK]`
`centurylink/mysql                                      Image containing mysql. Optimized to be link…   58                                      [OK]`
`zabbix/zabbix-web-nginx-mysql                          Zabbix frontend based on Nginx web-server wi…   41                                      [OK]`
`tutum/mysql                                            Base docker image to run a MySQL database se…   31`
`1and1internet/ubuntu-16-nginx-php-phpmyadmin-mysql-5   ubuntu-16-nginx-php-phpmyadmin-mysql-5          25                                      [OK]`
`mysql/mysql-cluster                                    Experimental MySQL Cluster Docker images. Cr…   19`
`centos/mysql-57-centos7                                MySQL 5.7 SQL database server                   17`
`schickling/mysql-backup-s3                             Backup MySQL to S3 (supports periodic backup…   16                                      [OK]`
`linuxserver/mysql                                      A Mysql container, brought to you by LinuxSe…   14`
`zabbix/zabbix-proxy-mysql                              Zabbix proxy with MySQL database support        10                                      [OK]`
`centos/mysql-56-centos7                                MySQL 5.6 SQL database server                   7`
`openshift/mysql-55-centos7                             DEPRECATED: A Centos7 based MySQL v5.5 image…   6`
`dsteinkopf/backup-all-mysql                            backup all DBs in a mysql server                3                                       [OK]`
`circleci/mysql                                         MySQL is a widely used, open-source relation…   3`
`frodenas/mysql                                         A Docker Image for MySQL                        3                                       [OK]`
`cloudfoundry/cf-mysql-ci                               Image used in CI of cf-mysql-release            0`
`inferlink/landmark-mysql                               landmark-mysql                                  0                                       [OK]`
`openzipkin/zipkin-mysql                                Mirror of https://quay.io/repository/openzip…   0`
`cloudposse/mysql                                       Improved `mysql` service with support for m…   0                                       [OK]`
`ansibleplaybookbundle/mysql-apb                        An APB which deploys RHSCL MySQL                0                                       [OK]`
`astronomerio/mysql-sink                                MySQL sink                                      0                                       [OK]`

`PS C:\Users\shawn> docker pull mysql`
`Using default tag: latest`
`latest: Pulling from library/mysql`
`no matching manifest for windows/amd64 in the manifest list entries`

**Comment by pgayvallet** [comment]
`docker search` currently does not filter on images available for your architecture. The image you're trying to pull (mysql) is only available for linux containers. You are on windows container mode. Either switch to linux containers, or pull images built for win arch.

Created https://github.com/moby/moby/issues/36205 for this issue on moby project. Feel free to follow it if interested. 

Closing
