### ISSUE TITLE
Local gulp not found

### ISSUE THREAD

**Issue by assadarram** [docker/for-win#1659]
### Information
I Changed my windows user password and after that
After starting docker and start run-docker
Getting local gulp not found og all gulp commands

### Steps to reproduce the behavior

  1. ...
  2. ...

#solution
open docker setting select networking. deselect your drive and select it agian. you wil be asked to reenter credentials. gulp commands will work agian

**Comment by pgayvallet** [comment]
Changing your credentials will cause all drive mounts to fail until you re-enter them from the configuration panel when un/resharing drives. Nothing much we can do about this, as the user credential is required to connect to the drive from the VM.

**Comment by assadarram** [comment]
Thanks for the reply
the problem is it took me few hours to find what went wrong. i went through all the changes on my pc to figuer out what could be the problem. "local gulp not found" was not usefull. it is frustrating and i thought it could be help for someone else
