### ISSUE TITLE
Cannot connect to published port in SWARM/ingress network

### ISSUE THREAD

**Issue by lukee8** [docker/for-win#1660]
I'm trying to build docker swarm cluster on Windows.
4 virtual machines with Windows 2016 build 1709. Connected into swarm cluster.
Image: stefanscherer/registry-windows:2.6.2
Docker version Server Version: 17.06.2-ee-6
Windows version 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)

`docker service create --name hub --publish published=5656,target=5000 --replicas=1 stefanscherer/registry-windows:2.6.2`

Without ingress network (using host mode) issue is the same.
`docker service create --name hub_host --publish mode=host,published=5454,target=5000 --replicas=1 stefanscherer/registry-windows:2.6.2`

Service is up and running but I cannot connect to it using any IP. 
Furthermore none of the docker swarm machines is listening on port 5656 (or 5000) - checking with 'netstat -an'.
Service is telling me that is listening on IP 10.255.0.8, but if I connect to console, local IP is 10.255.0.9 (and this IP I see in ingress network details).

Am I doing something wrong?

```
docker service ls
ID                  NAME                MODE                REPLICAS            IMAGE                                  PORTS
29upxf3nwmsb        hub                 replicated          1/1                 stefanscherer/registry-windows:2.6.2   *:5656->5000/tcp
```

```
docker service inspect hub
        "Endpoint": {
            "Spec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 5000,
                        "PublishedPort": 5656,
                        "PublishMode": "ingress"
                    }
                ]
            },
            "Ports": [
                {
                    "Protocol": "tcp",
                    "TargetPort": 5000,
                    "PublishedPort": 5656,
                    "PublishMode": "ingress"
                }
            ],
            "VirtualIPs": [
                {
                    "NetworkID": "obw6iu0ggcwxjaq9mzlproduk",
                    **"Addr": "10.255.0.8/16"**
                }
            ]


docker network inspect ingress
[
    {
        "Name": "ingress",
        "Id": "obw6iu0ggcwxjaq9mzlproduk",
        "Created": "2018-02-05T12:46:02.1195629+01:00",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.255.0.0/16",
                    "Gateway": "10.255.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": true,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "72341c607bf96005dd5be9380258315ab1950dba04ff0113b8e4b1cd0f8df70d": {
                "Name": "hub.1.nucokfbk7tx4ts1iwpjzjxnca",
                "EndpointID": "d99081ddc970338274eb2e92ebbfd8b504b22b66349a9c30f4975c90a97d9a7e",
                "MacAddress": "00:15:5d:fc:3a:a3",
                **"IPv4Address": "10.255.0.9/16",**
                "IPv6Address": ""
            },
            "ingress-sbox": {
                "Name": "ingress-endpoint",
                "EndpointID": "eda400afff7bcaffe9ccd31f49216b8c1c8ea1241ccf06335d9871b979b928a4",
                "MacAddress": "00:15:5d:fc:3d:91",
                "IPv4Address": "10.255.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4096",
            "com.docker.network.windowsshim.hnsid": "98cd163d-ab24-49b6-9e42-af0a84984081"
        },
```

**Comment by lukee8** [comment]
Errata,
Only ingress network is not working (not exposing specified port). Host mode is working fine:

```
docker service ps hub
ID                  NAME                IMAGE                                  NODE                DESIRED STATE       CURRENT STATE               ERROR               PORTS
a8c30kgt2vr0        hub_host.1          stefanscherer/registry-windows:2.6.2   DUSI-DOCKER02       Running             Running about an hour ago                       *:5454->5000/tcp
nucokfbk7tx4        hub.1               stefanscherer/registry-windows:2.6.2   DUSI-DOCKER01       Running             Running 2 hours ago
```

**Comment by BretFisher** [comment]
Looks like you need latest Windows patches, and upgraded Docker EE to at least 17.09 to support ingress. [See the announcement from Microsoft](https://blogs.technet.microsoft.com/virtualization/2017/09/26/dockers-ingress-routing-mesh-available-with-windows-server-version-1709/).

**Comment by lukee8** [comment]
Thanks. Another challenge is hot to upgrade from 17.06.2-ee-6 to the newest preview?

I've tried to just run 
Install-Module -Name DockerProvider -Force
Install-Package Docker -ProviderName DockerProvider -RequiredVersion preview

But it's not enough. Do I need to completely remove everything (destroy swarm, uninstall docker) or is there any upgrade path?

**Comment by IAPOLINARIO** [comment]
@lukee8 Same problems here. =/

**Comment by lukee8** [comment]
Another doubt about ingress network. 
Will it work with Windows Containers? Or only with Hyper-V Containers?

Based on http://blog.airdesk.com/2017/11/docker-overlay-network-details.html it looks like it uses virtualization layer (vm switch) which is not present when you use Windows Containers.

**Comment by BretFisher** [comment]
Sorry, I don't have those answers.

**Comment by willwhite1** [comment]
-force on the install command upgrades the docker runtime if there is an existing install

**Comment by willwhite1** [comment]
Install-Package Docker -ProviderName DockerProvider -RequiredVersion preview -FORCE

**Comment by willwhite1** [comment]
Even with this installed on the swarm node, I cannot get the mesh working via overlay, but at least some progress with container attaching to host port and being available.

**Comment by willwhite1** [comment]
So, got this working. Mesh routing appears to work if you run the container as a hyper-v isolated container. You can for docker to always run containers in this way by setting the following -

$t = "c:\ProgramData\docker\config\daemon.json"
$a = @'
{
    "exec-opts":["isolation=hyperv"]
}
'@
Add-Content -Path $t -Value $a
Restart-Service docker

And hey presto the mesh then worked for me.

**Comment by rn** [comment]
This issue tracker is for the Docker for Windows application, which runs on Windows 10. To get help with Docker on Windows Server please see http://success.docker.com/article/where-to-get-help-with-windows.
Thanks
