### ISSUE TITLE
Error: Cannot find specific module using compose up

### ISSUE THREAD

**Issue by Alikhll** [docker/for-win#1662]
I have a simple nodejs application and it's completely works after build and running in container
`docker build -t alikhll/node1 .`
`docker run -d -p 3000:3000 alikhlll/node1`
and this is my dockerfile
```
FROM node
COPY . /var/www
WORKDIR /var/www
RUN npm i
EXPOSE 3000
ENTRYPOINT node index
```
everything works fine
but after using docker-compose I had following problems
this is my docker-compose file
```
version: '3'
services:
  nodeapp1:
    image: nodeapp1
    build:
      context: .
      dockerfile: nodeapp1/dockerfile
    ports:
     - "8181:3000"
``` 
### Expected behavior
I expected after running `docker-compose up`, I can run this app using that specific port but that container exited with code 1 
### Actual behavior
it's detail of something happened for me after running that command
```
Creating network "compose_default" with the default driver
Building nodeapp1
Step 1/6 : FROM node
 ---> de1099630c13
Step 2/6 : COPY . /var/www
 ---> Using cache
 ---> 8047c1e060ef
Step 3/6 : WORKDIR /var/www
 ---> Using cache
 ---> 1f7f805482c5
Step 4/6 : RUN npm i
 ---> Using cache
 ---> 34aca21662d1
Step 5/6 : EXPOSE 3000
 ---> Using cache
 ---> 0e0966231c27
Step 6/6 : ENTRYPOINT node index
 ---> Using cache
 ---> 4dcb3d155989
Successfully built 4dcb3d155989
Successfully tagged nodeapp1:latest
Creating compose_nodeapp1_1 ... done
Attaching to compose_nodeapp1_1
nodeapp1_1  | module.js:473
nodeapp1_1  |       throw err;
nodeapp1_1  |       ^
nodeapp1_1  |
nodeapp1_1  | Error: Cannot find module '/var/www/index'
nodeapp1_1  |     at Function.Module._resolveFilename (module.js:527:15)
nodeapp1_1  |     at Function.Module._load (module.js:453:25)
nodeapp1_1  |     at Function.Module.runMain (module.js:665:10)
nodeapp1_1  |     at startup (bootstrap_node.js:201:16)
nodeapp1_1  |     at bootstrap_node.js:626:3
compose_nodeapp1_1 exited with code 1
```
### Information
 - I used docker for windows community edition
 - Version 18.02.0-ce-rc2-win51 (15631)
 - Channel: edge

**Comment by pgayvallet** [comment]
This is not the compose bug tracker.

Even though,  the `context` in your compose file seems wrong
```
build:
      context: .
      dockerfile: nodeapp1/dockerfile
```

you probably want `context: nodeapp1` instead, as when using `docker build` this is what your context is.
