### ISSUE TITLE
Unable to start any container on new installation of Docker

### ISSUE THREAD

**Issue by Mohjive** [docker/for-win#1666]
### Expected behavior
That the container I try to start actually starts

### Actual behavior
Docker fails starting the container

### Information
```
> docker container run microsoft/powershell:nanoserver
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container d49b6c49fd05e051b093efcd1b985c2926dc19194e9111711df334f2ac9668d1 encountered an error during Start: failure in a Windows system call: Call was canceled by the message filter. (0x80010002).
```

I have uninstalled and reinstalled Docker with reboots between, to no avail.

  - Diagnostic ID: CE301292-97BC-4C39-8D2F-57C208534839/2018-02-07_07-43-34
  - Windows version: Windows 10 Professional Version 1709 Build 16299.192

### Steps to reproduce the behavior

  1. Try to start any container

**Comment by rubenmarrufo** [comment]
Exactly same problem here.

- Diagnostic ID: 8EE31AAE-2807-491F-8146-FED7FEBB4E7E/2018-02-28_12-54-47

**Comment by rajeshanayaka** [comment]
One of my new VM encountering same issue, anyone able fix the issue ?
