### ISSUE TITLE
Sharing windows host SSH key with a docker container resolve in a "Permissions are too open" error.

### ISSUE THREAD

**Issue by JnMik** [docker/for-win#167]
Hey guys !

We're having issues with Docker on windows that we don't have on Linux.

Mounting the host (windows 10) ssh key into the container via volume makes the permissions over 600 and using composer install resolve in an ssh error "SSH keys are too open" when installing private repositories.

Probaly some kind of NTFS / linux problem or something..

We tried with the SSH_AGENT_SOCKS as well without success.

I've even tried using cygwin to changes permissions on the host but it did not work, and it's clearly not an acceptable solution for me even if it would have worked as it implies way too much overhead.

Any one had success doing this ? 
thanks !

**Comment by coolfarmer** [comment]
Exactly the same behavior here, we need help!

**Comment by JnMik** [comment]
Would that be a good idea to have a Windows volume plugin driver that makes all of this way easier ? 

https://docs.docker.com/engine/extend/plugins_volume/

**Comment by justincormack** [comment]
I reopened the `docker/docker` issue as I don't think this is specific to Docker for Windows...

**Comment by JnMik** [comment]
I still didn't had the time to check this at home. I'll try to find some time this weekend.

**Suggestion:**
Would that be an idea to have D4W ask us during install if we need an ssh key appended to the containers ? If the user reply yes, the wizard generate one for allowing the user to copy / paste it.
Then I guess it could be deactivated at any time in the menu 

![image](https://cloud.githubusercontent.com/assets/4965516/19769372/231c7566-9c29-11e6-92b7-7ea0df947839.png)

Could that be a viable solution ?

**Comment by airtonix** [comment]
imo, the correct way to deal with this is to use the $SSH_AUTH_SOCK which is available on systems that have at least (i think) `pshazz` installed: 

```
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

Loading personal and system profiles took 907ms.
~ $ gci env:SSH_AUTH_SOCK

Name                           Value
----                           -----
SSH_AUTH_SOCK                  /tmp/ssh-qgFBji4276/agent.4276
```

**Comment by rneugeba** [comment]
I'm afraid, but I suspect there is no easy fix. We use SMB/CIFS for volume mounts and SMB does not map file permissions very well between Linux and NTFS. You also can't map sockets over SMB. I'm afraid this is a wont-fix and I'm closing the issue.

One workaround might be copy the ssh keys into the container (either from a volume mount or via the Dockerfile) and then change the permission on they key. Not ideal, but it might work.

**Comment by webberist** [comment]
In case anyone else comes across this issue, here's a work around.

You'll need to copy the private key into a path accessible to the container.
The permissions on key will be too broad but piping the key into ssh-add bypasses this:
`cat id_rsa | ssh-add -k -`

Depending on your container, ssh-agent may not be already running:
``eval `ssh-agent` ``
