### ISSUE TITLE
Daemon option max-concurrent-downloads refused by settings panel but still seems to work

### ISSUE THREAD

**Issue by NReilingh** [docker/for-win#1671]
### Expected behavior
The docker daemon configuration panel in Settings will accept a configuration option of max-concurrent-downloads.

### Actual behavior
If this setting is set manually in the default daemon.json config file [Example daemon.json](https://github.com/docker/for-win/files/1704115/daemon.json.txt), it appears to work, but the settings panel reports "Invalid option", per screenshot:

![screen shot 2018-02-07 at 12 40 36 pm](https://user-images.githubusercontent.com/2458645/35931893-20dffc18-0c04-11e8-80f3-2f82cb1cf65f.png)

This also means if the user goes into Advanced mode to try to edit the JSON directly from the settings panel, it will prevent saving that setting.

Also note that clicking the "configuration file" link in the settings panel attempts to load https://docs.docker.com/engine/reference/commandline/dockerd/#windows-configuration-file, but there is no such anchor on the page.

### Information

  - Docker CE Stable in Windows Containers mode
  - Diagnostic: 655D4C22-64DB-42B3-8104-91EABC64F9AF/2018-02-07_12-28-09
  - Documented behavior: https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file
  - Docker CE 17.12.0-ce-win47 (15139), Windows 10 (1709)

### Steps to reproduce the behavior

  1. Put Docker into Windows Containers mode from the tray icon
  2. Open docker settings -> Daemon
  3. Click the switch to go from Basic to Advanced
  4. Edit the JSON to add a "max-concurrent-downloads" key with a value of 1
  5. Panel reports invalid option and refuses to apply
  6. Workaround: Go back to Basic mode and close the window
  7. Manually edit the %programdata%\docker\config\daemon.json file to add the key and value, then manually quit and restart docker
  8. Open the settings -> daemon panel again and see the error displayed
  9. Ignore it and pull a docker image with multiple fs layers
  10. Observe one layer downloading at a time.

**Comment by jasonbivins** [comment]
Hi @NReilingh 
I can reproduce this on edge and stable, so I'll go ahead and write it up as a bug. 
 Here's an article that might help if things get hung up with the invalid settings  https://success.docker.com/article/Docker_for_Windows_freezes_with_invalid_daemon_settings

**Comment by pgayvallet** [comment]
Hi, thanks for the report.

Reproduced. Was missing from our schema. 

Will be fixed in next edge.

**Comment by NReilingh** [comment]
Fixed since at least 18.06.0-cd-win72.

Thanks!
