### ISSUE TITLE
File access in mounted volumes extremely slow

### ISSUE THREAD

**Issue by yesterday679** [docker/for-win#1674]
In the laravel framework, access is very slow

**Comment by yesterday679** [comment]
![phpstrom](http://img.huaxi100.com/qiniu5a7c17609c0ed20180208172448.png)

**Comment by yesterday679** [comment]
![pic](http://img.huaxi100.com/qiniu5a7c1a4e0d6db20180208173718.png)

very slow

**Comment by yesterday679** [comment]
[docker for mac mirror problem](https://github.com/docker/for-mac/issues/77)

**Comment by jasonbivins** [comment]
Hi @yesterday679 

Can you provide a diagnostic ID please?

**Comment by yesterday679** [comment]
what is diagnostic ID ?  @jasonbivins

**Comment by pgayvallet** [comment]
Languages with a lot of file access ( understand : PHP with no cache ) play very badly with the samba protocol we are using for file sharing.

We are aware of this, and are currently researching for alternatives.

**Comment by yesterday679** [comment]
@pgayvallet  

Are there any temporary solutions?

**Comment by acip** [comment]
A temporary solution is to install and enable opcache and blacklist the "dev" folders: https://gist.github.com/acip/06b7b8ee26110e5e56519ce50f76c8b2

**Comment by lucasvanlierop** [comment]
I see the robot closed this issue however it has not been resolved at all, it's just that everything that's to be said about this has already been said. So @pgayvallet any updates on this? Note I would even love to pay for Docker for Windows if it would work fast

**Comment by lucasvanlierop** [comment]
For I now I switched back to Linux, I advise everyone here to do so, speed improvements of 3000% in some cases.
