### ISSUE TITLE
Docker Shared Drive Takes A Long Time To Load

### ISSUE THREAD

**Issue by spirodonfl** [docker/for-win#168]
### Expected behavior
With my C drive shared, I can see Docker startup in approx 30 seconds.

### Actual behavior
With my C drive shared, Docker takes up to 6 minutes to startup.

### Information
If I don't share my C drive and I use a custom powershell script to setup a mount by myself (after sharing the C drive manually), Docker is good to go after about 30 seconds and I can use the mounted C drive like normal.

Below, the custom powershell script I use to mount my C drive manually.

```
$drive = $env:homedrive.Substring(0,1)

$ip = Get-NetIPConfiguration -InterfaceAlias "vEthernet (DockerNAT)" | Select IPv4Address
$unc = "//" + $ip.IPv4Address.IPAddress + "/" + $drive

[Environment]::SetEnvironmentVariable("UNC", $unc, "Process")
[Environment]::SetEnvironmentVariable("DRIVE", $drive, "Process")
docker run -ti --rm --privileged --pid=host -e USERNAME -e USERDOMAIN -e DRIVE -e UNC ubuntu nsenter --target 1 --mount --uts --ipc --net --pid sh -x -c '[ -d "/spiros_mnt" ] || mkdir "/spiros_mnt" && mount.cifs "${UNC}" "/spiros_mnt" -o "user=${USERNAME},domain=${USERDOMAIN},noperm,forceuid,mfsymlinks,file_mode=0777,dir_mode=0777,nobrl,vers=3.0"'
```

### Steps to reproduce the behavior

  1. Share C Drive
  2. Start Docker

Please note that Docker starts up every time with the C drive shared. I get no errors. It just takes forever. I'm not sure if you need a diagnostic ID but I can provide one if you want.

**Comment by rneugeba** [comment]
@spirodonfl is this with the image I gave you? It looks like there is an issue with the kernel which we are debugging at the moment.

**Comment by spirodonfl** [comment]
@rneugeba Yep, it's the image you gave me. I'll close this ticket and try again when the new Beta comes out. :)

**Comment by rneugeba** [comment]
unfortunately, we were not able to fix it. Will update #54

**Comment by spirodonfl** [comment]
@rneugeba Oh no. :( That sucks. Should I reopen this ticket? What's the problem? Anything I can do to help?

**Comment by rneugeba** [comment]
no need to re-open. we are tracking this internally (as it hasn't been released). there are some weird delays with some docker commands on the 4.8 kernel on Hyper-V. We spent the last two days trying to narrow it down with mixed success.

**Comment by spirodonfl** [comment]
Ok cool. Happy to provide my machine to you guys if you need. :)
