### ISSUE TITLE
LoadBalancer service doesn't get External IP allocated after default install

### ISSUE THREAD

**Issue by rbtcollins** [docker/for-win#1681]
### Expected behavior
The service should get an external IP allocated (as shown in the video on https://blog.docker.com/2017/10/docker-for-mac-and-windows-with-kubernetes-beta/ )

### Actual behavior
The external IP stays in pending mode.

```jaeger-kubernetes\all-in-one>kubectl get -o wide svc/jaeger-query
NAME           TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE       SELECTOR
jaeger-query   LoadBalancer   10.108.150.72   <pending>     80:30494/TCP   1h        jaeger-infra=jaeger-pod```

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.

1EA2E1CC-79F2-4259-A9E8-6AED1039B4B2/2018-02-10_22-46-35

  - a reproducible case if this is a bug, Dockerfiles FTW

clone https://github.com/jaegertracing/jaeger-kubernetes/ and create the all-in-one sample yaml, then look at kubectl get all -o wide

  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

Winddows 10 1709 16299.214

### Steps to reproduce the behavior

  1. See above
  2. ...

**Comment by cmendible** [comment]
Hi guys same here. I've tried in 2 different Windows machines with the same result: **EXTERNAL-IP stays in pending  state.**

Docker Community Edition Version 18.02.0-ce-win52 (15732) 
Channel: edge
92c7ac6

Windows 10 Pro 1709 
OS Build16299.192

**Comment by pgayvallet** [comment]
Hello,

We fixed the display in latest edge (18.03-rc1). However, even when displaying `<pending>`, The service is correctly port-forwarded to localhost, on the port exposed by the pod.

I.E for your example

```
NAME           TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE       SELECTOR
jaeger-query   LoadBalancer   10.108.150.72   <pending>     80:30494/TCP   1h        jaeger-infra=jaeger-pod```
```

You should be able to access the service on `localhost:80` ( and NOT `localhost:30494` )

**Comment by cmendible** [comment]
Hi @pgayvallet,

I confirm it's just a display issue. Can't believe I was so lazy to not test for localhost:[port] before!

Thanks!

**Comment by rbtcollins** [comment]
It doesn't seem to be a display issue for me.
```
> kubectl get svc,ep -o wide
NAME                   TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                        AGE       SELECTOR
svc/jaeger-agent       ClusterIP      None             <none>        5775/UDP,6831/UDP,6832/UDP     8d        jaeger-infra=jaeger-pod
svc/jaeger-collector   ClusterIP      10.101.82.186    <none>        14267/TCP,14268/TCP,9411/TCP   8d        jaeger-infra=jaeger-pod
svc/jaeger-query       LoadBalancer   10.109.241.195   <pending>     80:30841/TCP                   8d        jaeger-infra=jaeger-pod
svc/keycloak           LoadBalancer   10.107.148.175   <pending>     8080:30735/TCP                 6m        run=keycloak
svc/kubernetes         ClusterIP      10.96.0.1        <none>        443/TCP                        15d       <none>
svc/zipkin             ClusterIP      None             <none>        9411/TCP                       8d        jaeger-infra=jaeger-pod

NAME                  ENDPOINTS                                        AGE
ep/jaeger-agent       10.1.0.38:6831,10.1.0.38:5775,10.1.0.38:6832     8d
ep/jaeger-collector   10.1.0.38:9411,10.1.0.38:14267,10.1.0.38:14268   8d
ep/jaeger-query       10.1.0.38:16686                                  8d
ep/keycloak           10.1.0.42:8080                                   6m
ep/kubernetes         192.168.65.3:6443                                15d
ep/zipkin             10.1.0.38:9411                                   8d
```

I can curl jaeger-query within the cluster from a test pod and access it on port 80 on localhost, but for keycloak I can access it within the cluster - ```curl http://keycloak:8080/``` but doing that from within windows itself fails - connection refused: 
```$ curl http://localhost:8080/
curl: (7) Failed to connect to localhost port 8080: Connection refused```

Where can I get details about the current DNAT'd ports and so on to diagnose this further?

**Comment by iahmad-khan** [comment]
Hi, 

Faced the same issue today with latest docker EE , external IP pending. Do we need to configure a separate IP pool for this purpose or the IP subnet allocated to UCP will be used?

**Comment by Ciantic** [comment]
On my machine the LoadBalancer gets a external IP `localhost` but it's not accessible, nothing is running there. My tests are here: https://github.com/Ciantic/microservices-and-kubernetes-experiments it should start with `start.bat` this is directly from Ambassador tutorial. 

However the maintainer of Ambassador says that Docker for Windows does not support type LoadBalancer.

**Comment by guillaumerose** [comment]
LoadBalancer service are supported. They are directly exposed on localhost on the host. You can double-check with nginx for instance.

**Comment by Ciantic** [comment]
I couldn't get the LoadBalancer working with Nginx either:

```
kubectl run my-nginx --image=nginx --replicas=1 --port=80
kubectl expose deployment my-nginx --port=80 --type=LoadBalancer
kubectl get svc
curl -m 10 http://localhost/
```

output is just:

```
deployment.apps "my-nginx" created
service "my-nginx" exposed
NAME         TYPE           CLUSTER-IP    EXTERNAL-IP   PORT(S)        AGE
kubernetes   ClusterIP      10.96.0.1     <none>        443/TCP        12m
my-nginx     LoadBalancer   10.97.68.29   localhost     80:31490/TCP   0s

curl: (28) Operation timed out after 10000 milliseconds with 0 bytes received
```

Can't find any meaningful log either, it just shows as if it were running but it does not respond in localhost.

I've also opened [a question in the Docker Community](https://forums.docker.com/t/kubernetes-hello-world-nginx-loadbalancer-does-not-connect/70055).

**Comment by feliperyan** [comment]
@Ciantic I also am not able to get it working on macOS having the exact same issue.

**Comment by Ciantic** [comment]
@feliperyan It works now for me. This issue is for Docker for Windows (for-win). However macOS version may have similar problems. I didn't do anything to fix it, it just seems to work right now. I suspect the port forwarding etc. may have been broken, but for some reason works now.
