### ISSUE TITLE
Unable to create file system image

### ISSUE THREAD

**Issue by shuntera** [docker/for-win#1682]
Can't start Docker for Windows

### Information
 DB1F9F72-7946-434A-95AD-E64CF47E83EB/2018-02-10_12-24-32
  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by haroldvandekamp** [comment]
I am on Windows 10 Insider Slow version 1709 Build 17074.1002 and also had the error "Unable to create file system image" when I was using Docker Community Edition 17.12.0-ce-win47 2018-01-12 (Stable).
I uninstalled that version, downloaded and installed the Docker Community Edition 17.09.1-ce-win42 2017-12-11 (Stable) version (https://download.docker.com/win/stable/14687/Docker%20for%20Windows%20Installer.exe), after that Docker starts normally.

**Comment by rn** [comment]
this looks like a dup of https://github.com/docker/for-win/issues/1540 which turned out to be a Windows bug. You either need to be on insider build 17104+ or try the latest edge release of Docker for Windows.
