### ISSUE TITLE
Unable to run Docker on Windows 10 with latest stable/edge

### ISSUE THREAD

**Issue by cdenneen** [docker/for-win#1683]
Basically a re-opening of #74

Virtualization is enabled but still getting error in docker as if it wasn't.
Tried latest stable build and now latest edge.

![capture](https://user-images.githubusercontent.com/720097/36065133-5a00da96-0e64-11e8-88ae-53ae8a8d5310.PNG)

**Comment by mosinve** [comment]
I had such problem, solved by resetting network by `netsh winsock reset`, as a check - try to run VM from HyperV manager, 
another possible solution is https://success.docker.com/article/Manually_enable_Docker_for_Windows_prerequisites
