### ISSUE TITLE
re-exec error: exit status 1

### ISSUE THREAD

**Issue by stevieflash42** [docker/for-win#1686]
### Expected behavior

Pull the microsoft/iis:windowsservercore-1709 image

### Actual behavior

Error after it tries to extract the third layer

### Information

Consistently unable to execute:

> docker pull microsoft/iis:windowsservercore-1709

I've tried adding these exclusions to Windows Defender with no joy (no other AV software on box):

> C:\ProgramData\Docker
> C:\Windows\Temp
> dockerd

I've tried running a docker save from a computer it IS working on and then running a docker load on the faulting box and end up with the same results

#### Full error is:

> re-exec error: exit status 1: output: time="2018-02-11T05:31:50Z" level=error msg="hcsshim::ImportLayer failed in Win32: The system cannot find the file specified. (0x2) layerId=\\\\?\\C:\\ProgramData\\Docker\\windowsfilter\\18d4ab636bf4a3da22c6671565357ec6fce1cdd8c2b7cd4ad9346ca235023d3b flavour=1 folder=C:\\Windows\\TEMP\\hcs431009291"
> hcsshim::ImportLayer failed in Win32: The system cannot find the file specified. (0x2) layerId=\\?\C:\ProgramData\Docker\windowsfilter\18d4ab636bf4a3da22c6671565357ec6fce1cdd8c2b7cd4ad9346ca235023d3b flavour=1 folder=C:\Windows\TEMP\hcs431009291

#### docker version:

> Preformatted text`Client:
>  Version:      17.06.2-ee-6
>  API version:  1.30
>  Go version:   go1.8.3
>  Git commit:   e75fdb8
>  Built:        Mon Nov 27 22:46:09 2017
>  OS/Arch:      windows/amd64
> 
> Server:
>  Version:      17.06.2-ee-6
>  API version:  1.30 (minimum version 1.24)
>  Go version:   go1.8.3
>  Git commit:   e75fdb8
>  Built:        Mon Nov 27 22:55:16 2017
>  OS/Arch:      windows/amd64
>  Experimental: false

#### docker info:

> Containers: 0
>  Running: 0
>  Paused: 0
>  Stopped: 0
> Images: 0
> Server Version: 17.06.2-ee-6
> Storage Driver: windowsfilter
>  Windows:
> Logging Driver: json-file
> Plugins:
>  Volume: local
>  Network: l2bridge l2tunnel nat null overlay transparent
>  Log: awslogs etwlogs fluentd json-file logentries splunk syslog
> Swarm: inactive
> Default Isolation: process
> Kernel Version: 10.0 14393 (14393.2035.amd64fre.rs1_release_inmarket.180110-1910)
> Operating System: Windows Server 2016 Datacenter
> OSType: windows
> Architecture: x86_64
> CPUs: 2
> Total Memory: 4GiB
> Name: EC2AMAZ-8BOS02R
> ID: G63G:EITM:7G2S:F2UA:GNAX:AGFX:27XQ:5Q3X:KRUH:Y4QX:RZPE:BORZ
> Docker Root Dir: C:\ProgramData\Docker
> Debug Mode (client): false
> Debug Mode (server): false
> Registry: https://index.docker.io/v1/
> Experimental: false
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false

**Comment by Shital-Zambare** [comment]
FROM microsoft/dotnet-framework:4.6.2
It gives the same error
 Step 3/7 : COPY . .
re-exec error: exit status 1: output: time="2018-02-14T11:54:57+05:30" level=error msg="hcsshim::ImportLayer failed in Win32: The system cannot find the path specified. (0x3) layerId=\\?\C:\ProgramData\Docker\windowsfilter\e40245b5e592f363e43ab586ad1123a04d13f11ed069be52
5b03f8fd365cf90b flavour=1 folder=C:\WINDOWS\TEMP\hcs772073079"
hcsshim::ImportLayer failed in Win32: The system cannot find the path specified. (0x3) layerId=\\?\C:\ProgramData\Docker\windowsfilter\e40245b5e592f363e43ab586ad1123a04d13f11ed069be525b03f8fd365cf90b flavour=1 folder=C:\WINDOWS\TEMP\hcs772073079

**Comment by Shital-Zambare** [comment]
Docker file : FROM microsoft/dotnet-framework:4.6.2
                     WORKDIR /.
                     COPY . .
I am also facing same issue at 3rd step.
Step 3/7 : COPY . .
re-exec error: exit status 1: output: time="2018-02-14T11:54:57+05:30" level=error msg="hcsshim::ImportLayer failed in Win32: The system cannot find the path specified. (0x3) layerId=\\?\C:\ProgramData\Docker\windowsfilter\e40245b5e592f363e43ab586ad1123a04d13f11ed069be52
5b03f8fd365cf90b flavour=1 folder=C:\WINDOWS\TEMP\hcs772073079"
hcsshim::ImportLayer failed in Win32: The system cannot find the path specified. (0x3) layerId=\\?\C:\ProgramData\Docker\windowsfilter\e40245b5e592f363e43ab586ad1123a04d13f11ed069be525b03f8fd365cf90b flavour=1 folder=C:\WINDOWS\TEMP\hcs772073079

**Comment by stevieflash42** [comment]
We think we figured out the problem. Apparently you can't even build the docker image if the base Windows Kernel (WITH service packs) doesn't match the docker image's. Kind of a pain, but after we upgraded everything we were able to pull just fine.

I knew about not being able to run without hyper-v isolation on incompatible Windows OS versions, but I didn't realize it meant that the builder machine had to respect that too. I guess is makes sense though: the image is technically "running" at each stage of the Dockerfile.

Disclaimer: we did spin all of this up on a brand new VM and everything, so I welcome correction if anyone has any insight into what was/is actually happening here.

**Comment by carlfischer1** [comment]
@stevieflash42 in your first post the Windows version was 10.0.14393.2035, aka Windows 2016, but the pull command was for the 1709 tag of windowsservercore. 

With Server 2016 mismatches in host/container patch level won't be prevented from starting, but aren't a supported configuration. That requirement is relaxed with Server 1709.

https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility
