### ISSUE TITLE
Docker in Win10VM dosn't run container (failure in a Windows system call)

### ISSUE THREAD

**Issue by Dawnkeeper** [docker/for-win#1690]
### Expected behavior

`docker run hello-world ` should start the hello world container

### Actual behavior
After downloading the container it aborts with:
`docker: Error response from daemon: container 5900d10164bd5272f0330f58aa9f27f7af56cb17a7443dd0fe63e089e33ca53a encountered an error during CreateContainer: failure in a Windows system call: Das System kann den angegebenen Pfad nicht finden. (0x3) extra info: {"SystemType":"Container","Name":"5900d10164bd5272f0330f58aa9f27f7af56cb17a7443dd0fe63e089e33ca53a","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\5900d10164bd5272f0330f58aa9f27f7af56cb17a7443dd0fe63e089e33ca53a","Layers":[{"ID":"745d78be-b629-5483-9952-cc44f96e9a04","Path":"C:\\ProgramData\\Docker\\windowsfilter\\8f21ccce1e550031b5f844fe68271c7c2cd4550f56b7ccb7d8fb5f574414e2fd"},{"ID":"d6c81cda-82a1-5c7f-bb68-d5b7014eca37","Path":"C:\\ProgramData\\Docker\\windowsfilter\\e930578e9cd1eda4ec6bcf593464c39d54f56fb6bd0e2b55aefd770c7b679307"},{"ID":"9f78da71-aac2-56fd-94f7-6f2c341c77fe","Path":"C:\\ProgramData\\Docker\\windowsfilter\\91405a3faff7ffb704d05fea41a83af7bd28c06d403e154c18b649fb15811112"},{"ID":"5bb7403c-5e8c-50bc-aa0d-df05d37518aa","Path":"C:\\ProgramData\\Docker\\windowsfilter\\f6f3504057b6ae37d862653b2ee22f7f89217a3831e49cddcfda51d2ca14f70d"}],"HostName":"5900d10164bd","HvPartition":true,"EndpointList":["c747af34-8925-4405-a2df-a522bb90798f"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\91405a3faff7ffb704d05fea41a83af7bd28c06d403e154c18b649fb15811112\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}.`
### Information
running on a VMware

### Steps to reproduce the behavior

  1. run the hello world container

**Comment by rn** [comment]
we do not support running Docker for Windows inside a windows vm. see https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-for-windows-in-nested-virtualization-scenarios
