### ISSUE TITLE
Docker for windows pull gets vmbus.dll error.

### ISSUE THREAD

**Issue by kriskomar-scentsy** [docker/for-win#1692]
### Expected behavior
when doing this:
docker pull scentsy/dev-iis:latest
in a powershell script in administrator mode, this error is thrown:
Attempting next endpoint for pull after error: failed to register layer: re-exec error: exit status 1: output: remove \\?\C:\ProgramData\Docker\windowsfilter\8417c373b9405faf0445b9164825969331ec72adb4b2a0648dc7c17b2ed231f4\UtilityVM\Files\Windows\System32\DriverStore\FileRepository\wvmbus.inf_amd64_9afa303f69d7201e\vmbuspipe.dll: Access is denied.

It looks like access is denied because the file was previously deleted.

### Actual behavior
File should exist or not be previously deleted.

### Information

This is the procmon line where it’s happening. Procmon output is also attached. It looks like it’s happening while dockerd.exe is working with it.
[ProcessMonitordocker vmbus issue.xlsx](https://github.com/docker/for-win/files/1717316/ProcessMonitordocker.vmbus.issue.xlsx)
 
![vmbus error in procmon](https://user-images.githubusercontent.com/22890403/36112639-8f5bebb6-0fe7-11e8-98eb-fa7a2490f96f.jpg)

This is the actual executed command that tried to make the delete:
C:\Program Files\Docker\Docker\Resources\dockerd.exe docker-windows-write-layer C:\ProgramData\Docker\windowsfilter 85aba28bb8da61cd7c210af6d16d6a5e306f4b9fa035e8bf53b16202476b9028 C:\ProgramData\Docker\windowsfilter\48b29d2b8c8deca255ce59511fe31c99c097458971ecb704311839daa9192cdc

And here’s the stack:
0	FLTMGR.SYS	FltDecodeParameters + 0x19d2	0xfffff80f5a377852	C:\WINDOWS\System32\drivers\FLTMGR.SYS
1	FLTMGR.SYS	FltDecodeParameters + 0x1578	0xfffff80f5a3773f8	C:\WINDOWS\System32\drivers\FLTMGR.SYS
2	FLTMGR.SYS	FltDecodeParameters + 0x117b	0xfffff80f5a376ffb	C:\WINDOWS\System32\drivers\FLTMGR.SYS
3	FLTMGR.SYS	FltDecodeParameters + 0xf1e	0xfffff80f5a376d9e	C:\WINDOWS\System32\drivers\FLTMGR.SYS
4	ntoskrnl.exe	IofCallDriver + 0x59	0xfffff803760a42d9	C:\WINDOWS\system32\ntoskrnl.exe
5	ntoskrnl.exe	ExAllocatePoolWithQuotaTag + 0x51a	0xfffff803760aaada	C:\WINDOWS\system32\ntoskrnl.exe
6	ntoskrnl.exe	ExAllocatePoolWithQuotaTag + 0x42c	0xfffff803760aa9ec	C:\WINDOWS\system32\ntoskrnl.exe
7	ntoskrnl.exe	NtSetInformationFile + 0x6a7	0xfffff803760a7507	C:\WINDOWS\system32\ntoskrnl.exe
8	ntoskrnl.exe	setjmpex + 0x8fc3	0xfffff80376212203	C:\WINDOWS\system32\ntoskrnl.exe
9	ntdll.dll	NtSetInformationFile + 0x14	0x7ffebfb70354	C:\Windows\System32\ntdll.dll
10	KernelBase.dll	DeleteFileW + 0x161	0x7ffebc1ee251	C:\Windows\System32\KernelBase.dll
11	KernelBase.dll	DeleteFileW + 0xb	0x7ffebc1ee0fb	C:\Windows\System32\KernelBase.dll
12	dockerd.exe	dockerd.exe + 0x5f55e	0x45f55e	C:\Program Files\Docker\Docker\resources\dockerd.exe

### Steps to reproduce the behavior
docker pull scentsy/dev-iis:latest
Error thrown on from powershell script run in admin mode.

**Comment by ebriney** [comment]
Hi @kriskomar-scentsy 
Can you try to delete layers with https://github.com/jhowardmsft/docker-ci-zap/raw/master/docker-ci-zap.exe
and retry to pull.
Alternatively, you can install [edge version](https://download.docker.com/win/edge/Docker%20for%20Windows%20Installer.exe) and reset to default (it includes ci-zap similar code path)

**Comment by kriskomar-scentsy** [comment]
@ebriney I have the edge version. How do I reset to default?

**Comment by kriskomar-scentsy** [comment]
It was determined that because my corporate network was blocking port 3544, for some reason the pull would fail somewhere in the middle. If anyone else comes across this, have your network guy make sure port 3544 is totally open.
