### ISSUE TITLE
Unable to Share C Drive

### ISSUE THREAD

**Issue by billbodapolypore** [docker/for-win#1694]
### Expected behavior
From Shared Drive tab I should be able to share my C drive

### Actual behavior
After the credential prompt the checkbox next to the drive unchecks.  

I also try the command displayed on that screen:
docker run --rm -v c:/Users:/data alpine ls /data

I get this error after the credential prompt:
docker: Error response from daemon: An error occured while sharing drive.

Details from the logs:
```
[16:08:31.131][NamedPipeClient][Info   ] Sending Version()...
[16:08:31.133][NamedPipeClient][Info   ] Received response for Version
[16:08:31.133][NamedPipeClient][Info   ] Sending Mount(C, , Docker.Core.Settings)...
[16:08:31.132][NamedPipeServer][Info   ] Version()
[16:08:31.133][NamedPipeServer][Info   ] Version done in 00:00:00.0004985.
[16:08:31.136][NamedPipeServer][Info   ] Mount(C, , Docker.Core.Settings)
[16:08:31.296][NamedPipeClient][Info   ] Received response for Mount
[16:08:31.296][NamedPipeServer][Info   ] Mount done in 00:00:00.1597767.
[16:08:40.495][CredentialAsker][Info   ] Storing credentials: removed\removed:***********
[16:08:40.496][CredentialAsker][Error  ] Failed to retrieve the user's credentials: A specified logon session does not exist. It may already have been terminated
```

### Information
Diagnostic ID:
2B13F88F-097A-4E5F-B048-90CDCA85F901/2018-02-12_16-22-07

### Steps to reproduce the behavior
  1. Open Settings from task bar icon
  2. Click Shared Drives
  3. Check C drive
  4. Click Apply
  5. Enter credentials in prompt

**Comment by ebriney** [comment]
Hi @billbodapolypore 
can you try to unshare your C drive manually:
 - second click on C drive - properties:
![diskproperties-sharingadvanced](https://user-images.githubusercontent.com/8415079/36146014-72f072a4-10b3-11e8-9021-a8c64f8d6101.PNG)
 - then in advance sharing - untick Share this folder:
![advancedsharing](https://user-images.githubusercontent.com/8415079/36146046-8da93efa-10b3-11e8-9746-3f83bfe2ad30.PNG)

then retry to enable filesharing in Docker Settings

**Comment by billbodapolypore** [comment]
@ebriney Thanks for the response.

It looks like my C: drive is not currently shared:
![image](https://user-images.githubusercontent.com/21219286/36153835-95621204-109d-11e8-8faf-f93f543a6c50.png)

**Comment by ebriney** [comment]
Can you try to share it manually?
PS: don't forget add your user in permission.

**Comment by billbodapolypore** [comment]
I made some assumptions based on your suggestion to "share it manually".  Please let me know if I misunderstood.

1. I went to the same properties dialog for my C: drive.  I
2. I clicked Advanced Sharing
3. I ticked Share this folder
![image](https://user-images.githubusercontent.com/21219286/36155243-d571a9e6-10a1-11e8-87ee-879a2132c877.png)
4. I clicked permissions 
5. I added my user and gave Full Control
![image](https://user-images.githubusercontent.com/21219286/36155285-fc312070-10a1-11e8-9ce7-be913bf42ab5.png)
6. I restarted the Docker app (task bar icon)
7. I went to Docker app > Settings and performed the exact same steps as in my original issue report and the same behavior occurred.  Reviewing the logs the same error is occurring:
`[09:42:18.979][CredentialAsker][Error  ] Failed to retrieve the user's credentials: A specified logon session does not exist. It may already have been terminated`

**Comment by ebriney** [comment]
Ok thanks.
Did you try to access your smb share from another computer?
It seems that either you have special network policies or the credentials are wrong (domain\user pass)

**Comment by denvit** [comment]
I have the same problem. Uploaded my diagnostics - ID: 3A571585-9253-4DFA-8BB7-003423356E11/2018-02-14_18-43-16

**Comment by billbodapolypore** [comment]
@ebriney I can access the SMB share from another machine

**Comment by billbodapolypore** [comment]
I tried doing something a bit different and didn't get an error this time but also I'm not getting directory results like I should:
![image](https://user-images.githubusercontent.com/21219286/36222211-a26df958-118e-11e8-8eed-a8e7bf135f53.png)

At this point I feel I'll have to chalk this up to some sort of firewall / group policy issue that my company has put restriction on my machine.  I wish we could find some sort of work-around.

**Comment by billbodapolypore** [comment]
One last thing I found.  I also get the same error when I click on Credential Manager in the control panel:
![image](https://user-images.githubusercontent.com/21219286/36222672-0b5467bc-1190-11e8-9612-1463167abbed.png)

Researching this general error I found that typically it comes from a Group Policy setting, however it is disabled on my system:
![image](https://user-images.githubusercontent.com/21219286/36222743-50a57810-1190-11e8-9532-3b302a1eae3c.png)

Does Docker user this Windows Credential Manager?  Perhaps this is the root of our issue?

**Comment by robotdad** [comment]
I've hit this with the stable channel 17.12 as well. The issue seems to be sharing with a domain account does not work. I had to create a new local user with access to the C drive to work around this.

**Comment by werebear73** [comment]
I'm having this issue too but not on a machine attached to a domain.  It is Windows 10 Workstation though.

**Comment by btodts** [comment]
/remove-lifecycle stale

I am hitting this with a Domain Account as well

**Comment by Cherishty** [comment]
+1 any update for this issue?
