### ISSUE TITLE
Error start vm linux on windows with hyper-v

### ISSUE THREAD

**Issue by deyvsonaguiar** [docker/for-win#1695]
Help me please this error:

Unable to create: O comando em execução parou porque a variável preferencial "ErrorActionPreference" ou o parâmetro comum está definido como Stop: Falha ao criar o disco rígido virtual.

O sistema não pôde criar 'C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx'.

Falha ao criar o disco rígido virtual.

O sistema não pôde criar 'C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx': O arquivo já existe. (0x80070050).
em New-MobyLinuxVM, <Nenhum arquivo>: linha 208
em <ScriptBlock>, <Nenhum arquivo>: linha 394
   em Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) na C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:linha 36
   em Docker.Actions.<>c__DisplayClass25_0.<SwitchDaemon>b__0() na C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:linha 273
   em Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() na C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:linha 59

**Comment by ebriney** [comment]
Hi @deyvsonaguiar can you send a report please
