### ISSUE TITLE
Problem running Docker's image

### ISSUE THREAD

**Issue by JGARCI7** [docker/for-win#1697]
### Expected behavior
hello-world
### Actual behavior
docker : C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container 
a9946ace7a25491c9826e666e7c09b5f73a8cbbf5d588958594a2146c6d4cd9c encountered an error during CreateContainer: failure in a 
Windows system call: No hay ningÃºn hipervisor en este sistema.
### Information

PS C:\WINDOWS\system32> docker info
Containers: 19
 Running: 0
 Paused: 0
 Stopped: 19
Images: 2
Server Version: 17.12.0-ce
Storage Driver: windowsfilter
 Windows: 
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 3.953GiB
Name: Juan-PC
ID: YVUU:SCS5:C7MS:QPE7:PYC6:F6WZ:7RBQ:L26V:MKVS:KQQH:WHCT:4T7I
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 29
 System Time: 2018-02-13T17:49:19.2560311+01:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

PS C:\WINDOWS\system32> docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:05:22 2017
 OS/Arch:	windows/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.24)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:15:52 2017
  OS/Arch:	windows/amd64
  Experimental:	true
### Steps to reproduce the behavior

  1. docker run hello-world

**Comment by snegas** [comment]
Hello @JGARCI7 ,

I would suggest next steps

- Open **Turn Windows features on or off** window
- Select **Containers** and **Hyper-V** (see the screenshot)
- Click OK & restart your computer

![screen shot 2018-02-13 at 11 34 51 pm](https://user-images.githubusercontent.com/9533852/36174964-96c9ae12-1116-11e8-9038-c0db32d6fd74.png)

It will work if you have Pro or Enterprise version of Windows and it looks like you do base on the information you've provided.

Hope it will help
