### ISSUE TITLE
Docker is stuck starting

### ISSUE THREAD

**Issue by Sammaye** [docker/for-win#170]
### Expected behavior

Docker starts
### Actual behavior

Docker encounters some kind of error and gets stuck
### Information

99C4D560-284B-48EE-8E9B-F77FDA2BE720/2016-10-26_08-36-07 is all In have, no docker files etc since I have not got that far
### Steps to reproduce the behavior
1. Install ocker
2. Try to start it

**Comment by rneugeba** [comment]
@Sammaye Thanks for your report. Could you try the latest Beta from https://download.docker.com/win/beta/InstallDocker.msi
it has a number of improvements, but even if it does not fix your issue, it will have some additional logging which would allow us to debug the issue better. If the issue still persist with the Beta, we'd appreciate if you could provide another diagnostics ID
thanks

**Comment by Sammaye** [comment]
I got the beta upload here C01D4477-3263-4F30-99F8-99D827E3CEC5/2016-10-27_08-28-59 it fails but does say more about why

**Comment by rneugeba** [comment]
Thanks for the logs. It looks like the Linux VM started successful and you should be able to run docker commands from a powershell. What is the error you see when you do something like `docker info` or similar after the animation of the whale in the systray stopped?

**Comment by Sammaye** [comment]
The animation never stops, that was what first concerned me.

But I will see what happens when I try and run docker commands as soon as I get back to my computer

**Comment by rneugeba** [comment]
@Sammaye had you had a chance to test this? If not I'm inclined to close this issue due to inactivity.
thanks

**Comment by Sammaye** [comment]
Poop, forgot all about, this I will get this done today, sorry about that

**Comment by Sammaye** [comment]
I reverted to using virtualbox so that's why I forgot about this

**Comment by Sammaye** [comment]
Oh, suddenly it is actually completing and working (from what I can see).

Yep, even kitematic is starting up now.

Not sure how it works, hyper-v does always seem a bit like 50/50 as to whether it works or not on a try.

**Comment by rneugeba** [comment]
@Sammaye thanks for getting back so quick and glad that it's working now. As you are probably aware you can't run VirtualBox at the same time as Hyper-V and we had issues reported where switching between them sometimes causes issues, in particular with Hyper-V.  When this happens, it's worth double checking that VirtualBox is completely un-installed, including the network adapters it creates.

Closing this issue.

**Comment by Sammaye** [comment]
I had never installed Virtualbox on this Windows install when I created this issue initially. 

It seems that installing toolbox, uninstalling it and then installing the hyper-v edition has made it work.

**Comment by rneugeba** [comment]
Docker Toolbox installs VirtualBox.

**Comment by Sammaye** [comment]
Indeed, that's where I got virtualbox from. So I installed toolbox as a
replacement to hyper-v, went to uninstall it today to test this and now
hyper-v edition suddenly works.
