### ISSUE TITLE
How to use host storage in kubernetes

### ISSUE THREAD

**Issue by thexder1** [docker/for-win#1703]
### Expected behavior
Able to mount shared drive in containers running in kubernetes

### Actual behavior
Could not find any way to configure this

### Information
I am using Docker for Windows Edge with the built in Kubernetes configuration and trying to mount a persistent volume of some kind from the host. I am running Windows 10 Enterprise. I thought I would be able to use the local volumes that were added as alpha in Kubernetes, but they are behind feature gates and I do not see any way to enable them so I can use that.

### Steps to reproduce the behavior

  1. Install Docker for Windows Edge
  2. Make sure you are using Linux Containers
  3. Open Docker settings, go to kubernetes tab and check the boxes and click apply
  4. Go to shared drives tab and share drive
  5. Ponder the possible ways this share could get passed into kubernetes.

**Comment by pgayvallet** [comment]
Hello,

In the 18.03-rc1 edge version (due this week), you will be able to use hostPath type volume to mount volumes shared from the host. Just use a hostPath volume. VM-side, the shared drive are in the `/host_mnt` folder. I.E: `"/host_mnt/c/path/to/my/folder` for a folder in the C drive.

**Comment by thexder1** [comment]
That does not seem to work, gives me an error saying something about
failing test for directory.

**Comment by thexder1** [comment]
OK, it works when I do not specify a type, but if I speficy type: Directory
I get the error "MountVolume.SetUp failed for volume "host" : hostPath type
check failed: /host_mnt/e/mysql_data is not a directory" on anything other
than the root.

**Comment by creativearmenia** [comment]
Running docker version 18.03.0-ce-rc1 on windows 10 
Failed to mount volume from persistentvolumeclaim,
it shows error under Events **Error: Error response from daemon: invalid mode:** 

![image](https://user-images.githubusercontent.com/619418/36775492-b3fda342-1c7b-11e8-9266-9094b4a66e0d.png)

**Comment by gpassero** [comment]
+1

**Comment by seanturner83** [comment]
+1

**Comment by kalexmills** [comment]
Do you need to have shared drives set up to enable k8s persistent volumes? It asks me to share the c:\ drive whenever I try to create a PVC.

And I am not having success with setting up shared drives in Docker for Windows.

**Comment by iBeizsley** [comment]
Anybody figure out the invalid mode issue? Am a newbie to both Docker and Kubernetes, but have managed to struggle through until this point.

Getting 

      Normal   Scheduled              2s    default-scheduler            Successfully assigned consoleapp to docker-for-desktop
      Normal   SuccessfulMountVolume  2s    kubelet, docker-for-desktop  MountVolume.SetUp succeeded for volume "consoleappmount"
      Normal   SuccessfulMountVolume  2s    kubelet, docker-for-desktop  MountVolume.SetUp succeeded for volume "default-token-p7w45"
      Normal   Pulled                 1s    kubelet, docker-for-desktop  Container image "netcorerunner" already present on machine
      Warning  Failed                 1s    kubelet, docker-for-desktop  Error: Error response from daemon: invalid mode: /mount

For

    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: consoleapp
      labels:
        app: consoleapp
    spec:
      containers:
      - name: consoleapp
        imagePullPolicy: Never
        image: netcorerunner
        args:
          - "/mount/Example.ConsoleApp.dll"
        ports:
        - containerPort: 80
        volumeMounts:
          - name: consoleappmount
            mountPath: /mount
      volumes:
        - name: consoleappmount
          hostPath:
        path:  C:/Projects/Builds/Example.ConsoleApp

**Comment by iBeizsley** [comment]
Invalid mode issue was solved for me by replacing

    volumes:
      - name: consoleappmount
        hostPath:
          path: C:/WhateverPath

with

    volumes:
      - name: consoleappmount
        hostPath:
          path: /C/WhateverPath

Misleading error message, but there's an issue for that already here:

https://github.com/kubernetes/kubernetes/issues/59876

**Comment by figaw** [comment]
@pgayvallet Thank you for your comment, it totally works, how... do you know this? :)

I'm trying to figure out where the documentation is for this, but the only thing I can find is a reference in [Docker for Windows Stable Release notes](https://docs.docker.com/docker-for-windows/release-notes/) under **Docker Community Edition 17.12.0-ce-win47 2018-01-12**:
> Fix Mount compatibility when mounting drives with -v //c/..., now mounted in /host_mnt/c in the LinuxKit VM. Fixes docker/for-win#1509, docker/for-win#1516, docker/for-win#1497

Thank you! (I'm only commenting here because the issue is still open.)
