### ISSUE TITLE
Empty mount folder if windows credentials changed

### ISSUE THREAD

**Issue by ivanbeldad** [docker/for-win#1705]
### Expected behavior

Docker should ask windows credentials if they are changed.

### Actual behavior

Docker doesn't throw errors if mount a folder after change your windows password, but it is always empty.

### Information

  - **Diagnostic ID**: B847770E-936B-417D-B049-2F0B5059CBEB/2018-02-15_05-05-10
  - **Docker**: Version 18.02.0-ce-win52 (15732)
  - **SO**: Windows 10 Pro Version 1709. Build 16299.248

### Steps to reproduce the behavior

  1. Share a drive
  2. Change your windows user password
  3. Run a container mounting a folder inside the shared drive.

**Comment by pgayvallet** [comment]
Hello,

We are not doing active checking of drive mounting/unmounting, so things like changing password or unmounting an usb drive will currently result in this, yes.

As workaround, you can simply unshare/reshare the drive from the settings.
