### ISSUE TITLE
Installation with build 10586

### ISSUE THREAD

**Issue by karlkras** [docker/for-win#1708]
### Expected behavior
Should install on (in fact, resulting error actually states as such):
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.10586 Build 10586

### Actual behavior
On install attempt:
`Docker for Windows 17.12.0-cd-win47`
`Installation failed: one pre-requeisite is not fullfuilled`
`Docker for Windows requires Windows 10 Pro or Enterprise version 10586, or Windows server 2016 RTM to run`

### Information
Pretty self explanatory.

### Steps to reproduce the behavior

  1. download latest installer for windows to a Windows 10 Enterprise , 10.0.10586 Build 10586 box
  2. Run it ...
  3. Error.

I've heard "solutions" that recommend updating the windows build version. I'm in a large corporate environment that will not allow such an "upgrade" without all systems getting this change, and they won't do this. Updates to the current build will be applied, but to an entirely different build, so this isn't an option. Or should it be.

**Comment by sundhaug92** [comment]
Do you have the hyper-v feature enabled?

**Comment by karlkras** [comment]
Well I've been running vbox vms on it no problem, so I would think so.

**Comment by ebriney** [comment]
Hi.

It's a mistake in the min req, we don't support 10586 anymore, you must have 14393 or newer build.
