### ISSUE TITLE
Docker for Windows Daemon logging configuration

### ISSUE THREAD

**Issue by stationcasinosgithub** [docker/for-win#171]
I'm trying to change the logging driver at the daemon level to use Splunk.
### Expected behavior

All container stdout and stderr logs sent to Splunk instance
### Actual behavior

Docker daemon fails to start.  Note: these options work at the container level.
### Information
- Diagnostic ID: 9F282288-85A8-4C23-9FA1-D559BB12CDDB/2016-10-26_11-19-22
### Steps to reproduce the behavior

Modify daemon configuration using Docker for Windows UI:
{
  "registry-mirrors": [],
  "insecure-registries": [],
  "debug": false,
  "log-driver": "splunk",
  "log-opts": [
    "splunk-token=<valid token here>",
    "splunk-url=<valid url here>",
    "splunk-insecureskipverify=true"
  ]
}

**Comment by dgageot** [comment]
Hi @stationcasinosgithub it looks like your `daemon.json` needs some fixing. Log options should have this form: `{ "log-opts": { "env": "FOO" } }`

See https://github.com/docker/docker/issues/22311
