### ISSUE TITLE
Cannot change default volume size in docker EE

### ISSUE THREAD

**Issue by heaths** [docker/for-win#1710]
### Expected behavior

When I add `"storage-opts": [ "size=127GB" ]` to daemon.json (or whatever is set as the daemon configuration file), I expect the volume size to be limited to that amount.

This does not appear to be a dup of #731 since that is docker CE, and setting `storage-opts` in docker CE has worked for me for quite a while.

### Actual behavior

The setting has no effect in 17.06-ee on Windows Server 2016. The volume size is still the 20GB default.

### Information

No diagnostic ID since this is docker 17.06-ee on Windows Server 2016 build 1709.

### Steps to reproduce the behavior

  1. Stop the docker service: sc stop docker
  2. Add/edit %ProgramData%\docker\config\daemon.json with content,
     ```json
     "storage-opts": [
       "size=127GB"
     ]
     ```
  3. Restart the docker service: sc start docker

**Comment by isanych** [comment]
Yep, it's the same for me, somehow option work as command line parameter, but not from daemon.json

**Comment by heaths** [comment]
/lifecycle frozen

Can someone who works on d4w comment? This seems like a good option (or just the general class of issue about what dockerd accepts via daemon.js) for EE. It certainly makes administration much easier than having to customize the service start command line.

**Comment by stephen-turner** [comment]
This repo is for Docker Desktop issues, and this bug is about Docker EE on Windows Server, so closing.
