### ISSUE TITLE
Docker on Windows 10 Pro Not Starting

### ISSUE THREAD

**Issue by ashrithr** [docker/for-win#1711]
I ran into an issue, where Docker for Windows cannot start so I re-installed it and now I am running into this issue:

```
Version: 18.02.0-ce-win52 (15732)
Channel: edge
Sha1: 92c7ac6fd6d2f3876329f394b1482a0d89211762
Started on: 2018/02/15 14:50:37.696
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1709
Build: 16299
BuildLabName: 16299.15.amd64fre.rs3_release.170928-1534
File: C:\Users\ashri\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[14:50:37.782][GUI            ][Info   ] Starting...
[14:50:37.794][GUI            ][Error  ] An instance is already running. Exiting.
```

I am not sure where the other instance is running. I tried creating the VM manually using docker-machine, restarted the docker service but nothing works.

Thanks!

**Comment by empperi** [comment]
I am facing the exact same issue. Would appreciate some information how Docker For Windows makes it's assumption regarding if Docker is already running or not. I've killed everything which is related to docker, services etc.  Basically, if one tries to execute `Docker for Windows.exe` it never shows anything but just prints a similar log file as what is shown in the original issue comment. This obviously prevents using Docker completely.

**Comment by stu4355226** [comment]
I am having the same issue. I've been tried to re-install, reboot my system over 10 times and still had no good news. From what i research, this issue has been known for at least 2 years (found a thread on 2016). It's hard to believe that many users cannot event open the production application.

**Comment by empperi** [comment]
As a first workaround I would love to hear from the Docker team what and where should I remove so that I could be absolutely 100% certain that every last bit of Docker has been removed from my system before I try to reinstall it. If this problem however cannot be fixed with that but it is actually a bug in the code doing the check if the instance is already running then I would very much prefer a quick fix for this. This is a blocker for me and it's making me hard to do my work since I need Docker on daily basis. I've tried edge and stable versions and so forth, nothing helps. Docker still just thinks it is already running even when I'm absolutely positive it isn't.

This is a blocker level bug, I truly hope someone from the Docker team pops by to comment this real soon.

**Comment by empperi** [comment]
Similar issues are starting to pop up, at least #1723 is a duplicate of this.

**Comment by empperi** [comment]
Oh wow. Just tried: now it started! Nothing has changed with the exception that several days have passed. It cannot be due to restarting the computer, because I tried that earlier already. The issue is definitely still there but fortunately now I can at least continue working with the dockerizing of our app.

**Comment by BillRiess** [comment]
@empperi can you elaborate on anything else that might have changed. I've been trying to get this to work for several days now.

**Comment by empperi** [comment]
I wish I could. I did try the following:

* Reinstall Docker
* Downgrade Docker (which means another reinstall)
* Kill everything at process level which has Docker mentioned
* Ensure Docker service is dead
* Reboot system (obviously)
* Manually delete everything from the hard drive which is related to Docker

Nothing worked. Then suddenly today I just tried again if it would start and to my surprise it did. 4 days have passed. I truly have no idea wtf happened. My only guess is that the code that assumes Docker is running is reading some kind of pid file somewhere but it has a failsafe in place which checks that if the pid file is too old then Docker cannot be running. This is purely guessing, I would love someone from the Docker Win team to pop by and confirm this and if it is indeed the case, then tell us what the pid file is so we could use deleting that file as a workaround in the near future while they are working on a true fix.

**Comment by ashrithr** [comment]
As pointed by @BillRiess  in #1723, killing the Razer Synapse 3 lets the Docker start again properly. @empperi you are right, it would have been better if the Docker log contains what process is conflicting with it for quickly debugging this issue.

**Comment by empperi** [comment]
Oh wow, I also do have a Razer mouse and Synapse. It must be the reason: it kept on crashing yesterday so I killed it. Later I found out Docker was able to start up. Geesh, good to know what is causing this.

**Comment by empperi** [comment]
I reported this bug to Razer too. Let's hope either one fixes it or even better: they would cooperate to ensure bugs like these do not happen again.

**Comment by stu4355226** [comment]
I make docker running as well today. Simply I just tried to kill all the process and re-open again and it works.
 Not sure what happened since I haven't done any changes in my local machine, it is just simply works after few days.

**Comment by jasonvasquez** [comment]
Oh wow - thank you so much! I hit the same issue and had been uninstalling, reinstalling, switching release channels, etc. for days.  I stopped razer synapse and voila!
