### ISSUE TITLE
Request for CLI option to share drive

### ISSUE THREAD

**Issue by RichieSams** [docker/for-win#1714]
### Expected behavior
Be able to share drives using DockerCli.exe

### Actual behavior
Sharing drives requires using the Docker for Windows GUI

### Information

I am working on creating and script to automate installation Docker for Windows. This will be used to ensure docker is installed on our server farm.

I am able to install silently, and start the daemon. However, the one issue remaining is sharing drives. The GUI is really nice; you click the checkbox next to the drive you want to share and the runtime does everything for you. I would like to request being able to call this with `DockerCli.exe`

DockerCli has a `-SharedDrives` switch, but this only lists the currently shared drives; it does not allow you to change which ones are shared.

Where does the code for `DockerCli.exe` live? I would be willing to help with an implementation if I can browse the code.

**Comment by RichieSams** [comment]
I decompiled the exe and dlls. I found some undocumented, experimental flags:

```
"C:\Program Files\Docker\Docker\DockerCli.exe" -Mount=<drive letter> --testftw!928374kasljf039 -Username=<user> -Password=<pass>

"C:\Program Files\Docker\Docker\DockerCli.exe" -Unmount=<drive letter> --testftw!928374kasljf039
```

They are working, but it's clear from the necessary `testftw` flag, they're still experimental.

**Comment by jasonbivins** [comment]
HI @RichieSams 
Thanks for your request - i went ahead and entered this in as an enhancement request for you - and I'll go ahead and close this issue out.

**Comment by RichieSams** [comment]
Thanks
