### ISSUE TITLE
Unable to connect AWS in 1.12.1

### ISSUE THREAD

**Issue by pratapnanda** [docker/for-win#172]
Hello,
I have installed docker toolbox from stable channel .I am unable to pointing to amazon aws instance .I can able to connect aws instance in previous version(1.11.2) by setting up the UCP client bundle .I don't get any such steps in 1.12.1. 

How to connect a running cluster in aws from window 10.

**Comment by friism** [comment]
For Docker toolbox issues, please use the Toolbox issue tracker: https://github.com/docker/toolbox/issues

... or consider installing Docker for Windows: https://docs.docker.com/docker-for-windows/
