### ISSUE TITLE
Python 2.X or 3.X images won't run on Windows 10

### ISSUE THREAD

**Issue by Disruption** [docker/for-win#1722]
### Expected behavior
Python 2.7 image runs properly

### Actual behavior
Loading fails with message:
Status: Downloaded newer image for python:2.7
standard_init_linux.go:195: exec user process caused "no such file or directory"

### Information
Diagnostic id: 9931324C-2F7D-4D9E-A9D2-D493A9BF8F75/2018-02-19_16-43-08

### Steps to reproduce the behavior
Simply run "docker run python:2.7"
It will fail with different messages.

Running the following will *work properly*:
- docker run hello-world
- docker run -it ubuntu bash

So the setup itself seems fine.

**Comment by stephen-turner** [comment]
I would assume this was a problem with the image, not with Docker for Windows, unless it worked on Linux.

In any case, I can't reproduce this. Could you check if it's working for you now?
