### ISSUE TITLE
Docker won't start

### ISSUE THREAD

**Issue by BillRiess** [docker/for-win#1723]
### Expected behavior
Docker starts.

### Actual behavior
Docker doesn't start.

### Information

```
Version: 17.12.0-ce-win47 (15139)
Channel: stable
Sha1: 9c692cd5b38166289573183371647d915f300292
Started on: 2018/02/19 17:15:35.189
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1709
Build: 16299
BuildLabName: 16299.15.amd64fre.rs3_release.170928-1534
File: C:\Users\Bill\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[17:15:35.262][GUI            ][Info   ] Starting...
[17:15:35.273][GUI            ][Error  ] An instance is already running. Exiting.
```

### Steps to reproduce the behavior

Installed docker and noticed the icon never showed up in the system tray. I've tried re-enabling both hyper-v and containers but it didn't help. Docker never starts.

**Comment by BillRiess** [comment]
I believe I found the problem, although it seems quite weird...

Uninstalling Razer Synapse 3 fixed the problem. I was trying to get Docker running when I had an update for Synapse when it was in the middle of the update I started Docker and it worked fine. Once the update was done I reboot the PC and noticed Docker refused to start again. This time I uninstalled Synapse completely and tried and Docker started right up. Confirmed after a reboot that it still works without Synapse installed.

This isn't the first time Synapse has caused issues with programs starting or running properly. This should be investigated more.

**Comment by ashrithr** [comment]
@BillRiess Thanks for pointing it out! Killing the Razer Synapse 3 fixed my issue as well.

**Comment by ThinkDualBrain** [comment]
@BillRiess suggestion also worked for me. Intel Thunderbolt was causing a conflict. This must be a recent change from one or the other, because I've been running both side-by-side for a while now without issue.

**Comment by mmeyer429** [comment]
Looks like someone found the actual issue:
https://www.reddit.com/r/docker/comments/815l9n/docker_for_windows_wont_start_if_razer_synapse_3/

**Comment by mat007** [comment]
Fixed in 18.05.0-ce-rc1-win63 (17439), thank you everyone.

**Comment by z0nekill** [comment]
#1563 is a bug that is linked to this one - and can probably be closed after this update :)

**Comment by jerelev** [comment]
I have the exact same issue with the current stable version.
18.03.1-ce-win65 (17513)
I've moved to the edge and it's working.
