### ISSUE TITLE
Docker not starting on Windows10

### ISSUE THREAD

**Issue by smartmeta** [docker/for-win#1728]
### Expected behavior

Excpect that docker starts.

### Actual behavior

Docker does not start.

### Information

Docker version 17.12.0-ce, build c97c6d6

A diagnostic was uploaded with id: 155A7B40-FBD2-4ED8-818B-2248450A2512/2018-02-20_12-22-35

Running on Windows 10 Enterprise

![image](https://user-images.githubusercontent.com/10464459/36421791-236a2efa-163a-11e8-94c6-2dd9174333c9.png)

### Steps to reproduce the behavior

I just installed docker and restarted the system.

Hyper-V is installed and active:

![image](https://user-images.githubusercontent.com/10464459/36421881-79257020-163a-11e8-9e79-63c544eed775.png)

#  Errors are 
```
...
[10:35:37.556][Linux          ][Error  ] Failed to start: Unable to create: Das Argument für den Parameter "VMSwitch" kann nicht überprüft werden. Das Argument ist NULL. Geben Sie einen gültigen Wert für das Argument an, und führen Sie den Befehl erneut aus.
bei New-MobyLinuxVM, <Keine Datei>: Zeile 243
bei <ScriptBlock>, <Keine Datei>: Zeile 409. Let's retry
...
[10:35:47.107][NamedPipeClient][Error  ] Unable to send Start: Unable to create: Das Argument für den Parameter "VMSwitch" kann nicht überprüft werden. Das Argument ist NULL. Geben Sie einen gültigen Wert für das Argument an, und führen Sie den Befehl erneut aus.
bei New-MobyLinuxVM, <Keine Datei>: Zeile 243
bei <ScriptBlock>, <Keine Datei>: Zeile 409
[10:35:46.763][Firewall       ][Info   ] Removing all existing rules...
[10:35:47.123][Notifications  ][Error  ] Unable to create: Das Argument für den Parameter "VMSwitch" kann nicht überprüft werden. Das Argument ist NULL. Geben Sie einen gültigen Wert für das Argument an, und führen Sie den Befehl erneut aus.
bei New-MobyLinuxVM, <Keine Datei>: Zeile 243
bei <ScriptBlock>, <Keine Datei>: Zeile 409
....
[10:35:47.060][NamedPipeServer][Error  ] Unable to execute Start: Unable to create: Das Argument für den Parameter "VMSwitch" kann nicht überprüft werden. Das Argument ist NULL. Geben Sie einen gültigen Wert für das Argument an, und führen Sie den Befehl erneut aus.
bei New-MobyLinuxVM, <Keine Datei>: Zeile 243
bei <ScriptBlock>, <Keine Datei>: Zeile 409    bei Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:Zeile 181.
   bei Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:Zeile 130.
   bei Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:Zeile 47.
   bei Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:Zeile 145.
```

How can I help you to solve my problem?

**Comment by smartmeta** [comment]
I also added Docker to the Firewall

![image](https://user-images.githubusercontent.com/10464459/36422561-dd52571e-163c-11e8-9328-ee07c1cde9f9.png)

to be sure that this is not the problem. 
After restart now I get;

 Unable to execute Start: Unable to start: Der ausgeführte Befehl wurde beendet, da die Einstellungsvariable "ErrorActionPreference" oder ein allgemeiner Parameter auf "Stop" festgelegt ist: Fehler beim Starten von "MobyLinuxVM".

Fehler beim Starten des virtuellen Computers "MobyLinuxVM", da eine der Hyper-V-Komponenten nicht ausgeführt wird.

Fehler beim Starten von "MobyLinuxVM" (ID des virtuellen Computers A417031B-D048-4274-9F85-4CA766C2C3DD).

Der virtuelle Computer "MobyLinuxVM" konnte vom Verwaltungsdienst für virtuelle Computer nicht gestartet werden, da eine der Hyper-V-Komponenten nicht ausgeführt wird (ID des virtuellen Computers: A417031B-D048-4274-9F85-4CA766C2C3DD)..
bei Start-MobyLinuxVM, <Keine Datei>: Zeile 315
bei <ScriptBlock>, <Keine Datei>: Zeile 410    bei Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:Zeile 256.
   bei Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:Zeile 130.
   bei Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:Zeile 47.
   bei Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:Zeile 145.
[12:48:58.287][NamedPipeClient][Error  ] Unable to send Start: Unable to start: Der ausgeführte Befehl wurde beendet, da die Einstellungsvariable "ErrorActionPreference" oder ein allgemeiner Parameter auf "Stop" festgelegt ist: Fehler beim Starten von "MobyLinuxVM".

Fehler beim Starten des virtuellen Computers "MobyLinuxVM", da eine der Hyper-V-Komponenten nicht ausgeführt wird.

Fehler beim Starten von "MobyLinuxVM" (ID des virtuellen Computers A417031B-D048-4274-9F85-4CA766C2C3DD).

Der virtuelle Computer "MobyLinuxVM" konnte vom Verwaltungsdienst für virtuelle Computer nicht gestartet werden, da eine der Hyper-V-Komponenten nicht ausgeführt wird (ID des virtuellen Computers: A417031B-D048-4274-9F85-4CA766C2C3DD)..
bei Start-MobyLinuxVM, <Keine Datei>: Zeile 315
bei <ScriptBlock>, <Keine Datei>: Zeile 410
[12:48:58.287][Notifications  ][Error  ] Unable to start: Der ausgeführte Befehl wurde beendet, da die Einstellungsvariable "ErrorActionPreference" oder ein allgemeiner Parameter auf "Stop" festgelegt ist: Fehler beim Starten von "MobyLinuxVM".

Fehler beim Starten des virtuellen Computers "MobyLinuxVM", da eine der Hyper-V-Komponenten nicht ausgeführt wird.

Fehler beim Starten von "MobyLinuxVM" (ID des virtuellen Computers A417031B-D048-4274-9F85-4CA766C2C3DD).

Der virtuelle Computer "MobyLinuxVM" konnte vom Verwaltungsdienst für virtuelle Computer nicht gestartet werden, da eine der Hyper-V-Komponenten nicht ausgeführt wird (ID des virtuellen Computers: A417031B-D048-4274-9F85-4CA766C2C3DD)..
bei Start-MobyLinuxVM, <Keine Datei>: Zeile 315
bei <ScriptBlock>, <Keine Datei>: Zeile 410


I uploaded this also : 
A diagnostic was uploaded with id: 155A7B40-FBD2-4ED8-818B-2248450A2512/2018-02-20_12-52-55

**Comment by jasonbivins** [comment]
Hi @smartmeta it looks like there's a Hyper-V issue  
``` vmswitch.sys failed to load the message resource is present but the message is not found in the string/message table```

Try to remove Hyper-V - reboot and then reinstall it
1. Disable Hyper-V and containers
```
Disable-WindowsOptionalFeature -FeatureName microsoft-hyper-v -online
Disable-WindowsOptionalFeature -Online -FeatureName Containers -All
```

2. reboot - then Enable Hyper-V and containers
 ```
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All

 Enable-WindowsOptionalFeature -Online -FeatureName Containers -All
```

Reinstall Docker

**Comment by smartmeta** [comment]
First one worked

```
PS C:\Windows\system32> Disable-WindowsOptionalFeature -FeatureName microsoft-hyper-v -online
Möchten Sie den Computer jetzt neu starten, um den Vorgang abzuschließen?
[Y] Yes  [N] No  [?] Hilfe (Standard ist "Y"): N


Path          :
Online        : True
RestartNeeded : True
```
but the second one faild 

```
PS C:\Windows\system32> Disable-WindowsOptionalFeature -Online -FeatureName Containers -All
Disable-WindowsOptionalFeature : Es wurde kein Parameter gefunden, der dem Parameternamen "All" entspricht.
In Zeile:1 Zeichen:64
+ Disable-WindowsOptionalFeature -Online -FeatureName Containers -All
+                                                                ~~~~
    + CategoryInfo          : InvalidArgument: (:) [Disable-WindowsOptionalFeature], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Dism.Commands.DisableWindowsOptionalFeatureCommand
```

But I'll restart now and see if I can enable both.

**Comment by smartmeta** [comment]
I just gave https://github.com/docker/for-win/issues/1338#issuecomment-352872963 a try.

But the first step faild:
```
PS C:\Windows\system32> docker-machine create --driver hyperv vm
Creating CA: C:\Users\itdlz-hooso\.docker\machine\certs\ca.pem
Creating client certificate: C:\Users\itdlz-hooso\.docker\machine\certs\cert.pem
Running pre-create checks...
(vm) Image cache directory does not exist, creating it at C:\Users\itdlz-hooso\.docker\machine\cache...
(vm) No default Boot2Docker ISO found locally, downloading the latest release...
(vm) Latest release for github.com/boot2docker/boot2docker is v18.02.0-ce
(vm) Downloading C:\Users\itdlz-hooso\.docker\machine\cache\boot2docker.iso from https://github.com/boot2docker/boot2doc
ker/releases/download/v18.02.0-ce/boot2docker.iso...
(vm) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
Creating machine...
(vm) Copying C:\Users\itdlz-hooso\.docker\machine\cache\boot2docker.iso to C:\Users\itdlz-hooso\.docker\machine\machines
\vm\boot2docker.iso...
(vm) Creating SSH key...
(vm) Creating VM...
(vm) Using switch "nat"
(vm) Creating VHD
(vm) Starting VM...
Error creating machine: Error in driver during machine creation: exit status 1
PS C:\Windows\system32>
```
maybe this gives a hint what's going wrong.

After restarting Docker I still get:

```
Unable to start: Der ausgeführte Befehl wurde beendet, da die Einstellungsvariable "ErrorActionPreference" oder ein allgemeiner Parameter auf "Stop" festgelegt ist: Fehler beim Starten von "MobyLinuxVM".
```

**Comment by edm00se** [comment]
I find myself in the same proverbial "boat". I got the same on upgrading to the latest stable, yesterday (17.03.0-ce); I didn't think to check what I was running prior to it.

I then tried uninstalling and installing the latest edge (18.02.0-ce) and get the same results.
Diagnostic id: `87E55A45-F003-4D23-BA19-175CF5F057B6/2018-02-21_08-41-31`

**Comment by smartmeta** [comment]
I wonder why there are 87 open issues containing 'ErrorActionPreference' and there is nearly no solution for it. Or is there?

**Comment by smartmeta** [comment]
I just tried to switch to windows containers 
like mentioned in https://stackoverflow.com/a/46613592/2032248
and now Docker is running and no longer complaining. 

Shouldn't that (windows containers ) be the default?

**Comment by edm00se** [comment]
@smartmeta I use Docker on Windows solely to use Linux based containers, as opposed to Windows containers. Since Windows containers are comparatively new, they're not a default for Docker for Windows.

ref: https://docs.docker.com/docker-for-windows/install/#about-windows-containers-and-windows-server-2016

**Comment by edm00se** [comment]
My issues appear resolved after my machine updated to the `Windows 10 Insider Preview 17107.1000 (rs4_release)`. This appears to be related to a previous build of Windows 10 Insider. I ran docker, got the previous warning, sent crash report (probably not needed), then once more clicked on the "reset to factory settings". Now it is working as expected, 

```
Docker CE
Version 17.12.0-ce-win47 (15139)
Channel: stable
9c692cd
```

**Comment by smartmeta** [comment]
Updated to version Version: 18.03.0-ce-win59 (16762) solved my problem.
