### ISSUE TITLE
Docker swarm overlay networking, connecting to the swarm from outside or localhost

### ISSUE THREAD

**Issue by yamac-kurtulus** [docker/for-win#1729]
Hello, 
I cannot connect to the published port on the swarm that uses overlay networking. I am using Docker for Windows with Windows containers. Both Windows and Docker are fully upgraded. After Windows' 1709 update, I was hoping this issue would be resolved. I looked for information on the Internet to see if I was doing something wrong to no avail. I would like to know if anyone was successfully able to get it working. 

On a side note, when I direct the port on my machine in `docker run -p 80:80` without using swarm, "localhost" does not work as well. I think this is a known limitation though. Both issues work when I switch to Linux containers. 

### Expected behavior
I am running a dotnet kestrel web server service. I should be able to connect to my service using the published port. 

### Actual behavior
Firefox gives me timeout, opera straight away returns connection refused. Cannot telnet into it either. Container IP's assigned by the overlay network do not work either.

### Information
`docker service ls` gives me this:
![image](https://user-images.githubusercontent.com/32689837/36435220-1e2675c4-1672-11e8-95e9-d6566f41f81b.png)
Ports cannot be seen there, is it because publish mode is host? Ports information is available in the output of `docker service ps`
![image](https://user-images.githubusercontent.com/32689837/36435315-6449768c-1672-11e8-8265-99d11c4a5d52.png) 
And when I change the publish mode, I can scale it as well and the port information is seen in `docker service ls` albeit still cannot connect. the one below is without the `publish mode=host` parameter:
![image](https://user-images.githubusercontent.com/32689837/36435874-dc2d3a84-1673-11e8-94bb-a3fa828d79ce.png)
For more info, this is the output of the `docker network ls` I wonder if i need some sort of bridge network like in Linux.
![image](https://user-images.githubusercontent.com/32689837/36435709-6fee5da8-1673-11e8-96d0-c3f3247d25bb.png)

### Steps to reproduce the behavior

  1. Initialise swarm
  2. Start the service, in my case: a simple web service built using aspnetcore:latest image. I tried different parameters, even used a docker-stack.yml:
     `docker service create --name=web --publish mode=host,published=80,target=80 web:aspnetcorelatest`  in the case above, I was unable to scale it on the same machine, which is normal i guess 
    `docker service create --name=web --publish published=85,target=80 web:aspnetcorelatest`
  3. Try to connect using one of `http://localhost` or another IP. I tried connecting over VPN, from another machine as well as Internet IP.

**Comment by lukee8** [comment]
Did you installed preview version of docker? You need it if you want to use overlay network (17.06 is not enough).

**Comment by rn** [comment]
What is your Docker for Windows version and the OS version? Can you upload diagnostics?
