### ISSUE TITLE
Docker Beta Crashes when updating

### ISSUE THREAD

**Issue by ManoMarks** [docker/for-win#173]
### Expected behavior

Docker for Windows will update
### Actual behavior

Docker Crashes after update. Docker can be restarted from start menu
### Information
- Diagnostic ID from "Diagnose & Feedback" in the menu.
  E32C97F5-7DA6-4441-B622-154CC9DE121D/2016-10-27_11-06-56
- host distribution and version (Windows version, build number, etc)
  Windows 10 version 1607, Docker for Windows
  This has happened the last few times Docker upgraded.

**Comment by rneugeba** [comment]
This issue seem to have falling through the cracks...It is quite old and there have been many changes since. I'm closing it but please re-open if you encounter the issue again.

Thanks for reporting and apologies that we didn't respond sooner.
