### ISSUE TITLE
Can't use Docker on Windows. open //./pipe/docker_engine: The system cannot find the file specified.

### ISSUE THREAD

**Issue by EdLichtman** [docker/for-win#1738]
### Expected behavior
I expect that when I run docker ps, I can see my docker containers.

### Actual behavior
When I run docker ps, instead I get an error message.

### Information
Error message is: 

error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.35/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

This is on a new Windows 10 device with VirtualBox installed. Docker prompted me to use Hyper-V which would cause problems. in order to get this working I tried:

PS
New-VMSwitch -name ExternalSwitch -NetAdapterName Wi-Fi -AllowManagementOS $true
New-VMSwitch -name InternalSwitch -SwitchType Internal

CMD
docker-machine create DataStorageService -d "hyperv"
Net stop com.docker.service
Net start com.docker.service

**Comment by pgayvallet** [comment]
What do you mean by `Docker prompted me to use Hyper-V which would cause problems` ? Did you enable it or not ?

**Comment by DominikDitoIvosevic** [comment]
@EdLichtman why did you close this? What was the fix?

**Comment by kenorb** [comment]
> docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows

This is general connectivity error to the service. Most likely related to desktop app not being running. So make sure it's in the tray icon up and running, otherwise restart it. Otherwise, check the firewall and antivirus for any block rules.

**Comment by AbsolutelyFreeWeb** [comment]
I had this same problem today. The docker service and docker desktop were both running (and I restarted them) additionally I made sure the command prompt window was elevated. Still I would get this same error. The problem resolved by restarting the computer.
