### ISSUE TITLE
CAB41BE6-900B-4E82-956C-75209DC60D84/2018-02-22_10-06-41

### ISSUE THREAD

**Issue by Tandev2018** [docker/for-win#1739]
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by pgayvallet** [comment]
Hi,

Closing. Please reopen with proper description if still present.
