### ISSUE TITLE
Can't share drive on Windows

### ISSUE THREAD

**Issue by StarpTech** [docker/for-win#1743]
### Expected behavior
I can share a drive

### Actual behavior
I can't share a drive

### Information

A diagnostic was uploaded with id: 67236A24-F2DD-4251-B5C0-3AB8EA21BF58/2018-02-22_21-59-28

Important logs:
```
[21:57:34.029][SambaShare     ][Error  ] Unable to mount E drive: 10.0.75.1 (10.0.75.1:445) open
rm: can't remove '/e': No such file or directory
rm: can't remove '/E': No such file or directory
umount: can't unmount /host_mnt/e: Invalid argument
mount error(112): Host is down
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
mount: mounting //10.0.75.1/E on /host_mnt/e failed: Invalid argument
...
```

### Steps to reproduce the behavior

  1. Open docker settings
  2. Share drive E:
  3. Type password
  4. Prompt disappears and nothing happens. The drive is unchecked.

**Comment by matheusmariano** [comment]
I solved this problem reseting Docker to factory defaults.

![image](https://user-images.githubusercontent.com/2306588/44688746-8961be00-aa2b-11e8-894c-941b41c29fa5.png)

**Comment by kiview** [comment]
Resetting to factory defaults didn't solve the problem for me.

**Comment by stephen-turner** [comment]
The file sharing code has been completely rewritten in 2.2, so I'm assuming this issue has now gone. If not, please open a new ticket.
