### ISSUE TITLE
Docker run with --publish of a port already in use gives an ambiguous error

### ISSUE THREAD

**Issue by KevM** [docker/for-win#1745]
For windows containers when the user already has a process listening on the host port being published to during the `docker run`. The error message does not mention ports but a file which is potentially misleading.

### Expected behavior

``` Error response from daemon: failed to create endpoint mssql on network nat: HNS failed with error : The process cannot publish port 1433 to the host port 1433 as it is already being used by another process.```

### Actual behavior

``` Error response from daemon: failed to create endpoint mssql on network nat: HNS failed with error : The process cannot access the file because it is being used by another process.```

### Steps to reproduce the behavior

```
net start mssqlserver
docker run --name mssql -d -p 1433:1433 microsoft/mssql-server-windows-developer
```

**Comment by KevM** [comment]
Sorry, accidentally opened this too quickly. Re-opening with actual details. 🙄

**Comment by kriskomar-scentsy** [comment]
I second this. I am experiencing this exact same thing and was able to confirm that it is in fact a port conflict and not a file. This isn't the first time a bad error message has sent me on a wild goose chase. Is it possible Docker could do a little technical debt term-fixing project to make errors more comprehensive?

**Comment by Kesmy** [comment]
I just spent six bloody hours trying to figure out why my container wouldn't start, what a massive waste of time when all you had to do was print the right error.

**Comment by stephen-turner** [comment]
I think this is an upstream bug, so I have copied it to moby/moby#36983.
