### ISSUE TITLE
Couldn't share drive.  

### ISSUE THREAD

**Issue by jinh-dk** [docker/for-win#1749]
### Expected behavior
share C drive with container. 
### Actual behavior
Coundn't share C drive. 
### Information
  - Diagnostic ID :  C17F6262-6919-488C-9076-4589934C4505/2018-02-25_13-23-59

### Steps to reproduce the behavior

1. Open docker settings
2. Share drive C:
3. Type password
4. a prompt said _A firewall is blocking file Sharing between Windows and the containers. See documentation for more info._

I have checked the firewall setting,  it allows to connect 10.0.75.1 on port 445.  
I also tried to reinstall  _File and Print Sharing service_ on DockerNET,  but it didn't help.  
![image](https://user-images.githubusercontent.com/26903080/36641574-e38debfe-1a31-11e8-947e-6f8b20b3e110.png)

**Comment by RaedsLab** [comment]
Same issue

**Comment by robnardo** [comment]
Looks like similar to #1762

**Comment by stephen-turner** [comment]
Closing as dupe of #1762 (and the solution seems to be there).
