### ISSUE TITLE
Docker does not start after reboot, but does start after logoff and login

### ISSUE THREAD

**Issue by dragonejt** [docker/for-win#1750]
### Expected behavior
Docker will start after reboot because I ticked the box in settings. It also will start when I doubleclick the desktop icon.
### Actual behavior
Docker will not start after reboot, nor will it start when I doubleclick the icon. There is a background process called Docker Service in Task Manager, but there is no tray icon. However, it will start after I logout and log back in. 
### Information
Windows 10 Pro Version 1709
Intel Core i7-6500U, 8GB RAM, 256GB SSD, 1TB HDD. Docker is installed on the SSD, along with Windows.
Processor Virtualization Enabled
Hyper-V Enable (2 Virtual Switches: Default and nat)

When I issue docker login on first reboot:
C:\Users\drago>docker login
Warning: failed to get default registry endpoint from daemon (error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.35/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.). Using system default: https://index.docker.io/v1/
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.

### Steps to reproduce the behavior

  1. Reboot Computer
  2. Wait for a few minutes and/or doubleclick the docker desktop icon. No tray icon appears.
  3. Sign out and Sign back in
  4. Wait for a few minutes and/or doubleclick the docker desktop icon. This time, a tray icon will appear saying Docker is starting.

**Comment by woudwijk84** [comment]
Allmost the same for me, except i am not getting an error on startup. After i signout of Windows and relog, Docker starts. I'm on a Windows 10 Enterprise machine. Added a textfile with the docker info output.
[docker-info.txt](https://github.com/docker/for-win/files/1987385/docker-info.txt)
