### ISSUE TITLE
Cannot start container after Docker for Windows first launch

### ISSUE THREAD

**Issue by sudoloic** [docker/for-win#1752]
### Expected behavior
Container should start with command `docker start -i [container_name]`

### Actual behavior
Error when starting container with command `docker start -i [container_name]`:
`Error response from daemon: driver failed programming external connectivity on endpoint [container_name](b67716c6c255663face61398ac447d72fe133ebb6402b5fd6a019a2d8fd6ae5c): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:8080:tcp:172.17.0.2:8080: input/output error`

Docker for Windows needs to be relaunched to be able to start a container

### Information

  - Diagnostic ID : 6CCDFB9C-855C-43BC-BDDC-CF2E9BCB90C2/2018-02-26_13-18-16
  - Always reproductible

### Steps to reproduce the behavior

  1. Reboot computer
  2. Launch Docker for Windows
  3. Wait until Docker is started
  4. Run command `docker start -i [container_name]`
  5. Error : `Error response from daemon: driver failed programming external connectivity on endpoint [container_name](b67716c6c255663face61398ac447d72fe133ebb6402b5fd6a019a2d8fd6ae5c): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:8080:tcp:172.17.0.2:8080: input/output error`

### Workaround
   1. Stop Docker for Windows
   2. Re-launch Docker for Windows
   3. Wait until Docker is started
   4. Run command `docker start -i [container_name]`
   5. Container started

**Comment by sudoloic** [comment]
Well... duplicate of https://github.com/docker/for-win/issues/1038

**Comment by firdanirp** [comment]
I solved this problem with restart my docker. I think this problem occured because we need to stop and exit docker before we shutdown our pc.

**Comment by jasonwilliams** [comment]
/remove-lifecycle stale 

This is still happening

Its always the first time.
After i restart docker it works

OS Name	Microsoft Windows 10 Pro
Version	10.0.17134 Build 17134
Docker Version 2.0.0.0-beta1-win75 (19925)
Channel: edge
915f68b
