### ISSUE TITLE
Docker 18.02 / 18.03 on Windows 10 1709 - Port mappings don't work

### ISSUE THREAD

**Issue by artiomchi** [docker/for-win#1756]
We've just updated to Docker Edge 18.02 on several machines and ran into the same issue.

We tried running both a linux and a windows container:

```
docker run --platform linux -d -p 8081:80 nginx
docker run -d -p 8082:80 microsoft/dotnet-samples:aspnetapp
```

### Expected behavior
We should be able to access either site by browsing to `http://localhost:8081` or `http://localhost:8081`.

### Actual behavior
In both cases we get a connection refused error. TCPView doesn't find a single process listening on these ports. When trying to access the sites by their internal IPs, the connection succeeds and the pages load fine: `http://172.17.42.246`

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

Diagnostic ID: F347ABB3-52E5-4FE3-B3F1-C48C42ABF4C9/2018-02-27_12-46-23

### Steps to reproduce the behavior

Run the following:
```
docker run --platform linux -d -p 8081:80 nginx
docker run -d -p 8082:80 microsoft/dotnet-samples:aspnetapp
```

Try to access the pages via `http://localhost:8081` or `http://localhost:8081`

**Comment by artiomchi** [comment]
It sounds like [this comment](https://github.com/docker/for-win/issues/1255#issuecomment-347460030) from #1255 might be relevant, but it's hard for me to know for sure

**Comment by artiomchi** [comment]
Additional information - when running in Linux Containers mode (when it runs a Hyper-V VM), the `docker networks ls` command returns three networks: `bridge`, `host` and `none`. When running in Windows Containers mode I only get `nat` and `none`. 

I was under the assumption that `nat` under windows 1709 should finally work, and while there are references to that, I'm not seeing this here

**Comment by artiomchi** [comment]
One more note, I ran the Windows container image on a Server 2016 1709 build (running docker 17.06, same networks returned by `docker network ls`, and the port mappings work

**Comment by jasonbivins** [comment]
Hi @artiomchi 
Thanks for reporting, I was able to reproduce this on the latest edge, but it does seem to be working properly on the stable channel.  I went ahead and  reported it as a bug

**Comment by Kesmy** [comment]
#1737 is the same, or a similar, issue.

**Comment by artiomchi** [comment]
Looks like it may be related, although on our environment the stable 17 build did work, while the edge build never managed to forward a port even once

**Comment by mlmeyers** [comment]
@artiomchi is it possible you have patch KB4074588 installed release just a couple weeks back? 

Our issues are introduced with this CU patch from MS. Would not be surprised if the issue is related to the same.

**Comment by artiomchi** [comment]
@mlmeyers I just checked, and indeed I do have that update installed. I've just uninstalled it to see if the issue is fixed - and port forwarding started working! Awesome

Seems like #1707 is the best issue for this

**Comment by mlmeyers** [comment]
@artiomchi thanks for the heads up and glad it got you going again. Unfortunately I work for a large organization and rolling back CU updates is not going to fly as a workaround | fix. @jasonbivins hopefully this helps to get traction on the issue.

**Comment by artiomchi** [comment]
Oh yeah, of course. I've seen your thread about it :)

I just did it to confirm whether this is the same issue or not, and whether I can close this ticket then

**Comment by Kesmy** [comment]
@mlmeyers I've also removed the update (which resolved the issue), and just wanted to second your assertion that removing the update is an unacceptable workaround.

**Comment by mlmeyers** [comment]
@Kesmy we unfortunately have multiple tracks going. I have decided to focus on  https://github.com/docker/for-win/issues/1707 as that is around the KB patch and port forwarding issues. They call out permission denied error but more is going on related to that CU. I would follow that thread to come up to speed :-)

If you don't mind would be great if you can confirm that with the patch applied you are not binding to a port listed as already reserved prior to container starting (details on how to check are in 1707) and post back the findings to https://github.com/docker/for-win/issues/1707. 

Cheers!
