### ISSUE TITLE
Set "-platform linux" as default in LCOW

### ISSUE THREAD

**Issue by hoegge** [docker/for-win#1759]
### Feature request 
I prefer to run LCOW to disable Hyper-V so I can use VMWare and Virtualbox on same machine.
But it seems like Kitematic can't pull Linux images and create linux containers when running on Windows containers and that you have to provide the `-platform linux` argument whenever you pull an image. I suppose that docker compose will also run into issues

I raised it at Kitematic since I thought it should be an option in Kitematic to choose platform, but they sent me here docker/kitematic#3609 

Is there or shouldn't there be a way to tell docker to always pull Linux images, since I for instance would probably never run any Windows images?

**Comment by carlfischer1** [comment]
@hoegge to change the default LCOW platform to Linux:

```[Environment]::SetEnvironmentVariable("LCOW_API_PLATFORM_IF_OMITTED", "linux", "Machine")```
```Restart-Service Docker```

Note that LCOW requires Hyper-V isolation, and therefore nested virtualization when running on a virtualization platform. idk how that will work with VMW and VirtualBox

https://blog.docker.com/2018/02/docker-for-windows-18-02-with-windows-10-fall-creators-update/

**Comment by hoegge** [comment]
What is the point of LCOW if you cannot run without the Hyper-V hypervisor anyway? Guess I misunderstood the release notes then.
It is really annoying there seems to be no way to use Docker and VMWare / Virtualbox on the same Windows machine. Would be nice if Docker for Windows had the option to use Virtual Box or VMware for containers instead. Docker toolbox seems to be abandoned but should be merged into Docker for Windows. 

Thanks for your clarification

**Comment by hoegge** [comment]
@carlfischer1 So this [https://www.hanselman.com/blog/DockerAndLinuxContainersOnWindowsWithOrWithoutHyperVVirtualMachines.aspx](url) saying:
`With the latest version of Windows 10 (or 10 Server) and the beta of Docker for Windows, there's native Linux Container support on Windows. That means there's no Virtual Machine or Hyper-V involved (unless you want), so Linux Containers run on Windows itself using Windows 10's built in container support.`
is not true?

**Comment by carlfischer1** [comment]
@hoegge both statements are true :)

Containers using Hyper-V isolation are different from Hyper-V VMs. They are an optimized VM that allows use of a different kernel than the host: https://docs.microsoft.com/en-us/virtualization/windowscontainers/about/

With LCOW for each Linux container there is a Hyper-V isolated container spun-up running a minimal purpose-built Linux kernel. As the blog post says, that's different from the previous Linux containers support in Docker for Windows that used a full-blown Hyper-V VM. 

So, the requirement for nested virtualization comes from the use of Hyper-V isolated containers, not Hyper-V VMs.

**Comment by artiomchi** [comment]
@carlfischer1 actually, I think the `LCOW_API_PLATFORM_IF_OMITTED` environment variable is no longer used.

Check this repository's readme: https://github.com/linuxkit/lcow, specifically this part:

> On older docker master builds:
> 
> Start the docker daemon (in an elevated PowerShell):
>
> ```$env:LCOW_SUPPORTED=1
> $env:LCOW_API_PLATFORM_IF_OMITTED="linux"
> Remove-Item c:\lcow -Force -Recurse; mkdir c:\lcow
> .\dockerd.exe -D --experimental --data-root c:\lcow
> ```

Also check this comment here: https://github.com/moby/moby/issues/35303#issuecomment-347687570

Seems like it's a cli preference setting, configured using the `DOCKER_DEFAULT_PLATFORM` environment variable. So it can even be set in the current command line, and it will affect only the current context. For a system wide setting, run this:

```powershell
[Environment]::SetEnvironmentVariable("DOCKER_DEFAULT_PLATFORM", "linux", "Machine")
```

That's what I set on my machine, and it's working like a charm on Docker for Windows 18.03

**Comment by rn** [comment]
I'm closing this issue here as this better discussed upstream in https://github.com/moby/moby, where the development happens. There is a PR https://github.com/moby/moby/pull/36418 which will make the `--platform=linux` obsolete.
