### ISSUE TITLE
Updated to Docker for Windows Edge 18.03.0 and volume mounted directories are empty in container.

### ISSUE THREAD

**Issue by klday** [docker/for-win#1765]
### Expected behavior
Using the same command to run and mount volumes as prior to the update.

### Actual behavior
When I run the container, the directories that were mounted in the run command are empty in the container.

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
         256EA96C-AA68-4B31-B843-711B788E8B6B/2018-03-01_06-41-17
  - host distribution and version (Windows version, build number, etc)
         18.03.0-ce-rc1-win54 (16164)
### Steps to reproduce the behavior

  1. From Anaconda prompt on a Windows PC> winpty docker run –-rm –it –v “C:\\Users\\myuser\\mydir\\myapp:/opt/Allegion/myapp” –v “C:\\Users\\myuser\\mydir\\utils:/opt/mydir/utils” –p 8888:8888 image/myapp:v0.0.0
  2. When container runs, at prompt> ls mydir/myapp
  3. The directory is empty
  4.  > ls utils
  5.  Also empty
  6.  Checked directories on local machine and all files are there.  
  7.  I tried changing the paths in the run command various different ways from removing quotes, to making the c lower case and changes 2 back slashes to one forward slash.  The paths are shown are the only ones that ran without an error, but then the directories are empty in the container.  
  8.  I used the exact same run command prior to update without issue.

**Comment by dzek69** [comment]
Had the same.

1. I restarted windows. Got infinite "Docker is starting".

2. I tried restarting again. Got ininite "Restarting" from Windows.

3. I forced computer power off and booted up again. Didn't touch anything, Docker started as usual. Everything works as usual.

Try it, good luck!

**Comment by laverya** [comment]
Also had the same. (Diagnostic `B3445382-D33C-4AD4-91D0-6BB05E82D18B/2018-04-23_13-28-46`)

Unfortunately, my issue was not resolved upon restarting Windows.

Docker version:
```Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:06:28 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   0520e24
  Built:        Wed Mar 21 23:14:32 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

Test output:

```
# C:\Users [13:54:19]
➜ ls


    Directory: C:\Users


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       2017-10-26     19:04                Administrator
d-----       2018-04-23     13:41                Andrew
d-r---       2017-10-26     19:55                Public


# C:\Users [13:54:21]
➜ docker run --rm -v /c/Users/:/data alpine ls -a /data/
.
..
# C:\Users [13:55:43]
➜ docker run --rm -v c:/Users/:/data alpine ls -a /data/
.
..
# C:\Users [13:56:32]
```

The C drive is shared according to the UI.

**Comment by dpgalloway** [comment]
I had the same issue mounting volumes with docker-compose, and was able to solve the same way as @laverya. I went into Docker settings, un-shared my C drive, clicked "Reset credentials", then attempted to run docker-compose again, re-entered my credentials and re-shared the C drive. After this, the volumes mounted correctly.
