### ISSUE TITLE
ERROR: readlink /var/lib/docker/overlay2: invalid argument when docker-compose up

### ISSUE THREAD

**Issue by FiveSigma5** [docker/for-win#1766]
### Expected behavior

`docker-compose up myservice` runs myservice

### Actual behavior

`docker-compose up myservice`
ERROR: readlink /var/lib/docker/overlay2: invalid argument

### Information

```
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:22 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:29 2017
  OS/Arch:      linux/amd64
  Experimental: true
```
Diagnostic ID: 158DC9A3-FAC7-49A8-ACF8-E7B20ADBE936/2018-03-01_13-52-21

OS: Windows 10 Pro
Edition: Professional

### Steps to reproduce the behavior

  1. docker-compose build myservice
  2. docker-compose up myservice

**Comment by IQNeoXen** [comment]
I do have exactly the same issue here... same OS, same docker version

**Comment by iskandersierra** [comment]
I'm having the same problem in version:
```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:28 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:13:46 2018
  OS/Arch:          linux/amd64
  Experimental:     false
 Kubernetes:
  Version:          v1.10.3
  StackAPI:         v1beta2
```

When I issue the command:
```
> docker-compose -f deploy\devenv-docker-compose.yaml up
```
The only answer I get is:
```
ERROR: readlink /var/lib/docker/overlay2/l: invalid argument
```
This is my devenv-docker-compose.yaml file:
```
version: "3.6"

services:
  nats-streaming:
    image: nats-streaming:0.10.2-linux
    ports:
    - 4222:4222
    - 8222:8222
```

**Comment by bakeiro** [comment]
Same here, win 10 pro with last version of docker (stable)
I end up resetting docker to factory default to solve the problem

**Comment by zeppelinlg** [comment]
Same here, each time need to reset docker to factory default

**Comment by Andremoniy** [comment]
Same here for MacOS High Sierra 10.13.6

**Comment by sirockin** [comment]
Same problem running docker on Windows 10 - I had to reset to factory default as above.
Docker version 18.09.2, build 624
docker-compose version 1.23.2, build 1110ad01
