### ISSUE TITLE
Docker 18.03 Linux based images built using LCOW can't be deployed to registries

### ISSUE THREAD

**Issue by artiomchi** [docker/for-win#1769]
So I've narrowed this down to as small an example as I could. I created a small hello world repo here: https://github.com/artiomchi/HelloWorld

When building the app using a linux image, while running 18.03 in Windows Container mode, the image builds successfully and can be started locally. But it fails when trying to deploy it to a remote registry.

### Expected behavior
`docker push ` should successfully push the image to the docker registry

### Actual behavior
The top layer retries multiple times, until eventually gives up with the following:
```powershell
PS D:\Development\HelloWorld\HelloWorld> docker push artiomchi/helloworld:alpine
The push refers to repository [docker.io/artiomchi/helloworld]
d140feb78cc6: Pushing [==================================================>]  262.7kB/262.7kB
154dc7e00f30: Layer already exists
c5de6b3aa838: Layer already exists
9dfa40a0da3b: Layer already exists
open \tmp\8797231b7737236ea8608ab3f7e63846a37cbfea164db833fbbbce80f392fceb-mount\app\HelloWorld.deps.json: The system cannot find the path specified.
```

### Information

Reproduced on several machines. Have a test repo that can be easily used to repro this. Running on Windows 10 with Fall Creator's update

### Steps to reproduce the behavior

```powershell
git clone https://github.com/artiomchi/HelloWorld.git
cd HelloWorld/HelloWorld
docker build --rm -f Dockerfile-lin-alpine -t helloworld:alpine . --no-cache
docker tag helloworld:alpine artiomchi/helloworld:alpine
docker push artiomchi/helloworld:alpine
```

**Comment by carlfischer1** [comment]
@artiomchi thanks for the detailed repro - this appears to be specific to moby/moby rather than Docker for Windows. please open an issue there and cc me.

**Comment by artiomchi** [comment]
Sure, will do! Thanks

I'll close this issue then
