### ISSUE TITLE
Docker image building in LCOW is **considerably** slower than using linux containers

### ISSUE THREAD

**Issue by artiomchi** [docker/for-win#1771]
Again, using my small hello world project as an example: https://github.com/artiomchi/HelloWorld

Running a very simple `docker build` command in windows containers mode with lcow, the whole process finishes in `1:03`. When running in linux containers mode it only takes `0:13`!!.

Seems like there's a significant delay between running each step, possibly slow disk operations. But it might be something else too.

### Expected behavior
The performance should be comparable, at least reasonably close between the two methods

### Actual behavior
Docker builds in lcow are **significantly** slower than when running in linux containers mode

### Information

Running Docker 18.03 on Windows 10 with 1709 Fall creator's update.
Disk shouldn't be an issue - running on an NVME SSD

Providing a simple repo to reproduce the issue

### Steps to reproduce the behavior

Running the build twice, to make sure that the build and runtime images are downloaded, and their download isn't affecting the timing.

```powershell
git clone https://github.com/artiomchi/HelloWorld.git
cd HelloWorld/HelloWorld
docker build --rm -f Dockerfile-lin-alpine -t helloworld:alpine . --no-cache
```

**Comment by rn** [comment]
LCOW creates a new utility VM per layer, so yes, build will be a lot slower. I think there is an option to share the utility VM for building but that is not recommended as it drops isolation between builds.

**Comment by artiomchi** [comment]
Oh wow... seriously?

Are there any plans to.. improve this?

I mean, you can see the timings above. And that's with a "hello world" project. That means with a serious project the local build will take ages!

**Comment by rn** [comment]
You'd have to check with Microsoft. I would think there is some room for improvement but AFAIK the team is currently mostly focussing on closing the gap in terms of functionality rather than performance improvements.

**Comment by artiomchi** [comment]
Damn.. that's.. sad to hear.

Thanks for taking the time to explain it to me

**Comment by rn** [comment]
FWIW, there is a "global mode" which re-uses a single VM during build, ie does not spin up a VM per layer, which ought to be faster. It basically hotplugs the layers into the VM as disks when building. 

However, there are some issues/bugs with this mode and I don't know how it behaves with concurrent builds, so YMMW.

You can try enabling it by setting the storage options, ie.:
```
 dockerd --experimental -D --storage-opt lcow.globalmode=1
```

**Comment by artiomchi** [comment]
You're an absolute legend!

Just tested the build script with global mode enabled, and the build time went down from over a minute to 32 sec! Still a far fetch from the timing in Linux mode, but that's a step forward

As you said, it's an experimental option, but it's something to look forward to (and test carefully) 😄
