### ISSUE TITLE
An item with the same key has already been added

### ISSUE THREAD

**Issue by silverl** [docker/for-win#1780]
### Expected behavior
Docker for Windows should start without error.
### Actual behavior
Docker for Windows starts with an error and is unusable.
### Information
Windows 10 Enterprise 
Version 10.0.16299 Build 16299
Hyper-V enabled
VirtualBox was installed, but uninstalled it and enabled Hyper-V.

Starting Docker for Windows results in an Error dialog containing the following text:
```
An error occurred
An item with the same key has already been added.
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 67
   at Docker.Actions.<>c__DisplayClass14_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 51
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```

Diagnostic ID: `5F5E3872-3905-40DE-B9B2-AD9EC2581829/2018-03-03_16-24-06`

I believe it's indicating that the named pipe `docker_engine` is missing. I have confirmed that it is missing by executing the following:

```
PS C:\Users\username> [System.IO.Directory]::GetFiles("\\.\\pipe\\") | Select-String "docker"

\\.\\pipe\\dockerBackend
\\.\\pipe\\PSHost.131645888929187251.3336.DefaultAppDomain.com.docker.service
\\.\\pipe\\dockerLogs
\\.\\pipe\\docker_d4w_systray
\\.\\pipe\\dockerBackendToGui
\\.\\pipe\\dockerVpnKitControl
\\.\\pipe\\dockerMobyLinuxVM-com1
\\.\\pipe\\dockerVpnKitDiagnostics

PS C:\Users\lsilverman> docker ps
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.37/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```
The powershell is elevated already. The Docker for Windows Service service is running.

### Steps to reproduce the behavior
Start Docker for Windows.

**Comment by silverl** [comment]
Ultimately, got around the issue by uninstalling Docker for Windows, then Hyper-V (with multiple reboots). Then I re-installed Hyper-V (reboots again) and then Docker for Windows. Things are working now.

**Comment by bernardpumped** [comment]
Hi,

I'm now also getting this problem tried uninstalling Docker then Hyper-V with multiple reboots , hasn't made any difference for me.

**Comment by bbgobie** [comment]
Having same issue. Mine started after I got a notification that there was a new version and I hit upgrade.
Uninstalling and reinstalling the latest version of docker did not help.

**Comment by Martijn-Mink** [comment]
I have the same issue when trying to install Docker for the first time, It happens both for the stable and the edge channel. I tried reinstalling Docker, turning Hyper-V off in Windows Features, rebooting, and turning Hyper-V on. This did not fix the issue.

**Comment by silverl** [comment]
I'll reopen this.

**Comment by christophla** [comment]
I ended up rolling back to 17.12.0-ce-win47 and everything is working again.

https://docs.docker.com/docker-for-windows/release-notes/#stable-releases-of-2018

**Comment by Martijn-Mink** [comment]
Thanks! That fixed it for me.

**Comment by jurosh** [comment]
Thanks @christophla downgrade worked for me too! (no reboot needed)

**Comment by lmame** [comment]
Some of my colleagues at work are using Docker 18.03 without problem but in my case after upgrading from 17,12 to 18.03 I had the error mentioned in this thread.
Uninstalling / reinstalling 18.03 didn't solve the issue so I had to downgrade to 17.12 thanks for the tip :)

Maybe a lead, it seems that for my colleagues that don't have the issue they are running Windows 10 "1703" and I am on Windows 10 "1709".

Moreover, we are using Avecto Defendpoint. With Windows 10 "1703" it is not a problem, but with Windows 10 "1709" Docker couldn't start at all and I had to upgrade to latest Avecto Defendpoint version (so same kind of issue as reported on some boards around Sophos for example).

**Comment by bernardpumped** [comment]
Hi Imane,
thats good to know i'm also on win10 Pro 1709, but not using Avecto Defendpoint,
I also rolled back to 17.12.0-ce-win47

**Comment by silverl** [comment]
I just upgraded to `18.03.0-ce-win58 (16761)` and the dreaded `An item with the same key has already been added.` error is back again.

**Comment by Nxtra** [comment]
For me it was solved after doing the following steps:
- uninstall docker 18.03.0-ce-win58
- reboot
- install docker 17.12.0-ce-win47
- reboot

**Comment by silverl** [comment]
Where are you folks finding prior installers for Docker? I can't seem to locate an installer for version 17, so I'm stuck with a crippled Docker 18.

**Comment by silverl** [comment]
Nevermind. Found it here: https://docs.docker.com/docker-for-windows/release-notes/#stable-releases-of-2018

**Comment by silverl** [comment]
Rollback to 17 worked for me as well.

**Comment by johnthom** [comment]
My solution: uninstalled 18, installed 17, no reboots needed.

**Comment by alltej** [comment]
Same here. 17 works. Reason need to update to 18 is because of Kubernetes support (18) - `Kubernetes is only available in Docker for Windows 18.02 CE Edge`

Anybody got a solution yet with 18?

**Comment by wulf0r** [comment]
facing the same with 18.02 on windows .. WHY did I update. I really should know better.

**Comment by eriawan** [comment]
I have this Docker 18 issue on Windows as well.

Why is there no response from Docker team? It's been three weeks.

@MagnusS, @dsheets ?

**Comment by stephen-turner** [comment]
Could those people seeing this bug please retest with 18.03.1 (or Edge 18.04)? We believe it's fixed in that version. Please collect new diagnostics and open a new ticket if you're still seeing it after that. Thank you.

**Comment by lmame** [comment]
Hi @stephen-turner , sorry for the delay, I tried the 18.03.1 version and it works, Thanks!

**Comment by silverl** [comment]
@stephen-turner 
I'm the original poster. This release has resolved the issue.  👍

**Comment by stephen-turner** [comment]
Perfect, thanks for letting us know, everyone.

**Comment by Martijn-Mink** [comment]
A little late, but it also solved it for me, thanks.
