### ISSUE TITLE
Docker won't start with Hyper-V activated

### ISSUE THREAD

**Issue by Ephasme** [docker/for-win#1782]
### Expected behavior
Docker to start and run normally
### Actual behavior
Docker stops at the beginning and gives me a crash windows
### Information

> Version: 17.12.0-ce-win47 (15139)
> Channel: stable
> Sha1: 9c692cd5b38166289573183371647d915f300292
> Started on: 2018/03/04 10:19:36.658
> Resources: C:\Program Files\Docker\Docker\Resources
> OS: Windows 10 Education
> Edition: Education
> Id: 1709
> Build: 16299
> BuildLabName: 16299.15.amd64fre.rs3_release.170928-1534
> File: C:\Users\Loup\AppData\Local\Docker\log.txt
> CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
> You can send feedback, including this log file, at https://github.com/docker/for-win/issues
> [10:19:36.769][GUI            ][Info   ] Starting...
> [10:19:37.039][Tracking       ][Info   ] Crash report and usage statistics are enabled
> [10:19:37.042][SegmentApi     ][Info   ] Usage statistic: appLaunched
> [10:19:37.982][NPS            ][Info   ] NPS user ceated on :2/19/2018 3:40:44 PM -08:00, last survey : 1/1/0001 12:00:00 AM +00:00
> [10:19:37.983][SegmentApi     ][Info   ] Usage statistic: heartbeat
> [10:19:37.985][SegmentApi     ][Info   ] Usage statistic: Identify
> [10:19:38.119][NamedPipeClient][Info   ] Sending Version()...
> [10:19:38.137][NamedPipeClient][Info   ] Received response for Version
> [10:19:10.824][BackendServer  ][Info   ] Started
> [10:19:38.134][NamedPipeServer][Info   ] Version()
> [10:19:38.134][NamedPipeServer][Info   ] Version done in 00:00:00.
> [10:19:38.145][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings, Docker.Core.DaemonOptions)...
> [10:19:38.148][NamedPipeServer][Info   ] Start(Docker.Core.Settings, Docker.Core.DaemonOptions)
> [10:19:38.152][PowerMode      ][Info   ] Stop
> [10:19:38.153][HyperV         ][Info   ] Stop
> [10:19:38.184][PowerShell     ][Info   ] Run script with parameters: -Stop True...
> [10:19:38.192][PowerShell     ][Info   ] Creating a Runspace Pool...
> [10:19:38.457][PowerShell     ][Info   ] Runspace Pool created (Min=1, Max=2)
> [10:19:38.554][HyperV         ][Info   ] Script started at 10:19:38.538
> [10:19:40.107][HyperV         ][Info   ] Module loaded at 10:19:40.106
> [10:19:40.246][HyperV         ][Info   ] VM MobyLinuxVM does not exist
> [10:19:40.247][HyperV         ][Debug  ] [stop] took 00:00:02.0840015 to run
> [10:19:40.247][OptimizeDisk   ][Info   ] Optimize
> [10:19:40.247][PowerShell     ][Info   ] Run script...
> [10:19:40.287][Moby           ][Info   ] Stop
> [10:19:40.293][PowerMode      ][Info   ] Start
> [10:19:40.293][HyperVGuids    ][Info   ] Installing GUIDs...
> [10:19:40.294][HyperV         ][Info   ] Create
> [10:19:40.294][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso...
> [10:19:40.295][HyperVGuids    ][Info   ] GUIDs installed
> [10:19:40.296][Firewall       ][Info   ] Removing all existing rules...
> [10:19:40.300][HyperV         ][Info   ] Script started at 10:19:40.300
> [10:19:40.315][Firewall       ][Info   ] All existing rules are removed.
> [10:19:40.316][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
> [10:19:40.318][HyperV         ][Info   ] Module loaded at 10:19:40.318
> [10:19:40.320][Firewall       ][Info   ] Opening ports for SMB...
> [10:19:40.326][Firewall       ][Info   ] Ports are opened
> [10:19:40.650][HyperV         ][Info   ] Creating Switch: DockerNAT...
> [10:19:40.955][Linux          ][Error  ] Failed to start: Unable to create: L’exécution de la commande s’est arrêtée, car la variable de préférence « ErrorActionPreference » ou le paramètre courant a la valeur Stop : Hyper-V a rencontré une erreur lors d’une tentative d’accès à un objet sur l’ordinateur « DESKTOP-3MP242O », car l’objet est introuvable. L’objet a peut-être été supprimé. Vérifiez que le service de gestion d’ordinateurs virtuels est en cours d’exécution sur l’ordinateur.
> à New-Switch, <Aucun fichier> : ligne 132
> à <ScriptBlock>, <Aucun fichier> : ligne 409. Let's retry
> [10:19:40.999][HyperV         ][Info   ] Hyper-V is running
> [10:19:40.999][PowerMode      ][Info   ] Stop
> [10:19:41.000][HyperV         ][Info   ] Stop
> [10:19:41.000][PowerShell     ][Info   ] Run script with parameters: -Stop True...
> [10:19:41.006][HyperV         ][Info   ] Script started at 10:19:41.006
> [10:19:41.025][HyperV         ][Info   ] Module loaded at 10:19:41.025
> [10:19:41.222][HyperV         ][Info   ] VM MobyLinuxVM does not exist
> [10:19:41.225][HyperV         ][Debug  ] [stop] took 00:00:00.2249983 to run
> [10:19:41.225][OptimizeDisk   ][Info   ] Optimize
> [10:19:41.225][PowerShell     ][Info   ] Run script...
> [10:19:41.272][Moby           ][Info   ] Stop
> [10:19:41.283][HyperV         ][Info   ] Destroy
> [10:19:41.284][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
> [10:19:41.289][HyperV         ][Info   ] Script started at 10:19:41.289
> [10:19:41.300][HyperV         ][Info   ] Module loaded at 10:19:41.300
> [10:19:41.386][HyperV         ][Info   ] VM MobyLinuxVM does not exist
> [10:19:41.389][HyperV         ][Info   ] Destroying Switch DockerNAT...
> [10:19:41.477][HyperV         ][Info   ] Removing VM MobyLinuxVM...
> [10:19:41.518][HyperV         ][Debug  ] [destroy] took 00:00:00.2350013 to run
> [10:19:41.518][Firewall       ][Info   ] Closing ports...
> [10:19:41.518][Firewall       ][Info   ] Removing all existing rules...
> [10:19:41.575][Firewall       ][Info   ] All existing rules are removed.
> [10:19:41.575][Firewall       ][Info   ] Ports are closed
> [10:19:41.575][HyperVGuids    ][Info   ] Removing GUIDs...
> [10:19:41.576][HyperVGuids    ][Info   ] GUIDs removed
> [10:19:41.576][HyperV         ][Info   ] Create
> [10:19:41.576][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso...
> [10:19:41.580][HyperV         ][Info   ] Script started at 10:19:41.580
> [10:19:41.592][HyperV         ][Info   ] Module loaded at 10:19:41.592
> [10:19:41.724][HyperV         ][Info   ] Creating Switch: DockerNAT...
> [10:19:41.847][PowerMode      ][Info   ] Stop
> [10:19:41.847][HyperV         ][Info   ] Stop
> [10:19:41.847][PowerShell     ][Info   ] Run script with parameters: -Stop True...
> [10:19:41.851][HyperV         ][Info   ] Script started at 10:19:41.851
> [10:19:41.861][HyperV         ][Info   ] Module loaded at 10:19:41.860
> [10:19:41.907][HyperV         ][Info   ] VM MobyLinuxVM does not exist
> [10:19:41.908][HyperV         ][Debug  ] [stop] took 00:00:00.0610007 to run
> [10:19:41.908][OptimizeDisk   ][Info   ] Optimize
> [10:19:41.908][PowerShell     ][Info   ] Run script...
> [10:19:41.946][Moby           ][Info   ] Stop
> [10:19:41.950][HyperV         ][Info   ] Destroy
> [10:19:41.950][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
> [10:19:41.955][HyperV         ][Info   ] Script started at 10:19:41.955
> [10:19:41.962][HyperV         ][Info   ] Module loaded at 10:19:41.962
> [10:19:42.002][HyperV         ][Info   ] VM MobyLinuxVM does not exist
> [10:19:42.003][HyperV         ][Info   ] Destroying Switch DockerNAT...
> [10:19:42.112][HyperV         ][Info   ] Removing VM MobyLinuxVM...
> [10:19:42.151][HyperV         ][Debug  ] [destroy] took 00:00:00.2010025 to run
> [10:19:42.151][Firewall       ][Info   ] Closing ports...
> [10:19:42.151][Firewall       ][Info   ] Removing all existing rules...
> [10:19:42.171][Firewall       ][Info   ] All existing rules are removed.
> [10:19:42.171][Firewall       ][Info   ] Ports are closed
> [10:19:42.171][HyperVGuids    ][Info   ] Removing GUIDs...
> [10:19:42.171][HyperVGuids    ][Info   ] GUIDs removed
> [10:19:42.181][NamedPipeServer][Error  ] Unable to execute Start: Unable to create: L’exécution de la commande s’est arrêtée, car la variable de préférence « ErrorActionPreference » ou le paramètre courant a la valeur Stop : Hyper-V a rencontré une erreur lors d’une tentative d’accès à un objet sur l’ordinateur « DESKTOP-3MP242O », car l’objet est introuvable. L’objet a peut-être été supprimé. Vérifiez que le service de gestion d’ordinateurs virtuels est en cours d’exécution sur l’ordinateur.
> à New-Switch, <Aucun fichier> : ligne 132
> à <ScriptBlock>, <Aucun fichier> : ligne 409    à Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) dans C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:ligne 181
>    à Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) dans C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:ligne 130
>    à Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) dans C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:ligne 47
>    à Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) dans C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:ligne 145
> [10:19:42.237][NamedPipeClient][Error  ] Unable to send Start: Unable to create: L’exécution de la commande s’est arrêtée, car la variable de préférence « ErrorActionPreference » ou le paramètre courant a la valeur Stop : Hyper-V a rencontré une erreur lors d’une tentative d’accès à un objet sur l’ordinateur « DESKTOP-3MP242O », car l’objet est introuvable. L’objet a peut-être été supprimé. Vérifiez que le service de gestion d’ordinateurs virtuels est en cours d’exécution sur l’ordinateur.
> à New-Switch, <Aucun fichier> : ligne 132
> à <ScriptBlock>, <Aucun fichier> : ligne 409
> [10:19:42.238][Notifications  ][Error  ] Unable to create: L’exécution de la commande s’est arrêtée, car la variable de préférence « ErrorActionPreference » ou le paramètre courant a la valeur Stop : Hyper-V a rencontré une erreur lors d’une tentative d’accès à un objet sur l’ordinateur « DESKTOP-3MP242O », car l’objet est introuvable. L’objet a peut-être été supprimé. Vérifiez que le service de gestion d’ordinateurs virtuels est en cours d’exécution sur l’ordinateur.
> à New-Switch, <Aucun fichier> : ligne 132
> à <ScriptBlock>, <Aucun fichier> : ligne 409

![](https://i.imgur.com/XanudYq.png)

### Steps to reproduce the behavior

  1. Install Docker on Windows 10
  2. Activates Hyper-V
  3. Start Docker
  4. Docker fails to start

**Comment by Ephasme** [comment]
I think it's a problem with Hyper-V because when I run Start-VM -Name TestVM in Powershell I get that:
![](https://i.imgur.com/D6NMBaq.png)

**Comment by halofx** [comment]
I ran into this same issue. I had enabled Hyper-V through the Control Panel - "Turn Windows features on or off". Hyper-V Manager would launch, let me create a VM, but wouldn't start them.

I removed Hyper-V and re-enabled it through Power Shell, as Microsoft outlines here: https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v.

Now Hyper-V and Docker are working properly.

**Comment by jasonbivins** [comment]
```
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All
Enable-WindowsOptionalFeature -Online -FeatureName Containers -All

```

**Comment by Ephasme** [comment]
@halofx and @jasonbivins 
Tried both your solutions but none has proved successful.
I have this now:

> Version: 17.12.0-ce-win47 (15139)
> Channel: stable
> Sha1: 9c692cd5b38166289573183371647d915f300292
> Started on: 2018/03/11 12:02:07.714
> Resources: C:\Program Files\Docker\Docker\Resources
> OS: Windows 10 Education
> Edition: Education
> Id: 1709
> Build: 16299
> BuildLabName: 16299.15.amd64fre.rs3_release.170928-1534
> File: C:\Users\Loup\AppData\Local\Docker\log.txt
> CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
> You can send feedback, including this log file, at https://github.com/docker/for-win/issues
> [12:02:07.797][GUI            ][Info   ] Starting...
> [12:02:08.032][Tracking       ][Info   ] Crash report and usage statistics are enabled
> [12:02:08.034][SegmentApi     ][Info   ] Usage statistic: appLaunched
> [12:02:08.946][NPS            ][Info   ] NPS user ceated on :2/19/2018 3:40:44 PM -08:00, last survey : 1/1/0001 12:00:00 AM +00:00
> [12:02:08.948][SegmentApi     ][Info   ] Usage statistic: heartbeat
> [12:02:08.953][SegmentApi     ][Info   ] Usage statistic: Identify
> [12:02:09.040][NamedPipeClient][Info   ] Sending Version()...
> [12:02:09.044][NamedPipeClient][Info   ] Received response for Version
> [12:02:09.045][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings, Docker.Core.DaemonOptions)...
> [12:02:09.043][NamedPipeServer][Info   ] Version done in 00:00:00.
> [12:02:09.046][NamedPipeServer][Info   ] Start(Docker.Core.Settings, Docker.Core.DaemonOptions)
> [12:02:09.046][PowerMode      ][Info   ] Stop
> [12:02:09.046][HyperV         ][Info   ] Stop
> [12:02:09.046][PowerShell     ][Info   ] Run script with parameters: -Stop True...
> [12:02:09.050][HyperV         ][Info   ] Script started at 12:02:09.050
> [12:02:09.059][HyperV         ][Info   ] Module loaded at 12:02:09.059
> [12:02:09.102][HyperV         ][Info   ] VM MobyLinuxVM does not exist
> [12:02:09.102][HyperV         ][Debug  ] [stop] took 00:00:00.0560193 to run
> [12:02:09.102][OptimizeDisk   ][Info   ] Optimize
> [12:02:09.102][PowerShell     ][Info   ] Run script...
> [12:02:09.136][Moby           ][Info   ] Stop
> [12:02:09.140][HyperV         ][Info   ] Create
> [12:02:09.140][HyperVGuids    ][Info   ] Installing GUIDs...
> [12:02:09.140][PowerMode      ][Info   ] Start
> [12:02:09.140][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso...
> [12:02:09.140][Firewall       ][Info   ] Removing all existing rules...
> [12:02:09.140][HyperVGuids    ][Info   ] GUIDs installed
> [12:02:09.146][HyperV         ][Info   ] Script started at 12:02:09.146
> [12:02:09.155][HyperV         ][Info   ] Module loaded at 12:02:09.155
> [12:02:09.157][Firewall       ][Info   ] All existing rules are removed.
> [12:02:09.157][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
> [12:02:09.159][Firewall       ][Info   ] Opening ports for SMB...
> [12:02:09.163][Firewall       ][Info   ] Ports are opened
> [12:02:09.254][HyperV         ][Info   ] Creating Switch: DockerNAT...
> [12:02:09.356][Linux          ][Error  ] Failed to start: Unable to create: L’exécution de la commande s’est arrêtée, car la variable de préférence « ErrorActionPreference » ou le paramètre courant a la valeur Stop : Hyper-V a rencontré une erreur lors d’une tentative d’accès à un objet sur l’ordinateur « DESKTOP-3MP242O », car l’objet est introuvable. L’objet a peut-être été supprimé. Vérifiez que le service de gestion d’ordinateurs virtuels est en cours d’exécution sur l’ordinateur.
> à New-Switch, <Aucun fichier> : ligne 132
> à <ScriptBlock>, <Aucun fichier> : ligne 409. Let's retry
> [12:02:09.363][HyperV         ][Info   ] Hyper-V is running
> [12:02:09.363][PowerMode      ][Info   ] Stop
> [12:02:09.363][HyperV         ][Info   ] Stop
> [12:02:09.363][PowerShell     ][Info   ] Run script with parameters: -Stop True...
> [12:02:09.367][HyperV         ][Info   ] Script started at 12:02:09.367
> [12:02:09.374][HyperV         ][Info   ] Module loaded at 12:02:09.374
> [12:02:09.408][HyperV         ][Info   ] VM MobyLinuxVM does not exist
> [12:02:09.408][HyperV         ][Debug  ] [stop] took 00:00:00.0449882 to run
> [12:02:09.408][OptimizeDisk   ][Info   ] Optimize
> [12:02:09.408][PowerShell     ][Info   ] Run script...
> [12:02:09.441][Moby           ][Info   ] Stop
> [12:02:09.446][HyperV         ][Info   ] Destroy
> [12:02:09.446][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
> [12:02:09.453][HyperV         ][Info   ] Script started at 12:02:09.453
> [12:02:09.459][HyperV         ][Info   ] Module loaded at 12:02:09.459
> [12:02:09.493][HyperV         ][Info   ] VM MobyLinuxVM does not exist
> [12:02:09.494][HyperV         ][Info   ] Destroying Switch DockerNAT...
> [12:02:09.559][HyperV         ][Info   ] Removing VM MobyLinuxVM...
> [12:02:09.592][HyperV         ][Debug  ] [destroy] took 00:00:00.1461336 to run
> [12:02:09.592][Firewall       ][Info   ] Closing ports...
> [12:02:09.592][Firewall       ][Info   ] Removing all existing rules...
> [12:02:09.642][Firewall       ][Info   ] All existing rules are removed.
> [12:02:09.642][Firewall       ][Info   ] Ports are closed
> [12:02:09.642][HyperVGuids    ][Info   ] Removing GUIDs...
> [12:02:09.643][HyperVGuids    ][Info   ] GUIDs removed
> [12:02:09.643][HyperV         ][Info   ] Create
> [12:02:09.643][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso...
> [12:02:09.648][HyperV         ][Info   ] Script started at 12:02:09.648
> [12:02:09.656][HyperV         ][Info   ] Module loaded at 12:02:09.656
> [12:02:09.750][HyperV         ][Info   ] Creating Switch: DockerNAT...
> [12:02:09.855][PowerMode      ][Info   ] Stop
> [12:02:09.855][HyperV         ][Info   ] Stop
> [12:02:09.855][PowerShell     ][Info   ] Run script with parameters: -Stop True...
> [12:02:09.860][HyperV         ][Info   ] Script started at 12:02:09.860
> [12:02:09.867][HyperV         ][Info   ] Module loaded at 12:02:09.867
> [12:02:09.902][HyperV         ][Info   ] VM MobyLinuxVM does not exist
> [12:02:09.903][HyperV         ][Debug  ] [stop] took 00:00:00.0479820 to run
> [12:02:09.903][OptimizeDisk   ][Info   ] Optimize
> [12:02:09.903][PowerShell     ][Info   ] Run script...
> [12:02:09.938][Moby           ][Info   ] Stop
> [12:02:09.945][HyperV         ][Info   ] Destroy
> [12:02:09.945][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
> [12:02:09.949][HyperV         ][Info   ] Script started at 12:02:09.949
> [12:02:09.955][HyperV         ][Info   ] Module loaded at 12:02:09.955
> [12:02:09.990][HyperV         ][Info   ] VM MobyLinuxVM does not exist
> [12:02:09.991][HyperV         ][Info   ] Destroying Switch DockerNAT...
> [12:02:10.056][HyperV         ][Info   ] Removing VM MobyLinuxVM...
> [12:02:10.088][HyperV         ][Debug  ] [destroy] took 00:00:00.1430023 to run
> [12:02:10.089][Firewall       ][Info   ] Closing ports...
> [12:02:10.089][Firewall       ][Info   ] Removing all existing rules...
> [12:02:10.103][Firewall       ][Info   ] All existing rules are removed.
> [12:02:10.103][Firewall       ][Info   ] Ports are closed
> [12:02:10.103][HyperVGuids    ][Info   ] Removing GUIDs...
> [12:02:10.103][HyperVGuids    ][Info   ] GUIDs removed
> [12:02:10.103][NamedPipeServer][Error  ] Unable to execute Start: Unable to create: L’exécution de la commande s’est arrêtée, car la variable de préférence « ErrorActionPreference » ou le paramètre courant a la valeur Stop : Hyper-V a rencontré une erreur lors d’une tentative d’accès à un objet sur l’ordinateur « DESKTOP-3MP242O », car l’objet est introuvable. L’objet a peut-être été supprimé. Vérifiez que le service de gestion d’ordinateurs virtuels est en cours d’exécution sur l’ordinateur.
> à New-Switch, <Aucun fichier> : ligne 132
> à <ScriptBlock>, <Aucun fichier> : ligne 409    à Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) dans C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:ligne 181
>    à Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) dans C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:ligne 130
>    à Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) dans C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:ligne 47
>    à Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) dans C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:ligne 145
> [12:02:10.131][NamedPipeClient][Error  ] Unable to send Start: Unable to create: L’exécution de la commande s’est arrêtée, car la variable de préférence « ErrorActionPreference » ou le paramètre courant a la valeur Stop : Hyper-V a rencontré une erreur lors d’une tentative d’accès à un objet sur l’ordinateur « DESKTOP-3MP242O », car l’objet est introuvable. L’objet a peut-être été supprimé. Vérifiez que le service de gestion d’ordinateurs virtuels est en cours d’exécution sur l’ordinateur.
> à New-Switch, <Aucun fichier> : ligne 132
> à <ScriptBlock>, <Aucun fichier> : ligne 409
> [12:02:10.132][Notifications  ][Error  ] Unable to create: L’exécution de la commande s’est arrêtée, car la variable de préférence « ErrorActionPreference » ou le paramètre courant a la valeur Stop : Hyper-V a rencontré une erreur lors d’une tentative d’accès à un objet sur l’ordinateur « DESKTOP-3MP242O », car l’objet est introuvable. L’objet a peut-être été supprimé. Vérifiez que le service de gestion d’ordinateurs virtuels est en cours d’exécution sur l’ordinateur.
> à New-Switch, <Aucun fichier> : ligne 132
> à <ScriptBlock>, <Aucun fichier> : ligne 409

**Comment by jasonbivins** [comment]
@Ephasme 
Can you open up Hyper-V manager ? Are you able to start and _connect_ to any VM's there?

**Comment by Ephasme** [comment]
@jasonbivins when I try to connect to the local server I get this:
https://i.imgur.com/PVXmECk.png

**Comment by jasonbivins** [comment]
@Ephasme   It looks like Hyper-V isn't getting setup correctly, even when you installed it manually.  Is there anything helpful in your Windows event viewer?  Docker won't run until you repair your Hyper-V installation.

**Comment by ninjax95** [comment]
Do you have resolved your problem ? If yes, how did you do, i have the same problem.

Thanks

**Comment by Ephasme** [comment]
No I didn't solve my problem sorry...

**Comment by drou7** [comment]
I have the same problem. Someone solve the problem ?

**Comment by Chepech** [comment]
Same problem here, tryed desinstalling Hyper-V, and enabling it back both from the Ui and the command line, everything looks normal but can start VMs on Hyper-V manager and therefore Docker also fails to start. It was working correctly (Docker) until the last  update.

**Comment by goseesomething** [comment]
Is there any way to solve?
In order to open VM , i have to turn off Hyper-V
But after Hyper-V being turned off,
I am not able to open Docker.....

**Comment by irmscher9** [comment]
Guys, who still have this issue, try the following: 
1. ensure that Virtualization technology is enabled in BIOS
2. In Windows search, type "turn windows features on or off"
3. If Hyper-V is enabled (box is ticked) then disable it and restart. Then enable it again and restart once more.
3a. If Hyper-V is disabled, enable it and restart. 
4. Docker now should work properly.

In my case the Hyper-V was screwed by VirtualBox so after the re-installation it now works properly.
Hope this helps!

**Comment by qfdk** [comment]
I have the same problem. Someone solve the problem ?
@irmscher9 i tried that. still not work

**Comment by natthawatklakpetch** [comment]
> Guys, who still have this issue, try the following:
> 
> 1. ensure that Virtualization technology is enabled in BIOS
> 2. In Windows search, type "turn windows features on or off"
> 3. If Hyper-V is enabled (box is ticked) then disable it and restart. Then enable it again and restart once more.
>    3a. If Hyper-V is disabled, enable it and restart.
> 4. Docker now should work properly.
> 
> In my case the Hyper-V was screwed by VirtualBox so after the re-installation it now works properly.
> Hope this helps!

This works for me. thanks irmscher9!

**Comment by DumboJetEngine** [comment]
I have a Hyper-V Server 2019.
I have installed and configured Docker, as suggested by MS.
The docker service won't start and gives me a 1067 error code when I try to start it manually.
It seems to me that Docker does not work on Windows and when it works it is by pure chance.

**Comment by berengamble** [comment]
The fix for me was to enable virtualisation in my bios. It'll be in `Advanced > CPU Configuration > SVM` - make sure it's enabled.

**Comment by pastime28** [comment]
@berengamble same fix for me. Everything working as expected.
