### ISSUE TITLE
Docker (Edge) is unable to start

### ISSUE THREAD

**Issue by afischer211** [docker/for-win#1784]
### Expected behavior
Normal startup of Docker
### Actual behavior
Crash on startup with error-message
Ein Element mit dem gleichen Schlüssel wurde bereits hinzugefügt.
   bei Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:Zeile 36.
   bei Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:Zeile 67.
   bei Docker.Actions.<>c__DisplayClass14_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:Zeile 51.
   bei Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:Zeile 59.
### Information
- Diagnostic ID from "Diagnose & Feedback" in the menu.
6CB5FF79-CA43-4A67-B6BE-92B0E5DA3F12/2018-03-05_11-26-31

The stable version runs without problems!

- host distribution and version (Windows version, build number, etc)
Windows10 version 1709 (Build 16299.248)

### Steps to reproduce the behavior
  1. install docker (edge)
  2. try to start - crash

**Comment by afischer211** [comment]
I tried the new Docker Edge version 18.03.0-ce-rc3-win56 (16433). Also this version crashes with the same problem on startup.
The diagnostic id is: 406643DC-6044-490B-81AC-094E3A24A297/2018-03-14_08-54-22

**Comment by oemergenc** [comment]
I have the same problem, any recomendations on this?

**Comment by lupenium** [comment]
Same Issue

**Windows**

> Windows 10 Pro, 
> Version: 1709
> Build: 16299.371

**Docker**

> Version 18.03.0-ce-win59 (16762)
> Channel: stable
> d70d80d

The diagnostic id is: 
> 12875D44-9529-482B-B231-3DBAABFF7435/2018-04-23_14-26-20

**Obs**: Firewall Disabled
