### ISSUE TITLE
How to forward port to/from linux container on Windows

### ISSUE THREAD

**Issue by kasper3** [docker/for-win#1787]
I am trying to run aspnet on Alpine Linux using windows 10 host.

Here is the docker command:

```powershell
docker run -p 3000:5001 -it microsoft/dotnet:2.1-sdk-alpine
```

In Alpine container:

```ash
dotnet new mvc -n wapp && dotnet run -p wapp

# ...
# Content root path: /wapp
# Now listening on: https://localhost:5001
# Now listening on: http://localhost:5000
# Application started. Press Ctrl+C to shut down.
```

after that when I browse to localhost:3000 or localhost:5001 in host (windows) browser, it does not respond. I also tried 127.0.0.1 with those ports..

How does it work, do I need to use `--expose` instead of or in addition to `-p` option? All the tutorials I have found so far are suggesting to have a Dockerfile, run as deamon then use docker run, but how about simple / quick `docker run -it ...` command, is it a no go? I remember seeing someone running node.js server and browsing via host browser using just `docker run -p .. -it ..` in like 10 secs.

**Comment by carlfischer1** [comment]
@kasper3 what you're doing looks correct. there is an issue with port mapping in the latest Windows KB - #1707 . what Windows version is displayed in `docker info`?

**Comment by kasper3** [comment]
Thanks to @artiomchi for spotting my mistake. I had to run the server using `<protocol>://*:<port>`. It is not the bug with docker.
