### ISSUE TITLE
Can't mount a host directory if the container directory exists and contains a file

### ISSUE THREAD

**Issue by mlapierre** [docker/for-win#179]
### Expected behavior

When using Windows containers, you can mount a host directory and overlay an existing container directory.
### Actual behavior

An error occurs when trying to start the container:

> docker: Error response from daemon: container db565702e017c2680415b7cd5681a3467d8bd3c769ce7f4499de9f429927ad45 encountered an error during Start: failure in a Windows system call: The connection with the Virtual Machine hosting the container was closed. (0xc037010a).
### Information
- Diagnostic ID: BC6256BA-9317-476F-8F5A-614251D86C58/2016-10-28_14-57-00

λ docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64
### Steps to reproduce the behavior

Example Dockerfile:

```
FROM microsoft/nanoserver 

WORKDIR c:/temp
COPY a.file c:/temp/a.file
```

Build and then run:

```
docker run -v c:/temp:c:/temp foo-image cmd

docker: Error response from daemon: container 3952c075b90fb85ff79b9616626e3b7b8acc1056a33b7e7546ffa801a094976c encountered an error during Start: failure in a Windows system call: The connection with the Virtual Machine hosting the container was closed. (0xc037010a).
```

Linux containers allow mounting under this scenario. The host directory would overlay the container directory, but would not remove the pre-existing content. 

Interestingly, it's fine if there is no file in the existing container directory, e.g.:

```
FROM microsoft/nanoserver 

WORKDIR c:/temp
```

```
docker run -v c:/temp:c:/temp foo-image cmd

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\temp>
```

**Comment by dgageot** [comment]
@friism Can you confirm this limitation?

**Comment by roolebo** [comment]
I'm running Windows 10 Insider Preview 14965 and hitting the same failure in Windows system call.
```
> docker run -it -v D:\data1:C:\data1 --name db mongo:3.2-windowsservercore
docker: Error response from daemon: container 81db187de842fa259bfb4c3c6227846c2c49312a1968b03762bdca6045f5af5f encountered an error during Start: failure in a Windows system call: The connection with the Virtual Machine hosting the container was closed. (0xc037010a).
```
In my case the directory doesn't exist in the container but exists on the host. 
Diagnostic ID: E1A58DA7-5E26-4EE2-943E-56BF3D71B146/2016-12-21_21-57-08

**Comment by Jonathan34** [comment]
facing the same if the folder contains a folder... can't try without the nested folder though

**Comment by dgageot** [comment]
@mlapierre @roolebo @Jonathan34 I'm going to close this issue in favor of [this one](https://github.com/docker/docker/issues/30556) on docker/docker. This is not something that can be fixed by Docker for Windows
