### ISSUE TITLE
Unable to switch "Windows Container" on Windows 10 PC - Professional Edition

### ISSUE THREAD

**Issue by svenkatesh99** [docker/for-win#1790]
### Expected behavior

I have docker for Windows  version18.03.0-ce-rc1 installed on my Windows 10 PC.  But I am unable to switch 

### Actual behavior

Current operation failed because Windows policy "Deny write access to fixed drives not protected by Bitlocker" is enabled. Please disable it and retry the operation' I have enabled this seting Registry but still getting same error again. 

  - host distribution and version (Windows version, build number, etc)
Windows Version - Version	10.0.14393 Build 14393
docker version  version18.03.0-ce-rc1

### Steps to reproduce the behavior

  1. Go to docker and click switch to windows conatiners
  2. Gets the above error

**Comment by jasonbivins** [comment]
Hi @svenkatesh99 
That setting is most likely managed by GPO 
It does look like it's fixed in the insider preview of windows: https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/530
