### ISSUE TITLE
Docker failed to initialize can you me please ?

### ISSUE THREAD

**Issue by kenshero** [docker/for-win#1795]
when install it work. after i sleep computer and open again. i reconnect internet then error.

"The type initializer for 'Docker.Core.Paths' threw an exception."

![docker_failed](https://user-images.githubusercontent.com/8245757/37073754-7530c150-21fb-11e8-8ee8-bc6374b3399c.png)

**Comment by jasonbivins** [comment]
@kenshero  does it reconnect after a reboot?

**Comment by kenshero** [comment]
I can work it . i dont know why.I think about network.
