### ISSUE TITLE
Linux image on Docker for Windows doesn't have Internet Access

### ISSUE THREAD

**Issue by danielhalati** [docker/for-win#1796]
Hello.I have this Dockerfile

```
FROM opensuse:42.1
ADD proxy /etc/sysconfig/
ADD LLVM4_from_Mirror.repo /etc/zypp/repos.d/
RUN zypper update
```

proxy file has my Internet Proxy settings like this with data put in place

```
PROXY_ENABLED="yes"
HTTP_PROXY=""
HTTPS_PROXY=""
FTP_PROXY=""
NO_PROXY=""

```

LLVM4_from_Mirror.repo looks like this:
```
[LLVM4_from_Mirror]
name=LLVM4 from Mirror
enabled=1
autorefresh=1
baseurl=http://ftp.halifax.rwth-aachen.de/opensuse/repositories/devel:/tools:/compiler/openSUSE_Leap_42.1/
path=/
type=rpm-md
keeppackages=0
```

When I run docker build command I get the following error:

![image](https://user-images.githubusercontent.com/16553732/37076445-4ca3e99a-21df-11e8-86c0-288fe7f59cec.png)

**Comment by rn** [comment]
I don't know zypper, but on a quick look the error looks like an issue with `LLVM4_from_Mirror.repo` and not with proxy setting. It says "invalid path component" and something about not being about to contact a server or somesuch

**Comment by danielhalati** [comment]
I copied this file from a Linux VM where it works. Also I used this file inside a Linux image which runs on Docker for Linux and it works.
