### ISSUE TITLE
"how likely are you to recommend to a friend" pop up blocks docker startup

### ISSUE THREAD

**Issue by rjmoseley** [docker/for-win#1799]
### Expected behavior

After a reboot docker for windows should start up automatically and without needing human intervention.

### Actual behaviour

After a reboot a pop up appears asking how likely you are to recommend docker for windows to a friend on a scale of 1 to 10.  Docker will not start until this pop up has been dismissed.

### Information

This makes using docker for windows painfully difficult to use on a remote CI machine as whenever the box restarts docker doesn't come back up until someone has logged in via RDP and dismissed the pop up.

I have no objections to being asked the question, just that docker startup is blocked until the question has been answered.

### Steps to reproduce the behaviour

  1. Reboot machine
  2. Become frustrated

(The pop up doesn't appear every time, however I think it might be on the first reboot after a docker upgrade?)

**Comment by jasonbivins** [comment]
Hi @rjmoseley 
Thanks for reporting - we have this fixed already and it should be included with the next release

**Comment by rjmoseley** [comment]
Hi @jasonbivins 
Are you able to say which release this should be appearing in?  I've upgraded to 18.03.0-ce-win59 (16762) and am still finding myself swearing excessively at this infuriating popup that breaks all our CI machines...

**Comment by jasonbivins** [comment]
@rjmoseley 
The fix for this was included in 18.03 Edge release - can you post a diagnostic ID ? 
Right click the Whale Icon - choose Diagnose and Feedback. Then copy\paste the diagnostic ID here.

**Comment by rjmoseley** [comment]
DA5EEF1C-58E3-44F1-974E-0680B105AC2E/2018-04-11_18-30-48

I'm currently running on the stable channel.  Is that 18.03 different to 18.03 on the edge channel?

**Comment by nvindice** [comment]
Same problem here. We use docker in production environment and this is the third or fourth time our (headless) cloud server failed to start becaus of this useless popup. I hope this will get fixed ASAP.

Version was 18.03 as well, I just upgraded to 18.06.
