### ISSUE TITLE
Docker Build failing on Hosted 2017 in VSO

### ISSUE THREAD

**Issue by rupreetg** [docker/for-win#1800]
### Expected behavior
Docker build should work 

### Actual behavior
Failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage C:\ProgramData\docker\windowsfilter\b8a31b48e5d3e5a3efa781f3091c0c1f381dab639497049764df48f37b0f924c\UtilityVM: The system cannot find the path specified.

### Information
My docker file is simple enough - 

FROM microsoft/aspnetcore:2.0-nanoserver-1709 AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/aspnetcore-build:2.0-nanoserver-1709 AS build
WORKDIR /src
COPY *.sln ./
COPY AT.Api/AT.Api.csproj AT.Api/
RUN dotnet restore
COPY . .
WORKDIR /src/AT.Api
RUN dotnet build -c Release -o /app

FROM build AS publish
RUN dotnet publish -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "AT.Api.dll"]

I am using VSO hosted 2017 build for my build definition. It works fine locally, but when when I run build on VSO, it fails. I searched online but couldn't any specific reason. This doesn't seem to be anti-virus issue, how can i investigate more to understand the root cause?

**Comment by jasonbivins** [comment]
@rupreetg 
Do you know what version of Windows the VSO is hosted on?  You are specifying version 1709  in your dockerfile- and this looks like the error we get when there is a conflict with Windows server versions (14393 and 1709)

**Comment by rupreetg** [comment]
I need to check as it's a hosted agent in VSO. Which version is compatible and can we used?

**Comment by rupreetg** [comment]
Thanks, that solved the issue. Closing the issue.
