### ISSUE TITLE
Edge version - Windows container can not save linux images

### ISSUE THREAD

**Issue by kkbruce** [docker/for-win#1803]
### Expected behavior

Save .tar file from Linux images.

### Actual behavior

Show error message:

- Error response from daemon: layer does not exist

### Information

1. docker version 18.03.0-ce-rc1
2. A diagnostic was uploaded with id: 7DFB7571-7A50-491B-BE01-8DE5ACFDFBA1/2018-03-08_10-57-19

### Steps to reproduce the behavior

In Windows Container:

  1. docker pull --platform linux ubuntu
  2. docker save -o ubuntu.tar ubuntu

**Comment by jasonbivins** [comment]
@kkbruce   Are you attempting to save a linux image within a windows container? or are you trying to run a Linux container on a Windows machine?

**Comment by kkbruce** [comment]
@jasonbivins 
I want to save Linux image within Windows container.
