### ISSUE TITLE
Docker for windows crashe when switching to linux containers

### ISSUE THREAD

**Issue by hunytalk** [docker/for-win#1808]
### Expected behavior
docker for windows should be able to switch from windows container ( default start) to linux container

### Actual behavior
docker crashes with red docker icon in taskbar when switched to linux container, still windows container are working. 
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
7454D69B-045B-48AF-938D-1A01357F8166/2018-03-08_23-42-20
  - a reproducible case if this is a bug, Dockerfiles FTW
n/a
  - page URL if this is a docs issue or the name of a man page
n/a
  - host distribution and version (Windows version, build number, etc)
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:22 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.24)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:15:52 2017
  OS/Arch:      windows/amd64
  Experimental: true

windows version: 10.0.15063 build 15063
### Steps to reproduce the behavior

  1. ... start docker for windows
  2. ... switch to linux containers

i have also noticed that during switching to linux containers, my MobyLinuxVM in hyper-v manager keeps restarting after 1 mins and displays below error.

Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Failed to create the virtual hard disk.

The system failed to create 'C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx'.

Failed to create the virtual hard disk.

The system failed to create 'C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx': General access denied error (0x80070005).
at New-MobyLinuxVM, <No file>: line 223
at <ScriptBlock>, <No file>: line 409
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 181
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 130
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

I have also attached the logs file. please help to resolve this issue
[newlog.txt](https://github.com/docker/for-win/files/1794444/newlog.txt)

**Comment by abhishekmuthyam** [comment]
facing same issue ,looking for solution

**Comment by hfatgit** [comment]
Same problem here. Almost virgin Win10 Enterprise 64bit installation on new machine (i7, 1TB SSD, 32GB RAM)

**Comment by chlumper** [comment]
Possible duplicate of #2404

**Comment by marvincolgin** [comment]
/remove-lifecycle stale

Win10 Pro .. unable to switch to Linux containers.

**Comment by bradseames** [comment]
/remove-lifecycle stale
Win10 Pro .. unable to switch to Linux containers.
