### ISSUE TITLE
Docker fails to start - Docker hv-sock proxy (vsudd) is not reachable

### ISSUE THREAD

**Issue by ph4wks** [docker/for-win#1809]
### Expected behavior
Docker should start in Windows 10 Enterprise.

### Actual behavior
Fails to start with error Docker hv-sock proxy (vsudd) is not reachable. 

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu. 
B42ABCDF-7EAF-468B-816B-BF2F714AF19F2018-03-08_09-59-22

  - host distribution and version (Windows version, build number, etc)
Windows 10 Enterprise Version 1511 Build 10586.1356
Running in a VMware Fusion Virtual Machine (VT-x Enabled)

### Steps to reproduce the behavior

  1. Install Hyper-V
  2. Installed Docker https://download.docker.com/win/stable/13620/Docker for Windows Installer.exe (because the latest version of Docker will not install unless you have the very latest version of Windows. See Issue 211)
  3. Move Docker image to C:\Users\[user]\Docker (to get around needing to provide permissions to Public folder) (Note: It didn't work where it was in public anyway. Same error. Even with fill permissions and navigating to the folder to force windows to ask for access.)

Tried: 
Run as admin
Disable experimental features
I am a local admin of the machine
I'm not on a domain
I have a firewall running. I cannot disable this or open any ports. But there are no logs as a result of starting Docker in the firewall logs anyway. 
There is no proxy on my network
Also note that I cannot get the Shared Drive C to work. It asks for creds and fails to 'tick'. I believe this could be the firewall though as I've read it needs port 445 to be open (this is not a good port to open on a Windows PC. Is there any way around this?)

**Comment by david-schopf** [comment]
A3D7AB1F-B687-4295-B6DB-5AD9F890F412/2018-03-11_00-14-29
Version 18.03.0-ce-rc1-win54 (16164)

**Comment by Ageraluon** [comment]
https://github.com/docker/for-win/issues/1811

**Comment by david-schopf** [comment]
Yeah! It finally works with 18.03.0-ce-rc3-win56 (16433).

**Comment by ph4wks** [comment]
Docker for Windows requires Windows 10 Pro or Enterprise version 14393, or Windows server 2016 RTM to run.Why is Docker tied to this 14393 build? What is it that technical needs this specific build or later?
--

**Comment by rn** [comment]
@ph4wks newer Windows builds have some important fixes which have not been backported. I know of several Hyper-V related issues: potential Linux kernel crashes on Skylake processors, issues with creating network switches (for which we had very hacky workarounds), potential BSOD in some scenarios, which we used more hacky work arounds. We would also have to have special cases for Windows container support etc. etc.

For a free product, like Docker for Windows, we also don't have the resources to test and support all the old releases of Windows 10. So periodically we stop supporting older versions.

14393 is not an arbitrary build, it is the RS1/Anniversary Update release from August 2016.

I'm closing this issue as Version 1511 Build 10586 is no longer supported.
