### ISSUE TITLE
Docker hv-sock proxy (vsudd) is not reachable

### ISSUE THREAD

**Issue by mixxit** [docker/for-win#1811]
### Expected behavior

Docker should start on login

### Actual behavior

Docker hv-sock proxy (vsudd) is not reachable
   at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 293
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 260
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 130
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

### Information

  - Diagnostic ID: 0A48A31F-ABCB-48B6-9F37-2A1FAA6FCC73/2018-03-09_08-23-06
  - Dell XPS 9550, Windows 10 Pro N Version 1709 OS Build 16299.248

### Steps to reproduce the behavior

Install docker and use it fine for a week or so
Randomly one day login to windows and watch docker try to start in system tray

**Comment by filippomonti** [comment]
me too the same problem on Windows 10 Pro.

- Diagniostic ID: 7E6F59A5-3C56-4666-A3AA-50D6FA4A9A04/2018-03-09_09-34-57

**Comment by david-schopf** [comment]
+1 
A3D7AB1F-B687-4295-B6DB-5AD9F890F412/2018-03-10_15-33-16

**Comment by Ageraluon** [comment]
It seems that this error seems so be quite prevalent amongst different systems.
I experience the same error on the current stable/edge versions. However, this version:
https://download.docker.com/win/lcow/Docker%20for%20Windows%20Installer.exe
seems to work much more stable for me. 
All others having the same problem, could you try that version and report your compatibility? Even with lcow switched off, this seems to work better for me.

One aspect that might be of importance here: This version tries to connect to the MobyLinuxVM for about 1:50min before it finally succeeds. However, the current stable/edge version seem to timeout after about 1:15min already, shuts down the MobyLinuxVM, tries again and finally fails showing the error of this post. Has there recently been a timeout set more strictly? This might not be compatible with slower hosts.

**Comment by filippomonti** [comment]
With the edge version is not possible to switch to linux container. This is the error
### Docker hv-sock proxy (vsudd) is not reachable
   in Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:riga 36
   in Docker.Actions.<>c__DisplayClass28_0.<SwitchDaemon>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:riga 304
   in Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:riga 59

- Diagniostic ID: 7E6F59A5-3C56-4666-A3AA-50D6FA4A9A04/2018-03-14_08-42-50

**Comment by mixxit** [comment]
0A48A31F-ABCB-48B6-9F37-2A1FAA6FCC73/2018-03-15_10-00-09

**Comment by filippomonti** [comment]
- Created virtual machine with Oracle VMBox
- Installed Ubuntu with Docker (for linux)
- Installed portainer and wnameless/oracle-xe-11g
Now works..
Sorry

**Comment by virtualestate** [comment]
+1 Our office have a mix of high spec Dell and Lenovo notebooks, and all are about a year old. Lenovo's are fine, but all of our Dells seem to suffer from this issue. We suspect it has something to do with Dell's hibernation process.

**Comment by ashrestha** [comment]
This had been bugging me for past several hours now until I found a work around. 
My environment:
- Windows 10
- Docker -v 17.12.0-ce

Here is how (hope it benefits some one as frustrated as myself):
1) [Disable Hyper-v](http://www.poweronplatforms.com/enable-disable-hyper-v-windows-10-8/)
2) Restart the system.
3) [Get Docker Toolbox for Windows](https://docs.docker.com/toolbox/toolbox_install_windows/)
4) Run the tool box and make sure to check the "Install Virtual Box" option.
5) Run the Docker terminal.

Until an optimal solution from the docker team is here, I guess this will have to do for me.

**Comment by saidmasoud** [comment]
FWIW, I resolved this issue by reverting from Docker for Windows 18.03 to 17.12. Going to skip the 18.03 build for now.

**Comment by lmatejka** [comment]
Any proposal/solution on this from Docker team? Thank you

**Comment by rn** [comment]
I've looked at all supplied diagnostics in this issue and other "Docker hv-sock proxy (vsudd) is not reachable" and they seem to fall into three categories:

- Running Docker for Windows inside a Windows 10 VM. This is problematic as we have no visibility of your Windows VM configuration and activity on the host. Because of that we can't support this configuration. See also https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-for-windows-in-nested-virtualization-scenarios
- The Linux VM is very slow booting. Please take a look at: https://github.com/docker/for-win/issues/1995
- There was a linux kernel crash of some sort. Please take a look at: https://github.com/docker/for-win/issues/1994

If you have provided a diagnostics ID, I've added you to the relevant issue, so I'm closing this issue.
