### ISSUE TITLE
Docker does not start: Docker hv-sock proxy (vsudd) is not reachable

### ISSUE THREAD

**Issue by Ageraluon** [docker/for-win#1817]
### Actual behavior
Docker for Windows in linux container mode encounters an error during startup: Docker hv-sock proxy (vsudd) is not reachable

Docker hv-sock proxy (vsudd) is not reachable
   bei Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:Zeile 36.
   bei Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:Zeile 67.
   bei Docker.Actions.<>c__DisplayClass14_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:Zeile 51.
   bei Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:Zeile 59.

### Information
Using Docker for windows latest stable (same error on edge)

Diagnostic ID:
F00DD952-FB18-43DE-9026-B546C7B82BE3/2018-03-11_20-19-09

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Ageraluon** [comment]
The new version 18.03.0-ce-rc3-win56 (16433)
is looking very promising here. Have only run it for an hour yet. The Performance is so far excellent.

**Comment by Ageraluon** [comment]
Works stable, even over restarts.

**Comment by ph4wks** [comment]
Docker for Windows requires Windows 10 Pro or Enterprise version 14393, or Windows server 2016 RTM to run.

Why is Docker tied to this 14393 build?   What is it that technical needs this specific build or later?

**Comment by bitbayio** [comment]
I solved the problem when I removed the static IP /DNS settings from my network adapter and choose dynamic (dhcp)
