### ISSUE TITLE
Docker Edge for Windows 18.03 windows containers broken

### ISSUE THREAD

**Issue by pmayweg** [docker/for-win#1819]
### Expected behavior
When I select Windows-Container during the installation, I do not expect Hyper-V to be needed.

### Actual behavior
When the docker ui starts, it says that Hyper-V is needed. It tries to install Hyper-V, which fails. Maybe because of VMWare WS installation.
When I switch the daemon with DockerCli -SwitchDaemon (case sensitive), I can start the UI, but there is still the option to "Switch to Windows Containers". If I select that, it will say again, it needed Hyper-V.

### Information
Where do I find that.
### Steps to reproduce the behavior
Install with "enable Windows Containers" without using Hyper-V.

**Comment by ebriney** [comment]
Hi @pmayweg,
Windows containers needs Hyper-V.
Did you enable hypervisor applications in processors option on your vm?

**Comment by jasonbivins** [comment]
@pmayweg   What error did you get during the install when Hyper-V failed?  Do you have any screenshots or logs?
