### ISSUE TITLE
Docker does not start (hangs)

### ISSUE THREAD

**Issue by vvsh** [docker/for-win#182]
### Expected behavior

Docker is starting
### Actual behavior

Docker does not start (hangs)
### Information
- 53899526-67E3-4367-AA7F-CE0053B39F54/2016-10-30_19-55-27
- Windows 10 Pro (1607) 14393.351
### Steps to reproduce the behavior
1. Install latest Docker for Windows (stable or beta version)
2. Start Docker

**Comment by vvsh** [comment]
Eventually docker started, but it took a lot of time.

**Comment by rneugeba** [comment]
@vvsh thanks for your report. Unfortunately the logs in the diagnostics are truncated.

Does it start with a long delay every time or just the first time after installation. What do you mean by "a lot of time", minutes, tens of minutes, hours?

Thanks

**Comment by vvsh** [comment]
@rneugeba, please find logs [here](https://dl.dropboxusercontent.com/u/16185759/log.txt).

From the logs you can see that the start took 45 minutes, but I started it at 10.24 and in 11.20 it was in "starting" state...

**Comment by rneugeba** [comment]
Thanks for the logs, but I'd be interested in the Docker for Windows application logs. The ones added in the diagnostics are truncated. Can you quite the app, start it again and once it is up and running (whale animation stopping), go to `Diagnose & Feedback` and upload the logs.
thanks

**Comment by medelasri** [comment]
Windows 10 Pro (1607) 14393.351 (Same Version)

When I run `docker-composer up  `

```
Building db
Step 1 : FROM mysql:latest
latest: Pulling from library/mysql
```
Still running without any results...

**Comment by vvsh** [comment]
@rneugeba, 53899526-67E3-4367-AA7F-CE0053B39F54/2016-11-01_08-08-21.

**Comment by vvsh** [comment]
@rneugeba, fresh diagnostic: 53899526-67E3-4367-AA7F-CE0053B39F54/2016-11-01_11-44-10.

**Comment by dgageot** [comment]
@vvsh Can you please give a try to Docker for Windows Beta31 and tell us if it fixes the issue for you?

**Comment by rneugeba** [comment]
I had a look at the above logs, but they are also truncated. The latest Beta 32.1 has a fix in the log collection. Could you try it and provide a diagnostics Id?

**Comment by vvsh** [comment]
@rneugeba, sorry, I uninstalled Windows on that PC, so I cannot provide such information anymore. On another PC I do not have such issues having Windows 10 Enterprise version.

**Comment by rneugeba** [comment]
Thanks for getting back. I'm closing this issue as we don't have a way to debug it anymore. Glad you have a system where it works.
