### ISSUE TITLE
Docker for Windows crashes after reboot under Parallels

### ISSUE THREAD

**Issue by superstator** [docker/for-win#1824]
### Expected behavior

Safely reboot host OS and continue running Docker

### Actual behavior

Docker crashes and cannot restart 

### Information

Most recent diagnostic ID:
6C396720-E38D-4FE6-8DC0-A9087506B812/2018-03-12_15-34-00

Docker runs fine on a fresh install, and I can run containers to my hearts content. If I reboot, however, it will begin to crash repeatedly while trying to start, always with the generic "Docker hv-sock proxy (vsudd) is not reachable" error. The only reliable solution I've found is to either uninstall and reinstall completely, or use admin rights to delete the entire C:\ProgramData\Docker folder.

I am running Windows 10 1709 build 16299.248 under Parallels 13.3 (43321), and macOS 
10.12.6

### Steps to reproduce the behavior

Install Docker
Start a container
Reboot
Crash!

**Comment by superstator** [comment]
After spending another hour or two trying to narrow this down better, it seems this is a semi-known issue running Docker for Windows under Parallels (or similar nested virtualization situations). Moby fails to sync it's clock to the host, with the error "tsc: HPET/PMTIMER calibration failed". ☹️ 

I understand that this is considered an unsupported scenario, but I guess I'll make a plea anyway: I build software for both Mac and Windows. That means I have no real choice but to use a Mac, and use virtualization. If there is any way to make the clock sync more forgiving, or allow for retries, or some kind of fallback clocksource, even if it does mean starting Docker in a VM takes a little longer, it would make my life a LOT easier.

**Comment by rn** [comment]
We have some notes in the [troubleshoot section](https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-for-windows-in-nested-virtualization-scenarios)

Having the clock calibration failing is likely an issue with resource contention. 

As the troubleshoot says we can't control how you set up the VM (though we make some recommendation) nor do we have any visibility of your host so can't help users with these type of issue. Closing

**Comment by superstator** [comment]
FWIW, I see no other signs of resource contention. This happens even with everything else shut down and the machine idle, both in the guest VM and the host OS. None of my other tools have resource issues, and I am able to routinely do things like open multiple Visual Studio instances, multiple VMs, minikube, etc, with zero problem. Once Docker starts, it runs great, and I can run multiple containers and long, complex builds without any resource problems whatsoever. The only recurring issue is this apparently extremely brittle clock sync during Moby startup. 

Assuming there's nothing to be done about making the clock sync less sensitive, all it would take to vastly improve this for me would be an option to allow Docker to retry Moby startup automatically, or at least offer some UI beyond the systray icon to monitor startup.
