### ISSUE TITLE
Hypervisor slows down my machine. hope using only virtualbox?

### ISSUE THREAD

**Issue by sl5net** [docker/for-win#1828]
### Expected behavior
Hope to use without hypervisor, because everything is slow here on this machine

### Actual behavior
Error: "System does not have a hypervisor." (german: "System verfügt über keinen Hypervisor")

### Information
https://social.technet.microsoft.com/Forums/windowsserver/en-US/b3350306-c81c-4c2e-bd6b-0f784e374408/will-hyperv-slow-down-my-pc-windows-8-while-not-running?forum=winserverhyperv

I've found that Hypervisor slows everything down.  If I turn off Hyper-V, everything works fine.  
So i there a chance to use docker witout Hypervisor, only with virtualBox?

  - Diagnostic ID from "Diagnose & Feedback" in the menu:
 E5A21269-9F1A-4CB3-A811-0D7284EB1B17/2018-03-13_16-54-54

  - a reproducible case if this is a bug, Dockerfiles FTW
turned of Hypervisor, reboot machine, started docker for winows.

  - host distribution and version (Windows version, build number, etc)
Lenovo ThinkPad T540p 
Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz 2.39 GHz 16,0 GB (15,7 GB verwendbar)
64-Bit-Betriebssystem, x64-basierter Prozessor
Windows 10 Pro

is there hope to use only virtualbox? or do i need to buy a new laptop? or something else?

**Comment by rn** [comment]
Unfortunately, we rely on Hyper-V and it is also needed for Windows containers and LCOW. We have not seen significant slowdowns with enabling Hyper-V and I seem to have a couple of machines with similar spec. Changing the hypervisor is a significant engineering effort and we are not working on this, so closing the issue. Docker Toolbox uses virtual Box by default, you could try that.
