### ISSUE TITLE
How to optimize the microsoft/windowsservercore

### ISSUE THREAD

**Issue by sharathj007** [docker/for-win#1830]
I am using the below commands to create a docker base image to run my application which needs visual studio redistribute package and java JDK in windows server 2016. My concern here is by using the microsoft/windowsservercore the base image size itself 10.4 GB, by including JDK and my project dependencies in dockerfile which create an image size of 11.8 GB. 
**DO ANY ONE CAN HELP ME TO REDUCE THE SIZE OF THE BASE IMAGE OR HOW CAN I OPTIMIZE THE SIZE HERE WILL BE VERY MUCH HELPFUL.**

NOTE: I have tried creating an image using microsoft/nanoserver but which has the minimal features and didn't allow to  install the visual studio redistributable package as part the image container which is very much required to run my application.
########################################################
FROM microsoft/windowsservercore

# COPY THE INSTALLATION FILES INTO THE CONTAINER
ADD ./source c:/source

# INSTALLING VC++ REDISTRIBUTABLE PACKAGE
![untitled](https://user-images.githubusercontent.com/34763508/37386567-0f6acd82-277f-11e8-92c1-a53e7f23d309.jpg)

RUN C:\source\vc_redist.x64.exe /quiet /install

RUN powershell.exe -command \

# INSTALLING JAVA JDK
./source/jdk.cmd; \

# SETTING UP ENVIRONMENT PATH VARIABLES FOR JDK FOLDER
./source/Environmentvariable.ps1; \
##########################################################

**Comment by rn** [comment]
Thanks for reporting. But this issue is not specific to the Docker for Windows application so I'm closing this issue.

You could try raising an issue on https://github.com/moby/moby/issues where more of the Microsoft developers and PMs hang out.
