### ISSUE TITLE
Docker failed to initialize

### ISSUE THREAD

**Issue by sasiarivukalanjiam** [docker/for-win#1836]
### Expected behavior
Docker for windows to be available and the icon to be showed on system tray.
### Actual behavior
Could not load type 'Docker.Win32Helpers.Membership' from assembly 'Docker.Win32Helpers, Version=1.0.6227.33162, Culture=neutral, PublicKeyToken=null'.

![image](https://user-images.githubusercontent.com/34734743/37469268-e9ff3b2a-288a-11e8-8a80-a7ac67049721.png)

### Information
Client:
 Version:       18.03.0-ce-rc1
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    c160c73
 Built: Thu Feb 22 02:34:04 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce-rc1
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.4
  Git commit:   c160c73
  Built:        Thu Feb 22 02:41:20 2018
  OS/Arch:      windows/amd64
  Experimental: true

### Steps to reproduce the behavior
Install docker for windows works fine without restart 
one restarting the windows machine.
Double click docker for windows and the dialog box with the error appears.
executed on windows 10 Enterprise edition version 1703 build 15063.909

**Comment by Letoh01** [comment]
Reverted to previous stable 17.12.0-ce-win47 2018-01-12
vpnkit.exe memory leak and "Could not load type 'Docker.Win32Helpers.Membership' from assembly 'Docker.Win32Helpers, Version=1.0.6227.33162, Culture=neutral, PublicKeyToken=null" error no longer present. Will wait for next edge version release and try again.
