### ISSUE TITLE
Container Stats API Returns Empty 'System_CPU_Usage'

### ISSUE THREAD

**Issue by Vacant0mens** [docker/for-win#1837]
### Expected behavior

Some kind of number listed under `system_cpu_usage` when querying `/containers/{id}/stats?stream=false`

### Actual behavior

The `system_cpu_usage` json node doesn't show up with the response. This makes calculating actual CPU usage next to impossible.

### Information

I'm using 5 nodes (running 17.06.2, API version 1.30) and querying the API with python.

I believe, according to the first response in [this](https://github.com/moby/moby/issues/29306) issue, the code [here](https://github.com/moby/moby/blob/801230ce315ef51425da53cc5712eb6063deee95/api/types/stats.go#L164) says it omits empty json nodes. 

So why is it coming up empty?

Sample response from server at URL: `/containers/{id}/stats?stream=false`:
```
{
----- snip -----
    "cpu_stats": {
      "cpu_usage": {
        "total_usage": 161718750,
        "usage_in_kernelmode": 82968750,
        "usage_in_usermode": 82968750,
        "cpu_percent": 0
      },
      "throttling_data": {
        "periods": 0,
        "throttled_periods": 0,
        "throttled_time": 0
      }
    },
----- snip -----
}
```

**Comment by rn** [comment]
Please provide details of your host os and full docker for windows version information
Thanks
