### ISSUE TITLE
Where is the storage location of the files that we code using ipnb?

### ISSUE THREAD

**Issue by numunir** [docker/for-win#184]
I am actually working on Tensor Flow and install docker to Tensor flow on Windows. Now, I have made some codes using tensor flow but I am unable to locate them on my hard disk.

Please guide me that how can I locate my files on PC?

**Comment by cons0l3** [comment]
@numunir what Docker image did you use to start your Tensorflow container? `> docker run -it --rm {DOCKER_IMAGE_TAG}`? What operating system is your host? What version of `> docker version` and `> docker info` are you running?

I am using [Install Instructions](https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#docker-installation), [Dockerfile](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/Dockerfile)

I start my container with `docker run -it -p 8888:8888 gcr.io/tensorflow/tensorflow`

This container has the directory /notebooks inside it. But does not expose it as volume to the outside. You would need to write your own Dockerfile with the a volume statement based on the Tensorflow Dockerfile.

Are your running on the [NVIDIA-Docker](https://github.com/NVIDIA/nvidia-docker)? It is a specialized dorcker fork only for linux host systems

**Comment by dgageot** [comment]
@numunir I'm afraid this is not a Docker for Windows specific issue. It's more a general Tensor Flow  or docker usage question, so I'm going to close the ticket.
