### ISSUE TITLE
Can't Mount Volumes/Directories At All when Running Windows Containers

### ISSUE THREAD

**Issue by binal-patel-medamerica** [docker/for-win#1840]
### Expected behavior
I should be able to mount volumes, or bind local paths to the container when starting up Windows containers.

### Actual behavior
I can start Windows containers without any persistent storage, but any attempts to add persistent storage causes a stack exception.

### Information
Diagnostic ID: 9B9BF21B-DF78-4976-9200-96DBA61BCCF1/2018-03-15_16-09-40
[log.txt](https://github.com/docker/for-win/files/1816946/log.txt)

Exception:

`PS C:\Users\PatelB2> docker run -e SERVER_URL="http://localhost:8111" --mount source=test,target=C:/BuildAgent/conf jetbrains/teamcity-agent:latest-nanoserver
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container 8d22e9f1923631c8287094c1ec72f061be9138032510e422dbeff3a8f9914828 encountered an error during CreateContainer: failure in a Windows system call: The request is not supported. (0x32) extra info: {"SystemType":"Container","Name":"8d22e9f1923631c8287094c1ec72f061be9138032510e422dbeff3a8f9914828","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\8d22e9f1923631c8287094c1ec72f061be9138032510e422dbeff3a8f9914828","Layers":[{"ID":"8da4fd04-f369-5440-a218-87785d2290f0","Path":"C:\\ProgramData\\Docker\\windowsfilter\\dc644fb816a57e65804903d0e6154fafb8474e0ef1eeeef0548280cffc2faa1d"},{"ID":"3a344459-af60-5a93-ad7c-517d0036d05d","Path":"C:\\ProgramData\\Docker\\windowsfilter\\6f9354f8db9629c2ca16f2cedc31c535309a8621655f8b42dba62c82028e6626"},{"ID":"9b9cc998-54b7-548b-ae91-62ec94471a27","Path":"C:\\ProgramData\\Docker\\windowsfilter\\c359d0689aa3f9e17f4c7ccc953122d24c3f65668fd97d31b3e03adf0651fb18"},{"ID":"092f04f2-a2ab-59a8-b7b6-92e948579f90","Path":"C:\\ProgramData\\Docker\\windowsfilter\\917aa5998b6d42a33d1e1bc15802dd52d103f07436ec846dac380f02182b15f5"},{"ID":"6a65b3dd-1c75-57ee-8f7a-344dc47bd8e8","Path":"C:\\ProgramData\\Docker\\windowsfilter\\88591afc7579e20fd8ff717374d6e62d1c474abc8cfae3f776c485e75e4c19ab"},{"ID":"2b81db18-058b-5e92-8c41-94491bdad050","Path":"C:\\ProgramData\\Docker\\windowsfilter\\5c30e6f414ad1f300fbbafd5772e837d8b4805636e77725f117210641088b2c1"},{"ID":"4f0b3550-5529-51ba-8d36-388dc42d9b92","Path":"C:\\ProgramData\\Docker\\windowsfilter\\eca627ca35f9aaf6909747b8f41692df9493d7a8a411922e02417e5fc3635738"},{"ID":"f25a6fff-eb02-5ac8-9794-63e8c3d9ccb4","Path":"C:\\ProgramData\\Docker\\windowsfilter\\dbfdbea586b7a8f2c0dfdabf61ad2798b308a51ed89d000c8c3bb4fbe85933ac"},{"ID":"f128f651-1f33-56d0-9a0f-e9ab42bbde4d","Path":"C:\\ProgramData\\Docker\\windowsfilter\\6fa565c1dc03718e7abb108a391ca9a45f6636e72b5ec78c756d8810727e2a36"},{"ID":"9eb625df-02b3-55bf-849b-0ee7a48e2c53","Path":"C:\\ProgramData\\Docker\\windowsfilter\\53b67bea7c10888f936eb49c227f6050b32fa1c55e881e1ab57febad327ee0e5"},{"ID":"3fa59b42-cd0f-54b7-aea2-8c8565d75e69","Path":"C:\\ProgramData\\Docker\\windowsfilter\\a93a4d74f37b1fc7f332a8eed7e194c7e900d58d4c4ad6a0c8377cf200e71601"},{"ID":"3a2e12d9-b385-5f70-9955-faf4a41f4e87","Path":"C:\\ProgramData\\Docker\\windowsfilter\\555c16973de240289f20e0b909480bf8a6cc4afb784c9796b9666ef8a81c0866"},{"ID":"64ec2c50-a7b9-5c3f-8522-b7c56eb96321","Path":"C:\\ProgramData\\Docker\\windowsfilter\\e025b1c0da4811a9590a4c859fcc2efa5762f527c4f60d46780d3e9c9570aba8"},{"ID":"73153821-cd1d-53e3-955e-3960c650c014","Path":"C:\\ProgramData\\Docker\\windowsfilter\\bb5e4a9e098edf8baa01f748263b6396bce883f804b0a02106223cb0d63b15c1"},{"ID":"a53b2db3-1377-55dd-aed2-01f6cc22ff02","Path":"C:\\ProgramData\\Docker\\windowsfilter\\2e78928b715d194b80c2db3aa237d508c99628528c69fa05f970b9c423e286c7"},{"ID":"e54701f6-a647-5d42-9c3e-75ebd0ff2042","Path":"C:\\ProgramData\\Docker\\windowsfilter\\4992c548435baeb28584d31b55803467c051269245de797a2a7a0361e7bfb59a"},{"ID":"f24fb3c2-4858-53b3-bbb9-9e450f06ae12","Path":"C:\\ProgramData\\Docker\\windowsfilter\\6315b867d7be364645cafce57eb5d24c6ece829e42e67961c9a0b98b7c488499"},{"ID":"68f0bb0c-d706-5446-8e46-5552cfffaed8","Path":"C:\\ProgramData\\Docker\\windowsfilter\\4f162b508e738f79430d6482dfabbf1bed5a19e9a2e9f467ee700bff5c4f057a"},{"ID":"3e4dff72-842d-5282-a85f-717b877aa1cd","Path":"C:\\ProgramData\\Docker\\windowsfilter\\3ba0214a3934c3efe9603638d60f65a984c9e7f1ed241fbfb65de5be43b49814"}],"HostName":"8d22e9f19236","MappedDirectories":[{"HostPath":"C:\\ProgramData\\Docker\\volumes\\test\\_data","ContainerPath":"C:\\BuildAgent\\conf","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"C:\\ProgramData\\Docker\\volumes\\0985e21ecbd237b4718a4d1af81fbd2fcbc29ed42de8c949d8afeb805e0b0fd9\\_data","ContainerPath":"c:\\buildagent\\conf","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}],"HvPartition":true,"EndpointList":["1c60c857-dcf2-4057-ac27-696061dc4614"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\4f162b508e738f79430d6482dfabbf1bed5a19e9a2e9f467ee700bff5c4f057a\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}.`

Occurs on both Stable and Edge.

**Comment by gtardif** [comment]
Hi, you're trying to put paths with spaces in them, and these paths are not enclosed in double quotes. `jetbrains/teamcity-agent` is separated from the previous part of the path and interpreted as an image name !. 
You need to Enclose your paths with double quotes if they contain spaces

**Comment by gtardif** [comment]
Sorry, I misread logs... reopening

**Comment by gtardif** [comment]
It seems that `source` is used instead of `target`and vice-versa. `source` should be `C:/BuildAgent/conf`, not target

**Comment by ebriney** [comment]
```
docker run --mount type=bind,source="src",target=C:/app --rm microsoft/nanoserver powershell.exe -Command "Get-ChildItem C:\app"
C:\Users\ebriney\go\src\github.com\docker\pinata\win\src\Resources\bin\docker.exe: Error response from daemon: invalid mount config for type "bind": invalid mount path: 'src' mount path must be absolute.
See 'C:\Users\ebriney\go\src\github.com\docker\pinata\win\src\Resources\bin\docker.exe run --help'.
```

**Comment by ebriney** [comment]
you must use absolute path for source

**Comment by ebriney** [comment]
for target as well

**Comment by binal-patel-medamerica** [comment]
Sorry gentlemen - I should have provided more detail.

Using docker volume create I created a named volume test, and was trying to use that named volume as the source, and the Windows path on the container as the destination.

Interestingly - this fails:

$ docker run -e SERVER_URL="http://localhost:8111" --mount source=test,target=C:/BuildAgent/conf jetbrains/teamcity-agent:latest-nanoserver
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container 0d8088e14a934f1518c8a3f4fda9315de5ce81c595b633801fb123dacb5f303a encountered an error during CreateContainer: failure in a Windows system call: The request is not supported. (0x32) extra info: {"SystemType":"Container","Name":"0d8088e14a934f1518c8a3f4fda9315de5ce81c595b633801fb123dacb5f303a","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\0d8088e14a934f1518c8a3f4fda9315de5ce81c595b633801fb123dacb5f303a","Layers":[{"ID":"8da4fd04-f369-5440-a218-87785d2290f0","Path":"C:\\ProgramData\\Docker\\windowsfilter\\dc644fb816a57e65804903d0e6154fafb8474e0ef1eeeef0548280cffc2faa1d"},{"ID":"3a344459-af60-5a93-ad7c-517d0036d05d","Path":"C:\\ProgramData\\Docker\\windowsfilter\\6f9354f8db9629c2ca16f2cedc31c535309a8621655f8b42dba62c82028e6626"},{"ID":"9b9cc998-54b7-548b-ae91-62ec94471a27","Path":"C:\\ProgramData\\Docker\\windowsfilter\\c359d0689aa3f9e17f4c7ccc953122d24c3f65668fd97d31b3e03adf0651fb18"},{"ID":"092f04f2-a2ab-59a8-b7b6-92e948579f90","Path":"C:\\ProgramData\\Docker\\windowsfilter\\917aa5998b6d42a33d1e1bc15802dd52d103f07436ec846dac380f02182b15f5"},{"ID":"6a65b3dd-1c75-57ee-8f7a-344dc47bd8e8","Path":"C:\\ProgramData\\Docker\\windowsfilter\\88591afc7579e20fd8ff717374d6e62d1c474abc8cfae3f776c485e75e4c19ab"},{"ID":"2b81db18-058b-5e92-8c41-94491bdad050","Path":"C:\\ProgramData\\Docker\\windowsfilter\\5c30e6f414ad1f300fbbafd5772e837d8b4805636e77725f117210641088b2c1"},{"ID":"4f0b3550-5529-51ba-8d36-388dc42d9b92","Path":"C:\\ProgramData\\Docker\\windowsfilter\\eca627ca35f9aaf6909747b8f41692df9493d7a8a411922e02417e5fc3635738"},{"ID":"f25a6fff-eb02-5ac8-9794-63e8c3d9ccb4","Path":"C:\\ProgramData\\Docker\\windowsfilter\\dbfdbea586b7a8f2c0dfdabf61ad2798b308a51ed89d000c8c3bb4fbe85933ac"},{"ID":"f128f651-1f33-56d0-9a0f-e9ab42bbde4d","Path":"C:\\ProgramData\\Docker\\windowsfilter\\6fa565c1dc03718e7abb108a391ca9a45f6636e72b5ec78c756d8810727e2a36"},{"ID":"9eb625df-02b3-55bf-849b-0ee7a48e2c53","Path":"C:\\ProgramData\\Docker\\windowsfilter\\53b67bea7c10888f936eb49c227f6050b32fa1c55e881e1ab57febad327ee0e5"},{"ID":"3fa59b42-cd0f-54b7-aea2-8c8565d75e69","Path":"C:\\ProgramData\\Docker\\windowsfilter\\a93a4d74f37b1fc7f332a8eed7e194c7e900d58d4c4ad6a0c8377cf200e71601"},{"ID":"3a2e12d9-b385-5f70-9955-faf4a41f4e87","Path":"C:\\ProgramData\\Docker\\windowsfilter\\555c16973de240289f20e0b909480bf8a6cc4afb784c9796b9666ef8a81c0866"},{"ID":"64ec2c50-a7b9-5c3f-8522-b7c56eb96321","Path":"C:\\ProgramData\\Docker\\windowsfilter\\e025b1c0da4811a9590a4c859fcc2efa5762f527c4f60d46780d3e9c9570aba8"},{"ID":"73153821-cd1d-53e3-955e-3960c650c014","Path":"C:\\ProgramData\\Docker\\windowsfilter\\bb5e4a9e098edf8baa01f748263b6396bce883f804b0a02106223cb0d63b15c1"},{"ID":"a53b2db3-1377-55dd-aed2-01f6cc22ff02","Path":"C:\\ProgramData\\Docker\\windowsfilter\\2e78928b715d194b80c2db3aa237d508c99628528c69fa05f970b9c423e286c7"},{"ID":"e54701f6-a647-5d42-9c3e-75ebd0ff2042","Path":"C:\\ProgramData\\Docker\\windowsfilter\\4992c548435baeb28584d31b55803467c051269245de797a2a7a0361e7bfb59a"},{"ID":"f24fb3c2-4858-53b3-bbb9-9e450f06ae12","Path":"C:\\ProgramData\\Docker\\windowsfilter\\6315b867d7be364645cafce57eb5d24c6ece829e42e67961c9a0b98b7c488499"},{"ID":"68f0bb0c-d706-5446-8e46-5552cfffaed8","Path":"C:\\ProgramData\\Docker\\windowsfilter\\4f162b508e738f79430d6482dfabbf1bed5a19e9a2e9f467ee700bff5c4f057a"},{"ID":"3e4dff72-842d-5282-a85f-717b877aa1cd","Path":"C:\\ProgramData\\Docker\\windowsfilter\\3ba0214a3934c3efe9603638d60f65a984c9e7f1ed241fbfb65de5be43b49814"}],"HostName":"0d8088e14a93","MappedDirectories":[{"HostPath":"C:\\ProgramData\\Docker\\volumes\\test\\_data","ContainerPath":"C:\\BuildAgent\\conf","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"C:\\ProgramData\\Docker\\volumes\\f98dd3e265bd063b3015021bcf24387e8f00497826001ec995d07cfbcb286cbb\\_data","ContainerPath":"c:\\buildagent\\conf","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}],"HvPartition":true,"EndpointList":["c06a45d0-fe7d-4d26-8928-2c221e1ec6ff"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\4f162b508e738f79430d6482dfabbf1bed5a19e9a2e9f467ee700bff5c4f057a\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}.

But this works:

$ docker run -e SERVER_URL="http://localhost:8111" -v test:C:/BuildAgent/conf jetbrains/teamcity-agent:latest-nanoserver

Per the documentation here: https://docs.docker.com/storage/volumes/#differences-between--v-and---mount-behavior they should have the same behavior.

**Comment by ebriney** [comment]
Yes, sorry!

**Comment by ebriney** [comment]
using nanoserver it is working

**Comment by ebriney** [comment]
ok, got the same with `jetbrains/teamcity-agent:latest-nanoserver-1709`

**Comment by ebriney** [comment]
what you can do is to fill an issue on `moby/moby` because it concerns windows daemon and the path seems to be correct from
```
{"ID":"3e4dff72-842d-5282-a85f-717b877aa1cd","Path":"C:\ProgramData\Docker\windowsfilter\3ba0214a3934c3efe9603638d60f65a984c9e7f1ed241fbfb65de5be43b49814"}],"HostName":"0d8088e14a93","MappedDirectories":[{"HostPath":"C:\ProgramData\Docker\volumes\test\_data","ContainerPath":"C:\BuildAgent\conf","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},
```
