### ISSUE TITLE
Unable to connect MobyLinuxVm

### ISSUE THREAD

**Issue by sudipto92** [docker/for-win#1841]
### Actual behavior
 It needs to connect and i should able to login VM

### Steps to reproduce the behavior

  1. Open Hyper-V Manager
  2. Right Click on MobyLinuxVM and then click Connect

**Comment by jasonbivins** [comment]
Hi @sudipto92    We actually disable most of the integration services for the MobyLinuxVM - you shouldn't be able to connect to it by design.
What were you trying to accomplish?

**Comment by sudipto92** [comment]
I want to start daemon in mobylinuxvm which will connect with portainer

**Comment by pgayvallet** [comment]
You can enter the VM via `docker run -it --privileged --pid=host justincormack/nsenter1 /bin/sh`

**Comment by rn** [comment]
Closing as this is by design and a workaround was suggested.

**Comment by sudipto92** [comment]
@pgayvallet is it will connect with MobyLinuxVm??

**Comment by rustyx** [comment]
@jasonbivins how do you disable it? (just curious)
