### ISSUE TITLE
Kubernetes cluster don't start properly

### ISSUE THREAD

**Issue by vincentditlevinz** [docker/for-win#1845]
### Expected behavior
A working kubernetes cluster 

### Actual behavior
kubernetes cluster appears to be started (green flag in docker settings) however, it doesn't work properly. For instance, "kubectl version" fails with the following message:

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"windows/amd64"}
Error from server (NotFound): the server could not find the requested resource

In docker's logs one can see errors like the following
12:06:53.975][VpnKit         ][Error  ] vpnkit.exe: Hvsock.read: Une connexion établie a été abandonnée par un logiciel de votre ordinateur hôte.
[12:06:53.976][ApiProxy       ][Info   ] time="2018-03-16T12:06:53+01:00" msg="Node status error: Get https://localhost:6445/api/v1/nodes: EOF"
[12:06:54.978][ApiProxy       ][Info   ] time="2018-03-16T12:06:54+01:00" msg="Node status error: Get https://localhost:6445/api/v1/nodes: EOF"

and finally messages indicating that the cluster is probably not started properly:

"Discarded service kube-dns: Unknown service type ClusterIP"
"Discarded service kubernetes: Unknown service type ClusterIP"
"Discarded service compose-api: Unknown service type ClusterIP"

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
E7734192-92D7-4CEC-818D-6EFF43A60066/2018-03-16_13-41-53
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)
Windows 10, Hyper-V, Home connection to internet (means no corporate proxy)
  - Useful information
Docker itself works correctly (ex: "docker run -p 8080:80 nginx" works as expected)
### Steps to reproduce the behavior

  1. Install Docker for windows edge 18.03.0-ce-rc4-win57 (16511)
  2. Switch to Linux containers
  3. Enable kubernetes

**Comment by khs1994** [comment]
Me,too

**Comment by vincentditlevinz** [comment]
As an alternative I've installed Minikube for windows and I manage to start a kubernetes cluster correctly with this version of docker (18.03.0-ce-rc4-win57 (16511)).

**Comment by vincentditlevinz** [comment]
I apologize. This is related to the fact that I was executing "kubectl version" with a powershell console open as admin and not the current user.
