### ISSUE TITLE
The operation timed out because a response was not received from the Virtual Machine hosting the container

### ISSUE THREAD

**Issue by danleydmello** [docker/for-win#1846]
I am trying to build docker image  using microsoft/iis by following steps decribed on https://hub.docker.com/r/microsoft/iis/. and getting this error:

PS D:\docker\iis> docker build -t iis-site .
Sending build context to Docker daemon  2.048kB
Step 1/5 : FROM microsoft/iis
 ---> 6d91070fab75
Step 2/5 : RUN mkdir C:\site
 **---> Running in 38f29bfe9e35
**container 38f29bfe9e35ad7bf534e66e0020e0b2f0caa87e51be958b48c6029f2b0e1803 encountered an error during Start: failure in
 a Windows system call: The operation timed out because a response was not received from the Virtual Machine hosting the
 Container. (0xc0370109)****
PS D:\docker\iis>

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
048585C3-B42F-4EE8-8E03-347399801267/2018-03-16_10-52-55

  - a reproducible case if this is a bug, Dockerfiles FTW
 Dockerfile:
      #Use IIS from microsoft docker registry
      FROM microsoft/iis
      RUN mkdir C:\site
     RUN powershell -NoProfile -Command \
            Import-module IISAdministration; \
            New-IISSite -Name "Site" -PhysicalPath C:\site -BindingInformation "*:8000:"

      EXPOSE 8000

     ADD content/ /site

  - host distribution and version (Windows version, build number, etc)
   Windows 10 Enterprise
 Docker Version 18.03.0-ce-rc4-win57 (16511)
Channel: edge

**Comment by jasonbivins** [comment]
Are you able to run any docker containers?  what do you get when you run `docker run hello-world:nanoserver`

**Comment by danleydmello** [comment]
Actually, I am new to docker and just yesterday installed docker and ran the hello-world image successfully. 
PS D:\docker\iis> docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (windows-amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

**Comment by rn** [comment]
Thanks for the report. This look like an issue with Windows containers not specifically to Docker for Windows (the app) so I'm closing this. Could you file an issue on https://github.com/moby/moby which is a more appropriate place for this type of issues.
Thanks

**Comment by danleydmello** [comment]
Thanks @thaJeztah , should this issue be reopened here again ?
