### ISSUE TITLE
Kubernetes: Apply leads to tls error

### ISSUE THREAD

**Issue by jonsalvas** [docker/for-win#1847]
### Expected behavior
Kubernetes deploys kubernetes-dashboard successfully with 
 kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/alternative/kubernetes-dashboard.yaml
### Actual behavior
Unable to connect to the server: remote error: tls: access denied
### Information
Windows 10.0.16299 Build 16299
Diagnostic ID: 0431763D-0EF8-422A-AA7A-6AE109E40259/2018-03-16_16-45-58

### Steps to reproduce the behavior

  1. Install Docker-For-Win Version 18.03.0-ce-rc4-win57 (16511)
  2. Enable Kubernetes and wait Kubernetes to be installed and green.
  3. Do a kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/alternative/kubernetes-dashboard.yaml

**Comment by pgayvallet** [comment]
Hello,

Without a proper diagnostic, there isn't much we can do.

Please perform and upload a diagnostic just after your reproduction scenario and give the diag id.

Thanks.
