### ISSUE TITLE
swarm init success but can not connect on port 2377

### ISSUE THREAD

**Issue by andarly** [docker/for-win#1849]
**Description**

swarm-mode preformance is not normal in docker for window(pc)
**Steps to reproduce the issue:**
1.exec `docker swarm init`  .then it show the manager ip "192.168.65.3:2377",but i can not see the ip through `ipconfig`
2.leave the swarm and  exec `docker swarm init --advertise-addr pc-ip:2377` .no exception,but i can not join the swarm from another docker machin,and i can not connect to my pc through `telnet pc-ip:2377`

**Describe the results you received:**
i can not connect the swarm in my pc through  port 2377
**Describe the results you expected:**
 init a swarm cluster normally,then join some node to it.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:22 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:29 2017
  OS/Arch:      linux/amd64
  Experimental: true
```

**Output of `docker info`:**

```
Containers: 29
 Running: 0
 Paused: 0
 Stopped: 29
Images: 42
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 2pojd3ufnyebrrg8k1mm4zg4q
 Is Manager: true
 ClusterID: k570ud1nl6wwszcchlj1c0m3r
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.65.3
 Manager Addresses:
  192.168.65.3:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155d006f53
ID: VALU:XV7T:273K:ZHDN:5PC3:HNEY:YRJR:4V7A:XE7N:CAYZ:DHOV:6NQV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 34
 Goroutines: 146
 System Time: 2018-03-16T14:54:43.6372366Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Comment by boogermann** [comment]
I'm running into the same problem. I have no idea where the 192.168.65.xxx is coming from, even from the same pc you can't ping the address.
It won't join a swarm as a manager either, I have another pc running ubuntu and I can start on it, but when I try to add the windows version as a manager to the swarm (it join as a worker just fine) I get the following error:
```
Error response from daemon: manager stopped: can't initialize raft node: rpc error: code = Unknown desc = could not connect to prospective new cluster member using its advertised address: rpc error: code = Unavailable desc = grpc: the connection is unavailable
```

**Comment by lluck42** [comment]
i have the same problem. win10 driver hyperv.
if change to window container，It's work.
now. I plan to use docker-machine ssh to work, before i can fix the problem

**Comment by shairozan** [comment]
Still definitely an issue. You can enable swarm mode on Docker for Windows, but it doesn't actually listen for the traffic. my bets are it's either in the NAT configuration (Which I'm still trying to find in HyperV) or firewall within Moby

**Comment by ShlomoAbraham** [comment]
This is still an issue for me. Anybody figure out a workaround?

**Comment by tirelibirefe** [comment]
I've the same problem. I couldn't understand how they can close the issue.

**Comment by lluck42** [comment]
I turn to minikube ， https://github.com/AliyunContainerService/minikube kube is butter

At 2019-03-20 20:09:25, "tirelibirefe" <notifications@github.com> wrote:


I've the same problem. I couldn't understand how they can close the issue.

**Comment by akhudairy** [comment]
I have the same problem on windows 10 using docker desktop. I enable the swarm mode and get a success message, but then I am not able to connect. When i check using command "netstat -an" I don't see the port open.

**Comment by parkerpatriot** [comment]
I have the same problem. I'm running on macOS Mojave.

**Comment by kspierson** [comment]
Also experiencing this exact issue on Windows 10. Anyone find any solution? It doesn't seem like the machine is listening on 2377 after initializing the swarm, and cannot figure out why.

**Comment by erenatas** [comment]
> I have the same problem on windows 10 using docker desktop. I enable the swarm mode and get a success message, but then I am not able to connect other workers (connection refused). When i check using command "netstat -an" I don't see the port open.

I am using Centos 7 and I don't see the port as well. it gives `:2377: connect: no route to host` error.

**Comment by LionelBergen** [comment]
Same issue here. I can connect docker-machine together in a swarm, but not my host (windows 10) physical machine.

I can also do a swarm init on my windows 10 machine, but then trying to join on docker-machines fail

**Comment by sisigawir** [comment]
I have the same issue running on macOS as worker and Centos 7 as manager.
This issue definitely still open.

**Comment by ac3d912** [comment]
@LionelBergen I got it working the same way you did (worker, upgrade to manager); however, when I then try to update the node (e.g. add a node label) it fails again:

`Error: manager stopped: can't initialize raft node: rpc error: code = Unknown desc = could not connect to prospective new cluster member using its advertised address: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: read tcp x.x.x.x:46796->y.y.y.y:2377: read: connection reset by peer"`

Where x.x.x.x is another manager node and y.y.y.y is my Windows host IP, so the other nodes on my network can route to it. In my case, I've setup docker-desktop with WSL2 integration in to Ubuntu, and I've setup 'netsh portproxy' from my Windows host to Ubuntu WSL2.  I am able to ssh from anywhere in to the Ubuntu host just fine.


```
PS C:\WINDOWS\system32> netsh interface portproxy show all
Address         Port        Address         Port
--------------- ----------  --------------- ----------
*               2375        172.24.61.82    2375
*               443         172.24.61.82    443
*               2376        172.24.61.82    2376
*               2377        172.24.61.82    2377
*               7946        172.24.61.82    7946
*               4789        172.24.61.82    4789
*               22          172.24.61.82    22

user@ubuntu:/$ ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.24.61.82  netmask 255.255.240.0  broadcast 172.24.63.255
        inet6 fe80::215:5dff:fea4:b961  prefixlen 64  scopeid 0x20<link
```

Of course, in the Ubuntu shell I get nothing out of netstat or sockstat.  In Windows, I don't see anything listening on 2377 (before I added the portproxy) or any other docker port.

So.  What is actually (should be) listening on port 2377??  The Windows host?  The WSL2 host?  I'm missing something here.

**Comment by senyor** [comment]
Have the same issue. After init swarm on clean Docker for Windows machine, no port 2377 is opened for listening.

**Comment by erenatas** [comment]
I have found a workaround. I have learned how to use Kubernetes and written my Helm Chart.

**Comment by senyor** [comment]
I have tried to debug and see log files. There it shows address 192.168.65.3 is associated with vm.internal hostname along with other hostnames. I also have Windows insider preview with WSL2 installed. Eventually created my own VMs with Hyper-V with swarm cluster. As nothing else worked, installed a Docker Toolbox and connected to swarm manager by http to port 2375, opened by passing -H parameter to dockerd.

**Comment by sisigawir** [comment]
Actually this is something that already clear on the document. 

> Currently, you cannot use Docker Desktop for Mac or Docker Desktop for Windows alone to test a multi-node swarm
[See this link](https://docs.docker.com/engine/swarm/swarm-tutorial/#use-docker-desktop-for-mac-or-docker-desktop-for-windows)

Another fact is that docker daemon is not installed on the windows/mac natively. It is installed under Hyper-V (a virtual machine) which has own subnet (probably you will get 192.168.65.3 ip address even if your PC use another subnet). This causes other machines cannot access the swarm master installed on windows/mac

**Comment by ac3d912** [comment]
> Actually this is something that already clear on the document.
> 
> > Currently, you cannot use Docker Desktop for Mac or Docker Desktop for Windows alone to test a multi-node swarm
> > [See this link](https://docs.docker.com/engine/swarm/swarm-tutorial/#use-docker-desktop-for-mac-or-docker-desktop-for-windows)
> 
> Another fact is that docker daemon is not installed on the windows/mac natively. It is installed under Hyper-V (a virtual machine) which has own subnet (probably you will get 192.168.65.3 ip address even if your PC use another subnet). This causes other machines cannot access the swarm master installed on windows/mac

I was hoping that was out of date for WSL2. I knew it was broken for the old Docker Desktop; just thought it was fixed/implemented with WSL2, but maybe not.

I realize the docker engine is running on a VM "behind" the host IP, which is why I was setting up portproxy port forwards, but not even it is listening on port 2377.

**Comment by lluck42** [comment]
@ac3d912 
虚拟机只能指定 subnet 而不是某个 ip，
ip 需要虚拟机中的系统来指定
（hyper-v虚拟机是可以设置固定ip的 https://blog.csdn.net/taurus_7c/article/details/101462983）

**Comment by STaRDoGG** [comment]
Hey all,

I'm just now wrasslin with this myself; am I clear in my understanding so far that docker swarm is unusable as of right now with docker desktop (windows?)

I just want confirmation before I continue fighting with it.

**Comment by ac3d912** [comment]
@STaRDoGG as far as I've gotten, it is unusable as a Master node. See #5336 where I opened a new bug. As a worker node it seems to work fine.
