### ISSUE TITLE
Run in interactive mode is all right but fail when I launch in daemon mode

### ISSUE THREAD

**Issue by sginer** [docker/for-win#1850]
I create a docker image with the following Dockerfile with the command

```shell
docker build -t zookeeper:1 .
```

```
FROM anapsix/alpine-java:8_jdk as BUILD

ADD http://mirror.ibcp.fr/pub/apache/zookeeper/zookeeper-3.4.11/zookeeper-3.4.11.tar.gz /tmp/sginer/
WORKDIR /tmp/sginer
RUN tar xzf *.gz && rm -f *.gz && mv zookeeper* zookeeper

FROM anapsix/alpine-java:8_jdk as IMAGE

COPY --from=BUILD /tmp/sginer/zookeeper /usr/sginer/zookeeper/
WORKDIR /usr/sginer/zookeeper

# ENV SERVER1_IP=ZOO-SERVER1
# ENV SERVER2_IP=ZOO-SERVER2
# ENV SERVER3_IP=ZOO-SERVER3
ENV SERVER_ID=1

COPY zoo.cfg /usr/sginer/zookeeper/conf
RUN  dos2unix /usr/sginer/zookeeper/conf/zoo.cfg
COPY run-zookeeper.sh /usr/sginer/zookeeper 
RUN  chmod +X /usr/sginer/zookeeper/run-zookeeper.sh && dos2unix /usr/sginer/zookeeper/run-zookeeper.sh
RUN  mkdir /usr/sginer/zookeeper/data

CMD [ "./run-zookeeper.sh" ]
```

zoo.cfg
```
tickTime=2000
initLimit=10
syncLimit=5
dataDir=/usr/sginer/zookeeper/data
clientPort=2181
server.1=ZOO-SERVER1:2888:3888
server.2=ZOO-SERVER2:2888:3888
server.3=ZOO-SERVER3:2888:3888
```

run-zookeeper.sh
```
echo ${SERVER_ID} > /usr/sginer/zookeeper/data/myid

/usr/sginer/zookeeper/bin/zkServer.sh start-foreground
```

When I run the image in interactive mode with this command, all works fine

```shell
docker run --it --name ZOO-SERVER1 --rm zookeeper:1 /bin/sh
```

But if I launch the container with this command

```shell
docker run -d --name ZOO-SERVER1 zookeeper:1

or

docker run -d --name ZOO-SERVER1 zookeeper:1 /usr/sginer/zookeeper/run-zookeeper.sh

```

I'have got this error in logs

standard_init_linux.go:195: exec user process caused "exec format error"

### Information

Docker informations

Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:22 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:29 2017
  OS/Arch:      linux/amd64
  Experimental: true

**Comment by rn** [comment]
This doesn't look like Docker for Windows specific issue, so I'm closing it.

It looks like `/run-zookeeper.sh` needs a `#!/bin/sh` in the first line so that it is executed as shell script

**Comment by sginer** [comment]
I have the same issue when I install bash shell in my image !

**Comment by rn** [comment]
it's not a question of having bash installed or not. If you use `CMD` it will try to execute `run-zookeeper.sh` which is just a text file so you get the error `"exec format error"`. You need to tell the system that this is a *shell* script. Either you add the `#!/bin/sh` as the first line in `run-zookeeper.sh` or you change the `CMD` line to something like:
```
CMD ["/bin/sh", "./run-zookeeper.sh"]
```

**Comment by sginer** [comment]
Oups, well, you'r right.

Sorry and thank you.

Regards

Stéphane GINER

2018-03-18 19:07 GMT+01:00 Rolf Neugebauer <notifications@github.com>:
