### ISSUE TITLE
How to expose UDP ports in windows docker file 

### ISSUE THREAD

**Issue by sharathj007** [docker/for-win#1851]
I am adding below UDP ports in windows dockerfile, but unable to get the data which i suppose to get from these ports. Pleas could any one can help me like how i can expose the UDP ports in windows docker file.

EXPOSE 21150:21150/udp
EXPOSE 21151:21151/udp
###################
Using the below command to run the  image
docker run -p 21150:21150/udp -p 21151:21151/udp imagename

**Comment by jacobblock** [comment]
Might be similar to https://github.com/docker/for-win/issues/1791?
