### ISSUE TITLE
Docker start error

### ISSUE THREAD

**Issue by sergiusnick** [docker/for-win#1852]
### Expected behavior

Docker is started

### Actual behavior

Docker is not started

### Information

  - diagnostic ID: 258C5AB0-DA8D-49AF-9E60-4BC469234C0A/2018-03-19_10-44-10
  - host distribution and version (Windows 10)

**Comment by jasonbivins** [comment]
@sergiusnick   It looks like the full diagnostic package didn't get fully created - can you resend?  Right click the Docker whale - choose Diagnose and Feedback
