### ISSUE TITLE
docker is not starting after installing on windows 10 Education

### ISSUE THREAD

**Issue by dheemanth1434** [docker/for-win#1854]
I am using windows 10 Education built number 1607 
![build](https://user-images.githubusercontent.com/22279025/37591358-4a1f8998-2b91-11e8-82fb-0e902528ff69.JPG)
I have installed docker it has installed correctly without showing errors after I tried to run the docker but it is showing that your windows version is not supported but in the documentation system requirements satisfied with my system.
![dockererror](https://user-images.githubusercontent.com/22279025/37591554-f941a6d6-2b91-11e8-885e-9f5400ca9808.JPG)
I have tried by enabling Hyper-v and virtualization but they did not work so, please resolve this

**Comment by rn** [comment]
Could you try:
```
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All
```
in an elevated powershell (ie run as Administrator).

**Comment by rn** [comment]
also could you provide a copy of `C:\Users\<username>\AppData\Local\Docker`? The easiest is via diagnostics (`Diagnose and Feewdback` in the system tray) assuming the app get's that far. Otherwise a zip file would be great.

**Comment by mdwhitis** [comment]
The Opening an Admin Powershell and doing:
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V –All
Worked for me an Windows 10 Pro.

**Comment by stephen-turner** [comment]
@dheemanth1434 Did you try @rn's commands. Are you still having problems? Otherwise I will close this ticket.
