### ISSUE TITLE
They're close, but "docker.for.mac.host.*" and "docker.for.win.*" should be better

### ISSUE THREAD

**Issue by atrauzzi** [docker/for-win#1855]
When running Docker for Windows and Docker for macOS, we get these handy aliases like `docker.for.mac.localhost`, `docker.for.mac.internal`, `docker.for.win.localhost` and `docker.for.win.internal`.

Unfortunately, when my projects are being worked on between macOS and Windows, someone has to go changing any of these host names for the specific platform they're on, despite the premise of the two being the same!  The fact that these two things that accomplish the exact same outcome are named differently is unhelpful.

Is there any way we can get a new convention like `docker.internal` and `docker.localhost`? Would it also be possible to simply have them resolve `localhost` when used on Linux which obviously doesn't have the extra layer going on?

The name of the game here is that I need my containers to have a consistent way to reference not the VM, but the actual physical hardware they're running on. Bonus points if it's a consistent IP address so that I can configure my own DNS aliases!

Moreover, would it be possible either with or without my suggested change to get all these magic hostnames documented somewhere? They seem to be rather un-googleable and largely defined by anecdotal knowledge rather than being clearly offered.

cc.
 - https://github.com/moby/moby/issues/36625
 - https://github.com/docker/for-mac/issues/2705

**Comment by akimd** [comment]
Let's close this one, and track the issue in docker/for-mac#2705.
