### ISSUE TITLE
Running the same process multiple times at the same time fails with strange errors, locking?

### ISSUE THREAD

**Issue by SeBsZ** [docker/for-win#1856]
It took me a long time to understand what was going on. I'm running this on a docker container running an opensuse image. I have found that when I open two powershells and log into the containers using `docker exec` and run the same command in both windows at almost the exact same time:

`env-linux/bin/python3 complexscript.py`
Created using virtualenv

Both windows will fail with the weirdest errors, mostly this one:

`Traceback (most recent call last):`
`  File "complexscript.py", line 29, in <module>`
`    import requests`
`ImportError: No module named 'requests'`

If I wait a few seconds between running the command in each Powershell, then the scripts run correctly.

I have also found that when I copy this directory to another directory that I just created, say /test then everything works as expected. The difference is that the first directory is actually a docker-compose volume mounted using `volumes:`. This means that the contents is synchronized to that of a Windows folder on the host.

My conclusion is that there seems to be some kind of file or directory locking going on that is causing these strange issues. I'm sure it's not limited to Python, but that's how I discovered something was wrong.

How can this be solved? Many thanks in advance. I apologize for not using the issue template. I wasn't sure how to explain how this can be reproduced. Let me know if I need to share more information.

**Comment by rn** [comment]
could you please provide some basic information, like what version you are using, what version of windows, is this with LCOW or the normal mode for Linux containers, is this on a volume mount, etc etc. Ideall with steps to reproduce as well.

**Comment by SeBsZ** [comment]
Absolutely, sorry for the scarcity of information, I thought this wasn't specific to my computer but just a general thing.

- Windows 10 version 1709 build 16299.309
- Docker CE 17.12.0-ce-win47 (15139), compose 1.18.0
- I have the option to "Switch to Windows containers", I'm not sure if I'm using LCOW or not.
- I mentioned it was on a volume mount, yes.

Steps to reproduce:
- Start a container based on opensuse:42.3
- Enter an interactive shell, using `docker exec`.
- Install packages for python such as python3-pip python3-virtualenv
- Create a virtualenv using `virtualenv env-linux`, in a volume attached to the host.
- Open a second interactive shell and run the same python script twice, quickly switch from one window to the other and hit enter in quick succession to run the same script at nearly the same time.
- Run the script using `env-linux/bin/python3 myscript.py`
- The python script should also be in the same volume attached to the host.
- The python script can be completely empty, it will still be reproduceable.

**Comment by rn** [comment]
Thanks, but could you please provide *exact* commands. For example:
- docker command line for starting container with volume mounts etc
- I have no idea how opensuse packaging works so don't know how to install stuff on opensuse
- what's `myscript.py`
- etc...

**Comment by SeBsZ** [comment]
- I mentioned myscript.py is completely empty.

I use docker-compose, here is the relevant part:

```
web_server:
    build: ./docker/
    command: bash -c "rm -f /var/run/httpd.pid && /usr/sbin/httpd -DFOREGROUND"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/srv/www/htdocs/mysite_dev/
```

Here's the exact Dockerfile I use for the above machine, it also comes with all the packages installed:

```
FROM opensuse:42.3
MAINTAINER Sebastiaan Bakker <sebs89@gmail.com>

WORKDIR /root/

RUN zypper addrepo https://download.opensuse.org/repositories/devel:languages:python/openSUSE_Leap_42.3/devel:languages:python.repo
RUN zypper addrepo https://download.opensuse.org/repositories/server:php:extensions:php7/openSUSE_Leap_42.3/server:php:extensions:php7.repo
RUN zypper -n --no-gpg-checks refresh
RUN zypper -n in curl vim apache2 apache2-mod_php7 java-1_8_0-openjdk java-1_8_0-openjdk-devel php7 php7-xdebug php7-mysql php7-memcached php7-curl php7-gd php7-exif php7-mbstring php7-ctype php7-phar php7-json php7-openssl php7-iconv php7-zlib php7-dom git subversion zip unzip mariadb python-supervisor python-setuptools python-devel python3-pip python3-virtualenv
RUN curl -sS https://getcomposer.org/installer | php
RUN mv composer.phar /usr/local/bin/composer

RUN mkdir /etc/supervisord.d/ /var/log/supervisord/ /var/run/supervisord/

RUN echo "LoadModule php7_module                    /usr/lib64/apache2/mod_php7.so" >> /etc/apache2/loadmodule.conf
RUN echo "LoadModule rewrite_module                 /usr/lib64/apache2/mod_rewrite.so" >> /etc/apache2/loadmodule.conf
RUN sed -i "s|APACHE_SERVER_FLAGS=\"\"|APACHE_SERVER_FLAGS=\"SSL\" |g" /etc/sysconfig/apache2
RUN sed -i "s|jdk.jar.disabledAlgorithms=MD2, MD5, RSA keySize < 1024|jdk.jar.disabledAlgorithms=MD2, RSA keySize < 1024|g" `readlink -f /usr/bin/java | sed -En 's@bin/java@lib/security/java.security@p'`
```

- I then just run `docker-compose up`.
- When it is running, I open two new powershell windows and use `docker exec -i -t web_server_1 /bin/bash`
- In both windows go to /srv/www/htdocs/mysite_dev/
- In one window run `virtualenv env-linux` and also create an empty file named myscript.py.
- In both windows run `env-linux/bin/python3 myscript.py` at the same time.

Let me know if that works or if you still can't reproduce the issue.

**Comment by plastbox** [comment]
Steps to reproduce: [https://github.com/docker/for-win/issues/969#issuecomment-411429451](url)

/remove-lifecycle stale

**Comment by hendrics** [comment]
i wonder if this issue is related https://github.com/docker/for-win/issues/2368 is related, thought that about accessing the same file twice from a local windows director mapped as volume

```python
with open(sys.argv[1], "r"):
      print("Open file once")
      with open(sys.argv[1], "r"):
      print("Open file twice")
```

Second print never happens.  Might just a similar issue, but not related.
