### ISSUE TITLE
Reinstall fails "Existing d4w installation is up to date"

### ISSUE THREAD

**Issue by noobG** [docker/for-win#1865]
### Expected behavior
Docker for Windows installs when running the installer

### Actual behavior
It doesn't

### Information
I ran into some issues where my containers wouldn't be accessible via localhost (probably related to https://github.com/docker/for-win/issues/1707). After trying for a few days to fix the problem, I decided to just remove docker completely and try again. To remove docker, I ran the script (as administrator) found here: https://success.docker.com/article/how-to-completely-remove-docker-in-windows-10

It seems to have removed Docker and the commands are no longer accessible in shell, but now I can no longer reinstall docker. When I run the installers (tried both 17.x and 18.x), it first says "Downloading packages..." for a few moments, and then it says "Existing d4w installation is up to date". Not sure where to go from here.

Edition: Windows 10 Pro
Version: 1709
OS Build: 16299.309

### Steps to reproduce the behavior
Not sure if it's consistently reproducable since I can't reinstall Docker and give it another go

  1. Run the script found here https://success.docker.com/article/how-to-completely-remove-docker-in-windows-10
  2. Run "Docker for Windows installer.exe"

**Comment by jasonbivins** [comment]
Hi @noobG 

It looks like that script doesn't catch all the registry keys - look for this one and remove it, along with any other docker keys here: `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Docker for Windows`

**Comment by noobG** [comment]
Hey @jasonbivins - thanks for the help

I don't see a Docker for Windows or any other docker related registry keys on my computer

**Comment by jasonbivins** [comment]
@noobG   Sometimes the installer doesn't use the Docker for Windows keys and names them using a GUID
Go to `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall` 
You'll need to manually arrow through the keys with GUID names for a Docker keys.

**Comment by noobG** [comment]
No dice, sadly

Been through them twice, no indication of Docker anywhere

**Comment by noobG** [comment]
@jasonbivins I ended up finding docker in the list of uninstallable programs in windows ("Uninstall or change program") and removed it there as well. Afterwards I was able to reinstall.

**Comment by dc8948** [comment]
Finding the above key in the "Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Docker for Windows" in registry fixed my problem. 

In the PS script that was provided at the top of this message, I added the following line to the bottom of the PS script to help in the future:

GET-ItemProperty HKCU:\software\microsoft\Windows\currentversion\uninstall -name "Docker for Windows" | Remove-Item -Recurse Force

**Comment by liddlem** [comment]
I tried all those things and it's still not working for me.
