### ISSUE TITLE
How to configure docker daemon in MobyLinuxVM?

### ISSUE THREAD

**Issue by sudipto92** [docker/for-win#1867]
Environment
  - I have tried with the latest version of my channel (Stable)
  - Docker for Windows Version: 17.12.0-ce-win47 (15139)

### Information
Currently, I have configure docker daemon for windows.
But i am not able to configure docker daemon for MobyLinuxVM( Linux Container).
Please guide me.

**Comment by prisar** [comment]
I also wanted to configure ModyLinuxVM since my docker for windows setup is not working because of **vpnkit** not running properly in Windows Server 2016 Standard.

**Comment by guillaumerose** [comment]
@sudipto92 You can directly change the daemon.json in the UI. 

@prisar We don't support Windows Server 2016. Although it should work as it is. Please use Windows 10 instead.

**Comment by prisar** [comment]
@guillaumerose then what is the supported version of Windows 10 needed for development?

**Comment by guillaumerose** [comment]
@prisar Take a look at https://docs.docker.com/docker-for-windows/install/#what-to-know-before-you-install

```
The current version of Docker for Windows runs on 64bit Windows 10 Pro, Enterprise and Education (1607 Anniversary Update, Build 14393 or later).
```

**Comment by prisar** [comment]
@guillaumerose Is it possible/recommended to use docker4windows in **64bit Windows 10 Pro or Enterprise** virtual machine in Hyper-V or VM Ware? I mean nested virtualization.

**Comment by guillaumerose** [comment]
We tried it for our CI. It was a nightmare. We had lot of issues with nested virtualization : strange errors and bad performance.

**Comment by prisar** [comment]
then what would be your suggestion, A physical machine with windows 10 installed?

**Comment by guillaumerose** [comment]
Yes it's the best solution

**Comment by prisar** [comment]
is there any other solution for the development environment. bcos i am not getting any physical machine currently.

**Comment by sudipto92** [comment]
@guillaumerose i have tried below steps:
Docker daemon for windows container is already configured
1. Right Click on Docker Icon ->Switch to Windows container
2. Right Click on Docker Icon ->Settings.. -> Daemon -> then click on advanced -> add below line
{"Hosts":[tcp://0.0.0.0:2375]} -> click on apply

But daemon is only configured for "Windows Container" in "Docker for windows".
I want to configure docker daemon for linux continer only
