### ISSUE TITLE
Error when i want to create a docker-machine 

### ISSUE THREAD

**Issue by Heartdeath** [docker/for-win#1868]
- Docker for Windows Version: 18.03.0-ce-rc4, build fbedb97

### Expected behavior

I want to create a docker-machine with that command : 

docker-machine create -d virtualbox dev

But i have this message : 
`Running pre-create checks...
Error with pre-create check: "This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)"`

so, I tested like this : 

docker-machine create -d  --virtualbox-no-vtx-check virtualbox dev

### Actual behavior

Actually, i have this error when i execute a docker-machine with virtualbox

output console 
![error](https://user-images.githubusercontent.com/22813795/37765491-869bfd0e-2dc4-11e8-8246-c5c0c8055bb5.PNG)

output virtualbox
![vb](https://user-images.githubusercontent.com/22813795/37765601-dabd10b2-2dc4-11e8-9466-f15cce645889.PNG)

If anyone can help me that would be great ! 

Have a good day

**Comment by guillaumerose** [comment]
This issue is related to docker-machine, please open it on https://github.com/docker/machine

Thanks.
