### ISSUE TITLE
Two networks with name "nat"

### ISSUE THREAD

**Issue by JanneRantala** [docker/for-win#1869]
### Expected behavior

Docker would only have one default "nat" network

### Actual behavior

Two "nat" networks exists, and neither can be used 

### Information

At some point when using Docker from Edge channel, the update process has managed to screw up networks Docker creates, and now I have two networks named "nat":

$ docker network ls
NETWORK ID          NAME                                                               DRIVER              SCOPE
33fbf59fe519        DockerExternal                                                     transparent         local
e3c6cb5f70f9        Wifi                                                               transparent         local
37a848736fb5        c1aed3e7578e8bf861dd7d34c190499ba378cff3cae50f81485e74e289073323   nat                 local
a27389cafa30        nat                                                                nat                 local
edecf92bee80        nat                                                                nat                 local
36ffac58f33a        none                                                               null                local

When I run for example docker-compose which has nat network defined in it, i'm getting error 

> ERROR: 2 matches found based on name: network nat is ambiguous

And if I try to remove one of those networks, I can't do that because of

> Error response from daemon: nat is a pre-defined network and cannot be removed

  - Windows Version: Windows 10 Enterprise 1703
  - Docker for Windows Version: 18.03.0-ce-rc4-win57 (16511)
  - Diagnostics id: 7143158E-5CC1-4EAC-B0B4-591C12A47682/2018-03-22_12-56-52

### Steps to reproduce the behavior

  1. This is a bit difficult to reproduce, something probably went wrong during DfW upgrade. And it ended up with two networks. Other needs to be removed, but don't know how.

**Comment by david-jarman** [comment]
I'm experiencing this too after the latest Docker update

**Comment by phorozan** [comment]
Same problem here!

**Comment by david-jarman** [comment]
I uninstalled Docker and reinstalled the [previous version](https://docs.docker.com/docker-for-windows/release-notes/#docker-community-edition-17120-ce-win47-2018-01-12).  That fixed the issue for me.

**Comment by phorozan** [comment]
I managed to address this issue by disabling the experimental features from the settings dialog and resetting the docker to factory settings.

**Comment by JanneRantala** [comment]
@phorozan Disabling experimental features and reseting to factory settings didn't help me.

**Comment by TribeDataWorksJim** [comment]
Same. Downgrading worked for me.  [https://docs.docker.com/docker-for-windows/release-notes/#docker-community-edition-17120-ce-win47-2018-01-12]

**Comment by bplasmeijer** [comment]
3c8a2dcba596        nat                                                                nat                 local
2057699b8f36        nat                                                                nat                 local

docker network rm 3c8a2dcba596
Error response from daemon: nat is a pre-defined network and cannot be removed

same here

**Comment by cocowalla** [comment]
I got the same after switching to LCOW

**Comment by david-jarman** [comment]
Here's what I did to get around this:

1. Run ```docker network ls``` and observe two NAT networks
1. Run ```Get-NetNat``` in Powershell and observe two NAT networks: Nat1 and Nat2
1. Run ```Remove-NetNat -Name Nat2``` to get rid of the second NAT network
1. Reset docker to factory settings
1. Run ```docker network ls``` and observe two networks with "DRIVER" set to nat, but this time, the name of the first one is a GUID, and running ```docker network rm <guid>``` succeeds, thus removing the second NAT network.

Mileage may vary, but this is what worked for me :)

**Comment by abjrcode** [comment]
@david-jarman Thanks for linking to the appropriate solution. Those steps didn't exactly work but there is another section in the page which modifies the registry and fixes it.

**Comment by Fredoid** [comment]
Same problem with Docker version 18.03.0-ce-win59, build 0520e24302 on Windows 10.

After uninstalling Docker, removing all Docker and .docker folder, re-installing Docker, same issues:

1. `docker network ls` shows 2 networks named `nat`
2. I have a container raising this error: `failed to build: network nat is ambiguous (2 matches found on name)`. Others containers on my laptop works well.

`Get-NetNat` return an empty result on my computer.

I don't know how, when and why Docker created thoses two network named `nat` and I have no idea how to restore the situation.

**Comment by Fredoid** [comment]
I've just found a solution in [this topic](https://social.msdn.microsoft.com/Forums/vstudio/en-US/a49c5cf8-b089-4421-bb12-ffa84f63a65c/docker-network-ls-is-showing-2-nat-networks?forum=windowscontainers) 

Simply run this following ps script to clean networks named "nat" and restart your computer.

```
$KeyPath = "HKLM:\SYSTEM\CurrentControlSet\Services\vmsmp\parameters\SwitchList"
$keys = get-childitem $KeyPath

foreach($key in $keys) {
	if($key.GetValue("FriendlyName") -eq 'nat')	{
		$newKeyPath = $KeyPath+"\"+$key.PSChildName
		Remove-Item -Path $newKeyPath -Recurse
	}
}

remove-netnat -Confirm:$false
```

Works on Windows 10 Pro with Docker version 18.03.0-ce-win59, build 0520e24302.

Thanks

**Comment by huangjj27** [comment]
Same issue occured in `Docker version 18.09.1, build 4c52b90`, using Windows 10 pro

**Comment by delcroip** [comment]
I finally worked for me by doing:

- Deactivate Experimental features as suggested by @phorozan
- Do Factory reset 
- The second nat changed its name 
![image](https://user-images.githubusercontent.com/4052505/58188879-b476f680-7cb9-11e9-97fe-594b1c160d2a.png)
- so I was able to remove to with
![image](https://user-images.githubusercontent.com/4052505/58188914-c6589980-7cb9-11e9-8db4-834fcc19cda6.png)

It is possible that it was luck because it was also the third time I did a factory reset .... maybe one should do factory reset until the second nat changes name

**Comment by alexluna1984** [comment]
On my PC windows 10 Pro did the following and it worked:
```
 Stop service docker
 Stop service HNS
 Delete "C:\ProgramData\Microsoft\Windows\HNS\HNS.data"
 Delete "C:\ProgramData\docker\network\files\local-kv.db"
 Start service HNS
 Start docker
```
Then restart your computer and start docker service again.
