### ISSUE TITLE
Docker error after update to 1.12.3-beta29.2 (8280) Issue with creating virtual Ethernet Switch

### ISSUE THREAD

**Issue by thariman** [docker/for-win#187]
### Expected behavior
Start Docker after update
### Actual behavior
Unable to start docker red
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
A42E28E6-C8F7-4CFD-A176-D04CC74FC87F/2016-11-01_11-56-15
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ... Update to version 1.12.3-beta29.2 (8280)
  2. ...  Tried to reinstall Hyper-V same issue.
  3.     Delete all the Hyper-V intervace switch and reinstall Hyper-V same issue.

Currently Hyper-V unusable.
When I tried to create new switch it give this error:
New-VMSwitch -name "NAT" -SwitchType internal
New-VMSwitch : Failed while creating virtual Ethernet switch.
Switch create failed, name = '7283DDE2-4385-4C42-A050-26BF7D90333C', friendly name = 'NAT': Ran out of memory (0x8007000E).

**Comment by dgageot** [comment]
@thariman Can you please give a try to Docker for Windows Beta31 and tell us if this fixes the issue for you?

**Comment by thariman** [comment]
I reinstall windows 10.

**Comment by dsmaher** [comment]
@dgageot - I have what appears to be the same issue.  I'm using Version 1.13-rc3-beta32.1, and docker is reporting the following error on startup:

```Unable to create: Cannot validate argument on parameter 'VMSwitch'. The argument is null. Provide a valid value for the argument, and then try running the command again.
at New-MobyLinuxVM, <No file>: line 234
at <ScriptBlock>, <No file>: line 370
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

The "crash report" that runs while that error is shown hangs forever, and the Docker for Windows Service chugs along consuming ~18-20% CPU.  When I kill that, the Docker for Windows UI consumes 18-20% CPU.

I've tried uninstalling + reinstalling, and have also tried manually deleting the `DockerNAT` VM Switch to no avail.  I get the same "Ran out of memory" error reported above (I seriously doubt that error is accurate... I've got 32GB RAM).

I have another Windows machine using the same Docker build that is working fine... (The *working* one is a VM on my Mac running under Parallels, and the *broken* one is my physical Windows box.. odd, right?).  The physical (aka broken) machine also has another Hyper-V VM on it, and I have two virtual switches I created for use by that other VM... not that I expect that should matter, but I know that any information is good information.

**Comment by dsmaher** [comment]
UPDATE:  I tried hacking the registry to remove the switch.... and that just made Docker move on to a different error.  I didn't save the information, but there might be a crash report for it.

Then I tried uninstalling Hyper-V and reinstalling it.  Unfortunately, that was my worst mistake.  Perhaps if I tried the hyper-v reinstall before the registry hack, it wouldn't have been so catastrophic, but it ended up making my physical network card completely unusable for Windows, and after several attempts at trying to resolve that, I ended up having to do a full reinstall of Windows.

So.... the moral of the story is... this is a *really* bad situation when it happens.

**Comment by rneugeba** [comment]
I'm closing this issue. @thariman seems to have fixed it by re-installing.

@dsmaher your system seemed to have been in a very bad state. This there was no followup I assume the re-install fixed it. If not, please try the latest Beta an open a new issue.

Thanks

**Comment by dsmaher** [comment]
Yes, reinstalling Windows fixed the problem.  After further investigation, it's possible that my hyper-v state may have been corrupted by a bad (older) Window Insider Preview build.  The current Windows preview build with the current Docker Beta build is fine.
