### ISSUE TITLE
Kitematic Blue Screens 

### ISSUE THREAD

**Issue by mdwhitis** [docker/for-win#1882]
A diagnostic was uploaded with id: CBAB554F-D929-47D0-9451-7C603BD5463F/2018-03-26_10-55-33in this Issue
  - Windows Version: 10 Pro Bversion 1709 Build 16299_334
  - Docker for Windows Version:  Dpocker Community 18.03.0-ce-win59 (16762)
     Channel Stable d70d80d

### Expected behavior
Starts Kitematic

### Actual behavior
Blue screens Windows
### Steps to reproduce the behavior
Start KiteMatic

**Comment by mdwhitis** [comment]
Blue Screen:
https://drive.google.com/file/d/0Bwek3_i4pMbdeE00ZE5kVGVhUTE3WXJyVEstZGJLX3RiUUVN/view?usp=sharing

**Comment by pgayvallet** [comment]
Hi,

Please open an issue in kitemac tracker : https://github.com/docker/kitematic

Closing.
