### ISSUE TITLE
If running before, auto start docker after successful upgrade/installation

### ISSUE THREAD

**Issue by MatthewHartstonge** [docker/for-win#1884]
To help with user friendliness, I want to propose auto-starting docker after being upgraded. Especially if docker has been killed at the beginning of the upgrade process.

  - [X] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics **(N/A)**
  - [x] I have included the Diagnostics ID in this Issue **(N/A)**
  - Windows Version: Microsoft Windows 10 Pro 10.0.16299 Build 16299 64-bit
  - Docker for Windows Version: 18.03.0-ce-win58 (16761) (edge)

### Expected behavior
- Docker finds an upgrade and asks you to upgrade
- Click to upgrade docker.
- Docker upgrade kills docker vm/process
- Docker installs/upgrades
- Docker upgrade restarts docker vm/process
- Docker installation/upgrade = complete
- Can do the dockery thing

### Actual behavior
- Docker finds an upgrade and asks you to upgrade
- Click to upgrade docker
- Docker upgrade kills docker vm/process
- Docker installs/upgrades
- Docker installation/upgrade = complete
- Starts to do the dockery thing
- derp, docker isn't running
- Hit winkey
- Search for docker
- Click/hit enter on docker shortcut
- twiddle thumbs waiting for dockery productiveness
- Can do the dockery thing

### Steps to reproduce the behavior

  1. Install older version of docker
  2. Right click on tray icon
  3. Click "Check for updates"
  4. When upgrade dialog pops up, Click "Upgrade"

**Comment by jasonbivins** [comment]
Hi @MatthewHartstonge 
We've got this in as a future enhancement request, but for now it's blocked due to a security issue in WIndows.  I'll add your request to the existing one, and I'll go ahead and close this one out.
