### ISSUE TITLE
E_ACCESSDENIED on startup

### ISSUE THREAD

**Issue by primus852** [docker/for-win#1887]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have submitted Diagnostics
  - [X] I have included the Diagnostics ID in this Issue
  - Windows Version: Windows 10 Pro 1709
  - Docker for Windows Version: 18.03.0-ce-win59 (16762)

### Expected behavior
Docker for Windows should start up as expected
### Actual behavior
I get an error message saying
 ```
Zugriff verweigert (Ausnahme von HRESULT: 0x80070005 (E_ACCESSDENIED))
   bei Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:Zeile 36.
   bei Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:Zeile 67.
   bei Docker.Actions.<>c__DisplayClass16_0.<ResetToDefault>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:Zeile 124.
   bei Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:Zeile 59.
```
I tried reinstalling and resetting to factory defaults as well, this also occurred on the earlier version (17 sth). I disabled the firewall and started Docker for windows as admin, still the same result.
### Information
Diagnostics ID: `DBB91407-3D74-4534-8C4B-7260DFCDD2BE/2018-03-27_11-28-30`
[log.txt](https://github.com/docker/for-win/files/1851467/log.txt)

**Comment by pentago** [comment]
Having the same issue. Nothing I do seems to resolve this issue.
This is the second time I get this issue, each time after Docker for Windows upgrade to a newer build.
Any idea on what can cause this and how to triage?

Thanks in advance!

**Comment by rn** [comment]
@primus852 do you run any AV software?

**Comment by primus852** [comment]
I run  the Windows Defender and windows firewall, nothing else.

Rolf Neugebauer <notifications@github.com> schrieb am Mi., 4. Apr. 2018,
17:16:

**Comment by rn** [comment]
could you try disabling CCleaner64 just in case it interferes? If that fails, could you try to quit any unnecessary apps...from the logs, some operations seem to take an unusually long time.

**Comment by Kender2** [comment]
For me (diagnostics ID DC0F15FC-416F-4314-9DE4-476C1AF742F7/20190213184211) this error occurs because Windows Firewall Control (from binisoft.org) prevents other programs from modifying windows firewall rules and settings.

```Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59```

Why does docker need to modify the firewall every time it starts? Can't we get a rule or set of rules included once? It kinda sucks to have to disable and re-enable firewall protection every time I want to start docker.
