### ISSUE TITLE
could not start the MobyLinuxVM on windows 10

### ISSUE THREAD

**Issue by arthi-ramachandran** [docker/for-win#189]
### Information
(1) installed "docker for windows" on windows 10 vm image enterprise edition
(2) When docker starts it thorws the following error:
          could not start MobyLinuxVM due to one of the Hyper-V components is missing. Same error while trying to start the VM from within the Hyper-V administrator

Hyper-V is enabled on the vm image. Task Manager -> Performance , "virtualization" is not an option that is being displayed. There is no concept of BIOs on vm image. How should we get this to work ? Have been breaking for a while. Help much appreciated.

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by rneugeba** [comment]
thanks for the report. which version of Docker for Windows are you using and does the error message contain a diagnostics ID you could provide?

**Comment by arthi-ramachandran** [comment]
Thanks. It seems the problem was that "virtualizatio" is not an option to enable or disable via the BIOS as it is virtual machine. We moved to bare  metal system and can get MobyLinuxVM to start. 

However, the bigger issue is that on windows 10 enterprise edition, with docker for windows installed, the microsoft/windowsservercore cannot be pulled. I get an 'unknown blob' message after several retries. 
https://hub.docker.com/r/microsoft/windowsservercore/
Many have reported this error in the post also.

Is there any light on how to pull the windowsservercore image ? Much appreciated.

**Comment by rneugeba** [comment]
@arthi-ramachandran thanks for getting back. Since the original issue is fixed. I'll close this issue. Could you open a new issue with the windowsservercore issue you are seeing, ideally with the command line you are using and uploaded diagnostics after the failure.
Thanks

**Comment by arthi-ramachandran** [comment]
Thanks. I am not sure if the issue is fixed. However, switched to a physical system with virtualization turned on to progress.

The bigger problem is that the Microsoft  windowsservercore image cannot be pulled. Gave the diagnostic id and logs in #195 Help will be much appreciated.
