### ISSUE TITLE
An extra \r is appended to the command in interactive mode

### ISSUE THREAD

**Issue by Cisien** [docker/for-win#1891]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have submitted Diagnostics
  - [X] I have included the Diagnostics ID in this Issue
  - Windows Version: 1803 (17634)
  - Docker for Windows Version: 18.03.0-ce

### Expected behavior
Pressing enter in an interactive session does not include an extra `\r` at the end of the command

### Actual behavior
An extra `\r` is appended to the end of the command
### Information
`99ECE95D-0F09-4A0E-ABAE-217A55967E65/2018-03-27_17-27-12`

```
C:\WINDOWS\system32>docker info
Containers: 12
 Running: 0
 Paused: 0
 Stopped: 12
Images: 51
Server Version: 18.03.0-ce
Storage Driver: lcow (linux) windowsfilter (windows)
 LCOW:
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17634 (17634.1000.amd64fre.rs_xbox.180323-1630)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 20
Total Memory: 31.7GiB
Name: Chris-PC
ID: YNTS:2WNQ:Z5T2:RYDB:3QUU:G4F2:2CYC:ABPV:AB7F:QHLA:S7KH:NYMJ
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 23
 System Time: 2018-03-27T17:31:00.0928453-07:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
Console code page 437
### Steps to reproduce the behavior
```
docker pull ubuntu --platform=linux
docker run --rm -i ubuntu bash
ls
bash: line 1: $'ls\r': command not found
```
including a `;` at the end of the command before pressing enter executes the command and then throws the error:
`/bin/bash: line 1: $'\r': command not found`

**Comment by stephen-turner** [comment]
I don't think this can work. PowerShell uses \r\n for its line endings, as normal on Windows, and that is passed straight into the container's stdin. It's essentially the same as https://github.com/moby/moby/issues/24388, but in interactive mode.

Are you able to use -it? That works the way you would expect.

**Comment by Cisien** [comment]
`-it` works

**Comment by AlexeyPavlov2** [comment]
> `-it` works

man, tnx
