### ISSUE TITLE
Hi Bret Fisher,  my production environment is AWS Linux. In the AWS Linux they are upgrade their OS customization for docker. Can you help me how to install AWS Linux EC2 Instance on docker?

### ISSUE THREAD

**Issue by Sivaram007** [docker/for-win#1892]
Please, check https://docs.docker.com/docker-for-win/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  Edge - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have submitted Diagnostics
  - [ ] I have included the Diagnostics ID in this Issue
  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by pgayvallet** [comment]
Little early for april's fool.

Closing.

**Comment by BretFisher** [comment]
Ummmm.... 😳
