### ISSUE TITLE
Simple demo that comes with Docker fails on Windows 10

### ISSUE THREAD

**Issue by bgoldca** [docker/for-win#1894]
Please, check https://docs.docker.com/docker-for-win/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have submitted Diagnostics
  - [ x] I have included the Diagnostics ID in this Issue
  - Windows Version: 10
  - Docker for Windows Version: 18.03.0-ce

### Expected behavior
Test build would work (from here: https://docs.docker.com/get-started/part2/#apppy)
### Actual behavior
I get an error trying to build the pacakge:
C:\app>docker build -t friendlyhello .
Sending build context to Docker daemon   5.12kB
Step 1/7 : FROM python:2.7-slim
2.7-slim: Pulling from library/python
no matching manifest for windows/amd64 in the manifest list entries
### Steps to reproduce the behavior

Diagnostic ID: EECAFC7B-5726-4B02-B403-8B71CA309AA8/2018-03-28_14-05-26

  1. created three files - app.py, dockerfile and requirements.txt
  2. populated files with the text provided here: https://docs.docker.com/get-started/part2/#apppy
  3. Ran docker build -t friendlyhello .
  4. I get the error: no matching manifest for windows/amd64 in the manifest list entries

**Comment by rn** [comment]
Looks like you try to build a Linux container when you have Windows containers enabled. If you try to use LCOW you need to specify `--platform linux` for the build

**Comment by rn** [comment]
closing as there was no response.
