### ISSUE TITLE
Docker does not start on Windows 10

### ISSUE THREAD

**Issue by fgozman** [docker/for-win#1897]
Please, check https://docs.docker.com/docker-for-win/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue
  - Windows Version: 10.0.16299 Build 16299
  - Docker for Windows Version: 18.03.0-ce-win58 (16761)
  - Diagnostic ID: D0ED53F1-412F-4BC1-85D3-1B6A192ABF5A/2018-03-29_11-46-12

### Expected behavior
Start running
### Actual behavior
Stopped with error:
"ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".
at New-Switch, <No file>: line 117
at <ScriptBlock>, <No file>: line 394
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 67
   at Docker.Actions.<>c__DisplayClass14_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 51
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

### Information

Windows Version: 10.0.16299 Build 16299
Docker for Windows Version: 18.03.0-ce-win58 (16761)
Diagnostic ID: D0ED53F1-412F-4BC1-85D3-1B6A192ABF5A/2018-03-29_11-46-12
Log file: [log.txt](https://github.com/docker/for-win/files/1859300/log.txt)

### Steps to reproduce the behavior

  1. Start Docker
  2. It will stop and show the a window with the text "An error occurred" and the following 
content:
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".
at New-Switch, <No file>: line 117
at <ScriptBlock>, <No file>: line 394
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 67
   at Docker.Actions.<>c__DisplayClass14_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 51
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by jurosh** [comment]
Same issue, cannot start Docker after latest update. :( My diagnostic id is `7C241551-3515-4639-8E87-90A15DB699E5/2018-03-29_12-01-27`

**Comment by reetamnath** [comment]
Hi,
I have the similar kind of issue but the Error message was different and i started getting this error after the docker update. Reverting it to the previous version didn't help me.

I got the following error:

Failed to start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer '<host>' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running..
at New-Switch, <No file>: line 117
at <ScriptBlock>, <No file>: line 394    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 183
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 111


Solve the issue by following the step in the [link](http://reinoutpennings.blogspot.in/2015/12/hyper-v-hyper-v-encountered-error.html)
and running the command 
**MOFCOMP %SYSTEMROOT%\System32\WindowsVirtualization.V2.mof**
from cmd as administration resolve the issue for me.

**Comment by fgozman** [comment]
@jurosh Did you have the same message like me with the version 18.03.0-ce-win58? I ask you this since I had similar problems also with the previous versions. I guess should be also some problems with Windows because I did some updates in Winrods and maybe it changed something in regards with Hyper-V. I also checked in the manager and have not find any VM created by Docker during the starting process like when I installed Docker for the first time. Very strange indeed. Thanks!

@reetamnath Tried before and also now tried again but nothing. Thanks!
Just in case someone from Docker see these the diagnostic ID is: D0ED53F1-412F-4BC1-85D3-1B6A192ABF5A/2018-03-29_15-00-41 and the error is the same.

**Comment by reetamnath** [comment]
@fgozman by seeing the error looks like your docker could not find the Hyper-V virtual switch for docker.
Try the following steps:
1. uninstall docker
2. perform the fix from [here](https://support.microsoft.com/en-us/help/3101106/you-cannot-create-a-hyper-v-virtual-switch-on-64-bit-versions-of-windo). 
3. Restart the pc.
4. install the docker.

Try it out.

**Comment by jurosh** [comment]
@fgozman I've updated comment; My error is one listed in here https://github.com/docker/for-win/issues/1780

**Comment by tiagocvboas** [comment]
Hello,

I do get the same error as @reetamnath 
```
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID B2C66165-AA93-44A1-8CA5-491926EC61E1)
at Start-MobyLinuxVM, <No file>: line 315
at <ScriptBlock>, <No file>: line 410
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 256
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 130
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Do
```

I have tried the downgrade to 17.12.0-ce and running:
```
MOFCOMP %SYSTEMROOT%\System32\WindowsVirtualization.V2.mof
````
As admin in a Powershell, restarted in between uninstalls and operations.

All without success.

**Comment by jasonbivins** [comment]
@fgozman   It looks like you're having an issue creating networks - this is from the Windows event viewer 
```The Network Setup Service service terminated unexpectedly.  It has done this 21401 time(s).```

Try to create the MobyLinuxVM manually, as well as the DockerNAT switch.
```
powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -create
```

**Comment by fgozman** [comment]
@reetamnath I tried the fix but for me was even worse because Windows refused to detect any network card.. I needed to reinstall Windows.

**Comment by tutnes** [comment]
Upgraded to docker Version: 18.03.0-ce-win59 (16762) today
Running:
OS: Windows 10 Pro
Edition: Professional
Id: 1803
Build: 17133
BuildLabName: 17133.1.amd64fre.rs4_release.180323-1312

And got the same issue.

**Comment by vnktsh** [comment]
Any updates on this issue? I'm facing the exact issue.

@fgozman Did you get to find any workarounds and make this work?

**Comment by karl-schelhammer-td** [comment]
I'm also having this same issue.

```
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".
at New-Switch, <No file>: line 117
at <ScriptBlock>, <No file>: line 394
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 67
   at Docker.Actions.<>c__DisplayClass14_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 51
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```
I also have a hyperv switch that doesn't appear to be attached to anything:

![hyperv-switch](https://user-images.githubusercontent.com/36993207/39442715-319d66fa-4c80-11e8-8b58-2bb11793f6d5.PNG)

I've reinstalled hyperv, docker more than a few times.  I've unistalled VirtualBox completely.

Eventually, I was able to get docker technically 'running', except now when I try to pull an image or do anything really, I get another error:

```
Using default tag: latest
Warning: failed to get default registry endpoint from daemon (error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.37/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.). Using system default: https://index.docker.io/v1/
error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.37/images/create?fromImage=tensorflow%2Ftensorflow&tag=latest: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

It all seems related to OP's issue from my perspective.  Or should I file an independent ticket?

Any advice here would be appreciated.

**Comment by karl-schelhammer-td** [comment]
I tried restarting from the settings tab and it still throws the same error whenever I try to pull any image.

**Comment by xcosmos6** [comment]
@reetamnath Thanks, it solved my problem by running the command MOFCOMP %SYSTEMROOT%\System32\WindowsVirtualization.V2.mof in powershell as administrator.

**Comment by leopal77** [comment]
Same issue here, diagnostic id `86E9E586-5A1F-434C-A372-5F1208B6A468/20180928132047`

What I have tried so far:
- Uninstall/install docker along with Hyper-V
- Manually create via Hyper-V manager app DockerNAT switch, **without** success
- `MOFCOMP %SYSTEMROOT%\System32\WindowsVirtualization.V2.mof` unfortunately does not work for me
- `powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -create` fails with this error log : 
`Hyper-V\Get-VMNetworkAdapter : Hyper-V was unable to find a virtual switch with name` .

Is there anything else I can try?

Thanks

**Comment by AddictArts** [comment]
+1 Same issue

**Comment by elimn** [comment]
I had the same problem, but none of the above solutions worked for me. I tried tons of variations on them, running various steps as an admin, rebooting in between, uninstalling and reinstalling Hyper-V. Here's what finally worked:

1. Open Hyper-V Manager
2. Click Hyper-V Settings
3. Under Server: Virtual Hard Disks click "Browse", and select an appropriate folder
4. Under Server: Virtual Machines click "Browse", and select an appropriate folder
5. Click Apply, then retry running Docker.

The problem was that ages ago I had setup Hyper-V to use a custom folder for its files. Some time during the intervening years I had delete those folders, as I stopped using Hyper-V. Thus, I was getting the exact same error message as everyone else, but for a different reason.

**Comment by bmoore813** [comment]
Im getting the same error and none of that has worked for me :(. Diagnostic report 9A1F2C86-5EDA-4882-B72B-31060D884658/20190109171157

**Comment by dorbsz** [comment]
same issue here, any updates?

**Comment by scabir** [comment]
I had the same issue; combination of two solutions mentioned by @reetamnath above helped:

- uninstall docker
- perform the fix from here.
- Restart the pc.
- install the docker.

and

- run `MOFCOMP %SYSTEMROOT%\System32\WindowsVirtualization.V2.mof` in Powershell admin mode
