### ISSUE TITLE
docker-compose failes with invalid volume specifiction

### ISSUE THREAD

**Issue by uglydawg** [docker/for-win#1899]
Please, check https://docs.docker.com/docker-for-win/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [X] I have tried with the latest version of my channel (**Stable** or Edge)
  - [X] I have submitted Diagnostics
  - [X] I have included the Diagnostics ID in this Issue
  - Windows Version: Windows 10 Pro
  - Docker for Windows Version: 18.03.0-ce

### Expected behavior
docker-compose trying to map drive
### Actual behavior
Fails with error:
PS C:\Users\user> docker-compose -f c:\temp\docker-compose.yml up --build
Creating temp_test_1 ... error

ERROR: for temp_test_1  Cannot create container for service test: invalid volume specification: '/c/temp:/data:rw'

ERROR: for test  Cannot create container for service test: invalid volume specification: '/c/temp:/data:rw'
ERROR: Encountered errors while bringing up the project.
### Information

156CB5F6-869E-4CF9-AE68-FC0358073106/2018-03-29_18-35-47

### Steps to reproduce the behavior

  1. docker-compose.yml
version: "3.6"

services:
  test:
    image: microsoft/windowsservercore
    volumes:
      - .:/data
networks:
  default:
    external:
      name: nat

  2. docker-compose -f c:\temp\docker-compose.yml up --build

**Comment by rn** [comment]
This looks like an issue with upstream `compose` not specific to the Docker for Windows application, so closing this. Could you open an issue on https://github.com/docker/compose instead?
