### ISSUE TITLE
docker-compose failing

### ISSUE THREAD

**Issue by krisbulman** [docker/for-win#19]
### Expected behavior
```bash
$ docker-compose --version
docker-compose version 1.x.x-rc-xx, build xxxxxxx
```

### Actual behavior
```bash
$ docker-compose --version
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose\cli\main.py", line 58, in main
  File "compose\cli\main.py", line 89, in dispatch
  File "compose\cli\docopt_command.py", line 25, in parse
  File "compose\cli\docopt_command.py", line 12, in docopt_full_help
  File "site-packages\docopt.py", line 575, in docopt
  File "site-packages\docopt.py", line 484, in extras
LookupError: unknown encoding: cp65001
docker-compose returned -1
```

### Information

  - ID 28C8317A-5C2F-4BC9-AA3B-D47229AA1776/2016-08-02_21-42-43
  - ```Docker version 1.12.0, build 8eab29e, experimental```
  - Windows 10 Insider Preview Build 14393

### Steps to reproduce the behavior

  1. Install docker for windows beta), test docker-compose --version
  2. Reset to factory defaults
  3. Follow instructions at https://docs.docker.com/docker-for-windows/
  4. Note that both  ```docker --version``` and ```docker-machine --version``` work

**Comment by dgageot** [comment]
Hi @krisbulman thanks a lot for taking time to report this issue.

This is a known [Compose bug](https://github.com/docker/compose/issues/2775) and [Python bug](http://bugs.python.org/issue1602). It comes from `cp65001` (the windows equivalent of utf-8) not being recognised as a valid encoding.

You must have set this encoding in your shell with something like `chcp 55001`.

I'm sorry I'm going to close this ticket in favour or [upstream compose issue](https://github.com/docker/compose/issues/2775)
