### ISSUE TITLE
Installation hangs if no disk space.

### ISSUE THREAD

**Issue by dazinator** [docker/for-win#1902]
Please, check https://docs.docker.com/docker-for-win/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have submitted Diagnostics
  - [ ] I have included the Diagnostics ID in this Issue
  - Windows Version: windows 10
  - Docker for Windows Version: 18.03.0-ce-win59

### Expected behavior
Installation fails gracefully if not enough disk space.

### Actual behavior
Installation hangs (not responding) - has been like this for 10+ minutes.

### Information

Installation not responding:

![image](https://user-images.githubusercontent.com/3176632/38138812-a4f51338-3424-11e8-99bb-31b9560e0bd4.png)

I have less than 1mb free space on C drive, so assuming this is related but only a guess.

### Steps to reproduce the behavior

  1. Install a docker update on windows 10 with low disk space.

**Comment by jasonbivins** [comment]
Hi @dazinator 
This appears to be a duplicate of https://github.com/docker/for-win/issues/1550

**Comment by dazinator** [comment]
@jasonbivins I hadn't seen that, thank you.
That issue actually has another link to one which I think is more closely related to what I am seeing (it shows a pretty much identical screenshot to mine): https://github.com/docker/for-win/issues/1417 which I think mine is a dupe of.

I will post there.
