### ISSUE TITLE
New install of Docker for Windows on Windows 10 hangs when starting a nanoserver container.

### ISSUE THREAD

**Issue by jmcconocha** [docker/for-win#1904]
Please, check https://docs.docker.com/docker-for-win/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have submitted Diagnostics
  - [x ] I have included the Diagnostics ID in this Issue
  - Windows Version: Win10 Ent. 64bit
  - Docker for Windows Version:
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:06:28 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.4
  Git commit:   0520e24
  Built:        Wed Mar 21 23:21:06 2018
  OS/Arch:      windows/amd64
  Experimental: false

### Expected behavior
Running nanoserver container

### Actual behavior
Download completes. Container never starts. Powershell or Command Terminal just hangs...

### Information
9E294426-099A-423D-9BAB-B8158420DD71/2018-03-30_16-41-18

### Steps to reproduce the behavior

  1. Install Docker for Windows
  2. Set for Windows Containers
  3. Run this Docker command: <docker run -it microsoft/nanoserver cmd>
  4. No more steps. No joy on the run...

--Console output--
PS C:\windows\system32> docker run -it microsoft/nanoserver cmd
Unable to find image 'microsoft/nanoserver:latest' locally
latest: Pulling from microsoft/nanoserver
bce2fbc256ea: Pull complete
5b557cd80a98: Pull complete
Digest: sha256:204c41542c0927ac0296802e44c56b886b47e99cf8220fb49
Status: Downloaded newer image for microsoft/nanoserver:latest

**Comment by malhotrav** [comment]
Windows Installer v18.03.0-ce-win59 hangs for me as well on Windows 10. Image attached for reference. Could you help with the resolution.

![docker-installation-hang](https://user-images.githubusercontent.com/36241180/38326145-a5b667f8-3862-11e8-81b8-38a72c00801c.png)

**Comment by jasonbivins** [comment]
@malhotrav @oyri 

These look like two separate errors unrelated to this one - please open a new issue with the details

**Comment by bayanr** [comment]
Just to add it's not slowness. I'm experiencing the same issue, even left the installer overnight and it was still hanging at that step. I cannot install docker and older installers don't seem to be available anywhere. I tried multiple times after rebooting with the same issue. It's extremely frustrating.

![image](https://user-images.githubusercontent.com/1216453/40978081-5eeff8f8-68db-11e8-993b-b6c92c45cebf.png)

**Comment by titovanton** [comment]
Same issue with me: win10 + docker for win
I'm using `docker-compose up` command and got to the kitchen for a break, after that, a restart of the docker makes it give any response on any command...

> I have installed 18.03.0-ce-win59 (16762) but after a short while all docker commands just hangs. Restarts docker damon and the same happens after a while. Have also tried to reboot windows several times. I have an existing swarm of docker services which tries to start its prosesses, but this never finishes before the docker commands starts to hang. Happens in a couple of minutes. Have windows 10 Enterprise.
