### ISSUE TITLE
Docker won't switch from Windows container to Linux 

### ISSUE THREAD

**Issue by Budsy** [docker/for-win#1905]
Please, check https://docs.docker.com/docker-for-win/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have submitted Diagnostics
  - [x ] I have included the Diagnostics ID in this Issue
  - Windows Version: Windows 10 PRO   Intel i7-6700k 4.2 GHz
  - Docker for Windows Version: 18.03.0-ce-win59 (16762)

### Expected behavior
Expect to be able to switch from Windows container to Linux
### Actual behavior
Error dialog... incompatible  OS version?
### Information
00A5FD90-30DC-432C-AD4F-C60A4B17097E/2018-03-30_22-18-52
### Steps to reproduce the behavior

  1. ... On my machine, use Docker quickstart menu to switch to Linux containers...
  2. ... wait, then Docker raises error dialog with message "Failed to switch because your Windows version is not compatible."

**Comment by Budsy** [comment]
I thought I set my machine's BIOS with virtualization configured, but I was mistaken. Issue solved.

**Comment by Budsy** [comment]
Yes, after correctly setting virtualization in the BIOS, now when I select the option to switch between Windows and Linux containers in the Docker control panel it works without error. I can run the kali-Linux-docker on my Windows 10 Dockers.

**Comment by hshivhare** [comment]
I was able to resolve this issue by disabling and then reenabling Hyper-V.

**Comment by nomansadiq11** [comment]
**Solved by enable the virtualization from BIOS**, I don't remember when I disabled this.
