### ISSUE TITLE
Feature Request: Docker-GUI shouldn't quit, when Hyper-V is not enabled.

### ISSUE THREAD

**Issue by itmuckel** [docker/for-win#1906]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have submitted Diagnostics
  - [ ] I have included the Diagnostics ID in this Issue
  - Windows Version: 10
  - Docker for Windows Version: 18.03.0-ce-win59 (16762)

### Expected behavior
When Docker finds Hyper V not enabled, it should keep running the GUI.

### Actual behavior
* Hyper V is not enabled
* Docker complains
* No, Docker, I don't want you to enable Hyper V
* I confirm the next Dialog saying that Docker cannot run this way
* **Actually I also want to change settings, so that Docker doesn't even start on startup anymore...**
* Docker quits

Now I have to google/find a configuration file where I can change this setting. Shouldn't be this way. 😄 
Enabling Hyper V, restarting, disabling Docker startup, disabling Hyper V, restarting felt so annoying, that I had to file this feature request. 😉

**Comment by jasonbivins** [comment]
Hi @itmuckel   Docker requires Hyper-V to run on Windows 10 - were you trying to uninstall Docker for WIndows?

**Comment by itmuckel** [comment]
Hey @jasonbivins!
I have Oracle's VirtualBox and Docker installed. Sometimes I use Docker very actively and don't need Hyper-V or Docker and sometimes I use VirtualBox a lot [which cannot run, when Hyper-V is activated](https://social.technet.microsoft.com/Forums/en-US/f89a6535-4026-433d-9bbc-fa6edc47e749/can-hyperv-and-virtualbox-coexist?forum=win10itprogeneral).

My solution now is that when I plan to use Virtual Box I first disable Docker and Hyper-V together and then restart.

So the issue is simply: If you have Hyper-V turned off and Docker is autostarting, there is no way to turn off autostart. It's only possible by enabling Hyper-V, restarting, changing Docker settings, disabling Hyper-V, restarting. That's all. 🙂

**Comment by G-Rath** [comment]
/lifecycle frozen

This issue shouldn't be closed, and closely relates to #3089. It's a very annoying and troubling issue, as it completely locks us out of docker settings (including the autostart settings) if we don't have hyper-v enabled.

**Comment by G-Rath** [comment]
/remove-lifecycle stale
/lifecycle frozen

This issue shouldn't be closed, and closely relates to #3089. It's a very annoying and troubling issue, as it completely locks us out of docker settings (including the autostart settings) if we don't have hyper-v enabled.

**Comment by riverar** [comment]
It's also important to note that lightweight process isolation does not rely on Hyper-V. This could really use a re-open (cc: @itmuckel)
