### ISSUE TITLE
Problem after uninstall Docker beta (aka deleting ProgramData\Docker)

### ISSUE THREAD

**Issue by cons0l3** [docker/for-win#191]
### Expected behavior
1) Uninstall of Docker for Windows removes C:\ProgramData\Docker directory.
2) Documentation on how to properly delete/remove C:\ProgramData\Docker after uninstall.

### Actual behavior

**!AFTER uninstall of Docker for Windows beta**

The folder C:\ProgramData\Docker is still existing. But almost 200 GB in Size. I need to clean up and remove. Everything is reproducable, as it is my development environment.

```
~> rd /S /Q C:\ProgramData\Docker 
[...]
Docker\windowsfilter\{LONG_HEX_NUMBER}\Files\Documents and Settings\All Users\AppData\AppData\AppData\.... Der Vorgang wurde erfolgreich beendet.
[...]
```
"Der Vorgang wurde erfolgreich beendet." translates into "The process has finished successfully." (weird, the files are still there...)

It seems that there is a link recursion in AppData? and **very freigtening it seems to link back to C:\Users\All Users\AppData!!!**

There is also access denies (as admin or booted under safe mode!):
``` 
~> icacls C:\ProgramData\Docker /reset /T /C
Docker\windowsfilter\{LONG_HEX_NUMBER}[...] access denied
[...]
```

### Information
λ docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

λ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.2-cs2-ws-beta
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Security Options:
Kernel Version: 10.0 14393 (14393.351.amd64fre.rs1_release_inmarket.161014-1755)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 11.99 GiB
Name: BLAUBEERE10
ID: ZUJM:NRJZ:TPN2:OCLO:4BSZ:CB2V:HWDZ:LIRK:V7AD:XPZL:IUM6:56CU
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

Additional environment details (AWS, VirtualBox, physical, etc.):
physical machine

**Comment by cons0l3** [comment]
same problem domain as #185

**Comment by rneugeba** [comment]
Hi @cons0l3 
thanks for the report. These are mostly the images used by Windows Containers. I agree we should remove them on un-install and on factory reset. @dgageot @simonferquel could you take a look?

**Comment by cons0l3** [comment]
the only work-around that did it for me:
1) create an empty directory e.g. C:\PURGE
2) boot into safe-mode
3) run `robocopy C:\PURGE C:\ProgramData\Docker /PURGE`
4) run `rd /S /Q C:\ProgramData\Docker`
5) reboot and rejoice ;-)

;tldr;
do not ask why, but the internet around msdn and technet said so... and if i could i would open an issue with Microsoft that their own tools such as rd/del/icacls work as expected on their filesystems.

**Comment by cons0l3** [comment]
if you want to move the C:\ProgramData\Docker folder to another disk (until we have the setting/option during install) e.g. to D:\Docker do the following:
1) uninstall Docker for Windows
2) remove ProgramData\Docker (see above comment)
3) install Docker for Windows and DO NOT START IT! 
4) Docker is running close it down/shut it off - or you will get files are open errors...
4) `robocopy C:\ProgramData\Docker D:\Docker /MIR /COPYALL`
5) `rmdir C:\ProgramData\Docker`
6) `mklink /D C:\ProgramData\Docker D:\Docker`
7) start Docker and run expirements.

later or in case you want to undo:

8) if you want to get rid of the directory junction created with `mklink` => `rd C:\ProgramData\Docker`. That only deletes the link and not the "real" directory or its content.

**Comment by rneugeba** [comment]
@cons0l3 thanks for the info. I actually have the same issue that I can't get rid of the data for other reasons). But normally you should be able to free up the disk space by just using `docker` commands as suggested https://github.com/docker/for-win/issues/192#issuecomment-257955714

**Comment by cons0l3** [comment]
@rneugeba I have tried this before uninstalling docker. As i recall a `docker rmi {HEX}` removed the image from the repository (`docker images` did not show the {HEX} image any more), but the files seemed to have not been properly removed from ProgramData\Docker\... 

I will retest.

**Comment by friism** [comment]
@rneugeba I discussed this with @jhowardmsft - he says the only safe way to remove images is with `docker rmi`.

**Comment by cons0l3** [comment]
so, the correct way to uninstall docker is to first `docker rmi` all the images? I was stuck with the ProgramData\Docker folder after executing the uninstall. After uninstall I do not have `docker rmi`... ;-)

**Comment by friism** [comment]
@cons0l3 yes, I know this is non-great, and we already have an internal issue tracking the problem.

**Comment by rneugeba** [comment]
The latest Beta (Beta34) now has  reset to factory option for Windows containers which removes container images and other artefacts and should significantly reduce disk space used. It does not completely remove the `C:\ProgramData\Docker` directory.

Doing this on uninstall is not going to be easy. As mentioned above the only safe way to do this is via `docker rmi` and the user may have already switched back to Linux containers, for example. Furthermore, the current uninstaller is pretty inflexible wrt to what we can do.

**Comment by jasonbivins** [comment]
Hi @cons0l3  Have you tried the docker prune -all command?
https://docs.docker.com/engine/reference/commandline/system_prune/

We do have an ehancement request in to handle folder cleanup a little better.

**Comment by lwansbrough** [comment]
This is fucking insanity!!! I've spent half an hour already trying to clear space on my HDD which is being _held hostage_ by Docker. I finally said fuck it, I'll just kill Docker. Uninstalled it, and it didn't clean up its fucking mess??????? Now you're telling me I have to reinstall Docker to remove files from my own computer??? Jesus Christ!!!
