### ISSUE TITLE
Unable to sign in via taskbar, proxy configured & signing in via cmd is successful

### ISSUE THREAD

**Issue by murugaratham** [docker/for-win#1910]
Please, check https://docs.docker.com/docker-for-win/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue
  - Windows Version: Windows 10 v1709
  - Docker for Windows Version: 17.12.0-ce

### Expected behavior
Can sign via taskbar
### Actual behavior
Says loading fail with no options to sign in 
![untitled](https://user-images.githubusercontent.com/653805/38179243-739da8fa-3653-11e8-9274-0c0f46c02c75.png)
### Information

Diagnostic Id: 23010741-62D9-4247-9BBE-10D322762069/2018-04-02_08-51-19

### Steps to reproduce the behavior

  1. Launch docker for windows
  2. Right click on icon
  3. Sees Loading failed

**Comment by jasonbivins** [comment]
Hi @murugaratham 
Normally we see this when there's no network connection - I can actually reproduce it on my laptop by turning off my wifi switch.  What are the results of a ```docker login``` command?

**Comment by murugaratham** [comment]
```
>docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username (murugaratham):
Password:
Login Succeeded
```
i am able to go online and do everything, but i am using cntlm, which i configured in settings (which i assume is for mobyVM), in my environment variables, i've also configured the same cntlm proxy. Is it due to the docker-for-windows not picking up the proxy settings?

**Comment by jasonbivins** [comment]
@murugaratham 
It definitely looks like Docker isn't picking up the proxy - when the menu loads like this it doesn't even detect a network connection. Have you entered the proxy information into the Settings menu?
![image](https://user-images.githubusercontent.com/28021664/38696176-69622666-3e5c-11e8-9c03-85101b933793.png)

**Comment by lmcarreiro** [comment]
@murugaratham I'm have a similar problem, but I'm getting a weird behavior of getting this success login message even when I provide wrong credentials... https://github.com/docker/for-win/issues/2074#issuecomment-393973126
When you log in, can you push images to your repository?
