### ISSUE TITLE
Can wrong OS family error be identified to improve the error message?

### ISSUE THREAD

**Issue by kasper3** [docker/for-win#1911]
Moved from https://github.com/moby/moby/issues/36773

On Windows, if docker is set to 'Windows container', and we try to run a Linux box, we get:

```
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: open \\.\pipe\docker_engine_windows
: The system cannot find the file specified.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
```

Can the reason be identified and user is instead (or additionally) alerted with:

> Please right-click docker icon in system tray and click 'Switch to Linux container...' in context menu

This sounds very GUI-centric, right? So perhaps we can introduce a command like `docker switch <os-family>`, so the direction for user works for both GUI and headless (win server core) scenarios.

**Comment by jasonbivins** [comment]
Hi @kasper3 
I wasn't able to get the same error you did when reproducing, but I was able to repro this
I entered it in as an enhancement request to help make the error messaging more helpful

**Comment by stephen-turner** [comment]
This has now moved to an upstream issue, moby/moby#36857, so I'm going to close this copy.
