### ISSUE TITLE
Remove --platform requirement

### ISSUE THREAD

**Issue by agowa338** [docker/for-win#1912]
Please, check https://docs.docker.com/docker-for-win/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [Edge] I have tried with the latest version of my channel (Stable or Edge)
  - Windows Version: 1803 (Build 17120.1)
  - Docker for Windows Version: 18.03.0-ce-win58 (16761)

### Expected behavior
When pulling a linux container on windows docker should not require the "--platform linux" parameter. The image should just be pulled if pulling linux images was enabled before/allowed.

### Actual behavior
```
latest: Pulling from library/alpine
no matching manifest for windows/amd64 in the manifest list entries
```

### Steps to reproduce the behavior

  1. Install Windows
  2. Install Docker
  3. run "docker pull alpine:latest"

**Comment by jasonbivins** [comment]
Hi @agowa338  In Docker for Windows, you can run Linux containers without the  --platform linux 
Right click the Whale icon - and choose Switch to Linux containers

![image](https://user-images.githubusercontent.com/28021664/38270126-82561122-3750-11e8-9586-09d4a1786e77.png)

**Comment by agowa338** [comment]
But than I cannot run Windows containers simultaneously.

**Comment by carlfischer1** [comment]
@agowa338 i think you are looking for https://github.com/moby/moby/pull/36418

**Comment by agowa338** [comment]
@carlfischer1 Can you please explain, why you think moby is related? Is it installed while installing Docker?

**Comment by carlfischer1** [comment]
@agowa338 that PR, when completed, will provide automated platform detection instead of having to specify a --platform value. 

The moby/moby project is upstream to Docker for Windows.
