### ISSUE TITLE
Win 10: Unable to pull microsoft/nanoserver. Receive permission problem on non-existent file

### ISSUE THREAD

**Issue by amracel** [docker/for-win#1916]
- [x ] I have tried with the latest version of my channel (Stable)
  - [x ] I have submitted Diagnostics
  - [x ] I have included the Diagnostics ID in this Issue
  - Windows Version: Windows 10 Enterprise
  - Docker for Windows Version: 18.03.0-ce-win59

### Expected behavior

Successful pull of microsoft/nanoserver

### Actual behavior

```
H:\>docker pull microsoft/nanoserver
Using default tag: latest
latest: Pulling from microsoft/nanoserver
bce2fbc256ea: Pull complete
5b557cd80a98: Extracting [==================================================>]    156MB/156MB
failed to register layer: re-exec error: exit status 1: output: open \\?\C:\ProgramData\Docker\tmp\hcs448587027\Files\Users\ContainerAdministrator\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup.$wcidirs$: Access is denied.
```
### Information
Diagnostic ID: 7F5C2B1E-A41A-4A7D-93C7-62718A2D3BE5/2018-04-04_16-24-38

The file requested, Startup.$wcdirs do not exist. There is a 'Start Menu\Programs\Startup' folder structure. But the Startup folder is empty.

I assume it's not actually a permissions issue, since the folder structure is created by the container.

### Steps to reproduce the behavior

  1.  run 'docker pull microsoft/naonserver

**Comment by jasonbivins** [comment]
@amracel 
Typically we see these kinds of errors when there is some type of scan running, AV or even VSS
does this run successfully?  ```docker run hello-world:nanoserver```

**Comment by amracel** [comment]
No. I receive the same error. Is there a way to narrow it down to see if it is a scanning error? We have Macafee and I cannot disable it.

**Comment by jasonbivins** [comment]
Hi @amracel
Do you get the same error if you use an elevated cmd prompt?  (right click- run as admin)
I do see several mentions of Mcaffee services in the logs - but nothing directly saying that they are blocking you. Are you able to exclude certain folders from the scan?  specifically \programdata\docker\windowsfilter

**Comment by amracel** [comment]
Yes, I have the same problem running in an elevated prompt. That's what led me to try to find an answer here in the first place.

No, unfortunately, I can't disable the scanning of any of the folders.

**Comment by jasonbivins** [comment]
At this point where it's failing - it's simply unpacking the Windows image inside the container. In this layer it's the file structure  that's getting delivered . ```\\?\C:\ProgramData\Docker\tmp\hcs448587027\Files\Users\ContainerAdministrator\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup.$wcidirs$```

**Comment by amracel** [comment]
I wonder if the file name with a ‘$’ in it is causing the issue then.

Here’s my attempt to run a ‘docker pull’ with a local account with admin privileges:

B112-26C5BE441F/2018-04-18_11-56-18

**Comment by amracel** [comment]
Sorry. Full log file name: C4FEC988-C538-47F2-B112-26C45BE441F5/2018-04-18_11-56-18
