### ISSUE TITLE
Please release v18.03.0

### ISSUE THREAD

**Issue by dhirschfeld** [docker/for-win#1917]
As it says in the title.

The latest available from https://download.docker.com/win/static/edge/x86_64/ is `17.10.0` which is 6 months out of date.

Similarly, the *"preview"* version available from PowerShell is also 6 months out of date:
```powershell
PS C:\> Find-Package -Name Docker -ProviderName DockerProvider -RequiredVersion preview

Name                           Version          Source           Summary
----                           -------          ------           -------
Docker                         17.10.0-ee-pr... Docker           Docker Enterprise Edition for Windows Server 2016 (Preview)
```

Since all versions up to and including `18.03.0` have been released for linux it seems like Windows is being treated as a bit of a 2nd class platform for docker.

**Comment by dhirschfeld** [comment]
***xref:*** #1460, #1599

**Comment by BrizzleRocker** [comment]
The downloads [here](https://docs.docker.com/docker-for-windows/install/) are the latest release (18.03) - I wouldn't bother personally as none of my installs worked after and I've rolled back to 17.12.10

**Comment by carlfischer1** [comment]
@dhirschfeld a bit of background:

Docker EE is supported on Windows Server, and current (yes, 17.06.*) releases can be installed [via Powershell](https://docs.docker.com/install/windows/docker-ee/#install-docker-ee). Note that is the same version of Docker EE available for Linux.

Docker CE, with a monthly Edge and quarterly Stable release cadence, is available for Windows 10 via Docker for Windows. There is no version of Docker CE for Windows Server, so there are no builds on https://download.docker.com.

It's known that the EE Preview version is out of date. We've deferred updating it in favor of plans to pull in the next release of Docker EE which should be what you want. Stay tuned.
