### ISSUE TITLE
Cant run docker on windows 10 enterprise latest build

### ISSUE THREAD

**Issue by Thorbenl** [docker/for-win#1920]
Hey.

Got a problem installing docker for windows 10 enterprise, latest build.
I downloaded a stable version. Double clicked to install (i am an admin overall) everything went fine until it came to the point of removing files in the installation. 

when i run a --quiet install from my terminal it suggests something with cannot make a shortcut on the desktop sth sth..i dont know any further

[Errors with regirstry](https://imgur.com/a/AuExB)

**Comment by jasonbivins** [comment]
@Thorbenl 
Does the install complete successfully if you right click - Run as admin?
