### ISSUE TITLE
docker daemon is not running.

### ISSUE THREAD

**Issue by kkumari-ptc** [docker/for-win#1922]
After restart of windows 10 enterprise getting following error:
C:\WINDOWS\system32>docker version
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:06:28 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.37/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

Also restarted the docker service.

**Comment by rn** [comment]
Are there any processes with `docker` or `Docker` running? Is there a tray icon you could use to upload diagnostics? Also, please follow the template we provide when filing an issue. Thanks

**Comment by jasonbivins** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id,
