### ISSUE TITLE
Docker won't start on win10 1803

### ISSUE THREAD

**Issue by zersiax** [docker/for-win#1927]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have submitted Diagnostics
  - [x ] I have included the Diagnostics ID in this Issue
  - Windows Version: Windows 10 1803
  - Docker for Windows Version: 18.03

### Expected behavior
Docker daemon starts normally
### Actual behavior
Docker attempts to start, but crashes with the error described in attached log file.
### Information

Diagnostics ID: 7307E659-4128-4582-AE1B-B34005A9990E/2018-04-08_14-26-28
Windows version: Windows 10 1803, build 17133.1

### Steps to reproduce the behavior

  1. Upgrade windows 10 1803 from home to professional using a product key.
  2.  Reboot.
3. Install Docker for Windows, either Stable or Edge give the same results.
4. Restart again.
5. Docker tries to start, but errors.
6. switch to Windows Containers. This works fine.
7. Switch back to Linux containers. This errors in a similar way to just trying to start, resulting in you getting stuck on Windows Containers.
8. Uninstall Docker for Windows, remove %appdata%\locale and \roaming Docker folders, as well as userdir\.docker.
9. Disable both HyperV and Containers from the "Turn Windows Features on and off" dialog.
10. Reboot, re-enable them. Reboot again.
11. In an elevated powershell command, run commands to enable hyperv and containers with the -all switch just for some added certainty.
12. Reinstall Docker.
13. Reboot.
14. Docker starts, once again in Linux Container mode ....and fails.
15. Pull hair out in frustration, grab your nearest container of strong liquor and give up.

I need this to work for my job, is there anyone over here who can see why this isn't working as advertised? I know very little about Docker and even less about HyperV, so I don't really have the know-how to debug this any further and I've already spent half my sunday on this to not have to spend hours doing this when I'm trying to actually get work done.
[docker_log.txt](https://github.com/docker/for-win/files/1887449/docker_log.txt)

**Comment by PascalKu** [comment]
Same issue here.

**Comment by nalpr** [comment]
1- I removed docker, disabled hyper-v , removed dockerNat adapter.
2- restarted windows .
3- reinstalled docker
4- enabled hyper-v. restarted windows

solved
I hope the best for you, been in same situation after update.

**Comment by ioagadmin** [comment]
I am about to update to v1803, is that 100% broken cause with Docker?

**Comment by jenslaufer** [comment]
Could not get docker working with v1803...downgraded to v1709

**Comment by Drumstix42** [comment]
Can confirm, this is a problem with upgrading to 1803. **However**, not all setups seem to run into the issue.

I followed @nalpr 's instructions exactly, and it got me back up and running. Thanks!

**Comment by r3dius** [comment]
@nalpr , thank you for this instructions. It deblocked my situation but can be embarassing when we have many packages to download.:/....

**Comment by nalpr** [comment]
@r3dius @Drumstix42  this happened again after another update.

I deleted all the hyper-v network adapters in device manager. solved the problem. without restarting or anything.

**Comment by ctgarvey** [comment]
I can  get the basic plain vanilla microsoft/iis image to spin up as  a docker (18.03.01)  windows container in Windows 10 enterprise 1803 but cannot access it via a mapped port on the host. Netstat -a reports the port state as SYN_SENT . ie no response from the server. I can access it on port 80. Theres something broken re the networking.  I can see the website only if i use the original http  TCP 80 port, and not the mapped port (8000, as per the example) .Any suggestions on how to fix the broken port mapping?  appreciated :-)

**Comment by pessimism** [comment]
Removing all Hyper-V Network adapters also worked for me without a restart.  Thank you @nalpr

**Comment by pessimism** [comment]
.. spoke too soon.  still only linux containers

**Comment by pessimism** [comment]
@nalpr s 4 step fix worked for me.  though when removing one of my hyper-v virtual switches i also encountered this obstacle removing it https://superuser.com/questions/1192492/how-to-remove-a-hyper-v-virtual-ethernet-switch  the solution there fixed that issue

**Comment by jycr** [comment]
We faced a similar problem with Windows 10 (build 1803) :

![image](https://user-images.githubusercontent.com/51145/45719040-63998600-bb9f-11e8-9122-0f43977021ba.png)

```
Échec de l’accès au magasin de configuration : Impossible de trouver un fournisseur de prise en charge de disque virtuel pour le fichier spécifié. (0xC03A0014).
à New-MobyLinuxVM, <Aucun fichier> : ligne 187
à <ScriptBlock>, <Aucun fichier> : ligne 394
   à Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) dans C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:ligne 36
   à Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) dans C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:ligne 77
   à Docker.Actions.<>c__DisplayClass16_0.<Start>b__0() dans C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:ligne 61
   à Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() dans C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:ligne 59
```
After diagnosing the Windows 10 environment, we noticed a problem with a driver called _Microsoft_VHD_ISO_VHBA_01_:
![image](https://user-images.githubusercontent.com/51145/45719105-92176100-bb9f-11e8-8d11-78fca6048dd0.png)

![image](https://user-images.githubusercontent.com/51145/45719138-ab201200-bb9f-11e8-882b-c205343e584f.png)


After updating the driver and restarting Docker, everything seems to be fixed.

**Comment by AnthonyCoughlin** [comment]
Hey All,

Not sure if this is related, but I ran into a similar issue where Docker-Machine would not load and deleting the Virtualbox adapter from the device manager fixed the issue.

Thanks for the help,
AnthonyC

**Comment by SetTrend** [comment]
Same issue here.

Today I set-up a fresh Windows 10x64 1809 VM, installed Docker for Windows and can't get the Linux container up running:

![can t start linux container](https://user-images.githubusercontent.com/9283914/50322384-1fd35700-04d5-11e9-9739-1fd91dcbee6a.png)

Switching to Windows containers works flawlessly, but switching back to the Linux container doesn't work.

I can't even access the Linux VM using Hyper-V Manager directly:

![can t start linux container](https://user-images.githubusercontent.com/9283914/50322455-44c7ca00-04d5-11e9-8899-eb3eb1b9f1c5.gif)
<br/>

The error message displayed by Hyper-V Manager is: "Video Remoting was disconnected".

**Comment by jbjhjm** [comment]
Problem still exists. Trying to reinstall Docker Desktop 2.3.0.2 because it crashed and reset to factory settings failed, too.
Uninstall has frozen. Reinstall fails as docker.iso / docker-desktop.iso cannot be deleted. Tried everything above, disabled hyper-v and its networks and devices. No success.
I'm now going to test to remove the files in safe mode.
ANNOYING, I must say. 
Seeing dozens of issue threads open for years (or auto-closed) the docker team should really take action :/
