### ISSUE TITLE
"docker pull" fails in windows 10

### ISSUE THREAD

**Issue by blacng** [docker/for-win#1928]
I followed the instructions [here ](https://tutorials.ubuntu.com/tutorial/tutorial-windows-ubuntu-hyperv-containers#0) to run linux container on windows. 

I entered this command in cmd (Ran as administrator):
```
C:\Users\USER\> set LCOW_SUPPORTED=1
C:\Users\USER> .\dockerd.exe -D --data-root C:\lcow
```

I also tried this command as suggested [here](https://github.com/docker/for-win/issues/1100):
`C:\Users\USER> .\dockerd.exe -D --experimental --data-root C:\lcow`

Then I entered this command in Windows Powershell (Ran as administrator):
`C:\Users\USER>  .\docker.exe pull ubuntu`

I also see this error message in cmd:

**ERRO: Resolver Setup/Start failed for container nat, "error in opening name server socket listen udp ... bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."**

  - [x] I have tried with the latest version of my channel (Stable)
  - Windows Version: Windows 10
  - Docker for Windows Version: Version 18.03.0-ce-win59 (16762)

### Expected behavior

- Pulling from library ubuntu

### Actual behavior
- no matching manifest for windows/amd64 in the manifest list entries

**Comment by rn** [comment]
With Docker for Windows you do not need to follow the instructions you reference (they are outdated in any case). If you switch, with the UI, to window containers you should see a pop up telling you how to use `LCOW` (there is no need to environment variables or starting the docker daemon manually).

then you can do:
```
docker pull --platform=linux ubuntu
```

Note, there is a PR for upstream `moby/moby` under review which will remove the need for the `--platform=linux` flag in the future.

I'm closing this issue. Let us know if you have additional quiestions/issues

**Comment by blacng** [comment]
Thank you @rn.
