### ISSUE TITLE
Docker run fails with 0xc0370106

### ISSUE THREAD

**Issue by kkla320** [docker/for-win#1929]
Please, check https://docs.docker.com/docker-for-win/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue
  - Windows Version: Windows 10 Enterprise 1709
  - Docker for Windows Version: 17.09.1-ce-win42 (14687)

### Expected behavior

I am expecting a running container.

### Actual behavior

I try to run a docker image but everytime the run command exits with the following message: 

> Error response from daemon: container e0df59b38ee914314d088c93616797c1da8a09304f9b8be75e004faad76f70ca encountered an error during Start: failure in a Windows system call (0xc0370106).

### Information
diagnostic ID: A3547D15-BB38-4DE8-A5DD-26BE124E8CB7/2018-04-09_13-04-25
The referenced diagnostics were created with docker vor windows 17.09.1-ce-win42 (14687). But I tried it also with 18.03.0-ce-win59 and the same error occurs.

### Steps to reproduce the behavior

I don´t know how to repoduce the issue on any other system. Probably something is wrong with my computer but I don´t have clue what it could be.

**Comment by rn** [comment]
what is the command? And I assume you are trying to run Windows containers (instead of Linux containers)?

**Comment by kkla320** [comment]
docker run --rm -it dockerhub.d-velop.de/minions/monitor_build:snapshot cmd

**Comment by rn** [comment]
can you run other images?

**Comment by kkla320** [comment]
After more trying I figured out that there are plenty of images that exit with the same error. But there are also images which execute successfully. 

I think #902 describes the same error. The images which crashes have plenty (about 30) of commands.

**Comment by szkxv6** [comment]
I've been having this same issue.  I'm currently using **Docker version 18.03.0-ce, build 0520e24**

**Comment by szkxv6** [comment]
Sorry, mega keypress mayhem then, I meant to add further information.
I'll need to investigate further, but the images I have difficulty with contain **VOLUME** commands - if those are taken out, it will run fine.

The initiating command doesn't need to include anything related to -v or --mount either - and yes, this is also for Windows Containers.

**Comment by kkla320** [comment]
@stephen-turner No, this does not explain the problem. If the VOLUME commands are taken out my image crashes anyways. 

I tried it with another image, the [microsoft/windowsservercore](https://hub.docker.com/r/microsoft/windowsservercore/) image, that works well with or without VOLUME commands.

**Comment by stephen-turner** [comment]
Hmm, in that case it sounds like your bug may not be the same as @szkxv6's, because they said theirs went away when the VOLUME commands were taken out. Just to confirm that I understood you correctly before, the exact same command runs successfully on other Windows machines?

**Comment by kkla320** [comment]
I agree with you in that case. As I mentioned before, the issue #902 describes the same error.

**Comment by stephen-turner** [comment]
Thanks. And does exactly the same command run successfully on other Windows machines?

**Comment by abezverkov** [comment]
I am getting the same behavior as @szkxv6.  The error goes away  if I comment the  VOLUME from the dockerfile

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:21:42 2018
  OS/Arch:      windows/amd64
  Experimental: false

**Comment by kkla320** [comment]
@stephen-turner The error appears on other windows machines as well. My colleague has the same error.

**Comment by skbasit** [comment]
I am facing same error, I narrowed it down to:
When a VOLUME is specified with a path that already exists in the image. Happens only for Windows Container (same thing works fine with linux container)

**Comment by TheFlow0360** [comment]
For me this happens when restarting an existing container with a volume.

    docker run -v myvolume:C:/mydirectory --name foobar -it microsoft/windowsservercore
    // doing stuff inside container, stopping (e.g. shutdown /s)...
    docker start -a -i foobar

The same happens when just running `docker create` and later `docker start`.

    Client: Docker Engine - Community
     Version:           18.09.2
     API version:       1.39
     Go version:        go1.10.8
     Git commit:        6247962
     Built:             Sun Feb 10 04:12:31 2019
     OS/Arch:           windows/amd64
     Experimental:      false
    
    Server: Docker Engine - Community
     Engine:
      Version:          18.09.2
      API version:      1.39 (minimum version 1.24)
      Go version:       go1.10.6
      Git commit:       6247962
      Built:            Sun Feb 10 04:28:48 2019
      OS/Arch:          windows/amd64
      Experimental:     false

**Comment by Asshiah** [comment]
For me it still happens today on up to date docker desktop 2.1.0.3 (38240) and windows 10 1803.17134.1006.

The error thrown is the following: 
> container 5f788e0a09cc489e0bf027ee1c7409c583a1f1775ebf9ad74c46bdfac1f9176c encountered an error during Start: failure in a Windows system call: The compute system exited unexpectedly. (0xc0370106)

I don't use any volume command in the docker file.

**Comment by gerwim** [comment]
> 
> 
> I am facing same error, I narrowed it down to:
> When a VOLUME is specified with a path that already exists in the image. Happens only for Windows Container (same thing works fine with linux container)

Yes, this seems to be the cause. When trying to mount a directory (or named volume) where this directory already exists, it crashes with 0xc0370106. My example docker-compose:
```
version: '3.4'

services:
  mssql:
    image: microsoft/mssql-server-windows-developer:2017-CU3
    volumes:
    - type: volume
      source: mssqldata
      target: c:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA
volumes:
  mssqldata:
```

/remove-lifecycle stale
