### ISSUE TITLE
Docker for Windows stuck to v1.12.1-stable build 7135

### ISSUE THREAD

**Issue by otravers** [docker/for-win#193]
### Expected behavior

I'd expect Docker for Windows to update Docker to 1.12.3 by now:
https://github.com/docker/docker/releases

### Actual behavior

I have checked "Check for updates when the application starts", but Docker for Windows doesn't tell me anything about new versions.

Docker for Windows also says it's up-to-date when I click on "Check for updates."

### Information

Windows 10 Pro

**Comment by dgageot** [comment]
Hi @otravers a stable release with docker 1.12.3 is planned at the end of this week

**Comment by dgageot** [comment]
@otravers 1.12.3 was release last week on stable channel.

**Comment by otravers** [comment]
Yes, I got it, and it solved the bash history problem that had motivated me to be waiting for this release specifically. You can indeed close this issue, thank you.
