### ISSUE TITLE
docker-machine create hyper-v problem

### ISSUE THREAD

**Issue by Stakman** [docker/for-win#1930]
Please, check https://docs.docker.com/docker-for-win/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have submitted Diagnostics
  - [x ] I have included the Diagnostics ID in this Issue
  - Windows Version: Version	10.0.15063 Build 15063
  - Docker for Windows Version: 18.03.0-ce

### Expected behavior
VM built
### Actual behavior
VM fails build with error -- Error with pre-create check: "Hyper-V PowerShell Module is not available"
notifying bugsnag: [Error with pre-create check: "Hyper-V PowerShell Module is not available"]
### Steps to reproduce the behavior

  1. ...run getting-started lab 4: docker-machine create -d hyperv --hyperv-virtual-switch "myswitch" myvm1

**Comment by rn** [comment]
This issue tracker is for the Docker for Windows application. Your error seems to be with `docker-machine` which is a separate and unrelated project. Please file an issue there.

However, it looks like you need to install the Hyper-V powershell modules. They typically come as an optional feature. You can check the list of installed feature with `Get-WindowsOptionalFeature -online` and the feature you are looking for should be `Microsoft-Hyper-V-Management-PowerShell`

**Comment by aeremin** [comment]
@Stakman I had similar issue yesterday. Have you able to connect to virtual machine host in Hyper-V application itself?

**Comment by Stakman** [comment]
Hyper-V management tools already enabled, but I will file  an issue with the proper project, although this appears to be a dup of #4424 there.

PS C:\> Get-WindowsOptionalFeature -Online -FeatureName *hyper-v* | select DisplayName, FeatureName, State

DisplayName                           FeatureName                               State
-----------                           -----------                               -----
Hyper-V                               Microsoft-Hyper-V-All                   Enabled
Hyper-V Management Tools              Microsoft-Hyper-V-Tools-All             Enabled
Hyper-V GUI Management Tools          Microsoft-Hyper-V-Management-Clients    Enabled
Hyper-V Module for Windows PowerShell Microsoft-Hyper-V-Management-PowerShell Enabled
Hyper-V Platform                      Microsoft-Hyper-V                       Enabled
Hyper-V Hypervisor                    Microsoft-Hyper-V-Hypervisor            Enabled
Hyper-V Services                      Microsoft-Hyper-V-Services              Enabled


@aeremin  The hyper V console appears to be working.  I can create VMs there but these do not show up in docker-machine ls
