### ISSUE TITLE
Modifying C:\Windows\System32\Drivers\etc\hosts prevents docker from listening on 2375

### ISSUE THREAD

**Issue by tonymet** [docker/for-win#1931]
## Overview
Adding an extra hostname like `127.0.0.1 localhost tonym.dev2` to my xxx\etc\hosts file prevents docker from listening on 2375

  - [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [ X] I have submitted Diagnostics
  - [X  ] I have included the Diagnostics ID in this Issue: 19F0A27A-5C99-493C-9E97-8550072F75BB/2018-04-09_15-44-23
  - Windows Version: 1709 16299.334
  - Docker for Windows Version  :Version 18.03.0-ce-win58 (16761)

### Expected behavior
Docker should listen on 2375 when using aliases in \etc\hosts

### Actual behavior
```
netstat -a -o|Select-String -Pattern 2375
[NO CONTENT]
```
### Information
Diagnostic id : 19F0A27A-5C99-493C-9E97-8550072F75BB/2018-04-09_15-44-23

```
netstat -a -o|Select-String -Pattern 2375 
```

### Steps to reproduce the behavior

  1.  Add alias to \etc\hosts e.g. `127.0.0.1 localhost tonym.dev2`
  2. Start docker
  3.  Activate "listen on 2375 unencrypted "
  4. Check netstat command above.

**Comment by jasonbivins** [comment]
Hi @tonymet 
I tested on a local machine and couldn't reproduce. It does look like there might be some conflicts though - it looks like another app is using 2375 as well.
```
[NVIDIA Web Helper.exe]
  TCP    127.0.0.1:2195         127.0.0.1:2375         ESTABLISHED     7084
 Can not obtain ownership information
  TCP    127.0.0.1:2197         127.0.0.1:2375         ESTABLISHED     7084
 Can not obtain ownership information
  TCP    127.0.0.1:2375         0.0.0.0:0              LISTENING       12076
 [com.docker.proxy.exe]
  TCP    127.0.0.1:2375         127.0.0.1:2195         ESTABLISHED     12076
 [com.docker.proxy.exe]
  TCP    127.0.0.1:2375         127.0.0.1:2197         ESTABLISHED     12076
 [com.docker.proxy.exe]
  TCP    127.0.0.1:4482         127.0.0.1:65001        ESTABLISHED     3000```

**Comment by tonymet** [comment]
@jasonbivins thanks for working to reproduce.  I'll leave this open for a day or so and then try to repro again if no one else experiences it.

**Comment by EnisG** [comment]
@tonymet I had the same issue, when I removed the extra entry in hosts file com.docker.proxy.exe started to listen on 2375 port. 

Version 18.03.1-ce-win65 (17513)
Channel: stable
93354b3
Windows version: 1709 - 16299.547

**Comment by auctionsjeff** [comment]
My company requires Kaspersky Endpoint Security on our machines. It turns out it was blocking access to the hosts file. Turning off "Host Intrusion Prevention" seems to fix it.
