### ISSUE TITLE
After stable channel update to 18.03.0 mem usage hits 100% when connecting via RDP

### ISSUE THREAD

**Issue by JOHNEPPILLAR** [docker/for-win#1932]
Please, check https://docs.docker.com/docker-for-win/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [Yes ] I have tried with the latest version of my channel (Stable or Edge)
  - [Yes] I have submitted Diagnostics
  - [Yes] I have included the Diagnostics ID in this Issue
  - Windows Version: Windows server 2016 - 10.0.14393 build 14393
  - Docker for Windows Version: Stable: 18.03.0-ce-win59(16762)

### Expected behavior
Normal docker vpnkit.exe mem usage with my containers running (linux node) is 18mb  
### Actual behavior
After recent upgrade to new ver and after around 24/48 usage the mem usage hits 100% when connecting via RDP. Looking at resource mon it's the vpnkit.exe service that has the mem leak
### Information

 id: E154BDF0-519B-469F-B5EE-35F305FEFF53/2018-04-10_06-49-36

### Steps to reproduce the behavior

  1. ...  Run docker
  2. ... Connect to windows machine via microsoft remote desktop RDP app after 24hrs. 
  3. ... Docker mem goes up to 100% and stays there until docker re-start

**Comment by jasonbivins** [comment]
@JOHNEPPILLAR 
Do you have any containers running when this happens?

**Comment by JOHNEPPILLAR** [comment]
I had the chance to rebuild my windows server host yesterday to see if this issue was a result of the host os. Unfortunately it was not. 

I have now reverted back to build: Docker Community Edition 17.12.0-ce-win47 2018-01-12 which does not have this problem.

**Comment by ericblade** [comment]
@JOHNEPPILLAR i haven't gone to revert anything yet, because it's shrinking for me once it hits 900, so it's not totally in my way, but I'm curious what you see for normal usage on vpnkit in 17.12 ?

**Comment by JOHNEPPILLAR** [comment]
@ericblade Since rolling back to 17.12 I now get a consistent 154mb. Before it would not stop at 900 but take all of the mem capacity and kill the box.

**Comment by ericblade** [comment]
I've had my whole machine locked up a couple of times (responds, slowly, to network pings, but nothing else responds, including local input devices) in the past week, could be related to memory exhaustion and thrashing from this.

**Comment by imarotte** [comment]
Linking to known vpnkit issue.  moby/vpnkit/issues/371

Are there instructions somewhere on how to build my our source so I can rollback to 17.12?

**Comment by ericblade** [comment]
I just picked up the update to 18.03.1, and initially, it doesn't seem to be doing it.  Running about 15 minutes so far, and vpnkit usage is chilling at 13.7 to 14.0MB.

I'll keep an eye on it.

**Comment by ericblade** [comment]
Nope, not fixed in 18.03.1, i just logged into the machine, and it was sitting at 700MB usage, with a note to please upgrade to 18.03.1-something newer.   So it didn't occur in the first 15 minutes or so that I was watching the machine, but sometime in the next 2 days after i let it go on it's own, it did.

**Comment by rn** [comment]
I'm closing this issue as this is on Windows Server and Docker for Windows is only supported on Windows 10.

I'm using RDP to access several Windows 10 machines with Docker for Windows and never had any issues.

Having said that, we are still interested getting to the bottom of this. I suggest to install the sysinternal Process Explorer as it is likely to provide you more detailed inside into memory/CPU usage.

**Comment by JOHNEPPILLAR** [comment]
So to confirm, if you want to use Docker on a windows server machine the only option is to use Docker EE?

**Comment by rn** [comment]
Yes, there is a free Docker EE Basic license with Windows Server.

Docker for Windows may work on Windows Server, but we do not test nor support.

**Comment by JOHNEPPILLAR** [comment]
Thanks. I will give the EE ver a go.

**Comment by ericblade** [comment]
... what?

Windows Server 2016 is a different SKU from 10, but they are the same core.  Also, this most definitely occurs outside of Windows Server, as my SKU is Win 10 Pro.  

The vpnkit included with Docker 18.03.x has a serious memory leak, and this is being closed because the original reporter is using a different Windows sku? .... what?

**Comment by rn** [comment]
@ericblade I have responded to the original post which runs on WIndows Server and there already is an upstream VPNKit issue.

**Comment by ericblade** [comment]
alright, makes sense.
