### ISSUE TITLE
ERROR: for {app}  Cannot start service {app}: container {container} encountered an error during Start: failure in a Windows system call: The compute system exited unexpectedly. (0xc0370106)

### ISSUE THREAD

**Issue by kondapaturisrinivasarao** [docker/for-win#1934]
ERROR: for dockercompose.....  Cannot start service ....: container .... encountered an error during Start: failure in a Windows system call: The compute system exited unexpectedly. (0xc0370106)
ERROR: for ....  Cannot start service ....: container .... encountered an error during Start: failure in a Windows system call: The compute system exited unexpectedly. (0xc0370106)
Encountered errors while bringing up the project.
Creating dockercompose... ... 
error : Creating dockercompose..... error
error : ERROR: for dockercompose...  Cannot start service ....: container .... encountered an error during Start: failure in a Windows system call: The compute system exited unexpectedly. (0xc0370106)
error : ERROR: for ...  Cannot start service ....: container .... encountered an error during Start: failure in a Windows system call: The compute system exited unexpectedly. (0xc0370106)
error : Encountered errors while bringing up the project..
error : 
error : For more troubleshooting information, go to http://aka.ms/DockerToolsTroubleshooting
Done building project "docker-compose.dcproj" -- FAILED.

Steps to reproduce
1.Run dockers on Windows containers(Not on Linux)
2.Create sample .net application
3.In the Docker-compose.yml file add volumes section.

sample :

version: '3'

services:
  {appname}:
    image: {imagename}
    volumes:
     - c:\{folder}\{subfolder}\:c:\app\data
    build:
      context: .
      dockerfile: {appname}\Dockerfile

**Comment by rn** [comment]
This does not look like an issue with the Docker for Windows application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place. Thanks
