### ISSUE TITLE
"readmode pipes not supported"

### ISSUE THREAD

**Issue by yorek** [docker/for-win#1937]
### Expected behavior

docker client from inside a windows container is able to connect to docker deamon running on the host via named pipes

### Actual behavior

docker return the followin error:
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/info: open //./pipe/docker_engine: message readmode pipes not supported In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

### Information
Diagnostic ID: 09D680EA-CE04-4DEF-BCCF-8A43674966C2/2018-04-10_17-51-47
Dockerfile: 
FROM microsoft/windowsservercore:1709 AS base

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ENV DESTINATION_FOLDER C:\\tools

WORKDIR /tmp

RUN $docker_url = ('https://download.docker.com/win/static/stable/x86_64/docker-17.09.0-ce.zip');\
    (New-Object System.Net.WebClient).DownloadFile($docker_url, '/tmp/docker.zip'); \
    $install_folder = Join-Path -Path $env:DESTINATION_FOLDER -ChildPath ''; \
    Expand-Archive -Path .\docker.zip -DestinationPath $install_folder; \
    Remove-Item ('{0}\docker\dockerd.exe' -f $env:DESTINATION_FOLDER)

FROM microsoft/powershell:6.0.2-nanoserver-1709

COPY --from=base ["tools", "tools"]

USER ContainerAdministrator  
RUN setx /M PATH "%PATH%;c:\tools\docker\;%ProgramFiles%\PowerShell;"

SHELL ["pwsh.exe", "-Command"]

### Steps to reproduce the behavior

1) create an image with the provided dockerfile
2) run the container: docker run -it -v \\\\.\pipe\docker_engine:\\\\.\pipe\docker_engine myimage
3) from inside the container run: docker info

**Comment by kepboy** [comment]
I suspect this is something to do with permissions on the named pipe.  And the dockerd process not having the required permissions to right to it.  Either permissions on the pipe or the pipe handle isn't duplicated correctly

**Comment by jsturtevant** [comment]
Looks like it was due to running on windows 10 with hyperv.  Will probably work if host is 1709 server and no hyperv.  See issue: https://github.com/moby/moby/issues/36562

Looks like insider builds and 1803 will resolve issue 🤞

**Comment by jsturtevant** [comment]
When I ran it on a 1709 Server I was not able to get it to work either.  I ran into the same as this issue: https://github.com/moby/moby/issues/36819

**Comment by StefanScherer** [comment]
This command works for me from my Mac targeting a Windows Server 1709 running the Docker engine 17.10.0-ee-preview-3.
The command also works directly on the Server 1709 both in cmd and PowerShell. I use the unix slashes on Mac to avoid quotes.
The server VM is created with the steps shown in my [windows-docker-machine](https://github.com/StefanScherer/windows-docker-machine) repo.

```
$ docker run -v //./pipe/docker_engine://./pipe/docker_engine -u ContainerAdministrator stefanscherer/docker-cli-windows:18.03.0-ce docker version
Client:
 Version:	18.03.0-ce
 API version:	1.34 (downgraded from 1.37)
 Go version:	go1.9.4
 Git commit:	0520e24302
 Built:	Fri Mar 23 08:31:36 2018
 OS/Arch:	windows/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	17.10.0-ee-preview-3
  API version:	1.34 (minimum version 1.15)
  Go version:	go1.8.4
  Git commit:	b8571fd
  Built:	Fri Oct  6 18:01:48 2017
  OS/Arch:	windows/amd64
  Experimental:	false
```

**Comment by jsturtevant** [comment]
On a VM in Azure I ran:

```
C:\Users\azureuser>  docker run -v //./pipe/docker_engine://./pipe/docker_engine -u ContainerAdministrator stefanscherer/docker-cli-windows:18.03.0-ce docker version
docker: Error response from daemon: invalid bind mount spec "//./pipe/docker_engine://./pipe/docker_engine": invalid volume specification: '\\.\pipe\docker_engine:\\.\pipe\docker_engine'.
See 'docker run --help'.

C:\Users\azureuser>ver

Microsoft Windows [Version 10.0.16299.248]

C:\Users\azureuser>docker version
Client:
 Version:      17.06.2-ee-6
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   e75fdb8
 Built:        Mon Nov 27 22:46:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.2-ee-6
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   e75fdb8
 Built:        Mon Nov 27 22:55:16 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

I updated the docker version with `Install-Package Docker -ProviderName DockerMsftProvider -Force` and still get:

```
 docker version
Client:
 Version:       17.06.2-ee-7
 API version:   1.30
 Go version:    go1.8.7
 Git commit:    925df35
 Built: Fri Mar 16 22:29:37 2018
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.06.2-ee-7
  API version:  1.30 (minimum version 1.24)
  Go version:   go1.8.7
  Git commit:   925df35
  Built:        Fri Mar 16 22:39:05 2018
  OS/Arch:      windows/amd64
  Experimental: false
PS C:\Users\azureuser> docker run -v //./pipe/docker_engine://./pipe/docker_engine -u ContainerAdministrator stefansche
rer/docker-cli-windows:18.03.0-ce docker version
C:\Program Files\Docker\docker.exe: Error response from daemon: invalid bind mount spec "//./pipe/docker_engine://./pipe/docker_engine": invalid volume specification: '\\.\pipe\docker_engine:\\.\pipe\docker_engine'.
See 'C:\Program Files\Docker\docker.exe run --help'.
```

I did not find a preview version using `Find-Package -Name Docker -ProviderName DockerMsftProvider -AllVersions`:

```
Find-Package -Name Docker -ProviderName DockerMsftProvider -AllVersions

Name                           Version          Source           Summary
----                           -------          ------           -------
Docker                         1.12.2-cs1       DockerDefault    Contains the CS Docker Engine for use with Windows...
Docker                         1.13.1-cs1       DockerDefault    Contains the CS Docker Engine for use with Windows...
Docker                         17.03.0-ee       DockerDefault    Contains Docker EE for use with Windows Server.
Docker                         17.03.1-ee       DockerDefault    Contains Docker EE for use with Windows Server.
Docker                         17.03.2-ee-5     DockerDefault    Contains Docker EE for use with Windows Server.
Docker                         17.06.2-ee-7     DockerDefault    Contains Docker EE for use with Windows Server.
Docker                         17.06.1-ee-2     DockerDefault    Contains the latest Docker EE for use with Windows...
Docker                         17.06.2-ee-5     DockerDefault    Contains Docker EE for use with Windows Server.
Docker                         17.06.2-ee-7     DockerDefault    Contains Docker EE for use with Windows Server.
Docker                         17.06.0-ce       DockerDefault    This is the latest CE version of docker
Docker                         17.06.2-ee-8-rc1 DockerDefault    This is a test
```

**Comment by rn** [comment]
This issue is with the upstream docker windows container implementation. This tracker is for the Docker for Window application, so i'm closing this here. Please check the exiting issues on  https://github.com/moby/moby or create a new issue there.
Thanks

**Comment by yorek** [comment]
Done: https://github.com/docker/for-win/issues/1937
