### ISSUE TITLE
Invalid reference format when starting docker container

### ISSUE THREAD

**Issue by cookiejest** [docker/for-win#1943]
Hey I am having issues with invalid reference format when I try and start this docker container using the command on docker for windows. Any ideas?

docker run -p 9077:9076 -v $(pwd)/data:/data -d qlikcore/engine:12.160.0 -S DocumentDirectory=/data -S AcceptEULA=yes

**Comment by jasonbivins** [comment]
Hi @cookiejest   I'm not aware of any flags for -S
