### ISSUE TITLE
Docker for windows issues

### ISSUE THREAD

**Issue by adityaamb** [docker/for-win#1945]
Please, check https://docs.docker.com/docker-for-win/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [ ] I have tried with the latest version of my channel (Stable )
  - [ ] I have submitted Diagnostics
  - [ ] I have included the Diagnostics ID in this Issue
  - Windows Version: Windows 10 pro
  - Docker for Windows Version: 18.03

I am trying docker commands like ocker info or docker create machine..none of them are working.
### Expected behavior
Give output based on command
### Actual behavior
Throwing error: 
docker : error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.37/version: open //./pipe/docker_engine: The system cannot find the file specified. In the 
default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
At line:1 char:1
+ docker version
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (error during co...is not running.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
### Steps to reproduce the behavior

  1. ...Install docker for windows
  2. ...OPen command window and run docker info

**Comment by jasonbivins** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id

**Comment by adityaamb** [comment]
What additional information do you need?
I already posted the error I am getting, the version I am working with and steps to reproduce.

**Comment by kenorb** [comment]
Make sure you ran the Desktop app and it's running properly.
