### ISSUE TITLE
docker pull ubuntu -> no matching manifest for windows/amd64

### ISSUE THREAD

**Issue by mmatrosov** [docker/for-win#1949]
I was following steps in this tutorial: https://docs.docker.com/docker-for-windows/

Everything worked fine until I tried to pull ubuntu image:

    C:\Users\Mikhail>docker pull ubuntu
    Using default tag: latest
    latest: Pulling from library/ubuntu
    no matching manifest for windows/amd64 in the manifest list entries

I tried everything from https://github.com/docker/for-win/issues/1100, I enabled experimental features, but result is still the same.

### Expected behavior

I have ubuntu image installed.

### Actual behavior

I get error `no matching manifest for windows/amd64 in the manifest list entries`.

### Information

    Microsoft Windows [Version 10.0.16299.371]

    C:\Users\Mikhail>docker version
    Client:
     Version:       18.03.0-ce
     API version:   1.37
     Go version:    go1.9.4
     Git commit:    0520e24
     Built: Wed Mar 21 23:06:28 2018
     OS/Arch:       windows/amd64
     Experimental:  false
     Orchestrator:  swarm

    Server:
     Engine:
      Version:      18.03.0-ce
      API version:  1.37 (minimum version 1.24)
      Go version:   go1.9.4
      Git commit:   0520e24
      Built:        Wed Mar 21 23:21:06 2018
      OS/Arch:      windows/amd64
      Experimental: true

    C:\Users\Mikhail>docker info
    Containers: 1
     Running: 0
     Paused: 0
     Stopped: 1
    Images: 1
    Server Version: 18.03.0-ce
    Storage Driver: windowsfilter (windows) lcow (linux)
     Windows:
     LCOW:
    Logging Driver: json-file
    Plugins:
     Volume: local
     Network: ics l2bridge l2tunnel nat null overlay transparent
     Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
    Swarm: inactive
    Default Isolation: hyperv
    Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
    Operating System: Windows 10 Pro
    OSType: windows
    Architecture: x86_64
    CPUs: 8
    Total Memory: 15.89GiB
    Name: Mikhail-PC
    ID: GFG5:IK5E:TK2T:QM5V:YSWC:HKYD:JOML:6EC6:ARZX:4MKW:UYES:D4DH
    Docker Root Dir: C:\ProgramData\Docker
    Debug Mode (client): false
    Debug Mode (server): true
     File Descriptors: -1
     Goroutines: 25
     System Time: 2018-04-14T19:18:03.7983648+03:00
     EventsListeners: 1
    Registry: https://index.docker.io/v1/
    Labels:
    Experimental: true
    Insecure Registries:
     127.0.0.0/8
    Live Restore Enabled: false

### Steps to reproduce the behavior

Follow steps in this tutorial: https://docs.docker.com/docker-for-windows/

**Comment by sanrioalvares** [comment]
I'm not sure why this worked, but the following command did it for me:
> docker.exe pull --platform linux ubuntu 

The docker daemon is set to "Switch to Windows containers".

**Comment by mmatrosov** [comment]
Well, yes, when I switched to Linux containers, it also worked. But I assumed I am better using Windows containers when I am on Windows.

**Comment by jasonbivins** [comment]
@mmatrosov   This error means that you're in Windows mode, trying to pull a Linux container - it's a confusing message - but easily fixed by right clicking the Docker Icon and choosing Linux containers

**Comment by mmatrosov** [comment]
@jasonbivins I'm sorry, I am new to docker, and it is not clear for me: is it even possible to have a "Windows mode" container with Linux?
