### ISSUE TITLE
Docker Images are deleted automaticaly after rebooting the Virtualbox/system

### ISSUE THREAD

**Issue by ranjithprethan** [docker/for-win#1952]
Hi, I have installed docker toolbox on window 7 machine. 
I am able to pull the images from docker hub and run it on docker.
However, when I restart my laptop/ virtualbox - docker daemon , the images are disappeared/deleted automatically.

Any help, is much appreciated.

-Ranjith

**Comment by rn** [comment]
This tracker is for Docker for Window, which is a Windows 10 application. For toolbox issues please use https://github.com/docker/toolbox
