### ISSUE TITLE
How to simply enable Docker for Windows TLS?

### ISSUE THREAD

**Issue by rwmajor2** [docker/for-win#1953]
I am sorry for such a basic question.  I have downloaded and installed Dockers CE on Windows 10 Version 18.03.0-ce-win59 (16762).  

I need to enable tcp://localhost:2376 access so a Java Client can talk to the API, but over TLS.  Can someone provide simple instructions on how to do this?  I just can't seem to find the definitive answer.  When I try something I think should work, Docker fails to start.  I have tried adding this in the System Tray Docker Settings:
```json
{
  "tls": true,
  "tlscert ": "c:/certs/cert.pem",
  "tlskey": "c:/certs/private.key"
}
```

**Comment by jasonbivins** [comment]
@rwmajor2    I can reproduce the crash, can you provide a diagnostic ID so that I can compare logs?

**Comment by Mart-Bogdan** [comment]
/remove-lifecycle stale

It's seems still relevant.
I want to enable TLS in my docker.

**Comment by dpeger** [comment]
/remove-lifecycle stale

Still valid:

Docker Desktop
Version: 2.0.0.0-win81 (29211)
Built: 4271b9e

Engine: 18.09.0

**Comment by kekru** [comment]
As an alternative approach, you can expose the remote api via a container.
See https://github.com/kekru/docker-remote-api-tls

**Comment by zxyabsent** [comment]
> As an alternative approach, you can expose the remote api via a container.
> See https://github.com/kekru/docker-remote-api-tls

Hello keru, by "alternative" do you mean this has been a long lasting issue but remains unresolved? I ran into this problem as well. Docker cannot find the .pem files even though I can open them directly on terminal.

**Comment by kekru** [comment]
Yes, this is a long lasting issue, but ni progress, as far as I know. See also https://github.com/docker/for-win/issues/453
