### ISSUE TITLE
USER instruction appears to be ignored for LCOW

### ISSUE THREAD

**Issue by solvingj** [docker/for-win#1955]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have submitted Diagnostics
  - [X] I have included the Diagnostics ID in this Issue:
0CA869F4-9932-4EF4-9E87-07050E3FA6BF/2018-04-16_08-32-16

  - Windows Version:  
Windows 10 Pro for Workstations Insider Preview : 1803 (17639.1000)
  - Docker for Windows Version:  
Version 18.04.0-ce-win62 (17151)
Channel: edge
e0a85f6

### Expected behavior
Given the Dockerfile below, the CMD `whoami` should print the username `testuser`, but instead, it shows that the user is `root`.  Additionally, adding a RUN or CMD instruction at the end to su testuser has no effect. You also cannot pass `su testuser` in the command as in docker run `... /bin/sh -c 'su testuser && whoami'` . `whoami` will again print root.  I have also tried running detached and reattaching after running  It seems there is something in docker for windows which forces the user to be root upon entry.  The only way to perform an operation as a specific user is in an interactive terminal, where `su testuser` works as expected. 

Dockerfile
```
FROM ubuntu:trusty

RUN useradd -ms /bin/bash testuser \
    && printf "testuser:testuser" | chpasswd \
    && adduser testuser sudo \
    && printf "testuser ALL= NOPASSWD: ALL\\n" >> /etc/sudoers

USER testuser
RUN whoami
CMD whoami
```

Build Log
```
c:\Users\me\Desktop>docker build . --platform=linux -t dockeruserfail
Sending build context to Docker daemon  103.4kB
Step 1/5 : FROM ubuntu:trusty
 ---> 3b853789146f
Step 2/5 : RUN useradd -ms /bin/bash testuser     && printf "testuser:testuser" | chpasswd     && adduser testuser sudo     && printf "testuser ALL= NOPASSWD: ALL\\n" >> /etc/sudoers
 ---> Using cache
 ---> b86bffa2a6bf
Step 3/5 : USER testuser
 ---> Using cache
 ---> 94849a0d376c
Step 4/5 : RUN whoami
 ---> Using cache
 ---> d63f59ce1c1e
Step 5/5 : CMD whoami
 ---> Using cache
 ---> e35c44ded873
Successfully built e35c44ded873
Successfully tagged dockeruserfail:latest
```

Runlog
```
c:\Users\me\Desktop>docker run dockeruserfail
root
```

**Comment by rn** [comment]
Thanks for reporting. This is a known issue with LCOW, which is tracked already tracked upstream: https://github.com/moby/moby/issues/36469
Closing
