### ISSUE TITLE
"docker for win10" how to open ssh?

### ISSUE THREAD

**Issue by dongasai** [docker/for-win#1956]
I want to perform some personalized operations on virtual machines in ssh?

Version 18.03.0-ce-win59 (16762)
Channel: stable

**Comment by jasonbivins** [comment]
https://docs.docker.com/machine/reference/ssh/

**Comment by dongasai** [comment]
I think you misunderstood me.
See figure



https://github.com/dongasai/note/blob/master/QQ图片20180516085857.png
