### ISSUE TITLE
Unable to Save image on Windows Server 2016, with docker version 18.03.0-ce. 

### ISSUE THREAD

**Issue by XtineInWa** [docker/for-win#1958]
Please, check https://docs.docker.com/docker-for-win/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have submitted Diagnostics
  - [ ] I have included the Diagnostics ID in this Issue
  - Windows Version: Windows Server 2016
  - Docker for Windows Version:  Docker 18.03.0-ce

### Expected behavior
docker image command should complete and a tar file be generated as a copied image

### Actual behavior
So far, I've left it alone for an hour and it still hasn't returned to a prompt (finished saving to tar file). I found the temporary files under ProgramData/Docker/tmp and see that their sizes has increased super slowly, but it has finally reached the 13.2 GB size and is not increasing.... This image very base image is SQL Express. Any ideas on why it is taking over an hour and still hasn't saved to a completed tar file? Thanks! to Unable to Save image on Windows Server 2016, with docker version 18.03.0-ce. I've tried unsuccessfully to save an image that is a committed copy of a sql express container. So far, I've left it alone for over an hour and it still hasn't returned to a prompt (finished saving to tar file). I found the temporary files under ProgramData/Docker/tmp and see that their sizes has increased super slowly, but it has finally reached the 13.2 GB size and is not increasing.... This image base image is SQL Express. Any ideas on why it is taking over an hour and still hasn't saved to a completed tar file? Before I commited the container, I added only two small tables to SQL Express. I have turned off all SQL services in Task Manager/Services just in case they are stomping on this copy job, but this doesn't help any.

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by gtardif** [comment]
Docker for Windows runs on Windows10. You are using Windows Server, you should use Docker EE Basic instead. For more details on docker on Windows Server, please look at http://success.docker.com/article/where-to-get-help-with-windows.
Thanks
