### ISSUE TITLE
Cannot create network in Windows container mode

### ISSUE THREAD

**Issue by KevM** [docker/for-win#1960]
Please, check https://docs.docker.com/docker-for-win/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [ X] I have tried with the latest version of my channel (Stable or Edge)
  - [ X] I have submitted Diagnostics
  - [ X] I have included the Diagnostics ID in this Issue
  - Windows Version: 1709 (OS Build 16299.371)
  - Docker for Windows Version: 18.04.0-ce-win62 (build 3d479c0)

### Expected behavior

Creating a network when in windows container mode should work without error. This works correctly when in Linus container mode.

### Actual behavior

```
> docker network create foo
```
> Error response from daemon: could not find plugin bridge in v1 plugin registry: plugin not found

### Information

Diagnostic Id: **D328A056-EE5B-4784-AE5E-D0CB52167DE4/2018-04-17_15-14-14**

### Steps to reproduce the behavior

  1. Switch to windows container mode.
  2. `docker network create mynet`

**Comment by jasonbivins** [comment]
@KevM 
Thanks for reporting! - I can repro on stable and edge so this has been reported as a bug

**Comment by marten-gustafsson-blinfo-se** [comment]
I can confirm. Windows 2016 server in Hyper-V
```
> docker network create --driver bridge ce-net --subnet=192.168.111.0/24
Error response from daemon: plugin not found
> docker --version
Docker version 17.06.2-ee-8, build 4e8ed51
> [System.Environment]::OSVersion.Version
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      14393  0
```

**Comment by jasonbivins** [comment]
@marten-gustafsson-blinfo-se 
Can you try again with a different driver?  bridge drivers aren't mentioned in the docs: https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-networking

**Comment by marten-gustafsson-blinfo-se** [comment]
```
> docker network create --driver nat --subnet=192.168.111.0/24 ce-net
Error response from daemon: HNS failed with error : Unspecified error
```

**Comment by marten-gustafsson-blinfo-se** [comment]
```
> docker network create help
Error response from daemon: plugin not found
```
:-)

**Comment by marten-gustafsson-blinfo-se** [comment]
`Although we continue to add new features and drive development, some of these features will not be back-ported to older platforms. Instead, the best plan of action is to "get on the train" for latest updates to Windows 10 and Windows Server. `

Too bad. Docker on Windows server works. Docker on Windows 10 is too buggy.

**Comment by KevM** [comment]
> Although we continue to add new features and drive development, some of these features will not be back-ported to older platforms. Instead, the best plan of action is to "get on the train" for latest updates to Windows 10

I don't mind "getting on the train" do you have a link to a resource where these trains are discussed? So we can get on them? 🚋 📆

**Comment by KevM** [comment]
Found the source of your quote. Maybe it will be helpful to someone.

https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-networking#windows-server-2016-work-arounds

**Comment by zongmi** [comment]
- Windows Version: 1803 (OS Build 17134.1)
- Docker for Windows Version: 18.04.0-ce-win62 (build 3d479c0)

`>  docker network ls`

> NETWORK ID          NAME                DRIVER              SCOPE
cd23685dc007        nat                 nat                 local
32e395bbfdbe        none                null                local
ccc02ba9a9ed        test_default        nat                 local
a4639042fcea        默认交换机               ics                 local

`>  docker network create my_net`

> Error response from daemon: could not find plugin bridge in v1 plugin registry: plugin not found

`>  docker plugin ls`

>Error response from daemon: plugins are not supported on this platform

**Comment by rbanhatti** [comment]
PS C:\Users\splunker\Documents\Workspace\ml-app\test\ml_app\ml_spl\ml_spl_distributed> docker-compose up -d --build
Creating network "ml_spl_distributed_mltk_distributed" with driver "bridge"
ERROR: could not find plugin bridge in v1 plugin registry: plugin not found
PS C:\Users\splunker\Documents\Workspace\ml-app\test\ml_app\ml_spl\ml_spl_distributed> docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
52093e16e6dc        Default Switch      ics                 local
6e225ed61db7        nat                 nat                 local
a907dfd0b011        none                null                local
PS C:\Users\splunker\Documents\Workspace\ml-app\test\ml_app\ml_spl\ml_spl_distributed> docker network create my_net
Error response from daemon: could not find plugin bridge in v1 plugin registry: plugin not found
PS C:\Users\splunker\Documents\Workspace\ml-app\test\ml_app\ml_spl\ml_spl_distributed> docker plugin ls
Error response from daemon: plugins are not supported on this platform
PS C:\Users\splunker\Documents\Workspace\ml-app\test\ml_app\ml_spl\ml_spl_distributed> docker --version
Docker version 18.03.1-ce, build 9ee9f40
PS C:\Users\splunker\Documents\Workspace\ml-app\test\ml_app\ml_spl\ml_spl_distributed> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      16299  0

**Comment by rbanhatti** [comment]
Any idea when the bug will be addressed? We are in need of this functionality :)

**Comment by MilesHart** [comment]
Any updates?

**Comment by ronaldclambert** [comment]
I was able to create a network on windows 10 using docker version:
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:21:42 2018
  OS/Arch:      windows/amd64
  Experimental: false
And the following steps: 
PS C:\Users\ron> docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
3bc504fbefe1        Default Switch      ics                 local
6a5f7a74139d        nat                 nat                 local
a913d528180a        none                null                local
PS C:\Users\ron> Get-VMSwitch

Name           SwitchType NetAdapterInterfaceDescription
----           ---------- ------------------------------
nat            Internal
Default Switch Internal


PS C:\Users\ron> docker network create -d nat dsocktnet
1c598dc7fca1a9b978997cc9fc457bc1c636e9964fe7315575c0ba393ab9954a
PS C:\Users\ron> docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
3bc504fbefe1        Default Switch      ics                 local
1c598dc7fca1        dsocktnet           nat                 local
6a5f7a74139d        nat                 nat                 local
a913d528180a        none                null                local
The challenge I am having is that I cannot seem to map and exposed port from the container to the host. I was able to create and start a container on the network using the following steps:
PS C:\Users\ron> docker container create --network dsocktnet -p 80:80 --name socktestc 0cb57fdc655e
562eff96e3711eba652851286a1a5cd21b303fc8e822a9598ab19a17ae915ce0
PS C:\Users\ron> docker start socktestc
Socktestc
But when I change netstat on the host I do not see anything listening on port 80. Perhaps I need to us a different hyper-V driver?
All The Best
Ron. L.

**Comment by andersson83** [comment]
any updates???

**Comment by yolpsoftware** [comment]
When I include a specific driver parameter in the call, it seems to work:

docker network create -d ics mynetwork

However, without the "-d ics", I'm having the same error:

docker network create mynetwork

**Comment by thavoo** [comment]
```
PS C:\Users\thavoo\webapp\laradock> docker network ls
NETWORK ID          NAME                         DRIVER              SCOPE
be15c7f94933        Modificador predeterminado   ics                 local
b509cf61adbe        nat                          nat                 local
21ef9b5017df        none                         null                local
PS C:\Users\thavoo\webapp\laradock> docker network create my_net
Error response from daemon: could not find plugin bridge in v1 plugin registry: plugin not found
PS C:\Users\thavoo\webapp\laradock> docker plugin ls
Error response from daemon: plugins are not supported on this platform
PS C:\Users\thavoo\webapp\laradock> docker network create -d ics mynet
0720c3c729b08a9a3a617cc943ec6cd80e7b863eb5a68cc0eb2c6642e1b135b7
PS C:\Users\thavoo\webapp\laradock> docker-compose up -d nginx mysql phpmyadmin
Creating network "laradock_frontend" with driver "bridge"
ERROR: could not find plugin bridge in v1 plugin registry: plugin not found
PS C:\Users\thavoo\webapp\laradock> docker network ls
NETWORK ID          NAME                         DRIVER              SCOPE
be15c7f94933        Modificador predeterminado   ics                 local
0720c3c729b0        mynet                        ics                 local
b509cf61adbe        nat                          nat                 local
21ef9b5017df        none                         null                local
```

**Comment by ngocleek** [comment]
I was able to fix this issue on my Windows 10 by the switch back to Linux containers.

**Comment by samayo** [comment]
@ngocleek  answered solved the issue. Why does docker default to win containers anyway? are there more people using that instead of linux containers?

**Comment by chetanchougle** [comment]
@samayo  Yes we use windows containers with windows host server . Is there anyway to use this one windows containers

**Comment by chetanchougle** [comment]
This is such a dead end for docker tools .Any updates ?

**Comment by Noblaze05** [comment]
By switching in linux containers seems to work find. Any updates on windows containers?

**Comment by TheCWater** [comment]
Still doesn't work with Windows containers

**Comment by ta32** [comment]
It looks like bridge mode is not supported for docker networks in windows?
https://docs.microsoft.com/en-us/virtualization/windowscontainers/container-networking/network-drivers-topologies

**Comment by ggirard07** [comment]
@AirMaxVII not sure `transparent` is the equivalent of `bridge` according to the doc you are referring to. `nat` seems a better fit and is the default on Windows container.

**Comment by wadoodrahimi** [comment]
Hello evryone,

I ran docker CE version 18.09.1 stable on Window 10 pro version 1809 and I activated the Swarm mode. I can create service but I can not connect to Overlay Network.

docker service create -d --name web --endpoint-mode dnsrr --publish mode=host,target=80,published=80 microsoft/iis

it works!

but if I try to connect to an Overlay Network it fails

docker service create -d --name web --endpoint-mode dnsrr --publish mode=host,target=80,published=80 --network my-net microsoft/iis

The error is: Hns failed with error : an adapter was not found

Here are the Networks:

NETWORK ID NAME DRIVER SCOPE

d1d1547a5d5e Standardswitch ics local

b3ad81976542 host transparent local

b5i0zkys9nsj ingress overlay swarm

5d0212aab409 nat nat local

ydkbf4vfnkqh my-net overlay swarm

039bdb7cc276 none null local

**Comment by Ritzpak** [comment]
Any update on this?  I'm running in AWS with Windows Server 2106 Datacenter.  AWS does not support Hyper-V so switching to Linux containers is not an option.

**Comment by charankumar4321** [comment]
Hi i have tried to create staic ip but its giving error that plugins are not supported in this platform iam using my docker is installed on windows 10 and iam using windows container

**Comment by cnilak** [comment]
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        142dfcedca
 Built:             02/28/2019 06:33:17
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.8
  Git commit:       142dfcedca
  Built:            02/28/2019 06:31:15
  OS/Arch:          windows/amd64
  Experimental:     false
PS C:\Windows\System32\drivers\etc> docker network create -d nat myNet
**Error response from daemon: HNS failed with error : The parameter is incorrect.**

**Comment by ani1203** [comment]
try 
docker network create networkName  --driver nat

mine is working on windows 10 and 2016 server

**Comment by skavor** [comment]
je suis débutant avec le docker, j'ai réçu une message d'erreur lorsque j'ai executé la commande "compose-docker up " 
ERROR: could not find plugin bridge in v1 plugin registry: plugin not found

**Comment by Vaccano** [comment]
I get this same error on docker for windows when it has gone belly up.  A full reset back to factory settings does NOT fix it.

**But switching from Windows mode to Linux mode then back to Windows again seems to fix it.**

**Comment by GizmoNo** [comment]
I got mine to work by using "docker network create "Name of network" -d nat. Hope that works for others

**Comment by paulostradioti** [comment]
> @ngocleek answered solved the issue. Why does docker default to win containers anyway? are there more people using that instead of linux containers?

It doesn't solve if you need a Windows container. Simply switching to Linux container is not an acceptable solution.

**Comment by samayo** [comment]
@paulostradioti  What are you saying? I actually reinstalled docker on formatted laptop and got the same error, googled it and arrived in this page again, and @ngocleek answer saved me for the second time. Just to be clear, I have windows 10 laptop and I am trying to run php/nginx/mariadb with docker

**Comment by carehart** [comment]
@samayo, what @paulostradioti was saying is that the recommendation to "switch to Linux mode" is not a suitable answer (to this problem of not being able to use a simple "docker network create whatever") for someone who DOES want to run Windows containers while on Docker for Windows in Windows mode. 

We understand that for YOU (and others who only want to run Linux containers while on Docker for Windows), that switch allows YOU to use that simple docker create (in linux mode). It does NOT "solve the problem" for us, though for now the proposal to use -d to name a driver type does seem to work.

**Comment by tchelidze** [comment]
> Hi there,
> 
> You should use the word _transparent_ and not _bridge_ when you are creating a bridge network for windows containers.
> 
> `PS C:\Windows\system32> docker network create -d transparent BR`
> 
> I have tested on Windows Server 2019 and I guess it will work on 2016 as well.
> 
> > PS C:\Windows\system32> docker network ls
> > NETWORK ID          NAME                DRIVER              SCOPE
> > 9dc6521b7102        BR                  transparent         local
> > edfff3ac7e60        nat                 nat                 local
> > be55ac10c0f9        none                null                local
> > PS C:\Windows\system32>
> > PS C:\Windows\system32>
> > PS C:\Windows\system32> docker network inspect 9d
> > [
> > {
> > "Name": "BR",
> > "Id": "9dc6521b71020b86782ca29dae4a80a6927c49f4b9f7634690e2c39634d48559",
> > "Created": "2018-11-26T14:00:14.0575883+01:00",
> > "Scope": "local",
> > "Driver": "transparent",
> > "EnableIPv6": false,
> > "IPAM": {
> > "Driver": "windows",
> > "Options": {},
> > "Config": [
> > {
> > "Subnet": "0.0.0.0/0"
> > }
> > ]
> > },
> > "Internal": false,
> > "Attachable": false,
> > "Ingress": false,
> > "ConfigFrom": {
> > "Network": ""
> > },
> > "ConfigOnly": false,
> > "Containers": {},
> > "Options": {
> > "com.docker.network.windowsshim.hnsid": "6D5088B8-5924-421A-B6C0-B9C11087BC2F"
> > },
> > "Labels": {}
> > }
> > ]
> 
> [https://docs.microsoft.com/en-us/virtualization/windowscontainers/container-networking/network-drivers-topologies](url)
> 
> Hope it helps

Fails with the following error on Win Server 2016

> Error response from daemon: HNS failed with error : Element not found.

**Comment by anvu03** [comment]
Anyone still have this problem? I do.

**Comment by samayo** [comment]
@anvu03 if you are trying to use linux containers try ngocleek's answer

**Comment by cocoandgaga** [comment]
> Anyone still have this problem? I do.

ues  'docker network create --driver nat  my-net" instead  ,not bridge

**Comment by xavier10quaresma** [comment]
no viable solution
