### ISSUE TITLE
Linux Containers on Windows Experimental apk update and apt-get update timeout / fail

### ISSUE THREAD

**Issue by allenerb** [docker/for-win#1961]
### System Information
Windows Version:  10.0.16299 Build 16299
Docker for Windows Version:  18.03.0-ce-win59 (16762)

### Expected behavior
Running LCOW (Experimental) Linux containers in Windows Mode for Docker.  I've tried both alpine:3.7 and ubuntu:latest images and I cannot get the apk update (for alpine) or the apt-get update for ubuntu to work.  They just hang.  Again, this is when I'm running in the Docker mode for Windows containers, I have experimental flag turned on for Docker.

### Actual behavior
When running apk update or apt-get update, the downloads never work.  They timeout.

### Information
Diagnostic ID: 7BDF60D1-4E2F-4B38-88E0-9425ED686335/2018-04-17_16-41-23

### Steps to reproduce the behavior
Enable experimental mode for Docker on Windows.
Issue the following commands...

```
docker run --platform linux --dit --name myalpine alpine:3.7
docker attach myalpine
# apk update
```
**** now it just hangs **** 

Same thing happens on Ubuntu - same basic commands

**Comment by jasonbivins** [comment]
@allenerb 
It works for me - do you get any errors, or does it just hang up?
Are you able to reach the internet from the containers, can you ping 8.8.8.8 from it?

**Comment by allenerb** [comment]
@jasonbivins - that's the frustrating thing.  If I attach to the container and ping external sites, I get responses back.  But the fetch calls fail.  It doesn't make any sense.  Eventually I just get a timeout.  Here's a dump of all the commands run back to back from the console - and as far as I can tell digging through the Docker logs, I don't see anything that shows a failure.  Fwiw - I've also tried forcing the "nat" network and that doesn't help either.  Here's the dump from the command line:

C:\Users\aunderwood  reactor
λ docker run --platform linux -dit --name extjsreactor alpine:3.7
1640c062b65d3da3f7b6f6bfcacbbf1e432f7e56b0c33cfa7ce4e557345a72b0

```
C:\Users\aunderwood
λ docker attach extjsreactor
/ # ping www.google.com
PING www.google.com (172.217.10.164): 56 data bytes
64 bytes from 172.217.10.164: seq=0 ttl=52 time=12.160 ms
64 bytes from 172.217.10.164: seq=1 ttl=52 time=12.726 ms
^C
--- www.google.com ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 12.160/12.443/12.726 ms
/ # ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=55 time=15.221 ms
64 bytes from 8.8.8.8: seq=1 ttl=55 time=11.210 ms
^C
--- 8.8.8.8 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 11.210/13.215/15.221 ms
/ # apk update
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.7/main: operation timed out
WARNING: Ignoring APKINDEX.70c88391.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.7/community: operation timed out
WARNING: Ignoring APKINDEX.5022a8a2.tar.gz: No such file or directory
2 errors; 11 distinct packages available
/ #
```

**Comment by allenerb** [comment]
It just hit me that Symantec Endpoint Protection might be the problem, and sure enough looking through the traffic logs and for some stupid reason the call is being blocked from the docker container.  Really odd...if I hit the site from the host OS, works fine...and as far as I remember hitting updates when running in "Linux Container" mode works fine.  But doing this platform linux mode is being blocked.  Going to see if I can track down the rule that's blocking the traffic.  only thing I can think is because the application name is blank and the port is not a standard known port...
![image](https://user-images.githubusercontent.com/6650583/38941915-98d44d54-42fb-11e8-9209-e08e835f8273.png)

**Comment by allenerb** [comment]
That's exactly what it was - the Symantec Endpoint Protection Firewall was blocking the traffic.  I turned it off and the apk update worked perfectly.  I guess I'm going to have to see how I can allow that port through...closing this ticket as it appears to not be Docker related.

**Comment by allenerb** [comment]
After further investigation, I think this is something that should probably be looked into from the Docker team.  So here's the situation, as mentioned previously, the apk update call fails when I'm running in Windows Container mode with platform = linux.  If I switch over to run in "Linux Mode" then it works fine through Symantec.  I'm just guessing based on what I saw in the network firewall log in Symantec Endpoint Protection, but I believe it might be blocked because of either the port or the fact that there was no application name associated with the request...here's a photo of the logs...the blocked ones were the LCOW calls, and the allowed ones were the ones where I'd switched over to Linux containers only.
![image](https://user-images.githubusercontent.com/6650583/38953276-3742f024-431c-11e8-84dd-653ffb4cabcc.png)

Also, you'll notice that the LCOW ones were using TCP whereas the Linux Containers were using ICMP - was a curious finding.  So I think making sure both "modes" of the containers should be communicating the same way - that would likely ensure the network communications work properly across the board.

**Comment by rn** [comment]
Thanks for the detailed analysis!

The LCOW mode uses Microsofts HNS for networking while the Linux Mode (where Docker for Windows runs a Linux VM where all containers are run), uses VPNKit for networking. These are implemented very differently and VPNKit works better for Firewalls as the outgoing connections look like they come from a normal application (like a web browser) while with HNS network connection originate from different network interfaces.

Most of the LCOW development is done in the upstream https://github.com/moby/moby repository and the issue you describe is not related to the Docker for Windows application. So I'm closing this issue here. You may want to raise an issue on the upstream repository, but I think there is very little which can be done there given that it is a third party firewall product causing the issue.
