### ISSUE TITLE
Wont share the C drive

### ISSUE THREAD

**Issue by jairov4** [docker/for-win#1963]
Please, check https://docs.docker.com/docker-for-win/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue
  - Windows Version: 10
  - Docker for Windows Version: 18.03.0-ce-win59 (16762)

### Expected behavior
In the settings UI, mark the C drive as shared, provide valid Windows credentials and get the drive shared.

### Actual behavior
In the settings UI, mark the C drive as shared, provide valid Windows credentials and nothing happens after apply changes and label with "updating drives..." disappears.

### Information
Diagnostic ID: 3C8E2612-8373-45C9-90D2-2C6818B2156C/2018-04-17_20-52-39

### Steps to reproduce the behavior

  1. In the settings UI
  2. mark the C drive as shared
  3. provide valid Windows credentials

**Comment by jasonbivins** [comment]
@jairov4   Are you getting an error right away, or when you try to start a container?  Check to make sure the linux image you're using is up to date.

`[20:52:25.701][SambaShare     ][Error  ] Unable to mount C drive: C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/usr/bin/nsenter1\": stat /usr/bin/nsenter1: no such file or directory": unknown.`

**Comment by jairov4** [comment]
It was setting the share option in the UI. Not running a specific container.

Enviado desde mi ASUS

-------- Mensaje original --------
De:Jason Bivins
Enviado:Wed, 18 Apr 2018 08:56:18 -0500
Para:docker/for-win
Cc:jairov4 ,Mention
Asunto:Re: [docker/for-win] Wont share the C drive (#1963)


@jairov4<https://github.com/jairov4> Are you getting an error right away, or when you try to start a container? Check to make sure the linux image you're using is up to date.

[20:52:25.701][SambaShare ][Error ] Unable to mount C drive: C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/usr/bin/nsenter1\": stat /usr/bin/nsenter1: no such file or directory": unknown.

**Comment by laymain** [comment]
I'm not sure, it could be.
Try to create a local account just for Docker
https://support.microsoft.com/en-ph/help/4026923/windows-create-a-local-user-or-administrator-account-in-windows-10

**Comment by jairov4** [comment]
I did, same problem with the local account

**Comment by samedwards1989** [comment]
I stopped docker and restarted it and it then allowed me to share my drives

**Comment by jairov4** [comment]
It suddenly start working, I didnt noticed what exactly made the change
I was playing with cortana options but some Windows Update was involved too

**Comment by laymain** [comment]
Are you sure that it isn't linked to the local account?

**Comment by jairov4** [comment]
completely sure, the time that worked it was puting my regular credential

**Comment by stephen-turner** [comment]
I'm glad it's working now. I'm not sure we have much to go on as it's not clear what made a difference, so I'm going to close this issue.

**Comment by askflow1111** [comment]
> I'm not sure, it could be.
> Try to create a local account just for Docker
> https://support.microsoft.com/en-ph/help/4026923/windows-create-a-local-user-or-administrator-account-in-windows-10

It worked for me! Thank you very much!

**Comment by speller** [comment]
Only reset to factory defaults worked for me to fix this issue.
