### ISSUE TITLE
Cannot login to Docker for Windows

### ISSUE THREAD

**Issue by sanaude** [docker/for-win#1964]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue
  - Windows Version: 1709 (OS Build 16299.309)
  - Docker for Windows Version: 18.03.0-ce-win59 (16762)

### Expected behavior
Would expect it to log in

### Actual behavior
It just puts a red highlight around docker id and password

### Information

  - Diagnostic ID: 91945987-5C79-4134-B225-FA63A986C444/2018-04-18_12-27-06
  - I can log into cloud.docker.com successfully using the same credentials

**Comment by sanaude** [comment]
Seemed to be a password character support issue. I made the password much simpler and it works now. As I mentioned before, the complex password worked just fine on the web login, just not the windows app.

**Comment by godijoe** [comment]
I made my password simple all lowercase 6 char still the same behavior. It just puts a red highlight around docker id and password. Please advise

**Comment by kombasltd** [comment]
Same issue here. Can not login with my docker.com credentials into Docker for Windows.
