### ISSUE TITLE
Docker seems to have a hardcoded DNS result for 'gitlab'

### ISSUE THREAD

**Issue by arc6011** [docker/for-win#1970]
Please, check https://docs.docker.com/docker-for-win/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [X ] I have submitted Diagnostics
  - [X ] I have included the Diagnostics ID in this Issue
  - Windows Version: Windows 10 Pro (1709)
  - Docker for Windows Version: 18.03.0-ce-win59 (16762)

### Expected behavior
When Docker is installed, pinging 'gitlab' from the host OS should fail or return a valid IP from the network DNS.

### Actual behavior
After installing Docker, pinging 'gitlab' from the host OS returns the address of the DockerNAT adapter.

### Information
9622D7E0-36C9-41D8-B279-45684804BBBC/2018-04-20_17-44-50

There seems to be a hard-coded DNS lookup result in the Docker VM.
This happens with a new installation of Windows 10 and Docker 18.
For me, this is occluding DNS lookups of a real GitLab server on the network. My only solutions are to either disable the DockerNAT adapter or uninstall Docker.

### Steps to reproduce the behavior

  1. Wipe a machine and install Windows 10
  2. Ping 'gitlab' - will fail or find an address from the configured network DNS if such a name is registered
  3. Install Docker 18 CE
  4. Ping 'gitlab' - will return 10.0.75.1 (the DockerNAT Hyper-V adapter)
  5. Uninstall Docker
  6. Ping 'gitlab' - will again return results from the configured network DNS as in step #2

**Comment by rn** [comment]
@arc6011 I'm not sure what you mean by "This seems to cause the host to also be registered in DNS with the Hyper-V adapter's address." Which DNS are you referring to here?

Despite the `DockerNAT` name this is actually not a NAT adapter. We create a *internal* switch which should only allow communication between the host and the VM.

How did you "disabled address registration for the NAT adapter on the GitLab host"? Is this some DNS server somewhere on your network and you see 10.0.75.1 on that DNS server? This address should never leave the host where docker for windows is running. As said it's an internal switch and we do not run DHCP to set the address...

**Comment by arc6011** [comment]
@rn It's entirely possible that I've misunderstood the mechanism of this issue.

I agree that the address of the DockerNAT adapter should not leave the host machine. But, after installing Docker on a virgin machine that had never seen anything but Windows 10 installation, a ping of 'gitlab' (the hostname of a separate physical host running gitlab under Docker for Windows) returned 10.0.75.1 instead of the real host IP address.

The only ways I found to get ping to return the actual host IP address were:
1. Uninstall Docker from the client machines
2. Disable the DockerNAT adapter on the client machines
3. Change the subnet address for the DockerNAT on the client or server machine
4. Disable the "Register this connection's address in DNS registration" option in "Advanced TCP/IP Settings" for DockerNAT on the server machine (screen shot of the IPv4 dialog attached with the option enabled)
![register_connection_address](https://user-images.githubusercontent.com/13943503/39444030-56c6f4e2-4c84-11e8-934b-36f931294afe.png)

Somehow the client name resolution is picking up the server's DockerNAT address and routing to the local switching adapter.

**Comment by rn** [comment]
I don't understand your setup. What are client and server machines in this context?

**Comment by arc6011** [comment]
To simplify...

I have two physical machines - both running Windows 10 Pro: 
The first machine has the hostname 'gitlab'. It is the "server." The other machine's hostname doesn't matter. It is a "client."

I installed Docker for Windows on the first ("server") machine and ran the GitLab Omnibus container, mapping the VM ports 80, 443, and 22 to host ports.

From the "client" machine, I can use a browser to connect to 'gitlab' with the expected results. I can ping 'gitlab' and see the IP address of the "server" host adapter. All works as I would expect it to.

However, if I install Docker for Windows on the "client" machine, that "client" machine host will no longer be able to access the GitLab server. Ping from that client machine will return the address of the DockerNAT adapter instead of the address of the "server" host adapter.

See the above notes for the resolution.

**Comment by rn** [comment]
Thanks for the clarification. Your setup now make sense. Of course I have no idea why this tick box is set for a network interface for an internal switch, nor does it make sense to advertise the hostname this way for an interface with a static IP address (as, AFAIK, the DNS name registration is done via DHCP).

In any case, I create an internal tracking issue.
