### ISSUE TITLE
windows 10 pro Failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running.

### ISSUE THREAD

**Issue by kuncao** [docker/for-win#1975]
Please, check https://docs.docker.com/docker-for-win/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have submitted Diagnostics
  - [ ] I have included the Diagnostics ID in this Issue
  - Windows Version:
windows 10 professional
  - Docker for Windows Version:
18.03
### Information
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start.

Failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running.

'MobyLinuxVM' failed to start. (Virtual machine ID 86B7CD57-CBAF-4531-8819-F96B5CB226AC)

The Virtual Machine Management Service failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running (Virtual machine ID 86B7CD57-CBAF-4531-8819-F96B5CB226AC).
at Start-MobyLinuxVM, <No file>: line 300
at <ScriptBlock>, <No file>: line 395
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 67
   at Docker.Actions.<>c__DisplayClass14_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 51
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

### Steps to reproduce the behavior
after installed Docker for Windows Installer.exe down load from 
https://store.docker.com/editions/community/docker-ce-desktop-windows
and  Hyper-V is enabled 
when start the docker ,error occur

https://github.com/docker/for-win/issues/574
at the end of the issue 574,the solution is for windows server
how to solve the issue in windows 10 professional?
thanks a lot

**Comment by stephen-turner** [comment]
@kuncao Thank you for your report. Please upload a diagnostics bundle and include the ID here. Thank you.

**Comment by jasonbivins** [comment]
@kuncao 
Can you provide a diagnostic ID ? (right click Docker - Diagnose and Feedback)

Are you able to open up Hyper-V manager?  Can you create or connect to any VMs there?

**Comment by kuncao** [comment]
https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/nested-virtualization
my env is a vm
in windows 10 vm , nested-virtualization does not support
thanks a lot

**Comment by padawanLearner** [comment]
Had this issue on a Win10 vCloud VM.  The VM use to be Win8, so the vCloud GuestOS setting was still set to Win8.  Changing vCloud GuestOS to Win10 and updating "Virtual hardware version" to 11 fixed it.
![nestedvirtualization](https://user-images.githubusercontent.com/5659833/41785652-48d0228a-7611-11e8-93ea-1f0c4bb9fa62.PNG)
