### ISSUE TITLE
Docker for windows - Linux container mode failed to start and not mounting volumes 

### ISSUE THREAD

**Issue by rajeshanayaka** [docker/for-win#1979]
- [x] I have tried with the latest version of Stable channel
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue : 9ABAC9E6-F8B7-44B5-A5E2-B1F40AB5742C/2018-04-27_09-42-23
  - Windows Version: Microsoft Windows [Version 10.0.16299.371] - 1709 
  - Docker for Windows Version: 18.03.1-ce

### Expected behavior
default container to start normal 

### Actual behavior

PS C:\Windows\system32> docker run --rm -v c:/Users:/data alpine ls /data
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.37/containers/create: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
PS C:\Windows\system32>

A diagnostic was uploaded with id: 9ABAC9E6-F8B7-44B5-A5E2-B1F40AB5742C/2018-04-27_09-42-23

### Steps to reproduce the behavior

1. Download and install docker for windows - stable Chanel
2. During installation do not select windows container option since we need Linux container 
3. docker for windows Settings, shared drive, check C drive 
4. run following command 
       docker run --rm -v c:/Users:/data alpine ls /data

**Comment by KristianRaue** [comment]
Same problem here, Updated to 18.03.1-ce on Windows 10. Before the update it worked, after the update docker fails to start.

**Comment by StupidPeopleTrick** [comment]
I am also seeing this issue after Windows Update.
docker version:
docker version 18.03.1-ce, build 9ee9f40
Windows hotfix just applied:
Security Update  KB4103729     NT AUTHORITY\SYSTEM  5/9/2018 12:00:00 AM
Update           KB4131372     NT AUTHORITY\SYSTEM  5/9/2018 12:00:00 AM
Security Update  KB4103727     NT AUTHORITY\SYSTEM  5/9/2018 12:00:00 AM
