### ISSUE TITLE
docker has memory leak with multiple run cmd.exe inside container

### ISSUE THREAD

**Issue by dyvniy** [docker/for-win#1984]
Please, check https://docs.docker.com/docker-for-win/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have submitted Diagnostics
  - [ ] I have included the Diagnostics ID in this Issue
  - Windows Version: 2016
  - Docker for Windows Version: 17.06.2-ee-10, build 66261a0

### Expected behavior

dockerd service take memory and return it back.

### Actual behavior

dockerd eat 0.5 Mb RAM each 100 cmd.exe runs inside container.
dockerd not free this RAM when container exits.

### Information

Test script:
[test_leaks.zip](https://github.com/docker/for-win/files/1957820/test_leaks.zip)
Endless exe file, need to prevent container's stop.
[endless.zip](https://github.com/docker/for-win/files/1957826/endless.zip)
"nv/servercore:endless" image based on "microsoft/windowsservercore" with endless.exe coped to C:/
[leaks.zip](https://github.com/docker/for-win/files/1957840/leaks.zip)
Script result on my machine.

### Steps to reproduce the behavior

  1. Install python 3.5 and docker on host Windows 2016 system.
  2. install docker & psutil python packets.
  3. Make analog of "nv/servercore:endless" image.
  4. Run test_leaks.py script and wait 1 hour.

**Comment by rn** [comment]
Thanks for the report. This looks like a potential issue with the upstream moby/moby code and is not specific to the Docker for Windows application, so I'm closing this issue here.
 Could you open an issue on https://github.com/moby/moby instead?
Thanks

**Comment by dyvniy** [comment]
Thanks for quick answer, but I disagree.
Docker has memory leak on windows system with standard image and standard command line tool "cmd.exe". Is it really problem of moby, that I never used and even heard before?
I can reproduce it without usage of python or new images, If you need.

**Comment by dyvniy** [comment]
@rn Its clear now, thanks
