### ISSUE TITLE
After docker update, very slow (unusable) write acces to bind mount, but fast read access

### ISSUE THREAD

**Issue by apsim-git** [docker/for-win#1987]
I recently updated to Docker 18.03.1-ce-win65 (17513). Before this, my containers had ~20-40MB/s read/write performance. Now, the read performance is unusable, while write performance is still OK.

### Expected behavior
Same read/write performance on bind mounts as before the Docker version update.

### Actual behavior
Write performance is the same as before (~40MB/s), but read performance is ~600KB/s.

### Information
Diagnostic ID: 4B878E7D-F47B-4AE1-A4D0-567BDFF72865/2018-05-01_12-15-13
OS Version: Windows Server 2016 Standard (10.0.14393)
Docker Version: 18.03.1-ce-win65 (17513)

### Steps to reproduce the behavior
[entry point of container below is /usr/bin/bash]
docker run --interactive=true --tty=true --mount type=bind,source=s:/test_folder,target=/io_test --network=none --name=test_container test_container

bash-4.4# cd /io_test
bash-4.4# dd if=/dev/zero of=from_dev.zeros bs=64MB count=10
10+0 records in
10+0 records out
640000000 bytes (640 MB, 610 MiB) copied, 16.7875 s, 38.1 MB/s

bash-4.4# time sync
real    0m0.011s
user    0m0.000s
sys     0m0.000s

bash-4.4# dd if=from_dev.zeros of=from_file.zeros bs=64MB count=10
[hit Ctrl-C after ~5 minutes]
^C4+0 records in
3+0 records out
192000000 bytes (192 MB, 183 MiB) copied, 337.91 s, 568 kB/s

[repeating these commands gives similar times, e.g:]
bash-4.4# dd if=/dev/zero of=from_dev2.zeros bs=64MB count=10
10+0 records in
10+0 records out
640000000 bytes (640 MB, 610 MiB) copied, 20.0504 s, 31.9 MB/s

Before I updated to the latest version of Docker, the write performance of both commands above would have been approx. the same since the initial file was sitting in cache. This unusable read performance appears in all my containers.

Any help here most appreciated!

**Comment by jasonbivins** [comment]
Hi - We don't actually support Docker for Windows (CE) running on Windows Server - so I'm going to go ahead and close this issue.
https://docs.docker.com/docker-for-windows/install/#what-to-know-before-you-install


The basic EE version for Server 2016 is free and is supported by Microsoft
https://www.docker.com/docker-windows-server

**Comment by apsim-git** [comment]
Thanks Jason.

Apologies for this.

**Comment by apsim-git** [comment]
The EE version for Server 2016 (at least <= 10.0.14393) doesn't currently support Linux containers. So for anyone else who hits upon this: it turned out to be a Windows Defender issue.
