### ISSUE TITLE
Docker stats does not work 

### ISSUE THREAD

**Issue by hoegge** [docker/for-win#1990]
Please, check https://docs.docker.com/docker-for-win/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have submitted Diagnostics
  - [X] I have included the Diagnostics ID in this Issue
  - Windows Version: Windows 10 Pro 1709 Build 16299.248
  - Docker for Windows Version :Version 18.05.0-ce-rc1-win63 (17439)

### Expected behavior
`docker stats` shows stats

### Actual behavior
just hangs, shows nothing and then exits after a while

### Steps to reproduce the behavior

 as above: type `docker stats` in command prompt, CMDer or PowreShell

**Comment by rn** [comment]
seems to work fine for me with the same version as you. Ran `docker stats` in one powershell and then a `docker run --rm -ti alpine` in another and the container shows up
![screen shot 2018-05-02 at 09 56 49](https://user-images.githubusercontent.com/3338098/39514500-3f767ec2-4def-11e8-86ac-185ea43d7a46.png)

**Comment by hoegge** [comment]
now suddenly also runs at my end (after increasing docker memory). Seems like a few struggling containers can make this function hang.
