### ISSUE TITLE
Access denied when creating symlinks on mounted volumes in windows nanoserver 

### ISSUE THREAD

**Issue by ielcoro** [docker/for-win#1997]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [ X] I have submitted Diagnostics
  - [X ] I have included the Diagnostics ID in this Issue
  - Windows Version: Windows 10 Version 1803 (17134.1)
  - Container image version: microsoft/nanoserver-insider:10.0.17134.1 or higher
  - Docker for Windows Version: 18.03.1-ce-win65 (17513)

### Expected behavior

Creating a symbolic link with mklink or programs that use the windows api, like npm, inside a mounted volume should work, like it does on a host machine.

### Actual behavior

Either with the ContainerUser user or ContainerAdministrator user, creating a symbolic link inside a mount volume returns Access Denied. The same happens when using a program that creates symbolic links like npm.

### Information
4E7CA670-B5CF-43EE-8346-BF3D34BE1201/2018-05-03_14-37-34

Latest versions of Windows containers changed the mounted volumes behavior, now instead of seing it as a junction point, that was causing problems with a myriad of software, like node, npm, git... it looks like a regular directory inside the container filesystem. 

Normal operation inside the mounted volume works as expected, however creating a symbolic link does not, blocking some npm operations like npm install with local packages or some git commands on the container.

### Steps to reproduce the behavior

  1. Pull an image of the latest nanoserver-insider 10.0.17134.1 or higher
`docker pull microsoft/nanoserver-insider:10.0.17134.1`
  2. Run in intercative mode mapping a volume with -v flag:
`docker run -it -v C:\app:C:\app microsoft/nanoserver-insider:10.0.17134.1`
  3.Move to the mounted volume: `cd \app\`
  4. Try to create a symbolic link to a file:
`mklink mylink file.txt`
 You should see an Access denied error.

**Comment by ielcoro** [comment]
Just a quick update,

I got exploring a bit more, i found it happens on any volume type, not just on binded volumes:

`docker run -it --mount 'type=volume,src=test,dst=c:\app' microsoft/nanoserver-insider:10.0.17134.1`

Mklink on c:\app returns Access is denied.

**Comment by jasonbivins** [comment]
@ielcoro   I was able to repro this in the EE version as well - I've opened up an issue on Moby/moby for tracking, and I'll go ahead and close this one

**Comment by ironsmile** [comment]
Linking the above mentioned issue would have been very helpful.

**Comment by lucasshd** [comment]
This should be the new opened Issue:
https://github.com/moby/moby/issues/37024
I hope it helps.
