### ISSUE TITLE
parse tcp://C:\Program Files\Docker\Docker: invalid character "\\" in host name

### ISSUE THREAD

**Issue by ondyb** [docker/for-win#1999]
Installed Docker Version 18.03.1-ce-win65 (17513) on Windows 10 Pro.
When I try to check docker version from command prompt, i get following error. (same for PowerShell, and other docker commands)
Docker is installed in [C:\Program Files\Docker\Docker].
Any idea what might be causing this?

Diagnostic ID: B7D170E9-DA7B-4C55-B9EC-39341D1908BF/2018-05-04_09-18-08

![image](https://user-images.githubusercontent.com/32889050/39609457-a8e9b882-4f7b-11e8-8bee-1928fde95da9.png)

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue
  - Windows Version: 10 Pro
  - Docker for Windows Version: 18.03.1-ce-win65 (17513)

### Expected behavior
docker version should be shown on console.
### Actual behavior
error message is shown as 
"parse tcp://C:\Program Files\Docker\Docker: invalid character "\\" in host name"
### Steps to reproduce the behavior

  1. Install Docker for Windows
  2. run docker --version from command line (command prompt or powershell)

**Comment by rn** [comment]
Do you, by any chance have the `DOCKER_HOST` environment variable set? By default this should not be set and the docker CLI should talk to a named pipe.

**Comment by jasonbivins** [comment]
Hi @ondyb you have a ```-```  in the name of your Host and docker isn't liking it on startup

I just tried on the edge channel and couldn't repro. Can you upgrade and see if that helps?

**Comment by vas4all** [comment]
Am encountering the same issue..Any update for the same?
