### ISSUE TITLE
"Inconsistent parameters PolicyStore PersistentStore and Dhcp Enabled" after update

### ISSUE THREAD

**Issue by kwinz** [docker/for-win#2]
### Actual behavior
During and since upgrade to version 1.12.0-beta21 (build 5971) 5b59d37
I get the error "Inconsistent parameters PolicyStore PersistentStore and Dhcp Enabled."
I am not aware of having changed any settings from the defaults.
The docker symbol displayed red on each restart.

The error did resolve itself after 3-4 times of restarting docker. Now everything seems to be fine.

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
6C337D1E-D334-4D53-814C-2B9AC9419A20/2016-07-29_02-40-36

### Steps to reproduce the behavior
Agree to the automatic update to version 1.12.0-beta21 in Docker for Windows.

**Comment by dgageot** [comment]
Here's the full error message for reference:

```
[02:40:31.407][PowerShell     ][Info   ] Run script with parameters: -Create True -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[02:40:31.487][HyperV         ][Info   ] Using existing Switch: DockerNAT
[02:40:31.620][NamedPipeServer][Error  ] Unable to execute Start: Failed to create Switch "DockerNAT": Inconsistent parameters PolicyStore PersistentStore and Dhcp Enabled
    bei System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   bei System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   bei Docker.Core.PowerShell.Run(String script, Dictionary`2 parameters, Action`1 lineReceived)
   bei Docker.Backend.Backend.Start(Settings settings)
   bei Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass7_0.<Register>b__0(Object[] parameters)
   bei Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

```

**Comment by dgageot** [comment]
I'm pretty sure this happens when we call:
```
$netIP = $networkAdapter | New-NetIPAddress -AddressFamily IPv4 -IPAddress $switchAddress -PrefixLength ($SwitchSubnetMaskSize) -ea Stop
```

**Comment by CharlesSong** [comment]
Failed to create Switch "DockerNAT": Inconsistent parameters PolicyStore PersistentStore and Dhcp Enabled

   在 Docker.Core.Pipe.NamedPipeClient.TrySend(String action, Object[] parameters)
   在 Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   在 Docker.Core.Backend.BackendClient.Start(Settings settings)
   在 Docker.Actions.<>c__DisplayClass26_0.<RestartVm>b__0()
   在 Docker.Core.TaskQueue.<.ctor>b__16_0()

**Comment by dgageot** [comment]
@kwinz @CharlesSong I couldn't repdoduce this issue. Can you run this command:

```
Get-NetAdapter "vEthernet (DockerNAT)" | Get-NetIPInterface
```

**Comment by dgageot** [comment]
@kwinz @CharlesSong Hi, any chance you had time to run the command?

**Comment by cbrevik** [comment]
@dgageot I'm getting the same thing, just ran the command:

```
> Get-NetAdapter "vEthernet (DockerNAT)" | Get-NetIPInterface

ifIndex InterfaceAlias                  AddressFamily NlMtu(Bytes) InterfaceMetric Dhcp     ConnectionState PolicyStore
------- --------------                  ------------- ------------ --------------- ----     --------------- -----------
32      vEthernet (DockerNAT)           IPv6                                                                Persiste...
32      vEthernet (DockerNAT)           IPv6                  1500               5 Enabled  Connected       ActiveStore
32      vEthernet (DockerNAT)           IPv4                                                                Persiste...
32      vEthernet (DockerNAT)           IPv4                  1500               5 Enabled  Connected       ActiveStore
18      vEthernet (DockerNAT)           IPv6                                                                Persiste...
18      vEthernet (DockerNAT)           IPv6                  1500               5 Enabled  Disconnected    ActiveStore
18      vEthernet (DockerNAT)           IPv4                                                                Persiste...
18      vEthernet (DockerNAT)           IPv4                  1500               5 Enabled  Disconnected    ActiveStore
```

**Comment by dgageot** [comment]
Thanks a lot @cbrevik for the feedback!

Can you run this command in an elevated Powershell before you restart Docker and see if it fixes the issue?

```
$vmNetAdapter = Get-VMNetworkAdapter -ManagementOS -SwitchName DockerNAT
Get-NetAdapter "vEthernet (DockerNAT)" | ? { $_.DeviceID -ne $vmNetAdapter.DeviceID } | Disable-NetAdapter -Confirm:$false -PassThru | Rename-NetAdapter -NewName "Broken Docker Adapter"
```

**Comment by cbrevik** [comment]
Thanks @dgageot, that seemed to solve it for me! 

In my case, it might be that this problem corresponded with installing Xamarin, and using the Visual Studio Emulator for Android. The emulator uses Hyper-V as well, and started messing around with the virtual switches on my first run.

**Comment by dgageot** [comment]
Closing. This was added to master branch and is planned to be released both on stable and beta channels.
