### ISSUE TITLE
cannot start docker-compose until restart docker

### ISSUE THREAD

**Issue by nonnyohiyo** [docker/for-win#2000]
After logon windows then open docker
i cannot run start docker-compose, it's show error 
`ERROR: for redis  Cannot start service redis: b'driver failed programming external connectivity on endpoint redis (72d4cCreating mysql ... error
9:tcp:172.18.0.2:6379: input/output error'`

Until restart docker, I cannot use docker-compose anyway.

**Comment by jasonbivins** [comment]
@nonnyohiyo 
Do you have Docker set to Auto-start?

<img width="740" alt="screen shot 2018-05-04 at 3 09 19 pm" src="https://user-images.githubusercontent.com/28021664/39647484-336b3ec8-4fad-11e8-97f3-9eca5148413d.png">

**Comment by nonnyohiyo** [comment]
No i'm start manualy. it's

**Comment by nonnyohiyo** [comment]
@jasonbivins No i'm start manual.
then run docker-compose i'ts show error
![image](https://user-images.githubusercontent.com/3001763/39660090-1f77dfce-5062-11e8-9528-02a9d0c06ac1.png)
