### ISSUE TITLE
Failed to share C drive on Linux Docker

### ISSUE THREAD

**Issue by csamleong** [docker/for-win#2001]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have submitted Diagnostics
  - [X] I have included the Diagnostics ID in this Issue: 

Other things i have tried but couldn't work:
1:uninstall and reinstall Hyper-V
2.uninstall and reinstall Docker, tried both latest Stable and Edge
3.disabled my firewall
4.confirmed that i do not have any weird characters in my account and password
5.tried to mount it on E drive (External drive).

### Expected behavior
Expected to share C drive with the docker.
Open Docker Terminal -> Check Shared Drives on C drive
It should remain checked after i clicked apply.

### Actual behavior
C drive went automatically unchecked again in shared drive.

### Information
  - Diagnostic ID:AB05FA53-E8BF-437E-9C42-2299EF1F6568/2018-05-04_15-56-43
  - Windows Version: Windows 10 pro
  - Docker for Windows Version: 18.05.0-ce-rc1-win63 (17439)

### Steps to reproduce the behavior

  1. Install latest docker version :  18.05.0-ce-rc1-win63 (17439)
  2. Go to shared drives - check C drive.
[log.txt](https://github.com/docker/for-win/files/1973629/log.txt)
[DebugInfo-2018-05-04_15-56-43.txt](https://github.com/docker/for-win/files/1973630/DebugInfo-2018-05-04_15-56-43.txt)

**Comment by namnh06** [comment]
get it today, it's so annoying to me.

**Comment by namnh06** [comment]
I knew what happen guys.

In my case, after remove xampp in my computer, I can not share drives any more. It's block the 445 port, guess that.

Just find this one and disable it !

![disable-445](https://user-images.githubusercontent.com/28762252/39950839-9a743a50-55ae-11e8-9ad8-f5baf12f60bc.PNG)

**Comment by jasonbivins** [comment]
Hi @csamleong  thanks for following up 
I'll go ahead and close this one out now.
