### ISSUE TITLE
Quite installation of docker with enabled kubernetes and shared drivers

### ISSUE THREAD

**Issue by aliluyko89** [docker/for-win#2003]
Hello,

I am using docker for windows on Windows 10 machine and docker edge 18.05.0-ce-rc1-win63 (17439)
Is it possible to install docker with already enabled kubernetes, shared drivers?
Or probably I can enable them from command line?

Thanks in advance

**Comment by jasonbivins** [comment]
Hi @aliluyko89 
Currently we don't have a silent installer that will setup Docker for Win with pre-configured settings.
We are working on an installer package that will do that, but I don't have an ETA for when that will be ready.

**Comment by aliluyko89** [comment]
@jasonbivins, thank you for fast response.
What about possibility to enable kubernetes using command line?

**Comment by aliluyko89** [comment]
@jasonbivins

**Comment by ma499** [comment]
I am also interested in enabling Kubernetes via CLI.
