### ISSUE TITLE
Build app failed on win10 1803

### ISSUE THREAD

**Issue by xin135** [docker/for-win#2004]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x ] I have included the Diagnostics ID in this Issue
  - Windows Version:win10 1803
  - Docker for Windows Version:18.05.0-ce-rc1

### Expected behavior

Build the demo app

### Actual behavior

Build failed

### Steps to reproduce the behavior

  1. refer to https://docs.docker.com/get-started/part2/#build-the-app 
  2. docker build -t friendlyhello . failed:

Sending build context to Docker daemon  4.608kB
Error response from daemon: Bad response from Docker engine

**Comment by jasonbivins** [comment]
@xin135 
Was the `docker run hello-world` command successful?

**Comment by jasonbivins** [comment]
Hi @xin135   I wasn't able to reproduce using the scripts provided, but i did run into an error when I didn't have each line of the requirements.txt on it's own line.  From the error message It actually looks like your Docker engine wasn't running.

There's a log file you can analyze for more information - see here https://docs.docker.com/docker-for-windows/troubleshoot/
