### ISSUE TITLE
Docker engine freezes after a while

### ISSUE THREAD

**Issue by hkoelewijn** [docker/for-win#2007]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x ] I have included the Diagnostics ID in this Issue
  - Windows Version: 
Windows10 1709, latest updates
  - Docker for Windows Version:
Version 18.03.1-ce-win65 (17513)
Channel: stable
93354b3

### Expected behavior
Docker engine is responsive
### Actual behavior
Docker engine is not responsive 
docker ps -a responds with 'Error response from daemon: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'

### Information
Diagnostic ID
17F28038-B039-469E-9BE5-118D85A94A03/2018-05-07_07-41-03

Docker compose with 3 networks and 65 containers (20*PostGres, 33*DotnetCore Ngnix, RabbitMQ)

### Steps to reproduce the behavior

  1. Start compose file
  2. Let it sit there for 24 hours

**Comment by WolfspiritM** [comment]
This is still an issue for me.
"docker ps" and all docker commands stops working and docker freezes out of sudden until restarting docker engine.
