### ISSUE TITLE
Failure to start after reinstall

### ISSUE THREAD

**Issue by gvoysey** [docker/for-win#201]
### Expected behavior
Docker for Windows reinstalls properly after being uninstalled.
### Actual behavior
```
Could not read CA certificate "C:\\WINDOWS\\system32\\config\\systemprofile\\.docker\\ca.pem": open C:\WINDOWS\system32\config\systemprofile\.docker\ca.pem: The system cannot find the path specified.

   at Docker.Backend.DockerDaemonChecker.Check()
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```
### Information
[Full Log](https://github.com/docker/for-win/files/569807/log.txt)
  - Diagnostic ID from "Diagnose & Feedback" in the menu.
9253A257-A8AF-401E-B4C2-8069B2392561/2016-11-03_14-35-46

  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)
Win 10 Pro. V 1607, build 14393.351 
### Steps to reproduce the behavior

  1. Delete docker for windows and docker toolbox (from previous installation) via win10 add/remove programs.
  2. boot into safe mode.
  3. remove `%USERPROFILE%\.docker`
  4.  reboot out of safe mode
  5.  install docker for windows
  6.  Above message displays; docker fails to start.
  7 .  Verified that `C:\\WINDOWS\\system32\\config\\systemprofile\\.docker` is not a directory. 
  8 . Verified that `%USERPROFILE%\.docker` is not a directory.

**Comment by rneugeba** [comment]
Thanks for the report. @simonferquel could you take a look? Seems to be an issue with certificates.

**Comment by gvoysey** [comment]
This persists in 1.12.3 (8488). 

Diag ID : 9253A257-A8AF-401E-B4C2-8069B2392561/2016-11-08_14-17-19

[log.txt](https://github.com/docker/for-win/files/579149/log.txt)

**Comment by simonferquel** [comment]
@rneugeba actually the message is the output of `docker ps`. @gvoysey can you confirm that running `docker ps` from any command line gives the same message ? what about `docker version`?

**Comment by gvoysey** [comment]
```
C:\Users\gvoysey>docker ps
Could not read CA certificate "C:\\Users\\gvoysey\\.docker\\ca.pem": open C:\Users\gvoysey\.docker\ca.pem: The system cannot find the path specified.

C:\Users\gvoysey>docker --version
Docker version 1.12.3, build 6b644ec

C:\Users\gvoysey>docker version
Could not read CA certificate "C:\\Users\\gvoysey\\.docker\\ca.pem": open C:\Users\gvoysey\.docker\ca.pem: The system cannot find the path specified.
```
@simonferquel 

`C:\Users\gvoysey\.docker` is not a directory that exists, right now.

**Comment by simonferquel** [comment]
What is the output of `where docker.exe` ?

**Comment by gvoysey** [comment]
@simonferquel : `C:\Program Files\Docker\Docker\Resources\bin\docker.exe`

**Comment by simonferquel** [comment]
hmm and `echo %DOCKER_CERT_PATH%` ?

**Comment by gvoysey** [comment]
```
C:\Users\gvoysey>echo %DOCKER_CERT_PATH%
%DOCKER_CERT_PATH%

```

so null, basically.

**Comment by simonferquel** [comment]
I see that there is a DOCKER_TLS_VERIFY env variable on your system. Can you remove it, logout / re-login and retry `docker version` ?

**Comment by gvoysey** [comment]
that seems to have improved matters somewhat: 
```
C:\Users\gvoysey>docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64
```

**Comment by simonferquel** [comment]
Can you confirm the issue is fixed then ?

**Comment by gvoysey** [comment]
Confirmed
