### ISSUE TITLE
How can sysctl settings be customized? (increase fs.inotify.max_user_instances for dnsmasq)

### ISSUE THREAD

**Issue by jamshid** [docker/for-win#2011]
- Windows Version:
Windows 10 
  - Docker for Windows Version:
Stable, Server Version: 18.03.1-ce
### Expected behavior

I should be able to change syctl settings in Docker for Windows ui config or via a config file.
I tried editing /etc/sysctl.conf using this but it's not preserved on reboot.
```
docker run -ti --privileged -v /:/tmp/root centos bash
```
This feature was also requested in https://forums.docker.com/t/sysctl-p-doesnt-work/43105.

I'm trying to create /etc/sysctl.d/60-max-user-watches.conf with below to workaround a failure in my container "dnsmasq: failed to create inotify: Too many open files".
```
fs.inotify.max_user_watches = 8192
fs.inotify.max_user_instances = 8192
```
Btw I don't need this workaround under Docker for Mac with the same container/environment, I wonder if you've already increased those settings in D4M?

PS: more info about the dnsmasq problem in https://github.com/kubernetes/kops/pull/2913.

**Comment by jasonbivins** [comment]
@jamshid 
Are you trying to make the changes persistent inside a container, or are you trying to change the Docker for Windows configuration?

https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/configure-docker-daemon

**Comment by jamshid** [comment]
Trying to make the changes permanently in Docker for Windows configuration. 
I don't see anything about "`sysctl`" in that link. 
How do I permanently increase fs.inotify.max_user_instances?

**Comment by wintercounter** [comment]
Bump.

**Comment by lukaszch** [comment]
I don't think this issue should be closed as it hasn't been addressed yet.

**Comment by jamshid** [comment]
I can't reopen this but looks like there are some similar workarounds in https://github.com/docker/for-win/issues/5202.
