### ISSUE TITLE
[Suggestion] Replace LCOW Hyper-V isolation with the WSL Linux kernel

### ISSUE THREAD

**Issue by SkryptX** [docker/for-win#2013]
I did some searching online and looked for better integration of Linux docker containers in Windows. LCOW is already a huge step, but there are some major incompatibilities that prevent it from being really useful yet. I stumbled upon WSL(Windows Subsystem for Linux) during the process and found out that a way to enhance the experience is to use WSL under Windows and run docker (or at least the daemon) inside it. So I asked myself, if it would be possible to join the WSL and LCOW team together to build a Linux kernel on Windows that allows for a near perfect interoperability. The WSL kernel already works quite nicely for most applications. 

Am I missing something important or is this something already in consideration by the development team?

**Comment by stephen-turner** [comment]
I think this would be a question for Microsoft, not for Docker.

**Comment by SkryptX** [comment]
Where would be the correct place to ask this? Is there a github dedicated to the efforts of the Windows team in regards to Docker for Windows or something?
