### ISSUE TITLE
unknown error after kill: docker-runc did not terminate sucessfully: container_linux.go:393: signaling init process caused "permission denied" : unknown

### ISSUE THREAD

**Issue by charytecholution** [docker/for-win#2014]
We are facing a unknown issue with docker-ce on Ubuntu OS when we are trying to stop container.

Example:

docker stop container-id

Error output:

**unknown error after kill: docker-runc did not terminate sucessfully: container_linux.go:393: signaling init process caused "permission denied"**
: unknown

I have verified all the possibilities but could not find any solution.

Can you guys help on this issue.

Thanks in advance.

**Comment by stephen-turner** [comment]
This github tracker is for Docker for Windows. I think you want moby/moby instead.

**Comment by StanislavBerezin** [comment]
:(

**Comment by Thaisap** [comment]
try this command: 
sudo killall containerd-shim
