### ISSUE TITLE
Adding files during build fails when deduplication is used

### ISSUE THREAD

**Issue by Rainmaker52** [docker/for-win#2016]
> Please, check https://docs.docker.com/docker-for-win/troubleshoot/.
_I would like to, but that page returns a 404_

  - [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have submitted Diagnostics. _Seems to contain some plaintext passwords. Would rather not send these_
  - [ ] I have included the Diagnostics ID in this Issue: 
  - Windows Version: Windows 10 1803 17134.5
  - Docker for Windows Version: 18.03.1-ce, build 9ee9f40

### Expected behavior
Files should be able to be added to the build process, regardless of deduplication being used.

### Actual behavior
Files that are deduplicated using Windows deduplication cannot be added during a build. Errors are displayed in the build, such as 

> ERRO[0013] Can't add file \\?\D:\temp\servicing\Packages\Package_220_for_KB4135051~31bf3856ad364e35~amd64~~10.0.1.1.cat to tar: readlink \\?\D:\temp\servicing\Packages\Package_220_for_KB4135051~31bf3856ad364e35~amd64~~10.0.1.1.cat: The system cannot find the file specified.

### Steps to reproduce the behavior

From powershell:
  1. 
```
PS D:\> Copy-Item -Recurse C:\Windows\servicing D:\Temp\
PS D:\> Copy-Item -Recurse C:\Windows\servicing D:\Temp\dedupme
PS D:\> Set-Content -Path D:\Temp\Dockerfile -Value @"
>> FROM microsoft/windowsservercore
>> ADD . \TempTest
>> "@
PS D:\> cd \temp
PS D:\temp> docker build .
Sending build context to Docker daemon  58.37kB
Step 1/2 : FROM microsoft/windowsservercore
 ---> ad6116672030
Step 2/2 : ADD . \TempTest
 ---> 78784d9f34f7
Successfully built 78784d9f34f7

```
  2.  Now, add reparse points to the files and try again.
```
PS D:\temp> Start-DedupJob -Type Optimization -Volume D: -Wait

Type               ScheduleType       StartTime              Progress   State                  Volume
----               ------------       ---------              --------   -----                  ------
Optimization       Manual                                    100 %      Completed              D:


PS D:\temp> docker build .
ERRO[0000] Can't add file \\?\D:\temp\dedupme\CbsApi.dll to tar: readlink \\?\D:\temp\dedupme\CbsApi.dll: The system cannot find the file specified.
ERRO[0000] Can't add file \\?\D:\temp\dedupme\CbsMsg.dll to tar: readlink \\?\D:\temp\dedupme\CbsMsg.dll: The system cannot find the file specified.
ERRO[0001] Can't add file \\?\D:\temp\dedupme\Packages\Microsoft-OneCore-Common-DriverClasses-Core-Package~31bf3856ad364e35~amd64~en-US~10.0.17134.1.cat to tar: readlink \\?\D:\temp\dedupme\Packages\Microsoft-OneCore-Common-DriverClasses-Core-Package~31bf3856ad364e35~amd64~en-US~10.0.17134.1.cat: The system cannot find the file specified.
ERRO[0001] Can't add file \\?\D:\temp\dedupme\Packages\Microsoft-OneCore-Common-DriverClasses-Core-Package~31bf3856ad364e35~amd64~~10.0.17134.1.cat to tar: readlink \\?\D:\temp\dedupme\Packages\Microsoft-OneCore-Common-DriverClasses-Core-Package~31bf3856ad364e35~amd64~~10.0.17134.1.cat: The system cannot find the file specified.

```

**Comment by rn** [comment]
@Rainmaker52 thank you for the detailed report. This looks like an issue with the Windows container implementation and is not specific to the Docker for Windows application (for which this tracker is).  So I'm closing this. Could you instead open an issue on the upstream repository https://github.com/moby/moby where most of the Windows container development happens. Docker for Windows just consumes the upstream moby code for Windows containers, so this is a better place for it.
Thanks
