### ISSUE TITLE
Stuck in Docker is Starting

### ISSUE THREAD

**Issue by NioZero** [docker/for-win#2017]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have submitted Diagnostics
  - [X] I have included the Diagnostics ID in this Issue
  - Windows Version: 
![capture_20180509_104544](https://user-images.githubusercontent.com/1264186/39818046-4ab4e184-5376-11e8-8afa-0e7d61197df6.png)

  - Docker for Windows Version:
![capture_20180509_104524](https://user-images.githubusercontent.com/1264186/39818024-45038e7a-5376-11e8-8612-491ffd85fdef.png)

### Expected behavior
Service Started

### Actual behavior
Stuck in "Docker is starting"

### Information

Diagnostic ID B565AD03-F26B-4AB7-AC17-B2540C1E5112/2018-05-09_10-37-34

### Steps to reproduce the behavior

  1. Fresh Install of Docker
  2. After Windows Restart Docker is trying to start automatically

**Comment by jasonbivins** [comment]
Hi - We don't actually support Docker for Windows (CE) running on Windows Server - so I'm going to go ahead and close this issue.
https://docs.docker.com/docker-for-windows/install/#what-to-know-before-you-install


The basic EE version for Server 2016 is free and is supported by Microsoft
https://www.docker.com/docker-windows-server
