### ISSUE TITLE
docker pull returns error when finish extracting

### ISSUE THREAD

**Issue by Mico-Fucho** [docker/for-win#2019]
### Expected behavior
Pull an image from registry (microsoft/nanoserver)

### Actual behavior
After download the image, when extracting has finished, I get the following error message:
failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer \\?\C:\ProgramData\Docker\windowsfilter\xxxxxxxxxx: Acceso denegado.

Same result with any other image

### Information
  - Diagnostic ID: 
     4D2A4BD3-85A7-4319-9F15-12A325A4CC3C/2018-05-10_06-10-19
  - dockercli -Version command result:
     Docker for Windows
     Version: 18.03.1-ce-win65 (17513)
     Channel: stable
     Sha1: 93354b38bd7210badafff8e0ce1f0be9a465be83
     OS Name: Windows 10 Pro
     Windows Edition: Professional
     Windows Build Number: 16299
  - I've uninstall/install Docker four times with two differents versions. Same result
### Steps to reproduce the behavior
  - Command on Powershell: 
     docker pull microsoft/nanoserver
  - Complete message after executing 'docker pull' command:
     PS C:\Program Files\Docker\Docker> docker pull microsoft/nanoserver
     Using default tag: latest
     latest: Pulling from microsoft/nanoserver
     bce2fbc256ea: Extracting [=========....     ....===============>]  252.7MB/252.7MB
     58518d668160: Download complete
     failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer \\?\C:\ProgramData                 \Docker\windowsfilter\xxxxx: Acceso denegado.

**Comment by jasonbivins** [comment]
It looks like your firewall is interfering - this error pops up between layers getting downloaded and extracted.
`
[06:08:59.963][WindowsDaemon  ][Error  ] No se puede conectar con el controlador de 'Escipion.spqr.es:6901'. Motivo: No se puede establecer una conexi�n ya que el equipo de destino deneg� expresamente dicha conexi�n 192.168.1.132:6901. Aseg�rese de que el controlador de pruebas est� en l�nea y se puede acceder a �l desde este equipo. Compruebe que el firewall de este controlador de pruebas no est� bloqueando la conexi�n.`
