### ISSUE TITLE
Docker about fails, no settings available KERNELBASE.dll

### ISSUE THREAD

**Issue by ccuster68** [docker/for-win#2022]
I am trying to get to settings within docker.

I right click the whale in task bar and only see about, I click about and docker fails.

I would expect to see settings.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have submitted Diagnostics
  - [ ] I have included the Diagnostics ID in this Issue
  - Windows Version:  Windows 10 Pro, 1709 (OS Build, 16299.192)
  - Docker for Windows Version:
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:21:42 2018
  OS/Arch:      windows/amd64
  Experimental: false

### Expected behavior
See settings and be able to click about without Docker failing

### Actual behavior
Only see about and docker fails when I click it

### Steps to reproduce the behavior

  1.  Right Click Whale in task 
  2. Click on about
[log.txt](https://github.com/docker/for-win/files/1992066/log.txt)

**Comment by rn** [comment]
how does it fail?

**Comment by ccuster68** [comment]
![1-docker](https://user-images.githubusercontent.com/13024963/39928282-cae03362-54e9-11e8-8ea9-b7733201448a.JPG)
![2-docker](https://user-images.githubusercontent.com/13024963/39928289-cd7ab26e-54e9-11e8-8061-8c3c09560c59.JPG)

I see the following and docker just fails.  I included the logs on the first post.

Thanks

**Comment by jasonbivins** [comment]
@ccuster68  What else do you have running?  It looks like there's a conflict, or a corrupt installation

`07:34:43.291][WindowsDaemon  ][Error  ] Faulting application name: Docker for Windows.exe, version: 18.3.1.17513, time stamp: 0x5ae73e38
Faulting module name: KERNELBASE.dll, version: 10.0.16299.15, time stamp: 0x4736733c
Exception code: 0xc000041d
Fault offset: 0x0000000000013fb8
Faulting process id: 0x1c3c
Faulting application start time: 0x01d3e86b66aae954
Faulting application path: C:\Program Files\Docker\Docker\Docker for Windows.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll`
