### ISSUE TITLE
Unable to start the Docker in Windows 10 Enterprise 

### ISSUE THREAD

**Issue by karate1105** [docker/for-win#2024]
- [ X] I have tried with the latest version of my channel (Stable or Edge)
  - [X ] I have submitted Diagnostics
  - [ X] I have included the Diagnostics ID in this Issue
  - Windows Version: Windows 10 version 1803
  - Docker for Windows Version:18.03.1-ce-win65 (17513)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by rn** [comment]
closing. there are no details nor diagnostics. Please re-open/open a new issue if you have the details. Thanks
