### ISSUE TITLE
Unable to run docker hello world on Windows (or anything else)

### ISSUE THREAD

**Issue by tbarlow12** [docker/for-win#2026]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue
  - Windows Version: 10, build 16299  

  - Docker for Windows Version: Docker version 18.03.1-ce, build 9ee9f40

### Expected behavior
Running Hello world example
### Actual behavior
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.37/containers/create: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
### Steps to reproduce the behavior

  1. docker run hello-world

**Comment by rn** [comment]
closing as not diagnostics ID is supplied. Please re-open or create a new issue with an diagnostics ID. Without, we are not able to help.

**Comment by kenorb** [comment]
Make sure you ran the desktop app by typing _Docker_ in Start menu.
