### ISSUE TITLE
docker run hello-world docker: Error response from daemon: container 5c1a31536da44a

### ISSUE THREAD

**Issue by sl5net** [docker/for-win#2027]
i used new docker installation. no reproos till yet.
i tried starting with 
https://docs.docker.com/get-started/#prepare-your-docker-environment

in this very first steps i got this error:

>docker run hello-world
docker: Error response from daemon: container 5c1a31536da44a

ID
E5A21269-9F1A-4CB3-A811-0D7284EB1B17/2018-05-13_20-29-54

please help

i restarted windows and tried again:
Microsoft Windows [Version 10.0.16299.431]
>docker run hello-world
docker: error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.37/containers/create: open //./pipe/docker_engine: Das System kann die angegebene Datei nicht finden. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
See 'docker run --help'.

**Comment by sl5net** [comment]
![2018-05-13 21_08_09-einstellungen](https://user-images.githubusercontent.com/5634759/39970779-d6d79bba-56f1-11e8-8157-be08c6e1dc3c.png)

**Comment by sl5net** [comment]
i did the follwong.
disabled hyper v. 
started bios, but dont changed anything there. closed bios witouht saving.
started windows Enabled hyper v. windows says needed restart. i clicked yes.
thats it. i dont know the reasons. but it worked. lets see how long ;)

Microsoft Windows [Version 10.0.16299.431]                                       
(c) 2017 Microsoft Corporation. Alle Rechte vorbehalten.                         
                                                                                 
C:\fre\private\docker>docker run hello-world                                     
                                                                                 
Hello from Docker!                                                               
This message shows that your installation appears to be working correctly.       
                                                                                 
To generate this message, Docker took the following steps:                       
 1. The Docker client contacted the Docker daemon.                               
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.        
    (windows-amd64)                                                              
 3. The Docker daemon created a new container from that image which runs the     
    executable that produces the output you are currently reading.               
 4. The Docker daemon streamed that output to the Docker client, which sent it   
    to your terminal.                                                            
                                                                                 
To try something more ambitious, you can run a Windows Server container with:    
 PS C:\> docker run -it microsoft/windowsservercore powershell                   
                                                                                 
Share images, automate workflows, and more with a free Docker ID:                
 https://cloud.docker.com/                                                       
                                                                                 
For more examples and ideas, visit:                                              
 https://docs.docker.com/engine/userguide/

**Comment by sl5net** [comment]
C:\fre\private\docker\test18-05-14_05-27>docker stop 8e008ebf3ad7
8e008ebf3ad7

C:\fre\private\docker\test18-05-14_05-27>docker container ls
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS
               NAMES
5227976cb9bb        friendlyhello       "python app.py"     About an hour ago   Up About an hour    0.0.0.0:4001->80/tcp   SOMENAME

C:\fre\private\docker\test18-05-14_05-27>docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS
     PORTS                  NAMES
5227976cb9bb        friendlyhello       "python app.py"     About an hour ago   Up About an hour
     0.0.0.0:4001->80/tcp   SOMENAME
8e008ebf3ad7        friendlyhello       "python app.py"     6 hours ago         Exited (137) About an hour ago                          eloquent_bhaskara

C:\fre\private\docker\test18-05-14_05-27>

**Comment by sl5net** [comment]
Please. Helpful for other beginner:
 In my opinion, someone should now adjust the tutorial at https://docs.docker.com/get-started/part2/.
Discussed here: https://stackoverflow.com/questions/50323199/docker-error-no-such-container-friendlyhello/50323301#50323301

**Comment by jasonbivins** [comment]
Hi @sl5net 
Thanks for the feedback, I'll submit this to the docs team for review.

**Comment by jiaoshannnnn** [comment]
docker run hello-world ,I encounted:
docker: Error response from daemon: container 63565d4aab362f637961533eaaafaa79c3321ed74862c4baefe82c7faa6eb1b9 encountered an error during CreateContainer: failure in a Windows system call: An address incompatible with the requested protocol was used. (0x273f) extra info: {"SystemType":"Container","Name":"63565d4aab362f637961533eaaafaa79c3321ed74862c4baefe82c7faa6eb1b9","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\63565d4aab362f637961533eaaafaa79c3321ed74862c4baefe82c7faa6eb1b9","Layers":[{"ID":"ae921cd3-f8b0-537a-a9d8-ca01c0c6ef2f","Path":"C:\\ProgramData\\Docker\\windowsfilter\\23efc36c4323f18eb912ac8db313872e679388e9af13fda24d44a48c5a0f57bc"},{"ID":"efd1580f-b14c-553e-be8b-abbddcc7a3d2","Path":"C:\\ProgramData\\Docker\\windowsfilter\\cff7b6f360b8db1cbf1440f298916c12e5d58ae389908984c24dfa39577d0b39"},{"ID":"ce482223-279a-5024-81d4-eb1cc4fd4e3f","Path":"C:\\ProgramData\\Docker\\windowsfilter\\f02b3046be44ef27e0b2323a2a94bef30e982d170ca4c9727081c4bcc35eabcb"},{"ID":"217528ef-2f47-5a6d-85b8-ca551f2b946f","Path":"C:\\ProgramData\\Docker\\windowsfilter\\9a9a82180721af2fe8f4fc5167bd25760c8fd534fe6470255ecb05f4cdbb8e80"}],"HostName":"63565d4aab36","HvPartition":true,"EndpointList":["fdf2681a-2223-4c60-b61f-617c3cae5a78"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\f02b3046be44ef27e0b2323a2a94bef30e982d170ca4c9727081c4bcc35eabcb\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}.

call for help,many thanks
