### ISSUE TITLE
service container becomes disconnected from overlay network

### ISSUE THREAD

**Issue by davidwmartines** [docker/for-win#2029]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have submitted Diagnostics
  - [ ] I have included the Diagnostics ID in this Issue
  - Windows Version: Windows Server version 1709, with Containers (16299.15.amd64fre.rs3_release.170928-1534)
  - Docker for Windows Version:  Docker version 17.06.2-ee-6, build e75fdb8

### Expected behavior
Container remains connected to swarm-mode overlay network.
### Actual behavior
About an hour after container is started, it appears to have lost its connection to overlay network.
### Information

*The container in question was attached to overlay network successfully, and is using dnsrr mode.*
Swarm mode.  Ubuntu master node.  Windows server 1709, with containers node.   All on Azure Virtual Machines.

### Steps to reproduce the behavior

1. Create a service in docker swarm, with a dnsrr network connection to an overlay network in the stack.
2.  Inspect the overlay network and observe container for service is connected with an IP address.
3.  From another container on the network, confirm that `Test-Netconnection -computername <service-name-of-subject-container> -port <published-port-of-service>` is successful.
4.  Start powershell session in subject container, and run `ipconfig \all` and confirm **Hyper-V Virtual Ethernet Adapter # 4** is listed, with connection on expected IP address.
3.  Repeat every 10 minutes or so, and observe that eventually  **Hyper-V Virtual Ethernet Adapter # 4** is no longer listed, and other containers cannot connect to it.

**Comment by jasonbivins** [comment]
Hi - We don't actually support Docker for Windows (CE) running on Windows Server - so I'm going to go ahead and close this issue.
https://docs.docker.com/docker-for-windows/install/#what-to-know-before-you-install


The basic EE version for Server 2016 is included with Windows and is supported by Microsoft
https://www.docker.com/docker-windows-server
