### ISSUE TITLE
com.docker.localhost-forwarder.exe using 1 full CPU core when Docker is idle after resume from sleep

### ISSUE THREAD

**Issue by brianholley** [docker/for-win#2031]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue
  - Windows Version: 16299.431
  - Docker for Windows Version: 18.03.1-ce-win65 (17513) 

### Expected behavior

Docker processes don't consume excess CPU cycles during idle

### Actual behavior

com.docker.localhost-forwarder.exe frequently uses more than 1 full CPU core when Docker is idle after resuming the machine from sleep

### Information

Diagnostic ID: 8B27E061-FABC-4C20-89E5-E63B12706E63/2018-05-14_20-32-54

### Steps to reproduce the behavior

Steps are not deterministic, but happen frequently:
  1. Start the Docker daemon
  2. Run a container
  3. Stop the container
  4. Put the machine to sleep
  5. Wake the machine

**Comment by jasonbivins** [comment]
@brianholley 
Do you normally have containers running when you see this issue? Or does it happen at random?

**Comment by jan11011977** [comment]
I also ran into this problem. Here is a crashdump that I took of the process while it was in this state (using 1 full core 100% of the time).
[com.docker.localhost-forwarder.zip](https://github.com/docker/for-win/files/2222947/com.docker.localhost-forwarder.zip)

**Comment by ronorato** [comment]
I have seen this issue multiple times on my laptop, usually having a reboot.  I usually have to kill off the process so that I can do other tasks.  I have recently installed Docker on a laptop that never had it installed before, so I do not yet have any containers running.   I am at the point where I have had to disable Docker from auto-starting so that it does not kill my laptop while it starts up.

**Comment by KiraResari** [comment]
I am also experiencing this issue. There are no containers running, and yet Docker is running at full steam. Why does this happen?

**Comment by smrutiranjantripathy** [comment]
I'm facing the same issue on windows version 1607 (OS build 1493.2363).  Even if there is no container running, com.docker.localhost-forewarder (Background process) is consuming approximately 50 % of the CPU.
