### ISSUE TITLE
docker command not found

### ISSUE THREAD

**Issue by idontusenumbers** [docker/for-win#2037]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue
  - Windows Version: Microsoft Windows [Version 10.0.16299.431]
  - Docker for Windows Version: Version 18.03.1-ce-win65 (17513)

### Expected behavior
`docker` command is found on non-admin command prompt

### Actual behavior
`docker` command is not found on non-admin command prompt

### Information
A diagnostic was uploaded with id: E45B55A5-4BF4-402C-AECC-D107AF621A9D/2018-05-15_19-27-32

### Steps to reproduce the behavior

  1. Install docker per instructions at https://docs.docker.com/docker-for-windows/
  2. Open Command Prompt or PowerShell and run docker

the `docker` command works on Command Prompt opened as Administrator

**Comment by idontusenumbers** [comment]
Seems a restart (or maybe just a log off) is required as I just restarted and now the command works from a non-admin prompt.

The docs should be updated and maybe instructions added to the install process.

Although if a method exists that accomplishes the same thing without restarting, that would be best.

**Comment by rn** [comment]
@idontusenumbers we add the Path to `docker` to the user's `PATH` on install and a log out/restart should not be required, at least I don't have to do it when I install it. It's likely that you need to open a new powershell/CMD window after install to get the updated path.

**Comment by idontusenumbers** [comment]
I thought opening a new cmd is what I needed to do too but it still didn't have the proper path info.

**Comment by mat007** [comment]
@idontusenumbers could you type `set path` in CMD for both admin and non-admin and report the result?

**Comment by idontusenumbers** [comment]
Yup, too late =/

**Comment by ebosveld** [comment]
I have this problem now. The Docker deamon is running, so it's weird behaviour. Will restart and see what happens. This is the result from `set path`:

`Path=C:\app\oracle\product\12.1.0\dbhome_1\bin;C:\app\ThinkPad-W541\product\11.2.0\client_1;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Development\apache-maven-3.3.9\bin;C:\Python27;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Git\cmd;C:\Development\chromedriver_win32;C:\Program Files\PuTTY\;C:\Program Files\nodejs\;C:\WINDOWS\System32\OpenSSH\;C:\Ruby24-x64\bin;C:\Users\ThinkPad-W541\AppData\Local\Microsoft\WindowsApps;C:\Users\ThinkPad-W541\AppData\Local\atom\bin;C:\Users\ThinkPad-W541\AppData\Local\Programs\Fiddler;C:\Users\ThinkPad-W541\AppData\Roaming\npm;C:\Program Files\Microsoft VS Code\bin;C:\Users\ThinkPad-W541\AppData\Local\Microsoft\WindowsApps;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.RB;.RBW`

**Comment by anthonyjoanes** [comment]
I have the same issue but all okay when I reboot the machine. I tried deleting the machines from virtualbox so that it recreates them when starting the shell but still docker not recognized as a command
