### ISSUE TITLE
docker-compose v2 context .

### ISSUE THREAD

**Issue by dantecoding** [docker/for-win#2041]
Diagnostic id : 48796B1A-56B2-44B4-AA57-D21F270A2AF1/2018-05-16_20-46-52
OS : windows 10 1803

http://prntscr.com/jiq8yx 

files path was working before update on docker 18.05.0-ce

http://prntscr.com/jiq9so docker version

When i starting build I gettin error.
Building php-fpm
ERROR: Cannot locate specified Dockerfile: php\Dockerfile

**Comment by GiorgioG** [comment]
Same for me.  Diagnostic Id: 41952F7F-78C2-4797-9034-2198A411B257/2018-05-16_23-41-50
18.05.0-ce-win66 (17760)
ERROR: compose.cli.errors.log_api_error: Cannot locate specified Dockerfile: src\WebApplication\Dockerfile

**Comment by GiorgioG** [comment]
@dantecoding rolled back to v18.03.1-ce-win65 (17513) Channel: stable 93354b3 and I'm back up and running.

**Comment by dantecoding** [comment]
@GiorgioG yeah, i did rollback on v18.03 and works fine.
