### ISSUE TITLE
Daemon error Page Moved

### ISSUE THREAD

**Issue by fpasquer** [docker/for-win#2045]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B85B8910-FDB1-4472-8437-C84913A8500F/2018-05-18_09-31-00

### Information

  - Windows Version: **windows 10 entreprise 1703 build 15063.1029**
  - Docker for Windows Version: **18.03.1-ce**

### Steps to reproduce the behavior
1: docker-machine create --driver hyperv --hyperv-virtual-switch "Primary Virtual Switch" --engine-env HTTP_PROXY="http://login:password in html@prox_company/" --engine-env HTTPS_PROXY="http://login:password in html@prox_company/" default

2: & "C:\Program Files\Docker\Docker\Resources\bin\docker-machine.exe" env | Invoke-Expression

3: docker pull microsoft/windowsservercore

Hello I got this issue than yesterday with docker on windows 10 entreprise. 

`PS C:\WINDOWS\system32> docker pull microsoft/windowsservercore
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: Page Moved`

I didn't find any other person with the same error message on google...

Some one got it already? 

About my self, I m behind a proxy company
Docker is set to run windows images
I did The VM with hyper-v with an external network.

I don't know if the issue from that, but it's strange --> check the picture attached
![image](https://user-images.githubusercontent.com/16100017/40222553-2bfd68c2-5a80-11e8-9689-ae9e6ce1f293.png)

Thank you for your time

**Comment by rn** [comment]
Why do you use the `docker-machine` commands? They should not be necessary, neither does the setting of the environment variables. Docker for Windows creates its own VM. Also I'm confused how this relates to the Windows containers you then try to pull.

Could you provide more details?
