### ISSUE TITLE
Installer running in container fails with error 1719

### ISSUE THREAD

**Issue by cristian-vescan** [docker/for-win#2047]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Correctly install a MSI setup.
In the Dokerfile I have 
```
# escape=`
FROM microsoft/windowsservercore:1803
SHELL [ "powershell", "-Command"]
ADD "http://download.backup4all.com/download/setup/b4asetup.msi" c:/msi/
RUN Start-Process msiexec.exe -ArgumentList '-i', 'c:\msi\b4asetup.msi', '/quiet', '/norestart' -NoNewWindow
```
### Actual behavior
The install fails with with error 1719.
`Error 1719. The Windows Installer Service could not be accessed. This can occur if you are running Windows in safe mode, or if the Windows Installer is not correctly installed. Contact your support personnel for assistance. `

### Information

  - Windows Version: Windows Server 1803 - 10.0.17134.1
  - Docker for Windows Version: 17.06.2-ee-10
          - Storage Driver: windowsfilter

  The same Dockerfile works on Windows 10 but fails on Windows Server 1803.
  This happens all the time.
  I don't know how to submit diagnostics from command line

### Steps to reproduce the behavior

  1. Using the Dockerfile listed above run `docker build`
  2. An error might or might not be displayed during Step 3/5
      ```T h e   W i n d o w s   I n s t a l l e r   S e r v i c e   c o u l d   n o t   b e   a c c e s s e d .   T h i s   c a n   o c c u r   i f   t h e   W i n d o w s   I n s t a l l e r   i s   n o t   c o r r e c t l y   i n s t a l l e d .   C o n t a c t   y o u r   s u p p o r t   p e r s o n n e l   f o r   a s s i s t a n c e .```
  3. Start a container and verify that the `dir "C:\Program Files (x86)"` command lists only 
```
common files
internet explorer
Microsoft.NET
WindowsPowerShell
```

**Comment by jasonbivins** [comment]
Hi @cristian-vescan   The for-win repo is for CE issues, you're running EE
This appears to be an issue with the way the  Windows container image is calling an installer, so you'll need to reach out to MS support   https://success.docker.com/article/where-to-get-help-with-windows
