### ISSUE TITLE
Checkpoints cannot be created - criu not found

### ISSUE THREAD

**Issue by MatthiasF999** [docker/for-win#2049]
- [X] I have tried with the latest version of Stable and Edge
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 1B282871-896E-4CFB-9BEB-34A59CA4F976/2018-05-18_22-16-18

### Expected behavior
A checkpoint of a container is created with `docker checkpoint create`.

### Actual behavior
criu is not found.

Error mesage:
`Error response from daemon: Cannot checkpoint container checkpoint-test: docker-runc did not terminate sucessfully: CRIU version check failed: exec: "criu": executable file not found in $PATH path= /var/run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/63208e73cd1ca2edc61f129f07c16d5044d4cc455b1c27dc5c2fcf8f54a8e591/criu-dump.log: unknown`

### Information

  - Windows Version: Windows 10 Build 17672
  - Docker for Windows Version: 18.05.0-ce

### Steps to reproduce the behavior

  1. `docker run --name checkpoint-test -e "SLEEP_SECONDS=1" benwhitehead/env-loop`
  2. `docker checkpoint create checkpoint-test checkpoint1`

**Comment by nevries** [comment]
Same happens on:

Mac os: 10.13.6 (17G65)
Docker: 18.06.0-ce-mac70 (26399)

**Comment by whelanp** [comment]
Same on the latest windows stable.

Version 18.06.1-ce-win73 (19507)
Channel: stable

@jasonbivins do you have a link to the bug report ?

**Comment by Ahlid** [comment]
+1

**Comment by josef-stromsky** [comment]
+1
