### ISSUE TITLE
Cannot share drive on Windows 10

### ISSUE THREAD

**Issue by LeGaS** [docker/for-win#2051]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Sharing a drive is possible without entering a password.

### Actual behavior

Sharing a drive always requires a password.

### Information

I have an account which does not have a password and when I am trying to share a drive, the authentication modal pops up and asks for a username and password. The OK button is disabled until I type something in the password field, therefore I cannot share the drive.

  - Windows Version: Windows 10 Pro, Version 1803
  - Docker for Windows Version: Version 18.03.1-ce-win65 (17513)
Channel: stable
93354b3

### Steps to reproduce the behavior

  1. Share a drive
  2. Click Apply
  3. Enter username and leave the password field empty

**Comment by justin-twys** [comment]
same here!
