### ISSUE TITLE
Container fails to start (it "stalls forever"...)

### ISSUE THREAD

**Issue by mpagani1968** [docker/for-win#2054]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Container fail to start

### Actual behavior
We have started docker in debug mode and we've seen it always remains at this step (see the full log in attach):
.....
time="2018-05-21T12:13:53.382606400+02:00" level=debug msg="libcontainerd: starting container  f69737c10688aa7242a04904f
a3f28749bbd152f1c5df0337806f74128de9d5b"
time="2018-05-21T12:13:53.382606400+02:00" level=debug msg="HCSShim::Container::Start id=f69737c10688aa7242a04904fa3f287
49bbd152f1c5df0337806f74128de9d5b"

### Information
  - Windows Version: Server 2016 version 1607
  - Docker for Windows Version: 17.06.2-ee-11

### Steps to reproduce the behavior
We are installing Docker on a new server Windows 2016 and we are experiencing a "stall status" on "docker container run ...".
Firstly, we have stopped our antivirus (Symantec Endpoint Protection), then we have installed Docker following all steps stated in https://docs.docker.com/install/windows/docker-ee/:
- Open a PowerShell command prompt (as Administrator), and type the following commands:
	Install-Module DockerMsftProvider -Force
	Install-Package Docker -ProviderName DockerMsftProvider -Force
- Check if a reboot is required, and if yes, restart your instance:
	(Install-WindowsFeature Containers).RestartNeeded
- If the output of this command is Yes, then restart the server with:
	Restart-Computer
- Test your Docker EE installation by running the hello-world container.
	docker container run hello-world:nanoserver
	
When we've run the last step, it has downloaded the newer image for hello-world:nanoserver, but it "stalls" without showing the "Hello from Docker" message.

We've then tried to start "docker" in debug mode (dockerd -D) and we've tried again to run "docker container run hello-world:nanoserver": it reaches the "Start" phase, but it never really starts...
I've attached the "log" traced by this last test (docker_trace.txt).

How could we check why it "stalls" without starting?

[Docker_trace.txt](https://github.com/docker/for-win/files/2025983/Docker_trace.txt)

**Comment by rn** [comment]
This issue tracker is for the Docker for Windows application, which runs on Windows 10. To get help with Docker on Windows Server please see http://success.docker.com/article/where-to-get-help-with-windows.
Thanks
