### ISSUE TITLE
unable to switch to linux containers

### ISSUE THREAD

**Issue by alexgman** [docker/for-win#2056]
I'm running this version of windows on my host machine:

![image](https://user-images.githubusercontent.com/4227695/40378030-0230d750-5db8-11e8-8f38-2a1e7f72b8ae.png)

I'm attempting to switch to linux containers like so:

![image](https://user-images.githubusercontent.com/4227695/40378051-0e0d0da0-5db8-11e8-8c5f-3eb1abfb7af9.png)

and getting the following message:

![image](https://user-images.githubusercontent.com/4227695/40378067-1ae69ca8-5db8-11e8-861f-ebc097cb5dba.png)

**Comment by rn** [comment]
Could you upload diagnostics and provide the ID?

**Comment by jasonbivins** [comment]
@alexgman I'm not having any issues with this on the same version, can you provide a diagnostic ID?
follow the first section here: https://docs.docker.com/docker-for-windows/troubleshoot/
