### ISSUE TITLE
docker-compose DNS resolution not working and timing out

### ISSUE THREAD

**Issue by abjrcode** [docker/for-win#2058]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 5BAC09FD-6C88-49CE-ACBD-0A4B45B91E8D/2018-05-22_19-56-53

### Expected behavior
Expect name resolution to work according to documentation.
### Actual behavior
It doesn't
### Information

  - Windows Version: Version 1803 (OS Build 17134.1)
  - Docker for Windows Version:
```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:21:42 2018
  OS/Arch:      windows/amd64
  Experimental: false
```

### Steps to reproduce the behavior
version: "3.6"
services:
  web:
    build: ./website/
    ports:
      - "8080:80"
    depends_on:
      - database
  database:
    build: ./database/
    environment:
      sa_password: some_pass
      ACCEPT_EULA: Y
I am using windows containers and more specifically `microsoft/aspnet:latest` and `microsoft/sql-server-windows:latest`
I can't resolve `database` from within the `web` container
I am not doing anything special inside the images of `web` nor `database`, just copying files
I can successfully ping by IP, but `nslookup` on the ip times out

**Comment by Dressee** [comment]
I am experiencing the same issue on Windows Server 1709 (Build 16299)
I am using docker version 17.06.2-ee-11 build 06fc007

After docker compose down/up from within my containers I cannot resolve hostnames.
Pinging on IP works fine.

**Comment by Dressee** [comment]
My issue can be pinpointed to docker network trying to open a socket on an existing ip:port(53) for DNS.
After docker compose up/down the default network is removed and recreated but the TCP Connection on port 53 remain in listen state.

After some iterations the newly created docker network will try to use an existing socket and this will fail. The result is that DNS resolving will not work.

**Comment by gingters** [comment]
I have the same issue. I got a docker-compose file, started it up, and my host is unable to connect to the container via the alias (which is required, as one of the apps running in a container creates an url pointing to the other container via its alias).


I have the same docker for windows version as the OP.

**Comment by BenRedmond** [comment]
I believe I'm having the same issue. Pretty new to docker and not much background in networking but when i get my containers up and running using docker-compose up, I can attach a shell to one of them and ping other containers on the same network. However my apps can't seem to communicate using the DNS.

`version: '3.4'

services:
  angular:
    image: angular
    container_name: angularcontainer
    build:
      context: ../angular
      dockerfile: Dockerfile
    ports:
      - "8000:80"

  coreapi:
    image: coreapi
    container_name: coreapicontainer
    build:
      context: ../coreapi
      dockerfile: Dockerfile
    ports:
      - "9000:80"`

**Comment by jmajoor** [comment]
I have the same problem on the EE version on Windows Server 1803.
I noticed that sometime (if my ping doesn't timeout) that the IP it resolves to is incorrect and not the IP of the container with the alias. It never seems to be able to resolve the name for the service and the alias (if it resolves) is resolved to an IP not on the vnet of the service.

Is there any work around? How can a container / service discover another container. I have multiple services in my compose file and they need to communicate with each other.

Additional Information:
Client:
 Version:       17.06.2-ee-11
 API version:   1.30
 Go version:    go1.8.7
 Git commit:    06fc007
 Built: Thu May 17 06:14:39 2018
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.06.2-ee-11
  API version:  1.30 (minimum version 1.24)
  Go version:   go1.8.7
  Git commit:   06fc007
  Built:        Thu May 17 06:17:26 2018
  OS/Arch:      windows/amd64
  Experimental: false

**Comment by abjrcode** [comment]
I eventually ended up solving this by:
1. Uninstalling Hyper-V and Docker.
1. Removing all Hyper-V created adapters from `Device Manager`
1. Removing the `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\VMSMP` node completely from the registry.
1. Restarting and reinstalling the above applications

I believe it was some messed up settings in the configuration of Hyper-V adapters or switches but I couldn't find a way to diagnose it all.
Good luck to you guys.

**Comment by daschott** [comment]
There is an issue in 1803 whereby Docker DNS doesn't work. Can you apply the following firewall rules to ensure Docker DNS works again:
`New-NetFirewallRule -DisplayName "Swarm DNS" -Direction Inbound -Action Allow -Protocol UDP -LocalPort 53`
`New-NetFirewallRule -DisplayName "Swarm DNS" -Direction Inbound -Action Allow -Protocol TCP -LocalPort 53`
