### ISSUE TITLE
F54D846B-9A75-463D-9B5E-F15F9B4C53CA/2018-05-24_20-01-19

### ISSUE THREAD

**Issue by HowardEdidin** [docker/for-win#2062]
Running docker on  an Azure VM

  - [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: F54D846B-9A75-463D-9B5E-F15F9B4C53CA/2018-05-24_20-01-19

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by rn** [comment]
We unfortunately are not able to support Docker for Window running inside Windows VMs (aka nested virtualisation) as we have no control nor visibility over how the Windows VM is configured. This is explained in more detail in the documentation: https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-for-windows-in-nested-virtualization-scenarios
