### ISSUE TITLE
Can't change disk image location

### ISSUE THREAD

**Issue by peik-cm** [docker/for-win#2063]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 5438AC69-7216-4738-B26C-7689894A2632/2018-05-25_11-42-51

### Expected behavior

Changing disk image location under settings => advanced actually changes image location.

### Actual behavior

When Disk image location is changed, Docker restarts. On restart the folder is changed back to default path.

### Information

I tried to first prune all containers and make the change, but the issue remains.

  - Windows Version: 10
  - Docker for Windows Version: 18.05.0-ce-win66 (17760) edge

**Comment by jasonbivins** [comment]
@peik-cm 

Were you trying to use your E: drive?  It looks like it's not showing up as available for docker to use

`"SharedDrives":{"D":true,"C":true,"E":false},`

**Comment by peik-cm** [comment]
D:

to 31. toukokuuta 2018 klo 2.19 Jason Bivins <notifications@github.com>
kirjoitti:

**Comment by morales2k** [comment]
Same as peik-cm described... This is happening to me as well. I am trying to use the J:\

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

J:\ was compressed. I noted this caused errors, so I decompressed it.  However, Docker settings will always reset to C: (on default path) no matter what I do.

I am attempting to share only the I: and J: drives and NOT the C: drive. It is uncked in the settings GUI. 

If there is a way to hard-code config using the config.json or daemon.json in the 
`{home-user-folder}\.docker` folder, then we could probably bypass using the gui to set these things for now!? Maybe?

Anyhow... I too uploaded diagnostic info:
ID: 09FA589A-0233-480C-B19D-BFDE8A52362E/2018-07-01_15-01-20


I installed docker from the stable executable for windows a few days ago now...
You could say I'm a proud, brand spanking new docker n00blet, already hitting a wall. Maybe I did something wrong when installing docker!?

**Comment by MisoHub** [comment]
I had same problem.. and I have changed the image directory. 

First, set shared drive which include new image directory 
And then, Reset to factory defaults, with comments to @morales2k  and try to change it
If it didn't work, delete MobyLinuxVM.vhdx in directory which you want to save it (in destination)
and try again. 

I resolve this problem with that procedure. 
hope to help you.

**Comment by OtaK** [comment]
Also, through testing, I just found out that HyperV can only store images on NTFS. It was denying my ExFAT drives.

**Comment by Vantage-DS** [comment]
Same issue.

Changing the location to D:, it resets to C:\ when Docker has restarted.

Changed in settings.json
Changed in Hyper V
Changed in Gui.

Nothing works. It just resets to C:

**Comment by sodaDreamer** [comment]
For anyone else still having problems with this, I managed to fix this by killing Docker then changing the **default** Virtual Hard Disk location in 'Hyper-V Settings' (as opposed to the settings for the individual VM). After restarting Docker it then created the .vhdx in the correct location.

**Comment by jdelano0310** [comment]
I had this same issue, I just deleted the MobyLinuxVM.vhdx from the new location. I had copied the contents from the default location to the new location. Docker would fail stating the GUI id failed. So I simply deleted the file from the new location and switched it in settings, Docker recreated it in the new location just fine.

**Comment by GreatFireWall** [comment]
same problem.

**Comment by ssy341** [comment]
Same problem. Default location at C:\Users\Public\Documents\Hyper-V\Virtual hard disks, I modifed then come back again. Can I move another place?

**Comment by TBBle** [comment]
I suspect this is a duplicate of #1589, which shows a process for moving that doesn't require changing system settings or resetting your Docker image.

**Comment by Neutrino3316** [comment]
I trying everything above, no help. I discover the bug when using the [Hyper-V Manager](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/about/). I tried to migrate the disk image via Hyper-V Manager, then a useful error message pop out. It says, **can't move to a folder that is using NTFS compression**, which may look like this:
![NTFS compression](https://www.windowscentral.com/sites/wpcentral.com/files/styles/xlarge/public/field/image/2019/03/ntfs-compression-file-folder-option-windows-10.jpg?itok=3_ORgE6r)
Remeber, **don't use NTFS compression**.

**Comment by KANGOD** [comment]
> Default location at C:\Users\Public\Documents\Hyper-V\Virtual hard disks, If you want to change the location to another, make sure the target folder is empty(just no MobyLinuxVM.vhdx file). When you apply configure, docker will move VHD to the new place.
> I also get the same problem, finally I figure out the target isn't empty cause this problem.
> 
> ![image](https://user-images.githubusercontent.com/1725705/56270982-fc8a8280-6129-11e9-95f6-fdec4cf8a8f0.png)

@ssy341 's method works. I manually copied the MobyLinuxVM.vhdx file before hitting the Apply button.

@Docker team, maybe better to add a warning dialog, instead of just fallback to original folder without hint.
