### ISSUE TITLE
Cannot mount shared drive

### ISSUE THREAD

**Issue by HowardEdidin** [docker/for-win#2067]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 83B9FDC5-7DA4-4C6C-A36F-BA11B551B13D/2018-05-26_10-05-02

### Expected behavior
Shared Drive mounted
### Actual behavior
No shared drives were mounted
### Information

  - Windows Version:  10  pro
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jasonbivins** [comment]
@HowardEdidin   It looks like your user doesn't have rights to share drives.  Do you know what permissions are set for the D: drive?

```[10:03:23.342][SambaShare     ][Error  ] Unable to mount D drive: 10.0.75.1 (10.0.75.1:445) open
mount.cifs kernel mount options: ip=10.0.75.1,unc=\\10.0.75.1\D,noperm,iocharset=utf8,nobrl,mfsymlinks,vers=3.02,sec=ntlmsspi,user=HowardEdidin,domain=AzureAD,pass=********
mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) ```

**Comment by huyong007** [comment]
@jasonbivins i have the same error  and the log is same to @HowardEdidin   but i do not how to set permissions for the C:drive , can you give me some recommendations for that  ,i have fix this error six hours today but i can not fix it  ,thank you very much

**Comment by huyong007** [comment]
# Diagnostics ID: 
7113411E-1847-493D-8F85-CE9240C8597E/2018-06-10_22-41-03;
# Docker version 18.05.0-ce, build f150324
