### ISSUE TITLE
Docker for windows feedback dialog performs submit on enter

### ISSUE THREAD

**Issue by BenjaminVettori** [docker/for-win#2068]
### Expected behavior

The feedback dialog form **does not** perform a submit if enter is pressed in the **multiline** textarea.

### Actual behavior

The feedback dialog form **does** perform a submit if enter is pressed in the **multiline** textarea.

### Information

If the feedback form pops up and the user enters some text, the form is closed if the enter key is pressed. It will happen frequently, that users submit unfinished feedback, since it is natural for a user to press enter in a multiline textarea. 

### Steps to reproduce the behavior

I actually dont know how to re-open the feedback formular, but once it is opened, enter some text and press enter => Then the dialog disappears.

**Comment by LoreenRH** [comment]
Hello! 

What Docker version are you using? can you please upload a diagnostics ID? 

thanks in advance :)
