### ISSUE TITLE
How to get kubeconfig for edge kubernetes?

### ISSUE THREAD

**Issue by erikbsap** [docker/for-win#2070]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: I'm not sure if I'm allowed to do that.

### Expected behavior
I get the kubeconfig from somewhere

### Actual behavior
It's gone and it doesn't come back with reset nor with deactivate and activate again.

### Information
  - Windows Version: 10
  - Docker for Windows Version: 18.05-ce
  - Kubernetes: 1.9.6

### Steps to reproduce the behavior

You can reproduce this by configuring a fresh docker Edge installation with kubernetes (then kubectl can see the docker context), then you overwrite or delete the kubeconfig. Now it's gone. How to get it back?

Please suggest what can be done, or where a solution is documented. Thanks a lot!

**Comment by LoreenRH** [comment]
Hello, 

Did you try factory defaults or reseting the kubernetes cluster? 

In case there is a bug, a diagnostic ID would be really helpful. ✨

**Comment by erikbsap** [comment]
> Did you try factory defaults or reseting the kubernetes cluster?

Yes. Additionally I tried deactivating kubernetes cluster and reactivating it again. Currently I try reinstalling. Docker is there, but kubernetes doesn't come up for an hour.

If there is a way for me to review diagnostics I'm happy to look into it myself, but without sign-off from corp IT I can't just send it to you.
