### ISSUE TITLE
ToolTip notification when docker is restarted

### ISSUE THREAD

**Issue by jehof** [docker/for-win#2071]
It would be nice to get a ToolTip/PopUp notification (like when you start docker) that docker is started, after I use the "Restart" command from the Menu of the System Tray Icon.

**Comment by jasonbivins** [comment]
Hi @jehof 
We actually just added the second pop-up in the latest Edge release.  I just tested and confirmed that you do get two popups now. One when you click restart - the other when Docker is running again.
