### ISSUE TITLE
Cannot login via GUI.

### ISSUE THREAD

**Issue by CharlesStover** [docker/for-win#2074]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
A43975D5-3447-4BE1-BCD8-F191D866950C/2018-05-29_15-11-16

### Expected behavior
Login to work.

### Actual behavior
Login is incorrect. Inputs turn red.

### Information
  - Windows Version: 1607, build 14393.2248
  - Docker for Windows Version: 18.03.1-ce-win65 (17513)

### Steps to reproduce the behavior
Try to login.

I think it may be related to corporate proxy, however, I have configured the corporate proxy in the Docker settings (maybe these are being ignored?).

**I am able to login via `docker login` without problem.** However, this does not sync with the Docker GUI, which remains logged out. Logging in only does not work with the GUI, neither on the initial popup nor the "Sign In / Create Docker ID..." option in the context menu.

**Comment by LoreenRH** [comment]
Hello!

Can you please upload your diagnostics again? I wasn't able to find them.

**Comment by CharlesStover** [comment]
A diagnostic was uploaded with id: A43975D5-3447-4BE1-BCD8-F191D866950C/2018-05-30_09-34-35

I don't know if the diagnostic will display an ID without reaching the server, but if so, it may be that my GUI client simply is unable to connect. Perhaps it is ignoring my `HTTP_PROXY` environment variables, and/or the environment variables within its own configuration? Again `docker login` works flawlessly from command line.

**Comment by CharlesStover** [comment]
If it may be relevant, the `HTTPS_PROXY` is self-signed/otherwise-invalid.

**Comment by CharlesStover** [comment]
Were you able to find the latest diagnostics file?

**Comment by lmcarreiro** [comment]
I have a similar problem, but what is weird is that, I'm using CNTLM and it works fine to pull images, but if I try to log-in via GUI, inputs just turns red with no output in CNTLM console window. It looks like it is not trying to log-in via proxy.

More weird, if I try to log-in via console `docker login`, I see a lot of requests in CNTLM window to `registry-1.docker.io:443` and `auth.docker.io:443`, I get a `Login Succeeded` message, but still can't push images to my own repository, I got the `denied: requested access to the resource is denied` message.

Even more weird, using `docker login` with any wrong user/password I always get the `Login Succeeded` message.

I'm using Windows 10 Enterprise, 1703 OS Build 15063.296 and Docker Edge version 18.05.0-ce, build f150324. I tried in Docker Stable before and got the same behavior.

Have tried with DNS server on automatic and fixed 8.8.8.8 and both didn't work.

**Comment by lmcarreiro** [comment]
@CharlesStover When you provide wrong user/password to `docker login` on command line, do you get any error message or are you getting a success message too?

**Comment by lmcarreiro** [comment]
@chrsoo After you solved the cntlm proxy issue, are you able to log-in?

**Comment by CharlesStover** [comment]
Good find. I haven't checked that the login is actually verified in command line, nor have I tried pushing. I'll do that as soon as I can get my machine to start.

Steps I've taken today:
`docker-machine create -d hyperv default` was not working. Used PowerShell or something to fix it.
`docker-machine create -d hyperv --hyperv-virtual-switch "External" default` had to be used to get it Internet access, as the default virtual switch was invalid. [source](https://stackoverflow.com/questions/40391389/docker-stuck-on-waiting-for-ssh-to-be-available)
The machine now creates flawelessly, but doing anything docker gives the error that it can't connect to the machine.
`docker-machine env` and setting all the environment variables fixed that.
Now I can use docker commands, but I get `proxy: unknown scheme: http`
This is [a bug](https://github.com/moby/moby/issues/25740) where Docker assumes `ALL_PROXY` means "non-HTTP" proxy and tries to use it as a `socks:` connection.
Removing `ALL_PROXY` from the environment fixed this, but I'm afraid it may break other applications that rely on it. We'll see.
Now I get Forbidden when my docker commands try to connect to the machine. I fixed this by using `docker-machine env --no-proxy` [source](https://github.com/docker/machine/issues/1693)
Now docker commands work, but connecting to the Internet (e.g. `docker login`) gives me:
`Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 172.17.40.10:53: no such host`

I'll let you know when I get that working. xp

**Comment by CharlesStover** [comment]
Okay, so the above is the wrong rabbit hole. It's just me trying to recreate a copy of Docker for Windows's machine, albeit fruitless. I'll leave it in case someone finds it on Google and needs to configure a new machine. (the next step is to configure nameservers in the machine)

I upgraded to Docker for Windows _Edge_. Set DNS to 8.8.8.8 and set proxy.
I now get "lookup failed: no servers configured" when trying to resolve login.
`Error response from daemon: Get https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp: lookup %HTTPS_PROXY% on ...: read udp ...->...: i/o timeout`

FML.

**Comment by CharlesStover** [comment]
Alright, well I got `docker login` working. The issue was with DNS for some reason. Using the fixed DNS would break it (probably corporate proxy). I had to use the proxy settings with automatic DNS. Now `docker login` gives accurate login results -- failure for incorrect login, success for correct credentials.

The GUI _still does not work_ though!

And nothing about the login screen is written to the log file.

@lmcarreiro If docker login is false positives all around, try upgrading to Edge. I at least don't have false positive logins.

**Comment by lmcarreiro** [comment]
I already was on Edge version, downloaded today... I think that is because the MITM attack that my company does with its proxy.

**Comment by chrsoo** [comment]
@lmcarreiro I don't think I logged in through the user interface before but I just tried and it does not seem to work in spite of the proxy working correctly. The dialog accepts the input, the Sign-In button greys out and nothing happens.

**Comment by gauravkakkar87** [comment]
run _docker as administrator_  and `docker login` in cmd using docker ID and pass should work

**Comment by aldass** [comment]
note if you also `run as administrator` the `Docker Desktop` app on Windows, it will allow you to login to docker hub.

**Comment by lilyyjzhou** [comment]
> note if you also `run as administrator` the `Docker Desktop` app on Windows, it will allow you to login to docker hub.

this works for me~!!!!

**Comment by FerasInfeeny01** [comment]
> run _docker as administrator_ and `docker login` in cmd using docker ID and pass should work

Worked fine for me, thanks :)

**Comment by situnayakea** [comment]
We are behinde corporate ntlm proxy and I was unable to log in to docker hub via the system tray docker desktop GUI.
To resolve this I edited to docker desktop config file at : -
C:\Program Files\Docker\Docker\Docker Desktop.exe.config
adding the following lines to specify proxy
<system.net>  
    <defaultProxy useDefaultCredentials="true">  
      <proxy usesystemdefault="true"  proxyaddress="http://blahblah" bypassonlocal="true"  />  
    </defaultProxy>  
  </system.net> 

GUI now dsuccesfully logs in
