### ISSUE TITLE
Fresh installation of docker for windows, server isnt working.

### ISSUE THREAD

**Issue by PresidentCamacho** [docker/for-win#2075]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 60BCAA29-3EA2-49BB-9EC5-C75319196939/2018-05-30_16-34-13

### Expected behavior
After a fresh installation of docker for windows I tried the command docker version. It takes docker 1 minute to give a reply and this is the reply: 

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm
error during connect: Get https://192.168.99.100:2376/v1.37/version: dial tcp 192.168.99.100:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

Also all docker cli commands are slow, it takes docker roughly 1 minute to give me a reply.
Because of the server not up, docker images/ps etc doesn't work either.

### Actual behavior

The server shouldn't be non reachable.

### Information
  - Is it reproducible? Yes
  - Is the problem new? Yes
  - Did the problem appear with an update? Uninstalled docker toolbox and installed docker for windows.
  - Windows Version: Windows 10 Enterprise
  - Docker for Windows Version: 18.03.1-ce

**Comment by rn** [comment]
Do you, by any chance still have `DOCKER_HOST` set in your environment? The docker CLI shouldn't talk to `192.168.99.100`. Instead it should use a named pipe.

**Comment by PresidentCamacho** [comment]
I worked by deleting all enviroment variables containing docker in its name and then installing the edge version.

**Comment by rn** [comment]
glad to hear. It's a common issue, especially for users comming from toolbox or other envs
