### ISSUE TITLE
Docker unauthorized: authentication required 

### ISSUE THREAD

**Issue by LogX7** [docker/for-win#2076]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6C7C8B43-30FB-4975-A165-35048907AFA3/2018-05-30_15-56-19

### Expected behavior
container running
### Actual behavior

```
> docker container run -p 8080:80 -d --name n2 httpd
Unable to find image 'httpd:latest' locally
latest: Pulling from library/httpd
3d77ce4481b1: Downloading
73674f4d9403: Download complete
d266646f40bd: Download complete
ce7b0dda0c9f: Download complete
01729050d692: Download complete
014246127c67: Download complete
7cd2e04cf570: Download complete
docker: unauthorized: authentication required.
See 'docker run --help'.
```

### Information
  - Windows Version: 10 pro Version 1709
  - Docker for Windows Version: 18.03.1-ce

i have logged in using docker login -u username -p password
and i’m getting this issue alot, not just with httpd but also with django, mysql … etc

### Steps to reproduce the behavior

  1. docker container run -p 8080:80 -d --name n2 httpd

**Comment by jasonbivins** [comment]
hi @LogX7   Can you run the `docker login` command? Or sign in through the GUI?

**Comment by LogX7** [comment]
@jasonbivins i'm signed in 
<img src="https://i.imgur.com/sPQbVYH.png">

**Comment by LogX7** [comment]
anyone ???!
