### ISSUE TITLE
Docker login works diffrently on windows than macOS/Linux, on a private registry.

### ISSUE THREAD

**Issue by bvbtest** [docker/for-win#2081]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID:
13506E46-29F4-47D7-A0DA-5D0AB686D0A6/2018-05-31_11-35-30

Expected behavior
When logging in with the correct login and passphrase, the login should be successful.

Actual behavior
Error, not authorized.

Information
  - Windows Version:
Windows 10
  - Docker for Windows Version:
18.03

Example given:
  1. when on Linux
docker login -u name -p succes registry.private.domain.com
Login Succesful
  2. when on Windows , the same command on the command prompt doesn't let me login on my private registry.
docker login -u name -p succes registry.private.domain.com
Login unauthorized 401 error

**Comment by rahul24** [comment]
Trying providing argument with full name i.e  —username  —password
