### ISSUE TITLE
Unable to run various docker commands

### ISSUE THREAD

**Issue by dylanf** [docker/for-win#2086]
unable to run docker commands

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 004AE68A-5EB9-4D64-B97F-DDF51F876151/2018-06-05_09-35-08

### Actual behavior
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\windows\system32>docker-machine ls
NAME   ACTIVE   DRIVER   STATE   URL   SWARM   DOCKER   ERRORS

C:\windows\system32>docker version
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:12:05 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.37/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by dylanf** [comment]
I do have administrative rights and execute the commands from a command prompt with admin privileges - however I am running a customized corporate image of windows 10 which has antivirus that I have limited control over.

**Comment by jurby** [comment]
+1

**Comment by kenorb** [comment]
Make sure you ran the desktop app by typing _Docker_ in Start menu.
