### ISSUE TITLE
excessive memory usage in vpnkit

### ISSUE THREAD

**Issue by jtnord** [docker/for-win#2087]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 51061EC2-9F3F-4302-A4BA-4D95A2305093/2018-06-05_12-07-17

### Expected behavior

Using Docker leaves me with ample memory to do other stuff.

### Actual behavior

VPNKit is using 4GB of private bytes (VMM) and a 2GB working set which is unacceptable.

![image](https://user-images.githubusercontent.com/494726/40972690-707ffbf8-68b9-11e8-9859-0f599f86f392.png)

### Information

  - Is it reproducible?

unknown.

  - Is the problem new?

I have not seen this high memory concumption fromVPNKit before.

  - Windows Version:

win 10 1803 (17134.48)

  - Docker for Windows Version:

18.04.0-ce-win62 (17151)

### Steps to reproduce the behavior

Unsure - have just been using docker for a while.
I have OpenVPN also running and have changed between various wireless and wired networks and been connecting / disconnected into the VPN and Hibernating / restoring the machine for a few days.

**Comment by rn** [comment]
@jtnord there will be a new edge release very soon now (hopefully next couple of days) which fixes some memory leaks in VPNKit. Could you try it when it is out?

**Comment by jtnord** [comment]
@rn sure.

**Comment by rn** [comment]
@jtnord actually, it just got released :) may take a while before it makes it through the distribution, but it should be version `18.05.0-ce-win67`

**Comment by jtnord** [comment]
Seems to be much better in that release.   The memory seems to stabalise around 140MB vmm / 75MB working set now

**Comment by allyn-psyonix** [comment]
Just ran across this ticket looking into the same issue in my environment. vpnkit-bridge.exe is taking up almost 1.5GB of memory.

I am running Docker v2.2.0.4.
