### ISSUE TITLE
Cannot mount file using windows containers

### ISSUE THREAD

**Issue by yorek** [docker/for-win#2089]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C2FF7C1C-4DF5-40AF-B21C-3113905AEC6E/2018-06-06_22-23-33

### Expected behavior
Correctly mount a folder

### Actual behavior
The following error:

 ```
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container 08cc92221f972fd07eee007cc345c6818c25034b8cfe68e4522b4460e3f667a9 encountered an error during CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2) extra info: {"CommandLine":"-v D:\\Temp:c:\\Temp","User":"ContainerUser","WorkingDirectory":"C:\\","Environment":{"PSCORE":"C:\\Program Files\\PowerShell\\pwsh.exe","ProgramFiles":"C:\\Program Files"},"EmulateConsole":true,"CreateStdInPipe":true,"CreateStdOutPipe":true,"ConsoleSize":[38,184]}.
```

### Information
  - Windows Version: 10 Pro, 1803
  - Docker for Windows Version:

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:21:42 2018
  OS/Arch:      windows/amd64
  Experimental: false

### Steps to reproduce the behavior
1) make sure you have a Temp folder in C:\ drive
2) docker run -it microsoft/powershell:6.0.2-nanoserver -v C:\Temp:C:\Temp

**Comment by jasonbivins** [comment]
Hi @yorek 
I was able to repro this, so i went ahead and reported it internally as a bug.

**Comment by yorek** [comment]
Great, thanks!

**Comment by rn** [comment]
@yorek it looks like your command line slightly wrong. Specifically the volume mount argument need to be before the image name, something like:
```
docker run -it -v C:\Temp:C:\Temp microsoft/powershell:6.0.2-nanoserver 
```
works fine for me. With your command line you are basically passing `-v C:\Temp:C:\Temp` as an argument into the powershell container.

Closing this, but please report if the above does not work

**Comment by yorek** [comment]
@rn you are totally right, using the -v option before the image it works nicely. I would say that there is a bug anyway...since the -v option, when used in the wrong sequence, still seems to be accepted and in fact the returned message is:

`
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container f263ceed47beb3eec16cac545486b2168fdb1f1591490615889364aeed95fe29 encountered an error during CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2) extra info: {"CommandLine":"-v C:\\Temp:C:\\Temp","User":"ContainerUser","WorkingDirectory":"C:\\","Environment":{"PSCORE":"C:\\Program Files\\PowerShell\\pwsh.exe","ProgramFiles":"C:\\Program Files"},"EmulateConsole":true,"CreateStdInPipe":true,"CreateStdOutPipe":true,"ConsoleSize":[38,184]}.
`

that leads to the idea that the "system cannot find the file specifie" is realted to the -v option

**Comment by yorek** [comment]
Btw, thanks a lot for the help! :)
