### ISSUE TITLE
Docker become unresponsive when running PHP file in container

### ISSUE THREAD

**Issue by lurock** [docker/for-win#2096]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
PHP script runs in windows docker container without the container getting into a state where it is not responding.  

### Actual behavior
When running the container freezes without finishing the execution of the PHP code and I can no longer docker exec into it from another command line window.  The only thing I can do is run docker stop on the container. 

### Information

It is reproducible.  I have added a docker container to the hub that reproduces the issue with all the source code and the docker file.  Here is the link https://hub.docker.com/r/maindg/php-multi-process-failure/

  - Windows Version:  Windows Server Core 1803
  - Docker for Windows Version: 18.03.1-ce

### Steps to reproduce the behavior

  1. docker pull maindg/php-multi-process-failure
  2. docker run -it maindg/php-multi-process-failure

**Comment by jasonbivins** [comment]
Hi - We don't actually support Docker for Windows (CE) running on Windows Server - so I'm going to go ahead and close this issue.
https://docs.docker.com/docker-for-windows/install/#what-to-know-before-you-install


The basic EE version for Server 2016 is free to install and is supported by Microsoft
https://www.docker.com/docker-windows-server
