### ISSUE TITLE
No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by ghost** [docker/for-win#2099]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D21AF8B3-9701-441B-B1DE-08AD4E1D2A2C/2018-06-09_18-48-57

### Expected behavior
Run the hello-world image.
### Actual behavior
`docker: error during connect: Post https://127.0.0.1:2376/v1.37/containers/create: dial tcp 127.0.0.1:2376: connectex: No connection could be made because the target machine actively refused it.`
### Information

  - Windows Version: Windows 10 Pro
  - Docker Version:
`>docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm`

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jasonbivins** [comment]
@havoc-ecksdee   Can you run ```docker info ``` and share the results here?

**Comment by chupee120** [comment]
docker info
error during connect: Get http://192.168.99.100:2376/v1.37/info: dial tcp 192.168.99.100:2376: connectex: Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu.

**Comment by chupee120** [comment]
No did not found...

Le ven. 20 juil. 2018 à 5:27 PM, loulouX <notifications@github.com> a
écrit :

**Comment by juri33** [comment]
+1

**Comment by amitakamat** [comment]
+1

docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:34 2018
 OS/Arch:           windows/amd64
 Experimental:      false
error during connect: Get https://192.168.99.100:2376/v1.38/version: dial tcp 192.168.99.100:2376: connectex: No connection could be made because the target machine actively refused it.

**Comment by chupee120** [comment]
+1

**Comment by minuz** [comment]
Any update on this? Having the same issue

![image](https://user-images.githubusercontent.com/818024/52473879-0a340100-2beb-11e9-9326-8bcb9fda6dcf.png)

**Comment by mesfeb** [comment]
Hi @minuz , i was searching  answer for same problem, did you get any solution?

**Comment by KezHalls** [comment]
I am having the same issue when trying to call the hello world.

**Comment by nikhilkumarbt** [comment]
Is the issue resolved ??.. any updates on this ?

**Comment by thanhtuan12576049** [comment]
you should reinstall docker .maybe it's work . I tried reinstalling and docker works normally. goodluck

**Comment by nicolimo86** [comment]
I have the same problem, when I try to run: `docker pull hello-world`
```PS C:\WINDOWS\system32> docker pull hello-world
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp 34.197.189.129:443: connectex: No connection
could be made because the target machine actively refused it.```


PS C:\WINDOWS\system32> docker info
Client:
 Debug Mode: false
 Plugins:
  cluster: Manage Docker clusters (Docker Inc., v1.2.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 19.03.5
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 14393 (14393.3442.amd64fre.rs1_release.191219-1727)
 Operating System: Windows Server 2016 Standard Version 1607 (OS Build 14393.3443)
 OSType: windows
 Architecture: x86_64
 CPUs: 2
 Total Memory: 20GiB
 Name: tradeci-2
 ID: VYDK:LCJQ:N2KZ:44YD:Z3GQ:6J2B:F4DS:QPPB:BEME:D3GD:KYN2:5J4P
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by shrikant656** [comment]
error during connect: Get https://0.0.0.0:2376/v1.37/images/json: dial tcp 0.0.0.0:2376: connectex: No connection could be made because the target machine actively refused it.

Any update on this issue? 
Getting above error.
