### ISSUE TITLE
Docker CLI crashes hard on Windows

### ISSUE THREAD

**Issue by ocafebabe** [docker/for-win#210]
### Expected behavior

List containers

### Actual behavior

PS C:\Users\Administrator> docker ps
Exception 0xc0000005 0x1 0x4b65404 0x180008910
PC=0x180008910
...

### Information

  - Diagnostic ID: F73347E9-9567-4874-A0AB-536541F110F5/2016-11-07_18-48-13
  - Windows 10 Pro Version 1607 (OS Build 14393.351)

### Steps to reproduce the behavior

I get the same error for all Docker commands (info, run, search)!

**Comment by ocafebabe** [comment]
Full stacktrace of the error.
[docker.txt](https://github.com/docker/for-win/files/576965/docker.txt)

**Comment by jimmyanttila** [comment]
I get the same error on the same OS version.
Issue occured after running **docker run -it --rm microsoft/dotnet**, reinstall doesn't solve it.

Diagnostic ID: 055C5F2E-273C-4636-96CD-CFCF26D50B30/2016-11-08_07-48-45

**Comment by dgageot** [comment]
@ocafebabe @jimmyanttila Could you give a try to Docker for Windows Beta31 and tell us if it fixes the issue?

**Comment by rneugeba** [comment]
This looks like what is already tracked here: https://github.com/docker/docker/issues/27423
Please take a look there and provide any additional information if required.
Thanks
Closing
