### ISSUE TITLE
Docker: shared drives and startup errors

### ISSUE THREAD

**Issue by martinlierschof** [docker/for-win#2100]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 59F5C897-AB53-40E4-90EF-63E74C74D1B9/2018-06-12_09-59-12

### Expected behavior
Docker starts in windows without any problems. (Stable and Edge)
Docker manages shared drives without forgetting them (unable to set sometimes)

### Actual behavior
Docker does not work, either docker cannot access my volumes anymore or docker responds with a problem it cannot create the pipe with the container. 

### Information
The actual problem is that it does somehow loses the connection with the Hyper-V manager. i have restarted the hyper-v service and then it sometimes works, mostly i have to restart docker and the hyper-v service.
Also somehow the shared drives cannot be shared(one drive cannot be shared suddenly, after restart of PC it works again) and everytime i run a docker-compose command which mounts a file, the next time i try toi start this container it says the file exists : "Cannot start service while creating mount source path '/f': mkdir /host_mnt/e: file exists". But after i restart docker, or restart the shares it works again, if the shares work.

I tried the following stuff:
- trying to switch to edge from stable and back
- re-installing with pruning all volumes and containers
- re-enabling hyper-v and reinstalling docker
- restart windows management instrumentation + restart docker docker service

Always running linux containers.
Iam running as Admin user but not "Administrator" here at work, at home it works better with acutal admin but still there are those problems.

  - Windows Version: see diagnostics
  - Docker for Windows Version: see diagnostics

### Steps to reproduce the behavior
There is no reliable way to reproduce this. Massive amount of log files are there.

**Comment by AmazingTurtle** [comment]
This can be reproduced when using a veracrypt volume. Mount it after docker deamon was started, then try to run a container with the newly mounted volume mounted to the docker container. It will fail to mount correctly. Even though it succeeds, it won't be able to find files and folders.
