### ISSUE TITLE
Failed to create endopoint "test" on network nat: HNS failed with error: Unspecified Error

### ISSUE THREAD

**Issue by Tigro90** [docker/for-win#2102]
### Expected behavior
Making .net Core 2.0 service API run on Docker container in Windows (hosted in Azure)

### Actual behavior
Error response from daemon: failed to create endpoint "test" on network nat: HNS failed with error: Unspecified Error

### Information

Dockerfile:

```
FROM microsoft/dotnet:2.0.0-runtime
RUN #ps1_sysnative Import-Module ServerManager 
RUN #ps1_sysnative Add-WindowsFeature Web-Server

ADD https://download.microsoft.com/download/B/1/D/B1D7D5BF-3920-47AA-94BD-7A6E48822F18/DotNetCore.2.0.0-WindowsHosting.exe ".\hosting.exe"
RUN start-process -Filepath .\hosting.exe -ArgumentList @('/install', '/quiet', '/norestart') -Wait 

COPY PublishOutput c:/case-api/PublishOutput
RUN #ps1_sysnative Remove-WebSite -Name 'Default Web Site'
RUN #ps1_sysnative New-Website -Name ‘test’ -Port 80 \ -PhysicalPath ‘c:/case-api/PublishOutput’ -ApplicationPool ‘MyTestAppPool’
EXPOSE 80
```

What I am trying to do is, starting from dotnet:2.0.0-runtime, is first installing IIS in order to host my API.
Then I add a Hosting Bundle, which I see around and seems necessary but I don't know yet how.
Copy the binaries of my API in the Image and at the end create the website. Unfotunately there is no error description (that I can find) to help targetting the issue

**Comment by jasonbivins** [comment]
Hi @Tigro90   Are you running on Windows 10, or Server 2016?
It sounds like you've either got a corrupt hns.data file - or you're trying to overwrite an existing network

This script will help https://github.com/MicrosoftDocs/Virtualization-Documentation/tree/live/windows-server-container-tools/CleanupContainerHostNetworking

**Comment by Tigro90** [comment]
Hello @jasonbivins , it's Windows Server 2016.

I am gonna try the script, and in the meantime I don't know if this may help but these are the networking settings about the Server where I am running Docker on Azure:

![network](https://user-images.githubusercontent.com/9882443/41298732-31ad8aa4-6e62-11e8-873b-46a6c4b9f2da.png)

**Comment by jasonbivins** [comment]
@Tigro90   We actually don't suport Docker for Windows running on Server 2016

Your Azure settings look ok - they actually match what I have in my Azure lab
The cleanup script  should take care of the issue though - the HNS is known to get corrupted.  From what I understand, in Server 2019 HNS will run in memory and not from a file.
