### ISSUE TITLE
Docker fails at system startup (network and volume errors)

### ISSUE THREAD

**Issue by pulse14** [docker/for-win#2103]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 5BAC2EB5-706C-4CA2-A9C5-9FFAB1659CE5/2018-06-13_11-32-52

### Expected behavior
- Volumes and network working without errors after a system reboot
### Actual behavior
Multiples errors when starting containers :
- `driver failed programming external connectivity on endpoint infrastucture-base_traefik_1 (4da0cbada8397178e23d179d67c8caccb53cc068983b721e507b06586f0114b5661dec43e): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:22:tcp:172.19.0.2:22: input/output error6770a0743e63265716975dfaa4c562f514cec09c0d08e838c6): Bind for 0.0.0.0:8080 failed: port is already allocated` But I have nothing on this port, only docker use it
- `Cannot start service ssh-tunnel: driver failed programming external connectivity on endpoint infrastucture-base_ssh-tunnel_1 (cdb9678e23d179d67c8caccb53cc068983b721e507b06586f0114b5661dec43e): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:22:tcp:172.19.0.2:22: input/output error`
- `OCI runtime create failed: container_linux.go:348`

To fix them I need to remove networks, containers and restart deamon, reset credentials at every startup.

### Information

  - Is it reproducible? Yes, just need to restart windows with any container with volumes and networks
  - Is the problem new? No, it fails at every startup
  - Did the problem appear with an update? No, just need to install docker on any system
  - A reproducible case if this is a bug, Dockerfiles FTW : It's not a custom container, just traefik and basic ssh container, nodejs too 

- Windows Version: Windows 10, version 1803
- Docker for Windows Version: 18.03.1-ce-win65 (17513)

### Steps to reproduce the behavior
1. Run your containers
2. Stop them
3. Reboot
4. Run your containers
5. It fails

### Steps to fix the problem
1. Manually restart docker
2. Reset volumes credentials

**Comment by pulse14** [comment]
Volumes errors when I don't reset credentials/reset everything :
- Diagnostics ID: 5BAC2EB5-706C-4CA2-A9C5-9FFAB1659CE5/2018-06-13_11-55-54

`ERROR: for infrastucture-base_traefik_1  Cannot start service traefik: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/host_mnt/c/***********************/config/traefik.toml\\\" to rootfs \\\"/var/lib/docker/overlay2/8b274e7b3927efa32d5b60e03d316aefd1b98384df1609a5c035dd17bcff0868/merged\\\" at \\\"/var/lib/docker/overlay2/8b274e7b3927efa32d5b60e03d316aefd1b98384df1609a5c035dd17bcff0868/merged/etc/traefik/traefik.toml\\\" caused \\\"not a directory\\\"\"":
unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type`

`ERROR: for traefik  Cannot start service traefik: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/host_mnt/c/****************/config/traefik.toml\\\" to rootfs \\\"/var/lib/docker/overlay2/8b274e7b3927efa32d5b60e03d316aefd1b98384df1609a5c035dd17bcff0868/merged\\\" at \\\"/var/lib/docker/overlay2/8b274e7b3927efa32d5b60e03d316aefd1b98384df1609a5c035dd17bcff0868/merged/etc/traefik/traefik.toml\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.`

PS: It displays the error not matter if C drive is shared or not. After resettings credentials I also need to remove the containers/networks.

When I fixed everything it works until system reboot.

**Comment by Redgar13** [comment]
Same problem here. Also 18.03.1-ce-win65 (17513), Windows 10 Enterprise 10.0.17134 Build 17134
I'm using MySQL containers if it matters (feels like it doesn't)

**Comment by pulse14** [comment]
Problem persist at version `18.06.0-ce-win72 (19098)`

**Comment by lromor** [comment]
Same problem here `Docker version 18.03.1-ce, build 9ee9f40`
