### ISSUE TITLE
Error: An error occurred while attempting to run Docker container

### ISSUE THREAD

**Issue by rupeshtech** [docker/for-win#2105]
### Information
CreateContainer: failure in a Windows system call: Logon failure: the user has not been granted the requested logon type at this computer. (0x569) extra info: 

  - Windows Version:
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:12:05 2018
 OS/Arch:      windows/amd64
 Experimental: true
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.10.1
  Git commit:   f150324
  Built:        Wed May  9 22:29:00 2018
  OS/Arch:      windows/amd64
  Experimental: true

**Comment by jurby** [comment]
+1

**Comment by rahul24** [comment]
run cmd/ps in admin mode and then try.

**Comment by jraristi** [comment]
This happens to me too on Windows 10, not a VM.

Error response from daemon: container 25f620523b7242e56bd9c27737957f172e119cfe81651eebfb87f15c79e5f80f encountered an error during CreateContainer: failure in a Windows system call: Logon failure: the user has not been granted the requested logon type at this computer. (0x569) extra info: 

```json
{
   "SystemType":"Container",
   "Name":"25f620523b7242e56bd9c27737957f172e119cfe81651eebfb87f15c79e5f80f",
   "Owner":"docker",
   "IgnoreFlushesDuringBoot":true,
   "LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\25f620523b7242e56bd9c27737957f172e119cfe81651eebfb87f15c79e5f80f",
   "Layers":[
      {
         "ID":"2b681f64-c4f6-5f37-aa1f-3f693b45e3c7",
         "Path":"C:\\ProgramData\\Docker\\windowsfilter\\a7f0907be1c107dbae20bc20d530fcb841175db68c557c4095864c84df61cb24"
      },
      {
         "ID":"03952bc1-f101-5cb5-b547-631d0f79520e",
         "Path":"C:\\ProgramData\\Docker\\windowsfilter\\b86bf45a6dbdabbbb6a695af771e37316e3a4ced346b3252e10e361a41b8ec33"
      },
      {
         "ID":"63522ffa-0fd2-53a2-9761-54c60f62db41",
         "Path":"C:\\ProgramData\\Docker\\windowsfilter\\64a6531e0a933966cd0169f670ec466f3b1ec6fa971fdf44fe9aea589b4d2fcd"
      },
      {
         "ID":"b57686bd-b980-53b6-9df5-f2dffe0d3d1d",
         "Path":"C:\\ProgramData\\Docker\\windowsfilter\\448c8d443e86c127cd3eb0f3a06c7f54f6596f968b0e4961c1914cf1d169e9a4"
      },
      {
         "ID":"83010c10-2bf2-5439-a503-a61250e3b904",
         "Path":"C:\\ProgramData\\Docker\\windowsfilter\\eb46a8d3c6621f72cdac68d6103996347816ddb9d4c9debef35752bbed776cfb"
      },
      {
         "ID":"37c9825a-b8ad-54e7-89f6-907d18367639",
         "Path":"C:\\ProgramData\\Docker\\windowsfilter\\8c7c5fc7b51856fcae99780c9dda4a92867dfb9fec7666a58b19cd4c0ea76c83"
      },
      {
         "ID":"1bbcbd98-892c-5cf4-8762-c1cf58aab3a2",
         "Path":"C:\\ProgramData\\Docker\\windowsfilter\\5c2abcb68f5ec6ee9d8659ae611d9bf6b3abdf6328ac4a9704057f287f122731"
      },
      {
         "ID":"4e6fa975-bd5c-57d1-a6ec-9e1840cd95a2",
         "Path":"C:\\ProgramData\\Docker\\windowsfilter\\4837c33bf4b83c979810d1fabf3bb8bf2268203f4f4e7919c873c25635fa85f8"
      }
   ],
   "HostName":"25f620523b72",
   "HvPartition":true,
   "EndpointList":[
      "f71f908c-e34d-47ab-b1bd-b74d18f1ffae"
   ],
   "HvRuntime":{
      "ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\5c2abcb68f5ec6ee9d8659ae611d9bf6b3abdf6328ac4a9704057f287f122731\\UtilityVM"
   },
   "AllowUnqualifiedDNSQuery":true
}
```

**Comment by jraristi** [comment]
I was able to fix this.

My problem was that Hyper V wasn't enabled in my Windows 10 Enterprise.

I uninstalled Docker, Enabled Hyper-V, reinstalled Docker and then it worked.

Further reference for solution [here](https://stackoverflow.com/questions/36885985/cannot-start-docker-after-installation-on-windows)

**Comment by Pvlerick** [comment]
I have this issue intermittently, I found that restarting all the Hyper-V related services fixes it.

**Comment by Pvlerick** [comment]
More precisely, it seems that restarting the "Hyper-V Host Compute Service" is sufficient.

**Comment by carljones4** [comment]
As a docker newbie, for me this error was caused by not being authenticated to docker.  Open a command prompt and type 'docker login', then log in.  Once successfully logged in to the docker cli, Visual Studio was able to pull the necessary docker image from docker hub and run the project.

**Comment by Zamaletdinov** [comment]
@carljones4, that really helps, thank you :)

**Comment by Zamaletdinov** [comment]
@carljones4, this really helps, thank you :)

**Comment by eolamisan** [comment]
Generally speaking this or similar problems happen to often for docker to be taken seriously in the windows platform.

**Comment by iekdosha** [comment]
I have encountered this issue on windows 10 with VS2019 trying to launch a dotnet core web api (docker settings were an option when opening the project).
I have tried:
- Running VS2019 as admin
- Logged in to Docker and shared the containing volume
- Enabled Hyper V and reinstalled Docker then rebooting

None of the above worked...
Can anyone assist? :)

**Comment by wajhighumman** [comment]
Just Make sure Docker on your computer is running.

WG


> ### Information
> CreateContainer: failure in a Windows system call: Logon failure: the user has not been granted the requested logon type at this computer. (0x569) extra info:
> 
> * Windows Version:
>   Client:
>   Version:      18.05.0-ce
>   API version:  1.37
>   Go version:   go1.9.5
>   Git commit:   f150324
>   Built:        Wed May  9 22:12:05 2018
>   OS/Arch:      windows/amd64
>   Experimental: true
>   Orchestrator: swarm
> 
> Server:
> Engine:
> Version: 18.05.0-ce
> API version: 1.37 (minimum version 1.24)
> Go version: go1.10.1
> Git commit: f150324
> Built: Wed May 9 22:29:00 2018
> OS/Arch: windows/amd64
> Experimental: true

**Comment by eolamisan** [comment]
> I have encountered this issue on windows 10 with VS2019 trying to launch a dotnet core web api (docker settings were an option when opening the project).
> I have tried:
> 
> * Running VS2019 as admin
> * Logged in to Docker and shared the containing volume
> * Enabled Hyper V and reinstalled Docker then rebooting
> 
> None of the above worked...
> Can anyone assist? :)

What works for me is restarting service "Windows Management Instrumentation".

**Comment by cannonfodda** [comment]
gpupdate \force did the trick for me.
