### ISSUE TITLE
Docker in Windows 10, "exec: \"powershell\": executable file not found in $PATH": unknown 

### ISSUE THREAD

**Issue by Tigro90** [docker/for-win#2108]
### Expected behavior
Being able to run powershell commands inside a running container hosted on Windows 10
### Actual behavior
error: "exec: \"powershell\": executable file not found in $PATH": unknown

### Information
I am trying to build an image on docker running on Windows 10. This image is supposed to start from a base image of .net Core 2.0, install IIS, make a .net Core service API being hosted in IIS .
The image builds correctly but I am not able to call the service, therefore I wanted to check if the API is really running inside the container and being hosted by IIS. Still don't know how to do this (if you can add a hint after the answer to the main problem it would be very much appreciated!), but at least I wanted to be able to check the list of processes  running in the container through a "powershell ps" command.
What I do:

docker run -d -t -p 80:80 --name test_demo test_demo 
docker exec test_demo powershell

Unfortunately I end up with this error but coudln't find a solution on the web.
If readying my dockerfile helps, here it is:

```
FROM microsoft/dotnet:2.0.0-runtime
RUN #ps1_sysnative Import-Module ServerManager 
RUN #ps1_sysnative Add-WindowsFeature Web-Server
ADD https://download.microsoft.com/download/B/1/D/B1D7D5BF-3920-47AA-94BD-7A6E48822F18/DotNetCore.2.0.0-WindowsHosting.exe ".\hosting.exe"
RUN #ps1_sysnative start-process -Filepath .\hosting.exe -ArgumentList '/install', '/quiet', '/norestart' -Wait 

COPY PublishOutput c:/friss-case-api/PublishOutput
RUN #ps1_sysnative Remove-WebSite -Name 'Default Web Site'
RUN #ps1_sysnative New-Website -Name ‘test’ -Port 80 \ -PhysicalPath ‘c:/friss-case-api/PublishOutput’ -ApplicationPool ‘MyTestAppPool’
EXPOSE 80
```

**Comment by jasonbivins** [comment]
@Tigro90 
I wasn't able to get powershell to work in this image:  microsoft/dotnet:2.0.0-runtime 
Here's what I get:
```
C:\WINDOWS\system32>docker run -it microsoft/dotnet:2.0.0-runtime powershell
docker: Error response from daemon: container afaa367ad700a1be01695a792a0f3c956e3abe8fc1c96a8ab7a4292c727d9e51 encountered an error during CreateContainer: ```

**Comment by thaJeztah** [comment]
I think it's nanoserver based, so not sure powershell is available in that; https://github.com/dotnet/dotnet-docker/blob/master/2.0/runtime/nanoserver-1709/amd64/Dockerfile

**Comment by Tigro90** [comment]
It is not nanoserver based.. but weird. @jasonbivins I use that one as base image and it works correctly but it is not nanoserver based for sure

**Comment by thaJeztah** [comment]
It's a multi-stage Dockerfile; second stage is using nanoserver;

```dockerfile
# Runtime image
FROM microsoft/nanoserver:1709

**Comment by Tigro90** [comment]
Oh wow.. I miss some comprehension then of what's going on.. I am sorry. Thanks @thaJeztah !

**Comment by thaJeztah** [comment]
No worries! Easy to forget that Dockerfiles now can have multiple `FROM` :smile:
