### ISSUE TITLE
plugin not found when trying to create a bridge network in windowserver

### ISSUE THREAD

**Issue by jesaremi** [docker/for-win#2109]
Using windowsservercore 1709
command:

> C:\>**docker network create localnet**
> Error response from daemon: plugin not found

**Comment by rahul24** [comment]
Try specifying -d argument and driver name.

**Comment by jeffsaremi** [comment]
i have. by default the driver is bridge. The above produces the same results as "docker network create -d bridge localnet"

**Comment by rahul24** [comment]
As per my understanding, bridge driver only exists in Linux not in windows. In windows, it’s NAT.

**Comment by jeffsaremi** [comment]
thank you. that explains it!

**Comment by S93rastogi** [comment]
As nothing  is mentioned about LCOW way of running Linux containers on Server  2019. I would like to add my information that could be important for some.

If you are using Docker EE and running Linux containers using LCOW way then you need to create a network using the NAT driver. The Bridge Driver is not available on Server 2019. Though the bridge Driver could be used to create a network for Linux Containers on Win 10 PC using Docker CE.

Please use the command mentioned below to resolve the error docker network create --driver nat NetworkName to resolve the error

**Comment by S93rastogi** [comment]
If you are using Docker EE and running Linux containers using LCOW way then you need to create a network using the NAT driver.

The **Bridge Driver is only available on Linux machine** so whenever we use Docker CE \(Docker for Windows) and run windows container, Bridge will not work but if we use Linux container Bridge will work smooth and user will face no issues.Though its also important to understand that Bridge Driver does not work for Linux container when we go LCOW way as LCOW internally uses Windows Kernel and Windows kernel has no support for Bridge Driver.

It's important to remember that Docker has made **Bridge as the default Network** Driver so its the responsibility of the person running the container to make a judicious decision about which driver to choose.

Please use the command mentioned below to resolve the error
**```docker network create --driver nat NetworkName```**
