### ISSUE TITLE
Cannot install docker for windows on Win10 enterprise

### ISSUE THREAD

**Issue by thawkins** [docker/for-win#211]
### Expected behavior
Docker for windows should install on Windows 10 Enterprise.

### Actual behavior
Error message is shown stating that pro, enterprise or educational is required to install. 

### Information
Unable to provide diagnostics as error is shown immeadiatly after clicking on the installer. 
 

### Steps to reproduce the behavior
Install windows 10 enterprise
update with windows update
enable hyper-V feature, ensure that service appears in feature set.
download docker for windows
double-click on installer package

![hyperv](https://cloud.githubusercontent.com/assets/14537/20086497/c415123a-a5ab-11e6-8fd5-e057e01d2570.PNG)
![install](https://cloud.githubusercontent.com/assets/14537/20086502/c7a75994-a5ab-11e6-8a04-94d407368f48.PNG)
![windows type](https://cloud.githubusercontent.com/assets/14537/20086504/ca4c2260-a5ab-11e6-9ca9-5ed0f926ad6b.PNG)

**Comment by friism** [comment]
Interesting, can you post the output of `[System.Environment]::OSVersion.Version` (from Powershell prompt)?

**Comment by thawkins** [comment]
I juat found out i was miasing tbe last windows update that pushed tbe
build number to the required level, ran that in and it now works. but the
nessage is deceptive.  if it said "you must have at least build xxxxx" then
i would not have posted the bug and i would have known immeadiatly what to
do.

Sorry for the false alarm.

**Comment by friism** [comment]
@ebriney can we divide up this error? Cases:

 1. Your Windows version is wrong (eg. it's "Home" or Windows Server 2016)
 2. Your Windows build is too old

**Comment by rneugeba** [comment]
Closing this issue. It seems that the issue was fixed by updating the version and we didn't have other reports of a similar issues and messing with the installer to provide better feedback is going to be tricky...

**Comment by joaociocca** [comment]
![sem titulo](https://user-images.githubusercontent.com/6473725/34575103-b47c2b86-f160-11e7-942c-976265a1bd88.png)
I know this is from 2016, but I just stumbled on this error. As the print shows, my machine is running Win 10 Enterprise build 10586 - the exact same build the Docker error says is the requirement.

**Comment by julienb243** [comment]
same.  Just occurred to me to yesterday trying to install on win 10 ent with the exact build # quoted by installer as minimum required ver.

**Comment by nickbenj** [comment]
And me - on Enterprise.

**Comment by MarcProe** [comment]
I cannot install on Windows 10 Education (which is basically a pro)

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      14393  0

**Comment by MarkStoakes** [comment]
encountered the same issue.  https://www.screencast.com/t/CO0WAzxv6X

**Comment by pkhandelwal612** [comment]
![image](https://user-images.githubusercontent.com/6346778/35026587-01b882a8-fb72-11e7-8b55-1373bb504321.png)


Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      10586  0

**Comment by ehimsi** [comment]
is there a fix for this?

**Comment by search4soumya** [comment]
same issue with me. is there a fix for this issue?

**Comment by pdubb29** [comment]
Can we re-open this issue? I'm having the same issue on my machine with the required build number, and the most recent Community Edition of Docker.

**Comment by jshafman** [comment]
i'm also having the same issue.  Can we get this bug opened again or does anyone have a fix?  I have the latest windows updates.

**Comment by qhungngo** [comment]
I also had one like this on Win10. Someone solve this?

**Comment by ehimsi** [comment]
try with this - 
https://download.docker.com/win/stable/13620/Docker for Windows Installer.exe

**Comment by jshafman** [comment]
That did work for me @ehimsi !  Do you know why that version worked the others didn't?

**Comment by ph4wks** [comment]
That new exe worked for me too. We need to be careful forcing the very latest version of Windows 10. Many many corps across the globe do not keep pace with the 6 monthly windows 10 releases.  Suggest N-1 or N-2 depending on what Docker are trying to achieve by suggesting the latest version.

**Comment by ehimsi** [comment]
@jshafman   - not exactly. Docker is changing rapidly and I found out the version post one of the updates on win 10.
