### ISSUE TITLE
Docker for windows 10(1803) install issue

### ISSUE THREAD

**Issue by Scottmu** [docker/for-win#2113]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Installed docker-ce for windows 
### Actual behavior
I download the installer file, double clicked it and show a blank window without anything, no button, no text....
I tried run the installer file in cmd window, the last output is  "Prompting for optional features" then the progress stoped.
### Information

  - Windows Version: windows 10 pro 1803
  - Docker for Windows Version: last version from docker store both stable and edge

### Steps to reproduce the behavior

  1. double-click installer file
  2. a blank window appeared..

**Comment by jasonbivins** [comment]
@Scottmu 
Do you get the same problem if you Right click the installer and choose "Run as Administrator"

**Comment by Eliasjamal** [comment]
I have the same problem and I have tried the "Run Administrator" with the same results

**Comment by Eliasjamal** [comment]
When running from cmd.exe the installs seems to stall at 'Prompting for optional features'

[11:21:51.356] [InstallHandler] Using embedded package
[11:21:51.457] [InstallWorkflow] Using package: res:d4w
[11:21:51.458] [InstallWorkflow] Downloading
[11:22:03.086] [InstallWorkflow] Exracting manifest
[11:22:03.190] [InstallWorkflow] Checking prerequisites
[11:22:07.209] [InstallWorkflow] Prompting for optional features

The Install window is also blank 

Are there any logs that I can check to see why the installation does not complete?

**Comment by Scottmu** [comment]
@jasonbivins thanks for your advises, I have tried but looks dose not work.

**Comment by jasonbivins** [comment]
@Scottmu @Eliasjamal 
Check to see if the installer gets far enough to create the directories -  C:\ProgramData\Docker  and C:\program files\docker

There will be logs there

**Comment by Scottmu** [comment]
@jasonbivins 
Thanks, I have tried to install on my surface book, but the install file work on my desktop, I thinks it might be some issue on surface machine.

**Comment by takeshi-kimura** [comment]
I have the same trouble with my surface book2 13inch

**Comment by manuelbieh** [comment]
Same problem here. Latest Win 10 Pro (default ring), latest Docker for Windows Installer.exe.

```
[15:19:37.822] [InstallHandler] Not run as admin, relaunching with UAC prompt
[15:19:42.308] [InstallHandler] No d4w installation found
[15:19:42.310] [InstallHandler] Using embedded package
[15:19:42.568] [InstallWorkflow] Using package: res:d4w
[15:19:42.569] [InstallWorkflow] Downloading
[15:19:44.167] [InstallWorkflow] Exracting manifest
[15:19:44.211] [InstallWorkflow] Checking prerequisites
[15:19:45.504] [InstallWorkflow] Prompting for optional features
```

**Comment by dxkrs** [comment]
the same promble to me!!!

**Comment by wguo32** [comment]
see https://github.com/docker/for-win/issues/1736

**Comment by harrisdt15f** [comment]
I also get the same error. I tried may of docker ce version but it doesn't work with me. need helps.
below is my information on getting errors.
![image](https://user-images.githubusercontent.com/27404296/44943205-edea9780-adf4-11e8-9f6a-68cf9dc18781.png)
![image](https://user-images.githubusercontent.com/27404296/44943210-0195fe00-adf5-11e8-8f33-4f62cc540e10.png)
![image](https://user-images.githubusercontent.com/27404296/44943215-15d9fb00-adf5-11e8-891d-d94b9a378e4b.png)

**Comment by Scottmu** [comment]
Finally, this issue has been fixed with uninstalled Duet app.

Thanks @wguo32 help
