### ISSUE TITLE
Not able to contact API service running in windows container

### ISSUE THREAD

**Issue by Tigro90** [docker/for-win#2115]
### Expected behavior
Calling service API in container reaches endpoint 

### Actual behavior
No answer from the endpoint

### Information
I am running a .net core API in a windows container. The api is correctly build, which means that when I run it through powershell **dotnet** command, it is correctly hosted in Kestrel and I am able to call it. 
In the code, I have set Kestrel to host this API on the address http://127.0.0.1:5050 . So, if it is up and running and on the browser I go to http://127.0.0.1:5050/swager , I am able to see the swagger page giving me the info about the service. Now.. I am able to make it up and running inside a container through a dockerfile that is the following:

```
FROM microsoft/aspnetcore-build:2.0 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY PublishOutput/. ./

# Build runtime image
FROM microsoft/aspnetcore:2.0
WORKDIR /app
COPY --from=build-env /app .
```

Nothing much about this. Then I try to run the container with the following command:

`docker run -d -p 8080:5050 --name test_demo test_demo`

Afterwards I go on the browser and I try to browse to localhost:8080/swagger but the endopoint is not reached.
I also tried to run the **docker inspect** and see the ip of the container and use that one instead of localhost.. what am I missing? Thanks in advance!

ENTRYPOINT ["dotnet", "Friss.CaseApi.Web.dll"]

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by thaJeztah** [comment]
Make sure the API is listening on 0.0.0.0; 127.0.0.1 is localhost of the container itself, so makes it only accessible from inside the container itself

**Comment by Tigro90** [comment]
@thaJeztah Thanks a lot man, it worked!
