### ISSUE TITLE
Docker for windows 10 : failed to register layer : rename

### ISSUE THREAD

**Issue by pavanssvr** [docker/for-win#2117]
Hi,
Installed docker on my Windows 10 Pro machine by downloading from https://docs.docker.com/docker-for-windows/install/  and  started running the commands in windows powershell mentioned in https://docs.docker.com/docker-for-windows/ link to check whether docker working properly or not.

Below is the error I am experiencing: (failed to register layer: rename)

PS C:\Users\name> docker --version
Docker version 18.03.1-ce, build 9ee9f40
PS C:\Users\name> docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
bce2fbc256ea: Extracting [==================================================>]  252.7MB/252.7MB
83eec61707e8: Download complete
eaac79658f14: Download complete
09da50837088: Download complete
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: failed to register layer: rename C:\ProgramData\Docker\image\windowsfilter\layerdb\tmp\write-set-731318441 C:\ProgramData\Docker\image\windowsfilter\layerdb\sha256\6c357baed9f5177e8c8fd1fa35b39266f329535ec8801385134790eb08d8787d: Access is denied.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
PS C:\Users\name>

**Comment by jasonbivins** [comment]
@pavanssvr 
Do you have any antivirus running? 
Generally this error means that we can't write to C:\ProgramData\Docker\ properly, or that there is something scanning it that's locking the files.

**Comment by pavanssvr** [comment]
Hi Jason,
Thanks for your inputs. I have uninstalled and reinstalled as administrator. Now working fine.

Thanks again..

**Comment by pavanssvr** [comment]
Hi,
I have installed 'docker for windows' on my Windows 10 machine  and the 'Server : Docker Engine' OS default sets to 'linux/amd64'. (i.e. the current setting is linux containers)
Now when I run the 'docker run hello-world' command, perfectly working fine.
But, 
when switching from linux containers to windows containers through Docker desktop and trying to pull any image, getting the below error message.( failed to register layer: rename)

PS C:\WINDOWS\system32> docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
e46172273a4e: Extracting [==================================================>]  92.82MB/92.82MB                         a3e3c1bcacdf: Download complete                                                                                         5912958fe266: Download complete                                                                                         b7394e3f86f1: Download complete                                                                                         C:\Program Files\Docker\Docker\Resources\bin\docker.exe: failed to register layer: rename C:\ProgramData\Docker\image\windowsfilter\layerdb\tmp\write-set-544254322 C:\ProgramData\Docker\image\windowsfilter\layerdb\sha256\bc06b22070cd8fb7c81b24025f0d67ed17390339fd8506cc46ce0224ec9c6e73: Access is denied.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.

I am a Dotnet developer and need to pull dotnetcore images which support 'Server : Docker engine of' Windows OS only

for instance, to pull the image 'mcr.microsoft.com/windows/nanoserver:1809', I need Windows container only

**Comment by webtrainingroom** [comment]
> 
> Hi Jason,
> Thanks for your inputs. I have uninstalled and reinstalled as administrator. Now working fine.
> 
> Thanks again..

Hi Pavanssvr,
What did you uninstall and reinstall? docker desktop or antivirus software?

Thanks

**Comment by BenhurKulzer** [comment]
> > Hi Jason,
> > Thanks for your inputs. I have uninstalled and reinstalled as administrator. Now working fine.
> > Thanks again..
> 
> Hi Pavanssvr,
> What did you uninstall and reinstall? docker desktop or antivirus software?
> 
> Thanks

Hi, i solve this problem on windows 10 just switching to linux containers.
