### ISSUE TITLE
failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage

### ISSUE THREAD

**Issue by priyankamakwana4** [docker/for-win#2119]
I have a private docker registry on Windows Server 2016 Datacenter and from local machine (Windows 10 Pro) I pushed few images to it. When I try to pull image from server it starts pulling and later throws an error

**failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage \?\C:\ProgramData\docker\windowsfilter\f9613d03a4fae39c0cebca07bc51aef2931756f5e674cda8f6b78729ba5ebac8\UtilityVM: The system cannot find the path specified.**

I used following image and steps to start a registry https://hub.docker.com/r/stefanscherer/registry-windows/

I tested with hello-world image, pushed it from local machine and pulled it from server, it worked.

But, I am unable to pull images like microsoft/wcf, microsoft/iis which are base images to my local built images.

Other way around, if I already have microsoft/wcf image on my server (which is base image for my locally built image), when pulling the locally built image why it goes to pull microsoft/wcf again. Is there any way I can use server's wcf image?

docker version

Client: 
Version: 17.06.2-ee-13 
API version: 1.30 
Go version: go1.8.7
Git commit: ac44d73 
Built: Mon Jun 4 16:46:59 2018 
OS/Arch: windows/amd64

Server: 
Engine: Version: 17.06.2-ee-13 
API version: 1.30 (minimum version 1.24) 
Go version: go1.8.7 
Git commit: ac44d73 
Built: Mon Jun 4 16:58:47 2018 
OS/Arch: windows/amd64 
Experimental: true

**Comment by jasonbivins** [comment]
@priyankamakwana4 
Do you have your registry setup in the GUI?  
<img width="745" alt="screen shot 2018-06-19 at 1 57 53 pm" src="https://user-images.githubusercontent.com/28021664/41615288-d45f1d42-73c8-11e8-8fa8-30118d0a4f4d.png">

**Comment by priyankamakwana4** [comment]
I don't have GUI, but here a snapshot of daemon.json:

{
  "registry-mirrors": ["my-registry.example:5000"],
  "insecure-registries": [
    "my-registry.example:5000"
  ],
  "debug": true,
  "experimental": true,
  "allow-nondistributable-artifacts": [
    "my-registry.example:5000"
  ]
}

**Comment by MatthewSwarbrick** [comment]
I am also experiencing this exact issue but with a secure registry set up. I've pushed an image that I have built to it, but am unable to pull that same image. When it pulls it downloads the layers but when it extracts it fails with the same error.

**Comment by priyankamakwana4** [comment]
Thanks Matthew, you are right. I figured out the same reason, I built base image using microsoft/wcf latest on windows 10 and was pulling that image on windows server 2016 which gave me this error. After changing its version, it works now.

It is given in this link: 
https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility

**Comment by ebriney** [comment]
@priyankamakwana4 you must post your issue on MS support [here](https://support.microsoft.com/en-us/premier)

**Comment by daghb** [comment]
For later, use [this compatibility list](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility) from Microsoft when trying to run different images on different host versions:

When you pull an image from Docker Hub, look for tags that support the correct host, like ltsc2016 (Windows Server 2016), 1709 (Fall 2017 Update) and 1803 (Spring 2018 update)

You may find your running host version using the `winver` command

**Comment by hrai** [comment]
I ran into similar issue when trying to run Linux docker containers in Windows host.
