### ISSUE TITLE
 "The server was not found or was not accessible." Error when trying to connect to SQL Server

### ISSUE THREAD

**Issue by Tigro90** [docker/for-win#2121]
### Expected behavior
Being able to contact SQL Server on the host from within the container

### Actual behavior
Error:  The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections.

### Information
I am using Windows containers and I use SQL server.
On my SQL server I can connect through TCP call. From SQL Server Configuration Manager I enabled the TCP calls and the standard port is 1433. So I tried (from the host) to use the IP of my machine to connect to the database and it worked.
Now, if my app runs not in a container I use as connection string the following:

`"Facts": "Data Source=.;Initial Catalog=Facts;Integrated Security=true"`

NOTE: the Data Source is a dot "." , means localhost, sorry if not very visible.
If instead I want the app run inside the container then I check through CMD what's the IP address of the host from the Ethernet adapter vEthernet (DockerNAT).. and it is 10.0.75.1 . Therefore my connection string becomes:

`"Facts": "Server=10.0.75.1,1433;Database=.;Initial Catalog=Facts;Integrated Security=true"`

Am I misunderstanding what should be into the Database= ?

**Comment by jasonbivins** [comment]
@Tigro90   
I don't think integrated security will work unless you setup a gMSA account.  Have you tried using SA and specifying an SA password?

https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-linux-2017
