### ISSUE TITLE
Feature request: Ability to run docker for windows with VirtualBox 

### ISSUE THREAD

**Issue by dhanvi** [docker/for-win#2127]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version: Windows 10 1803
  - Docker for Windows Version: 18.03-ce

It would be a nice for docker for windows to work with VirtualBox natively, something like if Hyper-V is disabled give option of installing VirtualBox and running docker. (I am aware that docker toolbox does this)

Lot of us use VirtualBox and don't want to enable Hyper-V

**Comment by rn** [comment]
This is a very significant engineering effort and we currently have no plans to support this, so I'm closing this. Supporting VirtualBox also means that things like Windows Containers won't work as they rely on Hyper-V

Out curiousity, what is your use case for VirtualBox?

**Comment by dhanvi** [comment]
VirtualBox usecase is to run Linux 🐧 on windows!

**Comment by rn** [comment]
you can do that with Hyper-V too.

**Comment by Ciantic** [comment]
Hyper-V is awful, it truly is, it's completely unusable for Desktop Linux, see this https://github.com/Microsoft/linux-vm-tools/issues/28#issuecomment-412647995

There is even input lag so that typing in desktop is unusable.

Please reconsider adding virtual box support, the Microsoft is not in a hurry to improve Linux support on the Hyper-V

**Comment by Dawood-ibn-Kareem** [comment]
Is there any way I can vote for this issue to be re-opened?  I too need to be able to run both VirtualBox and Docker for Windows.

**Comment by dhanvi** [comment]
Also, do check out https://docs.docker.com/docker-for-windows/wsl-tech-preview/
