### ISSUE TITLE
Docker hangs

### ISSUE THREAD

**Issue by pkch** [docker/for-win#213]
Docker froze for 10 min when attempting to run a container with `docker run -it --rm container_name`. It could not be cancelled with CTRL-C. After that `docker ps` also froze but could be cancelled with CTRL-C. 

The only active processes were two (library) `postgres` containers, each mapped to its own host folder (but maybe they still share some resources that cause a problem?):

After 10 min, everything seems to have recovered and works fine (I didn't restart anything, just waited).

Docker log diagnostic id: 92F4BAC6-95DD-4768-A59F-8BB64BA8CAA4/2016-11-08_12-16-28.

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by dgageot** [comment]
@pkch Can you give a try to the latest Beta 31 and tell us if the issue is solved?

**Comment by rneugeba** [comment]
Closing issue do to inactivity. Please re-open if the issue still persists with the latest Beta.
Thanks
