### ISSUE TITLE
No Shared Drivers settings panel

### ISSUE THREAD

**Issue by SetTrend** [docker/for-win#2132]
In the [documentation](https://docs.docker.com/docker-for-windows/#shared-drives#shared-drives) it says there is a Shared Drives panel in Docker for Windows settings:

### Expected behavior

![settings-shared-drives](https://user-images.githubusercontent.com/9283914/41668955-de9f8542-74b0-11e8-8b08-a4cdcae8a8ce.png)

<br/>

But I don't see that panel in my Docker for Windows installation:

### Actual behavior
![no shared drives](https://user-images.githubusercontent.com/9283914/41669027-0cdf384e-74b1-11e8-8390-0d973f7c1383.png)

<br/>

### Information
  - Windows Version: 10x64
  - Docker for Windows Version:

     ![docker version](https://user-images.githubusercontent.com/9283914/41669053-213f5ea4-74b1-11e8-8a10-bc26d4db32dd.png)

**Comment by jasonbivins** [comment]
Hi @SetTrend 
You're currently running in Windows container mode where there are different settings - Shared drives are automatically available in Windows mode.

Were you trying to run Linux containers?  If so, right click the Docker Icon in your systray and choose Switch to Linux containers.  The settings screen will match the one in your first screenshot after you switch.

**Comment by SetTrend** [comment]
Thanks, for clarifying, @jasonbivins !

Yet, shouldn't this difference be pointed out explicitly in a "Get started with Docker for **Windows**" documentation?

**Comment by py563** [comment]
i am running on linux containers but cannot see the panel

**Comment by mat007** [comment]
@py563 the UI has changed since, can you open a fresh issue please?

**Comment by py563** [comment]
I took my hours to figure that the UI was changed because in the docker
website and other docs for docker user blogs had the image like in this
issue, I did went ahead and opened new issue.
