### ISSUE TITLE
Unable to pull image "lambci/lambda:build-nodejs8.10" from windows

### ISSUE THREAD

**Issue by poojaharchirkar** [docker/for-win#2135]
Hi,
I m using following command to pull image from hub,
 docker pull lambci/lambda:build-nodejs8.10
but getting following error after I run above command.
Error : build-nodejs8.10: Pulling from lambci/lambda
image operating system "linux" cannot be used on this platform

Please help.

**Comment by rn** [comment]
Check in the whale systray menu, you most likey are in windows container mode and try to pull a linux container image. To pull and use linux container images you need to switch to Linux containers.

I'm closing this for now, but feel free to follow up if this does not work

**Comment by XMalatji** [comment]
I just keep getting these dots............................................................................... on windows...
