### ISSUE TITLE
Docker Violated My Space This Morning With Popup

### ISSUE THREAD

**Issue by pkellner** [docker/for-win#2138]
I've never posted an issue like this, but on the other hand, I feel like my computer was infected by Docker when it posted a request for feedback when my system booted. I hope this is not endorsed by Docker and is removed from all future versions. 

Docker should be leading and not following bad practices like this.  Can we imagine if every app I have on my computer asked me to do something when my computer boots?  And worse, no option in settings to disable this anti-social behavior.

Bad Docker, Bad!

![dockerbad](https://user-images.githubusercontent.com/241170/41727907-52a7b1c0-752a-11e8-9c4c-8112becb0977.png)

**Comment by jasonbivins** [comment]
@pkellner 
Are you seeing this on every system reboot, or just once?

**Comment by pkellner** [comment]
@jasonbivins I only saw it on my last boot (which was one time too many).  If it were a tool tip / popup from the tray icon that quietly disappeared if not attended to,  I'd not be happy but I would not be as annoyed and disappointed with Docker.  Once is once too many as a "must respond" on a system boot.

**Comment by ebriney** [comment]
Hi @pkellner, this is not an issue, so close it.
NB: you can still use toolbox which is not as invasive as Docker for Windows

**Comment by gillesdouaire** [comment]
Deleting this file will reset a 30-day period where the popup will not show up:

del C:\Users\<USER>\AppData\Roaming\Docker\.npsid
