### ISSUE TITLE
Connecting to Identity Web service running on Host from .net Core api running inside container (hosted in windows) gives error 400 Bad Request

### ISSUE THREAD

**Issue by Tigro90** [docker/for-win#2139]
### Expected behavior
I am able to make my api run in a container. The api should be able to connect to an Identity Server running on my host machine at: `http://localhost:26019/` . 

### Actual behavior
Unfortunately the error from the container is:
`Response status code does not indicate success: 400 (Bad Request)`

### Information
I am able from my api to contact a SQL Server database on the host machine through a connection string that is:
`"Database": "Data Source=docker.for.win.localhost,1433;Database=.;Initial Catalog=Test;Integrated Security=false;User Id=AppUser;Password=****;MultipleActiveResultSets=True"`
Similarly, I am trying to contact the Identity Web service running on the host through the connection string:
`"AuthorityUrl": "http://docker.for.win.localhost:26019"`

Unfortunately I don't manage to hit the service. What am I missing? Thanks in advance!

**Comment by rahul24** [comment]
As per my understanding, 400 is a client error which gets generated by servers when it encounter incomplete request. Request is reaching to server but with incomplete arguments/headers. Check the app config.

**Comment by Tigro90** [comment]
@rahul24 It's not about that, I have just verified. Even if I put another address for the server the error returned is 400, which means that the request is not reaching the server unfortunately
