### ISSUE TITLE
Docker for windows ce brutalistic install

### ISSUE THREAD

**Issue by walkerjian** [docker/for-win#2148]
Does not ask where to be installed, does not allow installer to specify any options, kitematic install is laughable - cut and paste (with requisite rename). Does not divulge consequences of choosing between Linux or Hyper-V containers, says that this can be changed after install but bounces around several pages without telling much. Generally a user sadistic install process. I suggest people writing documentation sit down with a noob installing this on a typical end user machine (choked ssd for c: and a biggish mechanical d: etc) and actually emanate a proper set of user sympathetic how-to's...

**Comment by jasonbivins** [comment]
Hi @walkerjian 
Thanks for the feedback
We do have an open enhancement request for some improvements to the install process, and I went ahead and added your comments there.
