### ISSUE TITLE
Fresh Docker for Windows Install Stuck on "Docker is starting..."

### ISSUE THREAD

**Issue by paulwinters** [docker/for-win#215]
After installing the program the Docker program becomes stuck starting up for several minutes before it fails. I have tried installing both the stable and beta, builds of Docker for Windows but the same problem happens with either build. 

The MobyLinuxVM is being built when viewed in Hyper-V Manager but it is not showing up in docker-machine ls.

```
$ docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      windows/amd64
 Experimental: true
An error occurred trying to connect: Get http://192.168.99.100:2376/v1.24/version: dial tcp 192.168.99.100:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

**Comment by rneugeba** [comment]
@paulwinters thanks for reporting the issue. Docker for Windows is a different to how you interact with the containers when compared to toolbox and `docker-machine`.

It looks like you may have the `DOCKER_HOST` environment variable set. Can you unset it and try `docker version` again?

**Comment by paulwinters** [comment]
Thanks, that solved my problem. Is DOCKER_HOST something that Docker Toolbox sets? I don't recall setting any Windows env variables.

**Comment by rneugeba** [comment]
great that it works for you, closing this issue.

Toolbox may have set the environment variable, but I'm not sure, TBH.
