### ISSUE TITLE
Windows Server 2016 & localhost port binding

### ISSUE THREAD

**Issue by mechanic22** [docker/for-win#2150]
I am reading through these articles (#458 and #204) and still confused about whether localhost will become supported in Windows Server 2016 through some windows update. 

Will this be available?
Is there a date it is expected? I saw April 2018 update, but not sure when that comes out? It is June

### Expected behavior

localhost port binding will work from host to container on Windows Server 2016

### Actual behavior

Does not work from host, other servers can access the port though.

### Information

  - Windows Version: Windows Server 2016 Standard Version 1607
  - Docker for Windows Version: 17.06.2-ee-10

**Comment by jasonbivins** [comment]
Hi @mechanic22 
This repo is for the CE version - Docker for Windows, so I'm going to go ahead and close this one out. 
You'll need to reach out to Microsoft support for clarification on this particular issue

**Comment by daschott** [comment]
Hi @mechanic22, speaking here on behalf of the Windows Core networking team.

This feature was released in Windows Server, version 1803. Unfortunately a bug was introduced which broke functionality for a subset of users. To be more specific: if you had a network adapter which is connected (and has a 169.254.x.y IP address) localhost stopped working.

The workaround was to disable any remaining adapters which have a 169.254.x.y IP address assigned.

Meanwhile, we fixed this issue with [Windows Insider build 17692](https://blogs.windows.com/windowsexperience/2018/06/14/announcing-windows-10-insider-preview-build-17692/) and above. We are still working on all the checkmarks that are needed to be able to propagate this fix to Windows April 2018 Update and Windows Server, version 1803. I will post back here if a KB is released.

**Comment by mechanic22** [comment]
Thanks @daschott - probably not the best place to post this but is there an easy way to upgrade from 1607 to 1803?

**Comment by daschott** [comment]
@mechanic22 Sorry for the delay here -- you can do this in the System settings in the Windows Update section. There is a feature called "Check for Updates" which should pull the recent OS for you. Windows 10 version 1803 uses OS build 17134.191.

We backported the localhost access fix there through [KB4340917](https://support.microsoft.com/en-us/help/4340917/windows-10-update-kb4340917), available now. 

To validate this fix, you can use `docker run -p 8080:80 microsoft/iis` command. Once the container is running, you should be able to use loopback and access the container using http://localhost:8080 or http://127.0.0.1:8080.

**Comment by mechanic22** [comment]
@daschott sorry of my ignorance, but is there a fix for windows server 2016 standard
