### ISSUE TITLE
Support other virtualization layers like VirtualBox, VMware instead of Hyper-V only

### ISSUE THREAD

**Issue by hsluoyz** [docker/for-win#2153]
We know that ``Docker for Windows`` has a hard dependency on ``Hyper-V``. ``Hyper-V`` is a bare-metal hypervisor which conflict with other virtualization solutions like ``VirtualBox``, ``VMware Workstation``, etc. It leads to an issue that a Windows user cannot use ``VirtualBox``, ``VMware`` together with Docker at the same time. The user has to enable ``Hyper-V`` to use Docker and disable ``Hyper-V`` to use ``VirtualBox``. And Such a switch needs a reboot with Windows OS update, which is very inconvenient.

I know ``Docker Toolbox`` uses ``VirtualBox`` instead of ``Hyper-V``. But it's marked as deprecated and maintenance has ended. I still want to use a up-to-date software.

So is there any possibility for ``Docker for Windows`` to support other virtualization layers like ``VirtualBox``, ``VMware Workstation`` instead of ``Hyper-V`` only? And letting the user to choose which one to use in the installation wizard and the run-time configuration interface? Thanks.

**Comment by rn** [comment]
@hsluoyz thank you for the request. Docker for Windows contains a lot of integration between the host and the Linux VM which are specific to Hyper-V. Implementing and supporting a similar level of integration for other Hypervisors is a very significant engineering effort. Furthermore, using a different hypervisor would prevent users to use Windows containers and new features such as LCOW, both of which rely on Hyper-V.

For these reasons we currently have no plans to support other hypervisors and I'm closing this issue.

**Comment by PeterKieu** [comment]
Uninstall Docker CE and back to Docker toolbox simply :(
I still use Vbox, Vmware on development PC.

**Comment by offero** [comment]
Hyper-V's support isn't good enough yet.

**Comment by fbeve** [comment]
So we can  not use Docker and Vmware at the same time on Windows.
Then what is the best solution ? change from windows to linux or Apple ? or what else ?

**Comment by albers** [comment]
I still use [Docker Toolbox](https://github.com/docker/toolbox). New Docker releases can be installed with `docker-machine upgrade`.
For local Kubernetes development I suggest [minikube](https://github.com/kubernetes/minikube). 
Both solutions are backed by Virtual Box.

**Comment by fbeve** [comment]
sound good. I will try docker toolbox. if it does not work as I need on windows 10, I will use a Ubuntu in vmware to install docker. thx
