### ISSUE TITLE
[kubernetes] Enable swagger-ui on kube-apiserver

### ISSUE THREAD

**Issue by BGR360** [docker/for-win#2155]
FEATURE REQUEST (**SOLUTION INCLUDED**)

  - [x] I have tried with the latest version of my channel (Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6AD12471-1777-4094-9E96-898D128A2F7E/2018-06-26_16-23-39

### Expected behavior

The swagger ui for exploring the Kubernetes API should be available at `/swagger-ui/` on the kubernetes api server.

### Actual behavior

`/swagger-ui/` is not recognized as a valid API path and simply returns the available API paths:

```
{
  "paths": [
    "/apis",
    "/apis/",
    "/apis/apiextensions.k8s.io",
    "/apis/apiextensions.k8s.io/v1beta1",
    "/healthz",
    "/healthz/etcd",
    "/healthz/ping",
    "/healthz/poststarthook/generic-apiserver-start-informers",
    "/healthz/poststarthook/start-apiextensions-controllers",
    "/healthz/poststarthook/start-apiextensions-informers",
    "/metrics",
    "/openapi/v2",
    "/swagger-2.0.0.json",
    "/swagger-2.0.0.pb-v1",
    "/swagger-2.0.0.pb-v1.gz",
    "/swagger.json",
    "/swaggerapi",
    "/version"
  ]
}
```

### Information

  - Windows Version: Windows 10 Enterprise
  - Docker for Windows Version: Version 18.05.0-ce-win67 (18263) (Edge)

### Steps to reproduce the behavior

  1. Start the Kubernetes cluster in the Docker for Windows settings
  1. Create a proxy on some port: ```$ kubectl proxy --port=8000```
  1. Navigate to http://localhost:8000/swagger-ui/

### How to fix

Simply add the following container option when starting up the `kube-apiserver-docker-for-desktop` pod:

```
--enable-swagger-ui
```

**Comment by jasonbivins** [comment]
Hi @BGR360 

I can repro and have reported the issue. I'll post an update here when there's more information

**Comment by alexsandro-xpt** [comment]
Is this ready to use?
