### ISSUE TITLE
The system cannot move the file to a different disk drive

### ISSUE THREAD

**Issue by mscrivo** [docker/for-win#2157]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker for Windows should work on systems where the system drive is not C:

### Actual behavior
Docker installs, but fails to run the hello world container with the following error:

> D:\Windows\system32>docker run hello-world
> docker: Error response from daemon: container 4c3983cefa1d4e066decd764cc2f2240ceaa982785d1cb3ce0aad3fe6ece6773 encountered an error during CreateContainer: failure in a Windows system call: The system cannot move the file to a different disk drive. (0x11) extra info: {"SystemType":"Container","Name":"4c3983cefa1d4e066decd764cc2f2240ceaa982785d1cb3ce0aad3fe6ece6773","Owner":"docker","IsDummy":false,"VolumePath":"\\\\?\\Volume{e0de1404-7a20-11e8-87c5-0004ffa70674}","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"D:\\ProgramData\\docker\\windowsfilter\\4c3983cefa1d4e066decd764cc2f2240ceaa982785d1cb3ce0aad3fe6ece6773","Layers":[{"ID":"aefd5f91-5a3a-592a-8db8-e8c4700ec28f","Path":"D:\\ProgramData\\docker\\windowsfilter\\123d27ded2df3728b97fffff1be8ff2fc63bdfb449d2a612361827dac5d1adaf"},{"ID":"98ebbca5-99a6-5347-bcf9-b082749c3204","Path":"D:\\ProgramData\\docker\\windowsfilter\\30f86bfc885718d2ec2c38c5169562cca9bfd794880c54e9711144d1655011d6"},{"ID":"41bb8286-81f5-5441-93e4-fa6cca4ac9a5","Path":"D:\\ProgramData\\docker\\windowsfilter\\a6ca616e92986d60d0a07876ddbc1f64d27d3d72fed4fabec3f6cde0f182cfbf"},{"ID":"25851739-2c34-57f9-9d64-4e5c3f201d54","Path":"D:\\ProgramData\\docker\\windowsfilter\\d4afc8eea85a7e6a8c84a7afb88c846f4ad66ad697f063bad3de5f8dbd4ffdcf"}],"HostName":"4c3983cefa1d","MappedDirectories":[],"HvPartition":false,"EndpointList":["9f24d59d-dd61-4cc6-95b4-ce2d9298cad4"],"Servicing":false,"AllowUnqualifiedDNSQuery":true}.

### Information
  - Is it reproducible?
yes

  - Is the problem new?
no, see this forum post from 2 years ago: https://forums.docker.com/t/the-system-cannot-move-the-file-to-a-different-disk-drive/25385

  - Did the problem appear with an update?
no

  - Windows Version: Windows Server 2016 LTS
  - Docker for Windows Version: 17.06.2-ee-14, build 6345dd7

### Steps to reproduce the behavior

  1. `docker run hello-world` where your Windows drive is something other than C:

**Comment by ebriney** [comment]
Hi @mscrivo, your issue concerns windows supported engine and must be reported directly on microsoft support here : https://support.microsoft.com/en-us/premier
