### ISSUE TITLE
firewall is blocking file sharing between windows and the containers

### ISSUE THREAD

**Issue by rboopathi** [docker/for-win#2159]
Getting below exception while trying to enable shared drive (C drive)

**firewall is blocking file sharing between windows and the containers**

Diagnostics ID: E92C5EEB-A5C9-440B-9E28-A68902A06578/2018-06-28_21-20-47

Checked the firewall 445 port. Tried check and uncheck File sharing in network sharing center. Tried uninstall and install File sharing in network sharing center. Tried setting the Docker (NAT) network to private. Nothing works. Same firewall blocking error still!!

**Comment by jasonbivins** [comment]
Hi @rboopathi   
http://success.docker.com/article/error-a-firewall-is-blocking-file-sharing-between-windows-and-the-containers

**Comment by buckyguy33** [comment]
I'm having a similar issue with Drive Sharing on Windows 10.  Symantec is installed on the endpoint.  I'm being told from my security folks that the Symantec policy applied to the machine trusts the private Docker network interface, private IP range and is set to allow traffic on 445 and 139 via TCP and 137 and 138 via UDP.  I can see in the Symantec logs that traffic being allowed yet Docker is complaining of a firewall blocking traffic.  When enabling Drive Sharing in Docker, what exactly are all of the checks being done to see if a firewall is enabled or could be blocking?

**Comment by corewrig** [comment]
My enterprise blocks 445 and 139, is there any way to get DockerSmbMount mapped to use a different port?

**Comment by RobinHSanner** [comment]
I am having the same issues.  I have tried all the workaround with no luck including turning off my firewall

/remove-lifecycle stale

**Comment by jakauppila** [comment]
I'm having issues with this as well.

Despite having this firewall allowance in place:
![image](https://user-images.githubusercontent.com/4100127/55734759-c0e31080-59e5-11e9-91cd-aaa47cd1bf4c.png)

I am still seeing blocks:
```
2019-04-08 09:55:30 DROP TCP 10.0.75.2 10.0.75.1 35635 445 60 S 1030279715 0 29200 - - - RECEIVE
```

Am I missing something?

**Comment by sashwin** [comment]
Hi Any updates here. I am facing the same issue

**Comment by cheahkhing** [comment]
+1 here as well.

**Comment by stephen-turner** [comment]
This is fixed with the new filesharing implementation in 2.2.0.3, so closing this ticket.
