### ISSUE TITLE
Docker run / docker pull not working

### ISSUE THREAD

**Issue by tamimibrahim17** [docker/for-win#2166]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 869E1054-C3D6-424A-AFDF-607BA0EF93C6/2018-07-02_15-20-16

### Expected behavior
 * docker pull should pull images.
 * docker run should pull images if images are not exists

### Actual behavior
 * I run `docker run hello-world`
get
```
PS C:\Users\User> docker run hello-world
Unable to find image 'hello-world:latest' locally
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: read udp 192.168.65.3:40350->192.168.65.1:53: i/o timeout.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
```
Here are some other steps I did after reading previous issues related to this
 * I have restarted docker couple of times.
 * I have reinstalled docker.
 * I have installed docker Edge version
 * I have changed docker DNS server to 8.8.8.8 and 8.8.4.4 
but no method worked for me

### Information
  - Windows Version: 10.0.16299
  - Docker for Windows Version: 18.05.0-ce-win67 (18263)
**`docker info`**
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.93-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155d4b0129
ID: FRH5:6HB6:GAUP:ZAVK:UFK6:PZDU:XO5C:2XMI:ARLR:LGAN:VXFY:VQOO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 20
 Goroutines: 36
 System Time: 2018-07-02T09:30:14.1990437Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by jaydubya1** [comment]
I can confirm i'm experiencing the same issue on Windows 10 - just did vanilla install of Docker for Windows and tried to run the hello world example - same error, Navigating to the url https://registry-1.docker.io/v2/ returns the same error as shown in PowerShell.

**Comment by jasonbivins** [comment]
@tamimibrahim17 
Is the server behind a proxy?  Is there anything that would be blocking the docker engine from reaching the internet?

**Comment by tamimibrahim17** [comment]
1. No server is not behind a proxy. In fact it's in my personal computer under home network. 

2. I can login to docker hub account, so I think docker get access to Internet. Is there any other way to test if docker get proper Internet access?

**Comment by tamimibrahim17** [comment]
After updating windows, this issue is fixed now!
