### ISSUE TITLE
win10

### ISSUE THREAD

**Issue by marcoscia** [docker/for-win#2167]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by LoreenRH** [comment]
Sorry we can't investigate without any diagnostics! Feel free to open a new issue with all the details. 

Thanks
