### ISSUE TITLE
Shared drive credentials can "go bad" and not provide any direct feedback

### ISSUE THREAD

**Issue by AnthonyMastrean** [docker/for-win#2169]
### Expected behavior

If there's an issue with the credentials for a shared drive, that should be displayed prominently to the user. A Windows notification pop-up would be OK.

If you run a Docker command with a mount/volume setting, _maybe_ you should get a warning there too. Or, more aggressively, a non-zero exit code (this probably needs some thinking through). 

I don't see any errors anywhere yet, but let me search my Windows event logs and Docker logs.

### Actual behavior

Docker doesn't do anything!

Docker commands with mount/volume settings appear to succeed. You end up running commands or applications without the necessary files and getting strange errors _inside_ your app or container (OK, so they're usually something like "file not found", but it still feels detached from the real problem).

### Information

This is reproducible. I don't think this is the _only_ case, but my team gets burned by this every time our passwords expire on the corporate Active Directory.

  - Windows Version: Windows 10 Pro 1803
  - Docker for Windows Version: 18.03

### Steps to reproduce the behavior

Again, this is what happens when our corporate passwords expire. I'll try to find other cases.

  1. Setup a shared drive w/ corporate credentials
  2. Wait like 90 days for them to expire (or ask your IT folks to expire them manually, maybe?!)
  3. Run the command in the Shared Drives page (it prints _nothing_)
```
PS> docker run --rm -v c:/Users:/data alpine ls /data
```
  4. If you use Reset Credentials and run again you'll see the expected pile of files/folders.
```
PS> docker run --rm -v c:/Users:/data alpine ls /data
All Users
Default
Default User
Public
desktop.ini
anthony.mastrean
```

**Comment by dakotahawkins** [comment]
This bit my co-worker the other day. We were coming back to a compose project after a few months, and volume mounts weren't working. It wasted a lot of his time.

**Comment by realdubb** [comment]
Wasted plenty of time because of this as well

**Comment by zfarrugia** [comment]
My colleagues and I run into this when our passwords expire after 90 days too.
Solution is simple, reset the credentials in docker settings. But I think Docker should notify the user if there is a permission issue.

**Comment by glasswatertable** [comment]
This was a SUPER FUN experience for a good week of getting no where with feedback or clues as to what was happening. 
Took me back to the time wastage days of internet explorer compatibility - +1 for the IE PTSD flashbacks

**Comment by AnthonyMastrean** [comment]
I noticed the following note in the 2.1.0.0 release

> Check stored credentials at start up before attempting to mount any shared drives, prompting the user to re-enter the credentials if the credentials are invalid.

**Comment by AnthonyMastrean** [comment]
I have several coworkers experiencing possible regressions on this https://github.com/docker/for-win/issues/2169#issuecomment-516874514

> I noticed the following note in the 2.1.0.0 release
> 
> > Check stored credentials at start up before attempting to mount any shared drives, prompting the user to re-enter the credentials if the credentials are invalid.

They're all on the latest version

![image](https://user-images.githubusercontent.com/217842/72182856-60409400-33ba-11ea-8340-592110c50413.png)
