### ISSUE TITLE
Ability to choose Windows containers during install?

### ISSUE THREAD

**Issue by tianon** [docker/for-win#217]
I would love to have the ability to choose Windows containers directly during install so that on first start, Docker fires up a Windows-native Docker daemon immediately.

Currently, Docker fires up a Linux VM initially, and I don't see an obvious way via the UI to remove the Linux VM either before or after switching to Windows containers (although it does show up via PowerShell, so I can remove it that way, but I don't know if that has negative side effects).

:heart:

**Comment by friism** [comment]
@tianon you can script this by running `DockerCli.exe -SwitchDaemon`. (it's in the `/resources/bin` folder).

Do you have more details on the use case? If you just want a raw daemon, you can script the install: https://github.com/docker/labs/blob/master/windows/windows-containers/Setup-Server2016.md

**Comment by tianon** [comment]
The use case is for Windows 10 (not Server), so https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_10 is a bit more complex than "install Docker for Windows and it'll take care of you", so I guess the use case would be folks who want/need Windows containers for development, but won't be using Linux containers at all (so creating/starting that VM, even just once, is a bit of a waste).  For my own use case, this was a one-off install on a personal install, so the VM was a minor irritation more than anything else and I don't need to really do it again. 😇

It's definitely not an urgent feature request, but I figured it'd be a good idea to get it filed and on the radar for consideration down the road. 😄 👍

(Definitely a fan of Docker for Windows -- makes the whole experience of using Docker on Windows way better regardless of the underlying containers. ❤️)

**Comment by dgageot** [comment]
@tianon thanks a lot for the feedback! After 1.13 is GA, we plan to improve the user experience for users who don't need the linux engine.

**Comment by rneugeba** [comment]
I created an internal tracking issue for this. Thanks for the request

**Comment by artiomchi** [comment]
Finally live and working in 18.03!

**Comment by walliski** [comment]
Another related feature would be to not only have `DockerCli.exe -SwitchDaemon`, but also allow for `DockerCli.exe -UseWindows` for example. This would make scripting docker usage a lot simpler :o

**Comment by abergs** [comment]
@walliski Yeah, I added an issue here: https://github.com/docker/cli/issues/1042

**Comment by abergs** [comment]
I see @rn... Where do I find the repo for DockerCli.exe? Did a lot of searcher for "SwitchDaemon" but couldn't find any code on github.

**Comment by rn** [comment]
the source code for `DockerCLI.exe` is not open sourced. It's part of the closed source Docker for Windows (and Mac) code base.

**Comment by abergs** [comment]
Oh, that’s too bad :( 
		
		

		/Anders (from phone)
	




On Tue, May 8, 2018 at 11:53 PM +0200, "Rolf Neugebauer" <notifications@github.com> wrote:












the source code for DockerCLI.exe is not open sourced. It's part of the closed source Docker for Windows (and Mac) code base.

**Comment by jasonbivins** [comment]
this feature has been added and is live in the stable channel - closing this issue
