### ISSUE TITLE
Linux containers will not mount drives when using Azure Active Directory Account

### ISSUE THREAD

**Issue by aderderian** [docker/for-win#2172]
I have tried multiple times to create local accounts, add permissions to that user, and re-apply settings in Docker to get Linux containers to work locally. Compose command just hangs and output is related to not being able to mount drives. 

Windows containers work, but I need Linux to work so I can publish to Azure Container Registry and then to Kubernetes. 

Version -
Version 18.03.1-ce-win65 (17513)
Channel: stable
93354b3

**Comment by jasonbivins** [comment]
@aderderian 
Please post a diagnostic ID
Are you running Windows 10 in Azure as well, or on a local machine that's connected to Azure AD?

**Comment by aderderian** [comment]
Hello,

I am not familiar in how to post a diagnostic id. Could you help with that?

The scenario is a local machine which is Windows 10.  This machine is joined to an Azure AD and I login with my company username to it.
