### ISSUE TITLE
Where to download nightly builds

### ISSUE THREAD

**Issue by edrevo** [docker/for-win#2176]
Related to https://github.com/docker/for-win/issues/2175.

Where can I find Windows binaries for the nightly Docker builds?

**Comment by jasonbivins** [comment]
Hi @edrevo   Nightly builds are no longer available

**Comment by CollinChaffin** [comment]
Then perhaps you should take down the darned page/directory that has been there FOREVER at https://download.docker.com/win/static as it still certainly makes it appear that you do.

**Comment by asfernandes** [comment]
The files at https://download.docker.com/win/static/ are too old.

**Comment by asfernandes** [comment]
Today, with Windows process isolation, it's possible to use the docker daemon without the Hyper-V stuff. But the docker standard installation process requires Hyper-V. It would be good if we could download and run the daemon. It would be even more good if there is a version of docker client with the daemon embedded, not requiring the start of a new process.
