### ISSUE TITLE
3BFE9F0E-DF11-4A4A-837E-6EA65F1C48B9/2018-07-07_09-10-30

### ISSUE THREAD

**Issue by francoishill** [docker/for-win#2187]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3BFE9F0E-DF11-4A4A-837E-6EA65F1C48B9/2018-07-07_09-10-30

### Expected behavior

Should be able to share a drive.

### Actual behavior

Unable to share a drive and the error displayed is "A firewall is blocking file Sharing between Windows and the containers.".

### Information

  - It is reproducible
  - The problem has been there from the start of this machine (after installing Docker 18.03.1-ce)
  - Windows Version: 10.0.16299
  - Docker for Windows Version: 18.03.1-ce

### Steps to reproduce the behavior

  1. Try and share a drive from the GUI

**Comment by LoreenRH** [comment]
Hi @francoishill, can you share drives from your cmd with `docker run --rm -v c:/Users:/data alpine ls /data` ?

**Comment by francoishill** [comment]
Wow @LoreenRH, that actually worked as expected. Why would this way work differently? Since now after the command the full drive is shared in the GUI too.

Just another note is that this is done on a company laptop and over the weekend I was connected to the company domain over VPN but now I am at the office. Could that have affected it?

**Comment by francoishill** [comment]
Hi @LoreenRH, unfortunately I tried this again on home network over VPN and the issue is still there. On the command-line it prints `Error response from daemon: Drive sharing seems blocked by a firewall.`.

I understand that this problem might be "fixable" from my side by perhaps chatting to our IT. Could you give any pointers as to how to ask/formalize a request to our IT?

I already confirmed correct ports are open in the Firewall. Besides, the firewall and Windows Defender are both completely disabled. We are using Trend Micro OfficeScan antivirus so perhaps I can request them to add "allow rules" as I do not have admin rights on its configuration.

Any assistance on how to formalize that request would be greatly appreciated.

**Comment by LoreenRH** [comment]
You can check in https://success.docker.com/article/error-a-firewall-is-blocking-file-sharing-between-windows-and-the-containers  

It could be that the vpn is enabling/disabling ports depending on which network you're connected or even the antivirus could be blocking smb protocol, so it's more of an IT issue on your side rather than a Docker for Windows issue, so I'll be closing this.
