### ISSUE TITLE
error mounting mongodb volume on Windows 10 Pro using Docker 18

### ISSUE THREAD

**Issue by jwnder** [docker/for-win#2189]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 90153922-3CBD-49A6-A40F-CFB90266C35C/2018-07-08_10-10-26

### Expected behavior

Running mongodb through docker 
- docker command: docker run --name mongo -v e:/VM/mongo:/data/db -p 27017:27017 mongo
- expected to be waiting for connection

### Actual behavior

- failed to write on mounted volume

### Information
  - Windows Version: 10 Pro
  - Docker for Windows Version: Docker version 18.03.1-ce, build 9ee9f40

### Steps to reproduce the behavior

  1. create a folder on whatever drive you want (example: e:/VM/mongo) 
  2. Share the folder e: in docker, use your windows credentials
  3. make sure that your windows user is administrator
  4. run command docker run --name mongo -v e:/VM/mongo:/data/db -p 27017:27017 mongo
  5. fails to write on mounted volume

**Comment by whitecolor** [comment]
https://github.com/docker/for-win/issues/138
