### ISSUE TITLE
Mounting a file requires drive letter or it's mounted as directory

### ISSUE THREAD

**Issue by rjplevin** [docker/for-win#2193]
I was trying to mount (via -v flag) a file on a Windows 10 host (`/tmp/foo.txt`), but it was being mounted in the container as a directory. If I specify it instead as `C:/tmp/foo.txt` or `C:\tmp\foo.txt`, it is properly mounted as a file. (And, oddly, if I specify it as `\tmp\foo.txt`, docker reports
`The source path "\\tmp\\pygcam-docker-dirmap.txt" is not a valid Windows path.`

**Comment by matclab** [comment]
Same problem here with docker 19.03.4 on windows 10.
