### ISSUE TITLE
Container crashing when installing npm module from git-repository

### ISSUE THREAD

**Issue by felixnorden** [docker/for-win#2195]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 64D35A89-AC9A-411D-867A-CA15584BEC1D/2018-07-09_15-24-38

### Expected behavior
Private dependency installs without failure and continues installing dependencies.

### Actual behavior
Container crashes with Windows System call error `0xc037010a` and can't be restarted.

### Information

  - Windows Version: 10.0.17134
  - Docker for Windows Version: 18.05.0-ce-win67 (18263)

I'm currently working on a new build pipeline for my development team and it involves running the build environment as a docker container to then output a built image of the given repository/branch. Everything seems to work, except for when I install the frontend dependencies using either yarn or npm. I have managed to install the dependencies successfully 2 times, but the other tries result in the container just crashing and can't be restarted. 

I have tried both installing everything manually and by different PowerShell scripts, run the scripts both in the Dockerfile and on a running container, but nothing has changed. I first noted this problem when we tried to install a dependency from a private GitHub repository. When I made the simple example below I also noted that this applies to public GitHub repos as well. 

I have tried lots of other stuff as well, so just ask me if you are wondering anything :)

### Steps to reproduce the behavior

  1. Build the image of the `Dockerfile` found below.

```
# escape=`

FROM microsoft/dotnet-framework:4.7.2-sdk

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# Install Chocolatey
RUN Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

# Install Git, Node and Yarn
RUN choco install -y git nodejs-lts; `
    choco install -y yarn --ignore-dependencies; 

RUN npm install -g npm;

WORKDIR C:\node-example

RUN npm init --yes; `
    npm install git+https://github.com/anvk/babel-npm-module-example

```

**Comment by felixnorden** [comment]
After further investigation, npm crashes on both public and private repositories, but yarn worked on the public ones. Also, the big issue seems to be the authentication when cloning a private repository as this crashes with the same error. Could it maybe have to do with the container trying to reach outside its own scope of the machine?

**Comment by kevinbosman** [comment]
I'm getting the same crash trying to `npm install` or `npm ci` with a git reference in `package.json`

Docker Version 18.05.0-ce-win67 (18263)
Windows Version 10.0.17134.112

**Comment by felixnorden** [comment]
**Update:** I have managed to accomplish successful git authentication using SSH by doing a clean install of OpenSSH. However, the problem with npm and yarn still persists... Is there some configuration that has to be made to npm/yarn in order for them to use the correct SSH client or anything? :) 

This image allows for manually cloning private repositories:

```
# escape=`

FROM microsoft/windowsservercore:1803

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# Install MinGit
RUN [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest 'https://github.com/git-for-windows/git/releases/download/v2.18.0.windows.1/MinGit-2.18.0-64-bit.zip' -Outfile MinGit.zip; `
    Expand-Archive c:\MinGit.zip -DestinationPath c:\MinGit; `
    $env:PATH = $env:PATH + ';C:\MinGit\cmd\;C:\MinGit\cmd'; `
    Set-ItemProperty -Path "'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment\'" -Name Path -Value $env:PATH 

# Install OpenSSH
RUN [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest 'https://github.com/PowerShell/Win32-OpenSSH/releases/download/v7.7.1.0p1-Beta/OpenSSH-Win64.zip' -Outfile openssh.zip ; `
    Expand-Archive openssh.zip -DestinationPath "'C:\Program Files\'" ; `
    Remove-Item openssh.zip -Force

# Installing Services (per https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH)
RUN Set-ExecutionPolicy Bypass; & 'C:\Program Files\OpenSSH-Win64\install-sshd.ps1';
RUN Set-Service ssh-agent -StartupType Automatic

# Fixing premissions (per https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH)
RUN Set-ExecutionPolicy Bypass -Confirm:$false; & 'C:\Program Files\OpenSSH-Win64\FixHostFilePermissions.ps1';
WORKDIR C:\

# Configure OpenSSH to correct path
RUN SETX PATH '"C:\Program Files\OpenSSH-Win64";%PATH%'
ENV GIT_SSH "C:\Program Files\OpenSSH-Win64\ssh.exe"
```

**Comment by felixnorden** [comment]
**Update:** So, after a lot of grueling trial and error I have come up with a Dockerfile that works without crashing. I didn't manage to get SSH to work, but providing an access token to GitHub and then using Yarn with the cache folder set to root seems to work! 

Here's what I came up with:
```
# escape=`

FROM microsoft/windowsservercore:1803

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# Install MinGit
RUN [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest 'https://github.com/git-for-windows/git/releases/download/v2.18.0.windows.1/MinGit-2.18.0-64-bit.zip' -Outfile MinGit.zip; `
    Expand-Archive c:\MinGit.zip -DestinationPath c:\MinGit; `
    $env:PATH = $env:PATH + ';C:\MinGit\cmd\;C:\MinGit\cmd'; `
    Set-ItemProperty -Path "'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment\'" -Name Path -Value $env:PATH 

RUN Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')); `
    choco install nodejs yarn -y

RUN mkdir C:\cache

# Set cache folder to root
ENV YARN_CACHE_FOLDER=C:\cache
```
I hope this problem gets fixed in the future, or at least improving on the error logging/handling not just swallow everything when things go wrong. 

Hope this helps for others out there :)

**Comment by Bohdan-Sydor** [comment]
Just verified that this issue is not reproducible in mcr.microsoft.com/windows/servercore:1809.
