### ISSUE TITLE
Share Drive

### ISSUE THREAD

**Issue by ghost23** [docker/for-win#2198]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B4565F90-3516-423E-B417-EB1E244DD4F5/2018-07-10_11-28-39

### Expected behavior
I am trying to share my C drive through the Docker for Windows GUI.

### Actual behavior
I get the Firewall blocked message.

### Information
I looked through various threads online. I re-installed the File and Printer service for the DockerNAT network adapter, I checked my Firewall settings and made sure, that the TCP and UDP ports are open for 10.0.75.1 / 2, I tried settting the DNS to fixed adress and then back again to force a network refresh.
I am out of ideas.

### Steps to reproduce the behavior
I click on the checkbox for my C Drive in the "shared drives" settings menu and then "apply".

**Comment by jasonbivins** [comment]
@ghost23 
The steps here should help:  https://success.docker.com/article/error-a-firewall-is-blocking-file-sharing-between-windows-and-the-containers

**Comment by ghost23** [comment]
Thank you. But I went through that article already. I couldn't manage to get the shared drive to work though.
