### ISSUE TITLE
Cannot attach to a container on WSL

### ISSUE THREAD

**Issue by Alebat** [docker/for-win#2199]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 720444C3-E69C-4A2B-996B-2B1B89A57A4A/2018-07-10_14-17-24

Hi all, I installed docker for windows with Hyper-V support and the option 'Expose daemon on tcp://localhost:2375 without TLS' enabled. I am trying to use the daemon through the Ubuntu CLI, here the output of the command docker version:
```
$ docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      18.03.1-ce
 API version:  1.37 (minimum version 1.24)
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:21:42 2018
 OS/Arch:      windows/amd64
 Experimental: false
```

### Expected behavior
If I run `docker run hello-world`, the daemon creates the image and the container. I should get the following output (actual output of the winows client on the same machine:
```
Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message...
```

### Actual behavior
Instead, on WSL (Bash on Ubuntu on Windows, Windows Subsystem Linux), I get the following, the data is downloaded, the image created and then an error: `tls: oversized record received with length 20527`. the same I get with `docker attach ...`.
```
$ docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
407ada6e90de: Pull complete
85710d780d68: Pull complete
9539f949462c: Pull complete
ec0bc3d03159: Pull complete
Digest: sha256:3e1764d0f546ceac4565547df2ac4907fe46f007ea229fd7ef2718514bcec35d
Status: Downloaded newer image for hello-world:latest
tls: oversized record received with length 20527
```
### Information
I did not try to reproduce the problem on another machine. I encounter this problem every time I try to attach to a container from WSL to docker for windows. Obviously I can not install the docker daemon on WSL due to virtualization restrictions.

My windows version is 10.0.16299 N/D build 16299

### Steps to reproduce the behavior
1. Run Docker daemon for Windows
2. On WSL `docker run hello-world`

**Comment by jasonbivins** [comment]
@Alebat try typing ```docker.exe``` instead of ```docker```
I got a different error using ```docker run hello-world``` but it worked with the .exe

**Comment by kenorb** [comment]
Same error on Windows 10 when running the container:

```
$ docker exec -it my_linux_container bash
tls: oversized record received with length 20527
```

**Comment by kenorb** [comment]
```
$ docker -H :2375 -D -l debug run hello-world
tls: oversized record received with length 20527
$ DOCKER_HOST=tcp://:2375 docker run hello-world
tls: oversized record received with length 20527
$ DOCKER_HOST=:2375 docker run hello-world
tls: oversized record received with length 20527
```

Since port 2375 suppose to be a non-TLS connection, why docker it's interpreting it as TLS? TLS should run on 2376, not 2375.

**Comment by ishu3101** [comment]
I'm also getting the same error. I have also installed docker for windows with Hyper-V enabled and the option `Expose daemon on tcp://localhost:2375 without TLS` enabled. I am trying to use the daemon through the Ubuntu CLI, here the output of the command docker version:

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.6.2
 Git commit:   f5ec1e2
 Built:        Thu Jul  5 23:07:48 2018
 OS/Arch:      linux/amd64

Server:
 Version:      18.06.1-ce
 API version:  1.38 (minimum version 1.12)
 Go version:   go1.10.3
 Git commit:   e68fc7a
 Built:        Tue Aug 21 17:29:02 2018
 OS/Arch:      linux/amd64
 Experimental: false
```

```
$ docker run -it ubuntu:18.04
tls: oversized record received with length 20527
```

```
$ docker.exe run -it ubuntu:18.04
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'
```

```
$ echo $DOCKER_HOST
tcp://localhost:2375
```

**Comment by kenorb** [comment]
I've removed `docker.io` and installed `docker-ce` in WSL and it worked.

```
sudo apt-get remove docker.io
sudo apt-get remove --purge docker*
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get update
sudo apt-get install docker-ce
```

If you've trouble removing apt packages, try [upgrading WSL](http://wsl-guide.org/en/latest/update.html) first.

Related: [“tls: oversized record received with length 20527” trying to “docker run” from Win10 WSL Bash only](https://stackoverflow.com/q/49049787/55075)

**Comment by Alebat** [comment]
Great! I was using the **old version** from APT.

I followed the official guide [https://docs.docker.com/install/linux/docker-ce/ubuntu/](https://docs.docker.com/install/linux/docker-ce/ubuntu/) from the beginning till INSTALL DOCKER CE/2 inclusive.

All those commands are necessary, as the version on APT is old.

**docker.exe**
When using docker.exe WSL actually calls the windows executable through its superpowers, but somehing with standard i/o is going wrong.
