### ISSUE TITLE
Network timed out while trying to connect to https://index.docker.io

### ISSUE THREAD

**Issue by ktor** [docker/for-win#22]
### Expected behavior
Pulling hello-world when I am not behind proxy.

### Actual behavior
    > docker run hello-world
    Unable to find image 'hello-world:latest' locally
    Pulling repository docker.io/library/hello-world
    docker: Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/hello-world/images. You may want to check your internet connection or if you are behind a proxy..
    See 'docker run --help'.`

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
`6412C29D-46BA-4A66-BF45-1681D9ED06C0/2016-08-04_10-35-01`

  - host distribution and version (Windows version, build number, etc)

        > ver
        Microsoft Windows [Version 10.0.10586]`

### Steps to reproduce the behavior

  1. Uninstall Docker for Windows 10
  2. Install Docker for Windows 10
  3. run `docker run hello-world`

**Comment by dgageot** [comment]
Hi @ktor, thank you for the report. That really helps improve the product!

I see from the diagnostic information that you have multiple "vEthernet (DockerNAT)" network adapters.

Could you run this command **from an elevated powershell"**, then restart Docker and see if it fixes the issue?

```
$vmNetAdapter = Get-VMNetworkAdapter -ManagementOS -SwitchName DockerNAT
Get-NetAdapter "vEthernet (DockerNAT)" | ? { $_.DeviceID -ne $vmNetAdapter.DeviceID } | Disable-NetAdapter -Confirm:$False -PassThru | Rename-NetAdapter -NewName "OLD"
```

**Comment by ktor** [comment]
Hi @dgageot , thank you! It worked!
