### ISSUE TITLE
Docker install succeeded (Windows 10), however docker will not start

### ISSUE THREAD

**Issue by erikas57** [docker/for-win#2200]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B995997F-7E8F-451C-BE32-DA5F5E4E3C98/2018-07-10_09-50-32

### Expected behavior
Docker would start up successfully.

### Actual behavior
After 10-20 minutes of seeing 'Docker is starting', I get an error about a named pipe.  

### Information

  - Windows Version: Windows 10 version 1703
  - Docker for Windows Version: 18.03.1-ce-win65 (17513)

- Note: I've also tried with the Edge channel version; same result
- This is very reproducible - I've uninstalled & reinstalled several times.
- I did have docker running on this machine a couple weeks ago, but the IT department needed to re-image my laptop with a fresh install of Windows 10 (drive was wiped, so no old files hanging around to mess with install).
- If I check services, I do see that 'Docker for Windows Service' is running.  
- If I open Hyper-V Manager, I see MobyLinuxVM up and running
- I've also tried 'Reset to Factory Defaults'

### Steps to reproduce the behavior

  1. Install docker... success
  2. Double-click 'Docker for Windows'
  3. Wait several minutes
  4. Get error message

**Comment by jasonbivins** [comment]
@erikas57  It looks like the Docker Daemon can't start, but I don't see anything in the logs indicating why.  Can you check the Application logs in your event viewer to see if there are any clues?

**Comment by erikas57** [comment]
I'm not seeing anything suspicious there unfortunately.
