### ISSUE TITLE
add integrated camera on laptop to support docker

### ISSUE THREAD

**Issue by dsaydon90** [docker/for-win#2201]
I have surface pro 4 with integrated camera.
today with docker ce for windows I can attach any disk on key or any partition in my windows OS under docker settings --> shared drives

But I can't attach my integrated camera (I didn't check if usb camera can be attached)

I mean no /dev/video0 is appear in my docker container (based on ubuntu)

any way you will be able to support the integrated camera of my laptop?

**Comment by rn** [comment]
Unfortunately, this is not possible. Hyper-V would need to offer USB device passthrough which it doesn't. This is not something we (Docker) can fix so closing this issue.

**Comment by dorsanyvision** [comment]
Thank you @rn  for your feedback.
did you ever found a workaround for this? maybe something in the Hyper-V level?

**Comment by dsaydon90** [comment]
Thank you @rn for your feedback.
did you ever found a workaround for this? maybe something in the Hyper-V level?

**Comment by rn** [comment]
There is no workaround I know off. It requires USB device pass through being implemented by Microsoft first.
