### ISSUE TITLE
Containers with --restart=always doesn't work after system boot-up

### ISSUE THREAD

**Issue by triforcely** [docker/for-win#2202]
- [x] I have tried with the latest version of my channel (**Stable** or ~~Edge~~)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C15145D8-FBAB-42D7-BEDF-E1D9C214D5F6/2018-07-11_18-02-45

### Expected behavior
I can use containers that were configured with --restart=always and expose ports to host after my computer is rebooted/turned on. I expect everything to work without the need of any additional work on my side since I assume everything is already set-up.

### Actual behavior
When docker finishes it initialization after system boots up and "docker ps" reports that containers are running, my attempts to connect to "postgres" and "redis" containers fail (these are the names of actual images).

### Information
When I restart docker manually (system tray, right click on whale > Restart) and docker finishes re-starting, they work just fine. Problem only exists when docker starts automatically when system boots up.

### Steps to reproduce the behavior

I'm using "redis" image in this example but the same thing happened with "postgres".

  1. Create container with restart-always flag, e.g. redis (docker run -d -p 6379:6379 --name redis --restart=always redis)
  2. Try to connect to redis instance (e.g. using RedisDesktopManager tool)
  3. It works ¯\_(ツ)_/¯
  4. Restart computer, wait for docker initialization to finish.
  5. (Optional) run "docker ps" to ensure that container is running
  6. Try to connect to redis: it won't connect.
  7. (Optional) Restart docker manually
  8. Try to connect to redis: it **will** connect.

**Comment by jasonbivins** [comment]
https://github.com/docker/for-win/issues/1192

**Comment by jasonbivins** [comment]
I havent been able to repro this consistently - it fails for me one out of every 10 or so tries

**Comment by triforcely** [comment]
Were you able to reproduce this consistently with linux containers?

**Comment by triforcely** [comment]
I was paying more attention to it since this issue was created and it doesn't happen every time even with linux containers. They sometimes autostart fine, however more often they fail. Maybe it is somehow related to my hardware (Ryzen 2700x CPU - I think industry is more Intel focused when it comes to virtualization)?
