### ISSUE TITLE
Spam of "Log will not be processed. Return code from OpenEventLog is 87" to the logs

### ISSUE THREAD

**Issue by fvoncina** [docker/for-win#2204]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 166D2AEB-9CEC-4EB2-B0FF-E3B1D5FFED4A/2018-07-11_22-42-25

### Actual behavior
I get thousands of the following errors in the service logs (ProgramData\Docker\service.XX.txt), several hundred per second:
[WindowsDaemon  ][Warning] Error opening event log file Parameters. Log will not be processed. Return code from OpenEventLog is 87.

It also writes the same error to the Application Event Log.

This behavior causes almost 100% use of CPU between Docker service process and Windows Event Log service.

  - Windows Version: Windows 10 1803
  - Docker for Windows Version: 18.03.1-ce-win65 (17513)

**Comment by tigwyk** [comment]
I believe I'm having the same issue. Unfortunately my log file doesn't show anything useful but my Application Event Log is filling up by the thousands with the exact same warning, "Error opening event log file Parameters. Log will not be processed. Return code from OpenEventLog is 87."

I am on the latest version of stable, as far as I know.

Windows 10 Insider Build 17713.rs5_release.180706-1551

Docker for Windows version: 18.03.1-ce-win65 (17513)

Diagnostics ID: E9BEF5E1-A8C8-4602-9ED3-CAAF6BE922BF/2018-07-17_16-07-53

[log.txt](https://github.com/docker/for-win/files/2203676/log.txt)

**Comment by nzacca** [comment]
FWIW, I don't have docker installed but I was able to stop the event log from filling up with these warnings by disabling the SNMP service as per: https://answers.microsoft.com/en-us/windows/forum/windows_10-performance/svchostexe-is-causing-system-slowdown-due-to/d7f7b94b-8184-4704-adc0-99fc93f36642

**Comment by tigwyk** [comment]
It does appear that disabling the SNMP service rectified this. Now I need to figure out why the SNMP service is going nuts. Thank you, @nzacca

**Comment by wholroyd** [comment]
According to the Windows Feedback for this issue (https://aka.ms/AA1vla6), this issue should be fixed in the Windows Insider build 17723.

**Comment by nzacca** [comment]
I can confirm that 17723 has fixed the issue. Thanks @wholroyd !
