### ISSUE TITLE
Docker for Windows 10 Firewall blocks use of Shared Drive

### ISSUE THREAD

**Issue by RichardDoyle-kcom** [docker/for-win#2205]
- [x ] I have tried with the latest version of my channel (Stable)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 0BADA315-03B3-4931-A80A-6C54588C82F1/2018-07-12_11-00-59

### Expected behavior
Docker should work normally with Windows 10
### Actual behavior
C:\Users\DoyleR\Workspace\RSP-Shared-IAM>docker-compose up -d
Starting wiremock                   ... done
Creating spring-cloud-config-server ... error

ERROR: for spring-cloud-config-server  Cannot create container for service spring-cloud-config-server: b'Drive sharing seems blocked by a firewall'

ERROR: for spring-cloud-config-server  Cannot create container for service spring-cloud-config-server: b'Drive sharing seems blocked by a firewall'
ERROR: Encountered errors while bringing up the project.

### Information

  - Windows Version: 10
  - Docker for Windows Version: 18.03.1-ce-win65 (17513)

### Steps to reproduce the behavior

 1. Run "docker-compose up -d" from a cmd window.

###Attempted solutions
1. Added firewall rules for docker.exe and docker-compose.exe on port 445, no change
2. Tried sharing the C drive for my user still fails
3. When I try to share the C drive from Docker settings, it says a firewall has blocked the attempt even though I have set up sharing for my domain user (Full Control).

**Comment by patrick-white** [comment]
I'm having the same issue diagnostic ID:
4991BF02-764F-4C9D-9060-6B82311F852D/2018-07-12_18-43-49

To add, I've also tried the steps outlined on:

https://blog.olandese.nl/2017/05/03/solve-docker-for-windows-error-a-firewall-is-blocking-file-sharing-between-windows-and-the-containers/

But I get a Windows error not allowing me to uninstall the File and Printer Sharing driver related to a Windows bug.

I set the network to private using the Powershell command:
`Set-NetConnectionProfile -interfacealias "vEthernet (DockerNAT)" -NetworkCategory Private`

And that seems to make it work for me.

**Comment by RichardDoyle-kcom** [comment]
@patrick-white Thanks for the tip, I tried your PowerShell command, it changes the error that I see but still encounters the block:

C:\Users\DoyleR\Workspace\RSP-Shared-IAM>docker-compose up -d
Creating network "rsp-shared-iam_docker_network" with driver "bridge"
Creating wiremock                   ... error
Creating spring-cloud-config-server ...

ERROR: for wiremock  Cannot start service wiremock: b'driver failed programming external connectivity on endpoint wiremock (35ab03d5f3361b7c9fceb437f448f2dab84927b9d97330a8168dbc422ecf0a95): Error starting userland proxy: mkdir /port/tcp:0.Creating spring-cloud-config-server ... error

ERROR: for spring-cloud-config-server  Cannot create container for service spring-cloud-config-server: b'Drive sharing seems blocked by a firewall'

ERROR: for wiremock  Cannot start service wiremock: b'driver failed programming external connectivity on endpoint wiremock (35ab03d5f3361b7c9fceb437f448f2dab84927b9d97330a8168dbc422ecf0a95): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:9999:tcp:172.18.0.2:8080: input/output error'

ERROR: for spring-cloud-config-server  Cannot create container for service spring-cloud-config-server: b'Drive sharing seems blocked by a firewall'
ERROR: Encountered errors while bringing up the project.

**Comment by pjirsa** [comment]
Getting the same issue as well. Even after turning off windows firewall completely and restarting docker.

**Comment by RichardDoyle-kcom** [comment]
@patrick-white @pjirsa After checking the support case below:

https://github.com/docker/for-win/issues/1038

I killed any ghost processes by using "docker ps -a" followed by "docker rm -f <tag>" and then, wait for it, ... restarted Docker!! Then all went smoothly for docker-compose. 

Still having issues with running a build for my own docker containers, but that probably belongs in a different ticket.

**Comment by yan9yu** [comment]
I've got the same issue and finally solved it with the following steps:
1. Run the following code in an `elevated` prompt.
```bash
Set-NetConnectionProfile -interfacealias "vEthernet (DockerNAT)" -NetworkCategory Public
```
NOTE: Make sure you are using an `elevated` prompt, otherwise it won't work.

2. Restart Docker Services
3. Tick the `Shared Drives` options in `Setting -> Shared Drives -> <Your-Drive>:`

Hope it helps.

**Comment by slim-hmidi** [comment]
When I'm connecting using the vpn of the company I have the same issue when launching docker-compose up, and I tried to reset the credentials and trying the given solutions mentioned in the comments and I can't fix the issue. Is it due to some rules made by the administrator to not allow it to access the disque when it is on VPN?
