### ISSUE TITLE
Executables copied into an image via build are "corrupted" somehow

### ISSUE THREAD

**Issue by waynesi** [docker/for-win#2209]
- [x] I have tried with the latest version of my channel (Stable)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
I copied some executables into my image via Dockerfile and I expect to run them with no issues.

### Actual behavior
I entered a container interactively and attempted to run the file, but ended up with an error "The system cannot execute the specified program." -- Please read the rest of the story in the details section before jumping to a conclusion.

### Information

  - Windows Version:  Windows 10 Pro 1709
  - Docker for Windows Version:

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:21:42 2018
  OS/Arch:      windows/amd64
  Experimental: false

### Steps to reproduce the behavior

I wrote a Dockerfile to build a Windows Server Core based image on top of the microsoft/dotnet-framework:3.5-sdk. All the versions of that image have been tried but all ended up with the same issue.

The Dockerfile doesn't do anything fancy. The line I wrote to copy the files is as below and it's pretty much all the Dockerfile does.
`COPY ["FolderOfMyExecutables", "C:\\Program Files (x86)\\TargetFolder"]`

Then I built the image with no errors and I started a container by running `docker run -it MyImageName:Mytag CMD`

Then within the container, I could CD into the TargetFolder and saw all my executables there.

When I tried to run one of them, I ended up with the error "The system cannot execute the specified program.", although the executable I wanted to run was a command line application.

After hours of searching around on the Internet, I got nothing although I'm pretty sure my executables definitely run on a Windows Server Core physical or virtual machine.

Finally I decided to try mounting the files from a host folder into the container using -v option, and I managed to run my executables in the container!

I used "diff" to compare the files from the TargetFolder and from the mounted folder, but there were no differences at all, except the ones in the TargetFolder just refused to run!

Finally, I tried another experiment.  I no longer mounted the host folder. I simply started a new container from the image, got into it, created a temp folder within the container, copied all my files to the temp folder, and then copied back and overwrote the files. So basically nothing changed on those files, but now they're all okay to run!

I also tried to commit the changes from the container back to the image, but I still got the exact same issue with the new image and could only be solved by the same way.

Is it possibly because of the file system permissions?

**Comment by waynesi** [comment]
I've uploaded the files to demonstrate the issue. [BugDemo.zip](https://github.com/docker/for-win/files/2196726/BugDemo.zip)

Once built the image, run an interactive CMD and go to C:\\Program Files (x86)\\Tools and run BRCC32, you should see the the error "The system cannot execute the specified program."

Now create a temp folder and copy over all the files, and copy back. You now should be able to run the executable.

**Comment by thaJeztah** [comment]
ping @jhowardmsft@johnstep PTAL

**Comment by johnstep** [comment]
I can reproduce the problem. There are no obvious security issues with the files; the security descriptors look as expected, and modifying them does not help. The debugger cannot map the module either::
```
C:\>C:\dbg\cdb "C:\Program Files (x86)\Tools\brcc32.exe"

Microsoft (R) Windows Debugger Version 10.0.16299.15 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.

CommandLine: "C:\Program Files (x86)\Tools\brcc32.exe"
Cannot execute '"C:\Program Files (x86)\Tools\brcc32.exe"', Win32 error 0n998
    "Invalid access to memory location."
Debuggee initialization failed, Win32 error 0n998
Invalid access to memory location.
```

However, as you mentioned, copying works fine, as does mounting that directory from the image into the container. However, copying the exact same files to another part of the image (from the host) also leads to executables that cannot run. I may set up a kernel debugger to learn more.

**Comment by johnstep** [comment]
For reference (and as is probably obvious from the name), the executable is Intel 32-bit:

```
C:\>C:\dbg\cdb.exe -z "C:\Program Files (x86)\Tools\brcc32.exe" -c "!dh brcc32"

Microsoft (R) Windows Debugger Version 10.0.16299.15 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:\Program Files (x86)\Tools\brcc32.exe]
Symbol search path is: srv*
Executable search path is:
ModLoad: 00400000 00432000   C:\Program Files (x86)\Tools\brcc32.exe
*** WARNING: Unable to verify checksum for brcc32.exe
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for brcc32.exe -
eax=00000000 ebx=00000000 ecx=00000000 edx=00000000 esi=00000000 edi=00000000
eip=00401000 esp=00000000 ebp=00000000 iopl=0         nv up di pl nz na po nc
cs=0000  ss=0000  ds=0000  es=0000  fs=0000  gs=0000             efl=00000000
brcc32+0x1000:
00401000 a164d04100      mov     eax,dword ptr [brcc32!RxCompileStatusImplTrackingCurrentStatus$qqsri+0x14a11 (0041d064)] ds:0041d064=00000000
0:000> cdb: Reading initial command '!dh brcc32'

File Type: EXECUTABLE IMAGE
FILE HEADER VALUES
     14C machine (i386)
       8 number of sections
9CE02625 time date stamp Mon May 26 22:12:05 2053

       0 file pointer to symbol table
       0 number of symbols
      E0 size of optional header
    818E characteristics
            Executable
            Line numbers stripped
            Symbols stripped
            Bytes reversed
            32 bit word machine
...
```

**Comment by johnstep** [comment]
I tested brcc32.exe on Windows 1803 and found that it runs with process isolation, but fails with Hyper-V. There is something interesting about the executable; 4 of its sections are shared, 2 of which are writable:
```
link /dump /headers brcc32.exe | sls -co 13,1 shared

  SECTION HEADER #1
      CODE name
     1C000 virtual size
      1000 virtual address (00401000 to 0041CFFF)
     1BA00 size of raw data
       600 file pointer to raw data (00000600 to 0001BFFF)
         0 file pointer to relocation table
         0 file pointer to line numbers
         0 number of relocations
         0 number of line numbers
  F0000060 flags
           Code
           Initialized Data
>          Shared
           Execute Read Write

  SECTION HEADER #4
    .rdata name
      1000 virtual size
     28000 virtual address (00428000 to 00428FFF)
       200 size of raw data
     22200 file pointer to raw data (00022200 to 000223FF)
         0 file pointer to relocation table
         0 file pointer to line numbers
         0 number of relocations
         0 number of line numbers
  50000040 flags
           Initialized Data
>          Shared
           Read Only

  SECTION HEADER #7
    .reloc name
      2000 virtual size
     2B000 virtual address (0042B000 to 0042CFFF)
      1C00 size of raw data
     23200 file pointer to raw data (00023200 to 00024DFF)
         0 file pointer to relocation table
         0 file pointer to line numbers
         0 number of relocations
         0 number of line numbers
  50000040 flags
           Initialized Data
>          Shared
           Read Only

  SECTION HEADER #8
     .rsrc name
      4630 virtual size
     2D000 virtual address (0042D000 to 0043162F)
      4630 size of raw data
     24E00 file pointer to raw data (00024E00 to 0002942F)
         0 file pointer to relocation table
         0 file pointer to line numbers
         0 number of relocations
         0 number of line numbers
  F0000040 flags
           Initialized Data
>          Shared
           Execute Read Write
```
Being shared means that processes can share the same physical pages. While this is certainly bad practice, and may trigger this issue, more debugging is needed to determine the root cause.

**Comment by johnstep** [comment]
The access violation occurs while setting up the user-mode process address space:
```
1: kd> !process -1 0; kC; r
PROCESS ffffc6069f9c9400
    SessionId: 1  Cid: 0000    Peb: 003e8000  ParentCid: 06f8
    DirBase: 26b00002  ObjectTable: ffffd782c5f5fa40  HandleCount:   3.
    Image: brcc32.exe

Call Site
nt!LdrpResGetResourceDirectory
nt!LdrpResSearchResourceMappedFile
nt!LdrResSearchResource
nt!PspLocateInPEManifest
nt!PspSetupUserProcessAddressSpace
nt!PspAllocateProcess
nt!NtCreateUserProcess
nt!KiSystemServiceCopyEnd
0x0
rax=000000000042d010 rbx=0000000000000000 rcx=000000000042d000
rdx=000000000042d000 rsi=000000000002d000 rdi=0000000000400000
rip=fffff801a6ec78c5 rsp=ffffea0c8d4fe1b0 rbp=ffffc6069f329000
 r8=0000000000432000  r9=ffffea0c8d4fe330 r10=0000000000000000
r11=0000000000032000 r12=0000000000001000 r13=0000000000400100
r14=0000000000032000 r15=0000000000000001
iopl=0         nv up ei ng nz na pe cy
cs=0010  ss=0018  ds=002b  es=002b  fs=0053  gs=002b             efl=00000283
nt!LdrpResGetResourceDirectory+0x315:
fffff801`a6ec78c5 0fb7420c        movzx   eax,word ptr [rdx+0Ch] ds:002b:00000000`0042d00c=????
```

**Comment by johnstep** [comment]
It looks like only the first page of the executable is readable by the process:
```
1: kd> !vad @rdx+0xc 1

VAD @ ffffc6069ebf8830
  Start VPN                  400  End VPN              431  Control Area  ffffc6069f988880
  FirstProtoPte ffffd782c53b2e70  LastPte ffffd782c53b2ff8  Commit Charge                c (0n12)
  Secured.Flink                0  Blink                  0  Banked/Extend                0
  File Offset                  0  
      ImageMap ViewShare EXECUTE_WRITECOPY 

ControlArea  @ ffffc6069f988880
  Segment      ffffd782c5316730  Flink      ffffc6069ebf8890  Blink        ffffc6069ebf8890
  Section Ref                 1  Pfn Ref                  2e  Mapped Views               31
  User Ref                   1a  WaitForDel                0  Per-Session
  File Object  ffffc6069ec83520  
  Flags (440200a0) Image File GlobalMemory GlobalOnlyPerSession 

      \VSMB-{dcc079ae-60ba-4d07-847c-3493609c0870}\F41BCE77-095B-5F42-8B51-3A071736714C\Files\brcc32.exe

Segment @ ffffd782c5316730
  ControlArea       ffffc6069f988880  BasedAddress  0000000000400000
  Total Ptes                      32
  Segment Size                 32000  Committed                   21
  Image Commit                     c  Image Info    ffffd782c5316778
  ProtoPtes         ffffd782c53b2e70
  Flags (4c0000) ProtectionMask 

Reload command: .reload brcc32.exe=00000000`00400000,32000

1: kd> !object 0xffffc6069ec83520
Object: ffffc6069ec83520  Type: (ffffc6069cd00c60) File
    ObjectHeader: ffffc6069ec834f0 (new version)
    HandleCount: 1 PointerCount: 32774
    Directory Object: 00000000  Name: \VSMB-{dcc079ae-60ba-4d07-847c-3493609c0870}\F41BCE77-095B-5F42-8B51-3A071736714C\Files\brcc32.exe {vmsmb}

1: kd> db 0x400000
00000000`00400000  4d 5a 50 00 02 00 00 00-04 00 0f 00 ff ff 00 00  MZP.............
00000000`00400010  b8 00 00 00 00 00 00 00-40 00 1a 00 00 00 00 00  ........@.......
00000000`00400020  00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00  ................
00000000`00400030  00 00 00 00 00 00 00 00-00 00 00 00 00 01 00 00  ................
00000000`00400040  ba 10 00 0e 1f b4 09 cd-21 b8 01 4c cd 21 90 90  ......	.!..L.!..
00000000`00400050  54 68 69 73 20 70 72 6f-67 72 61 6d 20 6d 75 73  This program mus
00000000`00400060  74 20 62 65 20 72 75 6e-20 75 6e 64 65 72 20 57  t be run under W
00000000`00400070  69 6e 33 32 0d 0a 24 37-00 00 00 00 00 00 00 00  in32..$7........

1: kd> db 0x400fa0
00000000`00400fa0  00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00  ................
00000000`00400fb0  00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00  ................
00000000`00400fc0  00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00  ................
00000000`00400fd0  00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00  ................
00000000`00400fe0  00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00  ................
00000000`00400ff0  00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00  ................
00000000`00401000  ?? ?? ?? ?? ?? ?? ?? ??-?? ?? ?? ?? ?? ?? ?? ??  ????????????????
00000000`00401010  ?? ?? ?? ?? ?? ?? ?? ??-?? ?? ?? ?? ?? ?? ?? ??  ????????????????
```

**Comment by johnstep** [comment]
That inaccessible memory above is not the issue. The same memory is inaccessible at this point in the success case as well. The difference is, when `nt!LdrpResGetResourceDirectory+0x315` executes above, in the success case, the memory is paged in, while in the failure case, an access violation occurs.

**Comment by waynesi** [comment]
Hi John,

Thanks a lot for investigating this issue. I hope you felt lots of fun when debugging this ancient tool which we unfortunately still rely on for our development.

Just a side note which I'm not sure if it's helpful. I used the exact same Dockerfile to build the image last July for the first time; of course based on the version of the Windows Server Core image available at that time. The image worked just fine. So, maybe the issue was introduced somewhere in the docker, the file filter, or the Windows Server?

**Comment by waynesi** [comment]
Hi John,

Sorry for disturbing you. Is there any update on your investigation if I may ask please? Thanks.

**Comment by thaJeztah** [comment]
@johnstep ^^

**Comment by johnstep** [comment]
Apologies for the long delay. Microsoft confirmed this is a Windows bug that is fixed in Windows Server 2019 and Windows 10 October 2018 Update. Unfortunately I have been unable to determine if and when this fix will be ported to prior affected versions of Window. I will reach out again, and let you know if I receive any more information that I can share. Thanks.

**Comment by waynesi** [comment]
Thanks you very much @johnstep for the update. I understand it's beyond the scope/responsibility of docker4win, and we greatly appreciate your effort of going extra mile to help us. Thanks.

**Comment by johnstep** [comment]
@waynesi Are you okay waiting for the Windows 10 update, currently delayed, but originally scheduled for October? Are you running this on Window Server also, or only on Windows 10?

**Comment by AnaghHegde** [comment]
> Apologies for the long delay. Microsoft confirmed this is a Windows bug that is fixed in Windows Server 2019 and Windows 10 October 2018 Update. Unfortunately I have been unable to determine if and when this fix will be ported to prior affected versions of Window. I will reach out again, and let you know if I receive any more information that I can share. Thanks.

@johnstep  Any updates on this ? I am facing this issue with Docker Desktop in windows 10.

**Comment by waynesi** [comment]
Hi @AnaghHegde,

Thanks a lot for your comments. It's okay. We've rebuilt our envionement with updated Windows Server docker images from MS earlier this year and it was working. So the bug has been fixed in their images. Although we can't pin down exactly when, it's no more a concern to us. 

I greatly appreciate all the effort your team has put into resolving this issue. Thanks a lot.
