### ISSUE TITLE
Docker unable to start on Windows 10

### ISSUE THREAD

**Issue by Getitdan** [docker/for-win#2210]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C345D429-0AF6-4E57-94DB-8A99E4B6BF7F/2018-07-16_14-48-06

### Expected behavior
Docker should run on windows 10.

### Actual behavior
Docker does not start.

### Information

  - Windows Version: 10
  - Docker for Windows Version: 18.03.1-ce-win65 (17513)
  - I have a new Windows 10 pro (upgraded from Windows 7).
After a fresh installation of Docker for Windows, I am getting the error:
![screenshot_1095](https://user-images.githubusercontent.com/11067170/42756934-cf0ff03e-8906-11e8-8161-13577c6f6f0f.jpg)
The text in the error above:
 > Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID 1D60AE71-F625-4A14-95D6-264618532954)
> at Start-MobyLinuxVM, <No file>: line 300
> at <ScriptBlock>, <No file>: line 395
>    at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
>    at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 67
>    at Docker.Actions.<>c__DisplayClass14_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 51
>    at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

Also, the log.txt file includes the following errors:

 > ...
> [14:12:09.685][Moby           ][Error  ] Failed to read Moby's logs: The operation has timed out.
> ...
> [14:12:13.257][VpnKit         ][Error  ] vpnkit.exe: While watching /etc/resolv.conf: ENOENT
> ...
> [14:12:45.643][Linux          ][Error  ] Failed to start: Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID D4AE07B1-7A05-439E-A17D-F6572AE861DF)
> at Start-MobyLinuxVM, <No file>: line 300
> at <ScriptBlock>, <No file>: line 395. Let's retry

**What have I tried**
This happens all over again (even after a full uninstalling & installing).
The docker icon in tray is red. I tried the following command (as suggested by: https://github.com/docker/for-win/issues/587): 
`netsh interface ipv4 set address name="vEthernet (DockerNAT)" static 10.0.75.1 255.255.255.0
`
This made docker tray icon to go white ("Docker is running" status), instead of red, pretending to work. But... now, running "docker ps" results in the following error:

> error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.37/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

I tried running: "netcfg -d", as suggested by https://github.com/docker/for-win/issues/748. But this didn't solve the issue.

I have also tried to disable hyper-v, and let docker to start it. Still didn't work.

This is really frustrating, as I cannot use Docker at all.
I made an upgrade to my Windows, from 7 to 10, only to get Docker running.
But all I'm getting are problems. Why isn't the normal installation simply work?
Thanks!

### Steps to reproduce the behavior

  1. Just try to install docker on Windows 10 (potentially to occur on an upgraded Windows 7).

**Comment by bogere** [comment]
I was also struggling to start docker after installation... 
You should try installing the window Updates. the latest before you start running your docker.
I did this and it worked perfectly. now iam able to run the docker commands . try that first

**Comment by Getitdan** [comment]
@bogere Thanks for your input. My Windows is already fully updated:
![screenshot_1094](https://user-images.githubusercontent.com/11067170/42756882-9f68025e-8906-11e8-8421-dfdd8661660c.jpg)

I'll add only errors from log.txt file of docker:
`...
[14:12:09.685][Moby           ][Error  ] Failed to read Moby's logs: The operation has timed out.
...
[14:12:13.257][VpnKit         ][Error  ] vpnkit.exe: While watching /etc/resolv.conf: ENOENT
...
[14:12:45.643][Linux          ][Error  ] Failed to start: Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID D4AE07B1-7A05-439E-A17D-F6572AE861DF)
at Start-MobyLinuxVM, <No file>: line 300
at <ScriptBlock>, <No file>: line 395. Let's retry`

And the notorious error:
![screenshot_1095](https://user-images.githubusercontent.com/11067170/42756934-cf0ff03e-8906-11e8-8161-13577c6f6f0f.jpg)

I did nothing wrong, and docker won't work. Please help me.

**Comment by rn** [comment]
@Getitdan do you run any AV software by any chance? Have you tried a factory reset?

**Comment by Getitdan** [comment]
@rn I have Nod32 Antivirus. I have just disabled it, and reinstalled docker. Still, the same problem occurs. I have just upgraded my Windows 7 to Windows 10. Do you have any other suggestion, or should I format my whole pc? Thanks a lot for your response! It's really important for me.

**Comment by Getitdan** [comment]
Update: 
I've tried this command:
`docker-machine create default`
and got:
`Running pre-create checks...
Error with pre-create check: "This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)"`

**Comment by Getitdan** [comment]
@rn Thanks, I formatted my whole Windows, and now it works.
