### ISSUE TITLE
Cannot switch to Linux Containers - no memory

### ISSUE THREAD

**Issue by CaroRob** [docker/for-win#2217]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:5A42AD7F-17C6-4E81-83D0-6D95C3FFC1AD/2018-07-17_02-51-35

### Expected behavior
Ability to switch to Linux container so I can install docassemble
### Actual behavior
docker whale turns red and I get a message "Not enough memory, free up memory or change settings."

### Information
I checked documentation and troubleshoot,
I have done everything I understand how to do on my machine,
Enable virtualization in the BIOS
I keep changing the memory setting in MobyLinux Hyper-VM - it doesn't stick
I turn off everything possible to free up memory - no dropbox, no google drive, no McAfee, no Word, no chrome, 
I need linux containers to work so I can run [docassemble.](https://docassemble.org/docs/installation.html#tocAnchor-1-1)
I have not reset Docker to original factory defaults - as it was when first installed, cause I think it is still as it was.
Please, help us understand the problem.  For instance:
  - Is it reproducible? - Yes every time I try to switch I get the same problem, have restarted machine mulitple times.
  - Is the problem new? I am new to Docker, only reason I installed is so I can run Docassemble
  - Did the problem appear with an update? - N/A

  - Windows Version: Windows 10 Pro 
  - Docker for Windows Version: Version 18.03.1-ce-win65 (17513)

### Steps to reproduce the behavior
  1. When I first start my laptop, as it is warming up Docker says it is not running, do I want to start and can it start in ex....- can't remember the word. I say OK and OK again when Windows asks if it's ok for Docker to make changes on the machine
  2. I ask to switch to Linux containers
  3. I get the error and red whale out of memory

Copied log file into issue - GitHub error: body too long
Selected log file to attach (log.txt) - GitHub error: We don't support that file type. Try again with a GIF, JPEG.......**TXT**.... or ZIP. 
WTF?
Have renamed log file with extension .TXT
[log.TXT](https://github.com/docker/for-win/files/2200712/log.TXT)

**Comment by jhpyle** [comment]
How much memory does your Windows 10 machine have?

**Comment by CaroRob** [comment]
Installed memory (RAM): 4.00 GB (3.71 GB usable)

**Comment by CaroRob** [comment]
sorry clicked wrong button.

**Comment by jhpyle** [comment]
I'm not an expert on Docker for Windows, but I have used it on Windows 10 (on a machine with 8 GB of RAM) and it hasn't given me any problems.

You could try the advice on [this stackoverflow topic](https://stackoverflow.com/questions/43170089/docker-wont-start-on-windows-not-enough-memory-to-start-docker) if you haven't already.

Docassemble itself requires at least 2GB of memory to be allocated to it, so if and when you get Docker up and running, go to Settings -> Advanced and make sure the memory is set to at least 2048MB.

I have never tried Docker for Windows on a machine with 4GB of RAM, so it is possible that 4GB is not enough; I don't know.

**Comment by CaroRob** [comment]
Thanks @jhpyle,
Yes, I tried everything in that post - except downgrading Docker version which was the last suggestion. Somehow I doubt that will be the solution, given other posts that suggest we use the latest greatest version if having the out of memory issue.

**Comment by jhpyle** [comment]
I'm using the latest version of Docker for Windows and it doesn't give me any memory errors.

I've never had to do the "switch" operation between Windows containers and Linux containers; it has always been set to Linux containers. 

As I said, I am not an expert, but two ideas that you could try if you haven't already: 1) Settings -> Reset -> Reset to factory defaults; 2) Uninstall the whole application, reboot, run Windows Update, then reinstall Docker.

Also, if Windows 10 Docker doesn't work out, you could go on DigitalOcean or Amazon Web Services and create a Linux VM there, and SSH to it.

**Comment by CaroRob** [comment]
Thanks Jonathan for such persistent help.
Already tried 1) Reset to factory defaults.
Haven't yet Tried uninstalling and reinstalling because... time.

However, my workstudy student has set up both development and production servers for us on DigitalOcean and I am learning docassemble on the development server fingers crossed I don't bring the whole thing tumbling down - as warned in your docassemble documentation. ;)

**Comment by preshi** [comment]
Hi CaroRob. I am also facing the same issue. Please share the troubleshooting steps if you are able to resolve the issue.

**Comment by CaroRob** [comment]
Never resolved. but reformatting computer over next 3 weeks - Hoping in
October if I try again it will work.

Good Luck - to all of us!

Caroline


Caroline Robinson
Codirector, Massachusetts Legal Aid Websites Project
Editor, MassLegalHelp.org <http://www.masslegalhelp.org/>
(857) 267-3171 8am-3pm M-F

--One should aim not at being possible to understand, but at being
impossible to misunderstand.
*Quintilian*

* <http://goog_711619766>*

* <http://twitter.com/masslegalhelp>*

* <http://twitter.com/masslegalhelp>*

*Join us for MLRI's 50th anniversary celebration
<https://connect.clickandpledge.com/w/Form/9aafdc5e-e76a-4fde-9e57-8d209c3f7586>
on September
26th!*

* <http://twitter.com/masslegalhelp>*

**Comment by jhpyle** [comment]
Hi @preshi -- if you are trying to get docassemble to work, I would recommend not spending very much time trying to get it to run inside Docker for Windows.  Docassemble is a server application and there are a lot of dangers with unsafe shutdowns if you run it in a desktop environment.  If you have a HyperV server, I would recommend making a Linux VM on it and then installing Docker on the Linux VM.  Or you could use a service like Docassemble Toolkit, or run Docker from a Linux VM on AWS/Azure/Digital Ocean/etc.
