### ISSUE TITLE
docker nodejs not working on windows 8.1

### ISSUE THREAD

**Issue by matt212** [docker/for-win#2224]
Hi,
I followed below docker +nodejs configuration
https://nodejs.org/en/docs/guides/nodejs-docker-webapp/
and please find below screen shot for the same.
however the installation and creation of container was successfully, I was unable to see local or webserver serving through docker
Please find below attached screenshot for the same .
![1](https://user-images.githubusercontent.com/1698139/42891173-50f37e1a-8acc-11e8-9b1f-3a732c1dff7e.png)
![2](https://user-images.githubusercontent.com/1698139/42891856-f7fc5d20-8acd-11e8-9fcf-bf614b0dd0ab.png)

![3](https://user-images.githubusercontent.com/1698139/42891175-514a0d20-8acc-11e8-9b74-fd4ac6f32338.png)
![4](https://user-images.githubusercontent.com/1698139/42891176-517183a0-8acc-11e8-9397-41f0e56ccb8e.png)

**Comment by LoreenRH** [comment]
Hello!
I believe you're using Docker Toolbox. This issue tracker is for Docker for Windows (Desktop) which is currently supported only on Windows 10. Can open your issue in the Docker Toolbox [issue tracker](https://github.com/docker/toolbox/issues) instead?
