### ISSUE TITLE
gcr.io/android-battery-historian:2.1 not found

### ISSUE THREAD

**Issue by mobilegmg** [docker/for-win#2226]
With reference to steps provided here: https://developer.android.com/studio/profile/battery-historian

I am getting below response
<img width="520" alt="12" src="https://user-images.githubusercontent.com/12729371/42935388-25f2b91a-8b67-11e8-9318-eb39df5e6336.png">
<img width="265" alt="11" src="https://user-images.githubusercontent.com/12729371/42935389-2637e350-8b67-11e8-9eb7-050dc086e3cd.png">

: 

Please help me ASAP.

**Information**
Windows Version: Windows 10 Enterprise
Docker for Windows Version: 18.03.1-ce

**Steps to reproduce the behavior**
Install docker edge on windows
start docker and it will fail to load image

**Comment by LoreenRH** [comment]
Hello,
This is not an issue of Docker itself, it's that the image gcr.io/android-battery-historian:2.1 has been removed, or updated. Refer to battery-historian issue tracker for this.
