### ISSUE TITLE
Docker not resolving the host name while executing the docker run

### ISSUE THREAD

**Issue by KrishnaPrasadVV** [docker/for-win#2227]
I am trying to create a VSTS build agent docker image.
I have pulled the microsoft/vsts-agent , and executing 'docker run' and passing the argument, but it throws an error,
 "curl: (6) Could not resolve host: cargill-sandbox.visualstudio.com"

**Comment by KrishnaPrasadVV** [comment]
I am trying to create a VSTS build agent docker image.
I have pulled the microsoft/vsts-agent , and executing 'docker run' and passing the argument, but it throws an error,
"curl: (6) Could not resolve host: cargill-sandbox.visualstudio.com"

please, Could anyone help me on this ?

**Comment by cjw296** [comment]
This sounds like #2301, can you try downgrading to 18.03?
