### ISSUE TITLE
Client certificates not being copied into MobyLinux VM

### ISSUE THREAD

**Issue by selverob** [docker/for-win#2231]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 93510656-47C6-4D43-ADFA-909F91CB23A7/2018-07-20_08-57-34

### Expected behavior
After copying my client SSL certificates into directories listed in Docker for Windows documentation, I should be able to log in to the Docker registry which requires them.

### Actual behavior
Executing `docker login <private_registry_url>` and inserting correct credentials gives me:
```
Error response from daemon: Get https://<private_registry_url>/v2/: remote error: tls: bad certificate
```

### Information
It seems the problem is in the code that's responsible for copying certificates into the Linux VM after starting it. If I get into the VM's filesystem and manually copy the certificates into `/etc/docker/certs.d/<private registry URL>`, everything works, until the next VM restart.

  - Windows Version: 1709, Build 16299.547
  - Docker for Windows Version: 18.03.1-ce-win65 (17513)

### Steps to reproduce the behavior
1. Either:
a) Copy the client certificates into `C:/ProgramData/Docker/certs.d/<private_registry_url>/`, or
b) Copy the client certificates in C:/Users/.../.docker/certs.d/<private_registry_url>/
2. Import the root certificate into Windows "Trusted Root Certification Authorities" (otherwise you'd get "X509: certificate signed by unknown authority")
3. Run `docker login <private_registry_url>`

**Comment by pmtslgit** [comment]
Same problem on 18.06.0-ce-win72 (19098)

If anyone knows how to force a manual copy on VM start as a workaround, I'm all ears.

As it stands now I have to manually copy the cert files over each time the VM restarts.

**Comment by moerketh** [comment]
We created a workaround to copy all docker certificates from all users to the moby vm each time the vm is started.

**Assumptions:** 
- Your certificates are in %USERPROFILE%\.docker\certs.d
- Docker client is located at "C:\Program Files\Docker\Docker\resources\bin\docker.exe"
- A log file can be created at "C:\Program Files\Docker\certinstall.log"

**How it works:**
A powershell background task is created that starts trying to connect to docker
When the connection is succesful all docker certificates from all users are copied to the mobyvm in the default /etc/docker/certs.d using a default Ubuntu container for the copy.

**How to install:**
Copy the following code at the end of the Start-MobyLinuxVM function in the MobyLinux.ps1 from your docker installation folder:
    Start-Job -ScriptBlock 
    {        
        Start-Transcript -Path "C:\Program Files\Docker\certinstall.log"
        [bool]$running = $false;
        write-host "start installing certificates"
        $dockerclient = "C:\Program Files\Docker\Docker\resources\bin\docker.exe"
        while(-not $running)
        {
            try
            {
                write-host "Waiting for docker to become available..."
                &$dockerclient ps
                if($LASTEXITCODE -eq 0)
                {
                    $running = $true
                }
                Start-Sleep -Seconds 10
            }
            catch
            {
                write-host "Caught exception $_ , waiting for docker to become available..."
                Start-Sleep -Seconds 10
            }
        }
        
        &$dockerclient run --name certinstaller --privileged --rm -v /:/host -dit ubuntu
        foreach ($d in Get-ChildItem "c:\users")
        {
            write-host "installing certificates from $d"
            &$dockerclient cp (Join-Path $d.FullName -ChildPath ".docker/certs.d") certinstaller:/host/etc/docker/certs.d
        }
        &$dockerclient stop certinstaller
        write-host "install certificates: Done"
        Stop-Transcript
    }

**Comment by siziyman** [comment]
Can confirm, same behavior is still present on 18.06

**Comment by corelgott** [comment]
Since we are on a windows system: How to add the certs for "localhost:5000" since windows won't allow a colon within the folder path. Is there some way to encode / escape it?

**Comment by martijndebruijn** [comment]
Please fix. The workaround did the job.

**Comment by Wauna** [comment]
It would appear I'm "special".  I cannot seem to get the workaround to work.  The file my network admin gave me is a '.cer' file.  I located the ".docker" folder in my C:\Users directory.  There was no "certs" anything.  I know very little here and don't know if "certs.d" is a file or a folder.  I found some info on google that suggested it was supposed to be a folder, but I don't know what it would look like inside the folder. 

Can someone elaborate on how to assemble the .docker directory correctly?   

I instrumented the powershell script to make I could confirm it was trying to run.  I'm hitting this line, but I cannot find any details on certinstaller.  

 &$dockerclient cp (Join-Path $d.FullName -ChildPath ".docker/certs.d") certinstaller:/host/etc/docker/certs.d

Any assistance is deeply appreciated.  3 days and counting... 

Thanks

**Comment by annam002** [comment]
I also could not get the script to copy the certificates; would really appreciate if it would get fixed. 
My workaround is to copy the certificates manually like this:
1. Log into docker vm:
`docker run --net=host --ipc=host --uts=host --pid=host -it --security-opt=seccomp=unconfined --privileged --rm -v /:/host alpine /bin/sh`

2. Copy (assuming you have mounted the directory where the certificates are stored)
```
mkdir certs.d
cd certs.d
mkdir <registry-name>
cd <registry-name>
cp ../../../../host_mnt/<path-to-directory>/client.* .
```

**Comment by andreynorin** [comment]
> I also could not get the script to copy the certificates; would really appreciate if it would get fixed.
> My workaround is to copy the certificates manually like this:
> 
> 1. Log into docker vm:
>    `docker run --net=host --ipc=host --uts=host --pid=host -it --security-opt=seccomp=unconfined --privileged --rm -v /:/host alpine /bin/sh`
> 2. Copy (assuming you have mounted the directory where the certificates are stored)
> 
> ```
> mkdir certs.d
> cd certs.d
> mkdir <registry-name>
> cd <registry-name>
> cp ../../../../host_mnt/<path-to-directory>/client.* .
> ```

I am able to login to MobyLinuxVM, mount my volume, create the file system structure, and copy the certs to it.

However, as soon as I disconnect from the bash session, those changes  are erased. 
Any idea how to make my changes persist?

**Comment by Anayoo** [comment]
> > I also could not get the script to copy the certificates; would really appreciate if it would get fixed.
> > My workaround is to copy the certificates manually like this:
> > 
> > 1. Log into docker vm:
> >    `docker run --net=host --ipc=host --uts=host --pid=host -it --security-opt=seccomp=unconfined --privileged --rm -v /:/host alpine /bin/sh`
> > 2. Copy (assuming you have mounted the directory where the certificates are stored)
> > 
> > ```
> > mkdir certs.d
> > cd certs.d
> > mkdir <registry-name>
> > cd <registry-name>
> > cp ../../../../host_mnt/<path-to-directory>/client.* .
> > ```
> 
> I am able to login to MobyLinuxVM, mount my volume, create the file system structure, and copy the certs to it.
> 
> However, as soon as I disconnect from the bash session, those changes are erased.
> Any idea how to make my changes persist?

I put my certificates in C:\ProgramData\docker\certs.d 
and use code:
`docker run --rm -d -v /:/host -v C:\ProgramData\docker\certs.d:/certs.d alpine cp -r /certs.d /host/etc/docker/certs.d`

**Comment by annam002** [comment]
Will this ever be fixed?

**Comment by martijndebruijn** [comment]
Please fix. After each update I have to fix this manually!

**Comment by af6140** [comment]
This is really important in an enterprise environment.

**Comment by martijndebruijn** [comment]
When will this issue be fixed? Every update causes manual work.

**Comment by hitslab** [comment]
Please fix

**Comment by kadarsys** [comment]
Please make it possible to add user certificates via the graphical interface.

**Comment by geo-aoe** [comment]
Please fix

**Comment by kadarsys** [comment]
Please fix

**Comment by elfilalime** [comment]
Please fix

**Comment by szbenceg** [comment]
> Please fix. After each update I have to fix this manually!

Sorry for bothering, but how can you fix it? The workaround mentions a file MobyLinux.ps1, but that has been removed. Thanks in advance for your answer.

**Comment by brianehlert** [comment]
How can this still be an issue??
There is more to life than a repo that does basic auth.
