### ISSUE TITLE
Build args not registered in RUN commands for Windows Containers

### ISSUE THREAD

**Issue by zckeyser** [docker/for-win#2232]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F7B03F0D-115B-41B2-9DD0-2E715AE3FFCA/2018-07-20_13-17-44

### Expected behavior
Sample Dockerfile
```
FROM microsoft/aspnet:windowsservercore-10.0.14393.693
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ARG some_path

# show that the arg works in COPY
COPY $some_path C:\test
RUN ls C:\test

# but the arg doesn't work in RUN
RUN Write-Host $some_path
```

Run using the command `docker build . -t sanity --build-arg some_path=foo/ --no-cache`.

The Write-Host should print the passed value of foo.
### Actual behavior
The output is below. Instead of printing foo, an empty line is printed, implying that the build arg was not registered. However, in the COPY call, the build arg works correctly.

```
PS C:\Users\ckeyser\source\repos\ConfigurationWebService\sanity-test> docker build . -t sanity --build-arg some_path=foo/ --no-cache
Sending build context to Docker daemon  3.072kB
Step 1/6 : FROM microsoft/aspnet:windowsservercore-10.0.14393.693
 ---> e761eca2f8df
Step 2/6 : SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
 ---> Running in c36d8631577d
Removing intermediate container c36d8631577d
 ---> 7860b8ed162d
Step 3/6 : ARG some_path
 ---> Running in 64b176b840cf
Removing intermediate container 64b176b840cf
 ---> cee6ac273aae
Step 4/6 : COPY $some_path test
 ---> 6e0d44266c1d
Step 5/6 : RUN ls test
 ---> Running in 216b5f61e388


    Directory: C:\test


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        7/20/2018   1:05 PM              0 testfile


Removing intermediate container 216b5f61e388
 ---> 369f6f223a89
Step 6/6 : RUN Write-Host $some_path
 ---> Running in 242094c26d55

Removing intermediate container 242094c26d55
 ---> 28626149f5d5
Successfully built 28626149f5d5
Successfully tagged sanity:latest
```
### Information
Tested on Windows 10 Professional, Version	10.0.17134 Build 17134 using Hyper-V, on an HP Elitebook.
Docker version 18.03.1-ce, build 9ee9f40

The problem is reproducible. To reproduce, take the dockerfile above, and run using the command above (`docker build . -t sanity --build-arg some_path=foo/ --no-cache`).

### Steps to reproduce the behavior

  1. Use the dockerfile below:
```
FROM microsoft/aspnet:windowsservercore-10.0.14393.693
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ARG some_path

# show that the arg works in COPY
COPY $some_path C:\test
RUN ls C:\test

# but the arg doesn't work in RUN
RUN Write-Host $some_path
```
  2. Build using `docker build . -t sanity --build-arg some_path=foo/ --no-cache`
  3. Verify that the Write-Host call didn't print anything.

**Comment by pbering** [comment]
As far as I know ARG and ENV variables are both only available as Windows environment variables, so from PowerShell you should use `Write-Host $env:some_path)`.

**Comment by zckeyser** [comment]
Looks like you're right -- is this documented somewhere that I missed?
