### ISSUE TITLE
install problem with docker edge 18.06

### ISSUE THREAD

**Issue by mohanramanujam** [docker/for-win#2233]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by gtardif** [comment]
Please provide diagnostic ID after uploading diagnostics, we can't investigate without the diagnostic ID
