### ISSUE TITLE
Windows 10 Pro clean installation.  Fully updated. Docker fails to start

### ISSUE THREAD

**Issue by kwmaharaj** [docker/for-win#2234]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker should start. 

### Actual behavior
Error is thrown. Unable to run docker commands such as docker ps. The HyperV vm docker creates for linux containers fails to start.

### Information
  - Is it reproducible? Yes
  - Is the problem new? I dont know, I am a first time user.
  - Did the problem appear with an update? Windows was installed and updated, then docker installed.

  - Windows Version: Windows 10 Pro Build: 17134
  - Docker for Windows Version: Version 18.03.1-ce-win65 (17513), Channel: stable, 93354b3

### Steps to reproduce the behavior
1. Performed clean installation of windows 10 PRO in a VirtualBox VM.  
2. Then fully updated because Docker wouldn't install on the build of Windows 10 PRO i had.  Updating windows is the suggested fix for that.
3. Once updates completed, docker was then installed, using linux containers.(I suspect this is the issue.  Docker might be creating it incorrectly?)
4. After install, it prompts to enable hyper v, OK is selected and it installs hyper v, windows restarts.
5. Docker fails to start when logging in.

### Log file
[log.txt](https://github.com/docker/for-win/files/2216013/log.txt)

### Error
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start.

Failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running.

'MobyLinuxVM' failed to start. (Virtual machine ID 2B11B17F-84C2-4D44-94DA-B6BF10DD5327)

The Virtual Machine Management Service failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running (Virtual machine ID 2B11B17F-84C2-4D44-94DA-B6BF10DD5327).
at Start-MobyLinuxVM, <No file>: line 300
at <ScriptBlock>, <No file>: line 395
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.<>c__DisplayClass23_0.<SwitchDaemon>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 264
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by rn** [comment]
I see errors like:
```
[10:23:30.032][WindowsDaemon  ][Error  ] Acquisition of End User License failed. hr=0xC004C003
Sku Id=4de7cb65-cdf1-4de9-8ae8-e3cce27b9f2c
```
and
```
[10:23:33.856][WindowsDaemon  ][Error  ] License Activation (slui.exe) failed with the following error code:
hr=0xC004C003
Command-line arguments:
RuleId=31e71c49-8da7-4a2f-ad92-45d98a1c79ba;Action=AutoActivate;AppId=55c92734-d682-4d71-983e-d6ec3f16059f;SkuId=4de7cb65-cdf1-4de9-8ae8-e3cce27b9f2c;NotificationInterval=1440;Trigger=NetworkAvailable
```

In your logs. I have no idea what these mean, but it looks like and issue with your windows installation

**Comment by kwmaharaj** [comment]
Thank you for the response.

If i switch to windows containers, so I right click on the whale and select switch to windows containers it works. 
Attempt to go back to linux fails.
