### ISSUE TITLE
Docker For Windows Crashes Enabling Hyper-V etc

### ISSUE THREAD

**Issue by garygsscott** [docker/for-win#2240]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 196A41C1-7392-4CFD-9C75-6F9ECE06ACEF/20180723140950

### Expected behavior
Features like Hyper-V are attempted be enabled in order to use Docker for Windows.    I expect this to be completed and allowed to reboot.

### Actual behavior
Application crashes will trying to enable Hyper-V

### Information

  - Windows Version: 10 171314.167
  - Docker for Windows Version: 18.6.0.18994

### Steps to reproduce the behavior

  1. … Install Docker For Windows 18.6.0.18994
  2. … When prompted to enable Hyper-V say yes and accept reboot.    Error is shown pre-reboot.

**Comment by garygsscott** [comment]
Can this please be re-opened and investigated please?    This was a confirmed issue, diagnostics were provided yet no-one was assigned to investigate and resolve the issue?   Many thanks.

**Comment by davl3232** [comment]
I have the same issue.
Every time docker launches since the first time I installed it a month ago, on my Windows 10 machine, it crashes.

**Comment by radub** [comment]
Please reopen the issue. My Win10 machined crashed. Same as @garygsscott.
