### ISSUE TITLE
LCOW: Invalid Platform OS "linux"

### ISSUE THREAD

**Issue by necroTaxonomist** [docker/for-win#2241]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 3ED176A3-2D7C-42BE-B181-E05843FEA108/2018-07-23_14-05-48

### Expected behavior
Build a Linux image for CentOS 6.8 while using Windows containers

### Actual behavior
Unable to pull the image or build.
Returns an error saying:
> Error response from daemon: invalid platform: invalid platform os "linux"

### Information

  - Windows Version: Windows 10 Enterprise Version 10.0.14393 Build 14393
  - Docker for Windows Version: Version 18.03.0-ce-win59 (16762)

I'm working on a project that requires running both Linux containers and Windows containers at the same time. I'm not using the most recent version of Docker in this channel, because that version crashes whenever I switch to Windows containers (#1898).

### Steps to reproduce the behavior

  1. Start Docker for Windows
  2. Switch to using Windows containers
  3. Enable Experimental features in the Docker settings
  4. In command line, run `docker pull --platform=linux centos:6.8`

**Comment by necroTaxonomist** [comment]
Downloaded 18.03.0-ce-win59 and now I just get an "unsupported os linux"

Has the experimental feature been removed?

**Comment by ebriney** [comment]
Hi @necroTaxonomist. Yes, you have to enable experimental in the daemon settings. We disabled it because if you pull an lcow image and disable experimental, it bricks your windows daemon...

**Comment by necroTaxonomist** [comment]
No, I don't see that option. Is that something separate I need to turn on?

**Comment by ebriney** [comment]
Can you dump your `docker info`?
Have you switch on windows containers? `--platform=linux` is only valid with windows daemon.

**Comment by necroTaxonomist** [comment]
```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 13
Server Version: 18.06.0-ce
Storage Driver: windowsfilter
 Windows: 
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 14393 (14393.2368.amd64fre.rs1_release_inmarket_aim.180712-1833)
Operating System: Windows 10 Enterprise Version 1607 (OS Build 14393.2368)
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 7.922GiB
Name: 327-Z240-3
ID: GODZ:GMRK:27BA:RMEU:HQFH:YDRD:73UM:H7VO:CIJF:LRXS:6F34:WT4I
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 46
 System Time: 2018-07-27T10:38:06.1273738-04:00
 EventsListeners: 2
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by ebriney** [comment]
Oh, lcow is supported on Windows RS3 (16299) and above only.

**Comment by necroTaxonomist** [comment]
Oh, thanks. Good to know I guess.

**Comment by chanseokoh** [comment]
@ebriney I'm seeing the same error.

> Oh, lcow is supported on Windows RS3 (16299) and above only.

I don't get what the number 16299 means. Below is my system. Does it not support `--platform linux` either?

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 18.03.1-ce
Storage Driver: windowsfilter
 Windows: 
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.2430.amd64fre.rs1_release_inmarket_aim.180806-1810)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 15GiB
Name: kokoro-winserver2016-v1
ID: XHOF:TYNO:OL2D:YS5E:J63Z:FMMU:3ZDS:BHTX:BXAB:25MB:FGN4:MQHR
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by chanseokoh** [comment]
Oh, BTW, I am trying `docker pull --platform linux registry:2` on Windows.

**Comment by mat007** [comment]
@chanseokoh 16299 is the build number of your Windows system, here yours is
```
Kernel Version: 10.0 14393 (14393.2430.amd64fre.rs1_release_inmarket_aim.180806-1810)
```
i.e. 14393

**Comment by mpathfinder** [comment]
Hi
Mine is as below but the same issue :
Is there any solution?
```
Client:
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.2.2-10-g3f18b65-tp-docker)
  app: Docker Application (Docker Inc., v0.8.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 19.03.1
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics l2bridge l2tunnel nat null overlay transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 16299 (16299.637.amd64fre.rs3_release_svc.180808-1748)
 Operating System: Windows 10 Enterprise Version 1709 (OS Build 16299.1331)
 OSType: windows
 Architecture: x86_64
 CPUs: 4
 Total Memory: 11.9GiB
 Name: Armandi-PC
 ID: EVS4:CARH:QOOA:OQ2T:TT2R:4DLH:CIIQ:ZMHL:DJGB:GQMG:K3YA:JH3T
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 30
  System Time: 2019-08-26T19:36:51.197303+04:30
  EventsListeners: 2
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by cowlinator** [comment]
I am also getting this error with
`Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)`

**Comment by cowlinator** [comment]
> Oh, lcow is supported on Windows RS3 (16299) and above only.
@ebriney
Can you reconfirm that  lcow is supported on Windows RS3 (16299) and above, and that `docker pull --platform=linux` is expected to work on Windows 10 v17134?
If so, this is a bug.

**Comment by ebriney** [comment]
From 19.03:
https://github.com/moby/moby/pull/39108
So if you need LCOW on RS3 we must use older versions (18.09 and older).
