### ISSUE TITLE
Daemon issue

### ISSUE THREAD

**Issue by 68muscle** [docker/for-win#2245]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 05332516-4A5F-4425-8655-C16C70B6644B/2018-07-24_12-43-20

### Actual behavior

I can't get past this error: Error response from daemon: Get https://registry-1.docker.io/v2/: unexpected EOF.

### Information

  - Windows Version: 10
  - Docker for Windows Version: 18.03.1-ce, build 9ee9f40

### Steps to reproduce the behavior

  1. Open a command Window.
  2. Issue docker pull hello-world

**Comment by deanskibum** [comment]
Any Update on this? I'm stuck also
