### ISSUE TITLE
Cannot make dockerd for Windows 1.12.3-beta30 listen to tcp://0.0.0.0:2375

### ISSUE THREAD

**Issue by zer0beat** [docker/for-win#225]
_Clone of @lusitania issue opened in https://github.com/docker/docker/issues/28320_

Following the instructions from [Docker ](https://docs.docker.com/engine/reference/commandline/dockerd/#/daemon-configuration-file) and [Microsoft ](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/docker/configure_docker_daemon?f=255&MSPPError=-2147217396#configure-docker-with-configuration-file) I can't start up docker with a changed hosts section of the config.

### Expected behavior
Startup of daemon

### Actual behavior
```
  Error response from daemon: Bad response from Docker engine

   at Docker.Backend.DockerDaemonChecker.Check()
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

### Steps to reproduce the behavior
  1. change Settings->Docker Daemon to
```
{
  "registry-mirrors": [],
  "insecure-registries": [],
  "hosts": [
    "tcp://10.0.75.0:2375",
    "tcp://"
  ]
}
```
  2. try to start
  3. change port 2376, repeat
  4. change IP to 0.0.0.0, try with un-/enc ports
  5. remove remote option and just keep the default for Windows (tcp://)

### Information

  - 5B7AC43B-CA65-42E7-98A8-B482CA7FC66D/2016-11-11_19-55-28 (example above)
  - 5B7AC43B-CA65-42E7-98A8-B482CA7FC66D/2016-11-11_20-03-41 (defaults)
  - Output of `docker version`:
```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      linux/amd64
 Experimental: true
```
  - Output of `docker info`:
```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 6
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 36
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.30-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 735.9 MiB
Name: moby
ID: H7LJ:K7SI:AFW5:3OYN:TCI2:LV5Y:USEZ:NIV4:TUGT:LQJA:U2IV:J2KA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 23
 System Time: 2016-11-11T19:06:03.7319736Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Comment by zer0beat** [comment]
I have tried to follow the same Microsoft steps and I got the same error. Reported error with id: 28F9AE61-5E87-4E83-9D1D-FE3DEEA38C58/2016-11-13_17-00-05

**Comment by dgageot** [comment]
Hi @zer0beat, thanks for your report. Is is the Linux engine or the Windows containers engine that you are trying to make listen on `0.0.0.0`?
 + If it's the **Linux** engine, I'm afraid this won't work and won't be fixed.
 + If it's the **Windows** engine, I'm afraid you can't (as of Beta 31) configure dockerd via the `daemon.json` GUI. It's something we developed already but that's going to ship with beta32.

**Comment by af6140** [comment]
It's the docker daemon itself, can only listen on 127.0.0.1 ip, it cannot be managed by remote tools.

**Comment by friism** [comment]
@af6140 Docker for Windows is currently optimized for local development of Dockerized apps. For that reason, there's no way to expose the Docker Engine on a public interface (which would let anyone on the local network schedule containers on your machine).

If you want to set up Docker host that's available to more people, I can recommend taking a look at [Docker Machine](https://docs.docker.com/machine/).

**Comment by remmeier** [comment]
a lot of tooling makes use of that port on windows due to the historic lack of a pipe. Support for npipe is so far non-existend (like in docker-java). This make the default docker for windows setup fairly unusable in various areas.

**Comment by remmeier** [comment]
could this area be cleanup a bit? also in the documentation? I see things like  "hosts": ["tcp://0.0.0.0:2376", "npipe://"] which are not working (https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/configure-docker-daemon). Having that 2375 port is fairly essential in windows since all the tooling (like docker-java) makes use of it. Support for npipe seems so far mostly non-existend. Which in turn makes the default docker for windows setup unusable.

**Comment by friism** [comment]
@remmeier This issue is about making the Docker API available on a public port. If you have to use software that depends on TCP to interact with Docker, you can still use `localhost:2375`.

If you want to propose changes to Microsoft documentation, it's available here: https://github.com/Microsoft/Virtualization-Documentation/

**Comment by bdellert** [comment]
+1 to come up with some solution here to enable using services like portainer and traefik in Windows containers.  That is, there is currently no way to expose the docker API to services running in containers on the same Windows host, and this is a substantial limitation.

**Comment by vassilvk** [comment]
I think I'm pretty confused regarding the availability of the daemon API endpoint served by **Docker for Windows** (not **Windows Containers**).

My understanding is that in the case of **Docker for Windows** running on a Windows 10 machine, the Docker daemon is running in **MobyLinuxVM** hosted by **Hyper-V**.

If `dockerd` daemon's API cannot be accessed from the outside, but only from within `localhost` (which in this case is **MobyLinuxVM**), then how does the `docker` CLI client running on my Windows host communicate with it? The Windows host is surely an external host to **MobyLinuxVM**.

And since the Windows `docker` CLI client is able to somehow hit the **MobyLinuxVM** `dockerd` daemon on an API endpoint, is there a document which tells us where to point our Windows API clients so they can have similar communication with the **MobyLinuxVM** Docker daemon?

**Comment by vassilvk** [comment]
Ok, I think I understand now [how it works](https://github.com/moby/moby/blob/master/client/client_windows.go) -- somewhat.

The Windows docker CLI client communicates with the **MobyLinuxVM** host through a Windows named pipe `npipe:////./pipe/docker_engine` -- possibly proxied over to **MobyLinuxVM** by `com.docker.proxy.exe`.

However, according to [this document](https://docs.docker.com/docker-for-windows/faqs/#how-do-i-connect-to-the-remote-docker-engine-api), I should be able to connect to `tcp://localhost:2375` on the Windows host, but I am unable to make this work.

After fresh installation of **Docker for Windows 17.03.1-ce** on **Win 10**, there are no Windows host processes listening on TCP port `2375` (`netstat -aon`).

My understanding is that [this is facilitated](http://docker-saigon.github.io/post/Docker-Beta/) by `com.docker.proxy.exe`.
The proxy process is running on my machine, but it does not bind to any of the ports mentioned in the article.

Can anyone confirm if they were able to hit `http://localhost:2375` on their **Windows 10** machines after fresh installation of **Docker for Windows** circa **17.03.1**?
Or at least if they were able to `netstat -aon` and see their Windows hosts listening on TCP port `2375`?

Is there any post-install configuration that needs to be applied to enable TCP Docker API access from within the Windows host to the Docker daemon running on **MobyLinuxVM**  (which itself is hosted by this same Windows host)?

**Comment by af6140** [comment]
It does not work, I think if u use docker machine to create the docker VM, then it can listen on the port.

**Comment by friism** [comment]
> how does the docker CLI client running on my Windows host communicate with it

Docker for Windows runs a proxy on the Windows host that makes Docker available on a named pipe at `//./pipe/docker_engine`. This is the default location of the Docker API on Windows, so no extra configuration is required to use it.

**Comment by friism** [comment]
To use `localhost:2375` in addition to the named pipe, use this checkbox in settings:

![image](https://cloud.githubusercontent.com/assets/126104/26026631/b8c81aae-37b3-11e7-944a-c2ae55db934d.png)

**Comment by vassilvk** [comment]
@friism - perfect, this worked (I can't believe I failed to see that option, doh!)
Thanks much!

**Comment by geminiyellow** [comment]
in  `windows 10 pro insider preview build 17074.rs_prerelease_flt.180116-1539`,
`Expose daemon on tcp ...` not working, when I check it , the docker will crash and cannot restart again.
what can I do?

**Comment by ashishxooa** [comment]
How can I bind this to other interface for eg.  on 0.0.0.0 and not just on localhost?

**Comment by atomaras** [comment]
Keep your dockerd as is i.e listening on localhost and run `netsh interface portproxy add v4tov4 listenport=2375 connectaddress=127.0.0.1 connectport=2375 listenaddress=<public interface ip> protocol=tcp` to proxy from your public interface ip to localhost. Worked like a charm for me.
