### ISSUE TITLE
docker problem in windows

### ISSUE THREAD

**Issue by almagjonaj** [docker/for-win#2252]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by almagjonaj** [comment]
error during connect: Get https://192.168.99.100:2376/v1.38/images/json?filters=%7B%22reference%22%3A%7B%22a%22%3Atrue%7D%7D: dial tcp 192.168.99.100:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by sanjeeva202dc** [comment]
same error for me also, Can some one help here
