### ISSUE TITLE
docker crash report

### ISSUE THREAD

**Issue by isharasjc** [docker/for-win#2254]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by gtardif** [comment]
We can't investigate issues without uploaded diagnostics and a Diagnostic ID in the issue
