### ISSUE TITLE
Unable to start a fresh install of Docker

### ISSUE THREAD

**Issue by amar-r** [docker/for-win#2256]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4D3E960F-E4A0-46C2-A617-E708BA58D4FD/2018-07-25_10-28-32

### Expected behavior
Start Docker
### Actual behavior
Docker stuck in "starting" state
### Information

  - Windows Version: Windows 10 1709
  - Docker for Windows Version: Docker version 17.06.0-ce, build 02c1d87

### Steps to reproduce the behavior

  1. Start docker

**Comment by ebriney** [comment]
Hi @amar-r.  Can you retry with the last version, we fixed an issue yesterday we introduced with a security fix last month.
Close the ticket if it works, thanks.

**Comment by ebriney** [comment]
Oh ok, good to know, perhaps we can detect it and put an appropriate message,
