### ISSUE TITLE
Failed to start: The directory is not empty.

### ISSUE THREAD

**Issue by AnthonyMastrean** [docker/for-win#2258]
- [ x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x ] I have uploaded Diagnostics
  - Diagnostics ID: 01FB1635-7103-47A9-9C4E-ED7FEC1651AC\20180725104147

### Expected behavior

Docker for Windows starts up properly.

### Actual behavior

I get this error message

> The directory is not empty.

### Information

Please, help us understand the problem.  For instance:
  - Is it reproducible? yes
  - Is the problem new? yes (I've seen a lot of errors and I'm only seeing this one after the latest Windows and Docker updates)
  - Did the problem appear with an update? latest
  - Windows Version: Windows 10 Pro 1803
  - Docker for Windows Version: 18.06.0-ce-win69 (19070) edge

### Steps to reproduce the behavior

Start and stop Docker a bunch.

**Comment by bigred8982** [comment]
I also had this problem. I went into the docker settings and did a factory reset. That seems to have fixed the issue for me.
