### ISSUE TITLE
Docker not working when installing first time. Attempts to install containers and crashes with Binary stream '0' does not contain a valid BinaryHeader

### ISSUE THREAD

**Issue by csa0911** [docker/for-win#2262]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID:
401814DA-3D00-4400-A979-74909E263B5B/20180725195957

### Expected behavior
Expected containers to be installed and Docker runs properly
### Actual behavior
Docker crashes
### Information
I installed the latest Stable version of Docker for Windows Community Edition. It installed directly but as soon as I ran 'Docker for Windows' application, it asked me to enable Hyper-V and containers so I clicked OK. However, after clicking OK, I was immediately shown a dialog with this error:

Binary stream '0' does not contain a valid BinaryHeader. Possible causes are invalid stream or object version change between serialization and deserialization.
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.WPF.BackendClient.InstallFeatures(Feature[] features) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:line 111
   at Docker.Notifications.BackendInstallFeatureExceptionReplier.<>c__DisplayClass10_0.<AskToUser>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Notifications\BackendInstallFeatureExceptionReplier.cs:line 103
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

  - Is it reproducible?
100%
  - Is the problem new?
First Install
  - Did the problem appear with an update?
No
  - A reproducible case if this is a bug, Dockerfiles FTW.
-->
  - Windows Version:
Windows 10 Pro Edition
  - Docker for Windows Version:
Version 18.06.0-ce-win70 (19075) Channel: stable
### Steps to reproduce the behavior

  1. Install Docker for Windows community 18.06.0-ce-win70 stable edition
  2. Run the installer
3. Open the application 'Docker for Windows' and Click OK when asked to enable Hyper V and containers
4. Notice crash

![image](https://user-images.githubusercontent.com/157112/43218992-626e939e-9046-11e8-87ad-53e6958f8e30.png)

**Comment by gtardif** [comment]
Thanks for the report, this is a bug in enabling "Hyper-V" or "containers" windows features the first time you run Docker for Desktop, we'll work on a fix for it. 
As a workaround, you can enable "Hyper-V" and "containers" features in "Windows Features" (search for "Turn Windows features on"), that will need a computer restart, then start Docker for Windows

**Comment by ebriney** [comment]
We did an hotfix release on stable yesterday, edge will follow today.
