### ISSUE TITLE
Docker for windows fails to start

### ISSUE THREAD

**Issue by durprasa** [docker/for-win#2263]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID:55445E1F-9760-4C77-8FDA-CC1A79718174/20180725115830

### Expected behavior
expect docker to start

### Actual behavior
Docker for windows fails to start, after update to latest version. 
Restarted the mahchine and docker too, no luck. still docker wont start

### Information

  - Windows Version: 1803 (OS BUild 17134.165)
  - Docker for Windows Version: 18.06.0-ce-win70 (19075)

### Steps to reproduce the behavior

  1. update docker for windows to latest stable release 18.06.0-ce-win70 (19075)
  2. Issue would start to be observed.
  3. restart machine, restart docker, start docker with elevated privileges, same behavior. Docker fails to start

**Comment by EriksonBahr** [comment]
Same issue here. Even restoring the factory defaults won't solve the issue... is there any way to downgrade it??

**Comment by EriksonBahr** [comment]
Hi. I was able to 'solve' it by uninstalling docker (both programs that appears in the installed programs) and then reinstalling using [InstallDocker.msi](https://download.docker.com/win/stable/InstallDocker.msi) from MS.

**Comment by EriksonBahr** [comment]
Solved here... it didn't have anything to do with the upgrade itself. My issue was in the hyper-v networks, where I had to delete (remove-netnat didn't work, I had to delete from the registry - lots of headaches).

After deleting all the hyper-v network then everything was back to normal. 

Hope this helps.

**Comment by MinweiWang** [comment]
Hi EriksonBahr，
I have the same issue after docker upgraded. Could you please explain more detail on how you solve the issue?
Thanks a lot.
Minwei

**Comment by EriksonBahr** [comment]
Hi

As mentioned previously, the upgrade itself didn't have anything to do with the my issues. The real rootcause was some changes I did in my hyper-v adapters to solve some VMs connectivity issues.

If that applies to you, you can follow [this](https://forums.docker.com/t/windows-build-14342-remove-netnat-the-requested-operation-is-not-supported/12749/2), and if you cannot run remove-netnat command, then you should take a look on [this](https://www.thomasmaurer.ch/2016/05/set-up-a-hyper-v-virtual-switch-using-a-nat-network/), see Sebastian's comments.

**Comment by MinweiWang** [comment]
Hi,
It works. 
Thanks！
