### ISSUE TITLE
Hyper-V and Containers features are not enabeld.

### ISSUE THREAD

**Issue by princedeekay** [docker/for-win#2265]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by gtardif** [comment]
Closing as a duplicate of https://github.com/docker/for-win/issues/2262.
As a workaround, you can enable "Hyper-V" and "containers" features in "Windows Features" (search for "Turn Windows features on"), that will need a computer restart, then start Docker for Windows
