### ISSUE TITLE
Unable to run 

### ISSUE THREAD

**Issue by adrianblakey** [docker/for-win#2270]
[log.txt](https://github.com/docker/for-win/files/2232679/log.txt)

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

The hello-world container executes and produces output. See https://hub.docker.com/_/hello-world/

### Actual behavior

PS C:\ProgramData\Docker\config> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All

Path          :
Online        : True
RestartNeeded : False

PS C:\ProgramData\Docker\config> docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
bce2fbc256ea: Pull complete
d4a9b16fd154: Pull complete
5a6000eb1a8c: Extracting [==================================================>]  1.665kB/1.665kB
56d4d021521d: Download complete
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: failed to register layer: re-exec error: exit status 1: output: time="2018-07-25T14:35:11-07:00" level=error msg="hcsshim::ImportLayer failed in Win32: The file cannot be accessed by the system. (0x780) layerId=\\\\?\\C:\\ProgramData\\Docker\\windowsfilter\\cc09b34f9e50bdeaaf4346611aae1a69583c7d1c59a9919dd17da96e911285b8 flavour=1 folder=C:\\ProgramData\\Docker\\tmp\\hcs562452871"
hcsshim::ImportLayer failed in Win32: The file cannot be accessed by the system. (0x780) layerId=\\?\C:\ProgramData\Docker\windowsfilter\cc09b34f9e50bdeaaf4346611aae1a69583c7d1c59a9919dd17da96e911285b8 flavour=1 folder=C:\ProgramData\Docker\tmp\hcs562452871.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
PS C:\ProgramData\Docker\config>

### Information

 - Reproducible: Yes
 - New: No. Same issue with 18.03.
 - Appear with update: No.
  - Windows Version: Windows 10. Version 1703 (OS Build 15063.1155)
  - Docker for Windows Version:

PS C:\ProgramData\Docker\config> docker --version
Docker version 18.06.0-ce, build 0ffa825

PS C:\ProgramData\Docker> docker info                                          
Containers: 2                                                                  
 Running: 0                                                                    
 Paused: 0                                                                     
 Stopped: 2                                                                    
Images: 1                                                                      
Server Version: 18.06.0-ce                                                     
Storage Driver: windowsfilter                                                  
 Windows:                                                                      
Logging Driver: json-file                                                      
Plugins:                                                                       
 Volume: local                                                                 
 Network: ics l2bridge l2tunnel nat null overlay transparent                   
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog          
Swarm: inactive                                                                
Default Isolation: hyperv                                                      
Kernel Version: 10.0 15063 (15063.0.amd64fre.rs2_release.170317-1834)          
Operating System: Windows 10 Enterprise Version 1703 (OS Build 15063.1155)     
OSType: windows                                                                
Architecture: x86_64                                                           
CPUs: 8                                                                        
Total Memory: 15.84GiB                                                         
Name: xxxxxxxxx                                                              
ID: CUVT:46FW:67VG:K6QY:TEFV:RWYA:LJFH:SVX3:SN5T:NIG4:VJUO:TDJ6                
Docker Root Dir: C:\ProgramData\Docker                                         
Debug Mode (client): false                                                     
Debug Mode (server): true                                                      
 File Descriptors: -1                                                          
 Goroutines: 31                                                                
 System Time: 2018-07-25T14:19:35.9793673-07:00                                
 EventsListeners: 1                                                            
Registry: https://index.docker.io/v1/                                          
Labels:                                                                        
Experimental: true                                                             
Insecure Registries:                                                           
 127.0.0.0/8                                                                   
Live Restore Enabled: false                                                    
                                                                               
PS C:\ProgramData\Docker> docker images
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
microsoft/windowsservercore   latest              7d89a4baf66c        2 weeks ago         10.7GB

PS C:\ProgramData\Docker\config> more .\daemon.json
{
    "registry-mirrors": [],
    "insecure-registries": [],
    "debug": true,
    "experimental": true
}

PS C:\ProgramData\Docker\config> docker ps -a
CONTAINER ID        IMAGE                         COMMAND                    CREATED             STATUS              PORTS               NAMES
b8f1e3a4b9f5        microsoft/windowsservercore   "c:\\windows\\system32…"   22 minutes ago      Created                                 eloquent_swirles
PS C:\ProgramData\Docker\config>

PS C:\ProgramData\Docker\config> docker images
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
microsoft/windowsservercore   latest              7d89a4baf66c        2 weeks ago         10.7GB
PS C:\ProgramData\Docker\config> docker run 7d89a4baf66c
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container eaf5a8bcf33c635f427565f81aeda625f77c97b3b015a1a77dad5e12ffb15be6 encountered an error during Start: failure in a Windows system call: The compute system exited unexpectedly. (0xc0370106).
PS C:\ProgramData\Docker\config> docker ps -a
CONTAINER ID        IMAGE                         COMMAND                    CREATED             STATUS              PORTS               NAMES
eaf5a8bcf33c        7d89a4baf66c                  "c:\\windows\\system32…"   45 seconds ago      Created                                 trusting_chatterjee
b8f1e3a4b9f5        microsoft/windowsservercore   "c:\\windows\\system32…"   24 minutes ago      Created                                 eloquent_swirles
PS C:\ProgramData\Docker\config> docker logs eaf5a8bcf33c
PS C:\ProgramData\Docker\config>

It's running Windows containers.

Attempting to switch to Linux containers results in an error: error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_eng ...

### Steps to reproduce the behavior

  1. docker run hello-world
  2. ...

**Comment by ebriney** [comment]
Hi @adrianblakey.
I tried on my computer and it works.
Did you have latest windows updates? (there seems to be an hyperv problem but that concerns linux containers)
Perhaps it's related to
`[14:54:48.736][WindowsDaemon  ][Info   ] Would be blocked by access protection rule  (rule is in warn-only mode) (Anti-spyware Maximum Protection:Prevent all programs from running files from the Temp folder).`
Can you disable your anti spyware software and retry?
You can also try a `docker image prune -f` or a reset to default to reload layers
