### ISSUE TITLE
Docker for Windows not starting on Windows 10 Education

### ISSUE THREAD

**Issue by BastianKrones** [docker/for-win#228]
### Expected behavior

Docker should start

### Actual behavior

Docker is stuck at "Docker is starting...."

### Information

  - Diagnostic ID: 2cd37571-2f8d-4145-9da9-a40fa5dcf1e4
  - Windows 10 Education (Version: 1607; Build: 14393.447)

### Steps to reproduce the behavior

  1. Lanching Docker for Windows

### Logfile

> Version: 1.12.3 (8488)
> Channel: Stable
> Sha1: d63ec34a49019d2e0b29d7706e57ccfc721ddb8f
> Started on: 2016/11/14 17:42:57.794
> Resources: C:\Program Files\Docker\Docker\Resources
> OS: Windows 10 Education
> Edition: Education
> Id: 1607
> Build: 14393
> BuildLabName: 14393.447.amd64fre.rs1_release_inmarket.161102-0100
> You can send feedback, including this log file, at https://github.com/docker/for-win/issues
> [17:42:57.747][Tracking       ][Info   ] Crash report and usage statistics are enabled
> [17:42:57.810][SegmentApi     ][Info   ] Usage statistic: appLaunched
> [17:42:57.869][NamedPipeClient][Info   ] Sending Version()...
> [17:42:57.893][NamedPipeClient][Info   ] Received response for Version
> [17:42:57.901][SegmentApi     ][Info   ] Usage statistic: heartbeat
> [17:42:55.345][BackendServer  ][Info   ] Started
> [17:42:55.345][Moby           ][Info   ] Connecting...
> [17:42:57.885][NamedPipeServer][Info   ] Version()
> [17:42:57.889][NamedPipeServer][Info   ] Version done.
> [17:42:58.089][Notifications  ][Info   ] Docker is starting...
> [17:42:58.089][Updater        ][Info   ] Checking for updates on channel Stable...
> [17:42:58.120][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings)...
> [17:42:58.120][NamedPipeServer][Info   ] Start(Docker.Core.Settings)
> [17:42:58.136][HyperVGuids    ][Info   ] Installing GUIDs...
> [17:42:58.136][HyperVGuids    ][Info   ] GUIDs installed
> [17:42:58.167][Updater        ][Info   ] Local build 8488 is as good as the remote 8488 on channel Stable
> [17:42:58.167][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
> [17:42:59.702][Firewall       ][Info   ] Ports are opened
> [17:42:59.702][HyperV         ][Info   ] Create
> [17:42:59.718][PowerShell     ][Info   ] Run script with parameters: -Create True -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
> [17:43:03.656][HyperV         ][Info   ] Creating Switch: DockerNAT...
> [17:43:25.446][SegmentApi     ][Info   ] Usage statistic: actionMenuSettings
> [17:43:38.042][FeedbackSettings][Info   ] Open logs
> [17:43:51.997][FeedbackSettings][Info   ] Open logs
> [17:44:08.052][FeedbackSettings][Info   ] Open logs
> [17:44:10.925][FeedbackSettings][Info   ] Open logs
> [17:44:39.485][FeedbackSettings][Info   ] Open logs
> [17:45:58.247][FeedbackSettings][Info   ] Upload diagnostic
> [17:45:58.253][NamedPipeClient][Info   ] Sending GetDebugInfo()...
> [17:45:58.257][NamedPipeServer][Info   ] GetDebugInfo()
> [17:46:10.916][FeedbackSettings][Info   ] Open logs
> [17:46:15.062][NamedPipeServer][Info   ] GetDebugInfo done.
> [17:46:15.077][NamedPipeClient][Info   ] Received response for GetDebugInfo
> [17:46:15.089][Program        ][Info   ] Sending Bugsnag report 2cd37571-2f8d-4145-9da9-a40fa5dcf1e4...
> [17:46:16.408][Program        ][Info   ] Bugsnag report 2cd37571-2f8d-4145-9da9-a40fa5dcf1e4 sent
> [17:46:16.463][NamedPipeClient][Info   ] Sending DownloadVmLogs()...
> [17:46:16.478][NamedPipeServer][Info   ] DownloadVmLogs()
> [17:46:16.496][PowerShell     ][Info   ] Run script...
> [17:46:21.717][FeedbackSettings][Info   ] Open logs

**Comment by myfope** [comment]
Hi,
do you use COMODO Internet Security Pro?
There are reports that this issue is caused by this software.

**Comment by BastianKrones** [comment]
Hi, 
sorry, but no, i am using Antivir.
Nevertheless i reinstalled docker without any antivir software and the issue is still remaining.

**Comment by BastianKrones** [comment]
I recently reinstalled Windows totally and docker is now working properly.
Sorry the issue just disappeared.

**Comment by adriansolis** [comment]
Hi, @BastianKrones . I am totally new to Docker and I want to have it working in my computer directly. I wanna know: Does Docker for Windows 10 Education uses toolbox or it runs directly? It's because I'm thinking to upgrade from Windows 10 home to pro, but that's $100 off my pocket. Nevertheless, I'm also a student so I could get the Education version.
