### ISSUE TITLE
 Backend service is not installed

### ISSUE THREAD

**Issue by 120064921** [docker/for-win#2294]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. issue
 Backend service is not installed
   在 Docker.WPF.BackendClient.CheckService() 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:行号 344
   在 Docker.WPF.BackendClient.SendMessage(String action, Object[] parameters) 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:行号 157
   在 Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:行号 77
   在 Docker.Actions.<>c__DisplayClass18_0.<ResetToDefault>b__0() 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:行号 137
   在 Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:行号 59

**Comment by ebriney** [comment]
Hi @120064921.
Try to check in powershell `Get-Service com.docker.service` if it's not there uninstall/reinstall Docker Desktop.
If it's there and status is running upload a diagnostic and reopen the issue.
