### ISSUE TITLE
Can't access server on LAN from container

### ISSUE THREAD

**Issue by LKajan** [docker/for-win#231]
### Expected behavior
Should be able to connect to our database server on ip 172.17.15.220
### Actual behavior
172.17.15.220 is not accessible. For example pinging to that ip is not working.
### Information
  - Diagnostic ID: 05C08335-768F-4633-B317-DB8FC12EB3B8/2016-11-15_12-58-42
  - Windows 10 Enterprise, Docker for Windows 1.12.3

I was not sure if I should create issue here or post to the forum but here I'll go.

I'm unable to connect to database server that is on our local network/domain. Ping to db server's ip address (172.17.15.220) also times out.
Is it because the subnet of my laptop (docker host) is 172.17.22.1/24 so it conflicts with docker's one? Actually my laptop and the db server are on different subnets.

I have tried to create a new bridge network with custom subnet and using that on my containers but without a success.

    docker network create -d bridge --gateway=192.168.0.1 --subnet=192.168.0.1/24 mybridge
    docker run --network=mybridge alpine ping 172.17.15.220
still doesn't work.

Does the default bridge with subnet 172.17.0.0/16 still cause problems?

Where the packages get stuck?

Or is this some firewall issue?

**Comment by rneugeba** [comment]
@LKajan thanks for your detailed report, and yes, this is a good place to report these type of issues.

I think you might be right regarding the address clash. The Docker bridge in the Linux VM is indeed using `172.17.0.0/24` as the default subnet and it clashes with your LAN. You can change the IP addresses used by changing the daemon configuration in the Settings menu. I think the entry you want is something like:
```
"bip": "172.16.0.0/16",
```
(or a different subnet)

HTH
Rolf

**Comment by LKajan** [comment]
Thanks @rneugeba,

Unfortunately docker is unable to start when adding the bip option to daemon config. I'm pretty sure that bip worked in previous docker version, maybe in 1.12.1.

Bip is not either listed as allowed [config options on Windows](https://docs.docker.com/engine/reference/commandline/dockerd/#/daemon-configuration-file#windows-configuration-file) any more.

**Comment by rneugeba** [comment]
@LKajan sorry, for the delay. Turns out my suggestion was incorrect and the syntax should be something like:
```
"bip": "172.18.0.1/16",
```
ie you specify the gateway as part of the IP address range. This works for me on Beta 30.1 and I verified the setting of ip address:
```
% ip addr
[...]
15: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP
    link/ether 02:42:f3:15:a5:db brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:f3ff:fe15:a5db/64 scope link
       valid_lft forever preferred_lft forever
[...] 
```

Could you give that a try?

FWIW the documentation you linked to regarding the `bip` config option not being allowed for Windows applies to *Windows Containers*. Docker for Windows Beta supports both Linux container and windows containers, but you seem to be using Linux containers (which is the default).

**Comment by LKajan** [comment]
Thank you @rneugeba!
I got it finally working.

So the trick was to have also the bip and a custom network for compose application.
I must have also misconfigured the bip not to have the .1 gateway when tried that by myself.

**Comment by rneugeba** [comment]
Excellent, glad it's working and thanks for reporting back. Yeah, I initially gave you a wrong example for the `bip` parameter (not to well documented) but realised when I tried myself.

**Comment by gulliva1** [comment]
@LKajan  you figured out the problem and i'm strugeling around with the same issue. Can you perhaps tell me how you configured your bridge or what else you have done to get it up running?

Greets

**Comment by LKajan** [comment]
@gulliva1, If your office network is in conflict with Docker then this should help you. First you must change Docker default subnet in daemon config. Add "bip": "172.18.0.1/16" to json config.
For normal docker containers you can just define a used network. First create one with:

    docker network create -d bridge --gateway=192.168.0.1 --subnet=192.168.0.1/24 mybridge
    docker run --network=mybridge alpine ping 172.17.15.220

For compose applications you must also define the default network. In you docker-compose.yml file add:

    networks:
      default:
        driver: bridge                
        ipam:                         
          driver: default           
          config:                       
            - subnet: 172.19.0.0/16

Our network configurations has changed since so I can't test this anymore and I'm not 100% sure if that was all.
Hopefully you get things working!

**Comment by gulliva1** [comment]
@LKajan 
Thanks for your reply, meanwhile it works fine. I solved the Problem by updating my locale docker version to the current stable release. 
After this, the problem was not longer existing.

Thanks a lot.
