### ISSUE TITLE
mobyLinuxVM cannot start on any Windows VM

### ISSUE THREAD

**Issue by sraul111** [docker/for-win#2320]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by sraul111** [comment]
mobyLinuxVM cannot start on any Windows azure VM

I tried on win 10 Azure vm  and win server 2016 vm

**Comment by gtardif** [comment]
Sorry, Docker Desktop for Windows (Windows 10) is not supported in nested virtualization scenarios. See https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-for-windows-in-nested-virtualization-scenarios for details.
To get help with Docker on Windows Server please see http://success.docker.com/article/where-to-get-help-with-windows.
