### ISSUE TITLE
Can't install Google Chrome into a new image using Dockerfile RUN commands. (base: windowsservercore)

### ISSUE THREAD

**Issue by NehirGokce** [docker/for-win#2326]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Google Chrome is installed in the new docker image I've created.

### Actual behavior

Google directory is created, however there is no Chrome installed.

### Information

  -The problem might be reproducable, I will be sharing my Dockerfile contents.
  - Windows Version: Windows 10 Pro
  - Docker for Windows Version: 18.06.0-ce-win72 

### Steps to reproduce the behavior

  1. Create a new directory named windows-selenium-chrome-node
  2. Create a new Dockerfile there
  3. Dockerfile contents:

FROM microsoft/windowsservercore

RUN powershell (new-object System.Net.WebClient).Downloadfile('http://javadl.oracle.com/webapps/download/AutoDL?BundleId=234443_96a7b8442fe848ef90c96a2fad6ed6d1', 'C:\JavaSetup8u181.exe')
RUN powershell start-process -filepath C:\JavaSetup8u181.exe -passthru -wait -argumentlist "/s,INSTALLDIR=c:\Java\jre1.8.0_181,/L,install64.log"
RUN powershell SetX /M PATH "\\"C:\Java\jre1.8.0_181\bin;$env:PATH\""
RUN powershell SetX /M JAVA_HOME "\\"C:\Java\jre1.8.0_181""
RUN del C:\JavaSetup8u181.exe
ADD https://www.7-zip.org/a/7z1805-x64.exe \7z1805-x64.exe
RUN powershell Start-Process -Wait -FilePath '\7z1805-x64.exe' -ArgumentList '/S'
RUN powershell SetX /M PATH "\\"C:\Program Files\7-zip;$env:PATH\""
RUN powershell Remove-Item -Force /7z1805-x64.exe
RUN powershell (new-object System.Net.WebClient).Downloadfile('https://chromedriver.storage.googleapis.com/2.41/chromedriver_win32.zip','C:\chromedriver_win32.zip')
RUN powershell (new-object System.Net.WebClient).Downloadfile('https://goo.gl/4g538W', 'C:\selenium-server-standalone-3.13.0.jar')
RUN 7z.exe e chromedriver_win32.zip
RUN powershell SetX /M PATH "\\"C:;$env:PATH\""
RUN powershell SetX /M PATH "\\"C:\chromedriver.exe;$env:PATH\""
RUN powershell (new-object System.Net.WebClient).Downloadfile('https://dl.google.com/chrome/install/latest/chrome_installer.exe', 'C:\ChromeSetup.exe')
RUN powershell . C:\ChromeSetup.exe /silent /install 

   4. Open up cmd.
   5. Go to the new directory we've created using cd
   6. docker build . -t windows-chrome-node
   7. docker run -ti windows-chrome-node
   8. Check inside the container's Program Files(x86)/Google directory to see that there is no Chrome installed.

**Comment by venkateshseerapu** [comment]
Hi @NehirGokce 

Did u find any solution to install the chrome browser through Windows docker file. I'm facing the similar issue, could you please help me with this.
