### ISSUE TITLE
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The object already exists.

### ISSUE THREAD

**Issue by sbarber2** [docker/for-win#2329]
- [X] I have tried with the latest version of my channel (Stable or Edge) -- Stable
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 7E3D135F-C968-49C1-9597-572F8D3793A6/20180730092551

### Expected behavior

Docker for Windows starts without error

### Actual behavior

Docker for Windows stops with this error:

Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The object already exists.

   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 77
   at Docker.Actions.<>c__DisplayClass16_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 61
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible?
Yes
  - Is the problem new?
Yes
  - Did the problem appear with an update?
Yes, updated from 1703 to 1806 CE. But also updated 64bit Windows 10 Pro, Enterprise (1511 November update, Build 10586) to Version 1803 (OS Build 17134.167) without trying Docker 1703 after the Windows upgrade first (my bad!)

  - Windows Version: Windows 10 Pro Enterprise Version 1803 (OS Build 17134.167) 
  - Docker for Windows Version:
Docker for Windows
Version: 18.06.0-ce-win72 (19098)
Channel: stable
Sha1: 5513f91045dac2b8d51420014ee9176d24791d7d
OS Name: Windows 10 Pro
Windows Edition: Professional
Windows Build Number: 17134

Also: 

C:\WINDOWS\system32>bcdedit /enum {default}

Windows Boot Loader
-------------------
identifier              {current}
device                  partition=C:
path                    \WINDOWS\system32\winload.exe
description             Windows 10 boot 2
locale                  en-US
inherit                 {bootloadersettings}
recoverysequence        {42e868bb-488b-11e6-95ad-896b1d2276cc}
recoveryenabled         Yes
allowedinmemorysettings 0x15000075
osdevice                partition=C:
systemroot              \WINDOWS
resumeobject            {8acaaf89-488a-11e6-95ad-896b1d2276cc}
nx                      OptIn
bootmenupolicy          Standard
hypervisorlaunchtype    Auto

### Steps to reproduce the behavior
1. Boot Windows, allow the default boot entry to boot
2. Watch Docker start automatically
3. Watch it fail as above.

**Comment by Filipedguy** [comment]
See https://github.com/docker/for-win/issues/2453#issuecomment-415023200 for more info

**Comment by verglor** [comment]
I have the same problem after Windows update to 1809.
