### ISSUE TITLE
thinkpad t410 i5 M430 4G ram install fails

### ISSUE THREAD

**Issue by osde8info** [docker/for-win#233]
### Expected behavior
install and run without any memory errors

### Actual behavior
gives not enough memory error

### Information
A23A7D60-5104-4597-8849-E121263D679D/2016-11-15_15-26-49

reboot and restart you dont get error

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ... install
  2. ...

**Comment by rneugeba** [comment]
by default the Linux VM is configured to use 2GB of memory. You can adjust this down to 1GB of memory using the settings. Could you try that?

**Comment by rneugeba** [comment]
actually, I'm closing this in favour of #234
