### ISSUE TITLE
Can't start Docker for Windows 18-06

### ISSUE THREAD

**Issue by gandalf4j** [docker/for-win#2330]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID: 2FA28238-7F8C-4261-8262-F9833F7C8E6C/20180730172918

### Expected behavior
Start Docker for Windows after update
### Actual behavior
Docker hangs forever until Crash report popup shows
### Information

  - Windows Version:
Windows 10 Enterprise
  - Docker for Windows Version:
18-06
### Steps to reproduce the behavior
-update docker for windows version

**Comment by geedsen** [comment]
Go back to an older version:
Install Chocolatey if you don't have it yet ( https://chocolatey.org/) and then in an elevated powershell prompt run "Choco list docker-for-windows --all" to see all versions available and run for example "Choco install docker-for-windows -version 18.03.1.17513" to install the mentioned version, make sure you uninstall the version you don't want first.

**Comment by gandalf4j** [comment]
@geedsen I'll unistall/restore a previous version, even if with other versions took me some ten minutes to get docker up and running...it's the only thing I can do...
thank you bye
