### ISSUE TITLE
Docker network id change on docker restart

### ISSUE THREAD

**Issue by JoBaAl** [docker/for-win#2337]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Network Id must not change on restart docker service.

### Actual behavior
When I restart docker, the Id of the network change. If the network id change, when docker is restarted I get the error  Error response from daemon: network networkid not found

The network information before restart is the following:

```
[
    {
        "Name": "dockerwindows_test",
        "Id": "8e2ba80b9ffa0323eaebd0a9a06f8e87fcea554d170571e919963e5750a2c5e3",
        "Created": "2018-07-31T13:50:47.5868263+02:00",
        "Scope": "local",
        "Driver": "nat",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "windows",
            "Options": null,
            "Config": [
                {
                    "Subnet": "0.0.0.0/0"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "4c9b5d09f2232e3f5ede77f20e63c394225f259d907cac639719d1d6a7d64bf2": {
                "Name": "dockerwindows_cm04_1",
                "EndpointID": "58cf402fbf4e9659b1a54569ba1f26d622e7d452f9ec801829c3c5bbaee961ce",
                "MacAddress": "00:15:5d:79:ff:13",
                "IPv4Address": "172.23.109.40/16",
                "IPv6Address": ""
            },
            "a22358f0e13f9b3fabdf08bec3cd3c074d50849bc502c1126dd0c7973bf17ba2": {
                "Name": "dockerwindows_cm08_1",
                "EndpointID": "52e4ceb221e16bf10bc45c6ed406f4ee9edfb50e10bde29bffc5736026c78d1f",
                "MacAddress": "00:15:5d:79:f1:9e",
                "IPv4Address": "172.23.96.84/16",
                "IPv6Address": ""
            },
            "d3b39cc23018c130891da1d1beb24ec1568bf1d3d9f3ade1ecf249493fb4ad74": {
                "Name": "dockerwindows_cm06_1",
                "EndpointID": "aeb0f6dc75812db61bb761b55e399f1693d214da04630ac1f0d05789a9b9e999",
                "MacAddress": "00:15:5d:79:fc:89",
                "IPv4Address": "172.23.105.250/16",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.windowsshim.hnsid": "290e2f62-9709-410a-acd4-8dfefa063cfe"
        },
        "Labels": {
            "com.docker.compose.network": "test",
            "com.docker.compose.project": "dockerwindows",
            "com.docker.compose.version": "1.22.0"
        }
    }
]
```

When I restart docker this is the network information:

```
[
    {
        "Name": "dockerwindows_test",
        "Id": "bb8f648805675935c1de7a1e48068ae1c356df60316fa0c6f9bafd416951688f",
        "Created": "2018-07-31T13:52:27.8556034+02:00",
        "Scope": "local",
        "Driver": "nat",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "windows",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.23.96.0/20",
                    "Gateway": "172.23.96.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {
            "com.docker.network.windowsshim.hnsid": "290e2f62-9709-410a-acd4-8dfefa063cfe",
            "com.docker.network.windowsshim.networkname": "dockerwindows_test"
        },
        "Labels": {}
    }
]
```
### Information

  - Windows Version: Windows 10 Pro 1803
  - Docker for Windows Version: 18.06.0-ce-win71 (19101)

### Steps to reproduce the behavior

  1. Docker-compose up -d
  2. docker network inspect nameofthenetwork
  3. Restart docker
  4. docker network inspect nameofthenetwork

**Comment by JoBaAl** [comment]
It seems a normal behaviour. My issue is solved as is shown in this post #2194

**Comment by dmitryRomanchenko** [comment]
The same issue for me. I have created a network manually, added it to the docker-compose file. It works fine for the first time but after restarting docker the network id changes and it cannot longer start the containers. That fix in #2194 doesn't help.

**Comment by JoBaAl** [comment]
Set the network as external. It worked for me. The second comment in #2194 works for me (not the last comment). I installed the container manually and the Network id changes on restart, but the container is started after restarting. It seems that the Id changing on restart is a normal behavior.

**Comment by dmitryRomanchenko** [comment]
yeah It is set as external but still can't start

**Comment by dmitryRomanchenko** [comment]
i reverted back to using the nat network and for some reason it works fine

**Comment by JoBaAl** [comment]
Have you set the nat Network as external?

**Comment by dmitryRomanchenko** [comment]
yeah it is set as external too

**Comment by jkldgoefgkljefogeg** [comment]
I am not using docker compose (just dcoker run) and the container was removed from network definition container field on restart. And the container restart fails with network id not found. 
How is this the normal behavior?

**Comment by akunaatrium** [comment]
I have the same problem on Windows Server 2016. There is a network with a specific ID and some containers running which use that network. When the OS is restarted, the ID of the network changes but containers are not coming up, because although they refer to the correct network name, but the original network ID (which is different now). Windows event log shows this: `Failed to start container 869fcb23c827be63f94662630a9dc1a1d15b88fdc405b6129a144b2458ea8b09: network 13973d1507914e28082e5c707ef6c2c736dbbd6cb4e8c699bf9379c599d4478b not found`.

This issue should be reopened because there is clearly an issue regarding Docker networks.

**Comment by jkldgoefgkljefogeg** [comment]
network ID should not change across reboots. It did not change in my case.
I gave up on Ubuntu 18.04 LTS server and switched to Photon OS 3.0, this issue went away
