### ISSUE TITLE
After kubernetes is enabled, it always shows kubernetes is starting, even the pc is rebooted

### ISSUE THREAD

**Issue by MinweiWang** [docker/for-win#2338]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:6AEBC401-3A1B-455F-96E7-F9FDDFDDB227/20180731203534

### Expected behavior
kubernetes is running
### Actual behavior
kubernetes is starting
### Information
  - Windows Version: Windows 10 Professional
  - Docker for Windows Version: Version 18.06.0-ce-win72 (19098)
Channel: stable

### Steps to reproduce the behavior
  1. enable kubernetes at settings->kubernetes
  2. reboot PC, it always shows kubernetes is starting. see snapshot attached.
![2018-07-31 20_57_22-settings](https://user-images.githubusercontent.com/24369218/43460845-7090cf56-9504-11e8-8586-f1e807d95b2d.png)

**Comment by MinweiWang** [comment]
After PC rebooted several hours, it still shows kubernetes is starting.....

**Comment by groboclown** [comment]
I had the same issue happen.  I had to "reset kubernetes" in order for it to start.

**Comment by dfme** [comment]
Similar issue to https://github.com/docker/for-win/issues/2065 ?
