### ISSUE TITLE
thinkpad t410 i5 M430 4G ram settings advance settings ignored

### ISSUE THREAD

**Issue by osde8info** [docker/for-win#234]
### Expected behavior
cpu should reduce to 1
mem should reduce to 1.7G

### Actual behavior
cpu stays at 2
mem stays at 2G

### Information
A23A7D60-5104-4597-8849-E121263D679D/2016-11-15_15-26-49
  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ... install (and ignore memory errors)
  2. ...reboot
  3. click docker settings
  4. click advanced
  5. reduce cpus to 1
  6. reduce mem to 1.7G
  7. click apply
  8. wait

**Comment by rneugeba** [comment]
I close this issue in favour of #235 as it seems the same/related issue reported by the same user
