### ISSUE TITLE
Cannot run Windows contrainers on Win10

### ISSUE THREAD

**Issue by ugnelis** [docker/for-win#2353]
I am trying to run **Windows containers** on Windows 10.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics (I have got an error only a few minutes later).

I have tried:
  - to reinstall Docker (not helping).
  - to reboot my laptop many times (not helping).
  - to run **Windows containers** on Windows 10 (not working, no error, example in picture)
![image](https://user-images.githubusercontent.com/8350893/43519464-d3c89870-958f-11e8-96ea-cd6e06447e2a.png)

P.s.  I have tried to run **Linux containers** on Windows 10 and it is working.

### Expected behavior
Message in console by using Windows containers:
```
Hello from Docker!
> docker run hello-world
This message shows that your installation appears to be working correctly.
...
```
### Actual behavior
Message in console by using Windows containers:
```
> docker run hello-world
(nothing happens)
```
### Information
  - Windows Version: 10 Pro x64 Version 1607 (Build 14393.0)
  - Docker for Windows Version:  Docker Stable (Docker version 18.06.0-ce, build 0ffa825
  - I have got an error only a few minutes later (I don't know if it's related):
```
Timed out while waiting for Docker daemon to be ready
   bei Docker.Backend.Processes.WindowsDockerDaemon.WaitForDaemonToBeReady() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:Zeile 147.
   bei Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:Zeile 222.
   bei Docker.Backend.ContainerEngine.Windows.Restart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:Zeile 153.
   bei Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:Zeile 48.
   bei Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:Zeile 180.

```

How can I solve this problem?

**Comment by ericcox** [comment]
I was having this problem earlier today. I was able to get around this by:

1. Completely uninstall Docker
2. Reboot the machine
3. Install Docker with "Use Windows Containers..." checked. (Or whatever it's called)

Before this, I tried merely uninstalling/installing without the reboot, and it did not work.

Hope that helps...

**Comment by ugnelis** [comment]
@Ericcox, I have tried this with different versions. It doesn't sound like solution to problem.

**Comment by jcjwent** [comment]
The solution provided by ericcox (https://github.com/docker/for-win/issues/2353#issuecomment-412692196) worked out for me.

**Comment by Monte-Christo** [comment]
I had to downgrade Docker. Nothing else suggested here worked.

1. Uninstall Docker
2. Go to [https://docs.docker.com/docker-for-windows/release-notes/#stable-releases-of-2018](https://docs.docker.com/docker-for-windows/release-notes/#stable-releases-of-2018)
3. Download Docker Community Edition 18.03.1-ce-win65 2018-04-30
4. Install

I finally was back up and running.

**Comment by guillemsola** [comment]
Same here. Installed 18.03 and windows containers are back again.
