### ISSUE TITLE
An error occured in windows 10

### ISSUE THREAD

**Issue by mypark3424** [docker/for-win#236]
### Expected behavior

I don't know why this happened. Please help me.
### Actual behavior
![default](https://cloud.githubusercontent.com/assets/20012568/20312251/22999282-ab96-11e6-84c1-72f5d2e7154a.PNG)

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.

Diagnostic ID  : BE474FA0-4C55-436E-B11E-571858FFB991/2016-11-16_00-44-11

  - a reproducible case if this is a bug, Dockerfiles FTW

  - page URL if this is a docs issue or the name of a man page

  - host distribution and version (Windows version, build number, etc)

    Windows 10 Pro, Intel(R) Core i7-6700K

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by friism** [comment]
Details here: https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization-must-be-enabled
