### ISSUE TITLE
Cannot run hello-world to confirm that the installation was successful

### ISSUE THREAD

**Issue by dazomega** [docker/for-win#2364]
Hi,

I am using windows 10 pro with hyper-V installed, my diagnostic ID is: 

I have checked the issues listed on: https://docs.docker.com/docker-for-windows/troubleshoot/

However these issues did not seem relevant to the issue I am experiencing. 

My log file is attached below:
[docker-log.txt](https://github.com/docker/for-win/files/2257006/docker-log.txt)

  - [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: ED6E939B-9750-4C6D-AB77-DE11C488FDB1/20180803111536

### Expected behavior

unable to find image 'hello-world-latest' locally
latest: pulling from library/hello-world

Hello from Docker!

### Actual behavior

error during connect: Get https://192.168.99.100:2376/v1.38/containers/json: dial tcp 192.168.99.100:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

### Information

I am quite new to docker, I have run docker for windows on windows 10 home prior to updating to pro with hyper-V. 

This problem is new when running this version of docker for windows, I have switched versions and found that the error still persists. 

I can run the command to retrieve the docker version: docker --version

however when trying to use the following command: docker run hello-world

the error is produced as shown above.

  - Windows Version: 10 Pro
  - Docker for Windows Version: 18.06.0-ce-win72 (Stable)

### Steps to reproduce the behavior

  1. docker run hello-world

**Comment by Foadsf** [comment]
I have reported similar issue [here](https://github.com/docker/for-win/issues/2596).  this error has been reported one month ago. still not even tagged! this is sad  to see Docker support is not that good.

**Comment by Patafikss** [comment]
I had the same problem, here are the steps I took :

- uninstall docker
- delete %USERS%/.docker
- delete eveything related to docker in %USERS%/AppData
- verify that your environnment variables related to docker are deleted
- go in device manager and delete everything related to hyper-v
- disable hyper-v feature
- reboot
- enable hyper-v
- reboot
- install docker
Somehow it worked.

**Comment by marczahn** [comment]
To me https://github.com/docker/for-win/issues/1746#issuecomment-384940428 was the solution. It seems that there have been leftovers from earlier installations
