### ISSUE TITLE
Can't open file located on mounted volume from different processes at the same time

### ISSUE THREAD

**Issue by logachev** [docker/for-win#2368]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
File located on the mounted volume can be opened for read multiple times (from different processes at the same time e.g.)

### Actual behavior
If file is located on the mounted volume, it can be opened once. If you try to open it again it fails with 'file not found error'.
It works on Linux and Mac.

### Information

  - Windows Version: 10 1803
  - Docker for Windows Version: 18.06.0-ce-win72 (19098)

### Steps to reproduce the behavior

1. Mount a folder with a file
2. Try to open any file twice at the same time (e.g. `cat sample.txt & cat sample.txt`)

I have quick repro here: https://github.com/logachev/dockertest
docker build -t test .
docker run -it -v <path_to_git>/scripts:/scripts test
python test.py sample.txt

Important update:
It seems like the issue is folder/disk specific.
If I clone my repo to e: and k: drives, mounting `/e/dockertest/scripts` - works but `/k/dockertest/scripts` doesn't work.

**Comment by logachev** [comment]
It might be related to the case-sensitivity attribute in Windows: https://blogs.msdn.microsoft.com/commandline/2018/06/14/improved-per-directory-case-sensitivity-support-in-wsl/

In my case, I see 100% repro if folder was created via WSL and no repro if it was created from Windows.
WSL now by default marks created directories with case-sensitive attribute that allows to work with them from either Linux or Windows.

If I disable this attribute, issue goes away. It appears, if attribute is enabled.
```
S:\source>docker run -it -v /s/source/test6/scripts:/scripts test
(app-root) bash-4.2$ python test.py sample.txt
Print file content:
Just some sample text

===================
Open file twice:
File opened
(app-root) bash-4.2$ exit
exit

S:\source>fsutil.exe file setCaseSensitiveInfo test6/scripts enable
Case sensitive attribute on directory S:\source\test6\scripts is enabled.

S:\source>docker run -it -v /s/source/test6/scripts:/scripts test
(app-root) bash-4.2$ python test.py sample.txt
Print file content:
Just some sample text

===================
Open file twice:
Failed to open file second time
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    with open(sys.argv[1], "r") as f2:
FileNotFoundError: [Errno 2] No such file or directory: 'sample.txt'
(app-root) bash-4.2$
```

**Comment by hendrics** [comment]
Interestingly, https://github.com/docker/for-win/issues/969#issuecomment-411429451 reports exactly the same issue 4 days after this is open.

**Comment by jzampieron** [comment]
Can confirm this issue 100% of the time. I have a compile process in a container that works under Mac and Linux and WSL.

Doing this from powershell consistently fails for parallel (-j8) builds. If I dial the `make -j8` back down to a `make -j1` everything works fine.

**Comment by stephen-turner** [comment]
The file sharing code has been completely rewritten in 2.2, so I'm assuming this issue has now gone. If not, please open a new ticket.

**Comment by logachev** [comment]
I just tried my old repro description and I no longer see the issue! Thanks @stephen-turner!
