### ISSUE TITLE
Docker daemon fails to start if configured with cluster-store option: The VM couldn't get an IP address

### ISSUE THREAD

**Issue by vincebowdren** [docker/for-win#237]
### Expected behavior

Docker daemon, when configured with options cluster-store and cluster-advertise, starts up successfully and lets me create an overlay network.

### Actual behavior

Docker daemon fails to restart, throwing this error:
```
[NamedPipeServer][Error  ] Unable to execute Start: Unable to start: The VM couldn't get an IP address after 60 tries
at Fatal, <No file>: line 353
at Start-MobyLinuxVM, <No file>: line 267
at <ScriptBlock>, <No file>: line 363    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

### Information

  - Diagnostic ID: 2ED685A8-396C-4179-8AE3-AE88F792A155/2016-11-15_15-15-03
  - Windows version: 10 Enterprise, Id 1607, build 14393, BuildLabName: 14393.187.amd64fre.rs1_release_inmarket.160906-1818
  - Fault observed happening the same in all of the following setups:
    1. Current stable build v1.12.3 build 6b664ec
    2. Current beta build v1.12.3. build 6b664ec experimental (2016-11-09)
    3. Current beta build, with the [altered iso from Issue 54](https://github.com/docker/for-win/issues/54#issuecomment-257157813)

### Steps to reproduce the behavior

  1. Install Docker for Windows; the docker engine starts up happily.
  2. Install consul on Windows as per [instructions](https://www.consul.io/intro/getting-started/install.html).
  3. Run consul, configuring it to be accessible from within any docker container: `consul agent -dev -bind="10.0.75.1" -client="0.0.0.0"` (in this case, *10.0.75.1* is the ip address of my pc)
  4. Confirm that consul is running locally and responding, with this command from a powershell window: 'Invoke-RestMethod -Uri http://10.0.75.1:8500/v1/catalog/nodes -Method Get'
  5. At this point you can restart the docker daemon if required, to confirm that the installation of consul has not, by itself, made anything go wrong.
  6. Make the crucial change: in the Docker Settings dialog's Docker Daemon tab, change config from the factory default:
```
{
  "registry-mirrors": [],
  "insecure-registries": [],
  "debug": false
}
```
adding two new options, pointing at the local consul service and advertising the pc's ip address:
```
{
  "registry-mirrors": [],
  "insecure-registries": [],
  "debug": false,
  "cluster-store": "consul://10.0.75.1:8500",
  "cluster-advertise": "10.0.75.1:2375"
}
```
  7. Press Apply, and wait for docker daemon to restart; it fails, timing out with the failure as shown above.

In addition to the diagnostic log, I have attached:
- 101: the output from the consul log
- 102: the log from a successful docker startup, without the cluster options
- 103: the log from a failing docker startup with the cluster options
[001_attachments.zip](https://github.com/docker/for-win/files/592549/001_attachments.zip)

**Comment by dgageot** [comment]
@vincebowdren Before you configured `dockerd`, have you tried to connect to consul from inside a container with a simple curl? There's a change that your firewall rejects communications from the Moby VM to the host on port 8500.

**Comment by vincebowdren** [comment]
@dgageot You're completely right. I checked with nmap (connecting from within a container), and it told me the port was filtered:

    PORT     STATE    SERVICE
    8500/tcp filtered fmtp

I reconfigured the windows firewall to stop blocking the port, and nmap confirmed that it was showing as open:

    PORT     STATE SERVICE
    8500/tcp open  fmtp

And that was enough to let docker restart with the cluster-store and cluster-advertise options - all sorted, thanks.

**Comment by dgageot** [comment]
@vincebowdren Good to know! I'm going to close the issue then.
