### ISSUE TITLE
Stuck at "Kuburnetes is starting..."

### ISSUE THREAD

**Issue by johnmiroki** [docker/for-win#2395]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:A3A24400-7AB8-42E7-9575-DDD4044CE1DE/20180808152358

### Expected behavior
After enabling kuburnetes, it starts in a timely manner
### Actual behavior
A dialog box pops up, reading "Waiting for Kuburnetes to be up and running“. Ten minutes later, the message remains. Closing that box, I can see "Kuburnetes is starting" on the left bottom of the Docker interface.

**Comment by fgarciachipi** [comment]
I have the same problem, after enabling Kubernetes the setting dialog always shows "Kubernetes is starting..."

![image](https://user-images.githubusercontent.com/8441996/43963736-250071b8-9c89-11e8-8a65-18f38db070d5.png)

**Diagnostics ID**:  9CEAA9CA-5643-4994-8762-A1B9F8DBEBD3/20180810101017
**OS**: Windows 10 Enterprise - version 1803 (OS build 17134.165)
**Docker for windows**: Version 18.06.0-ce-win72 (19098)
**Channel**: stable

I can run Kubernetes commands like: `kubectl get nodes` and it works
![image](https://user-images.githubusercontent.com/8441996/43963663-efb0910a-9c88-11e8-9ff5-edd3298416a6.png)

Also, I have noticed that the Kubernetes setting is "disabled"

![image](https://user-images.githubusercontent.com/8441996/43963840-73ae9ce0-9c89-11e8-8c97-1651e91ca4e4.png)

I have tried the "Reset Kubernetes Cluster..." option but the result is the same.

**Comment by fgarciachipi** [comment]
After a while (a day) Kubernetes is running too. I noticed this:

![image](https://user-images.githubusercontent.com/8441996/43977579-97486d4c-9cb2-11e8-8ec8-b352f3b01706.png)

It seems that there was something pending to download. Now that Kubernetes is running this is what I get:

![image](https://user-images.githubusercontent.com/8441996/43977853-52daec88-9cb3-11e8-8fe7-cc715a29ff71.png)

**Comment by johnmiroki** [comment]
@fgarciachipi good observation. Thanks. if only docker provided a way for us to manually download these packages/images...

**Comment by dfme** [comment]
similar issue to https://github.com/docker/for-win/issues/2065 ?

**Comment by giftkugel** [comment]
Try my solution commented at https://github.com/docker/for-win/issues/1962#issuecomment-418152414
