### ISSUE TITLE
Accessing a shared drive (PC2)  in Host (PC1) container

### ISSUE THREAD

**Issue by mpatturi** [docker/for-win#2398]
Dear Team,
We have a requirement where we need to access the share drive  located in a system in network other than host system.We are getting access denied exception though we are able to ping the ip of shared system from container.

Is it achievable ? if so what I need to configure in docker file or docker run command.

Any solution will be helpful.

Env: Docker for windows

Please, check https://docs.docker.com/docker-for-windows/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

Issues unrelated to Docker for Windows will be closed.  In particular, see
  - https://github.com/docker/compose/issues for docker-compose
  - https://github.com/docker/machine/issues for docker-machine
  - https://github.com/moby/moby/issues for Docker daemon
  - https://github.com/docker/docker.github.io/issues for the documentation
-->

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ebriney** [comment]
Hi @mpatturi. No it's not possible without tweaking things, filesharing in Docker for Windows do a smb share using a cifs mount on the network interface of the vm which is shared with your computer so basically it only access to your local drives (we mount 10.0.75.1\C).

You can mount your network drive manually (NFS and SMB should work) using `docker4w/nsenter-dockerd` image in privileged mode but you will have to do it every time your restart the vm.
