### ISSUE TITLE
Docker Fails to Reboot into Linux Containers

### ISSUE THREAD

**Issue by lafronzt** [docker/for-win#2401]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 8755712E-6213-4B45-BC4C-92B1E5BA3535/20180808144742

### Expected behavior

To switch from Docker Windows Containers to Docker Linux Containers

### Actual behavior

Unable to destroy: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Invalid class 

   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.<>c__DisplayClass25_0.<SwitchDaemon>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 275
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

### Information

  - Windows Version: Windows 10 Pro (Version 1709 - OS Build 16299.551)
  - Docker for Windows Version: 18.06.0-ce-win72 (19098)

### Steps to reproduce the behavior

  1. Start docker.
  2. Add the proxy settings, have docker restart.
  3. Switch Docker to Linux Containers
  4. Docker throws the error above.

**Comment by lafronzt** [comment]
I tried following the solution [here](https://github.com/docker/for-win/issues/436#issuecomment-316704346) to no avail.

Issue: #436 is similar but does not seem to provide a clean working solution or workaround.

**Comment by jasonbivins** [comment]
@lafronzt   This error usually means that there is a corrupt or invalid Powershell module

https://superuser.com/questions/1152280/get-net-powershell-cmdlets-failing-with-invalid-class

**Comment by lafronzt** [comment]
@jasonbivins I tried that, and it still does not work.

**Comment by kimjeff49** [comment]
I'm getting the same exact problem.

Couple of the people at my company had the same issue and had to downgrade to a lower version, but I'm not particularly sure what version of Docker that is.

**Comment by kimjeff49** [comment]
@lafronzt I found a workaround that might be a solution but I'm still testing its viability and have been getting blocked by my company proxy for a couple of things so I haven't gotten too far, but, what I did was I went into C:\Program Files\Docker\Docker\resources and found the MobyLinux.ps1 file : 


![pic1](https://user-images.githubusercontent.com/42388571/44154992-18a481bc-a07a-11e8-93b1-8ab594142486.PNG)


and opened the MobyLinux.ps1 file in Notepad++, found ErrorActionPreference and changed it from "Stop" to "SilentlyContinue"

![image](https://user-images.githubusercontent.com/42388571/44155087-4fa33690-a07a-11e8-9903-36017e289ad2.png)

Hope this will help, and if it does please let me know so I can tell my team!

**Comment by lafronzt** [comment]
@kimjeff49 Oh thanks. I will have to try this.

**Comment by cancerts** [comment]
switch from Docker Windows Containers to Docker Linux Containers failed ， is  any  solution effctive ? I double the hyper-v of microsoft  want fix our in his service !!!

**Comment by kimjeff49** [comment]
@cancerts I haven't had an issue pulling images and spinning up containers with my workaround yet, so it seems like a tenable solution if you would want to try it.
