### ISSUE TITLE
Hardware assisted virtualization and data execution protection must be enabled in the BIOS. (An error occurred)

### ISSUE THREAD

**Issue by sl5net** [docker/for-win#2403]
Docker says: An error occurred: Hardware assisted virtualization and data execution protection must be enabled in the BIOS. See https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization-must-be-enabled

### Expected behavior
started docker for Windows

### Actual behavior
click docker for Windows
wait update to new docker version is finished.
read/check the doku at 
1) https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization-must-be-enabled
becouse of error message: 
Hardware assisted virtualization and data execution protection must be enabled in the BIOS. See 
1) https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization-must-be-enabled

### Information
i see no difference beetween my configuration and screenshots at 1)

  - Is it reproducible?
yes

  - Is the problem new?
i dont thinks so.

  - Did the problem appear with an update?
probably it was there before. i dont know. docker asked me to update. i did it first.

  - A reproducible case if this is a bug, Dockerfiles FTW.
what do you mean by FTW?

  - Windows Version:
10 64bit

  - Docker for Windows Version:
Windows 10 10.0

![2018-08-09 07_51_57-error](https://user-images.githubusercontent.com/5634759/43880889-8b2a228e-9baa-11e8-9295-ac5d1ca60ad9.jpg)
![2018-08-09 07_50_38-table awaiting action](https://user-images.githubusercontent.com/5634759/43880913-a4778358-9baa-11e8-9b77-4f8ed9890bd8.jpg)
![2018-08-09 07_50_20-table awaiting action](https://user-images.githubusercontent.com/5634759/43880914-a493f1c8-9baa-11e8-8f70-a37febed7b08.jpg)

**Comment by sl5net** [comment]
![2018-08-09 08_06_58-table awaiting action](https://user-images.githubusercontent.com/5634759/43881079-4da3827e-9bab-11e8-9e67-a5f0a099ff7b.jpg)

**Comment by sl5net** [comment]
solved by:
Disabling Hyper-V + restarting Windows and then enabling it back

**Comment by TeraMervyn** [comment]
Had the same problem and I solved it by opening Powershell (Admin) and enter the following script:

dism.exe /Online /Enable-Feature:Microsoft-Hyper-V /All

Then restart docker.

**Comment by tsm91** [comment]
solved by enabling virtualization in BIOS advanced CPU settings

**Comment by cftang0827** [comment]
Solved by enabling Data execution prevention (DEP)
According to the link: https://www.online-tech-tips.com/windows-xp/disable-turn-off-dep-windows/

**Comment by tag** [comment]
To help others that come to this issue seeking answers, [this StackOverflow solution](https://stackoverflow.com/a/39989990/1327983) has helped many.

And while I'm here, I'll mention again how nice it would be if the error message were more specific as to the root cause. I've needed to help several dozen students with failed Docker installs this past month; all had Hyper-V enabled but were still seeing this error message.
