### ISSUE TITLE
Drives will not be shared in Docker, Windows 10 Eductation

### ISSUE THREAD

**Issue by microkid** [docker/for-win#2405]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Everything should work without problems
### Actual behavior
Docker crashes, and drives will not be shared
### Information

  1. Click to share.
2. Apply, and enter user details - click ok.
3. Box is now still unshared.

Log: see attached file
[docker_log_andreas.txt](https://github.com/docker/for-win/files/2273506/docker_log_andreas.txt)

**Comment by jasonbivins** [comment]
Hi @microkid  Are you seeing any other errors?  The logs are showing that Hyper-V isn't able to start

```

Kan ikke starte den virtuelle maskinen MobyLinuxVM fordi Èn av Hyper-V-komponentene ikke kj¯rer.

MobyLinuxVM kan ikke startes. (ID for virtuell maskin 734A5ACC-DCB2-43D6-A353-8C54D80FBC95)

Tjenesten Virtual Machine Management kan ikke starte den virtuelle maskinen MobyLinuxVM fordi Èn av Hyper-V-komponentene ikke kj¯rer```
