### ISSUE TITLE
[18.06] kubectl: error: open P:\/.kube/config: The system cannot find the path specified

### ISSUE THREAD

**Issue by lystor** [docker/for-win#2406]
- [x] I have tried with the latest version of my channel (Stable or Edge)

### Information
  - Windows Version: 18.06
  - Docker for Windows Version: 1803.17134.167

kubectl doesn't work because it tries to open .kube/config using env variables HOMEDRIVE and
HOMEPATH but docker generates this configuration file in C:\Users\<username>\.kube\config (env USERPROFILE)

```
# kubectl get pods
error: open P:\/.kube/config: The system cannot find the path specified.

> kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
error: open P:\/.kube/config: The system cannot find the path specified.
```

```
> set
HOMEDRIVE=P:
HOMEPATH=\
HOMESHARE=\\ks1\Users\NikolayU
USERPROFILE=C:\Users\nikolayu
```

```
> dir C:\Users\nikolayu\.kube\config
08/09/2018  03:30 PM             4,105 config
```

```
> dir P:
empty dir
```

Please fix this bug (use USERPROFILE env variable instead of HOMEDRIVE and
HOMEPATH).

Thank you

**Comment by thaJeztah** [comment]
ping @silvin-lubecki @simonferquel PTAL

**Comment by lystor** [comment]
With default values kubectl works as expected:
```
HOMEDRIVE=C:
HOMEPATH=\Users\nikolayu
```

Out sysadmins change HOMEDRIVE and HOMEPATH in Active Directory.

**Comment by mat007** [comment]
@lystor what is the behaviour you're expecting?
Option 1: `config` in `C:\Users\nikolayu\.kube` is fine and `kubectl` must be able to find it
Option 2: `config` should be written by Docker Desktop in `P:\.kube\config`
Also, where is your `.docker` located? `C:\Users\nikolayu\.docker` or `P:\.docker`?

I believe a workaround for the time being would be to set `KUBECONFIG` to `%USERPROFILE%\.kube`

**Comment by lystor** [comment]
> what is the behaviour you're expecting?

Option 1

> Also, where is your .docker located? C:\Users\nikolayu\.docker or P:\.docker?

.docker is located inside C:\Users\nikolayu\
P:\ doesn't have any system files and used to share files between users in lan.

**Comment by mat007** [comment]
I suggest you open an issue in the kubectl project then, see https://github.com/kubernetes/kubectl and/or set `KUBECONFIG` to override the default?

**Comment by lystor** [comment]
> I suggest you open an issue in the kubectl project then

OK. Thank you
