### ISSUE TITLE
Crash on statup

### ISSUE THREAD

**Issue by johnweland** [docker/for-win#2436]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 041097A8-BB44-433B-8AF2-8789E88C0340/20180815093745

### Expected behavior
Docker starts up

### Actual behavior
Docker does not startup

### Information

  - Windows Version: 10 Pro version 1803 build 17134.165
  - Docker for Windows Version: 18.06.0-ce

### Steps to reproduce the behavior

  1. I have formatted the PC and reinstalled Docker
  2. Docker starts up and prompts for Hyper-V
  3. Hyper-V installs and system reboots
  4. Docker crashes when starting up after Hyper-V is installed.

**Comment by BlackFrog1** [comment]
When your docker crashes, do you get the dialog to reset to factory defaults?
