### ISSUE TITLE
Using docker without HyperV

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [docker/for-win#2451]
Actually, I am using Android Studio and its emulators with Intel HAXM, the problem is it can't work with HyperV.

Then you can say: you should use HyperV with the Android emulator instead of Intel HAXM... well the performance is a REALLY trash compared with Intel HAXM. The emulator is pretty slow with HyperV.

So I have to literally disable and enable HyperV (and rebooting...) when I want to develop with an Android emulator.

Any suggestion to avoid using HyperV with Docker?

**Comment by ipv1337** [comment]
I've been looking around for this answer as well. So far I've had to resort to using Docker Toolbox, but that seems like a really dated approach.

**Comment by JavierSegoviaCordoba** [comment]
@ipv1337 that software is not deprecated?

**Comment by fingera** [comment]
+1

**Comment by ipv1337** [comment]
> @ipv1337 that software is not deprecated?

It was still around and usable when I left the comment almost a year ago, but I've since moved back to using Virtualbox since I've converted my home workload to k8s and wanted more control of my environment.

**Comment by mikeparker** [comment]
Windows container mode doesn't use Hyper-V, can you use Windows containers instead?
