### ISSUE TITLE
Fresh install of Docker fails with the error [Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The object already exists.]

### ISSUE THREAD

**Issue by AshwinJGitHub** [docker/for-win#2453]
- [X] I have tried with the latest version of my channel (Stable)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 
[20180818031508.zip](https://github.com/docker/for-win/files/2298843/20180818031508.zip)

### Expected behavior
Uninstalled Docker, Restarted, Fresh Install of Docker should have started Docker normally

### Actual behavior
Crashes with the following error message: 
```
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The object already exists.


   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 77
   at Docker.Actions.<>c__DisplayClass18_0.<ResetToDefault>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 137
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```
### Information

  - Windows Version: Microsoft Windows 10 Enterprise 10.0.17134
  - Docker for Windows Version: 18.06.0-ce-win72 (19098)

### Steps to reproduce the behavior

  1. Uninstall Docker
  2. Restart 
  3. Clean install of Docker (Do not check Windows Container option)

Results in the errors above and there is no VM in the Hyper-V Manager

**Comment by v9Chris** [comment]
Not sure what fixed it, but i basically tried everything under the sun and then  finally got it to work by running netcfg -d to nuke my network config and restarted my machine.

**Comment by DmytroStognii** [comment]
I have the same issue for Windows 10, but nothing helped: reboot, restart, re-install, "netcfg -d"...

**Comment by Filipedguy** [comment]
If you want to solve your docker right away, you can run those commands in powershell:

```powershell
$ipAddress = Get-NetIPAddress -IPAddress 10.0.75.1
$netAdapter = Get-NetAdapter | ? { $_.InterfaceIndex -eq $ipAddress.ifIndex }
$netAdapter | Remove-NetIPAddress -IPAddress 10.0.75.1 -Confirm:$false
```

**Comment by Filipedguy** [comment]
huytnd, Ive got some other issues that don't solve with this command... This problem happens when the docker is trying to create the MobyLinux Vm on Hyper-V... you can debug the powershell script(MobyLinux.ps1) and see where It breaks.

**Comment by rsvenkata** [comment]
This is for fixing the issue to start docker on Windows Pro.

https://github.com/docker/for-win/issues/1538#issuecomment-383536985

**Comment by falco467** [comment]
I had the same problem and the solution was to change a windows-security setting, which was auto-enabled with the last update: https://social.technet.microsoft.com/Forums/en-US/ee5b1d6b-09e2-49f3-a52c-820aafc316f9/hyperv-doesnt-work-after-upgrade-to-windows-10-1809?forum=win10itprovirt
