### ISSUE TITLE
Win32: WaitForDebugEvent null hFile.

### ISSUE THREAD

**Issue by OpenCppCoverage** [docker/for-win#2455]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
 [WaitForDebugEvent](https://msdn.microsoft.com/fr-fr/library/windows/desktop/ms681423(v=vs.85).aspx) Win32 function should have the same behavior on Docker and on Windows.

### Actual behavior
On Docker, ``WaitForDebugEvent`` returns null hFile. 

### Information

  - Windows Version: 10 Pro
  - Docker for Windows Version: Version 18.06.0-ce-win72 (19098)
  - Is it always reproducible.

[WaitForDebugEvent.zip](https://github.com/docker/for-win/files/2299648/WaitForDebugEvent.zip)

See file ``WaitForDebugEvent.cpp`` for a full example.  Running this code (WaitForDebugEvent.exe) on docker failed with ``hFile is null``. 

``hFile`` field inside [CREATE_PROCESS_DEBUG_INFO](https://msdn.microsoft.com/fr-fr/library/windows/desktop/ms679286(v=vs.85).aspx) or [LOAD_DLL_DEBUG_INFO](https://msdn.microsoft.com/fr-fr/library/windows/desktop/ms680351(v=vs.85).aspx) is null on Docker but not on Window.

### Steps to reproduce the behavior

  1. Unzip WaitForDebugEvent.zip
  2. Run ``docker build -t test .``
  3. Run ``docker run test:latest``
The output is:
```
Process started
LOAD_DLL_DEBUG_EVENT
hFile is nullLOAD_DLL_DEBUG_EVENT
```

If you run ``WaitForDebugEvent.exe cmd`` on Windows10 you have instead.
```
Process started
LOAD_DLL_DEBUG_EVENT
LOAD_DLL_DEBUG_EVENT
LOAD_DLL_DEBUG_EVENT
LOAD_DLL_DEBUG_EVENT
LOAD_DLL_DEBUG_EVENT
LOAD_DLL_DEBUG_EVENT
LOAD_DLL_DEBUG_EVENT
LOAD_DLL_DEBUG_EVENT
LOAD_DLL_DEBUG_EVENT
LOAD_DLL_DEBUG_EVENT
LOAD_DLL_DEBUG_EVENT
LOAD_DLL_DEBUG_EVENT
LOAD_DLL_DEBUG_EVENT
LOAD_DLL_DEBUG_EVENT
LOAD_DLL_DEBUG_EVENT 
```

Is it a Docker issue or a Docker image (microsoft/powershell) issue?

Please let me know if you need additional information.

**Comment by ebriney** [comment]
Hi @OpenCppCoverage, seems to be like a tricky low level issue :)
As far as it concerns Windows containers issue you must file an issue in https://github.com/moby/moby/issues (adding the prefix WCOW will help triaging).
Thanks.

**Comment by OpenCppCoverage** [comment]
Hi,

Thank you for your answer and advice.
I have created https://github.com/moby/moby/issues/37744. 

OpenCppCoverage
