### ISSUE TITLE
Accessing SQL Server in container too slow.

### ISSUE THREAD

**Issue by st2forget** [docker/for-win#2458]
Here is how I start sql server container:
```
docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=P@ssword123" --name mssql -p 1434:1433 -d microsoft/mssql-server-linux
```

I use MS SQL Management Studio 2017 to connect to an instance in the host machine and query data really fast. But connecting & querying to Docker Sql Server is too slow. Is there anything related to the hyperV virtual switch? Can I do something to boost the performance?

EDITED:
- Querying data inside a container itself is fast. I entered the container and use sqlcmd to query data and it is good
- Using MS SQL Management Studio to connect to container and query data using same query as above is too slow.

**Comment by ashamnx** [comment]
@st2forget did you manage to find any solution? I am experiencing a slow down when querying with msssql php driver.

**Comment by mariokom** [comment]
Same issue here. I am interested in the solution, if you found one.

**Comment by kevin2fly** [comment]
Exactly the same issue here. Have you found any solution?
