### ISSUE TITLE
Do not create a shortcut to Docker on the user's desktop

### ISSUE THREAD

**Issue by oliversalzburg** [docker/for-win#246]
**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 317
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 155
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.19-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: OV6J:OPDY:DVEB:U2KO:DISY:YJAH:3BIO:RITP:KJQY:T5KS:5U3R:RKFK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Install Docker for Windows or apply an update for Docker for Windows

**Describe the results you received:**
The installer will create a shortcut for Docker for Windows on my desktop.

**Describe the results you expected:**
The installer won't create a shortcut on my desktop.

Please note that this is even a point Microsoft is talking about themselves in the [Windows Application Design Guidelines](https://msdn.microsoft.com/en-us/library/windows/desktop/dn742493.aspx):
> **If you do only one thing...**
Don't abuse the desktop—keep users in control. If your target users are likely to use your program frequently, provide an option during setup to put a shortcut on the desktop, unselected by default.

That being said, I don't really understand why this is done/offered *at all*. If someone is capable of using Docker, I'm sure they're capable of dragging and dropping a shortcut to their desktop if they feel inclined to do so.  
The application that is started through the shortcut is, by default, also automatically started when Windows starts, making the existence of the shortcut even more pointless and this use case does not satisfy the "frequently used" requirement IMHO.

**Comment by Schweinepriester** [comment]
+1

**Comment by rneugeba** [comment]
@oliversalzburg Thanks for reporting here. 
@simonferquel could you take a look if we can make this optional in the installer?

**Comment by simonferquel** [comment]
Won't do before we use the new fancy installer infrastructure :(

**Comment by dgageot** [comment]
@oliversalzburg @Schweinepriester To be clear, we find that annoying too. I think it's one of the first tickets @rneugeba created on the project last February. The reason we didn't fix it is that the tool we use to build our installer doesn't support that.
Until docker 1.13 is GA, we are not going to change the installer.
However, after 1.13 is GA, one of the first things we are going to deploy on the Beta channel, is a fresh new, lightweight, installer which will support this feature.

**Comment by oliversalzburg** [comment]
Ah, I see. Thanks for the update :)

**Comment by mi-hol** [comment]
I'm on stable channel hence wonder @dgageot is there any news ?

**Comment by oliversalzburg** [comment]
Any chance this will be tackled at some point in time?

**Comment by oliversalzburg** [comment]
Still happening and I still care about it :P Very annoying

**Comment by wilferraciolli** [comment]
Fix please

**Comment by collinsauve** [comment]
+1 million.

**Comment by oliversalzburg** [comment]
I see that this is now an option during installation. Still checked by default, but the option is there. Good job.

Let's see how it behaves during the next update.

**Comment by rn** [comment]
Oh, I see this is still open. Should have closed it.

**Comment by oliversalzburg** [comment]
Aaaaaand it's back again! \o/

**Comment by oliversalzburg** [comment]
One of the biggest challenges in computing history: Keep the Docker for Desktop team from creating desktop shortcuts.
