### ISSUE TITLE
Cannot start kubernetes on windows

### ISSUE THREAD

**Issue by ghost** [docker/for-win#2472]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BC62717E-9B35-482D-BB3E-3AB95AC58570/20180821193003

### Information

  - Windows Version: windows 10 1803
  - Docker for Windows Version: docker for win 18.06.0-ce-win72

### Steps to reproduce the behavior

stuck in "kubernetes is starting" for hours, I uninstall / reinstall docker for windows several times, but cannot get it works.

**Comment by edo386** [comment]
I'm having a related issue, but I'm trying to disable verbose on docker demon (and it's not working) can reproduce the same error "The specified service already exists." by setting debug -> false in the json config, try to check if you have it false.

**Comment by anwalkers** [comment]
Diagnostic ID: 51BE916F-11C1-4855-9037-9EE0541E1A40/20180904163640

Same issue on the "edge" version of docker. Going back to minikube...

**Comment by VenkateshSrini** [comment]
Hi All,
I have found a solution for this. The one that worked for me was to reset the docker to factory settings. Then delete the .kube directory in C:\Users\<<username>>\.kube. Then we need to re-install Kubernetes.

I hope this is useful for all
