### ISSUE TITLE
Docker crashes after every reboot; have to reset to factory defaults

### ISSUE THREAD

**Issue by BlackFrog1** [docker/for-win#2474]
- [x] I have tried with the latest version of my channel Stable
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 669B6425-92FF-474F-A6EE-5D3E25E121C2/20180821211138

### Expected behavior
Every time I reboot my machine, I don't have to Reset to factory defaults.

### Actual behavior
After installation or resetting to factory defaults, I create and run any containers I like.  But when I restarted, I have been getting an error.

### Information
  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior
  1. I am currently logged in as a regular user on Windows
  2. When I start Docker for Windows, I start as an elevated user
  3. I create images, containers, network.
  4. I can run multiple containers
  5. Reboot the computer.
  6. Restart Docker for Windows as elevated user
  7. Error message; asks me to reset

**Comment by uzi0espil** [comment]
I faced something similar. At first Docker was working perfectly for me. Then I changed the windows language and then whenever I restarted my PC it crashes.. I solved it by reset to factory default in Docker.

**Comment by BlackFrog1** [comment]
Yes, when I reset to factory everything works again.  But I lose the images and containers I had.

Here is my latest error on the Edge branch:
  - Diagnostics ID: 669B6425-92FF-474F-A6EE-5D3E25E121C2/20180824211445
