### ISSUE TITLE
What properties of "firewall settings" should I change to share the drive??

### ISSUE THREAD

**Issue by tetsu61** [docker/for-win#250]
### Expected behavior
Change settings about "Shared Devices"
Complete to share the drive, allow connections between the Windows host machine and the virtual machine 

### Actual behavior
Unable to change settings about "Shared Devices" 
Get a message that says "Firewall detected"

### Information

  - Diagnostic ID : A3787F3B-EF6E-409A-8A18-87C4D981DE22/2016-11-24_11-43-32
  - Windows 10 enterprise
  - Docker version 1.12.3, build 6b644ec, experimental
  - https://docs.docker.com/docker-for-windows/#/firewall-rules-for-shared-drives/
    I referred this page, but I didn't know what  I should change the properties of my firewall settings.  

### Steps to reproduce the behavior

  1. Right click the docker's icon in the system tray 
  2. Select "Shared Drives" and check a box of  the Drive list
  3. Click "Apply"

**Comment by rneugeba** [comment]
@tetsu61 For volume sharing we must be able to connect to TCP port 445 for SMB/CIFS mounting. If you use the standard Windows firewall, you can check/change the setting in Advanced Firewall Settings, Inbound Rules, File and Printer Sharing (SMB-in).

**Comment by dgageot** [comment]
@amalm @pmsousa Beta 31 was just released with a fixed documentation url. Does it help?

**Comment by dgageot** [comment]
@tetsu61 Beta 31 was just released with a fixed documentation url. Does it help?

**Comment by dgageot** [comment]
I'm going to close this issue, has it seems the fixed documentation is enough now.
