### ISSUE TITLE
Volumes not propagating change events

### ISSUE THREAD

**Issue by Sub-Xaero** [docker/for-win#2502]
It has nearly been a year since there has been any visible movement on the Docker for Windows issue where filesystem events on the host are not replicated in the container, and the main issue ticket remains closed https://github.com/docker/for-win/issues/56, while it is clearly still an issue.

I am fully aware of https://github.com/merofeev/docker-windows-volume-watcher as a workaround, but it is beyond irritating having to have this CPU intensive script polling away in the background, as it often crashes and closes itself and has to be reopened and is generally just a poor hack. 

There have since been multiple updates to Windows Subsystem for Linux, and Linux Containers on Windows has been a feature for many months now, which was hailed as the saving grace for this problem https://github.com/docker/for-win/issues/56#issuecomment-342622084. 

Is there any news or progress on this issue?

**Comment by robertdumitrescu** [comment]
Amazing how much time was that ignored. I might switch back to Linux, too many annoyances on Windows. Will wait 2-3 more years and try again then.

**Comment by Sub-Xaero** [comment]
And haven't even gratified us with a response.
Just plain ignore the issue, that will make it go away 👍

Only reason I'm still using Windows is for the gaming. As soon as all the blockbuster games are playable on Linux, I'm dropping Windows like it's hot.
