### ISSUE TITLE
Docker won't start, even with new installation, error code 32788

### ISSUE THREAD

**Issue by treyharris** [docker/for-win#2503]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 97B5EDB7-FDB5-41AC-A19A-1A4509E3E7E3/20180829170234

### Expected behavior
Docker starts

### Actual behavior
Docker fails to start, with "An error occurred" window containing:
```
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to change state.

The operation failed with error code '32788'.
at Start-MobyLinuxVM, <No file>: line 300
at <ScriptBlock>, <No file>: line 395
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 77
   at Docker.Actions.<>c__DisplayClass16_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 61
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```

### Information

  - Windows Version: Windows 10 Pro, 64-bit
  - Docker for Windows Version: 18.06.0-ce-win72 (19098)

The problem appeared within the past 2 weeks (I noticed it on login, but didn't have time to look into it immediately); Docker had been running normally for several months prior to that time with no issue. It may have been related to an automatic update install.

Note that suggested troubleshooting solutions involving deleting all Hyper-V network adapters and other resources are not workable for me, as I already have an Ubuntu VM running in Hyper-V.

### Steps to reproduce the behavior

  1. Start Docker.

Or:

  1. Start Docker
  1. After getting error, "Reset to factory defaults" and try again

Or:

  1. Uninstall Docker.
  2. Download new Docker from Docker Store.
  3. Install new installation of Docker.
  4. Start new installation of Docker.

**Comment by menmikimen** [comment]
How much RAM have you assigned to your Docker VM?
I had a similar problem and managed to solve it by lowering RAM consumed by Hyper-V machines (docker included).

**Comment by crld** [comment]
@menmikimen thanks for that suggestion that ended up working for me as well; this happened when I tried to bump the ram/cpu for docker

**Comment by TsuyoshiUshio** [comment]
Just my workaround. 
After encounter this issue, 
I go to Hyper-V Manager and go to MobyLinuxVM then I enable Dynamic Memory. Then it works. :)
