### ISSUE TITLE
Refuses to start

### ISSUE THREAD

**Issue by csharpfritz** [docker/for-win#2506]
After installing 18.06.1-ce-win73 (19507) on the stable channel, I can no longer get Docker for Windows to start for me.

I have rebooted several times and am looking for next steps to diagnose and fix the issue, short of uninstalling and rebuilding

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mat007** [comment]
For us to investigate you would need to upload a set of diagnostics, following the steps at https://docs.docker.com/docker-for-win/troubleshoot.

**Comment by csharpfritz** [comment]
I did upload the diagnostics, but didn't grab the id...

I uninstalled, reinstalled and everything works now.


Jeff

**Comment by mat007** [comment]
Thanks, I'll just go ahead and close this issue then.
If this happens again feel free to open a new one.
