### ISSUE TITLE
Support for arbitrary mounts onto the Docker for Windows VM

### ISSUE THREAD

**Issue by caylorme** [docker/for-win#251]
### Expected behavior
The ability to Share a network mapped drive through the Docker for Windows Settings' Shared Drives section.

### Actual behavior
Only phyiscally attached drives are showing up

### Information

  - Cannot mount smb/cifs shares to the MobyLinuxVM in HyperV
  - This sucks if you are working from a mapped network drive
  - No way to do this ourselves because we do not have an interface for it
  - Docker CP will not solve the problem (Think build system...)

### Steps to reproduce the behavior

 1. Map a network Drive in Windows ([How?](http://www.dummies.com/computers/operating-systems/windows-7/how-to-map-a-network-folder-in-windows-7/))
 2. Visit the Shared Drives section of the Docker for Windows Settings ([How?](https://docs.docker.com/docker-for-windows/#/docker-settings))
 3. Notice the lack of existence for your mapped drive.

Hello,

I'd like to be able to create arbitrary, yet explicit,  mounts that are accessible via the docker client for the HyperV virtual machine (MobyLinuxVM).

For example:

I work from my desktop through a mounted volume. I have a mapped network drive (Z:), and I use git-bash/powershell to execute the docker client binary against the virtual host's docker daemon. My working (code) directory exists in the mapped drive. There is no option in the Docker Settings' Shared Drives section to share this mapped drive. I realize that the drives are made available to the virtual host as a smb / cifs share where it is mounted as, say for instance, "/c" -- where c is the drive letter so that it maps with the actual host's drive.

My request is to allow for volume mounting to the virtual machine through some means. If I had shell access to the MobyLinuxVM I would certainly attempt to add the drive myself to determine if that would in fact solve my problem.

The fact that I see this in the logs indicates that there is already an API that allows us to interact with the virtual machine and add mounts. We now simply need an addition to the interface (or SSH / Terminal Access) to allow us to define mounts and other parameters.
```
[22:09:37.942][DockerDaemonChecker][Info   ] Docker daemon is running
[22:09:37.952][NamedPipeServer][Info   ] Start done.
[22:09:37.956][NamedPipeClient][Info   ] Received response for Start
[22:09:38.009][NamedPipeClient][Info   ] Sending Mount(C, domain\username**********, Docker.Core.Settings)...
[22:09:38.015][NamedPipeServer][Info   ] Mount(C, domain\username:**********, Docker.Core.Settings)
[22:09:38.021][SambaShare     ][Info   ] Mount C
[22:09:38.051][Cmd            ][Info   ] Share name        C
[22:09:38.056][Cmd            ][Info   ] Path              C:\
[22:09:38.059][Cmd            ][Info   ] Remark            
[22:09:38.063][Cmd            ][Info   ] Maximum users     No limit
[22:09:38.067][Cmd            ][Info   ] Users             
[22:09:38.070][Cmd            ][Info   ] Caching           Caching disabled
[22:09:38.073][Cmd            ][Info   ] Permission        domain\username, FULL
[22:09:38.077][Cmd            ][Info   ] 
[22:09:38.081][Cmd            ][Info   ] The command completed successfully.
[22:09:38.085][Cmd            ][Info   ] 
[22:09:38.089][SambaShare     ][Info   ] "C" is shared
[22:09:38.270][SambaShare     ][Info   ] Username: username
[22:09:38.274][SambaShare     ][Info   ] Host IP: 10.0.75.1
[22:09:38.278][SambaShare     ][Info   ] Cifs options: noperm,iocharset=utf8,nobrl,mfsymlinks,vers=3.02,domain=domain
```

**Comment by rneugeba** [comment]
@caylorme thanks for your report. @simonferquel do you think we can add this feature? I don't think we can re-export and network share and then mount it, but we could try to provide the ability to mount network shares. The main issue I see would be if the network share requires different credentials...

@caylorme In the meantime you can get shell access with `nsenter` and something like:
```
docker run --rm --privileged --pid=host -ti justincormack/nsenter1 /bin/sh
```

**Comment by caylorme** [comment]
@rneugeba, thanks for the tip and for the initial triage.

My idea on the credentials would be a different format for authenticating. Or, instead of doing a single authentication object that is associated with every disk (probably okay for physically mounted disks), we could modify the current behavior to have  per-disk authentication objects.

Originally I was thinking something, similar to how we pass configuration parameters to the Docker daemon, like a JSON object that contains arrays of smb mounts. It would be nice, however, to abstract this to a nice GUI interface, I was just thinking of a quicker more versatile solution.

I would love to get involved in this, if there is any way I can help, let me know.
I'm assuming the interface is not open source... but what about the API that we are currently interfacing with to do the initial physical disk mounts? I know we probably communicate with some of the local host (windows) API to ensure the share to C is there with proper permissions, but are there any additional modifications that would need to be made to that? And... is that a part of the same project?


## Happy Thanksgiving!

**Comment by caylorme** [comment]
On a separate note,

@rneugeba, I have the drive mounted as /z/ on the VM now, but the client still tells me that the drive is not shared. Are you aware of a way to make the client believe the drive is shared?

**Comment by rneugeba** [comment]
Sorry, I forgot about the check for mounted volumes. We added this as we had seen many issues with users not sharing their volume.

The check looks for patters like `c:` at the start of the volume string. However, if you mounted your driver in the VM as `/z` then you should be able to circumvent the check by specifying the volume mount like this: `docker run --rm -ti -v /z:/foo alpine ls /foo`.

Does this work for you?

**Comment by caylorme** [comment]
@rneugeba, I tried this. After mounting the share to /z and /Z within the virtual machine, I attempted to use the docker client from my host (not from within the VM) and received this message:
### Windows Host
```
me@MY-PC MINGW64 /z/code/go/src/codewebsite/user/project1 (master)
$ docker run -it --rm -v "$PWD":/tmp alpine ash

C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: Z: drive is not shared. Please share it in Docker for Windows Settings.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
```
### Docker VM

```
/ # mount
tmpfs on / type tmpfs (rw,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /run type tmpfs (rw,nodev,relatime,size=201176k,mode=755)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
cgroup_root on /sys/fs/cgroup type tmpfs (rw,nosuid,nodev,noexec,relatime,size=10240k,mode=755)
openrc on /sys/fs/cgroup/openrc type cgroup (rw,nosuid,nodev,noexec,relatime,release_agent=/lib/rc/sh/cgroup-release-agent.sh,name=openrc)
cpuset on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cpu on /sys/fs/cgroup/cpu type cgroup (rw,nosuid,nodev,noexec,relatime,cpu)
cpuacct on /sys/fs/cgroup/cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpuacct)
blkio on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
memory on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
devices on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
freezer on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
net_cls on /sys/fs/cgroup/net_cls type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls)
perf_event on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
net_prio on /sys/fs/cgroup/net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_prio)
hugetlb on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
pids on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
dev on /dev type devtmpfs (rw,nosuid,relatime,size=10240k,nr_inodes=244136,mode=755)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime)
tracefs on /sys/kernel/debug/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
/dev/sda2 on /var type ext4 (rw,relatime,data=ordered)
db on /Database type 9p (rw,sync,dirsync,relatime,trans=fd,dfltuid=1001,dfltgid=50,version=9p2000,msize=4096,rfdno=5,wfdno=5)
port on /port type 9p (rw,sync,dirsync,relatime,trans=fd,dfltuid=1001,dfltgid=50,version=9p2000,msize=4096,rfdno=5,wfdno=5)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,relatime,name=systemd)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
/dev/sda2 on /var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
//10.0.75.1/C on /c type cifs (rw,relatime,vers=3.02,sec=ntlmssp,cache=strict,username=myuser,domain=mydomain,uid=0,noforceuid,gid=0,noforcegid,addr=10.0.75.1,file_mode=0755,dir_mode=0755,iocharset=utf8,nounix,serverino,mapposix,nobrl,mfsymlinks,noperm,rsize=1048576,wsize=1048576,actimeo=1)
//10.0.75.1/C on /C type cifs (rw,relatime,vers=3.02,sec=ntlmssp,cache=strict,username=myuser,domain=mydomain,uid=0,noforceuid,gid=0,noforcegid,addr=10.0.75.1,file_mode=0755,dir_mode=0755,iocharset=utf8,nounix,serverino,mapposix,nobrl,mfsymlinks,noperm,rsize=1048576,wsize=1048576,actimeo=1)
none on /var/lib/docker/aufs/mnt/9921ea757ef23fa7c3fe50f352e157f8c182d7104d410ea810d99a9369094d66 type aufs (rw,relatime,si=d41ae9d6961e9a2,dio,dirperm1)
shm on /var/lib/docker/containers/eb453c93f131150830274bd2e8c94d1349f0c717b61c2e104a67aef4a9aa0516/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /run/docker/netns/5b9e61b16fe1 type nsfs (rw)
//domain-controller.mydomain.com/ShareName on /z type cifs (rw,relatime,vers=1.0,cache=strict,username=myuser,domain=mydomain,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.1.3,file_mode=0755,dir_mode=0755,nounix,serverino,mapposix,rsize=61440,wsize=16580,actimeo=1)
```

**Comment by caylorme** [comment]
## Update
It seems like I only run into this when dealing with actual drives known to the client?
Check this out, if I mount my smb/cifs share to "/test" on the Virtual Machine, and reference that in the client instead of the current working directory, it works just fine.
This will be a decent workaround for now. If anyone is willing to look into this and help come up with a solution, please feel free to comment.

### MobyLinuxVM
```
 mount -t cifs //domain-controller1/MyShare /test -o user=myuser,domain=mydomain,vers=3.02,sec=ntlmssp,cache=strict,nounix,mfsymlinks,noperm,nobrl,mapposix
```

### Docker Client
```
docker run -it --rm -v "/test":/tmp alpine ls -lash /tmp
go      python
```

**Comment by msnelling** [comment]
An ideal solution would be to have the ability to mount network shares directly in the UI, not just mapped shared drives.

I'm currently working around this limitation by using this container to setup the shares in the Moby host https://github.com/iRobie/moby-cifs-mount
