### ISSUE TITLE
Error: A firewall is blocking file sharing between Windows and the containers

### ISSUE THREAD

**Issue by manishtomar** [docker/for-win#2512]
@kpratihast commented on [Thu Aug 30 2018](https://github.com/docker/hub-feedback/issues/1619)

The issue of 'A firewall is blocking file sharing between Windows and the containers' still persists in Docker for Windows v18.06.1-ce. 

The below article mandates to have a previous version (17.06.0-ce-win18 12627) in order for the fix to work:
https://success.docker.com/article/error-a-firewall-is-blocking-file-sharing-between-windows-and-the-containers

Any workaround / plans to fix this issue in the latest version ?

**Comment by manishtomar** [comment]
@kpratihast Issue moved to https://github.com/docker/for-win/issues/2512

**Comment by hecsalazar** [comment]
Hello I had same issue and it was the windows firewall enforcing a global policy in corporate network. To confirm if it's the firewall please follow this procedure:

https://superuser.com/questions/1130078/how-to-tell-which-windows-firewall-rule-is-blocking-traffic

that will allow to identify if the packet is dropped or connection is blocked

I had the same issue for sharing drives:
https://github.com/docker/for-win/issues/2527
