### ISSUE TITLE
Docker for windows not able to assign more than half memory of dual cpu computer. 

### ISSUE THREAD

**Issue by phylroy** [docker/for-win#2514]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
**Note Diagnostics not working.**  See this [issue](https://github.com/docker/for-win/issues/2513)

### Expected behavior
Ability to specify memory from docker gui. 

### Actual behavior
Allocates only up to about a 1/2 of the memory of my 32GB. Instead of requested memory.  

Is this a limitation of dual cpus? I have tried to manully change the  ram allocation in the Hyper-V manager as well to no success.. It always sets to the 15404MB when I try to set it larger than that. 

### Information

  - Docker for Windows Version: Version 2.0.0.0-win81 (29211) build 4271b9e
  - Windows Version: Windows 10 v1709build 16299.655
   - HP Z840 Dual CPU system Xeon E5-2650 2 processors with 32GB RAM

### Steps to reproduce the behavior
1. Try to set ram to above 15404MB on above dual core system from Docker for Win GUI
2. Start or restart docker. 
3. Open Hyper-V manager and notice that the memory of MobyLinuxVM is set to 15404. 

Here is some more information since diagnose is broken right now...

**settings.json file**
```
{
  "VmCpus": 42,
  "VmMemory": 25856,
  "VmSwap": 4096,
  "SubnetAddress": "10.0.75.0",
  "SubnetMaskSize": 24,
  "UseDnsForwarder": true,
  "NameServer": "8.8.8.8",
  "IsTracking": true,
  "ExposeTcp": false,
  "SharedDrives": {
    "C": false
  },
  "DaemonOptionsV2": null,
  "DaemonOptions": null,
  "LinuxDaemonOptionsCreationDate": "08/30/2018 17:21:32",
  "WindowsDaemonOptionsV2": null,
  "WindowsDaemonOptions": null,
  "WindowsDaemonOptionsCreationDate": null,
  "SysCtlConf": "",
  "ExecutableDate": "",
  "AutoUpdateEnabled": true,
  "StartAtLogin": true,
  "ProxyExclude": "",
  "ProxyHttp": "",
  "ProxyHttps": "",
  "UseHttpProxy": false,
  "UseWindowsContainers": false,
  "MobyVhdPathOverride": "E:\\docker\\MobyLinuxVM.vhdx",
  "MobyVhdDiskSize": 256000000000,
  "SwarmFederationExplicitlyLoggedOut": false,
  "ActiveOrganizationName": null,
  "KubernetesEnabled": false,
  "ShowKubernetesSystemContainers": false,
  "KubernetesInitialInstallPerformed": false,
  "DisplayedLCOWInfoMessage2": false,
  "DisplayedWelcomeWhale": true,
  "DisplayedAUFSWarning": false,
  "latestBannerKey": "",
  "DisplayRestartDialog": true,
  "DisplaySwitchWinLinContainers": true,
  "Debug": false
}
```

**docker info output**
```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 4
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.93-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 42
Total Memory: 14.69GiB
Name: linuxkit-00155dc4df1a
ID: DUUW:BPLU:Y4Y2:N7IB:JR6B:NDLO:MZZD:BAYU:SKVA:OZTD:5XTA:NR2D
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 47
 System Time: 2018-08-31T16:49:34.8404729Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**daemon.json** 
```
{    
    "data-root": "E:\\docker"
}
```

**Comment by phylroy** [comment]
Tried forcing the memory to be allocated using a powershell command as admin to 20GB..Unsuccessful. 
```
PS C:\Windows\system32> Set-VMMemory -VMName MobyLinuxVM -StartupBytes 20gb
Set-VMMemory : Failed to modify device 'Memory'.
'MobyLinuxVM' failed to modify device 'Memory'. (Virtual machine ID E56CC205-CCCF-4CC5-9664-E8D3557B7AD2)
Changing memory size of running virtual machine 'MobyLinuxVM' took too long to complete. Please make sure the guest
operating system has fully booted and try again.
At line:1 char:1
+ Set-VMMemory -VMName MobyLinuxVM -StartupBytes 20gb
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-VMMemory], VirtualizationException
    + FullyQualifiedErrorId : OperationFailed,Microsoft.HyperV.PowerShell.Commands.SetVMMemory

```

**Comment by nvankaam** [comment]
I am running into the same issue with Docker CE on Windows Server 2016. The machine has 24GB of RAM, but the MobyVM never gets more than 9378MB, even though the slider accepts values over 20GB. 

When containers consume all of the 9378MB, docker and all containers become unresponsive for a couple of minutes, after which some container is killed.

Docker version: 18.06.0-ce

**Comment by phylroy** [comment]
@nvankaam out of curiosity.. Does your host computer have have two cpus? I have two Xeon E5-2650 cpus.  I am wondering if docker only sees half due to that...

**Comment by nvankaam** [comment]
@phylroy No, it had 4. I have tried configuring docker to use 1, 2 or 3 cpu's, but that didn't make a difference. 
I don't have access to the machine right now, so I can't look up the exact hardware specs.

**Comment by nvankaam** [comment]
@phylroy I just figured u meant cpu's not cores. No, the machine only had a single CPU.

**Comment by nvankaam** [comment]
@phylroy I have removed my previous comments because they were incorrect.

I have looked up the hardware specifications, and the machine I was running on actually has 4 virtual CPU's. So your feeling that it might have to do with the two CPU's might be correct.

I have also tried running the same setup on a machine which I know of having 1 physical CPU, and I was able to assign 20GB of the 32GB RAM to the docker VM

**Comment by gvbkr** [comment]
We are running into this as well. Its frustrating as our app is heavy and we cannot run it on windows for many engineers as we cannot increase the docker memory / cpu. MAC has full support to maximize the resources. Any help is greatly appreciated.

**Comment by phylroy** [comment]
Still an issue in latest versions. 
Docker for Windows Version: Version 2.0.0.0-win81 (29211) build 4271b9e
Windows Version: Windows 10 v1709build 16299.655

**Comment by ckirney** [comment]
I am having the same issue.
Docker for Windows Version: Version 2.0.0.0-Win81 (29211), build 4271b9e
Windows version:  Windows 10 Enterprise, version 1709, OS Build 16299.665
In the Docker Desktop Advanced setting I put 22784 MB (out of 30208 MB possible) however only 15640 MB is applied to MobyLinuxVM.

**Comment by rifrayugo** [comment]
@nvankaam how docker determine the cpu if we have dual cpu?i also have the same issue on windows server. I have this spec:
First CPU has 12GB of Ram
Second CPU has 4GM of Ram.
I tried to increase the memory into 8GB from Docker Desktop UI, but in Hyper-V always assign 3.3GB of Ram.

**Comment by nvankaam** [comment]
@rifrayugo Sorry, I would not know that. We ended up deploying on machines with single cpu's.

**Comment by rifrayugo** [comment]
@nvankaam ok thank you. I decide to migrate my docker to linux server.

**Comment by ndrnpr** [comment]
does anybody have a working solution to solve this issue?

if I stop DockerDesktopVM and then set memory limit to a value above the half of total host's value it then starts succesfully, but connection between docker daemon and linux vm seems to be broken. Then when I restart Docker from it's standard dialogs, a memory limit equal to an half of host's total value is assigned again.
