### ISSUE TITLE
Docker crash while PC starts

### ISSUE THREAD

**Issue by Nextarius** [docker/for-win#2519]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F50AE9BC-A317-4E15-A5E0-73378B8EC78C/20180831100354

### Expected behavior
Docker should start without failing.

### Actual behavior
Docker crash while starting PC.

### Information

  - Windows Version: 1803 (Build 17134.228)
  - Docker for Windows Version: 18.06.1-ce-win73 (19507) stable

### Steps to reproduce the behavior

  1. Start PC
  2. Error happen

**Comment by harrisdt15f** [comment]
![img_20180901_145646](https://user-images.githubusercontent.com/27404296/44943356-aca7b700-adf7-11e8-9e3d-72b35a425e99.jpg)
I cannot install docker need help.

**Comment by Nextarius** [comment]
Uploaded a new diagnostic report after update Windows 10 to newest build version.
Diagnostic ID: F50AE9BC-A317-4E15-A5E0-73378B8EC78C/20180903205612

**Comment by Nextarius** [comment]
Newest diagnostic ID: F50AE9BC-A317-4E15-A5E0-73378B8EC78C/20180911102332
