### ISSUE TITLE
Error occurred: connectex: No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by gjonespf** [docker/for-win#253]
### Expected behavior
Docker starts and I can use it

### Actual behavior
Docker fails to start

### Information

Diagnostic ID
21795BA7-AEB6-4C69-ABC6-70B30EFCF6A1/2016-11-25_10-30-22

Windows 10 Build 14393

I've tried both stable and beta on this machine, no joy.  Have also tried removing all virtual network interfaces, factory resetting, trying different network virtual switches.  Nothing seems to work.  

### Steps to reproduce the behavior

1. Install fresh version of Docker (tried both stable and beta30.1 (8711)
2. Start docker
3. Fails with error message: Error occurred trying to connect: Get http://dev.docker:2375/v1.24/containers/json: dial tcp 10.0.75.2:2375: connectex: No connection could be made because the target machine actively refused it.

**Comment by rneugeba** [comment]
You seem to have the `DOCKER_HOST` environment variable set. Could you unset it and retry? With Docker for Windows you don't need this variable set.
thanks

**Comment by gjonespf** [comment]
To humour you, I removed it.  Unfortunately, had no effect.  Was there as I've previously run Docker Toolbox with my own custom builds of docker on this box.  Tested a number of other things, tried out changing to other IP subnets, nothing seemed to work.  When I went to change back to 10.0.75.1 I noticed a warning about another interface running with same IP address - one that didn't show up in devmgr even using hidden devices, not in Hyper-V Virtual Switch, and couldn't query it in PowerShell. Very strange. Ended up running:

`netcfg –d`

To uninstall all network adapters, then redo from scratch and finally got this working.  Hopefully this info helps someone else out.

**Comment by rneugeba** [comment]
Thanks for the quick reply and the details. In the past we had a lot of "fun" with windows networking adapters as well.

For Docker for Windows you do not need to specify the `DOCKER_HOST` environment variable. The communication with the docker daemon happens via a named pipe on the Windows host now.

Anyway, glad that it now works for you and thanks for closing the issue
