### ISSUE TITLE
Docker for Windows: Error response from daemon: An error occurred while sharing drive.

### ISSUE THREAD

**Issue by jjgriff93** [docker/for-win#2530]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: D10D1715-50F1-45AF-AE06-BD723A5340F4/20180902202605

### Expected behavior
Share my C drive on my Windows machine successfully

### Actual behavior
Every time I attempt to Share a drive, through the GUI - by ticking the C drive and authenticating, it unticks itself and does nothing. ON doing it via PowerShell, I get the error: `C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: An error occurred while sharing drive.`

### Information
<!--
Please, help us understand the problem.  For instance:
  - Is it reproducible?
Yes, I have even uninstalled Docker and reinstalle (stable branch), producing the same results. Restarting my machine has no effect also.
  - Is the problem new?
It has only occurred on my current Windows machine, I haven't seen this error on other machines.
  - Did the problem appear with an update?
On installing the latest branch of Docker in the past 2 weeks on my new machine.

  - Windows Version: Windows 10 Enterprise Edition, Version 1803 - OS Build 17134.228
  - Docker for Windows Version: Version 18.06.1-ce-win73 (19507)

**Comment by Madhyasta** [comment]
I am getting the same error? Did you got a fix for it?

**Comment by jjgriff93** [comment]
No @Madhyasta I've had no response from the team and still not working

**Comment by xtergo** [comment]
I had to share my C drive in Win10 first.

**Comment by bhushanbrb** [comment]
I see some Solutions which says Uninstall and Reinstall Microsoft File and Sharing protocol from NIC properties of Docker NAT but still same issue

**Comment by derfalx** [comment]
Are there any working solutions?

**Comment by olingern** [comment]
having the same issue

**Comment by mdiazcl** [comment]
Just in case people still getting this error!

This happens because you haven't enabled permissions to that drive at the Docker Engine.
Go to **Settings > Shared Drives** and select the one that you are trying to use as a local folder.

![image](https://user-images.githubusercontent.com/4249887/55599653-25c11100-572f-11e9-8258-0b692cdf2fe7.png)

Worked for me!

Regards,
 - MDiazCL
