### ISSUE TITLE
Docker is unable to run standard image

### ISSUE THREAD

**Issue by rajib2github** [docker/for-win#2547]
docker run hello-world

This command is giving below error:
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).

Version of Docker use:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:34 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
  Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true

**Comment by rajib2github** [comment]
Please give me reply. I am stuck with docker now completely. I am having Windows 10 enterprise 64 bit.

**Comment by AngryBeaver** [comment]
I have encountered a similar or same? Problem. 

My Problem is that it looks like the docker engine can not detect the correct dns server to look up. 
As Workaround 1) 
I have entered the correct dns and dns-search entries in my docker daemon files.
https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file
Fixes Internet issues within Containers.

As Workaround 2)
I resolv all needed hosts in my /etc/hosts (system32/driver/etc/hosts) there are 3 hosts you need
$ip registry-1.docker.io
$ip auth.docker.io
$ip %no idea it will come up as message text after you enetered the first two%
get the $ip by ping those hosts from your host windows machine.
This fix that you can download again form docker hub but it is terrible slow.

I would also be interested in some real solution to this.

**Comment by nuest** [comment]
Workaround for me was setting the DNS Server in the settings to a fixed value (the suggested `8.8.8.8`).
