### ISSUE TITLE
volume mounts in Docker for Desktop Kubernetes

### ISSUE THREAD

**Issue by DdannyB** [docker/for-win#2548]
Hello,

Does anybody know why i cant mount files from my compose file in Kubernetes but for Docker swarm it works?
i am using the new Kubernetes feature in Docker for Desktop. The mount im trying to make is:

Volumes:
-  C:\docker\appsettings.json:/app/appsettings.json

### Expected behavior

The compose file should work for docker swarm AND Kubernetes.

### Actual behavior
It works for Docker swarm but on Kubernetes i am getting this error:

Stack.compose.docker.com "adapter" is invalid: adapter: Invalid value: "null": conversion to kube entities failed: C:\docker\appsettings.json: only absolute paths can be specified in mount source

### Steps to reproduce the behavior
1. Create a compose file with a volume
2. Run the compose file on the new Kubernetes feature.

**Comment by singlewind** [comment]
@DdannyB did you fix the issue?

**Comment by DdannyB** [comment]
Yes, //c/docker/appsettings.json:/app/appsettings.json fixed it for me!
