### ISSUE TITLE
Why is `debug: true` by default?

### ISSUE THREAD

**Issue by SaschaNaz** [docker/for-win#255]
### Expected behavior

I think debug mode should be turned on manually.

### Actual behavior

Debug mode is being turned on by default.

### Steps to reproduce the behavior

  1. Install the latest beta 30 of Docker for Windows.
  2. `docker info`
  3. See `Debug Mode (server): true`

### Workaround

```json
{
  "registry-mirrors": [],
  "insecure-registries": [],
  "debug": false
}
```

**Comment by justincormack** [comment]
It is on by default to allow debugging of people's issues more effectively, as otherwise often we would just have to say please try to replicate your issue again with debug turned on.

Is it causing you a problem? Debug mode only affects logging.

**Comment by SaschaNaz** [comment]
No, I just thought turning the mode off might help solving significant performance difference between Docker container and native machine. It didn't help, however :/

**Comment by dgageot** [comment]
@SaschaNaz Thank you for your feedback! I'm going to close this issue since it's on purpose that we set debug mode to `true`. If you have performance issues, please create a ticket that includes a diagnostic id, so that we can help.
