### ISSUE TITLE
Docker commands taking way too long to execute

### ISSUE THREAD

**Issue by avinashs15** [docker/for-win#2555]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 43542D78-B78D-44D3-B2E3-2D468C27333C/20180906174958

### Expected behavior
docker commands should execute soon

### Actual behavior
docker commands are taking a long time to complete
simple commands like docker images 
docker ps -a is taking a long time to execute
This was working fine couple of days ag
### Information

  - Windows Version: 10 
  - Docker for Windows Version: Docker version 18.06.1-ce, build e68fc7a

### Steps to reproduce the behavior

  1. Run basic commands on powershell/cmd 
  2. Wait forever to complete

**Comment by jahmia** [comment]
Facing the same problem
