### ISSUE TITLE
Move functionality to docker-machine drivers

### ISSUE THREAD

**Issue by masaeedu** [docker/for-win#256]
Docker for Windows is really nice and ergonomic, and everything basically works out of the box. However, there now seems to be two different siloed feature sets with docker machine and docker-for-windows. 

If you want to be able to manage docker clusters/work with other hypervisors/ssh into the machine, you have to go back to docker-machine, where things don't work nicely out of the box. However if you move to Docker for Windows for the polished experience, you get a constrained feature set.

It would be great if the docker/for-win project could work as a testbed for features that could then be rolled back into docker-machine. E.g. if docker/for-win was motivated by lack of a good virtual networking abstraction in docker-machine, maybe the work on networking here could be rolled back into docker-machine in some way.

Overall, there is value in a consistent, cross platform set of abstractions for interfacing with a remote docker server (host volumes, networking, device forwarding, etc). The Windows-specific chrome can be built on top of that.

**Comment by rneugeba** [comment]
@masaeedu thank you for the suggestion.Unfortunately almost all of the features which make Docker for Windows easy to use are achieved via a tight integration of what runs in the Linux VM and services and components running inside the application. For most, if not all of the features it would not be possible to feed them back into a command line tool like `docker-machine`.

Did you have  particular feature in mind? I may be able to provide more specifics

**Comment by masaeedu** [comment]
Well, for example the host volumes feature works by mounting a Windows
shared folder using cifs. docker-machine could ssh into the box and set up
the appropriate knd of mount depending what platform you're running the
docker-machine client from.

**Comment by rneugeba** [comment]
This may be possible to do with `docker-machine`, but Docker for Windows does a whole bunch of other stuff around this:
- make sure the file share is exported
- make sure the firewall is opened
- rewrite the docker command line on the fly when `-v` is used.
- verify that shares are mounted when `-v` is used.
- manage credentials for CIFS mount
Some of these could be incorporated in `docker-machine` while others can't easily be incorporated (the checks and rewrites).

Thanks for your suggestion, but I'm closing this issue for now, as this seems more about adding features to `docker-machine`, which has it's own [github respository and issue tracker](https://github.com/docker/machine) than improvements and/or bugs with Docker for Windows, which this github issue tracker is about.
