### ISSUE TITLE
RUN command hangs at end of command for 20 mins

### ISSUE THREAD

**Issue by dazinator** [docker/for-win#2565]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E3848FD7-05DB-4B46-8A92-C76B6CCA34F9/20180907122347

### Expected behavior

In my DOCKERFILE I have several RUN instructions, each of them run a powershell script.

```
RUN powershell -NoProfile -File C:/Foo/install-dsc.ps1
RUN powershell -NoProfile -File C:/Foo/install-vs.ps1
RUN powershell -NoProfile -File C:/Foo/install-dev-express.ps1
```

When I build the image I use:

```
docker-compose build --no-cache --force-rm
```

The first two RUN instructions run ok.
The last one, the contents of `install-dev-express.ps1` script do this:

```
Write-Host "Installing Dev Express."

$process = [Diagnostics.Process]::Start("C:/Foo/TEMP/DXperience-12.1.8.exe","/Q /EMAIL:foo@bar.com /PASSWORD:foobar /EULA:accept");
do {
    Start-Sleep 5
    Write-Host "." -NoNewline
} until ($process.HasExited)

Write-Host "DevExpress install finished with exit code " $process.ExitCode
```

Basically it spawns a process to run an installation `exe` and sleeps in 5 second intervals, until the install has finished.
The install process takes about 10 minutes to complete.

After 10 minutes, and the install has finished, I see the output:

```
DevExpress install finished with exit code 0
```

This is now where my issue comes in - the powershell script has now finished. I now see a 20 minute period of nothing until eventually this appears:

```
Removing intermediate container 53a4ede22f9c
 ---> 2b2230179dbd

```

So it appears that after the script in the RUN command has finished, there is a very long delay where you would think docker has perhaps hung. However if you wait long enough (20 minutes in my case) it eventually proceeds.

### Actual behavior

If docker is legitimately busy for this long after the RUN script has finished executing, then I would expect some output from docker so that the user knows its still doing work, and it's not just hung.

### Information

  - Windows Version: Windows 10 latest update.
  - Docker for Windows Version: 18.06.1-ce-win73 (19507) (Stable)

### Steps to reproduce the behavior
I can consistently reproduce this when the RUN instruction runs this particular devexpress installer exe, however in order to run this .exe you need a devexpress licence which is not something I am able to share.

**Comment by kerrhome** [comment]
I have this same issue, @dazinator.  Did you ever find a solution?
