### ISSUE TITLE
Windows Server Edition

### ISSUE THREAD

**Issue by guhuajun** [docker/for-win#2574]
Greetings,

I cannot find any words about Windows Server edition in following documentation.
https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility

Will this work?

1. docker pull microsoft/windowsservercore:ltsc2016 in a Windows Server 2016 Standard edition box.
2. docker save microsoft/windowsservercore:ltsc2016 -o msft_wsc_ltsc2016.tar
3. docker load -i msft_wsc_ltsc2016.tar in a Windows Server 2016 DataCenter edtion box.

Thanks,
Greg

**Comment by jasonbivins** [comment]
Hi Greg -
We don't actually support the EE (server) version of the engine here, this area is for the CE (windows 10) version.   

But I did run these commands through a 2016 server box running on Azure, and was able to run through them with no problems with the EE engine.  The save and the load commands can take a while to complete with such a big image though.
