### ISSUE TITLE
Unable to launch process: 1260

### ISSUE THREAD

**Issue by evak2979** [docker/for-win#2578]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 20180910161759

### Expected behavior
- Docker should start when booting windows

### Actual behavior
- Docker icon is red. Message is: Unable to launch process: 1260
Error message:

```
> Unable to launch process: 1260
>    at Docker.Win32Helpers.NativeImpersonatedProcess.Start(NativeImpersonatedProcess* , basic_string<wchar_t\,std::char_traits<wchar_t>\,std::allocator<wchar_t> >* watchguardPath) in c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\xstring:line 1808
>    at Docker.Win32Helpers.ImpersonatedProcess.Start(String watchguardPath) in c:\gopath\src\github.com\docker\pinata\win\src\docker.win32helpers\impersonatedprocess.cpp:line 250
>    at Docker.Backend.Processes.ExternalProcess.StartImpersonatedProcess(String fileName, String arguments, String currentDirectory, IDictionary`2 envVariables, WindowsIdentityRecorder identity, CancellationToken stopToken) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\ExternalProcess.cs:line 66
>    at Docker.Backend.Processes.ExternalProcess.Start(String arguments, String currentDirectory, IDictionary`2 envVariables, WindowsIdentityRecorder identity) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\ExternalProcess.cs:line 52
>    at Docker.Backend.Processes.ApiProxy.StartWinNamedPipe(Settings settings, String daemonNamedPipe) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\ApiProxy.cs:line 73
>    at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 222
>    at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 96
>    at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 48
>    at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 180
```

### Information

  - Windows Version: 10 
  - Docker for Windows Version: Latest (and the one before latest)

### Steps to reproduce the behavior

  1. Boot to windows

Please see log file. Thank you and sorry for the trouble !
[log.txt](https://github.com/docker/for-win/files/2367317/log.txt)

Diagnostics:
[diagnostics.log](https://github.com/docker/for-win/files/2367323/diagnostics.log)

**Comment by jasonbivins** [comment]
Hi @evak2979 
It looks like you're getting blocked by security settings.  Specifically com.docker.proxy.exe is being blocked.  Do you have any malware blocking or security software installed?

```[16:17:59.831][WindowsDaemon  ][Warning] Event ID '866' in Source 'Microsoft-Windows-SoftwareRestrictionPolicies' cannot be found.  The following information is part of the event:'C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe', '{E63CF0E7-DBF1-4B2F-A797-DE01D2B0BFE2}', '*.doc*.exe'```

**Comment by evak2979** [comment]
I can check tomorrow with our team - I am confused as to why version 17.0.3 is working, but anything latter no. Plus, none of my colleagues seem to be experiencing this...
