### ISSUE TITLE
Can full-sync-on-flush workaround be applied on Windows?

### ISSUE THREAD

**Issue by SaschaNaz** [docker/for-win#259]
### Expected behavior

Near-equal performance of MySQL

### Actual behavior

MySQL is 10x slower than on native machine. DB Initialization especially takes 40 minutes.

### Information

  - Diagnostic: CD40C84E-6EB8-4012-B84E-A6D77C8B9036/2016-11-28_17-06-27
  - Dockerfile: https://github.com/SaschaNaz/docker-gitlab-runner-itrust/blob/master/Dockerfile
  - Windows 10
  - My use: Frequent DB read/write access to run testsets

I have near 10x performance difference between native machine and Docker container. I've tried applying MySQL skip-name-resolve tip and Java /dev/urandom tip but nothing worked, so I'm finally manipulating Docker itself. Is there a way to apply [this workaround for Mac](https://github.com/docker/for-mac/issues/668) on Windows?

This is not a duplicate of #188 as I don't have any significant speed difference in `VOLUME /var/lib/mysql`.

**Comment by rneugeba** [comment]
@SaschaNaz thanks for your report. From the description it's not clear to me if you keep the MySQL data files on the VMs disk or a volume from mounted from the host. Could you clarify?
Thanks

**Comment by SaschaNaz** [comment]
I tried both. I don't have to keep MySQL data so I at first started without `VOLUME` thing and later I added the line trying to fix my performance issue. Unfortunately I saw no difference.

**Comment by SaschaNaz** [comment]
This was because Docker VM was on a secondary HDD rather than an SSD.
