### ISSUE TITLE
Cannot switch to Windows containers

### ISSUE THREAD

**Issue by eeevans** [docker/for-win#2603]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:46B9E1CC-DA7F-4522-AE52-463596607621/20180913141951

### Expected behavior
Docker switches to windows containers
### Actual behavior
Timed out while waiting for Docker daemon to be ready
### Information
 Not needed, no containers running
  - Windows Version: Win 10 Ver 1803 OS Build 17134.228
  - Docker for Windows Version:
Client:                                        
 Version:           18.06.1-ce                 
 API version:       1.38                       
 Go version:        go1.10.3                   
 Git commit:        e68fc7a                    
 Built:             Tue Aug 21 17:21:34 2018   
 OS/Arch:           windows/amd64              
 Experimental:      false                      
                                               
Server:                                        
 Engine:                                       
  Version:          18.06.1-ce                 
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3                   
  Git commit:       e68fc7a                    
  Built:            Tue Aug 21 17:29:02 2018   
  OS/Arch:          linux/amd64                
  Experimental:     true                       
### Steps to reproduce the behavior

  1. I had been on the edge version and reset to factory defaults; I then switched to stable with factory defaults with the same results.
  2. ...

**Comment by guhuajun** [comment]
Greetings,

Based on my experience, free memory is very important when switching to Windows container.

**Comment by eeevans** [comment]
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="docker" /> 
  <EventID Qualifiers="0">1</EventID> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2018-10-09T21:32:34.702801400Z" /> 
  <EventRecordID>122334</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>evansw7p.amerinnovations.com</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Error occurred when creating network could not find plugin internal in v1 plugin registry: plugin not found</Data> 
  </EventData>
  </Event>

**Comment by eeevans** [comment]
I got the above error in the event log but it did switch to windows containers successfully this time.
