### ISSUE TITLE
Container encounterd Error during CreateProcess: failure in a Windows system call: Unspecified error (0x80004005)

### ISSUE THREAD

**Issue by kamyarvarz** [docker/for-win#2613]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 75654B00-B030-4E0E-8B64-0A59DF6C7D3C/20180915105329

### Expected behavior
Finish Build
### Actual behavior
Error received from Windows daemon
An error exit status 1 was encountered while building the Docker image.
[WindowsDaemon  ][Error  ] Error running exec 3cdd5782419581fc1685c29d72dc2fdaaeb45e98cd1ee044ae46f5a699fa5178 in container: container 48551cb7affca57beea9427a1a78370ecc9926fbe900535c13b1e8831cdf2e25 encountered an error during CreateProcess: failure in a Windows system call: Unspecified error (0x80004005) extra info: {"CommandArgs":["powershell","-Command","\n$hostsFile = \"C:\\Windows\\System32\\drivers\\etc\\hosts\"\n$src = [System.IO.File]::ReadAllLines($hostsFile)\n$a = $src += \"\"\nFor ($i=0; $i -le $a.length; $i++) {\n\tif ($a[$i].Contains(\"host.docker.internal\"))\n\t{\n\t\t$a[$i] = \"192.168.1.61 host.docker.internal\"\n\t\t$a[$i+1] = \"192.168.1.61 gateway.docker.internal\"\n\t\t[System.IO.File]::WriteAllLines($hostsFile, [string[]]$a)\n\t\texit\n\t}\n}\n$a = $a += \"# Added by Docker for Windows\"\n$a = $a += \"192.168.1.61 host.docker.internal\"\n$a = $a += \"192.168.1.61 gateway.docker.internal\"\n$a = $a += \"# End of section\"\n[System.IO.File]::WriteAllLines($hostsFile, [string[]]$a)\n"],"WorkingDirectory":"/app","Environment":{"HOSTNAME":"48551cb7affc","NODE_HEAPDUMP_OPTIONS":"nosignal","NODE_VERSION":"8.12.0","PATH":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","PORT":"3000","YARN_VERSION":"1.9.4"},"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}

### Information

  - Windows Version: 10 Pro
  - Docker for Windows Version: 
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:34 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.24)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:36:40 2018
  OS/Arch:          windows/amd64
  Experimental:     true
### Steps to reproduce the behavior

  1. ...Here's the Dockerfile: 
FROM node:8
ENV PORT 3000
ENV NODE_HEAPDUMP_OPTIONS nosignal
EXPOSE 3000
EXPOSE 9229
WORKDIR "/app"
COPY . /app
COPY run-dev /bin
COPY run-debug /bin
RUN chmod 777 /bin/run-dev /bin/run-debug
RUN apt-get update
RUN apt-get install bc
CMD ["/bin/bash"]
ARG bx_dev_user=root
ARG bx_dev_userid=1000
RUN BX_DEV_USER=$bx_dev_user
RUN BX_DEV_USERID=$bx_dev_userid
RUN if [ "$bx_dev_user" != root ]; then useradd -ms /bin/bash -u $bx_dev_userid $bx_dev_user; fi
  2. ... Error occured when the following command was executed:
docker image build --file Dockerfile-tools --tag nodejswebappwithexpressjsmnqci-express-tools --rm --pull --build-arg bx_dev_userid=0 --build-arg bx_dev_user=root .

**Comment by dougrathbone** [comment]
I am also seeing this in my Windows 10 Docker install while trying to use Docker build.

[09:04:35.659][WindowsDaemon  ][Error  ] exec's CreateProcess() failed [namespace=moby container=69ec6fa8bcfee1ebec3f71380649f3a48f65a5f5e2dcffda993c30d977971ee9 exec=c0472860b323a03c0015efe55a5cbac50621c44fe64fac38558d4b636185ce5a module=libcontainerd error=container 69ec6fa8bcfee1ebec3f71380649f3a48f65a5f5e2dcffda993c30d977971ee9 encountered an error during CreateProcess: failure in a Windows system call: The user name or password is incorrect. (0x52e)

The behavior I am seeing is that a build will run (very long...) and succeed, however if i run it a second time the build hangs (have waited a full day without movement).

**Comment by alkreddy** [comment]
I see the same with edgeHub and SimutedTemperatureSensor modules. They were working fine yesterday but they don't start any more... edgeAgent logs show 

`Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException- Message:Error calling start module SimulatedTemperatureSensor: Could not start module SimulatedTemperatureSensor
        caused by: Could not start module SimulatedTemperatureSensor
        caused by: container 75dcf18d2f2a765874ef1bdc72dc9c2c8a74780aa0974e0e3334f18efdf2fac6 encountered an error during CreateProcess: failure in a Windows system call: The password for this account has expired. (0x532) extra info: {"CommandLine":"dotnet SimulatedTemperatureSensor.dll","User":"moduleuser"`

**Comment by bcowell** [comment]
@alkreddy Looks like your windows account password has expired. Have you tried logging out and back into the server with your updated password?
