### ISSUE TITLE
Docker Run --mount: bind mount source path does not exist

### ISSUE THREAD

**Issue by GCSBOSS** [docker/for-win#2620]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 

### Expected behavior
When running `docker run -it --mount source=/host_mnt/c/Users/myself/existing/path,target=/usr/src/app/path,type=bind any-container`

The given container is run with the host directory mounted in it.

### Actual behavior
The container is not run and CLI prints me the following error: 
```
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: invalid mount config for type "bind": bind mount source path does not exist: /host_mnt/c/Users/myself/existing/path.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
```
### Information
Same error for any image, so the problem is not related to some image.

For some reason, the bind does not recognize my host filesystem path. Am I missing some detail in the command? Some windows specifics maybe?
  - Windows Version: **10 Pro 10.0.17134 (17134)**
  - Docker for Windows Version: **18.06.1-ce-win73 (19507)**

**Comment by kmillett** [comment]
I have the same issue.  I am using Windows Subsystem for Linux (WSL) with Ubuntu.  I would like to know if mounting a volume from the linux file system is supported.  I can mount a volume from the Windows file system, but not the linux file system.

**Comment by GCSBOSS** [comment]
@kmillett I believe this issue tracker is for "Docker for Windows". You should probably look [in here](https://github.com/docker/for-linux).

**Comment by kmillett** [comment]
@GCSBOSS I am using Docker For Windows.  I am trying to mount a volume to a path in the linux file system running under WSL and getting the same error you are getting.

**Comment by stshrive** [comment]
I have a fairly detailed issue similar to this open on the [WSL issues page](https://github.com/Microsoft/WSL/issues/3571) side which I believe may be related.

**Comment by mchenryc** [comment]
I was able to get bind-mounts working on WSL

1. Docker Settings > Shared Drives:

    Select the drives you'd like to share.

2. Edit `/etc/wsl.conf` in WSL to include the following:

        [automount]
        root = /
        enabled = true
        options = "metadata"        

    `root = /` mounts drives at `/c` instead of `/mnt/c`.  `$(pwd)` will still say `/mnt/c`, but `ls /c` also works now. See: https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly
    `enabled = true` allows launching windows processes from WSL. See: https://blogs.msdn.microsoft.com/commandline/2018/02/07/automatically-configuring-wsl/
    `options = "metadata"` fixes file permissions so chmod works (and files aren't 777 all the time)

3. Reboot

There are some caveats on older windows builds. See the nickjanetakis post for more.

**Comment by mchenryc** [comment]
I was able to get bind-mounts working on WSL, and work with files in both directions from the host machine.

1. Docker Settings > Shared Drives:

    Select the drives you'd like to share.

2. Edit `/etc/wsl.conf` in WSL to include the following:

        [automount]
        root = /
        enabled = true
        options = "metadata"        

    `root = /` mounts drives at `/c` instead of `/mnt/c`.  `$(pwd)` will still say `/mnt/c`, but `ls /c` also works now. See: https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly
    `enabled = true` allows launching windows processes from WSL. See: https://blogs.msdn.microsoft.com/commandline/2018/02/07/automatically-configuring-wsl/
    `options = "metadata"` fixes file permissions so chmod works (and files aren't 777 all the time)

3. Reboot

There are some caveats on older windows builds. See the nickjanetakis post for more.

**Comment by stshrive** [comment]
@GCSBOSS
Have you changed the `[automount]` location as mentioned above? I can confirm that following the instructions in the nickjanetakis post resolves this issue. I have independently run into this issue while working with WSL and docker on windows.

Also check out this [Medium article](https://medium.com/software-development-stories/developing-a-dockerized-web-app-on-windows-subsystem-for-linux-wsl-61efec965080) and this post in the [Microsoft Developers Blog](https://blogs.msdn.microsoft.com/commandline/2017/12/22/share-environment-vars-between-wsl-and-windows/). They may be useful.

**Comment by x2jitendra** [comment]
For Docker on windows, I just unchecked my shared drives in docker settings, saved, then checked them and saved.

I was attempting to do a docker stack deploy and it was not starting up (0/1 replicas when doing a docker stack services <service name>).  I tried restarting docker, but it was only when I unchecked / saved / checked / saved the shared drives did it start working. 

Using Version 18.06.1-ce-win73 (19507)

**Comment by stshrive** [comment]
@x2jitendra, I believe you will have to do that every time you update your windows password.

**Comment by GCSBOSS** [comment]
@x2jitendra @stshrive This se em very likely to be the case. Though I will only be able to test it after the weekend.

**Comment by x2jitendra** [comment]
@stshrive  that is good to know... unfortunately, in this case, I had not changed my windows password.  I did however update windows, so perhaps there was something in windows update that reset this for docker.

**Comment by Gonzalo2683** [comment]
In my case i run in the console and fix the problem:
`docker login` //  If the system have your credentials , you will be log in, if not, use your credentials

**Comment by serverdevil** [comment]
`docker login` does solve the problem.

**Comment by jtsalten** [comment]
> @x2jitendra, I believe you will have to do that every time you update your windows password.

This was the problem. I've changed the password some days ago... I didn't remember. Unchecking and rechecking shared drive makes it work again. Thanks.
