### ISSUE TITLE
AB1FB563-D2B8-4AA9-A8BD-F15E553E2488/20180919093622

### ISSUE THREAD

**Issue by hj2006287** [docker/for-win#2622]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
There is no information here about what the problem is. Please reopen if you have more information, such as a description of the problem and anything you are aware of that might have contributed to causing it.
