### ISSUE TITLE
docker push fails (EOF) and is reported 50% bigger on Windows with LCOW experimental mode

### ISSUE THREAD

**Issue by joshlang** [docker/for-win#2623]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Docker push works

### Actual behavior

Docker push fails to upload 1 layer, retries a few times, and errors with EOF.  It also reports the layer as being 50% bigger than it actually is, while pushing it.  Even after aborting/failing the process, both docker and the docker service process use max CPU indefinitely until hard-killed.

### Information

Docker for windows 18.06.1-ce-win73 (19507)
- Windows Containers mode
- Experimental mode ACTIVE
- Uploading to Azure Container Registry, although I suspect the problem would occur with any registry.

### Steps to reproduce the behavior

```
docker pull ubuntu
docker image tag ubuntu registry-name.azurecr.io/ubuntu
docker push registry-name.azurecr.io/ubuntu
```

### Output

```
...
a30b835850bf: Pushing [==>                                                ]   4.84MB/120.1MB
````

Sometimes, it actually makes it all the way to 120.1MB instead of failing/retrying, but it never actually completes - instead, in that case, it says "EOF" and quits.

When I push this image from an ubuntu box instead, it pushed just fine except ***layer a30b835850bf was about 80MB, not 120.1MB***

**Comment by darrenfurr** [comment]
I am experiencing the same issue using WinServer 2019 in Azure & trying to push a linux container to ACR.

**Comment by darrenfurr** [comment]
I've attached the docker daemon.log from attempting to use lcow to docker push a ubuntu image to my ACR. I received the same results @joshlang 
[daemon.zip](https://github.com/docker/for-win/files/2738721/daemon.zip)

**Comment by IanBFarrell** [comment]
I am currently running into this same issue.

**Comment by OneCyrus** [comment]
same issue here with pushing the nginx image to ACR. any ideas?

**Comment by cerebrate** [comment]
Exactly the same issue here, pushing to ACR, Docker Hub, or a local registry. I don't know if this is specifically relevant, but while I was fiddling with it, I tried cranking the maximum concurrent uploads down to one, which gives me the following final error message when the last retry of the push fails:

```
docker : failed CopyFileW Win32 call from 'C:\ProgramData\Docker\lcow\cache\scratch.vhdx' to
'C:\ProgramData\Docker\lcow\scratch\174ce691a4ebb5582bc88d0d6c1abe77ee2528b67659af12e94bea0e37223085.vhdx': The process cannot access the file because it is being used by another process.
```

Any progress on a fix?

**Comment by olihofmann** [comment]
I have the same problem, any ideas?

**Comment by chandrakala-adsk** [comment]
I am facing the same issue, any suggestion to fix this

**Comment by Silvenga** [comment]
I'm seeing the same problem. Most layers do succeed to upload, expect one, it's reproducible on multiple machines - same layer. 

@chandrakala-adsk what made you try deleting those folders (I don't have them)?

**Comment by lpingas** [comment]
I also observed the same issue using Docker Desktop 2.1.0.1 (37199): Although all my Windows base images are successfully pushed, whenever I try one Ubuntu based, I get the infinite retries coupled with EOF failure.

**Comment by arnoldpistorius** [comment]
I'm running into this problem as well.

**Comment by crossan007** [comment]
I'm getting this problem as well

**Comment by JesseBropez** [comment]
I too am having this issue, still.

**Comment by mugi111** [comment]
When I tried push to ACR(Azure Container Registry), I faced this issue, too. Is this still not solved?
If the method to solve this is there, Please teach.
I'm on Windows 10 Pro, docker desktop 2.2.0.0.

**Comment by rerime** [comment]
Same problem with Windows Server 2019 with Docker Engine 19.03.5.
Reproduce with Harbor or ACR(Azure Container Registry)

**Comment by 0x53A** [comment]
I faced the same issue where pushing an image repeatedly failed with the same layer.
I had to rebuild the image a few times with dummy changes until it could be successfully pushed.

The registry is ACR.

**Comment by Nandeeshswami** [comment]
Still facing the same issue
 failed CopyFileW Win32 call from 'C:\ProgramData\Docker\lcow\cache\scratch.vhdx' to 'C:\ProgramData\Docker\lcow\scratch\ae58a3c55787abcd0f280131a73882f1a280d2186bb91bc423818bdbcd6d31b6.vhdx': The process cannot access the file because it is being used by another process

**Comment by 0x53A** [comment]
still a bug

**Comment by 0x53A** [comment]
Also just as a note if anyone is interested, based on the comment by @crossan007 I am currently using this in my Fake build script:

```f#

let pushDockerLinux tag =
    let result =
        CreateProcess.fromRawCommand "docker.exe" ["push"; tag]
        |> Proc.run
    if result.ExitCode <> 0 then failwithf "docker command failed: %i" result.ExitCode

let pushDockerLinux_WithLCOWWorkaround tag =

    // use a mutex so only one push is done in parallel
    // (code for MutexLock not shown)
    use __ =  MutexLock.aquire "Global\\docker-linux"

    try
        pushDockerLinux tag
    with
      _ ->
        // https://github.com/docker/for-win/issues/2623
        // see if there are locked files left over
        let dir = @"C:\ProgramData\Docker\lcow\scratch"
        if Directory.Exists dir && (Directory.GetFiles dir).Length > 0 then
            let procs = Process.GetProcessesByName("vmwp")
            if procs.Length > 0 then
                printfn "==//== Trying workaround for LCOW bug, found %i vmwp processes" procs.Length
                for p in procs do
                    printfn "  * trying to kill %i ..." p.Id
                    try p.Kill() with exn -> printfn "    Kill failed: %O" exn

                pushDockerLinux tag
```

So basically, if the push fails and the directory ``lcow\scratch`` exists, then I automatically kill all ``vmwp`` processes and try again.
Maybe a bit heavy handed, but it seems to work ¯\_(ツ)_/¯

**Comment by Silvenga** [comment]
Still an issue?
