### ISSUE TITLE
Docker on windows10 crashed

### ISSUE THREAD

**Issue by PalojuRam** [docker/for-win#2624]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version: Windows 10 Enterprise
  - Docker for Windows Version: 18.06.0-ce-win72

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
There is no information here to diagnose the problem. Please reopen if you have more information to add, eg the diagnostics id.
