### ISSUE TITLE
installation on win10 x64/vs2017 fail

### ISSUE THREAD

**Issue by ShanghaiDivine** [docker/for-win#2626]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
There is no information here to diagnose the problem. Please reopen if you have more information to add.
