### ISSUE TITLE
Incorrect time in container compared to windows 10 host

### ISSUE THREAD

**Issue by martencassel** [docker/for-win#2640]
- [+] I have tried with the latest version of my channel (Stable or Edge)
  - [+] I have uploaded Diagnostics
  - Diagnostics ID: 24B7AFE5-DFF1-4AFB-87BB-27BD695F550C/20180925092627

### Expected behavior
The time in the container should match the hosts time.
### Actual behavior
Time time in container is off by ~ 7 hours
### Information

  - Is it reproducible? Yes
  - Is the problem new? No.
  - Did the problem appear with an update? No
  - Windows Version: Windows 10 Enterprise 1709, 16299.431.amd64fre.rs3_release_svc_escrow.180502-1908
  - Docker for Windows Version: 18.06.1-ce-win73 (19507), Channel: stable.

### Steps to reproduce the behavior
```
PS> docker pull microsoft/windowsservercore:1709
1709: Pulling from microsoft/windowsservercore
Digest: sha256:1bd535b56b751a434bb7d70c488567674553d5c2ee53cfec3550cdde3add3073
Status: Image is up to date for microsoft/windowsservercore:1709

PS> Get-Date -Format g
2018-09-24 12:53

PS> docker run --rm microsoft/windowsservercore:1709 powershell.exe /c Get-Date -Format g
9/24/2018 9:44 PM
```

**Comment by TimZander** [comment]
I think this and https://github.com/docker/for-win/issues/3168 are the same. BTW I am also experiencing this issue
