### ISSUE TITLE
Cannot stop/kill Linux containers when switch to Windows containers mode (LCOW bug?)

### ISSUE THREAD

**Issue by jtsalten** [docker/for-win#2642]
I've just installed the Docker last version available for Windows 10 Pro (18.09.0-ce-beta1
) . When Running on mode Windows Containers to be able to run Linux and Windows containers at same time I realize that I can't stop the Linux ones.
If I run, for example, **_docker stop ubuntu_** it keeps waiting more than 5 minutes till the container is stopped (it should take seconds).
Also **_docker kill ubuntu_** doesn't work.
To stop it quickly I have to run **_hcsdiag kill <hyper-v container id>_**, but I think is not the right way.

On the other side I can stop/kill perfectly a windows container with: **_docker stop nano_** or _**docker kill nano**_ (being nano the name of a windows container)
 
Docker Version:
     Server Version: 18.09.0-ce-beta1
Storage Driver: windowsfilter (windows) lcow (linux)

**Comment by ebriney** [comment]
@hi @jtsalten, it concerns daemon engine and lcow, so can fill an issue in moby: https://github.com/moby/moby/issues

**Comment by jtsalten** [comment]
Done. Issue #37919

**Comment by jtsalten** [comment]
It's not fixed yet in last edge releases....

**Comment by DavyGuedes** [comment]
> 
> 
> Done. Issue #37919

Thank you! Linking...
[#37919](https://github.com/moby/moby/issues/37919)

**Comment by nevrax** [comment]
this is an **AWFUL** experience!

it doesn't matter if you're running a small container like alpine linux or bigger ones like ubuntu or debian. you have to wait 3-5 minutes for simple operation like docker stop to finish properly. most of the times you'll end up restarting docker daemon, ce or cc edition same difference.

sometimes a docker stop -t 0 or a docker-compose down -t0 will do the trick and close the container pretty fast but try running lcow on widows with --restart always.

**Comment by nevrax** [comment]
takes less time rebooting the physical server!

**Comment by nevrax** [comment]
takes less time rebooting the physical server than stopping a lcow container on windows. this is how had bad it is. months have passed but nothing have changed.

**Comment by crossan007** [comment]
I'm seeing this too on LCOW containers with Docker ee (19.03.1) on Windows Server 2019

**Comment by MattGarnettWelsh** [comment]
This is causing us a massive headache at the moment - 5 minutes minimum for docker-compose down or docker stop commands. Restart-Service docker via pwsh is faster to stop a container and rm it...

**Comment by crossan007** [comment]
I wonder if this is related to the inability to *push* LCOW containers to a remote because `vmwp.exe` is locking the LCOW temp `vhdx`: https://github.com/docker/for-win/issues/2623#issuecomment-555738669

**Comment by Herr-Sepp** [comment]
Docker ee 19.03.5 on Windows Server 2019 (1809).
I have this behavior also with LCOW containers. 
Stop and Kill need sometimes over 5 Min for processing.

Has anyone found a workaround?
Does using Windows Server 2019 (1903) or (1909) help by this issue?

**Comment by MattGarnettWelsh** [comment]
I used `docker kill -s 9 <docker container ID>`

**Comment by Herr-Sepp** [comment]
Thank you! 
For docker stop works 
`docker stop --time=0 ` 
for me.

Hope this will be fixed with the new WSL2 base for Docker on Windows
