### ISSUE TITLE
fatal: unable to configure the Docker daemon with file C:\ProgramData\Docker\tmp-d4w\daemon.json: the following directives are specified both as a flag and in the configuration file: group: (from flag: [MYUserName], from file: Hyper-V Administrators)

### ISSUE THREAD

**Issue by AnveshMora** [docker/for-win#2647]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 
4997AB9F-F683-4378-B10C-B8D234709989/20180925135158 - [20180925135158.zip](https://github.com/docker/for-win/files/2414379/20180925135158.zip)
4997AB9F-F683-4378-B10C-B8D234709989/20180925135550 - [20180925135550.zip](https://github.com/docker/for-win/files/2414385/20180925135550.zip)

### Expected behavior
I've updated daemon.json with below content:

{  
"registry-mirrors": [],  "insecure-registries": [],  "debug": true,  "experimental": true,
	"hosts": ["tcp://0.0.0.0:2375","tcp://10.8.162.33:56625"],
	"data-root": "C:\\\\Users\\\\amora\\\\Docker",
	"tlsverify": false,
	"group" : "Hyper-V Administrators"
}

The main reason behind the i'm doing these changes is: I'm not able to pull docker image on to local .

Docker is expected to run without any errors
### Actual behavior
I'm not able to pull docker image on to local and facing below error:

> 1.11: Pulling from library/golang
error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/01/01a7659725712d182a581bf175c8e2ead5e04b852e5ba9231686005e1eb0ca8a/data?verify=1537866583-Eex7puVfBwE4RMqAyZeuHFMt%2BW8%3D: read tcp 10.8.162.33:59832->10.1.100.60:80: wsarecv: An existing connection was forcibly closed by the remote host.

If you observe above json, I've added "Hyper-V Administrators" to the group field, My user is added to that group and changed to data-root field to customise the docker container location.

**Right now, not able to Restart Docker service**, forget about pulling the docker image.
### Information

  - Windows Version: 10
  - Docker for Windows Version:
 docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:34 2018
 OS/Arch:           windows/amd64
 Experimental:      false

### Steps to reproduce the behavior

  1. Update daemon.json file with above configuration
  2. try to restart the docker, my system is behind comapny's firewall. So, I've also tried setting HTTP_PROXY and HTTPS_PROXY before running the reproduce scenario.

**Comment by ebriney** [comment]
Hi @AnveshMora : I just fixed that, it should ok in next version

**Comment by AnveshMora** [comment]
Thank you Emmanuel, Can you share the commit id and some more info what might be the cause?
