### ISSUE TITLE
MobyLinuxVM fails to get an IP

### ISSUE THREAD

**Issue by robrich** [docker/for-win#265]
### Expected behavior

When I start up Docker for Windows, I expect the Moby Linux VM to fire up.

### Actual behavior

Every time I start Docker for Windows, the Moby Linux VM starts, doesn't get an IP, and Docker for Windows crashes -- red whale tray icon and pop-up message showing the error.  If I stop and restart Moby Linux VM a few times, it eventually gets an IP, and all is well from then on.  Trolling through the Hyper-V logs, nothing stands out.  The Docker logs show the "failed to get an IP 60 times" message each time, but no cause.

The only thing weird is the Windows machine that Docker for Windows is installed in is itself a VM, though since the Anniversary Update, nested virtualization is a first class citizen.

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu: 97E81F99-EBB6-4A27-8BE8-EA7A3C168EF4/2016-11-29_19-27-08
  - host distribution and version (Windows version, build number, etc): Windows 10 Pro, build 14393.447
  - Docker for Windows version: 1.12.3-beta30.1 (8711)

### Steps to reproduce the behavior

  1. Start Docker for Windows, wait for it to crash (red tray icon)
  2. Open Hyper-V Manager, note MobyLinuxVM is running but has no IP address assigned
  3. Restart MobyLinuxVM in Hyper-V manager, repeat until it gets an IP
  4. Kill Docker for Windows in Task Manager
  5. Restart Docker for Windows, and everything is fine

**Comment by robrich** [comment]
Unlike https://github.com/docker/for-win/issues/247, I'm not starting Docker on boot.  The machine is running Outlook and Chrome, but I've not noticed a substantial system load when launching Docker.

**Comment by robrich** [comment]
It seems I may have duplicated https://github.com/docker/for-win/issues/54.  If you'd like, I'll close this and "me too" on that issue instead.

**Comment by dgageot** [comment]
@robrich yes please! I'll close the issue. You can had your diagnostic id to #54
