### ISSUE TITLE
I'm not able to start the docker using linux container in windows machine 

### ISSUE THREAD

**Issue by sarathTest** [docker/for-win#2662]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by sarathTest** [comment]
You are trying to start Docker but you don't have enough memory. Free some memory or change your settings. I'm try to create a Linux container in windows machine .but throw out of memory error how to allocate memory for Linux container

**Comment by mat007** [comment]
Click on the whale in you taskbar and open the `Settings`, then select `Advanced` and try increasing the memory allocated to Docker.
