### ISSUE TITLE
Docker Daemon is not running

### ISSUE THREAD

**Issue by BharathMannem** [docker/for-win#2671]
Windows 10 Pro
PS C:\WINDOWS\system32> docker --version
Docker version 18.06.1-ce, build e68fc7a

PS C:\WINDOWS\system32> docker ps
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.38/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

**Comment by Casraw** [comment]
Run this as Administrator

**Comment by Casraw** [comment]
Yes, but try also cmd. Like dockerd in powershell and docker in cmd. And stop the service when you start with that.

**Comment by medbelkheiri** [comment]
Same issue happening to me. Tried different options and doesn't solve it : 
- Option 1 : Run through PowerShell with and without admin elevation
- Option 2 : Run it through cmd

**Comment by Casraw** [comment]
Ok what says dockerd? When your runn it in powershell (Do you have the nat interface, do you stop the service....)??

**Comment by QUDUSKUNLE** [comment]
same issue with me.

**Comment by RajeswariMamilla** [comment]
Same here

**Comment by rquintino** [comment]
Hi, I solved this running the docker for windows (dekstop app), as administrator (not the docker command)
like this:

![image](https://user-images.githubusercontent.com/10835742/47120717-99e22800-d267-11e8-876c-cf97e8adcd53.png)

hope it helps!
(was working fine, don't what caused this, update?)

**Comment by benktesh** [comment]
I had to go through this problem.
I was able to resolve this by switching the docket daemon. 
cd "C:\Program Files\Docker\Docker"
./DockerCli.exe -SwitchDaemon

The solution was in [https://github.com/docker/for-win/issues/1825]

**Comment by pcimring** [comment]
> Hi, I solved this running the docker for windows (dekstop app), as administrator (not the docker command)
> like this:
> 
> ![image](https://user-images.githubusercontent.com/10835742/47120717-99e22800-d267-11e8-876c-cf97e8adcd53.png)
> 
> hope it helps!
> (was working fine, don't what caused this, update?)

Worked for me (after restarting, logging in, and generally jumping through several hoops :)
Tx!

**Comment by Ankit3794** [comment]
`mofcomp.exe C:\Windows\System32\wbem\NetNat.mof`

worked for me!

**Comment by piyushbag** [comment]
@Ankit3794 getting the below error while running the above command
```
Microsoft (R) MOF Compiler Version 10.0.18362.1
Copyright (c) Microsoft Corp. 1997-2006. All rights reserved.
Parsing MOF file: C:\Windows\System32\wbem\NetNat.mof
MOF file has been successfully parsed
Storing data in the repository...
An error occurred while processing item 1 defined on lines 5 - 12 in file C:\Windows\System32\wbem\NetNat.mof:
Error Number: 0x80041003, Facility: WMI
Description: Access denied
Compiler returned error 0x80041003
```
