### ISSUE TITLE
An error occurred

### ISSUE THREAD

**Issue by frontbear** [docker/for-win#2674]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 842422D0-C138-4EE8-B15E-5540ACC0658D/20181001183002

### Expected behavior
ok
### Actual behavior
![image](https://user-images.githubusercontent.com/35812002/46283958-a3ea0280-c5a8-11e8-8dba-2d65991f0178.png)

### Information

  - Windows Version: windows 10 1803
  - Docker for Windows Version: Version 18.06.1-ce-win73 (19507)
![image](https://user-images.githubusercontent.com/35812002/46284066-11962e80-c5a9-11e8-83ce-f1783ba76f9a.png)

![image](https://user-images.githubusercontent.com/35812002/46284053-00e5b880-c5a9-11e8-952d-fe327c5909f3.png)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Casraw** [comment]
Try use LinuxKit

**Comment by MarkHoo** [comment]
![image](https://user-images.githubusercontent.com/30554560/63491468-d7e45400-c4e9-11e9-9eee-e90e06ae9dc2.png)
