### ISSUE TITLE
Question: Run Docker as a Windows Service (without logging in) possible ?

### ISSUE THREAD

**Issue by Xyaren** [docker/for-win#2675]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 47D67653-C501-466F-88B9-DBDE3140076F/20181001215216

### Expected behavior

- When the System boots, all containers having restart always ( or unless-stopped) will automatically start,
without the user having to log in.
- When the user logs out, all containers will still be reachable from other devices.

### Actual behavior

Container starting only when user logs in and exits (stops responding) when the user logs out.

  - Windows Version: Windows Server 2016 10.0.14393
  - Docker for Windows Version: 2.0.0.0-beta1-win75 (19925) (Tried with Stable aswell)

### Steps to reproduce the behavior

  1. Start any container with a Web Interface
  2. Log out
  3. Open Address in Browser on 2nd Machine -> Timeout

**Comment by adrian-j-programmer** [comment]
Any chance to reopen this? Without this, docker cannot be used without human supervision or premium paid 3rd party software on windows machines.

**Comment by souchprod** [comment]
This issue should not be closed !
