### ISSUE TITLE
Error: A firewall is blocking file sharing between Windows and the containers

### ISSUE THREAD

**Issue by dzei** [docker/for-win#2677]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 52ED87FF-A339-471A-B711-E6A2B4CDE7D2/20181002090201

### Expected behavior
Share drives on Windows 10 should succeed

### Actual behavior
Error: A firewall is blocking file sharing between Windows and the containers

### Information
I've tried the following workarounds / steps but the problem persists:
https://success.docker.com/article/error-a-firewall-is-blocking-file-sharing-between-windows-and-the-containers
http://stackoverflow.com/questions/42203488/settings-to-windows-firewall-to-allow-docker-for-windows-to-share-drive/43904051#43904051
http://blog.medhat.ca/2017/01/docker-on-windows-10-error-firewall-is.html
http://www.kajabity.com/2017/08/unblock-docker-for-windows-firewall-issues-with-host-volumes/

Seems to be ongoing issue, here's a few more duplicate issues
Error: A firewall is blocking file sharing between Windows and the containers #2512
Upgraded and Can't share drive with docker I get: Error: A firewall is blocking file Sharing between Windows and the containers #2527
Windows 10: Docker for Windows: unable to share drive #2549
Windows 10: Docker for Windows: unable to share drive #690
Cannot Share drives Windows10 #1801
Unable to share drives #803
Windows 10 - Firewall Share C:\ Drive Blocking Problem - Many Proposed Solution Attempted #2628
Drive sharing seems to be blocked by a firewall #2629
New install of Windows 10 and Docker, unable to share drive false firewall error #2369
Error: A firewall is blocking file Sharing between Windows and the containers #355
firewall is blocking file sharing between windows and the containers #2159
Unable to share drive, complains firewall is blocking #738
Sharing drive fails with "Firewall detected" dialog box #345
Unable to share C: Drive [firewall] #466
Share Drive #2198

  - Windows Version:
Windows 10 Enterprise Version 1709 build 16299.665
  - Docker for Windows Version:
Version 2.0.0.0-beta1-win75 (19925)
Channel: edge

### Steps to reproduce the behavior
1. Launch Docker
2. When Docker is running, from 'Shared Drives' select C and click Apply

**Comment by samiulanik** [comment]
I am also having exact same issue. Tried lots of thing, nothing works.

**Comment by Ultronvision** [comment]
I have also same issue firewall blocking, searching a lot but found nothing, I am using Docker version 18.06.1-ce, build e68fc7a at Window 10 pro.

**Comment by dzei** [comment]
Update:

Our IT support created a new group policy for F-Secure that allows me to turn firewall off. After disabling firewall sharing drives on Docker works alright but firewall needs to be disabled whenever trying to mount anything to a container.

**Comment by ThinhTT84** [comment]
I have windows 10 1803, Firewall is off (both Windows Defender & McAfee Endpoint Security) but still cannot share the driver. I tried to uninstall File and Print sharing service on the Hyper-V virtual network card as suggestion in document but cannot do it.

**Comment by dzei** [comment]
> I have windows 10 1803, Firewall is off (both Windows Defender & McAfee Endpoint Security) but still cannot share the driver. I tried to uninstall File and Print sharing service on the Hyper-V virtual network card as suggestion in document but cannot do it.

1. First turn off Docker (wait until completely closed)
2. Disable Firewall
3. Turn on Docker
4. Share drive

**Comment by ThinhTT84** [comment]
> First turn off Docker (wait until completely closed)
Disable Firewall

I have firewall completely off from beginning already :(.

**Comment by piobrien** [comment]
I'm having this issue because the VM is trying to use SMB v1 to connect to the C: Share but our enterprise has disabled SMB v1 due to age and security issues.

You can verify if this is the issue by checking the following registry key: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters and seeing if the key SMB1 is set to 0 or not.

Whilst enabling SMB v1 can resolve the issue its been disabled by default in Windows 10 for good reason and a more permanent fix is needed.

**Comment by piobrien** [comment]
Do you have the SMB components installed, Windows 10 doesn't have these installed by default?

You can check with this powershell: 
**Get-WindowsOptionalFeature –Online –FeatureName SMB1Protocol**

If you choose to install SMB v1 you could use this command (however I don't recommend it): 
**Enable-WindowsOptionalFeature -Online -FeatureName SMB1Protocol**

In my environment I have the feature installed however group policy disables SMB v1 which prevents the  file sharing from working.

**Comment by piobrien** [comment]
Interesting, I followed these instructions and it worked for me https://github.com/docker/for-win/issues/313#issuecomment-339202384

**Comment by dzei** [comment]
> Interesting, I followed these instructions and it worked for me [#313 (comment)](https://github.com/docker/for-win/issues/313#issuecomment-339202384)

Sharing is possible with local admin rights but after applying changes it won't persist and volume remains unshared.

**Comment by dzei** [comment]
> Whilst enabling SMB v1 can resolve the issue its been disabled by default in Windows 10 for good reason and a more permanent fix is needed.

SMB1 seems to be already enabled on my machine. No luck with this workaround.

**Comment by piobrien** [comment]
Confirming https://github.com/docker/for-win/issues/313#issuecomment-339202384 works for me after a reboot and with SMB v1 disabled.

**Comment by tonyhxh** [comment]
SMB v1 is disabled by our GPO, and wondering if there is any other solution?

**Comment by tonyhxh** [comment]
Also tried following from #313, no luck. 

Navigate to C:\Users\Public\Documents\Hyper-V (it will ask administrative permission)
Click on folder "Virtual hard disks"
Here you will find "MobyLinuxVM.vhdx", just right click on it and goto context menu "Share with -> Advanced sharing settings..."
There you just go ahead and enable sharing under Public folder sharing blade and that's it.

**Comment by tonyhxh** [comment]
Finally the suggestions in #466 saved my day. In my case SMB V1 is disabled through GPO, and I tried a lot of solutions mentioned in github, but none of them works for me. The solutions from #466 did the job. Thanks for the great works from @jjqq2013 and @tlecomte!

**Comment by dzei** [comment]
In our case solution was to create a policy for F-Secure that allows filesharing from networks 192.168.65.0/24, 10.0.75.0/24 ja 127.0.0.1

I'll have to dig into if those IP's are out-the-box or specific to my current network configuration. In other words, we'll test the same policy from an another developer's workstation.

**Comment by RobinHSanner** [comment]
I am also having this issue.  I've tried all the workarounds with no success.  I even turned off my Norton Firewall and still had the same issue

**Comment by RobinHSanner** [comment]
I am having the same issues. I have tried all the workaround with no luck including turning off my firewall

/remove-lifecycle stale

**Comment by alphabytes** [comment]
facing the same issue... tried all the suggested solutions above, none of them worked.

**Comment by RobinHSanner** [comment]
A fellow worker clued me in on how to fix it.  Create a local account (note that this isn't a domain account with local administrators access) with membership in the groups 'Administrators' (the local one) and 'docker-users'.  Then when Docker prompts for credentials enter the credentials of your local administrator account.  I use Norton Smart Firewall and to get to the point where it would prompt me for credentials I still had to do the firewall exception thing.

**Comment by oscar6echo** [comment]
Same here.  
I'm not able to create a local account as it is a corporate machine.  
In this context, it seems there is no way to share local drives...

**Comment by rdagumampan** [comment]
We had similar issue and this blocking us from exploring SQL Server on containers for dev machines. Our devs runs on windows with Docker CE. The issue seems to have been existing for years with no clear resolution.

**Comment by LisaBurleson** [comment]
I've tried all the solutions proposed and still no joy. Docker works fine on my home computer, but it won't work on my work laptop (which has the firewall turned off). I have admin rights.  I've uninstalled and re-installed a couple times just to be sure. I guess I just can't use it on this machine. Or I just copy all the files into the docker image and don't mount a local drive.

**Comment by djbios** [comment]
Not working on my home PC. Interesting noticed: when I trying to share my C drive manualy (in explorer), after that, I see it in \\10.0.75.1\c , but when I try to check C drive in docker gui for sharing, it shows me "A firewall is blocking file sharing between Windows and the containers", and disable my manually created sharing.

**Comment by var23rav** [comment]
For Cisco Any-Connect(vpn) client try [this solution](https://github.com/docker/for-win/issues/345#issuecomment-496113245)

**Comment by coltenkrauter** [comment]
Open powershell as admin and run this,
```
Set-NetConnectionProfile -interfacealias "vEthernet (DockerNAT)" -NetworkCategory Private
```

**Comment by LisaBurleson** [comment]
I just tried that solution and it didn't change the firewall message. I tried messing with the .docker folder permission per https://github.com/docker/for-win/issues/3385  and that didn't work either. The search continues... 
Thanks for the suggestion.

**Comment by Amro-Hassan** [comment]
@coltenkrauter  solution worked for me.

**Comment by abmptit** [comment]
I tried all workaround, any new clues plz?

**Comment by ndywicki** [comment]
Same issue, I've already tests  all sugestions.

I can telnet my SMB service on 445, but I can't change the network caterory (NLM Policies group): 

````
PS C:\WINDOWS\system32> Set-NetConnectionProfile -interfacealias "vEthernet (DockerNAT)" -NetworkCategory Private
Set-NetConnectionProfile : Unable to set the NetworkCategory due to one of the following possible reasons: not running
PowerShell elevated; the NetworkCategory cannot be changed from 'DomainAuthenticated'; user initiated changes to
NetworkCategory are being prevented due to the Group Policy setting 'Network List Manager Policies'.
Au caractère Ligne:1 : 1
+ Set-NetConnectionProfile -interfacealias "vEthernet (DockerNAT)" -Net ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (MSFT_NetConnect...9B5E1E4E54DE}"):root/StandardCi...nnectionProfile)
   [Set-NetConnectionProfile], CimException
    + FullyQualifiedErrorId : MI RESULT 2,Set-NetConnectionProfile
````

So, I found how I can mount manually a CIFS volume V3 version like:

````
docker volume create --driver local --opt type=cifs --opt device=//X.X.X.X/C/workspaces/myVolume --opt o=user=XXXX,domain=XX,password=XXXX,vers=3.02 --name myVolume
````
And use it, ex. in docker-compose:

```
services:
   ...
   volumes:
      - myVolume:/PATH_INSIDE_CONTAINER

volumes:
   myVolume:
      # this will use the volume created beforehand
      external: true
```

But is very painful...

**Comment by stephen-turner** [comment]
This is fixed with the new filesharing implementation in 2.2.0.3, so closing this ticket.

**Comment by ndywicki** [comment]
I've update my windows docker client.... And it's work !!!!!
Thank you very much 😍
