### ISSUE TITLE
"The system cannot find the file specified" when executing RUN in "docker build"

### ISSUE THREAD

**Issue by snorrk** [docker/for-win#2679]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 879D4943-8690-4B82-8B42-D1654F57816F/20181002014257

### Expected behavior
"docker build ." completes successfully for the following dockerfile:
FROM microsoft/nanoserver
RUN ["md", "c:/bin"]

### Actual behavior
Error when running "docker build ." using the following dockerfile:
FROM microsoft/nanoserver
RUN ["md", "c:/bin"]

**Container xxxxxxxx encountered an error during CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2)**
[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000] extra info: {"CommandLine":"md c:/bin","WorkingDirectory":"C:\\","CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}

### Information

  - Windows Version: Windows 10 (1809)
  - Docker for Windows Version: Confirmed on latest stable and 2.0.0.0-beta1-win75 (19925)

**I believe this started after trying the experimental --squash argument.**

### Attempted recovery steps

- Update docker config to use a different directory for the Docker graph (along with docker service restart). New directory is populated by Docker but the error persists.
- Uninstall and re-install latest stable release of Docker
- Disable Hyper-V and Containers Windows features, restart, install Docker and let it re-enable the features.
- Run the command while collecting Procmon file system trace. Not able to find anything indicating what file could not be found (the file call might be there but since I have no idea what I'm looking for I probably wouldn't be able to identify it).
- Uninstall Docker, clear out all Windowsfilter directories with "docker-ci-zap.exe", re-install Docker.
- Apply a Windows restore point from before the issue started.
- Run "sfc /scannow". The tool found some issues but the error persisted even after reboot.

Any pointers would be appreciated.

**Comment by Danielovich** [comment]
Shouldn't c:/bin be c:\bin ?

**Comment by snorrk** [comment]
Very embarrassing. I was using incorrect syntax in the RUN function, causing the error.

**Comment by itroupansky** [comment]
Nor embarrassing! Thank you, you helped me solve similar issue!

**Comment by Mutz2** [comment]
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8
WORKDIR /app
ADD myapp /app
ENTRYPOINT ["C:\app\myapp\Simulator\Simulator\binx64\Debug\Simulator.exe"]

I have Docker file like this and getting Error of Cannot find specified file C:\app\myapp\Simulator\Simulator\binx64\Debug\Simulator.exe.

Please suggest the better way of ADD and ENTRYPOINT instruction syntax.
Thanks and regards

**Comment by anoooin** [comment]
Hi @Mutz2 - Did you find a solution for the ENTRYPOINT throwing Cannot find specified file error please.

Thank you,
Anusha

**Comment by Mutz2** [comment]
Hi Anusha, 
No. 
For my problem i reffered an another example which I am referring. Don't know if it helps you.
https://github.com/microsoft/dotnet-framework-docker/tree/master/samples/wcfapp.
