### ISSUE TITLE
Docker for Windows should not set VSmbDisableOplocks registry key

### ISSUE THREAD

**Issue by PatrickLang** [docker/for-win#269]
### Expected behavior
Docker for Windows should not set the registry key `HKLM:SOFTWARE\Microsoft\Windows NT\CurrentVersion\Virtualization\Containers\VSmbDisableOplocks`. That was needed for running Windows Server 2016 TP5 containers on Windows 10. It's no longer needed.

The troubleshooting script published in the [Windows containers documentation](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/troubleshooting) checks for this key and fails if it exists.

```none
Describing Windows container settings are correct
 [-] Do not have DisableVSmbOplock set to 1 73ms
   Expected: {0}
   But was:  {1}
   75:              $regvalue.VSmbDisableOplocks | Should Be 0
   at <ScriptBlock>, <No file>: line 75
```

### Actual behavior
Script should pass, this regkey should be 0 or should not exist

### Information

```none
> docker info

Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.13.0-rc2
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 14965 (14965.1001.amd64fre.rs_prerelease.161104-1700)
Operating System: Windows 10 Enterprise Insider Preview
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 3.999 GiB
Name: DESKTOP-J3HAKNT
ID: SPPO:ZWUE:QPBC:JGBL:LEUM:MS2R:QRGO:7GVV:XRK7:TX56:VM3E:5NBC
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### Steps to reproduce the behavior

  1. Install Docker for Windows beta 31
  2. Invoke-WebRequest https://raw.githubusercontent.com/Microsoft/Virtualization-Documentation/master/windows-server-container-tools/Debug-ContainerHost/Debug-ContainerHost.ps1 -UseBasicParsing | Invoke-Expression

### Related Issues
Also mentioned in https://github.com/Microsoft/Virtualization-Documentation/pull/503 and https://github.com/docker/for-win/issues/90

**Comment by dgageot** [comment]
Thanks @PatrickLang, this was fixed today on master

**Comment by rneugeba** [comment]
Beta32 shipped yesterday should fix this, closing. Please re-open if the issue persists
