### ISSUE TITLE
 failed to create endpoint X on network nat: HNS failed, attempt was made to perform an action in a degraded object

### ISSUE THREAD

**Issue by NAVFreak** [docker/for-win#2690]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F0B24E9C-240D-4DFE-B345-D389DAD29623/2018-10-04_08-53-59

### Expected behavior
Start and install new containers.

### Actual behavior
I get the error message "docker.exe: Error response from daemon: failed to create endpoint X on network nat: HNS failed with error : Ett försök gjordes att utföra en åtgärd i ett degraderat objekt.
ExitCode: 125"

Roughly translated means: "docker.exe: Error response from daemon: failed to create endpoint X on network nat: HNS failed with error : An attempt was made to perform an action in a degraded object."

### Information

  - Windows Version: Windows 10 Pro, version 1803, OS-version 17134.320
  - Docker for Windows Version: 17.09.0-ce-win33 (13620), Channel: stable

I Think the problem started after a windows update.
I have tried to reinstall docker and to reset it to factory settings but nothing helped.

**Comment by marcelbuijs** [comment]
Linux containers are working fine, this happens only with Windows containers.
PS C:\WINDOWS\system32> docker run hello-world
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: failed to create endpoint unruffled_mcnulty on network nat: HNS failed with error : Er is geprobeerd een bewerking uit te voeren op een verslechterd object.
PS C:\WINDOWS\system32>

Diagnostics ID: C4D5A972-74CC-4523-8EAB-4E4C35B09C18/20190313081641 
Latest WIndows 10 version
Docker version 18.09.2
