### ISSUE TITLE
Unable to start docker

### ISSUE THREAD

**Issue by stephane303** [docker/for-win#2692]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID:55FAC378-8F4F-48B4-8435-C7BBD534717F/20181004104731

### Expected behavior
Docker starts normally.
### Actual behavior
Docker display 'An error occured'
### Information

  - Windows Version:  Version 1809 (OS build 17763.1)
  - Docker for Windows Version: 18.06.1-ce-win73

### Steps to reproduce the behavior
  1. Reboot windows
  2. Start Docker

**Comment by the-ress** [comment]
I've got the exact same Windows and Docker versions and I got "Docker doesn't support your Windows version. Check documentation for minimum requirements." after installing Docker and restarting.

**Comment by stephane303** [comment]
I had accidentaly activated the 'Microsoft Insider Preview' .... maybe it's a warning for a future problem ...
I went back to my previous Windows 10 build and everything is good now ...
