### ISSUE TITLE
Windows 10 1809 ERROR

### ISSUE THREAD

**Issue by arigelni** [docker/for-win#2693]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 2BB46962-5098-42B2-99D6-E104B2C4D7B0/20181004105848

### Information

  - Windows Version: Windows 10 1809
  - Docker for Windows Version: Latest CE 18.06.1-ce-win73 (19507)

### Steps to reproduce the behavior

Installation succeeded but startup of "docker-for-windows.exe" fails after upated of windows

**Comment by ckuai** [comment]
I wasn't using new installation, but just after upgrade to winqo 1809, docker can't start. after reinstall, both Docker and Hyper-V (disable feature and re-enable) or running "MOFCOMP %SYSTEMROOT%\System32\WindowsVirtualization.V2.mof", nothing works for me. Until I check 1809 Hyper-V issues. Following MS technet thread solved my issue.

https://social.technet.microsoft.com/Forums/en-US/ee5b1d6b-09e2-49f3-a52c-820aafc316f9/hyperv-doesnt-work-after-upgrade-to-windows-10-1809?forum=win10itprovirt

**Comment by arigelni** [comment]
@ckuai solved it for me!!
