### ISSUE TITLE
Server 2016 - Hello-world not working

### ISSUE THREAD

**Issue by GeorgeIsKing** [docker/for-win#2695]
Hi,

I installed docker on Windows Server 2016. However, when trying to run hello-world, I get the following message PS C:\Windows\system32> docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
bce2fbc256ea: Pull complete
4a14bdf6da80: Pull complete
842bcbb9bd6e: Pull complete
3c15d2487d42: Pull complete
Digest: sha256:0add3ace90ecb4adbf7777e9aacf18357296e799f81cabc9fde470971e499788
Status: Downloaded newer image for hello-world:latest
C:\Program Files\Docker\docker.exe: Error response from daemon: container 284bf141b3d2b1546eb1d9333bb8035ad7a92be97cb1ce06ce6500fce3a47c0d encountered an error during CreateContainer: failure in a Windows system call: The system cannot find
 the path specified. (0x3) extra info: {"SystemType":"Container","Name":"284bf141b3d2b1546eb1d9333bb8035ad7a92be97cb1ce0
6ce6500fce3a47c0d","Owner":"docker","IsDummy":false,"VolumePath":"\\\\?\\Volume{724e0e7a-c7c1-11e8-b815-005056a11b6b}","IgnoreFlushesDuringBoot":true,"LayerFolderPath" :"C:\\ProgramData\\docker\\windowsfilter\\284bf141b3d2b1546eb1d9333bb8035
ad7a92be97cb1ce06ce6500fce3a47c0d","Layers":[{"ID":"0efa1816-268a-5460-9443-f85b06c9b548", "Path":"C:\\ProgramData\\docke
r\\windowsfilter\\00955993be9366ccec09a9c2f347c1bd597c263ce6999232cc6103c30638d4eb"},{"ID":"982fea8c-79f4-5220-bb2a-58ca1b4de06e","Path": "C:\\ProgramData\\docker\\windowsfilter\\115447d114f48ca155e35a8c30fa8ee298595a7235a492cd88107cac646e19e1"},{"ID":"0dfdc0ae-9ad4-5615-8fb9-664096a07c2d","Path": "C:\\ProgramData\\docker\\windowsfilter\\265d92c56687b92055a2b7
860418f4f2c7c9afd867872348f3dcf5510376fa30"},{"ID":"17a67d35-d298-5eae-9e5e-2eadbc4e1ccf", "Path":"C:\\ProgramData\\docker\\windowsfilter\\a203db67df41dc044e1b82ddb767231c6a4085774887914259b0f2f06f67aad8"}],"HostName":"284bf141b3d2","MappedDirectories":[],"HvPartition":false,"EndpointList":["7a800cfe-ed8d-4f58-8c3b-e385bbba1052"],"Servicing":false,"AllowUnqualifiedDNSQuery":true}.

### Expected behavior
I would expect Hello-world to run fine, as it's been doing on other Windows Server 2016 that I've installed it on.

### Actual behavior
I get the above error

### Information
I installed docker on this machine before but deploying a container didn't work and support assisted me with determining that, with the use of docker exec -i <> cmd, the hello-world container wasn't able to ping its own IP, gateway or 127.0.0.1.

I was then told to uninstall docker completely, which I did and deleted C:\ProgramData\docker.

Then reinstalled docker using:
   - Install-Module -Name DockerMsftProvider -Repository PSGallery -Force
   - Install-Package -Name docker -ProviderName DockerMsftProvider (Say A to the untrusted source)
   - Restart-Computer -Force

It was at this point that I'm now with trying to run hello-world and getting the above error.

Windows Server 2016 Standard

docker version
Client:
 Version:      17.06.2-ee-16
 API version:  1.30
 Go version:   go1.8.7
 Git commit:   9ef4f0a
 Built:        Thu Jul 26 16:43:19 2018
 OS/Arch:      windows/amd64

Server:
 Engine:
  Version:      17.06.2-ee-16
  API version:  1.30 (minimum version 1.24)
  Go version:   go1.8.7
  Git commit:   9ef4f0a
  Built:        Thu Jul 26 16:52:17 2018
  OS/Arch:      windows/amd64
  Experimental: false

George

**Comment by gaurav1216** [comment]
I am also getting the same issue after installing docker on window2016. Not able to run hello-world. Saying 
no-matching-manifest-for-unknown-in-the-manifest-list-entries. Please help me out.

**Comment by thaJeztah** [comment]
Looks like the image for Windows 2016 ("RS1") is missing; I did a `docker manifest inspect hello-world` and see only RS4 and RS5 is in the list;

```bash
docker manifest inspect hello-world:latest

....

      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1357,
         "digest": "sha256:04efdea6de289ea7f3d9ddbb8317a82bcd0cfefb397a68a42d53af0737fa74b8",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.17134.706"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1046,
         "digest": "sha256:057a2292b00553b4ab8e090487aaa8068bf8da87abd563875ffcbfadaf2d03ac",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.17763.437"
         }
```

Only `17134` (RS4) and `17763` (RS5) are present. 

(Referring to the list of versions in https://github.com/Microsoft/hcsshim/blob/bb6b18cdb527145747b43a770efdea50491dd1d5/osversion/windowsbuilds.go#L5-L9)

```go
package osversion

const (

	// RS2 was a client-only release in case you're asking why it's not in the list.
	RS1 = 14393
	RS3 = 16299
	RS4 = 17134
	RS5 = 17763
)
```

I'll open a ticket in the issue tracker for the `hello-world` image

**Comment by thaJeztah** [comment]
Opened https://github.com/docker-library/hello-world/issues/56

**Comment by StefanScherer** [comment]
@gaurav1216 you can use `docker/surprise` instead which also looks nicer. Press ESC to stop the container again. 🎉

**Comment by gaurav1216** [comment]
I am able to run docker/surprise.  But not able to run these microsoft/nanoserver ,microsoft/windowsservercore, microsoft/aspnet etc.  If these images doesnot support with window2016 (14393) build. then why they allows to install docker on window2016(14393).
