### ISSUE TITLE
Windows 1809 and Linux Containers throw Error.

### ISSUE THREAD

**Issue by ldrick** [docker/for-win#2697]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4E5D0BFD-6A89-4AB0-B0F2-0C46A9339A37/20181004134505

### Expected behavior
No Error.

### Actual behavior

Error occurs, saying:
`Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer '<mycomputername>' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-Switch, <No file>: line 117
at <ScriptBlock>, <No file>: line 394
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.<>c__DisplayClass25_0.<SwitchDaemon>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 275
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59`

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. Update to Windows 1809
  2. Restart Windows
  3. Use Docker with Linux Containers

**Comment by ldrick** [comment]
Bevor asking, what I tried already, without success:
- disabled Hyper-V, restarted, enabled again and restartet
- uninstalled Docker for Windows and reinstalled it
- disabled Container Feature in Windows and reenabled it

**Comment by ObviousDWest** [comment]
I'm getting the same error. I've uninstalled dfw, reinstalled the same (old) version, reinstalled the latest edge and stable versions.
I've tried the advice in all of these links:
https://shauncassells.wordpress.com/2018/05/24/fix-hyper-v-encountered-an-error-trying-to-access-an-object-on-computer-localhost-because-the-object-was-not-found-the-object-might-have-been-deleted-verify-that-the-virtual-machine-managemen/
https://github.com/docker/for-win/issues/2110
https://github.com/docker/for-win/issues/1077

This might be a Windows/MS error. In an admin powershell, Get-VMHost prints the same error.

**Comment by ObviousDWest** [comment]
Ok. I rolled back Windows to 1803, using these instructions:
https://www.thewindowsclub.com/rollback-uninstall-windows-10-creators-update

Unfortunately, this resets the registry, making uninstalling/reinstalling of docker very difficult. By trial and error, I found that renaming the following registry keys were helpful in getting the latest edge version installed and running (notice that I added "D" in front of Docker, so I could easily put them back if needed). Without these changes, the installer exe refused to run, or threw various errors wrt missing files or directories:
Computer\HKEY_CURRENT_USER\Software\DDocker Inc.
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\DDocker Inc.
Computer\HKEY_USERS\<whatever>\Software\DDocker Inc.
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\DDocker for Windows

What a long day.

**Comment by Monte-Christo** [comment]
Try downgrading Docker before doing something drastic:

1. Uninstall Docker
2. Go to [https://docs.docker.com/docker-for-windows/release-notes/#stable-releases-of-2018](https://docs.docker.com/docker-for-windows/release-notes/#stable-releases-of-2018)
3. Download Docker Community Edition 18.03.1-ce-win65 2018-04-30
4. Install

I was back up and running in no time.

**Comment by ckuai** [comment]
Same issue here. after upgrade to win10 1809, docker can't start. after reinstall, both Docker and Hyper-V (disable feature and re-enable) or running "MOFCOMP %SYSTEMROOT%\System32\WindowsVirtualization.V2.mof", nothing works for me. Until I check 1809 Hyper-V issues. Following MS technet thread solved my issue.

https://social.technet.microsoft.com/Forums/en-US/ee5b1d6b-09e2-49f3-a52c-820aafc316f9/hyperv-doesnt-work-after-upgrade-to-windows-10-1809?forum=win10itprovirt

**Comment by zerah-doan** [comment]
> Same issue here. after upgrade to win10 1809, docker can't start. after reinstall, both Docker and Hyper-V (disable feature and re-enable) or running "MOFCOMP %SYSTEMROOT%\System32\WindowsVirtualization.V2.mof", nothing works for me. Until I check 1809 Hyper-V issues. Following MS technet thread solved my issue.
> 
> https://social.technet.microsoft.com/Forums/en-US/ee5b1d6b-09e2-49f3-a52c-820aafc316f9/hyperv-doesnt-work-after-upgrade-to-windows-10-1809?forum=win10itprovirt

This worked for me
