### ISSUE TITLE
MobyLinuxVM.vhdx'. Error: 'General access denied error'.

### ISSUE THREAD

**Issue by simonm3** [docker/for-win#270]
I ran through the tutorial to create a dockerfile and it did not mention this would copy the entire folder I was working in which was 20GB. I looked at the size of images and containers and they all appeared to be small. So I just deleted the VM file which was taking all the space. However now I can't start docker. How can I recover?

**Comment by dgageot** [comment]
@simonm3 You can reset Docker to its factory settings: https://docs.docker.com/docker-for-windows/#/reset
