### ISSUE TITLE
compose command not working

### ISSUE THREAD

**Issue by diomac** [docker/for-win#2700]
Hi.

The compose command has stopped working. Simply run the command, but nothing happens.

**Comment by brunokunace** [comment]
Same here, i download new version but dont work anymore

![image](https://user-images.githubusercontent.com/16597320/46505150-8dd97d80-c806-11e8-82e5-03801a153486.png)

Please help.

**Comment by brunolm** [comment]
related https://github.com/docker/for-win/issues/2699

**Comment by alexsandro-xpt** [comment]
Same here, definitely nothing happens!

**Comment by diomac** [comment]
Fixed in lasted version. Thank you.
