### ISSUE TITLE
Docker On Windows failure in a Windows system call: No hypervisor is present on this system. (0xc0351000)

### ISSUE THREAD

**Issue by dotnetstep** [docker/for-win#2710]
Docker Version : 2.0.0.0-beta1-win75 (19925)
Channel : Edge

1. I have one local machine with following thing.
 - Windows 10 Enterprise ( Latest Oct 20
- I have enable experimental feature.

Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows 10 Enterprise Evaluation Version 1803 (OS Build 17134.286)
- Now I fire following command

- Docker pull ubuntu 
  It is working fine.

2. Now I have another machine in Azure VM.
- Windows 10 Pro.
- Experimental Feature enable
Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows 10 Pro Version 1803 (OS Build 17134.285)

- Docker pull ubuntu

failed to register layer: failed to start service utility VM (applydiff 535f073b3fcb3bbaba154f0f2a765368d1e68102cbc91f0432984dca7c2cd2eb): container 535f073b3fcb3bbaba154f0f2a765368d1e68102cbc91f0432984dca7c2cd2eb_svm encountered an error during CreateContainer: failure in a Windows system call: No hypervisor is present on this system. (0xc0351000) extra info: {"SystemType":"container","Name":"535f073b3fcb3bbaba154f0f2a765368d1e68102cbc91f0432984dca7c2cd2eb_svm","Layers":null,"HvPartition":true,"HvRuntime":{"ImagePath":"C:\\Program Files\\Linux Containers","LinuxInitrdFile":"initrd.img","LinuxKernelFile":"bootx64.efi"},"ContainerType":"linux","TerminateOnLastHandleClosed":true}

**Comment by snorrk** [comment]
What Azure VM type are you using? I believe not all Azure VM types support nested virtualization (see https://docs.microsoft.com/en-us/azure/virtual-machines/windows/nested-virtualization).

**Comment by viniciusxyz** [comment]
I have this problem in WIndows Hyper V 2019

C: \ Program Files \ Docker \ docker.exe: Error response from daemon: container e7d72971b217f4b22ee9af940de6d76b4d04381ec4bc3db69efbb73eab8ce7b9 encountered an error during CreateContainer: failure in a Windows system call: The request is not supported. (0x32) Extra info: {"SystemType": "Container", "Name": "e7d72971b217f4b22ee9af940de6d76b4d04381ec4bc3db69efbb73eab8ce7b9", "Owner": "docker", "VolumePath": "\\\\? \\ Volume {d78d142f-66db-41f0 -9131-0459ec34f940} "," IgnoreFlushesDuringBoot ": true," LayerFolderPath ":" C: \\ ProgramData \\ docker \\ windowsfilter \\ e7d72971b217f4b22ee9af940de6d76b4d04381ec4bc3db69efbb73eab8ce7b9 "," Layers ": [{" ID ":" ae802614-c1da-58d6 -9ba2-18d50a68dca7 "," Path ":" C: \ ProgramData \\ docker \\ windowsfilter \\ 3979d71906d50d19d132902dadd45cc3ef7a7902f0e6d6a1b412a10415b847a8 "}, {" ID ":" 4ad9f860-63f7-5bcd-b574-fd65e497834d "," Path ":" "HostName": "e7d72971b217", "HvPartition": false, "EndpointList": ["BC377D65-D9D6-419E-BF53-16012E50C3AE"], "C: \\ ProgramData \\ dock \\ windowsfilter \\ 336e6fc7c2c2cb1c4e1d4e09e1d47641e24df8339a8765d9" "AllowUnqualifiedDNSQuery": true}.

- Docker version:
Client:
 Version: 18.03.1-e-5
 API version: 1.37
 Go version: go1.10.6
 Git commit: 10493e3
 Built: Wed Jan 9 05:05:43 2019
 OS / Arch: windows / amd64
 Experimental: false

Server:
 Engine:
  Version: 18.03.1-e-5
  API version: 1.37 (minimum version 1.24)
  Go version: go1.10.6
  Git commit: 10493e3
  Built: Wed Jan 9 05:12:50 2019
  OS / Arch: windows / amd64
  Experimental: false


- Docker info:
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 1
Server Version: 18.03.1-ee-5
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
Operating System: Hyper-V Server 2019 Version 1809 (OS Build 17763.1)
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 4GiB
Name: WIN-T8NVIT6MLPK
ID: VEXN: KMR2: YBQU: 7KAM: BLEO: JDXD: CAYZ: HWG6: GHTI: JTKA: EHBP: OEF7
Docker Root Dir: C: \ ProgramData \ docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

How to reproduce problem:

 - Install Docker:
Install-Module DockerMsftProvider -Force
Install-Package Docker -ProviderName DockerMsftProvider -Force

- Install the required Features
# Enable features required (HNS Service)
Enable-WindowsOptionalFeature -Online -FeatureName HypervisorPlatform
Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform
Will reboot
Set-Service -Name hns -StartupType Automatic
Set-Service -Name docker -StartupType Automatic
cmd / c "sc config docker depend = hns"
Start-Service docker

Try to run any container:
docker run -ti mcr.microsoft.com/windows/servercore powershell

I tested with versions 18.09.1 ​​and 18.03.1-ee-5 of docker and the problem occurs in both.
