### ISSUE TITLE
Docker cannot apply checked shared drives

### ISSUE THREAD

**Issue by AndyBeHere** [docker/for-win#2719]
**Expected behavior**
- I went to Settings->Shared Drives and set checkbox on my F: drive. 
- After i pressed apply and input my user and password, i want to see then checkbox with drive F: is checked.

**Docker version**
![dockerversion](https://user-images.githubusercontent.com/38612236/46668465-15f0c600-cbff-11e8-8588-253c7f5b29fe.jpg)

**Actual behavior**
- I checked the checkbox of F:, and press apply
![1539078598 1](https://user-images.githubusercontent.com/38612236/46668476-1ee19780-cbff-11e8-896f-5f4f3a5ee539.jpg)
- input my user and password
![1539078905 1](https://user-images.githubusercontent.com/38612236/46668487-25700f00-cbff-11e8-8dd0-6edc410ef3ee.jpg)
- the checkbox of F: retireve unchecked
![1539078938 1](https://user-images.githubusercontent.com/38612236/46668504-2ef97700-cbff-11e8-926d-385ecf150387.jpg)

**Inspection of my binded container**
![containerinspect](https://user-images.githubusercontent.com/38612236/46668525-3d479300-cbff-11e8-949d-d2bf749245e7.jpg)

**Docker container logs**
![dockerlogs](https://user-images.githubusercontent.com/38612236/46668531-4173b080-cbff-11e8-8a0e-14e10409de1c.jpg)

**Ways I tried but not wokred**
- close firewall software
- change permission mode of local file to 777
- start UPnP Device Host and SSDP Discovery

**Related issues:**
- https://forums.docker.com/t/volume-mounts-in-windows-does-not-work/10693/9
- https://github.com/docker/for-win/issues/579

**Comment by willnil** [comment]
I have the same issue as well. Tried all suggested solutions but still didnt work.

**Comment by DmitryTronin** [comment]
Disabling "Experimental features" in Daemon settings section helped me.

**Comment by cwenzelg** [comment]
I have the same Issue and no "Experimental features" selected. After Reinstall the checkbox seems to stick but still docker has no Permissions to create mounted directories etc. worked before the last docker update... current Version is: 2.0.0.0-win78 (28905) it worked 3 days ago just fine.

**Comment by PsychoXIVI** [comment]
Same here :C

**Comment by felipemotta** [comment]
I have the same issue, any news about this topic?

**Comment by erssebaggala** [comment]
I had the same issue.  I had to first delete the docker-machine and after that I was able to tick the drive I wanted to share .

**Comment by abkhan5** [comment]
this still seems to be an issue

**Comment by tuukkasarvi** [comment]
Following the steps set out in this article solved the issue for me:
https://tomssl.com/2018/01/11/sharing-your-c-drive-with-docker-for-windows-when-using-azure-active-directory-azuread-aad/

**Comment by Flinze** [comment]
> Following the steps set out in this article solved the issue for me:
> https://tomssl.com/2018/01/11/sharing-your-c-drive-with-docker-for-windows-when-using-azure-active-directory-azuread-aad/

Thanks, this worked for me!

**Comment by Flinze** [comment]
Also wanted to add that my password for my user account on my Windows PC is quite long, and i changed it to something shorter, that worked for me.

**Comment by pakoneko** [comment]
![image](https://user-images.githubusercontent.com/790721/60186312-1e0c9680-985e-11e9-95b4-ad672a1634b4.png)
![image](https://user-images.githubusercontent.com/790721/60186578-a9862780-985e-11e9-85ca-ff25075b825d.png)

https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-access-sharing-and-security-model-for-local-accounts
Win+R run gpedit.msc ->Computer Configuration\Windows Settings\Security Settings\Local Policies\Security Options
Change the **Network access: Sharing and security model for local accounts**  to:
 **Classic - Local users authenticate as themselves**

Then operate on docker.

**Comment by snys98** [comment]
@pakoneko This worked for me. Thanks a lot. 😆

**Comment by bobdanek** [comment]
> 
> 
> 
> https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-access-sharing-and-security-model-for-local-accounts
> Win+R run gpedit.msc ->Computer Configuration\Windows Settings\Security Settings\Local Policies\Security Options
> Change the **Network access: Sharing and security model for local accounts** to:
> **Classic - Local users authenticate as themselves**
> 
> Then operate on docker.

This did **not** work for me.

**Comment by PoojaTrikha** [comment]
@bobdanek: Agree with you. Following this thread for the solution.

**Comment by rjangir** [comment]
stop doing anything and do this

1. Uninstall Docker Desktop(stable)
2. Restart Windows machine
3. Install Docker Desktop(Edge) 
4. issue resolved

**Comment by stephen-turner** [comment]
This should be fixed with the new filesharing implementation in 2.2.0.3, so closing this ticket. Please open a new ticket if there are still problems. Thank you.
