### ISSUE TITLE
docker-machine create does not work in Windows

### ISSUE THREAD

**Issue by zifik** [docker/for-win#272]
### Expected behavior
Docker swarm tutorial for [Install and Create a Docker Swarm](https://docs.docker.com/swarm/install-w-machine/) does not work for Docker in Windows. I simply wish to do some testing with Docker Swarm locally on my Windows 10 machine. I am able to create and run containers as expected with Docker installation. `docker-machine` execution is where things are failing.

### Actual behavior
Upon executing `docker-machine create -d hyperv somename` in an administrator powershell, it waits indefinitely for the new VM to obtain an IP address. My attempts to restart the VM and/or change the virtual switch don't help.

If I open the Hyper-V Manager and select the new VM, then click the **Networking** tab at the bottom, it shows the following:

- **Adapter**: Network Adapter (Dynamic MAC: XX:XX:XX:XX:XX)
- **Connection**: DockerNAT
- **IP Addresses**: <blank>
- **Status**: No communication

### Information

  - Diagnostic ID: F7C7D9CA-F4F2-40F5-99C7-65CC17FF8E41/2016-11-30_19-03-59
  - https://docs.docker.com/swarm/install-w-machine/
  - Windows 10
  - Docker version: 1.13.0-rc2 (I know its beta, didn't work with the stable version either)

### Steps to reproduce the behavior

  1. Install Docker for Windows. 
  2. Try running `docker-machine create -d hyperv somename`

**Comment by friism** [comment]
Here's a Powershell script that does this: https://github.com/docker/labs/blob/master/swarm-mode/beginner-tutorial/swarm-node-hyperv-setup.ps1

And docs: https://github.com/docker/labs/blob/70aaca74374ddc15c94bf7b088df5e17ed2b89ec/swarm-mode/beginner-tutorial/README.md#creating-the-nodes-and-swarm

Let us know if that doesn't get you started.
