### ISSUE TITLE
Cannot run windows containers (Error initializing network controller: HNS failed with error : The handle is invalid. )

### ISSUE THREAD

**Issue by jabbera** [docker/for-win#275]
### Expected behavior

Able to switch to windows docker containers.

### Actual behavior

Daemon won't start:-(

Log contains this error: [12:49:36.415][WindowsDockerDaemon][Info   ] Error starting daemon: Error initializing network controller: Error creating default network: HNS failed with error : The handle is invalid. 

Followed by:
```
[12:49:36.429][DockerDaemonChecker][Error  ] Docker daemon is not running
[12:49:36.434][WindowsDockerDaemon][Error  ] Process died
[12:49:36.474][ApiProxy       ][Info   ] proxy >> GET /_ping
[12:49:36.474][ApiProxy       ][Info   ] Dial name pipe  \\.\pipe\docker_engine_windows
[12:49:36.474][ApiProxy       ][Info   ] open \\.\pipe\docker_engine_windows: The system cannot find the
```

### Information

  - Diagnostic ID: 9035EE83-6225-45D1-A34D-49FB4D1CBF4C/2016-12-01_12-50-36

### Steps to reproduce the behavior

Install docker 1.3.0 on my windows 10 machine. (WinVer: 1607 14393.447)

**Comment by jabbera** [comment]
[NetTrace.zip](https://github.com/docker/for-win/files/625500/NetTrace.zip)

**Comment by friism** [comment]
@jabbera thanks for posting this, can you please also run the DebugContainerhost script and post the results? https://github.com/Microsoft/Virtualization-Documentation/tree/master/windows-server-container-tools/Debug-ContainerHost

We're working on integrating this into the Docker for Windows troubleshooting flow.

**Comment by jabbera** [comment]
[windows_results.txt](https://github.com/docker/for-win/files/625655/windows_results.txt)
[linux_results.txt](https://github.com/docker/for-win/files/625659/linux_results.txt)

**Comment by dgageot** [comment]
@jabbera Can you please close Docker for Windows, run this is an elevated Powershell and then restart Docker for Windows?

```
Get-ContainerNetwork | Remove-ContainerNetwork -Force -ea SilentlyContinue
Get-NetNat | Remove-NetNat -ea SilentlyContinue
```

**Comment by jabbera** [comment]
@dgageot Same issue:

> [13:07:49.867][WindowsDockerDaemon][Info   ] time="2016-12-02T13:07:49.867265600-05:00" level=info msg="Loading containers: start." 
> [13:07:49.927][WindowsDockerDaemon][Info   ] Error starting daemon: Error initializing network controller: Error creating default network: HNS failed with error : The handle is invalid. 
> [13:07:49.936][DockerDaemonChecker][Error  ] Docker daemon is not running
>

**Comment by jabbera** [comment]
@dgageot Just to be clear the powershell cmdlet gives me the same error. I'm unable to add any new container networks (Get-ContainerNetwork returns nothing) at all, let alone get the nat going.

New-ContainerNetwork -Name nat1
New-ContainerNetwork : The handle is invalid.

**Comment by dgageot** [comment]
@jabbera I'm not sure I understand. Can you share the output of this script?
```
Get-ContainerNetwork | Remove-ContainerNetwork -Force
Get-NetNat | Remove-NetNat
```

**Comment by jabbera** [comment]
It doesn't output anything. I'll snap a screenshot in a few minutes

**Comment by jabbera** [comment]
![ss](https://cloud.githubusercontent.com/assets/301208/20859894/751fb9cc-b939-11e6-8fed-3523f6346eae.png)

```
PS C:\WINDOWS\system32> Get-ContainerNetwork | Remove-ContainerNetwork -Force
PS C:\WINDOWS\system32> Get-NetNat | Remove-NetNat
PS C:\WINDOWS\system32> Get-ContainerNetwork
PS C:\WINDOWS\system32> Get-NetNat
PS C:\WINDOWS\system32> New-ContainerNetwork -Name "Test"
New-ContainerNetwork : The handle is invalid.
At line:1 char:1
+ New-ContainerNetwork -Name "Test"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-ContainerNetwork], VirtualizationException
    + FullyQualifiedErrorId : OperationFailed,Microsoft.Containers.PowerShell.Cmdlets.NewContainerNetwork

PS C:\WINDOWS\system32>
```

**Comment by dgageot** [comment]
@friism any idea how to fix this?

**Comment by jabbera** [comment]
I reimaged my desktop to "resolve" this so I wont' be able to provide any more information.
