### ISSUE TITLE
Docker not properly automatically adding users to docker-users group on installation

### ISSUE THREAD

**Issue by bbodenmiller** [docker/for-win#2755]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

One should be able to easily install and use Docker

### Actual behavior

User must install Docker then manually add themselves to `docker-users` group otherwise you get below error

```
docker: error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.38/containers/create: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
See 'docker run --help'.
```

### Information

  - Windows Version: 
  - Docker for Windows Version: 

### Steps to reproduce the behavior

  1. Install Docker
  1. Try to use Docker
  1. Fails to work

**Comment by natejgardner** [comment]
Windows: RS3 16299.666
Docker Engine: 18.06.1-ce-win73 19507
