### ISSUE TITLE
ERROR: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.

### ISSUE THREAD

**Issue by sampeson** [docker/for-win#2766]
After using Docker for windows with set of containers having 1000 ports exposed, putting them up and down I get eventually error:
ERROR: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.

NOTE! Workaround is to restart Docker from tasktray (wonder why it is painly slow).

  - [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 4094CF1C-53D7-4B4A-9E82-EFCB26E8943D/20181019092843

### Expected behavior
Starting and stopping of containers should work and it should not get out of sockets.

### Actual behavior
Sockets are used, getting error `ERROR: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.` all the time.

### Information
  - Is it reproducible? Yes, happens eventually.
  - Is the problem new? There is bug report #320 but have been closed, made new one.
  - Did the problem appear with an update? Not known.
  - Windows Version: Window 10 Enterprise version 1803 OS build 17134.345
  - Docker for Windows Version: Version 18.06.1-ce-win73 (19507)

### Steps to reproduce the behavior
1. Create compose file with this kind of ports configuration:
```
    ports:
      - "80:80"
      - "5038:5038"
      - "5060:5060/udp"
      - "10000-11000:10000-11000/udp"
```
2. Used this kind of networks configuration:
```
    networks:
      - test-net

   networks:
     test-net:
        driver: bridge
```
3. Create several services like that and start and stop

**Comment by deevodavis71** [comment]
This also happens regularly on Docker for Windows 2016, version "Docker version 18.06.1-ce, build e68fc7a" requiring a restart of the Docker daemon. It seems to be related to the system being up for just under 2 weeks. We originally had an issue on 2016 when we weren't running Docker as Administrator where it would die after a week. Now we run as Administrator, but as it stays up longer now we end up running out of sockets. Needs a fix ASAP as this is a critical issue IMHO.
