### ISSUE TITLE
docker 1.13.0-rc2: MobyLinuxVM doesn't get an IP

### ISSUE THREAD

**Issue by robrich** [docker/for-win#277]
Machine is Windows 10 Pro build 14393.447
Docker for Windows version 1.12.3-beta30.1

Using Docker for Win 1.12.3-beta30.1 (see https://github.com/docker/for-win/issues/265) I would often get the message "failed to get an IP 60 times".  Restarting the VM a few times in the Hyper-V manager would solve the concern.

After upgrading to Docker for Win 1.13.0-rc2, Docker no longer crashes on startup, and `docker run ...` now starts containers just fine.  But the VM doesn't get an IP address -- even after many restarts.  So I can't browse to running containers.  Diagnostic id `97E81F99-EBB6-4A27-8BE8-EA7A3C168EF4/2016-12-02_08-41-13`.

`docker-machine create --driver hyperv machine` creates the machine successfully but times out with message `This machine has been allocated an IP address, but Docker Machine could not
reach it successfully.`  Looking at Hyper-V manager, it got IPv6 address `fe80::215:5dff:febc` suggesting docker-machine create didn't wait long enough.  After running `@FOR /f "tokens=*" %i IN ('docker-machine env machine') DO @%i`, then running `docker pull node` errors with:

```
time="2016-12-02T09:04:31-07:00" level=warning msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:38020->[::1]:53: read: connection refused
```

**Comment by rneugeba** [comment]
@robrich I'm a little confused by the description. You say that `docker run` works for you now when using Docker for Windows. That's great. And from the logs it does look also that it is working.

But, where do you see that the VM doesn't get an IP address?

Also, with Docker for Windows you do not need to use `docker-machine` anymore. Docker for Windows creates and manages it's own virtual machine and it should just work when you start the application

**Comment by robrich** [comment]
I open the Hyper-V manager, choose the MobyLinuxVM, switch to the Networking tab, and it correctly shows DockerNAT connection, but it shows a blank space where the IP should be.

**Comment by rneugeba** [comment]
@robrich that's fine and expected in Beta31. We disabled the integration service in the VM which reports the IP address so the host can't determine the IP address anymore (it doesn't really need to)

Is everything else working for you?

**Comment by robrich** [comment]
Nope.  I fire up a docker container for a hello-world express app, hit `localhost:3000` and get a timeout.  If I knew the Docker VM IP, I'd try `that_ip:3000`, but ... hidden both from Hyper-V manager and `docker-machine`.

**Comment by rneugeba** [comment]
you don't need the IP. Ports from containers should be exposed on localhost.  `docker-machine` is not relevant in this context.

Could you provide the steps to reproduce your issue, like dockerfiles/compose files etc

**Comment by robrich** [comment]
Fail on me.  I forgot the `-p 3000:3000`.  It works like a charm.  Closing...
