### ISSUE TITLE
Docker don's work right after update Win 10 to 1809

### ISSUE THREAD

**Issue by Muntzer** [docker/for-win#2770]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 
    4D31A032-2D61-4972-BFA7-C6FA515375B3/20181019134413

### Expected behavior
Docker works.
### Information

  - Windows Version: Microsoft Windows 10 Pro 64bits
     Versión  10.0.17763 N/D Compilación 17763
     Hyper-V is present and Active
  - Docker for Windows Version:
Docker Community Edition
Version 18.06.1-ce-win73 (19507)
Channel: stable
b0f14f1

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Muntzer** [comment]
Please, any update about this issue ?
Thanks,

**Comment by FJavierL** [comment]
Hi,
If somebody will have the same problem, I resolved it apply this:
https://social.technet.microsoft.com/Forums/en-US/ee5b1d6b-09e2-49f3-a52c-820aafc316f9/hyperv-doesnt-work-after-upgrade-to-windows-10-1809?forum=win10itprovirt
