### ISSUE TITLE
Docker does not start after installing Windows 1803 update

### ISSUE THREAD

**Issue by HayDegha0917** [docker/for-win#2774]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Docker should start

### Actual behavior

I get the error documented in (closed) Issue #214.

### Information

  - Windows Version: 10 Enterprise Version 1803 (10.0.17134 Build 17134)
  - Docker for Windows Version: 18.06.1-ce-win73 (19507)

Note that this exact version of Docker was already installed and working fine prior to the Windows update.

It is reproducible. I was able to work around it using the suggestion posted in Issue #214 by @jerryau in Feb. 14, 2017.

### Steps to reproduce the behavior

  1. Start Docker prior to Windows Update. Everything looks good.
  2. Apply Windows patch
  3. Docker will not start and display error listed in Issue #214.

I tried to fix in the following ways without any success:

* Tried resetting to factory settings using the button in the error dialog box
* Tried uninstalling Docker and re-installing from a freshly downloaded installation package
* Tried uninstalling Docker and deleting related Windows registry setting, as well as cleaning out c:\Program Files\Docker (was not aware of C:\ProgramData\Docker, hence I did not clean that out).

Finally, I tried the suggestion in Issue #214 and that worked.

**Comment by github-cuongvm** [comment]
The same :( my issue was deleted
