### ISSUE TITLE
Crash when starting up w/ Windows Containes - Index was outside the bounds of the array

### ISSUE THREAD

**Issue by hhaperfion** [docker/for-win#2778]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F6791DEA-46A1-488E-AD25-5599D41F2A01/20181021091751

### Expected behavior
When I start Docker, it should run.

### Actual behavior
I receive error "Index was outside the bounds of the array". 
The call stack mention problems in Docker.Backend.DnsUpdater.PatchSystemHosts.
I cannot start / run Docker for Windows

### Information
My Docker from version 17 something worked. When I upgraded to 18.06 (latest), this error occured when I switch to Windows containers. It also occur when I select to swicth to Windows containes during installation. 

I have also tried previous v18 versions as well as the Edge build. 
I have removed Container and Hyper-V feature from Windows 10 and enabled again. 
I have tried disabling Firewall and given Everyone full control on hosts Windows file (temporarly)

I am running Windows 10 Pro with all available updates installed. 

  - Windows Version: Windows 10 Pro
  - Docker for Windows Version: Docker Community Edition 18.06.1-ce-win73 2018-08-29

### Steps to reproduce the behavior

I am not sure how to reproduce this - I don't know why it occurs.

**Comment by KwalityKoder** [comment]
I am seeing the same error using the Edge version of DfW 2.0.0.0-beta1-win75 2018-09-14,
I have two Linux containers running using docker compose, at the point where I attempt to switch to Windows Containers.

**Comment by KwalityKoder** [comment]
The problem appears to be Docker for Windows not having permissions to edit the \etc\hosts file.
One possible workaround is to edit the hosts file yourself. I changed mine as follows:

From
     127.0.0.1 localhost
     127.0.0.1 localhost host.docker.internal
To
      172.19.112.107 localhost
      172.19.112.107 host.docker.internal
      172.19.112.107 gateway.docker.internal

[Obviously use the ip address reported by ipconfig instead of the ip address shown.]

After doing that I can now use the "Switch to Windows Containers..." option in Docker for Windows.
