### ISSUE TITLE
Unable to start: 已停止该运行的命令，因为首选项变量“ErrorActionPreference”或通用参数设置为 Stop: “MobyLinuxVM”无法更改状态。  对象正在使用时无法执行此操作。 在 Start-MobyLinuxVM、<无文件> 中: 第 300 行 在 <ScriptBlock>、<无文件> 中: 第 395 行    在 Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:行号 36    在 Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:行号 77    在 Docker.Actions.<>c__DisplayClass18_0.<ResetToDefault>b__0() 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:行号 137    在 Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:行号 59

### ISSUE THREAD

**Issue by ziperlee** [docker/for-win#2779]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:E0E98252-12CB-4412-8BA6-D038BACA19D0/20181021221217

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. i try to remove images to D:, however, docker can never start after i modify C:User/user/.docker/deamon.json, even though i modify the file back
  2. i have tried Reload docker， but it is never work

**Comment by mat007** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?

**Comment by ziperlee** [comment]
docker error message:
Unable to start: 已停止该运行的命令，因为首选项变量“ErrorActionPreference”或通用参数设置为 Stop: “MobyLinuxVM”无法更改状态。

对象正在使用时无法执行此操作。
在 Start-MobyLinuxVM、<无文件> 中: 第 300 行
在 <ScriptBlock>、<无文件> 中: 第 395 行
   在 Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:行号 36
   在 Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:行号 77
   在 Docker.Actions.<>c__DisplayClass16_0.<Start>b__0() 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:行号 61
   在 Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:行号 59

**Comment by lycanthropes** [comment]
Have you solved this problem? I also meet this problem now.
