### ISSUE TITLE
In Docker for Windows, docker-compose run fails to set up link aliases

### ISSUE THREAD

**Issue by forevermatt** [docker/for-win#278]
### Expected behavior
Be able to communicate from one container to another container using a [link alias](https://docs.docker.com/compose/compose-file/#/links) defined in a docker-compose.yml file (version 2 syntax) when the first container was accessed via `docker-compose run`.

### Actual behavior
Cannot ping the 2nd container from the first container (accessed via `docker-compose run`) using the 2nd container's link alias.

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
    5E977760-88E4-43AF-8A65-298BB8165BB9/2016-12-02_11-36-45

  - a reproducible case if this is a bug, Dockerfiles FTW
    (see below)

  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

Windows 10 Pro x64
Docker for Windows 1.12.3 (8488)
```
/ # PS E:\Projects\(TEMP)> docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64
```
Docker Compose 1.9.0
```
PS E:\Projects\(TEMP)> docker-compose --version
docker-compose version 1.9.0, build 2585387
```

Note that this problem is only apparent for me under Docker for Windows and when using `docker-compose run`. The link aliases work fine when running docker within an Ubuntu VM (such as ia VirtualBox/Vagrant), and it works fine even under Docker for Windows when using `docker-compose exec`.

### Steps to reproduce the behavior

  1. Install Docker for Windows (1.12.3).
  2. Download `docker-compose-Windows-x86_64.exe` from <https://github.com/docker/compose/releases/tag/1.9.0> and place it at `C:\Program Files\Docker\Docker\resources\bin\docker-compose.exe` (replacing the existing docker-compose.exe file). 
    - This is to get past the `Interactive mode is not yet supported on Windows` error.
  3. Copy the following into a `docker-compose.yml` file in some folder on your computer.

    version: '2'
    services:
        one:
            image: alpine
            links:
                - two:alias.to.two
            command: top -b

        two:
            image: alpine
            command: top -b

  4. Open some kind of terminal in that folder (I used PowerShell for this example, but have also used Git-Bash).
  5. Run `docker-compose run --rm one sh`.
  6. In the shell of that docker container, run `ping two` to prove that the service name works.

    / # ping two
    PING two (172.19.0.2): 56 data bytes
    64 bytes from 172.19.0.2: seq=0 ttl=64 time=0.078 ms
    64 bytes from 172.19.0.2: seq=1 ttl=64 time=0.153 ms

  7. Still in the shell of that docker container, run `ping alias.to.two` to see the problem.

    / # ping alias.to.two
    ping: bad address 'alias.to.two'

  8. To prove that it just affects `run` not `exec`, run `docker-compose up -d`, then `docker-compose exec one sh` and `ping alias.to.two` (that ping will work).

**Comment by rneugeba** [comment]
thanks for the detailed report. I can repro this with Beta31 which comes with docker-compose 1.9. I suspect an issue with `docker-compose` and will ping the team but maybe also @djs55 can take a look?

I've installed `drill` in the alpine container with `apk update && apk add drill` and then in the container:
```
/ # drill two
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 52681
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;; two. IN      A

;; ANSWER SECTION:
two.    600     IN      A       172.18.0.2

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; SERVER: 127.0.0.11
;; WHEN: Fri Dec  2 23:29:00 2016
;; MSG SIZE  rcvd: 40
/ # drill alias.to.two
;; ->>HEADER<<- opcode: QUERY, rcode: NXDOMAIN, id: 8657
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0
;; QUESTION SECTION:
;; alias.to.two.        IN      A

;; ANSWER SECTION:

;; AUTHORITY SECTION:
.       86398   IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2016120202 1800 900 604800 86400

;; ADDITIONAL SECTION:

;; Query time: 60 msec
;; SERVER: 127.0.0.11
;; WHEN: Fri Dec  2 23:29:02 2016
;; MSG SIZE  rcvd: 105
```
and in the logs I see that for the second query the DNS request is forwarded to the external DNS server (it whould resolved locally):
```
[23:30:16.701][VpnKit         ][Debug  ] com.docker.slirp.exe: forwarding to server 8.8.4.4:53
[23:30:16.702][VpnKit         ][Debug  ] com.docker.slirp.exe: forwarding to server 8.8.8.8:53
```

While in Docker for Mac I see:
```
/ # drill two
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 32816
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;; two.	IN	A

;; ANSWER SECTION:
two.	600	IN	A	172.19.0.2

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; SERVER: 127.0.0.11
;; WHEN: Fri Dec  2 23:30:53 2016
;; MSG SIZE  rcvd: 40
/ # drill alias.to.two
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 13198
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;; alias.to.two.	IN	A

;; ANSWER SECTION:
alias.to.two.	600	IN	A	172.19.0.2

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; SERVER: 127.0.0.11
;; WHEN: Fri Dec  2 23:30:56 2016
;; MSG SIZE  rcvd: 58
```

**Comment by rneugeba** [comment]
Using `docker inspect` I see the alias `alias.to.two` is missing on windows:
```
PS> docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS
NAMES
fcde64677743        alpine              "sh"                7 minutes ago       Up 7 minutes
foo_one_run_1
633464b310ab        alpine              "top -b"            51 minutes ago      Up 51 minutes
foo_two_1
PS> docker inspect foo_one_run_1
[...]
       "NetworkSettings": {
           "Bridge": "",
           "SandboxID": "df2f0f35dd8995353bc20c91c7c29cd68bc336fd01152d45a173280aacecf7f8",
           "HairpinMode": false,
           "LinkLocalIPv6Address": "",
           "LinkLocalIPv6PrefixLen": 0,
           "Ports": {},
           "SandboxKey": "/var/run/docker/netns/df2f0f35dd89",
           "SecondaryIPAddresses": null,
           "SecondaryIPv6Addresses": null,
           "EndpointID": "",
           "Gateway": "",
           "GlobalIPv6Address": "",
           "GlobalIPv6PrefixLen": 0,
           "IPAddress": "",
           "IPPrefixLen": 0,
           "IPv6Gateway": "",
           "MacAddress": "",
           "Networks": {
               "foo_default": {
                   "IPAMConfig": {},
                   "Links": null,
                   "Aliases": [
                       "one",
                       "fcde64677743"
                   ],
                   "NetworkID": "5781b5ee0a5bec0ef231e7676f3bb33d40ddb4953e06729a1e2d3798ed461b6d",
                   "EndpointID": "ebdcc54d6f468bb355bc5bf6679dedfa3b45e6a79cb17f28174a499479c3ca34",
                   "Gateway": "172.18.0.1",
                   "IPAddress": "172.18.0.3",
                   "IPPrefixLen": 16,
                   "IPv6Gateway": "",
                   "GlobalIPv6Address": "",
                   "GlobalIPv6PrefixLen": 0,
                   "MacAddress": "02:42:ac:12:00:03"
               }
           }
       }
   }
``` 


while on Docker for Mac:
```
% docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
7fcf5e3382cc        alpine              "sh"                43 minutes ago      Up 43 minutes                           foo_one_run_1
ded7b1aef969        alpine              "top -b"            57 minutes ago      Up 43 minutes                           foo_two_1
% docker inspect foo_one_run_1
[...]
            "Networks": {
                "foo_default": {
                    "IPAMConfig": null,
                    "Links": [
                        "foo_two_1:alias.to.two",
                        "foo_two_1:foo_two_1",
                        "foo_two_1:two_1"
                    ],
                    "Aliases": [
                        "7fcf5e3382cc"
                    ],
                    "NetworkID": "962fb10f2fa4437cdb163513e0c87250ea52e754a82e82043c29954231708f1f",
                    "EndpointID": "d32a8ae7a48bbaa0ca4a3af724b4f8f4eaec8d42919a46fa746032a5aac6d085",
                    "Gateway": "172.19.0.1",
                    "IPAddress": "172.19.0.3",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:13:00:03"
                }
            }
        }
    }
```

Both use:
```
docker-compose version 1.9.0, build 2585387
```

**Comment by rneugeba** [comment]
closing this issue in favour of https://github.com/docker/compose/issues/4212 which is where the compose team is handling it. @forevermatt thanks for reporting and you may want to watch the issue for progress

**Comment by forevermatt** [comment]
Sounds good. Thanks!
