### ISSUE TITLE
Docker periodically not connecting

### ISSUE THREAD

**Issue by cmeiklejohn** [docker/for-win#2785]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics: No way to generate / upload diagnostics for this issue.  No debugging output, as show below.

### Expected behavior

Docker should always answer on the TCP port when it's listening on the port.

### Actual behavior

It does not.  Every 2 - 3 connections fail, debugging shows no output.  Verified with netcat that the port is listening and answering.

### Information
  - Is it reproducible? Yes
  - Is the problem new? Yes
  - Windows Version: Windows 10 1803
  - Docker for Windows Version: 18.06.1-ce, build e68fc7a

Docker is running in Windows; daemon is exposed and I'm using the Ubuntu docker client inside of Windows Subsystem for Linux.

```
cmeiklejohn@parrhesia:/mnt/c/Users/chris/GitHub/partisan$ date
Mon Oct 22 14:23:16 DST 2018
cmeiklejohn@parrhesia:/mnt/c/Users/chris/GitHub/partisan$ docker -D ps
Cannot connect to the Docker daemon at tcp://0.0.0.0:2375. Is the docker daemon running?
cmeiklejohn@parrhesia:/mnt/c/Users/chris/GitHub/partisan$ docker -D ps
Cannot connect to the Docker daemon at tcp://0.0.0.0:2375. Is the docker daemon running?
cmeiklejohn@parrhesia:/mnt/c/Users/chris/GitHub/partisan$ docker -D ps
Cannot connect to the Docker daemon at tcp://0.0.0.0:2375. Is the docker daemon running?
cmeiklejohn@parrhesia:/mnt/c/Users/chris/GitHub/partisan$ docker -D ps
Cannot connect to the Docker daemon at tcp://0.0.0.0:2375. Is the docker daemon running?
cmeiklejohn@parrhesia:/mnt/c/Users/chris/GitHub/partisan$ docker -D ps
Cannot connect to the Docker daemon at tcp://0.0.0.0:2375. Is the docker daemon running?
cmeiklejohn@parrhesia:/mnt/c/Users/chris/GitHub/partisan$ docker -D ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
cmeiklejohn@parrhesia:/mnt/c/Users/chris/GitHub/partisan$ docker -D ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
cmeiklejohn@parrhesia:/mnt/c/Users/chris/GitHub/partisan$ docker -D ps
Cannot connect to the Docker daemon at tcp://0.0.0.0:2375. Is the docker daemon running?
cmeiklejohn@parrhesia:/mnt/c/Users/chris/GitHub/partisan$ docker -D ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
cmeiklejohn@parrhesia:/mnt/c/Users/chris/GitHub/partisan$ docker -D ps
Cannot connect to the Docker daemon at tcp://0.0.0.0:2375. Is the docker daemon running?
cmeiklejohn@parrhesia:/mnt/c/Users/chris/GitHub/partisan$ docker -D ps
Cannot connect to the Docker daemon at tcp://0.0.0.0:2375. Is the docker daemon running?
cmeiklejohn@parrhesia:/mnt/c/Users/chris/GitHub/partisan$ docker -D ps
Cannot connect to the Docker daemon at tcp://0.0.0.0:2375. Is the docker daemon running?
cmeiklejohn@parrhesia:/mnt/c/Users/chris/GitHub/partisan$ docker -D ps
Cannot connect to the Docker daemon at tcp://0.0.0.0:2375. Is the docker daemon running?
cmeiklejohn@parrhesia:/mnt/c/Users/chris/GitHub/partisan$ docker -D ps
Cannot connect to the Docker daemon at tcp://0.0.0.0:2375. Is the docker daemon running?
cmeiklejohn@parrhesia:/mnt/c/Users/chris/GitHub/partisan$ docker -D ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
cmeiklejohn@parrhesia:/mnt/c/Users/chris/GitHub/partisan$ docker -D ps
Cannot connect to the Docker daemon at tcp://0.0.0.0:2375. Is the docker daemon running?
cmeiklejohn@parrhesia:/mnt/c/Users/chris/GitHub/partisan$ docker -D ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
cmeiklejohn@parrhesia:/mnt/c/Users/chris/GitHub/partisan$ docker -D ps
Cannot connect to the Docker daemon at tcp://0.0.0.0:2375. Is the docker daemon running?
cmeiklejohn@parrhesia:/mnt/c/Users/chris/GitHub/partisan$ docker -D ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
cmeiklejohn@parrhesia:/mnt/c/Users/chris/GitHub/partisan$ date
Mon Oct 22 14:23:37 DST 2018
cmeiklejohn@parrhesia:/mnt/c/Users/chris/GitHub/partisan$
```

**Comment by coderdude1** [comment]
Just tried docker on my work machine after several months of not using it, updated everything to latest and seeing this same behavior.

WSL shell
`➜  ~ docker container ls
Cannot connect to the Docker daemon at tcp://0.0.0.0:2375. Is the docker daemon running?
➜  ~ docker container ls
Cannot connect to the Docker daemon at tcp://0.0.0.0:2375. Is the docker daemon running?
➜  ~ docker container ls
Cannot connect to the Docker daemon at tcp://0.0.0.0:2375. Is the docker daemon running?
➜  ~ docker container ls
Cannot connect to the Docker daemon at tcp://0.0.0.0:2375. Is the docker daemon running?
➜  ~ docker container ls
Cannot connect to the Docker daemon at tcp://0.0.0.0:2375. Is the docker daemon running?
➜  ~ docker container ls
Cannot connect to the Docker daemon at tcp://0.0.0.0:2375. Is the docker daemon running?
➜  ~ docker container ls
Cannot connect to the Docker daemon at tcp://0.0.0.0:2375. Is the docker daemon running?
➜  ~ docker container ls
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
➜  ~ docker container ls
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES`

Everything works fine from powershell.  FWIW, my work machine is running symantec endpoint protection, but this worked fine several months ago.  I'll try to replicate on my home machine tonite

**Comment by vpopescu** [comment]
I am seeing the same thing. I have four containers running for about a week, Then I stopped them, and attempted to start them again. Two managed to start, and two are giving "Is the docker daemon running?" as above.

If I do the 'docker ps' as above, I get the same behavior as in the original problem report.

The port seems to be there, I can reliably telnet to port 2375 from inside the WSL session. So it's not like it lost the port.

Stopping/starting docker or the docker service doesn't fix the issue.
Restarting WSL environment fixes the problem, at least temporarily.
