### ISSUE TITLE
Docker fails to show containers/images: An error occurred trying to connect: Get

### ISSUE THREAD

**Issue by aysark** [docker/for-win#279]
### Expected behavior
Docker respond with listing of containers/images..etc. 

### Actual behavior
I'm using Docker for Windows 10.  It has been working fine for the past 2 months.  Suddenly yesterday, not sure if its because i switched between beta & stable version- but either way, it stopped working correctly.

I have tried uninstalling/reinstalling multiple times docker stable release, i have restart comp, i have disabled/enabled hyper-v to no avail.

When i do `docker ps`:  
```
An error occurred trying to connect: Get http://0.0.0.0:2375/v1.24/containers/json: dial tcp 0.0.0.0:2375: connectex: The requested address is not valid in its context.
```

When i do `docker images`:  
```
An error occurred trying to connect: Get http://0.0.0.0:2375/v1.24/images/json: dial tcp 0.0.0.0:2375: connectex: The requested address is not valid in its context.
```
`docker version`:
```Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      windows/amd64
An error occurred trying to connect: Get http://0.0.0.0:2375/v1.24/version: dial tcp 0.0.0.0:2375: connectex: The requested address is not valid in its context.
```

### Information
Diagnostic ID: B80D073E-1272-43FE-A938-1D30BD7F7790/2016-12-02_10-56-34
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.14393 N/A Build 14393

**Comment by dgageot** [comment]
@aysark Thanks for the report. You should maybe use Docker for Windows Beta 31 instead of the stable channel. It contains a lot of fixes that didn't make it yet to the stable channel.

**Comment by aysark** [comment]
@dgageot i did, i tried beta 31...

**Comment by rneugeba** [comment]
@aysark do you have `DOCKER_HOST` set in your environment? By default the docker CLI should try to connect to the daemon via a named pipe and not via `http://0.0.0.0:2375/`

**Comment by dgageot** [comment]
@aysark Any news?

**Comment by aysark** [comment]
@rneugeba Fixed it, by removing DOCKER_HOST in my env vars, it was set to tcp://0.0.0.0:2375/, not sure why/how.

**Comment by rneugeba** [comment]
thanks. closing
