### ISSUE TITLE
PowerShell scripts can no longer be executed using a Dockerfile

### ISSUE THREAD

**Issue by KiraResari** [docker/for-win#2791]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID (System A): 1C695D26-48A7-43F0-9FB3-3E0461CFBBC6/20181024050927
  - Diagnostics ID (System B): CC9A9BB9-A60A-46B1-BC34-D0726C0481D4/20181024061654

### Expected behavior

PowerShell scripts that have been added to a Windows Container can be executed using a Dockerfile with RUN [Script] 

### Actual behavior

When trying to execute a PowerShell script like this, the container hangs forever without any further feedback, displaying something like:
```
Step 1/3 : FROM microsoft/windowsservercore
 ---> 0534c30e0e3e
Step 2/3 : ADD source C:/source
 ---> 88aa8ed19839
Step 3/3 : RUN C:/source/ByeWorld.ps1
 ---> Running in b851f95db6ee
```

### Information

This first happened on a Dockerfile that I was using before and which worked (or at the very least displayed different errors unrelated to this one), However, today, without having changed anything, this error suddenly started occurring before any others.

  - Windows Version: Windows Server 2016 Datacenter x64, running on an Amazon EC2 Instance
  - Docker for Windows Version: 18.06.1-ce

### Steps to reproduce the behavior

I recreated this lightweight file combination that reproduces the behaviour:

Dockerfile:
```
# Starts with the windows servercore base image
FROM microsoft/windowsservercore

# Adds the Net Framework 3.5 Installation Media
ADD source C:/source

 # Runs the Bye World test program
RUN C:/source/ByeWorld.ps1
```

ByeWorld.ps1
```
echo "    /------------/"
echo "   /            /"
echo "  / Bye World! /"
echo " /            /"
echo "/------------/"
```

File Structure:
```
dockerfile
source
| ByeWorld.ps1
```

I have been able to reproduce this independently on two different systems (both using Amazon EC2)

**Comment by KiraResari** [comment]
I found two workarounds by now:

1. Rewriting the RUN statement as ''RUN powershell -file C:/source/ByeWorld.ps1 ''
2. Adding the statement ''SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]'' in front of the RUN statement

Both of these make this example case work. They don't explain, however, why it wasn'T working in the first place, or why it was working before today.

**Comment by thaJeztah** [comment]
Wondering if something changed in the windowsservercore base image and if they switched the default `SHELL`. What does `docker inspect microsoft/windowsservercore` show as default shell?

**Comment by KiraResari** [comment]
''docker inspect microsoft/windowsservercore'' shows this for me:

```
PS C:\Users\Administrator> docker inspect microsoft/windowsservercore
[
    {
        "Id": "sha256:0534c30e0e3ec86f6850d3aba7f23a859a9a4ffe4a64b30a347cd4e417c89dce",
        "RepoTags": [
            "microsoft/windowsservercore:latest"
        ],
        "RepoDigests": [
            "microsoft/windowsservercore@sha256:c60a7376f5147e40b65c51fce34ac17710742f97e91b5c3a71e1667e671112f1"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2018-09-11T11:19:41.0702115-07:00",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": [
                "c:\\windows\\system32\\cmd.exe"
            ],
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "Architecture": "amd64",
        "Os": "windows",
        "OsVersion": "10.0.14393.2485",
        "Size": 10882499524,
        "VirtualSize": 10882499524,
        "GraphDriver": {
            "Data": {
                "dir": "C:\\ProgramData\\Docker\\windowsfilter\\e36d74d2729d2f0c588849cdb906a584b40a32c61fbebbb4d2fddab143565dbc"
            },
            "Name": "windowsfilter"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:f358be10862ccbc329638b9e10b3d497dd7cd28b0e8c7931b4a545c88d7f7cd6",
                "sha256:7332b29f30e08a549df2a265c1cc679fd87254183cc7dcd7c07d318b62b1a10a"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
```

I'm not sure where I would be able to find information about the default ''SHELL'' in that output though...

**Comment by thaJeztah** [comment]
Right, so it looks like the image does not have a specific `SHELL` set. If it would be set, it would be shown in the `Config` section, something like;

```json
{
  "Config": {
      "Hostname": "",
      "Domainname": "",
      "User": "",
      "AttachStdin": false,
      "AttachStdout": false,
      "AttachStderr": false,
      "Tty": false,
      "OpenStdin": false,
      "StdinOnce": false,
      "Env": null,
      "Cmd": [
          "c:\\windows\\system32\\cmd.exe"
      ],
      "Image": "",
      "Volumes": null,
      "WorkingDir": "",
      "Entrypoint": null,
      "OnBuild": null,
      "Labels": null,
      "Shell": [
          "powershell",
          "-command"
      ]
  }
}
```

If you still have a machine where this _does_ work, perhaps you can inspect the image there as well and check if there is a custom shell set in that version of the image. If there is, then it means the image authors of the microsoft/windowsservercore image made a (backward incompatible) change to the image.

While that's definitely not desirable, it's generally recommended to pin to a specific tag/version of an image, instead of `:latest` (which is the default if you don't specify a tag). The "latest" tag is a "rolling" tag, which means that currently it may be a Windows server 2016 image, but in future a Windows 1903 (e.g.) image.
