### ISSUE TITLE
Win32 call "GetFinalPathNameByHandle" Fails for windows mounts

### ISSUE THREAD

**Issue by aybassiouny** [docker/for-win#2800]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A97F5092-33E3-4881-B922-20699A0CAFE7/20181028220219

### Expected behavior
`GetFinalPathNameByHandle` should succeed for mounted folders/drives and return path length. Path returned is expected to be something similar to `\\?\ContainerMappedDirectories\...`. 

### Actual behavior
Call fails with 0 return and GetLastError retrieves `ERROR_PATH_NOT_FOUND`. 

### Information
I think this has been a problem for sometime. Searching "docker GetFinalPathNameByHandle" yields 2-3 results, seems people just avoid using the call to mitigate. (e.g. [this](https://github.com/Microsoft/TypeScript/issues/13060) and [this](https://bugs.openjdk.java.net/browse/JDK-8172711)).  

  - Windows Version: repros on RS4 & RS5 
  - Docker for Windows Version: 2.0.0.0-beta1-win75 (19925) - Edge channel 

### Steps to reproduce the behavior
  1. `Docker run -v C:/temp:C:/temp -it microsoft/windowsservercore:latest`
  2. grab [realpath.exe](https://github.com/StefanScherer/dockerfiles-windows/tree/master/realpath) & run `realpath c:\temp` inside container

**Comment by aybassiouny** [comment]
Did anyone manage to look into this? I am beginning to think it's a bug with Microsoft/hcsshim instead, but it's hard to judge for sure. 

Please let me know if more info is needed.

**Comment by aybassiouny** [comment]
Ping @thaJeztah

**Comment by StefanScherer** [comment]
Windows mounts have been improved with 1803 base images. I haven‘t tried the realpath.exe with it, but the mapped directory is no longer a symlink so it should return the real path. Node.js works fine in 1703 and the upcoming 2019/1809 images.
