### ISSUE TITLE
Firewall exception when trying to share C drive

### ISSUE THREAD

**Issue by StefanTBG** [docker/for-win#282]
### Expected behavior
Attempting to share C drive.

### Actual behavior
Fails with firewall exception.

### Information

  - Diagnostic ID: 236A65AD-0948-4231-8C5B-A092636C5540/2016-12-03_03-24-05
  - Windows 10 build 14971
  - Beta release of Docker
  - I can see a firewall exception called DockerProxy already configured for port 445
  - No 3rd part ant-virus software, just Windows Defender

**Comment by dgageot** [comment]
@simonferquel Can you take a look at the diagnostics, please?

**Comment by dgageot** [comment]
@StefanTBG Could you give a try to Docker for Windows Beta31 and tell us if you see a different behaviour?

**Comment by StefanTBG** [comment]
@dgageot I uninstalled and then grabbed the latest beta version and can see that the version is 1.13.0-rc2-beta31. I'm still seeing the same behavior.

Here's the new diagnostic ID: 236A65AD-0948-4231-8C5B-A092636C5540/2016-12-05_01-08-07.

**Comment by vvsh** [comment]
@StefanTBG, I have had the same issue before 1.13.0-rc2-beta31 (9123), but on beta31 everything works.

**Comment by simonferquel** [comment]
@StefanTBG Are you sure you don't have a 3rd party firewall installed ?
Also, I see that you have VMWare services running. That can introduce some nasty bugs with Hyper-V.

**Comment by StefanTBG** [comment]
Closing this out. After updating today, this issue has been resolved. Current version: 1.13.0-rc3-beta32.1 (9324). Thanks for the help @simonferquel and @dgageot.
