### ISSUE TITLE
Docker windows container crashes with "the connection with the virtual machine hosting the container was closed"

### ISSUE THREAD

**Issue by derekwbrown** [docker/for-win#2821]
- [ X ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BBEDC552-AB31-421B-A01E-3DDFBCD8C965/20181029182212

### Expected behavior
The container should run
### Actual behavior

Attempting to run a command within the container fails with

`ERRO[0086] Error waiting for container: failed to shutdown container: container 74591bb47c378324a363e6e95cca348fd029851560dc38e0253ab3a137d67c1d encountered an error during Shutdown: failure in a Windows system call: The connection with the Virtual Machine hosting the container was closed. (0xc037010a)`

### Information

  - Windows Version: Windows 10 pro 1803 17134.345
  - Docker for Windows Version:
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:34 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.24)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:36:40 2018
  OS/Arch:          windows/amd64
  Experimental:     false

### Steps to reproduce the behavior
Create docker container with windowsservercore:1803, git & go.
Start container
Attempt to `go get` a project; in my case
`go get -d -u golang.org/x/lint/golint`

Container immediately crashes with 
`ERRO[0086] Error waiting for container: failed to shutdown container: container 74591bb47c378324a363e6e95cca348fd029851560dc38e0253ab3a137d67c1d encountered an error during Shutdown: failure in a Windows system call: The connection with the Virtual Machine hosting the container was closed. (0xc037010a)`

Note, I do *not* have a volume mounted
.

Container can be (re)created using docker file and associated files from
https://github.com/derekwbrown/testrepo/dockercrash

**Comment by derekwbrown** [comment]
I have tried resetting docker, and doing a full uninstall/reinstall. 
I've also tried disabling the local firewall, as I found some anecdotal evidence that this could be related to internal networking.  Still no luck

**Comment by derekwbrown** [comment]
Any update to this?

**Comment by billybooth** [comment]
I'm getting the same crash `(0xc037010a)` when I do a git clone of a private repository using the wincred helper against `git version 2.19.1.windows.1` from Scoop.  It's been baffling me for a couple of days and doesn't occur when I clone public repositories without invoking the helper, and it also does not occur when passing an access token via the URL...  I don't have much/any additional diagnostic info to provide, but I also _do not_ have a volume mounted, and I can provide more information if needed.

**Comment by derekwbrown** [comment]
Any update to this? Continues to happen with latest docker update:
docker version
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:51 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:56:41 2018
  OS/Arch:          windows/amd64
  Experimental:     false

**Comment by avoli** [comment]
Same Problem:
Operating System: Windows 10 Enterprise Version 1803 (OS Build 17134.471)
Docker Engine: 18.09.0

No Volumes mounted.

I try to run a jenkins agent inside a microsoft/dotnet-framework:4.7.2-sdk image. As soon as the agent gets a job to run, the container crashes.
Same is with a gitlab-runner in the same image.

**Comment by jakobehn** [comment]
I'm seeing this to, running a build agent inside a Windows container and get this error seemingly at random.

[0020] Error waiting for container: failed to shutdown container: container 3d30cf1a0da1a91dc26ce7ac8688a08ae6f3ccce66595f4af70a120c5359d750 encountered an error during Shutdown: failure in a Windows system call: The connection with the Virtual Machine hosting the container was closed. (0xc037010a)


Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:51 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:56:41 2018
  OS/Arch:          windows/amd64
  Experimental:     false

**Comment by hbuckle** [comment]
I get the same error when running the `pacman` command from msys2

```
RUN ridk exec pacman -S mingw-w64-x86_64-sqlite3 --noconfirm
```

It only occurs with hyper-v isolation, building the image from a Windows Server 1803 machine works.
The issue does not occur when using the servercore:1809 image, even with hyper-v isolation

**Comment by MagicShoebox** [comment]
Same problem
```
Win 10 Version 1803 (OS Build 17134.523)

Client: Docker Engine - Community
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:34:26 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:50:10 2019
  OS/Arch:          windows/amd64
  Experimental:     true
```

Image based off microsoft/dotnet-framework:4.7.2-sdk (which is based off servercore:1803).
The culprit appears to be a `git clone` via SSH (HTTPS works fine).

**Comment by MagicShoebox** [comment]
I was able to get Git working through some combination of updating Docker to 18.09.2 and switching to MinGit.

**Comment by chris1248** [comment]
happening for me too when I run a git command from my dockerFile:
```
FROM microsoft/windowsservercore:1803 AS basis_one
....
RUN git clone ssh://git@name.git "some\folder\somewhere"
```

**Comment by NeoParadox** [comment]
Same issue here. Everything works fine as long as the credential helper is not being used, e.g. passing the git credentials via the URL without storing them. Once I run `git config --global credential.helper store` and try to clone again using the same command the container crashes with error (0xc037010a).

**Comment by PedroWitzel** [comment]
I have same issue when I tried to clone using SSH. But there's no problem when cloning through HTTP.
But I cannot do a `git log`, it crashes the same way.
As does `git config --list`. I've put a `.gitconfig` on my `HOME` folder, nothing changed.
If I try to launch `bash.exe` in the git install folder, it also crashes.

`status`, `add` and `commit` seems to work just fine.

I'm using servercore:**1803** and git **2.22.0** installed through chocolatey.

> Client: Docker Engine - Community
>  Version:           19.03.1
>  API version:       1.40
>  Go version:        go1.12.5
>  Git commit:        74b1e89
>  Built:             Thu Jul 25 21:17:08 2019
>  OS/Arch:           windows/amd64
>  Experimental:      false
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          19.03.1
>   API version:      1.40 (minimum version 1.24)
>   Go version:       go1.12.5
>   Git commit:       74b1e89
>   Built:            Thu Jul 25 21:25:07 2019
>   OS/Arch:          windows/amd64
>   Experimental:     false

**Comment by ThibzR** [comment]
/remove-lifecycle stale

@PedroWitzel I am experiencing similar issue as you (with HTTP tho, can't do ssh), also using 1803 and git install through chocolatey (also tried git-for-windows install, mingit...). Some git commands such as git log and others are indeed crashing the container. I also found out that non LFS repository are crashing less. A LFS repository is crashing the container (with latest `git-lfs`) upon cloning. Unfortunately I can't try using 1809 as it needs to match windows host version.

> Client: Docker Engine - Community
>  Version:           18.09.2
>  API version:       1.39
>  Go version:        go1.10.8
>  Git commit:        6247962
>  Built:             Sun Feb 10 04:12:31 2019
>  OS/Arch:           windows/amd64
>  Experimental:      false

**Comment by NeoParadox** [comment]
@PedroWitzel @ThibzR  I tried to track under which conditions the crash happens and it seems that the container always ends up crashing when git.exe has to call one of the executables in the %GitInstallationDir%/usr/bin folder. The workaround that worked for me was not installing git in a RUN-instruction, but instead installing it during the container startup in a CMD-instruction.

**Comment by PedroWitzel** [comment]
@NeoParadox wouldn't that mean that it would install git every `run` giving a enormous headway ? I'm still getting to know docker, but could you make a new image with that `run` result ?

I've tried using [MinGit](https://github.com/StefanScherer/dockerfiles-windows/blob/master/git-for-windows-issue/Dockerfile), but had similar results. But I at least could do `git log` on my http-cloned repos.

**Comment by ThibzR** [comment]
@NeoParadox Damn, it actually worked, even LFS repo🙏  Thanks!
@PedroWitzel indeed this giving a headway, but better than nothing I guess..

**Comment by NeoParadox** [comment]
@PedroWitzel There can only be only one `CMD`, usually one of the last instructions in the dockerfile, that is only executed once you actually (re-)start your container. The installation itself is quick, your headway is entirely dependent on how many git operations and other operations that depend on them you have to execute.

**Comment by Roemer** [comment]
Just had the very same issue. I changed to 1809 and 1903 as base image and there the issue did not happen.

**Comment by nsoderberg** [comment]
Had the same issue, frequent crashes with the mentioned error message, especially when building the image. After upgrading to windowsservercore 2019 as the base image I haven't seen the problem.

**Comment by atomaras** [comment]
I have the same issue. Upgrading to servercore-ltsc2019 solved the problem for me. well that was weird :)
