### ISSUE TITLE
Docker Crashes On Startup (Windows 10 x64)

### ISSUE THREAD

**Issue by garygsscott** [docker/for-win#2824]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 196A41C1-7392-4CFD-9C75-6F9ECE06ACEF/20181030083108

### Information

  - Windows Version: 10 (1083)
  - Docker for Windows Version: 2.0.0.0-beta1-win75 (19925)

### Steps to reproduce the behavior

  1. Install Docker For Windows
  2. Reboot while using Windows 10 (1083) and wait for Docker service to startup.   Crashes instead of starting up.

**Comment by garygsscott** [comment]
Please advise if more information is needed to reproduce on your side.

**Comment by Runda-Scath-na** [comment]
Seeing the crash every time on startup.  I attached the error log that appears each time

[DockerBootupCrashOnWindows10Startup.log](https://github.com/docker/for-win/files/3467488/DockerBootupCrashOnWindows10Startup.log)

I am running Docker behind an enterprise proxy, but not sure if that is the cause or if the error log is jsut mentioning the proxy configs.  I am lost on what the error actually means.

Diagnostic id: 38E9B873-20DA-4578-81B5-9D8B9076C8CF/20190805115500
