### ISSUE TITLE
An error occurred while attempting to build Docker image

### ISSUE THREAD

**Issue by pathi84** [docker/for-win#2825]
I'm running Docker for Windows,

**Expected behavior**
While in Windows Container mode, I should be able to build images for Windows containers.

**Actual behavior**
An error occurred while attempting to build Docker image.	

C:\Users\xxxxx\.nuget\packages\microsoft.visualstudio.azure.containers.tools.targets\1.1.1\build\Container.targets 255

find the attached target file
[1.1.1.zip](https://github.com/docker/for-win/files/2529381/1.1.1.zip)

Diagnostics ID: 0FF52429-B476-4DA8-854E-BEEB64672ABA/2018103016421

**Comment by killnine** [comment]
+1 having the same issue.

I am using VS 15.8 and also tried with VS 15.9 preview

I am running DFW 18.06.1-ce-win73 (19507) (b0f14f1)

**Comment by haplios** [comment]
+1 Same issue here, VS 15.8.9, fresh install of Docker for Windows.

**Comment by sursamra** [comment]
+1 Same issue VS 2017

**Comment by gradforddavid** [comment]
+1 The same issue to me VS2017

**Comment by ojorma** [comment]
same here. has anyone been able to resolve this

**Comment by Sylwekqaz** [comment]
Same here. 
I captured HTTP calls with fiddler. It's looks like there is problem with proxy settings. 
Calls
Request:

    CONNECT aka.ms:443 HTTP/1.1
    Host: aka.ms
    Proxy-Connection: Keep-Alive

Response:

    HTTP/1.1 407 Proxy Authentication Required 

Request:

    CONNECT download.docker.com:443 HTTP/1.1
    Host: download.docker.com
    Proxy-Connection: Keep-Alive

Response: 

    HTTP/1.1 407 Proxy Authentication Required 

I have proxy setting set in system setting. Other programs correctly detect proxy settings, and i don't have any problems with internet.

**Comment by EminjanO** [comment]
???

**Comment by RLashofRegas** [comment]
Same issue, also happening for Linux containers. Restarting Docker and VS did not resolve it. I know my docker installation is working to some extent because I can build and run this sample: https://github.com/dotnet/dotnet-docker-samples/tree/master/aspnetapp using the CLI. When I try to open the csproj in visual studio and click Add->Docker Support->Keep Existing Dockerfile and then F5 I am getting the error listed above

**Comment by julielerman** [comment]
I ran into this problem today (trying to debug Docker in VS2017) and discovered (in my case) that I had to log into my docker account using the command line "docker login", even though I was already logged in via the docker desktop app. Hope this helps someone else!

**Comment by NullReferenceError** [comment]
I would echo @julielerman with that solution, and also that the Docker ID is not your Email address.  

There's another open issue over in docker hub-feedback that discusses the User ID vs Email situation.  Docker for windows will let you authenticate using email, but "docker login" will not work from the command line. https://github.com/docker/hub-feedback/issues/935

After updating my User Id and Password, then running "Docker Login" everything works fine.
