### ISSUE TITLE
failed to get default registry endpoint from daemon

### ISSUE THREAD

**Issue by girishgalla** [docker/for-win#2830]
I have tried with the latest version of my channel (Stable )
I have uploaded Diagnostics
  - Diagnostics ID: BC64E8E1-56A8-4146-A00F-764C6424912E/20181031171334

  - Windows Version: windows:  10.0.17134.345 professional 
  - Docker for Windows Version: 18.06.1-ce

When i tried to pull sample image "hello-world" the following error is coming
**command:** "hello-world"
**error:**
Warning: failed to get default registry endpoint from daemon (error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.38/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.). Using system default: https://index.docker.io/v1/
error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.38/images/create?fromImage=hello-world&tag=latest: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

**command:** docker info
**error:** 
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.38/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

**command** : docker version
**error:**
Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:34 2018
 OS/Arch:           windows/amd64
 Experimental:      false
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.38/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

**Comment by lwks** [comment]
I have a similar problem..
As soon as I start docker I'm getting the same error as you.
Windows version is 18.03 Enterprise and the last docker.

**Comment by drodbez** [comment]
I think it's a permissions issue, fixed this error on Ubuntu 18.04 using 'sudo' before 'docker'. Hope this helps.
Example
sudo docker pull repoNamehere

**Comment by snpdev** [comment]
See https://github.com/docker/for-win/issues/2671#issuecomment-430816883

**Comment by Hemaprasanthi** [comment]
I opened the docker terminal and waited till I get the picture. Then I tried the command again in my console it worked
