### ISSUE TITLE
Retry loop when pulling a container image

### ISSUE THREAD

**Issue by HarshaSuranjith** [docker/for-win#2838]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 95A7128E-132D-401B-BC00-F9096E60B80D/20181101195856

### Expected behavior
Run *hello world* docker  container

### Actual behavior
It identifies the container image and starts pulling the image. But abruptly terminates and retries the download and terminates again. This behavior is repeated in a loop.

Similar behaviour is observed when attempting to run other containers as well.

### Information
``` 
PS C:\Users\harshaa> docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
e46172273a4e: Retrying in 2 seconds
1f7d468f830c: Retrying in 2 seconds
35655e48c5c5: Download complete
8159aad5f944: Download complete 

```

  - Windows Version:  10.0.17134 Build 17134
  - Docker for Windows Version: 18.06.1-ce-win73 (19507)

### Steps to reproduce the behavior
~~NA~~

**Comment by HarshaSuranjith** [comment]
@docker-for-desktop-robot 
update ???

**Comment by mat007** [comment]
This does not look like an issue with the Docker for Windows application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place.
