### ISSUE TITLE
kubernetes can not started.

### ISSUE THREAD

**Issue by jeffery9** [docker/for-win#2839]
- When  enable kubernetes, create config file in wrong folder. [ edge channel]

> [00:23:49.125][DnsUpdater     ][Info   ] Network configuration change detected
> [00:23:49.125][PowerShell     ][Info   ] Run script '$(Find-NetRoute -RemoteIPAddress 8.8.8.8).InterfaceIndex[0]'...
> [00:23:49.679][ApiProxy       ][Info   ] Init returned
> [00:23:49.679][ApiProxy       ][Info   ] time="2018-11-02T00:23:49+08:00" msg="Cluster config received"
> [00:23:49.681][ApiProxy       ][Warning] time="2018-11-02T00:23:49+08:00" msg="Error while setting up kubernetes: cannot update the host kube config: open C:\\Users\\w541.kube\\config.lock: Access is denied.. Retrying in 1s"
> [00:23:50.471][VpnKit         ][Error  ] vpnkit.exe: Socket.UDPv4.read: udp -> 8.8.8.8:53 caught Lwt.Resolution_loop.Canceled returning Eof
> 
> [00:23:50.495][VpnKit         ][Error  ] vpnkit.exe: Socket.UDPv4.read: udp -> 8.8.8.8:53 caught Lwt.Resolution_loop.Canceled returning Eof
> 
> [00:23:51.179][ApiProxy       ][Info   ] Init returned
> [00:23:51.179][ApiProxy       ][Info   ] time="2018-11-02T00:23:51+08:00" msg="Cluster config received"
> [00:23:51.181][ApiProxy       ][Warning] time="2018-11-02T00:23:51+08:00" msg="Error while setting up kubernetes: cannot update the host kube config: open C:\\Users\\w541.kube\\config.lock: Access is denied.. Retrying in 1s"
> [00:23:51.814][VpnKit         ][Error  ] vpnkit.exe: Socket.UDPv4.read: udp -> 8.8.4.4:53 caught Lwt.Resolution_loop.Canceled returning Eof
> 
> [00:23:52.476][DnsUpdater     ][Info   ] Network configuration change detected
> [00:23:52.476][PowerShell     ][Info   ] Run script '$(Find-NetRoute -RemoteIPAddress 8.8.8.8).InterfaceIndex[0]'...
> [00:23:52.494][ApiProxy       ][Info   ] Init returned
> 

- always report `
vpnkit.exe: Hvsock.read: An established connection was aborted by the software in your host machine.
`   and  `msg="Cannot list nodes: Get https://localhost:6445/api/v1/nodes: EOF"`

> 
> [00:32:08.080][DnsUpdater     ][Info   ] Network configuration change detected
> [00:32:08.081][PowerShell     ][Info   ] Run script '$(Find-NetRoute -RemoteIPAddress 8.8.8.8).InterfaceIndex[0]'...
> [00:32:08.104][VpnKit         ][Error  ] vpnkit.exe: Hvsock.read: An established connection was aborted by the software in your host machine.
> 
> 
> [00:32:08.105][ApiProxy       ][Info   ] time="2018-11-02T00:32:08+08:00" msg="Cannot list nodes: Get https://localhost:6445/api/v1/nodes: EOF"
> [00:32:09.106][VpnKit         ][Error  ] vpnkit.exe: Hvsock.read: An established connection was aborted by the software in your host machine.
> 
> 
> [00:32:09.107][ApiProxy       ][Info   ] time="2018-11-02T00:32:09+08:00" msg="Cannot list nodes: Get https://localhost:6445/api/v1/nodes: EOF"
> [00:32:10.113][VpnKit         ][Error  ] vpnkit.exe: Hvsock.read: An established connection was aborted by the software in your host machine.
> 
> 
> [00:32:10.117][ApiProxy       ][Info   ] time="2018-11-02T00:32:10+08:00" msg="Cannot list nodes: Get https://localhost:6445/api/v1/nodes: EOF"
> [00:32:11.105][VpnKit         ][Error  ] vpnkit.exe: Hvsock.read: An established connection was aborted by the software in your host machine.
> 
> 
> [00:32:11.106][ApiProxy       ][Info   ] time="2018-11-02T00:32:11+08:00" msg="Cannot list nodes: Get https://localhost:6445/api/v1/nodes: EOF"

  - [ x ] I have tried with the latest version of my channel ( Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

C:\Users\w541>docker version
Client: Docker Engine - Community
 Version:           18.09.0-ce-beta1
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        78a6bdb
 Built:             Thu Sep  6 22:42:13 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0-ce-beta1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       78a6bdb
  Built:            Thu Sep  6 22:49:35 2018
  OS/Arch:          linux/amd64
  Experimental:     false
 Kubernetes:
  Version:          Unknown
  StackAPI:         Unknown

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. install the latest docker for windows 
  2. enable kubernets

**Comment by chamhaw** [comment]
+1

**Comment by mindriven** [comment]
+1
