### ISSUE TITLE
unable to start container on Win 10 LTSB 1607

### ISSUE THREAD

**Issue by mwallner** [docker/for-win#2842]
### Expected behavior
it should be possible to run containers

### Actual behavior
docker run freezes - no action possible

### Information
Docker 18.06.1 - ce
Windows 1607 LTSB 14393.0
![image](https://user-images.githubusercontent.com/5354972/47917084-acd03b80-dea8-11e8-9894-08cd7afa7a77.png)

virus scanner disabled/uninstalled, checked that hyper-v is enabled and working, rebooted the host several times.

### Steps to reproduce the behavior
* Install Docker
* `docker run hello-world`

**Comment by mwallner** [comment]
ping  @stefanscherer :-)

**Comment by mwallner** [comment]
Well..
According to https://docs.microsoft.com/en-us/virtualization/windowscontainers/about/index - you need Win 10 1606 - Build 14393.222 or later - I'm on 14393.0 

:-(

**Comment by mwallner** [comment]
I think I'll try to get along with Docker Toolbox - any objections?

**Comment by StefanScherer** [comment]
Yes, Toolbox is only for Linux containers.

**Comment by mwallner** [comment]
closing this issue: Windows Build 14393.222 or later is required to run "Docker For Windows"
thanks for the support!

**Comment by mwallner** [comment]
for details on Windows 10 updates - see https://www.microsoft.com/en-us/itpro/windows-10/release-information
