### ISSUE TITLE
High CPU - no container is running

### ISSUE THREAD

**Issue by grongron** [docker/for-win#2854]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 5232FBE1-3F49-4855-8E85-30DFC6CF4564/20181106152429

### Expected behavior
low cpu when no container is runnig
### Actual behavior
In Task manager: 30-30% CPU due to docker
    Docker for windows Service: 18% CPU
    WMI Provider Host: 14% CPU

   "Quite Docker" and the CPU is back to 2-3%

### Information

  - Windows Version: OS Name	Microsoft Windows 10 Enterprise, Version	10.0.17134 Build 17134
  - Docker for Windows Version: 18.06.1-ce, build e68fc7a

### Steps to reproduce the behavior

  1. Enable Hyper-V
  2. Install docker for windows
  3. Start docker

**Comment by qrzbrz** [comment]
WMI Provider logs the problem to EventViewer. After you start Docker Desktop open EventViewer (Windows+R, eventvwr), then in View Menu show Debug Protocols, then go to Microsoft->Windows->WMI Host. There you can find a lot of 5858 Events that show that Queryies are not closed properly by Docker.

**Comment by TheBlusky** [comment]
Were you able to do anything about it ?

**Comment by qrzbrz** [comment]
No, sorry I am not a docker-developer, only a user. My solution was to install an Ubuntu partition for using docker. Anyway, Windows 10 will soon get a linux kernel.

**Comment by nicolas-tg-ch** [comment]
I have the same problem on Windows 10 Enterprise, Version 1803
Docker Version 2.0.0.3 (31259), Build 8858db3.
Is there anything one can do to fix the cpu load issue?
see also https://github.com/docker/for-win/issues/809

**Comment by vlad-saling** [comment]
Have the same issue. VMI Provider Host keeps consuming CPU even if Docker Desktop is turned off. So once I stop working with Docker I use a temporary workaround described @ https://www.drivereasy.com/knowledge/wmi-provider-host-high-cpu-usage-on-windows-10-solved/#3 . Do fix for CPU consumption during work though :/

**Comment by nicolas-tg-ch** [comment]
the fix for the cpu consumption is described in #809 (disable dummy network adapters via settings -> network -> status -> change adapter options)

**Comment by vlad-saling** [comment]
@nicolas-tg-ch I've tried that before, no change. I only have 2 Hyper-V adapters there. I tried to disable only one or both of them, yet VMI Provider host consumed about the same amount of CPU regardless.
