### ISSUE TITLE
Switch to Windows container fails - Continuation of issue#90

### ISSUE THREAD

**Issue by dheater** [docker/for-win#287]
### Note
This seems to be a continuation of issue #90 which has been closed and I do not have the ability to reopen.

### Expected behavior

Switch to Windows containers ... succeeds

### Actual behavior

Switch to Windows containers ... fails

### Information

Previous beta version of Docker for Windows was working (1.12.3 beta 29.3)
I updated to Version 1.13.0-rc2-beta31

DisableVSmbOplock was set to 1. I've changed it to 0 and confirmed that I no longer get an error message from the debug script (see below).

Crash report: 400BFA24-1C02-4015-98FA-CF9C153CE0A1/2016-12-01_23-13-55

Tried the NAT steps from [this comment](https://github.com/docker/for-win/issues/90#issuecomment-254678067)

PS C:\WINDOWS\system32> Get-ContainerNetwork | Remove-ContainerNetwork -force
PS C:\WINDOWS\system32> Get-NetNat | Remove-NetNat
PS C:\WINDOWS\system32> New-ContainerNetwork -Name nat -Mode NAT –subnetprefix 10.0.76.0/24

Name Id Subnets Mode SourceMac DNSServers DNSSuffix

nat 842ba9dc-5b48-4c8b-9b83-99a0da75c7af {10.0.76.0/24} NAT

PS C:\WINDOWS\system32> Remove-NetNAT

Confirm
Are you sure you want to perform this action?
Performing operation Delete on Target H842ba9dc-5b48-4c8b-9b83-99a0da75c7af PolicyStore Local
[Y] Yes [A] Yes to All [N] No [L] No to All [S] Suspend [?] Help (default is "Y"):
PS C:\WINDOWS\system32> New-NetNat -Name DockerNAT -InternalIPInterfaceAddressPrefix 10.0.0.0/17

Name : DockerNAT
ExternalIPInterfaceAddressPrefix :
InternalIPInterfaceAddressPrefix : 10.0.0.0/17
IcmpQueryTimeout : 30
TcpEstablishedConnectionTimeout : 1800
TcpTransientConnectionTimeout : 120
TcpFilteringBehavior : AddressDependentFiltering
UdpFilteringBehavior : AddressDependentFiltering
UdpIdleSessionTimeout : 120
UdpInboundRefresh : False
Store : Local
Active : True

PS C:\WINDOWS\system32> docker run -it -v c:\data:c:\data microsoft/nanoserver powershell
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: open \.\pipe\docker_engine_windows: The system cannot find the file specified..
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
PS C:\WINDOWS\system32> wget https://github.com/Microsoft/Virtualization-Documentation/raw/master/windows-server-container-tools/Debug-ContainerHost/Debug-ContainerHost.ps1 -UseBasicParsing |
iex
Checking for common problems
Describing Windows Version and Prerequisites
[+] Is Windows 10 Anniversary Update or Windows Server 2016 149ms
[+] Has KB3192366, KB3194496, or later installed if running Windows build 14393 39ms
[+] Is not a build with blocking issues 34ms
Describing Docker is installed
[+] A Docker service is installed - 'Docker' or 'com.Docker.Service' 46ms
[+] Service is running 21ms
[+] Docker.exe is in path 2.06s
Describing User has permissions to use Docker daemon
[+] docker.exe should not return access denied 37ms
Describing Windows container settings are correct
[-] Do not have DisableVSmbOplock set to 1 44ms
Expected: {0}
But was: {1}
72: $regvalue.VSmbDisableOplocks | Should Be 0
at , : line 72
[+] Do not have zz values set 51ms
Describing The right container base images are installed
Error response from daemon: open \.\pipe\docker_engine_windows: The system cannot find the file specified.
[-] At least one of 'microsoft/windowsservercore' or 'microsoft/nanoserver' should be installed 106ms
ValidationMetadataException: The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
ParameterBindingValidationException: Cannot validate argument on parameter 'Property'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command
again.
at , : line 96
Describing Container network is created
[-] Error occurred in Describe block 1.03s
RuntimeException: Cannot index into a null array.
at , : line 125
Showing output from: docker info

Showing output from: docker version
Client:
Version: 1.13.0-rc2
API version: 1.25
Go version: go1.7.3
Git commit: 1f9b3ef
Built: Wed Nov 23 17:40:58 2016
OS/Arch: windows/amd64

Showing output from: docker network ls

Warnings & errors from the last 24 hours
Logs saved to C:\WINDOWS\system32\logs_20161201-230139.csv

**Comment by dgageot** [comment]
I see this error in the logs:
```
[22:57:25.407][WindowsDockerDaemon][Info   ] time="2016-12-01T22:57:25.398096600-06:00" level=info msg="Windows default isolation mode: hyperv" 
[22:57:25.409][WindowsDockerDaemon][Info   ] time="2016-12-01T22:57:25.409094400-06:00" level=info msg="[graphdriver] using prior storage driver: windowsfilter" 
[22:57:25.432][WindowsDockerDaemon][Info   ] Error starting daemon: layer does not exist
[22:57:25.440][WindowsDockerDaemon][Error  ] Process died
```

@friism have you seen that already?

**Comment by dheater** [comment]
After several uninstall/reinstalls, deleting the c:\ProgramData\Docker folder, and uninstalling and reinstalling the HyperV feature, its working now. So many changes over the past few hours. Sorry I can't say what exactly got it working again.
