### ISSUE TITLE
unpause of paused container fails to connect ports on unpause after windows restart 

### ISSUE THREAD

**Issue by peterkennard** [docker/for-win#2876]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
after windows restarts (reboots) and docker is running,  unpausing a container will resume it where it left off and it's internal ports will remain exposed to localhost as they were when it was paused.

### Actual behavior
after windows reboots and docker is running a container is unpaused and attempting to connect to its ports forwarded to localhost fails.  It requires stopping the container and removing it, and after rebooting windows, re-creating and running the container to reconnect to it's ports.  Apparently windows keeps the ports "in use".

### Information

  - Windows Version:  Windows 10 pro kept updated.
  - Docker for Windows Version: 18.06.1-ce, build e68fc7a

### Steps to reproduce the behavior

1. create and start a container exposing a port to localhost (in my primary case port 5900 for VNC)
2. connect to the container with VNC viewer. (success)
3. disconnect VNC viewer from container.
4. pause the container.
5. restart windows.
6. wait for docker to be running.
7. unpause the container.
8.  connect VNC viewer to container. ( connection fails ).

Note if 5 on continues without reboot:
5. unpause container
8. connect vnc viewer to container
9. connection succeeds and resumes container where it left off.

This also happens with web servers and ssh as well.  Apparently with any port forwarded to localhost on the windows host machine.

**Comment by stojan-jovic** [comment]
Same problem here with `18.03.0-ce-win59 (16762)` and Windows 10 Enterprise (updated). This issue should not be closed.
