### ISSUE TITLE
Docker not switching to linux containers on Windows 10 - 

### ISSUE THREAD

**Issue by MelleKoning** [docker/for-win#2878]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 8F136BD9-B3DA-4535-8E91-4D0C2D048DCC/20181112105628

### Expected behavior
Clicking on 'switch to linux containers' to work

### Actual behavior
A windows dialog showing the following error

Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The object already exists.

   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.<>c__DisplayClass25_0.<SwitchDaemon>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 275
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

### Information

  - Windows Version: 10
  - Docker for Windows Version: Version 18.06.1-ce-win73 (19507)

### Steps to reproduce the behavior

  1. install docker for windows. (to use windows containers)
  2. click 'switch to linux containers'
or
1. install docker for windows (to use linux containers)
2. docker won't start and gives the same error, tray-icon remains red.

**Comment by MelleKoning** [comment]
More Diagnostics uploaded with AE1C563B-57A4-4210-9087-D11B659DDCF6/20181112120303

**Comment by MelleKoning** [comment]
After removing windows 10 HyperV and Container features and removing docker (uninstall) it turns out there was a lingering Docker network adapter still there. 

Removed / disabled the docker network adapter in windows device manager.

Re install of windows HyperV and container features
Re install of docker windows setup
Had to also execute (re-install) manually the c:\program files\docker\docker\resources\MobyLinux.ps1 to have the MobyLinuxVM back up and running

After all of that, and several reboots, docker is running fine again.

My findings:
- Uninstall and re-install of docker does not check the failing network adapters and does not re-install the MobyLinuxVM if that is missing from Hyper-V manager.

Hope that somebody else finds this usefull. Good luck.

**Comment by Pxtl** [comment]
I'm facing similar problem - however I look in my network adapters on Device Manager and I don't see any reference to Docker.  A Hyper-V Virtual Ethernet Adapter, but no Docker one.

**Comment by MelleKoning** [comment]
Yes, the hyperV virtual adapter is the one. Try to disable it and then
reinstall will recreate that virtual network adapter, worked for me.

Op wo 14 nov. 2018 21:08 schreef Martin Zarate <notifications@github.com:
