### ISSUE TITLE
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.38/version: open //./pipe/docker_engine: The system cannot find the file specified.

### ISSUE THREAD

**Issue by BorisBokmans** [docker/for-win#2883]
When I'm trying to install the azure runtime I receive an error saying:
'error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.38/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration in Windows, the docker client must be run elevated to connect. This may also indicate that the docker daemon is not running.

I can reproduce this error (during connect) by running 'docker version' in PS.

OS: WIN 10 Enterprise 2017 LTSB

Docker:
Version: 18.06.1-ce
api version: 1.38
OS/arch: win/amd64

I tried to run PS elevated. Tried to re-install Docker. Tried to reboot.

Nothing works for me yet...

Can anyone help please?

**Comment by BorisBokmans** [comment]
Does this have anything to do with Docker not being defined in the system path?

**Comment by dsuurlant** [comment]
Having the same issue. Tried installing the Edge version, but that didn't work. If I try to run Docker for Windows as administrator, I get the Hyper-V error, which I can only fix by restarting Docker -- which takes it out of elevated mode. Chicken and egg. I eventually uninstalled it and went with Docker Toolbox instead.
