### ISSUE TITLE
Cannot resolve container hostname/alias from HOST (1806)

### ISSUE THREAD

**Issue by simplyQQ** [docker/for-win#2885]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 801BD8E3-DC22-4B61-845E-1C10B055C252/20181113175502

### Expected behavior
docker pull microsoft/nanoserver
docker run -h testname -dit microsoft/nanoserver powershell
ping testname

name should be resolved and pinged

### Actual behavior

ping does not resolve testname. Pinging by IP works.

### Information
This happens on some of the machines. On others works fine. I've reset windows network stack, reinstalled docker, reinstalled hyper-v/containers, nothing helps.

  - Windows Version: Microsoft Windows [Version 10.0.17763.55]
  - Docker for Windows Version: 18.06.1-ce-win73 (19507)

What is the method that container hostname should be resolved by windows? Does Docker start some kind of DNS server with priority? Should it use wins/netbios? Or what else? If I would know that information I could troubleshoot more.

**Comment by simplyQQ** [comment]
By the way, DNS *inside* the container works without problems. Resolvs host.docker.internal, resolves external DNS names. 

It's the reverse which doesn't work. And I'm not sure how is it supposed to work, because I don't see docker process listening on port 53, so I don't think the DNS server is exposed to HOST? But how does it work on the other machines then?

**Comment by simplyQQ** [comment]
I found the issue, but don't know how to fix it yet.

For some reason these machines disable Multicast for Virtual Switch created by Docker, at this location in registry: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces\{1d661d44-35a5-4f2e-aab5-9b5b313eaf3a}

I can change it back, and resolution starts working, but after reboot it's back to 0.

Any idea why this happens?

**Comment by markusknappfr** [comment]
I also have the same issue.
It came up with Windows 10 1809 (both upgrade install from 1803 and clean install of 1809).

`
docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 18.09.1
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
Operating System: Windows 10 Enterprise Version 1809 (OS Build 17763.253)
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 15.86GiB
Name: PC-KnappM
ID: 2QO4:ODXC:WMCK:66PJ:53IF:2EZL:MKMS:VOBG:3YVD:DA23:LVQL:U6BI
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 26
 System Time: 2019-01-16T14:42:01.45497+01:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
`

For me it was not enough to set EnableMulticast. Additionally I had to set FullDNSRegistrationEnabled.
Both has to be done after each reboot.

Here is my Powershell script for automation:
`# Get docker nat network interface and interface config
$interface = Get-NetIPInterface | where { $_.InterfaceAlias -like "*nat*" -and $_.AddressFamily -eq "IPv4" }
$interfaceconfig = Get-NetIPConfiguration | where { $_.InterfaceAlias -eq $interface.InterfaceAlias }
#1 EnableMulticast
Get-ChildItem -Path HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces\ -Recurse | Get-ItemProperty | where { $_.IPAddress -eq $interfaceconfig.IPv4Address } | Set-ItemProperty -Name 'EnableMulticast' -Value 1
#2 DNSRegistration
Get-CimInstance -ClassName Win32_NetworkAdapterConfiguration -Filter "IPEnabled=TRUE" | where { $_.IPAddress -like $interfaceconfig.IPv4Address } | Invoke-CimMethod -MethodName SetDynamicDNSRegistration -Arguments @{FullDNSRegistrationEnabled="TRUE";DomainDNSRegistrationEnabled="FALSE"} 
`
