### ISSUE TITLE
Docker for Windows fails to start with Linux containers

### ISSUE THREAD

**Issue by DBojsen** [docker/for-win#2911]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID:8EBB9414-E606-43D7-9697-EFF92BC83A80/20181119171251

### Expected behavior
Docker for Windows should start

### Actual behavior
Docker for Windows gives error during start

### Information
I have tried with several versions of Docker.
Have tried removing Docker and Hyper-V and reinstalling several times.
Gives error every time i start with Linux containers.

### Steps to reproduce the behavior
Just start Docker and then it fails

**Comment by endlos** [comment]
Docker fails to start for me too, after upgrading to v2.0.0.0-win78  #2914

**Comment by Thierry61** [comment]
In my case the problem is corrected with latest version [Version 2.0.0.3 (312)]59
