### ISSUE TITLE
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure  at New-Switch, <No file>: line 121 at <ScriptBlock>, <No file>: line 411

### ISSUE THREAD

**Issue by Ferido07** [docker/for-win#2934]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:A4909E7C-BE10-4E3D-BCA6-3A023B529ED8/20181121204344

### Expected behavior
Expected docker for windows to start
### Actual behavior
docker for windows doesn't start and gives the error message at the above diagnostics Id
 ->Output of docker version command
docker version
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:51 2018
 OS/Arch:           windows/amd64
 Experimental:      false
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
### Information

  - Windows Version: Windows 10 Pro 1803 OS Build 17134.407
  - Docker for Windows Version: Docker Desktop Community  Version 2.0.0.0-win78 (28905)
Channel: stable
Build: c404a62 after an update from docker 18.03ce

### Steps to reproduce the behavior

  1. I couldn't mount drives directories but the drive was already mounted(in shared drives).
  2. I reset the credentials in shared drives. 
  3. I followed the steps in https://blog.olandese.nl/2017/05/03/solve-docker-for-windows-error-a-firewall-is-blocking-file-sharing-between-windows-and-the-containers/ but when I reached the step to uninstall file and printer sharing driver I couldn't uninstall it(Error Message: Could not uninstall the File and Printer Sharing for Microsoft Networks Feature. The error is 0x80071779).
4. I tried a solution at https://github.com/docker/for-win/issues/367 by @CMCDragonkai so that maybe by making docker network private that I could enable the file mounting.
 5. I updated docker for windows to Version 2.0.0.0-win78 (28905)
Channel: stable
Build: c404a62 which was previously version 18.03ce
Incidentally there was also an update to Windows but only quality updates not a major feature update.
6. After update I got a message saying containers feature has not been enabled and that I need to restart my PC. So I touched ok and restarted my PC.
7. The above error with the diagnostic Id happens when I try to start Docker for Windows or whenever it automatically starts on startup of my PC .and now I can't start docker.

All the above may have been just a coincidence and may not require all the steps. It probably may be just because of the update in docker version.

**Comment by jsefiani** [comment]
Solved this issue? @Ferido07

**Comment by Ferido07** [comment]
Nope I tried many many things and wanted to post them here so that someone could work on it more but I delayed writing what I've done to the point that I forgot. 
I didn't find any solution so I resorted to resetting docker. I previously did have problems with docker and had to reset it too I don't know what that error was too. But since resetting has become a problem for me I am taking precautions now to not reset ever again.
 - First I disabled docker from starting on startup.
 - When I use docker always quit docker before shutting down windows.

**Comment by Ferido07** [comment]
And for the sharing of files in bind mount I have discovered that it can write and read files that are in my C: drive when executing commands from a shell attached to container but never show files hosted using web servers like nginx. But all those work on files mounted on D: drive. So I just test hosted files by placing them in D: drive. I think it has to do something with security in windows.
