### ISSUE TITLE
Docker crashes at start: C:\\ProgramData\\DockerDesktop\\pki\\apiserver-kubelet-client.crt not found

### ISSUE THREAD

**Issue by baua1310** [docker/for-win#2935]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 9F434F7C-01F9-405E-A1D4-84D38CE55DA8/20181121225413

### Expected behavior
Docker starts
### Actual behavior
Docker crashes
### Information

  - Windows Version: Microsoft Windows 10 Pro Version 1803 (Build 17134.407)
  - Docker for Windows Version: Docker version 18.09.0, build 4d60db4

### Steps to reproduce the behavior

  1. Install docker
  2. Start docker desktop
  3. Docker crashes with following error message:

```
time="2018-11-21T22:54:13+01:00" level=error msg="cannot get pki directory: cannot read \"apiserver-kubelet-client.crt\": open C:\\ProgramData\\DockerDesktop\\pki\\apiserver-kubelet-client.crt: Das System kann die angegebene Datei nicht finden."

   bei Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:Zeile 36.
   bei Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:Zeile 92.
   bei Docker.Actions.<>c__DisplayClass21_0.<ResetToDefault>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:Zeile 155.
   bei Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:Zeile 59.
```

I have looked up the dir C:\ProgramData\DockerDesktop\pki. There is no file called apiserver-kubelet-client.crt but a file called apiserver-etcd-client.crt

**Comment by lipeiyuan** [comment]
same error +1
how to fix it? reinstall has no effect

**Comment by kurtjmeyoung** [comment]
got the same error.
will this be fixed in the next version?

/remove-lifecycle stale

**Comment by SUMEETRM** [comment]
SAME ERROR. HOW DO I FIX IT?

**Comment by jpvosloo** [comment]
If you are using docker with WSL 2 then do the following in a terminal:
cd /d %LOCALAPPDATA%\Docker\pki 
copy apiserver-etcd-client.crt apiserver.crt
Now try to re-start docker.
