### ISSUE TITLE
Workspce can not up!

### ISSUE THREAD

**Issue by high5** [docker/for-win#2938]
$  docker-compose up workspace

workspace_1_a8c265ad0e33 | *** Killing all processes...
workspace_1_a8c265ad0e33 | Traceback (most recent call last):
workspace_1_a8c265ad0e33 |   File "/sbin/my_init", line 417, in <module>
workspace_1_a8c265ad0e33 |     main(args)
workspace_1_a8c265ad0e33 |   File "/sbin/my_init", line 333, in main
workspace_1_a8c265ad0e33 |     import_envvars(False, False)
workspace_1_a8c265ad0e33 |   File "/sbin/my_init", line 90, in import_envvars
workspace_1_a8c265ad0e33 |     for envfile in listdir("/etc/container_environment"):
workspace_1_a8c265ad0e33 |   File "/sbin/my_init", line 74, in listdir
workspace_1_a8c265ad0e33 |     return sorted(os.listdir(path))
workspace_1_a8c265ad0e33 | PermissionError: [Errno 13] Permission denied: '/etc/container_environment'

**Comment by 80666881** [comment]
I also got this problem currently,and cannot find answer in google
but finally I tried to change the Dockerfile user form laradock to root and fixed the problem.
![image](https://user-images.githubusercontent.com/26996368/49006766-cb261000-f1a4-11e8-910a-bbdf854bfed7.png)

**Comment by gokninski** [comment]
@80666881 Thanks a lot, this worked for me after rebuilding the workspace.
