### ISSUE TITLE
Please get rid of the evil docker-for-desktop-robot

### ISSUE THREAD

**Issue by StingyJack** [docker/for-win#2953]
In addition to it being an unnecessary nag and confusing, its pointing itself in the wrong direction. 

For an issue that is logged that does not receive help or resolution after X days, the bot should be pinging contributors and members for attention. As it is now, it only serves to remind the OP that they are stuck and not getting help.  It really gives a bad impression about this project.

That I have to go through the rigamarole to join some community slack channel just to discuss the bot is an additional sharp stick to the eye..

**Comment by stephen-turner** [comment]
Won't fix. I know you don't like it, but it's the only way we can manage the volume of stale tickets. Users always have the option to mark their tickets not stale.

**Comment by StingyJack** [comment]
@stephen-turner they are only "stale" because you or one of the other maintainer or collaborators have not responded. 

It's different if the author does not reply, or if it's an obvious junk message.

After how many times of unmarking "stale" on an issue are users to expect some assistance with your creation?
