### ISSUE TITLE
Error response from daemon: CreateComputeSystem

### ISSUE THREAD

**Issue by fqi** [docker/for-win#2956]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID:BADE056A-1CAC-4980-8687-35AD4B16C27F/20181124091636

### Expected behavior
docker run -it microsoft/nanoserver cmd
enter into command prompt of container

### Actual behavior
 Error response from daemon: CreateComputeSystem 0ae1afadd02c7c7f1c5ef47d2f03060df09523d6620dfb0f9567102c0f6699b3: The locale specific resource for the desired message is not present.

### Information

  - Windows Version:  Windows Pro 1803, Build 17134.345
  - Docker for Windows Version: Docker version 18.09.0, build 4d60db4

### Steps to reproduce the behavior

  1. docker run -it microsoft/nanoserver cmd
  2. ...

have uninstall and install Hyper-V, containers, Dockers and reboot multiple times, still get the same error. Have troubleshoot the following:
- run Debug-ContainerHost.ps1
  pass the debug and get following errors from windows event log:

 ProviderName: docker
TimeCreated                     Id LevelDisplayName Message
-----------                     -- ---------------- -------
11/24/2018 8:15:39 AM            1 Warning          Could not register builder git source: failed to find git binary...
11/24/2018 8:15:38 AM            1 Warning          Running experimental build
11/24/2018 8:15:22 AM            1 Error            Handler for POST /v1.39/containers/0ae1afadd02c7c7f1c5ef47d2f030...
11/24/2018 8:15:22 AM            1 Error            0ae1afadd02c7c7f1c5ef47d2f03060df09523d6620dfb0f9567102c0f6699b3...

   ProviderName: Microsoft-Windows-Hyper-V-Compute

TimeCreated                     Id LevelDisplayName Message
-----------                     -- ---------------- -------
11/24/2018 8:15:22 AM        12000 Error
11/24/2018 8:15:22 AM        12004 Error
11/24/2018 8:15:22 AM        12002 Error

- run ProcessExploer to check if vmcompute.exe bundle with other dlls, the result is no other dll bundled with vmcompute.exe

Question:
- what is next step to further troubleshoot the issue?
- the cause for Microsoft-Windows-Hyper-V-Compute 12000, 12002 and 12004?

**Comment by PatrykBanach** [comment]
Hi there,
I had the same error and in my scenario fix was in removing folder for container.
My script's parameter changed from:
#$ContainerFolder = 'c:\containerfolder'
to:
$ContainerFolder = ''

Hope that helps.

**Comment by fqi** [comment]
Hi  PatrykBanach, thank you for your reply, where to find the script in Docker for Windows 10 installation?

**Comment by PatrykBanach** [comment]
Hi fqi,
I have created my own script in PowerShell to create container. I assume you are doing it in another way...

**Comment by spanwair** [comment]
solution worked for me: (windows 10, windows containers)
1. uninstall hyper-v (windows features)
2. restart pc
3. install hyper-v (windows features)
4. restart pc
and it worked to build my container
