### ISSUE TITLE
First 2 layers of pull consistently failing with warecv: An existing connection was forcibly closed

### ISSUE THREAD

**Issue by lannaswdt** [docker/for-win#2957]
- [ X] I have tried with the latest version of my channel (Stable or Edge)
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID: FA251AD1-9384-48C2-B9A4-92AFF8CBB8BC/20181125080032

### Expected behavior
Able to pull all layers of an image

### Actual behavior
The first 2 layers consistently fail with  error warecv: An existing connection was forcibly closed by the remote host.

### Information
Running Docker for Windows on fresh re-install of 64-bit Windows 10 on a Surface Book with 16gb RAM. 
This happens every time with microsoft/windowsservercore, microsoft/mssql-server-windows-developer
It also happens with hello-world
Coincidentally or not, this started happening after last week's Docker update.
The download begins but the first 2 layers will start to download, then stop with a "retrying in x seconds" several times. All other layers download without problem and eventually the first 2 stop retrying and display the error.

Below is the output from attempting to pull hello-world. Note that although it appears the first 2 layers downloaded fully, in fact only the first 5-10mb downloaded before the attempt failed.

`C:\Users\david>docker pull hello-world`
`Using default tag: latest`
`latest: Pulling from library/hello-world`
`bce2fbc256ea: Downloading [==================================================>]  227.5MB/227.5MB`
`4a14bdf6da80: Downloading [==================================================>]  159.1MB/159.1MB`
`842bcbb9bd6e: Download complete`
`3c15d2487d42: Download complete`
`read tcp 192.168.1.33:53705->204.79.197.219:443: wsarecv: An existing connection was forcibly closed by the remote host.`

  - Windows Version: Windows 10 Pro Version 1809, OS build 17763.107
  - Docker for Windows Version: Docker Desktop Community Version 2.0.0.0-win78 (28905), Channel: stable, Build: c404a62

### Steps to reproduce the behavior

  1. docker pull microsoft/mssql-server-windows-developer OR
  2.  docker pull hello-world

**Comment by madearipermadi** [comment]
I also facing this issue when run under Windows Container, no issue on Linux Container. Any idea if any solution to this ? if we  open 204.79.197.219 in browser, it mentioned "Our services aren't available right now"

**Comment by dzitkowskik** [comment]
I have the same issue with microsoft/windowsservercore

**Comment by AndyWDev** [comment]
I am getting this issue with the hello-world image.   It is failing with 'Proxy Authentication Required' (proxy is entered correctly) - but is successful if I switch to Linux container.

First two always fail, second two always complete.

Using 18.09.1 on Windows 10 1809.

**Comment by RedReaperKun** [comment]
I have the same issue with windows containers.
Exposing daemon on localhost:2375 without TLS helped me once. Not sure if it was coincidence or a specific scenario, but give it a try.

**Comment by bencarlson** [comment]
I'm having this same issue - was there a resolution to it?
