### ISSUE TITLE
Docker Re- Installation Error

### ISSUE THREAD

**Issue by Basileus1995** [docker/for-win#2959]
Facing a critical installation error:
![image](https://user-images.githubusercontent.com/45323656/48975158-cfcdb580-f038-11e8-9679-2f2e8dd416fd.png)

Can anybody suggest a reliable solution to this issue? I am quite a novice when it comes to docker

**Comment by endlos** [comment]
Another process is blocking your .iso image. 
You can just extract the contents of your iso file and work from there.
