### ISSUE TITLE
Windows 10: Access to the path 'C:\ProgramData\Docker\config\daemon.json' is denied.

### ISSUE THREAD

**Issue by philb32** [docker/for-win#2968]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 92021E08-DC3E-43EF-97E0-8C83590C0139/20181126082024

### Expected behavior
Docker daemon starts automatically

### Actual behavior
Docker doesn't start because access to the path 'C:\ProgramData\Docker\config\daemon.json' is denied.

### Information
Only happened after updating to ce 2.0.0.0-win77 (28777)
I am in the docker-users group on my pc

### Steps to reproduce the behavior
Start docker

**Comment by philb32** [comment]
I uninstalled docker and reinstalled it (exactly the same version), now appears to be running ok.
Interestingly, the path C:\ProgramData\Docker\config no longer exists, and the settings json files seem to be in my AppData/Roaming/Docker directory.

**Comment by dermeister0** [comment]
Permissions for `C:\ProgramData\Docker\config\daemon.json` were strange ("unable to display owner"). I changed owner and granted permissions to administrators - it did not help. Removed the file to fix the issue.

**Comment by OlegBoulanov** [comment]
Same issue here... Had to confirm admin access to C:\ProgramData\docker\, and after that switching to Windows containers worked

**Comment by NAVFreak** [comment]
For me it was problem with my Azure AD account on my local computer.
I couldn't do as @OlegBoulanov recomended manually. I got a lot of errors when I tried to reset my admin rights to that folder for my user.

Instead I had to use the following PS script and then it worked
`
$path = get-item -Path 'C:\ProgramData\docker'    
    $acl = $dir.GetAccessControl('Access')
    $username = 'Domain\User'
    $AccessRights = New-Object System.Security.AccessControl.FileSystemAccessRule($Username,'Modify','ContainerInherit,ObjectInherit','None','Allow')
    $Acl.SetAccessRule($AccessRights)
    Set-Acl -path $Path -AclObject $Acl`
[Source](https://superuser.com/questions/1107465/windows-10-ntfs-permissions-for-azure-ad-account)

**Comment by gunaygultekin** [comment]
I had the same problem on my windows 10. I went to that folder(C:\ProgramData\docker) and create daemon.json and start docker. The problem was fixed in my side.

**Comment by War777** [comment]
> Permissions for `C:\ProgramData\Docker\config\daemon.json` were strange ("unable to display owner"). I changed owner and granted permissions to administrators - it did not help. Removed the file to fix the issue.

This also worked for me :) Thanks.
