### ISSUE TITLE
error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/containers/create: open //./pipe/docker_engine: The system cannot find the file specified

### ISSUE THREAD

**Issue by rajrao** [docker/for-win#2973]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: D1245583-8B0F-4738-995C-CE6D9521CE7B/20181126103222

### Expected behavior
"docker run hello-world" runs successfully
### Actual behavior
Error:
error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/containers/create: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

### Information

  - Windows Version:
  - Docker for Windows Version: 18.09.0, build 4d60db4

### Steps to reproduce the behavior

  1. Open Powershell in admin mode.
  2. Run "docker run hello-world"

**Comment by prakashashokan** [comment]
I am also getting the same error with latest Docker version 18.09.0, build 4d60db4
docker : error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/images/create?fromImage=hello-world&tag=latest: open 
//./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run 
elevated to connect. This error may also indicate that the docker daemon is not running.
At line:1 char:1
+ docker pull hello-world
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (error during co...is not running.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by rudimenten** [comment]
I have the same issue.

docker version
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:51 2018
 OS/Arch:           windows/amd64
 Experimental:      false

**Comment by sayaninja** [comment]
Same here, anyone resolved this? 

Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:51 2018
 OS/Arch:           windows/amd64
 Experimental:      false

**Comment by rajrao** [comment]
@prakashashokan @rudimenten @sayaninja, did any of you fix this?

**Comment by jakest** [comment]
Same issue here. No idea on a fix.

**Comment by jreta** [comment]
Hi i could resolved that.
I open Docker desktop as administrator.
This is useful for me.

**Comment by nnarain** [comment]
Running docker desktop as administrator worked for me also.

**Comment by shawnye** [comment]
Net start com.docker.service   ...  OK

But it's of no veil:

C:\Users\Administrator>docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
