### ISSUE TITLE
Docker with linux container fail to start

### ISSUE THREAD

**Issue by TheSETJ** [docker/for-win#2979]
Docker give me this error when I open it:

```
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Failed to create a new virtual machine.

'MobyLinuxVM' failed to realize.
   at New-MobyLinuxVM, <No file>: line 191
   at <ScriptBlock>, <No file>: line 411
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.<>c__DisplayClass28_0.<SwitchDaemon>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 305
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

```

And here is my log file: 
[log.txt](https://github.com/docker/for-win/files/2621338/log.txt)

I know there are some other issues like this, but I've checked them and tried them all. Disabling and enabling Hyper-V and Container, uninstalling and reinstalling Docker, Hyper-V network adapters, netcfg -d, MOFCOMP %SYSTEMROOT%\System32\WindowsVirtualization.V2.mof, ... .

I still can't use docker.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 88013CE5-CDB2-4195-AEAE-4DF5D654C754/20181127215323

### Expected behavior
To work properly.

### Actual behavior
It fails and displays the error page and tray icon turns red.

![image](https://user-images.githubusercontent.com/10893088/49103244-0cdfb500-f290-11e8-8a59-cf5cce926c11.png)

### Information

  - Windows Version: 1803
  - Docker for Windows Version: 2.0.0.0-win78 (28905) stable

### Steps to reproduce the behavior

Enable Hyper-V and Container.
Restart.
Install and run Docker.

**Comment by TheSETJ** [comment]
I've deleted all the files inside folders in these folders (that mean I've deleted all of my VMs and VHDs) and Docker works fine for now:
```
C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks
C:\ProgramData\Microsoft\Windows\Hyper-V
```
I try to use Docker and see what happens next. By the way, it's not a good solution to make things work.

**Comment by mrwatchmework** [comment]
I am having the same issues. Deleting all files related to Docker and the Hyper-V folders did  not work for me.

**Comment by chrisjasp** [comment]
I'm able to reproduce this issue. Also seeing it on Docker for Windows Version 2.0.0.0-win82. It appears that in my case the HyperV machine is removed and never recreated along with the virtual switch. Removing those directories is of no help in my case.

**Comment by tuann2** [comment]
I have same issue and i find in setting in Hyper-V Setting wrong and change then it work 
Change from "G:\Hyper-V\Virtual Hard Disks" (G disk don't exit on my computer) "E:\Hyper-V\Virtual Hard Disks" 
![image](https://user-images.githubusercontent.com/43159607/50621468-a9087600-0f38-11e9-930e-142a9da0f665.png)

**Comment by EpiqSty** [comment]
Same issue, diagnostic id 69313C0E-06C7-467F-B5D2-2B045CF9F806/20190509145859

**Comment by wilomgfx** [comment]
Same issue BDA560EF-04B8-4A9C-9BAF-2CCF8AEA1CE5/20190513101030

Restarting windows is the only way to make it work.

**Comment by mwmwmw** [comment]
Fix:
https://github.com/docker/for-win/issues/2979#issuecomment-451041684

Fix this error by going into the Hyper-V manager.

1) Choose Hyper-V Settings
![mmc_2019-05-28_06-33-40](https://user-images.githubusercontent.com/889851/58478206-beae5000-8112-11e9-9d98-7d22bc097da7.png)


2) Update the "Virtual Hard Disk" and "Virtual Machine" directories to use a folder that actually exists.
![mmc_2019-05-28_06-34-06](https://user-images.githubusercontent.com/889851/58478270-ddace200-8112-11e9-93d2-dd02542d691e.png)

3) Completely restart Docker. It will create a VM "MobyLinuxVM" in the folder you have selected.

**Comment by igotinfected** [comment]
> I have same issue and i find in setting in Hyper-V Setting wrong and change then it work
> Change from "G:\Hyper-V\Virtual Hard Disks" (G disk don't exit on my computer) "E:\Hyper-V\Virtual Hard Disks"
> ![image](https://user-images.githubusercontent.com/43159607/50621468-a9087600-0f38-11e9-930e-142a9da0f665.png)

THANK YOU! I deleted those folders accidentally, just recreating them and starting docker fixed everything.
