### ISSUE TITLE
Error while creating windows node js container

### ISSUE THREAD

**Issue by kulswaroop** [docker/for-win#2983]
**Expected behavior**
Launch a windows container

**Actual behavior**
Getting an error as below,
docker: Error response from daemon: container 292eeb8ea0f24a175b184fc0e28c89348f9dfcf0966a360ef7d6c7675039eb34 encountered an error during CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2)
[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000] extra info: {"CommandLine":"npm start","WorkingDirectory":"C:\\usr\\src\\app","Environment":{"NODE_SHA256":"9cc8fd129483aa64557155842dc8f1e7ed288efeab1a7fbb0210314bc7213058","NODE_VERSION":"7.6.0","NPM_CONFIG_LOGLEVEL":"info"},"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}.

### Steps to reproduce the behavior
Here is my DockerFile,

FROM stefanscherer/node-windows:7.6.0-nano
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 8080
CMD [ "npm", "start" ]

**Comment by Bohdan-Sydor** [comment]
It looks like npm is not in Path. Try CMD [“node”, “index.js”]
