### ISSUE TITLE
Start Docker Desktop when you log in checkbox is not being respected

### ISSUE THREAD

**Issue by D3MaxT** [docker/for-win#2989]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B7C6B1BE-CE61-4CB5-8490-2244596A5508/20181128201249

### Expected behavior
If the checkbox to "Start Docker Desktop when you log in" is unchecked under Settings > General, Docker should not start with Windows on the next reboot.

### Actual behavior
The box is unchecked but Docker still starts up with Windows on every restart/login.
Verified to be happening on two PCs I have Docker installed on.

### Information

  - Windows Version: Windows 10 Professional 64-bit 1809 build 17763.134
  - Docker for Windows Version: 2.0.0.0-win78 (28905)

**Comment by hho** [comment]
Possible Duplicate of #2950
