### ISSUE TITLE
localhost force bind

### ISSUE THREAD

**Issue by adithep** [docker/for-win#3]
Copy from https://forums.docker.com/t/locahost-only-bind/18622

With the new docker for windows version(beta 20 build 5779), it binds to localhost only, but I don't think that is a good idea for windows because certain ports are blocked for example 445, 80

### Expected behavior
samba

### Actual behavior
Error response from daemon: driver failed programming external connectivity on endpoint samba (43a4e1ec467d6f584d5799e7ed3b333bd2bcabc17f0086ec0851024b018620bc): Error starting userland proxy: Bind for 0.0.0.0:445: unexpected error Unix.Unix_error(Unix.EACCES, "bind", "")
Error: failed to start containers: samba

### Information

  - Windows 10 professional, docker for windows beta 20 build 5779

### Steps to reproduce the behavior

  1. docker run -it -p 139:139 -p 445:445 -d dperson/samba

**Comment by friism** [comment]
It's because your Windows machine is already running SMB on port 445. That means the port is in use, and the docker container cannot bind to it. Disabling port 445 would not work since Docker for Windows relies on the host SMB server to do volume sharing.

Can you not map your container SMB server to a different port.

**Comment by adithep** [comment]
@friism I guess I can, but the question is bind to localhost is a good idea? I think this should be optional like before because unlike mac, widows uses so many ports by default.

**Comment by friism** [comment]
@adithep we want using Docker to be a consistent experience across platforms, and we want running Docker containers to feel like running any other app.

I'm closing this issue for now, feel free to follow up if you have concerns.

**Comment by adithep** [comment]
Can I make a request then to make localhost optional for both mac and windows version? Should I create a new issue? I think there is nothing wrong with having ability to turn off localhost bind. I am having no problem with the mac version so far but I am already considering moving back to docker toolbox on windows machine because of this. It disrupts a lot of my workflow.
