### ISSUE TITLE
Disk space still utilized even after deleting containers and images.

### ISSUE THREAD

**Issue by vamsikrishnagithub** [docker/for-win#300]
### 

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior
I am using docker 1.12.3(8488) in windows 10.

  1. ...I have images which occupied almost 20GB. 
  2. ...I deleted all images and containers  but still hard disk space is not released.

**Comment by rneugeba** [comment]
@vamsikrishnagithub thanks for reporting. This is a known issue (see #244) and we have a solution in master which will ship with the next Beta update. Closing this issue as a duplicate.

**Comment by vamsikrishnagithub** [comment]
Is there a way to clean up the already used storage space??
