### ISSUE TITLE
Cannot access the container from browser

### ISSUE THREAD

**Issue by neiamenase** [docker/for-win#3005]
Windows Version: Windows Server 2016
 Docker for Windows Version: 18.09.0
![image](https://user-images.githubusercontent.com/4963885/49282894-418b8080-f4cb-11e8-8263-0bd3abbaa890.png)

I try to follow the steps in https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-images

1. I have a Docker file on c:\Build:
FROM microsoft/iis
RUN echo "Hello World - Dockerfile" > c:\inetpub\wwwroot\index.html

2. I run using powershell with admin privilege: docker build -t  imagename c:\Build
3. I run: docker run -d -p 8000:80 --name container imagename  ping -t localhost

![image](https://user-images.githubusercontent.com/4963885/49283475-cdea7300-f4cc-11e8-8ccf-145d2c47a40e.png)

All of the above steps are fine, but I cannot access the website,

I tried every combination like:
the ip address from ipconfig:8000 or 80; the ip address from inspect :8000 / 80
![image](https://user-images.githubusercontent.com/4963885/49283669-523cf600-f4cd-11e8-9e2c-6da49403770c.png)

But it all failed.

Then, I go on the Internet and find that we can actucally call the bash. therefore, I ran exec, however, there was something strange happened:

![image](https://user-images.githubusercontent.com/4963885/49283867-e27b3b00-f4cd-11e8-8514-ea3c1f398a5f.png)

fyi
network:
![image](https://user-images.githubusercontent.com/4963885/49283933-0b033500-f4ce-11e8-90f9-d1cf167cd068.png)

inspect container:
![image](https://user-images.githubusercontent.com/4963885/49283997-49005900-f4ce-11e8-9257-62978e4caedf.png)
![image](https://user-images.githubusercontent.com/4963885/49284062-6b927200-f4ce-11e8-8859-fb0a73bdba34.png)
![image](https://user-images.githubusercontent.com/4963885/49284123-98468980-f4ce-11e8-88c2-c590456cfd5e.png)

Any advice would be helpful, thanks

**Comment by snorrk** [comment]
I believe this is a Windows Server 2016 limitation that has been lifted in Windows Server 2019.

Search for "Ports bind to localhost" on this page: https://stefanscherer.github.io/docker-on-windows-server-2019/

**Comment by neiamenase** [comment]
If anyone cares, just wanna set in the end, I have solved the problem by avoiding port mapping.
I followed the steps in
https://blogs.msdn.microsoft.com/containerstuff/2017/02/14/manage-iis-on-a-container-with-the-iis-admin-console/

And use IIS management service intead, and the result is the same, I can now containerise a website application.
