### ISSUE TITLE
Docker powershell command not working due to space in parameter

### ISSUE THREAD

**Issue by ashischangan** [docker/for-win#3013]
I am trying add host entry using below powershell command but build iss failing due to space in it.
Note -I do not want to call powershell script in dockerfile to make host entry.Below is the command which  i am using in dockerfile.
Host entry which  i am trying to add
10.21.11.12 cmservices-qa1-ch01.com

RUN powershell.exe -Command Add-Content C:\Windows\System32\drivers\etc\hosts "10.21.11.12 cmservices-qa1-ch01.com"

Error:
Add-Content : A positional parameter cannot be found that accepts argument
1>[0m[91m'imservices-qa1-usch01.corporate.ingrammicro.com'.
1>[0m[91mAt line:1 char:1
1>+ Add-Content C:\Windows\System32\drivers\etc\hosts 10.22.103.32 imserv ...
1>[0m[91m+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1>    + CategoryInfo          : InvalidArgument: (:) [Add-Content], ParameterBin
1>[0m[91m   dingException
1>    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell
1>[0m[91m   .Commands.AddContentCommand
1>[0

**Comment by ashischangan** [comment]
Here is dockfile commands:

FROM microsoft/aspnetcore:2.0-nanoserver-sac2016 AS base
WORKDIR /app
EXPOSE 80
ENV ASPNETCORE_ENVIRONMENT="Development"
RUN powershell.exe -Command Add-Content C:\Windows\System32\drivers\etc\hosts "10.21.11.12 cmservices-qa1-ch01.com"

**Comment by Nikhil13x** [comment]
Facing exactly same issue. Any solutions identified?

**Comment by mmusin** [comment]
SHELL ["powershell", "-command"] worked for me
