### ISSUE TITLE
Docker don't start anymore in Windows 10

### ISSUE THREAD

**Issue by vripa** [docker/for-win#3024]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 9499D192-76DB-4FB1-8AE3-597268E3AD95/2018-12-04_11-11-06

### Expected behavior
Docker run
### Actual behavior
When I try to connect to my container :

docker run --rm -p 5438:5432 postgres
docker: error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.37/containers/create: open //./pipe/docker_engine: Impossibile trovare il file specificato. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
See 'docker run --help'.

### Information

  - Windows Version:  10 Pro
  - Docker for Windows Version: Tried last version. Uninstalled and Reinstalled 
      Version 18.03.1-ce-win65 (17513). (Same problem)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by joxford531** [comment]
I had the same problem after updating Windows 10 yesterday. Try this solution

https://social.technet.microsoft.com/Forums/en-US/ee5b1d6b-09e2-49f3-a52c-820aafc316f9/hyperv-doesnt-work-after-upgrade-to-windows-10-1809?forum=win10itprovirt

I had to first run `net stop vmcompute`, apply the change, then finally run `net start vmcompute`. Ensure the docker service is stopped then try connecting to the Hyper-V Server from Hyper-V Manager if you don't see your local machine listed.

**Comment by narigon** [comment]
I tried this solution and it didnt worked. I also downgraded docker to an earlier version and nothing. Any clue what to do?
