### ISSUE TITLE
Unable to switch to Linux Containers in Windows 10

### ISSUE THREAD

**Issue by chinns06** [docker/for-win#3029]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ngie-eign** [comment]
This issue is probably a duplicate of #1348.
