### ISSUE TITLE
Cannot share C drive when on AzureAD domain

### ISSUE THREAD

**Issue by mbp** [docker/for-win#303]
### Expected behavior

C drive should be shared

### Actual behavior

C drive cannot be shared

### Information

  - Diagnostic ID: 7B66A5D7-A80C-4A8E-8C48-34DFF49D4BC4/2016-12-09_10-56-02
  - Docker: 1.13.0-rc3-beta32 (9266)
  - Windows 10 Pro

### Steps to reproduce the behavior

  1. Go to Docker Settings => "Shared Drives"
  2. Share C drive, enter password
  3. Wait for a bit, nothing happens

In logs I see the error:

> [SambaShare     ][Error  ] Unable to mount C drive: 10.0.75.1 (10.0.75.1:445) open
mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
mount: mounting //10.0.75.1/C on /c failed: Invalid argument

I tried disabling firewall, but still the same problem.

I am on an AzureAD domain.

**Comment by mbp** [comment]
I found related issue #132 

I solved the problem by adding a new user account to my machine (local user) with Administrator permissions. Then I used this user for sharing the drive.

However - I guess it still should work to share drives even when on AzureAD.

**Comment by dgageot** [comment]
@mbp Sorry, as explained in #132 this is not something we can fix. The workaround you used is the best thing we can do. So, I'm going to close this ticket

**Comment by mbp** [comment]
@dgageot ok. But I also think it would be quite useful if the application actually told me that it was not possible to mount the drive. As mentioned, nothing happens in the UI. I have to go to the log file to find that error.
