### ISSUE TITLE
Windows node failed to join swarm ca mismatch

### ISSUE THREAD

**Issue by behoyh** [docker/for-win#3031]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 0E63FA06-DEF7-4722-8015-A29287AD0506/20181204164615

### Expected behavior
Node (worker/manger) is able to join swarm.
### Actual behavior
Node is not able to join swarm.
### Information

  - Hyper-V
  - Windows Version: Windows Server 2016
  - Docker for Windows Version: 18.09.0 ce

### Steps to reproduce the behavior

  1. Initialize a Docker swarm on a Windows node in Linux container mode.
  2. Attempt to join the swarm on another Windows machine (Linux containers) using the join token.

**Comment by behoyh** [comment]
Related: https://devops.stackexchange.com/questions/2494/docker-swarm-join-linux-container-error-remote-ca-does-not-match-fingerprint?r=SearchResults

**Comment by robolivable** [comment]
Was there a solution for this? Why was this closed?

**Comment by behoyh** [comment]
No solution yet, although I suspect one is coming within a year or so.
