### ISSUE TITLE
docker.exe  Error response from daemon Drive sharing failed for an unknown reason

### ISSUE THREAD

**Issue by higkoo** [docker/for-win#3035]
- [ Stable ] I have tried with the latest version of my channel (Stable or Edge)
  - [ Yes ] I have uploaded Diagnostics
  - Diagnostics ID: 9CD2F59F-7D3C-416A-993C-2B0A74F46995/20181205154030

### Expected behavior
 * Mount shared drives.

### Actual behavior
 * docker.exe  Error response from daemon Drive sharing failed for an unknown reason.
### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. Docker --> Settings.
  2. Chose D to share for example( drive C is the same).
  3. Input OS passwords.
  4. Then docker restarted.
  5. But D is also not shared.

### log.txt

> [15:48:19.144][SambaShare     ][Error  ] Unable to mount D drive: 10.22.33.1 (10.22.33.1:445) open
> rm: cannot remove '/d': No such file or directory  
> rm: cannot remove '/D': No such file or directory  
> umount: /host_mnt/d: not mounted.  
> mount.cifs kernel mount options:  
> ip=10.22.33.1,unc=\\10.22.33.1\D,noperm,iocharset=utf8,dir_mode=0777,nobrl,mfsymlinks,vers=3.02,sec=ntlmsspi,user=higkoo,domain=BILIOPS,pass=********  
> mount error(13): Permission denied  
> Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)  `

### My Env
>  Microsoft Windows [Version 10.0.17134.407]
>  Client: Docker Engine - Community
>   Version:           18.09.0
>   API version:       1.39
>   Go version:        go1.10.4
>   Git commit:        4d60db4
>   Built:             Wed Nov  7 00:47:51 2018
>   OS/Arch:           windows/amd64
>   Experimental:      false

>  Server: Docker Engine - Community
>   Engine:
>    Version:          18.09.0
>    API version:      1.39 (minimum version 1.12)
>    Go version:       go1.10.4
>    Git commit:       4d60db4
>    Built:            Wed Nov  7 00:55:00 2018
>    OS/Arch:          linux/amd64
>    Experimental:     false

**Comment by higkoo** [comment]
https://github.com/docker/for-win/issues/2946

**Comment by higkoo** [comment]
mr into https://github.com/docker/for-win/issues/2946 .

**Comment by splite** [comment]
@lisemon it was closed becouse this issue was merged to issue #2946

**Comment by garyamorris** [comment]
Don't understand why this is closed? Its happening on the latest version of docker on Windows 10.0.14393. I deal with this issue several times a day. Appreciate it might be an issue with the windows hypervisor platform but surely you can get a better error message or handling, unfortunately I work in an environment where updating windows isn't an option. So I'm in a continuous loop of restarting docker/windows as docker looses access to my shared directory, its so frustrating.

**Comment by GabrielBB** [comment]
In my case it was because i took to long to provide my Windows user password
