### ISSUE TITLE
After quitting Docker for Windows you have to restart Windows to start Docker again

### ISSUE THREAD

**Issue by plbr8nc** [docker/for-win#3062]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 088CA43F-B146-422E-A0DE-EE0A73729F2B/20181208152933

### Expected behavior
You can quit D4W and restart it immediately

### Actual behavior
After quitting D4W Hyper-V ist no able to create any vSwitch. So any other attempt to restart D4W fails, because DockerNAT is not found.
After Windows restarts, everything works well again.

### Information
Windows 10 Enterprise 2016 LTSB
Docker Desktop 2.0.0.0 Win 81 (29211)

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. Start Docker Desktop
  2. Quit Docker Desktop
  3. Start Docker Desktop -> Failure:

Unable to create: Der ausgeführte Befehl wurde beendet, da die Einstellungsvariable "ErrorActionPreference" oder ein allgemeiner Parameter auf "Stop" festgelegt ist: 

Von Hyper-V wurde kein virtueller Switch mit dem Namen "DockerNAT" gefunden..

bei New-Switch, <Keine Datei>: Zeile 121
bei <ScriptBlock>, <Keine Datei>: Zeile 411
   bei Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:Zeile 36.
   bei Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:Zeile 92.
   bei Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:Zeile 74.
   bei Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:Zeile 59.

  4. Restart Windows
  5. Start Docker Desktop -> success

**Comment by elmorekevin** [comment]
I'm on Windows 1903, build 19012.1102, with Docker Desktop 2.1.5.0

If I right click on the whale icon in the taskbar, and selecting Quit Docker, I cannot seem to restart it. 

I've tried searching start bar for "docker", which appears as "Run command" and then I right-click and select Run as Administrator. A CMD window opens, but nothing happens, no new whale icon.

For those that need to stop docker if they are low on RAM, how should they restart? Shouldn't there be a simple "Docker for Windows" shortcut in the start menu to easily restart the application?

**Comment by plbr8nc** [comment]
> I'm on Windows 1903, build 19012.1102, with Docker Desktop 2.1.5.0
> 
> If I right click on the whale icon in the taskbar, and selecting Quit Docker, I cannot seem to restart it.
> 
> I've tried searching start bar for "docker", which appears as "Run command" and then I right-click and select Run as Administrator. A CMD window opens, but nothing happens, no new whale icon.
> 
> For those that need to stop docker if they are low on RAM, how should they restart? Shouldn't there be a simple "Docker for Windows" shortcut in the start menu to easily restart the application?


My experience is that a restart without a windows restart does not work.
