### ISSUE TITLE
Docker with duplicated entry on Windows Startup

### ISSUE THREAD

**Issue by rodrigoscna** [docker/for-win#3063]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 3B153C10-ED5E-4DF1-83B3-50B5F3ED3BEA/20181208162234

### Expected behavior
Docker should not startup when the checkbox is disabled on config.

### Actual behavior
Due to a duplicated entry on Windows Startup config, Docker is always starting up with Windows when the user log in.

### Information
Windows:
Version: 10.0.17134 Build 17134

Docker:
Version: 2.0.0.0-win81 (29211)
Channel: stable
Build: 4271b9e

### Steps to reproduce the behavior
  1. ...
  2. ...

### Prints of the Windows Startup config
![docker-startup-disabled](https://user-images.githubusercontent.com/519408/49689291-5937ba00-fb06-11e8-9f5b-2194d8f652c6.png)
![docker-startup-enabled](https://user-images.githubusercontent.com/519408/49689292-5937ba00-fb06-11e8-922d-dec7c0f301ac.png)

**Comment by vuongggggg** [comment]
I've got the same problem.

- Windows: Version	10.0.17763 Build 17763

- Docker: Version 2.0.0.0-win81 (29211)
Channel: stable
Build: 4271b9e

**Comment by drstonephd** [comment]
I have the same issue with the latest stable build.  Using the Sysinternals tool "Autoruns", I see two entries for the same app.  Unlike in task manager, one is for "Docker Desktop" and one is "Docker for Windows".  The Docker configuration setting controls the "Docker Desktop" item.  The path for each are the same except the first has double quotes.  As a work around, perhaps uncheck the start option in the Docker setting and then disable the remaining item.   I used Autorun to delete the "Docker for Windows" entry.  

Version 2.0.0.3 (31259)
Channel: stable
Build: 8858db3
