### ISSUE TITLE
Docker for Windows - Sign in issue

### ISSUE THREAD

**Issue by SagarPatilOnGit** [docker/for-win#3066]
I have downloaded Docker for Windows 10 from official docker website. Docker version screenshot is attached below:
![image](https://user-images.githubusercontent.com/22322341/49721149-94152b80-fc87-11e8-9e4f-441e5d32da4f.png)

I have valid docker login credentials and able to login successfully on https://cloud.docker.com/
Then I tried to login to Docker for Windows from sign in option:
![image](https://user-images.githubusercontent.com/22322341/49721305-f110e180-fc87-11e8-960e-0ea8b26a4c4d.png)

### Expected behavior
I have logged in successfully.

### Actual behavior
Not able to log in, user id & password text boxes are highlighted in Red.

### Steps to reproduce the behavior
1. Install latest docker for windows
2. Sign up on https://cloud.docker.com/
3. Try login to docker for windows using credentials created in 2nd step. Login is not successful.

**Comment by JohanSpannare** [comment]
+1

**Comment by GopinathKarthikeyan** [comment]
use your email address instead Docker ID

**Comment by SagarPatilOnGit** [comment]
@GopinathKarthikeyan  Hey, thanks it worked. But I think that label need to be changed as it clearly mention only dockerid & does not explicitly tell to use email id only.

**Comment by GopinathKarthikeyan** [comment]
@SagarPatilOnGit Sounds Good.
