### ISSUE TITLE
docker-desktop versioning scheme

### ISSUE THREAD

**Issue by riezebosch** [docker/for-win#3069]
How are you planning to use the 4 digits for normal versioning? Currently, you use `2.0.0.0` with `win-81` suffix and on top of that the `29211` build number (?).

I'm asking because last week an update of 2.0.0.0 was published with the exact same version number. This is killing the update mechanism as used by [chocolatey](https://chocolatey.org/packages/docker-desktop).

Since I'm the maintainer of that package I would like to know if it is, for example, safe to put the build number in the last part of the version number. But why do you publish 4 digits anyway if not changing when publishing newer versions?

See: https://github.com/riezebosch/BoxstarterPackages/issues/28

**Comment by gtardif** [comment]
Right, this was a mistake on our side, in the new version scheme the 4th digit should have been incremented in the latest version for an update like this one without changing the docker engine version shipped with it. 
We should have a next version coming up in less than 2 weeks, definitely with a new version number.

**Comment by riezebosch** [comment]
The same applies to the `edge` channel release? Because that's also still on `2.0.0.0`: https://download.docker.com/win/edge/appcast.xml

**Comment by StefanScherer** [comment]
@riezebosch there is a new edge version `2.0.1.0` with 30090 in the download link.

**Comment by riezebosch** [comment]
Almost fixed it but now that download link isn't working anymore 😖

**Comment by riezebosch** [comment]
> Right, this was a mistake on our side, in the new version scheme the 4th digit should have been incremented in the latest version for an update like this one without changing the docker engine version shipped with it.
> We should have a next version coming up in less than 2 weeks, definitely with a new version number.

Any news on this?

**Comment by riezebosch** [comment]
It's there https://chocolatey.org/packages/docker-desktop/2.0.0.2 🎈🎉
