### ISSUE TITLE
Shared Drives are gone after reboot of Win10

### ISSUE THREAD

**Issue by frosch95** [docker/for-win#3083]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D2563671-8D44-412A-9CB0-D896CD4C7594/20181212130443

### Expected behavior
After reboot the Win10 machine, The net shares should not disappear. 

### Actual behavior
After reboot of the Win10 machine, the net shares are available until docker is started and then they are gone.

### Information

  - Windows Version:
  - Docker for Windows Version: Server Version: 18.09.0

We have a special Network that has to be set to stop firewall blocking (172.31.31.0/255.255.255.0). 
This Network is configuredin the settings and is still available after reboot.

When the shares are not available after reboot, I can change the network to something else (e.g. 172.31.30.0) and switch back to 172.31.31.0 after the restart of docker engine when applying the correct network, the shares are available.

Is it maybe a startup issue? Maybe when docker starts to create the shares the first time and try to test them it uses the default 10.0.75.0 network which is blocked by our firewall and the network is switched to 172.31.31.0 after mounting the shares failed?

**Comment by jasimancas** [comment]
Same error here in Windows Server 2019

**Comment by frosch95** [comment]
My fix is a bit different than yours. The apply button is inactive and removing changing the checkboxes with clicking apply shows the firewall error message.

The only way for me to get this work is changing the IP, save, change back, save again.

**Comment by slav4ik51493** [comment]
> My fix is a bit different than yours. The apply button is inactive and removing/changing the checkboxes and clicking apply shows the firewall error message.
> 
> The only way for me to get this work is changing the IP, save, change back, save again.

Did you changed IP in settings of docker?

**Comment by frosch95** [comment]
![ashampoo_snap_donnerstag 31 januar 2019_02h55m17s_002_](https://user-images.githubusercontent.com/464998/52025317-2e655300-2504-11e9-8193-5f893b84a24d.png)

**Comment by slav4ik51493** [comment]
But why you use 172.31.31.0? Is it random?

**Comment by slav4ik51493** [comment]
![image](https://user-images.githubusercontent.com/15287355/52025982-f88e9180-2538-11e9-896f-5b783ae0eb86.png)
End also, I can entry "172.31.31.1" into "Subnet Address"

**Comment by frosch95** [comment]
Have you read the Information section?

The **172.31.31.0** is a special subnet which **is not blocked** by our local installed desktop **firewall** (and I can not change this!). So this is the **only available default** I can use **for the virtual switch**.

**Every other subnet is blocked!**

So fine, I can change the network to **172.31.31.0** and everything **is working as long as I do not reboot**. 

**After a reboot** the docker network is **not reachable**.

When **changing the network** settings to something else (not working as it is not supported by our companies desktop firewall) like 172.31.30.0 **enables the _Apply_ button** and I can press it (leaving the initial 172.31.31.0 does not enable the button).

So I have to **_Apply_ a not working network** to get the possibility to **change the network back** to the working 172.31.31.0 and **_Apply_ that again**. After I have done that the **docker network is reachable**.

**Every time I reboot my desktop I have to do this procedure.**
And every _Apply_ does a docker restart which takes quite a while.

So something happens when pressing Apply in the network settings that gets the docker network working, which does not happen after a reboot and the docker starts initially .

**Comment by slav4ik51493** [comment]
Oh, sorry, I haven't read the Info section.
Thank you for reply, will war with my IT section of Company for solving this problem

**Comment by slav4ik51493** [comment]
I solved my problem by adding new rule to VipNet client...

**Comment by frosch95** [comment]
I could not change the VPN rules. They are managed by the companies IT. The "trick" with changing the IP address and changing the address back is a hint, that is must not be done in the VPN Software. I have no clue what is the difference between starting docker and the automatical restart of docker after network changes.
