### ISSUE TITLE
Windows Server 2016

### ISSUE THREAD

**Issue by Lonax** [docker/for-win#3087]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 81E95F90-27A5-4EAA-B6DB-253087FA9CF1/20181212224808

### Expected behavior
   Docker to start and run
### Actual behavior
Docker starts and crashes 

### Information

  - Windows Version:
Windows Server 2016 Datacenter (1607)
  - Docker for Windows Version:
Latest
### Steps to reproduce the behavior
  1. install docker
  2. start docker
  3. crash
A reproducible case, Dockerfiles FTW.
-->
[Docker crashlog.txt](https://github.com/docker/for-win/files/2673680/Docker.crashlog.txt)

  1. install docker
  2. start docker
  3. crash

**Comment by behoyh** [comment]
You need to enable virulalization on your CPU in vmware or whatever virtualization manager you are using

**Comment by GopinathKarthikeyan** [comment]
Enable Nested nested virtualization in your machine
