### ISSUE TITLE
Nested binds with Docker-in-Docker

### ISSUE THREAD

**Issue by LazarusX** [docker/for-win#3091]
- [x] I have tried with the latest version of my channel (Stable or Edge)

### Information

  - Windows Version: Windows 10 1809 BUILD 17763.194
  - Docker for Windows Version: Docker CE Version 2.0.0.0-win81 (29211), Linux container mode

### Steps to reproduce the behavior

We provide a tool with all its dependencies as a Docker image to reduce the burden of manual setup. The tool itself also depends on Docker. Users need to map the Docker socket on host to the container so that they can perform Docker operations in the container.

Now users would also like to bind files on the host machine to the containers they create in the tool container.

Here is how to reproduce:
1. Create folder `C:/temp/test` with a `test.txt` file in it.
1. `PS> docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v c:/temp/test:/test alpine`
1. `iotedgedev@726a6bc9b9c4:/home/iotedge$ ls /test/`: `test.txt` shows up in the result
1. `iotedgedev@a7c4f9a71f34:/home/iotedge$ sudo docker run -ti -v /test:/test alpine`
1. `/ # ls /test/`: now `test.txt` does not show up.

Screenshot:
![image](https://user-images.githubusercontent.com/716650/49929924-8ae1c400-fefe-11e8-979c-fd29e2b31f91.png)

**Comment by beatfactor** [comment]
@LazarusX are there any updates on this issue? can we re-open please?

**Comment by LazarusX** [comment]
I no longer work in this area so cannot verify if this issue is still reproducible. You can open a new one if it is.
