### ISSUE TITLE
Cannot start a container after the hibernation / sleep mode ("The system cannot find the file specified")

### ISSUE THREAD

**Issue by dropsonic** [docker/for-win#3093]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 698955C6-289B-4FA3-8533-B5EE4BFCB2EA/20181213190526

### Expected behavior
The container is started.

### Actual behavior
> C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container 306168b2cf8d4d9a0b674de9bd8e85e1cec626f2ecd8d2430fe0e032e3dbd761 encountered an error during CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2)
[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]
[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]
[Event Detail: vm\compute\management\orchestration\vmhostedcontainer\processmanagement.cpp(168)\vmcomputeagent.exe!00007FF626697B25: (caller: 00007FF62667A312) Exception(2) tid(118) 80070002 The system cannot find the file specified.
    CallContext:[\Bridge_ProcessMessage\ComputeSystemManager_ExecuteProcess\VmHostedContainer_ExecuteProcess]
 Provider: 00000000-0000-0000-0000-000000000000] extra info: {"CommandLine":"PS","WorkingDirectory":"C:\\","EmulateConsole":true,"CreateStdInPipe":true,"CreateStdOutPipe":true,"ConsoleSize":[30,117]}.

### Information
  - Windows Version: Windows 10 Pro 1709 16299.785
  - Docker for Windows Version: 18.09.0
I have a fresh installation. "Containers" and "Hyper-V" features are installed.

### Steps to reproduce the behavior

  1. Install Docker for Windows
  2. Execute `docker pull mcr.microsoft.com/windows/servercore:1709`
  3. Execute `docker run -it mcr.microsoft.com/windows/servercore:1709 PS`. Verify that all works fine.
  4. Hibernate your PC or put in into sleep and turn it on again.
  5. Execute `docker run -it mcr.microsoft.com/windows/servercore:1709 PS`. You'll get the error above.

Restart of the Docker doesn't help, but full PC restart makes all work again.

**Comment by Y2zz** [comment]
In my opinion, it seems that there may be some strange problems after sleep and hibernation startup, such as shared folder mapping error.  #584

**Comment by dropsonic** [comment]
> In my opinion, it seems that there may be some strange problems after sleep and hibernation startup, such as shared folder mapping error. #584

I don't use shared volumes / shared folders.
