### ISSUE TITLE
Release 29211: start automatically, then containers are unavailable

### ISSUE THREAD

**Issue by JPMoresmau** [docker/for-win#3100]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: FBC58536-F77C-4909-9BBE-918AA324B487/20181213174347

### Expected behavior
- Docker for windows does not start automatically when I log in (the checkbox is unchecked in the Settings)
- Docker for windows work during all my working day

### Actual behavior
- Docker for windows starts automatically when I log in. Trying to start containers fail with various and seemingly random messages. Restarting manually allows to start containers
- Containers are not reachable after a few minutes (like 2 or 3 minutes of activity). They're up but I can't reach them over the network ports. Issue looks similar to #426. For example a simple postgres database is not reachable

### Information
The problem is new with 29211, everything was working fine prior the update.

  - Windows Version: Windows 10 Entreprise
  - Docker for Windows Version: 29211

### Steps to reproduce the behavior
  1. Start and try to use Docker containers for more than 5 minutes

**Comment by JPMoresmau** [comment]
Any news? This makes Docker unusable for me on Windows.

**Comment by JPMoresmau** [comment]
The log always seem to say
`vpnkit.exe: Socket.Stream: caught An existing connection was forcibly closed by the remote host` No idea what's causing that, but I see VPNKit had recently socket related changes...

**Comment by demon1636** [comment]
The same issue appears to me. I also has win 10 and 29211 docker version. Any news or workarounds?

**Comment by JPMoresmau** [comment]
Release 31259 does NOT fix the issue for me.

**Comment by JPMoresmau** [comment]
Version: 2.0.3.0 (31778) (current edge) fixes the issue for me.
