### ISSUE TITLE
Bind Port Permission denied

### ISSUE THREAD

**Issue by zhenyuT** [docker/for-win#3103]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Success to start the container sandbox-proxy
### Actual behavior
Error response from daemon: driver failed programming external connectivity on endpoint sandbox-proxy (82a3e9d811f7544db6b34e5c9af207ae0c2fbadfa45f727b2e2ded309108c371): Error starting userland proxy: Bind for 0.0.0.0:50111: unexpected error Permission denied
Error: failed to start containers: sandbox-proxy

### Information

  - Windows Version: Windows 10
  - Docker for Windows Version: 2.0.0.0-win81 (29211)

### Steps to reproduce the behavior

  1. download HDP_3.0.1_docker-deploy-scripts.sh
  2. sh HDP_3.0.1_docker-deploy-scripts.sh

**Comment by mikeparker** [comment]
Could you link to the script in question that's not working? Thanks!

**Comment by zhenyuT** [comment]
I restart docker for some times, and then it suddenly turned to work all right.
I just don't know why.

**Comment by vaibhavsingh007** [comment]
Trying to resolve it here: 
https://stackoverflow.com/questions/53898025/permission-denied-on-port-when-starting-hdp-sandbox-proxy-on-docker-windows-10

**Comment by vaibhavsingh007** [comment]
> Could you link to the script in question that's not working? Thanks!

The script is proxy-deploy.sh

**Comment by vaibhavsingh007** [comment]
I tried the solution as suggested in SO (https://hortonworks.com/tutorial/sandbox-deployment-and-install-guide/section/3/#port-conflict). 
Few observations: 

1. When trying to edit the key name by adding a digit (eg. 50111:50111 -> 150111:50111), start to get the following error: 
 `invalid publish opts format (should be name=value but got '1080:1080').`
2. But deleting a digit, instead of adding seems to work. However, 
3. After trying to resolve all port conflicts (using that soln.), now getting the following error: 

```
sandbox-proxy
888e1bb1af36df4b0009858537905cdd74662d254fb11b1cb3c52bb2d87e94a4
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/cygdrive/c/Users/vaibh/Downloads/HDP_3.0.1_docker-deploy-scripts_18120587fc7fb/assets/nginx.conf\\\" to rootfs \\\"/var/lib/docker/overlay2/186ff8e2eb6dcbdcfbd4714823a1e4a322dfb28eb00eba7b7fea32a6e8ba54f5/merged\\\" at \\\"/var/lib/docker/overlay2/186ff8e2eb6dcbdcfbd4714823a1e4a322dfb28eb00eba7b7fea32a6e8ba54f5/merged/etc/nginx/nginx.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
```

Any suggestions will be appreciated.

**Comment by harperd** [comment]
For those still facing this issue I found the fix (for me [here](https://stackoverflow.com/questions/54181219/windows-cant-bind-to-port-above-49690)). Hope this helps others. Cheers!

**Comment by eruiz** [comment]
I have the same issue @vaibhavsingh007 described in https://github.com/docker/for-win/issues/3103#issuecomment-449650661 

Any help to sove that issue will be welcome

Thanks
