### ISSUE TITLE
I can't share my C: drive in Linux containers... smh. It says my firewall is blocking it... my firewall is turned off.

### ISSUE THREAD

**Issue by Iraaltizer** [docker/for-win#3105]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by GopinathKarthikeyan** [comment]
Mount a folder from C drive to Linux container
