### ISSUE TITLE
Reset to Factory defaults in Docker stable version Windows 10 - Dockerd docker engine service still refusing to start...

### ISSUE THREAD

**Issue by S3curityPlu5** [docker/for-win#311]
NOTE: I Thought I HAd SOLVED THIS PROBLEM , its just that the dockerd service still won't start... see last comment please for solution-
### Expected behavior
Reset to Factory defaults should bring windows 10 pro to working container host,

### Actual behavior
Docker Error popup displays: 
Receives error: Unable to start: The VM couldn't get an IP address after 60 tries
at Fatal, <No file>: line 353
at Start-MobyLinuxVM, <No file>: line 267
at <ScriptBlock>, <No file>: line 363
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
AFTER renaming old VM to OLDmobylinux, then reset to defaults again, but new VM was created and after running command docker images : 
receive the following 
An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/images/json: open //./pipe/docker_engine: The system cannot find the file specified.
### Information
Cannot get back to working state, No reason why cannot get an ip address, doesn't make sense, only one docker Nat network adapter set to default address settings, 

Diagnostic ID = 6696D7DE-88FD-44F5-90F6-BFAE1E91BD10/2016-12-11_13-22-30

This is a bug with my system, but would like to see why this cannot be fixed.
  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ... Rename old VM to OLDMOBYVM
  2. ...Reset to factory defaults

**Comment by S3curityPlu5** [comment]
digging through the logs and I see the following ip addresses are being used
192.168.65.2:55084 -> 192.168.65.10 2387
However, I have my Docker nat set to 10.0.75.1
This may be the reason that the VM is not getting an address, but where is the docker daemon getting 192.168.65 from?

**Comment by S3curityPlu5** [comment]
MobyLinuxVM was recreated successfully when reset to factory settings, but new  VM then Failed to shut down, after three attempts event log  = 
No more attempts will be made to automatically restart the virtual machine 'MobyLinuxVM' (ID=7B86AAA0-BF9E-4E71-ADA8-EE4030354FD1) because it has stopped responding to repeated attempts to restart it.

**Comment by S3curityPlu5** [comment]
OK, - Important -  Still using the stable version and changed the DOCKER NAT Network Adapter to 192.168.65.2 and the default gateway to 192.168. 65.1 and now it is working from command line as expected.  I did not change the addresses in the docker for windows application however.

**Comment by S3curityPlu5** [comment]
Since this is still open I should comment that although I am able to run docker containers, the docker daemon, or engine (dockerd service) is still refusing to start, when attempting to start from command line receive the following error:  level=fatal msg="unable to configure the Docker daemon with file 
C:\\ProgramData\\docker\\config\\daemon.json: json: cannot unmarshal string into Go value of type bool\n
kitematic now displays containers and can start and stop them, and there is now another service the com.docker.service running successfully but the docker engine refuses to start, I have set the config file to defaults, and taken out tlc verify= true, because of tls cert errors when it was true.

**Comment by jornh** [comment]
In your last comment I just noticed this: 

> "unable to configure the Docker daemon with file
C:\ProgramData\docker\config\daemon.json: json: cannot unmarshal string into Go value of type bool"

Sounds like a problem with the contents of this file. So, what's to content of your `daemon.json`? 

For reference after I completely nuked my `C:\ProgramData\docker\` tree before installing beta 32.1 mine is now just an empty JSON object, so: `{}`. Maybe you can get it working with that too?

**Comment by S3curityPlu5** [comment]
Thanks, I may have to nuke it but for now ... Here is the file
{
    "authorization-plugins": [],
    "bridge": "",
    "cluster-advertise": "",
    "cluster-store": "",
    "debug": true,
    "default-ulimits": {},
    "disable-legacy-registry": false,
    "dns": [],
    "dns-opts": [],
    "dns-search": [],
    "exec-opts": [],
    "fixed-cidr": "",
    "graph": "",
    "group": "",
    "hosts": [],
    "insecure-registries": [],
    "labels": [],
    "log-driver": "",
    "log-level": "",
    "mtu": 0,
    "pidfile": "",
    "raw-logs": false,
    "registry-mirrors": [],
    "storage-driver": "",
    "storage-opts": [],
    "tlscacert": "",
    "tlscert": "",
    "tlskey": "",
    "tlsverify": ""
}
