### ISSUE TITLE
Please, help me.

### ISSUE THREAD

**Issue by skwcrd** [docker/for-win#3113]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by AnthonyMastrean** [comment]
@skwcrd did you mean to post some details? your issue is empty 😄
