### ISSUE TITLE
Can't start "docker for windows"

### ISSUE THREAD

**Issue by saaadel** [docker/for-win#312]
### Expected behavior
started docker
### Actual behavior
hold on starting stage
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
A9638626-3DED-4D8F-97E2-5D96D87CE01B/2016-12-12_02-22-05
  - a reproducible case if this is a bug, Dockerfiles FTW
just installed docker from site, and ran item 1 from https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_10

  - page URL if this is a docs issue or the name of a man page
none
  - host distribution and version (Windows version, build number, etc)
Docker 1.12.3 (8488) stable d63ec34
Windows 10 Pro x64
Hyper-V Manager 10.0.14393.0

### Steps to reproduce the behavior

  1. ... installed docker from site: https://www.docker.com/products/docker#/windows
  2. ... started  "docker for windows" - holded on starting stage
  
  3. reboot
  4. ... started  "docker for windows" - holded on starting stage
  
  5. ran commands from item 1: https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_10
  6. reboot
  7. started "docker for windows" - holded on starting stage.

FYI Docker service is running

**Comment by saaadel** [comment]
Possible duplicate of Docker Hangs with "Docker is Starting" #291

**Comment by rneugeba** [comment]
@saaadel thanks for the report. We have an issue in the stable Branch where not all logs are collected. Could you try the latest Beta and see if that fixes the issue? If not we should at least get more logs from it.
thanks

**Comment by marjorienorm** [comment]
I'm having a star-up issue as well.  On start up I get an error with the following associated log

Version: 1.13.0-rc3-beta32.1 (9324)
Channel: Beta
Sha1: 31bcc0f6246738430a332a16bb698aa5ea48d80c
Started on: 2016/12/12 07:07:55.434
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1511
Build: 10586
BuildLabName: 10586.672.amd64fre.th2_release_sec.161024-1825
File: C:\Users\<USER ID>\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[07:07:56.051][GUI            ][Info   ] Starting...
[07:07:56.752][GUI            ][Error  ] Object reference not set to an instance of an object.
[07:07:56.831][CrashReport    ][Info   ] Preparing package to send with the diagnostics
[07:07:56.847][NamedPipeClient][Info   ] Sending GetDebugInfo()...
[07:07:56.865][NamedPipeClient][Info   ] Sending DownloadVpnKitLogs(C:\Users\<USER ID>\AppData\Local\Temp\xghbea0y.x5o\pcap.tar)...
[07:07:56.885][NamedPipeClient][Info   ] Sending DownloadVmLogs(C:\Users\<USER ID>\AppData\Local\Temp\xghbea0y.x5o\mobyLogs.tar)...
[07:07:57.802][NamedPipeClient][Info   ] Received response for DownloadVmLogs
[07:08:21.013][ErrorReportWindow][Info   ] Open logs

**Comment by rneugeba** [comment]
@simonferquel can you take a look at:
```
[07:07:56.752][GUI ][Error ] Object reference not set to an instance of an object.
```
This doesn't look too good to me

**Comment by simonferquel** [comment]
Hi @marjorienorm, could you go to the diagnostics tab, upload a diagnostic and give as the is ?

Thanks

**Comment by saaadel** [comment]
Still have this bug on beta, but after windows was started:
- I have stopped docker service, 
- exited from docker in tray, 
- started service again, 
- and booted docker in tray
and it's working now

**Comment by rneugeba** [comment]
I'm closing this issue. It seems @saaadel has fixed the issue. @marjorienorm if you still have an issue please try the latest Beta and open a new issue with a Diagnostics ID so that we can take a closer look.
Thanks

**Comment by saaadel** [comment]
Just will add details: problems only for linux containers on Windows. Stop-start scenario can help, tried it multiple times. Sad only that it does not work out of the box
