### ISSUE TITLE
Disabling "Automatically start Docker Desktop when you log in" won't work

### ISSUE THREAD

**Issue by SetTrend** [docker/for-win#3128]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

When I deselect "Automatically start Docker Desktop when you log in", Docker for Windows should _not_ start at log-on.

### Actual behavior

Although I deselected "Automatically start Docker Desktop when you log in" and although the checkbox is unchecked, Docker for Windows automatically starts at log-on.

### Information

  - Windows Version:
     Windows 10x64, v1809

  - Docker for Windows Version:
![grafik](https://user-images.githubusercontent.com/9283914/50323348-89556480-04d9-11e9-8832-2ae420de444d.png)

### Steps to reproduce the behavior

![grafik](https://user-images.githubusercontent.com/9283914/50323376-aa1dba00-04d9-11e9-8d2f-0d22f69486f2.png)
<br/>

I had to manually disable Docker for Windows in Task Manager:

![grafik](https://user-images.githubusercontent.com/9283914/50323379-b275f500-04d9-11e9-8ed3-2a5e6a290bbe.png)

**Comment by joshco** [comment]
I see this problem as well. Even though the checkbox is unchecked, When I reboot or log in, docker starts anyway.
![image](https://user-images.githubusercontent.com/290314/50375615-445f2a00-05ce-11e9-855a-105fc03aca40.png)

**Comment by mieber** [comment]
Same here. I use docker only from time to time and don't want to start it always.

**Comment by polys** [comment]
Same here with both the latest Stable and Edge on Windows 10 Pro 1809 and the latest Insider builds.

**Comment by mikeparker** [comment]
Thanks for reporting, this should be fixed by next release.

It's caused by our renaming to Docker Desktop and a mismatch in the windows registry. 

A workaround is to manually remove the registry key `Docker Desktop` in `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run`.

**Comment by SetTrend** [comment]
@mikeparker : Has this issue been fixed and can it be solved?

**Comment by mikeparker** [comment]
This is marked as fixed internally, I'm not sure which release it's in though. Feel free to close it or wait to test a new build.

**Comment by SetTrend** [comment]
I just updated to:

```
Version 2.0.0.3 (31259)
Channel: stable
Build: 8858db3
```

... and tested the setting. Apparently it hasn't been fixed yet.

**Comment by istrupin** [comment]
Can confirm this is still happening Windows 10 v1803

**Comment by martintzonev** [comment]
@mikeparker This seems to be still an issue on 2.1.0.0 (36874).  You mentioned the next stable update but that doesn't seem to be the case. Or am I misunderstanding the versioning?

**Comment by mikeparker** [comment]
@martintzonev you understand correctly, this should be fixed now on latest stable 2.1.0.0.

For existing broken setups you may need to check + uncheck the setting, can you try that please?

**Comment by martintzonev** [comment]
Thanks @mikeparker, switching the setting on and off did the trick. The service is no longer starting automatically on boot.

**Comment by mikeparker** [comment]
@martintzonev great, thanks for the update!
