### ISSUE TITLE
Can I connect Docker Desktop for windows to macOS host docker?

### ISSUE THREAD

**Issue by rspaulino** [docker/for-win#3147]
Currently using MacBook Pro + Docker Desktop for Mac + Parallels Desktop + Windows 10 + Visual Studio 2017.

I would like to offset as much as I can work from my VM to run native on macOS, so I wondering if it's possible to have Docker Desktop for windows to use the macOS host for the linux container. I would like to disable hyper-v and have all process related to docker running on the macOS host.

**Comment by pgayvallet** [comment]
Hello,

With socat, you should be able to expose the docket socket to a port on any interface, and use --host from the windows VM to connect to the mac daemon.

Something like `socat -d -d TCP-L:8080,fork UNIX:/var/run/docker.sock`
