### ISSUE TITLE
docker never started 

### ISSUE THREAD

**Issue by kvenkat79** [docker/for-win#3152]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 05C7BC0D-6824-4932-A30A-65A20C5059C4/20181228101030

### Expected behavior
Docker should start
### Actual behavior
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/containers/json?all=1: open //./pipe/docker_engine
: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be r
un elevated to connect. This error may also indicate that the docker daemon is not running.
### Information

  - Windows Version: 10 enterprise
  - Docker for Windows Version:18.09.0, build 4d60db4

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by GopinathKarthikeyan** [comment]
@kvenkat79 , Configure your docker daemon on the container host

**Comment by kvenkat79** [comment]
Can you please provide me the steps >> since I am new to docker

**Comment by GopinathKarthikeyan** [comment]
@kvenkat79 , The below URL will help you to configure docker daemon.

https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/configure-docker-daemon
