### ISSUE TITLE
Cant log in to Docker for Windows

### ISSUE THREAD

**Issue by MadDexter** [docker/for-win#3160]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...
I cannot log in to the DOcker for Windows console. I am able to log in to hub.docker.com with my username and password.

**Comment by GopinathKarthikeyan** [comment]
Try using User ID, If that is not working, Use your email ID.
