### ISSUE TITLE
"Expose daemon on tcp://localhost:2375 without TLS" option works only for the first Docker run

### ISSUE THREAD

**Issue by hron** [docker/for-win#3163]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6F8C3689-E193-4B32-A4F4-5A90E1D56AF3/20181231142202

### Expected behavior

After checking "Expose daemon on tcp://localhost:2375 without TLS" Docker should listen on 2375 port.

### Actual behavior

If you check this option just after installation it works until the first restart. I've tried blank slate install and etc...

### Information
  - Windows Version: Windows 10 Pro (10.0.17763 Build 17763)
  - Docker for Windows Version: Version 2.0.0.0-win81 (29211) / Build: 4271b9e

### Steps to reproduce the behavior

1. Download and install Docker
2. Run Docker, go to Settings -> General
3. Click on "Expose daemon on tcp://localhost:2375 without TLS"
4. Restart
5. Run Docker and check if it listens on 2375 port (you can use `resmon.exe` for that for example)

![image](https://user-images.githubusercontent.com/39293/50560459-a5db7300-0d09-11e9-8b81-0112134cd296.png)

**Comment by hron** [comment]
Unfortunately, this doesn't help. Also I am sure that Docker passes the correct values to `com.docker.proxy.com` process, but for some reason it doesn't listen on the requested port. Is there any way to debug it further?

Here is how I detect that the correct params are passed:
```powershell
PS C:\Users\aleks> Get-CimInstance Win32_Process -Filter "name = 'com.docker.proxy.exe'" | \
   select CommandLine                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                              
CommandLine                                                                                                                                                                                                                                                                                   
-----------                                                                                                                                                                                                                                                                                   
"com.docker.proxy.exe" -VM=8495ced5-6a34-47d6-ba15-f2f97f3c7124   \
        -dockerExe "C:\Program Files\Docker\Docker\Resources\bin\docker.exe" \
        -exposeTcp=localhost:2375 -proxyGUID=00000948-FACB-11E6-BD58-64006A7986D3                                                                              
```

However, there nothing listens on 2375 port:

```powershell
PS C:\Users\aleks> netstat -a -o -n | Select-String -Pattern 2375
PS C:\Users\aleks>                                               
```

I've also tried to disable my antivirus and uninstalling it completely. No luck...

**Comment by hongaar** [comment]
Could this be somehow related to https://github.com/docker/for-win/issues/3171? For me, `netsh interface ipv4 show excludedportrange protocol=tcp` includes the range `2302-2401`.

I work around this issue for now using this proxy https://gist.github.com/hongaar/d30fb88b937fe322b6a36f744c3e14a7

**Comment by hron** [comment]
I've just managed to nail my problem down. It turns out that the source of it was in Kaspersky AntiVirus. The important note that disabling Kaspersky doesn't fix it. I had to uninstall Kaspersky and reinstall Docker again. Only then the problem is fixed. I guess the issue should be closed because everything is okay with Docker regarding to this feature.

**Comment by hongaar** [comment]
@hron how did you find this out? Trial and error or is there some useful command to run to debug this further? I have the same problem but in my case, it can't be Kaspersky (don't have it installed).

**Comment by hron** [comment]
@hongaar in my case, if I uninstall Kaspersky and reinstall docker everything works okay. I am working with Kaspersky support to debug the issue further, but we don't yet have any precise results from this research. Will continue to work on it next week.

**Comment by hron** [comment]
For me the issue is resolved now and it seems Kaspersky wasn't the issue. I tried to follow the instructions from Kaspersky which involved disabling all services (["clean boot" for Windows](https://support.microsoft.com/en-gb/help/929135/how-to-perform-a-clean-boot-in-windows)) and it seems some of the services didn't work correctly on my desktop. I have suspicions that it was 'Intel Turbo Boost 3.0', but as I said the issue is not reproducible for me anymore.

**Comment by mabdelfattah** [comment]
@hron So, now you have latest versions of both Docker and Kaspersky working fine?

**Comment by onikih** [comment]
I use Norton Internet Security, not Kaspersky.  I was able to solve a problem similar to the one raised here by "opening port 2375 to Docker in the firewall setting of Norton."
