### ISSUE TITLE
All Containers lost during Update to 1.13.0-rc3-beta32

### ISSUE THREAD

**Issue by visual4** [docker/for-win#317]
### Expected behavior
After the Update, I expected to be able to start my existing containers like usual and like after the other updates before.
### Actual behavior
All of my containers, images and the login information to docker hub were lost. During update I was asked if I wanted to migrate data from docker toolbox, (which was still installed on my system, despite, I have been using docker for windows for almost half a year now).

### Information
https://forums.docker.com/t/all-containers-lost-during-update-to-1-13-0-rc3-beta32/25799/2

### Steps to reproduce the behavior

the following were the actions I took/ that happened:
- update notification, new docker version
- start upgrade
- popup about required reboot during update
- I cancelled the update by declining the popup
- docker had already been stopped by the update process, so I started docker
- the docker toolbox migration window appears - I answered no
- containers, images, login information is lost

- afterwards I did the update with reboot, hoping that the data somehow re-appears, unfortunately without luck

**Comment by dgageot** [comment]
Hi @visual4 Sorry there was a bug in Beta31 that could lead to losing all your containers. It is fixed in Beta32, but it got triggered during the upgrade process. I'm going to close this issue since it's fixed now.
