### ISSUE TITLE
Can't call GenerateConsoleCtrlEvent system call in windows containers

### ISSUE THREAD

**Issue by lox** [docker/for-win#3173]
### Expected behavior

When starting a process in a windows docker container, it's expected that the process should be able to call [GenerateConsoleCtrlEvent](https://docs.microsoft.com/en-us/windows/console/generateconsolectrlevent) to send CTRL_C or CTRL_BREAK events to it's own console process group and sub-processes.

This technique is used to signal subprocesses to gracefully terminate, e.g clean up resources before the stop.

### Actual behavior

Any call to `GenerateConsoleCtrlEvent` returns `Incorrect function`.

### Information

Windows version: Windows 10 Pro: Version 10.0.17134.472
Docker for Windows: 2.0.0.0-win81 (29211)

### Steps to reproduce the behavior

```go
package main

import (
	"log"
	"os"
	"os/signal"
	"syscall"
	"time"
)

var (
	libkernel32                  = syscall.MustLoadDLL("kernel32")
	procGenerateConsoleCtrlEvent = libkernel32.MustFindProc("GenerateConsoleCtrlEvent")
)

func main() {
	sigs := make(chan os.Signal, 1)
	signal.Notify(sigs)
	go func() {
		s := <-sigs
		log.Printf("Got signal %v", s)
		os.Exit(0)
	}()

	r, _, err := procGenerateConsoleCtrlEvent.Call(syscall.CTRL_C_EVENT, uintptr(0))
	if r == 0 {
		log.Fatalf("Error sending CTRL_C_EVENT: %v", err)
	}

	time.Sleep(time.Second)
	log.Printf("Exiting normally")
}
```

Dockerfile:

```
FROM mcr.microsoft.com/windows/servercore:ltsc2016
COPY ./ctrl-break-test.exe /
CMD ["/ctrl-break-test.exe"]
```

Tested with golang 1.11.4:

```
go build -o ctrl-break-test.exe .
docker build --tag ctrl-break-test .
docker run --rm ctrl-break-test
```

Output is:

```
2019/01/03 20:47:11 Error sending CTRL_C_EVENT: Incorrect function.
```

Expected (as when run from outside docker):

```
2019/01/03 20:52:08 Got signal interrupt
```

**Comment by lox** [comment]
@StefanScherer @mattn is this something you have encountered before? @mattn, I was liberally borrowing your idea from https://github.com/mattn/goemon/blob/master/proc_windows.go.

If anyone has a better suggestion on where to post this, I'd welcome it!

**Comment by mattn** [comment]
FYI, if you want to terminate process tree forcibly, you can use CreateJobObject/TerminateJobObject.

**Comment by lox** [comment]
Thanks @mattn, the thing I wanted most was to be able to intercept a signal and do a graceful shutdown with some cleanup. Ctrl-c and Ctrl-break seem like the only practical ways to do that?

**Comment by StefanScherer** [comment]
@lox have you tried Windows Server 2019? It is fixed in the ltsc2019 image.

I put your example code here and added a Dockerfile

```Dockerfile
FROM golang:1.11.4

COPY testctrlc.go testctrlc.go
RUN go build testctrlc.go

CMD [ "testctrlc.exe" ]
```

When I build and run the image on a Windows Server 2016 I can reproduce the error:

```
$ docker build -t testctrc .
$ docker run testctrlc
2019/01/07 07:29:34 Error sending CTRL_C_EVENT: Incorrect function.
```

When I build and run the image on a Windows Server 2019 it works:

```
$ docker build -t testctrc .
$ docker run testctrlc
2019/01/07 07:30:25 Got signal interrupt
```

Thanks @taylorb-microsoft and team for yet another improvement in Windows Server 2019 :-)
Thanks @tianon and team for adding Windows Server 2019 to the golang multi-arch image 🎉

**Comment by lox** [comment]
Thanks very much for that @StefanScherer! I'll try that image!

**Comment by mattn** [comment]
ping

**Comment by lox** [comment]
I can confirm this works in `ltsc2019` images, closing!
