### ISSUE TITLE
docker-compose in docker cannot mount file

### ISSUE THREAD

**Issue by u007** [docker/for-win#3180]
not sure if this is just docker for windows issue or its a docker compose in docker issue
but can someone please check this on windows?

  - [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: B4FF6B1C-D14E-42B0-81EB-E3667E3CB183/20190104113914

### Expected behavior

i did docker-compose up -d on the directory from within host machine and it works.
all instance started and running.

then  i add a comment into the docker compose file for caddy service and admin, and then:

```
docker run --rm -it -v "//c/project/srv:/srv" -v "//var/run/docker.sock:/var/run/docker.sock" --entrypoint /bin/sh docker/compose:1.23.2
$ cd /srv
$ docker-compose up -d
```
here is my compose file example:
```
admin:
    image: registry.gitlab.com/myproject/project:master
    ports:
     - 3000:3000
       restart: unless-stopped
  caddy:
    image: abiosoft/caddy
    volumes:
     - "./caddy/Caddyfile:/etc/Caddyfile"
     - "./caddy/.caddy:/root/.caddy"
    ports:
     - 80:80
     - 443:443
    restart: unless-stopped
```

docker-compose should recreate admin and caddy should work

### Actual behavior

admin recreated : ok, but caddy throws:
```
Recreating srv_caddy_1_1b00456b78ef ... error

ERROR: for srv_caddy_1_1b00456b78ef  Cannot start service caddy: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/srv/caddy/Caddyfile\\\" to rootfs \\\"/var/lib/docker/overlay2/54719ba66672bdf87c86884b3843630453cc13aceb5f2f8a33463092859b731b/merged\\\" at \\\"/var/lib/docker/overlay2/54719ba66672bdf87c86884b3843630453cc13aceb5f2f8a33463092859b731b/merged/etc/Caddyfile\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for caddy  Cannot start service caddy: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/srv/caddy/Caddyfile\\\" to rootfs \\\"/var/lib/docker/overlay2/54719ba66672bdf87c86884b3843630453cc13aceb5f2f8a33463092859b731b/merged\\\" at \\\"/var/lib/docker/overlay2/54719ba66672bdf87c86884b3843630453cc13aceb5f2f8a33463092859b731b/merged/etc/Caddyfile\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

### Information

  - Windows Version: 10 enterprise
  - Docker for Windows Version: 
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:51 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false

### Steps to reproduce the behavior

  1. please follow "Expected behavior" section

**Comment by drazul** [comment]
I just had the same problem and I solved going to the shared drives section, I disabled every shared drives and enabled again and all was solved.
I think this is related with a password change I did days ago and I found the solution here: https://stackoverflow.com/questions/45972812/are-you-trying-to-mount-a-directory-onto-a-file-or-vice-versa

**Comment by u007** [comment]
yes exactly  that happened due to password change

**Comment by IonelLupu** [comment]
@drazul @u007 disabling and enabling shared drivers doesn't work for me :/

**Comment by JackFe** [comment]
yes, disabling and enabling shared drivers in File sharing and restart container, it resolved!
![image](https://user-images.githubusercontent.com/24237673/82136693-d2325980-9842-11ea-9da2-8d983c8b0aaf.png)
