### ISSUE TITLE
An error occurred trying to run Docker for Windows

### ISSUE THREAD

**Issue by sergeivisotsky** [docker/for-win#3181]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 0B3DB8F6-C60B-4824-A011-EB181037CAA5/20190104090233

### Expected behavior
Be able to run Docker on Windows 10 without error described further.

### Actual behavior
```
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```
### Information

  - Windows Version: 10 Pro 1803, build 17134.472
  - Docker for Windows Version: 18.09.0, build 4d60db4

### Steps to reproduce the behavior

  1. Disabled Hyper-V to run Oracle VirtualBox
  2. Enabled Hyper-V so that it was able to Run Docker
  3. Trying to Reset to factory defaults

What kind of further actions should I perform to solve this issue?

**Comment by EmidioNeto** [comment]
I'm facing the same issue after some windows update.
Other thing that I found is that I 'm not able to create any new switch in Hyper-V.

![image](https://user-images.githubusercontent.com/998850/50685007-81381180-100f-11e9-8fac-f519f6740a64.png)

Also in the Hyper-V Virtual Switch Manager shows this error

![image](https://user-images.githubusercontent.com/998850/50685072-b9d7eb00-100f-11e9-955a-9150481e3879.png)

I tried to reinstall docker and Hyper-V features but without success.

I don't know if this option should be checked, but when I try to check I get this warning and the option is unchecked.

![image](https://user-images.githubusercontent.com/998850/50685277-72059380-1010-11e9-8711-714057819ce1.png)

**Comment by bruparel** [comment]
@EmidioNeto How do you Uninstall and Install Hyper-V?  Can you give steps?  I have exactly the same error as in this thread.  I want to try your solution.

**Comment by bruparel** [comment]
@EmidioNeto I found out how to Uninstall and Install Hyper-V, so please disregard the message above.  However, I was not able to find the keys that you mention above.  I did a 'regedit' and followed the path.  Both the keys don't exist.  Uninstalling Hyper-V, reboot, install Hyper-V, reboot did not fix Docker

**Comment by mikeparker** [comment]
There are a few different issues in this thread. 
* To the OP: VirtualBox and Hyper-V are not compatible, unfortunately theres not much docker can do about that.
* Failing on creating switches in hyper-v after a windows update is a separate issue, See https://github.com/docker/for-win/issues/1221#issuecomment-493118403 for the 'control flow guard' fix

**Comment by sergeivisotsky** [comment]
This issue is resolved. Please, close it.

**Comment by Shailesh1914** [comment]
Hi sergeivisotsky. You suggest that the issue is resolved.  Can you pls. suggest the steps for issue resolution.

**Comment by sergeivisotsky** [comment]
@Shailesh1914 Unfortunately, I don't remember solution step-by step but as far as I remember I've enable some Windows feature but it is not exactly :-)
