### ISSUE TITLE
Unable to mount drive, warned of firewall issues when there aren't any

### ISSUE THREAD

**Issue by shanselman** [docker/for-win#319]
### Expected behavior

Still unable to mount a drive. Firewall warning appears even though firewall rule is set.

![image](https://cloud.githubusercontent.com/assets/2892/21163089/d529e374-c145-11e6-9baa-cf86bc0c71cd.png)

### Actual behavior

On Windows 10 14986 with Docker Beta. I get the firewall warning with a default hello world isntall.

### Information

 A diagnostic was uploaded with id: 4DB63861-A8C7-4709-BFF1-B0A7DCEE82BA/2016-12-13_15-07-38

**Comment by simonferquel** [comment]
Hi Scott, we don't support insider builds for now but I'll still have a look to your diagnostics file to see if I see something obvious. Keep you posted!

**Comment by simonferquel** [comment]
The only thing I see is that I don't see any event in the Samba Server eventlog related to the DockerNat virtual network interface (as if the listener was not aware of this interface). It might be because of log truncation (we only get the last messages in the eventlog within diagnostics data).

Can you try from your local machine to access \\10.0.75.1\c (just make sure D4W did not remove the file share before) ?

**Comment by friism** [comment]
Might be related: https://github.com/docker/for-win/issues/326

**Comment by markharrisonuk** [comment]
I have the same issue - same build of Windows.

A43F6C92-060D-4D75-BA23-71C77EAE932E/2017-01-05_17-16-47

**Comment by dgageot** [comment]
Hi @shanselman @markharrisonuk, we've tried to fix this issue in a test release that can be downloaded here: https://download-stage.docker.com/win/samba-experiment/10154/InstallDocker.msi

**Comment by shanselman** [comment]
@dgageot Nope. 
![image](https://cloud.githubusercontent.com/assets/2892/23324470/d1f23508-faa2-11e6-97ce-b5fa1f67f013.png)

**Comment by shanselman** [comment]
If I turn this off and on, it works. But I have to do this EVERY time I changed networks.
![image](https://cloud.githubusercontent.com/assets/2892/23324572/60879b8c-faa3-11e6-99e7-36174251250c.png)

**Comment by jasonbivins** [comment]
@shanselman   Is this still a problem for you in the newer versions?
