### ISSUE TITLE
Unable to connect to the server: EOF

### ISSUE THREAD

**Issue by gulativivek** [docker/for-win#3194]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 649D1C5C-1B4A-436B-A360-8C5946D70B08/20190108114824

### Expected behavior
kubectl get pods should return list pf pods

### Actual behavior
Unable to connect to the server: EOF

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Marusyk** [comment]
I have the same issue. How to fix that?
