### ISSUE TITLE
Cannot login to Docker for Windows

### ISSUE THREAD

**Issue by godijoe** [docker/for-win#3199]
I have tried with the latest version of my channel (Stable)
 I have submitted Diagnostics
 I have included the Diagnostics ID in this Issue
Windows Version: Version	10.0.17134 Build 17134
Docker for Windows Version: 18.06.1-ce-win73 (19507)
Expected behavior
Would expect it to log in
Actual behavior
It just puts a red highlight around docker id and password. Tried creating a simple 6 char lowercase password, still does not work 
Information
Diagnostic ID: 6B69F9C5-0FA5-402B-966F-BA5CA14E1573/20190108160620
I can log into cloud.docker.com successfully using the same credentials

**Comment by nwohater** [comment]
I have the same problem.

**Comment by nwohater** [comment]
Uninstalled and re-installed docker desktop and that appears to have fixed it.

**Comment by mcquiggd** [comment]
I had the same issue just now, on Windows 10, latest build.

I installed Kitematic, which prompted me to log in to docker hub. That was successful.

Subsequently, I was also able to log in via the Docker for Windows UI.

I did not reinstall Docker.

**Comment by jtnord** [comment]
Had the same issue after changing my password just now.

can not login from the UI.  using the CLI and running `docker login` succeeded :-/

**Comment by nikfot** [comment]
I had the same issue. I quit Docker Desktop, used docker login and then run docker desktop again.
It worked.

**Comment by dvdobrovolskiy** [comment]
same issue. cannot login. Can login via command line and on web

**Comment by PreetSangha** [comment]
I found @nikfot solution the best. However 

- Changed my password (probably not needed but just to be safe)
- I stopped **and restarted** the docker desktop
- opened an elevated powershell window
- issued docker login and logged in there
- waited a few seconds and noted that docker desktop had signed me in.
