### ISSUE TITLE
Cannot pull any images from the public registry

### ISSUE THREAD

**Issue by AnthonyMastrean** [docker/for-win#3207]
I find myself unable to pull _any_ Docker image from the public registry.

```
PS> docker pull alpine
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

The Docker Desktop application is reporting that it's running and healthy. I have no indication that anything is wrong anywhere. In desperation, I tried to restart the Docker Desktop application. That failed the 1st time 😦 

 * **Diagnostic ID:** 8F2D6FDA-BDFD-45F5-8BCA-859BD1834656\20190110092942

I completely QUIT the application and started it up again and tried pulling and it worked.

But, it's pretty gnarly that something can break so badly on the backend that I can't pull and the Docker Desktop application doesn't know about it. I guess I'm not asking for support on these specific issues but rather requesting better error/status reporting.

**Comment by olihand** [comment]
Same thing here. If I quit the application and start it again it works.
