### ISSUE TITLE
Docker for Windows with Hyper-V: Containers constantly losing networking, restart docker fixes it for a while.

### ISSUE THREAD

**Issue by lsadehaan** [docker/for-win#3209]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E10FB3F3-2080-4980-8444-16041CDCFA4E/20190110201041

### Expected behavior
Networking to work

### Actual behavior
Networking works for a little while, then it stops and I need to restart docker for windows to get it back
### Information

  - Windows Version: Windows 10
  - Docker for Windows Version: Version 2.0.0.0-win78 (28905)

### Steps to reproduce the behavior

  1. Start some docker containers
  2. Use them for a while

I am using a Redis:latest and mariadb:latest container, completely default with only the default port exposed on host.

**Comment by turya** [comment]
I have this same issue, using Version 2.0.0.2 (30215) (and with previous versions).  Using nginx as a reverse proxy to small cluster of containers.  Networking within the containers works fine.  The host intermittently (anywhere from 5 minutes to an hour) stops being able to connect to the containers.  Restarting Docker for Windows fixes it (for a while).

**Comment by mrjoe7** [comment]
This issue went away after I installed https://support.microsoft.com/en-us/help/4476976/windows-10-update-kb4476976 today.

**Comment by mrjoe7** [comment]
> 
> 
> This issue went away after I installed https://support.microsoft.com/en-us/help/4476976/windows-10-update-kb4476976 today.

Spoke too soon. Tried working with docker today and it's not working again. That is weird because after the update I mentionad I worked with docker whole day and had no issues.

**Comment by bogdanb** [comment]
We have the same issue, or at least something similar, with Docker Desktop version 2.0.0.2 (30215).

Our containers are run in pairs, one running various versions of Jira (it uses Tomcat inside) and one running MySQL. Each pair has their own `-d bridge` network. We do all sorts of interactions with the containerized Jira servers to test add-ons, both via browser and via scripts making REST API calls.

Now, the weird thing is that in our case (unlike the comments above suggest) the containers tend to work for very long periods of time without an issue, as long as we only do REST calls or access pages via the browser. However, if we upload a new plugin to server, very often the containers become unresponsive. (I never noticed this happening right after opening or refreshing the page with the upload form. It tends to happen when I use a form on a tab that was loaded a while ago.)

The uploads are normal `Content-Type: multipart/form-data;` as far as I can tell.

When the problem happens, no container can be accessed anymore, not just the one that “triggered” the bug. (E.g., trying to open or reload any page in Chrome leads to a timeout without any response.) Restarting Docker seems to be the only solution; I tried restarting the existing containers, starting new ones, etc., with no success.

**Comment by jefflibby** [comment]
Having the same issue with 2.0.0.3. We had to downgrade our developers back to 18.06.1-ce-win73.

**Comment by jefflibby** [comment]
I see that Edge v 2.0.3.0 includes an update to Docker 18.09.3 which includes the following fix which I hope will resolve this issue:

Networking

    Windows: avoid regeneration of network ids to prevent broken references to networks. docker/engine#149

Will be waiting patiently for the stable release.

**Comment by tigerinus** [comment]
Looks like I am experiencing the same problem here. Ran `rabbitmq` container on my Windows Docker, then lost connection to every port after working for a while (less than 2hrs). Any update?

**Comment by BobDankert** [comment]
I am also experiencing this issue. It started a few days ago out of the blue - not sure what changed when this issue started. I am running version 2.0.0.3 (31259), Build: 8858db3. It's very frustrating. Luckily no one else at my office is having the issue, so it doesn't seem very widespread yet - but it's really quite annoying.

**Comment by sfarkas1988** [comment]
It starts appearing for me too, almost every 20-30min for the latest mariadb container on windows 10

**Comment by chriscupas** [comment]
Running docker machine specific does the trick for me
Check your docker machine IP

`docker-machine ip`

like so, open your browser and point that IP with the specific port you are trying to reach

**Comment by BobDankert** [comment]
I've got another developer in our office experiencing this issue. Anyone find anything that helps with this? I was experiencing it, but then it just completely stopped occurring for me and working normally.

**Comment by BobDankert** [comment]
@jefflibby Where did you find the 18.06.1-ce-win73 version? I can't seem to find past versions of docker desktop anywhere.

**Comment by djs55** [comment]
Thanks for the report. There have been several important bugfixes to the port fowarding recently. If you have time, could you try again with the latest edge version? https://download.docker.com/win/edge/40920/Docker%20Desktop%20Installer.exe
