### ISSUE TITLE
Memory is limited by default to 1GB

### ISSUE THREAD

**Issue by apetres** [docker/for-win#321]
### Expected behavior
When running ``windowsservercore`` without memory limit, the container should have as much memory as the host.
### Actual behavior
The container has its memory **limited to 1GB**.
### Information
```
>docker version
Client:
 Version:      1.13.0-rc3
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        Tue Dec  6 01:15:44 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-rc3
 API version:  1.25 (minimum version 1.24)
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        Tue Dec  6 01:15:44 2016
 OS/Arch:      windows/amd64
 Experimental: false
```
```
>docker info
Server Version: 1.13.0-rc3
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 14393 (14393.447.amd64fre.rs1_release_inmarket.161102-0100)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 11.96 GiB
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

I actually discovered this issue when an application tried to allocate memory and failed.
As a workaround I specified a memory limit > 1GB in ``docker run``.

### Steps to reproduce the behavior

  1.  Verify your physical memory amount by typing ``systeminfo`` in the console. In my case: ``Total Physical Memory:     12,245 MB``
  2.  Run ``windowsservercore`` without memory limit: ``docker run -it microsoft/windowsservercore cmd``
  3.  Run ``systeminfo`` inside the container and observe the line ``Total Physical Memory:     1,023 MB``

**Comment by rneugeba** [comment]
@apetres thanks for the report. Could you open an issue on https://github.com/docker/docker as this is not an issue specific to the Docker for Windows application, but more related to the core docker engine. Thanks

**Comment by apetres** [comment]
@rneugeba I tried to reproduce it on Linux (Debian host, two Debian containers). I checked ``MemTotal`` in the result of ``cat /proc/meminfo``, it was the same for the host and the two containers, meaning that the containers have access to the entire memory. 
It seems that this is a Windows-related issue.

**Comment by rneugeba** [comment]
Yes it's a Windows *container* related issue. Windows containers are setup by the Docker engine as well and the relevant devs hang out on the `docker/docker` github project. This tracker is mostly for the Docker for Windows application which ships with the Docker engine.
