### ISSUE TITLE
Cannot access container over localhost

### ISSUE THREAD

**Issue by Tadimsky** [docker/for-win#3214]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B36E885C-8711-466A-A926-0066327E1900/20190111173134

### Expected behavior

Exposing a container's ports using `-p 3000:443` should allow me to access the container at `localhost:3000`.

### Actual behavior

I get a connection refused when trying to do this. I can access the container if I go in through the container's IP address only.

### Information

  - Windows Version: 18312.1001
  - Docker for Windows Version: 2.0.0.0-win81 (29211)

### Steps to reproduce the behavior
  1. Have a container that listens on port 443/80
  2. Run `docker run -d -p 3000:443 7c20ca56ea4c` to run the container and expose port 443 as port 3000 on the local machine
  3. Try and make a request to `localhost:3000`

This request is failing for me. I cannot access the service this way. But if I get the IP address of the container's nat connection, I can access the service in the container.
The Docker HealthCheck (inside the container) is making requests agains the service as well and those are passing. So it's something in the connection between the host and the container.

**Comment by Sieabah** [comment]
I'm also having the same issue, was avoiding upgrading as it usually results in blue screens or something breaking. The older version was causing me blue screens every 30-40 minutes after starting, now this version prevents me from connecting to the containers.

Looking into the Hyper-V networking it only displays DockerNAT and the Default Switch. Don't know if there is supposed to be a third switch to allow access to the containers or the Default Switch handles that.

**Comment by Tadimsky** [comment]
@Sieabah what version of Windows are you running, for interest?
I’m assuming it’s a regression there because they added support for this last year but now it’s gone.

**Comment by Sieabah** [comment]
@Tadimsky Windows 10 Pro Version 1809 build 17763.253.

**Comment by Sieabah** [comment]
I was however in the insider build not too long ago and it was working, but after exiting insider it has stopped. I kept bluescreening with the insider build and docker. Now I'm on stable and this occurs.

(For clarification)
Other additional steps I've taken is uninstall and install multiple versions of docker both stable and edge and this problem is found on all versions.

I'm at a loss for what I need to do to fix this.

**Comment by mikeparker** [comment]
Using  `docker run -p 80:80 nginx` then hitting `localhost` in a browser seems to work OK for me.

Does this work for you? Which container are you running? Is it only port 443 that's problematic or 80 as well?

**Comment by mrjoe7** [comment]
Same thing is happening to me, but not immediately after container is started but after a few minutes. At first, I can connect to container, everything is working as expected and suddenly it stops working. It happens usually after 2-3 minutes but other times it takes 10 minutes. It's very weird.

**Comment by Sieabah** [comment]
With the update released today(?) it seems to have restored original functionality. I don't immediately have the issue, but I suspect I'll start blue screening soon.

**Comment by mrjoe7** [comment]
Still present in Version 2.0.0.2 (30215) Build: 0b030e1

**Comment by mikeparker** [comment]
@mrjoe7 @Tadimsky can you try:
> Using docker run -p 80:80 nginx then hitting localhost in a browser 
This helps us narrow down the problem area.
Also are you running windows or linux containers?
Also any details of which type of request you are making would be good.

**Comment by mrjoe7** [comment]
@mikeparker: This happens when I run `curl -vv http://localhost:80` AFTER container stops responding
```
tomas@LAPTOP-A0DA8LB3:~$ curl -vv http://localhost:80
* Rebuilt URL to: http://localhost:80/
*   Trying ::1...
* Connected to localhost (::1) port 80 (#0)
> GET / HTTP/1.1
> Host: localhost
> User-Agent: curl/7.47.0
> Accept: */*
>
^C
```

After I restart docker I am getting expected output
```
* Rebuilt URL to: http://localhost:80/
*   Trying ::1...
* Connected to localhost (::1) port 80 (#0)
> GET / HTTP/1.1
> Host: localhost
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx/1.15.8
< Date: Wed, 16 Jan 2019 11:48:33 GMT
< Content-Type: text/html
< Content-Length: 612
< Last-Modified: Tue, 25 Dec 2018 09:56:47 GMT
< Connection: keep-alive
< ETag: "5c21fedf-264"
< Accept-Ranges: bytes
<
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
... rest of output omitted on purpose  ...
```

I am running linux containers. Making only simple http rest requests to my application running in container.
Restarting container does not help, I must restart docker service to make it work again.

**Comment by mikeparker** [comment]
@mrjoe7 great thanks. I still can't repro it though - Can you provide any information on exactly what you did to get the container to stop responding? Did you hit it with high load, or sleep your machine, or leave it running for a long time etc?

**Comment by mrjoe7** [comment]
@mikeparker It usually happens after some time (approx 10 minutes).
Not sure if it necessarily correlates with high load. I will try to start my container and will let it sit quietly for some time to see if it happens again. Will report back after I get some results...

**Comment by mikeparker** [comment]
Thanks. If you can repro with a public container image (e.g. nginx) that would be best so we can rule out anything going wrong inside the container you've built itself.

**Comment by mrjoe7** [comment]
@mikeparker even with my app running without doing networking it's still working after 45 minutes. It seems wou were right that it happens under load.

**Comment by Tadimsky** [comment]
@mikeparker 

> Also are you running windows or linux containers?

I'm running Windows containers on this machine. I can try switching (in order to run `nginx`). I'm going to try `microsoft/dotnet-samples:aspnetapp` as I would think that that image should work.

> Also any details of which type of request you are making would be good.

I was just using `curl` to make the HTTP requests.

Mine doesn't work from the start, not after some amount of time or load.

**Comment by Tadimsky** [comment]
One interesting thing I've noticed is that the IP address the container says it has is different from the IP address docker inspect says it has. Not sure if I'm reading this info wrong though:

In container:
```
C:\app>ipconfig

Windows IP Configuration

Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . : corp.microsoft.com
   Link-local IPv6 Address . . . . . : fe80::187a:74f1:bbad:bcde%4
   IPv4 Address. . . . . . . . . . . : 192.168.204.37
   Subnet Mask . . . . . . . . . . . : 255.255.255.240
   Default Gateway . . . . . . . . . : 172.24.160.1
                                       192.168.204.33
```

In `docker inspect`:
```
 "Networks": {
                "nat": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "aa0ee0c5b606c824b6ba1cd60da31a00bb67d7807cb7c8c23dc65f0c365ce335",
                    "EndpointID": "0ea387f66928bdfd12872a35c8fb0f41a0fc737899443691ee74fd1187c9df81",
                    "Gateway": "172.24.160.1",
                    "IPAddress": "172.24.171.241",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "00:15:5d:2e:7a:9d",
                    "DriverOpts": null
                }
            }
```

**Comment by Universezero** [comment]
/remove-lifecycle stale

I'm currently having this issue trying to run a Kurento media server in Windows docker. No idea why I cannot connect to it.

**Comment by Tadimsky** [comment]
Yeah, I'm still having this issue. What else can we do?

**Comment by tburnett80** [comment]
I am having this issue as well, what I noticed is there is now Adapter for Docker NAT. 

I am able to connect by using <machine name>.<domain name>.com:<docker port>

But not localhost:<docker port> 

Is there some powershell script to recreate the Docker-NAT Adapter?

**Comment by chriscupas** [comment]
Running docker machine specific does the trick for me
Check your docker machine IP

`docker-machine ip`

like so, open your browser and point that IP with the specific port you are trying to reach

**Comment by Sieabah** [comment]
While that does work why is windows the only platform for which localhost is not the way it works? Linux and mac have localhost working

**Comment by chriscupas** [comment]
> While that does work why is windows the only platform for which localhost is not the way it works? Linux and mac have localhost working

I think it is how they handled the loopback.

**Comment by Sieabah** [comment]
@chriscupas I understand how it's an issue but shouldn't there be feature parity between the platforms so it runs _the same_ on each platform? Wasn't that the whole point of docker containers? If I have to develop on windows a specific way to use docker that isn't compatible with mac or linux I'm not quite sure what's the point.

This becomes a bigger issue when you consider web apps that use OAuth locally for development (with a dev key) now everyone has to specify their own docker machine IP on the oauth callback so it doesn't throw a fit.

**Comment by Cyreax** [comment]
This issue is still marked as open, but it's been a while so not sure if it's still relevant. I ran into this same problem today, on Windows 10 pro and the latest docker, when I ran the following:
 
docker run -p 8080:8080 <image> 

I had 8080 exposed in the Dockerfile too, but running this command did not actually expose the port under my localhost. Apparently you have to specify you want the port exposed under localhost. So what fixed it for me is the following:

docker run -p 127.0.0.1:8080:8080 <image>

Hope it helps. Cheers.

**Comment by r0und3r** [comment]
Still not working, even with your workaround @Cyreax Have the same problem under win10 with docker 19.03.5.

**Comment by 174304** [comment]
I am not able to access localhost:3000 after exposing port of container.
I can ping the container from localhost and vice-versa

content of docker file:-
FROM node:alpine

WORKDIR '/app'

COPY package.json .

RUN npm install

COPY . .

CMD ["npm", "run", "start"]


I am able to build successfully and run as well with -p 3000:3000.

Please help

**Comment by neo7337** [comment]
> This issue is still marked as open, but it's been a while so not sure if it's still relevant. I ran into this same problem today, on Windows 10 pro and the latest docker, when I ran the following:
> 
> docker run -p 8080:8080 [image]
> 
> I had 8080 exposed in the Dockerfile too, but running this command did not actually expose the port under my localhost. Apparently you have to specify you want the port exposed under localhost. So what fixed it for me is the following:
> 
> docker run -p 127.0.0.1:8080:8080 [image]
> 
> Hope it helps. Cheers.

it worked for me man, nice

**Comment by abitgen** [comment]
I faced the same issue, the ordering of docker run command matters. 
`docker run -p <host port>:<container port> <image>` **_Works_**
`docker run <image> -p <host port>:<container port> ` **_Doesn't Work_**

Using Windows 10 , Version 2004 (OS build 19041.329)
WSL 2 enabled - https://docs.microsoft.com/en-us/windows/wsl/wsl2-index
Ubuntu 18.04 installed from Microsoft store and its enabled in docker.
![image](https://user-images.githubusercontent.com/10978904/85382604-c0885400-b55c-11ea-9ca5-25aa905c01ea.png)

**Comment by mrjoe7** [comment]
> I faced the same issue, the ordering of docker run command matters.
> `docker run -p <host port>:<container port> <image>` **_Works_**
> `docker run <image> -p <host port>:<container port> ` **_Doesn't Work_**
> 
That si because the command `docker run <image> -p <host port>:<container port>` is, according to https://docs.docker.com/engine/reference/run/, passing arguments to application specified in `ENTRYPOINT`.

**Comment by techwork111** [comment]
Using ssh helped me connect using localhost.

The instructions in this post were what I followed: https://devblogs.microsoft.com/cppblog/build-c-applications-in-a-linux-docker-container-with-visual-studio/
