### ISSUE TITLE
Docker for Windos 10 not starting

### ISSUE THREAD

**Issue by skellytt** [docker/for-win#322]
### Expected behavior
Docker starts normally

### Actual behavior
Docker starts with errors
### Information

  - Diagnostic ID: D178-4074-8035-52587FAF9167/2016-12-15_05-52-44
  - OS Name:                   Microsoft Windows 10 Pro Insider Preview
    OS Version:                10.0.14986 N/A Build 14986

### Steps to reproduce the behavior

  1. Open Docker

**Comment by rneugeba** [comment]
@skellytt thanks for the report. The Diagnostics ID you supplied is not complete. There are bits missing from the start of the UUID. Could you update?
Thanks

**Comment by rneugeba** [comment]
closing due to lack of response. Please re-open when you have an update diagnostics ID.
Thanks
