### ISSUE TITLE
Since 2.0.0.2 Docker UI crash when opening menu from system tray icon

### ISSUE THREAD

**Issue by loganmzz** [docker/for-win#3225]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 5D014971-AC03-43EA-8934-553FB595D0B3/20190115162801

### Expected behavior
Accessing menu from system tray icon

### Actual behavior
Menu appears frozen (unable to click on any item) for short time (500-1500ms) and then Docker crash pop-up appears. And system tray icon disappear.

Docker Engine and Kubernetes are still up and running.

### Information
  - Windows Version: Windows 10 Pro - Version 1803 - OS Version 17134.523
  - Docker for Windows Version: 2.0.0.2
  - Container type: Linux
  - Kubernetes: true

Launching desktop shortcut (Docker for Windows) makes system tray icon reappear but still same behavior.

### Steps to reproduce the behavior
  1. Install Docker for Windows (latest: 2.0.0.2)
  2. Right-click on system tray icon

**Comment by tanvirp** [comment]
Facing the same issue. I have uploaded diagnostics as well.
Diagnostics ID: E229DCA7-B30E-4514-893D-E77D447A898D/20190115094456

- Windows Version: Win 10 Pro for Workstation - 1809
- Docker Desktop: 2.0.0.2
- Container: Linux
- Kubernetes: false

**Comment by brogdonm** [comment]
👍 

I get the same thing everytime I right-click on the docker icon in tray.

- Microsoft Windows 10 Enterprise x64
- Version: 10.0.17134 Build 17134

**Comment by dbstraight** [comment]
Same issue for me on Stable channel. Issue does not occur on Edge channel. Possible workaround for those suffering from this.

**Comment by JVimes** [comment]
Sadly, I spoke too soon. I ended up having to do a full reinstall of Docker Desktop.

Running images was giving me:

> Error response from daemon: hcsshim::ExpandScratchSize failed in Win32: The system cannot find the file specified. (0x2) path=C:\ProgramData\Docker\windowsfilter\\[folder that _does_ exist]"

I tried factory resetting (again), prune system, and recreating images/containers with no luck.

My environment isn't weird. I installed Docker Desktop via Chocolatey package.

**Comment by lovmoen** [comment]
I have the same problem. Stable channel, installed via auto-update installer.

Uploaded diagnostics:
CAF4E2BD-9DAD-4CAD-A2CB-C7DF2C989404/20190118085719

**Comment by magarma** [comment]
Same error here, now the shared drive is not able to mount properly the folders. When I'm creating the container into a folder, It's empty.

**Comment by scripty08** [comment]
same here. it's ridiculous. On every fu***** update of docker desktop you are getting some trouble. why are they releasing unstable versions steadily? can somebody explain it to me?

**Comment by novajohn** [comment]
Getting the same.

**Comment by danpoleary** [comment]
same here.  I guess back to vmware
