### ISSUE TITLE
Docker Service ports documentation

### ISSUE THREAD

**Issue by judavi** [docker/for-win#3227]
- [X] I have tried with the latest version of my channel (Stable or Edge)

### Expected behavior
I have been searching what is the role of the port :53 for the Docker service on Windows but I have not found any documentation of why the service keep that port open or if is possible to be configured or something else. 

The most complete document that I found doesn't mention anything about the port and the service https://docs.microsoft.com/en-us/virtualization/windowscontainers/container-networking/architecture

### Information

  - Is it reproducible? Yes
  - Is the problem new? N/A
  - Did the problem appear with an update? N/A
  - Windows Version: Server 2016
  - Docker for Windows Version: Docker version 18.03.1-ee-2, build ebbcd7e

### Steps to reproduce the behavior
1. Get the docker service PID
2. Execute on Powershell netstat -nao | findstr PID

![image](https://user-images.githubusercontent.com/1766933/51191411-3a360000-18dc-11e9-8ce2-f60c3b98ef18.png)

**Comment by daschott** [comment]
This is for Docker (DNS) name resolution and service discovery. I'm asking Docker if they have any more configuration docs on this, will circle back here.

**Comment by judavi** [comment]
thanks @daschott !
