### ISSUE TITLE
Docker for Windows upgrade hangs

### ISSUE THREAD

**Issue by aarongoldenthal** [docker/for-win#3228]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3943FED3-E8B8-4377-BF17-B5C25621D49D/20190115100301

### Expected behavior
Docker successfully completes upgrade.

### Actual behavior
I received notification of an available upgrade to Docker for Windows 2.0.0.2 (30215).  After starting the install the download completed, was extracted, and began installing.  At that point the installation hung.  After an hour I killed the upgrade process, rebooted, and reinstalled from a fresh installer.  After that docker installed within minutes and everything is working fine.

This same issue occurred on two machines, one configured for Linux containers and one for Windows containers.
- After killing the original install processes both showed Docker not installed and the MobyLinuxVM was removed.
- On the Windows container machine after reboot Docker did not start.
- On the Linux container machine Docker tried to start, but reported an error connecting to the Docker service.  After trying to quit Docker it hung and the process was killed prior to reinstall.

### Information
  - Windows Version: Windows 10 Pro Version 1809
  - Docker for Windows Version: 2.0.0.2 (30215)

**Comment by nicholashead** [comment]
This happens to me literally every time Docker for Windows has an update. It never completes successfully. The install process hangs somewhere, and while I appreciate the "cute" installer UX, it's not helpful in diagnosing what it's actually doing.

Mine is stuck here:

![image](https://user-images.githubusercontent.com/1168659/51193903-cd504500-189e-11e9-813d-6f7e007898a4.png)

So I just have to abort the install, uninstall and clean Docker, then re-install from latest installer binary.

**Comment by aarongoldenthal** [comment]
That's exactly where mine got stuck...

**Comment by gbelot2003** [comment]
I have the same problem!!

**Comment by youfoundkris** [comment]
![image](https://user-images.githubusercontent.com/2652163/51326341-3686b280-1a6f-11e9-882e-a149e11d95a7.png)

**Comment by nicholashead** [comment]
> Disable real time protection and controlled folder access. Then try again.

I don’t run Windows with this turned on at all, for what’s its worth.

**Comment by aarongoldenthal** [comment]
I have Windows Defender disabled.  I do run Bitdefender, but it logs and provides notification for any blocked process, and nothing was identified.

**Comment by micromouse** [comment]
> ![image](https://user-images.githubusercontent.com/2652163/51326341-3686b280-1a6f-11e9-882e-a149e11d95a7.png)
> 
> Disable real time protection and controlled folder access. Then try again.

thanks,i'm ok

**Comment by micromouse** [comment]
> Disable real time protection and controlled folder access. Then try again.
thanks,i'm ok

**Comment by hackdefendr** [comment]
Adding my name to the list. The installer version 2.0.0.2 hangs and never completes.

**Comment by AlexandreBarros** [comment]
I've the same problem, the installation never completes.

**Comment by aarongoldenthal** [comment]
And, of course the same problem happens with 2.0.0.3, this time with all antivirus real-time protection disabled.  Install completed after downloading the latest installer and rebooting with Docker disabled at startup (with antivirus realtime protection enabled, it's not the problem).

On another machine I tried stopping docker first and installing the update from the full installer, but it failed in the same way.

**Comment by dnalneh** [comment]
@aarongoldenthal 
same problem here, my UI is hanging at the following state:
![unbenannt](https://user-images.githubusercontent.com/2178069/52852163-20c0e780-3118-11e9-9a72-5713f5b26fec.PNG)

Any tipps?

**Comment by dnalneh** [comment]
ok, finally I solved it via the suggestion to restart from @langxiong in the issue #1172

**Comment by aarongoldenthal** [comment]
I did find that if I disabled Docker launching at startup and rebooted (to confirm nothing was running, just quitting docker had previously failed), then updated from the latest complete installer that it did complete successfully.

**Comment by kimi-chen** [comment]
One potential cause, make sure you are allowed to create Icon on your desktop. If your system admin disabled your user to create icon on your desktop, your installer will keep hanging like this as well. Give a try, uncheck the create icon option.

**Comment by brammiedema** [comment]
@kimi-chen I was sceptic, but your suggestion worked. I am really amazed by this. thanks for the suggestion. The weird thing is it did work for anaconda install with shortcut icon.

**Comment by kolomenkin** [comment]
I have the same problem with installing Docker Desktop 2.0.0.3

**Comment by FranklinYu** [comment]
This issue can be closed as a duplicate of #1172.

**Comment by diablodale** [comment]
## Repo

1. Have security policies and/or controlled folder denying manipulation of Desktop folder
2. When D4W suddenly with no interaction or user action displays a gigantic upgrade window...accept it

## Result

Upgrade hangs with no error indicated in the D4W upgrade window. Wait an hour...or two hours. Then close the hung installer with the X in the titlebar.

Sideaffect: D4W is now missing from your computer. Neither the upgrade or the previous version are installed.

## Expected

D4W to upgrade. Or timeout. Or display an error. And if the error scenario occurs, to rollback and keep the existing D4W.

![docker 2100 stuck](https://user-images.githubusercontent.com/679350/62262996-f4292f80-b41a-11e9-9ba3-2499bb0c2d8a.png)

**Comment by aarongoldenthal** [comment]
This is still an issue as of 2.1.0.3, and for me in all cases it hangs at "Run Docker Desktop backend service".  For most cases I've been able to successfully workaround by rebooting without closing the hung installer, downloading the full installer and re-running and everything is fine.

**Comment by JustWhit** [comment]
Upgrade Docker hung while removing files. Docker didn't show up under appwiz uninstall, so I manually removed and uninstalled remaining docker files using the script posted [here](https://success.docker.com/article/how-to-completely-remove-docker-in-windows-10)
Attempts to reinstall from scratch are now hanging during the "downloading package" phase. 
![image](https://user-images.githubusercontent.com/23580310/65916125-c7ee4880-e3a2-11e9-92cd-a48659445838.png)

I've restarted multiple times, redownloaded the installer, etc. with no luck. 
This is a managed work laptop, so I am unable to make changes to the security settings. 
I have to run exe's using PowerBroker, and security is handled by McAfee. 
I've installed Docker multiple times in the past with no problem.

**Comment by aarongoldenthal** [comment]
This is still an issue, and the symptoms have not changed.  I have three machines where I maintain Docker for Windows.  One machine has no issues upgrading (Win 10 Enterprise, now 1803, not sure if that's significant).  The other two have this issue (both Win 10 Pro, now 1903), and have for every release since this was written (through 2.1.0.5), and always for me at the same spot in the installation - "Run Docker Desktop backend service".

The workaround for me has also been the same - reboot without closing the hung installer, download the full installer, and re-run and the upgrade is nominal.

/remove-lifecycle stale

**Comment by aarongoldenthal** [comment]
So, with Docker for Windows 2.2.0.0, the installation fails instead of hanging with the following error:
![Docker](https://user-images.githubusercontent.com/6117004/72859219-a6360b80-3c88-11ea-9c3e-a79b1e25bdfd.png)

The resolution for me was still the same - reboot and re-run the installer (I tried re-running immediately after failure and received the same error).

And as before, the machines that have had this problem continue to have the problem, and those that  didn't before still don't.

**Comment by stiv-yakovenko** [comment]
I still have the problem, tried advises above, they don't work.

**Comment by aarongoldenthal** [comment]
This is still a problem with the version 2.3.0.2 installer. 

/remove-lifecycle stale

**Comment by aarongoldenthal** [comment]
This is still a problem with the version 2.5.0.1 installer.

/remove-lifecycle stale

**Comment by aarongoldenthal** [comment]
This is still a problem as of 3.1.0 with the new installer.  I also tried uninstalling and reinstalling with 3.0.0, but no change.

/remove-lifecycle stale

**Comment by aarongoldenthal** [comment]
As of Docker Desktop for Windows 3.5.2, this continues to be an issue with every upgrade and my 3 machines running 3 different Win 10 loads and is resolved the same way - start upgrade, it crashes, reboot machine, download latest installer, re-run and installation completes.  It's really frustrating.

/remove-lifecycle stale

**Comment by aarongoldenthal** [comment]
As of Docker Desktop for Windows 4.2.0, this continues to be an issue with every upgrade and my 3 machines running 3 different Win 10 loads and is resolved the same way - start upgrade, it crashes, reboot machine, download latest installer, re-run and installation completes. It's still really frustrating.

/remove-lifecycle stale

**Comment by aarongoldenthal** [comment]
Unbelievably, still an issue on Docker Desktop for Windows 4.5.1.

/remove-lifecycle stale

**Comment by aarongoldenthal** [comment]
As of 4.12.10 this is still not fixed (same issue and workaround as always).

/lifecycle frozen

**Comment by aarongoldenthal** [comment]
With v4.20.1 (maybe 4.2.0.0, I upgraded from 4.19.0 to 4.20.1), this finally appears to be resolved, 4 years later.
