### ISSUE TITLE
Another app is currently holding the xtables lock

### ISSUE THREAD

**Issue by billhab** [docker/for-win#323]
### Expected behavior
It should work. 

### Actual behavior
Creation of a network bridge fails with 
com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"unable to add inter-network communication rule: Another app is currently holding the xtables lock; waiting (1s) for it to exit...\n (\u003cnil\u003e)"}

### Information

A diagnostic was uploaded with id: A793F06A-2BB2-4848-AECB-269265A747E3/2016-12-15_12-45-54

### Steps to reproduce the behavior

  1. ... Using Java client API. 
  2. ...Create a container
  3.   create a bridge network.

**Comment by rneugeba** [comment]
@billhab thanks for your report. This looks like an issue with the core docker engine running inside the Linux VM in Docker for Windows. Could you file an issue under https://github.com/docker/docker with the information they require (like `docker info`, `docker version` output etc) and also include details about the Java API client and other useful information. It will also help the engine team if you include the docker log file which I extracted from the diagnostics and have attached.

Closing this issue

[docker.log.txt](https://github.com/docker/for-win/files/658157/docker.log.txt)
