### ISSUE TITLE
Having many issues getting Dockers Desktop to start

### ISSUE THREAD

**Issue by johngnazzo** [docker/for-win#3240]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by johngnazzo** [comment]
[log.161.txt](https://github.com/docker/for-win/files/2765114/log.161.txt)
[log.162.txt](https://github.com/docker/for-win/files/2765115/log.162.txt)
[log.163.txt](https://github.com/docker/for-win/files/2765116/log.163.txt)
[log.164.txt](https://github.com/docker/for-win/files/2765117/log.164.txt)
[log.165.txt](https://github.com/docker/for-win/files/2765118/log.165.txt)
[install-log.txt](https://github.com/docker/for-win/files/2765119/install-log.txt)

I had a working implementation of Docker on my Windows 10 Desktop.
When I was asked to upgrade I said yes and it refused to start.
I removed the Docker Desktop application from my Computer using add/remove programs then
Re-installed the version that was originally working.
Same problem.

I have attached the failing log files for your review.  Any help would be appreciated as I am now dead in the water.

Thanks,

**Comment by mat007** [comment]
It seems the bot closed the issue by mistake, sorry about that.
