### ISSUE TITLE
registry-mirrors daemon config not being honored

### ISSUE THREAD

**Issue by coben07** [docker/for-win#325]
### Expected behavior
I expect docker to use the registry specified in the registry-mirrors daemon config when retrieving images with a pull command or build of a Dockerfile.  We're using a nexus registry as a pass-thru cache of dockerhub.

### Actual behavior
Docker ignores the registry mirror config and goes straight to dockerhub registry.  I did confirm that when directly addressing the local registry it works fine (e.g. docker pull devnexus:8883/ubuntu:latest works as expected), but the implicit bahhavior of using the registry mirror does not (e.g. docker pull ubuntu:latest does not use the nexus registry mirror) 

### Information
  - Using a private nexus registry as a pass-thru cache of dockerhub
  - Diagnostic ID 824F8EDE-129F-4291-90FD-0D0394573C05/2016-12-15_14-55-13
  - Docker for Windows Version 1.12.3 (8488)

### Steps to reproduce the behavior

  1. Specify a private registry in the registry-mirrors docker daemon configuration
  2. docker pull hello-world
  3. observe the issue, that the docker daemon still searches and pulls the hello-world image directly from dockerhub instead of the registry-mirror.

You guys and gals rock!  Love docker.  Thanks for considering my issue.

**Comment by dgageot** [comment]
Hi @coben07 could you please try Docker for Windows Beta 33 and tell us if it works better?

**Comment by coben07** [comment]
Tested on Docker for Win Beta 33, same issue.  Adding screenshoot of daemon config screen.

Reproduced on Beta 33 by:  

- set registry-mirrors
- ran docker pull node:6.9.2 expecting docker to pull from aforementioned registry mirror but it pulls from dockerhub instead.

If I fully prefix the registry (pmnexus02d:8883/node:6.9.2) it works fine, but my understanding is that by setting the registry mirror I shouldn't need this prefix.

![registry-mirrors settings](https://cloud.githubusercontent.com/assets/2322279/21330026/2bf662bc-c601-11e6-8ee5-a694a7525ecd.png)

Thanks again for your time.  I'm working around this for now by prefixing the registry to the image name in the Dockerfile.

**Comment by dgageot** [comment]
Thanks @coben07 or the details.

+ Did you configure the registry as a pull though cache? https://docs.docker.com/registry/recipes/mirror/#/running-a-registry-as-a-pull-through-cache
+ @dmp42 any idea?

**Comment by coben07** [comment]
Thanks @dgageot and @dmp42.  I do have the registry configured as a pull through cache. It is a [nexus registry](https://www.sonatype.com/docker) inside our firewall as opposed to the official Registry docker image.   I did test it with a "docker pull pmnexus:8883/node" and confirmed the following behavior:  1st pull the nexus registry passes through to dockerhub to get the oficial node image and saves it to the nexus registry, after deleting the local node image and running the pull a 2nd time it pulls straight from nexus registry.  

And so, with "docker pull pmnexus:8883/node" the nexus pass-thru cache works perfectly.  When setting the registry-mirror in the json config to pmnexus:8883 with "docker pull node", it goes straight to dockerhub every pull (if not cached locally).

I do see all the examples use the "docker --registry-mirror=https://<my-docker-mirror-host> daemon", whereas I'm trying to use the json daemon config file.   I'll see if I can change the windows service to pass the --registry-mirror when starting the daemon to see if it works that way and post the results.

**Comment by coben07** [comment]
Thanks @dgageot and @dmp42 for your time.   Upon further research, I determined that the issue is an [open issue with the Nexus registry](https://issues.sonatype.org/browse/NEXUS-10813).   

To quote a statement from the ticket, "This is not possible at the moment, since the local docker can not be configured to transmit credentials to the configured mirror and Nexus 3 does not allow unauthenticated access."  This is clearly not an issue with docker or docker-for-windows and I'm closing this issue.  I apologize for not determining this sooner and I appreciate your time.

**Comment by peterlynch** [comment]
https://issues.sonatype.org/browse/NEXUS-10813 is fixed in Nexus 3.6.0

However, according to https://docs.docker.com/registry/recipes/mirror/

> It’s currently not possible to mirror another private registry. Only the central Hub can be mirrored.

So is what you are asking for even supported?
