### ISSUE TITLE
kubernetes api becomes unresponsive from windows (still works inside the VM)

### ISSUE THREAD

**Issue by marwatk** [docker/for-win#3257]
We're seeing an issue where the k8s api becomes unavailable after performing some very specific actions. 

We deploy a pod that itself deploys other pods (in our case for integration testing). After a few iterations the k8s api will become unresponsive:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Unable to connect to the server: net/http: TLS handshake timeout
```

Interestingly, if you run it from inside the VM it still works fine so k8s itself isn't the problem:
```

$ docker run --rm --network host lachlanevenson/k8s-kubectl --server=https://localhost:6443/ --insecure-skip-tls-verify=true version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

```

Which led us to perhaps vpnkit being the problem. In the vpnkit logs we see errors like this right when the errors begin:

```
$ docker run -it --rm --privileged --pid=host alpine:edge nsenter -t 1 -m -u -n -i -- tail -3 /var/log/vpnkit-forwarder.log
2019-01-18T17:14:31Z vpnkit-forwarder 2019/01/18 17:14:31 error copying: readfrom tcp 192.168.65.3:50054->192.168.65.3:6443: write tcp 192.168.65.3:50054->192.168.65.3:6443: write: broken pipe
2019-01-18T17:14:31Z vpnkit-forwarder 2019/01/18 17:14:31 error CloseWrite to: close tcp 192.168.65.3:50054->192.168.65.3:6443: shutdown: transport endpoint is not connected
2019-01-18T17:14:31Z vpnkit-forwarder 2019/01/18 17:14:31 Multiplexer main loop failed with Unknown channel id: 2440
```

Sometimes the final line is:
```
2019-01-17T23:38:10Z vpnkit-forwarder 2019/01/17 23:38:10 Multiplexer main loop failed with EOF
```

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BEDB784B-8080-4A8B-8CF1-64F1AB060649/20190118094739
  - Diagnostics ID: 3DEDD9D6-5E87-4BE9-A05C-89744FFEF0E1/20190118101814

### Expected behavior
k8s api remains available

### Actual behavior
k8s api becomes unavailable until docker is restarted

### Information

  - Windows Version: 1709 Build 16299.904 and 1803 Build 17134.523
  - Docker for Windows Version: 2.0.1.0 (30090) and 2.0.0.0-win81 (29211)

### Steps to reproduce the behavior

  We use WSL, so our test case is bash. If you need a Powershell let me know and I can throw something together.

  1. Check out [this demo repository](https://github.com/marwatk/k8s-bug-example)
  2. From WSL run `outer.sh`

  On docker 2.0.1.0 it usually fails in the first 10-20 outer loops. On docker 2.0.0.0-win81 it took over 40 outer loops to eventually fail.

  This example is the simplest case we could come up with to repeat the bug reliably (using a loose definition of reliably).

**Comment by ismail** [comment]
Possible dupe of #3108

**Comment by marwatk** [comment]
We just did some testing and confirmed it is indeed all ports that become unresponsive, so I'd agree. This is a dupe.

**Comment by djs55** [comment]
Although this is a duplicate, I'll reopen it while I investigate the repro steps.

**Comment by djs55** [comment]
The error `Multiplexer main loop failed with Unknown channel id: 2440` means that the `com.docker.vpnkit` process has sent a message (probably a close) for channel `2440` after `vpnkit-forwarder` has deleted the connection state (after both transmitting and receiving a close). I recently fixed some protocol bugs involving double-close but these fixes haven't shipped yet. If I can reproduce the problem I can test whether these fixes fix the problem (or not).

**Comment by tsuna** [comment]
I have this issue with Docker for Mac (edge channel, version 2.0.1.0 (30090)) as well.  The initial symptom was that all the `kubectl` commands time out with `Unable to connect to the server: net/http: TLS handshake timeout` but upon looking closer, I realized that if I step into the LinuxKit VM and then into the docker namespace, I can see the k8s apiserver running and can reach it on port 6443 just fine.  On the macOS host port 6443 was also open by VPNkit but somehow nothing would go through.  After poking around on the host I found the vpnkit log file that ended in:
```
2019-01-24T01:18:16Z vpnkit-forwarder 2019/01/24 01:18:16 error CloseRead from: close tcp 127.0.0.1:58002->127.0.0.1:6443: shutdown: transport endpoint is not connected
2019-01-24T18:46:34Z vpnkit-forwarder 2019/01/24 18:46:34 error CloseRead from: close tcp 127.0.0.1:40016->127.0.0.1:6443: shutdown: transport endpoint is not connected
2019-01-24T18:46:59Z vpnkit-forwarder 2019/01/24 18:46:59 error copying: readfrom tcp 127.0.0.1:40020->127.0.0.1:6443: write tcp 127.0.0.1:40020->127.0.0.1:6443: write: broken pipe
2019-01-24T18:46:59Z vpnkit-forwarder 2019/01/24 18:46:59 error CloseWrite to: close tcp 127.0.0.1:40020->127.0.0.1:6443: shutdown: transport endpoint is not connected
2019-01-24T18:46:59Z vpnkit-forwarder 2019/01/24 18:46:59 error CloseRead from: close tcp 127.0.0.1:40018->127.0.0.1:6443: shutdown: transport endpoint is not connected
2019-01-24T18:48:32Z vpnkit-forwarder 2019/01/24 18:48:32 error CloseRead from: close tcp 127.0.0.1:40550->127.0.0.1:6443: shutdown: transport endpoint is not connected
2019-01-24T18:48:45Z vpnkit-forw[133376.592804] serial8250: too much work for irq4
arder 2019/01/24 18:48:45 error copying: readfrom tcp 127.0.0.1:40554->127.0.0.1:6443: write tcp 127.0.0.1:40554->127.0.0.1:6443: write: broken pipe endpoint is not connected
2019-01-24T18:48:45Z vpnkit-forwarder 2019/01/24 18:48:45 error CloseWrite to: close tcp 127.0.0.1:40554->127.0.0.1:6443: shutdown: transport endpoint is not connected
2019-01-24T18:48:45Z vpnkit-forwarder 2019/01/24 18:48:45 error CloseRead from: close tcp 127.0.0.1:40554->127.0.0.1:6443: shutdown: transport endpoint is not connected
2019-01-24T18:48:45Z vpnkit-forwarder 2019/01/24 18:48:45 Multiplexer main loop failed with EOF
```
The log is generally pretty noisy but it went completely silent after that last EOF error, and the time of the error correlates well with when `kubectl` stopped working.

There was also one hit for the other log line mentioned above, although the time doesn't match as this got logged days before:
```
2019-01-18T21:03:49Z vpnkit-forwarder 2019/01/18 21:03:49 Multiplexer main loop failed with Unknown channel id: 280
```

Not sure whether I should file a separate issue in the `docker/for-mac` project or not?

Also is there a way to recover from this state?  Currently I have to restart D4M completely, which is rather disruptive.  It wasn't clear to me how to restart the forwarder in the LinuxKit VM, but maybe that could help recover?

**Comment by djs55** [comment]
I've fixed a number of bugs with the connection forwarding and now the code seems more stable to me. If you would like to try a pre-release version, the latest development build can be found [here for Windows](https://download-stage.docker.com/win/edge/31088/Docker%20Desktop%20Installer.exe) and [here for Mac](https://download-stage.docker.com/mac/edge/31088/Docker.dmg).

If you get a chance to try it, let me know if this is any better. If you still have problems, please do upload another bug report.

Thanks for your help with this issue!

**Comment by tsuna** [comment]
Thanks! Will try. Is this in v2.0.2.0 on the edge version? If not any idea when it'll hit the edge channel?

Bonus question: any chance of this code ever being open sourced? 😇

**Comment by pmsanford** [comment]
@djs55 I've been running this version for about 5 hours and tentatively it looks to have fixed the issue. 🎉 

I installed the 2.0.0.2 stable release and reproduced the issue within about a half hour to confirm that nothing in my environment had changed. After reproing it I installed the version you linked in your comment and I've been using it since then without problems. Will report back here if I experience any problems.

**Comment by ismail** [comment]
Did an overnight test with suspend etc. too, everything looks good now. Thanks for fixing this bug!

**Comment by djs55** [comment]
@pmsanford @ismail thanks very much for the feedback -- I'm glad that build was better for you.

@tsuna the fix will be in the next edge release but I'm not sure about the date yet -- hopefully not too long. The code for the port forwarding is in fact already open-source in the vpnkit repo: https://github.com/moby/vpnkit -- the client side is in OCaml and the server side is in Go.

**Comment by lucastheisen** [comment]
I got an update yesterday...  Edge version 2.0.2.1 (31274)...  Ran the [demo repository `outer.sh`](https://github.com/marwatk/k8s-bug-example), and it still failed after 3 iterations:
```
...
Outer loop: 2
Waiting for namespace to delete (1)
Waiting for namespace to delete (2)
Waiting for namespace to delete (3)
Waiting for namespace to delete (4)
namespace "k8s-bug-outer" created
If you don't see a command prompt, try pressing enter.
namespace/k8s-bug-inner created
deployment.apps/nginx-deployment created
[1] pod foo-deployment: Phase is [Pending]
[2] pod foo-deployment: Phase is [Pending]
[3] pod foo-deployment: Phase is [Running]
Deleting namespace
Loop count: 2
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Inner test finished
Outer loop: 3
Unable to connect to the server: net/http: TLS handshake timeout
```
Perhaps it still hasn't reached the edge release...

**Comment by djs55** [comment]
@lucastheisen yes, unfortunately the edge release was a small delta on top of the previous edge release -- it only contains the new `runc` with the security fix. The next edge should contain the fix.

**Comment by srinivasankavitha** [comment]
When can we expect the next release containing fixes for the bugs related to connection forwarding?

**Comment by dmuth** [comment]
Hey everyone, I'm not sure if this is related, but I Googled for `docker "Multiplexer main loop failed"`, because it's exactly the behavior that I am seeing (and able to reproduce reliably) on my Mac copy of Docker: https://github.com/docker/for-mac/issues/3674

Anyway, just throwing that out, since it seems like it might be important.
