### ISSUE TITLE
Docker Volume: Credentials needs to be reset after machine restart

### ISSUE THREAD

**Issue by linuxchata** [docker/for-win#3268]
Applied credentials for Shared Drives, needs to be set after machine restart.

Docker CE 18.06.1-ce-win-73 (19507) (stable)
Host OS: Windows 10 Pro x64

After reboot, there is an error in Docker daemon logs (found under C:\Users\USER_NAME\AppData\Local\Docker\) "Unable to mount C drive: firewall is blocking" and drive share is getting removed. The issue https://github.com/docker/for-win/issues/662 does not provide any solution.

Taken steps:
- Reinstall Docker including removing Containers and Hyper-V features and allow Docker to install them (https://github.com/Microsoft/hcsshim/issues/152#issuecomment-405860591).
- Install Docker version 2.0.0.0-win81 (29211), docker engine version is 18.09.0, stable.
- Install Docker version 2.0.0.0-win82 (29268), docker engine version is 18.09.0, edge.
- Used local user for share drive as per http://peterjohnlightfoot.com/docker-for-windows-on-hyper-v-fix-the-host-volume-sharing-issue/.
- Checking and applying steps as per https://success.docker.com/article/error-a-firewall-is-blocking-file-sharing-between-windows-and-the-containers.
- https://github.com/docker/for-win/issues/385#issuecomment-360701432 (command `netsh interface tcp show global` does not show interface with name "NetDMA")
- Applying command `Set-NetConnectionProfile -interfacealias "vEthernet (DockerNAT)" -NetworkCategory Private` as per https://github.com/docker/for-win/issues/738#issuecomment-304505592

_Originally posted by @linuxchata in https://github.com/docker/for-win/issues/385#issuecomment-448644683_

**Comment by tabareh** [comment]
This issue is extremely annoying and it takes lots of time from developers to get the containers spinning again. I'm thinking to go back to local installation of my services again.

Could you please prioritize this?

**Comment by mdzzohrabi** [comment]
I have same issue

**Comment by Laro88** [comment]
Come on Docker, my entire team is having a hard time with the requirements of "right click stupid whatr and Reset" and then reset credentials afterwards. How hard can it be for you to fix this?

**Comment by guixermo** [comment]
I'm having the same issue.
I'm working on a ubuntu VM with windous Host os.
After shuting down the vm, the problem appeared.
Anyone knows how to reset credentials from docker in ubuntu?

**Comment by linuxchata** [comment]
This issue seems to be fixed in newer versions of Docker
