### ISSUE TITLE
Unable to share 'D' drive

### ISSUE THREAD

**Issue by Jason0307** [docker/for-win#327]
Expected behavior

Would be able to Share D Drive using Settings > Share Drive

Actual behavior

UI asks for Credentials, enter the credentials but not share the driver.

Information

Diagnostic ID = 7DEAE932-325F-4B0F-9C2A-6D3A2DA3075A/2016-12-17_01-22-08
Windows 10, Docker Version 1.12.3(8488)

**Comment by dgageot** [comment]
Hi @Jason0307 could you please try [Docker for Windows Beta 33](https://docs.docker.com/docker-for-windows/) and tell us if it works better?

**Comment by Jason0307** [comment]
@dgageot I will have a try and then give your feedback as soon as possible.

**Comment by Frankwin** [comment]
I tried the beta, but no dice

**Comment by friism** [comment]
@Frankwin could you please create a diagnostic dump?

**Comment by storytime** [comment]
Hi

OS: Win 10
Docker: Version 17.03.0-ce-win1 (10296) Channel: stable e5a07a1
Diagnostic id: 79857338-0C06-4C76-9467-5E8EFC90D018/2017-03-23_14-51-30

Cannot create shared drive.
Run docker as admin
Then try to share drive, then type domain password and then nothing happens.

Logs: 
```
[14:32:11.535][SambaShare     ][Info   ] "E" is not shared
[14:32:11.535][SambaShare     ][Info   ] Creating share "E:\" as "E" with Full Control to "ORG\userName"
[14:32:11.558][Cmd            ][Info   ] System error 5 has occurred.
[14:32:11.559][Cmd            ][Info   ] 
[14:32:11.559][Cmd            ][Info   ] Access is denied.
[14:32:11.559][Cmd            ][Info   ] 
```

**Comment by jasonbivins** [comment]
@storytime @Frankwin 
Checking in- do you still see this in the newest version?
