### ISSUE TITLE
IPC between windows host and windows container

### ISSUE THREAD

**Issue by sgbihu** [docker/for-win#3276]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
The IPC test program can communicate between container and host

### Actual behavior
Test IPC(namedpipe) can't open the named pipe.

### Information

  - Windows Version: Windows 10 1803 build 17134.472
  - Docker for Windows Version:2.0.0.0-win81 (29211

### Steps to reproduce the behavior

  1. docker run --ipc=host -ti --entrypoint=powershell  test/hddl powershell
  2. docker run --ipc=host  -v \\.\pipe\mynamedpipe:\\.\pipe\mynamedpipe -ti --entrypoint=powershell  test/hddl powershell

both of them are failed the namedpipe ipc test. And I also want to share the memory between the host and container, can anyone help give the parameters?

**Comment by hsraju** [comment]
Any updates on this issue?
