### ISSUE TITLE
docker run hello-world is failing

### ISSUE THREAD

**Issue by swapnilarora** [docker/for-win#3282]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
Hi All,
I am facing an issue with my docker, it was working fine earlier until i installed minikube in my machine. I was running [docker run hello-world]
### Expected behavior
It should work
### Actual behavior
giving me error 
[docker: Error response from daemon: container 99db7959683fd1eea341ce8a5052071153182844ad8a04bacf206931a946240d encountered an error during Start: failure in a Windows system call: The driver was not loaded because it failed its initialization call. (0x287)
[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]
[Event Detail: onecore\vm\compute\management\shared\container\containerutilities.cpp(536)\vmcomputeagent.exe!00007FF7DC74EE4D: (caller: 00007FF7DC71D819) Exception(299) tid(36c) 80070287 The driver was not loaded because it failed its initialization call.
    CallContext:[\Bridge_ProcessMessage\ComputeSystemManager_Start\VmHostedContainer_Start]
 Provider: 00000000-0000-0000-0000-000000000000].]
### Information
[docker version:
Client: Docker Engine - Community
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:34:26 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:50:10 2019
  OS/Arch:          windows/amd64
  Experimental:     false]

[docker info
Containers: 18
 Running: 0
 Paused: 0
 Stopped: 18
Images: 30
Server Version: 18.09.1
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: <some value>
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows 10 Pro Version 1803 (OS Build 17134.556)
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 11.89GiB
Name: <some-value>
ID: <some-value>
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 26
 System Time: 2019-01-24T15:28:09.6523338+05:30
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 k8s.gcr.io
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine]

  - Windows Version: Windows 10 Pro
  - Docker for Windows Version:2.0.0.2(30215)

### Steps to reproduce the behavior
PS docker run hello-world

**Comment by viniciusxyz** [comment]
I Have a same problem here, i´m use Windows Hyper V 2019 1809,

 - Docker Version
Client:
 Version: 18.09.1
 API version: 1.39
 Go version: go1.10.6
 Git commit: 20b67756d0
 Built: unknown-buildtime
 OS / Arch: windows / amd64
 Experimental: false

Server:
 Engine:
  Version: 18.09.1
  API version: 1.39 (minimum version 1.24)
  Go version: go1.10.6
  Git commit: 20b67756d0
  Built: 09/01/2019 17:09:57
  OS / Arch: windows / amd64
  Experimental: false

 - Docker Info
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 3
Server Version: 18.09.1
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
Operating System: Hyper-V Server 2019 Version 1809 (OS Build 17763.1)
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 4GiB
Name: WIN-908B729AIV4
ID: WVTS: DEHC: UP7O: TXED: KBTO: Q52P: MEBL: 6IB2: 2RNV: 472G: 7H76: XV6P
Docker Root Dir: C: \ ProgramData \ docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

## How to reproduce problem:

### Install docker
 - Install Docker:
 - Install-Module DockerMsftProvider -Force
 - Install-Package Docker -ProviderName DockerMsftProvider -Force

### Install the required Features
 - Enable features required (HNS Service)
 - Enable-WindowsOptionalFeature -Online -FeatureName HypervisorPlatform
 - Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform
### Will reboot
 - Set-Service -Name hns -StartupType Automatic
 - Set-Service -Name docker -StartupType Automatic
 - cmd / c "sc config docker depend = hns"
 - Start-Service docker

### Try to run any container:
 - docker run -ti mcr.microsoft.com/windows/servercore powershell

**Comment by swapnilarora** [comment]
I re-installed docker for windows. and it worked, i don't know why it happened, what is RCA but it has worked after re-installed. Try your luck. Get back if you still face it.
