### ISSUE TITLE
Docker api no longer listening on tcp

### ISSUE THREAD

**Issue by altwohill** [docker/for-win#3286]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:56A0E553-B151-40AB-BBF2-2AAE9E21058A/20190126074457

### Expected behavior
Docker should be listening on tcp://localhost:2375
### Actual behavior
Nothing is listening on tcp://localhost:2375
### Information

Version: 2.0.0.2 (30215)
OS: Windows 10 Pro
Edition: Professional
Id: 1809
Build: 17763

Since updating to the latest version of Docker, it no longer listens on TCP port 2375.
The appropriate settings is checked
![image](https://user-images.githubusercontent.com/629254/51766556-ba136400-213f-11e9-8330-c081274ec1b3.png)

However nothing is listening on port 2375
![image](https://user-images.githubusercontent.com/629254/51766608-dca57d00-213f-11e9-9887-18566a792be3.png)

I've tried reinstalling to no avail. Can't see anything obvious in the logs. Any other places I can look for what might be the issue?

**Comment by enzanki-ars** [comment]
I am experiencing the same issue to.  But the "expose daemon without TLS" is set, but the it is not listening on that port and tools like PyCharm are unable to access it.

**Comment by pgayvallet** [comment]
Hello,

I'm not able to reproduce the issue on 2.0.0.2 nor on master.

```
 docker --host=tcp://localhost:2375 run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

[...]
```

Do you per any chance have a firewall or a security software that could actually block the app from opening the port ?

**Comment by enzanki-ars** [comment]
I just tested it on the Edge track too and still have the same error.  Additionally, I turned of Windows Firewall for a sanity check and still no luck.

**Comment by elijahgagne** [comment]
I'm seeing this as well on both the stable and edge tracks. Is there a way to revert back to an early version?

**Comment by elijahgagne** [comment]
I went back to stable version 2.0.0.0-win81 (29211). I downloaded it from https://docs.docker.com/docker-for-windows/release-notes/ and did an uninstall, fresh install. Unfortunately, no change of behavior.

**Comment by elijahgagne** [comment]
For some reason, it's working on 2.0.0.0-win81 (29211) again for me. Perhaps a reboot did it.

**Comment by wleev** [comment]
Also experiencing this, occurred after Docker update. Neither stable ( 2.0.0.2 ) nor edge ( 2.0.2.0 ) is working. Also tried downgrading, as was mentioned before. No luck there either.

Windows version: 10.0.17763 Build 17763

**Comment by kziemski** [comment]
Hello all, this looks like its broken for me as well. 
windows 10 latest/greatest no blocked ports both with/without antivirus firewall no effect.

is there a place where we could find a log error on docker desktop for windows for this port ?
 
in the meantime to anyone who's affected by this.
someone suggested running this below and using 23750 as docker_host port. 
workaround but obviously not ideal.

docker run -d --restart=always -p 127.0.0.1:23750:2375 -v /var/run/docker.sock:/var/run/docker.sock  alpine/socat  tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock

**Comment by rbairwell** [comment]
Docker Desktop Community is still broken on 2.0.3.0 (31778) edge on Windows 10 in this way. @kziemski 's suggestion does work.
