### ISSUE TITLE
Cannot use relative path in docker compose file

### ISSUE THREAD

**Issue by Stijn98s** [docker/for-win#3289]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 735FA516-6F13-4EA4-AB43-F3D5664CA269/20190126180839

### Expected behavior
Using relative paths in docker-compose file

### Actual behavior
Cannot deploy stack with docker
```
Stack.compose.docker.com "app" is invalid: app: Invalid value: "null": conversion to kube entities failed: D:\Websites\App: only absolute paths can be specified in mount source
```

### Information
  - Windows Version: Windows 10 Student (1809)
  - Docker for Windows Version: 18.09.1, build 4c52b90

### Steps to reproduce the behavior

docker-compose.yml (from https://docs.docker.com/docker-for-windows/kubernetes/)
```version: '3.3'

services:
  web:
    build: web
    image: dockerdemos/lab-web
    volumes:
     - "./web/static:/static"
    ports:
     - "80:80"

  words:
    build: words
    image: dockerdemos/lab-words
    deploy:
      replicas: 5
      endpoint_mode: dnsrr
      resources:
        limits:
          memory: 16M
        reservations:
          memory: 16M

  db:
    build: db
    image: dockerdemos/lab-db
```

  1. enable kubernetes
  2. enable deploy stacks default to kubernetes
  3. `docker stack deploy --compose-file docker-compose.yml app`

**Comment by Stijn98s** [comment]
Fixing in docker/cli#966

**Comment by lk77** [comment]
Hello,

i have the same issue,
relative path does not work anymore.
