### ISSUE TITLE
Error starting docker

### ISSUE THREAD

**Issue by felipebits** [docker/for-win#3291]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6B3642EE-064B-4321-BA6F-0715C4EA8DDE/20190126212342

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. Install Docker for Windows
  2. When prompted, let it add the Hyper-V components and restart.
  3. Launch Docker for Windows
  4. Wait for error.

Unable to create: O comando em execução parou porque a variável preferencial "ErrorActionPreference" ou o parâmetro comum está definido como Stop: Falha genérica 
em New-Switch, <Nenhum arquivo>: linha 121
em <ScriptBlock>, <Nenhum arquivo>: linha 411
   em Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) na C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:linha 36
   em Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) na C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:linha 92
   em Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() na C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:linha 74
   em Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() na C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:linha 59

**Comment by ckmbks** [comment]
这个问题也困扰了我好久，最后我尝试修改计算机名，把原本带中文的计算机名改成了全英文，重启系统后启动正常。这个我猜测就是因为中文计算机名导致powershell脚本执行失败。

Google Transfer:
This problem has also plagued me for a long time. Finally, I tried to change the computer name, changed the original computer name with Chinese to English, and restarted the system to start normal. I guess this is because the powershell script failed due to the Chinese computer name.

**Comment by mikeparker** [comment]
@felipebits can you confirm if you also have extended characters in your computer name?
