### ISSUE TITLE
Failed to create VM MobyLinuxVM on Win 10 - invalid amount of arguments

### ISSUE THREAD

**Issue by derfalx** [docker/for-win#33]
### Expected behavior
Docker should start

### Actual behavior
Docker does not start 

### Information

Diagnostic ID: E0BC3065-6B9C-4BB1-83EF-966436C17D7A/2016-08-10_10-46-01

I'm getting this error, after starting my computer this morning. 
OS: Latest Win 10 Pro Version (Version: 1607 Build: 1493.10)
Architecture: x64

The following Stacktrace is shown to me:
```
Failed to create VM "MobyLinuxVM": Für "min" und die folgende Argumenteanzahl kann keine Überladung gefunden werden: "2".
   bei Docker.Core.Pipe.NamedPipeClient.TrySend(String action, Object[] parameters)
   bei Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   bei Docker.Core.Backend.BackendClient.Start(Settings settings)
   bei Docker.Actions.DoStart(Settings settings, Boolean showWelcomeWindow)
   bei Docker.Core.TaskQueue.<.ctor>b__16_0()
```

Logfile: [log-2016-08-10_10-14-06.txt](https://github.com/docker/toolbox/files/410582/log-2016-08-10_10-14-06.txt)

It seems like some arguments to start the MobyLinuxVM are parsed or passed in a wrong way.
Restarting multiple times did not solve the problem.

I am not sure if this problem is also part of:

- [Kitematic setup error: connect ENOENT //./pipe/docker_engine](https://github.com/docker/toolbox/issues/548) - if I try to start Kitematic the `Error: connect ENOENT //./pipe/docker_engine` appear, but this should be a symptom and not the cause.
- [Docker fails to start on Windows 10](https://github.com/docker/for-win/issues/27) - seems to be similar but I get a different error within log files. If it's needed this issue can be merged.

[log-2016-08-10_10-14-06.txt](https://github.com/docker/for-win/files/410624/log-2016-08-10_10-14-06.txt)

**Comment by rneugeba** [comment]
Thank you for your report. I don't think we have seen this error before and it's kinda weird. Could you try executing this commands on an elevated powershell:
```
$CPUs = 2
[Math]::min((Get-VMHost).LogicalProcessorCount, $CPUs)
```
Thanks

**Comment by derfalx** [comment]
It returns `2`. 

I took a look into Hyper-V-Manager, it shows two virtual computer. Both are MobyLinuxVM with configurationversion 8.0 and 2048MB starting storage. Is it normal to have two virtual computer?

**Comment by rneugeba** [comment]
Ah, two VMs. That's no good. Someone else has reported this as well, but we have no idea how this happens (windows is sometimes weird like this). In the upcoming Beta22 we guard against this, but for now can you please exit the app, delete both of them in Hyper-V Manager or via powershell, and try starting the app again?
Thanks

**Comment by derfalx** [comment]
Deleting both virtual computer helped! Now Docker is working again. 
Thank you for your help!

**Comment by rneugeba** [comment]
@derfalx thanks for reporting back and glad it is working for you now. Closing this issue
