### ISSUE TITLE
/etc/resolv.conf in Moby VM populated with "domain" and "search", mutually exclusive.

### ISSUE THREAD

**Issue by sylvainbecu** [docker/for-win#3304]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
/etc/resolv.conf should contain "domain" OR "search". as described [here](http://man7.org/linux/man-pages/man5/resolv.conf.5.html):

> The domain and search keywords are mutually exclusive.  If more than
> one instance of these keywords is present, the last instance wins.

### Actual behavior
On my Docker Desktop config, values taken on my windows host network card are well inserted on "search" AND "domain" lines on resolv.conf on Moby VM.

Resolution of FQDN works well from VM and container.

With actual order of lines ( nameserver, search, domain ), the content of "search" line is ignored by VM resolver as it's overwritten by "domain" line content as described on resolv.conf man page.

### Information

  - Windows Version: 10
  - Docker for Windows Version: Version 2.0.0.2 (30215) / Channel: stable / Build: 0b030e1

### Steps to reproduce the behavior
  1. put a domain in "Connexion DNS suffix" of your internet connexion ( on Windows, domain have to exist )
  2. put other domains on "search domains" of your internet connexion ( on Windows, domains have to exist )
  3. Start a linux container
  4. observe line order and completion of /etc/resolv.conf ( nameserver/search/domain )
  5. try to resolve a FQDN > works
  6. try to resolve a \<short name\>, which exists in DNS under \<the domain on "domain"line\> > works
  7. try to resolve a \<short name\>, which exists in DNS under \<a domain on "search" line\> > KO

/etc/resolv.conf should only contain "nameserver" and "search" lines.

search line should contain concatenation of "Connexion DNS suffix" and "search domains" inherited from Windows host network card setting.

**Comment by djs55** [comment]
Thanks for the very clear bug report. I'll escalate this internally to our networking team.

**Comment by djs55** [comment]
@sylvainbecu the DNS behaviour is different on edge. We now forward all queries directly to the Windows DNS resolver which applies the search policy, rather than trying to replicate the Windows policy in Linux. Could you try installing edge and seeing if that works any better for you?

**Comment by sylvainbecu** [comment]
Hello

Thanks for the very prompt answer.

I install edge version ( Version 2.0.1.0 (30090) / Channel: edge / Build: c8b6ca6 ).

the resolv.conf contains only a "search" line as expected.

I made the same "nslookup shortname" on the container and the windows host.

"shortname" is neither in hosts file in VM or host.

_ Does not work in container " server san't find shortname: NXDOMAIN"
_ works in windows host.

FQDN resolving works fine in container. only short names to be completed with "search" suffix from host config does not work.

works if adding a "search" line in container resolv.conf.

**Comment by djs55** [comment]
Could you try with latest edge? I recently merged a fix to remove the mutually-exclusive entries from `/etc/resolv.conf` and to rely completely on the Windows system resolver.

**Comment by djahne** [comment]
@djs55 can you link the merged issue you mentioned in your comment from June 13 above? 

I have a feeling it caused a regression: https://github.com/docker/for-win/issues/4573
