### ISSUE TITLE
docker does not configure DNS correctly using mcr.microsoft.com/windows/servercore

### ISSUE THREAD

**Issue by blushingpenguin** [docker/for-win#3306]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 8CB4A6FE-2A50-4417-A611-9CF383540F0D/20190129160933

### Expected behavior
docker configures DNS to 8.8.8.8 (or other working address)

### Actual behavior
docker configures DNS to 192.168.0.1, which does not exist

### Information

  - Windows Version: mcr.microsoft.com/windows/servercore
  - Docker for Windows Version: Version 2.0.0.2 (30215)

### Steps to reproduce the behavior

1. docker pull mcr.microsoft.com/windows/servercore
2. docker run -it mcr.microsoft.com/windows/servercore
3. powershell
4. Get-DnsClientServerAddresses
{"log":"Ethernet 2                           5 IPv4    {172.20.176.1, 192.168.0.1}

I'm not sure where 192.168.0.1 comes from here.
(as below

	Get-DnsClientServerAddress\u001b[22;37;40m\u001b[K\u001b[51H\u001b[K\u001b[51;35H\u001b[51;1H\r\n","stream":"stdout","time":"2019-01-29T15:33:54.9709042Z"}
{"log":"InterfaceAlias               Interface Address ServerAddresses                                                                   \r\n","stream":"stdout","time":"2019-01-29T15:33:54.993905Z"}
{"log":"                             Index     Family                                                                                    \r\n","stream":"stdout","time":"2019-01-29T15:33:54.993905Z"}
{"log":"--------------               --------- ------- ---------------                                                                   \r\n","stream":"stdout","time":"2019-01-29T15:33:54.9969057Z"}
{"log":"Ethernet 2                           5 IPv4    {172.20.176.1, 192.168.0.1}                                                       \r\n","stream":"stdout","time":"2019-01-29T15:33:54.9989084Z"}
{"log":"Ethernet 2                           5 IPv6    {}                                                                                \r\n","stream":"stdout","time":"2019-01-29T15:33:55.0029058Z"}
{"log":"Loopback Pseudo-Interface 2          4 IPv4    {}                                                                                \r\n","stream":"stdout","time":"2019-01-29T15:33:55.0049048Z"}
{"log":"Loopback Pseudo-Interface 2          4 IPv6    {}                                                                                \r\n","stream":"stdout","time":"2019-01-29T15:33:55.0069034Z"}
)

This is my first outing as docker so apologies if I did something wrong.  I worked around this just by setting dns: [ "8.8.8.8" ] in the configuration

**Comment by richardgavel** [comment]
You're running Docker for windows, which means your network is using NAT networking. Relative to the container, the 192.168.0.1 is going to represent the Docker host. Your DNS calls would then just go thru your host. You actually don't necessarily want to change the primary DNS since, for example, you have a Docker compose file defining aliases for a Docker container. Going directly to 8.8.8.8 would prevent this from resolving.
