### ISSUE TITLE
Add support for physical hard disks

### ISSUE THREAD

**Issue by tamasd** [docker/for-win#3307]
While this is something that HyperV supports, if I set it on the VM itself, Docker breaks basically. I had to delete the VM and let docker create a new one.

I have an "unused" SSD in my computer, and I would like to pass it through directly to the VM to increase IO performance.

**Comment by pgayvallet** [comment]
Hello,

This is the first time I see this request. Could you point to any documentation benchmarking the perf difference between using directly an SSD as VM disk and using a vhdx file on a actual SSD ?

**Comment by damianh** [comment]
Came here to ask for the same feature. 

I know the primary argument against pass-through/physical disks is [portability](https://docs.microsoft.com/en-us/windows-server/administration/performance-tuning/role/hyper-v-server/storage-io-performance#pass-through-disks) but I'd argue that in this case people generally are not moving around their DockerDesktopVMs but rebuilding them instead. So searching around for perf benchmarks:

From https://www.teknophiles.com/2016/10/10/pass-through-disks-vs-vhdx-and-the-vhdxtool/:

> Performance is really the only reason you’ll hear for using pass-through disks.  And while performance is a great reason to select a particular configuration, many experts would argue that the advantage of pass-through disks over VHDs even in older versions of Hyper-V (2008 and 2008R2) was small.  Typically, numbers such as 15%-20% are thrown around.  With the improvements in Hyper-V 2012 and 2012R2 and the VHDX format, this advantage shrinks.  Use fixed rather than dynamic VHDXs, and the advantage shrinks further, to “virtually” nothing (pun intended).

From https://social.technet.microsoft.com/forums/windowsserver/en-US/7db96291-bd07-485a-936a-837f5bce529a/windows-server-2012-hyperv-vhd-or-passthrough-disk

> As Jens says, there is a slight performance difference between pass-through and virtual hard drives.  But most people will never experience it.  The difference is only really noticeable (with instrumentation to measure) when doing massive amounts of IO where you are attempting to push the limits of the physical environment.

So it looks like there isn't much of a performance difference.

Anyay, I'm going to see if putting the vhdx on a ramdrive make any difference 😬
