### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by luisaddor** [docker/for-win#3308]
@

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by pgayvallet** [comment]
Hello,

Closing. Please reopen with proper description and diagnostic if necessary.
