### ISSUE TITLE
Docker commands are awfully slow in Win 10 Docker for windows, cannot switch to Windows Containers

### ISSUE THREAD

**Issue by chetanku** [docker/for-win#3309]
- [X ] I have tried with the latest version of my channel (Stable or Edge) --Stable
  - [ X] I have uploaded Diagnostics

  - Diagnostics ID: 40E293D8-AC8F-45B9-937F-0F7264117CD1/20190129235154

### Expected behavior

to get docker -v within milliseconds

### Actual behavior

it takes ~100 seconds for the response

Also, I am not able to switch to windows containers : **Cannot start service docker on computer '.'.**

![image](https://user-images.githubusercontent.com/10711779/51959366-f71e7580-2421-11e9-8ba5-30d368eefa48.png)

### Information

  - Windows Version: Windows 10 Enterprise
  - Docker for Windows Version: ~18.09

### Steps to reproduce the behavior

  1. ... Install Docker for Windows in Win 10 Enterprise with hyperv
  2. ... Run docker -v

**Comment by chetanku** [comment]
After hours of troubleshooting, The issue was my office's security policies. we added docker and hyper-v to exclusion policies and docker is working like a charm.

**Comment by tamim2996** [comment]
@chetanku how to do that...Docker in my PC is extremely slow

**Comment by Mohammed-ElSayed** [comment]
> After hours of troubleshooting, The issue was my office's security policies. we added docker and hyper-v to exclusion policies and docker is working like a charm.

Could you tell what did you do in order to get this issue fixed (more details)?

**Comment by chetanku** [comment]
Hey guys, this solution will only work if your company or office has some restrictions on running third-party software. My company uses security enforcement software to restrict third-party software to run effectively. I worked with my company's help desk team to exclude docker and hyper-v from the security policies. hope this helps
