### ISSUE TITLE
Can't create virtual drive

### ISSUE THREAD

**Issue by AKCELEPATOP** [docker/for-win#3310]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 0E531811-455F-4030-8EB3-25E82FFE0C6C/20190130092354

### Information

  - Windows Version: Windows 10 Pro
  - Docker for Windows Version: latest

### Steps to reproduce the behavior

  1. Run docker

**Comment by pgayvallet** [comment]
Hello,

Could you actually describe the issue you are encountering ?
