### ISSUE TITLE
mobylinuxvm

### ISSUE THREAD

**Issue by Subashcogn** [docker/for-win#3311]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Subashcogn** [comment]
getting Mobylinuxvm error.unable to work.

**Comment by pgayvallet** [comment]
Hello

Closing. Please reopen with proper description and diagnostic if necessary.
