### ISSUE TITLE
Missing several folders and ca.pem

### ISSUE THREAD

**Issue by MiddleTv** [docker/for-win#3314]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Functional use of Docker and Docker Compose
### Actual behavior
When "docker" is used I get thrown this error -
could not read CA certificate "C:\\Users\\lumia\\.docker\\machine\\machines\\default\\ca.pem": open C:\Users\lumia\.docker\machine\machines\default\ca.pem: The system cannot find the path specified.
When "docker-compose" is used I get thrown this error -
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 124, in perform_command
  File "compose\cli\command.py", line 39, in project_from_options
  File "compose\cli\docker_client.py", line 84, in tls_config_from_options
  File "site-packages\docker\tls.py", line 81, in __init__
docker.errors.TLSParameterError: Path to a certificate and key files must be provided through the client_config param. TLS configurations should map the Docker CLI client configurations. See https://docs.docker.com/engine/articles/https/ for API details.
[9472] Failed to execute script docker-compose

### Information

  - Windows Version: Windows 10 Pro
  - Docker for Windows Version: Docker version 18.09.1, build 4c52b90

### Steps to reproduce the behavior

  1. Used Docker for Windows installer
  2. proceeded to follow instructions
  3. launched Docker Desktop
  4. tried using cmd and errors thrown

**Comment by MiddleTv** [comment]
Also forgot to mention, had Windows 10 Home and used Docker Toolkit. Then upgraded to Windows 10 Pro with Toolkit still installed. Then installed Docker Desktop whilst Toolkit was still installed, then proceeded to unistall Toolkit.

**Comment by ebriney** [comment]
@MiddleTv  I think you still have envs from docker-machine, remove all `DOCKER_*` envs and retry.
Docker Desktop doesn't need any certificates nor envs.

**Comment by MiddleTv** [comment]
Hey I'm sorry but I have no idea how to do it, would you be able to explain what I have to do? Thank you!

    On Wednesday, 30 January 2019, 16:48:05 CET, Emmanuel Briney <notifications@github.com> wrote:  
 
 
@MiddleTv I think you still have envs from docker-machine, remove all DOCKER_* envs and retry.
Docker Desktop doesn't need any certificates nor envs.
