### ISSUE TITLE
Volumes not working as expected in WSL on Windows 10 (VMware setup)

### ISSUE THREAD

**Issue by ishraqiyun77** [docker/for-win#3327]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics

### Expected behavior
That volumes should work and changes in the local files should automatically be reflected inside of the container.

### Actual behavior
This occurs when using the `docker run -v` flag or running `docker-compose up`.
```
npm ERR! path /app/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/app/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-01T17_54_09_471Z-debug.log
```
### Information
  - Is it reproducible?
I was able to reproduce it on my home and work computers.

  - Windows Version: 
Windows 10 Pro 17134.556
Ubuntu 18.04.1 LTS (WSL) 

  - Docker for Windows Version: 
Can't use Hyper-V (Docker for Windows), nor VirtualBox (Docker Toolsbox), so using VMware (Ubuntu 18.04.1 server) for `server` and WSL (Ubuntu 18.04.1) for `client`. 

### Steps to reproduce the behavior

  1. [Enable WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
  2. [Download VMware Player 15](https://www.vmware.com/products/workstation-player/workstation-player-evaluation.html)
  3. [Download Ubuntu Server 18.04.1 ISO](http://mirror.math.princeton.edu/pub/ubuntu-iso/18.04.1/)
  4. Create Ubuntu Server 18.04.1 VM in VMware player (default settings are fine)
  5. Install Docker CE in both WSL and the VM using [these instructions](https://docs.docker.com/install/linux/docker-ce/ubuntu/).
  6. In the VM do the following:
```
# Create the directory to store the configuration file.
sudo mkdir -p /etc/systemd/system/docker.service.d

# Create a new file to store the daemon options.
sudo nano /etc/systemd/system/docker.service.d/options.conf

# Now make it look like this and save the file when you're done:
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd -H unix:// -H tcp://0.0.0.0:2375

# Reload the systemd daemon.
sudo systemctl daemon-reload

# Restart Docker.
sudo systemctl restart docker

# Get the IP address of the VM
ip add
```
  7. In WSL do the following:
```
# Enter the IP of the VM where "X.X.X.X" is
echo "export DOCKER_HOST=tcp://X.X.X.X:2375" >> ~/.bashrc && source ~/.bashrc
```
  **FOLLOWING INSTRUCTIONS ARE ALL IN WSL**

  8. `docker info` to make sure they are talking
  9. `git clone https://github.com/ishraqiyun77/docker_kubernetes.git`
  10. `cd frontend`
  11. `npm install` to reinstall the `node_modules`
  12. `docker build -f Dockerfile.dev .`
  13. Delete the `node_modules`
  14. `docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app <image id>`
  15. This will generate the above error
  16. `docker-compose up`
  17. This will generate the above error too

Only occurs in WSL. Tested in a Ubuntu Desktop VM and everything works fine. Works fine on macOS.

**Comment by 8084** [comment]
Maybe you need to share your drive in docker settings?

![](https://docs.docker.com/docker-for-windows/images/settings-shared-drives.png)

Just guessing.
