### ISSUE TITLE
Virtual disk location uses wrong default setting of Hyper-V Manager

### ISSUE THREAD

**Issue by boscogh** [docker/for-win#333]
### Expected behavior
If I move MobiLinuxVM.vhdx to another place (other hdd) and chage settings of MobiLinuxVM appropriately, I expect VM will use disk from new place
### Actual behavior
VM uses Hyper-V Manager default virtual disk folder for searching it disk. If it's moved, it recreated, so Docker become clear, no images, no containers.
If I change Hyper-V Manager default virtual disk folder, to the folder where I move MobiLinuxVM.vhdx, Vm become able to find it.
### Information
n/a
### Steps to reproduce the behavior

  1. Stop docker vm, i.e. exit docker
  2. Open Hyper-V terminal
  3. Move MobiLinuxVM.vhdx to another place 
  4. Check that settings of MobiLinuxVM points to this new place and disk is there
  5. Start docker
  6. Check that settings of  MobiLinuxVM are changed and points to the fresh created VM disk, at the location which is configured as default storage for _all_ Hyper-V VM disks.

**Comment by rneugeba** [comment]
Which version of Docker for Windows are you using? The latest Beta has a new settings which allows you to move the VHDX. Could you try that?

**Comment by boscogh** [comment]
I use 1.12.3 stable channel
I actually successfully workarounded issue by changing default location of Hyper-V VM disks, to point the directore there I moved the MobiLinuxVM.vhdx, after that, dockers peek it up successfuly.
I just feel this is not worked as designed, and not straightforward

**Comment by rneugeba** [comment]
Thanks for the feedback. Closing this issue as this has been fixed in Beta which provides a Settings element to move the VHDX location just for the MobyLinuxVM.VHDX. This will be rolled into a stable release in the future.
