### ISSUE TITLE
The port exposing is not working

### ISSUE THREAD

**Issue by DanielPomfyuk** [docker/for-win#3332]
### Expected behavior
The port should be exposed to the local Windows machine (eg localhost:7777)
### Actual behavior
The port is not reachable although it is present in the netstat
### Information

The issuie is appearing in the Windows Desktop docker when running the Linux container with the exposed port. It is not available niether directly from container's IP nor from Docker gateway.Windows firewall & antiviruses are turned off. 

  - Windows Version: 10
  - Docker for Windows Version: 2.0.0.2

### Steps to reproduce the behavior
**Our port is in the netstat list with status 'listening'**
![1](https://user-images.githubusercontent.com/36210859/52181504-6cf85780-27fb-11e9-875a-186765730518.png)
**Docker`s process is up and running .Port forwarding seams fine**
![2](https://user-images.githubusercontent.com/36210859/52181508-784b8300-27fb-11e9-8f29-a88964ccd1f1.png)
**Docker run command**
![3](https://user-images.githubusercontent.com/36210859/52181510-7d103700-27fb-11e9-8740-3ada005647f1.png)
**Current Docker version**
![4](https://user-images.githubusercontent.com/36210859/52181513-800b2780-27fb-11e9-9322-79f692d161b4.png)
**Postman request and subsequent exception**
![5](https://user-images.githubusercontent.com/36210859/52181539-ba74c480-27fb-11e9-9ed4-d3f3586e0361.png)

**Comment by djs55** [comment]
@DanielPomfyuk thanks for your report. Could you try again on the latest edge version? There have been several important bugfixes to the port forwarding code recently.
