### ISSUE TITLE
docker client experimental setting

### ISSUE THREAD

**Issue by markusknappfr** [docker/for-win#3347]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information
  - Windows Version: 10 1809
  - Docker for Windows Version: 18.09.1

### Steps to reproduce the behavior
A simple question:
How can I set the experimental flag of the docker client.

For the docker server (daemon), it can be set in docker desktop. But not for the client.
On Linux, this config is in ~/.docker/config.json
I can't find such config on windows. 
In C:\Users\ < username > \.docker there is only a daemon.json and this does not have any effect.

I need the experimental feature to use
docker manifest inspect

docker version
Client: Docker Engine - Community
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:34:26 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:50:10 2019
  OS/Arch:          windows/amd64
  Experimental:     true

**Comment by markusknappfr** [comment]
Found it by myself:
If the file .docker\config.json is not there, it has to be created.
To enable experimental features, the content has to be:
{
  "experimental": "enabled"
}

**Comment by IgorGolivets** [comment]
Hi, I have enabled experimental feature in all possible configs in userprofile and in Program Files and in GUI also, but still docker CLI still says that it is not enabled:
PS C:\WINDOWS\system32> docker version -f '{{.Server.Experimental}}'
false
Running the latest version of Docker for Windows, 2.3.0.2 (45183), Engine 19.03.8
