### ISSUE TITLE
Please give a "stop asking until the next update" option in the updater.

### ISSUE THREAD

**Issue by rlpowell** [docker/for-win#336]
I'm on the beta, but I've been burned badly by bugs in the last few updates, so at this point I don't want to install any until an update comes along that has something I really want, but the popup keeps bugging me.  :P  It would be nice if in addition to "remind me later" there was "don't ask until the next update".

**Comment by thaJeztah** [comment]
Any reason to not switch to the stable channel?

**Comment by jornh** [comment]
Looks like unchecking **Settings -> General -> [ ] Automatically check for updates** comes pretty close to what you want

**Comment by friism** [comment]
Closing this since it's configurable in settings.
