### ISSUE TITLE
msg="Error while setting up kubernetes: cannot update the host kube config: Failed to load Kubernetes CA: couldn't load the certificate file C:\\ProgramData\\DockerDesktop\\pki\\ca.crt: open C:\\ProgramData\\DockerDesktop\\pki\\ca.crt: Access is denied.. Retrying in 1s"

### ISSUE THREAD

**Issue by rbtcollins** [docker/for-win#3360]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Docker should not error like this. Users should be granted read access, or the crt file put somewhere with user read access

Carries on forever, even after a full state reset of docker desktop

**Comment by shahha** [comment]
Following workaround fixed problem for me,
Using windows File Explorer I opened the `C:\ProgramData\DockerDesktop\pki`. Windows complained that i didn't have permission, asked if I want to add permission. I agreed, and kubernetes immediately finished starting up.
