### ISSUE TITLE
Error while clicking right button on docker icon on windows

### ISSUE THREAD

**Issue by skolesnikovroox** [docker/for-win#3363]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F9E90BBF-8DE7-450D-A33D-F1D73FB019C9/20190208170815

### Expected behavior
not crashing while right clicking 
### Actual behavior
crashing
### Information

  - Windows Version: 10 Pro 1809, 17763.253
  - Docker for Windows Version: 2.0.0.2 (18.09.1)

### Steps to reproduce the behavior

  1. right click on docker icon
  2. crash

**Comment by henningms** [comment]
Have the same issue here. Can't do anything with Docker Desktop due to the crashing :|

**Comment by skolesnikovroox** [comment]
Updating to Docker for Windows 2.0.0.3 solved the problem.

**Comment by ulrich** [comment]
Thank you for feedback @skolesnikovroox 

@henningms do you tried to reset to factory defaults or/and uninstall/install Docker Desktop for testing? Moreover, is it possible to try with the latest version 2.0.0.3 ?

**Comment by ulrich** [comment]
Unable to reproduce this issue with the 2.0.0.2 version on Windows 10 1809.
