### ISSUE TITLE
Docker Desktop fails to start: Value cannot be null Parameter name: path1 in Path.Combine 

### ISSUE THREAD

**Issue by ivanov0304** [docker/for-win#3375]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 11F38B12-F21C-4859-8BCA-0160C02BD5E8/20190212001042

### Expected behavior
Docker desktop should be able to start and connect to docker service.
### Actual behavior
After upgrade to version 2.0.2.30972 and reboot of host machine, docker desktop fails to start. It displays an error window with following callstack:
Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2, String path3)
   at Docker.Core.DynamicPaths.GetPkiFolder(Settings settings)
   at Docker.Backend.Processes.ApiProxy.CommonArgs(Settings settings)
   at Docker.Backend.Processes.ApiProxy.StartWinNamedPipe(Settings settings, String daemonNamedPipe, Boolean runAsSystem)
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions)
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

### Information

  - Windows Version: Windows 10 Pro
  - Docker for Windows Version: 2.0.2.30972

### Steps to reproduce the behavior

  1. Upgrade docker to version 2.0.2.30972 (I don't remember explicitly agreeing to perform the upgrade, so it might've happened silently)
  2. Reboot host machine
  3. Docker desktop cannot start

**Comment by abk3001** [comment]
Exactly the same problem after update ...

**Comment by carey-bishop** [comment]
This won't help @ivanov0304, but I was able to resolve this issue on my dev machine with a reset of Docker

**Comment by davestephens** [comment]
> This won't help @ivanov0304, but I was able to resolve this issue on my dev machine with a reset of Docker

After an hour of messing about a reset fixed it for me too, but it does mean it nukes all of your data, images, containers etc. If you're using Docker properly then this shouldn't be an issue :)

**Comment by DotNetSparky** [comment]
I just ran into this myself -- just in case someone else comes across this, this was how I moved past it without reseting anything...

The file `%APPDATA%\Docker\settings.json` (e.g. `C:\Users\USERNAME\AppData\Roaming\Docker\settings.json`) had a null value for `dataFolder`.

```json
  ...
  "dataFolder": null,
  ...
```

I just changed this to an empty string (`""`) and restarted.

```json
  ...
  "dataFolder": "",
  ...
```

Ironically, it seems where that error was being thrown, that setting doesn't even end up getting used (for CE)... but before it decides that it uses it in a call to `System.IO.Path.Combine` (which throws on null values).

**Comment by andresberrios** [comment]
@DotNetSparky that worked for me! Thanks!

**Comment by rvveldhuyzen** [comment]
> I just ran into this myself -- just in case someone else comes across this, this was how I moved past it without reseting anything...
> 
> The file `%APPDATA%\Docker\settings.json` (e.g. `C:\Users\USERNAME\AppData\Roaming\Docker\settings.json`) had a null value for `dataFolder`.
> 
> ```json
>   ...
>   "dataFolder": null,
>   ...
> ```
> 
> I just changed this to an empty string (`""`) and restarted.
> 
> ```json
>   ...
>   "dataFolder": "",
>   ...
> ```
> 
> Ironically, it seems where that error was being thrown, that setting doesn't even end up getting used (for CE)... but before it decides that it uses it in a call to `System.IO.Path.Combine` (which throws on null values).

@DotNetSparky That did the trick. Thank you so much for posting this!

**Comment by carey-bishop** [comment]
I've just experienced this issue for the second time now, triggered it seems by the latest Docker update.

**Comment by wagsiles** [comment]
> I just ran into this myself -- just in case someone else comes across this, this was how I moved past it without reseting anything...
> 
> The file `%APPDATA%\Docker\settings.json` (e.g. `C:\Users\USERNAME\AppData\Roaming\Docker\settings.json`) had a null value for `dataFolder`.
> 
> ```json
>   ...
>   "dataFolder": null,
>   ...
> ```
> 
> I just changed this to an empty string (`""`) and restarted.
> 
> ```json
>   ...
>   "dataFolder": "",
>   ...
> ```
> 
> Ironically, it seems where that error was being thrown, that setting doesn't even end up getting used (for CE)... but before it decides that it uses it in a call to `System.IO.Path.Combine` (which throws on null values).

Thanks a lot!!! It works!!!

**Comment by mamalukes** [comment]
Uninstalling my antivirus seems to make it work for me (Symantec). Everything else didn't work.

**Comment by mikeparker** [comment]
This is fixed and will be released shortly, please use the workaround as above until the release is out.

**Comment by mikeparker** [comment]
Docker Desktop 2.1.0.1 stable has been released with a fix for this now.

**Comment by creativetechdev** [comment]
This issue is with linux containers if you will switch to windows based containers docker will work correctly.
