### ISSUE TITLE
Docker Desktop 2.0.0.2 (30215) requires user:password for proxy to work

### ISSUE THREAD

**Issue by Toninoso** [docker/for-win#3377]
On Windows one can specify HTTP_PROXY (or HTTPS_PROXY) in two ways:

HTTP_PROXY=http://user:password@proxy:port

or 

HTTP_PROXY=http://proxy:port

Naturally, most users prefer the second form which will work fine with, say, Git when accessing Github, and in many other cases.

With Docker Desktop, AFAIK, one has to discover that only the first form will work by trial and error and, in any case, it is pretty bad security that anyone can walk by your desktop when you are away, click on Docker Desktop settings and see your password.

**Comment by TimRowe** [comment]
@Toninoso HTTP_PROXY is the enviroment variable？
Docker Desktop with gui proxy setting your format (http://user:password@proxy:port)does't work.
