### ISSUE TITLE
Docker Desktop keeps starting at login though that setting is disabled

### ISSUE THREAD

**Issue by Yggdrasil** [docker/for-win#3378]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A05E464B-8F2C-4FF7-AAD9-9209D6953F04/20190212103103

### Expected behavior
After disabling the "Start Docker Desktop when you login" setting, Docker should not run when I log in but should have to be manually started.

### Actual behavior
After disabling the "Start Docker Desktop when you login" setting, Docker still keeps starting when I log in.

### Information
The problem has persisted for weeks now. Not entirely sure when or how it started. I don't use Docker daily and suddenly noticed it kept running despite having disabled it earlier.

I've uninstalled and reinstalled Docker Desktop to no effect. I've toggled the setting on and off to no effect.

  - Windows Version: Windows 10 Pro (1803), joined to domain. Roaming profile.
  - Docker for Windows Version: 2.0.0.2 stable

### Steps to reproduce the behavior

Not sure how to reproduce on another system. It just started happening and I've ben unable to make it stop.

**Comment by wojciechrak** [comment]
I am too having this issue.

Windows 10 Pro (1809) build 17763.316, not joined to domain
Docker for Windows
Version 2.0.0.3 (31259)
Channel: stable
Build: 8858db3

I've tried reseting to factory defaults, but that didn't solve the issue.

**Comment by wp4nuv** [comment]
Just wanted to chime in as I also have the same issue and a reset doesn't do the trick.
Window 10 Pro Insider Preview (1903)
Build 18898
Docker for Windows
Version 18.09.2, build 6247962 (download from docker, not compiled)

**Comment by Exist2Resist** [comment]
Same here latest version keeps booting even though the option is disabled.
Latest version of Win 10 and Docker.

**Comment by Exist2Resist** [comment]
Quick fix in Win 10 is to ctrl+alt+del and open task manager. 
Bottom left click More Details.
Go to Startup tab, right click Docker Desktop and select Disable. 
Repeat steps with Enable if you want to enable on startup.
