### ISSUE TITLE
Error can't stat during image build

### ISSUE THREAD

**Issue by artisticcheese** [docker/for-win#338]
### Expected behavior
Build new image
### Actual behavior
Error thrown 
```
PS D:\docker> docker build d:\docker
Error checking context: 'can't stat '\\?\D:\docker\images\windowsfilter\295c43c61734d991b75abc46790a9f35816f399feb6fbe87bac487a260b4396d\UtilityVM\Files\Windows\System32\LogFiles\WMI\RtBackup''.
```
### Information
When trying to build image error is being thrown

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
Can not upload diagnostic log due to bug
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)
Version 1.13.0-rc3-beta33 (9442). Win 10

**Comment by friism** [comment]
Can you build any images? What happens if you use a relative path, eg. `cd d:\docker` and then `docker build .`

**Comment by artisticcheese** [comment]
Same issue. Also can not build ANY images. My dockerfile has simple instruction FROM microsoft/iis and nothing else.

```
PS D:\docker> docker build docker
unable to prepare context: unable to evaluate symlinks in context path: GetFileAttributesEx D:\docker\docker: The system cannot find the file specified.
```

**Comment by friism** [comment]
Is `d:\docker` the directory that holds your Docker graph directory? It may not be usable as build context, see https://github.com/docker/docker/issues/27739

What happens if you just create an empty directory, eg. `C:\foo`  or `D:\bar`, place your Dockerfile there and try the build?

**Comment by artisticcheese** [comment]
Yes, building from different directory works (like d:\foo).
My graph directory is d:\\docker\\images not d:\\docker
So what is exact limitation of building images?

**Comment by friism** [comment]
@artisticcheese all the the build-context directory (`d:\docker` in your case) is send to the Docker daemon as build context, including sub direcotries. The `images`  folder will container a lot of symlinks and other non-standard files that make that make Docker work, and this won't work.

cc'ing @jhowardmsft to see if errors might be improved for cases like this.

**Comment by friism** [comment]
Closing issue.
