### ISSUE TITLE
Docker being slow on Windows 10

### ISSUE THREAD

**Issue by ksiamro** [docker/for-win#339]
I created own Apache-php dockerfile with docker compose on Widnows 10 Enterprise.
I'm using Docker 1.12.3.
I follow https://msdn.microsoft.com/en-us/virtualization/hyperv_on_windows/quick_start/walkthrough_install and I have enabled Hyper-V on step 3, but in systeminfo.exe its
`Hyper-V Requirements: A hypervisor has been detected. Features required for Hyper-V are not be displayed.`
About 1-2 weeks ago Docker begin be slowly.
1. Very slowly open app and create default containers.
2. Very slow working containers.
3. Sometimes on browser Instead of project page I got 404 - project is in container.
On every system restart I have to close and run a few times docker for make it works.

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
1CF1B088-B819-4244-AAE6-8AC6FE0B8A4C/2016-12-19_08-10-13

I noticed repository d4w/nsenter is downloaded and run automatically every time i restart computer. What is it? I couldn't find anything on google. I found only nsenter but can't localize d4w.

**Comment by rneugeba** [comment]
@ksiamro thanks for the report
- the message: `Hyper-V Requirements: A hypervisor has been detected. Features required for Hyper-V are not be displayed` is expected.
- the `d4w/nsenter` is not really downloaded, it comes with the Docker for Windows installation. We use it to mount shared volumes.

As for your problem of docker slowing down, it's going to be tricky to debug without having access and the fact that it takes a couple of weeks to slow down is odd...

Does a factory reset help? Note, this will remove your images.

Also, could you try the latest beta, which has a lot of changes to the internals.

**Comment by ksiamro** [comment]
Thanks for answer ;)

ad. d4w/nsenter - Oh, good to know. I couldn't find any info about that. 
I was afraid about it cause sometimes d4w/nsenter is running few mins after Windows up.

I tried factory reset. Uninstall and install docker again. Also remove and build all images.

Can I provide You more info?

**Comment by friism** [comment]
@ksiamro do you have an example of a container or project that you find to be slow so that we can try to reproduce the problem?

**Comment by erichexter** [comment]
I have seen identical containers running slow on some very fast host machines and fast on average host machines. Its as if the container is being throttled. In most cases, I have found that the container will sit at 20% cpu utilization, which I assume is 20% of the available cores on the host machine. It is very hard to get any insight into what is causing the slowness, without knowing where to look. Are there any troubleshooting steps the team recommends to capture to help identify a root cause?

**Comment by jasonbivins** [comment]
Hi @erichexter 
Take a look at these settings in the GUI by right clicking > Settings > Advanced settings - they might help with the throttling.

![image](https://cloud.githubusercontent.com/assets/28021664/26795120/63806ee2-49f2-11e7-9fee-c0c454563793.png)

**Comment by jasonbivins** [comment]
@ksiamro   Are you still seeing slowness issues on the newer versions?

Have you tried setting the CPU throttling in the GUI?

**Comment by EMCP** [comment]
Are advanced settings ONLY for linux container mode?  I am in windows mode and not seeing Advanced settings whatsoever

**Comment by sandokanelcojo** [comment]
@EMCP nope, those are also in Windows.
Checked in version: 18.03.1-ce-win65 (17513)

**Comment by kerrhome** [comment]
I am using that version of Docker for Windows containers on Windows 10 and I do not see those options.  What could I be doing wrong?  There is no advanced tab at all.
![image](https://user-images.githubusercontent.com/5033953/41936838-81c47480-795c-11e8-9656-533995064b89.png)
