### ISSUE TITLE
Docker Desktop 2.0.0.2 pull-hello-world-returns-x509-certificate-signed-by-unknown-authority

### ISSUE THREAD

**Issue by Toninoso** [docker/for-win#3391]
None of the related issues on this site were helpful.

I tried a forum before posting here. Here is the post:
https://forums.docker.com/t/pull-hello-world-returns-x509-certificate-signed-by-unknown-authority/68926

Nothing in responses helped resolve the problem.

In short the problem is (see the post above for details):

Issue command: docker pull-hello-world.

Response:

Using default tag: latest
latest: Pulling from library/hello-world
1b930d010525: Pulling fs layer
error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/fc/fce2 2…
: x509: certificate signed by unknown authority (possibly because of “crypto/rsa: verification error” while trying to verify candidate authority certificate “MyCompany WebGateway CA”)

This is not supposed to happen in version 2.0.0.2 and company HTTP proxy certificates should be taken as valid even if self signed.

**Comment by PavelSosin** [comment]
I have the same issue when tying to access my kubernetes cluster from Chrome. Neither service which kubectl shows serves HTTPS. Chrome finds several certificates on my laptop: Company certificate installed by Company IT, several self-signed got from other servers, like minikube, etc. , but Chrome security rejects certificates issued by  "kubernetes" authority.
