### ISSUE TITLE
TCP port 2375 only lists Windows Images and not my Linux images

### ISSUE THREAD

**Issue by srifromchennai** [docker/for-win#3394]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Both Windows and Linux Images should be listed on the TCP port.

### Actual behavior
Only Windows Images are listed.

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...Expose port 2375 in docker settings
  2. ...Upadte daemon.json to add the host

Now try to list all the images.Only Windows Images will be displayed in the tcp port irrespective of whether Linux or Windows containers are running.

**Comment by nguyenl95** [comment]
I experience the same issue
