### ISSUE TITLE
Windows Firewall block with ver 18.09.2

### ISSUE THREAD

**Issue by gregorylocke** [docker/for-win#3396]
- [X ] I have tried with the latest version of my channel (Stable or Edge) This is what caused the error
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID:3F7F475E-387E-4EAD-80CC-1505F91C29DB/20190215165257

### Expected behavior
Local drive mount
Was running fine yesterday. 
Allowed docker image update to run today and now can't access local drives. 
share C: drive with docker application does not work.

### Actual behavior
Firewall blocked message after providing admin ID and psw in settings. 

### Information

  - Windows Version: 10 Enterprise 64-bit(24GB RAM)
  - Docker for Windows Version: 18.09.2

### Steps to reproduce the behavior

  1. ...go to settings,
  2. ...select share drive
3 select C
4 enter ID/psw
5 get message firewall Detected.
6 verified Firewall is open and sharing for Docker.

**Comment by SefaZeng** [comment]
I got the same issue,and the ways of before dont work for me..

**Comment by echo954** [comment]
Just downloaded Docker for the first time yesterday and been pulling my hair out since. I'm on version 18.09.2. The DockerSmbMount rule is in my firewall and I've set the DockerNat to private. Please Help!!

**Comment by rmNyro** [comment]
Seems like the issue is still present, just no one get a clue about it I guess. : /

**Comment by gregorylocke** [comment]
No fix available. No help. I gave-up on docker.
