### ISSUE TITLE
Docker Desktop 2.0.0.3 Installation failed

### ISSUE THREAD

**Issue by ChakritRakuang** [docker/for-win#3408]
The process cannot access the file 'C:\Program Files\Docker\Docker\Bugsnag.dll' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at LightweightInstaller.UnpackArtifactsStep.<DoAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.InstallWorkflow.<HandleD4WPackage>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()

**Comment by Arash-Sabet** [comment]
Same issue here.

**Comment by ulrich** [comment]
@ChakritRakuang @Arash-Sabet can you detail if this error occurred when you upgrade/install Docker Desktop from 2.0.0.2 to 2.0.0.3 or during an install from scratch ?

**Comment by Arash-Sabet** [comment]
Happened to me during upgrading. @ulrich

**Comment by ulrich** [comment]
Is it possible to restart Docker Desktop and try to upgrade (normally automatic) it by the **Check for Updates** item menu?

**Comment by Arash-Sabet** [comment]
To recover from the situation I had to restart the machine, delete docker folder and re-install the recent release of docker from scratch after disabling windows firewall and virus defender.

**Comment by ulrich** [comment]
@Arash-Sabet thank you for your feedback, it is not the normal situation that to do that. But the more important thing is you had is that you could update Docker Desktop.

**Comment by Arash-Sabet** [comment]
@ulrich Unfortunately docker update on windows is not taking place as smoothly as on OSX or Linux. Not sure why it faces to some complexities.

**Comment by cwpark6607** [comment]
I got the same issue when installing Docker Desktop 2.0.0.3 on my windows 10 enterprise. Is there any solution yet?

**Comment by xmalion** [comment]
same name, another issue. 
clean install on windows 10 Pro (1803). windows defender is disabled. repeat 2 times. reboot 1 time. zero result.
![image](https://user-images.githubusercontent.com/5241133/54083933-76fe0080-433b-11e9-90cb-f07ca13404ab.png)

**Comment by seanvikoren** [comment]
Turned off all security.  Install still hangs at 'Removing files..."

![docker_fail](https://user-images.githubusercontent.com/786528/59644237-f2cccd80-9120-11e9-8695-899d605dd38d.jpg)

**Comment by mikewalker74** [comment]
Same issue on windows 10 18917 insider build. disabling av didnt make a difference, is there any other workaround available ?

**Comment by tinours** [comment]
Same problem with 2.1.0.0 I did manage to add the installers 
  - 2.0.0.3 "Docker for Windows installer.exe" and 
  - 2.1.0.0 "ais2121p.qfs.exe"
in the authorized applications of Windows Defender by checking the name and place on drive in task manager and re-executing them manually.

After the installations finished, I try to start Docker for windows but there was an error that com.docker.service could not access some folders. I also add the c:\Program Files\Docker\Docker\com.docker.service in the authorized apps.

Then there was a problem with some parameters so I had to do a factory reset of docker settings to get it to work again.

Hopefully there will be a better fix than this.

Here is a print screen (in french, sorry) of my Windows Defender authorized apps and also the running docker for windows about screen.

![image](https://user-images.githubusercontent.com/11246222/62240926-159c0400-b3a6-11e9-8569-90d5882447d8.png)

**Comment by tinours** [comment]
Today I got the same problem with the update to 2.1.0.1 but this time it was a "Disk Full" message I received and now docker is completly uninstalled. So I need to reinstall the old version, hope I won't loose my containers config this time.

**Comment by tinours** [comment]
I just finish the 2.1.0.0 installation and everything is back online Yeah...
I will try the update to 2.1.0.1 with the same technics. (Check the temp name in Task Manager and add permission in Windows Defender for that file and runnit again simultaneously than close the first instance.)

**Comment by tinours** [comment]
Hope this will help with 2.1.0.1 also (I notice a lot of forums open for a bug of after upgrade...)

Erreur I had with the update.
![HddFull](https://user-images.githubusercontent.com/11246222/62714078-dedc7400-b9cb-11e9-8133-062f974694da.PNG)

Task Manager tasks I found.
![DockerInstallTaskManangerSubProcess](https://user-images.githubusercontent.com/11246222/62714111-f0258080-b9cb-11e9-884d-02e19ff08a03.PNG)

The Addition of the subprocess to the Windows Defender authorized applications to modify protected folders.
![AddTempInstallerInWindowsDefender](https://user-images.githubusercontent.com/11246222/62714149-02072380-b9cc-11e9-998f-3d447579a794.PNG)

Then the result ! Yeah.
![Success](https://user-images.githubusercontent.com/11246222/62714180-0e8b7c00-b9cc-11e9-99e2-a51725ef6862.PNG)

Really hope the containers will startup by themselves.

**Comment by tinours** [comment]
Success ! Please fix this in next release.

**Comment by sherif-med** [comment]
Download docker installer, do not use the existing installer and proceed with the reinstallation!

**Comment by 11ert** [comment]
I have had the same issue with version 2.1.0.3.
Disabled the virus scanner of windows and installation was succesful.
