### ISSUE TITLE
Cannot create a container with a volume on a drive mapped to network storage via CIFS

### ISSUE THREAD

**Issue by samcro1967** [docker/for-win#3417]
### Expected behavior
Create a docker container with a volume on a network drive.  Prompts for credentials to network drive and successfully mounts volume

### Actual behavior
Prompts for credentials and fails

### Information
The problem is reproducible.
It is not a new problem and has always occurred.
 Windows Version 10.0.17134.590

C:\Windows\system32>docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     true

### Steps to reproduce the behavior
docker create --name container_name -p 1234:1234 –v K:\Users\username\Documents\Docker\container_name\config:/config repository/container_name

K is a drive mapped to network attached storage via CIFS.

![image](https://user-images.githubusercontent.com/2319445/52958706-43424300-335a-11e9-9938-67e2388c3ff3.png)

Click Share It

![image](https://user-images.githubusercontent.com/2319445/52958761-5d7c2100-335a-11e9-9440-62d3f0d3de05.png)

Enter user ID and password.  Click OK.

"docker create --name container_name -p 1234:1234 –v K:\Users\username\Documents\Docker\container_name\config:/config repository/container_name
Error response from daemon: Drive sharing failed for an unknown reason"

I have tried a local account as well as an account created on the network storage.  The local account and the account on the network storage both have the same name and password.  I have tried using both computer_name\account_name and network _storage\account_name IDs and neither work.

I can connect to a container and map a drive with the user ID and PW without issue.
`mount -t cifs //<host>/<path> /<localpath> -o user=<user>,password=<user>`

**Comment by samcro1967** [comment]
Can anyone confirm if this is a bug or if this is not supposed to work?  I have read lots of posts for people trying to mount a  volume on a network drive, but have not seen anyone successfully do it.  The GUI seems to indicate it should be possible as it acknowledges it needs and prompts for creds.  It just fails to authenticate when they are provided.

**Comment by Cherishty** [comment]
I recently **successfully** use this feature in my latest docker for windows (Server Version: 18.09) and win10 1803. You may upgrade your OS or docker to validate it.

However, when it comes to win server 1803 or 2019, this pop-up doesn't show anymore, and mount will "success"  but getting error when access to the driver in container, which throws: 

> A specified logon session does not exist. It may already have been terminated.

I try every solution I can find but none can fix it. Anyone has any clues?

**Comment by samcro1967** [comment]
I have updated to Windows 10 build 1809 and it still does not work.  It no longer errors out after the PW is entered, but the container never gets created.  The command just fails and does not provide an error message back.
