### ISSUE TITLE
Can't run Dockers on Windows 10

### ISSUE THREAD

**Issue by mbunsk** [docker/for-win#3426]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mbunsk** [comment]
Windows Version 10.0.17134
Docker Desktop version 2.0.0.3 (31259)
Steps to reproduce:
1. Run Docker Desktop
2. Open CMD prompt and type "docker run hello-world"
3. error

**Comment by mbunsk** [comment]
Running this command in PowerShell solved my issue:
cd "C:\Program Files\Docker\Docker"
./DockerCli.exe -SwitchDaemon

**Comment by oldium** [comment]
So basically you tried to run a Linux container (hello-world) when you had Docker set to run Windows containers...

**Comment by Ciantic** [comment]
@mbsunk please close the issue from "Close issue" at the bottom of this page.
