### ISSUE TITLE
Docker cannot start

### ISSUE THREAD

**Issue by Jagoop** [docker/for-win#3442]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker should start
### Actual behavior
Docker fails with error:

Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The object already exists.

   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

### Information
Docker Desktop 
Community
2.0.0.3 (31259)

Windows 10 build 18342

### Steps to reproduce the behavior

I have not been able to reproduce the error, but instead solved it.

The cause was a failure when creating the MobyLinux VM. 
The script MobyLinux.ps1 tries us an Ip address that is already allocated to an adapter in line 156. In my case 10.75.0.1, which was in use by a bluetooth device.

I removed the bluetooth device, and everything worked.

Maybe you could add a check for ip's already in use?

**Comment by neiltwist** [comment]
Out of interest, I used to have a working Docker environment and I created another Hyper-V VM, but it broke Docker for Windows somehow. I reset everything and deleted the other VM, reset to factory settings and got this error (some time passed between each step). I checked my network adapters and nothing seemed to work, until I stumbled across somewhere else detailing how to delete network adapters when the delete option is greyed out. I had to search the registry entries in "HKEY_LOCAL_MACHINE->SYSTEM->CurrentControlSet->Services->Tcpip->Parameters->Interfaces" and found one with "10.0.75.1" as the IP address. I have no idea where this came from, but deleting this registry entry (after backing up) fixed the issue and the MobyVM could be created and started.

**Comment by mikeparker** [comment]
We're working on a solution which allows docker to work even if you have something already using the 10.0.75.1 address. In the meantime yes, removing whatever's using it is the workaround. 

This could be bluetooth devices (as in the OP) or it could be other network adapters or previous broken docker network adapters. We've seen a lot of external software break the docker network adapters leaving them hanging around, such as VPN clients, anti virus software, custom firewalls, switching domain user permissions and windows updates. Hopefully we can improve our detection of these scenarios in future.
