### ISSUE TITLE
Why is issue 1340 closed still?

### ISSUE THREAD

**Issue by StingyJack** [docker/for-win#3445]
Are there any maintainers here or is this whole repo run by the evil dockerbot?

/remove-lifecycle stale
/lifecycle frozen

**Comment by StingyJack** [comment]
FU bot

/remove-lifecycle stale

/lifecycle frozen

**Comment by guillaumerose** [comment]
Issue is reopened but this issue is nearly impossible to solve.

**Comment by StingyJack** [comment]
@guillaumerose - the issue should state that then, by a human, and not this poorly designed/implemented bot. It's been closing issues that maintainers haven't commented in or have even tagged. And the instructions it leaves for contacting the maintainers are not follow-able.
