### ISSUE TITLE
Sharing drive fails with "Firewall detected" dialog box 

### ISSUE THREAD

**Issue by avcarrillo** [docker/for-win#345]
### Expected behavior
Share specified drive with Docker containers
### Actual behavior
Error message: A firewall is blocking file Sharing between Windows and the containers. See documentation for more info.
### Information

When trying to share any of the available drives in the Docker -> Settings -> Shared Drives menu, I get the following error. 

Error message: A firewall is blocking file Sharing between Windows and the containers. See documentation for more info.

Drives C & D are physical. E and F are USB. All give the same error

Diagnostic ID = 8536A552-B31B-4EDE-BA77-D1EBED500CF7/2016-12-20_11-40-07

Host: Windows 10 Enterprise, Version 1607 (OS Build 14393.321)

### Steps to reproduce the behavior

Steps I performed:

1. Uninstalled Docker
2. Confirmed Hyper-V had no VMs
3. Rebooted
4. Disabled Firewall
5. Installed Docker Beta 1.13.0-rc4
6. Attempted to enabled Shared Drives for F. Received error Firewall detected. A firewall is blocking file Sharing between windows and the containers. Log shows the following. (Confirmed firewall is off)

[11:27:27.822][SambaShare ][Error ] Unable to mount F drive: firewall is blocking
[11:27:27.824][SambaShare ][Info ] Removing share F
[11:27:27.911][NamedPipeClient][Info ] Received response for Mount
[11:27:27.910][NamedPipeServer][Info ] Mount done in 00:00:03.0704345.
[11:27:27.911][SegmentApi ][Info ] Usage statistic: actionSettingsChanged
[11:28:41.013][FeedbackSettings][Info ] Open logs

**Comment by rneugeba** [comment]
@simonferquel could you take a look?

**Comment by denisvmedia** [comment]
I also have the same problem. And yes, disabling Windows Firewall doesn't help. No 3rd-party Firewall or Antivirus is installed.

**Comment by mikedarke** [comment]
I'm experiencing potentially the same issue, attempting to share either my C or D drives results in the "A firewall is blocking file Sharing between Windows and the containers". Windows firewall is disabled.

OS:	Microsoft Windows 10 Pro
Version: 10.0.14393 Build 14393
Docker version 1.13.0-rc5, build 43cc971 (Also tested on 1.12.5, build 7392c3b)
Diagnostic id: 932A343C-F6C5-4BD6-95F2-942E1726EBB9/2017-01-12_16-13-19

I have tried the suggestions from @gorbunovav that worked  for @denisvmedia from issue #114 but to no avail.

If I manually share the D: drive in Windows I can browse to \\10.0.75.1\d from Windows 
What I have noticed is that when I run a privileged container using...

    docker run --net=host --ipc=host --uts=host --pid=host -it --security-opt=seccomp=unconfined --privileged --rm alpine /bin/sh

...I cannot ping the host on 10.0.75.1, it just times out. If I look at the output from ifconfig the following network interfaces are displayed.

docker0   Link encap:Ethernet  HWaddr 02:42:A7:4E:7F:DF
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:a7ff:fe4e:7fdf/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:274 errors:0 dropped:0 overruns:0 frame:0
          TX packets:14 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:21364 (20.8 KiB)  TX bytes:972 (972.0 B)

eth0      Link encap:Ethernet  HWaddr C0:FF:EE:C0:FF:EE
          inet addr:192.168.65.2  Bcast:192.168.65.15  Mask:255.255.255.240
          inet6 addr: fe80::a46e:d6e9:af1b:c8b/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:345 errors:0 dropped:0 overruns:0 frame:0
          TX packets:566 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:30997 (30.2 KiB)  TX bytes:129440 (126.4 KiB)

hvint0    Link encap:Ethernet  HWaddr 00:15:5D:07:D3:03
          inet addr:10.0.75.2  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::215:5dff:fe07:d303/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:7579 errors:0 dropped:10 overruns:0 frame:0
          TX packets:247 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1181334 (1.1 MiB)  TX bytes:22726 (22.1 KiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:19 errors:0 dropped:0 overruns:0 frame:0
          TX packets:19 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:1680 (1.6 KiB)  TX bytes:1680 (1.6 KiB)

veth184963d Link encap:Ethernet  HWaddr 9E:48:23:99:13:63
          inet6 addr: fe80::9c48:23ff:fe99:1363/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:8 errors:0 dropped:0 overruns:0 frame:0
          TX packets:12 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:648 (648.0 B)  TX bytes:996 (996.0 B)
		  
Further testing has shown I can mount the host d share within the privileged container using the eth0 interface...
    
    mount -t cifs //192.168.65.1/d /d -o username=<username>,password=<password>
		
This same issue appears to be present across all machines I've tested on our work network. I can share without issues on my home laptop with the same Windows 10 and Docker builds.

Does anyone have any suggestions?

**Comment by sonofagunn** [comment]
I have the same problem. The only info I have that may help is that everything works fine when I am physically in my corporation's office. I get this firewall error if I am working from home, whether or not I am connected to the VPN. My corporation does have "DirectAccess" which I am connected to.

**Comment by sisu4u** [comment]
I have this problem as well. But for me it is definitely no firewall blocking that. 
What helps me is:
- Open Network and sharing center
- Properties of my ethernet connection
- Uninstalling "File and Printer Sharing for Microsoft Networks"
- Installing "File and Printer Sharing for Microsoft Networks"
- *Without* restarting the docker host I can now just share drive c:\

Sadly I have to do this every time I start the docker host / restart my computer.

I am on 1.13.0 (9795) and Windows Build 14986.1001

Here my diagnostics ID: A58293E2-C81D-4053-89ED-BF48C10543CF/2017-01-23_16-10-51

**Comment by peterhorvath** [comment]
I have similar problem.
I am on corporate network with corporate laptop with windows 10 enterprise 64bit development mode enabled. 
Domain profile has the firewall turned off.

A diagnostic was uploaded with id: 2A4F4285-C322-442B-896E-CE391D2F163E/2017-02-07_09-32-55
![image](https://cloud.githubusercontent.com/assets/1454081/22695442/cf46cbb2-ed18-11e6-9bf6-46d0973439fe.png)
![image](https://cloud.githubusercontent.com/assets/1454081/22695494/f0a555ee-ed18-11e6-950b-bd1ac226504e.png)

I am always getting firewall block messages as the others. I've tried to run docker as administrator that didn't help either

**Comment by simonferquel** [comment]
The network between the Linux VM and Windows is categorized as public. Can you check in Network and Sharing Center / Change advanced settings that file and printer sharing is enabled for "Guest or public" networks ?

**Comment by peterhorvath** [comment]
![image](https://cloud.githubusercontent.com/assets/1454081/22700318/3e7f08d2-ed28-11e6-9438-0a7a16924ef1.png)
![image](https://cloud.githubusercontent.com/assets/1454081/22700472/d3154b46-ed28-11e6-8e37-d4a7e2d41ab0.png)

**Comment by avcarrillo** [comment]
Guest or Public File and printer sharing are set to on. Still have the same problem

**Comment by avcarrillo** [comment]
Ok, I was able to get it working on my pc. The issue is I am on a corp domain, and the group policy was keeping the firewall on. I tried adding all the rules recommended by the Docker Docs, and disabling the actual windows service, but no luck. I finally follwed the instructions here https://www.vanstechelman.eu/windows/how_to_bypass_domain_policy_firewall_settings, but instead of removing the registry key, I just manually set them to 0, and rebooted. Once the pc was back online, I was able to share the drives. Hope that helps

**Comment by dgageot** [comment]
Hi @avcarrillo @peterhorvath @denisvmedia, we've tried to fix this issue in a test release that can be downloaded here: https://download-stage.docker.com/win/samba-experiment/10154/InstallDocker.msi

**Comment by diman82** [comment]
> Hi @avcarrillo @peterhorvath @denisvmedia, we've tried to fix this issue in a test release that can be downloaded here: https://download-stage.docker.com/win/samba-experiment/10154/InstallDocker.msi
Didn't help in my case.

**Comment by dgageot** [comment]
Thank you @diman82, we'll keep you posted when we have another version to test.

**Comment by libsamek** [comment]
Maybe the issue is routing entries from VPN client? See my post in https://github.com/docker/for-win/issues/360

**Comment by hugolesta** [comment]
Hi @libsamek  I have disabled all my VPN connections and It works ! Thanks!

**Comment by mireczatko** [comment]
sisu4u's solution fixed same issue for me. Thank you @sisu4u

**Comment by msimpson** [comment]
The solution posted by @sisu4u fixed my issues, as well. Although, it's only a band-aid.

**Comment by friism** [comment]
We shipped improvements in Docker 17.05, can you try upgrading and checking whether that solves the problem?

**Comment by mikevh** [comment]
I'm getting this message now on the latest edge version 17.05 of docker for windows. Previously when I check the C drive to share it, after entering my credentials, the C drive would automatically be then unchecked and not shared.  This is on a fresh install of Windows 10 version 1703

**Comment by gorbunovav** [comment]
@friism doesn't work for me too. The trick with file sharing disable/enable is still required after reboot.
Windows build 15063.138, Docker 17.05-ce-win9 (11965)

**Comment by msimpson** [comment]
@friism 
At this point, I believe it to be a Hyper-V issue in actuality. I found that instead of fully uninstalling the "ms_server" service from the adapter is necessary. You merely have to disable and then re-enable it before restarting Docker for it to resolve the issue.

In fact if you start Docker upon boot and have encountered this issue, you could configure Docker to not start upon boot and use the following PowerShell script instead:

```
$id = [System.Security.Principal.WindowsIdentity]::GetCurrent();
$principal = New-Object System.Security.Principal.WindowsPrincipal( $id );
$adminRole = [System.Security.Principal.WindowsBuiltInRole]::Administrator;

if ( $principal.IsInRole( $adminRole ) ) {
  Disable-NetAdapterBinding -Name "vEthernet (DockerNAT)" -ComponentId ms_server
  Enable-NetAdapterBinding -Name "vEthernet (DockerNAT)" -ComponentId ms_server
  Start-Process -NoNewWindow "\Program Files\Docker\Docker\Docker for Windows.exe"
}
```

That will cycle the interface's sharing service and then start Docker. It does however require, and checks for, Administrator privileges first.

**Comment by friism** [comment]
@msimpson what version are you using? We've shipped improvements in 17.05 (the Edge channel).

**Comment by msimpson** [comment]
@friism 
Sorry, but due to continued issues with Hyper-V in Windows 10 with regard to random screen flickering and artifacts I've been forced to remove it and stop using Docker for Windows as a result. Therefore, I cannot offer any further feedback as to whether or not this latest update fixed this networking issue.

**Comment by kiranj321** [comment]
@msimpson 's script of disabling and enabling is the only solution that worked for me so far. I am using Version 1703 (OS Build 15063.138)

**Comment by mikevh** [comment]
I'm still getting this error with the latest edge version 17.05.0-ce-win11 (12053)

**Comment by xtophs** [comment]
+1 on error still happening with win11:

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 21:43:09 2017
 OS/Arch:      linux/amd64
 Experimental: true

**Comment by superbob** [comment]
Still happening with last version :
_Version 17.06.0-ce-win18 (12627)
Channel: stable
d9b6651_
```
$ docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by max402** [comment]
In my case the problem was in windows system variable DOCKER_HOST=172.16.9.54:2375.
After removing that variable and restarting computer disks sharing in docker works again.

**Comment by todorinskiz** [comment]
+1... 9 months later ...

**Comment by damtur** [comment]
Still happening on 17.09.0-ce-win33  :(

**Comment by indiecore-fm** [comment]
Happening for me and no "workaround" fixes it.

**Comment by avcarrillo** [comment]
Try the following. using regedit, set HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\WindowsFirewall\PublicProfile\EnableFirewall to 0, then either restart, or use Windows Services, and restart Windows Firewall.

This works for me on the current version of Docker

**Comment by j0hnth0m** [comment]
Docker version: 17.12.0-ce-win46 (15048)

Not able to use Linux container because of Firewall blocking shared drive. Running Docker on a machine that is on a corporate network.

Windows Firewall is turned on for Public, Domain and private.  Docker rule for allowing SMB is defaulted from installing Docker.  It allows port 445/TCP on local 10.0.75.1 from remote 10.0.75.2 for public,domain and private.

Attempting to share C drive fails with Firewall block error.  If I turn off  'Public' in the firewall I can then share the C drive.  

Seems like this issue has been around on and off for over a year.  How is anyone actually using Docker on Windows with linux containers??  Anyone that is on a company network is NOT in a position to hack corporate security policies!  Messing with registry settings in an attempt to bypass Windows Firewall is NOT an option.

**Comment by avcarrillo** [comment]
J0hnth0m,

I am on a corp network, and agree 100% that messing with the registry to bypass security policies is a bad idea. This needs a permanent fix

**Comment by j0hnth0m** [comment]
FYI... 

Below is from the firewall log when attempting to share the C drive, first with Public turned off and then with Public turned on...

With public turned off (sharing works)...
2018-01-10 11:32:57 ALLOW TCP 10.0.75.2 10.0.75.1 37277 445 0 - 0 0 0 - - - RECEIVE
2018-01-10 11:32:57 ALLOW TCP 10.0.75.2 10.0.75.1 60420 445 0 - 0 0 0 - - - RECEIVE

With public turned on (sharing fails)...
2018-01-10 11:34:34 DROP TCP 10.0.75.2 10.0.75.1 44579 445 60 S 3442798341 0 29200 - - - RECEIVE

The Firewall rule created when installing Docker provides for access from 10.0.75.2 to 10.0.75.1 on TCP/445 for Public, Private and Domain. It appears that this rule is simply not working as expected when Windows Firewall is running on Public.

**Comment by friism** [comment]
@avcarrillo @j0hnth0m if you want, you can try out the new Linux Containers on Windows: https://blog.docker.com/2017/11/docker-for-windows-17-11/

They use a different runtime where bind-mounting volumes does not rely on networking: https://www.youtube.com/watch?v=JZtQnYaO874

**Comment by avcarrillo** [comment]
This is not an option for me. I am running Windows 10 Enterprise version 1607. All updates are managed by our IT dept, and I cannot force to 1709. 

When switching to edge, the Enable Linux Containers on Windows is disabled

**Comment by benzhi2011** [comment]
/lifecycle frozen
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:12:05 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.1
  Git commit:   f150324
  Built:        Wed May  9 22:20:16 2018
  OS/Arch:      linux/amd64
  Experimental: true

**Comment by var23rav** [comment]
When you do Folder sharing(volume mount) with wsl, you may face issue if there is any *vpn connection enabled*.

If you are using *Cisco Any-connect*,

* Allow Local Connection from Preferences
* Or, If you don't have the permission to allow Local Connection or You couldn't see this option
 try Change Docker Network to match any non secure routes of cisco any-connect to avoid this blocking 

Network ranges can be found in 
**Cisco AnyConnects -> click on the settings(gear icon) -> Route Details -> Non-Secure Routes**

Update **Docker -> Settings -> Network -> Subnet addres and Subnet Mask** to match non-secure routes from cisco any-connect

And restart the docker, if required rebuild the image.


![image](https://user-images.githubusercontent.com/7958115/58403279-e4d6e000-807f-11e9-94e0-05a54120449a.png)

**Comment by bdwyertech** [comment]
How can we get the sharing to use the DNS docker.for.win.localhost?  I can connect to whatever that is on port 445 from within a container.

Can we get an option exposed for what DNS or IP to connect to on the Shared Drives page?  Maybe an advanced config button?

**Comment by IonelLupu** [comment]
Still doesn't work. Why it has to be so hard to get things working on Windows??? I just don't get it. I am trying to make docker work on Windows for 6 months and no improvements.

**Comment by stephen-turner** [comment]
This is fixed with the new filesharing implementation in 2.2.0.3, so closing this ticket.

**Comment by avcarrillo** [comment]
Confirmed. Thank you Stephen
