### ISSUE TITLE
Can't start Docker after move the VM to another location different than default

### ISSUE THREAD

**Issue by reypm** [docker/for-win#347]
### Expected behavior
Docker restart successfully
 
### Actual behavior
Docker fails to start

### Information

  - Diagnostic ID: A0BDD173-6099-4B7B-A902-73A9C05DED36/2016-12-20_20-33-06
  - Docker logs (if help): [log.txt](https://github.com/docker/for-win/files/665268/log.txt)
  - Docker Version: 1.12.5 (9503)
  - Channel: Stable
  - OS: Windows 10 Pro
  - Edition: Professional
  - Id: 1607
  - Build: 14393

### Steps to reproduce the behavior

In Windows 10,

1. Stop Docker.
2. Type "Hyper-V Manager" in task-bar search box and run it.
3. Select your PC in the left hand pane
4. Right click on the correct virtual machine, Mine is called MobyLinuxVM
5. Select "Turn off" (If it is running)
6. Right click on it again and select "Move"
7. Follow the prompts

**Comment by jornh** [comment]
Looks like the path is hard-coded in version 1.12.5. Try uninstalling that version and switch to the beta version (or wait for 1.13.0 to come out in January I think). It supports moving the MobyLinuxVM VHD

See this related discussion on the Docker Forum https://forums.docker.com/t/move-mobylinuxvm-vhdx-to-another-drive/26293/2

The error in your log attached above indicates that you moved all of the VM including the .iso DVD it boots from which is actually located in the Docker Program Files install location and moving this I think will still not be supported with version 1.13 either.

**Comment by joyhope** [comment]
After restart the docker, the MobyLinuxVM is recreate in the c:/user/public/ ... .  It eats all my disk C.  I could not do normal working now.  Waiting for it fixed.

**Comment by rneugeba** [comment]
@joyhope as @jornh pointed out this is fixed in the Beta version where there is a settings menu to move the VHDX. Could you try that? This will be rolled into the 1.13 stable release, so I'm closing this issue.

**Comment by JaronrH** [comment]
No need to re-open on just account of me, but I wanted to mention that I too am experiencing this issue (Docker CE 17.06.1-ce-win24 13025).  

I've tried moving the VHDX using Hyper-V's Move and by manually repointing the VHDX, updating the Advanced settings, and using the MobyVhdPathOverride in the config [as mentioned in the linked forum].  In every case but the MobyVhdPathOverride change, it re-created and used c:.  In the MobyVhdPathOverride case, it just failed to start docker.  

I would really like to be able to move this and have good instructions on how to move it at some point in the future.

**Comment by mirsaeedi** [comment]
Still, I have this problem with the newest version (17.12.0-ce-win47).
