### ISSUE TITLE
Docker for Windows stuck at "Starting" inside Parallels VM

### ISSUE THREAD

**Issue by Meligy** [docker/for-win#3479]
After installing Docker (stable or Edge, same), it's stuck in "Starting" phase, then several minutes later shows an error log.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 45589590-A192-495F-A3E4-1F6A8495F519/20190228053608

### Expected behavior

Docker should start normally after install

### Actual behavior

It's stuck in "Starting" phase, then several minutes later shows an error log.

### Information

  - Windows Version: Windows 10 Pro (Version 1809, Build 17763.316)
  - Docker for Windows Version: the attached diagnosis is for Edge 2.0.2.1 but I also tried Stable first (I think 2.0.0.3).

### Steps to reproduce the behavior

  1. Install Windows 10 x64 Pro on Parallels for Mac
  2. Install Docker
  3. Try to start Docker

I'm not sure if Parallels is part of this or not.

### Attempted workarounds

I tried all below with no use, that's why it's a new issue not added to similarly titled issues, because workarounds there were not applicable.

- Removed Docker, and all files in user folder, app data, program files and program data, and all registry values, and environment values
- Ensure Parallels has virtualization on, also turned on PMU virtualization
- Ensured Windows clock is showing correct time (in previous life saw issues in VMs related to that)
- Removed Hyper-V VM and network switch and restarted Docker
- Removed Docker and Hyper-V completely, as well as any Virtual Machine or Hypervisor feature in Windows, then restarting, then reinstalling - along with Windows Containers feature and Windows Subsystem for Linux (were not installed before), then restarting and installing Docker

**Comment by aadamsx** [comment]
I'm trying to get docker to run on Win10 inside Parallels but no dice.  I tried most all the same things you did. Did you ever get this working?

**Comment by sanidhay** [comment]
Having the same issue can;t get Windows Docker working on Mac with Parallells. 
Any luch anyone?

**Comment by lubred** [comment]
You need to **Enable nested Virtualization** on your VM
1. Stop your VM
2. Go to your VM's configuration
3. Hardware ---> CPU & Memory
4. Check Enable nested Virtualization
5. Start your VM and Install Docker.
<img width="676" alt="Screenshot 2020-07-11 at 22 50 09" src="https://user-images.githubusercontent.com/8589225/87234512-7f4fcb00-c3c9-11ea-817f-eb84bc54db61.png">
