### ISSUE TITLE
C521B0B1-00EF-4F68-BE35-DCDA22BC6008/20190228161725

### ISSUE THREAD

**Issue by tulasikr437** [docker/for-win#3480]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C521B0B1-00EF-4F68-BE35-DCDA22BC6008/20190228161725

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ... Unable to mine
  2. ... Unable to start

**Comment by tulasikr437** [comment]
C521B0B1-00EF-4F68-BE35-DCDA22BC6008/20190228161725

**Comment by rebussharma** [comment]
Please provide logs and screenshots. Not everyone can lookup issue with Diag ID
