### ISSUE TITLE
MobyLinuxVM Has No IP Address

### ISSUE THREAD

**Issue by mdeering24** [docker/for-win#3483]
My Docker for Windows and **MobyLinuxVM** start up without any error messages. I am able to create and run containers like docker run -d -p 80:80 nginx and see the default page on localhost.

However, I am attempting to get my company’s app to work on **Docker for Windows** and it is not working. I am getting the HTML content through localhost port 80. But our app uses a separate URL to deliver static content. To get around this for development, on Mac, we have the /etc/hosts redirect a specific URL like **static-company.dev** to the VM IP Address where nginx looks at the URL and gets the appropriate content.

This is not currently possible because **MobyLinuxVM** keeps starting/running without an IP Address assigned to it. How do I get it to have one?

I have tried:
- Restarting Docker
- Restarting my PC
- Fulling deleting Docker and reinstalling

![capture1](https://user-images.githubusercontent.com/22523353/53611185-3c55d480-3b93-11e9-833c-fb7c016a778b.PNG)
![capture2](https://user-images.githubusercontent.com/22523353/53611186-3c55d480-3b93-11e9-96f6-f03ef958981d.PNG)

Steps to reproduce:
- Install Docker for Windows
- Look up MobyLinuxVM

**Comment by guillaumerose** [comment]
Inside the VM, you can reach your host with the special domain name: host.docker.internal.
