### ISSUE TITLE
Download jenkins.war failed with error "The remote name could not be resolved".  

### ISSUE THREAD

**Issue by liangming2003** [docker/for-win#3486]
Following command failed with error "The remote name could not be resolved: 'repo.jenkins-ci.org'.
The war file can be downloaded using the same command on the host machine Windows Server 2016.
How to fix this?

    Invoke-WebRequest -Uri $env:JENKINS_URL -OutFile $env:JENKINS_INSTALL_FILE -UseBasicParsing;

![capture4](https://user-images.githubusercontent.com/13327028/53624591-c5284b00-3c3b-11e9-88c1-b6d2b54d0551.PNG)
![capture2](https://user-images.githubusercontent.com/13327028/53624132-25b68880-3c3a-11e9-8b51-cfe1a50d0806.PNG)
![capture3](https://user-images.githubusercontent.com/13327028/53624133-264f1f00-3c3a-11e9-9f6d-879e0a4ac905.PNG)

dockerfile

FROM openjdk:8-jdk-windowsservercore

 ARG http_port=8080
 ARG agent_port=50000
 ARG JENKINS_VERSION

ENV JENKINS_HOME="c:/jenkins"
ENV JENKINS_INSTALL="c:/jenkins_install"
ENV JENKINS_ENTRY_POINT="${JENKINS_HOME}/jenkins.war"
ENV JENKINS_INSTALL_FILE="${JENKINS_INSTALL}/jenkins.war"
ENV JENKINS_NODE_AGENT_PORT ${agent_port}
ENV JENKINS_VERSION ${JENKINS_VERSION:-2.138.3}
ENV JENKINS_URL="https://repo.jenkins-ci.org/public/org/jenkins-ci/main/jenkins-war/${JENKINS_VERSION}/jenkins-war-${JENKINS_VERSION}.war"
ENV JENKINS_UC="https://updates.jenkins.io"
ENV JENKINS_SHA=953e4dda2d3065284c0016b3e8279e097f830c128b1f712d84780ff2b0751e7d

SHELL ["powershell", "-NoProfile", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; "]

RUN \    
    # Create a Jenkins directory     
    New-Item -ItemType Directory -Force -Path $env:JENKINS_HOME; \
    New-Item -ItemType Directory -Force -Path $env:JENKINS_INSTALL; \
    # Download Jenkins, save it in the Jenkins directory, and verify the SHA hash    
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; \        
    Invoke-WebRequest -Uri $env:JENKINS_URL -OutFile $env:JENKINS_INSTALL_FILE -UseBasicParsing; \
    if ((Get-FileHash -Path $env:JENKINS_INSTALL_FILE -Algorithm SHA256).Hash -ne $env:JENKINS_SHA) { throw 'Download hash does not match'} 

COPY ./scripts "${JENKINS_INSTALL}/scripts"

EXPOSE ${http_port}

EXPOSE ${agent_port}

CMD powershell $env:JENKINS_INSTALL/scripts/startup.ps1

**Comment by Dynom** [comment]
Perhaps this solution works for you as well: https://github.com/Microsoft/dotnet-framework-docker/issues/234#issuecomment-472826168
