### ISSUE TITLE
Uninstall hangs

### ISSUE THREAD

**Issue by jmkgreen** [docker/for-win#349]
### Expected behavior
Product removal

### Actual behavior

Log indicates something had happened, but process stalls.

### Information

See log.txt Gist: https://gist.github.com/jmkgreen/34f386c7ef81f8877f48ad1f2c85c2ca

### Steps to reproduce the behavior

I my case I had accepted an upgrade prompt but that upgrade had hung so after several minutes I rebooted. That was some weeks ago - I am now being prompted again to upgrade which also hangs. So I attempted to uninstall, which - guess - hangs.

And now I have an installation that refuses to leave me.

**Comment by rneugeba** [comment]
@simonferquel could you take a look?

**Comment by simonferquel** [comment]
Can you manually close Docker for windows, and stop the com.docker.service service before uninstalling ?

**Comment by jmkgreen** [comment]
@simonferquel ok did this - the uninstaller "Please wait while Windows configures Docker" progress bar gets further but stops at about 15% complete.

The `install-log.txt`:

```
Version: 1.12.3 (8488)
Channel: Stable
Sha1: d63ec34a49019d2e0b29d7706e57ccfc721ddb8f
Started on: 2017/01/03 12:47:02.891
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1511
Build: 10586
BuildLabName: 10586.672.amd64fre.th2_release_sec.161024-1825
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[12:47:02.846][Installer      ][Info   ] Killing processes...
[12:47:02.911][Installer      ][Info   ] Uninstalling...
[12:47:02.915][HyperV         ][Info   ] Destroy
[12:47:02.916][PowerShell     ][Info   ] Run script with parameters: -Destroy True...
[12:47:05.615][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[12:47:05.616][HyperV         ][Info   ] Destroying Switch DockerNAT...
[12:47:08.366][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[12:47:08.542][HyperV         ][Info   ] Delete VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
[12:47:08.543][Firewall       ][Info   ] Closing ports...
[12:47:10.725][Firewall       ][Info   ] Ports are closed
[12:47:10.726][HyperVGuids    ][Info   ] Removing GUIDs...
[12:47:10.748][HyperVGuids    ][Info   ] GUIDs removed
[12:47:10.748][Installer      ][Info   ] Uninstall completed successfully
```

The process has again hung so I `Cancel` and am left with `Canceling...`. Now off to reboot again as I have no other option.

**Comment by jmkgreen** [comment]
So I've not rebooted and against gone to uninstall Docker. This time I get an estimated time remaining - and this time it swiftly disappears!

Again, `install-log.txt`:

```
Version: 1.12.3 (8488)
Channel: Stable
Sha1: d63ec34a49019d2e0b29d7706e57ccfc721ddb8f
Started on: 2017/01/03 12:59:57.778
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1511
Build: 10586
BuildLabName: 10586.672.amd64fre.th2_release_sec.161024-1825
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[12:59:57.731][Installer      ][Info   ] Killing processes...
[12:59:57.793][Installer      ][Info   ] Uninstalling...
[12:59:57.793][HyperV         ][Info   ] Destroy
[12:59:57.793][PowerShell     ][Info   ] Run script with parameters: -Destroy True...
[13:00:00.462][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[13:00:00.477][HyperV         ][Info   ] Destroying Switch DockerNAT...
[13:00:00.508][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[13:00:00.696][HyperV         ][Info   ] Delete VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
[13:00:00.711][Firewall       ][Info   ] Closing ports...
[13:00:00.992][Firewall       ][Info   ] Ports are closed
[13:00:00.992][HyperVGuids    ][Info   ] Removing GUIDs...
[13:00:00.992][HyperVGuids    ][Info   ] GUIDs removed
[13:00:01.008][Installer      ][Info   ] Uninstall completed successfully
```

Add/Remove Programs no longer lists `Docker` (finally).

**Comment by thedewi** [comment]
I'm having the same problems. To some extent these issues appear to be 7 months old: https://forums.docker.com/t/cannot-uninstall-docker-for-windows/15661

I tried manually removing components as per ebriney's powershell instructions on that thread, although some of the commands were not quite correct. Afterwards I successfully installed the latest version, hoping things would be fixed, but I am once more stuck with a service that won't stop, uninstall, or allow new installations over the top.

**Comment by dlwyatt** [comment]
I've encountered the same problems recently; in my case, the uninstall (or upgrade) hangs when trying to remove the DockerNAT switch from Hyper-V.  I've worked around it by uninstalling Hyper-V, rebooting, then uninstalling / upgrading Docker, and finally reinstalling Hyper-V.  That's annoying, since it involves two reboots, but it's better than nothing.

**Comment by tungmilan** [comment]
I ran in this problem today as well. I have tried disabling Docker startup and services but still couldn't remove it from my Windows 10 Pro 64-bit

![Uninstall hang](https://cloud.githubusercontent.com/assets/6590141/22876108/e6dd4606-f183-11e6-965a-95624b96b2d1.png)

**Comment by Argasm** [comment]
Same here...

**Comment by bhaus** [comment]
Same here... (win10x64)
I got an old docker version (2.0.7135) and i cannot update or uninstall docker. It always hangs at the screen @tungmilan already postet.

**Comment by tlp0308** [comment]
I got same issue
![image](https://cloud.githubusercontent.com/assets/5714735/24230386/752b5402-0fb1-11e7-9754-ed6858971b38.png)

**Comment by jasonbivins** [comment]
Hi @Argasm 
Can you try this script?  Let me know what errors you receive if any

$ErrorActionPreference = "SilentlyContinue"

kill -force -processname 'Docker for Windows', com.docker.db, com.docker.slirp, com.docker.proxy, com.docker.9pdb, moby-diag-dl, dockerd
kill -force -processname com.docker.service

try {
	pushd "C:\Program Files\Docker\Docker\Resources"
    ./MobyLinux.ps1 -Destroy
	popd
} Catch {}

$service = Get-WmiObject -Class Win32_Service -Filter "Name='com.docker.service'"
if ($service) { $service.StopService() }
if ($service) { $service.Delete() }
Start-Sleep -s 5
Remove-Item -Recurse -Force "~/AppData/Local/Docker"
Remove-Item -Recurse -Force "~/AppData/Roaming/Docker"
if (Test-Path "C:\ProgramData\Docker") { takeown.exe /F "C:\ProgramData\Docker" /R /A /D Y }
if (Test-Path "C:\ProgramData\Docker") { icacls "C:\ProgramData\Docker\" /T /C /grant Administrators:F }
Remove-Item -Recurse -Force "C:\ProgramData\Docker"
Remove-Item -Recurse -Force "C:\Program Files\Docker"
Remove-Item -Recurse -Force "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Docker"
Remove-Item -Force "C:\Users\Public\Desktop\Docker for Windows.lnk"
Remove-Item -Recurse -Force "~\.docker"
Remove-Item -Recurse -Force "~\DockerSwarm"
Get-ChildItem HKLM:\software\microsoft\windows\currentversion\uninstall | ForEach-Object {Get-ItemProperty $_.pspath} | Where-Object { $_.DisplayName -eq "Docker" } | Remove-Item -Recurse -Force
Get-ChildItem HKLM:\software\classes\installer\products | ForEach-Object {Get-ItemProperty $_.pspath} | Where-Object { $_.ProductName -eq "Docker" } | Remove-Item -Recurse -Force
Get-Item 'HKLM:\software\Docker Inc.' | Remove-Item -Recurse -Force
# TODO Figure out how to do these properly!
# Get-ItemProperty HKCU:\software\microsoft\windows\currentversion\Run -name "Docker for Windows" | Remove-Item -Recurse -Force
# Get-ItemProperty HKCU:\software\microsoft\windows\currentversion\UFH\SHC | ForEach-Object {Get-ItemProperty $_.PSPath} | Where-Object { $_.ToString().Contains("Docker for Windows.exe") } | Remove-Item -Recurse -Force

# Remove env variables used by docker-machine
Get-Item Env:\COMPOSE_CONVERT_WINDOWS_PATHS | Remove-Item
Get-Item Env:\DOCKER_* | Remove-Item # DOCKER_CERT_PATH, DOCKER_HOST, DOCKER_MACHINE_NAME, DOCKER_TLS_VERIFY

**Comment by kenpavia** [comment]
I was experiencing the system hanging on the "Please wait while Windows configures Docker" window when installing Docker For Windows updates.  I disabled my anti-virus software, and the install finished in a matter of seconds.

**Comment by AlphaGit** [comment]
If anyone comes across this issue again (like me) and wants to try @jasonbivins's script, here's a code-friendly version of it:

```ps1
$ErrorActionPreference = "SilentlyContinue"

kill -force -processname 'Docker for Windows', com.docker.db, com.docker.slirp, com.docker.proxy, com.docker.9pdb, moby-diag-dl, dockerd
kill -force -processname com.docker.service

try {
pushd "C:\Program Files\Docker\Docker\Resources"
./MobyLinux.ps1 -Destroy
popd
} Catch {}

$service = Get-WmiObject -Class Win32_Service -Filter "Name='com.docker.service'"
if ($service) { $service.StopService() }
if ($service) { $service.Delete() }
Start-Sleep -s 5
Remove-Item -Recurse -Force "~/AppData/Local/Docker"
Remove-Item -Recurse -Force "~/AppData/Roaming/Docker"
if (Test-Path "C:\ProgramData\Docker") { takeown.exe /F "C:\ProgramData\Docker" /R /A /D Y }
if (Test-Path "C:\ProgramData\Docker") { icacls "C:\ProgramData\Docker" /T /C /grant Administrators:F }
Remove-Item -Recurse -Force "C:\ProgramData\Docker"
Remove-Item -Recurse -Force "C:\Program Files\Docker"
Remove-Item -Recurse -Force "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Docker"
Remove-Item -Force "C:\Users\Public\Desktop\Docker for Windows.lnk"
Remove-Item -Recurse -Force "~.docker"
Remove-Item -Recurse -Force "~\DockerSwarm"
Get-ChildItem HKLM:\software\microsoft\windows\currentversion\uninstall | ForEach-Object {Get-ItemProperty $_.PSPath} | Where-Object { $_.DisplayName -eq "Docker" } | Remove-Item -Recurse -Force
Get-ChildItem HKLM:\software\classes\installer\products | ForEach-Object {Get-ItemProperty $_.pspath} | Where-Object { $_.ProductName -eq "Docker" } | Remove-Item -Recurse -Force
Get-Item 'HKLM:\software\Docker Inc.' | Remove-Item -Recurse -Force

Get-ItemProperty HKCU:\software\microsoft\windows\currentversion\Run -name "Docker for Windows" | Remove-Item -Recurse -Force
Get-ItemProperty HKCU:\software\microsoft\windows\currentversion\UFH\SHC | ForEach-Object {Get-ItemProperty $_.PSPath} | Where-Object { $_.ToString().Contains("Docker for Windows.exe") } | Remove-Item -Recurse -Force

Get-Item Env:\COMPOSE_CONVERT_WINDOWS_PATHS | Remove-Item
Get-Item Env:\DOCKER_* | Remove-Item # DOCKER_CERT_PATH, DOCKER_HOST, DOCKER_MACHINE_NAME, DOCKER_TLS_VERIFY
```

**Comment by michael4096** [comment]
The issue still exists. My experience...
. all working as expected for over 1 year, stable version, no changes to installation made apart from updates
. an automatic upgrade failed to complete, app uninstall docker fails to complete, new install fails to complete, uninstall of new install fails to complete
. manual cleaning of folders, registry... attempted but no install joy on stable 
. new install of edge (maybe issue found and fixed) appeared to work but installation gave strange, non-repeatable effects such as socket disappearing and reboots required
. an automatic update to windows completely broke docker, vm working but wont connect
. uninstall fails and edge appears to reinstall but docker cli disappears from powershell in user mode - still there in administrator mode (??)
. uninstall fails but tried AlphaGit's script to clean up, needed two attempts and various reboots but stable now seems to install again correctly 17.06.2-ce; however the moby icon still indicating edge version

Makes trying to convince company to adopt docker and become EE member very difficult

**Comment by alexeykuptsov** [comment]
I just experienced this issue with Docker for Windows 17.06.2-ce-win27. Tried @AlphaGit's script as Administrator. And it helped.

**Comment by gaurav-lad** [comment]
![image](https://user-images.githubusercontent.com/10992787/31343437-3eb39aa0-ad2d-11e7-94fe-86b8f698b56e.png)
@thienly, @kenpavia, @tungmilan any success on same??
