### ISSUE TITLE
Docker for windows too slow to respond 

### ISSUE THREAD

**Issue by pewdee** [docker/for-win#3493]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3B4A9BC0-9684-4FD2-846C-D7294C4074FE/20190302171935

### Expected behavior

Docker run commands 

### Actual behavior

Docker stops respond for a while when I run commands, even base commands like "docker images -a"

### Information

  - Windows Version: Microsoft Windows [versão 10.0.17134.590]
  - Docker for Windows Version: Community Version 2.0.0.3 (31259)

**Comment by thernstig** [comment]
@pewdee Could it be related to this? https://github.com/docker/for-win/issues/1936

Please upvote that one if so.

**Comment by stephen-turner** [comment]
First check what else is running on your machine.

**Comment by ardalon** [comment]
@pewdee  Have you tried turning off "Send usage statistics" under Settings -> General in the Docker Desktop GUI ?  I went from 5+ seconds of waiting for a simple "docker images", "docker ps -a" to under 1 second!  It seems the send usage statistics is enabled by default.
