### ISSUE TITLE
Docker fails to start: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by inponomarev** [docker/for-win#3494]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 09B54813-A515-4907-B4BD-D0F54874FC14/20190303000032

### Expected behavior

Docker starts.

### Actual behavior

'Docker failed to initialize' window

### Information

  - Windows Version: Windows 10
  - Docker for Windows Version: 2.0.0.3

### Steps to reproduce the behavior

Docker fails to start after a new SSD has been installed on my machine.

**Comment by alpmarangoz** [comment]
Solution given by @simonferquel [here ](https://github.com/docker/for-win/issues/464 ) solved my problem.

**Comment by inponomarev** [comment]
Yes, deletion of %userprofile%\Roaming\Docker\ helped.

**Comment by peterhorsley** [comment]
Also worked for me, note path was: %userprofile%\AppData\Roaming\Docker

**Comment by wpjchris** [comment]
me too
