### ISSUE TITLE
how to deploy locally built images to kubernetes?

### ISSUE THREAD

**Issue by geogeim** [docker/for-win#3495]
The documentation is not clear how to deploy locally built images to the kubernetes instance that comes with docker for windows. I tried directly referencing the image name from kubernetes deploy configuration and then added it with `kubectl create -f deploy.yaml` but i get `Failed to pull image "5d1fe335608f": rpc error: code = Unknown desc = Error response from daemon: pull access denied for 5d1fe335608f, repository does not exist or may require 'docker login`

Do i need to install a local docker registry for kubernetes?

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:
```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 Kubernetes:
  Version:          v1.10.11
  StackAPI:         v1beta2

```

**Comment by guillaumerose** [comment]
Be sure to use the pull policy IfNotPresent and use the image name as you would do with docker run.

**Comment by geogeim** [comment]
i figured it out:  `imagePullPolicy: Never` fixed it.
