### ISSUE TITLE
The run -v don't work in Win10

### ISSUE THREAD

**Issue by ndj888** [docker/for-win#35]
I use "docker run -v" mount windows folder  , it's successful ,but I ls the Dir , it's empty.
This is my docker for Win10 version and docker info :
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      linux/amd64

Containers: 15
 Running: 1
 Paused: 0
 Stopped: 14
Images: 34
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 103
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.95 GiB
Name: moby
ID: HCJB:ANCS:IOQE:NRMO:NHJR:7VWF:XEGA:QS6E:5YDE:JXNQ:K6CM:A7OW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

Docker client for windows used this config:
The setting option , Shared Drives table select c: d: and input my user password.
II am very confused, hope to get your help, thank you.

**Comment by ndj888** [comment]
I to close RAV  try , but problem is not solved.

**Comment by gcristofol** [comment]
Same here, 
A diagnostic was uploaded with id: 06AA63FB-3E00-4EEC-ADC1-74042CE4B7AA/2016-08-11_17-34-57

**Comment by rneugeba** [comment]
Thanks for the reports. We discovered an issue with how we handle passwords and some passwords with some non alphanumeric characters won't work (examples characters are `;`, `"`, `,`, `*`). If your password contained some of these, the sharing may not work. 

Do you have some of these special characters in your password?

We do have a fix for this and will push it out on the beta channel as Beta22 very soon (hopefully later today). It would be great if you could test it then.

**Comment by ndj888** [comment]
Yes, I am so happy to test the new version,Some suggestions, but don't know is properly. 
My PC using WIN10 system and using Microsoft user to login , win8 ago us to local user to login system , look ,it's differently.

**Comment by ndj888** [comment]
@rneugeba My password is easy, Oh , using capital letter , so maybe is another problem.

**Comment by friism** [comment]
The fix to address the password bug was pushed today, please update to the latest beta: https://download.docker.com/win/beta/1.12.0.6313/NOTES

**Comment by ndj888** [comment]
@friism Can't download the beta.

**Comment by rneugeba** [comment]
@ndj888 apologies, but we had to pull the beta22 because some users experienced issues with the update process. It'll be live once we fixed it.

**Comment by rneugeba** [comment]
The beta is now out and downloadable from https://download.docker.com/win/beta/InstallDocker.msi

It would great if you could try it and let us know if it fixed your issue.

Thanks
Rolf

**Comment by rneugeba** [comment]
Closing this issue as there has been no update for 15 days. I assume the update to Beta24 fixed the issue. If not, feel free to re-open with another diag report.
Tahnsk
