### ISSUE TITLE
New installation of docker fails to start

### ISSUE THREAD

**Issue by worldspawn** [docker/for-win#3512]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 0CBB0391-355F-479B-B005-11051ADDD215/20190306103922

### Expected behavior
Docker starts and informs me "docker is running"

### Actual behavior
Docker does not start. "Docker is starting" is shown and then after quite a while a crash window appears.

### Information
I am trying to start docker for windows inside a windows 10 vm hosted on a windows 10 host machine. (Win10 -> Win10 -> Docker).

Its set to use linux containers.

I have tried reinstalling hyper-v/containers and docker both stable and edge. This is an hours old windows 10 pro installation (unactivated) version 1809 (17763.253). It has a couple of other things installed (vs community edition, jetbrains rider and cmdr).

While docker is _starting_ I see the VM appear in the hyper-v manager however it has no *status* and it little display window is just grey. If I attempt to connect to it, it fails.

A side issue seems to be the tray client becomes confused after I close the crash window and believes docker is running (while no vm is running). 

  - Windows Version:1809 (17763.253)
  - Docker for Windows Version: 2.0.3.0 (31778) - Edge

### Steps to reproduce the behavior
Not sure if relevant but the first time I ran docker for windows hyper-v/containers were not enabled so it enabled them then rebooted. Then after the reboot it failed to start because I hadn't enabled virtualisation on the vm. The vm was then shutdown, virtualisation was enabled and then the vm was started, at which I point I became stuck on this error.

**Comment by ebriney** [comment]
Hi @worldspawn I see in the diagnostics that `VirtualizationFirmwareEnabled` is false, did you enable virtualization in your BIOS?

see https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization

**Comment by worldspawn** [comment]
Hi @ebriney 

I ran `Set-VMProcessor -VMName Synotive -ExposeVirtualizationExtensions $true` on the host machine.

![image](https://user-images.githubusercontent.com/819581/53878278-8e00d200-405f-11e9-8604-51d45bc69ba6.png)

**Comment by worldspawn** [comment]
I've just created a new VM this time with no other items installed. Process was 
- Define VM
- Set Vms processor count to 4
- Set Vm's virtualisation to enabled
- Install windows 10
- Enabled Hyper-V and Containers
- Restart
- Install Docker
- Run docker... fail

**Comment by ebriney** [comment]
`Set-VMProcessor -VMName Synotive -ExposeVirtualizationExtensions $true` exposes nested virt in a vm.
`Get-WmiObject Win32_Processor | fl *` should gives you `VirtualizationFirmwareEnabled`
I check your new diagnostics.
In the previous ones I didn't see any logs from the vm.

**Comment by ebriney** [comment]
Are you trying to run `Docker Desktop` in a vm?

**Comment by worldspawn** [comment]
> Are you trying to run `Docker Desktop` in a vm?

Yep

**Comment by ebriney** [comment]
Sorry, I just saw it in the comment.
It is not always working but something it does and we don't officially support/test/recommend it.
Which kind of machine do you use to host your vm?
Why do you need to run it in nested virt?

**Comment by worldspawn** [comment]
I like to keep my host machine clean for important stuff like Xcom2 and Battlefield :)

The host machine has 6 cores hyper-threaded and 32gb ram. I gave the vm 6 logical cores and 20gb ram.

**Comment by ebriney** [comment]
And on your host machine?

**Comment by worldspawn** [comment]
Its also `false` on my host machine. I just rebooted, checked the bios and its on. Task manager is also reporting the virtualisation is enabled. Plus I created a windows 10 vm and can start it up and connect to it.

**Comment by worldspawn** [comment]
I could upload you the VM? Its just an unactivated windows install

**Comment by ebriney** [comment]
No, it's host specific.
I just created a fresh win10 18.09 vm, gen3, Default Switch with ExposeVirtualizationExtensions  on one our ci machine and installed the latest edge version from hub.

It starts and I can launch a container...

Do you have heavy load on your host? Because Hyper-V is stuck if you don't have enough CPU to start the vm in nested virt and Docker Desktop do a time out.

NB: I have `VirtualizationFirmwareEnabled` to false on all my machines and virtualization activated in the bios, so it's not an issue.

**Comment by ebriney** [comment]
`(Get-VM -Name Synotive).VMIntegrationService` do you have `Time Synchronization` enabled?

**Comment by worldspawn** [comment]
Hi @ebriney. Sorry i had to sleep. Time Synchonrization is enabled and my host is pretty much idle. I tried giving the vm more cores (8) but I'm still stuck with the same problem.

**Comment by worldspawn** [comment]
So I hadn't installed the October windows update on the host pc. This meant the configuration version of my vm was 8.3 (or 8.5). The vm itself was up to date and mobylinuxvm was being loaded as v9.0.

So I installed the update on the host and upgraded the vm configuration to 9.0 and voila! Docker party!!!

Thanks for your help trouble shooting this @ebriney 👍
