### ISSUE TITLE
Docker Desktop Issue

### ISSUE THREAD

**Issue by MoisesQ** [docker/for-win#3515]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by PavelSosin** [comment]
The latest available version in repository according choco:
docker-desktop v2.0.3.0-edge is the latest version available based on your source(s).
This version was corrupted. How to repair the current version or upgrade to v2.0.4.0 promised or how to  rollback to previous? It looks like the latest installer tries to install v2.0.3.0 again.
