### ISSUE TITLE
Docker Desktop fails to start

### ISSUE THREAD

**Issue by thomasmarti** [docker/for-win#3520]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 1D7BF828-A314-477E-BABD-FCF47FB7F5F4/20190307083443

### Expected behavior
Docker Deskto ist starting in a few seconds

### Actual behavior
Docker does not start and fail to start the V-Machine 'MobyLinuxVM'
The Problem started to occur a few days ago

### Information
  - Windows Version:
  - Docker for Windows Version:

### Error
[14:59:06.906][HyperV         ][Info   ] Attach Docker ISO C:\Program Files\Docker\Docker\Resources\docker.iso
[15:09:11.684][Linux          ][Error  ] Failed to start: Unable to start: Der ausgeführte Befehl wurde beendet, da die Einstellungsvariable "ErrorActionPreference" oder ein allgemeiner Parameter auf "Stop" festgelegt ist: Fehler beim Starten von "MobyLinuxVM".

Fehler beim Starten von "MobyLinuxVM" (ID des virtuellen Computers C099695C-EF17-430B-995F-FC553FD26C96).

"MobyLinuxVM": Fehler beim Starten des Arbeitsprozesses: In der Endpunktzuordnung sind keine weiteren Endpunkte verfügbar. (0x800706D9) (ID des virtuellen Computers C099695C-EF17-430B-995F-FC553FD26C96)..
bei Start-MobyLinuxVM, <Keine Datei>: Zeile 296

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by clue1967** [comment]
I am running into the same problem. Seeing 'VM MobyLinuxVM does not exist' in the logs.
This happened after my win 10 machine installed the latest windows updates yesterday. Reinstall of docker desktop didn't help. 
Diagnostics ID: 2B4C03EE-58E8-4C6F-8727-57DA8D0479B4/20190307160632
