### ISSUE TITLE
Incompatible with vmware in windows 10 system because started Hyper-V

### ISSUE THREAD

**Issue by ThinWonton** [docker/for-win#3524]
windows docker version : 2.0.2
As we know, docker uses Hyper-V for implementing virtualization in windows 10. However,  when i  installed virtual box or vmware in my system,  the other virtualization container works not fine. It seems that Hyper-V is incompatible with vmware . What should I do to solve the problem？

thanks.

**Comment by TaeckSeung** [comment]
Its only one Hypervisor allowed in Windows 10, You need to decide what to use for Virtualization.
But, luckily, the other option is able to use.
`Docker toolbox for Windows`(https://download.docker.com/win/stable/DockerToolbox.exe), its implementing Vmware Player, so you can solve this problem in this way.

**Comment by stephen-turner** [comment]
Unfortunately this is a Hyper-V restriction, and is out of our control.
