### ISSUE TITLE
An Error Occurred After changes in Hyper-V config

### ISSUE THREAD

**Issue by mesadhan** [docker/for-win#3527]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: C97EE787-FE44-4E6C-8B30-10ED88C245F7/20190308170342

### Expected behavior

After  changes in `Turn Windows features on or off` with below configuraiton Docker should start
    1. Checked Hyper-V (Hyper-v Management Tools and Hpyer-V platform Both options)
    2. And checked Windows Hpyervisor Platform Option

### Actual behavior

`An Error Occurred`
Hardware assisted virtualization and data execution protection must be enabled in the BIOS. 
See https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization-must-be-enabled

### Information

  - Windows Version: Windows 10 x64 Pro.
  - Docker for Windows Version: 2.0.0.3 (31259)
 - Machine RAM: 16 GB
 - MotherBoard: G1.Sniper Z97
 - CPU: Intel Core i7-4790K

### Steps to reproduce the behavior

First time Docker working properly but when I install Emulator and third-party virtualization application like (Android Studio Emulator and VMware Workstation then Problem Occurred).

1. To Runing VMware Workstation 15, I need to changes in `Turn Windows features on or off`
    1. Unchecked Hyper-V (Hyper-v Management Tools and Hpyer-V platform Both options)
    2. And checked Windows Hpyervisor Platform Option

After that, VMware and Android Studio Emulator runing and working properly.

2.  To working with docker again, Install Docker with changes in `Turn Windows features on or off`
    1. Checked Hyper-V (Hyper-v Management Tools and Hpyer-V platform Both options)
    2. And checked Windows Hpyervisor Platform Option

This time docker throw below issue but other Virtualilistion software working properly.

`An Error Occurred`
Hardware assisted virtualization and data execution protection must be enabled in the BIOS. 
See https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization-must-be-enabled

**Comment by sorenbache** [comment]
I have the exact same issue. Is there any workaround? I have tried to uninstall Docker and install again, but that does not seem to help.
