### ISSUE TITLE
add kubernetes to linux containers on windows (LCOW)

### ISSUE THREAD

**Issue by OneCyrus** [docker/for-win#3533]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Kubernetes should be available when running in windows container mode (LCOW).

### Actual behavior
At the moment we can enable Kubernetes only when using linux container mode on Windows but not when in Windows mode. With LCOW we should be able to run Linux containers in Windows mode too.

### Information

  - Windows Version: 1809
  - Docker for Windows Version: 2.0.3.0

**Comment by bvandehey** [comment]
This was closed due to inactivity but is this feature to add kubernetes support for Docker running in LCOW mode still something being considered?
