### ISSUE TITLE
An unexpected error occurred: Logon failure: the user has not been granted the requested logon type at this computer. (0x80070569).

### ISSUE THREAD

**Issue by dbsanfte** [docker/for-win#3542]
Docker for Windows crashing on startup with a Powershell error. If I restart the WMI service it will finally succeed:

> An unexpected error occurred: Logon failure: the user has not been granted the requested logon type at this computer. (0x80070569).

Crash dump ID is 758E0118-CC59-45C1-B59D-04F8D7F57200/20190311083200.

**Comment by Fabrice-Deshayes-aka-Xtream** [comment]
I've the same problem here. 
- Win 10 1809
- Docker Desktop
  - Version 2.0.0.3 (31259)
  - Channel: stable
  - Build: 8858db3

**Comment by CCGPaul** [comment]
Same issue here. Have added user to docker-users but it still does this

Log B540725F-4F3B-4C5E-96F9-66E11A52B9E6/20190508093708

**Comment by mctunes** [comment]
/remove-lifecycle stale

Still happening.

**Comment by yusufhilmi** [comment]
I got the same issue 

`
The operation failed.

The Hyper-V Virtual Machine Management service encountered an unexpected error: Logon failure: the user has not been granted the requested logon type at this computer. (0x80070569).
at New-MobyLinuxVM, <No file>: line 397
at New-MobyLinux, <No file>: line 182
at <ScriptBlock>, <No file>: line 810

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoRestartVM(Settings previousSettings)
   at Docker.Actions.<>c__DisplayClass34_0.<RestartVM>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()`

**Comment by borondy** [comment]
Got the same issue, restarting the Windows Management Instrumentation service solved the issue. 
Note: you may need to start the Services.msc as an administrator.

**Comment by mateusz-kozub** [comment]
@borondy Thanks, worked for me.

**Comment by mctunes** [comment]
It's great that restarting a service or two manually resolves the issue temporarily, but there appears to be an underlying problem here that is causing Docker to crash randomly, sometimes at start-up, sometimes after running for hours, and restarting a service is only puts a band-aid on the problem until it happens again.

I really hope this issue can be reopened and looked into, because for me at least, Docker for Windows is unusable.

**Comment by panuhorsmalahti** [comment]
I'm getting this. I fixed it by restarting 'Hyper-V Host Compute Service' in Services

**Comment by KoenBal** [comment]
> I've the same problem here.
> If I restart the hyperV service, quit docker desktop and restart it, it works.
> Diagnostic id : B70DF673-C29E-4AEC-999D-84F5ED5D8487/20190320090656

I could not find a hyperV service only a Hyper-V-... process.
I turned it off. Started docker desktop again as admin and now Docker is running.

**Comment by mikhey** [comment]
> 
> 
> Got the same issue, restarting the Windows Management Instrumentation service solved the issue.
> Note: you may need to start the Services.msc as an administrator.

Just encountered this issue.  I wonder if it could be related to putting the machine to sleep.

**Comment by tenortim** [comment]
I just hit this. Docker Desktop was running fine. It wanted to update so I let it. It failed to start up with this error. Restarting the Hyper-V Virtual Machine Management (vmms) service worked around the problem. There's no need to restart WMI; that's a very large hammer (restarts a lot of other unaffected services).

**Comment by StanChmielewski** [comment]
This same here. It is happening almost every time after machine restart.

**Comment by julianonunes** [comment]
> I'm getting this. I fixed it by restarting 'Hyper-V Host Compute Service' in Services

Did this and it started working fine.
