### ISSUE TITLE
Port 2375 not listening

### ISSUE THREAD

**Issue by malejpavouk** [docker/for-win#3546]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 79B915F4-D567-466F-8A8A-5C79E4DF5581/20190311171810

### Expected behavior
Once "Expose deamon on tcp://localhost:2375 without TLS" is clicked, I am able to access the port on port 2375 either using "telnet localhost 2375", docker client or "docker -H tcp://localhost:2375 ps". The port 2375 is visible as listening in netstat

### Actual behavior
None of the above mentioned is possible, the port is not listening in netstat

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false

Windows version: 10.0.17763

**Comment by mxl** [comment]
I had the same issue. By some reason Windows reserves port 2375:

```
netsh interface ipv4 show excludedportrange protocol=tcp
```

If you see that one of port ranges include port 2375 then you have the same issue.

Disable Hyper-V and reboot:

```
dism.exe /Online /Disable-Feature:Microsoft-Hyper-V
```

Then reserve port 2375:

```
netsh int ipv4 add excludedportrange protocol=tcp startport=2375 numberofports=1
```

Enable Hyper-V and reboot again:

```
dism.exe /Online /Enable-Feature:Microsoft-Hyper-V /All
```

Now it should be fine.

**Comment by romainprevost** [comment]
Thank you so much @mxl reserving port 2375 works perfectly for me!

**Comment by polar9527** [comment]
Thanks! It works for me!!!

> I had the same issue. By some reason Windows reserves port 2375:
> 
> ```
> netsh interface ipv4 show excludedportrange protocol=tcp
> ```
> 
> If you see that one of port ranges include port 2375 then you have the same issue.
> 
> Disable Hyper-V and reboot:
> 
> ```
> dism.exe /Online /Disable-Feature:Microsoft-Hyper-V
> ```
> 
> Then reserve port 2375:
> 
> ```
> netsh int ipv4 add excludedportrange protocol=tcp startport=2375 numberofports=1
> ```
> 
> Enable Hyper-V and reboot again:
> 
> ```
> dism.exe /Online /Enable-Feature:Microsoft-Hyper-V /All
> ```
> 
> Now it should be fine.
> 
> Also see [this thread](https://github.com/docker/for-win/issues/3171#issuecomment-459205576) where I found this solution.

Thanks, it works for me!!!

**Comment by zloykolobok** [comment]
> I had the same issue. By some reason Windows reserves port 2375:
> 
> ```
> netsh interface ipv4 show excludedportrange protocol=tcp
> ```
> 
> If you see that one of port ranges include port 2375 then you have the same issue.
> 
> Disable Hyper-V and reboot:
> 
> ```
> dism.exe /Online /Disable-Feature:Microsoft-Hyper-V
> ```
> 
> Then reserve port 2375:
> 
> ```
> netsh int ipv4 add excludedportrange protocol=tcp startport=2375 numberofports=1
> ```
> 
> Enable Hyper-V and reboot again:
> 
> ```
> dism.exe /Online /Enable-Feature:Microsoft-Hyper-V /All
> ```
> 
> Now it should be fine.
> 
> Also see [this thread](https://github.com/docker/for-win/issues/3171#issuecomment-459205576) where I found this solution.

Thanks, It works for me!!!

**Comment by dkocich** [comment]
I can't connect to 2375 with Intellij Docker plugin but `netsh interface ipv4 show excludedportrange protocol=tcp` do not list that the port is blocked (same with `netstat -aon | find /i "listening"`) but I still can't connect to it for some reason

**Comment by waylaidwanderer** [comment]
@dkocich I had the same experience, but in my case (Docker for Windows + WSL 2) all I had to do was execute `netsh int ipv4 add excludedportrange protocol=tcp startport=2375 numberofports=1` and reboot to get it to work.

**Comment by debuglevel** [comment]
Docker Installer and/or Dashboard should include some checks to prevent this problem.

Anybody knows why that port range is reserved?
