### ISSUE TITLE
Docker for Windows Installer doesn't set "Windows containers" mode

### ISSUE THREAD

**Issue by AArnott** [docker/for-win#3547]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: ACD3A501-EF79-4C7D-851E-6EE19D22607F/20190311153333

During the installation, I am offered a checkbox to put Docker into "Windows container" mode, which I checked:

![image](https://user-images.githubusercontent.com/3548/54161675-23111b80-4410-11e9-9b34-4e7a20f7ecbf.png)

### Expected behavior

Docker runs with Windows containers

### Actual behavior

After install, I launch Docker, and see that it's in Linux container mode in spite of my selection during installation. I have to manually switch it to Windows containers mode:

![image](https://user-images.githubusercontent.com/3548/54161705-36bc8200-4410-11e9-8839-5da3ac5dfa3b.png)

### Information

Yes, this reproduces. I've installed Docker twice and this reproduced.

  - Windows Version: Windows 10 1809
  - Docker for Windows Version: Docker Desktop for Windows 2.0.0.3

**Comment by edrickwong** [comment]
+1

**Comment by AArnott** [comment]
@edrickwong tip: use the "thumbs up" reaction on the issue instead of your "+1" comment, since it sums up with other votes so the project owners can readily see how many votes there are for a given issue.

**Comment by diablodale** [comment]
reproduced same behavior today
same repo steps, same expected, same actual
on...
Windows 10 Pro 1903 (10.0.18362.175)

**Comment by AArnott** [comment]
This seems to have been fixed in a recent build.
