### ISSUE TITLE
Docker TLS handshake error 

### ISSUE THREAD

**Issue by RahulKanvinde** [docker/for-win#3550]
I am using a proxy server to get access to load docker images. The docker version is 18.03.0-ce.
I get the following error:

Error response from daemon: Get https://registry-1.docker.io/v2/: proxyconnect tcp: tls: first record does not look like a TLS handshake.

My system:

Docker version 18.03.0-ce., build 0520e24302
Windows 7 OS 64 bit

**Comment by thedevd** [comment]
I am also getting the similar kind of exception when trying to pull docker images in windows docker (It is so frustrating) - 

Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: TLS handshake timeout

**Comment by bduman** [comment]
+1 same issue. Also docker behind proxy.
