### ISSUE TITLE
Docker Desktop  for windows installer fails to upgrade - always shows up-to-date message 

### ISSUE THREAD

**Issue by PavelSosin** [docker/for-win#3552]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [X ] I have uploaded Diagnostics
  - Diagnostics ID: - see screenshots

### Expected behavior
It should be possible to continue installation regardless which version has been installed for downgrade and **repair** purposes
### Actual behavior
If "version up-to-date" message appears during installation then installation is stopped deliberately because only "Close" option is available. Supposedly, either new installation manifest is wrong or old one processed incorrectly 
### Information

  - Windows Version: 10 with  Hyper-V enabled
  - Docker for Windows Version: 2.0.30 desired
### Steps to reproduce the behavior

  1. download edge release once and got "up-to-date message during installation
  2. ...download edge release second time and got the same message
<img width="530" alt="Up-to-Date" src="https://user-images.githubusercontent.com/21080596/54187946-55298880-44b7-11e9-81cd-2fc0aacf6304.PNG">
<img width="530" alt="Up-to-Date2" src="https://user-images.githubusercontent.com/21080596/54187947-55298880-44b7-11e9-8039-39b398dbcdc9.PNG">

**Comment by ulrich** [comment]
Thank you for your feedback Pavel,

I can't reproduce this issue. Can you use a newer version of Docker Desktop, there is the 2.0.0.4 version available?

**Comment by PavelSosin** [comment]
I just tried to install Docker desktop using chocolatery  but it failed too:
=================================================

Diagnostics:
Installing the following packages:
docker-for-windows
By installing you accept licenses for the packages.
Progress: Downloading docker-desktop 2.0.3.0-edge... 100%
Progress: Downloading docker-for-windows 99.0.0.0... 100%
docker-for-windows not installed. An error occurred during installation:
 Access to the path 'C:\ProgramData\chocolatey\lib\docker-desktop\tools' is denied.
docker-for-windows package files install completed. Performing other installation steps.
The install of docker-for-windows was NOT successful.
docker-for-windows not installed. An error occurred during installation:
 Access to the path 'C:\ProgramData\chocolatey\lib\docker-desktop\tools' is denied.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - docker-for-windows (exited 1) - docker-for-windows not installed. An error occurred during installation:
 Access to the path 'C:\ProgramData\chocolatey\lib\docker-desktop\tools' is denied.
====================== Please, take into account that folder attributed ca be set externally by IT on corporate computers
=========================================================
Finally, I succeeded to run   chocolatery installation and got the attached log
Is it OK?
[dockerInst.log](https://github.com/docker/for-win/files/2957344/dockerInst.log)

**Comment by PavelSosin** [comment]
Please, deprecate installer and installation procedure based on installer ASAP.  Entire procedure is extremely dangerous and down't satisfy basic security and automation requirements. It involves:

- Downloading exe file from Internet
- Manual execution of exe file from arbitrary folder which is not included into continue scan list
- No certified installation script ( operator ) provided

- [ ] 

- [ ] Manual 

- [ ]

**Comment by PavelSosin** [comment]
I tried to upgrade using choco upgrade but the issue persists:
Upgrading the following packages:
Upgrading the following packages:
docker-for-windows
 - docker-for-windows - docker-for-windows v99.0.0.0 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.

**Comment by PavelSosin** [comment]
Yet another argument to use certified Operator script: if installation requires Administrator privileges script should ask Admin password. on computers provided by enterprise IT   security attributes of some folders can be managed by IT without possibility to override. I can run cmd or PowerShell as administrator but I can't promise that some script is run with administrator privileged if this script is not known  to our IT which is "main" installer and supply "pre-installed" computer If they have to supply 200 personal computers they cant rely on developers' skills. Cloud assumes automation, automation, automation.   
Access to the path 'C:\ProgramData\chocolatey\lib\docker-for-windows\docker-for-windows.nupkg' is denied.

**Comment by PavelSosin** [comment]
Information about v2.0.0.4 is incorrect:
clist --download-cache-only --not-broken --exact docker-desktop returns 
                  docker-desktop 2.0.0.3 [Approved] Downloads cached for licensed users
What is your repository exact URL?

**Comment by PavelSosin** [comment]
Finally - this version of Docker Desktop for Windows works:
Version 2.0.0.3 (31259)
Channel: stable
Build: 8858db3
