### ISSUE TITLE
Docker stopped working after upgrading to Windows 10 1803  Initial Response

### ISSUE THREAD

**Issue by JasmineB1995** [docker/for-win#3554]
•	Which version of dockers are you using: Community or Enterprise Edition? - Community
•	Is this a brand new installation? – No. My user who reported the issue have been using it for some time.
•	Name and edition of the product – 
 
•	Output from “Docker version” and “Docker info” 
•	Microsoft Windows [Version 10.0.17134.619]
•	(c) 2018 Microsoft Corporation. All rights reserved.
•	
•	C:\WINDOWS\system32>docker version
•	Client: Docker Engine - Community
•	Version:           18.09.2
•	API version:       1.39
•	Go version:        go1.10.8
•	Git commit:        6247962
•	Built:             Sun Feb 10 04:12:31 2019
•	OS/Arch:           windows/amd64
•	Experimental:      false
•	error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
•	
•	C:\WINDOWS\system32>
C:\WINDOWS\system32>docker info
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
C:\WINDOWS\system32>
•	
•	Reproducible steps if available: Just open a command prompt and run docker PS or any other command. 
•	Full Error message (including docker command)
 
•	When this happened: After upgrading machine from 1703 to 1803.
•	Docker installation on machine

**Comment by LeonardAB** [comment]
Related to #1927
