### ISSUE TITLE
k8_etcd not starting within employers network, kubernetes not operable

### ISSUE THREAD

**Issue by jjfraney** [docker/for-win#3564]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 7FCB1943-58A4-4FE3-B9A5-09690C1D4740/20190313112944

### Expected behavior
kubernetes api server starts

### Actual behavior
kubernetes api server exits

### Information

Ultimately, why isn't k8s_etcd  container running when my laptop connected into my employer's network?

K8s starts fine using my home network.  It fails to start when operating within my employer's corporate network.  

In the fail case, I see this message in api server logs, then the api server exits, and does not reappear in 'docker ps' output again.
`F0313 14:52:30.889214       1 storage_decorator.go:57] Unable to create storage backend: config (&{ /registry [https://127.0.0.1:2379] /run/config/pki/apiserver-etcd-client.key /run/config/pki/apiserver-etcd-client.crt /run/config/pki/etcd/ca.crt true false 1000 0xc4205fbd00 <nil> 5m0s 1m0s}), err (dial tcp **127.0.0.1:2379: getsockopt: connection refused**)
`

My web searches tell me the above error means that api server cannot reach etcd.

In the fail case, the k8s_etcd container is not running.  I confirm this with a 'docker ps' and look at output.  The full docker ps output is attached.
[dockerps.txt](https://github.com/docker/for-win/files/2962488/dockerps.txt)
  
I cannot confirm whether etcd started and exited, or simply could not start.  Its life is too short for me to capture a log.

I assume the api server exits and does not recover when etcd is not available.  (I'm too much of a newbie to be sure.)

This [comment ](https://github.com/docker/for-win/issues/1649#issuecomment-364628494) in a similar issue says the vpnkit port may need to be opened.  The powershell command in that comment does not show a rule.  I didn't get the popup to open the firewall port, as mentioned in this [comment](https://github.com/docker/for-win/issues/1649#issuecomment-376190399).  My corporate security is pretty tight about accessing the control panel for firewall rules.  So, if you suspect this as root cause, I need a bit more evidence that the port is closed.

This [comment ](https://github.com/docker/for-win/issues/1649#issuecomment-465987763)in the same issue seems to be a read herring for my case.  I don't know how the KUBECONFIG file could affect the etcd container.

In case its useful, the full logs of api server:
`docker logs c6fc2e0c424e
Flag --admission-control has been deprecated, Use --enable-admission-plugins or --disable-admission-plugins instead. Will be removed in a future version.
Flag --insecure-port has been deprecated, This flag will be removed in a future version.
I0313 14:52:10.394949       1 server.go:135] Version: v1.10.11
I0313 14:52:10.395025       1 server.go:724] external host was not specified, using 192.168.65.3
I0313 14:52:10.885900       1 feature_gate.go:190] feature gates: map[Initializers:true]
I0313 14:52:10.886070       1 initialization.go:90] enabled Initializers feature as part of admission plugin setup
I0313 14:52:10.886504       1 plugins.go:149] Loaded 10 admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,DefaultTolerationSeconds,DefaultStorageClass,MutatingAdmissionWebhook,Initializers,ValidatingAdmissionWebhook,ResourceQuota.
I0313 14:52:10.887294       1 plugins.go:149] Loaded 10 admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,DefaultTolerationSeconds,DefaultStorageClass,MutatingAdmissionWebhook,Initializers,ValidatingAdmissionWebhook,ResourceQuota.
F0313 14:52:30.889214       1 storage_decorator.go:57] Unable to create storage backend: config (&{ /registry [https://127.0.0.1:2379] /run/config/pki/apiserver-etcd-client.key /run/config/pki/apiserver-etcd-client.crt /run/config/pki/etcd/ca.crt true false 1000 0xc4205fbd00 <nil> 5m0s 1m0s}), err (dial tcp 127.0.0.1:2379: getsockopt: connection refused)`

The problem is likely not easily producible until I know what causes it.

The problem may be new or not.  I do not know.

The problem did not appear with an update, as a regression.

  - Windows Version:  Microsoft Windows 10 Enterprise, 1709
  - Docker for Windows Version:  Community, Version 2.0.0.3 (31259), Channel: stable, Build: 8858db3

### Steps to reproduce the behavior

  1. Come into my employers' office, in NJ.  I know, not practical.
  2.  ....

**Comment by IkkertSergei** [comment]
I'm running into the same problem as jjfraney. Wanted to test the integration of Kübernetes under Windows unfortunately without success. Docker for Windows freezes in the message: Kübernetes is Starting. 

![image](https://user-images.githubusercontent.com/44962481/58104259-c9358a80-7be4-11e9-8909-a95fd172f001.png)

There is always an attempt to start a k8s_kube-apiserver container, which gets off with the following messages:

```
Flag --admission-control has been deprecated, Use --enable-admission-plugins or --disable-admission-plugins instead. Will be removed in a future version.                                                                        Flag --insecure-port has been deprecated, This flag will be removed in a future version.
I0521 13:56:09.918898       1 server.go:135] Version: v1.10.11                                                                                                                                                                   I0521 13:56:09.919022       1 server.go:724] external host was not specified, using 192.168.65.3
I0521 13:56:10.709868       1 feature_gate.go:190] feature gates: map[Initializers:true]                                                                                                                                         I0521 13:56:10.709898       1 initialization.go:90] enabled Initializers feature as part of admission plugin setup
I0521 13:56:10.710192       1 plugins.go:149] Loaded 10 admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,DefaultTolerationSeconds,DefaultStorageClass,MutatingAdmissionWebhook,Initializers,ValidatingAdmissionWebhook,ResourceQuota.
I0521 13:56:10.710579       1 plugins.go:149] Loaded 10 admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,DefaultTolerationSeconds,DefaultStorageClass,MutatingAdmissionWebhook,Initializers,ValidatingAdmissionWebhook,ResourceQuota.
F0521 13:56:30.732828       1 storage_decorator.go:57] Unable to create storage backend: config (&{ /registry [https://127.0.0.1:2379] /run/config/pki/apiserver-etcd-client.key /run/config/pki/apiserver-etcd-client.crt /run/config/pki/etcd/ca.crt true false 1000 0xc4205db680 <nil> 5m0s 1m0s}), err (dial tcp 127.0.0.1:2379: getsockopt: connection refused)
```
The etcd container is not started at all!!!

**Steps to reproduce the behavior**:
- Enable Kubernetes under Docker for Windows

**Comment by singlewind** [comment]
I have run into the same issue
`Flag --admission-control has been deprecated, Use --enable-admission-plugins or --disable-admission-plugins instead. Will be removed in a future version.                      Flag --insecure-port has been deprecated, This flag will be removed in a future version.                                                                                       I0703 11:38:15.557477       1 server.go:135] Version: v1.10.11                                                                                                                 I0703 11:38:15.557548       1 server.go:724] external host was not specified, using 192.168.65.3                                                                               I0703 11:38:15.778056       1 feature_gate.go:190] feature gates: map[Initializers:true]                                                                                       I0703 11:38:15.778109       1 initialization.go:90] enabled Initializers feature as part of admission plugin setup                                                             I0703 11:38:15.778499       1 plugins.go:149] Loaded 10 admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,DefaultTolerationSeconds,DefaultStorageClass,MutatingAdmissionWebhook,Initializers,ValidatingAdmissionWebhook,ResourceQuota.                                               I0703 11:38:15.779242       1 plugins.go:149] Loaded 10 admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,DefaultTolerationSeconds,DefaultStorageClass,MutatingAdmissionWebhook,Initializers,ValidatingAdmissionWebhook,ResourceQuota.                                               F0703 11:38:35.781746       1 storage_decorator.go:57] Unable to create storage backend: config (&{ /registry [https://127.0.0.1:2379] /run/config/pki/apiserver-etcd-client.key /run/config/pki/apiserver-etcd-client.crt /run/config/pki/etcd/ca.crt true false 1000 0xc420850180 <nil> 5m0s 1m0s}), err (dial tcp 127.0.0.1:2379: getsockopt: connection refused)`
