### ISSUE TITLE
A firewall is blocking file Sharing between Windows and the containers

### ISSUE THREAD

**Issue by phlopez06** [docker/for-win#3569]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A7A00774-7714-4B49-A835-C397E587279F/20190314091821

### Expected behavior
Being able to share my C: drive with Docker

### Actual behavior
I got the following when trying to share the C drive: A firewall is blocking file Sharing between Windows and the containers. See documentation for more info.
I have Windows Defender Firewall, with a "good" setting for DockerSmbMount, allowing InBound connection with local 10.0.75.1:445 and remote 10.0.75.2:Any
I have also McAfee Endpoint Security running. I don't have any control on it, managed by IT here.

### Information

  - Windows Version: 10 Enterprise 10.0.16299 Build 16299
  - Docker for Windows Version: 2.0.0.3 (31259), stable, Build 8858db3

### Steps to reproduce the behavior

  1. Just trying this command : docker run -v c:/Users:/data alpine ls /data
I can different different behavior when it is not working:
- Asking to share my C: drive when not enable. I share it and get blocked by firewall
- Not asking to share my C: drive (because settings in Docker said it's shared) and get 'partial' result (not showing the full directory listing, most of time empty list, sometimes just my user folder)

**Comment by PerfectLion** [comment]
I have the same problem.... with same configuration in my OS

Win10
McAfee Endpoint Security and not I don't have any control on it, too, and I am admin of PC

**Comment by ndywicki** [comment]
Same problem here in coorporate environment.

I've tried several workarounds found here :

- https://www.bountysource.com/issues/40379858-error-a-firewall-is-blocking-file-sharing-between-windows-and-the-containers
- https://stackoverflow.com/questions/42203488/settings-to-windows-firewall-to-allow-docker-for-windows-to-share-drive/43904051

and also:

- Uninstall Check Point VPN
- Create a local admin docker user
- Set DockerNAT on same eth0 network whit corp DNS suffix
- But I don't have permission to set DockerNAT in private network whit admin powerShell :
```
PS C:\Users\###> Set-NetConnectionProfile -interfacealias "vEthernet (DockerNAT)" -NetworkCategory Private
Set-NetConnectionProfile : Unable to set the NetworkCategory due to one of the following possible reasons: not running
PowerShell elevated; the NetworkCategory cannot be changed from 'DomainAuthenticated'; user initiated changes to
NetworkCategory are being prevented due to the Group Policy setting 'Network List Manager Policies'.
Au caractère Ligne:1 : 1
+ Set-NetConnectionProfile -interfacealias "vEthernet (DockerNAT)" -Net ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (MSFT_NetConnect...D07BCF2271CD}"):root/StandardCi...nnectionProfile)
   [Set-NetConnectionProfile], CimException
    + FullyQualifiedErrorId : MI RESULT 2,Set-NetConnectionProfile
```

### Information

- Telnet on 10.0.75.1 445 **working**
- Manual sharing C:\ **working**
- Windows Version: 10 Enterprise 17763.379 Build 1809
- Docker for Windows Version: 2.0.0.3 (31259), stable, Build 8858db3
- McAfee Endpoint Security and not I don't have any control on it, too, and I am admin of PC


Thanks

**Comment by asahire** [comment]
> I have the same problem.... with same configuration in my OS
> 
> Win10
> McAfee Endpoint Security and not I don't have any control on it, too, and I am admin of PC

This might help - https://www.opendxl.com/forum/index.php?thread/184-docker-unable-to-share-drives-on-systems-with-ens/
You need to allow 445 port on your McAfee endpoint security firewall. Without that, it is not possible to share the Drive.
