### ISSUE TITLE
always "starting..." in windows 10

### ISSUE THREAD

**Issue by jan4984** [docker/for-win#358]
### Expected behavior
docker in running state
### Actual behavior
docker is always in 'starting...' state
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.

25DECF22-65CA-4A6F-A7B5-E2A0FE10FD9D/2016-12-27_11-10-35

  - a reproducible case if this is a bug, Dockerfiles FTW

install docker for windows, then "docker is  starting...". I have wait for 30 mins.

  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mpratt62** [comment]
Having the same issue. I do not have any docker images setup yet.

**Comment by mpratt62** [comment]
When in powershell these commands hang: 

docker info
docker events

**Comment by rneugeba** [comment]
@jan4984 thanks for your report. Something doesn't seem right with your Hyper-V installation. normally in `bcdedit` the `hypervisorlaunchtype` is set to `Auto` but in your case it is set to `Off`. Unfortunately a lot of the other diagnose output is in Chinese, which I'm not fluent in (and doing google translate is somewhat cumbersome).

Could you quit and un-install the Docker for Windows application and then remove the the Hyper-V feature via the UI `Programs and Features`. This likely requires a reboot. Can you then enable the Hyper-V feature (which requires another reboot) and double check the `hypervisorlaunchtype` with `bcdedit` before re-installing Docker for Windows?

**Comment by jan4984** [comment]
@rneugeba thank you for help. 

It's the `hypervisorlaunchtype`  I think. I have turn a linux pc now,  so I will just close this issue.
