### ISSUE TITLE
Error while installing new updated version..

### ISSUE THREAD

**Issue by jainthedestroyer** [docker/for-win#3585]

**Comment by jainthedestroyer** [comment]
The report after executing command "Get-WmiObject Win32_OperatingSystem | fl *"

PSComputerName                            : DESTROYER
Status                                    : OK
Name                                      : Microsoft Windows 10 Enterprise|C:\WINDOWS|\Device\Harddisk0\Partition4
FreePhysicalMemory                        : 2119752
FreeSpaceInPagingFiles                    : 5340364
FreeVirtualMemory                         : 3635804
__GENUS                                   : 2
__CLASS                                   : Win32_OperatingSystem
__SUPERCLASS                              : CIM_OperatingSystem
__DYNASTY                                 : CIM_ManagedSystemElement
__RELPATH                                 : Win32_OperatingSystem=@
__PROPERTY_COUNT                          : 64
__DERIVATION                              : {CIM_OperatingSystem, CIM_LogicalElement, CIM_ManagedSystemElement}
__SERVER                                  : DESTROYER
__NAMESPACE                               : root\cimv2
__PATH                                    : \\DESTROYER\root\cimv2:Win32_OperatingSystem=@
BootDevice                                : \Device\HarddiskVolume2
BuildNumber                               : 17763
BuildType                                 : Multiprocessor Free
Caption                                   : Microsoft Windows 10 Enterprise
CodeSet                                   : 1252
CountryCode                               : 1
CreationClassName                         : Win32_OperatingSystem
CSCreationClassName                       : Win32_ComputerSystem
CSDVersion                                :
CSName                                    : DESTROYER
CurrentTimeZone                           : 330
DataExecutionPrevention_32BitApplications : True
DataExecutionPrevention_Available         : True
DataExecutionPrevention_Drivers           : True
DataExecutionPrevention_SupportPolicy     : 2
Debug                                     : False
Description                               : Anil's Destroyer
Distributed                               : False
EncryptionLevel                           : 256
ForegroundApplicationBoost                : 2
InstallDate                               : 20181209174035.000000+330
LargeSystemCache                          :
LastBootUpTime                            : 20190318151020.500000+330
LocalDateTime                             : 20190318163856.732000+330
Locale                                    : 0409
Manufacturer                              : Microsoft Corporation
MaxNumberOfProcesses                      : 4294967295
MaxProcessMemorySize                      : 137438953344
MUILanguages                              : {en-US}
NumberOfLicensedUsers                     :
NumberOfProcesses                         : 254
NumberOfUsers                             : 2
OperatingSystemSKU                        : 4
Organization                              :
OSArchitecture                            : 64-bit
OSLanguage                                : 1033
OSProductSuite                            : 256
OSType                                    : 18
OtherTypeDescription                      :
PAEEnabled                                :
PlusProductID                             :
PlusVersionNumber                         :
PortableOperatingSystem                   : False
Primary                                   : True
ProductType                               : 1
RegisteredUser                            : Windows User
SerialNumber                              : 00329-00000-00003-AA743
ServicePackMajorVersion                   : 0
ServicePackMinorVersion                   : 0
SizeStoredInPagingFiles                   : 5767168
SuiteMask                                 : 272
SystemDevice                              : \Device\HarddiskVolume4
SystemDirectory                           : C:\WINDOWS\system32
SystemDrive                               : C:
TotalSwapSpaceSize                        :
TotalVirtualMemorySize                    : 14070604
TotalVisibleMemorySize                    : 8303436
Version                                   : 10.0.17763
WindowsDirectory                          : C:\WINDOWS
Scope                                     : System.Management.ManagementScope
Path                                      : \\DESTROYER\root\cimv2:Win32_OperatingSystem=@
Options                                   : System.Management.ObjectGetOptions
ClassPath                                 : \\DESTROYER\root\cimv2:Win32_OperatingSystem
Properties                                : {BootDevice, BuildNumber, BuildType, Caption...}
SystemProperties                          : {__GENUS, __CLASS, __SUPERCLASS, __DYNASTY...}
Qualifiers                                : {dynamic, Locale, provider, Singleton...}
Site                                      :
Container                                 :

**Comment by Tijaques** [comment]
Same for me !

**Comment by jainthedestroyer** [comment]
I just upgraded my system to insider's preview of windows and the new updated version got no problem while installing ....

**Comment by jainthedestroyer** [comment]
I am leaving the issue open so that the problem must be solved for the others ....
