### ISSUE TITLE
Cannot mount volume on windows

### ISSUE THREAD

**Issue by Mikaka27** [docker/for-win#359]
### Expected behavior
Volume mounting works on windows

### Actual behavior
Error is received: C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: mkdir /c: file exists.

### Information

  - B77F5BF3-DCFB-4AB3-BEC4-762CBCE8E736/2016-12-27_21-53-18
  - Docker version: 1.12.5 (9503)
  - Windows 10 64-bit anniversary
  - I'm following this guide to pack aspnet core to docker: https://blogs.msdn.microsoft.com/stevelasker/2016/09/29/building-optimized-docker-images-with-asp-net-core/
  - Current path that I'm on when executing the command (mentioned below) is this: C:\Users\Mikaka\Documents\Visual Studio 2015\Projects\CSite (ie contains spaces, but I've checked running it from a different path like C:\Users and there was no change)
  - I've tried specifying the path manually using different syntaxes for example: C:\Users, /c/Users, c:/Users etc. and they all yield the same result

### Steps to reproduce the behavior

  1. Have docker for windows started
  2. Enter a folder in which you have .sln (visual studio solution) file in powershell
  3. Type this command: docker run -it --rm -v "$pwd\:/sln" microsoft/aspnetcore-build:1.0.1
  4. See error: /C: file exists

**Comment by PetaPetaPeta** [comment]
Do you have "Shared Drives" enabled in Docker for Windows?

**Comment by johnrb2** [comment]
I was having the same issue and found it was due to my cisco vpn. Docker then runs into firewall issues.

**Comment by rneugeba** [comment]
I can't reproduce the issue, but, your command line (`docker run -it --rm -v "$pwd:/sln" microsoft/aspnetcore-build:1.0.1`) is missing a `\` after the `$pwd`. So with:
```
docker run -it --rm -v "$pwd\:/sln" microsoft/aspnetcore-build:1.0.1
```
it works for me(tm).

Looking at the logs, there seem to be have been an issue with sharing the `C:` or `D:` drive. I see:
```
Unable to validate cred: Invalid username or password
```
However looking at the logs from the Linux VM I see that the `C:` drive is actually mounted.

Could you cut and paste the *exact* command line you execute together with the error message? If you use any dockerfiles, coult you provide them to?

**Comment by rneugeba** [comment]
Closing this issue due to lack of response. Please re-open if the issue persist.
thanks
