### ISSUE TITLE
Cannot create transparent network

### ISSUE THREAD

**Issue by MythreyaK** [docker/for-win#3592]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B81956F0-D115-4F60-91A3-AB8D6A5C20C1/20190319164902

### Expected behavior
Command used: `docker network create -d transparent InternetSwitch`
Docker successfully creates the transparent network adapter, so that I can connect containers directly to my network 
### Actual behavior
Error: `Error response from daemon: hnsCall failed in Win32: The parameter is incorrect. (0x57)`
### Information

  - Windows Version: 10.0.17763.316 (1809)
  - Docker for Windows Version: 2.0.0.3 (31259)

### Steps to reproduce the behavior

  1. Make sure you are in Windows container mode
  2. Try creating a new transparent network 
  3. Note the error described above

**Comment by JasonNoonan** [comment]
Hey there, just curious: have you tried making the network name lower-case?  IIRC, all of the docker components are case sensitive and require lower-case names.

**Comment by MythreyaK** [comment]
I did try a lower case, no luck, still the same error

**Comment by fourpastmidnight** [comment]
I am experiencing the _exact_ same issue with the _same_ set of repro steps. I am on the same version of Docker, except the 5 digit (build id?) is 31778.

The command I attempted to run was: `docker network create -d transparent transparent`.

**Comment by martywaz** [comment]
is there any update on this?  I'm getting the exact same error with the latest release

**Comment by xiaoxiangmoe** [comment]
is there any update on this? I'm getting the exact same error with the latest release

**Comment by Crosus97** [comment]
is there any update on this? I'm getting the exact same error with the latest release

**Comment by winstonhenke-work** [comment]
Also seeing this issue

**Comment by xiaoxiangmoe** [comment]
1

**Comment by xiaoxiangmoe** [comment]
is there any update on this?

**Comment by ilchenkob** [comment]
I have exactly the same issue.
Docker Desktop Version: 2.1.0.5 (40693)
Command used:
```powershell
docker network create -d transparent --subnet=172.26.1.0/16 --gateway=172.26.1.1 t_net
```

**Comment by olivier-haddad** [comment]
Same here.
Docker 19.03.5
Docker Desktop 2.2.0.3

 I hoped a transparent network would allow to use multicast. As of now I cannot run my IOT server from docker...

**Comment by SalFicara** [comment]
Same issue, application breaking bug still exists over a year later.

**Comment by robgoodwin** [comment]
Same issue.  If this is not the correct way to do this on the Desktop version of Docker, how should we proceed

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place?
Sorry, I would move it myself, but I can't because it's in a different org (it's `moby` not `docker`).
