### ISSUE TITLE
Docker for Windows is not starting / Error message is unclear

### ISSUE THREAD

**Issue by patrickbussmann** [docker/for-win#3595]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: CE903C23-C775-47A8-97DD-D264EBFD052E/20190320104339

### Expected behavior
Docker for Windows starts successfully.

### Actual behavior
<img width="517" alt="2019-03-20 11_46_53-Error" src="https://user-images.githubusercontent.com/15617021/54678658-e034ff00-4b05-11e9-9a58-cec1fbd39729.png">

<img width="446" alt="2019-03-20 11_48_15-Task-Manager" src="https://user-images.githubusercontent.com/15617021/54678775-24280400-4b06-11e9-86cf-a28c525a2d7f.png">

### Information
  - Windows Version: Windows 10 Pro
  - Docker for Windows Version: Newest, downloaded fresh from website

### Steps to reproduce the behavior
Starting Docker for Windows.

### Additional
I saw that a lot of peoples have this issue. (#329, #2713, #3469)
Maybe the error message could be improved so that it's more clear what to do.

When I go to Hyper-V Manager I can't start the MobyVM manually.
So I searched for it and found that "bcdedit /set hypervisorlaunchtype Auto" could help.

I will try it in the Meanwhile but maybe its helpful to extend the documentation for that or improve the error message.

**Comment by pipe01** [comment]
I had this same issue, running `bcdedit /set hypervisorlaunchtype Auto` and restarting completely fixed it!

**Comment by patrickbussmann** [comment]
For me the fix was disabling the Hyper-V feature, reboot and enable the Hyper-V feature again.
Now its running.
