### ISSUE TITLE
Login to internal docker registry with self-signed Server-Certificate fails

### ISSUE THREAD

**Issue by hofsa** [docker/for-win#36]
### Expected behavior
When trying to login to an internal docker registry with:
docker login registry.isc.ejpd.admin.ch
Expected successful login acknowledged with the message 
"Login Succeeded"
The exact same command run successfully from a Linux host.

### Actual behavior
Login fails with:
"Error response from daemon: Get https://registry.isc.ejpd.admin.ch:5000/v1/users/: x509: certificate signed by unknown authority" 

### Information
Diagnostic ID: 6BB9DE18-179E-43B2-8240-FA7CC6431D73/2016-08-12_10-21-58

The registry uses a self-signed Certificate (See attached file [registry.crt.txt](https://github.com/docker/for-win/files/414875/registry.crt.txt), remove txt-extension)

The CA-Certificate is added to the following locations on the Windows-filesystem:
C:\ProgramData\Docker\certs.d\registry.isc.ejpd.admin.ch
C:\ProgramData\Docker\certs.d\registry.isc.ejpd.admin.ch5000

Restarted Docker & even rebooted the Machine

Windows Version: Windows 10 Pro Version 1607 (OS Build 14393.10)
Docker for Windows: 1.12.0-stable (Build 5968)

The login also fails, if I connect to the MobyLinuxVM and execute the login-command there. I was not able to find the CA-Cert on the MobyLinuxVM. Looks like the certificates are not propagated from the Windows-Filesystem into the MobyLinuxVM

### Steps to reproduce the behavior

  1. Start an internal docker registry with a self-signed certificate
  2. Add the registry-certificate to C:\ProgrammData\Docker\certs.d\<<registry-name>>
  3. Try to login to the registry with:  docker login <<registry-name>>

**Comment by hofsa** [comment]
### Workaround
I was able to skip certificate-validation using the "insecure-registries" - option for the docker daemon:

```json
{
  "registry-mirrors": [],  
  "insecure-registries": [
    "registry.isc.ejpd.admin.ch",
    "registry.isc.ejpd.admin.ch:5000"
  ],
  "debug": true
}
```
`docker login registry.isc.ejpd.admin.ch` works now as expected.

**Comment by rneugeba** [comment]
@hofsa Thanks for following up. Yes for now, you have to set the insecure registry setting. Unless I misunderstood, this fixes your issue. Closing...please re-open if I misunderstood.
