### ISSUE TITLE
sharing drive throws firewall block error with windows native docker when cisco anyconnect VPN is ON

### ISSUE THREAD

**Issue by sugun999** [docker/for-win#360]
Expected Behaviour:

Filesharing should work even corporate cisco anyconnect VPN is ON

Actual behaviour:

Sharing drive C fails by throwing firewall block detected error

Information:

Installed native docker on windows 10 enterprise version 10.0.14393
Also, F-secure is installed on my laptop and opened necessary network firewall openings with f-secure (to allow all traffic between 10.0.75.1 & 10.0.75.2)
Everything works fine as long as the corporate cisco anyconnect VPN is NOT ON.

But as soon as corporate cisco anyconnect vpn is ON, sharing drive C fails by throwing firewall detected error.

As you know, when switching to corporate cisco anyconnect vpn, routing tables gets modified and it looks that filesharing is not working.

Is there any hack for this issue?

**Comment by SpencerTuft** [comment]
Me too.

**Comment by simonferquel** [comment]
Hi, which version of Docker for Windows are you using ? can you try latest beta ?

**Comment by sudhakar999** [comment]
Hi Simonferquel,

Thanks for the reply. I tried with both stable channel (1.12.5) & beta channel (1.13.0-rc4) and the end result is the same error which is "Firewall blocking file sharing between windows and the container. See documentation for more info"

Please note that all "file and printer sharing" inbound rules of windows firewall settings are enabled for private, public and domain profiles on my laptop.
And also, windows firewall is turned off for all private, public and domain profiles.

Please help us troubleshooting this issue.

**Comment by johnrb2** [comment]
Okay so what I have found out is that the vpn doesn't like the IP using 10.0.75.1 most likely because it is used by the business already.

You need to go to the Network Connections and going to the properties of NAT. And update docker network.

![image](https://cloud.githubusercontent.com/assets/13036323/21618327/a3923f4c-d1a7-11e6-94bd-10c886743549.png)

**Comment by johnrb2** [comment]
You might only need to change it in docker though. The IP can be 192.168.[whatever < 255].0

**Comment by johnrb2** [comment]
Yeah you just go to network settings in docker.

**Comment by sugun999** [comment]
Hi,

Thanks for the info. Instead of trying all the numbers (1-254) for IP part, is there any specific rule/criteria in choosing the number, so that it works?

**Comment by johnrb2** [comment]
You just don't want it to be one that is already in use by something else.

**Comment by johnrb2** [comment]
http://trendblog.net/ever-wondered-use-192-168-x-x-ip-addresses-home/

**Comment by sugun999** [comment]
Hi,

I tried with several free network IPs but still docker throws same error when trying to share C drive.

**Comment by johnrb2** [comment]
I had to get a computer with an operating system that was the full version of Windows 10 Pro instead of the companies modified version of Windows 10 and my computer had to be off the company's domain. It could be an issue with that. I am not an official docker worker. But I would suggest trying docker for windows beta and see if it fixes it and uploading a diagnostic file and copy and sharing the reference with your issue.

**Comment by friism** [comment]
@johnrb2 thanks for following up - it'd be very useful for us to learn what exactly blocked Docker on a normally configured machine.

**Comment by sugun999** [comment]
Hi Docker team,
Any workaround to get sharing drive works even with cisco anyconnect vpn?

**Comment by friism** [comment]
@sugun999 if possible, can you upload a diagnostic dump from the app and post the id here?

**Comment by sugun999** [comment]
Hi friism,

Thanks for the reply. Before sending dump, Could you please let me know, what diagnostic report contains?
Will the docker collects any security info?

**Comment by friism** [comment]
@sugun999 the diagnostic dump is pretty comprehensive to help us fully debug problems on user systems. Access to the dumps is limited to engineers working on Docker for Mac and Windows, and we handle the dumps with care.

If you're not comfortable using the diagnostic feature, please access the logs after encountering this problem, remove any sensitive info and paste the relevant log snippet in this issue.

**Comment by sugun999** [comment]
HI Friism,

Below is log excerpt which is logged when trying to share drive C.
Please note that F-secure software with my laptop, is not blocking anything. I added rule to allow all traffic from any IPv4 which is working without VPN.

Could you please take a look at this and provide solution for this issue why filesharing doesn't work with VPN?

[log_excerpt.txt](https://github.com/docker/for-win/files/704655/log_excerpt.txt)

**Comment by simonferquel** [comment]
From the log, I see that you changed the IP settings of the VM (it says your host has IP 192.168.230.1, so your VM should have 192.168.230.2).
From the following lines, I see that the VM cannot reach port 445 on 192.168.230.1. By any chance, can you make sure that the IP settings you chose do not conflict with the VPN connection IP ? (or just dump your `ipconfig /all` here)

**Comment by sugun999** [comment]
Hi Simeon,

Before or after opening VPN, I do see that "Ethernet adapter vEthernet (DockerNAT) 2" has

   IPv4 Address. . . . . . . . . . . : 192.168.230.1(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   
Ofcourse there is new virtual adapter gets created with VPN is ON and it gets own IPv4 address 141.19x.xxx.xxx and not conflicting with above docker Ethernet adapter.

**Comment by sugun999** [comment]
Hi,

Any ideas?

**Comment by simonferquel** [comment]
Unfortunately no. It seems that Cisco AnyConnect include some kind of firewall blocking port 445. We'll need to investigate more thoroughly, but we need the proper Cisco infrastructure to test it.

**Comment by SpencerTuft** [comment]
I did what @johnrb2 did and it worked just fine for me. I don't think Cicso anyConnect has to block port 445 to work properly. If it did, then it wouldn't be working for me or johnrb2.

**Comment by sugun999** [comment]
Hi SpencerTuft,

Could you please let me know, what is subnet address/mask you tried?

**Comment by SpencerTuft** [comment]
I used this: 255.255.255.0

**Comment by sugun999** [comment]
Yes, I understood that it is specific our vpn. Hence closing this

**Comment by rneugeba** [comment]
@sugun999 We obviously would like to work in environments with VPNs etc but unfortunately we have very little control over the VPN settings. We are looking into other options for filesharing which do not required the current network based setup but have not found a suitable replacement yet.

**Comment by libsamek** [comment]
Thanks for this issue! It made me realize, that's it a routing problem. VPN clients usually add static routes, for example 10.0.0.0/8. That was routed to our corp network.

I solved the issue by using address space, which isn't used in our corp network, for example something from 172.16.0.0 - 172.31.255.255.

So for anyone experiencing same problems, check your routing tables first and than do the correct addressing based on that :)

**Comment by lucastheisen** [comment]
@sugun999 , did you ever find a workaround?  I am also stuck behind Cisco AnyConnect.  When I suspend the VPN i can mount the shared drive without issue.  But as soon as I start the VPN back up, it fails again...

**Comment by pitaman71** [comment]
Same here

**Comment by oneut** [comment]
I had the same problem when cisco anyconnect VPN is ON.

I thought that there was a problem with the virtual switch.
After recreating the virtual switch with the connection to the VPN, shared drive has been activated 😃 

**Settings** > **Reset** > **Reset to factory defaults**

However, it takes time to reset to factory defaults... 😢

**Comment by oneut** [comment]
Sorry, I still did not move.
it was my misunderstanding 😢

**Comment by bartlomiejcieszkowski** [comment]
I've encountered the same issue, it seems that changing ip range to different than 10.0.0.0 family helps, so the docker container with -v/c/some/path:/root/somewhereelse mounts, but the firewall kicks in blocking 445 port - and disabling the firewall is a no go solution in corporate environments - would it be possible to add an option to change the port used by mount service?

**Comment by vamsitekuru** [comment]
I am still facing the same issue with CISCO VPN  . is there any alternative than changing IP frpm default (10.0.x.x) to some thing else ..

**Comment by DiJu519** [comment]
If you Open up AnyConnect on Windows, go into VPN -> Route Details, you may have an entry under the heading "Non-Secured Routes")

Take that Address/Mask combination, and put it under Docker's Settings -> Network -> Internal Virtual Switch

E.g if under "Non-Secured Routes: you have 123.456.0.0/16 then under "Internal Virtual Switch" have your Subnet Address as "123.456.0.0" and your Subnet Mask as "255.255.255.0"

**Comment by DiJu519** [comment]
For Linux, i **think** the following applies.

```
Configure the default bridge network

To configure the default bridge network, you specify options in daemon.json. Here is an example daemon.json with several options specified. Only specify the settings you need to customize.

{
  "bip": "192.168.1.5/24",
  "fixed-cidr": "192.168.1.5/25",
  "fixed-cidr-v6": "2001:db8::/64",
  "mtu": 1500,
  "default-gateway": "10.20.1.1",
  "default-gateway-v6": "2001:db8:abcd::89",
  "dns": ["10.20.1.2","10.20.1.3"]
}
```
https://docs.docker.com/network/bridge/#connect-a-container-to-the-default-bridge-network

Haven't tried it yet.

**Comment by lucastheisen** [comment]
@DiJu519 , the problem (for many of us) is that "Secured Routes" is set to `0.0.0.0/0`.  So no dice there.

**Comment by kamkie** [comment]
maybe there is option to use hyper-v socket for file sharing?

**Comment by jrbecart** [comment]
I don`t know why this issue was closed... 
The problem is still here.

**Comment by lucastheisen** [comment]
The only way i see around this would be to route the SMB/CIFS traffic through the npipe tunnel like they do for publishing ports.  Our VPM is configured at the corporate level to capture all ip traffic `0.0.0.0` which includes the [_reserved ranges_](https://en.wikipedia.org/wiki/Reserved_IP_addresses#IPv4).  I would really love to see the SMB/CIFS npipe routing, but think it may be to much of a boundary case to expect anyone else to implement it...  (though i imagine there may be many other corporate VPN's that do the same thing...)

**Comment by jrbecart** [comment]
Solution that works for my case are (from previous suggestions): 

- Ask for example this list of ip to be added in non-secured routes in the cisco anyconnect profile:
127.0.0.0/8
10.0.0.0/8
172.16.0.0/12
192.168.0.0/16

- Use [OpenConnect ](https://github.com/openconnect/openconnect-gui/releases)

**Comment by los93sol** [comment]
Bump, please consider changing the way this works so that it works for those of us in these scenarios

**Comment by bdwyertech** [comment]
If there was a way to override the destination address for SMB protocol from the Docker daemon, it would  likely get around the secured route issue.  You'd set it to the Cisco virtual adapters IP address and all the woes would likely go away as the restrictions apply to local IP's.  AnyConnect babysits the local routing table and makes sure everything flows out the virtual adapter, hence if the SMB destination was the AnyConnect adapter IP address, SMB would work.

**Comment by los93sol** [comment]
Interesting...similar to others mine secures 0.0.0.0/0 and when looking at the routing tables I can see it literally overrides everything.  Can you explain a bit more or point me to some documentation how routing SMB from Docker to AnyConnects virtual address would work in that scenario?  I’m interested to stage some tests while running a pcap to better understand.

**Comment by bdwyertech** [comment]
I don't have any documentation to point to, however I use this method when working remotely to allow certain tools to work... Take Packer as an example, it throws up a web server to serve up kickstart files.  I noticed it didn't work when allowing Packer to choose the IP (typically my WiFi adapter), however inserting my Cisco AnyConnect adapters IP address in there made it work fine.  I've also used this previously with Vagrant on VMware, which uses NFS/SMB for file sharing.

If you think about it, the network restrictions force everything out of that interface; its a catch all route with the best metric.  Being that your laptop has an IP on the network its being routed out to, if you bind all, e.g. bind to 0.0.0.0, then you're also listening on that interface.

**Comment by julianiacoponi** [comment]
Please can this be re-opened and addressed :) or at least figure some other way of running docker natively on windows with mounted volumes, whilst behind Cisco AnyConnect.

**Comment by kamkie** [comment]
there is new version of Cisco AnyConnect 4.7 (it is using windows vpn infrastructure) in windows store, i will test that this weekend

**Comment by Jordaanwatson** [comment]
I have a suggested 'fix' for this please follow instructions below:-

- Within your docker settings uncheck "Start docker desktop when you log in"
- Restart Machine 
- Now that machine is restarted open settings in Cisco anyconnect
- Go to networks and then in the top right where all your network connections are listed click the arrow pointing to the right (Sorry i don't have screen shots) this should show a drop down with enable and disable click disable
- Now start docker
- Docker should now start and run the daemon this time. 
- Now spin up your container
- Go back in to your Cisco any connect settings and enable the networking again
- Your container should stay open and you should be able to access the ports all fine

All in all the issue i believe happens is the cisco anyconnect VPN controls all network adapters and docker cant own one so by briefly disabling the VPN to allow docker daemon to establish a connection this should fix your issues running docker along side the VPN this step has to be reproduced ever restart!

**Comment by kamkie** [comment]
https://www.microsoft.com/en-us/p/anyconnect/9wzdncrdj8lh 
using this version of Cisco AnyConnect i can use volumes when connected to VPN

**Comment by julianiacoponi** [comment]
Thanks! I unfortunately use a non-microsoft store copy of AnyConnect and cannot find how to update my version from 4.6.03049 to 4.7+ ... any advice on how to do this appreciated! (Although I myself appreciate this is not relevant to this bug).

In the meantime, @Jordaanwatson I will try your method. However,I don't seem to have a "Networks" section in my AnyConnect settings?
![image](https://user-images.githubusercontent.com/32678459/55289668-2a996400-53c1-11e9-84e0-5f8bdeccb1d8.png)

**Comment by Jordaanwatson** [comment]
@julianiacoponi Your version is very close to the one i use if im not at my work machine at the moment but if you can find there it lists your networks or even just find where you can disable the VPN and re enable once you have docker started and a container running. Let me know how you get on!

**Comment by jeffjwills** [comment]
I also have this issue, I normally just kill Cisco to get around it but I can’t always do that. This issue is preventing me from recommending Docker to my organisation which is a shame.

Tried the Windows Store version of AnyConnect (4.7+) makes no difference for me.

Tried Jordaanwatson’s solution to disable Cisco, start a Docker VM, then enable Cisco but this doesn’t work for me. 

I am going to try getting some IP ranges added to the non-secured routes.

I am also going to try OpenConnect to see if it works but this is not a solution I can let anyone else use as AnyConnect is Corporate Policy.

Fingers crossed enough people have this issue and a new version of Docker will have a workaround!

**Comment by asinoai** [comment]
Had the same problem; to solve it, I switched to OpenConnect as mentioned already, but also had to add to the docker deamon's config file the following: "bip" : "192.168.1.5/24", because the default was clashing with existing IPs (https://docs.docker.com/v17.09/engine/userguide/networking/default_network/custom-docker0/)

**Comment by brianwthomas** [comment]
Would love a solution for this. I can't get this running in my corp environment either with VPN running

**Comment by var23rav** [comment]
As @johnrb2 says the best way is to change the docker network.

When you do Folder sharing(volume mount) with wsl, you may face issue if there is any *vpn connection enabled*.

Solution, If you are using *Cisco Any-connect*,

* Allow Local Connection from Preferences
* Or, If you don't have the permission to allow Local Connection or You couldn't see this option
 try Change Docker Network to match any non secure routes of cisco any-connect to avoid this blocking 

Network ranges can be found in 
**Cisco AnyConnects -> click on the settings(gear icon) -> Route Details -> Non-Secure Routes**

Update **Docker -> Settings -> Network -> Subnet addres and Subnet Mask** to match non-secure routes from cisco any-connect

And restart the docker, if required rebuild the image.


![image](https://user-images.githubusercontent.com/7958115/58403279-e4d6e000-807f-11e9-94e0-05a54120449a.png)

**Comment by brianwthomas** [comment]
If only it were that easy :(

I've cycled through about every network I can think of (192/172/1.1.1.0, etc...)  All results in not being able to access the shared drive.  Once off Anyconnect, it works fine.

Example error: docker.errors.APIError: 500 Server Error: Internal Server Error ("b'Drive sharing seems blocked by a firewall'")

Once I'm off Anyconnect I can hit the share drive just fine

**Comment by bartlomiejcieszkowski** [comment]
@brianwthomas i've stumbled on this issue and unfortunately i wasn't able to do anything about this, but this is due to the cisco anyconnect having too aggresive routing.

As I was using the container to get compilation environment, I recall that i've had some success with it while being still off from vpn starting a container in interactive mode and then connecting to a vpn.. but my memory is a bit fuzzy there..

I've had also the same issue with a combo of VirtualBox + AnyConnect - once the vpn is on, the ping and ssh to a machine was impossible.

Also I tried some route mangling back then with no success, but this looks like a good direction to workaround the issue - see for reference:
https://forums.virtualbox.org/viewtopic.php?f=8&t=62403

**Comment by ericis** [comment]
> As @johnrb2 says the best way is to change the docker network.
> 
> When you do Folder sharing(volume mount) with wsl, you may face issue if there is any _vpn connection enabled_.
> 
> Solution, If you are using _Cisco Any-connect_,
> 
> * Allow Local Connection from Preferences
> * Or, If you don't have the permission to allow Local Connection or You couldn't see this option
>   try Change Docker Network to match any non secure routes of cisco any-connect to avoid this blocking
> 
> Network ranges can be found in
> **Cisco AnyConnects -> click on the settings(gear icon) -> Route Details -> Non-Secure Routes**
> 
> Update **Docker -> Settings -> Network -> Subnet addres and Subnet Mask** to match non-secure routes from cisco any-connect
> 
> And restart the docker, if required rebuild the image.
> 
> ![image](https://user-images.githubusercontent.com/7958115/58403279-e4d6e000-807f-11e9-94e0-05a54120449a.png)

We don't see "Non-Secure Routes", only "Secured Routes (IPv4) - 0.0.0.0/0"

**Comment by ericis** [comment]
@var23rav

> Network ranges can be found in
> **Cisco AnyConnects -> click on the settings(gear icon) -> Route Details -> Non-Secure Routes**

We don't see "Non-Secure Routes", only "Secured Routes (IPv4) - 0.0.0.0/0"

![docker-shared-drives](https://user-images.githubusercontent.com/974919/67112147-8cc28680-f1a4-11e9-8d50-fe97bf9ef61c.gif)

**Comment by Jay1305** [comment]
Wow realized that the issue was created in the year 2016! I am still experiencing the issue when connected to Cisco VPN. As others pointed, I do see only secured routes with 0.0.0.0/0. Could there be any hack for us from docker side? I followed troubleshooting steps from - https://success.docker.com/article/error-a-firewall-is-blocking-file-sharing-between-windows-and-the-containers and still experience the same issue. Yes, we all know when we stop VPN, it works and when we start VPN, it stops working, so it would be some issue at VPN side. But can some master from Docker please help us? Thanks in advance.

**Comment by kumarjoshi** [comment]
I tried everything listed here and on https://stackoverflow.com/questions/42203488/settings-to-windows-firewall-to-allow-docker-for-windows-to-share-drive/47975648

Nothing worked for me. 

I run my dev environment on a docker container, and while on Corporate VPN (Cisco AnyConnect), I need the to mount my local drive on the container to access my project files.  

Here's a docker hack that worked for me:  **Add ` --publish 8000:8000` to your existing `docker run` command**

So 
`docker run -v C:/Users/kumar.joshi/KumarData:/mnt --name dev <image:latest> `

will become 
`docker run -v C:/Users/kumar.joshi/KumarData:/mnt --name dev --publish 8000:8000 <image:latest> `

Make sure the port is not used else you will get this error:
Bind for 0.0.0.0:8000 failed: port is already allocated

**Comment by mat007** [comment]
@kumarjoshi have you tried the latest edge version? We have completely rewritten how drive sharing works so that will likely fix your issue.

**Comment by bartlomiejcieszkowski** [comment]
@mat007 how does the new sharing work? Did you guys change anything related to samba mount? As there was problem with using mounted shares under windows/mac and forcing to 64bit inode - making it impossible to do thibgs with 32bit software - making docker not feasible solution under windows when i tried to deploy it

**Comment by mat007** [comment]
We have replaced Samba with a FUSE based implementation, there is no Samba anymore.
I suggest you give it a try and open fresh issues if needed.

**Comment by chrisps-dev** [comment]
I managed to get around the issue by setting my docker windows subnet address to 192.0.2.0, this was in the route details section of my cisco anyconnect settings under a subheading Non-secured Routes (IPV4), may be helpful to some, may not.

**Comment by ZhuBicen** [comment]
Please try the new version which use FUSE not SMB
https://docs.docker.com/docker-for-windows/edge-release-notes/#docker-desktop-community-2170

**Comment by mtarjanyi** [comment]
I didn't see this solution mentioned anywhere but a colleague offered the following settings change to overcome this issue:
![image](https://user-images.githubusercontent.com/20453491/76534747-32d79b80-647a-11ea-965e-552de485c2a5.png)

It seemingly works fine.
