### ISSUE TITLE
Microsoft seems to think Docker.Win32Helpers.dll is a trojan

### ISSUE THREAD

**Issue by sixcorners** [docker/for-win#3602]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
I don't know what the dll is expected to do.
### Actual behavior
I don't know what the dll does.
### Information
https://www.virustotal.com/#/file/cb8e8c8932bc7b410f3ecc429ae767ba06d90ccf9eb70dcb292fb2e21c0cda5e/detection

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. Use Windows Defender
  2. Try to start docker for windows

**Comment by victor-rds** [comment]
Same here, when I changed to windows containers immediately Misrosoft AV blocked it.
Here is the description link: https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fSkeeyah.I&threatid=2147725655
![image](https://user-images.githubusercontent.com/5115084/54734659-ce903d80-4b7f-11e9-85a0-aa6deccd5dc5.png)

**Comment by sixcorners** [comment]
I submitted the file here: https://www.microsoft.com/en-us/wdsi/filesubmission
https://www.microsoft.com/en-us/wdsi/submission/657116d2-ee5b-4e6f-acec-dcb23bddf312

**Comment by sixcorners** [comment]
I uh.. broke the raid 0 on my disks and need to reinstall windows for an unrelated reason..
I followed the instructions in https://www.microsoft.com/en-us/wdsi/submission/657116d2-ee5b-4e6f-acec-dcb23bddf312 and undid the allow on the trojan and it seemed to work.
Does it work for you now @victor-rds?

**Comment by sixcorners** [comment]
I think this is fixed.
