### ISSUE TITLE
Unexpected crash, docker unresponsive

### ISSUE THREAD

**Issue by sosensible** [docker/for-win#3605]
- [x ] I have tried with the latest version of my channel (Stable)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID:73B1EA68-00F5-4769-8E50-1F34FC77FBF9/20190321101157

### Expected behavior
Docker to run, and containers inside it.

### Actual behavior
Nothing is responding. Even a docker command via PowerShell just locks up.

### Information

  - Windows Version:
  - Docker for Windows Version: Current Windows 10 Enterprise

### Steps to reproduce the behavior

  1. ... Loaded an API container, UI (front end) container
  2. ... Hit the containers with a minor load... and docker crashed

**Comment by sixcorners** [comment]
Maybe it's because windows defender thought that one of the dll files was a trojan. see #3602
