### ISSUE TITLE
Docker for Windows always auto-start (although I turn off auto start with Windows)

### ISSUE THREAD

**Issue by donhuvy** [docker/for-win#3621]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 2FC17E05-6C5A-46B7-B7FF-C80AD3E24E79/20190325054912

### Expected behavior
Docker for Windows must does not auto-start (when I turn off auto start with Windows)

### Actual behavior
Docker for Windows always auto-start (although I turn off auto start with Windows)

### Information

  - Windows Version: Windows 10 Pro x64
  - Docker for Windows Version: Docker Desktop Community Version 2.0.0.3 (31259)

### Steps to reproduce the behavior

  1. Docker for Windows auto-start although I don't set it.

**Comment by Kaelum** [comment]
I've been forced to remove Docker until this is fixed.
