### ISSUE TITLE
Is it possible to change the settings of Docker for windows without using the app GUI?

### ISSUE THREAD

**Issue by AnjanaAK** [docker/for-win#3629]
### Problem
I need to automate the process of setting up WSL to use the docker-desktop in windows 10.

I installed docker in windows 10 using the chococlatey package :
https://chocolatey.org/packages/docker-desktop/2.0.0.3

The next step is to change the settings of docker desktop app to 'expose the daemon on tcp://localhost:2375 without TLS' and enable 'shared drives'. 

Since the automation doesn't allow to use the GUI, i need to change these settings via some commands or CLI. 

### Information

  - Windows Version: Windows 10 Pro , version:1809
  - Docker for Windows Version: Version 2.0.0.3 (31259), Channel: stable

### Steps to reproduce the behavior

  1. Open "Docker for Windows"
  2. Go to the General tab
    ![Capture2](https://user-images.githubusercontent.com/48975944/55050826-b38a6580-5078-11e9-8fe7-59928efbc924.JPG)

  3. Check the option to expose the daemon.
![Capture3](https://user-images.githubusercontent.com/48975944/55050828-b84f1980-5078-11e9-91ba-11c09ceaa939.JPG)

  4. Go to the Shared Drives tab and enable sharing all drives.
![Capture4](https://user-images.githubusercontent.com/48975944/55050831-bd13cd80-5078-11e9-9a83-4f097724daea.JPG)

What i am looking for is steps to do these operations using CLI only. Is that possible in docker for windows? 

Is that posssible by editing the daemon.json file?

**Comment by s-tuli** [comment]
I am also looking for the same. Any pointers? Thanks!

**Comment by GANG-CHEN-1** [comment]
> ### Problem
> I need to automate the process of setting up WSL to use the docker-desktop in windows 10.
> 
> I installed docker in windows 10 using the chococlatey package :
> https://chocolatey.org/packages/docker-desktop/2.0.0.3
> 
> The next step is to change the settings of docker desktop app to 'expose the daemon on tcp://localhost:2375 without TLS' and enable 'shared drives'.
> 
> Since the automation doesn't allow to use the GUI, i need to change these settings via some commands or CLI.
> 
> ### Information
> * Windows Version: Windows 10 Pro , version:1809
> * Docker for Windows Version: Version 2.0.0.3 (31259), Channel: stable
> 
> ### Steps to reproduce the behavior
> 1. Open "Docker for Windows"
> 2. Go to the General tab
>    ![Capture2](https://user-images.githubusercontent.com/48975944/55050826-b38a6580-5078-11e9-8fe7-59928efbc924.JPG)
> 3. Check the option to expose the daemon.
>    ![Capture3](https://user-images.githubusercontent.com/48975944/55050828-b84f1980-5078-11e9-91ba-11c09ceaa939.JPG)
> 4. Go to the Shared Drives tab and enable sharing all drives.
>    ![Capture4](https://user-images.githubusercontent.com/48975944/55050831-bd13cd80-5078-11e9-9a83-4f097724daea.JPG)
> 
> What i am looking for is steps to do these operations using CLI only. Is that possible in docker for windows?
> 
> Is that posssible by editing the daemon.json file?

Hey AnjannaAK, have you find a solution for this? would you please share it? thanks.
