### ISSUE TITLE
Cannot Connect to local Docker

### ISSUE THREAD

**Issue by ralusnom** [docker/for-win#3633]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: DA8F9127-BCFA-496A-A9E0-E565EB99CAAF/20190327185133

### Expected behavior
E.g. Using IDEA to connect to docker desktop windows or telnet localhost 2375
### Actual behavior
Cannot connect
### Information
The problem is always reproducible. I tried to completely uninstall Docker with registry cleanup and reinstallation. Same issues. Disables all firewalls or related software (virus scanner) - not working.

IDEA shows me this error:
`io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:2375 caused by: java.net.ConnectException: Connection refused: no further information
`
  - Windows Version: Windows 10 (1809)
  - Docker for Windows Version:  2.0.0.3

### Steps to reproduce the behavior
  1. come to my home
  2. open `cmd`
  3. type `telnet localhost 2375` 
  4. See the connection error message

**Comment by bahamut45** [comment]
👍 

![image](https://user-images.githubusercontent.com/3422019/55229110-5c24fa80-521c-11e9-8a27-197dc3437a25.png)

![image](https://user-images.githubusercontent.com/3422019/55229134-6a731680-521c-11e9-93bc-e58330734ad6.png)

![image](https://user-images.githubusercontent.com/3422019/55229172-85de2180-521c-11e9-86eb-d032c6b1d022.png)

**Comment by ralusnom** [comment]
thanks, bahamut45, but I forgot to mention, that I already enabled "expose daemon on port 2375".
I was running nicelay before upgrading to the October's Update 1809 and installing the latest 2.0.0.3 deamon.

:(

**Comment by ralusnom** [comment]
**SOLVED**. Maybe this could help others.
After doing a portcheck with PowerShell using the following command:

`Test-NetConnection -ComputerName localhost -Port 2375`
I saw all localhosts tries were "failed to connect".

Then I shut down the network adapters, one by one. And then the result of the check from above was:
> WARNUNG: TCP connect to (::1 : 2375) failed
> ComputerName     : localhost
> RemoteAddress    : 127.0.0.1
> RemotePort       : 2375
> InterfaceAlias   : Loopback Pseudo-Interface 1
> SourceAddress    : 127.0.0.1
> TcpTestSucceeded : True

Only 1 warning left, the others are gone. 👍 
Now, it works, I can connect from everywhere... Thx!

**Comment by bahamut45** [comment]
Thank you for diagnostic, i am disable the network adpaters one by one and restart docker-desktop. Now, it works.

**Comment by taeram** [comment]
Thanks for the tip! I just updated to Windows 10 1809 on Tuesday, and had this same issue.

I had two Network adapters installed by the FortiNet Client. I disabled both the "Ethernet 2" and "Ethernet 3" adapters and restarted Docker for Windows. I'm now able to connect to it on localhost:2347!

**Comment by maslke** [comment]
I had this same issue too, and still can't fix it out.
I disable all the network adapter but the wifi, but the docker didn't work.

**Comment by qqnc** [comment]
You saved me bro! I disabled one by one, and restarted the docker-desktop.  It works!

**Comment by TechMi97** [comment]
Yes managed to fix after disabling VPN, VirtualBox adapters. Its the problem with network adapters!. Thanks Alot!
