### ISSUE TITLE
Unable to Share C: drive with AzureAD credentials.

### ISSUE THREAD

**Issue by drchilds** [docker/for-win#364]
### Expected behavior
Selected drive is shared after entering AzureAD credentials.
### Actual behavior
1. User is prompted for credentials after selecting drive and clicking "Apply".
2. After a few seconds the selected drive is de-selected, and no error is shown.
### Information
  - Windows 10 Anniversary, fully patched.
  - Docker for Windows Beta 1.13.0-rc4-beta34 (9562)

### Steps to reproduce the behavior
See "Actual Behavior" above.

### Workaround
Sharing a drive with a privileged local account works as expected.

**Comment by rneugeba** [comment]
@drchilds Unfortunately, as explained in #132 this is not something we can fix. The workaround is to create a local user (see #132 and #303).
