### ISSUE TITLE
File Mode List for docker build

### ISSUE THREAD

**Issue by linquize** [docker/for-win#3641]
In Windows, there is no file mode. But in Linux, there is file mode.
To facilitate editing file on Windows, building Linux Container,
I suggest to add a file mode list `.dockermode`.
When `docker build` is called, docker client sends files to `docker daemon`.
Like `.dockerignore`, docker client can read `.dockermode` locally before sending files to `docker daemon`. If the file is found in `.dockermode`, override the file mode that is sent to docker daemon.
Instead of modifying `Dockerfile` to add `chmod` statements, the user writes an extra file `.dockermode` if he is using Windows client.

Syntax of `.dockermode`
```
build.sh 755
abc.txt 400
```

**Comment by linquize** [comment]
Any comment?

**Comment by linquize** [comment]
Anyone using Windows to build linux container?

**Comment by mat007** [comment]
This issue tracker is for Docker Desktop for Windows, general Windows container issues actually belong to https://github.com/moby/moby.
