### ISSUE TITLE
Crash issue

### ISSUE THREAD

**Issue by Osunkoyatolab** [docker/for-win#3647]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by pvizeli** [comment]
Crash on startup: EB698BE6-1403-4598-A129-6E0EC8DAC09E/20190329084130
