### ISSUE TITLE
Cannot set default-address-pools for Linux Docker Host VM

### ISSUE THREAD

**Issue by sumtec** [docker/for-win#3648]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 6529C422-4FDA-4030-8E76-F20BEEAD4994/20190329070839

### Expected behavior
Can set the daemon configuration file for my Linux Host VM on my Windows machine via the Setting -> Daemon panel. Especially, it should be able to set the default-address-pools.

### Actual behavior
Showing the following message and do not allow to apply.
"default-address-pools"; Must be a string array

This file is also different from the one in the Host VM. I tried to run the following command:
docker run --net=host --ipc=host --uts=host --pid=host -it --security-opt=seccomp=unconfined --privileged --rm -v /:/host alpine /bin/sh
chroot /host
cd /etc/docker
ls

What I found is that there's no docker.json. Changing it does not apply to the VM and the file will disappear after a restart. (Of course, but I tried a lot of different ways. That's why I tried this as last hope.)

I changed the file "C:\ProgramData\Docker\config" manually. The network created still follows the old pattern and generate unwanted address conflicts.

### Information

  - Windows Version: 10.0.17763.379
  - Docker for Windows Version: 2.0.3.0 (31778)

### Steps to reproduce the behavior

1. Right click on the tray icon.
2. Select Switch Linux container.
3. Right click on the tray icon.
4. Click settings.
5. Select Daemon
6. Change the config
7. Right click on the tray icon
8. Hit restart
9. Run:
docker run --net=host --ipc=host --uts=host --pid=host -it --security-opt=seccomp=unconfined --privileged --rm -v /:/host alpine /bin/sh
chroot /host
cd /etc/docker
ls
10. There's no daemon.json there

**Comment by jannispl** [comment]
I am experiencing the same issue.

**Comment by JorisVanEijden** [comment]
Doesn't have anything to do with Linux Docker Host.
The "Daemon" section of the settings is just broken on windows.

Setting "default-address-pools" through that screen simply cannot be done.
![image](https://user-images.githubusercontent.com/5211470/62114113-3c7b0d00-b2b6-11e9-9ef5-564c86dee9a6.png)

The json validation thinks it must be a string array, while in reality it needs to be an object array.
Editing the "%USERPROFILE%\.docker\daemon.json" manually and restarting docker for windows does work.

This is a bug in the json validation of the deamon.json in the gui of Docker Desktop.
