### ISSUE TITLE
Can't start docker service on windows server VM

### ISSUE THREAD

**Issue by josephgardner** [docker/for-win#365]
### Expected behavior
Docker service should start

### Actual behavior
WARNING: Waiting for service 'docker (Docker)' to start...
indefinitely

### Information

Running windows server 2016 in a parallels vm on osx. I was able to run the nanoserver helloworld, but the image dowload kept crashing with "unexpected EOF." I tried to pull the windowsservercore image,  same type of crashes. Rebooted and tried again a few times, but the service finally wouldn't start. I followed some suggestions in other issues to remove leftover nat/switch/etc. I tried uninstalling/reinstalling without any change. This is where I'm stuck. 

*diagnostics*
Checking for common problems
Describing Windows Version and Prerequisites
 [+] Is Windows 10 Anniversary Update or Windows Server 2016 99ms
 [+] Has KB3192366, KB3194496, or later installed if running Windows build 14393 80ms
 [+] Is not a build with blocking issues 128ms
Describing Docker is installed
 [+] A Docker service is installed - 'Docker' or 'com.Docker.Service'  32ms
 [-] Service is running 46ms
   Expected: {True}
   But was:  {False}
   39:         $AtLeastOneRunning | Should Be $true
   at <ScriptBlock>, <No file>: line 39
 [+] Docker.exe is in path 2.06s
 [+] Docker is registered in the EventLog service 24ms
Describing User has permissions to use Docker daemon
 [+] docker.exe should not return access denied 29ms
Describing Windows container settings are correct
 [+] Do not have DisableVSmbOplock set to 1 29ms
 [+] Do not have zz values set 25ms
Describing The right container base images are installed
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.25/images/json: open //./pipe/doc
ker_engine: The system cannot find the file specified.
 [-] At least one of 'microsoft/windowsservercore' or 'microsoft/nanoserver' should be installed 95m
s
   ValidationMetadataException: The argument is null or empty. Provide an argument that is not null
or empty, and then try the command again.
   ParameterBindingValidationException: Cannot validate argument on parameter 'Property'. The argume
nt is null or empty. Provide an argument that is not null or empty, and then try the command again.
   at <ScriptBlock>, <No file>: line 99
Describing Container network is created
 [+] At least one local container network is available 1.05s
 [-] At least one NAT, Transparent, or L2Bridge Network exists 27ms
   Expected {0} to be greater than {0}
   190:       $totalnets | Should BeGreaterThan 0
   at <ScriptBlock>, <No file>: line 190
 [-] NAT Network's vSwitch is internal 35ms
   Expected: {Internal}
   But was:  {}
   195:       $switchType | Should Be "Internal"
   at <ScriptBlock>, <No file>: line 195
 [-] Specified Network Gateway IP for NAT network is assigned to Host vNIC 38ms
   Expected: value to not be empty
   199:       $natGatewayIP | Should Not BeNullOrEmpty
   at <ScriptBlock>, <No file>: line 199
 [-] NAT Network's internal prefix does not overlap with external IP' 36ms
   Expected {0} to be greater than {0}
   226:         $hostips.Count | Should BeGreaterThan 0
   at <ScriptBlock>, <No file>: line 226
Showing output from: docker info

Showing output from: docker version
Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Showing output from: docker network ls

Warnings & errors from the last 24 hours

   ProviderName: docker

TimeCreated                     Id LevelDisplayName Message
-----------                     -- ---------------- -------
12/30/2016 6:32:54 PM            1 Error            Resolver Setup/Start failed for container no...
12/30/2016 6:21:45 PM            4 Error            fatal: Error starting daemon: Error initiali...
12/30/2016 6:21:44 PM            1 Error            Resolver Setup/Start failed for container no...
12/30/2016 6:08:04 PM            4 Error            fatal: Error starting daemon: Error initiali...
12/30/2016 6:08:04 PM            1 Error            Resolver Setup/Start failed for container no...
12/30/2016 8:49:54 PM            1 Error            Resolver Setup/Start failed for container no...
12/30/2016 8:35:18 PM            1 Error            Resolver Setup/Start failed for container no...
12/30/2016 7:52:16 PM            1 Error            Resolver Setup/Start failed for container no...
12/30/2016 1:05:56 PM            4 Error            fatal: Error starting daemon: Error initiali...
12/30/2016 1:05:56 PM            1 Error            Resolver Setup/Start failed for container no...
12/30/2016 1:04:08 PM            4 Error            fatal: Error starting daemon: Error initiali...
12/30/2016 1:04:08 PM            1 Error            Resolver Setup/Start failed for container no...
12/30/2016 12:54:21 PM           4 Error            fatal: Error starting daemon: pid file found...
12/30/2016 12:50:48 PM           4 Error            fatal: Error starting daemon: Error initiali...
12/30/2016 12:50:48 PM           1 Error            Resolver Setup/Start failed for container no...
12/30/2016 12:39:08 PM           4 Error            fatal: Error starting daemon: Error initiali...
12/30/2016 12:39:08 PM           1 Error            Resolver Setup/Start failed for container no...
12/30/2016 12:38:04 PM           4 Error            fatal: Error starting daemon: pid file found...
12/30/2016 12:33:15 PM           4 Error            fatal: Error starting daemon: pid file found...
12/30/2016 12:18:25 PM           4 Error            fatal: Error starting daemon: pid file found...
12/30/2016 12:11:36 PM           4 Error            fatal: Error starting daemon: pid file found...
12/30/2016 11:53:58 AM           4 Error            fatal: Error starting daemon: pid file found...
12/30/2016 2:49:13 PM            1 Error            Resolver Setup/Start failed for container na...
12/30/2016 2:49:13 PM            1 Error            Resolver Setup/Start failed for container no...
12/30/2016 11:30:47 AM           4 Error            fatal: Error starting daemon: pid file found...
12/30/2016 2:20:50 PM            1 Error            Resolver Setup/Start failed for container no...
12/29/2016 11:31:08 PM           1 Error            Resolver Setup/Start failed for container no...
12/29/2016 11:30:32 PM           4 Error            fatal: Error starting daemon: Error initiali...
12/29/2016 11:30:28 PM           1 Error            Resolver Setup/Start failed for container no...
12/29/2016 8:28:06 PM            4 Error            fatal: Error starting daemon: timeout
12/29/2016 8:24:31 PM            4 Error            fatal: Error starting daemon: pid file found...
12/29/2016 8:19:20 PM            4 Error            fatal: Error starting daemon: pid file found...
12/29/2016 8:17:32 PM            4 Error            fatal: Error starting daemon: pid file found...
12/29/2016 11:06:07 PM           1 Error            Resolver Setup/Start failed for container no...
12/29/2016 8:04:09 PM            4 Error            fatal: Error starting daemon: pid file found...
12/29/2016 8:02:44 PM            4 Error            fatal: Error starting daemon: pid file found...
12/29/2016 7:52:27 PM            4 Error            fatal: Error starting daemon: pid file found...
12/29/2016 7:40:59 PM            1 Error            Handler for POST /v1.25/containers/create re...
12/29/2016 10:39:39 PM           1 Error            Resolver Setup/Start failed for container no...
12/29/2016 8:49:50 PM            1 Error            Resolver Setup/Start failed for container no...
12/29/2016 8:41:41 PM            1 Error            Resolver Setup/Start failed for container no...
12/29/2016 8:34:42 PM            1 Error            Resolver Setup/Start failed for container no...
12/29/2016 8:26:12 PM            1 Error            Resolver Setup/Start failed for container no...

**Comment by simonferquel** [comment]
@friism  I think this one is not related to Docker for Desktop, could you redirect the issue to people working on Windows server containers ?

**Comment by friism** [comment]
@josephgardner can you re-open this here: https://github.com/Microsoft/Virtualization-Documentation/

You'll probably want to try to reset the networking as documented here: https://github.com/Microsoft/Virtualization-Documentation/tree/live/windows-server-container-tools/CleanupContainerHostNetworking#force-networking-cleanup
