### ISSUE TITLE
Docker4Windows: File Sharing Needs Password, My Computer Doesn't Have One

### ISSUE THREAD

**Issue by EnzoTheBrown** [docker/for-win#366]
### Expected behavior
make C:// a shared drive
### Actual behavior
Asking a password I don't have can't go further
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by simonferquel** [comment]
Hi @EnzoTheBrown By design, we rely on authenticated samba shares, so you need to protect your user account with a password to enable drive sharing

**Comment by rneugeba** [comment]
closing as this won't fix

**Comment by d4nc00per** [comment]
Is it possible to add something to the UI that explains why a password is enforced?

**Comment by Almusamim** [comment]
I hate passwords! :(

**Comment by Cperbony** [comment]
One solution found was create a User Windows Password.

**Comment by Cperbony** [comment]
One solution found was create a User Windows Password.

**Comment by Almusamim** [comment]
@Cperbony that is not a solution!

**Comment by Deilan** [comment]
@rn What's the problem with letting to enter a blank password? If it's not valid it would be rejected anyway.

![image](https://user-images.githubusercontent.com/4777512/42883463-536c2250-8aa4-11e8-99a2-6c9bbd0e2e28.png)

**Comment by WiseUA** [comment]
Maybe you are using a windows account, in which case you must enter a password here from the microsoft account.
For me it works.

**Comment by adrianotsi** [comment]
Yes,  thanks @WiseUA works for me🥇

**Comment by mansoncui** [comment]
I still can't use the Microsoft Windows password

**Comment by mansoncui** [comment]
I still can't use my Microsoft password

**Comment by mozzgov** [comment]
You can create a new user (DockerUser) with a password and make it shared. FAQ - [http://peterjohnlightfoot.com/docker-for-windows-on-hyper-v-fix-the-host-volume-sharing-issue/](url)

**Comment by sicdigital** [comment]
I used my the default username and my Microsoft password.

**Comment by ahmetanbar** [comment]
> @Deilan Maybe you are using a windows account, in which case you must enter a password here from the microsoft account.
> For me it works.
Thanks it works for me.

**Comment by minhlong** [comment]
Thanks @WiseUA It works

**Comment by okumo** [comment]
Thanks @WiseUA

**Comment by petermorlion** [comment]
Yes, I can confirm: if you have a Microsoft account, remove the <computer>\<user> username entirely, and enter your Microsoft account's email address (x.y@outlook.com for example). Then enter that account's password. Works.

**Comment by IronSean** [comment]
Note for those still having trouble, a Microsoft account is not the same as an Azure ActiveDirectory account which is what your School or Work might have for you. So if your proper Microsoft/AzureAD password isn't working, making another local user on the machine might be easiest.
