### ISSUE TITLE
I can't disable Docker's automatic initialization on Windows logon

### ISSUE THREAD

**Issue by reebr** [docker/for-win#3669]
### Expected behavior
Allow disable automatic initialization of Docker.

### Actual behavior
It Is being automatically initialized at logon even with the setting being disabled.
![general settings](https://user-images.githubusercontent.com/3982052/55381931-bebb1680-54fa-11e9-9e89-1e57ea154d38.png)

### Information
I am trying to disable the Docker auto initialization when I log on to Windows, but even disabling this option, Docker is initialized. I have no history of previous use of Docker on this machine, I just did a clean install.

  - Windows Version: Windows 10 Pro - Version 1809 (17763.379)
  - Docker for Windows Version: 2.0.0.3 (31259)

### Steps to reproduce the behavior
1. Install Docker for Windows
2. Go to the "general settings" menu and disable automatic startup
3. Restart the machine and wait, Docker will start automatically

**Comment by ulrich** [comment]
Hello @reebr 

I can reproduce this bug, thanks for your feedback! I put a ticket for the Docker Desktop team.

**Comment by reebr** [comment]
@ulrich thank you.
Is there any link to track the ticket created for this bug?

**Comment by ulrich** [comment]
@reebr hum, the ticket is on private issue tracker, but for information this bug is fixed in Edge version of Docker Desktop available [here](https://docs.docker.com/docker-for-windows/edge-release-notes/).
