### ISSUE TITLE
Docker starting error

### ISSUE THREAD

**Issue by skumarjain1169** [docker/for-win#3671]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ulrich** [comment]
Hello @skumarjain1169 

Can you generate diagnostic via the Diagnose and Feedback action in contextual menu?
