### ISSUE TITLE
docker windows login failed

### ISSUE THREAD

**Issue by dineshacce** [docker/for-win#3672]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ulrich** [comment]
Hello @dineshacce 

Maybe can you retry to login in Docker Desktop with your username and not your email. Thank you for your feedback if that works for you.
