### ISSUE TITLE
impatient whale: Docker desktop does not wait for Automatic (Delayed Start) service

### ISSUE THREAD

**Issue by R-Adrian** [docker/for-win#3673]
- [x ] I have tried with the latest version of my channel (Stable or Edge): Docker is freshly installed an hour ago, using Version 2.0.0.3 (31259), Channel: stable
  - [ ] I have uploaded Diagnostics: NO

### Expected behavior
Since this is my regular use desktop PC, i have configured the heavy performance hit services to **Automatic (Delayed start)** instead of the default Automatic mode, via the Windows service manager.

After system start/reboot, Docker desktop should wait for the services to start:
- vmms: Hyper-V Virtual Machine Management
- com.docker.service: Docker Desktop Service

### Actual behavior
Instead of waiting for the services to start, Docker will complain immediately at logon:

![impatient_whale](https://user-images.githubusercontent.com/16319504/55394617-627ee380-5548-11e9-8353-5b564bfd5e2f.png)

and if i press the Quit button, since i know that the service is actually starting, just with a slight delay, i'm getting this error:

![impatient_whale2](https://user-images.githubusercontent.com/16319504/55394733-9fe37100-5548-11e9-8d20-9cc285d8dd04.png)

```
Docker Desktop service is not running
   at Docker.WPF.BackendClient.CheckService(String action) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:line 305
   at Docker.WPF.BackendClient.SendMessage(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:line 167
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```

The problem might also be compounded by the fact that the Docker service does not have a dependency link to the Hyper-V Service, so, since non-related services usually will start in alphabetical order, Windows will actually try to start the Docker service BEFORE starting the Hyper-V Virtual Machine Management service.

![impatient_whale3](https://user-images.githubusercontent.com/16319504/55395358-06b55a00-554a-11e9-93c2-fac217e28fc8.png)

### Information
  - Windows Version: Windows 10 Pro 1809 x64, Version 17763.404
  - Docker for Windows Version: Version 2.0.0.3 (31259), Channel: stable, Build: 8858db3

### Steps to reproduce the behavior
  1. Just set the HyperV manager and Docker services to Delayed automatic start mode.
  2. restart the entire system
  3. log on to desktop, watch the whale fail immediately.

**Comment by R-Adrian** [comment]
note: after i shutdown Docker from the red tray icon, and i start it again after the Hyper-V and Docker services are running, it will start and run normally.

**Comment by aghanem** [comment]
Hi @R-Adrian,
I also faced this issue and I thought that the service dependency is the reason for this problem , so I added the docker desktop and the vmms services as a dependency to the docker engine service using the following command:
 sc command (sc config docker depend= com.docker.service/vmms) 
![image](https://user-images.githubusercontent.com/2403613/60046188-677aab80-96cf-11e9-8922-10c57a6a99fe.png)

But this didn't solve the problem and I got the same error after restarting. So I checked and found that there is a 3rd application for docker added to the auto start 
![image](https://user-images.githubusercontent.com/2403613/60046271-9729b380-96cf-11e9-9e07-2498b275b818.png)

So I went a head and disabled both entries for docker which are pointing to this executable:
C:\Program Files\Docker\Docker\Docker for Windows.exe

Once I disabled both of the entries and restarting, I didn't see the problem but now I have to manually start the docker app by double clicking on the docker desktop icon which points to the same above executable file. But of course, I had to wait until the docker services started.

Then I created a scheduled task to start this app automatically 5 minutes from user logon . This allowed the docker services to start before the schedule task runs, **problem solved.**
Here is the definitiaon for the schedule task I created, please copy the xml text into a new xml file and import it using windows schedule tasks and It will create the schedule task for you.

<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Date>2019-06-24T21:39:45.4745109</Date>
    <Author>AnasGhanemPC\Anas</Author>
    <URI>\Docker desktop</URI>
  </RegistrationInfo>
  <Triggers>
    <LogonTrigger>
      <Enabled>true</Enabled>
      <Delay>PT5M</Delay>
    </LogonTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>S-1-5-21-2970791990-2456468932-2830624274-1001</UserId>
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>true</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>false</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>true</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT72H</ExecutionTimeLimit>
    <Priority>7</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>"C:\Program Files\Docker\Docker\Docker for Windows.exe"</Command>
    </Exec>
  </Actions>
</Task>

**Comment by R-Adrian** [comment]
update:
 i am currently on Docker version 2.1.0.3 stable on my laptop and the error message when pressing the quit button is no longer happening.
- the Docker desktop app is exiting cleanly without any error message if i press the "Quit" button,
- the docker desktop service is now waiting for the Hyper-V Virtual Machine Management service to start and if it doesn't start in a reasonable time it will actually send it a start command too. I tested this chain of events by setting both services to Manual start and then i started only the Docker service... after about a minute of waiting the Docker service started the Hyper-V Virtual Machine Management service.

so, i can finally call this bug resolved. Thanks.
