### ISSUE TITLE
Can't run docker on wnidows

### ISSUE THREAD

**Issue by jemappelleMarie** [docker/for-win#3677]
### Actual behavior
I can't run docker, it sends this error: Hardware assisted virtualization and data execution protection must be enabled in the BIOS
### Information
  - Windows Version: Windows 10 Pro
  - Docker for Windows Version: Docker version 18.09.2, build 6247962

I've searched and tried a lot of solutions but still I receive the same error! The virtualization is also enabled.

**Comment by ulrich** [comment]
Hello @jemappelleMarie 

I think that you don't have Hyper-V enabled on your host. Can you check with this command on a PowerShell run as administrator?

`Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-All -Online`

**Comment by jemappelleMarie** [comment]
Hello @ulrich 
Thanks for your help.
I did what you said and Hyper-V is enabled but still receiving the same error :(

**Comment by ulrich** [comment]
Hello @jemappelleMarie 

Whit is your arch (Intel / AMD) ?

**Comment by ulrich** [comment]
Also, do you have another virt. tools like Virtualbox or others installed?

**Comment by jemappelleMarie** [comment]
Thanks for your help @ulrich
Intel(R) Core(TM)2 Duo CPU T6670 @ 2.20GHz
I installed docker toolbox and then Oracle VM VirtualBox was installed on my laptop.

**Comment by ulrich** [comment]
Hello @jemappelleMarie 

Please uninstall Docker Toolbox and VirtualBox. After that you need to reset to defaults factory your Docker Desktop installation.

**Comment by jemappelleMarie** [comment]
Thank @ulrich 
I uninstalled them. I also uninstalled docker and installed it again but still the same error :\

**Comment by ulrich** [comment]
@jemappelleMarie Do you have another virtualization tools on your host? If yes, uninstall them.

You can also reset to defaults the BIOS/UEFI settings.

**Comment by jemappelleMarie** [comment]
@ulrich 
No, I don't have any!
Sorry, I didn't get it! What should I do in The BIOS?!

**Comment by ulrich** [comment]
@jemappelleMarie you can find a button/action in the BIOS user interface aims to reset to defaults settings.

Maybe do you have to reset the settings of Hyper-V, for that's: uncheck all Hyper-V components in the Windows settings, restart the system, enable Hyper-V again.

**Comment by jemappelleMarie** [comment]
Thanks @ulrich 
I did it but still no progress! Also "Hyper-V Hypervisor" option is disabled and grayed and I can't enable it!

**Comment by ulrich** [comment]
@jemappelleMarie do you use the Windows Features panel?

Can you check if you find DockerDesktopVM and if it is running in Hyper-V manager?

**Comment by jemappelleMarie** [comment]
@ulrich  Yes, Windows Features
I checked Hyper-V Manager and if I'm not mistaken Docker is not running!

**Comment by ulrich** [comment]
Unfortunately I can't see what is the problem for now. I will see with my team member to find an another way to explore.

**Comment by ulrich** [comment]
> Sorry, I didn't get it! What should I do in The BIOS?!

Did you reset the default settings in your BIOS?

**Comment by jemappelleMarie** [comment]
> 
> 
> > Sorry, I didn't get it! What should I do in The BIOS?!
> 
> Did you reset the default settings in your BIOS?

Yes, I did.

**Comment by jemappelleMarie** [comment]
> 
> 
> Unfortunately I can't see what is the problem for now. I will see with my team member to find an another way to explore.

Thanks a lot for your help. I hope a solution will be found!
