### ISSUE TITLE
Docker commit is not working on windows Server 2019.

### ISSUE THREAD

**Issue by Piyush22394** [docker/for-win#3682]
I have Windows Server 2019 VM to work with Docker, having 250Gb of HDD and 16 GB ram.

I have written a dockerfile for copying some setups and then manually runs the installation on Containers. Now I need to creaet the image using those containers. When i use Docker commit it gives issue as 
"Error response from daemon: re-exec error: exit status 1: output: time=“2019-04-02T12:22:17+05:30” level=error msg=“hcsshim::ImportLayer failed in Win32: The system cannot find the path specified. (0x3) path=\\?\C:\ProgramData\Docker\windowsfilter\5bb9eea39e188d382fb8f336112584f3100797ac9fa887012e70c78fa7f2245a folder=C:\ProgramData\Docker\tmp\hcs981676719”
hcsshim::ImportLayer failed in Win32: The system cannot find the path specified. (0x3) path=\?\C:\ProgramData\Docker\windowsfilter\5bb9eea39e188d382fb8f336112584f3100797ac9fa887012e70c78fa7f2245a folder=C:\ProgramData\Docker\tmp\hcs981676719"

I am running the following docker specifications. I am using mcr.microsoft.com/windows/servercore:ltsc2019 image to perform all tasks.

Docker Version:
Client: Docker Engine - Community
Version: 18.09.2
API version: 1.39
Go version: go1.10.8
Git commit: 6247962
Built: Sun Feb 10 04:12:31 2019
OS/Arch: windows/amd64
Experimental: false

Server: Docker Engine - Community
Engine:
Version: 18.09.2
API version: 1.39 (minimum version 1.24)
Go version: go1.10.6
Git commit: 6247962
Built: Sun Feb 10 04:28:48 2019
OS/Arch: windows/amd64
Experimental: false

Error:

PS C:\data1> docker ps #Checking running containers

CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
fcc9a5618b85 radia-core:v1 “c:\windows\system32…” 20 hours ago Up 18 hours 3464/tcp, 3466/tcp kind_heisenberg

PS C:\data1> docker stop fcc   #Stop container
fcc

Here i stopped running container and tried to commit the container but it is giving error. Any help is appreciated

thanks in Advance…!.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Container should be committed and provided SHA value.
### Actual behavior
PS C:\data1> docker commit fcc9a5618b85 test:v1 #Committing Container

Error response from daemon: re-exec error: exit status 1: output: time=“2019-04-02T12:22:17+05:30” level=error msg=“hcsshim::ImportLayer failed in Win32: The system cannot find the path specified. (0x3) path=\\?\C:\ProgramData\Docker\windowsfilter\5bb9eea39e188d382fb8f336112584f3100797ac9fa887012e70c78fa7f2245a folder=C:\ProgramData\Docker\tmp\hcs981676719”
hcsshim::ImportLayer failed in Win32: The system cannot find the path specified. (0x3) path=\?\C:\ProgramData\Docker\windowsfilter\5bb9eea39e188d382fb8f336112584f3100797ac9fa887012e70c78fa7f2245a folder=C:\ProgramData\Docker\tmp\hcs981676719

### Information

  - Windows Version:
  - Docker for Windows Version:2.0.0.3

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Heneman** [comment]
Same thing. Windows Server 2019 v1809, 8gb RAM, 80gb HDD. Using `mcr.microsoft.com/windows:1809` as base image, manually installing tool, trying to commit the resulting container and getting this error:
```
PS C:\Windows\system32> docker commit 2b1a94cb66a7 image:tag
Error response from daemon: re-exec error: exit status 1: output: time="2019-07-31T09:48:17-05:00" level=error msg="hcsshim::ImportLayer - failed failed in Win32: The system cannot find the path specified. (0x3)" error="hcsshim::ImportLayer - failed failed in Win32: The system cannot find the path specified. (0x3)" importFolderPath="C:\\ProgramData\\docker\\tmp\\hcs997464039" path="\\\\?\\C:\\ProgramData\\docker\\windowsfilter\\54ce3262a89253fc5e585c1d0d528984ea534053deab17105eeeec2bb02f1151"
hcsshim::ImportLayer - failed failed in Win32: The system cannot find the path specified. (0x3)
```
