### ISSUE TITLE
Start container in non admin account errors

### ISSUE THREAD

**Issue by aristofanisl** [docker/for-win#3684]
Hi all,
i created a container with mysql (also tried mariadb) and when i start it i wont start giving the errors below (taken from container log)
`{"log":"2019-04-03  6:15:08 0 [Note] mysqld (mysqld 10.3.13-MariaDB-1:10.3.13+maria~bionic) starting as process 1 ...\n","stream":"stderr","time":"2019-04-03T06:15:07.9854062Z"}
{"log":"2019-04-03  6:15:08 0 [Warning] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive\n","stream":"stderr","time":"2019-04-03T06:15:07.9914234Z"}
{"log":"2019-04-03  6:15:08 0 [ERROR] mysqld: Can't lock aria control file '/var/lib/mysql/aria_log_control' for exclusive use, error: 95. Will retry for 30 seconds\n","stream":"stderr","time":"2019-04-03T06:15:07.9984092Z"}
{"log":"2019-04-03  6:15:39 0 [ERROR] mysqld: Got error 'Could not get an exclusive lock; file is probably in use by another process' when trying to use aria control file '/var/lib/mysql/aria_log_control'\n","stream":"stderr","time":"2019-04-03T06:15:39.0443424Z"}
{"log":"2019-04-03  6:15:39 0 [ERROR] Plugin 'Aria' init function returned error.\n","stream":"stderr","time":"2019-04-03T06:15:39.0473342Z"}
{"log":"2019-04-03  6:15:39 0 [ERROR] Plugin 'Aria' registration as a STORAGE ENGINE failed.\n","stream":"stderr","time":"2019-04-03T06:15:39.0473342Z"}
{"log":"2019-04-03  6:15:39 0 [Note] InnoDB: Using Linux native AIO\n","stream":"stderr","time":"2019-04-03T06:15:39.0492981Z"}
{"log":"2019-04-03  6:15:39 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins\n","stream":"stderr","time":"2019-04-03T06:15:39.0573645Z"}
{"log":"2019-04-03  6:15:39 0 [Note] InnoDB: Uses event mutexes\n","stream":"stderr","time":"2019-04-03T06:15:39.0573645Z"}
{"log":"2019-04-03  6:15:39 0 [Note] InnoDB: Compressed tables use zlib 1.2.11\n","stream":"stderr","time":"2019-04-03T06:15:39.0573645Z"}
{"log":"2019-04-03  6:15:39 0 [Note] InnoDB: Number of pools: 1\n","stream":"stderr","time":"2019-04-03T06:15:39.0583802Z"}
{"log":"2019-04-03  6:15:39 0 [Note] InnoDB: Using SSE2 crc32 instructions\n","stream":"stderr","time":"2019-04-03T06:15:39.0583802Z"}
{"log":"2019-04-03  6:15:39 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M\n","stream":"stderr","time":"2019-04-03T06:15:39.0604216Z"}
{"log":"2019-04-03  6:15:39 0 [Note] InnoDB: Completed initialization of buffer pool\n","stream":"stderr","time":"2019-04-03T06:15:39.114398Z"}
{"log":"2019-04-03  6:15:39 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().\n","stream":"stderr","time":"2019-04-03T06:15:39.1154025Z"}
{"log":"2019-04-03  6:15:39 0 [ERROR] InnoDB: Unable to lock ./ibdata1 error: 95\n","stream":"stderr","time":"2019-04-03T06:15:39.1173992Z"}
{"log":"2019-04-03  6:15:39 0 [Note] InnoDB: Retrying to lock the first data file\n","stream":"stderr","time":"2019-04-03T06:15:39.1173992Z"}
{"log":"2019-04-03  6:15:40 0 [ERROR] InnoDB: Unable to lock ./ibdata1 error: 95\n","stream":"stderr","time":"2019-04-03T06:15:40.1203741Z"}`

I have to mention that my account is non admin account.
I placed my account on docker group and set the hyper V management service to auto start (was disabled)
Although docker is starting with no problems it doesnt seem to run containers.
I am thinking something about file persmissions since i am not an admin at the current pc.
I also changed the "graph" parameter in daemon.json and set it to a directory that i created with my account.

Any ideas would be very helpful

Thank you in advance!

**Comment by aristofanisl** [comment]
My docker compose yml file
`# Use root/example as user/password credentials
version: '3'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - "./db/data:/var/lib/data"
    ports:
      - 3306:3306`

**Comment by mi-hol** [comment]
lifecycle frozen
