### ISSUE TITLE
Docker for Win wont accept HTTP Proxy with password auth

### ISSUE THREAD

**Issue by weidi** [docker/for-win#369]
### Expected behavior
In the Proxies Section there should be an additional fiel for authentication
### Actual behavior
even when writing down user:pass@proxy docker wont be able to connect to docker backend
![image](https://cloud.githubusercontent.com/assets/2188062/21672915/d4170bf0-d325-11e6-8bb6-1e3580f6262e.png)

### Information
[08:51:05.305][Notifications  ][Error  ] Failed to connect to dockerBackend: time out
Version: 1.13.0-rc4-beta34 (9562)
OS: Windows 10 Enterprise
Id: 1607
Build: 14393
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by simonferquel** [comment]
Can you try with the proper http:// prefix ? like http://user:pass@host:port ?

**Comment by dgageot** [comment]
Hi @weidi Any chance you got to try with `http://` prefix?

**Comment by weidi** [comment]
Hi @simonferquel @dgageot , It´s not working with or without http://
I get:
`[10:51:39.227][UpdateFeedDownloader][Error`  ] The remote server returned an error: (407) Proxy Authentication Required.`
Also a problem is, that the UI stays in Docker is starting mode and i´m unable to cancle this to edit settings, so i do have to do it manually in settings.json

**Comment by dgageot** [comment]
@simonferquel any idea?

**Comment by simonferquel** [comment]
No idea, maybe a proxy server with a fancy authentication protocol ?

**Comment by weidi** [comment]
It´s a bluecoat proxy and until now i managed connections through it with
every piece of software even my own ;)

2017-02-08 16:35 GMT+01:00 Simon Ferquel <notifications@github.com>:

**Comment by weidi** [comment]
I think it´s a 407 based authentication method so any browser or so prompts
for a password. Normally any other tool or linux is working when specifying
e.g. http_proxy="http://user:password@proxy.fqdn.net"

2017-02-10 10:11 GMT+01:00 Simon Ferquel <notifications@github.com>:

**Comment by kewne** [comment]
Using the "http://user:password@proxy_host:port/" format worked for me, the only thing to look out for is that the password needs to be URL encoded.

**Comment by rondinif** [comment]
..microsoft based proxy corporate will accept
Proxy-Authenticate: Negotiate
Proxy-Authenticate: Kerberos
Proxy-Authenticate: NTLM
Unfortunately as far as Docker CE 17.09.9-ce-win33 (13620) it try to
CONNECT registry-1.docker.io:443 HTTP/1.1
Host: registry-1.docker.io:443
User-Agent: Go-http-client/1.1
Proxy-Authorization: Basic

therefore an authentication method more robust than "Basic" is required in some case

**Comment by hirameki** [comment]
Thank you for response. I test it Mac OS and Windows, but not linux.
Docker for Linux not same? OK, I will test it Ubuntu and Cent OS.
Give me some some time for install linux to real machine.

**Comment by xDouglasx** [comment]
Enconding not working anymore, im using version of 2.0.0.0 of docker 
when i try run

docker pull swaggerapi/swagger-editor
i receive proxy authentication required.

i was running it with the following configuration:
http://username:password@host/proxi.js

my password is something@123 and i was using something%64123
%64 = @ 

i tried everything, the only thing that worked for me was changing my password 
to one that hasnt special characters since encoding wasnt working

**Comment by stphdenis** [comment]
Use %40 an not %64.
It have to be in HEX.

**Comment by jain2010** [comment]
I have used each and every method of proxy settings, but not getting the result. An error of proxy authentication required is being highlighting. Please suggest any method.
