### ISSUE TITLE
No working after Windows 10 upgrade to Version 10.0.17134.677

### ISSUE THREAD

**Issue by Mart-Bogdan** [docker/for-win#3703]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 4F92A185-602D-408E-92F8-47283C2C3EA4/20190406214135
  - Diagnostics ID: 4F92A185-602D-408E-92F8-47283C2C3EA4/20190406214002

### Expected behavior
I've updated windows due to reggular windows update.  I'm using latest Docker for widows, it states that no updates available:
![image](https://user-images.githubusercontent.com/775038/55675731-209ac800-58cf-11e9-956d-37a60b30ca5b.png)

### Actual behavior
After update  this docker isn't starting.
### Information

  - Windows Version: 10.0.17134.677
  - Docker for Windows Version: 2.0.0.31259

### Steps to reproduce the behavior

```
>docker images
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/images/json: open //./pipe/docker
_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the
 docker client must be run elevated to connect. This error may also indicate that the docker daemon is
not running.
```

P.S. I shall try fctory reset, but that's not plesant, to lose all volumes, etc.

**Comment by Mart-Bogdan** [comment]
I've made a factory reset, but it still don't work.

Diagnostics ID: 4F92A185-602D-408E-92F8-47283C2C3EA4/20190409131539

I checked, Hyper-V is operational, was able to create custom VM. But docker didn't create MobyLinux VM

**Comment by mikeparker** [comment]
We've seen multiple tickets about windows update breaking Hyper-V. Relevant logs:

```
[12:48:34.476][HyperV         ][Info   ] Script started at 12:48:34.476
[12:48:34.488][HyperV         ][Info   ] Modules loaded at 12:48:34.488
[12:48:34.514][HyperV         ][Info   ] Creating Switch: DockerNAT...
[12:48:39.391][HyperV         ][Info   ] Switch created.
[12:48:39.670][NamedPipeServer][Error  ] Unable to execute Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The object already exists.
```

Potential duplicates and suggested fixes here https://github.com/docker/for-win/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Unable+to+create%3A+The+running+command+stopped+because+the+preference+variable+%22ErrorActionPreference%22+or+common+parameter+is+set+to+Stop%3A+The+object+already+exists.
