### ISSUE TITLE
[Docker Desktop] - All ports seen to be closed after few minutes

### ISSUE THREAD

**Issue by gantispam** [docker/for-win#3705]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [X ] I have uploaded Diagnostics
  - Diagnostics ID:9845D1F9-BFAB-49E4-8D62-54B06CF8E749/20190407092541

### Expected behavior
Running some Docker container without interruption.

### Actual behavior
Docker work fine but after few minutes (random minutes) all ports seen to be closed (test with 3306, 1080, 9002, ...).
On another hand docker work fine for shell command : docker ps, docker exec, docker run, etc.
I need to Restart "Docker Desktop" to solve this bug.

### Information
  - Windows Version: W10 pro
  - Docker for Windows Version: Docker version 18.09.2, build 6247962
  - Used on "Linux container"

I tryed to disable : 
- windows defender firewall
- declare network vEthernet (DockerNAT) as private and trust
- Disable antivirus and firewall (Bitdefender Internet Security)

### Steps to reproduce the behavior
  1. Install Docker (HyperV : mobyLinuxVm) and switch to "Linux container"
  2. Build somes containers with docker-compose and expose somes ports. Exemple : curl http://127.0.0.1:9000 = OK
  3. wait few minutes..
  4. All ports seens to be closed... Exemple : curl http://127.0.0.1:9000 = curl: (7) Failed connect to 127.0.0.1:1080; Connection refused

**Comment by gantispam** [comment]
I'm not sure there is a relation but some times on build step (docker-compose up --build) : 
`ERROR: for CONTAINER-NAME  Cannot start service CONTAINER-NAME: error while creating mount source path '/host_mnt/c/00_projects_current/FOLDER_TOMOUNT': mkdir /host_mnt/c: file exists
ERROR: Encountered errors while bringing up the project.`

**Comment by gantispam** [comment]
I tried to uninstall+eboot+install+reboot : without success. 
Same issue 👎

**Comment by gantispam** [comment]
Wiresharl trace on Npcap LoopBack adapter : 
`15520	589.093660	127.0.0.1	127.0.0.1	TCP	86	[TCP Keep-Alive] 3306 → 52840 [ACK] Seq=2 Ack=1 Win=10224 Len=1[Reassembly error, protocol TCP: New fragment overlaps old data (retransmission?)]`

![bug-docker](https://user-images.githubusercontent.com/15685552/55754730-a2b0fb00-5a4d-11e9-80ac-e0159fdea4b0.png)

**Comment by mikeparker** [comment]
Hi, could you give an example image, docker-compose file you're using so I can try to repro this?

**Comment by gantispam** [comment]
Thx.
`version: '2.1'

services:
    myapp-mariadb:
        image: mariadb:10.3.7
        container_name: myapp-mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
            - MYSQL_PASSWORD=$MYSQL_PASSWORD
        ports:
            - 3306:3306
        networks:
            myapp_network:
                ipv4_address: 173.20.0.3
    elasticsearch-1:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
        environment:
            - discovery.zen.minimum_master_nodes=1
        ports:
            - 9200:9200
        networks:
            myapp_es_network:
                ipv4_address: 173.30.0.2
        healthcheck:
            test: curl -s http://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
            interval: 60s
            timeout: 30s
            retries: 5
    elasticsearch-2:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
        networks:
            myapp_es_network:
                ipv4_address: 173.30.0.3
        healthcheck:
            test: curl -s http://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
            interval: 120s
            timeout: 60s
            retries: 5
    wait_until_ready:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
        command: /usr/bin/true
        depends_on: {"elasticsearch-1": {"condition": "service_healthy"}}

networks:
    myapp_network:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 173.20.0.0/24
              gateway: 173.20.0.1
    myapp_es_network:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 173.30.0.0/24
              gateway: 173.30.0.1

volumes:
    myapp_v_mariadb:
    myapp_v_es_1:
    myapp_v_es_2:`

This is an resume (i'm use Extends function on real life and more containers).

This bug is only on Docker-for-win. 
For now, I have installed docker on linux VM (Windows HOST) and it's work fine...

**Comment by gantispam** [comment]
Same things for more simple docker-compose : 


[mariadb.yml.log](https://github.com/docker/for-win/files/3097572/mariadb.yml.log)
