### ISSUE TITLE
forever starting...

### ISSUE THREAD

**Issue by chenkezhe** [docker/for-win#3710]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID:
ABA10A76-CDAE-4A3C-A3FC-B4EBEA02A681/20190408151107

### Expected behavior
    starting as normal

### Actual behavior
    can NOT finish starting

### Information

  - Windows Version: win10 14393
  - Docker for Windows Version: Version 2.0.0.0-win81 

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mikeparker** [comment]
Relevant log line:
[13:04:00.542][VpnKit         ][Error  ] vpnkit.exe: Caught 使用了与请求的协议不兼容的地址�?
[13:04:00.542][VpnKit         ][Info   ]  while creating Hyper-V socket
[13:04:00.542][VpnKit         ][Error  ] vpnkit.exe: Caught 使用了与请求的协议不兼容的地址�?
[13:04:00.542][VpnKit         ][Info   ]  while creating Hyper-V socket

Translated as `Used an address that is incompatible with the requested protocol`

I suspect this is a problem with Hyper-V, there are a couple of potential solutions:
1) Upgrade Windows - you are using an old version when Hyper-V was young
2) Uninstall + Reinstall Hyper-V

Sorry I can't be much more help.
