### ISSUE TITLE
Error response from daemon: invalid volume specification

### ISSUE THREAD

**Issue by Assassinxxxx** [docker/for-win#3711]
This is what I enter:
docker run --rm --env-file deepfigures-local.env --volume E:\常用文档\信息管理课程设计\deepfigures-open-master\TestOutcome: --volume E:\常用文档\信息管理课程设计\deepfigures-open-master\TestPdf: deepfigures-cpu:0.0.1 python3 /work/scripts/rundetection.py      1.pdf

This is what I get:
docker: Error response from daemon: invalid volume specification: '/host_mnt/e/常用文档/信息管理课程设计/deepfigures-open-master/TestOutcome:'.
See 'docker run --help'.

I cannot figure out this issue, neither can I understand why there's an "host_mnt" before my path. Can anyone help me?

**Comment by mikeparker** [comment]
Hi, it looks like you're missing the 2nd part of the volume specification, i.e. you must specify source:destination

try something like
```
docker run --rm --env-file deepfigures-local.env --volume E:\常用文档\信息管理课程设计\deepfigures-open-master\TestOutcome:/destination1 --volume E:\常用文档\信息管理课程设计\deepfigures-open-master\TestPdf:/destination2 deepfigures-cpu:0.0.1 python3 /work/scripts/rundetection.py 1.pdf
```
You may have more luck using `--mount` as this is more modern flag and has more comprehensive documentation and simpler syntax: https://docs.docker.com/storage/volumes/

We will also improve the error message and get rid of the `host_mnt` as it's an internal concern.
