### ISSUE TITLE
WSL Cannot Connect to local Docker

### ISSUE THREAD

**Issue by yunfandev** [docker/for-win#3713]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C9FA72BB-030C-4689-9541-82CF2267DBB4/20190408165716

### Expected behavior
Manage docker from wsl
### Actual behavior
Cannot connect to the Docker daemon at tcp://localhost:2375. Is the docker daemon running?
### Information

  - Windows Version: 10.0.17763.379
  - Docker for Windows Version: 2.0.0.3 (31259)

### Steps to reproduce the behavior

  1. Upgrade Windows from 1803 to 1809

**Comment by yunfandev** [comment]
I try to re-enable hyper-v and then reinstall docker for windows, but the problem still exists.

**Comment by yunfandev** [comment]
I found that other people have similar problems #3633 #3662, but they will be fine after reinstall.

**Comment by yunfandev** [comment]
Is this because I just re-enable hyper-v but did not delete hyper-v default switch?

**Comment by yunfandev** [comment]
I have tried to remove hyper-v then uninstall hyper-v default switch from device manager and delete it from registry "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\vmsmp\parameters\SwitchList".
After this, enable hyper-v and reinstall docker for windows, but the problem still exists.😭😭😭😭😭😭😭😭😭😭

**Comment by designgears** [comment]
What ended up fixing this @yunfandev ??
