### ISSUE TITLE
What is the difference of Windows Installers

### ISSUE THREAD

**Issue by juniormayhe** [docker/for-win#3724]
An installer is available at https://runnable.com/docker/install-docker-on-windows-10
And another windows installer is available at https://www.docker.com/products/docker-desktop

Which one is correct for Windows 10?

**Comment by lorenrh** [comment]
I suggest you use the one from Docker's official page -> https://www.docker.com/products/docker-desktop

**Comment by mikeparker** [comment]
Yes, the original link is an old link, please use the latest version.
