### ISSUE TITLE
Cant start docker

### ISSUE THREAD

**Issue by DawidKowalczyk** [docker/for-win#3726]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Inconsistent parameters PolicyStore PersistentStore and Dhcp Enabled

   w Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) w C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:wiersz 36
   w Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) w C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:wiersz 92
   w Docker.Actions.<>c__DisplayClass21_0.<ResetToDefault>b__0() w C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:wiersz 155
   w Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() w C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:wiersz 59

**Comment by DawidKowalczyk** [comment]
cant run docker on win10

**Comment by mikeparker** [comment]
Hi, this is tough to diagnose, `Inconsistent parameters PolicyStore PersistentStore and Dhcp Enabled` is coming from Windows and seems to related to a broken network interface.  Check you don't have any custom network interfaces and try reset to defaults.

**Comment by mikeparker** [comment]
Possibly related:
https://github.com/docker/for-win/issues/2867
https://github.com/docker/for-win/issues/2050
https://github.com/docker/for-win/issues/1873

Are you running Cisco AnyConnect?
