### ISSUE TITLE
Cannot run linux containers in Windows 2016 server VM

### ISSUE THREAD

**Issue by prakarshsurya** [docker/for-win#3727]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Able to successfully pull and run linux containers
### Actual behavior

Using default tag: latest
latest: Pulling from library/debian
e79bb959ec00: Extracting [==================================================>]  45.34MB/45.34MB
failed to register layer: failed to start service utility VM (applydiff e702f990821403121e61f52254f23eb05f806147d96935aa291d9aa88df731c7): container e702f990821403121e61f52
254f23eb05f806147d96935aa291d9aa88df731c7_svm encountered an error during CreateContainer: failure in a Windows system call: The data is invalid. (0xd) extra info: {"System
Type":"container","Name":"e702f990821403121e61f52254f23eb05f806147d96935aa291d9aa88df731c7_svm","Layers":null,"HvPartition":true,"HvRuntime":{"ImagePath":"C:\\Program Files
\\Linux Containers","LinuxInitrdFile":"initrd.img","LinuxKernelFile":"bootx64.efi"},"ContainerType":"linux","TerminateOnLastHandleClosed":true}

### Information

  - Windows Version: Windows server 2016 (1607)
  - Docker for Windows Version: 17.10.0-ee-preview-3

### Steps to reproduce the behavior

  1. Follow the guide to install docker in windows server
https://www.altaro.com/msp-dojo/linux-containers-windows-server-2019/
  2. After setting the environment and restarting the docker service try pulling debian : docker pull debian

**Comment by mikeparker** [comment]
Hi, this repo is for Docker Desktop issues - you're running Docker Enterprise on windows server. Try https://github.com/moby/moby/issues

**Comment by prakarshsurya** [comment]
@mikeparker Thanks. i will move the issue and close it.

**Comment by leovarmak** [comment]
@prakarshsurya Found any solution ?
