### ISSUE TITLE
W10 VMware VM, Docker for linux fails, Docker for Windows starts, butt Hyper-V fails

### ISSUE THREAD

**Issue by activusbuildagent** [docker/for-win#3729]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: B738E0B6-A17F-4A70-B520-A6CDD559011D/20190410102051

### Expected behavior
Not supported but should work

### Actual behavior
VMware W10 VM, Hyper-V and containers enabled, docker for Linux fails, Docker for Windows Containers starts, but errors appear when running containers

### Information

Windows Version: W10 1809 (17763.194)
Docker for Windows Version: 
Version 2.0.0.3 (31259)
Channel: stable
Build: 8858db3
### Steps to reproduce the behavior

Created a fresh W10 1809 build VM on VMware ESXi 6.5 host
Enabled Hardware Virtualization
Enabled Performance Counters
Setup CPU/MMU virtualization: Hardware CPU and MMU

TaskManager shows Virtualisation enabled

System info shows that the VM is ready for virtualization:

Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                                            Virtualization Enabled In Firmware: Yes
                                            Second Level Address Translation: Yes
                                            Data Execution Prevention Available: Yes
In Windows Features:

Enabled Containers
Enabled the whole Hyper-V modules

Hyper-V Requirements:      
                                           VM Monitor Mode Extensions: Yes
                                            Virtualization Enabled In Firmware: Yes
                                            Second Level Address Translation: Yes
                                            Data Execution Prevention Available: Yes

Successfully pulled a Windows Server Core image from Docker Hub, but the following appears when trying to run it

PS C:\Users\administrator> docker images
REPOSITORY                             TAG                 IMAGE ID            CREATED             SIZE
mcr.microsoft.com/windows/servercore   latest              ea9f7aa13d03        3 months ago        11GB
PS C:\Users\administrator>
PS C:\Users\administrator> docker run -it ea9f7aa13d03 cmd
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: CreateComputeSystem 01e237e6b59634e85ee8a4af82c74c23dc795e0d054b774f7f0ecd2d3bc7487d: The virtual machine could not be started because a required feature is not installed.
(extra info: {"SystemType":"Container","Name":"01e237e6b59634e85ee8a4af82c74c23dc795e0d054b774f7f0ecd2d3bc7487d","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\01e237e6b59634e85ee8a4af82c74c23dc795e0d054b774f7f0ecd2d3bc7487d","Layers":[{"ID":"de177faa-c87d-5ea2-817a-b7f4a625da1c","Path":"C:\\ProgramData\\Docker\\windowsfilter\\8a1a3b3b547ed2591b5adc68bdd292ea2658921704d78fce96d4e581bba3c326"},{"ID":"5d7139e8-882b-5153-82c0-a1d34cbac8d4","Path":"C:\\ProgramData\\Docker\\windowsfilter\\550e5dfe972cb42baf69e3fc752e97f65833c725600a4528de2b81bf28e36e00"}],"HostName":"01e237e6b596","HvPartition":true,"EndpointList":["EA6B7FF7-7A9F-4CAE-A042-820392F31B5D"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\8a1a3b3b547ed2591b5adc68bdd292ea2658921704d78fce96d4e581bba3c326\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}).
PS C:\Users\administrator>

**Comment by prakarshsurya** [comment]
Hello, Azure VMs doesn't support nested virtualization, especially Windows 10, try with windows server 2016+

**Comment by activusbuildagent** [comment]
Hi prakarshsurya,
The VM is hosted on a VMware ESXi on premises host, Azure it is not mentioned at all in the issue

**Comment by mikeparker** [comment]
Hi, this isn't a supported scenario, see https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-desktop-for-windows-in-nested-virtualization-scenarios

Secondly, it looks like nested Hyper-V is failing due to some underlying issue rather than anything Docker Desktop related. I would recommend debugging the Hyper-V setup first and ensuring Hyper-V is working as expected.

**Comment by Galphaa** [comment]
on esxi 6.7u3  docker edge 2.1.7.0 is working
