### ISSUE TITLE
Where is locate pidfile | docker.pid 

### ISSUE THREAD

**Issue by Sviatik** [docker/for-win#3741]
I would like to have docker inside docker for use CI-agent. But for it i need to share `docker.pid` file inside docker container and I can't find that file in this path `C:\ProgramData\docker.pid` and even i try to add this in docker daemon config:
```
{
...
  "pidfile": "C:\\docker.pid",
...
}
```
And after a restart that file didn't appear.
Could you please help me?
I guess the problem more related to this repo rather `https://github.com/moby/moby/issues` 

  - [ ] Also tried different variant in config file like `"C:\docker.pid"`, `"C:/docker.pid"`. The same behavior

### Expected behavior
Create pid file in path `C:\docker.pid`
### Actual behavior
The file is absent
### Information

  - Windows Version: 10 1809 build 17763
  - Docker for Windows Version: 2.0.0.2 31259

The docker logs is clean about creating or removing `docker.pid` file.

**Comment by mikeparker** [comment]
Hi, this looks like an issue for moby/moby as this isn't part of Docker Desktop.

**Comment by Sviatik** [comment]
Anyway i found a way to run docker inside docker.
These two topics help me:
https://forums.docker.com/t/solved-using-docker-inside-another-container/12222/3
https://stackoverflow.com/questions/36765138/bind-to-docker-socket-on-windows

I needed docker.sock file and it locate `//var/run/docker.sock` so 
`-v //var/run/docker.sock:/var/run/docker.sock` resolve my problem.
