### ISSUE TITLE
Docker unable to connect; restart not working

### ISSUE THREAD

**Issue by dsbowen** [docker/for-win#3744]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 

### Actual behavior
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

Troubleshoot suggested to restart Docker service. This does not help. Uninstalling and reinstalling Docker does not help either.

### Information

  - Windows Version: 10 Enterprise
  - Docker for Windows Version: 18.09.2

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by I828502** [comment]
I have the same problem on Windows 10 Pro and uploaded the diagnostics with ID E14238CC-7EF8-43FB-8C13-E9E87F5D77CD/20190514073702
