### ISSUE TITLE
Crash on Windows 10 reinstall not help

### ISSUE THREAD

**Issue by pironmind** [docker/for-win#3749]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by gfijrb** [comment]
Of cource I fixed it removed folders in `%APPDATA%` `/roaming/docker` `/local/docker`
