### ISSUE TITLE
Unable to switch from regular docker to Windows Containers

### ISSUE THREAD

**Issue by dutch2005** [docker/for-win#3754]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Run Windows containers

### Actual behavior
crash, no docker

### Information

  - Windows Version: Server 2019
  - Docker for Windows Version: 

Version 2.0.0.3 (31259)
Channel: stable
Build: 8858db3

### Steps to reproduce the behavior

  1. switch to windows containers
  2. ...

**Comment by mikeparker** [comment]
Hi, can you attach your diagnostics ID please?
