### ISSUE TITLE
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### ISSUE THREAD

**Issue by BorisovDmytro** [docker/for-win#3756]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mikeparker** [comment]
Hi, could you attach your diagnostics ID please?

**Comment by BorisovDmytro** [comment]
BDE4F858-34BA-4F80-9E2E-C802B7F7D0AC/20190416172327

**Comment by BorisovDmytro** [comment]
If i use docker run all ok, but if docker create and docker start -i name container i have this error in past this worked but after last update docker i have this problem.
