### ISSUE TITLE
Unable to map files into Windows container

### ISSUE THREAD

**Issue by ramondeklein** [docker/for-win#376]
### Expected behavior
Mapping a file should show the file in the container. On Linux based systems, it is possible to map both files and directories into a container. Docker for Windows only seem to support the mapping of directories. 

### Actual behavior
The container doesn't start, but the error message **invalid mount config for type "bind": source path must be a directory** is shown.

### Information
Diagnostic ID: 3FA674D6-88DD-42CE-94CA-B98E3EC978A6/2017-01-09_13-22-08
Docker: 1.13.0-rc5-beta35 (9606)
OS: Windows 10 (1607 - Anniversary edition) and Windows Server 2016 with containers (Azure)

### Steps to reproduce the behavior
When I run `docker run -v C:\users\ramon\test:C:\test nanoserver cmd /c dir \` the the following output is shown:

```
 Volume in drive C has no label.
 Volume Serial Number is 5052-B0DB

 Directory of C:\

11/20/2016  11:32 AM             1,894 License.txt
07/16/2016  12:20 PM    <DIR>          Program Files
07/16/2016  12:09 PM    <DIR>          Program Files (x86)
01/09/2017  12:13 PM    <SYMLINKD>     test [\\?\ContainerMappedDirectories\02140D0F-EA2B-45EB-B943-15F3D781D226]
01/09/2017  12:13 PM    <DIR>          Users
01/09/2017  12:13 PM    <DIR>          Windows
               1 File(s)          1,894 bytes
               5 Dir(s)  21,256,855,552 bytes free
```
All files in the `test` directory are correctly mapped. Unfortunately, when the source is not a directory, but a file then the following message is shown:

```
Error response from daemon: invalid bind mount spec "C:\\users\\ramon\\test.config:C:\\test.config": invalid volume specification: 'C:\users\ramon\test.config:C:\test.config': invalid mount config for type "bind": source path must be a directory.
```

**Comment by ramondeklein** [comment]
I would like this functionality to be able to map the application's configuration into the directory. This configuration file should be located in the same directory and should have a fixed name (default .NET app.config).

**Comment by simonferquel** [comment]
@ramondeklein thanks for the report, it is indeed a limitation of windows containers. @friism do you know if something is planned to fix that ?

**Comment by dgageot** [comment]
@ramondeklein @simonferquel I'm going to close this issue in favor of [this one](https://github.com/docker/docker/issues/30555) on docker/docker
