### ISSUE TITLE
SMB Mapping Failures When VM and Container Hotfixes are Mismatched

### ISSUE THREAD

**Issue by micahyoung** [docker/for-win#3763]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: (not clearly relevant but we can upload if needed)

### Expected behavior
* With a Windows Server 2019 Datacenter VM that has February HotFixes
* Using a Docker image with March HotFixes
* I should be able to run `net use` in a container
* And always see the default output:
   ```
   New connections will be remembered.

   There are no entries in the list.
   ```

### Actual behavior
* `net use` frequently displays an error
   ```
   System error 5 has occurred.

   Access is denied.
   ```

### Information

Q) Is it reproducible?
A) Yes, it fails frequently with the setup steps described below

Q) Is the problem new?
A) Yes, it does not occur for VMs with February HotFixes using Docker images with February HotFixes 

Q) Did the problem appear with an update?
A) Yes, it appears to be caused when HotFix KB4489899 from March is installed in the Docker image but not the VM. This also occurs when the Docker image with April HotFixes is used.

### Additional issues
The same failure occurs for Windows Server 2019 VMs with February HotFixes and Docker images with the most recent April HotFixes (`mcr.microsoft.com/windows/servercore:1809-KB4493509`).

This failure also occurs for Windows Server 1709 and 1803 using VMs with February HotFixes running Docker images with March HotFixes.

### System Details
- Windows Version: `Microsoft Windows Server 2019 Datacenter` / `10.0.17763 N/A Build 17763`
- Docker for Windows Version: `18.09.5`
- *Windows VM Azure URN:* `MicrosoftWindowsServer:WindowsServer:2019-Datacenter-with-Containers-smalldisk:2019.0.20190214`
- *Docker image Version:* `mcr.microsoft.com/windows/servercore:1809-KB4489899`

### Steps to reproduce the behavior

1. Create a Windows Server 2019 Datacenter VM (which contains the February HotFixes)
   ```
   $ az vm create -n febVM -g rootfs-regression --image MicrosoftWindowsServer:WindowsServer:2019-Datacenter-with-Containers-smalldisk:2019.0.20190214
   ```
1. From an RDP connection to the VM, open an Adminstrator Powershell terminal for the following steps

1. Install docker
   ```
   > Install-Module -Name DockerMsftProvider -Repository PSGallery -Force
   > Install-Package -Name docker -ProviderName DockerMsftProvider -Force
   ```

1. Repeatedly attempt to start a Docker container (with March HotFixes) and run `net use`. 
   ```
   > while($true){ docker run mcr.microsoft.com/windows/servercore:1809-KB4489899 powershell "Start-Sleep 1; net use"; if ($LASTEXITCODE -ne 0) {break} }
   ```
   * *`Start-sleep 1` is used to rule out unrelated container startup race conditions.*

1. We expect `net use` to display 
   ```
   New connections will be remembered.

   There are no entries in the list.
   ```

**Comment by mikeparker** [comment]
Hi, thanks for the detailed report. This looks like you're using Docker Enterprise installed on a Windows Server, not Docker Desktop? For docker enterprise you want moby/moby. However this looks like it may be a microsoft issue.

**Comment by micahyoung** [comment]
Thanks @mikeparker . Would you have any suggestions for filing an issue directly with Microsoft? 

There's a link on the `windowsservercore` Docker Hub page to a tech forum but there's no clear way to file or track the bugs there.

**Comment by micahyoung** [comment]
Moved this info to here: https://github.com/moby/moby/issues/39104

Closing for now.
