### ISSUE TITLE
Docker Crashes on Start

### ISSUE THREAD

**Issue by mayfield2333** [docker/for-win#3771]
- [x] I have tried with the latest version of my channel (Stable and Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6899107F-9EDF-4D80-B039-C6DB24B7F7C6/20190418060211

### Expected behavior
Docker service Starts

### Actual behavior
Docker Service crashes and recommends Reset to Factory Defaults.

### Information
Failed before and after the Updates:
  - Feature update to Windows 10, version 1809 amd64 2019-04
  - [April 9, 2019—KB4493509 (OS Build 17763.437)](https://support.microsoft.com/en-us/help/4493509/windows-10-update-kb4493509)
  - [Security Update for Adobe Flash Player: April 9, 2019](https://support.microsoft.com/en-us/help/4493478/security-update-for-adobe-flash-player-april-9-2019)
  - [February 12, 2019—KB4483452 Cumulative Update for .NET Framework 3.5 and 4.7.2 for Windows 10, version 1809 and Windows Server 2019](https://support.microsoft.com/en-us/help/4483452/february-12-2019-kb4483452)
  - [Update for Adobe Flash Player: October 9, 2018](https://support.microsoft.com/en-us/help/4462930/update-for-adobe-flash-player)
  - EPSON - Printer - 4/22/2009 - 10.0.17119.1

All reported as being Successfully instaled on 4/17/2019

Attempt to restart Docker Desktop appears successful, but running "docker ps" shows:

```
C:\Users\kevin.mayfield>docker ps
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```
Uploaded Diagnostics: 6899107F-9EDF-4D80-B039-C6DB24B7F7C6/20190418061958

Quiting Docker and Restarting produces:
```
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'LP1-US-51695089' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```
Just install Edge with same results:

```
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'LP1-US-51695089' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-Switch, <No file>: line 111
at <ScriptBlock>, <No file>: line 409
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0()
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1()
```

  - Windows Version: Windows 10 Enterprise - Versin 1809 - installed 4/17/2019 - OS build 17763.437
  - Docker for Windows Version: 2.0.0.3 (31259(

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mayfield2333** [comment]
Edge version Crash report:
6899107F-9EDF-4D80-B039-C6DB24B7F7C6/20190418114201

**Comment by mikeparker** [comment]
Looks like a duplicate of https://github.com/docker/for-win/issues/3764, could you check the results there?

**Comment by mayfield2333** [comment]
Following the security settings change described in #3764 worked.

Sorry I didn't see the other issue before submitting.
