### ISSUE TITLE
No matching manifest for unknown in the manifest list entries on C:\Program Files\Docker\Docker\Resources\bin\docker.exe

### ISSUE THREAD

**Issue by jayeshdongare** [docker/for-win#3775]
**Expected behavior**
It would be download and install hello-world image, but does not work.

**Actual behavior**
_C:\Program Files\Docker\Docker\Resources\bin\docker.exe: no matching manifest for unknown in the manifest list entries.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'_

**Information**
PS C:\> docker --version
_Docker version 18.09.2, build 6247962_

PS C:\> docker run hello-world
_docker : Unable to find image 'hello-world:latest' locally
At line:1 char:1
+ docker run hello-world
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unable to find ...latest' locally:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
latest: 
Pulling from library/hello-world
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: no matching manifest for unknown in the manifest list entries.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'._

**Comment by jherman** [comment]
Just want to say I get the same exact error on Windows 2016

```
PS C:\Users\Administrator> docker run hello-world:nanoserver
Unable to find image 'hello-world:nanoserver' locally
nanoserver: Pulling from library/hello-world
C:\Program Files\Docker\docker.exe: no matching manifest for unknown in the manifest list entries.
See 'C:\Program Files\Docker\docker.exe run --help'.
PS C:\Users\Administrator> docker --version
Docker version 18.09.5, build be4553c277
```

**Comment by thaJeztah** [comment]
Microsoft has deprecated and removed nanoserver for Windows Server 2016, which is likely why this no longer works 😔, and windowsservercore is probably a bit too big as a hello-world image.

You can run `docker run -it docker/surprise` (which is quite small)

**Comment by jherman** [comment]
@thaJeztah Thank you.  I can confirm that this worked for me.

**Comment by thaJeztah** [comment]
Also see https://github.com/docker-library/hello-world/issues/56 and https://github.com/docker/for-win/issues/2695#issuecomment-483992855

**Comment by jherman** [comment]
@thaJeztah Maybe this is a long shot, have you successfully been able to get Portainer to run on Windows 2016? I followed these instructions:
https://blog.airdesk.com/2017/10/windows-containers-portainer-gui.html
Got all the way to the point where UI loads and I change the initial password, but I can't seem to reach the API endpoint that is assigned to interface "172.25.96.1"

Any suggestions?

**Comment by thaJeztah** [comment]
I'm not running on Windows myself, and don't have access to a Windows machine so ☺️ I'm not very helpful there 😅

**Comment by RAHULMJP** [comment]
I am not able to run any images. Getting this error.
PS C:\Users\NagathingalA1> docker pull ubuntu:latest
latest: Pulling from library/ubuntu
no matching manifest for windows/amd64 10.0.14393 in the manifest list entries
PS C:\Users\NagathingalA1> docker version
Client: Docker Engine - Enterprise
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        f660560464
 Built:             07/25/2019 20:59:52
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.5
  Git commit:       f660560464
  Built:            07/25/2019 20:57:41
  OS/Arch:          windows/amd64
  Experimental:     false
PS C:\Users\NagathingalA1>

**Comment by Jona2jef** [comment]
enable experimental true
