### ISSUE TITLE
Unable to start kubernetes on docker desktop win 10 pro

### ISSUE THREAD

**Issue by navalprabhakar** [docker/for-win#3782]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6D6B4F18-A862-43A2-9D71-EE8548BDFFF3/20190421043139

### Expected behavior
Kubernetes starts successfully

### Actual behavior
Kubernetes is starting
### Information
- Windows 10 Pro with docker desktop.
- Added VPNKit rule to allow
- Disabled firewall
- factory reset and removed .kube and restarted
- still same error - 04:41:54.406][ApiProxy       ][Info   ] time="2019-04-21T04:41:54+05:30" msg="Cannot list nodes: Get https://localhost:6445/api/v1/nodes: EOF"

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by SergeySypalo** [comment]
Check out solution from here: https://github.com/docker/for-win/issues/3799
