### ISSUE TITLE
can't pull windows image on a AMD/64 laptop

### ISSUE THREAD

**Issue by wgwi65** [docker/for-win#3787]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:10CCDCCD-2461-4F81-971D-5BAD1DB3AE0E/20190421234911

### Expected behavior
Download a image from mcr.microsoft.com/windows/nanoserver:1809
### Actual behavior
Get error message: 
1809: Pulling from windows/nanoserver
no matching manifest for unknown in the manifest list entries

### Information
[Docker Error log.txt](https://github.com/docker/for-win/files/3101384/Docker.Error.log.txt)

  - Windows Version:
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.16299 Build 16299
Processor	AMD Ryzen 7 PRO 2700U w/ Radeon Vega Mobile Gfx, 2200 Mhz, 4 Core(s), 8 Logical Processor(s)

  - Docker for Windows Version:
Version 2.0.0.3 (31259)
Channel: stable
Build: 8858db3

- Docker Version:
PS C:\Users\wgwi> docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:28:48 2019
  OS/Arch:          windows/amd64
  Experimental:     true

### Steps to reproduce the behavior

  1. start windows docker desktop
  2. start powershell
  3. issue command: docker pull mcr.microsoft.com/windows/nanoserver:1809
  4. Received error of: "no matching manifest for unknown in the manifest list entries"

**Comment by StefanScherer** [comment]
@wgwi65 please have a look at the Windows Container compatibility table https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility
You cannot pull Windows images that are newer than the operating system. Windows 10 1709 only supports the mcr.microsoft.com/windows/servercore:ltsc2016 and mcr.microsoft.com/windows/nanoserver:1709 image. But please notice that the 1709 images had the last update on April 9th and are now deprecated.
You should consider updating your Windows 10 operating system.

**Comment by Mierpo** [comment]
> 
> 
> @wgwi65 please have a look at the Windows Container compatibility table https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility
> You cannot pull Windows images that are newer than the operating system. Windows 10 1709 only supports the mcr.microsoft.com/windows/servercore:ltsc2016 and mcr.microsoft.com/windows/nanoserver:1709 image. But please notice that the 1709 images had the last update on April 9th and are now deprecated.
> You should consider updating your Windows 10 operating system.

@StefanScherer I'm a bit confused why Hyper-V isolation doesn't allow us to pull, build and run images of different and newer versions. The table in the link you provided mentions this:

Container OS version | Host OS version | Compatibility
-- | -- | --
Windows Server 2019, version 1903Builds 18362.* | Windows 10, version 1903Builds 18362.* | Only supports hyperv isolation
Windows Server 2019, version 1903Builds 18362.* | Windows 10, version 1803Builds 17134.* | Not supported

This essentially means I have no way of testing my Dockerfiles and builds on my local desktop (current version is 17134.*). _**What is the technical reason a virtual-machine level isolation is not sufficient**_ in these cases? I understand why process-level isolation would not be enough. But do the hyper-v vm-containers also share the kernel of the host?

Thank you for your time!
