### ISSUE TITLE
Docker for Windows fails to resolve DNS when VPN active

### ISSUE THREAD

**Issue by planetf1** [docker/for-win#379]
### Expected behavior
When VPN is activated on the (windows) host docker networking should continue working normally in the containers (using default networking setup)

### Actual behavior
When VPN is activated DNS resolution is not possible using the auto-set DNS server in the docker images

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
6E0573AA-4A4D-4F32-8E8C-E493E4A248D8/2017-01-10_17-46-45

  - a reproducible case if this is a bug, Dockerfiles FTW

* install docker (beta)
* Launch ubuntu shell with "docker run -i -t ubuntu /bin/sh"
* observe networking works just fine (ie apt-get update -- or install ping with apt-get)
* Launch Cisco VPN
* observe networking fails. DNS names will not resolve. /etc/resolv.conf contains 192.168.65.1 as the server. This cannot be contacted via nslookup/ping
* Stop Cisco VPN
* note that networking returns as normal
* 100% reproducible

Note I have
 1 x ethernet
 1 x wifi
 - ethernet, wifi are both setup as bridged connections in hyper-v for a regular vm
 - thereis also a hostonly hyper-v network

  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)
Windows 10 x64 version 1607
Version 1.13.0-rc5-beta35 (9606)
Channel: Beta
d603c07
Thinkpad W530 (SSD+HDD+i7 QC, 16GB ram)

### Steps to reproduce the behavior

  1. ...
  2. ...
as above

Original text report at http://stackoverflow.com/questions/41558915/docker-for-windows-dns-when-vpn-active

**Comment by planetf1** [comment]
As an aside, I did look at posting on the docker forum initially, but for some reason my id is suspended?? (also planetf1). I tweeted @dockersupport but no response?

**Comment by rneugeba** [comment]
@planetf1 thanks for your report. Any change you could upload a diagnostics and let us know the ID? We try to figure out the DNS config reconfigure the network used by the Linux VM and the diagnostics should contain some useful information to figure out what went wrong.
Thanks

**Comment by planetf1** [comment]
I did :-) ID was 6E0573AA-4A4D-4F32-8E8C-E493E4A248D8/2017-01-10_17-46-45

I'll do another one now in case it didn't work - 6E0573AA-4A4D-4F32-8E8C-E493E4A248D8/2017-01-10_18-09-02

**Comment by planetf1** [comment]
I also uploaded a diagnostic with the VPN stop (this is the working configuration) in case it helps show the difference

A diagnostic was uploaded with id: 6E0573AA-4A4D-4F32-8E8C-E493E4A248D8/2017-01-10_18-10-28

**Comment by rneugeba** [comment]
@planetf1 ah, sorry, missed the diagnostics ID in the original post.

I had a quick look and it seems like you may have manually configured a DNS server in the UI? Could you removing it?

Otherwise, I do see some DNS queries going through and get responses but they seem to get droped.

@djs55 could you take a look and see if this is similar to the issue we discussed the other day?

**Comment by planetf1** [comment]
@rneugeba I don't have a DNS server coded in the docker UI. It's set to "automatic" (though 8.8.8.8 is showing as greyed out in the manual textbox)

I've checked the hosts's adapters too... and again all are set to automatic.
My HOME dhcp tends to return 8.8.8.8, though I'm at a family member's tonight where their ISP DNS servers are in use. In the office it will be others again. Of course connecting via vpn introduces a new dns server into the mix. In all cases I have no name res in the docker environment.

I DO have the SEP 12 (at latest fix levels) firewall active though disabling not (not uninstalling) doesn't make any difference....

**Comment by rneugeba** [comment]
@planetf1 could you try [Beta 39](https://download.docker.com/win/beta/InstallDocker.msi), which was just released. It contains some fixes to the integrated DNS which may solve your issue. If you still have issues with DNS, it would be great if you could provide a new diagnostics ID for us to take a look at.
Thanks

**Comment by planetf1** [comment]
I just tried the latest beta and checking now all is working fine. DNS is resolved when on vpn (including for servers within the private intranet) and when not.

HOWEVER in the interim I switched from the production win 10 build to the insider/fast build (currently on 15014)  due to other networking issues, so unfortunately I can't be sure which change actually fixed it.

**Comment by rneugeba** [comment]
Thanks for getting back so quick and glad it's working now. I'm closing the issue.

It's almost certainly the VPNKit update. We fixed the behaviour when multiple DNS servers were in use and one returned an error before the real answer came back. From the diagnostics you sent this looked like what was happening.
