### ISSUE TITLE
Kubernetes is starting | Get stuck forever | windows 10

### ISSUE THREAD

**Issue by paraspatidar** [docker/for-win#3792]
Tried all things as mentioned in other issues like :
1. enabling vpnkit.exe.
2. disabled firewall completely.
3. choose google dns
4. running as admin
5. multiple times reinstalation / reboot
6. KUBECONFIG variable
 

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: EB224B96-FDA1-4C29-9C5D-4C41A4F91E40/20190422181648

### Information

  - Windows Version: win 10
  - Docker for Windows Version:2.0.0.3 (stable)

______________________________________________________________________________________________

18:12:38.234][VpnKit         ][Error  ] vpnkit.exe: While watching /etc/resolv.conf: ENOENT
[18:17:42.563][VpnKit         ][Error  ] vpnkit.exe: Upstream DNS server 202.88.149.25:53 has dropped 6 packets in a row: assuming it's offline
[18:17:44.515][VpnKit         ][Error  ] vpnkit.exe: Socket.UDPv4.read: udp -> 125.99.170.3:53 caught Lwt.Resolution_loop.Canceled returning Eof
....
...
[18:22:31.406][ApiProxy       ][Info   ] time="2019-04-22T18:22:31+05:30" msg="Cannot list nodes: Get https://localhost:6445/api/v1/nodes: EOF"

**Comment by shoff** [comment]
Same, happens to me on multiple different machines not just Windows 10 but also on Windows Server 2016.

**Comment by jason-daniels** [comment]
I was seeing what appeared to be the same behavior as you two.
While I've not determined 100% what made it work for me, here are the steps I (more or less) took
* Add both inbound and outbound firewall exceptions to windows firewall for vpnkit
* Uninstalled Docker
* Deleted Docker* folders from %appdata%
* Deleted .kube and .docker folders from my home/user directory.
* Disabled Hyper-V (reboot required)
* Enabled Hyper-V and rebooted.
* Reinstalled Docker and rebooted
* Launched the Docker Settings dialog and selected "Enable Kubernetes" then clicked apply
* Clicked run in background.

After a several minute wait, where I still saw "Kubernetes is starting" in orange, then left my machine alone until morning. I did disconnect if from the corporate network, tho I suspect that is unimportant.

By morning the "Kubernetes is running" icon was green in the settings dialog.
