### ISSUE TITLE
Cannot pull new Windows base image if Hyper-V container is running

### ISSUE THREAD

**Issue by nokjuh** [docker/for-win#3793]
### Expected behavior

Pulling newest Windows Server Core image succeeds without errors, no matter what containers are running on the host.

### Actual behavior

If there is a Windows Hyper-V isolation Windows Server Core container running, trying to pull
a new base image fails to "The process cannot access the file because it is being used by another process."

### Information
If the same container is running in process isolation mode, then the same pull command succeeds without errors.

I ran into this error in Azure Service Fabric environment, but I was able to reproduce it on a clean Azure Virtual Machine. I expect this to be a common issue, not just between specific Windows image versions, the versions below are some samples for a simple reproduction.

Our use case requires that we use Hyper-V containers in Azure Service Fabric, and that we have the containers running constantly. It's not acceptable that we would stop all the containers for e.g. 30 minutes every month to be able to pull the new image with latest Windows updates. For security reasons we can't use process isolation. So currently this is blocking our production use.

The issue is reproducible every time at least with the below versions, I believe it occurred earlier with other image versions but I wasn't able to narrow it properly down until now.

The file in the error message varies if using different versions, sometimes it's e.g. msfs.sys or cryptsp.dll. However, it always seems to be the same file with the same exact versions.

I looked at the file access of the file mentioned in the error message with Process Monitor, but wasn't able to see anything other than successful entries done by dockerd.exe near the error.

Windows version: Windows Server 2016 (14393.2906)
Docker version:
Client: Docker Engine - Enterprise
 Version:           18.09.4
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        c3516c43ef
 Built:             03/27/2019 18:22:15
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          18.09.4
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.8
  Git commit:       c3516c43ef
  Built:            03/27/2019 18:20:29
  OS/Arch:          windows/amd64
  Experimental:     false

Tested with Azure Virtual Machine (Windows Server 2016 with containers). It does not have com.docker.diagnose.exe installed, so I don't know how I could upload diagnostics.

Sorry if this is posted to the wrong location, I couldn't figure out all the different support choices related to Docker.

### Steps to reproduce the behavior

1. Pull a Windows Server Core image or any image based on it, the following is a sample version
docker pull mcr.microsoft.com/windows/servercore:10.0.14393.2848
2. Run the image in Hyper-V mode, the actual command doesn't seem to matter as long as the container is running
docker run --isolation=hyperv mcr.microsoft.com/windows/servercore:10.0.14393.2848 ping -t www.google.com
3. Try to pull a different version of the Windows Server Core image
docker pull mcr.microsoft.com/windows/servercore:10.0.14393.2906

10.0.14393.2906: Pulling from windows/servercore
3889bb8d808b: Already exists
ba2bcc6237ee: Extracting [==================================================>]  1.572GB/1.572GB
failed to register layer: re-exec error: exit status 1: output: remove \\?\C:\ProgramData\docker\windowsfilter\a023be6a753a7262c464118060214b6b8efb10c62132517c739bfa1add6c686c\UtilityVM\Files\Windows\System32\negoexts.dll: The process cannot access the file because it is being used by another process.

**Comment by nokjuh** [comment]
Each failed attempt to download the image also takes several gigabytes of space, leaving a directory such as C:\ProgramData\docker\windowsfilter\54b37b5ceeeac73e58b2798ca67e30b40c329f63b80c97862cac15277e0be14e-removing on the disk. The directory is not removed with "docker image prune" or reboot, so I don't see any supported way of removing the directories. They also pile up, so if you have made e.g. 10 failed attempts to download the image, the local C drive is likely totally full without any reasonable way to clean it up.

**Comment by guiserrato** [comment]
I am also running into this issue.

I have done some testing on Windows Server 2019 and it does not seem to have the problem.

Still, I hope this gets fixed for Server 2016.

**Comment by nokjuh** [comment]
I've been trying to get a response from Microsoft through other routes. Now I got a similar answer, that they've been able to reproduce the issue with Windows Server 2016 but not with Windows Server 2019. They did not promise any fix to Windows Server 2016, although I'll see if I can get any further response.

**Comment by nokjuh** [comment]
Microsoft responded in another ticket that they do not have plans to fix the bug in Windows Server 2016, so it seems that the only way to properly use Hyper-V containers is to update to Windows Server 2019.

**Comment by nokjuh** [comment]
This issue is extremely frustrating, since it's easy to run into it, basically it happens always with normal container image update process when using Hyper-V containers. It also causes the Docker computer disks to fill up, since it leaves several gigabytes of data that seems to be impossible to clean without resetting the whole computer installation.

As a workaround we have now defined the image version explicitly to use a certain date's version, but we still need to figure out a reliable way to actually get Windows updates to container images.

Windows Server 2019 update is the long-term solution, but it has other bugs preventing us from taking it into use yet. It is also not supported in all environments yet (https://support.microsoft.com/en-us/help/4035670/support-policy-for-containers-and-related-services-on-azure).
