### ISSUE TITLE
Fails to start - Virtualization

### ISSUE THREAD

**Issue by l-t-s** [docker/for-win#3796]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 892AA8A2-C101-463A-9992-DF81D411AB7D/20190422222911

### Expected behavior
- Have Docker Engine start.

### Actual behavior
- Did not.

### Information
I have no clue if this problem is reproducible, as it might be because of the special build of my OS and/or some software. However in my last install of Windows, Docker did run as expected, while I had all the similar software as I do now.  
I have virtualization enabled in my BIOS and it is detected by Windows, and Hyper-V is enabled from Windows features. Regardless of those, when launching Docker for Windows, it gives me the error of not having virtualization enabled on both Stable and Edge builds.  
Also tried re-enabling Hyper-V completely and restarting to see if it would have an effect, but after enabling it, Docker still gave the same error.  
From ``systeminfo``:
```
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes
```

  - Windows Version: Windows 10 Enterprise LTSC, version 1809, build 17763.437
  - Docker for Windows Version: 18.09.3, build 774a1f4

### Steps to reproduce the behavior

  1. Start Docker for Windows after fresh install.

**Comment by MythreyaK** [comment]
Could you show the output of `bcdedit`?

**Comment by l-t-s** [comment]
> Could you show the output of `bcdedit`?

```
Windows Boot Manager
--------------------
identifier              {bootmgr}
device                  partition=\Device\HarddiskVolume7
path                    \EFI\MICROSOFT\BOOT\BOOTMGFW.EFI
description             Windows Boot Manager
locale                  en-us
inherit                 {globalsettings}
default                 {current}
resumeobject            {c36b1955-37a2-11e9-a6cc-9c5c8e877747}
displayorder            {current}
toolsdisplayorder       {memdiag}
timeout                 30

Windows Boot Loader
-------------------
identifier              {current}
device                  partition=C:
path                    \Windows\system32\winload.efi
description             Windows 10
locale                  en-us
inherit                 {bootloadersettings}
isolatedcontext         Yes
allowedinmemorysettings 0x15000075
osdevice                partition=C:
systemroot              \Windows
resumeobject            {c36b1955-37a2-11e9-a6cc-9c5c8e877747}
nx                      OptIn
bootmenupolicy          Standard
```
I run dualboot with Ubuntu 18, so I boot to Windows via GRUB2. Could that affect it in some way?

**Comment by MythreyaK** [comment]
Could you run `bcdedit /Set {current} hypervisorlaunchtype auto`, reboot and try running docker again? Also, after reboot, it should look something like so
<pre>
...
systemroot              \Windows
resumeobject            {9ac48086-17b4-11e9-9223-c72947e27025}
nx                      OptOut
bootmenupolicy          Standard
<b>hypervisorlaunchtype    Auto</b>
...
</pre>

**Comment by l-t-s** [comment]
> Could you run `bcdedit /Set {current} hypervisorlaunchtype auto`, reboot and try running docker again?

That did the trick, as far as I know.  
Docker 2.0.4.1 (34207) running as it should, have yet to test all features but it seems to function.  
Cheers, @MythreyaK ! 🍻
