### ISSUE TITLE
Cannot share drive between Windows 10 and Docker

### ISSUE THREAD

**Issue by GergelyMindler** [docker/for-win#380]
### Expected behavior
Sharing is success.

### Actual behavior
I tried to share my D:\ drive (Docker is installed to C:\):
![kep](https://cloud.githubusercontent.com/assets/24973489/21843285/ad890d3e-d7ea-11e6-98e1-74e7de899ee3.png)

After I clicked to "Apply", I got this message (with and without Firewall):
![kep](https://cloud.githubusercontent.com/assets/24973489/21843294/bc1282fe-d7ea-11e6-9191-e757b43e035d.png)

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu:
     795B4680-B427-458E-8379-D2E148D59158/2017-01-11_10-43-28
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

**Comment by itcrab** [comment]
Hi. maybe my experience help you.

I have this problem on Windows 10 and easy fix it. I my case problem in my antivirus software.
I use Kaspersky Internet Security and it activated Network Screen Protection for all Networks and Docker Network (Hyper-V Virtual Ethernet Adapter). By default all vEthernet (DockerNAT) sets by Public Network (protected).

I solve this problem just change Docker Network from Public Network to Trusted Network. It take open needed port for Docker Windows Setttings program. Maybe may open only needed ports but I no have time tests it.

**Comment by itcrab** [comment]
I wrote issue to Kaspersky for automated setts all Docker Network is Trust Network.

**Comment by itcrab** [comment]
@friism ok, when I touch new information - I will send you message

**Comment by GergelyMindler** [comment]
@itcrab @friism Hi Guys, sorry for my late answer. This sounds good if the solution is so easy. Could you explain me how could I change the Docker Network from Public to Trusted? I am not so familiar with Docker and I do not see this option here : 
![image](https://cloud.githubusercontent.com/assets/24973489/21957835/2a40d07a-daa0-11e6-8852-da511e243dee.png)

**Comment by GergelyMindler** [comment]
@itcrab Otherwise I am not sure that my problem comes from my antivirus program. What I know that in my case, the switching off of firewall does not help me.

**Comment by itcrab** [comment]
@GergelyMindler first of all - I say about my solved problem on Docker:
![image](https://cloud.githubusercontent.com/assets/494995/21958202/7dded2ac-daca-11e6-9534-df934e30519d.png)

**Comment by itcrab** [comment]
@GergelyMindler 
> Could you explain me how could I change the Docker Network from Public to Trusted?
I do this in my antivirus (firewall include in it).
![image](https://cloud.githubusercontent.com/assets/494995/21958229/4bf12d5c-dacb-11e6-9215-3b3848c6d64a.png)

**Comment by GergelyMindler** [comment]
@itcrab I use the same version of Docker

**Comment by GergelyMindler** [comment]
@itcrab Hm, I use Comodo, not Kaspersky... but the problem is  the same... I check it where could I do what you did in Kaspersky

**Comment by itcrab** [comment]
@GergelyMindler you may do little test:
- disable all components of Comodo (full exit);
- reset to factory defaults Docker (!!! all containers will be lost);
- test sharing disk D.
Can test?

**Comment by itcrab** [comment]
@GergelyMindler maybe reset to factory defaults don't needed - you may first test without this step.

**Comment by itcrab** [comment]
@GergelyMindler I found this page:
https://docs.docker.com/docker-for-windows/troubleshoot/#/docker-fails-to-start-when-firewall-or-anti-virus-software-is-installed

> See the Comodo forums topics Comodo Firewall conflict with Hyper-V and Windows 10 Anniversary build doesn’t allow Comodo drivers to be installed. A Docker for Windows user-created issue describes the problem specifically as it relates to Docker: Docker fails to start on Windows 10.

**Comment by GergelyMindler** [comment]
@itcrab thank you

**Comment by itcrab** [comment]
@GergelyMindler disable Comodo (full exit) works or no?

**Comment by GergelyMindler** [comment]
@itcrab I cannot disable Comodo but I found the same menuitem as you:
![image](https://cloud.githubusercontent.com/assets/24973489/22035213/6e63f178-dcef-11e6-9cab-877d85e372b1.png)

The used language is Hungarian, "Tűzfal" = Firewall, "Hálózati zónák" = Network zones. The problem is that here I did not found Docker network - but the Docker is running.

**Comment by GergelyMindler** [comment]
@itcrab So, currently this problem is open yet.

**Comment by itcrab** [comment]
@GergelyMindler you may send message to Comodo for help give right settings for Docker

**Comment by thecatwhisperer** [comment]
Having the same issues as the OP.  Tried the following:

- Disabling firewall 
- disconnecting from VPN connections

**E888DD20-2CD0-47F9-BED0-8036680B4F1D/2017-01-23_10-06-54**

**Comment by dgageot** [comment]
Hi @GergelyMindler @thecatwhisperer @itcrab, we've tried to fix this issue in a test release that can be downloaded here: https://download-stage.docker.com/win/samba-experiment/10154/InstallDocker.msi

*Warning: This version will not auto-update to a newer version. It's only meant for testing. You must uninstall the version you have currently installed before you install this test version.*

**Comment by GergelyMindler** [comment]
@dgageot Hi David, at first, thank you. I downloaded the beta installer, uninstalled the installed version of Docker and started the beta installer. After then, I selected the repair method and now restart my PC. Moment, continuing :)

**Comment by GergelyMindler** [comment]
@dgageot I am here again, after restart. After Docker started, I tryed to share my D:\ drive and the Docker had problem with Comodo firewall agian. Till now, this is tha same issue.

In Comodo settings, I do not see the DockerNAT, so I cannot set the network for trusted network as @itcrab did it. This is also not changed.

**Comment by thecatwhisperer** [comment]
It seems my issue is that we have a Group Policy exception in the firewall that prevents all non-domain networks from accessing 445 (SMB).  Is there a way to force docker to use a bridged network?

**Comment by grahamehorner** [comment]
I have installed Microsoft Message Analyzer if this would help any I can record network packets at a low level when enabling sharing

**Comment by itcrab** [comment]
@dgageot sorry for delay, I installed your version Docker:
Version 17.03.0-ce-rc1 (10154)
Channel: samba-experiment
c9d1081

When I share my drive in Docker Settings I got this:
![image](https://cloud.githubusercontent.com/assets/494995/24333706/4b0a9d1e-1276-11e7-9e6c-fe015d5acd58.png)

Then I go to Kaspersky Settings and set Docker Network as Trusted Network.
After this - all works - I shared my drive in Docker Settings.

Then I reset to factory defaults for tests sharing drive again.
In progress sets factory defaults I got exception and send to you crash report: 47A897B0-26C4-44D4-B867-4EC2DDFDD535/2017-03-26_23-17-37

Then I start Docker (it was down after crashed) and reset Docker again - got crash report: 47A897B0-26C4-44D4-B867-4EC2DDFDD535/2017-03-26_23-20-54

I want retest all after reset to factory defaults but I don't may this. Thats all.

**Comment by vzaidman** [comment]
kaspersky => more tools => settings (left bottom icon) => protection => firewall => networks => docker  network => change network type to trusted network => save

**Comment by kirlat** [comment]
@GergelyMindler, I just configured Comodo for working with Docker successfully and if your problem is not resolved as of now, I can share my settings.

**Comment by itcrab** [comment]
@vzaidman yes - it solved problem me too (above I wrote about this) but if you reset Docker to factory defaults you need do this solution again.

Current question for @friism and @dgageot - why Docker is don't trusted in Kaspersky/Comodo/etc by default? I think it's will be very good news for all who using Docker everyday.

**Comment by friism** [comment]
@itcrab no, that's a question for Kaspersky/Comodo/etc - if you currently pay for their products I recommend that you open an issue with them.

**Comment by itcrab** [comment]
@friism I already wrote to Kaspersky and got answer they not be make Docker trusted by default. I understand them - I only one user of many thousands users... So small dot in full users picture.

But I think we may changing this together - if you send official message to Kaspersky (and all popular antiviruses) from Docker, Inc. You is not one user and your vote is biggest.

**Comment by centigrade-thomas-becker** [comment]
I have read the answers in this thread, and setting Kaspersky to treat Hyper-V as a trusted network mostly solved the problem for me. 

However! Every time I reboot my computer Kaspersky treats the Hyper-V adapter as a *new* and separate network and I manually have to set it to "trusted network" again. In the Kaspersky window "Available networks" I now have a list of about 20+ Hyper-V adapters and every day one or two new adapters are added to the list.

Does anyone perchance know how to prevent this behaviour?
