### ISSUE TITLE
accidentally delete the virtual machine manager hyper-V

### ISSUE THREAD

**Issue by CcaceresBrn** [docker/for-win#3803]
![Captura de pantalla (96)](https://user-images.githubusercontent.com/45244345/56617478-fa269d80-65ed-11e9-96a5-58b899977061.png)

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by MythreyaK** [comment]
Just restart docker if you deleted mobyVM. Also if the server isn't showing, make sure you started with HyperV on boot (you can check the output of `bcdedit` on `cmd`)
