### ISSUE TITLE
DockerForWin should create/remove routes for networks the same way linux does

### ISSUE THREAD

**Issue by TewWe** [docker/for-win#381]
### Expected behavior

Host machine should be able to communicate with the containers through IP address, without creating static routes manually.

### Actual behavior

Network traffic is not routed from host machine to the containers (through virtual switch), only if static routes are specified manually.

### Information

  - Diagnostic ID: 1D3D519B-776A-4D94-B4FB-533628263606/2017-01-11_11-47-25
  - Windows 10 Pro 1607 Build 14393.693

On linux, static routes are added to the routing table automatically by docker, on creation of the network.

### Steps to reproduce the behavior

  1. docker run --name some-nginx  -d nginx
  2. docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' some-nginx
`172.17.0.2`
  3. telnet 172.17.0.2 80
`Connecting To 172.17.0.2...Could not open connection to the host, on port 80: Connect failed`
  4. route add 172.17.0.0 mask 255.255.0.0 10.0.75.2 -p
` OK!`
  5. telnet 172.17.0.2 80
```
 HTTP/1.1 400 Bad Request
Server: nginx/1.11.8
Date: Wed, 11 Jan 2017 11:14:52 GMT
Content-Type: text/html
Content-Length: 173
Connection: close
<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx/1.11.8</center>
</body>
</html>
```

So I would expect for the docker daemon to create these routes when it creates docker networks.

It is discussed earlier in the forums: https://forums.docker.com/t/access-container-via-container-private-ip-from-windows-host-machine/22230

**Comment by rneugeba** [comment]
@TewWe thanks for the report. Adding the routes kinda works on the stable branch with 1.12 but won't work on 1.13 (see [here](https://github.com/docker/for-win/issues/221#issuecomment-269659422) for example). In Linux you can only access the other container by IP on the local host (but not from other hosts) so it's best to explicitly exporting ports (or create named services) which also works on Docker for Windows.

I'm closing this issue as won't fix with the same explanations given on https://github.com/docker/for-win/issues/221 But if you have a specific use case, please updating the issue.
Thanks
