### ISSUE TITLE
Cannot connect to Windows host Postgres service from Windows container

### ISSUE THREAD

**Issue by jordanjean** [docker/for-win#3817]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

I expect to connect to the Postgres Windows service through 5432 host port from my **Windows** container using the default NAT docker network.

### Actual behavior

From the Windows container I can ping the nat network gateway (host) but I can't connect to Postgres service running on localhost 5432 port through TCP.

### Information

- From my Windows container, the powershell command `Test-netConnection <gateway_address> -Port <Postgres_port>` returns :

```
PS C:\Users\Administrator> Test-netConnection 172.17.48.1 -Port 5432
WARNING: TCP connect to (172.17.48.1 : 5432) failed


ComputerName           : 172.17.48.1
RemoteAddress          : 172.17.48.1
RemotePort             : 5432
InterfaceAlias         : Ethernet
SourceAddress          : 172.17.50.182
PingSucceeded          : True
PingReplyDetails (RTT) : 0 ms
TcpTestSucceeded       : False
```

 - I get the following errors from my Spring application running on my container: 
`org.postgresql.util.PSQLException: The connection attempt failed.`,
```
Trying to establish a protocol version 3 connection to 172.17.48.1:5432
org.postgresql.Driver: Connection error:
org.postgresql.util.PSQLException: The connection attempt failed.
```
  - It works with Linux containers
  - Windows Version: Windows 10 Enterprise LTSC 1809
  - Docker for Windows Version: Docker CE Version 2.0.0.3 (31259) Channel: stable Build: 8858db3

### Steps to reproduce the behavior

  1. Run `mcr.microsoft.com/windows/servercore` (ltsc2019) image.
  2. Run `Test-netConnection <gateway_address> -Port <Active TCP port>` in PowerShell
  3. See TCP test failure

**Comment by jaafaree** [comment]
Any updates for this issue? I just met the same exception.
