### ISSUE TITLE
Docker for Windows frozen in starting state.

### ISSUE THREAD

**Issue by peterhorvath** [docker/for-win#382]
**### Expected behavior**
Docker for Windows to start
**### Actual behavior**
Docker for Windows stays is systry and keeps saying starting.....
**### Information**

  **- Diagnostic ID from "Diagnose & Feedback" in the menu.**
C90A5AB9-CD1B-4641-A455-056915E93DE4/2017-01-12_15-13-19
  **- a reproducible case if this is a bug, Dockerfiles FTW**
Latest stabel and latest beta 
  **- page URL if this is a docs issue or the name of a man page**
  **- host distribution and version (Windows version, build number, etc)**
Windows 10 Enterprise 64 bit 1607 14393.577
HP Z420 with xeon processor Virtualization enabled in BIOS and windows feature

**### Steps to reproduce the behavior**

  1. start docker
  2. from task manager stop after a while since it is not starting
  3. restart same behaviour

**Comment by rneugeba** [comment]
Thanks for the report. In the diagnostics I see remnants of VirtualBox. Could you completely un-install VBox and try again? Hyper-V (used by Docker for Windows) does not work with other virtualisation software installed.
Thanks

**Comment by peterhorvath** [comment]
Thanks that was it after i completely removed virtual box it is working.
Does that mean that i can't install and use virtual box for other purposes if i want to have docker for widows as well?

**Comment by rneugeba** [comment]
Thanks for getting back and glad it's working for you. I'm closing this issue.

To answer your question, you definitely can't use them at the same time, and switching between them can also cause problem...Judging by the number of issues we see, I'm not sure there is a reliable way to switch between them.
