### ISSUE TITLE
Docker fails to create swarm ingress network switch in Hyper-v with "Failed creating ingress network: hnsCall failed in Win32: Element not found."

### ISSUE THREAD

**Issue by AbsurdusAdeptus** [docker/for-win#3821]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 9B5A15E1-00CB-4769-8CA2-8EC6C22EBE19/20190427203651

### Expected behavior
`docker swarm init` on windows 10 (windows containers not moby or LCOW) should result in a switch being created in hyper-v's virtual switch manager. It should also make the creation and use of overlay networks possible.

### Actual behavior
`docker swarm init` silently continues past and internal error saying it completed. the logs show the error "Failed creating ingress network: hnsCall failed in Win32: Element not found." No new VMSwitch is created in hyper-v. After that swarm deploys will continually fail the task of attaching new containers to their new overlay networks.

### Information
Hey all. I've been fighting with this problem on multiple PCs for days. I'm trying to make use of Docker Swarm and I just cant get it up and running. The `docker swarm init` seems to run fine (reporting with the info for new nodes to use to join) and `docker network ls` shows a new ingress created scoped to swarm. But when I try to make use of any overlay networks through a `docker swarm deploy ...` or by manually creating one and attaching a container it fails. With `docker swarm deploy ...` the deploy tasks for all of the containers fail and retry forever just saying there was an HNS error, and the manual route fails after a small timeout with "docker: Error response from daemon: attaching to network failed, make sure your network options are correct and check manager logs: context deadline exceeded."

Looking into the docker logs I see this error while initializing the swarm "Failed creating ingress network: hnsCall failed in Win32: Element not found." I also noticed that right after the swarm init is run, in hyper-v a new switch is created for a few seconds (one with a lot of letters and numbers for a name) but is shortly after deleted. That made me go query the windows logs to see what was all being done and got some interesting events I've included in the "winLogs.txt" file. It shows the switch being created but then deleted. I've gotten this to work inside an Azure Windows 10 machine with the same version. I can't get it to work on my personal Desktop or laptop. Any ideas? 

  - Windows Version:1809 (OS Build 17763.437)
  - Docker for Windows Version: 18.09.2

### Steps to reproduce the behavior
1. Run the command `docker swarm init`
1. Run the command `docker network create -d overlay --attachable testoverlay` 
1. Run the command `docker run -it --rm --network testoverlay mcr.microsoft.com/windows/nanoserver:1809`

**Comment by AbsurdusAdeptus** [comment]
[winLogs.txt](https://github.com/docker/for-win/files/3124574/winLogs.txt)
[appdata-docker_log.txt](https://github.com/docker/for-win/files/3124575/appdata-docker_log.txt)

**Comment by AbsurdusAdeptus** [comment]
This is resolved after updating to Windows 10 1903.

**Comment by ncresswell** [comment]
i am seeing this same issue in Windows 10 1909... are you sure it was resolved?

**Comment by AbsurdusAdeptus** [comment]
It resolved on that computer at the time yes. I have for the most part abandoned docker swarm on windows though because of issues like this around the networking. I just tried it for fun on a newer laptop of mine running Windows 10 1909 and with the latest Docker for Windows and it failed same as it did here. Feel free to file a new ticket to get help because this does seem to still break with a near clean install of Windows 10 (this laptop is only a week old). But I'm done with swarm.
