### ISSUE TITLE
Docker cannot start anymore - error related to Hyper-V...

### ISSUE THREAD

**Issue by KarGrat** [docker/for-win#3827]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 9D8B9A91-084F-4FD2-82C8-2945B76EEDDE/20190429091340

### Expected behavior
Normal run of Docker

### Actual behavior
Sorry my laptop is in french. If required, i will translate...

Unable to create: L’exécution de la commande s’est arrêtée, car la variable de préférence « ErrorActionPreference » ou le paramètre courant a la valeur Stop : Hyper-V a rencontré une erreur lors d’une tentative d’accès à un objet sur l’ordinateur « LAPTOP-PEAES5HH », car l’objet est introuvable. L’objet a peut-être été supprimé. Vérifiez que le service de gestion d’ordinateurs virtuels est en cours d’exécution sur l’ordinateur.
à New-Switch, <Aucun fichier> : ligne 121
à <ScriptBlock>, <Aucun fichier> : ligne 411
   à Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) dans C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:ligne 36
   à Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) dans C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:ligne 92
   à Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() dans C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:ligne 74
   à Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() dans C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:ligne 59

So Docker is not running at all.
I already tried to uninstall then reinstall Docker (included Hyper-V through Windows) : not better, still an issue.
Please help me as I cannot run any local docker.. (and this is very important for my current project)

### Information
  - Is it reproducible? Yes systematically at open
  - Is the problem new? Yes (since 2 or 3 weeks ago)
  - Did the problem appear with an update? I think so but not sure...

  - Windows Version: 
![image](https://user-images.githubusercontent.com/25660464/56915833-cd73f980-6ab7-11e9-934c-9e9169d68dc0.png)

  - Docker for Windows Version:
![image](https://user-images.githubusercontent.com/25660464/56915895-f1373f80-6ab7-11e9-9c63-4515fa23d13c.png)

**Comment by samgegr8** [comment]
I am facing the same issue.  But I am installing Docker for the first time in my machine

https://github.com/docker/for-win/issues/3842

**Comment by ollisommer** [comment]
I got the same issue, win 10 Enterprise, 1908, docker 2003. Start-up (linux container) with "Verify that the Virtual Machine Management service on the computer is running"...
No luck to find a solution so far...

**Comment by KarGrat** [comment]
It seems that my problem is solved, by itself....
A new patch from W10 has been installed and docker is now reworking properly
Here below is the 3 patches installed automatically - one of them is the good one and I guess this is the first one KB4494441

![image](https://user-images.githubusercontent.com/25660464/58474529-a6a6f280-814b-11e9-910a-f462b5f0340f.png)
