### ISSUE TITLE
extremely slow network connection on win2016 host on gce after uninstalling docker 18.03ce1

### ISSUE THREAD

**Issue by sabujp** [docker/for-win#3840]
I have a windows 2016 VM running on GCE. It has docker 18.03ce1 installed. After I uninstall docker, scp/rsync over ssh connections to windows (via cygwin ssh) cannot exceed 10MB/s. Upgrading docker to the latest has the same effect as well. I checked all netsh int tcp show global and get-nettcpsettings before and after the uninstall and they are all identical.

### Expected behavior

Uninstalling or upgrade docker should not affect network performance on the host

### Actual behavior

Uninstalling docker reduces network performance scp/rsync over ssh by 3x

### Information

Yes, it's reproducible without doing *anything* else to the VM image other than just uninstalling Docker, the behavior as explained above occurs. It doesn't matter if the system has the latest windows updates either.

### Steps to reproduce the behavior

  1. Be running windows server 2016
  2. Have installed docker 18.03
  3. Run some transfers via scp or rsync over ssh with cygwin openssh
  4. Uninstall docker 18.03 or upgrade it latest docker
  5. Try transfers again and they will be 3x slower

**Comment by MaxyManju777** [comment]
Try with version 18.09.2
Check RAM size

**Comment by sabujp** [comment]
this is with the n1-cpu-4 (15gb ram instance), installing the latest doesn't help. The main issue here is why does *uninstalling* docker cause the network performance to plummet on the host? It's doing something to the network configuration somewhere that's causing this that isn't being show in netsh int tcp, get-nettcpsetting, or in the driver settings. The MTU also remains unchanged (1460 ..which is what gce currently only supports).

**Comment by sabujp** [comment]
I also turned off all hyper-v services and network switches and it didn't help. I also created a virtual switch in hyper-v (after disabling and re-enabling it) and made sure SR-IOV was enabled and that didn't help either.
