### ISSUE TITLE
Credentials needs to be reset all the time

### ISSUE THREAD

**Issue by sebastien-f** [docker/for-win#385]
### Expected behavior
Once credentials have been applied for Shared Drives, not having to set them again on a regular basis. 

### Actual behavior
I have two drives shared (F: & G:) through the Shared Drives menu in the settings. Those drives are where my projects are stored.

I'm creating my container something along this :

docker run -d -p 80:80 -p 3306:3306 -v G:\\__SOURCES\projectname\:/var/www --name project ubuntu:trusty

Everything works fine for a while (I can move, delete, edit, create files, either on the host or the container), then at some point, the volume will lose its rights and I will get, if the container is running :

```
root@c7c4a0903d5c:/var/www# ls
ls: reading directory .: Permission denied
```

If the container is not running and I try to run it, I'll get the following : 

`C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\"/G/__SOURCES/projectname/\\" to rootfs \\"/var/lib/docker/aufs/mnt/4b3252fe8a78b3092080cb514c8a6088bbbe1b4186f70f405e9e130cb7530b47\\" at \\"/var/www\\" caused \\"stat /G/__SOURCES/projectname: permission denied\\"\"".`

If I go to Settings, Shared Drives and click "Apply" or "Reset credentials", everything will works fine again, until it won't and I'll get the two messages above.

The container I'm launching is a basic ubuntu with a bunch of web dev stuff installed (apache, mysql,you get the idea).

I'm using Docker for Windows, version 1.12.5 and 1.13.0-rc5 build 43cc971, under Windows 10 pro, no domain joined, logging with a microsoft account.

### Information

  - Diagnostic ID :  9CDF3AFE-E0E7-44FF-9E3B-49BDC3BC2777/2017-01-13_14-10-40
  - Issue exists with all Dockerfiles
  - Window 10 Pro, docker version 1.12.5, 1.13.0-rc5 build 43cc971, 1.13.0-rc6, build 2f2d055.

### Steps to reproduce the behavior

  1. Share drives
  2. Start a container with volume shared on those drives
  3. Wait

**Comment by sebastien-f** [comment]
Issue still exists in Docker version 1.13.0-rc7, build 48a9e53.

If I can provide anything that would help troubleshoot that issue, feel free to tell me. 

I have try so many things to fix this, but I've run out of idea.

**Comment by simonferquel** [comment]
Thanks @sebastien-f, we'll investigate this further and eventually come with a fix. By any chance, is there a networking setting change when this occur ? (like change of wifi network, vpn connection,...)

**Comment by sebastien-f** [comment]
@simonferquel Thank you for acknowledging the issue. Regarding your question : no networking settings change that I am aware. Computer is connected via ethernet to a router, which itself is behind the internet box. Computer is configured with a static IP, internet IP is static too. I have a VPN connection to connect to a remote network, but said connection is triggered by hand only and I have not been connected to it for a while (weeks, if not months).

**Comment by sebastien-f** [comment]
Just to add more to the diagnostic : since updating to 1.13.0 build 49bf474 (more or less when it was available), I did not run into the issue until today (at the container start). Applying was not sufficient, I had to reset the credentials. I was connected to the VPN earlier today. I'll keep updating if I notice anything related to the issue and worthwile.

**Comment by michaelva** [comment]
I have the exact same issue on Window 10 Pro with docker 1.13.1-beta42. I usually have to restart docker to solve the problem.

**Comment by FredM** [comment]
Same issue on Windows 10 Pro using Docker 17.03.0-ce-win1 (10296)
Clicking on "Restart Docker" in the "Reset" tab solves the issue temporarily.

**Comment by sebastien-f** [comment]
A bit more input on my lastest observations. 

It really looks like this behavior is tighly connected to shared volumes. In one of the container I've been running, I have been using it outside of any shared volumes and almost never run into the issue. 

In an other container, I often save and edit files in the shared volume and ran into the issue on a frequent basis (couple of time per hour). 

Issue still present in 17.03.0-ce-win1 (10300)

**Comment by sebastien-f** [comment]
Had the issue à 12:06, opened the log at that time. Didn't do much until right now. Issue was there. 

Not much in the log

[12:06:38.489][FeedbackSettings][Info   ] Open logs
[12:38:18.729][SegmentApi     ][Info   ] Usage statistic: heartbeat
[13:38:18.730][SegmentApi     ][Info   ] Usage statistic: heartbeat
[13:38:30.852][Updater        ][Info   ] Checking for updates on channel beta...
[13:38:31.148][Updater        ][Info   ] Local build 10300 is as good as the remote 10300 on channel beta

**Comment by rneugeba** [comment]
@smithma01 reported the same issue on #547

**Comment by ikovalyov** [comment]
same issue happens randomly on win10 pro and Docker version 17.03.0-ce, build 60ccb22

**Comment by Motsols** [comment]
I can also confirm this annoying issue. I run local account on Win 10 Pro with Docker version 17.03.0-ce, build 60ccb22.

My container is using a shared drive and I need to reset credentials daily (sometimes a couple of times per day). It seems that if the container that uses the shared drive is up the entire day, it only asks once. If I stop it, leave it a few hours and then try to start it again I sometimes need to reset my credentials.

**Comment by TehJoE** [comment]
I have the same (or similar) problem. I have noticed that I can get shared drives working for a while by simply clicking "Apply" on the Shared Drives screen, rather than resetting credentials. It seems to stop working again after about 15 minutes or so, regardless of whether I reset credentials or just "Apply".

It seems like the share disconnects after 15 minutes of idle time, and then the VM tries to reconnect, but mysteriously fails to authenticate. If this is the case, I have no explanation for why this suddenly started happening when it worked before. 

Note that the SMB autodisconnect defaults to 15 minutes: [https://support.microsoft.com/en-us/help/297684/mapped-drive-connection-to-network-share-may-be-lost](https://support.microsoft.com/en-us/help/297684/mapped-drive-connection-to-network-share-may-be-lost) 
Even setting the autodisconnect interval to -1 to disable it didn't solve the problem.

Windows event viewer, under Applications and Services Logs/Microsoft/Windows/SMBServer/Security:
![](http://puu.sh/xLbCt/b1f0c49a1c.png)
The gaps in timestamps on these seem to roughly match when the share stops working.

/var/log/syslog on the VM:
![](https://puu.sh/xLbK4/c559b78b2a.png)
These just go on for a long, long time.

Docker version:
![](https://puu.sh/xLboJ/a693dc8805.png)

**Comment by eino-makitalo** [comment]
I have same problem... I try to check if these can help
https://social.technet.microsoft.com/Forums/windowsserver/en-US/82c9371a-eab9-4526-ba34-81d1f3bdc141/vm-cannot-access-to-a-hostshare-using-hyperv?forum=winserverhyperv

like  command
netsh interface tcp set global NetDMA = DISABLED

**Comment by viniciusraupp** [comment]
Same problem.
Windows 10 PRO 1803
Docker Version 18.03.1-ce-win65 (17513)

**Comment by jengstro2** [comment]
"corporation" IT called me, and they said some "thing" keeps authenticate with wrong windows credentials all the time. We identified its Docker (... probability is high). Bad thing is, that as automatic security procedure, my corp win account is locked :-( nice....
---
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.15063 Build 15063
Docker Version 18.03.1-ce-win65 (17513)

**Comment by LiamKarlMitchell** [comment]
still a problem

**Comment by arroyc** [comment]
/remove-lifecycle stale
I'm still repro-ing this issue on my machine ... using  docker for windows 18.06.1-ce-win73(19507) and my windows is 10.01.17134 build 17134 Win 10 enterprise
![image](https://user-images.githubusercontent.com/16231002/47760750-1404aa80-dc73-11e8-9013-1f7d8a3dae4e.png)

**Comment by sebastien-f** [comment]
Not sure if commenting/unstalling is usefull at that point as the issue has been automaticaly closed and I can't reopen it for you guys. I'm guessing that, as it did not gain a lot of traction while open, it will get even less while closed. I gave up on docker a while ago, partly due to this issue. Maybe reopen a new one and reference this one in it ?

**Comment by LiamKarlMitchell** [comment]
/remove-lifecycle stale
![image](https://user-images.githubusercontent.com/1968109/48457561-11d04d80-e828-11e8-9fbc-fbe0df29ed62.png)
Happening after password change, but it seems to be happening frequently after periods of inactivity on the PC, so that Resetting credentials only helps temporarily.

**Comment by linuxchata** [comment]
The same issue with Docker CE 18.06.1-ce-win-73 (19507)

**Comment by guixermo** [comment]
I'm having the same issue in a Ubuntu Vm in a Windows10 Host OS.
Anyone knows how can i reset credentials on ubuntu?

Thank you so much!!

**Comment by danielfroz** [comment]
The problem continues... have about 25 docker on Windows install running across different install bases. Recently installed in one customer and this last one is facing this annoying problem. Any fix has been provided? Please reply this issue with the fix release number so I can upgrade all to the correct version. Thanks

**Comment by ffMathy** [comment]
@simonferquel it seems this issue was closed prematurely by the stale issues bot. Can you re-open?

Happens to me too after upgrading to Docker 2.2.0.

**Comment by mat007** [comment]
@ffMathy is suspect what you’re experiencing is similar to #5567 as there should be no more credentials required starting with 2.2.0.0.

**Comment by ffMathy** [comment]
Thanks @mat007 - that seems to be it.
