### ISSUE TITLE
 wsarecv: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by waleadekoya** [docker/for-win#3853]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E68008E9-26C0-4B05-B15A-2AC9A129C688/20190504062129

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

read tcp 192.168.1.144:62377->204.79.197.219:443: wsarecv: An existing connection was forcibly closed by the remote host.

  1. ...
  2. ...
![image](https://user-images.githubusercontent.com/50258092/57174406-4ff11600-6e36-11e9-8ad3-6ff2aa1826b0.png)

**Comment by waleadekoya** [comment]
Docker version 18.09.2, build 6247962 [Docker DeskTop]
Windows 10 Pro

**Comment by kondalag** [comment]
Have the similar issue on machine as well. Is there any solution for it ?

**Comment by Gaboxondo** [comment]
same error... any answer?

**Comment by wawa0210** [comment]
same error... any answer? :<
