### ISSUE TITLE
Docker messed up hosts

### ISSUE THREAD

**Issue by OskarKlintrot** [docker/for-win#3866]
My `hosts` all of a sudden got corrupted and it looks like Docker Desktop v2.0.0.3 might have something to do with it.

![image](https://user-images.githubusercontent.com/6783879/57226048-5508bd80-700e-11e9-84d9-2b12d5fc5957.png)

![image](https://user-images.githubusercontent.com/6783879/57226072-62be4300-700e-11e9-8094-c40a028cf7cd.png)

**Comment by rcnicke** [comment]
This happened to me too.
Had a lot of config in my hosts file for dev purposes, and all of a sudden nothing seems to work on my dev machine.
Turns out my hosts file has been messed up, and it looks like docker desktop 2.1.0.3 has messed it up.

![image](https://user-images.githubusercontent.com/12692531/66118057-c062b580-e5d5-11e9-8428-72746fecb362.png)

**Comment by OskarKlintrot** [comment]
@simonferquel or someone? Maybe this needs to be looked at? I can not reopen the issue.

**Comment by simonferquel** [comment]
@ebriney can you PTAL ?

**Comment by OskarKlintrot** [comment]
It happened again:
![image](https://user-images.githubusercontent.com/6783879/68574902-3d057100-046b-11ea-9daa-c3b0ed669089.png)

v2.1.0.4 (39773)

**Comment by ebriney** [comment]
@OskarKlintrot I did a PR to force encoding when we read the file but the C# code was already quite straightforward:
 - loading hosts file with `File.ReadAllLines(filepath)`
 - checking/adding entries in the array
 - then saving using `File.WriteAllLines(newArray, filepath)`
Can you attach your hosts file so I can see what are the bytes on that first corrupted line?

**Comment by mikeparker** [comment]
It would also be good to know if you opened the hosts file in a particular editor and saved it again and if you saved it with a particular encoding.

**Comment by OskarKlintrot** [comment]
I opened the hosts file in VS Code. I tried to open it multiple times with different encodings but none worked. When I had restored it I saved it as UTF-8 using VS Code.

**Comment by OskarKlintrot** [comment]
@ebriney I have already restored it but if it happens again I will give it to you!

**Comment by ebriney** [comment]
Thanks

**Comment by OskarKlintrot** [comment]
@ebriney Now I have a corrupt hosts-file, do you have an email so I can send it to you? It does not contain any secrets per se but I still do not feel comfortable uploading it to the general public.

**Comment by mat007** [comment]
@OskarKlintrot which Docker Desktop are you running?

**Comment by OskarKlintrot** [comment]
Version 2.1.0.5 (40693)

**Comment by ebriney** [comment]
Great @OskarKlintrot, good news, we changed a bit the code but it has not yet been released on stable (you can get it in edge channel).
But send me your corrupted hosts file to emmanuel.briney@docker.com and I'll check if I find something interesting.
Thanks a lot.

**Comment by OskarKlintrot** [comment]
You've got mail 📬 

Any idea when the fix will be released?

**Comment by ebriney** [comment]
Thanks @OskarKlintrot !
Ok, it's full of 0 at start of file!
You can try last stable to see if the changes we did fixed it: https://download.docker.com/win/stable/Docker%20Desktop%20Installer.exe
