### ISSUE TITLE
erro ao iniciar

### ISSUE THREAD

**Issue by robison915** [docker/for-win#3878]
Unable to create: O comando em execução parou porque a variável preferencial "ErrorActionPreference" ou o parâmetro comum está definido como Stop: O Hyper-V encontrou um erro ao tentar acessar um objeto no computador 'DESKTOP-9RDMSKD'porque não localizou o objeto, que talvez tenha sido excluído. Verifique se o serviço Gerenciamento de Máquinas Virtuais está em execução no computador.
em New-Switch, <Nenhum arquivo>: linha 121
em <ScriptBlock>, <Nenhum arquivo>: linha 411
   em Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) na C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:linha 36
   em Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) na C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:linha 92
   em Docker.Actions.<>c__DisplayClass21_0.<ResetToDefault>b__0() na C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:linha 155
   em Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() na C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:linha 59

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version: Windows 10 pro
  - Docker for Windows Version: 
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by alefcarlos** [comment]
Rapaz, tive o mesmo problema.

Siga esse passo-a-passo: https://social.technet.microsoft.com/Forums/en-US/ee5b1d6b-09e2-49f3-a52c-820aafc316f9/hyperv-doesnt-work-after-upgrade-to-windows-10-1809?forum=win10itprovirt

**Comment by robison915** [comment]
Muito obrigado, resolveu o meu problema

**Comment by bacci** [comment]
> Rapaz, tive o mesmo problema.
> 
> Siga esse passo-a-passo: https://social.technet.microsoft.com/Forums/en-US/ee5b1d6b-09e2-49f3-a52c-820aafc316f9/hyperv-doesnt-work-after-upgrade-to-windows-10-1809?forum=win10itprovirt

Resolveu meu problema também
