### ISSUE TITLE
AMD Ryzen Master and Docker incompatability

### ISSUE THREAD

**Issue by CryptidCollective** [docker/for-win#3882]
Hello
I have an AMD 2700x Ryzen PC, Windows 10. 
I need to keep the cores in the processor boosted so use AMDs software, Ryzen Master to do this. This software is not compatible with Hyper-V so I have to keep that off. But i'd like to run docker, but docker needs Hyper-V enabled. Is there any work around, is there a docker that doesn't need Hyper-V.
thank you.

**Comment by lolmaus** [comment]
Yes, please use this: https://kitematic.com/

It will offer a VirtualBox-based installation of Docker.

**Comment by mikeparker** [comment]
You can run Docker Desktop in Windows container mode, that doesn't use Hyper-V?

**Comment by lolmaus** [comment]
An unrelated note for people coming from Google search.

I've finally had Docker Desktop running successfully on AMD Ryzen 2700X.

My issue, apart from enabling Hyper-V in BIOS (which Gigabyte *conveniently* calls `SVM`), was in the presence of the legacy Docker Toolbox in the system.

Docker Desktop started working after I removed Docker Toolbox and cleaned its env vars.

PS Credit [goes](https://github.com/docker/for-win/issues/2575#issuecomment-504534684) to @allout58.

**Comment by mikeparker** [comment]
@lolmaus thanks a lot for reporting back! I'll make a note of those findings.

**Comment by shammelburg** [comment]
So is it safe to say that the Ryzen 3900x and Docker will play nice together?
