### ISSUE TITLE
Docker Installation to different Drive Application communicates to HNS IP instead of Server IP

### ISSUE THREAD

**Issue by dharav9** [docker/for-win#3883]
I installed docker in the d: drive successfully by manually creating daemon.json file in the "c:/programdata/docker/cnfig" folder. I place  {"data-root" : "d://Doker"} line in the daemon.json file and restarted docker services.

Isuue: When i had installed docker in the system drive (C:\Programdata\docker) then my application   can talk to Server FQDN and Server IP address : - At this time we have not manually created daemon.json file

Now, when i installed docker on the D: drive by creating manual daemon.json file then my application can only talk to HNS IP address instead of Server FQDN or Server IP address.

As, we created manual daemon.json file to configure data directory, do we need to pass another variable so that it can listen to server FQDN or server IP as well?

We could say that it listens to IPv6 instead of ipv4.

Server Environment - Windows Server 2016

PS C:\Windows\System32> docker info
Containers: 23
 Running: 22
 Paused: 0
 Stopped: 1
Images: 24
Server Version: 17.06.2-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.447.amd64fre.rs1_release_inmarket.161102-0100)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 24
Total Memory: 511.9GiB
Name: DBNAAEAP035
ID: 52IO:H34S:QKFT:3SHY:YS6L:QDNP:SYT2:QA4G:3YOO:J3AD:HELS:V6GR
Docker Root Dir: D:\DockerDev
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
#------------------------------------
PS C:\Windows\System32> docker version
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:57:19 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:47 2017
 OS/Arch:      windows/amd64
 Experimental: false
#---------------------------------------------
**C:\Windows\System32>ipconfig/all**

Windows IP Configuration

   Host Name . . . . . . . . . . . . : DBNAAEAP035
   Primary Dns Suffix  . . . . . . . : development.webmd.net
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   DNS Suffix Search List. . . . . . : wpd.envoy.net
                                       envoy.net
                                       emdeon.net

Ethernet adapter Teaming - 10.165.168.22:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft Network Adapter Multiplexor Driver
   Physical Address. . . . . . . . . : 18-66-DA-FC-35-D0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   IPv4 Address. . . . . . . . . . . : 10.165.168.22(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 10.165.168.1
   DNS Servers . . . . . . . . . . . : 10.160.191.11
                                       10.140.191.13
   NetBIOS over Tcpip. . . . . . . . : Enabled

Ethernet adapter Backup - 10.165.220.111:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Broadcom NetXtreme Gigabit Ethernet
   Physical Address. . . . . . . . . : 18-66-DA-FC-35-D2
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   IPv4 Address. . . . . . . . . . . : 10.165.220.111(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.252.0
   Default Gateway . . . . . . . . . :
   NetBIOS over Tcpip. . . . . . . . : Enabled

Ethernet adapter vEthernet (HNS Internal NIC):

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter
   Physical Address. . . . . . . . . : 00-15-5D-9F-16-2D
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::a561:bbce:fe5a:8501%15(Preferred)
   IPv4 Address. . . . . . . . . . . : 172.17.128.1(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . :
   DHCPv6 IAID . . . . . . . . . . . : 318772573
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-24-5A-CE-7E-18-66-DA-FC-35-D2
   DNS Servers . . . . . . . . . . . : fec0:0:0:ffff::1%1
                                       fec0:0:0:ffff::2%1
                                       fec0:0:0:ffff::3%1
   NetBIOS over Tcpip. . . . . . . . : Enabled

Tunnel adapter isatap.{E440EAFA-8C72-4628-AB58-D88F801A55C7}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft ISATAP Adapter
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes

Tunnel adapter isatap.{6297C744-F5E8-43BD-A877-658E2D465EBD}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft ISATAP Adapter #2
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes

Tunnel adapter isatap.{CB546CB2-8F12-4A96-B6B0-446BEFB4DFB6}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft ISATAP Adapter #3
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes

**Comment by dharav9** [comment]
Following has been found from the logs:

AH00558: httpd.exe: Could not reliably determine the server's fully qualified domain name, using fe80::646c:1c37:967:d3fe. Set the 'ServerName' directive globally to suppress this message

**Comment by mikeparker** [comment]
This repo is for Docker Desktop bugs and you're running Docker Engine - Enterprise (windows server).

Please raise issues on https://github.com/moby/moby
