### ISSUE TITLE
Volume mounts do not work on windows 10 until I provide full path

### ISSUE THREAD

**Issue by yrshaikh** [docker/for-win#3885]
### Expected behavior
With this command I am able to mount perfectly `C:\Users\yshaikh>docker run --rm -v c:/Users/yshaikh/dockertest:/data alpine ls /data` 

But when I use the relative path like for example 
`C:\Users\yshaikh>docker run --rm -v dockertest:/data alpine ls /data` it does not mount.

### Actual behavior
Should be able to mount?

### Information
1. Able to reproduce on multiple machines.
2. Windows 10
3. Docker version 18.09.2, build 6247962
4. Shared Drive permission is given.

**Comment by lk77** [comment]
Hello,

same issue here since i updated docker,
my docker-compose.yml that uses a volume ./:/var/www, that used to work, doesnt work anymore.

Thanks.

**Comment by lk77** [comment]
Hello,

any news on this ?
it's still a big issue.

**Comment by spagu** [comment]
any updates to this in 2020?

**Comment by JackOfSpade** [comment]
Ignore the existence of a problem and it shall go away.
