### ISSUE TITLE
E3AF7F7F-082F-4F1F-A13C-320E564FBE4B/20190509102452

### ISSUE THREAD

**Issue by singhp27** [docker/for-win#3886]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mikeparker** [comment]
Please use the issue template and create a new issue with a description of what you were trying to do, what the problem is, diagnostics ID and repro instructions.
