### ISSUE TITLE
Hello world:nanoserver gives me this error

### ISSUE THREAD

**Issue by gcrandell426** [docker/for-win#3889]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by gcrandell426** [comment]
Anyone else seeing the same problem when you test hello world? 

C:\Program Files\Docker\docker.exe: failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImag
e \\?\C:\ProgramData\docker\windowsfilter\87f245f9a302cdd6f4b10d372bdb627eb1f636dc20ddb4208295329e76e4c88b\UtilityVM: Th
e system cannot find the path specified.
See 'C:\Program Files\Docker\docker.exe run --help'.

**Comment by sathsara1** [comment]
I'm facing the same issue :( Is there any way that i can resolve this...
