### ISSUE TITLE
Misspelling in the error dialog box.  "An error occured"

### ISSUE THREAD

**Issue by braveness23** [docker/for-win#389]
### Expected behavior

"An error occurred" (with two 'r's)

### Actual behavior

"An error occured" (with one 'r')

### Information

  - host distribution and version (Windows version, build number, etc)

C:\Users\xxx>docker version
Client:
 Version:      1.13.0-rc6
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   2f2d055
 Built:        Wed Jan 11 21:47:55 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-rc6
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   2f2d055
 Built:        Wed Jan 11 21:47:55 2017
 OS/Arch:      linux/amd64
 Experimental: true

### Steps to reproduce the behavior

  1. Do something that causes an error
  2. Hope your high school English teacher isn't looking ;-)

**Comment by simonferquel** [comment]
Thanks for the report @braveness23 we'll make sure to fix that soon !

**Comment by braveness23** [comment]
perrfect ;-)

**Comment by rneugeba** [comment]
Closing. thanks again for the report.
