### ISSUE TITLE
hnsCall failed in Win32

### ISSUE THREAD

**Issue by mvtleite** [docker/for-win#3893]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: AEA65184-E9CD-4E88-B467-FDE8E92CF454/20190510125704

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. Downloada image
  2. Start image

Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: failed to create endpoint RestMongo on network nat: hnsCall failed in Win32: O arquivo já está sendo usado por outro processo. (0x20).

**Comment by mikeparker** [comment]
Are you binding to the same port twice with 2 containers?
