### ISSUE TITLE
Docker run hello-world errs out with error during connect

### ISSUE THREAD

**Issue by trentwh64** [docker/for-win#3894]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: D7D9A5B8-1C54-44FD-826F-BD047B51E36B/20190510093806

### Expected behavior
Performed  docker run hello-world

### Actual behavior
Erred out
docker : C:\Program Files\Docker\Docker\Resources\bin\docker.exe: error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/containers/create: open //./pipe/docker_engine: The system 
cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
### Information

  - Windows Version: Version 1803 (OS Build 17134.1)
  - Docker for Windows Version:
Version 2.0.0.3 (31259)
Channel: stable
Build: 8858db3

### Steps to reproduce the behavior

  1. … Simply ran docker run hello-world
  2. ...

**Comment by DankoValkov** [comment]
Hello @trentwh64 ,

Earlier today I have experienced the same behavior, where it turns out to be exactly what the message is saying - "..docker daemon is not running". 

To switch it back you could do following in the CMD:

cd "C:\Program Files\Docker\Docker"
./DockerCli.exe -SwitchDaemon

and give your command for running the container another try.

**Comment by mikeparker** [comment]
Relevant lines from log
```
[14:46:40.476][NamedPipeServer][Error  ] Unable to execute Start: Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start.

Failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running.

'MobyLinuxVM' failed to start. (Virtual machine ID E167C6A7-7C1E-4915-BE5C-D1E3DA9CDC52)

The Virtual Machine Management Service failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running (Virtual machine ID E167C6A7-7C1E-4915-BE5C-D1E3DA9CDC52).
at Start-MobyLinuxVM, <No file>: line 296
```
This means you don't have all the Hyper-V components running properly. There are multiple possible causes for this:
* Maybe VirtualBox or other 3rd party software preventing Hyper-V from running (e.g. 3rd party virus scanners)
Could you check if the following Hyper-V components are running?

* Hyper-V Host Compute Service
* Hyper-V Virtual Machine Management

**Comment by planetjavainc** [comment]
> 
> 
> Hello @trentwh64 ,
> 
> Earlier today I have experienced the same behavior, where it turns out to be exactly what the message is saying - "..docker daemon is not running".
> 
> To switch it back you could do following in the CMD:
> 
> cd "C:\Program Files\Docker\Docker"
> ./DockerCli.exe -SwitchDaemon
> 
> and give your command for running the container another try.

After 2 days of trying, you suggestion worked for me.......
cd "C:\Program Files\Docker\Docker"
DockerCli.exe -SwitchDaemon    

I can now run the helloworld image.
Thank you so much, I hope things get easier from here!  :^)
