### ISSUE TITLE
 Stop: 'MobyLinuxVM' failed to start

### ISSUE THREAD

**Issue by tusharbudhe0302** [docker/for-win#3895]
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start.

Failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running.

'MobyLinuxVM' failed to start. (Virtual machine ID E29796F3-81DE-4BA7-81DC-986110B3E602)

The Virtual Machine Management Service failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running (Virtual machine ID E29796F3-81DE-4BA7-81DC-986110B3E602).
at Start-MobyLinuxVM, <No file>: line 287
at <ScriptBlock>, <No file>: line 382
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

---------------------------------------------------------------------------------------------

PS C:\Users\vmuser> docker images
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.27/images/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

**Comment by mikeparker** [comment]
It's likely something is preventing Hyper-V components from running correctly. Do you have any of the following:
* VirtualBox
* Cisco AnyConnect
* VPN clients
* 3rd party virus scanner

You can also try to inspect and enable the Hyper-V components yourself

**Comment by tusharbudhe0302** [comment]
yes, it's work. I have to restart my virtual machines. Enable it.

![image](https://user-images.githubusercontent.com/17787642/59046355-dc389380-884f-11e9-9386-5d5d5126e012.png)

**Comment by mikeparker** [comment]
Sorry, I don't understand. Do you mean it now works, because you restarted VirtualBox?

**Comment by tusharbudhe0302** [comment]
Yes, It's working. Thanks. Need to enable DHCP Server into Oracle VM Virtual box. You can close this issue.

**Comment by mikeparker** [comment]
@tusharbudhe0302 this error is the highest reported error for us. To get more information about it - can you tell me: Were you running Docker inside Windows inside VirtualBox?
