### ISSUE TITLE
Redirecting docker folder to alternate folder causes nat virtual switch to disappear

### ISSUE THREAD

**Issue by chunkyen** [docker/for-win#3907]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
nat switch should be visible in Hyper-V manager and Windows container networking shoud be mapped to host port to container port via the -p switch (such as -p 8080:80)
### Actual behavior
When the docker daemon config file was added with either graph: option ("graph": "D:\\docker")
or the data-root option ("data-root": "d:\\docker"), after a reboot the nat virtual switch will disappear. But the virtual nic for vEthernet (nat) is still visible however host to container nat is no longer working.
Removing the graph or data-root option solves the problem.
### Information

  - Is it reproducible?  yes
  - Is the problem new?  can't seems to find a similar problem on the web.
  - Did the problem appear with an update? No

  - Windows Version: 1903 (18362.86)
  - Docker for Windows Version: Docker version 19.03.0-beta3, build c55e026

### Steps to reproduce the behavior

  1. Verify nat virtual switch is present in Hyper-V manager
  2. Add "graph": "D:\\docker" to Docker Daemon Settings (Advanced)
 3. Reboot
4. Check Hyper-V manager, nat switch disappear
5 Run aspnetcore sample container with nat port mapping 8080:80, not working.
6. remove the line added in step 2
7. Reboot
8. nat virtual switch is back and nat port mapping to container is working again.

**Comment by mikeparker** [comment]
Do you have any errors in the log file? 
Did you add the line to the UI daemon settings or did you edit the json file manually by hand?
If you edited in the UI settings, can you check the json file is output as expected?

**Comment by chunkyen** [comment]
Which log file should I be looking at?
I edited the daemon settings in the UI and have verified that the dameon.json file reflected the change.

**Comment by mikeparker** [comment]
~\AppData\Local\Docker\log.txt

**Comment by chunkyen** [comment]
The only error I've got is shown below
[ApiProxy       ][Error  ] Process died

Other than no nat networking, other parts of docker appears to work normally.
