### ISSUE TITLE
2B92F0D6-2C68-4779-8DDD-80CBC76FB955/20190514132404

### ISSUE THREAD

**Issue by preethgit** [docker/for-win#3909]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mikeparker** [comment]
Please use the issue template and create a new issue with a description of what you were trying to do, what the problem is, diagnostics ID and repro instructions.
