### ISSUE TITLE
[bug] Docker is not working!

### ISSUE THREAD

**Issue by BeyondLimitation** [docker/for-win#391]
Diagnostic id: 7287BFDD-FFC2-40D0-8316-CDB6888C32D5/2017-01-14_13-59-35

My issue: i cannot connect my docker!
I typed `docker info` but i got a error!
And Docker was not running. Removed & Reinstalled it, but same...

What should i do?

**Comment by rneugeba** [comment]
On your system the Linux VM starts very slowly, but in the end I see it running

what's the error you get?

You could also try the latest Beta. It probably won't start faster but may not display the error.
Thanks

**Comment by BeyondLimitation** [comment]
@rneugeba What a strange... Now works fine. Closing this issue.
????
