### ISSUE TITLE
Unable to Change the timezone of a Windows ServerCore container - Access Denied

### ISSUE THREAD

**Issue by kalitse** [docker/for-win#3911]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Running `docker exec --privileged ContainerName powershell "Set-TimeZone 'Eastern Standard Time'"` will change timezone of container to EST.

### Actual behavior
Running `docker exec --privileged ContainerName powershell "Set-TimeZone 'Eastern Standard Time'"` produces the following:
```
Set-TimeZone : Access is denied
At line:1 char:1
+ Set-TimeZone 'Eastern Standard Time'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : FromStdErr: (:) [Set-TimeZone], Win32Exception
    + FullyQualifiedErrorId : SetTimeZoneFailed,Microsoft.PowerShell.Commands.
   SetTimeZoneCommand
```

### Information

I'm fairly new to containers so it's possible I'm missing something obvious. I searched for existing posts with the same issue or something similar and found a few that seemed promising : [moby/moby#37283] [moby/moby#32518] but none of them address changing the timezone of the container directly.

What information is available out there is either for Linux based containers or for Win 10 Docker CE. Not sure how much of a difference this makes, but the solutions provided did not resolve this issue.

I appreciate any suggestions or help from the community. Thanks in advance for your time.

  - Windows Version:
Google Cloud Compute Engine Images;
```
Windows Server 2019 Datacenter Core for Containers
Server Core, x64 built on 20190411
```
Container Image used: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019
-and
```
Windows Server version 1803 Datacenter Core for Containers
Server Core, x64 built on 20190411
```
Container Image used: mcr.microsoft.com/windows/servercore/iis:windowsservercore-1803

  - Docker for Windows Version:
```
Client: Docker Engine - Enterprise
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        be4553c277
 Built:             04/11/2019 06:44:52
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.8
  Git commit:       be4553c277
  Built:            04/11/2019 06:43:04
  OS/Arch:          windows/amd64
  Experimental:     false
```
### Steps to reproduce the behavior

  1. Create a servercore:ltsc2019 container
`docker run -itd --name example mcr.microsoft.com/windows/servercore:ltsc2019`
  2. Try to change the timezone of just the container
`docker exec --privileged example powershell "Set-TimeZone 'Eastern Standard Time'"`

**Comment by devkws** [comment]
same issue. Any work arounds?

**Comment by mikeparker** [comment]
Looks like you're running Docker Engine Enterprise, not Docker Desktop. You want https://github.com/moby/moby

**Comment by devkws** [comment]
I’m running docker for desktop. Same issue.

**Comment by mikeparker** [comment]
@devkws can you open a separate issue and attach your diagnostic ID please?

**Comment by kalitse** [comment]
Can I get an explanation for this? What is 'moby' and why should I use it instead of the Microsoft updated images?

[Administrateur Syst?mes EIT / EIT Systems Administrator]
www.gebocermex.com<http://www.gebocermex.com/>
christian.monaghan@sidel.com<mailto:christian.monaghan@sidel.com>
[cid:image002.jpg@01D516E6.3FE59F80]

**Comment by mikeparker** [comment]
This repo is for reporting bugs with Docker Desktop, and you are not using Docker Desktop.

To report bugs with Docker Engine Enterprise, please add your issue to https://github.com/moby/moby, its the runtime for docker engine enterprise. Alternatively contact Microsoft support.
