### ISSUE TITLE
Trying to quit docker results in "An error occurred"

### ISSUE THREAD

**Issue by royharp** [docker/for-win#3915]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
That docker would quit when I clicked [Quit] in the dialog "Service is not running / Docker Desktop Service is not running, would you like to start it? Windows will ask you for elevated access."
### Actual behavior
The "An error occurred" dialog appeared
### Information

  - Windows Version: Windows 10 Pro 1809 17763.475
  - Docker for Windows Version: Latest (I downloaded it today)

### Steps to reproduce the behavior

  1. Get a BSOD on Ntfs.sys SYSTEM EXCEPTION ERROR
  2. Do chkdsk /f on all drives
  3. Have docker report the BSOD
  4. Reboot
  5. Tell docker you want to quit rather than start
  6. Voila, the error occurs.

**Comment by mikeparker** [comment]
Can you link a diagnostic ID or the error message?

**Comment by royharp** [comment]
This is not a fix, but it helps. Right-click the docker icon in the notifications area, choose Settings, General, then uncheck the "Start Docker Desktop when you log in."

I, too, have received errors when quitting docker during its auto-startup process (none so spectacular as yours, but errors nonetheless). This is the way that works best for me. Alternatively, you can let Docker finish it's startup process, then quit it.
