### ISSUE TITLE
Not able to open docker desktop app

### ISSUE THREAD

**Issue by sajeeshthambiraj** [docker/for-win#3918]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:22064613-1FF0-4418-A0DF-B018294EB424/20190515151920

### Expected behavior
Not able to open Docker
### Actual behavior
Docker Cli not comming up

### Information

  - Windows Version: Windows 10 Enterprise 1709
  - Docker for Windows Version: 2.0.0.3

### Steps to reproduce the behavior

  1. After installation opened the DOCKER desktop app
  2. ...

**Comment by mikeparker** [comment]
Your diagnostic ID is not valid and your description is too vague to diagnose:
1. What do you mean by the Docker CLI not coming up?
2 Did docker desktop successfully start?
3. Can you use the system tray whale item, can you reach the about box?
4. Can you use docker commands from the command line, powershell etc?
