### ISSUE TITLE
Missing /etc/hostname in MobyLinuxVM

### ISSUE THREAD

**Issue by ziggemannen** [docker/for-win#3920]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
A running container
### Actual behavior

container not beeing starrted
trying to bind mount /etc/hostname to /etc/nodename in node-exporter (part of swarmprom) causes an error stating that /etc/hostname does not exist

The mount in stack.yml: "- /etc/hostname:/etc/nodename"
### Information

Tried on two different PC's with the same result.

  - Windows Version: 10 (1809)
  - Docker for Windows Version: 18.09.2

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mikeparker** [comment]
Can you give reproduction instructions please, with your docker-compose and images if possible
