### ISSUE TITLE
Cannot start service 2019

### ISSUE THREAD

**Issue by jampzo** [docker/for-win#3921]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3228ECD8-A24E-4051-81AD-B43E6A2357CD/20190515235029

docker-compose up

Cannot start service dtredis: driver failed programming external connectivity on endpoint dyrtrade_dtredis_1 (8d6a73b9c594cfb8ae4556a038f2907681b916b9ec964459bc1c8728763ccd45): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:6379:tcp:172.18.0.2:6379: input/outpuStarting dyrtrade_dtddbb_1

  - Docker for Windows Version: 18.09.2, build 6247962

**Comment by mikeparker** [comment]
This looks like a problem with a specific container, not a bug with Docker Desktop. Please use the support forum https://forums.docker.com/c/docker-desktop-for-windows
