### ISSUE TITLE
PowerShell Silent install never ends

### ISSUE THREAD

**Issue by damienvanrobaeys** [docker/for-win#3923]
I'm trying to install silently Docker from PowerShell using Docker for Windows Installer.exe
I used the switches install --quiet
The installation is OK, but on the PowerShell prompt, it never ends, always on the step "Installation succeeded" meaning we can pass to something else after the commandline.

Someone else has this kind of issue, see below:
https://stackoverflow.com/questions/55825909/what-is-the-silent-install-command-for-docker-for-windows-10#new-answer

**Comment by stephen-turner** [comment]
Sorry, there is no silent install for Docker Desktop Community. Scripted install is a feature of the Enterprise version.

**Comment by damienvanrobaeys** [comment]
Oh ok that sucks !!!
