### ISSUE TITLE
Docker doesn't actually open port to expose daemon on Build 1903

### ISSUE THREAD

**Issue by Jacrys** [docker/for-win#3924]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:2165EB2E-805D-430A-A542-6E771CF624BA/20190516141428

### Expected behavior
docker responds over tcp://localhost:2375
### Actual behavior
error during connect: Get http://localhost:2375/v1.39/info: dial tcp [::1]:2375: connectex: No connection could be made because the target machine actively refused it.
There are no apps listening on 127.0.0.1:2375, 0.0.0.0:2375 or localhost:2375
### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible? Yes
  - Is the problem new? Yes as of upgrading to Windows Build 1903
  - Did the problem appear with an update? yes, Windows Build 1903
  - A reproducible case if this is a bug, 
  - Windows Version: Version 1903 Build 18362.113
  - Docker for Windows Version: 2.0.0.3 (31259) Build 8858db3

### Steps to reproduce the behavior
1. Install Docker Dektop, set up, and enable "Expose daemon on localhost:2375 without TLS"
2. set DOCKER_HOST in WSL, install docker-ce  and try to connect to docker 
3. cry miserably into your tea as you try turning off firewalls and all kinds of magic shenanigans

**Comment by Jacrys** [comment]
Restarting the Docker Desktop app for the 375th time jarred something loose and allowed this to work.  I wish I knew the cause.

**Comment by Jacrys** [comment]
As of an OS restart, we are back in a non-working state.  Restarting the windows service, and even shutting it down and having docker restart it provide no effect.

**Comment by Jacrys** [comment]
Uploaded a new diagnostic file, available at 2165EB2E-805D-430A-A542-6E771CF624BA/20190517075754

**Comment by StefanScherer** [comment]
I have a Windows 10 1903 (18362.113) and Docker Desktop Edge 2.0.4.1, exposed the port 2375 and it works, also after a reboot (after upgrade of latest Cumulative Updates).

Can you open a PowerShell terminal and check port 2375?

```
PS C:\> netstat -ano | sls 2375

  TCP    127.0.0.1:2375         0.0.0.0:0              LISTENING       2344
```

**Comment by Jacrys** [comment]
#3546 did not show up in my initial search(es) on this issue.  reserving the docker port seems to have resolved this issue.

**Comment by Jacrys** [comment]
@StefanScherer 
I did, there were not.  
> There are no apps listening on 127.0.0.1:2375, 0.0.0.0:2375 or localhost:2375
