### ISSUE TITLE
erorr

### ISSUE THREAD

**Issue by reksa26** [docker/for-win#3925]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1.Always difficult when making more than 1 container sometimes MySQL is not readable or   error. So I have to reinstall it again

**Comment by reksa26** [comment]
Please in fix it quickly especially for me that is still beginner's confusion to fix the problem

**Comment by mikeparker** [comment]
Please use the issue template and create a new issue with a description of what you were trying to do, what the problem is, diagnostics ID and repro instructions.
