### ISSUE TITLE
89DDC15E-2D9D-4927-9DA9-EDCDBF3A5308/20190517113653

### ISSUE THREAD

**Issue by almaPerezClip** [docker/for-win#3927]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mikeparker** [comment]
Please use the issue template and create a new issue with a description of what you were trying to do, what the problem is, diagnostics ID and repro instructions.
