### ISSUE TITLE
Docker not starting after update to 1.13.0-rc7-beta37 (9733)

### ISSUE THREAD

**Issue by random0000** [docker/for-win#393]
I have diligently been upgrading whenever there is an update available without having any issues.  This last time I was in Windows container mode when I applied the update.  I was also experimenting with node labels and service constraints.  Here is the crash report diagnostic id: D72C48A6-52BE-4CB7-9BB9-BE6F019495D2/2017-01-16_13-59-00.

I get that error on startup, however when I switch to Linux containers everything seems to work fine. Switch back and I get the same error.

Thanks for any help!

**Comment by simonferquel** [comment]
Diagnostics tell that some KBs are missing in your computer:
  [Fail] Missing KB3192366, KB3194496, or later installed
Can you try to update Windows (using Windows Updates) ?

**Comment by random0000** [comment]
That did the trick - thanks and will also keep that in mind going forward!
