### ISSUE TITLE
Running docker version on win10 powershell results in this

### ISSUE THREAD

**Issue by takowprogrammer** [docker/for-win#3932]
docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

**Comment by mikeparker** [comment]
Please use the issue template and create a new issue with a description of what you were trying to do, what the problem is, diagnostics ID and repro instructions.
