### ISSUE TITLE
Getting 403 error while saving files - Win 10 Enterprise 

### ISSUE THREAD

**Issue by dmukhop** [docker/for-win#3933]
I am unable to save any files in the containers. I am getting 403 permission denied. I have all  drives shared in the docker setting.

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
When I open a python notebook in the container using Jupyter lab openned via localhost:8889 I should be able to save the file.
### Actual behavior
I am unable to save the file.
### Information

  - Windows Version:10.0.17763
  - Docker for Windows Version:2.0.0.3 (31259)

### Steps to reproduce the behavior

  1. ...
[log.txt](https://github.com/docker/for-win/files/3196385/log.txt)

  2. ...

**Comment by mikeparker** [comment]
I can't see any errors in your log file. Can you elaborate on your reproduction instructions? Exactly which images you're running?

**Comment by dmukhop** [comment]
HI Mike,              I have found out the exact issue with Docker and I hope you can fix it. It is quite reproducible. In Windows 10 Enterprise edition, when you use Azure Active Directory joins and create a shared volume with the host, after a few days, the sharing disappears. It may be because of expired certificates. I tried many options but only way to fix it is to go to Docker setting, un-share drives, and then try building containers with shared volumes again. At this time, the Docker window for sharing permission and explicit domain login appears. When you do that, you can again see the shared volumes.
             Please let me know if you need more details. 
Regards,
- Deb
    On Thursday, May 30, 2019, 07:46:41 AM PDT, Mike Parker <notifications@github.com> wrote:  
 
 
I can't see any errors in your log file. Can you elaborate on your reproduction instructions? Exactly which images you're running?

**Comment by mikeparker** [comment]
Thanks for the extra info. So to be clear, the drive disappears in the Docker Desktop UI? 

It'd be good to see your log file after the sharing disappears, any chance you could do a diagnostic upload? I can't see any error from your original log file - the diagnostic tool will scrape all the log files.

I'll pass the info on and we'll see if we can reproduce, it's a shame the reproduction takes a few days. If you have a faster reproduction please let me know. Thanks!

**Comment by mikeparker** [comment]
@dmukhop could you upload a diagnostic please? We are trying to fix this and need more details.
