### ISSUE TITLE
docker login issue - changed the password and docker crashed

### ISSUE THREAD

**Issue by mark79github** [docker/for-win#3934]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mark79github** [comment]
I installed Docker for Windows on Windows 10 64 bit machine. When prompted for Hyper V settings, I restarted the machine and tried logging in to the docker login window. After specifying my docker ID and password, I couldn't login due to password mismatch. However, changing the password and logging in again lead to docker crashed.

**Comment by mikeparker** [comment]
Can you upload a diagnostic ID please otherwise I can't see the crash report.
