### ISSUE TITLE
Docker no longer auto starting when switch Stable -> Edge

### ISSUE THREAD

**Issue by nphmuller** [docker/for-win#3939]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `60B42B01-C664-4F95-B310-C5802E3DC567/20190521082034`

### Expected behavior
Docker for Desktop should automatically start when starting Windows.

### Actual behavior
I have to start Docker for Desktop manually when starting Windows.

### Information
  - Windows Version: 10 1903 (18362.116)
  - Docker for Windows Version: Edge 2.0.4.1 (34207)

### Steps to reproduce the behavior
  1. Install Docker for Desktop Stable (I tried 2.0.0.3)
  2. Make sure the option `Start Docker Desktop when you log in` is enabled.
  3. Auto starting should work.
  4. Switch to the Edge channel via `You can switch to another version`. (Edge version 2.0.4.1)
  5. Make sure the option from step 2 is still enabled.
  6. Auto starting doesn't work anymore.

**Comment by mat007** [comment]
Hi @nphmuller, does it work if you disable `Start Docker Desktop when you log in`, apply to save the settings then enable it back and apply again?

**Comment by nphmuller** [comment]
I don't think the new Docker Edge has an apply button. But I tried unchecking `Start Docker Desktop when you log in`, closing the window, reopening the window and checking it again, and rebooting. Still no dice.

**Comment by mat007** [comment]
Oh you're right, just toggling the check box should save the change.

Can you run `regedit` and check what you have in `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run`? You should see a `Docker Desktop` entry.
If you keep `regedit` open and toggle the `Start Docker Desktop when you log in` check box then hit F5 in `regedit` you should see the entry appearing and disappearing.

I checked this by installing Edge 2.0.5.0 on top of the latest Stable using the `switch to another version` link.

**Comment by nphmuller** [comment]
Weird, the registry key is there. If I close Desktop Desktop manually, and execute the path in the registry key, Docker Desktop starts, But when I restart my system, Docker Desktop doesn't start.

Maybe, and this is really just a guess that's not based on anything, Docker Desktop tries to start before the Docker Service has started, and can't start because of that.

**Comment by mat007** [comment]
Can you open the «Startup Apps» Windows settings pane and see if you have «Docker Desktop» listed there? If it's there, is it disabled?

**Comment by nphmuller** [comment]
You're a life saver! It was disabled... I don't remember disabling it at all, however... 
Shall I close this issue? Or is there a change it got disabled by installing the Edge channel?

**Comment by mat007** [comment]
I don't think installing Docker Desktop should have changed this as nowhere in the code do we touch the associated registry key (which for the record is `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\StartupApproved\Run`), but anyway I'm glad this solved your issue.
I'll open an internal ticket to have us check and change that other registry key as well so that it doesn't happen again!
Thanks!
