### ISSUE TITLE
docker container it's always running after docker service or Windows 10 pro restart

### ISSUE THREAD

**Issue by albertolo** [docker/for-win#3949]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [X ] I have uploaded Diagnostics
  - Diagnostics ID: 2C7BEC33-7DB2-49C4-AB14-35733B9430F6/20190521222120

### Expected behavior  
To be able to stop a container, to be able to restart a container or that all containers stop after docker service  is restarted.

### Actual behavior
I have several containers that I can't stop. They are running after a windows restart or windows services restart.  I can not run docker stop container or docker restart container the process just hangs. 

### Information
I have been using docker for around 2 or 3 years, and I never have a issue like this. 
First I had one container that I cannot restart or stop, then I create another one and after several days the same happened. 

 
  - Windows Version: Window 10 Pro
  - Docker for Windows Version: Docker version 19.03.0-beta3, build c55e026

**Comment by hulucc** [comment]
I can reproduce the same thing here.
Acutally after the restart, run:
```
hcsdiag list
```
You will found no container running there while `docker ps` indicate the container is running. 

And there will be 3 similar error in event log when you creating new container.
```
Error running exec beaf525e31aeabc82caebf5a99b5c2f4b6a670b310a96f8b5c64f06f9a94b8d7 in container: container ade5a5b92d04d27464f0f3c5808e2591c9095f2389b92712bb09042e53040c32 encountered an error during CreateProcess: failure in a Windows system call: Unspecified error (0x80004005)
[Event Detail: failed to run runc create/exec call for container ade5a5b92d04d27464f0f3c5808e2591c9095f2389b92712bb09042e53040c32: exit status 1 Stack Trace: 
github.com/Microsoft/opengcs/service/gcs/runtime/runc.(*container).startProcess
	/go/src/github.com/Microsoft/opengcs/service/gcs/runtime/runc/runc.go:576
github.com/Microsoft/opengcs/service/gcs/runtime/runc.(*container).runExecCommand
	/go/src/github.com/Microsoft/opengcs/service/gcs/runtime/runc/runc.go:516
github.com/Microsoft/opengcs/service/gcs/runtime/runc.(*container).ExecProcess
	/go/src/github.com/Microsoft/opengcs/service/gcs/runtime/runc/runc.go:136
github.com/Microsoft/opengcs/service/gcs/core/gcs.(*gcsCore).ExecProcess
	/go/src/github.com/Microsoft/opengcs/service/gcs/core/gcs/gcs.go:425
github.com/Microsoft/opengcs/service/gcs/bridge.(*Bridge).execProcess
	/go/src/github.com/Microsoft/opengcs/service/gcs/bridge/bridge.go:582
github.com/Microsoft/opengcs/service/gcs/bridge.(*Bridge).(github.com/Microsoft/opengcs/service/gcs/bridge.execProcess)-fm
	/go/src/github.com/Microsoft/opengcs/service/gcs/bridge/bridge.go:236
github.com/Microsoft/opengcs/service/gcs/bridge.HandlerFunc.ServeMsg
	/go/src/github.com/Microsoft/opengcs/service/gcs/bridge/bridge.go:68
github.com/Microsoft/opengcs/service/gcs/bridge.(*Mux).ServeMsg
	/go/src/github.com/Microsoft/opengcs/service/gcs/bridge/bridge.go:139
github.com/Microsoft/opengcs/service/gcs/bridge.(*Bridge).ListenAndServe.func2.1
	/go/src/github.com/Microsoft/opengcs/service/gcs/bridge/bridge.go:315
runtime.goexit
	/usr/lib/go/src/runtime/asm_amd64.s:2361 Provider: 00000000-0000-0000-0000-000000000000] extra info: {"CommandArgs":["cmd.exe","/C","ECHO 192.168.0.16    host.docker.internal \u003e\u003e %systemroot%\\system32\\drivers\\etc\\hosts \u0026 ECHO 192.168.0.16    gateway.docker.internal \u003e\u003e %systemroot%\\system32\\drivers\\etc\\hosts"],"WorkingDirectory":"/data","Environment":{"GOSU_VERSION":"1.10","HOSTNAME":"ade5a5b92d04","PATH":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","REDIS_DOWNLOAD_SHA":"1e1e18420a86cfb285933123b04a82e1ebda20bfb0a289472745a087587e93a7","REDIS_DOWNLOAD_URL":"http://download.redis.io/releases/redis-4.0.14.tar.gz","REDIS_VERSION":"4.0.14"},"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}
```

This is a edge channel(19.03.0-beta3) speficied error, everything is fine with stable channel(18.09.02).
Also I tried with nightly build, but no luck.

**Comment by hulucc** [comment]
For someone want to remove the suspended container or as a workaround:
1. Delete correspond container folder in `C:\ProgramData\Docker\containers`
2. Settings -> Reset -> Restart Docker Desktop

**Comment by mikeparker** [comment]
This sounds like a real bug, is there any way you can help with decent reproduction instructions? Can you elaborate which container(s) you were running, anything in particular you did to cause the error state?

**Comment by hulucc** [comment]
I can't find anything special I did in my mind. Also I can reproduce on my colleague's surface with any container. 

Environment:
  - Dell XPS 13 9360
  - Windows Pro 1903 (or 1809) Chinese
  - Diagnostic ID: 669CBA43-76BC-4F1B-B468-45625EC820CE/20190531070759

Step:
  - Install Docker Desktop edge channel 2.0.4.1 using windows container
    - 2.0.4.1 not works
    - 2.0.4.0 not works
    - 2.0.3.0 works
    - 2.0.2.1 works
  - `docker login`
  - `docker run --name redis --restart always -d redis` && `docker ps`
    ```
    NAMES               CONTAINER ID        IMAGE               STATUS              PORTS
    redis               90b664223956        redis               Up 46 seconds       6379/tcp
    ```
  - check windows event log, docker emit 3 errors while creating
    - https://gist.github.com/hulucc/fdaa646349357ef7d794e47b46068d24
  - `hcsdiag list`
    ```
    90b664223956b02fa5ac57796722977110fca0ee32bf5a40755c8d76cda491ec
        Hyper-V Linux Container,    Running, 5BB4824E-5CEC-48DA-A139-EA3409B17A5E, docker
    ```
  - Docker Desktop tray -> Settings -> Reset -> Restart Docker Desktop
  - `docker ps`

    ```
    NAMES               CONTAINER ID        IMAGE               STATUS              PORTS
    redis               90b664223956        redis               Up 8 minutes        6379/tcp
    ```
  - `hcsdiag list`

    ```
    (nothing)
    ```
  - `docker kill redis`

    ```
    (hang forever)
    ```

**Comment by albertolo** [comment]
Hi,  in my case I just run microsoft sql server in different versions.   When I created the container I attached one database, the container has access to my c:\database\ folder.
