### ISSUE TITLE
0D34F17A-E12C-46AD-946F-ED6A3F0D59EF/20190522130236

### ISSUE THREAD

**Issue by omcjunior** [docker/for-win#3954]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mikeparker** [comment]
Please use the issue template and create a new issue with a description of what you were trying to do, what the problem is, diagnostics ID and repro instructions.
