### ISSUE TITLE
docker build hangs

### ISSUE THREAD

**Issue by caoyangjiang** [docker/for-win#3957]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F28664E1-3953-4290-AB1B-ED1CB1B85595/20190522174753

### Expected behavior
When running "docker build -t windows_ci ." for the Dockerfile below,  progress finishes as expected.
 
FROM caoyangjiang5/windows_ci:latest
RUN C:\vcpkg\vcpkg.exe install x264
 

### Actual behavior
progress hangs after running "C:\vcpkg\vcpkg.exe install x264" and build never finishes.

### Information

  - Windows Version: 1809 (OS BUILD 17763.503)
  - Docker for Windows Version: 2.0.0.3 (31259)

### Steps to reproduce the behavior

  1. Create a Dockerfile with following content
FROM caoyangjiang5/windows_ci:latest
RUN C:\vcpkg\vcpkg.exe install x264
  2. Run "docker build -t windows_ci ."
  3. This build should finish within 10 minutes.

**Comment by mikeparker** [comment]
This sounds like a problem with an individual container / image, what you're trying to run rather than a core docker desktop problem. Have you inspected the container logs?

Also see https://forums.docker.com/c/docker-desktop-for-windows for support forums

**Comment by caoyangjiang** [comment]
If I run command "C:\vcpkg\vcpkg.exe install x264" within an instance created from "caoyangjiang5/windows_ci:latest", it works and does not hang.  caoyangjiang5/windows_ci:latest is a image created from windows server core. I haven't inspect the container logs because I did not know how to do that. I will do some googling online.
