### ISSUE TITLE
ASP.NET Core 2.2 template - Build Docker Image fails

### ISSUE THREAD

**Issue by obamor** [docker/for-win#3960]
- [x] I have tried with the latest version of my channel (Stable or Edge) => 1709
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 17D91A6B-8733-407F-BF1C-D12D0AE46E94/20190523140805

### Expected behavior
- Build Solution succeded 
- Build Docker Imaged succeded
- Run ASP.NET core WebAPI default template with docker support (VS2017)

### Actual behavior
- Build Solution succeded 
- Build Docker Image fails

### Information

- new Docker installation 
- Proxy is set in confg.json and as Enviroment variable
- The following line of the docker log is interesting:
`[13:50:30.432][WindowsDaemon  ][Error  ] Login failed for user 'CORPORATE\<PCName>$'. Reason: Could not find a login matching the name provided. [CLIENT: <local machine>]`

As you can see he try to login with the PCName (replaced with Placeholder) 
I would expect something like COROPRATE/username

  - Windows Version: W10 Enterprise 1709
  - Docker for Windows Version:
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false
Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:28:48 2019
  OS/Arch:          windows/amd64
  Experimental:     false

### VS-Build-Output:
1>------ Build started: Project: DockerTest, Configuration: Debug Any CPU ------
1>DockerTest -> C:\Users\hubermax\source\repos\DockerTest\DockerTest\bin\Debug\netcoreapp2.2\DockerTest.dll
1>docker build -f "C:\Users\hubermax\source\repos\DockerTest\DockerTest\Dockerfile" -t dockertest:dev --target base  --label "com.microsoft.created-by=visual-studio" "C:\Users\hubermax\source\repos\DockerTest"
1>Sending build context to Docker daemon  22.02kB
1>
1>Step 1/4 : FROM microsoft/dotnet:2.2-aspnetcore-runtime-nanoserver-1709 AS base
1>2.2-aspnetcore-runtime-nanoserver-1709: Pulling from microsoft/dotnet
1>4c460812ddfa: Pulling fs layer
1>5ffb15f2e928: Pulling fs layer
1>4c460812ddfa: Waiting
1>9ef95ce817ec: Pulling fs layer
1>407ada6e90de: Pulling fs layer
1>9ed960db348d: Pulling fs layer
1>b1c56b678c06: Pulling fs layer
1>5ffb15f2e928: Waiting
1>f5febc958fa5: Waiting
1>f5febc958fa5: Pulling fs layer
1>9ed960db348d: Waiting
1>9ef95ce817ec: Retrying in 5 seconds
1>407ada6e90de: Retrying in 5 seconds
1>9ef95ce817ec: Retrying in 4 seconds
1>407ada6e90de: Retrying in 4 seconds
1>9ef95ce817ec: Retrying in 3 seconds
1>407ada6e90de: Retrying in 3 seconds
1>9ef95ce817ec: Retrying in 2 seconds
1>407ada6e90de: Retrying in 2 seconds
... 
1>407ada6e90de: Retrying in 2 seconds
1>9ef95ce817ec: Retrying in 2 seconds
1>407ada6e90de: Retrying in 1 second
1>9ef95ce817ec: Retrying in 1 second
1>authenticationrequired
1>C:\Users\hubermax\.nuget\packages\microsoft.visualstudio.azure.containers.tools.targets\1.4.10\build\Container.targets(258,5): error CTP1001: An error occurred while attempting to build Docker image.
1>Done building project "DockerTest.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

### Dockerfile:
FROM microsoft/dotnet:2.2-aspnetcore-runtime-nanoserver-1709 AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.2-sdk-nanoserver-1709 AS build
WORKDIR /src
COPY ["DockerTest/DockerTest.csproj", "DockerTest/"]
RUN dotnet restore "DockerTest/DockerTest.csproj"
COPY . .
WORKDIR "/src/DockerTest"
RUN dotnet build "DockerTest.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "DockerTest.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "DockerTest.dll"]

`

### Steps to reproduce the behavior
1. Create ASP.NET core WebAPI template with docker support
2. Start with "Docker"-PlayButton

**Comment by erjaintarun** [comment]
Any solution to this issue, I am also facing this error
