### ISSUE TITLE
Docker crash on Windows10

### ISSUE THREAD

**Issue by pramchan** [docker/for-win#3961]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by pramchan** [comment]
Docker on Windows 10 fails to start using latest version. It never worked to date on my Notebook.

**Comment by mikeparker** [comment]
Please use the issue template and create a new issue with a description of what you were trying to do, what the problem is, diagnostics ID and repro instructions.
