### ISSUE TITLE
Docker Error

### ISSUE THREAD

**Issue by peterennis** [docker/for-win#3965]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
**2A49494F-B446-41C3-993E-3E6DF6667C88/20190523100534**

I assume this is the most current stable version.
There is no obvious indication on the site related to the
version number when clicking on the download button.

### Expected behavior
No error

### Actual behavior
Error

### Information

  - Windows Version:
**Windows 10, 1809 Enterprise**
  - Docker for Windows Version:
**2.0.0.3**

### Steps to reproduce the behavior

  1. Sign-out from domain account
  2. Sign-in and error appeared

Crash report submitted with this ID: 2A49494F-B446-41C3-993E-3E6DF6667C88/20190523100534

All log files:

[Logs Docker Error.zip](https://github.com/docker/for-win/files/3213409/Logs.Docker.Error.zip)

![Capture271](https://user-images.githubusercontent.com/140737/58273197-0add4700-7d45-11e9-9b4a-b5d6014c2eea.png)

![Capture272](https://user-images.githubusercontent.com/140737/58273214-13ce1880-7d45-11e9-92b4-f83358bb5f61.png)

![Capture273](https://user-images.githubusercontent.com/140737/58273439-9525ab00-7d45-11e9-8de1-06241454a579.png)

![Capture274](https://user-images.githubusercontent.com/140737/58273533-c2725900-7d45-11e9-8000-ca09964fd27d.png)

**Comment by peterennis** [comment]
Shutdown restart:

![Capture275](https://user-images.githubusercontent.com/140737/58274105-fef28480-7d46-11e9-82a7-3e10a60c4084.png)

**Comment by mikeparker** [comment]
Looking at your logs and your description, my best guess is disconnecting your domain account means you no longer have access to the named pipes which allow docker processes to communicate.

Can you elaborate on exactly what you mean by 'log out of domain account' and logging back in? Do you mean log off/on your machine?

**Comment by peterennis** [comment]
Log out of domain account = log off/on my machine

**NOTE:** Our PCs get auto booted each night.
I do not recall if Docker was running at that time, but it would make sense
there were no processes running if it did not restart correctly.

**Comment by mikeparker** [comment]
So just to be super clear: you get this message when you log off and on whilst docker is running? Or when you restart the whole machine e.g. overnight?

**Comment by peterennis** [comment]
@mikeparker 
Docker is running and the machine is auto rebooted at night
Logon to domain, do some work
Logoff from domain account
Logon and error appeared

I do not recall if the Windows or Linux container was running
