### ISSUE TITLE
Docker does not respect the "mtu" setting in deamon.json on Windows Server 2019

### ISSUE THREAD

**Issue by ChrML** [docker/for-win#3972]
### Issue description
Docker for Windows does not seem to respect the "mtu" setting in daemon.json.

It always stays at the default 1500 instead of respecting the config value. The documentation is here:
https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/configure-docker-daemon

Cloud systems such as OpenStack has a maximum outgoing MTU size of 1450 instead of the default 1500. There every IP packet between 1451-1500 seem to be dropped between the container and the host os.

This issue causes standard images such as mcr.microsoft.com/dotnet/framework/sdk to fail to download files from the internet using for example "nuget restore" because of connection timeout, because packets are dropped. If you change the MTU to 1450 within the container, then "nuget restore" will work.

I think this issue should be pretty high priority because the consequence is that docker images in Windows are not really host configuration independant anymore. To run network applications within environments such as OpenStack is not possible without changing the docker-compose or run a command inside the image to change the MTU to 1450. This can be quite a hassle to manage, and troubleshoot.

### Expected behavior
  MTU size of 1450 inside the docker image.

### Actual behavior
  MTU size of 1500 inside the docker image.

### Information
  - Windows Server 2019 version 1809
  - Docker for Windows Version: 18.09.2-ce, Sun Feb 10 04:28:48 2019, windows/amd64

### Steps to reproduce the behavior
  1. Add the following configuration to C:\ProgramData\Docker\config\daemon.json:
    `"mtu": 1450`
  2. Ensure that Docker is switched to Windows Containers
  3. Restart the computer
  4. Start the windows/servercore image with the following command in PowerShell:
      `docker run -it mcr.microsoft.com/windows/servercore:ltsc2019 powershell`
  5. Run the following command to inside the docker image to view ethernet interfaces:
      `netsh interface ipv4 show subinterfaces`
  6. Observe that the ipv4 interfaces inside the docker image still has an mtu of 1500:
      ` MTU  MediaSenseState   Bytes In  Bytes Out  Interface`
      ` ------  ---------------  ---------  ---------  -------------`
      ` 4294967295                1          0          0  Loopback Pseudo-Interface 2`
      `   1500                1     121796     231275  Ethernet`

**Comment by stephen-turner** [comment]
Thank you for the detailed analysis, but could you please file it in https://github.com/moby/moby? This issue tracker is for Docker Desktop. (And having re-read the submission guidelines, I realise that's not very clear, so we will improve that). Thank you.
