### ISSUE TITLE
CD67F1FE-903C-4FDB-B418-E7FA265B2774/20190524104514

### ISSUE THREAD

**Issue by timscherr88** [docker/for-win#3973]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID:CD67F1FE-903C-4FDB-B418-E7FA265B2774/20190524104514

### Actual behavior
Doesn't start Docker Desktop
### Information

  - Windows Version:
  - Docker for Windows Version:  

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mikeparker** [comment]
Please use the issue template and create a new issue with a description of what you were trying to do, what the problem is, diagnostics and repro instructions.
