### ISSUE TITLE
docker.exe: failed to register layer: re-exec error: exit status 1

### ISSUE THREAD

**Issue by lutherpaul** [docker/for-win#3974]
Hi,
I get the error below when I run Hello-World. It worked when I installed about 8 months ago and I have not touched since. What could be the reason and what are the steps to fix? I tried to re-install docker on the same place without uninstalling, but the same error comes up. I really want to fix the issue rather than reinstall. My docker Version: 17.06.2-ee-16
Can someone please help?

-------------------
------------------
PS C:\WINDOWS\system32> docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
e46172273a4e: Extracting [==================================================>]  92.82MB/92.82MB
3d65648a54d8: Download complete
aee656205468: Download complete
9475349f525f: Download complete
C:\Program Files\Docker\docker.exe: failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage \\?\D:\Docker\windowsfilter\84623f9b014aa123b4f9bcda0e08630641522be87f1072a54df2845b0b8722e3\UtilityVM: The system
cannot find the path specified.
See 'C:\Program Files\Docker\docker.exe run --help'.
PS C:\WINDOWS\system32>
-------------------
------------------
PS C:\WINDOWS\system32> docker version
Client:
 Version:      17.06.2-ee-16
 API version:  1.30
 Go version:   go1.8.7
 Git commit:   9ef4f0a
 Built:        Thu Jul 26 16:43:19 2018
 OS/Arch:      windows/amd64

Server:
 Engine:
  Version:      17.06.2-ee-16
  API version:  1.30 (minimum version 1.24)
  Go version:   go1.8.7
  Git commit:   9ef4f0a
  Built:        Thu Jul 26 16:52:17 2018
  OS/Arch:      windows/amd64
  Experimental: false
PS C:\WINDOWS\system32>
-------------------
------------------

Thanks,
Paul.

**Comment by mikeparker** [comment]
It looks like you're running a very old version of docker desktop. As the issue template says, please try with the latest version. Then please open a ticket using the issue template with a description of how to reproduce the issue.

If the container is your own and want guidance on how to fix your own containers please try the support forum at https://forums.docker.com/c/docker-desktop-for-windows
