### ISSUE TITLE
289C0C9E-C505-4464-9B5C-DCA3B3FCFB50/20190525125752

### ISSUE THREAD

**Issue by Constantin017** [docker/for-win#3978]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 289C0C9E-C505-4464-9B5C-DCA3B3FCFB50/20190525125752

### Information

  - Windows Version: 1803 // Windows 10 PRO
  - Docker for Windows Version: 2.0.0.3 (31259) stable, build: 8858db3

### Steps to reproduce the behavior

  1. Turn on computer.
  2. Login to my windows account.

**Comment by mikeparker** [comment]
Please use the issue template and create a new issue with a description of what you were trying to do, what the problem is, diagnostics and repro instructions.
