### ISSUE TITLE
"Newby " I lose connection with Connection error: HTTPConnectionPool(host='spark1.webodm.net', port=80): Max retries exceeded with url: /task/new/init?token=c1f38f28-b3eb-4b69-82e5-46e6c189d04a (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f26037ca978>, 'Connection to spark1.webodm.net timed out. (connect timeout=30)')) 

### ISSUE THREAD

**Issue by pasllc2625** [docker/for-win#3979]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mikeparker** [comment]
Please use the issue template and create a new issue with a description of what you were trying to do, what the problem is, diagnostics and repro instructions.
