### ISSUE TITLE
Dockers for windows update

### ISSUE THREAD

**Issue by mashrafk2002** [docker/for-win#3981]
Docker show "A new version of Docker is available", when try to install it then update fails.

![DockerUpdateIssue](https://user-images.githubusercontent.com/43500478/58374338-6f95ce80-7f0a-11e9-915d-cfc33657dcfe.png)

**Comment by mikeparker** [comment]
Are you logged in?

**Comment by mashrafk2002** [comment]
No, I was not logged in but I am getting the exact same error even after logged in to docker.

**Comment by mikeparker** [comment]
Could you upload your installer log file?
