### ISSUE TITLE
NOT BEHIND A PROXY but still get "request canceled while waiting for connection"

### ISSUE THREAD

**Issue by gilesejb** [docker/for-win#3982]
- [X] I have tried with the latest version of my channel (Stable)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: AAB06192-0EDE-438E-B8E6-0BC04A579126/20190526040001

### Expected behavior
- able to connect to docker hub and pull images and push images to own repositories

### Actual behavior
- can't connect at all, even to log in

### Information
- the result of any docker command is:

> Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

  - Windows Version: Windows 10 Pro, Version 1809, Build 17763.503
  - Docker for Windows Version: 2.0.0.3 (31259), Build 8858db3

It seems like any thread related to this issue becomes polluted and confused by people posting about how to fix proxy settings. I want to be very clear that I am connecting to the net DIRECTLY, not using a proxy of any kind, and not from behind a corporate firewall.

NO PROXY!!!!

### Steps to reproduce the behavior

  1. open a command prompt
  2. enter any docker command

**Comment by mikeparker** [comment]
Can you log in inside Docker Desktop and list your images there?
Can you access https://registry-1.docker.io/v2/ from a browser on the same machine? (You should get an unauthorized json payload)

**Comment by gilesejb** [comment]
- from Docker Desktop, I can log in, and select Repositories to see a list of my repositories, and on selecting View All, I'm taken to Docker Hub, logged in, where I can see my repositories

- if I try to access https://registry-1.docker.io/v2/ from a browser I get 

>  This site can’t be reached registry-1.docker.io took too long to respond.

- I last installed a Windows update on 2019-05-20

- there are two updates currently waiting to install

**Comment by mikeparker** [comment]
If you can't access that website from a browser, unfortunately I suspect the issue is not with docker desktop and instead with something related to your connection and your DNS.

**Comment by mikeparker** [comment]
Can you do the following from powershell please
`Resolve-DnsName -Name registry-1.docker.io`
If you get IP addresses back can you see if you can ping them?

A possible cause may be your hosts file.

**Comment by gilesejb** [comment]
> PS C:\Users\giles> Resolve-DnsName -Name registry-1.docker.io

> Name                                          Type     TTL         Section        IPAddress

> - - - -                                           - - - -   - - -         - - - - - - -    - - - - - - - - -

> registry-1.docker.io                      A        599399    Answer        34.200.28.105

Less luck with ping:

> PS C:\Users\giles> ping 34.200.28.105

> Pinging 34.200.28.105 with 32 bytes of data:

> Request timed out.

**Comment by gilesejb** [comment]
One piece of information that might help is: I'm able to use Docker, the main registry, and private registries just fine when I'm inside my corporate network with the proxy configured.

But as soon as I come outside the corporate firewall and turn off proxying, I get the error...

**Comment by mikeparker** [comment]
I don't recognise that IP address, you can do a DNS lookup online and see the real results (although AWS may give you different IPs depending on where you live). https://mxtoolbox.com/SuperTool.aspx?action=a%3aregistry-1.docker.io&run=toolpage

The TTL is also suspicious.

The fact that it works inside your corporate network / proxy suggests you have some local network settings interfering with the networking but I can't diagnose exactly what. 
I'd suggest following some advice from people here:
https://github.com/docker/for-win/issues/611

Including:
* Changing your DNS settings from fixed -> automatic or automatic -> Fixed (8.8.8.8)
* Restarting docker
