### ISSUE TITLE
Kubernetes non localhost access refused

### ISSUE THREAD

**Issue by magicmoose** [docker/for-win#3989]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: A4E1FAD1-C265-4760-ACE8-C7D4DDB7BB2E/20190527134542

### Expected behavior
Kubectl commands should work
### Actual behavior
Connection gets refused
### Information
  - Windows Version: Windows 10 Enterprise : 1709
  - Docker for Windows Version: 2.0.4.1 2019-05-07

When working with kubernetes on edge. 
Replacing the server: https://localhost:6445 with a actual ip e.g. server: https://10.128.27.32:6445
leads to the connection to the cluster being refused. 

with the message :
The connection to the server 10.128.27.32:6445 was refused - did you specify the right host or port?
This is working fine in the current stable release.

**Comment by WeetA34** [comment]
Same issue for me with 2.0.5.0.
Kubernetes api server is listening on 127.0.0.1:6445 instead of 0.0.0.0:6445 for the stable version 2.0.3.0.
Is it configurable? if yes, where :)

**Comment by WeetA34** [comment]
As a workaround, i added a port forward on my workstation

`C:\>netsh interface portproxy add v4tov4 listenaddress=0.0.0.0 listenport=6445 connectaddress=127.0.0.1 connectport=6445 protocol=TCP
C:\>netsh interface portproxy show all

Listen on ipv4:             Connect to ipv4:

Address         Port        Address         Port
--------------- ----------  --------------- ----------
0.0.0.0         6445        127.0.0.1       6445`

**Comment by WeetA34** [comment]
You have to delete the port proxy before restarting Docker for Desktop else Kubernetes will stay in starting state
```C:\>netsh interface portproxy delete v4tov4 listenport=6445 listenaddress=0.0.0.0 protocol=tcp```

**Comment by WeetA34** [comment]
Hi
Docker 2.1.0.0 kubernetes API listens now on 127.0.0.1:6443 so you can use the following port proxy without having to delete it before restarting docker:
`C:\>netsh interface portproxy add v4tov4 listenaddress=0.0.0.0 listenport=6445 connectaddress=127.0.0.1 connectport=6443 protocol=tcp`

**Comment by WeetA34** [comment]
Hello
Any news? no way to configure it?
