### ISSUE TITLE
Unable to run Docker on Windows 10 Pro

### ISSUE THREAD

**Issue by ExiaSR** [docker/for-win#399]
### Expected behavior
Make it run
### Actual behavior
Ask me to enable Hardware assisted virtualization and data execution protection must be enabled in the BIOS. 
### Information
  * Diagnostic ID: E53C-43B5-8BDF-7D607FD61B52/2017-01-18_15-31-48
  * OS: WIndows 10 Pro
  * Docker Version: 1.13.0-rc7-beta37 (9733)

### Steps to reproduce the behavior
Follow the installation guide.

### Note 
  * I already verify that Virtualization is enabled on task manager. 
  * My bios only has VT-d option, and it's already enabled.

**Comment by simonferquel** [comment]
From the diagnostics file, it seems that you are running VMWare, and that is why Hyper-V can't kick off (only one hypervisor can run on a single machine).

Please uninstall VMWare and try if it works better.

**Comment by ExiaSR** [comment]
@simonferquel 
Hi Simon.  Thanks for the reply,

I tried to uninstall the VMWare, but it is still not working.

* Diagnostic ID: F702C5DB-E53C-43B5-8BDF-7D607FD61B52/2017-01-19_18-23-17

**Comment by simonferquel** [comment]
It seems that VMWare uninstallation did not reset the bootloader setting to a working Hyper-V environment. Can you try to launch `BCDEDIT /Set {current} hypervisorlaunchtype auto` in an elevated command prompt and restart your machine ?

**Comment by ExiaSR** [comment]
Thanks, it works now.
