### ISSUE TITLE
164611C1-F4F1-476B-97C9-429F6ADBB605/20190528111442

### ISSUE THREAD

**Issue by Shaif1604** [docker/for-win#3992]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Shaif1604** [comment]
[diagnostics.log](https://github.com/docker/for-win/files/3225948/diagnostics.log)

**Comment by mikeparker** [comment]
Please use the issue template and create a new issue with diagnostics and repro instructions.
