### ISSUE TITLE
Windows containers have no internet access, but Linux containers do - with VPN-Client active on host

### ISSUE THREAD

**Issue by moritzrinow** [docker/for-win#3995]
I have a Stonesoft VPN-Client and Docker-for-Windows installed on my host machine. My Windows containers seem to fail to resolve any host (even www.google.com). My Linux containers however work perfectly fine. When I disable the VPN Adapter in my network adapter list, the windows containers can access the internet again. But I need them to work with VPN active.

I have provided further details here:
https://stackoverflow.com/questions/56341873/windows-containers-have-no-internet-access-but-linux-containers-do-with-vpn-c

**Comment by mikeparker** [comment]
Unfortunately this is a problem between the windows host networking service and the VPN client, this isn't a docker bug. If I was to guess I'd say it's more likely to be the VPN client so i'd start there. Can you use a different client, alternatively try Stonesoft support.
