### ISSUE TITLE
no images and containers after update to  1.12.0-beta21 (build 5971)

### ISSUE THREAD

**Issue by staeppvargen** [docker/for-win#4]
### Expected behavior
After docker-update I expect that all images and container are still there. 

### Actual behavior
After docker-update all my docker-containers and images seem to be gone ("docker ps -a" and "docker images" show nothing).

### Information
- A20E5259-982A-4F12-B301-CD5CE7FFCE26/2016-07-29_14-06-39
- I updated to version  1.12.0-beta21 (build 5971)
- There was the question if I wanted to copy the images and container from a previously installed docker named "default". This question I answered with yes

Windows-Info:
Betriebsystemname	Microsoft Windows 10 Pro
Version	10.0.14393 Build 14393
Systemtyp	x64-basierter PC
Prozessor	Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz, 4001 MHz, 4 Kern(e), 8 logische(r) Prozessor(en)
BIOS-Version/-Datum	American Megatrends Inc. P1.70, 16.09.2014
SMBIOS-Version	2.8
Version des eingebetteten Controllers	255.255
Hauptplatinenhersteller	ASRock
Hardwareabstraktionsebene	Version = "10.0.14393.0"
Benutzername	IBEOS01\ingo

**Comment by rneugeba** [comment]
Thanks for the report and apologies that you lost the images and containers. Normally, the installer does not overwrite existing containers/images, but it seems that the installer detected an Docker Toolbox image somewhere and offered to migrate that. We are considering to disable the Toolbox migration when updating from one Docker for Windows version to a newer one.

**Comment by staeppvargen** [comment]
Fortunately I was just about to get started with "Docker for Windows", so there was no harm. 
I remember that I got the same question already before. Can you tell me on Win10, **where exactly this "default"-docker from toolbox is installed** or in which way "Docker for Windows" detects it? I'd like to get rid of the old stuff completely since I realized that lots of errors are coming from these "old relicts" hidden deep in the system.

**Comment by rneugeba** [comment]
By default it looks in `~\.docker\machines\machine\default\disk.vmdk`

**Comment by staeppvargen** [comment]
hm... nothing there and anywhere else to find. I'll pass that "find toolbox-residues" issue to the esoterism-department :)

**Comment by ebriney** [comment]
You just have to delete `~\.docker` to get rid of old toolbox VMs
