### ISSUE TITLE
Network timed out when trying to connect to dockerhub.io

### ISSUE THREAD

**Issue by samuelkdavis** [docker/for-win#40]
Execute run hello-world in a 'docker for windows' environment.
### Expected behavior
Unable to find the image locally, so downloads from dockerhub
### Actual behavior
Network times out consistently

docker run hello-world
Unable to find image 'hello-world:latest' locally
Pulling repository docker.io/library/hello-world
docker: Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/hello-world/images. You may want to check your internet connection or if you are behind a proxy..
See 'docker run --help'.

Attached logs

[logs.txt](https://github.com/docker/for-win/files/421978/logs.txt)

### Information
Looks like a proxy/dns issue, but the logs don't make much sense to me.
Docker for windows 1.12.0-stable build 5968

### Steps to reproduce the behavior

  1. run hello-world
  2. cry

**Comment by samuelkdavis** [comment]
Attached logs

[logs.txt](https://github.com/docker/for-win/files/421978/logs.txt)

**Comment by samuelkdavis** [comment]
I tried this 3 times earlier, but it seems the 4th time + some unknown fiddling seems to have made it work. Changing the DNS to 8.8.8.8 did nothing for me earlier, but is working now.

![image](https://cloud.githubusercontent.com/assets/6887841/17729576/f1854804-64b8-11e6-8fde-9d9772517666.png)

Earlier I tried setting the network to internal and sharing the internet connection, but in it's current working state that is now switched off.

![image](https://cloud.githubusercontent.com/assets/6887841/17729611/21ae5e76-64b9-11e6-9569-84dd47142b2c.png)

![image](https://cloud.githubusercontent.com/assets/6887841/17729649/504497f0-64b9-11e6-8284-87f3213dede5.png)

I'm sure I was in this exact same state earlier with the outgoing internet access being blocked, but it is working now. I hope these screenshots give some direction to those going through the same issue.

**Comment by rneugeba** [comment]
Hi @samuelkdavis thanks for the report and glad it is now working for you. From the logs, it's clear that the issue was related to DNS but it's hard to tell exactly what based on the logs alone. I'm closing this issue for now, but if it happens again, please re-open. Also, if it happens again, it would be great if you could got to `Diagnose & Feedback` and `Upload a diagnostic...` as this would provide us with additional information.

Thanks
Rolf
