### ISSUE TITLE
Error after installing docker for windows 

### ISSUE THREAD

**Issue by arunprasathv** [docker/for-win#4000]
Trying to Install Grafana Image but receiving this error,

docker: error during connect: Post 

http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/containers/create?name=grafana: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
See 'docker run --help'.

**Comment by mikeparker** [comment]
Please use the issue template and create a new issue with diagnostics and repro instructions.
