### ISSUE TITLE
docker crash

### ISSUE THREAD

**Issue by saytac** [docker/for-win#4002]
"
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411
   konum: Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs içinde: satır 255
   konum: Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions) C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs içinde: satır 189
   konum: Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs içinde: satır 48
   konum: Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) C:\workspaces\stable
"
4

**Comment by mikeparker** [comment]
There are multiple duplicate tickets already open , please use the following search

https://github.com/docker/for-win/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Hyper-V+was+unable+to+find+a+virtual+switch+with+name+%22DockerNAT
