### ISSUE TITLE
LCOW on Edge is not working

### ISSUE THREAD

**Issue by jrob** [docker/for-win#4004]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 40A1803B-0A11-4357-B8BD-916B20E6DECE/20190529193336

### Expected behavior

I can pull and run docker containers in windows using LCOW.

### Actual behavior

I am unable to pull or run LCOW containers.

```
$ docker pull --platform linux alpine
Using default tag: latest
Error response from daemon: unsupported os linux
```

```
$ docker run --platform=linux --rm -it busybox
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: operating system on which parent image was created is not Windows.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
```

### Information

  - LCOW works fine in docker desktop 2.0.3.0.
  - LCOW stopped working when I upgraded to 2.0.4.0 This is when Docker 19.03.0-beta3 was added.
  - Windows Version: Windows 10 1803 (OS Build 17134.799)
  - Docker for Windows Version: Edge 2.0.4.1 (34207)

```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.0-beta3
 API version:       1.40
 Go version:        go1.12.4
 Git commit:        c55e026
 Built:             Thu Apr 25 19:05:10 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.0-beta3
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.4
  Git commit:       c55e026
  Built:            Thu Apr 25 19:06:34 2019
  OS/Arch:          windows/amd64
  Experimental:     true
```

```
$ docker info
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0-beta1)
  buildx: Build with BuildKit (Docker Inc., v0.2.0-tp)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 10
 Server Version: 19.03.0-beta3
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics l2bridge l2tunnel nat null overlay transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
 Operating System: Windows 10 Enterprise Version 1803 (OS Build 17134.799)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 63.88GiB
 Name: KNL060VC
 ID: 0279cba6-d32a-453f-810b-12b66ce707bd
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 29
  System Time: 2019-05-29T15:38:01.2569294-04:00
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by mikeparker** [comment]
This works fine for me. Have you enabled the experimental flag in daemon settings?

**Comment by mikeparker** [comment]
Checking windows versions. FWIW in future LCOW will require RS5+ windows version: https://github.com/moby/moby/issues/33850#issuecomment-478192332

**Comment by mikeparker** [comment]
Got confirmation: latest LCOW support requires windows 19.03, you'll need to update windows.

**Comment by Aj821990** [comment]
I see my windows version is 19.03.1 and kernal version is 10.0 17134 but still facing the same issue. Can you please check what can be the issue at my end?

$ docker version
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:17:08 2019
 OS/Arch:           windows/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:25:07 2019
  OS/Arch:          windows/amd64
  Experimental:     true


$ docker info
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., v0.2.2-10-g3f18b65-tp-docker)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 19.03.1
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics l2bridge l2tunnel nat null overlay transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
 Operating System: Windows 10 Enterprise N Version 1803 (OS Build 17134.950)
 OSType: windows
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.43GiB
 Name: DESKTOP-HKE2U56
 ID: QQIO:MO7R:M3FA:XKJV:PZNI:U2X2:MPPJ:QHVC:2DBR:DAT5:ICHL:NWE2
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 27
  System Time: 2019-08-23T16:58:22.284214+02:00
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

**Comment by SebastienHo** [comment]
I faced the same problem and reverted to docker version 18..09.1 then it works : 

PS C:\Program Files\Docker> docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.09.1
Storage Driver: lcow (linux) windowsfilter (windows)
 LCOW:
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows Server Datacenter Version 1803 (OS Build 17134.1)
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 8GiB
Name: devopsagent3
ID: XATE:MJRD:DHPV:ROOA:O77G:NWW7:S3EQ:O5DK:TMTV:7HZU:RPAY:LY36
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
