### ISSUE TITLE
getting crashed

### ISSUE THREAD

**Issue by Nikhilrize** [docker/for-win#4006]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mikeparker** [comment]
Please use the issue template and create a new issue with description, diagnostics and repro instructions.
