### ISSUE TITLE
Applications are not able to access outside after few days 

### ISSUE THREAD

**Issue by chennakesava1** [docker/for-win#4007]
- [* ] I have tried with the latest version of my channel (Stable or Edge)
  - [*] I have uploaded Diagnostics
  - Diagnostics ID: C2A7D829-2462-425D-9582-F725CBEA3B34/20190530143313

### Expected behavior
Applications are not able to access  
### Actual behavior
when i installed it's running fine but after few days we are not able to access 
### Information

  - Windows Version:
OS Name:                   Microsoft Windows Server 2016 Standard
OS Version:                10.0.14393 N/A Build 14393
  - Docker for Windows Version:
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mikeparker** [comment]
Can you give a reproduction example, which container are you running? Did you restart the computer? What was failing?

**Comment by chennakesava1** [comment]
1. Can you give a reproduction example, which container are you running?
Issue happening after few days like might be reaching number of connections like once i restart docker then working fine again after few days services are not able to access.
I am running around 20 containers those are apache2, kafka, rabbitmq, CDR, Eureka, few JAVA microservices which interact each other.

2. Did you restart the computer? 
I no need to restart the computer.  i need to restart docker for windows then working fine.

3.What was failing?
I am not abel to access access apps like apache rabbitmq .. but i see the container statis is helghy

**Comment by chennakesava1** [comment]
Below are the container status 
C:\Users\Administrator\Documents\hardening\NOLIS-1.0.0>docker ps
CONTAINER ID        IMAGE                                                                       COMMAND                  CREATED             STATUS                       PORTS                                                                                        NAMES
4fc268606faf        161.92.248.172:5000/nolis-dicom-importer:phoenix-integration-1.0.0          "sh -c 'java $NOLIS_…"   23 hours ago        Up About an hour             0.0.0.0:270-271->270-271/tcp, 260/tcp, 0.0.0.0:8079->8079/tcp                                nolis-dicom-importer
cef855500d3f        161.92.248.172:5000/nolis-importer:phoenix-integration-1.0.0                "sh -c 'java $NOLIS_…"   3 days ago          Up About an hour             0.0.0.0:8087->8087/tcp                                                                       nolis-importer
241db00b0424        161.92.248.172:5000/nolis-study-watcher:phoenix-integration-1.0.0           "sh -c 'java $NOLIS_…"   3 days ago          Up About an hour (healthy)   0.0.0.0:8086->8086/tcp                                                                       nolis-study-watcher
877322d45224        161.92.248.172:5000/config-server:sig-markets-phoenix-customer-2.1.0.0      "sh -c 'java $JAVA_O…"   6 days ago          Up About an hour (healthy)   0.0.0.0:10015->10015/tcp                                                                     config-server
774309aa7511        161.92.248.172:5000/discovery:sig-markets-phoenix-customer-2.1.0.0          "sh -c 'java $JAVA_O…"   6 days ago          Up About an hour (healthy)   0.0.0.0:10008->10008/tcp                                                                     discovery
e7e3eb8629f2        161.92.248.172:5000/redis:sig-markets-phoenix-customer-2.1.0.0              "/bin/sh -c '(cron -…"   6 days ago          Up About an hour (healthy)   0.0.0.0:6379->6379/tcp                                                                       redis
ad06218e4e70        161.92.248.172:5000/filebeat:sig-markets-phoenix-customer-2.1.0.0           "filebeat -e -c /etc…"   6 days ago          Up About an hour (healthy)                                                                                                filebeat
9a73162d3958        161.92.248.172:5000/kafka:sig-markets-phoenix-customer-2.1.0.0              "/kafka-zoo-start.sh"    6 days ago          Up About an hour (healthy)   2888/tcp, 0.0.0.0:2181->2181/tcp, 0.0.0.0:9092->9092/tcp, 3888/tcp                           kafka
1a1161650dbb        161.92.248.172:5000/postgres:sig-markets-phoenix-customer-2.1.0.0           "docker-entrypoint.s…"   6 days ago          Up About an hour (healthy)   0.0.0.0:5432->5432/tcp                                                                       postgres
0cebf89c6915        161.92.248.172:5000/nolis-infra:phoenix-integration-1.0.0                   "sh -c 'java $NOLIS_…"   7 days ago          Up About an hour             0.0.0.0:8093->8093/tcp                                                                       nolis-infra
40fe863f2da8        161.92.248.172:5000/apache2:sig-markets-phoenix-customer-2.1.0.0            "/startup.sh"            7 days ago          Up About an hour (healthy)   0.0.0.0:443->443/tcp                                                                         apache2
ef16c7dbcad2        161.92.248.172:5000/nolis-application-workflow:phoenix-integration-1.0.0    "sh -c 'java $NOLIS_…"   7 days ago          Up About an hour             0.0.0.0:8084->8084/tcp                                                                       nolis-application-workflow
b28ba514d44c        161.92.248.172:5000/nolis-patient-management:phoenix-integration-1.0.0      "sh -c 'java $NOLIS_…"   7 days ago          Up About an hour             0.0.0.0:8088->8088/tcp                                                                       nolis-patient-management
f1ee8a4090b2        161.92.248.172:5000/nolis-task-management:phoenix-integration-1.0.0         "sh -c 'java $NOLIS_…"   7 days ago          Up About an hour             0.0.0.0:8098->8098/tcp                                                                       nolis-task-management
c1ede860e5a2        161.92.248.172:5000/nolis-medication-management:phoenix-integration-1.0.0   "sh -c 'java $NOLIS_…"   7 days ago          Up About an hour             0.0.0.0:8091->8091/tcp                                                                       nolis-medication-management
1bd5bdabc3f1        161.92.248.172:5000/nolis-visit-management:phoenix-integration-1.0.0        "sh -c 'java $NOLIS_…"   7 days ago          Up About an hour             0.0.0.0:8099->8099/tcp                                                                       nolis-visit-management
522ce043b1b9        161.92.248.172:5000/audit-service:sig-markets-phoenix-customer-2.1.0.0      "sh -c 'java $JAVA_O…"   7 days ago          Up About an hour (healthy)   0.0.0.0:8090->8090/tcp                                                                       audit-service
064c9492c8f3        161.92.248.172:5000/phoenix-cdr:sig-markets-phoenix-customer-2.1.0.0        "sh -c 'java $JAVA_O…"   7 days ago          Up About an hour (healthy)   0.0.0.0:8089->8089/tcp                                                                       phoenix-cdr
e7a9487fa872        161.92.248.172:5000/configuration:sig-markets-phoenix-customer-2.1.0.0      "sh -c 'java $JAVA_O…"   7 days ago          Up About an hour (healthy)   0.0.0.0:10007->10007/tcp                                                                     configuration
e2d81f67c310        161.92.248.172:5000/iam:sig-markets-phoenix-customer-2.1.0.0                "sh -c 'java $JAVA_O…"   7 days ago          Up About an hour (healthy)   0.0.0.0:10003->10003/tcp                                                                     iam
a43064e83683        161.92.248.172:5000/ems-service:sig-markets-phoenix-customer-2.1.0.0        "sh -c 'java $JAVA_O…"   7 days ago          Up About an hour (healthy)   0.0.0.0:10005->10005/tcp                                                                     ems-service
d6433c6724c5        161.92.248.172:5000/api-gateway:sig-markets-phoenix-customer-2.1.0.0        "sh -c 'java $JAVA_O…"   7 days ago          Up About an hour (healthy)   0.0.0.0:8443->8443/tcp                                                                       api-gateway
dfdea6d1ffb8        161.92.248.172:5000/rabbitmq:phoenix-integration-1.0.0                      "docker-entrypoint.s…"   2 weeks ago         Up About an hour (healthy)   4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp, 15671/tcp, 25672/tcp, 0.0.0.0:15672->15672/tcp   rabbitmq

**Comment by chennakesava1** [comment]
I am adding erros log fiel as well for your reference.

Version: 2.0.0.3 (31259)
Channel: stable
Sha1: 8858db33c8692b69de9987a5d672798d778735b2
Started on: 2019/05/29 12:00:14.373
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows Server 2016 Standard
Edition: ServerStandard
Id: 1607
Build: 14393
BuildLabName: 14393.2848.amd64fre.rs1_release.190305-1856
File: C:\Users\Administrator\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[00:00:17.038][SegmentApi     ][Info   ] Usage statistic: heartbeat
[00:00:27.049][SegmentApi     ][Error  ] Failed to track event heartbeat: timeout after 10s
[01:00:17.047][SegmentApi     ][Info   ] Usage statistic: heartbeat
[01:00:27.064][SegmentApi     ][Error  ] Failed to track event heartbeat: timeout after 10s
[02:00:17.048][SegmentApi     ][Info   ] Usage statistic: heartbeat
[02:00:27.079][SegmentApi     ][Error  ] Failed to track event heartbeat: timeout after 10s
[03:00:17.049][SegmentApi     ][Info   ] Usage statistic: heartbeat
[03:00:27.065][SegmentApi     ][Error  ] Failed to track event heartbeat: timeout after 10s
[04:00:17.051][SegmentApi     ][Info   ] Usage statistic: heartbeat
[04:00:27.065][SegmentApi     ][Error  ] Failed to track event heartbeat: timeout after 10s
[05:00:17.052][SegmentApi     ][Info   ] Usage statistic: heartbeat
[05:00:27.064][SegmentApi     ][Error  ] Failed to track event heartbeat: timeout after 10s
[06:00:17.064][SegmentApi     ][Info   ] Usage statistic: heartbeat
[06:00:27.079][SegmentApi     ][Error  ] Failed to track event heartbeat: timeout after 10s
[07:00:17.065][SegmentApi     ][Info   ] Usage statistic: heartbeat
[07:00:27.078][SegmentApi     ][Error  ] Failed to track event heartbeat: timeout after 10s
[08:00:17.066][SegmentApi     ][Info   ] Usage statistic: heartbeat
[08:00:27.081][SegmentApi     ][Error  ] Failed to track event heartbeat: timeout after 10s
[09:00:17.079][SegmentApi     ][Info   ] Usage statistic: heartbeat
[09:00:27.097][SegmentApi     ][Error  ] Failed to track event heartbeat: timeout after 10s
[10:00:17.080][SegmentApi     ][Info   ] Usage statistic: heartbeat
[10:00:27.095][SegmentApi     ][Error  ] Failed to track event heartbeat: timeout after 10s
[11:00:17.081][SegmentApi     ][Info   ] Usage statistic: heartbeat
[11:00:27.096][SegmentApi     ][Error  ] Failed to track event heartbeat: timeout after 10s
[12:00:17.082][SegmentApi     ][Info   ] Usage statistic: heartbeat
[12:00:27.095][SegmentApi     ][Error  ] Failed to track event heartbeat: timeout after 10s
[12:02:36.743][ApiProxy       ][Info   ] time="2019-05-30T12:02:36+05:30" msg="proxy >> GET /_ping\n"
[12:02:36.747][ApiProxy       ][Info   ] time="2019-05-30T12:02:36+05:30" msg="proxy << GET /_ping (4.0015ms)\n"
[12:02:36.883][VpnKit         ][Info   ] vpnkit.exe: Connected Ethernet interface f6:16:36:bc:f9:c6

[12:02:36.883][VpnKit         ][Info   ] vpnkit.exe: UDP interface connected on 161.92.248.172

[12:02:36.879][ApiProxy       ][Info   ] time="2019-05-30T12:02:36+05:30" msg="proxy >> POST /v1.39/images/161.92.248.172:5000/nolis-importer/push?tag=phoenix-integration-1.0.0\n"
[12:02:36.935][ApiProxy       ][Info   ] time="2019-05-30T12:02:36+05:30" msg="proxy << POST /v1.39/images/161.92.248.172:5000/nolis-importer/push?tag=phoenix-integration-1.0.0 (55.0032ms)\n"
[13:00:17.083][SegmentApi     ][Info   ] Usage statistic: heartbeat
[13:00:27.094][SegmentApi     ][Error  ] Failed to track event heartbeat: timeout after 10s
[13:38:44.518][VpnKit         ][Error  ] vpnkit.exe: Socket.Stream: caught An existing connection was forcibly closed by the remote host.


[14:00:17.085][SegmentApi     ][Info   ] Usage statistic: heartbeat
[14:00:27.097][SegmentApi     ][Error  ] Failed to track event heartbeat: timeout after 10s

**Comment by mikeparker** [comment]
Out of curiosity, why are you using Docker Desktop on a Windows Server? Did you try running Docker Engine Enterprise instead?

**Comment by mikeparker** [comment]
When you say `I am not abel to access access apps like apache rabbitmq .. but i see the container statis is helghy` can you be more specific? Whats wrong with the containers? What are the container logs saying? Which calls are failing? Is it the network connection, the disk access, is the container itself dying?

**Comment by chennakesava1** [comment]
We need to check the advantages on Docker Engine Enterprise then we will take a call on it.

Coming to this issue,  Yes all container status is healthy only and we are not seeing any error logs as well. 
actually, when this issue is there the request not reaching to containers it's blocking host system to Docker engine. once I restart Docker then it's working fine.


Is there any limit for Docker endpoint.  is it after reaching a number of requests it's will stopping response

**Comment by chennakesava1** [comment]
@mikeparker, by seeing the Docker for windows logs could you suggest any workaround.
 Docker for windows error logs 
`[02:00:27.079][SegmentApi ][Error ] Failed to track event heartbeat: timeout after `10s``

**Comment by mikeparker** [comment]
I dont think the event heartbeat is relevant. Thats just docker desktop pinging the tracking server to tell us docker desktop is running. It doesnt matter much if its blocked / failed. It won't be affecting your container connectivity.

**Comment by mikeparker** [comment]
Can you check memory and CPU usage of your containers and check you are not hitting the limits of the system? Please follow instructions here and paste the output: https://github.com/docker/for-win/issues/3858#issuecomment-499438402

**Comment by chennakesava1** [comment]
@mikeparker, looks memory & CPU looks fine even we have response container to container. we are able to access apache2 container app from deferment container. But i am not able to access from windows host once i restart the docker then i am able to access.  
we are having this issue other systems as well like win2016 standard as well. we are not using Kubernites & Swarm .
Is there any issues like exposed ports become unresponsive or outside network connectivity hangs like.

**Comment by stephanecot** [comment]
I have exactly the same problem here.
I never had this problem before and I think it s since I update to windows 10 19.03
I build a all fresh new computer this week end and I have exactly the same problem!

**Comment by chennakesava1** [comment]
@mikeparker, @stephanecot, I have downgraded the Docker for Windows version 18.09.2 to Docker for Windows version 18.06.1.
Now, I am not seeing this issue. @mikeparker.
