### ISSUE TITLE
Error / install on Windows, please help

### ISSUE THREAD

**Issue by pilwe** [docker/for-win#4008]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mikeparker** [comment]
Please describe the problem you are having and fill out the issue template.

**Comment by pilwe** [comment]
Sorry,

after install on Win 10 (1904) docker is not starting. I only get d´this Error:

Unable to create: Der ausgeführte Befehl wurde beendet, da die Einstellungsvariable "ErrorActionPreference" oder ein allgemeiner Parameter auf "Stop" festgelegt ist: Fehler beim Erstellen eines neuen virtuellen Computers.

MobyLinuxVM: Fehler beim Erstellen. (ID des virtuellen Computers: 6F50491E-7169-43A0-915E-CED6EE12B405)

Fehler beim Zugriff auf den Konfigurationsspeicher: Das System kann den angegebenen Pfad nicht finden. (0x80070003)..
bei New-MobyLinuxVM, <Keine Datei>: Zeile 191
bei <ScriptBlock>, <Keine Datei>: Zeile 411
   bei Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:Zeile 36.
   bei Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:Zeile 92.
   bei Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:Zeile 74.
   bei Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:Zeile 59.

**Comment by mikeparker** [comment]
Can you fill out the issue template please? I need to know the details. Including what version of docker desktop, what version of windows.
