### ISSUE TITLE
How to restart Docker with proxy settings using powershell or cmd

### ISSUE THREAD

**Issue by eivantsov** [docker/for-win#401]
I am trying to restart Docker service on Win 10, but after it is stopped and restarted  I cannot use any docker syntax:

```
PS C:\Windows\system32> net stop com.docker.service
The Docker for Windows Service service is stopping.
A system error has occurred.

System error 1067 has occurred.

The process terminated unexpectedly.

The Docker for Windows Service service was stopped successfully.

PS C:\Windows\system32> net start com.docker.service
The Docker for Windows Service service is starting.
The Docker for Windows Service service was started successfully.

PS C:\Windows\system32> docker ps
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.25/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error ma
y also indicate that the docker daemon is not running.
PS C:\Windows\system32>
```

My goal here is first to restart Docker without using Windows client app. Also another question: how to apply proxy settings for Docker, again, without interacting with the application (using powershell or cmd)

**Comment by rneugeba** [comment]
are you trying to use windows or Linux container?

If you are using Linux containers, we don't support starting it via powershell.

If you use Windows containers and don't want to use the UI, you can always just use the stand alone package as per: https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-10

**Comment by eivantsov** [comment]
@rneugeba yes, just old good linux containers. I'd like to be able to restart Docker from my application just like it's done in a nativr Docker for windows when you apply proxy settings or just restart Docker.

**Comment by rneugeba** [comment]
I'm afraid that's currently not possible. You can only change the settings via the UI for now.

What's your use case?

**Comment by eivantsov** [comment]
My application needs Docker as a dependency and it checks Docker health and connectivity. I want to hide Docker from a user, i.e. if proxy settings need to be applied, I want to do that in my app, without having a user to to Docker app UI.

**Comment by rneugeba** [comment]
@eivantsov Docker for Windows is designed as an desktop application to be used by end users/developers. So I'm closing this issue as won't fix

**Comment by eivantsov** [comment]
@rneugeba thanks for clarifying.
