### ISSUE TITLE
docker push exits with EOF.

### ISSUE THREAD

**Issue by gitnwana** [docker/for-win#4010]
While using `docker push` command to push the docker image to Azure container registry, the command exits with EOF.
`
The push refers to repository [registry.azurecr.io/name]
7387f39edda5: Layer already exists
f2868d922c36: Layer already exists
a1a215f52b02: Pushing [==================================================>]  42.37MB/42.37MB
851d4ecec8fb: Layer already exists
e16c226cf2a8: Layer already exists
7fd597d009e4: Pushing [=======>                                           ]  18.73MB/117.7MB
7c6ab5fb7059: Layer already exists
ed271eac23e9: Layer already exists
156ff16f37e4: Retrying in 19 seconds
EOF
`

**Comment by mikeparker** [comment]
This is a bug tracker, not a support forum, please ask support questions in https://forums.docker.com/c/docker-desktop-for-windows
