### ISSUE TITLE
Docker on Windows10Pro Runs but doesn't pop up in a window

### ISSUE THREAD

**Issue by swample1** [docker/for-win#4011]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B75D22EF-8BF3-4890-BF02-3079666EDC79/20190530153019

### Expected behavior
Docker Should Run
### Actual behavior
Runs, but only in background, no windows except log in window.
### Information
Is running in the background however nothing loads, 
Please, help us understand the problem.  For instance:
  - Is it reproducible?
  - Is the problem new?
  - Did the problem appear with an update?
  - A reproducible case if this is a bug, Dockerfiles FTW.
  - Windows Version: Windows10 Pro
  - Docker for Windows Version: 

### Steps to reproduce the behavior
A reproducible case, Dockerfiles FTW.
1. Download Fresh
2. Enable Hyper-V
3. Try to run
4. Log in (window goes away)
5. Nothing Happens

**Comment by mikeparker** [comment]
Do you have the system tray icon?

**Comment by inphobia** [comment]
while not exactly the same i do have a similar problem. the toolbar item for docker for windows shows up (i have changed the default windows settings to always show all icons on the taskbar), but right clicking on it to get the menu takes between 2 to 5 tries. commandline tools & intellij idea plugin don't seem to be having issues.

gonna be lazy & dump a screenshot with version info:
![image](https://user-images.githubusercontent.com/39005454/58696273-88cdcd80-8397-11e9-9ef7-8e7afcd0ff6b.png)

```Microsoft Windows [Version 10.0.18362.145]```

docker on windows:
```Docker version 19.03.0-beta3, build c55e026```


docker client on wsl with opensuse leap 15.1 also works fine when using tcp connections:
```
Linux LA7285 4.4.0-18362-Microsoft #1-Microsoft Mon Mar 18 12:02:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
Docker version 18.09.6, build 481bc7715621
```
(it says kubernetes is installed but that's the one which came with docker for windows)

my %USERPROPFILE%/.docker settings are:
```
{
  "registry-mirrors": [],
  "insecure-registries": [],
  "debug": true,
  "experimental": true
}
```

3 other settings changed when the docker for windows menu did pop up:
 * kubernetes disbaled 
 * telemetry disabled
 * tcp unencrypted on 127.0.01/8 enabled

**Comment by mikeparker** [comment]
One possibility is that you're clicking on the icon from a notification instead of the real systray icon, could you check that?

**Comment by inphobia** [comment]
> notification instead of the real systray icon

i don't think so. configured windows to always show all icons on the taskbar. most, if not all, of my notification center settings are turned off. it's not really an issue for me since i interact via cli almost always, but just wanted to note that i kinda see a similar issue.
