### ISSUE TITLE
Docker can connect to engine, but docker compose cannot

### ISSUE THREAD

**Issue by MikeChristensen** [docker/for-win#4012]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Docker-compose should run within a container and connect to the host's Docker engine

### Actual behavior

Error message:

Couldn't connect to Docker daemon. You might need to start Docker for Windows.

### Information

  - Windows Version: Windows Server 2019 Core (Build 17763 Kernel version 1809)
  - Docker for Windows Version: Docker version 18.09.6, build 1578dcadd2

### Steps to reproduce the behavior

  1. Run a container (doesn't matter which one) and mount the named pipe using `-v //./pipe/docker_engine://./pipe/docker_engine` - this will let your container talk to the host's docker engine.  You'll want to share out the Docker bin directory too so you can actually run docker in the container.
  2. In the docker container, type `docker ps` to verify you can indeed connect to the host's docker engine.
  3. From within the Docker container, try running `docker-compose` (point it to a YML file or something to build)

Result: `Docker ps` runs but `docker-compose` errors out.

**Comment by joeondrus** [comment]
Our team is also having this issue.  We also need to use `docker-compose up` in a Windows (Server 2019 1809) container.

I am not sure if these are related, but after looking into this issue we found quite a few problems that others are having which all attempt to use `-v //./pipe/docker_engine://./pipe/docker_engine`:
- [docker/compose/issues/5934](https://github.com/docker/compose/issues/5934)  
- [docker/docker-py/issues/2018](https://github.com/docker/docker-py/issues/2018)
- [mody/moby/issues/36970](https://github.com/moby/moby/issues/36970)

There are even more issues out there that are having this problem.  I can try to track some more down if you think it might help.

**Comment by SLdragon** [comment]
WaitNamedPipe API call in the npipesocket.py module doesn't work correctly from inside a Windows container.
This is because currently WaitNamedPipeis not supported from inside of Windows Containers (however CreateNamedPipeClient works ok). It fails with ERROR_FILE_NOT_FOUND

I created a pull request just avoid using WaitNamedPipe API to fix this issue:
https://github.com/docker/docker-py/pull/2421
