### ISSUE TITLE
d4w/nsenter keeps coming back after I deleted it

### ISSUE THREAD

**Issue by syncxplus** [docker/for-win#404]
### Expected behavior
NA
### Actual behavior
NA
### Information
Does anyone know what this image is? It keeps appearing when I run "docker images" every time after a docker restart. I have ran "docker rmi 9e4f13a0901e" to delete the image but after a docker restart, it is present again.
running env:
Windows10 14393.693
Docker version 1.12.5, build 7392c3b

### Steps to reproduce the behavior
1. Just startup the docker for windows, the d4w/nsenter appears. Delete it and restart docker, it appears again.

**Comment by friism** [comment]
Also reported on forums: https://forums.docker.com/t/what-is-the-image-d4w-nsenter-it-keeps-coming-back-after-i-delete-it-is-this-malware/27247

@simonferquel could this somehow be run as a non-userland container?

@syncxplus [can you please update to Docker 1.13.0](https://docs.docker.com/docker-for-windows/)? That the latest stable release. If the problem persists, generate a diagnostic dump and post the id

**Comment by simonferquel** [comment]
This is an image we use internally to remotely administrate the Linux VM (mount shared drives, ...) shipping with Docker for Windows (it is not pulled, but loaded from disk).
You can delete it, but it will be re-loaded each time Docker for Windows needs to take an administrative action.

**Comment by syncxplus** [comment]
@friism Upgrade to 1.13.0 build 49bf474, the issue still existed.
Already upload a  diagnostic dump with id **5D4DAECD-A3D2-445F-BA39-793A38A9969B/2017-01-22_20-55-20**

**Comment by dgageot** [comment]
@syncxplus @friism This container is used to mount the shared drives, so each time docker is restarted, the container is reloaded. @syncxplus is it an actual issue for you or was it just something that you found suspicious?

**Comment by syncxplus** [comment]
@dgageot Thanks for your explain. So far I see it is not a actual issue. Just feel confused since the container is not pulled by myself. It's an expected behaviour, right? If that we can close this topic.

**Comment by KevinBurton** [comment]
I am at 1.37 and am also seeing this. I looked on DockerHub the image apparently is in the registry but there is no description of it. 

`docker4w/nsenter-dockerd   latest              cae870735e91        5 months ago        187kB`

When I inspect the image I get:
docker inspect docker4w/nsenter-dockerd
```
[
    {
        "Id": "sha256:cae870735e91d8f29efc72455d794e592f3d9a16bb6f7dc8b48e9d89c23c8cdf",
        "RepoTags": [
            "docker4w/nsenter-dockerd:latest"
        ],
        "RepoDigests": [],
        "Parent": "",
        "Comment": "",
        "Created": "2017-10-25T13:50:32.862021612Z",
        "Container": "97de1a65fc41d8ed44ab200784091da8645f8d75b333a70d9ba1283102eb7c07",
        "ContainerConfig": {
            "Hostname": "97de1a65fc41",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "ENTRYPOINT [\"/usr/bin/nsenter1\"]"
            ],
            "Image": "sha256:87ff56922832a965557bb90c66c20b685d4d3352d8653c13130214bde74e66bc",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/usr/bin/nsenter1"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "DockerVersion": "17.10.0-ce",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": null,
            "Image": "sha256:87ff56922832a965557bb90c66c20b685d4d3352d8653c13130214bde74e66bc",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/usr/bin/nsenter1"
            ],
            "OnBuild": null,
            "Labels": null
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 187464,
        "VirtualSize": 187464,
        "GraphDriver": {
            "Data": {
                "MergedDir": "/var/lib/docker/overlay2/a8cb83dda2775d07edebdf7acb8f7d52ae8935a48f15eec01e0ab4ac0feb3ffe/merged",
                "UpperDir": "/var/lib/docker/overlay2/a8cb83dda2775d07edebdf7acb8f7d52ae8935a48f15eec01e0ab4ac0feb3ffe/diff",
                "WorkDir": "/var/lib/docker/overlay2/a8cb83dda2775d07edebdf7acb8f7d52ae8935a48f15eec01e0ab4ac0feb3ffe/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:4384a51c187e6448bff490258e3609fdbd75cb9d1a4c1f1fd1cb800acb4cb544"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
```
This is the version that I am running:
```
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:06:28 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   0520e24
  Built:        Wed Mar 21 23:14:32 2018
  OS/Arch:      linux/amd64
  Experimental: false
```
