### ISSUE TITLE
docker pull hello-world -> Error response from daemon: Get https://registry-1.docker.io/v2/

### ISSUE THREAD

**Issue by GitMaRob** [docker/for-win#4043]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by GitMaRob** [comment]
Diagnostics ID: 
06262931-8849-44AF-8C9B-748FC347B3FF/20190606105116

**Comment by GitMaRob** [comment]
I have tried with the latest version of my channel (Stable or Edge) -> YES
 I have uploaded Diagnostics -> YES

Diagnostics ID:
 06262931-8849-44AF-8C9B-748FC347B3FF/20190606105116


•Windows Version: VMWARE with Windows Server 2016
•Docker for Windows Version:
PS C:\Windows\system32> docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false

Steps to reproduce the behavior: 
There is nothing to reproduce, if restart it be the same issue.
We check with Wireshark
Firewall -> OK
Proxy -> OK

**Comment by GitMaRob** [comment]
PS C:\Windows\system32> docker pull hello-world
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connectio
n (Client.Timeout exceeded while awaiting headers)
PS C:\Windows\system32> docker --version
Docker version 18.09.2, build 6247962

**Comment by GitMaRob** [comment]
If i change to manual proxy configuration, so i get the followed issue:
https://github.com/docker/for-win/issues/4014

**Comment by GitMaRob** [comment]
Supplement: The Windows Server 2016 VM is hosted on a VMware ESXi on premises host. Hyper-V for the VM is activated.

**Comment by mikeparker** [comment]
Can you hit https://registry-1.docker.io/v2/ from the box at all?. i.e. `curl` or a browser?

**Comment by GitMaRob** [comment]
The Windows 2016 VM computer stands in a company network, behind firewall and proxy.

Windows 2016 VM ->
PS C:\WINDOWS\system32> curl https://registry-1.docker.io/v2/
curl : {"errors":[{"code": "UNAUTHORIZED", "message": "authentication required", "detail":null}]}

I also installed Docker parallel on a local notebook with Windows 10 in the company network. There everything works as it should. Therefore I can compare here. I get the same message on the local notebook Windows 10 when I use curl. Only that the Docker works here. 

Let's assume that the proxy and the system policies on the VM WIN 2016 Server are OK, so I would either have to prove that this is not the case, or there is another solution that is not related to it.

--------------------------------------------------------------

Yesterday I tested curl and there was no error on the local computer, it worked here. On the Windows 2016 server I had also tested it yesterday, there was also a timeout. But I can't reproduce this message today and only get the upper UNAUTHORIZED message in both cases. I have to say that both computers got a reboot yesterday evening.

I can't imagine that the network policies have changed again since yesterday!

I have full admin rights on the computers, i.e. I can download an exe file on both via the browser. 

If I enter the https://registry-1.docker.io/v2/ into the Chrome Browser, then I also get the following message on both computers:
{"errors":[{"code": "UNAUTHORIZED", "message": "authentication required", "detail":null}]}

**Comment by GitMaRob** [comment]
Must say that I have no proxy credentials. These are not managed by myself.

**Comment by GitMaRob** [comment]
I found this link: https://stackoverflow.com/questions/51188733/docker-registry-https-registry-1-docker-io-v2-dial-tcp-34-200-90-16443-giv 
I will first check this point again with our proxy administrator. Unless you @mikeparker have another suggestion.

**Comment by mikeparker** [comment]
The UNAUTHORIZED message means the connection is working, this is expected. The interesting piece is when the timeouts occur:

> On the Windows 2016 server I had also tested it yesterday, there was also a timeout. But I can't reproduce this message today and only get the upper UNAUTHORIZED message in both cases. 

This seems bizarre. I'd be interested if you can repro this.

I saw another report of a timeout hitting the registry also but they couldnt even hit it from a browser so it was likely DNS / VPN / Firewall settings outside of docker.

I don't have any suggestions yet and I'm not sure yet if its a Docker issue or an external networking issue.

**Comment by mikeparker** [comment]
Also I'm fairly sure that we don't officially support nested virtualization so I'm not sure we guarantee the networking will work if you're trying to run docker inside a VM. It's possible nested virt is to blame, not sure though.

**Comment by GitMaRob** [comment]
First of all many thanks @mikeparker for your quick answer! :)
I've found the solution and would like to document it here!

I also added the proxy last Friday with: set http_proxy=xxx.xxx.xxx.xxx.xxx:PORT.
Result: the same mistake as before.

Today I checked the settings again. 
I restart the WIN 2016 VM again and checked the proxy settings in IE. 
It was due to the proxy settings. If the proxy is "only" registered in IE or is set with set http_proxy, then Docker does not accept this entry in this case. Here the proxy MUST be entered additional under Docker settings with the identicaly proxy like in IE. That's it.


Solution in this case:
Docker-> Settings -> Proxy -> Webserver xxx.xxx.xxx.xxx.xxx:PORT
Check -> Use same for both
No bypass settings.
Restart Docker.

docker pull hello-world 

PS C:\Windows\system32> docker pull hello-world
Using default tag: latest
latest: Pulling from library/hello-world
1b930d010525: Pull complete
Digest: sha256:0e11c388b664df8a27a901dce21eb89f11d8292f7fca1b3e3c4321bf7897bffe
Status: Downloaded newer image for hello-world:latest
docker.io/library/hello-world:latest

That was the only difference between the Win 10 and Win2016 server, which the Docker needed additionally under the VM Win 2016 again the same proxy entry as in the IE is already registered.

So the subject is closed. Thank you!

**Comment by mikeparker** [comment]
Great, thanks for detailing the fix, i'm sure it'll help others!

**Comment by GitMaRob** [comment]
General additional info:
Docker now works fine for me. 
------------------------------------------------------------------------------
Note:
When I now test Curl again in PowerShell, it still displays the same result even though the proxy is registered in the Docker and is working:

PS C:\Windows\system32>  curl https://registry-1.docker.io/v2/
curl : {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}
At line:1 char:2
+  curl https://registry-1.docker.io/v2/
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

To test the function in that case, this test is the safer way to go:
PS C:\Windows\system32> docker pull hello-world
Using default tag: latest
latest: Pulling from library/hello-world
Digest: sha256:0e11c388b664df8a27a901dce21eb89f11d8292f7fca1b3e3c4321bf7897bffe
Status: Image is up to date for hello-world:latest
docker.io/library/hello-world:latest

Curl is a good way to check this issue general.
In our case, checking this setting with Curl doesn't seem to be able. Even if the proxy is entered in Docker, Curl gets an error.

Hope this helps others.

**Comment by sharkdeng** [comment]
> First of all many thanks @mikeparker for your quick answer! :)
> I've found the solution and would like to document it here!
> 
> I also added the proxy last Friday with: set http_proxy=xxx.xxx.xxx.xxx.xxx:PORT.
> Result: the same mistake as before.
> 
> Today I checked the settings again.
> I restart the WIN 2016 VM again and checked the proxy settings in IE.
> It was due to the proxy settings. If the proxy is "only" registered in IE or is set with set http_proxy, then Docker does not accept this entry in this case. Here the proxy MUST be entered additional under Docker settings with the identicaly proxy like in IE. That's it.
> 
> Solution in this case:
> Docker-> Settings -> Proxy -> Webserver xxx.xxx.xxx.xxx.xxx:PORT
> Check -> Use same for both
> No bypass settings.
> Restart Docker.
> 
> docker pull hello-world
> 
> PS C:\Windows\system32> docker pull hello-world
> Using default tag: latest
> latest: Pulling from library/hello-world
> 1b930d010525: Pull complete
> Digest: sha256:0e11c388b664df8a27a901dce21eb89f11d8292f7fca1b3e3c4321bf7897bffe
> Status: Downloaded newer image for hello-world:latest
> docker.io/library/hello-world:latest
> 
> That was the only difference between the Win 10 and Win2016 server, which the Docker needed additionally under the VM Win 2016 again the same proxy entry as in the IE is already registered.
> 
> So the subject is closed. Thank you!

I solved this issue by clicking docker icon on the right up corner. Than it prompted me to enter username and password. Than I can successfully pull. 
It seems previously I was not logged in. So it said "Error response from daemon:"

**Comment by XJTUzhangliwen** [comment]
try to run cmd as administrator

**Comment by vvaswani17** [comment]
> > First of all many thanks @mikeparker for your quick answer! :)
> > I've found the solution and would like to document it here!
> > I also added the proxy last Friday with: set http_proxy=xxx.xxx.xxx.xxx.xxx:PORT.
> > Result: the same mistake as before.
> > Today I checked the settings again.
> > I restart the WIN 2016 VM again and checked the proxy settings in IE.
> > It was due to the proxy settings. If the proxy is "only" registered in IE or is set with set http_proxy, then Docker does not accept this entry in this case. Here the proxy MUST be entered additional under Docker settings with the identicaly proxy like in IE. That's it.
> > Solution in this case:
> > Docker-> Settings -> Proxy -> Webserver xxx.xxx.xxx.xxx.xxx:PORT
> > Check -> Use same for both
> > No bypass settings.
> > Restart Docker.
> > docker pull hello-world
> > PS C:\Windows\system32> docker pull hello-world
> > Using default tag: latest
> > latest: Pulling from library/hello-world
> > 1b930d010525: Pull complete
> > Digest: sha256:0e11c388b664df8a27a901dce21eb89f11d8292f7fca1b3e3c4321bf7897bffe
> > Status: Downloaded newer image for hello-world:latest
> > docker.io/library/hello-world:latest
> > That was the only difference between the Win 10 and Win2016 server, which the Docker needed additionally under the VM Win 2016 again the same proxy entry as in the IE is already registered.
> > So the subject is closed. Thank you!
> 
> I solved this issue by clicking docker icon on the right up corner. Than it prompted me to enter username and password. Than I can successfully pull.
> It seems previously I was not logged in. So it said "Error response from daemon:"

it is already checked but not working with company network.

**Comment by Landstalker13** [comment]
what a bad tool this Docker who neglects their clients to fight with undocumented proxy constraints
