### ISSUE TITLE
Docker hv-sock proxy (vsudd) is not reachable

### ISSUE THREAD

**Issue by mattgould** [docker/for-win#406]
### Expected behavior
Docker runs

### Actual behavior
Docker failes with error:
  Docker hv-sock proxy (vsudd) is not reachable

### Information
Diagnostic ID: E9D48564-7054-4F6B-A5A7-EA1B04B7871E/2017-01-20_11-31-24

### Steps to reproduce the behavior

  1. Allowed Docker to update and it stopped working

**Comment by mattgould** [comment]
I have tried resetting Docker and also removing it and reinstalling from a new download.
It was working fine before it told me that there was a new version available and I allowed it to upgrade.

**Comment by kddlb** [comment]
I hsve the same issue, with Diagnostic ID `C36420E5-F955-412C-85FB-AA284069EF4B/2017-01-22_00-42-42`.

**Comment by groupe-pichet** [comment]
Hello, I has the same PB during a new install => `B244A149-E903-44BC-B5C1-7EBDA98A2659/2017-01-22_09-34-20`

**Comment by nhannb** [comment]
I have the same issue as well
CF1E3678-F30E-4038-91C9-626477E3B624/2017-01-24_08-17-39

**Comment by tschmit** [comment]
exact same issue (both channel stable and beta) on a new windows 10 pro installation

**Comment by kutenai** [comment]
Ack. I've been trying to get Docker running on a windows VM for a while. Did not realize it required Parallels PRO to do it till yesterday. I bought the upgrade, downloaded it, and was all excited to run it.. and I got this. So dissappointed right now, but hopeful there is a fix coming??

**Comment by mattgould** [comment]
To be absolutely clear, I am getting this error when running windows natively, not in a VM.
I am running Windows version:
```
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      14393  0
```

**Comment by mattgould** [comment]
After applying all windows updates and restarting, Docker is now working again.

**Comment by ggb667** [comment]
All windows updates applied.  Still happening.

**Comment by Nqabeni** [comment]
Docker hv-sock proxy (vsudd) is not reachable
   at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

**Comment by zleao** [comment]
same here.
running windows 10 pro on parallels 12, all updates

Docker hv-sock proxy (vsudd) is not reachable
   at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

**Comment by ankursaini2006** [comment]
I had the same issue on my windows 10 laptop. I have been trying to resolve it for 4 days and finally I am able to resolve it.

Since my laptop is enterprise one so Docker on windows was not running on startup with Admin rights. Then I tried to open Docker for Windows.exe with "Run as Admin" and then it worked correctly.

I hope this would help others also who are facing the similar issue.

**Comment by fpaiva-univapay** [comment]
I'm on a Mac with Parallels. If I boot by BootCamp, then no problem at all.

The solutions that I already have tried:

I tried to uninstall the Docker then the Hyper-V and then install Docker and have the Hyper-V installed by the Docker. However, still same problem.

I also tried to start Docker as administrator. Still same problem.

Anything else to try?

**Comment by wh01sjongalt** [comment]
Ditto, Windows 10 (fully updated) Updated Docker and then it fails to launch after a long period of loading.  Add/Remove DOCKER & reinstall is no use.  Hosed.

**Comment by kallie-b** [comment]
@ankursaini2006 @mattgould 

Forgive me, as I may not understand this issue entirely. And in fact, I believe there may be multiple things going behind this issue. That said, I'm currently doing research for the Windows Core Networking team, to understand the community's need for HTTP Proxy support for Windows containers.

On Windows, the host HTTP Proxy settings are associated with a user account. Today, we don't officially support inheritance of those settings into container endpoints. We're currently looking into adding that support. **Is this something that you would find useful? If so, can you name use-cases where this would be of value to you or others?**

**Comment by mattgould** [comment]
kallie-b: I don't have anything to add as the problem went away after upgrading Windows.
