### ISSUE TITLE
Docker starts when I login to Windows 10 when it should not

### ISSUE THREAD

**Issue by EagleEyeJohn** [docker/for-win#4061]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 7CEC89A0-66EF-49BC-93E4-E33F9F916F8E/20190610104126

### Expected behavior
Docker does not start when I login
"Start Docker Desktop when you log in" is not ticked - this should be respected

### Actual behavior
Docker DOES start when I login

### Information
  - Windows Version: 10
  - Docker Desktop Version: latest

**Comment by SteveALee** [comment]
I tried the Latest Edge build and the problems appears to be be resolved

**Comment by F21** [comment]
I am seeing this problem after docker for windows updated to 2.0.5.0 (35318) edge. Even though `Start Docker Desktop when you log in` is unticked, it still starts every time I log into Windows.

I am using Windows 10 1903 (build 18362.175).

**Comment by mat007** [comment]
@EagleEyeJohn this bug has been fixed on the Edge channel and should be available in the next Stable release (in a couple of weeks time now).
If needed in the meanwhile you can find the Edge build here https://hub.docker.com/editions/community/docker-ce-desktop-windows

I'll just go ahead and close this issue, should you run into the same problem after installing Edge feel free to re-open.
