### ISSUE TITLE
Deskto always run even though I have selected it not to

### ISSUE THREAD

**Issue by SteveALee** [docker/for-win#4062]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 10592FFA-D56C-4C34-B106-86FB84CEA259/20190610145021

### Expected behavior
When I uncheck 'start Docker for desktop when I log in' I expect it to never run again untill I manual run it or recheck the tick box and log in

![image](https://user-images.githubusercontent.com/618922/59200454-27281300-8b90-11e9-8e5e-90a37633c1ad.png)

### Actual behavior

It always runs on start up or login. So I need to right click in tray and select "Quit Docker Desktop"

### Information

  - Windows Version: 10 pro 10.0.18362
  - Docker Desktop Version: 2.0.0.3 (31259)

### Steps to reproduce the behavior

  1. ... Right click on systray icon and settings and uncheck "start Docker for desktop when I log in"
  2. ... Reboot

**Comment by mikeparker** [comment]
Is this the same on Edge build?

**Comment by kowalski7cc** [comment]
Duplicate of #4061

**Comment by SteveALee** [comment]
> Is this the same on Edge build?

I do not understand - it's a desktop build not a browser thing.

**Comment by mikeparker** [comment]
Docker Desktop Edge is the latest pre-release version of Docker Desktop. You can get it here: https://hub.docker.com/editions/community/docker-ce-desktop-windows

I will update the issue template to make this clearer!

**Comment by SteveALee** [comment]
I'll give it a go. I had to install the latest release anyway as it started crashing on start up.

**Comment by SteveALee** [comment]
Hmm, this is closed but also labelled "more info" so I'll try Edge build and let you know

**Comment by SteveALee** [comment]
@mikeparker does not happen in Edge build. FTW. I'm so happy I could close this issue

**Comment by mikeparker** [comment]
Go for it ;)

**Comment by SteveALee** [comment]
Oooh, closing this feels good!

What great service!!
