### ISSUE TITLE
Docker crashed while installation. Docker version 18.09.2, build 6247962

### ISSUE THREAD

**Issue by AmolPIO** [docker/for-win#4068]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker should install successfully

### Actual behavior
Docker gets crashed by end of installation on Windows 10 Pro

### Information

  - Windows Version: Windows 10 Pro
  - Docker Desktop Version: 18.09.2

### Steps to reproduce the behavior

1. Download Docker desktop install able
2. Run as administrator
3. Proceed with installation wizard steps
4. Crash dump is displayed on installation wizard

**Comment by mikeparker** [comment]
Can you please either attach a diagnostic ID or show the error message?
