### ISSUE TITLE
Crashing on startup. 

### ISSUE THREAD

**Issue by SteveALee** [docker/for-win#4069]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 10592FFA-D56C-4C34-B106-86FB84CEA259/20190612105145

### Expected behavior

Should not crash - actually should not start see my previous report.

### Actual behavior

boom on PC startup

### Information

Nothing obvious changed apart form Windows update

**Comment by mikeparker** [comment]
```
[10:51:45.363][NamedPipeServer][Error  ] Unable to execute Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Inconsistent parameters PolicyStore PersistentStore and Dhcp Enabled
```

See: https://github.com/docker/for-win/issues/2050 
Are you using Cisco AnyConnect? If so:
* stop Cisco agent
* restart docker
* start Cisco agent.

**Comment by SteveALee** [comment]
@mikeparker Thanks but no. I work from home so have no corporate stuff on my PC. I did start using RDP to access another of my machines.

**Comment by SteveALee** [comment]
I do use WebX though. Perhaps I tried launching Docker when running WebX for once.
https://github.com/docker/for-win/issues/2050#issuecomment-501645264

**Comment by SteveALee** [comment]
I uninstalled Docker and installed the Edge build and cannot repo the problem now. I even tried running WebX 1st.
