### ISSUE TITLE
Services are not able to access some times 

### ISSUE THREAD

**Issue by chennakesava1** [docker/for-win#4074]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:C2A7D829-2462-425D-9582-F725CBEA3B34/20190613145123

### Expected behavior
Server if running healthy no error logs from services should able to access. 
### Actual behavior
Services are showing healthy and not able to access and not found any error logs in services.
Below error logs from Docker for windows 
### Information

  - Windows Version:
[Host Name:                 NEURO-NOLIS-SER
OS Name:                   Microsoft Windows Server 2016 Standard
OS Version:                10.0.14393 N/A Build 14393](url)
  - Docker Desktop Version:
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false

### Steps to reproduce the behavior

Error logs 
VpnKit         ][Error  ] vpnkit.exe: Socket.tcp:161.85.29.30:64696.write TCPv4: caught An established connection was aborted by the software in your host machine.
[Error  ] vpnkit.exe: tcp:0.0.0.0:443:tcp:172.18.0.11:443 proxy failed with flow proxy a: attempted to write to a closed flow

[12:42:58.498][VpnKit         ][Error  ] vpnkit.exe: Socket.tcp:161.85.29.30:64755.write TCPv4: caught An established connection was aborted by the software in your host machine.
][Error  ] vpnkit.exe: tcp:0.0.0.0:443:tcp:172.18.0.11:443 proxy failed with flow proxy a: attempted to write to a closed flow

[12:43:49.267][VpnKit         ][Error  ] vpnkit.exe: Socket.tcp:161.85.29.30:65177.write TCPv4: caught An established connection was aborted by the software in your host machine.

[12:43:49.268][VpnKit         ][Info   ]  returning Eof

[12:43:49.268][VpnKit         ][Error  ] vpnkit.exe: tcp:0.0.0.0:443:tcp:172.18.0.11:443 proxy failed with flow proxy a: attempted to write to a closed flow

[12:43:58.967][VpnKit         ][Info   ] vpnkit.exe: Connected Ethernet interface f6:16:36:bc:f9:c6

[12:43:58.967][VpnKit         ][Info   ] vpnkit.exe: UDP interface connected on 161.85.29.22

[12:47:55.138][VpnKit         ][Error  ] vpnkit.exe: Socket.UDPv4.read: udp -> 130.139.56.140:53 caught Lwt.Resolution_loop.Canceled returning Eof

[12:49:00.260][VpnKit         ][Error  ] vpnkit.exe: Socket.tcp:161.85.29.30:50555.write TCPv4: caught An established connection was aborted by the software in your host machine.

[12:49:00.260][VpnKit         ][Info   ]  returning Eof

[12:49:00.260][VpnKit         ][Error  ] vpnkit.exe: tcp:0.0.0.0:443:tcp:172.18.0.11:443 proxy failed with flow proxy a: attempted to write to a closed flow

[12:50:47.315][SegmentApi     ][Info   ] Usage statistic: heartbeat
[12:51:35.293][VpnKit         ][Error  ] vpnkit.exe: Socket.tcp:161.85.29.30:52029.write TCPv4: caught An established connection was aborted by the software in your host machine.

[12:51:35.293][VpnKit         ][Info   ]  returning Eof
  1. ...
  2. ...
```
C:\Users\Administrator\Documents\hardening\NOLIS-1.0.0>docker ps -a --format "table {{.Names}}\t{{.Status}}
NAMES                         STATUS
nolis-importer                Up 41 minutes
nolis-dicom-importer          Up 37 minutes
nolis-patient-management      Up 40 minutes
nolis-medication-management   Up 41 minutes
nolis-study-watcher           Up 38 minutes (healthy)
nolis-infra                   Up 40 minutes
nolis-task-management         Up 41 minutes
nolis-audit                   Up 40 minutes
apache2                       Up 43 minutes (healthy)
nolis-application-workflow    Up 38 minutes
nolis-visit-management        Up 40 minutes
rabbitmq                      Up 43 minutes (healthy)
configuration                 Up 41 minutes (healthy)
audit-service                 Up 41 minutes (healthy)
phoenix-cdr                   Up 41 minutes (healthy)
iam                           Up 41 minutes (healthy)
ems-service                   Up 41 minutes (healthy)
api-gateway                   Up 41 minutes (healthy)
config-server                 Up 43 minutes (healthy)
discovery                     Up 43 minutes (healthy)
kafka                         Up 43 minutes (healthy)
redis                         Up 43 minutes (healthy)
postgres                      Up 43 minutes (healthy)
ldap                          Up 43 minutes
filebeat                      Up 43 minutes (healthy)

C:\Users\Administrator\Documents\hardening\NOLIS-1.0.0>docker restart apache2
apache2

C:\Users\Administrator\Documents\hardening\NOLIS-1.0.0>
```

Memory CPU

```
CONTAINER ID        NAME                          CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
fc604793db66        nolis-importer                0.29%               337.5MiB / 8.987GiB   3.67%               88.7kB / 96.5kB     19.8MB / 0B         57
b0caf2646185        nolis-dicom-importer          0.23%               440MiB / 8.987GiB     4.78%               75.1kB / 85.2kB     65.9MB / 0B         47
5b727a4090dc        nolis-patient-management      0.20%               424.9MiB / 8.987GiB   4.62%               64.8kB / 73.8kB     28.4MB / 0B         45
6caef4b68318        nolis-medication-management   0.24%               413.8MiB / 8.987GiB   4.50%               67.9kB / 76.1kB     27.3MB / 0B         45
5cbea4403269        nolis-study-watcher           0.17%               424.8MiB / 8.987GiB   4.62%               75.5kB / 85.5kB     66.5MB / 0B         49
d83bde37b50f        nolis-infra                   0.23%               402.2MiB / 8.987GiB   4.37%               65.1kB / 71.8kB     22.3MB / 0B         45
4d42bae8f037        nolis-task-management         0.19%               407.1MiB / 8.987GiB   4.42%               67.1kB / 75kB       27.7MB / 0B         45
987f4d56a6c2        nolis-audit                   0.22%               400.4MiB / 8.987GiB   4.35%               66.3kB / 73.1kB     21.7MB / 0B         45
f34663c2662d        apache2                       0.14%               18.56MiB / 8.987GiB   0.20%               1.58kB / 0B         21.8MB / 7.52MB     58
06eeaa9b8a7b        nolis-application-workflow    0.25%               577.9MiB / 8.987GiB   6.28%               173kB / 156kB       210MB / 0B          58
51632e7a7f58        nolis-visit-management        0.26%               411.7MiB / 8.987GiB   4.47%               65.6kB / 73.5kB     36.1MB / 0B         45
fa2638db3b55        rabbitmq                      142.20%             108.4MiB / 8.987GiB   1.18%               18.9MB / 15.4MB     69.4MB / 455kB      166
196b397e48e1        configuration                 0.44%               416MiB / 8.987GiB     4.52%               1.98MB / 1.32MB     47.8MB / 12.3kB     48
de48fb303ed3        audit-service                 0.79%               447.1MiB / 8.987GiB   4.86%               4.51MB / 2.62MB     42.4MB / 0B         64
2e3135f6c9de        phoenix-cdr                   0.46%               452.5MiB / 8.987GiB   4.92%               2.03MB / 1.35MB     24.1MB / 0B         62
f4974bf20440        iam                           0.58%               486.4MiB / 8.987GiB   5.29%               2.21MB / 1.5MB      74.1MB / 0B         55
3a54a1f6ca2f        ems-service                   0.47%               438MiB / 8.987GiB     4.76%               2.03MB / 1.35MB     47.6MB / 0B         49
0f1c546d51fb        api-gateway                   0.47%               371.7MiB / 8.987GiB   4.04%               2.05MB / 1.37MB     36.7MB / 0B         51
03abb12694f9        config-server                 0.44%               183.6MiB / 8.987GiB   2.00%               2.33MB / 1.57MB     191MB / 0B          51
d93f5f0fd62c        discovery                     1.52%               261.1MiB / 8.987GiB   2.84%               1.15MB / 868kB      56.6MB / 0B         69
892e4b3cd052        kafka                         14.56%              351.2MiB / 8.987GiB   3.82%               10.1MB / 15.6MB     54.3MB / 2.85MB     99
834b43d4b322        redis                         0.19%               2.734MiB / 8.987GiB   0.03%               5.73kB / 0B         21.5MB / 102kB      6
a067710a25a2        postgres                      0.04%               70.09MiB / 8.987GiB   0.76%               369kB / 1.12MB      174MB / 17.7MB      37
caff05580b38        ldap                          0.00%               105MiB / 8.987GiB     1.14%               15.1kB / 4.96kB     13.3MB / 8.19kB     4
f75e16e4644f        filebeat                      0.03%               6.09MiB / 8.987GiB    0.07%               36.6kB / 25kB       23.8MB / 4.1kB      11
```

**Comment by mikeparker** [comment]
Can you be more specific about what the problem is, please?

**Comment by chennakesava1** [comment]
Services are showing running, up, healthy but not able to access once restarted the system it's able to access.

**Comment by chennakesava1** [comment]
@mikeparker, This kind of issue we are seeing in Docker for Windows version 18.09.X if we downgrade to Docker for Windows 18.06.X we are not seeing this issue intermediately.
