### ISSUE TITLE
Docker process tries named pipe connection to domain controller and super slow as result

### ISSUE THREAD

**Issue by artisticcheese** [docker/for-win#4078]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [X ] I have uploaded Diagnostics
  - Diagnostics ID: A5CFBABE-4A2E-4272-AAC6-247DB94C8904/20190613094427

### Expected behavior
Not having delay in docker operation

### Actual behavior
There is 20s delay as docker tries to connect to domain controller for some reason to authenticate

### Information

  - Windows Version:
1809
  - Docker Desktop Version:
2.0.0.3

### Steps to reproduce the behavior

Issuing `docker images` introduces 20s delay as docker process for some reason asks to authenticate to domain controller

![image](https://user-images.githubusercontent.com/13176884/59442208-60929580-8dbf-11e9-8a26-3928a7d69197.png)

```
PS C:\Users\174181> Get-NetTCPConnection -State SynSent

LocalAddress                        LocalPort RemoteAddress                       RemotePort State       AppliedSetting OwningProcess
------------                        --------- -------------                       ---------- -----       -------------- -------------
192.168.1.25                        55159     206.180.193.110                     445        SynSent     Internet       4
```

Here is API being called docker.exe

```
<Event MSec=  "7479.7281" PID="2752" PName=  "docker" TID="19988" EventName="FileIO/Create"
  TimeStamp="06/14/19 16:50:41.752798" ID="Illegal" Version="3" Keywords="0x00000000" TimeStampQPC="894,422,754,215" QPCTime="0.100us"
  Level="Always" ProviderName="Windows Kernel" ProviderGuid="9e814aad-3204-11d2-9a82-006008a86939" ClassicProvider="True" ProcessorNumber="3"
  Opcode="64" TaskGuid="90cbdc39-4a3e-11d1-84f4-0000f80464e3" Channel="0" PointerSize="8"
  CPU="3" EventIndex="113664" TemplateType="FileIOCreateTraceData">
  <PrettyPrint>
    <Event MSec=  "7479.7281" PID="2752" PName=  "docker" TID="19988" EventName="FileIO/Create" IrpPtr="0xFFFFE78D0C5CAAF8" FileObject="0xFFFFE78D0124F680" CreateOptions="NONE" CreateDispostion="CREATE_NEW" FileAttributes="0" ShareAccess="ReadWrite" FileName="\\AMERICAS\PIPE\samr"/>
  </PrettyPrint>
  <Payload Length="94">
       0:  f8 aa 5c  c 8d e7 ff ff | 80 f6 24  1 8d e7 ff ff   ..\..... ..$.....
      10:  14 4e  0  0  0  0  0  1 |  0  0  0  0  3  0  0  0   .N...... ........
      20:  5c  0 44  0 65  0 76  0 | 69  0 63  0 65  0 5c  0   \.D.e.v. i.c.e.\.
      30:  4d  0 75  0 70  0 5c  0 | 41  0 4d  0 45  0 52  0   M.u.p.\. A.M.E.R.
      40:  49  0 43  0 41  0 53  0 | 5c  0 50  0 49  0 50  0   I.C.A.S. \.P.I.P.
      50:  45  0 5c  0 73  0 61  0 | 6d  0 72  0  0  0         E.\.s.a. m.r...
  </Payload>
</Event>
```

**Comment by artisticcheese** [comment]
Apparently I'm not the only one
https://github.com/docker/for-win/issues/1936#issuecomment-382317146

**Comment by ViceIce** [comment]
This is still an issue, please do not close this 😕

**Comment by saligam** [comment]
Agreed, I am still seeing this issue!

**Comment by ajwoodall** [comment]
I also had the same issue with Docker Engine 19.03 for Windows Server 2019. It was getting stuck on establishing \\DOMAINNAME\pipe\samr connection for about 15s. Docker commands that ran immediately after the slow one were fast, but if left idle for another 15s or so the next Docker command is 15s slow again.

I was able to workaround this problem by adding a HOSTS file entry on the Docker host for DOMAINNAME. It didn't seem to matter if I mapped DOMAINNAME to domain controller IP or 127.0.0.1, either way it made the Docker commands execute much faster.

**Comment by viceice** [comment]
still a problem

**Comment by mrgeoffrich** [comment]
So I was seeing the same behavior. My domain controller is doing DNS as well, but for some other reason I had set my PC's DNS to use Google. I changed my DNS to point back to the Domain Controller and now all my commands run quickly again. Its like its trying to resolve the domain name and taking a very long time before it times out. Now that it can resolve it, docker ps runs quickly again.

**Comment by jsco2t** [comment]
/remove-lifecycle stale

We are still experiencing this issue as well. I understand it's not a critical bug - but it does make working with Docker Desktop on Windows very frustrating at times.

**Comment by kregerre** [comment]
I am having the same issue on windows 10 2004 with wsl 2 and docker 2.3.0.2.  Has anyone resolved this issue?
