### ISSUE TITLE
Startup error after updating to 1.13

### ISSUE THREAD

**Issue by dsech** [docker/for-win#408]
Windows 10 Pro, Hyper-V with MobyLinuxVM.
Had latest 1.12 version installed, on stable channel. 
Installed 1.13 after receiving the update notification.
Now, when starting, it crashes with error:

```
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Inconsistent parameters PolicyStore PersistentStore and Dhcp Enabled


   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

Diagnostic ID: 9F2F69FE-6E71-44CF-A43C-0E479A1D4628/2017-01-21_04-28-40

I've also uninstalled and reinstalled 1.13, but it throws the same error.

Also, the VM doesn't exist anymore in Hyper-V Manager, neither the virtual network in Network Connections.

Also, are older .msi packages still available for download anywhere? Couldn't find the 1.12 on the website.

**Comment by dsech** [comment]
All is working after rebooting windows.

**Comment by sameronline** [comment]
Got the same error today when i updated to, restarted windows and it seems to be working again.

Version 17.03.0-ce-win1 (10296)
Channel: stable
e5a07a1

**Comment by geoff-maddock** [comment]
I started having this issue after a recent update.   

If I reboot, docker starts, I can docker-compose up my containers and everything works ok.  But when I leave for the night, my machine goes to sleep, and when I wake it back up, log in, the container has crashed and trying to communicate says:

```
PS C:\Users\geoff.maddock\PhpstormProjects\cadence> docker ps
Error response from daemon: The requested address is not valid in its context.
```

If close and restart docker, it fails and reports the exact same error as in the original post in this issue.

```
PS C:\Users\geoff.maddock\PhpstormProjects\cadence> docker version
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:22 2017
 OS/Arch:       windows/amd64
Error response from daemon: The requested address is not valid in its context.
```
