### ISSUE TITLE
The Docker not start successfully

### ISSUE THREAD

**Issue by ruizhi6666** [docker/for-win#4080]
### Expected behavior
The error not occur.
### Actual behavior
When open the software, An error occured.
Unable to create: 已停止该运行的命令，因为首选项变量“ErrorActionPreference”或通用参数设置为 Stop: 由于找不到某个对象，Hyper-V 尝试在计算机“CAIRZ1-PF10GSLC”上访问该对象时遇到错误。请验证该计算机上的虚拟机管理服务是否正在运行。
在 New-Switch、<无文件> 中: 第 121 行
在 <ScriptBlock>、<无文件> 中: 第 411 行
   在 Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) 位置 C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:行号 36
   在 Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) 位置 C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:行号 92
   在 Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() 位置 C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:行号 74
   在 Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() 位置 C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:行号 59

### Information

  - Windows Version: win10.0.17763.557
  - Docker Desktop Version:
Version 2.0.0.3 (31259)
Channel: stable
Build: 8858db3

### Steps to reproduce the behavior
open the application of Docker, then error occur. the issue 100% reproduced.

**Comment by martin-zheng** [comment]
same issue, any solution?

**Comment by niranjanasu** [comment]
Same issue for me.  I have tried to uninstall and reinstall.  Still the same issue.

**Comment by woshiquange** [comment]
same issue too， have you fixed this problem?

**Comment by niranjanasu** [comment]
Here is what I did: In mobilinux.ps1 file, there was a ErrorActionPreference which was set to Stop.  I changed it to SilentlyContinue.  After that mobilinux was created and everything seems to be working ok.  I verified that the DockerNat was created.

**Comment by zhangqianYY** [comment]
hi，Where is mobilinux.ps1 @niranjanasu ，i can not find it！！

**Comment by niranjanasu** [comment]
> 
> 
> hi，Where is mobilinux.ps1 @niranjanasu ，i can not find it！！

In my system, it was in - C:\Program Files\Docker\Docker\resources
