### ISSUE TITLE
Can't log in to Docker GUI

### ISSUE THREAD

**Issue by smeierhofer** [docker/for-win#4086]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
I expect to be able to log in via the Docker Desktop GUI.

### Actual behavior
I get red highlighting that shows that my username/password isn't correct.

### Information
I cannot log into Docker Desktop using GUI. I have verified that I can log in to both cloud.docker.com and hub.docker.com on the web using my Docker ID. I do not have the proxy enable.

This problem is showing up now after I did a Reset of Docker Desktop to factoring installed settings, which forced me to log in again.

  - Windows Version: Windows 10 build 1809 (OS Build 17763.503)
  - Docker Desktop Version: Stable 2.0.0.3 (31259)

### Steps to reproduce the behavior

1. Use Docker Desktop to login
2. Enter Docker ID and password
3. Click login

**Comment by markCoreGaming** [comment]
Running `docker login` command in CMD to login and rebooting Docker Desktop fixed this for me

**Comment by smeierhofer** [comment]
I didn't do anything different but it seems to work now.

**Comment by samciot** [comment]
This problem persists however.  The workaround - of logging in via terminal `docker login` command works, but does not resolve the problem.  Also remember that when logging in via the terminal and you have 2FA activated, use the Personal Access Token to login.  If you've lost this, generate a new one using docker.com web access.
