### ISSUE TITLE
[Feature] GPU utilization with WSL2 

### ISSUE THREAD

**Issue by pavlkara1** [docker/for-win#4091]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

This is mostly a feature request rather than a bug. As mentioned in the engineering blog post (https://engineering.docker.com/2019/06/docker-hearts-wsl-2/), you are moving away from the light-weight VM you were using to run Docker on windows, and instead use WSL 2 that Microsoft has announced. This is as close to native Linux as windows has ever been. Does this mean that we will be able to utilize our GPU in GPU-dependent workflows, as PyTorch or Tensorflow? If this irrelevant to this repo, can you get back to me with more info on the upcoming version that will use WSL?

**Comment by simonferquel** [comment]
GPU access within WSL2 will probably not land for WSL 2 first release, so we can't support it in Docker Desktop either. 
As it is a very frequent request, I guess they will work on it pretty soon. Care to answer @benhillis ?
