### ISSUE TITLE
Docker containers status is healthy but containers are not reachable. 

### ISSUE THREAD

**Issue by pejathayaS** [docker/for-win#4093]
### Expected behavior
Docker Containers expected to work fine and be responsive.
### Actual behavior
We are having an issue of unresponsive docker containers after a couple of hours or days. Restarting containers doesn’t help and restarting docker engine does. 
### Information

    Windows Version:
    OS Name: Microsoft Windows Server 2016 Standard
    OS Version: 10.0.14393 N/A Build 14393
    Docker for Windows Version:
    Client: Docker Engine - Community
    Version: 18.09.2
    API version: 1.39
    Go version: go1.10.8
    Git commit: 6247962
    Built: Sun Feb 10 04:12:31 2019
    OS/Arch: windows/amd64
    Experimental: false

Server: Docker Engine - Community
Engine:
Version: 18.09.2
API version: 1.39 (minimum version 1.12)
Go version: go1.10.6
Git commit: 6247962
Built: Sun Feb 10 04:13:06 2019
OS/Arch: linux/amd64
Experimental: false

I am running around 20 containers ; apache2, kafka, rabbitmq, CDR, Eureka, few JAVA microservices which interact each other. 
Checking the status of the logs using docker ps returns healthy response, but not able to reach the containers and the container logs also seems to be Okay.

The memory of the system and the cpu usage seems to be fine and doesn’t look to exceed the avg usage.

Below are the logs I have from the sytem.

Version: 2.0.0.0-win81 (29211)
Channel: stable
Sha1: 4271b9e6a880dcc505d3d7726a4e158c6bb558de
Started on: 2019/06/12 08:31:42.479
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1803
Build: 17134
BuildLabName: 17134.1.amd64fre.rs4_release.180410-1804
File: C:\Users\320045501\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[00:31:42.633][SegmentApi     ][Info   ] Usage statistic: heartbeat
[01:07:41.346][VpnKit         ][Error  ] vpnkit.exe: Socket.UDPv4.read: udp -> 130.140.80.134:53 caught Lwt.Resolution_loop.Canceled returning Eof

[01:15:49.740][VpnKit         ][Error  ] vpnkit.exe: Socket.UDPv4.read: udp -> 130.140.80.134:53 caught Lwt.Resolution_loop.Canceled returning Eof

[01:22:36.656][VpnKit         ][Error  ] vpnkit.exe: Socket.UDPv4.read: udp -> 130.140.80.134:53 caught Lwt.Resolution_loop.Canceled returning Eof

[01:22:36.656][VpnKit         ][Error  ] vpnkit.exe: Socket.UDPv4.read: udp -> 167.81.253.193:53 caught Lwt.Resolution_loop.Canceled returning Eof

[01:22:36.658][VpnKit         ][Error  ] vpnkit.exe: Socket.UDPv4.read: udp -> 130.140.80.134:53 caught Lwt.Resolution_loop.Canceled returning Eof

[01:22:36.658][VpnKit         ][Error  ] vpnkit.exe: Socket.UDPv4.read: udp -> 167.81.253.193:53 caught Lwt.Resolution_loop.Canceled returning Eof

### Steps to reproduce the behavior
There is no particular reproduce-able steps as such. It is random in nature as containers suddenly stops responding. 
The same application deployment on a Linux machine seems to be working fine as the issue is not seen for more than 3 weeks now. 

Is there a known issue with docker on windows  ?

**Comment by stephanecot** [comment]
Hello, I have the same problem since a week but my config has not changed.
I have a new computer this week end with a fresh install and I have the same problem

I am running on windows 10 19.03

**Comment by slavakos** [comment]
I've got a somewhat similar problem.
Diagnostics ID: C26F2771-4D81-4D25-AFA4-AD4FB1DE46EB/20190802055625
### Information
All containers on a physical machine running win10 are showing as "healthy" and up for more than 24 hours while they are unreachable and cannot be stopped/restarted/killed.
I have restarted docker, rebooted the host machine with no effect and the containers' uptime was not reset.

  - Windows Version: Win10
  - Docker Desktop Version: 2.1.0.0

**Comment by theperm** [comment]
Same here. After rebootwindows desktop machine container reports as healthy and up 11 days. Impossible as it should be in the not started state after a reboot. Cant start or stop it or remove it now.
Diagnostic ID: 12156C36-1B49-4E63-BF60-A62B34A400A3/20190827153044

**Comment by prc0mputing** [comment]
This issue happend same as it did for @pejathayaS for my server.  I'm running my docker stacks on Windows Server 2016 (1607) through hyper-V VM and Docker Desktop 2.0.0.3 (31259)
The docker service seems to work properly but infact it's not responding at all. The only way to coming off is restarting the docker service.
