### ISSUE TITLE
Docker Desktop does not start on Windows 10

### ISSUE THREAD

**Issue by mmehta4-northwell** [docker/for-win#4111]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ChanaLii** [comment]
docker must run in "win10 perfessional version" or"win10 enterprise version"

**Comment by mmehta4-northwell** [comment]
I am running Windows 10 Professional version.  That was not the problem.  In addition to listed configuration I had to turn on 'Virtual Machine Platform' feature and change Windows security setting to 'Override system settings'.
