### ISSUE TITLE
Docker taskbar icon is not consistent with new Windows 10 themes

### ISSUE THREAD

**Issue by brunofin** [docker/for-win#4113]
With the release of the new Windows 10 light theme, the current Docker for windows taskbar icon is no longer consistent with Windows' look & feel.

While all the other icons can pick up when the theme changes from Light to Dark and switch their colors from black to white, Docker remains white on a bright background, making it hard to see and overall inconsistent with the UI.

![image](https://user-images.githubusercontent.com/8077237/59908143-fc01b700-940c-11e9-9251-c18608bd38b2.png)

On another note, I though Docker for Windows was open source? This would be something anyone could easily fix, even I would proceed to create a PR after posting this issue...

**Comment by stephen-turner** [comment]
Thanks for reporting it @brunofin, we will fix it.

No, Docker for Windows has never been open source.

**Comment by brunofin** [comment]
Thanks for the info and thanks for clarifying. I don't know why I always had the impression it was open source :)

**Comment by thaJeztah** [comment]
It contains many open-source components (Docker Engine, Docker CLI, LinuxKit, VPNKit etc), but other parts are not open source.

Thanks for reporting!

**Comment by brunofin** [comment]
Just to add some more info:

![image](https://user-images.githubusercontent.com/8077237/59917711-f1eab300-9422-11e9-81f5-c7f901112395.png)

**Comment by xxxzsx** [comment]
still needed

**Comment by ciolansteen** [comment]
we need this so much. it's so annoying to know where  Docker Desktop app is in the taskbar by "where the big gap" is :)

**Comment by niteshrestha** [comment]
Over a year later do we have any update?

**Comment by stephen-turner** [comment]
Yes, we have fixed it in our internal builds, it just hasn't made it into a release yet.

**Comment by stephen-turner** [comment]
I'm pleased to report this is fixed in our latest Edge release, 2.3.5.0. Apologies for the delay!

**Comment by djs55** [comment]
The fix for this has now been released in [2.4.0.0 stable](https://desktop.docker.com/win/stable/48506/Docker%20Desktop%20Installer.exe).
