### ISSUE TITLE
Network drive connection loop on shares setup

### ISSUE THREAD

**Issue by sebastienfr** [docker/for-win#4118]
- [x] I have tried with the latest version of my channel (Stable or Edge) => stable
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 5956CAE8-12D2-424A-9CCD-439AA11F2484/20190620164049

### Expected behavior

The number of connections to a local NAS stays stable when setting up shared volumes on docker 4 win UI.

### Information

After setting up docker for Windows on Windows 10 with a 2 partitions disk (C and D drive), when enabling local volume mount (checking D drive in UI), user is asked about his credentials to scan network drives. Then the number of connections to local NAS through network drives increases by 1000 to 2000 in a few minutes and finally crashes the company NAS.

The problem does not appear with Docker Machine.

No docker container execution is needed, only the setup from the UI make this behaviour appear.

Maybe a company network restriction on the laptop is involved but it looks like the UI is looping over and over network drives.

![image002](https://user-images.githubusercontent.com/5099537/59915420-e2686b80-941c-11e9-9d1e-60bc31d00179.jpg)

**Comment by sebastienfr** [comment]
Hello, 

Has no one encountered such an issue ? Is there a way to have access to the source code to see what happens ? Regards.

**Comment by solvingj** [comment]
Just another user here, but I will have my team check to see if we see the same issue with our shared network drives.

**Comment by sebastienfr** [comment]
Thanks for your help. We have hundreds of people working here, using another host as a proxy is not really an option 😅but thanks for the tip.

**Comment by solvingj** [comment]
I only meant on your machine as a test. This project is still in an early state where users like yourself are likely to come across random protocol compatibility issues with specific vendor appliances like NAS, and the dev team here is unlikely to be able to reproduce your issue.

**Comment by sebastienfr** [comment]
Hello,

I expected some improvement after last september release. It looks better for fresh installed laptops, but it's still a mess even after update for existing installation.
I'll confirme after some days running the it's ok with this new release.
