### ISSUE TITLE
运行停止

### ISSUE THREAD

**Issue by MSG-maniac** [docker/for-win#4122]
Unable to create: 已停止该运行的命令，因为首选项变量“ErrorActionPreference”或通用参数设置为 Stop: 无法新建虚拟机。

“MobyLinuxVM”无法实现。
在 New-MobyLinuxVM、<无文件> 中: 第 191 行
在 <ScriptBlock>、<无文件> 中: 第 411 行
   在 Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) 位置 C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:行号 36
   在 Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) 位置 C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:行号 92
   在 Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() 位置 C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:行号 74
   在 Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() 位置 C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:行号 59

**Comment by starrysky1211** [comment]
The same problem
