### ISSUE TITLE
Docker auto starting on windows even if option disabled.

### ISSUE THREAD

**Issue by bvalat** [docker/for-win#4123]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D87D0CFD-0B29-4E15-862C-7C4ADA989FD7/20190622204140

### Expected behavior
Docker not starting with my computer on longon
### Actual behavior
Docker start with my computer even if i disabled the  "Start Docker Desktop when you log in"
### Information

  - Windows Version: WIN 10 PRO 1809
  - Docker Desktop Version:
Version 2.0.0.3 (31259)
Channel: stable
Build: 8858db3

### Steps to reproduce the behavior

  1. Loging in my win 10 pro computer
  2. Docker start

**Comment by bvalat** [comment]
Still have the problem with 4.2.1.
Tried gdb. The tools refuse to load the exe : not in executable format: File format not recognized.  Will try running from source.

**Comment by mlocati** [comment]
I experience this same issue.

Even if the "Start Docker Desktop when you login" option is not checked, docker keeps starting every time I power on my PC.
That's because of this regedit entry:

![image](https://user-images.githubusercontent.com/928116/69220751-fe13a180-0b75-11ea-8d15-684ed3f39ebe.png)

The application should delete this entry when the option is not checked.

**Comment by mat007** [comment]
@mlocati what’s the Docker Desktop version you’re running?
Can you tell us what’s the output for the following Powershell command?
```
 Get-Item -path HKLM:SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\StartupApproved\Run
```

Thanks!

**Comment by mlocati** [comment]
@mat007 I just tried to update Docker Desktop to the very latest version (`2.1.0.5 (40693)`) and this issue seems to be fixed now. It must be something that has been fixed in very recent versions, since I usually update Docker for Windows quite often.

Sorry for the hassle...

**Comment by mat007** [comment]
OK, no worries, glad it’s working for you now.

**Comment by joshco** [comment]
See @cdalexndr 's fix, which worked for me
https://github.com/docker/for-win/issues/5246#issuecomment-559750374
