### ISSUE TITLE
Reclaimable space value has wrong format

### ISSUE THREAD

**Issue by Deathofdemigod** [docker/for-win#413]
### Expected behavior
Reclaimable space in readable format.

### Actual behavior

PS C:\WINDOWS\system32> docker system df
TYPE                TOTAL               ACTIVE              SIZE                RECLAIMABLE
Images              13                  10                  15.65 GB            -4.752e+10 B (-303%)
Containers          14                  0                   0 B                 0 B
Local Volumes       0                   0                   0 B                 0 B
PS C:\WINDOWS\system32>

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

A diagnostic was uploaded with id: 3071BE33-3E80-4065-894F-DFA3B436841C/2017-01-23_09-00-51

Win 10 Enterprise v 1607 build 14393.223
64Gb of Ram.

### Steps to reproduce the behavior

  1.  open powershell as adm
  2. run "docker system df"

**Comment by dgageot** [comment]
Thanks @Deathofdemigod for the report. Could you report this issue on docker/docker? This is not something that can be fixed in Docker for Windows, so I'm going to close this one. Thanks again!
