### ISSUE TITLE
Docker can't start windows 10 on ESXI

### ISSUE THREAD

**Issue by kk88** [docker/for-win#4132]
- [X] I have tried with the latest version of my channel (Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: BC1BA1F4-3D16-4039-B10A-25ADF13258A9/20190624194010

When starting Docker it stucks and then I get the error message:
```
Timed out waiting for the lifecycle-server to start
   bei Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   bei Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   bei Docker.Actions.<>c__DisplayClass23_0.<Start>b__0()
   bei Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1()
```

  - Windows Version: Windows 10 Enterprise 1803 on ESXI Host
  - Docker Desktop Version: 2.0.5.0 (Edge)

**Comment by MuwuM** [comment]
Same issue here on Windows 10 without ESXI 

Resetting to factory default let's me start docker again, but all containers are lost.
