### ISSUE TITLE
chdir to cwd: permission denied

### ISSUE THREAD

**Issue by rmorrise** [docker/for-win#4133]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

From windows `cmd`:
`docker exec -u 0 -it --workdir /home/oracle buildDb bash`

Since I'm executing as root, it should go into the directory.

### Actual behavior

`OCI runtime exec failed: exec failed: container_linux.go:344: starting container process caused "chdir to cwd (\"/home/oracle\") set in config.json failed: permission denied": unknown`

### Information

The following commands work as expected. You can see the permissions of the destination folder in the output below:
```
C:\>docker exec -u 0 -it --workdir /home buildDb bash
bash-4.2# ls -ltr
total 4
drwx------ 1 oracle oinstall 4096 Jun 24 19:46 oracle
bash-4.2# cd oracle/
bash-4.2#
```

This is my first time using docker since upgrading to Windows 10, so I don't know if the problem existed previously. I didn't encounter this issue with `docker-machine` in windows 7, but it's been about a year since I worked on it last.

  - Windows Version: Windows 10 Enterprise
  - Docker Desktop Version: 2.0.0.3 (31259), stable channel

### Steps to reproduce the behavior

Building the image that this container is running takes some manual steps:

1. Clone this repo: http://github.com/rmorrise/docker-images
2. `cd` into `OracleDatabase/SingleInstance/dockerfiles`
3. Download the Oracle database installer (v12.2.0.1 linux x64) from Oracle: https://www.oracle.com/technetwork/database/enterprise-edition/downloads/oracle12c-linux-12201-3608234.html
4. Place the installer ZIP file (still zipped) in the `12.2.0.1` directory of your checkout
5. `./buildDockerImage.sh -e -v 12.2.0.1`

This will build the image. Then:
6. `docker run -d --name buildDb -p 1521:1521 rmorrise/oracle/database-novol:12.2.0.1-ee`

And reproduce the issue:
7. `docker exec -u 0 -it --workdir /home/oracle buildDb bash`

**Comment by rmorrise** [comment]
Aside: I just installed Docker Desktop last week, so I'm assuming it's the latest version. Nothing happens when I pick "Check for Updates" from the system tray menu, so I don't know if there are no updates or if the updater is blocked by our corporate proxy.

**Comment by dreamesee** [comment]
I fixed a problem that appears identical with an equivalent:  chmod 755 /home/oracle

I speculate that even though Docker is running as root _within docker_, the reality is that it is some entity/user that is neither the /home user, nor the 'host root'.
