### ISSUE TITLE
Failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running.

### ISSUE THREAD

**Issue by mansing2** [docker/for-win#4138]
I have tried with the latest version of my channel (Stable or Edge)
I have uploaded Diagnostics
Diagnostics ID: EAA39775-3736-4C08-BBF6-D00D8E51C632/20190626091314

**Expected behavior**
After installing Docker desktop the service is expected to up and running and should let allow pulling images and build containers. 

 **Actual behavior**
It is giving an error while restarting the Docker service. Error is "Failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running." 
Hyper-v service is enabled on the windows server.

When we manually restart the Docker from the system tray it starts but given below error when trying to pull an image.

```error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/images/create?fromImage=centos&tag=latest: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.```

**Information**
I have T3.xLarge instance with OS as Windows Server 2019 on AWS cloud platform.

**Steps to reproduce the behavior**
1. Install Docker for windows either using https://docs.docker.com/v17.09/docker-for-windows/install/  or https://hub.docker.com/editions/community/docker-ce-desktop-windows
2. After installation gets finishes Docker try to start the service and fails.

**Comment by mansing2** [comment]
has anybody faced this issue? any idea? is this the limitation of running Docker Desktop on Windows Server?

**Comment by jdj333** [comment]
From AWS support: "Unfortunately running Hyper-V or any other hypervisor on top of an EC2 instance is not supported."

You probably need to use a windows based ECS or EKS based service in order to deploy windows containers to AWS.

References:
http://cloudstacking.com/posts/running-hyper-v-vmware-or-xen-on-an-aws-ec2-instance.html
https://forums.aws.amazon.com/message.jspa?messageID=755831
