### ISSUE TITLE
F1-F4 keys do not work in Far Manager inside Docker terminal opened in ConEmu

### ISSUE THREAD

**Issue by dermeister0** [docker/for-win#414]
F1-F4 keys do not work in Far Manager inside Docker terminal opened in ConEmu

### Expected behavior

F1-F12 keys work in Docker terminal under ConEmu.

### Actual behavior

F5-F12 keys work in ConEmu.
F1-F12 keys work in real console.

### Information

Diagnostic ID: F0A02330-1871-4BFD-83F8-86402B74876B/2017-01-23_18-30-41
OS: Windows 10 Pro (EN)
OS version: 10.0.14393
Docker version: 1.13.0-rc5, build 43cc971

### Steps to reproduce the behavior

1. Install Docker for Windows.
2. Save the attached Dockerfile.txt file, rename it to Dockerfile.
3. Build image: docker build -t fartest:latest .
4. Run the image: docker run --rm -it fartest
5. Test F1-F12 keys in Far.
6. Detach console (Ctrl+Win+Alt+Space).
7. Test F1-F12 keys in real console.

### Notes

ConEmu has full ANSI terminal support and it works correctly. Several issues related to ConEmu are fixed already. I'm sure it's a bug of Docker, not ConEmu.

https://github.com/docker/docker/commits/master/pkg/term/term_windows.go

[Dockerfile.txt](https://github.com/docker/for-win/files/723442/Dockerfile.txt)

**Comment by dermeister0** [comment]
https://github.com/docker/docker/issues/27389

**Comment by dgageot** [comment]
@dermeister0 Can you make sure docker/docker#27389 describes your issue or create another issue on docker/docker? I'm going to close this ticket here because it's not something that can be fixed by Docker for Windows. Thanks a lot!
