### ISSUE TITLE
MobyLinux VM takes a long time to boot

### ISSUE THREAD

**Issue by tmpvar** [docker/for-win#416]
### Expected behavior

Docker runs

### Actual behavior

Docker fails with the following error

```
Docker hv-sock proxy (vsudd) is not reachable
   at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```
#### Diagnostic IDs
 - Stable (1.13.0) - 246AC402-739A-42BE-A040-2E718383F233/2017-01-23_08-15-39
 - Beta (1.13.0-beta38) - 246AC402-739A-42BE-A040-2E718383F233/2017-01-23_08-31-13

#### System Information

Windows 10 Pro running on an i7-5960X

```
PS C:\WINDOWS\system32> $PSVersionTable.BuildVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      14393  693
```

### Steps to reproduce the behavior

  1. install fresh either the stable (Version 1.13.0 (9795))
 or beta (1.13.0-beta38) version of docker for win
  2. attempt to launch docker for win
  3. after ~2 minutes an error dialog appears

**Comment by earlcherry** [comment]
the same problem

**Comment by dgageot** [comment]
Closing as it's a duplicate of #406

**Comment by tmpvar** [comment]
#406 has been closed, but things are still broken on my end.

I've tried using the latest docker, both stable and beta channels, and have installed all available windows updates.

**Comment by ups216** [comment]
@tmpvar did you restart your system after install all update? and if still not, install KB3213986. One of my client had the same issue and the kb fixed it.

**Comment by tmpvar** [comment]
Yeah, I've been keeping up on all the windows updates and am on the docker for win beta channel (currently Version 1.13.1-beta42 (10069)) and the issue persists

![update-status](https://cloud.githubusercontent.com/assets/46673/22909352/96acb9d4-f221-11e6-92b3-c48f396cfa91.png)

I shutdown my windows box daily, and on every boot 2 minutes later I get the docker error described in the OP

**Comment by rneugeba** [comment]
@tmpvar I re-open the issue since this is not a dup of #406. It looks like an entirely different issue. I've changed the title to better reflect what's going on

We start a Linux VM in Hyper-V as part of the application start. On normal systems this VM boots in ~10s. We check in the application if the VM was started. We have a timeout of 60s. From your logs the VMs doesn't even get half way through the kernel boot, nevermind the userspace and other bits and pieces.

This is quite odd give that you seem to have a quite fast machine with lots of memory. Do you have a high CPU load or memory pressure?

**Comment by friism** [comment]
Closing this since @tmpvar didn't follow up with details.

**Comment by tmpvar** [comment]
Fair enough, I guess this is a system level problem?

**Comment by friism** [comment]
@tmpvar It's hard to say. It'd be useful to learn of Hyper-V otherwise works normally for you.

For example, you could try to create boot2docker vms using the hyper-v driver as described here: https://github.com/docker/labs/tree/master/swarm-mode/beginner-tutorial#creating-the-nodes-and-swarm

**Comment by tmpvar** [comment]
I was able to run the following
<details>
<summary>docker-machine create -d hyperv manager</summary>

```
PS D:\work\labs\swarm-mode\beginner-tutorial> docker-machine create -d hyperv manager
Running pre-create checks...
(manager) Image cache directory does not exist, creating it at C:\Users\tmpvar\.docker\machine\cache...
(manager) No default Boot2Docker ISO found locally, downloading the latest release...
(manager) Latest release for github.com/boot2docker/boot2docker is v17.03.0-ce
(manager) Downloading C:\Users\tmpvar\.docker\machine\cache\boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v17.03.0-ce/boot2docker.iso...
(manager) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
Creating machine...
(manager) Copying C:\Users\tmpvar\.docker\machine\cache\boot2docker.iso to C:\Users\tmpvar\.docker\machine\machines\manager\boot2docker.iso...
(manager) Creating SSH key...
(manager) Creating VM...
(manager) Using switch "external"
(manager) Creating VHD
(manager) Starting VM...
(manager) Waiting for host to start...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: C:\Program Files\Docker\Docker\Resources\bin\docker-machine.exe env manager
```
</details>

`(manager) Waiting for host to start...` took quite a while to complete

However, when I run the ps1 included in the repo you linked it bombs out:
<details>
<summary>D:\work\labs\swarm-mode\beginner-tutorial> .\swarm-node-hyperv-setup.ps1</summary>

```
PS D:\work\labs\swarm-mode\beginner-tutorial> .\swarm-node-hyperv-setup.ps1
======> Creating manager machines ...
======> Creating manager1 machine ...
Running pre-create checks...
Error with pre-create check: "vswitch \"New Virtual Switch\" not found"
======> Creating manager2 machine ...
Running pre-create checks...
Error with pre-create check: "vswitch \"New Virtual Switch\" not found"
======> Creating manager3 machine ...
Running pre-create checks...
Error with pre-create check: "vswitch \"New Virtual Switch\" not found"
======> Creating worker machines ...
======> Creating worker1 machine ...
Running pre-create checks...
Error with pre-create check: "vswitch \"New Virtual Switch\" not found"
======> Creating worker2 machine ...
Running pre-create checks...
Error with pre-create check: "vswitch \"New Virtual Switch\" not found"
======> Creating worker3 machine ...
Running pre-create checks...
Error with pre-create check: "vswitch \"New Virtual Switch\" not found"
NAME      ACTIVE   DRIVER   STATE     URL                    SWARM   DOCKER        ERRORS
manager   -        hyperv   Running   tcp://10.0.1.22:2376           v17.03.0-ce
======> Initializing first swarm manager ...
Host does not exist: "manager1"
Host does not exist: "manager1"
Host does not exist: "manager1"
Host does not exist: "manager1"
======> manager2 joining swarm as manager ...
Host does not exist: "manager2"
Host does not exist: "manager2"
======> manager3 joining swarm as manager ...
Host does not exist: "manager3"
Host does not exist: "manager3"
Host does not exist: "manager1"
======> worker1 joining swarm as worker ...
Host does not exist: "worker1"
Host does not exist: "worker1"
======> worker2 joining swarm as worker ...
Host does not exist: "worker2"
Host does not exist: "worker2"
======> worker3 joining swarm as worker ...
Host does not exist: "worker3"
Host does not exist: "worker3"
Host does not exist: "manager1"
```
</details>

**Comment by tmpvar** [comment]
apparently this was due to windows power management settings and a bug in the oculus 🙄 - https://www.andrewmunsell.com/blog/oculus-rift-bug-power-plan-configuration/

I literally reset the defaults on the balanced plan and restarted docker. Works like a charm.

Thanks for your patience!

**Comment by akitafuki** [comment]
@tmpvar Thank you for your diligence.  I can confirm this worked for me.  

I was experiencing a similar situation where my Samsung Magician software created a new High Performance profile under power management.  I changed it back to Balanced and it worked like a charm. 

For clarity, I am using Docker for Windows 17.03.1-ce-win12 (12058) under Windows 10 Pro.
