### ISSUE TITLE
Unable to create: The object already exists

### ISSUE THREAD

**Issue by kristopher-d** [docker/for-win#417]
### Expected behavior
Docker starts
### Actual behavior
Docker Fails to start
### Information
Diagnostic 628E11F1-55C2-42EF-B589-CB9259407C2C/2017-01-23_10-02-03 uploaded

Windows 10 Pro
Version 1607
Build 14393.693

### Steps to reproduce the behavior
Attempt to start Docker for Win.

**Comment by gh0st** [comment]
Same problem.

**Comment by dgageot** [comment]
@kristopher-d You are currently using version 1.12.6 on Stable channel. Can you update to the latest version and tell us if it's better?

**Comment by dgageot** [comment]
Sorry, in fact you updated to 1.13. Let me check again...

**Comment by dgageot** [comment]
@kristopher-d Is it possible for you to Reset to Factory defaults?

**Comment by dgageot** [comment]
@kristopher-d any chance you could try?

**Comment by gh0st** [comment]
@dgageot for me everything is greyed out in the settings menu.

**Comment by simonferquel** [comment]
Thanks for the report. The issue should have been fixed and this should make it in next beta (beta 41).
Please make sure to update to beta41 as soon as you get prompted for it.

**Comment by JonCubed** [comment]
I'm getting this error with beta 42

diagnostic id: 41560D0B-E5AF-41B4-94BD-0C90C899004C/2017-02-11_22-59-15

OS: Windows 10 Pro
Build: 14393

**Comment by JonCubed** [comment]
@simonferquel @simonferquel  @dgageot  any chance you have any suggestions on how to fix this?

**Comment by dgageot** [comment]
Sorry @JonCubed we don't have a fix yet. We'll keep you posted when we have.

**Comment by jasonbivins** [comment]
@JonCubed 

We're out of Beta now - can you try in one of the newer builds?

**Comment by JonCubed** [comment]
@jasonbivins I eventually fix this via a combination of uninstalling, deleting docker folders, running clean up scripts and reinstalling. Currently running on stable with no issues

**Comment by gh0st** [comment]
I’ll give it a try Monday morning. 

Chad Hollman
