### ISSUE TITLE
The "C" of copyright in "About Docker" window is cropped

### ISSUE THREAD

**Issue by apupier** [docker/for-win#4170]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
![image](https://user-images.githubusercontent.com/1105127/60573479-078f9f00-9d78-11e9-8d8a-eaa9fa304561.png)

### Information

  - Windows Version: 10
  - Docker Desktop Version: 2.0.0.3 (31259

### Steps to reproduce the behavior

  1. right-click on tray icon
  2. click on "About Docker desktop"

**Comment by thaJeztah** [comment]
Thanks for reporting; let me forward this to the Docker Desktop team

**Comment by thaJeztah** [comment]
I was informed that this issue is already fixed, but the fix is not yet in the stable channel 🤗

Let me close this issue for housekeeping, but thanks again for reporting; it's appreciated ❤️
