### ISSUE TITLE
Not able to start docker

### ISSUE THREAD

**Issue by rajesh-mundhe** [docker/for-win#4173]
- [ ] I have tried with the latest version of my channel (Stable)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 2B79DDB8-6208-4510-8EDD-03EB7FC19087/20190703161600

### Expected behavior
  To download the image and execute that image without any issue
### Actual behavior
  It should download the image and execute without any issue in docker 
### Information
It was running fine when I was working on Toolbox, recently updated to Windows 10 Pro and installed Docker for windows.
Issue Details:- 
PS C:\Personal\Projects\Docker\doodle\cheers2019> docker build -t ***********/cheers2019 .
ERRO[0000] failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: open //./pipe/docker_engine: The system cannot find the file specified.
error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=mwuqv6b19nia96i0z2qx182m1&shmsize=0&t=rajeshmundhe9%2Fcheers2019&target=&ulimits=null&version=1: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

  - Windows Version: 10 Pro
  - Docker Desktop Version:2.0.0.31259

### Steps to reproduce the behaviour

  1. ...
  2. ...

**Comment by ThaoThanhLuu** [comment]
You should check out over here. I was having the same issues until I switched daemon.

https://github.com/docker/for-win/issues/1825#issuecomment-433719346
