### ISSUE TITLE
Docker 1.13 ignores the host timezone

### ISSUE THREAD

**Issue by michaelva** [docker/for-win#418]
### Expected behavior

The time in containers should be the same as the host system. 

### Actual behavior

After upgrading to docker 1.13, the host time is synced as if it was a UTC time. The host timezone is not taken into account.

On the host:  Mon Jan 23 10:23:22 PST 2017
In the container: Mon Jan 23 2:23:22 PST 2017

### Information
  - host distribution and version: Windows 10 pro 10.0.14393 Build 14393
  - Docker 1.13

**Comment by justincormack** [comment]
I think this may be due to Windows setting the host clock with local time, but Linux expected UTC. May have to introduce a configured offset for Linux.

**Comment by mattmeye** [comment]
+1 ( see https://github.com/docker/docker/issues/30322 )

**Comment by rneugeba** [comment]
Maybe I'm missing something, but with Beta 39 I get the following:
```
PS C:\Users\docker> Get-TimeZone


Id                         : W. Europe Standard Time
DisplayName                : (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
StandardName               : W. Europe Standard Time
DaylightName               : W. Europe Daylight Time
BaseUtcOffset              : 01:00:00
SupportsDaylightSavingTime : True



PS C:\Users\docker> date

Thursday, January 26, 2017 14:23:52


PS C:\Users\docker> docker run --rm alpine date
Thu Jan 26 13:23:54 UTC 2017
PS C:\Users\docker> Get-TimeZone


Id                         : Eastern Standard Time
DisplayName                : (UTC-05:00) Eastern Time (US & Canada)
StandardName               : Eastern Standard Time
DaylightName               : Eastern Daylight Time
BaseUtcOffset              : -05:00:00
SupportsDaylightSavingTime : True



PS C:\Users\docker> date

Thursday, January 26, 2017 08:26:31


PS C:\Users\docker> docker run --rm alpine date
Thu Jan 26 13:26:34 UTC 2017
```
I changed timezones in between. The time in the container shows UTC correctly irrespective of the timezone setting of the host.

**Comment by michaelva** [comment]
Looks like it's because the time synchronization service is not activated by default when the MobyLinuxVm is created in Hyper-V. When activated, the time is correctly synchronized between the host and the containers.

However the MobyLinuxVm is deleted and recreated every time docker is restarted, which means that the time synchronization service must be manually reactivated after each restart.

**Comment by rneugeba** [comment]
@michaelva thanks for this additional information. This looks like a dup of https://github.com/docker/for-win/issues/409

@mattmeye could you check if the timesychronisation service is enabled?

**Comment by mattmeye** [comment]
@rneugeba timesychronisation is not enabled, can i enable this by default?

**Comment by rneugeba** [comment]
@mattmeye thanks for the confirmation. This looks like a dup of #409 so I'm closing it. I'll ping you and @michaelva  on #409 so that you get updates.
