### ISSUE TITLE
Docker on Windows crashing in swarm mode

### ISSUE THREAD

**Issue by megaloni** [docker/for-win#4183]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 7D2B799A-48F1-4DFA-9197-56666EB05E8F/20190705083552

### Expected behavior
Docker remains functional when in swarm mode on windows.

### Actual behavior
Joined a hybrid swarm (master is a linux node) on several Windows 10 machines. Docker is unstable on the windows nodes, crashing within a few minutes to a few hours after starting. Running `docker ps` on the Windows node receives the error: "Error response from daemon: Bad response from Docker engine"

### Information

  - Windows Version: Windows 10
  - Docker Desktop Version: 2.0.0.3 (31259)

### Steps to reproduce the behavior

  1. Create a hybrid swarm, Ubuntu linux node as the master
  2. Join the swarm with one or more Windows nodes
  3. Monitor the output of `docker node ls` - the windows nodes will go from Ready to Down
  4. Run `docker ps` on one of the Windows nodes, receive the error: "Error response from daemon: Bad response from Docker engine"

**Comment by umang-desai** [comment]
I am having the same issue. 
Once the worker machine joins the swarm group, docker stops responding on those machines. Any CLI request returns the response 

"Error response from daemon: Bad response from Docker engine"

The log is as follows:
[Logs](https://pastebin.com/KsP3mzXL)

**Comment by achrjulien** [comment]
Hi, same problem here.
Did you get this solved?
