### ISSUE TITLE
"Kubernetes is starting..." stuck

### ISSUE THREAD

**Issue by tolstenko** [docker/for-win#4185]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 50D02B2F-18C1-4C29-B4A6-0BF9301F1407/20190705173413

### Expected behavior
Kubernetes up
### Actual behavior
Got stuck on: `Kubernetes starting...`
### Information

  - Windows Version: Windows 10 Pro;
  - Docker Desktop Version: Version 2.0.0.3 (31259). Channel: stable. Build: 8858db3.

### Steps to reproduce the behavior

  1. Install Docker
  2. Enable Kubernetes
  3. Get stuck 

I am facing this same issue as this one: https://github.com/docker/for-win/issues/1649
I shutdown the windows firewall, deleted the pki folder, reset dhcp.json, added `127.0.0.1 localhost.localdomain` to hosts file and still, the logs shows: `Cannot list nodes: Get https://localhost:6445/api/v1/nodes: EOF`, 

![Screenshot_54](https://user-images.githubusercontent.com/2386417/60744108-c996a480-9f4a-11e9-9444-c612157b048a.png)

**Comment by Marusyk** [comment]
the same problem on two different PC

**Comment by m3l3m01t** [comment]
same error, reset to factory default, uninstall, delete everything, none work

**Comment by mmisztal1980** [comment]
same as in #4316

**Comment by Marusyk** [comment]
any news?

**Comment by NiGhMa** [comment]
Running on the same issue.... boring... I tried everything I found on the web and I keep getting the message : 
[16:43:51.725][ApiProxy          ][Error  ] time="2020-04-01T16:43:51-04:00" msg="Cannot list nodes: Get https://kubernetes.docker.internal:6443/api/v1/nodes: EOF"

**Comment by ericis** [comment]
**Workaround:** disable Kubernetes in Docker Desktop and run it separately through `minikube` instead.

1. Disable Kubernetes by modifying "%USERPROFILE%\AppData\Roaming\Docker\settings.json"
```
...
  "kubernetesEnabled": false,
  "showKubernetesSystemContainers": false,
  "kubernetesInitialInstallPerformed": false,
...
```

2. [Install `minikube`](https://kubernetes.io/docs/tasks/tools/install-minikube/) and start it to run Kubernetes
