### ISSUE TITLE
How to reset docker for win default NAT IP Address?

### ISSUE THREAD

**Issue by kkbruce** [docker/for-win#4201]
- [x] I have tried with the latest version of my channel (**Stable**)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `DDA59996-BFDE-4B43-AD48-7FEE9BC87268/20190708171408`

### Expected behavior

* Reset default NAT IP Address, like IPAM.Config.Subnet and Gateway.
or 
* Delete default NAT.

### Actual behavior

In order to comply with the company's anti-virus software **firewall** policy, we hope that the NAT network can be unified IP settings by the development host.

### Information

  - Windows Version: Microsoft Windows [version 10.0.17134.829]
  - Docker Desktop Version: 2.0.0.3

### Steps to reproduce the behavior

* Try `fixed-cidr` in daemon.json, unsuccessful.
* Try `docker network rm nat` unsuccessful. show `Error response from daemon: nat is a pre-defined network and cannot be removed`
* Try https://github.com/docker/for-win/issues/726 step, win 10 run `Get-NetNat` no any information, `Get-ContainerNetwork | Remove-ContainerNetwork` show no this commands.

**Comment by federicobarera** [comment]
up
