### ISSUE TITLE
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure  at New-Switch, <

### ISSUE THREAD

**Issue by ryoheimatsumo** [docker/for-win#4205]
Someone know how to solve this issue??

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by cordyline** [comment]
I am also receiving this issue on windows, started happening yesterday. Factory resetting docker did not help, nor did installing backlogged windows updates.
