### ISSUE TITLE
GetFileAttributesEx <src>: The system cannot find the path specified

### ISSUE THREAD

**Issue by minherz** [docker/for-win#421]
### Expected behavior
When building an image from a conventional Dockerfile on Windows 10 Enterprise x64 (build >=1607) the COPY command will work
### Actual behavior
The COPY command fails with a message:
'GetFileAttributesEx <src>: The system cannot find the path specified' where <src> is a file or a folder (with trailing \) of the existing file in a path which is the same to the location of the Dockerfile or a subdirectory of the Dockerfile location.
### Information

  - Diagnostic ID: F9F388E9-7AB0-4CE8-BD59-045CF28124A7/2017-01-24_16-03-51

Windows 10 x64 Enterprise Version 1607 (OS Build 1493.693)

### Steps to reproduce the behavior

  1. Create a work folder (e.g. C:\Work\DockerApp)
  2. Create a file `Dockerfile` with the following content (see attached)
  3. Place a .NET Core console application into a folder (e.g. C:\Work\DockerApp\bin)
  4. Run a command `docker build C:\Work\DockerApp\`
[Dockerfile.zip](https://github.com/docker/for-win/files/726893/Dockerfile.zip)

**Comment by friism** [comment]
This works fine for me. Are you sure your file is named `app0` and not `app0.dll`?

```
C:\code\repros\path-thing> dir


    Directory: C:\code\repros\path-thing


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        1/24/2017   6:41 AM             93 bin0
-a----        1/24/2017   6:46 AM             93 Dockerfile


C:\code\repros\path-thing> docker build .
Sending build context to Docker daemon 3.072 kB
Step 1/4 : FROM microsoft/dotnet:nanoserver-runtime
 ---> 479ec2a8fb73
Step 2/4 : COPY .\\bin0\\ /app/
 ---> d977a9cba1f4
Removing intermediate container 1c3f7350b5b4
Step 3/4 : WORKDIR /app
 ---> 77a4cfdeee1c
Removing intermediate container ad28fd8ce500
Step 4/4 : CMD cmd
 ---> Running in 367ebcb73b7f
 ---> f73481785791
Removing intermediate container 367ebcb73b7f
Successfully built f73481785791
C:\code\repros\path-thing>
```

**Comment by minherz** [comment]
The `app` is a folder name. In the file the copying goes to `/app/` with trailing slash. The error that I receive hints that there is a problem to access the local (source) files and not the destination. When doing it through VS2017 RC I even see the folder created in the image.
Please, mind that I am working with Windows containers. I thought that this info will be reported by Docker diagnostics and mention it "just in case".
I get the following (with a working folder D:\WorkDir\TestDocker\CoreConsoleApp1:

```
D:\WorkDir\TestDocker\CoreConsoleApp1>dir bin
 Volume in drive D has no label.
 Volume Serial Number is B493-1A44

 Directory of D:\WorkDir\TestDocker\CoreConsoleApp1\bin

24-Jan-17  17:06    <DIR>          .
24-Jan-17  17:06    <DIR>          ..
23-Jan-17  17:25             5,120 CoreConsoleApp1.dll
22-Jan-17  10:36    <DIR>          Debug
               1 File(s)          5,120 bytes
               3 Dir(s)  121,855,262,720 bytes free

D:\WorkDir\TestDocker\CoreConsoleApp1>docker build .
Sending build context to Docker daemon 3.584 kB
Step 1/4 : FROM microsoft/dotnet:nanoserver-runtime
 ---> 479ec2a8fb73
Step 2/4 : COPY .\\bin\\ /app/
GetFileAttributesEx bin\: The system cannot find the file specified.

```

**Comment by friism** [comment]
I can't reproduce that either. Can you try with absolute paths and separately with fewer slashes, etc.?

```
C:\code\repros\path-thing> dir
    Directory: C:\code\repros\path-thing
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        1/24/2017   7:08 AM                bin
-a----        1/24/2017   6:46 AM             93 Dockerfile
C:\code\repros\path-thing> dir .\bin\
    Directory: C:\code\repros\path-thing\bin
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        1/24/2017   7:08 AM              0 foo.dll
C:\code\repros\path-thing> cat .\Dockerfile
FROM microsoft/dotnet:nanoserver-runtime
COPY .\\bin\\ /app/
WORKDIR /app
CMD [ "cmd" ]
C:\code\repros\path-thing> docker build .
Sending build context to Docker daemon 3.072 kB
Step 1/4 : FROM microsoft/dotnet:nanoserver-runtime
 ---> 479ec2a8fb73
Step 2/4 : COPY .\\bin\\ /app/
 ---> 3ded5e71d19b
Removing intermediate container 322ccf49a10d
Step 3/4 : WORKDIR /app
 ---> 2220cb9e0970
Removing intermediate container 082c57a6c036
Step 4/4 : CMD cmd
 ---> Running in 07b495fc1d8e
 ---> 196daa2a5986
Removing intermediate container 07b495fc1d8e
Successfully built 196daa2a5986
C:\code\repros\path-thing>
```

**Comment by minherz** [comment]
I am not sure what do you mean by fewer slashes? The docker documentation states I cannot use absolute path as COPY <src>. I tried to copy the content into drive C: (system) and selected simpler names for folders and the file. On the clean environment I have found the problem.
The behavior was due the .dockerignore which was in the context of the Dockerfile. Once the file was removed, everything start running.
Thank you.
