### ISSUE TITLE
Docker 1.13 cli gives a warning about crypto/x509

### ISSUE THREAD

**Issue by JettJones** [docker/for-win#422]
### Expected behavior
Docker ouput should be free of warnings (unless there's something to fix)

### Actual behavior
Docker 1.13.0 provides a developer warning on every run - it is reporting a library does not exist on windows. That's not something I can fix as a user.
```
>docker --version
time="2017-01-24T09:45:40-08:00" level=warning msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"
Docker version 1.13.0, build 49bf474
```
### Information
  - host distribution and version (Windows version, build number, etc)
running on windows 10 pro, Version 1607 (OS Build 14292.693)

This might be an issue from Go's system cert pool: https://github.com/golang/go/issues/16736

### Steps to reproduce the behavior

  1. Install docker 1.13.0 on windows
  2. Run `docker --version` (or any other command)

**Comment by dagbjorn** [comment]
I see the same issue running on Windows 10 Home, Version 1607 (OS Build 14393.693) after upgrading from Docker 1.12.6 to 1.13.0. Docker seems to work alright, but the warning is annoying.

**Comment by dgageot** [comment]
@JettJones Thanks for the report. Can I ask you to open an issue on docker/docker? I guess this is not something that can be fixed on Docker for Windows, so I'm going to close the ticket.

**Comment by Neelerak** [comment]
This issue was a problem with Go and should be resolved as of 14 days ago, any chance to get a hotfix?

https://github.com/golang/go/issues/16736

**Comment by raiello** [comment]
this problem still exists - does anyone have an update?

**Comment by bfoxtrot** [comment]
I am having this same issue on Docker Windows - not my primary environment but I am forced to use it. 
`$ docker --version
time="2017-03-17T11:35:57-04:00" level=info msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"
Docker version 1.13.1, build 092cba3`

Any Ideas?
As far as I can see this does not affect anything, but I get the error on every line or command UNLESS I am using docker-compose to build a file. With docker-compose I am seeing no error. 

Hope this helps.

**Comment by cyberbeast** [comment]
This is irritating. Is there any fix for this at all? I used the amazonec2 driver to init a docker-swarm and since then I've been getting this stupid message and executing "docker info"  returns absolutely nothing.

**Comment by sebdelvalle** [comment]
hahaha seriously no fix in 3 months? docker pls

**Comment by raadbintareaf** [comment]
I still have the same problem !

**Comment by SandHilt** [comment]
Same here. For while, I think that a downgrade solve.

**Comment by nathanp** [comment]
I am having the same issue on Windows 10

**Comment by iliasioannou** [comment]
Same here. Windows 10 - 64 bit -

**Comment by anthonyhendrickson** [comment]
*Jeopardy theme plays*

**Comment by singularentity** [comment]
This is also occurring in Windows 7 64 bit via docker toolbox.

**Comment by ischyrus** [comment]
I'm having the same issue.

**Comment by sunildhillon** [comment]
Same issue here as well !! 

Any quick fix?

**Comment by JorgenSmith** [comment]
Same here. I had to get rid of the Docker for Windows using Hyper V, as my Broadwell-E system would fail to boot intermittently with Hyper V enabled (no messages there). Now on Docker Toolbox, everything appears to be running ok but the messages are distracting. Thanks. :-)

**Comment by asantos2000** [comment]
This also occurring in Windows 7 with service pack 1.

**Comment by huang-wang** [comment]
same problem on win10 docker version 1.13.1

**Comment by huang-wang** [comment]
Version:  17.03.0-ce not solved either

**Comment by mbssaiakhil** [comment]
Using Docker Toolbox on Windows 10 64-bit
Getting the same error (for example, docker version output is shown below),

![docker version](https://cloud.githubusercontent.com/assets/26372981/24336305/6934551c-12aa-11e7-8ba0-7e53bbee8ea0.JPG)
The same message is shown for all the docker commands. 
Is there a solution?

**Comment by Labrat02** [comment]
Also receiving same message on Windows 8, 17.03.0-ce Docker Toolbox.

**Comment by dgageot** [comment]
Hi everyone, you should add your comments on https://github.com/docker/docker/issues/31863. This issue is not specific to Docker for Windows.

**Comment by laurencefass** [comment]
Version: 17.03.0-ce problem still exists

**Comment by sebdelvalle** [comment]
hi we are docker and we don't care xoxo

**Comment by anthonyhendrickson** [comment]
FYI

Following @dgageot 's response, and the related threads: this fix has been merged and will be in release 17.04

**Comment by luisnaranjo733** [comment]
Thank you! When will 17.04 become available?
@anthonyhendrickson

**Comment by mahmed0715** [comment]
same, what to do?

**Comment by laurencefass** [comment]
Im using windows toolbox with windows 10 standard and i am not seeing the same problem running commands directly from my (virtualbox guest machine) default docker host.  windows specific authentication problem?

**Comment by hichMEN** [comment]
https://communities.intel.com/thread/111087

**Comment by cpace6** [comment]
Updating to version 17.05.0-ce fixed this for me. See https://github.com/moby/moby/issues/31863

**Comment by edgarechm** [comment]
Why is this issue closed? The issue still happens!
