### ISSUE TITLE
7BA60D48-F8C9-4437-89EC-AF4B9161070C/20190711100758

### ISSUE THREAD

**Issue by dfuhs** [docker/for-win#4224]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ulrich** [comment]
Hello @dfuhs 

Can you check your Hyper-V configuration as recommend by Microsoft ?

https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v

**Comment by dfuhs** [comment]
Here is what it says when I check through the PowerSHell:

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Windows\system32> DISM /Online /Enable-Feature /All /FeatureName:Microsoft-Hyper-V

Deployment Image Servicing and Management tool
Version: 10.0.18362.1

Image Version: 10.0.18362.239

Enabling feature(s)
[==========================100.0%==========================]
The operation completed successfully.
PS C:\Windows\system32>

So to me that seems like it is operating correctly.

Daniel Fuhs
Eco-Resource Consulting, Inc.
Office: (608) 877-9372
Mobile: (608) 316-5368

**Comment by dfuhs** [comment]
Here is what it says when I run the other command:

PS C:\Windows\system32> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All


Path          :
Online        : True
RestartNeeded : False



PS C:\Windows\system32>

Daniel Fuhs
Eco-Resource Consulting, Inc.
Office: (608) 877-9372
Mobile: (608) 316-5368

**Comment by ulrich** [comment]
Hello,

It seems that the Docker Desktop/Hyper-V configuration is corrupted. You can:
- Run **MobyLinux.ps1** command located in the folder : C:\Program Files\Docker\Docker\resources for re-creating the VM
- Re-installing Docker Desktop from scratch (with defaults settings)

Ulrich
