### ISSUE TITLE
Docker Desktop for Windows running at Windows10 hyper-V is not working inside Oracle Virtualbox 6

### ISSUE THREAD

**Issue by derekjhyang** [docker/for-win#4231]
- [v] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
MobyLinux VM is running on Windows10 PRO HyperV, and Docker Desktop for Windows must be started.

### Actual behavior
1. Docker Desktop for Windows is started failed.
[12:15:10.393][Linux          ][Error  ] Failed to start: Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start.

Failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running.

'MobyLinuxVM' failed to start. (Virtual machine ID 08DABA13-9D3D-4119-9DEA-2CEFA467FA03)

The Virtual Machine Management Service failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running (Virtual machine ID 08DABA13-9D3D-4119-9DEA-2CEFA467FA03).
at Start-MobyLinuxVM, <No file>: line 296
at <ScriptBlock>, <No file>: line 412. Let's retry

### Information

  - Windows Version: 10x64 Pro
  - Docker Desktop Version: 2.0.0.3
  - Oracle Virtualbox: 6.0.8 

### Steps to reproduce the behavior

  1. Install Oracle Virtualbox 6.0.8
  2. Provisioning a Windows10x64 Pro VM
  3. Enable Intel-VT/AMD-V and enable PAE/NX for that VM's CPU settings.  
  4. Enable HyperV features inside the Windows10x64 Pro VM.
  5. Install Docker Desktop for Windows
  6. Start Docker Desktop for Windows

**Comment by stephen-turner** [comment]
Can you start other Hyper-V VMs inside the VirtualBox? If not, then there is no possibility of Docker Desktop working.
