### ISSUE TITLE
\\.\pipe\docker_engine does not work

### ISSUE THREAD

**Issue by danzaharescu** [docker/for-win#4238]
- [X] I have tried with the latest version of my channel (Stable)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 9C3C68D5-9E48-487C-83EA-379D88F8C523/20190715093217

I need to run "docker" command from within a running container.
For this, I have found that it should work if I mount the \pipe\docker_engine as a volume:

"docker -v \\\\.\pipe\docker_engine:\\\\.\pipe\docker_engine  _image_name_"

### Expected behavior
I should be able to run the command "docker" after logging in the container
(docker exec -i -t _container_name_ cmd)

### Actual behavior
I get the message:
"'docker.exe' is not recognized as an internal or external command,
operable program or batch file."

or 

'docker' is not recognized as an internal or external command,
operable program or batch file.

I have seen other \pipe\docker_engine related problems, but this time my behavior seems to be different. The volume mount and start of container seems to work without problems, however, the command is not recognized (I do not get any privilege related error as in other cases)

### Information

  - Windows Version: Windows server 2019 version 1809, OS build 17763.107
  - Docker Desktop Version: 2.0.0.3 (31259) Channel stable, build 8858db3

I have attached a minimal Dockerfile and app that would reproduce the issue, but I think there nothing special about it.
[docker_data.zip](https://github.com/docker/for-win/files/3391321/docker_data.zip)

### Steps to reproduce the behavior

just use the command:
docker -v \\\\.\pipe\docker_engine:\\\\.\pipe\docker_engine  _image_name_
Then try to execute "docker" inside the running container.

  1. ...
  2. ...

**Comment by ebriney** [comment]
Hi @danzaharescu , this is because your image doesn't contain docker cli binary.
You can bind mount `C:\Program Files\Docker\Docker\Resources\bin` when running your container or copy it when building your image.

**Comment by danzaharescu** [comment]
Hello @ebriney 
I was able to run the command, after creating a volume of host directory you mentioned into the docker image. This may look like an obvious catch now that it works, but unfortunately, not (or maybe not well enough) documented on the tutorials I have visited...
Thank you for the help.

**Comment by danzaharescu** [comment]
The issue is already closed, but it would be nice if this would be written very clear in the official documentation. For the moment, I have not been able to navigate to a described procedure, maybe it does exist, if it does, you may check it for completeness.

**Comment by tibre** [comment]
Well, I am dealing apparently with the same issue.   If available, @danzaharescu or @ebriney - Can you help me understand how do I bind mount when building the image?  An actual example of the yaml config file.

I am lost if this should be defined under volumes, as a command or inside an .env file?  

Thanks,

**Comment by danzaharescu** [comment]
Hello @tibre 
I do not have the code at hand now, but, you need to define 2 volumes in the "docker run" parameters list (the 'pipe' one, and the volume to your host docker installation)
The full command would be something like this:
**docker -v \\.\pipe\docker_engine:\\.\pipe\docker_engine -v "C:\Program Files\Docker":"c:\folder_inside_docker_image" .... image_name**

Then, if you attach to the docker image (with a command line - I think it is something such as "docker exec cmd container_name"), navigate to c:\folder_inside_docker_image, you would see the mapped C:\Program Files\Docker from the host.
What the pipe trick does, is that you can now run docker commands on the host from inside the container. "docker" command may not be available everywhere inside the container, so you may have to navigate to the "bin" folder to execute it, but this is an environment path issue (that you can fix if needed)

I hope this helps...

**Comment by tibre** [comment]
Thanks @danzaharescu ,

To clarify, I am actually able to install portainer via a docker command and binding paths.  My question is specifically to docker-compose.

For some reason when I try running what equates to the same configuration via a compose yml file, it simply does not work…

**1. So, here the docker command that works:**
_docker container run -d -p 5000:9000 -v \\.\pipe\docker_engine:\\.\pipe\docker_engine portainer/portainer_

**2. Here the yml file that fails (I commented env variables as they do not seem to work in Windows...):**
_Error: 2019/10/28 13:16:28 Invalid endpoint protocol: Portainer only supports unix://, npipe:// or tcp://_

_############## INTERFACES ###############
# Portainer - without Traefik enabled
  portainer:
    image: portainer/portainer
    container_name: portainer
#    restart: always
    command: -H \\.\pipe\docker_engine:\\.\pipe\docker_engine
    ports:
      - "5000:9000"
    volumes:
#      - ${USERDIR}/portainer/data:C:/data
#      - ${USERDIR}/shared:C:/shared
      - I:\ServerFolders\Z\Docker_App_Control\portainer\data:C:\data
#      - I:\ServerFolders\Z\Docker_App_Control\shared:C:\shared

    environment:
#      - TZ=${TZ}
      - TZ="America/Los Angeles"_

**Comment by danzaharescu** [comment]
Hello @tibre,
I am not using the compose for the moment, so unfortunately I cannot help you further with the issue...
