### ISSUE TITLE
Unable to install Docker Desktop, stuck on "Removing files..."

### ISSUE THREAD

**Issue by remyels** [docker/for-win#4243]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 8d82923d-a796-11e9-95c0-a0d3c134007b/20190716065427

### Expected behavior

Being able to successfully install Docker Desktop 2.0.0.3

### Actual behavior

Installer gets stuck at "Removing files..."

![Installing-Docker-Desktop](https://user-images.githubusercontent.com/38399341/61272810-aec8f900-a7b0-11e9-8b72-87263b2c463b.png)

### Information

  - Windows Version: Windows 10, Version 1809, OS Build 17763.557
  - Docker Desktop Version: 2.0.0.3 (31259)

### Steps to reproduce the behavior

  1. Download Docker Desktop 2.0.0.3
  2. Install it

I have also tried both Stable and Edge versions, to no avail. Let me know what you suggest. Thanks!

**Comment by remyels** [comment]
Please make sure to check the file attached to this comment

[service.txt](https://github.com/docker/for-win/files/3395860/service.txt)

**Comment by rogermarsal** [comment]
In my case I only desactivated windows defender.

**Comment by rogermarsal** [comment]
In my case I only desactivated windows defender.

**Comment by remyels** [comment]
> In my case I only desactivated windows defender.

The issue is that I cannot do that due to company policy :(
