### ISSUE TITLE
Docker does not preserve Hyper-V memory setting on startup

### ISSUE THREAD

**Issue by jimmyharris** [docker/for-win#425]
### Expected behavior

Docker respects my Hyper-V memory settings when launching the docker-for-windows application.

### Actual behavior

Docker sets the default configuration to whatever is set in the docker application configuration.

### Information

  - Diagnostic ID: 0B317FEB-9ADA-429C-A3CF-7400E0CCEF4E/2017-01-24_14-25-11
  - Windows Version: 10.0.14393.693

### Steps to reproduce the behavior

  1. Install Docker and Launch the docker application.
  2. Allow Docker-for-windows to setup the MobyLinux virtual machine.
  3. Close Docker-for windows and open the MobyLinux virtual machine settings in hyper-v manager.
  4. Enable dynamic memory and change the startup memory configuration to 512 MB.
  5. Launch docker-for-windows without starting the VM.
  6. Observe that the memory allocation has been reset to Static 2048 MB.

**Comment by jimmyharris** [comment]
Additionally, it would be nice if Docker's "Advanced" Settings pane supported enabling and disabling dynamic memory on windows.

**Comment by dgageot** [comment]
@jimmyharris We don't support users making changes directly in the Hyper-V Manager. That includes memory settings. As for the Dynamic memory, we have no plan to support it because it introduces random issues. I'm sorry I'm going to close that issue.

**Comment by jimmyharris** [comment]
I can understand that perspective but it is frustrating that we cannot, as users, attempt to work with hyper-v 's dynamic memory despite the random issues.  I would be more than happy to make the attempt to resolve these issues if I were able to modify docker for windows to support these capabilities myself, but there doesn't appear to be a path to even attempt to experiment with these issues without getting you directly involved.  Do you have more reference to where these decisions were made so I can better understand the types of issues you were facing?
