### ISSUE TITLE
Bind propagation shared/slave not working 

### ISSUE THREAD

**Issue by skwasiborski** [docker/for-win#4256]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 243E39A1-A3D0-4E40-B992-2FF486C03DC8/20190717161521

### Expected behavior
Specify bind mount with bind propagation shared or rshared or slave or rslave, container starts with mount with specified bind propagation.
### Actual behavior
Container fails to start with following message:
docker: Error response from daemon: path /host_mnt/c/temp/target is mounted on /host_mnt/c but it is not a shared or slave mount.
### Information

  - Windows Version: Windows 10 Enterprise 1903 build 18362.239

  - Docker Desktop Version:
```
Client: Docker Engine - Community
 Version:           19.03.0-rc2
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        f97efcc
 Built:             Wed Jun  5 01:37:59 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.0-rc2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       f97efcc
  Built:            Wed Jun  5 01:42:10 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683 
```

### Steps to reproduce the behavior

Given c:\temp\target exists run following:
docker run -d -it --rm --name devtest --mount type=bind,source="c:\temp\target",target=/app --mount type=bind,source="c:\temp\target",target=/app2,readonly,bind-propagation=rslave nginx:latest

or

Given /tmp/target on docker VM exists run following:
docker run -d -it --rm --name devtest --mount type=bind,source=/tmp/target,target=/app --mount type=bind,source=/tmp/target,target=/app2,readonly,bind-propagation=rslave nginx:latest

I tried mounting both windows path and docker host VM path both without success. I tried both from windows cmd and WSL/bash shells.

**Comment by skwasiborski** [comment]
Any advise on working around the issue?

**Comment by rafaelreis-r** [comment]
I'm having the exact same issue on Docker Desktop.

`Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683`

**Comment by dwthien** [comment]
I'm having the exact same issue on Docker Desktop, I run on WSL. After I try to other ways.

Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 2
  Paused: 0
  Stopped: 2
 Images: 13
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.943GiB
 Name: docker-desktop
 ID: MPED:CSS3:PV2P:ZL7Y:ZBV2:OVPQ:C273:I3ZA:4TQB:WKTS:BWGH:2EFR
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 50
  Goroutines: 63
  System Time: 2020-04-26T11:53:58.767579326Z
  EventsListeners: 3
 Username: dwthien
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
