### ISSUE TITLE
Docker commands fail on fresh install Windows 10 -- trouble shooting documented needs update.

### ISSUE THREAD

**Issue by BrainSlugs83** [docker/for-win#4265]
RE: https://success.docker.com/article/docker-for-windows-fails-with-a-daemon-not-running-message
> If this does not resolve your issue, Please file an issue at https://github.com/docker/for-win/issues.

### Steps to Reproduce
On a fresh install of Docker on Windows 10; after reboot, I've run any `docker pull foo/bar` command from an administrative command prompt, and received the error message:
> Using default tag: latest
> error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/images/create?fromImage=...&tag=latest: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

I followed the trouble shooting steps located at https://success.docker.com/article/docker-for-windows-fails-with-a-daemon-not-running-message -- which consist of stopping and restarting the service.

### Expected behavior
I expected the troubleshooting steps to solve my issue, or for there to be more steps / or at least a list of other things to investigate 

### Actual behavior
The documentation only contained steps for stopping and restarting the service; which was not relevant or related to my issue. (And as instructed by the documentation, I'm logging an issue here.)

### Actual Solution
I had to manually launch the "Docker Desktop" application (which I did not know existed)... wait for it to chooch for a bit in the system tray, and when it was finally ready, I had to click on it and sign in with my docker credentials.

I did not know this was required, that this tool had to be run, or that I had to sign in just to pull down public images. -- And I believe the troubleshooting documentation should be updated to reflect this (possibly as the primary step, since it's apparently such an integral part of the environment setup procedure).

**Comment by psgg1981** [comment]
Had the very same problem. Thanks for sharing @BrainSlugs83
