### ISSUE TITLE
I never ever got Docker to run on my Machine

### ISSUE THREAD

**Issue by kuntergunt** [docker/for-win#4270]
I've been installing, uninstalling, installing again. I always get error messages related to bugs in code that do not say anything about what is going wrong here. 
I'll keep on using Docker on Linux where it is absolutely easy to install and stable until Docker on Windows becomes usable to me.

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
Closing this ticket, as it does not contain any information to help diagnose the issue.
