### ISSUE TITLE
Docker Desktop for windows WSL 2, serial port support

### ISSUE THREAD

**Issue by cranphin** [docker/for-win#4271]
Hi!

I could not find a better place to ask/suggest this, please redirect me elsewhere as appropriate :)

Docker Desktop for Windows on WSL 2 is underway, and it sounds amazing.

There is one feature which I hope might be possible on this platform, and which would benefit a lot of people from the 'Maker' community: Support for serial ports like /dev/ttyusb0.

The use case for this is that a lot of embedded devices are programmed via a serial port (via a USB adapter like cp2102), and have a SDK which is Linux based and generally works very well in a Docker container. For example the popular ESP8266 and ESP32 devices.

I already use docker containers to program for these devices, having serial ports exposed in docker containers would be the last part to a great developer experience here :)

Thanks!

**Comment by leofabri** [comment]
I remember reading somewhere online, maybe on the official Microsoft developer website, that someone said that WSL2 won't support serial devices at first (a feature that only works with WSL1). 
Unfortunately, I'm in your same situation. I work with and ESP32 most of the time on Ubuntu Desktop and the only thing that is preventing me from moving to WSL2 is serial support that is not working. Like you, I use Docker with several containers, and Docker works just perfectly. However serial devices are way too important! I hope they'll fix this as soon as possible

**Comment by cranphin** [comment]
> Unfortunately, I'm in the same situation. I work with and ESP32 most of the time on Ubuntu Desktop and the only thing that is preventing me from moving to WSL2 is serial support that is not working.

It might or might not help you, but have a look at my current workaround which uses flashing over TCP to serial with some hackery: https://github.com/cranphin/esp32_win_buildscripts

**Comment by simonferquel** [comment]
We are dependant on Microsoft on this one. Please report the issue on https://github.com/microsoft/wsl/issues.

**Comment by cranphin** [comment]
I meant/mean to do as you suggested still :)

Though I have been thinking, and better (in my case) would be to support usb instead of serial devices. Most of these boards use a USB to serial (or other protocol!) chip :)

Fortunately, USB support is something they intend to do, but might take a while: https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq#can-i-access-the-gpu-in-wsl-2-are-there-plans-to-increase-hardware-support

And then docker needs to support it too.. :)

**Comment by leofabri** [comment]
> > Unfortunately, I'm in the same situation. I work with and ESP32 most of the time on Ubuntu Desktop and the only thing that is preventing me from moving to WSL2 is serial support that is not working.
> 
> It might or might not help you, but have a look at my current workaround which uses flashing over TCP to serial with some hackery: https://github.com/cranphin/esp32_win_buildscripts

Hi, @cranphin I'm trying to set up a development environment to program my ESP32 boards. I came across your workaround but since there isn't any documentation, would you mind guiding me through the setup process? Thank you in advance.
