### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by pkch** [docker/for-win#428]
`docker pull python` or `docker commit ...` fail with an "out of space" message.

Diagnostic ID: 5C6BAFC1-902A-48C1-86BD-C2E50A8F354B/2017-01-25_00-31-23

Docker 1.13.0 (9795) under Windows 10 Build 14393

```
> docker commit -m "python 3.6" quirky_haibt python36
Error response from daemon: Error processing tar file(exit status 1): write /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial_universe_binary-amd64_Packages.lz4: no space left on device
```

I don't know how to reproduce this (it works fine on another computer with a similar setup).

I'm sure my Windows hard drive has plenty of space.

[Related SO question](http://stackoverflow.com/questions/41813774/no-space-left-on-device-when-pulling-an-image)

**Comment by rneugeba** [comment]
It looks like the Linux VM did not find the hard disk as I see:
```
[23:53:02.394][Moby           ][Info   ]  * Configuring host block device ... * ERROR: automount failed to start
```
In the Logs. Could you check that `C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx` exists? Could you also try a factory reset?

thanks
rolf

**Comment by pkch** [comment]
@rneugeba Yes, `C:\Users\Public\Documents\Hyper-V\Virtual hard disks\MobyLinuxVM.vhdx` exists. I don't want to do factory reset yet; I'm pretty sure it will fix the problem, but then I wouldn't be able to do any additional diagnostics to find the bug. I guess if nothing useful can be done, I'll factory reset in a few days.

**Comment by rneugeba** [comment]
@pkch Hmm, I didn't see anything obvious in the diagnostics except this from the Linux boot:
```
hv_vmbus: registering driver hv_storvsc
hv_vmbus: probe failed for device 86afc19d-0372-4404-84c7-9fc785b47a33 (-12)
hv_storvsc: probe of 86afc19d-0372-4404-84c7-9fc785b47a33 failed with error -12
```
This is the Linux kernel probing the VMBus for storage devices and reporting an error. It's a little un-usual since -12 is `ENOMEM`, but that might just be a wrong error code.

I think we have all the information we need at this stage, so please try the factory reset and see if it fixes it.

**Comment by rneugeba** [comment]
@pkch did the factory reset work for you?

**Comment by pkch** [comment]
Yes, actually not even a factory reset but a computer reboot (although it's possible a new version of docker was installed in the meantime).

**Comment by rneugeba** [comment]
Thanks for getting back and glad that it's now working for you. Closing
