### ISSUE TITLE
Exposing SCTP port error

### ISSUE THREAD

**Issue by LionelJouin** [docker/for-win#4282]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 75F747F1-A56C-4841-8DD8-490AFF2EFF49/20190723090102

### Expected behavior

The container should start and the SCTP port should be exposed. It should have the same behavior as if I run a container and expose a TCP or UDP port.

### Actual behavior

The container is in "Created" status, there is no port exposed and I get this error:

> C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: driver failed programming external connectivity on endpoint happy_pare (e5a67ff031549b3d90f8a46e54e6de7e87c6ed5ec0e0cb0cbef86bc4f2bebd25): Error starting userland proxy:.

### Information

  - Windows Version: Windows 10 Entreprise, Version 1709, OS Build: 16299.1237
  - Docker Desktop Version: 2.0.0.3 (31259)
I tried to restart docker, restart my computer, on another computer, with another image, I always had the same issue.

### Steps to reproduce the behavior

  1. Use this image [aweimeow/sctp-server](https://hub.docker.com/r/aweimeow/sctp-server):
`docker run -ti --name sctp -p 9999:9999/sctp aweimeow/sctp-server bash`

**Comment by Boskim0n0** [comment]
Im having the same problem with version 2.1.0.1

**Comment by Boskim0n0** [comment]
#4755  i tried with an Ubuntu VM and docker started succesfully. The problems seems to be inside the windows version.
