### ISSUE TITLE
Cannot mount volumes 

### ISSUE THREAD

**Issue by AnticliMaxtic** [docker/for-win#4300]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BA533F44-CB28-4201-AE40-E230F0762F3A/20190725153654
[20190725153654.zip](https://github.com/docker/for-win/files/3433267/20190725153654.zip)

### Expected behavior

I have a file in a folder on my Windows machine C:\git\temp\installer.exe
```Powershell
PS C:\git> ls .\temp\


    Directory: C:\git\temp


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        5/26/2019   9:37 PM       50164688 installer.exe
```
When I run the following command from powershell I would expect to see the file installer.exe to be listed when running the ```ls /root/temp``` command

```PowerShell
PS C:\git> docker run --rm -it -v ${PWD}/temp:/root/temp ubuntu
root@b8107bd9b140:/# ls /root/temp/
installer.exe
root@b8107bd9b140:/# exit
```
### Actual behavior
There appears to be nothing in the folder 

```PowerShell
PS C:\git> docker run --rm -it -v ${PWD}/temp:/root/temp ubuntu
root@b8107bd9b140:/# ls /root/temp/
root@b8107bd9b140:/# exit
```

### Information
  - Is it reproducible?
This happens every time I am not on my company network, but does not happen when I am connected to the company intranet

  - Is the problem new?
No, I need help looking through the log to pinpoint the failure point. I have tried working with the IT department but they are incapable of determining the source of the failure. 

  - Windows Version: 1809
  - Windows Edition Windows 10 Pro
  - OS build 17763.615

  - Docker Desktop Version: 2.0.0.3 (31259)

### Steps to reproduce the behavior

  1. Remove my pc from the company intranet
  2. attempt to volume mount a folder to a docker container
  3. see that it fails

**Comment by volphy** [comment]
The same issue occurs while using Docker Desktop 2.1.3

It's an old bug and I can remember it occurring longer than one year.

**Comment by lsklyut** [comment]
This is happening to me as well, except when I'm on my company's VPN. It seems to have been introduced in 2.1 - downgrading to 2.0.0.2 resolved the issue for me. 

OS Build: 17763.437

Additionally, if I add a file to that directory in the container, that file persists across new runs when mounting the same directory. However, I can't locate the manually added file anywhere on my local file system.


```
PS C:\dev\storage-test> ls


    Directory: C:\dev\storage-test


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        11/4/2019   3:03 PM            115 Dockerfile
-a----        11/4/2019   3:03 PM             27 storage-test.php


PS C:\dev\storage-test>
PS C:\dev\storage-test>
PS C:\dev\storage-test> docker run -v ${PWD}:/usr/src/app -ti storage
[root@cbce1aad45de app]# pwd
/usr/src/app
[root@cbce1aad45de app]# ls
[root@cbce1aad45de app]# touch pineapple.txt
[root@cbce1aad45de app]# ls
pineapple.txt
[root@cbce1aad45de app]# exit
exit
PS C:\dev\storage-test>
PS C:\dev\storage-test>
PS C:\dev\storage-test> ls


    Directory: C:\dev\storage-test


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        11/4/2019   3:03 PM            115 Dockerfile
-a----        11/4/2019   3:03 PM             27 storage-test.php


PS C:\dev\storage-test>
PS C:\dev\storage-test>
PS C:\dev\storage-test> docker run -v ${PWD}:/usr/src/app -ti storage
[root@c263ffbec718 app]# ls
pineapple.txt

```
