### ISSUE TITLE
Installing Docker Desktop on Windows 10 Home requires editing the Registry

### ISSUE THREAD

**Issue by ebednarz** [docker/for-win#4306]
### Expected behavior

After downloading the Docker Desktop for Windows installer I'd expect it to run successfully on Windows 10 Home with Hyper-V installed.

### Actual behavior

Installation fails.

### Information

After changing

    Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion

from `Core` to `Professional` installation succeeds. 

### Steps to reproduce the behavior

As outlined above, in that order.

**Comment by stephen-turner** [comment]
Windows 10 Home with Hyper-V installed? That's impossible, isn't it?

**Comment by ebednarz** [comment]
> Windows 10 Home with Hyper-V installed? That's impossible, isn't it?

The Hyper-V packages in `C:\Windows\servicing\Packages` can be installed with DISM.

Cf. https://www.deskmodder.de/blog/2018/08/23/windows-10-home-hyper-v-aktivieren/ (German)

**Comment by ebednarz** [comment]
I've been reminded just now that you need to do that for every update, as well. 🤦‍♂️

**Comment by stephen-turner** [comment]
Sorry, we're not going to change this. Our prerequisites check whether Hyper-V is installable, not whether it is installed. If you're going to write a script to hack around Microsoft's restrictions, you can easily change the registry in the same script.

**Comment by ebednarz** [comment]
It is fairly obvious that the installer does **not** check whether Hyper-V can be installed.

Thanks for your implicit feedback on the engineering quality of this project though. :)

**Comment by mwarrenus** [comment]
> Windows 10 Home with Hyper-V installed? That's impossible, isn't it?

With the release of Windows Subsystem for Linux v2 (aka WSL 2), Microsoft enabled Hyper-V for use in Windows Home.  See for example https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq . 
> Does WSL 2 use Hyper-V? Will it be available on Windows 10 Home?

> WSL 2 will be available on all SKUs where WSL is currently available, including Windows 10 Home.

> The newest version of WSL uses Hyper-V architecture to enable its virtualization. This architecture will be available in the 'Virtual Machine Platform' optional component. This optional component will be available on all SKUs. You can expect to see more details about this experience soon as we get closer to the WSL 2 release.

**Comment by stephen-turner** [comment]
Hyper-V itself is not available on Windows 10 Home even in the 2004 release, even though WSL 2 uses the technology internally. However, Docker Desktop can run on WSL 2, so you no longer need full Hyper-V and it runs on Windows 10 Home now.
