### ISSUE TITLE
Docker for Windows Failed To Start

### ISSUE THREAD

**Issue by katygarner** [docker/for-win#431]
### Expected behavior

Expect to see that docker has started successfully

### Actual behavior

After several minutes, error saying "Invalid bind address format: http://localhost:2375" and docker has not started.

### Information

  - Diagnostic ID: 8B05F453-80F1-4E18-95A3-6FF744157E1B/2017-01-25_10-50-55
  - Windows 10 Pro (OS Build 14393.693)

### Steps to reproduce the behavior

  1. Try to Start docker
  2. Wait and error occurs.

I have tried both stable and beta version.  I previously had docker for windows working successfully on my machine, but after not using for a few months and then installing the latest version this is now a problem for me.

**Comment by rneugeba** [comment]
@katygarner thanks for your report. It looks like you have the `DOCKER_HOST` environment variable set:
```
DOCKER_HOST                    http://localhost:2375
```
could you unset it and try again? You may have to log out and in again for the change to take effect.

**Comment by katygarner** [comment]
@rneugeba Thanks for your response.

DOCKER_HOST wasn't showing in the environment variables gui, as I'd deleted it previously.  After your message I looked a little further and discovered that it was visible when I used "set" in the command window.  I managed to completely get rid of any trace of the environment variable and docker is now starting.  

Thanks!

**Comment by rneugeba** [comment]
Glad it's working for you now. Closing.

**Comment by friism** [comment]
@rneugeba do you think it would be worth checking for this in the installer?

**Comment by rneugeba** [comment]
@friism created an internal tracking issue
