### ISSUE TITLE
docker-compose up -d Issue

### ISSUE THREAD

**Issue by jbwebpro** [docker/for-win#4321]
ERROR: for php  Cannot start service php: b'OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \\"rootfs_linux.go:58: mounting \\\\\\"/c/Users/.../.../docker/docker-config/www.conf\\\\\\" to rootfs \\\\\\"/mnt/sda1/var/lib/docker/overlay2/1234567890/merged\\\\\\" at \\\\\\"/mnt/sda1/var/lib/docker/overlay2/1234567890/merged/etc/php-fpm.d/www.conf\\\\\\" caused \\\\\\"not a directory\\\\\\"\\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type'
ERROR: Encountered errors while bringing up the project.

### Expected behavior
It should run some containers like PHP, MySQL and so on.
### Actual behavior
It stops and showing that ERROR.

### Information

  - Windows Version: 10
  - Docker Toolbox Version: 18.03.0-ce / Even the latest version has error.

### Steps to reproduce the behavior

  1. ... docker-compose up -d.
  2. ... a some-php container: error. 

This really bugs me. And maybe this will be the reason for me not to have a job anymore.

**Comment by mikeparker** [comment]
Are you using docker desktop or docker toolbox?

**Comment by saschatoussaine** [comment]
Seems to be the Toolbox:
> Docker Toolbox Version: 18.03.0-ce / Even the latest version has error.

I have the same error on Windows 10, too.
