### ISSUE TITLE
Can't log in and can't pull image

### ISSUE THREAD

**Issue by Cedhulk** [docker/for-win#4323]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 9F3237C3-611E-4ABA-8FF8-D0097F2D4B7D/20190730151916

### Expected behavior

I installed Docker for windows and I can’t login to the docker hub with my login and password. I cant pull the hello-world image neither.
Beside that I’m in a company so there is a proxy. How can I be sure that I do the good settings (for windows and linux container) ?

It has to connect

### Actual behavior
I have this error when I do these things : “Error response from daemon: Get https://registry-1.docker.io/v2/ : Method Not Allowed”

### Information

  - Windows Version: windows 10
  - Docker Desktop Version: Docker 18.09.2

### Steps to reproduce the behavior

  1. "docker login" in PowerShell cli
  2. then I i put my ID and password and my error appear
, when I pull an image it is the same.

**Comment by mikeparker** [comment]
What happens if you try to log in via the Docker Desktop UI?

Also which version of Docker Desktop are you running? You quoted the engine version (18.09.2) but not the Desktop version. I assume Stable 2.0.0.3?

**Comment by Cedhulk** [comment]
Via the UI it does nothing.
It is the last version of Docker desktop
