### ISSUE TITLE
SSL certificate problem: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by gireeshspr** [docker/for-win#4324]
Hi All,
'docker build' executing the following RUN command in Dockerfile throws SSL certificate error.
RUN go get github.com/pdevine/go-asciisprite

### Expected behavior
docker build complete without error

### Actual behavior 
Build an image from a Dockerfile
PS C:\Users\gviswanathan\doodle\cheers2019> docker build -t lgdocker1/cheers2019 .
Sending build context to Docker daemon  13.31kB
Step 1/9 : FROM golang:1.11-alpine AS builder
1.11-alpine: Pulling from library/golang
050382585609: Pull complete
0bb4ee3360d7: Pull complete
893f09c2afb0: Pull complete
c2e22f8e95ff: Pull complete
e908c6b3f8b4: Pull complete
Digest: sha256:e14164f34ebf0197a6d07a22ad3518374f5beb2a72ec61eb28f794562d8b9183
Status: Downloaded newer image for golang:1.11-alpine
 ---> d9aba3165478
Step 2/9 : RUN apk add --no-cache git
 ---> Running in 8a5d2bcf249e
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
(1/5) Installing nghttp2-libs (1.38.0-r0)
(2/5) Installing libcurl (7.65.1-r0)
(3/5) Installing expat (2.2.7-r0)
(4/5) Installing pcre2 (10.33-r0)
(5/5) Installing git (2.22.0-r0)
Executing busybox-1.30.1-r2.trigger
OK: 21 MiB in 20 packages
Removing intermediate container 8a5d2bcf249e
 ---> 5d4834ee329f
Step 3/9 : RUN go get github.com/pdevine/go-asciisprite
 ---> Running in 17b54df0fced
# cd .; git clone https://github.com/pdevine/go-asciisprite /go/src/github.com/pdevine/go-asciisprite
Cloning into '/go/src/github.com/pdevine/go-asciisprite'...
fatal: unable to access 'https://github.com/pdevine/go-asciisprite/': SSL certificate problem: self signed certificate in certificate chain
package github.com/pdevine/go-asciisprite: exit status 128
The command '/bin/sh -c go get github.com/pdevine/go-asciisprite' returned a non-zero code: 1
### Information
  - This issue can be reproduced.
  - Windows Version: Win 10
  - Docker Desktop Version: Desktop Community Version 2.0.0.3 (31259), Build: 8858db3

### Steps to reproduce the behavior
Follow the steps in the following link
https://hub.docker.com/?overlay=onboarding

**Comment by JorisVanEijden** [comment]
Cannot reproduce issue.
Windows 10, Docker version 18.09.2, build 6247962

Dockerfile:
```
FROM golang:1.11-alpine AS builder
RUN apk add --no-cache git
RUN go get github.com/pdevine/go-asciisprite
```
Output:
```
PS C:\tst> docker build -t lgdocker1/cheers2019 .
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM golang:1.11-alpine AS builder
1.11-alpine: Pulling from library/golang
050382585609: Already exists
0bb4ee3360d7: Pull complete
893f09c2afb0: Pull complete
c2e22f8e95ff: Pull complete
e908c6b3f8b4: Pull complete
Digest: sha256:e14164f34ebf0197a6d07a22ad3518374f5beb2a72ec61eb28f794562d8b9183
Status: Downloaded newer image for golang:1.11-alpine
 ---> d9aba3165478
Step 2/3 : RUN apk add --no-cache git
 ---> Running in ec0e57dd11ef
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
(1/5) Installing nghttp2-libs (1.38.0-r0)
(2/5) Installing libcurl (7.65.1-r0)
(3/5) Installing expat (2.2.7-r0)
(4/5) Installing pcre2 (10.33-r0)
(5/5) Installing git (2.22.0-r0)
Executing busybox-1.30.1-r2.trigger
OK: 21 MiB in 20 packages
Removing intermediate container ec0e57dd11ef
 ---> 39cc448617c3
Step 3/3 : RUN go get github.com/pdevine/go-asciisprite
 ---> Running in d4daee297d9c
Removing intermediate container d4daee297d9c
 ---> d99248061f38
Successfully built d99248061f38
Successfully tagged lgdocker1/cheers2019:latest
```

Perhaps your internet is being tampered with? Or it was a temporary issue?
What is the result of running this command without docker?
`git clone https://github.com/pdevine/go-asciisprite`

**Comment by gireeshspr** [comment]
Thanks for looking into this. 

Here is the command I ran from powershell and got the response

PS C:\Users\gviswanathan\doodle\cheers2019> git clone https://github.com/pdevine/go-asciisprite
Cloning into 'go-asciisprite'...
fatal: unable to access 'https://github.com/pdevine/go-asciisprite/': SSL certificate problem: self signed certificate in certificate chain

**Comment by JorisVanEijden** [comment]
Yeah, this is completely unrelated to docker.
Maybe an antivirus? https://github.com/Microsoft/Git-Credential-Manager-for-Windows/issues/646

**Comment by gireeshspr** [comment]
I did a little more research and found that it works on my personal laptop. The command fails at workplace. So it looks like a network security related issue that prevents the certificate verification.

Also, I am able to run the command without issues by disabling the SSL check with the following. 
resolution1: git -c http.sslVerify=false clone https://github.com/docker/doodle.git
resolution2: git config --global http.sslVerify "false"  (not recommended because of security reasons)

Now I have a problem when the docker build command 'RUN go get github.com/pdevine/go-asciisprite' is executed. Even after disabling the ssl check globally (using the resolution 2), the RUN command fails.

Any help on running the RUN command with an option to disable the SSL check like the following?
RUN go get github.com/pdevine/go-asciisprite with noSSLCheck

**Comment by mikeparker** [comment]
Thanks for helping out with this one @JorisVanEijden !

@gireeshspr you should try the support forum for individual setup / docker command help: https://forums.docker.com/

**Comment by dannyknowlton** [comment]
Thank you InfoSec for killing productivity one brick at a time.

**Comment by Tyatyushkin** [comment]
add string to Dockerfile

cat Dockerfile
FROM golang:1.11-alpine AS builder
RUN apk add --no-cache git
**RUN git config --global http.sslVerify "false"**
RUN go get github.com/pdevine/go-asciisprite
WORKDIR /project
COPY cheers.go .
RUN CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' -o cheers cheers.go

FROM scratch
COPY --from=builder /project/cheers /cheers
