### ISSUE TITLE
Docker error after restarting VM 

### ISSUE THREAD

**Issue by guixermo** [docker/for-win#4329]
I'm trying to give more RAM to my Linux VM but first i need to shut down the VM image.
When i restart the vm, i can't initiate docker correctly giving me this error:

`Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/home/ubuntu/Descargas/scripts/assets/nginx.conf\\\" to rootfs \\\"/var/lib/docker/overlay2/ebbbe053a9670b801ef0119f4502630a618268fe87c586d2cd2cb8423142d737/merged\\\" at \\\"/var/lib/docker/overlay2/ebbbe053a9670b801ef0119f4502630a618268fe87c586d2cd2cb8423142d737/merged/etc/nginx/nginx.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
Error: failed to start containers: sandbox-proxy
mysql
`
Thank you so much for your help :)

**Comment by mikeparker** [comment]
There are already open issues tracking this issue. Please add your details to an existing ticket by using the search function to find existing open issues. This can usually be done by entering your error message into the search box.

See:https://github.com/docker/for-win/issues?utf8=%E2%9C%93&q=is%3Aissue+OCI+runtime+create+failed+
