### ISSUE TITLE
Hyper-V was unable to find a virtual switch with name "DockerNAT".

### ISSUE THREAD

**Issue by kjarrad** [docker/for-win#4330]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [X ] I have uploaded Diagnostics
  - Diagnostics ID: C8464E2D-E292-46AA-85ED-A6AC6E559F44/20190731101643

### Expected behavior
Start Docker Desktop.

### Actual behavior
Docker Desktop does not start.

### Information

  - Windows Version: Windows 10 Enterprise, Intel i7-6700 3.41GHz, 16G RAM, 64 bit
  - Docker Desktop Version: 2.0.0.3 (31259), stable, 8858db3, Engine 19.09.2

### Steps to reproduce the behavior

  1. start computer
  2. login
  3. Docker Desktop pop up window displays error message: Hyper-V was unable to find a virtual switch with name "DockerNAT".
  4. command line: 
    $ docker --version
    Docker version 18.09.2, build 6247962
  5. command line:
    $ docker run hello-world
    C:\Program Files\Docker\Docker\Resources\bin\docker.exe: error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/containers/create: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.

**Comment by mikeparker** [comment]
There are already open issues tracking this issue. Please add your details to an existing ticket by using the search function to find existing open issues. This can usually be done by entering your error message into the search box.

See:https://github.com/docker/for-win/issues?utf8=%E2%9C%93&q=is%3Aissue+Hyper-V+was+unable+to+find+a+virtual+switch+with+name+%22DockerNAT%22
