### ISSUE TITLE
Unable to Start Docker Desktop App

### ISSUE THREAD

**Issue by Raaghu** [docker/for-win#4333]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID:  A956ABC7-7997-43A6-BFA4-98C4D2D8619A/20190731132712

### Expected behavior
Docker Desktop Should run successfully

### Actual behavior

Gets Following Error Every time

Hardware assisted virtualization and data execution protection must be enabled in the BIOS. See https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization-must-be-enabled

### Information

  - Windows Version: Windows 10
  - Docker Desktop Version: 2.0.0.3

### Steps to reproduce the behavior

  1. Install Docker for Desktop
  2. Run Docker Desktop shortcut on the Windows Desktop
  3. Asks for Hyper-V ennoblement , Click Yes
  4. machine restarts automatically
  5. Boot error during restart
  6. Disable hypervisorlaunchtype in bcdedit command in Safe Mode
  7. Restart
  8. Double click on Docker for Desktop
  9. Error is displayed
 10. Followed instructions in link provided in Error
 11. No success after that even

**Comment by mikeparker** [comment]
Which windows 10 are you running?

**Comment by mikeparker** [comment]
It's highly likely your computer does not support SLAT and you can't run Hyper-V or docker. See https://github.com/docker/for-win/issues?q=is%3Aissue+Hardware+assisted+virtualization+is%3Aclosed for lots of issues already closed.
