### ISSUE TITLE
Unable to check availability for Windows feature *Hyper-V*

### ISSUE THREAD

**Issue by Thrilokg** [docker/for-win#4334]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

![image](https://user-images.githubusercontent.com/49150454/62217929-20b45b80-b3c9-11e9-8011-b72cf7614651.png)

**Comment by mikeparker** [comment]
Please fill out the issue template, most importantly including a diagnostic ID for us to see your logs and any relevant reproduction instructions.
