### ISSUE TITLE
Unable to start the docker desktop with the below issue

### ISSUE THREAD

**Issue by lgiduthuri** [docker/for-win#4335]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by lgiduthuri** [comment]
Unable to start at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean execute AfterStart Cleanup) at Docker.Actions.<>c__DisplayClass 24_0.<Start>b__0() at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

**Comment by mikeparker** [comment]
Please fill out the issue template, most importantly including:
* What the problem is
* A diagnostic ID for us to see your logs
* How to reproduce the error (what is your setup).

**Comment by lgiduthuri** [comment]
Hi,
Problem:
I am unable to launch desktop docker for windows 10 machine. After installing If I double click  the desktop ICON getting the below error.

[cid:image001.png@01D547F4.774E4C30]

Tried uninstalling and installing many things but still facing the same error

A diagnostic ID for us to see your logs : Attached the log file for your referencr
How to reproduce the error (what is your setup).:

  *   Download docker desktop for windows from docker hub
  *   Double click the docker short cut key installed on desktop and getting the above error
[cid:image001.png@01D547F4.774E4C30]

**Comment by sportradar-satis** [comment]
I seem to have the same problem; after updating to the latest stable version of docker for windows, v2.1.0.0, it crashes on startup with a similar error message as lgiduthuri reported above.
`Unable to create
   ved Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- Slutt på stakksporing fra forrige plassering der unntak ble iverksatt ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   ved Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   ved Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   ved Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()`

A crash report has been uploaded with diagnostic id: 1E68929C-6164-4443-B671-A9A1E4D9AE06/20190801085055

**Comment by mkirkevo** [comment]
I have just as well installed Docker Desktop for Windows and have the same error condition upon attempting start Docker Desktop.

```
Unable to create
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()
```

diagnostic ID: 410B5B33-3EF7-42B4-8B5D-C4ACE4D9038F/20190801145707

Steps to reproduce:  Install Docker for Windows and attempt to start.

**Comment by mkirkevo** [comment]
I believe I found my issue with this.  
I had previously had VirtualBox installed and when uninstalled it left the VBOX network drivers in place.  I was able to remove those and that allowed Docker Desktop to create the HyperV virtual switch and complete startup.

Reference article I found to this: https://dottech.org/101997/how-to-uninstall-virtualbox-drivers-on-windows/

**Comment by chrjsorg** [comment]
Same issue on windows computer I have to use. :(

Diagnostic Id:
C0857F11-0413-49B9-A0A6-24E747C7B173/20190802094627

**Comment by prudnikovdbison** [comment]
Same Issue..... Its so dangerous to update docker.....

Diagnostic Id:
4932DC0D-893D-4E4F-8709-F19C96E533E3/20190808083651

**Comment by mat007** [comment]
@chrjsorg here is I think the relevant part of the logs
```
[11:45:44.030][PowerShell        ][Error  ] Die Ausf�hrungsrichtlinien wurden von Windows PowerShell erfolgreich aktualisiert, die Einstellung wird jedoch von einer in einem spezielleren Bereich definierten Richtlinie �berschrieben. Aufgrund der �berschreibung wird die aktuelle geltende Ausf�hrungsrichtlinie "Unrestricted" f�r die Shell beibehalten. Geben Sie "Get-ExecutionPolicy -List" ein, um die Ausf�hrungsrichtlinieneinstellungen anzuzeigen. Weitere Informationen erhalten Sie mit "Get-Help Set-ExecutionPolicy".
```
My German is a bit rusty but if this refers to powershell scripts not able to be executed due to some signing issue, I believe this has been fixed in the new Stable 2.1.0.1 release.
You can download it from https://download.docker.com/win/stable/37199/Docker Desktop Installer.exe

**Comment by mat007** [comment]
@prudnikovdbison I think it’s the same issue as ☝️ , your log file has the same error message.

**Comment by mat007** [comment]
@lgiduthuri I’m unsure what your diagnostics ID is, and therefore cannot look at your log files.

**Comment by darknoon29** [comment]
Same issue here : i have VirtualBox installed too.
Diagnostic Id:
1D12EDFF-EE20-4147-BB16-92D1FE596C69/20190902093951
