### ISSUE TITLE
Docker for Windows Crash

### ISSUE THREAD

**Issue by eakerma** [docker/for-win#4338]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mikeparker** [comment]
Please fill out the issue template, most importantly including:
* What the problem is
* A diagnostic ID for us to see your logs
* How to reproduce the error (what is your setup).
