### ISSUE TITLE
Freshly installed and firstly runned Docker doesn`t work

### ISSUE THREAD

**Issue by avillia** [docker/for-win#4347]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 08DA0031-5C09-41FC-8CB6-62B7C6735CA0/20190731184806

### Behavior
  - Trying to run docker at first time, got this.
  - Just doesn`t running, even after enabling virtulaization and reloading HyperV
### Information

  - Windows Version: Windows 10 LTSC
  - Docker Desktop Version: 2.1.0.0 (36874)

**Comment by mikeparker** [comment]
```
[21:47:39.263][IsoConfig         ][Warning] Error while migrating PKI from C:\Users\Admin\AppData\Roaming\Docker\pki : �������� �� ����� ���� ��������������.
��� ���������: path1
```

**Comment by mikeparker** [comment]
See https://github.com/docker/for-win/issues/3375#issuecomment-515808417
