### ISSUE TITLE
Unable to start Docker after upgrade to 2.1.0.0

### ISSUE THREAD

**Issue by reebr** [docker/for-win#4348]
### Expected behavior
- Start Docker without problems.

### Actual behavior
- Unable to start Docker.

<kbd>![image](https://user-images.githubusercontent.com/3982052/62241416-80057200-b3af-11e9-8bd7-19f0f466f725.png)</kbd>

### Information

- Is it reproducible?
  - Yes, just have to update from 2.0.0.3 to 2.1.0.0
- Did the problem appear with an update? Yes
- Windows Version: 10 Pro x64 (1809 - 17763.615)
- Docker Desktop Version: 2.1.0.0
- Diagnostic ID: FCBFD225-F22F-49A9-A46C-8C9BE278C2D6/20190731191526

### Steps to reproduce the behavior
- Update Docker from 2.0.0.3 to 2.1.0.0.
- Try to initialize Docker.
- The crash occurs.

**Comment by alexkb** [comment]
I just upgraded to 2.1.0.0 too, and had the same error. After a reboot the issue went away though.

**Comment by dovahkiin16** [comment]
Same Issue I'm having after upgrading to 2.1.0.0 too, and had the same error. the problem persists even after restarting my Workstation

**Comment by mikeparker** [comment]
From your log file:
```
Not enough memory in the system to start the virtual machine DockerDesktopVM.
Could not initialize memory: Ran out of memory (0x8007000E).
'DockerDesktopVM' failed to start. (Virtual machine ID 42F00BEC-8864-43A8-81AE-31C5C4585FEC)
Not enough memory in the system to start the virtual machine DockerDesktopVM with ram size 2048 megabytes. (Virtual machine ID 42F00BEC-8864-43A8-81AE-31C5C4585FEC)
'DockerDesktopVM' could not initialize memory: Ran out of memory (0x8007000E). (Virtual machine ID 42F00BEC-8864-43A8-81AE-31C5C4585FEC)
```

**Comment by mikeparker** [comment]
@alexkb and @dovahkiin16 can you upload logs or a diagnostic ID so I can check if you're also having a memory problem or if its a separate issue?

**Comment by reebr** [comment]
@mikeparker this memory-related error is strange, but it gave me an idea of what it might be.

Anyway, why this friendly message is not displayed on the interface anymore? It's much easier for us to diagnose a problem by using this message instead of only seeing the stack trace.

**Comment by 3komma14** [comment]
I have the same issue. Restart doesn't help.  
Diagnostic ID = 4514AB46-36A1-46D9-A078-AA9136CDE32C/20190802105340

**Comment by mikeparker** [comment]
@reebr I agree, I've opened an item so we can ensure the out-of-memory error is displayed on the UI if possible.

**Comment by reebr** [comment]
@mikeparker thanks, I'll close this issue since the problem was memory related (and I was able to initialize the Docker normally).

@3komma14  @dovahkiin16
Maybe you guys should create a specific issue for your related problems.
