### ISSUE TITLE
Error response from daemon: Unknown instruction: HYDRATE

### ISSUE THREAD

**Issue by bhumesh** [docker/for-win#435]
### Expected behavior
Should give * BUILD SUCCEEDED *
### Actual behavior
Sending build context to Docker daemon 112.6 kB
Error response from daemon: Unknown instruction: HYDRATE
### Information
I am trying to generate sample image using provided here https://github.com/jkingyens/docker4xcode but ran into this issue. Below is docker information:

$ docker -v
Docker version 1.13.0, build 49bf474

$ docker info
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 2
Server Version: 1.13.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.4-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: IK3E:Z44U:5NIH:44TX:FAQG:VROG:F64M:RB5F:NVT2:IR37:UBRO:TLDP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 23
 Goroutines: 32
 System Time: 2017-01-27T08:22:31.302389943Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

### Steps to reproduce the behavior

  1. Download or clone https://github.com/jkingyens/docker4xcode
  2. follow video https://www.youtube.com/watch?v=CGHOH9Ocl1k

**Comment by friism** [comment]
`HYDRATE` is not a Dockerfile instruction. It appears to be invented by the xcode-related project you reference, which is not affiliated with Docker.

Here's a Dockerfile reference: https://docs.docker.com/engine/reference/builder/

**Comment by poojasree** [comment]
Error response from daemon: Unknown instruction: M
