### ISSUE TITLE
Docker 2.1.0.0 update does nothing after downloading package, restarts VM after a few minutes

### ISSUE THREAD

**Issue by AaronFriel** [docker/for-win#4350]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

I cannot upload diagnostics from this machine for compliance reasons.

### Expected behavior

Clicking "Install Update" on the update prompt (screenshot below) should install the update

![image](https://user-images.githubusercontent.com/788800/62241082-52a7cc80-b38d-11e9-9880-131ce9bcf673.png)

### Actual behavior

I get a UAC prompt, then I see this:

![image](https://user-images.githubusercontent.com/788800/62241122-67846000-b38d-11e9-8fd2-303e0f4d9ca4.png)

That then disappears after a while, while I observe this behavior. (I'm not saying any of this is incorrect, just that this is what I observe):

1. While the "Installing Docker Desktop" window is up, `docker ps` does not work and the `DockerDekstopVM` is off. (I think this is expected behavior.)

2. The prompt then disappears. I don't know what it's doing at this point, but the Docker icon disappears from the taskbar notification tray list.

3. ???

4. At least once while doing this (see next point), the `DockerDesktopVM` restarted before I did anything else, but there was still no icon in the task tray. Or at least, it did once. I don't know what triggered that. At that point `docker ps` works, but there's no Docker icon in the taskbar notification tray.

5. Seeing that nothing is happening, I click start, run, and start Docker Desktop again, at which point I see the notification tray icon again, and this pops up:

![image](https://user-images.githubusercontent.com/788800/62241586-4a9c5c80-b38e-11e9-9d83-47d4fa1e31fa.png)

Looks familiar! 

I've now done this six or seven times I think.

### Information

  - **Is it reproducible?** Yes. It happens every time I click "Install Update".
  - **Is the problem new?** Yes, previous updates installed correctly.
  - **Did the problem appear with an update?** Technically yes? But I would really like the update to appear.
  - Windows Version: Windows 10 1903
  - Docker Desktop Version: 2.0.5.0 (35318)

**Comment by glours** [comment]
Yes, in some specific cases the auto-updater of the 2.0.5.0 briks the upgrade process :-/
