### ISSUE TITLE
Docker Desdktop 2.1.0.0 Edge issues with GUI - not showing up at all

### ISSUE THREAD

**Issue by gillesdouaire** [docker/for-win#4351]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
After the upgrade from Edge 2.0.5.0 to 2.1.0.0, I should be able to navigate to the UI, and modify the settings.

### Actual behavior
When I click on settings, no UI pops up. I can't access the UI. Also, the About windows is blank -- shows no version details, nothing. 
![image](https://user-images.githubusercontent.com/29061201/62241735-bdfe9800-b3a7-11e9-9617-e26f00334ef7.png)

Happens on two different Windows machines I tried installing it on, see Windows versions below.

### Information
  - Windows Version: 10.0.17763.379 and 10.0.17134.885
  - Docker Desktop Version: 2.1.0.0 Edge

### Steps to reproduce the behavior
  1. Upgrade to 2.1.0.0 Edge.
  2. As soon as the install is done, try accessing the UI via the toolbar icon. Won't work. The logs show nothing abnormal.

**Comment by gillesdouaire** [comment]
Also: reboot does not change this situation.

**Comment by glours** [comment]
Did you try to restart Docker Desktop? 
Can you click on troubleshoot menu & send us your diagnostic please (update the issue with the diag number)

**Comment by gillesdouaire** [comment]
Unfortunately, I can't run diagnostics... The troubleshoot menu will pop up, but it's not usable. For instance, it says that the Docker Engine is stopped, but it's not accurate. See image below - the menu shows the red flagged Docker Engine, but at the same time, I can `docker run hello-world` successfully.

![image](https://user-images.githubusercontent.com/29061201/62293089-ce5d5400-b435-11e9-9a5b-cdab442e7a64.png)

**Comment by mikeparker** [comment]
Can you upload a diagnostic please? I'd like to see the log file. There might be an error trying to load the new UI.

**Comment by gillesdouaire** [comment]
I stopped Docker Desktop, restarted it and then tried accessing settings, the about menu and the diagnostic menu. The log file covers all activities since the restart. 
[log.txt](https://github.com/docker/for-win/files/3462361/log.txt)

**Comment by gillesdouaire** [comment]
Upgrading to 2.1.1.0 Edge did not resolve this...

Do you need more logs?

**Comment by gillesdouaire** [comment]
One machine still has this UI issue, on the other one, it resolved by itself.

/remove-lifecycle stale

**Comment by gillesdouaire** [comment]
2.2.1.0 edge fixes it (finally)

**Comment by mat007** [comment]
Great, sorry it took so long!
