### ISSUE TITLE
Docker Desktop stable download does not work, says I need to uninstall Docker Desktop Enterprise

### ISSUE THREAD

**Issue by AaronFriel** [docker/for-win#4352]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

I cannot upload diagnostics due to compliance reasons.

### Expected behavior

I have been stuck trying to update to 2.1.0.0 (see #4350), and so I downloaded the latest version of Docker Desktop for Windows, I downloaded the signed executable here: https://download.docker.com/win/stable/Docker%20for%20Windows%20Installer.exe and it appears to have downloaded version 2.0.0.31259

I expected the installer to run and well, install.

### Actual behavior

I see a window titled "Installing Docker Desktop" with the text "You need to uninstall Docker Desktop Enterprise in order to install Docker Desktop Community" see screenshot:

![image](https://user-images.githubusercontent.com/788800/62242011-22612d80-b38f-11e9-9ce7-f07a32457a1a.png)

I am, however, running Docker Desktop Community 2.0.5.0 (35318), see screenshot:

![image](https://user-images.githubusercontent.com/788800/62242058-37d65780-b38f-11e9-9523-25c64ab7b518.png)

### Information
  - **Is it reproducible?** Sure, it happens every time I run the installer.
  - **Is the problem new?** Unsure.
  - **Did the problem appear with an update?** See #4350, so, maybe?
  - **Windows Version:** Windows 10 1903
  - **Docker Desktop Version:** 3.0.5.0 (35318)

**Comment by glours** [comment]
Can you try to update with [the next edge version](https://download.docker.com/win/edge/36873/Docker%20Desktop%20Installer.exe) and not the stable one?

**Comment by mikeparker** [comment]
> I downloaded the signed executable here: https://download.docker.com/win/stable/Docker%20for%20Windows%20Installer.exe and it appears to have downloaded version 2.0.0.31259

Apologies for the confusion - this is an old download link, and as you've noticed you'll get an old version which gets confused if you try to install on top of a more recent version. The reason for the download link changing is because `Docker for Windows` was renamed `Docker Desktop`. For now we've updated that link so it'll work so if you try again you should get 2.1.

**Comment by AaronFriel** [comment]
Using the Edge installer worked fine.

**Comment by mikeparker** [comment]
We've added a release note about the linked issue and updated the old download link so I'm closing this. Thanks for the report!
