### ISSUE TITLE
restarting after upgrade

### ISSUE THREAD

**Issue by fabiobusnello** [docker/for-win#4353]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by reebr** [comment]
?

**Comment by mikeparker** [comment]
This issue does not contain enough information for us to help. Please open a new issue and fill out the issue template, most importantly including:
* What the problem is
* A diagnostic ID for us to see your logs
* How to reproduce the error (what is your setup).
