### ISSUE TITLE
Docker Desktop breaks in update with windows sandboxing

### ISSUE THREAD

**Issue by mdegans** [docker/for-win#4356]
During an upgrade to the latest version of Docker Desktop,

windows sandboxing blocked access to my desktop from goqaajox.0o0.exe

The update hung, and Docker is now half-uninstalled.

[screenshot here](https://i.imgur.com/SgM6caa.jpg)

**Comment by mikeparker** [comment]
I'm unsure this process is anything to do with us, it looks somewhat like malware. How exactly did you install docker desktop and how did you update it?

**Comment by mdegans** [comment]
I installed Docker Desktop with the Windows installer available [here](https://www.docker.com/products/docker-desktop).  It broke when it auto-updated. I have my doubts that it's malware since this is a brand new machine with stock Windows (Surface), I have relatively few things installed (pycharm, clion, creative cloud, vscode, vs, steam, Skyrim, and that's about it), and I've never actually used docker on this machine.

To replacate what I did, I:

- installed docker desktop 2.0.0.2 on Windows 10 pro, 18362.239
- turned on Controlled Folder Access
- at some point Docker Desktop prompted for an update.
- [it hung at "removing files"](https://i.imgur.com/VuvHDxJ.jpg) and windows notified me of the block. I just tried it again and the blocked binary is [another name entirely](https://i.imgur.com/DZe2Wpb.jpg).
- i unblocked, but the installer was still stuck, so i killed it, leaving docker half-uninstalled

**Comment by fguitton** [comment]
This has been an outstanding issue for a very long time. On my side it has to do with the installer trying to create shortcut (which I don't want) on my Desktop (which is protected via Windows Controlled Folders). Since the installer as a random name it is not possible to predictably add a rule to let it pass in the Windows Security Center. Nevertheless the installed should not fail for a desktop shortcut, the rest of the files are installed properly and docker would be perfectly functional.

**Comment by mdegans** [comment]
Shortcut creation seems the likely culprit. My "solution" has been to simply not use Docker Desktop. Docker runs find in a HyperV instance which is what Desktop does anyway.

Plus I don't need/want it to access my C drive at all, really. Goodness, I was horrified when I saw it had enabled a network share for my C drive and I could access it from the network.

**Comment by mikeparker** [comment]
You're right there are issues with the installer adding the desktop shortcut, we'll either provide a checkbox to enable/disable it or simply remove it altogether. Thanks for the info!
