### ISSUE TITLE
Run only docker engine wsl2 and not the old docker engine

### ISSUE THREAD

**Issue by codingarchitect** [docker/for-win#4357]
Hi,
I am running docker for windows wsl2 tech preview.
Will it be possible to run only docker engine wsl2 and not the old docker engine.
Right now, the old docker engine always runs when I start docker desktop.
Can this be switched off while keeping the wsl2 preview docker engine running?

If I quit docker for desktop, the wsl2 preview docker engine as well exits.

Thanks,

**Comment by gtardif** [comment]
Hi, currently you can switch to windows containers (that will not require the VM for linux containers), and when restarting Docker Desktop, it should not restart the Linux VM. Then use the WSL2 tech preview as you do now.

**Comment by hurie** [comment]
Or you can stop old docker engine using hyper-v manager.

**Comment by codingarchitect** [comment]
Thanks @gtardif and @hurie for the suggestions.

**Comment by TimJones** [comment]
@hurie I found the Docker Desktop simply restarts the HyperV VM after some time.

**Comment by Hades32** [comment]
why is this closed? That's not really solved and it's pretty inconvenient

**Comment by mschnee** [comment]
Seconded, why is this closed?  Starting Docker Desktop, and the HyperV VM, breaks my system's networking for an entire 5 minutes.  I only want to be using the wsl2 engine, and I only want to start it alone.  Is `Docker Engine` necessary for `Docker Engine WSL2` to run?

**Comment by stephen-turner** [comment]
See my response in #4700.
