### ISSUE TITLE
Docker does not run - create VM in Hyper-V  "Unable to destroy: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Invalid class"

### ISSUE THREAD

**Issue by Ltek** [docker/for-win#436]
### Expected behavior
docker fresh install should start and create VM in Hyper-V

### Actual behavior
does not create VM and throws error...

Unable to destroy: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Invalid class

at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
at Docker.Backend.ContainerEngine.Linux.DoDestroy(Boolean keepVolume)
at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.b__0(Object[] parameters)
at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

### Information
6833C2FA-3890-4713-B73C-E9F7490F4044/2017-01-27_07-40-37
Window 10 Pro, all MS updates installed (to-date)

### Steps tried to fix

uninstalling/reinstall docker stable and beta - several times
removed all Hyper-V virtual NICs and VMs.
Cleaned using JV16 power tools and CCleaner
reboots between all steps
uninstall/reinstall Hyper-V

**Comment by Ltek** [comment]
I did several web searches and it looks like this is a fairly common problem and has been for a long time. Is the Docker team going to address this? ... is there a fix, or is this going to be logged as a Known Bug or it is just being ignored?

**Comment by simonferquel** [comment]
Your Windows installation seem to have problems : can you try to run a simple `Get-NetIPAddress` in powershell ? We are relying on it for VM setup and it seems to fail (witch shouldn't happen)

**Comment by efraser67** [comment]
Having the same issue when changing Switching back from using Windows to Linux containers...  Any progress on this?

**Comment by rneugeba** [comment]
@efraser67 do you have a diagnostics ID for us to take a look at?

**Comment by efraser67** [comment]
F1E7D54E-50D7-4184-A0A5-D31126969C88/2017-02-15_11-05-35

**Comment by efraser67** [comment]
Also get the same error when trying to Reset to Default under settings...

**Comment by efraser67** [comment]
Folks,

I was wondering if there may be a work around for this as it is making it impossible to work with docker.  Every time I attempt to download an image it stops me letting me know that the image won't work with the Windows OS.  I've even tried to install a separate boot2docker vm and connect to it with PS.  Which tells me it can't use the certificate due to an X509 error.

Any and all help would be GREATLY appreciated!

Regards,
Ed

**Comment by henningst** [comment]
I'm getting the exact same error almost every time I reboot Windows 10.

I usually get it up and running after doing "Reset to factory defaults" a couple of times. Resetting once rarely works, so it has to be done multiple times.

Here are a couple of error dumps:
600E8F38-6852-4E3B-BEC7-43B00FE475FD/2017-02-23_10-00-56
600E8F38-6852-4E3B-BEC7-43B00FE475FD/2017-02-23_10-01-50

**Environment**
Windows 10 Pro version 1607 build 14393.693 running on a Mac Book Pro using Boot Cap 6.0.

**Comment by kwiniarski** [comment]
I also had similar problem with ErrorActionPreference. When tried in console `PS C:\Program Files\Docker\Docker\resources> .\MobyLinux.ps1 -Create` I was getting:

```
New-NetIPAddress : Nie można odnaleźć elementu.
At C:\Program Files\Docker\Docker\resources\MobyLinux.ps1:164 char:23
+ ... rkAdapter | New-NetIPAddress -AddressFamily IPv4 -IPAddress $switchAd ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (MSFT_NetIPAddress:ROOT/StandardCimv2/MSFT_NetIPAddress) [New-NetIPAddress], CimException
    + FullyQualifiedErrorId : Windows System Error 1168,New-NetIPAddress
```

The only way I managed to fix it was to provide DockerNat DeviceId as a string. I have replaced in MobyLinux.ps1 `$networkAdapter = Get-NetAdapter | ? { $_.DeviceID -eq $vmNetAdapter.DeviceId }` with `$networkAdapter = Get-NetAdapter | ? { $_.DeviceID -eq "{177CF6B-3FF3-4BAE-A87A-8C4226482D56}" }` and it worked.

**Comment by Migronon** [comment]
I had the same issue. Docker was crashing every time I started it. Resetting it to factory defaults did not help. 

@simonferquel 's comment about "Get-NetIPAddress in powershell"  provided the important hint, as it also didn't work for me. I was finally able to resolve the issue by resetting wmi as described here: https://superuser.com/questions/1152280/get-net-powershell-cmdlets-failing-with-invalid-class.

**Comment by jasonbivins** [comment]
Closing this - will write a kb including links to:
https://blogs.technet.microsoft.com/askperf/2014/08/11/wmi-missing-or-failing-wmi-providers-or-invalid-wmi-class/
