### ISSUE TITLE
WSL 2 Tech Preview option is not shown

### ISSUE THREAD

**Issue by peteromio** [docker/for-win#4361]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 10CC6966-5EF5-4840-9C55-A88B8E5C878C/20190801061905

### Expected behavior
" the Docker Desktop menu displays the WSL 2 Tech Preview option."
### Actual behavior
the Docker Desktop menu does not show the WSL 2 Tech Preview option.
### Information
  - Windows Version: winsdows 10 pro insider preview fast ring 18950.1000.
  - Docker Desktop Version: 2.1.0.0(36883)
  - wsl: ubuntu18.04 wsl v2

### Steps to reproduce the behavior
I had not previously installed docker, ubuntu18.04 does not have a classic docker installation either. Docker starts correctly by default (hyper-v but not wsl2 mode because that option does not appear).

**Comment by chenzihaojie** [comment]
The same problem.
Windows Version:  Windows 10 Pro Insider Preview 18945.1001

**Comment by hurie** [comment]
Mine resolve with leave ubuntu console open while installing docker desktop preview. If it not working try to login first.

**Comment by peter-developer** [comment]
Without reinstalling docker, I restarted windows, opened wsl on the console before docker, and the option still didn't appear, restarted windows again, I did the same steps and now the option appears.

**Comment by chenzihaojie** [comment]
I restarted windows again and again , also opened wsl on the console before docker , but it didn't work!

**Comment by unikzforce** [comment]
it doesn't work. it's not showing.

**Comment by simonferquel** [comment]
@gtardif @mat007 can it be related to a feature flag cache ? I am running the TP (build 36883) on Windows build 18945 without issue.

**Comment by simonferquel** [comment]
Can you try to remove `already-enabled-features.json` and `features-cache.json` from `C:\Users\<username>\AppData\Roaming\Docker` and restart docker desktop ?

**Comment by unikzforce** [comment]
I'm sorry, My windows build number 1s 18941 but WSL 2 Tech preview needs 18945 or higher

**Comment by unikzforce** [comment]
anyway I'm currently using windows build 18950 and still nothing shows up

**Comment by gtardif** [comment]
@simonferquel it could be related to a feature flag cache (although we have not seen issues with this previously on windows), or if some users are not connected when starting Docker Desktop, it would then start Docker Desktop but not activate the Tech Preview feature. 
Restarting Docker while being connected should reload the feature files and activate the WSL2 feature.
@unikzforce @chenzihaojie can you check if `C:\Users\<username>\AppData\Roaming\Docker\features-cache.json` contains a feature `wsl2V0` ?

**Comment by chenzihaojie** [comment]
![2019-08-02_161215](https://user-images.githubusercontent.com/13294789/62354846-529bfe00-b540-11e9-8558-5be52ce0a2af.png)
There is no file named "features-cache.json"

**Comment by chenzihaojie** [comment]
@simonferquel  @gtardif  can you share the file with me ?

**Comment by simonferquel** [comment]
I really think there is something weird happening related to feature activation here. Maybe something with localized Windows installation ?

**Comment by chenzihaojie** [comment]
> I really think there is something weird happening related to feature activation here. Maybe something with localized Windows installation ?

How could I manually active the feature ?

**Comment by arajala** [comment]
Same problem here, Windows 10 Enterprise 10.0.17134. Deleted the app data files mentioned above, they do not fix the issue and so far have not regenerated.

**Comment by binkley** [comment]
I have same question as @chenzihaojie -- is there a safe way to edit the features cache json file, and enable WSL2?

**Comment by greggmarshall** [comment]
I'm having this issue to.

I don't see anything related to WSL2 in features-cache.json

@gtardif what do you mean by "some users are not connected when starting Docker Desktop"?  Am I supposed to be connected some way???  If so, how do I do that?

**Comment by dgenezini** [comment]
> 
> 
> Mine resolved with leave ubuntu console open while installing docker desktop preview. If it not working try to login first.

Solved this way, but I've uninstalled docker before installing with Ubuntu bash opened.

**Comment by junwatu** [comment]
I have the same problem. I have Windows with version i 18980.vb_release.190907-1301 and Ubuntu installed but after i uninstalled Ubuntu and install "Ubuntu 18.04 LTS" version, strangely WSL 2  Tech Preview option is shown on Docker Desktop

**Comment by chenzihaojie** [comment]
> I have the same problem. I have Windows with version i 18980.vb_release.190907-1301 and Ubuntu installed but after i uninstalled Ubuntu and install "Ubuntu 18.04 LTS" version, strangely WSL 2 Tech Preview option is shown on Docker Desktop

Solved this way, thx

**Comment by coltenkrauter** [comment]
@junwatu 
> I have the same problem. I have Windows with version i 18980.vb_release.190907-1301 and Ubuntu installed but after i uninstalled Ubuntu and install "Ubuntu 18.04 LTS" version, strangely WSL 2 Tech Preview option is shown on Docker Desktop

Can you provide more explicit details of your fix? I am battling this 🤕 

For example, was Docker 2.1.2 installed and running when you installed Ubuntu 18.04 LTS? Or did you reinstall Docker after install Ubuntu? Was a reboot required?

I've been trying all of these with no luck thus far.

**Comment by coltenkrauter** [comment]
I am wondering if I can manually create my own wsl docker context. Would someone be willing to export their wsl context and share it? 

```
# Creates a file with the context information
docker context export wsl
```

It would be much appreciated.

**Comment by grahame** [comment]
I hit this. I had "Ubuntu" installed from the Microsoft Store, with WSL 2 enabled. It was running.

I then tried to install the tech preview. I got an error that my existing Docker installation was already up to date.

I uninstalled Docker.

I installed Docker Tech Preview from https://download.docker.com/win/edge/36883/Docker%20Desktop%20Installer.exe

The option did not appear in the context menu.

Based on what was mentioned here, I then uninstalled 'Ubuntu' and installed 'Ubuntu 18.04' from the Microsoft store. These seem to be different apps, even though they seem to (in the end) install the same actual version of Ubuntu.

After installing and enabling WSL2, and rebooting, the option appeared in the context menu.

**Comment by junwatu** [comment]
@coltenkrauter  in my case there was no need to uninstall Docker or need a reboot but you can see @grahame detail answer for other solution.

**Comment by drahen** [comment]
Try this:
If you install "Ubuntu" version, execute `wsl -s Ubuntu`
If you install "Ubuntu 18.04" version, execute `wsl -s ubuntu 18.04` as per Docker documentation

Then (maybe) restart your pc.

I am using "Ubuntu" version from Microsoft Store and not "Ubuntu 18.04".

**Comment by coltenkrauter** [comment]
Version 2.1.4.0 should fix our issues! 

https://docs.docker.com/docker-for-windows/edge-release-notes/

I'm downloading it now.

**Comment by ptflp** [comment]
remove old docker, and install new docker desktop (solved)

**Comment by eXigentCoder** [comment]
Mine wasn't showing no matter which version of Ubuntu I installed so I just left it and carried on with my other work for about 30 min after logging in to docker desktop and having Ubuntu open. Just checked on it now and the option is there (definitely wasn't showing once my PC initially booted up). However now it's just showing `Loading...` like in #4734. Going to update to 2.1.5.0 to see if that fixes the last issue

* Using `Ubuntu` from the store and not `Ubuntu18.04`
* Docker 2.1.4.0
* Windows 10 pro build 19013

**Comment by eXigentCoder** [comment]
Looks like the flag has been moved into settings in `2.1.5.0`, confirmed by the [release notes]

(https://docs.docker.com/docker-for-windows/edge-release-notes/)
![image](https://user-images.githubusercontent.com/8137674/68186520-0633e480-ffad-11e9-8e89-2fdac626f3db.png)

**Comment by Radi8621** [comment]
@eXigentCoder Looks the same on my device, cant seem to find any clues why. 
Have you goten any new hints, thanks in advance.

**Comment by ironerumi** [comment]
@Radi8621 I suppose docker have a updated intro for wsl2
[Docker Desktop WSL 2 backend](https://docs.docker.com/docker-for-windows/wsl-tech-preview/)

I updated to `2.1.6.1`
![image](https://user-images.githubusercontent.com/39033099/69402290-b5f1ac00-0d3a-11ea-93cb-345e7bdcb858.png)
"wsl" is still there, however, it seems docker is still using the "default" context even I followed the instruction.
![image](https://user-images.githubusercontent.com/39033099/69402357-f05b4900-0d3a-11ea-9f38-ea75ba936c5f.png)
![image](https://user-images.githubusercontent.com/39033099/69402368-f94c1a80-0d3a-11ea-8872-047f671e89da.png)

Although, wsl2 distros are running after docker started.
![image](https://user-images.githubusercontent.com/39033099/69402464-3e704c80-0d3b-11ea-8b19-4528782cb515.png)

Hope there is a way to identify whether docker is using wsl2 or not.

**Comment by simonferquel** [comment]
As soon as the checkbox "Use wsl2 backend" is checked, it totally replaces the Hyper-v VM. You can check there Hyper-v management console and see that docker hyper-v VM is stopped.
As we now have full feature parity, we don't use a separate context anymore for wsl. You can safely remove it using "docker context rm"

**Comment by ironerumi** [comment]
@simonferquel thanks for the info!

**Comment by HissYu** [comment]
I installed 2.1.7.0 first, not seeing the option. Then updated it to 2.2.1.0 with Ubuntu-18.04 console on and finally I got the option.

**Comment by bootids** [comment]
I install docker desktop 2.1.2.0 after opened wsl on the console,then run docker context use wls in powershell.after that,upgrade docker desktop to newest,its worked

**Comment by stephen-turner** [comment]
There have been a lot of changes to the WSL 2 support, is anyone still seeing this on the latest version?
