### ISSUE TITLE
Docker Desktop CE Stable 2.1.0.0 download link is 2.0.0.3

### ISSUE THREAD

**Issue by WeetA34** [docker/for-win#4363]
Hello

I tried to download the latest Docker Desktop CE Stable (2.1.0.0) from official download and stable release notes pages. Both return this link: https://download.docker.com/win/stable/Docker%20for%20Windows%20Installer.exe.
The downloaded version is 2.0.0.3.

Rgds

**Comment by gtardif** [comment]
Thank you for reporting this, this has been fixed now.
