### ISSUE TITLE
Problem with docker desktop 

### ISSUE THREAD

**Issue by jbthummar** [docker/for-win#4365]
- Windows Version: Windows 10 Pro
  - Docker Desktop Version: 2.1.0.0
- Diagnostics ID: 8DC2DBDD-6240-4BE2-B059-6ABABE3E3D6F/20190801074318

**Comment by zappy-shu** [comment]
Please fill out the issue template, most importantly including:

What the problem is
A diagnostic ID for us to see your logs (already done, thank you)
How to reproduce the error (what is your setup).
