### ISSUE TITLE
Out of memory - Issue since latest update

### ISSUE THREAD

**Issue by johnthomas22** [docker/for-win#4368]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 238DDF49-DAE4-4142-82E4-C3E0F69F9485/20190801081500

### Expected behavior

Docker starts

### Actual behavior
Docker fails to start

### Information

  - Windows Version: Version	10.0.16299 Build 16299

  - Docker Desktop Version:

### Steps to reproduce the behavior

Since the last Docker update, Docker Desktop has failed to start with the following messsages:

Unable to start
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

**Comment by mikeparker** [comment]
```
Not enough memory in the system to start the virtual machine DockerDesktopVM.

Could not initialize memory: Ran out of memory (0x8007000E).

'DockerDesktopVM' failed to start. (Virtual machine ID E882D002-05C8-47C9-B90E-303A9C6E22EC)

Not enough memory in the system to start the virtual machine DockerDesktopVM with ram size 2048 megabytes. (Virtual machine ID E882D002-05C8-47C9-B90E-303A9C6E22EC)
```
Can you confirm how much memory is on your machine?

**Comment by johnthomas22** [comment]
8GB.

Guess I'll need to shrink the VM RAM?

Regards,

John Thomas

**Comment by mikeparker** [comment]
Yes that should work, or simply free up some computer memory, close programs, reboot the OS etc. 

Were you running the previous version fine? Was your previous VM using 2GB before the update? (I'm wondering if your VM setting was overwritten during the update). Our memory usage should not have changed, so maybe there's a bug during the update process which takes too much memory. Other users have reported something similar but got it working simply through a reboot.

**Comment by johnthomas22** [comment]
That's odd, Mike. The problem I reported has recurred every day since I
applied the update - about 5-7 days.

I boot my laptop each morning.

This morning, Docker did not fail to start :-) Slightly concerned that if I
reduce the allocated memory, it will have some new problems.

Regards,

John Thomas

**Comment by mikeparker** [comment]
Interesting, thats good to know that it's not just after the upgrade and its on every boot. I suppose our memory footprint has increased slightly since the last version as we have added more features and functionality, maybe you're right up at the edge of available memory. 

If you restart docker after it fails the first time after reboot, does it start working? I'm wondering if you have some startup programs which take the available memory then release it.

Shrinking the VM memory shouldnt have any adverse effects unless you use lots of containers that use all the memory.

**Comment by johnthomas22** [comment]
Mike,

I might not have been clear. Prior to the upgrade Docker Windows Desktop
would not start on most starts. But a restart of Docker Desktop for Windows
worked. Usually. (If I'd started too many other things including Chrome
tabs before restarting Docker, the restart failed, perhaps understandably.)

The error quoted to you was only seen after the upgrade, and except for
this morning, has been seen on every boot since.

I'll let you know what happens tomorrrow!

Regards,

John Thomas

**Comment by mikeparker** [comment]
We are going to release a new version which will make the 'out of memory' error clear to the user, so they can at least ensure they have enough memory free before starting Docker.

It's unclear there is any bug here, but we'll continue to monitor the 'out of memory' bugs being raised and see if its abnormally high.

**Comment by johnthomas22** [comment]
Virtual memory is notoriously difficult to measure...

Good to know you're going to make the errors clearer though. It started
just fine again today, I think the 2GB memory setting is exactly the same
as prior to the upgrade. Not to worry, please close this ticket, if the
problem comes back I'll shrink the memory allocation.

Regards

John

**Comment by johnthomas22** [comment]
Correction.

It's Docker Desktop itself that's failing to start.

Unable to start
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[]
parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean
showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at
Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

So I don't have the option to reduce memory usage.

Regards,

John Thomas

**Comment by mikeparker** [comment]
As a workaround you can manually edit the settings.json file to reduce the VM memory. This usually lives at `C:\Users\(username)\AppData\Roaming\Docker\settings.json`. edit the `memoryMiB` value.

**Comment by ebanisadr** [comment]
I just had this issue too. For me, I was just out of memory. I closed other programs, restarted, and it worked. This is the first time I've used Docker Desktop on windows, and the error was a little more cryptic than I could understand. A nice message that "Docker needs more RAM" would be appreciated because I can solve that on my own without having to search for this thread.

**Comment by johnthomas22** [comment]
Edited the .json file as you suggested and Desktop and my application
started just fine thanks.

Regards,

John

**Comment by johnthomas22** [comment]
Adjusting the memory in JSON file seems to have fixed the issue. 

"As a workaround you can manually edit the settings.json file to reduce the VM memory. This usually lives at C:\Users\(username)\AppData\Roaming\Docker\settings.json. edit the memoryMiB value".

**Comment by adamwelsh** [comment]
This needs to be handled better. Users can back their way into a corner by sliding the memory allocation to the max in the UI, then become locked out of the app from the next restart onward when it crashes at startup. Some how other apps have figured out how to not let you over-allocate. No reason docker can't do better on this.

**Comment by kmshort** [comment]
> This needs to be handled better. Users can back their way into a corner by sliding the memory allocation to the max in the UI, then become locked out of the app from the next restart onward when it crashes at startup. Some how other apps have figured out how to not let you over-allocate. No reason docker can't do better on this.

100% with you there. This just happened to me, and that's what I did. Dragged the slider all the way across. Then crash after crash after crash. I have 64gb ram and I told it that it could use it oops. However it couldn't allocate it, so crash.
Why can't docker try to allocate, if it can't then it says "hey there isn't enough memory - do you want to check and lower the allocated ram amount? Here you go, here's the slider!".
