### ISSUE TITLE
AuthorizationManager check failed. PowerShell execution policy prevents Docker Desktop for Windows 10 starting

### ISSUE THREAD

**Issue by through-a-haze** [docker/for-win#4369]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 97285CAF-6CD0-4CB2-AAED-D63ECFA5A529/20190801084329

### Expected behavior
Docker desktop should start

### Actual behavior
I got the crash report

### Information

  - Is the problem new? **Yes**
  - Did the problem appear with an update? **Yes**
  - I tried to "Reset to factory defaults" with no success
  - Windows Version: Windows 10 Pro 1803, OS build 17134.829
  - Docker Desktop Version: 2.1.0.0 (36874) stable

### Steps to reproduce the behavior

  1. Try to start Docker Desktop
  2. Get the crash report

**Comment by pleforhod** [comment]
The same bug happens to me

**Comment by marcelolx** [comment]
Same for me.

**Comment by through-a-haze** [comment]
> 
> edit: After restart my machine and then restart docker 5x it started working again. 🤔

Restarted my machine only once. Might it be the case? 🤔

**Comment by pleforhod** [comment]
After restart working again

**Comment by through-a-haze** [comment]
Restarted my machine again - didn't help, docker still crashes.

**Comment by marcelolx** [comment]
What is the output for `docker ps -a`?

**Comment by ottens** [comment]
> **What is the output for `docker ps -a`?**
Error response from daemon: i/o timeout

**Error reported by Docker:**
Timed out waiting for the lifecycle-server to start
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

Windows 10 Pro version 1903 with Docker Desktop 2.1.0.0

**Comment by through-a-haze** [comment]
> What is the output for `docker ps -a`?

error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/json?all=1: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

And the error says: "Unable to stop at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()" followed by a stack trace.

**Comment by marcelolx** [comment]
@ottens @through-a-haze Seems really a bug, because on my machine the output doesn't show a error, the only problem was that i couldn't start my containers.

**Comment by through-a-haze** [comment]
@marcelolx I see, in my case it is a docker itself. That crash appears every time I try to start Docker Desktop.

**Comment by AbzM** [comment]
Same here, i am having issues. my docker was updated,. i had crash reports, now docker is running however i cannot access my containers 👎

**Comment by marcelolx** [comment]
> Same here, i am having issues. my docker was updated,. i had crash reports, now docker is running however i cannot access my containers 👎

@AbzM If you run `docker ps -a` what is the output? Are your containers not running, but only not show on `docker ps`?

**Comment by AbzM** [comment]
@marcelolx since doing the update, i created another container, when i run docker ps -a, only the newly created container is listed... it does not seem to identify the other 10 or so containers that I did have prior to the update.

**Comment by mikeparker** [comment]
```
[11:42:32.444][PowerShell        ][Error  ] Windows PowerShell updated your execution policy successfully, but the setting is overridden by a policy defined at a more specific scope.  Due to the override, your shell will retain its current effective execution policy of AllSigned. Type "Get-ExecutionPolicy -List" to view your execution policy settings. For more information please see "Get-Help Set-ExecutionPolicy".
[11:42:32.478][PowerShell        ][Error  ] AuthorizationManager check failed.
```

**Comment by AbzM** [comment]
I wanted to roll back... not sure how. If i go to uninstall docker for desktop, it says its going to wipe out all of my containers.. So i Cancelled.

**Comment by mikeparker** [comment]
Docker Desktop 2.1.0.1 stable has been released with a fix for this now.

**Comment by through-a-haze** [comment]
@mikeparker yes, it works! Thanks!
