### ISSUE TITLE
net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by oferpl** [docker/for-win#437]
### Information

  - Diagnostic ID : A172D1A8-178E-4CA7-8546-82EEBD6FDFE3/2017-01-27_21-00-52

### Steps to reproduce the behavior

  1. Tryied to pull microsoft/iis:nanoserver and failed over "net/http: TLS handshake timeout"

**Comment by dgageot** [comment]
Hi @oferpl Thanks for the report. Can you confirm you can pull other images than `microsoft/iis:nanoserver`? I see errors like `lookup registry-1.docker.io: getaddrinfow: No such host is known.` Maybe it was a transient issue.

**Comment by oferpl** [comment]
That was already resolved. Thanks.

**Comment by WeihanLi** [comment]
Hi @grtdevops ,how do you solve that problem?
When I pull elasticsearch image via `docker pull docker.elastic.co/elasticsearch/elasticsearch:6.4.0` meet the same error.

error details:

> error pulling image configuration: Get https://d2iks1dkcwqcbx.cloudfront.net/docker/registry/v2/blobs/sha256/1a/1ac6765457316224b41e3663704f904473d5480f68eb20c983d91fa014205f9e/data?Expires=1536950844&Signature=iJc7aRS1g28dX1vlnj2MP4go--e4fdPfBC3EKI8xJplo7Lm5ZDjrHIKD84gqKPweXgI3QAWApnh0MxwSjkT1wlSWvxDYApzgNzgjLlB4e7CRXrb9eIqVsSmg3TAJiiTAL4fu2aBPXJfvMUqhzg-EfV46dZaLcq1FyeHc9J2YFy4qZ592ZZbJY7rHhLaqUqKJLLy5bbWJkr49DYoxzCwYJLgUSTQdEU2udmgHJDlNIqxVleQXemjo8ICqH3TV6PTS0f9WgTY~Ev5F5IUq0dIPINL1y3E6SPI69dzZvQ1m92Bw-dbvenSSpyvJJCf5M3GDCaRA2Md9MYW2QxI5vaooZQ__&Key-Pair-Id=APKAIVAVKHB6SNHJAJQQ: net/http: TLS handshake timeout
