### ISSUE TITLE
[QUESTION - LIMITATION] Technical preview - WSL2 Does not detect OpenSuse Leap 15-1

### ISSUE THREAD

**Issue by tebeco** [docker/for-win#4370]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - ⚠ Diagnostics ID: not sure if relevant (might be an actual limitation)

### Expected behavior
Wsl2 activation should detect any wsl2 distro ?

### Actual behavior
![image](https://user-images.githubusercontent.com/2266487/62283026-f0180480-b450-11e9-89b6-119f3b19e088.png)

### Information
  - Windows Version:
![image](https://user-images.githubusercontent.com/2266487/62283048-fc03c680-b450-11e9-9184-100311f4f7d6.png)

  - Docker Desktop Version:
![image](https://user-images.githubusercontent.com/2266487/62283100-16d63b00-b451-11e9-81cd-692fccff78bf.png)

### Steps to reproduce the behavior
<!--
A reproducible case, Dockerfiles with reproduction inside is best.
  1. I properly uninstalled `Docker For Windows` (Stable)
  2. I properly uninstalled every previous WSL 1/2 (`Ubuntu-18.04` + `OpenSuse Leap 15.1
  3. I removed completly any single files on my system i found about docker in `AppData` / `ProgramData`
  4. Re-installed `Docker For Windows - Technical Preview`
  5. Re-installed `OpenSuse Leap 15-1`

The distro is not detected
Is that intended as a technical limitation ?

**Comment by simonferquel** [comment]
Current technical preview only runs on top of Ubuntu 18.04. This limitation will be lifted in an upcoming release.

**Comment by tebeco** [comment]
@simonferquel 

thx for the clarification closing this issue
if you think letting it open so that any body could "watch it" to see when it's resolved
(Unless there is a policy that will automatically close it / like a bot ?)
