### ISSUE TITLE
Docker Compose not using WSL 2 engine

### ISSUE THREAD

**Issue by Silic0nS0ldier** [docker/for-win#4374]
`docker-compose` does not use the daemon selected with `docker context use ...`. This is preventing me from testing out the WSL 2 tech preview, which I had been hoping to road test with some rather heavy projects at my work.

### Expected behavior

`docker-compose up` respects selection made by `docker context use ...`

### Actual behavior

`docker-compose up` always uses the VM based Docker Engine.

### Information

  - Windows Version: Windows 10 Pro `1903, 18945.1001`
  - Docker Desktop Version: `19.03.1, build 74b1e89`
  - Docker Compose version: `1.24.1, build 4667896b`

### Steps to reproduce the behavior

1. Start WSL docker engine.
2. `docker context use wsl`
3, Run `docker-compose up -d` with any arbitrary `docker-compose.yml` setup (e.g. the experimental setup over at https://github.com/userfrosting/UserFrosting).
4. Run `docker ps` and observe none of the containers started are present appear.
5. `docker context use default`
5. Run `docker ps` and observe the containers are present.

**Comment by simonferquel** [comment]
Hi @Silic0nS0ldier,
This is a known issue in docker-compose which does not understand contexts yet (we are working on it cc @ulyssessouza).
In the mean time, you can use the `DOCKER_HOST` env variable and set it to `npipe:////./pipe/docker_wsl` before running docker-compose. This will let it connect to the WSL daemon.

**Comment by simonferquel** [comment]
For better file performance, you should consider putting your files within the WSL file system and use docker-compose from a WSL terminal. This way, no need to set `DOCKER_HOST`.

**Comment by ad-on-is** [comment]
> For better file performance, you should consider putting your files within the WSL file system and use docker-compose from a WSL terminal. This way, no need to set `DOCKER_HOST`.

I'm a bit confused now. What's the benefit of Docker for Windows 2.1.0.0 over installing docker natively in a WSL2 instance?

My setup is as follows:

Windows:
I have `D:/Projects/Web` with a bunch of web-projects, a `docker-compose.yml` with nginx, php-fpm and mysql and mounting everything from D:/Projects/Web to the docker containers.

WSL2
Additionally, for testing and evaluational purposes, I've copied everything from D:/Projects/Web to `\\wsl$` network folder into `/home/add/Web`. Here I also have a `docker-compose.yml` mounting everything from `/home/add/Web` into the docker container.

**Comment by simonferquel** [comment]
There are a few benefits now:
- both CLI and daemons are kept up to date accross windows and wsl
- the same daemon is accessible from both windows and wsl
- bind mounts from windows still work, bind mounts from wsl work faster
- exposed container ports (including both tcp and udp) are forwarded on localhost

In a few months you'll also have:
- CLI and daemons are kept up to date accross windows and all your WSL distros
- All the WSL distros and windows can access the same daemon
- Bind mounts from all WSL distros will be as fast as the current TP single-distro support
- You'll be also able to run Kubernetes on top of the WSL daemon

**Comment by simonferquel** [comment]
There are also all the hidden docker for desktop gems that we are actively working on for WSL2:
- vpn connectivity
- transparent http(s) proxy configuration
- trusted CA synchronization between the host and the distro running docker
- Compose on Kubernetes

**Comment by ad-on-is** [comment]
Ah, I see. Thanks for the clarification. So the only way to get the best I/O performance is to move the files to WSL2.

**Comment by Silic0nS0ldier** [comment]
Thanks @simonferquel, I'll give the work around a go.

I'm guessing that when running `docker-compose` within the context (a terminal session I mean) of WSL, Compose uses the WSL 2 engine by default instead.

**Comment by simonferquel** [comment]
@Silic0nS0ldier correct. It also handles bind mounts using the local file system instead of relying on a 9p network share (which should give you a serious performance boost for all things related to bind mounted files)

**Comment by planetf1** [comment]
Workaround 1 
---
If you are using Windows insider builds with WSL2 (see https://docs.docker.com/docker-for-windows/wsl-tech-preview/)
do the instructions listed, then as per https://github.com/docker/for-win/issues/4374 issue:
```
set DOCKER_HOST=npipe:////./pipe/docker_wsl
```
and then retry the docker-compose command

This time the notebook will start fine.

This also tends to indicate  this is a docker for windows problem

Looking at other workarounds...

**Comment by Silic0nS0ldier** [comment]
Recent changes in WSL2 docker implementation have resolved this, closing.
It may occur again in the future if simultaneous Linux and Windows containers are considered, but for the scope of this there isn't any reason to keep it open.
