### ISSUE TITLE
Cannot Install Preview Release (2.1.0.0) on Windows 10 Home

### ISSUE THREAD

**Issue by yaumilakhir** [docker/for-win#4378]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x]  I have not uploaded Diagnostics because install fails before

### Expected behavior
With the support of WSL2, expect to be able to install the docker desktop on Windows 10 Home

### Actual behavior
Docker desktop still require Windows 10 Pro or Enterprise

![image](https://user-images.githubusercontent.com/9656500/62298474-40b54f00-b49d-11e9-814a-42375b589873.png)

### Information

  - Windows Version: Windows 10 Home Insider Preview Single Language (Build 18950)
  - Docker Desktop Version: 2.1.0.0

### Steps to reproduce the behavior
  1. enable WSL2
  2. install Ubuntu via Microsoft Store
  3. install Docker Desktop Installer.exe

**Comment by mkontani** [comment]
I saw same problem... 😫

**Comment by hakiri** [comment]
I have the same problem, I use this approach instead 
https://nickymeuleman.netlify.com/blog/linux-on-windows-wsl2-zsh-docker

**Comment by reedacorn** [comment]
I also have docker hosted inside wsl2. Are there any disadvantages to this?

**Comment by chakshutandon** [comment]
If you are using the vscode remote containers extension (https://code.visualstudio.com/docs/remote/containers) to develop inside a container, it expects to find a docker daemon on the windows host. I have tried exposing a daemon from wsl to windows, but couldn't get folder mounts to work correctly (maybe they have fixed this) and other issues. Using the preview release 2.1.0.0 , I have been able to use this feature flawlessly on Windows 10 Pro.

**Comment by hakiri** [comment]
Does it work with windows 10 home edition? Currently they said it could works, but it didn't!!

Sent from Windows Mobile 

De : Chakshu Tandon
Envoyé le :lundi 12 août 2019 14:39
À : docker/for-win
Cc : hakiri; Comment
Objet :Re: [docker/for-win] Cannot Install Preview Release (2.1.0.0) onWindows 10 Home (#4378)

If you are using the vscode remote containers extension (https://code.visualstudio.com/docs/remote/containers) to develop inside a container, it expects to find a docker daemon on the windows host. I have tried exposing a daemon from wsl to windows, but couldn't get folder mounts to work correctly (maybe they have fixed this) and other issues. Using the preview release 2.1.0.0 , I have been able to use this feature flawlessly on Windows 10 Pro.

**Comment by jederfreitas** [comment]
The same here, following...

**Comment by mikhailbalin** [comment]
The same

**Comment by jdlee726** [comment]
The same

**Comment by meshwara** [comment]
Any news ?

**Comment by legracen** [comment]
Confirmed the new installers do not currently function for Windows Home either. 

Build 18990.vb_release.190921-1704

I believe it's because the Tech Preview also includes the old version of Docker for Windows that requires a Full Hyper-v instillation. 

Suggestion: Separate the wsl2 tech preview to install without the older version.

**Comment by v2okimochi** [comment]
The same problem.
Could I get and install any old versions of `Preview Release` to Home Edition now?

**Comment by filipebanzoli** [comment]
Same problem here! I hope Windows 10 Home Edition (with wsl2) gets access to docker, as his engineers said:
https://engineering.docker.com/2019/06/docker-hearts-wsl-2/

**Comment by hakiri** [comment]
folks,
Docker for windows is not necessary anymore, instead install WSL 2  (see
here https://www.thomasmaurer.ch/2019/06/install-wsl-2-on-windows-10/) and
install Docker on it as you do for Linux (see here
https://medium.com/faun/docker-running-seamlessly-in-windows-subsystem-linux-6ef8412377aa
)

Then use Docker remote extension on VSCode (see here:
https://code.visualstudio.com/docs/azure/docker and here
https://code.visualstudio.com/docs/remote/containers
and here https://code.visualstudio.com/docs/remote/containers-advanced
)

Enjoy !


Le sam. 12 oct. 2019 à 16:27, filipebanzoli <notifications@github.com> a
écrit :

**Comment by filipebanzoli** [comment]
Awesome! I actually did this in the meantime and indeed it worked! I didn't know about this powerful extension on VSCode, for sure I'll check this out. Thanks for sharing!

**Comment by owennewo** [comment]
I realise I can run docker daemon inside wsl2, however 'Docker for Windows' gives me other benefits e.g. a zero maintenance kubernetes cluster.  

Docker appears to still want people to use 'docker for windows' AFAIK, I'm hoping they'll realize that it can now run on Windows Home for people (assuming you have wsl2) and change the installer to allow this.

**Comment by unshare** [comment]
Well, I've successfully installed and tested Docker Desktop 2.1.6.0 with WSL2 on Windows 10 Home build 19025, but I had to do two workarounds:
- Fake Windows edition to bypass installer checks (similar to #4306, but I've done it slightly differently)
- Edit Docker Desktop config files to enable WSL2 backend (as by default, Hyper-V is required and Docker Desktop panics before one can check the checkbox in GUI)

I'm not sure if Docker Desktop doesn't or won't rely on Windows 10 Pro-only features.
I'm not sure if WSL2 will work this way in production releases either (e.g. WSL2 used to not work on Windows 10 Home initially).

However, it's likely Docker knows something for sure (definitely they know a lot more than their target audience), so why not do this:
- Double-check that Docker Desktop with WSL2 backend uses no Windows 10 Pro-only features and that current WSL2 behaviors are expected to persist into production releases
- Adjust installer so that if Windows 10 Home is WSL2-capable it
  - doesn't panic
  - enables WSL and Virtual Machine Platform features instead of Hyper-V
  - enables WSL2 backend by default (not sure if the latter is installer's job)
- Adjust the Docker Desktop proper so that if Windows 10 Home is WSL2-capable it
  - doesn't panic
  - considers WSL2 backend being enabled as factory default
  - doesn't allow to disable WSL2 backend just in case
- Disabling switching between Linux and Windows containers modes might also be a good idea.
(I'm not aware of Windows Containers being supported on Windows 10 Home)

**Comment by unshare** [comment]
@mikeparker PTAL ^^^

**Comment by unshare** [comment]
AFAIK, there is no public source repository for the installer, so I took a liberty to review it under JetBrains dotPeek.
If my analysis is correct, one can achieve successful installation just by manipulating values in the `app.json` manifest within the package.
But the installer is also responsible for populating `settings.json`, so this step should be revisited in code.
Enabling Windows features is an optional step, but it can be disabled only during initial interactive installation, initial meaning there is no `settings.json` in place.
Certainly, the installer has to do a lot of stuff much better.

**Comment by mikeparker** [comment]
We are enabling Windows 10 Home support as we speak. The code first draft is done just testing and release to go. Should be released on edge shortly (next few weeks) hopefully.

**Comment by sreekanthgs** [comment]
> * Edit Docker Desktop config files to enable WSL2 backend (as by default, Hyper-V is required and Docker Desktop panics before one can check the checkbox in GUI)

@unshare Can you please share the config (K,V) and the file to which you've added this to achieve the end result quoted? I had unchecked the option enable windows feature checkbox, but as you've mentioned, docker desktop panics before start. I really dont want to enable Hyper-V for this. Thank you.

**Comment by unshare** [comment]
@sreekanthgs
```%APPDATA%\Docker\settings.json``` looks self-explanatory to me. ```wslEngineEnabled``` key is there.
I can't share configs (and I wouldn't if I could) as the test environment has long been recycled.

**Comment by sreekanthgs** [comment]
> @sreekanthgs
> `%APPDATA%\Docker\settings.json` looks self-explanatory to me. `wslEngineEnabled` key is there.
> I can't share configs (and I wouldn't if I could) as the test environment has long been recycled.

Thank you. Had seen this. The config param `wslEngineEnabled` param was true for me on install itself without me enabling it but seems that wasn't it. Finally had to enable Hyper V, get docker working and then enable WSL, disable Hyper V again.

**Comment by unshare** [comment]
Well, Docker Desktop has to fail at least once as per my observations.
Like @mikeparker said, no-hassle workflow is in the working.

**Comment by mat007** [comment]
Quick update: the Edge release with WSL 2 on Windows Home will likely be in January.

**Comment by rfay** [comment]
Just want to say @mat007 @mikeparker the fact that you're updating us on this (and other issues as well) is absolutely lovely and just thrilling. Kudos. Thanks!  Also, that you're addressing longstanding issues like this one.

**Comment by hakiri** [comment]
@mikeparker @mat007   Any alpha or indirect version before edge version is vert welcomed ❤️

**Comment by ReissZachary** [comment]
Any news since November? Is there a beta version that supports Windows 10 home somewhere?

**Comment by hakiri** [comment]
So far, we still wait for the Edge release with WSL 2. @mat007 Any link or further details are welcomed !

**Comment by mat007** [comment]
We’re thinking the next Edge release will be available at the end of the month, maybe early February at most.
Sorry for the wait!

**Comment by hakiri** [comment]
@mat007 should the next Edge release support windows home edition easily? Does this existing release support it?

**Comment by snow-jallen** [comment]
I can confirm that modifying any value inside of HKLM\Software\Microsoft\Windows NT\CurrentVersion that says "Core" to "Professional" - that will let you install the latest edge release.  Then before you try to run it, change wslEngineEnabled to true in %APPDATA%\Docker\settings.json like @unshare mentioned.  Those two tweaks worked for me.

**Comment by mkontani** [comment]
I confirmed this issue has been resolved in [version 2.2.2.0](https://docs.docker.com/docker-for-windows/edge-release-notes/#docker-desktop-community-2220)! 🎉 

It works well for me.
