### ISSUE TITLE
'docker-desktop.iso' failed to open because of error: 'The file or directory is corrupted and unreadable.' Latest Docker Desktop (2.1) does not start

### ISSUE THREAD

**Issue by mnotley-reward** [docker/for-win#4379]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: AB7719FD-59FD-4BA6-8902-ED6D7F825BE4/20190801141007 

### Expected behavior
Docker loads with windows startup

### Actual behavior
Docker unable to start

### Information

  - Windows Version: Enterprise Insider Preview 18941
  - Docker Desktop Version: Version: 2.1.0.0 (36874) Channel: stable

### Steps to reproduce the behavior

Unclear on reproduction at this point, this may just be due to me running an unsupported version of Windows. Today's log file errors:

`[09:39:38.162][Moby              ][Error  ] Failed to read Moby's logs: The operation has timed out.
[09:40:07.236][HyperV            ][Error  ] Unable to start: System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'DockerDesktopVM' failed to start.

Synthetic SCSI Controller (Instance ID C2CDE658-D0E2-4258-8A5D-3DD9CFC42873): Failed to Power on with Error 'The file or directory is corrupted and unreadable.'.

Attachment 'C:\Program Files\Docker\Docker\Resources\docker-desktop.iso' failed to open because of error: 'The file or directory is corrupted and unreadable.'.

'DockerDesktopVM' failed to start. (Virtual machine ID 4DCED02E-EFF7-4555-8891-8AAB879F6A1E)

'DockerDesktopVM' Synthetic SCSI Controller (Instance ID C2CDE658-D0E2-4258-8A5D-3DD9CFC42873): Failed to Power on with Error 'The file or directory is corrupted and unreadable.' (0x80070570). (Virtual machine ID 4DCED02E-EFF7-4555-8891-8AAB879F6A1E)

'DockerDesktopVM': Attachment 'C:\Program Files\Docker\Docker\Resources\docker-desktop.iso' failed to open because of error: 'The file or directory is corrupted and unreadable.' (0x80070570). (Virtual machine ID 4DCED02E-EFF7-4555-8891-8AAB879F6A1E)
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at Docker.Core.PowerShell.<>c__DisplayClass13_0.<InvokeAsync>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<InvokeAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<RunCommandAsync>d__11.MoveNext()
[09:40:07.236][Linux             ][Error  ] Failed to start: Unable to start. Let's retry`

**Comment by silencej** [comment]
After upgrading to 2.1.0.0, my docker-for-win also halts in starting. My docker log is a bit like in https://github.com/docker/for-win/issues/13, but complaining "vpnkit.exe: While watching /etc/resolv.conf: ENOENT".

However I try the following and succeed:

```
choco uninstall desktop
choco install desktop
```

May help those who install docker-desktop with choco.

**Comment by mnotley-reward** [comment]
> After upgrading to 2.1.0.0, my docker-for-win also halts in starting. My docker log is a bit like in #13, but complaining "vpnkit.exe: While watching /etc/resolv.conf: ENOENT".
> 
> However I try the following and succeed:
> 
> ```
> choco uninstall desktop
> choco install desktop
> ```
> 
> May help those who install docker-desktop with choco.

manual re-installation of 2.1 stable worked for me too.

**Comment by mikeparker** [comment]
Thanks for the report, trying to figure out what this is. Good to know a reinstall fixed it.

@silencej Just be aware, the chocolatey installer is maintained by someone outside Docker and we can't guarantee what it does or whether it'll work - but i'm glad its working for you.

**Comment by silencej** [comment]
The sad news is, the same issue comes again today. I don't want to reinstall it every time since I have database data volume inside (I am using mssql docker image for sqlserver).

Diagnostics ID:
21C2F29D-4F81-4FD4-A372-975770F6F5A7/20190808070308
21C2F29D-4F81-4FD4-A372-975770F6F5A7/20190808071656

**Comment by mikeparker** [comment]
@silencej i can't see any errors in your log files. What exactly is the problem? Can you paste the error? It seems like a different problem to the OP.

**Comment by silencej** [comment]
@mikeparker It's a little bit like https://github.com/docker/for-win/issues/4449. Mine is like this:

> [14:09:53.284][VpnKit         ][Error  ] vpnkit.exe: While watching /etc/resolv.conf: ENOENT
> [14:09:53.285][VpnKit         ][Info   ] vpnkit.exe: C:\Windows\System32\drivers\etc\hosts file has bindings for localhost astrill.com www.astrill.com members.astrill.com
> [14:09:53.285][VpnKit         ][Info   ] vpnkit.exe: Updating transparent HTTP redirection: {
> [14:09:53.285][VpnKit         ][Info   ]   "exclude": "",
> [14:09:53.285][VpnKit         ][Info   ]   "transparent_http_ports": [
> [14:09:53.285][VpnKit         ][Info   ]     80
> [14:09:53.285][VpnKit         ][Info   ]   ],
> [14:09:53.285][VpnKit         ][Info   ]   "transparent_https_ports": [
> [14:09:53.285][VpnKit         ][Info   ]     443
> [14:09:53.285][VpnKit         ][Info   ]   ]
> [14:09:53.285][VpnKit         ][Info   ] }

The symptom is: docker is in "starting" status for a seemingly endless long time. Now I switch back to v2.0.0.3, and the problem is gone.
