### ISSUE TITLE
Not an issue. Loving the Edge integration with WSL 2

### ISSUE THREAD

**Issue by scrossan-crown** [docker/for-win#4380]
Loving how the edge version of docker for desktop (windows) is integrating with WSL 2 and how it maps the port to localhost / 127.0.0.1 so I can map domains to it in my hosts file (such a god send).

Are you planning to make it so you can turn off the hyper-v (og) docker desktop on start up? 

Just want to say keep up the good work.

**Comment by StefanScherer** [comment]
@scrossan-crown Thank you !!
At the moment you can switch to Windows containers mode, this only starts the Windows engine which takes less resources and doesn't start the Hyper-V VM.

**Comment by mikeparker** [comment]
@scrossan-crown thanks a lot, I will pass on the feedback to the team!
