### ISSUE TITLE
Windows (1903) - Docker Desktop (2.1.0) stops working randomly during use.

### ISSUE THREAD

**Issue by Stereocheck** [docker/for-win#4383]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
2E19CB8C-26E7-400F-91ED-E435D70B1012/20190801160909
### Expected behavior
In the previous version of Docker desktop I could leave my PC, instigating an auto-log-off after some time, then return and log in and continue using docker unhindered. 

### Actual behavior
In the latest version after logging back in, running containers are no longer accessible and interacting with docker gives the following error:
```
PS S:\Docker\Apps> docker container ls
Error response from daemon: open \\.\pipe\docker_engine_linux: The system cannot find the file specified.
```

### Information

  - Windows Version: W10 (1903)
  - Docker Desktop Version: 2.1.0

This is reproducible.
Is resolved by resetting Docker Desktop from the settings menu.
Is not specific to any given container

So I have recently upgraded windows to 1903 from 1703 (I think), and also upgraded to 2.1.0 at the same time (it popped the update up right afterwards so I just did it as I was burning time on updates anyway). I haven't tried reverting versions of DD yet, though I will. Reverting OS versions is not viable unfortunately.

### Steps to reproduce the behavior

  1. ... Start Docker desktop
  2. ... Leave the PC alone, for some time (normally over an hour) (current Windows power plan is the default "Balanced")
  3. ... Log back in

**Comment by ktmitton** [comment]
I've observed the same behavior.

Some additional details on my observations:
- Containers that were running before system restart are still listed in `docker ps` as healthy
- `docker inspect` on these containers doesn't seem to show anything out of the ordinary
- Any command to actually use the container (such as `docker exec` or even `docker kill`) will fail

My workaround for now when I forget to kill containers before a restart is to stop docker, open up C:\ProgramData\Docker\containers, delete everything in that directory, then restart docker.

**Comment by mikeparker** [comment]
Could you clarify as there are multiple types of windows logoff / restart options:

1. Is your machine (a) Locking the screen (leaving apps running) or (b) Logging off (closing all apps) (c) Sleep / Hibernate?
2. Do you have fast reboot enabled?

Thanks!

**Comment by ktmitton** [comment]
I don't think I have fast reboot enabled, but I'll have to verify that.

Simplest way I've replicated it was to spin up a container (last I used was redislabs/redismod), once it was started and I could hit it, then did a full restart of the machine. No sleep or hibernate in my testing.

**Comment by mikeparker** [comment]
@ktmitton Whilst it's definitely an issue, that doesn't sound like the same issue as the OP. The OP says docker commands don't work at all, like `docker container ls`. You're saying `docker container ls` works when you reboot but your _container_ stops working, rather than the _docker engine_ stops working, right?

**Comment by Stereocheck** [comment]
1.. Locking the screen (all apps are still running)
Over a short period of time I can log back in and it still works. Longer periods cause it to happen which suggests a power state transition -  hibernate is disabled so possibly sleep, though I have no settings which control sleep timeouts (admin policy must be enforcing power settings I guess). In fact there are no options for setting sleep anywhere. Display is set to turn off after 240 minutes, though the screen switches off much sooner than that, probably through a monitor timeout. It happens in under 2 hours though, so not sure if that setting has an effect.
 2: Yes fast reboot is enabled.

**Comment by ktmitton** [comment]
@mikeparker ah, I was thinking that was the same error I was getting on `docker kill`, and assumed we were talking about the same thing. I can get a separate ticket entered for my issue.

**Comment by mikeparker** [comment]
@ktmitton you're seeing `Error response from daemon: open \.\pipe\docker_engine_linux: The system cannot find the file specified.`?

**Comment by ktmitton** [comment]
@mikeparker I thought it was, but apparently my memory is terrible, and it isn't. I'm getting `no such container` when I try to `docker exec` into a container, and `docker kill` is just hanging...has been for the last 30 minutes while I try to get more details.

Unless you think otherwise, I'll enter a new issue.

**Comment by mikeparker** [comment]
@ktmitton yes please, thanks!

**Comment by ktmitton** [comment]
@mikeparker turns out there was an existing issue (https://github.com/docker/for-win/issues/4383), I'll add my notes to that.

**Comment by mikeparker** [comment]
@Stereocheck looking at your logs, it looks like various processes tried to wake up and eventually started working, but perhaps not in a timely manner. Do you know how quickly you tried to use the docker command line after logging in, and also do you know if the whale icon was animating (i.e. docker desktop was 'starting')?

Also there are various sessions in your log file ranging from 5am to 7pm, do you know roughly what time you saw this error?

**Comment by Stereocheck** [comment]
@mikeparker It wouldn't have been immediately after logging back in, probably 5 or 10 mins. However the issue is persistent, once it happens it is repeatable till I restart docker. I actually left it in that state till the following day and still got the same error.

**Comment by Stereocheck** [comment]
I'm also starting to think this is actually time invariant, I locked my system and left it for 25 min next time I logged in it happens - the only container running was portainer:
```
docker run -d -p 9000:9000 -v portainer_data:/data portainer/portainer -H tcp://10.0.75.1:2375
```

Thinking about it portainer was probably running last time as well. I'll see if I can repro without portainer running.

**Comment by Stereocheck** [comment]
@mikeparker looks like the lock/unlock was a complete red herring. This just happened whilst I was using docker, one minute working fine, the next I get the error above. Not using portainer.
New diagnostics:
2E19CB8C-26E7-400F-91ED-E435D70B1012/20190805153120

**Comment by Stereocheck** [comment]
Where can I download the previous version? I'd like to revert the version and see if this still happens.

**Comment by mikeparker** [comment]
The docs have all the links to the various versions https://docs.docker.com/docker-for-windows/release-notes/

The last release installer is here https://download.docker.com/win/stable/31259/Docker%20for%20Windows%20Installer.exe

**Comment by djs55** [comment]
@Stereocheck thanks for uploading new diagnostics. It looks like one of the backend processes died and was restarted, but it's stateful and therefore the Docker API forward was forgotten, hence the error accessing `\\.\pipe\docker_engine_linux`
```
[16:30:42.133][ApiProxy          ][Info   ] time="2019-08-05T16:30:42+01:00" msg="proxy << POST /v1.40/containers/6623067861f01838916ca88e8c2a94c0ee7c8059c6a373c9313634683d98cb1b/attach?stderr=1&stdout=1&stream=1 (2h54m51.6183719s)\n"
[16:30:42.142][GoBackendProcess  ][Error  ] Process died
[16:30:47.143][GoBackendProcess  ][Error  ] Auto restarting process
[16:30:47.143][GoBackendProcess  ][Info   ] Starting C:\Program Files\Docker\Docker\Resources\com.docker.backend.exe -addr unix:\\.\pipe\dockerBackendApiServer
```
Obviously it shouldn't have died in the first place, so we'll have to investigate that. We'd also like to make this particular process stateless so the impact of restarts will be less significant.

**Comment by Stereocheck** [comment]
@djs55 OK thanks, is there anything I can do to get more useful info on the process crash itself?

**Comment by djs55** [comment]
@Stereocheck I'll see if I can think of something useful for you to try.

In the meantime, do you know if anything in particular seems to trigger the failure or be correlated with it? Are you using a lot of port forwards? Do they include privileged ports? Perhaps monitor the `com.docker.backend` process in a task viewer and check if it seems to be leaking memory (or perhaps handles?)

**Comment by Stereocheck** [comment]
Nothing obvious comes to mind, the earlier failures were when I was away from my computer so it would have been largely idle. Only port forward is:
```
PS F:\Downloads\Procdump> netsh interface portproxy show all

Listen on ipv4:             Connect to ipv4:

Address         Port        Address         Port
--------------- ----------  --------------- ----------
10.0.75.1       2375        127.0.0.1       2375
```

That forward is to make portainer work. I've snapshotted com.docker.backend in processexplorer, I'll review again tomorrow. I've also set up a postmortem debugger to generate a crash dump, not entirely sure if it'll catch it, but worth a try.

**Comment by Stereocheck** [comment]
So the issue happened overnight, unsurprisingly no crash dump generated. I can run an instrumented version if that helps.

**Comment by Stereocheck** [comment]
@djs55 I attached a debugger and reproduced it
```
Unhandled exception at 0x00007FF8EA5FCC3D (DgApi64.dll) in com.docker.backend.exe. 
```
Looks like a crash caused by an interaction with "Digital Guardian" from Verdasys, some policy installed corporate security software from the look of it.

I have a dump if it's any use, though probably not if it's not even crashing in your code.

**Comment by mikeparker** [comment]
@Stereocheck thats an interesting development. @djs55 for reference some blurb on the DgApi64.dll -> https://www.file.net/process/dgapi.dll.html

> This .dll file can be injected to all running processes and can change or manipulate their behavior. The program has no visible window. There is no detailed description of this service. It can change the behavior of other programs or manipulate other programs. Dgapi.dll is not a Windows core file. It is a Verisign signed file. It is certified by a trustworthy company. Dgapi.dll is able to connect to the Internet, record keyboard and mouse inputs, monitor applications and manipulate other programs. Therefore the technical security rating is 48% dangerous, but you should also take into account the user reviews.

> Important: Some malware camouflages itself as dgapi.dll. Therefore, you should check the dgapi.dll process on your PC to see if it is a threat.

User comments:
> Blocks some programs. Does not allow some programs to run.

> Its corp spyware and kills roboform

**Comment by djs55** [comment]
@Stereocheck @mikeparker this is all very interesting! Assuming this is legitimate corporate security software then perhaps the `com.docker.backend.exe` process (and potentially the other `com.docker.*` processes) need to be added to some kind of whitelist? Since the process is new in this release, possibly there already are whitelist entries for other Docker processes?

**Comment by Stereocheck** [comment]
https://digitalguardian.com/products/digital-guardian-platform/application-whitelisting

**Comment by andrewfinnell** [comment]
I too have the same issue. The docker engine will randomly stop working through out the day. I cannot find anything in common between what I was just doing and the engine crashing. This is also happening to every co-worker on my team since the last two updates.

**Comment by Stereocheck** [comment]
@andrewfinnell is your corporate policy installing Digital Guardian on your machines? (look for DGAgent.exe in task manager)

**Comment by Stereocheck** [comment]
You could try talking to your IT admins to see if they can whitelist the process in DG? Or possibly get them to open a support ticket with Verdasys? Alternatively I don’t know if there’s currently any related activity from the docker dev team, though there is mention above about a more resilient restart mechanism, hopefully that should appear in an update soon. For my current scenario
I’ve switched back to using VMs.


________________________________

**Comment by StoneyEagle** [comment]
I encounter this problem as well.
It happens randomly even when the pc never goes to sleep or gets locked.
In fact it happens while i am using/working multiple containers.
Sometimes they run for 2 hours and sometimes for 20 minutes.
Basically all containers are getting killed and the only fix is rebooting the pc, restarting docker does not help.
Seems to be occurring after the latest update for/of Windows.
Running the same stack on Ubuntu 18.04 and 19.04 bare or from a Ubuntu Hyper-V/VirtualBox on Windows is stable.

**Comment by andrewfinnell** [comment]
@stereocheck My only solution was to revert to a Version that was accepted by Digital Guardian

**Comment by StoneyEagle** [comment]
So i have come to the conclusion that the problem is related to memory on AMD Ryzen in my case.
I have a Laravel stack with multiple php-fpm containers that each run a queue task, one of them is running ffmpeg commands.

I have my stack running on:
   AMD Ryzen-2700x 16GB Windows (14T/5GB assigned)
   Playstation 4 Arch (no restrictions)
   Intel i7-3770 16GB Windows (7T/5GB assigned) (friends pc)

After some tweaking and testing, the containers on the PS4 and my friends pc kept running without failure, while my pc kept crashing to where docker appears to be functional but all the containers are gone and the docker daemon is unreachable while also all the ports that are assigned by docker eg. 80, 3306 where still in use by docker.

I have installed htop in the container that runs the ffmpeg commands and noticed that there is a memory issue that only exist on Ryzen. 
The moment ffmpeg asks for more memory than is assigned to docker / available it crashes.
Both PS4 and Intel stay within the set limit but Ryzen fails to do so.

I have increased the memory to 7GB 
A34C4E95-FFF3-4C12-9859-4F22D3B8D58A/20191012224155
And at 10GB assigned to docker it stops crashing under high load.

I hope this is helpful in fixing the issue.
If someone from the docker team would like to test this, i'll be happy to provide what is needed to do so.

**Comment by hexmode** [comment]
Docker Desktop version: 2.1.7.0
Windows version: 10.0.17763

I just started using this week and things have been going great.  Then I started getting `Error response from daemon: open \\.\pipe\docker_engine_linux: The system cannot find the file specified` in response to most commands.  A little searching led here.

I started Docker Desktop after this happened and (despite having a container running -- I thought) it said "No containers running... please start one from your terminal."

Now, when I try to start one from the terminal, the message has changed.

Now I'm getting `error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/create: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.`

I opened powershell in administrator mode and got the same error.

**Comment by ppatmigra** [comment]
I have the same issue. After a while most docker (cli) commands stop working and just reply:

`Error response from daemon: open \\.\pipe\docker_engine_linux: Det går inte att hitta filen.`
(sorry for swedish, same as "The system cannot find the file specified")

Docker Desktop 2.2.0.0 (42247)
Windows 10 1809 (17763.973)

A restart from the Desktop menu lets me get back to a working state for some time (10 min up to hours).
Any suggestions wellcome.

**Comment by NathanWailes** [comment]
I was just having this issue and restarting Docker Desktop fixed it (this time) without my needing to restart my computer.

**Comment by lokinmodar** [comment]
Having the same issue. I submitted the crash reports through the Docker reporting tool

**Comment by binhex** [comment]
This is STILL an issue with docker desktop 2.2.0.3 (42716) channel 'stable', PLEASE can this be looked at, i cant quite believe this issue was opened 6 months ago and there is no resolution to docker just randomly crashing!?.

**Comment by StoneyEagle** [comment]
I haven't had this issue in a while, maybe because i assigned enough memory or the bug is actually fixed.
I do have other random issues like mounted files not being synced into the container at random points in time, usually after an update of docker.
But because no one from docker cared, i can't be arsed to report issues...

**Comment by hll1682003** [comment]
I have the same issue in win10, with docker desktop v 2.2.0.4, and engine version 19.03.8, 
`docker container ls` complains about 

> Error response from daemon: open \\.\pipe\docker_engine_linux: The system cannot find the file specified.

and if I simply restart docker, it works again

**Comment by ckeeney** [comment]
I just uploaded a crash report of this issue with diagnostic id 

`F614B727-DB9B-41E1-A5E0-3BB5DBB22D59/20200323193911`

**Comment by deysn** [comment]
I also do have the same issue in windows10, with docker desktop v 2.2.0.4, and engine version 19.03.8,
when I issue the command " docker ps "  it says:
Error response from daemon: open \.\pipe\docker_engine_linux: The system cannot find the file specified.

**Comment by SLITH3RIN** [comment]
Hi, same error here.
I am adding my diagnostic id
`BB3F0D85-1F68-4066-9BB5-3ABC0EEB91F3/20200402083722`

**Comment by SLITH3RIN** [comment]
Still occurring on version 2.2.0.5

**Comment by MetaBarj0** [comment]
I can reproduce too. Version is  2.2.0.5. Running on a Windows 10 Pro 1903 build 18363.720 as a vmware VM.

**Comment by boabjohn** [comment]
Hi guys,
Just piling on here as a Win10 user:  10.0.17763 N/A Build 17763
Docker Desktop, 2.2.0.5 (43884)/Stable Engine: v19.03.8
Lando rrc3

After about an hour or so of inactivity (sorry, still figuring this out) I can return to my machine and see a happy Docker dashboard, but the local app is offline, and lando start yields the dreaded _linux pipe problem: ` \\.\pipe\docker_engine_linux: The system cannot find the file specified.`

So far I have been successful in restarting DD, then restarting Lando, and we're back.

My machine is not powering down or going onto standby, BTW...this looks like just a straight up spin-down of Docker.

**Comment by boabjohn** [comment]
Will leave this thread for now...no consistent behaviours to report I'm afraid. I have seen DDesktop stay alert and available now through full hibernation and wakeup cycles, and stay available for several hours with the computer on other tasks...no "spin-down". If I can figure out a pattern, I'll be back. Meantime I'm just happy to get on with my work!
