### ISSUE TITLE
Cannot install Docker Desktop, installer hangs on "Removing files"

### ISSUE THREAD

**Issue by AnthonyMastrean** [docker/for-win#4384]
I am unable to upgrade from 2.0 to 2.1 or install 2.1 by itself (even after using this ["official" script](https://success.docker.com/article/how-to-completely-remove-docker-in-windows-10)). The installer hangs on "Removing files...".

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Installation should succeed.

### Actual behavior

The installer is stuck on this screen.

![image](https://user-images.githubusercontent.com/217842/62324474-9ecf3b80-b477-11e9-8e57-ecf3feaf2710.png)

I can cancel the installation and no Docker application shows up in the Control Panel.

![image](https://user-images.githubusercontent.com/217842/62324802-40ef2380-b478-11e9-977c-b7e6f0f3f306.png)

But, the Docker daemon is still in startup.

![image](https://user-images.githubusercontent.com/217842/62324735-1d2bdd80-b478-11e9-9512-fcc784b95346.png)

And files are still littering my disk.

![image](https://user-images.githubusercontent.com/217842/62324782-359bf800-b478-11e9-93fc-c6cd3515219c.png)

### Information

 * Windows 10 Pro 64-bit 1903
 * Docker Desktop 2.1.0.0

**Comment by AnthonyMastrean** [comment]
I canceled the installation. I rebooted. I ran the "official" [install cleanup script](https://success.docker.com/article/how-to-completely-remove-docker-in-windows-10). I rebooted. I installed again. It worked.

🤷‍♂

**Comment by jnelson** [comment]
Just a hunch: this may be related to Windows Security's "Ransomware Protection" Controlled Folder Access setting. It's not on by default. I turned it on recently. The following Docker update failed with all of the above symptoms.
