### ISSUE TITLE
Arguments no longer encoded in ENTRYPOINT when using shell-form with an exec-form SHELL

### ISSUE THREAD

**Issue by heaths** [docker/for-win#4386]
In the latest stable version 19.03.1 a user found a problem when building a Dockerfile that uses an exec-form `SHELL` with a shell-form `ENTRYPOINT`, which was working up to an including version 18.09.3:

```dockerfile
SHELL ["cmd", "/S", "/C"]
# ...
ENTRYPOINT C:\BuildTools\Common7\Tools\VsDevCmd.bat &&
```

When inspecting the current image, seems `ArgsEscaped` is missing, which in version 18.09.3 was `"ArgsEscaped": true`. See https://github.com/MicrosoftDocs/visualstudio-docs/issues/3713 for details.

**Comment by mikeparker** [comment]
Ok i've been looking into this, i am fairly sure this is not a Desktop issue, and rather a docker engine issue, so you probably want github.com/moby/moby

Some history around this, probably related to https://github.com/moby/moby/pull/38541/files 
And there was a spec change which changes how arguments get escaped here https://github.com/opencontainers/runtime-spec/pull/998

**Comment by heaths** [comment]
Thanks for finding that. I thought it might be more of an engine issue but typically have been asked to open issues here first. That said, I know @jhowardmsft and will ask him for more context and suggested fixes/workarounds.

We need to start the vsdevcmd.bat environment initialization script (mainly updates the `PATH` environment variable with installed toolset paths) before we run anything, sot he `&&` means, "if that worked, then run the given command".
