### ISSUE TITLE
Update installer hangs - can't upgrade or uninstall Docker

### ISSUE THREAD

**Issue by bdelavega-maralytix** [docker/for-win#4387]
Whenever I get a dialog box telling me about a new docker, it hangs upgrading. This has happened a few times.  Most recently this occurred with 2.1.0.0 last night.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 7C4CB761-861B-43B9-8998-B41E0B6F9FF8/20190801192007

### Expected behavior
Upgrade succeeds or fails and terminates.

### Actual behavior
Upgrade hangs. Specifically, i get the dialog that scrolls by many libraries getting installed, then it stops moving.   I wait 20-30 minutes and force kill the install or force restart the computer.

There is nothing docker related in Add / Remove Programs.

Then I flail around trying to upgrade or uninstall.  Most recently I tried to uninstall in an admin powershell, like so:

```
PS C:\Program Files\Docker\Docker\resources> .\ForceRemoveDocker.ps1
Script started at 19:03:52.921
Modules loaded at 19:03:54.626
VM MobyLinuxVM does not exist
Destroying Switch DockerNAT...
Removing VM MobyLinuxVM...
Delete VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx


SUCCESS: The file (or folder): "C:\ProgramData\Docker" now owned by the administrators group.
processed file: C:\ProgramData\Docker\
Successfully processed 1 files; Failed processing 0 files
PS C:\Program Files\Docker\Docker\resources>
```

Rebooted and still have docker 2.0.0.3 failing at startup.

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible?
No idea.  It has happened on my laptop with every message about a new version being available.

  - Is the problem new?
With 2.1.0.0 it's new.

  - Did the problem appear with an update?
Yes. 

  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.
No idea how to reproduce this.

  - Windows Version: 10 pro - 10.0.18362

  - Docker Desktop Version: 2.0.0.3, stable, 8858db3

### Steps to reproduce the behavior
  1. At some point get a dialog announcing the availability of a new docker desktop version
  2. Accept the advice and install the update

I know this is not enough to reproduce the issue. If you want me to collect anything else or share any other details, I'd be happy to.

**Comment by Koricz** [comment]
I have same problem. When I run Docker, there is popup that new version 2.1.0.0 (36873) is available. I click to update. Package is downloaded ... and that's all. If i run Docker again, there is the same New version popup. If I skip installation, Docker starts, but there is still old version installed.

Same with running Docker and Check for Updates menu.

Version: 2.0.5.0 (35318), update channel Edge.
Windows 10 pro

**Comment by douglasharley-westat** [comment]
same problem here...docker desktop informs me that an update is available, i click update, docker alert says it will shutdown after tasks complete but nothing ever happens and update is never applied. i am on windows 10 have disabled real-time protection in windows security center, and protected folders is not enabled either. extremely annoying...

**Comment by mat007** [comment]
@bdelavega-maralytix has your diagnostics been created right after aborting the installation?
They seem to not have any installer upgrade logs.

**Comment by mat007** [comment]
Could you try and run it from the command line, for instance
```
Docker\ Desktop\ Installer.exe install --log-output-file=install-log.txt
```
and paste the content of the log file after the installation froze?

Thanks!

**Comment by bdelavega-maralytix** [comment]
> @bdelavega-maralytix has your diagnostics been created right after aborting the installation?
> They seem to not have any installer upgrade logs.

The diagnostics were created after aborting the installation a few times, but not *right* after.  If it helps, I will attach a zip file of all the files in AppData/Local/Docker (I left out the wsl folder).

**Comment by bdelavega-maralytix** [comment]
> Could you try and run it from the command line, for instance
> 
> ```
> Docker\ Desktop\ Installer.exe install --log-output-file=install-log.txt
> ```
> 
> and paste the content of the log file after the installation froze?

Well it successfully upgraded after a few reboots and an uninstall attempt, so i don't think there is anything to upgrade now.  I am willing to give it a try though - maybe it will still hang.  Where is the `Docker\Desktop` folder you mention?

I have 
C:\ProgramData\DockerDesktop
C:\ProgramData\Docker (no Desktop sub-directory)
C:\Program Files\Docker\Docker (neither has a Desktop sub-directory)
C:\Users\bill\AppData\Local\Docker (no Desktop sub-directory)

**Comment by mat007** [comment]
Oh sorry right, it’s the `Docker Desktop Installer.exe` that you can download directly from the Docker web site, but as you pointed out if you finally managed to upgrade it’s too late now, thanks anyway.

My suspicion is that for some reason the newly installed Docker service could not be started, which due to a bug hangs the installer. I’ll fix that one and try to add more feedback when something goes wrong.

Thanks for your help!

**Comment by mat007** [comment]
@Koricz and @douglasharley-westat have you eventually managed to upgrade?
If not, could you try and run the installer from the command line as described above?
The link for the Stable release is https://download.docker.com/win/stable/36874/Docker%20Desktop%20Installer.exe and for Edge https://download.docker.com/win/edge/36873/Docker%20Desktop%20Installer.exe

Thanks!

**Comment by mat007** [comment]
A screenshot of the hanged installer window would help as well.

**Comment by bdelavega-maralytix** [comment]
@mat007 - thank you for looking into it.

**Comment by Koricz** [comment]
@mat007  Hi, I just checked the file downloaded (into temp directory) with auto update and this seems to be some older version of the installer that you posted. Also the size is different.

![image](https://user-images.githubusercontent.com/11611623/62648544-50c4a700-b953-11e9-9396-af6ad0f8403f.png)

![image](https://user-images.githubusercontent.com/11611623/62648816-d21c3980-b953-11e9-9975-f0ecf3dd8d63.png)

Maybe this is the problem.

I will now run the version you posted with requested parameters and post the log and results...

**Comment by Koricz** [comment]
@mat007 So, with the installer version you posted (stable), the installation process was flawless. Thank you.

![image](https://user-images.githubusercontent.com/11611623/62649868-ea8d5380-b955-11e9-95e5-dbb9ca3cbb26.png)



Log file output

`
[out][20:48:50.029] [InstallHandler] Existing environment found: version=35318, displayVersion=2.0.5.0, basePath=C:\Program Files\Docker\Docker, channel=edge, channelUrl=https://download.docker.com/win/edge/appcast.xml
[out][20:48:50.038] [InstallHandler] Using embedded package
[out][20:48:50.139] [InstallWorkflow] Using package: res:CommunityInstaller.DockerDesktop.d4w
[out][20:48:50.140] [InstallWorkflow] Downloading
[out][20:48:59.558] [InstallWorkflow] Extracting manifest
[out][20:48:59.600] [InstallWorkflow] Checking prerequisites
[out][20:49:08.122] [InstallWorkflow] Uninstalling previous version in update mode
[out][20:49:08.138] [UninstallWorkflow] Reading installation manifest
[out][20:49:08.139] [UninstallWorkflow] Running before update actions
[out][20:49:08.139] [UninstallWorkflow] Proceeding with CommunityInstaller.ExecAction
[out][20:49:13.691] [UninstallWorkflow] Proceeding installed components
[out][20:49:13.693] [UninstallWorkflow] Proceeding with CommunityInstaller.ExecAction
[out][20:49:13.694] [UninstallWorkflow] Proceeding with CommunityInstaller.SettingsUpdateAction
[out][20:49:13.696] [UninstallWorkflow] Proceeding with CommunityInstaller.PathAction
[out][20:49:13.924] [UninstallWorkflow] Proceeding with CommunityInstaller.PathAction
[out][20:49:14.094] [UninstallWorkflow] Proceeding with CommunityInstaller.AutoStartAction
[out][20:49:14.095] [UninstallWorkflow] Proceeding with CommunityInstaller.ShortcutAction
[out][20:49:14.097] [UninstallWorkflow] Proceeding with CommunityInstaller.ShortcutAction
[out][20:49:14.098] [UninstallWorkflow] Proceeding with CommunityInstaller.ServiceAction
[out][20:49:14.101] [UninstallWorkflow] Proceeding with CommunityInstaller.AddToGroupAction
[out][20:49:14.102] [UninstallWorkflow] Proceeding with CommunityInstaller.CreateGroupAction
[out][20:49:14.103] [UninstallWorkflow] Unregistering product
[out][20:49:14.244] [InstallWorkflow] Unpacking artifacts
[out][20:49:40.449] [InstallWorkflow] Deploying component CommunityInstaller.CreateGroupAction
[out][20:49:40.535] [InstallWorkflow] Deploying component CommunityInstaller.AddToGroupAction
[out][20:49:40.616] [InstallWorkflow] Deploying component CommunityInstaller.ServiceAction
[out][20:49:41.236] [InstallWorkflow] Deploying component CommunityInstaller.ShortcutAction
[out][20:49:41.296] [InstallWorkflow] Deploying component CommunityInstaller.ShortcutAction
[out][20:49:41.299] [InstallWorkflow] Deploying component CommunityInstaller.AutoStartAction
[out][20:49:41.300] [InstallWorkflow] Deploying component CommunityInstaller.PathAction
[out][20:49:41.494] [InstallWorkflow] Deploying component CommunityInstaller.PathAction
[out][20:49:41.669] [InstallWorkflow] Deploying component CommunityInstaller.ExecAction
[out][20:49:42.191] [InstallWorkflow] Registering product
` 

It seems to me that auto update did not download the latest installer version.

**Comment by bdelavega-maralytix** [comment]
> A screenshot of the hanged installer window would help as well.

A new version came out (21.1.0.1) and the behavior reproduced. Here are screenshots.

At 12:06 local time the installer:
![image](https://user-images.githubusercontent.com/14293231/62720200-827f5180-b9d7-11e9-90dc-08363783c969.png)

I did some other work (i ignored the installer for a while).  At 12:21 it looked like so:
![image](https://user-images.githubusercontent.com/14293231/62720263-a8a4f180-b9d7-11e9-9d53-7166567f013c.png)

It still looks like that at 12:26.

If you want me to try the command line version, I'm happy to. I'll reboot and run it alone.

**Comment by bdelavega-maralytix** [comment]
I ran the installer at the command line with an admin prompt and it finished.

> C:\Users\bill\Downloads>dir doc*
>  Volume in drive C is Windows7_OS
>  Volume Serial Number is 1975-39E4
> 
>  Directory of C:\Users\bill\Downloads
> 
> 08-Aug-19  12:30       875,410,136 Docker Desktop Installer.exe
> 31-Jul-19  21:11       567,050,280 Docker for Windows Installer (1).exe
> 25-Apr-19  07:37       567,050,280 Docker for Windows Installer.exe
> 09-May-19  22:53            64,181 document.pdf
>                4 File(s)  2,009,574,877 bytes
>                0 Dir(s)  47,183,319,040 bytes free
> 
> C:\Users\bill\Downloads>"Docker Desktop Installer.exe" install --log-output-file=install-log.4387.txt
> 
> C:\Users\bill\Downloads>
> 

Not that it matters now, but here's the log:
[install-log.4387.txt](https://github.com/docker/for-win/files/3484169/install-log.4387.txt)

**Comment by Koricz** [comment]
Hi, today auto update to 2.1.0.1 (37199) was finished without any issue.

**Comment by mat007** [comment]
@bdelavega-maralytix that’s odd that it worked with the command line (but good for you 😁 ).
Can you check in the Windows event viewer around the time when it stayed stuck on the service not starting to see if you have any error message?

**Comment by yoDon** [comment]
I finally gave up on trying to upgrade and tried to uninstall. At the end of uninstalling 2.1.0.0 presents a an empty dialog box with no contents or buttons except for the system close window "X" button in the upper right. Clicking the close window button pops up a dialog asking if I want to cancel the uninstall. No, I don't want to cancel the uninstall. The uninstall has finished and docker no longer shows in my list of installed programs. The only option is to click "yes" I want to cancel the uninstall, which appears to not cancel the uninstall but simply end the uninstall. As other commenters have said in this thread Docker needs to get it's installer act together. Building good installers AND uninstallers for windows is hard work and docker is failing at it. I do think I've finally got docker uninstalled but my confidence is low and my desire to re-install it to get the newest version is even lower after this experience.

**Comment by vsavkov** [comment]
Docker Desktop Installer hangs forever on "Deploying component CommunityInstaller.ServiceAction" step.

Docker Desktop 2.1.0.4
Installer: CommunityInstaller 2.1.0.39773
OS: Windows 10 Enterprise, Version: 10.0.17763 Build 17763

The installer was started from Command Prompt (that was started as Administrator):
C:\dir>"Docker Desktop Installer.exe" install --log-output-file=<output-file>
Log attached.
[docker-install.2019-10-25.txt](https://github.com/docker/for-win/files/3772033/docker-install.2019-10-25.txt)

**Comment by mikeparker** [comment]
@vsavkov Can you upload this log file please? (or a full diagnostic)
`C:\Users\<username>\AppData\Local\Docker\install-log.txt`

**Comment by vsavkov** [comment]
@mikeparker Will do, tomorrow is the earliest.

**Comment by SpoonOfDoom** [comment]
Is this the same as  #1172?

**Comment by vsavkov** [comment]
@SpoonOfDoom looks the same.
