### ISSUE TITLE
Docker Install hangs, abort manually and Error Popup comes again and again

### ISSUE THREAD

**Issue by ThorstenSeddig** [docker/for-win#4388]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mikeparker** [comment]
Which version? which windows version? are you installing or upgrading? Whats the error popup?

**Comment by ThorstenSeddig** [comment]
Hello Mr. Parker,

My Windows Version is: 
Microsoft Windows 10 Enterprise
Version 10.0.17763 Build 17763

I have installed Docker new - wo times. 
After the first time, windows autostart didn't work and i have tried to 
remove it from Windows, by special script:

kill -force -processname 'Docker for Windows', com.docker.db, 
com.docker.slirp, com.docker.proxy, com.docker.9pdb, moby-diag-dl, dockerd
kill -force -processname com.docker.service

try {
        pushd "C:\Program Files\Docker\Docker\Resources"
    ./MobyLinux.ps1 -Destroy
        popd
} Catch {}

popd

$service = Get-WmiObject -Class Win32_Service -Filter 
"Name='com.docker.service'"
if ($service) { $service.StopService() }
if ($service) { $service.Delete() }
Start-Sleep -s 5
Remove-Item -Recurse -Force "~/AppData/Local/Docker"
Remove-Item -Recurse -Force "~/AppData/Roaming/Docker"
if (Test-Path "C:\ProgramData\Docker") { takeown.exe /F 
"C:\ProgramData\Docker" /R /A /D Y }
if (Test-Path "C:\ProgramData\Docker") { icacls "C:\ProgramData\Docker\" 
/T /C /grant Administrators:F }
Remove-Item -Recurse -Force "C:\ProgramData\Docker"
Remove-Item -Recurse -Force "C:\Program Files\Docker"
Remove-Item -Recurse -Force "C:\ProgramData\Microsoft\Windows\Start 
Menu\Programs\Docker"
Remove-Item -Force "C:\Users\Public\Desktop\Docker for Windows.lnk"
Remove-Item -Recurse -Force "~\.docker"
Remove-Item -Recurse -Force "~\DockerSwarm"
Get-ChildItem HKLM:\software\microsoft\windows\currentversion\uninstall | 
ForEach-Object {Get-ItemProperty $_.pspath} | Where-Object { 
$_.DisplayName -eq "Docker" } | Remove-Item -Recurse -Force
Get-ChildItem HKLM:\software\classes\installer\products | ForEach-Object 
{Get-ItemProperty $_.pspath} | Where-Object { $_.ProductName -eq "Docker" 
} | Remove-Item -Recurse -Force
Get-Item 'HKLM:\software\Docker Inc.' | Remove-Item -Recurse -Force
# TODO Figure out how to do these properly!
# Get-ItemProperty HKCU:\software\microsoft\windows\currentversion\Run 
-name "Docker for Windows" | Remove-Item -Recurse -Force
# Get-ItemProperty HKCU:\software\microsoft\windows\currentversion\UFH\SHC 
| ForEach-Object {Get-ItemProperty $_.PSPath} | Where-Object { 
$_.ToString().Contains("Docker for Windows.exe") } | Remove-Item -Recurse 
-Force

# Remove env variables used by docker-machine
Get-Item Env:\COMPOSE_CONVERT_WINDOWS_PATHS | Remove-Item
Get-Item Env:\DOCKER_* | Remove-Item # DOCKER_CERT_PATH, DOCKER_HOST, 
DOCKER_MACHINE_NAME, DOCKER_TLS_VERIFY


The second time after installation autostart worked and I got the 
following error messages:

Backend service is not installed
   bei Docker.WPF.BackendClient.CheckService(String action) in 
C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:Zeile 
291.
   bei Docker.WPF.BackendClient.SendMessage(String action, Object[] 
parameters) in 
C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:Zeile 
167.
   bei Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in 
C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:Zeile 
59.

Backend service is not installed
   bei Docker.WPF.BackendClient.CheckService(String action) in 
C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:Zeile 
291.
   bei Docker.WPF.BackendClient.SendMessage(String action, Object[] 
parameters) in 
C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:Zeile 
167.
   bei Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean 
showWelcomeWindow, Boolean executeAfterStartCleanup) in 
C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:Zeile 
90.
   bei Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in 
C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:Zeile 
74.
   bei Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in 
C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:Zeile 
59.


Mit freundlichen Grüßen / Best regards

Thorsten Seddig
Software Engineer
____________________________________________________________

SICK AG  |  Erwin-Sick-Str. 1  |  79183 Waldkirch  |  Germany
Phone  +49 7681 202-3964  |  thorsten.seddig@sick.de  |  
http://www.sick.de





Von:    "Mike Parker" <notifications@github.com>
An:     "docker/for-win" <for-win@noreply.github.com>
Kopie:  "ThorstenSeddig" <thorsten.seddig@sick.de>, "Author" 
<author@noreply.github.com>
Datum:  02.08.2019 14:01
Betreff:        Re: [docker/for-win] Docker Install hangs, abort manually 
and Error Popup comes again and again (#4388)



Which version? which windows version? are you installing or upgrading? 
Whats the error popup?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


 ____________________________________________________________

SICK AG  |  Sitz: Waldkirch i. Br.  |  Handelsregister: Freiburg i. Br. HRB 
280355 
Vorstand: Dr. Robert Bauer (Vorsitzender)  |  Reinhard Bösl  |  Dr. Mats 
Gökstorp  |  Dr. Martin Krämer  |  Markus Vatter
Aufsichtsrat: Gisela Sick (Ehrenvorsitzende)  |  Klaus M. Bukenberger 
(Vorsitzender)
