### ISSUE TITLE
Trying to connect to http, ip, and tcp using docker but failing 

### ISSUE THREAD

**Issue by mahaalkhairy** [docker/for-win#439]
### Expected behavior

get a http:// connection for the running result 

### Actual behavior
Error: 
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: error during connect: Post http://MY_SERVER_IP:2375/v1.25/containers/create: dial tcp: lookup MY_SERVER_IP: getaddrinfow: No such host

### Information

  - Diagnostic ID: E795E212-E8D6-420A-ABE3-D5CE015926A5/2017-01-28_12-42-13
  - host distribution and version: Windows 10 - professional 

### Steps to reproduce the behavior
 
  1.  in power shell type: docker -H MY_SERVER_IP:2375 run -l proxied=true -d -p 139:80 -p 445:443 helloworld

**Comment by rneugeba** [comment]
@mahaalkhairy I'm not sure I understand your scenario. If you have Docker for Windows installed and running on you local machine you don't need to specify the `-H` option.

If you try to use the docker CLI to interact with a docker daemon running on a another machine you need to make sure that the firewall allows connection to port 2375 and that the daemon is listening on the main interface.

**Comment by mahaalkhairy** [comment]
Thanks, my problem is fixed now

**Comment by rneugeba** [comment]
great, thanks for getting back and good to hear it's working for you. Closing the issue
