### ISSUE TITLE
Docker Containers show Healthy but doesn't respond on browser After Restart

### ISSUE THREAD

**Issue by BSSIRajbir** [docker/for-win#4399]
Docker Containers show Healthy but doesn't respond on browser
Diagnostics ID : ECA95947-FEC2-4F89-9105-FFDB25C8CFEB/20190802201808

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ggirard07** [comment]
Are you running in Linux containers mode or in Windows containers mode?
Are you using `docker-compose`?

**Comment by ktmitton** [comment]
@BSSIRajbir sounds like you may have the same issue I have, and was reported in #4056, do the steps outlined in my [comment](https://github.com/docker/for-win/issues/4056#issuecomment-517772866) match what you see?
