### ISSUE TITLE
Docker WSL context does not start when docker start (At logon at least, probably always)

### ISSUE THREAD

**Issue by tebeco** [docker/for-win#4404]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3E162870-D128-4BE3-B2E0-051948CE01E8/20190803102645

### Expected behavior
When i startup windows, Docker is set to also run at startup time.
Once docker is "running" i expect to interact with is like `docker images ls`

### Actual behavior
The WSL2 context is not started :
![image](https://user-images.githubusercontent.com/2266487/62411007-17f09f00-b5ee-11e9-9a01-7c5585e7b8a7.png)

### Information
  - Is it reproducible?  Yes
  - Is the problem new?  Yes (from Wsl2)
  - Did the problem appear with an update? Yes and No, i think it's just wsl context not starting
  - A reproducible case if this is a bug => just reboot ;)
  - Windows Version: 10 insider fast / Build 18950
  - Docker Desktop Version: `2.1.0.0 (36883)`

### Steps to reproduce the behavior
1. Install ubuntu
2. set it version to `wsl2`
3. Install `Docker for Windows Technical preview for `Wsl2`
4. Set `wsl` as default context (i guess `docker context use wsl`)
5. make sure it works by running `docker context ls`
```
docker context ls
NAME                DESCRIPTION                               DOCKER ENDPOINT                  KUBERNETES ENDPOINT   ORCHESTRATOR
default             Current DOCKER_HOST based configuration   npipe:////./pipe/docker_engine                         swarm
wsl *               Docker daemon hosted in WSL 2             npipe:////./pipe/docker_wsl          
```

6. run `docker run --rm -it alpine sh` to be sure it works
7. Set `Docker` start at windows logon
8. reboot
9. Wait for `Docker` to be started
10. run `docker images ls` **It will fail**

![image](https://user-images.githubusercontent.com/2266487/62411616-e085f080-b5f5-11e9-857f-e54146b23849.png)

**Comment by simonferquel** [comment]
The tech preview does never automatically start. You need to go the the WSL 2 tech preview to start it manually.

It will be solved in a future release.

**Comment by tebeco** [comment]
fair enough (closing i guess ?)

**Comment by ksawerykarwacki** [comment]
is there any way to add this to autostart? like some bash script to run it on startup? I belive it changes context on windows side and runs three things on wsl side

`/usr/share/docker-desktop/default/lifecycle-server

dockerd -D --bip 10.255.0.1/16 --data-root /var/data/docker-desktop/default/daemon-data --config-file /mnt/c/Users/ksawe/AppData/Local/Docker/wsl/default/daemon.json

containerd --config /var/run/docker/containerd/containerd.toml --log-level debug`
