### ISSUE TITLE
External Ports cannot be Accessed after Updating

### ISSUE THREAD

**Issue by MrTyton** [docker/for-win#4409]
- Diagnostics ID: 43994544-177A-4562-B49D-6C0A7292A150/20190803184417

### Expected behavior

Can access docker containers through ports from outside the machine.

### Actual behavior

I have a bunch of containers that have ports forwarded on them for external access. Everything was working fine, then I followed the prompt to update to the latest version of docker.

Once that finished, the containers became inaccessible outside of localhost.

If I do localhost:number then I get the expected web page from the docker container. However, if I, from a different computer on the network, do ip.address:number, then it times out, and same if I try to access it from outside the network with port forwarding.

All of the other port forwards for different services on the machine still work, it's just the docker containers that are affected.

I've tried restarting the docker service, the computer, and the router. None of them fixed it. The failure point for it was exactly me updating docker after the prompt.

**Comment by kjlhgfds** [comment]
I had the same issue with the 2.1.0.0 version of windows docker.
I downgraded to version 2.0.0.3 and everything worked again, os it's definitly an update related issue.

**Comment by colcek** [comment]
I have something different but similar issue and to solve that I also downgraded.
Please see my issue #4424

**Comment by jhovanylinkin** [comment]
> * Diagnostics ID: 43994544-177A-4562-B49D-6C0A7292A150/20190803184417
> 
> ### Expected behavior
> Can access docker containers through ports from outside the machine.
> 
> ### Actual behavior
> I have a bunch of containers that have ports forwarded on them for external access. Everything was working fine, then I followed the prompt to update to the latest version of docker.
> 
> Once that finished, the containers became inaccessible outside of localhost.
> 
> If I do localhost:number then I get the expected web page from the docker container. However, if I, from a different computer on the network, do ip.address:number, then it times out, and same if I try to access it from outside the network with port forwarding.
> 
> All of the other port forwards for different services on the machine still work, it's just the docker containers that are affected.
> 
> I've tried restarting the docker service, the computer, and the router. None of them fixed it. The failure point for it was exactly me updating docker after the prompt.


I have the same error 😕
the only solution i found
was reinstall version 2.0.0.3

**Comment by frankyifei** [comment]
Happens to me as well

**Comment by sjdvda** [comment]
I believe this is the same issue: https://github.com/docker/for-win/issues/4391
