### ISSUE TITLE
Error at starting Docker

### ISSUE THREAD

**Issue by Kadantte** [docker/for-win#4414]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 0181BB61-86B7-410A-9C28-AA2CA43C73C6/20190804151714

### Expected behavior
Start Docker
### Actual behavior
Hardware assisted virtualization and data execution protection must be enabled in the BIOS. See https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization-must-be-enabled
### Information

  - Windows Version: Windows 10 Pro 1809 / OS Build: 17763.615
  - Docker Desktop Version:  18.06.1-ce-win73 (19507)
Channel: stable

![Capture](https://user-images.githubusercontent.com/11579313/62424932-44c7b380-b6cd-11e9-89a9-ec11a208f12a.PNG)

![Capture ](https://user-images.githubusercontent.com/11579313/62424933-4abd9480-b6cd-11e9-86a1-24a05824e567.PNG)

### Steps to reproduce the behavior

1. Enable Hyper-V feature.
2. Install Docker with default options.

**Comment by telalwar** [comment]
@Kadantte See if this helps you https://github.com/docker/for-win/issues/4452#issuecomment-518815167

**Comment by Kadantte** [comment]
I tried with the New Version of Docker Windows Containers works but when I try to switch to Linux it gives me this Error:
`
Failed to switch because your Windows version is not compatible.

Hardware assisted virtualization and data execution protection must be enabled in the BIOS. See https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization-must-be-enabled

Keeping previous configuration.
`
