### ISSUE TITLE
Docker failed to start

### ISSUE THREAD

**Issue by atiwari1989** [docker/for-win#443]
### Expected behavior
Docker should start

### Actual behavior
Docker not starting.

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
75C78334-B964-4DA5-9A86-31B48143BA98/2017-01-30_10-38-03
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)
Version: 1.12.3 (8488)
Channel: Stable
Sha1: d63ec34a49019d2e0b29d7706e57ccfc721ddb8f
Started on: 2017/01/30 10:28:41.001
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1607
Build: 14393
BuildLabName: 14393.447.amd64fre.rs1_release_inmarket.161102-0100

### Steps to reproduce the behavior

  1. Start Docker

**Comment by dgageot** [comment]
Hi @atiwari1989 could you please try a more recent version of Docker for Windows? This should give us more information to debug your issue.

**Comment by atiwari1989** [comment]
Hi David,
It is giving error when I am trying to install updates as well.

Crash report uploaded with id
D15C29DC-93D4-42D3-B15E-9A2EA4AA69DC/2017-01-30_11-47-18


<http://www.openbet.com/> Abhijit Tiwari
Software Analyst
T: +44 208 742 1600

E: abhijit.tiwari@openbet.com
W: www.openbet.com
OpenBet Ltd
Chiswick Park Building 9
566 Chiswick High Rd
London
W4 5XT
UK
<https://www.openbet.com/email_promo>
This message is confidential and intended only for the addressee. If you
have received this message in error, please immediately notify the
postmaster@openbet.com and delete it from your system as well as any
copies. The content of e-mails as well as traffic data may be monitored by
OpenBet for employment and security purposes. To protect the environment
please do not print this e-mail unless necessary. OpenBet Ltd. Registered
Office: Chiswick Park Building 9, 566 Chiswick High Road, London, W4 5XT,
United Kingdom. A company registered in England and Wales. Registered no.
3134634. VAT no. GB927523612

**Comment by simonferquel** [comment]
Could you uninstall first and then install the latest msi ?

**Comment by friism** [comment]
Closing this since @atiwari1989 didn't follow up - please re-open if you have more details.
