### ISSUE TITLE
Unable to Login and Pull Images

### ISSUE THREAD

**Issue by arie-sh** [docker/for-win#4433]
- [ x ] I have tried with the latest version of my channel Stable
  - [ x ] I have uploaded Diagnostics
  - Diagnostics ID: E06A4FB8-2F67-43CB-9D22-56B02C6C9A4A/20190806040907

### Expected behavior
Logged in after I have submitted my DockerID and Password

### Actual behavior
Failed to Login with the DockerID and Password Textboxt became RED

### Information
  - Is it reproducible? YES
  - Is the problem new? Newly installed docker desktop for windows
  - Did the problem appear with an update? Newly installed docker desktop for windows
  - Windows Version: Windows 10 Enterprise
  - Docker Desktop Version: 2.1.0.0 (36874) - Docker version 19.03.1, build 74b1e89
  - I've successfully logged in  on https://cloud.docker.com/ and https://hub.docker.com/

### Steps to reproduce the behavior

![image](https://user-images.githubusercontent.com/53806944/62511414-be7eaf00-b83d-11e9-9e09-3069a2d47522.png)

  1. Start Docker Desktop
  2. Click Sign-In / Create Docker ID
  3. Input Docker ID and Password
  4. Click Sign-In

**Comment by lukasz-wolski** [comment]
same behaviour observed.

Diagnostics ID: 75D274DE-EAA5-405E-B547-470A7B406749/20190830163754
