### ISSUE TITLE
No such host when pulling images from registry

### ISSUE THREAD

**Issue by maicol07** [docker/for-win#4437]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E209C6A4-9449-4323-AB40-EFAAB00AE4C2/20190806072257

### Expected behavior
Pull images correctly without any error
### Actual behavior
I get an error trying to pull images from registry. For example running `docker run hello-world` like Getting Started docs say returns the following:
```
PS C:\Users\Maicol> docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
1b930d010525: Pulling fs layer                                                                                          D:\Program Files\Docker\Docker\Resources\bin\docker.exe: error pulling image configuration: Get https://registry-1.docker.io/v2/library/hello-world/blobs/sha256:fce289e99eb9bca977dae136fbe2a82b6b7d4c372474c9235adc1741675f587e: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: no such host.
See 'D:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
```

### Information

  - Windows Version: 10
  - Docker Desktop Version: 2.1

### Steps to reproduce the behavior

  1. Follow docs steps (https://docs.docker.com/docker-for-windows/)

**Comment by mikeparker** [comment]
`Get https://registry-1.docker.io/v2/library/hello-world/blobs/sha256:fce289e99eb9bca977dae136fbe2a82b6b7d4c372474c9235adc1741675f587e: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: no such host.`

Likely a DNS issue

**Comment by maicol07** [comment]
@mikeparker I've tried also with Google ones but it didn't work...

**Comment by mikeparker** [comment]
Manual / Automatic DNS?

**Comment by maicol07** [comment]
@mikeparker I've used [DNS Jumper](https://www.sordum.org/7952/dns-jumper-v2-1/)

**Comment by mikeparker** [comment]
Have you tried without DNS jumper and using automatic dns?

**Comment by maicol07** [comment]
@mikeparker how can I do this? I'm new to Docker

**Comment by maicol07** [comment]
@mikeparker I've tried setting Automatic DNS both in Docker Desktop settings and in Wireless card settings but none of these worked

**Comment by mikeparker** [comment]
hi @maicol07 this is probably a question for the community forums -> https://forums.docker.com/

**Comment by kwanele** [comment]
> `Get https://registry-1.docker.io/v2/library/hello-world/blobs/sha256:fce289e99eb9bca977dae136fbe2a82b6b7d4c372474c9235adc1741675f587e: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: no such host.`
> 
> Likely a DNS issue

How do i resolve this

**Comment by kalb1** [comment]
Logout from Docker Desktop was worked for me.
