### ISSUE TITLE
freshly installed Docker Desktop does not start a new container. 

### ISSUE THREAD

**Issue by skystar1991** [docker/for-win#4454]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 2B1A8B2D-8FC8-4F4D-BA60-26EBB8A91F9E/20190806115349

### Expected behavior
running a docker command 'docker run mcr.microsoft.com/windows/nanoserver:1809-amd64' will start a container and run. 

### Actual behavior
hangs after hitting the enter key.

### Information

I updated 2.1.0.0 and it did not start a container. I removed Docker Desktop and installed 2.0.0.3 it has the same behavior.

  - Windows Version:
```
Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
Operating System: Windows Server 2019 Datacenter Evaluation Version 1809 (OS Build 17763.652)
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 16GiB
```
  - Docker Desktop Version:
```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:28:48 2019
  OS/Arch:          windows/amd64
  Experimental:     false
```

### Steps to reproduce the behavior
This is Guest OS and nothing is installed but Docker Desktop and Firefox. The OS has the latest Windows Update.
running 'docker run ...' does not start a container. the container is actually in 'created' status.

**Comment by mikeparker** [comment]
I can't see any errors in your log file. I know this doesn't help but the command works fine for me.

Have you tried any other containers? have you tried linux container mode?

Are you running on a virtualized server?

**Comment by skystar1991** [comment]
@mikeparker Hello Mike, I forgot to mention. yes, this is virtualized server running on Windows Server 2016. would it be a problem?
