### ISSUE TITLE
Installation appears to be successful but the whale never turns blue

### ISSUE THREAD

**Issue by NatureMike** [docker/for-win#4457]
Error message states:
C:\Users\a-jenkinsm>docker image ls --all
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/images/json?all=1: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

Docker Desktop Service is running.

  - [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 885835C7-D9D2-40DE-B77C-9E79BE9BB50E/20190806155356

### Expected behavior
Trying to just get a positive response from docker run hello-world or docker image ls --all
### Actual behavior
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/images/json?all=1: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
### Information

  - Windows Version: Windows Server 2019
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mikeparker** [comment]
Looks like your machine is running too slowly for Docker Desktop to work. Are you running in a virtualized environment?

**Comment by NatureMike** [comment]
Yes, it is a virtual server running in our data center.  Is there a way to get it to work?  It is a pretty beefy server, so I'm not sure how we would speed it up.

**Comment by mikeparker** [comment]
Unfortunately this is likely a problem because of nested virtualization, which we don't officially support. Please see https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-desktop-for-windows-in-nested-virtualization-scenarios for details.

Whilst we would love to guarantee running nested virt will always work, the reality is keeping it stable across all VM providers and all OS patches would be a very large amount of work.

Really, Docker Desktop is not designed for server hosts, its designed as a developer desktop tool. If you want to run docker on Windows Server then Docker EE (which comes with Windows Server licenses) is the official method.

**Comment by NatureMike** [comment]
Thank you very much for the response and the information.    This isn't your issue, but for context I was trying to install and configure an Esri GIS product called Notebook Server (for hosted Jupyter Notebooks) which uses Docker Engine.   Unfortunately that can't run with Docker EE, only Docker CE.  
https://enterprise.arcgis.com/en/notebook/latest/install/windows/install-docker-for-arcgis-notebook-server.htm

**Comment by mikeparker** [comment]
Whilst I can't comment in any official way, purely as an informed observer that would seem a little odd and it doesn't seem hugely surprising that it doesn't work properly. It goes without saying that using an official docker server product is going to be more reliable as it'll be designed for server workloads.

That said, there are plenty of people who are trying to get docker desktop working in various virtualized environments and so you may get some unofficial help from the community forum (https://forums.docker.com/), also contacting your hosting company directly they may have some workarounds.
