### ISSUE TITLE
 Error report after update - Out of memory

### ISSUE THREAD

**Issue by mmdsyl** [docker/for-win#4459]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:2AEC4ACF-1D28-4775-A1FF-E7C7DD61917A/20190807060007

### Expected behavior
after update ,open docker
Unable to start
   在 Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   在 Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   在 Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   在 Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

### Actual behavior
open docker
### Information

  - Windows Version: Win 10 1903(OS 18362.239)
  - Docker Desktop Version:2.0.0.31259  update --> 2.1.0.0

### Steps to reproduce the behavior
I use docker 2.0.0.31259
It says update, and I click update button.
After the update, it was found that it could not be used

**Comment by zappy-shu** [comment]
@mmdsyl looking at you logs I see:
```
已停止该运行的命令，因为首选项变量“ErrorActionPreference”或通用参数设置为 Stop: “DockerDesktopVM”无法启动。

系统内存不足，无法启动虚拟机 DockerDesktopVM。

无法初始化内存: 内存已用完 (0x8007000E)。

“DockerDesktopVM”无法启动。(虚拟机 ID AA49F699-108F-4D98-B514-3EA24E69D1CF)

系统内存不足，无法启动虚拟机 DockerDesktopVM，需要内存大小 2048 MB。(虚拟机
```

The DockerDesktopVM requires 2048MB of RAM to start. Please can you check how much you have spare and try closing some other applications if you are running low
