### ISSUE TITLE
Docker 2.1 k8s pv manager creates pvs even if shared folders are not enabled which end up using tmpfs

### ISSUE THREAD

**Issue by marwatk** [docker/for-win#4466]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3DEDD9D6-5E87-4BE9-A05C-89744FFEF0E1/20190807182731

### Expected behavior

No physical volumes are created for unbound physical volume claims when shared folders are not enabled.

### Actual behavior

Physical volumes are created pointing to a non-existant path in the VM, which instead uses `tmpfs` consuming RAM when writing files.

### Information

  - Windows Version: Win10 1709
  - Docker Desktop Version: 2.1.0.0

### Steps to reproduce the behavior

1. Disable folder sharing (our VPN precludes it)
2. Create a pvc like this:
```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvbug1-pvc
  labels:
    delkey: pvbug
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: pvbug1-pv
  storageClassName: hostpath
```
3. Wait a few seconds and a physical volume will appear like this:
```
$ kubectl get pv/<pv name> -o yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    docker.io/hostpath: C:\Users\MWatkins\.docker\Volumes\webrestore-pvc\pvc-bc0a2d4a-b7ca-11e9-b9a0-00155d01723a
    pv.kubernetes.io/provisioned-by: docker.io/hostpath
  creationTimestamp: 2019-08-05T21:48:17Z
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-bc0a2d4a-b7ca-11e9-b9a0-00155d01723a
  resourceVersion: "14435"
  selfLink: /api/v1/persistentvolumes/pvc-bc0a2d4a-b7ca-11e9-b9a0-00155d01723a
  uid: bc163917-b7ca-11e9-b9a0-00155d01723a
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 40Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: webrestore-pvc
    namespace: asias-localcluster
    resourceVersion: "14424"
    uid: bc0a2d4a-b7ca-11e9-b9a0-00155d01723a
  hostPath:
    path: /host_mnt/c/Users/MWatkins/.docker/Volumes/webrestore-pvc/pvc-bc0a2d4a-b7ca-11e9-b9a0-00155d01723a
    type: ""
  persistentVolumeReclaimPolicy: Delete
  storageClassName: hostpath
  volumeMode: Filesystem
status:
  phase: Bound
```

Note the `path` under `hostPath`. If we create a pod to consume it and examine the mount it looks like this:
```
overlay on /test_mount type overlay (rw,relatime,lowerdir=/containers/services/docker/lower,upperdir=/containers/services/docker/tmp/upper,workdir=/containers/services/docker/tmp/work)
```

The `workdir` ends up as `/containers/services/docker/tmp/work`, which in the moby vm looks like:
```$ docker run -it --rm --privileged --pid=host justincormack/nsenter1
/ # df /containers/services/docker/tmp/work
Filesystem           1K-blocks      Used Available Use% Mounted on
tmpfs                  9473544   6612072   2861472  70% /containers/services/docker/tmp
```

We see that it ends up with a `tmpfs` limiting your write ability to the memory limit on the pod. But, more importantly, it prevents binding a proper `pv` to the `pvc` at a later time.

We only encountered this because we have automation that comes in and creates `pv`s for any unbound `pvc`s using paths under `/var/lib/docker` (because we can't use shared folders). If we create requisite `pv`s before our `pvc`s no broken `pv`s are created.

**Comment by guillaumerose** [comment]
You're totally right! Thanks for reporting it. This bug is here for more than year so. I will take a look.
