### ISSUE TITLE
unable to share drive

### ISSUE THREAD

**Issue by jasminewu229** [docker/for-win#4467]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 7277C7F6-CB6D-4A51-ABB6-AC9BE83A5448/20190808021512

### Expected behavior
share C drive

### Actual behavior
Error: A firewall is blocking file sharing between Windows and the containers. See documentation for more info.

### Information
  - Is it reproducible? yes, always
  - Is the problem new? no
  - Did the problem appear with an update? I have just downloaded the latest version,
  - Windows Version: WIN 10 Enterprise
  - Docker Desktop Version: 
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:17:08 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:17:52 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

### Steps to reproduce the behavior
1. Download docker for windows and install it
2. in 'Settings' -> shared drives, select C drive and apply
3. error pops up: A firewall is blocking file sharing between Windows and the containers. See documentation for more info.

## I have tried:
1. add another local user with admin privilege as suggested in some other issues, no luck
2. restart docker app, no luck
3. checked my smb registry value, no luck
4. checked my firewall rules on port 445, it's already allowed no luck
5. disabled file and printer sharing for msft networks and re-enable it again on DockerNAT adapter, no luck
6. reset docker app to factory defaults, no luck
7. restarted my laptop, no luck

**Comment by mat007** [comment]
Can you try if it works when you disable your firewall?

**Comment by jasminewu229** [comment]
> 
> 
> Can you try if it works when you disable your firewall?

Unfortunately I don't have the luxury to disable my firewall as it's controlled by our company's group policy. I have checked the firewall rules - isn't this sufficient?
![image](https://user-images.githubusercontent.com/20765228/62771199-416a6880-bacf-11e9-9f0b-c5d6cfd1c033.png)

**Comment by kll** [comment]
Same exact issue here, even with the firewall disabled.
docker desktop community: 2.1.0.3
windows 10 pro 1903
Diagnostics ID: 116825F6-F7FC-4F1A-BD0B-07CDA11EED29/20191021150002

**Comment by kll** [comment]
I updated to 2.1.0.4 and same result.
Diagnostics ID: 116825F6-F7FC-4F1A-BD0B-07CDA11EED29/20191022140219
![docker-share-firewall](https://user-images.githubusercontent.com/16741/67293802-ee3f6980-f4b2-11e9-8143-0472955a4432.png)

**Comment by djs55** [comment]
@jasminewu229 thanks for your report. There's a completely new drive sharing implementation in the latest edge release which should be immune to firewall issues.

In case it's useful I've written instructions for setting up and testing the new file sharing implementation available in the edge channel here: https://github.com/docker/for-win/issues/5139#issuecomment-559700215

**Comment by stephen-turner** [comment]
This is fixed with the new filesharing implementation in 2.2.0.3, so closing this ticket.
