### ISSUE TITLE
Issue when updating the Docker desktop Windows

### ISSUE THREAD

**Issue by Madhufuture** [docker/for-win#4473]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mikeparker** [comment]
Can you upload a diagnostic / log file please? Or fill in the template.

**Comment by Madhufuture** [comment]
I'm not able to reproduce the issue. Tried force updates to the docker desktop, but no luck. Closing the issue.

**Comment by Madhufuture** [comment]
I'm not able to reproduce the issue. Tried force updates to the docker desktop, but no luck. Closing the issue.
