### ISSUE TITLE
unable to run linux containers

### ISSUE THREAD

**Issue by chazt3n** [docker/for-win#4474]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 9B59023C-A2EB-400C-A306-CA7E1DD301F5/20190808150019

Note: docker.exe is set to run as admin, docker desktop is set to run as admin.

### Expected behavior
run linux containers
### Actual behavior

```$ docker ps
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```
>Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Creating the virtual machine failed.

> at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.<>c__DisplayClass36_0.<SwitchDaemon>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

### Information

  - Windows Version: 10.0.17134 Build 17134
  - Docker Desktop Version: 2.1.0.1 (37199)

### Steps to reproduce the behavior
start docker desktop

**Comment by ChuangTzuping** [comment]
same problem.  
windows version : win10 1903 (18362.267)

**Comment by mat007** [comment]
Sorry, for an unknown reason your diagnostics file never reached us.
Do you think you could try and send a fresh one?

**Comment by chazt3n** [comment]
I've uploaded a new report with this id: 9B59023C-A2EB-400C-A306-CA7E1DD301F5/20190815171719

**Comment by mat007** [comment]
Here is the root error in the log
```
Cannot open vmms service on computer '.'
```
There is something wrong with Hyper-V, maybe look at e.g. https://superuser.com/questions/1329033/virtualization-enabled-but-not-being-displayed-windows-10 ?

**Comment by chazt3n** [comment]
Ok thank you sir

**Comment by chazt3n** [comment]
![image](https://user-images.githubusercontent.com/3843179/63522851-b457e400-c4be-11e9-808d-7ddde5b9a965.png)
I've got it enabled, and windows containers seem to work (if that matters?)

**Comment by chazt3n** [comment]
trying to start MobyLinuxVM from hyper-v does this:
![image](https://user-images.githubusercontent.com/3843179/63522974-ea956380-c4be-11e9-9ae0-d83214993fb6.png)

(which the underlying error is likely what you're seeing - I will try to completely uninstall and reinstall - it worked the day before I made this ticket so possibly some company policy mishap (other members of team are working fine)

**Comment by mikeparker** [comment]
Can you try restarting the Hyper-V Virtual Machine Management service? This worked here https://github.com/docker/for-win/issues/4668#issuecomment-533173071

**Comment by mikeparker** [comment]
Also try this https://github.com/docker/for-win/issues/3597#issuecomment-474949164

**Comment by chazt3n** [comment]
I got this to work - it was my company blocking it..

**Comment by mikeparker** [comment]
@chazt3n for reference, which program / policy was making it fail? (I ask because we have lots of users getting the same thing!)

**Comment by chazt3n** [comment]
I've reached out to my ops team - I know we had a policy that blocked hyper-v from creating/starting VMs

asking for more detail
