### ISSUE TITLE
Docker desktop not starting up.

### ISSUE THREAD

**Issue by 001aniket** [docker/for-win#4477]
Hi All,

Attached is the Docker desktop log file while has error details of my problem statement.

Please look and suggest.

Regards,
Aniket
[Docker log.txt](https://github.com/docker/for-win/files/3484451/Docker.log.txt)

**Comment by 001aniket** [comment]
Also attaching the Docker diagnostic logs.
[diagnostics.log](https://github.com/docker/for-win/files/3484456/diagnostics.log)

**Comment by mat007** [comment]
Can you update to Stable 2.1.0.1 and see if that helps?

![image](https://user-images.githubusercontent.com/2386884/62758879-f37a4400-ba7f-11e9-9e58-52836b7705c4.png)

**Comment by whereisaaron** [comment]
I installed this update and poof, error display and docker no long working or installed. Tried installing fresh, might be working, but system tray menu won't appear anymore 😢

**Comment by mat007** [comment]
@whereisaaron can you open a fresh issue with more details please, as it does not seem to be related to the issue here, is it?
