### ISSUE TITLE
Windows Server 2016 compatibility

### ISSUE THREAD

**Issue by Elufimov** [docker/for-win#448]
### Expected behavior
Normal installation of Docker for Windows on Windows Server 2016

### Actual behavior
![5f14c8385989c074caab97a664e12428](https://cloud.githubusercontent.com/assets/423130/22454454/641e656c-e79f-11e6-9047-4a00d4231007.png)
### Information

  - Windows Server 2016 (Version 1607, OS Build 14393.639)
  - Docker for Windows 1.13.0 and Beta 39 

### Steps to reproduce the behavior

  1. Download InsatallDocker.msi 
  2. Run it
  3. Get the error.

**Comment by rneugeba** [comment]
Thanks for your report. This is expected behaviour for now as we currently only support Windows 10 version (as per https://docs.docker.com/docker-for-windows/). We have, however an internal tracking issue to support for Windows Server.

**Comment by Elufimov** [comment]
Thanks for quick response! Could you tell when windows server support will land?

**Comment by rneugeba** [comment]
we are currently in the process of refactoring the installer which will also enabled Windows Server support. I can't give exact timelines for this, but we are not talking several months...

**Comment by Elufimov** [comment]
It is great. I will wait for updates then.

**Comment by fredgate** [comment]
So how to use docker-compose on windows server 2016 ? The recommanded installation provides only the daemon and the client but not compose.

**Comment by friism** [comment]
> So how to use docker-compose on windows server 2016

    Invoke-Webrequest https://github.com/docker/compose/releases/download/1.11.1/docker-compose-Windows-x86_64.exe -OutFile $Env:Programfiles\docker\docker-compose.exe

**Comment by MSch** [comment]
@rneugeba I know it's not yet been several months, but may I nevertheless inquire about an update?

**Comment by DavePilks** [comment]
Hi has there been any update on this? I am trying to build Linux container images on a Server 2016 instance.

**Comment by friism** [comment]
@DavePilks Yes, the new experiemental Edge installer should work on WS2016: https://docs.docker.com/docker-for-windows/install/#download-docker-for-windows
