### ISSUE TITLE
Crashing While Starting.

### ISSUE THREAD

**Issue by berkaygndzs** [docker/for-win#4487]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6830626A-574E-4CEA-9619-C019EF1F439D/20190810184920

### Expected behavior
Start Docker for Windows succesfully.
### Actual behavior
Crashing after a while.
### Information

  - Windows Version: Windows 10 Pro 
  - Docker Desktop Version: 2.1.0.1

### Steps to reproduce the behavior

  1. Try starting the application
  2. It'll crash eventually.
I get this error on crash:
```
Timed out waiting for the lifecycle-server to start.
This may be the result of a slow environment or there may be a real problem.
This timeout can be increased by editing settings.json, value 'lifecycleTimeoutSeconds'.
This file is usually in C:\Users\(your username)\AppData\Roaming\Docker

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()
```

**Comment by tomik23** [comment]
I had the same symptom, every application with a docker did not start after the docker was updated.
What helped, `settings -> reset -> Reset to factory defaults`
Windows 10 pro 1903
Docker 2.1.01 (37199)

**Comment by Johnson90512** [comment]
![image](https://user-images.githubusercontent.com/25690600/62834819-8ac9cd80-bc1f-11e9-9cd5-650f195aafb3.png)

**Comment by berkaygndzs** [comment]
@tomik23 Hey, the reset options are disabled and when i hover over them my cursor is spinning.
![image](https://user-images.githubusercontent.com/20186439/62834981-edd95580-bc5b-11e9-890b-3b73c7c73ffc.png)

**Comment by jpl-jengelke** [comment]
Look at solution near the end here: https://github.com/docker/for-win/issues/3597
