### ISSUE TITLE
Windows 10x64 Pro fails to start upon manually restart

### ISSUE THREAD

**Issue by jayson-lynnfield-zen** [docker/for-win#4490]
id: 2726F93E-0B53-456F-80FE-D310B25692E0/20190811201106

Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Failed to modify device 'Ethernet Connection'.

'DockerDesktopVM' failed to modify device 'Ethernet Connection'. (Virtual machine ID DE6EBF2E-E517-485D-8E97-AE1DA6D10691)

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version: Windows 10 x64 Pro
  - Docker Desktop Version: 19.03.1, build 74b1e89
P.S.: utility were started from non-admin user

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by VenturaFranklin** [comment]
I get this same issue.
Diagnostics ID: DC806410-3658-4133-BB83-D79A514D6942/20191021191423

After clicking "Reset to factory defaults" I get a similar error, but the error says "Element not found"
Diagnostics ID: DC806410-3658-4133-BB83-D79A514D6942/20191021191842

I've seen online to disable/re-enable Hyper-V but disabling Hyper-V kills my whole system and I have to system restore. Hyper-V seems to work fine as I can start other VMs in the manager. But in the manager the DockerDesktopVM is not listed, but at one time was. Is there a way to generate the VM DockerDesktopVM again to start it? Could this be causing issues with Docker Desktop starting?
