### ISSUE TITLE
Kubernetes-as-orchestrator fails to process multi-file `$KUBECONFIG`

### ISSUE THREAD

**Issue by TBBle** [docker/for-win#4491]
- [x] I have tried with the latest version of my channel (Stable)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: N/A, no crash or other behaviour to trigger the diagnostics uploader

### Expected behavior

With a customised `KUBECONFIG` env-var that lists multiple config files, `docker ps` should still function when the option "Deploy Docker Stacks to Kubernetes by default" is selected.

### Actual behavior

With a customised `KUBECONFIG` env-var that lists multiple config files, `docker ps` fails function when the option "Deploy Docker Stacks to Kubernetes by default" is selected, with the following output:

```
PS C:\Users\paulh> docker ps
unable to resolve docker endpoint: default orchestrator is kubernetes but unable to resolve kubernetes endpoint: Error loading config file "C:\Users\paulh\.kube\config;C:\Users\paulh\.kube\dev.config;C:\Users\paulh\.kube\ci.config;C:\Users\paulh\.kube\k8s-test.config;C:\Users\paulh\.kube\ci2.config;C:\Users\paulh\.kube\project.config;": open C:\Users\paulh\.kube\config;C:\Users\paulh\.kube\dev.config;C:\Users\paulh\.kube\ci.config;C:\Users\paulh\.kube\k8s-test.config;C:\Users\paulh\.kube\ci2.config;C:\Users\paulh\.kube\project.config;: The filename, directory name, or volume label syntax is incorrect.
```

It's pretty clearly trying to blindly `open(${KUBE_CONFIG})`, assuming the environment variable points to a single file, not a list of config files.

I couldn't change the setting as the 'Apply & Restart' button wouldn't light up, since the setting is on the Kubernetes tab, and Kubernetes was still starting. So I manually removed the setting from `%USERPROFILE%\.docker\config.json`, and `docker ps` was working again.

I also suspect this was blocking the Docker Desktop Kubernetes stack from starting, but it could also have been a coincidence that as soon as I changed the config file, it started up.

### Information

  - Windows Version: Windows 10 Enterprise 1903 (18362.175)
  - Docker Desktop Version: 2.1.0.1 (37199) Stable

### Steps to reproduce the behavior

  1. Install fresh Docker Desktop for Windows
  2. Enable Kubernetes
  3. Customise your `KUBECONFIG` environment variable to point to extra config files for other Kubernetes stacks you work with
  4. Confirm `docker ps` operates correctly.
  5. Enable the 'Deploy Docker Stacks to Kubernetes by default' setting, click "Apply & Restart"
  6. Confirm `docker ps` now gives the listed error.

**Comment by alexvy86** [comment]
Just ran into the exact same issue

**Comment by TBBle** [comment]
/remove-lifecycle stale

I just hit this (or a variation again), with Docker Desktop for Windows 2.2.0.0, which was failing to start Kubernetes because my currently-selected context was in one of the other files in my `${KUBECONFIG}` than ~/.kube/config.

I didn't capture the log because changing the context to one that was in ~/.kube/config caused startup to complete. I did look at the log, and the error was something like "Cannot <something>, current context is not in kubernetes configuration"

So Docker Desktop is still not processing/merging `${KUBECONFIG}` correctly.

**Comment by mat007** [comment]
Thanks for the reports.
The initial problem with `docker ps` is in the open-source upstream component Docker CLI, see https://github.com/docker/cli/blob/2dcd4d3d2954fa5a64d91d9bb64b337cc70298b7/cli/context/kubernetes/load.go#L99 and should probably be reported there.

@TBBle you’re experiencing a slightly different issue though, I’ll open an internal ticket about it, thanks!

**Comment by TBBle** [comment]
I've opened docker/cli#2334 for the issue I originally reported (and which @alexy86 also hit), and so I'll close this issue.

I'll leave the more-recent issue that @mat007 has taken as an internal ticket to be resolved through that internal ticket.
