### ISSUE TITLE
Error Report

### ISSUE THREAD

**Issue by svetyx** [docker/for-win#4492]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version: Windows 10 Pro 18362.267
  - Docker Desktop Version: 2.0.0.3

### Steps to reproduce the behavior

  1. switch on PC
  2. ...

**Comment by jpl-jengelke** [comment]
https://github.com/docker/for-win/issues/3597
