### ISSUE TITLE
D584A1ED-8BCC-481E-9974-4DFFC77639B8/20190812144417

### ISSUE THREAD

**Issue by m-kovacina** [docker/for-win#4499]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mat007** [comment]
Can you explain what issue you’re facing?
