### ISSUE TITLE
Unable to start: The VM couldn't get an IP address after 60 tries

### ISSUE THREAD

**Issue by juherr** [docker/for-win#45]
### Expected behavior
Upgrade and start.
Or provide a better message in case of issue.

### Actual behavior
First, I tried the auto update which failed without any message (docker didn't start or started with the previous version).
Then, I tried a manual update which worked well but at the start I received:

```
Unable to start: The VM couldn't get an IP address after 60 tries
à Fatal, <Aucun fichier> : ligne 313
à Start-MobyLinuxVM, <Aucun fichier> : ligne 233
à <ScriptBlock>, <Aucun fichier> : ligne 322
   à Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   à Docker.Backend.LinuxContainersEngine.DoStart(Settings settings)
   à Docker.Backend.LinuxContainersEngine.Start(Settings settings)
   à Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass7_0.<Register>b__0(Object[] parameters)
   à Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

### Information

  - Diagnostic ID: 63FC49AC-136A-4694-8FC1-E651A239AEE3/2016-08-18_09-42-11
  - host distribution: Windows 10.0.14393

### Steps to reproduce the behavior

  1. Upgrade to beta23
  2. Try to start

Fix:
I had `127.0.0.1 docker.local` in my `hosts` file to solve a previous issue. When I remove it, docker is running well.

**Comment by rneugeba** [comment]
@juherr Thanks for your report.I tried to reproduce and added `127.0.0.1 docker.local` to `C:\Windows\System32\drivers\etc\hosts` and I could start The app just fine. Did you change anything else?

**Comment by juherr** [comment]
@rneugeba Maybe the fix didn't fix. I've just added the configuration in my host again, and docker is running now.

**Comment by rneugeba** [comment]
Thanks for getting back to me. I'm closing this issue as it seems to have fixed itself for you. We still have a related issue (#17) open in any case.
