### ISSUE TITLE
Docker freezes Windows [on boot]

### ISSUE THREAD

**Issue by Jan0707** [docker/for-win#450]
### Expected behavior

Should boot and launch docker

### Actual behavior

Freezes during boot/login

### Information

- Cannot provide any

### Steps to reproduce the behavior

1 ) Most recent version of Windows 10.
2) Install Docker for windows
3) Docker encounteres the error mentioned in #447 
4) System freezes
5) Hard reset
6) System keeps freezing during boot/login

I would appreciate any help removing docker via command prompt on Windows 10 Install USB stick. Otherwise the machine remains completely unusable...

I thought about just removing the docker directory in C:\Program Files\Docker but wasn't sure if that is a good idea. As the USB stick does not provide a powershell I cannot run the force uninstall script in the docker directory.

**Comment by simonferquel** [comment]
What you can do to prevent Docker for attempting to start is to disable virtualization support. That would provide you a way to safely boot to windows and even send us a diagnostic file :)

**Comment by friism** [comment]
Closing this due to lack of follow-up. @Jan0707 please re-open if you get more details.
