### ISSUE TITLE
Yarn run  /bin/sh: 1: <dependency>: not found

### ISSUE THREAD

**Issue by kmax3672** [docker/for-win#4508]
I am getting the following issues with yarn when trying to start up my docker container using docker compose. After a build and running "docker-compose up -d" I can see my container is created. However, I then try to tail the logs and see the following and my container is not up. My Dockerfile is below. Has anyone run into similar issues and resolved?

I am using Windows 10 Pro and Docker Desktop 2.1.0.1. The following Dockerfile appears to work on a Mac machine.

PS C:\Users\docker-compose> docker-compose logs --tail=100 -f api
Attaching to docker-compose_api_1
api_1 | yarn global v1.12.3
api_1 | [1/4] Resolving packages...
api_1 | [2/4] Fetching packages...
api_1 | [3/4] Linking dependencies...
api_1 | [4/4] Building fresh packages...
api_1 | success Installed "bunyan@1.8.12" with binaries:
api_1 | - bunyan
api_1 | success Installed "knex@0.19.1" with binaries:
api_1 | - knex
api_1 | Done in 20.38s.
api_1 | yarn run v1.12.3
api_1 | $ babel-watch -L ./src/index.js -w config -- --env=local.myname
api_1 | /bin/sh: 1: babel-watch: not found
api_1 | error Command failed with exit code 127.
api_1 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
docker-compose_api_1 exited with code 0

DockerFile

```
FROM node:11.12-stretch

ARG NODE_ENV
ENV NODE_ENV ${NODE_ENV}

# Install common dependencies
RUN apt-get update \
  && apt-get install -y nasm vim net-tools \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Install Yarn
RUN curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3 && \
  ln -sf $HOME/.yarn/bin/yarn /usr/local/bin/yarn && \
  ln -sf $HOME/.yarn/bin/yarnpkg /usr/local/bin/yarnpkg

WORKDIR /tmp
COPY package.json /tmp/
RUN yarn install

WORKDIR /var/app
COPY . /var/app/

ENTRYPOINT ["node", "./build/app/index.js"]

COPY setup/docker-host.sh /
RUN chmod +x /docker-host.sh

EXPOSE 6789

WORKDIR /var/app

```

**Comment by mat007** [comment]
Maybe this should be raised to https://github.com/docker/compose?

**Comment by kmax3672** [comment]
> Maybe this should be raised to https://github.com/docker/compose?

I can raise it there additionally but since this works on some others Macs I'm inclined to believe it's related to Windows

**Comment by mat007** [comment]
Indeed, but it’s still docker-compose. This bug tracker here is for the Docker Desktop application (on Windows), which docker-compose is bundled in.
