### ISSUE TITLE
Set-TimeZone Changing Host Machine TimeZone too

### ISSUE THREAD

**Issue by efaruk** [docker/for-win#451]
## BUG REPORT INFORMATION

**Description**
When we use Set-TimeZone in windowscore based container its changing host machine timezone too.

### Expected behavior
Use Set-TimeZone to set only container timezone
### Actual behavior
Set-TimeZone affecting both container and host machine
### Information
I'm running windows docker host machine inside of an Oracle VirtualBox

**Output of `docker version`:**

```
Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 12
Server Version: 1.12.2-cs2-ws-beta
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.693.amd64fre.rs1_release.161220-1747)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 6 GiB
Name: wincon
ID: TRSR:EBZG:57NQ:VGAH:NTIE:WA4T:ZLAK:7JCX:2LMU:HFHF:UVLV:AZRC
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### Steps to reproduce the behavior

1. Create Dockerfile as following:
```
FROM microsoft/dotnet-framework:3.5
COPY assets/ assets/
ENTRYPOINT [ "powershell" ]
```
2. Build and run container with -it switch
3. Run `Set-TimeZone -Id "Pacific Standard Time"` (Different timezone from host machine)
4. Check Container's and Host Machine time zones with `Get-TimeZone` powershell command

**Note:**: I have already created an issue at: https://github.com/docker/docker/issues/30587

Thanks, regards

**Comment by rneugeba** [comment]
I can not reproduce this with 1.13 and a base nanoserver image nor with the `microsoft/dotnet-framework:3.5` image. I've tried Windows 10 Pro builds 14393.693 and 15014.1000.

This issue tracker is actually for the Docker for Windows application, which currently does not run on Windows Server, so I'm closing this issue.

I suggest to open an issue on https://github.com/docker/docker/  or maybe on https://github.com/Microsoft/Virtualization-Documentation/issues.

Feel free to reference this issue on the new issue.

Thanks
