### ISSUE TITLE
Startup error: Logon failure

### ISSUE THREAD

**Issue by mbrodala** [docker/for-win#4514]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 67AB376F-1034-43C6-A9A9-879845D66C7B/20190814070630

### Expected behavior
Docker Desktop should start normally.

### Actual behavior
Docker Desktop starts slowly and then fails with an error:

```
Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The operation failed.

An unexpected error occurred: Logon failure: the user has not been granted the requested logon type at this computer. (0x80070569).

The operation failed.

The Hyper-V Virtual Machine Management service encountered an unexpected error: Logon failure: the user has not been granted the requested logon type at this computer. (0x80070569).

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()
```

### Information

  - Windows Version: Windows 10 Pro (1903)
  - Docker Desktop Version: 2.1.0.1 (37199)

Notice that I had to [set up an additional local Windows user for drive share](https://blogs.msdn.microsoft.com/wael-kdouh/2017/06/26/enabling-drive-sharing-with-docker-for-windows/) since we use Active Directory here.

### Steps to reproduce the behavior

  1. Start Docker Desktop

Notice that this worked just fine with the previous Docker Desktop release. Is there some way to downgrade to the previous release and retry?

**Comment by mbrodala** [comment]
The error has disappeared after uninstalling and reinstalling Docker Desktop and Disabling/Enabling Hyper-V. Not sure what exactly fixed the issue though. :-/

**Comment by arjunkrishna9911** [comment]
Uninstalling Docker desktop, disabling Hyper-V, restart and re-install of Docker desktop fixed the error in my case. Anyway while re-installing docker will automatically enables the Hyper-V. 

FYI, my windows machine had Virtualbox installed. I guess that might be causing the issue.
