### ISSUE TITLE
while pulling image getting error "no matching manifest for windows/amd64 10.0.17134 in the manifest list entries"

### ISSUE THREAD

**Issue by girish-ankit** [docker/for-win#4518]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Varun2706** [comment]
Yes, i also have same issue, it was working fine with old version.

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place. Thanks
