### ISSUE TITLE
Stuck at Kubernetes is starting when upgraded to 2.1.1.0 edge

### ISSUE THREAD

**Issue by SrikanthSrinivasamurthy** [docker/for-win#4519]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 77942CB7-0E44-41F8-B8D4-31D97468053A/20190814111917

### Expected behavior
Kubernetes cluster should start, Settings panel should have green dot saying Kubernetes is running.
kubectl get pods should return empty set. 
### Actual behavior
docker is up docker command works fine. it downloaded images and all.
but kubectl command gives error.
> kubectl.exe get po
Unable to connect to the server: Gateway Timeout

I am behind origination proxy, gave  proxy setting docker images downloading successfully
```
docker images
REPOSITORY                           TAG                 IMAGE ID            CREATED             SIZE
k8s.gcr.io/kube-proxy                v1.14.3             004666307c5b        2 months ago        82.1MB
k8s.gcr.io/kube-apiserver            v1.14.3             9946f563237c        2 months ago        210MB
k8s.gcr.io/kube-controller-manager   v1.14.3             ac2ce44462bc        2 months ago        158MB
k8s.gcr.io/kube-scheduler            v1.14.3             953364a3ae7a        2 months ago        81.6MB
k8s.gcr.io/coredns                   1.3.1               eb516548c180        7 months ago        40.3MB
k8s.gcr.io/etcd                      3.3.10              2c4adeb21b4f        8 months ago        258MB
k8s.gcr.io/pause                     3.1                 da86e6ba6ca1        20 months ago       742kB
```

### Information
tried with all solution like
1. Delete C:\ProgramData\DockerDesktop\pki folder, 
2. did reset cluster, re-installed docker 
3. used fixed DNS (8.8.8.8) & host file as entry to 127.0.0.1 localhost
4. uninstalled completely restarted machine and reinstalled noting worked.
none of the above worked.
in logs i am seeing 
```
[14:35:08.619][ApiProxy          ][Error  ] time="2019-08-14T14:35:08+05:30" msg="Cannot list nodes: Get https://kubernetes.docker.internal:6443/api/v1/nodes: Gateway Timeout"
[14:35:08.826][ApiProxy          ][Error  ] time="2019-08-14T14:35:08+05:30" msg="Cannot list nodes: Get https://kubernetes.docker.internal:6443/api/v1/nodes: Gateway Timeout"
[14:35:09.624][ApiProxy          ][Error  ] time="2019-08-14T14:35:09+05:30" msg="Cannot list nodes: Get https://kubernetes.docker.internal:6443/api/v1/nodes: Gateway Timeout"
[14:35:09.825][ApiProxy          ][Error  ] time="2019-08-14T14:35:09+05:30" msg="Cannot list nodes: Get https://kubernetes.docker.internal:6443/api/v1/nodes: Gateway Timeout"
```
previous version 2.1.0.0 was working fine.. after upgrade was not working, i uninstalled and tried to reinstall Docker 2.1.0.0 even that got stuck now in kubernets starting phase.

  - Windows Version: Windows 10 Enterprise Version 1709 64 bit 
  - Docker Desktop Version: Docker Edge 2.1.1.0 (37260)
### Steps to reproduce the behavior

Just upgrade the docker to 2.1.1.0

**Comment by tonymathewt** [comment]
Mine is very similar (when I upgraded to 2.1.0.1:

`[17:23:20.195][ApiProxy          ][Error  ] time="2019-08-20T17:23:20+05:30" msg="Cannot list nodes: Get https://kubernetes.docker.internal:6443/api/v1/nodes: Service Unavailable"`

while the error is 'Service Unavailable'

- Windows Version: Windows 10 Pro Version 10.0.17134 64 bit
- Docker Desktop Version: Docker Edge 2.1.0.1 (37199)

**Comment by wu-yafeng** [comment]
Mine is very similar (when I upgraded to 2.1.0.1):

[14:12:14.540][ApiProxy          ][Error  ] time="2019-09-04T14:12:14+08:00" msg="Cannot list nodes: Get https://kubernetes.docker.internal:6443/api/v1/nodes: dial tcp: lookup kubernetes.docker.internal: no such host"

while the error is 'no such hosts'

Windows Version: Windows 10 Pro Version 64 bit
Docker Desktop Version: Docker Edge 2.1.0.1 (37199)

**Comment by EagleEatApple** [comment]
1. Please make sure below lines are in hosts file, those are added by Docker Desktop first time running.
# Added by Docker Desktop
192.168.1.6 host.docker.internal
192.168.1.6 gateway.docker.internal
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section

2. Please make sure your hosts file is "ANSI" format, Windows 10 don't recognize UTF-8.
A better way is to use Windows Notepad with Administrator right to generate a new ANSI hosts file, and then replace the one in C:\Windows\System32\drivers\etc

3. use ipconfig/flushdns to reset DNS, then you should be able to ping kubernetes.docker.internal successfully, like
Pinging kubernetes.docker.internal [127.0.0.1] with 32 bytes of data:
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128

4.  if you cannot edit hosts file, check whether your anti-virus software block it.

5. After restart Docker Desktop, you should be able to see below information in C:\Users\****\AppData\Local\Docker\log.txt,
vpnkit.exe: C:\Windows\System32\drivers\etc\hosts file has bindings for localhost host.docker.internal gateway.docker.internal kubernetes.docker.internal

Hope these can help you fix the issue!

**Comment by wu-yafeng** [comment]
> 1. Please make sure below lines are in hosts file, those are added by Docker Desktop first time running.
> 
> # Added by Docker Desktop
> 192.168.1.6 host.docker.internal
> 192.168.1.6 gateway.docker.internal
> 
> # To allow the same kube context to work on the host and the container:
> 127.0.0.1 kubernetes.docker.internal
> 
> # End of section
> 1. Please make sure your hosts file is "ANSI" format, Windows 10 don't recognize UTF-8.
>    A better way is to use Windows Notepad with Administrator right to generate a new ANSI hosts file, and then replace the one in C:\Windows\System32\drivers\etc
> 2. use ipconfig/flushdns to reset DNS, then you should be able to ping kubernetes.docker.internal successfully, like
>    Pinging kubernetes.docker.internal [127.0.0.1] with 32 bytes of data:
>    Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
>    Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
> 3. if you cannot edit hosts file, check whether your anti-virus software block it.
> 4. After restart Docker Desktop, you should be able to see below information in C:\Users****\AppData\Local\Docker\log.txt,
>    vpnkit.exe: C:\Windows\System32\drivers\etc\hosts file has bindings for localhost host.docker.internal gateway.docker.internal kubernetes.docker.internal
> 
> Hope these can help you fix the issue!

It works for me after add following line to hosts file:
127.0.0.1 kubernetes.docker.internal

**Comment by SrikanthSrinivasamurthy** [comment]
I have upgraded to Docker 2.1.3.0 (38275) it started working

**Comment by benbendemo** [comment]
`[ApiProxy          ][Info   ] time="2020-01-16T20:58:18+08:00" msg="cannot list nodes: Get https://kubernetes.docker.internal:6443/api/v1/nodes: dial tcp: lookup kubernetes.docker.internal: no such host"
[20:58:18.992][GoBackendProcess  ][Info   ] time="2020-01-16T20:58:18+08:00" msg="external: POST /events 200 \"Go-http-client/1.1\" \"\""`

It fixed my problem.

**Comment by benbendemo** [comment]
Thanks for your sharing.
