### ISSUE TITLE
After upgrading to latest Windows Insider build, Docker menu won't appear

### ISSUE THREAD

**Issue by severisv** [docker/for-win#4520]
After upgrading to latest Windows Insider build, Docker menu won't appear. Docker is running fine - I am able to use it from the command line, when I left- or right-click the tray icon, nothing happens. Hovering it shows the "Docker Desktop is running" label.

![bilde](https://user-images.githubusercontent.com/966063/63019767-98d85200-be9c-11e9-9649-5700583332a4.png)

I've tried reinstalling Docker Desktop without luck.

What I would like to do is enable WSL 2 Tech Preview. Is there any way to do that without a working GUI?

**Comment by mat007** [comment]
Is there anything suspicious in `%LOCALAPPDATA%\Docker\log.txt` when the menu fails to open?
Which version of Docker Desktop are you running?

**Comment by severisv** [comment]
v19.03.1

As of today it magically works. Haven't updated Docker or Windows (that I know of).

Looking at the logs there are no logs from the time period that I couldn't open the menu - only install logs that say nothing unusual.

**Comment by vincentytran** [comment]
I have the same issue but for the latest stable version where the icon right click does not work.
