### ISSUE TITLE
DNS lookup of host machine fails

### ISSUE THREAD

**Issue by bender316** [docker/for-win#4523]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 16BC9DBC-4313-4E42-B04D-610FA09C9374/20190814131737

### Expected behavior
Docker container can access host machine via its FQN.

### Actual behavior
Docker container fails to resolve IP address from host machine.

asterisk were added by me. They contain real information.

my machine:
root@e351e345bdf9:/app/apache-artemis-2.6.3# nslookup nb-dmu.\*.\*.de
Server:         127.0.0.11
Address:        127.0.0.11#53

Non-authoritative answer:
*** Can't find nb-dmu.\*.\*.de: No answer

another teammate's machine
root@e351e345bdf9:/app/apache-artemis-2.6.3# nslookup pc-ms.\*.\*.de
Server:         127.0.0.11
Address:        127.0.0.11#53

Non-authoritative answer:
Name:   pc-ms.\*.\*.de
Address: \*.\*.\*.\*

### Information

  - Windows Version: Win10 1903
  - Docker Desktop Version: 2.1.0.1

It broke when updating to Docker Desktop 2.1.0.0

### Steps to reproduce the behavior
It can be reproduced on every Docker desktop installation on my team so I'm quite sure it can be reproduced with the commands in the "actual behavior" section above:

**Comment by fhoering** [comment]
Same for reverse dns lookups.

Before:

Now:
```

**Comment by fhoering** [comment]
Same for reverse dns lookups.

Before (Docker version 18.09.2, build 6247962):
```
[f.horing] ~ $nslookup 8.8.8.8
Server:         192.168.65.1
Address:        192.168.65.1#533

Non-authoritative answer:
8.8.8.8.in-addr.arpa    name = dns.google.

Authoritative answers can be found from:
```

Now (Docker version 19.03.2, build 6a30dfc)
```
[f.horing] ~ $nslookup 8.8.8.8
Server:         192.168.65.1
Address:        192.168.65.1#53

Non-authoritative answer:
*** Can't find 8.8.8.8.in-addr.arpa.: No answer

Authoritative answers can be found from:
```

As indicated here https://github.com/docker/for-win/issues/4425 the workaround of changing /etc/resolv.conf from `192.168.65.1` to a working dns works.
