### ISSUE TITLE
Docker continues starting at login even with disabled option

### ISSUE THREAD

**Issue by reebr** [docker/for-win#4525]
### Expected behavior
Allow disable automatic initialization of Docker on Windows logon.

### Actual behavior
It Is being automatically initialized at logon even with the settings being disabled:

<kbd>![image](https://user-images.githubusercontent.com/3982052/63049793-e8744900-beaf-11e9-8a6f-35b653c7f3ba.png)</kbd>

### Information
I am trying to disable the Docker auto initialization when I log on to Windows, but even disabling this option, Docker is initialized. This problem was reported before on #3669 (on version 2.0.03) and until now this problem still exist.

Not being cool because I have several containers that run at the same time as Windows boots, leaving the environment completely slow.

- Windows Version: Windows 10 Pro - Version 1809 (17763.678)
- Docker for Windows Version: 2.1.0.1 (37199)

### Steps to reproduce the behavior

1. Install Docker for Windows
2. Go to the "general settings" menu and disable automatic startup on log in
3. Restart the machine and wait, Docker will start automatically

**Comment by mat007** [comment]
Can you run the following (powershell or cmd) command and tell us if you see any entry for Docker Desktop?
```
reg query "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run"
reg query "HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Run"
```

**Comment by reebr** [comment]
@mat007 Yes.
```
Docker Desktop    REG_SZ    C:\Program Files\Docker\Docker\Docker Desktop.exe
```

**Comment by mat007** [comment]
Can you try enabling and disabling the check box in Docker Desktop and see if that removes that registry key?

If not you can override this setting by disabling Docker Desktop startup using Windows Startup apps:

![image](https://user-images.githubusercontent.com/2386884/63171154-41241d00-c03b-11e9-97d5-8fa7b88f0e47.png)

**Comment by reebr** [comment]
I really don't understand what happened. 😯 

I had already tried to enable and disable startup but still had not worked. Well, following these steps I I got it, Docker is not initializing on startup as expected.

Thank you.
