### ISSUE TITLE
Update to Docker 2.1.1.0 (37260) fails silently after download is complete

### ISSUE THREAD

**Issue by Monte-Christo** [docker/for-win#4527]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C92A4416-C181-4F89-BA37-C377AC4831DD/20190815085720

### Expected behavior

Update  to Docker 2.1.1.0 (37260) succeeds.

### Actual behavior

Update process quits silently after download is complete.

### Information

  - Windows Version: Win 10 Pro 1903 Build 18632.267
  - Docker Desktop Version: 2.0.5.0 (33518)

### Steps to reproduce the behavior

  1. .Start Docker Desktop
  2.  Docker Desktop Update window pops up
  3. Click on Install Update
  4. Confirm elevation
  5. Download will start. After it completes (100%), window closes and Docker quits.

**Comment by mat007** [comment]
You can try running the installer directly, here is the link to download the latest Stable: https://download.docker.com/win/stable/Docker%20for%20Windows%20Installer.exe
If you do it on the command line adding the following flag you’ll get a log file you can look at or copy the errors here to try and understand what happens:
```
"Docker Desktop Installer.exe" install --log-output-file=install-log.txt
```

**Comment by Monte-Christo** [comment]
Attached please find the install logs. i ran the command in an elevated PowerShell window.
It says " Component CommunityInstaller.ShortcutAction failed" and "The system cannot find the file specified. (Exception from HRESULT: 0x80070002)". I do not know how to get beyond this.

[install-log2.txt](https://github.com/docker/for-win/files/3508809/install-log2.txt)

**Comment by mat007** [comment]
This looks like a duplicate of #4480.

**Comment by Monte-Christo** [comment]
Thanks. That did it. Much appreciated.
