### ISSUE TITLE
Unable to start Docker Desktop

### ISSUE THREAD

**Issue by kaifengxu** [docker/for-win#4544]
082C8218-6504-4954-B2EC-8C87646D5AF1/20190818153552

**Comment by ulrich** [comment]
Hello @kaifengxu 

Can you explain in more detail the issue? You can use the provided PR template for that.

Moreover, I saw in the diagnostics logs that the values in daemon.json file.

`
{"debug":true,"experimental":false,"insecure-registries":1,"registry-mirrors":1}
`

Can you remove the insecure-registries and registry-mirrors entries?

**Comment by kaifengxu** [comment]
> 你好@kaifengxu
> 
> 您能否更详细地说明问题？您可以为此使用提供的PR模板。
> 
> 此外，我在诊断日志中看到daemon.json文件中的值。
> 
> `{"debug":true,"experimental":false,"insecure-registries":1,"registry-mirrors":1}`
> 
> 您可以删除不安全的注册表和注册表镜像条目吗？

the problems have been resolved,Caused by windows virtualization settings
