### ISSUE TITLE
USB/IP device added by a privileged container is only visible by other privileged containers

### ISSUE THREAD

**Issue by eine** [docker/for-win#4548]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E9FA3323-7ADF-49BB-A59A-73C64DC4AFC1/20190819014954

### Expected behavior

Registering/adding an USB/IP device in a privileged container makes it visible/usable straightaway.

### Actual behavior

The device is properly registered/add/created, and it can be successfully used by ANY OTHER privileged container created afterwards, but not by the container which created it.

### Information

As seen in libusb/libusb#613, I found this issue while trying to use [VirtualHere](https://www.virtualhere.com) to share a USB device between a Windows 10 host and a Docker Desktop container running on the same host.

### Steps to reproduce the behavior

See https://github.com/ghdl/docker/tree/feat-usbip/usbip.

1. Build USB/IP kernel modules for the Hyper-V VM in an unprivileged container.
2. With a privileged container, load USB/IP kernel modules.
3. Start virtualhere windows server on the host.
4. Start virtualhere client inside a privileged GNU/Linux container.
5. Add hub to the virtualhere client and `USE` a device.
6. `ls -la /dev/bus/usb/001` in the container where the client is running.
7. `ls -la /dev/bus/usb/001` from any other privileged container.

**Comment by oholimoli** [comment]
We are using Docker Desktop with WSL 2 and need a way that the container can access our debugger that is connected via USB.
