### ISSUE TITLE
Config File gets corrupted on Windows crash

### ISSUE THREAD

**Issue by cfstras** [docker/for-win#455]
### Expected behavior
Docker starts back up after the system crashed with a bluescreen

### Actual behavior
A message appears:
```Unable to start Docker for Windows service: 2 at Docker.Program.Run(IReadOnlyCollection`1 args)```
This is a copy of #208 -- I figured out what caused this and have reproduced it (accidentally) at least two times.

When I look into `%APPDATA%/Docker/settings.json` after a Bluescreen (does not seem to matter what triggered the bluescreen), the file is filled with a bunch of null bytes.
Deleting the file fixes the problem, but that means losing the settings.

I'm running on Windows 10 x64 10.0.14393,
Docker 1.13.0 (9795)

**Comment by dgageot** [comment]
Hi @cfstras, it's nice that you managed to identify the root cause of this issue. We are going to take a look at what we can do to better deal with this kind of situation in the future.

**Comment by JeremyKennedy** [comment]
I'd like to add that I encountered this problem as well, but deleting the file didn't fix it. I deleted the ProgramData, Roaming, and Local folders, but I still encountered the error.

I ended up fixing it when I noticed that the startup type of the "Docker for Windows" service was set to disabled, so I changed it to manual. This fixed my issue.

I submitted a crash report: CE61147B-EB18-4B48-9598-C80B329CA715/2017-02-17_13-43-29

**Comment by grangeway** [comment]
I've seen this behaviour on other dotnet apps - so i'd be really interested to know if anyone investigates further if there's an underlying dotnet/windows bug here

**Comment by jasonxu11** [comment]
I have resolved the problem,just in the control panel find the docker and right click and then select the repair menu,if not work, download the docker from official site,also  **right click** the InstallDocker.msi select the repair menu

**Comment by jrmclau** [comment]
I came here to post my solution, but it is the same as @JeremyKennedy's. I changed the service from disabled to manual.
