### ISSUE TITLE
Docker container stuck in unhealthy state and running docker stop hangs

### ISSUE THREAD

**Issue by carlsonad** [docker/for-win#4554]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:69AD3559-BCAC-4B98-A9A5-EF541EF47468/20190819192611

### Expected behavior
The docker container I'm running wouldn't be unhealthy or would respond to docker stop commands

### Actual behavior
The docker container is marked unhealthy and docker stop just hangs.

### Information

  - Windows Version: Windows 10 Version 1809 Build 17763.678
  - Docker Desktop Version: 2.1.0.1 (37199) stable

I'm using a microsoft/mssql-server-windows-developer container for a local instance of SQL Server.   It's the only container that I'm running.  I was able to connect to SQL sometime early last week.  Probably on Monday or Tuesday.  I haven't tried connecting since then until this afternoon.  Windows updates were applied over the weekend and I had to restart my computer this morning.  Now docker ps shows the following:

![image](https://user-images.githubusercontent.com/12514767/63294833-ea178580-c290-11e9-84ea-0fc377ba98e2.png)

I've tried docker stop and the command just hangs.  No error is displayed, the container never stops and the command never returns control back to the command prompt.

### Steps to reproduce the behavior

I don't know how I got in this state so I don't have exact steps.  Maybe it started happening after windows updates were run?

**Comment by derekwbrown** [comment]
I have same problem.
Windows 10 1809 Build 18362.295
C:\WINDOWS\system32>docker version
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:17:08 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:25:07 2019
  OS/Arch:          windows/amd64
  Experimental:     false

**Comment by suinxinliulang** [comment]
I have the same problem，but my STATUS is normal and I use commads like docker-compose down stop kill are not working

**Comment by skivol** [comment]
Had seemingly similar problem: the container (nginx with static content) of a service managed by docker swarm ended up in "unhealthy" state probably directly after start (no logs were outputted by it).
`docker stop container_id` didn't hang, but didn't stop the container either.

`docker rm -f container_id` did the job though (the scale of the service was 1 and there was another healthy container running beside the unhealthy one so it was a matter of cleaning up the things).

**Comment by coolfarmer** [comment]
Same problem here, I have installed Docker to run Plex Media Server. Sometime I can stop the container without problem, and sometime it just hang and I need to reboot Docker + net stop/start com.docker.service.

**Comment by Drewster727** [comment]
Exact same problem on Windows Server 2019 (1809)

**Comment by coolfarmer** [comment]
I just found why mine was stuck and unhealty, I was using SMB share with a SQLite Database which is using file locking and SMB share can't use that feature, so the corrupted database push my container to an unhealty state. If this can help other, i'm happy!

**Comment by Drewster727** [comment]
> I just found why mine was stuck and unhealty, I was using SMB share with a SQLite Database which is using file locking and SMB share can't use that feature, so the corrupted database push my container to an unhealty state. If this can help other, i'm happy!

@coolfarmer I am using an SMB share on my host, mounting it as a local drive (i.e. M drive) and then sharing that path to the container. Could be related, still has to be a bug though.

**Comment by Drewster727** [comment]
Update:
To test the SMB share theory -- I moved my SMB network share files to the C drive of one of the swarm windows nodes. Then, reinitialized my swarm service to mount to the local C locations where I placed the files. I don't see the containers sticking around now. I'll provide another update if I see it get stuck again, but so far so good... However, this is bad, I *need* my SMB share because I have large files my containers use that makes it impractical to copy to every swarm node individually.

**Comment by coolfarmer** [comment]
In my case I use a little workaround, I have mounted my folder inside a docker volume (file-locking is autorized between that volume and my container). And with this container (https://hub.docker.com/r/gdiepen/volume-sharer) I can access that volume from SMB at \\10.0.75.2

More infos: https://www.guidodiepen.nl/2017/08/sharing-all-your-docker-data-volumes-via-samba/
I hope this can help you too.

**Comment by Drewster727** [comment]
@coolfarmer thanks -- unfortunately, I'll need something that is more production-ready, which is an official fix from docker. @thaJeztah have you seen this one before by chance?

**Comment by Drewster727** [comment]
Just observed this behavior again. I do *not* actually thing it's related to SMB shares, at least not in my case. Here are some related logs I saw in the event viewer about it trying to terminate a container and failing, leaving it orphaned/running:
```
TimeGenerated : 10/10/2019 11:49:50 AM
Message       : failed to terminate hccshim container [container=aa9299de7eef41a91f8bef3aafce412733a8274f51da2fc775b292cea767351b module=libcontainerd
                namespace=moby error=container aa9299de7eef41a91f8bef3aafce412733a8274f51da2fc775b292cea767351b encountered an error during Terminate:
                failure in a Windows system call: The remote procedure call failed and did not execute. (0x6bf) process=init pid=9580 signal=9]

TimeGenerated : 10/10/2019 11:49:50 AM
Message       : hcsshim::ComputeSystem::Terminate - End Operation - Error [cid=aa9299de7eef41a91f8bef3aafce412733a8274f51da2fc775b292cea767351b
                error=Terminate aa9299de7eef41a91f8bef3aafce412733a8274f51da2fc775b292cea767351b: The remote procedure call failed and did not execute.]

TimeGenerated : 10/10/2019 11:49:20 AM
Message       : failed to shutdown hccshim container [module=libcontainerd namespace=moby
                container=aa9299de7eef41a91f8bef3aafce412733a8274f51da2fc775b292cea767351b process=init pid=9580 signal=15 error=container
                aa9299de7eef41a91f8bef3aafce412733a8274f51da2fc775b292cea767351b encountered an error during Shutdown: failure in a Windows system call:
                The remote procedure call failed and did not execute. (0x6bf)]

TimeGenerated : 10/10/2019 11:49:20 AM
Message       : hcsshim::ComputeSystem::Shutdown - End Operation - Error [cid=aa9299de7eef41a91f8bef3aafce412733a8274f51da2fc775b292cea767351b
                error=Shutdown aa9299de7eef41a91f8bef3aafce412733a8274f51da2fc775b292cea767351b: The remote procedure call failed and did not execute.]
```

**Comment by ibauersachs** [comment]
/remove-lifecycle stale
This is still an issue, regardless of whether SMB is involved or not.

```
Client: Docker Engine - Enterprise
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        2ee0c57608
 Built:             11/13/2019 08:00:16
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.12
  Git commit:       2ee0c57608
  Built:            11/13/2019 07:58:51
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Comment by bkwdesign** [comment]
I'm experiencing the same thing on my Docker Windows .. running same sql server image as the OP (microsoft/mssql-server-windows-developer)
```
Server:
 Containers: 8
  Running: 1
  Paused: 0
  Stopped: 7
 Images: 1
 Server Version: 19.03.5
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 18362 (18362.1.amd64fre.19h1_release.190318-1202)
 Operating System: Windows 10 Pro Version 1903 (OS Build 18362.592)
 OSType: windows
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.92GiB
 Name: bkwdesign-work
 ID: YBEY:V426:ZTNX:4QFQ:SMZK:EWPV:MUIT:QID7:BV7Q:JJMA:NUGC:BMP2
 Docker Root Dir: D:\Scratch\Toolz\docker-graph
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 45
  System Time: 2020-01-23T08:05:40.945675-05:00
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

Here's the way I start my container:
```
docker run -d -p 1433:1433 -v D:/temp/:C:/temp/ --isolation=hyperv -e sa_password=[myPwd] -e ACCEPT_EULA=Y -e attach_dbs="[{'dbName': 'prod','dbFiles': ['C:\\temp\\prod.mdf','C:\\temp\\prod.ldf']},{'dbName': 'MyOtherDB','dbFiles': ['C:\\temp\\MyOtherDB.mdf', 'C:\\temp\\MyOtherDB.ldf']  }]" microsoft/mssql-server-windows-developer
```

**Comment by McKeownDesign** [comment]
If you are using IIS try this:
https://github.com/microsoft/IIS.ServiceMonitor

Our container has same type of issues. I think it had something to do with nothing making IIS requests and it shutting down. This will keep the IIS service running and has worked for us. Just pop a powershell script in your dockerfile and run this executable.

**Comment by greenmooseSE** [comment]
FWIW, in our case the unwanted behavior started when ```vmcompute.exe``` crashed (using Docker Enterprise on Windows Server 2019).
Containers became unresponsive/unhealthy after about 17 minutes, juast after ```vmcompute.exe``` crashed, and could not be stopped via docker stop.
Issue went away when uninstalling WMWare Tools (see https://github.com/docker/for-win/issues/5044).

From event viewer:
```
Faulting application name: vmcompute.exe, version: 10.0.17763.831, time stamp: 0x26b81899
Faulting module name: ntdll.dll, version: 10.0.17763.831, time stamp: 0x1f1a0210
Exception code: 0xc0000409
Fault offset: 0x00000000000a4720
Faulting process id: 0x2708
Faulting application start time: 0x01d5dfecd2e6910a
Faulting application path: C:\Windows\system32\vmcompute.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 1e402011-7a67-4b1a-a147-7a89c6dcde67
Faulting package full name: 
Faulting package-relative application ID: 
```
