### ISSUE TITLE
Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection

### ISSUE THREAD

**Issue by pfmoore** [docker/for-win#4557]
Opening a new issue with my specific details, as requested in other similar issues which have been closed.

  - [x] I have tried with the latest version of my channel (Stable)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 24E54C5B-B53C-4B69-AB63-742B6467DBF7/20190820081826

### Expected behavior

`docker pull ubuntu` downloads an ubuntu image.

### Actual behavior

```
>docker pull ubuntu
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

### Information

I am running Windows 10, behind a corporate NTLM proxy over which I have no control. I have cntlm running on my local PC, configured correctly and confirmed to work with other software.

Environment variable settings:

```
HTTP_PROXY=http://localhost:3128
HTTPS_PROXY=http://localhost:3128
```

(Variables in the SYSTEM area are named in uppercase, in the USER area in lowercase. Both have the same values. Checking the environment from a command prompt shows uppercase used. I have no idea if case matters here).

This has happened since I installed Docker, I have not been able to get things working. I have tried:

* Setting my docker DNS to 8.8.8.8
* Restarting (repeatedly!) all of docker desktop, the docker service, my PC and cntlm.
* Setting "Manual proxy configuration" in Docker desktop to `http://localhost:3128`, `http://127.0.0.1:3128` and `http://10.0.75.1:3128`, none of which work.

I will also try setting my global proxy environment variables to `http://10.0.75.1:3128` and update this issue (I haven't tried this yet, and it needs a reboot so I am posting this issue now and will update once tried). **Edit:** Confirmed, setting http(s)_proxy to `http://10.0.75.1:3128` doesn't work either.

**Please do not provide suggestions for Linux or for docker machine on older versions of Windows** - this is a Docker for Windows issue on Windows 10 that I am experiencing and I will not be able to follow Linux-based suggestions. It will be a lot harder for me to confirm I've followed all suggestions and still have an issue if people offer suggestions that only apply to other platforms. There are a lot of other issues for this problem, and they all seem to contain suggestions that I can't follow.

  - Windows Version: 10
  - Docker Desktop Version: 2.1.0.1 (37199)

### Steps to reproduce the behavior

  1. `docker pull ubuntu`

**Comment by luchsamapparat** [comment]
Did you find a solution for your issue?

**Comment by pfmoore** [comment]
No. I simply gave up trying to use Docker on that machine 🙁
