### ISSUE TITLE
Failed to Start Docker Service on GCE

### ISSUE THREAD

**Issue by silverbp** [docker/for-win#456]
### Expected behavior

Install Docker on Windows Server 2016 and for the service to start.

### Actual behavior

After installing Docker on Windows Server 2016 in GCE I get the following error in the event log.
```
 fatal: Error starting daemon: Error initializing network controller: Error creating default
                     network: HNS failed with error : Unspecified error
```

### Information

  - Windows Server 2016 Core (also tried non-core 2016 version)
  - GCE Cloud Hosting
  - Docker Version 1.13.0 (But have also tried the 1.12 in the OneGet/Nuget repo)

### Steps to reproduce the behavior

  1. Create new Windows Server 2016 Core VM on GCE
  2. `Add-WindowsFeature Containers -restart`
  3. Login to machine after reboot
  4. `wget -UseBasicParsing https://get.docker.com/builds/Windows/x86_64/docker-1.13.0.zip -OutFile Docker.zip`
  5. `Add-Type -A 'System.IO.Compression.FileSystem';  [IO.Compression.ZipFile]::ExtractToDirectory('Docker.zip', 'docker');`
  6. `dockerd.exe --register-service`
  7. `Start-Service Docker`
  8. `$a = Get-EventLog -LogName application -EntryType Error -Newest 1`
  9. `$a | format-list -property *`

**Comment by silverbp** [comment]
I've also tried the documented way of installing docker which uses oneget and install 1.12... version, the above install 1.13. Neither will start up.

**Comment by dgageot** [comment]
Hi @silverbp I haven't tried those yet, but have you take a look at Google's instructions? https://cloud.google.com/compute/docs/containers/#docker_on_windows

**Comment by silverbp** [comment]
Hm, can't believe I didn't find that before, that works, thanks for the help!
