### ISSUE TITLE
docker desktop enable kubernetes failed, always is starting...

### ISSUE THREAD

**Issue by BoraDon** [docker/for-win#4569]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
kuberenetes enable success
### Actual behavior
still starting for hours
### Information

  - Windows Version:
win10
  - Docker Desktop Version:
37199 stable
### Steps to reproduce the behavior

Diagnostics ID is 
B127CB3F-C8C7-42C6-A978-AC84E8C61054/20190822100144
  1. tried removing pki folder, .kube folder, still not working
  2. shutdown firewall and change the DNS to 8.8.8.8, still not working
  3. add KUBECONFIG enviroment variable as systerm variable, still not working
  4. install and open docker desktop as administrator, still not working

**Comment by BoraDon** [comment]
the log is as following:
[18:24:48.671][ApiProxy          ][Error  ] time="2019-08-22T18:24:48+08:00" msg="Cannot list nodes: Get https://kubernetes.docker.internal:6443/api/v1/nodes: EOF"
[18:24:49.027][GoBackendProcess  ][Info   ] error copying: EOF

**Comment by Swissbite** [comment]
Same issue on my machine.

**Comment by Swissbite** [comment]
After several other solutions I did the final solution, and I'm not happy because it did not solve the root issue (which I don't know what it is). But this worked for me:

- Uninstall Docker for Desktop (which removes the VM)
- Delete .kube
- Delete \AppData\Local\Docker
- Install Docker for Desktop

After enabling kubernetes and all other required settings, it works...

**Comment by BoraDon** [comment]
> After several other solutions I did the final step by completely uninstall docker and reinstall it. I'm not happy because it did not solve the root issue (which I don't know what it is).
> 
> * Uninstall Docker for Desktop (which removes the VM)
> * Delete .kube
> * Delete \AppData\Local\Docker
> * Install Docker for Desktop
> 
> After enabling kubernetes and all other required settings, it works...

thanks @Swissbite ,my issue was solved, the reason is Chinese Greate Firewall...
it's so annoy ...

**Comment by huangjinzhou** [comment]
嗨！你好，我也碰到跟你同样的问题，请问你是怎么解决的？我开启蓝灯也没能解决

**Comment by yefuchao** [comment]
> 嗨！你好，我也碰到跟你同样的问题，请问你是怎么解决的？我开启蓝灯也没能解决

如果可以的话，卸载重装可以解决。
