### ISSUE TITLE
Can't create a Windows container with 4G of memory on Windows 10

### ISSUE THREAD

**Issue by Almenit** [docker/for-win#457]
### Expected behavior
A Windows container with 4G of memory
### Actual behavior
Error response from daemon: container f0a146e253d820674f1d7116bc59237a2fea5f7963688a5081d647b1c0625c29 encountered an error during CreateContainer: failure in a Windows system call: The handle is invalid. (0x6).
### Information

  - Diagnostic ID: D56E4B55-0A2E-4DEB-B014-876267EC5BA1/2017-02-02_10-56-52
  - Version: 1.13.1-rc1-beta40 (9961) Channel: beta
  - OS: Windows 10 Pro 1607

### Steps to reproduce the behavior
docker run -it -m 4G microsoft/windowsservercore powershell

**Comment by rneugeba** [comment]
Thanks for your report. I can't reproduce this issue on my system, but it does look like an issue with the docker engine and not the Docker for Windows application. There error is coming from the windows engine daemon.

Could you open an issue on https://github.com/docker/docker and provide the output of:
```
docker info
(Get-CimInstance -Namespace root\cimv2 Win32_OperatingSystem).BuildNumber
get-hotfix
```
as well as the contents of the log file which you can get from the `Diagnose & Feedback -> Logs` menu. People will be most interested in lines prefixed with `[WindowsDockerDaemon]`.

Thanks

**Comment by Almenit** [comment]
Ok thanks
Issue submitted.
