### ISSUE TITLE
Reset docker to factory settings options not available. 

### ISSUE THREAD

**Issue by albertolo** [docker/for-win#4576]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
As stated in docs there should be an option to restore to factory settings. 

### Actual behavior
There is no option to restore to factory settings 

### Information
 
  - Windows Version:  Windows 10 Pro Version 1903 
  - Docker Desktop Version:
Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:17:08 2019
 OS/Arch:           windows/amd64
 Experimental:      true
![foto docker](https://user-images.githubusercontent.com/1964766/63539112-f55ff080-c4de-11e9-926c-0e9b85c865f0.PNG)

**Comment by stephen-turner** [comment]
As explained in the release notes, it's moved to the new Troubleshooting pane on Edge. However, we will be making it more obvious before the new UI graduates to Stable.

**Comment by sharathchandra717** [comment]
Its here
![image](https://user-images.githubusercontent.com/31856935/76211588-a2584b80-622c-11ea-8a0b-15856f280deb.png)
