### ISSUE TITLE
WSL 2 Tech Preview Installer "Existing installation is up to date"

### ISSUE THREAD

**Issue by AdamVig** [docker/for-win#4580]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] ~I have uploaded Diagnostics~ (does not apply)
  - ~Diagnostics ID:~

### Expected behavior
[WSL 2 Tech Preview](https://docs.docker.com/docker-for-windows/wsl-tech-preview/#download) should install with the provided installer.

### Actual behavior
Installer says "Downloading package..." then "Existing installation is up to date." When I run Docker, there is no "WSL 2 Tech Preview" option on the right click menu.

### Information

  - Windows Version: 18965.1000 (Insiders "Fast" track)
  - Docker Desktop Version: 2.1.0.1

### Steps to reproduce the behavior

  1. Download [Docker Desktop WSL 2 Tech Preview Installer](https://download.docker.com/win/edge/36883/Docker%20Desktop%20Installer.exe).
  2. Run the installer.

**Comment by robmccready** [comment]
Seeing the same thing.

Docker: 2.1.0.2 (37877)
Windows: 18970.rs_prerelease.190824-1711

**Comment by AdamVig** [comment]
I was able to work around this by uninstalling Docker then running the tech preview installer again.
