### ISSUE TITLE
.dockerignore-file documentation

### ISSUE THREAD

**Issue by Alessar** [docker/for-win#459]
Possible it is documentation issue.
https://docs.docker.com/engine/reference/builder/#/dockerignore-file

Documentation says that ```/foo/bar``` and ```foo/bar``` it are the same.
### Expected behavior
Expected that ```/node_modules``` and ```node_modules``` will be the same too.
### Actual behavior
In case ```node_modules``` looks like, all stuff in that directory are ignored correctly.
In case ```/node_modules``` docker try to push node_modules into container and sometimes get error:
```WindowsError: [Error 3] The system cannot find the path specified: 'E:\\Project\\node_modules\\very-very-long-path\\filename'```

And additionally, looks like, docker cannot work with long names - possible it is issue too.

**Comment by friism** [comment]
@Alessar please re-open on the `docker/docker` repo since this is an engine issue.

It would also be good if you could expand your examples to make it easier to reproduce the problem.

Thanks!
Michael
