### ISSUE TITLE
Docker does not start after Windows 10 update

### ISSUE THREAD

**Issue by hli-git3** [docker/for-win#4592]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 04A48174-C6CA-4D99-9431-002D1E2D139E/20190826132809

### Information

  - Windows Version: Windows 10 Enterprise 1809
  - Docker Desktop Version: 2.1.0.1(37199)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jpl-jengelke** [comment]
I'll just drop this here: https://github.com/docker/for-win/issues/3597
