### ISSUE TITLE
Unable to open Docker UI from system tray icon

### ISSUE THREAD

**Issue by razvannegrea-sys** [docker/for-win#4593]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
When I right click the Docker system tray icon, I should be able to see the Docker UI pop up.

### Actual behavior
Nothing happens, even after more than 1 minute.

### Information
This problem appears even after I reinstalled Docker for Windows 

  - Windows Version: Windows 10 Enterprise 
  - Docker Desktop Version: 
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:17:08 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:17:52 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

### Steps to reproduce the behavior
1. Install Docker for Windows
2. Right-click the Docker system tray icon

**Comment by padyx** [comment]
Same here. Upgraded via built-in update function to 2.1.0.1 and the tray just no longer works.
Uninstalling & Reinstalling does not fix the issue.

**Comment by vincentytran** [comment]
I have the same issue. System tray does not work.

**Comment by whereisaaron** [comment]
For me, I downloaded a fresh copy of the installer, completely uninstalled 2.1.0.1, then installed it again with the downloaded installer. and that did work to get the System Tray menu back.

**Comment by razvannegrea-sys** [comment]
I also tried uninstalling and using a fresh copy of the 2.1.0.1 installer - but no luck :(

**Comment by padyx** [comment]
Still present after upgrade to 2.1.0.3.
Also "Reset to factory defaults" (shown when Hyper-V connection was somehow broken) did not resolve the issue.

**Comment by razvannegrea-sys** [comment]
Even with the 2.0.2.0 version from the Edge channel, after a restart, the problem re-occurred.

**Comment by f-leclere** [comment]
same issue occured on win10.1803 or 1809 and dockerdesktop 2.1 series not with 2.0 series

**Comment by whereisaaron** [comment]
Seems a permanent bug now. Every update the problem occurs again. I have to completely uninstall and install from scratch to get it stable again.
