### ISSUE TITLE
Docker desktop is failing to start with the error 'Timed out waiting for the lifecycle-server to start.'

### ISSUE THREAD

**Issue by harshitshah436** [docker/for-win#4596]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `74EA6B74-804D-43A1-8DB9-09010615B4F2/20190826180252`

### Expected behavior

After a clean install, docker desktop should start, but it's not starting.

### Actual behavior

Getting the following error message, which is hard to debug.
```
Timed out waiting for the lifecycle-server to start.
This may be the result of a slow environment or there may be a real problem.
This timeout can be increased by editing settings.json, value 'lifecycleTimeoutSeconds'.
This file is usually in C:\Users\(your username)\AppData\Roaming\Docker

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()
```

[log.txt](https://github.com/docker/for-win/files/3542593/log.txt)

### Information

  - Windows Version:  Windows 10 Enterprise (Id: 1803, Build: 17134). This is a windows 10 VM hosted on VMWare vsphere.
  - Docker Desktop Version: 2.1.0.1

Before few weeks, everything was working fine. I think, I tried to update docker or restarted the machine and then it has stopped working.

I have tried with 2.0.0.3 and 2.1.0.1 stable installers but none of those are working and giving same errors. I tried increasing memory, enabling/disabling hyper-v but none of those has helped yet.

### Steps to reproduce the behavior

  1. Clean install/reinstall
  2. Start docker desktop.

**Comment by gljubojevic** [comment]
Mac Parallels 13.3.2, Windows 10 pro 1903 virtual machine
- Stable 2.1.0.1 doesn't work
- Stable 2.0.0.3 doesn't work (as suggested above)

Both versions have same issue virtual machine in Hyper-V consumes 50% host CPU and never gets ready to work.
- Changing VM settings in (more memory or more CPU-s ) doesn't have any effect.
- Extending lifecycle timeout up to 600s doesn't have any effect

However latest Edge release: 
Docker Desktop Community 2.1.1.0 (37260) **works**, starts within 10s
Also I have selected inside Edge version installation to install missing windows components  not sure if this made difference or what exactly changes in Win.

I have disabled docker desktop auto start on OS startup, hate having apps running that I don't use so I can't confirm if starts within 10s when OS is starting.

Hope this helps.

**Comment by mikeparker** [comment]
Your machine is really slow. Are you running nested virtualization? i.e. Windows in a VM (e.g. on a mac)? 

Have you tried increasing the timeout in the settings file, as per the error message?

**Comment by gljubojevic** [comment]
@mikeparker if you asking me than:

> Your machine is really slow. Are you running nested virtualization? i.e. Windows in a VM (e.g. on a mac)?

- Yes I'm running Windows 10 pro on Mac notebook (i7, 16GB ram) using paralles
- Yes Nested Virtualisation is enabled for W10 VM it doesn't work without it

> Have you tried increasing the timeout in the settings file, as per the error message?

- Yes I have tried to increase timeout up to 10 minutes without success

Finally I have installed Edge release 2.1.1.0 (37260) that actaully works.

However I don' think that my machine speed has anything to do with docker VM not starting inside Hyper-V because for both stable releases 2.1.0.1 and 2.0.0.3 looks like machine is stuck unresponsive and consumes a lot of CPU.

**Comment by mikeparker** [comment]
Sorry, no, I'm asking the original poster. I'm aware you're running nested virt which is unfortunately not officially supported.

**Comment by mikeparker** [comment]
> What is VMware vSphere?
> A server virtualization platform from VMware.

You are using nested virtualization, this is not a supported scenario. Please see docs: https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-desktop-for-windows-in-nested-virtualization-scenarios

> Docker Desktop is not supported in nested virtualization scenarios. It might work in some cases, and not in others.

**Comment by a5ync** [comment]
I can confirm that Docker Desktop Community 2.1.1.0 (edge) works for me on VMware. Thanks!

**Comment by jftuga** [comment]
I can also confirm that Docker Desktop 2.1.7.0 works on Windows 10 v1809 running on top of ESXi 6.7. I was able to run the *mcr.microsoft.com/windows/servercore:ltsc2019* image.

**Comment by devopswx** [comment]
> 
> 
> @mikeparker if you asking me than:
> 
> > Your machine is really slow. Are you running nested virtualization? i.e. Windows in a VM (e.g. on a mac)?
> 
>     * Yes I'm running Windows 10 pro on Mac notebook (i7, 16GB ram) using paralles
> 
>     * Yes Nested Virtualisation is enabled for W10 VM it doesn't work without it
> 
> 
> > Have you tried increasing the timeout in the settings file, as per the error message?
> 
>     * Yes I have tried to increase timeout up to 10 minutes without success
> 
> 
> Finally I have installed Edge release 2.1.1.0 (37260) that actaully works.
> 
> However I don' think that my machine speed has anything to do with docker VM not starting inside Hyper-V because for both stable releases 2.1.0.1 and 2.0.0.3 looks like machine is stuck unresponsive and consumes a lot of CPU.

**I can confirm this solution actually WORKS!**
A big thank you :)

**Platform:** 
 Windows 10 VM in a nested environment i.e inside  VMWare Workstation 15
AMD FX-8350 with 8GB RAM with 3 cores provided to the VM.
**Issue:** 
Docker desktop is failing to start with the error 'Timed out waiting for the lifecycle-server to start.
**Solution**: As suggested uninstalled the latest Docker Desktop Community 2.1.0.5
and Installed Docker Desktop for Windows Edge 2.1.1.0

**Comment by paweljasinski** [comment]
2.1.0.5 stable doesn't work
2.1.7.0 edge works
Platform:
Windows 10 18363 VM in VMWare Workstation 15

**Comment by jamesbluecrow** [comment]
> Mac Parallels 13.3.2, Windows 10 pro 1903 virtual machine
> 
> * Stable 2.1.0.1 doesn't work
> * Stable 2.0.0.3 doesn't work (as suggested here #4393)
> 
> Both versions have same issue virtual machine in Hyper-V consumes 50% host CPU and never gets ready to work.
> 
> * Changing VM settings in (more memory or more CPU-s ) doesn't have any effect.
> * Extending lifecycle timeout up to 600s doesn't have any effect
> 
> However latest Edge release:
> Docker Desktop Community 2.1.1.0 (37260) **works**, starts within 10s
> Also I have selected inside Edge version installation to install missing windows components not sure if this made difference or what exactly changes in Win.
> 
> I have disabled docker desktop auto start on OS startup, hate having apps running that I don't use so I can't confirm if starts within 10s when OS is starting.
> 
> Hope this helps.

Life saver, the latest edge version works, in my case it is 2.1.7.0

Thank you!

**Comment by Galphaa** [comment]
yeap on esxi 6.7u3  docker edge 2.1.7.0 is working
