### ISSUE TITLE
Getting `ln: failed to create symbolic link` during dockerized build

### ISSUE THREAD

**Issue by sanseihappa** [docker/for-win#46]
### Expected behavior
When I git clone my source repo
And I run the build of that source inside a container with local file system mounted
Then I expect that the build will work
### Actual behavior
The build is failing with
> `ln: failed to create symbolic link '../build/.config': Operation not supported`
### Information

  - 1157C837-2963-4A79-A337-A44A61FC8BEF/2016-08-18_15-43-43
  - Windows 10.0.14393

### Steps to reproduce the behavior

In powershell
  1. `git clone <blah>`
  2. `cd <blah>` (the `Dockerfile` lives at the top-level)
  3. `docker build --tag=<thing> --build-arg USER=${env:username} --build-arg UID=1000 .`
  4. `docker run -u ${env:username} -it -v ${pwd}:/mnt/work octane/fw:latest bash ./build.sh`

Not sure if it is relevant, but the reason for building the image and then running, and the reason for the build args is to handle permissions issues that typically occur when running on a Linux host (I'm attempting to enable Windows here).  There are corresponding statements in my `Dockerfile` like this:

```
# This is to avoid permissions issues with files created during the build
# It assumes the same user is building the image as is running it!
# We use the --gecos option because adduser prompts otherwise and leaves some messy stderr output
ARG USER
ARG UID
RUN adduser --disabled-password --gecos "First Last,RoomNumber,WorkPhone,HomePhone" --uid $UID $USER
```

**Comment by rneugeba** [comment]
@sanseihappa thanks for the report. Could you try Beta23 instead of the stable? We added some improvements to the beta for symlink handling. You can get the Beta23 here: https://download.docker.com/win/beta/InstallDocker.msi

Thanks
Rolf

**Comment by sanseihappa** [comment]
@rneugeba Yes! The Beta version is working for me and getting past that error!

**Comment by rneugeba** [comment]
@sanseihappa thanks for getting back (I seem to have missed the reply initially and only noticed it now). I'll close this issue.
