### ISSUE TITLE
fatal: failed to start daemon: Error initializing network controller: Error creating default network: hnsCall failed in Win32: Element not found. (0x490)

### ISSUE THREAD

**Issue by rajavan** [docker/for-win#4600]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by hinews** [comment]
I got the same issue on AWS Windows 1903 LTS with Docker Community 19.03.1
It's happened first time when I run "docker-compose up -d"

Creating network "userend-19-windows-dc__02-09-2019_16-55-43_shared" with the default driver
hnsCall failed in Win32: Element not found. (0x490)

But the second try resolved the issue.

**Comment by AlessandroBorges** [comment]
Same issue here.
Error message from Event Viewer:

fatal: failed to start daemon: Error initializing network controller: Error creating default network: hnsCall failed in Win32: Element not found. (0x490)

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place.
Thanks!
