### ISSUE TITLE
How to share disk silently in docker by powershell unattended input credentials

### ISSUE THREAD

**Issue by LauShawn** [docker/for-win#4603]
### Expected behavior
After install docker in win10, use powershell run the command below:
`docker run --rm -v c:/Users:/data alpine ls /data`
Can share c disk for linux container success silently.

### Actual behavior
A confirmation box and input box pop up, I need all run silently and unattended.
![image](https://user-images.githubusercontent.com/12406839/63845342-6e1deb80-c9bc-11e9-83d2-43cc6f491383.png)
![image](https://user-images.githubusercontent.com/12406839/63845719-fc926d00-c9bc-11e9-872d-0079a47ede9e.png)
Is there any method can solve the click and input(username/password) unattended? Thanks!

### Information

  - Windows Version: Windows 10 Enterprise
  - Docker Desktop Version: 2.1.0.1

### Steps to reproduce the behavior

  1. install docker in win10
  2. docker run --rm -v c:/Users:/data alpine ls /data

**Comment by LauShawn** [comment]
I solved it by using UIAutomation, hope this will help you if you encountered the same problem.

**Comment by J-XL** [comment]
Please share more details of the UIAutomation workaround
