### ISSUE TITLE
WSL2 tech preview extremely slow

### ISSUE THREAD

**Issue by ksawerykarwacki** [docker/for-win#4626]
I try to run Oracle Apex app, but everything works super slow. I cannot load App builder because my browser hangs loading site. Stopping of the container took 11 seconds. Tests cannot run because script that checks if DB is ready times out. 

Overall docker on wsl2 seems to work much slower than DockerDesktopVM

**Comment by temega** [comment]
I'm not familiar with the apps you're naming but I had similar issues with overall unacceptable WSL2 performance. The reason was that I was building huge projects (lot's of file so lots of watchers) in my `/mnt/` folder. Perhaps try setting up your projects in the home dir... `cd ~`

**Comment by ksawerykarwacki** [comment]
I haven't used any mounts or volumes. I know that Oracle DB is huge and APEX only adds overhead but I have no idea why it runs slower on wsl2 docker than on MobyVM. Is there any limitation to resources that docker on wsl2 can access? I tuned my MobyVM to have access to 4 cores and 12 GB of RAM but I would assume that from wsl2 docker should have access to everything (8 cores, 32 GB of RAM) and should run faster not slower.
