### ISSUE TITLE
Inability to pull windows/nanoserver

### ISSUE THREAD

**Issue by bcorcoranJMP** [docker/for-win#463]
### Expected behavior
docker pull windows/nanoserver succeeds

### Actual behavior
failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage C:\ProgramData\Docker\windowsfilte
r\4a7fcaefe91154b56d2068a0ef8d23d43f4b853decc66955e4ca5d4e25f625de\UtilityVM: The process cannot access the file because
 it is being used by another process.
### Information
87C74FDD-6D06-4304-A2ED-A2DFF675ED14/2017-02-03_11-19-33

Using Docker for Windows, with docker.exe and dockerd.exe 1.14.0-dev
OS is Windows 10 Enterprise Anniversary Edition 64-bit
Microsoft Windows Update KB3216755 installed
Symantec SEP 12.1.6 installed

### Steps to reproduce the behavior

  1. Install Docker for Windows Beta Version 1.13.1-rc1-beta40 (9961)
  2. Switch to Windows Containers
  3. Try to do a docker pull microsoft/nanoserver (fails)
  4. Try to unzip and copy in docker v 1.14.0 and restart machine
 5.  Try to do docker pull microsoft/nanoserver (still fails)

I know this issue has been mentioned before, but it seems to have gone stale and there was never an adequate resolution.  My understanding is that Symantec AV is interfering with docker's use of a temp directory.  Shutting off Symantec does nothing.  I cannot install SEP on a corporate machine.  Is anybody at Microsoft or Docker working on this?  Log attached.
[log.txt](https://github.com/docker/for-win/files/751171/log.txt)
[log.txt](https://github.com/docker/for-win/files/751173/log.txt)

**Comment by rneugeba** [comment]
The error in question seems to be:
```
[11:17:17.659][WindowsDockerDaemon][Info   ] time="2017-02-03T11:17:17.659418200-05:00" level=error msg="Error trying v2 registry: failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage C:\\ProgramData\\Docker\\windowsfilter\\4a7fcaefe91154b56d2068a0ef8d23d43f4b853decc66955e4ca5d4e25f625de\\UtilityVM: The process cannot access the file because it is being used by another process." 
[11:17:17.659][WindowsDockerDaemon][Info   ] time="2017-02-03T11:17:17.659418200-05:00" level=error msg="Attempting next endpoint for pull after error: failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage C:\\ProgramData\\Docker\\windowsfilter\\4a7fcaefe91154b56d2068a0ef8d23d43f4b853decc66955e4ca5d4e25f625de\\UtilityVM: The process cannot access the file because it is being used by another process." 
```

**Comment by rneugeba** [comment]
Can you install either Process Explorer or the `handle` utility from sysinternals and see which process uses the above files?

**Comment by bcorcoranJMP** [comment]
The directory mentioned does not even exist (guid that starts with 4a).  A subsequent pull attempt references a directory starting with a guid of dde4, but that does not exist either.  Running ProcessExplorer and searching for file handles in use in directory c:\ProgramData\Docker does not reveal anything.

I've rebooted several times, and the problem still exists.

**Comment by bcorcoranJMP** [comment]
I was able to get a pre-deployment copy of Symantec Endpoint 14.0.  Installing this and putting in the appropriate folder exceptions (program files\Docker, ProgramData\Docker) has fixed the problem.  This could be a pretty big issue for users that have AV software blocking use of temp files during a pull.

**Comment by rneugeba** [comment]
Thanks for getting back to us and glad it's working. I'll pass the above on
