### ISSUE TITLE
can't change disk image location

### ISSUE THREAD

**Issue by darkflame0** [docker/for-win#4641]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
change disk image location
### Actual behavior
![image](https://user-images.githubusercontent.com/22924199/64197875-b73cd680-ceb9-11e9-9240-b78d0ef899fc.png)
I can't change the path even if browse
### Information

  - Windows Version: windows10 1903 18970.1005
  - Docker Desktop Version:2.1.1.0(37260) edge

**Comment by ldario** [comment]
Are you using Hyper-V?  I had a similar issue, and used this [fix](https://github.com/docker/for-win/issues/2063#issuecomment-433069658) as a workaround.

**Comment by pauljmelia** [comment]
I'm experiencing the same issue:

- Windows Version: Windows 10 1903 19025.1
- Docker Desktop Version 2.1.6.0 (40740) edge

@ldario : I've tried the fix to no avail.
