### ISSUE TITLE
Can't use host docker daemon from container

### ISSUE THREAD

**Issue by GabrielBB** [docker/for-win#4642]
No matter what I and a co-worker try, we can't connect to the docker daemon in our Windows host. I check that the container has the `/var/run/docker.sock` file but we still get a "docker: command not found" when executing `docker exec -t ${container} docker ps`. We are not using a windows container.

This is how I'm running the container:

`docker run -d -p 49001:8080 -v "D:/container_volumes/jenkins":/var/jenkins_home:z -v /var/run/docker.sock:/var/run/docker.sock -t jenkins/jenkins`

I also tried with my personal computer. According to [this post](https://stackoverflow.com/questions/36765138/bind-to-docker-socket-on-windows) it should work.

OS: Windows 10 Pro
Docker Desktop version: 2.1.0.1 (37199)
Image: [jenkins/jenkins](https://hub.docker.com/r/jenkins/jenkins/)

**Comment by mccarthysean** [comment]
@GabrielBB, I created a [GitLab repo](https://gitlab.com/mccarthysean/develop-inside-linux-docker-container-on-windows-10-host) for you to clone and test, which connects a Linux Docker container (in which you can develop your code with VS Code) to your Windows Docker host. Hope it helps!

It requires Docker Desktop for Windows, VS Code, and the "Remote Development" extension for VS Code. 

I think you'll like it!
-Sean

**Comment by naamancampbell** [comment]
As per [this Container Solutions post](https://blog.container-solutions.com/running-docker-in-jenkins-in-docker), the Docker binary also needs to be mounted onto the Jenkins container.  The Docker binary is located in `/usr/local/bin/docker` on Windows Docker-Desktop.

`-v /usr/local/bin/docker:/usr/bin/docker` 

I also needed to add `--user root` to the `docker run` command to enable access to the Docker UNIX socket.

**Comment by GabrielBB** [comment]
@naamancampbell OMG Finally. "-v /usr/local/bin/docker:/usr/bin/docker" worked! For some reason everybody says that "/var/run/docker.sock:/var/run/docker.sock" should work on Windows too but it didn't.

**Comment by GabrielBB** [comment]
Documented in: https://stackoverflow.com/questions/36765138/bind-to-docker-socket-on-windows/58204900#58204900

**Comment by stringang** [comment]
Windows10:

```shell
docker run \
-v /var/run/docker.sock:/var/run/docker.sock
--user root
images:tag
```
solve this problem
