### ISSUE TITLE
Can't share drives in windows

### ISSUE THREAD

**Issue by paulgmiller** [docker/for-win#4651]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID: ED164D0D-6E2C-48A0-836B-0A4BD25397E1/20190904214908

### Expected behavior
Sharing drives works
### Actual behavior
Sharing drives is ignored with no error
### Information

  - Windows Version: windows 10 (1903)
  - Docker Desktop Version: 2.1.0.2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
Can't share drives: Check a drive. Prompts for password, Accepts password but then there is no error and drive is unshared. 

![image](https://user-images.githubusercontent.com/1474379/64295214-9f02a100-cf25-11e9-98db-db3719246073.png)

Similar to this. 
https://github.com/docker/for-win/issues/690#issuecomment-373017897

**Comment by joshlang** [comment]
Ditto

**Comment by LItterBoy-GB** [comment]
me too
[operate](https://youtu.be/IHvhv6c0M7c)

**Comment by Jacob-Tate** [comment]
See solution in #690

**Comment by rmNyro** [comment]
Same, here. Personally I just droped Docker for windows as it's unsuable right now (unless you have a disk operation free service).

**Comment by PoojaTrikha** [comment]
Even i have the same issue. To resolve it, I created a local account with Administrator rights. But still the issue persists. Following the thread to get the resolution.
