### ISSUE TITLE
can't share drive C:

### ISSUE THREAD

**Issue by acherner** [docker/for-win#4658]
Updated Windows 10 yesterday, updated Docker to latest,
can't share drive C: now.
Symptoms and steps to reproduce:

1. go to Docker settings, share C
2. user login popup appears, our Authentication is via AzureAD
3. entering credentials, popup closes but C still not shared

Tried the following as well after checking some suggestion on the web:
1. Shared manually drive C: via right click properties, drive is shared successfully
2. shared drive via Docker 
Result: C still not shared in Docker, manual share from C that was done in step 1 disappeared, no share on C now.
Please advise.

**Comment by acherner** [comment]
This guide worked for me as workaround:
https://tomssl.com/2018/01/11/sharing-your-c-drive-with-docker-for-windows-when-using-azure-active-directory-azuread-aad/amp/

**Comment by Glavic** [comment]
@acherner I have no azure account and have the same issue. I tried your solution, but still not working.

**Comment by smartmeta** [comment]
same issue
