### ISSUE TITLE
[CRASH] - Timeout after update to 2.1.0.2

### ISSUE THREAD

**Issue by gantispam** [docker/for-win#4659]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker Engine start

### Actual behavior
* Docker desktop work fine but after last updated 2.1.0.2 : 
  * Timeout on start Docker Desktop
  * You can found all logs : [log.txt](https://github.com/docker/for-win/files/3578162/log.txt)

* In logs we can found : 
  * ```write /var/lib/containerd/io.containerd.metadata.v1.bolt/meta.db: no space left on device```
  * So, i have 880Go space free..
  * ```[31merror[0m="unknown service containerd.services.containers.v1.Containers: not implemented"```
  * So? 

* On diagnostic tools we can found : 
* Stacktrace :
> Timed out waiting for the lifecycle-server to start.
> This may be the result of a slow environment or there may be a real problem.
> This timeout can be increased by editing settings.json, value 'lifecycleTimeoutSeconds'.
> This file is usually in C:\Users\(your username)\AppData\Roaming\Docker
> 
>    à Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
> --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
>    à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    à Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
>    à Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
>    à Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
>    à Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

* So, my computer config is : CPU I7-9700K + RAM 32Go 3000Mhz + SSD 

### Information

  - Windows Version:10-pro
  - Docker Desktop Version:2.1.02
  - VM : hyperV DockerDesktopVM

### Steps to reproduce the behavior
  1. update docker desktop to last version 2.1.02
  2. start docker desktop
  3. fail.. timeout (see logs attachment)

### Tempory fixe : 
  1. Uninstall docker for windows 2.1.0.2
  2. Remove all folders (see https://success.docker.com/article/how-to-completely-remove-docker-in-windows-10)
  3. Download and install docker for windows 2.1.01 (https://docs.docker.com/docker-for-windows/install/)

**Comment by mikeparker** [comment]
> This timeout can be increased by editing settings.json, value 'lifecycleTimeoutSeconds'

Did you increase the timeout?
