### ISSUE TITLE
"Access to the path 'Docker Desktop Installer.exe' is denied" during Update to 2.1.0.2

### ISSUE THREAD

**Issue by OscarVanL** [docker/for-win#4660]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
(I am not sure if these diagnostics will be particularly helpful, as the error left docker uninstalled and I had to reinstall it to gather the diagnostics

### Expected behavior

Docker has an update, the dialog telling me about the update to 2.1.0.2 shows up, I click 'Install Update' and the update begins to install. 

It should ask for elevated permissions through UAC if it does not have administrator access. If it fails or cannot get administrator access, it should revert to the previous state and not leave the docker application uninstalled.

### Actual behavior

Error dialog pops up during update stating `Access to the path 'Docker Desktop Installer.exe' is denied`, no request for elevated permissions through Windows UAC is prompted. Clicking 'OK' leaves the program uninstalled rather than reverting to the previous state before failure. 

I had to reinstall Docker from scratch after this, but every time I attempted to reinstall it said 
`The process cannot access the file 'C:\Program Files\Docker\Docker\Docker Desktop Installer.exe' because it is being used by another process.` This occurred until I rebooted, after which I could reinstall it as usual.

### Information

  - Is it reproducible? I am not sure.
  - Is the problem new? Yes
  - Did the problem appear with an update? Unsure, although I have done past updates without this issue.
  - Windows Version: Windows 10 Education 1903
  - Docker Desktop Version: 2.1.0.1
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. Click Install on dialog asking to update to 2.1.0.2
  2. Error message, leaving docker uninstalled.

**Comment by shooky-web-dev** [comment]
Same issue here, Docker failed to update and just disappeared. Attempts to download and install it again - fails.

**Comment by OscarVanL** [comment]
To follow on from this issue, after reinstalling I had [this issue](https://github.com/docker/docker-credential-helpers/issues/24), which was resolved by removing the JSON value "credsStore":"desktop" from C:\Users\----\.docker\config.json

**Comment by someniatko** [comment]
I installed 2.1.0.1 from scratch successfully without restarting Windows. However, yes, 2.1.0.2 installation is broken indeed.

**Comment by ProH4Ck** [comment]
Same problem with **Docker Desktop 2.1.2.0**

**Comment by withwind8** [comment]
Same problem when updating to 2.1.0.2.
Solved with moving C:\Program Files\Docker\Docker\Docker Desktop Installer.exe (which is the only file in that directory) to another directory and run it. After installation, version shows 2.1.0.1.
And then it auto check and update to 2.1.0.3 successfully.

**Comment by apo91** [comment]
Got the same issue today when updating to 2.1.0.3:
```
The process cannot access the file 'C:\Program Files\Docker\Docker\Docker Desktop Installer.exe' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at CommunityInstaller.RegisterProductStep.Register(String basePath, Manifest manifest, String manifestJson)
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackage>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()
```

**Comment by BoKKeR** [comment]
> To work around this issue I had to restart, move `Docker Desktop Installer.exe` file outside of the `Program Files` folder, run it, let it install 2.1.0.3, then run it, click agree to update request. After this it installs 2.1.0.4 properly.


This worked for me too
