### ISSUE TITLE
Windows Containers on Windows 10 Pro identifies themselves as "Microsoft" instead of the Full OS Name

### ISSUE THREAD

**Issue by mwheeler1982** [docker/for-win#4665]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [X ] I have uploaded Diagnostics
  - Diagnostics ID: C21939CC-0F86-407C-A239-C506F1A06B7F/20190905194138

### Expected behavior
Windows containers should identify themselves as the Full OS name, e.g. "Microsoft Windows 10 Pro" or "Microsoft Windows Server 2019"

### Actual behavior
When running Server Core containers, the "systeminfo" and "wmic os get name" commands run from within the containers, report themselves as only "Microsoft". I'm assuming the underlying Windows APIs that normally return this information are not reporting back correctly.

This only happens when the Host OS is Windows 10 Pro. Windows containers hosted on Windows Server (tested with Server 2019) report back correctly.

Using Process Isolation or Hyper-V isolation does not make a difference.

### Information

  - Windows Version: Windows 10 Pro 1903 (build 18362)
  - Docker Desktop Version: 2.1.0.2 (37877)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. docker run --rm mcr.microsoft.com/windows/servercore:1903 "systeminfo"
  2. or run "wmic os get name" from within a running container

**Comment by StefanScherer** [comment]
Thanks for reporting. But this is probably an issue in the underlying Windows base image.
The Docker Hub page https://hub.docker.com/_/microsoft-windows-servercore refers to the Microsoft forum https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowscontainers
Please report your request there.
I'll close this issue, but when you have created a forum question you can link it here for reference. Thanks.

**Comment by guhuajun** [comment]
@StefanScherer Maybe https://github.com/moby/moby/issues is another choice. We can ping someone from Microsoft directly. I was monitoring MSDN forum for some time, but not all the time.
