### ISSUE TITLE
Docker breaks Windows networking services when enabling Hyper-V on a non compatible processor

### ISSUE THREAD

**Issue by riahc3** [docker/for-win#467]
**Description**

Docker enabled Hyper-V on a non SLAT processor that is not compatible with Windows 10 1607 Hyper-V and it broke a lot of networking services (OpenVPN, Npcap, etc)

**Steps to reproduce the issue:**

Install OpenVPN and nmap on a processor without SLAT.
Install Docker
Docker will ask you if you want to enable Hyper-V. Say yes.
Docker gives a error but auto restarts any ways.
Weird networking starts.

**Describe the results you received:**
Nmap said it could not find the service it needed to sniff. OpenVPN could not use it's tap adapter... Other issues that used to work but now don't which I imagine are all related

**Describe the results you expected:**
The opposite.

**Additional information you deem important (e.g. issue happens only occasionally):**
Docker should autodetect the ability for the system to be compatible with itself and Hyper-V. I imagine it enables Hyper-V thru a Powershell command and NO.

**Output of docker version:**
Latest. Just downloaded it and tested to reproduce it.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I also had VMWare Workstation and VirtualBox to test that it affected the network stack and I confirm it does. They were installed BEFORE Docker.

**Comment by simonferquel** [comment]
Thanks for the feedback. @rneugeba should we check that SLAT / etc. is enabled prior to enable Hyper-V related features ?

**Comment by rneugeba** [comment]
SLAT/EPT was introduced by Intel with Nehalem in 2008 (quite a long time ago...). I'm surprised Windows does not check stuff like this before enabling Hyper-V. We could check for SLAT...

**Comment by simonferquel** [comment]
I think they don't check it because the extension can be enabled / disabled from BIOS settings even after the hv feature is installed.
