### ISSUE TITLE
Bugcheck terminal_server_driver_made_incorrect_memory_reference with process isolation

### ISSUE THREAD

**Issue by marcanpilami** [docker/for-win#4670]
- [x] I have tried with the latest version of my channel (Stable 2.1.0.2)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: cannot upload, since bugcheck, but dump available!

### Expected behavior
Container starts

### Actual behavior
Either :
* works
* freezes, then a `restart-service docker` causes a bugcheck terminal_server_driver_made_incorrect_memory_reference 
* directly causes bugcheck

### Information

  - Windows Version: 10 Pro 1809, KB4511553, 17763.678
  - Docker Desktop Version: 2.1.0.2 (was already failing with 2.1.0.1)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no. 

This was reproduced on multiple other computers.

### Steps to reproduce the behavior

  1. `docker run -it --rm --isolation=process mcr.microsoft.com/windows/nanoserver:1809 cmd /C set`
 
Does work with hyperv isolation.

**Comment by marcanpilami** [comment]
Additional info from event viewer (in French) : La vérification d’erreur était : 0x000000cf (0xffff9b047f0e1030, 0x0000000000000010, 0xffff9b047f0e1030, 0x0000000000000002). Un vidage a été enregistré dans : C:\windows\MEMORY.DMP. ID de rapport : 29876703-4557-411b-b2b9-4ec104579a86.

I can upload the dump at your prefered location if you need it.

**Comment by philipproplesch** [comment]
Any updates on this one? Running Docker Desktop v2.2.0.0 (also observed in v2.1.0.5) in a similar environment and experience the same BSOD described by @marcanpilami - same error code and everything.

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place?
