### ISSUE TITLE
Docker Desktop on Windows unable to switch to Edge

### ISSUE THREAD

**Issue by enriquegrodrigo** [docker/for-win#4672]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: EADD6820-A726-46B9-8880-962700B48AD4/20190906110137

### Expected behavior

I changed the channel to Edge. The application should have downloaded the new version and install it, changing docker version to 2.1.1.0.

### Actual behavior

The application downloads the version but docker desktop is killed. After starting again, the docker desktop application is not upgraded (it remains with the stable version 2.1.0.2)

### Information
  - Windows Version: Windows 10 Pro (1903)
  - Docker Desktop Version: 2.1.0.2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Change channel to Edge
  2. Wait for version download 
  3. Killed...

**Comment by Cossey** [comment]
This is also occurring on my desktop as well. I want to try out buildx but can't at the moment until this is fixed. Same version of Windows as O.P.

**Comment by maku** [comment]
Same situation for me... (running Win 10 Pro Insider Preview Build 18975.rs_prerelease.190830-1502)

**Comment by jjjjeeffff** [comment]
I got this working by going to https://docs.docker.com/docker-for-windows/edge-release-notes/ and downloading the 2nd latest version (2.1.3.0 currently). The latest version 404s there, but the previous installs and then prompts to update to 2.1.4.0, which then downloads successfully.

**Comment by maulerjan** [comment]
+1

**Comment by BenjaminAbt** [comment]
Same problem for me
Windows 10.0.18363.418
https://twitter.com/Abt_Benjamin/status/1207282459190218754

**Comment by emandere** [comment]
Another option to turn on experimental features is to go to the  Settings->Daemon and select Experimental and then restart. Once I did that I was able to access edge features like buildx
