### ISSUE TITLE
Docker Crashing after every system restarts

### ISSUE THREAD

**Issue by jibupcherian** [docker/for-win#4674]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: EA0806AE-A51B-4703-A794-3075F47BDFD6/20190906144246

### Expected behavior
I should not get an error when starting
### Actual behavior
![image](https://user-images.githubusercontent.com/46607141/64437027-19006a80-d08b-11e9-9533-a744e12e049a.png)

### Information

  - Windows Version: Windows 10 Pro
  - Docker Desktop Version: 2.1.0.2(37877) Stable
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No, Office Laptop

### Steps to reproduce the behavior

  1. Docker is crashing once after the system restarts
  2. ...

**Comment by NitinNextGen** [comment]
I am facing the same issue as above.
