### ISSUE TITLE
Error when switching to Windows Containers

### ISSUE THREAD

**Issue by joben** [docker/for-win#468]
### Expected behavior
Switch docker to use Windows Containers
### Actual behavior
Error during the switch. Docker Whale turns red.
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
2A8D0902-3D7C-41BF-ABE0-BA7E5CC4E130/2017-02-07_16-42-05
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)
Microsoft Windows [Version 10.0.14393]

### Steps to reproduce the behavior

  1. Right Click on Docker Whale icon in the system tray
  2. Click on "Switch to Windows Containers"
  3. Error Dialog Window appears.

**Comment by simonferquel** [comment]
Hi @joben 
From the logs, I see that it is a Windows Container Networking issue (something the Docker for Windows team is not responsible for).

Could you please submit this issue to https://github.com/docker/docker/issues ?

**Comment by rneugeba** [comment]
Closing this issue, assuming you have filed a new issue on docker/docker.
thanks
