### ISSUE TITLE
Docker fails to start: "Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input"

### ISSUE THREAD

**Issue by darrenkidd** [docker/for-win#4685]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `5DB6BA1D-0FF8-416B-AD09-3D381D9CEFC6/20190909101258`

### Expected behavior

Docker should start.

### Actual behavior

![image](https://user-images.githubusercontent.com/14284827/64523204-f3f04e00-d34f-11e9-87f3-d63714cc181d.png)

```
Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input.

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()
```

### Information

  - Windows Version: Windows 10 Pro @ 1903
  - Docker Desktop Version: 2.1.1.0 (37260)
  - Docker Desktop Channel: edge
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

![image](https://user-images.githubusercontent.com/14284827/64522948-56951a00-d34f-11e9-894d-49415e4d4f4d.png)

### Steps to reproduce the behavior

  1. Start Docker and wait... 🐳 ⌚️ 
  2. 💥

**Comment by darrenkidd** [comment]
Have tried disabling "Control Flow Guard" for `vmcompute`, restart service, reboot, everything. Nothing seems to help.

Had same issue with 2.1.0.1 as I commented [here](https://github.com/docker/for-win/issues/4595#issuecomment-526126980). Have upgraded to *edge* channel since then but hasn't helped.

**Comment by darrenkidd** [comment]
Disabled "Use strict CFG":

![image](https://user-images.githubusercontent.com/14284827/64525273-8f83bd80-d354-11e9-8c0a-fa17dd1f2b04.png)

Stopped and started `vmcompute`:

![image](https://user-images.githubusercontent.com/14284827/64525297-9ad6e900-d354-11e9-9528-7ce1cd06f2e8.png)

Got the same error - "Unable to create".

Cc: @jpl-jengelke #3597 

Does anyone know of a working (old) version that I could go back to?

**Comment by darrenkidd** [comment]
Have confirmed that the bump to the **2.1** series seems to have triggered this. Running Windows 10 Pro 1903 with **2.0.0.2-2.0.0.3** works fine.

**Comment by mikeparker** [comment]
I can see this coming through in our error tracking. The latest edge (2.1.2.0) outputs the powershell stack trace, any chance you could retry on edge and either upload the log or extract the powershell stack trace from it?

**Comment by mikeparker** [comment]
@darrenkidd perfect, thanks! We're looking at it.

**Comment by zappy-shu** [comment]
@darrenkidd apologies for the delay. It looks like there might be something wrong with the DockerNAT virtual network adapter. Please could you run the following in powershell and post the results.

`Import-Module Hyper-V; Get-NetAdapter | Where-Object { $_.DeviceID -eq (Get-VMNetworkAdapter -ManagementOS -SwitchName DockerNAT).DeviceId } | Format-List`

You can try removing the DockerNAT switch. Open the Hyper-V Manager -> Virtual Switch Manager, select DockerNAT and click Remove

**Comment by jpl-jengelke** [comment]
> Disabled "Use strict CFG":
> 
...
> 
> Stopped and started `vmcompute`:
> 
...
> 
> Got the same error - "Unable to create".
> 
> Cc: @jpl-jengelke #3597
> 
> Does anyone know of a working (old) version that I could go back to?

Please get @zappy-shu the net adapter info. I would also respectfully suggest attempting to completely disable Control Flow Guard (CFG).

**Comment by darrenkidd** [comment]
Thanks for investigating @zappy-shu! And apologies for the delay on my end.

> It looks like there might be something wrong with the DockerNAT virtual network adapter.

I would agree! But I'm no longer sure this is being triggered just in **2.1.x.x**. I think there might be issues around this adapter that go back further.

While I've been waiting, I've been using **2.0.0.3** (Stable) as that version starts fine on my machine (as noted above). However, when I try to share my C: drive via Settings it fails (after entering correct credentials) with the "firewall detected" dialog (see image below). The correct firewall rules are present and active, All the other suggested troubleshooting steps don't help. The DockerNAT virtual switch exists _inside_ Hyper-V, but there's no vEthernet adapter for it in Windows. (In contrast, the "Default Switch" virtual switch in Hyper-V _does_ have a vEthernet adapter.)

e.g.

![Firewall detected dialog](https://success.docker.com/api/images/.%2Ferror-a-firewall-is-blocking-file-sharing-between-windows-and-the-containers%2Fimages%2Fimage.png)

Not sure if they are related, but this missing DockerNAT adapter sure seems suspicious.

I've now uninstalled that **2.0.0.3**, rebooted, and installed **2.1.3.0** (latest Edge). This also fails to start, but the error message is slightly different:

```
Unable to create Hyper-V VM: The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input.
at Set-IPAddress, <No file>: line 290
at Set-SwitchIPAddress, <No file>: line 320
at New-MobyLinuxSwitch, <No file>: line 260
at New-MobyLinux, <No file>: line 176
at <ScriptBlock>, <No file>: line 800
at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
```

**Diagnostic ID:** `5DB6BA1D-0FF8-416B-AD09-3D381D9CEFC6/20190923104342`

As expected, no VMs created in Hyper-V but the DockerNAT virtual switch exists there. However, no vEthernet adapter for DockerNAT exists; here's the output of your Powershell script:

![image](https://user-images.githubusercontent.com/14284827/65420021-376cb100-de54-11e9-8d63-fd472815b917.png)

So nothing listed. I see the same when eye-balling the network adapters.

Here's DockerNAT in Hyper-V:

![image](https://user-images.githubusercontent.com/14284827/65420371-1789bd00-de55-11e9-8218-df94acbdc158.png)

I hope that helps - let me know if there's other troubleshooting I can perform.

**Comment by darrenkidd** [comment]
Hey @zappy-shu, at work now so will have to run the PS tonight at home.

> This sounds like there may be an upgrade path issue. To confirm, this started when you upgraded from v2.0.0.3 to v2.1.1.0?

Not quite. I installed Docker on my Windows laptop for the first time about two months ago; I think it was a 2.1.x.y (Stable). Docker was starting fine then.

I then upgraded Windows to 1809 and then 1903, and Docker stopped starting. I think I may have taken a new minor version of Docker at some point in there as well. Nothing helped. I have no idea if the network adapter was around, then.

I then uninstalled and installed various other versions until I spotted that 2.0.0.2 and 2.0.0.3 worked. So I just started using them. Since then - and because of troubleshooting steps above - I've uninstalled those and installed various Edge and Stable flavours for testing. So I have no idea how much is going wrong each time I swap versions. But the ultimate trigger is potentially something introduced in the latest Windows release i.e. Control Flow Guard as many others have suggested.

At this stage I'm not in a position to reinstall Windows but happy to try other troubleshooting steps if needed.

**Comment by darrenkidd** [comment]
Here's the output @zappy-shu (running as Administrator):

```powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\WINDOWS\system32> Import-Module Hyper-V
PS C:\WINDOWS\system32> $vmNetAdapter = Get-VMNetworkAdapter -ManagementOS -SwitchName DockerNAT
PS C:\WINDOWS\system32>
PS C:\WINDOWS\system32> if ($vmNetAdapter) {
>>     $networkAdapter = Get-NetAdapter | Where-Object { $_.DeviceID -eq $vmNetAdapter.DeviceId }
>>     $networkAdapter | Remove-NetIPAddress -Confirm:$false
>> }
PS C:\WINDOWS\system32>
PS C:\WINDOWS\system32> Remove-VMSwitch DockerNAT -Force
Remove-VMSwitch : Failed while removing virtual Ethernet switch.
Internal miniport delete failed, internal NIC = '{05BF5D3C-4682-4953-9C75-3A149B8CD126}': Invalid parameter
(0x80041008).
At line:1 char:1
+ Remove-VMSwitch DockerNAT -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-VMSwitch], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.RemoveVMSwitch

PS C:\WINDOWS\system32> Import-Module Hyper-V; Get-VMSwitch DockerNAT | Format-List


Name                                             : DockerNAT
Id                                               : f6fc9ac0-888a-4ec0-9be2-0b00d6efaecf
Notes                                            :
Extensions                                       : {}
BandwidthReservationMode                         : Absolute
PacketDirectEnabled                              : False
EmbeddedTeamingEnabled                           : False
IovEnabled                                       : False
SwitchType                                       : Internal
AllowManagementOS                                : True
NetAdapterInterfaceDescription                   :
NetAdapterInterfaceDescriptions                  :
NetAdapterInterfaceGuid                          :
IovSupport                                       : False
IovSupportReasons                                :
AvailableIPSecSA                                 : 0
NumberIPSecSAAllocated                           : 0
AvailableVMQueues                                : 0
NumberVmqAllocated                               : 0
IovQueuePairCount                                : 0
IovQueuePairsInUse                               : 0
IovVirtualFunctionCount                          : 0
IovVirtualFunctionsInUse                         : 0
PacketDirectInUse                                : False
DefaultQueueVrssEnabledRequested                 : True
DefaultQueueVrssEnabled                          : False
DefaultQueueVmmqEnabledRequested                 : True
DefaultQueueVmmqEnabled                          : False
DefaultQueueVrssMaxQueuePairsRequested           : 16
DefaultQueueVrssMaxQueuePairs                    : 0
DefaultQueueVrssMinQueuePairsRequested           : 1
DefaultQueueVrssMinQueuePairs                    : 0
DefaultQueueVrssQueueSchedulingModeRequested     : StaticVrss
DefaultQueueVrssQueueSchedulingMode              : Dynamic
DefaultQueueVrssExcludePrimaryProcessorRequested : False
DefaultQueueVrssExcludePrimaryProcessor          : False
SoftwareRscEnabled                               : False
BandwidthPercentage                              : 0
DefaultFlowMinimumBandwidthAbsolute              : 0
DefaultFlowMinimumBandwidthWeight                : 0
CimSession                                       : CimSession: .
ComputerName                                     : XXXX-YYYY <-- redacted
IsDeleted                                        : False
DefaultQueueVmmqQueuePairs                       : 0
DefaultQueueVmmqQueuePairsRequested              : 16
```

HTH!

**Comment by zappy-shu** [comment]
@darrenkidd thanks for the info. I suspect the Windows update has somehow managed to break the VM switch though I can't think how.

I suggest, if you can, uninstalling Docker Desktop then uninstall/reinstalling the Hyper-V Windows Feature before re-installing Docker Desktop. This will hopefully remove the bad switch.

**Comment by darrenkidd** [comment]
Hey @zappy-shu, have done the following:

1. Uninstalled (working) **2.0.0.3**.
1. Removed Hyper-V from Windows Features. Restarted.
1. Confirmed Hyper-V not installed.
![image](https://user-images.githubusercontent.com/14284827/65831123-7b5b2c80-e312-11e9-8d5a-2c048218aa62.png)
1. Confirmed Docker not installed.
1. Confirmed no DockerNAT vEthernet adapter. Disabled the two existing vEthernet adapters.
![image](https://user-images.githubusercontent.com/14284827/65831128-9fb70900-e312-11e9-8062-15750ab2e3b7.png)
1. Installed Docker **2.1.3.0** from Edge.
![image](https://user-images.githubusercontent.com/14284827/65831134-b78e8d00-e312-11e9-8bc7-205df0416190.png)
1. Restarted.
![image](https://user-images.githubusercontent.com/14284827/65831137-bfe6c800-e312-11e9-9a68-fc2bd0210529.png)
1. Killed Docker before it started up after login.
1. Confirmed virtual switch exists via Hyper-V management.
![image](https://user-images.githubusercontent.com/14284827/65831145-e0168700-e312-11e9-864a-f1d5a016c4b0.png)
1. Confirmed no DockerNAT vEthernet adapter.
1. Started Docker. Got same error:
```Unable to create Hyper-V VM: The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input.
at Set-IPAddress, <No file>: line 290
at Set-SwitchIPAddress, <No file>: line 320
at New-MobyLinuxSwitch, <No file>: line 260
at New-MobyLinux, <No file>: line 176
at <ScriptBlock>, <No file>: line 800```
1. Confirmed no VM in Hyper-V and no DockerNAT vEthernet adapter.

So I would agree that something in the Windows Update has killed the ability for Docker to create the VM and adapter(s). There's been a lot of talk about the Strict Control Flow Guard stuff, but since I've disabled that and experienced the same problem before I think it might be _related_ but not the direct _culprit_.

However, as I've got a working version 2.0.0.3 on the exact same Windows install there's clearly a regression somewhere in the 2.1.x.x Docker line. It would be interesting to see if the others in GH with the same/similar issue have seen the adapter go missing as well, or if the root cause is deeper than that. I'm totally willing to do more troubleshooting as required, and can upload diagnostics from newer Edge builds that collect more info.

**Comment by gyokutoku** [comment]
Just the same problem.
In my case I have ever recovered it by restart the Windows, but does not work any more since yesterday.
And I think the other issues titled "Unable to create - 已停止该运行的命令，因为首选项变量“ErrorActionPreference”或通用参数设置为 Stop: 找不到元素。" 
or "Unable to create - ユーザー設定変数 "ErrorActionPreference" または共通パラメーターが Stop に設定されているため、実行中のコマンドが停止しました。仮想マシンの作成に失敗しました。" are saying the same thing. It seems to be a common problem.

**Comment by mkwong04** [comment]
I encountered similar issue but managed to get it resolved by manually remove the DockerNAT virtual switch entry from windows 10 registry.

For my case, i follow the darrenkidd's steps and not able to resolve, then i look further into the log, found it attempt to use existing DockerNAT and failed when attempt to create something. 

I tried manually remove the DockerNAT switch from Hyper-V manager UI so to force docker to auto create a new one, but hitting some invalid parameter error. Then i found a suggestion on remove via registry manually (https://superuser.com/questions/1192492/how-to-remove-a-hyper-v-virtual-ethernet-switch)

Remember to backup registry before make the changes

look under the registry path below for entries, click on the entries you will find an attribute named "FriendlyName"
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\VMSMP\Parameters\SwitchList 

look for one that having value of "DockerNAT" and remove it. restart the computer. Newly installed docker able to start properly.

Hope this help.

**Comment by darrenkidd** [comment]
Thanks @mkwong04 for those details.

I tried using some of the clean-up PowerShell commands [here](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/configure-docker-daemon#clean-up-docker-data-and-system-components) to kill the dodgy virtual switch but that didn't work. I can't remember where I got the instructions from.

I think I did have a look at the registry briefly, but for whatever reason (I don't remember) I chickened out of removing it that way.

In the end I had to wipe my machine and reinstall Windows 10. Docker has been working fine since then, but it was a bit disappointing that I had to resort to that.

I'll close this issue off because I can't replicate nor help debug it anymore.

**Comment by kimzeevaarders** [comment]
> I encountered similar issue but managed to get it resolved by manually remove the DockerNAT virtual switch entry from windows 10 registry.
> 
> For my case, i follow the darrenkidd's steps and not able to resolve, then i look further into the log, found it attempt to use existing DockerNAT and failed when attempt to create something.
> 
> I tried manually remove the DockerNAT switch from Hyper-V manager UI so to force docker to auto create a new one, but hitting some invalid parameter error. Then i found a suggestion on remove via registry manually (https://superuser.com/questions/1192492/how-to-remove-a-hyper-v-virtual-ethernet-switch)
> 
> Remember to backup registry before make the changes
> 
> look under the registry path below for entries, click on the entries you will find an attribute named "FriendlyName"
> HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\VMSMP\Parameters\SwitchList
> 
> look for one that having value of "DockerNAT" and remove it. restart the computer. Newly installed docker able to start properly.
> 
> Hope this help.

The deletion of the registry item as you described worked perfectly for me after experiencing the same error (deinstall of hyperv/dockerdesktop didn't work for me). Thx!
