### ISSUE TITLE
Duplicate virtual hard disk using space

### ISSUE THREAD

**Issue by cdalexndr** [docker/for-win#4686]
Currently I have two identical virtual hard disks taking space on my PC:
```
C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx(13.956.546.560 bytes)
C:\Users\All Users\DockerDesktop\vm-data\DockerDesktop.vhdx(13.956.546.560 bytes)
```
Inspecting Hyper-V manager, the one in use is from "ProgramData".
I've done recently an upgrade to docker desktop, which I suspect is the reason for the duplication. If this is the case, docker installer should clean old virtual hard disk after moving it.

Docker desktop version 2.1.0.2 (37877).

**Comment by cdalexndr** [comment]
In addition, both `service.txt` files from parent DockerDesktop folder from both location have the **same content**(diffed using kdiff3), and timestamp:
`Started on: 2019/09/09 13:33:11.349`
It seems the service is using both locations. What is the reason for this duplication?

**Comment by cdalexndr** [comment]
Diagnostics ID: E631F14E-8B3C-46B7-82F8-B975F82EAAD7/20190926100335
After trying to reduce disk image size (disk image recreated) I still have two identical disk images of 102MB.

**Comment by vladimir-poleh** [comment]
There is no any duplication. ```C:\Users\All Users\``` is a link to the ```C:\ProgramData\```. Physically these files are stored once in the ```C:\ProgramData\```.

**Comment by cdalexndr** [comment]
Indeed, was using [Space Monger 1.4.0](http://www.aplusfreeware.com/categories/LFWV/SpaceMonger.html) to find used space and it seems it doesn't handle links.
