### ISSUE TITLE
After upgrading to the lastest version the Kubernetes wont start any more. 

### ISSUE THREAD

**Issue by gkfischer** [docker/for-win#4687]
- [x ] I have tried with the latest version of my channel (Stable)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: F54280B9-ABC2-42C5-ABC5-D75420E81F18/20190910073712

### Expected behavior
Kubernetes starting after Desktop started
### Actual behavior
Kubernetes is starting is shown for ever
### Information

  - Windows Version: Windows 10
  - Docker Desktop Version: 2.1.0.2 (37877)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior
Upgrade to latest version

**Comment by nsinitsin** [comment]
I have the same problem. Diagnostic ID: 8472C14D-D5F0-48E6-AC0B-47012DB96523/20190913085747

**Comment by fidgi** [comment]
same issue. Diagnostic ID: 49FFB5DA-B7F5-4C01-B847-42626BA0CE47/20190914162418
