### ISSUE TITLE
Windows 10 Enterprise with Proxy: Error response from daemon: Get https://registry-1.docker.io/v2/: EOF

### ISSUE THREAD

**Issue by glungu** [docker/for-win#4692]
- [x] I have tried with the latest version of my channel (Stable 2.1.0.1)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B5C7051C-DD69-4DDC-8FED-67A294F4AC27/20190910092935

### Expected behavior
Below commands should work without errors:
```docker login```
```docker pull hello-world```

### Actual behavior
```
C:\>docker login
Authenticating with existing credentials...
Login did not succeed, error: Error response from daemon: Get https://registry-1.docker.io/v2/: EOF
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username (xxx):
Password:
Error response from daemon: Get https://registry-1.docker.io/v2/: EOF
```
```
C:\>docker pull hello-world
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: EOF
```

Please notice also that the following command works (run on Windows from Git Bash console). The proxy root certificate is installed on Windows, I have to provide path here because Git Bash uses separate location for trusted certificates:
```
$ curl --cacert <path_proxy_root_cert> https://registry-1.docker.io/v2/
```
It returns 401 Unauthorized, but the request gets through to docker hub repository alright:
```
< HTTP/1.1 401 Unauthorized
...
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}
```

### Information
The problem is reproducible, uninstalled and re-installed several times. (Tried some things that people suggest on the internet, but they just don't work for me, like setting http_proxy and https_proxy env vars in lowercase, setting DNS Server to 8.8.8.8, etc.)

  - Windows Version: Win 10 Enterprise
  - Docker Desktop Version: 2.1.0.1 (37199) Stable
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Install Docker Desktop for Windows
  2. Configure Proxy in Settings
  3. Set DNS Server to 8.8.8.8 in Settings (this step is not necessary, result is the same either way)

**Comment by vrana116** [comment]
I am also facing same issue. Any suggestion.

**Comment by bharath324** [comment]
I am facing this issue.

**Docker Desktop : Docker version 19.03.5, build 633a0ea
Windows 10 Pro,Version	10.0.18362 Build 18362**

I ran simple commands
**Login succeeded:**
```
C:\WINDOWS\system32>docker login
Authenticating with existing credentials...
Login Succeeded

```
_However_, **docker run failed: with EOF**:
```
C:\WINDOWS\system32>docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
docker: Get https://registry-1.docker.io/v2/library/hello-world/manifests/sha256:92c7f9c92844bbbb5d0a101b22f7c2a7949e40f8ea90c8b3bc396879d95e899a: EOF.
See 'docker run --help'.
```
