### ISSUE TITLE
Unable to stop - 已停止该运行的命令，因为首选项变量“ErrorActionPreference”或通用参数设置为 Stop: 由于以下错误无法启动服务“Hyper-V 主机计算服务 (vmcompute)”: 无法启动计算机“.”上的服务 vmcompute。

### ISSUE THREAD

**Issue by kobe24o** [docker/for-win#4702]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:DB168071-8AFC-4010-B5FA-1DDFC405870F/20190912004058

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  Unable to stop - 已停止该运行的命令，因为首选项变量“ErrorActionPreference”或通用参数设置为 Stop: 由于以下错误无法启动服务“Hyper-V 主机计算服务 (vmcompute)”: 无法启动计算机“.”上的服务 vmcompute。

   在 Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   在 Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   在 Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   在 Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

**Comment by Spike-Wang** [comment]
请问你是如何解决的，一样的问题

**Comment by zijianyue** [comment]
同问，一样的问题

**Comment by kobe24o** [comment]
我也不是太懂，小白


|                               |
陈明明
|
|
mingmingchen1989@163.com
|
签名由网易邮箱大师定制
在2019年11月12日 12:03，Ge Zijian<notifications@github.com> 写道：

同问，一样的问题

**Comment by snoopylovefiona** [comment]
右下角的工具栏，找到docker的图标，单机，然后有个【switch to windows containers...】，单机然后切换就可以了，应该是默认了Linux的container
