### ISSUE TITLE
Docker won't start

### ISSUE THREAD

**Issue by MrMaik** [docker/for-win#4707]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID:4001063F-45D1-4D50-A0CD-58F146B6BE80/20190912112133

### Expected behavior
Docker starts
### Actual behavior
Docker shows "An error occurred"

Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Creating the virtual machine failed.

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()
### Information

  - Windows Version:
Windows 10 Pro Version 1803 installed on 02-05-2018 OS build 17134.950
  - Docker Desktop Version:
2.1.0.2 (37877)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
No

### Steps to reproduce the behavior

  1. Try to start Docker Desktop
  2. Wait for the error to show up

**Comment by montao** [comment]
If you use Hyper-V please open Hyper-V and check if your Docker VM is alright. If the Docker VM is not started then you might encounter the problem you experience. You might need to restore or remove some VM if you happened to create a VM which gets stuck and then it could block the Docker VM in Hyper-V.

**Comment by mikeparker** [comment]
Can you try restarting the Hyper-V Virtual Machine Management service? This worked here https://github.com/docker/for-win/issues/4668#issuecomment-533173071

**Comment by MrMaik** [comment]
this worked, i've also moved the storage of the virtual disks and virtual machines
and I haven't had the problem since
