### ISSUE TITLE
Shared drive broken when switching networks

### ISSUE THREAD

**Issue by dazhao-msft** [docker/for-win#471]
This is a customer issue reported by a VS user. The original comment is at https://developercommunity.visualstudio.com/content/problem/16774/docker-error-when-running-aspnet-core-11-web-app.html.

Here is his original comment:

_I reported the incorrect version # in the .yml file and have been told it will be fixed in the next RC update. I also have a problem every time I move between networks. Fox example, everything will work perfectly while I'm at work, then I go home and it's broken. I fix it there and it works until I go back to work.
Open Settings in Docker and restore to factory defaults. Then reshare your drive(s). This fixes it for me. I assume it has to do with Linux and Windows communicating via network. 
, 
Here is another thing I've had to do lately. It seems to happen when I change networks. When I'm at work, it's fine. When I move to my home network or at another office, I have to do this, then it's fine until I move back to the office or to another network. I imagine it's got to do with Linux and Windows communicating via the network.
Open up Settings in Docker. Reset to factory defaults. Re-share your drive(s). For me, the incorrect .yml file (which I submitted as a bug and have been told is fixed for the next release) and the Docer reset are the only remaining issues._

**Comment by simonferquel** [comment]
Thanks for the report.

Just unsharing - re-sharing the drive should work imo. There seem to have 2 parts for this issue:
- The Firewall thing (making sure port 445 on the host is reachable from the Linux VM) -> we fixed that by creating a firewall rule that allows port 445 to be reached on the internal HV network endpoint from (and only from) the Linux VM IP
- The Samba server service enabling/disabling for a given network profile. 
-> this one is more complicated: I can't find any api that ensures SMB server is enabled without opening the firewall to any client. So for now we don't do this systematically (but re-creating the network share seem to do that anyway...).
