### ISSUE TITLE
Download link is broken - just takes me to docker hub

### ISSUE THREAD

**Issue by trondhindenes** [docker/for-win#4713]
There's no (easy to spot) way to download docker for desktop. I'm just taken to Docker hub, and there's no link from there to somewhere I can actually download it.

nav: https://www.docker.com/products/docker-desktop --> https://hub.docker.com/ --> ?

**Comment by stephen-turner** [comment]
Thanks, the link seems to have got broken. Reporting it to our website team.

**Comment by StefanScherer** [comment]
You probably want one of these
https://hub.docker.com/editions/community/docker-ce-desktop-windows
https://hub.docker.com/editions/community/docker-ce-desktop-mac
