### ISSUE TITLE
Cannot pull images or containers from docker

### ISSUE THREAD

**Issue by Richard-gallegos** [docker/for-win#4715]
" C:\Users\Richard>docker pull mcr.microsoft.com/windows/nanoserver:1903
error during connect: Post https://192.168.99.101:2376/v1.40/images/create?fromImage=mcr.microsoft.com%2Fwindows%2Fnanoserver&tag=1903: dial tcp 192.168.99.101:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

C:\Users\Richard>docker run hello-world
docker: error during connect: Post https://192.168.99.101:2376/v1.40/containers/create: dial tcp 192.168.99.101:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
See 'docker run --help'. "

Not sure why it is but I have run into this issue quite a few times this past week and the fact that I can't even pull/run the simplest of containers like hello-world is alarming.

I am running Windows 10 Enterprise with Hyper-V and virtualization enabled in my BIOS.

I have uninstalled and reinstalled Docker for Windows and have reset my machine several times, but I cannot seem to get past this issue.  Anyone else having this type of problem?

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker to pull the designated container/image

### Actual behavior
Docker fails to connect and thereby fails to pull the designated container/image

### Information

  - Windows Version: 10 Enterprise
  - Docker Desktop Version: 2.1.0.1
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

**Comment by youwalther65** [comment]
I run into similiar issues during the last days. Have a look at DOCKER related environment variables, unset them and restart Docker. Sometimes it helps. Still researchng this
