### ISSUE TITLE
Does not respect 'Max Disk Image size' setting

### ISSUE THREAD

**Issue by MythreyaK** [docker/for-win#4725]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 0A0752D5-AD92-4089-AB85-DCB9FAF4D599/20190915180940

### Information
  - Windows Version: 1809
  - Docker Desktop Version: 2.1.0.2
  - Running on a Laptop
### Steps to reproduce the behavior
  1. Switch to Linux container mode (NOT LCOW)
  2. Open settings and reduce disk image size to, say 10GB
  3. After restart, observe the settings page reverting to ~50GB  (in my case)  

Applying the setting:

![image](https://user-images.githubusercontent.com/26112391/64925760-16cca780-d813-11e9-822a-dd99964d3fd7.png)

After Docker restart: 

![image](https://user-images.githubusercontent.com/26112391/64925733-ce14ee80-d812-11e9-924a-7835519cf477.png)

**Comment by jbroutier** [comment]
Same here

Docker version: 2.1.0.3
Windows version: 1903

**Comment by Maxiride** [comment]
/remove-lifecycle stale

The issue is still present and no workaround has been proposed nor here nor in the duplicate issues reported.

**Comment by mat007** [comment]
Have you tried with the latest Edge? I just tested and this seems to work fine.
See https://docs.docker.com/docker-for-windows/edge-release-notes

**Comment by Maxiride** [comment]
@mat007 
I've installed the latest edge version (2.1.7.0) and the issue, for me, it is solved. I can resize the disk image without issues and I don't receive any alert about losing containers data (new feature I didn't read about?)

**Comment by mat007** [comment]
> Resizing did erase everything, even the images I had without any alert. I'd have expected that actually.

Indeed good catch, I think the old UI used to do this and this was forgotten in the new UI overhaul.
I have added an internal story ticket for this, thanks!

**Comment by MythreyaK** [comment]
Issue seems to persist.

Docker version: 2.2.0.0 (42247)
Docker engine: 19.03.5
Commit: 633a0ea

![1](https://user-images.githubusercontent.com/26112391/75992038-64ea7a00-5f1d-11ea-8241-67675f40e926.png)
![2](https://user-images.githubusercontent.com/26112391/75992051-67e56a80-5f1d-11ea-8525-0aed6a634ac9.png)

P.S. Please let me copy version strings from the `About Docker Desktop` setting :)
