### ISSUE TITLE
Stop using the system tray as the app entrypoint

### ISSUE THREAD

**Issue by trondhindenes** [docker/for-win#4727]
This might be a personal preference, but I strongly dislike some apps' tendency to use the system tray as the app entry point. The system tray is bloated, and just consumes valuable space. It would be MUCH better if Docker Desktop used a regular start menu app. 

Sure, use the system tray as a "lightweight" indicator of whether or not the Docker daemon is running etc, but move the app itself to a regular start-menu app.

**Comment by sc0ttwad3** [comment]
+1

**Comment by mwsluis** [comment]
+1 the right click menu is just really frustrating to use sometimes.
