### ISSUE TITLE
"Install Docker Desktop on Windows" does not work - cannot download docker for windows on a linux computer

### ISSUE THREAD

**Issue by philipreimer** [docker/for-win#4729]
### Expected behavior
Clicking "Download Docker" should start downloading Docker Desktop for Windows installer

### Actual behavior
Clicking "Download Docker" redirects back to https://docs.docker.com/install/
No download ist started.

### Information

I am trying to download the windows version of Docker Desktop using Firefox 69.0 on Manjaro Linux. I want to install Docker Desktop on a Windows System, of course.

### Steps to reproduce the behavior

1. Go to https://docs.docker.com/docker-for-windows/install/ using Firefox on Linux
2. Click "Download from Docker Hub" -> get redirected to https://hub.docker.com/?overlay=onboarding
3. Click "Download Docker" button

**Comment by lerignoux** [comment]
same behavior on chromium

**Comment by philipreimer** [comment]
Seems to have been fixed. I get redirected to docker hub now and can download the windows installer.

**Comment by mat007** [comment]
Thanks @philipreimer, I’ll go ahead and close this ticket now then.
