### ISSUE TITLE
WSL 2 Tech Preview Not Working with 2.1.3.0 (38275)

### ISSUE THREAD

**Issue by AdamVig** [docker/for-win#4734]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `985E6BD3-C397-4913-9BA3-F37750C50956/20190917013723`

### Expected behavior
WSL 2 Tech Preview starts.

### Actual behavior
WSL 2 Tech Preview does not start. Instead, the window says "Loading..." on the Status tab and none of the sections under the "Logs" tab display anything. The problem persists after a Docker restart, a system restart, and a Docker reinstall.

The WSL 2 Tech Preview was working before. I updated to the latest Docker Edge version today then encountered this problem.

For what it's worth, I found that I am no longer able to close Docker windows with the "x" button in the top right. Instead, I have to right click the title bar and select "Close" from the context menu.

### Information

  - Windows Version: Windows 10 Pro 1903
  - Docker Desktop Version: 2.1.3.0 (38275)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. Install and run Docker Desktop Edge.
  2. Click the icon then select "WSL 2 Tech Preview."

**Comment by AdamVig** [comment]
Workaround: downgrade from 2.1.3.0 to 2.1.2.0. Installers are available [here](https://docs.docker.com/docker-for-windows/edge-release-notes/).

Verified that the WSL 2 Tech Preview works when I uninstall 2.1.3.0 and installed 2.1.2.0 instead.

**Comment by sc0ttwad3** [comment]
I encountered the identical problem and had to downgrade to fix it. Selecting __WSL 2 Tech Preview__ in 2.1.3.0 seems to be missing the __WSL 2 Tech Preview__ features.  

Here's 2.1.3.0:

![WSL2-engine-v2 1 3 0-Stopped](https://user-images.githubusercontent.com/1682691/65011117-50b7af80-d8e0-11e9-8516-a4cf5bd759c3.png)

Compared with 2.1.2.0:

![WSL2-engine-v2 1 0 0-Running](https://user-images.githubusercontent.com/1682691/65011136-64631600-d8e0-11e9-8460-90506030d728.png)

**Comment by JohnCrist1988** [comment]
Also experienced the same issue. Nothing to add that wasn't already stated before. Downgrading also allowed me to use WSL2 once again with Docker.

**Comment by simon-ibars-cko** [comment]
Hi, I also experienced the same issue as described by sc0ttwad3 and his screenshots . I do have the same configuration as stated by JohnCrist1988 and AdamVig however my Windows OS Version is slightly different = **18980.1**

**Comment by rfay** [comment]
Sorry for a question that I should know... but doesn't uninstalling destroy everything already in docker's world, all containers, volumes, etc? I note that I can't downgrade easily... installing 2.1.2.0 after just *exiting* 2.1.3.0 results in the installer saying "Existing installation is up to date".

**Comment by sungyongcho** [comment]
hi.

**Comment by sungyongcho** [comment]
> Sorry for a question that I should know... but doesn't uninstalling destroy everything already in docker's world, all images, volumes, etc? I note that I can't downgrade easily... installing 2.1.2.0 after just _exiting_ 2.1.3.0 results in the installer saying "Existing installation is up to date".

hi im fairly new to the github environment so if i've done anything wrong please understand.
Yes. As the daemon cannot be running there is no way to backup containers and images that i know of... or is there? thanks and im much appreciated of this project!!

**Comment by rafakwolf** [comment]
Same issue here.
-Latest W10 insiders fast
-Ubuntu 18.04.3 LTS
-Docker Desktop Community 2.1.3.0

**Comment by brennaman** [comment]
I'm also experiencing this issue.

**Comment by rfay** [comment]
I bit the bullet and 
* Uninstalled 2.1.3.0
* Installed 2.1.2.0
It made docker work with the tech preview.

Interestingly enough, I lost all the volumes and images on the *windows* side, but *retained* all the volumes and images on the WSL2 side. Not what I expected.

**Comment by wayne-optin** [comment]
How do you install the older specific version? (2.1.2.0) The installer gives me 2.1.0.0, and offers me an update to 2.1.3.0 (which I verified doesn't work on my WSL 2 / build 18985 setup) but no option for 2.1.2.0 ...

**Comment by aldobrynin** [comment]
> How do you install the older specific version? (2.1.2.0) The installer gives me 2.1.0.0, and offers me an update to 2.1.3.0 (which I verified doesn't work on my WSL 2 / build 18985 setup) but no option for 2.1.2.0 ...
Have you tried this one? https://docs.docker.com/docker-for-windows/edge-release-notes/#docker-desktop-community-2120

**Comment by JaySurplus** [comment]
> How do you install the older specific version? (2.1.2.0) The installer gives me 2.1.0.0, and offers me an update to 2.1.3.0 (which I verified doesn't work on my WSL 2 / build 18985 setup) but no option for 2.1.2.0 ...

Here is the 2.1.2.0 download link:　https://download.docker.com/win/edge/38030/Docker%20Desktop%20Installer.exe

**Comment by lucasama** [comment]
I confirm that Docker Desktop 2.1.3.0 breaks WSL 2 Tech Preview, and Docker no longer works in WSL.
Reinstalling version 2.1.2.0 fixes it.
Skipping version 2.1.3.0...
Thank you!

**Comment by mwoodpatrick** [comment]
Confirmed that moving back to version 2.1.2.0 fixed the problem for me with windows version 18990, do we know what broke on 2.1.3.0 and when we might get a fix.

**Comment by JohnCrist1988** [comment]
Ongoing confirmation that Windows 10 Build 18990.vb_release.190921-1704 works well with 2.1.2.0 but does not work with 2.1.3.0 regarding the use of the WSL2 technical preview.

**Comment by chadgrant** [comment]
Disapointed in how many devs feel the need to post "me too" comments

**Comment by stephen-turner** [comment]
We are planning a new Edge release this week, which (we believe!) will fix this issue.

**Comment by JohnCrist1988** [comment]
> Disapointed in how many devs feel the need to post "me too" comments

I'm disappointed how someone thinks everyone posting on a bug report thread is a Docker dev. But that's none of my business.

**Comment by coltenkrauter** [comment]
Thanks for your work on this @stephen-turner .

I just installed 2.1.4 and it didn't seem to show me the WSL2 Tech Preview option, unless I am looking in the wrong place. 

![image](https://user-images.githubusercontent.com/18080897/66853126-66e27b00-ef33-11e9-89f6-3f0ce5a6548b.png)

Any direction would be greatly appreciated. Seems like people are also talking about this issue over here (at least I parsed them as the same issue): https://github.com/docker/for-win/issues/4361

**Comment by Daegalus** [comment]
What link did you use to download it? the one on the edge release pages just returns 404 for me? maybe a CDN propagation issue.

**Comment by coltenkrauter** [comment]
I didn't use a link. I had an earlier version installed and when docker started, it prompted me to update.

**Comment by verglor** [comment]
For me WSL2 works well in version 2.1.4.0 (39357): https://i.imgur.com/Eyz3jL4.png
I upgraded from 2.1.2.0 via chocolatey.

**Comment by sc0ttwad3** [comment]
Version 2.1.4.0 works great, again, for me the past hour. (Prompted to upgrade from 2.1.2.0, simply clicked OK) Ubuntu-18.04 running hyper-fast...

![wsl-pstree](https://user-images.githubusercontent.com/1682691/66857157-ab324300-ef54-11e9-820d-c0a5024a2d87.png)

![wsl2](https://user-images.githubusercontent.com/1682691/66857183-b5ecd800-ef54-11e9-81ec-3b506d0e9b48.png)

**Comment by verglor** [comment]
@Daegalus - since build number of 2.1.4.0 is 39357, the correct download link should probably be https://download.docker.com/win/edge/39357/Docker%20Desktop%20Installer.exe

**Comment by coltenkrauter** [comment]
That is so odd. I am also running Ubuntu-18.04 LTS from the windows store. I don't see the WSL 2 Tech Preview (as shown in my above screenshot)

I upgraded docker and then rebooted with no luck. Did you guys do anything else? 

I'll start by uninstalling docker altogether and installing the latest version of edge.

**Comment by coltenkrauter** [comment]
Things are still not working for me. 

1. I completely uninstalled Docker, I even went into the AppData folder and blew away all remnants of Docker that I could find. 
2. I installed Docker 2.1.4.0
   At this point, I waited for Docker to run and then right clicked on the little icon and there was no sign of WSL 2 Tech Preview
3. I uninstalled Ubuntu 18.04
4. I installed Ubuntu 18.04 and I set it as my default wsl in powershell, then I opened and setup Ubuntu 18.04

Still, no sign of WSL 2 Tech Preview

Anybody have any other ideas?

I've rebooted

**Comment by sc0ttwad3** [comment]
Just throwing some things at the wall:

* Have you tried using the troubleshooter to run diagnostics?
* Under Settings...Command Line...is Enable experimental features on?
* Did you verify/set the default version of WSL to use for new new distro installations (wsl --set-default-version <Version> or manually wsl --set-version <Distro> <Version>)?
* Anything in the Docker logs that might indicate a problem?

**Comment by zot** [comment]
@coltenkrauter If you go to Settings and click Docker Engine, does it look like this?

![image](https://user-images.githubusercontent.com/26665/66893084-eb95cd80-eff5-11e9-911a-ff30c88a811b.png)

The upgrade works for me and I wonder it your settings has `"experimental": true` in it.

**Comment by stephen-turner** [comment]
@coltenkrauter Maybe a silly question, but which build of Windows do you have?

**Comment by KingsDevelopment** [comment]
Encountering the same issue. WSL2 is not showing up on 2.1.4.0 (39357)

**Comment by coltenkrauter** [comment]
@stephen-turner 
![image](https://user-images.githubusercontent.com/18080897/66927941-820dc300-efe5-11e9-955f-0bdb45b26580.png)

Windows Version	10.0.18362 Build 18362

![image](https://user-images.githubusercontent.com/18080897/66928189-dadd5b80-efe5-11e9-97f2-88c2c042d3b7.png)

![image](https://user-images.githubusercontent.com/18080897/66928540-6656ec80-efe6-11e9-8d01-c616b7c6da9a.png)

I appreciate your time!

**Comment by lucasama** [comment]
Apparently you are not in the fast ring. Your windows build is old, you need at least 18917 to have WSL 2:
https://docs.microsoft.com/en-us/windows/wsl/wsl2-install

**Comment by coltenkrauter** [comment]
Oh my word... #SlapsOwnFace 

Thanks for recognizing that. Can't believe that skated past me. Time to update Windows.

**Comment by Felix-Indoing** [comment]
I would like to know if this is supposed to be shown with Archlinux WSL 2?  I am in Windows Build 18970 and with Docker Desktop  2.1.4.0 installed but cannot see the menu entry also.

**Comment by robertiansweetman** [comment]
Still having challenges with Docker Desktop 2.1.4.0 and WSL2 in that the window arrives but remains blank, failing to load. The docker deamon doesn't report as started. Have reverted back to build 2.1.2.0 in the meantime. Running Windows Fast Ring build 18999-1 and have WSL defaulted to run WSL2 with Ubuntu 18.04 LTS as per the documented recommendations.

Maybe, if this is going to be in play for the next 6 months before going GA with H120 someone can point me (users?) to a post about where to get better debug logs to pass on with issues rather than just version numbers of random things? Thanks

**Comment by ptflp** [comment]
remove old docker, and install new docker desktop (solved)

**Comment by dragon788** [comment]
I have run into similar issues to robertiansweetman. I have the latest Insider Preview on the Fast ring and WSL2 enabled for the Ubuntu (Default) which is 18.04 under the hood. I started with 2.1.4.0 (Edge) from one of the direct links above and I could at least see the WSL2 Tech Preview option in the menu and get to the "secret" config page that utilizes WSL2. After installing it has suggested upgrading from 2.1.4.0 to 2.1.6.0, but I waited until I had at least tried starting once from the menu, which did work. After upgrading the menu item disappeared though I did find under the General settings there was a toggle for the WSL2 based engine, but it failed to detect my WSL2 enabled Ubuntu VM (Default, but basically 18.04 under the hood), so I went through and created the specific Ubuntu-18.04 version from the Store and converted it to WSL2 (probably should have enabled WSL2 as the default earlier but hadn't thought I'd be making this many VMs to test it out).

**Comment by dragon788** [comment]
OK, after uninstalling and going back to 2.1.4.0 and setting my default WSL back to Ubuntu I was able to get it working again, and it even continued working after upgrading to 2.1.6.0 again. I found the "secret" to getting it working in my WSL2 containers was to grant them access under "Resources > WSL Integration", though initially after doing this it showed I had two Docker engines running according to the status bar at the lower left. After a system reboot and another upgrade it only shows 1 Docker engine status again.

I figured out I can switch between the contexts of `default` and `wsl` in Powershell, but once I set `wsl` I can't interact with the containers from Powershell, but if I set it back to `default`, WSL machines can run `docker ps` but can't pull/start containers. It also seems like the DockerCli command to switch to a specific engine or switchdaemon don't appear to be properly taking effect, perhaps because of a different location for the CLI/engine with the changes in the Tech Preview/Edge builds?

**Comment by yoshiyes** [comment]
Docker Desktop (tech preview) break wsl..
Dockerd service/process use port 53 and prevent wsl to start

**Comment by robertiansweetman** [comment]
> 
> 
> OK, after uninstalling and going back to 2.1.4.0 and setting my default WSL back to Ubuntu I was able to get it working again, and it even continued working after upgrading to 2.1.6.0 again. I found the "secret" to getting it working in my WSL2 containers was to grant them access under "Resources > WSL Integration", though initially after doing this it showed I had two Docker engines running according to the status bar at the lower left. After a system reboot and another upgrade it only shows 1 Docker engine status again.
> 
> I figured out I can switch between the contexts of `default` and `wsl` in Powershell, but once I set `wsl` I can't interact with the containers from Powershell, but if I set it back to `default`, WSL machines can run `docker ps` but can't pull/start containers. It also seems like the DockerCli command to switch to a specific engine or switchdaemon don't appear to be properly taking effect, perhaps because of a different location for the CLI/engine with the changes in the Tech Preview/Edge builds?

@dragon788 - finally got to the bottom of my own particular issue here: 
https://github.com/docker/for-win/issues/5326

Obviously it's a challenge to not conflate things so YMMV
