### ISSUE TITLE
Windows container loses network connection when connecting the host to Pulse Secure VPN

### ISSUE THREAD

**Issue by mauro-dellachiesa** [docker/for-win#474]
### Expected behavior
Windows container should have access to the external network (internet) and still be accessible from host 
after connecting the VPN (Pulse Secure)
### Actual behavior
Windows container has network connection until the VPN is connected on the host.
### Information

  - Diagnostic ID: 9AC0171B-D643-4B71-813A-6A8C0ACB121C/2017-02-07_20-05-51
  - Windows 10 Pro Version	10.0.14393 Build 14393

I'm using **microsoft/aspnet** as the base for a .net web application, which connects to a db only accessible when connected to the VPN.
If I run the container and have the VPN off, I can access the web site by entering the IP on a browser, but of course it fails because it cannot access the db.
Once I turn on the VPN, the container is not even accessible from a browser on the host (always using IP). 
I can exec a ping to any domain inside the container and it won't reply.

Thanks for taking care of this!

**Comment by simonferquel** [comment]
Are you running your app in a Linux container or a Windows one ?

On a Linux container, if port is correctly exposed, you should access it using localhost:<port>

**Comment by mauro-dellachiesa** [comment]
I'm running a Windows container (microsoft/aspnet) on a Windows host.

**Comment by simonferquel** [comment]
Ok, could you file an issue on https://github.com/docker/docker/issues ? Networking with Windows containers is handled in the Core docker project

**Comment by mauro-dellachiesa** [comment]
Sure thing! Thanks

**Comment by simonferquel** [comment]
Closing the issue on this tracker then :) thanks !
