### ISSUE TITLE
The system failed to create 'DockerDesktop.vhdx'.

### ISSUE THREAD

**Issue by weiweipolyu** [docker/for-win#4741]
Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Failed to create the virtual hard disk.

The system failed to create 'C:\..................DockerDesktop.vhdx'.

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c_

**Comment by ldario** [comment]
Hey!  I had this issue too after a windows update and a docker update.  It seemed to be a weird issue with Hyper-V.  I followed [this](https://github.com/docker/for-win/issues/3577#issuecomment-515049714), and it ended up that changing the "Virtual Hard Disk" and "Virtual Machine" directories fixed it for me.

If that doesn't work for you, hopefully these might: 
* [fixing vmcompute](https://github.com/docker/for-win/issues/3597#issuecomment-493118183)
* [rebuilding the WMI components for virtualization](https://github.com/docker/for-win/issues/1538#issuecomment-357595611)
* [Uninstalling Hyper-V Virtual Adapters](https://github.com/docker/for-win/issues/1538#issuecomment-419162861)
