### ISSUE TITLE
How can i reset permission for my own added files(Click Once .Net c#) in a docker container image ?

### ISSUE THREAD

**Issue by dockergirl** [docker/for-win#475]
### Information

  -SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-x
r-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.

### Steps to reproduce the behavior

 docker build ... in docker file COPY command, copy to /usr/share/nginx/www/

**Comment by simonferquel** [comment]
Can you please share your `dockerfile` and the `docker run` command you are using ?

**Comment by dockergirl** [comment]
FROM nginx:latest
# RUN apt-get -y update && apt-get 
COPY  myClickOnceStuff /usr/share/nginx/www/myClickOnceStuff
CMD ["nginx", "-g", "daemon off;"]

**Comment by simonferquel** [comment]
The permission should not be a problem. You might want to look at the nginx image documentation though to know where to put content files.

The warning just says that as the security model of windows and Linux are different, it uses a default that says basically "everything is read/write/executable"

**Comment by dockergirl** [comment]
COPY static-html-directory /usr/share/nginx/html :-) 
it was the error...now working see my pages on localhost :-) ...have to check if they are working though.

**Comment by simonferquel** [comment]
Can we close the issue rhen ?

**Comment by dockergirl** [comment]
Yes but if it had been a security issue then is there any manual to get the command from ? I mean i have to edit a file in an image, how do i do that ? Do i remove the file and then add myeditedfile with dockerfile ?

**Comment by simonferquel** [comment]
what you can do is in your dockerfile, changing the rights on the files you just added with a `RUN chmod ...` command for putting explicit access rights to your file
