### ISSUE TITLE
Access to the path 'dockerd.exe' is denied.

### ISSUE THREAD

**Issue by brianharwell** [docker/for-win#4754]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics

### Expected behavior
The upgrade to a newer version succeeds.

The setup should make sure there are no file locks on `dockerd.exe` before it uninstalls Docker Desktop.

### Actual behavior
When there is a new update it fails because `dockerd.exe` has a file lock. When the setup fails I need to use a file unlocker utility to forcibly remove the file lock, download and install the latest channel release (which is not the latest), open Docker Desktop and check for updates, and do this again.

Here is the error message
```
Access to the path 'dockerd.exe' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at CommunityInstaller.UninstallWorkflow.<ProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<PerformUninstall>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()
```

After Docker Desktop uninstalled itself for the update the `dockerd.exe` file was left. I tried deleting it and I got this error, even though I had no other applications open.

![image](https://user-images.githubusercontent.com/1017867/65147238-55b15780-d9e3-11e9-90e9-95ba7c3da565.png)

### Information

Please, help us understand the problem.  For instance:
  - Is it reproducible? It happens on *every* update
  - Is the problem new? No, I'm just getting tired of seeing this error
  - Did the problem appear with an update? Yes, with *every* update
  - Windows Version: 10 v1809
  - Docker Desktop Version: 2.1.0.2 (trying to install 2.1.0.3)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
1. Install Docker Desktop
2. Use it like normal
3. When an update appears, click update
4. Boom!

**Comment by MBK75** [comment]
This has happened to me on every update since I installed Docker for Windows probably 8 months ago.

**Comment by MBK75** [comment]
It looks like the issue is the Windows Event Log.  When I try to delete dockerd.exe manually, that is what has a lock on the file.  I don't know how to restart the Event Log service (it doesn't appear to be simple) so I have to reboot.

**Comment by Vaccano** [comment]
I also get this every single time I update.  I put off updating as long as possible because it is so annoying.

**Comment by mat007** [comment]
As it happens we have rewritten the deletion code of the (un)installer and it shipped with Edge 2.1.5.0 (not in Stable yet).
Has this problem happened recently? Would you happen to have log files with the error message and stack trace (look in `%LOCALAPPDATA%\Docker`)?

**Comment by sakshivij** [comment]
> I also get this every single time I update. I put off updating as long as possible because it is so annoying.
> 
> Since this looks like it will not be fixed anytime soon, here are the steps to successfully upgrade Docker Desktop for Windows:
> 
> 1. Rename C:\Program Files\Docker\Docker\resources\dockerd.exe to dockerd_old.exe
> 2. Download the new version from: https://hub.docker.com/?overlay=onboarding
> 3. Install the new version
> 4. Go to C:\Program Files\Docker\Docker\resources and try to delete dockerd_old.exe.  (This may not work because Windows Event Log may have it locked.  A tool (like LockHunter or Unlocker) can delete it on reboot.

This is the only solution that has seemed to work for me if anybody is still looking for one.

**Comment by MBK75** [comment]
I think the error is because dockerd.exe holds a lock on the Event Viewer

**Comment by sakshivij** [comment]
> I think the error is because dockerd.exe holds a lock on the Event Viewer

Yes you are correct. Previous one can be deleted easily after fresh install.
