### ISSUE TITLE
Docker Problem

### ISSUE THREAD

**Issue by stanleyyeo97** [docker/for-win#4758]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stanleyyeo97** [comment]
Diagnostics ID: BFA8F527-C51C-4785-A1E2-33F802183CC5/20190919020418

**Comment by JohnCrist1988** [comment]
The title of the issue, and the body of the issue, don't inform us what the problem is. Can you elaborate as to what you're doing, what's not working, what's happening, etc? i.e, can you fill in the blank areas of the above form?
