### ISSUE TITLE
Unable to set "Share Drive"

### ISSUE THREAD

**Issue by tariqg11** [docker/for-win#4760]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BC639E78-575A-4201-AFC0-3CF4035D7769/20190919075044

### Expected behavior
When click on 'Apply' in Settings after selecting to 'share' the "C" drive, the settings to take affect.
### Actual behavior
When 'Apply' is clicked in Settings after selecting to 'share' the "C" drive the 'busy-circle' shows up and never goes away until the 'Docker Desktop' application is killed from Task Manager.
### Information

  - Windows Version: Win 10 Pro
  - Docker Desktop Version:  2.1.0.3 (38240)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Right click on the Docker icon in tray, select settings
  2. Select "Shared Drives"
  3. Select the box under "Shared" column for "C"
  4. Click on "Apply" button at bottom right of the settings box and 'busy circle' shows up.

**Comment by mryserb** [comment]
Had a similar problem, on my machine the lanmanserver (described as "Server" in windows services) was deactivated/stopped... after enabling it, it worked!

**Comment by tariqg11** [comment]
> Had a similar problem, on my machine the lanmanserver (described as "Server" in windows services) was deactivated/stopped... after enabling it, it worked!

Thank you, I tried to enable it from TaskManager/Services first but turns out it was disabled, I had to do some digging and it was listed as "Server" in the Windows Administrative Toos > Services, once enabled from there then I was able to start the service from Task Manager / Services !!!!

Thank you !
