### ISSUE TITLE
Unable to enable Docker Engine for WSL 2 in latest technical preview

### ISSUE THREAD

**Issue by fiveisprime** [docker/for-win#4764]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6056A120-048B-4254-82BA-9FC8C58CBB5D/20190919215143

### Expected behavior
Should be able to enable the WSL 2 docker engine. 

### Actual behavior
WSL 2 status screen stuck at "Loading..."

### Information
- Reproduces 100% since the last update (took it today)
- On Windows Insiders@190907
- Docker Desktop Version: 2.1.3.0 (38275)
- Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
1. Right-click on Docker Desktop tray icon and choose "WSL 2 Tech Preview"
1. The status view is selected by default and displays "Loading..." indefinitely

I also tried manually setting the docker context using `$ docker context use wsl`, which successfully switches context. This has no real affect though since the daemon isn't running. I've reset defaults and even reinstalled Docker Desktop - as soon as I take the latest update, I'm back in this state.

**Comment by LordObsidian01** [comment]
I am experiencing the exact same issue

**Comment by Andor233** [comment]
I am experiencing the exact same issue

**Comment by tbertenshaw** [comment]
same here

**Comment by dspe** [comment]
+1

**Comment by KingsDevelopment** [comment]
Yap same here

**Comment by tbertenshaw** [comment]
noticed this seems to be a dupe of #4734   Also can confirm as that issue mentions that uninstalling and getting the 2.1.2.0 does work

**Comment by eblount** [comment]
Yes, same

**Comment by ducmthai** [comment]
+1, same here

**Comment by ivellios** [comment]
Same as well :)

**Comment by dasalazar1** [comment]
+1

**Comment by coltenkrauter** [comment]
+1

**Comment by THernandez03** [comment]
+1

**Comment by kylos101** [comment]
[2.1.3.0 would not start for me...downloading 2.1.2.0 from here and downgrading. Thanks for the tip, @tbertenshaw ](https://docs.docker.com/docker-for-windows/edge-release-notes/)

**Comment by y-kawa** [comment]
+1

**Comment by kershnerd** [comment]
+1

**Comment by Armatorix** [comment]
+1

**Comment by NickCoad-NewsPerform** [comment]
> [2.1.3.0 would not start for me...downloading 2.1.2.0 from here and downgrading. Thanks for the tip, @tbertenshaw ](https://docs.docker.com/docker-for-windows/edge-release-notes/)

@kylos101 do you mind explaining how you downgraded? Is there a better process than manually backing up images and uninstalling Docker?

**Comment by thosch-mpa** [comment]
+1

**Comment by Armatorix** [comment]
Duplication of #4734

**Comment by Armatorix** [comment]
Resolved in 2.1.4.0
