### ISSUE TITLE
Firewall blocking shared drives

### ISSUE THREAD

**Issue by jamesstewart1** [docker/for-win#4769]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 13663272-F517-4B73-B392-CA969D9A457C/20190920101347

### Expected behavior
Can share C drive from shared drives without switching off the firewall.
### Actual behavior
Error message - Firewall error. A firewall is blocking file sharing between Windows and the containers. See documentation for more info.
I have tried this on multiple machines on and off the domain and I am getting the same error. 
I can telnet 10.0.75.1
This has been tried with static dns settings. 
The file and print sharing is enabled. 
### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by djs55** [comment]
@jamesstewart1 thanks for your report. There's a completely new drive sharing mechanism in the latest edge release which should be immune to firewall issues.

In case it's useful I've written instructions for setting up and testing the new file sharing implementation available in the edge channel here: https://github.com/docker/for-win/issues/5139#issuecomment-559700215

**Comment by stephen-turner** [comment]
This is fixed with the new filesharing implementation in 2.2.0.3, so closing this ticket.
