### ISSUE TITLE
Docker service fails to start with Powershell error: Creating the virtual machine failed

### ISSUE THREAD

**Issue by ftdube** [docker/for-win#477]
### Expected behavior
Docker service starts with no error

### Actual behavior
Docker fails to start and I get an error saying : 

Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Creating the virtual machine failed.
at New-MobyLinuxVM, <No file>: line 197
at <ScriptBlock>, <No file>: line 374
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

### Information

  - Diagnostic ID : 66A026CF-C64A-4183-AD23-DEE7F878F0D0/2017-02-08_12-14-24
  - Windows 10 Pro build 1607
  - Docker Version 1.13.0 (9795)

### Steps to reproduce the behavior

  1. Install the Windows Docker msi
  2. Start Docker

**Comment by simonferquel** [comment]
Can you try to create any VM manually from Hyper-V manager ?

**Comment by ftdube** [comment]
Ironically it seems like rebooting my PC fixed the issue.  But I can't seem to have access to my grid even if the containers are running and the docker ps command doesn't seem to work :\

**Comment by rneugeba** [comment]
@ftdube I'm closing this issue as the original issue seem to have resolved itself with a reboot. Could you open a new issue with more of a description (and errors) and new diagnostics of what's not working. I can't quite understand your brief description above
thanks
