### ISSUE TITLE
WSL 2 will not launch distro while Docker is running.

### ISSUE THREAD

**Issue by dp6000** [docker/for-win#4772]
**Summary**
I set up a Ubuntu-18.04 distro and Docker WSL 2 Tech Preview last night and everything was working well. This morning I needed to reboot my Once the PC restarted, WSL reported a 0xffffffff error whenever I tried to launch the distro.

![image](https://user-images.githubusercontent.com/2501197/65363970-9ff12f00-dbc3-11e9-8cfb-274ae44ac7eb.png)

I was able to launch the distro, once I uninstalled docker and restarted the system. I have tried
Docker versions 2.1.0.0 and 2.1.2.0.  Note 2.1.3.0 had a different issue that prevented testing.

Resource Monitor showed two instances of dockerd.exe and one instance of svchost.exe (netsvcs-p) using port 53. Once I uninstalled docker, only the svchost was using the port.
-->
![image](https://user-images.githubusercontent.com/2501197/65363752-797ec400-dbc2-11e9-8fcb-cba8ba376739.png)

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 52E0251A-2370-4CA7-A831-F49373B6B7A7/20190920220011

### Expected behavior
Docker should not prevent WSL 2 distro from launching.

### Actual behavior
See summary above

### Steps to reproduce the behavior

  1. Set up WSL 2 per Microsoft and Docker Instructions
  1a. Install Ubuntu-18.04 distro from Windows Store. Set it as default.
  1b. Install Terminal from Windows Store
  2. Install Docker 2.1.2.0 and have it start up on boot.  (note 2.1.3.0 has a different issue that inhibits testing.)
  3. Restart the PC
  4. open Terminal and start distro by selecting Ubuntu-18.04 from the dropdown.
  5. Alternatively,  type:  wsl -d Ubuntu-18.04  in powershell.  WSL should report error 0xffffffff.
 
**To correct the issue:**
   1. Uninstall Docker.
   2. Reboot PC
   3. Launch Terminal
   4. Start the distro using methods described in steps 4 or 5 above.

### Launching Docker WSL 2 Team Preview Prior to Uninstalling Docker:
![image](https://user-images.githubusercontent.com/2501197/65363878-032e9180-dbc3-11e9-889f-4704aed3d2a8.png)

**Comment by stephen-turner** [comment]
cc @simonferquel

**Comment by simonferquel** [comment]
This is the typical HNS-related issue we have randomly. What windows build number do you have @dp6000?

**Comment by YakhontovYaroslav** [comment]
@simonferquel I`m on 18985.1 (18985.vb_release.190913-1426) and having similar issues.
There is an [issue](https://github.com/microsoft/WSL/issues/4364) on WSL repo with wider discussion of the same or closely related issue, hope this helps.

**Comment by simonferquel** [comment]
@benhillis can we have someone from HNS team have a look at this issue ? There might be something wrong within https://github.com/docker/libnetwork for Windows networkgs, but it is clearly outside my comfort zone

**Comment by dp6000** [comment]
@simonferquel I apologize for the later reply.  I am running Windows 10 Pro Version 1903.  Unfortunately, the build version just got updated two days ago.  I was using the prior build to the current 18990.vb_release.190921-1704.  If I get some time this week, I will test on the current build.

**Comment by daschott** [comment]
I am unable to reproduce the issue on 2.1.3.0 because WSL will not launch.  On  2.1.2.0 I am able to successfully run Docker engine on WSLv2 + WSLv2 ubuntu simultaneously. How often does this issue reproduce? 

I am on build 18990.vb_release

**Comment by dp6000** [comment]
@daschott I was able to successfully run docker on windows build 18995.vb_release.190927-1420 using docker version 2.1.2.0 (38030).  I was not able to reproduce the issue I previously reported.

I noticed that resource monitor is no longer showing docker running on port 53.

![image](https://user-images.githubusercontent.com/2501197/66328251-23f42800-e8e1-11e9-9573-3a8536e360bd.png)

![image](https://user-images.githubusercontent.com/2501197/66328395-687fc380-e8e1-11e9-88b9-2dfbd10dc451.png)

**Comment by Enf0** [comment]
What was the solution to this issue? I am running Docker 2.1.4.0 (WSL 2 Tech Preview) on Windows 10 build 18999.vb_release.191004-1432 and I'm experiencing this issue still. 
After a reboot, WSLv2 Ubuntu-18.04 fails to start with error "Error: 0xffffffff", presumably because dockerd.exe is listening on port 53 which conflicts with svchost.exe, as indicated previously here and in https://github.com/microsoft/WSL/issues/4364

**Comment by Silic0nS0ldier** [comment]
I'm able to reproduce this issue under Windows build 19002 (released October 17, 2019) and Docker Desktop for Windows 2.1.4.0 (39357). I'm not able to reliably reproduce this issue, its plausible that there are race conditions occurring (which makes sense I guess).

**Comment by Silic0nS0ldier** [comment]
Issue appears to be persisting under 2.1.5.0 based on #5085 , worth using it as the main issue given it is actually open.
