### ISSUE TITLE
Device Option not mapping Serial Port COMx to container

### ISSUE THREAD

**Issue by zonyl** [docker/for-win#478]
### Expected behavior
Serial Port from host available to container
 docker run --device COM3:/dev/ttyS2 

### Actual behavior
 docker run --device COM3:/dev/ttyS2 -v /c/Projects/mh/local:/usr/src/misterhouse/local -t -i zonyl/misterhouse
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: linux runtime spec devices: error gathering device information while adding custom device "COM3": lstat COM3: no such file or
directory.

### Information
PS C:\Projects\mh\local> [System.IO.Ports.SerialPort]::getportnames()
COM4
COM3

PS C:\Projects\mh\local> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      14986  0

### Steps to reproduce the behavior

  1. ...docker run --device COM3:/dev/ttyS2 -v /c/Projects/mh/local:/usr/src/misterhouse/local -t -i zonyl/misterhouse

**Comment by rneugeba** [comment]
The container is running in a Linux VM and it is not possible to map host (windows) devices such as the serial port into the VM so you can't map it into the container. So unfortunately, this won't fix

**Comment by MahajanHarsh** [comment]
Will it work with linux host (ubuntu) with linux container? if yes, how?

**Comment by quang319** [comment]
Is there any future plan to add this feature?
