### ISSUE TITLE
WSL 2 Tech Preview not starting after installing latest Microsoft changes

### ISSUE THREAD

**Issue by mwoodpatrick** [docker/for-win#4785]
I'm having a problem with the WSL 2 Technical preview. This was working until I installed the latest Microsoft updates now when I run WSL 2 Tech Preview the dialog box comes up and say its loading but it never completes  and shows Docker Engine WSL2 is stopped. I ran the diagnostics but this does not show anything. Any suggestions on how to debug this?

**Comment by tecnojp** [comment]
The same happened to me when i installed the Build 18985.1 of Windows 10.
I also noticed that i cannot change the Disk Image Location anymore in the Settings.
I also open a Problem in the Hub of Comments.
https://aka.ms/AA64es0

**Comment by peter-developer** [comment]
something similar happens to me, except that docker worked fine with win10 18985 and it was when I updated docker desktop to the latest version that the problems you described began to occur.

**Comment by julie-ng** [comment]
Same problem - this is what it looks like - it never finishes loading. Killing all Docker processes and restarting does not help...

![image](https://user-images.githubusercontent.com/1269507/65602264-e79cff80-dfa3-11e9-8717-922c5837aaa6.png)

For reference, this is my Windows version
![image](https://user-images.githubusercontent.com/1269507/65602245-d94ee380-dfa3-11e9-93fa-478cfc72111d.png)

**Comment by jcuribe** [comment]
looks like its docker 2.1.3 I have had to downgrade to docker 2.1.2

**Comment by verglor** [comment]
Duplicate of #4734
