### ISSUE TITLE
WSL 2 "Pool overlaps with other one" when running docker stack deploy

### ISSUE THREAD

**Issue by sfischaber** [docker/for-win#4791]
### Summary

I set up a Ubuntu-18.04 distro and Docker WSL 2 Tech Preview and am working through the [getting started guide](https://docs.docker.com/get-started/).  I have started the WSL 2 daemon and can run through part 2, but when I reach part 3 and try to run:

`docker stack deploy -c docker-compose.yml getstartedlab`

I get a "Pool overlaps with other one" error on all of my replicas.
  

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E6C0D726-8204-49E1-94F9-A8C765AB9863/20190924102825

### Expected behavior

Running `docker stack deploy -c docker-compose.yml getstartedlab` under WSL 2 context should bring up 5 replicas.  This works under the default context.

`PS> docker context ls`

NAME |               DESCRIPTION   |                            DOCKER ENDPOINT     |             KUBERNETES ENDPOINT  | ORCHESTRATOR
---|---|---|---|---
default *      |     Current DOCKER_HOST based configuration |  npipe:////./pipe/docker_engine ||                        swarm
wsl           |      Docker daemon hosted in WSL 2         |    npipe:////./pipe/docker_wsl||

`PS> docker stack deploy -c docker-compose.yml getstartedlab`
`Creating network getstartedlab_webnet`
`Creating service getstartedlab_web`
`PS> docker service ps getstartedlab_web`

ID|                  NAME|                  IMAGE |                 NODE|                DESIRED STATE|       CURRENT STATE|         ERROR|               PORTS
---|---|---|---|---|---|---|---
zg8n3i0ay5to  |      getstartedlab_web.1  | friendlyhello:latest |  docker-desktop  |    Running |            Running 3 hours ago||

### Actual behavior

But running from the WSL2 context gives errors.

`~/docker-tutorial$ docker context ls`

NAME|                DESCRIPTION |                              DOCKER ENDPOINT|               KUBERNETES ENDPOINT|   ORCHESTRATOR
---|---|---|---|---
default * |          Current DOCKER_HOST based configuration |  unix:///var/run/docker.sock   || swarm

`~/docker-tutorial$ docker stack deploy -c docker-compose.yml getstartedlab`
`Creating network getstartedlab_webnet`
`Creating service getstartedlab_web`
`~/docker-tutorial$ docker service ps getstartedlab`

ID|                  NAME|                      IMAGE|                  NODE|                DESIRED STATE|       CURRENT STATE|                     ERROR|                              PORTS
---|---|---|---|---|---|---|---
hw5dhmpkbx3d |       getstartedlab_web.1|       friendlyhello:latest|   HostName|          Ready|               Rejected less than a second ago |  "Pool overlaps with other one …"|
hkqsvbculj5l|         \_ getstartedlab_web.1 |  friendlyhello:latest |  HostName|       Shutdown |           Rejected 5 seconds ago  |          "Pool overlaps with other one …"|
tp1vz4vjae90    |     \_ getstartedlab_web.1  | friendlyhello:latest |  HostName|        Shutdown|            Rejected 10 seconds ago |          "Pool overlaps with other one …"|
wwo2b1yo3may  |       \_ getstartedlab_web.1  | friendlyhello:latest |  HostName|       Shutdown|            Rejected 15 seconds ago    |       "Pool overlaps with other one …"|
392xr2kjc752  |       \_ getstartedlab_web.1 |  friendlyhello:latest  | HostName|        Shutdown  |          Rejected 20 seconds ago |          "Pool overlaps with other one …"|

### Information

  - Windows Version:  Windows 10 Insider Preview Build 18980.1
  - Docker Desktop Version: 2.1.2 (note 2.1.3 has a different issue that prohibits resting)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

1. Set up WSL 2 per Microsoft and Docker Instructions
1a. Install Ubuntu-18.04 distro from Windows Store.
2. Install Docker 2.1.2.0
3. Start Docker and Start Windows Subsystem for Linux 2 (Technical Preview)
4. Follow instructions in [Part 2 getting started](https://docs.docker.com/get-started/part2/) to build app
5. Follow instructions in [Part 3 getting started ](https://docs.docker.com/get-started/part3/)
5a. Create docker-compose.yml
5b. run `docker swarm init`
5c. run `docker stack deploy -c docker-compose.yml getstartedlab`

**Comment by darkflame0** [comment]
Is there any progress?

**Comment by seanmetrix** [comment]
was able to do a workaround using docker-compose - seems the issue is swarm networks - docker-compose uses a local network and doesn't have the problem.

however docker-compose doesn't have all the functionality that swarm does.

please fix!
