### ISSUE TITLE
WSL2 Tech Preview Loading

### ISSUE THREAD

**Issue by nicoabie** [docker/for-win#4795]
- [X] I have tried with the latest version of my channel (Stable or Edge) 
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Starts the WSL2 Docker Engine
### Actual behavior
It can't start the WSL2 Docker Engine
### Information

  - Windows Version: Windows Insiders Preview Version	10.0.18950 Build 18950
  - Docker Desktop Version: 2019-09-13 2.1.3.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: NO

![image](https://user-images.githubusercontent.com/2797992/65526990-57d65300-dec8-11e9-91b6-a5a18e091ca4.png)

**Comment by wsung** [comment]
Duplicate Issue? https://github.com/docker/for-win/issues/4734

Uninstall 2.1.3.0 and install 2.1.2.0 instead.

**Comment by beaufrusetta** [comment]
Having them same issue...will try downgrading the version and report back.
