### ISSUE TITLE
Credential error on container start

### ISSUE THREAD

**Issue by rtjandrews** [docker/for-win#4798]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 73C3164A-ACC0-4A21-8E4A-16C96A9E3408/20190925073251

### Expected behavior
The host.docker.internal entry should be entered into the container hosts file and the container should be able to contact a service running on the host.

### Actual behavior
The host.docker.internal entry is not in the hosts file and I cannot connect to a service running on my localhost.

### Information
  - Windows Version: Windows 10 (1903)
  - Docker Desktop Version: 2.1.0.1
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

The Windows event log has errors regarding invalid username and password ...

Error running exec 178b3c06bd029f2c4fa5f1496e431c6512babeedab1c2d8576a36aaeb16b8a07 in container: container 4a9e117f3202863fbd7228d76189094c3da93183e4a6e695a07c5e0a11ffb90e encountered an error during CreateProcess: failure in a Windows system call: The user name or password is incorrect. (0x52e)
[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]
[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]
[Event Detail: onecore\vm\compute\management\orchestration\vmhostedcontainer\processmanagement.cpp(173)\vmcomputeagent.exe!00007FF67618AE77: (caller: 00007FF67613E4AB) Exception(2) tid(388) 8007052E The user name or password is incorrect.
    CallContext:[\Bridge_ProcessMessage\VmHostedContainer_ExecuteProcess] 
 Provider: 00000000-0000-0000-0000-000000000000] extra info: {"CommandLine":"cmd.exe /C \"ECHO 10.200.34.118    host.docker.internal \u003e\u003e %systemroot%\\system32\\drivers\\etc\\hosts \u0026 ECHO 10.200.34.118    gateway.docker.internal \u003e\u003e %systemroot%\\system32\\drivers\\etc\\hosts\"","User":"Administrator","WorkingDirectory":"/","Environment":{"LOCALAPPDATA":"C:\\Users\\ContainerAdministrator\\AppData\\Local","PSCORE":"\\PowerShell\\pwsh.exe","PSModuleAnalysisCachePath":"\\Microsoft\\Windows\\PowerShell\\docker\\ModuleAnalysisCache","ProgramFiles":"C:\\Program Files"},"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}

### Steps to reproduce the behavior

  1. Run docker run -it mcr.microsoft.com/powershell powershell 
  2. Check Windows event log for errors
  3. run ping host.docker.internal

**Comment by ki11roy** [comment]
Same issue with 2.1.0.3 (38240)

**Comment by valik-tut** [comment]
Same issue with 2.1.0.4(39773)

**Comment by ambrauer** [comment]
Seeing this on 2.2.0.3(42716) on Windows 10 (1809) as well

**Comment by idemax** [comment]
Same in `Docker version 19.03.5, build 633a0ea` (`docker --version`)
Docker Win Desktop `2.2.0.3 (42716) stable`

**Comment by idemax** [comment]
> Same in `Docker version 19.03.5, build 633a0ea` (`docker --version`)
> Docker Win Desktop `2.2.0.3 (42716) stable`

Solved (?)

I was executing with the -it after image tag, example: `docker run dotnet-uwp-unity -it powershell`

So I moved the `-it` just after the `run` argument: `docker run -it dotnet-uwp-unity powershell`

**Comment by ilazarevski** [comment]
Any news about above issue?

Docker version 19.03.5, build 633a0ea (docker --version)
Docker Win Desktop 2.2.0.3 (42716) stable
