### ISSUE TITLE
Allow user to add custom Certificate Authorities

### ISSUE THREAD

**Issue by bbodenmiller** [docker/for-win#48]
### Expected behavior

I should be able to use a registry signed by a custom Certificate Authority without having to register it as insecure. 

### Actual behavior

When attempting to use a registry signed by a custom Certificate Authority Docker for Windows returns a `x509: certificate signed by unknown authority` error. Only workaround is to register registry as insecure.

Related to https://github.com/docker/for-win/issues/26, https://github.com/docker/for-win/issues/36, https://github.com/docker/for-win/issues/23, & https://github.com/docker/for-mac/issues/343. Per @friism at https://github.com/docker/for-win/issues/9#issuecomment-236690036 looks like something like this may already be on the roadmap.

**Comment by rneugeba** [comment]
@bbodenmiller Yes, this definitely is on the roadmap. Thanks for filing this issue here (and commenting on the issues you referenced).

**Comment by dgageot** [comment]
@bbodenmiller for your information this will be included in next beta (Beta26)

**Comment by dgageot** [comment]
@bbodenmiller Docker for Windows Beta26 was released yesterday. Could you give it a shot and see if it fixes your issue?

**Comment by bbodenmiller** [comment]
Sure, will check. Do I upload the CA cert or do you pull them from the Windows cert store? The latter would be the better option.

**Comment by dgageot** [comment]
@bbodenmiller We do pull them from the cert store :-)

**Comment by dgageot** [comment]
Hi @bbodenmiller Did `beta26` work for you?

**Comment by jasonsoft** [comment]
Hi @dgageot,

I just tried both version of `beta26` and `stable-1.12.1`, but I still got `509: certificate signed by unknown authority` .  I import my certificate under `Trust Root Certification Authorities` folder.  Do you have any suggestions that I can try?  Thank you

**Comment by bbodenmiller** [comment]
1.12.1 worked for me. Perhaps some documentation is needed around where certs should be placed?

**Comment by jasonsoft** [comment]
@bbodenmiller ,

Would you mind me asking where did you put your certs?

**Comment by dgageot** [comment]
@bbodenmiller yes, of course! We will

**Comment by bbodenmiller** [comment]
@jasonsoft looks like mine is in both `Trusted Root Certification Authorities` and `Intermediate Certification Authorities`.

**Comment by dgageot** [comment]
@bbodenmiller @jasonsoft I hope it works well for you two. Can this is issue be closed?

**Comment by bbodenmiller** [comment]
Sounds good to me. Should I open a new issue about how it should be documented?

**Comment by friism** [comment]
> Perhaps some documentation is needed around where certs should be placed?

cc @londoncalling for docs

**Comment by dgageot** [comment]
I'm going to close this issue and create an issue in our internal tracker to make sure this is documented

**Comment by GarbageYard** [comment]
Hi. I am using docker-machine on Win 10 Enterprise. When i try to run `docker login`, i get error:

```
docker login docker.artifactory.abc.net -u tom -p tom_pwd
Error response from daemon: Get https://docker.artifactory.abc.net/v2/: x509: certificate signed by unknown authority
```

I added certificate to both `Trusted Root Certification Authorities` and `Intermediate Certification Authorities` . I've been trying to get this working for the last 2 days but to no avail. Any pointers?

**Comment by lyz19890927** [comment]
After add the certificate, I have to restart my docker, then it worked. Spent a lot of time to figure out this way.
