### ISSUE TITLE
Shared Drives do not work if password contains unsafe linux shell characters

### ISSUE THREAD

**Issue by jtnord** [docker/for-win#480]
### Expected behavior

The username and password I enter can be used to create/mount a share

### Actual behavior

if my password contains unsafe characters like `! " $ * ( '` (the list to the right has not been fully vetted and there may be more unsafe characters or it may be just a subset of them that cause issues) then the share is created but the mount fails and then the share is destroyed.  This causes all manner of confusion.

### Information

See #466 for the diagnostic and my logs etc..
Split from that ticket as this is a concrete example of an epic failure.  (who uses short passwords with only [a-zA-Z0-9] these days?)

### Steps to reproduce the behavior

  1. create a local user with a password `myPassword!$`
  2. try to enable sharing of your C drive
  3. Notice the above fails.
  4. while have hair, remove some, goto 1
  5. change the users password to `myPassword123`
  6. try to enable sharing of your C drive
  7. notice that it works...

 8. take palm of hand and move rapidly towards forehead.
  9. _realize that the password you have been using on your laptop is probably not secure enough and needs a larger set of characters._
 10. _realise that you where hacked at a coffee shop as you have a week password_
 11. _wipe your laptop and re-install from scratch._

**Comment by rneugeba** [comment]
@jtnord I'm pretty sure that the special characters you mention above work as we test them (and some are in my password). Here is what we use for testing:
`P@s;w," .%^*03rd$`\/r!`
`d$!ø§£µîüéàæøå4`
`s=#~2))-+|{}[]<>`
The two missing from your list is `(` which should be fine, and `'` which may be special

**Comment by jtnord** [comment]
@rneugeba well it didn't work for my with my normal user account.
I created a new account with password `myPassword!$` and it didn't work.
I change the password to `myPassword` and it worked first time.

Maybe it is the combination coupled with the fact that it is at the end?  I don't know but the above steps reproduced the issue for me.

**Comment by rneugeba** [comment]
I've just tried with Beta41 and the password you mention just works

**Comment by simonferquel** [comment]
Per chance, are you using an old version of Docker for Windows (I mean, very old) ?

**Comment by jtnord** [comment]
> Per chance, are you using an old version of Docker for Windows (I mean, very old) ?
Nope - 1.13.1-rc2-beta41
