### ISSUE TITLE
Docker Engine (WSL2) does not start

### ISSUE THREAD

**Issue by akaliazin** [docker/for-win#4805]
- [ ] I have tried with the latest version of my channel (Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 10686354-4A58-430F-ACC1-28F5D03CF905/20190925202601

### Expected behavior
* Docker Engine - running
* Docker Engine (WSL2) - runnning
### Actual behavior
* Docker Engine - running
* Docker Engine (WSL2) - stopped. Status page: "loading..." indefinitely; "Apply and Restart" button - greyed out

### Information

  - Windows Version:  10.0.18990 N/A Build 18990
  - Docker Desktop Version: 
```
docker info |grep -i version
 Server Version: 19.03.2
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Kernel Version: 4.14.131-linuxkit
```
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
* no, its a bare-metal server:
```
> systeminfo

Host Name:                 AIML01-WIN10
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.18990 N/A Build 18990
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Windows User
Registered Organization:
Product ID:                00329-00000-00003-AA990
Original Install Date:     25/09/2019, 01:06:34
System Boot Time:          25/09/2019, 19:55:54
System Manufacturer:       LENOVO
System Model:              30A5S00D00
System Type:               x64-based PC
Processor(s):              2 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 63 Stepping 2 GenuineIntel ~2400 Mhz
                           [02]: Intel64 Family 6 Model 63 Stepping 2 GenuineIntel ~2394 Mhz
BIOS Version:              LENOVO A6KTA4AUS, 14/05/2019
```

**Comment by amos-ortal** [comment]
I'm seeing the same thing (same Windows build)

**Comment by akaliazin** [comment]
yea, apparently there is an issue with this 2.1.3.0 Docker Desktop version. removing it and installing 2.1.2.0 instead did fix it.
So for now I set to skip 2.1.3.0

**Comment by verglor** [comment]
Duplicate of #4734

**Comment by bobbyconnolly** [comment]
> yea, apparently there is an issue with this 2.1.3.0 Docker Desktop version. removing it and installing 2.1.2.0 instead did fix it.
> So for now I set to skip 2.1.3.0

For me it's because I installed the WLinux distro and not Ubuntu 18.04. Are there plans to support other distros?
