### ISSUE TITLE
Cannot reduce disk image max size

### ISSUE THREAD

**Issue by cdalexndr** [docker/for-win#4809]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E631F14E-8B3C-46B7-82F8-B975F82EAAD7/20190926100335

### Expected behavior
Disk image max size to be 32GB
### Actual behavior
Disk image max size is 59.6GB
### Information

  - Windows Version: 1803
  - Docker Desktop Version: 2.1.0.3 (38240)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. Disk image max size is currently 80GB
  2. Change it to 32GB, click Apply and accept warning

**Comment by cdalexndr** [comment]
Note: same environment as https://github.com/docker/for-win/issues/4686

**Comment by MythreyaK** [comment]
Similar to #4725

**Comment by alandsidel** [comment]
This is just a bump, I'd like to see this fixed as well, as well as an option to use a fixed size rather than dynamically resizing disk image.

**Comment by edqallen** [comment]
Bad bot.

**Comment by cdalexndr** [comment]
Is it solved? Why the bot closed this issue?

**Comment by edqallen** [comment]
No, it's not fixed.  Yes, this the bot is just a way to make it look like there are fewer issues than there really are.
