### ISSUE TITLE
Docker fails to start after reboot

### ISSUE THREAD

**Issue by kimhmadsen** [docker/for-win#4815]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 7D3894A4-3A56-4F80-B565-39FDD9E7F4BC/20190927054623

### Information

  - Windows Version: 1809 (build 17763.737)
  - Docker Desktop Version: 2.1.0.3 (38240)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Reboot the laptop and docker fails to start.
  2. ...

**Comment by maximveksler** [comment]
Same here, what is the error message?

**Comment by kimhmadsen** [comment]
> Same here, what is the error message?

Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Creating the virtual machine failed.

**Comment by mikeparker** [comment]
Can you try restarting the Hyper-V Virtual Machine Management service? This worked here https://github.com/docker/for-win/issues/4668#issuecomment-533173071

**Comment by maximveksler** [comment]
> Can you try restarting the Hyper-V Virtual Machine Management service? This worked here [#4668 (comment)](https://github.com/docker/for-win/issues/4668#issuecomment-533173071)

In my case I've tried shutdown / restart the Win 10 OS without success only rollback to previous Docker build helps. Unlikely for it being a file handler issue, unless and order of loading race condition ?
