### ISSUE TITLE
Unable to access setting when Hyper-V is off

### ISSUE THREAD

**Issue by AntonioCS** [docker/for-win#4816]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Access docker settings to disable "Start Docker Desktop when you log in"

### Actual behavior
Docker shuts down everything because hyper-v is disable and all I see is an error message stating that hyper-v is disabled
### Information
I had to disable hyper-v so that I could use virtualbox.
I used to use docker but on windows 10 pro it's extremely slow for the current project I am working on, so I moved to a combination of vagrant+docker, but since I didn't disable docker starting up when I log in, every time I boot the machine I get presented with an error message from docker saying that hyper-v is disabled.

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior
1 - Check "Start Docker Desktop when you log in" in Docker General Settings
2 - Disable hyper-v
3 - Reboot
4 - Try to uncheck "Start Docker Desktop when you log in" in Docker General Settings

  1. ...
  2. ...

**Comment by MythreyaK** [comment]
Make sure in Task Manager > Startup, docker is disabled (if it exists). Alternatively, you could try disabling docker through Windows services (Win key, search `services`). Look for `Docker Desktop Service`, open properties and set `Startup Type` to `Manual`. Note that this might cause Docker to prompt you to start the service when you launch docker. To fix this, just revert the setting to `Automatic (Delayed Start)`.

**Comment by AntonioCS** [comment]
@MythreyaK thanks but shouldn't I be able to access docker settings?
I understand that docker cant' function but that doesn't mean I shouldn't be able to access the settings, for situations like this.
I have done all you said and it's disable but I just think it's silly that I have to do it like that instead of just unchecking it in the docker settings.

**Comment by MythreyaK** [comment]
You're right! 
Since most of the UI is dependent on docker running, perhaps this edge case was not such a priority. Glad it worked out though!
