### ISSUE TITLE
Docker start/restart gives error

### ISSUE THREAD

**Issue by jay8127** [docker/for-win#4821]
I downloaded Docker Desktop for Windows. But it's start/restart pops up an error always. Error is:
Unable to stop - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Service 'Hyper-V Host Compute Service (vmcompute)' cannot be started due to the following error: Cannot start service vmcompute on computer '.'.

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass27_0.<ResetToDefault>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

This is the crash report.
91B0158A-F240-4809-8E64-22921FE89C1B/20190927135904

**Comment by jay8127** [comment]
I also tried to reset to factory settings, but no luck.

**Comment by maximveksler** [comment]
I'm trying to reinstall docker desktop, will update.

**Comment by maximveksler** [comment]
Please note duplicate https://github.com/docker/for-win/issues/4815

**Comment by maximveksler** [comment]
What worked for me (for some reason) was to actually uninstall and download a new version from docker hub.

It's version `2.1.0.1 (37199)` and offers to upgrade to `2.1.0.3 (38240)` which seems to be a broken release.

**Comment by SmileEye** [comment]
@mikeparker  thank you, this answer solves my problem !

**Comment by jay8127** [comment]
> flow

Thanks @mikeparker , it really solved it.

**Comment by NishantChauhan** [comment]
This solves the problem

**Comment by jay8127** [comment]
Thanks, i took your other advise as this seems risky for security reasons,
so started different solution by using Kubernetes instead of setting up
docker containers by myself

**Comment by NishantChauhan** [comment]
@jay8127 : Can you provide link for the other advise that you applied?
