### ISSUE TITLE
Dockerimage won't get its content refreshed by dockerbuilt. 

### ISSUE THREAD

**Issue by dockergirl** [docker/for-win#483]
### 
I built an nginx image with my default ClickOnceStuff as a game . Now, i want to get the container in the productive cloud where i need to add the complete ClickOnce content & all my nice webpages.

### Actual behavior
I changed dockerfile COPY to the another directory, where i have my complete web content and changed the line COPY blabla ...It did not work IE is still displaying the old content on localhost.
Then i googled and i simply let the dockerfile unchanged and add the webpages to the existing directory in my game built. But it does not recreate the image, it is still the 2 days ago, it does not add the content and now im getting nervous... 

### Information
There is no message from docker built on this...is there any rebuild command ? Or how to get it refresh the content !
  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. Always the same.
  2. ...

**Comment by dockergirl** [comment]
Finally, i deleted the image ...but is there any command or something ? I mean it is very annoying because how should i know that a build wont build ??? There is no message.

**Comment by friism** [comment]
@dockergirl please use this repo for reporting bugs and issues with Docker for Windows. If you're looking for suggestions and help on using Docker, please file a post with details on what you're trying to do on the forums: https://forums.docker.com/

**Comment by dockergirl** [comment]
yes but the content is not refreshed is it not a bug for you ?

**Comment by friism** [comment]
@dockergirl please provide more details and a simple test that I can inspect run that reproduces the problem, and I'll let you know.

**Comment by dockergirl** [comment]
Pull official nginx image and create a simple dockerfile like
FROM nginx:latest
# RUN apt-get -y update && apt-get 
COPY  mywebsite /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]

mywebsite will contain a simple htm page mywebpage.htm just writing hello world (for me it is the complete Click Once stuff but it doesnt matter, simple static html content will do)

put docker file beside mywebsite and use docker built -t...
 then run the image in the container with exposing port 8080:80...start IE & type localhost...mywebpage.htm ...your webpage will display the html content like "Hello World!"

now change this mywebpage.htm or add more htm files into mywebpage...and then build again the image...now you want to see the new content in IE when you run localhost...the new websites your just added. But you will see your old Hello World and in the moment i dont know how to get in the new content. If you list outr the images you see the old images then remove it and build again...there will be a new image then run it in the container and it will be still the old content...just one page displayed by going in IE to localhost...

**Comment by friism** [comment]
By default `ps` only shows running containers. Use `ps -a` to also show stopped containers. To have containers automatically removed once they exit, use `docker run --rm <your-image>`.

```
C:\code\repros\nginx-content> cat .\Dockerfile
FROM nginx
COPY . /usr/share/nginx/html/.
C:\code\repros\nginx-content> cat foo.txt
hello world

C:\code\repros\nginx-content> docker build -t nginx-test .
Sending build context to Docker daemon 3.072 kB
Step 1/2 : FROM nginx
 ---> cc1b61406712
Step 2/2 : COPY . /usr/share/nginx/html/.
 ---> 88101017315e
Removing intermediate container b732340d7c3c
Successfully built 88101017315e

C:\code\repros\nginx-content> docker run -p 80:80 -d nginx-test
6438bf097c84be152d13f97a05b99c0a90f69b31be7a9908a560987f08a8e965

C:\code\repros\nginx-content> (iwr -UseBasicParsing http://localhost/foo.txt).Content
hello world

C:\code\repros\nginx-content> Add-Content "update" -Path foo.txt

C:\code\repros\nginx-content> docker build -t nginx-test .
Sending build context to Docker daemon 3.072 kB
Step 1/2 : FROM nginx
 ---> cc1b61406712
Step 2/2 : COPY . /usr/share/nginx/html/.
 ---> a95717e0f561
Removing intermediate container 9e665fad9ba7
Successfully built a95717e0f561

C:\code\repros\nginx-content> docker rm -f 6438bf097c84be152d13f97a05b99c0a90f69b31be7a9908a560987f08a8e965
6438bf097c84be152d13f97a05b99c0a90f69b31be7a9908a560987f08a8e965

C:\code\repros\nginx-content> docker run -p 80:80 -d nginx-test
3a4cb7321ac32030120535984bd2fd0cbf7765608fbcec60599ad0bddc98e875

C:\code\repros\nginx-content> (iwr -UseBasicParsing http://localhost/foo.txt).Content
hello world
update
```

As you can see above, the scenario you describe works great.

**Comment by dockergirl** [comment]
Thank you. The only thing i chaged in my code that i added the cat thing & copied the dockerfile into mycontent folder. Now it works. Im sorry, im totally new to docker. In Visual Studio if i click build then that was it all so far...but im learning fast. I try to ask next time the docker forum.

**Comment by dockergirl** [comment]
I dont want to talk much about this but still have to...after succeeding once, i wanted to repeat this & then also removing images,container, cat did not help. Then i downloaded Chrome & it worked with Chrome once...after did 2x midification did not anymore...soi have to add to the troubleshooting IE & Chrome (both i tried) must not be enabled to keep content while docker build more time...because not the docker who does not refresh but browser wont get new content or the nginx might be the one but still whatever so simply dont let keep files for the browser will help & content will be always actual.
