### ISSUE TITLE
Windows 10 is not activated after running container in process isolation

### ISSUE THREAD

**Issue by jonaslewin** [docker/for-win#4831]
- [x] I have tried with the latest version of both channels (Stable and Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 952D93EE-0E65-489D-8893-59C110730FD6/20190930080902

### Expected behavior
Windows to stay activated
### Actual behavior
Windows is not activated. The error message is:
**Windows can't activate at this time. Try activating Windows later. If that does not work contact your system administrator. Error code: 0x8007232B**
In a few cases we got other error codes, but they where all resolved by using the temporary workaround below.
### Information

  - Windows Version: 10.0.18362.387
  - Docker Desktop Version: Docker version 19.03.2, build 6a30dfc
  - We have this issue both on non-virtualized and on virtualized Windows 10, version 1903 with the latest updates. The issue is present in the latest stable docker desktop and the latest edge version.

### Steps to reproduce the behavior

  1. Use Windows containers and enable experimental features.
  2. Run a container using process isolation. Example:
`docker run --isolation process mcr.microsoft.com/windows/servercore:1903 ping -t localhost`
Wait a few minutes. Then go to Windows Settings - Update & Security - Activation.
Alternatively: Wait a few hours and the message that Windows is not activated will appear on the desktop.

### Temporary workaround
Go to Windows Settings - Update & Security - Activation. Click on Troubleshoot. 

This will in 95% of the cases resolve the issue, untill the Windows is restarted and docker runs the container in process isolation again. The remaining 5% is solved by again restarting Windows again, followed by the Troubleshoot steps.

**Comment by Romfos** [comment]
I have the same issue

Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 19.03.5
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 18363 (18362.1.amd64fre.19h1_release.190318-1202)
 Operating System: Windows 10 Pro Version 1909 (OS Build 18363.476)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.94GiB
 Name: PC
 ID: <REMOVED FROM LOG>
 Docker Root Dir: <REMOVED FROM LOG>
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 28
  System Time: 2019-11-24T23:04:10.1484903+03:00
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

**Comment by guillaume86** [comment]
I don't have issues reactivating my copy, but I have the issue that windows keep deactivating when running isolation process containers.

**Comment by pkoutsogilas** [comment]
Is also have the same thing happening, very annoying. 
My colleagues have the same problem.

```
Client:` Docker Engine - Enterprise
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        2ee0c57608
 Built:             11/13/2019 08:00:16
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.12
  Git commit:       2ee0c57608
  Built:            11/13/2019 07:58:51
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place?
