### ISSUE TITLE
Shared Drivers gives `Firewall detected` error (even if the firewall is disabled)

### ISSUE THREAD

**Issue by IonelLupu** [docker/for-win#4832]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
**Diagnostics ID**:
F9A12E9E-585A-4707-8A80-B522AE5A3792/20190930134255

### Expected behavior
Yet another problem with Windows :/ 🤦‍♂ I am trying to set one of my drives as shared-drivers but I keep getting an error from docker:
![image](https://user-images.githubusercontent.com/4083652/65877976-9a4ed280-e395-11e9-8779-ba0c1e178f27.png).

This is EVEN IF my Firewall is disabled which is really odd. 

### Actual behavior
Should let me allow a drive to be shared
### Information

  - Windows Version: 10 Pro 1903
  - Docker Desktop Version: 2.1.0.3 (38240) - stable
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. This is really hard to reproduce. I just installed docker and tried to use it.

**Comment by juan-analian** [comment]
Hi @IonelLupu , I had the same issue this morning. 
Check that "vEthernet (DockerNAT)" adapter has this IP Address: 10.0.75.1 (255.255.255.240 mask).

I found another network adapter whit this IP and the name "Broken Docker Adapter (20190608T1306098858Z) (1)". I remove the static IP settings.

**Comment by PhiltasticGuy** [comment]
@IonelLupu, I ran into the same issue in the past at work. I fixed it with the PowerShell command as per this [answer on StackOverflow](https://stackoverflow.com/questions/42203488/settings-to-windows-firewall-to-allow-docker-for-windows-to-share-drive/43904051).

In my case, our corporate policies were applying restrictions on certain network profiles (i.e. Public and Unidentified Network). By default, Docker creates the `vEthernet (DockerNAT)` card as an *Unidentified Network* on Windows. Running this PowerShell command will set the `vEthernet (DockerNAT)` card's network profile to *Private*.

```
Set-NetConnectionProfile -interfacealias "vEthernet (DockerNAT)" -NetworkCategory Private
```

**Comment by IonelLupu** [comment]
@juan-analian the IP Address is already 10.0.75.1 (255.255.255.240 mask), which means this is not the problem.

I tried @PhiltasticGuy 's solution (which I remember I tried before and it didn't work) and it worked. One more thing, Windows got some updates and I also deactivated and activated Hyper-V(plus restart PC). 

Idk which one of these is responsible for making it work.
