### ISSUE TITLE
docker swarm init fails due to socket permissions

### ISSUE THREAD

**Issue by chsakell** [docker/for-win#4836]
## Expected behavior

`docker swarm init` initializes a swarm 

## Actual behavior

`docker swarm init` fails with the following error:
```
Error response from daemon: manager stopped: failed to listen on remote API address: listen tcp 192.168.96.1:2377: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
```

## Information

I am using Windows Containers, the actual command is the following (using my IPV4 address)
```
docker swarm init --listen-addr 192.168.96.1 --advertise-addr 192.168.96.1
```
No app uses port **2377**.

**Windows Version**: Windows 10 Version 1903 (OS Build 18362.356)

**docker info**
Server:                                                                               
 Containers: 11                                                                       
  Running: 1                                                                          
  Paused: 0                                                                           
  Stopped: 10                                                                         
 Images: 87                                                                           
 Server Version: 19.03.2                                                              
 Storage Driver: windowsfilter                                                        
  Windows:                                                                            
 Logging Driver: json-file                                                            
 Plugins:                                                                             
  Volume: local                                                                       
  Network: ics l2bridge l2tunnel nat null overlay transparent                         
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog  
 Swarm: inactive                                                                      
 Default Isolation: hyperv                                                            
 Kernel Version: 10.0 18362 (18362.1.amd64fre.19h1_release.190318-1202)               
 Operating System: Windows 10 Pro Version 1903 (OS Build 18362.356)                   
 OSType: windows                                                                      
 Architecture: x86_64                                                                 
 CPUs: 12                                                                             
 Total Memory: 15.89GiB                                                               
 Name: DELL-HOST                                                                      
 ID: BI4Z:A577:AUPE:TPWP:TSZZ:5I4G:NK44:2QKE:SYRZ:ZMSX:EIER:7YYQ                      
 Docker Root Dir: D:\ProgramData\Docker                                               
 Debug Mode: true                                                                     
  File Descriptors: -1                                                                
  Goroutines: 87                                                                      
  System Time: 2019-09-30T23:52:30.3867959+03:00                                      
  EventsListeners: 1                                                                  
 Registry: https://index.docker.io/v1/                                                
 Labels:                                                                              
 Experimental: false                                                                  
 Insecure Registries:                                                                 
  127.0.0.0/8                                                                         
 Live Restore Enabled: false                                                          
 Product License: Community Engine

**Comment by chsakell** [comment]
I have just found that the `2377` port belongs to excluded port ranges: 
` netsh int ipv4 show excludedportrange protocol=tcp`

**Administered port exclusions**

Start Port  |   End Port
----------  |  --------
      1561        1660
      1661        1760
      1761        1860
      1861        1960
      1981        2080
      2280        2379
      2380        2479
      2480        2579
      2580        2679
      2680        2779
      2979        3078
      3079        3178
      9000        9000
     50000       50059

**Comment by khtan** [comment]
Is there any resolution for this? I am running into the same problem as well.

Also, a search showed that https://github.com/docker/for-win/issues/3171 is a related problem that got closed, even though the nothing was fixed.

Hope the team is able to take a look at this. 

Thanks,

**Comment by khtan** [comment]
There is a workaround in https://github.com/docker/for-win/issues/3171 that worked for me.
I just had to replace <targetport> with the value I needed, ie 2377.

**Copied instructions for clarify :**
1. Disable hyper-v (which will required a couple of restarts)
dism.exe /Online /Disable-Feature:Microsoft-Hyper-V

2. When you finish all the required restarts, reserve the port you want so hyper-v doesn't reserve it back
netsh int ipv4 add excludedportrange protocol=tcp startport=<targetport> numberofports=1

3. Re-Enable hyper-V (which will require a couple of restart)
dism.exe /Online /Enable-Feature:Microsoft-Hyper-V /All

**Comment by raghunathchary** [comment]
I had same issue my end after I restarted my PC, I couldn't get into docker swarm
```
# docker swarm init --advertise-addr 192.168.2.4                                                                                                                          

Error response from daemon: manager stopped: failed to listen on remote API address: listen tcp 0.0.0.0:2377: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
```
I tried to prune the docker networks with following command:
```
# docker network prune                                                                                                                                                      WARNING! This will remove all networks not used by at least one container.
Are you sure you want to continue? [y/N] y
Deleted Networks:
Default Switch
External VM Switch
```
This step helped me to resolve the issue. Now my docker swarm init works without any issue.

`docker swarm init --advertise-addr 192.168.2.4`
