### ISSUE TITLE
All Docker commands fail with "unable to resolve docker endpoint"

### ISSUE THREAD

**Issue by rlauriston** [docker/for-win#4838]
Diagnostics: 

  - [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: A4587BC8-7068-49A2-A8F8-E977233C6AC4/20190930214549

### Expected behavior

Docker commands work as documented.

### Actual behavior

All Docker commands fail with "unable to resolve docker endpoint: open C:\Users\robert\.docker\machine\machines\default\ca.pem: The system cannot find the path specified."

### Information

I upgraded from Windows 7 to Windows 10 the other day. Downloaded Docker for Windows Installer.exe, completed installation, all commands (even docker --version) failed with "unable to resolve docker endpoint." Tried both cmd and PowerShell.

Uninstalled, verified program and program data directories were empty, reinstalled, same problem.

I see that the certificates are actually at .docker\machines\certs\ rather than .docker\machine\machines\default\.

  - Windows Version: 10 Pro 10.0.18362
  - Docker Desktop Version: 2.1.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. run any Docker command

**Comment by rlauriston** [comment]
This is a duplicate of https://github.com/docker/for-win/issues/1746, which does not mention the error message I got.

**Comment by rlauriston** [comment]
Actually, shouldn't the Docker Desktop installer doesn't remove the problematic path entries?

**Comment by IPLodbrok** [comment]
I also ugraded from win 7 to win 10 and have the same problem now

**Comment by IPLodbrok** [comment]
The solution is:
1) Uninstall docker toolbox
2) delete all docker system and user variables (because the docker uninstaller does not do that...)
3) Install docker desktop again

_> after that everything should work as expected

**Comment by katherinefhc** [comment]
>     2\. delete all docker system and user variables

@IPLodbrok  do you know where those user variables are stored? thanks so much!

**Comment by golyalpha** [comment]
@katherinefhc 
Explorer > This PC (Right Click)> Properties > Advanced system settings > Environment Variables...

Not sure what the variable names are, but yeah.

**Comment by clay53** [comment]
@IPLodbrok 's solution didn't help me.
