### ISSUE TITLE
"docker --version" got Exception in Window 10 pro

### ISSUE THREAD

**Issue by nancwang** [docker/for-win#485]
### Expected behavior
Docker version 1.12.0, build 8eab29e, experimental

### Actual behaviour
Exception 0xc0000005 0x0 0x240c67af2a4 0x18000890a
PC=0x18000890a

syscall.Syscall(0x7ffc73a4dc40, 0x2, 0x30c, 0x3, 0x0, 0x0, 0x0, 0x310)
        /usr/local/go/src/runtime/syscall_windows.go:163 +0x6b
...

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
55B0B206-D953-476C-8234-4C13F05E2DAF/2017-02-10_19-06-18
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)
    Window 10 Pro

### Steps to reproduce the behaviour

Following instruction of https://docs.docker.com/docker-for-windows

  1. ... Download InstallDocker.msi and Double-click InstallDocker.msi to run the installer
  2. ... Start Docker for Windows as Step 2 
  3. ... Go to Step 3. Check versions of Docker Engine, Compose, and Machine by command as following
         $ docker --version
Output:
Exception 0xc0000005 0x0 0x240c67af2a4 0x18000890a
PC=0x18000890a

syscall.Syscall(0x7ffc73a4dc40, 0x2, 0x30c, 0x3, 0x0, 0x0, 0x0, 0x310)
        /usr/local/go/src/runtime/syscall_windows.go:163 +0x6b
github.com/docker/docker/vendor/github.com/Microsoft/go-winio.setFileCompletionNotificationModes(0x30c, 0x303, 0x0, 0xffffffff)
        /go/src/github.com/docker/docker/vendor/github.com/Microsoft/go-winio/zsyscall_windows.go:88 +0x6f
github.com/docker/docker/vendor/github.com/Microsoft/go-winio.makeWin32File(0x30c, 0xc0423bb890, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/github.com/Microsoft/go-winio/file.go:78 +0xd8
github.com/docker/docker/vendor/github.com/Microsoft/go-winio.DialPipe(0xc0420c5108, 0x16, 0xc0423bb980, 0x0, 0x1180920, 0xc041fe1dff, 0xc0423bb9f8)
        /go/src/github.com/docker/docker/vendor/github.com/Microsoft/go-winio/pipe.go:188 +0x537
github.com/docker/docker/vendor/github.com/docker/go-connections/sockets.DialPipe(0xc0420c5108, 0x16, 0x773594000, 0xc042030001, 0x1000000000010, 0x100, 0x100)
        /go/src/github.com/docker/docker/vendor/github.com/docker/go-connections/sockets/sockets_windows.go:26 +0x46
github.com/docker/docker/vendor/github.com/docker/go-connections/sockets.configureNpipeTransport.func1(0xba718f, 0x3, 0xc042399660, 0x19, 0x60, 0x0, 0xc0423c2001, 0xc0423be180)
        /go/src/github.com/docker/docker/vendor/github.com/docker/go-connections/sockets/sockets_windows.go:19 +0x49
net/http.(*Transport).dial(0xc0420c6870, 0xf13040, 0xc0420381f0, 0xba718f, 0x3, 0xc042399660, 0x19, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/http/transport.go:829 +0x82
net/http.(*Transport).dialConn(0xc0420c6870, 0xf13040, 0xc0420381f0, 0x0, 0xba78bf, 0x4, 0xc042399660, 0x19, 0x0, 0x0, ...)
        /usr/local/go/src/net/http/transport.go:967 +0x1a8c
net/http.(*Transport).getConn.func4(0xc0420c6870, 0xf13040, 0xc0420381f0, 0xc04238f980, 0xc0423ae3c0)
        /usr/local/go/src/net/http/transport.go:885 +0x7f
created by net/http.(*Transport).getConn
        /usr/local/go/src/net/http/transport.go:887 +0x3a8

goroutine 1 [select]:
github.com/docker/docker/vendor/golang.org/x/net/context/ctxhttp.Do(0xf13300, 0xc0420393e8, 0xc04238f920, 0xc0420c6960, 0xc0420c6960, 0xc04216b9e0, 0x599f4c)
        /go/src/github.com/docker/docker/vendor/golang.org/x/net/context/ctxhttp/ctxhttp.go:55 +0x40a
github.com/docker/docker/client.(*Client).doRequest(0xc0423b2000, 0xf13300, 0xc0420393e8, 0xc0420c6960, 0x6, 0x0, 0x0, 0x0, 0xc0420c6960, 0x0)
        /go/src/github.com/docker/docker/client/request.go:127 +0x75
github.com/docker/docker/client.(*Client).Ping(0xc0423b2000, 0xf13300, 0xc0420393e8, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/client/ping.go:17 +0x1d4
github.com/docker/docker/cli/command.(*DockerCli).Initialize(0xc0421a74a0, 0xc042300e80, 0xba9364, 0x6)
        /go/src/github.com/docker/docker/cli/command/cli.go:158 +0x181
main.newDockerCommand.func2(0xc042083680, 0xc04239aae0, 0x0, 0x1, 0x0, 0x0)
        /go/src/github.com/docker/docker/cmd/docker/docker.go:48 +0xa9
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0xc042083680, 0xc04203e3b0, 0x1, 0x1, 0xc042083680, 0xc04203e3b0)
        /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:628 +0x578
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc042083680, 0xc042083b00, 0xc04231ccd0, 0xc042064430)
        /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:742 +0x37e
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(0xc042083680, 0xc042083680, 0xf0ad40)
        /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:695 +0x32
main.main()
        /go/src/github.com/docker/docker/cmd/docker/docker.go:104 +0xeb

goroutine 18 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:116 +0x15e
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x29
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x48

goroutine 19 [select]:
net/http.(*Transport).getConn(0xc0420c6870, 0xc042399640, 0x0, 0xba78bf, 0x4, 0xc042399660, 0x19, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:890 +0x9d3
net/http.(*Transport).RoundTrip(0xc0420c6870, 0xc0420c6960, 0xc0420c6870, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:367 +0x31a
net/http.send(0xc0420c6960, 0xf0a700, 0xc0420c6870, 0x0, 0x0, 0x0, 0x8, 0xc042064560, 0x411d3f)
        /usr/local/go/src/net/http/client.go:256 +0x166
net/http.(*Client).send(0xc04238f920, 0xc0420c6960, 0x0, 0x0, 0x0, 0xc042064560, 0x0, 0x1)
        /usr/local/go/src/net/http/client.go:146 +0x109
net/http.(*Client).doFollowingRedirects(0xc04238f920, 0xc0420c6960, 0xc2b7e0, 0x3, 0x1, 0x0)
        /usr/local/go/src/net/http/client.go:528 +0x5ec
net/http.(*Client).Do(0xc04238f920, 0xc0420c6960, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:184 +0x1f1
github.com/docker/docker/vendor/golang.org/x/net/context/ctxhttp.Do.func1(0xc04238f920, 0xc0420c6960, 0xc2b100, 0xc0423ae360)
        /go/src/github.com/docker/docker/vendor/golang.org/x/net/context/ctxhttp/ctxhttp.go:48 +0x40
created by github.com/docker/docker/vendor/golang.org/x/net/context/ctxhttp.Do
        /go/src/github.com/docker/docker/vendor/golang.org/x/net/context/ctxhttp/ctxhttp.go:51 +0xe4

goroutine 33 [syscall, locked to thread]:
syscall.Syscall6(0x7ffc73a46bf0, 0x5, 0x310, 0xc0423b5f5c, 0xc0423b5f60, 0xc0423b5f68, 0xffffffff, 0x0, 0x7ffc6fe13040, 0x1, ...)
        /usr/local/go/src/runtime/syscall_windows.go:174 +0x6b
github.com/docker/docker/vendor/github.com/Microsoft/go-winio.getQueuedCompletionStatus(0x310, 0xc0423b5f5c, 0xc0423b5f60, 0xc0423b5f68, 0xffffffff, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/github.com/Microsoft/go-winio/zsyscall_windows.go:76 +0xc6
github.com/docker/docker/vendor/github.com/Microsoft/go-winio.ioCompletionProcessor(0x310)
        /go/src/github.com/docker/docker/vendor/github.com/Microsoft/go-winio/file.go:129 +0x82
created by github.com/docker/docker/vendor/github.com/Microsoft/go-winio.initIo
        /go/src/github.com/docker/docker/vendor/github.com/Microsoft/go-winio/file.go:57 +0x87
rax     0x0
rbx     0xc042030368
rcx     0x30c
rdi     0x229000
rsi     0xc0423bb7a0
rbp     0xc0423bb750
rsp     0x124fd98
r8      0x1
r9      0x0
r10     0x30c
r11     0x12c89c8
r12     0x0
r13     0xd3
r14     0xc27993
r15     0x3
rip     0x18000890a
rflags  0x10246
cs      0x33
fs      0x53
gs      0x2b

**Comment by friism** [comment]
Do you have WebCompanion installed? https://github.com/docker/docker/issues/27423#issuecomment-278292231

**Comment by nancwang** [comment]
Thanks friism! removing WebCompanion makes docker work but my IE got issue. I can live with Firefox.

**Comment by rneugeba** [comment]
thanks for reporting. Closing as a dup of https://github.com/docker/docker/issues/27423

**Comment by QaiserAli** [comment]
Thank you @friism. Removing WebCampanion fixed the issue for me.
