### ISSUE TITLE
Unable to ping to external database from docker container after installing the kubernetes. it works if uninstall kubernetes and reset the docker windows to factory settings.

### ISSUE THREAD

**Issue by areddy31** [docker/for-win#4852]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by anithaaduri** [comment]
I am using windows 10 .
