### ISSUE TITLE
Docker runs on start up and everytime it starts to run I just got this error and can never run the Docker

### ISSUE THREAD

**Issue by raylucker** [docker/for-win#4859]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A4DD0417-8102-492E-8CEA-E39A86AC8B16/20191003014644

### Expected behavior
Docker runs smoothly

### Actual behavior
Error, docker cant run

### Information

  - Windows Version: 10 Pro
  - Docker Desktop Version: 19.03.2, build 6a30dfc
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. Starting my PC
  2. Start up docker runs
  3. Error

**Comment by MythreyaK** [comment]
Could you show the output of `bcdedit`?

**Comment by raylucker** [comment]
> Could you show the output of `bcdedit`?


![bcdedit](https://user-images.githubusercontent.com/15060104/66449341-f04f0480-ea7e-11e9-8d20-c33d04834e9b.JPG)

**Comment by MythreyaK** [comment]
That looks OK! 
Could you show the full error message?
