### ISSUE TITLE
Docker memory issue?? 

### ISSUE THREAD

**Issue by eferias** [docker/for-win#486]
### Expected behavior
to run
### Actual behavior
doesn't run
### Information
says that i am out of memory, however i am trying to run it on a brand new surface 4 pro and i have over 75% of my hard drive free. under advanced settings, it shows that the memory is being maxed out at 2048gb. every other system that runs docker (that i've seen) shows its using at least 2gb but it wont let me pass 2048 gb. can i modify it so i can use 2gb? plz help

  - C2054543-3058-4DE6-9349-800E2F19EF99/2017-02-10_15-07-42

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by rneugeba** [comment]
The memory referred to in the error message is RAM not the hard disk. Your system seems to have only 4GB of memory which is a "bit tight" to run a Linux VM which is configured by default to use 2GB. You can adjust the memory for the VM in the settings menu under the advanced tab. Note, while you can reduce the memory used by the VM it may have a performance impact or cause other issues.

I'm closing this issue but please comment/re-open if there are additional issues

<img width="833" alt="screen shot 2017-02-10 at 22 45 10" src="https://cloud.githubusercontent.com/assets/3338098/22847095/de280da4-efe2-11e6-85ac-41a1932d5f55.png">
