### ISSUE TITLE
lifecycle-controller-api eats a lot of CPU sometime

### ISSUE THREAD

**Issue by 19317362** [docker/for-win#4865]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: CAA4EF6F-E662-40F2-8070-9496C6176459/20191003201244

### Expected behavior
CPU normal

### Actual behavior
Takes  a lot of CPU of my laptop. 

### Information

  - Windows Version: Win10 Insider 10.0.18990.1
  - Docker Desktop Version: WSL2 Technical Preview
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1.  export ubuntu for a backup
        wsl --export Ubuntu backup01.tar
  2.  wsl report a local network broken

  3.   The process named lifecycle-controller-api eats a lot of CPU. Which cause the CPU fan make a big noise (laptop).

**Comment by lukas-wg2** [comment]
I also have this issue, lifecycle-controller-api.exe uses 20-25% constantly. I have tried to restart Docker, my machine but it remains at high CPU usage. I currently have no running containers. I'm using WSL 2 and the technical preview. When Docker Engine for WSL 2 fails to start, it doesn't use any CPU.
