### ISSUE TITLE
Docker checkpoints are not available on Windows

### ISSUE THREAD

**Issue by conioh** [docker/for-win#4867]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D3085E89-6D67-4B4D-82DB-9BD1FB1EF318/20191003215007

### Expected behavior
Docker checkpoints should be available for Linux containers and for Windows container running under Hyper-V isolation.

### Actual behavior
Docker checkpoints aren't available at all:
```
C:\>docker checkpoint
docker checkpoint is only supported on a Docker daemon running on linux, but the Docker daemon is running on windows

C:\>docker checkpoint --help
docker checkpoint is only supported on a Docker daemon running on linux, but the Docker daemon is running on windows
```

### Information
  - Windows Version: Windows 10 Pro 1903 x64 (18362.356)
  - Docker Desktop Version: 2.1.0.3 (38240)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

Where the daemon runs sounds pretty irrelevant.
- If we're running a Linux container we're inside a Linux VM, so CRIU should be available to suspend and resume the processes there.
- If we're running a Windows container under Hyper-V isolation we should be able to take a snapshot just like Hyper-V can. (This argument applies to LCOW too, but perhaps implementing through CRIU like on Linux is preferable.)
- Only if we're running a Windows container using process isolation there's no way yet to suspend and resume processes.

Even if you won't support either of the scenarios, it should still be documented. What other commands will suddenly not work on Windows? What about `docker save`?...

### Steps to reproduce the behavior
```
C:\>docker checkpoint
docker checkpoint is only supported on a Docker daemon running on linux, but the Docker daemon is running on windows

C:\>docker checkpoint --help
docker checkpoint is only supported on a Docker daemon running on linux, but the Docker daemon is running on windows
```

**Comment by stephen-turner** [comment]
This is an engine feature request, please file in moby/moby. (Sorry, I would move it there but github doesn't allow it).

**Comment by conioh** [comment]
> This is an engine feature request, please file in moby/moby. (Sorry, I would move it there but github doesn't allow it).

@stephen-turner 
This has nothing to do with Moby and everything to do with Docker. I never went to the Moby website. I went to Docker's. I downloaded Docker. From the Docker website. According to the instructions on the Docker website. And Docker is the thing that doesn't work as the docs on https://docs.docker.com say.

Moby isn't the product I'm using. It's the underlying infrastructure. I never used Moby directly. Moreover, the moby/moby GH page explicitly says:

> ***The Moby project is not intended as a location for support or feature requests for Docker products***, but as a place for contributors to work on open source code, fix bugs, and make the code more useful. The releases are supported by the maintainers, community and users, on a best efforts basis only, and are not intended for customers who want enterprise or commercial support; Docker EE is the appropriate product for these use cases.

I'm really not sure whether this is an extremely sophisticated form of trolling or are you serious.

The documentation issue is certainly a Docker issue, or is Moby responsible for the lies on http://docs.docker.com? If *Docker* doesn't support something don't lie and say it does. You can't blame Moby for this.

**Comment by stephen-turner** [comment]
I'm not trolling. It's not a Docker Desktop issue, because we are only importing the engine as an upstream.

If you're asking for an Engine feature request, it belongs in https://github.com/moby/moby.

If you have a documentation bug, it belongs in https://github.com/docker/docker.github.io.

Unfortunately github doesn't allow me to move the tickets to another repo.

**Comment by conioh** [comment]
@stephen-turner There seems to be a communication problem here.

You seem to think that I can can and should triage the problem, and decide should the mismatch between the documentation and the behavior resolved by...
- changing the documentation (saying that docker checkpoints are unsupported on Windows hosts);
- changing the behavior (making docker checkpoints work on Windows hosts), or 
- both (fixing docker so that checkpoints work on LCOW containers and Hyper-V isolation containers and fix the documentation to note that checkpoints are not supported or process isolation containers).

Obviously I can't do that, and even if I could I shouldn't have to. That's your job, not mine. Maybe you'd want to assign people to the bug or do you expect to fix all of it myself and open a PR?

I expect you (Docker, Inc.; not necessarily you personally) to do that. I can't and I won't do your job for you.

![source](https://user-images.githubusercontent.com/10606081/68342438-43a28a00-00f3-11ea-87b2-883cd86eb11d.gif)


Moreover, this issue isn't different from hundreds of other issues here that concern the "docker engine" rather than your fancy tray icon, and they weren't sent off to the Moby repo. For example: #2209, #1960, #1916, #1787, etc.

What I'm seeing here are repeating (#4868, #4041) grotesque attempts by multiple Dokcer, Inc. employees (at least yourself and @mikeparker, but I suspect many more) to dodge their responsibilities and not do their jobs by making pathetic nonsense excuses.

I see a bug in Docker - I report it to Docker, Inc. It's not my responsibility to decide how the bug should be fixed, and even if I made that decision, there's no reason to assume Docker, Inc. and its employees would follow it.

Since Docker, Inc. persistently refuses to address bug reports and instead prefers the path of b.s. excuses I am left with no choice but to recommend to my employers not to buy under any circumstances Docker, Inc.'s "Enterprise" offerings with their supposed "Technical Support SLA" and what not.

You have demonstrated repeatedly that you will not address bugs and instead look for any excuse - nonsensical as it may be - to do whatever it is that you do there instead of working. You can't be trusted to actually provide support and I'm recommending all of my employers not to fall for this scam and pay you for what will never be supplied.
