### ISSUE TITLE
Docker stuck in "Docker is starting" state

### ISSUE THREAD

**Issue by mmisztal1980** [docker/for-win#487]
### Expected behavior
Docker should start, and the Windowed-app should be usable. CLI should be usable, and a small Linux VM should be present in Hyper-V.

### Actual behavior
Docker is stuck in starting state, and most of the options in the windowed app are frozen. The tray icon says "docker is starting" and it doesn't change. Attempts to run a container result with an error in the CLI. No Moby-Linux VM is present in Hyper-V

![desktop](http://imageshack.com/a/img921/5412/iR5Lxq.png)

```
PS C:\Windows\system32> get-computerinfo *hyper*


CsHypervisorPresent                               :
HyperVisorPresent                                 :
HyperVRequirementDataExecutionPreventionAvailable :
HyperVRequirementSecondLevelAddressTranslation    :
HyperVRequirementVirtualizationFirmwareEnabled    :
HyperVRequirementVMMonitorModeExtensions          :

```

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
    **5239E3DB-D0D2-47AE-B158-5D03C5A0619A/2017-02-10_22-19-15**
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. Start the Machine
  2. Observe the Docker tray icon being stuck in "Starting" state.

**Comment by mmisztal1980** [comment]
**Update**
I've uninstalled Hyper-V and rebooted the machine. Docker has picked this up and prompted me to enable Hyper-V - which I did. after a reboot the issue persists.

**Comment by rneugeba** [comment]
@mmisztal1980 thanks for your report. You seem to have the exact same error message as in #482. I'm closing this as a duplicate. I've mentioned you on that issue so that you should get updates. Could you try what I suggested in: https://github.com/docker/for-win/issues/482#issuecomment-278993095

**Comment by stiv-yakovenko** [comment]
I have same problem. How can I fix it?

**Comment by Danrrodrigues** [comment]
**Work for me in powersheell in 17/10/2018**

 **It looks like Hyper-V didn't get installed correctly either**
Try to remove them, then install manually to see if that helps. Make sure you run powershell as an admin

- Disable-WindowsOptionalFeature -FeatureName microsoft-hyper-v -online
  - (wait, sometimes until now you have decided, if not, continue)
  - restart-computer
- Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All
 - restart-computer 
- Enable-WindowsOptionalFeature -Online -FeatureName Containers -All

or

 - run MOFCOMP %SYSTEMROOT%\System32\WindowsVirtualization.V2.mof in powershell 
 - restarting the Hyper-V Management service
