### ISSUE TITLE
Unable to launch docker on windows 10, everytime I get a crash error

### ISSUE THREAD

**Issue by sainadh89** [docker/for-win#4874]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker expected to launch as usual 

### Actual behavior
Docker crashes

### Information

  - Windows Version: Windows 10 Pro Build 18362
  - Docker Desktop Version: 2.1.0.1 (37199)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No 

### Steps to reproduce the behavior

  1.Diagnostic ID 8E44639A-3687-4DAF-A205-4F0773F6750B/20191005090817
  2. ...

**Comment by AliagaMusayev** [comment]
Did you get this error?
Hyper-V was unable to find a virtual switch with name “DockerNAT”

**Comment by sainadh89** [comment]
no, I did not get the error 'Hyper-V was unable to find a virtual switch with name “DockerNAT”'

I was not able to get to the bottom of the issue, and I happened to swap my HDD with SSD, as part of that I had to do a fresh install of Windows10 pro. From then on I did not face any issues and docker is running smoothly. 

Thanks for taking time to look into this.
