### ISSUE TITLE
WSL2 engine is stopped. Settings or logs are non-responsive

### ISSUE THREAD

**Issue by OriYosefiMSFT** [docker/for-win#4887]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID:
EEA65468-412F-440F-AFE4-7E03B8239259/20191007172546
### Expected behavior
Docker info in WSL Ubuntu fails with "ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"

Opening the `WSL 2 Tech Preview` option:
Docker Engine WSL2 is marked as stopped, the `settings` page is stuck in "loading" and the logs page I non responsive

### Actual behavior
For all the above to work

### Information

  - Windows Version:
10.0.18995
  - Docker Desktop Version:
2.1.3.0 (38275)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
No
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by joemaller** [comment]
Roll back to 2.1.2.0, download link is here:  [Docker Desktop Community 2.1.2.0](https://docs.docker.com/docker-for-windows/edge-release-notes/#docker-desktop-community-2120)

https://github.com/docker/for-win/issues/4734
