### ISSUE TITLE
docker-machine created  with driver hyperv could not  connecting to exported ports

### ISSUE THREAD

**Issue by DongyueWang** [docker/for-win#489]
### Expected behavior
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env manager
### Actual behavior
Setting Docker configuration on the remote daemon...

This machine has been allocated an IP address, but Docker Machine could not
reach it successfully.

SSH for the machine should still work, but connecting to exposed ports, such as
the Docker daemon port (usually <ip>:2376), may not work properly.

You may need to add the route manually, or use another related workaround.

This could be due to a VPN, proxy, or host file configuration issue.

You also might want to clear any VirtualBox host only interfaces you are not using.
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env manager

### Information

  - FD5180E0-966C-458A-8A01-A0E59983FE74/2017-02-12_14-29-06
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1.  docker-machine create --driver hyperv manager
  2. ...

**Comment by friism** [comment]
You're probably missing `--hyperv-virtual-switch`. See this: https://github.com/docker/labs/blob/master/swarm-mode/beginner-tutorial/swarm-node-hyperv-setup.ps1

Could I ask you to please close and re-open this on the docker-machine repo? https://github.com/docker/machine/

**Comment by DongyueWang** [comment]
the hyperv-virtual-switch is DockerNAT which is internal net type.
should I create a virtual switch of external net type ?

2017-02-12 16:58 GMT+01:00 Michael Friis <notifications@github.com>:
