### ISSUE TITLE
DockerDesktopVM failed to start on Windows Server 2019

### ISSUE THREAD

**Issue by ananthoju** [docker/for-win#4890]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. Enabled Hyper-V Host Service and VMM
  2. Trying to run docket desktop and seeing below crash issue

Unable to start - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'DockerDesktopVM' failed to start.

Failed to start the virtual machine 'DockerDesktopVM' because one of the Hyper-V components is not running.

'DockerDesktopVM' failed to start. (Virtual machine ID 9724CB53-61AF-49C5-96FD-A266516F8F12)

The Virtual Machine Management Service failed to start the virtual machine 'DockerDesktopVM' because one of the Hyper-V components is not running (Virtual machine ID 9724CB53-61AF-49C5-96FD-A266516F8F12).

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

**Comment by jamir-araujo** [comment]
I'm having the same issue. I've tried to start the VM from the Hyper-V Manager and same error appears.

```
An error occurred while attempting to start the selected virtual machine(s).

'DockerDesktopVM' failed to start.

Failed to start the virtual machine 'DockerDesktopVM' because one of the Hyper-V components is not running.

'DockerDesktopVM' failed to start. (Virtual machine ID 07EF586D-516B-4D7A-9779-9C79F1EDFAC3)

The Virtual Machine Management Service failed to start the virtual machine 'DockerDesktopVM' because one of the Hyper-V components is not running (Virtual machine ID 07EF586D-516B-4D7A-9779-9C79F1EDFAC3).
```

My `docker version`

```
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf5
 Built:             Thu Oct 17 23:44:48 2019
 OS/Arch:           windows/amd64
 Experimental:      false
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

I'm running Docker Desktop 2.1.0.4 no a Windows Server 2019 1809 VM.

**Comment by zishanumar** [comment]
> I'm having the same issue. I've tried to start the VM from the Hyper-V Manager and same error appears.
> An error occurred while attempting to start the selected virtual machine(s).
> 
> 'DockerDesktopVM' failed to start.
> 
> Failed to start the virtual machine 'DockerDesktopVM' because one of the Hyper-V components is not running.
> 
> 'DockerDesktopVM' failed to start. (Virtual machine ID 07EF586D-516B-4D7A-9779-9C79F1EDFAC3)
> 
> The Virtual Machine Management Service failed to start the virtual machine 'DockerDesktopVM' because one of the Hyper-V components is not running (Virtual machine ID 07EF586D-516B-4D7A-9779-9C79F1EDFAC3).
> 
> My docker version
> Client: Docker Engine - Community
>  Version:           19.03.4
>  API version:       1.40
>  Go version:        go1.12.10
>  Git commit:        9013bf5
>  Built:             Thu Oct 17 23:44:48 2019
>  OS/Arch:           windows/amd64
>  Experimental:      false
> error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
> 
> I'm running Docker Desktop 2.1.0.4 no a Windows Server 2019 1809 VM.

I am also facing the same issue :(

**Comment by jamir-araujo** [comment]
I managed to fix mine. 

The Nested Virtualization was not enabled on my Windows Server 2019 VM.

If you are having the same issue, you have to shut down your Windows Server VM, go to the VM manager and enable the Nested Virtualization feature for this VM.

I've done this and its working for me.

**Comment by vladneyo** [comment]
I have the same issue with:
- AWS EC2 Windows Server 2019 with Containers (tried on t2.micro, t3a.large)
- Docker version 19.03.5, build 2ee0c57608

Enabling Nested Virtualization **didn't work** there.

Also switching docker to Linux containers manually causes the following error:
```
Unable to start Hyper-V VM: 'DockerDesktopVM' failed to start.

Failed to start the virtual machine 'DockerDesktopVM' because one of the Hyper-V components is not running.

'DockerDesktopVM' failed to start. (Virtual machine ID CF827929-048A-4AFD-8C73-6E3D5BAB1A5D)

The Virtual Machine Management Service failed to start the virtual machine 'DockerDesktopVM' because one of the Hyper-V components is not running (Virtual machine ID CF827929-048A-4AFD-8C73-6E3D5BAB1A5D).
at Start-MobyLinuxVM, <No file>: line 688
at <ScriptBlock>, <No file>: line 811

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.<>c__DisplayClass39_0.<SwitchDaemon>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()
```

Windows containers are okay.
