### ISSUE TITLE
Docker is not running in Ubuntu WSL(Windows Subsytem for Linux)

### ISSUE THREAD

**Issue by venkatesh1753** [docker/for-win#4893]
I am using WSL and installed ubuntu. I have installed docker in ubuntu but docker is not running..
I restarted several times, but nothing is working..
Please find the attached screenshot and please help me to resolve this issue..
<img width="659" alt="ubuntu" src="https://user-images.githubusercontent.com/29490565/66451687-8d804d80-ea2b-11e9-9d66-90db6d21b697.PNG">

**Comment by avinoamsn** [comment]
see https://github.com/docker/for-win/issues/4887. Also, (this guide)[https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly] may be helpful if you're still having trouble.
