### ISSUE TITLE
Docker takes forever to start

### ISSUE THREAD

**Issue by Mikerad1** [docker/for-win#4896]
- [x] I have tried with the latest version of my channel (Stable)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 928FCE1E-594C-4FB6-A81E-97CC9D736E48/20191009074008

### Expected behavior
Docker start on start up
### Actual behavior
It stays in a starting state
### Information

  - Windows Version: Windows 10
  - Docker Desktop Version: 2.1.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

Dont know how to reproduce. it just happens
  1. ...
  2. ...

**Comment by mikeparker** [comment]
Hard to tell from your logs but there is a Hyper-V VM timestamp which looks like it was running before you booted docker desktop. The timestamps are all over the place too. Was your machine sent to sleep before docker had finished booting maybe?

I would try opening Hyper-V Manager directly and removing the VM then restarting your computer and rebooting docker desktop. You could also try switching from Linux containers -> Windows containers, that may clear up the VM.
