### ISSUE TITLE
Open source Docker for Windows documentation

### ISSUE THREAD

**Issue by bbodenmiller** [docker/for-win#49]
It appears the source of https://docs.docker.com/docker-for-windows/ is not on GitHub. Could that be open sourced so we can suggest improvements?

**Comment by rneugeba** [comment]
@bbodenmiller thanks for the suggestion. I think it would be a good idea. I'm not fully familiar with the docs process, but I contacted some people and we'll investigate

**Comment by rneugeba** [comment]
A quick update. We are working on putting all the documentation up on github, but this is a bigger task. For now we will provide a feedback mechanism.

/cc @londoncalling

**Comment by rneugeba** [comment]
@bbodenmiller the docs are now at: https://github.com/docker/docker.github.io
and we accept PRs :)

Thanks for the suggestion, closing
