### ISSUE TITLE
Cannot define volume via Dockerfile

### ISSUE THREAD

**Issue by minherz** [docker/for-win#490]
### Expected behavior
When creating a docker image with volume the image should be created.

### Actual behavior
An error `Unrecognised volume spec: invalid volume specification: '\test1'` is shown at step of execution of the `VOLUME` command.

### Information

  - Diagnostic ID: F9F388E9-7AB0-4CE8-BD59-045CF28124A7/2017-02-12_16-18-51
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - Host distribution: Version 1.13.1-beta42 (10069)
  - Windows version: Windows 10 x64 Enterprise Version 1607 (OS Build 14393.693)

The docker is running in **Windows containers** mode.

### Steps to reproduce the behavior

  1. Create a `Dockerfile` with the following content in a working directory (e.g. C:\Work)

```
#
# Dockerfile for problem reproducing
#
FROM microsoft/dotnet:nanoserver

RUN mkdir /test1
VOLUME /test1

CMD ["CMD"]
```

  2. Change the current directory to be C:\Work
  3. Execute `docker build . -t test`

**Comment by rneugeba** [comment]
Thanks for the report. Looks like two things are missing, the drive letter and I think you also need to specify/override the escape character. This:
```
# escape=`
FROM microsoft/dotnet:nanoserver

RUN mkdir c:\test1
VOLUME c:\test1

CMD ["CMD"]
```
works for me.

@friism do have a place where we document common pitfalls between Unix/Linux and Windows Dockerfiles?

**Comment by minherz** [comment]
Thank you. The suggest script works. The same syntax (standard windows path syntax) works when mounting the volume to shared folder with `docker run` command.
