### ISSUE TITLE
Containers do not restart after windows updates despite having --restart unless-stopped policy defined

### ISSUE THREAD

**Issue by dewalds** [docker/for-win#4902]
Hi All,

We're encountering an issue on Windows Server 2019 with docker 19.03.1 and 19.03.2 where, once windows restarts due to updates, docker daemon is running but containers are not despite having a --restart unless-stopped policy defined.

### Expected behavior
Containers should be started when windows restarts.
### Actual behavior
Containers are not running
### Information
PS C:\Users\nqrgn7d> docker version
Client: Docker Engine - Enterprise
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        f660560464
 Built:             07/25/2019 20:59:52
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.5
  Git commit:       f660560464
  Built:            07/25/2019 20:57:41
  OS/Arch:          windows/amd64
  Experimental:     true

### After restarting all containers

PS C:\Users\nqrgn7d> docker info
Client:
 Debug Mode: false
 Plugins:
  cluster: Manage Docker clusters (Docker Inc., v1.0.1)

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 19.03.1
 Storage Driver: windowsfilter (windows) lcow (linux)
  Windows:
  LCOW:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics l2bridge l2tunnel nat null overlay transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.805)
 OSType: windows
 Architecture: x86_64
 CPUs: 4
 Total Memory: 16GiB
 Name: nqrgn7d-vm0
 ID: GEQF:3XQF:FUV3:TCSQ:MFKH:MESN:OGFS:BI2K:VR5V:CLAZ:GC7H:WBBG
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

### docker inspect of a container
"RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            **},**

### Steps to reproduce the behavior
  1. Create a container
  2. Install windows updates on an Azure Virtual Machine
  3. Once windows restarts, containers are in a stopped state.

**Comment by mat007** [comment]
This does not look like an issue with Docker Desktop but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place?
