### ISSUE TITLE
Sharing Windows 10; Firewall problem (firewall disabled).

### ISSUE THREAD

**Issue by eliezeralmeida** [docker/for-win#491]
### Expected behavior
Disk Sharing C:

### Actual behavior
Firewall Blocking; But my firewall is disabled!

### Information
Diagnostic ID: B0370B99-0420-4F97-8E6F-29AD4C0F0FA9/2017-02-12_18-06-59
Docker Version: Version 1.13.1 (10072)
Windows Version: Windows 10 Pro Insider Preview, Build: 15031

### Steps to reproduce the behavior

1 - Right click on the Docker icon
2 - Click Settings
3 - Cripple Frame C:
4 - Click Apply

#### Log information
[docker-log.txt](https://github.com/docker/for-win/files/769594/docker-log.txt)

#### ScreenShot behavior
![docker-shared-firewall](https://cloud.githubusercontent.com/assets/2786448/22865619/0cbc1170-f14f-11e6-8203-5f014d3a2f64.png)

**Comment by eliezeralmeida** [comment]
Apparently the problem is with the compilation Preview Insider;
I looked at the issues again and found something similar here # 355;

If this is really the problem, sorry for the issue.

**Comment by rneugeba** [comment]
I'm on insider build 15031 and I can access shared drives with the firewall turned off and on.

Do you have any other AV or firewall software installed?

**Comment by eliezeralmeida** [comment]
I have no other firewall installed.
I use only Microsoft Antivirus

**Comment by eliezeralmeida** [comment]
I tried this solution without success.
[#355 issuecomment: 271889419](https://github.com/docker/for-win/issues/355#issuecomment-271889419)

**Comment by dgageot** [comment]
Hi @eliezeralmeida, we've tried to fix this issue in a test release that can be downloaded here: https://download-stage.docker.com/win/samba-experiment/10154/InstallDocker.msi

*Warning: This version will not auto-update to a newer version. It's only meant for testing. You must uninstall the version you have currently installed before you install this test version.*

**Comment by eliezeralmeida** [comment]
> Hi @eliezeralmeida, we've tried to fix this issue in a test release that can be downloaded here: https://download-stage.docker.com/win/samba-experiment/10154/InstallDocker.msi
> 
> Warning: This version will not auto-update to a newer version. It's only meant for testing. You must uninstall the version you have currently installed before you install this test version.

Did not work!
Same behavior. I tried with Firewall on and off.

Log: [docker-log.txt](https://github.com/docker/for-win/files/790176/docker-log.txt)
Diagnostic: B0370B99-0420-4F97-8E6F-29AD4C0F0FA9/2017-02-21_10-09-31

**Comment by sazwqa** [comment]
Didn't work. Diagnostic ID: 42BF299E-4D59-4211-B09B-E753A1131C3B/2017-02-21_21-38-26

**Comment by dgageot** [comment]
@eliezeralmeida @sazwqa Sorry to hear that. We'll keep you posted when we have another version to try. Thanks for your help!

**Comment by eliezeralmeida** [comment]
@dgageot if you need me to do some testing, just let me know, I'll be happy to help.

**Comment by ctaggart** [comment]
A coworker just ran into this issue. I had him turn off the Windows Firewall for troubleshooting. It did not help. I am having him uninstall Docker and reinstall next. He was on 1.13. I had him upgrade to 1.17. The problem occurred in both versions.

**Comment by ctaggart** [comment]
We reset to factory defaults. Docker then crashed with this diagnostic report 6F06099B-5F7C-4130-9D1C-3CBF83817D4F/2017-05-09_08-23-30.  After restarting again it worked.

**Comment by eliezeralmeida** [comment]
I tried again and now everything is ok.
I do not know exactly which version was working again.

My SO Version: Windows 10 Pro Insider Preview: Versão 10.0.16232 Compilação 16232
My Docker Version: 2.0.12627

**Comment by perlatsp** [comment]
I had the same issue for days... tried everything, uninstall and install again nothing worked.

I fixed it by disabling Windows Defender for docker Nat network and after that reset Docker to factory defaults. I don't know which of these two fixed the problem, but it is working now.

**Comment by dhaigvip** [comment]
After trying various settings, finally it worked for me.
1. Network and Sharing center --> vEthernet(DockerNAT)-->Properties
2. Uncheck and Check  again - File and Printer sharing for Microsoft networs.
3. Move to "Sharing" Tab --> Check "Allow other network users " --> vEthernet (nat)

**Comment by sanditriana** [comment]
i had simillar issue. 
before it. i disabled vEthernet(DockerNAT). and just enabled it. and somehow it works :).

can someone explain why its working?
ty

**Comment by IonelLupu** [comment]
@ghost @sanditriana  it still doesn't work :/
