### ISSUE TITLE
Error when switching to Linux container

### ISSUE THREAD

**Issue by Nephelo** [docker/for-win#493]
### Expected behavior
Switch to Linux containers will start docker deamon.

### Actual behavior
Error when switching to Linux containers:
`Unable to create: Der ausgeführte Befehl wurde beendet, da die Einstellungsvariable "ErrorActionPreference" oder ein allgemeiner Parameter auf "Stop" festgelegt ist: Fehler beim Erstellen eines neuen virtuellen Computers.

MobyLinuxVM: Fehler beim Erstellen..
bei New-MobyLinuxVM, <Keine Datei>: Zeile 197
bei <ScriptBlock>, <Keine Datei>: Zeile 375
   bei Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   bei Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   bei Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   bei Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)`

### Information

  - Diagnostic ID: 67B9DBC2-B068-43BB-9A5A-FA19BCD49A98/2017-02-13_09-12-36
  - Version: 1.13.1-beta42 (10069)
  - OS: Windows 10 Education Build: 14393

### Steps to reproduce the behavior
  - Install docker and switch to Linux container

**Comment by rneugeba** [comment]
Thanks for the report. The diagnostics don't contain anything conclusive, just things like:
```
13.02.2017 08:46:06          16010 Fehler           Fehler beim Vorgang.
13.02.2017 08:46:06          15010 Fehler           Fehler beim Erstelleneines neuen virtuellenComputers.
13.02.2017 08:46:06          19600 Fehler           MobyLinuxVM: Fehler beim Erstellen. (ID des virtuellen Computers: 47E7D39A-7B8C-4379-974A-95EC5F00391B)
```


I see you have several other Hyper-V VMs. Do they work? Can you create new VMs manually without errors. The error comes from `C:\Program Files\Docker\Docker\resources\MobyLinux.ps1` which basically just creates a Linux VM using powershell but fails

**Comment by Nephelo** [comment]
Thank you very much for your help.
Yes, all other VMs worked but I didn't notice that creating a new one fails. The issue was a wrong default configuration of my Hyper-V (the default folder for VMs didn't exist). This resulted in a failure when creating a new VM.

**Comment by rneugeba** [comment]
Great. I think I saw the issue once before with a different user...we should probably add a check for this as the error messages we get are not obvious. Closing

**Comment by blandman** [comment]
I was able to get around this by opening the Hyber-V console, right clicking on the computer name, and stopping the Hyper-V service. Then from the Docker task icon, switch to Linux and avoided errors.

**Comment by creativetechdev** [comment]
its only with the linux containers.

**Comment by creativetechdev** [comment]
done every possible steps but not resolved.
