### ISSUE TITLE
Port forwarding doesn't work

### ISSUE THREAD

**Issue by ksawerykarwacki** [docker/for-win#4935]
Windows 10 build 18999
Docker for Windows 2.1.4.0

If i run container with -p 8080:8080 everything works fine, but if I switch to -p 80 I get:

C:\Program Files\Docker\Docker\resources\bin\docker.exe: Error response from daemon: Ports are not available: /forwards/expose/port returned unexpected status: 500.

**Comment by plubberdink** [comment]
Same issue on macOS 10.14.6
Docker version 2.1.4.0 (39357)

**Comment by rfay** [comment]
Don't bother with 2.1.5.0, it has a different problem, apparently with docker-compose. See https://github.com/docker/compose/issues/6998

**Comment by mat007** [comment]
Thank you for opening this issue!
This bug is being fixed and will the fix will be released as part of the upcoming Edge 2.1.6.0 due around Nov. 13th.

**Comment by ksawerykarwacki** [comment]
Any more info about release date? I would love to try new wsl2 backend but i cannot due to this issue.

**Comment by rfay** [comment]
Yay, fixed in Docker Edge 2.1.6.0, https://docs.docker.com/docker-for-mac/edge-release-notes/ - I haven't tested on Windows but working on macOS.
