### ISSUE TITLE
Docker crashes at startup

### ISSUE THREAD

**Issue by jtinguely** [docker/for-win#4937]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker starts
### Actual behavior
Docker crashes
### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by verglor** [comment]
I wonder how this issue can be resolved without providing any information at all...
