### ISSUE TITLE
Docker Dameon Failed to Start

### ISSUE THREAD

**Issue by venkatramvelmurugan** [docker/for-win#4948]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ... In Windows 10 OS, Go to Docker Desktop App
  2. ... click the Docker Desktop App
  3.    Docker Failed to start and display the above messages.

**Comment by alafhamad** [comment]
same issue with me, I was working just fine

**Comment by alafhamad** [comment]
Diagnostics id B0536932-00CF-4B09-9B8E-BF1539A3CF6F/20191017220312
