### ISSUE TITLE
Docker desktop crashes after windows 10 version 1809 for x64-based system(KB4521862)

### ISSUE THREAD

**Issue by maykalasunderraj** [docker/for-win#4950]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 80DA3FB8-9F18-4111-9B7A-BFE44C6AD250/20191018053713

### Information

  - Windows Version: Windows 10
  - Docker Desktop Version: 
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by maykalasunderraj** [comment]
Diagnostics id 80DA3FB8-9F18-4111-9B7A-BFE44C6AD250/20191018053713

**Comment by alafhamad** [comment]
Diagnostics id B0536932-00CF-4B09-9B8E-BF1539A3CF6F/20191017220312
