### ISSUE TITLE
Is there a settings file for Docker Desktop?

### ISSUE THREAD

**Issue by realmhamdy** [docker/for-win#4953]
I made the mistake of making the allowable RAM to the docker engine 32GB. now i can't start Docker desktop anymore:

![docker-daily](https://user-images.githubusercontent.com/5938078/67092612-fb591180-f1af-11e9-81b8-703c8ed46c2a.jpg)

Now the only option available for me is to **Reset to Factory Defaults** which will erase my images and is something i'd rather not do.

I can't edit back the setting because the settings screen is disabled or not functional.

I tried reducing the memory for DockerDesktop VM in hyper-v manager but Docker keeps resetting it back to 32GB each time it starts up.

Is there a settings file i can edit manually to reduce the VM RAM?

**Comment by stephen-turner** [comment]
Yes, AppData\Roaming\Docker\settings.json.

**Comment by realmhamdy** [comment]
Thanks @stephen-turner. the setting is called `memoryMiB` for reference.
