### ISSUE TITLE
Install fails with There is insufficient disk space to complete operation. more the 100G free on disk

### ISSUE THREAD

**Issue by Keldandorin** [docker/for-win#4954]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Working install exe
### Actual behavior
install failed
### Information
There is insufficient disk space to complete operation. (Exception from HRESULT: 0x80030070 (STG_E_MEDIUMFULL))
   at System.Runtime.InteropServices.ComTypes.IPersistFile.Save(String pszFileName, Boolean fRemember)
   at CommunityInstaller.ShortcutAction.DoAsync(CancellationToken cancelToken)
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackage>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()
  - Windows Version: 1809 build: 17763.805
  - Docker Desktop Version: Docker Desktop 2.1.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: physical machine.

run install both by clicking on exe and running in cmd with local admin run as admin mode

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mat007** [comment]
Can you try again without checking the box to create a shortcut on the desktop?

**Comment by mat007** [comment]
Also, does your machine have more than one drive?

**Comment by Keldandorin** [comment]
Never get the question to create the shortcut on desktop. Only one drive on machine

**Comment by mat007** [comment]
Don’t you get this screen with the check boxes?

![image](https://user-images.githubusercontent.com/2386884/67110293-ada1d080-f1d2-11e9-9077-a52bd691fd0c.png)

Can you paste the content of `%LOCALAPPDATA%\Docker\install-log.txt`?

**Comment by Keldandorin** [comment]
One thing I forgot to tell was that I had a older version of docker installed before so it started as a upgrade. Checked Program and Files that docker is removed and can also see that VM in hyper-v is gone to. It just hit me that I have not restarted my pc. Will try that and then try to install docker again.

**Comment by Keldandorin** [comment]
Restarted computer and tried installing again but no luck there

**Comment by Keldandorin** [comment]
NO I dont get to screen it throw error before that. Cant find a install-log.txt in that folder. Only a log.txt
![image](https://user-images.githubusercontent.com/15968468/67119723-0465d500-f1e8-11e9-8d02-22f524194e04.png)

**Comment by Keldandorin** [comment]
[log.txt](https://github.com/docker/for-win/files/3745283/log.txt)

**Comment by Keldandorin** [comment]
Please,let me know if I can provide any more information.

**Comment by mat007** [comment]
Do you happen to have Controlled folder access enabled?

![image](https://user-images.githubusercontent.com/2386884/67139668-04e78580-f253-11e9-86d9-0344a010a32c.png)

**Comment by Keldandorin** [comment]
That was it..Turned it of and installation work like a charm, Thx alot for help
