### ISSUE TITLE
Docker Failed To Initalize ... after installing Android Emulator (Andy46_.16)

### ISSUE THREAD

**Issue by weavermount** [docker/for-win#496]
### Expected behavior
Docker service / gui loads

### Actual behavior
Docker fails to initialize

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
1EBBE537-6B80-4E7D-ADEE-2C908AB3434B/2017-02-13_10-56-35

  -GUI error message
Object reference not set to an instance of an object.
   at Docker.Program.Run(IReadOnlyCollection`1 args)

- Logs
Version: 1.13.1 (10072)
Channel: Stable
Sha1: 94675c5a765e2c51fba6c10b87e0a1a4ed3dde51
Started on: 2017/02/13 11:12:21.728
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1607
Build: 14393
BuildLabName: 14393.693.amd64fre.rs1_release.161220-1747
File: C:\Users\wwest\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[11:12:21.953][GUI            ][Info   ] Starting...
[11:12:22.422][GUI            ][Error  ] Object reference not set to an instance of an object.
[11:12:40.851][ErrorReportWindow][Info   ] Open logs

### Steps to reproduce the behavior

  1. Installed docker.
  2. Used docker just fine for months
  3. Installed Andy (46.16)
  4. Docker fails to initialize.

I uninstalled the emulator, confirmed that there are no vmware / virtualbox partial installs. Uninstalling and reinstalling docker, and restarting my machine. The error message are a  little to cryptic for me to follow up much at all. Any ideas?

**Comment by friism** [comment]
Android Emulator uses HAXM for virtualization, which is incompatible with Hyper-V (used by Docker for Windows).

**Comment by weavermount** [comment]
well that's something.  Can you suggest a fix for docker?

**Comment by rneugeba** [comment]
Unfortunately, that is not something we can fix easily. Both HAXM and Hyper-V use the Intel virtualisation extensions and only one piece of software can control them. The only fix would be to port Docker for Windows to use HAXM which is a major engineering effort and it would break windows containers as well
