### ISSUE TITLE
Sharing C: drive doesn't work with VPN (Citrix Gateway)

### ISSUE THREAD

**Issue by jccastellana** [docker/for-win#4969]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 50A91E50-ACBB-4175-BABB-EFE6A85BB71E/20191021144708

### Expected behavior

Sharing C: drive works.

### Actual behavior

Sharing C: drive doesn't work.

### Information

  - Is it reproducible? Yes
  - Is the problem new? No
  - Did the problem appear with an update? No

  - Windows Version: 10 version 1803
  - Docker Desktop Version: 2.1.0.4 (latest)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Connect to my company's Citrix Gateway VPN
  1. Right-click on Docker Desktop => Settings => Shared Drives
  2. Check C drive then click on Apply
  3. A window appeared with the message : 

Firewall detected

A firewall is blocking file sharing between Windows and the containers. See documentation for more info.

**Comment by scyto** [comment]
@jccastellana Have you tried enabling   'Local LAN access' in the citrix gateway plugin configuration page?

Without this, by Citrix design, all network traffic is intercepted by the citrix gateway plugin and routed to you corporate network.  I would say this is a Citrix issue not a docker for windows issue.  But not my call :-)

**Comment by djs55** [comment]
@jccastellana thanks for your report. There's a completely new drive sharing mechanism in the edge channel which should be immune to conflicts with VPN clients.

In case it's useful I've written instructions for setting up and testing the new file sharing implementation available in the edge channel here: https://github.com/docker/for-win/issues/5139#issuecomment-559700215

**Comment by stephen-turner** [comment]
This is fixed with the new filesharing implementation in 2.2.0.3, so closing this ticket.
