### ISSUE TITLE
Permission denied on Windows 10 when writing to host volume

### ISSUE THREAD

**Issue by bhabermaas** [docker/for-win#497]
### Expected behavior
It should work. It used to before updating to docker 1.13.0

### Actual behavior
Fails with permission denied. 

### Information
A diagnostic was uploaded with id: A793F06A-2BB2-4848-AECB-269265A747E3/2017-02-13_17-36-24
  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by bhabermaas** [comment]
I have allowed all permissions on the mounted volume.  If I use the CLI to run the container and mount the volume I can write if I chmod 777. 
Using the Remote API, the volume has a bind rw, but unable to write and get permission denied.

**Comment by rneugeba** [comment]
Thanks for the report. Could you provide a concrete example for us to better understand the issue?
thanks

**Comment by bhabermaas** [comment]
Very simple.  This was working and now it isn't.  

PS C:\Users\bihaber> docker run --rm -it -u fmwpltfm -v //d/dockerOutput:/output:rw fmwtest:latest bash
fmwpltfm@ef5fab65723e:/$ cd /output
fmwpltfm@ef5fab65723e:/output$ ls -al
total 4
drwxr-xr-x 2 root root   60 Feb 14 13:20 .
drwxr-xr-x 1 root root 4096 Feb 14 13:27 ..
-rw-r--r-- 1 root root    0 Feb 14 13:20 test
fmwpltfm@ef5fab65723e:/output$ touch test
touch: cannot touch 'test': Permission denied
fmwpltfm@ef5fab65723e:/output$

**Comment by rneugeba** [comment]
When you say it sued to work, which version did you use before? stable or beta channel?
thanks

**Comment by bhabermaas** [comment]
No problem on 1.12 stable.  I upgraded to 1.13.0 and it worked. then I got a notice to update. hasn't worked since.

**Comment by rneugeba** [comment]
I can't reproduce this. I tried your command line above, but it can't find the `fmwtest` image so I use standard ubuntu and use two different users already configured.
```
PS C:\Users\rneugeba> docker run --rm -it -v C:\test:/test ubuntu bash
root@4dadf13b5617:/# id
uid=0(root) gid=0(root) groups=0(root)
root@4dadf13b5617:/# touch /test/foo
root@4dadf13b5617:/# exit
PS C:\Users\rneugeba> docker run --rm -it -u mail -v C:\test:/test ubuntu bash
mail@327a01172745:/$ id
uid=8(mail) gid=8(mail) groups=8(mail)
mail@327a01172745:/$ touch /test/bar
mail@327a01172745:/$ ls -l /test
total 0
-rwxr-xr-x 1 root root 0 Feb 14 13:53 bar
-rwxr-xr-x 1 root root 0 Feb 14 13:52 foo
```
Could you provided the output of `id` when inside your container as user `fmwpltfm`?

We did not change anything with regards to the mounting between 1.13.0 stable and the latest stable. I tried the above on the latest Beta, but again we dod not change anything related to the shared volumes there either

**Comment by bhabermaas** [comment]
Must be a Windows 10 update that is causing it.

**Comment by rneugeba** [comment]
I'm not sure. I've tried on build 10586.672 and 14393.693 (latest RS1 update) and latest insider fast ring build 15031.0 and all three work

**Comment by bhabermaas** [comment]
Seems to be tired to what userid I specify for the container.  I have added that user to windows and given it all access to the disk.  But I still get permission denied.  Is there anyway that I can turn off permission checking for a mount?

**Comment by rneugeba** [comment]
The UID mapping is done by the samba client/server and is not easily changeable.

What is the output of `id` when you are inside the container? 
What is are the permissions on the `/output` directory in the container?

**Comment by bhabermaas** [comment]
If I run without the mount, the permissions look correct - 

PS C:\Users\bihaber> docker run --rm -it fmwtest:latest bash
root@d74e5994d6b7:/# ls -al /test_output
total 8
drwxrwxrwx 1 fmwpltfm root 4096 Aug 23 08:53 .
drwxr-xr-x 1 root     root 4096 Feb 14 14:34 ..
root@d74e5994d6b7:/# exit
exit

If I run it with the mount then the permissions are lost - 

PS C:\Users\bihaber> docker run --rm -it -u fmwpltfm -v //d/dockerOutput:/test_output:rw fmwtest:latest bash
fmwpltfm@a3463248866f:/$ ls -al /test_output
total 4
drwxr-xr-x 2 root root   40 Feb 14 14:10 .
drwxr-xr-x 1 root root 4096 Feb 14 14:34 ..
fmwpltfm@a3463248866f:/$

Why is that?

**Comment by rneugeba** [comment]
because in the first case you are loooking at a local directory in the container and in the second case you are looking at the drectory mounted from the host. These are different directories with different permission settings

**Comment by bhabermaas** [comment]
So how do I get the permissions to agree?  On windows the dockerOutput directory has full access for user fmwpltfm (windows user).

**Comment by bhabermaas** [comment]
![snap1](https://cloud.githubusercontent.com/assets/8658889/22934027/7483a32a-f29b-11e6-987c-e85986d08b22.gif)

**Comment by rneugeba** [comment]
This has little to do with the permissions on the host (ie windows). When you share the drive in Docker for Windows you provide a username/password in the dialog box. This is passed to the Linux VM which uses these credentials to SMB mount the drive. Inside the VM the directories are mounted with the default user and permission (root and 0755).

I'm not entirely sure why this works for me, but not for you. Again, could you provide the output of `id` when in the container. Also, another difference may be, is windows user `fmwpltfm` a local admin or not?

**Comment by bhabermaas** [comment]
Below is the same output but with the user id from container.  I have tried putting the windows user in all different groups but with no affect. 
ALL I WANT TO DO IS HAVE MY PROGRAM RUNNING IN THE CONTAINER BE ABLE TO WRITE ITS OUTPUT TO THE DIRECTORY ON WINDOWS.   

PS C:\Users\bihaber> docker run --rm -it -u fmwpltfm -v //d/dockerOutput:/test_output:rw fmwtest:latest bash
fmwpltfm@2631ad002435:/$ id
uid=735019(fmwpltfm) gid=1000(fmwpltfm) groups=1000(fmwpltfm)
fmwpltfm@2631ad002435:/$ ls -al /test_output
total 4
drwxr-xr-x 2 root root   40 Feb 14 14:10 .
drwxr-xr-x 1 root root 4096 Feb 14 15:12 ..
fmwpltfm@2631ad002435:/$

**Comment by rneugeba** [comment]
I understand what you want to do. No need to use all capital letters. It's rude

**Comment by bhabermaas** [comment]
Sorry I apologize.

**Comment by bhabermaas** [comment]
I uninstalled Docker 1.13.1 and reinstalled Docker 1.12.3 -- problem solved. 
The moral of the story is: Do not update to a newer Docker if the one you have that works!!!
Obviously Docker 1.13 stable isn't as stable as it should be.

**Comment by seydu** [comment]
@bhabermaas How did you downgrade to 1.12?
I am trying to do so but I cannot find that version of docker for Windows.

**Comment by bhabermaas** [comment]
Fortunately I had the earlier download so I could install it after uninstalling 1.13.  You should ask the Docker people where you can get earlier releases.

**Comment by seydu** [comment]
Thank you

**Comment by Johlandabee** [comment]
I've got the same behavior with 17.12.0-ce-rc3-win43 (14802) on Windows 1709.

**Comment by njbotkin** [comment]
Same here on Windows 1709 `10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)`

```
>docker version
Client:
 Version:       17.12.0-ce-rc4
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    6a2c058
 Built: Wed Dec 20 15:53:56 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.12.0-ce-rc4
  API version:  1.35 (minimum version 1.24)
  Go version:   go1.9.2
  Git commit:   6a2c058
  Built:        Wed Dec 20 16:04:19 2017
  OS/Arch:      windows/amd64
  Experimental: true

**Comment by pribilinskiy** [comment]
Same, when this will be fixed?

**Comment by nabossha** [comment]
same issues here, when can we expect a fix?

**Comment by Mnuzz** [comment]
Possible workarounds can be inferred from some of the discussions here. These guys have some clever ideas: https://github.com/wodby/docker4drupal/issues/29

**Comment by don-lab-dc** [comment]
Same issue here. Would love a fix or workaround.

**Comment by bjolar** [comment]
Same issue here, using Docker edge, Win 10 Enterprise od build 14393.1593. Chmod has no effect and can't clone git repos.

**Comment by lchnnl** [comment]
I had the same problem with my version of Docker: 
```
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:22 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:29 2017
  OS/Arch:      linux/amd64
  Experimental: true

```
Eventually managed to get this working:
- Killed and removed the container where the volume is mounted
- Turned off my shared drive in Docker settings
- Then restarted the computer
![image](https://user-images.githubusercontent.com/3322365/36927436-e38bbdb6-1e7d-11e8-9b7b-2933c287e1d2.png)
- After a fresh restart, enabled the shared drive again.
- After enableing I had to provide my windows username + password.
- Started the container, and everything was working.

This method worked for me. Need to check if it'll work for you too.

**Comment by ejo** [comment]
@lchnnl, interesting -- when I try to use the same fix that you just did, disabling and then re-enabling the shared drive does not ask for my credentials.

My docker diagnostic upload: F1A041F4-7A2F-4F74-8C5A-35011595092A/2018-03-09_13-47-28

My Docker for Windows experience has been almost comically bad. Simple, superficially easy tasks like almost any "quick-start" tutorial for docker-compose, wordpress on docker, quickstarts for connecting redis and logging containers and other things to a web server container... All the simple initial tasks are no problem.

But then as soon as the ecosystem ages even a little bit and a few parts of projects have been fired up and down and tinkered with, the trouble begins... trouble that I don't have with docker on its native Linux. Pretty soon I have to `docker system prune` and `docker volume prune` and restart the Docker for Windows system almost every time I want `docker-compose up` to work even for the simplest projects. And not only do I have to do all that cleanup, the cleanup itself has side effects so I often have to cleanup with those prune commands, restart Docker for Windows, then attempt a `docker-compose up` which is already going to fail the first time, then run it a second time for it to work.

The kinds of things that go wrong when I don't go through all that: my webserver container (wordpress or otherwise) can't connect to its associated mysql server in another container. Normally it can, and it never fails on Linux but it sure fails in Docker for Windows. Something is causing leftover network connections or port assignments from previous runs to get in the way of new runs, in a way that is not a problem on Linux. Right now in a Powershell window I am having exactly that problem even after completely resetting the Docker for Windows system and cleaning *everything* and forcing re-creation of my containers. The cleanest start I could get, short of reinstalling Docker for Windows itself, and there's still a connection problem between containers because of some hidden networking problem that this system is explicitly supposed to save me from dealing with. And it does, on Linux.

I am confident that Docker for Windows will overcome these troubles in time, but I am not making a bet on when. For now I will return to doing all my docker-based development using a Linux VM when I'm forced to work on a Windows host, and I will lean toward working on my native Linux boxes when possible. This is not great because I use Adobe Lightroom and Photoshop a lot during the same work sessions as my docker-based projects, and I don't expect these Adobe apps will ever run all that well except on native Windows; I have used them successfully in Wine but results are too slow to be efficient for getting work done.

**Comment by Shurrir** [comment]
I think this is the same issue?
https://github.com/lando/lando/issues/705#issuecomment-366217231

**Comment by wtokumaru** [comment]
Just installed docker toolbox for Windows 10 Home, can not even do the second step of the tutorial because of this: https://docs.docker.com/get-started/part2/

**Comment by dublinus** [comment]
I'm having the same issue as well, latest version of docker. The containers can read from mounted volumes, but I get the permission denied crash as soon as they try to write files.

**Comment by Entrio** [comment]
Exactly same issue here 18.03.1-ce

**Comment by schekili** [comment]
I had the same problem this week. The cause was that I changed my windows session password and it seems that Docker needed to get the new credentials.
To do so, I went to docker settings-> Shared Drives -> uncheked the shared drive then Apply -> Recheck the drive and Apply.  Once done docker asked me to enter my credentials again which I did.
Restarted docker and it started working again

**Comment by LiamKarlMitchell** [comment]
I can not write files inside docker to the mounted locations. WinDocker Version 18.05-0-ce

My user is a member of Administrators and docker-users.
Using a Microsoft account (Email address) to sign in.

I would note that I got other "Administrator Permission" is required when trying to simply delete or move files on my drive using explorer. It was a drive that was in the PC from my old Windows 7 prior to installing new Windows 10.

I edited the advanced security of the drive as I noticed docker-users did not seem to have Full Control or Write access, I have allowed it as such and after a long wait for it to enumerate all files and apply, my docker containers now have write permission.

I've done the whole drive to be safe (do this over night), but it seemed to work just fine on the sub folder I wanted to use as well.

**Comment by eibenm** [comment]
I have also getting this issue for a couple months now.  I have created a "Docker" user in both the Administrators and docker-users user groups.  This user is used for the docker shared drive. 

Many of the comments above reference various permutations of resetting credentials and re-sharing drives.  Trying some of these out, I was able to get the mount working correctly once, but as soon as the container was spun down the issue resurfaced again.

**Comment by masonlr** [comment]
Please see this post: https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly

On the WSL, we created a `.conf` file at `/etc/wsl.conf` with the following content:

```
[automount]
root = /
options = "metadata"
```

After re-starting windows, the docker volume mounts work okay, for example:

```
docker run -it -v "$(pwd)":/home/user/test ubuntu:latest bash
```

**Comment by fakocher** [comment]
I encountered a similar error. I fixed it my resetting the credentials in the Shared Drives settings.

**Comment by Mnuzz** [comment]
@abdennour Comments like those are unhelpful and disrespectful. Not a good fit for Github.

**Comment by wally666** [comment]
Hi guys, try use "Reset credentials" link in the Docker Settings tab:

![image](https://user-images.githubusercontent.com/1333753/47710861-20b5de00-dc34-11e8-8812-0383af682566.png)

it helped for me, docker kept old password, so I had to refresh my credentials.

**Comment by menicolas89** [comment]
I am having this issue and none of the solutions worked for me. frustrated.

**Comment by matheusmaximo** [comment]
Same issue here.

Docker version
`Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:51 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false`


Windows 10 version:
Version 1809 (OS Build 17763.195)

**Comment by VladPks** [comment]
Had the same error in Windows 10 and was able to solve it doing the following (following mostly suggestions from previous posts):

1. stop all docker containers
2. go to my docker directory, first uncheck read-only then go to security and allow full control for all users
3. open docker settings/shared drives, checked the drive containing the docker directory and when pressing the apply button and had to provide my credentials 
4. in cmd used: docker run -p 80:80 -v C:\docker\src:/var/www/html my-container

let me know if this also helped any of you

**Comment by danielchodusov** [comment]
Probably unsafe but fixed the issue for php-fpm

```
version: '3'
services:

    php:
        image: arodax/php7.2-fpm
        volumes:
            - .:/var/www
        command: 'php-fpm -R'
        environment:
            PHP_FPM_USER: root
            PHP_FPM_GROUP: root
```

**Comment by matheusmaximo** [comment]
My problem was because I was trying to use a folder (c:\Users\user_name\AppData) which my Docker user account had no access to.
I gave access to the account on that folder and it works fine for me.

**Comment by raknjak** [comment]
For me it was a combination of solutions above that probably triggered it to work:
- reset credentials on shared drivers
- reboot
- remove read-only from docker folder
- reboot
when I started up my server my ssl config wasn't loading ERR_SSL_PROTOCOL_ERROR
- reboot
- start docker, still ssl failure
- reboot
- it works ... ???

**Comment by ncimino** [comment]
I encountered this same problem, and I am fairly frustrated with what I found.

My C: drive Security user list includes the user account I log into Windows 10 with; However, the directory I was trying to use as a writable volume mount (from my user directory) does not include the user account I log into Windows 10 with, but did include my Microsoft Live account as a user.

I then used my Microsoft Live account credentials to login and bingo I had write access.

My guess is that this is 1) docker is not using the APIs which would work for both Microsoft account and local user authentication, 2) Microsoft is mixing the directory owners of directories making it hard for authentication to be persistent and robust, or more likely 3) some combination of these is what is leading to these problems.

**Comment by KerstenBreuer** [comment]
Encountering the same problem with docker toolbox on Windows 10 Home 1809 signed in with a microsoft account.

We really need this fixed for our project of empowering biologist to do bioinformatic analysis on windows. 

@rn could you please help us with this or assign somebody to this issue?

Thanks and best wishes

**Comment by KerstenBreuer** [comment]
With the non-legacy docker for windows (not docker toolbox), I am getting the same unfortunate behavior.

**Comment by olivier299792458** [comment]
Bump

**Comment by PerArneng** [comment]
I'm also having this problem. I can mount a volume but the process get permission denied when trying to create a file in the mounted directory.

**Comment by Ordiel** [comment]
Is this a newer error, or a Windows update thing (which I did recently). I am also seeing this and seeing another fellow posting here less than 7 hours ago seams suspicious

**Comment by malger** [comment]
I was able to fix the permission issue by creating a local administrator account and use that for the Docker Shared Drives Credentials. With my Domain-user i also was unable to create files/folders in shared directories. Therefore i might suggest some kind of permission setting bug when using domain users.

**Comment by malger** [comment]
i used this guide
https://tomssl.com/2018/01/11/sharing-your-c-drive-with-docker-for-windows-when-using-azure-active-directory-azuread-aad/

**Comment by belousa** [comment]
I fixed this problem permanently by giving the Windows local account Docker the permission to full control the files under the directory I was mounting. My suspicion is that when Docker connects to the C share as itself, Windows checks the permission of each file against the account that was used to authenticate the connection. On my machine, the permissions were Read/Execute for Everyone. I had to add Full Control for Docker for the check to succeed.

**Comment by AlessandroVol23** [comment]
> I was able to fix the permission issue by creating a local administrator account and use that for the Docker Shared Drives Credentials. With my Domain-user i also was unable to create files/folders in shared directories. Therefore i might suspect some kind of permission setting bug when using domain users.

This worked for me. After trying it with a dedicated docker user in administrator group and explicit permissions to the folder (which didn't work).

Just activating local admin account -> setting passwod -> reverting credentials in docker share did work, Thanks! :-)

**Comment by AlessandroVol23** [comment]
> I was able to fix the permission issue by creating a local administrator account and use that for the Docker Shared Drives Credentials. With my Domain-user i also was unable to create files/folders in shared directories. Therefore i might suspect some kind of permission setting bug when using domain users.

This worked for me as well. A Local dedicated docker account with admin privileges didn't work and I have no idea why.

**Comment by ferpega** [comment]
Same here.  I also can mount volumes but the container cannot see files nor create files with the permission denied message.

```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 Kubernetes:
  Version:          v1.10.11
  StackAPI:         v1beta2

```

**Comment by eoriont** [comment]
I believe I have the same problem. I am trying to mount my postgresql db in my host from my pg container, but it can't start because of permission.

```pg-docker | The files belonging to this database system will be owned by user "postgres".

pg-docker | This user must also own the server process.
pg-docker |
pg-docker | The database cluster will be initialized with locale "en_US.utf8".
pg-docker | The default database encoding has accordingly been set to "UTF8".
pg-docker | The default text search configuration will be set to "english".
pg-docker |
pg-docker | Data page checksums are disabled.
pg-docker |
pg-docker | fixing permissions on existing directory /var/lib/postgresql/data ... ok
pg-docker | creating subdirectories ... ok
pg-docker | selecting default max_connections ... 20
pg-docker | selecting default shared_buffers ... 400kB
pg-docker | selecting dynamic shared memory implementation ... posix
pg-docker | creating configuration files ... ok
pg-docker | running bootstrap script ... 2019-06-23 04:40:10.566 UTC [78] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
pg-docker | 2019-06-23 04:40:10.566 UTC [78] HINT:  The server must be started by the user that owns the data directory.
pg-docker | child process exited with exit code 1
pg-docker | initdb: removing contents of data directory "/var/lib/postgresql/data"
pg-docker exited with code 1```

**Comment by eoriont** [comment]
Well, I got around to fixing it today, and I changed this:
```
version: "3"
services:
  db:
    image: postgres
    container_name: pg-docker
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - C:/Users/oriont/Documents/pgdata:/var/lib/postgresql/data
```
to this:

```
version: "3"
services:
  db:
    image: postgres
    container_name: pg-docker
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    external: true
```

And now I don't know where the data is being stored, but it works even if I delete and rebuild the container.
