### ISSUE TITLE
Install fails non-gracefully when kubectl is in use

### ISSUE THREAD

**Issue by matthewhartstonge** [docker/for-win#4973]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
- On upgrade, kubectl should be upgraded first, to detect if it is in use (proxying dashboard)
- The installation process will complain it can't upgrade kubectl and end, leaving the current Docker for desktop installation intact.

### Actual behavior
- Docker for desktop uninstalls Docker.
- Docker for desktop then attempts to upgrade kubectl
- Docker for desktop can't, as the process is in use in the background proxying a kube-dashboard instance.

As such, the user is left in a state where Docker for desktop is now uninstalled, with no way to retry installation, leading to having to fish for a whale in the docker hub/store to obtain the same installation package just downloaded.

### Information

  - Very reproducible, has happened to myself and co-workers over the past 2 docker updates on multiple different machines.
  - Windows Version: Windows 10 1903
  - Docker Desktop Version: 2.1.0.4 (39773)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Install an old version of Docker for Desktop
  2. Proxy to a `kube-dashboard` instance for a cluster
  3. Run "Check for update"
  4. Upgrade Docker for Desktop.

**Comment by whereisaaron** [comment]
@matthewhartstonge just had the same thing.
Every release of the Docker Desktop installer seems more broken than they previous one 😢 
I just don't upgrade any more, if I do it an hour wasted cleaning up the mess the installer makes.
