### ISSUE TITLE
Docker not restart after settings change - forced to restart executes restart after restart

### ISSUE THREAD

**Issue by MaciejBrzozowski** [docker/for-win#4976]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
After value changes an click "Apply" button it should be disabled (should be gray)

### Actual behavior
After value changes an click "Apply" button is not disabled and restarts are chained
Clicking few times creates a chain of restarts. If you click 5 times Docker will restart 5 times.
This happend after closing settings and selecting restart from menu.

### Information
  - Windows Version: 
Win10 Pro 
i7-4770@3,4GHz
32GB RAM

  - Docker Desktop Version: 2.1.0.4 (39773)
Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf5
  Built:            Thu Oct 17 23:50:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
### Steps to reproduce the behavior

Run Docker 
Go to Settings
Increase CPU cores (2 -> 4)
Increase RAM (2GB -> 8GB)
Increase swap to maximum (4GB)

Click Apply - nothing happens 
Click Apply again (few times) - still nothing happend
Restart from menu
Docker starts to restart few times.

**Comment by stickycode** [comment]
I tried to increase the memory and after the restart docker fails to start, with both 2.0.1.3 and 2.0.1.4. I was forced to reinstall to get it running again. The Apply button seemed like it didnt respond but I think its just really slow...
