### ISSUE TITLE
Vmmem high CPU usage - B5EED30B-F016-4CC5-B7C4-94D0D75D14C9/20191022074337

### ISSUE THREAD

**Issue by ghost** [docker/for-win#4977]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [X ] I have uploaded Diagnostics
  - Diagnostics ID: B5EED30B-F016-4CC5-B7C4-94D0D75D14C9/20191022074337

### Actual behavior
Docker vmmem process uses a lot of cpu : more than 60%.

### Information
  - Windows Version:
  - Docker Desktop Version: Docker version 19.03.2, build 6a30dfc
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: NO

### Steps to reproduce the behavior
Here are my docker-compose.yml and dockerfile

[vmmemCPU.zip](https://github.com/docker/for-win/files/3754283/vmmemCPU.zip)

**Comment by Joe-Pena** [comment]
Got the same issue, downgraded to 2.1.2.0 (Not 2.1.3.0, as that version doesn't allow wsl tech preview to start) by downloading the installer for this version from here:

https://download.docker.com/win/edge/38030/Docker%20Desktop%20Installer.exe

after install, CPU usage is back to normal.
