### ISSUE TITLE
Docker Desktop crashes when setting drive share credentials with cmdkey

### ISSUE THREAD

**Issue by npeder** [docker/for-win#4978]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
    - BF1AC00D-0F74-4689-80B9-40569E13D10A/20191022075151 (Stable 2.1.0.4)
    - BF1AC00D-0F74-4689-80B9-40569E13D10A/20191022083633 (Edge 2.1.0.4)

### Expected behavior
That Docker Desktop shares the drive OR at least shows a decent error message and the opportunity to reenter the credentials.

### Actual behavior
Docker Desktop crashes with this error:
```
The parameter is incorrect.


   at System.Security.Cryptography.ProtectedData.Unprotect(Byte[] encryptedData, Byte[] optionalEntropy, DataProtectionScope scope)
   at Docker.WPF.Credentials.MountCredentialAsker.DecryptPassword(Byte[] encrypted)
   at Docker.WPF.Credentials.MountCredentialAsker.RetrieveCredential(String target)
   at Docker.Actions.PreStartCheck(ContainerEngineMode engine)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()
```

### Information

This error is reproducible every time. I have tried both the stable and edge versions.
  - Windows Version: Windows 10 Enterprise, version 1709, OS build 16299.1451
  - Docker Desktop Version: 2.1.0.4 (39773) stable
  - Docker Desktop Version: 2.1.4.0 (39357) edge
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No, Windows 10 is installed directly on a desktop computer.

I am trying to install and configure Docker Desktop unattended and I need to share a drive. I am aware that this might not be supported, and if that is the case I should create a feature request issue for that, but at least I would expect Docker Desktop not to crash, and maybe give me the opportunity to enter new credentials if Docker Desktop can't use what it finds in Windows credential manager.

### Steps to reproduce the behavior

1. Install Docker Desktop
2. Stop Docker Desktop
3. Edit c:\Users\<username>\AppData\Roaming\Docker\settings.json to have
```
"sharedDrives": {
    "C": true,
    "E": false
  }
```
4. Run the command: `cmdkey /generic:"Docker Host Filesystem Access" /user:MYDOMAIN\niped /pass:Test1234`
(Domain and password has been changed).
5. Start Docker Desktop
6. Docker Desktop crashes with the error mentioned under Actual behavior

**Comment by djs55** [comment]
@npeder thanks for your report. There's a completely new drive sharing mechanism in the latest edge release which doesn't require credentials at all, so hopefully works around this problem.

In case it's useful I've written instructions for setting up and testing the new file sharing implementation here: https://github.com/docker/for-win/issues/5139#issuecomment-559700215
