### ISSUE TITLE
Error on start Docker desktop for windows after updating to 2.1.0.4

### ISSUE THREAD

**Issue by jodurpar** [docker/for-win#4984]
Unable to start docker desktop for windows 10 after update 2.1.0.4 (39773) version.

Windows 10 Enterprise version 17763.775

Unable to create System.Management.Automation.ActionPreferenceStopException ("ErrorActionPreference"). 

there are any way to downgrade desktop version to 2.1.0.3 without lose all images/containers ?

Any ideas ?
[log.txt](https://github.com/docker/for-win/files/3761092/log.txt)

**Comment by anuri73** [comment]
I also have troubles on updating, with following error:

```
Сбой операции дешифрования, см. внутреннее исключение.
   в System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   в System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.<ReadAsync>d__4.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в CommunityInstaller.DownloadStep.<DoAsync>d__35.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в CommunityInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()
```

**Comment by ofek** [comment]
If you go to `Hyper-V Manager` then on the right `Virtual Switch Manager...`, do you get an error?

**Comment by jodurpar** [comment]
In the Hyper-v Masnager i get this error: Can not conect to to server, check if vm manager service are running. But all are running .....

**Comment by jodurpar** [comment]
Ok, i solved the problem. For same reason the hyper-v ecosystem was corrupted. I have completely uninstalled hyper-v and reinstalled it (from control panel).

Thanks to all!
