### ISSUE TITLE
`docker save` with a windowsservercore image fails on file integrity checksum

### ISSUE THREAD

**Issue by mattdanskey** [docker/for-win#499]
### Expected behavior
Able to run `docker save` with an image based on `microsoft/windowsservercore`

### Actual behavior
Attempting to save results in the following message: 
>Error response from daemon: file integrity checksum failed for "Files/ProgramData/Microsoft/Diagnosis/Events_Normal.rbs"

### Information

Diagnostic ID: 0E44D6BA-6725-4804-ABD5-25A91047AADE/2017-02-14_16-31-51
Docker version 1.13.1, build 092cba3
Windows 10 Pro, build 14393.693
Running inside of Parallels

I've been unable to use `docker save` successfully on an image based on `microsoft/windowsservercore` -- or even been able to save that image itself. I have been able to save `microsoft/nanoservercore` successfully. 

I've tried removing and re-downloading the image, but it seems that a partial image that `docker images -a` is still on my machine, meaning the majority of the image wasn't re-downloaded, as noted below:

> PS C:\> docker pull microsoft/windowsservercore:10.0.14393.823
10.0.14393.823: Pulling from microsoft/windowsservercore
3889bb8d808b: Already exists

I wonder if the fix involves re-downloading that layer that Already exists that I haven't been able to track down and get rid of.

Note that `docker save` for the windowsservercore image worked on a Windows Server 2016 machine running Docker 1.13.1-cs1, build 8709b81

### Steps to reproduce the behavior

  1. `docker pull microsoft/windowsservercore:10.0.14393.823`
  2. `docker save -o repro.tar microsoft/windowsservercore:10.0.14393.823`

**Comment by friism** [comment]
```
save microsoft/windowsservercore -o foo.bar
Error response from daemon: open \\?\C:\ProgramData\Docker\windowsfilter\06f977eab32c03e2743d1336a4266d7e318708e20b35706e94a7a861fbf092a1\Files\Boot\BCD: The system cannot find the path specified.
```

@jhowardmsft do you know what might be going on?

**Comment by jhowardmsft** [comment]
This sounds very similar to https://github.com/docker/docker/issues/25893. Can you file an issue over to docker/docker instead of here.

**Comment by mattdanskey** [comment]
@jhowardmsft Done!
