### ISSUE TITLE
SOLVED: Mounting directories on Windows 10 do not seem to work

### ISSUE THREAD

**Issue by michaelwiller** [docker/for-win#50]
docker run --rm -v c:/Users/michael:/data alpine ls -la /data

### Expected behavior
List of C:\Users\michael
![ls](https://cloud.githubusercontent.com/assets/7422395/17834097/1b591234-6732-11e6-836e-1c7bf1bd307f.PNG)

### Actual behavior
Only showing "." and "..".

![ls](https://cloud.githubusercontent.com/assets/7422395/17834102/3f7c38f8-6732-11e6-8691-afd975f57d71.PNG)

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.

F72D0B33-B1B3-4168-B9E8-D812A10C0166/2016-08-21_00-03-22

Docker version is:

Client:
 Version:      1.12.1-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7889dc7
 Built:        Fri Aug 12 18:35:53 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.1-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7889dc7
 Built:        Fri Aug 12 18:35:53 2016
 OS/Arch:      linux/amd64
 Experimental: true

(switched to Beta, since this didn't work in stable 1.12)

  - host distribution and version (Windows version, build number, etc)

Confirm that C: is shared. And user SCOTT-TIGER-MW\michael has full control.
![ls](https://cloud.githubusercontent.com/assets/7422395/17834165/40d321ce-6734-11e6-868e-800bf0499df5.PNG)

Password of "michael" is _very_ short and has no special characters.

Observation: 
System reacts to C:/Users/not-found just as it reacts to C:/Users/michael ... It can't see anything in the share.

Tried to use share as "net use X: \\SCOTT-TIGER-MW\michael\C"; dir X:\Users\michael. This worked as expected (list of content displayed).

### Steps to reproduce the behavior

  1.  docker run --rm -v c:/Users/michael:/data alpine ls -la /data
  
I have tried entering credentials in settings with and without machine-name. Docker seems to be using the machine-name just fine. But none of the options work.

**Comment by michaelwiller** [comment]
Disabling Norton firewall and auto-protect allows the share to work. Even works with Norton protection reenabled. Restart Docker and the connection is lost again.
I have trust set up for com.docker.proxy, slirp and Docker for Windows.
Q: What traffic do I need to allow through?

**Comment by michaelwiller** [comment]
I have created a rule in the firewall allowing incoming traffic for TCP/UPD on ports 139,445 on net 10.0.75.0/24. This seems to resolve matters.

Can anyone think of a better way?

**Comment by yetanotherchris** [comment]
I was having the exact same problem as @michaelwiller but trying to map to a folder on C:

    docker run -it -v /C/Code/Nginx/logstash:/config-dir logstash bash -c "ls /config-dir"

The firewall walls fixed it (along with a Docker restart). I'm not tying it down to an IP.

**Comment by michaelwiller** [comment]
Glad I could help :)
This is why I left it open. Closing the issue and prefixing with "SOLVED:"

**Comment by yetanotherchris** [comment]
For anyone viewing this, here's two lines of powershell for the firewall rule:

     New-NetFirewallRule -DisplayName "Docker For-Win TCP" -Direction Inbound –LocalPort 139, 445 -Protocol TCP -Action Allow
     New-NetFirewallRule -DisplayName "Docker For-Win UDP" -Direction Inbound –LocalPort 139, 445 -Protocol UDP -Action Allow

**Comment by lypanov** [comment]
The above Powershell should really be in the documentation. It's just not enough to have to search for 10 minutes to find this Github issue.

**Comment by friism** [comment]
@simonferquel could we auto-open these ports during install?

**Comment by simonferquel** [comment]
@friism it is already done on beta channel (and stable 1.13 will have it)

**Comment by friism** [comment]
@simonferquel awesome, thx
