### ISSUE TITLE
Unable to launch docker, Unable to create error after updating Windows 10 

### ISSUE THREAD

**Issue by Levity1** [docker/for-win#5002]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 2EE0A2AE-5143-4737-AE40-1D9FE24338A7/20191024222207

### Expected behavior
Docker launches with no issues
### Actual behavior
Error appears after launching -- 
"Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input.

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()"
### Information

  - Windows Version: 
Windows 10 Version 10.0.18362 Build 18362
  - Docker Desktop Version:
2.1.0.4 (39773)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
No

### Steps to reproduce the behavior

  1. Launch docker
  2. Error appears

**Comment by ThePlenkov** [comment]
Same for me. Suddenly crashes. Cannot work anywore!

**Comment by n-richaud** [comment]
The windows update reset some configurations , so you need to follow this procedure to make it work again : https://github.com/docker/for-win/issues/1221#issuecomment-493118403
On the laptop i tried the fix it was not for "Code flow guard (CFG)" i had to uncheck "override settings" so uncheck this uncheck it for all .

**Comment by ThePlenkov** [comment]
I solved my issue like this:
1. Disable Hyper-V (Windows features)
2. Reboot
3. Enable Hyper-V
4. Reboot

**Comment by Levity1** [comment]
Thanks for the help, I tried both of these methods and the Hyper-V changes the error code after the 2nd reboot, but reinstalling docker gets me back to square one. 

Here is the error code I get after re-enabling Hyper-V + reboot:

```
Unable to create Hyper-V VM: The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input.
at Set-IPAddress, <No file>: line 290
at Set-SwitchIPAddress, <No file>: line 320
at New-MobyLinuxSwitch, <No file>: line 260
at New-MobyLinux, <No file>: line 176
at <ScriptBlock>, <No file>: line 800

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass25_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()
```

**Comment by CaliGlenn** [comment]
> The windows update reset some configurations , so you need to follow this procedure to make it work again : [#1221 (comment)](https://github.com/docker/for-win/issues/1221#issuecomment-493118403)
> On the laptop i tried the fix it was not for "Code flow guard (CFG)" i had to uncheck "override settings" so uncheck this uncheck it for all .

Tried this. Didn't work.



> I solved my issue like this:
> 
> 1. Disable Hyper-V (Windows features)
> 2. Reboot
> 3. Enable Hyper-V
> 4. Reboot

Tried this too. Didn't work.

Suggestions are welcome. Been looking to this issue for to long today :(

**Comment by Levity1** [comment]
I've found a workaround temporarily. It seems Docker Version 2.0.0.3 still works if you want to give that a try.

**Comment by CaliGlenn** [comment]
> I've found a workaround temporarily. It seems Docker Version 2.0.0.3 still works if you want to give that a try.

Nope, still same error for me :'(
