### ISSUE TITLE
Linux container running in Windows C drive is not staying shared.

### ISSUE THREAD

**Issue by powersjt4** [docker/for-win#5005]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
C drive stays shared and Docker stands up the Linux container. 
### Actual behavior
C drive does not appear to stay shared.  Check box under settings indicates that the drive is still shared. Unchecking, checking again and restarting docker will resolve the issue.

Starting docker-compose job produces the below error.
```
Creating network "docker_default" with the default driver
Creating docker_thingworx_1 ... error

ERROR: for docker_thingworx_1  Cannot start service asdf: error while creating mount source path '/host_mnt/c/authorized/RootFile/java-sdk/src/test/resources/docker/keystores/keystore.jks': mkdir /host_mnt/c: file exists

ERROR: for thingworx  Cannot start service asdf: error while creating mount source path '/host_mnt/c/authorized/RootFile/java-sdk/src/test/resources/docker/keystores/keystore.jks': mkdir /host_mnt/c: file exists
ERROR: Encountered errors while bringing up the project.
```

### Information

  - Windows Version: Windows 10 Version 10.0.17134 Build 17134
  - Docker Desktop Version: 2.1.0.4 (39773)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Yes

### Steps to reproduce the behavior

This machine is a virtual machine used as a GitLab CI runner.
  1. Machine has been running and standing up and shutting down docker-compose jobs
  2. After a while the error above is produced and the container does not start.

**Comment by djs55** [comment]
@powersjt4 there's a completely new drive-sharing mechanism in the latest edge version which may fix this problem.

In case it's useful I've written instructions for setting up and testing the new file sharing implementation here: https://github.com/docker/for-win/issues/5139#issuecomment-559700215
