### ISSUE TITLE
Container fails to run in priviledged mode

### ISSUE THREAD

**Issue by Xandroid4Net** [docker/for-win#501]
### Expected behavior
When using docker-compose up with the yml file below, container will run in priviledged mode.

```
version: "2.1"

services:
  web:
    build: .
    command: nodemon -L --debug=5858

    privileged: true
    tty: true
    ports:
      - "3000:3000"
      - "5858:5858"
networks:
  default:
    external:
      name: nat
```

dockerfile for base node image

```
FROM microsoft/windowsservercore

ENV NPM_CONFIG_LOGLEVEL info  

RUN powershell -Command "wget -Uri https://nodejs.org/dist/v6.9.5/node-v6.9.5-x64.msi -OutFile node.msi -UseBasicParsing"

RUN msiexec.exe /q /i node.msi

CMD [ "node" ]  
```

dockerfile for hapi server with serialport

```
FROM node:695

WORKDIR /app

RUN npm install --silent --progress=false -g nodemon@1.10.2

COPY package.json /app/package.json
RUN npm install 


COPY . /app

CMD ["npm.cmd", "start"]
```

### Actual behavior

When docker-compose up is run the initialization fails with the following error

PS C:\Users\honeyws\Documents\ComApiNodeWindows> docker-compose up
Removing comapinodewindows_web_1
Recreating f8442170a78f_comapinodewindows_web_1

ERROR: for web  Cannot start service web: container c1e3bd481a189a4f68566e4dd470af1ef385288ec7e831633e39363809358613 enc
ountered an error during CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x
2) extra info: {"ApplicationName":"","CommandLine":"nodemon -L --debug=5858","User":"","WorkingDirectory":"C:\\app","Env
ironment":{"NPM_CONFIG_LOGLEVEL":"info"},"EmulateConsole":true,"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStd
ErrPipe":false,"ConsoleSize":[0,0]}
ERROR: Encountered errors while bringing up the project.
PS C:\Users\honeyws\Documents\ComApiNodeWindows>

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

ID 097756B2-58F4-436C-901D-FFC79D6EA8B6/2017-02-15_15-24-44

```
PS C:\Users\honeyws\Documents\ComApiNodeWindows> docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      windows/amd64
 Experimental: true
```
I have also tried the following docker run which is successful

docker run -p 3000:3000 -t comapinodewindows_web:latest

but the --priviledged flag causes the same failure as the compose command.

### Steps to reproduce the behavior

  1. docker build -t node .               (the first dockerfile from above)
  2. docker tag node:latest node:695 
  3. docker-compose build
  4. docker-compose up

**Comment by rneugeba** [comment]
Thanks for your report. This seems like an issue with the windows docker engine. Could you file an issue on https://github.com/docker/docker instead? I wouldn't be surprised if `--priviledged` does not work the same way as it does on Linux as it is related to the Linux capabilities.

**Comment by rneugeba** [comment]
thanks for filing the issue. closing this one
