### ISSUE TITLE
A firewall is blocking file Sharing between Windows and the containers

### ISSUE THREAD

**Issue by manrajesh** [docker/for-win#5015]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Drive should be shared via docker Desktop.
### Actual behavior
I have tried all the options available in https://github.com/docker/for-win/issues/355 but none of them are working. 
### Information

  - Windows Version: WIndows 10
  - Docker Desktop Version: 2.1.0.4(39773)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No, Windows 10 laptop

**Comment by djs55** [comment]
@manrajesh thanks for your report. There's a completely new drive sharing mechanism available in the edge channel which should fix these firewall issues.

In case it's useful I've written instructions for setting up and testing the new file sharing implementation available in the edge channel here: https://github.com/docker/for-win/issues/5139#issuecomment-559700215

**Comment by stephen-turner** [comment]
This is fixed with the new filesharing implementation in 2.2.0.3, so closing this ticket.
