### ISSUE TITLE
After PC reboot docker version gets executed with error

### ISSUE THREAD

**Issue by gavvvr** [docker/for-win#502]
### Expected behavior

Client and server info to display normally

### Actual behavior

> PS C:\Users\gavvvr> docker version
> Client:
>  Version:      1.13.1
>  API version:  1.26
>  Go version:   go1.7.5
>  Git commit:   092cba3
>  Built:        Wed Feb  8 08:47:51 2017
>  OS/Arch:      windows/amd64
> error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.26/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

### Information

I have Windows 10 Pro and clean docker installation.
Diagnostics id is: F068A9F3-E1DD-4082-B56E-07AE117C7941/2017-02-16_00-34-59

### Steps to reproduce the behavior

  1. Install Docker
  2. Reboot PC
  3. open cmd.exe or powershell and type `docker version`

**Comment by rneugeba** [comment]
@gavvvr thanks for the report. I had a look at the logs and they look fine. Maybe I don't quite understand the issue. You mentioned you get the error after a reboot. Does it work after waiting for a while? Is the application running (check the systray and look for the whale)? The docker command would only work once the animation of the whale stops.

**Comment by gavvvr** [comment]
@rneugeba the application in tray was running and indicated the docker is ready (green circle in settings).
I solved the problem by `Settings -> Reset -> Restart Docker...`
Now i can't reproduce it when i restart PC :)

**Comment by rneugeba** [comment]
Thanks for getting back and glad it's now working. Weird, though and I wish I knew why it broke. In any case, closing this issue for now, please re-open if it happens again.
thanks
