### ISSUE TITLE
Credential helpers are used even if they are not configured

### ISSUE THREAD

**Issue by pirast** [docker/for-win#5020]
- [ X ] I have tried with the latest version of my channel (Stable or Edge)
- [ X ] I have uploaded Diagnostics

### Expected behavior
Docker should keep the config.json file untouched on every startup (esp. not insert/modify credStore value).

### Actual behavior
On every startup, Docker modifies the config.json file on Windows, adding "credsStore":"desktop", which ultimatively leads to a situation in which it is not using the credentials stored in the config.json file in base64 encoding. In our use case, this is needed. In #1359, a checkbox has been introduced for Docker for Mac ("Securely store Docker logins in macOS keychain") to work around this issue. A solution would be to also introduce it for Docker for Windows. Alternatively, an option "credsStore":"none" would be an option which is persisted.

**Comment by philippe-granet** [comment]
Same problem for me, open new issue #6043
