### ISSUE TITLE
Timed-out waiting for the lifecycle-server to start

### ISSUE THREAD

**Issue by rasego68** [docker/for-win#5031]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
C3321885-AA8E-486A-8CB6-E5F69C77DF72/20191030145832
### Expected behavior
Run Docker
### Actual behavior
Not Initializing
### Information

  - Windows Version: Windows 10 Pro
  - Docker Desktop Version: 2.0.4.1
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Mac with VMware Fusion

### Steps to reproduce the behavior

  1. ...install Docker 
  2. ...does not initialize Docker

**Comment by rasego68** [comment]
[20191030145832.zip](https://github.com/docker/for-win/files/3795058/20191030145832.zip)

**Comment by rasego68** [comment]
Guys please any help I can get will be greatly appreciated!

**Comment by rasego68** [comment]
I found the solution

**Comment by ebriney** [comment]
Hi @rasego68, what did you do to fix it?

**Comment by rasego68** [comment]
I install the latest version of docker
