### ISSUE TITLE
Docker Desktop Windows crashes with message "Failed to start the virtual machine 'DockerDesktopVM' because one of the Hyper-V components is not running."

### ISSUE THREAD

**Issue by larsekman** [docker/for-win#5034]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B6F9F5BB-FC0D-48B6-BE4D-51C28D7672FA/20191031015747

### Expected behavior
Docker Desktop does not crash.

### Actual behavior
After installing Docker Desktop on a clean Windows 10 machine, the program crashes shortly after start with the message "Failed to start the virtual machine 'DockerDesktopVM' because one of the Hyper-V components is not running."

### Information

  - Windows Version: 10.0.18362
  - Docker Desktop Version: 2.1.0.4 (39773)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Yes, VMWare Fusion

### Steps to reproduce the behavior

  1. Install latest version of Docker Desktop on a clean Windows 10 install running in VMWare Fusion.
  2. Run Docker Desktop.

**Comment by larsekman** [comment]
Is there a previous version of Docker for Windows that can be downloaded and that works?

**Comment by dimdimych** [comment]
@larsekman nobody cares apparently
