### ISSUE TITLE
Docker Startup Error

### ISSUE THREAD

**Issue by otedolaishola** [docker/for-win#5040]
Hello Team,
I have an issue starting up my docker desktop for Windows.

The version is included below and my diagnostics ID.

I have also attached a screenshot of the error I received when I tried to run 'docker run hello-world' from the command prompt.
![doc startup error](https://user-images.githubusercontent.com/57218901/67942664-3f94da80-fbd0-11e9-805c-389fd63d6e38.PNG)

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 3A4B961A-D40F-408E-BF70-6A11B1E2FD03/20191031110313

### Information

  - Windows Version: Docker Desktop
  - Docker Desktop Version: 19.03.4
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Deweytle** [comment]
Are you running your windows as a virtual machine with VMWare ?
