### ISSUE TITLE
Losing connection to Docker daemon after a short period of time (10-15 minutes). Issue related to VMWare Tools update

### ISSUE THREAD

**Issue by stumpdk** [docker/for-win#5044]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 28DD3868-64B6-4EEA-BACE-63759F8DCC13/20191101143502

### Expected behavior
   1. Start Docker Desktop for Windows
   2. There should be access to the Docker daemon until Docker Desktop for Windows is shut down

### Actual behavior
   1. The connection to the Docker daemon is lost after roughly 10 to 15 minutes
   2. A restart of the host and/or the Docker service solves the problem temporarily, but the connection is lost again after 10-15 minutes

### Information
This might not be an issue as such, but a description of incompatibility between Docker and a certain version of VMWare Tools. The issue is reported to help others experiencing the same problems we have.

Please, help us understand the problem.  For instance:
  - Is it reproducible? Yes
  - Is the problem new? Yes
  - Did the problem appear with an update? Yes, an update of VMWare Tools.
  - Windows Version: Windows 10 Pro build 1903
  - Docker Desktop Version: Docker for Windows v. 2.1.0.4 and v. 2.1.3.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Yes, on VMWare running virtual Windows servers.
  - The issue was experienced on three different Windows 10 servers running the same version of VMWare Tools.

### Steps to reproduce the behavior
  1. Start Docker Desktop for Windows 10 build 1903 with VMWare Tools v. 11265 (11.0.1)
  2. Wait 10-15 minutes
  3. Connection to Docker is lost, and the error "Error response from daemon: Bad response from Docker engine" is written when running commands such as docker ps

### Steps to avoid the problem
   1. Uninstall VMWare Tools  v. 11265 (11.0.1)
   2. Install v. 10309 (10.2.5)
   3. Enjoy Docker

**Comment by noraab** [comment]
Same on 
- Windows Server 2019 Version 1809 Build 17763.973
- Docker Engine - Enterprise 19.03.5

**Comment by stumpdk** [comment]
@noraab can you confirm VMWare Tools v. 11265 (11.0.1)?

**Comment by noraab** [comment]
> @noraab can you confirm VMWare Tools v. 11265 (11.0.1)?

@stumpdk yes, exactly same version.

**Comment by kiberboy** [comment]
I have a similar problem. After 15-20 minutes swarm service is not responding, and can't be stopped or killed. But docker commands such as ps or logs works.

- Windows Server 2019 Version 1809 Build 17763.737
- Docker Engine - Enterprise 19.03.5

Uninstalling the VMWare tools helped.

**Comment by MuhKuh7** [comment]
Same problem after installing VMWare Tools 11.0.1
After max 30 minutes the event log shows that "vmcompute.exe" crashed in module "ntdll.dll" and Docker stops working.

**Comment by SeigneuS** [comment]
I don't know if this can help, but I remark that the docker network is modified after problem occurs:

BEFORE PROBLEM:
PS C:\ibm\PAW_2.0.48> docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
d12c2e0ca54a        nat                 nat                 local
221c8781b911        none                null                local

AFTER PROBLEM (which occurs after 30 minutes. The Docker service had to be restarted but my containers are still not working)
PS C:\ibm\PAW_2.0.48> docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
d12c2e0ca54a        nat                 nat                 local
e1c0ab3d0107        none                null                local

And as a result, the Endpoints and IP addresses of my containers are changed too, while the gateway and subnet of Docker are still the same (I do not know if this is relevant, I'm novice on this):

BEFORE PROBLEM:
PS C:\ibm\PAW_2.0.48> docker network inspect nat
        "Name": "nat",
        "Id": "d12c2e0ca54ab6932ea7806d4ffe5b409f350ea904988734f87196e340672acc",
        "Created": "2020-02-10T14:47:42.2008025+01:00",
        "Scope": "local",
        "Driver": "nat",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "windows",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.19.64.0/20",
                    "Gateway": "172.19.64.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
...
            "2152f97c6b3ab7333d79240de8eb1f12a132e11cf4bf4d7ac2ecb709c27a1c54": {
                "Name": "mongo",
                "EndpointID": "eeee6eba0b841691ddf41555eaab06b178a10a40681a69ccbbc01f00fc7163f3",
                "MacAddress": "00:15:5d:18:26:38",
                "IPv4Address": "172.19.67.39/16",
                "IPv6Address": ""
            },
...
        },
        "Options": {
            "com.docker.network.windowsshim.hnsid": "e13063c3-abda-4dfb-920d-8f88e992f877",
            "com.docker.network.windowsshim.networkname": "nat"
        },
        "Labels": {}
    }

AFTER PROBLEM :
PS C:\ibm\PAW_2.0.48> docker network inspect nat
[
    {
        "Name": "nat",
        "Id": "d12c2e0ca54ab6932ea7806d4ffe5b409f350ea904988734f87196e340672acc",
        "Created": "2020-02-10T15:17:32.1732736+01:00",
        "Scope": "local",
        "Driver": "nat",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "windows",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.19.64.0/20",
                    "Gateway": "172.19.64.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
...
            "2152f97c6b3ab7333d79240de8eb1f12a132e11cf4bf4d7ac2ecb709c27a1c54": {
                "Name": "mongo",
                "EndpointID": "1399c539d77fd36da70a9b9b89263e6b593973bf1921d88d25263e21b59b76f8",
                "MacAddress": "00:15:5d:18:28:e0",
                "IPv4Address": "172.19.67.21/16",
                "IPv6Address": ""
            },
...
        },
        "Options": {
            "com.docker.network.windowsshim.hnsid": "e13063c3-abda-4dfb-920d-8f88e992f877",
            "com.docker.network.windowsshim.networkname": "nat"
        },
        "Labels": {}
    }
]

I have no idea what can be done to make my containers working again.

In addition to this I traced with Process Monitor what the process vmtoolsd.exe is doing; it mainly accesses these registry keys :
HKLM\System\CurrentControlSet\Services\Tcpip\Parameters
HKLM\System\CurrentControlSet\Services\Tcpip\Parameters\Domain
HKLM\System\CurrentControlSet\Services\Tcpip\Parameters\Hostname
HKLM\Software\Policies\Microsoft\System\DNSclient
And it is also accessing some \Device\Harddisk Volumes
That is pretty all I can see...
Any idea what vmware tools is doing that breaks docker containers ?

**Comment by MuhKuh7** [comment]
Just tested with VMWare Tools 11.0.5, but the issue remains.

**Comment by tallandtree** [comment]
We had the same issue with:

- Windows Server 2019 Datacenter Version 1809 (OS Build 17763.379)
- VMWare: version 11.0.2. 
- Docker EE: 19.03.5

I've downgraded to: VMWare version 10.3.2.9925305 and it seems solved. At least I've not seen the error in the log for now.

**Comment by hfu559675** [comment]
we have the same issue. We reached out to VMWare about this, but they told us to ask Docker team to fix the issue.

**Comment by tuunit** [comment]
We do have the same issue as well and we don't have the option to downgrade VMWare Tools either. Is there any investigation going on about what could be the root cause of this issue?

**Comment by tuunit** [comment]
After some testing, I found out by increasing the memory the issue of losing the connection to the docker daemon persists but gets delayed by several minutes. I'm talking about the memory that Docker Desktop is allowed to allocate in the resource settings:

- By increasing the memory to 4GB the connection lose occurs after about ~18-20min
- With 6GB the issue occurs after about ~25-28min

Maybe this information can help to identify the root cause.

**Comment by oliverkurth** [comment]
The issue should be fixed in VMware Tools 11.0.6. See https://my.vmware.com/web/vmware/details?downloadGroup=VMTOOLS1106&productId=974 .

**Comment by stumpdk** [comment]
Hi @oliverkurth 
Thanks for the update. Where do you see, that the update solves the problem? I read through the changelog, and couldn't find any information about Docker.

**Comment by patschi** [comment]
> Where do you see, that the update solves the problem? I read through the changelog, and couldn't find any information about Docker.

It seems to be related to the `AppInfo` component which was first introduced in VMware Tools 11.0.0, and not directly with Docker. I've heared back that this behavior was indeed addressed in 11.0.6 (see [release notes](https://docs.vmware.com/en/VMware-Tools/11.0/rn/VMware-Tools-1106-Release-Notes.html)).

**Comment by oliverkurth** [comment]
Yes, it is related to the appinfo plugin, which has been fixed in 11.0.6. This is the same issue as documented in https://kb.vmware.com/s/article/78550 , however Docker for Windows isn't listed there as an affected application.

**Comment by tuunit** [comment]
I can confirm, that upgrading to version 11.0.6 fixed the issue for our servers.

**Comment by kkbruce** [comment]
I have same issue. And upgrading to version 11.0.6 fixed losing connection problem.

**Comment by bbqrob** [comment]
@kkbruce Did you use `v11.0.1` before this? Or an even older version?

**Comment by tuunit** [comment]
@bbqrob I used v11.0.1 and it wasn't working with that version. After updating to v11.0.6 the issue is gone.

**Comment by fluffyDough** [comment]
@bbqrob check the issue mentioned by @MuhKuh7 (https://github.com/moby/moby/issues/40328). For me both VMTools versions 11.0.1 and 11.0.5 did not work (random containers were closing with 3221226505 error code after a few minutes my VM was restarted). I was upgrading from 10.x. 11.0.6 works properly. I added a comment with my environment details in mentioned issue.

**Comment by kkbruce** [comment]
@bbqrob  yes, we upgrade to `v11.0.1` then Docker started to go wrong.
