### ISSUE TITLE
Images, Containers and Volumes all gone when increasing memory from Settings->Advanced

### ISSUE THREAD

**Issue by bmadina** [docker/for-win#5045]
F6EBE065-99E7-471D-B439-3770CC6F9433/20191102105320

Hello,

I have all my Docker data (images, containers and volumes) missing after I tried to increase memory from settings->advanced in Docker Desktop for Windows 2.1.0.4. Engine 19.03.4

I upgraded first from 2 to 4GB but computer answered there was not available such amount. Decreased to 3 GB and started OK but all the data gone.

Somenone any thoughts?

Thanks in advance!

**Comment by valentincauro** [comment]
Same here... just lost all my unsaved DB... 
Do you think there is a way to restore it ? 
Thanks

**Comment by mat007** [comment]
Duplicates #5278
