### ISSUE TITLE
Install latest edge, ubuntu WSL2 cannot find docker daemon

### ISSUE THREAD

**Issue by manardella** [docker/for-win#5054]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 9DEF3CC1-C653-4580-A378-02929AF6C333/20191104204036

### Expected behavior
Run `sudo docker ps` in the ubuntu console under WLS2

### Actual behavior
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.

### Information

  - Windows Version: Windows 10 PRO fast ring (latest available)
  - Docker Desktop Version: Latest EDGE with WLS backend.
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No. Windows 10 running in Dell T1700 small form factor tower.

### Steps to reproduce the behavior

  1. Windows 10 PRO fast ring.
  2. Install ubuntu WLS2, docker.
  3. All works, install docker edge (not the latest build with WLS backend
  4. Enable experimental WLS backend
  5. Restart
  6. ERROR: The ubuntu distro not longer can detect or connect to the docker daemon.

**Comment by manardella** [comment]
Trying to uninstall and reinstall.

**Comment by StefanScherer** [comment]
The recommended way is using Docker Deskop. We‘ve released a new Edge version 2.1.5.0 which brings docker engine for WSL2.

**Comment by manardella** [comment]
My fault. I have just reinstalled it. Reboot. Enable WLS2. Go to settings and enable ubuntu integration

![image](https://user-images.githubusercontent.com/6719744/68158015-b6bacd80-ff46-11e9-8d22-823dfd02d934.png)

**Comment by manardella** [comment]
I think that step should be in the manual or in the release blog post.

Thanks for replying!

Thanks for your hard work.  :)

**Comment by FredM** [comment]
I just updated to 2.1.5.0 and I have the same error ("Cannot connect to Docker Deamon").

But when I go to
> Settings > Resources > Configure from which WSL2 distros you want to access Docker

, check the option and try to restart the engine, I have a popup saying

"Cross distro mounts are not enabled for distro Ubuntu-18.04"
![image](https://user-images.githubusercontent.com/779815/68176421-c3ddb980-ff52-11e9-8bb7-9007e7d6e80f.png)

If I click "Ok", after a few seconds the same message appear again. As long as I click "Ok" I end up with the same message.

I tried to reboot but same result

**Comment by cspotcode** [comment]
How do I revert my Docker Desktop installation to the WSL2 Tech Preview?  My team's workflow relies on mounting `/var/run/docker.sock` into our containers, so I cannot use the new WSL2 Backend.

**Comment by FredM** [comment]
> EDIT: I found a download link: https://docs.docker.com/docker-for-windows/edge-release-notes/#docker-desktop-community-2140
> I had to fully uninstall, then reinstall using that download.

Thanks for the link, works like a charm in 2.1.4.0. I guest we'll skip 2.1.5.0 ;)

**Comment by manardella** [comment]
It works for me. Make sure you have enabled wls2 (not 1) for the ubuntu and restarted the machine. I hope it helps. Then remove docker, restart, install docker, restart, enable wls2.

**Comment by FredM** [comment]
Looks like it is fixed in 2.1.6.0 :)

**Comment by PavelSosin-320** [comment]
I see PS C:\Users\Pavel> wsl list
/bin/bash: list: command not found
PS C:\Users\Pavel> wsl --list
Windows Subsystem for Linux Distributions:
Ubuntu (Default)
docker-desktop-data
docker-desktop
but nothing in the Docker Desktop setting screen

**Comment by StefanScherer** [comment]
@PavelSosin-320 list all distros with the version: `wsl -l -v` Maybe you have to convert the Ubuntu distro to version 2. Docker is only supported with WSL2.

**Comment by PavelSosin-320** [comment]
I got WSL 2.0 and Ubuntu from Microsoft Store and installed them folowing official instruction. Ubuntu itself works well. The problem that Docker Desktop settings resources proposes to select distro to manage its resources but shows empty list. WSL shows both Ubuntu (Default) and Docker desktop installed and running.Actually, I found nothing about WSL distro resource management except promises to implement something. Maybe it is configured in some wsl.config file?

**Comment by skyrpex** [comment]
> The problem that Docker Desktop settings resources proposes to select distro to manage its resources but shows empty list.

Same here. The list is empty.

**Comment by skyrpex** [comment]
> I got WSL 2.0 and Ubuntu from Microsoft Store and installed them folowing official instruction. Ubuntu itself works well. The problem that Docker Desktop settings resources proposes to select distro to manage its resources but shows empty list. WSL shows both Ubuntu (Default) and Docker desktop installed and running.Actually, I found nothing about WSL distro resource management except promises to implement something. Maybe it is configured in some wsl.config file?

I had to enable v2 for Ubuntu specifically. It worked for me after that.

**Comment by jayagami** [comment]
`sudo service docker start`

**Comment by pscheit** [comment]
works, but if you had, you need to unset $DOCKER_HOST as well
