### ISSUE TITLE
Getting image from ECR fails with no basic auth credentials

### ISSUE THREAD

**Issue by volphy** [docker/for-win#5055]
I found this issue appearing in Docker Desktop 2.1.0.4

### Expected behavior
If running MS Windows 10 (version 1809) & Windows Subsystem for Linux (Debian Buster) and Docker for Windows , ~/.docker/config.json settings should be honored.

### Actual behavior
In such a setting ~/.docker/config.json seems to be ignored.

### Steps to reproduce the behavior

How to reproduce it:
1. log in to an ECR `aws ecr get-login --no-include-email`
2. verify that credentials are persisted to ~/.docker/config.json
3. docker pull any image from the ECR

Sample output (anonymyzed):
```
$ docker build -t my-connector:latest .
Sending build context to Docker daemon  30.77MB
Step 1/8 : FROM AWS_ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com/my-openjdk:release-1-6-0
Get https://AWS_ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com/v2/my-openjdk/manifests/release-1-6-0 no basic auth credentials
```

**Comment by volphy** [comment]
Similar issue:  https://github.com/docker/for-mac/issues/3779

**Comment by jtoberon** [comment]
Josh from ECR here. We will investigate.

**Comment by somujay** [comment]
Is the ECR that you are trying to access is in the same AWS account?

**Comment by nmeyerhans** [comment]
Hi @volphy. The symptoms you describe match the behavior with Docker authentication if your credentials don't match the region of the repository you're trying to access. Can you try explicitly passing the region to your `get-login` call? e.g. 

`aws ecr get-login --no-include-email --region eu-west-1`

I've tested Docker Desktop 2.1.0.5 (Windows 10 Enterprise 1809) in a few different configurations against ECR, and have only managed to reproduce the symptoms you describe when the credentials aren't available for the region that hosts the registry I'm trying to work with.

As an aside, have you looked at using the [amazon-ecr-credential-helper](https://github.com/awslabs/amazon-ecr-credential-helper)? It eliminates the need for the explicit `get-login` step and uses your AWS credentials to authenticate with ECR, simplifying the authentication process.

**Comment by volphy** [comment]
You are right.

Now it works for me in the following environment:

- Docker for Desktop 2.1.0.5 (Windows 10 Enterprise 1809)
- AWS CLI 1.16.302
- Powershell

(I have some issues with misconfigured WSL but it is more an WSL issue than Docker issue)
