### ISSUE TITLE
WSL 2 backend does not appear to install/run

### ISSUE THREAD

**Issue by cerebrate** [docker/for-win#5056]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4E6EF1A9-9BE2-41DF-86AA-EC294E1D6A09/20191105062426

### Expected behavior

After checking the "Enable the experimental WSL 2 based engine" checkbox, and waiting for Docker Desktop to stop and restart:

1. WSL 2 options should be visible under "Resources"
2. A WSL docker context should exist
3. The Docker WSL distros should be visible to `wsl -l`

### Actual behavior

None of the above are true, even after waiting an additional several hours later. Apart from the checkbox remaining checked, there is no sign of the WSL 2 backend.

### Information

Tested with an upgrade from the previous version of Docker Desktop Edge. Also tested with a clean reinstall after removing previous version.

  - Windows Version: Windows 10 Professional Insider, build 19013
  - Docker Desktop Version: 2.1.5.0 (40323)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No.

### Steps to reproduce the behavior

  1. Install Docker Desktop on Windows 10 Insider with WSL installed.
  2. Attempt to enable WSL 2 backend.

**Comment by zot** [comment]
I'm seeing the docker-desktop WSL distro but in Settings->Resources->WSL INTEGRATION, when I check Ubuntu and then click Apply & Restart, nothing happens. Then, when I reopen the settings window, Ubuntu is unchecked.

I'll try a restart and see what happens.

**Comment by zot** [comment]
OK, after checking Docker's log, I had to do these things:

1. delete the docker group (or just rename it to something like x-docker)
2. make sure /dev/fuse is accessible (`sudo chmod 0666 /dev/fuse`)

Go to Docker Settings->Resources->WSL INTEGRATION and enable my distro (Ubuntu), then Apply & Restart.

After that, I found that all of my docker containers and images were gone. Lucky for me, I keep my important data outside of containers :).

I rebuilt one of my working containers but now it can't access my X server anymore through the WSL adapter, using host networking, like it could before. Working on that...

**Comment by simonferquel** [comment]
Yes, the mount story will improve with an upcoming Windows Insider build.

**Comment by cerebrate** [comment]
Same (original post) error persists in 19018, symptoms and logfiles unchanged.

**Comment by cerebrate** [comment]
Actually, we can go ahead and close this: this is a consequence of #5067 . I was expecting this WSL backend to function in the same manner as that in the tech preview, i.e., to be able to use Windows or Linux containers by changing the Docker context, hence my confusion with the "non-running" WSL.

**Comment by toddtee** [comment]
> Go to Docker Settings->Resources->WSL INTEGRATION and enable my distro (Ubuntu), then Apply & Restart.

Thanks! I didn't know about this setting, so flipping that switch worked for me!
