### ISSUE TITLE
Latest Edge (40323): credential box appears forever on C drive sharing

### ISSUE THREAD

**Issue by JPMoresmau** [docker/for-win#5057]
- [ X ] I have tried with the latest version of my channel (Stable or Edge)
  - [ X ] I have uploaded Diagnostics
  - Diagnostics ID: FBC58536-F77C-4909-9BBE-918AA324B487/20191105073838

### Expected behavior
I can check the C drive box to share my drive and it succeeds after entering my credential
Was working fine with previous version of Docker (like yesterday). Credentials haven't changed.

### Actual behavior
The credential box keeps appearing

### Information
  - Windows Version: 10.0.18362
  - Docker Desktop Version: 2.1.5.0 (40323)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No
  - VPN: turned off

### Steps to reproduce the behavior
  1. Go to Settings/Resources/File Sharing
  2. Click on C
  3. Click on Apply & Restart
  4. Credential box appears. Enter credential
  5. Box keeps appearing. No error, no explanation

**Comment by djs55** [comment]
@JPMoresmau thanks for the report. There is a new default filesharing system in this version which doesn't need credentials. I don't know (yet) why the credential dialog is still popping up on your machine :( I'll investigate.

In the meantime could you try running a command like this directly from powershell?
```
docker run -it -v C:\Users\Public:/foo alpine ls /foo
```
There should be a pop-up "Do you want to share this drive?":
![Capture d’écran 2019-11-05 à 09 35 45](https://user-images.githubusercontent.com/198586/68195921-b4408e00-ffaf-11e9-814a-38ef6fac17c7.png)

Hopefully if you click "Share it" it will work without credentials. Let me know if that works for you.

**Comment by JPMoresmau** [comment]
Thanks @djs55, but this is what I get:
```
PS C:\Users\jean-philippem> docker run -it -v C:\Users\Public:/foo alpine ls /foo
docker : C:\Program Files\Docker\Docker\resources\bin\docker.exe: Error response from daemon: status code not OK but 500: {"Message":"Unhandled 
exception: Drive has not been shared"}.
Au caractère Ligne:1 : 1
+ docker run -it -v C:\Users\Public:/foo alpine ls /foo
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Program File... been shared"}.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
See 'C:\Program Files\Docker\Docker\resources\bin\docker.exe run --help'.
```

**Comment by djs55** [comment]
@JPMoresmau after some discussion with my colleagues we have a theory: we believe there is a caching bug in the Windows service (not the app) which allows the system as a whole to get out of sync, where the app believes we are using the new filesharing mechanism but the service believes we are still using the old one.

If this theory is correct then you should be able to fix it by:

1. re-enabling "experimental features" in the Docker engine, see this screenshot: (set `"experimental": true` and then hit the "Apply and Restart button)

![Capture d’écran 2019-11-05 à 10 22 57](https://user-images.githubusercontent.com/198586/68199634-53688400-ffb6-11e9-8e28-ca220d439d1a.png)

2. restarting the "Docker Desktop service", see this screenshot: (search for "Services", select "Docker Desktop Service" in the list and then click on the "Restart the service" link)

You may need to restart the app a final time after the service has been restarted.

![Capture d’écran 2019-11-05 à 10 41 17](https://user-images.githubusercontent.com/198586/68201029-eaced680-ffb8-11e9-92e2-6bd421a4ed19.png)

**Comment by JPMoresmau** [comment]
Now I don't see the C drive under file sharing:
![image](https://user-images.githubusercontent.com/122273/68204183-bd3d5980-ffc7-11e9-9529-a9339566b9b8.png)

But your previous command fails:
```
docker : C:\Program Files\Docker\Docker\resources\bin\docker.exe: error during connect: Post 
http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/create: open //./pipe/docker_engine: The system cannot find the file specified. In the 
default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is 
not running.
```

I have restarted the service and the app and they both say they are running

**Comment by JPMoresmau** [comment]
OK, I'll leave the previous comment for posterity :-), but I had my VPN enabled. Disable VPN, restart Docker app, `docker run -it -v C:\Users\Public:/foo alpine ls /foo` lists the content of the directory fine.
