### ISSUE TITLE
Cannot mount local WSL file system v2.1.5.0

### ISSUE THREAD

**Issue by zot** [docker/for-win#5059]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 758CAAE9-ED91-4D26-BA11-D16C2F2073C2/20191105090803

### Expected behavior
When using docker run -v HOST-DIR:CONTAINER-DIR, HOST-DIR should appear in the container.

### Actual behavior
CONTAINER-DIR is empty in the container.

### Information
My host dir is a loop-mounted file system within my WSL 2 Ubuntu image.

This worked for me in version 2.1.4.0 but not in 2.1.5.0 (with the new WSL 2 backend).

### Steps to reproduce the behavior
  1. Create a file system in a file (I used dd to make a sparse file, loop-mounted it, and used mkfs to create the file system)
  2. Mount the file system on a directory
  3. use docker run -v to attempt mounting the directory into the container

**Comment by simonferquel** [comment]
This is a known issue, and will be fixed with a future Windows Insider build (current cross-distro mounts do not support mounting anything that is directly backed in the '/' mount point)
Please be patient :)

**Comment by zot** [comment]
Is there a way to mount something else from /mnt/wsl into a container (like from another WSL 2 distro), by any chance?

[EDIT] So far I haven't had any luck with what I've tried...

**Comment by simonferquel** [comment]
You can mount anything from your distro vhd ( eg. `docker run --rm /home:/mnt/home alpine ls /mnt/home` should just work). Anything that is not on the vhd itself (e.g. /sys, or /proc) is not visible (yet) from the container though

**Comment by zot** [comment]
I'm in an Ubuntu distro and I want to mount / from it and also / from my Alpine distro (i.e. /mnt/wsl/Alpine) into the container.

It seems like that's not possible yet because that's not in the VHD itself (although it is in another running WSL 2 instance)?

**Comment by zot** [comment]
Accessing WSL mounts other WSL instances in a container is now working in 2.1.6.0 for me, but with a huge caveat: I have to keep a docker container running.

Once I exit all of the docker containers, the docker WSL mounts disappear, along with /mnt/Alpine (a / mount from within my Alpine WSL instance). Curiously though, my bind mount from /mnt/Alpine/home/bill.shared onto /home/bill in my Ubuntu WSL instance does not disappear.

So at this point, I can at least use docker by keeping one container running.

**Comment by zot** [comment]
I ended up punting on docker within WSL2 for now. Hopefully the teams will resolve these issues and also the ability to mount vhdx files in WSL2. I'd love to use docker for my day-to-day work...
