### ISSUE TITLE
DeviceIOControl Win32 API call returns strange result for SYMLINKD folder mounted to docker volume

### ISSUE THREAD

**Issue by minherz** [docker/for-win#506]
### Expected behavior
When calling `DeviceIOControl` the resulted "substitute name" that can be derived from the `REPARSE_DATA_BUFFER` structure is expected to start with `\??\` in a case the call returns the absolute path.
### Actual behavior
When the `DeviceIOControl` is called in the windows container for a folder that is mounted volume and appears in the listing (by `dir` command) as SYMLINKD it starts with just `\`.

For example `dir` result is
```
02/16/2017  01:35 PM    <SYMLINKD>     .minio [\\?\ContainerMappedDirectories\A07E52BD-3B5B-44EB-8648-7DDB69D26682]
02/16/2017  04:51 PM    <DIR>          app
11/20/2016  01:32 PM             1,894 License.txt
02/16/2017  01:35 PM    <DIR>          Program Files
07/16/2016  02:09 PM    <DIR>          Program Files (x86)
02/16/2017  01:35 PM    <DIR>          volume
02/16/2017  01:37 PM    <SYMLINKD>     volume0 [c:\volume]
```
Calling `DeviceIOControl` for `c:\.minio` results in the following values:
```
PrintName offset 130
PrintName length 134
SubstName offset 0
SubstName Length 128
Flags 0
PrintName -> \\?\ContainerMappedDirectories\A07E52BD-3B5B-44EB-8648-7DDB69D26682
SubstituteName -> \ContainerMappedDirectories\A07E52BD-3B5B-44EB-8648-7DDB69D26682
```
Calling it for `c:\volume0 shows:
```
PrintName offset 0
PrintName length 18
SubstName offset 18
SubstName Length 26
Flags 0
PrintName -> c:\volume
SubstituteName -> \??\c:\volume
```
### Information

  - Diagnostic ID: F9F388E9-7AB0-4CE8-BD59-045CF28124A7/2017-02-16_15-44-33
  - Originally issue was reported to minio project as it was discovered due invalid behavior of `golang` code for processing data storage path (see [issue 3742 in minio/minio](https://github.com/minio/minio/issues/3742)).
  - Operating System and version: Windows 10 x64 Enterprise Version 1607 (Build 14393.693)
  - Docker for Windows version: Version 1.13.1-beta42 (10069) in Beta mode

I wrote an application that calls DeviceIOControl and prints the returned fields. It requires dotnet core 1.1 to run (see the image in the reproduction steps). It can be found [here](https://slack-files.com/T3NG3BE8L-F46CVAYEN-8247786785). I can share the code of the app if required.

### Steps to reproduce the behavior

  1. Run command
```
docker run -it -v c:\mounted_folder --name=test microsoft/dotnet:nanoserver cmd
```
  2. Use any application (e.g. this .net core 1.1 app that i wrote) to call `DeviceIOControl` and print the resulted fields for c:\mounted_folder and observe the output of the SubstituteName.
  3. Create a "local" symbolic link
```
mklink /D c:\System c:\Windows
```
  4. Use the application again for c:\System and observe the output of the SubstituteName.

**Comment by rneugeba** [comment]
@minherz thanks for the detailed report. This seems an issue with the windows docker engine and it would be better to file an issue on https://github.com/docker/docker as this is where those developers hang out.
Thanks

**Comment by minherz** [comment]
Please, advise how the issue can be moved? Will it be enough to open an issue there with a link to this one?

**Comment by rneugeba** [comment]
Unfortunately, GH does not allow moving issues between projects (otherwise I would have done that :).

It's best if you open a new issue there. Since you already typed everything up nicely here, I'd hit the "Edit Comment" button above on your original post and then copy and paste into the new issue.

It's also a good idea to add the output of `docker info` to the body

**Comment by rneugeba** [comment]
thanks. closing this issue
