### ISSUE TITLE
support wcow and lcow with wsl2 backend

### ISSUE THREAD

**Issue by kamkie** [docker/for-win#5067]
using wsl2 first preview it was possible tu run lcow container in one context using wsl2 backend 
and wcow in another context

new docker desktop on wsl2 preview (2.1.5) currently doesn't allow this

**Comment by ebriney** [comment]
Hi @kamkie , you can still do it but you need to `switch to windows containers` to start windows daemon or `switch to linux containers` in windows one in launch at startup.
Only the last daemon is relaunched when you start the application.
And there is only context so you need to switch every time you want to redirect cli to the appropriate engine.

**Comment by kamkie** [comment]
it would be really nice if we could use windows containers and `--platform` switch (like with wcow and lcow) but with wsl2 backend instead of lcow 

if this is something that you don't want to implement fell free to close this issue

**Comment by cerebrate** [comment]
I'd like to, shall we say, _strongly encourage_ the implementation of this, or if not this - although it is obviously the preferable option - then at least the ability to run Windows and Linux containers simultaneously and switch back and forth between controlling them using `docker context` .

Being able to mix container types in a single docker/single machine scenario is the key feature of Docker/WSL 2 for me. If that's not supported, there's not all that much to be gained over my previous practice of installing docker both on Windows and inside WSL.

**Comment by kamkie** [comment]
can we keep this open? 
having lcow and wcow at this same time was nice feature of first preview of docker desktop wsl2

**Comment by kamkie** [comment]
now tracked in https://github.com/docker/roadmap/issues/79 and https://github.com/docker/for-win/issues/6311
