### ISSUE TITLE
Had trouble starting Docker

### ISSUE THREAD

**Issue by dewens12** [docker/for-win#5075]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Prithviraj001** [comment]
I can't understand the issue, @dewens12  can u give detailed information about the issue ?
