### ISSUE TITLE
cat: can't open '/run/wsl-bootstrap.pid': No such file or directory

### ISSUE THREAD

**Issue by thnk2wn** [docker/for-win#5081]
- [ X ] I have tried with the latest version of my channel (Stable or Edge)
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID: E5488066-8079-4EC3-AF15-90B9D424A9B0/20191106125614

### Expected behavior
Docker Desktop on Windows with WSL 2 restarts without error

### Actual behavior
Docker desktop restarts with error:

<pre>
wsl exited with code 1. Stderr is:
cat: can't open '/run/wsl-bootstrap.pid': No such file or directory
sh: you need to specify whom to kill

   at Docker.Backend.ContainerEngine.WslEngine.DoStop()
   at Docker.Backend.ContainerEngine.WslEngine.Restart(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.BackendNamedPipeServer.<Run>b__8_3(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
</pre>

### Information

  - Windows Version: 10.0.19013.1
  - Docker Desktop Version: 2.1.5.0 (40323)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No Windows machine

### Steps to reproduce the behavior

This was working originally, not sure what triggered it.
  1. Installed prereqs for WSL2 on Windows and latest Docker
  2. Everything worked originally
  3. Built and pushed some containers
  4. Rebooted Windows
  5. Docker fails on startup and restart

**Comment by simonferquel** [comment]
Thanks for reporting this. We already have a fix for this issue and it will show up in a future release
