### ISSUE TITLE
Cannot get docker-compose up to work after latest Windows Fast Ring Insiders update.

### ISSUE THREAD

**Issue by Joe-Pena** [docker/for-win#5084]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
A1DA193C-15B2-455E-AF73-051E138DD72C/20191106160055
### Expected behavior
After booting up PC, docker starts by itself. WSL2 Backend is turned on, and Ubuntu is selected as the Distro of choice in the Resources section of settings.

Running the command `docker-compose up` in a directory with a `docker-compose.yml` should read the compose file and build up a container.

container should be running, and running `docker container ls` should show the containers.
### Actual behavior
After starting WSL2 (Ubuntu 18.4 LTS), running the `docker container ls` command shows there are no containers running, which is good, as it shows that docker is connected correctly, rather than showing a daemon error.

However, when running `docker-compose up` on any directory with a `docker-compose.yml` file, the images are downloaded succefully, but the containers themselves cannot be created, as this error keeps showing up:

```ERROR: for node-api_mongo-middleware_1  Cannot create container for service mongo-middleware: b"invalid volume specification: '/run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu/67ffe9d98f8e2071b230b69d060ee9b83418d7b277b8b5e645d29f3337a27ab2:rw'"```

It seems like there's a mounting issue? I know the WSL2 Backend blog post from a few days ago mentioned some limitations regarding mount points. However, this wasn't an issue yesterday, as it was working fine, before updating windows.

### Information

  - Windows Version: [Version 10.0.19018.1]
  - Docker Desktop Version: 2.1.5.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Start docker desktop, with WSL2 Backend active
  2. Try to run `docker-compose up` on any directory with a docker-compose.yml file.

**Comment by ad-on-is** [comment]
Same problem here, with a docker-compose file using nginx, php-fpm and mysql

**Comment by Joe-Pena** [comment]
I can confirm the above!

Ran through the docker-compose tutorial on the official docs. And docker-compose works, until I specify volumes.

If volumes are specified a lot of weird behavior occurs where folders get created with trailing `:`

**Comment by agustindidiego** [comment]
I'm also having issues with volumes after latest Windows Update and Docker for win update.
I'm testing with a postgres container. The container is created successfully, but mounted volumes are empty.
This happens when running docker linux version from inside wsl.
I'm specifying a volume for postgres entrypoint as:

`volumes:
        - ./postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d`
my relative path contains 3 init scripts, but after the container is started I check the /docker-entrypoint-initdb.d folder inside postgres container and it's empty
What I'm seeing is that volume host path is shown as:
`/run/desktop/mnt/host/wsl/Ubuntu-18.04/mnt/c/Users/me/project/docker/postgres/docker-entrypoint-initdb.d`
And I see on wsl ubuntu that a new path is being created on `/mnt/wsl/Ubuntu-18.04/mnt/c/../postgres/docker-entrypoint-initdb.d` but it's empty, it doesn't point to the actual path.
I already trying changing the wsl.conf root conf from /mnt/ to / and the same happens.
I also tried specifying an absolute path instead of a relative and the same happens.
Not sure if the issue is on docker-compose, wsl update or docker update. It seems that it is related with the new crossDomain feature.
It was working fine before these latests updates.

**Comment by simonferquel** [comment]
Thanks for reporting those bugs.
@agustindidiego the bug you have is different from the other ones, and I think you are running a build prior to 19018, or that you created the container prior to upgrading to 19018.

For the others, there seem to be a real issue with the new mount handler and compose. I'll have a look at this tomorrow.

**Comment by simonferquel** [comment]
Identified the root cause, will be fixed in next release

**Comment by Joe-Pena** [comment]
@simonferquel Great, thanks! Do you have any sort of ETA on the next release?

The work around I ultimately came up with was to uninstall docker and Ubuntu and reinstall everything again, except with Docker version 2.1.2.

It seems 2.1.5 did a number on my wsl2 installation that simply downgrading didn't fix it, so I had to wipe my wsl install and start from scratch.

**Comment by simonferquel** [comment]
@gtardif do we have an ETA for next Edge release?

**Comment by ad-on-is** [comment]
Is there any other workaround in the meantime, except setting up a fresh WSL 2 distro?

**Comment by pyarmak** [comment]
Having the same issue here.

**Comment by dmartinhorodrigues** [comment]
@ad-on-is I've "deactivated" the experimental engine in Docker Desktop 2.1.5 (hoping to revert any changes made by it to the WSL2 installation), uninstalled it and installed the latest version I had at hand - which was 2.1.0.
I'm just using a single Ubuntu 18 distro with WSL2 but everything seems to be working again.

**Comment by wildlyinaccurate** [comment]
Is there a workaround for this issue other than installing an old version?

**Comment by simonferquel** [comment]
Hmm wait for nov 12th is the best workaround I have, sadly.

**Comment by atrauzzi** [comment]
Would really love to see a workaround, even if it's a short time period.

**Comment by ad-on-is** [comment]
I just wrote a golang script for fun, which parses the docker-compose.yml and generates `docker run` commands with volumes, links, etc..

https://gitlab.com/ad-on-is/godoco

If you need other stuff from your docker-compose which is not implemented yet... feel free to grab the source and implement it yourself, since everything is mostly covered in the code and the rest is just a matter of copy&paste ;-)

**Comment by benoitscherrer** [comment]
Same problem here with docker swarm on Windows  10.0.19018.1 with the new Docker 2.1.5.0
Hope this is solved by 11/12 !
Thanks

**Comment by mshappe** [comment]
So, OK, yeah, Docker Desktop for WSL2 is beta and WSL2 itself is beta and we're all living dangerously. I get that.

But `docker-compose` with bind mounts is kinda core functionality. If that doesn't work, there's hardly any point. Telling us we get to twiddle our thumbs 'til the 12th is not really a great look.

**Comment by abresnev** [comment]
> 
> ### Funny workaround
> 
> I just wrote a golang script for fun, which parses the docker-compose.yml and generates `docker run` commands with volumes, links, etc..
> 
> https://gitlab.com/ad-on-is/godoco
> 
> If you need other stuff from your docker-compose which is not implemented yet... feel free to grab the source and implement it yourself, since everything is mostly covered in the code and the rest is just a matter of copy&paste ;-)

cannot unmarshal data: yaml: unmarshal errors:
  line 776: cannot unmarshal !!map into []string
  line 889: cannot unmarshal !!map into []string
  line 1116: cannot unmarshal !!map into []string

**Comment by rvanlaak** [comment]
Excited for nov 12! 🎉 

Would integration tests like running `docker-compose up` with a volume come in handy? That would allow making beta releases with a "known problems" section documented 😉

**Comment by newk** [comment]
Any update on when this bug will be fixed?

**Comment by simonferquel** [comment]
The release we planned for today has been postponed to later this week, sorry about this.

**Comment by vanstinator** [comment]
I still had the binary for the original WSL 2 release which I was able to roll back to and it works yet. It's not great. But it's a workaround.

**Comment by dasbuilder** [comment]
> @ad-on-is I've "deactivated" the experimental engine in Docker Desktop 2.1.5 (hoping to revert any changes made by it to the WSL2 installation), uninstalled it and installed the latest version I had at hand - which was 2.1.0.
> I'm just using a single Ubuntu 18 distro with WSL2 but everything seems to be working again.

That's what I figured. I had version 2.1.0 installed and had no issues running docker-compose. However, on this new version, that's not the case.

**Comment by dmartinhorodrigues** [comment]
> > @ad-on-is I've "deactivated" the experimental engine in Docker Desktop 2.1.5 (hoping to revert any changes made by it to the WSL2 installation), uninstalled it and installed the latest version I had at hand - which was 2.1.0.
> > I'm just using a single Ubuntu 18 distro with WSL2 but everything seems to be working again.
> 
> That's what I figured. I had version 2.1.0 installed and had no issues running docker-compose. However, on this new version, that's not the case.

So, as I was dealing with massive performance issues with v2.1.0, I've decided to bite the bullet and tried this uninstall/upgrade "method" with v2.1.4 (praying that it wouldn't implode WSL2 or something). Everything kept working the same! 

Hopefully, we'll get a proper fix soon 🙏

**Comment by gardwired** [comment]
can confirm that uninstall, downgrade to 2.1.4 then reboot worked ok for me.

**Comment by adrenallen** [comment]
@simonferquel any update on this?  At a standstill today, really trying to avoid rebuilding my WSL2 vm if possible.

**Comment by simonferquel** [comment]
Yes sorry, the build is almost ready to ship. I'll post a message here when you can update

**Comment by mathieumuller** [comment]
Any release date? I am hesitating to downgrade to 2.1.4 but it seems to be imminent, isn't it?

**Comment by mat007** [comment]
@mathieumuller 99% chance it’s going to be tomorrow.

**Comment by SlayerBirden** [comment]
To anyone asking about a workaround - I was able to "fix" it by switching "**volumes**" config in `docker-compose.yml` to the more verbose way (https://docs.docker.com/compose/compose-file/#volumes). Though it'll only work on 3.7 afaik...

**Comment by simonferquel** [comment]
It has shipped! 2.1.6.0 fixes this issue

**Comment by newk** [comment]
Installing now! Will update feedback as soon as I try. TY

**Comment by bushidocodes** [comment]
Just installed. Now seems to work as expected! 🙌👏

**Comment by agustindidiego** [comment]
I confirm it is now working.
I'm noting a bit of slowness by running a fresh Laravel site(Homepage is taking between 7 and 10 secs to load ) but I don't know the reason, I will compare it by running the same container without WSL

**Comment by gmsantos** [comment]
Docker 2.1.6.0 was released o/

**Comment by gmsantos** [comment]
working like a charm! thank you @simonferquel

**Comment by jdibling** [comment]
Somethin's not right here. Was working fine on 2.1.4, I skipped 2.1.5, and just installed 2.1.6. Now I get this:

jdibling@LAPTOP-BJVVKFT7:~/repos/gitlab.com/stream-ai/svc-xcr$ docker-compose up
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
jdibling@LAPTOP-BJVVKFT7:~/repos/gitlab.com/stream-ai/svc-xcr$

**Comment by gmsantos** [comment]
@jdibling it's seems like another issue. Docker WLS2 backend changed a lot in 2.1.5.0. Now docker daemon runs in a separate WSL2 distro (see https://engineering.docker.com/2019/10/new-docker-desktop-wsl2-backend/)

Did you integrated your distro with WSL2?

![image](https://user-images.githubusercontent.com/1991286/69095953-2b573700-0a32-11ea-8cda-410be688c2b6.png)

**Comment by jdibling** [comment]
Thanks for the quick response, @gmsantos . I'll check that now and reply here.

**Comment by Silic0nS0ldier** [comment]
One other thing to be aware (since it has caused issues for me) is that you may need to uninstall the existing Docker Desktop version first for the 2.1.4 to 2.1.5 upgrade, when I do a version upgrade normally the WSL Integration resource section doesn't show up and misc other issues also make their presence known.

**Comment by jdibling** [comment]
@Silic0nS0ldier , I typically do the same, but I didn't this time due to laziness. I'm happy to report that it's working nonetheless, which is more I can say for previous updates I've attempted without doing an uninstall first. Maybe I got lucky, or maybe the installer is more stable now.

**Comment by adrenallen** [comment]
Working for me now as well, didn't have to uninstall old version just went through with the typical update process. 👍
