### ISSUE TITLE
Docker Desktop causing issues launching and converting WSL2 distros

### ISSUE THREAD

**Issue by sirredbeard** [docker/for-win#5085]
Docker Desktop appears to bind port 53 and sporadically cause problems launching and converting WSL2 distros.

Here is a report of it interfering with launching distros that was closed because the OP was unable to reproduce: https://github.com/docker/for-win/issues/4772. However there have been subsequent reports of this issue in that thread.

This issue is sporadic. Here is another thread on WSL: https://github.com/microsoft/WSL/issues/4364. In this thread it is seen the issue can occur on first run, subsequent run, and also when converting to WSL2, which is where I encountered it.

@simonferquel Is this the sporadic HNS bug you have referred to elsewhere?

I encountered this on Docker Desktop 2.1.5 edge and Windows 10 build 19018.

![Annotation 2019-11-06 185146](https://user-images.githubusercontent.com/33820650/68347942-813cee00-00c6-11ea-9533-f1837f80df77.png)

The solutions seem to focus on killing Docker services holding onto port 53.

I ended up having to manually stop Docker services using service name, PID, and manually before I could convert a distro to WSL2:

![Annotation 2019-11-06 181530](https://user-images.githubusercontent.com/33820650/68347381-b9dbc800-00c4-11ea-8b9f-67d2d952eef7.png)

**Comment by simonferquel** [comment]
Yes, HNS does not want any process to listen on port 53 on any interface to work properly. The problem is that we need to listen on port 53 to ensure cross-container communication with windows containers (on the HNS interface plugged to that container). I think we also run a DNS server somewhere for Linux containers with docker desktop. For this one, I'll investigate if we can change the port.

**Comment by simonferquel** [comment]
@stephen-turner I think we need a meeting with folks from HNS team at Microsoft. I don't think listening on port 53 on the host should kill HNS. In the meantime, I'd like to see with @djs55 if we can somehow run the DNS server on another port.

**Comment by simonferquel** [comment]
First quicklook at our DNS handling for Linux containers seem to indicate we already listen on a random port instead of 53. Do you see the problem happen only with Windows Containers enabled, or does it happen in Linux Containers mode as well ?

**Comment by simonferquel** [comment]
https://github.com/docker/libnetwork/blob/d0ae17dcfaa1f21e3b0f5d55bba4239f08489640/network_windows.go#L30 <- libnetwork does that for each HNS network that is not ICS (it maps the notion of docker networks to HNS networks on Windows).
Do we know someone from the HNS team who could have a look at why it breaks HNS ?

**Comment by sirredbeard** [comment]
It happened when I was using Windows containers.

Just so you know I was using Windows containers because the Linux containers would not start when run inside Hyper-V.

**Comment by Silic0nS0ldier** [comment]
I've also hit this issue while Windows containers was being used (under 2.1.4.0 this was to avoid having the Hyper-V Linux container start). Haven't hit this under 2.1.5.0 and likely won't anytime soon as there are other issues blocking me from switching over (I use lando.dev which I've been unable to get running under the 2.1.5.0, have have been able to under 2.1.4.0 via the Linux binary).
