### ISSUE TITLE
Anti-virus or Registry permissions preventing Run Registry modifications causes installation to fail

### ISSUE THREAD

**Issue by mushroomTeladi** [docker/for-win#5087]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Installer succeeds, or warns if AutoRun registry key cannot be added.

As the upgrade process appears to uninstall the previous version of Docker, this error effectively leaves the system without Docker.

### Actual behavior
Installer fails and rolls back with the following error:

```
Attempted to perform an unauthorized operation.
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   at CommunityInstaller.AutoStartAction.DoAsync(CancellationToken cancelToken)
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackage>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()
```

Windows Event Log explains why, as an event emitted by the corporate anti-virus (McAfee Endpoint Security) running on my laptop:

```
EventID=1092

<usrname> ran Docker Desktop Installer.exe, which tried to access HKCU\SOFTWARE\MICROSOFT\WINDOWS\CURRENTVERSION\RUN\DOCKER DESKTOP, violating the rule "Registering of programs to autorun", and was blocked. For information about how to respond to this event, see KB85494.
```

### Information

  - Windows Version: 10 Enterprise 17.09 Build 16299.1451
  - Docker Desktop Version: 2.1.0.4, 2.1.0.1, 2.0.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

Reproducible with registry permissions.

  1. Open Regedit.exe and remove "Full Control" permissions on Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run for your user and Administrators.
  2. Run installer.

Alternatively, configure your anti-virus to disallow adding of new AutoRun registry entries.

**Comment by guaranadev** [comment]
I'm having the same issue. The installer should at least install docker without autorun and not give a meaningless stack trace
