### ISSUE TITLE
Failed to share drives

### ISSUE THREAD

**Issue by superbull** [docker/for-win#5092]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 44F9C76C-F4AB-48FF-948F-5FFBDA1823A4/20191107101740

### Expected behavior
Can share drive successfully.

### Actual behavior
Firewall detected.

### Information

  - Windows Version: 10 (1803)
  - Docker Desktop Version: 2.1.0.4(39773)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No
  - I am inside corporation network.
  - I followed the documentation to open port 445 but with no luck.

### Steps to reproduce the behavior

  1. share drives

I guess this is caused by some company policy, could someone give me some hints how to find the root cause?

**Comment by djs55** [comment]
@superbull thanks for your report. There's a completely new drive sharing mechanism in the latest edge release which shouldn't be blocked by the firewall.

In case it's useful I've written instructions for setting up and testing the new file sharing implementation available in the edge channel here: https://github.com/docker/for-win/issues/5139#issuecomment-559700215

**Comment by stephen-turner** [comment]
This is fixed with the new filesharing implementation in 2.2.0.3, so closing this ticket.
