### ISSUE TITLE
After Sleep: error during connect: Get http:////./pipe/docker_engine/v1.40/containers/json:  open //./pipe/docker_engine: The system cannot find the file specified.

### ISSUE THREAD

**Issue by thnk2wn** [docker/for-win#5093]
- [ X ] I have tried with the latest version of my channel (Stable or Edge)
  - [ X ] I have uploaded Diagnostics
  - Diagnostics ID: E5488066-8079-4EC3-AF15-90B9D424A9B0/20191107125902

### Expected behavior
When the machine wakes up from sleep Docker Desktop resumes successfully as it was working before sleep.

### Actual behavior
Upon waking up from sleep (in my case returning to my work computer some 15 hours later the next day) the following initial error is present.

<pre>
error during connect:
Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/json: 
open //./pipe/docker_engine: The system cannot find the file specified.
In the default daemon configuration on Windows, the docker client 
must be run elevated to connect. 
This error may also indicate that the docker daemon is not running.

   at Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning)
   at Docker.Backend.ContainerEngine.WslEngine.Start(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.BackendNamedPipeServer.<Run>b__8_2(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
</pre>

### Information

  - Windows Version: 10.0.19013.1
  - Docker Desktop Version: 2.1.5.0 (40323)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No
  - Using WSL 2: Yes

### Steps to reproduce the behavior

  1. Ensure Docker Desktop is running
  2. Let the machine sleep / go idle overnight
  3. Log back on the next morning and attempt to use

Alternative versions of above are logging off at the end of the day or restarting at the end of the day and attempting to use Docker the following day.

**Comment by simonferquel** [comment]
I think we have a fix for that comming in next week build (you'll need to update to Windows Insider 19018+ though).

**Comment by SlayerBirden** [comment]
Hi @simonferquel is there an update? I'm on 10.0.19023.1 (Windows) and 2.1.5.0. I see this error every time my computer is starting after sleep/restart/shutdown. Thankfully workaound from #5082 works for me.

**Comment by simonferquel** [comment]
Version 2.1.6.0 has just shipped with lots of bug fixes :)
