### ISSUE TITLE
wsl integration with fedora remix not working

### ISSUE THREAD

**Issue by kamkie** [docker/for-win#5107]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 2C04910D-279C-4E1D-A9C5-456EF18DAC0E/20191109111709

### Expected behavior
wsl2 integration works with fedora-remix

### Actual behavior
integration fails to start

### Information
[12:14:12.400][WslIntegrationAgent-fedoraremix][Info   ] 2019/11/09 12:14:12 Unable to setup docker user group: exit status 127
[12:14:12.404][WslIntegrationAgent-fedoraremix][Warning] Failed to setup docker group in distro, disabling integration

windows 19018
docker edge 2.1.5

**Comment by simonferquel** [comment]
Thanks for your feedback, this issue has been fixed and will roll-out in next release :)

**Comment by kamkie** [comment]
same problem with openSUSE-Leap-15-1

**Comment by simonferquel** [comment]
The fix also applies to Open Suse

**Comment by ntrp** [comment]
Any eta on when will it be released? Just to have an idea

**Comment by kamkie** [comment]
you can use small script as a workaround 
```
sudo /mnt/wsl/docker-desktop/docker-desktop-proxy --distro-name fedoraremix --docker-desktop-root /mnt/wsl/docker-desktop
```

**Comment by ntrp** [comment]
Thanks but unfortunately I don't have that file structure in my `/mnt/wsl`, I'm using ArchWSL

**Comment by ntrp** [comment]
is there any way to manually activate the integration? Any code snippet on what that is doing?
My `/mnt/wsl` is populated with plenty of files and filesystems (docker, k8s etc).

**Comment by kamkie** [comment]
i noticed this same problem with alpine 
adding wsl.conf from ubuntu solved this problem 
```
kamkie@kamkie-ROG:~$ cat /etc/wsl.conf
[automount]
enabled     = true
crossDistro = true
root        = /mnt/
```
but then i got strange problems 
maybe it will be all that's needed for you

**Comment by ntrp** [comment]
I tried that but it does not change anything.. anyway it looks to me that the WSL directories are mounted so I don't think that this config is relevant.

A link to the commit that fixed the issue would be really useful..

**Comment by ntrp** [comment]
Ok I'm sorry but that script actually appeared after rebooting and worked in the end.. I thought that it was enough to call `wsl --shutdown` to reset the machine

**Comment by ntrp** [comment]
Actually after changing that file and rebooting the file you mentioned appeared.. I thought it was enough to run `wsl --shutdown`.

It ultimately works but I hope the next release comes fast ^^'

**Comment by kamkie** [comment]
works in 2.1.6

**Comment by magneticflux-** [comment]
@kamkie I've tried the script you suggested and it just hangs. If I pass it `--kill` as well, it immediately finishes, but doesn't do anything as far as I can tell. I'm running `sudo /mnt/wsl/docker-desktop/docker-desktop-proxy --distro-name WLinux --docker-desktop-root /mnt/wsl/docker-desktop`.

**Comment by simonferquel** [comment]
@magneticflux- can you upload a diagnostic ? There are several reasons why the agent would crash. We fixed a few in the build that should land this week, but a diagnostic file would help me confirm if you need something else.
By any chance, did you change the default shell of the root user in your distro ?
