### ISSUE TITLE
lstat D:\1\data-storage.jar: no such file or directory during ADD

### ISSUE THREAD

**Issue by vvsh** [docker/for-win#511]
Dockerfile:

FROM schickling/opencv

ARG jarfile
WORKDIR /usr/app
ADD ${jarfile} /usr/app

I am building image using the following image:

docker build --build-arg jarfile=D:\1\data-storage.jar .

### Expected behavior

Jar is copied into a container.

### Actual behavior

Sending build context to Docker daemon 2.048 kB
Step 1/4 : FROM schickling/opencv
 ---> 29c2513b623b
Step 2/4 : ARG jarfile
 ---> Using cache
 ---> bea013266018
Step 3/4 : WORKDIR /usr/app
 ---> 43d12efcec3c
Removing intermediate container bd17187f6767
Step 4/4 : ADD ${jarfile} /usr/app
lstat D:\1\data-storage.jar: no such file or directory

### Information

Windows 10 Enterprise, hyper-v

Why does it happen?
Thanks

**Comment by friism** [comment]
The source of the `ADD` most be in the context of the build (i.e. the `.` in `docker build`). Details here: https://docs.docker.com/engine/reference/builder/#/add

I'm closing this issue for now. If you have follow-up questions on how to use Docker, please start a topic on the [Docker Forums](https://forums.docker.com/c/docker-for-windows) (this issue tracker is for reporting bugs and problems).
