### ISSUE TITLE
Giant log.0.txt file in AppData directory

### ISSUE THREAD

**Issue by sixcorners** [docker/for-win#5113]
I found a 17GB log file in my AppData\Local\Docker directory.
Shouldn't these things be smaller?
It was log.0.txt or log0.txt I forget which.

**Comment by kostelnyy** [comment]
same issue. @sixcorners did you find a solution?

**Comment by mat007** [comment]
Thanks for reporting this, we hadn’t realized this as we keep wiping and re-installing Docker Desktop all day long…
We’ll fix it as soon as possible.

@kostelnyy you can simply delete it, it’s just a log file.

**Comment by feltz916** [comment]
this never got fixed btw..
