### ISSUE TITLE
Map TCP port to host ip not working (Edge)

### ISSUE THREAD

**Issue by edrevo** [docker/for-win#5114]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 315815B6-CD38-4A84-8B00-DD3472824094/20191110081942

### Expected behavior
Port forwarding bound to a specific IP address should work.

### Actual behavior
```
failed programming external connectivity on endpoint fervent_easley (44aec7ef6f293cf0c5e1fa828ca378b108e9826aa076a713070fbbe16e6804f1): Error starting userland proxy: listen tcp 192.168.1.23:80: bind: cannot assign requested address.
```

### Information
I get the same behavior both in the MobyVM daemon and in the WSL2 daemon. I wasn't able to reproduce this issue on the lastest stable versions of Docker and Win10.

I have 2 IPs set in my network adapter, but I removed one of them to see if the issue disappeared and it still happened. Binding to 127.0.0.1 did work though.

  - Windows Version: Win 10 19018.1
  - Docker Desktop Version: 2.1.5.0 (40323)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: ❌ 

### Steps to reproduce the behavior

  1. `docker run --rm -it -p 192.168.1.23:9090:9090 alpine sh`

**Comment by simonferquel** [comment]
@djs55 can you have a look at this one ?

**Comment by marekmartins** [comment]
Any news regarding this? I have similar issue.
