### ISSUE TITLE
Unable to start - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'DockerDesktopVM' failed to start.

### ISSUE THREAD

**Issue by BrightRan** [docker/for-win#5118]
Unable to start - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'DockerDesktopVM' failed to start.

Failed to start the virtual machine 'DockerDesktopVM' because one of the Hyper-V components is not running.

'DockerDesktopVM' failed to start. (Virtual machine ID A8EA9B3A-E734-4563-8C78-B2A2AC8C8726)

The Virtual Machine Management Service failed to start the virtual machine 'DockerDesktopVM' because one of the Hyper-V components is not running (Virtual machine ID A8EA9B3A-E734-4563-8C78-B2A2AC8C8726).

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.<>c__DisplayClass36_0.<SwitchDaemon>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

**Comment by minoseah629** [comment]
i have seen this error recently.  check your windows features.  

Containers, Hyper-V, Windows Hypervisor Platform, VIrtual Machine Platform. 

one of them might not be needed 

![image](https://user-images.githubusercontent.com/1980068/68688926-9c33b600-053d-11ea-9bee-513a57a64cb9.png)

**Comment by BrightRan** [comment]
I only enabled Hyper-V.
I installed the Docker on my VM with Win10 OS (Version1903), this problem has been happening since the installation of Docker.

**Comment by minoseah629** [comment]
i had an issue installing with 2.1.4.0 and 2.1.5.0 on windows 10.  i looked around in the other issues and it appears to be many people.  

The first issue i listed is a few hours ago and the other issue is 13 days ago.  
#5127 #5041 

As an alternative, I created a window server 2019 hypervisor and ran 2.1.5.0 on it with no issue. 

just frustrating.

**Comment by BrightRan** [comment]
Yeah, looks like many people have this trouble.
I also tried some regular solution steps like as:
● enable hyper-v (windows features)
● netcfg -d (powershell)
● reboot

But they all do not work.
