### ISSUE TITLE
Unable to login to a private registry if Kubernetes feature is turned on

### ISSUE THREAD

**Issue by nolmit** [docker/for-win#5121]
Login to a secure private docker repository (pull image also) throws an error in case of Kubernetes feature is turned on:

> Error response from daemon: Get https://harbor-registry.xxxxx.com/v2/: dial tcp 10.1.1.81:443: connect: no route to host

### Information
  - Windows Version: Win10, 10.0.17763
  - Docker Desktop Version: 2.1.0.4
  - Docker configurations: default
  - Works fine on Docker Desktop for macOS

### Steps to reproduce the behavior
  1. Install docker desktop
  2. Perform docker login to a secure private repository:
      _docker login  https://harbor-registry.xxxxx.com --username 'user' --password 'pass'_
      ### Actual behavior: Login Success
 3.  Turn Kubernetes feature on, wait for complete
 4. Perform docker login to a secure private repository once again

### Actual behavior:
Error response from daemon: Get https://harbor-registry.xxxxx.com/v2/: dial tcp 10.1.1.81:443: connect: no route to host
### Expected behavior
Login should be success

**Comment by simonferquel** [comment]
@guillaumerose this is an issue with our static CNI bridge CIDR. 
Thanks for the feedback @nolmit, we don't (yet) allow users to customize the Cluster CIDR which is statically defined as 10.1.0.0/16. Unfortunately that means that when trying to reaching 10.1.1.81 (the IP of your registry), the daemon will take a route to the local Kubernetes network.

I think we need to provide a way for the user to customize this, I'll put this on our backlog, but can't commit on a specific time-frame for resolving the issue.

**Comment by nolmit** [comment]
Thank you for clarification, @simonferquel.  May be it would be good to have this documented somewhere (if it's not already)?

**Comment by aelmanaa** [comment]
hello @simonferquel 

thanks for the info. agreed with @nolmit I spent few hours trying to figure out the issue. was even thinking that was a problem with my firewall :(
Indeed, it's good to document this limitation
