### ISSUE TITLE
Kubernetes cluster fails to start. Using WSL2 features.

### ISSUE THREAD

**Issue by marcusm** [docker/for-win#5124]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 5E664D64-52AD-4448-8683-B1E19DDC8249/20191112230641

### Expected behavior
Kubernetes server should start when checked

### Actual behavior
Kubenetes failes to start.
### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by simonferquel** [comment]
Hmm from your diagnostic file, I see a working Kubernetes cluster. Can you describe what is not working exactly ?
