### ISSUE TITLE
Need to delete old WSL2 context

### ISSUE THREAD

**Issue by aaronsteers** [docker/for-win#5125]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

After updating to the latest edge version of Docker Desktop, I expect previous "context" settings to be cleaned up and aligned with the new "wsl2 backend".

### Actual behavior

After updating to the latest edge version of Docker Desktop, the previous "context" is not cleaned up. The new "wsl2" version is (or appears to be) running under "default" and the "wsl2" version is still there (selected or deselected depending upon user's action). Linux-based clients have not "context" command so it is not possible to get similar info.

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

It appears that users can (should?) run the following after the upgrade:

```
docker context use default
docker context rm wsl
```

Performing these tasks appears to be necessary in order to prevent later confusion around which version of the backend is running (since both versions now seem to use the same "default" context).

Confirmation appreciated - since I was not able to find any guidance on this in the provided documentation.

### Steps to reproduce the behavior

  1. Upgrade to the latest edge version
  2. Run `docker context ls` from a windows command prompt.

Output is misleading since `default` apparently is now the "real" WSL2 option:

```
NAME                DESCRIPTION                               DOCKER ENDPOINT                  KUBERNETES ENDPOINT                                 ORCHESTRATOR
default *           Current DOCKER_HOST based configuration   npipe:////./pipe/docker_engine   https://kubernetes.docker.internal:6443 (default)   swarm
wsl                 Docker daemon hosted in WSL 2             npipe:////./pipe/docker_wsl
```

**Comment by pdebruin** [comment]
"Docker" and "kubectl" command not found in WSL2 (OS Build 19041) with Docker Desktop (2.1.7). Apparently due to docker context mix-up, since the above steps helped fix it.
