### ISSUE TITLE
top args cause to error

### ISSUE THREAD

**Issue by roie4job** [docker/for-win#513]
### Expected behavior
the command:
docker top [container_id] args1 arg2 ...
will return the same output as:
docker exec [container_id] ps  args1 arg2 ...

### Actual behavior
output is:
Error response from daemon: Error running ps: exit status 1

### Steps to reproduce the behavior

 1. docker run tomcat:8.0
 2. docker top [container_id] -e -o pid,lstart,pcpu,pmem,sz,ni,stat,cmd

### Information
 working on windows 10

Output of  docker version :
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: true

Output of  docker info :
Containers: 14
 Running: 1
 Paused: 0
 Stopped: 13
Images: 6
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 101
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.8-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.941 GiB
Name: moby
ID: KBZQ:5QHB:AZ3R:YD3F:C75G:OGQA:6YIT:D46Z:CDSI:D2N5:7MZT:MYTH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 20
 Goroutines: 31
 System Time: 2017-02-19T07:57:39.1496673Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by dgageot** [comment]
See https://github.com/docker/docker/issues/31161

**Comment by dgageot** [comment]
@justincormack wdyt?

**Comment by justincormack** [comment]
We could add GNU `ps` to Moby instead of the default one, I think we may have an internal issue for this from way back. I still think it is a bug in Docker that it does not actually define it. Also I think the docker containers we ship do not have GNU `ps`, and it is not listed as a requirement, its kind of annoying.

**Comment by friism** [comment]
Internal issue is `3491`. Also reported here: https://forums.docker.com/t/docker-top-appears-to-behave-differently-than-on-linux-systems/13326/2
