### ISSUE TITLE
Windows 10 1909: Running older Windows version image in process isolation

### ISSUE THREAD

**Issue by Sam13** [docker/for-win#5148]
As far as I have interpreted the new features of Windows 10 Version 1909 it should be possible to run an image which is based on an older Windows version in process isolation.
But if I try that it fails.

I'm using latest Docker Desktop Community 2.1.0.4 on Windows 10 Pro Version 1909 (OS Build 18363.476).

When I try to run the command:
_docker run --rm -it --isolation=process mcr.microsoft.com/windows/servercore:ltsc2019 cmd.exe_

I get an error: _Error response from daemon: hcsshim::CreateComputeSystem db5ee1a1e644ee26d6be4d86d70cb372b114119d2ce1edad6a4b6c6ec8ca767d: The system cannot find the file specified._

Running the same image with Hyper-V isolation works:
_docker run --rm -it mcr.microsoft.com/windows/servercore:ltsc2019 cmd.exe_

Running the 1909 image in process isolation also works:
_docker run --rm -it --isolation=process mcr.microsoft.com/windows/servercore:1909 cmd.exe_

Does Windows 1909 not provide this feature or is there some additional configuration which needs to be done?

**Comment by StefanScherer** [comment]
It works with the previous semi-annual image 1903, but not with 1809/ltsc2019.

```
PS C:\Users\docker> docker run -it --isolation process mcr.microsoft.com/windows/servercore:1903 powershell.exe
Unable to find image 'mcr.microsoft.com/windows/servercore:1903' locally
1903: Pulling from windows/servercore
5b663e3b9104: Pull complete                                                                                                                         9b19620c6c6c: Pull complete                                                                                                                         
Digest: sha256:06b2a8750b5245ffbb4dedd603dbde323a6694fac3705e73e6a6c389d12e7baa
Status: Downloaded newer image for mcr.microsoft.com/windows/servercore:1903
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\> cmd
Microsoft Windows [Version 10.0.18363.476]
(c) 2019 Microsoft Corporation. All rights reserved.
```

I'll close this ticket as it's not related to Docker Desktop, it's a feature of Windows to support process isolation. Nothing we can do here. Things in Windows Container world sometimes isn't that backward compatible.

**Comment by Sam13** [comment]
Thanks for the clarification. Too bad that I did not test version 1903...
Perfectly valid to close the ticket - this was more a question than an actual bug report.

For me this means all my images need to be at least version 1903 if I want to use this feature.

Do you know whether version 1903 is the minimal version to use also for future Windows versions or does this feature always require a "similar" Windows version to work?

**Comment by StefanScherer** [comment]
I don‘t know 🤷‍♂️ 😀

**Comment by StefanScherer** [comment]
Linking https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/1286 for reference.
