### ISSUE TITLE
Mysql cannot be reached when running in Windows

### ISSUE THREAD

**Issue by mchadwickchennault** [docker/for-win#516]
### Expected behavior
Docker containers should work consistently across platforms. Specifically, my container should be able to connect to mysql in OS X and Windows 10 Anniversary.

### Actual behavior
Cannot connect to mysql on Windows 10 Anniversary.

### Information
The following docker-compose.yml works perfectly in OS X, but not in Windows.
```version: '2'
services:
  mysql:
    container_name: manager_mysql
    build: ./mysql
    image: mysql:tag
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: manager
    volumes:
      - ./mysqldata:/var/lib/mysql
  php:
    container_name: manager_php
    build: ./php
    image: php:tag
    ports:
      - '80:80'
    volumes:
      - ../../manager:/manager
      - ~/.composer:/root/.composer
      - ~/.ssh:/root/.ssh
    depends_on:
      - mysql
volumes:
  db:
```

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
     FA409F44-A90A-48F2-A386-57C90F0A4878/2017-02-22_10-57-13
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)
    Windows 10 Pro 10.0.14393 build 14393

### Steps to reproduce the behavior

  1. docker-compose up -d
  2. docker-compose run php bash
  3. mysql -h mysql -u **** -p
  4. ERROR 2005 (HY000): Unknown MySQL server host 'mysql' (0)

**Comment by friism** [comment]
@mchadwickchennault the service host name is not expected to be available from the host. If you're connecting from the host, connect to `localhost` on port 3306.

**Comment by mchadwickchennault** [comment]
Thank you for the quick feedback.

I am attempting to connect from the "php" container, not the "mysql" container.

`mysql -h localhost -u **** -p` results in `ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)`

Also, connecting to "mysql" works in OS X.

**Comment by simonferquel** [comment]
Can you try without mounting any volume in the MySQL service ?

**Comment by mchadwickchennault** [comment]
I tried that and it does work. I can get the MySQL service working without volumes. Then start it again with a shared volume and it works... temporarily. However, if I rebuild my containers, it breaks again.

**Comment by mchadwickchennault** [comment]
I think I have resolved my issue with mysql not starting in Windows. The trick was to remove `innodb_flush_method='O_DIRECT'` from my.conf relative to this issue: https://bugs.mysql.com/bug.php?id=79200 
Why this only causes issues in Windows and not Mac is still a mystery to me.

**Comment by friism** [comment]
@mchadwickchennault thanks for following up. For mounting volumes from the host, Docker for Windows using samba/CIFS. Most likely, default innodb relies on filesystem semantics that are not honored by samba.

I'm glad you found a workaround! As suggested by @simonferquel, not mounting the database data-directory from the host should solve the problem too.
