### ISSUE TITLE
Docker 2.1.5 within Linux engine WSL 2 crashes on restart No images necessary

### ISSUE THREAD

**Issue by martin0** [docker/for-win#5162]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:29379D0A-3BD2-4A87-A2BA-67B33F2AAC30/20191118084022

### Expected behavior
Expect to be able to configure and then restart successfully using new configuration

### Actual behavior
Crashes on startup
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

   at Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning)
   at Docker.Backend.ContainerEngine.WslEngine.Start(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.BackendNamedPipeServer.<Run>b__8_2(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

### Information

  - Windows Version:1903 (build 19013.11.22)
  - Docker Desktop Version: 2.1.5.0 (40323)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Using WSL 2 based engine

### Steps to reproduce the behavior

  1. ...Install docker, chose WSL2 based engine.
  2. ...Select WSL integration distro
3 reboot windows (my initial test appeared to succeed, but this morning  it fails)

**Comment by martin0** [comment]
I was able to run it after restarting the Windows service Docker Desktop Service. I'll leave this open a little longer to confirm no further issue with startup

**Comment by ma-bourassa** [comment]
Exact same problem here. I also have this exact configuration
- Windows Version:1903 (build 19013.11.22)
- Docker Desktop Version: 2.1.5.0 (40323)
- Running with WSL 2

I use this to restart the Docker service but it needs to be done each time I restart the PC. 
```
Net stop com.docker.service
Net start com.docker.service
```

**Comment by simonferquel** [comment]
This should be fixed in 2.1.6.0

**Comment by martin0** [comment]
2.1.6 says WSL 2 engine requires Windows Build 19018 or higher - this requires being on the fast ring, rather than the slow ring.
Any recommendations?

**Comment by martin0** [comment]
For now I'm switching back to Hyper-V mode

**Comment by simonferquel** [comment]
That is the safest way, indeed. The other solution would be to switch to fast ring.

**Comment by martin0** [comment]
I was happy just re-starting the windows service. I may just go back to 2.1.5.
However i hit another problem - to do with mariadb. This was fine initially, so I'm confused about that.
