### ISSUE TITLE
Docker Containers For Windows no longer creating VPN NAT/VMSWITCH objects in windows 10 1903/1909 host

### ISSUE THREAD

**Issue by dubblies** [docker/for-win#5165]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
NAT to VPN tunnel adapter should be created when accessing VPN resources

### Actual behavior
No NAT is created but is instead created against the LAN/WIFI adapter or not at all

### Information
I have spent a lot of time testing to find differences and it appears that in windows 10 1809, docker will automatically create a NAT from my containers IP to the VPN adapter when accessing VPN resources. This no longer happens in windows 10 1903/1909. I have tried various combinations of no windows firewall, no AV, etc. This seems to be the default networking in docker that is not creating the NAT objects.

Further - in 1809 in hyperv a vmswitch for "nat" is created and an interface paired to it. This fails in 1903/1909. I had originally found an event with hyper-visor saying it could not create the switch but i have not dug back in to relocate it. 
If you check your vmswitches it wont exist in 1903/1909 but shows in 1809 (get-vmswitch). The interface however does exist (get-netipinterface). It appears that the NATing is not happening because there is no switch associated to the NAT. 

Creating the vmswitch leaves you with a duplicate "nat" interface (vEthernet (nat) 2). I am still working through possibly doing the networking manually to see if this is just a race condition or order of operations but I have not yet made it that far. I have seen A LOT of posts about this very issue.

### Steps to reproduce the behavior
Use windows 10 1809 default installation, works fine
Ugrade to/fresh install windows 10 1903/1909 and it happens immediately, default install.

use commands like get-netnatsession to see the NATs. The NATs are created on the fly when accessing a resource so youll need to hit the internet inside a container before seeing any NATs on the host windows 10 machine.

**Comment by mikeparker** [comment]
To be clear, are you running Docker Desktop, or running Docker on windows server?

**Comment by dubblies** [comment]
> To be clear, are you running Docker Desktop, or running Docker on windows server?

Docker Desktop

**Comment by mikeparker** [comment]
Which version are you using? 
We changed a lot of the NAT code in latest edge, can you try that? 
https://docs.docker.com/docker-for-windows/edge-release-notes/

**Comment by jbaarsch2** [comment]
/remove-lifecycle stale

This is still a issue, not if using the edge version will meet our needs. Any word on edge version and NAT over VPN?  I do not want to install edge just to run the test, but will keep it in mind if I cannot find another work around....
