### ISSUE TITLE
Kubernetes fails to start on fast ring w/ 2.1.6.0 and wsl 2 ubuntu 18.04

### ISSUE THREAD

**Issue by moolbits** [docker/for-win#5173]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D8561184-220D-41CF-9566-546C4AA1914D/20191119072541

### Expected behavior

Enabling Kubernetes should start a single node cluster, and indicate that it's running.

### Actual behavior

Enabling Kubernetes does not work, spins up some system containers for k8s, but ultimately indicates that it 'failed to start'.

### Information

  - Windows Version: Build 19025
  - Docker Desktop Version: 2.1.6.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Clean install Build 19025 
  2. Make sure virtualization and container support is enabled
  3. Enable WSL
  4. Install Ubuntu 18.04
  5. Set distro to be backed by WSL 2
  6. Install Docker Edge 2.1.6.0
  7. Enable WSL 2 based engine
  8. Enable WSL Integration for Ubuntu-18.04 under Resources
  10. Enable Kubernetes

**Comment by simonferquel** [comment]
In the logs, I see that Kube-proxy fails (which makes everything else fail):
```
I1119 07:26:06.453926       1 conntrack.go:52] Setting nf_conntrack_max to 524288
I1119 07:26:06.454313       1 conntrack.go:83] Setting conntrack hashsize to 131072
F1119 07:26:06.454423       1 server.go:449] write /sys/module/nf_conntrack/parameters/hashsize: operation not supported
``` 
Are you running wsl2 with a custom kernel ?

**Comment by simonferquel** [comment]
Ok, after investigation, it is a real issue happening with machines with many processors. I'll create a PR to fix that.

**Comment by zailic** [comment]
I have similar issue. 
```
kubectl logs -p kube-proxy-vqw4s -n kube-system
W1119 10:29:50.434321       1 proxier.go:500] Failed to read file /lib/modules/4.19.79-microsoft-standard/modules.builtin with error open /lib/modules/4.19.79-microsoft-standard/modules.builtin: no such file or directory. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W1119 10:29:50.435676       1 proxier.go:513] Failed to load kernel module ip_vs with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W1119 10:29:50.436591       1 proxier.go:513] Failed to load kernel module ip_vs_rr with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W1119 10:29:50.437559       1 proxier.go:513] Failed to load kernel module ip_vs_wrr with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W1119 10:29:50.438638       1 proxier.go:513] Failed to load kernel module ip_vs_sh with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W1119 10:29:50.439631       1 proxier.go:513] Failed to load kernel module nf_conntrack with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W1119 10:29:50.443714       1 server_others.go:249] Flag proxy-mode="" unknown, assuming iptables proxy
I1119 10:29:50.458480       1 server_others.go:143] Using iptables Proxier.
W1119 10:29:50.458597       1 proxier.go:321] clusterCIDR not specified, unable to distinguish between internal and external traffic
I1119 10:29:50.458881       1 server.go:534] Version: v1.15.5
I1119 10:29:50.466897       1 conntrack.go:52] Setting nf_conntrack_max to 131072
I1119 10:29:50.467218       1 conntrack.go:83] Setting conntrack hashsize to 32768
F1119 10:29:50.467287       1 server.go:449] write /sys/module/nf_conntrack/parameters/hashsize: operation not supported
```

Docker version: 2.1.6.0
wsl 2 kernel version: 4.19.79-microsoft-standard

**Comment by simonferquel** [comment]
@zailic can you confirm you have a machine with a high number of CPU cores ?

**Comment by simonferquel** [comment]
We don't have machines with enough CPUs to reproduce the issue in our CI. Are you ok to test an experimental build to check if we managed to workaround this issue ?

**Comment by zailic** [comment]
@simonferquel  yes 4 cores / 8 logical processors / 1 socket

**Comment by zailic** [comment]
I have also this wslconfig
```
[wsl2]
memory=4GB
processors=4
```

**Comment by zailic** [comment]
> We don't have machines with enough CPUs to reproduce the issue in our CI. Are you ok to test an experimental build to check if we managed to workaround this issue ?

sure

**Comment by simonferquel** [comment]
Ok, so that is actually a low amount of CPUs, triggering the same issue with different numbers.
I have a build cooking that should fix the issue both for high and low number of CPUs. I'll post a link here as soon as it is ready.

**Comment by zailic** [comment]
So, I just removed the wslconfig restriction, so now the cpu map is identical with the host, and now kubernetes started successfuly.

**Comment by simonferquel** [comment]
https://download-stage.docker.com/win/edge/40848/Docker%20Desktop%20Installer.exe this is an untested version. Proceed with caution

**Comment by tebeco** [comment]
Same indisder build (19025)
Same Docker for Windows build (2.1.6.0)

Same stack trace :
![image](https://user-images.githubusercontent.com/2266487/69149288-71fe6d00-0ad6-11ea-9e95-ad6f65759a28.png)
![image](https://user-images.githubusercontent.com/2266487/69149317-82164c80-0ad6-11ea-9f6e-8eb18e0e5bae.png)

out of curiosity, where is the `wslconfig` file, not sure i got the good one
i found a `/etc/wsl.conf`

**Comment by simonferquel** [comment]
https://download-stage.docker.com/win/edge/40857/Docker%20Desktop%20Installer.exe <- I managed to reproduce the issue with your .wslconfig sample (thanks!), and this one seem to fix the issue.
Can you try it ? (you may need to reset your Kubernetes cluster from the settings for this to work)

**Comment by zailic** [comment]
> Same indisder build (19025)
> Same Docker for Windows build (2.1.6.0)
> 
> Same stack trace :
> ![image](https://user-images.githubusercontent.com/2266487/69149288-71fe6d00-0ad6-11ea-9e95-ad6f65759a28.png)
> ![image](https://user-images.githubusercontent.com/2266487/69149317-82164c80-0ad6-11ea-9f6e-8eb18e0e5bae.png)
> 
> out of curiosity, where is the `wslconfig` file, not sure i got the good one
> i found a `/etc/wsl.conf`

Is located on host machine(if not exist you can create it), not wsl2 box:
```
%userprofile%\.wslconfig
```

**Comment by roybotnik** [comment]
@simonferquel - New build works for me. Thank you! And yes I had to reset the kubernetes cluster.

**Comment by moolbits** [comment]
> https://download-stage.docker.com/win/edge/40857/Docker%20Desktop%20Installer.exe <- I managed to reproduce the issue with your .wslconfig sample (thanks!), and this one seem to fix the issue.
> Can you try it ? (you may need to reset your Kubernetes cluster from the settings for this to work)

@simonferquel @zailic @tebeco  Long story short, I had to reset docker for-win to factory defaults and then restart my computer a couple times to get this to work.. But it did work! 

Thank you very much for the support. Here is the long story:

After running the installer provided Docker kept crashing while trying to start. Here is a Crash Report ID from one of those: D8561184-220D-41CF-9566-546C4AA1914D/20191119195837

First I tried restarting my computer which didn't work because docker kept crashing while trying to start. 

Second, I ended up selecting to 'reset docker to factory defaults' from the crash report menu which allowed docker to start up, and when it did I saw that WSL Backend was already enabled which didn't seem normal to me so naturally I unchecked that box, and clicked apply, which crashed docker for-win again. For which I didn't collect a crash report before rebooting my comp (which may be a separate issue I havn't had time to confirm yet).

After rebooting my computer docker started up, again with WSL Backend enabled, I went over to Resources enabled my Ubuntu-18.04 distro selected apply which seemed to take normally - in that I could access docker from my WSL terminal and docker didn't crash. 

Lastly I enabled Kubernetes, it started up normally and has been running now for a couple hours even after reboot. 

I haven't had time wipe, and or delete docker for-win, and test with a clean install. Has anyone else tried this? As mentioned there are some issues updating to this fix that I ran into but those may be separate issues.

**Comment by moolbits** [comment]
@simonferquel New build works for me too! Thanks all for the support.

**Comment by simonferquel** [comment]
If you want to switch back to an official build, I managed to merge the patch in time for 2.1.6.1 :)

**Comment by tebeco** [comment]
Too fast

**Comment by moolbits** [comment]
That's just dandy. Thanks again!
