### ISSUE TITLE
"Stable" version of Docker Desktop 2.1.0.5 (40693) on the up to date Windows 10

### ISSUE THREAD

**Issue by pluczak99** [docker/for-win#5178]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: (submitted, but sorry, did not memorize)

### Expected behavior

Docker Desktop should install and start successfully on Windows 10 Enterprise 64-bit evaluation license. This however is not happening, even after Docker Desktop reinstallation, version 2.1.0.5 (40693) for some very odd reason branded as "stable". There is nothing stable about not even getting through installation with default settings.

### Actual behavior

Docker service (Windows Service) starts, but Docker Desktop does not reflect that (probably because the service is not started fully).
Additionally, when entering Settings from the Docker Desktop's popup menu, all settings are read-only and a small, status text on the Settings window shows "Docker is starting" (which it never ends doing).

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior
  1. Get a brand-new machine with modern specification (Intel Core i7 with 6 cores, 32GB RAM, 256 GB SSD + 500 GB SSD).
  2. Install Windows 10 Enterprise 64-bit evaluation, run Check for Updates and install everything Microsoft throws at you at given day of week.
  3. Configure the system to include Containers as one of the Windows features.
  4. Download and install Docker Desktop 2.1.0.5 (40693). Installation seems to complete, but Docker is unusable.
  5. Try uninstalling Docker Desktop. The Docker uninstallation window pops up, it says "uninstallation finished", but when you try to close the window, it asks you "Do you want to cancel uninstallation?".

For a most recent, official build of Docker Desktop, the build quality reminds me of some terminology used many years ago in some of my projects, managed using a flavor of agile methodology. It "works", but it does not "work work". 

Docker's release management processes need significant increase of software quality improvement process and setting up, at long last, a meeting when everybody gets up to speed on the semantic of the "stable build" term. 

Although an app that has a setup process broken to the point of never completing installation and configuration and it still may be called "stable", this is not the mainstream meaning of the term.

**Comment by shanthalakudva** [comment]
Another issue what I observed is, Docker Settings menu not appearing.
When I tried uninstalling followed by re-installing sometimes it works and then suddenly stopped working.
Very weird.
