### ISSUE TITLE
'DockerDesktopVM' failed to start.

### ISSUE THREAD

**Issue by ashley-neal** [docker/for-win#5180]
### Expected behavior
Docker opens and runs

### Actual behavior
Docker crashes, throws this error:
`Unable to start - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'DockerDesktopVM' failed to start.

Failed to start the virtual machine 'DockerDesktopVM' because one of the Hyper-V components is not running.

'DockerDesktopVM' failed to start. (Virtual machine ID 7A8D7FF0-6DB7-4553-B85F-C827C0767483)

The Virtual Machine Management Service failed to start the virtual machine 'DockerDesktopVM' because one of the Hyper-V components is not running (Virtual machine ID 7A8D7FF0-6DB7-4553-B85F-C827C0767483).

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()`

### Information
I am trying to set up a VMWare Windows Dev environment. I can't seem to get docker to start.

I am running Windows 10 Pro through VMWare
The problem occurs each time I attempt to start Docker.

I have attempted the following resolutions:
https://social.technet.microsoft.com/Forums/en-US/ee5b1d6b-09e2-49f3-a52c-820aafc316f9/hyperv-doesnt-work-after-upgrade-to-windows-10-1809?forum=win10itprovirt
https://github.com/docker/for-win/issues/5118
https://github.com/docker/for-win/issues/3375#issuecomment-515808417 

Here is the log:
[diagnostics.log](https://github.com/docker/for-win/files/3866542/diagnostics.log)

**Comment by ashley-neal** [comment]
@mikeparker - I've seen you commenting around town. Do you have any links or suggestions to get this operational?

**Comment by mikeparker** [comment]
We don't technically support nested virtualization scenarios as there are way too many combinations to test and support, but I've heard that it *mostly* works and there are various people on the forums / community slack trying to get the various VM providers working nicely with Docker Desktop.

I'd be interested to know if you resolved this or gave up :)

**Comment by richdevboston** [comment]
@mikeparker WTF kind of support answer is that?  This is an open issue with your commercial product.

**Comment by mat007** [comment]
@richdevboston this issue tracker is for Docker Desktop Community, which commercial product support were you looking for?
