### ISSUE TITLE
Docker Desktop Keeps Crashing

### ISSUE THREAD

**Issue by STaRDoGG** [docker/for-win#5185]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 2ECBE1F4-ADE2-4D97-8082-505598CFAE53/20191120162500

### Expected behavior

Docker Desktop not to crash.

### Actual behavior

Docker Desktop is frequently crashing, and along with it, my entire PC. (it forces a reboot).

I'm looking at my Event Viewer and seeing a ton of these:

![image](https://user-images.githubusercontent.com/1524526/69259147-5ef5a680-0b83-11ea-9c97-6c575de80a88.png)

The error message of all, look like these few that I copied:

> 'DockerDesktopVM' has encountered a fatal error.  The guest operating system reported that it failed with the following error codes: ErrorCode0: 0x7F44208E78C0, ErrorCode1: 0xC00003C000, ErrorCode2: 0xC00003BDF0, ErrorCode3: 0xFFFFFFFFFFFFFFF8, ErrorCode4: 0xC00003BD80.  If the problem persists, contact Product Support for the guest operating system.  (Virtual machine ID DEC0759F-D547-4597-9917-2FBBF1A5DB27)

Guest message:

> 'DockerDesktopVM' has encountered a fatal error.  The guest operating system reported that it failed with the following error codes: ErrorCode0: 0x7F396A3DF8C0, ErrorCode1: 0xC000028800, ErrorCode2: 0xC0000285F0, ErrorCode3: 0xFFFFFFFFFFFFFFF8, ErrorCode4: 0xC000028580.  If the problem persists, contact Product Support for the guest operating system.  (Virtual machine ID 22B07A61-A284-4D2B-96BB-B6BCB74B16D8)

Guest message:

> 'DockerDesktopVM' has encountered a fatal error.  The guest operating system reported that it failed with the following error codes: ErrorCode0: 0x7FAC24BF28C0, ErrorCode1: 0xC000037000, ErrorCode2: 0xC000036DF0, ErrorCode3: 0xFFFFFFFFFFFFFFF8, ErrorCode4: 0xC000036D80.  If the problem persists, contact Product Support for the guest operating system.  (Virtual machine ID F80F5B1A-04E6-4BF8-A89F-BCC4A987679C)

Guest message:

> 'DockerDesktopVM' has encountered a fatal error.  The guest operating system reported that it failed with the following error codes: ErrorCode0: 0x7F39ECFFD8C0, ErrorCode1: 0xC00003C000, ErrorCode2: 0xC00003BDF0, ErrorCode3: 0xFFFFFFFFFFFFFFF8, ErrorCode4: 0xC00003BD80.  If the problem persists, contact Product Support for the guest operating system.  (Virtual machine ID 382EA946-6A31-417E-8338-B25A2B3B1D24)

Guest message:

> 'DockerDesktopVM' has encountered a fatal error.  The guest operating system reported that it failed with the following error codes: ErrorCode0: 0x7F35F3A5F8C0, ErrorCode1: 0xC000028800, ErrorCode2: 0xC0000285F0, ErrorCode3: 0xFFFFFFFFFFFFFFF8, ErrorCode4: 0xC000028580.  If the problem persists, contact Product Support for the guest operating system.  (Virtual machine ID 382EA946-6A31-417E-8338-B25A2B3B1D24)

Guest message:

> 'DockerDesktopVM' has encountered a fatal error.  The guest operating system reported that it failed with the following error codes: ErrorCode0: 0x7F82223518C0, ErrorCode1: 0xC000037000, ErrorCode2: 0xC000036DF0, ErrorCode3: 0xFFFFFFFFFFFFFFF8, ErrorCode4: 0xC000036D80.  If the problem persists, contact Product Support for the guest operating system.  (Virtual machine ID 664BF6B1-5F11-4C89-9FE9-FC6A7576A63F)

Guest message:

> 'DockerDesktopVM' has encountered a fatal error.  The guest operating system reported that it failed with the following error codes: ErrorCode0: 0x7EFD56E748C0, ErrorCode1: 0xC000037000, ErrorCode2: 0xC000036DF0, ErrorCode3: 0xFFFFFFFFFFFFFFF8, ErrorCode4: 0xC000036D80.  If the problem persists, contact Product Support for the guest operating system.  (Virtual machine ID 664BF6B1-5F11-4C89-9FE9-FC6A7576A63F)

Guest message:

### Information

  - Windows Version: Win 10 x64
  - Docker Desktop Version: 

![image](https://user-images.githubusercontent.com/1524526/69259024-34a3e900-0b83-11ea-816b-b4b458ad49de.png)

  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Just Hyper-V

### Steps to reproduce the behavior

Just run Docker desktop and it randomly happens.

**Comment by STaRDoGG** [comment]
@djs55 Here's the issue I was referring to in the previous thread. Thanks for having a look. =)

**Comment by basilin** [comment]
I am getting this issue constantly . I am running docker inside AzureVm
```
'DockerDesktopVM' has encountered a fatal error.  The guest operating system reported that it failed with the following error codes: ErrorCode0: 0x8, ErrorCode1: 0x81000004134C0000, ErrorCode2: 0x7F79E9BDA5A3, ErrorCode3: 0x0, ErrorCode4: 0x7F77B3EBAC20.  If the problem persists, contact Product Support for the guest operating system.  (Virtual machine ID 8449CC35-0922-4D15-810C-36B2654BB215)
```

**Comment by STaRDoGG** [comment]
@basilin For kicks, take a look at how much free space you have on that Hyper-V VM. It seems my issue was related to it running out of space. Once I re-sized the VM itself and gave it a lot more space it seems to have resolved the crashing for me.

**Comment by ozgurtezel89** [comment]
I am having the same issue for the past 3days.
