### ISSUE TITLE
Prerequisites for WSL 2 tech preview feature seem wrong in documentation

### ISSUE THREAD

**Issue by JDeman** [docker/for-win#5191]
Hi,

It looks like your [documentation](https://docs.docker.com/docker-for-windows/wsl-tech-preview/) isn't up to date regarding the prerequisites for the WSL 2 Tech Preview feature:

![docker_for_win_doc_issue](https://user-images.githubusercontent.com/8964002/69284543-28557580-0bef-11ea-928e-89d116a8ad7d.PNG)

But then on the settings tab of the tech preview the version required is higher:

![docker_win_settings_pannel](https://user-images.githubusercontent.com/8964002/69284697-808c7780-0bef-11ea-811b-2b59337adc68.PNG)

Regards

**Comment by stephen-turner** [comment]
@usha-mandya Can you fix this? Thank you.

**Comment by usha-mandya** [comment]
@JDeman Thanks for reporting this. WSL 2 documentation has been updated. Please see https://docs.docker.com/docker-for-windows/wsl-tech-preview/.
