### ISSUE TITLE
MSYS2 installation hangs forever

### ISSUE THREAD

**Issue by iameli** [docker/for-win#5193]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C1F656CF-E0E5-4183-A0FB-D9C56B05A2FC/20191121191109

### Expected behavior

The build works

### Actual behavior

The build hangs forever

### Information
[Here's my Dockerfile](https://github.com/livepeer/go-livepeer/blob/cf90a0f432f6830da9c0ddcf9b48eadda86acf29/docker/Dockerfile.build-windows). The step that hangs is an installation of MSYS2 suitable for building mingw64 applications. The build hangs both on my home computer and in Azure using their `windows-2019`  build image - [here's a build timing out after six hours](https://dev.azure.com/ericxtang/Livepeer%20pipeline/_build/results?buildId=820).

It's not something in the container hanging, as `docker ps` reports that nothing is running. After the step finishes my SDD usage spikes up to 100% for a few minutes and Docker logs report that the layer export succeeded but the build just sits there forever.

  - Windows Version:Version 10.0.18362 Build 18362
  - Docker Desktop Version: 2.1.0.5 (40693)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Issue reproduces in both instances

### Steps to reproduce the behavior
```bash
git clone https://github.com/livepeer/go-livepeer
cd go-livepeer
git checkout cf90a0f432f6830da9c0ddcf9b48eadda86acf29
docker\windowsbuild.ps1
```

**Comment by StefanScherer** [comment]
There are known issues with MSYS2 in a Windows Container. I did some tests a while ago, https://github.com/StefanScherer/dockerfiles-windows/tree/master/msys2 with a link to another issue https://github.com/msys2/MSYS2-packages/issues/1490
You should file an issue there, I don't think there's much we can do on our side.

**Comment by iameli** [comment]
I'd agree if I were running into that no-output error, but that's not my issue. My build is hanging and `docker ps` reports that nothing is running - surely it can't be MSYS2's fault when no MSYS2 executables are running? Docker just needs to finish packaging up the layer and instead it's hanging forever.

Trying a build on the latest edge version now.

**Comment by daewok** [comment]
I had the same issue installing msys2 through chocolatey. Root cause seemed to be similar to https://github.com/microsoft/hcsshim/issues/696

I fixed it by using docker-ci-zap to remove the folder under C:\ProgramData\docker\tmp\ that it was trying to delete.
