### ISSUE TITLE
Domain credentials not working in Settings->Resources->File Sharing

### ISSUE THREAD

**Issue by mcleanra** [docker/for-win#5199]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 7E40C4C9-D1D1-4691-A98F-ADD4CEF07FF2/20191122091350

### Expected behavior
In Docker desktop settings under Resources -> File sharing, I expect to select the C drive to make it available to my containers.

### Actual behavior
When I check the C drive and then "Apply & Restart", I am prompted for filesystem credentials with my domain user account prepopulated.  I enter the correct password and am continually re-prompted with no error message.

### Information

  - Windows Version: Windows 10 Enterprise Build 19023.vb_release.191108-1432
  - Docker Desktop Version: 2.1.6.1 (40900)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

`git clone https://github.com/chanm003/budget`
`cd budget`
`git checkout multiple_auth_schemes`
`docker-compose up`

**Comment by djs55** [comment]
@mcleanra thanks for your report. There is a completely new drive-sharing mechanism in the latest edge release which doesn't require credentials at all, and which therefore should work around this problem.

In case it's useful I've written instructions for setting up and testing the new file sharing implementation here: https://github.com/docker/for-win/issues/5139#issuecomment-559700215

**Comment by mikeparker** [comment]
We have released a fix for sometimes seeing the old filesharing username/password credentials box in todays Edge release 2.1.7.0

Can you please try todays build and see if this fixes your issue? https://docs.docker.com/docker-for-windows/edge-release-notes/

**Comment by mattbell87** [comment]
Is this related to #1352? I might try that Edge release.

**Comment by mattbell87** [comment]
I can confirm that 2.1.7.0 works with my AzureAD windows account. No creds were needed to share my drives to the containers.

![Docker 2.1.7.0 working](https://user-images.githubusercontent.com/2722612/70675024-fdd17680-1cdb-11ea-970a-2791b192b007.png)

**Comment by stephen-turner** [comment]
Believed fixed in 2.2.
