### ISSUE TITLE
Does Docker for Windows support CUDA?

### ISSUE THREAD

**Issue by forhonourlx** [docker/for-win#52]
Does Docker for Windows support CUDA? And can I find the gpu device on Docker?

Thanks & Regards.

**Comment by rneugeba** [comment]
Hi @forhonourlx Docker for Windows run a Linux VM on top of Hyper-V. Hyper-V does not support GPU device passthru so, I'm afraid, we can't offer CUDA support in Linux containers in Docker for Windows.
