### ISSUE TITLE
Moby does not start at all

### ISSUE THREAD

**Issue by piwi91** [docker/for-win#520]
### Expected behavior
Docker starting

### Actual behavior
Docker crashes while starting

### Information

1BCE9076-E5FE-4E59-AACA-6AFF2C24B428/2017-02-23_14-34-48

Microsoft Windows 10 Pro
Windows 10.0.14393 Build 14393

### Steps to reproduce the behavior

New laptop and it crashes immediately after the setup:

```
Docker hv-sock proxy (vsudd) is not reachable
   bij Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId)
   bij Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   bij Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   bij Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   bij Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

**Comment by dancerjude** [comment]
I have the same problem, same S.O. and version, same error.

**Comment by abhishekdiwakar** [comment]
Any resoltuions yet?

**Comment by smaeda-ks** [comment]
Hi, did you tried to apply latest windows update? As my case, KB3211320 was the answer.

**Comment by piwi91** [comment]
All updates are installed now so I will give it another try this week.

**Comment by dancerjude** [comment]
@smaeda-ks unfortunately KB3211320 did not worked for me...

**Comment by simonferquel** [comment]
@piwi91 the vm does not seem to start at all. I tried to see the logs but I can't but I can't understand a word of your language...
There seem to be a critical error in Microsoft-Windows-Hyper-V-Worker events.

Also, are you able to manually create a VM and start it (using Hyper-V manager)?

**Comment by friism** [comment]
@piwi91 did you have a chance to look at this?

**Comment by piwi91** [comment]
@friism No, and I went for the Virtualbox approach because I couldn't develop without a working Docker VM. Unfortunately, I don't have a setup available to check this out at the moment...

**Comment by rn** [comment]
closing old issues
