### ISSUE TITLE
[WSL2] Impossible to activate on build 1903

### ISSUE THREAD

**Issue by Geekimo** [docker/for-win#5203]
Hi everyone,
as  WSL 2 has been released with 1903 this November, why do we still need to have the lastest fast ring Windows Insider release ?
Is there a workaround to enable docker desktop to work with 1903 ?

**Comment by StefanScherer** [comment]
Docker Desktop uses WSL2 features that require OS build 19018 or higher. This is also available in Slow Ring.

**Comment by stephen-turner** [comment]
@Geekimo What do you mean when you say "WSL 2 has been released with 1903"?
