### ISSUE TITLE
Docker Desktop Installer should show Version

### ISSUE THREAD

**Issue by kivi** [docker/for-win#5205]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
I wish the installer on Windows 10 shows me the Docker version to be installed. If Docker Desktop ist not installed

### Actual behavior
If Docker Desktop is installed it shows the installed version is newer. I uninstall Docker completly from my computer and as I have different "Docker Desktop Installer" files I don't know which one would install what version. Starting the installer is taking me through installation but not telling beforehand what version of Docker is going to be installed.

### Information
it is reproducible and just simple as that. A install which is not showing the version it is going to install.  

  - Windows Version: Windows 10 / build 19025.vb
  - Docker Desktop Version: various Testing Edge and Latest
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no, running just windows pro

### Steps to reproduce the behavior
  1. Download Docker Desktop installer for windows
  2. Install
  3. Uninstall Docker Desktop
  4. Download another Version... now you don't know which was, which if you ignore the date and your personal memory, which you have downloaded first.

**Comment by mikeparker** [comment]
It is technically possible to see the version you can right click -> properties -> details, although I admit this is a little obscure.

![image](https://user-images.githubusercontent.com/1557887/70661169-9bd12c80-1c5b-11ea-8038-4c66d864f585.png)

**Comment by mat007** [comment]
Thanks for your feedback, we’ve fixed this and it should be available in the next Edge release.

![image](https://user-images.githubusercontent.com/2386884/70713874-40e51700-1ce7-11ea-932c-4441f7a3de40.png)
