### ISSUE TITLE
Docker timed out waiting for the lifecycle-server to start in Version 10.0.19028Build 19028

### ISSUE THREAD

**Issue by mwoodpatrick** [docker/for-win#5211]
Starting with version 10.0.19028 (Build 19028) I'm getting:

   Docker timed out waiting for the lifecycle-server to start. 

Install was working fine previous to upgrade

Crash report:
	5B81673D-4614-408D-AAD6-6CBB9BBBE6B5/20191124150755

**Comment by mikeparker** [comment]
Did you follow the instructions in the error message and try increasing the timeout?

**Comment by mwoodpatrick** [comment]
/remove-lifecycle stale

This issue is still occurring Also see https://github.com/docker/for-win/issues/5848 for related problems

**Comment by mwoodpatrick** [comment]
The timeout occurs after many minutes, how do we determine why its hanging?
