### ISSUE TITLE
Docker-desktop kubernetes context not in the list

### ISSUE THREAD

**Issue by wheestermanstoyota** [docker/for-win#5216]
Running Docker for Windows 2.1.5 (40693) with kubernetes activated, the local kubernetes is started successfully. I can even load a context of one of our remote clusters, so I can connect to these from my Windows environment.

But... based on the documentation I should have  windows-desktop context when I right-click Kubernetes, I don't see this one? 

When I try kubectl command to the local one, the context is not correct

Unable to connect to the server: dial tcp 127.0.0.1:8080: connectex: No connection could be made because the target machine actively refused it.

There were no errors at installation time neither. How can I get the correct local context inside my environment?

Walter

**Comment by pradorodriguez** [comment]
I have the same issue :( ...

**Comment by hencca** [comment]
me too

**Comment by JohnRobinv** [comment]
same here.
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-dispatcher", GitCommit:"f5757a1dee5a89cc5e29cd7159076648bf21a02b", GitTreeState:"clean", BuildDate:"2020-02-06T03:31:35Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"darwin/amd64"}
Unable to connect to the server: net/http: TLS handshake timeout
```

docker desktop
2.2.0.3(42716)

**Comment by Nilamkhule** [comment]
Yes, did not see context getting added for enabled k8s cluster.
Unable to connect to the server: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

**Comment by mat007** [comment]
Do you have a `KUBECONFIG` environment variable?
What does `~/.kube/config` look like? Does it contain a `docker-desktop` context?
