### ISSUE TITLE
Docker pull fails with "no route to host" when accessing insecure registry in LAN

### ISSUE THREAD

**Issue by cluick** [docker/for-win#522]
### Expected behavior

We are using an insecure registry in our LAN which is reachable via "myhost:5000". I´ve added "myhost:5000" to the list of insecure registries in Docker Settings / Deamon and restarted docker.
Now I´m expecting that I can pull a docker image from this registry.

### Actual behavior

Executing "docker pull myhost:5000/kinf-4.3-components" on the Windows command line (cmd.exe) fails with the following output:

Using default tag: latest
Pulling repository myhost:5000/kinf-4.3-components
Error while pulling image: Get http://myhost:5000/v1/repositories/kinf-4.3-components/images: dial tcp 172.17.11.17:5000: getsockopt: no route to host

### Information

Diagnostic ID: F842665D-53B2-4BDD-ADB4-BAE48A9FD28C/2017-02-23_16-42-32
docker -v: Docker version 1.13.1, build 092cba3
Network Settings: 
- Subnet Address: 10.0.75.0
- Subnet Mask: 255.255.255.0

The output shows that docker resolved the hostname "myhost" to the correct IP 172.17.11.17.

Can you tell me how I can enable docker daemon to access the IP 172.17.11.17?

**Comment by simonferquel** [comment]
@djs55 can you have a look at it ? it seems vpnkit can't foute to this particular IP

**Comment by TroyLDay** [comment]
Also experiencing this with rc7, then also after upgrade to 17.03.0-ce-win1 (10300)

**Comment by TroyLDay** [comment]
Finally, I completely uninstalled the software (which was marked as Beta at the bottom of the General tab), rebooted, and completely reinstalled the STABLE version...and the trouble went away.

**Comment by cluick** [comment]
I still have the same problems, even after reinstallation of docker for windows. I´m now using the Docker Community Edition 17.12.0-ce-win47 (15139).
I attached the "log.txt" from my latest retry...
[log.txt](https://github.com/docker/for-win/files/1677115/log.txt)

**Comment by stphngrtz** [comment]
I'm having the same issue.

```bash
Docker version 17.12.0-ce, build c97c6d6
```

**Comment by laurentKTR** [comment]
Same problem here with Docker version 17.12.0-ce, build c97c6d6 ( W10 )
trying to pull from private registry : getsockopt: no route to host

i'm getting this error without any extra config
Adding my private repo in "insecure-registries" reports the same error
Adding the suffix to dns-search reports the same error

We have the same problem on another computer with a fresh install of docker window

**Comment by laurentKTR** [comment]
i have added bridge:none to the configuration
so i was able to push to the private registry, 
but with this option now dotnet restore within dockerfile doesn't work anymore

**Comment by stphngrtz** [comment]
We just noticed that removing every other bridged network but the default helps aswell.

```bash
> docker pull our-private-repository:18082/our/image:latest
Error response from daemon: Get http://our-private-repository:18082/v2/: dial tcp 123.456.789.123:18082: getsockopt: no route to host

> docker network ls
NETWORK ID          NAME                       DRIVER              SCOPE
e177178a5c9f        bridge                     bridge              local
0f362e7e14a6        network-1                  bridge              local
0ddbf9bbe3e3        network-2                  bridge              local
1e0ccbec292a        host                       host                local
e1e07bcb3505        none                       null                local

> docker network rm 0f 0d

> docker pull our-private-repository:18082/our/image:latest
latest: Pulling from our/image
...
...
```

Weird 😕

**Comment by laurentKTR** [comment]
just adding that this problem occurs at the company because we are under active directory
At home with my personal w10 and another computer ubuntu  hosting the private repository 
i don't have this problem

**Comment by trippinCode** [comment]
Got the same issue running a docker registry on a VM ubuntu host on my lan, api v2/_catalog calls are going through and i can use the repository from the vm, but when i try to use the registry from my windows laptop i get:
```
C:\Users\USER>docker pull 192.168.100.63:5000/firstimgtag
Using default tag: latest
Error response from daemon: Get https://192.168.100.63:5000/v2/: dial tcp 192.168.100.63:5000: getsockopt: no route to host
```

**Comment by rgj8** [comment]
Hi, i've got same problem.
Using Windows 10 1607, Docker for Windows 18.03.0-ce-win59 (16762).

With ForceRemoveDocker.ps1 script, I can access network till switching from lan nic to wlan nic. Only uninstall & new install of docker for windows does not work for me.

I think its an problem with hyper-v. Because networking between containers still works. Only containers / docker pull -> DockerNAT -> host system -> lan does not work.

**Comment by laurentKTR** [comment]
i'm still facing this issue in another way
When i'm building vs2017 core console using docker compose, the nugets from internet are restored
but i'm getting errors for nugets from our internal nuget repository.

Every thing works well when compiling from a linux machine

**Comment by rgj8** [comment]
Now I've downgraded to Docker Community Edition 17.06.0-ce-win18 2017-06-28.
-> It acts like before (docker login / pulling / building works), i try if it fails in some hours again :-(

**Comment by luizportela** [comment]
Same problem here. Seems that the problem in the mac edition was solved: https://github.com/docker/for-mac/issues/1797

**Comment by guoqingfu** [comment]
I had the same problem,  win10 18.03.1-ce .
step1 Right click the docker icon and select the 'Switch to Windows containners' .
step2 Config host add one custom domain match harbor ip , eg: 172.17.xx.xx harbor.demo.local
step3 open CMD and input [docker login -u admin -p Harbor12345 harbor.demo.local]

**Comment by cluick** [comment]
I can still reproduce the issue with the latest version of Docker for Windows.

**Comment by laurentKTR** [comment]
still facing the problem with the latest version

**Comment by alkuzad** [comment]
Version 2.0.0.0-win78 (28905)
Channel: stable
Build: c404a62

Still same error, fixed by removing all dangling networks, however networks should not impact how `docker pull` behaves.

**Comment by abgm** [comment]
docker network prune :)
Set the bit option on 
docker -> deamon.json -> bip 
docker is creating sub-networks on the same range that your private registry
https://docs.docker.com/v17.09/engine/userguide/networking/default_network/custom-docker0/
https://github.com/docker/compose/issues/4336
https://github.com/docker/for-mac/issues/218

**Comment by cluick** [comment]
Thanks @abgm - setting bip to "192.168.254.1/24" resolved the issue for me!

**Comment by ertemmstein** [comment]
> docker network prune :)
> Set the bit option on
> docker -> deamon.json -> bip
> docker is creating sub-networks on the same range that your private registry
> https://docs.docker.com/v17.09/engine/userguide/networking/default_network/custom-docker0/
> [docker/compose#4336](https://github.com/docker/compose/issues/4336)
> [docker/for-mac#218](https://github.com/docker/for-mac/issues/218)

thanks , this is solved my issue which is "no route error" on for docker for windows.
Just added "bip": "`192.168.117.1/24"` line to deamon.json and restart docker

**Comment by ctlove0523** [comment]
> docker network prune :)
> Set the bit option on
> docker -> deamon.json -> bip
> docker is creating sub-networks on the same range that your private registry
> https://docs.docker.com/v17.09/engine/userguide/networking/default_network/custom-docker0/
> [docker/compose#4336](https://github.com/docker/compose/issues/4336)
> [docker/for-mac#218](https://github.com/docker/for-mac/issues/218)

thanks,use your method sovled my problem

**Comment by laurentKTR** [comment]
Hi 

this is the configuration i'm setting in my docker client on window
Right click on icon , settings then daemon then advanced
{
  "registry-mirrors": [],
  "debug": true,
  "experimental": false,  
  "bip": "192.168.254.1/24"
}

Apply

**Comment by jtruxon** [comment]
worked for me, docker version v19.04.4

**Comment by ezequielsantana** [comment]
> Hi
> 
> this is the configuration i'm setting in my docker client on window
> Right click on icon , settings then daemon then advanced
> {
> "registry-mirrors": [],
> "debug": true,
> "experimental": false,
> "bip": "192.168.254.1/24"
> }
> 
> Apply

Thank you very much @laurentKTR !

**Comment by Aidan-Pasquale99** [comment]
I'm using Docker Desktop Community v2.2.0.3 on Windows 10 Enterprise v1903 and suddenly encountered this issue today after months of authenticating with and pushing images to a personal insecure registry. Somehow, switching to Windows containers fixed this for me... 

The networking all seems fine, I can ping the registry DNS etc, but every _docker login_ command  failed with 'no route to host' until I switched to Windows containers - it then worked perfectly. Switching back to Linux containers causes the issue again. Very strange.

**Comment by guidoavvisati** [comment]
The solution from @laurentKTR works for me as well!

**Comment by cluick** [comment]
After using the workaround @laurentKTR described for a while now, I found out that the issue reappears again after every Docker-For-Windows-Update. I have to backup my configuration, reset the docker installation to factory defaults and apply the "daemon.json" config again and then it works. It´s really a pain in the axx and I´m a really frustrated after fiddling around with this for a long time now. Has anyone a suggestion on how to resolve this issue permanently?

**Comment by cluick** [comment]
The issue is still present in Docker for Windows v19.03.12

**Comment by mortenmoulder** [comment]
Can confirm this still is an issue in v19.03.12 as well.

Adding "bip" to the Docker Engine as suggested by @laurentKTR worked for me.

**Comment by Nguimjeu** [comment]
> Hi
> 
> this is the configuration i'm setting in my docker client on window
> Right click on icon , settings then daemon then advanced
> {
> "registry-mirrors": [],
> "debug": true,
> "experimental": false,
> "bip": "192.168.254.1/24"
> }
> 
> Apply

Sorry if noob question. How do you determine which value to set the `bip` to?
In my Docker Desktop, I have under Resources > Network > Docker subnet the value **192.168.65.0/28**.
