### ISSUE TITLE
Docker desktop uninstall doesn't remove entries from Windows hosts file

### ISSUE THREAD

**Issue by raffi-t** [docker/for-win#5220]
Docker version:
2.1.0.40693

Windows 10, build 18362

After uninstalling Docker desktop my pc was still resolving to host.docker.internal. After some digging, the hosts file in c:\Windows\System32\Drivers\etc\hosts had to manually be edited to remove the entries docker put in. Please improve the clean up process when uninstalling docker.

Steps to reproduce,
Installed docker for windows. 
Uninstall docker for windows.
PC still resolves to host.docker.internal.

**Comment by bruceburge** [comment]
This is is still occurring as of 07/02/2020
