### ISSUE TITLE
WSL2 distribution does not apply

### ISSUE THREAD

**Issue by ThreshHNS** [docker/for-win#5233]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4FABB6E5-067C-4AAF-B563-FB29E850ABA1/20191127194036

### Actual behavior
  - WSL2 distribution does not apply after settings toggle switch and clicking "Apply and Restart". All was fine, but something strange happened. 

### Information
Good day,
For some reason, the docker stopped working. I can’t apply the distribution in wsl integration. After switching the toggle switch and pressing the button "apply and restart", the button turns gray and the docker does not restart. Everything used to be fine, but now I am getting the error "docker: Cannot connect to the Docker daemon at unix: ///var/run/docker.sock. Is the docker daemon running ?." and still got toggle in gray position after applying it. Can you help me to resolve it?
Thank you!

  - Windows Version: 19033.1
  - Docker Desktop Version: edge 2.1.6.1 (40900)

![2019-11-28_03-50-20](https://user-images.githubusercontent.com/24918680/69755319-f1550600-1192-11ea-85cf-7168dd86e125.png)

![2019-11-28_03-52-37](https://user-images.githubusercontent.com/24918680/69755332-f74ae700-1192-11ea-8a64-b16158ff15e6.png)

**Comment by simonferquel** [comment]
For some reason, the script responsible for creating the docker user group fails.
Can you try running this:
```
wsl -d Ubuntu-18.04 -u root
( addgroup docker || true ) && addgroup <your wsl username> docker
```
and if this one fails,

```
wsl -d Ubuntu-18.04 -u root
( groupadd docker || true ) && usermod -aG docker <your wsl username>
```

and send the output in a comment ?

**Comment by ThreshHNS** [comment]
Thank you for the answer! That's what it gives out, but the docker still behaves the same. The button Apply and restart" also does nothing
`addgroup: The group `docker' already exists.
Adding user `thresh' to group `docker' ...
Adding user thresh to group docker
Done.`
![image](https://user-images.githubusercontent.com/24918680/69852906-712cbe80-12c0-11ea-8b99-f19ceda9d473.png)

**Comment by simonferquel** [comment]
Per any chance, can you capture the exit code of both scripts ?

**Comment by simonferquel** [comment]
Also, can you try with another distro (like Ubuntu without version pinning) ? that would help me to see if there is something broken outside of wsl, or if there is something particular that makes the integration fail.

**Comment by simonferquel** [comment]
Also, what shell do you use by default ? (I think those scripts are executed under whatever default shell is configured for your distro. We might want to change that)

**Comment by ThreshHNS** [comment]
> Also, what shell do you use by default ? (I think those scripts are executed under whatever default shell is configured for your distro. We might want to change that)

Okey, it's make sense. I use fish by default shell with `chsh -s `which fish``. I will try to set it back to bash and retry.

**Comment by ThreshHNS** [comment]
> Also, what shell do you use by default ? (I think those scripts are executed under whatever default shell is configured for your distro. We might want to change that)

Okey, it's make sense. I set fish by default shell with` chsh -s 'which fish'`. I will try to set it back to bash and retry.

**Comment by ThreshHNS** [comment]
I reinstalled the distribution and now the docker is working. I'll try to switch to fish and check the WSL Integration.

**Comment by ThreshHNS** [comment]
Reinstall the distribution fixed my problem with Docker.
