### ISSUE TITLE
Docker Desktop shows no running containers

### ISSUE THREAD

**Issue by villasv** [docker/for-win#5243]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 297599AB-0135-420D-9D5B-A9132B13CD1D/20191128191839

### Expected behavior
Active containers should show up on the Docker Desktop Interface

### Actual behavior
Nothing shows, despite containers being running.
![image](https://user-images.githubusercontent.com/6609289/69828524-ecc43800-11fa-11ea-8809-3cdb9ed2ab6c.png)

### Information
  - Windows Version: OS Build 19030.1
  - Docker Desktop Version: 2.1.6.1 (40900)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: The WSL2 backend

### Steps to reproduce the behavior
  0. Not sure if reproducible outside my machine
  1. Spin up some containers
  2. Open Docker Desktop

**Comment by mikeparker** [comment]
We have fixed a number of bugs in this area for todays Edge release 2.1.7.0.

Could you please check this build and see if your issue has been fixed? https://docs.docker.com/docker-for-windows/edge-release-notes/

**Comment by villasv** [comment]
Testing with 2.1.7.0 (41536), still nothing shows up.

I realized that my Windows environment is poluted with a DOCKER_HOST variable pointing to `192.168.99.100`, the previous VirtualBox setup. I've made a fool of myself and I can't even find from where that variable is coming from so I wasn't able to remove it before testing, but just saying just in case it might be related.

**Comment by mikeparker** [comment]
So am I right in thinking you're running linux containers under WSL 2?

When you say the containers are running can you show the commands you're running (and output) to show them?

I think this sounds like the container UI isn't working correctly with WSL 2 if I'm reading this right.

**Comment by villasv** [comment]
> I think this sounds like the container UI isn't working correctly with WSL 2 if I'm reading this right.

Yes.

![image](https://user-images.githubusercontent.com/6609289/70800433-02a13380-1d8b-11ea-9a73-90a677d068f1.png)
![image](https://user-images.githubusercontent.com/6609289/70800637-83602f80-1d8b-11ea-8102-a35b0255269d.png)

**Comment by villasv** [comment]
I was able to remove the `DOCKER_HOST` environment variable from my system that was pointing to the old VirtualBox setup, and the UI started to show the containers.

So it seems that the UI was being affected by that environment variable. If this is intentional, we can close this issue. If not, we can reword the title and description.
