### ISSUE TITLE
Start at login option invalid after update

### ISSUE THREAD

**Issue by cdalexndr** [docker/for-win#5246]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E631F14E-8B3C-46B7-82F8-B975F82EAAD7/20191129104514

### Expected behavior
Docker should not start at log in.

### Actual behavior
Docker starts at log in.

### Information

  - Windows Version: 10, 1903
  - Docker Desktop Version: 2.1.0.5 (40693)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: NO

### Steps to reproduce the behavior
In a previous version the option worked correctly, but after updating (automatic pop-up to update) the option is invalid. I believe the reproductible steps are:
  1. Settings -> disable "_Start Docker Desktop when you log in_"
  2. Update docker
  3. Docker starts at login, but the option is displayed as disabled

**Comment by cdalexndr** [comment]
After enabling and disabling the option, it works correctly, so the issue is that the option is not preserved after update.

**Comment by mat007** [comment]
I believe this has been fixed in Edge 2.1.2.0 released back in September.
As you’re on the Stable channel you will have to wait until the next Stable release which at the moment is planned for mid-December and will include this fix.
Sorry for the inconvenience.

**Comment by joshco** [comment]
@cdalexndr your workaround worked for me. I'm on stable channel.
