### ISSUE TITLE
wsl2 integration menu doesn't showing the installed distros

### ISSUE THREAD

**Issue by lucas-felix** [docker/for-win#5247]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: AEACEDF5-8225-4684-820C-6D98F342DCE1/20191129195813

### Expected behavior

When I access Settings > Resources > WSL Integration, my wls distros should be listed like this:

![](https://docs.docker.com/docker-for-windows/images/wsl2-choose-distro.png)

### Actual behavior

But in my installation there's no distro on the list:

![settings-wsl-integration](https://user-images.githubusercontent.com/2891706/69891130-f0c68780-12d8-11ea-986c-cf36a12d4e64.PNG)

I have the following distros installed (the result of executing `wsl --list` command):

```
Windows Subsystem for Linux Distributions:                                                                             
Ubuntu-18.04 (Default)                                                                                                 
docker-desktop                                                                                                         
docker-desktop-data                                                                                                    
Debian                                                                                                                 
Ubuntu
```

### Information

  - Windows Version: 2004. OS build: 19033.1
  - Docker Desktop Version: 2.1.6.1
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

At first, the WSL2 option didn't even show up. After I upgrade Windows to the latest version of the fast ring, I checked the option but the distros aren't shown.

### Steps to reproduce the behavior

  1. Install the Latest Windows version of the fast ring.
  2. Install Ubuntu/Ubuntu 18.04 wsl2 distro
  3. enable docker WSL2 backend
  4. try Settings > Resources > WSL Integration

**Comment by StefanScherer** [comment]
Could you run `wsl -l -v` and add the output here as a comment? Only version 2 distros are listed at the moment.

**Comment by lucas-felix** [comment]
Oh, boy! It makes complete sense. But I could swear that I had set the version 2 as default. Thanks and sorry about that.

**Comment by StefanScherer** [comment]
We‘re discussing how to help users in that situation, maybe listing all distros and helping to convert to version 2 if the user enables one.
