### ISSUE TITLE
Repeated problem starting Docker on Windows 10 Pro

### ISSUE THREAD

**Issue by DoctorWho8** [docker/for-win#5249]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

This is what the thing said:
Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'MRWORF1' because the object was not found. The object might have been deleted, or you might not have permission to perform the task. Verify that the Virtual Machine Management service on the computer is running. If the service is running, try to perform the task again by using Run as Administrator.

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass27_0.<ResetToDefault>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()
I am running locally. And this laptop is running Windows 10 Pro. Reproducible? It has happened here three times.

**Comment by NeyahPeterson** [comment]
I had this issue at my work because Trend was preventing the creation of the DockerNAT switch in Hyper-V.  Our antivirus team opened a ticket with Trend and received directions on how to resolve it.

This link was relevant when I supplied it to my av team
https://success.trendmicro.com/solution/1120119-unable-to-create-hyper-v-vswitch-on-a-windows-10-machine-with-officescan

**Comment by mikeparker** [comment]
@NeyahPeterson interesting find, thanks for the info. Virus scanners can be frustrating when they break our networking. Can you remember if it was exactly this error message? There are a few very similar messages like this. 

> Hyper-V encountered an error trying to access an object on computer 'MRWORF1' because the object was not found. The object might have been deleted, or you might not have permission to perform the task. Verify that the Virtual Machine Management service on the computer is running. If the service is running, try to perform the task again by using Run as Administrator.

**Comment by NeyahPeterson** [comment]
@mikeparker No, my error message was
> [Error  ] Unable to create: System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".
