### ISSUE TITLE
Docker not starting when using WSL 2

### ISSUE THREAD

**Issue by AlexanderSarson** [docker/for-win#5250]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D63154E0-3896-4726-8682-D74D3807A463/20191201093807

### Expected behavior
Docker desktop starts

### Actual behavior
Docker never starts

### Information

I just moved to Windows insider slow ring and uninstalled my old docker installation.
Installed the newest edition of docker with WSL 2.
When i start my computer docker just hangs for almost 30 minutes and then crashes with error: timeout waiting for lifecycle server to start
If i restart my computer it looks like docker starts fine every time.

  - Windows Version: Windows 10 Pro Build: 19033
  - Docker Desktop Version: 2.1.6.1 (40900)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Start computer, log in
  2. Wait 30 minutes until docker crashes.

**Comment by mikeparker** [comment]
Can you try the new Edge version please? 2.1.7.0. Let me know if this helps!

**Comment by AlexanderSarson** [comment]
Hi Mike
it works, thanks 👍
