### ISSUE TITLE
docker mishandles trailing backslashes in ENV if backslash is the escape character.

### ISSUE THREAD

**Issue by Artem-B** [docker/for-win#5254]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D200CF49-CF54-4FC5-8543-EFC7B0378983/20191202050104

### Expected behavior
Image environment set correctly according to the dockerfile statements or `docker commit -c` arguments.

### Actual behavior

* Trailing backslash is always removed from `-c ENV var value` (unless ``escape=` `` is set in the docker file)
* Arguments for subsequent `-c` options or dockerfile statements are inappropriately appended to the statement with the stripped backslash.

### Information

  - Windows Version:  Windows 10 Pro, 10.0.18363 N/A Build 18363
  - Docker Desktop Version: 2.1.0.5 (40693)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

```shell
$ docker pull hello-world 
$ docker inspect -f "{{json .Config.Env }}" hello-world 
null
$ docker commit -c "ENV A path" -c "ENV B another\\path" \
    -c "ENV C trailing\\backslash\\" hello-c hello-c-env
$ docker inspect -f "{{json .Config.Env }}" hello-c-env
["A=path","B=another\\path","C=trailing\\backslash"]
### There's no more `\` at the end of C's value  ^^^.

$ docker commit -c "ENV A path" -c "ENV B another\\path" \
    -c "ENV C trailing\\backslash\\" \
    -c "ENV D This gets appended to C" hello-c hello-c-env2 
$ docker inspect -f "{{json .Config.Env }}" hello-c-env2
["A=path","B=another\\path","C=trailing\\backslashENV D This gets appended to C"]
###  Ouch. Now ENV D got glued into C   ---------^^^

$ cat Dockerfile.env
FROM hello-world

ENV A path
ENV B another\\path
ENV C trailing\\backslash\\
ENV D This gets appended to C
$ docker build -t env3 -f Dockerfile.env env3
$ docker inspect -f "{{json .Config.Env }}" env3 
["A=path","B=another\\path","C=trailing\\backslashENV D This gets appended to C"]
###  Same problem with Dockerfile   ------------^^^
```
Note that only the **trailing** backslash disappears from the value of `C`. There is no problem with the inner backslash. The problem disappears in case of `ENV` in a  the docker file if it has ``# escape=` ``  in it or if it's passed as `-c` to `docker commit`

EDIT: reformatted reproduction instructions.

**Comment by mikeparker** [comment]
@thaJeztah any idea on this one?

**Comment by thaJeztah** [comment]
`\` is the default for line continuation in Dockerfiles, so `ENV D` being glued to the previous line looks like the expected behavior.

I'd have to look into the `commit -c` example, but IIRC, that feature was implemented a bit as a "hack" and the `-c` instructions were literally creating an (in-memory?) Dockerfile that's being parsed, so likely follows the same rules.

**Comment by Artem-B** [comment]
The backslash is properly escaped in both cases -- inside of the value it turns into a single backslash. Yet the quoted backslash at the end always gets stripped. I understand the gluing of lines if it were just a single backslash, but it's `\\` which causes this.

**Comment by thaJeztah** [comment]
Opened https://github.com/moby/buildkit/pull/1559 to fix
