### ISSUE TITLE
Cannot share drives with docker

### ISSUE THREAD

**Issue by near-ethic** [docker/for-win#5255]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: ECBD4EBC-E7DB-4B1F-8137-3A72CD830845/20191202083312

### Information

  - Windows Version: Windows 10 Enterprise Version 1903, Build 18362.175
  - Docker Desktop Version: 2.1.0.5 (40693)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Go to Settings > Shared drives
  2. Check any local drive
  3. Click Apply
  4. Unable to share with error: Firewall detected. A firewall is blocking file sharing between Windows and the containers. See documentation for more info.

I tried:
 - https://success.docker.com/article/error-a-firewall-is-blocking-file-sharing-between-windows-and-the-containers
 - https://github.com/docker/for-win/issues/1942
 - using my local Admin user
 - using my organizational user

This issue appeared after I unshared drives and tried to share them again.

**Comment by mikeparker** [comment]
We've rewritten how the file sharing works on latest edge version, if you're willing to give it a try it'll likely solve your problem: https://download.docker.com/win/edge/41561/Docker%20Desktop%20Installer.exe

**Comment by near-ethic** [comment]
The linked edge version fixes my issue. Thanks :)
