### ISSUE TITLE
Using docker with a VPN

### ISSUE THREAD

**Issue by ant-i-c-s** [docker/for-win#5257]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 049F09EA-61C1-4319-B9E8-7E1B8A8A7C65/20191202151016

### Expected behaviour

Docker can pull images while connected to Anyconnect VPN.

### Actual behaviour

Docker can't pull images.

### Information

  - Windows Version: Version	10.0.17763 Build 17763
  - Docker Desktop Version: Docker version 19.03.5, build 633a0ea
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. Start and connect to cisco anyconnect vpn
  2. Run `docker run hello-world` when it doesn't already exist

```
Unable to find image 'hello-world:latest' locally
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
```

It works fine without the VPN.

**Comment by acclaimuser** [comment]
This is real pain with VPN setup. There are many issues reported here on this topic but unfortunately there is no resolution still it seems.
