### ISSUE TITLE
Docker has been removed after the 2.1.0.5 (40693) upgrade

### ISSUE THREAD

**Issue by hossamEZZOUKH** [docker/for-win#5258]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Update docker smoothly
### Actual behavior
update is not performed, and docker is removed from my machine.
### Information
This behavior is reproducible, it's appear while updating to 2.1.0.5 (40693). I tried it for several times!!
I did not find any explanation yet.

### & please tell me , what other information can i afford to you ?

**Comment by mat007** [comment]
What does the final installation screen look like?
Also do you have any `install-log*.txt` file(s) in `%LOCALAPPDATA%\Docker`?

**Comment by hossamEZZOUKH** [comment]
### this is my install-log.txt

[install-log.txt](https://github.com/docker/for-win/files/3915905/install-log.txt)

### this the final installation screen 
![issue](https://user-images.githubusercontent.com/23157472/70039416-34134580-15ba-11ea-9f57-6f310cade295.PNG)

**Comment by mat007** [comment]
It seems you have a quite old installer file in `C:\Program Files\Docker\Docker` (like pre-2.1.0.0) that doesn’t want to get deleted and is blocking the new installer…
Can you try to uninstall Docker Desktop from the «Add or remove programs» Windows panel then installing the latest from https://download.docker.com/win/stable/Docker%20Desktop%20Installer.exe ?
Maybe you will need to manually delete `C:\Program Files\Docker\Docker` as well in-between.

Sorry about that…

**Comment by hossamEZZOUKH** [comment]
Thank you @mat007 
The issue was fixed by downloading the latest docker installer, also i needed some access rights on the Docker folder, for the delete..

Thank you again ..
