### ISSUE TITLE
[WSL 2] Docker for WSL 2 cannot be installed on Windows 10 Home

### ISSUE THREAD

**Issue by edoardomazzella** [docker/for-win#5259]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
It should be possible to install Docker Desktop on Windows 10 Home with a build containing WSL 2 feature

### Actual behavior
Installation does not start and the following message is shown:
Docker Desktop requires Windows 10 Pro or Enterprise version 15063 to run.

### Information

  - Windows Version: Windows 10 Home Build 19033.1
  - Docker Desktop Version: 2.1.6.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Run the Docker Desktop setup exe on  Windows 10 Home Build 19033.1

**Comment by mat007** [comment]
Yes, it’s a feature we’re going to release in a near future, please see #4586
