### ISSUE TITLE
ps -a

### ISSUE THREAD

**Issue by fredgate** [docker/for-win#526]
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by dgageot** [comment]
Hi @fredgate, I think something happened while you edited this ticket. It doesn't contain any information about the issue

**Comment by fredgate** [comment]
Sorry. It was a manipulation error that I had not seen. With several screens, I did not enter a text in the right place.
You can close and/or delete.
