### ISSUE TITLE
Docker Desktop 2.1.6.1 WSL Integration Always Reverts to Off on Reboot 

### ISSUE THREAD

**Issue by sc0ttwad3** [docker/for-win#5264]
**Docker Desktop 2.1.6.1 Edge Release** with WSL integration setting **'on'** (Ubuntu-18.04 distro) and running, without issue—**reverts on reboot**—to turning this setting **'off'** and integration stops running.

This repeats after every reboot, regardless of user or system initiated reboot, and while running on every Windows 10 insider build since Docker Desktop 2.1.6.1 edge was first released, and continues now up through the current **Windows 10 insider build 19033.1**

**To fix**: change the setting back to 'on' after every system reboot (obviously not an on-going solution).

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
 Kubernetes:
  Version:          v1.15.5
  StackAPI:         v1alpha3
```
![Docker-WSL-Integration-Off-Issue-02](https://user-images.githubusercontent.com/1682691/70022577-9f312d80-1562-11ea-93e9-4affcf3e8e78.jpg)

![Docker-WSL-Integration-Off-Issue-00](https://user-images.githubusercontent.com/1682691/70020266-1b734300-155a-11ea-8b0f-8c2c81695529.jpg)

On reboot, this setting always is always set back to 'off' and WSL integration isn't running.

![Docker-WSL-Integration-Off-Issue](https://user-images.githubusercontent.com/1682691/70020284-23cb7e00-155a-11ea-8c73-6ed00d7804fd.jpg)

**Comment by simonferquel** [comment]
Thanks, can you submit a diagnostic (using the troubleshooting screen) on your next restart ? It will help us diagnose what happens.

**Comment by sc0ttwad3** [comment]
I was about to send the diags, but then after today's latest Windows Insider build 19035.1 was complete, I ran through multiple reboots in my testing, and this issue has 
been resolved. Going to close this out.
