### ISSUE TITLE
er

### ISSUE THREAD

**Issue by marwi434** [docker/for-win#5265]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
There doesn't seem to be any info in this issue for us to be able to help you, so closing it.
