### ISSUE TITLE
Prevent Right Click of system tray menu items

### ISSUE THREAD

**Issue by seanclarkgithub** [docker/for-win#5267]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Right clicking the system tray icon should just display the menu
### Actual behavior
Right clicking system tray is often laggy and so a second right click actually clicks the quit menu item.
### Information

  - Windows Version:17763.864
  - Docker Desktop Version:2.1.0.1(37199)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:NO

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mikeparker** [comment]
Yes this is a good idea i've accidentally click Quit in the past also. I'll see what we can do.
