### ISSUE TITLE
[WSL2] docker CLI cannot connect to running docker engine

### ISSUE THREAD

**Issue by verglor** [docker/for-win#5268]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 83925FF1-D3EE-4CBF-A54A-68AC6D60F69F/20191203173658

### Expected behavior
`docker ps` typed in windows terminal should print list of docker containers.

### Actual behavior
`error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_wsl/v1.40/containers/json: open //./pipe/docker_wsl: The system cannot find the file specified.
`

### Information

  - Windows Version: 10.0.19033.1
  - Docker Desktop Version: 2.1.7.0 (41351)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

I can use kitematic or docker CLI from inside of wsl - only `C:/Program Files/Docker/Docker/resources/bin/docker.exe` cannot connect to engine.

```
>docker context use wsl
wsl
Current context is now "wsl"

>docker ps
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_wsl/v1.40/containers/json: open //./pipe/docker_wsl: The system cannot find the file specified.

>wsl docker ps
CONTAINER ID        IMAGE                                COMMAND             CREATED             STATUS              PORTS                   NAMES
520dd7578a07        kitematic/hello-world-nginx:latest   "sh /start.sh"      4 hours ago         Up 17 seconds       0.0.0.0:32768->80/tcp   hello-world-nginx
```
![](https://i.imgur.com/bpByqyE.png)

**Comment by paflynn-msft** [comment]
I believe that this is caused by having your default distro set to something other than Ubuntu. I had set fedoraremix as default distro and docker access via wsl2. Changing this setting/default distro didnt appear to resolve this in docker desktoop/unlock the setting option.

The docker desktop version 2.1.0.0 has a prerequisite checker that showed I was missing ubuntu, even though I had it installed. 

So I : 

1. uninstalled docker desktop,
2. Installed ubuntu 18.04 from the store 
3. from Powershell: ran wsl --set-version Ubuntu-18.04 2 Per https://docs.microsoft.com/en-us/windows/wsl/wsl2-install 
3. installed docker desktop 2.1.0.0
4. upgraded to docker desktop 2.1.6.1
5. I was then able to reenable docker on wsl2 option in docker settings
6. then I enabled access from each distro in Docker Settings  \ Resources \ WSL Integration 
![docker options for distro access](https://user-images.githubusercontent.com/28742167/70080955-87df5800-15d5-11ea-921c-20f57abf8a08.png)

**Comment by paflynn-msft** [comment]
Perhaps this does not have to do with default distro... I thought I had changed it to ubuntu-18.04 but it was set to fedoraremix the whole time I did the reisntall process.

So, this might have to do with a windows version upgrade ? Not sure, but a reinstall of docker desktop and installing ubuntu 18.04 lts resolved the issue.

**Comment by verglor** [comment]
My default distro is Ubuntu-18.04 and I never had any other distro installed:

![](https://i.imgur.com/5f5ARMC.png)

```
>wsl -l -v
  NAME                   STATE           VERSION
* Ubuntu-18.04           Running         2
  docker-desktop         Running         2
  docker-desktop-data    Running         2
```

**Comment by paflynn-msft** [comment]
Strange

**Comment by simonferquel** [comment]
This is because we don't use the wsl context anymore since we replace the whole hyper-v backend with wsl2.
Please use the default context and remove the old wsl context with docker context rm

**Comment by verglor** [comment]
Great, thanks :-)

**Comment by dbykadorov** [comment]
After update to Doker Desktop 2.1.7.0 (41536) I cant connect to docker from WSL2:

```
hudson@DESKTOP:/mnt/c/Users/hudson$ docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

I removed old wsl context

```
C:\Users\hudson>docker context list
NAME                DESCRIPTION                               DOCKER ENDPOINT                  KUBERNETES ENDPOINT   ORCHESTRATOR
default *           Current DOCKER_HOST based configuration   npipe:////./pipe/docker_engine                         swarm
```

WSL2 engine enabled: 

![image](https://user-images.githubusercontent.com/243108/70654994-7e568f80-1c68-11ea-8264-8ab5af99595a.png)

WSL integration enabled

![image](https://user-images.githubusercontent.com/243108/70655041-93cbb980-1c68-11ea-977e-61ffab24ad1f.png)

All WSLs have version 2

```
C:\Users\hudson>wsl -l -v
  NAME                   STATE           VERSION
* Ubuntu-18.04           Running         2
  docker-desktop         Running         2
  docker-desktop-data    Running         2
  Debian                 Stopped         2
```

How I can fix this?

**Comment by paflynn-msft** [comment]
> This is because we don't use the wsl context anymore since we replace the whole hyper-v backend with wsl2.
> Please use the default context and remove the old wsl context with **docker context rm**

**Comment by dbykadorov** [comment]
@paflynn-msft I removed wsl context before write this post. In Ubuntu and windows I have only default context:

``` 
UBUNTU
docker context list
NAME                DESCRIPTION                               DOCKER ENDPOINT               KUBERNETES ENDPOINT   ORCHESTRATOR
default *           Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                         swarm
```
``` 
WIN
docker context list
NAME                DESCRIPTION                               DOCKER ENDPOINT                  KUBERNETES ENDPOINT   ORCHESTRATOR
default *           Current DOCKER_HOST based configuration   npipe:////./pipe/docker_engine                         swarm
```

**Comment by simonferquel** [comment]
@dbykadorov Can you upload a diagnostic file and paste it's I'd here ? You can do this from the troubleshooting screen.

**Comment by dbykadorov** [comment]
@simonferquel Sorry, I just removed Docker Desktop and installed it again (2.1.7.0) - and it worked now.

Previous errors were caused by upgradig (not reinstalling) from 2.1.6.1 to 2.1.7.0 - maybe this information helps you.
