### ISSUE TITLE
[2.1.6.1] Can not see enable WSL 2 engine option

### ISSUE THREAD

**Issue by sep2** [docker/for-win#5277]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: FAB0BF2F-42FF-4C5E-BC1A-ECF72265C5D6/20191205073004

### Expected behavior
Can see the enable WSL2 engine option.

### Actual behavior
![image](https://user-images.githubusercontent.com/39055101/70213315-0114b180-1774-11ea-84bc-acbf3ffe39fc.png)

### Information
  - Is it reproducible? Yes
  - Is the problem new? No
  - Did the problem appear with an update? No
  - Windows Version: Build 19033.1
  - Docker Desktop Version: 2.1.6.1 (40900)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
  1. Install WSL 2 Ubuntu and restart
  2. Install Docker Desktop and restart

**Comment by roja45** [comment]
I have the same issue on build 19037.1, wsl 2 option does not appear

**Comment by PavelSosin-320** [comment]
I have exactly the same issue with Windows Pro Version 1909 build 18363.476 and Dokcer desktop 2.6.1,
i.e. everything is latest

**Comment by PavelSosin-320** [comment]
Diagnostic ID 1695A9B2-5AAE-4023-953F-F08D7698FC5A/20191210092121

**Comment by mat007** [comment]
Something you guys can try:
1. quit Docker Desktop
2. delete `%APPDATA%\Docker\already-enabled-features.json` and `%APPDATA%\Docker\features-cache.json`
3. make sure you’re connected to the Internet
4. start Docker Desktop

If it still doesn’t work can you post the new contents of these files (or upload a new diagnostics)?

**Comment by PavelSosin-320** [comment]
Just tested and after some deep dive in log I found: both already-enabled-features and features-cach exist but http://localhost/features ends with timeout ???
I suppose either some Windows security or Norton protection blocks it or feature request is issued too early and few retrys are necessary. It can work on Unix because preceding Unix version request is OK.

**Comment by PavelSosin-320** [comment]
It looks like WSL 2.0 issue - [WSL issue 4637](https://github.com/microsoft/WSL/issues/4673)
I also never see which distro is running: >wsl --list --running
There are no running distributions. I installed Ubuntu which is marked as Default

**Comment by roja45** [comment]
This morning the option has appeared.  Computer has been on all night, no restarts, no other changes, but I just started docker desktop again, and now the option has appeared.

**Comment by PavelSosin-320** [comment]
I suspect windows security more and more: http://localhost in my browser returns "connection refused" Also wget in WSL 2.0 console responses in the same way. Diagnostics log is filled with such requests. Every new Windows 10 release inforces network security more and more. ping6 to localhost ():1) is always OK

**Comment by PavelSosin-320** [comment]
I suppose that [WSL 2.0 support to localhost ](https://www.bleepingcomputer.com/news/security/wsl2-now-supports-localhost-connections-from-windows-10-apps/)

**Comment by PavelSosin-320** [comment]
That's it! After Windows emergency update for build 1609 installation checkbox is enabled but binding guidence mentioned in Microsoft notification has to be verified and adopted!

**Comment by mikeparker** [comment]
We've just released an update to the Edge channel which fixes various feature integration and detection with WSL 2, this may fix your issues: https://docs.docker.com/docker-for-windows/edge-release-notes/#docker-desktop-community-2170
