### ISSUE TITLE
Upgrading the Hyper-V DockerDesktopVM adding RAM scraps the VM!

### ISSUE THREAD

**Issue by NBardelot** [docker/for-win#5278]
OS = Window 10 (1909, up to date)
Docker Desktop for Windows up-to-date
Kubernetes installed via Docker Desktop and up-to-date
Engine = 19.03.5
Compose = 1.24.1
Kubernetes = 1.14.8
Notary = 0.6.1
Credential Helpers = 0.6.3
Machine = 0.16.2

I had several images I built + volumes and networks (using Docker Compose). I also had a namespace under Kubernetes with several services/pods/volumes/claims etc.

I go to the Docker Desktop GUI into ‘Advanced Settings’. I add 2Go of RAM. The message at the bottom of the screen says: ‘Docker will restart when applying those changes.’

Instead of being restarted, the VM has been scraped and replaced by a brand new VM. I've lost my volumes, images, etc. The Docker Engine shows nothing. The standalone Kubernetes does not contain my namespaces.

And here I'm lucky, everything I lost is recoverable from other sources. But that's about as bad a behaviour you can encounter… 😱

**Comment by hjoelr** [comment]
This happened to me too. I came here to report it and found it already reported. In my case it deleted the `DockerDesktop.vhdx` and started over with a fresh one.

![image](https://user-images.githubusercontent.com/221971/70655627-91e10680-1c26-11ea-811c-c2ad3bbb5ec5.png)

**Comment by dwpramik** [comment]
Any movement on this? I had a similar thing happen when decreasing the RAM allocation from 2GB to 1GB. After the service restarted all of my containers and images were gone.

![image](https://user-images.githubusercontent.com/3422093/72617489-0afb0a00-3907-11ea-9bde-42a72b752f52.png)

**Comment by mat007** [comment]
We tested this with the latest Edge release and the behaviour seems to be:
- decreasing the amount of memory scraps the images and containers, this is expected however there should be a popup to warn about this (we have now fixed this and it will be available in the next Stable and Edge releases)
- increasing the amount of memory does not scrap the images and containers (if it does it definitely is a bug, but we failed at reproducing it)

**Comment by cspeckmim** [comment]
@mat007 have you also noticed the volumes also being scrapped in addition to the containers and images? For us that is the more serious concern we have. For example if we're running PostgreSQL and have its database files persisted to a volume, changing the RAM will suddenly cause all data to be wiped out. While we're implementing backup & recovery solutions this is still pretty concerning behavior to lose volumes.

**Comment by fumunda** [comment]
Same here.  Added 2 CPU, 2 GB RAM, and 1GB to swap and my DockerDesktop.vhdx went from 2.22GB down to 105mb.  Everything gone.   

Doesn't speak well for using this is any kind of actual capacity.  Pretty disappointing.  I love docker, normally.

Win 10 Enterprise

**Comment by mat007** [comment]
Oh sorry, I shouldn’t reply to issues in the middle of the night 😅 I mixed it up with **Disk image size** in my previous comment: changing CPUs, RAM and/or Swap shouldn’t get rid of any data!

Can someone upload a set of diagnostics (Troubleshot window) preferably right after experiencing the issue?
Thanks!

**Comment by dwpramik** [comment]
Here are the most recent logs where I was able to reproduce this. This happened when I reduced the ram from 2GB to 1GB. Prior to the change I had 2 containers, 2 images, and 6 volumes. After the change, everything gone.

One thing that is very concerning to me is that this hasn't been a completely reproducible case for us. I tried multiple times today on one machine switching the RAM allocation up and down and no problems (even though I've had the issue on that machine before). Tried it on another machine and was able to get it to happen.

[20200120195109.zip](https://github.com/docker/for-win/files/4087680/20200120195109.zip)

**Comment by mat007** [comment]
Thank you @dwpramik, I have created an internal ticket and referenced this issue.
Yes, it’s a flaky behaviour. That doesn’t surprise me given we have automated tests to this. 😬 
I’m thinking this may be triggered by a heavy load of containers in the VM, but it’s just a hunch for now.

**Comment by dwpramik** [comment]
@mat007 Has there been any movement on this issue?

**Comment by mat007** [comment]
We’ve looked at the diagnostics but couldn’t see anything relevant.
We’ve also failed to reproduce it (and we have automated tests checking this).
Given that it’s quite a nasty bug we’ve moved the ticket to the next sprint so we can have a proper look again.

**Comment by cspeckmim** [comment]
I just tried this on my mac using 2.2.0.0 (42247), downsizing memory usage from 4gb to 2gb while having 2 running containers. I verified that all containers, images, and volumes remained after the downsize. The containers were stopped/started as expected.

Could the deletion of volumes be a Windows-only bug?

**Comment by NBardelot** [comment]
I'd like to point out that in my case (in the ticket description), on Windows, it was an **increase** in memory, not a downsizing. that caused the volumes and data to be dumped.

**Comment by mat007** [comment]
@dwpramik you said it happens every time on one of your machines?
Would you be able to install a custom build and give it a go if I make one with extra logging?

**Comment by dwpramik** [comment]
@mat007 maybe not every time but we were able to get it to happen pretty consistently. Sure we could try that out.

**Comment by mat007** [comment]
Thanks @dwpramik here is the link https://download-stage.docker.com/win/stable/42685/Docker%20Desktop%20Installer.exe
It’s basically a 2.2.0.2 with a few minor unrelated non-released fixes and some extra logging in the settings area.
If you manage to reproduce it, a diagnostics bundle would be really nice, thanks a lot!

**Comment by dwpramik** [comment]
@mat007 Just wanted to update you on my end. Unfortunately I haven't had any luck reproducing the issue from a 2.2 version. Both the install that you provided, as well as the latest 2.2.0.3. The version we initially had the issue on was 2.1.0.5. Would there be any way for you to provide a version of that install with the logging in the settings area? Just trying to think of ways that we can get these logs for you.

**Comment by mat007** [comment]
Yeah, I was a little hoping/fearing this might happen as the code in this area has changed a bit since 2.1.0.5.
It’d be nice to get to the bottom of this though given how nasty a bug it is…

Here is a custom build https://download-stage.docker.com/win/stable/42813/Docker%20Desktop%20Installer.exe
The version says 2.1.0.6 but don’t pay attention to it (also don’t use it outside of this experiment 😬).
You should probably uninstall any prior version before installing it too, although it will let you think it can be installed on top of a 2.2.0.x it will just fail…

Thanks a lot!

**Comment by mat007** [comment]
Oh and I had to remove some of the WSL Tech Preview bits to make the build so you’ll get a

![image](https://user-images.githubusercontent.com/2386884/74534024-2d4a6c80-4f33-11ea-9182-d3be3dd8817b.png)

but as long as you don’t click on Quit, that’s fine… 😅

**Comment by dwpramik** [comment]
@mat007 I got it to happen with that 2.1.0.5 install you provided. Here are the logs and the details:
[20200214141110.zip](https://github.com/docker/for-win/files/4204849/20200214141110.zip)

Base Settings:
1 CPU
2 GB Ram
1 GB Swap

2 Containers
2 Images
4 Volumes
Disk Size ~1.5 GB

Changed ram from 2 GB to 1 GB
All containers, images, and volumes gone. Disk wiped.

I know others reported having the issue when increasing the RAM, so I am going to see if I can get that to happen and provide more logs, but I wanted to send these off to you now.

**Comment by mat007** [comment]
Ah thanks, I managed to understand how this was triggered and managed to reproduce it in 2.1.0.5.
The frontend/UI part of the code has been rewritten in 2.2.0.0 and the backend/engine part in our current master, which explains why it doesn’t happen anymore.

I would advise to upgrade to either Stable 2.2.0.3 or Edge 2.2.1.0 (basically the same content) and if that happens again open a fresh issue as the cause would be different given that the faulty code is not there anymore.

Thanks again @dwpramik !

**Comment by dwpramik** [comment]
Great, thank you @mat007 !

**Comment by mat007** [comment]
If anyone can reproduce this issue with either a Stable 2.2.0.3+ or an Edge 2.2.1.0+ please get in touch, thanks!

**Comment by sergii-zhuravel** [comment]
@mat007  Hi. Just faced the same issue on Mac. I've updated the Docker Desktop recently, just started it and found out that there is no any containers and images.  
Docker Desktop Community Stable 2.2.0.3(42716)

Is it possible to restore my old images/containers? (maybe there are in some folder..)

**Comment by isandow** [comment]
The update for 2.2.0.4 just purged the `.docker` folder in my home folder on macos. All databases gone
