### ISSUE TITLE
When built with --squash option, previously created folders are missing in the final image

### ISSUE THREAD

**Issue by elutsky** [docker/for-win#528]
### Expected behavior
When built with --squash option, folders created in previous steps **supposed to be available on future steps**

### Actual behavior
When built with --squash option, folders created in previous steps **are not available (missing)** on future steps

### Information

docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      windows/amd64
 Experimental: true

Diagnostic ID : 59D769DD-8A58-432A-8165-4FDE4665FF05/2017-02-25_07-17-30, 59D769DD-8A58-432A-8165-4FDE4665FF05/2017-02-25_07-48-56
![image](https://cloud.githubusercontent.com/assets/7150258/23328474/5fd1814e-fb2a-11e6-946a-a5b80d26d303.png)

### Steps to reproduce the behavior
Dockerfile:
```
FROM microsoft/aspnet:4.6.2
SHELL ["powershell","-command"]
RUN mkdir C:\tools; \
        mkdir C:\approot;
COPY /tools/ c:/tools/
RUN dir

```
##   1. Build with --squash option: _docker build --no-cache **--squash** -t test . -f Dockerfile.issue_

output:
Sending build context to Docker daemon 48.67 MB

Step 1/5 : FROM microsoft/aspnet:4.6.2
 ---> e761eca2f8df
Step 2/5 : SHELL powershell -command
 ---> Running in d48b8bb7ae03
 ---> 3e21615782c6
Removing intermediate container d48b8bb7ae03
Step 3/5 : RUN mkdir C:\tools;     mkdir C:\approot;
 ---> Running in 9d4b7b0fd44e

    Directory: C:\

Mode                LastWriteTime         Length Name                          
----                -------------         ------ ----                          
d-----        2/25/2017   7:29 AM                tools                         
d-----        2/25/2017   7:29 AM                approot                       

 ---> 4a15e9683af5
Removing intermediate container 9d4b7b0fd44e
Step 4/5 : COPY /tools/ c:/tools/
 ---> 80a819770da7
Removing intermediate container df78c5a5696c
Step 5/5 : RUN dir
 ---> Running in dc2217b49fdc

    Directory: C:\

Mode                LastWriteTime         Length Name                          
----                -------------         ------ ----                          
d-----        2/25/2017   7:29 AM                **approot**                       
d-----        2/25/2017   7:29 AM                inetpub                       
d-----        7/16/2016   4:18 PM                PerfLogs                      
d-r---        2/25/2017   7:30 AM                Program Files                 
d-----        7/16/2016   4:18 PM                Program Files (x86)           
d-----        2/25/2017   7:29 AM                **tools**                         
d-r---        1/18/2017  10:43 PM                Users                         
d-----        1/18/2017   8:43 PM                Windows                       
-a----       11/23/2016  12:45 AM           1894 License.txt                   
-a----       10/14/2016   2:55 AM         135864 ServiceMonitor.exe            

 ---> d43865c147fa
Removing intermediate container dc2217b49fdc
Successfully built d43865c147fa

##   2. Running container
_**docker run -d --name issue test**_
**_docker exec -i issue cmd_**
C:\>**_dir_**
dir
 Volume in drive C has no label.
 Volume Serial Number is B414-5C6D

 Directory of C:\

02/25/2017  07:31 AM    <DIR>          inetpub
11/23/2016  12:45 AM             1,894 License.txt
07/16/2016  03:18 PM    <DIR>          PerfLogs
01/08/2017  11:24 PM    <DIR>          Program Files
07/16/2016  03:18 PM    <DIR>          Program Files (x86)
10/14/2016  01:55 AM           135,864 ServiceMonitor.exe
01/18/2017  10:43 PM    <DIR>          Users
01/18/2017  08:43 PM    <DIR>          Windows
               2 File(s)        137,758 bytes
               6 Dir(s)  21,169,467,392 bytes free

##   3. Building **without --squash** option: _docker build --no-cache  -t test . -f Dockerfile.issue_

Output:
Sending build context to Docker daemon 48.67 MB

Step 1/5 : FROM microsoft/aspnet:4.6.2
 ---> e761eca2f8df
Step 2/5 : SHELL powershell -command
 ---> Running in 5f76e72634dd
 ---> 0c56e7a0e7d9
Removing intermediate container 5f76e72634dd
Step 3/5 : RUN mkdir C:\tools;     mkdir C:\approot;
 ---> Running in fcb788ba13d3

    Directory: C:\

Mode                LastWriteTime         Length Name                          
----                -------------         ------ ----                          
d-----        2/25/2017   7:37 AM                tools                         
d-----        2/25/2017   7:37 AM                approot                       

 ---> 68f73a4a8485
Removing intermediate container fcb788ba13d3
Step 4/5 : COPY /tools/ c:/tools/
 ---> 5bb0d0d90c4a
Removing intermediate container bbdb355d0c3b
Step 5/5 : RUN dir
 ---> Running in 05bedc51783f

    Directory: C:\

Mode                LastWriteTime         Length Name                          
----                -------------         ------ ----                          
d-----        2/25/2017   7:37 AM                approot                       
d-----        2/25/2017   7:37 AM                inetpub                       
d-----        7/16/2016   4:18 PM                PerfLogs                      
d-r---        2/25/2017   7:37 AM                Program Files                 
d-----        7/16/2016   4:18 PM                Program Files (x86)           
d-----        2/25/2017   7:37 AM                tools                         
d-r---        1/18/2017  10:43 PM                Users                         
d-----        1/18/2017   8:43 PM                Windows                       
-a----       11/23/2016  12:45 AM           1894 License.txt                   
-a----       10/14/2016   2:55 AM         135864 ServiceMonitor.exe            

 ---> 02f61b895bda
Removing intermediate container 05bedc51783f
Successfully built 02f61b895bda

## 4. Running container:
_**docker run -d --name issue test**_
**_docker exec -i issue cmd_**
C:\>**_dir_**
dir
 Volume in drive C has no label.
 Volume Serial Number is B414-5C6D

 Directory of C:\

02/25/2017  07:37 AM    <DIR>          **approot**
02/25/2017  07:40 AM    <DIR>          inetpub
11/23/2016  12:45 AM             1,894 License.txt
07/16/2016  03:18 PM    <DIR>          PerfLogs
01/08/2017  11:24 PM    <DIR>          Program Files
07/16/2016  03:18 PM    <DIR>          Program Files (x86)
10/14/2016  01:55 AM           135,864 ServiceMonitor.exe
02/25/2017  07:37 AM    <DIR>          **tools**
01/18/2017  10:43 PM    <DIR>          Users
01/18/2017  08:43 PM    <DIR>          Windows
               2 File(s)        137,758 bytes
               8 Dir(s)  21,173,391,360 bytes free

**Comment by friism** [comment]
When I try to run squashed image, Docker just hangs.

cc @jhowardmsft

**Comment by simonferquel** [comment]
This is a windows docker engine related issue more than a docker for desktop one.

Could you please reopen an issue on https://github.com/docker/docker/issues with a hint that it is specific to Windows Containers ?

**Comment by elutsky** [comment]
As @simonferquel  asked - moved to https://github.com/docker/docker/issues/31468
