### ISSUE TITLE
Creating the virtual machine failed.

### ISSUE THREAD

**Issue by Starov88** [docker/for-win#5282]
[dockerLog.txt](https://github.com/docker/for-win/files/3932033/dockerLog.txt)
Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Creating the virtual machine failed.

   в Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   в Docker.Actions.<>c__DisplayClass36_0.<SwitchDaemon>b__0()
   в Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

**Comment by ramonchk** [comment]
same

**Comment by mikeparker** [comment]
Have you tried with latest edge version?
