### ISSUE TITLE
Increasing Docker RAM (from 2 to 4GB) and swap space (from 1 to 2GB) causes fatal crash error

### ISSUE THREAD

**Issue by richdevboston** [docker/for-win#5284]
- [ x  ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Increase RAM and swap space and experience Docker build working properly.

### Actual behavior

CRASH, CRASH, CRASH !!! 

I have to reset Docker to factory reset settings to get it to run at all after that.  

It will not successfully restart after resetting itself to factory RAM and swap space settings.  

### Information

  - Windows Version:  10 Professional 
  - Docker Desktop Version:  
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ... Use Docker Desktop to increase RAM (from 2 to 4GB) and swap space (from 1 to 2GB) causes fatal crash error
  2. ...  Get Error Message below

Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The computer 'DATASCIENCEMAES' could not be resolved. Make sure you typed the machine name correctly and that you have network access.

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass27_0.<ResetToDefault>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

[20191208034408.zip](https://github.com/docker/for-win/files/3935837/20191208034408.zip)

**Comment by richdevboston** [comment]
Docker is a very unstable product on Windows (community edition and commercial product).  I have had problems like this every time I have gone to use it over the past 2 years, I get fatal installation errors, or configuration errors, requiring me to lose minutes to hours of time debugging, changing configuration files, upgrading components, etc.  Eventually I get it working, but then a nagging upgrade required by a new containerized application breaks my working Docker base installation and I have to start over.  I wish Docker platform was more robust and immune to its own upgrades.

**Comment by NBardelot** [comment]
Seems to be related to my issue: 
https://github.com/docker/for-win/issues/5278

**Comment by mikeparker** [comment]
What version are you running?
What do you mean by reset to factory works but also doesn't work?
