### ISSUE TITLE
Error to install Docker 2.1.0.5 (fullfilled)

### ISSUE THREAD

**Issue by felipefqa** [docker/for-win#5285]
I get a issue when install docker for my Windows 10:

![image](https://user-images.githubusercontent.com/15947453/70384503-1a795180-195e-11ea-9536-12172413f1a4.png)

my build version is 

BuildNumber                               : 18362

**Comment by mikeparker** [comment]
Are you running windows home, pro, or enterprise?

**Comment by gajwani** [comment]
Question: I'm running Windows 10 Home, but WSL2 is available. I have it installed and I'm using it. Will I be unable to use Docker Desktop with it because it's not Pro/Enterprise?

**Comment by mat007** [comment]
@gajwani support for WSL 2 on Windows Home is in the works and will likely be available on Edge in January.
