### ISSUE TITLE
docker images fails

### ISSUE THREAD

**Issue by tbuffryslb** [docker/for-win#5289]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker images should provide images informatiion

### Actual behavior
having error:
C:\WINDOWS\system32>Net stop com.docker.service
The Docker Desktop Service service is stopping.
The Docker Desktop Service service was stopped successfully.

C:\WINDOWS\system32>Net start com.docker.service
The Docker Desktop Service service is starting.
The Docker Desktop Service service was started successfully.

C:\WINDOWS\system32>docker images
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/images/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

### Information

  - Windows Version: 10.0.17134
  - Docker Desktop Version: .1.0.5 (40693)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

I tried, reset to default factory, uninstall / reinstall and having "Docker for windows running and white in the status bar"

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mikeparker** [comment]
Did you start docker desktop? Why are you using net start / stop with the service?

**Comment by tbuffryslb** [comment]
yes docker desktop is running, docker service is running, i used net start stop to resart it for testing

**Comment by tbuffryslb** [comment]
Resolved by turn off Hyper-V from windows feature, restart, and turn on
