### ISSUE TITLE
Hang when sharing drive

### ISSUE THREAD

**Issue by SamSuffit** [docker/for-win#5292]
- [*] I have tried with the latest version of my channel (Stable or Edge)
  - [*] I have uploaded Diagnostics
  - Diagnostics ID: ECE06ACD-A38D-4FE3-A5C7-FF62A6DED5C7/20191209144921

### Expected behavior

To share drives

### Actual behavior

I'm using docker in company environment . I've got a active directory account which are not admin for my computer.
I'm lauching docker with and admin account (still defined in the actvie directory) which can not log into windows but has admin right for my computer.

When I'm sharing c drive (the only I got) docker stall in Updating for ever.

![image](https://user-images.githubusercontent.com/6215499/70446149-fcfed180-1a9c-11ea-9d47-c3c78081459c.png)

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mikeparker** [comment]
Have you tried the latest edge version?

**Comment by SamSuffit** [comment]
Sorry for the dailed response.

I can't test with the last edge version : 

![image](https://user-images.githubusercontent.com/6215499/70984909-96407000-20bb-11ea-9127-0ed4d0bc7e72.png)

And it still failed with the latest 2.1.05

**Comment by SamSuffit** [comment]
Fix in 2.2.2.0
I think this wàs caused dy windows service named "server" which was off on my laptop
