### ISSUE TITLE
Docker failing to start

### ISSUE THREAD

**Issue by mwoodpatrick** [docker/for-win#5298]
After installing windows 10  Version: 10.0.19035 N/A Build 19035 docker is refusing to start see crash report 5B81673D-4614-408D-AAD6-6CBB9BBBE6B5/20191210225939

**Comment by nconder** [comment]
@mwoodpatrick see if you have these updates https://github.com/docker/for-win/issues/5304 installed recently then try uninstalling if it coincides with your troubles.

**Comment by mikeparker** [comment]
Can you fill in the issue template please?

**Comment by mwoodpatrick** [comment]
I have tried with the latest version of my channel (Stable or Edge) still fails with 2.1.7.0(41536)
 I have uploaded Diagnostics
  - Diagnostics ID: 5B81673D-4614-408D-AAD6-6CBB9BBBE6B5/20191212021512
                             5B81673D-4614-408D-AAD6-6CBB9BBBE6B5/20191210225939
                             
### Expected behavior
 lifecycle-server should start and docker running under Ubuntu 18.04 (using WSL 2) should be runnable 

### Actual behavior 
got error:
Timed out waiting for the lifecycle-server to start.
This may be the result of a slow environment or there may be a real problem.
This timeout can be increased by editing settings.json, value 'lifecycleTimeoutSeconds'.
This file is usually in C:\Users\(your username)\AppData\Roaming\Docker

   at Docker.Backend.LifecycleClient.WaitForServerUp(TimeSpan pingTimeout)
   at Docker.Backend.ContainerEngine.WslEngine.DoStart(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.ContainerEngine.WslEngine.Start(Settings settings, String daemonOptions, Credential credential, Boolean retry)
   at Docker.Backend.ContainerEngine.WslEngine.Start(Settings settings, String daemonOptions, Credential credential, Boolean retry)
   at Docker.Backend.ContainerEngine.WslEngine.Start(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.BackendNamedPipeServer.<Run>b__8_2(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

### Information

  - Windows Version:  Version: 10.0.19035 N/A Build 19035

  - Docker Desktop Version: 2.1.7.0(41536)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No, running windows 10 with WSL 2 enabled on HP Spectre x360

### Steps to reproduce the behavior
I just restarted windows with above software and docker hung.  When I look at my update history I see:

 Windows 10 Insider Preview 19035.1 (vb_release) Successfully installed on ‎12/‎7/‎2019
 Windows 10 Insider Preview 19033.1 (vb_release) Successfully installed on ‎12/‎2/‎2019
 ...
											
But when I select "Uninstall updates" it says "No updates are installed on this computer"!

I have run  "sfc /SCANNOW" and it reported no issues.

Investigating further, please let me know if you have any suggestions of anything I can do to debug these issues further.




  1. ...
  2. ...

**Comment by mwoodpatrick** [comment]
I am running with windows 10.0.19536 N/A Build 19536 & docker 2.1.7.0 (41536) and things appear to be working normally. When running with WSL 2 (Ubuntu 18.04.3 LTS) where can I find the docker log files? Also where is the data for volumes stored in the host OS the data reported by: 

docker inspect lemp_wordpress_dbdata

does not appear to be correct, there is no /var/lib/docker directory
[
    {
        "CreatedAt": "2019-12-22T23:07:51Z",
        "Driver": "local",
        "Labels": {
            "com.docker.compose.project": "lemp_wordpress",
            "com.docker.compose.version": "1.25.1-rc1",
            "com.docker.compose.volume": "dbdata"
        },
        "Mountpoint": "/var/lib/docker/volumes/lemp_wordpress_dbdata/_data",
        "Name": "lemp_wordpress_dbdata",
        "Options": null,
        "Scope": "local"
    }
]

**Comment by mrbrazzi** [comment]
- [X] I have tried with the latest version of my channel (Stable)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: E37D09A7-F695-4F6A-9380-A544CF140879/20200126235340

### Expected behavior
Docker start without any error

### Actual behavior
Docker fails when start

### Information
  - Windows Version: Windows 10 Pro 1909 build 18363.592
  - Docker Desktop Version: 2.1.0.5 (40693)

### Steps to reproduce the behavior
  1. Double click on Docker's desktop icon
