### ISSUE TITLE
Crash after allowing "Elevated access" on Windows after system boot

### ISSUE THREAD

**Issue by hasMobi** [docker/for-win#53]
### Expected behavior

Docker service to start.

### Actual behavior

Docker service crashes on boot.

### Information

When I boot up the PC (Windows 10 Pro), I get a popup saying that the Docker service is not running and I need to enable Elevated access in Windows for it to start. I click Yes twice and then I get the following "Error during initialization" screen which is frozen, meaning that it's stuck there forever.

![image](https://cloud.githubusercontent.com/assets/9678143/17866828/b54c16be-68b0-11e6-9ef0-d905bcca1e10.png)

### Steps to reproduce the behavior

1. Boot up PC.
2. Wait for Docker to autostart.

### Log file contents:
http://pastebin.com/vCACfiZi

**Comment by rneugeba** [comment]
@hasMobi thanks for the report. Could you retry with the latest Beta24 from https://download.docker.com/win/beta/InstallDocker.msi

Thanks

**Comment by friism** [comment]
@hasMobi closing this issue for now, please report back if you're still seeing this problem with beta25 which was released yesterday.
