### ISSUE TITLE
Windows 10 install issues v 2.1.6.1 dell laptop

### ISSUE THREAD

**Issue by AlgoBeach** [docker/for-win#5300]
One or more errors occurred.

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass28_0.<ResetToDefault>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

  - [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker desktop to run
### Actual behavior
fails on bootup
### Information
See error messages above
Please, help us understand the problem.  For instance:
  - Is it reproducible? yes
  - Is the problem new? with this instllation
  - Did the problem appear with an update? no reinstall
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.
-->
  - Windows Version: Win 10
  - Docker Desktop Version:2.1.6.1
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
windows 10 w/ WSL 2.0

### Steps to reproduce the behavior
<!start docker desktop
A reproducible case, Dockerfiles with reproduction inside is best.
-->

  1. ...
  2. ...

**Comment by mat007** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-windows/troubleshoot?
