### ISSUE TITLE
Error During Connecting

### ISSUE THREAD

**Issue by Emmanuelaaron** [docker/for-win#5301]
I have just installed Docker on my windows 10 machine, but when I run this commande `docker run hello-world`, I get the error below
`docker: error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/create: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
See 'docker run --help'.`

I have tries all the options at [here](https://success.docker.com/article/docker-for-windows-fails-with-a-daemon-not-running-message) but none has worked.

Any immediate response will be highly appreciated

**Comment by mikeparker** [comment]
Sorry for the basic question, but was Docker Desktop actually running? Just installing it is not enough.

**Comment by Emmanuelaaron** [comment]
Thanks @mikeparker  for reaching out, well I resolved this issue by enabling virtualization, Docker is now running and now the only blocker I'm facing is that when try to run this command `docker run postgres:latest`, I get the error below
`latest: Pulling from library/postgres`
`no matching manifest for windows/amd64 10.0.18362 in the manifest list entries`

I really do not know how to resolve it.

**Comment by mikeparker** [comment]
Most likely this https://stackoverflow.com/a/57548944/1554346

Do you mean enabling virtualization in your BIOS? In windows?

**Comment by Emmanuelaaron** [comment]
Yes enabling virtualization in the BIOS in Windows.
Well I tried the solution on the link instead I was getting a not enough memory error while switching the containers. Even when  i tried to create more space all was in vain.

**Comment by Emmanuelaaron** [comment]
Thanks @mikeparker, I managed to bypass the issue above. Instead of switching to linux containers I followed the steps below.

`Right click Docker instance`
`Go to Settings`
`Daemon`
`Advanced`
`Set the "experimental": true`
`Restart Docker`
