### ISSUE TITLE
Windows 10 updates causing docker failure to start

### ISSUE THREAD

**Issue by nconder** [docker/for-win#5304]
Docker Desktop running on Windows 10 1909 is failing to start with one or both updates KB4533002 and KB4530684.

I uninstalled both updates and things are back to normal. I was unable to produce log / trouble shooting files for this event. The machine is very slow during this issue causing system wide slowdowns.

I will try to nail down exactly what update it is during off hours with logs.

Docker 2.1.0.5(40693)
Engine 19.03.05

**Comment by mwoodpatrick** [comment]
Very curious I'm showing 

    Windows 10 Insider Preview 19035.1 (vb_release) Successfully installed on ‎12/‎7/‎2019
    Windows 10 Insider Preview 19033.1 (vb_release) Successfully installed on ‎12/‎2/‎2019
     ...

But when I select "Uninstall updates" it says "No updates are installed on this computer" investigating further and running sfc

**Comment by nconder** [comment]
I am unable to reproduce the issue. I have reinstalled the Windows updates that original may have caused the issues and everything is running fine.
