### ISSUE TITLE
Docker Desktop will not start, or: "This error may also indicate that the docker daemon is not running"

### ISSUE THREAD

**Issue by matt-bernhardt** [docker/for-win#5305]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F165E8F9-8681-4909-8309-BC9F1E82A64F/20191211205742

### Expected behavior
* Being able to start Docker Desktop
* Non-error responses from the Docker CLI on Windows

### Actual behavior
Docker Desktop fails with this error box:
![image](https://user-images.githubusercontent.com/1403248/70660998-5b5cb900-1c31-11ea-8d5b-b421f4d6d1b3.png)

Attempting to use the Docker CLI - whether in a command prompt, WSL, PowerShell, or Git Bash for Windows - generates mention that the docker daemon is not running.

#### Command prompt
```
C:\docker>docker ps
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

#### WSL
```
mjbernha@LIBS-0500865:/mnt/c/Windows/System32$ docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

#### Powershell
```
PS C:\Users\mjbernha> docker ps
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

#### Git Bash for Windows
```
mjbernha@LIBS-0500865 MINGW64 ~
$ docker ps
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

### Information

  - Windows Version: 10
  - Docker Desktop Version: 19.03.5, build 633a0ea
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

I have tried uninstalling and re-installing Docker Desktop, and consulted various articles that have recommended various steps. I don't use Docker frequently, and do remember some tension in the past where running Vagrant (or perhaps more accurately VirtualBox) would prevent Docker from running. When I would start Vagrant, I would be prompted to do _something_ in order to get it to run, with the warning that this would affect Docker (somewhere in here Hyper-V was also mentioned).

However, when I now try to run Docker, I see no similar mentions that provide any useful information. I have checked within the Task Manager that Virtualization is enabled (the link from the error box that I screenshotted above). Virtualization is listed as being enabled.

I also see a link from https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization-must-be-enabled that leads to https://github.com/docker/for-win/issues/74 - which seems odd to me as that issue was described "way messy with lots of different issues posted by users" before being closed and locked two years ago.

**Please note**
It is entirely possible that this issue is being caused by some aspect of my computer that is not Docker Desktop. I somewhat suspect that the issue lies in the cluster of Hyper-V, Virtualbox, or related systems. As a result, I'm not entirely hopeful that reporting this issue here will result in a solution - but perhaps I am wrong in my diagnosis. At the least, because my following Docker links has led me here, I want to describe what I'm seeing in the hope that someone else might find some value in it.

### Steps to reproduce the behavior

I would love to be able to produce a Dockerfile in order to reproduce this issue - because that would imply that Docker was running in some form on my computer.

The best I can manage right now is something like:
  1. Install Docker Desktop from the "Download Docker Desktop for Windows" link at https://hub.docker.com/?overlay=onboarding
  2. Attempt one of the following steps:
  * Launch Docker Desktop (observe the error box screenshotted above)
  * Run `docker ps` from any CLI on Windows 10 (observe the outcome included under "Actual behvaior" above)

**Comment by matt-bernhardt** [comment]
Relatively quick update - I think I finally resolved this. (Of course, moments after writing this).

Apparent solution:
Hyper-V, despite being listed under "Turn Windows features on or off" as being active, _was not in fact active_. This became apparent when running `systeminfo` under PowerShell, and seeing that the requirements were listed as met (which is not the output you would expect were Hyper-V actually running).

Steps:
* Open "Turn Windows features on or off"
* Turn Hyper-V off (uncheck box, making sure all sub-components are marked as off)
* Hit "Ok" - your machine will reboot
* When your computer starts up again, open "Turn Windows features on or off" and turn Hyper-V back on. Your machine will reboot again.

Confirmation:
* Within Powershell, `systeminfo` now ends with the phrase `Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.`
* `docker ps` behaves as expected
* The Hello World onboarding tutorial functions as expected.

**Comment by Rea2** [comment]
Thank you, man! You've made my day. It works great!/

**Comment by coniye** [comment]
Matt - You genius!!!!
Thank you

**Comment by kostyden** [comment]
Thank you! I quit on docker about a year ago because of this issue. After having nice experience with docker on Mac, decided to have another try.

**Comment by RajaKrovvidi** [comment]
![image](https://user-images.githubusercontent.com/14907732/86499534-ab44ce00-bd83-11ea-9ef5-b3186577bc34.png)

Still get the error after following your suggestion.

**Comment by rajeevchaturvedi** [comment]
Thank you @matt-bernhardt !

**Comment by MarcosScavone** [comment]
Another solution:
https://docs.microsoft.com/en-us/windows/wsl/install-win10
