### ISSUE TITLE
Registry Symbolic Link lost when building an image

### ISSUE THREAD

**Issue by robe070** [docker/for-win#5316]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics. **I don't know which diagnostics are relevant to this Windows behavior.**
  - Diagnostics ID:

### Expected behavior
Registry Symbolic Link continues to work in Container

### Actual behavior
Symbolic link is no longer recongised by Windows as a symbolic link
PS C:\> reg query HKEY_LOCAL_MACHINE\Software\LANSA

HKEY_LOCAL_MACHINE\Software\LANSA
    SymbolicLinkValue    REG_LINK    5C00520065006700690073007400720079005C004D0041004300480049004E0045005C0053006F0066007400
77006100720065005C0057006F00770036003400330032004E006F00640065005C004C0041004E0053004100

### Information

  - It is reproducible
  - Its in Images mcr.microsoft.com/windows/servercore/iis:windowsservercore-1903 and 1909
  - Host Windows Version: Microsoft Windows [Version 10.0.18363.535]
  - Docker Desktop Version: 2.1.0.5 (40693)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
No

### Steps to see behavior working

  1. Run a 1909 container
`docker run -it --isolation=process -v h:\temp:c:\temp mcr.microsoft.com/windows/servercore/iis:windowsservercore-1909
`

Note: Put the program x64SoftwareKeyLink.exe, described in repro section, in the h:\temp directory or equivalent.

2. Run another powershell session into the container

`docker exec -it [id] powershell`

3. Run same commands as in the dockerfile below

```
reg add HKEY_LOCAL_MACHINE\Software\WOW6432Node\LANSA; `
reg query HKEY_LOCAL_MACHINE\Software\WOW6432Node\LANSA; `
c:\temp\x64SoftwareKeyLink.exe LANSA; `
reg query HKEY_LOCAL_MACHINE\Software\LANSA
```

  4. Result:
```
The operation completed successfully.

HKEY_LOCAL_MACHINE\Software\WOW6432Node\LANSA
    (Default)    REG_SZ

Setting symlink key succeeded

HKEY_LOCAL_MACHINE\Software\LANSA
    (Default)    REG_SZ
```

### Steps to reproduce the behavior

  1. Dockerfile

```
# escape=`
FROM mcr.microsoft.com/windows/servercore/iis:windowsservercore-1909
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
RUN Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine
COPY .\*.exe .\
RUN reg add HKEY_LOCAL_MACHINE\Software\WOW6432Node\LANSA; `
    reg query HKEY_LOCAL_MACHINE\Software\WOW6432Node\LANSA; `
    .\x64SoftwareKeyLink.exe LANSA; `
    reg query HKEY_LOCAL_MACHINE\Software\LANSA
```
  2. The program .\x64SoftwareKeyLink.exe and its source code may be found [here]. (https://www.codeproject.com/Articles/11973/Registry-Symbolic-Links). The program needs to be in the Dockerfile directory

  3. Run the new image and powershell into it and run this command

`reg query HKEY_LOCAL_MACHINE\Software\LANSA`

  4. Result:

```
HKEY_LOCAL_MACHINE\Software\LANSA
    SymbolicLinkValue    REG_LINK    5C00520065006700690073007400720079005C004D0041004300480049004E0045005C0053006F0066007400
77006100720065005C0057006F00770036003400330032004E006F00640065005C004C0041004E0053004100
```

**Comment by robe070** [comment]
/remove-lifecycle stale

warm regards

Rob Goodridge

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place?
