### ISSUE TITLE
Can not access machine on hosts's local network from within container

### ISSUE THREAD

**Issue by TheKvist** [docker/for-win#5319]
Hello,

I am trying to migrate our development enviroment in the company into Docker containers. My host machine is in the company's network and behind our corporate proxies. The containers need access to the internet as well as to machines on our local network.
As for the internet access, it worked fine so far, but I am not able to establish any connection to the machines on the local network. I've searched the web for quite a while now but could not find any solution to my problem.

For example, we have a machine running on 192.168.40.191, which I can ping from WSL and get a response. When I try to ping it from inside any container, nothing happens.

I have not made any special configuration to the Docker daemon besides from setting the DNS settings in the "Network" tab to the same address the Ethernet adapter on the host is configured to use, so I don't really understand what's happening here.

As far as DNS is concerned, I have been trying to find a solution here https://docs.docker.com/v17.09/engine/userguide/networking/default_network/configure-dns/, where it says "[...] in the absence of the --dns=IP_ADDRESS..., --dns-search=DOMAIN..., or --dns-opt=OPTION... options, Docker makes each container’s /etc/resolv.conf look like the /etc/resolv.conf of the host machine", so I checked the /etc/resolv.conf inside the container and it's only line of content is

    nameserver 192.168.65.1

However, this address is completely unknown to me. The actual address of the DNS server in our network is 192.168.50.4, so I wonder what's going on here and where Docker got that other address from. Moreover, with this address it's the other way around, the container can ping it but WSL can not. To rule out that it may be related to WSL itself, I tried from CMD directly on the host, to no avail.

Did I miss any configuration or something? I never used Docker in a corporate environment before and all of these things that always worked perfectly now suddenly going wrong are completely new to me. Any help would be greatly appreciated.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 1F130026-13D1-4183-AF9E-0D7FBAE50FCB/20191213103738

### Expected behavior

* Docker Containers use the same DNS as the Docker Host
* Addresses pinged in the host's local network from within the container respond

### Actual behavior

* Local network addresses can not be reached by any means

### Information

  - Windows Version: Windows 10 Pro 1809 Build 17763.529
  - Docker Desktop Version: 2.1.0.5
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

**Comment by TheKvist** [comment]
Does nobody have even an idea? I can't imagine this is an edge case and I'd really need some help.

**Comment by monjjindo** [comment]
@TheKvist Were you able to find a solution for this? I'm experiencing the same issue and have been surprised that this doesn't seem to be more widespread. When I ping the server name, I can see it resolves the correct IP but never gets a response.

**Comment by monjjindo** [comment]
In case anyone else finds this, I was able to find a solution to the issue I was facing. Apparently, my work is using the same subnet as the default Docker one. Changing Docker's default subnet resolved the issues I was seeing.
