### ISSUE TITLE
Error loading Newtonsoft.Json, on Docker startup

### ISSUE THREAD

**Issue by shashank-kaul-webjet** [docker/for-win#532]
### Expected behavior
Docker for windows starts up

### Actual behavior
Docker crashes on startup, with error loading' Newtonsoft.Json, Version=8.0.0.0'

### Information
It seems that there is a conflict within docker about which version of Newtonsoft.JSON is required.
The default version of the JSON assembly is 9.0.1.19813. On startup i get an error indicating that docker can't find version 8.0.

I manually replaced the dll with veriosn 8.0.3.19514. The docker startup proceedes a bit further this time, but then i get an error indication that docker can't find Newtonsoft.JSON 9.0!

### Steps to reproduce the behavior

1. Startup docker on windows
2. Get error loading ' Newtonsoft.Json, Version=8.0.0.0'
3. Replace JSON dll with verion 9
4. Startup docker
5. Get error loading ' Newtonsoft.Json, Version=9.0.0.0'

log files are attached indicating both errors.

[log_version8_Error.txt](https://github.com/docker/for-win/files/802339/log_version8_Error.txt)
[log_version9_Error.txt](https://github.com/docker/for-win/files/802340/log_version9_Error.txt)

**Comment by simonferquel** [comment]
Can you verify that your installation folder has a "Docker for Windows.exe.config" file with correct binding redirects ?

**Comment by shashank-kaul-webjet** [comment]
After some invistigation i figured what was happening.

Our sysadmin using MS Intune, was installing an older version of docker. This older version clashed with the current version. 
The config fles said version 8 of JSON required but the folder had version 9

I'm closing this issue.
Thanks for you help.
