### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by Bhushan-cbs** [docker/for-win#5338]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Bhushan-cbs** [comment]
While opening Docker it says system is out of my memory.. my system has 4GB RAM and windows 10 Education

**Comment by mikeparker** [comment]
Docker Desktop linux VM requires 2GB free on boot by default, if you don't have enough free memory you can reduce the amount of memory it will use:
Check out %appdata%\Docker\settings.json and edit:
```
  "memoryMiB": 2048,
  "swapMiB": 1024,
```
Bear in mind using less than 2GB you probably won't be able to run kubernetes but docker will probably still work (provided you don't use lots of big containers).
