### ISSUE TITLE
Network failure cross 2 containers after period of no use. Only work around is to reinstall / repair doc for win.

### ISSUE THREAD

**Issue by garrardkitchen** [docker/for-win#534]
### Expected behavior

See a list of things on a page.

### Actual behavior

After a period away from page, on refresh, the list of things do not reappear.

### Information

Hacked together simple .net 4.5 app to render single web page in one container (f# mvc) and call out for list of things got from another container (web api f#).  

After I repair docker for windows it works again.

Diagnostic ID:  

```
D2A89C65-D2E1-497C-9A55-179FAA1770A2/2017-02-27_14-37-00
```

docker-compose (**docker-compose.windows.yaml**):

```
version: '3'
services:  

  web:
    # build:
    #    context: .
    #    dockerfile: Dockerfile
    image:
     garrardkitchen/web
    depends_on: 
      - api        
    ports:    
      - "8000"    
    links:
      - api
    networks:
      - backend
    #ports:

  api:
    # build:
    #    context: .
    #    dockerfile: Dockerfile.api   
    image:
     garrardkitchen/api
    expose:
      - "8080" 
    networks:
      - backend      

networks:
  backend:
    external:
      name: nat
```

web docker (**Dockerfile**):

```
FROM microsoft/aspnet
ARG site_root=app3
ADD ${site_root} /inetpub/wwwroot
EXPOSE 8000
```

api docker (**Dockerfile.api**):

```
FROM microsoft/aspnet
ARG site_root=api
ADD ${site_root} /inetpub/wwwroot
EXPOSE 8080
```

Host distribution and version (Windows version, build number, etc):
```
Docker version 1.13.1, build 092cba3
```

### Steps to reproduce the behavior

Fresh install (or repair) of docker for win:
  1. docker-compose --file .\docker-compose.windows.yml up -d
  2. docker inspect -f "{{ .NetworkSettings.Networks.nat.IPAddress }}" app3_web_1 <- get container ip
  3. Nav to container ip, to observe list of things

Failure:
After some time the internal DNS fails. This has also happened when laptop has been in sleep mode:
  1. Nav back to same ip address
  2. No things listed

You can access controller that calls out to api by using http://{container-ip}/mvcapi/cars.  You will see this when it fails:

```
error:The remote server returned an error: (403) Forbidden.
Response from http://api/cars:
<html>
<head>
  <title>403 Forbidden</title>
</head>
<body bgcolor="#ffffff">
  <h2>403 Forbidden</h2>
  <p></p>
</body>
</html>
```

To call API direct, establish container IP and use http://{container-ip}/cars.

Warmest regards,

Garrard.

**Comment by simonferquel** [comment]
This issue is related to the docker container engine (not Docker for Desktop).

Can you resubmit this on https://github.com/docker/docker/issues ? (please tag it as Windows related)
