### ISSUE TITLE
Docker protocol not available

### ISSUE THREAD

**Issue by jalaitin1** [docker/for-win#5341]
- [ x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x ] I have uploaded Diagnostics
  - Diagnostics ID: 88399B09-CF64-4CC6-9A4F-C1139D067464/20191218083259

### Expected behavior
Command 
$ ./gradlew jib --image=springio/gs-spring-boot-docker
executes successfully and deploys the example application to the Docker.

### Actual behavior
Command fails due to:
Container entrypoint set to [java, -cp, /app/resources:/app/classes:/app/libs/*, hello.Application]
I/O error for image [registry-1.docker.io/springio/gs-spring-boot-docker]:
    Socket Closed

### Information

  - Windows Version: 10 PRO
  - Docker Desktop Version: 2.1.0.5 (40693)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: NO

Example application https://spring.io/guides/gs/spring-boot-docker/

From the Git Bash:
$ DOCKER_HOST=unix:///var/run/docker.sock docker ps
protocol not available

### Steps to reproduce the behavior

Example application https://spring.io/guides/gs/spring-boot-docker/

0. $ docker login
Authenticating with existing credentials...
Login Succeeded

  1. $ ./gradlew jib --image=springio/gs-spring-boot-docker

Container entrypoint set to [java, -cp, /app/resources:/app/classes:/app/libs/*, hello.Application]
I/O error for image [registry-1.docker.io/springio/gs-spring-boot-docker]:
    Socket Closed
Executing tasks:
[=====================         ] 70.0% complete
> launching layer pushers
> pushing blob sha256:30a37d8ec94c5e5c9464e18e4...

> Task :jib FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jib'.
> com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException: Build image failed, perhaps you should make sure your credentials for 'registry-1.docker.io/springio/gs-spring-boot-docker' are set up correctly. See https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#what-should-i-do-when-the-registry-responds-with-unauthorized for help

2. $ DOCKER_HOST=unix:///var/run/docker.sock docker ps
protocol not available

**Comment by stephen-turner** [comment]
I'm not quite sure what you're trying to do here, but you seem to be using someone else's Linux example and expecting it to work on Docker Desktop for Windows. I don't see any evidence of a Docker Desktop problem here.
