### ISSUE TITLE
Encryption disabling is not an option nor SMB below 3

### ISSUE THREAD

**Issue by miroslavvojtus** [docker/for-win#5342]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

There is no need to:

1. reduce security by disabling encryption (suggested in #1637) 
1. reduce security by enabling SMB2 (suggested in https://forums.docker.com/t/volume-mounts-in-windows-does-not-work/10693/144)

### Actual behavior

In order to make Windows 10 sharing possible i had to:

1. Reduce security by disabling encryption (suggested in #1637)
1. Reduce security by enabling SMB2 (suggested in https://forums.docker.com/t/volume-mounts-in-windows-does-not-work/10693/144)
1. Enable SMB 1 client in optionalFeatures (sort of acceptable as it is only client)
1. Switch ethernet interface from Public to Private (suggested in https://stackoverflow.com/a/43904051) (sort of acceptable as it is private network, but due to corporate policy I have to exec the command after each restart)

### Information
This is standard setup on our corporate machines for Samba server:

```powershell
PS C:\WINDOWS\system32> Get-SmbServerConfiguration


AnnounceComment                 :
AnnounceServer                  : False
AsynchronousCredits             : 64
AuditSmb1Access                 : False
AutoDisconnectTimeout           : 15
AutoShareServer                 : True
AutoShareWorkstation            : True
CachedOpenLimit                 : 10
DurableHandleV2TimeoutInSeconds : 180
EnableAuthenticateUserSharing   : False
EnableDownlevelTimewarp         : False
EnableForcedLogoff              : True
EnableLeasing                   : True
EnableMultiChannel              : True
EnableOplocks                   : True
EnableSecuritySignature         : True
EnableSMB1Protocol              : False
EnableSMB2Protocol              : False
EnableStrictNameChecking        : True
EncryptData                     : True
IrpStackSize                    : 15
KeepAliveTime                   : 2
MaxChannelPerSession            : 32
MaxMpxCount                     : 50
MaxSessionPerConnection         : 16384
MaxThreadsPerQueue              : 20
MaxWorkItems                    : 1
NullSessionPipes                :
NullSessionShares               :
OplockBreakWait                 : 35
PendingClientTimeoutInSeconds   : 120
RejectUnencryptedAccess         : True
RequireSecuritySignature        : False
ServerHidden                    : True
Smb2CreditsMax                  : 2048
Smb2CreditsMin                  : 128
SmbServerNameHardeningLevel     : 0
TreatHostAsStableStorage        : False
ValidateAliasNotCircular        : True
ValidateShareScope              : True
ValidateShareScopeNotAliased    : True
ValidateTargetName              : True
```

### Steps to reproduce the behavior
1. any of:
    - Set the samba server as mentioned above
    - Disable SMB client 1 in options
    - `Set-NetConnectionProfile -interfacealias "vEthernet (DockerNAT)" -NetworkCategory Public` 
1. reset credentials in settings
1. restart docker desktop
1. attempt to share any drive in settings => various errors in logs depending on what you disable/enable

**Comment by stephen-turner** [comment]
@miroslavvojtus Please try the latest Edge build. We have moved away from Samba (and will be removing it from Stable soon).

**Comment by miroslavvojtus** [comment]
Thank you for the fast reply. I will try it. 👍
