### ISSUE TITLE
Docker crashes systematically on some pages of a symfony PHP app

### ISSUE THREAD

**Issue by lmartones** [docker/for-win#5343]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 5162D2B7-A42C-4490-B458-4220284C206C/20191217164936

### Expected behavior
No container crashes, page is rendered (or an error is raised).

### Actual behavior
Docker goes down when a PHP page is run. This happens for few specific pages, mostly when they fetch consistent data and do some compute with it. The PHP application has a memory limit set so that it doesnt cause the crash it self. 

There is no specific error on docker logs or container logs.

This works well on at least 7 other PCs with same specs. 

Docker for windows was reinstalled and the problem still persists. We have similar problem on another PC too.

We make several tests, most of them after a PC reboot and a docker factory reset (or at least `docker-compose down`). 

### Information

  - Windows Version: Windows 10 professionnal, version : 10.0.17763 n° 17763
  - Docker Desktop Version: 19.03.5, build 633a0ea
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no, basic windows + hyper V

### Steps to reproduce the behavior

  1. Start docker and `docker-compose up -d` project
  2. Run a specific PHP page
  3. After few minutes docker wont answer and all containers go down

**Comment by mikeparker** [comment]
Have you tried the edge build?
https://docs.docker.com/docker-for-windows/edge-release-notes/

**Comment by lmartones** [comment]
Hi Mike, sorry for my late answer.

Yes we tester Edge without much more success. Are there some specific diagnosis steps we could try to do ?
