### ISSUE TITLE
Windows 10 Enterprise 1607.14393 - (element not found problem in powershell)

### ISSUE THREAD

**Issue by PetrShypila** [docker/for-win#536]
### Expected behavior

Docker starts after installation
Installed on Windows 10 Enterprise. Previously had installed VirtualBox and Vagrant.

### Actual behavior

Error occurs before starting

### Information

  - Diagnostic ID: 93711B56-2D58-46A7-B210-E8EA0428A991/2017-02-28_14-18-26 
  - Download latest version of Docker from website
  - page URL if this is a docs issue or the name of a man page
  - OS: Windows 10 Enterprise
  - Edition: Enterprise
  - Id: 1607
  - Build: 14393

### Steps to reproduce the behavior

  1. Install Docker
  2. Launch after installation
  3. Docker crashes on start with error

**Comment by simonferquel** [comment]
This issue has been fixed in the latest stable version of Docker for Windows (1.13.1). Can you update ?

**Comment by PetrShypila** [comment]
Unfortunately I don't have this laptop anymore. Beside issue with docker it has problems with windows update and some other issues. IT department already replaced it with new one.

However, yesterday docker was up to date. So I am not sure that it could possibly fix issue. Most likely there was problems with Windows.
