### ISSUE TITLE
failed to run docker desktop in linux containers mode

### ISSUE THREAD

**Issue by kmursk** [docker/for-win#5366]
I've installed Docker Desktop v2.1.0.5 on Windows Pro 10 (release 1909), but it can not run in mode for linux containers.  I have uploaded Diagnostics. ID is: D3A16E9F-7321-401C-8DD9-70B71315081B/20191222233953

### Expected behavior
Mode for linux containers is supported by application.
### Actual behavior
Application crashes with error.
"Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Failed to create a new virtual machine.
'DockerDesktopVM' failed to realize. (Virtual machine ID AE15BAC7-73A3-4BE8-9F4B-2EA85E4D5743)
Failed to access configuration store: The system cannot find the path specified. (0x80070003).
   в Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   в Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   в Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   в Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()"
### Information
  - Windows Version: 10 (build 1909)
  - Docker Desktop Version: 2.1.0.5
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

**Comment by PavelSosin-320** [comment]
I can't switch from Windows containers back to linux containers with DockerDesktop 2.1.7 CE too - there is no such option ????
I'm running Docker Desktop with WSL 2.0 Ubuntu and Kubernetes orchestration
It worked until recently and I was even able to connect to my Cluster both from Windows CMD and Linux BASH and deploy a lot of stuff like NGINX ingress.
In the current version both Container type switch and Resource management disapeared :(

**Comment by mat007** [comment]
There isn’t as much Resource management options in Windows containers and WSL 2 because they mostly for configuring the LinuxVM used only in Linux non WSL 2 containers.

What do you mean by no option to switch to Linux containers?
Don’t you have the following entry in the menu?

![image](https://user-images.githubusercontent.com/2386884/71412268-43cbfa00-264d-11ea-8e7a-12ad23b7592f.png)

**Comment by PavelSosin-320** [comment]
Sorry, Now I see that this menu item works in flip/flop mode but I didn't find its behaviour description in documentation. But something is missed in UI anyway - in which mode Kubernetes works currently - Linux or Windows mode? I deployed several charts using Helm 3 and no of them was Windows containers. Of couse, this information is not kept in Kubernetes itself, neither helm list doesn't show it. But it is so special feature of Docker Desktop for Windows that this information has to be dispayed somewhere

**Comment by kmursk** [comment]
I've solved this case. The reason is Hyper-V's behavior. Meaningful message in log was "Storage is unavailable". It happens when Hyper-V can not create virtual machine. In its turn this trouble occurs when Hyper-V's option default directory for virtual machines is set. In my case it was external hdd. If external hdd is disconnected, Hyper-V won't execute commands to create virtual machine. The problem could be more obvious if Hyper-V logged the path it finds, but error message is extreamly brief and confusing. In its turn Docker desktop doesn't check if Hyper-V is able to start DockerDesktopVM. It would be nice, if in future versions there would be such check and logging, cause in "linux containers" mode Docker Desktop directly depends on Hyper-V and DockerDesktopVM's health.
