### ISSUE TITLE
Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows

### ISSUE THREAD

**Issue by Neelerak** [docker/for-win#537]
**Resubmitting:**
https://github.com/docker/for-win/issues/422

This issue was a problem with Go and should be resolved as of 14 days ago, any chance to get a hotfix?

https://github.com/golang/go/issues/16736

**Comment by simonferquel** [comment]
As @dgageot said, the Docker cli / engine are not build by the Docker for Desktop team. Could you please resubmit the issue on https://github.com/docker/docker/issues?
