### ISSUE TITLE
Unable to use GUI after upgrade to 2.1.7.0, cli works fine

### ISSUE THREAD

**Issue by marwatk** [docker/for-win#5376]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3DEDD9D6-5E87-4BE9-A05C-89744FFEF0E1/20191226170945

### Expected behavior
Able to view version in Docker -> About Docker Desktop
Able to adjust settings in Docker -> Settings
Able to run diagnostics from GUI
Able to reset docker in Troubleshooting

### Actual behavior

About Docker Desktop dialog shows but all fields are blank
Settings window continuously spins with "Docker _updating_" in the status bar
Reset/Run Diagnostics both clickable but don't do anything

### Information

  - Is it reproducible? Yes
  - Is the problem new? Yes
  - Did the problem appear with an update? Yes
  - Windows Version: Win 10 Enterprise 1809 (17763.914)
  - Docker Desktop Version: 2.1.7.0 and 2.2.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

I attempted to switch to Edge via the GUI but the installer would always just disappear without completing the upgrade. No errors presented. I downloaded the Edge installer and it successfully upgraded to Edge release. After the upgrade, however, I'm unable to view the GUI at all. I tried clearing my `%USERPROFILE%\.docker` folder but experienced the same behavior. I'm able to _use_ docker from the CLI just fine, I just can't use the GUI to adjust settings or perform any actions.

**Comment by mat007** [comment]
Maybe similar to #5326, can you check if you have any environment variable defined which starts with `DOCKER_` possibly `DOCKER_CERT_PATH` pointing to a non-existing location?

**Comment by marwatk** [comment]
Nope, no environment variables defined that start with `DOCKER` at all.

**Comment by mat007** [comment]
Would you mind installing this internal build https://download-stage.docker.com/win/edge/41684/Docker%20Desktop%20Installer.exe which adds some logging in case of error when populating the menu?
After triggering the Settings for instance can you look in `%LOCALAPPDATA%\Docker\log.txt` to see if you have any error being logged near the end of the file?

**Comment by marwatk** [comment]
Here's the log. I clicked on the settings menu at `[08:41:09.670][SegmentApi        ][Info   ] Usage statistic: actionMenuSettings`. Let me know if I can provide anything else.

[log - Copy.txt](https://github.com/docker/for-win/files/4010224/log.-.Copy.txt)

**Comment by twistezo** [comment]
I have the same problem as author.

- Windows 10 Pro 2004 build 19041.1 (slow ring) 
- WSL 2. 

I'm using `Enable the experimental WSL 2 based engine` option.

#### Temporarily solution for install working latest version
1. Remove Docker with its remains and restart system. Note that without removing these remains or without system restart the next fresh install will have the same loop with "Docker updating" at down-left corner of Docker GUI. 
2. Install Desktop Edge 2.1.7.0.
3. Don't exit Docker. After this you will have looped updating info and Docker will be working only on Windows side, not under WSL. I checked what with go to sleep when using laptop, and after sleep Docker works fine. Also tried to uncheck option "Automatically check for updates" but without success.

Remains:
```
C:\Program Files\Docker
C:\ProgramData\DockerDesktop
C:\Users\[USERNAME]\.docker
C:\Users\[USERNAME]\AppData\Local\Docker
C:\Users\[USERNAME]\AppData\Roaming\Docker
C:\Users\[USERNAME]\AppData\Roaming\Docker Desktop
```

**Comment by marwatk** [comment]
FWIW the issue persists in 2.2.0.0.

**Comment by bbomgardner** [comment]
I have this same issue. Before when the new settings UI was in Edge, now with 2.2.0.0.

Clearing the paths listed by @twistezo did not seem to work for me. I have also followed [these steps](https://success.docker.com/article/how-to-completely-remove-docker-in-windows-10) but I'm still missing _something_ when performing the uninstall or there is another problem with my machine that I have yet to find.

```
❯ tail -1 $env:localappdata/docker/log.txt
[16:58:33.269][SegmentApi        ][Info   ] Usage statistic: actionMenuSettings

❯ cat  $env:localappdata/docker/log.txt | grep -iE "err|fail"
[16:30:11.319][PowerShell        ][Info   ] Run script with parameters: -Stop True -VmName DockerDesktopVM -SwitchName DockerNAT -Verbose True -ErrorAction Stop
[16:30:15.015][PowerShell        ][Info   ] Run script with parameters: -Create True -VmName DockerDesktopVM -VhdPathOverride C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx -VhdSize 68719476736 -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 28 -PreferredIPAddress  -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\resources\docker-desktop.iso -SwitchName  -Verbose True -ErrorAction Stop
[16:30:21.775][PowerShell        ][Info   ] Run script with parameters: -Start True -VmName DockerDesktopVM -IsoFile C:\Program Files\Docker\Docker\resources\docker-desktop.iso -confIsoFile C:\ProgramData\DockerDesktop\tmp-d4w\config.iso -VhdPathOverride C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx -DockerIsoFile C:\Program Files\Docker\Docker\resources\docker.iso -Verbose True -ErrorAction Stop
[16:30:22.034][VpnKit            ][Error  ] vpnkit.exe: Starting to watch : EINVAL
[16:30:22.034][VpnKit            ][Error  ] vpnkit.exe: Failed to watch hosts file : invalid argument
[16:30:22.034][VpnKit            ][Error  ] vpnkit.exe: While watching /etc/resolv.conf: ENOENT
Binary file (standard input) matches
```

**Comment by twistezo** [comment]
@bbomgardner check https://github.com/microsoft/WSL/issues/4321#issuecomment-573351391

**Comment by marwatk** [comment]
I'm still using WSL 1 (on 1809), so I don't think it's necessarily WSL related.

**Comment by marwatk** [comment]
I broke down and tried twistezo's steps and still have the issue after a wipe/reboot/fresh install.

**Comment by bbomgardner** [comment]
As a note, I am unable to perform any action within the menu (including diagnostics /reset) with this issue. What is the correct way to generate a diagnostics upload + ID from the CLI?

![2020-01-21_19-15-23](https://user-images.githubusercontent.com/17881317/72854508-95829700-3c82-11ea-87d5-0eba958ff3f1.gif)

**Comment by simonferquel** [comment]
@marwatk I had a look at your logs and have a better understanding of what is happening. The backend actually runs just fine, but for some reason, the UI fails to connect to the internal docker desktop API.
The bad news, is that we have currently no idea why it could not connect. Do you have per-any chance a 3rd party antivirus or something that may block named-pipe connections ?

**Comment by marwatk** [comment]
@simonferquel The answer is all them... all the antivirus. Carbon Black (though in report-only mode), Symantec Endpoint protection (but disabling doesn't help), and Global Protect VPN that blocks split tunneling. And I'm sure a few I'm unaware of.

This only started happening with the latest GUI, however. I was running just fine before that. And if I manually update settings.json I can _use_ docker just fine (including the new shared folders), doesn't that communicate over named pipes, too?

But I have a coworker running the a similar build (he's on Cisco AnyConnect and 1709, but the same rules apply with split tunneling) and he's had no issues.

**Comment by simonferquel** [comment]
The old UI was running in the same process as the systray and did not use named pipe connections. The new one does. I wonder if one of the antivirus somehow changes default namedpipe access rights (I don't know if it is even possible, and I can't find how it could be a good idea)

**Comment by bbomgardner** [comment]
AV would probably make the most sense? My coworker is also experiencing this exact issue with 2.2.0.0 and we both are running ESET Endpoint Security 6.5.2118.0 on 1809. VPN is Junos Pulse and I believe split-tunneling is enabled. I will discuss this with our network and security team tomorrow and report back what we find out.

**Comment by twistezo** [comment]
Anti-virus or firewall are not the cause because I had this problem using only built-in Windows 10. The weird thing is that the problem itself disappeared after cleaning and reinstalling Docker the third or fourth time.

**Comment by gillesdouaire** [comment]
blocked on the same issue...

**Comment by gillesdouaire** [comment]
I reported the issue MONTHS ago, of course, no one worked on it. https://github.com/docker/for-win/issues/4351

**Comment by acheaito** [comment]
Blocked on the same issue as well. We’re on Windows 10 Enterprise Build 1809.

**Comment by twistezo** [comment]
I found cause and solution. It's weird but when you open Docker Desktop from Windows taskbar where you usually pin its it goes to updating loop. But when you run it from Windows Search (win + S) it will run normally and its icon goes to Windows notification bar 😄

**Comment by mikeparker** [comment]
Docker Desktop is more than just the front end executable. If you pin the front end executable it won't start the back end. Please make sure if you pin Docker Desktop to your taskbar, you're pinning the boot sequence executable `C:\Program Files\Docker\Docker\Docker Desktop.exe` NOT the front end `C:\Program Files\Docker\Docker\frontend\Docker Desktop.exe`

**Comment by simonferquel** [comment]
Wow @twistezo I never thought anyone would do that ! thanks for the heads up.

**Comment by gillesdouaire** [comment]
Unfortunately, running Docker Desktop from Windows Search (win + S) does not solve it for me.

**Comment by twistezo** [comment]
@gillesdouaire like @mikeparker said, run Docker from `C:\Program Files\Docker\Docker\Docker Desktop.exe`

**Comment by gillesdouaire** [comment]
Yes, that's what I did, unfortunately does not work, still have the infinite updating spinner on the UI

**Comment by acheaito** [comment]
Same. The workaround didn't work for me either.

**Comment by marwatk** [comment]
Workaround did not work for me either.

**Comment by Antiavanti** [comment]
The same issue, version 2.2.0.0. I downgraded to 2.1.0.5 😢 
Workaround is not applicable, docker was already started from the right `Docker Desktop.exe`.

**Comment by twistezo** [comment]
Maybe you guys have running any Docker app or Docker service in background?

**Comment by mat007** [comment]
@twistezo the OP reported that the command line works fine, so the application must be running correctly. There is definitely something else going on there.

**Comment by gillesdouaire** [comment]
for me, it's finally fixed with 2.2.0.3 (42716) - stable

**Comment by bbomgardner** [comment]
Same. Looks like 2.2.0.3 fixed it. ¯\_(ツ)_/¯

**Comment by gillesdouaire** [comment]
On edge channel, 2.2.1.0 also fixes it.

**Comment by acheaito** [comment]
Same. 2.2.1.0 edge fixed it. Haven't tried stable.

**Comment by mat007** [comment]
Stable 2.2.0.3 and Edge 2.2.1.0 have basically the content, so either should fix it.
I’ll go ahead and close this issue then, thanks!

**Comment by darron1217** [comment]
@mat007 
Workaround did not work for me either. (on 2.3.0.2)
Would you reopen this issue?

**Comment by mat007** [comment]
@darron1217 can you please open a fresh ticket with diagnostics if possible?
