### ISSUE TITLE
error after installing docker desktop

### ISSUE THREAD

**Issue by mtnnova** [docker/for-win#5399]
![docker error](https://user-images.githubusercontent.com/59383870/71611513-f272bc00-2bb2-11ea-90ab-4a46e73a33a6.PNG)

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ulrich** [comment]
Quickly, it seems you have a software protection activated which avoid to run the Docker daemon. Windows daemon send 0xC004F074 error in the logs.
