### ISSUE TITLE
Docker does not pull images (manifest for image not found)

### ISSUE THREAD

**Issue by vvsh** [docker/for-win#540]
### Expected behavior

docker successfully pulls image

### Actual behavior

docker pull nginx:latest
manifest for nginx:latest not found

The same for other images (busybox, postgres:latest and other).

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
D2ABE1B2-6047-49A1-8F6A-955B9E70EA97/2017-02-28_22-03-35
  - host distribution and version (Windows version, build number, etc)
Windows 10 Enterprise (10.0.14393)

### Steps to reproduce the behavior

  1. Download latest version of Docker for Windows (stable)
  2. execute docker pull nginx:latest

**Comment by justincormack** [comment]
AWS S3 is down in US East and this is affecting Docker Hub.

**Comment by justincormack** [comment]
See http://status.docker.com/ for updates

**Comment by vvsh** [comment]
I was expecting that this is the reason because a few hours ago everything worked.

**Comment by vvsh** [comment]
@justincormack, do they have deployments/replicas in other regions?

**Comment by justincormack** [comment]
@vvsh it seems not at present.
