### ISSUE TITLE
Docker for windows not pulling packages in windows 10

### ISSUE THREAD

**Issue by FryDerm** [docker/for-win#541]
### Expected behavior
Be able to pull packages from docker hub.

### Actual behavior
Getting an error: manifest for [package name] not found.

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
D1E22011-E3D3-4F30-B94F-6E87AD2AF24C/2017-02-28_14-28-13

  - a reproducible case if this is a bug, Dockerfiles FTW
docker pull microsoft/aspnetcore:latest

  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

1. Open powershell
2. Run the command docker pull microsoft/aspnetcore:latest
3. After a few minutes the following error is returned: manifest for microsoft/aspnetcore:latest not found.

**Comment by FryDerm** [comment]
It appears this is related to an outage in the registry service as reported here. I will close the issue and will monitor the service instead.

https://github.com/ethcore/parity/issues/4503#issuecomment-283138221

**Comment by Protoje** [comment]
May I ask if this Issue has a Solution already? Can't find any helpful thread and the Link you posted above doesn't work for me. 
Got that issue while trying to download Ansible through Kitematic itsself and also through the Kitematic shell.

**Comment by friism** [comment]
@Protoje Can you please open a separate issue with details and diagnostics specific to your problem?
