### ISSUE TITLE
Kubernetes stays starting...

### ISSUE THREAD

**Issue by mscottreed** [docker/for-win#5412]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: D9235141-C9D2-4E8C-96E2-6BD844125CE6/20200103162539

### Expected behavior
Kubernetes starts successfully

### Actual behavior
Kubernetes stays stuck in starting...

### Information
Many people have reported this problem, but most seem resolved by simple things I have already tried (like removing .kube folder or adding firewall rules).  It has to be something related to this machine (which is somewhat locked down and using a VPN to connect), it works fine on my other machines.

  - Windows Version: Windows 10 Version 1809 (OS Build 17763.914)
  - Docker Desktop Version: 2.1.0.5 (40693)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no, on physical laptop

### Steps to reproduce the behavior
Install Docker for Windows
1) Enable sharing of C drive
2) Enable Kubernetes
Expect Kubernetes to start successfully.

**Comment by Fingalzzz** [comment]
Same issue here, Diagnosis ID: 3B592D70-E28B-4A9E-95B7-9F6524B9F3D9/20200117022940.

**Comment by cyclump** [comment]
I work behind a corporate proxy.  With 2.1.x.x we needed to add the `docker.internal` to the bypass proxy setting in the Docker GUI to have the UI acknowledge the successful download and installation of kubernetes.  Some folks added `internal` and others added `docker.internal` and it solved a lot of problems for us.

Hope this helps!
