### ISSUE TITLE
Get https://registry-1.docker.io/v2/: net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by itman-lrf** [docker/for-win#5414]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mat007** [comment]
Maybe similar to #5386 ?

**Comment by rohmanhm** [comment]
It fixes my issue.
https://github.com/docker/kitematic/issues/1125#issuecomment-269751446
