### ISSUE TITLE
Build arguments don't work

### ISSUE THREAD

**Issue by sjuberman** [docker/for-win#542]
### Information
I'm running Docker For Windows set to Windows Containers and I'm trying to build a dockerfile that uses the ARG keyword. 

Example dockerfile:

> FROM microsoft/windowsservercore:10.0.14393.447
ARG stuff=otherstuff
RUN echo $stuff

Diagnostic ID: 768E3F98-6C7F-49D0-96E3-098EE2E6F37F/2017-03-01_11-03-56
Windows 10 Build 14393.693
Docker for Windows Version 1.13.1 (10072) Beta Channel

### Expected behavior
If i run `docker build --build-arg stuff=somestuff .` the argument in the dockerfile should be overwritten and echoed.

### Actual behavior
Arguments don't work at all in Dockerfiles when running Windows Containers. Neither the set value in the dockerfile nor the value sent in to the build command is echoed.

### Steps to reproduce the behavior

  1. Set Docker for Windows to Windows Containers
  2. Copy above dockerfile
  3. run `docker build --build-arg stuff=somestuff .`
  4. Notice that the values from the build argument is not echoed

**Comment by simonferquel** [comment]
Your RUN command is incorrect. On windows default shell (cmd), you reference en variables with %stuff%

**Comment by sjuberman** [comment]
@simonferquel Alrighty, that works. The documentation(https://docs.docker.com/engine/reference/builder/) is not really clear on that you need to to use the environment variable syntax for the shell that your are using. Thanks for your clarification.

**Comment by johngrabner** [comment]
What is the syntax for yaml file to specify a build parameter?

I am trying to get  my images to build using a private npm package.

Windows command prompt, I can display the env variable as follows:
```
> echo %NPM_TOKEN%
a129e5de-xxxxxxxxxx
```
The yaml file should create a build paramer (per documentation).  
```
version: '3.1' 
services: 
  eui_to_cluster_api: 
    build: 
        context: .
        dockerfile: Dockerfile_eui_to_cluster_api.Dockerfile
        args:
          - NPM_TOKEN
```

The dockerfile as per the above suggestion
```
FROM node:10
ARG NPM_TOKEN  
RUN echo "Oh dang look at that read only token %NPM_TOKEN%"
COPY ./eui_to_cluster_api/.npmrc ./
```

And finally the .npmrc contains
//registry.npmjs.org/:_authToken=${NPM_TOKEN}
