### ISSUE TITLE
6FF6B348-E253-4C64-91F7-EACF6865D2C6/20200107120430

### ISSUE THREAD

**Issue by lsvvcc** [docker/for-win#5426]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ulrich** [comment]
More informations?
