### ISSUE TITLE
Unable to create volume correctly. Data we create in container is not showing up in the volume

### ISSUE THREAD

**Issue by MusarratNawaz** [docker/for-win#544]
### Expected behavior

Volumes must be shared among multiple containers

### Actual behavior
Volumes command are working fine but no files in the folder.so we are unable to share among multiple containers
### Information

Problem statement
Unable to create volume correctly. Data we create in container is not showing up in the volume

Environment Information
Host details
•	Windows 10
•	Pro edition
•	Updated with latest version released in Jan 2017 (including anniversary update)
Docker version

PS C:\WINDOWS\system32> docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      windows/amd64
 Experimental: true
PS C:\WINDOWS\system32>

Docker Info
PS C:\WINDOWS\system32> docker info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.13.1
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 14393 (14393.693.amd64fre.rs1_release.161220-1747)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 15.91 GiB
Name: CRLHW-PSDT12
ID: NNNW:AZJC:KR3L:WLKM:IIVI:QMBI:RZEG:KONQ:GRN4:ZZEN:M4WT:LFQF
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 23
 System Time: 2017-03-01T18:45:18.9399541+05:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
PS C:\WINDOWS\system32>

Steps followed to create container & volume
•	Pulled docker image “Microsoft/mssql-server-windows” (https://hub.docker.com/r/microsoft/mssql-server-windows/)

•	Created a volume (image docker file does not mention creation of a volume)
Docker volume create m5volume

•	Create a container using created volume
docker run -d -p 1433:1433 --name volumeTest -e sa_password=PassW0rd! -e ACCEPT_EULA=Y -v m5volume:C:\Volume -e attach_dbs="[{'dbName':'SampleDb','dbFiles':[C:\Volume microsoft\\mssql-server-windows\\,'C:\Volume microsoft\\mssql-server-windows\\sampledb_log. ldf']}]" microsoft/mssql-server-windows

o	Volume we created on docker 
o	Volume we want to create on our host, for sharing the data with other docker engines

•	Get IP address of the container and connect it through SSMS

•	reate a new DB with some tables in it

•	Go back to the volume folders, there should be files created corresponding to the new DB created
o	No files are seen in the m5volume (in the docker engine) or at C:\Volume (on the host).

•	If we stop and remove ‘rm’ the container, recreate a VM and attach the same volume, the data is lost 

Diagnostics
Is volume created correctly
PS C:\WINDOWS\system32> docker volume ls
DRIVER              VOLUME NAME
local               dockerm5volume
local               m5volume
PS C:\WINDOWS\system32>

Is container created correctly
PS C:\WINDOWS\system32> docker ps -a
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS                       PORTS                    NAMES
b15413c46b19        microsoft/mssql-server-windows   "cmd /S /C 'powers..."   4 days ago          Exited (1067) 25 hours ago                            condescending_bassi
d6065fa7a84d        microsoft/mssql-server-windows   "cmd /S /C 'powers..."   6 days ago          Up 25 hours                  0.0.0.0:1433->1433/tcp   m5

Is container using specified volumes
Docker inspect m5
C:\WINDOWS\system32>docker inspect m5
[
    {
        "Id": "d6065fa7a84d923ff2904c1e3d99d90a7e57e85da62c823df22f5fff5072fb20",
        "Created": "2017-02-23T10:18:52.6258039Z",
        "Path": "cmd",
        "Args": [
            "/S",
            "/C",
            "powershell ./start -sa_password %sa_password% -ACCEPT_EULA %ACCEPT_EULA% -attach_dbs \\\"%attach_dbs%\\\" -Verbose"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 1924,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2017-02-28T12:22:27.1440356Z",
            "FinishedAt": "2017-02-24T09:52:28.38032Z"
        },
        "Image": "sha256:6fb5a1dbd3c8a7378644bf173f766d0913c9f57d4cf3fc7068050594392b34aa",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "LogPath": "C:\\ProgramData\\Docker\\containers\\d6065fa7a84d923ff2904c1e3d99d90a7e57e85da62c823df22f5fff5072fb20\\d6065fa7a84d923ff2904c1e3d99d90a7e57e85da62c823df22f5fff5072fb20-json.log",
        "Name": "/m5",
        "RestartCount": 0,
        "Driver": "windowsfilter",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "C:\\ProgramData\\Docker\\volumes\\m5volume:C:\\Volume"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "1433/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "1433"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 0,
            "ConsoleSize": [
                44,
                168
            ],
            "Isolation": "hyperv",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Name": "windowsfilter",
            "Data": {
                "dir": "C:\\ProgramData\\Docker\\windowsfilter\\d6065fa7a84d923ff2904c1e3d99d90a7e57e85da62c823df22f5fff5072fb20"
            }
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "c:\\programdata\\docker\\volumes\\m5volume",
                "Destination": "c:\\volume",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "d6065fa7a84d",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "1433/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "sa_password=PassW0rd!",
                "ACCEPT_EULA=Y",
                "attach_dbs=[]"
            ],
            "Cmd": [
                "cmd",
                "/S",
                "/C",
                "powershell ./start -sa_password %sa_password% -ACCEPT_EULA %ACCEPT_EULA% -attach_dbs \\\"%attach_dbs%\\\" -Verbose"
            ],
            "ArgsEscaped": true,
            "Image": "microsoft/mssql-server-windows",
            "Volumes": null,
            "WorkingDir": "C:\\",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "49a4cb2a3bb3c0536562e20b886c26293d39f103323b0c040287be0280fb8bbb",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "1433/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "1433"
                    }
                ]
            },
            "SandboxKey": "49a4cb2a3bb3",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "nat": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "98730690738d4e796564d46cbaff1f341fb6de163497fee0ba6f186763671d88",
                    "EndpointID": "2249a429fc1f1069f08f48b26cdb506155341c1fd36b62e1483868eaf5648a03",
                    "Gateway": "172.25.160.1",
                    "IPAddress": "172.25.171.18",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "00:15:5d:58:a1:ca"
                }
            }
        }
    }
]

Are folders created 
Volumes folders appearing. But there isn’t any file in the folder

As per Docker documentation that there must be a file.

Other run commands tried
docker run -d -p 1433:1433 --name volumeTest -e sa_password=PassW0rd! -e ACCEPT_EULA=Y -v m5volume:C:\Volume -e attach_dbs="[{'dbName':'SampleDb','dbFiles':[C:\Volume microsoft\\mssql-server-windows\\,'C:\Volume microsoft\\mssql-server

Same result, nothing appears in the folders when creating a DB

**Comment by simonferquel** [comment]
You are mounting the volume in `C:\Volume` but attaching db files from `c:\Volume microsoft`. does not seem correct to me.

**Comment by MusarratNawaz** [comment]
Hi Simon
microsoft\mssql-server-windows this is the image name.We had also used these commands

docker run  --name volumeTest  -v C:\Volume -d -p 1433:1433 -e sa_password=PassW0rd!-e ACCEPT_EULA=Y microsoft\mssql-server-windows


docker run -d -p 1433:1433 --name volumeTest -–isolation=hyperv -v C:\Volume:C:\ProgramData\Docker\volumes -e sa_password=PassW0rd! -e ACCEPT_EULA=Y microsoft/microsoft\mssql-server-windows
