### ISSUE TITLE
Docker locks files in Symfony Development Environment (Webpack)

### ISSUE THREAD

**Issue by gmuehl** [docker/for-win#5440]
I have dockerized my Symfony Development, everything works very good as long as i don't use Symfony Encore. I have found several Tickets regarding Docker locking files, but not really a solution.

**This Works:**

```
docker-compose up -d
yarn run encore production
```

Now i can run `yarn run encore production` as often as i want, it will work every time!

Next I open http://localhost in a Browser, everything works, the CSS Webpack has created is delivered without any errors.

Now i run `yarn run encore production` again and it fails. It can't empty the build-Directory. There are some files now that can't be deleted (Webpack comes up with error -4051). I can't delete the files in Windows, i can't delete the files directly within the Container. The Files have correct Ownerships, and correct permissions. But they are not deletable. I used :cached on the mounted Volume, and i tried it without :cached

I can solve this issue with running `docker-compose down` followed by `docker-compose up`.
I can run `yarn run encore production` now (once) after it fails again when i access http://localhost with the browser.

So, what is wrong? Permissions are ok, Ownership is ok, the Container did not even modify the files that can't be deleted, it just delivers them. Fun fact: i only have this Problem with the generated Webpack files, i can read / write / delete all other files without any problems! My guess would be that it could be something with the Public-Dir of the Webserver, and Caching of the Webserver.

**Comment by gmuehl** [comment]
My Docker-Config for Symfony: https://github.com/gmuehl/docker-symfony

**Comment by mat007** [comment]
Thanks for the report, I know this was some time ago but do you remember what Docker Desktop version you were running?
Did you try with a recent one? If you’re still experiencing the problem could you upload diagnostics (Troubleshoot window from the systray menu) and quote the ID here please?
Thanks!

**Comment by gmuehl** [comment]
This were three Releases ago when there were general Problems with mounting Drives, haven't ist tested wit the newer Versions so far
