### ISSUE TITLE
Kubernetes is stuck on starting after enabling it on Docker for Windows 10

### ISSUE THREAD

**Issue by MobyWare** [docker/for-win#5442]
### Expected behavior
Kubernetes cluster should start

### Actual behavior
Kubernetes keeps indicating that it is starting

### Information
Running docker for windows 10, with docker version Docker version 19.03.5, build 633a0ea. I enabled Kubernetes and it is just stuck on starting.

Diagnosis ID: 5116C6F1-8254-4923-AF0E-92AA9E24A01D

### Steps to reproduce the behavior
1. Open Docker settings
2. Click enable on the kubernetes tab

**Comment by ulrich** [comment]
Can you resend diagnostic? Yours is not found in the db.

Thank you.

**Comment by MobyWare** [comment]
> Can you resend diagnostic? Yours is not found in the db.
> 
> Thank you.

I just uploaded again and got the ID - 5116C6F1-8254-4923-AF0E-92AA9E24A01D/20200109130358

**Comment by ulrich** [comment]
Can you confirme that you have the **docker-desktop** context activated?

**Comment by MobyWare** [comment]
> Can you confirme that you have the **docker-desktop** context activated?

I believe so. I ensured via the UI (see screenshot) and the CLI.

![docker_desktop_context](https://user-images.githubusercontent.com/5482510/72165895-3f664780-3396-11ea-84f0-040b410800d0.png)

**Comment by Fingalzzz** [comment]
Same issue here, Diagnosis ID: 3B592D70-E28B-4A9E-95B7-9F6524B9F3D9/20200117022940.

**Comment by zhangzerui20** [comment]
In my cases, docker ps can't find Kubernetes's images, and logs is :
`[Error  ] time="2020-01-20T09:48:30+08:00" msg="Cannot list nodes: Get https://kubernetes.docker.internal:6443/api/v1/nodes: EOF"`

I've tried `rm pki` and `rm .kube`, but that didn't work.
 
In the end I found that my problem was that kubernetes couldn't get the image he needed, and this article finally solved my problem.

https://github.com/AliyunContainerService/k8s-for-docker-desktop/blob/master/README_en.md

**Comment by Lanpice** [comment]
Same issue. 
Diagnosis ID: E232DD58-7CB3-4DFA-BD9A-21E322AFFC7C/20200303035825

**Comment by mikhey** [comment]
I've been having trouble with this too with v2.2.0.3 stable, it's stuck in starting phase and never gets passed it.

Windows 10 1809 (Build 17763.1039)
Docker: 2.2.03 (42716)
Engine: 19.03.05, 
k8s 1.15.5.  

I have done the following with reboots in between: 
- Uninstalled Docker
- Uninstalled Hyper-V, 
- Disabled Hyper-V hypervisor (bcedit)
- Enabled Hyper-V hypervisor
- Installed Hyper-V
- Installed Docker

In addition to all that I have:
- Set the `KUBECONFIG` machine environment variable
- Configured docker to use the DNS of 8.8.8.8
- Deleted:
    - `%USERPROFILE%\.kube\`
    - `%PROGRAMDATA%\DockerDesktop\`
    - `%APPDATA%\Docker\`

Every time it just stalls... I see some 503 errors in the `%APPDATA%\Docker\log\vm\kubelet.log` scroll by as I'm watching it.

I wonder if it could be a network configuration at the office that's causing this or something much bigger - there seems to be a lot of issues out there regarding this...

I have followed all of these issues below and attempted the resolutions and I'm still coming up empty handed

- #5222 
- #4924  
- #4519 
- #4185
- #1649
- #4316
- #1962

**Comment by 6r6** [comment]
Hi there, my windows and docker version are almost same as @mikhey ，and I have tried everything I can find in other issues ， please kindly review my diagnosis file , thank you !

Diagnosis ID: EF375BA0-8590-4213-B989-3DB2D03F8517/20200311143150

```
C:\Users\peter>docker ps
CONTAINER ID        IMAGE                  COMMAND             CREATED             STATUS              PORTS               NAMES
9e3214b75309        k8s.gcr.io/pause:3.1   "/pause"            9 minutes ago       Up 9 minutes                            k8s_POD_kube-scheduler-docker-desktop_kube-system_131c3f63daec7c0750818f64a2f75d20_0
1a9b63b1a731        k8s.gcr.io/pause:3.1   "/pause"            9 minutes ago       Up 9 minutes                            k8s_POD_kube-controller-manager-docker-desktop_kube-system_b2850863d2a1ddaac8ed962e6881584c_0
3a52b4163d8c        k8s.gcr.io/pause:3.1   "/pause"            9 minutes ago       Up 9 minutes                            k8s_POD_kube-apiserver-docker-desktop_kube-system_556b996466155d7ad37d896897208f67_0
2eb177cc3d67        k8s.gcr.io/pause:3.1   "/pause"            9 minutes ago       Up 9 minutes                            k8s_POD_etcd-docker-desktop_kube-system_f132e1c85abd4953a304d1c65d9d74f9_0
```
