### ISSUE TITLE
WSL2 cannot Access Docker Daemon at unix:///var/run/docker.sock

### ISSUE THREAD

**Issue by ayashkantha** [docker/for-win#5446]
Docker desktop backend version is v19.03.5
Docker cli version on ubuntu is 19.03.3, build a872fc2f86
Ubuntu version running on wsl2 is Ubuntu 19.10

Docker cannot see the the windows deamon. I have enabled wsl intergration -> ubuntu. But when I do `docker context ls` on powershell output is like below,

```
NAME                DESCRIPTION                               DOCKER ENDPOINT                  KUBERNETES ENDPOINT   ORCHESTRATOR
default *           Current DOCKER_HOST based configuration   npipe:////./pipe/docker_engine                         swarm
```

Why it doesn't show the wsl endpoint there? How can I debug this further?

**Comment by simonferquel** [comment]
There is no wsl endpoint anymore.
Can you send a diagnostic please ? There must be something wrong with the wsl integration agent, that logs could reveal.

**Comment by ayashkantha** [comment]
> There is no wsl endpoint anymore.
> Can you send a diagnostic please ? There must be something wrong with the wsl integration agent, that logs could reveal.

I uninstalled docker desktop and installed native docker on wsl, that is working fine so far. Thank you for the reply.
