### ISSUE TITLE
ADE55B86-63E9-4CB2-B98C-99672A7D2563/20200109130655

### ISSUE THREAD

**Issue by joachimzadi** [docker/for-win#5448]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ulrich** [comment]
Thank you for report, but we need more informations about your trouble.
