### ISSUE TITLE
Docker Desktop for Windows (Edge) locks read only file volumes 

### ISSUE THREAD

**Issue by paulspencerwilliams** [docker/for-win#5449]
The Edge version of Docker Desktop for Windows locks file volumes mounted readonly, unlike the stable version. 

  - [ x] I have tried with the latest version of my channel (Stable and Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 99472381-30A3-42CD-BF25-61D903B7C4FD/20200109142035

### Expected behavior

Starting the attached `docker-compose` environment which mounts a read only file volume to `realm-import.json` does not leave a lock open to this file. This is replicated in the Stable Version: 

![image (3)](https://user-images.githubusercontent.com/351758/72075398-93682200-32eb-11ea-87ed-3242aeca5466.png)

![image (1)](https://user-images.githubusercontent.com/351758/72075454-a8dd4c00-32eb-11ea-8ea1-61f031216012.png)

### Actual behavior

Starting the same `docker-compose` environment using Edge results in the following lock by `com.docker.backend.exe`:

<img width="1055" alt="fails-with-docker-for-windows-edge" src="https://user-images.githubusercontent.com/351758/72075506-c27e9380-32eb-11ea-91ea-c2dc621ba875.PNG">

Furthermore, bringing down the environment, and deleting all containers / volumes etc using `docker system prune --volumes -a -f` is insufficient to release the lock. It can only be released by shutting down Docker Desktop. 

### Information
I can replicate this on my physical Windows environment with current Edge.

<img width="411" alt="about-windows" src="https://user-images.githubusercontent.com/351758/72073242-73366400-32e7-11ea-8c07-41543e3cdde7.PNG">

<img width="572" alt="about-edge" src="https://user-images.githubusercontent.com/351758/72073260-7c273580-32e7-11ea-835d-b791ecaf347f.PNG">

### Steps to reproduce the behavior
In folder containing attached docker-compose.yml and realm-import.json file, run 
```
docker-compose up -d
```

Verify locks using 
```
& 'C:\Program Files\LockHunter\LockHunter.exe' c:\users\paulw\source\repos\Gerald\realm-import.json
```

[realm-import.zip](https://github.com/docker/for-win/files/4041023/realm-import.zip)

**Comment by stephen-turner** [comment]
Thanks for the report @paulspencerwilliams. Looking into it.

**Comment by djs55** [comment]
Thanks for the report! I've fixed something related to this, would you like to try an experimental build to see if it helps?

The build is https://download-stage.docker.com/win/edge/41944/Docker%20Desktop%20Installer.exe

If it still reproduces, could you upload a fresh set of diagnostics?

Thanks again!

**Comment by paulspencerwilliams** [comment]
@djs55 I've just tried it, and the good news is that it works perfectly. The file remains unlocked. 

Any ideas whether, if accepted, this change will make it into the next stable release?

**Comment by stephen-turner** [comment]
Yes, it will be in the next Stable release @paulspencerwilliams.

**Comment by stephen-turner** [comment]
I believe this is now fixed: we just forgot to close the ticket, so I'll close it now.
