### ISSUE TITLE
Kubernetes won't start

### ISSUE THREAD

**Issue by nachtmonkey** [docker/for-win#5450]
- [ x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x ] I have uploaded Diagnostics
  - Diagnostics ID:  C5643B52-3961-4C7F-B218-02339860172B/20200109184828

### Expected behavior
Kubernetes starts

### Actual behavior
The message 'kubernetes starting' doesn't go away

### Information
  - Is it reproducible?  Yes
  - Is the problem new?  Don't know, this is my first time enabling Kubernetes
  - Did the problem appear with an update?  No
  - Windows Version:  10
  - Docker Desktop Version:  2.1.7.0 (41536)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:  no

### Steps to reproduce the behavior
Tried restarting Docker, uninstalling and reinstalling.  Tried it with the latest version of Stable and Edge.

  1. Run Docker
  2. Open Setttings
  3. Go to Kubernetes tab
  4. Enable Kubernetes
  5. Always says 'Kubernetes starting', never actually starts

The log file has a repeating message:  

[ApiProxy          ][Info   ] time="2020-01-09T13:59:48-05:00" msg="cannot list nodes: Get https://kubernetes.docker.internal:6443/api/v1/nodes: EOF"

I don't know if that is relevant. Tried the 'Reset Kubernetes cluster' button.  Also tried deleting pki and .kube folders, no change in behavior.

**kubctl version** yields:

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Unable to connect to the server: EOF

**Comment by nachtmonkey** [comment]
I figured it out.  It was a proxy issue.  My fault, but the error message could stand to be a little more helpful.

**Comment by STaRDoGG** [comment]
@nachtmonkey I have the same issue; what do you mean specifically by "it was a proxy issue?"

I don't have anything set in the GUI for Proxy.

**Comment by nachtmonkey** [comment]
@STaRDoGG  I am running on Windows 10.  In my case, it was the system proxy settings.  In the start menu, type 'proxy' and disable it there.  Good luck.
