### ISSUE TITLE
Docker cannot start after fresh install

### ISSUE THREAD

**Issue by pyro-dev** [docker/for-win#5451]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 5A0BFB28-EA80-4415-AD6B-549B34EE5F53/20200110045126

### Expected behavior
Docker Desktop shall start after fresh install

### Actual behavior
Docker Desktop fails with an exception
 
### Information

  - Windows Version: Windows 10 Enterprise1909, build 18363.535
  - Docker Desktop Version: 2.1.0.5
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

I have HyperV running (tested with HyperV Quick Create with some Ubuntu machines, and Windows Sandbox is running fine as well), and also installed Containers optional feature.
When attempting to start Docker Desktop, I just get an error as described below.

> Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Failed to create a new virtual machine.
> 
> 'DockerDesktopVM' failed to realize. (Virtual machine ID 4C75CA66-EE70-45FD-8F07-18259BB42619)
> 
> Failed to access configuration store: The system cannot find the path specified. (0x80070003).
> 
>    at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
>    at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
>    at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
>    at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

### Steps to reproduce the behavior

  1. Installing Docker Desktop
  2. Try to launch it

**Comment by mat007** [comment]
Possibly similar to #1200?

**Comment by Andrew415** [comment]
I confirm this issue affects me too. Trying on multiple Windows 2019 versions in AWS. I've tried switching to Windows containers as well and it still breaks on stable or edge.

**Comment by jaydigital01** [comment]
jaydigital01
I'm confirming the problem. Been working on it for a week. Using a new HP AIO desktop. It worked once, but crashes on startup whenever I open Docker Desktop. Using ver. 2.2.0.0

**Comment by jaydigital** [comment]
Forget it!
