### ISSUE TITLE
Windows 10 Enterprise 1511 10586.753

### ISSUE THREAD

**Issue by svantebanan** [docker/for-win#546]
### Expected behavior

Docker to start after installation

### Actual behavior

When I try to start it after a fresh installation I get an error with the message "Hardware assisted virtualization and data execution protection must be enabled in the BIOS". 

### Information

Might be related to issue 536 [https://github.com/docker/for-win/issues/536](url)

I have virtualization enabled according my taskmanager and I have double checked the settings in BIOS. Also virtual box and VMware works just fine. 

Here is my output from docker version:
PS H:\> docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      windows/amd64
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.26/version: open //./pipe/docker_engine: The system c
annot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to
 connect. This error may also indicate that the docker daemon is not running.

### Steps to reproduce the behavior

1. Install Docker
2. Launch after installation
3. Docker crashes on start with error

**Comment by alvissd** [comment]
I have the same issue. Tried to reisntall many times as well as download newest version.
C:\Users\locmai>docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      windows/amd64
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.26/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

**Comment by svantebanan** [comment]
Also tried the new version and it still the same issue.

**Comment by rneugeba** [comment]
Could you please provide a diagnostics ID? You can upload it via the whale systray menu.
thanks

**Comment by alvissd** [comment]
Just upload it: 2B80BD8F-B657-4A68-9F6F-A62389B0A285/2017-03-08_10-03-57
This is when docker was starting forever,sometimes it come with a crash report,,sometimes it stay that way forever.

**Comment by svantebanan** [comment]
Here is my diagnostics: 410F82E8-5E40-43AC-8F17-0E9B4CF66798/2017-03-08_09-40-16

**Comment by rneugeba** [comment]
Thanks for the reports. @alvissd, looking at your logs it is very different to @svantebanan. Could I ask you open a separate issue?

@svantebanan Looking at your debug info, I see in the `bcdedit` output:
```
hypervisorlaunchtype    Off
```
This means that Hyper-V will not be launched at boot time.

I also see several VMware processes running. Hyper-V and VMware can not be run at the same time.  Could you try to disable/uninstall VMware and then disable the Hyper-V feature. A reboot is required. Then Docker for Windows should try to enable HyperV again and another restart would be required.

**Comment by svantebanan** [comment]
I updated to the new build of Windows version 1607 (14393.447) and now it seems to be working.

**Comment by rneugeba** [comment]
@svantebanan thanks for getting back and glad that it is working now. I suspect the update re-enabled Hyper-V in the boot config. Closing this issue.

**Comment by svantebanan** [comment]
Yes its set to auto now in the new version, so that was most likely the problem that I had. Thank you for your help.

**Comment by alvissd** [comment]
Don't know how but I just tried to disable and enable the Hyper-V (again) and now it works.
Thanks anyway :D

**Comment by rneugeba** [comment]
@alvissd excellent. Good to hear. The slightly odd thing with your system was that there were hardly any diagnostics collected, which is strange, ho hum
