### ISSUE TITLE
Permission denied to the mount path

### ISSUE THREAD

**Issue by kunalverma94** [docker/for-win#5471]
Hi ,  
When i run i linux based  container  with physical location mounted and then try to write to that mounted path 
i get Error Permission denied
docker run --rm -it -v ${PWD}:/www  alpine 
inside container I navigated to www folder 
cd www
mkdir xyz 
Error Permission dennied
when i try to create folder inside www folder it says Permission denied .
inspect info :
   "Mounts": [
            {
                "Type": "bind",
                "Source": "/host_mnt/d/Users/",
                "Destination": "/aaa",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
Details:
-Linux container
-win 10
-Docker latest version
I have added a few seconds video that explains it please take a  look.  
Regards,
Kunal Verma
[video.zip](https://github.com/docker/for-win/files/4058044/video.zip)

**Comment by mat007** [comment]
Which version is this? If this is the latest Edge, can you please generate a diagnostics.
If not can you try with the latest Edge https://docs.docker.com/docker-for-windows/edge-release-notes/ ?

**Comment by kunalverma94** [comment]
Hi @mat007 ,
Thank you 👍  very much i updated and it started working fine for me .

Please find previous error version details if needed
version : Docker Desktop Community 2.1.5.0
[20200114100439.zip](https://github.com/docker/for-win/files/4058642/20200114100439.zip)

Thanks and regards ,
Kunal Verma
