### ISSUE TITLE
mount error(13): Permission denied

### ISSUE THREAD

**Issue by Jetsly** [docker/for-win#548]
OS: win10 10.0.10586
docker version
```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
```
Error log
````
[09:35:10.731][ApiProxy       ][Info   ] proxy << POST /v1.26/containers/20faed574603ca5dbed828d9a1d4ab7affb0600fea1898177543eb7e44d6374c/start
[09:35:10.746][ApiProxy       ][Info   ] proxy << POST /v1.26/containers/20faed574603ca5dbed828d9a1d4ab7affb0600fea1898177543eb7e44d6374c/attach?stderr=1&stdin=1&stdout=1&stream=1
[09:35:11.536][ApiProxy       ][Info   ] Cancel connection...
[09:35:11.543][SambaShare     ][Error  ] Unable to mount E drive: 10.0.75.1 (10.0.75.1:445) open
mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
mount: mounting //10.0.75.1/E on /e failed: Invalid argument
````

**Comment by friism** [comment]
@Jetsly can you please run the in-app diagnostics and post diagnostic ID?

**Comment by Alienpruts** [comment]
Hello, sorry to barge in like this, but I experience the same error.

Whenever I try to select the C drive for sharing, it asks me for my credentials, after which it returns to the share drive dialog, which remains unchecked. The log excerpt as posted by @Jetsly is the same is for me, except ofcourse the drive letter (C in my case)

I've added a diagnostic:

A diagnostic was uploaded with id: A6C62569-D863-418C-A9FB-A987C9A1008D/2017-03-12_16-59-00

Hope this helps, should any more info be needed, shout.

**Comment by thiagolunardi** [comment]
The same with me.

A diagnostic was uploaded with id: 0B5FCE3D-AD53-469F-826A-9A44C5A45115/2017-03-30_11-44-04

**Comment by sytou** [comment]
Same error in the log file : 
[16:05:37.757][SambaShare     ][Error  ] Unable to mount C drive: 10.0.75.1 (10.0.75.1:445) open
mount error(112): Host is down
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
mount: mounting //10.0.75.1/C on /c failed: Invalid argument
A diagnostic was uploaded with id: 4D552922-0C5E-494B-825D-C1B264C14D7B/2017-04-10_16-07-17

**Comment by wambiri** [comment]
I was having similar issues and had almost given up trying to resolve, until i found this:

https://github.com/docker/for-win/issues/313

Not sure if it will help anyone here but following totomakers instructions at the bottom solved my issues.

**Comment by rn** [comment]
closing old issues

**Comment by FritschAuctores** [comment]
Any Solution?
