### ISSUE TITLE
Exception when launching hello-world in docker

### ISSUE THREAD

**Issue by sashalok** [docker/for-win#549]
### Actual behavior
 docker run hello-world  
Exception 0xc0000005 0x0 0xc042baafe9 0x18000890a
PC=0x18000890a

syscall.Syscall(0x7ff84986dc40, 0x2, 0x268, 0x3, 0x0, 0x0, 0x0, 0x26c)
        /usr/local/go/src/runtime/syscall_windows.go:163 +0x6b
github.com/docker/docker/vendor/github.com/Microsoft/go-winio.setFileCompletionNotificationModes(0x268, 0x203, 0x0, 0xffffffff)
        /go/src/github.com/docker/docker/vendor/github.com/Microsoft/go-winio/zsyscall_windows.go:88 +0x6f
github.com/docker/docker/vendor/github.com/Microsoft/go-winio.makeWin32File(0x268, 0xc0423ab890, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/github.com/Microsoft/go-winio/file.go:78 +0xd8
github.com/docker/docker/vendor/github.com/Microsoft/go-winio.DialPipe(0xc0420b13c8, 0x16, 0xc0423ab980, 0x0, 0xc0423b4120, 0xc041fe28f7, 0xc0423ab9f8)
        /go/src/github.com/docker/docker/vendor/github.com/Microsoft/go-winio/pipe.go:188 +0x537
github.com/docker/docker/vendor/github.com/docker/go-connections/sockets.DialPipe(0xc0420b13c8, 0x16, 0x773594000, 0xc042028800, 0x10, 0x100, 0x100)
        /go/src/github.com/docker/docker/vendor/github.com/docker/go-connections/sockets/sockets_windows.go:26 +0x46
github.com/docker/docker/vendor/github.com/docker/go-connections/sockets.configureNpipeTransport.func1(0xba722f, 0x3, 0xc04237f820, 0x19, 0x60, 0x0, 0xc0423b8001, 0xc0423b4180)
        /go/src/github.com/docker/docker/vendor/github.com/docker/go-connections/sockets/sockets_windows.go:19 +0x49
net/http.(*Transport).dial(0xc0420b2870, 0xf13040, 0xc04200a2c0, 0xba722f, 0x3, 0xc04237f820, 0x19, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/http/transport.go:829 +0x82
net/http.(*Transport).dialConn(0xc0420b2870, 0xf13040, 0xc04200a2c0, 0x0, 0xba795f, 0x4, 0xc04237f820, 0x19, 0x0, 0x0, ...)
        /usr/local/go/src/net/http/transport.go:967 +0x1a8c
net/http.(*Transport).getConn.func4(0xc0420b2870, 0xf13040, 0xc04200a2c0, 0xc04237bda0, 0xc04239c420)
        /usr/local/go/src/net/http/transport.go:885 +0x7f
created by net/http.(*Transport).getConn
        /usr/local/go/src/net/http/transport.go:887 +0x3a8

goroutine 1 [select]:
github.com/docker/docker/vendor/golang.org/x/net/context/ctxhttp.Do(0xf13300, 0xc04200b4c8, 0xc04237bce0, 0xc0420b2960, 0xc0420b2960, 0xc0421539e0, 0x599f4c)
        /go/src/github.com/docker/docker/vendor/golang.org/x/net/context/ctxhttp/ctxhttp.go:55 +0x40a
github.com/docker/docker/client.(*Client).doRequest(0xc0423a2000, 0xf13300, 0xc04200b4c8, 0xc0420b2960, 0x6, 0x0, 0x0, 0x0, 0xc0420b2960, 0x0)
        /go/src/github.com/docker/docker/client/request.go:127 +0x75
github.com/docker/docker/client.(*Client).Ping(0xc0423a2000, 0xf13300, 0xc04200b4c8, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/client/ping.go:17 +0x1d4
github.com/docker/docker/cli/command.(*DockerCli).Initialize(0xc042191500, 0xc0422e90e0, 0x3, 0xc042364d80)
        /go/src/github.com/docker/docker/cli/command/cli.go:158 +0x181
main.newDockerCommand.func2(0xc042364d80, 0xc042382b90, 0x1, 0x1, 0x0, 0x0)
        /go/src/github.com/docker/docker/cmd/docker/docker.go:48 +0xa9
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0xc042364d80, 0xc042007fd0, 0x1, 0x1, 0xc042364d80, 0xc042007fd0)
        /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:628 +0x578
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc042075680, 0xc042075b00, 0xc04230ad80, 0xc042026428)
        /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:742 +0x37e
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(0xc042075680, 0xc042075680, 0xf0ad40)
        /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:695 +0x32
main.main()
        /go/src/github.com/docker/docker/cmd/docker/docker.go:104 +0xeb

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:116 +0x15e
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x29
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x48

goroutine 6 [select]:
net/http.(*Transport).getConn(0xc0420b2870, 0xc04237f800, 0x0, 0xba795f, 0x4, 0xc04237f820, 0x19, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:890 +0x9d3
net/http.(*Transport).RoundTrip(0xc0420b2870, 0xc0420b2960, 0xc0420b2870, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:367 +0x31a
net/http.send(0xc0420b2960, 0xf0a700, 0xc0420b2870, 0x0, 0x0, 0x0, 0x8, 0xc042026560, 0x411d3f)
        /usr/local/go/src/net/http/client.go:256 +0x166
net/http.(*Client).send(0xc04237bce0, 0xc0420b2960, 0x0, 0x0, 0x0, 0xc042026560, 0x0, 0x1)
        /usr/local/go/src/net/http/client.go:146 +0x109
net/http.(*Client).doFollowingRedirects(0xc04237bce0, 0xc0420b2960, 0xc2b880, 0x3, 0x1, 0x0)
        /usr/local/go/src/net/http/client.go:528 +0x5ec
net/http.(*Client).Do(0xc04237bce0, 0xc0420b2960, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:184 +0x1f1
github.com/docker/docker/vendor/golang.org/x/net/context/ctxhttp.Do.func1(0xc04237bce0, 0xc0420b2960, 0xc2b1a0, 0xc04239c3c0)
        /go/src/github.com/docker/docker/vendor/golang.org/x/net/context/ctxhttp/ctxhttp.go:48 +0x40
created by github.com/docker/docker/vendor/golang.org/x/net/context/ctxhttp.Do
        /go/src/github.com/docker/docker/vendor/golang.org/x/net/context/ctxhttp/ctxhttp.go:51 +0xe4

goroutine 17 [syscall, locked to thread]:
syscall.Syscall6(0x7ff849866bf0, 0x5, 0x26c, 0xc0423a5f5c, 0xc0423a5f60, 0xc0423a5f68, 0xffffffff, 0x0, 0x7ff843c43040, 0x1, ...)
        /usr/local/go/src/runtime/syscall_windows.go:174 +0x6b
github.com/docker/docker/vendor/github.com/Microsoft/go-winio.getQueuedCompletionStatus(0x26c, 0xc0423a5f5c, 0xc0423a5f60, 0xc0423a5f68, 0xffffffff, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/github.com/Microsoft/go-winio/zsyscall_windows.go:76 +0xc6
github.com/docker/docker/vendor/github.com/Microsoft/go-winio.ioCompletionProcessor(0x26c)
        /go/src/github.com/docker/docker/vendor/github.com/Microsoft/go-winio/file.go:129 +0x82
created by github.com/docker/docker/vendor/github.com/Microsoft/go-winio.initIo
        /go/src/github.com/docker/docker/vendor/github.com/Microsoft/go-winio/file.go:57 +0x87
rax     0x0
rbx     0xc042028b68
rcx     0x268
rdi     0x312000
rsi     0xc0423ab7a0
rbp     0xc0423ab750
rsp     0x2ddfd98
r8      0x1
r9      0x0
r10     0x268
r11     0x1218620
r12     0x0
r13     0xd3
r14     0xc27a3b
r15     0x3
rip     0x18000890a
rflags  0x10246
cs      0x33
fs      0x53
gs      0x2b### Information
- Diagnostic ID from "Diagnose & Feedback" in the menu.
B42B5432-1BBC-4C4F-B4BC-34C2CA33580F/2017-03-03_12-29-17
  
  ### Steps to reproduce the behavior

  1. docker run hello-world  
2. ...

**Comment by rneugeba** [comment]
Looking at  docker/docker#27423 and your logs in more detail, it does look like the same issue. you get a permission denied error. I'm closing this issue for now, please re-open if you don't have a Web Companion or similar installed.
