### ISSUE TITLE
Docker for Windows using WSL 2 experimental backend failing to start for 2.1.7.0

### ISSUE THREAD

**Issue by shinmyung0** [docker/for-win#5497]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6CE92A12-C63A-4509-99DC-E20419F732C7/20200118053259

### Expected behavior

Docker for windows should start using the experimental backend for WSL 2. This was working previously without issues.

### Actual behavior

Docker for windows fails to start.

### Information

  - Windows Version: 19041.21
  - Docker Desktop Version: 2.1.7.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

Docker does not start up at all. I've checked `%AppData%/Docker` to check if compression or encryption is enabled but it isn't.

**Comment by simonferquel** [comment]
It seems to be the same bug as https://github.com/microsoft/WSL/issues/4726. The fix is going to rollout in an upcoming Windows build.
In the mean time, a simple restart of Windows should fix the issue.
