### ISSUE TITLE
Docker hv-sock proxy (vsudd) is not reachable

### ISSUE THREAD

**Issue by KorwinS** [docker/for-win#550]
### Expected behavior
Expect docker to start up properly

### Actual behavior
Docker attempts to start when the computer is started. After several minutes it pops up with "An error occurred" stating:
"Docker hv-sock proxy (vsudd) is not reachable
   at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

### Information
Diagnostic ID from "Diagnose & Feedback" in the menu:
3799E979-03D6-497F-BEA0-D2A734B47892/2017-03-03_13-44-44

host distribution and version (Windows version, build number, etc):
Version: 17.03.0-ce-win1 (10300)
Channel: beta
Sha1: 05a8abd3046f3afe1a293f3f41239d3b5cc183f3
Started on: 2017/03/03 13:41:27.695
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1607
Build: 14393
BuildLabName: 14393.0.amd64fre.rs1_release.160715-1616

I've tried stable and beta channels and get the same exact error with both. 

### Steps to reproduce the behavior
Fresh install of Docker for Windows
Start Docker

**Comment by zaktimson** [comment]
Same issue, Diagnostic ID: 0A99EB25-25FB-4BE5-A658-BEEC44B3B4B4/2017-03-03_14-31-51

**Comment by Fantoccini** [comment]
same issue: 511C83E9-063C-4BE7-8EEB-AE187AF691CA/2017-03-04_22-15-11

**Comment by SanderElias** [comment]
Had the same issue, enabled a fixed DNS, and that seemed to solve it.

**Comment by KorwinS** [comment]
Tried changing the DNS settings to fixed and get the same error.

**Comment by KorwinS** [comment]
The issue was resolved by updating Windows 10 to the last big rollup update.

**Comment by Nqabeni** [comment]
Which update? I am experiencing the same issue.

**Comment by Fleischloser** [comment]
For me the only working solution was to complete uninstall docker and hyper-v via widows-feature deactivate.
