### ISSUE TITLE
Unable to access Docker daemon from Pengwin (WLinux) WSL 2 distro

### ISSUE THREAD

**Issue by magneticflux-** [docker/for-win#5500]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: FD788649-191E-46E8-96CE-19A170F2BDB5/20200120004730

### Expected behavior

I am able to access the daemon from inside a WSL2 distro.

### Actual behavior

I am unable to access the daemon from inside a WSL2 distro.

### Information

  - Windows Version: Windows 10 Pro Insider Preview Build 19546
  - Docker Desktop Version: 2.1.7.0 (41536)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No
  - Distro used: Pengwin (WLinux)

### Steps to reproduce the behavior

  1. Install Docker Desktop Edge
  2. Enable experimental WSL 2 based engine
  3. Enable WSL integration under Settings/Resources/WSL Integration/WLinux
  4. Attempt to start "hello world" container in WSL 2 distro

**Comment by magneticflux-** [comment]
Related issues: https://github.com/docker/for-win/issues/5107 https://github.com/docker/for-win/issues/5153

**Comment by simonferquel** [comment]
Hi @magneticflux- Just read your diagnostic file. It appears to be a known issue (that we fixed in the build to come this week).
It looks like the root's user default shell has been changed in WLinux, and our docker group creation script fails. Can you confirm that changing it to bash fixes the issue ?
You can do that with
```
wsl.exe -d WLinux -u root
chsh -s /bin/bash
```

**Comment by magneticflux-** [comment]
That fixes it, thanks!
