### ISSUE TITLE
Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to stop.

### ISSUE THREAD

**Issue by kimschurmann** [docker/for-win#5503]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F217F9AE-0ABF-4580-86FE-145E12352542/20200120063544

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. Start docker desktop :)

**Comment by jovanhan2** [comment]
same issue, diagnostics ID: D8B1E502-7E03-4C06-AC7D-AC9A916221A9/20200120112853
