### ISSUE TITLE
Extracting image fails: failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer \\?\C:\ProgramData\Docker\windowsfilter\*: The parameter is incorrect.

### ISSUE THREAD

**Issue by Antronin** [docker/for-win#5506]
For me this is still an issue:
```PS C:\WINDOWS\system32> docker pull nanoserver/iis
Using default tag: latest
latest: Pulling from nanoserver/iis
bce2fbc256ea: Extracting [==================================================>]  252.7MB/252.7MB
e7a598ed389e: Download complete
330fc9a0a84f: Download complete
8accfc5d2068: Download complete
ce0579b0380c: Download complete
363f5ae71fe9: Download complete
bdadd5a88cb5: Download complete
73f9c45f3462: Download complete
failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer \\?\C:\ProgramData\Docker\windowsfilter\60ffe5729894329a0e53cd97b4ce80af4459d95efc06f5edb37044d249dda4e2: The parameter is incorrect.
```

I switched my Docker Destop to use Windows Containers. Still once the Download of the layer are finished, at the end of the first layers extract I got this error, all the time.

I'm on Windows 10, Diagnostic ID is: 0FDAFCEF-27E8-4C7A-B0ED-1613BA01A5F0/20200120142208
I'm unable to use almost any Windows image:

```
PS C:\WINDOWS\system32> docker pull microsoft/iis
Using default tag: latest
latest: Pulling from microsoft/iis
3889bb8d808b: Extracting [==================================================>]   4.07GB/4.07GB
31f9df80631e: Download complete
26c58eaecc60: Download complete
1eea0c95c6fc: Download complete
5c630eb846f0: Download complete
failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer \\?\C:\ProgramData\Docker\windowsfilter\a5ea703cb7da8015bd69cefef038402b29c0c9bdd75b5e36cafc25d7836ea172: The parameter is incorrect.
```

_Originally posted by @Antronin in https://github.com/docker/for-win/issues/933#issuecomment-576297464_

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place.
Thanks

**Comment by Antronin** [comment]
Please tell me why is this not an issues with Docker Desktop, while this was considered as one:
https://github.com/docker/for-win/issues/933
I originally posted it there, but I realized it was closed so I created this new issue.

**Comment by mat007** [comment]
Docker Desktop merely packages the `docker` CLI and Windows daemon but the code and support lives in the open-source upstream `moby/moby`.
