### ISSUE TITLE
No IP Address is assigned to MobyLinuxVM

### ISSUE THREAD

**Issue by szantopeter** [docker/for-win#551]
I am trying to create a swarm cluster, by making my docker for windows the master. I can access the exposed services from a remote browser, but remote nodes can't join the swarm cluster

    > docker swarm join --token <<TOKEN>> 192.168.0.10:2377
    Error response from daemon: rpc error: code = 14 desc = grpc: the connection is unavailable

I also noticed that in the hyper-v Manager the MobyLinux VM does not get an IP address

![image](https://cloud.githubusercontent.com/assets/69414/23570939/e6debb2a-0066-11e7-8a01-b454eb339789.png)

I tried to change the virtual network switch external, but it didn't help

Diagnostic info : 871C2321-9189-4551-A28A-A454A24B698E/2017-03-03_23-25-04

**Comment by digitalbanana** [comment]
I see the same issue but it means I cannot get Rancher u[p and running locally.....its a pain so any help is appreciated
