### ISSUE TITLE
Enable the experimental WSL 2 based engine check box. does not exist

### ISSUE THREAD

**Issue by dakorpar** [docker/for-win#5513]
I'm running wsl 2 on my machine and latest version of docker, but I don't have
Enable the experimental WSL 2 based engine check box. under general.
I restarted docker and PC it did not help.

![image](https://user-images.githubusercontent.com/9303856/72825965-45063c00-3c78-11ea-98fd-5b2a0227d3fa.png)

 - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 28E690D2-9D79-4F5C-8911-E9AB2672FB7A/20200121170040

### Expected behavior
I should have that check box
### Actual behavior
I do not have checkbox

**Comment by giesenmartin** [comment]
The same for me

**Comment by Kinmarui** [comment]
same here
Diagnostic ID: 398E90E9-6A35-405D-BBC1-5728D1DCAA5B/20200121205659

**Comment by Michagogo** [comment]
I am also not seeing the option to switch to using WSL2.
Diagnostic ID is 8BD62117-08EF-4326-83FA-414A6B83C74A/20200122051026.

**Comment by chunter90** [comment]
The same for me.
Diagnostic ID: 42A89AEE-EAA0-4554-9932-C47DC34A3FFD/20200122083742

**Comment by guillaumerose** [comment]
We are fixing it, a new release will be published soon.

**Comment by mat007** [comment]
Can anyone with this issue please try the following:
1. make sure you’re connected to the Internet
2. quit Docker Desktop 2.2.0.0 if needed
3. start Docker Desktop 

The WSL 2 checkbox is behind a feature flag which is listed in a file downloaded from the Internet when Docker Desktop starts (and on a 1h timer when it runs).
There might however be a cache somewhere on Windows as we’ve seen in the past some users for whom the checkbox suddenly appeared without them (or us) changing anything… If the checkbox doesn’t show up after going through 1, 2, 3 above then wait a bit and retry after a few minutes.

You’ll be happy to know that we have changed our feature flags implementation on Edge to fix this, but it didn’t make it to Stable quite yet.

Sorry for the inconvenience!

**Comment by giesenmartin** [comment]
Yep, it has work for me.

Thank you very much

 

Martin Giesen

Heidhörn 8

22307 Hamburg

 

Tel.:  040-69705784

E-Mail:   <mailto:martin@giesen-webentwicklung.de> martin@giesen-webentwicklung.de

 

 

 

 

 

Von: Mathieu Champlon <notifications@github.com> 
Gesendet: Mittwoch, 22. Januar 2020 12:50
An: docker/for-win <for-win@noreply.github.com>
Cc: giesenmartin <martin@giesen-webentwicklung.de>; Comment <comment@noreply.github.com>
Betreff: Re: [docker/for-win] Enable the experimental WSL 2 based engine check box. does not exist (#5513)

 

Can anyone with this issue please try the following:

1.	make sure you’re connected to the Internet
2.	quit Docker Desktop 2.2.0.0 if needed
3.	start Docker Desktop

The WSL 2 checkbox is behind a feature flag which is listed in a file downloaded from the Internet when Docker Desktop starts (and on a 1h timer when it runs).
There might however be a cache somewhere on Windows as we’ve seen in the past some users for whom the checkbox suddenly appeared without them (or us) changing anything… If the checkbox doesn’t show up after going through 1, 2, 3 above then wait a bit and retry after a few minutes.

You’ll be happy to know that we have changed our feature flags implementation on Edge to fix this, but it didn’t make it to Stable quite yet.

Sorry for the inconvenience!

**Comment by dakorpar** [comment]
works, thanks

**Comment by Kinmarui** [comment]
guess this
> on a 1h timer when it runs

didn't even restart docker from yesterday and now I see WSL2 option.
