### ISSUE TITLE
Docker Update installation failed on Windows 10

### ISSUE THREAD

**Issue by saf-itpro** [docker/for-win#5514]
**Environment**:  Windows 10 - Pro - ver 1903

Got the latest update notification from Docker today (January 21, 2020). But got the following error message when tried to install the update. Please advise.

**Error**:

> The directory is not empty.
> 
>    at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
>    at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
>    at CommunityInstaller.UninstallWorkflow.<ProcessAsync>d__11.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at CommunityInstaller.InstallWorkflow.<PerformUninstall>d__25.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()

**Comment by djs55** [comment]
@saf-itpro do you have a file called `install-log.txt` in `C:\Users\<username>\AppData\Local\Docker`? If so could you attach it to the ticket?

**Comment by saf-itpro** [comment]
@djs55 Many thanks for prompt response. Requested file is attached.
[install-log.txt](https://github.com/docker/for-win/files/4092773/install-log.txt)

**Comment by mat007** [comment]
@saf-itpro do you have other log files in the same folder with a similar date as `install-log.txt`? Maybe `install-log.1.txt`?
Could you attach `log.txt` as well?

**Comment by andreladocruz** [comment]
same issue here 

Environment: Windows 10 - Pro - ver 1903

Just returned to version 2.1.0.5

**Comment by saf-itpro** [comment]
@mat007 Per your request, files are attached. Please feel free to ask if you need any more info:

[log.txt](https://github.com/docker/for-win/files/4093074/log.txt)

[install-log0.txt](https://github.com/docker/for-win/files/4093084/install-log0.txt)
[install-log1.txt](https://github.com/docker/for-win/files/4093064/install-log1.txt)
[install-log2.txt](https://github.com/docker/for-win/files/4093065/install-log2.txt)
[install-log3.txt](https://github.com/docker/for-win/files/4093066/install-log3.txt)

**Comment by saf-itpro** [comment]
@mat007 Sorry, you had asked for files with similar dates. I should mention that install-log0.txt and install-log1.tx are a year old. And file install-log3 is about two months old. install-log2.txt, install.log and log.txt have modified date as today's date.

**Comment by dogotaru** [comment]
This might be of some help. We had the same failure installing the update. It was solved installing (not updating) the latest version of docker desktop, unchecking "enable required windows settings".
