### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by bryonh** [docker/for-win#5515]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by djs55** [comment]
@bryonh could you open a fresh issue with
- a description of what went wrong
- steps to reproduce the behaviour
- a diagnostics ID (from the whale menu -> Troubleshoot -> Upload)
Thanks!
