### ISSUE TITLE
unix socket bind fails on windows volume mount (grpcfuse)

### ISSUE THREAD

**Issue by umairsair** [docker/for-win#5519]
Docker version 19.03.5

unix socket bind fails on windows volume mount (grpcfuse)

```
root@cac1ce68d053:/docker# cat test.py
#!/usr/bin/env python
import socket
sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
sock.bind("test.socket")


root@cac1ce68d053:/docker# ./test.py
Traceback (most recent call last):
  File "./test.py", line 5, in <module>
    sock.bind("test.socket")
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 5] Input/output error
```

In above example, c:\docker:/docker volume mount is used.

**Comment by stephen-turner** [comment]
Note that this does not work in the previous Samba file sharing implementation either.

I'm not sure what you were hoping would happen. What would a socket look like in the underlying Windows file system where you are trying to write it?

**Comment by umairsair** [comment]
Previously it was limitation of CIFS, but now we are implementing our own file system, so IMO it is possible to support this now. It doesn't matter how it looks like on windows, but for container internal usage, it should be possible to create unix socket and applications inside container can communicate using it. What do you think?

**Comment by stephen-turner** [comment]
We don't have a new file system, we just have a new file sharing mechanism between the underlying Windows file system and the container. It's still backed by a Windows file system underneath.

You can still create a socket in a part of the file system that is not shared from a folder on your host. (And of course there are lots of other methods of interprocess communication that don't go via the Unix file system at all).
