### ISSUE TITLE
Download older stable version

### ISSUE THREAD

**Issue by robbaman** [docker/for-win#5523]
Is there a place where I can download the previous stable version? I've updated to the new 2.2.0.0 version just now and now I'm unable to run the containers I've been running for months.

I've tried uninstalling, rebooting, resetting, nothing works, so after spending about 3 hours on this now I just want to go back to the previous version (the one with the older UI, not the new flashy dashboard).

Unfortunately I can't seem to be able to find a download page listing the older versions to download, so any help would be greatly appreciated.

**Comment by Floxius** [comment]
I only found the 2.1.0.4, but the .5 link is not available, I guess they forgot to update the link, but I guess you can use it and skip this build, then upgrade to 5 when the link will be available: https://docs.docker.com/docker-for-windows/release-notes/

**Comment by MarcelCosta79** [comment]
Same boat too.
Nothing seems to work.

**Comment by ryangroth5** [comment]
I have broken bind mounts where files system propagation is taking minutes and not triggering appropriate rebuilds when I ask npm to watch the filesystem since the update. Thanks for the link.

**Comment by lutomlin** [comment]
I'm having to downgrade to keep using it. I'm having issues where containers don't seem to have mounts cleaned up correctly at teardown, and when I recreate and attempt to start the same container again it claims:
`error while creating mount source path ... : file exists`
It does appear to sometimes go away on restarting the Docker service.

**Comment by MarcelCosta79** [comment]
> I'm having to downgrade to keep using it. I'm having issues where containers don't seem to have mounts cleaned up correctly at teardown, and when I recreate and attempt to start the same container again it claims:
> `error while creating mount source path ... : file exists`
> It does appear to sometimes go away on restarting the Docker service.

That´s exactly whats happening to me.
I´ve just reinstalled multiple times. Same error.

How can I downgrade ?

**Comment by jaskiratr** [comment]
I was facing similar issue. Bind mounts stopped working in 2.2.0 on Windows 10. I downgraded to 2.1.0.4 
to get things back up as earlier.
https://download.docker.com/win/stable/39773/Docker%20Desktop%20Installer.exe

**Comment by mat007** [comment]
Here is the link to the 2.1.0.5 release https://download.docker.com/win/stable/40693/Docker%20Desktop%20Installer.exe
We’ll update the release notes shortly to add it.

**Comment by mfoulds** [comment]
If you use chocolatey, this command should work: `choco install docker-desktop --version=2.1.0.5`

**Comment by robbaman** [comment]
I've uninstalled Docker entirely and then installed the 2.1.0.5 version using choco, but for some reason not all issues are completely gone. When I attempt to run SqlServer via the command

```
docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=saSA123!" --name sql -p 11433:1433 -v C:\DockerData\SqlServer:/var/opt/mssql -d mcr.microsoft.com/mssql/server
```

It creates and runs the container, but it doesn't work. The logs contain a whole array of errors:

```
/usr/bin/find: '/proc/8/task/18/ns': Permission denied
/usr/bin/find: '/proc/8/task/19/fd': Permission denied
/usr/bin/find: '/proc/8/task/19/fdinfo': Permission denied
/usr/bin/find: '/proc/8/task/19/ns': Permission denied
/usr/bin/find: '/proc/8/fd': Permission denied
/usr/bin/find: '/proc/8/map_files': Permission denied
/usr/bin/find: '/proc/8/fdinfo': Permission denied
/usr/bin/find: '/proc/8/ns': Permission denied
/usr/bin/find: '/proc/8/task/8/fd': Permission denied
/usr/bin/find: '/proc/8/task/8/fdinfo': Permission denied
/usr/bin/find: '/proc/8/task/8/ns': Permission denied
/usr/bin/find: '/proc/8/task/9/fd': Permission denied
/usr/bin/find: '/proc/8/task/9/fdinfo': Permission denied
/usr/bin/find: '/proc/8/task/9/ns': Permission denied
/usr/bin/find: '/proc/8/task/10/fd': Permission denied
/usr/bin/find: '/proc/8/task/10/fdinfo': Permission denied
...
```

It seems to have something to do with the volume binding as when I use `-v test:/var/opt/mssql` it works (but then I won't have the data locally). The odd thing is, when I use the command that errors out, a whole lot of files and directories are created in the C:\DockerData\SqlServer location which seems to me that the privileges and such are setup correctly.

Is there a log somewhere that I can check to get more detailed information as to what may be going wrong? Right now it just doesn't work and that's about as much as I know :(

**Comment by mat007** [comment]
@robbaman can you please open a fresh issue with a diagnostic?

**Comment by stephen-turner** [comment]
We have updated the release notes with the location of the previous version.

**Comment by stephen-turner** [comment]
Of course we still want to fix the underlying issues that are causing people to downgrade. But there seem to be several unrelated issues in this ticket, so could everybody who has a problem on 2.2.0.0 please open a new ticket, and include a description of the problem and a diagnostic ID. Thank you.
