### ISSUE TITLE
lots of dns query of docker-for-desktop or docker-desktop always end in NXDOMAIN

### ISSUE THREAD

**Issue by wu105** [docker/for-win#5524]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker desktop with default options should be able to resolve dns name docker-desktop (latest versions) or (older versions) docker-for-desktop that it is trying to resolve repeatedly in the background.

We would like  to know what  docker-desktop/docker-for-desktop is intended to be, the kubernetes cluster created by Docker Desktop or the node of the kubernetes cluster.  If it is intended as the node, how to find out its external ip.  

Docker Desktop installation is already updating the /etc/hosts file on the host, and it would be best to add an entry also for docker-desktop/docker-for-desktop.

At least there should be an option to control the qurery frequency.
 
### Actual behavior
Docker desktop installations with Kubernetes enabled generates upto 100,000 dns queries on docker-for-desktoip per day that all end up on the root dns server generating NXDOMAIN error.  Latest Docker Desktop seems to be querying docker-desktop.  The individual windows hosts see no ill effect, but the company dns server gets the queries from all Docker Desktop hosts and is under stress to keep up.

### Information

  - Windows Version: windows 10
  - Docker Desktop Version: latest and versions released in the past year, e.g., 2.0.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. install Docker Desktop,  new or older versions, default configuration, then enable kubernetes
  2. check the _default domain_ root dns server for queries on docker-for-desktop._default domains_ or docker-desktop._default domains_ that end up in NXDOMAIN,  _default domains_ are the ones configured on the installation host.  Such queries are especially resource intensive to process, because it is not cached, and goes all the way to the root  DNS server for the <default domain> every time, which works hard before giving up with NXDOMAIN error.

**Comment by mat007** [comment]
I believe this is actually a duplicate of #5089
