### ISSUE TITLE
Folder sharing not working with Docker Desktop v2.2.0.0

### ISSUE THREAD

**Issue by Holger2233** [docker/for-win#5526]
I updated to Docker Desktop for Windows version 2.2.0.0 today and since that the folder sharing between local (Windows) host and container does not work anymore. The command
`docker run --rm -v C:\dev\Tests:/tests -it test/testcafe -e chromium:headless /tests/Login.js`
was working fine on my previous docker version, but since the update it returns an error:
`docker: Error response from daemon: error while creating mount source path '/host_mnt/c/dev/Tests': mkdir /host_mnt/c/dev: file exists.`
This is regardless of enabling drive sharing globally in the settings, or on demand via cmd windows.

Furthermore, sharing on demand does only work in Windows cmd, but not in Powershell, where the command fails with the error above straight away without sharing popup being displayed.

Please provide a fix for this asap, otherwise I will have to downgrade as well.

https://hub.docker.com/editions/community/docker-ce-desktop-windows -->
  - [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: (downgraded to Docker v2.1.0.4 already as I need to keep working with Docker)

### Expected behavior
Docker run with folder sharing works as prior to Docker update 
### Actual behavior
After updating Docker, 
`docker run --rm -v C:\dev\Tests:/tests -it test/testcafe -e chromium:headless /tests/Login.js` 
fails with error 
`docker: Error response from daemon: error while creating mount source path '/host_mnt/c/dev/Tests': mkdir /host_mnt/c/dev: file exists.`
### Information

  - Windows Version: Windows 10.0.18363
  - Docker Desktop Version: 2.2.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
1. update Docker
2. build docker image using attached dockerfile
[dockerfile.zip](https://github.com/docker/for-win/files/4094968/dockerfile.zip)
3. Run command `docker run --rm -v C:\dev\Tests:/tests -it test/testcafe -e chromium:headless /tests/Login.js`  with either C: drive shared in the Docker settings or using sharing on demand.

**Comment by mat007** [comment]
Hi, thanks for reporting this, it looks the same as #5516, right?

**Comment by stephen-turner** [comment]
Resolving as duplicate. #5516 has an explanation and workaround.
