### ISSUE TITLE
6E8CCA58-1DC8-4643-9D5F-C314BBE8B8A1/20200122022037

### ISSUE THREAD

**Issue by shihajp** [docker/for-win#5527]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ManfredLange** [comment]
What issue is this describing? @shihajp Perhaps you could update with a more descriptive title and some more details about the problem you're observing. This would help other users to see if they observe the same or a different issue. Also, in some cases a different user might be able to suggest a workaround.
