### ISSUE TITLE
Intermittent issues saving files on volume mounts after upgrading from 2.1.0.5 to 2.2.0.0

### ISSUE THREAD

**Issue by ManfredLange** [docker/for-win#5528]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BD5A15A8-2B44-443D-91BC-C2B67188BF92/20200122024100

### Expected behavior

Shouldn't interfere with editing files in a folder that is part of a mounted volume

### Actual behavior

VS Code frequently reports error when editing code inside development container:
> Failed to save '<filename>': The content of the file is newer. Please compare your version with the file contents.
An example for <filename> is `time.integration.ts` (i.e. there are to dots in the file name; is this considered to be "canonical?)
When that error is shown the file in question cannot be saved. The file is in a folder that is part of a volume mount.

### Information

This is reproducible as far as it happens quite frequently with version 2.2.0.0 and did not at all with version 2.1.0.5. It's just a matter of time, i.e. it may work for a while and then saving  file will result in this error.

I noticed there was an item in the release notes indicating that how volume mounts are treated has changed, e.g. to improve the performance. Could this be related?

### Environment:
- Windows 10 Pro Version 10.0.18362 Build 18362
- Docker Desktop 2.2.0.0 (42247)
- Visual Studio Code version 1.41.1
- No virtualized Windows, no VM (other than the one Docker Desktop creates)
- Docker Desktop configured to run Linux-based container

### Steps to reproduce the behavior

  1. Set up some project, e.g. nodejs/typescript, with VS Code, a development container and the extension for remote development
  2. Edit files while connected with development container. This will intermittently show the error.

### Dockerfile
```
FROM node:12

# node may come with an outdated version of npm. Ensure we have latest npm.
RUN npm install -g npm

# Avoid EACCESS when running in dev container:
# RUN mkdir /lambda
# RUN chown -R root:root /lambda
```
### docker-compose.yml
```
version: '3.2'

services:
  dev:
    image: toggl-import-dev-container
    build:
       context: .
       dockerfile: Dockerfile
    container_name: toggl-import-dev-container
    working_dir: /lambda
    volumes:
       - .:/lambda
       # Allows SLS to read an AWS profile (see serverless.yml)
       - ~/.aws:/root/.aws
    depends_on:
      - localstack
    # Make sure the dev container doesn't exit right away:
    command: sleep infinity

  localstack:
    image: localstack/localstack
    ports:
      - "4567-4584:4567-4584"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
```

**Comment by lorddoumer** [comment]
as already mentioned in other issue: with 2.2. docker has a problem with symlinsk (same folderstructure works perfect with 2.1 after I rolled back), maybe related?

**Comment by mat007** [comment]
Thank you for your for the reproduction steps, I can confirm we were able to reproduce this issue on our end.

**Comment by marcospgp** [comment]
This update was a mess, so many new issues showing up :( I have spent all day trying to debug them but I'll chalk it down to the update and try to install an older version of docker for windows.

**Comment by theloveofcode** [comment]
I am experiencing the same issue.

**Comment by stevensnicole** [comment]
Also seeing same problem here, timestamp being returned to webapp reading an index is : 1970-01-01T00:00:00Z.  Off to rollback.

**Comment by ephesused** [comment]
Perhaps related, I'm seeing container trouble working with files whose paths are long (over 260 characters from the windows side). When I run ls on one of these files, the response is "No such file or directory". When I run ls -l against the directory I see the files listed, but I get question marks for the permissions, owner, group, and date. When I shorten the name of the file so the full windows path is 260 characters or fewer, the file immediately is recognized properly in the container.

**Comment by stephen-turner** [comment]
@ephesused That sounds different, could you open a new ticket please?

**Comment by ephesused** [comment]
> @ephesused That sounds different, could you open a new ticket please?

Thanks. It's now https://github.com/docker/for-win/issues/5572 .

**Comment by ManfredLange** [comment]
Tried 2.2.0.0 a for a couple of days longer but have now decided to go back to version 2.1.0.5 until a patch is available for 2.2.0.0. 

In it's present form I'd say that the product is unusable for our environment.

Happy to try a new version once available.

**Comment by ManfredLange** [comment]
In case you are considering to go back to version 2.1.0.5, I'd recommend removing version 2.2.0.0, then reboot your windows box. Install 2.1.0.5 after the reboot only. I noticed that without the reboot I had the same issue with 2.1.0.5 as well.

If you are looking for the 2.1.0.5 installer, the link is https://download.docker.com/win/stable/40693/Docker%20Desktop%20Installer.exe (see this [comment](https://github.com/docker/for-win/issues/5530#issuecomment-577140248))

**Comment by theloveofcode** [comment]
I also had to downgrade every Windows developer on my team. 2.2.0.0 is unusable for daily development with this issue. (We are using it for Magento, so lots of very long file paths, in case that matters. We were also seeing the 1970 dates.)

**Comment by stephen-turner** [comment]
We have a new private build which (we believe) fixes this bug. https://download-stage.docker.com/win/stable/42579/Docker%20Desktop%20Installer.exe. Please try it and let us know how you get on.

**Comment by stephen-turner** [comment]
We have just released 2.2.0.3, which we believe fixes this issue, so closing this ticket. In case any Edge users are watching this ticket, it will be on the Edge channel tomorrow too.

**Comment by stevensnicole** [comment]
To update, 2.2.0.3 has fixed the day issues we were seeing against the indexes.
Many thanks.

**Comment by ManfredLange** [comment]
We've upgraded to version 2.2.0.3 and we are no longer seeing the issue.

@stephen-turner @stevensnicole Thank you for the great effort to get this resolved quickly! Keep up the good work!
