### ISSUE TITLE
Nodemon in legacy mode issue after upgrading to docker 2.2.0.0

### ISSUE THREAD

**Issue by ceottaki** [docker/for-win#5532]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
File system should not report files to have been changed if they haven't.

### Actual behavior
Nodemon reports files changing almost constantly, although no files have been touched.
This is at least while using Chokidar's polling method (nodemon -L). This issue is not present in Docker Desktop 2.1.0.5 (40693).

### Information

  - Windows Version: Windows 10 (Version 1903)
  - Docker Desktop Version: 2.2.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No.

**Comment by mat007** [comment]
Thank you for the report, am I right to think this is similar to #5528?

**Comment by ceottaki** [comment]
> Thank you for the report, am I right to think this is similar to #5528?

I did see that issue, but I am not entirely sure they're related, although they seem to be similar. I didn't experience that issue in particular, although my scenario is very similar to that one.

**Comment by stephen-turner** [comment]
I failed to reproduce this. Could you give more explicit instructions?

I ran `nodemon -L -V ...` inside the container, and then watched for `[nodemon]` lines on stdout. I edited files on the host file system and saw the lines, but I didn't see the lines when I wasn't editing files, which was the behaviour I was expecting.

By the way, what happens without -L under our new file sharing? I would expect the file changes to be noticed properly, in a way they wouldn't have been under Samba.

**Comment by ezk84** [comment]
@stephen-turner I've tested it without polling and it works as expected! 

There is a sporadic problem with inotify events propagation failing when nested mounts are involved that I'm trying to pin down and report though.

**Comment by ceottaki** [comment]
Apologies, I ended up not being able to test this without polling, as we were in the middle of a tight deadline so it was simpler to not upgrade to 2.2.0.0 right now. I will be able to test this without polling shortly as well.

Thanks!

**Comment by stephen-turner** [comment]
We have just released 2.2.0.3, which we believe fixes this issue, so closing this ticket. In case any Edge users are watching this ticket, it will be on the Edge channel tomorrow too.

@ceottaki If you do find it is still not fixed, please post here and I will reopen the ticket. Thank you.

**Comment by ceottaki** [comment]
Awesome, @stephen-turner , I've just tested this and it worked perfectly, thanks!
