### ISSUE TITLE
Container won't start after 2.2.0.0 - no such file or directory on bind mount

### ISSUE THREAD

**Issue by MJPA** [docker/for-win#5533]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Container to run and work

### Actual behavior

Container doesn't always run and errors in shell

### Information
Was working fine pre-2.2.0.0 update, now the container doesn't always start. Running with the following docker-compose.yml:

    node_image:
      image: node:12-alpine
      volumes:
        - ./app:/srv/app
      working_dir: /srv/app
      command: "npm start"

npm fails to run with "Error: ENOENT: no such file or directory, uv_cwd". I can manage to start the container via the dashboard, but opening the cli for it prints:

    sh: getcwd: No such file or directory
    (unknown) #

I can browse and view the files though. I have a feeling this is linked to the container not starting first time around...

  - Windows Version: 10
  - Docker Desktop Version: 2.2.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
See above docker-compose.yml

**Comment by lorddoumer** [comment]
are you using symlinks? I have noticed 2.2 on windows somehow don't recognize the symlinks working with 2.1 and therefore had to revert docker :(

**Comment by MJPA** [comment]
nope, no symlinks, just a regular folder with the app source code

had to revert to 2.1 because of this (and an events API bug that doesn't make sense...)

**Comment by rmlira** [comment]
I am having the same problem with a .net core application. The container runs but when I try to run docker exec -it xxxx /bin/bash it returns

```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
```

**Comment by mat007** [comment]
Thanks for you report, we were able to reproduce this issue on our end.

**Comment by codejnki** [comment]
I am seeing a similar issue when trying to run the Microsoft SQL Server 2017 or 2019 docker container and attempting to mount a volume to store data.  The container fails to start with a number of "Permission Denied" errors.  If we omit the volume mounting the container starts as expected.

**Comment by luastoned** [comment]
I see the same issue with nodemon, here is something I found in the logs:
`[15:44:14.932][GoBackendProcess  ][Info   ] time="2020-01-22T15:44:14+01:00" msg="rejecting access to file using non-canonical name nodemon (canonical name is nodemon.js)"`

**Comment by akulyk** [comment]
Got the same error
Find out that happens when 
```
   volumes:
    - ./apps/nodejs:/app
    - ./.env:/app/.env
    - ./.env:/app/backend/.env
    - ./.env:/app/frontend/.env
```
cant mount .env file from root project directory

**Comment by MJPA** [comment]
@mat007 cool, hopefully a quick fix + update released, the new dashboard is awesome but can't use it currently until this issue is fixed

**Comment by akulyk** [comment]
how to downgrade docker-desktop
?

**Comment by rmlira** [comment]
> how to downgrade docker-desktop
> ?

You have to uninstall current version, reboot machine and download an old release. I have made the download from: https://beta.docs.docker.com/docker-for-windows/release-notes/

I can't find other resource to download the previous engine.

**Comment by ManfredLange** [comment]
## Possible Workaround

In the past I found that volume or bind mounts in combination with alpine-based images on Windows hosts can at times cause problems with symbolic links (among others).

When I run into issues that "smell" like that, I typically test the same setup with a non-alpine base image and usually the problems go away. My (completely unfounded) hypothesis is that the drivers that come with alpine are not as sophisticated than the ones that come with other base images.

So in this case instead of using base image `node:12-alpine` perhaps using `node:12` works.

**Comment by stephen-turner** [comment]
We have a new private build that (we believe) fixes this bug. https://download-stage.docker.com/win/stable/42579/Docker%20Desktop%20Installer.exe. Please try it and let us know how you get on.

**Comment by majkinetor** [comment]
Doesn't seem to work for me. 

I noticed one strange thing - when I restart docker and run container very quickly it runs OK, then on subsequent run, it fails. If i restart docker and wait for 1 minute or so, it fails even the first time.

**Comment by stephen-turner** [comment]
We have just released 2.2.0.3, which fixes this issue, so closing this ticket. In case any Edge users are watching this ticket, it will be on the Edge channel tomorrow too.

**Comment by majkinetor** [comment]
It works now. Thx.

**Comment by snettah** [comment]
I've always the error in 2.2.0.3  

<img width="413" alt="Screenshot 2020-02-19 at 09 42 35" src="https://user-images.githubusercontent.com/10152935/74816838-35702680-52fc-11ea-95b8-6fd70e1c25a2.png">

```
app              | path.js:1077
app              |         path = process.cwd();
app              |                        ^
app              |
app              | Error: ENOENT: no such file or directory, uv_cwd
```
