### ISSUE TITLE
error while creating mount source path 

### ISSUE THREAD

**Issue by magistrator** [docker/for-win#5535]
Docker for Windows 10 
Desctop Version 2.2.0.0
Engine Version 19.03.5

after the latest update, I can't start my containers anymore 
I receiving this error 
```

ERROR: for unify-api  Cannot start service web: error while creating mount source path '/host_mnt/d/unifyprojects/unifyapi': mkdir /host_mnt/d/unifyprojects: file exists

ERROR: for web  Cannot start service web: error while creating mount source path '/host_mnt/d/unifyprojects/unifyapi': mkdir /host_mnt/d/unifyprojects: file exists
ERROR: Encountered errors while bringing up the project.

```
all my drives are shared 
( here you can see it http://joxi.ru/EA4BWoPTOveEBm )

here are docker-compose settings which cause a problem 
`
    volumes:
    - .:/home/www/app
`
what can I do to share my local drive or where I can find a logs to understand what goes wrong?

**Comment by lorddoumer** [comment]
with 2.2. docker has a problem with symlink - same folderstructure works perfect with 2.1 after I rolled back, maybe related?

**Comment by magistrator** [comment]
@lorddoumer yes, it could be related I think. and how to solve it? 

and how I can rollback my version on windows?

**Comment by pixelat3d** [comment]
Uninstall 2.2.0 and then reinstall using the link below (2.1.0.5)
`https://download.docker.com/win/stable/40693/Docker%20Desktop%20Installer.exe`

**Comment by magistrator** [comment]
@pixelat3d thanks! 
it solved my problem, I just hope in feature versions this issue will be solved

**Comment by swojdyga** [comment]
Why is this was closed?

This issue is still problem in newest versions.

Easiest way to test it is a create a very long path in mounted volume - then you will encounter errors such as "Function not implemented" etc.

Take it into consideration, please.

**Comment by mat007** [comment]
@swojdyga can you please open a fresh issue and provide some information (the version you’re running and if possible a diagnostics report)?
Thanks!
