### ISSUE TITLE
Windows 10 WSL 2 Node improperly joins Ubuntu/Windows

### ISSUE THREAD

**Issue by eshenayo** [docker/for-win#5555]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 90DA8A6A-6999-4242-BC35-B06CC2E41024/20200123002525

### Expected behavior
With windows firewall completely disabled and confirmed UDP/TCP ports 7946 and UDP 4789 open between all nodes. Testing WSL 2 in Linux container mode with Docker swarm. 
swarm init on ubuntu node as manager with 2 additional worker nodes - 1 windows, 1 ubuntu. I would expect that the overlay network lists all nodes by IP as peers and should allow all nodes to communicate via the overlay swarm network. 

### Actual behavior
* Initial swarm join from the WSL 2 node shows 2 IPs in the ingress network: that of the docker desktop and windows host
* node rm --force of the WSL 2 node, rejoin the swarm with --advertise-addr flag and windows host IP 
    * Windows docker desktop log shows reuse of deleted node ID, even though a new node ID is assigned for the worker:
```
REMOVAL:
# history | grep 'node rm'
  730  docker node rm gnrmrgnieof5u6zkcvfqabn0u
-->  760  docker node rm --force svtvpit24yhfo4va6ovi88e6e
  764  docker node rm --force caddq91rnsd69051049nt0s3i
  766  docker node rm 1gwheemjsxzb0fr1v8rhjs5p2
  768  docker node rm p4ivye9ijqz75565x3uihkyru

# docker node ls (EXAMPLE, LEFT OLD NODE TO SHOW ASSIGNMENT OF NEW IDs, SAME NAME):
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS      ENGINE VERSION
NEW NODE--> ezu4wkavseyiftdl76cafsaax     docker-desktop      Ready               Active                                  19.03.5
OLD NODE--> yi50fi8uu7wis1yg211yui11e     docker-desktop      Down                Active                                  19.03.5
1egbrd8e9o8lqq9cdi170115q *   portainer           Ready               Active              Leader              19.03.5
nodtufevjd4d21tqt2kb7mzy0     ubuntu-c8125        Ready               Active                                  19.03.5

```

```
IN LOG AFTER REMOVAL AND RE-ADD NODE:
[16:19:13.916][WindowsDaemon     ][Error  ] agent: session failed [node.id=svtvpit24yhfo4va6ovi88e6e error=rpc error: code = PermissionDenied desc = Permission denied: unauthorized peer role: rpc error: code = PermissionDenied desc = Permission denied: node svtvpit24yhfo4va6ovi88e6e was removed from swarm module=node/agent backoff=8s]
```
    * WSL 2 node joins the cluster with 'unknown' IP when address is specified 
```> docker network inspect --format '{{ .Peers }}' ingress
[{4acdd992f4e7 10.1.1.87} {73a12b6cfc9c 10.1.1.109} {e6c22c82ada1 unknown}]
```
    * WSL 2 node joins the cluster with docker-desktop IP from docker subnet (192.168.65.0/28)
```
> docker network inspect --format '{{ .Peers }}' ingress
[{4acdd992f4e7 10.1.1.87} {73a12b6cfc9c 10.1.1.109} {f9bd53d18529 192.168.65.3}]
```
* netstat on Windows host shows expected ports listening, but multiple TIME_WAIT:
```
netstat -a -n -b | findstr "4789" (removed multiple TIME_WAIT for brevity)
  TCP    10.1.1.103:7946        10.1.1.109:38190       TIME_WAIT
  TCP    10.1.1.103:7946        10.1.1.109:38192       TIME_WAIT
  TCP    10.1.1.103:7946        10.1.1.109:38194       TIME_WAIT
  TCP    10.1.1.103:54263       10.1.1.87:7946         TIME_WAIT
  TCP    10.1.1.103:54270       10.1.1.103:7946        TIME_WAIT
  TCP    10.1.1.103:54272       10.1.1.103:7946        TIME_WAIT
  TCP    10.1.1.103:54274       10.1.1.103:7946        TIME_WAIT
  TCP    10.1.1.103:54276       10.1.1.103:7946        TIME_WAIT
  TCP    10.1.1.103:54277       10.1.1.103:7946        TIME_WAIT
  TCP    10.1.1.103:54279       10.1.1.103:7946        TIME_WAIT
  TCP    10.1.1.103:54280       10.1.1.109:7946        TIME_WAIT
  TCP    10.1.1.103:54281       10.1.1.103:7946        TIME_WAIT
  TCP    10.1.1.103:54284       10.1.1.103:7946        TIME_WAIT
  TCP    10.1.1.103:54285       10.1.1.103:7946        TIME_WAIT
  TCP    10.1.1.103:54287       10.1.1.103:7946        TIME_WAIT
  TCP    10.1.1.103:54294       10.1.1.103:7946        TIME_WAIT
  TCP    10.1.1.103:54295       10.1.1.103:7946        TIME_WAIT
  TCP    10.1.1.103:54297       10.1.1.103:7946        TIME_WAIT
  TCP    10.1.1.103:54299       10.1.1.103:7946        TIME_WAIT
  TCP    10.1.1.103:54300       10.1.1.103:7946        TIME_WAIT
  TCP    10.1.1.103:54302       10.1.1.103:7946        TIME_WAIT
  TCP    10.1.1.103:54304       10.1.1.103:7946        TIME_WAIT
  TCP    10.1.1.103:54307       10.1.1.103:7946        TIME_WAIT
  TCP    10.1.1.103:54310       10.1.1.87:7946         TIME_WAIT
  TCP    10.1.1.103:54324       10.1.1.109:7946        TIME_WAIT
  TCP    10.1.1.103:54338       10.1.1.109:7946        TIME_WAIT
  TCP    [::]:7946              [::]:0                 LISTENING
  UDP    0.0.0.0:7946           *:*
  UDP    [::]:7946              *:*
``` 
* services deployed on the cluster are created on the WSL 2 instance
```
# docker service ls
ID                  NAME                  MODE                REPLICAS            IMAGE                        PORTS
xp8djmilovkh        portainer_agent       global              3/3                 portainer/agent:latest
otburlqquk3k        portainer_portainer   replicated          1/1                 portainer/portainer:latest   *:8000->8000/tcp, *:9000->9000/tcp
# docker service ps portainer_agent
ID                  NAME                                        IMAGE                    NODE                DESIRED STATE       CURRENT STATE                ERROR               PORTS
mgypgfl11ebr        portainer_agent.ezu4wkavseyiftdl76cafsaax   portainer/agent:latest   docker-desktop      Running             Running about a minute ago                     
tngohhhajbhv        portainer_agent.yi50fi8uu7wis1yg211yui11e   portainer/agent:latest   docker-desktop      Shutdown            Running 2 minutes ago                          
yxii310tc1z9        portainer_agent.nodtufevjd4d21tqt2kb7mzy0   portainer/agent:latest   ubuntu-c8125        Running             Running about an hour ago                      
ztbx9mplsh0g        portainer_agent.1egbrd8e9o8lqq9cdi170115q   portainer/agent:latest   portainer           Running             Running 6 days ago  
```
### Information
Docker swarm created with 3 nodes:
* manager: ubuntu 18.04
* worker: ubuntu 18.04
* worker: windows WSL 2 docker desktop

  - Windows Version: Windows 10 Pro 19035.1.amd64fre.vb_release.191126-1316
  - Docker Desktop Version: 19.03.5, build 633a0ea
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

Prereq: 2 Ubuntu and 1 Windows with WSL 2 enabled

  1. On Ubuntu Manager: docker swarm init --advertise-addr <IP>; docker swarm join-token worker
  2. On Ubuntu and Windows workers: docker swarm join --advertise-addr <worker IP> --token <join-token>
  3.  On WSL 2 node: docker swarm leave --force
  4. On Ubuntu Manager: docker node rm <id of docker-desktop>
  5. On WSL 2 node: docker swarm join --advertise-addr <worker IP> --token

**Comment by simonferquel** [comment]
Hi, this scenario is not supported, and furthermore, you should not run docker (or/and swarm) directly within WSL, especially concurrently in different distro.
The reason for that is that every WSL distro share the same network namespace, and running concurrently multiple docker daemon might completely break networking in your WSL distros (they might create conflicted ip tables rules etc.).

That is why we create our own network/pid/mount namespace to run Docker with Docker Desktop.

**Comment by eshenayo** [comment]
Hello @simonferquel I must not have been clear in framing the issue. I have Docker Desktop running, and joined with 'Linux containers' when I joined the windows node to the swarm with the goal to manage Linux containers on the Windows host using Docker Desktop. Are you saying that  only Windows Containers are supported using Docker Desktop with swarm? I was following this guide: https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/swarm-mode

**Comment by simonferquel** [comment]
Indeed, I misunderstdood a bit.
So it is still an unsupported scenario at the moment: swarm is only supported in single node mode on Docker Desktop linux containers.

I am not entirely sure that all networking scenarios work with swarm / windows containers on windows 10 client as well.
