### ISSUE TITLE
Cannot turn off autostart if HW-virt is disabled. (GUI oversight)

### ISSUE THREAD

**Issue by AnorZaken** [docker/for-win#5558]
If hardware virtualization is disabled, you get an error every time you start docker.
If start with windows is enabled, you get this error every time you computer starts.

All settings are grayed out while the error is displayed (because "Docker is starting...").
App and settings close when you close the error, thus autostart cannot be disabled.

I'm sure I can find the autostart in the registry, or by other means, and fix it that way...
But this is a GUI oversight nonetheless, so I figured it's worth reporting.

**Comment by AnorZaken** [comment]
Not sure what approach would be more elegant, but most reasonably some settings should not be grayed out even in a starting state, i.e. all settings that does not affect running behavior (maybe that's just this setting?).

**Comment by AnorZaken** [comment]
Or there could be an option to disable autostart in the error messagebox itself, but maybe that's too wonky?

_(Comment split in two so people can react to the two parts separately.)_

**Comment by mat007** [comment]
Thanks for the feedback, this is indeed a great UX improvement suggestion!

You don’t actually have to fiddle with registry keys as the auto-start can be disabled from the Windows Startup Apps panel, but I agree it’s not super obvious and we could probably add a message with a link to open the panel in the error window?

![image](https://user-images.githubusercontent.com/2386884/72966783-05e30280-3dc0-11ea-8b50-b883344b4920.png)
