### ISSUE TITLE
Running cordova build fails with invalid framework identity error

### ISSUE THREAD

**Issue by bikashmishra100** [docker/for-win#556]
Docker version
```
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   32697b5
 Built:        Thu Feb  2 06:23:31 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.14.0-dev
 API version:  1.26 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   32697b5
 Built:        Thu Feb  2 06:23:31 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

I installed visual studio 2015 community edition with the xml file [admin.txt](https://github.com/docker/for-win/files/821915/admin.txt) and installed windows SDK 10 in the docker container.

When i run cordova build --archs=x64, it fails with below error.
```
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1818,5): error APPX0404: Invalid framework identity 'Name = Microsoft.VCLibs.120.00.Debug, MinVersion = 12.0.21005.1'. It is expected to have three parts delimited by a comma. [C:\workspace\platforms\windows\CordovaApp.Windows10.jsproj]
```

The verbose msbuild logs are attached [build.txt](https://github.com/docker/for-win/files/821922/build.txt).

**Comment by friism** [comment]
I don't think this is a bug with Docker or Docker for Windows. To get help using Docker, please start a thread on the forums: https://forums.docker.com/c/docker-for-windows
