### ISSUE TITLE
Unable to access containers on 10.0.75.2

### ISSUE THREAD

**Issue by IanIsFluent** [docker/for-win#5560]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C55CB553-66AB-4C4B-9B85-44857181FD90/20200123085312

Docker Version 2.2.0.0 (42247).
Windows Version 10.0.18362 Build 18362.

### Expected behavior
I can access my containers on http://10.0.75.2:xxxx as I used to be able to in version .

### Actual behavior
I get `This site can’t be reached 10.0.75.2 took too long to respond. ERR_CONNECTION_TIMED_OUT.`

As a side note - in the troubleshooting documentation, networking section, step 3. Ensure DockerNAT is enabled by checking the Virtual Switch Manager on the Actions tab on the right side of the Hyper-V Manager. Isn't very helpful, as the `Virtual Switch Manager...` button contains no mention of a Docker NAT - and the troubleshooting instructions don't mention what to do in that case.

**Comment by mat007** [comment]
This looks like the same as #5538 ?

**Comment by IanIsFluent** [comment]
Thanks @mat007 ! That looks super-similar. And explains my confusion re: Docker NAT not being there - the docs are clearly incorrect!

This is _slightly_ different only in that we're trying to use an ip rather than localhost (10.0.75.2) to access the containers. It certainly seems like it'll be the same underlying issue, though. Thanks, I couldn't find the issue by searching (I did try!!).

**Comment by IanIsFluent** [comment]
Yeah, I've downgraded to 2.1 and 10.0.75.2 is working again (and I can see Docker NAT - the thing the docs don't tell you how to fix if its missing!)

I realise its impossible to please everyone all the time, but a 'breaking change' notice that the Docker NAT is going away and 10.0.75.2 won't respond any more in the release notes would have been amazing 😄.

**Comment by mat007** [comment]
I understand your pain, sorry about this and thank you for taking it that great!
We were pretty sure DockerNAT was an internal implementation detail that was safe to get rid of, but obviously we were wrong…
We’re currently weighting the options about what to do next.

**Comment by IanIsFluent** [comment]
No problem, as I said here, it did seem like we were relying on something not mentioned in the docs (much) - making us a bit this guy: https://xkcd.com/1172/ 😆
