### ISSUE TITLE
Unable to create Hyper-V VM: Hyper-V

### ISSUE THREAD

**Issue by pratheeban15** [docker/for-win#5563]
Unable to create Hyper-V VM: Hyper-V encountered an error trying to access an object on computer 'IE6CLTGX3S0X2' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-MobyLinuxVM, <No file>: line 388
at New-MobyLinux, <No file>: line 182
at <ScriptBlock>, <No file>: line 810

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass30_0.<ResetToDefault>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

**Comment by nestoralonsovina** [comment]
Having the same issue. Anyone found a solution?

**Comment by jwang5237** [comment]
Having the same issue.  Anyone found a solution?

**Comment by andy1024** [comment]
I'm facing the same issue. It happened just after an automated Windows 10 update.

**Comment by jwang5237** [comment]
I ran the following command in PowerShell as an Administrator:
```
MOFCOMP %SYSTEMROOT%\System32\WindowsVirtualization.V2.mof
```
and Docker Desktop started up correctly

**Comment by andy1024** [comment]
Yes, that seems to do the job as more people used it successfully. Thanks @jwang5237

**Comment by rkasn** [comment]
facing the same issue.
Ran MOFCOMP %SYSTEMROOT%\System32\WindowsVirtualization.V2.mof, still having the same issue

**Comment by lfournial** [comment]
Same issue for me.
@jwang5237 solution works fine for me 
> MOFCOMP %SYSTEMROOT%\System32\WindowsVirtualization.V2.mof
