### ISSUE TITLE
Check for updates doesn't suggest latest version

### ISSUE THREAD

**Issue by NotMyBestWork** [docker/for-win#5568]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: EEA7F2AB-C104-417A-B3CF-F3955B82CB3A/20200123125138

### Expected behavior
Check for updates > receive a prompt for a latest version (2.2.0.0)

### Actual behavior
Says I'm on latest version
![](https://i.gyazo.com/d8895498f0374af4b3b97b409ee3cb53.png)

### Information

  - Windows Version: Microsoft Windows 10 Pro, 10.0.18362 N/A Build 18362
  - Docker Desktop Version: 2.1.0.5
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: **No**
  - Running `docker run hello-world` works fine:
> Hello from Docker!
> This message shows that your installation appears to be working correctly.
  - No proxies in my network, no proxy is configured in settings

### Steps to reproduce the behavior

  1. ...
  2. ...
[log.txt](https://github.com/docker/for-win/files/4103150/log.txt)

**Comment by csuzw** [comment]
I've got the same behaviour.  In the last couple of days I was getting notifications saying there was an update but as I didn't want to update at the time I chose the remind me later option.  Now that I want to update, it no longer seems to be an option.

**Comment by nebuk89** [comment]
Thanks for the report. We've had a higher than usual number of issues reported on https://github.com/docker/for-win/ so we've decided to pause the update notification until we've had a chance to triage them. 

If you want to upgrade immediately, the new version is still available for download at https://download.docker.com/win/stable/Docker%20Desktop%20Installer.exe.

**Comment by NotMyBestWork** [comment]
Ah, alright, thanks for the info

**Comment by nebuk89** [comment]
Sadly it will be another full update when we get the fix out, this was part of the reason we decided to pause the roll out to not cause everyone to have to download 1GB twice when we get the fixes ready in the next few days.

**Comment by NotMyBestWork** [comment]
Thanks for the info, appreciated.
