### ISSUE TITLE
SQL Server DB file cannot be removed upon completion of integration test

### ISSUE THREAD

**Issue by redhedjim** [docker/for-win#5575]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 2DE52831-65DB-45B2-AE10-1C6A0C4EF791/20200123180024

### Expected behavior
Once an integration test started by Visual studio is finished, c# should delete the DB file.

### Actual behavior
The attempt to delete the temp DB file throws an error
**Edit** This only began once the update to 2.2.0.0 was made.
```
System.Data.SqlClient.SqlException : Could not delete file '/tmp/WMLEOT-DT_7BD66FB6326540198269DCBB14CA0353_TestDbInstance.mdf'. See the SQL Server error log for more information.
Could not delete file '/tmp/WMLEOT-DT_46C5238FABE24DD3A8B06C2710A00946_TestDbTemplate_log.ldf'. See the SQL Server error log for more information.
```
Once the test fails I can remove the DB file manually.

### Information

  - Windows Version: Windows 10 Version 10.0.17134 Build 17134
  - Docker Desktop Version: 2.2.0.0

### Steps to reproduce the behavior

1. C# code running on host creates a database file in the mounted directory and issues ATTACH command to the SQL Server running in Docker container over SQL connection
2. SQL Server ATTACH-es this mounted file as a database; SQL Server locks the mounted file using read/write file handle; filesystem server talks to filesystem client that locks the actual file on host
3. C# code running on host runs test
4. C# code running on host issues DETACH command to the SQL Server over SQL connection
5. SQL Server asks filesystem to release the file lock on the mounted file; filesystem server starts to notify the client that handle has been released but doesn't wait for completion; filesystem tells SQL Server that file lock has been released; SQL Server notifies C# code over SQL connection that database has been DETACH-ed
6. C# code tries to delete the database file on host, but the filesystem client still holds a lock on the file because gRPC notification has not arrived yet;

**Comment by stephen-turner** [comment]
This is fixed in 2.2.0.4.
