### ISSUE TITLE
Cannot connect to localhost (port 80 and 443) from a docker container

### ISSUE THREAD

**Issue by mdekoster** [docker/for-win#5576]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 62C194B8-1BA8-4ADD-BCF2-AD66E769E55B/20200123192531

### Expected behavior
Running wget from de WSL2 Ubuntu 18.04 host:
```
$ wget http://localhost
--2020-01-23 20:32:48--  http://localhost/
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:80... connected.
```

### Actual behavior
Running wget from within a busybox container:
```
$ docker run -it busybox /bin/sh
/ # wget http://localhost
Connecting to localhost (127.0.0.1:80)
wget: can't connect to remote host (127.0.0.1): Connection refused
```
### Information

  - Windows Version: Windows 10 Insider (build 19546)
  - Docker Desktop Version: 2.1.7.0 (41536) edge
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Running inside WSL2 Ubuntu 18.04

### Steps to reproduce the behavior

See expected and actual behavior

**Comment by simonferquel** [comment]
Hi, your container runs in its own network namespaces. To reach the host, please use http://host.docker.internal.

**Comment by mdekoster** [comment]
Thanks for the quick response.

Some additional information of the problem I try to solve:

I have created an application on kubernetes in docker-for-desktop and use an nginx ingress on top of it. From the windows host I can connect to that application over port 443 (the hosts file on windows has an entry for the domain name to 127.0.0.1). From the WSL2 Ubuntu the application is also reachable over port 443 (/etc/hosts also has an entry for the domain name to 127.0.0.1). How can I reach the application from a docker container (which contains a client of the application running in kubernetes)?

**Comment by simonferquel** [comment]
It should work as well. We have a end server that resolves host.docker.internal correctly so that you can connect to a port on your host machine from a container.
