### ISSUE TITLE
Windows containers run: The file name is too long. (0x6f).

### ISSUE THREAD

**Issue by shirl3y** [docker/for-win#5577]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 9DEEAB0F-9002-4A16-98F4-8D9A3C983B3B/20200123043949

### Expected behavior
To be able to run windows hello-world container. It also fails for other docker images, but I'd expect to at least be able to run hello-world

### Actual behavior
```
C:\windows\system32>docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
ee446884f7be: Pull complete                                                                                             
8b4475a48151: Pull complete                                                                                             
7c57688e630a: Pull complete                                                                                             
Digest: sha256:9572f7cdcee8591948c2963463447a53466950b3fc15a247fcad1917ca215a2f
Status: Downloaded newer image for hello-world:latest
docker: Error response from daemon: container de51b24a8c04cb47ba265ce204126a4609baa2657f95d079f8450d9ca451729f encountered an error during Start: failure in a Windows system call: The file name is too long. (0x6f).
```

### Information

  - Windows Version: Windows 10 Enterprise Version 1909 (OS Build 18363.592)
  - Docker Desktop Version: 19.03.5
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

- It seems to be a new issue, but I'm not sure what version of docker I was on previously.

### Steps to reproduce the behavior

  1. Reset Docker Desktop to factory defaults
  2. docker run hello-world

### Other useful information
It looks like some of the default files in the windows image are too long. For example,
`C:\ProgramData\Docker\windowsfilter\c9c2561d13347c01c45846eba2c7001f093dcf17d73daefac190d4850d681c6b\Files\Windows\System32\CatRoot\{F750E6C3-38EE-11D1-85E5-00C04FC295EE}\Microsoft-Windows-Services-ServiceController-ServerOS-Package~31bf3856ad364e35~amd64~~10.0.17763.973.cat`

output of `docker version`

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:36:50 2019
  OS/Arch:          windows/amd64
  Experimental:     true
```

output of `docker info`
```
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., v0.3.1-tp-docker)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 1
 Server Version: 19.03.5
 Storage Driver: windowsfilter (windows) lcow (linux)
  Windows:
  LCOW:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 18363 (18362.1.amd64fre.19h1_release.190318-1202)
 Operating System: Windows 10 Enterprise Version 1909 (OS Build 18363.592)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.83GiB
 Name: <machine name>
 ID: TRMA:YEWZ:5L4P:5WBS:2TRM:PIJN:Z32U:I7LU:FMPC:WOEN:I7QP:UWRU
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 30
  System Time: 2020-01-23T12:35:51.6041135-08:00
  EventsListeners: 2
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine```

**Comment by shirl3y** [comment]
Here is a snippet of the log file when running `docker run hello-world`

[log1.txt](https://github.com/docker/for-win/files/4105894/log1.txt)

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place.
Thanks!
