### ISSUE TITLE
Docker hangs on start

### ISSUE THREAD

**Issue by getglad** [docker/for-win#558]
### Expected behavior
Docker would complete the start up process successfully

### Actual behavior
Docker hangs during start up - does not crash, but just appears stuck in start up process.

### Information

Win10 Pro - was successfully running docker until today (first time I have started it back up on this machine post update). I am also prevented from restarting normally while Docker is stuck in the start up mode.

Diagnostic report: B3D9ADCA-8C10-41BC-8C5D-F68AC1AE6062/2017-03-06_22-46-29

I tried killing the Docker.Service task  and got the below:

Binary stream '0' does not contain a valid BinaryHeader. Possible causes are invalid stream or object version change between serialization and deserialization.
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.WPF.BackendClient.Start()
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass16_0.<Start>b__0()
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1()

Crash report: B3D9ADCA-8C10-41BC-8C5D-F68AC1AE6062/2017-03-06_22-50-20

**BUT** if I kill Docker for Windows task, but leave Docker.Service running and then restart Docker for Windows, I first get a 'failed to start' error and then Docker starts and seems to be running normally.

Happy to test/try anything to help drill down on the issue.

**Comment by don-lab-dc** [comment]
Same problem. 

For windows docker beta: A diagnostic was uploaded with id: 9F4E49DB-A39C-4D5F-875F-6AD44ABF2EE1/2017-03-09_11-29-16

For windows docker stable: A diagnostic was uploaded with id: 9F4E49DB-A39C-4D5F-875F-6AD44ABF2EE1/2017-03-09_12-20-47

**Comment by cle-ros** [comment]
I had the very same issue, and the following helped. I can't fully explain it, since I am not particularly familiar with the details of these virtualization techniques, but it looks to be a problem with Hyper-V:

1. uninstall docker
2. disable Hyper-V
3. restart
4. reinstall docker
5. docker will complain that Hyper-V is not enabled. Let docker enable it for you, and then restart

Again, I don't fully understand what's going on, but maybe this does help you, too.

**Comment by getglad** [comment]
Little late to respond, but can firm that seems to be a consistent fix

**Comment by makosblade** [comment]
This fix also worked for me

**Comment by yhilem** [comment]
This fix doesn't work for me :

Win10 Pro - was successfully running docker until today.

Docker CE for windows 
Version 17.06.0-ce-win18 (12627)
Channel: stable
d9b6651

Failed to start :

Le flux binaire '0' ne contient pas de BinaryHeader valide. Les raisons possibles sont un flux non valide ou une modification de la version de l'objet entre la sérialisation et la désérialisation.
   à Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   à Docker.WPF.BackendClient.Start()
   à Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   à Docker.Actions.<>c__DisplayClass16_0.<Start>b__0()
   à Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1()

**Comment by armas77** [comment]
Same issue here!
And the solution gave by cle-ros , didn't work for me.

Crash report diagnostic id:
2D754CA1-D8AE-48CF-96DF-A78B63CE864D/2017-07-07_10-36-20

**Comment by ThomasBouman** [comment]
Another one here:

9C89DB19-6A5C-405A-95F0-A698248545E9/2017-07-13_16-11-59

**Comment by sudhirtumati** [comment]
Another diagnostic id:

FC811971-D853-43BD-A32F-C845AF0B711C/2017-07-21_23-33-33

**Comment by tolkonepiu** [comment]
Same issue:
8A6DBB00-A1B2-49B4-958B-9C32FC48C5DC/2017-07-23_23-11-22

**Comment by tolkonepiu** [comment]
Solve this issue. **Reinstall** File and Printer Sharing for Microsoft Networks from the **vEthernet (DockerNAT)** network adapter.

**Comment by ThomasBouman** [comment]
I had to install this (not reinstall), but after that it worked. Thanks @tolkonepiu

**Comment by bjdx** [comment]
@tolkonepiu Thank you for this, I tried everything I could think of but this fixed it straight away. 

Network and Sharing Center -> Change adapter settings -> vEthernet (DockerNAT) -> Right Click ->  Properties -> Install... -> Service -> Add.. ->Manufacturer: Microsoft -> File and Printer Sharing for Microsoft Networks -> OK

Then stop the failed docker and restart it.   *sigh of relief*

**Comment by VampireDaniel** [comment]
works for me by using tolkonepiu's solution

**Comment by PierreOlivierG33** [comment]
Cle-Ros solution also works for me

**Comment by johnmiroki** [comment]
cle-ros's solution doesn't work for me (win 10 pro pre-release + 17.12.0-ce-win46)

**Comment by sandangel** [comment]
I could not find File and Printer Sharing for Microsoft Networks as @bjdx has suggested, and when I try to install any program in Network Service, I received an error: This program is blocked by group policy.

I'm using Windows 10 Education Insider Preview 17093

**Comment by mi-hol** [comment]
fixed in Windows build 17107.1000

**Comment by milewski** [comment]
if you happen to have Astrill VPN installed on your machine.. uninstall it.. this was the reason why i was getting this `Binary stream '0' does not contain ....` error..

**Comment by abdeneve** [comment]
@bjdx thank you very much, this made me

@tolkonepiu Thank you for this, I tried everything I could think of but this fixed it straight away.

Network and Sharing Center -> Change adapter settings -> vEthernet (DockerNAT) -> Right Click -> Properties -> Install... -> Service -> Add.. ->Manufacturer: Microsoft -> File and Printer Sharing for Microsoft Networks -> OK

**Comment by naveenmajumdar** [comment]
i am facing the same 
FD1D8D67-5222-4ACC-A805-30558C61AEB2/20180726163535

**Comment by naveenmajumdar** [comment]
this fix worked 

Network and Sharing Center -> Change adapter settings -> vEthernet (DockerNAT) -> Right Click -> Properties -> Install... -> Service -> Add.. ->Manufacturer: Microsoft -> File and Printer Sharing for Microsoft Networks -> OK
