### ISSUE TITLE
Start of Docker Desktop fails with error message "Unable to create Hyper-V VM: [...]"

### ISSUE THREAD

**Issue by ChrisAlexB** [docker/for-win#5583]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 01D230AF-A6A1-4CFD-8CE2-88B15911F24E/20200124124802

### Expected behavior
* Docker Desktop starts up normally and can be used

### Actual behavior
* Startup terminates with error message (original computername containing letters and digits only replaced with XXX)

```
Unable to create Hyper-V VM: Hyper-V encountered an error trying to access an object on computer 'XXX' because the object was not found. The object might have been deleted, or you might not have permission to perform the task. Verify that the Virtual Machine Management service on the computer is running. If the service is running, try to perform the task again by using Run as Administrator.
at New-MobyLinuxVM, <No file>: line 397
at New-MobyLinux, <No file>: line 182
at <ScriptBlock>, <No file>: line 810

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass30_0.<ResetToDefault>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()
```

### Information

  - Windows Version: Windows 10 Enterprise Version 10.0.17763
  - Docker Desktop Version: 2.2.0.0 (42247) - downloaded today (24th Jan 2020)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no. 
  - error is reproducible and occurs during every start (start as normal user and start via "run as administrator")
  - End of last year, docker desktop worked. This year, it doesn't. Usual automatic windows updates have been applied. Other changes in configuration are not known to me
  - windows features under "Hyper-V" are on
  - hyper-V manager does not show any virtual machines
  - WindowsVirtualization.V2.mof has been re-compiled with MOFCOMP
  - Service "Hyper-V Virtual Machine Management" is running

### Steps to reproduce the behavior

  1. Start Docker Desktop
  2. Read the error message

**Comment by jwinkt** [comment]
I have the similar environment and result except that my Windows Version is Windows 10 Enterprise Version 1909 (OS Build 18363.592).  See below

`Unable to create Hyper-V VM: The operation failed.

An unexpected error occurred: Logon failure: the user has not been granted the requested logon type at this computer. (0x80070569).

The operation failed.

The Hyper-V Virtual Machine Management service encountered an unexpected error: Logon failure: the user has not been granted the requested logon type at this computer. (0x80070569).
at New-MobyLinuxVM, <No file>: line 397
at New-MobyLinux, <No file>: line 182
at <ScriptBlock>, <No file>: line 810

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()
`

**Comment by driouxg** [comment]
Here's a couple of links reporting similar issues: [](https://stackoverflow.com/questions/53659856/docker-for-windows-logon-failure) and [](https://github.com/docker/for-win/issues/1056). In short, try opening Power Shell and executing `gpupdate /force`. If the command executes successfully, restart your computer and open docker for desktop as admin.

**Comment by ChrisAlexB** [comment]
Thanks @driouxg, I tried all that but the original issue is still there - Docker Desktop is not starting with the same error message

**Comment by nestoralonsovina** [comment]
Same problem here, anyone found a solution?

**Comment by NYMEZIDE** [comment]
Same problem

Windows 10 v 1903 (18362.418)
Docker from 2.2.0.0 to 2.2.0.4. 

May be KBxxxxx Update for WIndows bring in this problem?

**Comment by jagretz** [comment]
The original post is a different error from what @jwinkt posted. For this see the comment I added on [issues/6068](https://github.com/docker/for-win/issues/6068#issuecomment-607783290)

**Comment by dprestegard** [comment]
I have this issue often, also on Windows 10 Enterprise 17763 (outside my control sadly).

I've found that it happens when I don't log in quickly after rebooting. I imagine it's a conflict with some of the spyware crap my company has on my work laptop. The good news is, the workaround is simple, reboot and log in right away :D

**Comment by christianhuening** [comment]
Did you by any chance set custom paths in the Hyper-V settings? I had moved the default folder for virtual disks and VMs to another drive, then forgot about it and in a cleanup deleted those folders. This caused initially reported issue. I looked into my hyper-v settings and recreated the folder I configured, then it started to work again.

**Comment by dprestegard** [comment]
Nope. No custom paths.

**Comment by richardgragasin** [comment]
any updates? im having the same issue
