### ISSUE TITLE
Not able to install on windows 10 enterprise edition

### ISSUE THREAD

**Issue by amarendrayadav** [docker/for-win#5585]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 108D8BE6-4648-4CB6-A4B8-7EE87ADBD79A/20200124143509

### Expected behavior
Should run on Windows 10
### Actual behavior
Does not run
### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by amarendrayadav** [comment]
diagnostic Id : 108D8BE6-4648-4CB6-A4B8-7EE87ADBD79A/20200124143509

**Comment by deathpax** [comment]
I just experienced the same thing.

- Windows 10 Enterprise 64-bit 10.0, Build 16299
- Docker Desktop Version 2.2.0.0 (42247) stable
- Diagnostic id: 5FBEDD01-BC6C-4031-948B-EDFFFFC15E71/20200124165512

**Comment by amarendrayadav** [comment]
I found the solution to the problem
Check whether you are able to create Hyper-V using quick create? If not follow - [this](https://social.technet.microsoft.com/Forums/en-US/900298bd-4a86-4c9d-9950-11f0c050fa2f/hyperv-manager-unable-to-connect-to-server-quotlocal-computerquot?forum=win10itprovirt) then re start your system and try reinstalling docker again
