### ISSUE TITLE
Crash at startup (failed to start daemon: Error initializing network controller)

### ISSUE THREAD

**Issue by AlessandroBorges** [docker/for-win#5596]
- [ X] I have tried with the latest version of my channel (Stable or Edge) 
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID:  13B955C8-5C05-45D4-AA87-E5470625B11A/20200125140656

### Expected behaviour
Application startup

### Actual behaviour
Application crash at startup, after a fresh install

### Information
Error message from Event Viewer:

fatal: failed to start daemon: Error initializing network controller: Error creating default network: hnsCall failed in Win32: Element not found. (0x490)

Diagnostic ID 13B955C8-5C05-45D4-AA87-E5470625B11A/20200125140656

  - Windows Version: **Microsoft Windows [versão 10.0.18362.592]**
  - Docker Desktop Version:  **2.2.0.0 (42247)** 
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: **NO**

### Steps to reproduce the behavior
fresh install it and try to run.

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place.
Thanks!
