### ISSUE TITLE
Getting BSOD 0X1CA "SYNTHETIC_WATCHDOG_TIMEOUT" when docker is using 60% to 80% of CPU

### ISSUE THREAD

**Issue by Osodarck** [docker/for-win#5597]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D3E0D259-7E89-4291-AD97-BB82DFA98E95/20200125174231

### Actual behavior
Windows 10 PRO  getting BSOD 0X1CA "SYNTHETIC_WATCHDOG_TIMEOUT" error when docker is using 60% to 80% of CPU 
### Information

  - Windows Version: Windows 10 PRO
  - Docker Desktop Version: 2.2.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

**Comment by Venjakosov** [comment]
Struggling to fix 0x1ca bluescreen for a week. Deleted everything, fixed all I could, but it didn't help. Thank you, trying to remove docker container from computer! Works fine right now
