### ISSUE TITLE
WSL2: The pipes are being closed

### ISSUE THREAD

**Issue by LaravelFreelancerNL** [docker/for-win#5607]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: DA56DBE1-43A5-476A-944E-56A5EA7940A5/20200127085035

### Expected behavior
For docker desktop to see the running containers within WSL2

### Actual behavior
Docker desktop sees the containers with exited (255) status. Eventhough they are running within WSL2

If I try to start them manually, which succeeds for all but the nginx container, I get separate instances.

The log file shows a lot of 'The pipes are being closed errors.'
time="2020-01-27T09:45:12+01:00" msg="error CloseWrite to: De pipes wordt gesloten."

### Information
This happens regularly but not always, after a reboot.

  - Windows Version: 19551
  - Docker Desktop Version: Edge 2.1.7
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

#5571 This is the point where I reset the settings to defaults and try again.

### Steps to reproduce the behavior
- Rebooting will trigger this regularly but not always.

**Comment by simonferquel** [comment]
Per any chance, do you have containers in auto-restart mode with bind mounts ? We have a few remaining issues with this scenario with the wsl2 backend.

**Comment by LaravelFreelancerNL** [comment]
Not consciously. Two containers (nginx, php) have bind mounts, but none have a manually set restart policy in the docker-compose.yml. 

Docker index doesn't contain restart policy info for either of the containers.

Perhaps it's a default? 
I'll manually set it to no when this happens again and see if it makes a difference

**Comment by simonferquel** [comment]
There might be a larger issue there. But I really think it is related to a race we have between our wsl backend and the integration agent bind mount restoration code.
When you encounter the issue, `docker-compose down && docker-compose up` should bring everything back to normal.

**Comment by LaravelFreelancerNL** [comment]
> When you encounter the issue, `docker-compose down && docker-compose up` should bring everything back to normal.

Unfortunately it doesn't. After the issue returned this morning I tried those options but to no avail.
A reset to factory defaults and a consequent rebuild of the images, reboot etc got it up and running again.
Sometimes the reset to factory defaults crashes, in which case I have to reinstall Docker Desktop.
The last time that happend was about a month ago in the same version of Docker Desktop Edge

**Comment by simonferquel** [comment]
Ok, I was able to reproduce the issue. I thought only auto-restart containers were impacted, but actually all containers trigger the issue. 

I'll write a mitigation for the next release that will make `docker-compose down && docker-compose up` work, but unfortunately fixing the root cause of the issue (so that just restarting the containers work) will take some time.

**Comment by LaravelFreelancerNL** [comment]
Cool! A quick work around is great for now.

Here is some other info that might help:
What sometimes happen is that the WSL2 docker and Docker Desktop both have, different, running instances of the same docker-compose environment.  

Connecting from the host to a DB will show a different instance then connecting to 'that' DB container from within WSL2

**Comment by simonferquel** [comment]
This error is definitely related to Mount points. Something that should work before the mitigation hits a release is: 
- `docker-compose down`: will remove all the containers that cause issues
- Stop docker-desktop
- from your wsl distro `sudo rm -rf /mnt/wsl/docker-desktop-bind-mounts/<Your Distro Name>`: this will remove any garbage docker has created in place of actual bind mounts
- Start docker-desktop
- `docker-compose up`.

**Comment by LaravelFreelancerNL** [comment]
Did you just make me happy twice within 30 minutes? Thanks Simon!
I'll try it next time and keep you posted.
