### ISSUE TITLE
kubernets is starting like forever

### ISSUE THREAD

**Issue by godhelpjun** [docker/for-win#5608]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by godhelpjun** [comment]
Diagnostics ID: C1631F6E-2BC6-48DF-B8B8-DBA12368104B/20200127102526

**Comment by mat007** [comment]
Duplicates #5609
