### ISSUE TITLE
After the recent update of Docker Desktop (2.2.0.0 42247) docker randomly unmounts my symlinks volumes

### ISSUE THREAD

**Issue by catalin560** [docker/for-win#5611]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 6B4E1634-1F06-4E63-B2B8-79D564758F80/20200127154126

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by JamesG-DPharos** [comment]
Confirmed here as well. A co-worker just ran into this exact same problem. Win 10 / Docker (2.2.0.0 42247). Files will only synchronize when the container starts for the first time.

**Comment by Lucile-Besse** [comment]
Same here, we are 2 with same troubles. Others are waiting before update because it's almost impossible to work. Do you have any solution ?

**Comment by mat007** [comment]
This is likely a variant of #5582 for which we have a fix ready, it will be released soon.
Sorry for the inconvenience.

**Comment by JamesG-DPharos** [comment]
@Lucile-Besse 
> Same here, we are 2 with same troubles. Others are waiting before update because it's almost impossible to work. Do you have any solution ?

Our solution was to roll back to 2.1.0.1 (37119). Just be **_very aware_** that "uninstalling" will take down your containers. Make sure you back up first.

**Comment by Lucile-Besse** [comment]
Thanks ! I found a download link for previous version. But we are waiting for new release ;)

**Comment by silentworks** [comment]
I'm having this issue too, hope the fix will be released soon.

**Comment by mat007** [comment]
This should be fixed in 2.2.0.3 now.

**Comment by catalin560** [comment]
thanks but I'm sticking to 2.1.0.5 since it works perfectly... I'll let others test out your builds...
