### ISSUE TITLE
Issues with the WSL2 Integration 

### ISSUE THREAD

**Issue by louhde** [docker/for-win#5613]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 72ACA15C-C9B8-44BE-84DD-7734CAA4A575/20200127170203

### Expected behavior

We should be able to stop WSL2 integration for a specific distribution and go back to it later. 

### Actual behavior

If I turn off integration for a specific distribution, "docker-desktop" WSL mount no longer works. It's okay. But if I turn on integration I should be able to use Docker but symlinks appears to be broken. It seems legit but not user-friendly.

### Information

  - Is it reproducible? Yes
  - Is the problem new? No 
  - Did the problem appear with an update? I don't think so
  - Windows Version: 19041.21
  - Docker Desktop Version: 2.1.7.0 (41536)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Install WSL 2 integration on a distribution (I use Debian and Ubuntu, same issue)
  2. Test if docker commands works well
  3. If it's okay, turn off integration. If not, well ... don't know.
  4. Turn on again and checks docker commands. You should have a error like "Is the daemon running" error or worse "command not found", I had both during my debug phases.

**Comment by simonferquel** [comment]
I can't reproduce with this repro. However, it might very well be related to https://github.com/docker/for-win/issues/5607 for which we have a mitigation coming. Looking at logs right now.

**Comment by simonferquel** [comment]
Hmm, after having a look at the logs it happens that there is an issue triggered by the fact that there has been a change in your /etc/wsl.conf file changing the auto mount root. This is definitely a bug on our side, I am writing a fix for that.

**Comment by louhde** [comment]
Thanks for your answer @simonferquel ! I'll be waiting for an update. Have a good day !

**Comment by simonferquel** [comment]
We have a fix coming for this one. Thanks for the report :)

**Comment by simonferquel** [comment]
In the meantime, disabling the integration, removing /usr/bin/docker and reenabling it, should bring back the docker cli.
This can also be done for kubectl, man pages, and shell completion scripts.

**Comment by simonferquel** [comment]
Erf, just tested, the workaround does not work until you have removed all symlinks. You can watch the file `c:\users\<username>\appdata\local\docker\log.txt` to see which symlinks are causing problems.

**Comment by mat007** [comment]
Sorry, merging the PR with the fix in our internal repo auto-closed this issue.
Let’s keep it open until you can actually confirm it’s been fixed in the next release.

**Comment by louhde** [comment]
@simonferquel I tried to remove symlinks one by one but always forgot one or two so when I turned on integration again I have to find which one I forgot and do it again and again and again .... My workaround is to desinstall Docker and my WSL distro which is not a real workaround bacause it's too ... savage

**Comment by simonferquel** [comment]
You don't have to disable/reenable the integration while removing links, docker desktop will retry to run the agent in a loop.
So what I did was to open the log file in vs code (which refresh every time the file is changed), and just removed links as log lines print. Not ideal solution I know, but definitely better than loose your wsl distro.

**Comment by louhde** [comment]
Actually it's working, i'll touch nothing until the fix but I keep this if it's broken again. Thanks for you're help !

**Comment by BryanDollery** [comment]
> @simonferquel I tried to remove symlinks one by one but always forgot one or two so when I turned on integration again I have to find which one I forgot and do it again and again and again .... My workaround is to desinstall Docker and my WSL distro which is not a real workaround bacause it's too ... savage

I'm in exactly this position and it's slowing me down. I use containers professionally and this is messing me up. I have also resorted to reinstalling both components to resolve the problem.  
90DCCA05-21DC-4220-8275-2E5916B17F76/20200202135328
