### ISSUE TITLE
Windows - Mounting volumes does not warn if the folder/drive is not shared

### ISSUE THREAD

**Issue by laurencee** [docker/for-win#562]
### Expected behavior
A warning or prompt to share the underlying drive

### Actual behavior
No indication there is any issue
See: https://github.com/docker/docker/issues/21535

### Information

Mounting volumes on windows requires the underlying path to be setup as shared (fine) but the user is not given any indication of this during the mounting process through the Docker Community Edition UI.

### Steps to reproduce the behavior

  1. Make sure the drive you want to mount is not setup for sharing
  2. Mount the volume in docker for an image

**Comment by laurencee** [comment]
I'm not referring to the command line, I'm referring to the docker community edition UI. 

This was back from when the issue I linked was raised (2nd October 2016), not sure if the problem has been addressed since then.
https://github.com/docker/docker/issues/21535#issuecomment-250956847

**Comment by friism** [comment]
Docker will now provide an error if volume mounts are attempted without drive sharing enabled, so I'm closing.
