### ISSUE TITLE
Enter filesystem credentials infinite loop

### ISSUE THREAD

**Issue by Strandedpirate** [docker/for-win#5623]
- [x ] I have tried with the latest version of my channel (Stable or Edge)

### Expected behavior
Enter credentials once for each shared drive, dialog goes away, docker restarts.

### Actual behavior
Credential dialog pops goes into infinite loop. After clicking save it just pops up again; over and over and over and over...

![image](https://user-images.githubusercontent.com/1452996/73295463-58ac2800-41cd-11ea-8597-2675a86d1c13.png)

### Information
  - Windows Version:
![image](https://user-images.githubusercontent.com/1452996/73295516-724d6f80-41cd-11ea-99bf-abbc972c660b.png)

  - Docker Desktop Version:
![image](https://user-images.githubusercontent.com/1452996/73295483-606bcc80-41cd-11ea-990c-a58da18b9354.png)

  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. right click docker -> Settings -> Resources -> File Sharing
  2. check a drive, any drive.
  3. Apply & Restart
  4. Enter filesystem credentials dialog pops up -> enter user/pass.
  5. Repeats until the end of time or you click cancel.

**Comment by nick-randal** [comment]
I had the exact issue. The only way out of the loop was to uninstall and reinstall. After reinstall DD crashed on start with a settings error. The solution to stop the crash on start was to remove Docker from WIndows Crendential Manager.

**Comment by mat007** [comment]
This looks like a duplicate of #5567 ?

**Comment by Strandedpirate** [comment]
Yup, looks like a duplicate.

I removed docker credentials from Windows Credential Manager, uninstalled, reinstalled 2.2.0.0 and still had the same issue.

I uninstalled 2.2.0.0 and installed version 2.1.0.5 and I'm back up and running without issue.
