### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by fenrick** [docker/for-win#5626]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:CABF7E3F-35E9-4B79-9690-A8310552D8D1/20200128234134

### Expected behavior

Docker Desktop starts and runs as per normal

### Actual behavior

Crashed and only option is to reset environment to factory defaults.

I have uploaded diagnostics CABF7E3F-35E9-4B79-9690-A8310552D8D1/20200128234134.

I will attempt to update to new Doctor Desktop Edge version; and reset to factor defaults - not expecting to reproduce unfortunately after that.

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. unknown - machine crashed - no error reported or problem in windows troubleshooting
  2. manual started docker desktop after confirming that other WSL2 (Ubuntu) was working properly.
  3. crashed.

**Comment by mat007** [comment]
This looks a lot like https://github.com/microsoft/WSL/issues/4726
