### ISSUE TITLE
Docker does not start anymore

### ISSUE THREAD

**Issue by Grisu118** [docker/for-win#5629]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 85CA4FB7-CAA2-476A-B1E5-0CAB00E381DF/20200129055858

### Expected behavior
Docker for windows starts

### Actual behavior
It crashes: 
```
Unable to stop Hyper-V VM: Das angegebene Modul "Hyper-V" wurde nicht geladen, da in keinem Modulverzeichnis eine gültige Moduldatei gefunden wurde.
bei <ScriptBlock>, <Keine Datei>: Zeile 90

   bei Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   bei Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   bei Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   bei Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()
```

### Information
I did not use docker for some time on this host. So I can not tell since when it is not working. 

I have already completely removed docker and the windows hyper-v features and installed it again. Still the same issue. 

  - Windows Version: 10.0.18363 Build 18363
  - Docker Desktop Version: 2.2.0.0 (42247)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

1. Start docker

**Comment by Waschndolos** [comment]
same here
