### ISSUE TITLE
docker exec powershell or cmd - pasting from clipboard limited to 50 chars

### ISSUE THREAD

**Issue by latonita** [docker/for-win#563]
When i run interactive session (cmd or powershell) inside container with 'docker exec' command I need to paste text into command line.

For example I'm trying to fix all dependencies for building asp.net project using msbuild and want to run build manually inside container. Here is sample command line:
`"c:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" /p:Platform="Any CPU" /p:VisualStudioVersion=12.0 /target:Clean;Rebuild /property:Configuration=Release;Private=true /verbosity:normal /tv:4.0 /p:VSToolsPath=c:\MSBuild.Microsoft.VisualStudio.Web.targets.14.0.0.3\tools\VSToolsPath PROJECT.sln
`
### Expected behavior
I dont want to write this manually every time. I want to paste command from clipboard. it shall work.

### Actual behavior
when i paste long text (like command above) i only have first 50 chars pasted. for command above it gives me
`"c:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.ex`
so i have to split original line and paste it part by part and it drives me crazy

### Information

- A diagnostic was uploaded with id: A7B1AC63-0048-4C36-AC69-9B9A9450E3F1/2017-03-09_17-24-44
- Docker version 17.03.0-ce-rc1, build ce07fb6
- host is Windows Version 10.0.14393
- windows containers mode
- FROM microsoft/iis

### Steps to reproduce the behavior

  1. build container based on microsoft/iis image
  2. run it
  3. docker exec -ti <ID> powershell 
or
docker exec -ti <ID> cmd
  4. try to paste long text (>50 chars)

**Comment by apetres** [comment]
I have the same issue, but it reproduces only with powershell.

**Comment by friism** [comment]
Thanks for reporting. This is tracked here:

 * https://github.com/lzybkr/PSReadLine/issues/460
 * https://github.com/docker/docker/issues/29646
 * https://github.com/docker/docker/issues/27793

**Comment by robe070** [comment]
A good workaround is to map a volume on the docker run command and then put a script file in your local directory and execute that through the container e.g. if h:\temp is your local directory:
`docker run -v h:/temp/:c:/temp/ ...`

Open a powershell session in the docker container - here the container id = b9...

`docker exec -it b9 powershell`

Allow scripts to be run:

`Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine`

In Container powershell session run the script:

`c:\temp\myscript.ps1`
