### ISSUE TITLE
unwatching path

### ISSUE THREAD

**Issue by rafacolsn** [docker/for-win#5633]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: EA117535-E171-4DDE-B363-75421F1F6871/20200129151029

### Expected behavior
I expect change on my local fs is propagated to my container with a binded volume

### Actual behavior
when my container is running, change in my local volume is not propagated to my container
### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mat007** [comment]
Thanks for your report, this looks like a duplicate for #5530, right?

**Comment by stephen-turner** [comment]
Closing this ticket as a dupe. We believe it is fixed in the latest release, 2.2.0.3.
