### ISSUE TITLE
All images, containers, volumes, networks were deleted after I resized machine memory size

### ISSUE THREAD

**Issue by wisammechano** [docker/for-win#5634]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F67999F3-AF8F-438C-A54B-8B6DED5F4257/20200129155643

### Expected behavior
Reduced memory from 2048 MB to 1024 MB.
Reducing the memory size of the machine shouldn't delete or affect the hard disk of the machine.

### Actual behavior
Everything was deleted and vhdx size was ~2.4 GB used, now it is reset to 100 MB only.

### Information

  - Windows Version: Win 10 Pro V 1909 (OS Build 18363.592)
  - Docker Desktop Version: 2.1.0.5 (stable channel)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No.

### Steps to reproduce the behavior

  1. I had 2 containers running with docker-compose up -d. 
    - mysql:5.7 with a named volume. 
    - wordpress:latest with bind to partition D:
    - some images for nginx, phpfpm, ubuntu, debian, alpine... etc
  2. From settings > advanced, I reduced memory from 2048 to 1024 and hit apply. Docker restarted.
  3. Checked docker ps -a, nothing. Checked images and volumes nothing.
  4. Checked settings again, noticed the disk space usage went down to 100 MB from ~2.4 GB

**Comment by px528** [comment]
same issue...so bad.

**Comment by mat007** [comment]
Duplicates #5278
