### ISSUE TITLE
Docker Desktop Not Utilizing Full Resources Set in Settings (RAM/disk space)?

### ISSUE THREAD

**Issue by ludeykrus** [docker/for-win#5638]
Hi everyone, 

I recently built a new workstation for photogrammetry work. I'm running Docker Desktop on Windows 10 Pro, running 2x Intel Xeon 2697V3's, 128gb registered RAM, 1TB SSD. I have WebODM installed in Docker, and it runs successfully. It will complete processing projects. However, after a few projects, I was getting errors due to not able to write due to no disk space available. I noticed that in WebODM's diagnostic window, only ~58 gb of disk space and ~62gb of RAM are being utilized by WebODM/Docker despite having allocated 500gb of disk space and 100gb of RAM (allocated via Docker Desktop -> settings -> advanced). I can't seem to get around this issue... any advice? Docker info results below:

$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 5
  Running: 5
  Paused: 0
  Stopped: 0
 Images: 39
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 56
 Total Memory: 61.52GiB
 Name: docker-desktop
 ID: 5CWM:BWTV:WWRT:2QED:QOI5:HTSO:5UTZ:GMWL:4GET:G6GH:CRTE:TOPV
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 83
  Goroutines: 115
  System Time: 2020-01-29T21:44:57.650126882Z
  EventsListeners: 4
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

**Comment by mat007** [comment]
Could it be that you’re running out of inodes in the VM?
See for instance https://github.com/docker/for-win/issues/1042#issuecomment-577722134
