### ISSUE TITLE
Simple question about file-locking and Docker 2.2.0.0 (with his new gRPC FUSE)

### ISSUE THREAD

**Issue by coolfarmer** [docker/for-win#5640]
We all know that the old docker with the Samba Sharing is not the good way to go when you have to use the file-locking feature (example with SQLite databases).

I can't test now because I have downgraded my docker to 2.1.0.5 (because of all know issues) but I'm impatient and too curious.

 Will new sharing system (gRPC FUSE) allow the file-locking functionnality?

Thanks!

**Comment by diadras** [comment]
Hi, I am sorry for semi-hijacking your thread but I have been looking for an answer everywhere and have not been able to find an answer. I am experiencing a huge issue with Docker 2.2.0.0 and would really like to downgrade to 2.1.0.5 but I simply cannot find a way to do this. You are saying you downgraded and I wonder if you were able to point me in the right direction on how to do this?
