### ISSUE TITLE
Docker 2.2.0.0 uninstalling reinstalling not working 

### ISSUE THREAD

**Issue by UTHjarthur** [docker/for-win#5650]
having an issue with Docker  2.2.0.0 on windows 10 1903 --- 

installed docker update 2.2.0.0 
After update Docker errors out.
try to remove Docker for reinstalling
Docker uninstaller freezes and will not complete at all. 
manually removed all Docker folder and file from the computer 
manually removed reg data for Docker 
manually stoped and removed Hyper-V VM
redownload Docker 
run the installer but I keep giving a message that Docker Desktop 2.2..0.0 existing installation is up to date. 
no files installed and verified that the computer does not have any Docker file installed.

**Comment by mat007** [comment]
It’s probably due to the registry key `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Docker Desktop`

**Comment by UTHjarthur** [comment]
manually removed reg data for Docker Desktop
Now able to reinstall. 
" Installation Succeeded "
But still, get the error on docker startup

One or more errors occurred.

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

Crash report ID 700158AE-95F7-4A10-9A61-6D9C96F5E988/20200130163823

**Comment by UTHjarthur** [comment]
It looks as there is an issue with the Microsoft Windows Subsystem for Linux Launcher freezing the uninstaller.  

Open task manager 
expanded the CommuityInstaller 
end task for " Microsoft Windows Subsystem for Linux Launcher "
Now the CommuityInstaller will complete " Uninstalled successfully "

**Comment by mat007** [comment]
Yes, I think this might be similar to #5570?

**Comment by wzhfs** [comment]
1:cmd regedit
2:search docker desktop
3:remove
4:ok-install
