### ISSUE TITLE
Unable to execute engine/start

### ISSUE THREAD

**Issue by a-m4xwell** [docker/for-win#5651]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: DCFB9831-69A4-4CFD-94D2-3F5244F90603/20200130122403

### Expected behavior
Install docker desktop (edge or stable) onto windows machine. start docker and docker starts. 
### Actual behavior
Install docker, start docker, start fails with the following
![image](https://user-images.githubusercontent.com/31956999/73469906-fb57d880-437e-11ea-9268-8fd2f48c47f2.png)
I had docker running on my machine however started getting this error after updating it to the latest version. Intially had an issue where the C drive could not be mounted however uninstalling DD and reinstalling fixed that and lead to the current issue. 
### Information
Log attached
[log.txt](https://github.com/docker/for-win/files/4135134/log.txt)

  - Windows Version: 10.0.16299 Build 16299
  - Docker Desktop Version: Latest (stable)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. see above

**Comment by mat007** [comment]
Your log file has this error:
```
Synthetic SCSI Controller (Instance ID 488C9F6E-942C-4D0C-BA44-870931EB36BD): Failed to Power on with Error 'General access denied error'.

 Account does not have permission to open attachment 'C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx'. Error: 'General access denied error'.
```

A quick search on the Internet points to https://kx.cloudingenium.com/microsoft/servers/hyper-v/resolved-hyper-v-general-access-denied-error-trying-load-virtual-hard-drive/

I’m not sure how you got into this state though…
