### ISSUE TITLE
Docker desktop fails to start

### ISSUE THREAD

**Issue by sovereignoshan** [docker/for-win#5656]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by sovereignoshan** [comment]
showing docker error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/images/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.daemon is not running, but i restarted it, even after that same error.

**Comment by urinal-cake** [comment]
Receiving this as well, but only when modifying the daemon.json file to include:
```
"hosts": [
    "tcp://0.0.0.0:2375"
  ]
```
Docker engine Docker version 19.03.5, build 633a0ea
Docker for Windows 2.2.0.0
