### ISSUE TITLE
Docker 2.2.0.0 not working in the powershell 

### ISSUE THREAD

**Issue by Raidri** [docker/for-win#5658]
- [x] I have tried with the latest version of my channel (Stable or Edge)

### Expected behavior
If I type docker info in my powershell I except that I get the docker information
### Actual behavior
If I type docker info I get the following error:

Unbehandelte Ausnahme: System.ComponentModel.Win32Exception: Die angegebene ausführbare Datei ist keine gültige Anwendung für diese Betriebssystemplattform.
   bei System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   bei shim.CommandExecutor.execute(String process, String arguments, String working_directory, Boolean is_gui, Boolean wait_for_exit, Boolean requires_elevation)
   bei shim.ShimProgram.Main(String[] args)

### Information
The latest docker version before 2.2.0.0 runs as expected. Since I've updated to the newest version I got the error above.

- Docker version 2.2.0.0 (42247)
- Docker Engine 19.03.5
- Windows 10 pro Version 10.0.18363 Build 18363
- x64

**Comment by Raidri** [comment]
I could solve it. There was a registry problem. If i cleared the registry manually the docker commands worked as expected after reinstall docker.

**Comment by mat007** [comment]
@Raidri thanks for the report, for you mind sharing which registry keys you had to remove?
