### ISSUE TITLE
Docker Startup Crash (Windows 10)

### ISSUE THREAD

**Issue by McSelfish** [docker/for-win#5659]
hello there i have issue with Docker Software when i try to start it. i get this Error And It Crashes. Does Anyone Know How To Fix It?

1 Crash Report Diagnostic Id 214F8428-FCFB-46B4-B19D-31B1FCFDE253/20200131080223

The Crash Error v

Unable to stop Hyper-V VM: Cannot validate argument on parameter 'Id'. The argument is null. Provide a valid value for the argument, and then try running the command again.
at <ScriptBlock>, <No file>: line 4

   w Docker.Backend.HyperV.HandleException(String action, Exception ex) w C:\workspaces\stable-2.2.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV\HyperV.cs:wiersz 306
   w Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters, PowerShellConfiguration config) w C:\workspaces\stable-2.2.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV\HyperV.cs:wiersz 287
   w Docker.Backend.ContainerEngine.Linux.DoStop() w C:\workspaces\stable-2.2.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:wiersz 359
   w Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions, Credential credential) w C:\workspaces\stable-2.2.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:wiersz 202
   w Docker.Backend.BackendNamedPipeServer.<Run>b__8_3(Object[] args) w C:\workspaces\stable-2.2.x\src\github.com\docker\pinata\win\src\Docker.Backend\BackendNamedPipeServer.cs:wiersz 43
   w Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) w C:\workspaces\stable-2.2.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:wiersz 49
   w Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) w C:\workspaces\stable-2.2.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:wiersz 187

**Comment by mat007** [comment]
You can try this:
1. quit Docker Desktop
2. open the Hyper-V Manager (from the Windows Start menu)
3. select DockerDesktopVM and click Remove server on the right
4. start Docker Desktop

**Comment by McSelfish** [comment]
i tried what you said but i receive this right now
Diagnostic Id 214F8428-FCFB-46B4-B19D-31B1FCFDE253/20200131103945


Timed out waiting for the lifecycle-server to start.
This may be the result of a slow environment or there may be a real problem.
This timeout can be increased by editing settings.json, value 'lifecycleTimeoutSeconds'.
This file is usually in C:\Users\(your username)\AppData\Roaming\Docker

   w Docker.Backend.LifecycleClient.WaitForServerUp(TimeSpan pingTimeout) w C:\workspaces\stable-2.2.x\src\github.com\docker\pinata\win\src\Docker.Backend\LifecycleClient\LifecycleClient.cs:wiersz 123
   w Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions, Credential credential) w C:\workspaces\stable-2.2.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:wiersz 293
   w Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions, Credential credential) w C:\workspaces\stable-2.2.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:wiersz 214
   w Docker.Backend.BackendNamedPipeServer.<Run>b__8_3(Object[] args) w C:\workspaces\stable-2.2.x\src\github.com\docker\pinata\win\src\Docker.Backend\BackendNamedPipeServer.cs:wiersz 43
   w Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) w C:\workspaces\stable-2.2.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:wiersz 49
   w Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) w C:\workspaces\stable-2.2.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:wiersz 187
