### ISSUE TITLE
On restarting the machine, my db2 is lost and I have to recreate it

### ISSUE THREAD

**Issue by weslen02** [docker/for-win#5662]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 
03B32621-F892-48B0-BD6F-AF12848F4793/20200131134037

### Expected behavior
I hope, when restarting my machine, that the DB2 container will continue to work.

### Actual behavior
DB2 container is lost, as if it were not instantiated and created, I have to recreate it again.

When I create, it works, but as soon as the machine is restarted it stops working and I can't use it anymore, sometimes the container goes up and lasts for 20 sec and falls, sometimes it goes up but it doesn't work, when is recreate, works again, but if I restart the machine the problem is returned.
I can't connect to my database or my application, so I have to recreate it every time after a restart of my machine.
### Information

  - Windows Version: 10
  - HW: Intel Core i5 8th Gen/ SSD 250GB/ Memory 8GB
  - Docker Desktop Version: 2.2.0.0 (42247)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: On Windows > Linux Container based

### Steps to reproduce the behavior

  1. ... I created 2 folders on my machine with the name for exemple ` ws-docker ` and ` dockerDB2 `
  2. ... cd ws-docker
  3. ... cd dkFiles
  4. ... docker login
  5. ... docker pull ibmcom/db2
  6. ... I created a file with the extension  ` <.env_list> ` in the directory dockerDB2
  7. ... I input the values in the file (.env_list):
` LICENSE=accept `
` DB2INSTANCE=db2inst1 `
` DB2INST1_PASSWORD=<mypasswd> `
` DBNAME=testdb `
` BLU=false `
` ENABLE_ORACLE_COMPATIBILITY=false `
` UPDATEAVAIL=NO `
` TO_CREATE_SAMPLEDB=true `
` REPODB=false `
` IS_OSXFS=true `
` PERSISTENT_HOME=false `
` HADR_ENABLED=false `
` ETCD_ENDPOINT= `
` ETCD_USERNAME= `
` ETCD_PASSWORD= `
  8. ... and run the command:
` docker run -h mydb2 --name mydb2  --restart=always --detach --privileged=true -p 50000:50000 -p 55000:55000 --env-file .env_list -v /ws-docker/dockerDB2:/database ibmcom/db2 `

**Comment by mat007** [comment]
We have a new build that fixes several errors related to file sharing. You can get it from https://download-stage.docker.com/win/stable/42716/Docker%20Desktop%20Installer.exe.
I’d be nice if you could give it a go and report whether this works for you or not. If not could you upload a fresh diagnostics bundle?

**Comment by weslen02** [comment]
Sure @mat007 , I'll try and report next if it worked, thank you

**Comment by weslen02** [comment]
**Diagnostics ID:**
**03B32621-F892-48B0-BD6F-AF12848F4793/20200211204910**

Hello @mat007 , I reinstalled Docker in version 42716, but the error persists, the creation of DB2 worked, but when I restarted the machine the error was returned and can't connection on Database in Docker after restart.
Error: `com.ibm.db2.jcc.am.SqlException`
😢 

Thank you in advance!

**Comment by mat007** [comment]
Oh this is actually Windows containers, right?
Was this working properly before you upgraded to 2.2.0.0?

**Comment by weslen02** [comment]
Right @mat007 I am using Containers in OS Windows, but my container is based in Linux, no Windows, and it's never working for me, but my friend work with the container Docker and are using the same configs how to me, but for him it's work, him restart the machine and don't lost the docker after restart, but I'm not lucky as he is. 😫 

Thank you in advance!

**Comment by weslen02** [comment]
Hello, I formatted my machine and reinstalled the Windows operating system, but the problem returned. So I created a "solution" for this, I think it is not the better, but it was what I managed to do to solve my problem.
The solution was to use an Ubuntu virtual machine on Hyper-V, install Docker on that VM, and use DB2 and Docker inside the VM; this is seems more of a work around than a solution, but as I said, I need use Windows mandatory, and to use the Docker I had to take this approach.

You can see the steps here [Connect DB2 via DBeaver to Docker on Ubuntu VM Hyper-V](https://github.com/weslen02/connect-db2-via-dbeaver-to-docker-on-ubuntu-vm-hyper-v/blob/master/README.md)

This can be useful for more people, Thank you.
