### ISSUE TITLE
WSL 2: Unable to setup docker group

### ISSUE THREAD

**Issue by boostchicken** [docker/for-win#5668]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 961A9DD8-6C3F-4893-923F-18A175F4D3B6/20200202002209

### Expected behavior

Able to enable docker in WSL distros
### Actual behavior
Errors out with 
[16:21:16.190][WslIntegrationAgent-kali-linux][Info   ] 2020/02/01 16:21:16 Unable to setup docker user group: exit status 1
[16:21:16.192][WslIntegrationAgent-kali-linux][Warning] Failed to setup docker group in distro, disabling integration
[16:21:16.205][WslIntegrationAgent-Ubuntu][Info   ] 2020/02/01 16:21:16 Unable to setup docker user group: exit status 1
[16:21:16.208][WslIntegrationAgent-Ubuntu][Warning] Failed to setup docker group in distro, disabling integration

I am able to use it after creating a docker group and running 
sudo /mnt/wsl/docker-desktop/docker-desktop-proxy --distro-name Ubuntu --docker-desktop-root /mnt/wsl/docker-desktop.

However, I do not see the WSL context under docker context ls in powershell when just using the proxy
### Information

  - Windows Version: 19555.1001
  - Docker Desktop Version: 2.2.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Enable WSL integration
  2. Under resources enable Docker WSL Integration in distros
 3. Apply and Restart

**Comment by simonferquel** [comment]
By any chance, is your root user configured to use a non-bash terminal ? (fish maybe?)

**Comment by boostchicken** [comment]
I triple checked this, not the case.

**Comment by simonferquel** [comment]
We made a few changes to make it more reliable, can you try this private build: https://download-stage.docker.com/win/stable/42579/Docker%20Desktop%20Installer.exe ?

**Comment by simonferquel** [comment]
Oh, you are running 19555 which is kind of broken (see https://github.com/microsoft/WSL/issues/4860).

**Comment by JChrist** [comment]
If it's helpful at all, I have found out that _manually_ starting the desktop proxy in wsl2 with *sudo* in one terminal, allows me to work on another one.
I used instructions in this comment to start the proxy:
https://github.com/docker/for-win/issues/5096#issuecomment-572730439

**Comment by boostchicken** [comment]
@simonferquel do you still want me to test this new build or just wait for new Windows build?

**Comment by boostchicken** [comment]
@JChrist yeah, I have been doing that and it has been working for me.

**Comment by JChrist** [comment]
After updating Windows 10 to insider build 19564 and Docker for Windows to 2.2.1.0, the issue has been resolved. 
Please note that it still required to re-enable Ubuntu integration. from Settings -> Resources -> WSL Integration, but this time it worked perfectly and the proxy started fine (on its own).
So, for me at least, this can be considered resolved.

**Comment by boostchicken** [comment]
This should be fixed now.  Everything is working on my end.
