### ISSUE TITLE
New file sharing implementation is broken

### ISSUE THREAD

**Issue by Alan-Jowett** [docker/for-win#5678]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 2DDA73CE-5D02-4AEA-B540-DCDB86D318DC/20200203172743

### Expected behavior
Successfully able to build within container.

### Actual behavior

Container loses connection to volume

docker run -v c:\test:/test -it --rm build
/ # cd test
/test # wget http://www.squid-cache.org/Versions/v4/squid-4.10.tar.gz
Connecting to www.squid-cache.org (173.209.34.163:80)
squid-4.10.tar.gz    100% |************************************************************************| 5133k  0:00:00 ETA
/test # tar xvfz squid-4.10.tar.gz
squid-4.10/
squid-4.10/src/
squid-4.10/src/DiskIO/
squid-4.10/src/DiskIO/Mmapped/
squid-4.10/src/DiskIO/Mmapped/MmappedFile.cc
squid-4.10/src/DiskIO/Mmapped/Makefile.am
squid-4.10/src/DiskIO/Mmapped/Makefile.in
squid-4.10/src/DiskIO/Mmapped/MmappedIOStrategy.h
squid-4.10/src/DiskIO/Mmapped/MmappedDiskIOModule.h
squid-4.10/src/DiskIO/Mmapped/MmappedDiskIOModule.cc
squid-4.10/src/DiskIO/Mmapped/MmappedFile.h
squid-4.10/src/DiskIO/Mmapped/MmappedIOStrategy.cc
squid-4.10/src/DiskIO/DiskThreads/
tar: squid-4.10/src/DiskIO/Mmapped: Cannot utime: Connection aborted
tar: squid-4.10/src/DiskIO/Mmapped: Cannot change ownership to uid 1000, gid 1000: Socket not connected
tar: squid-4.10/src/DiskIO/Mmapped: Cannot change mode to rwxr-xr-x: Socket not connected
tar: squid-4.10/src/DiskIO/DiskThreads: Cannot mkdir: Socket not connected
squid-4.10/src/DiskIO/DiskThreads/DiskThreadsDiskFile.h
tar: squid-4.10/src/DiskIO/DiskThreads/DiskThreadsDiskFile.h: Cannot open: Socket not connected
...

### Information

  - Windows Version: 18363.628
  - Docker Desktop Version: v19.03.5
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
  1. Create build container: [build.zip](https://github.com/docker/for-win/files/4149181/build.zip)
      docker build . -t build

  2. Launch build container: docker run -v C:\Users\atjow\test:/test -it --rm build

  3. Pull sources: wget http://www.squid-cache.org/Versions/v4/squid-4.10.tar.gz

  4. Extract sources: tar xvfz squid-4.10.tar.gz

Fails at this step with lost volume connection

**Comment by mat007** [comment]
We have a new build that fixes several errors related to file sharing. You can get it from https://download-stage.docker.com/win/stable/42716/Docker%20Desktop%20Installer.exe.
I tried to untar the squid archive in a container (alpine) and it seems to work, it’d be nice if you could give it a go and report whether this works for you or not. If not could you upload a diagnostics?
Thanks!

**Comment by Alan-Jowett** [comment]
Initial tests seem positive. If you don't mind I will get some more folks on my team to try it (it was impact quite a few folks) and if no one hits any issues we can close this issue.

**Comment by stephen-turner** [comment]
@Alan-Jowett Is this fixed now?
