### ISSUE TITLE
ERROR - Timed out waiting for the lifecycle-server to start.

### ISSUE THREAD

**Issue by granbahamut** [docker/for-win#5680]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D188AF21-D4C1-43D0-ACC6-451AD1F8D6E0/20200203192004

### Expected behavior
Docker desktop starts normall on Windows 10

### Actual behavior
Every time I try to start docker desktop with a clean installation, it tries for like 10 minutes, then it crashes immediately. No matter if I put more or less memory (tried from 1GB to 4GB on ```memoryMiB``` property and 512 to 2GB on the ```swapMiB``` property), no matter if I put more or les time on the ```lifecycleTimeoutSeconds``` property.

```
Timed out waiting for the lifecycle-server to start.
This may be the result of a slow environment or there may be a real problem.
This timeout can be increased by editing settings.json, value 'lifecycleTimeoutSeconds'.
This file is usually in C:\Users\(your username)\AppData\Roaming\Docker

   en Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext() en C:\workspaces\stable-2.2.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:línea 102
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) en C:\workspaces\stable-2.2.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:línea 39
   en Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications) en C:\workspaces\stable-2.2.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Actions.cs:línea 132
   en Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0() en C:\workspaces\stable-2.2.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Actions.cs:línea 104
   en Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1() en C:\workspaces\stable-2.2.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\TaskQueuing\TaskQueue.cs:línea 46
```

Maybe is related to Issues #5069 #5082 #5093

### Information
  - Is it reproducible?: Yes, latest versions of Docker desktop (Standard and edge) has this behavior.
  - Is the problem new?: Aparently no, but the solutions seen on the Issue tracker did not help to solve the problem, for now...
  - Did the problem appear with an update?: Since the update previous to version 2.2.0.
  - Windows Version: Winwows 10 - build 16299.125
  - Docker Desktop Version: 2.2.0.42247
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No, its my physical machine, no VM's used.

I had to uninstall Docker completely to try to fix this problem, but it keeps happening.
  - Restart the PC doesn't change the behavior.
  - Reinstalling Docker, still crashes.
  - Installing an Edge version does the same.

### Steps to reproduce the behavior
  1. ... Just start Docker desktop, that's all.

**Comment by PavolSvidran** [comment]
I got exact same issue, probably 3 weeks or maybe 1 month ago.
I'm forced to stop using docker because of this issue, which is not easily solved, no time for it :(

Btw i think that i got this issue after some windows update.

**Comment by pleonex** [comment]
I get this error all the time after the update 2.2.0.3 (42716). I am running on a physical machine (no VM). Report ID: 4A77728F-60A3-4A6D-B1E6-2D259B18B737/20200214070951

**Comment by PavolSvidran** [comment]
Any progress with?

**Comment by oxycoder** [comment]
This problem happen when using WSL2 backend.
Workaround is not starting up docker with windows. Make sure Linux subsystem started before you run docker.

**Comment by mollychen12** [comment]
I got the same quesition，and my docker desktop version is  2.3.0.4
and Os:Windows 10 Enterprise
ID:1803
