### ISSUE TITLE
Docker Desktop 2 not Creating Unix Socket on Alpine WSL 2

### ISSUE THREAD

**Issue by AlexanderAllen** [docker/for-win#5681]
- [x] I have tried with the latest version of my channel (Stable, 2.2.0.0 42247)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

* After enabling WSL integration for Alpine WSL (version 2), 
* Docker Desktop should mount unix socket for communication with Docker Engine.

### Actual behavior

```
docker info
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

### Information

  - Windows Version: Windows 10 Pro Insider Preview, version 2004, build 19551.1005
  - Docker Desktop Version: Stable, 2.2.0.0 42247
  - Running Windows natively.

```
PS C:\Users\user> wsl -l -v
  NAME                   STATE           VERSION
* Alpine                 Running         2
  Ubuntu-18.04           Running         2
  docker-desktop         Running         2
  docker-desktop-data    Running         2
```

### Steps to reproduce the behavior

  1. wsl -d Alpine
  2. docker info

[wsl-alpine-strace.txt](https://github.com/docker/for-win/files/4150226/wsl-alpine-strace.txt)
[lxcore_kernel.etl.txt](https://github.com/docker/for-win/files/4150230/lxcore_kernel.etl.txt)
[lxcore_service.etl.txt](https://github.com/docker/for-win/files/4150231/lxcore_service.etl.txt)
[lxcore_user.etl.txt](https://github.com/docker/for-win/files/4150232/lxcore_user.etl.txt)

* What does enabling the WSL 2 in Docker Desktop entail?
* Is toggling the integration enable the Unix socket for communication with the Docker Daemon?
* Is integration (and the unix socket) currently available on Ubuntu WSL?
* Could it be that Alpine is missing additional packages for integration to work?

**Comment by AlexanderAllen** [comment]
Some additional basic troubleshooting steps I followed over here: 
https://medium.com/@callback.insanity/docker-desktop-2-unix-socket-not-available-on-alpine-wsl-2-96618bbbe3

**Comment by simonferquel** [comment]
The proxy (as well as CLI binaries that we ship with docker-desktop) depends on glibc. You need to install a glibc package (such as https://github.com/sgerrand/alpine-pkg-glibc) on your alpine environment to make it work.

**Comment by AlexanderAllen** [comment]
You've made my day @simonferquel . Tested, confirmed working. [I wrote this morning a story detailing the install and successful test](https://medium.com/@callback.insanity/successfully-connect-alpine-wsl-2-to-docker-desktop-2-2-620e135340df). I can't be thankful enough to your team for the WSL integration, it's magical.

Closed!

**Comment by kesor** [comment]
> The proxy (as well as CLI binaries that we ship with docker-desktop) depends on glibc. You need to install a glibc package (such as https://github.com/sgerrand/alpine-pkg-glibc) on your alpine environment to make it work.

Any chance that `/mnt/wsl/docker-desktop/docker-desktop-proxy` can become available as a uclibc binary or a static binary with no dynlib dependencies?

**Comment by thunder-spb** [comment]
Just a note, `sudo ln -sf /mnt/wsl/docker-desktop/shared-sockets/guest-services/docker.sock /var/run/docker.sock` worked for me :) But yeah, that would be great to make this automatically

**Comment by rigon** [comment]
@thunder-spb It also works for me!
