### ISSUE TITLE
Docker: Error response from daemon: failed to create endpoint determined_curran on network nat: HNS failed with error : Unspecified error

### ISSUE THREAD

**Issue by hemantkalra** [docker/for-win#5683]
Expected behavior
docker run -p 8081:8080 f00324fdc2a6 should run my docker and map 8081 local port to 8080 docker port.

I am using Docker version Docker version 19.03.5, build 2ee0c57608 on Windows 2016.

Actual behavior
docker: Error response from daemon: failed to create endpoint determined_curran on network nat: HNS failed with error : Unspecified error.

Information
Not able to get any output and DockerDebuginfo.ps1 is not found and dockerd -D is giving following.
time=“2020-02-04T09:37:21.290152100+05:30” level=info msg=“Starting up”
failed to load listeners: open //./pipe/docker_engine: Access is denied.

Steps to reproduce the behavior
docker run -p 8081:8080 f00324fdc2a6

I am very new to Docker. I installed docker in Windows 2016 following steps mentioned in docker website. As far as I understood there is something wrong with networking and I followed all the steps mentioned in following link but there is no luck.

https://github.com/docker/for-win/issues/750

**Comment by basickarl** [comment]
Getting the same: `docker: Error response from daemon: failed to create endpoint hole on network nat: HNS failed with error : Unspecified error.`
