### ISSUE TITLE
test

### ISSUE THREAD

**Issue by natorebu** [docker/for-win#5686]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by natorebu** [comment]
.

**Comment by natorebu** [comment]
latest: Pulling from library/hello-world
no matching manifest for windows/amd64 10.0.17134 in the manifest list entries

**Comment by thaJeztah** [comment]
Looks related to https://github.com/docker-library/hello-world/issues/56 (which has some more background information)
