### ISSUE TITLE
Use client cert to access secure private registry

### ISSUE THREAD

**Issue by hobti01** [docker/for-win#569]
### Expected behavior
docker login my.secure.registry
Username: myusername
Password:
Login Succeeded

### Actual behavior

There is no method to provide *client* certificate and key to the docker daemon running in the VM.  Docker daemon cannot connect to a secure registry that requires client certs.

### Information
Same issue as docker/for-mac#1320

### Steps to reproduce the behavior

1. Implement docker registry protected by TLS on port 443 and requiring client certificate
2. Add CA cert for registry to windows cert store
3. Attempt login
4. Wonder where to put client certificate and key.

**Comment by friism** [comment]
I think this is covered here: https://docs.docker.com/docker-for-windows/faqs/#how-do-i-add-custom-ca-certificates

**Comment by hobti01** [comment]
I'm sorry, but it is not.  That issue is for CA certificates, not client certs.  I had the same confusion with the Mac team.

**Comment by friism** [comment]
Ah, sorry - this is currently targeted for the next release.

**Comment by wiktor-k** [comment]
Release notes for Docker for win 17.06.0-ce-win18 (12627) mention "Support for client (i.e. "login") certificates for authenticating registry access (fixes docker/for-win#569)".

Should this ticket be closed?

**Comment by zadeluca** [comment]
I tried following the updated FAQ for using client certs (https://docs.docker.com/docker-for-windows/faqs/#how-do-i-add-client-certificates) but cannot get it to work. I still just get prompted for a username/password. I also posted my question to the forum (https://forums.docker.com/t/using-client-certificates/41364)

Any ideas? Thanks...

**Comment by softwarevamp** [comment]
I think this breaks loading windows trusted root authorities. 👎

**Comment by vyadh** [comment]
I got this working using files (rather than the Windows cert store). That isn't ideal obviously, but as a workaround. For example, executing 'docker-compose up' (PowerShell syntax):

`
$cert_path = 'c:\dev\scripts\certs\test'

docker-compose `
 -H mydocker.host.com:2376 `
 --tlsverify `
 --tlscacert $cert_path\ca.pem `
 --tlscert $cert_path\client.pem `
 --tlskey $cert_path\client-key.pem `
 up `
 -d
`

**Comment by wtigotw** [comment]
Any update? I'd really like to see this addressed. It seems that the work done for this was unsuccessful since the FAQ has been updated to remove the proposed solution.
