### ISSUE TITLE
Adding an insecure-registry via settings->docker engine breaks docker install

### ISSUE THREAD

**Issue by ronnyek** [docker/for-win#5692]
- [x] I have tried with the latest version of my channel (Stable or Edge)

Could not upload diagnostics, because troubleshooter wont even launch at this point.

### Expected behavior
I was attempting to be able to have docker command line be able to push to an insecure registry hosted on another machine. I was under the impression I needed to make sure that docker had `insecure-registries` populated with the hostand port of that machine.

In docker desktop, I clicked on Settings->Docker Engine, then added my insecureregistry so the json looked like so:
``` 
{
  "registry-mirrors": [],
  "insecure-registries": ["othermachine:port"],
  "debug": true,
  "experimental": false
}
```
I then hit Apply & Restart.

### Actual behavior
After this, docker is just completely broke. Even if I edit the json that was in that docker engine page, so it was what it was before (just empty square braces).

Once things go south, I can no longer connect to the dockervm in hyper-v manager to get logs, and most things docker desktop related just start failing. I've been unable to run troubleshooter after docker begins to fail, and ultimately I've had to uninstall docker and reinstall every time.
### Information

  - Windows Version: 10 1903 (18362.535)
  - Docker Desktop Version: 19.03.5
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
This is a native machine running the dockervm as a linux hosts in hyper-v.
### Steps to reproduce the behavior

For me:
  1. Docker tray icon -> Settings -> Docker Engine
  2. Add a registry to the insecure registries json property
  3. Hit Apply & Restart

**Comment by mat007** [comment]
Thanks for the report, what’s your Docker Desktop version?

If you look in `%APPDATA%\Docker\log\vm\docker.log` you’ll likely have a bit more information about what went wrong, for instance
```
failed to start daemon: insecure registry othermachine:port is not valid: invalid host "othermachine"
```
To reset or edit the daemon config you can directly modify `%USERPROFILE%\.docker\daemon.json` then quit and re-launch Docker Desktop.
