### ISSUE TITLE
.Docker folder not up to date.

### ISSUE THREAD

**Issue by CasaRol** [docker/for-win#5702]
- [y] I have tried with the latest version of my channel (Stable or Edge)
  - [y] I have uploaded Diagnostics
  - Diagnostics ID: 12D342D8-CE26-4B2F-828C-19391B885D45/20200205122349

### Actual behavior
The clean install of docker desktop resulted in my .docker-folder to not be updated with the rest of the system. I'm missing core files in order to even run "docker version"

current error message : "unable to resolve docker endpoint: open C:\Users\<Username>\.docker\machine\machines\default\ca.pem: The system cannot find the path specified."

### Information
     - I'm running it on Powershell with a clean docker intall.
     - I reainstalled as I had docker quickstart teminal and docker dekstop installed and it gave some 
        issues which lead to not being able to do anything within docker without exceptions.

### Steps to reproduce the behavior

  1. Remove all docker files from your computer (including .docker folder)
  2. Reinstall docker desktop on windows 10 pro

**Comment by mat007** [comment]
Do you have any environment variable which name starts with `DOCKER_` that you might have previously have set say for when you were using Docker Machine?

**Comment by CasaRol** [comment]
I do have a DOCKER_CERT_PATH which is set to .../.docker/machine/machines/default but i do not have those files in my ".docker"-folder

**Comment by CasaRol** [comment]
Is there any way for me to update the .docker folder?

**Comment by mat007** [comment]
Just remove the environment variable.

**Comment by stephen-turner** [comment]
@CasaRol Did removing the environment variable fix the problem?

**Comment by CasaRol** [comment]
Oh sorry! Yes it worked perfectly! Thank you very much!
