### ISSUE TITLE
Cannot run process isolated containers anymore after updating to Windows 1909

### ISSUE THREAD

**Issue by drauch** [docker/for-win#5708]
### Expected behavior

I can run `docker run --isolation Process mcr.microsoft.com/windows/servercore:ltsc2019` without errors.

### Actual behavior

I get the error:

```
docker: Error response from daemon: hcsshim::CreateComputeSystem 09a562689840ed63c6f51f1bdb34973e996a3339784380748322fcb44f1fe4f8: The system cannot find the file specified.
(extra info: {"SystemType":"Container","Name":"09a562689840ed63c6f51f1bdb34973e996a3339784380748322fcb44f1fe4f8","Owner":"docker","VolumePath":"\\\\?\\Volume{d937f6de-dd1b-4a79-a06f-e375663b1d2d}","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\09a562689840ed63c6f51f1bdb34973e996a3339784380748322fcb44f1fe4f8","Layers":[{"ID":"9cc9c6c9-720e-56b8-8666-c55a447aa544","Path":"C:\\ProgramData\\Docker\\windowsfilter\\916f7433d2b4a29d206ea46b131f59539bafce49929dd18d8e063c73c7d66fcb"},{"ID":"a0b38a38-abce-595f-b355-ee7f95f5a446","Path":"C:\\ProgramData\\Docker\\windowsfilter\\237f0b01103775586bceeb74d2174ca8c929210cd5c1a431d10f50dd86daa100"}],"HostName":"09a562689840","HvPartition":false,"EndpointList":["2664327E-E3DA-4989-B292-D20A129FB749"],"AllowUnqualifiedDNSQuery":true}).
```

### Information
  - Is it reproducible? Yes
  - Is the problem new? Yes
  - Did the problem appear with an update? Yes, after updating to Windows 1909
  - Windows Version: W10 1909
  - Docker Desktop Version: 2.2.0.0 stable
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

**Comment by drauch** [comment]
Note: the Docker container seems to be created but is not running. Trying to run it results in the same error as above.

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place?
