### ISSUE TITLE
Unable to execute Restart: Error response from daemon: Bad response from Docker engine

### ISSUE THREAD

**Issue by furio** [docker/for-win#571]
### Expected behavior
 Docker have to start
### Actual behavior
HyperV starts but docker ends with:
```

Unable to execute Restart: Error response from daemon: Bad response from Docker engine
    in Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning)
   in Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   in Docker.Backend.ContainerEngine.Linux.Restart(Settings settings)
   in Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   in Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

1C94AFFE-10D4-4B6B-A4D3-F16E0AFCA683/2017-03-11_11-36-35
Docker: Version 17.03.0-ce-win1 (10300) Channel: beta 05a8abd
Windows 10 Pro - 1607 - 14393.693
(A docker reset to factory seems to fix the issue)

### Steps to reproduce the behavior

  1. Start windows
  2. Start docker

**Comment by KevinBusse** [comment]
Had the same issue today...

Docker version 17.06.0-ce, build 02c1d87
Windows 10 Pro - 1607 - 14393.1358

**Thanks for pointing out that factory reset helps here, though**

**Comment by alp82** [comment]
Got the same issue with `Version 17.07.0-ce-rc3-win23 (13024)`. Factory Reset did not help in my case.

**Comment by AnnapoorniS** [comment]
Got the same issue while installing docker in Window 10.

**Comment by alp82** [comment]
I could resolve it by uninstalling and reinstalling docker (stable branch).

**Comment by clns** [comment]
Reinstalling the stable version also worked for me. I previously had edge, but I didn't try to reinstall edge, I went for stable directly.

**Comment by hellowin** [comment]
How to clean reinstalling docker? I managed to reinstall it but I think the system still recognize last docker installation. I use Win 10 and Docker version 17.09.0-ce-win32.

**Comment by makapaka23** [comment]
Any other info on this ? Since my last update I have not been able to run docker at all - factory reset and uninstall/reinstall doesn't help me :(

**Comment by hellowin** [comment]
Try to downgrade to this https://github.com/docker/for-win/issues/1148#issuecomment-333677117

This is not a fix, only downgrade to working version of docker.
