### ISSUE TITLE
Cannot remote debug docker container

### ISSUE THREAD

**Issue by KrzysZG37** [docker/for-win#5710]
Hi

I have problem with remote debug my docker container. What is important, there is no docker NAT interface in my ipconfig output.

Regards

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mat007** [comment]
About DockerNAT you might want to check #5538
