### ISSUE TITLE
Re: #5663 - Docker Desktop still crashing after Windows 10 Update

### ISSUE THREAD

**Issue by plleg** [docker/for-win#5711]
This is basically an update to: #5663 - Docker Desktop crashes after Windows 10 update.

  - [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID: 2F4E65B5-BC26-4EAB-94A4-E8AFD65D5F42/20200206145120

### Expected behavior
Docker starts up

### Actual behavior
Docker does not start

### Information
  - Is it reproducible? yes
  - Is the problem new? no
  - Did the problem appear with an update? yes
  - Windows Version: Windows 10 Pro insider preview 10.0.19559
  - Docker Desktop Version: 2.1.7.0 (41536) Edge
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior
reboot computer

**Comment by sc0ttwad3** [comment]
Same here even with Docker Desktop 2.2

**Comment by RobertBernstein** [comment]
I am having the same problem (running the same Insider Preview version of Windows, 10.0.19559), but am running Docker 2.2.0.0 (42247).  It times out while trying to initialize.  Help!

**Comment by naourass** [comment]
Check this solution : https://github.com/docker/for-win/issues/5811

**Comment by plleg** [comment]
As of a recent update to Windows and Docker, it is running as expected.
win: Windows 10 Pro Insider preview
docker: 2.2.1.0 (42746) Edge

**Comment by RobertBernstein** [comment]
This issue can be closed as far as I'm concerned.

**Comment by sc0ttwad3** [comment]
Same here.

**Comment by plleg** [comment]
close it. There have been many updates to Docker and Windows 10 Pro insider.
