### ISSUE TITLE
Kubernetes does not start after updating to 2.2.0.0

### ISSUE THREAD

**Issue by TheDaftGazebo** [docker/for-win#5713]
- [X] I have tried with the latest version of my channel (Stable)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: DC2E3DC5-712F-4353-8CBC-9CD5909A68CF/20200206175603

### Expected behavior

Kubernetes to start

### Actual behavior

Kubernetes does not start when enabled

### Information

  - Windows Version: Windows 10 Enterprise Version 1809, OS Build 17763.973
  - Docker Desktop Version: 2.2.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No
 - Initially, I had updated from Docker Desktop v2.1.0.5 (which I had Docker and Kubernetes working just fine under), but when Kubernetes wouldn't start after the update to 2.2.0.0, I attempted to uninstall Docker Desktop and scrub my system of the various Kubernetes and Docker files/folders to do a fresh install of 2.2.0.0. After a fresh install, however, Kubernetes still wouldn't start.

### Steps to reproduce the behavior

  1. Fresh install of Docker
  2. After Docker is started and running, enable Kubernetes
  3. The settings view for Docker hangs with a loading spinner, with Kubernetes perpetually stuck in the "Starting" state with the orange dot

**Comment by STaRDoGG** [comment]
This isn't a fix, to get Kubernetes working, but if you want to at least get back to having the Kubernetes option turned back off (no spinning icon, items not grayed out, etc.) give this a shot, it worked for me (until they get the bug fixed).

[https://geekdrop.com/content/kubernetes-in-docker-stuck-showing-kubernetes-starting-forever](https://geekdrop.com/content/kubernetes-in-docker-stuck-showing-kubernetes-starting-forever)

**Comment by TheDaftGazebo** [comment]
Thank you, it looks like I was able to get Kubernetes to stop trying to start. I've now tried uninstalling 2.2.0.0 and reinstalling 2.1.0.5 to see if it's a version issue, but I still can't get Kubernetes to start. At this point, I assume it's not a version issue, but something else in my system causing it to act up, though I am unsure as to how I can go about debugging it and figuring out why it won't start. Is there a way I can try to enable Kubernetes from a command line or something so that I can at least get some kind of log output?

**Comment by TheDaftGazebo** [comment]
I figured out my issue. My hosts file got borked somehow, it was upwards of 230MB with a load of empty lines. No idea how that happened. Hope it doesn't happen again. I got my hosts file sorted though, with the correct IP addresses for docker and kubernetes. It appears to be all working now. Thanks for the help!

**Comment by STaRDoGG** [comment]
> I figured out my issue. My hosts file got borked somehow, it was upwards of 230MB with a load of empty lines.

Always happy to help.

230mb Hosts file? *falls over*

In my 26 years of computin' I've literally never heard of one getting that huge, and I even once made a shareware to go through people's browser bookmarks and auto add all links in it to their hosts, to speed up surfing, with comments next to each one! lol

> I got my hosts file sorted though, with the correct IP addresses for docker and kubernetes.

Curious, which IP addresses for docker and Kube you used? Maybe I'm just doing something wrong myself?

I'm just now dipping my toes into the Kubernetes waters and researching all the various flavors, and from what I can gather, [Kind ](https://kind.sigs.k8s.io/) *seems* to be basically the same thing as the built-in Docker Kubernetes, though I may be wrong (and if someone else reading this knows, I'd appreciate for them to lemme know the details). My next step was to try it out, since I couldn't get the built-in Kubernetes running.

**Comment by TheDaftGazebo** [comment]
I'd have to find where I came across this again, but essentially I added these 2 lines to the hosts file (which I think would have been auto added normally):

192.168.1.6 host.docker.internal
192.168.1.6 gateway.docker.internal

I don't know if these are actually used, but everything is working now, so I'm not gonna touch it.

**Comment by STaRDoGG** [comment]
> I'd have to find where I came across this again

haha, that was from the link I gave ya above, which is actually my website. Weird that it fixed things for you though, but not me. Either way, glad it worked out for ya!
