### ISSUE TITLE
Unable to use localhost as proxy server after upgrading to 2.2.0

### ISSUE THREAD

**Issue by claneo** [docker/for-win#5715]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Run a proxy server on host, set docker proxy setting to `http://localhost:xxx` or `http://127.0.0.1:xxx`, `docker pull` works.

### Actual behavior

Prior to 2.2.0, it works fine, after upgrading to 2.2.0, it does not work.

Then I try to change proxy setting to `http://host.docker.internal:xxx` and `http://192.168.x.x:xxx`(host's external ip), both works fine;

It seems like that docker desktop 2.2.0 now handle proxy inside vm instead of host.

I already known that `host.docker.internal` can be used in container, but I can't find any document says that it can be used in proxy setting.

### Information

  - Windows Version: Windows 10 1910
  - Docker Desktop Version: 2.2.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

**Comment by mat007** [comment]
Thanks for your report, indeed there seem to be a regression there.
We are investigating this.

**Comment by djs55** [comment]
The fix for this has been included in [2.4.0.0 stable](https://desktop.docker.com/win/stable/48506/Docker%20Desktop%20Installer.exe).
