### ISSUE TITLE
Docker Volume Sharing Windows 10 - Checkpoint VPN

### ISSUE THREAD

**Issue by grahamehorner** [docker/for-win#572]
### Expected behavior
Docker volume share

### Actual behavior
Docker volume share reports firewall is enabled & blocking sharing

### Information
I was not connected to the corporate VPN using checkpoint; however
docker was impacted by the checkpoint VPN application, I removed
checkpoint VPN software and then accepted/shared volumes.

**Comment by friism** [comment]
@grahamehorner thanks for sharing. Can I close this issue?

It might be useful for us if you could capture a diagnostic dump with the checkpoint app installed so we can figure out what's going on.

**Comment by cmosguy** [comment]
@friism, I am using Symantec Endoint protection here, and I am suffering the same issue.  If I connect to the VPN corporate network i can no longer connect to my shared volumes.  Is there a solution this?
