### ISSUE TITLE
wsl2-and desktop v2.7.1.0  - Failed to check wsl-bootstrap version: exit code: 1

### ISSUE THREAD

**Issue by tim-pluralgroup** [docker/for-win#5723]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version: 10 Pro 
OS Name: Microsoft Windows 10 Pro Insider Preview
OS Version:                10.0.19555 N/A Build 19555

  - Docker Desktop Version: 2.7.1.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:NO

### Steps to reproduce the behavior

  1. ...Reinstalled and upgrade 2.1.7.0 with experimental WSL checked

  2. ...Crash REPORT FA2C9341-6AFF-41D8-92E2-69FD86DC8775/20200209203013
[dockerLog_Failed.txt](https://github.com/docker/for-win/files/4177813/dockerLog_Failed.txt)
[dockerLog_Failed.txt](https://github.com/docker/for-win/files/4177816/dockerLog_Failed.txt)

**Comment by tim-pluralgroup** [comment]
Submitted previously  and no response as yet??

**Comment by danieldiazastudillo** [comment]
Had the same issue today after upgrading to WSL2 and using new Docker Engine for WSL2. First of all, i think that MS Docs about installing WSL2 are a bit incomplete. After following all instructions for upgrading the command to set the default **distro** (`wsl --set-default Ubuntu-16.04`) is missing, it just sets the default architecture `wsl --set-version  <distro> 2` & converts if it's necessary. When distros were listed, the default version for my WSL was _Legacy_, so to be careful i did this:

1. Export **Legacy** distro via `--export` (just to be sure)
2. Set my Ubuntu distro as default (it is version 2, downloaded via Windows Store)
3. Unregister Legacy distro (so it is no longer listed with `wsl -l -v`)
4. Update Docker Desktop to latest EDGE version
5. Set Docker Resources WSL Integration to enable integration with default WSL distro **and** my Ubuntu distro

Of course this is assuming you have WSL2 based engine enabled previously. With this changes everything works perfectly,

**Comment by okainov** [comment]
Same issue... Very upset about practical impossibility to use Docker :(
