### ISSUE TITLE
wsl2  with docker desktop - cannot start- Failed to check wsl-bootstrap version: exit code: 1

### ISSUE THREAD

**Issue by tim-pluralgroup** [docker/for-win#5727]
- [ x] I have tried with the latest version of my channel (Stable or Edge)- BOTH
  - [ x] I have uploaded Diagnostics- YES
  - Diagnostics ID:

### Actual behavior
cannot start 
### Information

  - Windows Version: 
OS Name: icrosoft Windows 10 Pro Insider Preview
OS Version: 10.0.19555 N/A Build 19555
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: NO

### Steps to reproduce the behavior

[DockerIssuelog.txt](https://github.com/docker/for-win/files/4182630/DockerIssuelog.txt)
[dockerLog_Failed.txt](https://github.com/docker/for-win/files/4182631/dockerLog_Failed.txt)
[docker-log.txt](https://github.com/docker/for-win/files/4182632/docker-log.txt)

reporo steps- https://docs.docker.com/docker-for-windows/wsl-tech-preview/

crash report ID: FA2C9341-6AFF-41D8-92E2-69FD86DC8775/20200210191648

  1. ...
  2. ...

**Comment by alexandre-melard** [comment]
same issue, ID: BC59E8C6-4BF4-4A03-A7B7-87E3F0931957/20200210190927

**Comment by tim-pluralgroup** [comment]
I have removed and reinstalled several times-- I can get back to WSL 1 and use the docker Hyper-v VM and it starts-- when I do the steps to change to WSL2-- it does not start-- and gives the erorr message - **Failed to check wsl-bootstrap version: exit code: 1**

**Comment by takashiki** [comment]
Try run `netsh winsock reset` with admin privilege in powershell.

**Comment by tim-pluralgroup** [comment]
takashiki - thank you for responding- very tortuous -- It was fixed in the most recent version  update. Works good now.
