### ISSUE TITLE
[Feature request] Docker Dashboard - add option to search images from docker hub and start container

### ISSUE THREAD

**Issue by martin-tarjanyi** [docker/for-win#5731]
First of all, I really like the new UI. Especially, the displaying of containers started with docker-compose.

One feature that Kitematic has but currently is missing from Docker Dashboard is the ability to search images published on Docker Hub and starting containers from them with a click of a button.

Do you plan to add this feature?

**Comment by stephen-turner** [comment]
Thanks for the feedback, @martin-tarjanyi. Yes, we do plan to add that.

cc @nebuk89.

**Comment by jeserkin** [comment]
1:1 was wondering about same option. Loved the way one can easily search through log of the container as well.
