### ISSUE TITLE
Docker desktop stuck at `Docker is starting` v2.2.0.3

### ISSUE THREAD

**Issue by spottedmahn** [docker/for-win#5737]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 1E67C252-17EF-4210-9A57-FBA843DDE22E/20200211185459

### Expected behavior
Docker desktop should start

### Actual behavior
It's not starting

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible? yes
  - Is the problem new? yes
  - Did the problem appear with an update? yes, everything was fine until the clicked that upgrade button!
  - Windows Version: Win10 v1909
  - Docker Desktop Version: 2.2.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

**Comment by spottedmahn** [comment]
When I search the log for "fatal" this is the first entry I see:

>[13:53:02.382][ApiProxy          ][Info   ] time="2020-02-11T13:53:02-05:00" msg="🍀 socket server listening : \\\\.\\pipe\\dockerGuiToDriver"
[13:53:02.386][ApiProxy          ][Fatal  ] time="2020-02-11T13:53:02-05:00" msg="listen tcp 127.0.0.1:2375: bind: An attempt was made to access a socket in a way forbidden by its access permissions."
[13:53:02.394][ApiProxy          ][Error  ] Process died

**Comment by spottedmahn** [comment]
`Reset to factory defaults` allowed me to get it started

**Comment by spottedmahn** [comment]
It wouldn't surprise me if the problem [was related to this](https://forums.docker.com/t/wsl-and-docker-for-windows-cannot-connect-to-the-docker-daemon-at-tcp-localhost-2375-is-the-docker-daemon-running/63571/13).  I had a container autostarted for [remote manage via WSL](https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly).

![image](https://user-images.githubusercontent.com/14079228/74275303-a3f02b80-4ce1-11ea-9635-7c8d9c98dcc0.png)

**Comment by spottedmahn** [comment]
broken again today after a reboot.   must be that auto-startup container...

**Comment by spottedmahn** [comment]
resetting to factory defaults again...  this happened:

![image](https://user-images.githubusercontent.com/14079228/74374053-b040bb00-4dab-11ea-9012-8e336c978ec4.png)

**Comment by spottedmahn** [comment]
there must be a way to remove an `autostart` container w/o the daemon running, right?

[Couldn't try to turn off the autostart](https://stackoverflow.com/a/37600885/185123) as the daemon can't start:

>\>docker update --restart=no alpine/socat
error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/alpine/socat/update: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

**Comment by dfriedenberger** [comment]
Have the same problem. After resetting to factory defaults, it works from commaand line. After enabling the option "Expose daemon on tcp://localhost:2375 without TLS" it failed again. 

Send CrashReport: 204ffcc0-53e1-11ea-96ae-0205857feb80/20200220130136

**Comment by dfriedenberger** [comment]
I solved it by adding port to excludedportrange. It's described in [Issue 3546 Comment 483311479](https://github.com/docker/for-win/issues/3546#issuecomment-483311479)

docker no longer crashed after the downgrade to 2.1.0.5, but could not bind to port 2375 furthermore. You can check it with `docker -H tcp://0.0.0.0:2375 info`. I find that there is no docker problem So I found the solution with adding port to excludedportrange. Also works with latest version 2.2.0.3.

**Comment by spottedmahn** [comment]
[That](https://github.com/docker/for-win/issues/3546#issuecomment-483311479) did the trick 🚀, thanks @dfriedenberger!

---

It seems kinda extreme having to disable the Hyper-V feature, **reboot**, reserve port, re-enable and **reboot**.  There's gotta be a way w/o the reboots!  Right 🤔?

**Comment by spottedmahn** [comment]
I'm guessing this was triggered by a switch from VirtualBox to Hyper-V? 🤔

>keep supporting VirtualBox if Hyper-V is not ready for prime time  [Source](https://github.com/docker/for-win/issues/5753#issuecomment-589842292).
