### ISSUE TITLE
docker doesn't track changes of webapp source files on bind mount

### ISSUE THREAD

**Issue by mariusz-podsiadlo** [docker/for-win#5738]
- [v] I have tried with the latest version of my channel (Stable or Edge)
  - [v] I have uploaded Diagnostics
  - Diagnostics ID: A1443414-6E3D-407C-BDA8-2B4A48D4CC3A/20200211194036

### Information

I develop webapp served by services running on docker container. One of the services which is responsible for serving of components of the app (html, js, css, etc.) has bind mount folder with source files. When I modify source files and try to test changes in web browser, browser receives unchanged files. It not happens always. In fact, a few times after start of docker files are refreshed correctly and changes are visible in browser. But after few cycles docker loses track of changes on bind mount and I must restart docker to bring it back to normal state.
In system log i found errors form Hyper-V-Integration:
"'DockerDesktopVM': The Data Exchange integration service is either not enabled, not running or not initialized."
with event id 4092.
However, Data Exchange integration service is not running but is started on demand. When I try to run it manually it starts and stops immediately with message that it will be run when needed

**Comment by stephen-turner** [comment]
@mariusz-podsiadlo Unfortunately your diagnostics didn't upload correctly, so I can't see which version you're on. But if it's 2.2.0.0, then I recommend upgrading because this is almost certainly fixed in 2.2.0.3.

**Comment by mariusz-podsiadlo** [comment]
Yes, ver. 2.2.0.3 solves the problem. Thanks.

śr., 12 lut 2020 o 14:12 Stephen Turner <notifications@github.com>
napisał(a):
