### ISSUE TITLE
Docker failed to start:   'MobyLinuxVM' because one of the Hyper-V components is not running at Start-MobyLinuxVM, <No file>

### ISSUE THREAD

**Issue by oracleason** [docker/for-win#574]
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start.

Failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running.

'MobyLinuxVM' failed to start. (Virtual machine ID 497367E2-C673-40A3-A41E-99931DA39599)

The Virtual Machine Management Service failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running (Virtual machine ID 497367E2-C673-40A3-A41E-99931DA39599).
at Start-MobyLinuxVM, <No file> : line 287
at <ScriptBlock>, <No file>: line 382
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings)
   at Docker.Backend.Backend.RestartAll(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

install docker on windows 10 enterprise, first start failed. 

do you know how to fix the issue?

**Comment by friism** [comment]
In hyper-v manager, can you create a Hyper-V VM? More debugging suggestions here: https://docs.docker.com/docker-for-windows/troubleshoot/#hyper-v

**Comment by oracleason** [comment]
yes, i can. but start failed. 

Failed to start the virtual machine 'test' because one of the Hyper-V components is not running.

**Comment by ssonam09** [comment]
I am facing the similar issue I am trying to install docker on windows10 Enterprise  virtualbox but it was giving error so i tried to enable nested virtualization but create Vm using server 2016 iso creation was successful but when I tried to start Virtual machine it is giving error one of the hyperv component is not running please help here?

**Comment by nagkumar** [comment]
We are seeing the similar issue, no confirmed answer anywhere else.. can you pl. fix it immediately

**Comment by friism** [comment]
@nagkumar please open a separate issue with Docker for Windows diagnostic ID.

**Comment by vinsma26** [comment]
I also tried running Docker within a Windows 10 VirtualBox VM but to no avail.  The overall consensus is that Hyper-V is needed to be running on a system before Docker can start, and a virtualized Hyper-V is not supported on VirtualBox VM's.  Of course, anyone is welcome to correct me on this if I'm wrong.

**Comment by RynoDeJager** [comment]
@vinsma26, did you perhaps get confirmation on your statement about Hyper-V not being supported in VirtualBox?

**Comment by yetanotherchris** [comment]
@Rager71  Virtualization in virtualization isn't supported in VirtualBox and they have no plans to (from the website docs).

**Comment by cihant** [comment]
Is your CPU supports virtualization? Please check this. If you installed hyper-v while installing docker, please uninstall hyper-v and try install again. If your cpu doesn't support virtualization you can see.

**Comment by aollivierre** [comment]
Resolved by running the following PowerShell script to enable nested virtualization (only Windows Server 2016).

Run the following in PowerShell commands from outside the Hyper-V Host of the Hyper-V Guest. i.e (Windows 10 Enterprise > Hyper-V running Windows Server 2016 Eval > Hyper-V to run MobyLinuxVM) so run the powershell script from the very lower layer in this case Windows 10.

#The first command will download the powershell script file "Enable-NestedVm.ps1"
Invoke-WebRequest https://raw.githubusercontent.com/Microsoft/Virtualization-Documentation/master/hyperv-tools/Nested/Enable-NestedVm.ps1 -OutFile ~/Enable-NestedVm.ps1

#The second command will execute the actual script. Replace "VmName" with the proper VM name running in the Hyper-V host. Follow the prompts on the PowerShell screen with Y/N to enable MAC spoofing and other options that may come up as needed.
~/Enable-NestedVm.ps1 -VmName "VmName"

You may need to restart the Hyper-V host VM and the MobyLimuxVM should run fine in the Hyper-V guest. Of course if you click the "switch to Windows Containers" from the Docker system tray the error for MobyLinuxVM will be gone. That is not a fix though as the MobyLinuxVM is needed for Linux Containers if that`s what you are going after.

More details on the powershell script that enable the new nested virtualization technology that is only built in Windows Server 2016.
https://www.thomasmaurer.ch/2015/10/hyper-v-nested-virtualization-in-windows-10-build-10565/

**Comment by devvvy** [comment]
> x and they have no plans to (from the website docs).

Sorry I can't find the url to Dockers where it says it's not supported?

**Comment by ClientIco** [comment]
> > x and they have no plans to (from the website docs).
> 
> For sake of everyone, Dockers officially don't support "Nested Virtualization"
> https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-for-windows-in-nested-virtualization-scenarios
> _"Docker for Windows can run inside a Windows 10 virtual machine (VM) running on apps like Parallels or VMware Fusion on a Mac provided that the VM is properly configured. However, problems and intermittent failures may still occur due to the way these apps virtualize the hardware. For these reasons, Docker for Windows is not supported for nested virtualization scenarios. It might work in some cases, and not in others."_
> 
> #2987

Thanks Appreciate more that you might realize. Best regards. You save us major amount of time!

**Comment by cawoodm** [comment]
So all the talk of the difference between VMs and Containers being "no Hypervisor is required" is nonsense?

**Comment by freemansoft** [comment]
Linux containers on windows (pre WSL 2) require a VM (MobeyVM).  
Linux containers on Linux and windows containers on Windows can be run or without VMs. 
Windows containers on Linux are not implement (AFAIK)
