### ISSUE TITLE
Can't write to volume in Dockerfile in Windows container

### ISSUE THREAD

**Issue by pagdot** [docker/for-win#5742]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 4F226D24-1691-4562-BBFF-7063BE736E2F/20200212071751

### Expected behavior

Writing to volume works while building Dockerfile.

### Actual behavior

Writing dosn't work.

### Information

  - Problem is reproducible using minimal Dockerfile
  - Writing to volume is possible when running the container
  - Windows Version: 1809
  - Docker Desktop Version: 2.2.0.3 (Engine: 19.03.5)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Normal Windows 10

### Steps to reproduce the behavior

Dockerfile:

```
FROM mcr.microsoft.com/windows/servercore:1809
VOLUME [ "c:/data" ]
RUN echo test>c:\data\test.txt && dir c:\data
RUN mkdir c:\data2 && echo test>c:\data2\test.txt && dir c:\data2
```

  1. docker build

Expected output: Both `dir`-commands list test.txt file

Actual output: The first `dir`-command displays an empty directory

**Comment by mat007** [comment]
This seems to be working for me, is that not the output you were expecting?

```
Step 1/4 : FROM mcr.microsoft.com/windows/servercore:1809                   
 ---> fdc91ce7c6d8                                                          
Step 2/4 : VOLUME [ "c:/data" ]                                             
 ---> Running in e14c9031b7e5                                               
Removing intermediate container e14c9031b7e5                                
 ---> d48d2f2c111e                                                          
Step 3/4 : RUN echo test>c:\data\test.txt && dir c:\data                    
 ---> Running in 1234ad25a331                                               
 Volume in drive C has no label.                                            
 Volume Serial Number is E4F0-4C31                                          
                                                                            
 Directory of c:\data                                                       
                                                                            
02/12/2020  09:39 AM    <DIR>          .                                    
02/12/2020  09:38 AM    <DIR>          ..                                   
02/12/2020  09:39 AM                 7 test.txt                             
               1 File(s)              7 bytes                               
               2 Dir(s)  286,907,432,960 bytes free                         
Removing intermediate container 1234ad25a331                                
 ---> 0d5bee89f6fe                                                          
Step 4/4 : RUN mkdir c:\data2 && echo test>c:\data2\test.txt && dir c:\data2
 ---> Running in dc49b24311a4                                               
 Volume in drive C has no label.                                            
 Volume Serial Number is E4F0-4C31                                          
                                                                            
 Directory of c:\data2                                                      
                                                                            
02/12/2020  09:39 AM    <DIR>          .                                    
02/12/2020  09:39 AM    <DIR>          ..                                   
02/12/2020  09:39 AM                 7 test.txt                             
               1 File(s)              7 bytes                               
               2 Dir(s)  21,248,704,512 bytes free                          
Removing intermediate container dc49b24311a4                                
 ---> 8fa0aa959ff5                                                          
Successfully built 8fa0aa959ff5                                             
```

**Comment by pagdot** [comment]
I've tested it before and I'm pretty sure it didn't show up, but this works now.
When running the container the directory is empty though:

```
docker run --rm -it 495882bdc78b cmd /C dir C:\data
 Volume in drive C has no label.
 Volume Serial Number is 2E2F-F78E

 Directory of C:\data

02/12/2020  09:58 AM    <DIR>          .
02/12/2020  09:58 AM    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)  51,779,051,520 bytes free
```

**Comment by mat007** [comment]
Yes that’s because it’s a temporary unnamed volume which gets discarded, you can read more about volumes [here](https://docs.docker.com/engine/reference/builder/#volume) (most notably «Changing the volume from within the Dockerfile: If any build steps change the data within the volume after it has been declared, those changes will be discarded.») and also [here](https://stackoverflow.com/a/55516433/1195832).

**Comment by pagdot** [comment]
According to the docs:
> **Volumes on Windows-based containers**: When using Windows-based containers, the destination of a volume inside the container must be one of:
> - a non-existing or empty directory
> - a drive other than `C:`

Wouldn't that then mean that initialization of volumes at build-time isn't possible?

**Comment by mat007** [comment]
I’m not overly familiar with Windows-based containers but I think you might be right…

Anyway this issue tracker is for Docker Desktop the product, the upstream docker Windows container implementation is actually located at https://github.com/moby/moby.

**Comment by pagdot** [comment]
Ok, thank. I'll close this issue now
