### ISSUE TITLE
After update to 2.2.0.3 can't run containers anymore

### ISSUE THREAD

**Issue by drauch** [docker/for-win#5743]
`docker run -it mcr.microsoft.com/windows/servercore:1909 powershell` 

### Expected behavior

Should run the container and attach me to it so I can use powershell.

### Actual behavior

Command line window gets stuck, no output, no error, even CTRL+C doesn't work anymore. Opening a second command line and executing "docker ps -a" window gives the following output:

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional>docker ps -a
CONTAINER ID        IMAGE                                       COMMAND             CREATED             STATUS              PORTS               NAMES
03d528bbbe46        mcr.microsoft.com/windows/servercore:1909   "powershell"        49 minutes ago      Created                                 compassionate_elbakyan
```

Note: trying to attach to it via docker exec or even trying to remove it via docker rm results in hangs as well.

### Information
  - Is it reproducible? Yes. On two machines.
  - Is the problem new? Yes, after updating to 2.2.0.3.
  - Did the problem appear with an update? Yes, 2.2.0.3.

  - Windows Version: 1909
  - Docker Desktop Version: 2.2.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No.

Best regards,
D.R.

**Comment by mat007** [comment]
This seems to be working for me
```
Windows PowerShell                                                              
Copyright (C) Microsoft Corporation. All rights reserved.                       
                                                                                
Try the new cross-platform PowerShell https://aka.ms/pscore6                    
                                                                                
PS C:\> dir                                                                     
                                                                                
                                                                                
    Directory: C:\                                                              
                                                                                
                                                                                
Mode                LastWriteTime         Length Name                           
----                -------------         ------ ----                           
d-r---         2/9/2020   3:25 AM                Program Files                  
d-----         2/9/2020   3:16 AM                Program Files (x86)            
d-r---         2/9/2020   3:26 AM                Users                          
d-----        2/12/2020   9:20 AM                Windows                        
-a----        10/7/2019  10:32 PM           5510 License.txt                    
                                                                                
                                                                                
PS C:\>
```

Can you upload diagnostics (Troubleshoot windows) please?

**Comment by drauch** [comment]
1F16DA57-3563-4DA7-815A-CC59239E010F/20200212082631

**Comment by stephen-turner** [comment]
@drauch Also, what was the version you were upgrading from? 2.2.0.0 or 2.1.*? Thanks.

**Comment by stephen-turner** [comment]
@drauch Also, what was the version you were upgrading from? 2.2.0.0 or 2.1.*? Thanks.

**Comment by drauch** [comment]
2.2.0.0

But guess what, after running the Troubleshoot option, it worked again. But as soon as I executed:

```
docker run -it --isolation=Process mcr.microsoft.com/windows/servercore:1909 powershell
```
(note: this time using process isolation)

the hang was back. Is there a problem with process isolation? Is it possible that it doesn't detect an incompatibility between my Windows version 18363.592 and the container's 18363.657 version?

**Comment by pwuertz** [comment]
@drauch maybe this is related to https://hub.docker.com/_/microsoft-windows-servercore
```
Important: You might encounter issues when using Windows Server container
images for the February 11, 2020 security update release
```
Looks like one of the recent windows updates broke process isolation?

**Comment by stephen-turner** [comment]
Ah yes, I think https://support.microsoft.com/en-us/help/4542617/you-may-encounter-issues-when-using-windows-server-docker-container-im explains it. Thanks, @pwuertz. Closing this as a known Microsoft issue that we can't do anything about.

**Comment by Drewster727** [comment]
yeah, they sure as hell did break it. Just spent a bunch of time trying to figure out wtf was wrong after rolling in some 1909 nodes!
