### ISSUE TITLE
Docker.Core.Backend.BackendDestroyException: No answer from VM

### ISSUE THREAD

**Issue by spottedmahn** [docker/for-win#5753]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID:1E67C252-17EF-4210-9A57-FBA843DDE22E/20200212202152

### Expected behavior
no error

### Actual behavior
![image](https://user-images.githubusercontent.com/14079228/74374347-35c46b00-4dac-11ea-9425-d5ecbc879386.png)

### Information

  - Windows Version: Win10 v1909
  - Docker Desktop Version: 2.2.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. ```docker run -d --restart=always -p 127.0.0.1:23750:2375 -v /var/run/docker.sock:/var/run/docker.sock  alpine/socat  tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock``` ([related to getting WSL and docker talking](https://github.com/docker/for-win/issues/5737#issuecomment-584831851))
  2. restart docker desktop

**Comment by icyevilfantasy** [comment]
I#ve to confirm this. After i updated my Winndows 10 to Version "Win10 v1909" this morning, i got the same error/crash.

Any solutions to this problem yet?

**Comment by luke-pefi** [comment]
So I just installed Docker again for the first time since early 2019 and it looks like docker-toolbox is a "legacy" product now.  Fine, I install Docker Desktop and get this lovely error.  Now that wouldn't be so irksome if there was some way to tell it to use good old VirtualBox instead of that stinking Hyper-V BS that had _never_ worked for me (and I must have tried it at 5 different times at least).

Methinks you guys need to 1) keep supporting VirtualBox if Hyper-V is not ready for prime time 2) Fix that terrible Docker GUI thingy that displays a spinner forever with no user feedback.  Whatever happened to good old docker-machine?? Surely that awful contraption doesn't replace it... Sheesh

**Comment by vandernorth** [comment]
On Windows 10 1909 with Docker Desktop 2.2.0.3 I was able to get rid of the error after pressing "Reset to factory defaults" which created a new container in HyperV.

**Comment by dzoech** [comment]
I have the same problem on Windows 10 1909 with Docker Desktop 2.2.0.3.

Resetting to factory defaults didn't solve the problem.

**Comment by icyevilfantasy** [comment]
Resetting to factory defaults worked for me (but it's not good practice because you loose all images and volumes)

**Comment by spottedmahn** [comment]
@icyevilfantasy FYI: my root problem was port 2375 being reserved (by Hyper-V it appears).  [Once on reserved that port](https://github.com/docker/for-win/issues/5737#issuecomment-589988654) my problem went away.

**Comment by dzoech** [comment]
I could my issue by reinstalling Docker using the installer from the https://hub.docker.com/editions/community/docker-ce-desktop-windows/

My problem seemingly came from installing docker-desktop via chocolatey.

**Comment by glsetliff1** [comment]
Unfortunately none of these steps fixed the issue for me, but I am getting a different BackendDestroyException:

Docker.Core.Backend.BackendDestroyException:
One or more errors occurred.
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

  System.AggregateException:
  One or more errors occurred.
     at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
     at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
     at Docker.Backend.LifecycleClient.DockerStart()
     at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions, Credential credential)
     at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
  
     Docker.Core.HttpBadResponseException:
     unable to fetch daemon.json: Get http://unix/engine/daemon.json: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
        at Docker.Backend.HttpClientExtensions.<ParseResponseBodyAsJsonAsync>d__2`1.MoveNext()
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at Docker.Backend.HttpClientExtensions.<GetJsonAsync>d__0`1.MoveNext()

**Comment by klabranche** [comment]
I just did a reset to factory defaults to resolve this on my machine....

**Comment by davidxyz981** [comment]
I aslo meet this problem after I upgrade my windows10 to latest version 1909 ,any can help? 
Thank you.

**Comment by glsetliff1** [comment]
The solution that worked for me was to disable the Windows Subsystem for Linux.

https://www.tenforums.com/tutorials/46769-enable-disable-windows-subsystem-linux-wsl-windows-10-a.html

**Comment by dnperfors** [comment]
I had the same issue, looks like it can be solved by cleaning up the hosts file (C:\Windows\System32\driver\etc\hosts). Mine had 72 million lines, most of them empty, some were duplicate `host.docker.internal` and `gateway.docker.internal`, all with different ip's.
I just cleaned out my hosts file and reinstalled docker, so I probably need a reboot before I can confirm completely that the issue is fixed.

**Comment by sauravshaurya** [comment]
@dnperfors Wont work , i tried

**Comment by dnperfors** [comment]
@sauravshaurya, I didn’t see the issue since I updated docker and cleaned up my hosts file, but I still get empty lines In the hosts file whenever docker starts... But it could be that other applications triggered this issue because of my hosts file...

**Comment by adonisv79** [comment]
Its WSL2. it keeps getting issues on latest windows 10 against docker for some reason. Although Docker for Windows recommends it, I just disabled it and used hyper-V instead. works ok now
