### ISSUE TITLE
Latest Docker Desktop for Windows Fails to Start

### ISSUE THREAD

**Issue by djlawhead** [docker/for-win#5754]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 23071925-1B0B-48CB-AFF8-40B9C1B38F84/20200212174123

### Expected behavior

Docker engine for Windows starts without error.

### Actual behavior

Docker fails to start. Stack trace indicates timeout in connecting to underlying engine.

### Information

Clean install of Docker on Windows 10 Enterprise 1809.

  - Windows Version: Windows 10 Enterprise 1809
  - Docker Desktop Version: 2.2.0.3 (42716) (stable)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No.

#### Stack trace
```
Docker.Core.Backend.BackendDestroyException:
Timed out waiting for the lifecycle-server to start.
This may be the result of a slow environment or there may be a real problem.
This timeout can be increased by editing settings.json, value 'lifecycleTimeoutSeconds'.
This file is usually in C:\Users\(your username)\AppData\Roaming\Docker
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()
```

### Steps to reproduce the behavior

  1. Install docker 2.2.03.
  2. After installation, attempt to start docker.

**Comment by MateuszSobala** [comment]
The same happened for me. Sent diagnostic id 4A67EAD6-13CA-4E24-9A5F-BAD9EE1A3C6E/20200218092056.

**Comment by vidi42** [comment]
Happened to me as well, but after a few restarts it seems to have started working again. All my networks and containers are there as well.

Maybe adding `lifecycleTimeoutSeconds : 600` in C:\Users\(your username)\AppData\Roaming\Docker\settings.json as suggested in the stack trace could help

**Comment by glimmerphoenix** [comment]
Same problem here. Sent diagnostic id: 8F968C6B-7557-4429-81EF-49AF08D2386E/20200309095859. Adding `lifecycleTimeoutSeconds:600` to `settings.json` does not seem to fix the issue.

**Comment by dweggemans** [comment]
Increasing the timeout fixed the issue for me
