### ISSUE TITLE
Docker fails to start after installing 2.2.0.3

### ISSUE THREAD

**Issue by kylefender** [docker/for-win#5757]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: AA0C48D4-451C-4FC1-921A-12840688C192/20200213054505

### Expected behavior
After installing 2.2.0.3, Docker should start up normally.

### Actual behavior
Docker throws an error during startup:

```
Docker.Core.Backend.BackendDestroyException:
Unable to stop Hyper-V VM: The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.
at <ScriptBlock>, <No file>: line 90
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

  System.Management.Automation.RuntimeException:
  Unable to stop Hyper-V VM: The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.
  at <ScriptBlock>, <No file>: line 90
     at Docker.Backend.HyperV.HandleException(String action, Exception ex)
     at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters, PowerShellConfiguration config)
     at Docker.Backend.ContainerEngine.Linux.DoStop()
     at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
  
     System.IO.FileNotFoundException:
     The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.
```
     

### Information

  - Windows Version: Win 10 Enterprise, 1909, build 18363
  - Docker Desktop Version: 2.2.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Install latest stable build
  2. Restart computer

I originally tried upgrading from 2.2.0.0 but the upgrade process failed, reporting the error that it couldn't unmount the iso - this left Docker uninstalled. I restarted my machine and installed 2.2.0.3. I rebooted and Docker displayed the error above.

**Comment by imac-beep** [comment]
Having the same issue.

**Comment by frizzr** [comment]
Just FYI...this is probably a duplicate of [this issue](https://github.com/docker/for-win/issues/5834), which says they fixed this bug in the edge version of 2.2.2.0 (build 43066.) 

Direct download of the 43066 edge release here:

https://download.docker.com/win/edge/43066/Docker%20Desktop%20Installer.exe

**Comment by kylefender** [comment]
To fix it (for me), I had to update the `PSModulePath` (system environment variable) because it wasn't handling an array of strings. I removed the bad entry and added a new value. The values I have for that environment variable are:

C:\Program Files\WindowsPowerShell\Modules\
C:\Windows\System32\WindowsPowerShell\v1.0\Modules

**Comment by evilnerd** [comment]
> To fix it (for me), I had to update the `PSModulePath` (system environment variable) because it wasn't handling an array of strings. I removed the bad entry and added a new value. The values I have for that environment variable are:
> 
> C:\Program Files\WindowsPowerShell\Modules
> C:\Windows\System32\WindowsPowerShell\v1.0\Modules

You sir, are an absolute hero!
