### ISSUE TITLE
Stuck on "Sending build context to Docker daemon"

### ISSUE THREAD

**Issue by PetaPetaPeta** [docker/for-win#576]
### Expected behavior

I have an container that should have a build context of 32 mb. When I run `docker build .` I expect the container to be built.

### Actual behavior

When I run `docker build .` it is stuck on `Sending build context to Docker daemon 1.114 MB`. I have tried with the same image(private image) on a different laptop, but under the same setup and the result is the same. I have tr

### Information

  -  Diagnostic id: 690837A7-0988-4B89-B557-7EFCE92C6352/2017-03-13_13-47-44
  -  I am running this on Windows 10 with the newest version of Docker for Windows on the edge channel. The command is being run from "Bash on Ubuntu on Windows". It is set up with `DOCKER_HOST=tcp://127.0.0.1:2375`.
  -  Output of `docker version`:
```
Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

### Steps to reproduce the behavior

  1.  `mkdir src`
  2.  `dd if=/dev/zero of=src/output.dat  bs=32M  count=1`
  3.  Create a Dockerfile with contents:
```
FROM ubuntu:14.04

COPY src/ /opt
```
  4.  `docker build .`

**Comment by PetaPetaPeta** [comment]
I just attempted to update to the latest version on docker on unix such that server and client matches. 
```
Client:                                                                                                                                                                                                                               [9/1680] Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:57:58 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
```
This gives me the following:
```
➜  docker docker build .
Sending build context to Docker daemon 557.1 kB
```

**Comment by PetaPetaPeta** [comment]
I have found [this thread](https://forums.docker.com/t/sending-build-context-hangs/15364/8) which seems to document some of the same issues, but without a solution.
It should be noted that if I create a `docker-compose.yml`-file and try to build from there it functions as expected.

**Comment by friism** [comment]
I think this is a known bug in WSL: https://github.com/Microsoft/BashOnWindows/issues/1123#issuecomment-249452291

Fwiw I can't repro on my latest insider build so it's possible that they fixed it:

```
C:\Users\Michael Friis> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      15055  0
```

```
friism@LAPTOP-G8D4BRBC:~/repro/build-hang$ docker -H localhost:2375 build .
Sending build context to Docker daemon 33.56 MB
Step 1/2 : FROM ubuntu:14.04
 ---> 7c09e61e9035
Step 2/2 : COPY . /test
 ---> 676c3ca04b6e
Removing intermediate container 4581324384df
Successfully built 676c3ca04b6e
friism@LAPTOP-G8D4BRBC:~/repro/build-hang$
```

**Comment by ArthurZ** [comment]
In my case a co-worker advised to assign more runnable memory to Docker which helped.
