### ISSUE TITLE
Docker for Windows crash upon switch linux to windows

### ISSUE THREAD

**Issue by monger39** [docker/for-win#5761]
Hi,
I installed Docker for Windows. At some point in time I made a switch to Linux containers, 
and created a container for Jenkins. This all works fine. Over time I've had a few updates of
Docker itself.
Now, I would like to create a new container, i.e. a Jenkins Windows slave. But whenever I do
a "Switch to Windows containers" Docker goes into 'starting', and after a few minutes crashes
with an exception:
 "Docker.Core.Backend.BackendException:
Time out has expired and the operation has not been completed.
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
"
I've uploaded crash report with ID: E9F88F9D-89EA-495E-8DB9-B98398784E25/20200212143716

I've rebooted my system multiple times. I've even (after seeing hint somewhere) disabled Hyper-V,
then enabled it again (reboots after each). No luck.

From the Docker Dashboard, it looks as if I have no containers running. It actually shows only 1,
which is an (experimental) Docker-out-of-Docker Jenkins slave I created from the then running
master. 
However, when I run a "docker ps -a" I do see this same container, which appears to be running:

CONTAINER ID        IMAGE                COMMAND             CREATED             STATUS              PORTS               NAMES
0ce03496fa9f        jenkins/jnlp-slave   "jenkins-agent"     5 weeks ago         Created                                 nifty_curran

Also in the logs, I see a continuous stream of 

When I press delete in the Dashboard, Docker ask if I want to delete the container.

   [12:24:59.381][APIRequestLogger  ][Info   ] [d91b900e] <Server end> GET http://localhost/docker -> 200 OK (took 1ms)
   [12:24:59.389][APIRequestLogger  ][Info   ] [aae2c2b4] <Server start> GET http://localhost/docker

which looks as if this container is trying to reach the docker... ?

From what I have read, Docker should be able to switch anyway, but it doesn't work for me.

After deleting the container (from the GUI), quitting the Docker and restarting, strangely enough, 
on the cmdline (ps -a) I now get:
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                             PORTS               NAMES
c9bb3c6cb7ce        6c4eea1bc24a        "cmd.exe"           7 months ago        Exited (3221226219) 7 months ago                       vibrant_dewdney
ec7e69571af6        6c4eea1bc24a        "cmd.exe"           7 months ago        Exited (0) 7 months ago                                peaceful_ellis

And... the switch works ..

My feeling says that there is an issue withc the switch icw some (unmanaged/lost ?) container still running. 

I'm currently running:
- Docker Version: 2.2.0.3 (42716).
- OS: Windows 10 Enterprise, Build: 17134
- on a Dell Latitude 7490      
thx M.

PS: I tried uploading the log.txt directly from the Docker dir, but get an error that the filetype is not supported. Renaming to 'TXT' (uppercase extension does work). Kinda strange!
[log_man.TXT](https://github.com/docker/for-win/files/4198062/log_man.TXT)
details ..

**Comment by Arun4D** [comment]
hi
Any update? i am also getting the same error after upgrade to latest,
