### ISSUE TITLE
WSL backend, vmmem high memory usage

### ISSUE THREAD

**Issue by ksawerykarwacki** [docker/for-win#5766]
Docker Desktop 2.2.0.3
Windows 10 build 19041 (slow ring)

I use docker to build container with my dev env which contains Oracle DB and Apex and run some tests against it.

Unfortunately Oracle hogs almost all of my memory. Is there any way to limit maximum ram that can be used by the containers?

![image](https://user-images.githubusercontent.com/11694791/74453257-6f67a580-4e82-11ea-87c0-8d11e348edbc.png)

**Comment by stephen-turner** [comment]
Can this be set in Oracle? I imagine you would have the same problem if Oracle were running directly on the host.

**Comment by ksawerykarwacki** [comment]
Yeah but I would like to avoid artificial limit on my container based on my specific host

**Comment by simonferquel** [comment]
You can set memory limits on individual containers. You can also use ~/.wslconfig to configure wsl2 utility vm max memory.

**Comment by ksawerykarwacki** [comment]
After further investigation this seems to be caused by https://github.com/microsoft/WSL/issues/4166

**Comment by stephen-turner** [comment]
Closing as the bug is in Windows not Docker Desktop.
