### ISSUE TITLE
Installation failed - Failed to start service

### ISSUE THREAD

**Issue by sebascomeau** [docker/for-win#5768]
- [x] I have tried with the latest version of my channel (Stable or Edge)

### Expected behavior
Docker Desktop installed and running

### Actual behavior
Docker Desktop installation failed.

Exception message: Failed to start service: The service did not respond to the start or control request in a timely fashion

Screen capture:
![7E5ABFFB](https://user-images.githubusercontent.com/2814465/74460403-3966f900-4e63-11ea-9f9e-51efcbf23341.PNG)

Here's the installation log: [install-log.txt](https://github.com/docker/for-win/files/4199815/install-log.txt)

### Information

  - Windows Version:  Microsoft Windows 10 Enterprise (10.0.17134 N/A Build 17134 - 1803)
  - Docker Desktop Version: 2.2.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
 1. Download Docker Desktop Community Edition Stable latest version 2.2.0.3 
 2. Run the executable with admin privilege

**Comment by mat007** [comment]
Anything suspicious in the Windows Event Viewer?

**Comment by sebascomeau** [comment]
Service Control Manager - Error 01
![Service Control Manage - Error 01](https://user-images.githubusercontent.com/2814465/74532467-a3d07580-4f05-11ea-8229-dcd98ac87518.png)

Service Control Manager - Error 02
![Service Control Manage - Error 02](https://user-images.githubusercontent.com/2814465/74532469-a501a280-4f05-11ea-9408-d64a057fada6.png)

**Comment by sebascomeau** [comment]
I tried to install version 2.1.0.5 and got a Query Error (Security - Access is denied) when trying to start the Docker Desktop service while installing. I don't know what the service is trying to access when starting.

![DC75A798](https://user-images.githubusercontent.com/2814465/75346900-061a6600-5876-11ea-9136-c0b0bf7dfbee.PNG)

**Comment by sebascomeau** [comment]
I tried to install version 2.1.0.5 and got a Query Error (Security - Access is denied) when trying to start the Docker Desktop service while installing. I don't know what the service is trying to access when starting.

![DC75A798](https://user-images.githubusercontent.com/2814465/75346900-061a6600-5876-11ea-9136-c0b0bf7dfbee.PNG)

**Comment by sebascomeau** [comment]
I tried to install version 2.1.0.5 and got a Query Error (Security - Access is denied) when trying to start the Docker Desktop service while installing. I don't know what the service is trying to access when starting.

![DC75A798](https://user-images.githubusercontent.com/2814465/75347150-89d45280-5876-11ea-876f-fef8ab09573c.PNG)

**Comment by sebascomeau** [comment]
I'm suspecting the issue is caused by my HOMEDRIVE and HOMEPATH user variables pointing to a network drive. I tried to changed it to C: and \Users\(username) but Windows wont listen to my changes. Maybe a GPO enforce those values at runtime. I'm continuing to investigate.

**Comment by sebascomeau** [comment]
I give up until someone fix this. I set system variable HOME to C:\Users\%USERNAME% and this fixed my path when launching a bash terminal but not cmd. I tried with my admin account that don't have the weird variable configuration that my regular user have and the install hang trying to run the Docker Desktop backend service. Tried the version 2.2.0.3 and still have the same initial issue.

![Untitled](https://user-images.githubusercontent.com/2814465/75374412-a1293500-58a2-11ea-8e9c-227bbc7625eb.png)

**Comment by SINDHUN97** [comment]
Hi,
Facing same issue.I am trying to upgrade from Docker Desktop 2.1.0.3 to 2.2.0.5 getting Installation failed:The Server service is not started.Any solution?
![image](https://user-images.githubusercontent.com/46042598/79723799-05e19880-8304-11ea-973b-cd9fe081a4ab.png)

**Comment by sebascomeau** [comment]
No solution yet for my work computer but I successfully installed in on another computer at home without any problem. Could be caused by the security on my work computer.

**Comment by mat007** [comment]
@SINDHUN97 your problem looks different, it’s likely #5150

**Comment by mat007** [comment]
@sebascomeau when the installer hangs, are you able to look if there is any error in `%programdata%\DockerDesktop\service.txt`?
Do you still get that same error in the Windows Event Viewer?

**Comment by HongChongxi** [comment]
I am also getting the same error when installing the Stable release of Docker for Windows. I am using Windows 10 (Build: 19041). Can anybody help to advise?

![image](https://user-images.githubusercontent.com/52709640/84622252-1c286100-af0f-11ea-917a-66ce58a8349d.png)

**Comment by thundergs** [comment]
I am also getting the same error when installing Docker Desktop version 2.3 for Windows 10 Pro 2004. I tried both the Stable release and the Edge releases :
[install-log.txt](https://github.com/docker/for-win/files/4788678/install-log.txt)

![image](https://user-images.githubusercontent.com/20730180/84818457-61aa6400-afcb-11ea-8970-b8b08a4b5c98.png)

**Comment by mss1010** [comment]
I had the same issue, and the following solved it for me:

Restart all running Hyper-V services in task manager.

Before that, I uninstalled and reinstalled it couple of times, and deleted Docker directories in User\Appdata\Local and Program Files. Not sure if this is required, but in the end restarting a couple of related services fixed it for me.
