### ISSUE TITLE
net use fails to mount network drive

### ISSUE THREAD

**Issue by apetres** [docker/for-win#577]
### Expected behavior

After typing `net use * \\\\path` the output is  `The command completed successfully.` and the network drive is mounted.

### Actual behavior

It outputs `System error 64 has occurred. The specified network name is no longer available` and the drive is not mounted.

### Information

  - Diagnostic ID: 64ED47AF-047A-4425-86A4-627DFDE197DC/2017-03-13_15-56-19
  - docker version:
```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

### Steps to reproduce the behavior

 1. `docker run -it microsoft/windowsservercore` 
 2. Type `net use * \\existing-network-path`. You may use a letter instead of *, same result.

Note: the same command succeeds on the host.

**Comment by friism** [comment]
This works for me on Windows Server. I can mount a directory shared on the host. I use the default gateway as the IP address:

```
PS C:\> ipconfig

Windows IP Configuration


Ethernet adapter vEthernet (Container NIC c8fa165b):

   Connection-specific DNS Suffix  . : docker.com
   Link-local IPv6 Address . . . . . : fe80::d100:ff84:2128:fee0%18
   IPv4 Address. . . . . . . . . . . : 172.30.36.81
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . : 172.30.32.1
```

    PS C:\> net use * \\172.30.32.1\test
    Enter the user name for '172.30.32.1': Administrator
    Enter the password for 172.30.32.1:
    Drive Z: is now connected to \\172.30.32.1\test.
    
    The command completed successfully.

@PatrickLang might have more details

**Comment by friism** [comment]
@apetres do you have more details on your setup?

**Comment by apetres** [comment]
I did some more investigation. Mounting a shared directory situated on host works for me too. I also mounted successfully a shared drive from one of my coworker's machine. What I cannot mount is a samba drive running on linux (`\\share\folder`).

I tried the following scenarios:

- on host (Windows 10):
```
PS C:\> net use V: \\share\folder
The command completed successfully.
```

- on VM (Windows Server 2016):
```
PS C:\> net use V: \\share\folder
The command completed successfully.
```

- in container (microsoft/windowsservercore):
```
PS C:\> ping share
Pinging share [10.106.1.219] with 32 bytes of data:
Reply from 10.106.1.219: bytes=32 time<1ms TTL=62
Reply from 10.106.1.219: bytes=32 time=1ms TTL=62

PS C:\> net use V: \\share\folder
System error 64 has occurred.

The specified network name is no longer available.

PS C:\> net use V: \\10.106.1.219\folder
System error 64 has occurred.

The specified network name is no longer available.
```

The OS on the host is Windows 10 Version 1607 Build 14939.729 .
The output of `docker network inspect nat`:
```
[
    {
        "Name": "nat",
        "Id": "c329936c4bba7f9cf4630a2b14e60de0948a5229ba5842aa74b32b80a5d76a2e",
        "Created": "2017-03-16T11:57:17.6714772+02:00",
        "Scope": "local",
        "Driver": "nat",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "windows",
            "Options": null,
            "Config": [
                {
                    "Subnet": "192.168.160.0/20",
                    "Gateway": "192.168.160.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Containers": {
            "4a9d4b4721e99b74ecdb36918159d30cfedd656d99f4d210c76d3a697c197040": {
                "Name": "angry_heyrovsky",
                "EndpointID": "96c3ce24dfd09630ba7cd5720e9416b2af7218a9e4e4732c4a160ae2a23845b3",
                "MacAddress": "00:15:5d:da:8a:e0",
                "IPv4Address": "192.168.169.103/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.windowsshim.hnsid": "71e8a262-cbbd-46e2-9ee8-d0af6c27babb",
            "com.docker.network.windowsshim.networkname": "nat"
        },
        "Labels": {}
    }
]
```

It may be related to some restriction in our internal network configuration, but I doubt that because I mounted the shared drive in a Linux container with the command:
```
mount -t cifs //share/folder /mnt/share
```

**Comment by apetres** [comment]
Tried the `New-PSDrive` cmdlet, got the same result:
```
PS C:\> New-PSDrive -Name 'Q' -Root '\\share\folder' -Persist -PSProvider FileSystem
New-PSDrive : The network path was not found
At line:1 char:1
+ New-PSDrive -Name 'Q' -Root '\\share\folder' -Persist -PSProvider Fi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Q:PSDriveInfo) [New-PSDrive], Win32Exception
    + FullyQualifiedErrorId : CouldNotMapNetworkDrive,Microsoft.PowerShell.Commands.NewPSDriveCommand
```

**Comment by kejsiStruga** [comment]
Hi, did you find any solution on this issue ? I am facing same problem on win server. Works fine on my local machine though.

**Comment by nkamatam** [comment]
I have the same problem. Did anyone find a solution for this?
