### ISSUE TITLE
Container dies for every 30 minutes on Windows WSL

### ISSUE THREAD

**Issue by drajpal** [docker/for-win#5770]
I am using Docker For Windows (Desktop) on Windows 10 WSL Ubuntu. Everything was running fine until suddenly container would die after running for a while(at most 30 minutes). The underline exception as below. In order to make it work, I need to restart docker for every 30 minutes.

Errors from Event Viewer:
Faulting application name: vmcompute.exe, version: 10.0.19033.1, time stamp: 0x46d5ff54
Faulting module name: ntdll.dll, version: 10.0.19033.1, time stamp: 0xf262997f
Exception code: 0xc0000409
Fault offset: 0x00000000000a00b0
Faulting process id: 0x2f20
Faulting application start time: 0x01d5e121c1aeb270
Faulting application path: C:\WINDOWS\system32\vmcompute.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 5ef282fd-37ca-4095-9116-12c6d93283c1
Faulting package full name:
Faulting package-relative application ID:

Faulting application name: vmcompute.exe, version: 10.0.19033.1, time stamp: 0x46d5ff54
Faulting module name: ntdll.dll, version: 10.0.19033.1, time stamp: 0xf262997f
Exception code: 0xc0000409
Fault offset: 0x00000000000a00b0
Faulting process id: 0x2f20
Faulting application start time: 0x01d5e121c1aeb270
Faulting application path: C:\WINDOWS\system32\vmcompute.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 5ef282fd-37ca-4095-9116-12c6d93283c1
Faulting package full name:
Faulting package-relative application ID:

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: ACCF5D99-B837-47B4-9441-BE54F529611F/20200213190111

### Expected behavior
Not Expecting the crash
### Actual behavior
Crashing for every 30 minutes
### Information
##Docker Version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
 Kubernetes:
  Version:          Unknown
  StackAPI:         Unknown

  - Windows Version: Windows 10 Enterprise (Ubuntu 18.04)
  - Docker Desktop Version: 2.2.0.0
  - Running on VM (VMWare):

### Steps to reproduce the behavior
1. Setup docker for desktop on a Windows WSL machine.

**Comment by simonferquel** [comment]
It looks like the whole wsl2 vm is crashing in your case.
Also you are using a fairly old insider build (19033 from your logs). Can you try to move to a more up-to-date one and see if the problem still occurs ?

**Comment by MichaelVach** [comment]
I have seen the same behavior with newer versions as well.
WSL 2 based docker engine running on VMWare ESXi U2

Docker:
Version: 2.2.2.0 (43066)
Channel: edge
Sha1: 58f099c0ccae55d230bab0d0663f9294e44cb8b6
Started on: 2020/03/06 14:39:30.846
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 2004
Build: 19041
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406

EventLog 1:
Faulting application name: vmcompute.exe, version: 10.0.19041.84, time stamp: 0xe0012492
Faulting module name: ntdll.dll, version: 10.0.19041.84, time stamp: 0x74437382
Exception code: 0xc0000409
Fault offset: 0x00000000000a00d0
Faulting process id: 0x3014
Faulting application start time: 0x01d5f3a4b4e7270e
Faulting application path: C:\WINDOWS\system32\vmcompute.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 96aad4a8-77ab-4555-898a-e1eadc85ec6c
Faulting package full name: 
Faulting package-relative application ID:

EventLog 2:
Faulting application name: vmwp.exe, version: 10.0.19041.84, time stamp: 0x7110e2a5
Faulting module name: ntdll.dll, version: 10.0.19041.84, time stamp: 0x74437382
Exception code: 0xc0000409
Fault offset: 0x00000000000a00d0
Faulting process id: 0x578
Faulting application start time: 0x01d5f3a4b4edebf7
Faulting application path: C:\WINDOWS\System32\vmwp.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 13d9292b-078f-4bee-9fba-5b9b9a01ba20
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Outek** [comment]
This is still an issue.
Win 10 Version 2004 (19035.1)
Docker edge 2.3.0.1 44875

Containers dying every 10-30min.

**Comment by JakeAi** [comment]
I also have this issue. It happens exactly every 30 minutes. I am on a fresh Server 2019 install. I installed Docker via the powershell commands on the website. You can see below the logs restart exactly on the 30 minute mark. Also, i have the same Event Viewer logs as posted above by @MichaelVach .
```
2020/08/11 07:34:54 server: Reverse tunnelling enabled,
2020/08/11 07:34:54 server: Fingerprint ,
2020/08/11 07:34:54 server: Listening on 0.0.0.0:8000...,
2020/08/11 07:34:54 Starting Portainer 1.24.1 on :9000,
2020/08/11 07:34:54 [DEBUG] [chisel, monitoring] [check_interval_seconds: 10.000000] [message: starting tunnel management process],
2020/08/11 08:04:52 Warning: the --template-file flag is deprecated and will likely be removed in a future version of Portainer.,
2020/08/11 08:04:53 Templates already registered inside the database. Skipping template import.,
2020/08/11 08:04:53 server: Reverse tunnelling enabled,
2020/08/11 08:04:53 server: Fingerprint ,
2020/08/11 08:04:53 server: Listening on 0.0.0.0:8000...,
2020/08/11 08:04:53 Starting Portainer 1.24.1 on :9000,
2020/08/11 08:04:53 [DEBUG] [chisel, monitoring] [check_interval_seconds: 10.000000] [message: starting tunnel management process],
2020/08/11 08:34:53 Warning: the --template-file flag is deprecated and will likely be removed in a future version of Portainer.,
2020/08/11 08:34:53 Templates already registered inside the database. Skipping template import.,
2020/08/11 08:34:53 server: Reverse tunnelling enabled,
2020/08/11 08:34:53 server: Fingerprint ,
2020/08/11 08:34:53 server: Listening on 0.0.0.0:8000...,
2020/08/11 08:34:53 Starting Portainer 1.24.1 on :9000,
2020/08/11 08:34:53 [DEBUG] [chisel, monitoring] [check_interval_seconds: 10.000000] [message: starting tunnel management process],
2020/08/11 09:04:53 Warning: the --template-file flag is deprecated and will likely be removed in a future version of Portainer.,
2020/08/11 09:04:54 Templates already registered inside the database. Skipping template import.,
2020/08/11 09:04:54 server: Reverse tunnelling enabled,
2020/08/11 09:04:54 server: Fingerprint ,
2020/08/11 09:04:54 server: Listening on 0.0.0.0:8000...,
2020/08/11 09:04:54 Starting Portainer 1.24.1 on :9000,
2020/08/11 09:04:54 [DEBUG] [chisel, monitoring] [check_interval_seconds: 10.000000] [message: starting tunnel management process],
2020/08/11 09:30:06 http error: Invalid JWT token (err=Invalid JWT token) (code=401),
2020/08/11 09:34:50 Warning: the --template-file flag is deprecated and will likely be removed in a future version of Portainer.,
2020/08/11 09:34:51 Templates already registered inside the database. Skipping template import.,
2020/08/11 09:34:51 server: Reverse tunnelling enabled,
2020/08/11 09:34:51 server: Fingerprint ,
2020/08/11 09:34:51 server: Listening on 0.0.0.0:8000...,
2020/08/11 09:34:51 Starting Portainer 1.24.1 on :9000,
2020/08/11 09:34:51 [DEBUG] [chisel, monitoring] [check_interval_seconds: 10.000000] [message: starting tunnel management process],
2020/08/11 09:37:45 http error: Invalid JWT token (err=Invalid JWT token) (code=401),
2020/08/11 10:04:52 Warning: the --template-file flag is deprecated and will likely be removed in a future version of Portainer.,
2020/08/11 10:04:53 Templates already registered inside the database. Skipping template import.,
2020/08/11 10:04:53 server: Reverse tunnelling enabled,
2020/08/11 10:04:53 server: Fingerprint ,
2020/08/11 10:04:53 server: Listening on 0.0.0.0:8000...,
2020/08/11 10:04:53 Starting Portainer 1.24.1 on :9000,
2020/08/11 10:04:53 [DEBUG] [chisel, monitoring] [check_interval_seconds: 10.000000] [message: starting tunnel management process],
2020/08/11 10:04:53 http error: Invalid JWT token (err=Invalid JWT token) (code=401),
2020/08/11 10:04:53 http error: Invalid JWT token (err=Invalid JWT token) (code=401),
2020/08/11 10:34:53 Warning: the --template-file flag is deprecated and will likely be removed in a future version of Portainer.,
2020/08/11 10:34:54 Templates already registered inside the database. Skipping template import.,
2020/08/11 10:34:54 server: Reverse tunnelling enabled,
2020/08/11 10:34:54 server: Fingerprint ,
2020/08/11 10:34:54 server: Listening on 0.0.0.0:8000...,
2020/08/11 10:34:54 Starting Portainer 1.24.1 on :9000,
2020/08/11 10:34:54 [DEBUG] [chisel, monitoring] [check_interval_seconds: 10.000000] [message: starting tunnel management process],
2020/08/11 11:04:52 Warning: the --template-file flag is deprecated and will likely be removed in a future version of Portainer.,
2020/08/11 11:04:53 Templates already registered inside the database. Skipping template import.,
2020/08/11 11:04:53 server: Reverse tunnelling enabled,
2020/08/11 11:04:53 server: Fingerprint ,
2020/08/11 11:04:53 server: Listening on 0.0.0.0:8000...,
2020/08/11 11:04:53 Starting Portainer 1.24.1 on :9000,
2020/08/11 11:04:53 [DEBUG] [chisel, monitoring] [check_interval_seconds: 10.000000] [message: starting tunnel management process],
2020/08/11 11:34:53 Warning: the --template-file flag is deprecated and will likely be removed in a future version of Portainer.,
2020/08/11 11:34:53 Templates already registered inside the database. Skipping template import.,
2020/08/11 11:34:53 server: Reverse tunnelling enabled,
2020/08/11 11:34:53 server: Fingerprint ,
2020/08/11 11:34:53 server: Listening on 0.0.0.0:8000...,
2020/08/11 11:34:53 Starting Portainer 1.24.1 on :9000,
2020/08/11 11:34:53 [DEBUG] [chisel, monitoring] [check_interval_seconds: 10.000000] [message: starting tunnel management process],
2020/08/11 12:04:52 Warning: the --template-file flag is deprecated and will likely be removed in a future version of Portainer.,
2020/08/11 12:04:53 Templates already registered inside the database. Skipping template import.,
2020/08/11 12:04:53 server: Reverse tunnelling enabled,
2020/08/11 12:04:53 server: Fingerprint ,
2020/08/11 12:04:53 server: Listening on 0.0.0.0:8000...,
2020/08/11 12:04:53 Starting Portainer 1.24.1 on :9000,
2020/08/11 12:04:53 [DEBUG] [chisel, monitoring] [check_interval_seconds: 10.000000] [message: starting tunnel management process],
2020/08/11 12:34:53 Warning: the --template-file flag is deprecated and will likely be removed in a future version of Portainer.,
2020/08/11 12:34:54 Templates already registered inside the database. Skipping template import.,
2020/08/11 12:34:54 server: Reverse tunnelling enabled,
2020/08/11 12:34:54 server: Fingerprint ,
2020/08/11 12:34:54 server: Listening on 0.0.0.0:8000...,
2020/08/11 12:34:54 Starting Portainer 1.24.1 on :9000,
2020/08/11 12:34:54 [DEBUG] [chisel, monitoring] [check_interval_seconds: 10.000000] [message: starting tunnel management process],
2020/08/11 13:04:53 Warning: the --template-file flag is deprecated and will likely be removed in a future version of Portainer.,
2020/08/11 13:04:53 Templates already registered inside the database. Skipping template import.,
2020/08/11 13:04:53 server: Reverse tunnelling enabled,
2020/08/11 13:04:53 server: Fingerprint ,
2020/08/11 13:04:53 server: Listening on 0.0.0.0:8000...,
2020/08/11 13:04:53 Starting Portainer 1.24.1 on :9000,
2020/08/11 13:04:53 [DEBUG] [chisel, monitoring] [check_interval_seconds: 10.000000] [message: starting tunnel management process],
2020/08/11 13:34:53 Warning: the --template-file flag is deprecated and will likely be removed in a future version of Portainer.,
2020/08/11 13:34:54 Templates already registered inside the database. Skipping template import.,
2020/08/11 13:34:54 server: Reverse tunnelling enabled,
2020/08/11 13:34:54 server: Fingerprint ,
2020/08/11 13:34:54 server: Listening on 0.0.0.0:8000...,
2020/08/11 13:34:54 Starting Portainer 1.24.1 on :9000,
2020/08/11 13:34:54 [DEBUG] [chisel, monitoring] [check_interval_seconds: 10.000000] [message: starting tunnel management process],
2020/08/11 14:04:53 Warning: the --template-file flag is deprecated and will likely be removed in a future version of Portainer.,
2020/08/11 14:04:54 Templates already registered inside the database. Skipping template import.,
2020/08/11 14:04:54 server: Reverse tunnelling enabled,
2020/08/11 14:04:54 server: Fingerprint ,
2020/08/11 14:04:54 server: Listening on 0.0.0.0:8000...,
2020/08/11 14:04:54 Starting Portainer 1.24.1 on :9000,
2020/08/11 14:04:54 [DEBUG] [chisel, monitoring] [check_interval_seconds: 10.000000] [message: starting tunnel management process],
```

**Comment by JakeAi** [comment]
Updating VMWare tools solves the problem for me. Anything over 11.0.6 will fix this issue. Apparently not a Docker issue.

**Comment by MakGulati** [comment]
> Updating VMWare tools solves the problem for me. Anything over 11.0.6 will fix this issue. Apparently not a Docker issue.

could be please explain how that can be done?
also i think vmware is a premium service so are there opensource alternatives for that?
Thanks a lot.
