### ISSUE TITLE
Support for Docker on Windows Home Insider build removed?

### ISSUE THREAD

**Issue by tsuki42** [docker/for-win#5779]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Successful installation of Edge version on Windows Home Insider build 2004(19041.21)
### Actual behavior
The 2.1.8.0(41944) version of Docker Desktop (Edge channel) is working fine but the updates are no longer supported.
![image](https://user-images.githubusercontent.com/22864071/74583898-34847f80-4ff2-11ea-871e-7dffa84ef544.png)
I also tried downloading the latest Edge build but it couldn't install. Has the support for WSL2 on Home Edition been disabled for now? If yes, when shall it be available again?

### Information

  - Windows Version: Windows Home Insider build 2004 (19041.21)
  - Docker Desktop Version: 2.1.8.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Download latest Docker Desktop Community from Edge channel 
  2. Try installing on the aforementioned windows machine.

**Comment by stephen-turner** [comment]
@tsuki42 Apologies for the confusion. 2.1.8.0 was a private build, not a publicly released build. The Windows Home support has not yet reached the public builds. It's coming soon, but you might want to not take 2.2.1.0 and wait for 2.2.2.0.
