### ISSUE TITLE
After upgrade to 2.2.0.3 (42716) D drive cannot be shared anymore

### ISSUE THREAD

**Issue by jwdejong** [docker/for-win#5780]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 58E8BEF1-7699-48C7-98AE-992C8E6A0CFB/20200215080258

### Expected behavior
I expect to see all my drives under Resources -> file sharing, but I only see the C drive. This wasn't the case in the previous version that I had installed.

### Actual behavior
The D drive is not listed and cannot be shared (used as a volume for containers).

### Information

The problem is 'reporducible' on my system.
The problem arose after the upgrade to 2.2.0.3

  - Windows Version: Windows 10 Pro
  - Docker Desktop Version: 2.2.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

Go to Settings -> Resources -> File Sharing. D drive is not listed (but this is probably environment specific?)

**Comment by jlucktay** [comment]
I have a similar issue with a USB external drive, also under Windows 10 Pro.
After I attach the drive, the drive letter "D" does not show up under Docker > Settings > Resources > File Sharing.
I have to leave the USB drive connected and reboot the PC, then D drive will show up in File Sharing and can be mounted as a volume into a new container.

**Comment by jwdejong** [comment]
Ok thanks, the drive that isn't visible is encrypted (bitlocker) and not available at startup (as I have to unlock it first). I will try to remove the encryption to see if this fixes the problem for now. In the previous version I did not experience this issue so hopefully it will be resolved soon.

**Comment by stephen-turner** [comment]
I think this is the same as #5725, so closing this copy. (Let me know if I'm wrong and I'll reopen it).
