### ISSUE TITLE
Time difference in docker containers vs host machine after Windows sleep

### ISSUE THREAD

**Issue by inliquid** [docker/for-win#5781]
Have been experiencing this issue quite for a while with `Docker Desktop for Windows Edge`. After Windows has slept for some time, local time in docker containers will be different to that of host machine. Restart of Docker solves the problem.

**Comment by liayn** [comment]
I can confirm this issue, which is present for me for ages. Seems to be a HyperV / Moby thing.

**Comment by stephen-turner** [comment]
Thanks for the report, @inliquid. Closing as a dupe of #5593.
