### ISSUE TITLE
After upgrading to Docker 2.2.03 unable to install stable/rabbitmq

### ISSUE THREAD

**Issue by VenkateshSrini** [docker/for-win#5782]
i'm trying to install the using the command
helm install --name rabbitmq --set rabbitmq.username=user,rabbitmq.password=PASSWORD stable/rabbitmq.
I have even tried the option

helm install --name rabbitmq --set rabbitmq.username=user,rabbitmq.password=PASSWORD,volumePermissions.enabled=true stable/rabbitmq

rabbit mq is crashing with error

> init terminating in do_boot ({error,{could_not_write_file,/opt/bitnami/rabbitmq/var/lib/rabbitmq/mnesia/rabbit@rabbitmq-0.rabbitmq-headless.default.svc.cluster.local/cluster_nodes.config,ebusy}})
> {"init terminating in do_boot",{error,{could_not_write_file,"/opt/bitnami/rabbitmq/var/lib/rabbitmq/mnesia/rabbit@rabbitmq-0.rabbitmq-headless.default.svc.cluster.local/cluster_nodes.config",ebusy}}}

When I down grade the same to 2.1.* with Kubernetes v1.14.8 it works without any issues
### Expected behavior
The Rabbit MQ pod in Kubernenete should run with out an issues. 
### Actual behavior
The rabbitMQ in kubernetes is crashing
### Information
  - Windows Version: Windows 10
  - Docker Desktop Version: 2,2,03
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Running on 
Laptop using Hyper V
  - Helm version :- v2.13.1
   - Kubernetes on Docker for Desktop (windows) :- v1.15.5
   - Which chart:stabl/rabbitmq

### Steps to reproduce the behavior

1) Upgrade or install the 2.2.03 version of Docker. 
2) Install rabbitmq as stated above using helm chart

**Comment by JoostvdB94** [comment]
I have the same issue,

May have something to do with the new way of using filesystems
https://www.docker.com/blog/new-filesharing-implementation-in-docker-desktop-windows/

**Comment by JoostvdB94** [comment]
Possible duplicate of #5665

**Comment by VenkateshSrini** [comment]
Yeah. But then I think they should do something the existing container works without any breakage. Also in Kubernetes, I'm not sure how we will add such volume mounts stated in the above link while executing the HELM charts

**Comment by robbaman** [comment]
It appears 2.2.0.4 is out now, does anyone know if this problem is fixed in this version? I'm afraid to try and break my machine.

**Comment by VenkateshSrini** [comment]
Hi,
Any update on the issue. Will this https://github.com/docker/for-win/issues/6646 resolve the rabbit MQ issue also or something else needs to be done ?
