### ISSUE TITLE
Docker Desktop Unable to Bind to socket, enters crashes loop in 2.2.0.3

### ISSUE THREAD

**Issue by demospace** [docker/for-win#5785]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: EBB19118-EAC6-4BE1-8DC6-FEAFE39C1A67/20200215170505

### Expected behavior
Docker Desktop starts and continues to run.

### Actual behavior
After upgrading to 2.2.0.3, docker desktop enters a crash loop.

### Information

  - Windows Version: 10.0.18362
  - Docker Desktop Version: 2.2.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

The first error in log.txt is in vpnkit.exe relating to hosts file.
Fata Error occurs on TCP listen on port 2375: listen tcp 127.0.0.1:2375: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

DD worked fine prior to the update.

I updated to 2.2.0.3 in order to use docker desktop with the Windows Wireguard VPN client which was not possible in prior versions with my network config.

Also for the record: it looks like the Docker VNAT switch is missing in my Hyper-V config after update. No changes were made to my Hyper-V config except the Docker upgrade.

**Comment by naourass** [comment]
Check this solution : https://github.com/docker/for-win/issues/5811

**Comment by demospace** [comment]
Upgraded to Win10 19041 solved this for me.
