### ISSUE TITLE
Unable to open Docker after installing in Window 10

### ISSUE THREAD

**Issue by es2012** [docker/for-win#5788]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:AD8CA28F-A436-4B83-986E-F75B0483DC80/20200216065129

### Information

  - Windows Version: Win 10 Pro
  - Docker Desktop Version: Latest Version(Recently download after sign up)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. … Download latest version of Docker
  2. … Install with all the checkboxes checked and run the Docker after installation completes.

**Comment by naourass** [comment]
Check this solution : https://github.com/docker/for-win/issues/5811
