### ISSUE TITLE
Cannot check shared drives

### ISSUE THREAD

**Issue by kirillsmartdriving** [docker/for-win#579]
### Expected behavior
I go to Settings->Shared Drives and set checkbox on my C: drive. After i press apply and input my credentials (administrator). And i want to see than checkbox with drive C: is checked.

### Actual behavior

But i see than checkbox on my drive C: loose checked

### Information

  - Diagnostic ID:D102530D-7536-45B9-8929-D95B0A54207A/2017-03-13_19-41-10

### Steps to reproduce the behavior

  1. Go to Settings -> Shared Drives
  2. Set checkbox on C:

I has error in log file:
Unable to mount C drive: standard_init_linux.go:178: exec user process caused "exec format error"

**Comment by thasmo** [comment]
I'm experiencing the same. Activating a new shared drive asks for credentials and after confirming by clicking on "okay", the dialog closes and the checkmark is removed from the drive. There's also no new share created on the drive/HDD itself when looking at it's share options via Windows explorer.

This happens after upgrading to `17.03.0-ce-win1 (10296)` (I think).

**Comment by thasmo** [comment]
I solved this by reinstalling `Docker for Windows` completely.

**Comment by kirillsmartdriving** [comment]
After reinstalling latest stable version, bug not reproduced. GT, GJ!

**Comment by geedamed** [comment]
Still happening for me, Docker for Windows Version 17.03.1-ce-win5 (10743), Channel: stable, b18e2a5.

Diagnostic ID: F3CBCC80-B553-4924-9A36-B8CCBDC577E9/2017-03-30_11-12-39

**Comment by geedamed** [comment]
Sorry for piggybacking a closed issue, solved mine by turning on the SSDP Discovery and UPnP Device Host services (they run automatically by default).

**Comment by kirillsmartdriving** [comment]
@geedamed great thanks Gabriel!

**Comment by wieslawo** [comment]
I have the same issue, start UPnP Device Host resolve problem
