### ISSUE TITLE
Volume mounted as folder causes 'file exists' error

### ISSUE THREAD

**Issue by RichardForshaw** [docker/for-win#5792]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E8D6BAD9-7BBD-4788-8CE4-4CD59F2C16A2/20200217044508

### Expected behavior
Docker container starts with specified mounts

### Actual behavior
Docker container will not start

### Information

  - Windows Version: 10
  - Docker Desktop Version: 2.2.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

I recently installed the latest Docker Desktop upgrade (2.2.0.3) and when I tried to start my containers I experienced the same problem as described in issue #5516, despite running the version with the fix.

Prior to updating the problem was not present (I cannot remember the previous version that I had)

After some more investigation I realised I have a special case where I have a separate windows partition which I mount within a subfolder of 'C' (my user directory):

![image](https://user-images.githubusercontent.com/8829039/74624588-0040c880-5184-11ea-8ff0-7ef121447757.png)

This could be a special case of #5516 which is still not handled.

### Steps to reproduce the behavior

  1. Mount a volume as a folder in Windows
  2. `docker container run --rm -v "C:\Users:/data" alpine ls /data` will work as expected
  3. `docker run --rm -v ${PWD}:/data alpine` (or using the full path to the mounted volume) will produce the same error as #5516.

**Comment by RichardForshaw** [comment]
Note: If I also mount the partition as a different drive letter and refer to that location in the example command, I am prompted to share the drive but if I click 'Share It' I get the message:

```
C:\Program Files\Docker\Docker\resources\bin\docker.exe: Error response from daemon: status code not OK but 500: {"Message":"Unhandled exception: Drive sharing failed for an unknown reason"}.
```

**Comment by cslovell** [comment]
I'm also on 2.2.0.3 and having similar volume issues. Commenting out the volumes works and produces "hello, world!". With volumes defined, it shows 

````
ERROR: for 5e5cabcf4e10_data-proc-training_code_1  Cannot start service code: error while creating mount source path '/host_mnt/c/Development/repos/data-proc-training/input': mkdir /host_mnt/c/Development: file exists

ERROR: for code  Cannot start service code: error while creating mount source path '/host_mnt/c/Development/repos/data-proc-training/input': mkdir /host_mnt/c/Development: file exists
ERROR: Encountered errors while bringing up the project.
````

docker-compose.yml
```
version: '3.7'

services:
  code:
    image: 'ddd'
    build: 
      context: ./code
      dockerfile: Dockerfile
    volumes: 
      - ./output:/mnt/out
      - ./input:/mnt/in
  ```

Directory has the following structure: 

```
code\
    app.py
    Dockerfile
    requirements.txt
input\
    data.csv
output\
.env
docker-compose.yml
```

**Comment by ravikumars** [comment]
I will add that I am facing the same issue where I cannot share/mount the volume from Windows 10 to the docker container.
Docker Desktop: 2.2.0.5(43884)

In my case I have a .vhdx file that I first mount as a drive or folder to the windows machine. From there I am trying to mount it to the container

**Comment by msfayed** [comment]
Hi, 
I am facing the same issue with partition mounted as a subfolder, did any one found a solution or workaround ?

**Comment by mshgh** [comment]
I am facing it too. In my case I use permanent subst to create drive D: as described in https://en.wikipedia.org/wiki/SUBST#Persisting_across_reboots

I have found workaround for me (not that I like it...) NTFS junction created by `mklink.exe` works for me actually. And I do not need to point to the "real" folder, junction to substed drive works just fine.
`D: substed as C:\DISK_D` and `C:\git linked to D:\git`.

```
C:\>dir
 Volume in drive C is WIN10
 Volume Serial Number is xxxx-xxxx

 Directory of C:\

...
31.05.2020  19:16    <JUNCTION>     git [D:\git]
...
```
