### ISSUE TITLE
Issues without logs and details cannot be debugged, and will be closed.

### ISSUE THREAD

**Issue by kia9372** [docker/for-win#5795]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
Yes, they will.
