### ISSUE TITLE
Drive assigned a mount point of folder path throws error when in docker-compose volume

### ISSUE THREAD

**Issue by cslovell** [docker/for-win#5810]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6F42A688-5BEB-4077-81C8-CADC27E608EF/20200218211753

### Expected behavior
Consider a system with a hard drive mounted as a folder-mounted volume in C:\development, and a project in the directory C:\development\project. Inside this, there is a docker-compose.yml file:
```
version: '3.1'

services:
  code:
    image: 'ddd'
    build: 
      context: ./code
      dockerfile: Dockerfile
    #volumes: 
      #- './output:/app-data/out'
      #- ./input:/app-data/in
```
The expectation is that "docker-compose up" works both with volumes commented out and without. 

### Actual behavior
In this situation, docker-compose up works without volumes. With volumes enabled, the following error is thrown:
```
Starting data-proc-training_code_1 ... error

ERROR: for data-proc-training_code_1  Cannot start service code: error while creating mount source path '/host_mnt/c/Development/repos/data-proc-training/output': mkdir /host_mnt/c/Development: file exists

ERROR: for code  Cannot start service code: error while creating mount source path '/host_mnt/c/Development/repos/data-proc-training/output': mkdir /host_mnt/c/Development: file exists
ERROR: Encountered errors while bringing up the project.
``` 
If the project is moved to a folder not on the drive mounted as a folder path, it works in both scenarios. 

### Information
 - The problem is reproducible. 
 - The folder C:\Development is a folder-mounted volume

  - Windows Version: Windows 10 Enterprise, 10.0.16299 Build 16299.
  - Docker Desktop Version: 2.2.0.3 (42716), stable. Engine: 19.03.5, Compose: 1.25.4, Notary: 0.6.1, Kubernetes: v1.15.1, Notary: 0.6.1, Credential Helper: 0.6.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior
1. Go to computer management, and map a secondary drive to have an additional folder mount. 
2. Navigate to this drive and create a simple directory with a docker-compose file that runs a hello world example
3. Run docker-compose up to ensure it works. 
4. Add a volume binding and run docker-compose up again. 

Run docker-compose up with a volume assigned as above. 
```
volumes: 
      - './output:/app-data/out'
```
5. There should be an error as above. 

### Workaround
Change folder to be lettered drive instead of folder-mount.

**Comment by UTAS-Nick-Howden** [comment]
I have a similar issue with volume mounts using docker-desktop version 2.2.0.3 (the mounts worked with 2.2.0.0)

ERROR: for xxx-server  Cannot start service xxx-server: error while creating mount source path '/host_mnt/c/VirtPart/Drive.D/Demo_Data/Docker/netdata': mkdir /host_mnt/c/VirtPart: operation not permitted
ERROR: Encountered errors while bringing up the project.


version: '3'
services:
  netdata:
    image: netdata/netdata
    hostname: host.docker.internal 
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./:/tmp/local
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
