### ISSUE TITLE
Docker Service is not starting

### ISSUE THREAD

**Issue by rocky010563** [docker/for-win#5820]
Using Windows 10 Enterprise 10.0.18362.
Installed Docker Desktop 2.2.0.42716.
The Docker Desktop Service will not run. Event Viewer has the following information:
Faulting application name: com.docker.service, version: 2.2.0.42716, time stamp: 0x8395d74e
Faulting module name: ntdll.dll, version: 10.0.18362.657, time stamp: 0x64d10ee0
Exception code: 0xc0000005
Fault offset: 0x000000000001e6a6
Faulting process id: 0x63f4
Faulting application start time: 0x01d5e73d1d337b23
Faulting application path: C:\Program Files\Docker\Docker\com.docker.service
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: c0de912b-2a12-42b8-a5c0-67758f19f8d4
Faulting package full name: 
Faulting package-relative application ID: 

Docker version produces:
C:\WINDOWS\system32>docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

**Comment by rocky010563** [comment]
Tried to uninstall (so that I can reinstall) and it fails with a similar access violation:
Faulting application name: Docker Desktop Installer.exe, version: 2.2.0.42716, time stamp: 0x5e41b886
Faulting module name: sysfer.dll, version: 14.2.5078.2000, time stamp: 0x5d48ecce
Exception code: 0xc0000005
Fault offset: 0x000000000001c79a
Faulting process id: 0x597c
Faulting application start time: 0x01d5e76547de9f67
Faulting application path: C:\Program Files\Docker\Docker\Docker Desktop Installer.exe
Faulting module path: C:\WINDOWS\System32\sysfer.dll
Report Id: 770c0d91-0f67-412e-8251-556aef92d626
Faulting package full name: 
Faulting package-relative application ID:

**Comment by lionelperrin** [comment]
I have what I believe is the same issue with Windows 10 Enterprise 1909 (OS Build 18363.657)
```
Faulting application name: com.docker.service, version: 2.2.0.43472, time stamp: 0xc944d58c
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000000055583f3f
Faulting process id: 0x45f8
Faulting application start time: 0x01d603816f87382c
Faulting application path: C:\Program Files\Docker\Docker\com.docker.service
Faulting module path: unknown
Report Id: 61ffe171-c539-4ccc-9950-f53b980750f3
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by lionelperrin** [comment]
@rocky010563 Can you confirm which version of windows you're using ? (the result of the command: winver) Do you have the exact version of symantec you're using ? Do you avecto on your machine ?

I'm trying to find common points with my situation. Uninstalling symantec end point seems to fix the problem...

**Comment by rocky010563** [comment]
Windows 10 Enterprise Version 1903 (OS Build 18362.657)
Symantec Version 14 (14.2 RU2) build 5323 (14.2.5323.2000)
No Avecto

________________________________

**Comment by lionelperrin** [comment]
Very similar versions in my case:
```
Windows 10 Enterprise 1909 (OS Build 18363.657)
Symantec Version 14 (14.2 RU2) build 5323 (14.2.5323.2000)
````

**Comment by lionelperrin** [comment]
It is probably more related to symantec than docker desktop: https://knowledge.broadcom.com/external/article?legacyId=TECH246815
