### ISSUE TITLE
NuGet package restore fails with file already exists

### ISSUE THREAD

**Issue by gitfool** [docker/for-win#5822]
### Information

  - Windows Version: Windows 10 1909 (OS Build 18363.657)
  - Docker Desktop Version: 2.2.1.0 (42746) edge
  - Are you running inside a virtualized Windows: No

### Steps to reproduce the behavior

Using the docker client from WSL(v1) pointing to Docker Desktop via env vars:
```
DOCKER_CERT_PATH=
DOCKER_HOST=tcp://localhost:2375
DOCKER_MACHINE_NAME=localhost
DOCKER_TLS_VERIFY=
```
and `/etc/wsl.conf` config file:
```ini
[automount]
enabled = true
mountFsTab = true
options = "metadata,umask=0022,fmask=0011,case=off"
root = /

[filesystem]
umask = 0022

[interop]
appendWindowsPath = false
enabled = true

[network]
generateHosts = true
generateResolvConf = true
```
The following fails after updating Docker Desktop to v2.2.1.0:
```bash
 ~ >  mount
rootfs on / type lxfs (rw,noatime)
none on /dev type tmpfs (rw,noatime,mode=755)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)
devpts on /dev/pts type devpts (rw,nosuid,noexec,noatime,gid=5,mode=620)
none on /run type tmpfs (rw,nosuid,noexec,noatime,mode=755)
none on /run/lock type tmpfs (rw,nosuid,nodev,noexec,noatime)
none on /run/shm type tmpfs (rw,nosuid,nodev,noatime)
none on /run/user type tmpfs (rw,nosuid,nodev,noexec,noatime,mode=755)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
C:\ on /c type drvfs (rw,noatime,uid=1000,gid=1000,umask=22,fmask=11,metadata,case=off)
D:\ on /d type drvfs (rw,noatime,uid=1000,gid=1000,umask=22,fmask=11,metadata,case=off)
E:\ on /e type drvfs (rw,noatime,uid=1000,gid=1000,umask=22,fmask=11,metadata,case=off)

 ~ >  cd /c/Devel

 /c/Devel >  docker run -it --rm -w /build -v "$(pwd):/build" mcr.microsoft.com/dotnet/core/sdk:3.1.102-bionic

root@1fd34bb083f9:/build# dotnet tool install --tool-path ./tools GitVersion.Tool --version 5.1.3
/usr/share/dotnet/sdk/3.1.102/NuGet.targets(123,5): error : The file '/build/tools/.store/.stage/t1t25kcs.0s4/gitversion.tool/5.1.3/gitversion.tool.nuspec' already exists. [/tmp/ujbnv4lr.tyj/restore.csproj]
The tool package could not be restored.
Tool 'gitversion.tool' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
```
Also, with the same version, the following succeeds:
```bash
 ~ >  cd Devel

 ~/Devel >  docker run -it --rm -w /build -v "$(pwd):/build" mcr.microsoft.com/dotnet/core/sdk:3.1.102-bionic

root@51bb524ae562:/build# dotnet tool install --tool-path ./tools GitVersion.Tool --version 5.1.3
You can invoke the tool using the following command: dotnet-gitversion
Tool 'gitversion.tool' (version '5.1.3') was successfully installed.
```
The difference is that the failure only happens when using my Windows C: drive from WSL(v1).

**Comment by stephen-turner** [comment]
We don't recommend using docker from WSL 1. Use PowerShell, or if you have the latest Insiders build of Windows, WSL 2.

**Comment by gitfool** [comment]
Well, I’ve been using Docker client from WSL(v1) for a very long time, probably since inception. While there have always been quirks, especially with perms, the above issue is different and due to a recent change. Hopefully the repro steps will help track it down.

I’ll definitely be switching to WSL(v2) as soon as it’s generally available!

**Comment by gitfool** [comment]
FWIW, this issue persists with Docker Desktop Version 2.2.3.0 (43965) (edge).

**Comment by dobriai** [comment]
FWIW, I just started experiencing the exact same issue. A few clarifications, however:

- The same install command that **fails** locally, on my Windows 10 machine, **succeeds** on a Jenkins pipeline, presumably all running under some Linux environment.
- We had not changed the docker image for quiet some time - 6 months, give or take, so I cannot provide very granular timing info when something stopped working.
- Also, the very reason I am dealing with this matter is that we switched from `dotnet-sdk-2.2` to `dotnet-sdk-3.1` - I do not know if that matters here.
- I am using a stock Ubuntu 18.04 for a "starter" image base and adding `apt-get install -y dotnet-sdk-3.1` to my `Dockerfile` to build my image,

**Comment by RLHSI** [comment]
I'm running into the same issue using normal Linux Docker images (not WSL).  I'm using VSCode's Remote Development extensions to program inside a container and I can't get Cake.Tool to install:

```
> dotnet tool install Cake.Tool --version 0.38.4 --tool-path ./build/tools/

/usr/share/dotnet/sdk/3.1.300/NuGet.targets(128,5): error : The file '/workspaces/repo/build/tools/.store/.stage/ye4tnp4a.wmz/cake.tool/0.38.4/cake.tool.nuspec' already exists. [/tmp/3cu12aiw.3k0/restore.csproj]
```

* Windows 10, 1809 build 17763
* Docker Desktop 2.3.0.3 (45519) stable channel
* Are you running inside a virtualized Windows: No
