### ISSUE TITLE
Docker Desktop delays windows restart/shutdown

### ISSUE THREAD

**Issue by allanwright** [docker/for-win#5825]
Restarting and shutting down Windows 10 is delayed by Docker Desktop because windows reports that Docker Desktop is still shutting down. This has only started happening in the latest version. Prior to this, the process of shutting down Docker Desktop has never delayed the windows restart/shutdown process, at least not enough to be notified of the fact.

  - [X ] I have tried with the latest version of my channel (Stable)
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID: A266E9AB-367A-483D-8025-9B7F805CDCD2/20200220032447
  - Is it reproducible? Yes
  - Is the problem new? Yes
  - Did the problem appear with an update? Problems has only started occurring in latest version.
  - Windows Version: Windows 10 Pro 1903 (18362.657)
  - Docker Desktop Version: 2.2.0.3 (42716)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
  1. Start machine, login and allow Docker Desktop to complete its startup process.
  2. Restart or shutdown machine.

In previous versions, the machine would shutdown without ever reporting that Docker Desktop was in the process of shutting down still.

**Comment by phlox** [comment]
an increasing number of people in our team are facing this issue. I can't remember exactly when it started on my PC (Windows 10 Enterprise, 10.0.17134), maybe a month ago. A workaround is to stop Docker desktop manually before shutting down Windows. However, a permanent solution would be appreciated

**Comment by tiberiuemilian** [comment]
same issue on my side

**Comment by tobimat80** [comment]
Same here - Build 17134.1610

**Comment by nam178** [comment]
Same here. I have to manually quit docker Desktop before shutting down.

**Comment by ArcturusKhan** [comment]
Same, manually quitting docker seems to do the trick for now.

**Comment by ccornchip** [comment]
I started getting this issue when I updated docker.  I'm going to try to see if I can undo the update.

**Comment by DmitryBav** [comment]
Reporting the same issue and confirming that quitting Docker manually helps.

**Comment by stephen-turner** [comment]
For anyone still watching this ticket, this is fixed in version 3.2.0.
