### ISSUE TITLE
Duplicated Context in KubeCtl config even after deleting it

### ISSUE THREAD

**Issue by michaelsync** [docker/for-win#5830]
Hi,

As I am not able to reopen this issue https://github.com/docker/for-win/issues/5089 or didn't get the response, I am opening this as a new issue here. 

**Issue**

Docker for desktop (Windows) is showing `docker-desktop` and `docker-for-desktop`. I had deleted `docker-for-desktop` context manually. but when I restarted the machine, it cames back. 

Env:
* Windows 10
* Docker version 19.03.5, build 633a0ea
* kubectl version 

> Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
> Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"c52f59bbba5fbf21fbb18e9a06f96e563fe4c20a", GitTreeState:"clean", BuildDate:"2020-01-31T20:00:26Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**Comment by mat007** [comment]
Let me re-open #5089 which has more information.
