### ISSUE TITLE
Clarify Docker Desktop for Windows licensing conditions.

### ISSUE THREAD

**Issue by paulspencerwilliams** [docker/for-win#5838]
### Information

Could you please clarify the licensing conditions for running Docker Desktop for Windows in production, specifically on the LTSC release of Windows 10 IOT. Also, a summary of Docker Desktop for Windows vs Enterprise licensing on key Windows platforms would be useful.

**Comment by stephen-turner** [comment]
@paulspencerwilliams Please contact legal@docker.com. Thanks.
