### ISSUE TITLE
Attempting to reinstall Docker Desktop for Windows after uninstalling not working

### ISSUE THREAD

**Issue by waseemMbutt** [docker/for-win#5840]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
(re)Installation proceeds normally
### Actual behavior
After uninstalling and attempting to reinstall, the installer fails to run completely.  
### Information

  - Windows Version: Windows 10 Pro Version 1909
  - Docker Desktop Version: 2.2.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Install the specified version of Docker Desktop, with defaults selected
  2. Attempt to run Docker Desktop, get error seen here:
![image](https://user-images.githubusercontent.com/60798683/75072849-48ceed80-54c6-11ea-9a50-47a3a29cea38.png)

  3. Try to uninstall through control panel, doesn't work
  4. Run the Powershell script to uninstall Docker in the Program Files directory where Docker folder should be, (may need to run twice replacing "Docker for Windows" references with "Docker Desktop" references the second time)
  5. Download installer again, will run into "Already latest" even though uninstalled
  6. Manually delete HKLC/.../currentversion/uninstall docker registry key
  7. Installer now runs but errors with output:
![image](https://user-images.githubusercontent.com/60798683/75072910-6ac87000-54c6-11ea-80f7-581bb1367961.png)

Logging reproduced below:
Failed to start service: The service did not respond to the start or control request in a timely fashion
   at CommunityInstaller.ServiceAction.<AddService>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.ServiceAction.<DoAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__24.MoveNext()

**Comment by waseemMbutt** [comment]
[install-log.txt](https://github.com/docker/for-win/files/4238113/install-log.txt)

**Comment by mat007** [comment]
Is there anything in the Windows Event Viewer?

**Comment by waseemMbutt** [comment]
> Is there anything in the Windows Event Viewer?

Yes see screencap below:

![docker error](https://user-images.githubusercontent.com/60798683/75256223-22080400-57b1-11ea-8860-c17c2189334b.PNG)

**Comment by waseemMbutt** [comment]
Also seeing the following:
![image](https://user-images.githubusercontent.com/60798683/75257169-91322800-57b2-11ea-91fa-c7717b52101a.png)

**Comment by southplay** [comment]
I am seeing similar security errors in the logs and have a theory that it's related to permissions even though I am in the "Administrator" group. I am following up with IT to investigate.
