### ISSUE TITLE
Containers freeze after a while

### ISSUE THREAD

**Issue by patrickleogit** [docker/for-win#5854]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 
     3CA84AA9-6007-4E5E-B015-F24BFA6CCC72/20200224104420

### Expected behavior

I am using Docker + Laradock for my projects. Everything was working fine until last week, when the issue began to occur for unknown reasons. I use Laradock together with Docker-Compose everytime, starting both Nginx and Mysql. I expect my containers to be up and running all the time.

### Actual behavior

I can't access my local sites and databases anymore after a while. Everything freezes and I have to restart Docker Desktop and re-open the containers by using "build --no-cache nginx mysql" and "up -d nginx mysql". This happens after a while while I'm testing one of my projects through the terminal. Every container freezes, meaning I can't work on any of my projects anymore. I have to manually restart Docker Desktop. This solves the problem temporarily as it happens again after a while. I tried re-building with no-cache, I tried resetting everything to factory settings and I tried re-installing Docker Desktop but without any luck.

### Information

  - Windows Version: 10 Pro x64 Ver. 1909 (build SO 18363.657)
  - Docker Desktop Version: tried with both latest Stable version and latest Edge version.
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

**Comment by vdbMark** [comment]
Did you happen to find a fix for this issue? I seem to be running in to the same problem.
