### ISSUE TITLE
Feature Request: /var/run/docker.sock

### ISSUE THREAD

**Issue by tracker1** [docker/for-win#586]
Given how many applications integrate with docker inside containers, it would be nice if Docker for Windows supported detecting a volume mount from /var/run/docker.sock as a special case, and mapped the pipe to a socket inside said container.

I realize that this may be a bit complex, but would be a *REALLY* nice feature to have, given the number of systems that provide instructions for running a temporary instance with a volume map..

For example

    alias ctop="docker run -ti --name ctop --rm -v /var/run/docker.sock:/var/run/docker.sock quay.io/vektorlab/ctop:latest"

While alias is a shell/bash concept, it would be nice to do similarly in a CMD file in windows to do the same.

**Comment by friism** [comment]
It's a little unclear what you're asking, but if the question is whether you can run Linux containers that have access to the daemon socket, then the answer is "yes":

    docker run  -v /var/run/docker.sock:/var/run/docker.sock docker docker ps
    CONTAINER ID        IMAGE                      COMMAND                  CREATED                  STATUS                  PORTS                       NAMES
    dbdfa9c85c37        docker                     "docker-entrypoint..."   Less than a second ago   Up Less than a second                               gifted_boyd

This won't work for Windows containers because of limitations on that platform

**Comment by friism** [comment]
Closing, please re-open if this is not what you were looking for

**Comment by tracker1** [comment]
@friism and that works in Docker for Windows?

**Comment by tracker1** [comment]
@frism with "Docker for Windows" the command expressly does *NOT* work... as windows doesn't use a file socket like it does in Linux... the VM environment might... what I'm asking for, is for the Windows version to detect specifically a host path of `/var/run/docker.sock` and wire up a correct mapping into the running container, via whatever method can make that happen.

    C:\> docker run -it --rm  -v /var/run/docker.sock:/var/run/docker.sock docker docker ps
    C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from 
    daemon: invalid bind mount spec "/C/Program Files/Git/var/run/docker.sock;
    C:\\Program Files\\Git\\var\\run\\docker.sock": invalid volume specification: 
    '/C/Program Files/Git/var/run/docker.sock;C:\Program Files\Git\var\run\docker.sock': 
    invalid mount config for type "bind": invalid mount path: 
    '\Program Files\Git\var\run\docker.sock' mount path must be absolute.
    See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.

As you can see, this does not work... right now, there doesn't seem to be a clean way for docker tooling inside a container to run via the Docker for Windows version.

**Comment by tracker1** [comment]
@friism disregard, it's a git-bash on windows issue...   The only thing I could find when searching was that you would have to do some kind of TCP proxy to the named pipe... etc.  And really didn't want that... didn't realize it was actually build in already.

**Comment by awidjaja** [comment]
@friism , 

> docker run  -v /var/run/docker.sock:/var/run/docker.sock docker docker ps

doesn't work int the latest version of docker for windows using LCOW

**Comment by friism** [comment]
> doesn't work int the latest version of docker for windows using LCOW

@awidjaja it only works for Docker Windows containers

**Comment by friism** [comment]
@awidjaja yes, this won't work because your Windows Docker daemon (the one running your LCOW containers) is not listening on a UNIX socket, but on a Windows named pipe

**Comment by awidjaja** [comment]
thanks, yes I think that's the explanation. 
Would you mind to reopen this issue as bug as this was working on earlier version?

**Comment by friism** [comment]
@awidjaja for now, you can go back to running Linux containers without LCOW. I think it'd be a good idea to open an issue on github.com/moby/moby to track the problem of mounting the Docker daemon socket into Linux LCOW containers on Windows. Ping @jstarks on the issue.

**Comment by awidjaja** [comment]
added a comment on https://github.com/moby/moby/issues/35425
