### ISSUE TITLE
Pulling images results in EOF error

### ISSUE THREAD

**Issue by ZusorCode** [docker/for-win#5868]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 7FC22DAD-37E0-4D53-B0DD-424EA7621A46/20200224232509

### Expected behavior
Docker pull downloads images
### Actual behavior
```
PS C:\Users\Username> docker pull hello-world
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/library/hello-world/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fhello-world%3Apull&service=registry.docker.io: unexpected EOF
```
### Information

  - Windows Version: Windows 10 Pro Build 18363
  - Docker Desktop Version: v19.03.5
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. docker pull hello-world (or other images)

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place?

**Comment by ZusorCode** [comment]
For anyone who comes across this, it was caused by my FritzBox router.

https://github.com/docker/for-mac/issues/3493#issuecomment-616338458
