### ISSUE TITLE
Unable to run any docker related commands as it shows an error during connect.  But the docker desktop in windows is in running status and the docker version when queried is displaying as 19.03.5.

### ISSUE THREAD

**Issue by DeepthiPalaniKumar** [docker/for-win#5870]
docker pull hello-world
ERROR:
Using default tag: latest
error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/images/create?fromImage=hello-world&tag=latest: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

docker run hello-world

ERROR:
 error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/create: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

**Comment by wmcook-hex** [comment]
Experiencing this same issue today. Have not had this problem until now. I have the service running, but still receive the _"error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/prune: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running."_ error message.

docker --version output: _Docker version 19.03.5, build 633a0ea_
