### ISSUE TITLE
Docker Desktop fails to start

### ISSUE THREAD

**Issue by skanduru** [docker/for-win#5875]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
D13D4B47-450A-4AB5-9021-BD520EF2CFE8/20200225135602
### Expected behavior
Docker Desktop is expected to start
### Actual behavior
Docker Desktop is not starting
### Information

  - Windows Version: Windows 10 Version 1909 (OS Build 18363.418)
  - Docker Desktop Version: latest stable version
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Started Docker Desktop on a laptop

### Steps to reproduce the behavior

  1. Start Docker Desktop after installation
  2. ...

**Comment by skanduru** [comment]
Hyper-V is enabled. I could see that the Hyper-V gets started, then the error occurs that Hyper-V can't be stopped

**Comment by erikbye** [comment]
![image](https://user-images.githubusercontent.com/2594911/75283661-92e00800-5813-11ea-98b5-d1720278f088.png)

Make sure your system environment variable PSModulePath contains the two following locations as shown in screenshot.

**Comment by Ezak91** [comment]
i had the same error

PSModulePath is set as shown in the screenshot
