### ISSUE TITLE
Docker Starting Failure on Windows 10

### ISSUE THREAD

**Issue by hc621** [docker/for-win#5879]
- [Y] I have tried with the latest version of my channel (Stable or Edge)
  - [Y] I have uploaded Diagnostics
  - Diagnostics ID:5E673C80-087A-405A-AFE2-1749737D8117/20200225194404

### Expected behavior
Install in windows 10 enterprise version, with Hyper V enabled
### Actual behavior
docker crashed when it tried to start.
### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by erikbye** [comment]
See my comment on this other issue, might be related.

https://github.com/docker/for-win/issues/5875#issuecomment-591046768
