### ISSUE TITLE
the credentials error show like this 

### ISSUE THREAD

**Issue by tivepro** [docker/for-win#5886]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ... start docker 
  2. ... get this message 

System.Security.Cryptography.CryptographicException:
Clave no válida para utilizar en el estado especificado.

   en System.Security.Cryptography.ProtectedData.Unprotect(Byte[] encryptedData, Byte[] optionalEntropy, DataProtectionScope scope)
   en Docker.WPF.Credentials.MountCredentialAsker.DecryptPassword(Byte[] encrypted)
   en Docker.WPF.Credentials.MountCredentialAsker.RetrieveCredential(String target)
   en Docker.WPF.BackendClient.Start(ContainerEngineMode mode)
   en Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   en Docker.Actions.<>c__DisplayClass30_0.<ResetToDefault>b__0()
   en Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

**Comment by tivepro** [comment]
when I runned as an administrador I get this message

Acceso denegado. (Excepción de HRESULT: 0x80070005 (E_ACCESSDENIED))

**Comment by akunzai** [comment]
Maybe duplicated with #3560 

you can try to removing `Docker Host Filesystem Access` record in Credential Manager

```powershell
cmdkey /delete:"Docker Host Filesystem Access"
```
