### ISSUE TITLE
Why is "system proxy" not a selectable option?

### ISSUE THREAD

**Issue by sthuber90** [docker/for-win#589]
### Expected behavior
Going to settings > proxies > select "use system proxy"
### Actual behavior
Going to settings > proxies > select "use system proxy" cannot be selected 
![image](https://cloud.githubusercontent.com/assets/4415930/23942900/01697880-096e-11e7-9ffe-a4fefc38bb49.png)

### Information
Running on windows 10 using AD and docker community ediion version 17.03.0-ce-win1 (10296) e5a07a1

### Steps to reproduce the behavior

  1. Open docker-for-win settings
  2. Go to proxies
  3. Try to select "use system proxy"

**Comment by jhoval** [comment]
Any update about this issue?

**Comment by ezfranca** [comment]
I have same problem here. Any updates ?

**Comment by YaelMendes** [comment]
same problem here. Any updates ?

**Comment by sthuber90** [comment]
Why was this feature removed in the most recent docker version 17.12.0-ce-win46 (15048) 0ac7325?

**Comment by sthuber90** [comment]
Well you could say that this issue was resolved by removing the option to use the system proxy. I don't quite think that this is an ideal solutions, but it solved the issue 😆
