### ISSUE TITLE
Docker container freeze when executing invalid binary 

### ISSUE THREAD

**Issue by prabindh** [docker/for-win#5896]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID - 9F6D2931-01E3-4D58-886B-62255D459BE5/20200227104835

### Expected behavior
Docker container should not freeze

### Actual behavior
Docker container freezes

### Information

  - Windows Version: 1909
  - Docker Desktop Version: 19.0.3+
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

Note: This is when running with "Windows Container" option in Docker.
  1. Any image, and entering into container via cmd.
  2. In the cmd prompt, execute any "dll" file, or non-executable file, for ex C:\App\some.dll and press enter.
  3. Docker container does not respond after this, and needs to be killed from another shell.

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place?
