### ISSUE TITLE
Docker crashes when starting with linux containers enabled on windows 10

### ISSUE THREAD

**Issue by joller134** [docker/for-win#5899]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: BBA6C591-5358-44E4-B980-7AFBDB5BDA69/20200227223300

### Expected behavior

when i launch the docker desktop application i expect it to open up succefully.

### Actual behavior

when booting up docker it crashes and throws me an error

When 

I launch docker with the linux containers. Docker works succesfully when using the windows containers however i require linux containers for my project.

### Information

  - Windows Version: Windows 10 enterprise
  - Docker Desktop Version: v2.2.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

I am using docker for a university course and the laptop I use is registered to a domain of the university. there for my computer name is a set of 8 digits and the fullname follows the format 8 digits.domain.uni.com.

I have tried to search the issue on the internet but after a long search did not find the same problem. I checked that virtualization is enabled in my bios. Hyper-v is enabled in windows.

-  As recommended in <a href=http://github.com/docker/for-win/issues/147>this</a> issue i added all my domain names to C:\Windows\System32\drivers\etc\hosts and used the ip address from ping loopback and local adresses. 

- i reinstalled Docker multiple times

- disabling unused network adapters.

The error thrown by docker is the following 

System.Management.Automation.RuntimeException:
  Unable to create Hyper-V VM: The computer '.' could not be resolved. Make sure you typed the machine name correctly and that you have network access.
  at New-MobyLinuxVM, <No file>: line 388
  at New-MobyLinux, <No file>: line 182
  at <ScriptBlock>, <No file>: line 810
     at Docker.Backend.HyperV.HandleException(String action, Exception ex)
     at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters, PowerShellConfiguration config)
     at Docker.Backend.HyperV.Create(Settings settings)
     at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
  
  
The full log can be viewed at this [log.txt](https://github.com/docker/for-win/files/4264507/log.txt)

### Steps to reproduce the behavior

  1. Install the most recent stable version of docker desktop (last download 26/02/2020)
  2. Install with the linux containers selected as default.
  3. Launch Docker Desktop

**Comment by neoAnkit** [comment]
enable hyper vm on your machine

**Comment by joller134** [comment]
> enable hyper vm on your machine

I already enabled hyper-v in windows features and my bios prior to booting up docker.

**Comment by MythreyaK** [comment]
This sounds like a network issue `The computer '.' could not be resolved`. The hostname is somehow being read as a literal `.`. Could you revert the edits to your `hosts` file and try again? Hyper-V seems to be working fine.

**Comment by joller134** [comment]
thank you i will try. At the moment i run a separate Linux desktop machine in which I ssh from a distance while travelling
