### ISSUE TITLE
Docker daemon reports incorrect number of CPUs (does not match Hyper-V)

### ISSUE THREAD

**Issue by ngoodnight** [docker/for-win#59]
### Expected behavior

In my use case, the Hyper-V VM used by Docker reports 15 virtual processors. I would expect the Docker daemon to report the same number, and running containers should also see 15 CPUs by default. 

### Actual behavior

The Docker daemon reports 8 CPUs regardless of how many are allocated to the VM. All containers see/utilize only 8 CPUs.
 
### Information

OS: Latest Win 10 Pro Version (Version: 1607 Build: 14393.0)
Architecture: x64
CPU: 20 physical cores

I've tested this with both the latest stable and beta releases of Docker for Windows. It reproduces in both cases.

Diagnostic ID: 985EBEAD-F56B-4A7A-9ACE-7AEE7CA1E17E/2016-08-24_16-29-36

docker info:
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 1
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 8
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.19-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 19.07 GiB
Name: moby
ID: ZETF:7OLP:TS5F:4LVQ:MLJG:4PXP:6PKX:SI6D:2PDS:Q5LB:YW2J:IFEO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8

### Steps to reproduce the behavior

  1. Set the number of CPUs to N > 8 in the Docker Windows App
  2. Verify that Hyper-V shows N virtual processors allocated to the VM
  3. Run a container on ubuntu:16.04 and check /proc/cpuinfo to see if it reports only 8 processors

**Comment by friism** [comment]
It looks like this is due to a kernel setting that we set, cc @justincormack

**Comment by justincormack** [comment]
Hi, fixing this for the next release. I think it was inherited from the old boot2docker config, was not intended to be limited.

**Comment by rneugeba** [comment]
@ngoodnight This should be incorporated in the next Beta. Closing this issue for now. Thanks for reporting it.

**Comment by ngoodnight** [comment]
Thanks for the quick response. I'll check the next beta release.
