### ISSUE TITLE
Message C: drive is not shared at the end install oncrawl-elk

### ISSUE THREAD

**Issue by sytou** [docker/for-win#590]
### Expected behavior
Try to install 
https://github.com/cogniteev/oncrawl-elk

### Actual behavior
ERROR: for logstash  Cannot create container for service logstash: C: drive is not shared. Please share it in Docker for Windows Settings
ERROR: Encountered errors while bringing up the project.

docker run --rm -v c:/Users:/data alpine ls /data
docker: Error response from daemon: C: drive is not shared. Please share it in Docker for Windows Settings.

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
4695DF25-FA7F-4DC9-AA93-FD9D74AA162C/2017-03-15_12-41-01

  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)
Windows 10 professional
Version 1607
Version OS 14393.693

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by friism** [comment]
Please share the drive in settings: https://docs.docker.com/docker-for-windows/#shared-drives

**Comment by sytou** [comment]
I try but it still doesn't work.
I set my user / pwd but still doesn't change.
I try this : https://docs.docker.com/docker-for-windows/troubleshoot/#verify-domain-user-has-permissions-for-shared-drives-volumes
No more change.
What can i do ?
Thks for your help.

**Comment by sytou** [comment]
[18:56:15.130][SambaShare     ][Error  ] Unable to mount C drive: 10.0.75.1 (10.0.75.1:445) open
mount error(112): Host is down
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
mount: mounting //10.0.75.1/C on /c failed: Invalid argument

**Comment by sytou** [comment]
![firewall](https://cloud.githubusercontent.com/assets/12085103/23963666/599a873a-09b2-11e7-80b5-1e60db1fc850.png)
