### ISSUE TITLE
Docker exiting seconds after starting

### ISSUE THREAD

**Issue by gacole** [docker/for-win#5901]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:5AEEA6D1-ACB0-49F7-95D4-ED40C7ABEB72/20200228151651

### Expected behavior
docker continuing to run
### Actual behavior
exiting
### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...docker start sql1
  2. ...docker ps -a shows it exited after a few seconds

**Comment by MythreyaK** [comment]
If you want an interactive session, use the -it parameter.

**Comment by gacole** [comment]
I copied my db files out, uninstall docker and installed a new one. I couldn't wait 6 days for help.

**Comment by MythreyaK** [comment]
Oh well, glad to know you were able to solve it. Feel free to close/reopen the issue in case it reappears.
