### ISSUE TITLE
Docker Dashboard is connecting via all exposed TCP ports when viewing logs of containers

### ISSUE THREAD

**Issue by RejectKid** [docker/for-win#5903]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
I have a ZMQ service in a container running that notifies when ports are connected to it.  When I open the dashboard and click into the it to see the logs, there is NOT a TCP connection made over all exposed ports (looks to be some web request header information).
### Actual behavior
I have a ZMQ service in a container running that notifies when ports are connected to it.  When I open the dashboard and click into the it to see the logs, there is a TCP connection made over all exposed ports (looks to be some web request header information) and is messing with our "what ports are being used" functionality
### Information

  - Windows Version: windows 10
  - Docker Desktop Version: 2.2.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. Have a container running with many ports exposed that is running a zMQ style listener on those ports
  2. Open dashboard and click into the logs
  3. In our case this services says "Hello [PORTNUMBER]" many many times as the dashboard seems to be connecting to the exposed ports and sending data over them

**Comment by thaJeztah** [comment]
looks the same as https://github.com/docker/for-mac/issues/4264

**Comment by stephen-turner** [comment]
Yes, closing as a dupe.

**Comment by stephen-turner** [comment]
Fixed in 2.2.0.4.
