### ISSUE TITLE
Getting hcsshim::CreateComputeSystem <container id> Access Denied 

### ISSUE THREAD

**Issue by rroman81** [docker/for-win#5914]
- [ x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x ] I have uploaded Diagnostics
  - Diagnostics ID: 37736633-5D92-491E-B9D4-7AD801B6FF3D/20200301202550

### Expected behavior
During docker image build step under https://github.com/Sitecore/docker-images/tree/master/windows/dependencies/mssql-developer-2017 location I am getting the following error:
```powershell
 ---> Running in 20ea8f586bb9
hcsshim::CreateComputeSystem 20ea8f586bb911c53610877759f6c16d36aa8132059b0ca1cb0015f1d5bbc508: Access is denied.
(extra info: {"SystemType":"Container","Name":"20ea8f586bb911c53610877759f6c16d36aa8132059b0ca1cb0015f1d5bbc508","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\20ea8f586bb911c53610877759f6c16d36aa8132059b0ca1cb0015f1d5bbc508","Layers":[{"ID":"ea180f4c-2da4-5ac2-9e4d-402f15480db8","Path":"C:\\ProgramData\\Docker\\windowsfilter\\b8a20d601730e225a2282b754a6c4fd38a61fb5023955f9d0daa925787276dc0"},{"ID":"8425f751-207c-599b-9f40-adb6d3487341","Path":"C:\\ProgramData\\Docker\\windowsfilter\\6ab7d332489d406eb1acaf5bfe6597b91ac4a8db1217bfea7e8cc8dc67bc22a6"},{"ID":"fec5e668-afe9-5810-aadf-93ce326bafc5","Path":"C:\\ProgramData\\Docker\\windowsfilter\\7a578227226ebb969acd8ebd9bdfd480409b5f697e5f65f1f206ae53c4fbc78c"},{"ID":"b8de46a7-a65c-5231-9561-03cc1623b504","Path":"C:\\ProgramData\\Docker\\windowsfilter\\26c168123004f2dfc1faaad47e1ab6825b9a16162ec1534846da387097a6f895"}],"MemoryMaximumInMB":4096,"HostName":"20ea8f586bb9","HvPartition":true,"EndpointList":["8207256B-EAF4-4CCA-8E85-9F065A51BE5F"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\7a578227226ebb969acd8ebd9bdfd480409b5f697e5f65f1f206ae53c4fbc78c\\UtilityVM"},"AllowUnqualifiedDNSQuery":true})
```

### Actual behavior
I would expect the image to complete building itself.

### Information

  - Windows Version: Windows 10 Pro Version 1809 (OS Build 17763.1039)
  - Docker Desktop Version: Docker Desktop CE 19.03.5
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
Running
### Steps to reproduce the behavior

  1. git clone [sitecore repository/docker-images](https://github.com/Sitecore/docker-images)
  2. navigate to ~/dependencies/mssql-developer-2017
  3. Run `docker image build --build-arg BASE_IMAGE=mcr.microsoft.com/windows/servercore:ltsc2019 --memory 4GB --tag mssql-developer:2017-windowsservercore-ltsc2019 .`

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place?

**Comment by rroman81** [comment]
Created related issue for those that want to follow: https://github.com/moby/moby/issues/40610
