### ISSUE TITLE
Docker for desktop not installing

### ISSUE THREAD

**Issue by RiyaSapra** [docker/for-win#5916]
After installation, the following error shows : Docker Desktop requires Windows 10 Pro or Enterprise version 15063 to run.

I have windows 10 pro and Hyper-V and virtualization is enabled.

**Comment by mat007** [comment]
What’s the output of `ver` in a command shell?

**Comment by RiyaSapra** [comment]
Microsoft Windows [Version 10.0.10240]

**Comment by mat007** [comment]
This means version 10240, as the error messages tells you you need at least 15063.
