### ISSUE TITLE
Never i used a similar shitty program

### ISSUE THREAD

**Issue by Arngue** [docker/for-win#5922]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
B6D4E75A-A3AE-45D8-AEC5-66997D5136D8/20200303091313
### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
I'm closing this because it doesn't contain any symptoms, only an insult. If you want us to look at your bug report, please indicate what symptoms you saw and what you expected.
