### ISSUE TITLE
Error after installing Docker on Windows 10

### ISSUE THREAD

**Issue by Movs681221** [docker/for-win#5933]
After installing Docker on my Windows 10 PC, I tryed to run: docker run hello-world; to test the installation; but that result on the following error:

docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
a35da61c3562: Extracting  101.1MB/101.1MB
be21f08f6701: Download complete
10d1439be4eb: Download complete
C:\Program Files\Docker\Docker\resources\bin\docker.exe: failed to register layer: re-exec error: exit status 1: output: Failed to safefile.OpenRelative failed in Win32: open \\?\C:\ProgramData\Docker\windowsfilter\70423a6e550df06abfcf8a974e3e7be2213ebb6853347b048131dd71fea9931f\Files\Users\Public: Access is denied. (0x1f) Files\Users\Public.
See 'C:\Program Files\Docker\Docker\resources\bin\docker.exe run --help'.

Please help.
Best regards.

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place?
