### ISSUE TITLE
Failed creating ingress network: hnsCall failed in Win32: The parameter is incorrect. (0x57)

### ISSUE THREAD

**Issue by ncresswell** [docker/for-win#5935]
As per a previously closed issue https://github.com/docker/for-win/issues/3821#issuecomment-594234892

I have the exact same issue on 3x brand new Windows 10 Desktops running Windows 1909 and Docker 19.03.5.

I have created a single node swarm cluster using the command "docker swarm init --advertise-addr 127.0.0.1", however in the event log, i see "Failed creating ingress network: hnsCall failed in Win32: The parameter is incorrect. (0x57)" but the swarm creation continues without error.

However, when try to deploy anything that needs to attach to ingress, it fails with HNScall failed.

I ran the powershell script to clean and delete all vswitches as per https://raw.githubusercontent.com/MicrosoftDocs/Virtualization-Documentation/master/windows-server-container-tools/CleanupContainerHostNetworking/WindowsContainerNetworking-LoggingAndCleanupAide.ps1, but no difference.

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place?
