### ISSUE TITLE
CREATED time of image is incorrect for new builds

### ISSUE THREAD

**Issue by rabbers** [docker/for-win#5939]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
When executing 'docker build' and then 'docker images -a', I should see the hash from 'Successfully Built' in the list with CREATED as something like '1 minute ago' or a similarly small amount of time.

### Actual behavior
When executing 'docker build' and then 'docker image -a', I actually see that the hash from 'Successfully Built' in the list with CREATED as '11 hours ago'.

### Information
The issue is reproducable.
I don't know if the problem is new, I only just started with Docker.
  - Windows Version:

10     0      18362  0

  - Docker Desktop Version:
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

No

### Steps to reproduce the behavior
1) I built a default aspNet3.0 web project docker file with 'docker build -f .\Dockerfile ..
2) I noted the hash from the success message
3) The CREATED column shows '11 hours ago' - note that my current time is 10:49, so I'm presuming that the time portion of the stamp is not stored.

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place?
