### ISSUE TITLE
Docker Desktop: Dashboard - scrolling through log jumps back to end of log

### ISSUE THREAD

**Issue by PaulInglis** [docker/for-win#5941]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 0864072C-05FC-4146-A208-50DB400F9B6F/20200304122129

### Expected behavior
When scrolling through a log on Dashboard, I expect to be able to see quite far back in the log
### Actual behavior
When I scroll back even half a page it scrolls me to the end of the log.....even if the log is no longer updating

### Information

  - Windows Version: Windows 10 - 1909
  - Docker Desktop Version: 2.2.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. Load any image that produces a log
  2. Select the image in dashboard
  3. Try to scroll up

Attached is a gif video of what happens
![docker-logs-jump](https://user-images.githubusercontent.com/3604276/75879979-55cbd500-5e14-11ea-862f-219a441c1933.gif)

**Comment by stephen-turner** [comment]
@PaulInglis Turn off the "Stick to bottom" switch.

**Comment by PaulInglis** [comment]
> @PaulInglis Turn off the "Stick to bottom" switch.

Thank you....clearly I am blind!
