### ISSUE TITLE
GET /containers/{id}/stats returns invalid time format

### ISSUE THREAD

**Issue by vdvarlamov** [docker/for-win#5942]
https://docs.docker.com/engine/api/v1.40/#operation/ContainerStats
"read": "2015-01-08T22:57:31.547920715Z"
In fact: "read":"2020-03-04T14:59:28.0520539+03:00". 
![image](https://user-images.githubusercontent.com/47747798/75880463-5f623680-5e2e-11ea-8157-f9f1eb7040d0.png)
Host - Windows Server 2019

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place?
