### ISSUE TITLE
'Unable to write to the database' - Cannot start docker

### ISSUE THREAD

**Issue by sheen4n** [docker/for-win#595]
### Expected behavior
To start the docker properly (in Windows 10, Parallels)
### Actual behavior
Unable to start - error 'Unable to write to the database'
### Information
Diagnostics ID: B20528FF-B79D-442E-BB3A-D7737D84B0B9/2017-03-19_00-37-39
  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by NPrice99** [comment]
I am having the same issue - Unable to start - error 'Unable to write to the database' just start docker using "Reset"
