### ISSUE TITLE
Dashboard: duplicate log lines are skipped

### ISSUE THREAD

**Issue by davidgruar** [docker/for-win#5954]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: CDD2469C-909D-41B9-970F-B38B02693253/20200306163004

### Expected behavior
Standard output from a container should be visible on the Logs panel in Docker Desktop Dashboard.

### Actual behavior
Any duplicate log lines are not output. See repro steps below.

### Information

  - Windows Version: Windows 10 Enterprise 1903
  - Docker Desktop Version: 2.2.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

#### Dockerfile
```dockerfile
FROM busybox
COPY run.sh .
CMD [ "sh", "run.sh" ]
```

#### run.sh
```bash
echo One
echo Two
echo Three
echo Two
echo One
echo Four
```

Build and run:
```cmd
> docker build -t logtest .
> docker run logtest
```

Console output:
```
One
Two
Three
Two
One
Four
```

Output in Dashboard:
```
One
Two
Three
Four
```

**Comment by mat007** [comment]
Thanks for your report, I can confirm I’m able to reproduce this simply by running
```
docker run -it alpine sh -c "echo 1 && echo 2 && echo 3 && echo 1 && echo 2 && echo huh"
```
![image](https://user-images.githubusercontent.com/2386884/76105251-e224f600-5fd4-11ea-95db-6a6389cba11c.png)

**Comment by mat007** [comment]
We have now fixed this bug in our master branch.
This fix will be released with the next Edge, but not the next Stable sadly, as that one will be based on Edge 2.3.0.1 that has just been released.

**Comment by davidgruar** [comment]
I can confirm this is now fixed in the latest stable release. Thanks @mat007.
