### ISSUE TITLE
Proxy enviroment variables not exported

### ISSUE THREAD

**Issue by coobas** [docker/for-win#5964]
Hi,

it seems that after the last update to Docker Desktop 2.2.0.3 (on Win 10), proxy variables are not automatically exported as before (https://docs.docker.com/network/proxy/). E.g. with this Dockerfile:
```
FROM python:3.7
RUN env
```
the env does not containt `http_proxy` etc. variables, even though proxy is configured in Settings / Resources / Proxies.

This is very inconvenient if the machine is behind a proxy.

Thanks in advance for looking into this
Jakub

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mat007** [comment]
Hi @coobas, thanks for your report.
I’ve tested with 2.1.0.5 but I’m not seeing the behaviour you’re describing either, do you remember which version you upgraded from?

![image](https://user-images.githubusercontent.com/2386884/76197375-4f5ea400-61ec-11ea-9450-8df1a6a78287.png)

**Comment by coobas** [comment]
Hi, thanks for looking into this. I don't remember the version, sorry. I'm also only anticipating this is what has changed. The real practical issue I have is I cannot `pip install` packages behind the proxy, which was possible before -- likely due to `https_proxy` etc. variables exported during the build. I remeber I did read somewhere that the variables are exported automatically and I also understand this sentence from https://docs.docker.com/network/proxy/#configure-the-docker-client says the same: "2. When you create or start new containers, the environment variables are set automatically within the container." Maybe I'm missing something though.

Overall, to resolve this, it'd be enough to answer: What is the proper way to export proxy-related variables to the build process and containers?

**Comment by mat007** [comment]
Well, you just need to follow the instructions at the link you posted.
Edit the `docker` command line config file `config.json` in your home folder under `.docker` (i.e. `%USERPROFILE%\.docker\config.json`) and add you proxy configuration e.g.
```
   "proxies":
   {
     "default":
     {
       "httpProxy": "http://127.0.0.1:3001",
       "httpsProxy": "http://127.0.0.1:3001",
       "noProxy": "*.test.example.com,.example2.com"
     }
   }
```
then
```
$ docker run --rm python:3.7 env
PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=973c1e64b9ae
HTTPS_PROXY=http://127.0.0.1:3001
https_proxy=http://127.0.0.1:3001
NO_PROXY=*.test.example.com,.example2.com
no_proxy=*.test.example.com,.example2.com
HTTP_PROXY=http://127.0.0.1:3001
http_proxy=http://127.0.0.1:3001
LANG=C.UTF-8
GPG_KEY=0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D
PYTHON_VERSION=3.7.6
PYTHON_PIP_VERSION=20.0.2
PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/d59197a3c169cef378a22428a3fa99d33e080a5d/get-pip.py
PYTHON_GET_PIP_SHA256=421ac1d44c0cf9730a088e337867d974b91bdce4ea2636099275071878cc189e
HOME=/root
```
```

**Comment by coobas** [comment]
Thank you again.

I anticipated the json config serves the same purpose as the config in the GUI Settings / Resources / Proxies, is it not?

Anyway, I think I've found out the difference: I'm using docker client from WSL (Docker version 19.03.7, build 7141c199a2) via the tcp connection (enabled "Expose daemon on tcp://localhost:2375 without TLS"). Using this client, proxy variables are not exported. On the other hand, using the Windows client (Docker version 19.03.5, build 633a0ea), http variables are exported automatically (using your `docker run --rm python:3.7 env` to check).

Could you please check whether you can replicate this behaviour?

**Comment by coobas** [comment]
Solved - did not realize the proxy settings are for the client, not the daemon. Hence `~\.docker\config.json` must be adjusted in WSL as well. 
Thanks for your support!

**Comment by mat007** [comment]
Glad you solved it @coobas !
I’ll go ahead and close this issue then.
