### ISSUE TITLE
Cannot uninstall, repair, or install Docker.

### ISSUE THREAD

**Issue by aconfee** [docker/for-win#5974]
- [ x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x ] I have uploaded Diagnostics

### Expected behavior
Install Docker fresh

### Actual behavior
I'm prompted with 'Do you want to replace your current version of Docker Desktop 2.2.0.0 (42247) with this new one 2.2.0.3 (42716)? 
No: Cancels installation. 
Yes: Fails with error immediately. 

### Information
  - Windows Version: 10 Version 1709 (OS Build 16299.1686)
  - Docker Desktop Version: Not on computer. 
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No.

### Steps to reproduce the behavior
  1. *Original error was a failure to uninstall docker.
  2. Manually delete Docker folder from Program Files
  3. Manually delete Docker from App Data
  4. Try to install Docker 

Problems:
Originally, Docker failed to uninstall.
After manually deleting all traces of Docker from my system, Docker is still in my list of programs in 'Apps & Features' ie 'Add and Remove Programs in the control panel. 

State:
I can't uninstall, repair, or install Docker. This machine is Docker proof. Any help to get Docker installed is appreciated! 

** I have tried running the Powershell script provided in the Docker forums which is intended to completely remove Docker from my machine. It ran without error, but did not fix this issue.

**Comment by mat007** [comment]
Launch `regedit` from the command prompt and open `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall` then remove `Docker Desktop` and try again the installer.

**Comment by aconfee** [comment]
Thank you! That did it. Thanks for such a quick response.
