### ISSUE TITLE
Docker windows installation failed (RPC server is too busy to complete the operation)

### ISSUE THREAD

**Issue by BarryLoo** [docker/for-win#5976]
# Docker windows installation failed

### Docker

```
File Version: 2.2.0.42716
Product Version: 2.2.0.42716
```

### System Info

```
Windows 10 educational x64
Version: 1809
Operation System Version: 17763.1039
```

## Installation stack trace Info

```
RPC 服务器太忙，不能完成该操作。(This Chinese sentence means: RPC server is too busy to complete the operation. )

   在 System.DirectoryServices.DirectoryEntry.RefreshCache()
   在 System.DirectoryServices.AccountManagement.PrincipalContext.DoMachineInit()
   在 System.DirectoryServices.AccountManagement.PrincipalContext.Initialize()
   在 System.DirectoryServices.AccountManagement.PrincipalContext.get_QueryCtx()
   在 System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithTypeHelper(PrincipalContext context, Type principalType, Nullable`1 identityType, String identityValue, DateTime refDate)
   在 System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithType(PrincipalContext context, Type principalType, String identityValue)
   在 System.DirectoryServices.AccountManagement.GroupPrincipal.FindByIdentity(PrincipalContext context, String identityValue)
   在 CommunityInstaller.CreateGroupAction.<DoAsync>b__33_0()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 (The stack trace's tail of last triggered exception info ) ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 CommunityInstaller.InstallWorkflow.<HandleD4WPackageAsync>d__29.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 (The stack trace's tail of last triggered exception info ) ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 CommunityInstaller.InstallWorkflow.<ProcessAsync>d__24.MoveNext()
```

**Comment by SgtPooki** [comment]
Providing raw english stacktrace as well. This is for Docker Desktop 2.2.0.5

```
The RPC server is too busy to complete this operation.

   at System.DirectoryServices.DirectoryEntry.RefreshCache()
   at System.DirectoryServices.AccountManagement.PrincipalContext.DoMachineInit()
   at System.DirectoryServices.AccountManagement.PrincipalContext.Initialize()
   at System.DirectoryServices.AccountManagement.PrincipalContext.get_QueryCtx()
   at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithTypeHelper(PrincipalContext context, Type principalType, Nullable`1 identityType, String identityValue, DateTime refDate)
   at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithType(PrincipalContext context, Type principalType, String identityValue)
   at System.DirectoryServices.AccountManagement.GroupPrincipal.FindByIdentity(PrincipalContext context, String identityValue)
   at CommunityInstaller.CreateGroupAction.<DoAsync>b__33_0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__24.MoveNext()
```

**Comment by BarryLoo** [comment]
> Providing raw english stacktrace as well. This is for Docker Desktop 2.2.0.5
> 
> ```
> The RPC server is too busy to complete this operation.
> 
>    at System.DirectoryServices.DirectoryEntry.RefreshCache()
>    at System.DirectoryServices.AccountManagement.PrincipalContext.DoMachineInit()
>    at System.DirectoryServices.AccountManagement.PrincipalContext.Initialize()
>    at System.DirectoryServices.AccountManagement.PrincipalContext.get_QueryCtx()
>    at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithTypeHelper(PrincipalContext context, Type principalType, Nullable`1 identityType, String identityValue, DateTime refDate)
>    at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithType(PrincipalContext context, Type principalType, String identityValue)
>    at System.DirectoryServices.AccountManagement.GroupPrincipal.FindByIdentity(PrincipalContext context, String identityValue)
>    at CommunityInstaller.CreateGroupAction.<DoAsync>b__33_0()
>    at System.Threading.Tasks.Task.Execute()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at CommunityInstaller.InstallWorkflow.<HandleD4WPackageAsync>d__29.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__24.MoveNext()
> ```

Thanks for reply.
The stacktrace you gave is same to mine. And so sorry for my version is Chinese, so I can tell you it's same as yours. What's more your version(2.2.0.5 ) is close to mine(2.2.0.42716). Can you track to problem to fix it? Or what version which can be safely updated and when?

**Comment by mat007** [comment]
Thanks for the reports, could any of you open the Remote Registry service properties

![image](https://user-images.githubusercontent.com/2386884/78965866-93500c00-7afe-11ea-9419-ece0db18c743.png)

and tell me what you see on the Log On tab?

![image](https://user-images.githubusercontent.com/2386884/78965880-a1059180-7afe-11ea-9bd0-c88412dd9c68.png)

Thanks!

**Comment by BarryLoo** [comment]
> Thanks for the reports, could any of you open the Remote Registry service properties
> 
> ![image](https://user-images.githubusercontent.com/2386884/78965866-93500c00-7afe-11ea-9419-ece0db18c743.png)
> 
> and tell me what you see on the Log On tab?
> 
> ![image](https://user-images.githubusercontent.com/2386884/78965880-a1059180-7afe-11ea-9bd0-c88412dd9c68.png)
> 
> Thanks!

Same thing as you show in the second shortcut.

**Comment by mat007** [comment]
Is there any more information in Windows Event Viewer around the time the installation failed?

**Comment by mat007** [comment]
Is the `Server` service started?

![image](https://user-images.githubusercontent.com/2386884/78975508-86d6ae00-7b14-11ea-9093-1b1f9752a3aa.png)

**Comment by mat007** [comment]
Do you happen to have Active Directory enabled?

**Comment by BarryLoo** [comment]
> Do you happen to have Active Directory enabled?

My _Server_ in services.msc is stopped. I turn it on and test the installation again. Now Docker has been  successfully installed. Thanks a lot.

**Comment by mat007** [comment]
Ah, nice! That’s a variant of #5150 then, which has been fixed in Edge 2.2.3.0 and will be available in the next Stable.
I’ll go ahead and close the ticket then!

**Comment by SgtPooki** [comment]
FYI that server service is not started for me, and when I attempt to start it I get an error. Tracking down solutions for that now.

**Comment by BarryLoo** [comment]
> FYI that server service is not started for me, and when I attempt to start it I get an error. Tracking down solutions for that now.

Well, check the system event log at the time when you start _Server_ service start faild. The log will show the detail for you. FYI the event log is belong to System And Security which in _Control Pannel_
