### ISSUE TITLE
Docker starts on one account but not the other

### ISSUE THREAD

**Issue by themac13** [docker/for-win#5979]
Hi, we have a problem where we are not able to start docker in a nested VM. It works on one account but nothe other. I made sure that my account exist in the administrators group, the docker-user and hyper-v. This is my diagnostic ID

F70E0D91-8ECA-458E-960B-DFC40A18BC0B/20200310182531

**Comment by stephen-turner** [comment]
Sorry, Docker Desktop is not supported in a nested virtualisation situation. It sometimes works and sometimes doesn't, but it's largely out of our control.
