### ISSUE TITLE
Unable to start Docker: HNS failed with error : The parameter is incorrect.

### ISSUE THREAD

**Issue by marijnd** [docker/for-win#598]
Cannot start Docker for Windows

In the logfile I get the error message:

    Error starting daemon: Error initializing network controller: Error creating default network: HNS failed with error : The parameter is incorrect. 

    at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings)
    at Docker.Backend.ContainerEngine.Windows.Start(Settings settings)
    at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
    at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

#### Info
  - Diagnostic ID 4D55769B-8F78-4A4B-8A84-5787644105EA/2017-03-21_10-59-05
  - Docker version 17.03.0-ce, build 60ccb22
  - Windows Version 1607 (OS Build 14393.935)

[service.txt](https://github.com/docker/for-win/files/857704/service.txt)

**Comment by apetres** [comment]
`Get-NetNat | Remove-NetNat` worked for me (see https://github.com/docker/docker/issues/29207).

**Comment by rustyx** [comment]
I had this issue which seems to have been caused by a custom NAT entry. After removing the NAT the issue was resolved.

Check in PowerShell: `Get-NetNat`, if anything is returned, try removing with `Remove-NetNat` (unless you really need it of course, for example for a Hyper-V VM).

**Comment by marijnd** [comment]
`Get-NetNat | Remove-NetNat` also worked for me.

At first it failed (InvalidOperation) but after a few tries it worked. Docker runs now.

**Comment by caokennedy** [comment]
Hi, I am getting the same issue. I have tried Get-NetNat | Remove-NetNat and this failed to work. 
`fatal: Error starting daemon: Error initializing network controller: Error creating default network: HNS failed with error : {Object Exists} An attempt was made to create an object and the object name already existed. `

When I run dockerd --debug in Admin mode I get : `open //./pipe/docker_engine: Access denied `

Has anyone found a fix for this issue other than Get-NetNat | Remove-NetNat? 

Thanks,
Caoimhe

**Comment by zmrfzn** [comment]
@caokennedy  facing the same issue. tried `Get-NetNat | Remove-NetNat`, deleting HNS.data file and also recreating container-network. But it reappears repeatedly.

is there a fix for this? or an Open Bug?

**Comment by caoimhek7** [comment]
@zmrfzn I was using the same OS and Docker version
OS: Win Server 2016
Docker version: 18.06 ee

and rolled back to 17.03 docker ee as it was an issue with Windows and/or Docker. I contacted both Microsoft and Docker about this issue and it has made no progress.. Hoping to see a find in the next release.

**Comment by zmrfzn** [comment]
> @caokennedy facing the same issue. tried `Get-NetNat | Remove-NetNat`, deleting HNS.data file and also recreating container-network. But it reappears repeatedly.
> 
> is there a fix for this? or an Open Bug?
> 
> OS: Win Server 2016
> Docker version: 18.06 ee

There still seems to be the same issue. 

In 18.06.3 release it was mentioned that this issue was fixed on windows 
release notes here => [18.06.3](https://docs.docker.com/engine/release-notes/#18093). 

The HNS network just hangs and on restarting the host, it does not start the docker service.

Is there any workaround apart from reinstalling the docker feature all together ?

**Comment by rupakg** [comment]
I have the same issue. Containers are restarting indefinitely with these error messages:

```
HNS failed with error : The parameter is incorrect.
```
or 

```
starting container failed: container xxxxx: endpoint create on GW Network failed: failed to create endpoint gateway_xxxxx on network nat: HNS failed with error: The object already exists.
```
OS: Win 2016 Server Standard VM

**Docker Info:**
Client: Docker Engine - Enterprise
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        1578dcadd2
 Built:             05/04/2019 02:34:11
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Enterprise 2.1
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       be4553c
  Built:            Thu Apr 11 06:23:08 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 Universal Control Plane:
  Version:          3.1.3
  ApiVersion:       1.39
  Arch:             amd64
  BuildTime:        Mon Jan 28 18:25:34 UTC 2019
  GitCommit:        4be4a1f
  GoVersion:        go1.10.6
  MinApiVersion:    1.20
  Os:               linux
 Kubernetes:
  Version:          1.11+
  buildDate:        2019-01-15T17:33:26Z
  compiler:         gc
  gitCommit:        3e62468863641262df4dfd2a66610d23d4d792dd
  gitTreeState:     clean
  gitVersion:       v1.11.5-docker-4
  goVersion:        go1.10.6
  major:            1
  minor:            11+
  platform:         linux/amd64
 Calico:
  Version:          v3.5.0
  cni:              v3.5.0
  kube-controllers: v3.5.0
  node:             v3.5.0

**Comment by axehigh** [comment]
Same problem here.
 
Windows Server 2016 (windows/amd64 10.0.14393)
Docker version 19.03.5, build 2ee0c57608

Getting the following error message when trying to do docker-compose up

> Creating network "registry_default" with the default driver
> ERROR: HNS failed with error : The parameter is incorrect.

**Comment by pada57** [comment]
Any news on that one ? same issue

**Comment by adib-next** [comment]
any updates?

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation. If you have this issue you’ll need to open an issue on https://github.com/moby/moby instead as that is the more appropriate place.
