### ISSUE TITLE
docker-machine command not found.

### ISSUE THREAD

**Issue by hassaan4** [docker/for-win#5981]
Hi - I am facing issue in using docker-machine command. I am trying docker-machine command on latest version of docker desktop and facing error that "docker-machine : The term 'docker-machine' is not recognized as the name of a cmdlet, function, script file, or operable program."
![docker-machine not found](https://user-images.githubusercontent.com/33511054/76391715-1a8e5080-6396-11ea-9138-b735c62ec34a.PNG)

**Comment by mat007** [comment]
As per the release notes:
> Docker Machine is no longer included in the Docker Desktop installer. You can download it separately from the [Docker Machine releases](https://github.com/docker/machine/releases) page.

**Comment by hassaan4** [comment]
Hi @mat007 - when i try to create the machine after installing docker machine from release page it gives error that " Error with pre-create check: "Powershell was not found in the path"
![docker-machine error](https://user-images.githubusercontent.com/33511054/76400868-069f1a80-63a7-11ea-93a1-95f2883c4b5a.PNG)
 "

**Comment by mat007** [comment]
I suppose that’s an issue to raise on https://github.com/docker/machine

**Comment by hassaan4** [comment]
Hi @mat007 - Please specify clearly as i am unable to find.

**Comment by hassaan4** [comment]
Thanks @mat007
