### ISSUE TITLE
Adding "hosts":  ["tcp://0.0.0.0:2375"] to daemon configuration JSON prevents Docker from starting

### ISSUE THREAD

**Issue by Yopt** [docker/for-win#5984]
- [V] I have tried with the latest version of my channel (Stable or Edge)
  - [V] I have uploaded Diagnostics
  - Diagnostics ID:20200311082452
[20200311082452.zip](https://github.com/docker/for-win/files/4317041/20200311082452.zip)

### Expected behavior
Docker starts normally
### Actual behavior
Adding "hosts":  ["tcp://0.0.0.0:2375"] to daemon configuration JSON prevents Docker from starting
### Information
  - It is reproducible
  - Windows Version: Windows 10 1909
  - Docker Desktop Version: 2.2.0.3 stable, Engine 19.03.5
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
Use configuration
{
  "registry-mirrors": [],
  "insecure-registries": [],
  "debug": true,
  "experimental": false,
  "hosts":  ["tcp://0.0.0.0:2375"]
}
[20200311082452.zip](https://github.com/docker/for-win/files/4316977/20200311082452.zip)

**Comment by sHlyoMa** [comment]
The same behavior for Docker Desktop Version: 2.2.0.5 and Win 10 (1909)
