### ISSUE TITLE
Totally broken Docker Desktop 2.2.0.3, factory resets or reinstalling not helping.

### ISSUE THREAD

**Issue by bdegreve** [docker/for-win#5986]
- [x] I have tried with the latest version of my channel (Stable ~or Edge~)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 0F0CABA5-5A49-470B-9B60-213306896940/20200311100407

OK, this one is really puzzling me.  I tried several times to completely remove Docker Desktop from my machine and to reinstall it, trying to reset to factory defaults, rebooted the machine, followed instructions from https://success.docker.com/article/how-to-completely-remove-docker-in-windows-10, but the abnormal behavior remains.  Reinstalling 2.1.0.5 still seem to work, but 2.2.0.3 is totally broken for me.

### Expected behavior

To be able to use docker desktop I suppose :-/
- To be able to change settings in the settings windows, and to be able to click on Apply & Restart (see screenshot)
- Not having a growing list of wsl.exe subprocesses (see screenshot)
- Being able to switch to linux containers
- Being able to factory reset docker desktop.

### Actual behavior

I'm seeing a number of unexpected behaviors, not sure if they're all related:
- I'm seeing a growing list of `wsl.exe` child processes (see screenshot), while WSL 2 support is supposedly disabled
- The "Apply & Restart" button remains disabled, even if I try to toggle some of the settings checkboxes (see screenshot).
- If I check some of the settings checkboxes, and I close the window, next time I open Settings window, the settings are again unchecked.
- I cannot switch to Linux containers without Docker Desktop crashing (so I'm on Windows containers)
- I cannot do DNS lookups from within a windows container like servercore.

![image](https://user-images.githubusercontent.com/8344480/76407790-2d038c80-638c-11ea-91c7-13513f044f35.png)

![image](https://user-images.githubusercontent.com/8344480/76407890-5d4b2b00-638c-11ea-9476-edfcdbebd2af.png)

### Information

  - Windows Version: 1909 (OS Build 18363.657)
  - Docker Desktop Version: 2.2.0.3 (42716)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

I don't know how to reproduce this.  It seems to be isolated to my machine.  I suppose I tried to enable WSL 2 after I upgraded to 2.2.0.3, and it has been troubles ever since.
  1. ...
  2. ...

### Backtrace

```
Docker.Core.Backend.BackendDestroyException:
One or more errors occurred.
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

  System.AggregateException:
  One or more errors occurred.
     at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
     at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
     at Docker.Backend.LifecycleClient.DockerStart()
     at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions, Credential credential)
     at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
  
     Docker.Core.HttpBadResponseException:
     unable to fetch daemon.json: Get http://unix/engine/daemon.json: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
        at Docker.Backend.HttpClientExtensions.<ParseResponseBodyAsJsonAsync>d__2`1.MoveNext()
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at Docker.Backend.HttpClientExtensions.<GetJsonAsync>d__0`1.MoveNext()
```

**Comment by simonferquel** [comment]
Hi, the WSL-related issue has already been fixed on our master branch but it is not available yet. It should be released in next Edge release, and on stable a little later.

I can send you a private build to unlock your, or you can try one of the 2 workarounds we have for this issue:
- Disable WSL Windows feature
- Or update to Windows Insider slow ring

**Comment by bdegreve** [comment]
Turns out, WSL is already disabled :-/  Don't know when this happened.
I cannot update to Windows Insider slow ring.

Currently I'm back on Docker version 2.1.0.5, which is behaving more as expected, except I cannot do any DNS lookups from inside a container (above I reported this as an issue I'm having with 2.2.0.3, I must have remembered incorrectly)

**Comment by bdegreve** [comment]
OK, so between _enabling_ WSL and upgrading to 2.2.0.4, this erratic behavior disappeared:
- I can switch back and forth between Windows and Linux containers
- I can actually change the settings and click Apply & Restart
- The wsl.exe subprocesses are gone

DNS lookups (like for google.com) are still not possible from windows containers. From linux containers nslookup works but pinging to google.com doesn't.  But this is likely a separate issue ...
