### ISSUE TITLE
Docker Desktop, docker stuck on starting.

### ISSUE THREAD

**Issue by brannmar** [docker/for-win#5988]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 43CC9CA4-2E60-4388-9600-A81CC9A54E42/20200311122349

### Expected behavior
That i actually starts
### Actual behavior
Never starting. 
### Information

The Desktop app starts but the deamon does not. 
  - Windows Version: 
![image](https://user-images.githubusercontent.com/7968452/76417180-b327cf00-639c-11ea-9fea-fea3e469cb35.png)

  - Docker Desktop Version: 2.2.0.3 (42716)

  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

**Comment by brannmar** [comment]
I found an closed issue that pointed me in the directon to solve this. https://github.com/docker/for-win/issues/5737

**Comment by itunc** [comment]
I had the same issue, when I tried to enable "Expose daemon on tcp://localhost:2375 without TLS" on Docker Desktop Version: 2.2.0.5

Sure there is a workaround given at (https://github.com/docker/for-win/issues/3171#issuecomment-459205576) but you need time to figure this out hence is not a solution. 
This bug problem be solved by the docker windows - desktop team!
