### ISSUE TITLE
File not found - 2EF3F30B-0AF7-4275-AF1C-259D68712ADE/20200311155417

### ISSUE THREAD

**Issue by hardcoremore** [docker/for-win#5990]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mat007** [comment]
Dup of #5955
