### ISSUE TITLE
Failed to check wsl-bootstrap version: exit code: 1

### ISSUE THREAD

**Issue by wang7143** [docker/for-win#5994]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F52A3B0C-9606-475D-8527-8C61F556B527/20200312023232

### Actual behavior
i open docker desktop, It is not running properly, and i can't open the ubuntu on wsl2 with powershell, it does not respond. 
but yesterday they working fine
### Information

  - Windows Version: windows 10 home insider preview Build 19577.re_prerelease.200228-1439
  - Docker Desktop Version: 2.2.20
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: NO
  but i install the  VMware® Workstation 15 Pro (15.1.0 build-13591040) in my system
### Steps to reproduce the behavior

Docker.Core.Backend.BackendException:
Failed to check wsl-bootstrap version: exit code: 1
 stdout(utf8): 
 stdout(unicode): 
  stderr (utf8): �ο��Ķ������Ͳ�֧�ֳ��ԵĲ�����

  stderr (unicode): 캲벿쒵풶췐뮲Ꟗ횳ꊳ퓊쒵�ꎡ഍�
   在 Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   在 Docker.Actions.DoRestartVM(Settings previousSettings)
   在 Docker.Actions.<>c__DisplayClass34_0.<RestartVM>b__0()
   在 Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

  System.InvalidOperationException:
  Failed to check wsl-bootstrap version: exit code: 1
 stdout(utf8): 
 stdout(unicode): 
  stderr (utf8): �ο��Ķ������Ͳ�֧�ֳ��ԵĲ�����

    stderr (unicode): 캲벿쒵풶췐뮲Ꟗ횳ꊳ퓊쒵�ꎡ഍�
     在 Docker.Backend.ContainerEngine.WslEngine.WslOneShotResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode)
     在 Docker.Backend.ContainerEngine.WslEngine.IsDistroDeployed(List`1 existingDistros)
     在 Docker.Backend.ContainerEngine.WslEngine.DoStart(Settings settings, String daemonOptions, Credential credential)
     在 Docker.Backend.ContainerEngine.WslEngine.Restart(Settings settings, String daemonOptions, Credential credential)
     在 Docker.Backend.BackendNamedPipeServer.<Run>b__8_3(Object[] args)
     在 Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
     在 Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

**Comment by simonferquel** [comment]
I think it is VMWare that basically killed the Windows Virtualization Platform.
WSL2 has the same limitation has full Hyper-V related to 3rd party virtualization tools.

**Comment by wang7143** [comment]
> I think it is VMWare that basically killed the Windows Virtualization Platform.
> WSL2 has the same limitation has full Hyper-V related to 3rd party virtualization tools.

i colesd vmware, I cannot enter the subsystem ubuntu, If I switch wsl to version 1, I can enter ubuntu

**Comment by simonferquel** [comment]
Yes, if you can't enter ubuntu in version 2, that means that wsl2 is borken somehow. VMWare seems likely to have killed it. (WSL 2 relies on the same virtualization platform as Hyper-V).

**Comment by wang7143** [comment]
> Yes, if you can't enter ubuntu in version 2, that means that wsl2 is borken somehow. VMWare seems likely to have killed it. (WSL 2 relies on the same virtualization platform as Hyper-V).

You mean i need to uninstall vmware

**Comment by simonferquel** [comment]
Yes, wsl 2 and vmware are not compatible at the moment.

**Comment by wang7143** [comment]
> Yes, wsl 2 and vmware are not compatible at the moment.

thank you very much
