### ISSUE TITLE
Docker stop does not send control signal for Windows containers with TTY

### ISSUE THREAD

**Issue by StephenCleary** [docker/for-win#5996]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: CAAF42FA-50A5-4E40-8EAC-B94B538F0497/20200312031037

### Expected behavior

`docker stop` sends Windows containers `CTRL_SHUTDOWN_EVENT`.

### Actual behavior

`docker stop` correctly sends Windows containers `CTRL_SHUTDOWN_EVENT` *if* there is no TTY (`-t` option). If `docker stop` is used on a container run with `-t`, then no console control event is sent to the container.

### Information

  - Windows Version: 10.0.18362 Build 18362
  - Docker Desktop Version: 2.2.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No.

### Steps to reproduce the behavior

1. Build a console app that listens for console control signals.
2. Run the app in a Windows docker container, passing the `-t` flag.
3. Stop that docker container.

https://github.com/StephenClearyExamples/DockerWindowsSignalRepro

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place?
