### ISSUE TITLE
2.2.2.0 version docker for desktop windows can't find k8s menus

### ISSUE THREAD

**Issue by King-Pan** [docker/for-win#6000]
the docker for desktop windows version is 2.2.2.0(43066)

but i can not found the k8s menu

**Comment by King-Pan** [comment]
![image](https://img2018.cnblogs.com/blog/375390/201906/375390-20190604021320927-1584245826.png)

i can not found k8s menus

**Comment by King-Pan** [comment]
my docker for desktop

![image](https://user-images.githubusercontent.com/9877701/76510248-3ffd8600-648c-11ea-9d78-26d9fff0faf4.png)
![image](https://user-images.githubusercontent.com/9877701/76510281-50156580-648c-11ea-8721-8b4b6dccfe17.png)

**Comment by mat007** [comment]
You need to switch to Linux containers:
![image](https://user-images.githubusercontent.com/2386884/76510872-964dd300-6452-11ea-91d4-71174d7c9cba.png)

**Comment by King-Pan** [comment]
thank you very much. i can running k8s in my computer.
