### ISSUE TITLE
If upgrade of Docker Desktop fails, retry is not possible

### ISSUE THREAD

**Issue by mochr** [docker/for-win#6015]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 48445EAD-061C-4EBD-A452-ED708BD55BA0/20200402130638

### Expected behavior
If for some reason the upgrade of Docker Desktop fails, I would expect to be able to retry at a later time. If retry is not possible, I would like to revert to the older version of Docker Desktop.
### Actual behavior
An error message is shown, and after acknowledgement Docker Desktop is no longer installed on the computer. Docker Desktop must be manually downloaded and installed to make it work again.

Error message:
> The Server service is not started.
> 
>    at System.DirectoryServices.DirectoryEntry.RefreshCache()
>    at System.DirectoryServices.AccountManagement.PrincipalContext.DoMachineInit()
>    at System.DirectoryServices.AccountManagement.PrincipalContext.Initialize()
>    at System.DirectoryServices.AccountManagement.PrincipalContext.get_QueryCtx()
>    at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithTypeHelper(PrincipalContext context, Type principalType, Nullable`1 identityType, String identityValue, DateTime refDate)
>    at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithType(PrincipalContext context, Type principalType, String identityValue)
>    at System.DirectoryServices.AccountManagement.GroupPrincipal.FindByIdentity(PrincipalContext context, String identityValue)
>    at CommunityInstaller.CreateGroupAction.<DoAsync>b__33_0()
>    at System.Threading.Tasks.Task.Execute()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at CommunityInstaller.InstallWorkflow.<HandleD4WPackageAsync>d__29.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__24.MoveNext()

### Information

  - Windows Version: Windows 10 Enterprise, 1803, 17134.1365
  - Docker Desktop Version: 2nd newest I think. Can not verify as it was removed by the updater.
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Get prompt to update Docker Desktop.
  2. Click yes to update
  3. Make the updater fail (I think the "Server"-process was not running, causing the updater to fail).
  4. The upgrade will fail and Docker Desktop has been removed from the computer.

**Comment by mochr** [comment]
Still an issue with the latest version.
Updated with Diagnostics ID, error message and updated Windows version.

**Comment by mat007** [comment]
This should be fixed on the Edge channel, see https://docs.docker.com/docker-for-windows/edge-release-notes/#bug-fixes-and-minor-changes but it will only reach Stable in about ~3 weeks.

Closing as dup of #5150

**Comment by mochr** [comment]
Great, thanks!
