### ISSUE TITLE
Listing the contents of a directory in a shared volume with 200K files from within a ubuntu container gets stuck

### ISSUE THREAD

**Issue by david-sackstein** [docker/for-win#6020]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4D3862D9-BFCB-4F31-9A40-5107C9450310/20200314120504

### Expected behavior
The ```find .``` command should start almost immediately to list all files in the folder shared as a volume with the host even if there are 200000 files in the folder.  
This can be expected to take some time, but it should begin almost immediately.

### Actual behavior
The ```.``` character is printed but nothing else. (I waited 10 minutes)
Then the shell does not respond.   
Moreover, CTRL C does not interrupt the ```find .``` command.  
The only way I found to stop the container was to restart Docker Desktop

### Information

  - Windows Version: Windows 10 Pro
  - Docker Desktop Version: Docker Desktop 2.2.0.3 (42716) stable
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No
  - Is this reproducible? Yes 100% of the time

### Steps to reproduce the behavior

 1. Install Docker Desktop 2.2.0.3 (42716) stable on Windows 10 
 2. Configure docker to work in WSL (Ubuntu 16 distribution) [the usual procedure here]
    - Expose daemon on ```tcp://localhost:2375 without TLS```
    - In WSL, define environment variable ```DOCKER_HOST=localhost:2375```
    - In WSL, in ```/etc/wsl.conf``` in the ```[automount]``` section, define ```root = /```
 3. Create a folder on the Windows host that contains 200,000 files (even small ones). e.g. ```c:/temp```
 4. Run a docker container, mapping c:/temp on the host to /opt in the container as follows:
    ```docker run -it -v /c/temp:/opt ubuntu bash```
 5. In the bash prompt of the container run ```cd /opt``` and then ```find .```
### Notes
- I have tried the same with 10000 files and eventually the command completes.  
This leads me to the conclusion that the ```find``` command is not stuck but that it is taking an extremely long time to complete and that it only produces its output when it completes.
- I have tried the same using ```ls``` instead of ```find .```
The reason I recommend using ```find``` to reproduce is because ```ls``` sorts its output which naturally requires delaying the print of the output until all files have been scanned.
- Even if ```ls``` can be expected to delay printing until the scanning is complete, I would still expect the operation to take a reasonable amount of time compared with the same command run on the host.
@BretFisher

**Comment by david-sackstein** [comment]
Closed by mistake. Reopened.
Can be reproduced with: Docker Desktop 2.2.0.4 (43472) stable on Windows 10

**Comment by BretFisher** [comment]
Note that Docker Desktop doesn't support WSL1 AFAIK. Can you reproduce without using WSL1?

Curious if you've tried it with Windows insider preview (version 2004, which goes stable release in a few weeks I think), which changes to WSL2 which will totally change this file behavior, and can get may times the performance boost on file I/O.

See https://youtu.be/MrZolfGm8Zk?t=121 for a demo on I/O differences, and the [Docker blog post on the technical changes](https://www.docker.com/blog/new-docker-desktop-wsl2-backend/) happening once you update your Windows 10 to 2004 and WSL2.
