### ISSUE TITLE
when I open Kubernetes , the "settings" alawys loading...

### ISSUE THREAD

**Issue by lone741** [docker/for-win#6036]
when I open Kubernetes , the "settings" alawys loading... So I can't set any sets.

the log file "time="2020-03-16T17:08:11+08:00" msg="cannot list nodes: Get https://kubernetes.docker.internal:6443/api/v1/nodes: EOF""

**Comment by Tonyangl** [comment]
I have same issue。

**Comment by yanivpaz** [comment]
see https://github.com/docker/for-win/issues/6264
