### ISSUE TITLE
Your recent update just killed my host file :(

### ISSUE THREAD

**Issue by noc2spam** [docker/for-win#6038]
This is sad and dangerous at the same time. My host file got corrupted due to your update. Now, all the virtual host entries are gone. Is this some kind of a joke????

I see a bunch of NULL charecters and then:

```
# Added by Docker Desktop
192.168.x.x host.docker.internal
192.168.x.x gateway.docker.internal
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
```

Please fix it. Uninstalling the software for now.

**Comment by mat007** [comment]
Sorry about that @noc2spam, do you remember if this was an install from scratch or an upgrade (from which version)? Stable or Edge?
Could you take a look at log files in `%LOCALAPPDATA%\Docker` to see if there is any error?
Could you attach `%LOCALAPPDATA%\Docker\Log.txt` to this issue, please?
If you don’t have quite yet uninstalled Docker Desktop can you create and upload a diagnostics bundle using the button in the Troubleshoot window?

Thank you!

**Comment by noc2spam** [comment]
> Sorry about that @noc2spam, do you remember if this was an install from scratch or an upgrade (from which version)? Stable or Edge?
> Could you take a look at log files in `%LOCALAPPDATA%\Docker` to see if there is any error?
> Could you attach `%LOCALAPPDATA%\Docker\Log.txt` to this issue, please?
> If you don’t have quite yet uninstalled Docker Desktop can you create and upload a diagnostics bundle using the button in the Troubleshoot window?
> 
> Thank you!

Hi Mathieu,

Thanks for the reply. No, it was some kind of auto upgrade, to a clean install. I was trying the software out. I am fairly new to this concept so I am not exactly sure what caused this behavior. 

Here's my log like you asked for.
https://pastebin.com/MXz7ZjTw

Thank you for the help. Much appreciated. :)

**Comment by mrwensveen** [comment]
For what it's worth, I've had issues with hosts files turning to a bunch of NULL characters on my laptop before, and am pretty sure this was unrelated to Docker. If this happens before Docker writes its host info to the file, Docker may appear to be the culprit but is actually not.

I can't guarantee that Docker isn't the culprit, however. It just doesn't necessarily have to be.
