### ISSUE TITLE
Docker Desktop installer reported by Eset to contain a virus

### ISSUE THREAD

**Issue by bzuu-easy** [docker/for-win#6052]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
After downloading the Docker Desktop installer it should install without issues.

### Actual behavior
After downloading Docker Desktop for Windows it gets deleted by Eset Antivirus.

### Information

  - Eset Version: 7.1.2053.0 also seen with 7.2.2055.0
  - Reported malware: MSIL/Shutdowner.BV trojan
  - SHA1 hash of downloaded file: 9DFB2A5E8764BC844AC02F17605C6D092D2D26D9
  - SHA256 hash of downloaded file: 6BAF54CB0A719A5E53469FDF20D73CE8690065E8191654E3DFF1FDA180C15FF6

### Steps to reproduce the behavior

  1. Download the current installer from https://hub.docker.com/editions/community/docker-ce-desktop-windows
  2. Run the file through Eset

**Comment by blazejkarwowski** [comment]
Same applies to edge channel installer.

**Comment by unherz** [comment]
This is very important for some companies. 
Is this an issue related to docker or ESET?

Btw: also actual Docker desktop updates are failing cause of this suspicious behaviour.

**Comment by blazejkarwowski** [comment]
Its hard to know if its ESET related as i dont have access to other antivirus software (both in company and in home I use ESET)

**Comment by stephen-turner** [comment]
Thanks for the report. We have reported it to ESET.

**Comment by allanbarklie** [comment]
I have the same ESET catch, also chocolatey reports incorrect checksum
ERROR: Checksum for 'C:\Users\[user name]\AppData\Local\Temp\chocolatey\docker-desktop\2.2.0.4\Docker Desktop Installer.exe' did not meet '6baf54cb0a719a5e53469fdf20d73ce8690065e8191654e3dff1fda180c15ff6' for checksum type 'sha256'

**Comment by inkr-xx** [comment]
Same problem in different computers
![image](https://user-images.githubusercontent.com/2520220/76860058-14e7ad80-6863-11ea-892e-d449155a0651.png)

**Comment by StefanScherer** [comment]
Thanks for reporting this issue. We've contacted ESET and they confirm that this is a false positive.
For ESET users please update your antivirus database. 
After that downloading and installing Docker Desktop should work again. 
Sorry for the inconvenience.

**Comment by stephen-turner** [comment]
Thanks for sorting it, @StefanScherer.

**Comment by bzuu-easy** [comment]
Thank you @stephen-turner and @StefanScherer for the quick resolution. I've just updated Eset and it works fine now.
