### ISSUE TITLE
kubernetes keeps at the status starting and doesnt start

### ISSUE THREAD

**Issue by oussamaelhajoui** [docker/for-win#6057]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Kubernetes should start

### Actual behavior
Kubernetes keeps at thje status starting and does not start

### Information

  - Windows Version: 10 - 2004
  - Docker Desktop Version: latest of writing the post  `2.2.0.4`
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Enable the experimental WSL 2 based engine
  2. Enable Kubernetes

**Comment by Tonyangl** [comment]
I have same issue。

**Comment by davidlday** [comment]
Likewise. This is repeated in my logfile:

```text
[11:25:36.983][ApiProxy          ][Info   ] time="2020-03-19T11:25:36-04:00" msg="cannot list nodes: Get https://kubernetes.docker.internal:6443/api/v1/nodes: Service Unavailable"
[11:25:36.984][GoBackendProcess  ][Info   ] time="2020-03-19T11:25:36-04:00" msg="external: POST /events 200 \"Go-http-client/1.1\" \"\""
```

**Comment by ericjacques** [comment]
removing the %ProgramData%/DockerForDesktop/pki as described in [#3799](https://github.com/docker/for-win/issues/3799) fixed the issue for me.
