### ISSUE TITLE
Docker stops working after some minutes 

### ISSUE THREAD

**Issue by hg-schneider** [docker/for-win#6060]
- [x] I have tried with the latest version of my channel (Stable)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D4438153-639B-4BBB-926C-A4A811B9A0DD/20200318080504

### Expected behavior
Containers can be started and they run normally

### Actual behavior
Containers stop after a few minutes.
Docker seems to crash
No more containers can be run

### Information
The problem is 100% reproducable
I have observed it since aproximately 2 weeks

I observed the Problem in 2.2.0.3. To check if it is related to that version I've downgraded to a previous version but it also did not work with that. Also after receiving 2.2.0.4 the issue is still there.
Removing Docker completely and reinstalling does not fix the issue too.

Windows 10 Version: 1803 (Build 17134.1365)
Docker Desktop Version: 2.2.0.4
The Window 10 System is accessed via Citrix

### Steps to reproduce the behavior
Run:
for i in {1..100}; do docker run --rm hello-world; date ; sleep 60; done

After approximately 15 Minutes Docker showing the following error:
C:\Program Files\Docker\Docker\resources\bin\docker.exe: Error response from daemon: Bad response from Docker engine.
time="2020-03-18T11:34:11+01:00" level=error msg="error waiting for container: EOF"

After that every docker command fails. For example
$ docker ps
Outputs the error:
Error response from daemon: open \\.\pipe\docker_engine_linux: Das System kann die angegebene Datei nicht finden.

See attached log:
[docker-hello-world-output.txt](https://github.com/docker/for-win/files/4348625/docker-hello-world-output.txt)

**Comment by hg-schneider** [comment]
In the meantime I've upgraded to Windows 10 Enterprise x64 Version 19.09 (Build 18363.720) but the issue is still the same.

I've uploaded new diagnostic data.
Diagnostics ID: E5651B20-8267-42C1-B181-AF89D704C12F/20200323152905

**Comment by hg-schneider** [comment]
Still the same for Docker Desktop Community version 2.3.0.3 (45519)

**Comment by hg-schneider** [comment]
As none else seems to have the same issue, I close the ticket.

**Comment by oocx** [comment]
We seem to have the same problem on at least 3 different machines. Please reopen the issue.

**Comment by hg-schneider** [comment]
I reopen the issue as requested by @oocx.

Currently I am running Docker Desktop Community version 2.3.0.4
I still have the issue with this version.

**Comment by oocx** [comment]
@hg-schneider We may have found the solution for us, It looks like it could be a bug in vmware tools (as mentioned in #5044). I'll let you know if that fixed the problem for us as soon as I have feedback from all devs who have the problem.
