### ISSUE TITLE
driver "windowsfilter" failed to remove root filesystem

### ISSUE THREAD

**Issue by fafg** [docker/for-win#6064]
```shell script
docker rm -f 02ed5773b8ec
Error response from daemon: container 02ed5773b8ecc0428a9fff574e3ab9946c8a6b88f2fd1f0c1245c1e366c32be0: driver "windowsfilter" failed to remove root filesystem: failed to detach VHD: The device is not ready.: rename C:\ProgramData\Docker\windowsfilter\02ed5773b8ecc0428a9fff574e3ab9946c8a6b88f2fd1f0c1245c1e366c32be0 C:\ProgramData\Docker\windowsfilter\02ed5773b8ecc0428a9fff574e3ab9946c8a6b88f2fd1f0c1245c1e366c32be0-removing: Access is denied.
``` 

### Expected behavior
container removed

### Actual behavior
status: Removal in Progress (forever, even after windows reboot solution)

### Information

  - Windows Version:
![image](https://user-images.githubusercontent.com/9274235/76980833-fb656500-6939-11ea-99ed-d015d2b0550c.png)
  - Docker Desktop Version:
![image](https://user-images.githubusercontent.com/9274235/76980320-577bb980-6939-11ea-8097-b1978a1bc587.png)
  - Are you running inside a virtualized Windows: YES

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place?

**Comment by fafg** [comment]
thank you very much @mat007
