### ISSUE TITLE
Docker Inside a VM crass

### ISSUE THREAD

**Issue by dsalasjanda** [docker/for-win#6065]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
Docker Desktop is not supported inside a VM.
