### ISSUE TITLE
Docker Desktop resizes VM on StartUp

### ISSUE THREAD

**Issue by DotNet-Ninja** [docker/for-win#6067]
I'm building a script in PowerShell core to set up my local windows machine with a kubernetes cluster and I am adjusting the size of the DockerDesktopVM in my script and restarting Docker.  When I switch the daemon, it resizes the VM back to it's original size:

Steps:
Stop docker services
Stop VM
Set VM Memory
Start VM
Start docker services
Switch Daemon twice (Per advice on Stack-Overflow  https://stackoverflow.com/questions/51760214/how-to-restart-docker-for-windows-process-in-powershell)
DockerCli.exe -SwitchDaemon
DockerCli.exe -SwitchDaemon

I have logging between each step and after the final daemon switch the memory size has switched back to it original value.  (It was my new value right before that call)

Is this by design for some reason?

**Comment by stephen-turner** [comment]
Why do you want to set the memory in a script not in the UI?

If it has to be in a script, I would guess that setting it in the Docker settings file would work, although I haven't tried.

**Comment by mat007** [comment]
Depending on your Docker Desktop version changing the disk size may be broken at the moment, see #5881 but otherwise you should be able to change it in the settings file `%APPDATA%\Docker\settings.json` field `diskSizeMiB`.

**Comment by stephen-turner** [comment]
@mat007 I think this was RAM not disk size.

**Comment by DotNet-Ninja** [comment]
I'll give that a try today and see if that will work.  Thanks for the suggestion.

**Comment by DotNet-Ninja** [comment]
> 
> 
> Why do you want to set the memory in a script not in the UI?
> 
> If it has to be in a script, I would guess that setting it in the Docker settings file would work, although I haven't tried.

FWIW: I'm doing this in a script so that I can roll it out to all of the developers on my team consistently.

**Comment by DotNet-Ninja** [comment]
I was able to get that approach to work:
For anyone interested here is the script

```
Stop-Service *docker*
$settingsFile = "$env:APPDATA\Docker\settings.json"
$settings = Get-Content $settingsFile | ConvertFrom-Json
$settings.memoryMiB = 8192
$settings | ConvertTo-Json | Set-Content $settingsFile
Start-Service *docker*        
&$Env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchLinuxEngine
```
Thanks for your help!

**Comment by stephen-turner** [comment]
Great, glad it worked and thanks for letting us know.

**Comment by nebuk89** [comment]
@DotNet-Ninja is there anything else that would make it easier for you to roll this out to your team? 🤔

**Comment by DotNet-Ninja** [comment]
> 
> 
> @DotNet-Ninja is there anything else that would make it easier for you to roll this out to your team? 🤔

At this point I think I have most of the process for setting things up worked out and we are reviewing it.  Thanks again for everyone's help!
