### ISSUE TITLE
[WSL2] Unable to mount named volumes with a number for the 1st or 2nd character

### ISSUE THREAD

**Issue by sleighzy** [docker/for-win#6070]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

When creating and mounting a named volume that contains numbers in the name it should mount as expected.

### Actual behavior

A permission denied error occurs if the volume name contains a number in the first or second position of the name.

### Information

  - Windows Version: Windows 10 Pro (Slow Ring) 19041.153
  - Docker Desktop Version: Edge 2.2.2.0 (43066)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

Prerequistes:
- Be on the Windows Insider build, I'm on the Slow Ring, I have not tried with the Fast Ring
- Have Docker Desktop running
- Have the new WSL 2 engine enabled in Docker Desktop
- Have it enabled with your WSL distro, I'm using Ubuntu 18.04
- Open your WSL distro to run the below Docker commands, the local Docker service in the Ubuntu distro is not running so this will use the WSL 2 engine

The below steps are based on the Docker documentation for named volumes and the Nginx example:
https://docs.docker.com/storage/volumes/

Using the volume name of "myvol2" as per the example in the documentation works as expected. The below steps show that "m2vol2" does not.

  1. Create a docker volume named "m2yvol2"
  2. Run the nginx container and attempt to mount the "m2yvol2" volume to /app as per the example
  3. This fails with a permission denied error
  
```sh
$ docker volume create m2yvol2
m2yvol2
$ docker run -d --name devtest -v m2yvol2:/app nginx:latest
docker: Error response from daemon: mkdir m2yvol2: permission denied.
See 'docker run --help'.

$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

Attempt to run the same container with the same named volume but using the long syntax works as expected:

```sh
$ docker run -d --name devtest --mount source=m2yvol2,target=/app nginx:latest
b55bfc10f5c691322eb1ef393e820463e288ed5391f461b7a029237dcdd8c76c

$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
b55bfc10f5c6        nginx:latest        "nginx -g 'daemon of…"   3 seconds ago       Up 2 seconds        80/tcp              devtest
```

This issue does not occur when:
- using named volumes and running Docker at the Windows command line, i.e. not your WSL distro.
- using named volumes and running Docker from the WSL Ubuntu distro and Docker Desktop is not running
- if the volume name contains numbers but they are not the first or second character in the name
- when mounting volumes using the long syntax
- when mounting directories on the host, even if they do have numbers in the first or second character

This was initially discovered when I was attempting to use k3d to deploy k3s clusters. When k3d creates the cluster it also creates a named volume that starts with "k3d-k3s-". It took me a long time to work out that the problem was with the "3" in "k3d". When I update their source code to use "rancher-" as the prefix instead it works as expected.

**Comment by sleighzy** [comment]
I have retested this with the Stable Channel version of Docker Desktop and found it to be working as expected there. It seems I'm only getting this with Edge. I'll switch back to Edge again and see if I'm able to replicate again.

**Comment by sleighzy** [comment]
Confirmed. I'm only experiencing the issue on the Edge channel.

**Comment by simonferquel** [comment]
Thanks, I'll try to reproduce on our current master today.

**Comment by simonferquel** [comment]
Hi, I confirm that I can't reproduce on current master neither from Ubuntu command prompt, not from powershell.

**Comment by sleighzy** [comment]
Thanks for that. I'm still able to replicate every time I switch to Edge 2.2.2.0 so will stay with Stable for the moment. Let me know if there's any other info you need, else could leave open for a bit to see if anybody else hits this. Probably something environmental on my end, but would have thought maybe others would have come across as well.

**Comment by sleighzy** [comment]
Closing as am seeing no issues in later updates of Docker Desktop.
