### ISSUE TITLE
Unable to start Docker on Windows

### ISSUE THREAD

**Issue by malinaa96** [docker/for-win#6076]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 
28751E3F-6A57-4D5D-9A8C-75BEE09595DB/20200319092859

### Actual behavior
Unable to start Docker, it throws errors [log.txt](https://github.com/docker/for-win/files/4353768/log.txt)

### Information
  - Windows Version: Windows 10 Pro
  - Docker Desktop Version:  19.03.8
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

**Comment by Kayuwaii** [comment]
Do you have any existing Hyper-V VM? If you do, you can either delete them(which is obviously not a good idea) or you can change Hyper-V default paths to new empty directories(you can switch back to the "normal" ones when you are not using docker.

![image](https://user-images.githubusercontent.com/24458540/77404041-65a25d80-6db1-11ea-82f3-629b581651d9.png)
I am refering to the default VM and VHD path. 
This was what fixed the issue for me

**Comment by malinaa96** [comment]
I finished with formatting my computer and now it works.
