### ISSUE TITLE
 hcsshim::CreateComputeSystem The request is not supported.

### ISSUE THREAD

**Issue by DevRCRun** [docker/for-win#6077]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 54D5C941-EE16-4DBF-B712-2DE165661D13/20200319095957

### Expected behavior

Windows containers start without issue (as they have previously on this machine).

### Actual behavior

docker run hello-world
C:\Program Files\Docker\Docker\resources\bin\docker.exe: Error response from daemon: hcsshim::CreateComputeSystem 70b6cf806eef813a8a93b40780c32e43f5406f0cbec10b922d3bd35ecc677b6c: The request is not supported.
(extra info: {"SystemType":"Container","Name":"70b6cf806eef813a8a93b40780c32e43f5406f0cbec10b922d3bd35ecc677b6c","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\70b6cf806eef813a8a93b40780c32e43f5406f0cbec10b922d3bd35ecc677b6c","Layers":[{"ID":"efdb9ef8-f3bd-5727-91d0-5cf37d4129f9","Path":"C:\\ProgramData\\Docker\\windowsfilter\\93bfb5264355e61159fcabb4e4a1f2463f288947a8718a7980109417f4434ec2"},{"ID":"5db7de6e-71a1-5cb1-b704-0ef5e921f317","Path":"C:\\ProgramData\\Docker\\windowsfilter\\d8d6d2081e02811bae76d90efb05b5006a16eb10e2a924ba691a2d323391b172"},{"ID":"a5d02035-0786-58f1-976d-ba7b00181d78","Path":"C:\\ProgramData\\Docker\\windowsfilter\\621d06be89dc3ece6cf1c9db3450d5739fff9872d5efef80aa8ef7bcaee23632"}],"HostName":"70b6cf806eef","HvPartition":true,"EndpointList":["26A95269-5607-46E2-AC84-4E60D850E246"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\621d06be89dc3ece6cf1c9db3450d5739fff9872d5efef80aa8ef7bcaee23632\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}).

### Information

  - Windows Version:
Container Host OS Product Name: Windows 10 Enterprise (1909 - OS build 18363.720 )
Container Host OS Build Label: 18362.1.amd64fre.19h1_release.190318-1202
  - Docker Desktop Version: 2.2.0.4 (43472)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No. 

### Steps to reproduce the behavior

attempt to start any windows container from mcr.microsoft.com or https://hub.docker.com/r/stefanscherer/node-windows/

I think this has occurred since the latest update, switch to Linux containers and they are fine.  Debug-ContainerHost.ps1 reports all is fine with the exception of the below but I think reading around you've removed this now anyway?

Get-VMSwitch : Hyper-V was unable to find a virtual switch with name "nat".
At C:\Development\1803 nanoservernode\Debug-ContainerHost.ps1:177 char:22

 [-] NAT Network's vSwitch is internal 30ms
   Expected: {Internal}
   But was:  {}
   223:       $switchType | Should Be "Internal"
   at <ScriptBlock>, C:\Development\1803 nanoservernode\Debug-ContainerHost.ps1: line 223
 [-] A Windows NAT is configured if a Docker NAT network exists 80ms
   Expected {0} to be greater than or equal to {1}
   233:        $winnatCount | Should Not BeLessThan $natCount
   at <ScriptBlock>, C:\Development\1803 nanoservernode\Debug-ContainerHost.ps1: line 233`

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place?
