### ISSUE TITLE
Mounting a Windows share to a container

### ISSUE THREAD

**Issue by Hamsterman** [docker/for-win#6083]
I have been looking hundreds of post that try to explain how to map a share to a container - but still no luck.

My setup
* Window Server 2019
* Docker Desktop (docker version 19.03.2)
* Docker containers set to "Linux Containers"
* Docker Engine config have an extra line:   "experimental": true
* NFS server enabled
* SMB 1.0/CIFS enabled
* A share called DockerShare on the same machine (Everyone Full Control on share and Filesystem).

It seems that some people have this working:
docker volume create --driver local --opt type=nfs --opt o=addr=127.0.0.1,hard,nolock,rw --opt device=:/DockerShare bar
docker run -it -v bar:/server-dev alpine sh

But I get this error:
C:\Program Files\Docker\docker.exe: Error response from daemon: error while mounting volume '/var/lib/docker/volumes/bar/_data': failed to mount local volume: mount :/DockerShare:/var/lib/docker/volumes/bar/_data, data: addr=127.0.0.1,hard,nolock: operation not supported.

When I switch to nfs4 I get a different error.
docker volume create --driver local --opt type=nfs4 --opt o=addr=127.0.0.1,hard,nolock,rw --opt device=:/DockerShare bar
docker run -it -v bar:/server-dev alpine sh

C:\Program Files\Docker\docker.exe: Error response from daemon: error while mounting volume '/var/lib/docker/volumes/bar/_data': failed to mount local volume: mount :/DockerShare:/var/lib/docker/volumes/bar/_data, data: addr=127.0.0.1,hard,nolock: connection refused.

Why is this so hard ? - shouldn't it be possible to code something that just work without so many problems.

By the way I did this as well
docker run -it -v //127.0.0.1/DockerShare:/server-dev alpine sh
No errors but I could not see the files from the DockerShare in the server-dev folder.
I tried to create a folder in the server-dev folder from within my container to my surprise it was still there after exited the container, removed it, did a docker volume prune and executed
docker run -it -v //127.0.0.1/DockerShare:/server-dev alpine sh
again.
Also I did a search for the folder I created but it could not be found on the Window host.

On last thing - I tried the "standard" way which is activating sharing of the C drive in Docker Deskop.
Then I started the container like this:
docker run -it -v /c/SomeTest/:/server-dev alpine sh
That works just fine - I can see the content of C:\SomeTest and I can add files in it which shows instant in the server-dev folder.

The confusion is complete!

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place?

**Comment by mat007** [comment]
Well hold on, sorry, file sharing is kind of tied to Docker Desktop as well actually.
You need to tell us what version of Docker Desktop you’re running and also if possible upload diagnostics (Troubleshot menu from the systray menu).

**Comment by Hamsterman** [comment]
I am running: DockerDesktop 2.2.0.4
Diagnostics ID: 8EE5C91D-2005-41AC-8260-F66F5D875017/20200320080802

**Comment by djs55** [comment]
@Hamsterman thanks for your report. If you have a moment could you describe your use-case a little? We focus our testing on the "standard" way for file sharing rather than NFS or CIFS.

I suspect the reason NFS isn't working is because in
```
docker volume create --driver local --opt type=nfs4 --opt o=addr=127.0.0.1
```
The `127.0.0.1` is unfortunately the localhost inside the helper Linux VM, not the Windows `127.0.0.1`. Could you try replacing this with `host.docker.internal` (which resolves to an internal IP which can be used to contact the host)

I don't believe this syntax is supported: `docker run -it -v //127.0.0.1/DockerShare`. I think your initial attempt with `docker volume create` is the right approach, if you really want to use NFS/CIFS.

**Comment by Hamsterman** [comment]
First of all I have no favorite protocol I would like to use at this point in time. I just wanna see just one work. I have tried with the nfs4 as you can see below.

If I use host.docker.internal
docker volume create --driver local --opt type=nfs4 --opt o=addr=host.docker.internal,hard,nolock,rw --opt device=:/DockerShare bar
docker run -it -v bar:/server-dev alpine sh

C:\Program Files\Docker\docker.exe: Error response from daemon: error while mounting volume '/var/lib/docker/volumes/bar/_data': failed to mount local volume: mount :/DockerShare:/var/lib/docker/volumes/bar/_data, data: addr=host.docker.internal,hard,nolock: invalid argument.

And if I use the actual IP of the Windows host
docker volume create --driver local --opt type=nfs4 --opt o=addr=192.168.X.X,hard,nolock,rw --opt device=:/DockerShare bar
C:\Program Files\Docker\docker.exe: Error response from daemon: error while mounting volume '/var/lib/docker/volumes/bar/_data': failed to mount local volume: mount :/DockerShare:/var/lib/docker/volumes/bar/_data, data: addr=192.168.5.33,hard,nolock: protocol not supported.

**Comment by Hamsterman** [comment]
*bump*

**Comment by Hamsterman** [comment]
bump again
