### ISSUE TITLE
Enabling WSL 2 support causes an error

### ISSUE THREAD

**Issue by swiatoslaw** [docker/for-win#6093]
- Diagnostics ID:  BE9AE752-C0F9-4C39-A6D5-66C99C34E557/20200321093400

### Expected behavior
Apply WSL 2 support without any errors

### Actual behavior
Applying WSL 2 support causes a crash

### Information
  - Windows Version: Windows 10 Pro 2004, OS build: 19041.153
  - Docker Desktop Version: 2.2.0.4 (43472) Stable
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No
  - (WSL has no installed distributions)
  - (Outdated WSL 2 kernel?)

### Steps to reproduce the behavior
1. Enable the experimental WSL 2 based engine
2. Click on Apply & Restart
3. Error occurs

**Comment by simonferquel** [comment]
For a limited period, enabling WSL2 requires an additional manual step: installing the Linux Kernel msi: https://aka.ms/wsl2kernel

**Comment by tyler36** [comment]
Docker: 2.3.0.2

Updated to Win10 Pro 2004 this morning and installed WSL 2.
Docker detected this and offered to change engine but Docker crashes. 

If I turn off "WSL 2 engine", it starts up. Turn on "WSL 2 engine" and crashes. 
Tried a reboot.
Tried updating to Docker 2.3.0.3.
