### ISSUE TITLE
DockerCli.exe -SwitchLinuxEngine doesn't return to PowerShell prompt

### ISSUE THREAD

**Issue by VeselovAndrey** [docker/for-win#6098]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 77669C7E-1661-4991-A238-7B74FCA2AA0B/20200322173128
Please see description below.

### Expected behavior
Switch to Linux Docker Engine.

### Actual behavior
Command 
PS> .\DockerCli.exe -SwitchLinuxEngine
doesn't return to PowerShell prompt. Only way to comis to press Ctrl+C.

> - Is it reproducible?
Yes

>  - Did the problem appear with an update?
Don't know. I didn't tried that before.

>  - Windows Version: 
Windows 10 Pro 1909 18363.720

>  - Docker Desktop Version:
Communoty 2.2.0.4 (43472)

### Steps to reproduce the behavior
1. Switch to Windows Engine (if current Engine is Linux)
2. Quit from Docker Desktop (and stop Docker)
3. Open PowerShell command line
4. Run .\DockerCli.exe -SwitchLinuxEngine
If at this time you will try to run "docker version"
```
 Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```
Important: It's never happens when I trying switch from Linux Engine to Windows Engine using
 .\DockerCli.exe -SwitchWindowsEngine

### Workaround 
1. After .\DockerCli.exe -SwitchLinuxEngine wait around 30 sec
2. Run Docker Desktop 
Sometimes it runs normally, sometimes closes immediately, sometimes produces an error (see uploaded diagnostics).

If it runs normally then click Ctrl+C in PowerShell to abort DockerCli command.

**Comment by mat007** [comment]
Thanks for the report, but `DockerCli` is an internal undocumented tool and we likely won’t do any extra work around it.
That being said `DockerCli` is a CLI wrapper to control the Docker Desktop application, therefore it makes sense for it to be running so that it works properly…

**Comment by VeselovAndrey** [comment]
@mat007 thanks for prompt response.

But is there any other way to have different docker configuration?

I will explain:
My initial goals is to keep Windows images on other drive (not in C:\ProgramData\Docker\). 
As result I need different configs for Windows and Linux engines. In Windows Docker config (daemon.json) I need following setting 
```
"data-root": "some path to some drive and folder"
```
But Linux Engine fails to start in this case (I need to switch sometime Engines as I'm a software developer).

But Docker Desktop allows to have only single file. So I wrote PSScript that updates config and switches Docker Engine. 

But maybe these is other way?

**Comment by VeselovAndrey** [comment]
BTW looks like it works if Docker Desktop running while switching.
