### ISSUE TITLE
Unable to build kernel module with kernel sources from linuxkit/kernel:4.19.76

### ISSUE THREAD

**Issue by etherai** [docker/for-win#6099]
### Expected behavior

Attempting to build kernel module results in a kernel module that cannot be inserted.

```
# modprobe wireguard
modprobe: can't load module wireguard (extra/wireguard.ko): invalid module format
```

Issue description here: https://github.com/linuxkit/linuxkit/issues/3402

In the above issue I found https://hub.docker.com/r/docker/for-desktop-kernel/tags?page=1&name=4.19.76

but it is not clear which container has the sources that match the kernel that is shipping with Docker for Windows. I tried a couple and still got the magic version mismatch error on attempting to load the module.

Thanks for the guidance!

### Actual behavior

It should be obvious which kernel headers I should be building against.

### Information

  - Windows Version: Windows 10
  - Docker Desktop Version: 2.2.0.4
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM No

**Comment by djs55** [comment]
Thanks for your report. It's not currently obvious which image corresponds to which version -- I'll have to think about where to put that information.

In kernel 2.2.0.4 the kernel is https://hub.docker.com/layers/docker/for-desktop-kernel/4.19.76-d665d2cbc4fe70f8ab08ba2cd82d052e41d2a704-amd64/images/sha256-c42bff3d5f285dcb1dde0937a8b99e2f51f1f764bd9b847c5d188fd02bb74136?context=explore

To look inside and see the headers + source:
```
$ docker pull docker/for-desktop-kernel:4.19.76-d665d2cbc4fe70f8ab08ba2cd82d052e41d2a704-amd64
$ docker create --name linux docker/for-desktop-kernel:4.19.76-d665d2cbc4fe70f8ab08ba2cd82d052e41d2a704-amd64 /bin/sh
$ docker cp linux:/ .
$ ls
System.map		intel-ucode-license.txt	kernel-dev.tar		kernel.tar		sys
dev			intel-ucode.cpio	kernel-headers.tar	linux.tar.xz		wireguard.tar.xz
etc			kernel			kernel-source-info	proc
```

That should be enough to completely recompile the kernel. To make a loadable module I'm not 100% sure as there may be an interaction with the RANDSTRUCT stuff -- let me know how you get on and if there is more info needed.

In future we'd like to use a linuxkit 5.4 kernel directly -- this 4.19 has a couple of backports: mostly FUSE bugfixes plus the `virtio-blk` `DISCARD` implementation.

**Comment by etherai** [comment]
Thank you, @djs55! With that kernel image I was able to successfully build a working kernel module.

**Comment by djs55** [comment]
@etherai thanks for the confirmation, and sorry for the hassle!
