### ISSUE TITLE
Docker fails trying at each system start to update from 5971 to 6563

### ISSUE THREAD

**Issue by staeppvargen** [docker/for-win#61]
### Expected behavior
1) System starts up. Docker shows "whish to updatefrom 5971 to 6563"-layer => confirm
2) Docker downloads new files and asks for admin rights to install => password & confirm
3) Docker is up and running in the new version

### Actual behavior
1) and 2) like above
3) Docker is dying silently in the background
4) At next system- or  manual docker start it asks again if it should update (from 5971 to 6563)

### Information
1) Win Version: Win10 Pro, Version 1607, Build 14393.103

2) Involved upgrades according to layer info:
- Docker 1.12.1 
- Docker machine 0.8.1 
- Linux kernel 4.4.19 
- aufs 20160822
For more details see 
[docker_log.txt](https://github.com/docker/for-win/files/440641/docker_log.txt)

3) Fehler-Anzeige aus dem Event-Log
[docker_error_events.txt](https://github.com/docker/for-win/files/440640/docker_error_events.txt)

THANKS FOR YOUR EFFORTS! :)

**Comment by friism** [comment]
Thanks for reporting, and sorry about the breakage. Beta21 had a [bug that means that later auto-updates cannot be applied](https://docs.docker.com/docker-for-windows/release-notes/#/beta-23-release-2016-08-16-1-12-1-rc1-beta23).

Please download and run the installer directly: https://download.docker.com/win/beta/InstallDocker.msi

**Comment by staeppvargen** [comment]
Thanks, that worked!
