### ISSUE TITLE
WSL 2: cannot build an image with a dockerfile in wsl filesystem

### ISSUE THREAD

**Issue by anisg** [docker/for-win#6101]
### Expected behavior

build a docker image with a dockerfile in the wsl filesystem should work (right?)

### Actual behavior

when building in the wsl filesystem, doing `docker build .`, docker won't respond.

when using docker-compose, I got the following error:
```
TypeError: You must specify a directory to build in path
[8412] Failed to execute script docker-compose
```

### Information
  - Windows Version:  **Windows 10 Home - 0.0.19041 Build 19041**
  - Docker Desktop Version: **2.2.2.0 (43066)  -- edge**
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: **No**

### Steps to reproduce the behavior

1.  create a file named 'Dockerfile' in both WSL filesystem and Windows filesystem
```yml
# file 'Dockerfile'
FROM node:12.3
```
2. build the image with `docker build .`

**Comment by simonferquel** [comment]
Have you converted your distro to WSL 2 ?
Can you send a diagnostic report ?

**Comment by anisg** [comment]
Ok I was still on WSL 1 😃

switching to WSL 2 fixed the issue for me. Thank you.

**Comment by simonferquel** [comment]
Closing then, thanks!
