### ISSUE TITLE
Do not see the Kebernetes settings on the Settings menu

### ISSUE THREAD

**Issue by newstrider** [docker/for-win#6114]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 196B433B-50F0-4CA5-BFE3-07D45CA4432A/20200324201411

### Expected behavior
See Kubernetes section on Settings
### Actual behavior
Kubernet section does not appear on Settings

### Information

  - Windows Version: Windows 10
  - Docker Desktop Version: Stable 2.2.0.4 (43472) - with the Kubernetes: v1.15.5
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

**Comment by newstrider** [comment]
![image](https://user-images.githubusercontent.com/11384034/77473724-3fe67a00-6dec-11ea-8037-90a0886e5d8c.png)
just for reference

**Comment by mat007** [comment]
You’re in Windows containers mode, you need to switch to Linux containers for Kubernetes.
