### ISSUE TITLE
Edge 2.2.2.0 file sharing not persisting through restarts

### ISSUE THREAD

**Issue by arseniybanayev** [docker/for-win#6116]
Reproduce:
1. Add a directory to the file sharing screen, click "Apply & Restart"
2. Run any container with a volume and verify **sharing works**
3. Restart Docker Desktop
4. Run the container in #2 again and **sharing doesn't work**
5. Remove the directory added in #1, click "Apply & Restart"
6. Add the directory removed in #5, click "Apply & Restart"
7. Run the container in #4 again and **sharing works**

**Comment by mat007** [comment]
Thanks for the report, I can confirm I am able to reproduce it on Edge 2.2.2.0.
This has actually been fixed in the meanwhile in our master branch and should be available in the next Edge in about a week time, sorry for the inconvenience!

**Comment by arseniybanayev** [comment]
Thanks! Yeah, seemed like an easy one :)
