### ISSUE TITLE
No answer from VM - Log: 458B111D-E8FA-4BDD-8459-60AA76959F16/20200325161451

### ISSUE THREAD

**Issue by JoshHubanks** [docker/for-win#6118]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: **458B111D-E8FA-4BDD-8459-60AA76959F16/20200325161451**

### Expected behavior
- Docker should start, even after I reset factory defaults.
### Actual behavior
![image](https://user-images.githubusercontent.com/5112600/77561347-f736cb80-6e94-11ea-850a-2783995ced22.png)

### Information

  - Windows Version: **Windows 10 Enterprise 10.0.18363**
  - Docker Desktop Version: **2.2.0.4 (43472)**
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: **No**
  - Did the problem appear with an update? **Yes, after the most recent upgrade**

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by michaelsanford** [comment]
Seems like my issue as well, only Docker does starts and I can build images and compose containers, but _dies a few minutes later_ with the above message.

I also attempted starting Docker Desktop as Admin, after ```Restart-Services *docker*``` in an Administrative Powershell.

My Diagnostics ID:
```
C8FEC65B-C3FD-42FA-B425-16A22A9B3F82/20200327155110
```
