### ISSUE TITLE
Example Voting App does not build

### ISSUE THREAD

**Issue by roybooth** [docker/for-win#6121]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Example Voting Application builds

### Actual behavior

gunicorn fails to build due to wrong Python version

### Information

Happens every time I run command docker-compose up build

Windows cmd shell output : 

Digest: sha256:a9d3631c5062a6759362dafae7192041f6c10d83a9632daaab02024ccdae906d
Status: Downloaded newer image for python:2.7-alpine
 ---> 037e005d160a
Step 2/7 : WORKDIR /app
 ---> Running in ede6879fb612
Removing intermediate container ede6879fb612
 ---> da7ff38fe0be
Step 3/7 : ADD requirements.txt /app/requirements.txt
 ---> ee7218f8b456
Step 4/7 : RUN pip install -r requirements.txt
 ---> Running in a692c0566ff4
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting Flask
  Downloading Flask-1.1.1-py2.py3-none-any.whl (94 kB)
Collecting Redis
  Downloading redis-3.4.1-py2.py3-none-any.whl (71 kB)
Collecting gunicorn
  Downloading gunicorn-20.0.4-py2.py3-none-any.whl (77 kB)
ERROR: Package 'gunicorn' requires a different Python: 2.7.17 not in '>=3.4'
ERROR: Service 'vote' failed to build: The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1

===========================================================

Windows 10 pro
Docker 19.03.8, build afacb8b
running on native intel i7 hardware

### Steps to reproduce the behavior

  1. follow instructions on https://docs.docker.com/docker-for-windows/dashboard/ 
  2. at step https://docs.docker.com/docker-for-windows/dashboard/#explore-running-containers-and-applications

  3. follow link to the Example voting app, take you to git, select clone or download, 
  4. select download zip, extract to a folder on local disk
  5. To start the application, navigate to the directory containing the example voting application in the CLI and run docker-compose up --build.

Console output for build shown above.

**Comment by mat007** [comment]
I believe this should be open on https://github.com/dockersamples/example-voting-app but unfortunately I can’t transfer the issue as that repository is in a different org.
Would you mind re-opening it there?
Thanks!
