### ISSUE TITLE
Disable WSL2 backend when WSL2 is not running

### ISSUE THREAD

**Issue by nphmuller** [docker/for-win#6122]
I've ran into an issue with WSL2 not working (not Docker related), so I wanted to switch Docker back to a full VM temporarily. The problem I'm running into is that Docker won't start, because I have the WSL2 backend enabled. So the settings windows is stuck at `starting` and I can't uncheck the `Enable the experimental WSL 2 based engine` option.

I'm on version `2.2.0.4 (43472)` stable.

**Comment by simonferquel** [comment]
Hmm, that is an interesting UI case. We'll try to find a good way to provide an UI to handle that.
In the meantime, you can edit your setting file at `C:\Users\<username>\AppData\Roaming\Docker\settings.json` and set `wslEngineEnabled` to false.

**Comment by nphmuller** [comment]
Thanks for the fast response! That is exactly what I was looking for.

For now I found another workaround: Disable WSL via `Turn Windows features on or off`. When Docker starts you receive a popup that WSL should be enabled and Docker Desktop is able to fall back to full VM mode.
