### ISSUE TITLE
No matching manifest for windows/amd64 10.0.17134 in the manifest list entries

### ISSUE THREAD

**Issue by dA505819** [docker/for-win#6128]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
It should have build fastai.

### Actual behavior
```$ docker build -t fastai-v3 .```

Sending build context to Docker daemon  181.5MB
Step 1/8 : FROM python:3.7-slim-stretch
3.7-slim-stretch: Pulling from library/python
no matching manifest for windows/amd64 10.0.17134 in the manifest list entries

### Information

  - Windows Version: Windows 10 pro
  - Docker Desktop Version: 2.2.0.4
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mat007** [comment]
You’re probably in Windows container mode but needs Linux containers for that:

![image](https://user-images.githubusercontent.com/2386884/77655977-82868e80-6f73-11ea-8378-d5e403e8d842.png)

**Comment by dA505819** [comment]
I have tried it but it shows "Windows version not compatible".

**Comment by dA505819** [comment]
@mat007 Thankyou! The error solved.
