### ISSUE TITLE
Dashboard showing "too many" containers

### ISSUE THREAD

**Issue by gthvidsten** [docker/for-win#6129]
This is not actually a bug, but a request for updated documentation about the Dashboard, which currently is bit weak on how containers are displayed.

Whenever I do `docker run` a new entry appears in the Dashboard, even if it is the same image being run. If I do this many times the Dashboard will end up showing many non-running containers.

If I do `docker container ls` or `docker ps` it gives an empty list, which conflicts with the Dashboard that has a list of many non-running containers.

This may be by design, of course, but for me, as a novice, it is highly confusing.
I don't know how it is supposed to work, or how I should interpret the Dashboard with many non-running containers, even when they all point to the same image.
Had there been a better description in the Dashboard documentation this could probably be explained so that novices like me don't end up as confused.
Maybe it would help if the Dashboard had a "refresh" button? Maybe it should have a "clear all non-running" button?

In any case, clarifying this could be a good idea.

**Version:** 2.2.0.4 (43472) stable

**Comment by mat007** [comment]
Thanks for the report, that’s a good point you’re bringing up.
The Dashboard actually lists stopped containers, which `docker ps` doesn’t do by default as it needs a `-a` to show them.
Stopped containers can be restarted (`docker start …`) which the Dashboard can do as well.

**Comment by stephen-turner** [comment]
It's possible (and normal) to create several containers from one image. You can clear up old, unwanted ones using `docker rm`. Or if you start them with `docker run --rm`, they will delete themselves when they are stopped.
