### ISSUE TITLE
Error response from daemon: Cannot start container 729d72186506926089721f30de1fe43b5f69bc5097db08d516ae945f5ebe832f: &Error=Error=Your installation does not contain a license key file. Please verify that key.txt is in the Windocks directory and contains a valid license key. Please contact support@windocks.com

### ISSUE THREAD

**Issue by rayhsu02** [docker/for-win#6131]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jzabroski** [comment]
lol...
