### ISSUE TITLE
External HDDs not showing up in File Sharing Section

### ISSUE THREAD

**Issue by RejectKid** [docker/for-win#6132]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
External HDDs to show up in the Resources > File Sharing
### Actual behavior
I only see my internal C: drive
### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

This use to have externals on previous versions

Win 10 Pro
2.2.0.4 docker for windows
no
### Steps to reproduce the behavior

Plug in external HDD, go to relevant settings.  

Possibly something I need to setup?  Ive seen other screenshots on here of people with (what i presume are external) drives other than C on their settings.

**Comment by mat007** [comment]
Thanks for your report, we believe this is actually fixed on Edge, would you care to try it out?
https://download.docker.com/win/edge/Docker%20Desktop%20Installer.exe

**Comment by mat007** [comment]
Actually your version if you quit and re-launch Docker Desktop it should show your drive.

**Comment by RejectKid** [comment]
> Actually your version if you quit and re-launch Docker Desktop it should show your drive.

well then.... i hit restart docker plenty of times, but never did that. that worked.  thanks!
