### ISSUE TITLE
I'm attempting to run Docker Desktop that was installed on a AWS EC2 Windows instance. Has anyone else had a issue with this?

### ISSUE THREAD

**Issue by revivedtitan** [docker/for-win#6135]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
In general, Docker Desktop is not supported on VMs. It may work, it may not, depending on the underlying virtualisation technology, which we have no control over.
