### ISSUE TITLE
getting an error response from daemon about lincence key file 

### ISSUE THREAD

**Issue by singhAvneet** [docker/for-win#6142]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 3D95BEFD-C688-4573-80EE-A797A24046DB/20200327204026

### Expected behavior
when I am trying to execute command "docker run hello-world"
expect docker to run hello world container
### Actual behavior
I am getting this error.
WARNING: Error loading config file:Invalid auth configuration file
Error response from daemon: Cannot start container 9df67ee89942c8f1206a99054937a8ce9144e11f3f4a09664b7972f108002c78: &Error=Error=Your installation does not contain a license key file. Please verify that key.txt is in the Windocks directory and contains a valid license key. Please contact support@windocks.com.
### Information

  - Windows Version: 10 (1909)
  - Docker Desktop Version: 2.2.0.4(43472)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
    No I am not running windows vitalization

**Comment by singhAvneet** [comment]
this is the same error was opened and closed #6131

**Comment by mat007** [comment]
My guess would be you have the wrong `docker.exe` in the path first, apparently Windocks provides one and they seem to have added their own license check inside…

**Comment by jzabroski** [comment]
I ran into this issue today.  I am on Docker Desktop Community 2.3.0.3 (45519) Stable Channel.

Has anyone found a better tool than Docker Desktop?  The UI is IMHO not very good/intuitive and doesn't seem to provide many features.  For example, I don't use this tool often, and I can never remember how to search the docker hub for images.

![image](https://user-images.githubusercontent.com/447485/86782377-fa615c00-c02c-11ea-8932-1e6a270abbae.png)

**Comment by jzabroski** [comment]
1. What is the Windocks directory?  ~/.windocks doesnt exist.
2. What configuration file is it searching for?  When I search this repository for support@windocks.com, I only found these issues, so where is this error message coming from?  I can't even search the code to figure it out, which sort of defeats the purpose of using open source software - I can't even submit a patch for a better error message since I can't even find the error message in the first place :(
