### ISSUE TITLE
Docker fails to start with error failed to check wsl-bootstrap version: exit code: 1

### ISSUE THREAD

**Issue by hax0kartik** [docker/for-win#6151]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A9BBAC5D-DBAB-4C90-A717-74001DB3E36B/20200328143955

### Expected behavior
 Docker starts
### Actual behavior
Docker does not start with the error `Docker.Core.Backend.BackendException:
Failed to check wsl-bootstrap version: exit code: 1
 stdout(utf8): 
 stdout(unicode): 
  stderr (utf8): Error: reading version file: open /docker-desktop-deploy-version: no such file or directory
2020/03/28 14:36:20 open /docker-desktop-deploy-version: no such file or directory
reading version file`
### Information

  - Windows Version: windows 10 home, 19041.153
  - Docker Desktop Version: 2.2.2.0 (43066)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Try starting docker desktop

**Comment by NickGraham101** [comment]
I'm encountering the same issue.  The problem started after I applied the latest Windows update (KB4550936).

Windows Version: windows 10 pro, 19041
Docker Desktop Version: 2.2.0.5 (43884)
Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No
Diagnostics ID: B72392B9-C768-46C2-BFEF-6CDE028E24EB/20200416070750

Are there any updates or workarounds?

**Comment by hax0kartik** [comment]
I fixed this by resting docker to factory defaults
