### ISSUE TITLE
Docker Desktop fails to start with timeout

### ISSUE THREAD

**Issue by gabrielgrant** [docker/for-win#6159]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 5862756A-180D-4967-AADA-407ED45BECB6/20200329152638

### Expected behavior

Windows boots, and docker starts within seconds. This is what happened with previous versions.

### Actual behavior

Docker hangs for several minutes after Windows boots, then eventually pops up an error window after the attempt to start times out.

### Information

This now seems to happen every time I boot. 

This is a top-spec, 7th-gen X1 Carbon, so would be _very_ surprised if it's just "normal" slow booting. According to the Hyper-V Manager, the DockerDesktopVM does start (state changes to "Running" after starting docker desktop, status is briefly "Starting - Succeeded", then is blank)

<details><summary>Full logs</summary>

```
Docker.Core.Backend.BackendDestroyException:
Timed out waiting for the lifecycle-server to start.
This may be the result of a slow environment or there may be a real problem.
This timeout can be increased by editing settings.json, value 'lifecycleTimeoutSeconds'.
This file is usually in C:\Users\(your username)\AppData\Roaming\Docker
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

  System.TimeoutException:
  Timed out waiting for the lifecycle-server to start.
This may be the result of a slow environment or there may be a real problem.
This timeout can be increased by editing settings.json, value 'lifecycleTimeoutSeconds'.
This file is usually in C:\Users\(your username)\AppData\Roaming\Docker
     at Docker.Backend.LifecycleClient.WaitForServerUp(TimeSpan pingTimeout)
     at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions, Credential credential)
     at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
  ```

</details>

  - Windows Version: Windows 10 Pro 1903, build 18362.720
  - Docker Desktop Version: 2.2.0.4 (43472)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No, Windows runs directly on the machine

<details><summary>Full version info</summary>

![image](https://user-images.githubusercontent.com/493968/77853780-d0c9a680-719a-11ea-9015-cf8ee87a1636.png)

</details>

### Steps to reproduce the behavior

  1. reboot windows

Error message is the same as in #4393 but that issue was closed with the resolution of just increasing the timeout. Tried 300 and 600 seconds, but still no luck. Is it really expected that Docker should now suddenly take longer than 10 minutes to boot on a top-of-the-line machine? If so, perhaps the default timeout should be increased...

**Comment by madallday** [comment]
I was having this problem. I uninstalled fully and re-installed. (Current version is 2.3.0.2 (45183) stable) and the problem seems to have been fixed.
Prior I had tried several times increasing the timeout and resetting to factory defaults but those did not work.  Of course, re-installing likely reset it to factory defaults anyway.
