### ISSUE TITLE
Docker for Windows won't start after installing PS 7

### ISSUE THREAD

**Issue by paschott** [docker/for-win#6166]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker for Windows starts as expected.

### Actual behavior
Unable to start due to missing modules:
Hyper-V
NetAdapter
NetTCPIP

### Information
  - Windows Version: 10 Professional v2004  build 19041.172
  - Docker Desktop Version: 2.2.0.4
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
  1. Install PS 7
  2. Set PS 7 as the default. (Might be in path ahead of old PowerShell 5.1)
  3. Attempt to start Docker Desktop. Get error about missing Hyper-V module.
  4. Copy Hyper-V module from "C:\Windows\System32\WindowsPowerShell\v1.0\Modules" to "C:\Program Files\WindowsPowerShell\Modules"
  5. Attempt to start Docker Desktop. Get error about missing NetAdapter module.
  6. Copy the NetAdapter module from old to new modules folder.
  7. Attempt to start Docker Desktop. Get error about missing NetTCPIP module.
  8. Copy the NetTCPIP module form old to new folder.

At this point, after manually copying the modules, I am able to start Docker. I don't necessarily want all old modules to be part of my PS Module Path for v7. That has caused other issues on my machine. Copying over those specific modules worked, though I'm wondering if there's a way to force a specific version of PowerShell or do something else on install to make sure the necessary modules show up in the module path.

There is a workaround, but it would be nice if there were a check/copy of those modules if they aren't present or a way to force Docker for Windows to use PS 5.1 when doing its work if those required modules aren't present in v7.

**Comment by mat007** [comment]
Thanks for the report.
In the next version (Edge this week, Stable in 2 or 3 weeks) we have dropped the Powershell scripts, which as you have witnessed first hand were causing a lot of problems.
This should fix this issue!
