### ISSUE TITLE
Kubernetes doesnt start after fresh reinstall - VpnKit gives argument errors

### ISSUE THREAD

**Issue by BrenPutzeys** [docker/for-win#6167]
[20200330062307.zip](https://github.com/docker/for-win/files/4401129/20200330062307.zip)

  - [x] I have tried with the latest version of my channel Stable: 2.2.0.4 edge: 2.2.2.0
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:D5A717EC-9E31-4301-92A0-25A5D9F0268A/20200330062307

### Expected behavior
When starting kubernetes from a fresh installed docker desktop it should start.

### Actual behavior
Kubernetes stays in status starting.
while log displays errors: 
[VpnKit            ][Error  ] vpnkit.exe: Starting to watch : EINVAL
[VpnKit            ][Error  ] vpnkit.exe: Failed to watch hosts file : invalid argument

[VpnKit            ][Error  ] vpnkit.exe: While watching /etc/resolv.conf: ENOENT
[VpnKit            ][Error  ] vpnkit.exe: Pipe.listen: caught (Failure "Failed to connect vmnet device")

[GoBackendProcess  ][Error  ] time="2020-03-28T07:13:02+01:00" msg="error accepting multiplexer data connection: EOF"

[GoBackendProcess  ][Error  ] time="2020-03-28T07:13:30+01:00" msg="wsl expose error:Post http://unix/forwards/expose/port: open \\\\.\\pipe\\dockerWsl2BootstrapExposePorts: The system cannot find the file specified."

### Information

It is reproducible as i tried uninstalling the entire docker for desktop and reinstalling it, it still stays the same.
Problem appeared on friday 27/03, not after an update.
This was on an older docker for desktop 
Suddenly kubernetes didnt want to start anymore.
I tried restarting docker desktop
reseting the kubernets cluster
reseting to factory defaults
uninstalling and reinstalling the newest docker for desktop 2.2.0.4

uninstalling removing folders that where not deleted and reinstalling (tried this several times while removing:
C:\Users\<User>\AppData\Roaming\Docker
C:\Users\<User>\AppData\Roaming\Docker Desktop
C:\Users\<User>\.kube
C:\Users\<User>\.docker

All followed by a full uninstall and reinstall

  - Windows Version: 1909
  - Docker Desktop Version: 2.2.0.4
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. Not sure how to reproduce it since i think it only affects this specific system for some reason, probably because i cant really clean uninstall it, to reinstall it

**Comment by rkarthi91** [comment]
I also have same problem please help attached log file
[log.txt](https://github.com/docker/for-win/files/4493209/log.txt)
