### ISSUE TITLE
Dashboard minor issues

### ISSUE THREAD

**Issue by alex-pravdin-springernature** [docker/for-win#6174]
This is my list of issues that I have when working with the Docker Desktop Dashboard. They are not critical but nice to fix:

1. Can not choose the shell executable when running a shell inside a container. By default it's `sh` but I prefer `bash`. An option in settings would be nice.
2. Console log scrolls to the end automatically. Really hard to read the output on previous pages, every 2 seconds the log scrolls to the end.
3. Can not update port mapping settings on an existing/running container. Sometimes I need to expose not exposed ports or change their settings.
4. Container group (deployed by docker-compose) always become collapsed when I leave the settings or console log of a container in the group. Very inconvenient when often switching between multiple containers in the group.

It would be nice to have these issues fixed.

A wish: Please make Dashboard the default action on double-clicking the system tray icon.

PS: Thanks for running the `cmd` console window when running a container shell. In our organization, PowerShell is blocked and I can't use Kitematic as a main development tool (it seems Kitematic's principled position is to use PS only). But I still have to use Kitematic with the Docker Dashboard because of the issues above.

**Comment by stephen-turner** [comment]
Thanks for all your feedback, @alex-pravdin-springernature. For 2., there is a checkbox at the bottom of the log window to toggle this behaviour.

**Comment by stephen-turner** [comment]
Assigning the rest to @stlucek.

**Comment by alex-pravdin-springernature** [comment]
@stephen-turner Thanks for pointing out to that switch! :) What if to change it's name to something like "Auto-scroll down"? The word "scroll" is well-known for every developer even with poor English skills. "Stick to bottom" was unclear to me what we actually sticking to the bottom. I always saw the term "stick" in relation to tool windows and various visual blocks. That's why I saw this switch a lot of times but didn't pay attention what it's actually for.

**Comment by stephen-turner** [comment]
Thanks for that insight, @alex-pravdin-springernature.
@stlucek Maybe "Always scroll to bottom" or something like that would be better.

**Comment by alex-pravdin-springernature** [comment]
@stephen-turner I checked this switch functionality and want to add few cents. It also doesn't work as I expected. When it turned off, the screen never scrolls. When it turned on, I can't see anything except the last page (always scrolls down no matter the current scrolling position). These are two opposite sides. But from my personal experience, I can say that the truth is in the middle and the most convenient behavior is when it scrolls down automatically only when it's already at the bottom. 

If a user scrolls even one line up it should stop automatic scroll down. The logic is simple - to follow the user's intentions. If a user doesn't touch the log window then it always shows the latest lines. If he or she intentionally scrolls up, then auto-scroll should be turned off to allow a user to read logs without interruptions. When the user scrolls down to the bottom by itself, it means he or she intentionally wants to see the latest lines again and auto-scroll should be turned on again.

**Comment by alex-pravdin-springernature** [comment]
Also, it would be nice to move running containers to the top of the list, exited to the bottom. In my current composition, I have a lot of exited containers left there after the `run` command. And running containers are somewhere in the middle of the list. But can be anywhere. If the list would contain 30 exited containers and 3 running, the process of searching for the running ones would be difficult.

**Comment by stephen-turner** [comment]
@stlucek Lots of good feedback here.
1) I think we should toggle the checkbox whenever the user scrolls. (And leave it off even if they manually scroll back to the bottom; they should manually check it on again if they want it).
2) I agree the running containers should be at the top, or maybe there should be sort options for different sorts.

**Comment by alex-pravdin-springernature** [comment]
@stlucek Thanks for your feedback. 
1. From my experience, I never wanted to leave the scroll position as is when scrolled to the bottom. I think if the switch will be toggled automatically of on user scroll, then it should be toggled automatically back. In this case, this switch will explicitly and visually represent current behavior. If it will be switched off and not turned back then it could be annoying to always click on the switch after each manual scroll.

**Comment by stephen-turner** [comment]
My reason for saying that the checkbox should not put itself back on automatically, is that I think it would be annoying if you scrolled up and down to try and find something, and when you happened to reach the bottom it would start jumping.

**Comment by alex-pravdin-springernature** [comment]
I see. You may investigate this case and check what users expect more often. I saw somewhere the behavior I described and found it very convenient. Probably, on some CI/CD tools log live outputs. Probably, Kitematic works the same.

Example use case that work for me:

Some web or api server log. It prints new lines constantly and I'm looking for some errors or deviations (expectation: scrolls automatically). I leave it working for some time and then go back and scroll manually to find something. If found - I stop scrolling and read the log, switch to other apps and back, copy some text from the log (expectation: don't scroll anywhere from the position I left it). Finished with the case and scroll down to check the live log with the latest lines (expectation: auto-scroll again).

Assumptions: 
- If we are at the bottom, most probably we want to see a live log. If scrolled somewhere we most probably want to see a static log.
- If a program switched something by itself, then it should switch it back by itself. If it doesn't switch back then it's better to not switch anything at all.

Suggestion:
- Rename the switch to something like "auto-stick to bottom" and in the on position work as I described above (auto-scroll at bottom, static if manually scrolled up). When it turned off, leave the current behavior.
