### ISSUE TITLE
Setting up Windows 2016 to use local registry

### ISSUE THREAD

**Issue by shaulm** [docker/for-win#618]
I am trying to setup an offline environment and I am unable to find where to set or change the settings so that Docker looks at a local registry. The JSON file that was referenced in one of the articles that I read does not exist in the folder. 
Another question, is it possible to set up a local registry on Windows?

Any help would be appreciated.

Thanks in advance

**Comment by alefesta** [comment]
I think this could help: https://github.com/docker/labs/tree/master/windows/registry

**Comment by friism** [comment]
The link @alefesta posted has relevant resources, closing.
