### ISSUE TITLE
Is there an install-from-zip file scheme for Docker Desktop on Windows 10?

### ISSUE THREAD

**Issue by jeffreyofisher** [docker/for-win#6182]
UAC won't allow it to be installed on my company-managed laptop; we are encouraged to look for install-from-zip capability in such cases to install for our user login's use.  

I see no mention of this capability in the documentation, nor FAQ, nor troubleshooting issues.

**Comment by stephen-turner** [comment]
No, because it's not just laying down files, it needs to start up some services etc.
