### ISSUE TITLE
Docker Desktop crashes switching to Windows containers

### ISSUE THREAD

**Issue by DaveHCL** [docker/for-win#6183]
- [ X] I have tried with the latest version of my channel (Stable or Edge) Stable 2.2.0.4
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID:
  0C9CBD75-EDE0-4E88-90E4-8F809E587812/20200331200002

### Expected behavior
Docker to allow Switch to Windows Containers without errors

### Actual behavior
Switching to Windows containers causes Docker to crash

### Information

  - Windows Version:Windows 10 Version 1909 OS Build 18363.720
  - Docker Desktop Version:2.2.0.4
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior
<!--
Install it 2.2.0.4 on Windows 10 with running the installer as Admin(This resolved an issue where install not as admin would cause Desktop to crash upon startup)
start Docker Desktop after installing without Windows container box checked. 
Once started, Switch to Windows containers and crash 

Uninstalled VirtualBox and removed left over files
Have VMware workstation pro installed
Used Revo uninstaller to remove Docker Desktop prior to above installed
Reset to Factory defaults does not resolve issue

[log.txt](https://github.com/docker/for-win/files/4411624/log.txt)

**Comment by kennethnavarro** [comment]
Im also experiencing this issue. can somebody help us?

**Comment by DaveHCL** [comment]
Still need help
going to try new version to see if it resolves the issue
