### ISSUE TITLE
Error getting nodes: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again

### ISSUE THREAD

**Issue by tawada2020** [docker/for-win#6185]
I'm having issues when testing my docker installation:

https://docs.docker.com/get-started/

The issue occurs when I run the command "docker run hello-world"

  - [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics

  - Diagnostics ID:

4CF23A8E-94E7-474C-8FEA-6477A9074596/20200331224351

### Expected behavior

I was expecting to receive the following message:

Hello from Docker!
    This message shows that your installation appears to be working correctly.

### Actual behavior

I'm receiving the following error:

C:\Program Files\Docker\Docker>docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
8e709836e4dc: Pull complete
543ff0f9573f: Pull complete
f01167dd6121: Pull complete
Digest: sha256:f9dfddf63636d84ef479d645ab5885156ae030f611a56f3a7ac7f2fdd86d7e4e
Status: Downloaded newer image for hello-world:latest
docker: Error response from daemon: hcsshim::OpenComputeSystem a43dc72f0b3b9b7a5769c4aa53ca3440e2b34342b2afc888ba456259ad62b6b6: context deadline exceeded.

### Information
 Just follow the steps from this link: https://docs.docker.com/get-started/
  - Windows Version: Windows 10 Enterprise version 10.0.17763 Build 17763
  - Docker Desktop Version: 2.2.0.4(43472)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
<!-- I'm just following  the steps from this link: https://docs.docker.com/get-started/

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place?

**Comment by mat007** [comment]
Or if it wasn’t intentional for you to run Windows containers you can switch to Linux containers:

![image](https://user-images.githubusercontent.com/2386884/78102232-21830e80-73ea-11ea-9a3e-fe566aac25de.png)
