### ISSUE TITLE
can not stop compose projects on dashboard

### ISSUE THREAD

**Issue by Diluka** [docker/for-win#6187]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 47A10DD9-CCC7-4F86-A58C-3E1C80017E2E/20200401011031

### Information

  - Windows Version: 1909
  - Docker Desktop Version: 2.2.0.4
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. can not control(start, stop, remove) compose projects
  2. can control each container in compose projects

**Comment by stephen-turner** [comment]
@stlucek More dashboard feedback

**Comment by Diluka** [comment]
I see. Today it is working fine.
