### ISSUE TITLE
Unable to write to the database. Exit code: 1

### ISSUE THREAD

**Issue by hvdlazari** [docker/for-win#619]
I just installed Docker for Windows v17.03 and got the following error message:

_**Unable to write to the database. Exit code: 1
   em Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   em Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   em Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   em Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)**_

My log is:

Version: 17.03.1-ce-win5 (10743)
Channel: stable
Sha1: b18e2a50ccf296bcd637b330c0ca9faaab9d790c
Started on: 2017/04/05 08:20:09.897
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1607
Build: 14393
BuildLabName: 14393.953.amd64fre.rs1_release_inmarket.170303-1614
File: C:\Users\hcunha\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 

...

[08:20:29.851][DataKit        ][Error  ] Process died
[08:20:31.101][Database       ][Error  ] 2017/04/05 08:20:29 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/04/05 08:20:29 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/04/05 08:20:30 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/04/05 08:20:30 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/04/05 08:20:30 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/04/05 08:20:30 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/04/05 08:20:30 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/04/05 08:20:30 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/04/05 08:20:30 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/04/05 08:20:30 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/04/05 08:20:30 Failed to contact the database on \\.\pipe\dockerDataBase: open \\.\pipe\dockerDataBase: O sistema nÃ£o pode encontrar o arquivo especificado.

[08:20:31.102][Database       ][Error  ] Unable to modify database: Unable to write to the database. Exit code: 1. Let's retry in 1s

...

Diagnostic ID 9129BCA6-8F52-4344-B7A2-6C19FB88E642/2017-04-05_08-21-23

Please help me.

**Comment by git22ura** [comment]
+1

**Comment by gmomm** [comment]
+1 Exactly the same here.

**Comment by gmomm** [comment]
Found out that I had a conflict with the OpenText socks client that I have installed, once I uninstalled the docker worked. Still don't know how to enable both to work together or why they were conflicting (sure in the network layer).

**Comment by friism** [comment]
@gmomm interesting - please post back if you find out more.

**Comment by hlums** [comment]
Any update on this? I'm installing Docker on Windows 10 and ran into the same issue.

**Comment by gmomm** [comment]
What I learned is that there was network conflict with a product (open text
socks) that I had installed, could be the same for you, this conflict was
blocking (I was unable to get deeper into it) the network communication
required by the shared pipe ...So I uninstalled it and used an alternative
socks solution

Em Qua, 9 de ago de 2017 12:31, Hong Lu <notifications@github.com> escreveu:

**Comment by hlums** [comment]
@gmomm Thanks for the lightning response! I actually don't have open text socks installed. Maybe it's some other products. How did you know it was open text socks?

**Comment by gmomm** [comment]
I looked for any applications that have relation with network and are not
part of the basic installation of windows,
 I uninstalled , restarted Windows , and Presto it's working

Em Qua, 9 de ago de 2017 15:24, Hong Lu <notifications@github.com> escreveu:

**Comment by iceweird** [comment]
Hi there, i'm also having the same problem, i'm runing windows 10 professional

**Comment by iceweird** [comment]
i've installed the last Edge version and the same error pops up

Unable to write to the database. Exit code: 1
   em Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings) em C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 246
   em Docker.Backend.ContainerEngine.Linux.Restart(Settings settings) em C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 182
   em Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) em C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   em Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) em C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

report ID: 5136A7F1-3053-436D-8C41-87318833CDD7/2017-08-14_17-17-28

@friism or @jasonbivins any thoughts on this ?

**Comment by iceweird** [comment]
Hi, this solved for me , uninstalling Web companion.
https://github.com/docker/for-win/issues/821

**Comment by YohanAlard** [comment]
Hi, solved for me too (uninstall my VPN Astrill tools) and problem is gone.

**Comment by ramilS** [comment]
same problem Docker version 17.06.2-ce, build cec0b72

**Comment by Sumanta1985** [comment]
Same problem. Can anybody help with some clue? I tried all different steps mentioned in this forum. Even tried to add a VM in Hyper-V
![image](https://user-images.githubusercontent.com/33609821/32704801-52fbf248-c7d9-11e7-9d62-488199fe92af.png)

**Comment by rn** [comment]
both the latest stable and edge version don's use the database anymore. Please retry with the latest versions.
