### ISSUE TITLE
docker run image not working in windows 10 Docker for Desktop v2.2.0.4

### ISSUE THREAD

**Issue by payal-sharma-1606** [docker/for-win#6190]
Error 1: 
driver error deleting endpoint friendly_bell : hns failed with error : The endpoint was not found. 
Error 2:
Failed to load container mount 0b0244c0e81684934d02fbd340c462d37a3a8e78db4eaab444d1733b0c397388: mount does not exist

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place?
