### ISSUE TITLE
Pulling images impossible: Unexpected EOF

### ISSUE THREAD

**Issue by gingters** [docker/for-win#6192]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: FDE7E224-A933-4E0F-94F5-5BA825FF2155/20200401125255

### Expected behavior

`docker run hello-world` should run.

### Actual behavior

Docker fails at pulling the image with an `unexpected EOF` error:
 
```
PS C:\Dev> docker run hello-world
Unable to find image 'hello-world:latest' locally
C:\Program Files\Docker\Docker\resources\bin\docker.exe: Error response from daemon: Get https://registry-1.docker.io/v2
/library/hello-world/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fhello-world%3Apull&
service=registry.docker.io: unexpected EOF.
```

This does also happen when downloading from other registries:
```
PS C:\Dev> docker pull mcr.microsoft.com/mssql/server:2019-latest
Error response from daemon: Get https://mcr.microsoft.com/v2/mssql/server/manifests/2019-latest: unexpected EOF
```

### Information

  - Is it reproducible? Yes.
  - Is the problem new? Yes.
  - Did the problem appear with an update? Probably. I could pull images bevor. But I can't tell when this was introduced.
  - Windows Version: 1909 Build 18363.752
  - Docker Desktop Version: 2.2.0.4 (43472)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Additional Info:

I already tried:
 * uninstalling Docker Desktop & reinstalling
   * Both Edge as well as Stable
 * Reset to factory defaults
 * Login with my dockerhub credentials
 * logout again

There are different unexpected EOF issues on the community and here, but no answers:
* https://forums.docker.com/t/unexpected-eof-on-auth-docker-io-when-trying-to-pull-from-docker-hub/90652
* https://github.com/docker/for-win/issues/5868
* https://github.com/moby/moby/issues/40578

This is a complete showstopper, as reinstalling and factory reset of course cleared *all* images, and now I can't run anything on docker anymore.

**Comment by gingters** [comment]
Update:

I went back and installed several older Docker versions:
* This also happens with 2.2.0.3.
* Sadly 2.2.0.0 isn't available as a download from the Release Notes page.
* The Edge build 2.1.7.0 (the 2.2 RC ?) also has this issue.
* The Edge build 2.1.5.0 (new Filesharing Impl) also has this issue.
* 2.1.0.2 also.

I didn't go back further than that. I am pretty sure that it still worked with one of these previous versions, so my _guess_ would be that the latest Windows update 18363.752 from March the 24th changed something that docker can't cope with.

**Comment by gingters** [comment]
Update: I went back several versions of Docker Desktop, but that did not resolve the problem.
I also uninstalled KB4541335 and KB4551762 as these were the latest bigger Windows Updates to check if that changed something, but it didn't.

**Comment by gingters** [comment]
Update: I did a complete **fresh install of Windows 10** (1909 18363.720) and a **fresh install of Docker** (2.2.0.5 (43884).

I also did a new diagnostic from the new installation: 4FCFC13E-A452-4269-8906-1C0E7B94F04F/20200402173141

Seriously: I need support here. This is a **complete blocker**. A fresh install of both Windows and Docker, and it can't download any image at all. This is absolutely unusable in this state.

I am a developer and I am willing to support you in diagnosing this issue as much as possible, so please get in contact.

**Comment by gingters** [comment]
Update: Someone mentioned to me that it could be an issue with some network chips freaking out on a gigabit connection. Tried another throttled network too: Same issue.

**Comment by SR-Lut3t1um** [comment]
Same issue for me!

**Comment by McGregsen** [comment]
We are also seeing this issue on multiple windows clients in our network. There is no proxy or anything like that in use.

I think the issue started appearing about 1,5 weeks ago. Not sure about the exact timeframe but I am fairly certain it was still working 2 weeks ago. And as far as I could tell there was no update to docker4win when the issue started appearing (There was a recent update a few days ago but that didn't change the behaviour).
So I am actually leaning towards a windows update issue maybe? Although we also already tried removing various recent windows updates without any success.

**Comment by twsI** [comment]
I am facing this issue as well. checked both latest stable and edge channel. Tried several reinstalls.
```
PS C:\Users\User> docker --version
Docker version 19.03.8, build afacb8b

PS C:\Users\User> docker info
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., v0.3.1-tp-docker)
  mutagen: Synchronize files with Docker Desktop (Docker Inc., testing)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 9.736GiB
 Name: docker-desktop
 ID: 7KGG:PIJ2:5JBI:5ZCR:KIML:AP7A:P64S:E65L:6DEY:DV2K:2VUB:V5H5
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 39
  Goroutines: 50
  System Time: 2020-04-23T11:17:46.490945716Z
  EventsListeners: 3
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by TSK-Dev** [comment]
Same issue for me. 
Restarting machine, Reinstall Docker für windows, set to docker desktop "Switch to windows containers" an back to linux containers.
Nothing works for me.

**Comment by twsl** [comment]
Still the same behaviour with 

* Docker Desktop Version: 2.3.0.1 (44875)

**Comment by medokin** [comment]
Having this issue for some weeks now, nothing helped, completely reinstalled Windows, issue is still there:

**Diag**: C5936D36-F1F8-4856-BECC-0FBD5B1A1B13/20200515174356
**Docker Desktop Version**: 2.3.0.2 (45183)
**Windows 10** (2004)


Pulling from official docker and microsoft does not work. Pulling from google is very instable, but works sometimes.
```
PS C:\Users\Niko> docker pull postgres
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/library/postgres/manifests/latest: Get https://auth.docker.io/token?account=medokin&scope=repository%3Alibrary%2Fpostgres%3Apull&service=registry.docker.io: unexpected EOF

PS C:\Users\Niko> docker pull mcr.microsoft.com/mssql/server:2019-latest
Error response from daemon: Get https://mcr.microsoft.com/v2/mssql/server/manifests/2019-latest: unexpected EOF

PS C:\Users\Niko> docker pull gcr.io/google_containers/cadvisor
Using default tag: latest
latest: Pulling from google_containers/cadvisor
9d48c3bd43c5: Pull complete
f7d6cbe0ad90: Pull complete
15f5311b080f: Pull complete
Digest: sha256:46d4d730ef886aaece9e0a65a912564cab0303cf88718d82b3df84d3add6885c
Status: Downloaded newer image for gcr.io/google_containers/cadvisor:latest
gcr.io/google_containers/cadvisor:latest
```

**Comment by gingters** [comment]
@medokin @twsl @TSK-Dev 
From your profiles I see you are from Germany, too. Could be important ;)
@McGregsen I can't tell that from your profile, but I take a wild guess:

I figured out the problem lies with my router.
I have an AVM Fritz!Box Cable modem (and a Vodafone / ex Kabel BW line). If you too have an AVM router, read further:

With the latest Fritz!OS firmware it seems there is an issue with the Hardware Packet Acceleration.
One workaround for me is to disable that setting temporarily, the other one was using a VPN service.

See also this post for detailed instructions on how to disable hardware packet acceleration:
https://github.com/docker/for-mac/issues/3493#issuecomment-616338458

**Comment by twsl** [comment]
@gingters I already found the thread. Thanks for sharing the solution tho. It's still weird, that it works with windows containers and not linux.

**Comment by medokin** [comment]
@gingters You are right, I have a brand new 6591.... It works now.

**Comment by rGunti** [comment]
Can also confirm. Fritz!Box 6660 Cable (unbranded) with Vodafone 1Gbps plan.
Disabling hardware acceleration works but slows down your internet speed to max 150 Mbps.
I can get around the issue by using a VPN connection but that's not a solution.

**Comment by McGregsen** [comment]
@gingters 
Thanks for the update. You are correct I am from Germany as well.
With your information we were able to implement a fix/workaround that works for us until an updated firmware for the box can be provided.

**Comment by TSK-Dev** [comment]
Thanks to you, @gingters.
Same for me:  Germany, Provider Vodafon. 
The problem started when I booked the new tarif "Vodafon Cable Max 1000" and get a new Fritz Box 6490.  If I deactivate "Hardwarebeschleunigung", docker runs stable. 
I guess, some problems with Playstation Internet connection are also caused by this problem.
What surprises me very much is that this problem does not always occur, when hardware acceleration is disabled. It occours mainly in the evenings and on weekends. Is there any filter causing problems that is only set at certain times when there is a lot of traffic?

**Comment by vietd24** [comment]
I can confirm with a Fritzbox Cable 6660 Unitymedia Region (now Vodafone) that pulling docker images are working as expected when disabling hardware acceleration in the support menu.

**Comment by vietd24** [comment]
FYI: Using the new 7.19 BETA firmware on my Fritzbox 6660 seems to have fixed the problem.

**Comment by lpfann** [comment]
> 
> 
> FYI: Using the new 7.19 BETA firmware on my Fritzbox 6660 seems to have fixed the problem.

Not for me.
Still unexpected EOF when pulling images with packet acceleration.

**Comment by cybertschunk** [comment]
Same problem here, docker is currently unusable

**Comment by paulkre** [comment]
Same problem here! I work for an organization with a lot of employees. I can't just make changes to our router's configuration that will affect itsnetwork speed.

**Comment by lauff** [comment]
Same problem for me with a FRITZ!Box 6591 Cable FRITZ!OS 07.13

**Comment by mbaniasad** [comment]
so just to confirm.
same problem. working in Germany and have a Gigabit connection.
my colleague tried a throttled connection. didn't work.

**Comment by Cartman0** [comment]
same issue in `gcc` image.

env
- docker desktop for windows: 2.3.0.3(45519)
- docker engine: 19.03.8, build afacb8b

**Comment by ciB89** [comment]
I have got the exact same issue, also win 10, also Germany, also FritzBox router (6591 cable). At first after installing docker for windows everything worked fine and I was able to pull, build and push (altohugh I had to make sure to use google dns). Then it suddenly stopped. Using PIA now as a workaround and it works..

**Comment by TSK-Dev** [comment]
Sehr geehrte Damen und Herren,
 
ich bin bis einschließlich 31.07.2020 nicht im Hause. Ihre E-Mail wird nicht  weitergeleitet.
In dringenden Fällen wenden Sie sich bitte an meine Kollegen unter edv@ndstsk.de.
 
Mit freundlichen Grüßen

Stephan Nikolaus
Niedersächsische Tierseuchenkasse
EDV / Internet



 

 
 
   
I just installed the newest FritzOS version released today (07.19-80490 BETA) and hello-world can now pull without problem.

```

❯ docker pull hello-world

Using default tag: latest

latest: Pulling from library/hello-world

0e03bdcc26d7: Pull complete

Digest: sha256:49a1c8800c94df04e9658809b006fd8a686cab8028d33cfba2cc049724254202

Status: Downloaded newer image for hello-world:latest

docker.io/library/hello-world:latest

```

I dont know if anything else changed because I did not test it before updating.

**Comment by Spenhouet** [comment]
We have the same issue. We can't update the firmware of our Fritz!Box 6591 Cable since it is provided by the provider. There also must be something wrong on the docker side of things. No other application has these issues.

**Comment by TSK-Dev** [comment]
Sehr geehrte Damen und Herren,
 
ich bin bis einschließlich 31.07.2020 nicht im Hause. Ihre E-Mail wird nicht  weitergeleitet.
In dringenden Fällen wenden Sie sich bitte an meine Kollegen unter edv@ndstsk.de.
 
Mit freundlichen Grüßen

Stephan Nikolaus
Niedersächsische Tierseuchenkasse
EDV / Internet



 

 
 
   
We have the same issue. We can't update the firmware of our Fritz!Box 6591 Cable since it is provided by the provider. There also must be something wrong on the docker side of things. No other application has these issues.

**Comment by gingters** [comment]
> We have the same issue. We can't update the firmware of our Fritz!Box 6591 Cable since it is provided by the provider. There also must be something wrong on the docker side of things. No other application has these issues.

It's most likely not the Docker side but rather Amazon.
Docker hosts on Amazon and there are other applications that also show these issues,
i.e. the Elite: Dangerous game launcher can't download the game files (hosted on Amazon), and the JetBrains Toolbox for the JetBrains developer tools also can't download new versions of the tools (also hosted on Amazon) in this constellation.

Strangely enough, the Jetbrains Toolbox issue also occured with a colleague on his Mac, while the other issues only affect Windows machines.

Yesterday AVM released a new FritzBox! firmware that allegedly fixes these issues.
I hope Vodafone is fast adopting the changes this time for their branded boxes.

**Comment by TSK-Dev** [comment]
Sehr geehrte Damen und Herren,
 
ich bin bis einschließlich 31.07.2020 nicht im Hause. Ihre E-Mail wird nicht  weitergeleitet.
In dringenden Fällen wenden Sie sich bitte an meine Kollegen unter edv@ndstsk.de.
 
Mit freundlichen Grüßen

Stephan Nikolaus
Niedersächsische Tierseuchenkasse
EDV / Internet



 

 
 
   
> We have the same issue. We can't update the firmware of our Fritz!Box 6591 Cable since it is provided by the provider. There also must be something wrong on the docker side of things. No other application has these issues.

It's most likely not the Docker side but rather Amazon.
Docker hosts on Amazon and there are other applications that also show these issues,
i.e. the Elite: Dangerous game launcher can't download the game files (hosted on Amazon), and the JetBrains Toolbox for the JetBrains developer tools also can't download new versions of the tools (also hosted on Amazon) in this constellation.

Strangely enough, the Jetbrains Toolbox issue also occured with a colleague on his Mac, while the other issues only affect Windows machines.

Yesterday AVM released a new FritzBox! firmware that allegedly fixes these issues.
I hope Vodafone is fast adopting the changes this time for their branded boxes.

**Comment by Spenhouet** [comment]
> Yesterday AVM released a new FritzBox! firmware that allegedly fixes these issues.
I hope Vodafone is fast adopting the changes this time for their branded boxes.

We should not count on that. I have little hope that Vodafone will push any update (soon or not at all).
This probably has to be fixed on behalf of Docker, Amazon, ... or who ever can.

Docker it not working for me on Windows at all. Not on WSL and not via Hyper-V.

**Comment by Spenhouet** [comment]
An additional observation:

- 🟢 nvcr.io  
- 🔴 docker.io 

There seems to be some difference between registries. The NVIDIA registry works while docker hub does not.

**Comment by Cartman0** [comment]
i don't use Fritzbox router.
this maybe network connection problem..

**Comment by JanFellner** [comment]
Same constellation here (Vodafone - FRITZ!Box 6591 Cable - FRITZ!OS 07.13).
Strange unexpected eof issues while docker login.

**Comment by cybertschunk** [comment]
Update: I managed to get docker working again inside a virtualized linux installation. The windows host system is still unable to pull any images. This really seems to be a windows related problem.

**Comment by pluralistix** [comment]
It's not Windows only. I do have the same problem FritzBox 6660 (07.19-80490 BETA) with Vodafone Red Internet & Phone 1000 Cable. docker pull alpine on Fedora 32 "Client.Timeout exceeded while awaiting headers" while docker pull 000.dkr.ecr.eu-west-1.amazonaws.com/dummy succeeds. Disabling Hardware Packet Acceleration or using a VPN from my company (terrible slow) "fixes" it.

**Comment by fcolling** [comment]
> It's not Windows only. I do have the same problem FritzBox 6660 (07.19-80490 BETA) with Vodafone Red Internet & Phone 1000 Cable. docker pull alpine on Fedora 32 "Client.Timeout exceeded while awaiting headers" while docker pull 000.dkr.ecr.eu-west-1.amazonaws.com/dummy succeeds. Disabling Hardware Packet Acceleration or using a VPN from my company (terrible slow) "fixes" it.

PROBEM WAS ISOLATED!!
I use windows 10 and FritzBox 6660 cable  500mbps and I have the same problem, but if I use my old fritzbox 7360 20mbps it works perfectly.

**Comment by SteveScott** [comment]
I have no idea what box I have but I am in an enterprise environment in America and I am getting the EOF error.

**Comment by molesmoke** [comment]
I have the same issue pulling Windows containers (Linux containers appears to be OK on a Linux host, but this could just be because the layers I'm pulling there are smaller). If I try repeatedly, it does eventually succeed. My network setup is a little unusual - a rural setup through a chain of Ubiquiti PowerBeam AC dishes. I've not noticed any issues downloading large files from other sources though.

**Comment by SteveScott** [comment]
I am pulling a Linux container on Windows. I work for government so it is
behind so many firewalls. I don't know where to start. I think I am
connecting to the proxy server. It just rejects the request?

**Comment by hgross** [comment]
I have the same issue: Windows 10 over 1GBit ethernet via 500 MBit UnityMedia (Vodafone) - FRITZ!Box 6591 Cable - FRITZ!OS 07.13 - DSLite connection

**Comment by tfrommen** [comment]
> I have the same issue: Windows 10 over 1GBit ethernet via 500 MBit UnityMedia (Vodafone) - FRITZ!Box 6591 Cable - FRITZ!OS 07.13 - DSLite connection

💯 this one!

**Comment by SteveScott** [comment]
My problem was caused by the network. I entered an HTTP and an HTTPS connection, but the proxy only accepts HTTP requests. I changed both secure and insecure web server URLs to HTTP.  I hear that this is common with many proxy servers: some only accept HTTP internally.

**Comment by SteffenMangold** [comment]
Same here with Vodafone - FRITZ!Box 6591 Cable - FRITZ!OS 07.13
Deactivating hardware acceleration fixed it.

Because I find it hard to find, maybe this helps otheres:
![image](https://user-images.githubusercontent.com/20702171/89122211-d7a85300-d4c5-11ea-87f6-a87a80082c14.png)

**Comment by KorbenDev** [comment]
Had the same issue. Also my NAS couldn't download images, but had a different error message: "Client.Timeout exceeded while awaiting headers". After disabling hardware acceleration on my Fritzbox it worked just fine.
Router: AVM Fritzbox 6660 (cable)
Firmware: Fritz!OS 07.19-80783 BETA
Provider: Vodafone (1 Gbit cable)

**Comment by KorbenDev** [comment]
For me (as a AVM FB6660 user) the issue has been solved with today's new BETA Firmware (07.19-81008 BETA).
Download of Docker images now works fine without disabling hardware acceleration.

**Comment by Fleshgrinder** [comment]
I have a FRITZ!Box 6591 Cable from Vodafone (branded) with a 1G connection in Berlin and disabling hardware acceleration also fixed the issue for me.

**Comment by VanillaFord** [comment]
same here with a branded FRITZ!Box 6591 Cable from Vodafone and with a 1G connection.
Unfortunately the connection slows down to below 500mbps with hardware acceleration off.
Vodafone is not known for updating the firmware frequently, so this is going to be a major issue, even if AVM will be able to fix it in a subsequent firmware update.
My Linux NAS is able to pull images from docker-hub just fine, with hardware acceleration enabled.

**Comment by thimo-seitz** [comment]
Recently my FritzBox 6660 updated to 07.21, which fixed the issue for me.

**Comment by shivan** [comment]
Here the same, FritzBox 6591, OS 7.13

Hopefully Vodafone will soon update to 7.20 or newer.

**Comment by hgross** [comment]
> I have the same issue: Windows 10 over 1GBit ethernet via 500 MBit UnityMedia (Vodafone) - FRITZ!Box 6591 Cable - FRITZ!OS 07.13 - DSLite connection

I operate my own FRITZ!Box 6591 Cable (not provided by Vodafone, [Routerfreiheit](https://www.bundesnetzagentur.de/DE/Sachgebiete/Telekommunikation/Verbraucher/WeitereThemen/WLanRouter/routergesetz-node.html)) and updated to the new [7.21 release](http://download.avm.de/fritzbox/fritzbox-6591-cable/other/fritz.os/info_en.txt) - this fixed the issues for me. I have hardware acceleration enabled.

**Comment by emuuu** [comment]
> (not provided by Vodafone, [Routerfreiheit](https://www.bundesnetzagentur.de/DE/Sachgebiete/Telekommunikation/Verbraucher/WeitereThemen/WLanRouter/routergesetz-node.html))

Well Routerfreiheit is pretty much of a joke in this context as Vodafone only grants you static public IP(s) if you use their router. If you want to use your own u automatically fallback to a dynamic IP (they don't tell you that in advance tho)

I've just configured the FritzBox to be just a gateway for my Linksys router. This seems to fix the problem as well. Just pulled a mongo image without any problems.

**Comment by VanillaFord** [comment]
I do have that problem, although using a MikroTik external router behind the Fritz (VF 6951), that is configured as exposed host.
The only way for me to solve this, is not to use Windows anymore, as pulling imgaes via my Liniux based NAS is possible.

**Comment by hgross** [comment]
> > (not provided by Vodafone, [Routerfreiheit](https://www.bundesnetzagentur.de/DE/Sachgebiete/Telekommunikation/Verbraucher/WeitereThemen/WLanRouter/routergesetz-node.html))
> 
> Well Routerfreiheit is pretty much of a joke in this context as Vodafone only grants you static public IP(s) if you use their router. If you want to use your own u automatically fallback to a dynamic IP (they don't tell you that in advance tho)
> 
> I've just configured the FritzBox to be just a gateway for my Linksys router. This seems to fix the problem as well. Just pulled a mongo image without any problems.

Yeah, for me even getting a static IP wasn't possible anymore in 12/2019 - only DSLite for newly connected houses. Of course I [filed a complaint](https://www.bundesnetzagentur.de/DE/Allgemeines/Kontakt/Kontakt_node.html) with the agency. BTW: The "static-ip gap" can be somewhat (significant performance loss) bridged using a cheap vServer with a static ip which routes through a VPN into your home network.

**Comment by alxbauer** [comment]
Same story! FritzBox 6591, Vodafone, OS 07.13.
Thanks a lot for sharing the work a round!

**Comment by thomasjungblut** [comment]
> Recently my FritzBox 6660 updated to 07.21, which fixed the issue for me.

I realize that I'm late to the party, but indeed the update to 07.21 fixed it (6591 cable).  What a crazy issue! Is there more information on what the issue was from Fritz!OS point of view?

**Comment by thimo-seitz** [comment]
Nothing specific in the changelog. Maybe that entry:
![grafik](https://user-images.githubusercontent.com/20231368/96090954-3d9f5680-0ec9-11eb-8e77-3fcb0cb4dd5b.png)

**Comment by Nowi5** [comment]
Had the same issue. Thank you for your support. Still waiting for my update (vodafone/unitymedia)
![image](https://user-images.githubusercontent.com/27913135/97803617-cd276200-1c4a-11eb-9a03-5d6981c1ace3.png)

**Comment by jsteenri** [comment]
I encountered this same issue as well from the Americas with no FritzBox! in sight.   Ensuring that the docker pull was not going though a proxy server solved the problem for me.  

Specifically, in Docker Desktop Settings ==> Resources ==> Proxies, either don't define one, or add exceptions as needed.

Note: when working with the new GitHub Container Registry, I found I needed **both** `ghcr.io` and `github-production-container-registry.s3.amazonaws.com` in the exception list.

**Comment by VinzSpring** [comment]
I encountered a similar issue where I couldn't pull any images from docker.
Deactivating the Vodafone-Gateway's Internal Firewall fixed the issue! 👍

**Comment by Day0Dreamer** [comment]
@VinzSpring - How did you do that? 
Also - VPN helped

**Comment by jmartsch** [comment]
I have the same issue: Windows 10 over 1GBit ethernet via 500 MBit UnityMedia (Vodafone) - FRITZ!Box 6591 Cable - FRITZ!OS 07.13. 

The problem is, that Vodafone/Unitymedia did not update the firmware to 7.0.20 which is released 3 months before yet. There is a long german thread about this issue here https://forum.vodafone.de/t5/Internet-Ger%C3%A4te/Kein-Update-bei-FritzBox-6591-Cable/td-p/2421100 and it really makes me angry, that such important updates take such a long time.

**Comment by VinzSpring** [comment]
@Day0Dreamer via the router's webinterface.

**Comment by Novalis15** [comment]
Same Issue here: FRITZ!Box 6591 Cable with FRITZ!OS 07.13 (1GBit ethernet UnityMedia (Vodafone)).
Disabling Hardware acceleration is a valid workaround for now. Hope Vodafone is rolling out a new FRITZ!OS Update soon.

**Comment by gururajn** [comment]
I'm having similar issue when I execute the build command docker-compose -f docker-compose.yml up -d --build 
ERROR: unexpected EOF

**Comment by khamza85** [comment]
Getting the same error after I changed `--data-root `from` C:\ `to` D:\ `disk. My router is InnboxG74 and not from Germany.

**Comment by shivan** [comment]
fyi: Today I got the Update 7.22 from Vodafone on my FritzBox 6591

**Comment by VanillaFord** [comment]
...this update seems to be directed towards Unitymedia boxes only, see: https://www.vodafonekabelforum.de/viewtopic.php?f=67&t=43570 (VF-West)
Regular VF users will still have to wait ;-(

**Comment by fabianblum** [comment]
If you have Fritz!Box. Disable "Hardware acceleration". After you logged in click on the bottom side on "Content" 
![image](https://user-images.githubusercontent.com/16725150/107357346-3a605400-6ad2-11eb-9713-84dc5c0ab19d.png) and then on "Fritz!Box Support" 
![image](https://user-images.githubusercontent.com/16725150/107357410-4ba96080-6ad2-11eb-962e-af9d734de220.png) then scroll to "Packet acceleration" and disable it. 
![image](https://user-images.githubusercontent.com/16725150/107357462-5fed5d80-6ad2-11eb-86cb-268f058f5582.png)
Save and it should work now

**Comment by sschuberth** [comment]
Thanks @fabianblum. However, that was already [described in a comment](https://github.com/docker/for-win/issues/6192#issuecomment-720084645) above 😉

**Comment by busaku** [comment]
Worked. But lost 700Mbits download.

**Comment by dfyx** [comment]
> ...this update seems to be directed towards Unitymedia boxes only, see: https://www.vodafonekabelforum.de/viewtopic.php?f=67&t=43570 (VF-West)
> Regular VF users will still have to wait ;-(

Even worse: only Unitymedia boxes with dynamic IP addresses. Business customers with static IP addresses (like me) will have to wait until late April, according to the hotline.

**Comment by ColinCee** [comment]
Fixed a similar issue when I tried setting up WSL2 with docker today.

```sh
$ docker-compose up
Pulling db (mongo:4.4-bionic)...
ERROR: Get https://registry-1.docker.io/v2/: EOF
$ cat ~/.docker/config.json 
{
        "auths": {
                "https://index.docker.io/v1/": {}
        },
        "credsStore": "desktop.exe"
}
```
I had an existing WSL2 with docker installation working fine so I compared the config.json and deleted the auths so that it looks like this:

```json
{
        "auths": {},
        "credsStore": "desktop.exe"
}
```

**Comment by VanillaFord** [comment]
> fyi: Today I got the Update 7.22 from Vodafone on my FritzBox 6591
fwiw:
....VF pushed v7.21 (note, not 7.22 like with ex-unitymedia boxes) to my Homebox 6591Cable about 10 days ago and I've been pulling my hair out since then.
First I had to perform a factory reset in order from preventing the box to reboot every 15 mins.
Second, the LAN-Switch is showing port-flaps, where the link will go offline for about 3-4secs.....never had this with v7.13 and earlier, but as it turns out this is an incompatibility with my main switch and router, a mikrotik RB4011...after moving the port into a VLAN on my Mikrotik CRS326 switch, this is now stable again.

...sorry for OT.

**Comment by VanillaFord** [comment]
> fyi: Today I got the Update 7.22 from Vodafone on my FritzBox 6591

fwiw:
....VF pushed v7.21 (note, not 7.22 like with ex-unitymedia boxes) to my Homebox 6591Cable about 10 days ago and I've been pulling my hair out since then.
First I had to perform a factory reset in order from preventing the box to reboot every 15 mins.
Second, the LAN-Switch is showing port-flaps, where the link will go offline for about 3-4secs.....never had this with v7.13 and earlier, but as it turns out this is an incompatibility with my main switch and router, a mikrotik RB4011...after moving the port into a VLAN on my Mikrotik CRS326 switch, this is now stable again.

...sorry for OT.

**Comment by jmartsch** [comment]
> > fyi: Today I got the Update 7.22 from Vodafone on my FritzBox 6591
> 
> fwiw:
> ....VF pushed v7.21 (note, not 7.22 like with ex-unitymedia boxes) to my Homebox 6591Cable about 10 days ago and I've been pulling my hair out since then.
> First I had to perform a factory reset in order from preventing the box to reboot every 15 mins.
> Second, the LAN-Switch is showing port-flaps, where the link will go offline for about 3-4secs.....never had this with v7.13 and earlier, but as it turns out this is an incompatibility with my main switch and router, a mikrotik RB4011...after moving the port into a VLAN on my Mikrotik CRS326 switch, this is now stable again.
> 
> ...sorry for OT.

Everything worked fine here, as soon as my router had the update.

**Comment by dfyx** [comment]
Vodafone has updated all routers by now so I'd say this can be closed.
