### ISSUE TITLE
No docker commands in powershell or cmd.exe?

### ISSUE THREAD

**Issue by mmuncan** [docker/for-win#6196]
i even set the path of docker [C:\Program Files\Docker\Docker] in the environmental settings, still no luck.

has anyone an idea? :)

ID: 4CE345EA-CA11-49C8-BD80-0AD9A4F82A9E/20200401191036

**Comment by mat007** [comment]
It’s in `C:\Program Files\Docker\Docker\resources\bin` but the installer should add it to your `PATH`:

![image](https://user-images.githubusercontent.com/2386884/78177730-da833080-745e-11ea-98fb-49d84988a7ea.png)
