### ISSUE TITLE
Weird reference to base image disk location & unknown folder of same size as image

### ISSUE THREAD

**Issue by Ariwari** [docker/for-win#620]
I've been cleaning up my Docker containers and images since my ProgramData folder exceeded 30GB, which was a bit to much for me. 

But now I'm a bit confused by the following picture:

![weird location reference](https://cloud.githubusercontent.com/assets/4222552/24704282/483f91f0-1a07-11e7-87f5-ca6f7b31d26c.PNG)

I have one image left: b4713e4d8bab, a microsoft/windowsservercore image which is 10.1GB.
When I inspect the location of this image I get the following size for the folder: 5.41GB.

This difference is weird enough, but the weirdest comes when I check the other folder 
(77b3fb4a6f19f272c9a04017f0659c56f682097e0068a5a5440329aa8491a382)
in the same directory: this one is 10.1GB?! Yet when I do a [Full inspect image b4713e4d8bab.txt](https://github.com/docker/for-win/files/896096/Full.inspect.image.b4713e4d8bab.txt) I can't seem to find any reference to that folder.

I would like to remove one of those folders to clear up hard drive space, but which one to pick?

**Comment by friism** [comment]
@Ariwari the safest way to remove these folders is using `docker system prune` (optionally with `-a`), or with `docker rmi`.

If that doesn't work for you, there's a tool available, but it's not safe and you should use it very carefully: https://github.com/jhowardmsft/docker-ci-zap

**Comment by Ariwari** [comment]
Hi @friism thanks for reacting,

I'm aware of the "docker rmi" command, I used that command to remove all of my other containers (and folders that belonged to them). Didn't yet know about the "docker system prune", looks like a pretty handy command, thanks for that!:)

But to make my issue more clear, I now have 2 folders and only 1 container image and the references look funky to me.

Image b4713e4d8bab has a reference to the 5.41GB folder with "docker inspect b4713e4d8bab", while "docker images tells me that the image is 10.1GB which corresponds with the 10.1GB folder that doesn't show up with the "docker inspect b4713e4d8bab" command. 

Now I destroyed the b4713e4d8bab image with "docker rmi b4713e4d8bab" and both folders got removed. Happy enough with that, but still a bit confused why the folder 10.1GB folder didn't seem to have any visible 'connection' to the container.

Same happens when retrying (pulling the windows/servercore image), one 5.41GB folder and one 10.1GB folder with only a reference to the 5.41GB folder and "docker images" again shows the image to be 10.1GB in size, allthough it now seems the total size is 5.41+10.1=15.42GB because it has 2 folders.

**Comment by friism** [comment]
@Ariwari if I remember correctly, the subdirs represent image layers, not images themselves. So it may be that the image you deleted had two layers.

If you're curious about Docker internals, I recommend looking at the graph-driver code in the docker/docker project.

**Comment by Ariwari** [comment]
@friism You are right about the image having two layers, and I now understand why I couldn't find any reference to the 10.1GB folder name: the layers are hashed in sha256. 

I'm going to do some more research on where this hashing occurs in code and what it hashes to connect an image layer to a subfolder (programdata/Docker/windowsfilter/<subfolder>)in the host system.

Interesting stuff, thanks again for responding this helps me alot!

**Comment by friism** [comment]
@Ariwari I think the folder name is just the layer id/hash. You can get those with `docker history <image-name>`.
