### ISSUE TITLE
network_mode: host

### ISSUE THREAD

**Issue by MJPA** [docker/for-win#6203]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Connect via some IP to the ports on the container

### Actual behavior

No IP to connect to anymore?

### Information

Since upgrading to Docker for Windows 2.0.0+, a container I had using `network_mode = host` is no longer available to connect to. For <2.0.0, the poor performance of bind mounts meant I used volumes and had a container to share them out with samba back to the host for developing.

Since 2.0.0, while performance is better, there are still issues that are causing issues so would like to keep the current setup. That is, a container to share the volumes out back to the host so I can edit files etc.

Is this no longer possible? Is there an alternative approach?

**Comment by gingters** [comment]
The Docker release notes for version 2.2.0.3 explicitely state:

> DockerNAT has been removed from Docker Desktop 2.2.0.0 **as using an IP address to communicate from the host to a container is not a supported feature**. To communicate from a container to the host, you must use the special DNS name host.docker.internal. We also recommend using ports to communicate from the host to a container. For more information, see [Networking](https://docs.docker.com/docker-for-win/networking/#use-cases-and-workarounds).


See also: https://docs.docker.com/docker-for-windows/release-notes/#docker-desktop-community-2203

**Comment by MJPA** [comment]
Ah, didn't see that one. At least there's a work around for now. Guess when that stops working I'll find something else to use instead of docker...
