### ISSUE TITLE
Docker Desktop 2.2.3.0 edge (both Win and Mac) doesn't support IPV6 in container

### ISSUE THREAD

**Issue by rfay** [docker/for-win#6206]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Applications using ipv6 inside the container and binding to an ipv6 port should work fine. (They have worked fine for years and years with docker).

### Actual behavior

As of Docker Desktop for Windows 2.2.0.5 suddenly binding to an ipv6 port doesn't work. I note that this same behavior occurs in Docker Desktop for Mac 2.2.0.5 today as well. It does *not* occur on Linux with dockerd 19.03.8

### Information

  - Windows Version: 10
  - Docker Desktop Version: 2.2.3.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Tried both virtualized and real hardware

### Steps to reproduce the behavior

This uses the official nginx container with a tiny site config using ipv6:

1. Make a directory, cd into the directory
2. Create the file Dockerfile with these contents (must be Linux LF endings)
```
FROM nginx
RUN echo "server { \
    listen [::]:80 default ipv6only=on; \
    } \
    " > /etc/nginx/conf.d/default.conf
```
3. Build the docker image `docker build -t noipv6 .`
3. `docker run --rm noipv6`

You'll get "2020/04/02 16:37:51 [emerg] 1#1: socket() [::]:80 failed (97: Address family not supported by protocol)" because ipv6 seems unsupported inside the linux container.

**Comment by stephen-turner** [comment]
Thanks, @rfay. Same as docker/for-mac#4415.

**Comment by rfay** [comment]
Hah, I looked before starting the post, but it took me more than an hour to get it written, replicated, tested :)

**Comment by stephen-turner** [comment]
Well, the other one is in for-mac, it's good to have a ticket in the for-win repo too.

**Comment by djs55** [comment]
Thanks very much for the report and reproduction steps. If you have time to try it, I've got an early development build based on edge with IPv6 working again: [win](https://download-stage.docker.com/win/edge/44007/Docker%20Desktop%20Installer.exe) and [mac](https://download-stage.docker.com/mac/edge/44007/Docker.dmg) 2.2.3.0 (44007) . Let me know if it works better for you or not. Sorry for the inconvenience this issue has caused.

**Comment by mikaelkaron** [comment]
Had the same problem and 44007 fixed it for me

**Comment by STaRDoGG** [comment]
44007 seems to have fixed the ipv6 issue for me as well.

**Comment by rfay** [comment]
This was long since solved.
