### ISSUE TITLE
Populating a volume using a container does not work in Docker on Windows

### ISSUE THREAD

**Issue by pukachupenn** [docker/for-win#6207]
I'm following the instruction on this Docker official page under ["Populate a volume using a container"](https://docs.docker.com/storage/volumes/#populate-a-volume-using-a-container) in an attempt to create a new volume populated with existing files in a newly launched container. However, file copy to the volume is not taking place at all and the volume remains completely empty.

### Expected behavior
Running this command:
`docker run -it --name=test -v C:\Data dataimage/test1:version1`
should create a new volume under **C\:Data** inside the container and copy all existing files at that location into the volume.

### Actual behavior
The volume gets created but the original content of the folder is completely hidden and empty. If I run the above command without the `-v option` instead, then I can see the original files at the same location.

### Information
I am using Docker Engine version is v19.03.8. 
My host OS is Windows Server 2019 running on a G4 instance of AWS EC2.

### Steps to reproduce the behavior
  1. Create a Windows container image with a folder named C:\Data and place some files and folders under it.
  2. Launch a new container using this image, with a new volume created at the same location as in the command above.
  3. Now observe that the C:\Data inside the container is empty.

**Comment by mat007** [comment]
This issue tracker is for Docker Desktop, see https://github.com/moby/moby/issues for the Docker daemon, e.g. running on Windows Server with Docker EE, etc…
