### ISSUE TITLE
windows docker 17.03.1 pull extremely slow from private registry

### ISSUE THREAD

**Issue by JiangJeffery** [docker/for-win#621]
### Expected behavior
i want to pull an image from our private registry。

### Actual behavior
![image](https://cloud.githubusercontent.com/assets/26914253/24745125/04f5df0e-1ae7-11e7-8be3-39e52d79970e.png)

![image](https://cloud.githubusercontent.com/assets/26914253/24745258/929fbe4c-1ae7-11e7-9943-0ff6a08e2d39.png)

### Information

pull is too slow 
the first Layers and the second Layers are too big。
when i look about the network.
i find it is pulling from a special ip address(117.18.232.200)。
117.18.232.200 is from Australia，but i am from china

can any one help me???

**Comment by friism** [comment]
Windows images have "foreign layers" which means that the layers that contain Windows are not (by default) stored in your private registry. There's a workaround to make that happen, though: https://github.com/docker/docker/issues/27580#issuecomment-262346159

We're also trying to come up with improvements.

**Comment by JiangJeffery** [comment]
@friism thanks first.
but i am not very clear,

"stop Docker Engine and start again with -g set to non-standard location"
how to start with -g to non-standard location

docker load -i image.tar.gz into that fresh Docker engine (eg. use -H to point at it)
what "eg. use -H to point at it" means

i need your help.
