### ISSUE TITLE
Trying to start k8s locks up the settings app

### ISSUE THREAD

**Issue by rockfordlhotka** [docker/for-win#6212]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6EAC03C8-EDFA-40EB-A762-44109A7C08BC/20200402232256

### Expected behavior

I should be able to turn on k8s in docker desktop settings and have it work.

### Actual behavior

I turned on k8s in docker desktop settings and the settings panes are all covered with a busy animation. Docker is running, but k8s has been "starting" for over 24 hours now.

![image](https://user-images.githubusercontent.com/2333134/78309376-686b2400-7510-11ea-89c3-ca4f2ecea0a8.png)

### Information

I've tried to enable k8s off and on for the past 18 months or more, with different versions of docker for windows and then docker desktop. I've always had the same result, so I'd say it is reproducible. In fact, I must assume it fails for everyone?

I've tried on a Surface Pro 4, 5, and 6 over time. I've tried on my big 6 core 32 gb ram desktop over time. Always the same result.

* This is always running on Windows 10 (though versions have changed over time - right now it is in the current Slow Ring preview).
* Right now it is failing in docker 2.2.0.5 (43884) I installed today, but it was failing with the previous build yesterday, and many older builds over the past 1-2 years
* Windows 10 is running on the metal on both my Surface Pro devices and my workstation

### Steps to reproduce the behavior

1. Install docker desktop on Windows 10
1. Make sure it works (I've never had an issue with docker itself working)
1. Go to the settings pane for Kubernetes and turn it on
1. k8s will never start, and the settings panes all become locked out

**Comment by mat007** [comment]
Relevant log error
```
[18:24:41.872][ApiProxy          ][Warning] time="2020-04-02T18:24:41-05:00" msg="Error while setting up kubernetes: cannot update the host kube config: invalid configuration: context was not found for specified context: microk8s. Retrying in 1s"
```
I think you may have a conflict with a (previous) installation of `microk8s`, somehow this prevents Docker Desktop to start Kubernetes.

**Comment by simonferquel** [comment]
Good catch @mat007. 
@rockfordlhotka can you cleanup your ~/.kube/config file and try to restart Docker Desktop ?

If you get stuck, you can also ~/AppData/Roaming/Docker/settings.json to disable Kubernetes and restart Docker Desktop.

**Comment by rockfordlhotka** [comment]
I tried a few changes to the config file, ultimately entirely deleting the config file and restarting docker desktop, but always with the same result.

Now I've edited the `settings.json` file to disable k8s. Interestingly enough, now the settings app only shows Docker as running, _but_ it is also still busy and locked out.

**Comment by ulrich** [comment]
Hello @rockfordlhotka 

It seems that Simon and Mat found the origin of your trouble. We have done a little corrections in the bootstrap code of Kubernetes module when there is a misconfiguration of context. The Kubernetes status will be stopped only.

In your context, can you try this:

- kubectl config set-context microk8s
- kubectl config use-context microk8s
- Stop and start Docker Desktop (no restart)

Thank you for your feedback.
