### ISSUE TITLE
WSL2: After upgrade to 2.2.3.0 I cannot access sqlserver (even with sqlcmd tool)

### ISSUE THREAD

**Issue by pellea** [docker/for-win#6218]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E3BECDB0-EE3E-4617-B404-A8B0600E5B96/20200403125542

### Expected behavior
Successfully connect to a SQL Server (linux) running on WSL2 with SQLCMD tool or Azure Data Studio from Windows 10.

### Actual behavior
Cannot connect to the server using SQLCMD or Azure Data Studio.

### Information

  - Is it reproducible? Yes
  - Is the problem new? Yes
  - Did the problem appear with an update? Yes

  - Windows Version: Win 10 Pro Insiders 2004 19592.1001
  - Docker Desktop Version: 2.2.3.0
  - WSL 2 Ubuntu

### Steps to reproduce the behavior
  1.  docker run -e 'ACCEPT_EULA=Y' -e 'MSSQL_SA_PASSWORD=XxxxPassword' --name 'mssql-xxxx' -p 1401:1433 -v mssqlxxxxvolume:/var/opt/mssql -d mcr.microsoft.com/mssql/server:2019-latest
  2. sqlcmd -S 127.0.0.1,1401 -U sa -P XxxxPassword

Before the update to 2.2.3.0 the port 1401 was working fine. I tried with another port but it's not working either.
I have also did a "reset to factory defaults".

**Comment by simonferquel** [comment]
Have you tried to unquote all your flags ? (removing the quotes worked for me)

**Comment by pellea** [comment]
The exact same docker command was working before the upgrade to 2.2.3.0. 

But I did tried and it's the same behavior.

**Comment by simonferquel** [comment]
Yes good catch. Those errors are raised by Windows, which for some reason blocks com.docker.backend.exe to bind to those ports on your machine. By any chance, have you blocked it when Windows prompted you the first time you tried to expose a port ? (maybe even before updating to 2.2.3.0).

Can you check the firewall rules related to this program ?

**Comment by simonferquel** [comment]
For a bit of context, before 2.2.3.0, if our own backend process was refused to bind the port, there would be a second chance with exposing on the wsl root network namespace (that windows would re-expose on the windows side). This is no longer the case, as it caused port clashing issues.

**Comment by pellea** [comment]
com.docker.backend.exe is allowed for TCP and UDP for any ports (for private and public network).
Even with the firewall completely Off it's not working.

**Comment by simonferquel** [comment]
Can you look at ports in use using `netstat -ano` and at ports reservations with `netsh interface ipv4 show excludedportrange protocol=tcp` ? There is clearly something on the Windows side forbidding you to bind on these ports.

**Comment by pellea** [comment]
Thank for pointing out `netsh interface ipv4 show excludedportrange protocol=tcp`. 
Both port are listed there.

I switch to 10433 and it's working...
