### ISSUE TITLE
Failure after disk space has run out

### ISSUE THREAD

**Issue by igorpopryadukhin** [docker/for-win#6219]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4737A864-A63D-4CB0-B407-C5265D1DADE9/20200403121042

### Actual behavior

  - Windows 10:
  - Docker Desktop Version: 2.2.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Windows

Greetings.
After the disk has run out of free space.
Docker for Windows crashed and did not want to start.

After rebooting the PC, the docker offered to reset all parameters, since the launch was unsuccessful.

I suspect that DockerDesktop.vhdx is broken.

How to restore all images?

**Comment by igorpopryadukhin** [comment]
In fact, I did not reset the data, as this would lead to a complete deletion of all data.

**Comment by STaRDoGG** [comment]
Open up the Windows Hyper-V Manager, and expand the disk size. Then try to start DD again.
