### ISSUE TITLE
'MobyLinuxVM' failed to start worker process: An invalid HANDLE was specified.

### ISSUE THREAD

**Issue by okproject** [docker/for-win#622]
### Information

Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID D2E07033-FBE5-44E7-AE9D-3FB958CD608A)

'MobyLinuxVM' failed to start worker process: An invalid HANDLE was specified. (0xC0000008). (Virtual machine ID D2E07033-FBE5-44E7-AE9D-3FB958CD608A)
at Start-MobyLinuxVM, : line 287
at , : line 382
at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings)
at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.b__0(Object[] parameters)
at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

  - Diagnostic ID from "Diagnose & Feedback" in the menu. : **55E59B74-5D2E-48A8-9AE8-9FC3631166F4/2017-04-06_20-59-44**

  - Version

Version 17.04.0-ce-win7 (10981)
Channel: edge
b598153

Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 06:06:36 2017
 OS/Arch:      windows/amd64
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.28/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

- Error output : 

error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.28/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

### Steps to reproduce the behavior

  1. ... Not possible to explain reprodcure error steps. Because i dont know how it is happen.
  2. ...

**Comment by okproject** [comment]
After 17.05.0-ce-rc1 update, this error fixed for me.

**Comment by friism** [comment]
@okproject thanks for following up - I'll close this issue for now, please re-open if the problem returns.
