### ISSUE TITLE
WSL2 backend not starting after enabling unencrypted TCP 2375 listener

### ISSUE THREAD

**Issue by mastacheata** [docker/for-win#6220]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 075CDFEE-799E-4367-ACC8-6226130CC160/20200403164828

### Expected behavior
Restarting docker should restart docker

### Actual behavior
Restarting docker kills it with fire

### Information

  - Is it reproducible?
Yep, happens every time.

  - Is the problem new?
Think so, yes. It hasn't happened the last time I tried to enable the IP socket instead of the Named-Pipes one.

  - Did the problem appear with an update?
Yes, I retry the WSL2 backend every few months to see if it's feasible to replace the Windows backend.

  - Windows Version: 10/2004/19592.1001
  - Docker Desktop Version: v19.03.8
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
  1. Update docker
  2. Switch to WSL2
  3. Wait 10 minutes for Docker to start
  4. After start notice that IntelliJ-based IDEs can no longer access Docker
  5. Reenable the TCP-listener on 2375
  6. Still can't connect
  7. Restart docker and see if that helps
  8. Wait 10-15 Minutes for Docker to start (it won't actually start, but that's what we're waiting for)
  9. After the usual 10-15 minutes are over, see the happy little popup of Docker notifying you it has crashed and won't come back any time soon

**Comment by stephen-turner** [comment]
Comments, @simonferquel?

**Comment by simonferquel** [comment]
I'll have a look on monday

**Comment by mastacheata** [comment]
If I reset docker to factory settings it will behave as expected again.

The only problem with that is I'd like to keep using my PyCharm Docker integration, which at the time of writing this doesn't understand the concept of named pipes, but only Unix sockets or TCP connections.
The Expose on tcp without TLS doesn't seem to have any effect at all on the WSL2 backend. It refreshes shortly (less than 2 sec - it's definitely not restarting the daemon, that takes waaaaaay longer)

If I then manually restart docker hoping it's only a hiccup in the UI, the same scenario as above unfolds with the only exit being "reset to factory".

**Comment by simonferquel** [comment]
I'll work on a fix today and probably will give you a private build to unlock you.
In the meantime, one thing you can try, is to setup an X server on your Windows host, and run PyCharm for Linux from your WSL distro. This way you'll get the extra benefit of near native IO performance for your bind-mounts.

**Comment by simonferquel** [comment]
Hmm your diagnostic file is corrupted, and I cannot reproduce locally. Can you send a new diagnostic ? I think something else is wrong with your environment.

**Comment by mastacheata** [comment]
Sure, I can reproduce this perfectly fine, but I really need Docker for work at the moment. I'll send a new Diagnostic and will post the ID here later tonight. 

Thanks for looking into this already.

**Comment by mastacheata** [comment]
075CDFEE-799E-4367-ACC8-6226130CC160/20200407131339
New Diagnostics ID. Sorry didn't make it yesterday.

**Comment by simonferquel** [comment]
```
[14:21:34.912][ApiProxy          ][Fatal  ] listen tcp 127.0.0.1:2375: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
```
There are 2 potential reasons for that:
- either a process is already listening on 2375 (can be checked with `netstat -ano` in admin powershell)
- there is a port reservation for this port (can be checked with `netsh interface ipv4 show excludedportrange protocol=tcp`)

**Comment by mastacheata** [comment]
netstat includes 2375 only on the remote side. which would be any client trying to reach docker at 2375

netsh doesn't include 2375 at all
