### ISSUE TITLE
after upgrading to 2.2.3 unable to docker-compose within wsl2 ubuntu

### ISSUE THREAD

**Issue by vairakkumar-vairaperumal** [docker/for-win#6221]
after upgrading to 2.2.3 unable to docker-compose within wsl2 ubuntu
  - [ x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
docker-compose -f filename build continues to build successfully
### Actual behavior
received message: 
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?
### Information

  - Windows Version: 10 2004
  - Docker Desktop Version: Docker version 19.03.8, build afacb8b
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1.  start docker with attached to ubuntu distros
  2.  docker ps works successfully in ubuntu wsl
  3. docker-compose -f docker-composefile.yml build
  4. receive the error message

**Comment by vlad320** [comment]
Good afternoon. After upgrading to 2.2.3, 80% of containers do not work for me either

**Comment by simonferquel** [comment]
Can you run a diagnostic and give us a diagnostic id ?
