### ISSUE TITLE
Desktop edge never start

### ISSUE THREAD

**Issue by dgx80** [docker/for-win#6225]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
080BFCA5-91F3-40B4-BA03-89B0365FC4BB/20200404192213
### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. install wsl2
  2. install docker desktop edge
  3. activate wsl2 engine
  4. run docker desktop and never starting

080BFCA5-91F3-40B4-BA03-89B0365FC4BB/20200404192213

**Comment by simonferquel** [comment]
I see a few occurences of WSL failures in your logs. e.g., on deploying docker-desktop wsl distro:
```
[14:24:22.012][WSL2Provisioning  ][Error  ] Failed to deploy distro docker-desktop to C:\Users\[redacted]\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Le d�lai de l�op�ration a expir�, car aucune r�ponse n�a �t� re�ue de l�ordinateur virtuel ou du conteneur.
```
and while copying data from the windows side to docker-desktop-data distro:
```
[14:37:19.023][LinuxWSL2Engine   ][Info   ] Error: mounting wslCLIDest: open /mnt/host/wsl/docker-desktop-data/isocache/2abf59b0f62178dd0405d492dad9443e1431d37a2608d939bcd0999a5d0e514e.iso: input/output error
[14:37:19.023][LinuxWSL2Engine   ][Info   ] 2020/04/04 18:37:18 open /mnt/host/wsl/docker-desktop-data/isocache/2abf59b0f62178dd0405d492dad9443e1431d37a2608d939bcd0999a5d0e514e.iso: input/output error
[14:37:19.515][LinuxWSL2Engine   ][Warning] Distro stopped with exit code 1
```
I am pretty sure you got a WSL failure while copying an iso file to the docker-desktop-data distro (this is something we do to improve performance) resulting in a corrupted file. 

Please try this:
- Stop Docker Desktop
- In a Powershell window, run `wsl -d docker-desktop-data -e /wsl-keepalive` and keep the window open.
- Open a wsl terminal (your own distro, such as Ubuntu).
- `ls /mnt/wsl/docker-desktop-data/isocache/` should give you a list of iso files
- remove them all with `sudo rm /mnt/wsl/docker-desktop-data/isocache/*`
- In the "wsl-keepalive" terminal, hit ctrl+c
- run docker desktop (it should take a little bit more time than usual)

Let me know if it fixes your issue.

**Comment by zegerius** [comment]
@simonferquel I am facing the same issue. Something strange is going on:

/mnt/wsl/docker-desktop-data/isocache > ls
ls: reading directory '.': Input/output error

/mnt/wsl/docker-desktop-data/isocache > sudo rm .
rm: refusing to remove '.' or '..' directory: skipping '.'

I reinstalled Docker Desktop after this issue and the images disappeared and reappeared from `wsl --list`, so not sure what's going on here..

5C3F1306-CBA0-4477-BBEC-45006B5D4F26/20200602095725

**Comment by simonferquel** [comment]
We think the root of the issue lives in the way WSL 2 handles shutdown (when a user closes his/her Windows session), where the timeout for WSL 2 distros to shotdown cleanly is too short and their filesystem can be dettached too harshly (leading to filesystem corruption).

We are working with Microsoft on that one.

**Comment by IITII** [comment]
> My ENV  
> Win10 2004 build 19041  
> docker version: 2.3.0.3(45519) stable  
> wsl2 ubuntu1804  

I simplely resolve this problem by following steps:
1. quit docker desktop
2. stop docker service in `service.msc` which should be called `com.docker.service`
3. shutdown wsl: `wsl --shutdown`
4. start wsl by click the icons(maybe this step is not necessary)
5. start docker windows

Good luck.

**Comment by Kif11** [comment]
I'm still getting `Error: mounting wslCLIDest: stat /mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-wsl-cli.iso: no such file or directory` from Docker. The solution offered by @IITII  doesn't help. Also getting filesystem error as pointed by @simonferquel
