### ISSUE TITLE
crashing hyper-v config

### ISSUE THREAD

**Issue by lerenah** [docker/for-win#6229]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by lerenah** [comment]
Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The operation failed.

An unexpected error occurred: This user isn't allowed to sign in to this computer. (0x80070531).

The operation failed.

The Hyper-V Virtual Machine Management service encountered an unexpected error: This user isn't allowed to sign in to this computer. (0x80070531).

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

**Comment by ido-ran** [comment]
I also run into this issue. Docker for Windows worked just fine and suddenly it didn't.
It seems the issue is with `Hyper-V Virtual Machine Management` service.
I can replicate it easily (on my machine) when starting `Hyper-V Manager` and try to create a new Virtual Machine. No OS and no network, I just click Finish and it show the error.

I've turned on security audit and this seems to be the failure.


```
An account failed to log on.

Subject:
	Security ID:		SYSTEM
	Account Name:		PF25C4F3$
	Account Domain:		workgroup
	Logon ID:		0x3E7

Logon Type:			5

Account For Which Logon Failed:
	Security ID:		NULL SID
	Account Name:		6DCFEAE9-F0FF-4768-A80C-C1D1630363E6
	Account Domain:		NT VIRTUAL MACHINE

Failure Information:
	Failure Reason:		User not allowed to logon at this computer.
	Status:			0xC000006E
	Sub Status:		0xC0000070

Process Information:
	Caller Process ID:	0x790
	Caller Process Name:	C:\Windows\System32\vmms.exe

Network Information:
	Workstation Name:	-
	Source Network Address:	-
	Source Port:		-

Detailed Authentication Information:
	Logon Process:		Advapi  
	Authentication Package:	Negotiate
	Transited Services:	-
	Package Name (NTLM only):	-
	Key Length:		0

This event is generated when a logon request fails. It is generated on the computer where access was attempted.

The Subject fields indicate the account on the local system which requested the logon. This is most commonly a service such as the Server service, or a local process such as Winlogon.exe or Services.exe.

The Logon Type field indicates the kind of logon that was requested. The most common types are 2 (interactive) and 3 (network).

The Process Information fields indicate which account and process on the system requested the logon.

The Network Information fields indicate where a remote logon request originated. Workstation name is not always available and may be left blank in some cases.

The authentication information fields provide detailed information about this specific logon request.
	- Transited services indicate which intermediate services have participated in this logon request.
	- Package name indicates which sub-protocol was used among the NTLM protocols.
	- Key length indicates the length of the generated session key. This will be 0 if no session key was requested.
```

**Comment by pkuehne** [comment]
For everyone still affected by this, try the following, it fixed the issue for me (and a bunch of other people):

* Clear the security event log (Event Viewer> Windows Logs> Security)
* Launch the Registry Editor
* Find the following key: `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\CrashOnAuditFail`
* Set the value of the key to 1
* Restart the computer

After this Hyper-V and Docker should start properly again.

**Comment by shinberg** [comment]
> For everyone still affected by this, try the following, it fixed the issue for me (and a bunch of other people):
> 
> * Clear the security event log (Event Viewer> Windows Logs> Security)
> * Launch the Registry Editor
> * Find the following key: `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\CrashOnAuditFail`
> * Set the value of the key to 1
> * Restart the computer
> 
> After this Hyper-V and Docker should start properly again.

Helps for me, but after update this registry flag is reset to previous value.
