### ISSUE TITLE
getsockopt: connection refused when trying to push to a local docker registry

### ISSUE THREAD

**Issue by PeterGrandcourt** [docker/for-win#624]
### Expected behavior
Follow instructions on https://docs.docker.com/registry/
docker run -d -p 5000:5000 --name registry registry:2
docker pull ubuntu
docker tag ubuntu localhost:5000/myfirstimage
docker push localhost:5000/myfirstimage

no errors

### Actual behavior
docker run -d -p 5000:5000 --name registry registry:2
docker pull ubuntu
docker tag ubuntu localhost:5000/myfirstimage
docker push localhost:5000/myfirstimage
The push refers to a repository [localhost:5000/myfirstimage]
Get https://localhost:5000/v1/_ping: dial tcp 10.44.2.113:5000: getsockopt: connection refused
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
EAEEE8DB-23DA-4F49-A534-0576BBACA6D4/2017-04-07_16-43-31
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
https://docs.docker.com/registry/#tldr
  - host distribution and version (Windows version, build number, etc)
Windows 10 Enterprise build 1607 64 bit OS buid 14393.953
Docker:
Version 17.03.1-ce-win5 (10743)
Channel: stable
b18e2a5

### Steps to reproduce the behavior

  Follow instructions on https://docs.docker.com/registry/
1. open powershell
2 docker run -d -p 5000:5000 --name registry registry:2
3. docker pull ubuntu
4. docker tag ubuntu localhost:5000/myfirstimage
5. docker push localhost:5000/myfirstimage

**Comment by friism** [comment]
I think you need to set `insecure registries` in the Docker config (this can be done in the systray menu). Details here: https://github.com/sameersbn/docker-gitlab/issues/890#issuecomment-247194859

By default, local registries (eg. 127.0.0.0/8 and I think localhost) should be allowed. What's very mysterious is that your localhost seems to resolve `10.44.2.113` - I don't know why that would be.

**Comment by PeterGrandcourt** [comment]
I checked my docker for windows settings, and had my actual IP address setup in the insecure registries list, but not local host.
I've added localhost:5000 and this results in the following.

docker push localhost:5000/myfirstimage
The push refers to a repository [localhost:5000/myfirstimage]
Put http://localhost:5000/v1/repositories/myfirstimage/: dial tcp [::1]:5000: getsockopt: connection refused

So still getting the connection refused.

If it is necessary to add localhost to the insecure repositories, then it would be great if that was mentioned in the registry documentation.

**Comment by sirajmansour** [comment]
@friism i can confirm that i had the same experience as @PeterGrandcourt.

**Comment by hantsy** [comment]
I am using the latest Docker Toolbox 18.01 under Windows 10, add `localhost:5000` or `127.0.0.1:5000` into `config.json` of the machine.

```
            "InsecureRegistry": [
                "localhost:5000",
                "127.0.0.1:5000"
            ],
```

It does not work at all.

BTW,  I am sure I have set the 5000 mapped to localhost in VirtualBox, and I can access http://localhost:5000/v2/_catalog in my browser.

**Comment by RogerWeihrauch** [comment]
Howdy interested colleagues
May someone tell me a solution on same related, but running on different platform, error:
I am running DCOS, try to push nginx as docker container with this command:
docker push boot.dcos:5000/nginx
and run int o the same error. The thing is: where do I find above mentioned config.json fie in this env?
Where is this JSON file?
Thanx in advance for all your helpful responses.
Regards,
Roger

**Comment by willbush** [comment]
@hantsy I believe InsecureRegistry setting should go in the daemon.json file.

**Comment by stec00** [comment]
@hantsy Also it should be "insecure-registries", not "InsecureRegistry"

**Comment by javydreamercsw** [comment]
I'm having the same issue. Any solutions?

**Comment by bauerjj** [comment]
@javydreamercsw 

You probably don't have a default registry. Do this:
`docker run -d -p 5000:5000 --restart=always --name registry registry:2`
Restart `dockerd` and then push your image using `docker push localhost:500/<your_container>`

**Comment by javydreamercsw** [comment]
Figured that and got it running, thanks!

**Comment by rmichaelbics** [comment]
I have tried all the above but it does not work for me. I am using Windows 10 OS.
