### ISSUE TITLE
Overwritten resolv.conf

### ISSUE THREAD

**Issue by christiandavilakoobin** [docker/for-win#6245]
### Expected behavior
After wake up, sometimes the /etc/resolv.conf file is overwritten with google DNS.

### Actual behavior
The resolv.conf must keep the original value.

### Information
As a workaround, doing a docker-compose down & up restore the original value.

**Comment by justincormack** [comment]
Can you provide a way to replicate this? How are you setting the `/etc/resolv.conf` file?

**Comment by christiandavilakoobin** [comment]
I'm not sure how to reproduce it. After doing docker-compose up, this is the content of resolv.conf:
\# This configuration is written to the config.iso
nameserver 192.168.65.1

But randomly after a PC reboot, it changes to:
nameserver 8.8.8.8
nameserver 8.8.4.4

**Comment by christiandavilakoobin** [comment]
I saw something today. I boot my PC, and the docker image has the wrong resolv.conf. I stopped the container, and started again, and the resolv.conf changed to the right one. It seems a race condition at PC boot.

**Comment by christiandavilakoobin** [comment]
I'm using docker 2.3, and it doesn't happen anymore so far.
