### ISSUE TITLE
The virtual machine could not be started because a required feature is not installed.

### ISSUE THREAD

**Issue by aschip** [docker/for-win#6253]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
C2402989-20DF-4D3C-8DD5-1A62F47BC24F/20200407025800
### Expected behavior
Able to build & run windows container images on windows 10 Pro
### Actual behavior
Unable to build and/or run windows container images on windows 10 Pro
### Information

  - Windows Version: 10
  - Docker Desktop Version: 
![image](https://user-images.githubusercontent.com/13371053/78625779-13992600-78e1-11ea-8d21-6bc8590099f0.png)

  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

1. Download sample : https://github.com/dockersamples/docker101-windows/tree/master/hostname-app

2. docker build --tag hostnameapp:1.0

You get following error: 

```
 Error response from daemon: hcsshim::CreateComputeSystem e02218fd2835bff5a5375e358d8b7dcee1cc42186d069a08b39e5feefac0aaa0: The virtual machine could not be started because a required feature is not installed.
```

Virtualization has been enabled: 
![image](https://user-images.githubusercontent.com/13371053/78626054-be114900-78e1-11ea-841c-c9b58f5b7997.png)

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place?
Sorry, I would move it myself, but I can't because it's in a different org (it's `moby` not `docker`).

**Comment by webtrainingroom** [comment]
is there any solution for above mentioned error? please share the solution if any! i am getting the same error while trying build asp.net core 3.1 on windows 10.
