### ISSUE TITLE
Win10 - Hyper-V Virtualization is active but errormessage occurs

### ISSUE THREAD

**Issue by ARennen** [docker/for-win#6256]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [X ] I have uploaded Diagnostics
  - Diagnostics ID: 7A1EE04C-EFBE-4945-97C6-3880BD18F70F/20200407052858

### Expected behavior
Just want to start Docker Desktop. 
### Actual behavior
Stops with Error:
Hardware assisted virtualization and data execution protection must be enabled in the bios.
![image](https://user-images.githubusercontent.com/63279323/78635104-baf86780-78a5-11ea-9c51-da4c262434ef.png)

### Information

systeminfo:
Anforderungen für Hyper-V:                     Erweiterungen für den VM-Überwachungsmodus: Ja
                                               Virtualisierung in Firmware aktiviert: Ja
                                               Adressübersetzung der zweiten Ebene: Ja
                                               Datenausführungsverhinderung verfügbar: Ja
  - Windows Version:
Microsoft Windows Version 1903(Build 18362.657)
  - Docker Desktop Version:
2.2.0.43884 (docker --version : Docker version 19.03.8, build afacb8b)

  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
no
### Steps to reproduce the behavior

(No changes to the BIOS settings made!)

  1. Install Docker Desktop and run
  2. Install VirtualBox
  3. Deactivate Hyper-V feature
  4. Run Virtual Box
  5. Deinstall VirtualBox
  6. Reactivate Hyper-V feature
  7. Try to run Docker Desktop again
  8. Error about Hardware assisted virtualization... will occur
  9. Deinstall Docker Desktop and disable Hyper-V feature
10. Reinstall DockerDesktop with feature to aktivate nessecary Windows Features automatically
11. Error still exists

**Comment by SoShellon** [comment]
same problem
