### ISSUE TITLE
No log files created and docker logs returnd nothing

### ISSUE THREAD

**Issue by PavelSosin-320** [docker/for-win#6257]
No log files created for Linux based containers regardless of how the container is run
- via docker run
- via Kubernetes deploy
- via Docker compose

  - [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID no diagnostics created!!!:

### Expected behavior
json log file for the running container is available via Docker logs
via dashboard
via File manager inside Appdata\Docker\containers

### Actual behavior
neither method displays a log files
### Information

  - Windows Version: Windows 10 2004 Pro dev preview
 - WSL 2.0 Microsoft Ubuntu 18.04 distro
  - Docker Desktop Version: 2.3 Edge
  - Log driver is default
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
No 
### Steps to reproduce the behavior
1. Install Docker Desktop on top of recent Windows edition with the recent WSL 2.0
2. Deploy and run some Linux based containers
3. deploy some staff to Kubernetes like the dashboard  or Ingress
-----------
I have totally 34 according to the docker ps and dashboard
Try to get log using docker logs or Dashboard
Check Containers folder on the host Windows - don't exist

  1. ...
  2. ...

**Comment by PavelSosin-320** [comment]
P.S. This is not a surprise:  containers folder inherits read-only property from the parent Docker folder. Nobody, especially WSL VM can write something into this folder. This is the wrong design for WSL: Linux distro can't write into ProgramData or even, cd into this folder. To be able to write something output folders of Docker must reside under the Owner's folder like \Users\MyUser\.docker\Containers and this folder has to be writable for the Owner at least.
Also, User's data subfolder has to be writable to ensure volume mapping

**Comment by simonferquel** [comment]
I don't really see your issue:
Docker logs work as expected:
```
simon@GROSPC:~/pinata$ docker run --name nginx -d -p 80:80 nginx
a3331df6c1e39e9dc8215c04f46ec59c11fbe68c2787ab59dc567cc7e308b460
simon@GROSPC:~/pinata$ curl http://localhost
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
simon@GROSPC:~/pinata$ docker logs nginx
172.17.0.1 - - [07/Apr/2020:09:11:46 +0000] "GET / HTTP/1.1" 200 612 "-" "curl/7.58.0" "-"
```

**Comment by simonferquel** [comment]
Also, logs from dockerd and other services running within wsl2 are located in `C:\Users\<username>\AppData\Roaming\Docker\log\vm`

**Comment by PavelSosin-320** [comment]
Proposed solution:
Windows WSL operates with 2 nested filesystems: Linux and Windows. It's impossible to create a hard link between 2 filesystems but it's possible to create creat symbolic link like ln -s VM ln -s /mnt/c/Users/Pavel WinUserPavel
After it will be possible to create the correctly scoped and secured structure for logs inside owner's subtree:
```
root@MSI:~# ls WinUserPavel/.docker
application-template  config.json  daemon.json
root@MSI:~# cd WinUserPavel/.docker
root@MSI:~/WinUserPavel/.docker# mkdir containers
root@MSI:~/WinUserPavel/.docker# mkdir MyContainer12345678
root@MSI:~/WinUserPavel/.docker# cd MyContainer12345678
root@MSI:~/WinUserPavel/.docker/MyContainer12345678# pwd
/root/WinUserPavel/.docker/MyContainer12345678
root@MSI:~/WinUserPavel/.docker/MyContainer12345678# ls
root@MSI:~/WinUserPavel/.docker/MyContainer12345678#:
The host log target destination can be passed to log driver via environment:
- WSL environment
- Docker environment parameter
- config.json or daemon.json
Windows user name availability inside WSL VM is already under discussion.
Last step: log driver should take care to write logs to the desired place.
Hopefully, somebody can take this issue for implementation. 🤞

 
```

**Comment by PavelSosin-320** [comment]
@simonferquel Maybe you are right, this is the right place. but the documentation says something else.  Another issue is that logfile names are simply dockerlog0,1,dockerlog2, ...., etc. everything is under a single VM folder. They are plain text files and not json although my log driver is json-file. 
docker logs CONTAINER  returns nothing anywhere. Dashboard shows a black square instead of a log.
I have 34 containers running managed by Swarm and Kubernetes orchestration. Such log gives me nothing.

**Comment by PavelSosin-320** [comment]
@simonferquel Maybe json-file driver doesn't work it doesn't exist:
### PS C:\WINDOWS\system32> docker plugin ls
returns nothing. "log driver" = "json-file" has effect only if such driver exists?
