### ISSUE TITLE
Unable to start Docker on Windows 10 (1703)

### ISSUE THREAD

**Issue by davidgwright** [docker/for-win#626]
### Expected behavior
I expected to be able to execute the "docker run hello-world" test command

### Actual behavior
Failed to start up - refer to attached png.

### Information

[log.txt](https://github.com/docker/for-win/files/907343/log.txt)
![dockerfail](https://cloud.githubusercontent.com/assets/4597181/24827806/3b095c48-1c94-11e7-886e-684d9b6b5301.png)

I ran "coreinfo.exe -v" and this is the output:

Intel(R) Core(TM)2 CPU          6600  @ 2.40GHz
Intel64 Family 6 Model 15 Stepping 6, GenuineIntel
Microcode signature: 000000D0
HYPERVISOR      -       Hypervisor is present
VMX             *       Supports Intel hardware-assisted virtualization
EPT             -       Supports Intel extended page tables (SLAT)

### Steps to reproduce the behavior

  1. Install the latest docker for windows from the stable channel
  2. Launch docker for windows

**Comment by Abdullah2993** [comment]
try running `bcdedit /set hypervisorlaunchtype auto` from admin cmd and restarting the PC

**Comment by davidgwright** [comment]
Output of bcedit indicates it is already auto

Windows Boot Loader
-------------------
identifier              {current}
device                  partition=C:
path                    \Windows\system32\winload.exe
description             Windows 10
locale                  en-US
inherit                 {bootloadersettings}
recoverysequence        {575bfc6d-1c76-11e7-b0a6-ebe2cde6ee9d}
displaymessageoverride  Recovery
recoveryenabled         Yes
allowedinmemorysettings 0x15000075
osdevice                partition=C:
systemroot              \Windows
resumeobject            {575bfc6b-1c76-11e7-b0a6-ebe2cde6ee9d}
nx                      OptOut
bootmenupolicy          Standard
hypervisorlaunchtype    Auto

**Comment by ernestobarros** [comment]
Thanks @Abdullah2993 that helped!
@davidgwright Did you also restart with "shutdown /s /t"

**Comment by davidgwright** [comment]
@ernestobarros Did i restart what with "shutdown /s /t"?

**Comment by friism** [comment]
@davidgwright could you run and post a diagnostic id?

**Comment by davidgwright** [comment]
@friism Can you give me the command to run to obtain the diagnostic id or steps required to get it?

**Comment by friism** [comment]
![image](https://cloud.githubusercontent.com/assets/126104/24934299/9b74fdf2-1ecf-11e7-8d7d-8b5a834b8adc.png)

**Comment by davidgwright** [comment]
A Diagnostic with the id "76E3D1A3-F461-4C3E-94B2-12EDFB8B097A/2017-04-12_17-44-03" was uploaded..

**Comment by davidgwright** [comment]
I looked into the diagnostic file created and saw something about a missing capability - SR-IOV - so I started giving up on using Docker for what I wanted to do (play with ejabberd). So I thought to create a Linux Virtual Machine and start from there.

I have installed Oracles Virtual Box and created a Debian Linux Virtual Box Machine. Before I installed ejabberd and configured it I thought just try docker in the virtual machine. I then downloaded docker-ce and installed it and ran the hello-world docker file and it worked fine. I think I shall give up on Windows 10 however...

If I install Debian or any other Linux type distro on the computer instead of in a Virtual Box will I have the same issue as Windows 10? The question I am asking is does Virtual Box provide what is missing in my hardware\bios and if I use a Linux distro instead on Windows 10 as my base O\S will I have the same issue as I am currently having?

**Comment by RomanOrlov** [comment]
I might be wrong, but core 2 duo e6600 is not supporting SLAT wich is Hyper-V requirement. If you would type in cmd systeminfo there would be (in bottom) list of Hyper-V requirements with Yes/No checks. And if it so the only possibility to install docker is to move to linux.

**Comment by davidgwright** [comment]
As I stated in my initial comment...Coreinfo says SLAT is supported?

I ran "coreinfo.exe -v" and this is the output:

Intel(R) Core(TM)2 CPU 6600 @ 2.40GHz
Intel64 Family 6 Model 15 Stepping 6, GenuineIntel
Microcode signature: 000000D0
HYPERVISOR - Hypervisor is present
VMX * Supports Intel hardware-assisted virtualization
EPT - Supports Intel extended page tables (SLAT)

**Comment by davidgwright** [comment]
I ran systeminfo and you were correct.

Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: No
                           Data Execution Prevention Available: Yes

**Comment by friism** [comment]
@simonferquel I'm guessing SLAT is required to run? If so, should we check `systeminfo` on install and abort if it's not there?

**Comment by RomanOrlov** [comment]
Today tryed to install docker to win 8.1 with docker toolbox, then in dispair to win 10 with latest docker for win. None of that worked. Logs and errors was like **davidgwright** had. 
Once again it turned out that processor (intell core 2 duo T9600) is not supporting SLAT (I strongly believed  there was i3 or i5 processor and don't checked any requirements). Funny coincidence.
Problem was solved only after moving to linux xD
If SLAT is really required, than it would be really great to check and inform about this missing requirement.

**Comment by friism** [comment]
We have an internal issue to add a check for SLAT to avoid this problem.
