### ISSUE TITLE
WSL2 integration disappears on WSL shutdown. 

### ISSUE THREAD

**Issue by speller** [docker/for-win#6261]
When WSL is shut down by the `wsl --shutdown` command docker integration stops working:

```
$ docker ps

Command 'docker' not found, but can be installed with:

sudo apt install docker.io
```

After restarting docker it works fine.

**Comment by simonferquel** [comment]
Hi, Running wsl --shutdown actually kills the whole Docker/WSL2 backend. We don't try to recover automatically from there at the moment and you indeed need to restart Docker Desktop to make it work again.

I am not sure if we will tackle that issue, as to do this we will forcefully need to restart the utility VM immediately (which might not be what the user want).

**Comment by speller** [comment]
I came to the shutdown because WSL's current date become wrong after sleeping: https://github.com/microsoft/WSL/issues/4245 and tried solving it by rebooting WSL. If you have any contacts with the WSL team it would be nice to ping them to solve this issue until WSL2 GA release as it will cause a lot of issues with WSL's Linux itself and with the Docker Desktop in particular.
