### ISSUE TITLE
docker run error: Ports are not available: unable to list exposed ports: Get http://unix/forwards/list: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by yinjinit** [docker/for-win#6262]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version: 10
  - Docker Desktop Version: 19.03.8

### Steps to reproduce the behavior

  1. docker run hello-world
  2. Then I see error message: C:\Program Files\Docker\Docker\resources\bin\docker.exe: Error response from daemon: Ports are not available: unable to list exposed ports: Get http://unix/forwards/list: net/http: request canceled (Client.Timeout exceeded while awaiting headers).

**Comment by Yougigun** [comment]
same here. it had been fine, but this error message just bumped up starting from few days ago.

**Comment by yinjinit** [comment]
I think it's due to the Hyper-V bridge. I reinstalled it and it's working fine now.
