### ISSUE TITLE
start service error

### ISSUE THREAD

**Issue by marll** [docker/for-win#6269]
Hi,
the docker version is: Version 2.0.0.0-win81 (29211) Channel: stable Build: 4271b9e
During start of the service on windows 10 show the following error (diagnostic id: E0229051-0201-4A17-A099-7DC1F13707A1/20200408180739): 
Unknown action Version
   in Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:riga 36
   in Docker.WPF.BackendClient.Version() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:riga 46
   in Docker.WPF.BackendClient.CheckVersion() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:riga 199
   in Docker.WPF.BackendClient.CheckService(String action) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:riga 314
   in Docker.WPF.BackendClient.SendMessage(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:riga 167
   in Docker.Actions.<>c__DisplayClass25_0.<RestartVm>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:riga 228
   in Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:riga 59

**Comment by mat007** [comment]
2.0.0.0 is quite old, you should upgrade to a more recent version first.

**Comment by marll** [comment]
Hi,
with the new version does not find any container.
How can I restore the existing container?
Thanks
