### ISSUE TITLE
Docker suddenly won't start: Unable to create: ISO file

### ISSUE THREAD

**Issue by KenWatts** [docker/for-win#627]
### Expected behavior
Docker has been working perfectly for some time on Windows 10 for me, until this morning...
### Actual behavior
It won't start this morning. 
### Information
Diagnostic ID:
6038661B-DF44-4589-98A8-C6F7EEF708AD/2017-04-08_08-45-37

I'm on Windows 10 Pro 64bit 
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Abdullah2993** [comment]
Had the same issue https://github.com/docker/for-win/issues/623

**Comment by KenWatts** [comment]
My solution was to completely uninstall, then completely reinstall Docker.
