### ISSUE TITLE
Different colors for different windows

### ISSUE THREAD

**Issue by sbaron0** [docker/for-win#6282]
Hi, I ussually works with two monitors, and I open two or more instances of VSC at the same time with different components of the system, it could be a great help if I can use different colors for different instances to recognice them in one view. VSC use two difernet colors, one if you use a folder  and another if you use a workspace, I request if that could be different for different instances.
thanks a lot

**Comment by mat007** [comment]
Hi, it’s a little difficult to understand what exactly you’re suggesting.
Are you sure you wanted to create the issue on the Docker Desktop for Windows tracker?
