### ISSUE TITLE
WSL 2: chmod on [...]/.git/config.lock failed: Operation not permitted

### ISSUE THREAD

**Issue by pr1metine** [docker/for-win#6284]
## Description
The switch to WSL 2 has been quite a performance boost for me. Unfortunately I am now unable to use git due to the following thrown error: 

```
error: chmod on [...]/.git/config.lock failed: Operation not permitted
fatal: could not set 'core.filemode' to 'false'
```

I attempted to clone a repo to a drive (mounted with `volumes`). 

## Steps to reproduce
1. Get a docker image (you can use my docker image [pr1metine/quickcode:latest](https://hub.docker.com/repository/docker/pr1metine/quickcode)). It's HUGE though.
2. Run the container detached with a volume flag: `docker run -d -v "C:\\:/home/coder/project" --name code pr1metine/quickcode`
3. Try to clone a repo:

```
$ docker exec -it code /bin/bash
$ cd project
$ git clone (a repo of your choice)
```

## Possible Solution
Fortunately though there might be a quick fix for these issues with these [Chmod/Chown WSL Improvements](https://devblogs.microsoft.com/commandline/chmod-chown-wsl-improvements/). Until then I will switch back to the stable version.

**Comment by simonferquel** [comment]
Hi,
Thanks for the report. I'll add chmod/chown support for windows files.
However, for better performance, please put your projects files in a WSL distro file system. This way bind mounts will only use local filesystems, giving you much better performance (kernel cache will be enabled and inotify events will work).

**Comment by pr1metine** [comment]
Hello @simonfrequel,
am I supposed to put my projects into this folder?

`%LOCALAPPDATA%\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs`

**Comment by simonferquel** [comment]
No, within your wsl distro, you create a directory such as `~/projects` and you put your sources there instead of on the Windows filesystem. (then you can do things like `docker run -v ~/projects:/projects ...` from your wsl distro).

**Comment by pr1metine** [comment]
So you are saying that I should switch from Docker Desktop to Docker run in WSL?

**Comment by simonferquel** [comment]
No, docker desktop is now capable of running inside wsl2 (in general settings, just enable the wsl2 backend).
From there, you can enable integration with any of your wsl2 distro.

**Comment by pr1metine** [comment]
Ah, thanks.

**Comment by pr1metine** [comment]
wtf. What about solving the original issue in the first place instead of having to rely on a workaround?

**Comment by simonferquel** [comment]
Sorry if it was not clear. We have a fix inbound. It will be released in next edge.

By the way, the approach described here is not a workaround. It is a best practice with wsl2 backend.

**Comment by pr1metine** [comment]
Oh, my bad then.
