### ISSUE TITLE
"DockerCli.exe version" does not output anything

### ISSUE THREAD

**Issue by gillesdouaire** [docker/for-win#6289]
To reproduce
  1. Install Docker for Windows Edge 2.2.3.0
  2. Navigate to "C:\Program Files\Docker\Docker"
  3. Run "DockerCli version"

It outputs nothing.

It used to input something like this:

```
Docker Desktop
Version: 2.2.0.5 (43884)
Channel: stable
Sha1: 758e889f2c543b35d0bdfa51e811744f686d81b3
OS Name: Windows 10 Enterprise
Windows Edition: Enterprise
Windows Build Number: 17763
```

**Comment by mat007** [comment]
Hi @gillesdouaire, sorry for not getting back to you sooner.
`DockerCli` is an internal tool that we never documented and will probably remove at some point in the future.

That being said if you explained a little what you’re looking to do, there might be other ways?

**Comment by gillesdouaire** [comment]
No worries, OK, understood. 

We have an automated build running under Docker Desktop and before the build starts, that was the way to display the Docker Desktop we used in our logs. Any alternate command line displaying the Docker Desktop version would be ok for us.

**Comment by mat007** [comment]
I guess you could do something like
```
PS C:\Users\mathi> (Get-Item -path 'C:\Program Files\Docker\Docker\Docker Desktop.exe').VersionInfo

ProductVersion   FileVersion      FileName
--------------   -----------      --------
2.2.3.0          2.2.3.44359      C:\Program Files\Docker\Docker\Docker Desktop.exe
```
Or there is a JSON file that has is used by Docker Desktop for displaying the about box: `C:\Program Files\Docker\Docker\resources\componentVersion.json` e.g.
```
{
  "Informational": "2.2.3.0",
  "sha1": "384eaeed782ffb9d0870f71fb3a234fbfc6ba77a",
  "ComposeVersion": "1.25.5",
  "NotaryVersion": "0.6.1",
  "CredentialHelpersVersion": "0.6.3",
  "EngineVersion": "19.03.8",
  "CliVersion": "19.03.8",
  "KubernetesVersion": "v1.16.5",
  "VersionPack": "community",
  "Edition": "community",
  "Channel": "edge"
}
```

Does that help?

**Comment by gillesdouaire** [comment]
Yes, thanks, that is helpful. You can close the ticket.
