### ISSUE TITLE
Docker-compose commands perform very slowly

### ISSUE THREAD

**Issue by herecydev** [docker/for-win#629]
I've put a [comment here also](https://github.com/docker/compose/issues/3848) but I'm thinking that this is more targeted to docker for windows.

### Expected behavior

Docker-compose performs quickly, as normal docker commands do.

### Actual behavior

Docker-compose has significant delays when executing commands like `docker-compose ps`. Usually around 100x that of normal docker commands like `docker ps`. The waits seem to occur around the following logs:

```
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=True, filters={u'label': [u'com.docker.compose.project=foo', u'com.docker.compose.oneoff=
False']})
```

or

```
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
```

But it's very difficult to pinpoint the issue. Commands like `docker run` or `docker ps` are completely unaffected.

### Information
Windows 10 Professional
Version 17.03.1-ce-win5 (10743)

I have tried changing the DNS to google's DNS 8.8.8.8 but this hasn't affected the time. Internet connectivity is wired, and experiencing normal, quick responses on the host (windows machine). I'm more than happy to provide more information, but I don't know what else to give.

Factory reset of docker does not help, however uninstalling, deleting hyper-v machines and reinstalling docker completely does help **temporarily**. It will run smoothly until an indeterminate amount of time (usually under an hour) at which point it exhibits the excessive wait times.

**Comment by friism** [comment]
@herecydev could I convince you to run and post diagnostic ids, preferable both before and after you incur the slowdown.

Pinging @shin-

**Comment by herecydev** [comment]
Absolutely, several of us here are seeing the same symptoms and want to help but don't really know what to look for. **Could you advise us what's the best way to get the information you need**. 

Additional information we discovered today: machine restarts help in a similar way to reinstalling docker but for a limited time only. At some *undefined* point, severe performance problems occur, though it seems like frequent activity accelerates the problem. Once again, base docker commands are unaffected but compose is seriously impacted. I've looked for unusual DNS requests using `tcpdump` but there doesn't look like there many requests at all.

CC'ing @smudge202

**Comment by herecydev** [comment]
Yep that's perfect will post back ASAP with some IDs.

**Comment by smudge202** [comment]
Hopefully it's acceptable that I've done this slightly out of order. So my machine had been on for a while and was experiencing the incredibly sluggish `docker-compose` behaviour @herecydev described (`docker-compose ps` took 43 seconds to execute) when I arrived at work this morning. The diagnostic ID at the point it's running slow was `5712F26E-3C2B-4F6D-A5DF-FFCA8BF0B2DC/2017-04-12_08-45-25`.

I'm just going to restart quickly, confirm docker-compose commands are again running at an acceptable speed, and get a second diagnostic.

**Comment by herecydev** [comment]
@friism Was everything okay with those diagnostics? Do you need anything else?

**Comment by ced-b** [comment]
I experienced the same issue, in my case I had an http proxy set on Edge which applied Windows wide. Turning the proxy off immediately speeds up docker-compose. However, I was not able to figure out yet what needs to be added to the proxy bypass to make the system use the proxy and bypass the proxy for docker-compose.

**Comment by herecydev** [comment]
Can confirm there's some proxy magic going on that's causing compose to slow down. In our case, we frequently have to use fiddler and it was causing the slow down. When you shut it down, the compose immediately completes. Hope that helps @friism. I'm still unsure what interaction compose is having with the windows host.

**Comment by sebastiansirch** [comment]
I am experiencing exactly the same issue. docker-compose is basically unusable for me behind a corporate proxy. Here is my support ID: 7CC20D73-F6F6-4838-BAF9-F87958043D04/2017-07-04_20-50-21
Is there a workaround or fix for this issue?

**Comment by borgdrone7** [comment]
Same problem here with Fiddler. Disabling proxy is not a solution.

**Comment by Blizzke** [comment]
Same issue here... `docker-compose up` with proxy enabled - almost 15 minutes, without proxy about 10 seconds.

**Comment by adam66** [comment]
Using Docker on Windows in a corporate secure environment is like being stoned to death. After figuring out a work-around for the inability to create volumes due to the firewall, I've now hit this issue too.

**Comment by andriusjakas** [comment]
Similar here: 

Win10 and using docker-compose, but if i set windows environment variables http_proxy and https_proxy its fast again (probably bypasses windows system proxy)

**Comment by ccrowhurstram** [comment]
I get very slow response times as well, but it's not limited to docker-compose.

For example, `docker ps` takes 20-25 seconds to return even when there are no containers running.

---
**Computer info**

WindowsBuildLabEx                                       : 16299.15.x86fre.rs3_release.170928-1534
WindowsCurrentVersion                                   : 6.3
WindowsEditionId                                        : Professional
WindowsInstallationType                                 : Client
WindowsProductName                                      : Windows 10 Pro
WindowsVersion                                          : 1709

**Comment by wisekingtran** [comment]
I encountered the same issue with
A diagnostic was uploaded with id: D0009917-D217-41C9-B854-915BCD314256/2018-04-03_01-26-09

**Comment by Rene94** [comment]
docker compose up command takes too much time !! how can I solve this?

**Comment by Pvlerick** [comment]
/remove-lifecycle stale

This is still an issue :-(

**Comment by adifatol** [comment]
/remove-lifecycle stale

Slow here also, behind corporate proxy. Removing it is not an option.
Here is a diagnostic I uploaded: 46B0E81C-B47B-4F66-8E72-C33394C0E1A9/2019-06-13_14-52-48

**Comment by niclaslindstedt** [comment]
Also having this issue. Behind corporate firewall.
