### ISSUE TITLE
[WSL2] Symlinks cause error running docker build

### ISSUE THREAD

**Issue by TorelTwiddler** [docker/for-win#6290]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4289FDB2-8D11-4CAA-8F2C-2473FA8C24A1/20200410163907

### Expected behavior
Running `docker build .` in WSL 2 with a symlink in the directory works correctly.

### Actual behavior
Running `docker build .` in WSL 2 with a symlink causes an error.

### Information

  - Windows Version: 10.0.19041
  - Docker Desktop Version: 2.2.0.5 (43884) Stable
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Not virtualized, but running Windows via Mac Bootcamp.

I've narrowed it down to a minimal case, described in the steps below. This is assuming that Docker Desktop has WSL 2 integration set up.

### Steps to reproduce the behavior

  1. Create a new directory with a minimal Dockerfile in it, e.g. `FROM alpine`. (source image doesn't matter)
  2. Create a new file, `touch real.js`.
  3. Create a symlink to the new file, `ln -s real.js link.js`.
  4. Run `docker build .`. Note that an error similar to the following occurs:

```
~/code/test> docker build .
time="2020-04-10T09:50:13-07:00" level=error msg="Can't add file \\\\?\\UNC\\wsl$\\Ubuntu\\home\\toreltwiddler\\code\\test\\link.js to tar: open \\\\?\\U
NC\\wsl$\\Ubuntu\\home\\toreltwiddler\\code\\test\\link.js: The name of the file cannot be resolved by the system."
time="2020-04-10T09:50:13-07:00" level=error msg="Can't add file \\\\?\\UNC\\wsl$\\Ubuntu\\home\\toreltwiddler\\code\\test\\real.js to tar: archive/tar: 
missed writing 7 bytes"
time="2020-04-10T09:50:13-07:00" level=error msg="Can't close tar writer: archive/tar: missed writing 7 bytes"
Sending build context to Docker daemon  1.536kB
Error response from daemon: Error processing tar file(exit status 1): unexpected EOF
```

**Comment by simonferquel** [comment]
It is recommended to run builds and containers from your wsl distro instead of Windows (e.g. put your source in your Ubuntu or wsl distro of choice, and run `docker build` from there). You'll get much better I/O performance, and full Linux filesystem fidelity.

**Comment by TorelTwiddler** [comment]
@simonferquel Sorry for not being clear. The entire project is within the `/home/toreltwiddler/code/test` directory, which is within the Ubuntu distro directories.

**Comment by simonferquel** [comment]
Yes but from error text it seems that the cli invoked is a windows one (paths to the build contexts are unc-style).

**Comment by TorelTwiddler** [comment]
After re-setting up my docker with WSL, it started working again. I'm not sure exactly what was wrong, but I believe I had symlinked `docker` to `docker.exe` or the like, which caused it to use the Windows CLI, as @simonferquel mentioned. Thanks for the help!
