### ISSUE TITLE
Docker push [WindowsDaemon ][Warning] failed to upload schema2 manifest: received unexpected HTTP status: 500 Internal Server Error

### ISSUE THREAD

**Issue by m2web** [docker/for-win#6298]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID:
3770D44F-B877-4C4A-84B8-8C3295893FB9/20200411135800
### Expected behavior
push Docker image to Heroku successfully

### Actual behavior
Log:
[08:36:17.668][ApiProxy          ][Info   ] time="2020-04-11T08:36:17-04:00" msg="Cancel connection..."
[08:36:17.669][WindowsDaemon     ][Warning] failed to upload schema2 manifest: received unexpected HTTP status: 500 Internal Server Error
[08:36:17.670][WindowsDaemon     ][Info   ] Attempting next endpoint for push after error: received unexpected HTTP status: 500 Internal Server Error
[08:36:17.693][ApiProxy          ][Warning] time="2020-04-11T08:36:17-04:00" msg="ignored error: The handle is invalid."
[08:37:17.885][ApiProxy          ][Info   ] time="2020-04-11T08:37:17-04:00" msg="Cancel connection..."
[08:37:17.886][ApiProxy          ][Info   ] time="2020-04-11T08:37:17-04:00" msg="proxy >> GET /v1.40/events\n"
[08:37:17.888][ApiProxy          ][Info   ] time="2020-04-11T08:37:17-04:00" msg="proxy << GET /v1.40/events (5m0.0034288s)\n"
[08:37:17.892][WindowsDaemon     ][Info   ] debug: Client context cancelled, stop sending events

### Information
  - Powershell Version: 5.1.19041.1
  - Windows Version: 10.0.19041 Build 19041
  - Docker Desktop Version: v19.03.8
  
### Steps to reproduce the behavior
I produce the error running the following from the Powershell CLI:

1. From Powershell CLI: PS C:\Users\MARKMCFADDEN\Source\Repos\dotnet\prayerapi\prayerapi> **dotnet publish -c Release**
Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
  Restore completed in 67.11 ms for C:\Users\MARKMCFADDEN\Source\Repos\dotnet\prayerapi\prayerapi\prayerapi.csproj.
  prayerapi -> C:\Users\MARKMCFADDEN\Source\Repos\dotnet\prayerapi\prayerapi\bin\Release\netcoreapp3.1\prayerapi.dll
  prayerapi -> C:\Users\MARKMCFADDEN\Source\Repos\dotnet\prayerapi\prayerapi\bin\Release\netcoreapp3.1\publish\

2. PS C:\Users\MARKMCFADDEN\Source\Repos\dotnet\prayerapi\prayerapi> **docker build -t prayerapi.dll ./bin/Release/netcoreapp3.1/publish**
Sending build context to Docker daemon  23.79MB
Step 1/4 : FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
3.1: Pulling from dotnet/core/aspnet
8e709836e4dc: Pull complete
6dbb4bb89742: Pull complete
b417bb8428e6: Pull complete
ca532727f6e1: Pull complete
71374f5435b3: Pull complete
500d8f38a1d7: Pull complete
d77a7ec1547c: Pull complete
Digest: sha256:31355469835e6df7538dbf5a4100c095338b51cbe52154aa23ae79d87585d404
Status: Downloaded newer image for mcr.microsoft.com/dotnet/core/aspnet:3.1
 ---> dc28376d4369
Step 2/4 : WORKDIR /app
 ---> Running in 6bb63d1eea94
Removing intermediate container 6bb63d1eea94
 ---> 2918cd8a58ad
Step 3/4 : COPY . .
 ---> 054e2d37a0e7
Step 4/4 : CMD ASPNETCORE_URLS=http://*:$PORT dotnet prayerapi.dll
 ---> Running in 92af4f8db116
Removing intermediate container 92af4f8db116
 ---> a3206144fb9e
Successfully built a3206144fb9e
Successfully tagged prayerapi.dll:latest

3. PS C:\Users\MARKMCFADDEN\Source\Repos\dotnet\prayerapi\prayerapi> **docker tag prayerapi.dll:latest registry.heroku.com/dailyprayerapi/web**

4. PS C:\Users\MARKMCFADDEN\Source\Repos\dotnet\prayerapi\prayerapi> **docker push registry.heroku.com/dailyprayerapi/web**
The push refers to repository [registry.heroku.com/dailyprayerapi/web]
20b5d1017783: Pushed
2c65027d92e6: Pushed
e7e2868f4904: Pushed
ab1144ee21e6: Pushed
7f30fc0f479f: Pushed
c8f0f680d6d5: Pushed
b384ebea5925: Pushed
fb5b5108dec9: Pushed
1f10b6910472: Pushed
cea17d6bca65: Skipped foreign layer
*received unexpected HTTP status: 500 Internal Server Error*

**Comment by m2web** [comment]
Anyone...anyone...Bueller?

**Comment by mat007** [comment]
Hi @m2web,

This doesn’t look like an issue with Docker Desktop, does it?
Moreover as your pushing to the Heroku registry it’s outside Dockers’ reach, have you tried contacting them?

**Comment by m2web** [comment]
@mat007, Thanks for the response. While I agree that this is likely a Heroku issue. I was hoping that someone else ran across this same issue. In short, given that I am using this for learning purposes and it is a free Heroku app, I cannot submit a support ticket.
