### ISSUE TITLE
Mount shared folders as a different user

### ISSUE THREAD

**Issue by greut** [docker/for-win#63]
### Expected behavior

A mounted volume rights can be changed.

It doesn't seem that Windows shares allows this at runtime. Would it be possible to give a UID/GID pair from the UI (or JSON config) to enable this kind of behaviour from the Mobylinux VM?

```
# mount -t cifs ... /c -o username=...,password=...,uid=$UID,gid=$GID,...
```
### Actual behavior

Mounted volumes belong to `root`
### Information

https://forums.docker.com/t/mounting-a-volume-as-non-root-from-windows/17548/2
### Steps to reproduce the behavior
1. `$ docker run --rm -it -v c:/Users/Me:/data ls -l /data`
   -rwxr-xr-x 1 root root 22299 ...

**Comment by rneugeba** [comment]
@greut thanks for the suggestion. My main concern is that if you run multiple containers than they all have to agree on the acceptable userid/groupid. Of course that is true now as well.

Could you give an example of something which complains about root being the default?

Would it work, if we hard code a different userid/groupid?

**Comment by greut** [comment]
[composer](https://getcomposer.org/) is one of those tools, but it's not a blocker.

```
Do not run Composer as root/super user! See https://getcomposer.org/root for details
```
https://getcomposer.org/doc/faqs/how-to-install-untrusted-packages-safely.md

`1000:1000` or `1000:100` seems like good default values to me.

**Comment by moleCuleFFF** [comment]
Apache is a good case point, as Apache runs as user and group www-data:www-data it cannot write to named volumes. Basically making Drupal development on docker a real PITA due to its directory structure.

I think this will be one of the most requested features, the best way to manage this would be to allow you to declare a uid:gid per volume euither in docker-compose if your using it or Dockerfile

**Comment by vbarinov** [comment]
This problem stops me from using Docker for web development from the Windows host. Apache/php should not run from `root`. Any status?

**Comment by friism** [comment]
I think this is related to the same CIFS/Samba limitation as here: https://github.com/docker/for-win/issues/39

Closing this issue.

**Comment by greut** [comment]
@friism the problem isn't only that you cannot chown on a CIFS mounted folder. You cannot set a different uid/gid for the mounted folder but root's.

**Comment by rneugeba** [comment]
@greut This is a limitation of CIFS/SMB and there is little we can do about this. The uid/gid are basically global for all containers. We could potentially offer a configuration option to mount with a different uid/gid. Would that help?

**Comment by greut** [comment]
@meugeba you suggestion was part of the initial request indeed. `-o uid=$UID,gid=$GID`

**Comment by h3rj4n** [comment]
+1

**Comment by glinton** [comment]
+1

**Comment by gvenzl** [comment]
Hi everybody, we are facing this issue again with Oracle Database running on a Windows container. Oracle expects certain files to be owned by the user running the database for security purposes. The user has to be other than `root` and is usually `oracle`.

I'm wondering whether the above suggestion of using a configuration option to mount with a different uid/gid on Windows is already available? Any insights, @rn?
