### ISSUE TITLE
[WSL2] Mounted SMB Global Mapping results in container incorrectly storing data in WSL2 VM

### ISSUE THREAD

**Issue by riverar** [docker/for-win#6307]
Windows 10 10.0.19041.153
Docker version 19.03.8, build afacb8b

- [x] I have tried with the latest version of my channel (Stable or Edge)
- [ ] I have uploaded Diagnostics
  - Diagnostics ID: N/A - Cannot provide for privacy reasons.

### Expected behavior
Docker mounts the location in the container, as it does with other paths. This worked in LCOW.

### Actual behavior
Docker mounts the location in the container, however it is not wired correctly to the host machine, therefore data does not get read or written to the SMB global mapping target. Instead, the data ends up in the `docker-desktop` VM's filesystem (e.g. `/mnt/host/uC/mapping-target-hostname/`).

### Repro steps

Requirements:
* Windows host
* Docker CE Edge, with WSL2 integration enabled
* A shared SMB location

On the Docker Windows host with WSL2 integration enabled...

1. Open PowerShell and create a SMB global mapping:
```powershell
New-SmbGlobalMapping -LocalPath M: -RemotePath \\Machine\SharedLocation -Persistent 
$true -UseWriteThrough $true -Credential (Get-Credential)
```
2. In the same PowerShell window, write a test file to the mapped location:
```powershell
New-Item C:\Mount\from-host.txt
```
3. Verify this file was written to the remote server by browsing to `\\Machine\SharedLocation` using File Explorer.
4. Start a linux container, mount the local (global mapping target) path, and list contents of mounted location:
```
docker run --rm -it -v M:\:/tmp/mount alpine:latest ls /tmp/mount/
```
5. Observe location is empty
6. Start a linux container, mount the local (global mapping target) path, and write a test file:
```
docker run --rm -it -v M:\:/tmp/mount alpine:latest touch /tmp/mount/from-container.txt
```
7. Start a linux container, mount the local (global mapping target) path, and list contents of mounted location:
```
docker run --rm -it -v M:\:/tmp/mount alpine:latest ls /tmp/mount/
```
8. Observe location only has `from-container.txt`.
9. Verify `from-container.txt` was not written to the remote server by browsing to `\\Machine\SharedLocation` using File Explorer.

**Comment by simonferquel** [comment]
cc @benhillis. Actually the issue is a combination of 3 things:
- WSL only expose local drives (from your own wsl distro, I suppose you don't see any /mnt/m mount point either ?). 
- docker desktop only validates that the bind source is reachable from the windows side for allowing creating containers with windows bind mounts
- docker engine automatically create source directory on container creation if the file or directory does not exist.

As a workaround, I suggest that instead of mounting the samba share from windows, you do that in your own distro using cifs tools. Then you can use docker CLI from your wsl distro to access the network share.

**Comment by riverar** [comment]
Shouldn't the Docker bootstrapping distro mount the shares in such a way that Docker can access them? Or did I misunderstand [this post](https://www.docker.com/blog/new-docker-desktop-wsl2-backend/)?

> The bootstrapping distro also manages things like mounting the Windows 9p [sic] shares in a place that can be accessed by the Linuxkit container (to avoid using Samba for sharing Windows files with containers), and controls the lifecycle of the Linuxkit container (ensuring clean shutdown etc.).

Where does the above functionality live? I've been trying to find this digging around in the bootstrapping distro.

**Comment by simonferquel** [comment]
What the blog post means, is that we bind mount the 9p mountpoints where WSL mounts your local drive into the linuxkit environment. But WSL does not mount your network drives, only the local drives.

**Comment by riverar** [comment]
@simonferquel Thanks. I'm trying to track down who's creating the `/mnt/host/uC/mapping-target-hostname/`. The `uC` in particular is interesting as it appears some component is at least trying to support network locations.

**Comment by riverar** [comment]
I attempted to use the suggested workaround to no avail.

Workaround failure repro:
1. In WSL2-enabled distro, execute `sudo mount -t cifs \\\\server\\share /mnt/location -o user=username,pass=password`
2. Observe location is mounted and contains files (`ls /mnt/location`)
3. Launch container (`docker run --rm -it -v /mnt/location:/tmp/test alpine:latest`)
4. Observe container starts without error, location is mounted, but contains no files (`ls /tmp/test`)

**Comment by simonferquel** [comment]
This one is a bug. I'll need to look at this.

**Comment by simonferquel** [comment]
Hmm, actually I could not reproduce :/

**Comment by riverar** [comment]
@simonferquel Will take another look at this. Did you test this exactly as listed above? Did you use a SMB share hosted on another box or cheat and use a local share?

**Comment by simonferquel** [comment]
I used a share I created on the windows host

**Comment by LukasVice** [comment]
> I attempted to use the suggested workaround to no avail.
> 
> Workaround failure repro:
> 
> 1. In WSL2-enabled distro, execute `sudo mount -t cifs \\\\server\\share /mnt/location -o user=username,pass=password`
> 2. Observe location is mounted and contains files (`ls /mnt/location`)
> 3. Launch container (`docker run --rm -it -v /mnt/location:/tmp/test alpine:latest`)
> 4. Observe container starts without error, location is mounted, but contains no files (`ls /tmp/test`)

I had the same problem with Docker Desktop Edge 2.3.01. I installed Docker Desktop Stable 2.2.0.5 and it worked fine. Then I reinstalled Docker Desktop Edge and the problem was gone - I can't reproduce it right now...

**Comment by LukasVice** [comment]
If you start the container without first mounting the CIFS directory locally, you will get an empty folder in the container (this is understandable). If you then mount the CIFS directory locally and start a new container, you will get an empty folder again. But after restarting Docker and starting a new container, the correct files of the mounted CIFS directory are available.

**Comment by riverar** [comment]
I still have 100% repro on this, even with the local share.

@simonferquel can you re-test carefully? Did you deviate from the provided repro?

**Comment by simonferquel** [comment]
Just retried with success now on win 10 build 19041.
If you do the share from the same machine, please note that the ip of the windows host is different from the ip of the WSL utility VM. (and that trying to access the share from \\\\<machine name>\\ in wsl will fail as the host name of the wsl distro is the same as the windows one (so it will resolve to localhost). 

So you need to reference the network share using the IP of your windows host.

**Comment by riverar** [comment]
@simonferquel Not sure what you're doing differently but I can repro with a Windows smb location and a Linux (via Samba) smb location. I guess the next step is for me to repro this in a VM and rule out all my machines.

**Comment by tylerohlsen** [comment]
> I attempted to use the suggested workaround to no avail.
> 
> Workaround failure repro:
> 
> 1. In WSL2-enabled distro, execute `sudo mount -t cifs \\\\server\\share /mnt/location -o user=username,pass=password`
> 2. Observe location is mounted and contains files (`ls /mnt/location`)
> 3. Launch container (`docker run --rm -it -v /mnt/location:/tmp/test alpine:latest`)
> 4. Observe container starts without error, location is mounted, but contains no files (`ls /tmp/test`)

Are you running step #3 from a command prompt on the Windows host or from your WSL2 distribution terminal window?

**Comment by msrlrocket** [comment]
I seem to be having this issue. is there anyway to fix other than sharing out your directory and reconnecting to it? for some reason it feels like a split brain kinda issue

**Comment by sirfuzzalot** [comment]
> If you start the container without first mounting the CIFS directory locally, you will get an empty folder in the container (this is understandable). If you then mount the CIFS directory locally and start a new container, you will get an empty folder again. But after restarting Docker and starting a new container, the correct files of the mounted CIFS directory are available.

Thanks! This worked for me executing `docker-compose` and `docker container run` inside WSL2 shell.

- Externally hosted network share mounted to WSL2 VM via `cifs` `ver=3.0` .
- Share connected to container through volume.

```bash
docker run -it -v /mnt/g:/mnt/g node:14.10.0-buster-slim bash -c "ls -l /mnt/g"
```

- Windows 2004 - 19041.264
- Ubuntu 20.04.1 LTS (Focal Fossa)
- Docker Desktop Stable - 2.3.0.0 (48506)

**Comment by doug62** [comment]
I have the same problems with Docker 3
