### ISSUE TITLE
Issue with concurrent creating symlinks on volumes

### ISSUE THREAD

**Issue by whitecolor** [docker/for-win#631]
Steps to reproduce
1) create directory with folders `dir1` and `dir2`
2) create file `link.js`:
```js
const fs = require('fs')

const link1 = '/app/dir1/app'
const link2 = '/app/dir2/app'

try { fs.unlinkSync(link1) } catch (e) { }
try { fs.unlinkSync(link2) } catch (e) { }

// first param can be any target folder
fs.symlink('/bin', link1, console.log)
fs.symlink('/bin', link2, console.log)
```
2) in this directory in shell run `docker run --rm -v "%CD%:/app" -it -w /app mhart/alpine-node:7.8.0 sh`
3) inside container run `node link.js`
4) run multiple times you should see the error:
```
{ Error: EINVAL: invalid argument, symlink '/bin' -> '/app/dir2/app'
  errno: -22,
  code: 'EINVAL',
  syscall: 'symlink',
  path: '/bin',
  dest: '/app/dir2/app' }
```

If to create links in the same directory, there would be no errors.

This issue relates to yarn https://github.com/yarnpkg/yarn/pull/3097

**Comment by friism** [comment]
This is probably related to other symlink-emulation related problems: https://github.com/docker/for-win/issues/137

**Comment by whitecolor** [comment]
regarding this issue, there is a general question: is it possible to determine the we are currently running container under docker for windows? (in general case)

@friism

**Comment by friism** [comment]
> is it possible to determine the we are currently running container under docker for windows

@whitecolor no, I don't think so - is this because you'd want to special-case running in Docker for Windows?

**Comment by whitecolor** [comment]
Yes this question is discussed in this issue https://github.com/yarnpkg/yarn/pull/3097

**Comment by rn** [comment]
closing as this seems to be:
- a more general issue with SMB mounts (as per the yarm link)
- possibly fixed in yarn
- a very old issue
