### ISSUE TITLE
docker desktop crashes seconds after start

### ISSUE THREAD

**Issue by hvojdani** [docker/for-win#6312]
-  I have tried with the latest version of my channel (Stable or Edge)
  -  I have uploaded Diagnostics
  - Diagnostics ID: 5E739ACF-EE07-4399-833C-2CA54208FDAB/20200412182316

docker desktop  edge: 2.2.3.0
windows 10 version :  2004 build 19603-1000
wsl2 enabled, kubernete enabled

### Actual behavior
docker desktop does not start normally and after some seconds it will terminate by os.

after 2 or 3 attempt it works and does not quit.

### Information
same error repeated on event log:

`Application: Docker Desktop.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Docker.ApiServices.Registries.DockerHub+<ValidateBasicCredentialsAsync>d__26.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Docker.ApiServices.Registries.DockerHub+<LogIn>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Docker.ApiServices.Registries.DockerHub+<AutoLogIn>d__16.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

`

**Comment by mat007** [comment]
Thanks for the report, I’m trying to work out where this might crash.

Are you logged in? Did you activate 2FA on Docker Hub?

**Comment by hvojdani** [comment]
> Are you logged in? Did you activate 2FA on Docker Hub?

yes,
and i don't activated 2FA

**Comment by mat007** [comment]
If you log out from Docker Hub and restart, does it still crash?

**Comment by mat007** [comment]
It’s hard to understand what is happening, I made a change to the code to try and grasp things better and created a private build, would you mind giving it a go?
https://download-stage.docker.com/win/edge/44456/Docker%20Desktop%20Installer.exe

**Comment by hvojdani** [comment]
> If you log out from Docker Hub and restart, does it still crash?

i tried and started well, 
had some ideas and tested them all but i am not facing the error for 2 days. :/

does high memory usage while docker is running (about 85%) effect on this situation? 

> It’s hard to understand what is happening, I made a change to the code to try and grasp things better and created a private build, would you mind giving it a go?

As soon as I hit it again, i will try.

thank you 👏

**Comment by mat007** [comment]
> i tried and started well,

OK, at least it means I vaguely see which area of the code this is coming from.

> does high memory usage while docker is running (about 85%) effect on this situation?

Not directly but maybe it delays some of the startup procedures that perform I/O and you’re triggering a race in the code somehow.

🤔

**Comment by hvojdani** [comment]
finaly solved in new release
tested this and crashed exactly when i have no internet connection 
> 2.3.0.1 (44875)
This is the Edge channel, which gives you early access to our newest features. Be aware that some of them may be experimental, and some of them may not ever reach the Stable release.
Bug fixes and minor changes 
Fixed an upgrade bug where users on versions still using the Powershell based VM management experience a silent un-installation crash leading to Docker Desktop being uninstalled instead of upgraded. 
**Fixed a crash when failing to login due to no Internet connection.** 
Fixed bug in handling shared volume paths with ".." characters. Fixes docker/for-win#5375. 
WSL 2: Docker Desktop detects when the wsl-distro is stopped and displays an actionable error message. 
Fixed a bug in ftruncate which prevented libgit2sharp from cloning repositories on shared volumes. See docker/for-win#5808. 
Fixed a bug that caused starting and stopping of a Compose application from the UI to fail when the path contains whitespace.

**Comment by mat007** [comment]
Nice! Thanks for letting us know. 😁
