### ISSUE TITLE
WORKDIR not able to create directory.

### ISSUE THREAD

**Issue by ameya-lab** [docker/for-win#6314]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:C6AF9E48-AF35-4CD0-B377-AE72C85FA8C5/20200413070137

### Expected behavior
Create a directory
### Actual behavior
WORKDIR not able to create directory
### Information

  - Windows Version: 10 PRO
  - Docker Desktop Version:
$ docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: HyperV

### Steps to reproduce the behavior

FROM node:alpine

WORKDIR /app

COPY package.json .
RUN npm install -g npm

COPY . .

CMD ["nmp" , "run" , "start"]

  1. ...
  2. ...

Getting the below error -

web_1  | internal/modules/cjs/loader.js:979
web_1  |   throw err;
web_1  |   ^
web_1  |
web_1  | Error: Cannot find module '/app/nmp'
web_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
web_1  |     at Function.Module._load (internal/modules/cjs/loader.js:859:27)
web_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
web_1  |     at internal/main/run_main_module.js:17:47 {
web_1  |   code: 'MODULE_NOT_FOUND',
web_1  |   requireStack: []

**Comment by mat007** [comment]
I don’t think this is a problem with the container or at least definitely not with Docker Desktop.
It looks to me as if `npm install -g npm` is failing.
