### ISSUE TITLE
Unable to increase RAM for 'DockerDesktopVM' beyond 50% of Total RAM of Host Machine

### ISSUE THREAD

**Issue by Mahes-P** [docker/for-win#6323]
Diaggnostics ID: B1121943-7E84-4510-87AC-B582EE819702/20200414084226
I have uploaded Diagnostics.
  - Windows Version: Windows 10 Pro
  - Docker Desktop Version:2.2.0.5
  - Docker is running on Hyper-V of Windows 10 , in Linux Container mode.

### Steps to reproduce the behavior
1.  On Hyper-V Manger--> Select 'DockerDesktopVM' --> On right side 'DockerDesktopVM' section select 'Settings'--> it will open a new window, there select Memory and increase Memory to 40GB ( as host machine has 64GB of RAM)-->Click on Apply/Ok--> It fails.

2. On Windows task bar --> Right Click on 'Docker' icon --> Settings--> Resources--> Advanced--> Increase RAM size by dragging the bar to 40GB --> then 'Apply & Restart'--> It completes, but still VM RAM size is not increasing.

I am able to allocate maximum of around 32GB of RAM (i.e. 50% of HOST machine RAM)  to this Docker VM, beyond this it is not allocated to VM.

Kindly help on this.

Expected to allocate approximately 40 to 50GB of RAM to this DockerDesktopVM.

**Comment by mat007** [comment]
Could it be similar to #5881?

**Comment by innovationatgalaxy** [comment]
I am reporting about RAM size not about Hard Disk.

**Comment by mat007** [comment]
What does
> It completes, but still VM RAM size is not increasing.

mean exactly?

**Comment by innovationatgalaxy** [comment]
Here, i 'completes' i mean i am able to increase RAM size on Docker UI, but it is not reflecting for VM.

> What does
> 
> > It completes, but still VM RAM size is not increasing.
> 
> mean exactly?

**Comment by mat007** [comment]
> On Hyper-V Manger--> Select 'DockerDesktopVM' --> On right side 'DockerDesktopVM' section select 'Settings'--> it will open a new window, there select Memory and increase Memory to 40GB ( as host machine has 64GB of RAM)-->Click on Apply/Ok--> It fails.

What is the error message?

**Comment by Tall-Paul** [comment]
same as https://github.com/docker/for-win/issues/2514 ?

**Comment by Mahes-P** [comment]
> same as #2514 ?

seems to be.. but i do not think its related to CPU in my case
