### ISSUE TITLE
Linux docker on Windows machine startup issue: Docker desktop service is not running

### ISSUE THREAD

**Issue by wefewwe211321** [docker/for-win#6332]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:BAFF4418-27A3-46DF-8D89-783C12E4D29A/20200415044513

### Expected behavior
Upon rebooting computer docker should auto start.
1 app is set for "restart unless stopped"
### Actual behavior
"Docker desktop service is not running would you like to start it? Windows will ask you for elevated access"
I must manually click this every time I restart my computer or it won't work
### Information

I've tried checking windows services, everything seems fine. Set process to auto restart if the "Docker Desktop Service" fails
  - Is it reproducible?
Always
  - Is the problem new?
Always been there for me
  - Did the problem appear with an update?
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.

  - Windows Version: 10 PRO
  - Docker Desktop Version: 19.03.8
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mat007** [comment]
Thanks for the report.

What do the properties of the «Docker Desktop Service» look like, it the «Startup type» set on automatic?

![image](https://user-images.githubusercontent.com/2386884/79303464-48176e00-7eef-11ea-89ae-7af83fe62e45.png)

**Comment by wefewwe211321** [comment]
![image](https://user-images.githubusercontent.com/53066699/79358278-3b4e4680-7efe-11ea-9e47-dd669691c196.png)

I previously had it set to normal automatic, trying out delayed start just to see what happens. Don't think it worked

**Comment by mat007** [comment]
It should be on just «Automatic».

Is there anything in the Windows Event Viewer around the time you start your system which may relate to the Docker Desktop Service?

**Comment by wefewwe211321** [comment]
I did the factory reset option within docker to see if that would fix it, it has not.

Ahh yes it looks like there is a log that basically just says it failed to [start](`url`)
[Dockerservice.zip](https://github.com/docker/for-win/files/4482821/Dockerservice.zip)

**Comment by mat007** [comment]
What about `C:\ProgramData\DockerDesktop\service.txt`?

**Comment by wefewwe211321** [comment]
Here is what that files shows

Version: 2.2.0.5 (43884)
Channel: stable
Sha1: 758e889f2c543b35d0bdfa51e811744f686d81b3
Started on: 2020/04/15 11:23:02.196
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 1909
Build: 18363
BuildLabName: 18362.1.amd64fre.19h1_release.190318-1202
File: C:\ProgramData\DockerDesktop\service.txt
CommandLine: "C:\Program Files\Docker\Docker\com.docker.service"
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[10:02:12.737][NamedPipeServer   ][Info   ] app/version()
[10:02:12.738][NamedPipeServer   ][Info   ] app/version done in 00:00:00.0009206.
[10:02:12.741][NamedPipeServer   ][Info   ] filesharing/get-protocol()
[10:02:12.742][APIRequestLogger  ][Info   ] [c16176b3] <GoBackendClient start> GET http://localhost/features
[10:02:12.747][GoBackendProcess  ][Info   ] time="2020-04-18T10:02:12-06:00" msg="external: GET /features 200 \"\" \"\""
[10:02:12.764][APIRequestLogger  ][Info   ] [c16176b3] <GoBackendClient end> GET http://localhost/features -> 200 OK (took 22ms)
[10:02:12.764][NamedPipeServer   ][Info   ] filesharing/get-protocol done in 00:00:00.0229573.
[10:02:13.200][ApiProxy          ][Info   ] time="2020-04-18T10:02:13-06:00" msg="proxy >> HEAD /_ping\n"
[10:02:13.203][ApiProxy          ][Info   ] time="2020-04-18T10:02:13-06:00" msg="proxy << HEAD /_ping (1.9961ms)\n"
[10:02:13.220][ApiProxy          ][Info   ] time="2020-04-18T10:02:13-06:00" msg="proxy >> GET /v1.40/info\n"
[10:02:13.250][ApiProxy          ][Info   ] time="2020-04-18T10:02:13-06:00" msg="proxy << GET /v1.40/info (30.1674ms)\n"
[10:02:15.085][ApiProxy          ][Info   ] time="2020-04-18T10:02:15-06:00" msg="proxy >> HEAD /_ping\n"
[10:02:15.090][ApiProxy          ][Info   ] time="2020-04-18T10:02:15-06:00" msg="proxy << HEAD /_ping (5.0439ms)\n"
[10:02:15.125][ApiProxy          ][Info   ] time="2020-04-18T10:02:15-06:00" msg="proxy >> GET /v1.40/version\n"
[10:02:15.136][ApiProxy          ][Info   ] time="2020-04-18T10:02:15-06:00" msg="proxy << GET /v1.40/version (10.9741ms)\n"

**Comment by wefewwe211321** [comment]
I tried doing a full uninstall and reinstall with deleting that folders as well as those in program files.
Issue is still present even with no changes to docker or anything

**Comment by mat007** [comment]
It seems there is something that prevents the service from starting on boot…
Is this your personal machine or is it managed by you company IT department?

**Comment by wefewwe211321** [comment]
It is a personal machine. Fairly fresh build of windows 10 Pro edition.
I'll try the DISM and SFC to see if it's all proper.

**Comment by wefewwe211321** [comment]
Didn't help. Are we able to escalate this? 
Did you take a look at the diagnostics and notice anything?

**Comment by StefanScherer** [comment]
I have a machine on which I can reproduce the problem.

- Hardware: DELL E6430 laptop with a spinning disk (no SSD), Intel i5, 4GB RAM
- Software: Windows 10 Pro v2004, fresh installed, only updated MS Edge and installed DD 2.3.0.2 Stable, and installed Ubuntu 20.04 WSL 2 distro. It's a DELL laptop with a spinning disk.

I once switched to Windows Containers, back to Linux Containers. 

After about two reboots I now see the popup "Docker desktop service is not running would you like to start it? Windows will ask you for elevated access" on every reboot.

- Diagnostics ID: FA2F1B44-5136-4051-A929-1C216A76137B/20200526213353

At one boot I opened the Ubuntu shell very quickly (login and as soon as the task bar showed the icon I double clicked it, DD wasn't even started), entered the first commands, then it disappeared. Opening the Ubuntu shell again I got an "Error: 0xffffffff Press any key to continue..." error.

- Diagnostics ID: FA2F1B44-5136-4051-A929-1C216A76137B/20200526214240

This happened only once, but the further reboot still show the "Service is not running" popup.
Then I've captured the boot with Process Monitor and also saw two AppCrash reports in C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Docker Desktop.* which I have attached here:

[boot-and-appcrash.tar.gz](https://github.com/docker/for-win/files/4687015/boot-and-appcrash.tar.gz)
