### ISSUE TITLE
Error when running Docker desktop on Windows 10 hosted in VirtualBox

### ISSUE THREAD

**Issue by MichaelKnight** [docker/for-win#6339]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
Also, Docker Desktop is not supported in a virtualised environment. Sometimes it works, sometimes it doesn't. This is not because of us, it's whether Hyper-V can run in the virtualised environment, which is not under our control.
