### ISSUE TITLE
Docker won´t start automatically

### ISSUE THREAD

**Issue by marpinello** [docker/for-win#634]
### Expected behavior

Docker to start automatically with windows start

### Actual behavior
It gets a error message

### Information
This issue is similar to #271 but in that case everybody is sayng that the issue is related to some kind of VM installation, which is not the case here
it is a normal windows 10 Pro, installed in a real notebook.
After windows has started normally, I restart Docker by the settings>Reset>Restart Docker menu and it is all fine.

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
95BF0225-19EB-4169-93FA-F36026869213/2017-04-12_09-09-34

  - host distribution and version (Windows version, build number, etc)
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      14393  0

### Steps to reproduce the behavior

  1. ...start Docker for Windows
  2. ...wait the error to occur

**Comment by samarth202** [comment]
Same error , Running Docker on Windows Host using Parallels with nested virtualization enabled.

Diagnostic ID : 3A18DADB-9EEF-4C23-9A63-78DD1A7A10AB/2017-04-26_13-37-27

Host Distribution and version : 
10 0 14393 0

**Comment by gabrielbrancolini** [comment]
I was close to recommend this product in the company I work for, but I do have the very same issue and I can see that no one has fixed this. Hope you have good luck.
