### ISSUE TITLE
Running windows docker from WSL [Feature Request]

### ISSUE THREAD

**Issue by mariotoffia** [docker/for-win#635]
### Expected behavior
I've got WSL on my win 10 machine and I do like to fire up the windows docker.exe and thus communicate with the windows docker daemon. I would like to have a docker bin/bash shell installed with the docker installation since it is on my path.

Is this possible to provide with your distribution.
### Actual behavior
Must specify docker.exe.

### Information
```#!/usr/bin/env bash
##
# Taken from vs code startup script
#

NAME="docker"
DOCKER_PATH="$(dirname "$(dirname "$(realpath "$0")")")"
DOCKER="$DOCKER_PATH/bin/$NAME.exe"
if grep -q Microsoft /proc/version; then
        "$DOCKER" "$@"
        exit $?
fi
"$DOCKER" "$@"
exit $?```

**Comment by friism** [comment]
@mariotoffia do you have a link to the source code where VSCode does this?

**Comment by mariotoffia** [comment]
I found it in the installation directory on my windows machine - but it is on GitHub as well:
[code.sh](https://github.com/Microsoft/vscode/blob/master/resources/win32/bin/code.sh).

In the windows _"Program Files (x86)/Microsoft VS Code/bin/"_ they've removed the extension _.sh_ therefore named _"Program Files (x86)/Microsoft VS Code/bin/code"_
