### ISSUE TITLE
Docker is not start on Windows 10 Pro 

### ISSUE THREAD

**Issue by BPSah-50** [docker/for-win#6358]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 5CB74C52-B49C-4341-8580-F4C0330F6B34/20200417090544

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...
![image](https://user-images.githubusercontent.com/38720236/79553425-169ece00-80ba-11ea-97fb-4327c0ae293b.png)

![Screenshot_1](https://user-images.githubusercontent.com/38720236/79553599-59f93c80-80ba-11ea-9da6-b4748597d0e4.png)

**Comment by BPSah-50** [comment]
please fix this issue.

**Comment by nerjamartin** [comment]
Disabling and re-enabling Hyper V again solved the problem in my case. I hope it helps you.

**Comment by BPSah-50** [comment]
Sorry,

I have doing Disabling and re-enabling Hyper V again but problem
not solved.

Please help me.

Bishwa

**Comment by nerjamartin** [comment]
Just to be sure, do you make this ? ->

1. disable hyper v
2. restart
3. enable hyper v
4. restart
5. launch docker c.e. for windows

That was my "solution-workflow". Hope this works.

Good luck!!

________________________________________
De: BPSah-50 <notifications@github.com>
Enviado: viernes, 17 de abril de 2020 13:34
Para: docker/for-win
Cc: Antonio J Martin; Comment
Asunto: Re: [docker/for-win] Docker is not start on Windows 10 Pro  (#6358)

Sorry,

I have doing Disabling and re-enabling Hyper V again but problem
not solved.

Please help me.

Bishwa

**Comment by BPSah-50** [comment]
I have also followed to given your step but problem not solved.



Bishwa

**Comment by LordEvron** [comment]
For me it worked!

**Comment by LordEvron** [comment]
For me it worked!

**Comment by BPSah-50** [comment]
Sorry.

Not working in my system. Help me!



Bishwa

**Comment by Richard-Barrett** [comment]
Try this:

Try this, I had the same issue:
So I was actually able to solve it by doing the following:

Enter The following commands within an elevated command prompt:
```
Enable Hyper V - You can do this by running the following command as administrator. - dism.exe /Online /Enable-Feature:Microsoft-Hyper-V /All

Enable Hypervisor with following command - bcdedit /set hypervisorlaunchtype auto
```
Research: https://dotnetthoughts.net/hardware-assisted-virtualization-and-data-execution-protection-must-be-enabled/

Then Restart and prompt asks to download the Linux Kernel

Apparently Docker Desktop is forgetting this in their initial set-up for the updates and installation for anybody using Hyper-V and the Linux Containers requiring the WSL2 Linux Kernel Backend to initialize Containers. provided by Microsoft.

Microsoft Link: https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel

Download the above ^^

Stackoverflow Link: https://stackoverflow.com/questions/59413071/error-message-for-hyper-v-and-data-execution-for-docker-desktop-on-windows-10-fa/59653039#59653039

You need to Download wsl2-kernel. 
Similar Github Issue: https://github.com/docker/for-win/issues/6689
