### ISSUE TITLE
Linux container in windows 10

### ISSUE THREAD

**Issue by karthiickk** [docker/for-win#6359]
>> docker pull hello-world
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by mat007** [comment]
Do you use a proxy?

**Comment by karthiickk** [comment]
> Do you use a proxy?

Actually I am using office network.I can able to use windows containers but I cannot able to access Linux containers.i want change the proxy settings

**Comment by mat007** [comment]
Have you set the proxy in the Docker Desktop settings?
