### ISSUE TITLE
Docker run -u

### ISSUE THREAD

**Issue by nou2** [docker/for-win#636]
Hi,

I am currently facing a problem with Docker on Windows while using the -u option.

### Expected behavior

According to the [documentation](https://docs.docker.com/engine/reference/run/#user):

> When passing a numeric ID, the user does not have to exist in the container.
>-u="", --user="": Sets the username or UID used and optionally the groupname or GID for the specified command.

So running:

`docker run -it -u 400:401 some_image` _should_ work.

I am a Windows noob so I am not sure if uid / gid have any sense here but the docker run documentation does not say anything so... If you're wondering why -u 400:401 it's because it's an options that is prepended by a plugin in jenkins while running a container to execute  build steps in it. Same command line works on Linux.

### Actual behavior

The command fails with:

`C:\Program Files\Docker\docker.exe: Error response from daemon: container ID encountered an error during CreateProcess: failure in a Windows system call: The user name or password is incorrect. (0x52e)`

In the extra information you can see:

`"User":"400:401"`

As I said, noob here, but looks like the uid:gid is interpreted as a username ?

### Information

>Containers: 10
Running: 1
Paused: 0
 Stopped: 9
Images: 24
Server Version: 17.03.0-ee-1
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.953.amd64fre.rs1_release_inmarket.170303-1614)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 64 GiB
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

### Steps to reproduce the behavior

  1. Deploy a docker deamon on a Windows 10 machine
  2. Execute `docker run -it -u 400:401 microsoft/nanoserver`

Best regards.

**Comment by friism** [comment]
I don't think the `-u` options currently make sense for Windows containers, so I recommend not using them.

cc @johnstep

**Comment by nou2** [comment]
Would it then be possible to have annotations in the documentation for windows as it is the case for the dockerfile reference for instance ? I am aware this is work in progress but that would be useful to know the differences if there is for an option on each platform.

 Ok for uid:gid, but -u ContainerAdministrator won't do the job either and I feel like it should since it is the default user in the container ?

**Comment by friism** [comment]
cc @mstanleyjones
