### ISSUE TITLE
keep asking for for update to 2.2.0.5 (43884)

### ISSUE THREAD

**Issue by keuss** [docker/for-win#6364]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4B621748-E3AE-4D01-86F9-C24881A5FE9C/20200417120302

### Expected behavior

Update from 2.2.0.4 (43472) to 2.2.0.5 (43884)

### Actual behavior

Keep display update pop-up after each start. Try to install update but i got "docker is up-to-date" every time.

### Information

  - Is it reproducible : when i check for update or at each start of my machine
  - Windows Version: Windows 10 Entreprise / 1803
  - Docker Desktop Version: 2.2.0.4 (43472) stable
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: NO

Thanks

**Comment by mat007** [comment]
Thanks for the report, it seems the installation fails and reports an incorrect error (already up to date) instead of
```
[09:42:00.261] [CheckForUpdateHandler] Unable to find a new version
Exception type: System.ComponentModel.Win32Exception, Exception message: Ce programme est bloqué par une stratégie de groupe. Pour plus d’informations, contactez votre administrateur système, StackTrace:
   à System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   à System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   à CommunityInstaller.NewVersionFoundDialog.btnInstall_Click(Object sender, RoutedEventArgs e)
```

For some reason it tries to run the newly downloaded installer and fails…
Is this your machine or is it configured by your company administrator?

**Comment by keuss** [comment]
Thank for answering !

I used to be administrator on my machine, but since a couple of weeks i'm not admin anymore ...

**Comment by mat007** [comment]
I have to admit the error message is pretty bad, but that might explain why it fails…
It should prompt for elevation though so there might be something odd there anyway.

As a workaround I guess you could try to run the installer directly from https://download.docker.com/win/stable/Docker%20Desktop%20Installer.exe

**Comment by keuss** [comment]
Yep, i will try. Anyway not a problem related to docker desktop.

Merci !

**Comment by djs55** [comment]
In [stable 2.4.0.0](https://desktop.docker.com/win/stable/48506/Docker%20Desktop%20Installer.exe) check for updates errors should be reported as "toast" notifications.
