### ISSUE TITLE
CPU limits on Docker

### ISSUE THREAD

**Issue by philcuk** [docker/for-win#6365]
Hi

I am running a MongoDB under Docker and using a Python process to manipulate the datasets.  It is running on a Windows machine, AMD Ryzen 8core / 16Gb RAM, but is ridiculously slow compared to my mates Mac laptop with identical code and size of data.   His Mac is 32Gb RAM, 4core CPU and not running Windows! the Mac is about 5x performance.

The database is about 4Gb and is able to be held entirely in RAM, but it never goes above 13% CPU even though I have set docker settings to use 8CPUs, 8GB RAM and 1GB swap.  I have uploaded diags on A8C176AA-C364-45F2-B1CF-96C6F57D5764/20200417130649.

I was hopeful that Docker could use more than 1 core but it looks like its struggling.  Anyone any ideas on things to check to speed it up?  We are using pymongo for the python processing.

  - Windows Version:  10
  - Docker Desktop Version:  v19.03.8

**Comment by mat007** [comment]
Thanks for the report.

Does the Hyper-V Manager report the correct amount of CPUs for the DockerDesktopVM?

![image](https://user-images.githubusercontent.com/2386884/79838014-aabaaf00-83b2-11ea-941c-a0db928be19c.png)

Alternatively you could try the new WSL 2 backend for Docker Desktop, this would mean switching to the Windows Insider Program for updates for now but this will be generally available with the next major Windows update.

**Comment by philcuk** [comment]
Hi Mathieu

Thanks for coming back to me.  Checked the HyperV config and all seems fine, we’ve had a tinker with the code and it looks more efficient now, and although not necessarily using all 8 CPU’s I’m ok with the performance so will probably close this thread.

Appreciate the response.
Phil.
