### ISSUE TITLE
Docker Desktop version  Settings > Resources not displaying Advanced tab 

### ISSUE THREAD

**Issue by bilalchraibi** [docker/for-win#6368]
I installed the version like described in this blog:
https://www.docker.com/blog/a-new-way-to-get-started-with-docker/ by @stlucek.
Once I installed it, I can't see the following tabs:
- Advanced
- File Sharing 
- Network

When I want to install the official previous version, the installation package tells me that I have the latest version.

### Expected behavior
![image](https://user-images.githubusercontent.com/44674415/79595188-637ba800-80ac-11ea-96b0-e22f15c5b55f.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/44674415/79595128-5068d800-80ac-11ea-88f2-f7224645ba58.png)
### Information
  - Windows Version: 10.0.18363 Build 18636
  - Docker Desktop Version: 2.2.3.0 (43965)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

**Comment by bilalchraibi** [comment]
Well, I found my issue. Those tabs are not available under Windows Container. They are displayed only in Linux container mode. I'm not sure if they should be also visible in the Windows container as well.

**Comment by mat007** [comment]
They’re only for Linux containers, indeed.

**Comment by marceloavf** [comment]
I'm using with Linux containers and can't see these options either. @bilalchraibi

**Comment by mat007** [comment]
@marceloavf if you’re using the WSL 2 backend (that’s the default now if your Windows version supports it), as is the case here because you have a «WSL Integration» sub-section in your screenshot, you don’t need to manually tweak the resources allocated to the VM (because there is no VM).

**Comment by marceloavf** [comment]
How can I change this memory setting in WSL 2 for docker @mat007 ? Is that any related to docker?

I'm getting some JS heap of memory errors and seems to be docker limiting it.

Thank you.
