### ISSUE TITLE
Is there a hook I can use to run a bat/powershell script after docker starts?

### ISSUE THREAD

**Issue by ninrod** [docker/for-win#638]
I want that immediately after docker starts, it calls a bat script of mine. 

is that possible?

thanks in advance.

**Comment by friism** [comment]
Thanks for opening this issue - what's your use case?

**Comment by ninrod** [comment]
hi @friism.

I have a fully optimized docker image focused on shell productivy (zsh, tmux, vim, openssh-server, and friends) to where I mount the docker daemon socket and the docker executable. So I really control the mobylinux docker daemon on windows 10 from inside this container through the mounted docker client executable, mainly because using the dos prompt, powershell, or any port of the unix shell like cygwin, msys, etc..., is a huge pain. 

This container has an sshd daemon running, so Everytime I log in to my machine I have to wait for the docker service to start and when it starts, then I hit my `.bat` script that spins up my image as a daemon container.

after my image is up, then I ssh into it and start to work inside a real unix shell, even in windows. I'd love to `docker exec -it run $CONTAINER zsh` into it, but that's not an option because of docker/docker#8755.

The issue is: I have to manually wait for the docker service to start to call my spin up script. If I could use a hook provided by docker, that would be hugely convenient.

**Comment by Yivan** [comment]
We need this too to make some environment customizations.

@friism So is there a way ?
@ninrod How did you manage to run post-starting script ?

Thanks

**Comment by ninrod** [comment]
@Yivan as of now, I just place a link in the desktop that points to a powershell script that bootstraps the entire environment if the environment is down, or simply enters the container if the environment is up.
