### ISSUE TITLE
Docker deletes Window's SMB share and blames firewall for no connection

### ISSUE THREAD

**Issue by laytoneverson** [docker/for-win#639]
### Expected behavior

I am able to start docker with a shared local drive. Under "Shared Drives" when I click the check next to the "C" and press "Apply" I enter my password, the checkbox remains green, and I am able to build my containers. 

### Actual behavior

I enter my password, the check box becomes empty and the drive is not shared, and he windows share is removed as well. I am alerted with a message telling me the firewall blocked the connection.

My firewall is configured correctly and this problem continues to happen with the firewall disabled completely. 

### Information

  - Diagnostic ID: **C1150827-0FCC-4C96-8AB9-ACDFB51E1A1D/2017-04-13_09-16-07**
  - [log.txt](https://github.com/docker/for-win/files/920108/log.txt)
  - : ![image](https://cloud.githubusercontent.com/assets/1046148/25012024/74114e60-202c-11e7-8572-d963dfc85cd1.png)

### Steps to reproduce the behavior

I have determined that it is a SMB authentication issue:

1. Browse to drive C in explorer.
1. Right click drive C and select properties -> Sharing.
1. Remove everyone and add my user with all full privileges.
1. Browse network and notices that my drive is shared. 
1. Switch to Docker and attempt to mark drive C shared.
1. Enter password when prompted by dialog.
1. I authenticate successfully. 
1. The green checkbox becomes empty. 
1. My C drive is no longer shared in explorer.

**Comment by laytoneverson** [comment]
Similar to #466

**Comment by wambiri** [comment]
I was having similar issues and had almost given up trying to resolve, until i found this:

https://github.com/docker/for-win/issues/313

Not sure if it will help anyone here but following totomakers instructions at the bottom solved my issues.

**Comment by yooakim** [comment]
I have the same issue as this issue is reporting. I've uploaded diagnotics with id `5DF94002-2A09-4318-A1BB-89B29F98B3A5/2017-05-16_07-30-40`.

My firewall is opened as follows (rule created by Docker installation):
```
C:\Users\yooak> netsh advfirewall firewall show rule name=DockerSmbMount

Rule Name:                            DockerSmbMount
----------------------------------------------------------------------
Enabled:                              Yes
Direction:                            In
Profiles:                             Domain,Private,Public
Grouping:
LocalIP:                              10.0.75.1/32
RemoteIP:                             10.0.75.2/32
Protocol:                             TCP
LocalPort:                            445
RemotePort:                           Any
Edge traversal:                       No
Action:                               Allow
Ok.
```

**Comment by mburnett8** [comment]
Thanks @docker-desktop-robot! I actually needed help on this issue tho.
