### ISSUE TITLE
Better TTY support

### ISSUE THREAD

**Issue by DeltaWhy** [docker/for-win#64]
When using `docker run -it` I often have rendering issues that I think are due to the container's process being unaware of the size of the Windows terminal. If it's sized too small then columns from `ls` will overlap. Another frequent issue is with recalling commands from my shell history that wrap onto a second line.

I'm not sure if these are issues with the Docker client or if they're inherent limitations of conhost.exe. Is there any way to run the client in MinTTY or similar? Currently when I try it from a Cygwin terminal I get 'input device is not a TTY' and a request to try it with winpty, which as I understand it just runs conhost off-screen so would have the same issues.

**Comment by rneugeba** [comment]
@DeltaWhy There is fairly little we can do about this, as this primarily depends on the quality of the terminal emulation provided by others. However, there are a few things you can do to maybe improve things a little:

- with conhost based terminals (PS and CMD), make sure the `Properties->Layout->Wrap text output on resize` is selected.
- with conhost based terminals, it seems that the AE (1607) version has some improvements

With `git-bash` (which comes installed when  you install git) you can use `winpty`, which also ships with `git-bash`:
```
% docker run --rm -ti alpine sh
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'
% winpty docker run --rm -ti alpine sh
/ # exit
```
However, resizing the terminal will not work properly...ie it seems to drop the rest of the lines.

For interactive sessions, conhost.exe based shells, like `cmd` or Powershell are probably your best option.

**Comment by rneugeba** [comment]
Closing as won't fix. Please let me know if there is an update.
