### ISSUE TITLE
Auto-Updated pre-requisite for 17.05.0-ce-rc1-win8 (11189) fails on Windows 10 

### ISSUE THREAD

**Issue by gleeds** [docker/for-win#640]
### Expected behavior
Updater updates Docker for Windows to the new version.

### Actual behavior
The following error message is given:
![image](https://cloud.githubusercontent.com/assets/1095404/25026253/4e2b0986-206b-11e7-8637-ef7d6becf3a0.png)

### Information

  - Diagnostic ID: 0D3C54A3-3636-471C-8D1D-8AE541CFDADF/2017-04-13_17-24-17
  - Windows Version: Windows 10 Enterprise N Version 1607 (OS Build 14393.953)
![image](https://cloud.githubusercontent.com/assets/1095404/25026782/e2164d66-206d-11e7-9dc2-f5925ffa9ac6.png)

### Steps to reproduce the behavior

  1. Have 17.04.0-ce-win7 (10981) installed on Windows 10 Enterprise N Version 1607
  2. Accept prompt to update
  3. Click Yes when asked to elevate to Administrator privileges
  4. Get the above error after a few seconds

**Comment by mgw854** [comment]
I can reproduce on Windows 10 Education build 16176 coming from the same Docker version (10981).

**Comment by MichaelSL** [comment]
I have the same issue on Windows 10 Pro N v1703 Build 15063.138

**Comment by vriesmarcel** [comment]
I am running on windows creators update, windows 10 pro and see also this error and am unable to run the edge channel :-( 
Is there any way I can pass in at command line to skip this version check, which seems to be flawed?
version number the os is:
ver: Microsoft Windows [Version 10.0.15063]

thanks!

**Comment by Patrock** [comment]
I have the same problem with edge channel updates to 17.05.0-ce-rc1-win8 on Windows 10 Education build Version 1607 and now 1703 (Creators update)...

**Comment by vicenterusso** [comment]
Same problem with Windows 10 Enterprise
Version 1607
Build 14393.1066

**Comment by simonferquel** [comment]
Thanks for reporting the issue, we are actively tracking it and it should be fixed in an upcoming Edge build.

**Comment by rn** [comment]
I think this is fixed so closing
