### ISSUE TITLE
RUN in dockerfile causes a non-zero error code to be returned when running windows containers and specifying --platform=linux

### ISSUE THREAD

**Issue by mcollinge** [docker/for-win#6408]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Expect the container to be built successfully, without errors.

### Actual behavior
`FROM nginx:alpine
RUN echo 'Hello, world!'`

With the command `docker build --platform=linux .` causes the error:

`The command '/bin/sh -c echo 'Hello, world!'' returned a non-zero code: 4294967295: failed to shutdown container: contai
ner 6cbc4a04ed480477822110ec902e99d2919870e80c267977444bc2e3d71bd124 encountered an error during hcsshim::System::waitBa
ckground: failure in a Windows system call: The virtual machine or container with the specified identifier is not runnin
g. (0xc0370110): subsequent terminate failed container 6cbc4a04ed480477822110ec902e99d2919870e80c267977444bc2e3d71bd124
encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The virtual machine or co
ntainer with the specified identifier is not running. (0xc0370110)`

This works perfectly fine when running using linux containers

### Information

  - Windows Version: Windows 10 Pro Version 1909
  - Docker Desktop Version: 2.2.0.5 (43884)

Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:37:20 2020
  OS/Arch:          windows/amd64
  Experimental:     true    

  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Start with a simple dockerfile `FROM nginx:alpine
RUN echo 'Hello, world!'` (Also happens using 'mcr.microsoft.com/dotnet/core/sdk:3.1-alpine')

  2. `docker build --platform=linux .`

  3. Error!

This also occurs when specifying the platform in a docker-compose file

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place?
Sorry, I would move it myself, but I can't because it's in a different org (it's `moby` not `docker`).

**Comment by mcollinge** [comment]
That's fine by me, I wasn't too sure where would be better
