### ISSUE TITLE
hcsshim::PrepareLayer - failed failed in Win32: Incorrect function. (0x1)

### ISSUE THREAD

**Issue by raj-o** [docker/for-win#6421]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 4F886707-661D-4C8E-A8F3-98DD1DCF72A1/20200422122009

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. PS C:\Users\rajibdut\Desktop\DockerFiles> docker build .
Sending build context to Docker daemon  3.248GB
Step 1/16 : FROM mcr.microsoft.com/windows/servercore:ltsc2019
 ---> fdf6432edbdc
Step 2/16 : LABEL maintainer sumit.x.kumar@oracle.com
 ---> Running in 278d34409243
hcsshim::PrepareLayer - failed failed in Win32: Incorrect function. (0x1)

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18362 N/A Build 18362

PS C:\Users\rajibdut\Desktop\DockerFiles> docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:37:20 2020
  OS/Arch:          windows/amd64
  Experimental:     false
PS C:\Users\rajibdut\Desktop\DockerFiles> docker info
Client:
 Debug Mode: false

Server:
 Containers: 11
  Running: 0
  Paused: 0
  Stopped: 11
 Images: 2
 Server Version: 19.03.8
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 18362 (18362.1.amd64fre.19h1_release.190318-1202)
 Operating System: Windows 10 Pro Version 1903 (OS Build 18362.720)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.76GiB
 Name: RAJIBDUT-IN
 ID: MOHA:MC7F:QQFU:XAU6:QQB4:XMNS:N5MC:2J5J:VMHO:3OMQ:LWZK:KFEE
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 27
  System Time: 2020-04-22T17:15:35.2515816+05:30
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
  2. ...

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place?
Sorry, I would move it myself, but I can't because it's in a different org (it's `moby` not `docker`).
