### ISSUE TITLE
Docker Desktop fails to start

### ISSUE THREAD

**Issue by mcgarrah** [docker/for-win#6423]
Looked thru existing issues with startup errors. Tried setting timeout from 180 to 600 seconds to no avail. On most current stable version.

https://hub.docker.com/editions/community/docker-ce-desktop-windows
  - [ x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x ] I have uploaded Diagnostics
  - Diagnostics ID: C48A1B9E-F1EE-442E-ADCE-A38449BAE329/20200422173604

### Expected behavior

Expect Docker to startup. Currently does not start consistently in the last week or so after last upgrade. Intermittently is would fail to start usually based on lack of resources. That is not the case now.

### Actual behavior

Does not startup.

### Information

  - Is it reproducible? Yes
  - Is the problem new? In the last week or so.
  - Did the problem appear with an update? I think about 2.2.0.4 update it became an issue but with 2.2.0.5 it persists.
  - Windows Version: Windows Enterprise Version 1803 (OS Build 17134.1425)
  - Docker Desktop Version: 2.2.0.5 (most current stable)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Nope on a laptop

### Steps to reproduce the behavior

Just restart windows and fails to start Docker. Manual restarts fail as well.  Logs are in the diag upload.

**Comment by Richard-Barrett** [comment]
Try this:

Try this, I had the same issue:
So I was actually able to solve it by doing the following:

Enter The following commands within an elevated command prompt:
```
Enable Hyper V - You can do this by running the following command as administrator. - dism.exe /Online /Enable-Feature:Microsoft-Hyper-V /All

Enable Hypervisor with following command - bcdedit /set hypervisorlaunchtype auto
```
Research: https://dotnetthoughts.net/hardware-assisted-virtualization-and-data-execution-protection-must-be-enabled/

Then Restart and prompt asks to download the Linux Kernel

Apparently Docker Desktop is forgetting this in their initial set-up for the updates and installation for anybody using Hyper-V and the Linux Containers requiring the WSL2 Linux Kernel Backend to initialize Containers. provided by Microsoft.

Microsoft Link: https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel

Download the above ^^

Stackoverflow Link: https://stackoverflow.com/questions/59413071/error-message-for-hyper-v-and-data-execution-for-docker-desktop-on-windows-10-fa/59653039#59653039

You need to Download wsl2-kernel. 
Similar Github Issue: https://github.com/docker/for-win/issues/6689
