### ISSUE TITLE
docker: Error response from daemon: hcsshim::CreateComputeSystem : The virtual machine could not be started because a required feature is not installed.

### ISSUE THREAD

**Issue by chuksie2003** [docker/for-win#6427]
6C89AB46-E3D5-4981-A6F6-4A22A25F8546/20200423174859

Please help review my docker diagnosis report, i get the subejct error when i try to deploy a microsoft sql server docker file o my laptop

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
This does not look like a bug in Docker Desktop, but in Windows container code in the upstream Engine. Could you please open an issue in moby/moby instead. (Sorry, I would just move it but it's not possible because it's not in the docker org).
