### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by dominikbullo** [docker/for-win#6437]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: EC0D0E5C-2401-4846-92F2-69037ED42B43/20200424132146

### Information

  - Windows Version: Win 10 Education 1909 (18363.815)
  - Docker Desktop Version: 2.2.0.5
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: 

### Steps to reproduce the behavior

Reboot or manually start Docker Desktop.

**Comment by Richard-Barrett** [comment]
Try this:

Try this, I had the same issue:
So I was actually able to solve it by doing the following:

Enter The following commands within an elevated command prompt:
```
Enable Hyper V - You can do this by running the following command as administrator. - dism.exe /Online /Enable-Feature:Microsoft-Hyper-V /All

Enable Hypervisor with following command - bcdedit /set hypervisorlaunchtype auto
```
Research: https://dotnetthoughts.net/hardware-assisted-virtualization-and-data-execution-protection-must-be-enabled/

Then Restart and prompt asks to download the Linux Kernel

Apparently Docker Desktop is forgetting this in their initial set-up for the updates and installation for anybody using Hyper-V and the Linux Containers requiring the WSL2 Linux Kernel Backend to initialize Containers. provided by Microsoft.

Microsoft Link: https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel

Download the above ^^

Stackoverflow Link: https://stackoverflow.com/questions/59413071/error-message-for-hyper-v-and-data-execution-for-docker-desktop-on-windows-10-fa/59653039#59653039

You need to Download wsl2-kernel. 
Similar Github Issue: https://github.com/docker/for-win/issues/6689
