### ISSUE TITLE
can not mount volume if the directory in container is not empty

### ISSUE THREAD

**Issue by junvwang** [docker/for-win#644]
### Expected behavior
the **docker run -v {host folder}:{container folder}** can be successful, and {container folder} is overlayed by {host folder}

### Actual behavior
- if {container folder} doesn't exist or empty, the docker run command can be successful.
- if {container folder} is not empty, docker run failed, error message is:   _C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container 619777c5a92e9b42c5ccbe858ace376e4c4b91b58140031c482370fe5fe16239 encountered an error during Start: failure in a Windows system call: The compute system exited unexpectedly. (0xc0370106)._

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
    8B7B3242-1B2F-4580-8222-C130904C44C2/2017-04-14_18-30-01

  - host distribution and version (Windows version, build number, etc)
    Major  Minor  Build  Revision
    10     0      15063      0

### Steps to reproduce the behavior
  1. [Dockerfile](https://github.com/docker/for-win/files/921934/Dockerfile.txt) (attached):
`# escape='
FROM microsoft/windowsservercore
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
RUN New-Item C:\test -type directory; New-Item C:\test\dummy.txt -type file; New-Item C:\test2 -type 
directory
`
  2. this command will fail, because c:\test in container is not empty:
`docker run -ti -v D:\docker\Test:**C:\test** test powershell`

3. this command is ok, because c:\test2 in container is empty:
`docker run -ti -v D:\docker\Test:**C:\test2** test powershell`

**Comment by friism** [comment]
This is a know limitation:

 * https://github.com/docker/docker/pull/31980/
 * https://github.com/docker/docker/issues/20127

Please re-open if you think that's not the case.

**Comment by junvwang** [comment]
Hi @friism, for this statement 

> The following examples will fail when using Windows-based containers, as the destination of a volume or bind-mount inside the container must be one of: a non-existing or empty directory; **or a drive other than C:**. Further, the source of a bind mount must be a local directory, not a file.

How can i get a new drive other than C: in windows container?

thanks.

**Comment by dtretyakov** [comment]
@junvwang, you could do that like that: https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/334#issuecomment-233062541
