### ISSUE TITLE
WSL2: CLI tools got lost from integration. Cannot restore them.

### ISSUE THREAD

**Issue by alexkrauss** [docker/for-win#6441]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 21394073-DB37-49FA-8287-726A6C45ED10/20200424220626

### Expected behavior

In my distro (Debian), I can access docker using command line tools after enabling the integration in the settings.

### Actual behavior

The above used to work fine until today. Some accident (presumably a docker-compose command) now seem to have removid the cli binaries. Looking around, I see a dangling symlink from `/usr/bin/docker` to `/mnt/wsl/docker-desktop/cli-tools/usr/bin/docker`. In fact, `/mnt/wsl/docker-desktop/cli-tools/` is empty.

I tried to disable the integration and re-enable it again, with no effect. 
What can I do to restore the proper integration, without having to throw away the whole distro?

I would appreciate some workaround that help restore the integration.

### Information

  - Windows Version: 2004 (Build 19041.21)
  - Docker Desktop Version: 2.2.0.5 (43884)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No.

**Comment by simonferquel** [comment]
Have you changed something in your /etc/wsl.conf file?

**Comment by alexkrauss** [comment]
@simonferquel I don't seem to have this file, but I cannot remember touching it.

**Comment by simonferquel** [comment]
Unfortunately, we have an issue with diagnostic files for latest stable. Can you send me your `%LOCALAPPDATA%\docker\log.txt` file ?

**Comment by alexkrauss** [comment]
@simonferquel I just sent the log file to your email (too large to post here and may be sensitive). Thanks for helping.

**Comment by simonferquel** [comment]
I did not received the mail, on which address did you send it ?

**Comment by alexkrauss** [comment]
I sent it to the address mentioned in your github profile (hotmail.fr). But anyway, after looking through it, it does not actually appear very sensitive, so I put it up here: https://gist.github.com/alexkrauss/5eeb7ee935f069d997b8bf4f82a3dd38

**Comment by simonferquel** [comment]
For some reason the docker WSL distro stopped... Those logs don't give any reason why. We improved logging and diagnostics a lot for the build coming (normally) today. I'll ping you when it is out.

**Comment by tttonyyy** [comment]
I am having the same issue.  Machine upgraded to Windows 10 (2004) with bundles WSL2.  Clean install of Docker Desktop and Ubuntu 2.  Work for a while then stopped without any apparent change done my myself.

/mnt/wsl/docker-desktop/cli-tools/ is empty.
Under powershell, **docker context ls** does not show the wsl context.

**Comment by pkostelnik** [comment]
I run today into the same problem.
Every WSL Linux distribution seems not to be able to mount the cli tools. Docker works still fine in Windows Powershell.
Information:
>Windows 10 Enterprise Insider: Ver. 2004 (Build 19640.1)
Docker desktop community: edge 2.3.1.0 (45408) 
Same problem with Docker desktop stable

**docker context ls** shows following:

> PS C:\Users\xxxxxxxxxx> docker context ls
NAME                DESCRIPTION                               DOCKER ENDPOINT                  KUBERNETES ENDPOINT   ORCHESTRATOR
default *           Current DOCKER_HOST based configuration   npipe:////./pipe/docker_engine                         swarm
wsl                 Docker daemon hosted in WSL 2             npipe:////./pipe/docker_wsl

so everything seems to be fine but still no cli inside my WSL2 distributions
