### ISSUE TITLE
WSL2 Docker error on system shutdown

### ISSUE THREAD

**Issue by speller** [docker/for-win#6446]
Sometimes when I shutdown or restart the system with WSL2 Docker (2.3.0.0 44472) I get the following error box on the logout screen:

![image](https://user-images.githubusercontent.com/1829515/80281371-90335d80-8745-11ea-81b2-aeffcbd2cc66.png)

**Comment by Eji4h** [comment]
Same error.

**Comment by ITSecMedia** [comment]
Same error here too!

**Comment by Attoy** [comment]
I've got the very same error. Nothing disruptive but annoying.

**Comment by dockwarder** [comment]
Same here! This message pops up once I shut down my computer. I haven't noticed any problems yet, but it is definitely giving me a sense of discomfort.

**Comment by lrozenblyum** [comment]
I've got a similar message, however it mentions 'wsl.exe'.
Windows event logs don't show anything...

**Comment by justinkb** [comment]
Is this project abandoned or something?

**Comment by CodeBrotha** [comment]
> Is this project abandoned or something?
> 
> edit: I figured out how to programmatically make docker desktop exit. To do this, run C:\Program Files\Docker\Docker\DockerCli.exe -Shutdown
> 
> Now all that's needed is figuring out how to run this on shutdown/reboot/logoff

Did you find a way to run this on shutdown/reboot/logoff?

**Comment by justinkb** [comment]
> Did you ever find a way to run this on shutdown/reboot/logoff?

I did not, I switched to actually manually running the docker service inside the WSL and ditched Docker Desktop completely. I build the docker-cli client for windows from source, run a dockerized https proxy for the docker socket in the wsl docker service to expose it to the windows hosting the wsl, making it accessible to windows users (cli / jetbrains tools / vscode) via usage of DOCKER_HOST env variables and such

**Comment by CodeBrotha** [comment]
> > Did you ever find a way to run this on shutdown/reboot/logoff?
> 
> I did not, I switched to actually manually running the docker service inside the WSL and ditched Docker Desktop completely. I build the docker-cli client for windows from source, run a dockerized https proxy for the docker socket in the wsl docker service to expose it to the windows hosting the wsl, making it accessible to windows users (cli / jetbrains tools / vscode) via usage of DOCKER_HOST env variables and such

It's crazy that you even had to do all that, but I guess we've been left to fend for ourselves on this issue.

**Comment by boistordu** [comment]
related to that https://github.com/docker/for-win/issues/6933

**Comment by judos** [comment]
/remove-lifecycle stale
/lifecycle frozen

Cool another issue tracker that auto closes tickets without anyone doing anything after users take time to provide feedback.
Though please use +1 instead of adding comments like "same issue"

**Comment by rob-mackin** [comment]
+1

**Comment by stephen-turner** [comment]
This is fixed in versions 3.2.0 and 3.2.1. Closing the ticket now.
