### ISSUE TITLE
Getting below issue while starting Docker in windows OS

### ISSUE THREAD

**Issue by 9040010697** [docker/for-win#6449]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by 9040010697** [comment]
atal: failed to start daemon: Error initializing network controller: Error creating default network: failed during hnsCallRawResponse: hnsCall failed in

**Comment by stephen-turner** [comment]
I think this is not an issue with Docker Desktop but with the upstream container engine that we just bundle. Could you please open an issue in moby/moby instead? (Sorry, I would move this issue if I could, but it's not possible because the engine is not in the docker org).
