### ISSUE TITLE
Error response from daemon: Get https://registry-1.docker.io/v2/

### ISSUE THREAD

**Issue by Maartenvm** [docker/for-win#645]
### Expected behavior
Docker pulls images from the hub

### Actual behavior
$ docker pull ubuntu:latest
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

OR

$ docker pull ubuntu:latest
latest: Pulling from library/ubuntu
c62795f78da9: Pulling fs layer
d4fceeeb758e: Pulling fs layer
5c9125a401ae: Pulling fs layer
0062f774e994: Pulling fs layer
6b33fd031fac: Pulling fs layer
0062f774e994: Waiting
6b33fd031fac: Waiting
error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/6a/6a2f32de169d14e6f8a84538eaa28f2629872d7d4f580a303b296c60db36fbd7/data?Expires=1492170952&Signature=E0A~GOGDgV1e9cOPewmXhuqyaC6X7eHQkSTvByTwPZFlBEwW9kbn6UsRr~HBETkiEEEYzZaVVybJwSMaD2~Fz7QisbarJDcnzA4Tg3vy~d8JdyiEiDC5JeTSH~HhM--s5KYe9tqP5NxCAKh4ofkFU7Ko5GgwKzcFsiUEcMpN55Y_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp: lookup dseasb33srnrn.cloudfront.net on 192.168.65.1:53: read udp 192.168.65.2:44129->192.168.65.1:53: i/o timeout

### Information
- Diagnostic ID from "Diagnose & Feedback" in the menu.
6FB09841-00ED-48AE-9A7B-27E56475193A/2017-04-14_13-30-57

- host distribution and version (Windows version, build number, etc)
Windows 10 Pro, fully updated.

### Steps to reproduce the behavior
docker pull ubuntu:latest

**Comment by Maartenvm** [comment]
I worked around the problem by **setting the DNS to fixed 8.8.8.8** in the settings menu.

Could this be related to the DNS issues tweeted here https://twitter.com/dockerstatus/status/841779182703009792 ?

**Comment by MrZoidberg** [comment]
I'm also experiencing this issue:

_PS D:\> docker pull mongo:latest
latest: Pulling from library/mongo
47e616392c23: Pulling fs layer
b8dc044ce904: Pulling fs layer
e32719290561: Pulling fs layer
02d8f1b053c5: Waiting
d836acd00557: Waiting
84f67488220c: Waiting
de17099d47ff: Waiting
4a180e6abe11: Waiting
fc25b86cb5cf: Waiting
6400c13c01f6: Waiting
d7c7ea74f012: Waiting
error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/
63/6329fba85f659b362927801fb9a3baea98688791d01630ea7b25d79deb9e0053/data?Expires=1493474113&Signature=NrjNEuZS5fSYxB7ZJO
iqhMK3vK789CM6npcrBi0fC3NDpATYHdbQa863ICt6mVg0U~1YZMWpDEfANtev3UH3BLAM0a2iefun7TbYWyWbJCKozN-R8tMXW9zIjLh6CoGbagar6wGWrY
MLpjWZTaTpZHXdqrEEFbBeMc1luwgMSK0_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp: lookup dseasb33srnrn.cloudfront.net on 19
2.168.65.1:53: read udp 192.168.65.2:59361->192.168.65.1:53: i/o timeout_

A diagnostic was uploaded with id: 63643211-7B93-42C5-806A-89DA39C52F7B/2017-04-29_16-37-17

**Comment by xanview** [comment]
My DNS is already set to 8.8.8.8 and I'm able to resolve without issues:

```
$ host registry-1.docker.io
registry-1.docker.io has address 34.231.174.197
registry-1.docker.io has address 34.225.140.215
registry-1.docker.io has address 54.86.192.189
registry-1.docker.io has address 52.22.232.68
registry-1.docker.io has address 52.72.188.69
registry-1.docker.io has address 34.224.205.109
$ wget registry-1.docker.io
--2017-07-24 18:23:36--  http://registry-1.docker.io/
Resolving registry-1.docker.io... 54.86.192.189, 34.225.140.215, 34.231.174.197, ...
Connecting to registry-1.docker.io|54.86.192.189|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://registry-1.docker.io/ [following]
--2017-07-24 18:23:36--  https://registry-1.docker.io/
Connecting to registry-1.docker.io|54.86.192.189|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 0 [text/plain]
Saving to: ‘index.html’

index.html                                                      [ <=>                                                                                                                                      ]       0  --.-KB/s    in 0s      

2017-07-24 18:23:36 (0.00 B/s) - ‘index.html’ saved [0/0]
```

However Docker is not able to connect for some reason:
```
$ docker pull ubuntu:latest        
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

Any ideas?

**Comment by samsonkolge** [comment]
Please use the following link ::
https://docs.docker.com/engine/admin/systemd/#httphttps-proxy
