### ISSUE TITLE
Setting ui keep loading and never finished

### ISSUE THREAD

**Issue by comeUpWithItLater** [docker/for-win#6455]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: EA3E8153-3DF2-4444-9B21-45B938E824B4/20200426024648

### Expected behavior

Setting UI  finished loading in seconds  after click the docker icon in  taskbar and select "Settings", so i can change the settings.

### Actual behavior

Never finished loading, even after Docker restart and OS restart.

ps. didn't try factory reset.

![1587902532(1)](https://user-images.githubusercontent.com/15116923/80307039-473ce100-87f9-11ea-8a46-c04009969872.jpg)

### Information
  - Is it reproducible? : not sure.
  - Is the problem new? : yes, 1st first.
  - Did the problem appear with an update? : No
  - Windows Version: 1909
  - Docker Desktop Version: 
![1587903126(1)](https://user-images.githubusercontent.com/15116923/80307232-4d7f8d00-87fa-11ea-8815-3da0970463f0.jpg)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:  No.

**Comment by mat007** [comment]
Thanks for the report.
This is Kubernetes failing to start which causes this, we have changed the UI to not lock it when starting Kubernetes now to work around this. It will be available in the next release.

In the meanwhile you can shut down Docker Desktop, open `%APPDATA%\Docker\settings.json` and flip `kubernetesEnabled` back to false, then relaunch Docker Desktop.
Sorry for the inconvenience!

**Comment by comeUpWithItLater** [comment]
Flipping kubernetesEnabled back to false did fix the UI issue. But now I got a new one: Kubernetes wouldn't start:
![1587972999(1)](https://user-images.githubusercontent.com/15116923/80346342-2928bc80-889d-11ea-942f-6fe859ea40bf.jpg)

**Comment by mauro-dellachiesa** [comment]
I'm having this same issue.
diagnostic id: 490D5704-2FAB-470C-AD5F-9D463C2DB383/20200427151346

## Notes
- This was the first time I tried using K8S on my local. Until today, I used just docker (win and linux containers) without any issue.
- I did try a factory reset and did not work. The diagnostic I reference was created after the factory reset

Thanks!

**Comment by mauro-dellachiesa** [comment]
Looks like with the latest version this got solved because I was able to run
`kubectl cluster-info` successfully.
