### ISSUE TITLE
Can't share drive. mounting .../C on /c failed: Invalid argument

### ISSUE THREAD

**Issue by devnixs** [docker/for-win#646]
Before I start, this is not a duplicated issue. I've read all the other github issues related to that error, and tried every possible fix, and none of them worked.

**My firewall is completely disabled for all networks.**
If I create the share manually using 
````
net share C=C:\ /grant:MYMACHINE\MYUSER,FULL /CACHE:None
````
And then try to share the driver in docker for windows, the share is deleted.

Something surprising is that I can access the share in windows explorer
But when I try with the command line, it fails :

![image](https://cloud.githubusercontent.com/assets/4487892/25062509/96e00498-21cd-11e7-83a0-4688ecf14a72.png)

**But it works in explorer!**
![image](https://cloud.githubusercontent.com/assets/4487892/25062528/fa275088-21cd-11e7-99e9-70b4b191a887.png)

Of course, I tried rebooting, uninstalling and reinstalling docker many times.

I already tried 
https://github.com/docker/for-win/issues/77
https://github.com/docker/for-win/issues/114
https://github.com/docker/for-win/issues/125
https://github.com/docker/for-win/issues/98
https://github.com/docker/for-win/issues/280
https://github.com/docker/for-win/issues/313
https://github.com/docker/for-win/issues/530
https://github.com/docker/for-win/issues/639
https://github.com/docker/for-win/issues/466

### Expected behavior

- I should be able to share a drive in docker for windows

### Actual behavior

- After typing my password, the checkbox gets unchecked

### Information

The error in the log is : 
````
[09:52:23.832][SambaShare     ][Error  ] Unable to mount C drive: 10.0.75.1 (10.0.75.1:445) open
mount error(95): Not supported
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
mount: mounting //10.0.75.1/C on /c failed: Invalid argument
````
And the Diagnostic ID is 416D68C3-32DA-4D22-8310-B4729A32B7B8/2017-04-15_11-24-53

I'm on Windows 10 Pro, version 1607 (OS Build 14393.1066 )

### Steps to reproduce the behavior

  1. Open docker for windows, shared drives tab. 
  2. Check a drive
  3. Hit apply
  4. Enter your password
  5. The checkbox get unchecked!

Thanks for your help! I'm really getting out of ideas.

**Comment by grahamehorner** [comment]
have you tried creating a local account adding it to the administrator group and using this when sharing the credentials for this account when sharing the volume in docker?

Gabriel Cloud System Limited
4 St. Gabriel Ave, Riverside Village,
Hebburn, Tyne & Wear, England NE31 1AG


CAUTION:This email and any attachments transmitted with it contain information that is CONFIDENTIAL and may be privileged or otherwise protected from disclosure. If you are not the intended recipient please notify us immediately and delete all copies of this email message and any attachments transmitted with it from your system. If you are not the intended recipient, any use, disclosure or copying of this email message and any attachments transmitted with it is strictly prohibited. This email message and any attachments transmitted with it cannot be guaranteed to be secure or error free as information could be intercepted, corrupted, lost, destroyed or incomplete. Although we routinely screen for viruses, it makes no representation or warranty as to the absence of viruses in this email or any attachments. The views expressed in this email are those of the sender and not necessarily those of Gabriel Cloud Systems LTD; if you require clarification please contact the sender.

proud sponsors of
Hebburn Town Juniors FC
(Junior Madrid)

Get Outlook<https://aka.ms/sdimjr> for iOS
________________________________

**Comment by devnixs** [comment]
Thanks for your answer.
Yes! I tried that already and it didn't work.



On Sat, Apr 15, 2017 at 11:36 PM +0200, "Grahame Horner" <notifications@github.com<mailto:notifications@github.com>> wrote:

have you tried creating a local account adding it to the administrator group and using this when sharing the credentials for this account when sharing the volume in docker?

Gabriel Cloud System Limited
4 St. Gabriel Ave, Riverside Village,
Hebburn, Tyne & Wear, England NE31 1AG


CAUTION:This email and any attachments transmitted with it contain information that is CONFIDENTIAL and may be privileged or otherwise protected from disclosure. If you are not the intended recipient please notify us immediately and delete all copies of this email message and any attachments transmitted with it from your system. If you are not the intended recipient, any use, disclosure or copying of this email message and any attachments transmitted with it is strictly prohibited. This email message and any attachments transmitted with it cannot be guaranteed to be secure or error free as information could be intercepted, corrupted, lost, destroyed or incomplete. Although we routinely screen for viruses, it makes no representation or warranty as to the absence of viruses in this email or any attachments. The views expressed in this email are those of the sender and not necessarily those of Gabriel Cloud Systems LTD; if you require clarification please contact the sender.

proud sponsors of
Hebburn Town Juniors FC
(Junior Madrid)

Get Outlook<https://aka.ms/sdimjr> for iOS
________________________________

**Comment by simonferquel** [comment]
From the diagnostics, I see many Samba errors (with status: Request is not supported) while authenticating.
By any chance do you have any windows policy restricting the file shares authorized authentication schemes ?

**Comment by devnixs** [comment]
Hi @simonferquel and thanks for taking the time to look into that.
I'm not aware of any policy restricting the file shares, But I have to admit, I'm no expert.
Maybe you could guide me and tell me where to look?
Thanks!

**Comment by devnixs** [comment]
It's a shame but I had to format my computer. Couldn't find another way and I needed it to work.
Closing that issue then.

**Comment by waelkdouh** [comment]
I am facing the same issue with the latest version of docker on windows 10

**Comment by quangakgl** [comment]
me too

**Comment by prajapatin** [comment]
After lot of struggle, I was able to get rid of this error. Please follow below steps if none of the resolution works mentioned on this thread.
1. Navigate to C:\Users\Public\Documents\Hyper-V (it will ask administrative permission)
2. Click on folder "Virtual hard disks"
3. Here you will find "MobyLinuxVM.vhdx", just right click on it and goto context menu "Share with -> Advanced sharing settings..."
4. There you just go ahead and enable sharing under Public folder sharing blade and that's it. Once you have saved this settings, go ahead and enable sharing drive through docker command or through docker UI (settings)

**Comment by strarsis** [comment]
I also have the same issue on Docker Toolbox (VirtualBox default hypervisor).
It appears that CIFS support is missing.

**Comment by PsychoXIVI** [comment]
Similar problem for me :C
