### ISSUE TITLE
WSL compose version is different with Windows compose

### ISSUE THREAD

**Issue by matinrco** [docker/for-win#6461]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
They should be in same version.
### Actual behavior
from windows powershell:
![image](https://user-images.githubusercontent.com/11003970/80316755-cd1a5580-8814-11ea-93fa-3c80d88e1946.png)

from wsl2 shell (debian):
![image](https://user-images.githubusercontent.com/11003970/80316785-04890200-8815-11ea-99d3-6dabb28052a4.png)

### Information

  - Windows Version: 2004 (19041)
  - Docker Desktop Version: 2.3.0.0 (44472)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Updated from docker desktop 2.2.3.0 to 2.3.0.0 . (edge)
  2. ...

**Comment by mat007** [comment]
Oh good catch, yes indeed!
Thanks for the report, this will be fixed in the next release.

**Comment by rfay** [comment]
Here I thought that the docker client and docker-compose had to be manually installed in the wsl2 machine, which would mean they'd often be different?

**Comment by djs55** [comment]
@rfay Docker Desktop comes with Linux binaries and should symlink them if you enable the WSL 2 distro integration in settings.

**Comment by djs55** [comment]
The fix for this issue has been released in [stable 2.4.0.0](https://desktop.docker.com/win/stable/48506/Docker%20Desktop%20Installer.exe).
