### ISSUE TITLE
After bios update (Dell 5490 Sku 0959), Docker was not able to start.  I lost all my containers.  

### ISSUE THREAD

**Issue by wrbejar** [docker/for-win#6468]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
There is no information here to allow us to triage the problem, so I'm going to close this ticket. But have you made sure that you have all the correct BIOS options including virtualisation?

**Comment by wrbejar** [comment]
Yes, all virtuallization options are ok. I was using Docker without any problem. Docker problem occurred after Bios Update. Tks.
