### ISSUE TITLE
Simple - Port is bound but web browser will not connect to the containers webserver

### ISSUE THREAD

**Issue by nkaku** [docker/for-win#6487]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 9C94AD66-BAA9-4490-BEAA-BF3E899A9D8E/20200429071009

### Expected behavior
Display of static-site webpage

### Actual behavior
Cannot connect.

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by rreis27** [comment]
I may be encountering the same issue.

about 3 days ago, my working development ide stopped allowing me to access my dotnet core website on the host port that is dynamically generated/exposed to my host machine.

My Diagnostics is

ABD215CA-702E-4C01-A8E2-12682B775795/20200501191423

ABD215CA-702E-4C01-A8E2-12682B775795/20200501191423

**Comment by rreis27** [comment]
I figured out my issue.  My application was exiting out and not logging properly.  I figured this out by debugging the project by itself.
