### ISSUE TITLE
Docker Stable won't switch to Linux Containers and on Windows containers throiws error on building containers

### ISSUE THREAD

**Issue by hicreate** [docker/for-win#6489]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID 78506B83-7B95-4BE2-B71E-790AC9570616/20200429083724

### Expected behavior
Docker runs containers when on Windows containers and switches to Linux containers when selected.

### Actual behavior
When running windows containers, the app looks like it has installed fine, I can sign in but if I use the cli to run hello-world I get the following error in powershell 

"C:\Program Files\Docker\Docker\resources\bin\docker.exe: error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/create: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running."

I also cannot complete the onboarding for the same reason.

If I then right click the task bar icon to switch to Linux Containers docker throws an error in a ui window that says:

Failed to switch because your Windows version is not compatible.

Hardware assisted virtualization and data execution protection must be enabled in the BIOS. See https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization-must-be-enabled

Keeping previous configuration."

### Information
Im on Windows 10 Pro, ver 1909 (happened also with 1907 yesterday). 

Docker Version shows:

Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false

I can reproduce the behaviour even after uninstall and reboot.

Fixes I've tried:

- I have tried to enable and disable Hyper V both thorugh the CLI and UI, with the reboots,
- I've been into the bios to ensure that virtualisation is enabled (confirmed through the task manager also)
- I've disabled CFG in Windows security
- I've tried the edge release too, issues with that also which I've raised in a separate ticket.

### Steps to reproduce the behavior

  1. Install docker
  2. Try to run docker image in windows containers
3. Try to switch to Linux containers.

**Comment by more-urgent-jest** [comment]
the error you get when trying to run hello-world sounds like what I get behind a proxy without the settings specified
