### ISSUE TITLE
Shared drive cannot be enabled for account from Azure Active Directory/Microsoft Intune

### ISSUE THREAD

**Issue by evgri243** [docker/for-win#649]
I have a Windows PC managed by Intune (named _work account_ during windows post installation setup wizard). And when I try to enable drive sharing, it prompts for user credentials, accepts them and just fails with no exception or error message; just nothing happens and drive remains unshared.

I had a look at daemon logs and find that `netsh` command fails with _System error 1332 has occurred. No mapping between account names and security IDs was done._ I'm not sure, but believe that the problem is due to inability of Docker for Windows to look up a SID for user account in AAD (not an ordinary AD).

It's not blocking, since _**you can use credentials of any other local user in credentials prompt to solve this issue**_, but it would be great to add AAD support in future or just add error message and some info in docs.

### Information

Daemon logs:

> [00:37:11.553][SambaShare     ][Info   ] Removing share C
> [00:37:11.591][SambaShare     ][Info   ] Mount C
> [00:37:11.634][Cmd            ][Info   ] This shared resource does not exist.
> [00:37:11.634][Cmd            ][Info   ] 
> [00:37:11.634][Cmd            ][Info   ] More help is available by typing NET HELPMSG 2310.
> [00:37:11.634][Cmd            ][Info   ] 
> [00:37:11.637][SambaShare     ][Info   ] "C" is not shared
> [00:37:11.637][SambaShare     ][Info   ] Creating share "C:\" as "C" with Full Control to "user"
> [00:37:11.673][Cmd            ][Info   ] System error 1332 has occurred.
> [00:37:11.673][Cmd            ][Info   ] 
> [00:37:11.673][Cmd            ][Info   ] No mapping between account names and security IDs was done.
> [00:37:11.673][Cmd            ][Info   ] 
> [00:37:11.678][SambaShare     ][Error  ] Failed to create share "C:\" as "C" with Full Control to "user" with code: 2
> [00:37:11.702][Cmd            ][Info   ] This shared resource does not exist.
> [00:37:11.702][Cmd            ][Info   ] 
> [00:37:11.705][NamedPipeClient][Info   ] Received response for Mount
> [00:37:11.702][Cmd            ][Info   ] More help is available by typing NET HELPMSG 2310.
> [00:37:11.702][Cmd            ][Info   ] 

### Steps to reproduce the behavior

  1. Login into Intune-joined PC with AAD account with no corresponding local user 
  2. Try to enable _C:_ drive share

**Comment by skidoosh** [comment]
Just figured this out with our sys admin. We've got the same setup AAD+Intune. You need to create a local admin user account for example "Docker" with a non-expiring password and use that account when Docker challenges you for your AD credentials. Working a treat for us so far.

Hope this helps.

**Comment by simonferquel** [comment]
Yes unfortunately we can't fix that. Samba file sharing is basically broken with AAD :(. local accounts is the way to go.

**Comment by ivanov** [comment]
@skidoosh - thank you so much for following up! I've been trying to figure this out the whole day and your tip worked like a charm!
