### ISSUE TITLE
Unable to pull images with WSL2 engine

### ISSUE THREAD

**Issue by sefranz** [docker/for-win#6494]
I am not able to access the official docker registry in any way. This includes but not limited to:
1. Registry login through `docker login`
2. Pulling any images

  - [x] I have tried with the latest version of my channel (Stable or **Edge**)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4FABF347-80B2-4BEF-909D-538C79B1720F/20200429113855

### Expected behavior
When starting the _getting-started_ container the image is pulled and a corresponding container is started.

### Actual behavior
```bash
 $ docker run -dp 80:80 docker/getting-started
Unable to find image 'docker/getting-started:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/docker/getting-started/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Adocker%2Fgetting-started%3Apull&service=registry.docker.io: unexpected EOF.
See 'docker run --help'.
```

### Information
  - Windows Version: Windows 10 Pro 2004 (Build 19041.208)
  - Docker Desktop Version: 2.3.0.1 (44875) [edge Channel]
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No
  - Further: I am using the WSL 2 based engine

### Steps to reproduce the behavior
1. Install docker desktop with WSL 2 based engine
2. Run `docker run -dp 80:80 docker/getting-started`

**Comment by joshward** [comment]
I had this same issue. My problem was that I had the Docker CLI installed directly on WSL.

I switched docker for windows back to Hyper-V, then uninstalled the Docker CLI from WSL. After turning back on WSL integration everything worked.

**Comment by sefranz** [comment]
This fixed my issue as well, I owe you many thanks
