### ISSUE TITLE
win10 use docker command in cmd error

### ISSUE THREAD

**Issue by hxdhero** [docker/for-win#650]
PS C:\windows\system32> docker info
Exception 0xc000001d 0x0 0x0 0x18000890c
PC=0x18000890c

syscall.Syscall(0x7ffaff23dc40, 0x2, 0x270, 0x3, 0x0, 0x0, 0x0, 0x26c)
        /usr/local/go/src/runtime/syscall_windows.go:163 +0x6b
github.com/docker/docker/vendor/github.com/Microsoft/go-winio.setFileCompletionNotificationModes(0x270, 0x203, 0x0, 0xffffffff)
        /go/src/github.com/docker/docker/vendor/github.com/Microsoft/go-winio/zsyscall_windows.go:88 +0x6f
github.com/docker/docker/vendor/github.com/Microsoft/go-winio.makeWin32File(0x270, 0xc042421890, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/github.com/Microsoft/go-winio/file.go:78 +0xd8
github.com/docker/docker/vendor/github.com/Microsoft/go-winio.DialPipe(0xc04219b8c8, 0x16, 0xc042421980, 0x0, 0xc04240cd20, 0xc041fec21f, 0xc0424219f8)
        /go/src/github.com/docker/docker/vendor/github.com/Microsoft/go-winio/pipe.go:192 +0x537
github.com/docker/docker/vendor/github.com/docker/go-connections/sockets.DialPipe(0xc04219b8c8, 0x16, 0x773594000, 0x13658e0, 0x10, 0x100, 0x100)
        /go/src/github.com/docker/docker/vendor/github.com/docker/go-connections/sockets/sockets_windows.go:26 +0x46
github.com/docker/docker/vendor/github.com/docker/go-connections/sockets.configureNpipeTransport.func1(0xe4e0ee, 0x3, 0xc042418520, 0x19, 0x60, 0x0, 0xc042416401, 0xc04240cd80)
        /go/src/github.com/docker/docker/vendor/github.com/docker/go-connections/sockets/sockets_windows.go:19 +0x49
net/http.(*Transport).dial(0xc0420b2960, 0x130bf80, 0xc04200a290, 0xe4e0ee, 0x3, 0xc042418520, 0x19, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/http/transport.go:829 +0x82
net/http.(*Transport).dialConn(0xc0420b2960, 0x130bf80, 0xc04200a290, 0x0, 0xe4e91b, 0x4, 0xc042418520, 0x19, 0x0, 0x0, ...)
        /usr/local/go/src/net/http/transport.go:967 +0x1a8c
net/http.(*Transport).getConn.func4(0xc0420b2960, 0x130bf80, 0xc04200a290, 0xc042405c80, 0xc04240cae0)
        /usr/local/go/src/net/http/transport.go:885 +0x7f
created by net/http.(*Transport).getConn
        /usr/local/go/src/net/http/transport.go:887 +0x3a8

goroutine 1 [select]:
net/http.(*Transport).getConn(0xc0420b2960, 0xc042418500, 0x0, 0xe4e91b, 0x4, 0xc042418520, 0x19, 0x0, 0x0, 0x4129ba)
        /usr/local/go/src/net/http/transport.go:890 +0x9d3
net/http.(*Transport).RoundTrip(0xc0420b2960, 0xc0420b2b40, 0xc0420b2960, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:367 +0x31a
net/http.send(0xc0420b2b40, 0x12fdd40, 0xc0420b2960, 0x0, 0x0, 0x0, 0x8, 0xc042024610, 0x4137bf)
        /usr/local/go/src/net/http/client.go:256 +0x166
net/http.(*Client).send(0xc042405bc0, 0xc0420b2b40, 0x0, 0x0, 0x0, 0xc042024610, 0x0, 0x1)
        /usr/local/go/src/net/http/client.go:146 +0x109
net/http.(*Client).doFollowingRedirects(0xc042405bc0, 0xc0420b2b40, 0xef1e58, 0x3, 0xc04214b801, 0x410cc6)
        /usr/local/go/src/net/http/client.go:528 +0x5ec
net/http.(*Client).Do(0xc042405bc0, 0xc0420b2b40, 0xc04200a290, 0xc0420b2b40, 0xc04200a290)
        /usr/local/go/src/net/http/client.go:184 +0x1f1
github.com/docker/docker/vendor/golang.org/x/net/context/ctxhttp.Do(0x32d4028, 0xc04200a290, 0xc042405bc0, 0xc0420b2a50, 0xc0420b2a50, 0xc04214b990, 0x5cabac)
        /go/src/github.com/docker/docker/vendor/golang.org/x/net/context/ctxhttp/ctxhttp.go:30 +0x99
github.com/docker/docker/client.(*Client).doRequest(0xc042360980, 0x32d4028, 0xc04200a290, 0xc0420b2a50, 0x6, 0x0, 0x0, 0x0, 0xc0420b2a50, 0x0)
        /go/src/github.com/docker/docker/client/request.go:127 +0x75
github.com/docker/docker/client.(*Client).Ping(0xc042360980, 0x32d4028, 0xc04200a290, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/client/ping.go:17 +0x233
github.com/docker/docker/cli/command.(*DockerCli).Initialize(0xc0423871f0, 0xc042313c20, 0x4, 0x13820e0)
        /go/src/github.com/docker/docker/cli/command/cli.go:189 +0x3f0
main.newDockerCommand.func2(0xc0423f58c0, 0x13820e0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/cmd/docker/docker.go:50 +0xa9
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0xc0423f58c0, 0xc042004610, 0x0, 0x0, 0xc0423f58c0, 0xc042004610)
        /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:628 +0x578
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc042073d40, 0xc042392240, 0xc042339e30, 0xc0420244d0)
        /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:742 +0x37e
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(0xc042073d40, 0xc042073d40, 0x12fe380)
        /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:695 +0x32
main.main()
        /go/src/github.com/docker/docker/cmd/docker/docker.go:169 +0xeb

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:116 +0x15e
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x29
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x48

goroutine 7 [syscall, locked to thread]:
syscall.Syscall6(0x7ffaff236bf0, 0x5, 0x26c, 0xc042423f5c, 0xc042423f60, 0xc042423f68, 0xffffffff, 0x0, 0x7ffafb9f3040, 0x1, ...)
        /usr/local/go/src/runtime/syscall_windows.go:174 +0x6b
github.com/docker/docker/vendor/github.com/Microsoft/go-winio.getQueuedCompletionStatus(0x26c, 0xc042423f5c, 0xc042423f60, 0xc042423f68, 0xffffffff, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/github.com/Microsoft/go-winio/zsyscall_windows.go:76 +0xc6
github.com/docker/docker/vendor/github.com/Microsoft/go-winio.ioCompletionProcessor(0x26c)
        /go/src/github.com/docker/docker/vendor/github.com/Microsoft/go-winio/file.go:129 +0x82
created by github.com/docker/docker/vendor/github.com/Microsoft/go-winio.initIo
        /go/src/github.com/docker/docker/vendor/github.com/Microsoft/go-winio/file.go:57 +0x87
rax     0x0
rbx     0x1365c48
rcx     0x270
rdi     0x39b000
rsi     0xc0424217a0
rbp     0xc042421750
rsp     0x8fd78
r8      0x1
r9      0x0
r10     0x270
r11     0x1677110
r12     0x0
r13     0xd3
r14     0xeecb17
r15     0x3
rip     0x18000890c
rflags  0x10246
cs      0x33
fs      0x53
gs      0x2b

**Comment by simonferquel** [comment]
@dgageot it rings a bell, but can't recall which one. Do you have an idea ?

**Comment by dgageot** [comment]
@simonferquel Sorry, no

**Comment by hxdhero** [comment]
because of web companion
