### ISSUE TITLE
Get error when you move/rename a file with vue extension (VueJs)

### ISSUE THREAD

**Issue by coolfarmer** [docker/for-win#6501]
My setup is pretty basic, I have a container for my project and I have installed Yarn, Webpack and VueJS. I run "yarn watch" command to watch my code and when I move a component (example.vue), I got this error 98% of time:

```
error  in ./assets/game/finance/bank/loan/components/NewLoanRequestModal.vue

Syntax Error: Error: ENOENT: no such file or directory, open '/var/www/app/assets/game/finance/bank/loan/components/NewLoanRequestModal.vue'
```
Even if I reboot the container and reload yarn watch, the error persist.
This error happen only when I move or rename .vue files. I have 2 workarounds to get rid of it :

**Workaround 1**: Stop all container and quit docker and restart all the things. (reloading the container only does not fix the problem).

**Workaround 2**: I have to rename the file twice, I don't know how this can fix the error but it work about ~50% of time. Example: I move component.vue, get the error, rename the file to component1.vue, then rename back the file to component.vue.

  - [x] I have tried with the latest version of my channel (-> Stable)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F038DED9-684B-479E-98A8-29477AD4CF30/20200429175526

### Expected behavior
I want to move/rename a .vue file without getting any error.

### Actual behavior
I get a weird error and have to use workarounds to get rid of it.

### Information
  - Is it reproducible: Yes (98% of time)
  - Did the problem appear with an update? I don't think no, I have this project since ocker 2.2
  - Windows Version: Win10 1909 (build 18363.778)
  - Docker Desktop Version: 2.2.0.5 (43884)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
  1. Run yarn watch to watch the modified files
  2. Move or rename a file with vue extension

**Comment by mat007** [comment]
Thanks for the report!

We’ve made several fixes to the file sharing code lately, they aren’t yet available or the Stable channel (soon!) but if you fancy trying out an Edge build you can grab one from https://docs.docker.com/docker-for-windows/edge-release-notes/

If you’re still experiencing the problem then, can you upload diagnostics (from the Troubleshoot window that can be opened using the systray menu)?

**Comment by coolfarmer** [comment]
Diagnostics ID (Docker Edge): F038DED9-684B-479E-98A8-29477AD4CF30/20200429203123

Ok I can see the difference with Edge (and yes it's better... _but not perfect_).
The good thing is that I don't have anymore the need to quit Docker and restart all my things, a simple "yarn watch" again and the problem is fixed, but here is some details:

Imagine this tree:
.
├── public
├── components
│   ├── clock.vue
│   └── wall.vue
└── src
    └── example.vue

**Steps:**
1. Start "yarn watch" to start file watching
2. Move `clock.vue` to `/src`, we'ill receive this error:
`Syntax Error: Error: ENOENT: no such file or directory, open '/path/...blablabla'`

3. A click outside PhpStorm _(or Ctrl+S)_ will trigger yarn to compile (this step was not working on 2.2). With **2.3 Edge** we are receiving this message:
```
 WAIT  Compiling...                                                                                                                                                                                                               
 DONE  Compiled successfully in 624ms
```
Yes, it work good this time!

4. But what happen if we move back `clock.vue` under `/components` ? The same error than before:
`Syntax Error: Error: ENOENT: no such file or directory, open '/path/...blablabla'`

But now, even if I hit Ctrl+S Yarn don't want to compile it again and is completely "stuck" with that error. The only thing I can do is restart yarn with `yarn watch` (not a big deal, it's better than restart docker on 2.2 haha).

As you can see the problem is partially fixed, it's pretty rare that I move back a file freshly moved but yeah it can happen.
