### ISSUE TITLE
DockerDesktop fails to start on Windows 10 Enterprise VDI

### ISSUE THREAD

**Issue by naikshubham** [docker/for-win#6508]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 5F8527DB-7A42-47A9-886A-51278FB0A86B/20200430092425

### Information

  - Windows Version: Windows 10 Enterprise
  - Docker Desktop Version: Docker version 19.03.5, build 633a0ea
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Running it on Windows 10 Enterprise VDI

### Steps to reproduce the behavior

  1. Try running Docker Desktop on Windows 10 Enterprise VDI

**Comment by mat007** [comment]
Thanks for the report, however Docker Desktop isn’t supported when running in a virtual environment.
For more information see https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-desktop-in-nested-virtualization-scenarios
