### ISSUE TITLE
Possible enhancements to "Using Docker in WSL 2"

### ISSUE THREAD

**Issue by RohitJain13** [docker/for-win#6510]
After following the instructions on the "Using Docker in WSL 2" page, everything should ideally run without an hitch.

I ran into a couple of _minor_ hitches that I wanted to share that perhaps could be addressed.

1. I get a permissions denied message when running docker in my WSL 2 distro
2. I get a message that my WSL 2 distro cannot find and connect to a Docker daemon

Solution / enhancement:
1. The permission issue is really not a WSL 2 issue. It is more a Linux issue and can be quickly resolved.  What would otherwise require docker commands to be preceded by sudo in order for things to run properly, can easily be addressed by adding your user to the docker group, as follows:
- Create the docker group (which probably already exists)
   sudo groupadd docker 
- Add your user to the docker group
  sudo usermod -aG docker ${USER} 
- Log out and back or enter 
   su -s ${USER} 

Adding this to the write-up might help some folks avoid this issue.

2. The cannot connect to Docker daemon issue only occurred when I had Docker starting up at Windows startup and login time.  I found that the Resources -> WSL Setting was not enabled for Ubuntu.  It was enabled for my default WSL distro, and I had set my default distro as ubuntu, but yet Ubuntu was not enabled.  When I re-enabled it, everything worked fine.

My suspicion is that there is a timing dependency here. I have not tested this. But it looks like if Ubuntu WSL is not running at the time the Docker Desktop is started then Ubuntu does not get recognized and enabled.  If I start Ubuntu and then start Docker everything works fine (again, sorry I have not completely verified this due to time constraints). 

If the above is verified to be true, then it at least needs to be documented in that above mentioned write-up, or perhaps some product enhancements need to be made to Docker / WSL to remember this specific distro enablement.

**Comment by stephen-turner** [comment]
Thanks for the feedback, @RohitJain13. Assigning @simonferquel and @usha-mandya.

**Comment by usha-mandya** [comment]
@simonferquel Let me know after you've verified the behaviour. We can add a note in the WSL 2 docs on enabling the distro before starting Docker Desktop.

**Comment by simonferquel** [comment]
Actually, docker desktop creates the group and adds the default user to that group. It just requires the user to launch a fresh session (group membership is cached by Linux after login).

But the point 2. seems very likely to be a bug. I'll try to reproduce it.

**Comment by RohitJain13** [comment]
> Actually, docker desktop creates the group and adds the default user to that group. It just requires the user to launch a fresh session (group membership is cached by Linux after login).
> 
> But the point 2. seems very likely to be a bug. I'll try to reproduce it.

We should probably document that the user launch a fresh session to pick up the new user addition to the group.  Thanks!
