### ISSUE TITLE
docker crash on start after install

### ISSUE THREAD

**Issue by yura-k** [docker/for-win#6511]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 2345B69F-E5F8-414E-8E5B-FE069D176509/20200430171924

### Expected behavior
After installation & restart on Windows host docker initialize and starts automatically
### Actual behavior
Crash 
### Information

  - Windows Version: Win 10 Enterprise, 1709 (16299.1387)
  - Docker Desktop Version: 2.2.05 (43884), Engine: 19.03.8, Compose: 1.25.4
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no, windows is running natively on Dell laptop Precision 3530

### Steps to reproduce the behavior

  1. Windows 10
  2. Enable all required features
  3. Install docker
  4. restart widows after docker installation
  5. wait for docker initialize
  6. get crash report

**Comment by e-belair** [comment]
Getting crash too, crash report id: 7A46077D-AEA1-4429-A7E6-1D69A271368A/20200501100659

**Comment by marcselis** [comment]
I've experienced that Docker Desktop 2.2+ won't run on Windows version 1709.  Docker Desktop version 2.1.0.5 is the last one that does.
