### ISSUE TITLE
[WSL2] Connect to a MySQL SSH-tunnel running on host

### ISSUE THREAD

**Issue by ad-on-is** [docker/for-win#6516]
My setup is as follows:

Docker Desktop 2301 (44875) edge, with WSL integration enabled
Windows 10 Insider 19613

I'm running a NodeJS Container from within WSL, I also have an SSH-tunnel running on host, port 3307 connecting to a remote MySQL-Database.

When I connect with `localhost:3307` from within DataGrip on Windows, I can successfully establish a connection to the datebase.

However, when I try to connect to the datebase from withing my Node script, it does not work.

I've tried the following `host.docker.internal:3307`, `172.22.41.230:3307`, and just in case `localhost:3307`

`172.22.41.230:3307` and `localhost:3307` give me an ECONNREFUSED
`host.docker.internal:3307` gives me an ENOTFOUND host.docker.internal

Any clue how I can establish a connection to the ssh-tunnel?

**Comment by ad-on-is** [comment]
The error was caused due to a `dns` entry in my `docker-compose.yml`. Removing that entry fixes the issue.

**Comment by denisdifazio** [comment]
In the end which of the following `host.docker.internal:3307`, `172.22.41.230:3307` or `localhost:3307` worked for you? I'm trying to do the same without success.

**Comment by ad-on-is** [comment]
> In the end which of the following `host.docker.internal:3307`, `172.22.41.230:3307` or `localhost:3307` worked for you? I'm trying to do the same without success.

`host.docker.internal:3307`

**Comment by denisdifazio** [comment]
Thank you! It start working after I restart LxssManager
