### ISSUE TITLE
Failed : Switch to linux container

### ISSUE THREAD

**Issue by gittadesushil** [docker/for-win#6517]
[docker_fail_log.log](https://github.com/docker/for-win/files/4564200/docker_fail_log.log)

  - [ ] I have tried with the latest version of my channel (Stable)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 9C557EB9-CEF8-4712-89C5-7D4BA3319430/20200501122601

### Expected behavior
I should be able to switch to linux container
### Actual behavior
Error dialog appear while switching from windows to linux container
### Information

  - Windows Version: Windows 10 Enterprise 

```
Version : 1803
OS build  : 17134.1425
```
  - Docker Desktop Version:

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:37:20 2020
  OS/Arch:          windows/amd64
  Experimental:     false
```

  - Are you running inside a virtualized Windows - YES on a cloud server

### Steps to reproduce the behavior

  1. Install docker desktop stable verion on windows cloud server VM
  2. While installing make sure you check-in for install for windows container 

Note: I have checked insider Hyper-v and I don't find any VM attached to it

**Comment by Richard-Barrett** [comment]
Try this:

Try this, I had the same issue:
So I was actually able to solve it by doing the following:

Enter The following commands within an elevated command prompt:
```
Enable Hyper V - You can do this by running the following command as administrator. - dism.exe /Online /Enable-Feature:Microsoft-Hyper-V /All

Enable Hypervisor with following command - bcdedit /set hypervisorlaunchtype auto
```
Research: https://dotnetthoughts.net/hardware-assisted-virtualization-and-data-execution-protection-must-be-enabled/

Then Restart and prompt asks to download the Linux Kernel

Apparently Docker Desktop is forgetting this in their initial set-up for the updates and installation for anybody using Hyper-V and the Linux Containers requiring the WSL2 Linux Kernel Backend to initialize Containers. provided by Microsoft.

Microsoft Link: https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel

Download the above ^^

Stackoverflow Link: https://stackoverflow.com/questions/59413071/error-message-for-hyper-v-and-data-execution-for-docker-desktop-on-windows-10-fa/59653039#59653039

You need to Download wsl2-kernel. 
Similar Github Issue: https://github.com/docker/for-win/issues/6689
