### ISSUE TITLE
Various kernel warnings, eventually ending with a kernel crash

### ISSUE THREAD

**Issue by aydogankaragoz** [docker/for-win#652]
### Expected behavior
Docker Starting successfully
### Actual behavior
Not starting
### Information

3197FA4A-7A0F-475E-AD35-2F887FEBD6D5/2017-04-17_12-03-48

### Steps to reproduce the behavior

  1. Try to start
  2. Wait

**Comment by simonferquel** [comment]
@rneugeba, the logs show many kernel warnings, and eventually ends with a crash.

**Comment by rneugeba** [comment]
This looks like the same issue we had on https://github.com/docker/for-win/issues/274

This issue is a combination of processor (SkyLake) and Hyper-V. Do you have all updates installed?

**Comment by rneugeba** [comment]
closing due to lack of information. Please re-open if the issue persist after windows updates
