### ISSUE TITLE
Unable to start docker desktop for linux containers

### ISSUE THREAD

**Issue by sasathy1** [docker/for-win#6522]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E87A6F46-5187-4494-A050-F13C5213BC36/20200501203813

### Expected behavior
When I try to start docker desktop, it starts for Windows containers by default. When I right click on Docker -> Switch to Linux containers, the docker desktop fails to start. 
PS: I have a Windows 10 desktop

### Actual behavior
Docker should start normally

### Information

  - Windows Version: 10
  - Docker Desktop Version: Docker version 18.09.0, build 51668a30
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

**Comment by Richard-Barrett** [comment]
Try this:

Try this, I had the same issue:
So I was actually able to solve it by doing the following:

Enter The following commands within an elevated command prompt:
```
Enable Hyper V - You can do this by running the following command as administrator. - dism.exe /Online /Enable-Feature:Microsoft-Hyper-V /All

Enable Hypervisor with following command - bcdedit /set hypervisorlaunchtype auto
```
Research: https://dotnetthoughts.net/hardware-assisted-virtualization-and-data-execution-protection-must-be-enabled/

Then Restart and prompt asks to download the Linux Kernel

Apparently Docker Desktop is forgetting this in their initial set-up for the updates and installation for anybody using Hyper-V and the Linux Containers requiring the WSL2 Linux Kernel Backend to initialize Containers. provided by Microsoft.

Microsoft Link: https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel

Download the above ^^

Stackoverflow Link: https://stackoverflow.com/questions/59413071/error-message-for-hyper-v-and-data-execution-for-docker-desktop-on-windows-10-fa/59653039#59653039

You need to Download wsl2-kernel.
