### ISSUE TITLE
lỗi không chạy đc docker

### ISSUE THREAD

**Issue by khaistarmoon** [docker/for-win#6534]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 5C771165-6611-4FA7-9284-F013003AEA27/20200503051424
### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ulrich** [comment]
Hello @khaistarmoon 

Can you check if Hyper-v is running by **services.msc** command ?
