### ISSUE TITLE
I just can't start the Docker Desktop For Windows

### ISSUE THREAD

**Issue by CaRaH-Lee** [docker/for-win#6535]
- [ √ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ √ ] I have uploaded Diagnostics
  - Diagnostics ID:5E647FDD-5CF8-4A17-BE8C-3E675E39B40A/20200503061159

### Expected behavior
running the docker with windows containers
### Actual behavior
pop a error dialog
### Information
Docker.Core.Backend.BackendException:
fatal: failed to start daemon: Error initializing network controller: Error creating default network: failed during hnsCallRawResponse: hnsCall failed in Win32: There are no more endpoints available from the endpoint mapper. (0x6d9)
   在 Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   在 Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   在 Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   在 Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

  Docker.Core.DockerException:
  fatal: failed to start daemon: Error initializing network controller: Error creating default network: failed during hnsCallRawResponse: hnsCall failed in Win32: There are no more endpoints available from the endpoint mapper. (0x6d9)
     在 Docker.Backend.Processes.WindowsDockerDaemon.WaitForDaemonToBeReady()
     在 Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions)
     在 Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions, Credential credential)
     在 Docker.Backend.BackendNamedPipeServer.<Run>b__8_2(Object[] args)
     在 Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
     在 Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

  - Windows Version:windows10 1909
  - Docker Desktop Version:2.2.0.5
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:No

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place?
Sorry, I would move it myself, but I can't because it's in a different org (it's `moby` not `docker`).
