### ISSUE TITLE
Unable to Install Docker 2.2.043884

### ISSUE THREAD

**Issue by georgedelacruz213** [docker/for-win#6536]
2.2.043884
CommunityInstaller

PS C:\Windows\system32> Get-WmiObject -Class Win32_OperatingSystem | % Buildnumber
17763
PS C:\Windows\system32> Get-WmiObject -Class Win32_OperatingSystem | % Caption
Microsoft Windows 10 Pro
PS C:\Windows\system32> D:
PS D:\> cd .\Downloads\
PS D:\Downloads> & '.\Docker Desktop Installer (2).exe'
PS D:\Downloads> System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.String.StartsWith(String value, StringComparison comparisonType)
   at CommunityInstaller.ProcessEnvironmentDetector.RelaunchFromTemp(String[] args)
   at CommunityInstaller.Cmd.InstallHandler.Run(String[] args)
   at CommunityInstaller.Program.Main(String[] args)

Whenever I open the Docker desktop installer, it does not show anything so I decided to open it via Powershell and it throws me this error.

**Comment by mat007** [comment]
Thanks for the report.
I looks like you may have (had) an old version of Docker Desktop installed on you system and this confuses the installer.
Can you open `regedit.exe` (Windows-r then type `regedit`) and see if you have anything under `SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall` that’d be either `Docker Desktop` or `Docker for Windows`?
If so you can remove it and start the installer again to work around this issue.

I’ll do a proper fix in our code.

Thanks!

**Comment by georgedelacruz213** [comment]
Hi @mat007 

Yes, I had an old version of docker and it does not respond when I try to uninstall it so I deleted files related to docker manually.

Thanks for the workaround! I have successfully installed Docker Desktop in my pc.
