### ISSUE TITLE
docker windows 10 1703 shared drives （Windows 10 共享磁盘问题）

### ISSUE THREAD

**Issue by lanmingle** [docker/for-win#654]
开始安装 Windows 10 后安装 docker 没有问题，但是重启后发现挂载失效，之后我重置，还是有问题，后面我把 docker 卸载后则又可以，但是重启后还是一样。

我的 Hyper-V 存储在 D 盘上，挂载的盘是 E 盘，Windows pro 10 1703。

Began after install Windows 10 installation docker no problem, but found that mount failure after the restart, after I reset, or have a question, behind me the docker after unloading, can again, but still the same after restart.
I stored in the Hyper - V D plate, disc is E plate mount, Windows pro 10, 1703.

**Comment by khaliullov** [comment]
the same problem. "Creators Update". When adding share to Docker and press "Apply" my share to disk C: is disappearing!
Error message:
"A firewall is blocking file Sharing between Windows and the containers. See documentation for more info."
Firewall is disabled.

**Comment by lanmingle** [comment]
@khaliullov 

多谢你的解答，我已经解决了。
首先，卸载本地上安装的 Docker ，再停止 Windows 的防火墙，这样比较简单，不要顾虑这么多，或者设置开放端口（这个我也是从别的看到过介绍，但是实验不成功），重启电脑，重新安装 Docker ，另外我还特意把 Hyper-V 所存储的目录与挂载的目录一致，我想这个也许不会影响，希望能为后续遇到这问题的解答。

Thank you for your answer, I have already solved.
First, unload the Docker installed on the local, and then stop the Windows firewall, which is simple, don't worry so much, or setting up the open ports (this I also seen introduced from other, but the experiment is not successful), restart your computer, reinstall the Docker, I also specially to the Hyper - V storage directory and mounted directory is consistent, I think this may not affect, wish for subsequent meet the answer of the question.

**Comment by hack2root** [comment]
Try Power Shell 3 command under Adminstator access rights as follows:

Set-NetConnectionProfile -interfacealias "vEthernet (DockerNAT)" -NetworkCategory Private

Then enable drive C,D share in Docker settings.
