### ISSUE TITLE
Can't bind IP address:port to container

### ISSUE THREAD

**Issue by KamGor** [docker/for-win#6549]
Okay, I'm after a few days with WSL2 and latest Docker Edge with WSL backend and I'm so disappointed. Why is it not possible to use `-p 123.123.123.123:80:80` within docker anymore? After using `docker run -p ip_address:port:port` docker generate random port and use 127.0.0.1 address.

On bare WSL2 I can assign an additional IP address to the network interface and listen on that address even with simply `nc` tool. Then I can check that address on the host machine and it is possible to get a response from `nc` tool. So, why is it not possible to bind an IP address to a container?

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 2C869355-4761-4177-87F0-1D12AA05B7D2/20200504173718

### Expected behaviour
Docker container should be bonded with the selected IP address and port

### Actual behaviour
Docker does some magic and bind container with random port and 127.0.0.1 IP address.

### Information
  - Windows Version: Windows 10 Pro 2004
  - Docker Desktop Version: 2.3.0.1 (Edge)

### Steps to reproduce the behaviour
  1. Assign extra IP address within WSL
  2. Create a container with Nginx/Apache bind to extra IP with `-p extra_ip_address:port:port`
  3. Docker does some magic and returns a wrong IP address and random port

**Comment by simonferquel** [comment]
There is currently a limitation for this scenario, where the IP address must be an address of the Windows Host (or 127.0.0.x or 0.0.0.0).
Could you give us a little more context to have a feeling how important it is to be able to bind on a discrete WSL 2 IP address ?

**Comment by KamGor** [comment]
I think it's a serious game-changer. I have multiple projects which have a lot of services like DBs, some calculation services, multiple front serving apps, workers, etc. We are testing them how they work together on our local machines when we are developing new features. So I create a Docker project which can simulate project on a developer machine.

On Linux:
The project contains a single network for all components. Every part of the system is a separate container which has a separate IP address, so the developer doesn't have to bind ports or do nothing more than `docker-compose up -d`.

On windows (Idea which I tried to implement):
I tried to add an IP address to a network interface and bind each IP address to a separate container which needs an IP address to work with host machine web browser.

**Comment by simonferquel** [comment]
Yeah, due to network isolation, it wont work this way. To access a container port, you need to expose it (in your compose file, or with `-p` in docker run).
However, if you want to expose each of them on different IPs, you can do it, by exposing each container on a different 127.0.0.x IP (which are all valid loopback IPs and that work on both the Windows host and WSL).

E.g. `docker run -p 127.0.0.42:80:80 nginx` should make nginx reachable on 127.0.0.42 both from a Windows browser, or using curl/wget within your wsl distro.

**Comment by KamGor** [comment]
@simonferquel Thank You! I don't know why I didn't think about it before. Now I can only say there is a small bug with displaying PORTS on `docker ps -a` after running container this way.

`Docker ps -a` shows 127.0.0.1:random_port instead of selected_ip_address_on_loopback:selected_port.

Example: 
![docker bug](https://user-images.githubusercontent.com/26033487/81296484-41a18f80-9072-11ea-9a5e-f01797db481c.png)

**Comment by simonferquel** [comment]
Yes, this is a known issue: internally we do some magic API interception to do the port forwarding in a way that works seemlessly. If you inspect the container you might see interesting labels there.

**Comment by simonferquel** [comment]
Basically, we listen on a randomly assigned port within the Linuxkit distro, and proxy this port on the windows host (and within wsl main network namespace) transparently

**Comment by KamGor** [comment]
For me, this thread has been exhausted. Thank You again for your help and simple workaround.
