### ISSUE TITLE
Run linux VPN-client container as a service on windows 10 enterprise 19041

### ISSUE THREAD

**Issue by gscorrea** [docker/for-win#6550]
My situation is that I need make several different VPN connections at the same time and for that I have to run different VMs and takes a toll on my host.
So the idea was to run several containers, each with a different VPN connection and from windows  host with routing configuration, access the networks provided by each vpn connection.

WINDOWS HOST ---> VPN1 container ----> tunnel ----> remote network 1.
                            |
                             ---> VPN2 container ----->tunnel ----> remote network 2.

If this is not possible yet on docker desktop on windows 10 enterprise 19041, when will be available, as this can be achieved from a linux host?

**Comment by paroque28** [comment]
I need to run a Linux container with a VPN on Windows. Any update, advice? Is it possible?
