### ISSUE TITLE
Unable to run windows container

### ISSUE THREAD

**Issue by jkeane** [docker/for-win#6551]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X ] I have uploaded Diagnostics
  - Diagnostics ID: 0D4C63F1-4AC9-4748-9651-6276A33F62ED/20200504230522

### Expected behavior
Host PS> docker run -it mcr.microsoft.com/powershell:nanoserver-1909 powershell
Container PS> c:\

### Actual behavior
C:\Program Files\Docker\Docker\resources\bin\docker.exe: Error response from daemon: container 21395f0034892407011f8473ea12e37a051f76870f405e14d4b84888c9d8a9b9 encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2)
[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]
[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]
[Event Detail: onecore\vm\compute\management\orchestration\vmhostedcontainer\processmanagement.cpp(173)\vmcomputeagent.exe!00007FF74B9AAE77: (caller: 00007FF74B95E4AB) Exception(1) tid(38c) 80070002 The system cannot find the file specified.
    CallContext:[\Bridge_ProcessMessage\VmHostedContainer_ExecuteProcess]
 Provider: 00000000-0000-0000-0000-000000000000] extra info: {"CommandLine":"powershell","User":"ContainerUser","WorkingDirectory":"C:\\","Environment":{"LOCALAPPDATA":"C:\\Users\\ContainerAdministrator\\AppData\\Local","POWERSHELL_DISTRIBUTION_CHANNEL":"PSDocker-NanoServer-1909-KB4551762-amd64","PSCORE":"\\PowerShell\\pwsh.exe","PSModuleAnalysisCachePath":"\\Microsoft\\Windows\\PowerShell\\docker\\ModuleAnalysisCache","ProgramFiles":"C:\\Program Files","WindowsPATH":"C:\\Windows\\system32;C:\\Windows"},"EmulateConsole":true,"CreateStdInPipe":true,"CreateStdOutPipe":true,"ConsoleSize":[50,212]}.

### Information

Windows 10: 10.0.18363

Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

### Steps to reproduce the behavior

  1.   docker run -it mcr.microsoft.com/powershell:nanoserver-1909 powershell
error occurs

NOTE: If I switch to Linux containers and run: docker run -it mcr.microsoft.com/powershell:ubuntu-18.04 pwsh, the image downloads fine and I get the expected powershell prompt within the container

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place?
Sorry, I would move it myself, but I can't because it's in a different org (it's `moby` not `docker`).
