### ISSUE TITLE
Docker Failed to start on Windows 10 Enterprise VM

### ISSUE THREAD

**Issue by ankitashine132** [docker/for-win#6554]
I am trying to install Docker Desktop in windows 10 Enterprise VM. Also.I have enabled Hyper-V. I have gone through many articles but couldn't fix it. Please if anyone can help me on below error:

Below are VM Details:

Windows 10 Enterprise RAM: 4 GB System Type: 64-bit OS, x64 based processor

Docker version: 2.2.0.5.

virtualization is enabled still I face same issue. Enabled 'Use Intel VT-x/AMD-V for instruction set virtualization...' .

[Error ] Unable to start Hyper-V VM: Microsoft.HyperV.PowerShell.VirtualizationException: 'DockerDesktopVM' failed to start.

Failed to start the virtual machine 'DockerDesktopVM' because one of the Hyper-V components is not running.

'DockerDesktopVM' failed to start. (Virtual machine ID 109C9013-5F42-4EF4-A80C-AE69E1372AFC)

The Virtual Machine Management Service failed to start the virtual machine 'DockerDesktopVM' because one of the Hyper-V components is not running (Virtual machine ID 109C9013-5F42-4EF4-A80C-AE69E1372AFC). ---> Microsoft.Virtualization.Client.Management.VirtualizationOperationFailedException: 'DockerDesktopVM' failed to start.
[ErrorLog_VM.txt](https://github.com/docker/for-win/files/4578890/ErrorLog_VM.txt)

**Comment by stephen-turner** [comment]
Docker Desktop often doesn't work inside a VM. This is not a Docker bug, it's whether the outer VM can run another VM inside it, which is outside our control.
