### ISSUE TITLE
Docker fails to start hv-sock proxy (vsudd) is not reachable in Windows 10 Enterprise

### ISSUE THREAD

**Issue by patrick-mota** [docker/for-win#656]
### Expected behavior
Docker starts

### Actual behavior
Docker fails to start for linux containers.
I already tried to uninstall Docker, reinstall, install different versions, uninstall Hyper-V reinstall Hyper-V, tried to run docker as administrator too... Nothing seems to work.

> Docker hv-sock proxy (vsudd) is not reachable
   à Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId)
   à Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   à Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   à Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   à Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

### Information

  - Diagnostic ID : 5576D20B-3707-41A2-8663-F9AFF0A1D27C/2017-04-20_09-09-41

Version: 17.04.0-ce-win7 (10981)
Channel: stable
Sha1: b18e2a50ccf296bcd637b330c0ca9faaab9d790c
Started on: 2017/04/20 09:06:44.707
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1607
Build: 14393
BuildLabName: 14393.0.amd64fre.rs1_release.160715-1616

### Steps to reproduce the behavior

  1. Start Docker
  2. Wait
  3. Failed to start

**Comment by hitched-simon-williams** [comment]
I am also getting this.  It has been happening on the last two versions of Docker.  Everything seemed fine before this.  If I got to the Daemon page of the settings dialog and press Apply to restart, Docker starts okay, but the next time I restart the machine, I get the error.

**Comment by patrick-mota** [comment]
Well I tried with Docker 1.13 and got the same error so I don't know.... maybe I'll try if necessary the same thing with 1.13 and upload the diagnostic ID if needed.

**Comment by patrick-mota** [comment]
Just had an update for Windows and after the reboot docker seems working again !

I had this BuildLabName: 14393.0.amd64fre.rs1_release.160715-1616

and now:
BuildLabName: 14393.1066.amd64fre.rs1_release_sec.170327-1835

**Comment by thalestakao** [comment]
I m using Docker for Windows 17.06.0-ce-win18 (12627) and I solved this problem.

Try this:

1. click the up arrow to the left of your notification area icons.
2. right-clicking the Docker and cliking "Switch to Linux containers...".
3. restart your Windows.
