### ISSUE TITLE
Erro ao iniciar o Docker

### ISSUE THREAD

**Issue by eriellensouza** [docker/for-win#6560]
ID : 0BF44AA5-6556-4317-960F-F32D172E30F9/20200505134733

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ulrich** [comment]
Hello @eriellensouza 

We need more informations or diagnostics ID.

**Comment by eriellensouza** [comment]
diagnostics ID : 0BF44AA5-6556-4317-960F-F32D172E30F9/20200505134733

**Comment by ulrich** [comment]
@eriellensouza thank you for your feedback.

**Comment by eriellensouza** [comment]
What do I do with this "/ reopen" command, I am new to using Docker.
