### ISSUE TITLE
docker starting takes forever, can't switch to windows container.

### ISSUE THREAD

**Issue by AliceCMos** [docker/for-win#6561]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: CD162E70-6226-4C86-B056-3F78CA3EE393/20200505143858

### Information

  - Windows Version: Windows 10 Pro, Version: 10.0.18363 Build 18363
  - Docker Desktop Version: 2.2.0.5 (43884)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by itunc** [comment]
Did you try to enable _'Expose daemon on tcp://localhost:2375 without TLS'_ under settings? In that case it might have something to the with a reserved port by the Hyper-V and this workaround might help https://github.com/docker/for-win/issues/3171#issuecomment-459205576 .
