### ISSUE TITLE
Very high CPU and disk usage when host wakes from sleep

### ISSUE THREAD

**Issue by sgryt** [docker/for-win#6564]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 
CCF324D6-4AE6-4E76-A9AF-A4FBB6FF2B33/20200506063703

### Expected behavior
Close-to-idle CPU's and disk on host after waking from sleep
### Actual behavior
Very high CPU and disk usage on host after waking from sleep.
### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible?
It seems to happen each time the host wakes from prolonged sleep (in the state where I have to supply my Bitlocker password before the host OS resumes)
  - Is the problem new?
Yes, I have only seen it happen after I installed and started using Docker for Windows
  - Did the problem appear with an update?
No
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.
Not sure how I could provide this without shipping the laptop to you ?

  - Windows Version: 
Windows 10 Pro version 1909, 64bit
  - Docker Desktop Version: 
2.2.0.5 (43884)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: 
Yes, in a Hyper-V guest (with nested virtualization enabled). The guest OS is the same as the host OS (Windows 10 Pro version 1909, 64bit).

### Steps to reproduce the behavior

  1. Install Docker Desktop for Windows in a Hyper-V guest image using the OS versions mentioned above. 
  2. Use a laptop for the host
  3. Configure the guest with 16GB RAM and 4 cores (on a host with 64GB RAM and 8 cores)
  4. Put the laptop to sleep
  5. Wake it up again.
  6. The vmmem.exe process on the host now consumes 50% CPU until such time that I manage to connect to the Hyper-V guest and restart Docker Desktop. This takes about 10 minutes in my case, because the CPU's in the guest VM are max'ed out.
  7. Very high disk usage on the host is also observed

**Comment by paaland** [comment]
I have the same issue. Running Docker Desktop 2.2.0.5 (stable) on Windows 10 2004 (19041.208) using WSL 2 and the WSL 2 integration.

Laptop is an Lenovo P53 with 32 GB ram. WSL is limited to use 8 GB ram and 4 GB swap.

After laptop resumes from sleep, according to Windows task manager the total CPU load is 100%. Everything lags badly. If I look at details in task manager and sort by CPU load no visible process is using more than 20-30% CPU, but total is 100% all the same.

By trial and error I've determined that either killing "docker desktop.exe" or asking docker desktop to restart fixes the problem. Even if "docker desktop.exe" does not consume more than a few % CPU according to task manager.

I did notice that when "show kernel times" were on, the kernel was responsible for about 50% of the 100% load. My guess is some interrupt or handle handling have gone bad after the suspend/resume.

**Comment by mat007** [comment]
Docker Desktop is not supported in a virtualised environment. It might work or it might not, but it's out of our control, it depends on whether the outer virtual machine supports nested virtualisation.
For more information see https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-desktop-in-nested-virtualization-scenarios.

**Comment by mat007** [comment]
@paaland you may want to comment on #6947 or maybe open a different issue as I’m not sure #6947 is with WSL 2.
Also you may want to check https://github.com/microsoft/WSL/issues/4166?
