### ISSUE TITLE
Doker unable to start after installung for the first time. Please fix this ASAP

### ISSUE THREAD

**Issue by brdeepak** [docker/for-win#6568]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 5F0E9714-70DD-43AC-9F8B-A4F43A24D3F6/20200506162252

### Information

  - Windows Version: windows 64bit
  - Docker Desktop Version: 2.2.0.5
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Am trying to run on a cloud machine.

### Steps to reproduce the behavior

  1. Install the latest version of docker desktop installer.
  2. click on docker installer to install the latest version of docker
  3.  Try running the docker. docker displays that its starting but it crashes with an error.

**Comment by stephen-turner** [comment]
Docker Desktop is not supported in a virtualised environment. It might work or it might not, but it's out of our control, it depends on whether the outer virtual machine supports nested virtualisation.
