### ISSUE TITLE
Docker version 2.5.0.5 fails to install

### ISSUE THREAD

**Issue by hpets3526** [docker/for-win#6572]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
When running the docker for windows installer it completes and starts docker

### Actual behavior
it fails to install with this error:
![docker](https://user-images.githubusercontent.com/16153999/81230796-bf549500-8fb7-11ea-8a42-92e4107ee36c.PNG)

### Information

  - Windows Version: Windows 10 Enterprise  version 1909
  - Docker Desktop Version: 2.5.0.5
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Download latest from https://hub.docker.com/editions/community/docker-ce-desktop-windows/
  2. Attempt to Install

**Comment by mat007** [comment]
Thanks for the report, this looks like the same as #6091.
I’ll go ahead and close this one as a duplicate.
