### ISSUE TITLE
diagnostic ID 5110CC1E-7670-4EB2-A45A-A27813814D38/20200507200143

### ISSUE THREAD

**Issue by rewalston** [docker/for-win#6587]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID:5110CC1E-7670-4EB2-A45A-A27813814D38/20200507200143

### Expected behavior
Expect when link is clicked within docker that it opens default browser.

### Actual behavior
Will not open browser no matter what I do.
### Information

  - Windows Version: Windows 10 Pro
  - Docker Desktop Version:v19.03.8
N  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
Docker
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
Which link?

**Comment by rewalston** [comment]
I think it was when I was setting it up for the first time to run with Pi as a Pi Node. I can't remember, and can't find where I was looking.
________________________________
