### ISSUE TITLE
encountered an error during CreateContainer: failure in a Windows system call: The system cannot find the path specified.

### ISSUE THREAD

**Issue by ttelfer** [docker/for-win#659]
When attempting to build a Dockerfile to download 7zip and install, the build process fails with the following error:

`container 184987b3241c947a6c32777698d4290e4961cbc93f86ce5f7ab688fde637c25f encountered an error during CreateContainer: failure in a Windows system call: The system cannot find the path specified. (0x3) extra info: {"SystemType":"Container","Name":"184987b3241c947a6c32777698d4290e4961cbc93f86ce5f7ab688fde637c25f","Owner":"docker","IsDummy":fals
e,"VolumePath":"\\\\?\\Volume{94ff26a4-1eef-11e7-9100-ca60bfaf35a5}","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\docker\\windowsfilter\\184987b3241c94
7a6c32777698d4290e4961cbc93f86ce5f7ab688fde637c25f","Layers":[{"ID":"99b48d69-8804-51ae-96a8-37854e9e459f","Path":"C:\\ProgramData\\docker\\windowsfilter\\26e25ad6194d411d8f
e16f623f0415e8e959fd76abb3a2d99ffa72dce5643077"},{"ID":"03561cfb-0da8-5ea4-ba79-c275acc04521","Path":"C:\\ProgramData\\docker\\windowsfilter\\04eb17d37d1c45a67913ba6f55836d4
36d1ddd70b31643b2efefe13e9c5f425d"},{"ID":"f042343c-bff5-5926-8adb-fd7ae9c22555","Path":"C:\\ProgramData\\docker\\windowsfilter\\bbe28aa47b2088ebe26fcb6236d85cb5d5badd066bb3
017c2fc3f2b3efeb7647"},{"ID":"572322a2-a546-5f09-a054-b9aa2da4b885","Path":"C:\\ProgramData\\docker\\windowsfilter\\cc8cd0b2631d8450939aebfff360a41ef0aa3d9ae7edb6cfa84865d53
b5adcf7"},{"ID":"228e3f8d-2615-5414-a5aa-8cdfa1f21a98","Path":"C:\\ProgramData\\docker\\windowsfilter\\e49ba929309ecab4df8995bc7ba8c588eb4f0b780cb367b86b218c508f909391"}],"H
ostName":"184987b3241c","MappedDirectories":[],"HvPartition":false,"EndpointList":["ccb1fe0e-99f5-4f02-b7e8-5740138b441d"],"Servicing":false,"AllowUnqualifiedDNSQuery":true}`

The command I ran to build the following Dockerfile was:

`docker build -t blah/blah .`

`
FROM microsoft/windowsservercore

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]

WORKDIR C:\\downloads

ADD http://www.7-zip.org/a/7z1604-x64.exe 7zip.exe
RUN Get-ChildItem C:\\downloads

RUN Start-Process msiexec -Wait \
		-ArgumentList @( \
			'/i', \
			'7zip.msi', \
			'/quiet', \
			'/qn', \
			'INSTALLLOCATION=C:\7zip', \
			'ADDLOCAL=all' \
		); \
`

Client:
 Version:      17.03.1-ee-3
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 19:31:22 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ee-3
 API version:  1.27 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 19:31:22 2017
 OS/Arch:      windows/amd64
 Experimental: false

docker info:

Containers: 178
 Running: 0
 Paused: 0
 Stopped: 178
Images: 175
Server Version: 17.03.1-ee-3
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.953.amd64fre.rs1_release_inmarket.170303-1614)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 16 GiB
Name: DEV-AMI1
ID: SVZZ:ZB2W:I2HM:K6VC:RBOC:I7JK:SQCB:ABHL:WE4V:ZP3K:6DHV:WTAA
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

Windows Server 2016 Datacenter Edition

**Comment by friism** [comment]
Yeah, I've never gotten any of the 7z installers or auto-extractors to work in containers. You can use the powershell module though:

    Install-Package PS7Zip -Force | Out-Null

For the record, I think this is the Dockerfile that you want (it doesn't work either):

```
FROM microsoft/windowsservercore

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]

ADD http://www.7-zip.org/a/7z1604-x64.exe 7zip.exe

RUN Start-Process msiexec -Wait -ArgumentList @( '/i', '7zip.msi', '/quiet', '/qn', 'INSTALLLOCATION=C:\7zip', 'ADDLOCAL=all' );
```

Other references:

 * https://github.com/git-for-windows/git/issues/986#issuecomment-266318940
 * https://github.com/moby/moby/commit/5e19064462ebb23b36170c1bd68d44c03a40e564
 * https://www.powershellgallery.com/packages/PS7Zip/1.0.0.3

I'm closing this, please re-open if this reply doesn't get you unstuck.

**Comment by deeruattavar** [comment]
how to run and view this 7zip working or not

**Comment by deeruattavar** [comment]
FROM microsoft/windowsservercore

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]

ADD http://www.7-zip.org/a/7z1604-x64.exe 7zip.exe

RUN Start-Process msiexec -Wait -ArgumentList @( '/i', '7zip.msi', '/quiet', '/qn', 'INSTALLLOCATION=C:\7zip', 'ADDLOCAL=all' );

This is working fine,it has created images and ran the container with following command  "docker run -d 7zip"

But i was not able to see running container,it shows like it has create d and exited.. how to make it running and  view this rinning 7zip app

![image](https://user-images.githubusercontent.com/25116352/34758858-ca5bb460-f5fe-11e7-9b83-6bea27dd86f9.png)
