### ISSUE TITLE
docker-compose host volume does not mount

### ISSUE THREAD

**Issue by vorpleblade** [docker/for-win#66]
# docker-compose host volume does not mount

### Expected behavior
docker-compose should mount the defined host volume in the container.

### Actual behavior
docker-compose does not mount local volume on docker host in windows.

### Information

Diag ID: `D9FD48C3-5135-4629-A764-D694FB410CF9/2016-08-30_09-36-08`

- Host OS
  - Windows 10 Enterprise
  - Version: 1607
  - OS Build: 14393.82
- Docker version
  - Docker version 1.12.0, build 8eab29e
- Docker-compose version
  - docker-compose version 1.8.0, build d988a55

## Steps to reproduce
- Create local temp folder with a local file

`mkdir C:\temp\foo`
```
docker-bug  > mkdir C:\temp\foo


    Directory: C:\temp


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        8/30/2016     08:47                foo

```

`echo "# Foo" > C:\temp\foo\readme.md`

- Build docker image file using a Dockerfile with the following:

```
FROM alpine

ENTRYPOINT ["ls", "/data"]
```

`docker build -t docker-bug .`
```
docker-bug  > docker build -t docker-bug .
Sending build context to Docker daemon 4.096 kB
Step 1 : FROM alpine
 ---> 4e38e38c8ce0
Step 2 : ENTRYPOINT ls /data
 ---> Using cache
 ---> 4b87371a442f
Successfully built 4b87371a442f
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.
```

- Run docker image

`docker run -v c:/temp/foo:/data docker-bug`

Returns the expected output
```
docker-bug  > docker run -v c:\temp\foo:/data docker-bug
readme.md
docker-bug  > docker run -v c:/temp/foo:/data docker-bug
readme.md
docker-bug  >

```

- Execute docker-compose with the following:
```
version: '2'
services:
  sample:
    image: docker-bug
    volumes:
      - c:\temp\foo:/data
```

`docker-compose --verbose up`

Returns the error:
```
docker-bug  > docker-compose --verbose up
compose.config.config.find: Using configuration files: .\docker-compose.yml
docker.auth.auth.load_config: File doesn't exist
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose\cli\main.py", line 61, in main
  File "compose\cli\main.py", line 110, in perform_command
  File "compose\cli\command.py", line 35, in project_from_options
  File "compose\cli\command.py", line 110, in get_project
  File "compose\cli\command.py", line 85, in get_client
  File "site-packages\docker\api\daemon.py", line 76, in version
  File "site-packages\docker\utils\decorators.py", line 47, in inner
  File "site-packages\docker\client.py", line 140, in _get
  File "site-packages\requests\sessions.py", line 477, in get
  File "site-packages\requests\sessions.py", line 465, in request
  File "site-packages\requests\sessions.py", line 594, in send
  File "site-packages\requests\sessions.py", line 196, in resolve_redirects
  File "site-packages\requests\sessions.py", line 573, in send
  File "site-packages\requests\adapters.py", line 433, in send
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='proxy.company.com', port=8080): Read timed out. (read timeout=60)
docker-compose returned -1
```

I've tried different volume statements and they all fail:
```
- c:/temp/foo:/data
```
```
- /c:/temp/foo:/data
```
```
- /temp/foo:/data
```

**Comment by dgageot** [comment]
Hi @vorpleblade it doesn't look like an issue with volume mounting to me.

This error in the compose output seems to point to the actual issue: `requests.exceptions.ReadTimeout: HTTPConnectionPool(host='proxy.company.com', port=8080): Read timed out. (read timeout=60)`.

It looks like compose is trying to connect to `proxy.company.com` rather than to the docker daemon

**Comment by vorpleblade** [comment]
I edited the output value.  The proxy server is available and used when building docker images.

**Comment by dgageot** [comment]
Thank you @vorpleblade, I'm glad your issue is solved. Can I close the issue then?

**Comment by vorpleblade** [comment]
Thanks @dgageot please close the issue.
