### ISSUE TITLE
Copying files to external shared drive fails

### ISSUE THREAD

**Issue by alebianco** [docker/for-win#661]
### Expected behavior

Copying large files to external USB drives completes without errors.

### Actual behavior

Copying large files to external USB drives files fails and part of the file is missing in destination folder.

The `cp` command terminates with the message:
`cp: error writing to '/out/test.bin': I/O error`

The larger the file, the higher the chance of a failure. a 300mb file is almost certain to fail the test.

Using **ubuntu** instead of **alpine** yields the same result with a slightly different error message.

### Information

  - Diagnostic ID: A46EA3FB-5008-4A51-AE09-C216295BFD3E/2017-04-20_23-38-53
  - Windows 10 Pro (10.0.15063 Build 15063)
  - Version 17.03.1-ce-win5 (10743) stable b18e2a5

### Steps to reproduce the behavior

  1. From the Docker settings, share the target drive (`E:` in my case) and apply the changes
  2. From a shell run this command
`docker run --rm -v E:/out:/out alpine sh -c "dd if=/dev/urandom of=random.bin bs=1038336 count=300 && cp random.bin /out/test.bin"`

### Temporary solution

Keep using **Docker 1.12.1-beta24** (yes, this is a terrible workaround...)

**Comment by alebianco** [comment]
would be supercool to have some kind of acknowledgement of the report 🙈

**Comment by jonscheiding** [comment]
I have experienced this as well.

**Information**

- Diagnostic ID: 8529DFA3-1774-4DE8-B8E1-8B4193687162/2017-09-27_11-58-40
- Windows 10 Pro Version 10.0.15063 Build 15063
- Docker Version 17.06.2-ce-win27 (13194) stable 428bd6c
- The bind-mounted directory is on an NTFS file system

I've seen this error in various different ways:

- `tar -czf /mount/archive.tar.gz /large-dir`
- `mv /archive.tar.gz /mount`
- `dd if=/archive.tar.gz of=/mount/archive.tar.gz`

All of these fail with some variation on "Failed to close: input/output error".  The data all seems to copy, but then there is a pause, which I assume represents some kind of flush to the host filesystem, and then this error.  It only happens with large files: the one I am dealing with is between 5GB-6GB.

It doesn't fail every time.  I've had more success using `tar` without compression.  Once I also tried `pv archive.tar.gz > /mount/archive.tar.gz` and that worked.

**Comment by jonscheiding** [comment]
Follow up: I did a "Reset to factory defaults" and it seems to have resolved my problems.

I'm not sure what the problem might have been, as this was a brand new Windows installation.  But possibly it had to do with the fact that I installed Windows 10 Anniversary Update _after_ installing Docker.  That's my only guess.

**Comment by alebianco** [comment]
@jonscheiding damn, I just formatted my machine in the hope you were right

I can add a piece of information though, folders mounted from FAT32 drives seems to work fine, NTFS drives fail consistently

**Comment by alebianco** [comment]
I started digging on the mount options today

this are the mount options of my drive:
//10.0.75.1/E on /E type cifs (rw,relatime,vers=3.02,sec=ntlmssp,cache=strict,username=*****,domain=*******,uid=0,noforceuid,gid=0,noforcegid,addr=10.0.75.1,file_mode=0755,dir_mode=0755,iocharset=utf8,nounix,serverino,mapposix,nobrl,mfsymlinks,noperm,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)

I found a way to change the mount options, and setting *cache=none* seems to solve the issue!
Now i'm trying to figure out why the cifs cache is causing problems

If only the Docker team would take an interest in the ticket ...

**Comment by jonscheiding** [comment]
@alebianco I was afraid I would have to convert my volumes to FAT32.  How did you change those options?  Did you just mount/unmount from within the container, or is there a more durable way?

**Comment by alebianco** [comment]
No, it's not maintainable nor durable. It's also very insecure. Basically I wouldn't use this for no application except debugging the issue ...

You have to run the container as privileged  (--privileged --pid=host) and hijack the mounts from within providing the host credentials manually.

If you want to give it a shot and you're using **alpine** as a base, it goes like this:
```
apk update
apk add util-linux
rm -rf /var/cache/apk/*
nsenter --target 1 --mount --uts --ipc --net --pid /bin/sh
```
then you can unmount and re-mount the host folders manually. In my case it's something like:
```
umount /E
mount -t cifs //10.0.75.1/E /E -o rw,relatime,vers=3.02,sec=ntlmssp,cache=none,username=<host-username>,domain=<host-domain>,passowrd=<host-password>,uid=0,noforceuid,gid=0,noforcegid,addr=10.0.75.1,file_mode=0755,dir_mode=0755,iocharset=utf8,nounix,serverino,mapposix,nobrl,mfsymlinks,noperm,rsize=16384,wsize=57344,echo_interval=60,actimeo=1
```
After that you can use the _/E_ mount as regular and moving files there shouldn't fail. 

I did notice there's a hit on performances, it's something like 25% slower than expected but at least it works ...

**Comment by jonscheiding** [comment]
@alebianco Thanks, remounting with `cache=none` has also got rid of the problem for me.  You're right, though, it's not suitable as a permanent workaround.

I opened a new ticket (#1154), maybe it will get some attention.

**Comment by lunchboxwu** [comment]
@alebianco Your solution works for me too. Thanks. 

But I still hope this issue could be solved in the near future.

**Comment by alebianco** [comment]
thanks @lunchboxwu it's cool that this is helping someone one, even if just by avoiding some headaches.
I ended up stopping using Docker completely, it's absurd I didn't even get a reply from the team after more than a year, even if only to acknowledge the report and say that I'm dead wrong 😠

**Comment by jonscheiding** [comment]
@lunchboxwu @alebianco In case it's of interest to you guys, I seemingly can't reproduce this problem any more as of version 17.12.0-ce-win47.

**Comment by cdalexndr** [comment]
Still an issue with Docker version 19.03.5, build 633a0ea.
Trying to move a 1.5GB file from docker volume to mounted ntfs dir.
`mv: error writing to '/dest/db.tar': I/O error`
