### ISSUE TITLE
Access containers by IP in WSL2 Ubuntu 20.04 with Docker Desktop Edge with WSL2 backend

### ISSUE THREAD

**Issue by alexchiri** [docker/for-win#6610]
In "normal" Ubuntu with Docker, you can access containers using their IP (that you determine from  "docker container inspect id").

I know there are many things that are different in the setup with Ubuntu in WSL2 and Docker Desktop for Windows Edge with WSL2 backend, but I am wondering if there is any way to access containers using their IP in this setup? If not, what is preventing that from happening? Is it a design decision or a bug or configuration? 

As far as I know, accessing containers by private IP is not encouraged or an advertised feature, so I know what I'm asking here is rather "niche". I find it useful when using Kubernetes in Docker in WSL and to be able to connect to the "nodes" IPs directly.

I have tried to do this on Window 10 2004 with WSL2 and Docker Desktop with WSL2 backend 2.3.0.1, from a Ubuntu 20.04 running in WSL2, but it doesn't work in the "default" setup.

### Steps to reproduce the behavior

- Run a Docker container from Ubuntu WSL2 and keep it running
- Get its private IP using `docker container inspect id`
- ping IP from Ubuntu WSL2 and expect a reply

**Comment by alexchiri** [comment]
Found workaround for this: don't use Docker Desktop with WSL2 backend if you need to connect to Docker containers by private IPs in WSL2. Just install Docker CE normally in the WSL2 distribution. Also, don't use Ubuntu 20.04 for this, there are some issue with installing Docker CE in it.

**Comment by helzgate** [comment]
I used docker desktop with no problem.  I just had to use the Remote-Development extension (that also supports WSL) instead of the Remote-WSL extension.  The instructions found [here](https://code.visualstudio.com/docs/remote/containers) show items to install in Windows and Linux but you shouldn't have to install any of that (especially NOT the Linux instructions).  After connecting to a "remote-try-node" container from VSCode and running the demo server, I was suprised that I could connect to it from another computer with no issue.

**Comment by alexchiri** [comment]
@helzgate those are some really cool extensions and features that I had no idea about! Clarification question: when you say running and connecting to the demo server, what do you mean? What steps did you do to achieve that?

My impression is that VS Code is attaching to containers and then you can expose ports on the local host when needed, but it does not connect to the IP address of the Docker container. For the limited use case I have, I want to be able to ping the IP of the container for example or to connect to one of its ports directly using its private IP. 

I started a container using VS Code Remote Container extension and from a network perspective it looks pretty much the same with a normal container started in the default bridge network. I think the issue is that it is simply not possible to do this (connect directly to the private IP of a Docker container from the host) when using Docker for Windows (or for Mac as a matter of fact) and that it only works in containers running in Docker for Linux.

**Comment by helzgate** [comment]
@alexchiri step 2 under [QuickStart](https://code.visualstudio.com/docs/remote/containers#_quick-start-try-a-dev-container) in the instructions I provide above show you how to quickly get a little demo server up and running.

**Comment by paolomainardi** [comment]
@alexchiri can you please describe the workaround you mentioned before ? I confirm the bug on Ubuntu 20.04 indeed, going to try 18.04.

**Comment by alexchiri** [comment]
@paolomainardi I don't think it's a bug, I think it's how [it's documented it should work in Docker for Windows](https://docs.docker.com/docker-for-windows/networking/#per-container-ip-addressing-is-not-possible) and Docker for Mac. The confusion, in this case, is that with Docker with WSL2 backend we are using Docker from the Linux WSL, but it is still the Docker for Windows we are running the containers in, which is why we cannot access containers by private IPs.

The workaround is to not use Docker for Windows with WSL2 backend to run Docker in the WSL distros, but install Docker as you would in any Linux distribution, as described in [Docker's official page](https://docs.docker.com/engine/install/ubuntu/).

**Comment by paolomainardi** [comment]
@alexchiri yes, thanks for the explanation, but the question was related to the fact that when i tried to install a docker container on WSL2 on a standard Ubuntu 18.04 i cannot access private ips from Windows.

**Comment by alexchiri** [comment]
As far as I understand the docs, with Docker for Windows you cannot access Linux containers by private IP from the host. It seems to only work with Windows containers.

**Comment by paolomainardi** [comment]
Can you access Linux containers by IP using just WSL2 ?

**Comment by alexchiri** [comment]
Yes. I managed to do that using the Ubuntu 18.04 distro in WSL2 and installing Docker for Linux in it as you would install it in any normal Ubuntu installation.

**Comment by paolomainardi** [comment]
@alexchiri are you sure about that ? if you run a container on ubuntu wsl2, without any kind of port mapping, you can access docker private ips from Windows ? I have just tried now (as i did in the past) by running a simple nginx webserver and i cannot access it from Windows.

**Comment by paolomainardi** [comment]
This is the test case.

WSL2:
``` 
root@LAPTOP-NLLFFOFU:/home/paolo# docker run -d nginx:alpine
9f4ff65a76eee27c033af016b7209b4693299898d8f5bbe38bd1ad98b5e37a49
INFO[2020-05-25T22:29:17.695815700+02:00] shim containerd-shim started                  address=/containerd-shim/bf6a7f8f7d2c3e72c32dd9ad30ad71b9d26bc045e83d42af5291d82534da4bf9.sock debug=false pid=2356
root@LAPTOP-NLLFFOFU:/home/paolo#
root@LAPTOP-NLLFFOFU:/home/paolo#
root@LAPTOP-NLLFFOFU:/home/paolo# docker inspect 9f4 | grep IPAddre
            "SecondaryIPAddresses": null,
            "IPAddress": "172.17.0.2",
                    "IPAddress": "172.17.0.2",
root@LAPTOP-NLLFFOFU:/home/paolo# curl 172.17.0.2
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

**Comment by alexchiri** [comment]
@paolomainardi not from Windows, if you run a Linux container in Ubuntu WSL2 running Docker for Linux in that Ubuntu, you can access the Linux container from the Ubuntu WSL2 using the container's private IP. As mentioned above, using Docker for Windows, from WSL2 or Windows directly, you cannot access Linux containers using their private IPs.

**Comment by paolomainardi** [comment]
Ok so you confirm that you cannot access containers from Windows, clear.

**Comment by quanhongnguyen** [comment]
@alexchiri as far as i known docker daemon is able to start on ubuntu wsl 2. How did you get it working ?

**Comment by alexchiri** [comment]
@quanhongnguyen I think I need more context to be able to answer your question. Are you talking about the docker daemon from Docker for Linux installed inside of Ubuntu? Or is it the Docker daemon coming from Docker for Windows that is accessed from WSL2? And did you mean that Docker Daemon is **not** able to start in WSL2 in your question?

**Comment by notresponding2u** [comment]
Hi,

I am having the same issue - I have:

**Ubuntu 20.04 LTS** installed on wsl 2;

**Client: Docker Engine - Community** installed according to the ubuntu guide in the official page (not docker on windows)
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:44 2020
 OS/Arch:           linux/amd64
 Experimental:      false 

I have it running, with few containers, there are RabbitMq asd portainer. I cannot access neither of them from the windows host system (win 10 home). I have tried adding inbound rules in windows, but no luck.

I have been googling it for a while, and some say that ubuntu 20 does not get the ipv6 ports forwarded, and tried to apply solution for it. Could that be the case and I am doing it wrong?

I ll try the 18.04 as suggested

> @alexchiri yes, thanks for the explanation, but the question was related to the fact that when i tried to install a docker container on WSL2 on a standard Ubuntu 18.04 i cannot access private ips from Windows.

**Comment by notresponding2u** [comment]
It did not work for me.

**Comment by theAkito** [comment]
I want to access a server in a Docker container, running in WSL2, from the Windows host. Is it possible or not?

**Comment by marlocarlo** [comment]
There's no solution to accessing the docker container under wsl2? That's it ?

**Comment by theAkito** [comment]
@marlocarlo 

I managed to access a server in a Docker container, which has an exposed port.

1. This port needs to be let through the Firewall. Every normal Windows 10 will automatically ask for it.
2. Find out the IP of your WSL session. You can do that with `ip a` within WSL2.
3. Connect to the server with the address of the WSL session and exposed port of the Docker container.
4. Example target Docker container address:
```
172.28.4.35:51234
```
