### ISSUE TITLE
Error on attempting to enable WSL2

### ISSUE THREAD

**Issue by fdavidg** [docker/for-win#6611]
I attempted to enable WSL2 in the setting check box and received and error. I now can not access the settings page or Docker!

Here is the error message:
Docker.Core.Backend.BackendException:
Failed to deploy distro docker-desktop to C:\Users\user\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout(utf8): E
 I can not attach the log.txt file as it is to big per your restrictions!

  - [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID:38FE18A0-5B31-462C-A8C8-587A0C3D8454
[20200510172431.zip](https://github.com/docker/for-win/files/4606308/20200510172431.zip)

### Information

  - Windows Version: Windows 10 Pro version 2004 20H1 10.0.19041.208
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: NO

### Steps to reproduce the behavior

  1. In setting I checked the box to enable WSL2

  2. ...

[diagnostics.log](https://github.com/docker/for-win/files/4606267/diagnostics.log)
[log1.txt](https://github.com/docker/for-win/files/4606268/log1.txt)
[20200510163428.zip](https://github.com/docker/for-win/files/4606309/20200510163428.zip)

**Comment by simonferquel** [comment]
This is a WSL issue related to HNS and a bug whenever a process is listening to port 53 on an HNS interface.
Can you check with netstat if a process is indeed listening on port 53 on Windows ?
