### ISSUE TITLE
Docker Desktop - "WSL 2 is not Installed" prompt when trying to enable WSL 2 based engine

### ISSUE THREAD

**Issue by erincar** [docker/for-win#6612]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3E458A6E-E192-433C-BDCD-E65B7AD230FA/20200510175413

#### Applying & restarting...
![Docker_Desktop_2020-05-10_20-52-50](https://user-images.githubusercontent.com/11043332/81506940-6f046c80-9302-11ea-9141-f6088b12846a.png)

#### ...then succeeding in applying changes & restarting
[didn't happen]

#### Applying & restarting...
![Docker_Desktop_2020-05-10_20-52-50](https://user-images.githubusercontent.com/11043332/81506940-6f046c80-9302-11ea-9141-f6088b12846a.png)

#### ...then failing with this error prompt:
![Docker_Desktop_2020-05-10_20-53-06](https://user-images.githubusercontent.com/11043332/81506941-70ce3000-9302-11ea-9ce1-283b0d4c8482.png)

### Information
Hello good people of Docker Community, my issue is regarding the "WSL 2 is not installed" error I'm receiving on native Windows 10, build 2004. The error is mistaken because I actually have WSL 2 installed, but I have it installed in a custom folder in my secondary disk, under `D:\WSL\`.

The problem appeared after I updated to version 2004, updated Docker to most recent version and installed WSL 2, which was the first time I expected it to work on my system, it failed at my first try on this system.

I am suspecting that Docker Desktop expected a WSL installation in its default location, and failed to find my installation in a custom folder.

  - Windows Version: Version 2004, OS Build 19041.208
  - Docker Desktop Version: 2.2.0.5 (43884) - Stable
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
  1. Install WSL with Ubuntu 18.04 *to a custom folder in secondary disk*, e.g. `D:\WSL\` - Update to WSL2
  1. Open Docker Desktop > Settings
  2. Enable `Enable the experimental WSL 2 based engine` option
  3. Click `Apply & Restart`

**Comment by simonferquel** [comment]
Hi,
We don't check the distro installation directory (we run within our own distro). Can you send me your docker desktop log file ? (We have an issue with diagnostic files in 2.2.0.5)

**Comment by erincar** [comment]
Hello,

Thanks for your help. While I was trying to reproduce the issue for logging purposes, my Docker Desktop has crashed and then prompted an update to 2.3.0.2. After updating, I am able to successfully enable the WSL2 engine. Appreciated!

**Comment by mat007** [comment]
Thanks, I’ll go ahead and close this issue now then.
