### ISSUE TITLE
Hyper-V configuration issue, Docker running on a virtual machine

### ISSUE THREAD

**Issue by ayushraj11** [docker/for-win#6614]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 6ACC302A-1006-4446-B5EA-49B0EBDA33D5/20200509130003

### Expected behavior
Docker starts normally
### Actual behavior
Docker crashes with an error report and fails to start
### Information

  - Windows Version: 1809 (OS Build 1763.720)
  - Docker Desktop Version: Community Version 2.2.0.43884
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
Yes, on a VDI machine (DWS_SBDC_Virtual_Workspace)
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mat007** [comment]
Docker Desktop is not supported in a virtualised environment. It might work or it might not, but it's out of our control, it depends on whether the outer virtual machine supports nested virtualisation.
For more information see https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-desktop-in-nested-virtualization-scenarios.
