### ISSUE TITLE
Docker Windows Container Network

### ISSUE THREAD

**Issue by niyuzheno1** [docker/for-win#6617]
Can't ping to google on docker:
Dockerfile:
FROM mcr.microsoft.com/windows/nanoserver:1809

Output in command prompt:
C:\>ping www.google.com
Ping request could not find host www.google.com. Please check the name and try again.

C:\>ipconfig /all

Windows IP Configuration

   Host Name . . . . . . . . . . . . : 897ccaa5bc8f
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   DNS Suffix Search List. . . . . . : lan1

Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . : lan1
   Description . . . . . . . . . . . : Microsoft Hyper-V Network Adapter
   Physical Address. . . . . . . . . : 00-15-5D-1A-AF-81
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::1cc1:129e:dd91:9d3d%4(Preferred)
   IPv4 Address. . . . . . . . . . . : 172.18.35.21(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . : 172.18.32.1
   DHCPv6 IAID . . . . . . . . . . . : 67114333
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-26-4A-9F-61-00-15-5D-1A-AF-81
   DNS Servers . . . . . . . . . . . : 172.18.32.1
                                       192.168.1.1
   NetBIOS over Tcpip. . . . . . . . : Disabled

**Comment by niyuzheno1** [comment]
Issue ID:F91037B6-E78A-4719-9ABF-622EBB45A0F9/20200511055236

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place?
Sorry, I would move it myself, but I can't because it's in a different org (it's `moby` not `docker`).
