### ISSUE TITLE
Docker stopped working since last Windows insider update.

### ISSUE THREAD

**Issue by Mitschiro** [docker/for-win#6618]
- [x ] I have tried with the latest version of my channel (Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 8BAC5FF9-49ED-40A8-B743-4DC2D7B5C19A/20200511070307

### Expected behavior
Docker should start / restart.

### Actual behavior
On startup Docker goes into an Error state (red icon), when clicking on the restart button, Docker crashes with:

`Docker.ApiServices.StateMachines.InvalidTransitionException:
Cannot stop from an unstable state
   at Docker.ApiServices.StateMachines.UnstableState.Docker.ApiServices.StateMachines.IInternalEngineState.BeginStopAsync()
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StopAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<RestartAsync>d__29.MoveNext()`

- I tried with the current Docker version and the one before, both behave the same way. I tried uninstalling and reinstalling Docker. Same behavior.
- WSL 2 is running and working.

I think the most recent windows insider update just blew something up.

### Information
  - Windows Version: 10.0.19624 Build 19624
  - Docker Desktop Version: 2.3.0.0 and 2.3.0.1
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No.

### Steps to reproduce the behavior

  1.  Start Docker. Docker goes into error state.
  2. Restart Docker, Docker crashes.

Thanks for your work.

**Comment by ivail89** [comment]
I have the same bug, Diagnostics ID EE8A9A26-0BA8-4110-AF74-565713BD2163/20200515084804

**Comment by Jelle-zonder-k** [comment]
Same error here, did anyone find a solution yet?

**Comment by solovyov-private** [comment]
The same bug on a fresh win from the slow ring
Windows Version: 10.0.19041 Build 19041.264
Docker Desktop Version: 2.3.0.2
Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No.

Diagnostic ID: 20B73EA4-8C58-45BB-ABF5-2BDB4502C371/20200518080321

**Comment by samuel14find** [comment]
The same bug:
Windows Version: 2004 Build 19041.264
Disable integration with WSL2 the docker will work again. However very slow.

**Comment by solovyov-private** [comment]
I have made this work nice on WSL2 now! But too stupid to explain the root of solution.
Steps I performed:
- installed OpenSUSE from MS Store to work directly (as I have a fresh Win installation w/nothing), ensured that it has wsl version 2 
`wsl -l -v`
- uninstalled Docker
- unregistered stuck Docker subsystem, this state was still showing as "Installing"
`wslconfig /u docker-desktop`
- ensured that new containers use wsl2
`wsl --set-default-version 2`
- installed Docker again... Started OK.

**Comment by samuel14find** [comment]
Thank you. It worked here. I suspected that docker-desktop.

**Comment by Mitschiro** [comment]
Thanks mate! This works as expected for me.

I hope Docker fixes this though because it is not obvious what to do when this happens. I also reinstalled Docker etc before, but i did not had the wslconfig on my radar.

I also had "docker-desktop-data" still lingering around. So i added one more step to what @solovyov-private posted: `wslconfig /u docker-desktop-data`

---------
Solution from @solovyov-private 

> I have made this work nice on WSL2 now! But too stupid to explain the root of solution.
> Steps I performed:
> 
> * installed OpenSUSE from MS Store to work directly (as I have a fresh Win installation w/nothing), ensured that it has wsl version 2
>   `wsl -l -v`
> * uninstalled Docker
> * unregistered stuck Docker subsystem, this state was still showing as "Installing"
>   `wslconfig /u docker-desktop`
> * ensured that new containers use wsl2
>   `wsl --set-default-version 2`
> * installed Docker again... Started OK.

**Comment by brezanac** [comment]
> I have made this work nice on WSL2 now! But too stupid to explain the root of solution.
> Steps I performed:
> 
> * installed OpenSUSE from MS Store to work directly (as I have a fresh Win installation w/nothing), ensured that it has wsl version 2
>   `wsl -l -v`
> * uninstalled Docker
> * unregistered stuck Docker subsystem, this state was still showing as "Installing"
>   `wslconfig /u docker-desktop`
> * ensured that new containers use wsl2
>   `wsl --set-default-version 2`
> * installed Docker again... Started OK.

This actually fixes the problem.

I've experiemented a bit on a couple of freshly installed Win 10 2004 machines and it turns out that setting WSL to version 2 **right after** installing WSL and **before** installing Docker or any WSL distribution, prevents the issue from happening.

I initially tried to convert an existing WSL distro to version 2 and all it did is put docker-desktop into an endless "Installing" state.

**Comment by hasayakey** [comment]
netsh winsock reset

**Comment by deanflyer** [comment]
Same issue here Windows 10 2004 (19041.264). Installed and configured WSL 2 as per MS instructions, but stuck with docker-desktop shown as installing... (`wsl -l -v`). Uninstalling docker desktop, and unregistering using `wslconfig /u docker-desktop` and reinstalling docker desktop did the trick.

**Comment by curry684** [comment]
Why was this issue closed if the underlying issue is not yet fixed?

Just managed to reproduce this by blowing up Docker with a far too huge docker-compose environment. Was all working until it launched Elasticsearch.... now stuck in dead installing state.

**Comment by Mitschiro** [comment]
I closed it because solutions where found, obv not from the Docker team directly.
But i see why closing it might be an issue. I reopen the issue.

**Comment by miguelangelbg** [comment]
> I have made this work nice on WSL2 now! But too stupid to explain the root of solution.
> Steps I performed:
> 
> * installed OpenSUSE from MS Store to work directly (as I have a fresh Win installation w/nothing), ensured that it has wsl version 2
>   `wsl -l -v`
> * uninstalled Docker
> * unregistered stuck Docker subsystem, this state was still showing as "Installing"
>   `wslconfig /u docker-desktop`
> * ensured that new containers use wsl2
>   `wsl --set-default-version 2`
> * installed Docker again... Started OK.

The key thing for me was the command.
`wslconfig /u docker-desktop`
Once I unregistered the stuck docker subsystem I could install Docker again having the Ubuntu WSL distribution.

**Comment by devplayg** [comment]
> I have made this work nice on WSL2 now! But too stupid to explain the root of solution.
> Steps I performed:
> 
> * installed OpenSUSE from MS Store to work directly (as I have a fresh Win installation w/nothing), ensured that it has wsl version 2
>   `wsl -l -v`
> * uninstalled Docker
> * unregistered stuck Docker subsystem, this state was still showing as "Installing"
>   `wslconfig /u docker-desktop`
> * ensured that new containers use wsl2
>   `wsl --set-default-version 2`
> * installed Docker again... Started OK.

Thank, It works.
Ubuntu 18.04 also works instead of openSUSE.

**Comment by JPumpkin** [comment]
> I have made this work nice on WSL2 now! But too stupid to explain the root of solution.
> Steps I performed:
> 
> * installed OpenSUSE from MS Store to work directly (as I have a fresh Win installation w/nothing), ensured that it has wsl version 2
>   `wsl -l -v`
> * uninstalled Docker
> * unregistered stuck Docker subsystem, this state was still showing as "Installing"
>   `wslconfig /u docker-desktop`
> * ensured that new containers use wsl2
>   `wsl --set-default-version 2`
> * installed Docker again... Started OK.

Thanks, It works for me.
