### ISSUE TITLE
Unable to mount C drive: firewall is blocking

### ISSUE THREAD

**Issue by pasblin** [docker/for-win#662]
### Expected behavior
share c drive whith docker containers
### Actual behavior
Unable to mount C drive: firewall is blocking
### Information
  - OS : Microsoft Windows 10 pro , version : 10.0.15063 compilation 15063
  - Docker version Version 17.03.1-ce-win5 (10743) Channel: stable b18e2a5
  - Diagnostic ID 52F73CBD-D905-4DCD-AE85-8BA14B8512CC/2017-04-21_09-38-00
  - Today after updating windows I can not share my C disk in docker through settings
  - I have no antivirus and I tried disabling the windows firewall

**Comment by kpantos** [comment]
Same issue here.

**Comment by dariomehr** [comment]
Same issue.
I was working nice and suddenly i can't access to localhost.
Apache didn't find files like index.html in /var/www/html because was empty.
So, I uncheck and check share C drive, then appears "A firewall is blocking file Sharing between Windows and the containers". But there is not firewall or AV blocking.

**Comment by simonferquel** [comment]
We have done some improvement that should be there in next edge build (17.05.0-rc2). Please stay tuned

**Comment by khaliullov** [comment]
@simonferquel I've just tried binaries from 17.05.0-rc2 (docker.exe and dockerd.exe, restarted service) but have no luck:
"A firewall is blocking file Sharing between Windows and the containers. See documentation for more info."

firewall is disabled.
Samba share was deleted by Docker after trying to enable it in Settings.

Diagnostic id: 4142E57A-AFB8-4DCE-A46D-1ED455E849F8/2017-04-28_10-03-18
Docker version 17.05.0-ce-rc2, build c57fdb2

**Comment by khaliullov** [comment]
the only workaround that worked for me is described here: https://github.com/docker/for-win/issues/530#issuecomment-293565549

**Comment by jasonterando** [comment]
Hi, does the recent 17.03.1-ce-win12 release include any updates regarding this issue?

**Comment by friism** [comment]
@jasonterando can you try an edge release, currently 17.05?

**Comment by jasonterando** [comment]
@friism - sure thing, I'll kick the tires this weekend and let you know how it goes.  Thanks

**Comment by ahgyger** [comment]
@friism just tried on Version 17.05.0-ce-win11 (12053). Still not working... on win 1703.

**Comment by jasonterando** [comment]
@friism - edge seems to be working much better for me.  On installation, I had to reshare the C: drive, but after that, things seem pretty reliable.  Will be hitting it harder starting tomorrow, I had family in from out of town.  Will keep you updated.
