### ISSUE TITLE
[question] docker desktop resource configuration file

### ISSUE THREAD

**Issue by dilox** [docker/for-win#6621]
I would like my program to know how much memory docker desktop can allocate and alert the user if it is < 4GB, before starting containers.
So, in which file docker desktop store information like resources memory, cpu and swap?
I already tried with $USER\.docker\config.json and daemon.json with no luck.
I found something using docker info, but I am not so sure...
Tnx in advance, Pierluigi

**Comment by mat007** [comment]
Hi @dilox, I believe the file you’re looking for is `%APPDATA%\Docker\settings.json`?

**Comment by dilox** [comment]
Thanks,  @mat007
