### ISSUE TITLE
unexpected EOF while login using cli, or pulling images

### ISSUE THREAD

**Issue by integer88** [docker/for-win#6622]
- [X] I have tried with the latest version of my channel (Stable or Edge) => both (2.2.0.43884, 2.3.0.44875)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 7EB7D9D2-BE96-4B7B-BD12-B20EA9F09B19/20200511125332

### Expected behavior
In case of using the command `docker login` I would expect a logged in response. In case of pulling an image, I would expect pulling the image.

### Actual behavior
I get an error message, every time I use any command, that connects to docker hub:
`Error response from daemon: Get https://registry-1.docker.io/v2/: Get https://auth.docker.io/token?account=integer88&client_id=docker&offline_token=true&service=registry.docker.io: unexpected EOF`
### Information

  - Windows Version: Windows 10 2004 (Build 19041.208)
  - Docker Desktop Version: 2.3.0.1
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

I had docker installed a long time ago. I uninstalled it.
Now I reinstalled latest docker desktop (I tried stable, and I tried edge => same behaviour with both versions).
I also use WSL2 on the same PC.

### Steps to reproduce the behavior

I don't know, how to reproduce this behaviour on another PC. I just installed docker, and the error occurs with each command, that connects to docker hub, e. g.
```
docker login
docker pull alpine
docker run hello-world
```

**Comment by Supportic** [comment]
I am getting the same error again and again. It doesn't work when I try to login with my PW but it works with an KEY created on hub.docker.com > account > security. As soon as I want to pull any image it gives me again an error msg.
"Error response from daemon: Get https://registry-1.docker.io/v2/docker/getting-started/manifests/latest: Get https://auth.docker.io/token?account=<account>&scope=repository%3Adocker%2Fgetting-started%3Apull&service=registry.docker.io: unexpected EOF."

The funny thing is that login with my PW in the GUI works.

**Comment by SangNguyenTL** [comment]
> I am getting the same error again and again. It doesn't work when I try to login with my PW but it works with a KEY created on hub.docker.com > account > security. As soon as I want to pull any image it gives me again an error msg.
> "Error response from daemon: Get https://registry-1.docker.io/v2/docker/getting-started/manifests/latest: Get https://auth.docker.io/token?account=accountName&scope=repository%3Adocker%2Fgetting-started%3Apull&service=registry.docker.io: unexpected EOF."
> 
> The funny thing is that login with my PW in the GUI works.

I got the same error, it's confusing.
There's more. I just get the "EOF" message instead of knowing what the problem is.

**Comment by SangNguyenTL** [comment]
There was a problem with GameFirst VI, after I turned it off everything worked properly. I think anyone using Asus laptops have this software. Turn it off.

**Comment by ThaDaVos** [comment]
@SangNguyenTL - Only the gamer laptops have that software and only if people kept it installed -> I also have a Asus Laptop but I uninstalled GameFirst as I was having other issues as well because of it
