### ISSUE TITLE
Docker Desktop 2.3.0.2 stable - K8s cluster does not start

### ISSUE THREAD

**Issue by gillesdouaire** [docker/for-win#6627]
- [X] I have tried with the latest version of my Stable channel 2.3.0.2
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 
538974A4-2382-43B2-B6A9-39D2147CA522/20200511163545
6A9CF06B-C780-42FF-825B-3FB006CFFE55/20200511163959

### Expected behavior
K8s should startup and run within a couple of minutes.

### Actual behavior
K8s cluster does not run even after 10 minutes of spining. Resetting the K8s cluster does not work either.

### Information
  1. Update to 2.3.0.2 stable
  2. Start Docker Desktop; the K8s cluster will stay "starting" mode forever.

Tested on two different machines -- that's why there is two diagnostic ID in this ticket.

**Comment by stephen-turner** [comment]
@gillesdouaire Have you successfully started k8s on earlier versions of Docker Desktop?

**Comment by gillesdouaire** [comment]
@stephen-turner yes, it was working fine on both machines before this update

**Comment by stephen-turner** [comment]
We do have a new version of Kubernetes in this version, so most likely it's due to an upstream change. We are aware that there always seems to be a small proportion of people who can't start Kubernetes, which is frustrating to us as we haven't been able to spot the pattern.

**Comment by gillesdouaire** [comment]
oh. and no traces of that is broken in the Diagnostics?

**Comment by gillesdouaire** [comment]
What is the new K8s version ? I guess it was linked to release 2.3.0.0 or 2.3.0.1, but we don't see these in the stable channel release notes:

**Comment by gillesdouaire** [comment]
oh ok. v1.16.5

**Comment by ulrich** [comment]
@gillesdouaire you probably encounter an certificate issue, Try to delete manually the PKI folder of Docker Desktop and restart Docker Desktop.

> C:\Users\YOU\AppData\Local\Docker\pki

Thank you for your feedback.

**Comment by zssng** [comment]
Sometimes i make mistake abount docker resource or network setting,and docker failed to start.The setting ui is busy so the only thing i can do is reset docker .When k8s failed to start ,i cannot access the config ui ,in the end ,i have to reset the full application too,which is sad.

**Comment by zssng** [comment]
> Sometimes i make mistake abount docker resource or network setting,and docker failed to start.The setting ui is busy so the only thing i can do is reset docker .When k8s failed to start ,i cannot access the config ui ,in the end ,i have to reset the full application too,which is sad.

I found %APPDATA%/docker/settings.json solve my problem.

**Comment by gillesdouaire** [comment]
@ulrich Thanks for the suggestion. I did the `C:\Users\YOU\AppData\Local\Docker\pki` folder delete, but the K8s cluster still does not want to go up after a Docker restart. The `pki` folder was re-created, however.

**Comment by gillesdouaire** [comment]
@zssng You are impling that modifying `%APPDATA%/docker/settings.json` works? I was under the impression that this file was not authoritative and modifying it would not change the actual Docker settings. Pretty sure I tested this in older versions and did not work...

**Comment by ulrich** [comment]
@gillesdouaire OK, sorry for the late response. Did you do a Kubbernetes cluster reset?

Can you resend a diagnostic again after delete PKI folder/reset Kubernetes cluster please?

**Comment by gillesdouaire** [comment]
1- deleted the pki folder
2- restarted docker
3- confirm the pki folder is re-created
4- docker starts, but K8s cluster does not start within 5 minutes
5- reset k8s cluster
6- docker starts, but k8s cluster does not start within 5 minutes
7- run diagnostics: 538974A4-2382-43B2-B6A9-39D2147CA522/20200513134036

**Comment by ulrich** [comment]
OK, it's maybe related to the use of corporate proxy. Can you test without the corporate proxy enabled?

Thanks for your feedback.

**Comment by gillesdouaire** [comment]
1-reset docker to factory default (no proxy configured)
2- start docker
3- enable k8s cluster
4-docker still runs, but k8s cluster does not start within 5 minute

**Comment by gillesdouaire** [comment]
Also tried configuring our corporate proxies, while using things like "localhost,127.0.0.1,kubernetes.docker.internal" in the no_proxy, but this does not work either.

**Comment by relief-melone** [comment]
I'm havind the same issue. 

(Diagnostics-ID E61695E8-4DA3-4111-8858-03B16296D9D2/20200519104022)

The etcd Pod is declining all requests because of problems with the certificate. I tried all points that used to work

- reinstalling completely (with complete removal of docker not just uninstall)
- deleting pki folder (which never got recreated)
- deleting .kube folder
- netsh port reserving config
- resetting to factory default

and various combinations of those. Nothing worked. Also I am experiencing this without beeing behind a corporate proxy and on my personal machine (from which the Diagnostics File is from)

**Comment by savamilovanovic** [comment]
Verify you have in etc\hosts file:
# Added by Docker Desktop
192.168.1.21 host.docker.internal
192.168.1.21 gateway.docker.internal
# To allow the same kube context to work on the host and the container:
**127.0.0.1 kubernetes.docker.internal**
# End of section
I had WebRoot locking my hosts file, so 127.0.0.1 kubernetes.docker.internal was not updated

**Comment by gillesdouaire** [comment]
thanks @savamilovanovic unfortunately, it does not work here.

**Comment by ulrich** [comment]
@gillesdouaire We are very sorry for you. Can you try to downgrade and test again? For that, you need to uninstall Desktop by the menu: Troubleshoot, Uninstall button.

The previous stable worked is available here : https://docs.docker.com/docker-for-windows/release-notes/#docker-desktop-community-2205

**Comment by relief-melone** [comment]
> 
> 
> Verify you have in etc\hosts file:
> # Added by Docker Desktop
> 
> 192.168.1.21 host.docker.internal
> 192.168.1.21 gateway.docker.internal
> # To allow the same kube context to work on the host and the container:
> 
> **127.0.0.1 kubernetes.docker.internal**
> # End of section
> 
> I had WebRoot locking my hosts file, so 127.0.0.1 kubernetes.docker.internal was not updated

didn't do anything here either :/ Still not running. Any info I can post additional to my previous comment to help?

**Comment by ulrich** [comment]
@relief-melone can you recursively list your **~/.kube** folder (with rights) ?

**Comment by relief-melone** [comment]
@ulrich thanks for the quick reply

A rather long list. I uploaded it here [https://gofile.io/d/mFB2db](url)

but theres nothing particularily special to it. everythings on 755. If you look at the Security Tab in Preferences of the folder
- System
- User
- Administrators
get full access

**Comment by semuserable** [comment]
Same problem, can't start the cluster. pki removal didn't help

```
Version: 2.3.0.2 (45183)
Channel: stable
Sha1: e9b671cd3cb844cb63ad6fd7c79a4d15424233c4
Started on: 2020/05/26 19:40:28.324
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 1909
Build: 18363
BuildLabName: 18362.1.amd64fre.19h1_release.190318-1202
```

**Comment by gillesdouaire** [comment]
soooooo.... what worked for me (behind a corporate proxy):

1- stopping docker completely
2- adding "kubernetes.docker.internal" to the Windows env NO_PROXY variable (not in the Docker Desktop setting tab of the app, that is left blank)
3- re-starting docker
4- re-setting the K8s cluster
5- it works

**Comment by gillesdouaire** [comment]
@ulrich Correct, however the difference is that when configuring it in the Docker Desktop proxy setting page (as I had tried previously), it did not work; it only worked as I updated the NO_PROXY as part of the Windows environment, likely because HTTP_PROXY and HTTPS_PROXY were also defined there.

**Comment by ulrich** [comment]
@gillesdouaire awesome 👍

**Comment by relief-melone** [comment]
@ulrich unfortunately I am having the same issue on my private machine which is not behind a proxy :/ Working fine on my business machine behind the proxy without the settings mentioned above.

**Comment by DavidBuzatu-Marian** [comment]
> @ulrich Correct, however the difference is that when configuring it in the Docker Desktop proxy setting page (as I had tried previously), it did not work; it only worked as I updated the NO_PROXY as part of the Windows environment, likely because HTTP_PROXY and HTTPS_PROXY were also defined there.



> soooooo.... what worked for me (behind a corporate proxy):
> 
> 1- stopping docker desktop completely
> 2- adding "kubernetes.docker.internal" to the Windows env NO_PROXY variable (not in the Docker Desktop setting tab of the app, that is left blank)
> 3- re-starting docker
> 4- re-setting the K8s cluster
> 5- it works
> 
> tested under Stable 2.3.0.3

After days of struggling, this worked for me as well. Thank you sir

**Comment by mwu2018** [comment]
Somehow my hosts file has the following entries.
```
# Added by Docker Desktop
192.168.1.101 host.docker.internal
192.168.1.101 gateway.docker.internal
host.docker.internal
gateway.docker.internal
```
It works again after replacing the last two lines with
```
192.168.1.21 host.docker.internal
192.168.1.21 gateway.docker.internal
```
However, the namespace I created and all deployments in it have been lost.
