### ISSUE TITLE
WSL Error

### ISSUE THREAD

**Issue by lucianoedipo** [docker/for-win#6629]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 22A48469-10E8-4A3D-B0B2-359E30F9EA8A/20200511174512

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by simonferquel** [comment]
the wslpath utility within our wsl distro is failing for some reason (from the logs: wslpath failed; stderr is "wslpath: C:\\Program Files\\Docker\\Docker\\resources\\wsl\\docker-wsl-cli.iso\n": exit status 1).
cc @benhillis, do you know of reasons why wslpath may fail ?
In the mean time, can you try to stop docker desktop, run `wsl --shutdown` in a terminal, and restart docker desktop ?

**Comment by benhillis** [comment]
What windows build?

**Comment by simonferquel** [comment]
This one is on build 19624. But I saw it on 19041 as well.

**Comment by benhillis** [comment]
An strace of the command would be useful, dmesg output, the usual suspects.
