### ISSUE TITLE
Mount source not adjusted when redeploying to Docker Swarm in WSL 2 distro

### ISSUE THREAD

**Issue by Darthmineboy** [docker/for-win#6631]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: CBBBD5D6-8FA3-4528-939F-9AA4575E8189/20200511172533

### Expected behavior
Volume bind path should stay the same when re-deploying the same Docker Compose file to Docker Swarm.

### Actual behavior
The volume bind path is correctly set (adjusted to WSL distro) when a Docker Compose file is deployed for the first time. When re-deploying the same unchanged Docker Compose file the volume bind path changes (unadjusted to WSL distro).

### Information

  - Windows Version: Windows 10 Pro - Version 2004 - OS build 19041.208
  - Docker Desktop Version: 2.3.0.2 (45183)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

I am running Docker Desktop on Windows 10 using the WSL 2 based engine. I have a WSL 2 distro running Ubuntu 18.04, and the WSL integration is enabled for the Ubuntu 18.04 distro. Docker Swarm is also initialized.

```
wsl --list -v
  NAME                   STATE           VERSION
* Ubuntu-18.04           Running         2
  docker-desktop-data    Running         2
  docker-desktop         Running         2
```

### Steps to reproduce the behavior

docker-compose.yml
```
version: '3.8'
services:
  busy:
    image: nginx
    volumes:
      - ./:/data
```
Inside the Ubuntu 18.04 distro I am deploying the above Docker Compose file to Docker Swarm. The Docker Compose specifies a service that mounts the current directory (e.g. /root/test) to the /data path inside the container.
  1. Create directory /root/test
  2. Place above docker-compose inside /root/test and enter the directory
  3. Run: `docker stack deploy --compose-file docker-compose.yml test`
  4. Run: `docker stack ps test`
```
     ID                  NAME                IMAGE               NODE                DESIRED STATE       CURRENT STATE           ERROR               PORTS
dmn1a7z0r7io        test_busy.1         nginx:latest        docker-desktop      Running             Running 6 seconds ago
```
  5. Observe that the service in the test stack is correctly running. Use the ID of the service in the next step
  6. Run: `docker inspect <ID>`
  7. Observe the mount source.
```
"Mounts": [{
  "Type": "bind",
  "Source": "/run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu-18.04/0d5741c3685fd8a3dfa04c2df3de917c5ea716b845d537d7bfcdedd74b42b051",
  "Target": "/data"
}]
```
  8. Again run: `docker stack deploy --compose-file docker-compose.yml test`
  9. Run: `docker stack ps test`
```
     ID                  NAME                IMAGE               NODE                DESIRED STATE       CURRENT STATE                      ERROR                              PORTS
mrqwyi5dinim        test_busy.1         nginx:latest        docker-desktop      Ready               Preparing less than a second ago
ia26o6mvccc4         \_ test_busy.1     nginx:latest        docker-desktop      Shutdown            Rejected 4 seconds ago             "invalid mount config for type…"
dmn1a7z0r7io         \_ test_busy.1     nginx:latest        docker-desktop      Shutdown            Shutdown less than a second ago
```
  10. Observe that errors are given even though we didn't make changes to the Docker Compose file: `invalid mount config for type`. Use the ID of the service with the error in the next step.
  11. Run: `docker inspect <ID>`
  12. Observe that the mount source has changed
```
"Mounts": [{
  "Type": "bind",
  "Source": "/root/test",
  "Target": "/data"
}]
```

What I believe is happening is that the first time the stack is deployed the mount path points to the `/root/test` directory of the Ubuntu 18.04 distro. That is the correct behaviour. However if we deploy again the mount path changes to the `/root/test` directory, which in this context belongs to the default docker-desktop WSL. The `/root/test` directory doesn't exist in docker-desktop which is why it results in an incorrect mount config for type error. 

If the docker-compose.yml is placed in the `/root` folder instead of the `/root/test` folder, then no errors happen because the docker-desktop WSL happens to have a `/root` folder. However the mounted `/root` folder then contains the data of the docker-desktop WSL and not the Ubuntu 18.04 WSL.

**Comment by simonferquel** [comment]
We are aware of the issue and are actively working on it. Unfortunately, the fix was not ready on time for this version. We'll try to introduce it in a smaller patch release.
