### ISSUE TITLE
WSL Images/containers missing in WSL2

### ISSUE THREAD

**Issue by afcruzs** [docker/for-win#6632]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

When moving to wsl2 it would be great to have the containers I had using hyper visor in the new version of docker or some form of migration tool.

### Actual behavior

After I moved to wsl2 running `docker image ls` and `docker ps -a` didn't show any of my containers or images.  I tried going back to wsl2 and running `docker export` over my dev container and then `docker import` on wsl but didn't work (complained about a file being read-only, not sure if this is actually due to wsl2 or something specific about my container). 

### Information

  - Windows Version: Windows 10 (OS Build 19041)
  - Docker Desktop Version: 2.3.0.2 (45183)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. Create containers using hyperv
  2. Move to wsl2 on docker latest version (https://docs.docker.com/docker-for-windows/wsl-tech-preview/)

**Comment by stephen-turner** [comment]
Thanks for the feedback, @afcruzs. We actually considered this. We may still do it in a future version, but we decided against it for now so that people could try out WSL 2 and move back to Hyper-V if it didn't work.

cc @nebuk89 for information.

**Comment by klinki** [comment]
@stephen-turner Is there any workaround to do this manually? I'd love to switch to WSL2 but I cannot do that right now, since I'd miss all current containers.

**Comment by stephen-turner** [comment]
No, sorry, they live in separate worlds.
