### ISSUE TITLE
wsl2: windows and linux containers side by side

### ISSUE THREAD

**Issue by Romfos** [docker/for-win#6635]
Hi,

As I understand, now we can run linux containers on windows without MobyVM(wsl2). 
Do you have plans to do possible to run windows and linux containers side by side?

This is very important point for me, because lcow is deprecated

**Comment by stephen-turner** [comment]
Thanks for the feedback, @Romfos. No immediate plans, but we're aware of the feature request. I suggest you add a thumbs-up to https://github.com/docker/roadmap/issues/79.
