### ISSUE TITLE
System.InvalidOperationException: Errno: 38='Function not implemented'

### ISSUE THREAD

**Issue by borgez** [docker/for-win#6639]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Container started

https://ravendb.net/docs/article-page/4.2/csharp/start/installation/running-in-docker-container

### Actual behavior
---> System.InvalidOperationException: Errno: 38='Function not implemented' (rc=0) - 'rvn_create_and_mmap64_file failed on FailAllocFile for '/opt/RavenDB/Server/RavenData/System/Temp/scratch.0000000000.buffers''. FailCode=FailAllocFile.

at Sparrow.Server.Platform.PalHelper.ThrowLastError(FailCodes rc, Int32 lastError, String msg) in C:\Builds\RavenDB-Stable-4.2\42038\src\Sparrow.Server\Platform\PalHelper.cs:line 35

### Information

  - Windows Version: 1909 (18363.815)
  - Docker Desktop Version: 2.3.0.2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. docker run --rm -p 8080:8080 -p 38888:38888 -v c:/RavenDb/Data:/opt/RavenDB/Server/RavenData --name RavenDb-WithData -e RAVEN_Setup_Mode=None -e RAVEN_License_Eula_Accepted=true -e RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork ravendb/ravendb

**Comment by stephen-turner** [comment]
The stack trace you have quoted seems to be all within RavenDB code. Have you tried opening a bug report with them?

**Comment by nnicksize** [comment]
### Workaround (not that bad)
I had the same problem after updating to [Docker Desktop 2.3.0.2](https://docs.docker.com/docker-for-windows/release-notes/#docker-desktop-community-2302). Uninstalling Docker Desktop and installing version [2.2.0.5](https://docs.docker.com/docker-for-windows/release-notes/#docker-desktop-community-2205) solved the problem for me.

### Information
- OS: Microsoft Windows 10.0.18363
- Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Evidence
- This error only appeared with a mounted volume.
- The function mentioned in the logs `rvn_create_and_mmap64_file` fails on the call to `posix_fallocate64` with error code 38 (ENOSYS).

Imho, those two points lend themselves to the idea that this issue might be related to Docker Desktop for Windows.

**Comment by mat007** [comment]
This may actually be the same root cause as #6634 as at least the error message is similar.
