### ISSUE TITLE
Fail on start because computer name could not be resolved

### ISSUE THREAD

**Issue by ghost** [docker/for-win#664]
### Expected behavior
Start Docker

### Actual behavior
Failed to Start

### Information

  - Diagnostic ID - CED91799-2DDE-49BA-95DB-9C9AB0448CA9/2017-04-21_22-43-00

Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The computer 'EZEQUIEL-NOTEBO' could not be resolved. Make sure you typed the machine name correctly and that you have network access.
at New-MobyLinuxVM, <No file>: line 218
at <ScriptBlock>, <No file>: line 381
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

### Steps to reproduce the behavior
1. Start Windwos 10 
2. Wait for docker autostart
3. Start fail and display Error feedback

![error](https://cloud.githubusercontent.com/assets/985899/25300377/457ae46c-26e4-11e7-9d86-64c67335fca4.png)

###Log file
[log.txt](https://github.com/docker/for-win/files/948652/log.txt)

**Comment by sbania** [comment]
I had the same issue and it was related to the length of my hostname (the name was truncated by the command output). Just search for the MobyLinux.ps1 script and replace every call to "get-VMHost" by "get-VMHost -ComputerName "localhost"". Run the script again and the linux VM will be created. Restart docker and everything should be fine.

**Comment by ezequiellorenzatti** [comment]
Thanks sbania, i just change de computer name from "EZEQUIEL-NOTEBOOK" to "EZEQUIEL" and the problem was solved.

**Comment by friism** [comment]
Thanks for reporting, I've created an internal issue to fix this problem

**Comment by simonferquel** [comment]
The problem is fixed, it might not be there in this week build though.

**Comment by adinunzio84** [comment]
We encountered this issue when the hostname has a period (ex: "28736.somecompany.com")
