### ISSUE TITLE
mount a folder but can't open it after several hours

### ISSUE THREAD

**Issue by tristetravel** [docker/for-win#665]
### Expected behavior
when mounted a windows folder,  it should always can visited

### Actual behavior
the mounted dir can visit after run the container with the daemon mode, but second day the mounted path can't visit, run ls in the dir turned out "reading directory .: Input/output error", and run ll in parent dir showed "d?????????   ? ?    ?        ?            ?  mounted_dir_name"

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu. 1D0D7F60-2672-4D28-B0FA-9ACA69C5608F/2017-04-22_14-06-20
  - host distribution and version (Windows version, build number, etc) windows 10 Pro insider preview, Build 14926.rs_prerelease.160910-1529

### Steps to reproduce the behavior

  1. run the contained with mounted folder
  2. open the folder it can work
  3. after several hours, reopen the folder, it can't work

**Comment by simonferquel** [comment]
Can you check if File and printer sharing is still enabled in the `vEthernet (Docker Nat)` network adapter properties ?

**Comment by tristetravel** [comment]
it is enabled, besides,  if run a new container with same command, the new one will have the share folder access, and will happen the same situation after several hours.
