### ISSUE TITLE
Unable to open GUI directly on 2.3.0.2 wsl2. Right click -> dashboard works fine.

### ISSUE THREAD

**Issue by darron1217** [docker/for-win#6650]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
1. Docker Desktop Service is running
2. Double click on `Docker Desktop` shortcut in `frontend` folder.
3. Docker Desktop GUI opened

### Actual behavior
1. Docker Desktop Service is running
2. Double click on `Docker Desktop` shortcut in `frontend` folder.
3. Docker Desktop GUI **not** opened

### Information

  - Windows Version: win 10 pro (build 2004) OS build. 19041.208
  - Docker Desktop Version: 2.3.0.2 (stable)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

  - Is it reproducible? Yes. I did factory reset and reinstall but none of them fixed this problem. 
  - Is the problem new? Yes. Previous version (maybe 2.2.x.x) worked just fine.

### Steps to reproduce the behavior

1. Install Docker Desktop
2. Make sure Docker Desktop Service is running
3. Double click on `Docker Desktop` shortcut in `frontend` folder.
4. GUI not opened.

**Comment by stephen-turner** [comment]
You double-clicked on the shortcut on your desktop? I don't think that has ever opened the dashboard.

I still have 2.2.0.5 installed on this machine, and I just tested it: double clicking only started the service and made the whale appear in the system tray but didn't open the dashboard.

**Comment by darron1217** [comment]
@stephen-turner 
Oh you are right. I double-clicked frontend folder's exe.

**Comment by darron1217** [comment]
I usually pin Docker Desktop GUI to taskbar. And it stopped working after update.

**Comment by stephen-turner** [comment]
Ah yes, I think that only worked by mistake before. And it didn't really work, because it didn't check that the back end was running, so we had lots of people who started up the dashboard when the engine was stopped, which caused a lot of confusion.

Having said that, it's a good question whether we should launch the UI on startup. At least if someone has double-clicked the icon, rather than that the program has just started at OS start time, in which case it probably wants to start in the background.

cc @stlucek @nebuk89 @trungutt for info/any thoughts.

**Comment by darron1217** [comment]
In my opinion, it would be nice to rollback `frontend/Docker Desktop.exe` functionality with changing its name to `Docker Desktop GUI.exe`. (Also changing root folder's file to `Docker Desktop Service.exe`
This will make people more clear to understand what they do.

**Comment by stephen-turner** [comment]
Unfortunately it wasn't just the names that were confusing. People pinned the GUI to their toolbar, and then when they launched it, they couldn't understand why they saw no containers. We don't want people to have to understand the architecture.

**Comment by darron1217** [comment]
Please provide shorcut for Dashboard.

I want to open it directly from taskbar...

**Comment by stephen-turner** [comment]
Yes, we're getting this feedback from a few people. We're looking into quicker ways to get to the dashboard.

**Comment by LeptoFlare** [comment]
*super* glad this has been implemented in 2.3.2.0! ❤️

**Comment by stephen-turner** [comment]
As @LeptoFlare says, this is now fixed in the latest Edge release, 2.3.2.0. Thanks for the feedback, everyone.
