### ISSUE TITLE
Docker desktop doesn't start after updating to 2.3.0.2

### ISSUE THREAD

**Issue by etshei** [docker/for-win#6657]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 8509B592-56F5-4B78-8B68-1936690C3734/20200512132825

### Expected behavior
Docker starting normaly and showing the notification that Docker has started

### Actual behavior
Launching the docker desktop exe shows the docker loading icon near the time and shows a notification saying "Linux containers Hyper-V backend is starting", but after some seconds (after the notification hides) the icon is freezing and trying to reach it by the cursor makes it disapear.

### Information

  - Windows Version: WIN 10 PRO version 1909 / build number 18363
  - Docker Desktop Version: Docker Desktop Community 2.3.0.2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

**Comment by etshei** [comment]
I found that when I stop internet connection docker starts normaly and at the same time when i reconnect to internet and I try to connect to Docker Hub, the error bellow shows and docker stop.

`
System.NullReferenceException:
La référence d'objet n'est pas définie à une instance d'un objet.
   à Docker.ApiServices.ClientConfig.DockerLoginSync.CredentialChanged(String registryUrl, Credential cred) dans C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\ClientConfig\DockerLoginSync.cs:ligne 156
   à Docker.ApiServices.Registries.DockerHub.<FinalizeLogin>d__20.MoveNext() dans C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\Registries\DockerHub.cs:ligne 153
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Docker.ApiServices.Registries.DockerHub.<LogIn>d__17.MoveNext() dans C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\Registries\DockerHub.cs:ligne 91
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Docker.WPF.Registries.LoginDialog.<OnLogin>d__10.MoveNext() dans C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.WPF\Registries\LoginDialog.xaml.cs:ligne 73
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   à System.Windows.Threading.DispatcherOperation.InvokeImpl()
   à MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   à MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   à System.Windows.Threading.DispatcherOperation.Invoke()
   à System.Windows.Threading.Dispatcher.ProcessQueue()
   à System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   à MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   à MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   à System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   à MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   à MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   à System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   à System.Windows.Window.ShowHelper(Object booleanBox)
   à System.Windows.Window.ShowDialog()
   à Docker.WPF.Registries.PromptLogin.<OpenAsync>b__6_1() dans C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.WPF\Registries\PromptLogin.cs:ligne 37
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   à System.Windows.Threading.DispatcherOperation.InvokeImpl()
   à MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   à MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   à System.Windows.Threading.DispatcherOperation.Invoke()
   à System.Windows.Threading.Dispatcher.ProcessQueue()
   à System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   à MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   à MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   à System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   à MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   à System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   à System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   à System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   à System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   à Docker.Program.Run(IReadOnlyCollection`1 args) dans C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Program.cs:ligne 333
`

**Comment by mat007** [comment]
Thanks for the report, what does the content of `%USERPROFILE%\.docker\config.json` look like? Do you have an `auths` field there?

**Comment by etshei** [comment]
i think the file is corrupted, couldn't show anything readable with notpad++ nor with VS code, just some weird characters

**Comment by mat007** [comment]
Hmm, that’s peculiar! Would you mind attaching it to this issue, still?

**Comment by etshei** [comment]
Here it is
[config.zip](https://github.com/docker/for-win/files/4621613/config.zip)

**Comment by mat007** [comment]
Thanks! It looks like it got corrupted indeed, I’ll have a look at the code to see if I can spot something.
In the meanwhile if you delete it and restart Docker Desktop it should re-create it and start properly.

**Comment by etshei** [comment]
i've deleted the file and everything is working fine now 👍 
thanks @mat007
i'm closing this issue

**Comment by djs55** [comment]
The fix for this has been released in [2.4.0.0 stable](https://desktop.docker.com/win/stable/48506/Docker%20Desktop%20Installer.exe).
