### ISSUE TITLE
Event Viewer displays Hyper-V-Integration 4092 Error

### ISSUE THREAD

**Issue by Borkason** [docker/for-win#666]
The Windows Event Viewer displays *Hyper-V-Integration 4092 Error*. This is after a regular install. No changes to the MobyLinuxVM. The Data Exchange integration service (Key-Value Pair Exchange) is indeed turned off, this is how it was installed by the Docker installer (edge).

*Edit: Docker works fine, it just displays the error in the event viewer.*

### Information

**Log Name:** Microsoft-Windows-Hyper-V-Worker-Admin
**Source:** Microsoft-Windows-Hyper-V-Integration
**Event ID:** 4092
**Level:** Error
**Message:** MobyLinuxVM: The Data Exchange integration service is either not enabled, not running or not initialized. (Virtual machine ID 8419AD25-B227-470A-8947-66DAE8A21472) 

```
PS C:\WINDOWS\system32> Get-VM | Get-VMIntegrationService

VMName      Name                          Enabled PrimaryStatusDescription SecondaryStatusDescription
------      ----                          ------- ------------------------ --------------------------
MobyLinuxVM Guest Service Interface       False   OK
MobyLinuxVM Heartbeat                     True    OK
MobyLinuxVM Key-Value Pair Exchange       False   OK
MobyLinuxVM Shutdown                      True    OK
MobyLinuxVM Time Synchronization          True    OK
MobyLinuxVM VSS                           False   OK
```

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
    6955FDB0-3106-4385-A55A-E946535BF3C8/2017-04-22_12-05-17
  - host distribution and version (Windows version, build number, etc)
    Windows 10 Pro Version 1703 (Build 15063.138)
    Docker version 17.05.0-ce-rc1, build 2878a85

### Steps to reproduce the behavior

  1. Standard installation, no changes to the MobyLinuxVM.

**Comment by friism** [comment]
Thanks for reporting - does Docker work if you enable the Key-Value Pair Exchange service?

**Comment by Borkason** [comment]
Oh … no, Docker does work with the service disabled. It just displays the error message in the event viewer.

**Comment by simonferquel** [comment]
Yes, we don't use this service, and it has been known for causing some stability / performance issues with some Linux Kernels we used in the past. So it is switched off. Windows only complains because it can't obtain guest environment information because of that (like guest IP address etc.)

**Comment by friism** [comment]
Closing.
