### ISSUE TITLE
Docker Desktop on Windows is not starting automatically without Login to Windows machine

### ISSUE THREAD

**Issue by innovationatgalaxy** [docker/for-win#6670]
### Expected behavior
Docker Desktop on Windows shuold start automatically once machine is up post reboot or if the service crashes.
### Actual behavior
Docker Desktop on Windows is not starting though machine is up post reboot. It waits for someone to login and start it manually.
It is same whether "Start Docker Desktop when you log in" option is checked in or not.
### Information
  - Is it reproducible? - yes
  - Is the problem new? - i hope it exists
  - Did the problem appear with an update? -no
  - A reproducible case if this is a bug- Yes
  - Windows Version: Windows 10 Pro
  - Docker Desktop Version: 2.1.0.1 (37199), Engine 19.03.1
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: NO, its a physical Windows 10 machine

### Steps to reproduce the behavior
- please install Docker Desktop on Windows
- try to restart machine and wait for sometime do not login to machine.
- login to the machine after 5-10 mins, see if Docker service is already up or it is trying to come up after you login.
- expected is it should have comeup with windows start, but it waits for someone to login machine, then it comes up.

**Comment by stephen-turner** [comment]
By design.

**Comment by innovationatgalaxy** [comment]
> By design.

Is there any workaround ? because if we are running in prod environment, and somehow system went down, then it keeps on waiting for someone to login, else Docker won't start.

**Comment by stephen-turner** [comment]
We don't really recommend Docker Desktop for production workloads. You should use docker on a Linux box, or Docker for Windows Server if you want Windows containers.

**Comment by innovationatgalaxy** [comment]
> Docker for Windows Server

yes we are planning for that, currently we have this setup.
