### ISSUE TITLE
Docker desktop failing to start insider program latest updates

### ISSUE THREAD

**Issue by itaywol** [docker/for-win#6672]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 5102A019-F1DB-46FF-83CB-E2C58206A9C8/20200513050217

### Expected behavior
Docker daemon should start

### Actual behavior
Docker daemon fails to start on startup

### Information

  - Windows Version: **Windows 10 Pro N Insider Preview Build 19624.rs_prerelease.200502-1339**
  - Docker Desktop Version: **Stable 2.3.0.2 (45183)**
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: **No**

### Steps to reproduce the behavior

  1. Upgrade Windows to the latest insider preview build(19624.rs_prerelease.200502-1339)
  2. Use docker desktop with WSL2 engine
  3. Restart the computer to apply updates...
  4. Docker desktop failing to start

**Comment by Gcozier** [comment]
Hello,
If Wsl2 is not started before the Docker daemon, the Daemon will crashes because of a timeout ?

**Comment by simonferquel** [comment]
Seems to be related to a WSL2 service crash issue (from your logs).
What happens if you try to run a WSL2 (not 1) distro ?

**Comment by tankist** [comment]
> Seems to be related to a WSL2 service crash issue (from your logs).
> What happens if you try to run a WSL2 (not 1) distro ?

I have the same build and the same issue. WSL 2 runs well for me.

Attaching my crash log:

[20200513163252.zip](https://github.com/docker/for-win/files/4623349/20200513163252.zip)

**Comment by Richard-Barrett** [comment]
Hi Try this:

Try this, I had the same issue:
So I was actually able to solve it by doing the following:

Enter The following commands within an elevated command prompt:
```
Enable Hyper V - You can do this by running the following command as administrator. - dism.exe /Online /Enable-Feature:Microsoft-Hyper-V /All

Enable Hypervisor with following command - bcdedit /set hypervisorlaunchtype auto
```
Research: https://dotnetthoughts.net/hardware-assisted-virtualization-and-data-execution-protection-must-be-enabled/

Then Restart and prompt asks to download the Linux Kernel

Apparently Docker Desktop is forgetting this in their initial set-up for the updates and installation for anybody using Hyper-V and the Linux Containers requiring the WSL2 Linux Kernel Backend to initialize Containers. provided by Microsoft.

Microsoft Link: https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel

Download the above ^^

**Comment by tankist** [comment]
> Hi Try this:
> 
> Try this, I had the same issue:
> So I was actually able to solve it by doing the following:
> 
> Enter The following commands within an elevated command prompt:
> 
> ```
> Enable Hyper V - You can do this by running the following command as administrator. - dism.exe /Online /Enable-Feature:Microsoft-Hyper-V /All
> 
> Enable Hypervisor with following command - bcdedit /set hypervisorlaunchtype auto
> ```
> 
> Research: https://dotnetthoughts.net/hardware-assisted-virtualization-and-data-execution-protection-must-be-enabled/
> 
> Then Restart and prompt asks to download the Linux Kernel
> 
> Apparently Docker Desktop is forgetting this in their initial set-up for the updates and installation for anybody using Hyper-V and the Linux Containers requiring the WSL2 Linux Kernel Backend to initialize Containers. provided by Microsoft.
> 
> Microsoft Link: https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel
> 
> Download the above ^^

Unfortunately, it didn't help. I even tried full wipe of Hyper-V/Docker/WSL and re-installing back. Also I've tried Ubuntu 20.04 LTS instead of 18.04 LTS.

**Comment by Richard-Barrett** [comment]
Ensure you have it enabled in your BIOS:
https://support.lenovo.com/us/en/solutions/ht500006
Yeah I just started working with Ubuntu 20.04 LTS two days ago and have not really tried to install docker yet. Consider how resource heavy it is I might switch back to 19.10.  

# For Ubuntu 18.04
If you just want to do Docker and don't mind the CLI you can do the following open up a Terminal and try the following:
Install Docker on Ubuntu 18.04 
```
sudo apt update
sudo apt install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
sudo apt update
```
Next Run an apt-cache policy for docker
```
apt-cache policy docker-ce
```

You should see something like this:
```
docker-ce:
  Installed: (none)
  Candidate: 18.03.1~ce~3-0~ubuntu
  Version table:
     18.03.1~ce~3-0~ubuntu 500
        500 https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages
```

Finally Install:
```
sudo apt install docker-ce
sudo systemctl status docker
```

# Windows
If you want to do it on Windows I would do the following:
1. Uninstall Everything Related to Docker-Desktop in Control Panel 
2. If you are using Chocolatey you can uninstall all of that there too with `choco uninstall package`
3. Restart your Machine and Enter BIOS Menu and Make sure you have Virtualization and/or Hyperthreading Enabled. 

Use this link to see how to get into BIOS: https://support.lenovo.com/us/en/solutions/ht500006
You may need to reset your BIOS to default (Note not all Machines Support Virtualization) 
4. Allow for normal boot to occur
5. Enable Hyper-V for Windows 10 
https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v
6. Run through the following in an elevated command prompt and allowing for administrative access by right-clicking on command prompt:
```
dism.exe /Online /Enable-Feature:Microsoft-Hyper-V /All
bcdedit /set hypervisorlaunchtype auto
```

7. Restart Your Computer One More Time
8. Boot up
9. You can go to Docker-Desktop or you can install it with Chocolatey
If you want to install it via website, I assume you know where to go. Get the Stable Version. 
10 (Option A). Install as normal via https://www.docker.com/products/docker-desktop
10 (Option B). Use Chocolatey: 
Open up powershell in elevated admin console and install chocolatey
```
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
```
https://chocolatey.org/install

Then after you install it run:
```
choco install docker-desktop
```
Chocolatey Link: https://chocolatey.org/packages/docker-desktop#releasenotes
Docker Release Notes: https://docs.docker.com/docker-for-windows/release-notes/

Whatever you decide, you need to make sure 
1. Your System Supports Virtualization
2. You have that enabled in System BIOS

Hope this helps, I too have had so many problems with Docker-Desktop as of late.
