### ISSUE TITLE
Docker Desktop on Windows is not able to allocate RAM to 'DockerDesktopVM' beyond 50% of Windows Host Machine RAM

### ISSUE THREAD

**Issue by innovationatgalaxy** [docker/for-win#6674]
### Expected behavior
On Docker Desktop on Windows, we should be able to allocate RAM beyond 50% of Total RAM of host machine.
EX: If Windows10 Host mahcine has 64 GB of RAM, we should be able to allocate beyond 32GB of RAM to DockerDesktopVM. We have free RAM available for this. But when we try to allocate, no matter if we allocate any amount  of RAM beyond 32GB, DockerDesktopVM is getting only 32 GB.

### Actual behavior
On Docker Desktop on Windows, we are be able to allocate only 50% of  Total RAM of  Windows host machine.
If we allocate beyond that, still DockerDesktopVM  is getting allocated to 50% of  Total RAM of  Windows host machine.

### Information
  - Is it reproducible? Yes
  - Is the problem new? NO
  - Did the problem appear with an update? NO
  - A reproducible case if this is a bug. Yes
  - Windows Version: Windows 10 Pro
  - Docker Desktop Version: 2.1.0.1 (37199), Engine 19.03.1
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: NO, its a physical Windows 10 machine

### Steps to reproduce the behavior
- Please install Docker Desktop on Windows, version 2.1.0.1
- Try to expand RAM size on for Docker. on Host machine, Right side bottom(tray icons) --> Right click on Docker ICON -->Settings--> Advanced-->Memory--> Here drag and expand the RAM to beyond 50% of Total host machine RAM 
- Restart Docker Desktop on Windows.
- Once Docker is up and Running please verify RAM size for 'DockerDesktopVM' on 'Hyper-V Manager' and also on Docker settings (on Host machine, Right side bottom(tray icons) --> Right click on Docker ICON -->Settings--> Advanced-->Memory)

**Comment by stephen-turner** [comment]
This is a very old version that is no longer maintained, have you tried the latest?
