### ISSUE TITLE
Docker Not starting having issue  

### ISSUE THREAD

**Issue by saamageneric** [docker/for-win#6676]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
No information to enable us to debug this, closing the ticket.
