### ISSUE TITLE
Windowsfilter folder

### ISSUE THREAD

**Issue by MICH66** [docker/for-win#6681]
My docker installation crashed when updating to the newest version and after several atttempst at restarting my pc. I decided to uninstall and reinstall. My data-root folder was c:\docker\Virtualdockers\. It contained the windowsfilter folder which contains many gb's og data from the old containers. Theses can no longer be used so I tried to delete the contents om windowsfilters folder. 

I tried the complete cleanup/uninstall script from the docker forum. 
I tried using Docker system prune 

Nothing is working.

I have no containers installed at the momment and just wont to clean out the old ones and release the disk space.

How do I do this?

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mat007** [comment]
You may be able to reclaim the folder with https://github.com/moby/docker-ci-zap
