### ISSUE TITLE
Expose daemon on tcp://localhost:2375 without TLS makes Docker unavailable

### ISSUE THREAD

**Issue by CedricPerotto** [docker/for-win#6682]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 1A0925A5-2D78-42E6-BE74-7904BD7DF44B/20200513132131

### Expected behavior
Exposing the daemon on port, should restart Docker and expose the port properly.

### Actual behavior
When clicking on the expose daemon checkbox and then do an apply and restart. Docker restarts, but when trying to execute a simple docker container ls it  returns the following error:
`error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.   `
### Information

  - Windows Version: 10 Pro (1909)
  - Docker Desktop Version:  2.3.0.2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no 

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by allenvose** [comment]
I have this problem as well, setting the option makes docker unavailable after restart.  Immediately clearing the setting and restart makes docker available again.

**Comment by stephen-turner** [comment]
In the latest Edge release, 2.3.2.0, we have improved this so that application startup is no longer blocked when port 2375 is in use, and a toast notification pops up instead.
