### ISSUE TITLE
i have also an issue with docker desktop, it took to an error while installing 

### ISSUE THREAD

**Issue by anandsoni143** [docker/for-win#6688]
![Capture1](https://user-images.githubusercontent.com/47745941/81831606-2dbac980-955b-11ea-8c70-c86a21d3305a.PNG)
![Capture1](https://user-images.githubusercontent.com/47745941/81831622-33b0aa80-955b-11ea-9138-43f19a177ddb.PNG)

i have already a latest version 1909 of windows 10 home but cannot install docker in it

![Capture](https://user-images.githubusercontent.com/47745941/81831371-e3d1e380-955a-11ea-9156-3591abd040fe.PNG)

**Comment by stephen-turner** [comment]
The message is clear, your build of Windows is too old. You need the Insiders Preview, or Windows 2004 when it comes out.

**Comment by anandsoni143** [comment]
is this issue can be resolved by updating windows

**Comment by mat007** [comment]
> is this issue can be resolved by updating windows

Yes, you need Version 2004 (May 2020 Update).

**Comment by anandsoni143** [comment]
i have instALLED LATEST UPDATES OF MAY 
MY WINDOWS IS SHOWING UP TO DATE 
BUT WHAT CAN I DO TO INSTALL DOCKER DESKTOP ON WINDOWS

**Comment by anandsoni143** [comment]
i cannot install docker also in my latest version

**Comment by anandsoni143** [comment]
it is showing , you are up to date

**Comment by mat007** [comment]
Which version do you have at the moment?

**Comment by anandsoni143** [comment]
![Capture3](https://user-images.githubusercontent.com/47745941/82029842-2f000980-96b5-11ea-8640-b356fc92a6e4.PNG)




look at this sir i have my latest version of os

**Comment by mat007** [comment]
This is the version you need: https://en.wikipedia.org/wiki/Windows_10_version_history#Version_2004_(May_2020_Update)
This is the version you have: https://en.wikipedia.org/wiki/Windows_10_version_history#Version_1909_(November_2019_Update)

**Comment by anandsoni143** [comment]
how do i get that version

**Comment by anandsoni143** [comment]
it is showing you are upto date

**Comment by stephen-turner** [comment]
The Windows 2004 version is still not released to the public. You can get it if you join the Insiders program. Or wait a few days, I think Microsoft are going to release it very soon.

**Comment by anandsoni143** [comment]
hello sir , i have a querry about docker file , 
i made a docker file and put the CMD command wrong 
now it is showing the cannot find path specified 
i want my all specification with all software that i put in RUN command in docker file
but i cannot download all software again 
but i want change only in CMD commadn that i have put in docker file so what should i do
