### ISSUE TITLE
How to expose host d drive to D drive in the container for windows docker image?

### ISSUE THREAD

**Issue by cyly** [docker/for-win#6695]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
We have two drives c: and d:. C drive is the system drive and D drive is the data drive. We need to expose the host d drive to the d drive in the windows docker container. Is there a way to do that?

docker run -it -v d: windows-base-sdk3.5-vc:20200513 cmd
I used the command above to launch the container. Inside the container, I can access D drive. However D drive empty and the files on my host D drive are not shared. Anything wrong? How could I solve this issue?
### Expected behavior
The D drive on the host machine is shared as D drive in the docker container.

### Actual behavior
The D drive in the docker container is empty.

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mat007** [comment]
In theory I believe it should be
```
docker run -it -v d:\:d:\ windows-base-sdk3.5-vc:20200513 cmd
```
but when I do (I don’t have a D drive)
```
docker run -it -v c:\:d:\ mcr.microsoft.com/windows/nanoserver:1903 cmd
```
it crashes…
```
docker: Error response from daemon: container efcab00cb5fc5b07dd89946b10e619cae5d99903050114326270bc62a4ecb7d6 encountered an error during hcsshim::System::Start: failure in a Windows system call: The virtual machine or container exited unexpectedly. (0xc0370106).
```
and these errors should be reported upstream in https://github.com/moby/moby for someone at Microsoft to take a look at…

**Comment by ebriney** [comment]
`docker run -it -v c:\:c:\host_drive mcr.microsoft.com/windows/nanoserver:1903 cmd` is working.
You cannot create drive in the container but you can mount a drive in any directory on `C:\`
