### ISSUE TITLE
unable to update config values using dfw settings or daemon.json

### ISSUE THREAD

**Issue by thehundt** [docker/for-win#670]
### Information

  - 5A00C18A-FE8D-4700-93A4-681F5B2752E3/2017-04-25_11-18-34
  - Windows Server 2016 Standard Version 1607 OS Build 14393.1066

### Steps to reproduce the behavior

  1. Add settings under Daemon => Advanced and click Apply
     {
        "registry-mirrors": [],
        "insecure-registries": [],
        "debug": true,
        "experimental": true,
        "graph": "e:\\dockerimages"
       }

  2. when docker restarts, the settings are not applied:

 Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.05.0-ce-rc1
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: active
 NodeID: a05to6fx2bsx46i08ape6cu10
 Is Manager: true
 ClusterID: ztih3h430nqb1etn7mta86mv2
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.133.2.3
 Manager Addresses:
  10.133.2.3:2377
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1066.amd64fre.rs1_release_sec.170327-1835)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 12GiB
Name: NHMicroServices
ID: AW3Z:VBFJ:X3SR:ICDX:UHHG:WG4U:DQF7:EBQH:HUIX:3BDE:HEV2:C5VD
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by simonferquel** [comment]
Thanks for reporting the issue, it has been fixed internally and will be fixed in an upcoming Edge version (this week or the next one)

**Comment by thehundt** [comment]
Thanks Simon.  I installed the latest dev version and it appears to be working with the daemon.json file now:  Server Version: 17.06.0-dev
