### ISSUE TITLE
Bind-mounting Windows host paths into sibling containers broken in v2.3.0.2

### ISSUE THREAD

**Issue by djg2002** [docker/for-win#6700]
I believe a bug with bind-mounting Windows paths in sibling containers has been introduced in v2.3.0.2

### Expected behavior

Bind-mounting Windows host volumes into sibling containers should work with Windows host's full paths - e.g. //C/Users/Me/... 

```
powershell> docker run --rm -it --volume //C/Users/[username]:/root --volume /var/run/docker.sock:/var/run/docker.sock docker:19.03.8

docker> docker run -it --rm --mount type=bind,source="//C/Users/[username]/.ssh",target="/root/.ssh",readonly alpine

alpine> ls /root/.ssh

id_rsa ...
```
### Actual behavior

Using '//C/' no files mounted in 'docker' container.  Partial fix was to changed to use 'C:/' and files visible, however running:

```
powershell>    docker run --rm -it --volume C:/Users/[username]:/root --volume /var/run/docker.sock:/var/run/docker.sock docker:19.03.8
docker> docker run -it --rm --mount 
type=bind,source="C:/Users/[username]/.ssh",target="/root/.ssh",readonly alpine
---> docker: Error response from daemon: invalid mount config for type "bind": invalid mount path: 'C:/Users/[username]/.ssh' mount path must be absolute.
```

### Information

This is a new issue since installing update yesterday
Before yesterday the volumes were working OK
Problem appears to be related to 2.3.0.2
Dockerfile FROM python:3.7.7-slim-buster without much additional configuration - builds fine,  issue seems to be with docker run... 
Windows Version	10.0.17763 Build 17763
Docker Desktop Version: 2.3.0.2
Physical machine (not virtualised) - is Intel i7-4790K
'docker' image version docker:19.03.8  (unchanged from yesterday)

### Steps to reproduce

```
powershell>    docker run --rm -it --volume C:/Users/[username]:/root --volume /var/run/docker.sock:/var/run/docker.sock docker:19.03.8
docker> docker run -it --rm --mount type=bind,source="C:/Users/[username]/.ssh",target="/root/.ssh",readonly alpine
---> docker: Error response from daemon: invalid mount config for type "bind": invalid mount path: 'C:/Users/[username]/.ssh' mount path must be absolute.
```

I tried various other forms getting a path does not exist error:

```
docker> docker run --mount type=bind,source="/C/Users/Me/.ssh",target="/root/.ssh"
 # ->  Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /C/Users/Me/.ssh

docker> docker run --mount type=bind,source="//C/Users/Me/.ssh",target="/root/.ssh"
 # ->  Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /C/Users/Me/.ssh

docker> docker run --mount type=bind,source="/root/.ssh",target="/root/.ssh"
 # ->  Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /root/.ssh.
```

**Comment by natashadsilva** [comment]
I'm having the same problem. I installed the update and my mounted volumes are no longer accessible from the container.

**Comment by neilharvey94044** [comment]
Same here.  Bind mounts are not working properly.  Anyone know how to roll back the update?

**Comment by djg2002** [comment]
Just had a thought  - I am also running Windows Subsystem for Linux.

Maybe related since there has been mention of WSL changes? No idea though and can’t remove WSL as I need that while Docker is out of action.

**Comment by ebriney** [comment]
Hi @djg2002 thanks for the report, we fixed the issue, it will be in next patch release.
As a workaround you can use `/host_mnt/c/Users/[username]/.ssh` as source for your mount point.

**Comment by mat007** [comment]
This does look like the same as #6668

**Comment by mat007** [comment]
Closing this one as a duplicate, feel free to ask for it to be re-opened if you believe it’s a different issue.
