### ISSUE TITLE
can't run docker desktop

### ISSUE THREAD

**Issue by heshamdalla** [docker/for-win#6701]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by heshamdalla** [comment]
Windows 10 Pro v1903
Docker version 2.3.0.4
VirtualBox V 6.1
on MAC OSX Catalina 10.15.4

**Comment by Richard-Barrett** [comment]
Have you checked to see if Nested Virtualization is turned on?
https://forums.virtualbox.org/viewtopic.php?f=1&t=90831

**Comment by Richard-Barrett** [comment]
Furthermore, you should try this inside the virtual machine from within Windows if nested virtualization is turned on: https://dotnetthoughts.net/hardware-assisted-virtualization-and-data-execution-protection-must-be-enabled/

**Comment by heshamdalla** [comment]
Thank you...
I checked and same result

________________________________

**Comment by stephen-turner** [comment]
Docker Desktop is not supported inside a VM. It might work, it might not, but it's outside our control: it depends on the whether the outer hypervisor can run Hyper-V.
