### ISSUE TITLE
Docker.Core.HttpBadResponseException: Unhandled exception: job failed with message: Failed to create a new virtual machine.

### ISSUE THREAD

**Issue by rastascan** [docker/for-win#6704]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C1247723-B58F-4190-8578-160FD662EAEF/20200514033025

### Expected behavior
Launch linux containers in docker
### Actual behavior
Docker.Core.HttpBadResponseException:
Unhandled exception: job failed with message: Failed to create a new virtual machine.

### Information

  - Windows Version: 1909
  - Docker Desktop Version: 2.3.0.2 (45183)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Not running on a virtualised environment. 

### Steps to reproduce the behavior

  1. Windows containers works fine
  2.  Switch to linux containers and then crashes
[log.txt](https://github.com/docker/for-win/files/4625911/log.txt)

**Comment by stephen-turner** [comment]
Are you trying to run it inside a VM?

**Comment by rastascan** [comment]
No, running on Windows 10 pro x64 V1909.
I've tried reinstalling. Enabling / disabling hyper-v

**Comment by rastascan** [comment]
I've located the problem. I checked the hyper-V settings and changed the virtual hard disks and virtual machines to valid folders. They were pointing to non existent ones.
