### ISSUE TITLE
Docker.Core.HttpBadResponseException: Unhandled exception: 序列不包含任何元素

### ISSUE THREAD

**Issue by lzhpo** [docker/for-win#6706]
When I start docker, it cannot be started. An error is reported!
When I restart, it's OK again, but the task of self starting is few!

## The error
![Docker启动出错-序列不包含任何元素](https://user-images.githubusercontent.com/42663571/81894779-36ef7900-95e3-11ea-8912-769d79e4e72d.png)

## The docker version
![Docker-Version](https://user-images.githubusercontent.com/42663571/81894810-4ff82a00-95e3-11ea-8a52-5cfdcc44b04a.png)

What is the reason? I upgraded the version, like? thank you!

**Comment by xuehua312741499** [comment]
I have the same problem ..

**Comment by xuehua312741499** [comment]
When I swich to linux containers ,will have this problem..

**Comment by lzhpo** [comment]
Yes, it's like this every time I turn it on, it's a headache!

**Comment by lzhpo** [comment]
> I have the same problem ..

请问您解决了这个问题吗？docker-win官方不更新给一个回应的吗？这个问题很严重！

**Comment by lzhpo** [comment]
> When I swich to linux containers ,will have this problem..

Did you solve this problem?Isn't docker-win officially updated to a response?This problem is serious!

**Comment by xuehua312741499** [comment]
Has nobody fix this probelm?

**Comment by lzhpo** [comment]
Forget it, no one solved it, I shut it down, downgrade it!

**Comment by esileme** [comment]
Switch to Windows Containers is works
