### ISSUE TITLE
Docker fails to mount files inside volume from local WSL

### ISSUE THREAD

**Issue by atopheim** [docker/for-win#6709]
Trying to run docker locally inside Visual Code WSL terminal on Windows Pro - using Docker ( version 19.03.8 ) for Windows.

$ docker run --rm --volume /mnt/c/Users/tor/Projects/temp/:/etc/folder/vars/ -it busybox

It seems to be mounting the folders correctly but the folder is empty in the destination ( so the files are not being mounted ).

Meaning I can run the command below inside the container, but the folder is empty - returning nothing.

$ ls /etc/folder/vars
$

**Comment by mat007** [comment]
Is this WSL or WSL 2?
Could you upload some diagnostics (Troubleshoot window from the systray menu).

**Comment by annam002** [comment]
I have the same problem. It occurs with then newest version of Docker Desktop, 2.3.0.2, with WSL2. I "fixed" it by downgrading to the previous Docker version (you can find the links to the previous versions here: https://docs.docker.com/docker-for-windows/release-notes/). It also gives me a strange message that host_mnt is not implemented:

`D:\workspaces>docker run --net=host --ipc=host --uts=host --pid=host -it --security-opt=seccomp=unconfined --privileged --rm -v /:/host alpine /bin/sh`
`/ # ls host`
`ls: host/host_mnt: Function not implemented`
`bin         etc         lib         mnt         proc        run         sendtohost  sys         usr`
`dev         home        media       opt         root        sbin        srv         tmp         var`
