### ISSUE TITLE
Extracting downloaded image is extremely slow

### ISSUE THREAD

**Issue by sebhaub** [docker/for-win#671]
### Expected behavior
extracting is faster than downloading an image

### Actual behavior
extracting takes way longer than downloading.

as an example : `docker pull microsoft/nanoserver:10.0.14393.953`, extracting a 115mb layer took more than 70 seconds. On larger layers (microsoft/dotnet-framework for example) this gets even worse.

### Information

|Category | Value |
-----|----------------------------
| OS | Windows Server 2016 |
| Server Version | 17.03.1-ee-3 |
| Storage Driver | windowsfilter |
| Default Isolation | process |

### Steps to reproduce the behavior

I get this behaviour on different machines. So the only step to reproduce is pulling an image.
Hopefully someone can point me to the right direction since i cant find similar issues.
Thanks in advance.

**Comment by friism** [comment]
@sebhaub one (obviously non-recommended) way to speed this up is to disable Windows Defender:

    Set-MpPreference -DisableRealtimeMonitoring $true

@sebhaub do you have other antivirus or similar running on the machine?

cc @patricklang

**Comment by friism** [comment]
@sebhaub This is not really something that can be fixed in Docker for Windows. If anything is to be done, it's in either the platform codebase or in the `distribution` component:

 * https://github.com/docker/distribution/
 * https://github.com/moby/moby

cc @jstarks

I'm closing this issue, but others should feel free to follow up.

**Comment by jim-obrien-orig** [comment]
Sill slow on mac and linux. What happens on multi-repo projects like this is that core issues suffer from "pass the buck" and noone  takes responsibility for them. The extract is incredibly slow compared to tar/gzip. It may have something to do with sha256 redundant checks - this issue - https://github.com/moby/moby/issues/38536, but  I suspect that's not the only problem.
