### ISSUE TITLE
Docker image is set for a custom path in Settings but still build on default path

### ISSUE THREAD

**Issue by a3369** [docker/for-win#6710]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
I set Disk image location (Settings => Resources) to a custom path on another drive (E:/), Docker is building the image on the path set in the Settings.
### Actual behavior
I set Disk image location (Settings => Resources) to a custom path on another drive (E:/), Docker is building the image still on the default path. But setting shows my custom path.
### Information

  - Windows Version: Win 10
  - Docker Desktop Version: 2.3.0.2 (45183)
  - I using windows not in a VM.

### Steps to reproduce the behavior

  1. Set Disk image location (Settings => Resources) to a custom path
  2. Apply and Restart
  3. Have a look in the folder and used disk space on your drives

**Comment by mat007** [comment]
Thanks for the report.

Does it work if you change the path to a path on the C drive?
I just tested switching it to `C:\tmp\vhdx` and it does work, hovewer I don’t have another drive to test…

**Comment by a3369** [comment]
Hi Mathieu,

good question. I switch back to the older version 2.2.0.5 (43884). Here it works well again.

So I can’t tell, if it works when I just change the path on the same drive. But it didn’t worked on another drive.
It was necessary to switch to another drive because the default drive (C:) has not enough space to handle the big docker images of my project.

Best Regards,
Axel

Von: Mathieu Champlon <notifications@github.com>
Gesendet: Freitag, 15. Mai 2020 10:36
An: docker/for-win <for-win@noreply.github.com>
Cc: Axel Monse <axel.monse@sixt-leasing.com>; Author <author@noreply.github.com>
Betreff: Re: [docker/for-win] Docker image is set for a custom path in Settings but still build on default path (#6710)


Thanks for the report.

Does it work if you change the path to a path on the C drive?
I just tested switching it to C:\tmp\vhdx and it does work, hovewer I don’t have another drive to test…

**Comment by mat007** [comment]
I resized my C and just created a D to try this out and it seems to be working:

![image](https://user-images.githubusercontent.com/2386884/82033070-77f79400-969c-11ea-895d-1971b44f2366.png)

And the default vhdx location is now empty:

![image](https://user-images.githubusercontent.com/2386884/82033041-6d3cff00-969c-11ea-8d98-2d93c63f668e.png)

🤔

**Comment by mat007** [comment]
Is your E drive a regular drive?

**Comment by a3369** [comment]
No. It is only a partition. E: is not a physical drive. C: and E: are on the same physical drive.

Von: Mathieu Champlon <notifications@github.com>
Gesendet: Freitag, 15. Mai 2020 11:10
An: docker/for-win <for-win@noreply.github.com>
Cc: Axel Monse <axel.monse@sixt-leasing.com>; Author <author@noreply.github.com>
Betreff: Re: [docker/for-win] Docker image is set for a custom path in Settings but still build on default path (#6710)


Is your E drive a regular drive?
