### ISSUE TITLE
failed to start docker on windows 10

### ISSUE THREAD

**Issue by ozy-work** [docker/for-win#6715]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 22D59FB1-EB8F-4C81-8518-FE1DC77D5F1B/20200514130726

### Expected behavior
Docker starts and functioning 
### Actual behavior
docker fail to start, cannot connect to the docker daemon message
### Information

  - Windows Version:
  - Docker Desktop Version:2.3.0.2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
No
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ozy-work** [comment]
missed the windows version info: microsoft windows 10 enterprise, 10.0.1.18363

**Comment by Richard-Barrett** [comment]
Hi this is what worked for me on my Version of Windows:

# Windows
Here is what worked for me:
If you want to do it on Windows I would do the following:
1. Uninstall Everything Related to Docker-Desktop in Control Panel and disable Hyper-V
https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v
2. If you are using Chocolatey you can uninstall all of that there too with `choco uninstall package` and disable Hyper-V https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v
3. Restart your Machine and Enter BIOS Menu and Make sure you have Virtualization and/or Hyperthreading Enabled. 

Use this link to see how to get into BIOS: https://support.lenovo.com/us/en/solutions/ht500006
You may need to reset your BIOS to default (Note not all Machines Support Virtualization) 
4. Allow for normal boot to occur
5. Enable Hyper-V for Windows 10 
https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v
6. Run through the following in an elevated command prompt and allowing for administrative access by right-clicking on command prompt:
```
dism.exe /Online /Enable-Feature:Microsoft-Hyper-V /All
bcdedit /set hypervisorlaunchtype auto
```

7. Restart Your Computer One More Time
8. Boot up
9. You can go to Docker-Desktop or you can install it with Chocolatey
If you want to install it via website, I assume you know where to go. Get the Stable Version. 
10 (Option A). Install as normal via https://www.docker.com/products/docker-desktop
10 (Option B). Use Chocolatey: 
Open up powershell in elevated admin console and install chocolatey
```
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
```
https://chocolatey.org/install

Then after you install it run:
```
choco install docker-desktop
```
Chocolatey Link: https://chocolatey.org/packages/docker-desktop#releasenotes
Docker Release Notes: https://docs.docker.com/docker-for-windows/release-notes/

Whatever you decide, you need to make sure 
1. Your System Supports Virtualization
2. You have that enabled in System BIOS
3. Makes sure you have downloaded the WSL 2 background: https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel

Hope this helps, I too have had so many problems with Docker-Desktop as of late.

**Comment by ozy-work** [comment]
thank you. 
I will try that and update on the result

**Comment by darkmattercoder** [comment]
@Richard-Barrett 

I noticed that you keep advising your above procedure in a lot of issues filed during the last days regarding the startup issue of docker for windows. And I really appreciate your effort trying to help people.

However, your solution seems to target only really new windowses that already allow the use of WSL2, doesn't it?

However, many machines, especially in enterprise context are not able to use WSL2, and most likely won't for at least half a year from now.

Do you suggest your above solution nevertheless? Do you have an explanation, why in an environment, where docker for win has been used for a long time without issues, behaves like that?

Is that the only alternative, that will help fixing the issue?

**Comment by Richard-Barrett** [comment]
I have seen the issue and I have seen some of the debug output from multiple people. The newest update actually disabled Hyper-V and then destroys the virtual switch necessary for the network overlay on docker containers. Since the update, it totally botched my Docker-Desktop on a Windows Insider Addition. After I did the above it worked just fine and I was able to pull down a key cloak container and use it without any problems. After I did the above I was prompted install The WSL 2. I didn’t have that before the update. Which is why it prompted me for it. Also if you try to switch to Linux Containers it will Brick the Docker Installation, which is what caused my problem, then I did an update that destroyed the network overlay. After doing my proposed procedure it worked for me.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by drdajoyce** [comment]
@Richard-Barrett 

Hi Richard,

I followed your steps and the error still persists for me. The only thing I didn't do was download the WSL 2 background (I'm on build 17763 so it's not compatible with my version of Windows).
