### ISSUE TITLE
Error when Docker on Windows 10 starts [SOLVED]

### ISSUE THREAD

**Issue by carlca** [docker/for-win#672]
### Expected behaviour
Docker should start
### Actual behaviour
Docker fails to start. Gives error message
![image](https://cloud.githubusercontent.com/assets/260612/25399255/c45b32d2-29e6-11e7-8e73-e1ac09de0231.png)

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
A1142FE5-C51C-4DC2-9B5C-DE1471564225/2017-04-25_18-34-46
  - a reproducible case if this is a bug, Dockerfiles FTW
Happens every time I try to start Docker.
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)
Windows Pro 64 bit insider edition Build 16179

### Steps to reproduce the behavior

  1. Try to start Docker.
  2. ...

**Comment by carlca** [comment]
This was the bug which finally forced me to switch to Apple Mac. So thanks, Docker!

**Comment by stephen-turner** [comment]
Obsolete, closing
