### ISSUE TITLE
Error on Start Up of Docker Desktop

### ISSUE THREAD

**Issue by robert-1109** [docker/for-win#6722]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 
4D93FE65-5CCD-4ED8-8D09-8B8A8CFF0C87/20200514151023
### Expected behavior
Starting the app
### Actual behavior
An error occured -> creating instantly an crash report
### Information

  - Windows Version: Windows 10 Pro
  - Docker Desktop Version: 2.3.0.2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Richard-Barrett** [comment]
Just a heads up these guys will just close an issue, if you don't include anything. 
Perhaps this might help, as I don't have access to everything and cannot see what you are experiencing . I know for me it was a prompt for enabled hypervisor-v even though I had it installed, enabled, and set to true in system BIOS and was using Hyper-V as my Hypervisor for Virtualbox.

# Windows
Here is what worked for me:
If you want to do it on Windows I would do the following:
1. Uninstall Everything Related to Docker-Desktop in Control Panel and disable Hyper-V
https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v
2. If you are using Chocolatey you can uninstall all of that there too with `choco uninstall package` and disable Hyper-V https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v
3. Restart your Machine and Enter BIOS Menu and Make sure you have Virtualization and/or Hyperthreading Enabled. 

Use this link to see how to get into BIOS: https://support.lenovo.com/us/en/solutions/ht500006
You may need to reset your BIOS to default (Note not all Machines Support Virtualization) 
4. Allow for normal boot to occur
5. Enable Hyper-V for Windows 10 
https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v
6. Run through the following in an elevated command prompt and allowing for administrative access by right-clicking on command prompt:
```
dism.exe /Online /Enable-Feature:Microsoft-Hyper-V /All
bcdedit /set hypervisorlaunchtype auto
```

7. Restart Your Computer One More Time
8. Boot up
9. You can go to Docker-Desktop or you can install it with Chocolatey
If you want to install it via website, I assume you know where to go. Get the Stable Version. 
10 (Option A). Install as normal via https://www.docker.com/products/docker-desktop
10 (Option B). Use Chocolatey: 
Open up powershell in elevated admin console and install chocolatey
```
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
```
https://chocolatey.org/install

Then after you install it run:
```
choco install docker-desktop
```
Chocolatey Link: https://chocolatey.org/packages/docker-desktop#releasenotes
Docker Release Notes: https://docs.docker.com/docker-for-windows/release-notes/

Whatever you decide, you need to make sure 
1. Your System Supports Virtualization
2. You have that enabled in System BIOS
3. Makes sure you have downloaded the WSL 2 background: https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel

Hope this helps, I too have had so many problems with Docker-Desktop as of late.
