### ISSUE TITLE
"Show system containers (advanced)" does not affect docker cli in WSL2

### ISSUE THREAD

**Issue by uncleyo** [docker/for-win#6725]
This is a minor, but noticeable behavior discrepancy with cli in WSL2 distro

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics

### Expected behavior
`docker` cli ran inside WSL2 default distro honors "Show system containers (advanced)" default unchecked value, like Windows host `docker.exe` does
### Actual behavior
`docker` cli inside WSL2 distro shows all Kubernetes containers regardless of setting value

### Information

  - Windows Version: 10 x64, Version 2004, Build 19041.264
  - Docker Desktop Version: 2.3.0.2 (45183)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. Run Docker Desktop in WSL2 mode
  2. Enable Kubernetes
  3. Leave "Show system containers (advanced)" unchecked
  4. Enable WSL Integration
  5. Run `docker ps -a` in your WSL distro

**Comment by simonferquel** [comment]
Thanks for the feedback. This is definitely a bug !

**Comment by brunobertechini** [comment]
Behavior confirmed. Is there any ETA?

**Comment by chino** [comment]
I seem to have the issue where the setting seems to have no effect on both windows and linux.  I keep seeing system containers in the ps output list regardless of the option.  This is on docker 19.03.12.
