### ISSUE TITLE
Cannot start container with SQL Server 2019 after updates

### ISSUE THREAD

**Issue by neilharvey94044** [docker/for-win#6726]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: BEF9BB1C-3461-4423-9294-A3744DCB331F/20200514195103

### Actual behavior
These are the logs obtained from "docker logs sql1":
SQL Server 2019 will run as non-root by default.
This container is running as user mssql.
Your master database file is owned by root.
To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
ERROR: BootstrapSystemDataDirectories() failure (HRESULT 0x80070001)
SQL Server 2019 will run as non-root by default.
This container is running as user mssql.
Your master database file is owned by root.
To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
ERROR: BootstrapSystemDataDirectories() failure (HRESULT 0x80070001)
### Information

  - Windows Version: 10 Pro Version	10.0.18362 Build 18362
  - Docker Desktop Version: Docker version 19.03.8, build afacb8b
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
Running on a laptop, Windows 10 Pro, using Hyper-V.  Container created using the following <password replaced with ????>:
docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=????" `
   -v d:\sql1\data:/var/opt/mssql/data `
   -v d:\sql1\logs:/var/opt/mssql/log `
   -v d:\sql1\backup:/var/opt/mssql/backup `
   -p 1433:1433 --name sql1 `
   -d mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
### Steps to reproduce the behavior

  1. I have reproduced the problem numerous times by removing the container, recreating the container, and attempting to start it.  Both before and after removing the Windows 10 updates.
  2. ...

**Comment by neilharvey94044** [comment]
I have uninstalled the 2.3.02 and installed back to 2.2.05.  This has resolved the problem.  Will look for a future release that resolves 2.3.02 issues.  Thanks!

**Comment by mat007** [comment]
Thanks for the report and sorry for the inconvenience.
I believe this is similar to #6646 in case you wanted to track the progress on fixing it?
