### ISSUE TITLE
Docker Windows Fails to Start and Reset to Factory default

### ISSUE THREAD

**Issue by csagar** [docker/for-win#6729]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: AD61DA14-AB93-4233-A484-95BAC4D234D8/20200515012644

### Expected behavior
Should start Docker for Windows

### Actual behavior
Docker Windows Fails to Start and Reset to Factory default

### Information

  - Windows Version: Windows 10
  - Docker Desktop Version: 2.3.0.2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by antoineco** [comment]
ref #6738 possibly

**Comment by csagar** [comment]
Had to disable Hyper-V and Containers Windows feature to uninstall and delete the .vhdx file in ProgramData folder for a clean re-install later.
