### ISSUE TITLE
Docker build very slow

### ISSUE THREAD

**Issue by gregpakes** [docker/for-win#673]
### Expected behavior

I am a docker newbie, so this could be normal but I just need to check.

I am creating a container from a dockerfile and it takes over 10 minutes to create, this seems like a very long time.

dockerfile:

```
FROM microsoft/iis

MAINTAINER gregpakes

SHELL ["powershell", "-command"]

RUN Install-WindowsFeature Web-Server; \
    Install-WindowsFeature Web-ASP; \
	Install-WindowsFeature Web-Stat-Compression; \
	Install-WindowsFeature Web-Dyn-Compression; \
	Install-WindowsFeature Web-Default-Doc; \
	Install-WindowsFeature Web-Http-Errors; \
	Install-WindowsFeature Web-Http-Logging; \
	Install-WindowsFeature Web-Asp-Net45; \
	Install-WindowsFeature Web-AppInit; \
	Install-WindowsFeature Web-WebSockets;	
```

The **Microsoft/IIS** image is already downloaded.

Is this normal?

**Update**

I think I've figured it out.  I believe that because the dockerfile was in the root of my project, the build context was 10GB.  I have moved the dockerfile into it's own directory and it looks good now.

**Comment by friism** [comment]
Thanks for following up, closing.
