### ISSUE TITLE
AWS EC2 instance <Windows 10> - failed to start docker container 

### ISSUE THREAD

**Issue by chavansachin20** [docker/for-win#6730]
I have tried with the latest version of my channel (Stable or Edge)
I have uploaded Diagnostics 

**Expected behavior**
Docker should start any container 
as of now trying to create hello-world container with below command
`docker run hello-world `

**Actual behavior**
docker creates container but fails to start the container, error as below
> docker : Error response from daemon: hcsshim::CreateComputeSystem 
7ddc29884f4c63413ca009346bbd21442de9866fae5941a58d3d331baf6be110: The virtual machine could not be 
started because a required feature is not installed.

**Information**
- Windows Version: Windows 10 
- Docker Desktop Version: 
- ![image](https://user-images.githubusercontent.com/5293496/82016071-d1ac8e00-969d-11ea-81b7-685c1dd57130.png)
- Using AWS EC2 instance: this was working, suddenly stopped working on the creation of containers.

**Steps to reproduce the behavior**
1. Installer Docker for Windows 
2. Start Docker 
3. Open PowerShell with Run as Admin - execute the command : docker run hello-world  
4. error as below Screenshot 

 
**Screenshot :**
![image](https://user-images.githubusercontent.com/5293496/82015873-69f64300-969d-11ea-90d6-4fe57f3d240b.png)

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place?
Sorry, I would move it myself, but I can't because it's in a different org (it's `moby` not `docker`).

**Comment by chavansachin20** [comment]
Hi @mat007 ,

as requested raised issue under https://github.com/moby/moby
- https://github.com/moby/moby/issues/40972
