### ISSUE TITLE
WSL2 integration does not support --net=host

### ISSUE THREAD

**Issue by antoineco** [docker/for-win#6736]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

When running a container with `--net=host` inside a WSL2 environment, I can access the ports of the service it runs, at least from within the WSL2 environment.

### Actual behavior

The ports of the service running inside the container are not reachable, neither from within the WSL2 environment nor from Windows.

### Information

  - Windows Version: 10.0.19041.264
  - Docker Desktop Version: 2.3.0.1 (44875) edge
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

1. Inside WSL2, create a NGINX config file called `default.conf` in the current directory
      ```nginx
      server {
          listen       8080;
          listen  [::]:8080;
          server_name  localhost;
      }
      ```

1. Inside WSL2, run a NGINX container, mounting the config in the expected location
      ```
      $ docker run --rm \
        --net host \
        --volume $PWD/default.conf:/etc/nginx/conf.d/default.conf \
        nginx:stable
      ```

1. Send a request to `localhost:8080`
      ```console
      $ curl http://127.0.0.1:8080
      curl: (7) Failed to connect to 127.0.0.1 port 8080: Connection refused
      ```

1. Send a request to `<eth0>:8080`
      ```console
      $ curl http://172.18.153.238:8080
      curl: (7) Failed to connect to 172.18.153.238 port 8080: Connection refused
      ```

1. Try the same thing from a web browser in Windows

**Comment by antoineco** [comment]
@annam002 it seems like you managed to make this work according to https://github.com/docker/for-win/issues/6709#issuecomment-629059016?

**Comment by simonferquel** [comment]
Docker daemon runs inside an isolated network namespace with WSL2 backend. --net=host means "run my container in the network namespace where docker daemon runs", which is not the same as your distro's. 
To workaround that, you should explicitly expose ports (using `-p` flag). Exposed ports are tunelled to both the main WSL2 network namespace and windows host.

**Comment by antoineco** [comment]
I understand that, but it's a big downgrade from the experience I get when I run my own Docker daemon.

Let me give you an example: I have a local API gateway that provides a front-end application access to multiple backends running in various locations (part of it in a staging environment, part of it also running locally). Before migrating to the WSL2 backend, I could proxy to `http://localhost/myapi`. Now I either have to run everything in a container, or nothing.

On one hand Docker for Windows does a ton of magic to expose ports, Kubernetes services, etc. transparently on the Windows host, on the other hand the container network itself is completely isolated from WSL environments. This feels quite inconsistent to me.

**Comment by simonferquel** [comment]
Hmm you can workaround that quite easily, without needing `--net=host`: we have a special host entry `host.docker.internal` that resolves to your host machine (on the host, it resolves to 127.0.0.1, and it resolves to a reachable IP from a container). Instead of connecting to http://localhost/myapi, you just specify http://host.docker.internal/myapi and it should just work.

**Comment by antoineco** [comment]
Ahhh that's what this host is for, thanks for the tip @simonferquel!

**Comment by RoelofBerg** [comment]
When operating a TFTP server (or similar protocols) inside docker --net=host was quite handy. TFTP is a UDP protocol, the tftp server is reached on one certain port (69) and then connects back to the sender by any arbitrary port the sender chose. The back-connection does not happen in my experiments when I don't allow the outbound ports to be reached. Defining an arbitrary port range with tens of thousands of ports with the -p option (if this would even help) is something I'd like to avoid. For such protocols --net=host was an apropriate solution. However, in WSL2 I haven't seen it running yet.

**Comment by satomi85** [comment]
Same issue here, would be great have a fix or workaround.

**Comment by simonferquel** [comment]
Unfortunately --net=host actually means "use the same network namespace as dockerd". Dockerd itself runs in an isolated network namespace to avoid iptable clashing or similar issues with your other WSL distros.

**Comment by hxl-dy** [comment]
Keepalive.
