### ISSUE TITLE
Typo in notification "Hyper-V backend is distroying"

### ISSUE THREAD

**Issue by antoineco** [docker/for-win#6739]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

"Hyper-V backend is **destroying**"

### Actual behavior

"Hyper-V backend is distroying"

![image](https://user-images.githubusercontent.com/3299086/82045560-961abf80-96af-11ea-8531-6c16d1aee337.png)

### Information

  - Windows Version: 10.0.19041.264
  - Docker Desktop Version: 2.3.0.1 (44875) edge
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

In the troubleshooting menu, click "Reset to factory defaults"

**Comment by mat007** [comment]
Oh thanks good catch, I’ll fix it right away!
