### ISSUE TITLE
Creating multiple NAT networks => no internet inside containers

### ISSUE THREAD

**Issue by gregpakes** [docker/for-win#674]
### Expected behavior

I am using **docker-compose** to setup a legacy application for our development environments.  

I am trying to create a new nat network in the yml file.  

If I just tell it to use the pre-existing **nat** network, all containers are able to access the internet.

If I tell it to create a new network with driver type **nat**, none of the containers within than network can access the internet.

I am a newbie, but I would expect the containers to be able to access the internet.

### Actual behavior

Containers created in the new nat networks are not able to access the internet.

### Info

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 11
Server Version: 17.03.1-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 15063 (15063.0.amd64fre.rs2_release.170317-1834)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 31.82 GiB
Name: iSAMS-LAP-GREG3
ID: H5EZ:EK42:BS6Y:FC3X:TRWA:YDP5:5RCT:ZZ3U:VJ7K:GTOC:C4Y5:ZDXK
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 48
 System Time: 2017-04-26T11:07:17.8002118+10:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by friism** [comment]
Can you post a docker-compose file that reproduces the problem?

You might also want to look into the new overlay networking support: https://blogs.technet.microsoft.com/virtualization/2017/04/18/ws2016-overlay-network-driver/

It's a lot simpler than messing around with NAT.

**Comment by gregpakes** [comment]
I am now unable to replicate this.  I suspect I was connected to a VPN when testing previously.

I have looked at the overlay network support.  I have two issues/questions:

1. The documentation seems to suggest it is only applicable if running in Docker Swarm mode? 
2. The documentation suggests that container->external is not supported: https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-networking
