### ISSUE TITLE
CredStore setting not removed if Docker Desktop is uninstalled. (Stable)

### ISSUE THREAD

**Issue by rwilliams** [docker/for-win#6744]
- [✔️ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
After uninstalling Docker Desktop with WSL2 support I expect my WSL2 linux distros to behave as normal with docker installed locally.

### Actual behavior
Default distros and any other distros that were selected to use Docker Desktop with WSL2 engine have the `credStore` set to desktop.exe even though Docker Desktop no longer exists.

### Information

  - Windows Version: 19628 (Fast Ring)
  - Docker Desktop Version: Stable 2.3.0.2 (Installer Version)

### Steps to reproduce the behavior

  1. Install Docker Desktop with WSL2 backend. Set some WSL2 linux distro(s) to use Docker Desktop.
  2. Uninstall Docker Desktop. Install or re-enable local docker withing WSL2 distro. 
  3. The `config.json` in `~/.docker` is still pointing to desktop.exe for the `credStore`.

**Comment by simonferquel** [comment]
Thanks for the report. I'll add it to our backlog
