### ISSUE TITLE
'docker-machine rm ~~~' needs context hint to -force in case of error

### ISSUE THREAD

**Issue by mlefkon** [docker/for-win#675]
### Expected behavior
"Successfully removed myvm1"

### Actual behavior
PS C:\Users\xxx> docker-machine rm myvm1
About to remove myvm1
WARNING: This action will delete both local reference and remote instance.
Are you sure? (y/n): y
Error removing host "myvm1": exit status 1
PS C:\Users\xxx>

### Information
I had stopped and deleted the VM in Hyper-V.  Docker-machine rm command was not finding the VM, so it was exiting in an error.  My suggestion is to let people know that there is a "-f" option available to get around this error that would show up in the output after "Error removing host".

A diagnostic was uploaded with id: F8633AE9-1358-4921-8145-B65DA2948E14/2017-04-26_11-46-43

### Steps to reproduce the behavior

  1. Stop and delete VMname in Hyper-v
  2. CLI: docker-machine rm VMname

**Comment by friism** [comment]
Can you please open this issue against the `machine` project where a fix can be made? https://github.com/docker/machine/
