### ISSUE TITLE
WSL 2 does not rely on hyper-v. why does docker check whether Hyper-V function is enabled

### ISSUE THREAD

**Issue by hyzx86** [docker/for-win#6759]
https://docs.docker.com/docker-for-windows/wsl/#prerequisites

Why do I need to turn on the Hyper-V function after enabling the docker of WSL 2 kernel? After my test, WSL 2 can still be used normally after turning off the Hyper-V function, but the docker will still prompt that the Hyper-V function is not turned on, and then it cannot be started

I thought that after using WSL 2, VMware and docker could coexist, but this is not the case

**Comment by antoineco** [comment]
ref #6738

**Comment by hyzx86** [comment]
My fault, WSL 2 depends on Hyper-V, WSL 1 does not depend on Hyper-V

**Comment by antoineco** [comment]
WSL2 does not depend on Hyper-V. This is a bug.

**Comment by mat007** [comment]
WSL 2 needs the «Virtual Machine Platform» but not Hyper-V, see https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq#does-wsl-2-use-hyper-v-will-it-be-available-on-windows-10-home but not 
But the Docker Desktop installer is supposed to turn that on if needed, @hyzx86 is that feature off for you after installation?

**Comment by hyzx86** [comment]
> WSL2 does not depend on Hyper-V. This is a bug.

No ， WSL 2 will depend on hyper-v. 
you can see here , https://docs.microsoft.com/en-us/windows/wsl/compare-versions 

@mat007 Yes， I  turned off hyper-v ，because I need vmwere

**Comment by mat007** [comment]
@hyzx86 maybe that’ll help then: https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq#will-i-be-able-to-run-wsl-2-and-other-3rd-party-virtualization-tools-such-as-vmware-or-virtualbox ?

**Comment by hyzx86** [comment]
@mat007 
Now it's OK. I converted the virtual machine of VMware to hyper-v  ：），
Maybe we will use the co-existence of VM ware and Hyper-V in the future, but it's not the time yet

**Comment by antoineco** [comment]
> No ， WSL 2 will depend on hyper-v.
> you can see here , https://docs.microsoft.com/en-us/windows/wsl/compare-versions

@hyzx86 there is not mention of Hyper-V in this page. See Mat's reply: https://github.com/docker/for-win/issues/6759#issuecomment-630089089

**Comment by hyzx86** [comment]
> > No ， WSL 2 will depend on hyper-v.
> > you can see here , [`https://docs.microsoft.com/en-us/windows/wsl/compare-versions`](https://docs.microsoft.com/en-us/windows/wsl/compare-versions)
> 
> @hyzx86 there is not mention of Hyper-V in this page. See Mat's reply: [`#6759 (comment)`](https://github.com/docker/for-win/issues/6759#issuecomment-630089089)

Well, I just want to say that WSL 2 does not support running with VMware at the same time
