### ISSUE TITLE
Unhandled exception: Sequence contains no elements

### ISSUE THREAD

**Issue by pimverheij** [docker/for-win#6764]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mat007** [comment]
Dup of #6651
