### ISSUE TITLE
Container hangs up, even SIGKILL does not help

### ISSUE THREAD

**Issue by Pho3nixHun** [docker/for-win#6766]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B44D34EA-96A8-4EA9-A107-7B5C522D79A3/20200517091622

### Expected behavior
Container does not hang up.
Container can be killed with SIGKILL.

### Actual behavior
I noticed this on a particular image (`pho3nixhun/lit-dev:latest`), but then I tested it on a node:alpine and same issue appeared. When I issue long running `npm i` (or `yarn install`) the container hangs up. I cannot even kill it (`docker kill --signal SIGKILL <id>`). It happens 9 times out of 10. It was not happening with previous versions. 

### Information

  - Windows Version: Windows 10 Pro Build: 1909
  - Docker Desktop Version: Docker desktop 2.3.0.2 (45183)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

1. `docker run -ti -v %CD%:/srv/app node:alpine sh`
2. `cd /src/app`
3. `npm i gulp@^4.0.2 polymer-cli@^1.9.10 polyserve@^0.27.0 readline@^1.3.0 sass@^1.26.5 typescript@^3.5.2`
4. or `yarn add gulp@^4.0.2 polymer-cli@^1.9.10 polyserve@^0.27.0 readline@^1.3.0 sass@^1.26.5 typescript@^3.5.2`

I don't think it's a problem with npm, node or alpine, since it was working fine in the last 11 month and it's break down right after the latest docker version. (I also tried multiple alpine and node versions)

**Comment by Pho3nixHun** [comment]
Switching to wsl2 seems to be fixing it

**Comment by Neurrone** [comment]
I can reproduce this as well with the latest version, will try downgrading now to the previous version.

**Comment by FireFart** [comment]
Same over here

**Comment by ariddlestone** [comment]
Same here.

I'm having to manually remove the node_modules directory before running `npm ci` now. When it happens for me, other containers stop responding too.

**Comment by Neurrone** [comment]
Downgrade to 2.20 solved the issue for me. 

Am wondering how the windows releases are tested? This is not meant as any criticism, but I was also hit by #6041 in the previous 2.2 release, which cost me a few hours of debugging until I thought of checking the docker issue repo.

**Comment by FireFart** [comment]
any updates on this? Still happens on `2.3.0.3`
