### ISSUE TITLE
Windows Serve 2019 standard: Docker community cannot be updated

### ISSUE THREAD

**Issue by Ageraluon** [docker/for-win#6769]
When trying to install the newest Docker Desktop community edition (2.3.0.2) on windows server 2019, installation fails with the following message:

> Docker Desktop requires Windows 10 Pro/Enterprise (15063+) or Windows 10 Home (19018+).

The previous version runs and installs fine (2.2.0.5). Has support for windows server for the community edition been dropped?

  - Windows Version: Windows Server 2019 standard, build 17763.1217
  - Docker Desktop Version: 2.3.0.2 
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. try to install Docker desktop community edition 2.3.0.2, error prevents installation

**Comment by stephen-turner** [comment]
Docker Desktop has never been supported on Windows Server. We recommend using Docker Engine for Windows Server instead. However, we haven't intentionally broken it either.

**Comment by metrotyranno** [comment]
Uninstall KB4551853, this breaks it.

**Comment by metrotyranno** [comment]
Same issue on 17763.1158

**Comment by Ageraluon** [comment]
Thank you for the info, I'll look Docker Engine. However, Docker Desktop has been running quite well for some time on my platform, and I am hesitant to switch. Is there any chance this will be looked into or will Docker Engine be the only way to go from now on?
Thank you for the Feedback!

**Comment by mat007** [comment]
@Ageraluon sorry for the inconvenience.
Although we don’t support Docker Desktop on Windows Server, we will revert the change on the installer that prevents it from installing as we didn’t mean to do this.
This will be available in the next Stable release (next week or so, hopefully).

**Comment by metrotyranno** [comment]
AFAIK Docker Desktop seems to be the only way to install docker on windows server (apart from buying Docker Enterprise)

Docker engine lists no installation path for windows server and refers to docker desktop for windows.

**Comment by Ageraluon** [comment]
Thats great news, many thanks for your support on this one! I'm doing that as a hobby project (got Server with a university student license to tinker with for free) so enterprise would've been quite out of my league.

**Comment by StefanScherer** [comment]
@metrotyranno the Docker EE Engine license is included in a Windows Server license. You can still install it as described in https://docs.docker.com/ee/docker-ee/windows/docker-ee/ or in https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=Windows-Server

**Comment by dheeraj-10** [comment]
> 
> 
> @metrotyranno the Docker EE Engine license is included in a Windows Server license. You can still install it as described in https://docs.docker.com/ee/docker-ee/windows/docker-ee/ or in https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=Windows-Server

@StefanScherer I remember reading on the inclusion of Docker EE license with Win Server 2019. But, have been unable to locate a link either from Docker or MS for the same.
Has there been any change in the licensing terms post the takeover for Docker EE by Mirantis?
[https://www.docker.com/faq-for-docker-enterprise-customers-and-partners](url)

**Comment by StefanScherer** [comment]
@dheeraj-10 I cannot speak for Mirantis, if you need a more up to date information than what's available at the links I showed, please contact Mirantis.

**Comment by FeodorFitsner** [comment]
Any update?

**Comment by StefanScherer** [comment]
@FeodorFitsner Yes, you should be able to install the latest Stable release 2.3.0.4.

**Comment by FeodorFitsner** [comment]
Thank you! I can confirm Docker Desktop 2.3.0.4 can be installed on Windows Server 2019.
