### ISSUE TITLE
Docker version information not available in new Edge installer

### ISSUE THREAD

**Issue by riezebosch** [docker/for-win#677]
### Expected behavior
The `Docker for Windows Installer.exe` contains the version number of `Docker CE` that is installed.

### Actual behavior
The `Docker for Windows Installer.exe` has its own versioning scheme.

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior
<img width="1440" alt="screen shot 2017-04-26 at 11 19 12" src="https://cloud.githubusercontent.com/assets/1427334/25427247/3860d34a-2a72-11e7-9b93-3b80a649f71c.png">

This makes automating the update of this [chocolatey package](https://chocolatey.org/packages/docker-for-windows) very hard.

  1. ...
  2. ...

**Comment by friism** [comment]
Docker for Windows is designed to be self- and auto-updating, and the installer is not designed to be invoked by external scripts that maintain a library of different versions. Changing the installer file version is not a priority for us at the moment.

I'll keep this issue open.

**Comment by riezebosch** [comment]
By discovering the RSS (see #954)  the information from the installer is no longer required.
