### ISSUE TITLE
Hyper

### ISSUE THREAD

**Issue by jawwadkhan78** [docker/for-win#6770]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by thaJeztah** [comment]
looks like this was opened accidentally
