### ISSUE TITLE
WSL 2 documentation is unclean

### ISSUE THREAD

**Issue by creocoder** [docker/for-win#6773]
It does not explain WSL 2 distributions. Docker installed without any additional distribution still works. Running: `wsl --list --verbose` show:

```
  NAME                   STATE           VERSION
* docker-desktop         Running         2
  docker-desktop-data    Running         2
```

Can developers be more clean about those? In what cases any other distributions may be interesting? What `docker-desktop` distribution include? And why additional `docker-desktop-data` distribution needed? Can both be safely removed in case of using `Ubuntu` distribution for example?

Please update documentation with more information.

**Comment by simonferquel** [comment]
Hmm I think we have a blog post answering that, but indeed I don't think documentation include those details.

So I am describing it first here:
- docker-desktop is a distro whose only purpose is to spin up a namespace to run our Linuxkit Docker-Desktop distro (the same distro as with hyper-v or docker desktop for mac, running within a linux namespace instead as a full-fleged VM). Users should not use it (or risk breaking things), but can have a look at it, to try to understand how all that works.
- docker-desktop-data is a pure storage distro which is mounted inside the "docker-desktop" one. It allows us to recreate a fresh "docker-desktop" distro on updates without loosing data.

When you install Ubuntu and run docker client from there, we just run a thin proxy within it to expose the docker daemon and make sure bind mounts and port exposition work seemlessly, without having to install anything in your distro.

**Comment by creocoder** [comment]
Thanks so much for the explanation. The main issue with the documentation is that it does not mean that you need to install a separate distribution. Also `docker-desktop` become main distro. So it possible to build containers without installing any additional distro and run them. I think that installing additional distro should be mandatory requirement and it would be great to add such information to documentation.

> or risk breaking things

Can you elaborate please? Since it become main distro `wsl` just run `bash` inside it. And I guess you mean user can break something? (this aspect why it may be good idea to not make it main)

Is that also possible to somehow reset `docker-desktop` distro if it become broken for some reason without re-installing Docker?

**Comment by simonferquel** [comment]
Actually some users may not want to run wsl2 distros and just interact with Docker from the windows command line. For them, we should not require to install any user distro.

The docker-desktop distro exposes all the nifty details about how we run docker-desktop. Users may kill important process, remove important files and just break docker-desktop.

At any time, you can unregister docker-desktop distro. Restarting docker-desktop will just recreate it.

**Comment by creocoder** [comment]
So it not recommended to run `wsl` and do anything in `docker-desktop` distro then. I think it would be better to add this to documentation too. Also instructions how to:

> unregister docker-desktop distro

would also be great in case when user break it already by some reason.

**Comment by stephen-turner** [comment]
@creocoder Not answering your question, but if you're interested in the internal details, I recommend @simonferquel's talk at WSLconf. You can find it on Youtube.

**Comment by bshuler** [comment]
My installation is stuck on:

wsl --list --all --verbose
  NAME              STATE           VERSION
  docker-desktop    Installing      2

I am not sure where to get help from here. I have rebooted, uninstalled, etc

**Comment by zadokdaniel** [comment]
> My installation is stuck on:
> 
> wsl --list --all --verbose
> NAME STATE VERSION
> docker-desktop Installing 2
> 
> I am not sure where to get help from here. I have rebooted, uninstalled, etc

I got same issue did you find any solution?

**Comment by bshuler** [comment]
> > My installation is stuck on:
> > wsl --list --all --verbose
> > NAME STATE VERSION
> > docker-desktop Installing 2
> > I am not sure where to get help from here. I have rebooted, uninstalled, etc
> 
> I got same issue did you find any solution?

No solution yet. I have opened an issue here: https://github.com/docker/for-win/issues/7279

**Comment by simonferquel** [comment]
You can run `wsl --unregister docker-desktop`, then `wsl --shutdown` and restart docker desktop.

**Comment by cql-darian-bonnell** [comment]
@simonferquel - Freakin' Life Saver!!! That did it for me. FINALLY!!!

**Comment by simonferquel** [comment]
@Baryczka I think you are right, we modify .docker/config.json to use the same registry credential helper as on windows (and thus having to `docker login` only once)

**Comment by Baryczka** [comment]
Thanks for very quick answer @simonferquel. So this could be. I was playing with permissions for `config.json` in Windows(read only) and WSL2 (440) as Docker-desktop was changing at every boot my `"credStore":"ecr-login"` to  `"credsStore":"desktop"` and in WSL2 to desktop.exe. Is there any way to prevent this overwriting mechanism?
