### ISSUE TITLE
Docker crash while I changed the resource settings adding more RAM, more CPU, more storage and more SWAP

### ISSUE THREAD

**Issue by andrei-rebegea** [docker/for-win#6779]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
No debugging info provided, closing this ticket.
