### ISSUE TITLE
Not able to ping windows host machine from inside windows docker container

### ISSUE THREAD

**Issue by chintanhighq** [docker/for-win#678]
### Expected behavior
Should able to ping host machine
### Actual behavior
I am not able to ping **a** host machine from where docker is started. However, I can ping all other machines from same network.
### Information
**Docker version:**
```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64
 Experimental: true

```
**Docker info:**
```
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 12
Server Version: 17.03.1-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 14393 (14393.1066.amd64fre.rs1_release_sec.170327-1835)
Operating System: Windows 10 Pro N
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 7.914 GiB
Name: MACHINE1.LOCAL.COM
ID: VJST:XSIE:K6UO:AOKS:XJLE:TXKX:LDYL:6ASY:H432:3N3N:MZLP:P333
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 18
 System Time: 2017-04-26T16:56:51.8539555+05:30
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```
**Docker Networks** is as below:
```
NETWORK ID          NAME                DRIVER              SCOPE
b918926b120e        nat                 nat                 local
3f88f8a8a5aa        none                null                local
```
A diagnostic was uploaded with id: E1CCD2B3-FB55-420A-84EB-7D6B6F84108F/2017-04-26_16-45-40

### Steps to reproduce the behavior
To reproduce this issue, I simply fired below command.

`docker run -ti microsoft/nanoserver ping machine1.local.com`

in above command machine1.local.com is a host machine from where docker container is running.

If I fire below command then it works perfectly fine 
`docker run -ti microsoft/nanoserver ping machine2.local.com`
Above command is executed from machine1.local.com and it works perfectly fine. I am getting ping's response from machine2.local.com.

Please let me know in case you need further details.

TIA

**Comment by chintanhighq** [comment]
Update:

I can access docker container using docker's internal IP. Is there any way that port can be accessible on localhost instead of docker's ip?
If I use machine ip on same system then it is not working, however same thing is working from other machines.
Can anyone please explain this behavior?

**Comment by oneledgeradmin** [comment]
I run into the same issue.

**Comment by JeromeD-gre** [comment]
Is this bug fixed?
After 2 years, I got the same problem.
