### ISSUE TITLE
Docker for Windows WSL2 swarm host node ip is unresolvable.

### ISSUE THREAD

**Issue by PavelSosin-320** [docker/for-win#6790]
In the swarm mode docker node ls and inspect shows Docker WSL image as hostname instead of the host node name. Correspondingly,  in the new WSL 2.0 docker-desktop wsl running distro has own IP address but it is accessible only from the host Windows. The regular WSL distros have /etc/resolve.conf which helps to resolve the real Hostname. But the docker-desktop has not and shows unusable information. 
If I want to create use remote SSH session to access my remote Docker node in the swarm I need the host IP listed in docker node ls or docker inspect node!
https://hub.docker.com/editions/community/docker-ce-desktop-windows -->
  - [ X] I have tried with the latest version of my channel (Stable or Edge) -Edge
  ### Actual behavior:
C:\Users\Pavel>docker node inspect docker-desktop
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS      ENGINE VERSION
docker node ls
qp0h66fwz2ihy4hnt3co3ujkb *   docker-desktop      Ready               Active              Leader              19.03.8
docker node inspect docker-desktop
       "Status": {
            "State": "ready",
            **"Addr": "192.168.65.3"**
        },
        "ManagerStatus": {
            "Leader": true,
            "Reachability": "reachable",
            "**Addr": "192.168.65.3:2377**"
        }
### Expected behavior
IP addresses should be the real Host IP addresses resolved.
### Information

  - Windows Version: Win 10 2004
  - Docker Desktop Version: 2.3.2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. enable swarm orchestration and attach host as a single node
  2. docker host ls - shows docker-desktop as a host-name
  3. docker host inspect shows WSL IP addresses. 
wsl -d Docker-desktop shows the correct value for the NAME env variable, i.e. echo $NAME shows my computer name in the local network.
wsl -d docker-desktop nslookup $NAME
nslookup: can't resolve '(null)': Name does not resolve

Name:      MSI
Address 1: 127.0.1.1 MSI.localdomain

**Comment by snowdej** [comment]
I have this problem,  But
If I use WSL2 docker as swarm init - it doesnt work (same as you)
If I swarm init on another host (even a vm running docker2boot or multipass) then the wsl2 instance can join that swarm 

In other words it cant be swarm leader

**Comment by PavelSosin-320** [comment]
Yet another hint: when I use my computer name from inside running container, for example, curl MSI:<port published-by-docker-container-via-bridge-network it works, even I don't use explicitly any external DNS which can hold my laptop's IP address.  
Docker network inspect overlay shows:
**"Peers":** [
            {
                "Name": "ce80b33ec8c6",
                **"IP": "192.168.65.3" - WSL IP**
            }
Should it hold also my laptop IP?

**Comment by simonferquel** [comment]
Swarm on Docker Desktop (including Hyper-V, WSL2, and Mac backends) only work in single nodes setup, and is there for local development needs only.

This IP is the vpnkit virtual sock interface of the Docker Desktop LinuxKit environment. This environment is not reachable directly (it does not run in the main wsl2 network namespace).
