### ISSUE TITLE
Latest update keeps getting me unhealthy containers - Reset to default fails

### ISSUE THREAD

**Issue by TheDoubleH** [docker/for-win#6796]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: BC13101E-D6E4-4C50-814E-D182B34E92B7/20200519182107

### Information

  - Windows Version: Windows 10 / 1909 / 18363.836
  - Docker Desktop Version: 2.3.0.2 (45183)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Computer goes to sleep
  2. Realize container is unhealthy
  3. Reset Docker Desktop

**Comment by stephen-turner** [comment]
What do you mean by "unhealthy"?

**Comment by TheDoubleH** [comment]
> What do you mean by "unhealthy"?

When using the Docker Add-in in VS Code, the container is listed as ‘Unhealthy’. When trying to restart, remove or anything else the system just freezes.
