### ISSUE TITLE
Cannot mount volume: "The path is not of a legal form"

### ISSUE THREAD

**Issue by timster** [docker/for-win#6797]
I'm unable to mount a local volume when running a container or changing file sharing preferences.

### Expected behavior

I should be able to mount a local volume to a container.

### Actual behavior

When I try to add a path under Resources > File Sharing I get the following error:

![Screen Shot 2020-05-19 at 3 42 44 PM](https://user-images.githubusercontent.com/173666/82371109-a2708680-99e7-11ea-9166-e6df12442a33.png)

When I try to run this command to test:

`​docker run -v c:\users:/data alpine ls /data`

I get the following error:

![Screen Shot 2020-05-19 at 3 41 33 PM](https://user-images.githubusercontent.com/173666/82371191-c207af00-99e7-11ea-91cd-e6fb3c4c3631.png)

### Information

Running the latest version of Docker Desktop. Downloaded yesterday.

**Comment by stephen-turner** [comment]
@timster Please upload diagnostics and attach the ID. Thanks.

**Comment by Kznnzk** [comment]
I've got the same error ( in French) "The path is not a legal form" / "Le chemin d'accès n'a pas une forme conforme" ,  I can't mount any drive in Resources > File Sharing

I ran the same command than @timster ,

`​docker run -v c:\Users:/data alpine ls /data`

 here is the diag ID: 1A171116-9A9E-4398-8EB8-828B5DE45E7E/20200524080534 for the file I uploaded


Docker Desktop : 
`Version: 2.3.0.2 (45183)
Channel: stable`

**Comment by timster** [comment]
Unfortunately we can't send diagnostics from the machine that is having the problem. Looks like  @Kznnzk was able to send them though.

**Comment by mat007** [comment]
For some unknown reason you apparently have an empty path among the shared paths.
A workaround for the time being would be to open `%APPDATA%\Docker\settings.json`, locate the `"filesharingDirectories"` key and remove the empty path from the list.
You shouldn’t need to shutdown or restart Docker Desktop to do it.

Let me know if this fixes the issue?

**Comment by mat007** [comment]
Actually the empty folder can be seen in the UI and you should be able to remove it from there:

![image](https://user-images.githubusercontent.com/2386884/83129638-615e2d80-a0dd-11ea-8b35-189f002474f3.png)

**Comment by Kznnzk** [comment]
That fixed the issue for me. Thanks @mat007 !

**Comment by mat007** [comment]
Thanks for confirming it @Kznnzk!
There may be something amiss with the config migration, as it seems you upgraded from 2.2.0.5 (where we still had drives being shared instead of folders), right?

**Comment by Kznnzk** [comment]
>  as it seems you upgraded from 2.2.0.5 (where we still had drives being shared instead of folders), right?

That's correct.

**Comment by stephen-turner** [comment]
This is fixed in the latest Edge release, 2.3.2.0.

**Comment by djs55** [comment]
The fix from edge has now been released in latest [stable 2.4.0.0](https://desktop.docker.com/win/stable/48506/Docker%20Desktop%20Installer.exe).
