### ISSUE TITLE
Missing ipv4 address of new machine

### ISSUE THREAD

**Issue by treiboll** [docker/for-win#68]
### Expected behavior
I expect after creating a new machine, that there schould be an ipv4 address available for the eth0 device of that machine of the subnet 10.0.75.0 as it es defined in the docker settings. 

### Actual behavior
After creating new machines there are only ipv6 addresses and e.g. the joining to a swarm fails with errors. See below.

### Information
  - Diagnostic ID : 63A029AD-B8F2-434A-B976-407D5DC5A1AB/2016-09-02_08-48-23
  - Docker v1.12.0 and docker-machine 0.8.0 on Windows 10 Pro Build 1607.

### Steps to reproduce the behavior

  1. `docker-machine create --driver hyperv master`
  1. `docker-machine create --driver hyperv worker`
  1. `docker-machine ssh master`
  1. master: `docker swarm init --advertise-addr eth0` 
  1. worker: 
        `docker swarm join \ `
              `--token SWMTKN-1-51mnr3nv48rfymobh2wk0cshdjyd66uhqsz9oun5u6zsep8ew0-15901tuo8wvphqravp4u91hsw \`
              `[fe80::215:5dff:fe02:e025]:2377`
  1. error on worker: `Error response from daemon: could not find local IP address: dial udp [fe80::215:5dff:fe02:e025]:2377: connect: invalid argument`

**Comment by dgageot** [comment]
@treiboll Thank you for this bug report. I believe it should be posted on the `Docker Machine` project: https://github.com/docker/machine/issues

**Comment by treiboll** [comment]
@dgageot Thanks for your message. I created a new issue as you suggested.

**Comment by treiboll** [comment]
Closing issue....

**Comment by PhoenixAD** [comment]
The same problem...Is there any solution?

**Comment by treiboll** [comment]
Look at [this issue](https://github.com/docker/machine/issues/3718)
