### ISSUE TITLE
Unable to select WSL2 integration in Docker Setup

### ISSUE THREAD

**Issue by mudnaes** [docker/for-win#6804]
I am trying to install Docker Desktop and enable WSL2 integration. Before install Docker Desktop, I have installed Kernel Upgrade package for WSL2. 

The option for use WSL 2 based engine is always greyed out.  Have rebooted the PC multiple times. No change.

  - [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 42CC0C09-2B97-4CCB-B6BB-D9CBF8797CF7/20200520101548

### Expected behavior
Should be able to select checkbox for enable WSL2 based engine.

### Actual behavior
Box is greyed out.

### Information
Have installed both 2.3.0.1 Edge and 2.3.0.2 Stable. Same problem. I am using Debian in WSL2. It is working fine for all other development work. Windows version is 1909 (18363.836 build).

**Comment by simonferquel** [comment]
Windows 1909 does not have wsl2. I did not think it was possible to install the kernel update package on it.

**Comment by mudnaes** [comment]
Thx! I am a bit embarrassed as I thought I was running WSL2. As correctly pointed out I am not since running version 1909. 

WSL2 is available in Windows 10, version 2004.  Closing item as resolved.
