### ISSUE TITLE
no matching manifest for windows/amd64 10.0.18363 in the manifest list entries

### ISSUE THREAD

**Issue by melvin15-commit** [docker/for-win#6809]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
No info in the ticket, closing.
