### ISSUE TITLE
Repair installation fails

### ISSUE THREAD

**Issue by KOConchobhair** [docker/for-win#681]
### Expected behavior
Repair installation succeeds

### Actual behavior
Repair fails with error "The specified account already exists."

### Information

Can't launch Docker for Windows currently (which is why I'm trying to repair it)
```
c:\Program Files\Docker\Docker>dockercli -Version

Docker for Windows
Version: 17.03.1-ce-win5 (10743)
Channel: stable
Sha1: b18e2a50ccf296bcd637b330c0ca9faaab9d790c
OS Name: Windows 10 Pro
Windows Edition: Professional
Windows Build Number: 14393
```
```
c:\Users\cougar\Downloads>docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64
```
### Steps to reproduce the behavior

  1. Delete C:\Program Files\Docker\Docker\com.docker.service (somehow was removed, i suspect my virus scanner)
  2. Double-click InstallDocker.msi
  3. Click Next, Click Repair, click Repair
![image](https://cloud.githubusercontent.com/assets/2014215/25503123/2a0a0712-2b67-11e7-9055-4256a6dcb95a.png)
[MSIa6421.LOG.TXT](https://github.com/docker/for-win/files/962843/MSIa6421.LOG.TXT)

**Comment by friism** [comment]
Can you try this with the latest (non-legacy) edge installer? We've changed the installer a lot for that release.

**Comment by joamag** [comment]
I'm also having this issue. The non legacy installer does not work for me.
