### ISSUE TITLE
Docker desktop - Switching to windows contianer resulting in error

### ISSUE THREAD

**Issue by dinilvenugopal** [docker/for-win#6811]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by dinilvenugopal** [comment]
•Diagnostics ID: EF664E5B-6035-485E-A68D-5DD193187FCD/20200520151918

**Comment by stephen-turner** [comment]
Closing as dupe of #6812.
