### ISSUE TITLE
Incorporate `CleanupContainerHostNetworking.ps1` in Docker for Windows "Factory Reset"

### ISSUE THREAD

**Issue by friism** [docker/for-win#682]
(opening in public tracker to discuss with Microsoft folks)

Docker for Windows should probably incorporate elements from the Windows Docker container networking clean-up script as part of the factory reset and maybe also un-install: https://github.com/Microsoft/Virtualization-Documentation/tree/master/windows-server-container-tools/CleanupContainerHostNetworking

cc @jmesser81 @dineshgovindasamy @kallie-b @patricklang @simonferquel

**Comment by kallie-b** [comment]
I've taken on the task of re-vamping the script and ensuring it's covering all of the bases that we need. I know it needs some updates to catch up with overlay and other platform changes that have been made recently. I still need to gain a lot more clarity on the specific gaps that exist with the script, and how exactly it should be improved. If you guys have thoughts on that front I'd love to hear them :)
