### ISSUE TITLE
Can not start Kubernetes cluster

### ISSUE THREAD

**Issue by ratanparai** [docker/for-win#6820]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E18040AA-0687-49C9-B4E3-F54256678BE1/20200521053251

### Expected behavior

Enable Kubernetes from settings should start Kubernetes cluster 

### Actual behavior

Kubernetes status keep showing `Starting`. I tested with both the Stable and Edge channel and with and without WSL2 integration enabled. Keep it for ~12+ hours and the status doesn't change. 

### Information

  - Windows Version: Windows 10 Pro (2004)
  - Docker Desktop Version: 2.3.1.0 (45408) - edge channel
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Go to Kubernetes settings
  2. Enable Kubernetes 
  3. The status of Kubernetes keep showing `starting`

**Comment by ChiefInnovator** [comment]
I am having the same issue!  Please help.  This is a blocker.

**Comment by ChiefInnovator** [comment]
I was finally able to get Kubernetes installed.  Please see the issue I just closed on troubleshooting and debugging.  https://github.com/docker/for-win/issues/6817

**Comment by ratanparai** [comment]
Apparently this was a network issue, downloaded those images and then it Kubernetes starts without any issue. Thanks, @ChiefInnovator  🎉

```shell
docker/desktop-kubernetes:kubernetes-v1.16.5-cni-v0.8.5-critools-v1.17.0
docker/desktop-storage-provisioner:v1.1
docker/desktop-vpnkit-controller:v1.0
k8s.gcr.io/kube-proxy:v1.16.5
k8s.gcr.io/kube-scheduler:v1.16.5
k8s.gcr.io/kube-controller-manager:v1.16.5
k8s.gcr.io/kube-apiserver:v1.16.5
docker/kube-compose-controller:v0.4.25-alpha1
docker/kube-compose-api-server:v0.4.25-alpha1
docker/kube-compose-installer:v0.4.25-alpha1
k8s.gcr.io/etcd:3.3.15-0
k8s.gcr.io/coredns:1.6.2
k8s.gcr.io/pause:3.1
```

**Comment by ChiefInnovator** [comment]
> Apparently this was a network issue, downloaded those images and then it Kubernetes starts without any issue. Thanks, @ChiefInnovator 🎉
> 
> ```shell
> docker/desktop-kubernetes:kubernetes-v1.16.5-cni-v0.8.5-critools-v1.17.0
> docker/desktop-storage-provisioner:v1.1
> docker/desktop-vpnkit-controller:v1.0
> k8s.gcr.io/kube-proxy:v1.16.5
> k8s.gcr.io/kube-scheduler:v1.16.5
> k8s.gcr.io/kube-controller-manager:v1.16.5
> k8s.gcr.io/kube-apiserver:v1.16.5
> docker/kube-compose-controller:v0.4.25-alpha1
> docker/kube-compose-api-server:v0.4.25-alpha1
> docker/kube-compose-installer:v0.4.25-alpha1
> k8s.gcr.io/etcd:3.3.15-0
> k8s.gcr.io/coredns:1.6.2
> k8s.gcr.io/pause:3.1
> ```

Glad I could help.  BTW, I noticed you have two more images than I.  The VPNKit and Storage Provisioner.  What in your setup required these?

**Comment by ratanparai** [comment]
@ChiefInnovator: I enabled Kubernetes with WSL2 in another machine (fresh) and then run `docker images` command to list all the images it downloaded. Then I downloaded those images on the affected machine. I have no idea why they were there and if they are required.

**Comment by ChiefInnovator** [comment]
I noticed that those extra images came down on my Mac and not on my Windows machine.
