### ISSUE TITLE
Docker fails to start when fixed-cidr specified

### ISSUE THREAD

**Issue by biiiipy** [docker/for-win#683]
### Expected behavior
It should create a nat with a subnet that's specified in fixed-cidr
### Actual behavior
Fails to start:
```
Error starting daemon: Error initializing network controller: Error creating default network: HNS failed with error : The object already exists. 

   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Windows.Restart(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```
### Information

  - Diagnostic ID: 87AD68EE-6A16-4030-AE12-A37335FD83E9/2017-04-28_08-07-05
  - Windows 10 Anniversay build 14393.1066

### Steps to reproduce the behavior

1. Get-ContainerNetwork and copy nat subnet
2. Set fixed-cidr with the copied nat subnet through UI - for example "fixed-cidr": "172.27.32.0/20"
3. Exit Docker and kill Docker service (Docker.Service)
4. (Get-ContainerNetwork | Where-Object {$_.Name -eq 'nat'}) | Remove-ContainerNetwork
5. Start Docker

**Comment by JanneRantala** [comment]
@biiiipy This is the same issue I've been discussing with MS people for several weeks now. At first, my issue was with Windows Server 2016 and getting exactly the same error as you described. That problem still persists (Issue https://github.com/Microsoft/Virtualization-Documentation/issues/529). But yesterday I was able to get the same problem with Docker for Windows after I had installed stable channel version when trying to see if this fixed-cidr issue exists there. Edge channel version starts though but it doesn't change that network. Was this issue with stable or edge channel?

**Comment by biiiipy** [comment]
Thanks @JanneRantala for the reply!

**I'm using:**
Version 17.03.1-ce-win5 (10743)
Channel: stable

Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64
 Experimental: false

**But on Windows Server 2016 I don't have this issue with this Docker version:**
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.24)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      windows/amd64
 Experimental: false
