### ISSUE TITLE
windows docker

### ISSUE THREAD

**Issue by wiztrust** [docker/for-win#6831]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by wiztrust** [comment]
windows docker errors

**Comment by stephen-turner** [comment]
No info in this ticket, closing
