### ISSUE TITLE
CPU goes wild without running any containers

### ISSUE THREAD

**Issue by blindzero** [docker/for-win#6834]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics: no because of compliance reasons

### Expected behavior
CPU shouldn't go wild without any container running.

### Actual behavior
After booting PC the fan is running wild.
Looking into task manager shows "System Interrupts" at 100%. Sometimes it is vmmem process.
Shutting down Docker solves the issue.

### Information
  - Windows Version: Win 10 Pro N - 1909 18363.836
  - Docker Desktop Version: 2.3.0.2 (45183) (latest stable at this point)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No, plain Windows with Windows Container (but switching to Linux containers seems not to make a difference)
  - It occured with latest Windows Patch day update.

### Steps to reproduce the behavior
  1. Starting PC
  2. Docker is automatically started --> behaviour
  3. Shutdown Docker --> problem is gone

**Comment by hoogamaphone** [comment]
I've been having this problem as well. While Docker is running, vmmem stays flat in the 12-16% cpu usage (never idle). If I restart docker, I can see that vmmem drops off, and then as soon as Docker restarts, it comes back at 12-16% usage.
