### ISSUE TITLE
Docker not enabling hyper-V on windows enterprise

### ISSUE THREAD

**Issue by atotalnoob** [docker/for-win#6835]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:  C250266E-5E25-446E-8F14-E6948E92EC0B/20200522171027

### Expected behavior
Docker works without any issues
### Actual behavior

Installed docker for windows, checked enable hyper-V. 

After install and reboot, I ran `docker -v` and got `Docker version 19.03.8, build afacb8b`

Running `docker run hello-world` gets 
```
docker: error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/create: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
See 'docker run --help'.
```

I tried enabling/disabling hyper-v, rebooting, reinstalling, etc. When I try to start docker from the gui, I just get `Cannot enable Hyper-V service`

I ran `systeminfo` and under `Hyper-V Requirements` got 

``` 
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: No
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes
```

To me, this points to virtualization not being enabled in bios. I checked and it isn't enabled. Being as this is a corporate laptop, I don't have access to change this setting. 

Is there another way I can get docker working without enabling virtualization?

### Information
  - Windows Version: 1803
  - Docker Desktop Version: 19.03.8, build afacb8b
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

**Comment by mat007** [comment]
Sorry, there is no way to use Docker Desktop without enabling virtualization, see https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization
