### ISSUE TITLE
Issue with running the docker(PORT)

### ISSUE THREAD

**Issue by bhanuteja2001** [docker/for-win#6839]
![Screenshot (128)](https://user-images.githubusercontent.com/44323155/82733473-ac6cef00-9d31-11ea-9ba3-e566cd061287.png)

Docker Verison : v18.09.0

What can be the issue?

**Comment by mat007** [comment]
Your server runs on port 5000 in the container but you’re mapping 8000, see https://docs.docker.com/engine/reference/commandline/run/#publish-or-expose-port--p---expose
Try
```
docker run -p 5000:8000 money_api
```

**Comment by bhanuteja2001** [comment]
@mat007  i have tried it, no use!!!

**Comment by mat007** [comment]
Try replacing the IP address in your browser with `localhost`.

**Comment by bhanuteja2001** [comment]
@mat007 nope no use

**Comment by bhanuteja2001** [comment]
Yeah i found the mistake
had to change the host to 0.0.0.0

**Comment by bhanuteja2001** [comment]
@sabarnix if you are using a flask application and trying to make a container using docker.Then in the ___main__ part of the code change the run(hosy ='0.0.0.0')
