### ISSUE TITLE
ERROR: Couldn't connect to Docker daemon. You might need to start Docker for Windows. #5099

### ISSUE THREAD

**Issue by lioaslan** [docker/for-win#6841]
Hi, 
I have just installed Docker and I try to use `docker-compose up` but It show error: `ERROR: Couldn't connect to Docker daemon. You might need to start Docker for Windows. #5099`
I try to restart Docker and restart Window but it doesn't work.
```
docker-compose version 1.25.5, build 8a1c60f6
Docker version 19.03.8, build afacb8b
```
Thanks for any helps

**Comment by mat007** [comment]
Do you have a `DOCKER_HOST` environment variable set? Or any environment variable that starts with `DOCKER_`?
Do you have a `Docker Desktop` service running?
Is Docker Desktop started?
