### ISSUE TITLE
Docker desktop - kubernetes failed to start on windows

### ISSUE THREAD

**Issue by udyshnkr** [docker/for-win#6844]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B3FD67FA-5CD7-45CA-8E4D-FFC8029B6F30/20200524071208

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. Download docker desktop on windows standard edition
  2. Install and leave defaults as-is enable Kubernetes, gets stuck forever.

**Comment by PavelSosin-320** [comment]
The same on my Windows 10 2005 WSL2 dev pre-release Docker Desktop edge. 
Docker context ls shows something non-understandable:
pavel@MSI:~$ ```
docker context ls
NAME                DESCRIPTION                               DOCKER ENDPOINT               KUBERNETES ENDPOINT                                 ORCHESTRATOR
default *           Current DOCKER_HOST based configuration   unix:///var/run/docker.sock   https://kubernetes.docker.internal:6443 (default)   swarm
```
docker-test                                                   unix:///var/run/docker.sock   **! My test context**                                                    swarm
from my Ubuntu 20.04 distro kubectl shows
kubectl cluster-info
Kubernetes master is running at https://kubernetes.docker.internal:6443
KubeDNS is running at https://kubernetes.docker.internal:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
and kubectl get pods --all-namespaces=true shows:
kube-system   etcd-docker-desktop                      1/1     Running   20         14d
kube-system   kube-apiserver-docker-desktop            1/1     Running   20         14d
.........
**Where is the truth?**
Diagnostics ID 1695A9B2-5AAE-4023-953F-F08D7698FC5A/20200606061512
