### ISSUE TITLE
Error response from daemon: open \\.\pipe\docker_engine_linux: The system cannot find the file specified.

### ISSUE THREAD

**Issue by taliw-gituser** [docker/for-win#6853]
- [x] I have tried with the latest version of my channel (Stable or Edge)
I upgraded to 2.2.0.5, the latest version causes another issue for us so can't use it
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: error evaluating symlinks from mount source "/host_mnt/c/Users/noa.ohayon/.asms": lstat /host_mnt: function not implemented.
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 0E8F7A66-2288-4423-8810-7C676A38D7FB/20200525054511

### Expected behavior
Docker works properly
### Actual behavior
Can't run any docker commands in powershell, only get response
Error response from daemon: open \\.\pipe\docker_engine_linux: The system cannot find the file specified.

### Information

  - Windows Version: 10
  - Docker Desktop Version: 2.2.0.5
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mftmoto** [comment]
I join to the problem...
Same trouble.

**Information**
- Windows Version: 10
- Docker Desktop Version: 2.3.0.3


Restart docker solves problem, but it down every 15 minutes.

**Comment by rimmugygr** [comment]
I have that on windows 10:
C:\WINDOWS\system32>docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false
Error response from daemon: open \\.\pipe\docker_engine_linux: The system cannot find the file specified.

**Comment by Donadonzi** [comment]
I had the same issue, and I was using the **Stable** version. I changed to the **Edge** version and the error went away.

**Comment by shitole18** [comment]
having same error

**Comment by alexyakunin** [comment]
Same error.

**Comment by mcalcote** [comment]
Keep getting the same error 😢

**Comment by joaovictortb** [comment]
Continue recebendo o mesmo erro 😢😢😢

**Comment by PeterPorzuczek** [comment]
How to fix it?

**Comment by ricardopaiva** [comment]
If you're using WSL 2 backend, this might help solving the problem.

Open Powershell
Run "**wsl --list**"
You should see "**docker-desktop**" and "**docker-desktop-data**". If "docker-desktop-data" is the default one, change the default one to "docker-desktop" running the following command:
"**wsl --set-default docker-desktop 2**".
Restart Docker.

**Comment by john-j-stout** [comment]
> If you're using WSL 2 backend, this might help solving the problem.
> 
> Open Powershell
> Run "**wsl --list**"
> You should see "**docker-desktop**" and "**docker-desktop-data**". If "docker-desktop-data" is the default one, change the default one to "docker-desktop" running the following command:
> "**wsl --set-default docker-desktop 2**".
> Restart Docker.

This solved the problem for me, thanks!

**Comment by maxiride** [comment]
Likely a duplicate of #4495 please focus all efforts on a single issue ticket.
