### ISSUE TITLE
Docker desktop for Windows stuck in updating on start

### ISSUE THREAD

**Issue by joacar** [docker/for-win#6857]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `FC8B3C92-4AD8-43CD-B2B4-7030ED06A572/20200525090602`

### Expected behavior
Docker Desktop for Windows should start

### Actual behavior
Docker Desktop for Windows doesn't start but stuck in "Docker _updating_". 

### Information

  - Windows Version: Microsoft Windows 10 Enterprise 10.0.17763 N/A Build 17763
  - Docker Desktop Version: 2.3.0.2 (45183)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

I reset to factory defaults Wednesday and then it worked, but now it's back. Sometimes it starts after a restart, and sometimes not. Think this started when an update got stuck.. Pressing Cancel doesn't work either, still updating.

### Steps to reproduce the behavior
Start Docker Desktop for Windows

**Comment by mollychen12** [comment]
I got the same question ,as I run the docker desktop on my laptop which could touch the internet ,it's goes well,but while I run the docker desktop on my pc which is out of internet,it keep updating~ I doubt if is the problem of the internet
