### ISSUE TITLE
Docker desktop failed to start after updating to v2.3.1.0

### ISSUE THREAD

**Issue by phonethantko** [docker/for-win#6859]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 108C2B4D-707D-467B-B3A4-B1BA49A7CD7C/20200525141924

### Expected behavior
Docker Desktop to start as expected

### Actual behavior
Docker Desktop failed to start with 
```System.InvalidOperationException: Failed to deploy distro docker-desktop```

After attempting to restart the docker, it is stuck at the starting stage.

### Information

  - Windows Version: Windows 10 Home 013661494357
  - Docker Desktop Version: 2.3.1.0 (45408)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: NIL

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by simonferquel** [comment]
From the logs, it seems WSL service crashed.
Can you try to restart lxssmanager service and restart Docker Desktop ?

**Comment by phonethantko** [comment]
This resolved the issue. Thanks - I will close the issue now.
