### ISSUE TITLE
Windows 10 Docker container never starts - Docker ps locks up

### ISSUE THREAD

**Issue by bvandehey** [docker/for-win#686]
### Expected behavior
Executing the following command: "docker -it --rm microsoft/nanoserver cmd" should give a command prompt in the new container.

### Actual behavior
The command never returns a prompt and appears to hang. Going into another Powershell instance and running "docker ps" also just hangs. I have tried both the Stable channel and the Edge channel.

### Information

  - Diagnostic ID: 830B227B-139A-497D-A934-7AF958FB6266/2017-04-29_10-25-45
PS C:\WINDOWS\system32> docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 17.05.0-ce-rc1
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 14393 (14393.0.amd64fre.rs1_release.160715-1616)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 31.89GiB
Name: ALK-NUC1259
ID: 4WWQ:ZUCJ:Y3XK:EOAF:MFDM:VX56:XQZ6:UMAN:DUZC:3M5O:WBCK:RRLI
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

### Steps to reproduce the behavior

  1. docker -it --rm microsoft/nanoserver cmd

**Comment by pennacook** [comment]
seeing the same behavior on current stable. Docker run with either nano or windowsservercore hang. Docker ps also hangs. 
Images pull okay, but no container will run.

Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 3
Server Version: 17.03.1-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 14393 (14393.0.amd64fre.rs1_release.160715-1616)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 7.999 GiB
Name: VDDP35X
ID: QZH4:UROT:P2ZC:JFSN:XDPQ:P35X:GARL:LTES:4O5I:XS3B:BIDV:NOG4
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 26
 System Time: 2017-05-18T09:57:25.6854997-04:00
 EventsListeners: 0
Http Proxy: xxxx
Https Proxy: xxxx
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by pennacook** [comment]
seeing the same behavior on current stable. Docker run with either nano or windowsservercore hang. Docker ps also hangs. A diagnostic was uploaded with id: 07CE4D39-F29C-4A2A-8D06-554556801AD2/2017-05-18_09-55-30
Images pull okay, but no container will run.

Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 3
Server Version: 17.03.1-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 14393 (14393.0.amd64fre.rs1_release.160715-1616)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 7.999 GiB
Name: VDDP35X
ID: QZH4:UROT:P2ZC:JFSN:XDPQ:P35X:GARL:LTES:4O5I:XS3B:BIDV:NOG4
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 26
 System Time: 2017-05-18T09:57:25.6854997-04:00
 EventsListeners: 0
Http Proxy: xxxx
Https Proxy: xxxx
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by Francommit** [comment]
Experiencing the same behaviour with Docker EE on Win Server 2016 Standard

**Comment by andrewleech** [comment]
I'm getting exactly the same behavior occasionally. Not sure how to trigger it, my server runs fine for some time (2016 core) using docker for CI builds, then one will not respond to the same `docker run` command used shortly beforehand, after which manually running `docker ps` never completes.

**Comment by Francommit** [comment]
@andrewleech  how'd you installer docker? Offline or online? I'm beginning to think the offline installer skips some steps.

**Comment by andrewleech** [comment]
This is on a server I've been using for well over a year, but I'm quite sure it was installed online. 
My old notes are:
```
Install-Module -Name DockerMsftProvider -Repository PSGallery -Force -Confirm:$False
Install-Package -Name docker -ProviderName DockerMsftProvider -Force -Confirm:$False
```
and I've updated it a number of times since with 
```
Install-Package -Name docker -ProviderName DockerMsftProvider -Update -Force
```
Sorry I don't remember what version it's on currently, I'll check and update again when I get to the office.

This issue has happened a number of time to us, possibly once a month or so. 
When it occurs, killing / restarting the docker service doesn't help, I still can't run `docker ps`. 
I've found I have to just restart the server.

**Comment by Francommit** [comment]
Hmm are you using an AV by any chance? I'm trying to find common problems between different people experiencing the same issue.

**Comment by andrewleech** [comment]
Nope, no AV. Currently even the built in defender has been shut off.

**Comment by andrewleech** [comment]
PS C:\Users\Administrator> docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 191
Server Version: 17.06.2-ee-6
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.2248.amd64fre.rs1_release.180427-1804)
Operating System: Hyper-V Server 2016
OSType: windows
Architecture: x86_64
CPUs: 3
Total Memory: 4.996GiB
Name: windows1-spring
ID: IA37:7XUY:7M5J:ZBFO:FVZ7:XKEL:XDKV:DGKY:NO5A:36AD:C6ER:CPAM
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by Francommit** [comment]
Hey Andrew. Mind flicking me an email at francommit@gmail.com ? Want to see if we can find any similarities between our environments. Cheers.

**Comment by Francommit** [comment]
Had another crack. This is where mine's falling over:

![image](https://user-images.githubusercontent.com/11533365/41086250-c2c934f0-6a7c-11e8-8c6d-1039ee41b863.png)

After this a reboot is required in order to get docker to a useable state. Otherwise the container remains locked and can't be used by anyone.

**Comment by Francommit** [comment]
Turns out my server's installation of 'Containers' was corrupted. After using another fresh server everything worked fine.
