### ISSUE TITLE
Cant start kubernetes

### ISSUE THREAD

**Issue by innovateklb** [docker/for-win#6865]
I went to settings> kubernetes > enable kubernetes 

It never starts , always with status "starting":
![image](https://user-images.githubusercontent.com/56449728/82844403-f946f600-9ee8-11ea-927d-43ace7151ef6.png)

I have factory reset and cleared all containers, yet the issue persists.

I need some help plz.

Regards, 

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by agateriver** [comment]
Same problem

**Comment by relief-melone** [comment]
you can search ;) it looks like this is beeing opend alot of times recently. 
Possibly Duplicate of #6627

**Comment by Nish17g** [comment]
Please add the following line to the etc\hosts files
127.0.0.1 kubernetes.docker.internal
