### ISSUE TITLE
Failed to set version to docker-desktop: exit code: -1

### ISSUE THREAD

**Issue by jasonyux** [docker/for-win#6868]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A73FF5E5-D3D8-4D4D-887F-20A8C34A8252/20200526012841

### Expected behavior
Docker starts when I click the docker desktop app. Reset to factory default and re-installing has both been tried, but the error persists.
### Actual behavior
"An error occurred" window pops up, with the first two lines:
```
Failed to set version to docker-desktop: exit code: -1
 stdout: 
 stderr: �ο��Ķ������Ͳ�֧�ֳ��ԵĲ�����
```

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jasonyux** [comment]
Part of the `logfile` where the error begins looks like this:
```
[09:28:37.573][DockerHub         ][Info   ] Login successfull
[09:28:37.719][WSL2Provisioning  ][Error  ] Failed to set version to docker-desktop: exit code: -1
 stdout: 
 stderr: ?ο???????????????????????
[09:28:37.725][LinuxWSL2Engine   ][Info   ] Stopping windows side processes
[09:28:37.851][LinuxWSL2Engine   ][Info   ] Stopping engine
[09:28:38.023][LinuxWSL2Engine   ][Warning] Failed to send stop message to distro, will terminate abrubtly: ?ο???????????????????????
[09:28:38.202][LoggingMessageHandler][Info   ] [6479b8f8] <BackendAPIClient start> POST http://backend/windowsfeatures/check
[09:28:38.800][LoggingMessageHandler][Info   ] [6479b8f8] <BackendAPIClient end> POST http://backend/windowsfeatures/check -> 200 OK (took 598ms)
[09:28:39.551][LinuxWSL2Engine   ][Info   ] Terminating lingering processes and wsl distros and patching host file
[09:28:39.551][LoggingMessageHandler][Info   ] [acbba378] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[09:28:39.649][LoggingMessageHandler][Info   ] [acbba378] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 96ms)
[09:28:39.651][WSL2Provisioning  ][Info   ] Checking docker-desktop
[09:28:39.652][WSL2Provisioning  ][Info   ] deploying WSL distro docker-desktop to C:\Users\26238\AppData\Local\Docker\wsl\distro
[09:28:40.337][WSL2Provisioning  ][Error  ] Failed to set version to docker-desktop: exit code: -1
 stdout: 
 stderr: ?ο???????????????????????
[09:28:40.338][LinuxWSL2Engine   ][Info   ] Stopping windows side processes
[09:28:40.458][LinuxWSL2Engine   ][Info   ] Stopping engine
[09:28:40.624][LinuxWSL2Engine   ][Warning] Failed to send stop message to distro, will terminate abrubtly: ?ο???????????????????????
[09:28:40.782][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.FailedToStartState to state change sink
[09:28:40.782][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.FailedToStartState sent to state change sink
[09:28:40.782][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.FailedToStartState from LinuxWSL2
[09:28:40.783][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"failed to start","Mode":"linux","date":1590456520}
```

**Comment by simonferquel** [comment]
Yes, can you:
- Stop Docker Desktop
- Restart LxssManager service
- unregister docker-desktop wsl distro (`wsl.exe --unregister docker-desktop`)
- restart Docker Desktop ?

**Comment by ZhouJie-BBM** [comment]
Same issue here, I already followed this step and still not working:
* Stop Docker Desktop
* Restart LxssManager service
* unregister docker-desktop wsl distro (wsl.exe --unregister docker-desktop)
* restart Docker Desktop

My error message is:
```
System.InvalidOperationException:
Failed to set version to docker-desktop: exit code: -1
 stdout: �S��v�[a�{|�W
N/ec\Ջ�v�d\O0

stderr: 
   在 Docker.Core.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) 位置 C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Core\WslCommand.cs:行号 119
   在 Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__6.MoveNext() 位置 C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:行号 48
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__23.MoveNext() 位置 C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:行号 91
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() 位置 C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:行号 29
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() 位置 C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:行号 67
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() 位置 C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:行号 92
```

My system environment info:
```
C:\Users\ZhouJie>wsl --list --verbose
  NAME              STATE           VERSION
* Ubuntu-20.04      Stopped         2
  docker-desktop    Stopped         2
```

My windows 10 version is `10.0.19041.264`, ubuntu-20.04 can run successfully.

**Comment by simonferquel** [comment]
if you try to run `wsl -d docker-desktop` can you enter the docker desktop distro manually ?

**Comment by tndev1219** [comment]
I tried to enter the docker desktop distro manually with above command.
But I can't with this error..
`The attempted operation is not supported for the type of object referenced.`

**Comment by solxnp** [comment]
> if you try to run `wsl -d docker-desktop` can you enter the docker desktop distro manually ?

I also encountered this problem, but after I tried to execute this command, although I can enter, I still cannot use the docker command

![image](https://user-images.githubusercontent.com/18416053/93071272-8689a280-f6b2-11ea-9b1a-c5106bbfad5b.png)

**Comment by irudayarajjoseph** [comment]
> * [x]  I have tried with the latest version of my channel (Stable or Edge)
> * [x]  I have uploaded Diagnostics
> * Diagnostics ID: A73FF5E5-D3D8-4D4D-887F-20A8C34A8252/20200526012841
> 
> ### Expected behavior
> Docker starts when I click the docker desktop app. Reset to factory default and re-installing has both been tried, but the error persists.
> 
> ### Actual behavior
> "An error occurred" window pops up, with the first two lines:
> 
> ```
> Failed to set version to docker-desktop: exit code: -1
>  stdout: 
>  stderr: �ο��Ķ������Ͳ�֧�ֳ��ԵĲ�����
> ```
> 
> ### Information
> * Windows Version:
> * Docker Desktop Version:
> * Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
> 
> ### Steps to reproduce the behavior
> 1. ...
> 2. ...
Solution 
Disable Legacy Console for Command Prompt in Windows 10
Press Windows Key + X then select Command Prompt (Admin).
Right-click on the Title bar of the Command Prompt and select Properties. ...
disable legacy mode then uncheck “Use legacy console (requires relaunch)” and click OK.

**Comment by irudayarajjoseph** [comment]
Disable Legacy Console for Command Prompt in Windows 10
Press Windows Key + X then select Command Prompt (Admin).
Right-click on the Title bar of the Command Prompt and select Properties. ...
disable legacy mode then uncheck “Use legacy console (requires relaunch)” and click OK.

**Comment by irudayarajjoseph** [comment]
> * [x]  I have tried with the latest version of my channel (Stable or Edge)
> * [x]  I have uploaded Diagnostics
> * Diagnostics ID: A73FF5E5-D3D8-4D4D-887F-20A8C34A8252/20200526012841
> 
> ### Expected behavior
> Docker starts when I click the docker desktop app. Reset to factory default and re-installing has both been tried, but the error persists.
> 
> ### Actual behavior
> "An error occurred" window pops up, with the first two lines:
> 
> ```
> Failed to set version to docker-desktop: exit code: -1
>  stdout: 
>  stderr: �ο��Ķ������Ͳ�֧�ֳ��ԵĲ�����
> ```
> 
> ### Information
> * Windows Version:
> * Docker Desktop Version:
> * Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
> 
> ### Steps to reproduce the behavior
> 1. ...
> 2. ...

Disable Legacy Console for Command Prompt in Windows 10
Press Windows Key + X then select Command Prompt (Admin).
Right-click on the Title bar of the Command Prompt and select Properties. ...
disable legacy mode then uncheck “Use legacy console (requires relaunch docker)” and click OK.
