### ISSUE TITLE
sudden `The command 'docker-compose' could not be found in this WSL 1 distro.`

### ISSUE THREAD

**Issue by iamdevlinph** [docker/for-win#6876]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6899FC08-4418-4FEC-826E-C0EE2789A4CF/20200526075002

### Expected behavior

I was expecting `docker-compose` to run.

### Actual behavior

```
➜  project git:(develop) docker-compose up -d
The command 'docker-compose' could not be found in this WSL 1 distro.
We recommend to convert this distro to WSL 2 and activate
the WSL integration in Docker Desktop settings.
See https://docs.docker.com/docker-for-windows/wsl/ for details.
```

### Information

  - Windows Version: Windows 10 Version 1909 (OS Build 18363.836)
  - Docker Desktop Version: 2.3.0.2 (45183)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

I just recently switched back to a project that uses docker and I got this error. I think there was an update before this version that I'm using. I wasn't working on the project so I don't know if `docker-compose` already broke during that time.

The thing is, I'm expected to be on WSL 2 when it's still not yet released publicly, it's still in the insider builds. And it's also impossible to enable the WSL 2 engine in the docker  desktop settings because it needs Win 10 build 19018+

**Comment by iamdevlinph** [comment]
Tried switching between
```
export DOCKER_HOST=tcp://localhost:2375
#export DOCKER_HOST=unix:///var/run/docker.sock
```

**Comment by iamdevlinph** [comment]
Tried switching to `Windows containers` but still nothing

**Comment by iamdevlinph** [comment]
Solved by downgrading from `2.3.0.2 (45183)` to `2.2.0.5 (43884)`

**Comment by thaJeztah** [comment]
> The thing is, I'm expected to be on WSL 2 when it's still not yet released publicly, it's still in the insider builds. And it's also impossible to enable the WSL 2 engine in the docker desktop settings because it needs Win 10 build 19018+

I think WSL2 should be generally available now (as of one or two weeks?)

**Comment by iamdevlinph** [comment]
As far as the public ring or release goes, version 2004 (which has the WSL2 as far as i know) is still due to be released on the 28th of May 2020 according to the first result on google. And it's not going to be available to all users at once so it will also take a while for everyone to have the update.

**Comment by StefanScherer** [comment]
@iamdevlinph indeed, the `docker` and `docker-compose` helper scripts which we ship with 2.3.0.2 assumes WSL2.
In a WSL1 distro you could install `docker-compose` binary or via pip and have in in PATH. AFAIK the helper script that shows the warning is at the end of the PATH, so your local installed binaries should still work.
Correct, I also hope that May 28th will give you the chance to update to v2004.

**Comment by iamdevlinph** [comment]
@StefanScherer I also tried installing `docker-compose` thru pip but it wasn't working for me so I just downgraded.
Anyways, let's just hope the windows update will really come on the 28th and will not cause any issues (looking at the recent windows update track record 😆)

**Comment by thaJeztah** [comment]
Sorry for the confusion on my side; I _thought_ it was generally available, but there was some confusion and Microsoft _tweeted_ it was available, but they, erm, did so prematurely 😂

**Comment by sas5580** [comment]
> 
> 
> As far as the public ring or release goes, version 2004 (which has the WSL2 as far as i know) is still due to be released on the 28th of May 2020 according to the first result on google. And it's not going to be available to all users at once so it will also take a while for everyone to have the update.

You can actually download the update right now through the [Update Assistant](https://www.microsoft.com/en-ca/software-download/windows10), even if it doesn't show up when you check for updates.

**Comment by iamdevlinph** [comment]
Make sure you've enabled wsl2 and set the distro you're using to be an wsl2 one.
Refer: 
- https://scotch.io/bar-talk/trying-the-new-wsl-2-its-fast-windows-subsystem-for-linux
- https://pureinfotech.com/install-windows-subsystem-linux-2-windows-10/

Then you'll also need to make sure the "enable wsl 2 integration" thing is checked in the docker setting.

**Comment by ltlvtao** [comment]
Maybe you have installed docker-desktop on windows too. So, docker-compose in wsl is not avalible. You can rename docker-compose to another name in "C:\Program Files\Docker\Docker\resources\bin".

**Comment by fighcell** [comment]
This issue is not resolved. Many devices like the surface book 2 still don't have the Windows 10 2004 update and WSL 2. When docker version 2.3.0.45519 is installed docker-compose is giving the error:

he command 'docker-compose' could not be found in this WSL 1 distro.
We recommend to convert this distro to WSL 2 and activate
the WSL integration in Docker Desktop settings.

Solution is downgrading Docker-Desktop
