### ISSUE TITLE
Can't delete directory after it's been mounted to a container

### ISSUE THREAD

**Issue by mcongy** [docker/for-win#6889]
I can't delete a directory after it's been mounted to a container.

I'm using image `node:lts-alpine`

When I run my container using

`docker run --rm -v <<path_to_my_directory>>:/var/task:ro,delegated node:lts-alpine node <<path_to_my_node_script.js>>`
(and it successfully finishes), the directory remains in a strange state, where it can't be deleted.

I tried everything, deleting from the command line and from the windows file explorer.

### Expected behavior
Directory can be deleted as usual.

### Actual behavior
Directory can't be deleted, operation hangs for a while, and then ends with 
`Error: EPERM: operation not permitted, lstat`

`docker ps` doesn't show any running containers.

### Information

Windows: Windows 10 Education N, Version 1803

Docker desktop: 2.3.0.2 (45183)

Not virtualized

I'm sorry if I'm doing something wrong, and the problem is on my side.

**Comment by mat007** [comment]
Thanks for the report, could you try with 2.3.0.3 and if it’s still happening upload some diagnostics (Troubleshoot window, from the systray menu)?
