### ISSUE TITLE
Mongodb with volume doesn't work (Operation not permitted)

### ISSUE THREAD

**Issue by whitecolor** [docker/for-win#689]
Just run (replace volume with some dir on FS on shared drive):
```
docker run -v /d/Data/test:/data/db mongo
```

```
2017-05-01T09:02:17.311+0000 E STORAGE  [initandlisten] WiredTiger error (1) [1493629337:311829][18:0x7fc0e186ccc0], con
nection: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted
2017-05-01T09:02:17.313+0000 I -        [initandlisten] Assertion: 28595:1: Operation not permitted src/mongo/db/storage
/wiredtiger/wiredtiger_kv_engine.cpp 267
```

Mongo docs says `For example, HGFS and Virtual Box’s shared folders do not support this operation.`
https://docs.mongodb.com/manual/administration/production-notes/#fsync-on-directories

I wonder if it is possible to make work on current docker for windows.

**Comment by friism** [comment]
Docker for Windows volume mounting works over a SMB share. Most like, mongodb doesn't work when trying to write data to a Windows drive mounted over the network because of missing filesystem mapping semantics between Linux and Windows.

I recommend using a Linux-only volume instead that's not mounted from the Windows host.

**Comment by whitecolor** [comment]
Right, but it is not persistent setup even for dev environment, sometimes I do `reset to defaults` (when things go wrong, or just clean everything up. So if I don't use volumes from windows machine, I need more complex workflow to keep everything safe.

> because of missing filesystem mapping semantics between Linux and Windows.

Doesn't docker plan to implemnt something like this?

Or isn't it possible to run on "docker for windows" linux and windows containers at a time, without `swithing`?

**Comment by friism** [comment]
> Doesn't docker plan to implemnt something like this?

No, not right now. You might be able to tweak the mongodb storage engine to work on an SMB share: https://forums.docker.com/t/issues-with-mongo-with-mounted-volume-for-data/15085/4

**Comment by whitecolor** [comment]
No WireTired engine is used by default.

What about my second question:
Isn't it possible to run on "docker for windows" linux and windows containers at a time, without switching?

**Comment by friism** [comment]
@whitecolor no, it's not - you'll have to setup two separate vms (linux and windows) either locally or in the cloud to experiment

**Comment by whitecolor** [comment]
Well I'm now about simple dev workflow.
