### ISSUE TITLE
Failed to reset to default

### ISSUE THREAD

**Issue by agateriver** [docker/for-win#6892]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F2E5D14E-5CEC-4E7A-AEFF-1F2364900772/20200527015723

### Expected behavior
Reset to factory defaults
### Actual behavior
Failed to reset to default
### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. click "Reset to factory defaults"

**Comment by flcdrg** [comment]
Same problem, ID: 43DD85C2-1D3E-4FD5-A411-14CA522211D1/20200603035049
