### ISSUE TITLE
WSL 2: userns-remap not working / daemon.json not picked up

### ISSUE THREAD

**Issue by ugrupp** [docker/for-win#6897]
I have Docker for Desktop running, using WSL2. I now want my containers to have a user namespace remapping as described in https://docs.docker.com/engine/security/userns-remap/

My problem is that I don't know where to put `"userns-remap": "username"`.

I tried:

* Docker Desktop settings -> Docker Engine. This actually makes Docker Desktop crash/not start on "Apply & Restart"
* Inside WSL: `/etc/docker/daemon.json`
* `C:\Program Files\Docker\Docker\resources\linux-daemon-options.json`

But none of this seems to get picked up by the daemon running in WSL, which I think is autostarted by Docker Desktop(?).
For debugging purposes, I installed and ran `dockerd` manually inside WSL, and it picked up `/etc/docker/daemon.json`, also logging that the user mapping is set up.

  - [x] I have tried with the latest version of my channel (**Stable** or Edge)
  - [x] I have uploaded Diagnostics (with `"userns-remap": "username"` set in Docker Desktop Engine settings screeen, which makes the app crash)
  - Diagnostics ID: 7C43D941-532E-4D06-98FE-3E984DACFBCB/20200527093104

### Expected behavior

With `"userns-remap": "user"` set in the correct daemon.json, file ownership (UID and GID) on shared volumes should be remapped from container to linux host.

### Actual behavior

The UID/GID values used in the container get remapped 1:1 into the host space, leading to misaligned file ownership.

### Information

  - Windows Version: Windows 10 2004 (With WSL 2 enabled)
  - Docker Desktop Version: 2.3.0.2 (With WSL 2 enabled)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

**Comment by simonferquel** [comment]
For now we don't support userns-remap. The main reason is that docker desktop runs in its own namespace and does not have information about your own WSL distro usernames / UID / GID and subuid/subgid settings from your distro.
