### ISSUE TITLE
Docker not installed properly on windows server 2016

### ISSUE THREAD

**Issue by sagar1609t** [docker/for-win#6899]
When i run the docker version in power shell , i am getting below issue..can someone help me on this
I tried with the latest version also and still getting the same issue

PS C:\Windows\system32> docker version
Client: Docker Engine - Enterprise
 Version:           18.09.11
 API version:       1.39
 Go version:        go1.12.12
 Git commit:        6112046bc9
 Built:             11/13/2019 07:51:12
 OS/Arch:           windows/amd64
 Experimental:      false
error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect.: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/versio
n: open //./pipe/docker_engine: The system cannot find the file specified.

**Comment by kbhargava505** [comment]
Here is the screen shot
![image](https://user-images.githubusercontent.com/36661656/83030036-0252d700-a051-11ea-91a1-d99223a688b9.png)

**Comment by thaJeztah** [comment]
```
the docker client must be run with elevated privileges 
```

Did you open a privileged shell?

**Comment by sagar1609t** [comment]
Yea it's working now.. thanks for the support
