### ISSUE TITLE
Unable to pull the selenium standalone in windows server 2016

### ISSUE THREAD

**Issue by sagar1609t** [docker/for-win#6900]
Can someone help me on this
-->I installed docker in windows server 2016
--> i tried to pull the selenium standalone chrome, but getting the below error message

![image](https://user-images.githubusercontent.com/66018940/83031595-61651b80-a052-11ea-86b8-2d724c98c72e.png)

**Comment by stephen-turner** [comment]
This issue tracker is for Docker Desktop, not Docker Enterprise on Windows Server. The latter is not even owned by Docker, Inc. any more, and first-line support is provided by Microsoft.

**Comment by sagar1609t** [comment]
@stephen-turner where  we can  find the solution for the above one??
