### ISSUE TITLE
Unable uninstall and reinstall Docker

### ISSUE THREAD

**Issue by c-goes** [docker/for-win#6901]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Uninstall Docker via https://success.docker.com/article/how-to-completely-remove-docker-in-windows-10 completely removes Docker

### Actual behavior

After running the script from https://success.docker.com/article/how-to-completely-remove-docker-in-windows-10 I can neither install Docker nor uninstall it. It's also not functional any more.

### Information

  - Windows Version: Version	10.0.18362 Build 18362
  - Docker Desktop Version:  2.3.0.3 , 2.3.1.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. Install Docker for Windows
  2. Try to uninstall via https://success.docker.com/article/how-to-completely-remove-docker-in-windows-10
  3. Try to install it again from Docker Desktop Installer.exe
  4. Installer reports that Docker is already the newest version
  5. Uninstall also fails

**Comment by matthewbullweb** [comment]
I had this issue after using system restore in windows 10. I had to backup my data and perform a fresh start keeping my data. I feel some sort of removal tool maybe needed (like you used to get with anti virus software).

**Comment by c-goes** [comment]
Unfortunately I have no backup but found a work around: 
1. Install Docker for Windows **Edge channel** (had installed stable first)
2. Uninstall Docker for Windows (Edge) via normal Uninstaller (not the script)
3. Install Docker for Windows (Edge)
4. Uninstall Docker for Windows (Edge)
5. Install Docker for Windows (Stable)

It feels Docker messes too much with Windows settings and internals that are not restored upon uninstalling Docker.
