### ISSUE TITLE
Docker 2.3.0.3 will not start on Windows 10 Pro Insider 19631

### ISSUE THREAD

**Issue by plleg** [docker/for-win#6905]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 2F4E65B5-BC26-4EAB-94A4-E8AFD65D5F42/20200527191027

### Expected behavior
Docker starts

### Actual behavior
Docker does not start

### Information

  - Windows Version: Windows 10 Pro Insider 19631
  - Docker Desktop Version: 2.3.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior
Start Docker Desktop

**Comment by fchazot** [comment]
I have the same issue after I updated, tried to reset but throw an error, tried to reinstall, didn't change anything :-/

**Comment by plleg** [comment]
Right after posting this I surprisingly got Docker to work.

- uninstalled Docker Desktop
- reinstalled Docker Desktop (from fresh download)
  - (it installed version 2.3.1.0. Before the original try it told me 2.3.0.3 was the latest)
- Docker Desktop started up and has been running fine.

**Comment by fchazot** [comment]
Thanbks going to try that. the 3.3.1.0 is an edge version, not a stable one, but if it works, I'll take it :)

**Comment by fchazot** [comment]
@plleg this version works, thanks a lot!
