### ISSUE TITLE
Docker update Failed while removing virtual Ethernet switch

### ISSUE THREAD

**Issue by Nick-Abbott** [docker/for-win#6910]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4DAC7216-58D1-4366-A7DE-3A742ABFE67F/20200527232444

### Expected behavior
Launch docker

### Actual behavior
Docker fails to start

### Information

Docker was working properly for weeks. When I restarted my computer it asked if I would like to update. I clicked yes and it updated. From then on every time I launch docker it says "an error occurred" with a Docker.Core.HttpBadResponseException with message "Failed while removing virtual Ethernet switch. I have tried restarting my computer, resetting to factory, reinstalling docker for windows, and running as administrator but receive the same result.

  - Windows Version: Windows 10 Education 1909 (18363.836)
  - Docker Desktop Version: 2.3.0.3 (45519)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

**Comment by mat007** [comment]
Thanks for the report, do you have anything listed in the registry under `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\vmsmp\parameters\SwitchList`?

**Comment by Nick-Abbott** [comment]
Yes, I have 2 entries. A DockerNAT and a Default Switch with a Container NIC as a child

**Comment by mat007** [comment]
Can you delete the DockerNAT (make a reg backup before 😁) and see if that fixes you issue?

**Comment by Nick-Abbott** [comment]
I had to restart my PC again after deleting it from the registry but now I seem to be up and running! Thanks!
