### ISSUE TITLE
Error response from daemon: open \\.\pipe\docker_engine_linux: The system cannot find the file specified.

### ISSUE THREAD

**Issue by SupJoeeeeeey** [docker/for-win#6912]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 99B7778A-F4C2-452D-A87D-42C120685987/20200528011600

### Expected behavior
Proper information returned with docker cli.

### Actual behavior
Run any docker command in shell will return 
`Error response from daemon: open \\.\pipe\docker_engine_linux: The system cannot find the file specified.`

### Information
  - Windows Version: Win 10 Enterprise 10.0.17763 Build 17763
  - Docker Desktop Version: 2.2.0.5 (43884)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
The problem will just come back after rebooting docker desktop for a while. I have tried the following options with no luck:
* restart docker multiple times
* reinstall docker
* factory settings
* latest and older docker versions

**Comment by SupJoeeeeeey** [comment]
I know this issue is a duplicate but I am just providing my diagnostic logs to provide more context..

**Comment by milindchavan12** [comment]
Did anyone you find solution for this?
