### ISSUE TITLE
after upgrading to latest windows preview build, Docker Desktop crashes on launch

### ISSUE THREAD

**Issue by dpicts** [docker/for-win#6913]
- [ Y] I have tried with the latest version of my channel (Stable or Edge)
  - [ Y] I have uploaded Diagnostics
  - Diagnostics ID: 72CFF118-0494-421C-A6E4-F0C29967D2BF/20200528015924

### Information

  - Windows Version: 10.0.19041 Build 19041
  - Docker Desktop Version: 2.3.1.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: NO

### Steps to reproduce the behavior
-Upgraded windows to the latest Insider build 
-enabled WSL 2... 
-opened docker desktop and switched to WSL 2 mode...
- Docker Desktop crashes.

Attempted fixes: 
- Reset to Factory Defaults (I had no docker images anyways), but that had no effect.
- Uninstall Docker Desktop and Reinstall... still crashes

**Comment by simonferquel** [comment]
For some reason, the diagnostic did not upload correctly. Can you upload a new one ?

**Comment by dpicts** [comment]
new Diagnostics ID: 72CFF118-0494-421C-A6E4-F0C29967D2BF/20200528151530

**Comment by simonferquel** [comment]
From your logs, I see:
`[11:15:20.196][WSL2Provisioning  ][Error  ] Failed to set version to docker-desktop: exit code: -1
 stdout: The Windows Subsystem for Linux instance has terminated.`

I suppose that it is because wsl2 itself fails.
Can you try to restart LxssManager service and Docker Desktop ?

**Comment by dpicts** [comment]
That didn't work... I tried installing Ubuntu (from the windows store) and the WSL keeps terminating on it as well, so it looks like there is something wrong with the WSL installed on my machine and not a Docker issue.
