### ISSUE TITLE
Cannot enable Hyper-V service - Docker Desktop on Windows

### ISSUE THREAD

**Issue by nahooshmandlik** [docker/for-win#6916]
Docker Desktop was installed on Windows 10. It worked for couple of days. Was working with a container and the machine went in hibernate mode. When taken out of hibernation, it was not responding, hence force shutdown. After that Docker Desktop never starts, gives "Cannot enable Hyper-V service". Tried uninstall and re-installing. Tried all remedies after doing google search. Tried Edge versions and again installed stable versions. Nothing has resolved the situation. Waiting for help.

**Comment by tolarovic** [comment]
Did you change BIOS settings for Virtualisation?

**Comment by nahooshmandlik** [comment]
Hi Peter,

Yes, I did change the BIOS settings for Virtualisation. I did mention that
the Docker Desktop was working fine for couple of days. It only stopped
after a situation. The situation is as below.

1. Was working with a container, and the system went into hibernation.
2. After some time, when the system woke up (due to key press), all the
applications which were running earlier (including Docker Desktop) were in
"Not Responding" status.
3. I forced shutdown my laptop, and rebooted the laptop.
4. After which the Docker Desktop stopped working.
5. I then removed and installed the Docker Desktop again, but no luck.
6. I tried edge and stable releases both, but no luck.
7. I tried all the steps I could find doing a web search to fix the
problem, but no luck.
8. One change I noticed during all the subsequent re-installation steps,
the installer never asked me to re-boot the laptop once the installation
was done. It did ask only when I fresh install the Docker Desktop.

Waiting to hear from you.

Thanks and Regards
Nahoosh

**Comment by mat007** [comment]
@nahooshmandlik have you tried removing Hyper-V, rebooting, then adding it back (or re-installing Docker Desktop which will do it for you)?

**Comment by nahooshmandlik** [comment]
Yes I did re-install Docker Desktop couple of times. Even today
after receiving this email I attempted one more time. The installation went
till end with no error. The installer did not prompt me to reboot the
laptop.

When I invoked the Docker Desktop (by clicking the icon on the desktop), it
gave error. The error snapshot is as attached.

[image: image.png]
Thanks and Regards
Nahoosh

**Comment by mat007** [comment]
The problem is more likely to come from Hyper-V, hence my suggestion to uninstall it, reboot, then install it again.

![image](https://user-images.githubusercontent.com/2386884/83517271-e334c900-a4d8-11ea-95f3-f67a0543c279.png)
