### ISSUE TITLE
Docker doesn't run on the latest version of Windows 10 Home

### ISSUE THREAD

**Issue by afriron** [docker/for-win#6921]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F960CB3F-E638-4CB6-A712-8D05CBF086CD/20200528074614

### Expected behavior
After loading, Docker should start.

### Actual behavior
After loading Docker Desktop, I see a red Docker icon in the tray and the message " Docker Desktop failed to stop".

Command `docker` run -dp 80:80 docker/getting-started` fails with an error 

> C:\Program Files\Docker\Docker\resources\bin\docker.exe: error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/create: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

### Information
  - Windows Version: 2004 (build 19041.264)
  - Docker Desktop Version: 2.3.0.3 (45519)
  - I running inside a virtualized Windows WSL2

### Steps to reproduce the behavior

  1. Enable WSL2.
  2. Install Docker Desktop.
  3. Run Docker Desktop.

**Comment by MelloTonio** [comment]
Same here man, been trying hours and hours and nothing

**Comment by simonferquel** [comment]
I see that somehow WSL 2 fails to even do simple actions like terminating a distro with some strange output: [10:28:10.975][WSL2Provisioning  ][Error  ] Failed to terminate distro: exit code: -1
 stdout: 5 ACI5AB2C5B @0A?@545;5=8O A C:070==K< 8<5=5<.

If you are in a virtualized Windows, can you check that nested virtualization is enabled on the Host ? (it is required for WSL 2 to work). Also can you try to use wsl2 distro and see what happens (don't forget to upgrade distro from wsl 1 to wsl 2 (with `wsl --set-version <distro-name> 2>`)

**Comment by afriron** [comment]
I run Docker on a physical computer with virtualization enabled. Wsl2 is used (my version of Windows Home does not support Hyper V).
Here is the output of the `wsl -l -v` command:
  NAME              STATE           VERSION
* Ubuntu            Stopped         2
  docker-desktop    Installing      2

Specified that WSL2 is used.
Ubuntu in WSL2 works fine as far as I can tell.

**Comment by afriron** [comment]
I just noticed that Docker has status: installing. Maybe that's the problem?
