### ISSUE TITLE
`block in materialize': Could not find remotipart-1.4.4 in any of the sources

### ISSUE THREAD

**Issue by pornsukon** [docker/for-win#6923]
/usr/local/bundle/gems/bundler-1.9.0/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find remotipart-1.4.4 in any of the sources (Bundler::GemNotFound)
	from /usr/local/bundle/gems/bundler-1.9.0/lib/bundler/spec_set.rb:85:in `map!'
	from /usr/local/bundle/gems/bundler-1.9.0/lib/bundler/spec_set.rb:85:in `materialize'
	from /usr/local/bundle/gems/bundler-1.9.0/lib/bundler/definition.rb:132:in `specs'
	from /usr/local/bundle/gems/bundler-1.9.0/lib/bundler/definition.rb:177:in `specs_for'
	from /usr/local/bundle/gems/bundler-1.9.0/lib/bundler/definition.rb:166:in `requested_specs'
	from /usr/local/bundle/gems/bundler-1.9.0/lib/bundler/environment.rb:18:in `requested_specs'
	from /usr/local/bundle/gems/bundler-1.9.0/lib/bundler/runtime.rb:13:in `setup'
	from /usr/local/bundle/gems/bundler-1.9.0/lib/bundler.rb:122:in `setup'
	from /usr/local/bundle/gems/bundler-1.9.0/lib/bundler/setup.rb:18:in `<top (required)>'
	from /usr/local/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
	from /usr/local/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
	from /usr/local/lib/ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
	from /usr/local/bundle/bin/rails:14:in `<main>'

**Comment by mat007** [comment]
This doesn’t look like a problem with Docker Desktop but with rubygems, closing.

**Comment by pornsukon** [comment]
Thanks, I can solve it
