### ISSUE TITLE
Failed to set version to docker-desktop: exit code: -1

### ISSUE THREAD

**Issue by samerdokas** [docker/for-win#6925]
- [x] I have tried with the latest version of my channel (Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 5945B336-1E91-4187-A6B6-250D338CDF1C/20200528120056

### Expected behavior
Once Docker Desktop is started, it does not fail and `wsl -l -v` shows both `docker-desktop` and `docker-desktop-data` as `Running`.

### Actual behavior
Once Docker Desktop is started, it immediately fails with
```
System.InvalidOperationException:
Failed to set version to docker-desktop: exit code: -1
 stdout: The attempted operation is not supported for the type of object referenced.
```
Reseting to factory defaults, uninstalling/reinstalling, wiping out the %APPDATA%/Docker folder, installing the Edge version does not help. I have always rebooted after each uninstallation.

Observing `wsl -l -v` during docker startup shows that `docker-desktop` successfully installs and is "Running" for around a second, after which it is "Stopped" and the crash diagnostics dialog is shown.
Once the dialog is closed, `wsl -l -v` does not list anything. `docker-desktop-data` is never installed.

### Information
It is 100% reproducible and applies to the WSL2 backend. Both 2.3.0.3 and 2.3.1 are affected.

- Windows version: 2004 (19041.264)
- Docker Desktop Version: 2.3.1
- Virtualized Windows: No

### Steps to reproduce the behavior
  1. Install Docker Desktop with WSL 2 checkbox checked
  2. Run Docker Desktop

**Comment by StefanScherer** [comment]
That sounds like this error with WSL 2: https://github.com/microsoft/WSL/issues/4177 - and maybe this comment https://github.com/microsoft/WSL/issues/4177#issuecomment-627935965 

Are you able to run a normal Ubuntu distro as WSL 2?

**Comment by samerdokas** [comment]
Hi Stefan,

it does seem to be the case. The NoLsp workaround does work, which would mean it is not related to Docker. My bad.

**Comment by StefanScherer** [comment]
Thanks for the feedback @samerdokas. I'm glad it works now. Enjoy!

**Comment by ChenYi1125** [comment]
System.InvalidOperationException:
Failed to set version to docker-desktop: exit code: -1
 stdout: �S��v�[a�{|�W
N/ec\Ջ�v�d\O0

F8E78EBB-2CD2-46C9-9AA5-68E1C8D07AC2/20200608030610
