### ISSUE TITLE
Docker hangs on restart, then eventually crashes

### ISSUE THREAD

**Issue by SamuelCook** [docker/for-win#6929]
- [x] I have tried with the latest version of my channel (Stable)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 9B7B59D1-E489-4702-A623-A43152624C9A/20200528005354

### Expected behavior
Docker starts up

### Actual behavior
Docker hangs on either 'updating' or 'starting' for a very long time (left overnight) and then crashes

### Information
  - Is it reproducible? Yes, occurs every time Docker is started
  - Is the problem new? Yes, started occurring with latest Windows/latest Docker/WSL2 update
  - Windows Version: Windows 10 build 2004
  - Docker Desktop Version: 2.3.0.3 stable build 45519
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

  1. Install Docker
  2. Start Docker
  3. Restart Docker

**Comment by SamuelCook** [comment]
This appears to be the same issue as #6961. I uninstalled and reinstalled Docker Desktop, did not expose port 2375, and the crash does not occur.

I currently rely on connecting to the Docker port on 2375 from other docker clients on my local network. For now I will connect over SSH, which works just fine.

**Comment by djs55** [comment]
I believe this issue has been fixed in the latest [stable 2.4.0.0](https://desktop.docker.com/win/stable/48506/Docker%20Desktop%20Installer.exe).
