### ISSUE TITLE
nobrl flag on volume mounts causes silent errors

### ISSUE THREAD

**Issue by lokkju** [docker/for-win#694]
in #11, the nobrl flag was added to the mount options, causing lock requests to not be send to the CIFS server.  This causes silent corruption in sqlite when using journaling.  While nobrl may be a valid solution in some cases, having it as a non-documented, non-configurable, mount flag provides the illusion of locking working, without any warning to the user that their applications could silently fail if they need file locking, mmap, etc.

I'm not sure what the solution is, other than perhaps *not* using CIFS for access to the underlying file system.  Has there been any consideration of a direct-access local volume driver?

**Comment by friism** [comment]
We don't have a viable alternative to CIFS at the moment even though it has a number of drawbacks.

Docker for Windows is a development tool. Is the current setting impeding using Docker for Windows for development purposes?

**Comment by lokkju** [comment]
At the moment, it is blocking me from using sqlite db files reliably in my host mounted config folders; essentially the nobrl flag addition in #11 hid the problem instead of solving it.  Since I often use sqlite in development, it's a real problem.  Each time a container doesn't exit cleanly, or two process attempt to use the same file, the risk of corruption occurs.  At the very least, it should be *very* well documented that any functionality that relies on file locking will be broken on host volumes.  Preferably, it should be a configurable option on a per container basis.

Of course, the best would be not using CIFS, but I understand that is an large undertaking.

**Comment by friism** [comment]
I agree that it should be documented, cc @londoncalling.

@lokkju can you use a named volume? `docker volume create`. The would be Linux-only.

Michael

**Comment by lokkju** [comment]
Oh, interesting; so volume create, creates a location in the MobyLinuxVM?  That might work.  Is there any easy way to access that from the host, as well?

**Comment by friism** [comment]
No, those Linux volumes are not easily accessible from the Windows host.

**Comment by Andy2244** [comment]
I suspect my #1385 has a similar problem with sqlite+wal under headphones, but with the new lcow. What is lcow using internally, is it also cifs?
The bigger problem is that even using volumes + lcow results in i/o errors, so there is no fix atm.

**Comment by Elehiggle** [comment]
It took me 4 days to come here and figure out what is causing issues with my containers. You can use SMB with vers=1.0, that will work with SQlite databases. But unfortunately it has many other drawbacks and issues (POSIX leaks, I guess due to locking issues as well). I'll use SMBv3 now with the nobrl flag, but will create an extra mount just for SickRage. With backups it should be fine.
