### ISSUE TITLE
Require VirtualMachinePlatform but I have wsl2

### ISSUE THREAD

**Issue by heckad** [docker/for-win#6951]
After update windows 10 and install wsl2 I tried to install docker for windows and got the error:
`call to whvsetuppartition failed error success last 0xc000000d 87 verr nem vm create failed` in Virtualbox. The reason for this error is that VirtualMachinePlatform is enabled. After off this feature, I got the new error from docker desktop: 

```
WSL2 is not installed

Install WSL using this powershell script (in an administrative powershell) and restart your computer before using Docker Desktop:

Enable-WindowsOptionalFeature -Online -FeatureName $("VirtualMachinePlatform", "Microsoft-Windows-Subsystem-Linux")
```

This error proposes to tern on VirtualMachinePlatform and seems because this option off, docker desktop shows error. Seems this is a bug in startup check. In case when wsl2 supported the need to check on  Windows-Subsystem-Linux only.

**Comment by mat007** [comment]
WSL 2 does indeed require the Virtual Machine Platform feature, see https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq#does-wsl-2-use-hyper-v-will-it-be-available-on-windows-10-home
