### ISSUE TITLE
unable to resolve docker endpoint: open .docker\machine\machines\default\ca.pem: The system cannot find the path specified DockerDesktop windows

### ISSUE THREAD

**Issue by prabhatsingh0087** [docker/for-win#6957]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: EC1C7DAF-3A7B-48B2-9760-A248F42306E9/20200529140441

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Manvityagi** [comment]
https://github.com/docker/for-win/issues/7629

Duplicate for this one.
