### ISSUE TITLE
dOCKER fAILED tO sTOP -- FROM TASKBAR ICON

### ISSUE THREAD

**Issue by freebrew** [docker/for-win#6970]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by freebrew** [comment]
HYPER-V is the issue. messing with MEMU/VirtualBox

**Comment by stephen-turner** [comment]
There is not enough info in this ticket to diagnose the problem. However, it is true that VirtualBox won't run in the presence of Hyper-V. This is an issue with VirtualBox, not Docker Desktop.

**Comment by freebrew** [comment]
but why does Hyper-V have to lockdown virtualization? why can they not share like good boys and girls?
