### ISSUE TITLE
Docker Desktop fails to start with WSL2 based engine enabled

### ISSUE THREAD

**Issue by ErikGrimes** [docker/for-win#6971]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D6C760E2-E400-4DBD-BF7F-C51A09032AA0/20200530010012

### Expected behavior
Docker Desktop starts

### Actual behavior
Docker Desktop fails to start

### Information

This problem started after the 5 2020 Windows update.
  - Windows Version: Microsoft Windows Pro 10.0.19041 Build 19041
  - Docker Desktop Version: 2.3.0.3 stable
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

  1. Start Docker Desktop

**Comment by StefanScherer** [comment]
In the diagnostics I can see an error "[WSL2Provisioning  ][Error  ] Failed to terminate distro: exit code: -1 stdout: There is no distribution with the supplied name."

Could you run the following command in a PowerShell terminal and paste the output here?

```
wsl -l -v
```

If there is a `docker-desktop` distro, try the following:

1. Stop Docker Desktop
2. In a PowerShell terminal run the following command: `wsl --unregister docker-desktop`
3. Start Docker Desktop again, it should create the distro again.

**Comment by ErikGrimes** [comment]
I followed the instructions and everything is working fine now. Please
close the issue. Thanks.

**Comment by miking-the-viking** [comment]
Thanks @StefanScherer !

**Comment by mattroark** [comment]
Thanks @StefanScherer - that worked perfectly. For reference, `docker-desktop` was stuck in an `Installing` state.
```
C:\Users\roark>wsl -l -v
  NAME              STATE           VERSION
  docker-desktop    Installing      2
```

It oddly couldn't find it when unregistering, but, worked successfully, in any case.

```
C:\Users\roark>wsl --unregister docker-desktop
Unregistering...
The system cannot find the path specified.

C:\Users\roark>wsl -l -v
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
```

Docker was then successfully able to start with both `docker-desktop` entries showing in `Running` state.
```
C:\Users\roark>wsl -l -v
  NAME                   STATE           VERSION
* docker-desktop         Running         2
  docker-desktop-data    Running         2
```

**Comment by adamskwersky** [comment]
Thanks, I had this very same problem! This might be good to add to the troubleshooting.

**Comment by LotusGeek** [comment]
I tried the suggested fix, and it didn't work for me. I've created a ticket for it. #7760

**Comment by evaneaston** [comment]
After reinstalling edge (2.3.3.2) ,I also tried the workaround of deregistering the docker-desktop distribution.  Just as @LotusGeek reported, it recreates it the distribution and docker fails to start.  I'll add my diagnostics to #7760.

**Comment by rajesh1420621** [comment]
> In the diagnostics I can see an error "[WSL2Provisioning ][Error ] Failed to terminate distro: exit code: -1 stdout: There is no distribution with the supplied name."
> 
> Could you run the following command in a PowerShell terminal and paste the output here?
> 
> ```
> wsl -l -v
> ```
> 
> If there is a `docker-desktop` distro, try the following:
> 
> 1. Stop Docker Desktop
> 2. In a PowerShell terminal run the following command: `wsl --unregister docker-desktop`
> 3. Start Docker Desktop again, it should create the distro again.
![image](https://user-images.githubusercontent.com/63142287/88456255-de1d4600-ce99-11ea-83cd-f9cecad5b149.png)


I ran the command wsl.exe --unregister docker-desktop and it is running since long time with the message Unregistering...
