### ISSUE TITLE
Unable to mount host folder after update to latest version

### ISSUE THREAD

**Issue by mshgh** [docker/for-win#6980]
I am using this technique (see [wiki](https://en.wikipedia.org/wiki/SUBST#Persisting_across_reboots)) to "create" drive D: on my single-volume Windows 10 NB. It means there exists disk _D:_ on my computer, but it is actually pointing to _C:\DISK_D_. After upgrade to the latest Docker Desktop Community 2.3.0.3 (not sure from what version) I am no longer able to mount host folders from disk _D:_ while there is no problem to mount folders from disk _C:_

Not sure if this is related, but `docker run -it --rm -v /host_mnt/:/xyz alpine:3.11 ls -la /xyz` shows only folder `c` to me.

**Comment by mat007** [comment]
This looks like the same as #5792?

**Comment by mshgh** [comment]
I wouldn't be surprised if the root cause is the same. This is different use case, though.
It would be great if addressed both permanent subst and folder mounted partition is part of acceptance criteria.

The other issue is more elaborated. I'll add my use case there and we can close this one.

**Comment by mat007** [comment]
Thanks, closing this one.
