### ISSUE TITLE
Docker container port not accessible on Windows 10

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [docker/for-win#6981]
Port mapping is not working with Docker version 19.03.8, build afacb8b
Neither localhost:8000 nor 0.0.0.0:8000 works
Diagnostics-id: 95B665D7-BB3C-4E58-A43F-DCC26BAE0B5D/20200531190852

**Comment by mat007** [comment]
Can you explain a bit more what you do?

**Comment by Karlheinzniebuhr** [comment]
Sure, so I started a docker-compose mapping port 8000:8000.
The application started successfully, but from the host, I can't connect to port 8000. The port mapping is not working for some reason

**Comment by mat007** [comment]
Your logs are full of `ICMP: destination unreachable from 192.168.65.3`, do you happen to have blocked it? Could you try maybe after deactivating your firewall, just for testing if it works?
