### ISSUE TITLE
Docket stop to working on WSL 2

### ISSUE THREAD

**Issue by Nervado** [docker/for-win#6983]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 1A057ECB-FE15-46EF-82D4-278A4B9A3041/20200531220052

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by simonferquel** [comment]
You seem to be running windows insider build 19631. I think it is the one where they basically broke Windows file access from WSL 2. I think the latest insider fast unbroke it.
