### ISSUE TITLE
Windows Docker Issue

### ISSUE THREAD

**Issue by abhinavkabra** [docker/for-win#6984]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by abhinavkabra** [comment]
I have tried with and without WSL but not working

**Comment by stephen-turner** [comment]
There is not enough info in this ticket to debug the issue, closing.
