### ISSUE TITLE
Cannot start Docker Desktop after upgrading to Windows 2004 & updating to WSL2

### ISSUE THREAD

**Issue by yehoshuadimarsky** [docker/for-win#6985]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `7D9F21D8-FEFB-4ACD-8C3A-9962B359DC1F/20200531235618`

### Expected behavior
Docker works.

### Actual behavior
It doesn't. It when the service tries to start, it crashes with an error:
![image](https://user-images.githubusercontent.com/24758845/83365891-971f4280-a379-11ea-9cde-913fbc7b2891.png)

Full diagnostics have been uploaded, see above

### Information

  See the diagnostics data
#### Situation where it was working
* Windows 10 Pro 1909, latest updates
* Docker 2.2.* because the 2.3.* was screwing up the filesystem, as per https://github.com/docker/for-win/issues/6634#issuecomment-627542221
* WSL (not WSL2) installed, not really used, only 1 distro installed
#### Now it's not
* Upgraded to Win 10 Pro 2004
* Installed/Updated to WSL2
* Docker 2.2.* crashed. 
* Upgraded to 2.3.*, still crashed. 
* Uninstalled, reinstalled, still crashed.
* Send help please

**Comment by mbobka** [comment]
Try to disable in Windows Security -> Reputation-based protection:
![image](https://user-images.githubusercontent.com/10296334/83478443-7ef51380-a49e-11ea-93f8-23bc54df0a7f.png)

**Comment by simonferquel** [comment]
C:\Users\ydima\AppData\Local\Docker\wsl\distro seem to have some attributes set preventing WSL 2 to deploy a distro in it.
Can you check this directory attributes, especially unset encryption and compression ?

**Comment by yehoshuadimarsky** [comment]
> Try to disable in Windows Security -> Reputation-based protection:
> ![image](https://user-images.githubusercontent.com/10296334/83478443-7ef51380-a49e-11ea-93f8-23bc54df0a7f.png)

Was already set to off by my admin:
![image](https://user-images.githubusercontent.com/24758845/83591250-857a9e00-a525-11ea-90c9-1fbc77e56c78.png)

So that doesn't seem to be the issue

**Comment by yehoshuadimarsky** [comment]
> C:\Users\ydima\AppData\Local\Docker\wsl\distro seem to have some attributes set preventing WSL 2 to deploy a distro in it.
> Can you check this directory attributes, especially unset encryption and compression ?

Looks like everything is set to normal, see screenshot below. As a precaution, I unencrypted my entire hard drive by removing BitLocker, didn't help. Can't figure this out.

![image](https://user-images.githubusercontent.com/24758845/83591331-b22eb580-a525-11ea-8560-256ab3d900ba.png)

**Comment by hoan-cosmos** [comment]
I've just updated to Windows 10 2004 & updated to WSL2 & installed docker stable lasted version today.
At first, I had the same problem with @yehoshuadimarsky, then I disabled and re-enabled all the options in Windows Security -> Reputation-based protection and now Docker worked.
![image](https://user-images.githubusercontent.com/29880544/83597190-de335080-a590-11ea-8ef5-9bffa45fea68.png)

**Comment by yehoshuadimarsky** [comment]
Seems to be a deeper issue caused by my Windows 2004 upgrade, can't even start WSL distros anymore, same error: 

![image](https://user-images.githubusercontent.com/24758845/83981174-98a4b980-a8e9-11ea-898e-022297a75536.png)

So guessing not a Docker specific problem anymore, will close for now
