### ISSUE TITLE
WSL2 Windows 10 Enterprise Build 19635 release 200522-1435 Don't Work

### ISSUE THREAD

**Issue by supermavster** [docker/for-win#6987]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A3FC1E5B-48B2-4EBE-831B-7C53C22E3B5A/20200601041622

### Information

  - Windows Version: Microsoft Windows 10 Enterprise - 10.0.19635 N/A Build 19635
  - Docker Desktop Version: 19.03.8, build afacb8b
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Virtualized Windows (WSL Ubuntu 2004.2020.424.0)

### Steps to reproduce the behavior

  1. Install WSL Windows Store
  2. Install Docker (Edge or common) same error
  3. Follow the spets https://docs.microsoft.com/en-us/windows/wsl/install-win10
  4. Change set WSL 2 as your default version.
  5. Active WSL 2 in docker and ERROR!! check the Diagnostics ID: A3FC1E5B-48B2-4EBE-831B-7C53C22E3B5A/20200601041622

**Comment by simonferquel** [comment]
`stat /mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-wsl-cli.iso: no such file or directory`: I think Microsoft introduced a bug in a recent Insider fast build where some windows files can't be accessed from wsl2 distros. It seems you are falling in this case (can you have a look if under a WSL 2 distro you can access your Windows files ?)

**Comment by supermavster** [comment]
Hi, it is curious sometimes it does not recognize certain files or memory, therefore before starting tasks I mount the disk (whatever it is) and I continue with my work.

I use the following commands
`
# created as su to match /mnt/c
sudo mkdir -p /c 
# update /etc/fstab; requires su
sudo sh -c "echo '/mnt/c /c none bind' >> /etc/fstab"
sudo mount -t drvfs C: /mnt/c
# reload fstab; requires su
sudo mount -a
`

**Comment by supermavster** [comment]
That issues is close: The new update of Docker and Windows with WSL2 Fix the problem, thank you.
