### ISSUE TITLE
port forwarding / listening is not stable.  Would like to know why?

### ISSUE THREAD

**Issue by devtrichy** [docker/for-win#6988]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by devtrichy** [comment]
Port listening is not stable.

**Comment by stephen-turner** [comment]
There is not enough info in this ticket to understand what the problem is or how to diagnose it, closing.
