### ISSUE TITLE
Can not use Kitematic with Docker for Windows

### ISSUE THREAD

**Issue by ahaak** [docker/for-win#7]
### Expected behavior
Using/connect Kitematic to run Docker containers.

### Actual behavior
When opening Kitematic an error occurs at 99% of the initial setup. Error message: connect TIMED OUT 198.105.244.23:2375.
### Information

  - Diagnostic ID: 3D05AAEF-630B-4F46-A82E-D9A6415A59F9/2016-07-29_09-10-02
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - Windows 10, Docker  ver: 1.12.0-beta21 (build: 5971) 5b59d37

### Steps to reproduce the behavior

  1. Docker running.
  2. Start Kitematic. (e.g. right click on Docker in system tray & open Kitematic)

**Comment by dgageot** [comment]
Hi @ahaak, thanks for the report. Can you try to install a more recent version of Kitematic? Old versions are no longer compatible witch recent versions of Docker for Windows.
The latest version can be found here: https://github.com/docker/kitematic/releases/tag/v0.12.0

**Comment by dgageot** [comment]
Closing. Checking the version of Kitematic was added to master branch
