### ISSUE TITLE
Crash when start

### ISSUE THREAD

**Issue by semmaxim** [docker/for-win#7005]
- [V] I have tried with the latest version of my channel (Stable or Edge)
  - [V] I have uploaded Diagnostics
  - Diagnostics ID: 332F539B-16FC-410B-8C9A-B7A2D89D0431/20200602071156

### Expected behavior
Working
### Actual behavior
Crash
### Information
I try to reset settings and reinstall docker desktop - nothing change.
System.InvalidOperationException:
Failed to set version to docker-desktop: exit code: -1
 stdout: 5?>445@68205<K5 
 stderr: 
   в Docker.Core.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) в C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\WslCommand.cs:строка 119
   в Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__6.MoveNext() в C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:строка 48
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__23.MoveNext() в C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:строка 91
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() в C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:строка 29
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() в C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:строка 67
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() в C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:строка 92

  - Windows Version: Microsoft Windows [Version 10.0.19041.264]
  - Docker Desktop Version: 2.3.0.3 (45519)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: none

### Steps to reproduce the behavior

Update windows to 2004 version.
Agree with Docker to enable WSL2.

**Comment by ldsad7** [comment]
Any solution?
