### ISSUE TITLE
Docker cannot start after upgrade win10 1909 to win10 2004

### ISSUE THREAD

**Issue by mmyydd** [docker/for-win#7010]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:9461C80B-4838-479C-B2E8-173162D3DEA5/20200602081206

### Information

  - Windows Version: win10 19041.264
  - Docker Desktop Version: 2.3.1.0 (45408)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by senseysensor** [comment]
Same here.
9B3176C1-E2DA-4D6D-BD35-6FFE3C3511E3/20200602181620
