### ISSUE TITLE
Choosing WSL 2 backend instead of Hyper-V without Hyper-V installed

### ISSUE THREAD

**Issue by Albert221** [docker/for-win#7012]
Hi! I just updated Docker and I want to use WSL 2. But after the update I clicked on 'Not now' when it prompted me whether I want to use WSL 2. Now I can't do anything, cuz settings with enabling WSL 2 are in Docker Desktop, but when I open Docker Desktop I just get the error.

![image](https://user-images.githubusercontent.com/4085280/83503112-e45afb80-a4c2-11ea-8529-ce526fea1030.png)

Is there a way I can enable WSL 2 through CLI or some configuration file? I don't want to install Hyper-V just for that.

**Comment by mat007** [comment]
You can change the `"wslEngineEnabled"` setting in `%APPDATA%\Docker\settings.json`.

**Comment by Albert221** [comment]
Thanks! It would be awesome if this was mentioned in https://docs.docker.com/docker-for-windows/wsl/
