### ISSUE TITLE
There are no up to date installer for windows server

### ISSUE THREAD

**Issue by isanych** [docker/for-win#7014]
Currently there is no way to install up to date version of docker on semi annual channel of Windows Server (Server 2004, Server 1909 etc) - there is no GUI there and often there is no virtualization support, but windows containers with isolation process working fine there.
Currently in order to get up to date docker on server I'm installing docker ee 19.03.5 (https://docs.mirantis.com/docker-enterprise/v3.0/dockeree-products/docker-engine-enterprise/dee-windows.html) - latest version installing at server without hassle, then installing docker for windows on separate windows 10 machine, then replace binaries on server.

Can we have up to date docker ce installation for windows server?

**Comment by stephen-turner** [comment]
This bug tracker is for Docker Desktop, but I think I can answer your question.

Unfortunately we don't have CE for Windows Server, and haven't had for many years. There is not really any need as EE Engine is free with a Windows Server licence. But as you know, Mirantis now own Docker Enterprise. I don't know their plans with respect to taking the latest version and you will need to ask them.

Sorry, I realise that's not very helpful.
