### ISSUE TITLE
Docker doesn't start on win10 pro

### ISSUE THREAD

**Issue by maksl** [docker/for-win#702]
### Expected behavior

Docker for Windows will start and Docker GUI will be available.

### Actual behavior

Docker for Windows is starting and after some time show modal with:
An error occured.
Hardware assisted virtualization and data execution protection must be enabled in the BIOS. See https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization-must-be-enabled

### Information

  - Diagnostic ID: 6F0B4E82-9252-4EBB-905A-FED782D10F55/2017-05-04_02-40-37
  - host distribution and version
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.15063 N/A Build 15063
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Windows User

System Manufacturer:       Gigabyte Technology Co., Ltd.
System Model:              P35-DS3P
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 23 Stepping 10 GenuineIntel ~3333 Mhz

Total Physical Memory:     8 190 MB
Available Physical Memory: 5 423 MB
Virtual Memory: Max Size:  13 310 MB
Virtual Memory: Available: 10 214 MB
Virtual Memory: In Use:    3 096 MB

Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: No
                           Data Execution Prevention Available: Yes

### Steps to reproduce the behavior

  1. Install Docker for Windows.
  2. Run it. Or start Windows, log on and wait, wile Docker for Windows will try to start.

[log.txt](https://github.com/docker/for-win/files/974967/log.txt)
[log.79.txt](https://github.com/docker/for-win/files/974980/log.79.txt)
[DebugInfo-2017-05-04_02-40-37.txt](https://github.com/docker/for-win/files/974975/DebugInfo-2017-05-04_02-40-37.txt)

**Comment by friism** [comment]
Yeah, I don't think it works without SLAT (Second Level Address Translation). We have an issue tracking work to check for that at install.
