### ISSUE TITLE
Docker desktop for windows 2.3.0.3 breaks MariaDB alter table again

### ISSUE THREAD

**Issue by Daemach** [docker/for-win#7024]
The problem mentioned in https://github.com/docker/for-win/issues/5604 is happening now in 2.3.0.3.  I am using a bound volume.  Alter table to add columns crashes with this error:

Error on rename of './coldbox/#sql-alter-1-b' to './coldbox/users' (errno: 16 "Device or resource busy")

**Comment by mat007** [comment]
Could you tell us a bit more about how you run this? A compose file maybe?

**Comment by Daemach** [comment]
version: '3.6'
# if no version is specificed then v1 is assumed. Recommend v2 minimum
volumes:
  sql-data:
networks:
  IPCDNet:

services:
  mysql:
    image: mariadb:10.5
    container_name: ipcd_dbase
    environment:
      MYSQL_ROOT_PASSWORD: '2h2=he2+E'
    volumes:
      - type: bind
        source: ./data
        target: /var/lib/mysql
      # - type: bind
      #   source: ./database/backups
      #   target: /var/opt/mssql/backups
    ports:
      - 3306:3306
    networks:
      - IPCDNet
    restart: always
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    networks:
      - IPCDNet

**Comment by Daemach** [comment]
Can I get you more information on this?  I'm about to give up on docker and just install it locally.  Every time I try to add or rename a column the database has to be dropped and recreated.

**Comment by Daemach** [comment]
Error on rename of './coldbox/#sql-alter-1-44' to './coldbox/users' (errno: 16 "Device or resource busy")

**Comment by mat007** [comment]
Running compose with the compose file you provided seems to be working fine for me, do I need to do something else to trigger the issue?

**Comment by Daemach** [comment]
Renaming columns or tables triggers it, but it's semi-random.

**Comment by L1yp** [comment]
My docker works the same way on wsl2., docker cp cannot manipulate files in containers. 

For example: 
docker cp nginx.conf nginx-web:/etc/nginx/nginx.conf
> Error response from daemon: Error processing tar file (exit status 1): unlinkat / etc/nginx/nginx.conf: device or resource busy
docker exec -it nginx-web rm -f /etc/nginx/nginx.conf
> rm: cannot remove '/etc/nginx/nginx.conf': Device or resource busy
