### ISSUE TITLE
Problem on start in Windows 10

### ISSUE THREAD

**Issue by wmenezes2020** [docker/for-win#7037]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by senseysensor** [comment]
9B3176C1-E2DA-4D6D-BD35-6FFE3C3511E3/20200603063310
