### ISSUE TITLE
WSL2 integration not working after enabling

### ISSUE THREAD

**Issue by mchobbylong** [docker/for-win#7039]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `B42B54C8-4B54-4F35-B87C-9D27222F0C9C/20200603141639`

### Expected behavior

The `docker` command in my WSL2 Ubuntu distro should work.

### Actual behavior

Type `docker` into the shell, then get the `not found` error:
```
The command 'docker' could not be found in this WSL 2 distro.
We recommend to activate the WSL integration in Docker Desktop settings.

See https://docs.docker.com/docker-for-windows/wsl/ for details.
```

### Information

  - Windows Version: `10.0.19041.264`
  - Docker Desktop Version: `2.3.0.3 (Stable)`
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Install Docker Desktop via the official exe installer
  2. Check that `Enable integration with my default WSL distro` switch is checked
  3. Open a Windows Terminal shell, open a tab for WSL2 Ubuntu-18.04 shell, and type `docker`.

**Comment by StefanScherer** [comment]
When you run `docker` in a distro where the integration isn‘t fully finished the fallback script is found in PATH that gives you this message. 

Once the integration is finished if you still see this message please run `hash -r` in Ubuntu. Afterwards the docker binary is called. 

This also can happen directly after logging in to Windows and open the Ubuntu terminal before Docker Desktop has started.

**Comment by mchobbylong** [comment]
@StefanScherer Thanks for your quick response.

That is not the case I am experiencing since I am sure that Docker Desktop itself is fully started before I enter the WSL2 shell. In fact, executing `hash -r` does not solve my problem.

However, one thing worth to mention is that a process `com.docker.wsl-distro-proxy.exe` is continually starting and dying in the host Win10. I can see this in the Task Manager.

The corresponding piece (I think) in the `logfile` is:

```
[00:08:45.888][WslIntegrationAgent-Ubuntu-18.04][Info   ] time="2020-06-04T00:08:47+08:00" level=fatal msg="open /run/docker-desktop-proxy.pid: permission denied"
[00:08:45.958][WslIntegrationAgent-Ubuntu-18.04][Info   ] 2020/06/04 00:08:45 Proxy error: exit status 1
```

And these two lines repeat again and again in the logfile.

**Comment by grebnetiew** [comment]
I had the same problem, and (tentatively) attribute it to having set zsh as the shell for root.

I do think docker should be able to deal with 'nonstandard' configurations, or at least give some semblance of an error message if it finds a situation it can not deal with.

**Comment by mchobbylong** [comment]
@grebnetiew Seems that docker is only adapted to bash as the default shell. And it is noteworthy that invoking zsh by `zsh -c` will have a different behavior compared to bash (see [here](https://superuser.com/questions/91881/invoke-zsh-having-it-run-a-command-and-then-enter-interactive-mode-instead-of)), which may be the reason why docker's integration process fails.

**Comment by lackovic** [comment]
I am having the same issue on [ArchWSL](https://github.com/yuk7/ArchWSL), logged in as non-root user belonging to the wheel group (`%wheel ALL=(ALL) ALL` in visudo).

Any idea how I could solve/troubleshoot it?

Using bash:
```sh
$ ps -p $$
PID TTY          TIME CMD
  8 pts/0    00:00:00 bash
```

Docker is running and WSL 2 is enabled:

![2020-06-30_140643](https://user-images.githubusercontent.com/1663053/86119537-57b05700-badb-11ea-94c0-8488460d48c1.png)

Windows 10 version 2004 build `19041.329`
Docker Desktop Version: `2.3.0.3 (Stable)`

**Comment by lackovic** [comment]
> Any idea how I could solve/troubleshoot it?

Uninstalling and re-installing Docker Desktop has fixed the issue.

Went through [the documentation](https://docs.docker.com/docker-for-windows/wsl/#install) again an noticed the sentence _Ensure you have completed the steps described in the Prerequisites section before installing the Docker Desktop Stable 2.3.0.2 release._ I suspect I had previously installed Docker Desktop before WSL 2.

**Comment by chiptus** [comment]
> Okay, I just found that the problem comes from a fake-`bash` I set as the default shell of `root`. This actually makes the integration process failed to execute the commands with `root` privilege. This issue is now solved.

I have the same problem. I don't see a service that is terminating. Where is that logfile you mentioned? How do I know which is the default shell for `root`? Mine was zsh and I changed to bash using `chsh -s $(which bash)`

**Comment by mchobbylong** [comment]
@chiptus 

> Where is that logfile you mentioned? 

Right-click Docker's tray icon then click "Troubleshoot". This will generate the logfile.

> How do I know which is the default shell for `root`?

It is in file `/etc/passwd`.

The good news is that a new Stable version is released and the developer group claimed this issue is properly fixed (related issue: #7653). You should give it a try :-)

**Comment by chiptus** [comment]
I actually fixed it by uninstalling the ubuntu app and installing ubuntu
20.04

**Comment by chiptus** [comment]
and it's back again 👎

**Comment by chiptus** [comment]
I have the following logs:
```
[13:05:04.261][WslIntegrationAgent-Ubuntu-20.04][Info   ] /bin/bash: /mnt/wsl/docker-desktop/docker-desktop-proxy: Permission denied
[13:05:04.317][WslIntegrationAgent-Ubuntu-20.04][Info   ] 2020/07/29 13:05:04 Proxy error: exit status 126
[13:05:05.706][WslIntegrationAgent-Ubuntu][Info   ] 2020/07/29 13:05:05 unable to create ~/.docker directory: exit status 4294967295
[13:05:08.067][WslIntegrationAgent-Ubuntu-20.04][Info   ] /bin/bash: /mnt/wsl/docker-desktop/docker-desktop-proxy: Permission denied
[13:05:08.141][WslIntegrationAgent-Ubuntu-20.04][Info   ] 2020/07/29 13:05:08 Proxy error: exit status 126
[13:05:09.459][WslIntegrationAgent-Ubuntu][Info   ] 2020/07/29 13:05:09 unable to create ~/.docker directory: exit status 4294967295
[13:05:11.921][WslIntegrationAgent-Ubuntu-20.04][Info   ] /bin/bash: /mnt/wsl/docker-desktop/docker-desktop-proxy: Permission denied
[13:05:11.984][WslIntegrationAgent-Ubuntu-20.04][Info   ] 2020/07/29 13:05:11 Proxy error: exit status 126
[13:05:12.222][WslIntegrationAgent-Ubuntu][Info   ] 2020/07/29 13:05:12 unable to create ~/.docker directory: exit status 4294967295
```

root default shell is /bin/bash

**Comment by alfonso-rb** [comment]
This happened to me. I had to uninstall and reinstall docker desktop. I rebooted in between for good measure. I wouldn't be surprised if it happens again...

**Comment by samuk190** [comment]
Don't need to reinstall it.

Open windows shell as admin
wsl --unregister docker-desktop

then go to services, stop docker desktop service

restart and voila

**Comment by Falx** [comment]
While this solves it when it happens (issuing `wsl --unregister ubuntu`, then restarting everything). I was able to reproduce the issue every time I issue the following command: `docker rm -f [containername]`. 

I am running 
* Docker Desktop 2.3.0.4 (46911) stable
* Engine: 19.03.12
* On WSL2 (using Ubuntu)

**Comment by zxibang** [comment]
It might be the WSL2 Ubuntu isn't the default subsystem.
I solved this problem by:
1. windows shell cmd run: wsl --unregister docker-desktop
2. go to services, stop docker desktop service
3. windows shell cmd run: wslconfig /s  Ubuntu-16.04  #Ubuntu-16.04 is my wsl2 ubuntu's name
4. checkout is it the default subsystem: wsl --list
5. open docker desktop APP, then open ubuntu and run docker command.

**Comment by xe-nvdk** [comment]
> While this solves it when it happens (issuing `wsl --unregister ubuntu`, then restarting everything). I was able to reproduce the issue every time I issue the following command: `docker rm -f [containername]`.
> 
> I am running
> 
> * Docker Desktop 2.3.0.4 (46911) stable
> * Engine: 19.03.12
> * On WSL2 (using Ubuntu)

Happens to me too. Same scenario.

**Comment by parkan** [comment]
you can also check whether the integration is enabled for a specific system under `Settings -> Resources -> WSL INTEGRATION` (separate from the "Use the WSL2 Engine" setting in General) and enable/disable it for specific images

**Comment by spicylentils** [comment]
Confirm Docker for Windows is running. It wasn't for me. After Docker for Windows is running, execute hash -r. docker now runs in WSL2.

**Comment by gphorvath** [comment]
> Don't need to reinstall it.
> 
> Open windows shell as admin
> wsl --unregister docker-desktop
> 
> then go to services, stop docker desktop service
> 
> restart and voila

This helped me!

**Comment by adi-mohan** [comment]
> Don't need to reinstall it.
> 
> Open windows shell as admin
> wsl --unregister docker-desktop
> 
> then go to services, stop docker desktop service
> 
> restart and voila

This worked for me!
