### ISSUE TITLE
exit code: -1  stdout: There is no distribution with the supplied name.

### ISSUE THREAD

**Issue by rnwolf** [docker/for-win#7050]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID:  0627D9A5-F188-464C-9800-511273C03C1B/20200604073724

### Expected behavior

Turn on laptop, windows notifications show that docker is running.

### Actual behavior

Turn on laptop,  Docker Error window, with options to reset report or quit.

### Information

Updated to latest insiders build, 19640, for Win10 today. 
(Have been getting Win 10 Green error screen intermittently for several weeks to say that there was a hypervisor error.)
Reset to factory defaults, via option on error dialog, did not resolve the error.

  - Windows Version: Insider Build Microsoft Windows 10 Pro    10.0.19640 Build 19640
  - Docker Desktop Version: Docker version 19.03.8, build afacb8b 
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Turn laptop off/on
  2. Login in
  3. Wait for error screen.

**Comment by jcohentech** [comment]
I have the same exact problem. I installed Docker Desktop for Windows on a fresh install of Windows 10 19640 (aka 2020). I have enabled WSL2 and installed Ubuntu 18.04. I have installed the latest packages in the distro. Here is my back trace when I do a "Factory Reset" even though I have never had the Docker Desktop running:
[docker.log](https://github.com/docker/for-win/files/4743359/docker.log)

**Comment by bartj3** [comment]
I was running into similar issues, tried reinstalling Docker and everything. This is a totally uneducated "fix", but what solved this for me was removing both docker-desktop and docker-desktop-data via powershell and then restarting Docker, so:
```
 wsl --unregister docker-desktop
 wsl --unregister docker-desktop-data
```

This will obviously result in loss of some data, but for that was fine.

**Comment by jkone27** [comment]
thanks, got the same problem. @bartj3 solution solved for me, but still not clear why this happens

**Comment by jcohentech** [comment]
The first command:

`wsl --unregister docker-desktop`

Resolved my problem. Thank you very much for resolving that for me. It appears the install is causing a problem.

**Comment by rnwolf** [comment]
@bartj3 suggestion worked for me. Thanks.

**Comment by ethanbergstrom** [comment]
This worked for me. Ran into it with a brand new install on top of 2004. Thanks!

**Comment by kevprice83** [comment]
I had the same issue and executing `wsl --unregister docker-desktop` seems to have fixed the issue. Additionally there was a warning/error printed after that saying something to do with directory could not be found. Now when I execute that command I don't get the same error, it just stops the docker desktop process cleanly.

**Comment by czmichael** [comment]
thanks, got the same problem. @bartj3 solution solved for me

**Comment by astamicu** [comment]
Thanks for the unregister tip. 
When running `wsl -l -v` docker-desktop was stuck as installing.
The unregister and restart docker solved the failing start.
