### ISSUE TITLE
Docker stops responding randomly - Error response from daemon: Bad response from Docker engine

### ISSUE THREAD

**Issue by infa-mnagappa** [docker/for-win#7055]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 285D752F-D7CB-4FD1-AEC3-5B1F29261F03/20200604231021
Note: This is diagnostics after I upgraded to latest version  as per my comment: https://github.com/docker/for-win/issues/7055#issuecomment-639168787. I had some issues uploading diagnostics when I originally reported this issue.

### Information
  - Is it reproducible?
It happens mutliple times a day. But i don't know what exactly leads to this.
  - Is the problem new?
Started last week. While I'm not sure, it could be related to some changes that happened in the system as part of our monthly IT software patch
  - Did the problem appear with an update?
This is not associated with Docker Desktop updates. I've been on the same version for a few months without any issues. 
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.
No Repro
  - Windows Version: Windows 10, Version 1809, OS Build: 17763.1158
  - Docker Desktop Version: 2.1.0.5 (40693) stable
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No.
### Steps to reproduce the behavior
Don't know the repro. It happens randomly. I have been trying to correlate with any specific specific event such as my VPN connection state to my company's network, etc. I've reduced the number of the containers that I run, increased RAM, etc. I'm not able to correlate this to any local AntiVirus/Firewall activity also.

Most of the time, I have to restart my system. Just restarting Docker for Desktop alone does not work.

[docker-log.txt](https://github.com/docker/for-win/files/4729792/docker-log.txt)

**Comment by infa-mnagappa** [comment]
I'll collect and post diagnostics next time this happens

**Comment by infa-mnagappa** [comment]
I upgraded to:
Version: 2.3.0.3 (45519)
Channel: stable

I don't know if this problem is the same as what I reported originally. Now I'm now seeing a different error message:
>docker ps
Error response from daemon: open \\.\pipe\docker_engine_linux: The system cannot find the file specified.

Here is my diagnostics ID: 285D752F-D7CB-4FD1-AEC3-5B1F29261F03/20200604231021

I have gone through this issue reported earlier: https://github.com/docker/for-win/issues/4495
1. I see errors in my Windows Event Log: 'DockerDesktopVM' was reset because an unrecoverable error occurred on a virtual processor that caused a triple fault. This error might have been caused by a problem in the hypervisor. If the problem persists, contact Product Support. (Virtual machine ID 55D7769F-ED61-4B81-815D-42C7C4D3223C)
2. The workaround described here didn't help: https://success.docker.com/article/docker-for-windows-fails-with-a-daemon-not-running-message

**Comment by infa-mnagappa** [comment]
Restarting Docker Desktop from UI helps to workaround.

**Comment by philastrophist** [comment]
> 
> 
> Restarting Docker Desktop from UI helps to workaround.

Not permanently

**Comment by ozgurtezel89** [comment]
I have the same issue, was able to run it for an hour the other day, but now I am now able to start it at all. I have windows build 1809

**Comment by infa-mnagappa** [comment]
Got this from windows event viewer and it appears specific to linux vm page fault seen below:
<6>[ 9037.663284] docker0: port 1(veth39a0a47) entered disabled state
<1>[12673.171087] BUG: unable to handle kernel paging request at fffffffefffbd20d
<6>[12673.171451] PGD 164010067 P4D 164010067 PUD 0 
<4>[12673.171671] Oops: 0010 [#1] SMP PTI
<4>[12673.171846] CPU: 2 PID: 0 Comm: swapper/2 Tainted: G             L  T 4.19.76-linuxkit #1

It may be too early to claim that the problem is completely resolved. But just wanted to put this out in case you want to  try these options. Both of them seem to improve stability:
Opiton 1. https://social.technet.microsoft.com/Forums/en-US/ee5b1d6b-09e2-49f3-a52c-820aafc316f9/hyperv-doesnt-work-after-upgrade-to-windows-10-1809?forum=win10itprovirt
Option 2: If you don't want to be dealing with security flags as suggested in option 1, then try applying Windows 1909 update.

**Comment by ozgurtezel89** [comment]
I have removed the following MS updates and didn't have the issue over the weekend (however didn't have much time to fully monitor it.) Once I fully monitor it will post an update if the issue is resolved. Thanks for sharing @infa-mnagappa I will try your solution too. 
MS Updates I have removed:
KB4558998
KB4561608
KB4551853
KB4552930
