### ISSUE TITLE
Docker crashes on launch.

### ISSUE THREAD

**Issue by FireMasterK** [docker/for-win#7060]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B4752325-D68D-4301-A7C9-64F15777CBA3/20200604162647

### Expected behavior
Docker starts up.
### Actual behavior
Docker crashes on launch.
### Information

  - Windows Version: Microsoft Windows [Version 10.0.19041.264]
  - Docker Desktop Version: 2.3.0.3 (45519)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. Enable Hyper-V feature and VT-d in BIOS.
  2. Install WSL
  3. Install Docker.
  4. Open Docker Desktop

**Comment by joemsak** [comment]
Docker stopped working for me and WSL - docker would not open - I reinstalled docker - now it starts by crashing saying the WSL distro stopped. I cannot do my work as a result

**Comment by FireMasterK** [comment]
Solved by reinstalling windows.
