### ISSUE TITLE
Can we run docker on a VM with Windows10 and  WSL1? (nested virtualization - host is a VM & ubuntu VM is created through hyper-v for docker) 

### ISSUE THREAD

**Issue by pingasa** [docker/for-win#7069]
[log.txt](https://github.com/docker/for-win/files/4733816/log.txt)

  - [ ] I have tried with the latest version of my channel (Stable or Edge) - stable
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: CF13FEC2-6CD2-428A-9157-B6C8AE565B29/20200604114726

### Information

  - Windows Version: Windows 10 Enterprise , VM , build : 10.0.17763.1217
  - Docker Desktop Version:2.3.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Yes, Windows vitual machine

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mat007** [comment]
Docker Desktop is not supported in a virtualised environment. It might work or it might not, but it's out of our control, it depends on whether the outer virtual machine supports nested virtualisation.
For more information see https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-desktop-in-nested-virtualization-scenarios.
