### ISSUE TITLE
Can't share drive because UAC is not used

### ISSUE THREAD

**Issue by Pomax** [docker/for-win#707]
Windows 10 pro x64, local administrator account without a password, set to require manual UAC consent for any sensitive operation.

### Expected behavior

Share drive, click apply, get UAC prompt to allow the operation by docker.

### Actual behavior

Share drive, click apply, get a username and password dialog. Since the account has no password, the share operation can never be completed.

### This part makes sense

![screenshot 208](https://cloud.githubusercontent.com/assets/177243/25757919/647f4504-3181-11e7-93b9-17f78a1f3074.png)

### This part does not

This should be a UAC prompt, with the application asking Windows whether it's allowed to do a thing (and windows then asks the user, without the requesting application having insight into that process). UAC is explicitly there to prevent applications from grossly overstepping their boundaries: if your application asks for a user's password, your application cannot be trusted anymore because it now has all the information it needs to run arbitrary code: install whatever it likes, delete any normally protected directory, full unfettered access to the registry, etc. etc. etc.

![screenshot 209](https://cloud.githubusercontent.com/assets/177243/25757932/716cb120-3181-11e7-94c9-777bd75c74f5.png)

You should never be asking the user for their username/password. Each sensitive operation should be a UAC request (and then if users known better, they can explicitly run the application "as administrator" so that UAC requests are automatically granted)

**Comment by jpmckearin** [comment]
This would fix a lot of problems people are having with password requirements when sharing a drive.

**Comment by G-Rath** [comment]
@Pomax @jpmckearin The reason that docker requires you to have a password is because[ it mounts your *entire hard drive* as a network share](https://github.com/docker/for-win/issues/616#issuecomment-319856195).

Asking for UAC here would result in your hard drive being exposed without a password.

Docker believe that the only way to handle this is to - as you say - demand you hand over your admin password, and trust them to do nothing malicious with it.

**Comment by Pomax** [comment]
This raises questions... asking for UAC permission here is still absolute the correct way to go, so based on your description the much more important question is why Docker needs to expose the entire drive, instead of network-mapping very specific directories as network drives (because that's a thing Windows can do just fine). If Docker just needs to "see" a drive then expose what it needs to see "as a drive", don't expose the entire drive, that would be silly.

**Comment by G-Rath** [comment]
@Pomax I completely agree. If you look at the issue I linked to, it seems like Windows containers *may* offer a solution in the future, once they support Linux containers.

**Comment by Pomax** [comment]
/remove-lifecycle stale

This is something that really does need to be addressed for Windows.

**Comment by stephen-turner** [comment]
This is fixed with the new filesharing mechanism in 2.2.0.3.
