### ISSUE TITLE
An error occurred when I wanted to launch Docker Desktop

### ISSUE THREAD

**Issue by NeginMajidi** [docker/for-win#7070]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
No debugging info in the ticket, closing.
