### ISSUE TITLE
Newly installed docker desktop not starting on Windows Home

### ISSUE THREAD

**Issue by nickygiorgi** [docker/for-win#7072]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 822C5818-12DA-49F2-9368-F174F912E979/20200605062256

### Expected behavior

After installation, I can start docker desktop successfully.

### Actual behavior

After installation, docker desktop fails to start.

### Information

  - Windows Version: Windows Home version 2004 (OS Build 19041.264)
  - Docker Desktop Version: 19.03.8, build afacb8b
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no, I am running on a physical machine (a Dell laptop, model Inspiron 17)

### Steps to reproduce the behavior

  1. Verify that laptop supports hardware virtualization by checking Performance tab of the Task manager as detailed on documentation
  2. Verify WSL2 is updated
  3. Open the Windows Features dialog and verify "Virtual Machine Platform", "Windows Hypervisor Platform" and "Windows Subsystem for Linux" are enabled
  4. Download Docker Desktop from https://hub.docker.com/editions/community/docker-ce-desktop-windows
  5. Run the installer
  6. The installer reports that my machine is compatible with docker desktop
  7. Installation completes successfully
  8. Start Docker Desktop. Docker Desktop fails to start.
  9. Restart Windows
  10. Try starting Docker Desktop. Docker Desktop fails to start again.

Thank you for looking at this issue!

**Comment by StefanScherer** [comment]
According to the diagnostics WSL has a problem to find the Docker Desktop distro.
What is the output of the following command?
```
wsl.exe -l -v
```

**Comment by nickygiorgi** [comment]
Hi Stefan,

it's:

NAME                   STATE           VERSION
docker-desktop    Installing      2

hope this helps.

**Comment by StefanScherer** [comment]
Oh, then it's stuck. There is a rare issue.
In that case you could fix it by stopping Docker Desktop, then remove the docker-desktop distro with the following command

```
wsl.exe --unregister docker-desktop
```

Then start Docker Desktop again.

**Comment by nickygiorgi** [comment]
Thank you, it started now!

Going to close this issue.
