### ISSUE TITLE
Docker fails to start on Windows 10 version 2004 using WSL2

### ISSUE THREAD

**Issue by Cyberuben** [docker/for-win#7075]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 7D6F6550-69C3-469F-AE84-B8B6500074BD/20200605091737

### Expected behavior
Docker starts normally, causing me to run my application

### Actual behavior
Docker takes a long while to boot, eventually opening a crash report. Docker worked fine yesterday, no updates were installed as far as I know.

### Information

  - Windows Version: Windows 10 version 2004 (build 19041.264)
  - Docker Desktop Version: 
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

Will add crash log once it appears again

### Steps to reproduce the behavior

  1. Start Windows
  2. Start Docker for Windows

**Comment by rohanBrid18** [comment]
I'm also facing the same issue on Windows 10 version 2004 (build 19041.450)

**Comment by yamelkaya** [comment]
I have the same situation. It seems the issue happened after the latest Windows Update 

Windows 10 Home 2004 (build 19041.450)

**Comment by derrick-lau** [comment]
I have the same issue with Windows 10 Home 2004 (build 19041.450)

**Comment by cameeob2003** [comment]
I am facing the same issue.
