### ISSUE TITLE
Slow command execution while on slow internet

### ISSUE THREAD

**Issue by mikesir87** [docker/for-win#7077]
I've got a colleague who is currently relying on satellite internet while working from home. Every docker command takes half a minute to run, even when not pulling any images, etc. 

To troubleshoot, he's turned off "Send usage statistics", but no real change was noticed. If he turns off his wifi, commands run instantly. 

What else should I be looking at? He did mention this was the behavior both before and after running with WSL2, so hasn't been a recent change it seems. Any pointers?

Diagnostic ID: `18540BE9-D5C2-42F7-B709-3F2DB043FDCB/20200605135204`

**Comment by chris-crone** [comment]
This might be this issue: https://github.com/docker/cli/issues/2420

The latest Desktop does not yet ship the latest CLI so I'll get you a build to test if it is fixed

**Comment by mat007** [comment]
There is a range a suspicious causes described in #2131 as well.

**Comment by StefanScherer** [comment]
I once sat in a train and had slow experience using the experimental `docker manifest` commands. These commands do a lot of requests to Hub to get metadata.

**Comment by mikesir87** [comment]
Hi all! Thanks for jumping in so quickly. @chris-crone sent me an updated CLI build that contains the PR merge from docker/cli#2516. I had my colleague test it out and confirmed that command execution is much, much faster now. So, looks like we're good to go! Any idea how soon that might make it into a DD build/deploy?

**Comment by StefanScherer** [comment]
Thanks for testing the cli. It‘s part of Docker 19.03.11 and the next release edge or stable will have it. But I don‘t have a release date for you 😅.

**Comment by StefanScherer** [comment]
We've shipped 19.03.12 with the latest Docker Desktop Stable 2.3.0.4.
