### ISSUE TITLE
[Windows container] Cannot open cli from dashboard

### ISSUE THREAD

**Issue by stefanoPrimo** [docker/for-win#7079]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
I have a windows container. from the dashboard, if I choose the action "CLI" in order to open the terminal it will point to` bin/bash` but because of the container is of the type windows, the terminal won't open. Instead, it has to open PowerShell/CMD (maybe according to some settings)
### Actual behavior
![image](https://user-images.githubusercontent.com/36199751/83895499-0e2a5180-a753-11ea-8b9b-6ae69d3818fb.png)

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. switch to windows container
  2. create/run any windows based container
  3. Go to dashboard --> click on action "cli"

**Comment by mat007** [comment]
Thanks for the report, I have created an internal ticket to fix the issue.

**Comment by stephen-turner** [comment]
This is fixed in the latest Edge release, 2.3.2.0.
