### ISSUE TITLE
amend https://github.com/docker/for-win/issues/114 with a link to the stated documentation

### ISSUE THREAD

**Issue by Pomax** [docker/for-win#708]
https://github.com/docker/for-win/issues/114 was closed but @rneugeba forgot to include the link(s) to *where* the mentioned documentation updates are, which makes it very hard for people to find their way to a possible solution to a problem they're tearing their hair out over.

Can the issue be amended (or the last comment updated) to include explicit links to the docs?

**Comment by friism** [comment]
Here's a link: https://docs.docker.com/docker-for-windows/troubleshoot/#docker-fails-to-start-when-firewall-or-anti-virus-software-is-installed

I also updated Rolf's comment.
