### ISSUE TITLE
Docker Desktop crashes when switching to Linux Container  

### ISSUE THREAD

**Issue by garunachalam-btig** [docker/for-win#7081]
In docker Desktop (running on a Windows 10 1903 VM), when i switch to Linux Container, It crashes.

- Diagnostics ID:
E6CB342D-D95D-43C2-98F8-D381E58CE177/20200605162203
### Expected behavior
When switching to Linux Container, it should work.
### Actual behavior
It crashes

  - Windows Version:
Window 10 1903

  - Docker Desktop Version:
2.3.0.3 (45519)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
Yes, running Docker desktop on a windows VM.

### Steps to reproduce the behavior
This is a brand new install.  On a newly provisioned VM, I installed docker desktop and switched to linux container. That's it.

**Comment by mat007** [comment]
Docker Desktop is not supported in a virtualised environment. It might work or it might not, but it's out of our control, it depends on whether the outer virtual machine supports nested virtualisation.
For more information see https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-desktop-in-nested-virtualization-scenarios.
