### ISSUE TITLE
Docker won't start after changing computer name in Windows 10 Pro

### ISSUE THREAD

**Issue by erick-tejada** [docker/for-win#709]
### Expected behavior

Normal startup.

### Actual behavior

After changing the computer name in Windows 10 Pro, I get the following error:

Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The computer 'ETEJADA-SURFACE' could not be resolved. Make sure you typed the machine name correctly and that you have network access. The previous name was the original serial number...

This is happening even after Resetting to Factory Defaults and even completely uninstalling/re-installing Docker... Unfortunately, I don't remember the old name to change it back and test if it works again... Shouldn't uninstalling Docker clear any old config referencing my old computer name?

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.

2467046C-F354-4B1E-8906-CA4198A8B60D/2017-05-05_16-59-00

  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

Windows 10 Pro
Version 1607 (OS Build 14393.1066)

### Steps to reproduce the behavior

  1. Change computer name
  2. Start Docker

**Comment by pfaffle** [comment]
Shot in the dark, but I had a computername of "cmeinschein-ulyaoth", and was experiencing the same issue after upgrading to Docker 17.03.1-ce-win10 (11972). I renamed my computer to "cmeinscheind" instead and reinstalled Docker, and the service started up successfully.

Related to having a dash in the computer name, maybe?

**Comment by friism** [comment]
It's because the hostname is too long - we have an internal issue tracking this.

**Comment by erick-tejada** [comment]
@friism Thank you. I have shortened the name and it works. 

Curiously enough, before shortening the name, I uninstalled Docker, then Disabled/Re-enabled Hyper-V and reinstalled docker, and Docker was working fine... until I restarted the PC and the problem showed itself again (I'm just putting this out there in case it might help you guys solving the issue...).
