### ISSUE TITLE
Shared Drives does not appear in settings for Linux Containers Mode

### ISSUE THREAD

**Issue by baaridunnasr** [docker/for-win#7093]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
In Linux containers mode, there should be an option to share drives.

### Actual behavior

There is no option to share drives in Linux Containers mode
![Docker Settings](https://user-images.githubusercontent.com/12585952/83958471-e55ba680-a88f-11ea-9992-cd692017c8c5.png)

Docker containers actually run with no issue at all. Next Cloud instance was tested with no issues. 

### Information

  - Windows Version: Version 2004, 19041.264
  - Docker Desktop Version: 2.3.0.3 (45519) Stable
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Hyper V and Containers features enabled
  2. Install Docker from installer
  3. Not sure if there's any other issue but it doesnt show. 
  4. Have tried reinstalling.

Can I additionally try to install docker without WSL integration? Maybe that might work?

**Comment by mat007** [comment]
There is no need for configuring file sharing with the WSL 2 backend as the system takes care of permissions.
What is the problem you are having exactly?

**Comment by baaridunnasr** [comment]
So when we say a linux container is running on a Win 2004 it is actually working on WSL2? Then it would mean that we have drive access by default.

I had just installed Docker on Windows and created a nextcloud container. Is it possible for me to check from within the container if I can read/write to a windows directory?

**Comment by mat007** [comment]
> So when we say a linux container is running on a Win 2004 it is actually working on WSL2? Then it would mean that we have drive access by default.

Yes.

> Is it possible for me to check from within the container if I can read/write to a windows directory?

I guess you can try and `touch` a file?

> It was my understanding that a Linux container on a Win host would have an option (Share Drive) so that the linux container can access the windows directory... Perhaps you can clarify or point me in the right direction?

You need to mount a folder when running the container, see for instance https://docs.docker.com/storage/bind-mounts/

**Comment by baaridunnasr** [comment]
Yes! That worked completely fine. Thanks for helping me out. :)
