### ISSUE TITLE
Problem loading Docker desktop on Windows 10

### ISSUE THREAD

**Issue by firebull81** [docker/for-win#7115]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 23BC9767-6012-4CE1-A8FE-35B960FAB401/20200608095444

### Expected behavior
- Run properly

### Actual behavior
- Can't run/load

### Information

  - Windows Version: 10 Enterprise
  - Docker Desktop Version: v19.03.8
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Install docker desktop
  2. Try to run it

**Comment by sturteva** [comment]
I am having similar issues, also running 10 Enterprise.

Docker version 19.03.8, build afacb8b

Diagnostics ID: 69B2FF41-603D-4DE0-9185-2975AC2FF39C/20200608211823 (uploaded)

I have ensured that I have Hyper-V installed and that my CPU allows for virtualization

![VirtualizationTaskManagement](https://user-images.githubusercontent.com/32139677/84083036-b7f92080-a995-11ea-8ca5-be89024c31e8.png)
