### ISSUE TITLE
Docker crash on windows start

### ISSUE THREAD

**Issue by srothkin** [docker/for-win#7119]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by frankenbeans** [comment]
I was able to replicate this issue on my Mac using High Sierra 10.13.6
