### ISSUE TITLE
Docker for Windows (edge) New Installer does not recognize Windows 10 Education Edition

### ISSUE THREAD

**Issue by willmtemple** [docker/for-win#712]
### Expected behavior

The Docker for Windows (edge) executable Installer should be compatible with Windows 10 Education edition, as this version of Windows supports Hyper-V and works fine with docker when installed from the legacy MSI installer.

### Actual behavior

The new installer fails with the following message:

> **Installation Failed: one pre-requisite is not fulfilled**
> Docker for Windows requires Windows 10 Pro or Enterprise version 10586, or Windows server 2016 RTM to run

### Information

Docker for Windows Version 17.05.0-ce-rc1-win8 (11189)
Channel: edge
`73d01bb`

Windows 10 Education (Creator's Update, Version 1703, Build 15063.250)

### Steps to reproduce the behavior

  1. Install Windows 10 Education edition with the Anniversary or Creator's Update
  2. Enable Hyper-V
  3. Attempt to use the new installer, and observe that it does not succeed

**Comment by friism** [comment]
I think @simonferquel is working on a fix.

**Comment by andreymir** [comment]
Could be the same issue for Windows Pro N Insider Preview (build 16193). Installer fails with the same error message.

**Comment by oyosefi** [comment]
Got a similar one for Windows 10 Enterprise

**Comment by tparikka** [comment]
This is probably a duplicate of #725.

**Comment by erdemt** [comment]
when will be resolved? Is there any workaround?

**Comment by harunthuo** [comment]
did anyone find a working solution for this issue?

**Comment by zhangruoyao68** [comment]
same thing happened to win 10 education

**Comment by hannah-docker** [comment]
@simonferquel is this still on your radar? Looking for a status please

**Comment by rscarvalho** [comment]
Any updates on this?

**Comment by harunthuo** [comment]
updating my windows 10 pro solved the issue for me

**Comment by saifulss** [comment]
Same here. Leaving comment here for others. Windows 10 Education here. Once I finished Windows Update all the way, Docker for Windows started working. It wasn't before.

**Comment by willmtemple** [comment]
Is this still a thing?

**Comment by XBITSwitzerland** [comment]
I have this Error too. Noone found a solution?

**Comment by harrisdt15f** [comment]
I also cannot run docker on Education version
![image](https://user-images.githubusercontent.com/27404296/44942107-1a92b500-addd-11e8-87a7-f750e899a516.png)
![image](https://user-images.githubusercontent.com/27404296/44942112-3bf3a100-addd-11e8-97c4-3b0113f8e84f.png)
![image](https://user-images.githubusercontent.com/27404296/44942115-4b72ea00-addd-11e8-9f1d-308d0221fe40.png)
need help.

**Comment by willmtemple** [comment]
I'm unsubscribing from this bug since no one seems to care, this project is not open source, and I'm not even using windows anymore.

Good luck everyone who's been waiting over 480 days for the fix.
