### ISSUE TITLE
Docker failed to start and also failed to stop

### ISSUE THREAD

**Issue by melissagwolf** [docker/for-win#7128]
- [ X ] I have tried with the latest version of my channel (Stable or Edge)
  - [ X ] I have uploaded Diagnostics
  - Diagnostics ID:
B8C15C41-C7E0-4B6C-9938-BEB1B03E233F/20200609004142
B8C15C41-C7E0-4B6C-9938-BEB1B03E233F/20200609003944

### Expected behavior

Docker starts up normally

### Actual behavior

Error message that docker failed to start and also failed to stop

### Information

I just installed docker for desktop.  I first had to upgrade to the newest version of Windows 10 (OS build 19041.264).  I am using Windows 10 Home version 2004.  I do not have any dockerfiles yet and have not logged in yet.  I do not understand why docker is not starting or stopping properly

**Comment by dalgibbard** [comment]
Same issue here; repeatedly rebooting will usually allow it to start eventually. WSL is working fine in the meantime.

My diag ID for the same issue; Win10 build 19640.1
36E24245-04C5-43C6-8E05-8C0CEA05F175/20200609083645
