### ISSUE TITLE
Volumes do not mount using mingw

### ISSUE THREAD

**Issue by albfan** [docker/for-win#713]
### Expected behavior

After share C unit

> dir C:\mydir
file1
file2

> docker run -d -v ~/afanjul/mydir:/myvolume myimage

mount those files on docker container

### Actual behavior

mingw translate /myvolume into a absolute path on host

C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: invalid bind mount spec "/C/Users/afanjul/mydir;C:\\Program Files\\Git\\myvolume": invalid volume specification: '/C/Users/afanjul/mydir;C:\Program Files\Git\myvolume': invalid mount config for type "bind": invalid mount path: '\Program Files\Git\myvolume' mount path must be absolute.

on cmd.exe it works correctly

### Information

docker ce 17.03.1-ce-win5 (10743)
windows 10

**Comment by jrajala-eficode** [comment]
I am dealing with same problem...

**Comment by castarco** [comment]
Me too u.u ...

**Comment by friism** [comment]
Both mingw and Docker for Windows attempts to magically rewrite paths to make volume mounts work. I think what you're seeing is that magic interacting badly.

I recommend using a different shell or using absolute paths quoted to result in a correct windows-style path.

**Comment by albfan** [comment]
You're right: http://www.mingw.org/wiki/Posix_path_conversion

Seems double // solves it
