### ISSUE TITLE
"Switch to Windows containers..." disabled (version 1511 build 10586.873)

### ISSUE THREAD

**Issue by jasonp123** [docker/for-win#715]
### Expected behavior
Expected to be able to switch to Windows containers for build 10586.873

### Actual behavior
Context menu item disabled

### Information
winver tells me I am running version 1511 (build 10586.873).  The "Switch to Windows containers..." is disabled and tooltip says build 14372 and higher is required.

HyperV manager shows MobyLinuxVM running (although it doesn't look like I can connect to it)

Could this be a group policy setting?

**Comment by friism** [comment]
That sounds strange - cc @simonferquel @ebriney 

@jasonp123 can I get you to upload a diagnostic so that we have all the details on your system?

**Comment by jasonp123** [comment]
How can I generate a diagnostic and look at it locally (so I can sanitize)?

**Comment by jasonp123** [comment]
You can probably remove this.  My 1st grade math failed me (build 10586.873 < 14372)

**Comment by jasonp123** [comment]
You can probably remove this.  My 1st grade math failed me (build 10586.873 < 14372)
