### ISSUE TITLE
failed during hnsCallRawResponse: hnsCall failed in Win32: An adapter was not found. (0x803b0006)

### ISSUE THREAD

**Issue by KhimairaCrypto** [docker/for-win#7155]
- [ x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x ] I have uploaded Diagnostics
  - Diagnostics ID: A60B047F-98F8-483D-9A5A-006030FCCD02/20200610023046

### Expected behavior
Been able to run the service

### Actual behavior
The service wont run and the task will send log the following error: failed during hnsCallRawResponse: hnsCall failed in Win32: An adapter was not found. (0x803b0006) 
### Information

  - Windows Version:10.0.19041 Build 19041
  - Docker Desktop Version: I tried using the 2.3.1.0 (edge) and 2.3.03(stable). Same outcome.
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: I am using it on my local PC. Tried turning on/off WSL2 and same results

### Steps to reproduce the behavior
  1. ...  docker swarm init --advertise-addr 192.168.0.92
  2. ...  docker create network -d overlay my-overlay
  3. ...  docker run -d -p 8000:80 --name my-running-site mcr.microsoft.com/windows/servercore/iis
. I am able to have iis running on port 8000 without any issues.
  4. ...  docker service create --name web --endpoint-mode dnsrr --publish mode=host,target=8000 --network my-overlay --constraint 'node.labels.os==windows'  mcr.microsoft.com/windows/servercore/iis
  5. ... docker service ps web --no-trunc
`wsdxwby7g2va0gvsfo3ghdfen   web.1               mcr.microsoft.com/windows/servercore/iis:latest@sha256:efca6c1d6af873ef75997a8331d6b1e0677cab38f14002de9ca820940b75785f   roller Ready               Rejected 2 seconds ago    "failed during hnsCallRawResponse: hnsCall failed in Win32: An adapter was not found. (0x803b0006)"
pp6ocb9zmtx5ei3riie8a97s0    \_ web.1           mcr.microsoft.com/windows/servercore/iis:latest@sha256:efca6c1d6af873ef75997a8331d6b1e0677cab38f14002de9ca820940b75785f   roller Shutdown            Rejected 7 seconds ago    "failed during hnsCallRawResponse: hnsCall failed in Win32: An adapter was not found. (0x803b0006)"
zp1pnwqwcq1s85enaz4qm7ilt    \_ web.1           mcr.microsoft.com/windows/servercore/iis:latest@sha256:efca6c1d6af873ef75997a8331d6b1e0677cab38f14002de9ca820940b75785f   roller Shutdown            Rejected 12 seconds ago   "failed during hnsCallRawResponse: hns`

**Comment by KhimairaCrypto** [comment]
Any idea guys?

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place?
Sorry, I would move it myself, but I can't because it's in a different org (it's `moby` not `docker`).
