### ISSUE TITLE
Kubernetes service is not starting

### ISSUE THREAD

**Issue by mfabbri** [docker/for-win#7159]
- [/] I have tried with the latest version of my channel (Stable or Edge)
  - [/] I have uploaded Diagnostics
  - Diagnostics ID: CEFA9330-E633-4346-9B6C-FEF0115067CD/20200610084032

### Expected behavior
Kubernetes service started
### Actual behavior
Kubernetes service always on starting status
### Information

  - Windows Version: 1803 (Build 17134.1304)
  - Docker Desktop Version: 2.3.0.3 (45516)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Physical laptop

### Steps to reproduce the behavior

  1. Activate Kubernetes flagging the checkbox
  2. Restart Docker Desktop

**Comment by gavinwilliams** [comment]
I'm having the same issue however I'm on:

Windows Version:  2004 (Build 19640.1) (Insiders)
Docker Desktop Version: 2.3.0.3 (45519)

I'm running under WSL.

**Comment by gavinwilliams** [comment]
Uninstalling Docker, restarting and installing again and enabling Kubernetes fixed it for me. It took a long time (about 15 mins) for the kubernetes service to start though.

**Comment by mfabbri** [comment]
yeah... I had to reinstall and I got it to work. I'm closing the issue but it sounds an hard way to solve problems...
