### ISSUE TITLE
Error when pulling image: connection refused

### ISSUE THREAD

**Issue by Ageraluon** [docker/for-win#716]
### Expected behavior
Docker pulls image from central repository 

### Actual behavior
Docker aborts pulling the image with the following exception:

>docker pull wonderfall/nextcloud
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:54563->[::1]:53: read: connection refused

The fault occurs with any image, i.e. docker pull hello-world produces the same error

### Information

- Diagnostic ID: 51578C7A-1132-4648-8158-802688E092E9/2017-05-08_23-46-36

- Running Docker CE edge on Windows Server 2016, all updates installed.

- Setting the DNS Server to 8.8.8.8 manually in the docker settings does not resolve the issue
### Steps to reproduce the behavior

- When starting docker, the images are pulling correctly
- Fault occurs after longer run times of docker edge running on windows server 2016.
- After restarting docker manually, the image pulls correctly again.

**Comment by cniweb** [comment]
I have the same issue.
Setting the DNS Server to 8.8.8.8 manually in the docker settings resolve the issue!

**Comment by guillemsola** [comment]
My Docker installation with Version 17.06.1-ce-win24 (13025) Channel: stable 54dc09c works perfectly after a hard reset. 

Then once I reboot computer (or so) it looses network connectivity with the above message. I had set my DNS to 8.8.8.8 and could pull images or do a search.

I'm with win10 in enterprise environment with no proxy.

**Comment by dustinmoris** [comment]
Same issue here. @guillemsola solution worked for me, thanks!

**Comment by guillemsola** [comment]
For any other having a similar issue. As this error is coming back almost every time I boot the computer what works for me is change **Docker -> Settings -> Network change DNS server from Automatic to fixed or fixed to Automatic**. 

IMO it seems that changing de DNS server re-configures the hyperv network so that it works again.

**Comment by gjorgiev** [comment]
Solution is correct. 

Changing DND in settings from automatic to fixed 8.8.8.8 solved the problem.

**Comment by 1605200517** [comment]
Seemes to come up again with stable/ Version 17.09.0-ce-win33 (13620)

**Comment by guillemsola** [comment]
@1605200517 did you tried to switch DB settings from automatic to fixed and the other way around every time it fails?

**Comment by cschyma** [comment]
I can confirm this issue with 17.09.0-ce-win33 (13620). Have to apply @guillemsola 's workaround to get it working after every login.

**Comment by beercafeguy** [comment]
I can confirm the issue still exists in Docker for windows. version: 17.09.1-ce, build 19e2cf6

**Comment by maddoglv** [comment]
its the same with 17.12.0-ce, build 9c692cd 

and the solution to this problem I cannot find tried to set it manual to 

 Docker -> Settings -> Network change DNS server from Automatic to fixed or fixed to Automatic.

and tried to do set to fixed apply and then back to automatic problem still remains...

**Comment by Ageraluon** [comment]
Changing the DNS seems to cause a restart which by itself provides a temporary fix - see description above. After long run times, the issue reappears.

**Comment by alim92** [comment]
this worked for me: changed to fixed DNS server and then changed back to automatic
