### ISSUE TITLE
Docker fails to start on Windows 10 version 1607

### ISSUE THREAD

**Issue by ben-court** [docker/for-win#717]
### Expected behavior
Docker successfully starts

### Actual behavior
Docker fails to start with the error:

    The operation has timed out.
      at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
      at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings)
      at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
      at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

### Information

  - Diagnostic ID: B0D5D082-3935-4056-946B-E1F1118F0ABF/2017-05-09_12-50-48
  - Windows 10 version 1607

I have tried uninstalling and reinstalling the latest version but get this error every time I try to start docker. I've also tried the restart docker and reset to factory defaults options but neither make any difference

**Comment by Sandra-Young-Brighton** [comment]
Same situation here. I've tried uninstalling Docker for Windows, removing Hyper-V and restarting, then reinstalling Docker for Windows and allowing it to turn Hyper-V back on.

**Comment by jamiebull1** [comment]
Same situation here. I've tried uninstalling Docker for Windows, removing Hyper-V and restarting, then reinstalling Docker for Windows and allowing it to turn Hyper-V back on.

**Comment by Sandra-Young-Brighton** [comment]
Thank you - what I am planning on doing today is getting into Ubuntu through the boot DVD and uninstalling through that, then creating a virtual machine within Windows...
________________________________

**Comment by nicksterx** [comment]
Running this command in an elevated powershell fixed it for me. 

"MOFCOMP %SYSTEMROOT%\System32\WindowsVirtualization.V2.mof"
