### ISSUE TITLE
app in container can not get client real ip

### ISSUE THREAD

**Issue by SquallATF** [docker/for-win#718]
### Expected behavior
nginx run in container can get client real ip
### Actual behavior
nginx run in container get subnet gateway ip (`172.17.0.1`) as client ip
### Information

  - Diagnostic ID: A72FDF84-1D17-435F-BBE0-CE266B082CB8/2017-05-09_23-01-40.
  - Windows Server 2016 14393

### Steps to reproduce the behavior

 run `docker run --rm  -p 80:80  nginx:stable-alpine`

**Comment by friism** [comment]
I agree that this is not correct behavior, but I'm also curious to understand why you need the client IP for developing apps with Docker for Windows.

**Comment by SquallATF** [comment]
I'm try to build a production site via docker for windows. I known that is not recommend, but I only have a Windows server and can not be reinstall OS to Linux.

**Comment by consatan** [comment]
I‘m in the maintenance of a website, some features need to judge based on the client IP.

**Comment by mausolos** [comment]
I think this is the same issue I'm having, running 17.09.0-ce on windows 10 enterprise 64.

In my case, I'm trying to use xdebug between a docker container running Ubuntu 16.04 and phpstorm running in Windows.

What's super weird is I can telnet 10.0.75.1 9000, I can telnet docker.for.win.localhost 9000, I can telnet my Windows machine name at port 9000 as well. I try each of those in my xdebug.ini.

But when I try to actually use xdebug on a page, here's what I see in the logs (regardless of which of the above I've tried using):

Log opened at 2017-10-06 04:31:09
I: Checking remote connect back address.
I: Checking header 'HTTP_X_FORWARDED_FOR'.
I: Checking header 'REMOTE_ADDR'.
I: Remote address found, connecting to 172.17.0.1:9000.
W: Creating socket for '172.17.0.1:9000', poll success, but error: Operation now in progress (29).
E: Could not connect to client. :-(
Log closed at 2017-10-06 04:31:09

**Comment by ilyabreev** [comment]
Same issue. 17.09.1-ce-win42 (14687)
