### ISSUE TITLE
Persistent error after update: open \\.\pipe\docker_engine_linux: The system cannot find the file specified

### ISSUE THREAD

**Issue by philastrophist** [docker/for-win#7183]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
F3CFD39E-B805-4EF0-981E-1257B210569B/20200611113021
### Expected behavior
Downloads image from dockerhub and runs

`docker run -it -p 8888:8888 -e DISPLAY=192.168.1.115:0.0 -v ${pwd}:/opt/project/ lucidnonsense/astropython3 jupyter notebook --allow-root --no-browser --port 8888 --ip 0.0.0.0` 

### Actual behavior

```
Unable to find image 'lucidnonsense/astropython3:latest' locally
latest: Pulling from lucidnonsense/astropython3
d51af753c3d3: Already exists
fc878cd0a91c: Already exists
6154df8ff988: Already exists
fee5db0ff82f: Already exists
1675f1d8ad67: Downloading [============>                                      ]   34.3MB/141MB
18122b6a339f: Downloading [============>                                      ]  34.85MB/142.6MB
bb09b6428fb8: Download complete
62560ee5dffd: Download complete
3c79fd660826: Downloading [>                                                  ]   14.5MB/897.5MB
ae3006e1290e: Waiting
1e613e86a60d: Waiting
2307de7ce544: Waiting
C:\Program Files\Docker\Docker\resources\bin\docker.exe: Error response from daemon: Bad response from Docker engine.
See 'C:\Program Files\Docker\Docker\resources\bin\docker.exe run --help'.
```
And then when trying to run any other docker command:
```>>> docker ps
Error response from daemon: open \\.\pipe\docker_engine_linux: The system cannot find the file specified.
```
A restart fixes this for about 10 minutes.

### Information

  - Windows Version: 1809
  - Docker Desktop Version: 2.3.0.3 (45519)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. `docker run -it -p 8888:8888 -e DISPLAY=192.168.1.115:0.0 -v ${pwd}:/opt/project/ lucidnonsense/astropython3 jupyter notebook --allow-root --no-browser --port 8888 --ip 0.0.0.0`

**Comment by gyssels** [comment]
Same issue but has new when doing the (https://github.com/docker/for-win/issues/5919) solution:
❯ .\dockerd.exe
time="2020-08-19T17:52:28.785589600+02:00" level=info msg="Starting up"
failed to load listeners: open //./pipe/docker_engine: Access is denied.

**Comment by anand188** [comment]
Same issue i am facing in Windows 10 VM machine with Hyper-V, every time i need to restart purge clean all data works after few mins again same error
