### ISSUE TITLE
registry-mirrors works for linux containers but windows containers are not mirrored

### ISSUE THREAD

**Issue by paulkling** [docker/for-win#719]
### Expected behavior
I would expect Windows containers to mirrored like Linux Containers
### Actual behavior
When I set registry-mirrors on linux the registry:2 image from Docker Hub mirrors images. When I switch to Windows Containers and set registry-mirror docker will pull the image but it will not mirror
### Information
  - Using registry:2 image
  - Mirror/registry running on Linux 
  - Mirror configured with 
     - proxy:
           remoteurl: https://registry-1.docker.io
  - Docker version
     - Client:
 Version:      17.05.0-ce-rc1
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 20:55:05 2017
 OS/Arch:      windows/amd64
Server:
 Version:      17.05.0-ce-rc1
 API version:  1.29 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 20:55:05 2017
 OS/Arch:      windows/amd64
 Experimental: false

  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. Setup registry and configure config.yml
   - proxy: 
        remoteurl: https://registry-1.docker.io
  2. Switch to Windows containers
  3. Setup docker for windows to use registry-mirror 
  - I tried both https://dtr-test:5000 and just dtr-test:5000
![image](https://cloud.githubusercontent.com/assets/1531911/25861344/1016072e-34aa-11e7-8085-4c4b71b4d2cc.png)
  4. Do a docker pull and check registry to see if the registry has copy of the images.

**Comment by friism** [comment]
@paulkling what image did you pull? Note that Windows images rely on foreign layers that are not generally distributed to registries when pulling and pushing.

**Comment by friism** [comment]
More details here: https://github.com/moby/moby/issues/27580

**Comment by paulkling** [comment]
I see yeah these probably have foreign layers as they are the base Microsoft images.  It is unfortunate that we can't mirror the Microsoft images since they are so big. Thank you for the information. Feel free to close if moby/moby#27580 takes care of the issue.

These are the 3 images I tired to pull are.

- microsoft/dotnet-samples:dotnetapp-nanoserver

- microsoft/powershell

- hello-world:nanoserver

**Comment by friism** [comment]
I haven't considered the behavior for mirrors and foreign layers, so it's great that you're testing it. When you pulled `microsoft/dotnet-samples:dotnetapp-nanoserver` through the mirror, was _nothing_ cached (eg. not even the top-most layers)?

**Comment by paulkling** [comment]
Ok I nuked my repo/mirror apparently someone had manually tagged and pushed in a version of dotnet-samples image. I think this was causing the mirror not to work 

I now mirrored .. successfully. I would say the mirror is working with Windows Images

![image](https://cloud.githubusercontent.com/assets/1531911/25866094/e39e6cc0-34ba-11e7-94b2-7d71a8891054.png)
