### ISSUE TITLE
Container port binding working randomly

### ISSUE THREAD

**Issue by hawm** [docker/for-win#7196]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 20FB1524-C53D-4E05-8655-6ED43E68CFEC/20200611200628

### Expected behavior
Container listen all my defined ports after start.

### Actual behavior
Container ports are listening randomly, like below
1. all listening
2. part listening
3. all not listening

Restart the container will randomly change to one of the states describe above.

### Information

  - Windows Version: 10.0.19041 Build 19041
  - Docker Desktop Version: 2.3.1.0(45408)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Windows WSL 2 backend

### Steps to reproduce the behavior

Dockerfile: https://github.com/discourse/discourse_docker/blob/master/image/discourse_dev/Dockerfile
How i boot container: https://github.com/discourse/discourse/blob/master/bin/docker/boot_dev

  1. git clone https://github.com/discourse/discourse.git 
  2. run [bin/boot_dev](https://github.com/discourse/discourse/blob/master/bin/docker/boot_dev) to boot container inside repo which be cloned above.
  3. run `sudo netstat -tulpn | grep LISTEN` or whatever command to check port using you want, you may see one of the states i describe at **Actual behavior** section above, some ports are not listening at sometime.
  4. restart the container
  5. repeat step 3 to 5

**Comment by onomatopellan** [comment]
There is a known bug in WSL2 when coming from a shutdown state. Can you restart Windows and see if still happens?

**Comment by hawm** [comment]
> There is a known bug in WSL2 when coming from a shutdown state. Can you restart Windows and see if still happens?

It's keep happening whatever i restart the Windows or WSL many times. I possible see some similar issues about this but not sure , could you point me out where the known bugs related issue it is?

**Comment by onomatopellan** [comment]
If a restart didn't fix it then is a different issue. Localhost port forwarding fails when Fast Startup is enabled https://github.com/microsoft/WSL/issues/5298

**Comment by onomatopellan** [comment]
If it helps, I can't reproduce the issue in latest insider build 19645. Restarted the container twice.

![Annotation 2020-06-12 135239](https://user-images.githubusercontent.com/599142/84546919-b23b6c00-ad02-11ea-896c-297311fbe679.png)

**Comment by hawm** [comment]
But i can reproduce it.
![image](https://user-images.githubusercontent.com/20796940/84563032-2588c080-ad8b-11ea-95dd-fc2690fc91f5.png)

**Comment by onomatopellan** [comment]
Ah, that sounds like https://github.com/microsoft/WSL/issues/5306
What's the output of `netsh int ipv4 show excludedportrange protocol=tcp` ?

**Comment by hawm** [comment]
> Ah, that sounds like [microsoft/WSL#5306](https://github.com/microsoft/WSL/issues/5306)
> What's the output of `netsh int ipv4 show excludedportrange protocol=tcp` ?

But the ports what i am using for container are not listing by the command output
![image](https://user-images.githubusercontent.com/20796940/84564394-dc893a00-ad93-11ea-9b61-c04cc98faeaf.png)

**Comment by onomatopellan** [comment]
what's the output of `netsh int ipv4 show dynamicport tcp` ?

**Comment by hawm** [comment]
```
Protocol tcp Dynamic Port Range                                                                                        
 ---------------------------------                                                                                       
Start Port      : 1024                                                                                                  
Number of Ports : 13977    
```

**Comment by onomatopellan** [comment]
See https://github.com/docker/for-win/issues/3171#issuecomment-554587817

**Comment by hawm** [comment]
Thanks a lot, it's working now.

**Comment by onomatopellan** [comment]
You're welcome. Just out of curiosity, when was the last time you did a Windows clean install?

**Comment by hawm** [comment]
Almost 2 years ago------------------ Original ------------------From: onomatopellan  <notifications@github.com>Date: Sat,Jun 13,2020 5:59 PMTo: docker/for-win <for-win@noreply.github.com>Cc: hawm <dishohack@gmail.com>, State change <state_change@noreply.github.com>Subject: Re: [docker/for-win] Container port binding working randomly (#7196)
You're welcome. Just out of curiosity, when was the last time you did a Windows clean install?

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/docker/for-win/issues/7196#issuecomment-643600736",
"url": "https://github.com/docker/for-win/issues/7196#issuecomment-643600736",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
