### ISSUE TITLE
Docker -Cannot see option to Share Drives in Settings -Windows 10 Home

### ISSUE THREAD

**Issue by julien-campbell** [docker/for-win#7199]
Hi,

I have the problem where I cannot the see the option to Share Drives on Docker settings.
![image](https://user-images.githubusercontent.com/66806548/84450431-53e09180-ac0d-11ea-95b5-4fa7cbf7463c.png)

I am already switched to Linux Containers.
![image](https://user-images.githubusercontent.com/66806548/84450396-3ca1a400-ac0d-11ea-8429-572e7347253e.png)

However, I am running on Windows 10 Home so I do not have the option to unselect "Use the WSL 2 based engine" as in brackets it says "Windows Home can only run the WSL 2 backend". Is there a way to solve this?

![image](https://user-images.githubusercontent.com/66806548/84450610-dbc69b80-ac0d-11ea-9092-a5a928b4e35a.png)

My end goal is to share my c drive on my windows computer to a linux container I am trying to run called madslupe/hddm. This is because when I run my container with the command:

docker run -it --rm -v c:/school/2020_summer_research/analysis_data/dir_of_data_and_notebook/:/home/jovyan/data -p 8888:8888 madslupe/hddm jupyter notebook

I get a URL which I open to an interface of Jupyter Notebook (as expected) and the file folder I open called "data" is empty, where I am expecting it to contain all my data and analyzing scripts.

![image](https://user-images.githubusercontent.com/66806548/84451439-4aa4f400-ac10-11ea-84be-5a0925e3b589.png)

Is this due to the c drive not being shared? Or is this an error relating to mounting in my command line I typed out or something else?

**Comment by stephen-turner** [comment]
Windows 10 Home can only run Docker in WSL 2 mode because Windows 10 Home can't run Hyper-V. But WSL 2 is better anyway. You don't need the file sharing options because all your files are already available to WSL 2.

Your command looks correct to me, assuming you're running it from PowerShell. Does it list the files correctly if you run
```docker run -it -v c:/school/2020_summer_research/analysis_data/dir_of_data_and_notebook/:/home/jovyan/data ubuntu ls /home/jovyan/data```

**Comment by julien-campbell** [comment]
Thank you for the quick reply! I am new to this so I appreciate the help.

So I typed in your command in Windows Powershell and it pulled ubuntu successfully. However, there was nothing after that. 

I ran it again to double check what happens and then it successfully executed without any list of files or any output at all. So I guess this is not the correct response?
