### ISSUE TITLE
Traceroute not working on Docker for Windows Containers

### ISSUE THREAD

**Issue by dynamicdeploy** [docker/for-win#7201]
The command below or any traceroute doesn't work on Linux Containers running on Docker for Windows
**docker run -it alpine traceroute -n www.google.com**
It never resolves

C:\datafiles\onerowconsole>docker run -it alpine traceroute -n www.google.com
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
df20fa9351a1: Pull complete Digest: sha256:185518070891758909c9f839cf4ca393ee977ac378609f700f60a771a2dfe321
Status: Downloaded newer image for alpine:latest
traceroute to www.google.com (172.217.5.100), 30 hops max, 46 byte packets
1 172.17.0.1 0.013 ms 0.006 ms 0.006 ms
2 * * *
3 * * *
4 * * *
5 * * *
6 * * *
7 * * *
8 * * *

goes on..

**Comment by stephen-turner** [comment]
Thanks for the report. This issue is upstream, in vpnkit (moby/vpnkit#194). As you discovered, they fixed it for ICMP and UDP, but not for TCP.
