### ISSUE TITLE
Crash after enforced WSL kernel upgrade

### ISSUE THREAD

**Issue by PavelSosin-320** [docker/for-win#7204]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID:  1695A9B2-5AAE-4023-953F-F08D7698FC5A/20200612062239

### Expected behavior
Docker desktop startup after WSL Kernel upgrade
### Actual behavior
Crash
### Information

  - Windows Version:
  - Docker Desktop Version: latest
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No\ 
Plain Win 10 2004 build 19645.1
### Steps to reproduce the behavior
![Docker Desktop crash](https://user-images.githubusercontent.com/54495912/84476334-a4500180-ac96-11ea-993e-ff5af22f2a35.png)

  1. ... Upgrade WSL kernel from the Microsoft store following the notification
  2. ... Restart Windows

Hint : 
WSL starts with own IP
C:\Users\Pavel>wsl -u root
Welcome to Ubuntu 20.04 LTS (GNU/Linux 4.19.104-microsoft-standard x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Fri Jun 12 09:46:04 IDT 2020

  System load:  0.0                Processes:             8
  Usage of /:   0.9% of 250.98GB   Users logged in:       0
  Memory usage: 0%                 IPv4 address for eth0: 172.21.117.171
  Swap usage:   0%

**Comment by simonferquel** [comment]
@Benhillis we have received multiple feedback about users that get the "Kernel update is required error" when running `wsl --import`  even after having installed it.

**Comment by benhillis** [comment]
Any reports on 2004 or just insider builds?  This issue should be resolved in the next Insider build.

**Comment by simonferquel** [comment]
Just insider, thanks !

**Comment by gagneet** [comment]
As a workaround to get Docker working on a Windows Insider build.
- Uninstall Docker and WSL 2 kernel.
- Go to the Control Panel -> Programs -> Turn Windows features on or off
- Uncheck the following: Containers, Hyper-V, Windows Subsystem for Linux
- Restart the system
- Install Docker without the WSL2 enabled/checked in the first screen
- Go to the Control Panel -> Programs -> Turn Windows features on or off
- Turn on/check the Windows Subsystem for Linux
- Restart the system.

Do not install the WSL2 Kernel.

Docker should be up and running :-)

**Comment by agate-pris** [comment]
I had the same problem in my environment. Thanks.
