### ISSUE TITLE
DOcker does not start on Windows 10

### ISSUE THREAD

**Issue by rakeshzaveri** [docker/for-win#721]
### Expected behavior
Start Docker
### Actual behavior
Error: Hardware assisted virtualization and data execution protection must be enabled in the BIOS. See https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization-must-be-enabled

### Information
Windows 10
Virtualization  enabled (Task Manager)

BIOS:
Intel (R) Virtualization Technology [Enabled]
Intel (R) VT-d Feature [Enabled]

Tried: 
Disable Hyper-V >> Shutdown >> Start >> Start Docker (will ask to start HyperV) >> Start Hyper-V >> shotdown >> Start Windows >> start docker ---- Same error

### Steps to reproduce the behavior
Start Windows >> Docker Popup shows asking to Start docker >> Start Docker and after few min shows this error.

Thankyou!!

**Comment by rakeshzaveri** [comment]
This is the error I get now:
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Failed to create the virtual hard disk.

The system failed to create 'C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx'.

Failed to create the virtual hard disk.

The system failed to create 'C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx': The file exists. (0x80070050).
at New-MobyLinuxVM, <No file>: line 218
at <ScriptBlock>, <No file>: line 381
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

What could be the issue?
TIA

**Comment by macroting** [comment]
I got the totally same issue:Failed to create the virtual hard disk...
Do you get any solution for this error, why the issue is closed?
Thanks! @rakeshzaveri
