### ISSUE TITLE
Kubernetes accessibility from another Hyper-v VM

### ISSUE THREAD

**Issue by birinderjagdev** [docker/for-win#7218]
### Information
  - Windows Version: Windows 10 v1809 (17763.1192)
  - Docker Desktop Version: 2.3.0.3 (45519)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No
  
I have 2 VMs in Hyper-V:
- **DockerDesktopVM** -> default docker desktop VM
	- I have kubernetes enabled in DockerDesktop and it has generated KUBECONFIG file at C:/Users/<profile>/.kube/config
- **dev-centos** -> another Centos VM that I created. 
	- CentOS VM is attached to an internal NATSwitch.
	- Created a NAT network using `New-NetNat` command in Powershell.
	- VM is configured with static IP and manual DNS entry to get internet access.
	- Installed kubectl utility on CentOS.

| Name | Value|
| ---------------------- | ----------------- |	
| Windows Ethernet IP |  192.168.0.20 (ping-able from CentOS)|
| CentOS VM IP| 		 10.0.76.10|
| Kubernetes API|		 https://127.0.0.1:6443 (DockerDesktop's magic proxy)|

### Expected behavior
- Copy KUBECONFIG file inside CentOS
- Add `192.168.0.20 kubernetes.docker.internal` entry in /etc/hosts file

`kubectl get pods` should work

### Actual behavior
```
[root@dev-centos tools]# kubectl get pods
The connection to the server kubernetes.docker.internal:6443 was refused - did you specify the right host or port?
```

Is there any way I can access the kubernetes cluster from another hyper-V VM ?

**Comment by yevgenykuz** [comment]
I encountered something similar (with a slightly different setup).
Had to resort to creating a manual proxy on your windows main host, something like:
`netsh interface portproxy add v4tov4 listenport=6443 connectaddress=127.0.0.1 connectport=6443 listenaddress=___IP_you_can_access_from_your_vm_i.e:192.168.0.20___ protocol=tcp
`

**Comment by birinderjagdev** [comment]
Amazing suggestion, creating a proxy worked as you described. Thanks @yevgenykuz !!!
