### ISSUE TITLE
help in 2017

### ISSUE THREAD

**Issue by AVeliz** [docker/for-win#722]
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...1ADE4E90-8100-43FE-9F17-0049322BEE1F/2017-05-09_14-11-36
  2. ...

**Comment by friism** [comment]
Please add more details on what's going on.
