### ISSUE TITLE
docker failed to start with wsl-2 on windows home

### ISSUE THREAD

**Issue by dhruvsakalley** [docker/for-win#7223]
- [ x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x ] I have uploaded Diagnostics
  - Diagnostics ID: 0D929B51-940D-405F-B181-0EB45E81D0CA/20200613005001

### Information

  - Windows Version: Windows 10 Home build 10.0.19041
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by gagneet** [comment]
As a workaround to get Docker working on a Windows Insider build.
- Uninstall Docker and WSL 2 kernel.
- Go to the Control Panel -> Programs -> Turn Windows features on or off
- Uncheck the following: Containers, Hyper-V, Windows Subsystem for Linux
- Restart the system
- Install Docker without the WSL2 enabled/checked in the first screen
- Go to the Control Panel -> Programs -> Turn Windows features on or off
- Turn on/check the Windows Subsystem for Linux
- Restart the system.

Do not install the WSL2 Kernel.

Docker should be up and running :-)

**Comment by dhruvsakalley** [comment]
Hi Gagneet,
Thank you for your response. I'm specifically interested in using Docker with WSL2 because I want GPU passthrough. Also I'm not on windows insider build, I'm going with the general distribution. I'll wait for a proper fix.
