### ISSUE TITLE
Docker for windows not working!

### ISSUE THREAD

**Issue by navjots35** [docker/for-win#7226]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by gagneet** [comment]
As a workaround to get Docker working on a Windows Insider build.
- Uninstall Docker and WSL 2 kernel.
- Go to the Control Panel -> Programs -> Turn Windows features on or off
- Uncheck the following: Containers, Hyper-V, Windows Subsystem for Linux
- Restart the system
- Install Docker without the WSL2 enabled/checked in the first screen
- Go to the Control Panel -> Programs -> Turn Windows features on or off
- Turn on/check the Windows Subsystem for Linux
- Restart the system.

Do not install the WSL2 Kernel.

Docker should be up and running :-)

**Comment by navjots35** [comment]
Thanks buddy! I'll try this out.
