### ISSUE TITLE
Docker does not start

### ISSUE THREAD

**Issue by rodoaravena** [docker/for-win#7232]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 9CA07F44-65AF-41AC-B0B1-3FEC58C4310C/20200613204552

### Expected behavior
Start Docker
### Actual behavior
Cannot stop from un an unstable state
### Information

Please, help us understand the problem.  For instance:
  - Is it reproducible? Every time a Itry to start docker
  - Is the problem new? Yes
  - Did the problem appear with an update? No
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.

  - Windows Version: Windows 10, 2004
  - Docker Desktop Version: v19.03.8
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: WSL2

**Comment by gagneet** [comment]
As a workaround to get Docker working on a Windows Insider build.

Uninstall Docker and WSL 2 kernel.
Go to the Control Panel -> Programs -> Turn Windows features on or off
Uncheck the following: Containers, Hyper-V, Windows Subsystem for Linux
Restart the system
Install Docker without the WSL2 enabled/checked in the first screen
Go to the Control Panel -> Programs -> Turn Windows features on or off
Turn on/check the Windows Subsystem for Linux
Restart the system.
Do not install the WSL2 Kernel.

Docker should be up and running :-)

**Comment by rodoaravena** [comment]
I have not installed the Insider Build btw, I had to uninstall Docker and delete WSL2 Docker Distros. The status of that distros was "installing" , it was so weird, because a few weeks ago worked flawlessly but suddenly stop working, maybe was an failed update.
Anyway, I tried your solution @gagneet in another PC and works fine! :) Thanks!
