### ISSUE TITLE
'MobyLinuxVM' failed to start worker process: Windows cannot verify the digital signature for this file. 

### ISSUE THREAD

**Issue by bluevulpine** [docker/for-win#724]
### Expected behavior

Docker starts.

### Actual behavior

Docker fails to start. The "An error occurred" screen appears with the following:

Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID EB300E9A-1E3A-4BD4-8AA1-5CBF11D791E3)

'MobyLinuxVM' failed to start worker process: Windows cannot verify the digital signature for this file. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source. (0xC0000428). (Virtual machine ID EB300E9A-1E3A-4BD4-8AA1-5CBF11D791E3)
at Start-MobyLinuxVM, <No file>: line 287
at <ScriptBlock>, <No file>: line 382
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

This began appearing today after docker updated to the latest edge version 17.05.0-ce-win9.

Attempted fixes so far:

1. Restarting docker.
2. restarting windows, 
3. resetting docker to factory defaults, 
4. uninstalling and reinstalling edge. 
5. Uninstalling and returning to stable.
6. deleting the MobyLinux VM out of Hyper-V. 

I have currently reinstalled this edge version:

Version 17.05.0-ce-win9 (11965)
Channel: edge
ef1b7b6

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
79C8C019-D07C-44BA-8675-3D4F91E6CBCA/2017-05-09_16-40-46

  - host distribution and version (Windows version, build number, etc)
Windows 10 Pro
Version 1703 (OS Build 15063.250)

**Comment by bluevulpine** [comment]
It's starting to look like Hyper-V is completely hosed. I'm not clear on how it became broken at the same moment I installed ce-win9, but no VMs will start. It sounds like I'm not the only one in my company that has had Hyper-V implode some random amount of time after installing the Creators Update, and the only solution anyone has found so far is to have their workstation re-imaged. I'm still unclear as to how, why, or even if the Docker update triggered this, but the problem definitely extends outside of Docker at this point.

**Comment by toddysm** [comment]
I am suddenly experiencing the same issue after having Docker running on my machine for a while. I am not even able to see the VM in the list of VMs on Hyper-V. The two major things that happened between the working and non-working state are:

1. Installing Windows Creative Update
2. Installing SentinelOne agent

It doesn't seem to be Hyper-V because I am able to run other VMs. Any ideas?
