### ISSUE TITLE
Unable to update docker to version 17.0.5.0-ce-win9(11965)

### ISSUE THREAD

**Issue by alefesta** [docker/for-win#725]
### Expected behavior
Docker should be udpated to the latest version without errors
### Actual behavior
It stops at the end of download because Windows version minimum requirement are not met
### Information

I have the following version:
Major  Minor  Build  Revis
-----  -----  -----  -----
10     0      15063  0
From the logs I see also:
S: Windows 10 Enterprise N
Edition: EnterpriseN
Id: 1703
Build: 15063
BuildLabName: 15063.0.amd64fre.rs2_release.170317-1834

The installation stop with the error:
Docker for Windows requires Windows 10 Pro or Enterprise version 10586
Could be that the error is related to my version that is a version N and for some reason do not expose correctly the build number to the installer? 

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by simonferquel** [comment]
Hi, next Edge build should resolve the issue, thanks for reporting

**Comment by tparikka** [comment]
Ran into the same issue. In case it's useful, I am on Windows 10 Enterprise 2016 LTSB Version 1607 OS Build 14393.1198.
