### ISSUE TITLE
Docker on Windows failed to Start Post windows restart.

### ISSUE THREAD

**Issue by Mahes-P** [docker/for-win#7252]
[service.29.txt](https://github.com/docker/for-win/files/4779580/service.29.txt)
[log.txt](https://github.com/docker/for-win/files/4779581/log.txt)
[service.txt](https://github.com/docker/for-win/files/4779583/service.txt)
[service.25.txt](https://github.com/docker/for-win/files/4779584/service.25.txt)
[service.26.txt](https://github.com/docker/for-win/files/4779587/service.26.txt)
[service.27.txt](https://github.com/docker/for-win/files/4779588/service.27.txt)
[service.28.txt](https://github.com/docker/for-win/files/4779589/service.28.txt)

  - [Y] I have uploaded Diagnostics
  - Diagnostics ID: F2652C0B-1012-4D11-9499-ECF22C787342/20200612134340

### Expected behavior
- Docker Should have started normally post login.
### Actual behavior
- Docker was not started post login , and it was showing error as "an error occurred".

### Information

Please, help us understand the problem.  For instance:
  - Is it reproducible? No idea , as we encounter part of crash.
  - Is the problem new? Yes sw it for first time.
  - Did the problem appear with an update?
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.

  - Windows Version: Windows10 Pro
  - Docker Desktop Version: Version: 2.1.0.5 (40693)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: NO

### Steps to reproduce the behavior
NA

When we logged in found System was restarted 2 days back,.
Docker was supposed to come up once we logged to the machine. But  We saw it in "Failed to start mode". Attached Diagnostic ID and the logs are updated part of it.

**Comment by moeinrahimi** [comment]
looks like many people have this issue recently, this needs to get fixed ASAP!
