### ISSUE TITLE
Permission Denied when access a mounted directory after waking the PC.

### ISSUE THREAD

**Issue by oziroe** [docker/for-win#727]
### Expected behavior

I expect that everything is OK.

### Actual behavior

Sometimes a docker run command with a `-v` parameter will fail. It doesn't matter which dir do you mount into guest system and where is it mounted. The fail message is messy and contains "Permission Denied" to access the host dir's path. Everything is OK after restarting docker server.

This bug ofter happened when the computer falled asleep and I woke it up, and the docker server keeps running during the sleeping. The bug never disappear without a restarting. Sometime the bug also happens without sleeping.

Even for a running container, the bug happens, too. "Permission Denied" also appears in the error message of the thread in the container, but the denied path is the mounted path in guest instead.

### Information

  - Diagnostic ID: FCFAF1B9-CF83-4B7A-8AB2-29A19C2E7000/2017-05-10_18-26-02
  - a reproducible case: decleared very clearly as above. Here comes the docker file.
```Dockerfile
FROM ubuntu
RUN sed -i "s/archive.ubuntu.com/mirrors.xjtu.edu.cn/g" /etc/apt/sources.list
RUN apt update && apt install -y mit-scheme
WORKDIR /code
CMD scheme
```
The sed command is not important for reproducing in my opinion.

This is the command I use to build/start the container
```bash
winpty docker build . -t oziroe/scheme
winpty docker run --rm -it -v /$(pwd)/code:/code oziroe/scheme
```
I run these in Git Bash(MinTTY), that's what the slash before `$(pwd)` for.

Notice: the `code` dir in host is exist before running docker run command.
  - host distribution and version
    - Macbook Pro 13', late 2013.
    - Windows 10 Pro, build 1703
    - dual boot with macOS 10.12
    - Docker version: 17.03.1-ce-win5 (10743)

### Steps to reproduce the behavior

As above.

**Comment by oziroe** [comment]
I have updated my docker to 17.03.1-ce-win10 (11972), and the bug is still there.

I captured a screenshot for it:

![default](https://cloud.githubusercontent.com/assets/17892607/25933993/d49ccfac-364d-11e7-9e69-bf89e30adfe7.PNG)

The first `docker run` shows a typical instance of this bug, and the second is executed after I restarted docker server, and it is a normal error. After I change to home dir, the command ran successfully at the third time, as scheme REPL shows up.

The same error will be raised as the first `docker run` if I am under a dir in my home dir. Because the path contains some Chinese characters MinTTY can not display it correctly so I didn't show the bug in my home dir, but it happens as well.

**Comment by jasonterando** [comment]
I've been getting this periodically on Windows 10.  Another related symptom is you get the "firewall blocking" error when you try and share your drive.  Somebody else came up with a workaround, go into "Network and Sharing Center", access any NIC's properties and uninstall and reinstall the "File and Printer Sharing for Microsoft Networks".  Almost all of the time, this "fixes" the issue without a reboot or even a Docker restart.

**Comment by oziroe** [comment]
Thanks. I have tried your advice and the bug just shown up after that. I am restarting docker and hoping it not happening any more.

**Comment by oziroe** [comment]
I'm sorry to say that after doing as @jasonterando said the problem is still there. Even more, it seems to be more frequently...

I hope it will be fixed as soon as possible.

**Comment by wang9563** [comment]
I hope it will be fixed as soon as possible too.

**Comment by mp-whoellinger** [comment]
Problem still exists in 17.09.0-ce-win33 with latest Windows 10.
