### ISSUE TITLE
WSL Docker failing after mount

### ISSUE THREAD

**Issue by AaronNBrock** [docker/for-win#7271]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: EBA6B3A7-A48A-4E56-A16C-6F16E8011507/20200616111745

### Expected behavior
From WSL being able to the following command twice
```bash
docker run --rm -it -v /:/mnt/host/ ubuntu
```

### Actual behavior
The second time it's run I get the following message:
```
The command 'docker' could not be found in this WSL 2 distro.
We recommend to activate the WSL integration in Docker Desktop settings.

See https://docs.docker.com/docker-for-windows/wsl/ for details.
```

### Information
I'm trying to mount the filesystem since I use docker as my shell.  I've tried both Edge & Stable.

  - Windows Version: 19041
  - Docker Desktop Version: 2.3.1.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Running within WSL

### Steps to reproduce the behavior

  1. Open WSL
  2. Run:
    ```bash
    docker run --rm -it -v /:/mnt/host/ ubuntu
    ```
  3. Exit the shell
  4. Run the command again

**Comment by Kevinrob** [comment]
Same issue here.

And:
```
kevin@home:/mnt/wsl/docker-desktop/cli-tools$ ls -la
total 0
drwxr-xr-x 2 root root  40 Jun 17 14:16 .
drwxr-xr-x 4 root root 100 Jun 17 14:16 ..
```
