### ISSUE TITLE
Docker does not start after 17.05.0 update on Windows 10 Pro with Creator Update

### ISSUE THREAD

**Issue by gimmemoore** [docker/for-win#729]
### Expected behavior
Docker on Windows 10 Cretor Edition starts properly after update 
Version 17.05.0-ce-win9 (11965)
Channel: edge
ef1b7b6

### Actual behavior
Docker does not start and gives the following error  if the checkbox 'Expose deamon on tcp://localhost:2375 without TLS' is uncheck. It is unchecked following the update to 17.05.0-ce-win9 (11965)

```
error during connect: Get http://127.0.0.1:2375/v1.29/containers/json: dial tcp 127.0.0.1:2375: connectex: No connection could be made because the target machine actively refused it.

   at Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

### Information

  - **Diagnostic Id** : E2C88AC3-A986-4B79-B00D-F4A810EE99CC/2017-05-10_09-15-12
  - Install update 17.05.0-ce-win9 (11965)
  - Docker will attempt to restart and fail
  - Windows 10 Pro Version 1703 OS Build 15063.296

**Comment by friism** [comment]
Can you provide more details on your setup and what's trying to connect to Docker? Is this the error shown by Docker for Windows?

You might want to try a factory reset.

**Comment by gimmemoore** [comment]
Yes the error is shown by Docker for Windows in a popup window.

I did try a factory reset, and every time I run into the same error.

I manage to fix it by going to the setting and checking the Expose deamon on tcp://localhost:2375 without TLS

**Comment by friism** [comment]
Can you see if you've set the `DOCKER_HOST` environment variable?

**Comment by gimmemoore** [comment]
It was set ':2375' (according to the microsoft ssh instruction for Azure Container Services with Swarm as Orchestrator)

**Comment by friism** [comment]
@gimmemoore and it works if you remove the environment variable?

**Comment by gimmemoore** [comment]
@friism removing the environment variable does not solve the problem. I get the same error after removing it and unchecking the 'Expose deamon on tcp://localhost:2375 without TLS' checkbox.

**Comment by duizendnegen** [comment]
Just wanted to chime in and confirm that checking "Expose deamon on tcp://localhost:2375 without TLS" makes Docker start on Windows 10.
