### ISSUE TITLE
Windows Containers can't access internet

### ISSUE THREAD

**Issue by danswain** [docker/for-win#7292]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 7400AC13-7B14-4269-A47E-6506275529D7/20200617143041

### Expected behavior
A response from google.com
### Actual behavior
Ping request could not find host www.google.com. Please check the name and try again
### Information

  - Windows Version: Windows 10 Pro - Version - 1903 - OS Build 18362.836
  - Docker Desktop Version: 2.3.0.3 (45519)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: 

No, this is native Windows 10 on a Dell XPS Laptop.. I do have a company VPN installed. And have HyperV installed. No proxy servers configured.

The thing that's weird is that if I "switch to Linux containers" it works fine.. it's just Windows Containers (which unfortunately is what I need).

### Steps to reproduce the behavior

  1. docker run -it mcr.microsoft.com/dotnet/framework/sdk:4.8 ping "www.google.com"
  2. (see Expected ie a Ping response)
  3. Actual is it can't resolve the host.

Thanks for any help.

**Comment by Hish15** [comment]
Are you on a corporate network or at home?
In my case, I can not ping from the office. I mean even the host PC can not ping.
