### ISSUE TITLE
Docker Desktop failed to stop

### ISSUE THREAD

**Issue by 80220** [docker/for-win#7295]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 5488E46D-A66C-4943-AE2E-47C7907F05DC/20200617150350

### Actual behavior

Can not start docker [desktop](url)

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by 80220** [comment]
I noticed that even though I uninstall docker destop it is stilll left hanging under wsl2 distros:
```
PS C:\WINDOWS\system32> wsl --list --verbose
  NAME              STATE           VERSION
* Ubuntu-20.04      Running         2
  Ubuntu-18.04      Stopped         1
  docker-desktop    Installing      2
PS C:\WINDOWS\system32> wslconfig /l
Windows Subsystem for Linux Distributions:
Ubuntu-20.04 (Default)
Ubuntu-18.04
PS C:\WINDOWS\system32>
```

**Comment by 80220** [comment]
Close it, i fixed it by unregistrering docker-desktop
`PS C:\WINDOWS\system32> .\wslconfig.exe /u docker-desktop`

**Comment by stvnksslr** [comment]
this also works 
`wsl --unregister docker-desktop`

**Comment by pengyue** [comment]
> this also works
> `wsl --unregister docker-desktop`

This actually works better for me, the command `PS C:\WINDOWS\system32> .\wslconfig.exe /u docker-desktop` gave me `Access is denied` error even if it runs with as administrator.

**Comment by jazzfog** [comment]
> this also works
> `wsl --unregister docker-desktop`

Thanks this has helped.

Also for context: `--unregister` - "Unregisters the distribution."

You can see your distributions by running `wsl -l -v`

```
D:\web>wsl -l -v
  NAME                   STATE           VERSION
* Ubuntu-20.04           Running         2
  docker-desktop         Running         2
  docker-desktop-data    Running         2
```

**Comment by eliseuborges** [comment]
Nice! It works for me.

**Comment by ryannmedina** [comment]
Thank you! This fixed it for me too!
