### ISSUE TITLE
Enable expose daemon on tcp://localhost:2375 option disables the daemon 

### ISSUE THREAD

**Issue by tradercentric** [docker/for-win#7307]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version: Windows 10
  - Docker Desktop Version: 2.3.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No. Just Hyper-V

### Steps to reproduce the behavior

The only reason I need to expose the daemon is for Jetbrain's Docker connection

  1. ...  Enable expose daemon on tcp://localhost:2375 option, agree to restart.
  2. ... Go to command prompt, enter "docker container ls"

Here is the the error output:
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

**Comment by stephen-turner** [comment]
In the latest Edge release, 2.3.2.0, we have improved this so that application startup is no longer blocked when port 2375 is in use, and a toast notification pops up instead.
