### ISSUE TITLE
Docker daemon doesn't listen to port 2375 although it is configured in Windows WSL2

### ISSUE THREAD

**Issue by PavelSosin-320** [docker/for-win#7308]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
WSL 2 integration on Windows 10 2004 allows connection via host IP or WSL VM IP and port 2375
### Actual behavior
Integration with WSL 2 is totally broken:

### Information

  - Windows Version: 2005 dev pre-release
  - Docker Desktop Version: 2.3.1.0 (45408) Edge
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No
docker --debug info
Output:
```
DEBU[0000] FIXME: Got an status-code for which error does not match any expected type!!!: -1  module=api status_code=-1
Client:
 Debug Mode: true
Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
errors pretty printing info
```
### Steps to reproduce the behavior

  1. Config WSLIntegration with Ubuntu 20.04 distro
  2. ...Try to use get some info about docker instance using docker info
There is no connection to Docker via docker.sock
  3.  Check used context docker context ls:
```
docker context ls
NAME                DESCRIPTION                               DOCKER ENDPOINT               KUBERNETES ENDPOINT                                 ORCHESTRATOR
**default *           Current DOCKER_HOST based configuration   unix:///var/run/docker.sock**   https://kubernetes.docker.internal:6443 (default)   swarm
docker-test                                                   unix:///var/run/docker.sock                                                       swarm

```
I suppose that interaction between WSL2 distros is via Unix sock is impossible any more because distros don't share filesystems in WSL2 and every distro has own /var/run
The generated context is incorrect!

From the other hand, this mechanism is redundant: Distro has own IP but Docker daemon doesn't listen on the non-tls port:
wsl -d docker-desktop -u root ss -tulpn
```
Netid       State         Recv-Q         Send-Q                  Local Address:Port                 Peer Address:Port
tcp         LISTEN        0              128                         127.0.0.1:6443                      0.0.0.0:*            users:(("wsl-bootstrap",pid=15,fd=13))
tcp         LISTEN        0              128                                 *:5000                            *:*            users:(("wsl-bootstrap",pid=15,fd=11))
tcp         LISTEN        0              128                                 *:3306                            *:*            users:(("wsl-bootstrap",pid=15,fd=8))
tcp         LISTEN        0              128                                 *:5005                            *:*            users:(("wsl-bootstrap",pid=15,fd=12))
tcp         LISTEN        0              128                                 *:220                             *:*            users:(("wsl-bootstrap",pid=15,fd=10)
```
---------------------------------------------
All containers/services are published to WSL Distro VM as expected but Daemon itself doesn't listen any port.
Since all WSL ports are propagated to the Windows host all containers are visible.
If the dockerd running inside Dockerdesktop distro will listen to port 2375 it will be accessible on Windows port 2375  using TCP: protocol.  But not the localhost of Ubuntu!

**Comment by stephen-turner** [comment]
Any comments, @simonferquel?

**Comment by PavelSosin-320** [comment]
@simonferquel After testing Docker API I found that the is obviously at the Linux client's side. From the Windows command shell, Docker running inside WSL2 distro is available at localhost and responses as described in HTTP API spec . on curl HTTP request. But integration with WSL distro doesn't offer the correct CLI version or CLI's or client-side configuration via the correct Docker context.
It looks problematic because autogenerated WSL config files look not like I expect.

**Comment by justinkb** [comment]
You wanna disable that UI option anyway and expose the daemon via a secure https server by employing a docker socket proxy container

**Comment by PavelSosin-320** [comment]
It means that the assumption is that Integration with WSL distro means mapping of Distro's user profile/ssh is mapped to Windows user profile/ssh. Otherwise how curl can and Docker CLI get the user's ssh keys? Hopefully, you don't suggest generating keys for every available distro separately  The are already 10 WSL2 available distros today and I installed 5 of them. 
The problem is that generated by the default Windows docker client config is blank - contains nothing for cross WSL2 distros connection. 
And finally, neither tcp 2375 nor 2376 is exposed on the Windows host - Docker desktop proxy doesn't do it on the correct network or listens to something different that 0.0.0.0  i.e. listens to all interfaces including Eth0 of distro - see WSL 2 documentation.
`{"auths":{"https://index.docker.io/v1/":{}},"credsStore":"desktop","experimental":"enabled","stackOrchestrator":"swarm"}`
I also hope that I don't need to install all CLIs in every distro and can use Windows CLI in WSL 2 interop mode as it is offered by today's Windows - it works for me.
For Kubernetes I simply created. symlink to kubeconfig. I can't do it for docker because of cross-WSL2 distro communication requires separate Docker context entries for  TCP and socket protocols.
Unfortunately,

**Comment by PavelSosin-320** [comment]
@stephen-turner  How docker.proxy connected to the Docker network can help me - it proxies traffic from overlay network or host to containers through the docker networks but daemon itself is not connected to these networks. All containers ports are exposed on my Windows/WSL2 host OK using any possible method. Daemon is exposed to the Windows/WSL2 host via daemon.sock in the /run/host-sockets. This socket is visible via  /mnt/wsl/docker-desktop/docker-desktop-proxy. But it gives me nothing - this is a regular file, not a tcp socket. If it is not tcp WSL2 doesn't propagate it to the Windows host.
I tried to add TCP host to the daemon configuration but then Docker stopped to start.
I expect that "expose daemon via tcp port 2375 works sounds exactly as it sounds,  both daemon and CLI configuration are updated and Docker starts listening TCP ports 2375 and 2376 without and with TLS.
Kubernetes works because its API is exposed by API server pod via TCP port.

**Comment by simonferquel** [comment]
You don't need to enable TCP exposition to have WSL integration work. When you enable integration with your distro in Docker Desktop settings, we run a proxy within your distro that expose the daemon on /var/run/docker.sock. It also does some magic: handling bind mounts so that you can mount files from your distro without having to rely on nfs or any remote file system, port exposition within wsl2 etc.

All you need to do is to enable integration with your WSL2 distro in the settings.

**Comment by PavelSosin-320** [comment]
I did it and it doesn't help. It doesn't cause docker daemon to listen to the Windows host IP. I think it is impossible by WSL 2 design - the WSL VM network is bridged to the Host network via WSL2 bridge. There are numerous discussions about it but only one solution. I made  simple exercise with Nodejs server running inside WSL VM and found that it is listening to:
Starting up http-server, serving 
  http://127.0.0.1:8080 - localhost for the VM insiders
  http://172.17.245.1:8080 - WSL Adapter IP which it got from the Windows Host -for the Windows processes, like browser. What is strange is how these ports are represented by ss from the Linux side: [::ffff:172.17.245.1]:35293. Looks like IPV6 ????
Indeed I expected docker.proxy and even saw it in some previous Docker Desktop versions but later it disappeared. Proxy is always a good thing. I asked once how to configure it for the WSL2 scenario but never got an answer.

**Comment by simonferquel** [comment]
Docker desktop with wsl don't use TCP to integrate with your distro (it uses the cross distro share that is mounted in /mnt/wsl by default and uses Unix sockets).
Can you send a diagnostic file so that I can better understand what happens?

**Comment by PavelSosin-320** [comment]
Happens expected thing - socket is peer-to-peer connection. it's enough to open 2 different distros and only 1 continues to work, even not in parallel, sequentially. Socket is intra-VM solution by definition, especially if it is created in unix:///var/run/docker.sock - Every distro has its own folder  /var/run. docker CLI tries to open it in own /var/run and says:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
There is shared subtree in every distro /mnt/wsl/docker-desktop/shared-sockets
/mnt/wsl/docker-desktop/shared-sockets
guest-services  host-services
with no sockets created by Docker daemon.
unix:///mnt/wsl//mnt/wsl/docker-desktop/shared-sockets is not mentioned in any configuration
Everybody today can run wsl -l -v in Windows and see several WSL2 distro running. How Docker daemon can serve them via a single peer-to-peer socket?
