### ISSUE TITLE
Docker Desktop 2.3.0.3 no longer working (Windows)

### ISSUE THREAD

**Issue by fgarcia** [docker/for-win#7309]
This morning docker stopped working on Windows 20.04 and I noticed other issues mentioning problems too. 

1. I tried to reset to factory defaults, but I got an error report this could not be done.
2. I tried to reinstall 2.3.0.3, this did not work
3. I downgraded to 2.3.0.2, this DID work

Before the downgrade the one thing I did notice is that according `wsl -l -v` my `docker-desktop-data` was missing and `docker-desktop` was always under the state of "installing"

Not sure where I should report my findings since there are multiple related issues in the last day

**Comment by julienbalas** [comment]
When using the "troubleshooting" menu, the reset tu factory default works.

**Comment by sivaiahnaidu** [comment]
i was facing the same issue for so many days and I got to notice even after switching to hyper-v it still shows installing, so I tried terminating distro (wsl -t docker-desktop) and it didn't work.
![image](https://user-images.githubusercontent.com/25014275/85079232-e96abb00-b1e3-11ea-80f3-890a18794cbb.png)

So what I have done was, I unregistered the distro (wsl --unregister docker-desktop). then went back to Docker and checked the use WSL2 option and restarted it. it worked and now in 
wsl --list --verbose I got both docker-desktop and docker-desktop-data and the Docker launched successfully without that failed to start error 


![image](https://user-images.githubusercontent.com/25014275/85079492-99402880-b1e4-11ea-8f49-6fd2d28f82fe.png)

PS: I am not a professional , but as I was facing similar issue as it is solved now I though I could help some one. so can you try this and confirm if its working

**Comment by fgarcia** [comment]
for me unregister did not work :(

**Comment by sivaiahnaidu** [comment]
@fgarcia what was the error you got when you try to unregister? 
anyway,try this procedure exactly and let me know if it's working.

1) Uninstall docker and Linux subsystem update(this can be found in the control panel as Windows Subsystem for Linux update)
2) go to Windows features turn off Linux subsystem and turn on hyper-v (Restart)
3)then install docker again - this time don't use WSL use hyper-v for docker this should launch without any issues
4) After everything is working fine, Download the Linux subsystem update from here
https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel
5) this should enable WSL in features by default but check and enable if not
6)restart the system
7)go to docker and now enable WSL2 in the docker settings. this should again cause failed to start/stop issue and the docker icon becomes red
8)now check the list: (Run Poweshell as Admin)
Input: wsl --list --verbose 
output:
you must see smthg like this
NAME              STATE           VERSION
  docker-desktop    Installing      2
9)now close the docker application and run terminate command(idk if this step is imp as the output suggests it didnt change anything but this is the exact procedure i followed and it worked so..)
Input: wsl -t docker-desktop
output: 
There is no distribution with the supplied name.
10)  Unregister the docker application(make sure its closed)
input: wsl --unregister docker-desktop
output: Unregistering...
11)Now check if you can still see docker or not in ths list(if you dont see docker-desktop its a good sign)
input: wsl --list --all
12)Now launch the docker application and it should launch with out the issues
13) you can check this with below command
input: wsl --list --verbose
output: 
NAME                   STATE           VERSION
* Ubuntu-20.04           Running         2
  docker-desktop         Running         2
  docker-desktop-data    Running         2

Hope this is helpfull

**Comment by fgarcia** [comment]
@sivaiahnaidu thanks a lot for the detailed answer, hopefully it will help others. 

As I wrote in the issue, I fixed the problem by downgrading. It is just that 2.3.0.3 does not work for me. Since I can work without problems on 2.3.0.2 I decided to wait for 2.3.0.4 before upgrading.

**Comment by FredyC** [comment]
@sivaiahnaidu Thank you very much, your approach did help me too and everything is working again 💯

**Comment by fgarcia** [comment]
closing this issue because 2.3.0.5 works again for me (not 2.3.0.4 or 2.3.0.3)
