### ISSUE TITLE
ERROR: error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/info: open //./pipe/docker_engine:

### ISSUE THREAD

**Issue by jiangweiatgithub** [docker/for-win#7310]
88319690-8695-4E4D-BD75-2417B0FE97B5/20200618095937

docker info
Client:
 Debug Mode: false

Server:
ERROR: error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

**Comment by Bhavye-Malhotra** [comment]
same issue
