### ISSUE TITLE
WSL2 intergration don't work anymore

### ISSUE THREAD

**Issue by Kevinrob** [docker/for-win#7311]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: F6C2A956-0572-42AF-9C3C-E0FBEEAE0CB1/20200618120038

### Expected behavior
Docker work in WSL2

### Actual behavior
```
kevin@home:~$ docker ps

The command 'docker' could not be found in this WSL 2 distro.
We recommend to activate the WSL integration in Docker Desktop settings.

See https://docs.docker.com/docker-for-windows/wsl/ for details.
```

### Information

  - Windows Version: 19042.330
  - Docker Desktop Version: 2.3.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. open bash
  2. docker ps

**Comment by Kevinrob** [comment]
![image](https://user-images.githubusercontent.com/4509277/85018624-c69dbf80-b16d-11ea-9452-b357b2871564.png)

**Comment by Kevinrob** [comment]
With Edge version 2.3.1.0. I got:
```
WSL distro stopped while waiting for Lifecycle server.
  >Stdout:

  >Stderr:
2020/06/18 12:37:15 resolving /mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-wsl-cli.iso...
Error: mounting wslCLIDest: stat /mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-wsl-cli.iso: no such file or directory
2020/06/18 12:37:15 stat /mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-wsl-cli.iso: no such file or directory
mounting wslCLIDest
main.doRun
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:224
main.run.func1
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:83
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:838
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:943
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).Execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:883
main.main
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1373
```
Crash ID: F6C2A956-0572-42AF-9C3C-E0FBEEAE0CB1/20200618123718

**Comment by kwiniarski** [comment]
I have a very similar problem. Till today everything was working fine, I was able to use `docker` command in PowerShell or bash in WSL exchangeably. However, now `docker` in WSL is not working. It shows:
```
The command 'docker' could not be found in this WSL 2 distro.
We recommend to activate the WSL integration in Docker Desktop settings.

See https://docs.docker.com/docker-for-windows/wsl/ for details.
```
Restarting Docker or WSL does not help. Also unchecking and checking integration with WSL option does nothing. What I have noticed, is that my docker command points to: `/mnt/c/Program Files/Docker/Docker/resources/bin/docker`. But during Docker restart, for a short moment, it points to `/usr/bin/docker` and the command works as expected. But as soon as the restart has been completed, `which docker` points back to `/mnt/c/Program Files/Docker/Docker/resources/bin/docker`.
Symlink under `/usr/bin/docker` is broken as `/mnt/wsl/docker-desktop/cli-tools/` is an empty directory.

I was able to fix this only by reinstalling my WSL Linux distro (reinstalling Docker is not enough). It worked for a while, but after a few docker-compose ups and downs problem has returned.

I'm using edge version 2.3.1.0 (45408) on Windows 10 2004 build 19041.330.
My diagnostic ID: 392C0538-49E0-45AF-996F-43B979EE7649/20200701093512

**Comment by shabbirh** [comment]
I have exactly the same problem, but it exhibits after I remove a docker container (from WSL2) that was created using my distro and in WSL2.

So:

I create the container inside my Ubuntu WSL2 distro:

$ docker run --name blahcontainer blah/blah

then after a while, I am finished with that container, I remove it - again from inside my WSL2 distro:

$ docker rm blahcontainer

immediately after that - docker stops working and I get:

$ docker ps -a

The command 'docker' could not be found in this WSL 2 distro.
We recommend to activate the WSL integration in Docker Desktop settings.

See https://docs.docker.com/docker-for-windows/wsl/ for details.

-- 
This is running on the current stable 2.3.0.3 on Windows 10 (2004) (Clean install not upgraded), and using Ubuntu (MS Store MetaPackage which gives 20.04 LTS).

I managed to get docker back by rebooting (not ideal by any stretch, restarting docker or wsl didn't help), but getting it back after rebooting is hit and miss.

What is interesting is that containers that I had previously (and set to restart-always), continue working perfectly without any issues, but cannot be managed from withing WSL2.  Even though they are WSL2 containers!  I can continue to manage them fine within Powershell.

**Comment by jano42** [comment]
Same problem

- Docker Desktop 2.3.0.4 (46911) / stable
- Windows 10 Version 2004 (19041.388)

**Comment by erikhakansson** [comment]
Same here. Note that Docker Desktop is looking for `/mnt/host/c/...` but the filesystem is mounted at `/mnt/c`

* Docker Desktop 2.3.0.4 (46911)
* Windows 10 Build 20180

**Comment by Kevinrob** [comment]
Always the same issue.

* Windows 10 Professionnel 20H2 - 19042.423
* Docker Desktop 2.3.4.0 46980

![image](https://user-images.githubusercontent.com/4509277/89879535-66525980-dbc3-11ea-8340-70b92b2a6bac.png)

```bash
kevin@DESKTOP:~$ docker ps

The command 'docker' could not be found in this WSL 2 distro.
We recommend to activate the WSL integration in Docker Desktop settings.

See https://docs.docker.com/docker-for-windows/wsl/ for details.

kevin@DESKTOP:~$ which docker
/mnt/wsl/docker-desktop-bind-mounts/Ubuntu-18.04/a5e260e5a708e9bc7beceb8338f3705e6249bccb6c5df38f624e9ae58ea118de/mnt/c/ProgramData/DockerDesktop/version-bin/docker
```

**Comment by pablorq** [comment]
Same problem:

- Docker Desktop v2.3.0.4(46911)
- Windows 10 version 2004 (19041.450)

From Windows:
```
>wsl -l -v
  NAME                   STATE           VERSION
* Ubuntu                 Running         2
  docker-desktop         Running         2
  docker-desktop-data    Running         2

>docker context ls
NAME                DESCRIPTION                               DOCKER ENDPOINT                  KUBERNETES ENDPOINT   ORCHESTRATOR
default *           Current DOCKER_HOST based configuration   npipe:////./pipe/docker_engine                         swarm
```

From WSL2:
```
$ which docker
/c/Program Files/Docker/Docker/resources/bin/docker  
```

**Comment by Kevinrob** [comment]
It's work again with version 2.3.5.1 🎉 (edge)
![image](https://user-images.githubusercontent.com/4509277/91443927-4f269380-e874-11ea-8176-5c1b20591017.png)

**Comment by netsnatch** [comment]
@Kevinrob 
Same problem

Version 2.3.5.1
![Windows PowerShell](https://user-images.githubusercontent.com/11537020/91464634-7477c980-e895-11ea-93c8-7440e70a909e.png)
![image](https://user-images.githubusercontent.com/11537020/91464745-96714c00-e895-11ea-8723-d25664ef070d.png)
![image](https://user-images.githubusercontent.com/11537020/91464799-a4bf6800-e895-11ea-8305-f12c2a0c4508.png)

**Comment by Kevinrob** [comment]
@netsnatch You have to install a separate WSL2 distro like Ubuntu or Debian (from the Microsoft Store)

**Comment by borremosch** [comment]
I recently upgraded from Docker Desktop 2.2.0.5 to 2.3.0.4 when I encountered this error. In my case, I had previously added `/mnt/c/Program\ Files/Docker/Docker/resources/bin/` to my `$PATH` variable in `.bashrc`. Apparantly, this breaks later versions of Docker Desktop. I was able to fix the issue by removing `/mnt/c/...` from my `$PATH` variable.

**Comment by jankalfus** [comment]
Same problem here. I have a separate Ubuntu distro in WSL 2, integration in Docker Desktop enabled, everything was working fine until a few minutes ago. Suddently, "The command 'docker' could not be found in this WSL 2 distro.".

This is obviously an issue with either Docker Desktop or WSL 2 that needs fixing.

Please reopen @Kevinrob
