### ISSUE TITLE
Error during connect , daemon is not working

### ISSUE THREAD

**Issue by ravikittad** [docker/for-win#7317]
error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=dhum9h72lr5tylv1fygv6l9es&shmsize=0&t=tme_drupal_php_7.4-apache-buster&target=&ulimits=null&version=1: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

This is resolved, it is because docker was not insalled properly, Windows Docker Toolbox installed and issue resolved.

**Comment by 849427** [comment]
C:\>docker --version
Docker version 19.03.8, build afacb8b

C:\>docker run hello-world
docker: error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/create: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
See 'docker run --help'.


same issue
