### ISSUE TITLE
docker desktop is not starting on wsl insider build 20150

### ISSUE THREAD

**Issue by mdekoster** [docker/for-win#7319]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A4F0C4D9-1FC7-422B-B4F8-782DE8295A4D/20200619054919

### Expected behavior
Start docker-desktop on WSL2
### Actual behavior
Failed to start on WSL2 (Windows Build 20150)
### Information
  - Windows Version: Insider build 20150
  - Docker Desktop Version: 2.3.1.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

**Comment by gaffneyd4** [comment]
After updating to windows dev build 20150.rs_prerelease.200612-1734 the edge release of docker for windows (with wsl2 engine enabled) would crash on startup.

The error message docker displayed is a wsl2 error message: `WSL 2 requires an update to its kernel component 20150 - more information: https://aka.ms/wsl2kernel`.

I was able to resolve the error by following the instructions there to update the wsl2 kernel, and afterwards docker for windows was able to start successfully.

**Comment by stephen-turner** [comment]
Thanks for the report. @gaffneyd4 has the solution. And it's outside of our control. Closing this ticket.
