### ISSUE TITLE
Cannot start docker desktop on win 10 home 2004

### ISSUE THREAD

**Issue by maxferrario** [docker/for-win#7329]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: DFEACDA5-3247-42F0-AC27-6016F7E75713/20200619151838

### Expected behavior
docker desktop starts
### Actual behavior
docker desktop does not start
### Information

  - Windows Version: win 10 home 2004
  - Docker Desktop Version: 2.3.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: NO

If i click on the red docker icon and click restart I get the following error message:

Docker.ApiServices.StateMachines.InvalidTransitionException:
Cannot stop from an unstable state
   at Docker.ApiServices.StateMachines.UnstableState.Docker.ApiServices.StateMachines.IInternalEngineState.BeginStopAsync() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\UnstableState.cs:line 36
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StopAsync>d__15.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 81
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<RestartAsync>d__29.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:line 272

If i run
docker run -dp 80:80 docker/getting-started
from an elevated prompt I get the error
C:\Program Files\Docker\Docker\resources\bin\docker.exe: error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/create: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by edvardpotter** [comment]
I have the same problem

**Comment by StefanScherer** [comment]
It looks there is a problem with the WSL 2 distros. I see an error `There is no distribution with the supplied name.`

Could you open a PowerShell terminal and run the following commands to check what the current status is?

```
wsl.exe -l -v
```
This should list all WSL distros.

Are you able to run other WSL 2 distros? You could install eg. the Ubuntu distro from the Microsoft Store and run it. But please check that it's running as version 2. To be able to run WSL 2 distros is a requirement to run Docker Desktop on Windows 10 Home. Maybe there is the problem.

We have a document about Docker Desktop and WSL 2 at https://docs.docker.com/docker-for-windows/wsl/

**Comment by JPumpkin** [comment]
I have the same issue.

`PS C:\WINDOWS\system32> wsl.exe -l -v
  NAME              STATE           VERSION
  docker-desktop    Installing      2
PS C:\WINDOWS\system32>`

**Comment by maxferrario** [comment]
Hi Stefan, 
the output of `wsl.exe -l -v` is

> \> wsl.exe -l -v
>   NAME              STATE           VERSION
> * Ubuntu-20.04      Stopped         2
>   docker-desktop    Installing      2

Does the "Installing" status mean that something went wrong during the installation?

BTW, Ubuntu does run correctly on my PC:

> \> wsl.exe
> Welcome to Ubuntu 20.04 LTS (GNU/Linux 4.19.104-microsoft-standard x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
>   System information as of Sun Jul 26 06:34:43 CEST 2020
> 
>   System load:  0.0                Processes:             8
>   Usage of /:   0.5% of 250.98GB   Users logged in:       0
>   Memory usage: 1%                 IPv4 address for eth0: 172.30.243.151
>   Swap usage:   0%

**Comment by StefanScherer** [comment]
Hi @maxferrario,
Thanks for the details. Yes, the installing state indicates a problem. 

Stop Docker Desktop and run `wsl.exe --unregister docker-desktop` and then start Docker Desktop again. 
We‘re working on a fix for the Stable release which we already have in the Edge release.

**Comment by maxferrario** [comment]
Hi @StefanScherer,
Docker Desktop is running now: thanks a lot for your help!
