### ISSUE TITLE
Failed to deploy distro docker-desktop

### ISSUE THREAD

**Issue by georgemih** [docker/for-win#7345]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - The same problem exists with the Edge version
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C769EEE0-6D7F-4BA7-95DE-AA2B2528D549/20200621050318

### Expected behavior
Docker launches for the first time
### Actual behavior
The process stops, an error occurred  and the taskbar icon becomes red.
### Information
I tried reinstalling docker and the same problem occurred. 
 Here is the error message:
`System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\georg\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: �� 
stderr: 
   σε Docker.Core.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) στο C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\WslCommand.cs:γραμμή 119
   σε Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__16.MoveNext() στο C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:γραμμή 142
--- Τέλος ιχνηλάτησης στοίβας από προηγούμενη θέση όπου δημιουργήθηκε μια εξαίρεση ---
   σε System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   σε System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   σε Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__6.MoveNext() στο C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:γραμμή 44
--- Τέλος ιχνηλάτησης στοίβας από προηγούμενη θέση όπου δημιουργήθηκε μια εξαίρεση ---
   σε System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   σε System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   σε Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__23.MoveNext() στο C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:γραμμή 91
--- Τέλος ιχνηλάτησης στοίβας από προηγούμενη θέση όπου δημιουργήθηκε μια εξαίρεση ---
   σε System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   σε System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   σε Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() στο C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:γραμμή 29
--- Τέλος ιχνηλάτησης στοίβας από προηγούμενη θέση όπου δημιουργήθηκε μια εξαίρεση ---
   σε System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   σε System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   σε Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() στο C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:γραμμή 67
--- Τέλος ιχνηλάτησης στοίβας από προηγούμενη θέση όπου δημιουργήθηκε μια εξαίρεση ---
   σε System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   σε Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() στο C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:γραμμή 92
`
![εικόνα](https://user-images.githubusercontent.com/45794467/85220252-aad72b00-b3b2-11ea-98b2-0af868051952.png)

  - Windows Version: Windows 10 home version 2004 (19041.329)
  - Docker Desktop Version: 2.3.0.3 (45519) "stable"
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

**Comment by sapinder** [comment]
https://github.com/docker/for-win/issues/6640

Disabling Hyper-V helped me

**Comment by MHacker9404** [comment]
I'm also getting this error - and disabling hyper-v is not an option for me.

**Comment by settoloki** [comment]
Not helpful, but I'm also experiencing the same issue, and like @MHacker9404 I also attempted to move my distributions to a bigger drive. So I imagine the issue is surrounding that.

https://dev.to/kimcuonthenet/move-docker-desktop-data-distro-out-of-system-drive-4cg2

I have since deleted everything docker related and reinstalled docker desktop
I have disabled Hyper-V 
Removed and reinstalled wsl unbuntu

**Comment by MHacker9404** [comment]
spotted this: [](https://www.bleepingcomputer.com/news/microsoft/windows-10-2004-kb4571756-breaks-windows-subsystem-for-linux-2/)
