### ISSUE TITLE
From PITLORD

### ISSUE THREAD

**Issue by pitlordsuper** [docker/for-win#7352]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by pitlordsuper** [comment]
Thanks

**Comment by stephen-turner** [comment]
No information on what the problem is, closing this ticket.
