### ISSUE TITLE
Docker Desktop - Failed to start DockerDesktopVM windows 10

### ISSUE THREAD

**Issue by anupwarke** [docker/for-win#7353]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version: Window 10 Pro 1909
  - Docker Desktop Version: 2.3.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Start Docker Desktop
  2.

**Comment by anupwarke** [comment]
[Error.log](https://github.com/docker/for-win/files/4809881/Error.log)

**Comment by ggoyal23** [comment]
I am also getting the same behavior. Installed docker latest stable version (2.3.0.3) and it is giving an error on Windows 10 and failed to start.
"Docker.Core.HttpBadResponseException:
Unhandled exception: job failed with message: 'DockerDesktopVM' failed to restore. (Virtual machine ID F297D6A9-607A-4FCC-AD41-82B898CA5111)"

**Comment by anupwarke** [comment]
@ggoyal23 Do you get any way out of this issue?
Thanks

**Comment by anupwarke** [comment]
### **SOLVED**

With lot of google and analysis of the issue, finally i resolved this issue. **_With more analysis to the issue i identified that the issue is not with Docker Desktop_**. When we run the Docker Desktop with Linux container, docker generally creates a VM named "DockerDesktopVM" over Hyper-V which actually provide the linux backend for docker.

The issue was with this VM only. the windows was not able to start this VM even with elevated user access. So i went around the Microsoft logs (Event Viewer) and analyzed the Hyper-V logs for failure. I observed "**_Virtual Machine Worker Process initialization has timed out, and will terminate._**"
`Log Name:      Microsoft-Windows-Hyper-V-Worker-Admin
Source:        Microsoft-Windows-Hyper-V-Worker
Date:          6/22/2020 11:04:30 PM
Event ID:      3062
Task Category: None
Level:         Error
Keywords:      
User:          NT VIRTUAL MACHINE\B090AFBE-5461-4896-8930-599E1D3DD0B8
Computer:      XXXXXX-XXXXXXX
Description:
Virtual Machine Worker Process initialization has timed out, and will terminate.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-Hyper-V-Worker" Guid="{51ddfa29-d5c8-4803-be4b-2ecb715570fe}" />
    <EventID>3062</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2020-06-22T17:34:30.746835200Z" />
    <EventRecordID>147</EventRecordID>
    <Correlation />
    <Execution ProcessID="15884" ThreadID="2924" />
    <Channel>Microsoft-Windows-Hyper-V-Worker-Admin</Channel>
    <Computer><Computer-Name></Computer>
    <Security UserID="X-X-X-XX-X-XXXXXXXXXX-XXXXXXXXXX-XXXXXXXXXX-XXXXXXXXXX" />
  </System>
  <EventData>
  </EventData>
</Event>`

This pointed that windows is getting timed out while starting the VM. So i decided to check the VM starting manually using command line. Microsoft has documented well about the power-shell commands for all features. you can find the commands for starting VM. Reference Doc [here](https://docs.microsoft.com/en-us/powershell/module/hyper-v/start-vm?view=win10-ps)


With command line analysis with Start-VM command, i got to know that there is **AccessDenied** error received for the command. **_Even you create any random VM, windows fails to start_**. I further googled it and tried lot of ways like _VHDX & VMCX files may not have correct permission_, _add the permission to these files with ICacls for GUID_ blahblahblah.....  However failed....

Then i identified the comments in one of the blog for locagroup setting. Reference [here](https://community.spiceworks.com/topic/881602-hyper-v-vms-won-t-start)  - Comment "_Nick Holness
Apr 7, 2015 at 3:49 PM_". 

**THANKS A LOT to Nick Holness, you rescued me from this problem**

**_Working solution & Details:_**

1. Start the *Docker Desktop* with linux container enabled. You will be prompt with error. **DO NOT CLICK ON QUIT AS IT WILL CLEAR THE VM & OTHER DETAILS**
2. Open the PowerShell with administrator right
3. type command "Get-VM" and you list of VMs. this will list your docker VM as well "DockerDesktopVM"
4. type command "Start-VM -Name DockerDesktopVM" and enter. This will fail with error "**AccessDenied:Microsoft.HyperV.PowerShell.Commands.StartVMCommand**"
**_THIS IS THE MAIN REASON FOR DOCKER FAILURE_**
5. type command "net localgroup administrators" and enter
if you see "Everyone" as a part of the list administrators group then follow below steps else there is some other issue
6. type command "net localgroup administrators Everyone /delete" and enter
**NOTE: You might see *SERVICE* as a part of list the please delete SERVICE rather Everyone**.
7. Reboot the system and try the docker start with administrator rights.


_**Not Sure, how the Everyone/SERVICE is added as a part of administrators group. but that was the main issue in my case**_ Closing the issue.

Thanks
