### ISSUE TITLE
Can no longer talk to services running in Docker containers from host

### ISSUE THREAD

**Issue by daviddyball** [docker/for-win#7355]
- [x] I have tried with the latest version of my channel (Stable or Edge) `Stable`
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `0A6F9022-D4A4-42FC-B05C-8719E90C2A02/20200621173454`

### Expected behavior

I'm running a simple docker container that listens on port 3000 and serves basic HTML. I'd expect to be able to navigate to `http://localhost:3000` and access my service running in the container.

### Actual behavior

Unable to connect from Windows host to any service/process bound to a network port in my docker container:

![image](https://user-images.githubusercontent.com/1235844/85231418-b21c2a00-b3ee-11ea-8ca0-087e5b808fe9.png)

### Information

* I am running with WSL2 integration enabled
* I have done the following (trying and failing between each change):
  * Restarted Docker daemon
  * Restarted WSL
  * Restarted PC
  * Tried a different wireless network (in case of possible odd routing issues)
  * Reset network settings in windows (`Settings` -> `Network & Internet` -> `Network reset`)
  * Unregistered and re-installed my main Ubuntu 20.04 WSL container
  * Uninstalled/Re-installed Docker Desktop for Windows
  * Uninstalled WSL + Re-installed WSL + Re-registered Ubuntu 20.04 + Converted to WSL2
* This problem appeared after starting my PC up today. The last update pushed out the new Edge browser and didn't seem to have any WSL/WSL2 related changes

* Windows Version: `10.0.19041`
* Docker Desktop Version: Stable `2.3.0.3 (45519)` and Edge `2.3.1.0`
* Running on a Windows 10 laptop

### Steps to reproduce the behavior

  1. Start any container with a service bound to any port
  2. Attempt to connect from Windows host to `localhost:<port>`
  3. Where it previously worked fine it now fails with `Connection Reset`

**Comment by fabienheureux** [comment]
I have the same issue with latest docker desktop update. 
Version `2.3.2.0` / channel edge

**Comment by canove** [comment]
Same here. I can only access using the WSL ip (172.x.x.x)
