### ISSUE TITLE
Microsoft SQL Server Container stops working, when I shutdown or reboot my PC. 

### ISSUE THREAD

**Issue by gadeleonp** [docker/for-win#7359]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by gadeleonp** [comment]
Good day, I hope you are safe and in Good health. When I install the container works fine:
_**docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Password' -p 1433:1433 -d mcr.microsoft.com/mssql/server:2017-latest**_
Then I run this:
_**docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Password' -e 'MSSQL_PID=Express' -p 1433:1433 -d mcr.microsoft.com/mssql/server:2017-latest-ubuntu**_ 


The problem is when I need to shutdown or reboot my PC. When I login again to the docker desktop console. All the Microsoft Sql Server 2017 containers for docker are stoped and unable to start. 
I am using this for a software development process. Can anyone please help me?
Best regards, 

Gustavo de León

**Comment by djechelon** [comment]
See #7312, you should post error messages

**Comment by JMackCo** [comment]
I am having same issue this morning.. Started pc this morning. Windows 10. I have not been able to get docker up and running again for two hours... Installed reinstalled. Clean/Purge data/ Reset to factory defaults. When I try to run from VS Code> I get this error:    ERROR: Couldn't connect to Docker daemon. You might need to start docker from Windows. I started and restarted service.  
![image](https://user-images.githubusercontent.com/55293458/85285879-ab79cb00-b45f-11ea-8974-6211dd8b5471.png)

![image](https://user-images.githubusercontent.com/55293458/85285961-cba98a00-b45f-11ea-82f8-4bc2209636f1.png)
[log.txt](https://github.com/docker/for-win/files/4813082/log.txt)
