### ISSUE TITLE
Perma-locking issues after 30 days of inactivity is a really stupid idea.

### ISSUE THREAD

**Issue by cowlinator** [docker/for-win#7370]
Perma-locking issues after 30 days of inactivity is a terrible and foolish policy.

Example: Docker for Windows cannot be said to support Windows 10, when Docker with Windows 10 Creators Update simply fails container startup.  This is a platform-breaking issue.  Windows 10 is not supported for docker?
See https://github.com/docker/for-win/issues/703

And yet this issue has been perma-locked.  Guess it's time to forget all about it?

**Comment by stephen-turner** [comment]
The issue you refer to was closed in 2017, which means no-one was going to look at it anyway. As the message says, if you still have an issue, you are welcome to open a new ticket.

However, in this case, the Windows version you mention is not even supported by Microsoft any more, so we cannot support it. Our stated support policy is that all versions still under Microsoft support are tested and work.

**Comment by cowlinator** [comment]
Ok.  Sorry for my strong language, I was having a bad day.
