### ISSUE TITLE
Docker.Core.HttpBadResponseException: unable to fetch daemon.json

### ISSUE THREAD

**Issue by drandell** [docker/for-win#7387]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 72A6C731-3937-4217-B91C-2683EFAB9796/20200623160041

### Information

  - Windows Version: Windows 10 Pro -  Version 10.0.19041 Build 19041
  - Docker Desktop Version: Latest
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by paulmiller3000** [comment]
Same issue here. This happened after updating Docker Desktop and answering "yes" to the question about moving from Hyper-V to WSL 2. 

I've seen the error message reported by the op several times, yet it always seems to go stale and be closed automatically, with no actual resolution. Not answering a question doesn't make the issue go away.

My fix was to reset Docker Desktop to factory defaults. If that doesn't work for you, try this: https://forums.docker.com/t/docker-deskto-for-windows-2-2-0-3-42716-fails-to-update-fails-fresh-install/88879/7

**Comment by paulmiller3000** [comment]
Sad to see nobody from the project has addressed this.

Unfortunately, the issue reared its head again today, although I had **not** enabled WSL 2. Interestingly, I just closed Docker Desktop and restarted it, and this time it worked fine.
