### ISSUE TITLE
Docker Desktop failed to stop

### ISSUE THREAD

**Issue by vitorvasc** [docker/for-win#7388]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F5948A6E-258D-4907-870B-57AE5674E6F2/20200623163720

### Expected behavior

Docker should start up after install

### Actual behavior

The icon on the tray is red and showing a message 'docker desktop failed to stop'

### Information

  - Is it reproducible? Happens everytime I try to start docker on my machine
  - Is the problem new? Actually this is the first time I try to install docker on this computer
  - Did the problem appear with an update? --
  - Windows Version: Windows 10 Home Single Language, 2004, Build 19041.329
  - Docker Desktop Version: Docker version 19.03.8, build afacb8b 
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. I just installed docker for the first time on this computer and tried to start. I also installed WSL2 and Ubuntu.
  2. ...

**Comment by MDDietz** [comment]
I face the exact same problem. I tried installing it on Windows Home 2004 build. Did you figure anything out yet? Cause im considering switching to Windows Pro hoping that thats going to fix the problem since everythings working fine on my other pc with Windows Pro on.

**Comment by kbieser** [comment]
I upgraded to Windows 10 Education yesterday and am getting the same error message.

**Comment by samcr0w** [comment]
I am having the same issue. Recently upgrade Windows 10 to version 2004 in order to install WSL 2.0. Ran an install of Docker yesterday and receive the same error message. Please let me know if upgrading to Windows 10 Pro resolves the issue. Hate to drop additional money just to take this class.

**Comment by Julen-Lujambio** [comment]
Honestly, I think using the docker toolbox is probably the best option currently for windows home. I personally just installed docker in my WSL2 subshell (Ubuntu) and that worked perfectly (https://docs.docker.com/engine/install/ubuntu/). Also, when using docker I would have one terminal that I ran `dockerd ` on and that would run the docker deamon.  Then I would just use another terminal in which I would run `sudo docker run hello-world` for example. Hopefully that helps!

**Comment by vitorvasc** [comment]
> Honestly, I think using the docker toolbox is probably the best option currently for windows home. I personally just installed docker in my WSL2 subshell (Ubuntu) and that worked perfectly (https://docs.docker.com/engine/install/ubuntu/). Also, when using docker I would have one terminal that I ran `dockerd ` on and that would run the docker deamon. Then I would just use another terminal in which I would run `sudo docker run hello-world` for example. Hopefully that helps!

Yes, perfect. I was about to reply with the same words. I installed Ubuntu using WSL2 and followed the tutorial to install docker on Linux.

Forget about Docker Desktop, I don't think it's worth.

**Comment by kbieser** [comment]
Thank you, but I can’t even get docker toolbox to run now that I updated to Windows 10 Education.

**Comment by Julen-Lujambio** [comment]
Then, I would just do it the Linux subshell way. Hopefully, that doesn't give you any problems.

**Comment by DavidMelnychuk** [comment]
For others having the same problem, try to use the solution posted here: https://github.com/docker/for-win/issues/7295#issuecomment-645989416 . Worked for me when nothing else did.

**Comment by kbieser** [comment]
Thank you so much for this! I was able to get docker running in ubuntu. Now I hope I can build my container. Fingers crossed!
