### ISSUE TITLE
"Docker failed to stop" whenever Docker Desktop is run on Windows 10 

### ISSUE THREAD

**Issue by jmfiola** [docker/for-win#7389]
- [X] I have tried with the latest version of my channel (Stable)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3C62A177-1692-4B98-BEC2-22ABBA7872A3/20200623192017

### Expected behavior
When Docker Desktop starts up, it doesn't crash.

### Actual behavior
When Docker Desktop starts up, it crashes

### Information
 - **I recently upgraded from Windows 10 home to Windows 10 Pro. I have enabled all the necessary features to get Docker working (Hyper-V and containers)**
  - Windows Version: Windows 10 Pro build 19041.329
  - Docker Desktop Version: 2.3.0.3 (45519)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
Start Docker
Docker icon in the taskbar will be red, and say "Task failed to stop". If you try to reset docker, it will **fail to reset to factory default.**

**Comment by kbieser** [comment]
Did you find a solution for this? I upgraded from Windows 10 home to Windows 10 Education yesterday and continue to get the same error.

**Comment by DavidMelnychuk** [comment]
@kbieser Had the same issue and was able to fix it by following the solution [here]https://github.com/docker/for-win/issues/7295#issuecomment-645989416). 
Close docker then unregister it from wsl:
`PS C:\WINDOWS\system32> .\wslconfig.exe /u docker-desktop
`
Then try to run Docker again and hopefully it works.

**Comment by kbieser** [comment]
Thank you! I will give this a try.
