### ISSUE TITLE
docker ps is unavailable after installing.

### ISSUE THREAD

**Issue by jeremyje** [docker/for-win#7396]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID:3968A51E-85E9-4D62-AEB9-0261E7B16DD5/20200624053531

### Expected behavior
`docker ps` should return an empty list of containers.
### Actual behavior

```
C:\> docker ps
error during connect: Get https://192.168.99.126:2376/v1.40/containers/json: dial tcp 192.168.99.126:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

### Information

  - Windows Version: 2004 (OS Build 19041.329)
  - Docker Desktop Version: 2.3.0.3 (45519)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Windows Host with Hyper-V enabled. Intel 7700K.

### Steps to reproduce the behavior

1. Install Docker Desktop
1. `docker ps`
1. Switch between Linux and Windows containers options will give the same result.
1. I've also tried WSL2 and legacy Hyper-V modes.

![Capture](https://user-images.githubusercontent.com/1312331/85505519-5d6de000-b5a3-11ea-8de8-3871cc9c2f23.PNG)

**Comment by StefanScherer** [comment]
Hey @jeremyje it looks like you have environment variables set, eg. the `DOCKER_HOST` variable pointing to `192.168.99.126:2376`. Docker Desktop doesn't use the TLS endpoint, so it looks like a classic Docker Machine configuration or something like that.

**Comment by jeremyje** [comment]
I reinstalled docker and now it works. :/
