### ISSUE TITLE
不能启动

### ISSUE THREAD

**Issue by ligt1** [docker/for-win#7399]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:866F75AB-5AAE-490F-B690-12E7BA2CAC89/20200624075507

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Andreby42** [comment]
lao wai kan de dong zhong wen ?
