### ISSUE TITLE
error starting

### ISSUE THREAD

**Issue by kbieser** [docker/for-win#7419]
Diagnostic id: 2EF69869-ACC6-43E3-BDDE-339606F09E2B/20200624231257

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by quocdai92** [comment]
same issue. Here is my log:
[log.txt](https://github.com/docker/for-win/files/4829360/log.txt)
