### ISSUE TITLE
Image2Docker - how to get virtual machine disk image(VHD, VHDX or WIM)?

### ISSUE THREAD

**Issue by ramkiranadabala** [docker/for-win#742]
Dear Team,

We are new to docker MTA program. We are trying to migrate couple of our .Net legacy applications(framework3.5) onto Docker containers.

Input to Image2Docker is a virtual machine disk image(VHD, VHDX or WIM). Yes, our .Net applications are hosted on IBM VMs(Windows 2012).

Our question here is, how do we generate the virtual machine disk images?

Really appreciate your guidance.

Regards,
Ram

**Comment by sixeyed** [comment]
@ramkiranadabala the supported disk format is VHD, which is the Hyper-V format. You don't need to use a disk though - you can run Image2Docker on the machine itself, or remotely if you share the root drive. The docs explain [how to use different sources](https://github.com/docker/communitytools-image2docker-win/blob/master/docs/IIS.md).

This is not a D4W issue though - Image2Docker has its own [repo](https://github.com/docker/communitytools-image2docker-win/).

**Comment by rn** [comment]
closing as per the previous comment
