### ISSUE TITLE
Windows 10 Quick Start: Failure in a Windows system call: winapi error #3757047808 (0xdff00000) 

### ISSUE THREAD

**Issue by alexsab1** [docker/for-win#743]
### Expected behavior

Run example from Microsoft article: https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-10

`docker run -it microsoft/nanoserver cmd`

### Actual behavior

Error when running example command line

> C:\WINDOWS\system32>docker run -it microsoft/nanoserver cmd
> docker: Error response from daemon: container 5d1d50137e8bdd61cc32dda40f39591d5ade573d42888e6e6f68072215ba4438 encountered an error during CreateContainer: failure in a Windows system call: winapi error #3757047808 (0xdff00000) extra info: {"SystemType":"Container","Name":"5d1d50137e8bdd61cc32dda40f39591d5ade573d42888e6e6f68072215ba4438","Owner":"docker","IsDummy":false,"IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\docker\\windowsfilter\\5d1d50137e8bdd61cc32dda40f39591d5ade573d42888e6e6f68072215ba4438","Layers":[{"ID":"705154cb-d50c-505b-ae04-20898d1d2c33","Path":"C:\\ProgramData\\docker\\windowsfilter\\b014c41ac5418a4221347e49f8ede18f9d2dec14e56c2e678792ce98e776c10b"},{"ID":"a3bee206-1ac9-5911-8165-5028fff6e31a","Path":"C:\\ProgramData\\docker\\windowsfilter\\f0bbeb797349b36a31386167537ba5d9262f8d575bdeb0b143084eb43e21e3e6"}],"HostName":"5d1d50137e8b","MappedDirectories":[],"SandboxPath":"C:\\ProgramData\\docker\\windowsfilter","HvPartition":true,"EndpointList":["a65ede83-1377-40b7-8f65-868da3e565f5"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\docker\\windowsfilter\\b014c41ac5418a4221347e49f8ede18f9d2dec14e56c2e678792ce98e776c10b\\UtilityVM"},"Servicing":false,"AllowUnqualifiedDNSQuery":true}.
> 

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu: 23460B30-ED4C-4D1F-A58E-DA046B5C837F/2017-05-12_12-49-09
  - a reproducible case if this is a bug, Dockerfiles FTW: N/A
  - page URL if this is a docs issue or the name of a man page: N/A
  - host distribution and version (Windows version, build number, etc): Windows 10 version 1607 OS Build 14393.1066

### Steps to reproduce the behavior

 Run step 4 in article: https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-10

**Comment by Grauenwolf** [comment]
I'm seeing a different error:

C:\Source>docker run -it microsoft/nanoserver cmd
docker: Error response from daemon: container e31cc45f5d4849055ff13566014c696cad5a5effc9702622c3524b43b3f9ea01 encountered an error during CreateContainer: failure in a Windows system call: No hypervisor is present on this system. (0xc0351000) extra info: {"SystemType":"Container","Name":"e31cc45f5d4849055ff13566014c696cad5a5effc9702622c3524b43b3f9ea01","Owner":"docker","IsDummy":false,"IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\e31cc45f5d4849055ff13566014c696cad5a5effc9702622c3524b43b3f9ea01","Layers":[{"ID":"b43f5bf9-40d3-5fed-881c-105d1b4496cd","Path":"C:\\ProgramData\\Docker\\windowsfilter\\6214d91103e6aaf1ae8fca1a7312fa6939d1c0de4e13c19ead8915ccdf25745b"},{"ID":"eca436c3-1750-5858-ba86-380cd21bf844","Path":"C:\\ProgramData\\Docker\\windowsfilter\\8992d70442bb7e2c539993fd319fb91bfe0f20ed6a063fad9ab90a83882ebaff"}],"HostName":"e31cc45f5d48","MappedDirectories":[],"SandboxPath":"C:\\ProgramData\\Docker\\windowsfilter","HvPartition":true,"EndpointList":["e18c867d-844c-47e1-aa0c-fc7f045062ea"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\6214d91103e6aaf1ae8fca1a7312fa6939d1c0de4e13c19ead8915ccdf25745b\\UtilityVM"},"Servicing":false,"AllowUnqualifiedDNSQuery":true}.

**Comment by friism** [comment]
@alexsab1 are you running on bare metal or in some sort of VM?

@Grauenwolf it looks like Hyper-V is not working on your system - can you create normal Hyper-V vms?

**Comment by Grauenwolf** [comment]
I'm running inside a VMWare VM.

-----Original Message-----

**Comment by alexsab1** [comment]
@friism Running on bare metal

**Comment by alexsab1** [comment]
@Grauenwolf please create your own issue for the error you are receiving. Thank you

**Comment by ozancoskun** [comment]
@alexsab1 did you ever find a solution to this problem? I'm still experiencing this
