### ISSUE TITLE
Cannot Start Docker on Linux containers, ""

### ISSUE THREAD

**Issue by CarlosRocha2409** [docker/for-win#7432]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:19D0E84A-05BB-4C34-A5FC-13E5168EE615/20200625231331

### Expected behavior
Docker alowing me to use docker comands on WSL

### Actual behavior
When i try to launch docker, it says "Failed to stop", i cannot restart the service, i cannot reset to default settings also
this is one of the errors when i tried to restart the service:

Docker.ApiServices.StateMachines.InvalidTransitionException:
Cannot stop from an unstable state
   en Docker.ApiServices.StateMachines.UnstableState.Docker.ApiServices.StateMachines.IInternalEngineState.BeginStopAsync() en C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\UnstableState.cs:línea 36
   en Docker.ApiServices.StateMachines.EngineStateMachine.<StopAsync>d__15.MoveNext() en C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:línea 81
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Docker.Engines.Engines.<RestartAsync>d__29.MoveNext() en C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:línea 272

### Information
 I dont know how i got this error for real i'm new with wsl

**Comment by allenabraham** [comment]
Then I faced couple of issues like the one you are facing, which I was able to resolve by doing the following:

- Shutting down wsl:
- `wsl --shutdown`

Reinstalling Docker.
Restarting the Docker Desktop.


Also as a side note, my daily routine the last week firefighting the high disk usage caused by localservicenonetworkfirewall, which was resolved by switching on Windows Firewall.
Trust it helps you.
