### ISSUE TITLE
Kubernetes hangs on Start

### ISSUE THREAD

**Issue by SCBionicle** [docker/for-win#7434]
In reference to issue: #1962

  - [ ✅ ] I have tried with the latest version of my channel (Stable)
  - [ ✅ ] I have uploaded Diagnostics
  - Diagnostics ID: 26F01EFE-71B3-4E04-8B54-43D240B0DA24/20200625234848

### Expected behavior
Kubernetes status on Docker for Windows transitions to running and I should be able to access the context through `kubectl`
### Actual behavior
After enabling Kubernetes in the Docker settings through the Docker Dashboard, it hangs on starting (waited for at least 10 minutes) and cannot connect to the generated context through kubectl.
### Information

This bug is consistently reproducible on my machine as of the previous update and is still present today.
  - Windows Version: Windows 10 Pro Update 2004 Build 19041
  - Docker Desktop Version: 2.3.0.3 (46619) (Stable)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No, this is a physical machine

### Steps to reproduce the behavior

  1. Open Docker Desktop Dashboard
  2. Go to the settings
  3. Go to Kubernetes tab
  4. Enable Kubernetes
  5. (No prompt appears in comparison to Mac)
  6. Press "Apply & Restart"
  7. Wait for restart
  8. Docker starts, but Kubernetes hangs under starting indefinitely

**Comment by SCBionicle** [comment]
Still an issue in this version:
Client: Docker Engine - Community
 Azure integration  0.1.15
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:43:18 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
 Kubernetes:
  Version:          Unknown
  StackAPI:         Unknown

**Comment by SCBionicle** [comment]
New Diagnostic ID: 26F01EFE-71B3-4E04-8B54-43D240B0DA24/20200924011440

**Comment by Nish17g** [comment]
Please add the following line to the etc\hosts files
127.0.0.1 kubernetes.docker.internal
