### ISSUE TITLE
Docker Version --format no longer support shorthand '-f' (channel:ee version:2.3.2.0 46268)

### ISSUE THREAD

**Issue by hsiungw** [docker/for-win#7444]
the following command return error.

docker version -f "{{.Server.Os}}"

Error:
unknown shorthand flag: 'f' in -f

But this is fine.

docker version --format "{{.Server.Os}}"
windows

![image](https://user-images.githubusercontent.com/16015694/85841875-53c9bf80-b7d1-11ea-8dc8-87a064cd8b44.png)

**Comment by gtardif** [comment]
Thx for the feedback, this should be fixed in the next edge update.

**Comment by gtardif** [comment]
Hi, FYI, a security path has been published today on Docker Desktop for Win. Unfortunately the fix for this issue is not part of the security release, but will be out soon.
