### ISSUE TITLE
Can't mount /dev/shm/ from Windows environment when using WSL2 backend

### ISSUE THREAD

**Issue by kiview** [docker/for-win#7455]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4F13C4FD-BD29-4BDD-899F-5AB9BBACA7D6/20200627091735

### Expected behavior

Mounting `/dev/shm/` from the Windows environment should work:
```
docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-firefox
```

### Actual behavior

When running from Windows environment (e.g. Powershell) the command will fail with
```
C:\Program Files\Docker\Docker\resources\bin\docker.exe: Error response from daemon: error while creating mount source path '/dev/shm': mkdir /dev/shm: file exists.
```

It works when run from inside WSL2.

### Information

Only happens with the WSL2 backend when creating the container from the Windows environment.

  - Windows Version: Windows 10 Pro 2004
  - Docker Desktop Version: 2.3.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Native installation

This is related to https://github.com/testcontainers/testcontainers-java/issues/2552.

### Steps to reproduce the behavior
Run from Powershell:
```
docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-firefox
```

**Comment by stephen-turner** [comment]
Any comments, @simonferquel? Do we expect this to work?

**Comment by simonferquel** [comment]
It should yes.

**Comment by kiview** [comment]
I'd be happy to help in any way possible to debug and fix this issue, also in order to make using WSL2 backend more seamless for Testcontianers users.

**Comment by GetoXs** [comment]
https://github.com/docker/for-win/issues/7148

**Comment by stephen-turner** [comment]
Thanks for that, @GetoXs, I'd missed that ticket. It has 13 👍s too. I'll bump our internal ticket up the backlog a bit.

**Comment by simonferquel** [comment]
I have been able to identify the issue and made a fix (which should come in a future Edge release). Thanks for the report.
