### ISSUE TITLE
Docker for Win crashes upon launch now

### ISSUE THREAD

**Issue by TheNetWhiz** [docker/for-win#7461]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 797D20E0-F5E6-4B93-BAD1-8D43A8484CC7/20200628012654

### Expected behavior

Docker Desktop starts

### Actual behavior

Crashes with an error

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. Boot computer and launch Docker automatically or manually.
  2. Crashes. Have reinstalled several times, rebooted, and retried Hyper-V settings. Nothing is getting it to start.

**Comment by JensHaley** [comment]
I had the same problem, this worked for me (Win 10, 1909; Docker 2.3.0.3):

1. If you have docker installed, de-install it.
1. Make sure Hyper-V is deactivated. If not, deactivate it, reboot.
1. Install Docker again. During the installation process, tick the option to let Docker configure Hyper-V.
1. After the installation is finished, let Docker restart your PC.

**Comment by TheNetWhiz** [comment]
I tried your recommendation and it did not work. Same errors.
