### ISSUE TITLE
Can't type command after start container

### ISSUE THREAD

**Issue by EnziinSystem** [docker/for-win#747]
### Expected behavior
It can type text in Power Shell after start container.
### Actual behavior
After start container, I can't type any command in terminal.
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. Step 1: start container but can't type text.

![step1](https://cloud.githubusercontent.com/assets/25495466/26022422/59840dd4-37cf-11e7-965a-767bafe0d9b4.png)

2. Step 2 : Press CTRL+C and attach again

![step2](https://cloud.githubusercontent.com/assets/25495466/26022421/59826998-37cf-11e7-8343-153038cf4821.png)
![step3](https://cloud.githubusercontent.com/assets/25495466/26022424/5988dcf6-37cf-11e7-8be3-d50c77efe25b.png)
![step4](https://cloud.githubusercontent.com/assets/25495466/26022423/59855a9a-37cf-11e7-9954-d86739db89a7.png)

And log file, I run on Windows 10, ubuntu 17.04 image

[log.txt](https://github.com/docker/for-win/files/998339/log.txt)

**Comment by mechanic22** [comment]
Have you tired starting your container with the "-i, --interactive" option?

Usage:  docker start [OPTIONS] CONTAINER [CONTAINER...]

Start one or more stopped containers

```
Options:
  -a, --attach                  Attach STDOUT/STDERR and forward signals
      --checkpoint string       Restore from this checkpoint
      --checkpoint-dir string   Use a custom checkpoint storage directory
      --detach-keys string      Override the key sequence for detaching a container
      --help                    Print usage
  **-i, --interactive             Attach container's STDIN**
```

**Comment by EnziinSystem** [comment]
Thanks, mechanic22!

**Comment by dgageot** [comment]
@EnziinSystem I am going to close this issue since using `-i` is the way to solve your problem
