### ISSUE TITLE
docker trust key generate

### ISSUE THREAD

**Issue by danashviro** [docker/for-win#7483]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 8C89258C-657E-4040-B83B-AEA7A515D88A/20200629133505

I'm trying to generate trust key, in order to use Content trust for my images.
I used this manual https://docs.docker.com/engine/security/trust/trust_delegation/#using-docker-trust-to-generate-keys
 on cmd:
`docker trust key generate {new key name}`
I'm getting 
`Generating key for {new key name}...`
`Enter passphrase for new {new key name} key with ID {id}:`

I enters a passphrase (random string) and nothing happens
### Expected behavior
after inserting a passphrase and pressing enter,
`Repeat passphrase for new {new key name} key with ID {id}:` 
should appear

### Actual behavior
nothing happens
### Information

  - Windows Version: Windows 19 Enterprise 1909
  - Docker Desktop Version: 19.03.8, build afacb8b
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. `docker trust key generate {new key name}`
  2. enter a passphrase

**Comment by JimmySimard** [comment]
I've got the same problem as you ! Have you found a solution ?

**Comment by danashviro** [comment]
> I've got the same problem as you ! Have you found a solution ?
@JimmySimard no, I use a Linux container to manage the keys
