### ISSUE TITLE
You have an update ready. Install it now. There is an update. Install. Really. Update. Now

### ISSUE THREAD

**Issue by oliversalzburg** [docker/for-win#749]
![image](https://cloud.githubusercontent.com/assets/1658949/26047972/8ae82b26-3955-11e7-9f55-aa8d855133e6.png)

**Comment by oliversalzburg** [comment]
And then it fails:
![image](https://cloud.githubusercontent.com/assets/1658949/26048043/c7902d6c-3955-11e7-8abb-d0fd18c3e325.png)

**Comment by friism** [comment]
Thanks for reporting - the latest release has a fix for the multiple update windows.
