### ISSUE TITLE
Cannot uninstall Docker v1.12.1-rc1-beta23 Build: 14393

### ISSUE THREAD

**Issue by Mastergalen** [docker/for-win#75]
### Expected behavior

Docker should uninstall itself when uninstalling it from Control Panel -> Uninstall a program.

### Actual behavior

The uninstallation process is unable to proceed unless the original `InstallDocker.msi` file exists.

![2016-09-11 12_36_42-windows installer](https://cloud.githubusercontent.com/assets/1261152/18416729/71ccae50-781c-11e6-8b6b-810fcd4c353b.png)

### Information

Related to https://forums.docker.com/t/solved-unable-to-remove-or-upgrade-from-1-12-0-rc2-beta16/17820

I cannot locate the download links for the original `InstallDocker.msi` file. I've tried:

* https://download.docker.com/win/beta/1.12.1.14393/InstallDocker.msi
* https://download.docker.com/win/stable/1.12.1.14393/InstallDocker.msi

but none of them work.

* Windows 10 Pro 64 bit , v1607, OS Build 14393.105
* Docker v1.12.1-rc1-beta23 Build: 14393

I also tried to simply download the latest [stable](https://download.docker.com/win/stable/InstallDocker.msi) version and simply running that, though installation fails as it's unable to remove the old docker version, also ends up giving the same prompt to locate the installation package `InstallDocker.msi`.

### Steps to reproduce the behavior

  1. Go to Control Panel -> Uninstall a program
  2. Uninstall Docker
  3. Installation unable to proceed due to missing `InstallDocker.msi` file

**Comment by Mastergalen** [comment]
After being able to find the build number within `Docker.Backend.dll` locate in `C:\Program Files\Docker\Docker` and checking the build number inside the properties of the file, I found that the build number i have installed is 6433.

The download link that works is https://download.docker.com/win/beta/1.12.1.6433/InstallDocker.msi

However, after downloading the file and trying the uninstall again, it is still complaining that it is not a valid installation package.

**Comment by dgageot** [comment]
@ebriney Could you try to help @Mastergalen please?

**Comment by Mastergalen** [comment]
@ebriney Thank you, I eventually gave up on this though and just reset my Windows 10.
