### ISSUE TITLE
Can't Start Docker after install - Hyper-V is enabled

### ISSUE THREAD

**Issue by crazyoutlook** [docker/for-win#7509]
[docker_log.txt](https://github.com/docker/for-win/files/4853461/docker_log.txt)

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by crazyoutlook** [comment]
[docker_log.txt](https://github.com/docker/for-win/files/4853464/docker_log.txt)

**Comment by crazyoutlook** [comment]
Hi, Have attached log file which was generated as error log. My Hyper-V is enabled from BIOS and Windows still getting error.

**Comment by anupwarke** [comment]
Refer #7353 if this helps you
