### ISSUE TITLE
Docker keeps crashing all of a sudden with that legend

### ISSUE THREAD

**Issue by DoctorWho8** [docker/for-win#7510]
Docker.ApiServices.StateMachines.InvalidTransitionException:
Cannot stop from an unstable state
   at Docker.ApiServices.StateMachines.UnstableState.Docker.ApiServices.StateMachines.IInternalEngineState.BeginStopAsync() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\UnstableState.cs:line 36
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StopAsync>d__15.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 81
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<RestartAsync>d__29.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:line 272

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by santfirax** [comment]
I upgraded my Docker today and I also have this problem

**Comment by pdgcvs** [comment]
Does it starts?
I had the same exception but mine would not even start. 
 
Running:
`wsl -l -v` 
Would present a "docker-desktop" with installing status 

Running this command and restarting docker seens to have fixed for me: 
`wsl --unregister docker-desktop`

**Comment by DoctorWho8** [comment]
wsl --unregister docker-desktop it did something. I'm going to install this newly downloaded kit. And then run it and see what happens. It insisted that the installation that exists is up to date. It seems  And your idea to use wsl --unregister docker-desktop did indeed do something. The instance I have worked. Now to try it. And here's the ultimate starter:
PS C:\Users\hanso\OneDrive\Desktop> docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
0e03bdcc26d7: Pull complete
Digest: sha256:d58e752213a51785838f9eed2b7a498ffa1cb3aa7f946dda11af39286c3db9a9
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/
That tells me it worked. But I'm a Slackware fan. Now to track down one. And the one by vbatts works. I'm going to keep this issue open until we get clear idea as to what's wrong..
