### ISSUE TITLE
Volume mounting: Access denied errors

### ISSUE THREAD

**Issue by richardgavel** [docker/for-win#752]
I am trying using Window 10 and Docker for Windows 17.03.1-ce-win12 (12058). I am trying to create a container that will be used on a CI server for build execution. The source code is mounted as C:\src. The build will copy some files into a subdirectory of C:\src. Subsequent build will delete them. But I get a "Unable to delete file...Access to path is denied" error. When I try to delete the file from the host, I get the it's open in vmmem.

**Comment by friism** [comment]
This is most likely an issue for `moby/moby`.

Please provide a series of steps that reproduce the problem, and `Dockerfile` etc. to build.

**Comment by richardgavel** [comment]
Sorry, I should have clarified that this is within the context of a Windows container.

**Comment by megamindbrian** [comment]
```
Set-NetConnectionProfile -interfacealias "vEthernet (DockerNAT)" -NetworkCategory Private
```
?

**Comment by mawl** [comment]
Same issue here - we also use windows docker containers for CI builds.
C:\Windows\system32>docker --version
Docker version 17.03.1-ee-3, build 3fcee33 (is this correct for windows server 2016 and Windows-native Docker Engine? - I wonder about the ee in it...)

When trying to copy a file which was created during build from within the container its access is denied.
But only with docker run without -it.
When starting the container with -it and went into it the copy command works.

As a workaround we're creating the build output in a temp folder outside the mounted directory and copy it back from there to the mounted volume.

Any ideas?

**Comment by azstate** [comment]
hello, I am using Azure Windows server 1709 with containers machine. Have mapped volume using -v <src>:<dest>. I am not able to access word files from volume. It gives Access Denied error. Please suggest
