### ISSUE TITLE
failed to start docker

### ISSUE THREAD

**Issue by Tungquantedge** [docker/for-win#7527]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. open docker
  2. app require restart to install kennel linux but click restart nothing happen
![image](https://user-images.githubusercontent.com/32952770/86309391-d32e1780-bc45-11ea-9fa4-cf9e8502c1cd.png)

**Comment by stephen-turner** [comment]
Did you follow the link and install the kernel from Microsoft's website?
