### ISSUE TITLE
Docker is using port 5000 which I need for another service

### ISSUE THREAD

**Issue by JasonGoemaat** [docker/for-win#753]
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by friism** [comment]
Docker doesn't use port 5000 out of the box. Please provide more details

**Comment by JasonGoemaat** [comment]
I'm running Windows 10 Pro.  Looking at resource monitor it shows two entries for com.docker.slirp.exe listening on tcp port 5000, one for 'IPv6 loopback' and one for 'IPv4 unspecified'.

Other running docker apps are 'com.docker.db.exe', 'com.docker.proxy.exe', and 'com.docker.service'.

**Comment by dgageot** [comment]
@JasonGoemaat Can you make sure `docker ps` shows no container using the port 5000?
