### ISSUE TITLE
Docker failed to start after update to Windows 10 and wls2 enabled

### ISSUE THREAD

**Issue by S1AnGeR** [docker/for-win#7532]
- [*] I have tried with the latest version of my channel (Stable or Edge)
  - [*] I have uploaded Diagnostics
  - Diagnostics ID:9B3E86C9-91DE-4AD3-A511-299E97CDEE04/20200702130513
  - Crash Report ID: 9B3E86C9-91DE-4AD3-A511-299E97CDEE04/20200702132431

### Expected behavior
Docker runs correctly

### Actual behavior
docker: Error response from daemon: open \\.\pipe\docker_engine_linux: The system cannot find the file specified.
### Information

  - Is it reproducible? - Yes
  - Is the problem new? - Yes, after update to windows 10 v.2004 wsl2
-->
  - Windows Version: Windows 10 Version 2004 (19041.264)
  - Docker Desktop Version: 2.3.0.3 (45519)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No.

### Steps to reproduce the behavior
try docker run , docker: Error response from daemon: open \\.\pipe\docker_engine_linux: The system cannot find the file specified.

I already thy reinstall it (but docker uninstall always failed) , so I used to powershell script :
‘C:\Program Files\Docker\Docker\resources\MobyLinux.ps1’ -Destroy
$service = Get-WmiObject -Class Win32_Service -Filter “Name=‘com.docker.service’”
$service.StopService()
$service.Delete()
Start-Sleep -s 5
Remove-Item -Recurse -Force "~/AppData/Local/Docker"
Remove-Item -Recurse -Force "~/AppData/Roaming/Docker"
takeown.exe /F “C:\ProgramData\Docker” /R /A /D Y
icacls “C:\ProgramData\Docker” /T /C /grant Administrators:F
Remove-Item -Recurse -Force "C:\ProgramData\Docker"
Remove-Item -Recurse -Force "C:\Program Files\Docker"
Remove-Item -Recurse -Force "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Docker"
Remove-Item -Force "C:\Users\Public\Desktop\Docker for Windows.lnk"
Get-ChildItem hklm:\software\microsoft\windows\currentversion\uninstall | ForEach-Object {Get-ItemProperty $.PSPath} | Where-Object { $.DisplayName -eq “Docker” } | Remove-Item -Recurse -Force
Get-ChildItem hklm:\software\classes\installer\products | ForEach-Object {Get-ItemProperty $.pspath} | Where-Object { $.ProductName -eq “Docker” } | Remove-Item -Recurse -Force
Get-Item ‘HKLM:\software\Docker Inc.’ | Remove-Item -Recurse -Force
Get-ItemProperty -path HKCU:\software\microsoft\windows\currentversion\Run -name “Docker for Windows” | Remove-Item -Recurse -Force

**Comment by MarcelMo** [comment]
Try to run from an elevated command prompt, this solved this problem for me!
