### ISSUE TITLE
Cannot Open Any Application While Docker Desktop Edge v2.3.2.1 Running

### ISSUE THREAD

**Issue by Keimeno** [docker/for-win#7539]
- [X] I have tried with the latest version of my channel (Stable or Edge)

### Information

  - Windows Version: Windows 10 Home 19041
  - Docker Desktop Version: 2.3.2.1
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Start Docker Desktop
  2. Try to run any app, like Powershell or Chromium and it will crash immediately on startup

To run any app I must stop Docker Desktop, open it, and start Docker Desktop again.

This also happens with the stable version 2.3.0.3. However when opening an application with the stable version my entire monitor goes black, and the application crashes as well.

Are there any related issues to this?

**Comment by stephen-turner** [comment]
Wow. No. Never seen a report of that before.

Could you upload some diagnostics and attach the id here? Although I'm not completely sure whether it will capture the important event because it's the other program that fails to start.

**Comment by Keimeno** [comment]
I'll run some diagnostics later and upload a video.

**Comment by Keimeno** [comment]
Okay now it is getting seriously weird.

Before I comment on what happend, I need to address that I've installed Docker Toolbox before, uninstalled it, then installed Docker Desktop about 15 times until it worked. I've also restarted my PC several times by now, and this error already occured to me yesterday.

Now after I've run the diagnostics **without** opening any window, I can finally open other applications now (Couldn't even shut down my Laptop without exiting docker desktop, shutdown process couldn't start).

So, I can open every application, except for VS Code for some reason. At one point VS Code will directly shut down again, but mostly the integrated terminal in VS Code will go blank and unresponsive. I've installed the Docker extension for VS Code (maybe that's the reason it still doesn't work there). I'll try to restart my Laptop a few times again and reinstall VS Code to check if the error stops happening then.

Anyways here are the diagnostics:
Diagnostic without doing any action: 4E87EEEF-F351-473F-B334-59ECF4F5D882/20200703111102
Diagnostic, but opening a few processes and VS Code:  1st Test: **Docker Desktop Crashed** 2nd Test: 4E87EEEF-F351-473F-B334-59ECF4F5D882/20200703112341

While running the second diagnostic, it got back to it's old behavior, everything crashes again. + The Screen went black, same thing happened with the Stable version.

Also; here's the [video](https://image.monternos.net/u/yPeuKlpICbBgs0Ja248HEFSdYiZ6cMjt.mp4) showing what happened.

**Comment by Keimeno** [comment]
I found out when this starts happening. If I start Docker Desktop **after** I've uninstalled the Docker extension in VS Code and then start VS Code, or any other app, everything works totally fine. I can open everything at any time while Docker runs.

However, if I start [this compose script](https://github.com/WHG-Students/Bankingsystem/blob/develop/docker-compose.yml) everything works fine, until I save any file. Usually when I save a file docker goes ahead and moves it and rebuilds the application. However with Docker Desktop that doesn't seem to be possible. Because the moment I save a file with the compose script running, VS Code crashes. After that I can't open any application again. So it occurs when copying files from windows to wsl I guess.

Also funny remark; Sometimes the monitor doesn't turn black after crashing, but there's a [graphic bug](https://image.monternos.net/u/F3H41wfBTGhZOAbDWC72QKdnSIJmUNuq.png) occurring in VS Code which is quite funny

**Comment by stephen-turner** [comment]
This is very weird. I can't imagine how Docker Desktop could cause a graphical bug in VS Code.

**Comment by Keimeno** [comment]
So; After a few more restarts and working with my Laptop, I wasn't able to open more than 1 Chromium Application at a time. Meaning if I open Discord while having VS Code open, one of them started crashing, and in general Windows has several bugs now.

After that, I've done a factory reset on my Laptop and installed the Docker Desktop Stable version and everything works completely fine now. Still not sure why that happened.

**Comment by stephen-turner** [comment]
OK, thanks for the update. Glad you got it sorted. I'll close the ticket now.
