### ISSUE TITLE
Shared Drives/Advanced/Network tabs in Docker for Windows not displayed in Windows Container mode

### ISSUE THREAD

**Issue by JonJam** [docker/for-win#754]
### Expected behavior
The Shared Drives/Advanced/Network tabs in Docker for Windows settings should always be displayed.

### Actual behavior
The Shared Drives/Advanced and Network tabs in Docker for Windows are not displayed when it is in Windows Container mode.

### Information
- Docker for Windows Version: Version 17.03.1-ce-win12 (12058), Channel: stable, d1db126
- OS: Windows 10 Enterprise, Version 1704, Build: 15063.296

### Steps to reproduce the behavior
1. Launch Docker for Windows.
2. Switch to Windows Containers if not already in it.
3. Select Settings.
4. Observer Shared Drives, Advanced and Network tabs not displayed.

**Comment by friism** [comment]
These settings are not applicable to Docker Windows containers.

Other than looking at these tabs when in Docker Windows container mode, what are you trying to achieve?

**Comment by JonJam** [comment]
@friism Apologies I

**Comment by JonJam** [comment]
@friism My mistake I skipped over the part in the documentation that these settings were only applicable for Linux containers

**Comment by NReilingh** [comment]
@friism What do you mean by "not applicable"? Why would we not need to manage resource allocation for Windows containers, given that by default they are given only a restrictive 1GB of RAM?

**Comment by rottitime** [comment]
Can someone please help. How do we get these tabs to show

**Comment by shahriarhossain** [comment]
I was having 'Not enough memory to start' issue, someone suggested that switching to windows container and then switching back to linux continer sometime resolve the issue. So I did. Switching to Windows Container runs successfully. But when I tried to switch back to Linux I hit the 'Not enough memory to start' issue again. And there is no where I can see the advanced tab on the settings.
