### ISSUE TITLE
ERROR: Service 'web' failed to build: Get https://registry-1.docker.io/v2/: x509: certificate is  valid for *.kneura.com, not registry-1.docker.io

### ISSUE THREAD

**Issue by kmmizouri** [docker/for-win#7560]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by rg2609** [comment]
Hi, I am too facing this error while building the docker image and the base image is `ubuntu:18.04`. Error : 
```
abc@dell:~/zzz/xxxx$ docker build .
Sending build context to Docker daemon 2.506 GB
Step 1/10 : FROM ubuntu:18.04
Get https://registry-1.docker.io/v2/: x509: certificate is valid for *.cropx.info, not registry-1.docker.io
```

**Comment by kmmizouri** [comment]
@rg2609 
1- add this line to your system32/drivers/etc/hosts :: 
3.223.220.229 registry-1.docker.io
2- reboot docker
