### ISSUE TITLE
docker after windows update

### ISSUE THREAD

**Issue by tbouakline** [docker/for-win#7561]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by PavelSosin-320** [comment]
Indeed, After the latest upgrade of Windows 10 no distro started smoothly including docker-desktop. Everything related to WSL 2 has to be removed and re-installed. If you after build 20151 all your distros have a chance to be broken. Docker desktop removal and re-installation solved the problem for me.

**Comment by PavelSosin-320** [comment]
Many things in WSL2 happen only once, during the initial startup of  distro and it assumes the non-destructive Docker Desktop upgrade process to keep the paste with Windows releases. The correct sequence is:
Backup data - create checkpoint, maybe to the cloud storage
wsl --terminate distro
wsl --unregister distro
download new adopted Docker-desktop distro tar
wsl --import docker-desktop distro tar
Restore data from checkpoint
Restart Docker daemon.
It will be a salvage package for non-professional Docker users of Windows home edition and noise silencer for the Docker desktop team.
