### ISSUE TITLE
issues about 'docker import/export ' command

### ISSUE THREAD

**Issue by Luxios** [docker/for-win#758]
when I use the two commands in windows powershell (win10)
docker export [container id] > xx.tar
docker export [container id] xx.tar

the file size of the tar produced by the first command is much bigger than the second one.

and when I tried the command on the first tar file
cat xx.tar | docker import - image
The computer crashed.

docker import xx.tar image on the second tar file worked well, but on the first tar file it gave wrong message: invalid tar header.

Why?

**Comment by friism** [comment]
This is not a Docker for Windows issue, it's a [problem with PowerShell](https://github.com/PowerShell/PowerShell/issues/1908). Just us the -o parameter:

    docker export <cid> -o foo.tar

**Comment by Luxios** [comment]
@friism Thanks.But does `docker export <cid> -o foo.tar` has any difference from `docker export <cid> foo.tar`

**Comment by friism** [comment]
`docker export <cid> foo.tar` is not a valid command.

```
docker export 524539eafb58 foo.tar
"docker export" requires exactly 1 argument(s).
See 'docker export --help'.

Usage:  docker export [OPTIONS] CONTAINER

Export a container's filesystem as a tar archive
```
