### ISSUE TITLE
Error response from daemon: hcsshim::ActivateLayer - failed failed in Win32: The process cannot access the file because it is being used by another process. (0x20)

### ISSUE THREAD

**Issue by ti-jalopez** [docker/for-win#7591]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID:212232B5-0F3E-4A7F-8CEE-904B1754FD72/20200708101922

### Expected behavior
 - Start containers fine if yesterday run fine and there is no changes.

### Actual behavior
- Error when I try to start any container

### Information

  - Windows Version:  10.0.19041.329
  - Docker Desktop Version: 2.3.0.3 (45519)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: NO

### Steps to reproduce the behavior

  1. Yesterday I run two dockers containers fine, but today al my containers are stopped in state existed.
  2. When I try to start any container there is an error: Error response from daemon: hcsshim::ActivateLayer - failed failed in Win32: The process cannot access the file because it is being used by another process. (0x20)
  3. I've been researching in logs and event viewer:
log.txt: [12:19:16.848][ApiProxy          ][Error  ] hostPathOfVolume C failed, skipping volume
event viewer: hcsshim::ActivateLayer - failed failed in Win32: The process cannot access the file because it is being used by another process. (0x20) [path=C:\ProgramData\Docker\windowsfilter\775191b5424f148643163afa39fd7faa31d421d3b86cf31abdbc68d657b1a8c2 error=hcsshim::ActivateLayer - failed failed in Win32: The process cannot access the file because it is being used by another process. (0x20)]
  4. The file sandbox.vhdx in folder 775191b5424f148643163afa39fd7faa31d421d3b86cf31abdbc68d657b1a8c2 is used by system process. I've tried to kill de handle using handle.exe from sysinternals, but an error occurs: Error closing handle. Controlador no valido (not valid controller).
 5. If I create a new container it run fine.

**Comment by Nyryus** [comment]
I'm facing the same issue.
Diagnostic ID: 3A9CC876-CD55-4085-84A2-A6516658E754
[20201125115307.zip](https://github.com/docker/for-win/files/5596865/20201125115307.zip)

Checking the event viewer before the error there is an information:
```
debug: FIXME: Got an API for which error does not match any expected type!!!: hcsshim::ActivateLayer - failed failed in Win32: The process cannot access the file because it is being used by another process. (0x20) [module=api error_type=*hcserror.HcsError]
```
