### ISSUE TITLE
Unable to login to Docker on Windows - unknown error when proper credentials are given

### ISSUE THREAD

**Issue by cmsptcp** [docker/for-win#7596]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by vineelsahini** [comment]
I am having the same issue as well. What is the solution ?
