### ISSUE TITLE
Cannot run Docker after reinstall

### ISSUE THREAD

**Issue by ericis** [docker/for-win#76]
### Expected behavior
Docker daemon starts when Windows starts.

### Actual behavior
Failure with error.

### Information

  - Diagnostic: 8800B175-02A6-4B07-92A0-BE9066A0F6D8/2016-09-13_08-23-57
  - Windows Enterprise 10 Version	10.0.14393 Build 14393
  - Docker 1.12.0-stable (build: 5968)

### Steps to reproduce the behavior

  1. Uninstall & reinstall

### Resolutions attempted

- Uninstall "Windows Containers"
- Uninstall dev Unix tools beta Windows feature
- Disable dev-mode
- Reinstall network drivers
- Uninstall VirtualBox (it's using Hyper-V)
- Reinstall Docker *Had issues fully removing docker several times*
- Reinstall Hyper-V

### Interesting bits of log file

com.docker.slirp.exe: Waiting for connections on socket hyperv-connect://3e573135-2e23-48b8-8050-25500ba12e45
[08:23:35.679][ApiProxy       ][Info   ] Started
[08:23:35.695][Database       ][Info   ] Removing com.docker.driver.amd64-linux/proxy/exclude
[08:23:35.695][Database       ][Info   ] Removing com.docker.driver.amd64-linux/proxy/http
[08:23:35.695][Database       ][Info   ] Removing com.docker.driver.amd64-linux/proxy/https
[08:23:35.785][ApiProxy       ][Info   ] docker proxy (on deprecated port): ready
[08:23:35.789][ApiProxy       ][Info   ] dns server: ready
[08:23:35.790][ApiProxy       ][Info   ] docker proxy: ready
[08:23:35.903][DataKit        ][Info   ] 
[08:23:35.904][DataKit        ][Info   ] +6358885us       fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled
[08:23:37.627][Database       ][Error  ] 2016/09/13 08:23:35 Failed to Walk to 9pdb 9p: No such file or directory
2016/09/13 08:23:35 Failed to Create branch/ master /transactions/ 9pdb 9p: No such file or directory
2016/09/13 08:23:35 Failed to create database branch: p9p.MessageRerror{Ename:"No such file or directory"}

[08:23:37.628][Database       ][Error  ] Unable to write to the database: Unable to remove from the database. Exit code: 1. Let's retry in 1s

**Comment by dgageot** [comment]
Hi @ericis , thanks for the detailed report! Could you give a try to the Beta channel instead of the Stable channel? It contains multiple fixes that might help.

**Comment by ericis** [comment]
Will do @dgageot. I'll report back within 24 hours. Thanks.

**Comment by ericis** [comment]
Okay, I'm up and running, but attempting to retrace my steps. Resources I used came from:
- https://github.com/docker/for-win/issues/67
- https://forums.docker.com/t/unable-to-send-start-failed-to-start-mobylinux-vm/13258/8

**Comment by ericis** [comment]
Note: Windows 10 Enterprise running the latest Docker for Windows on top of Hyper-V (versions above).
(**not VirtualBox!**)

Steps I attempted that eventually got it working...
(1) Reinstall Docker (failed)
(2) Stop/Start Docker service manually (failed)
(3) Realized the issue seemed related to something in Hyper-V
(4) Used [Vagrant](http://vagrantup.com) to confirm I could create a Hyper-V image through automation
  1. Install vagrant
  2. Create a "Vagrantfile" in an empty directory with the content
  3. In a command window with the current working directory pointed to the directory above with the "Vagrantfile", run `vagrant up --provider=hyperv`

(5) Realized I had to run Vagrant as Administrator in order for it to work (_their error message does not indicate this clearly_)
(6) Success!
(7) Followed the instructions from @dgageot outlined in issue #67
> @qwebek Thanks for the update. As @rneugeba said, you should be in C:\Program Files\Docker\Docker\resources to run the commands. So let me refine the sequence of commands that you could run:
> * exit the application
> * `Stop-Service com.docker.service`
> * `cd 'C:\Program Files\Docker\Docker\resources'`
> * `.\MobyLinux.ps1 -Destroy`
> * check that the VHDX file (C:\Users\Public\Public Documents\Hyper-V\Virtual hard disks\MobyLinuxVM.vhdx) is removed
> * `.\MobyLinux.ps1 -Create`

(8) The last command failed the same way the comment from @qwebek indicated.
(9) Attempt to manually create a VM in Hyper-V with the existing "MobyLinuxVM.vhdx" file (C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx)
(10) Compare settings between docker's "MobyLinuxVM" virtual image in Hyper-V to the new one created in step 7
(11) Failed without much detail. Wouldn't boot making me wonder if it was the .vhdx or the .iso.
(12) Used Hyper-V to "inspect" the .vhdx file and succeeded.
(13) Deleted the previous VM attempt from Hyper-V
(14) Manually created a new VM in Hyper-V with a brand new .vhdx file based on Gen-1 and copied the settings
(15) Failed.
(16) Did steps 11-12 with Gen-2
(17) Success!
(18) For kicks, I tried the "Reset" process from the Docker for Windows GUI as indicated [in a few posts to the Docker Forums](https://forums.docker.com/t/unable-to-send-start-failed-to-start-mobylinux-vm/13258/6):
> `settings->Reset->Reset to factory`
(19) Success!

Now... the odd thing is that I tried the factory reset from the beginning. So, something along the way affected the outcome, or doing it twice was the trick. The first time took FOREVER. In between, I also uninstalled Windows updates, uinstalled Docker and deleted files manually (chose to use `rimraf` from NPM), stopping and starting the docker services, etc. However, I feel something about the steps above actually helped resolve the issue, so I don't highlight these various attempts.

Good luck! I hope someone can find a reproducible solution with the help I've found from others!

**Comment by qwebek** [comment]
Thanks for detailed description Eric, will try some of your steps

Cheers,

**Comment by dgageot** [comment]
@ericis You could also give a more recent version a try. Please tell us if your issue is fixed so that I can close the issue. Thanks a lot!

**Comment by qwebek** [comment]
Hey Eric,

> (10) Compare settings between docker's "MobyLinuxVM" virtual image in Hyper-V to the new one created in step 7

Does this mean you already had MobyLinuxVM VM in Hyper-V after docker isntallation and start?

> (14) Manually created a new VM in Hyper-V with a brand new .vhdx file based on Gen-1 and copied the settings

How did you copy the settings?

Thanks

**Comment by dgageot** [comment]
Hi @ericis @qwebek Do you still have the issue? Did you try a more recent version?

**Comment by qwebek** [comment]
Hi @dgageot 

I have not resolved my issue yet, but It looks like my issue is not related to Docker but to Hyper-V itself
So please close #67  if you like

Thanks.

**Comment by rneugeba** [comment]
@qwebek I assume you were suggesting to close this issue (#76) rather than #67. So closing it. Please feel free to re-open if I mis-understood

**Comment by gokhansengun** [comment]
Tried everything including fresh install of Win 10. Issue appeared to be not enabling VT-x support from VMware :-)

ps: I am running Windows on a Mac
