### ISSUE TITLE
Cannot stop VM MobyLinuxVM in Windows 10

### ISSUE THREAD

**Issue by KADacey** [docker/for-win#760]
**During startup of the Docker service the following error is encountered**:
Unable to execute Start: Unable to stop: Couldn't stop VM MobyLinuxVM
at Fatal, <No file>: line 372
at Stop-VM-Force, <No file>: line 368
at Stop-MobyLinuxVM, <No file>: line 298
at <ScriptBlock>, <No file>: line 379    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.DoStop()
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

**Diagnostic ID**: 33090FE1-136B-4C30-B13B-B0FD22801C42/2017-05-22_15-49-33
**OS**: Windows 10 Pro
**Version**: 1607
**Build**: 14393.1066

This happens every time I start my machine. It appears that the VM is in a bad state as I'm unable to interact with it (can't turn it off, shut it down, etc.) in Hyper-V Manager.

**Comment by KADacey** [comment]
This issue looks very similar to https://github.com/docker/for-win/issues/651.

**Comment by wikrie** [comment]
or maybe it has something to do with general Moby Issue  #748

**Comment by KADacey** [comment]
If I delete the files in "C:\Users\kdacey\AppData\Roaming\Docker" then Docker will start successfully. Obviously this is a terrible workaround as I have to do this on a daily basis when I shut down my machine each night.

**Comment by felipedemacedo** [comment]
I had the same problem ... it may (or may note) be related to the **docker system prune** that I executed days before. The steps I followed to solve it were:
1. Delete the folder 'Docker' in C:\Users\[your_username]\AppData\Local (as @KADacey said) 
2. Restore to factory defaults in Settings -> Reset -> Reset to factory defaults ...

I also noticed that ... **_before this procedure I had something like 32 gb in this file_**: C:\Users\Public\Documents\Hyper-V\Virtual hard disks\MobyLinuxVM.vhdx
and now it's down to less than 2 gb.

**Comment by MiorantsoaRak** [comment]
I had the same probleme. What I did is I've just click on repare Docker in **Panel control -> programs -> Programs and Feature** : right click on Docker and choose repare.

**Comment by JMroczka** [comment]
This is still an issue that needs fixing on Docker for Windows!

**Comment by StingyJack** [comment]
@docker-desktop-robot you are an a**hole.

/remove-lifecycle stale
/lifecycle frozen
