### ISSUE TITLE
Dependency from Docker Desktop Service to Server Service

### ISSUE THREAD

**Issue by danielwagn3r** [docker/for-win#7608]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
No dependency to Server service.

### Actual behavior
Dependency to Server service.

### Information
  - Windows Version: Windows 10 1803
  - Docker Desktop Version: 2.3.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior
Since Docker Desktop for Windows 2.3.0.3 there seem's to be a runtime dependency of the Docker Desktop Service to the Server Service (LanmanServer). This effectively blocks usage of Docker in environments with security hardened Windows clients.

As in https://www.docker.com/blog/deep-dive-into-new-docker-desktop-filesharing-implementation/ described, with the new implementation of filesharing using FUSE this dependency shouldn't be necessary.

**Comment by stephen-turner** [comment]
Sorry, it is still required, see #5150.

**Comment by danielwagn3r** [comment]
This issue discussed installation.

However since 2.3.0.3 it's required for runtime, too.  Which worsened the situation. 

Any reason for that?

**Comment by stephen-turner** [comment]
Hmmm, maybe I was wrong, but I thought we only checked it at installation time. Can you paste a screenshot of the error?

But in any case, it's required at installation time because it's required to run. I think it was named pipes it was needed for, if I recall correctly.

**Comment by danielwagn3r** [comment]
Here's the dependency at windows service level

![image](https://user-images.githubusercontent.com/5670510/87060040-51705800-c20a-11ea-9e1c-80b2fadfaa16.jpeg)

**Comment by danielwagn3r** [comment]
We could handle installation time with a limited exception. However for runtime this is a blocker at least for us.

**Comment by stephen-turner** [comment]
I don't think we can remove this requirement, sorry.

**Comment by danielwagn3r** [comment]
This seem's to be inconsistent with the announcement here https://www.docker.com/blog/new-filesharing-implementation-in-docker-desktop-windows/ where you stated:

> The new version can’t conflict with organisation-wide security policies as we don’t need to use Administrator privileges to share the drive and create a firewall exception for port 445.

Essentially the current version isn't usable and there is still no explanation what the server service is used for, if the new file sharing implementation doesn't rely on it anymore.
