### ISSUE TITLE
Kubernetes Not working. stuck at status Starting on the dashboard

### ISSUE THREAD

**Issue by jawadSharif** [docker/for-win#7609]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6DAD3F8D-3F27-4E07-A4F5-D66484CEDF01/20200709110659

### Expected behavior
Kubernetes should start when its enabled in settings
### Actual behavior
it always show kubernetes: starting 
### Information
issue is with latest version. intially it was working fine but suddenly kubernetes stopped working 

  - Windows Version: 10
  - Docker Desktop Version: 2.3.0.3 (45519)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: running inside a windows vm

### Steps to reproduce the behavior

  1. created a cluster 
  2. reset kubernetes cluster
  3. restart docker.

**Comment by jawadSharif** [comment]
![image](https://user-images.githubusercontent.com/18321140/87038062-7d311500-c1ed-11ea-9905-a4e958ce25a5.png)

**Comment by jawadSharif** [comment]
![image](https://user-images.githubusercontent.com/18321140/87038188-aea9e080-c1ed-11ea-8a48-95d81b4268cb.png)

**Comment by ZhangDi-d** [comment]
while docker is running，make sure that you already have thoes images。 then try to start k8s.

![image](https://user-images.githubusercontent.com/29948535/87540823-dcea5d00-c6d2-11ea-9281-c76b252f917f.png)

**Comment by jawadSharif** [comment]
even docker images does not work
![image](https://user-images.githubusercontent.com/18321140/88797280-61dd7800-d1a3-11ea-8d59-dc58f5d65152.png)
