### ISSUE TITLE
Cannot start Docker - MobyLinuxVM missing

### ISSUE THREAD

**Issue by AntonyAspect** [docker/for-win#761]
### Expected behavior

Docker to start,
### Actual behavior
Error that the MobyLinuxVM is missing.
### Information

96353603-EE95-42EF-957F-C35865C8183C/2017-05-23_13-31-37

**Comment by wikrie** [comment]
sound like the same issue as #748
https://github.com/docker/for-win/issues/748

**Comment by aaljaseem** [comment]
The solution is to make external virtual switch on hyper-v.
It worked

**Comment by BE55Roberts** [comment]
How do you make the external virtual switch change? When I bring up Hyper-V, there is no MobilLinuxVM. I'd like to recreate it. Anyone know how?
