### ISSUE TITLE
Getting an error when pulling image: failed to register layer: re-exec error: exit status 1: output: Failed to OpenForBackup failed in Win32

### ISSUE THREAD

**Issue by garrardkitchen** [docker/for-win#762]
Through lack of disk space on primary drive (C) I want to set a different location for images etc.

Following documented instructions I use UI and select > Settings > Daemon tab > switch to Advanced then change location of images etc to f:\docker > apply change.  However, when it finishes pulling down image it errors.

I have tried several documented work arounds, including disabling UAC, disabling local security policy (UAC: Run all administrators...), adding folder to Windows Defender exclusions but still I get the error.

Can anybody help?

### Expected behavior

Image be pulled down and placed in new location (f:\docker), I get to create multiple container solution via VS 2017 and push compose file to Service Fabric cluster

### Actual behavior

```
F:\vsts> docker pull microsoft/aspnet
Using default tag: latest
latest: Pulling from microsoft/aspnet
3889bb8d808b: Extracting [==================================================>]  4.07 GB/4.07 GB
1a106d48ef90: Download complete
acdccdc9a6ca: Download complete
756cefdb1714: Download complete
6817b055148f: Download complete
9d0da2545409: Download complete
6030db3b7ee4: Download complete
failed to register layer: re-exec error: exit status 1: output: Failed to OpenForBackup failed in Win32: open \\?\F:\docker\windowsfilter\9f428d5de861859d8
22ccf3027c7cf07f49c5aa34a5106f194202dae1bfcea4a\Files: A required privilege is not held by the client. (0x1f) \\?\F:\docker\windowsfilter\9f428d5de861859d8
22ccf3027c7cf07f49c5aa34a5106f194202dae1bfcea4a\Files
F:\vsts>
```

### Information

  - Version 17.03.1-ce-win12 (12058), Channel: stable, d1db126
  - Docker for Windows
  - Community Edition

### Steps to reproduce the behavior

  1. Switch to docker for windows 
  2. Via docker UI > Settings > Daemon > Switch to advanced and enter `{"graph":"f:\\docker"}` > apply. Obviously change f:\\docker to align with your non-C drive target path.
  3. Open up either PS or command prompt and enter `docker pull microsoft/aspnet`
  4. Wait ~20 mins for image to download
  5. Observe error

Warmest regards,

Garrard.

**Comment by garrardkitchen** [comment]
My f drive was using exFAT so reformatted as NTFS and all working as expected after reinstall.

**Comment by friism** [comment]
@jhowardmsft do you think it would make sense to provide a better error in case the graphdriver is placed on a fat-formatted drive?

**Comment by jhowardmsft** [comment]
Sure. Open an issue. Low priority though relatively.

**Comment by friism** [comment]
Done: https://github.com/moby/moby/issues/33391

**Comment by Sawan-Verma** [comment]
C:\Users\p10406792>docker image pull microsoft/windowsservercore
3889bb8d808b: Extracting [==================================================>]   4.07GB/4.07GB
latest: Pulling from microsoft/windowsservercore
failed to register layer: re-exec error: exit status 1: output: Failed to OpenForBackup failed in Win32: open \\?\C:\ProgramData\Docker\windowsfilter\72270bf5a233ba621ff9b39d88131ff9dfe642414d33ae4820719b9e1410dcb7\Files\Windows\System32\scrnsave.scr: Access is denied. (0x1f) \\?\C:\ProgramData\Docker\windowsfilter\72270bf5a233ba621ff9b39d88131ff9dfe642414d33ae4820719b9e1410dcb7\Files\Windows\System32\scrnsave.scr

**Comment by byorxyz** [comment]
I'm getting the same error. 

C:\...>docker build -t deepcrm .

==error message==

failed to register layer: re-exec error: exit status 1: output: Failed to OpenForBackup failed in Win32: open \\?\C:\ProgramData\Docker\windowsfilter\d49866c14a915ce7a6cbb408ec5edb23c5a8467be90e26e13855897c1a98610b\usr\share\man\man3\Locale::gettext.3pm.gz: The filename, directory name, or volume label syntax is incorrect. (0x1f) \\?\C:\ProgramData\Docker\windowsfilter\d49866c14a915ce7a6cbb408ec5edb23c5a8467be90e26e13855897c1a98610b\usr\share\man\man3\Locale::gettext.3pm.gz

**Comment by subash544772** [comment]
i am also getting the same error 
failed to register layer: re-exec error: exit status 1: output: Failed to OpenForBackup failed in Win32: open \\?\C:\ProgramData\docker\windowsfilter\d8cfddf350dd25e7e424e6710798a68fe3905f583382747e19a38dfb4ba7e37f\usr\share\man\man3\Locale::gettext.3pm.gz: The filename, directory name, or volume label syntax is incorrect. (0x1f) \\?\C:\ProgramData\docker\windowsfilter\d8cfddf350dd25e7e424e6710798a68fe3905f583382747e19a38dfb4ba7e37f\usr\share\man\man3\Locale::gettext.3pm.gz

any help and suggestion will really be helpful.

**Comment by amracel** [comment]
Similar issue here. I am on a Windows 10 machine with Docker Community Edition Version 18.03.0-ce-win59. I am in an environment with ID cards so there's no passwords. So I switched from Linux containers to Windows to avoid the need for a local admin user with a password. I tied to pull down the microsoft/windowsservercore image and received the following error:
```
failed to register layer: re-exec error: exit status 1: output: Failed to OpenForBackup failed in Win32: open \\?\C:\ProgramData\Docker\windowsfilter\1601449730d3dc6ac2f66a62092122cdd778ffadf981962a8ad60c6b98b05254\Files\ProgramData\Microsoft\Windows\Start Menu\Programs\desktop.ini: Access is denied. (0x1f) \\?\C:\ProgramData\Docker\windowsfilter\1601449730d3dc6ac2f66a62092122cdd778ffadf981962a8ad60c6b98b05254\Files\ProgramData\Microsoft\Windows\Start Menu\Programs\desktop.ini
failed to register layer: re-exec error: exit status 1: output: Failed to OpenForBackup failed in Win32: open \\?\C:\ProgramData\Docker\windowsfilter\1601449730d3dc6ac2f66a62092122cdd778ffadf981962a8ad60c6b98b05254\Files\ProgramData\Microsoft\Windows\Start Menu\Programs\desktop.ini: Access is denied. (0x1f) \\?\C:\ProgramData\Docker\windowsfilter\1601449730d3dc6ac2f66a62092122cdd778ffadf981962a8ad60c6b98b05254\Files\ProgramData\Microsoft\Windows\Start Menu\Programs\desktop.ini

```
The file referenced doesn't exist. And I have access to read the ProgramData/Docker/windowsfilter directory.
Similar issue here. I am on a Windows 10 machine with Docker Community Edition Version 18.03.0-ce-win59. I am in an environment with ID cards so there's no passwords. So I switched from Linux containers to Windows to avoid the need for a local admin user with a password. I tied to pull down the microsoft/windowsservercore image and received the following error:
```
failed to register layer: re-exec error: exit status 1: output: Failed to OpenForBackup failed in Win32: open \\?\C:\ProgramData\Docker\windowsfilter\1601449730d3dc6ac2f66a62092122cdd778ffadf981962a8ad60c6b98b05254\Files\ProgramData\Microsoft\Windows\Start Menu\Programs\desktop.ini: Access is denied. (0x1f) \\?\C:\ProgramData\Docker\windowsfilter\1601449730d3dc6ac2f66a62092122cdd778ffadf981962a8ad60c6b98b05254\Files\ProgramData\Microsoft\Windows\Start Menu\Programs\desktop.ini
failed to register layer: re-exec error: exit status 1: output: Failed to OpenForBackup failed in Win32: open \\?\C:\ProgramData\Docker\windowsfilter\1601449730d3dc6ac2f66a62092122cdd778ffadf981962a8ad60c6b98b05254\Files\ProgramData\Microsoft\Windows\Start Menu\Programs\desktop.ini: Access is denied. (0x1f) \\?\C:\ProgramData\Docker\windowsfilter\1601449730d3dc6ac2f66a62092122cdd778ffadf981962a8ad60c6b98b05254\Files\ProgramData\Microsoft\Windows\Start Menu\Programs\desktop.ini

```
The file referenced doesn't exist. And I have access to read the ProgramData/Docker/windowsfilter directory.

**Comment by shoneworn** [comment]
I have fixed this issue by myself , Look here https://blog.csdn.net/shoneworn/article/details/80621120 . I have mark it with my blog .

**Comment by B5045438** [comment]
@shoneworn The issue is I switched to windows to fix another issues caused by the linux installation for docker not playing well with virtual box (for the docker machine) because it wants hyper-v which docker with linux doesn't like.

**Comment by shoneworn** [comment]
@B5045438 Is your system win10 ?  normally ，it's default installed hyper-v when you installing docker besides you system is win7 which need you install virtual box .

**Comment by amracel** [comment]
@shoneworn , yes, my system is 'native' Win10.
