### ISSUE TITLE
Sharing drives/folders?

### ISSUE THREAD

**Issue by MBK75** [docker/for-win#7621]
The online documentation right now for sharing drives/folders with Docker for Windows is out of date (at least what I can find), and the UI options shown do not exist any longer.

I have had problems using an alternate drive from C:\, and I think this may be related.

What is the new procedure to share drives/folders with docker overall and/or with Containers in the latest version?

**Comment by stephen-turner** [comment]
Are you using the Hyper-V backend or the WSL 2 backend? If it's WSL 2, the UI isn't needed any more, Windows handles it.

**Comment by MBK75** [comment]
Hi Stephen, I'm not sure - is there a way to tell?  I used the defaults when installing.

It looks like I get access denied messages when trying to use PowerShell to copy files from the container to a removable E:\ drive.  I also can't keep my images/containers on the E:\ drive or they fail during creation, so I think the two are possibly linked.  Any suggestions are welcome

**Comment by stephen-turner** [comment]
The General tab on Settings will tell you which you're using.

**Comment by MBK75** [comment]
Ah, I am using Hyper-V.  I will try out the WSL 2.

**Comment by MBK75** [comment]
Any takers on sharing drives with Windows Containers?  Docker for Windows can't seem to use my D:\ drive or an external USB-C drive that I have

**Comment by stephen-turner** [comment]
Sorry, I missed your previous message. For Windows containers, we also don't handle the file sharing, which is why you're not seeing the options. That code is in the upstream engine, https://github.com/moby/moby. I'm not aware of any reason why it can't share a different drive, but I'm not an expert in that component.
