### ISSUE TITLE
Feature request: Controlling docker-desktop node name

### ISSUE THREAD

**Issue by hubiierik** [docker/for-win#7626]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics

### Expected behavior
As an docker operator perusing swarm nodes on a master node
I would like to see a list of nodes with unique hostnames
In order to easily identify nodes subject for further actions.

### Actual behavior
When the swarm includes multiple `docker-desktop` nodes, 
it is hard to discriminate between `docker-desktop` nodes since they all show up  with the same hostname.

It is possible that the hostnames shown in the node list are actually **disrto names**, which in that case **could be considered a bug**.

### Information
Ex. picked from: https://stackoverflow.com/questions/59824034/how-to-change-docker-node-hostname 
```
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS      ENGINE VERSION
pl0b3aa6vit00unxqzzbmyhbe     docker-desktop      Down                Active                                  19.03.5
w2t3uk2gjnpn33g0sktp8le1s     docker-desktop      Ready               Active                                  19.03.5
yys70s53u2iujqa8oq161c2fv     docker-desktop      Down                Active                                  19.03.5
hyuu5n7o7c78uf2nf96680og6 *   swarmpit            Ready               Active              Leader              19.03.5
c5wrnvu25dbm655yn2dvir0pn     vpn                 Ready               Active                                  19.03.5
```

The listed hostnames are probably not hostnames at all since the actual hostname of the docker-desktop node is different from the listing. Drawn from a different example, here is what the hostname looks on one of the nodes:

```
> wsl -d docker-desktop hostname
DESKTOP-QXXXXXX   <-- Hostname as expected
```
As can bee seen, the docker-desktop distro inherits the hostname from Windows 10.
It would be useful to have some means of controlling how docker-desktop nodes present themselves.
Alternatively, if the column name `HOSTNAME` carries any weight, nodes should show up with their true hostname.

**Comment by hubiierik** [comment]
Additional information:
I added an Unbuntu repo to WSL2 and installed docker in that.
Then I let the docker on Ubuntu join my swarm.
This shows up with the expected `ESKTOP-QXXXXXX` hostname in my `docker node ls` list.

**Comment by leukosaima** [comment]
Agreed, this would be nice.

**Comment by danipisca07** [comment]
Totally upvoting this, either use the actual hostname or provide a way to set this in docker-desktop gui

**Comment by TheOtherRealm** [comment]
And it can lead to `Error response from daemon: node manager is ambiguous (2 matches found)` when you try to do operations such as: `docker node demote manager`
I tried using IDs instead but this gave me an error

**Comment by pnatel** [comment]
Can we reopen this issue?
It also occurs on the MAC desktop client
