### ISSUE TITLE
Windows Event Log is holding a file handle to dockerd

### ISSUE THREAD

**Issue by sixcorners** [docker/for-win#7627]
How do I kill windows event log?

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker installs
### Actual behavior
![image](https://user-images.githubusercontent.com/585501/87225954-52ae9b80-c356-11ea-93c9-07ca5e3aa021.png)

![image](https://user-images.githubusercontent.com/585501/87225947-488c9d00-c356-11ea-85a3-2cfe15600327.png)

### Information

idk how to reproduce this.
I can't install docker for windows edge.
  - Windows Version:
![image](https://user-images.githubusercontent.com/585501/87225977-7376f100-c356-11ea-846a-9a879320f92e.png)
Why can't I copy paste from this stupid dialog box

  - Docker Desktop Version: 2.3.3.1
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
I think HyperV is enabled which actually puts everything in a VM. But no not really.
### Steps to reproduce the behavior

  1. have docker for windows installed (stable)
  2. install docker for windows (edge)

**Comment by sixcorners** [comment]
Workaround:
kill the svchost running the event log service.
do find it run process explorer and click the binoculars
![image](https://user-images.githubusercontent.com/585501/87226119-5c84ce80-c357-11ea-9de6-e1ed83aaf9c8.png)

**Comment by brettjacobson** [comment]
/remove-lifecycle stale

This isssue is not stale, its just being ignored.

https://github.com/docker/for-win/issues/4754 originally reported this problem in September 2019.

It makes installing an update via automation incredibly painful.  It also affected DockerEE.
