### ISSUE TITLE
unable to resolve docker endpoint: open C:\Users\username\.docker\machine\machines\default\ca.pem: The system cannot find the path specified.

### ISSUE THREAD

**Issue by caroe2014** [docker/for-win#7629]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
By typing: docker --version it should show the version. The truth is that I can not do anything
### Actual behavior
As soon as I type "docker" on the command prompt ans press "Enter" the following message is displayed:

unable to resolve docker endpoint: open C:\Users\Username\.docker\machine\machines\default\ca.pem: The system cannot find the path specified.

I looked into that path and the ca.pem file doesn't exist.

### Information

  - Windows Version: 10
  - Docker Desktop Version: 2.3.0.3 (45519)
  - Channel: stable
  - Composer: 1.25.5
  - Engine: 19.03.8
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. For the issue to happen I don't need any Dockerfile.
  2. I go to the command prompt.
  3. Type: docker --version, and the issue will occur right away.

Troubleshooting Steps I tried:
Uninstall docker for Desktop and installed it again. I was hoping it would install the certificate, ca.pem, but it didn't happen.

**Comment by caroe2014** [comment]
I solved the my own issue:
The previous versions had the public under: C:\Users\username\.docker\machine\machines\default\. The environment variable is pointing to it: DOCKER_CERT_PATH=C:\Users\username\.docker\machine\machines\default\

The issue is that the new version has the public key under: C:\Users\username\.docker\machine\certs\ If I upgrade it or uninstall it and installed it again, it doesn't update the DOCKER_CERT_PATH environment variable to the new path for the public key but keep the old one.

Solution:
I had to manually update the DOCKER_CERT_PATH=C:\Users\username\.docker\machine\certs\
Problem solved.

**Comment by fjt523** [comment]
Another case for the same error: 
**PC Information:**
Win10 home 2004, os 19041.264
wsl2 (ubuntu, with docker.io version 18.xx.xx installed). docker works fine in wsl2.

**Actual behavior**
Install 'Docker Desktop Installer (for **win10 home**) Version 2.3.0.4, stable channel'. 
Then type 'docker' in cmd.exe
_PS C:\Users\fjt\getting-started> docker version
unable to resolve docker endpoint: open C:\Users\fjt\.docker\machine\machines\default\ca.pem: The system cannot find the path specified._

in wsl2:
'docker version' runs fine.  and it report version is '18.xx.xx'.   _The original output is missing._

**Solution**
Remove 'docker.io' in wsl2. Then reinstall 'Docker Desktop Installer (win10 home)' in Win10

**Note**
The direcotry 'C:\Users\fjt\\\.docker\machine\' doesn't exits. So I delete the windows environment  variables: DOCKER_CERT_PATH DOCKER_MACHINE_NAME, DOCKER_TLS_VERIFY. 
And docker runs ok:
_C:\Users\fjt\getting-started>docker build -t docker101tutorial .
Sending build context to Docker daemon   10.2MB
Step 1/21 : FROM python:alpine AS base
alpine: Pulling from library/python
df20fa9351a1: Pull complete
...
Status: Downloaded newer image for python:alpine_

**Comment by Manvityagi** [comment]
> I solved the my own issue:
> The previous versions had the public under: C:\Users\username.docker\machine\machines\default. The environment variable is pointing to it: DOCKER_CERT_PATH=C:\Users\username.docker\machine\machines\default\
> 
> The issue is that the new version has the public key under: C:\Users\username.docker\machine\certs\ If I upgrade it or uninstall it and installed it again, it doesn't update the DOCKER_CERT_PATH environment variable to the new path for the public key but keep the old one.
> 
> Solution:
> I had to manually update the DOCKER_CERT_PATH=C:\Users\username.docker\machine\certs
> Problem solved.

Thanks, it saved my day!

**Comment by pankajan05** [comment]
I solved my issue also.
thank you for this solution. After I update the _**DOCKER_CERT_PATH=C:\Users\username.docker\machine\certs**_ in my environment variable it work fine.

**Comment by bakcyll** [comment]
how can I change this variable? where it is?

**Comment by yogat3ch** [comment]
> how can I change this variable? where it is?

@bakcyll Environment Variables on Windows. Windows key + S then type "Environment" and it should give the link for "Edit the system environmental variables"
