### ISSUE TITLE
sudo service docker won't work for wsl 2

### ISSUE THREAD

**Issue by auspic7** [docker/for-win#7635]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 8C2E2B56-0E86-4E49-BAF5-B06DB3F99738/20200712115912

### Expected behavior
`sudo service docker` command ran on wsl2 (4.19.121-microsoft-standard) should print service status
### Actual behavior
`sudo service docker` command prints `docker: unrecognized service`
### Information

  - Windows Version:  20161.1000, Windows Feature Experience Pack 120.16201.0.0
  - Docker Desktop Version: 2.3.0.3 (45519)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: nope
I followed instructions in [docker documentation page for wsl](https://docs.docker.com/docker-for-windows/wsl/) so docker can installed to my windows, and checked the command `docker run -d -p 80:80 docker/getting-started` on ubuntu running successfully, but the `service` command won't work as described above.

### Steps to reproduce the behavior

  1. follow the instructions in [here](https://docs.docker.com/docker-for-windows/wsl/)
  2. `sudo service docker` on wsl2 ubuntu

**Comment by stephen-turner** [comment]
I'm not sure why you were expecting this to work. Or is it a feature request rather than a bug report?

**Comment by auspic7** [comment]
> I'm not sure why you were expecting this to work. Or is it a feature request rather than a bug report?

nope, Sorry but I think I am not understanding the mechanism of docker on wsl. I thought docker daemon is supposed to be running because I can use docker on wsl.
