### ISSUE TITLE
Changing the default user shell breaks the WSL integration

### ISSUE THREAD

**Issue by nelak** [docker/for-win#7653]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 480F74F1-FDD1-4618-937C-CA3F6A66E5E2/20200714130704

### Expected behavior
Changing the default shell from `/bin/bash` shouldn't block the wsl integration
Reverting the shell back to `/bin/bash` fixes the issue

### Actual behavior
Changing the default shell from `/bin/bash` for a user disables the wsl integration because the `docker.sock` cannot be created
`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

### Information

  - Windows Version: 10
  - Docker Desktop Version: 2.3.0.3 (45519)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. `chsh -s /home/linuxbrew/.linuxbrew/bin/fish`
  2. `wsl --terminate Ubuntu`
  3. `wsl ~`
  4. `docker ps`

**Comment by stephen-turner** [comment]
@simonferquel Have you seen this issue before?

**Comment by simonferquel** [comment]
I previously fixed an issue like this one. Probably a regression with the cloud cli stuff.

**Comment by stephen-turner** [comment]
2.3.0.3 is the latest Stable, it doesn't have the cloud CLI. Do you know when you fixed it, @simonferquel? Maybe the change has only reached Edge not Stable?

**Comment by simonferquel** [comment]
it was a long time ago, i'll look at logs

**Comment by simonferquel** [comment]
Ok, this is the interesting log:
`[10:06:33.139][WslIntegrationAgent-Ubuntu5][Info   ] 2020/07/14 10:06:33 Unable to setup docker user group: exit status 6`
There is probably something that don't force using `sh -c` explicitly. I'll have a look

**Comment by simonferquel** [comment]
@nelak with fish enabled by default, what does `wsl -d Ubuntu5 whoami` returns ?

**Comment by simonferquel** [comment]
(that is the only script that was not explicitly running with /bin/sh)

**Comment by nelak** [comment]
@simonferquel it returns the default user that has been setup in `/etc/wsl.conf`

**Comment by simonferquel** [comment]
I got a build for you to try here: https://desktop-stage.docker.com/win/stable/46707/Docker%20Desktop%20Installer.exe

**Comment by nelak** [comment]
@simonferquel Looking good!!!
Thanks a lot! I had been trying to figure this one out since the preview releases of WSL2
💯

**Comment by nelak** [comment]
@simonferquel Do you know when this would be reaching the stable/edge channel so I know when I can move to the official builds again. Thanks!

**Comment by simonferquel** [comment]
I don't have an exact timing, but next stable will have it.
Not entirely sure for edge, probably shortly after.

**Comment by stephen-turner** [comment]
We just released Stable 2.3.0.4, and I think this is fixed in it.

**Comment by nelak** [comment]
Yeah, I can confirm it was in the release notes and it is fixed in 2.3.0.4
Thanks a lot! 💯

**Comment by stephen-turner** [comment]
Great, thanks for the confirmation, I'll close the ticket.
