### ISSUE TITLE
Windows 10 - Hardware assisted virtualization and data execution protection

### ISSUE THREAD

**Issue by AustinMaddox** [docker/for-win#766]
### Expected behavior
Docker to start up successfully (green light).

### Actual behavior
Failed to start up - refer to attached screenshot.

![capture](https://cloud.githubusercontent.com/assets/961446/26433582/e167a37e-40c0-11e7-9473-a518768a7e3d.png)

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu. A diagnostic was uploaded with id: C7A0886B-80F2-42BC-BB11-D27466D166C7/2017-05-24_20-38-59
  - Windows 10 Pro
  - Hyper-V is enabled. Virtualization is enabled. DEP is enabled.

### Steps to reproduce the behavior

1. Install the latest docker for windows from the stable channel
2. Launch docker for windows

**Comment by friism** [comment]
Your CPU doesn't have SLAT, so I don't think Docker for Windows will work: https://en.wikipedia.org/wiki/Second_Level_Address_Translation

We have an issue to show a better install error.
