### ISSUE TITLE
Docker Desktop not starting correctly

### ISSUE THREAD

**Issue by jbrown9100** [docker/for-win#7662]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 83667856-D5F8-4FC1-A07B-4649712E9111/20200714214129

### Actual behavior
Docker fails to start correctly on Windows boot.

### Information

  - Windows Version: Windows 10 Insider Build 20161
  - Docker Desktop Version: 2.3.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Restart my windows PC
  2. Docker starts but fails to completely start
  3. Left click on Docker Desktop manager and select "Check for updates".
  4. Docker starts running correctly.

**Comment by abrose** [comment]
I'm experiencing exactly the same issue  on Windows 10 Ver. 2004 (Build 19041.388) and Docker Engine Version 19.03.12. After clicking on "Check for updates" the Docker taskbar icon indicates Docker started and running but when opening Docker Settings the status is "starting" and won't change to running.

Diagnostics ID: 15ED0175-DF30-4C44-A2ED-B029247E6A4D/20200805054658
