### ISSUE TITLE
Windows container on Windows 10 fails to start with "-m 4g" but runs OK with "-m 3g"

### ISSUE THREAD

**Issue by deafsheep** [docker/for-win#767]
### Expected behavior
Command `docker run -ti -m 4g microsoft/nanoserver cmd` should work fine on a Windows 10 machine with 32 Gb RAM.

### Actual behavior

Command results in this error message:
`
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container ad5daea5af71e433efbe4ced27e3553c009be78f2cd2ea5ee9cf63798fdc890e encountered an error during CreateContainer: failure in a Windows system call: A connection could not be established with the Virtual Machine hosting the Container. (0xc0370108) extra info: {"SystemType":"Container","Name":"ad5daea5af71e433efbe4ced27e3553c009be78f2cd2ea5ee9cf63798fdc890e","Owner":"docker","IsDummy":false,"IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\ad5daea5af71e433efbe4ced27e3553c009be78f2cd2ea5ee9cf63798fdc890e","Layers":[{"ID":"05ed9e7f-50fc-5547-b50f-0b3bd04b7c46","Path":"C:\\ProgramData\\Docker\\windowsfilter\\87ff91487e924ad07948b9d75921a6e5ff836000a0973fb3a9f155ba1c6f9c56"},{"ID":"2023745b-c852-5a0b-a1c9-d6e583a23714","Path":"C:\\ProgramData\\Docker\\windowsfilter\\aede6a6a41c139f7cf2648a52b9bac0d938da809ca5cc66c111cab4cac9cb450"}],"MemoryMaximumInMB":4096,"HostName":"ad5daea5af71","MappedDirectories":[],"SandboxPath":"C:\\ProgramData\\Docker\\windowsfilter","HvPartition":true,"EndpointList":["3eac4fd9-2ac4-4575-bfbd-a2e46b5aba70"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\87ff91487e924ad07948b9d75921a6e5ff836000a0973fb3a9f155ba1c6f9c56\\UtilityVM"},"Servicing":false,"AllowUnqualifiedDNSQuery":true}.
`

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
`E5BB9482-3B4D-4744-8BD2-05932B2311E4/2017-05-23_23-00-27`

Clean install of docker on Windows 10
```
OS: Windows 10 Pro
Edition: Professional
Id: 1703
Build: 15063
BuildLabName: 15063.0.amd64fre.rs2_release.170317-1834
```

And docker:
```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

### Steps to reproduce the behavior

  1. Run `docker run -ti -m 3g microsoft/nanoserver cmd` - works fine.
  2. Run `docker run -ti -m 4g microsoft/nanoserver cmd` - times out with error message (see above).

Also this issue is discussed:
https://forums.docker.com/t/windows-container-runs-with-m-3g-but-fails-to-start-with-m-4g/32568
And:
https://stackoverflow.com/questions/44145351/docker-for-windows-container-is-not-starting-with-m-4g-but-works-fine-with-m-3

I can provide any additional info for investigation.

**Comment by friism** [comment]
From your forum post I understand that you're running this in VMWare. This might be the problem, so it would be interesting if you can reproduce outside of VMWare.

**Comment by deafsheep** [comment]
Thank you for your answer.

Sorry for creating some confusion, but if you check my 3rd post
https://forums.docker.com/t/windows-container-runs-with-m-3g-but-fails-to-start-with-m-4g/32568/4

You can see that I had the same thought and I was indeed able to reproduce the same problem on physical machine with Windows 10 and 32 Gb RAM.

The diagnostics id I provided is that post (E5BB9482-3B4D-4744-8BD2-05932B2311E4/2017-05-23_23-00-27) is from a physical machine, not a VM.

Also same post has a little more details on my second attempt to reproduce this issue.

**Comment by deafsheep** [comment]
Hello, is there any news related to this issue?
Were you able to reproduce this problem?

Maybe I could provide any assistance?

This problem is a show stopper, because this means you can't develop memory intensive applications for containers on Windows 10.

**Comment by MikhailTymchukDX** [comment]
Same problem still persists for me. Running Windows 10 with 16 GB RAM.

Diagnostic ID from "Diagnose & Feedback" in the menu.
`DE1DFB14-3272-4DF5-A007-C1A6F902DD09/2017-08-28_19-17-45`

```
> docker version
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:48:20 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 23:03:03 2017
 OS/Arch:      windows/amd64
```

```
> docker info
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 3
Server Version: 17.06.1-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 14393 (14393.1358.amd64fre.rs1_release.170602-2252)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 15.69GiB
Name: Classified
ID: Classified
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 24
 System Time: 2017-08-28T19:18:47.8363469+03:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by elweilando** [comment]
I have a similary problem. 
microsoft/nav-docker#97

**Comment by kine** [comment]
Similar problem for me. Cannot run container with more than 2GB RAM on my desktop with 16GB RAM and Windows 10 Enterprise.
`Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.12.0-ce-rc2
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 15.7GiB
Name: ksacek
ID: 3PEH:KSNC:M3B7:NHSP:S7UG:2EVU:6TPO:MNCX:WSPC:O5OZ:4XWE:HVDZ
Docker Root Dir: G:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 26
 System Time: 2017-12-14T16:09:23.5044207+01:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false`

**Comment by DominikGebhart** [comment]
There seems to be an issue with specific CPUs that do not support 1GB pages, according to [this issue]( https://github.com/docker/for-win/issues/1094).
