### ISSUE TITLE
Issue: docker Windows Container mode"Windows conatiners supports requires a windows 10 build >=14372"

### ISSUE THREAD

**Issue by admsense** [docker/for-win#768]
### Expected behavior
I want to switch to docker Windows Container mode as I am using Docker for Windows
### Actual behavior
But while trying to switch to docker Windows Container mode it is showing message that "**Windows conatiners supports requires a windows 10 build >=14372**"
### Information
Diagnostic ID: 0F71A533-3D1D-4133-84BC-50B8B032D69C/2017-05-30_11-02-27
I want to run this command: `docker build -t nativebuildimage -f .\Dockerfile.windows .`
But I got this output:
**Sending build context to Docker daemon 36.13 MB
Step 1/7 : FROM microsoft/windowsservercore
latest: Pulling from microsoft/windowsservercore
3889bb8d808b: Pulling fs layer
1a106d48ef90: Downloading
unknown blob**
After this I was suggested to switch to docker Windows Container mode. 
And then I got above issue.
I also tried with Docker for Windows - Edge Channel, but same problem appeared. 
  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by friism** [comment]
@admsense can you please run diagnostics and include the diagnostic id?

**Comment by admsense** [comment]
@friism  can you please guide, how to run this diagnostics?

**Comment by friism** [comment]
https://docs.docker.com/docker-for-windows/#diagnose-and-feedback

**Comment by admsense** [comment]
@friism 0F71A533-3D1D-4133-84BC-50B8B032D69C/2017-05-30_11-02-27

**Comment by mrkkhattak** [comment]
I also faced this issue and have submitted my feed back. 
B77E4D3E-B0EA-4040-A1A6-F0135E8869C1/2017-06-20_16-01-25

I have tried both with Stable and Edge versions and result is same.
