### ISSUE TITLE
Docker VM fails to obtain an IP address so connections to containers fail

### ISSUE THREAD

**Issue by Jiia** [docker/for-win#769]
### Expected behavior
MobyLinuxVM obtains an IP on boot and connection to containers work fine.

### Actual behavior
MobyLinuxVM fails to obtain an IP address and containers can't be connected to from the host.

### Information

 - Diagnostic ID: EA07C4A8-6D8A-4B9D-A574-F9EF7AA4D044/2017-05-25_23-42-32
 - Windows 10 Pro N v.1607 build 14393.1198

### Steps to reproduce the behavior

  1. Install docker
  2. Open Hyper-V and check Networking status for MobyLinuxVM
  3. IP Address field is empty
  4. Create any container, open a port and ping it
  5. Network unreachable

### Other

I've tested this with the latest stable and latest edge with the same result. Reinstalled Docker several times. This is the first time I'm running Docker on this machine. Connections from inside the container to the web work fine but connections from host to the containers fail. I'm currently unable to do anything with Docker on Windows while the problem persists. I found a similar thread from last year but that particular issue is supposed to have been fixed several months ago.

![mobylinux-noip](https://cloud.githubusercontent.com/assets/5290053/26469904/5ce6089a-41a4-11e7-9822-1fdd993c46bc.PNG)

![mobylinux-noip2](https://cloud.githubusercontent.com/assets/5290053/26469996/b77cfb1a-41a4-11e7-8bc7-8aedf83b6f33.PNG)

**Comment by BMarinov** [comment]
Me and a colleague have the exact same problem (on both dev machines). The VM is inaccessible and no amount of tinkering seems to be helping. I even tried it at home (Windows 10 Fall Update) and sadly I couldnt get it working either.

When can we expect an update on the issue?

**Comment by juliolpiva** [comment]
same problem.

**Comment by sdindiver** [comment]
I am facing same problem. Is there any workaround

**Comment by remyoucef** [comment]
Is there a solution?

**Comment by remyoucef** [comment]
@juliolpiva @sdindiver in case you don't find a solution. You should use "localhost" inside Windows and use "host.docker.internal" inside containers.
More infos: https://docs.docker.com/docker-for-windows/networking/#use-cases-and-workarounds

**Comment by javlc** [comment]
This issue keeps happening, Docker Desktop for Windows
Docker version 18.09.2, build 6247962

/lifecycle frozen

**Comment by Elardzhi** [comment]
any update on this?

**Comment by Bernolt** [comment]
Up
