### ISSUE TITLE
Docker-machine commands failing in Docker for Windows

### ISSUE THREAD

**Issue by talaniz** [docker/for-win#770]
### Expected behavior
`docker-machine start default`, `docker-machine env` and `docker-machine rm default` should be able to start, run the env command and remove the default machine.

### Actual behavior
`docker-machine start default` fails with exit status 1. 
`docker-machine env`, `docker-machine rm default` both fail with Error checking TLS connection: Host is not running.

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
    CD27494F-9BB2-487A-9B14-F71363087816/2017-05-25_18-18-25

### Steps to reproduce the behavior

  1. Install Docker for Windows
  2. Create default machine
  3. Attempt to run docker-machine commands

**Comment by friism** [comment]
Why do you want to use docker-machine with Docker for Windows? If you want to test swarm, you can use the docker-machine hyper-v driver: https://github.com/docker/labs/tree/master/swarm-mode/beginner-tutorial#creating-the-nodes-and-swarm

**Comment by talaniz** [comment]
I'm closing this out. I hadn't touched Docker in a while and I had a different setup on Docker Toolbox on my Mac. Once I read your comment, I revisited the docs and realized I did need it. Thanks for the quick response.
