### ISSUE TITLE
Docker Desktop crashes at Windows startup

### ISSUE THREAD

**Issue by nikur** [docker/for-win#7705]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
I have created a task through Windows Task Scheduler which starts Docker Desktop automatically at system boot. I have enabled task delay by 1 min and set the task to run under SYSTEM account with elevated privileges. Docker should start at system start-up without any user interaction required. I have created the task according to the instructions given in the following StackOverflow posting: [Link](https://stackoverflow.com/a/59467740)

### Actual behavior
Since the last update of Docker Desktop, it always fails to start automatically. Starting it manually through the desktop shortcut works fine.

The internal log file shows the following stack trace:
`[21:47:59.921][GUI               ][Info   ] Starting...
[21:47:59.929][ComponentVersions ][Info   ] Edition community
[21:47:59.929][ComponentVersions ][Info   ] Edition community
[21:48:04.851][GUI               ][Error  ] System.UnauthorizedAccessException:
Access denied (Exception of HRESULT: 0x80070005 (E_ACCESSDENIED))
   at Windows.UI.Notifications.ToastNotifier.Show(ToastNotification notification)
   at Docker.WPF.AccessDeniedNotifier.CheckAccess() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.WPF\AccessDeniedNotifier.cs:Line 75.
   bei Docker.Program.Run(IReadOnlyCollection`1 args) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Program.cs:Line 188.`

### Information

  - Windows Version: Windows 10 Pro (Build 19041.388)
  - Docker Desktop Version: 2.3.0.3 (45519)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Activate Windows task to start Docker at start-up
  2. Reboot the system

**Comment by stephen-turner** [comment]
If it's working when clicking the desktop shortcut, then I would say that it's working properly. If there's a problem with some user's StackOverflow recipe, then you'll have to ask him about it, sorry.

**Comment by nikur** [comment]
It used to work until the latest update. I suppose this exception is related to Docker Desktop being started in headless mode. The error I mentioned only occurs in that situation. So I suppose that in the latest revision, some statement was added in the code which breaks when run in headless mode.
Why isn't there any "official" option to install Docker Desktop as a service and run it at start-up automatically? It is only possible to run Docker at user login but that isn't really useful when running a server. I would like to configure the server such that it launches Docker along with the containers without requiring any user interaction so that in case of a power outage or something like that, it is enough to push the "power on" button in order to get the system working again.
If there is any better solution to my problem, please let me know about it.

**Comment by stephen-turner** [comment]
Docker Desktop is intended for developers and we don't test headless scenarios. For a server, Docker Enterprise Engine is a better option, and is included in the cost of a Windows Server licence.

**Comment by nikur** [comment]
It is a development machine for which Docker Enterprise Engine isn't available. So this is not an option for me. :-(
