### ISSUE TITLE
File not changing inside docker container after updating from 2.1.0.5 to 2.2.0.0 

### ISSUE THREAD

**Issue by nick4fake** [docker/for-win#7706]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C43F34E9-E28F-4907-998C-A80ED50DE691/20200717092800

### Expected behavior
When shared folder is mounted files can be changed from both sides.

### Actual behavior
If I change a file from windows it doesn't update in docker until I go inside container and touch it.
Removing file from Windows causes docker to not be able to interact with it (touch and rm don't work).
Chaning files from docker immediately changes them in windows.

### Information

  - Windows Version: Windows 10 1909 build 18363.900
  - Docker Desktop Version: 2.3.0.3 (45519)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. Well, any docker image and any mount path

(possibly) relevant issue:
https://github.com/docker/for-win/issues/5530

**Comment by stephen-turner** [comment]
@djs55 PTAL
