### ISSUE TITLE
error when pulling microsoft/mssql-server-windows-developer

### ISSUE THREAD

**Issue by ormico** [docker/for-win#771]
### Expected behavior
pull microsoft/mssql-server-windows-developer with no error

### Actual behavior
PS> docker pull microsoft/mssql-server-windows-developer
Using default tag: latest
latest: Pulling from microsoft/mssql-server-windows-developer
3889bb8d808b: Already exists
1a106d48ef90: Already exists
ba911a964385: Pull complete
0959b0dec93b: Pull complete
93b25dc096cf: Pull complete
950c9ef6e374: Extracting [==================================================>] 1.206 kB/1.206 kB
f8d7775d5f86: Download complete
811a876df5c0: Download complete
becb800f0e5b: Download complete
a1dc86564384: Download complete
a7669bc02479: Download complete
563b63d45d98: Download complete
d07d5544a6ea: Download complete
aafe6386c661: Download complete
failed to register layer: re-exec error: exit status 1: output: time="2017-05-25T18:13:02-04:00" level=error msg="hcsshim::ImportLayer failed in Win32: The process cannot access the file because it is being used by another process. (0x20) layerId=\\\\?\\C:\\ProgramData\\Docker\\windowsfilter\\ae7e5bd3e35bd530d2bbe85415e3349f24c9b8895b5a658a406416cdcb734dc3 flavour=1 folder=C:\\WINDOWS\\TEMP\\hcs047807131"
hcsshim::ImportLayer failed in Win32: The process cannot access the file because it is being used by another process. (0x20) layerId=\\?\C:\ProgramData\Docker\windowsfilter\ae7e5bd3e35bd530d2bbe85415e3349f24c9b8895b5a658a406416cdcb734dc3 flavour=1 folder=C:\WINDOWS\TEMP\hcs047807131
[05/25/2017 18:17:30] C:\Users\zack.moore
PS>

### Information
diagnostic ID: 177EE27A-2124-4DCD-92A9-530AF8027283/2017-05-25_18-19-46

I already have some docker images pulled which did not error:
PS> docker images
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
microsoft/aspnetcore          1.1.2-nanoserver    99beb0f4370b        16 hours ago        1.2 GB
microsoft/windowsservercore   latest              4f222178c921        2 weeks ago         10.2 GB
microsoft/nanoserver          latest              6c367cf4cb98        2 weeks ago         1.02 GB

I have Symantec Endpoint Protection Cloud which I am suspicious of but I have already done the following:
1. Turn off "Auto-Protect"
2. Add exclusion for C:\\ProgramData\\Docker

This happens on my work laptop. Does not occur on my personal laptop. I am an admin.

### Steps to reproduce the behavior
on affected PC run:
pull microsoft/mssql-server-windows-developer with no error

**Comment by friism** [comment]
Are you using a recent Symantec version? Please see this issue: https://github.com/docker/for-win/issues/463#issuecomment-279021703

Since this is probably Symantec related, I recommend getting in touch with them too.

**Comment by ormico** [comment]
i'm using latest

**Comment by friism** [comment]
@ormico ok, can you try procmon to see what program is hogging the file? https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx

**Comment by ormico** [comment]
Help about states:
Symantec Endpoint Protection Cloud
Version: 22.9.3.13

**Comment by ormico** [comment]
sure. from the error should I be watching C:\ProgramData\Docker\ or C:\Windows\Temp
I wasn't sure which was the issue based on the message.

**Comment by ormico** [comment]
ps. i already downloaded windowsservercore but is there anything else I can do to speed up the test and not have to re-download each time I run? I'm having to pull like 3+GB each time.

**Comment by friism** [comment]
Try to reproduce with the nanoserver image

**Comment by ormico** [comment]
I don't get the same error with the nanoserver image, which is weird. I can drop the image and try it again just to be sure.

Interestingly, I just tried this with Process Monitor running and didn't get the error. I've been getting this error all day and got it just before. Then I started process Monitor and set it to Auto-Scroll and didn't get the error. I'll run it again to test.

**Comment by ormico** [comment]
i'm not a docker pro, but nanoserver pulls instantly and no error.
PS> docker pull microsoft/nanoserver
Using default tag: latest
latest: Pulling from microsoft/nanoserver
bce2fbc256ea: Already exists
4a8c367fd46d: Already exists
Digest: sha256:86fa413540250b8de248da0a095f13fa119e00a212a855df98947d6948892b54
Status: Downloaded newer image for microsoft/nanoserver:latest

I'll try again for the sql image

**Comment by ormico** [comment]
so far as I can tell (which I don't really trust) nothing has that folder or a file in it locked, per Process Monitor. I don't use this all the time so I may be getting something wrong.

I checked the folder in C:\ProgramData\Docker\windowsfilter\f910166e136cdb91f27177b84d55d4633e8ee84b90759c7b1e5738c96eaf8891 and in c:\windows\temp


[ProcessMonitor.zip](https://github.com/docker/for-win/files/1030516/ProcessMonitor.zip)

**Comment by ormico** [comment]
Did a little research on this today.

First, I found this on Symantec's page. No solution but it sounds pretty similar. 
https://www.symantec.com/connect/forums/sep-14-stops-docker-windows-working-0

Found this which is not about docker but describes how Symantec keeps touching files even when you turn off Real Time protection. 
https://www.symantec.com/connect/forums/how-disable-protection-completely#comment-3253231

I'll probably uninstall Symantec and verify that is the cause. It looks like just stopping the service won't work as it just restarts.

Last, I found a workaround.
I can't pull that image from the registry on this machine, but I can on another machine, save it, copy it, and load it on this computer.
```
[05/26/2017 18:36:49] C:\Users\zack.moore\downloads\docker
PS> docker load -i .\microsoft-mssql-dev.dockerimage
5b54b8a9d3b8: Loading layer [==================================================>] 54.27 kB/54.27 kB
918788af00ea: Loading layer [==================================================>] 54.27 kB/54.27 kB
8bd646e96903: Loading layer [==================================================>] 54.27 kB/54.27 kB
742e3e4b1d04: Loading layer [==================================================>] 54.27 kB/54.27 kB
779e69b74429: Loading layer [==================================================>] 54.27 kB/54.27 kB
a2f4c378d115: Loading layer [==================================================>] 54.27 kB/54.27 kB
d52ed8204bba: Loading layer [==================================================>] 61.44 kB/61.44 kB
fa976c928453: Loading layer [==================================================>] 54.27 kB/54.27 kB
465609603c33: Loading layer [==================================================>] 2.501 GB/2.501 GB
5d14572f36ce: Loading layer [==================================================>] 2.045 GB/2.045 GB
0bcb9587329b: Loading layer [==================================================>] 180.4 MB/180.4 MB
ada646efa8c0: Loading layer [==================================================>] 54.27 kB/54.27 kB
Loaded image: microsoft/mssql-server-windows-developer:latest
[05/26/2017 18:48:24] C:\Users\zack.moore\downloads\docker
PS> docker images
REPOSITORY                                 TAG                 IMAGE ID            CREATED             SIZE
microsoft/mssql-server-windows-developer   latest              e89ac77fc70e        9 days ago          14.9 GB
microsoft/windowsservercore                latest              4f222178c921        2 weeks ago         10.2 GB

```

**Comment by friism** [comment]
It's very odd that `load` works and `pull` doesn't, since the FS operations should be similar. Glad you found a workaround though, and let us know what you find out.
