### ISSUE TITLE
Fails to start "Failed to create or configure Hyper-V VM: Sequence contains no elements.."

### ISSUE THREAD

**Issue by petedmarsh** [docker/for-win#7721]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: **173C613D-8CFE-4772-95F2-A96DC0E98AED/20200718122318**

### Expected behavior

Docker starts

### Actual behavior

A pop-up appears with the message "Failed to create or configure Hyper-V VM: Sequence contains no elements.."

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

Windows 10
Docker Desktop 19.03.1

Everything was working fine but there was a Windows update last night which I suspect might be to blame.

### Steps to reproduce the behavior

Start Docker
Crashes

**Comment by petedmarsh** [comment]
Note I have tried this with 19.03.1 and edge and both have the same issue.

**Comment by VoyagerWD** [comment]
Could you solve this problem? I have the same issue

**Comment by petedmarsh** [comment]
@VoyagerWD unfortunately not. I suspect it was caused by a windows update (this was all working on my pc, I turned it off and installed updates and the next time I turned it on it wasn't working).

**Comment by loicpascal** [comment]
I have the same error : `[Error  ] Start failed with Failed to create or configure Hyper-V VM: Sequence contains no elements..`   
Although Hyper-V feature is active on my computer. I can send you logs report if you want.

**Comment by petedmarsh** [comment]
I wasn't able to fix this directly.

However, I installed WSL 2 and reinstalled Docker and configured it to use that and now I can use Docker again.

**Comment by pms-github** [comment]
I am also facing same issue , everything was working post windows update it's crashed. Not able to get up. Can not use WSL 2 since I am little older on windows patch
