### ISSUE TITLE
Docker crashes in Windows 10 Build Version 1903 -

### ISSUE THREAD

**Issue by lakshmanl** [docker/for-win#7731]
I tried to download lastest stable version of Docker Desktop, it seems to be crashing with below error. I saw couple threads closed with the same error. 

I checked and my Hyper V manager is running and I tried to stop and start it. No joy. 

This is a virtual machine running on a vcloud. Anything else I should check ?

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version: Windows 10 , Build  1903
  - Docker Desktop Version: 2.3.0.3 (45519)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: on a Vcloud 

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jgwinner** [comment]
I don't see the error number, but just wanted to say I had the same problem, if yours was "Out of memory"
