### ISSUE TITLE
Window 10 pro 2004 build docker desktop proces not starting 

### ISSUE THREAD

**Issue by arjunasuresh3** [docker/for-win#7737]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: C7CB7E2F-076B-40A5-94CC-3D09B6581DF4/20200720075013

### Information

  - Windows Version: windows 10 pro 2004 build
  - Docker Desktop Version: 2.3.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by sahanja** [comment]
x86_64/ARMv7l (AArch32)/ARMv8l (AArch64) Debian 9+, Ubuntu 16.04+, CentOS/RHEL 7+ x86_64 Snow capped Linux 3.9+.
[192.168.100.1](https://1921681001.id/) [192.168.1.1](https://19216811.cam/) [jpg to pdf](https://jpgtopdf.onl/)
