### ISSUE TITLE
Running docker/docker-compose from windows when referenced volume is in WSL2 does not appear to work

### ISSUE THREAD

**Issue by ebmeierj** [docker/for-win#7742]
- [x] I have tried with the latest version of my channel (Stable or Edge)
- [x] I have uploaded Diagnostics
- Diagnostics ID: B8C4DDEA-CDB3-4DD0-92DC-27D61A884911/20200720170133

### Expected behavior
I've been scouring docs / issues for a couple of days now and have found numerous threads which seem related but not exactly what I'm trying to do.

I currently have Ubuntu 18 and Ubuntu 20 WSL2 distros installed. I am trying to run a php application using docker for windows. The setup guides have recommended that I install the actual code in WSL2 to optimized volume speed. This is all fine however I'd _really_ like to still run my docker commands from windows. I've seen conflicting reports of this working or not working. Most of these reports cite the issue being related to docker not knowing which distro you are referring to. However I'm using a network share to reference the files which seems to be aware of which distro I'm referring to.

### Actual behavior
When creating the container from windows the volume reference appears to point to a non-existent directory and the volume is empty.

### Information
- Is it reproducible? yes
- Is the problem new? I'm new to docker desktop so I'm not sure
- Did the problem appear with an update? I'm new to docker desktop so I'm not sure
- Windows Version:
  - Edition: Windows 10 Pro
  - Version: 2004
  - OS build: 19041.329
- Docker Desktop Version:
  - Engine: 19.03.8
  - Compose: 1.25.5
- Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior
* I mapped `\\wsl$\Ubuntu-18.04` to `g:`
* wsl -d Ubuntu-18.04
* cd /home/joeebmeier
* mkdir test/
* touch test/hello
* I created a simple docker-compose file:
```
---
version: '3.7'
services:
  test_volumes:
    image: ubuntu:latest
    volumes:
    - "./test:/test"
    command:
    - bash
    - -c
    - while [ true ]; do sleep 60; done
```

##### Container Created on Windows:
1.  cd g:\home\joeebmeier
2. docker-compose up -d

After the container is created, if I inspect it I see that the bind mount is defined as `/run/desktop/mnt/host/uC/wsl$/Ubuntu-18.04/home/joeebmeier/test:/test:rw` and when I exec into the container the /test/ directory is empty 

##### Container Created on WSL2:
1. wsl -d Ubuntu-18.04
2. cd /home/joeebmeier
3. docker-compose up -d

After the container is created, if I inspect it I see that the bind mount is defined as `/run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu-18.04/1b57a4f0dee0806771c8c57f485f87489777a59af673ab426435e38e8bdbbcd6:/test:rw` and when I exec into the container the /test/ directory has the expected file

### Conclusion:
It would seem that if I want performant volumes I have to put my code in WSL however once I've done that I can no longer use windows to start containers. I understand the reasoning behind putting the code in WSL for the volume performance but this solution seems to miss the point if that means I can no longer use windows to start a docker container. I've read some other posts which would suggest that different WSL OSs create those volumes differently and windows has no way of knowing what OS you are attempting to use. As a compromise would it be possible to make starting containers work from Windows for the default WSL? This seems reasonable since if you are using windows as your primary docker medium it stands to reason that you would not be installing a custom WSL OS.

**Comment by psoares** [comment]
I have a probably related issue. Volume mounts using the linux syntax are not working after upgrading to 2.3.0.4 (46911) on Windows 10 without WSL2, neither from powershell, not from WSL. Tried after resetting docker to factory defaults and got the same problem.

Note: I shared the entire c: drive in the docker 
![docker-version](https://user-images.githubusercontent.com/192243/88691291-ac3ef600-d0ca-11ea-95fc-dee61cbaa1ac.png)
![docker-sharing](https://user-images.githubusercontent.com/192243/88691419-d395c300-d0ca-11ea-8c22-9039b76f7dbf.png)

config.

examples:
- From powershell:
```
ls /tmp # lists many files
docker run --rm -ti -v /tmp:/foo alpine ls -al /foo # => no files other than .. and .

docker run --rm -ti -v c:/tmp:/foo alpine ls -al /foo # => shows the files
```

- From WSL:
```
ls /tmp # lists many files, from the WSL filesystem
docker run --rm -ti -v /tmp:/foo alpine ls -al /foo # => no files other than .. and .
docker run --rm -ti -v /mnt/c/tmp:/foo alpine ls -al /foo # => no files other than .. and .
docker run --rm -ti -v c:/tmp:/foo alpine ls -al /foo # => lists files from the windows c:/tmp

# in an empty directory
echo hello > hello.txt
ls # => shows .., . and hello.txt
docker run --rm -ti -v `pwd`:`pwd` -w `pwd` alpine ls -al # => shows only .. and .
```

It gets worse... if I write a file inside the container on a mounted directory, it gets persisted somehow... but not visible "from the outside". e.g. from WSL terminal in an empty directory:
```
docker run --rm -ti -v `pwd`:`pwd` -w `pwd` alpine sh -c 'echo hello > hello.txt'
ls #=> no files
docker run --rm -ti -v `pwd`:`pwd` -w `pwd` alpine cat hello.txt # => displays hello
```

docker-compose volume mounts are completely broken too, obviously...

**Comment by ebmeierj** [comment]
I'm not really sure how the behavior described by @psoares is related - other than it has to do with docker volumes (which is pretty generic). I believe the behavior is just confusion surrounding how docker for windows treats "linux" style volume paths. This behavior was present in previous releases and is present using Hyper-v. You can check out https://stackoverflow.com/questions/43181654/locating-data-volumes-in-docker-desktop-windows for more information.
