### ISSUE TITLE
Docker crashes every once a while

### ISSUE THREAD

**Issue by icezone** [docker/for-win#7752]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 67836C52-3D31-4CC3-BBCD-253A08211F9E/20200721153354

### Information

  - Windows Version: Windows 10
  - Docker Desktop Version: 2.3.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by sahanja** [comment]
For both us and our customer's record we are seeing holders halted arbitrarily inside stacks, there is nothing in the logs, and no explanation behind them to be halted, however we are seeing them halting haphazardly for the duration of the day, particularly in the course of the most recent two days. This is a significant issue as it is causing personal time for both us and our customer and thinking about inadequately the docker cloud administration when there doesn't appear to be any soundness.
[snaptube](https://snaptube.cam/)  [vidmate](https://vidmate.bid/) [word to pdf](https://wordtopdf.ltd/)
