### ISSUE TITLE
Clean install of Docker Desktop on Windows 10 Home does not set win10 Envitonment variables (docker-machine)

### ISSUE THREAD

**Issue by CasaRol** [docker/for-win#7756]
- [ ] I have tried with the latest version of my channel (Stable)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 055325D1-1A9D-4220-A389-3E48DDA4581A/20200721173553

### Expected behavior

Docker-machine should be recognized by the command alone

### Actual behavior

"The term 'docker-machine' is not recognized as the name of a cmdlet"

Doens't seem to install any machine for docker to run when calling the command. the folder under "C:\Users\<USERNAME>\.docker\machine\machines is empty after clean install while the docker system looks for a file within this folder

### Information

  - Windows Version: Windows 10 Home (version 2004 (latest))
  - Docker Desktop Version: 19.03.8
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Running in Powershell

### Steps to reproduce the behavior

  1. Removed Docker toolbox
  2. Removed Docker Desktop
  3. Removed all docker_* in windows 10 Environment variables
  4. Restart
  5. Reinstall Docker Desktop

**Comment by thaJeztah** [comment]
Docker Desktop does not use VirtualBox and/or Docker Machine to create the VM in which the daemon runs (and no longer ships with Docker Machine), so for that reason you won't see it there.

If you need Docker Machine for other uses, you can still download it from GitHub; https://github.com/docker/machine/releases/tag/v0.16.2

**Comment by CasaRol** [comment]
Oh! okay. But it still ises the VM's to run, right?

**Comment by stephen-turner** [comment]
No, on Windows 10 Home it uses WSL 2, it doesn't need a full VM.
