### ISSUE TITLE
Docker WSL Nodemon filechange issue

### ISSUE THREAD

**Issue by blankstar85** [docker/for-win#7758]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: AE0D7320-4319-4E50-AF70-09E5ACCB120D/20200721184124

### Expected behavior
Nodemon should detect file changes and trigger the rebuild.

### Actual behavior
No restart is triggered due to changes.

### Information

Please, help us understand the problem.  For instance:
  - Is it reproducible? Yes
  - Is the problem new? Not Sure, I just switched to WSL to take advantage of the improvements, this was working under hyper-v
  - Did the problem appear with an update? Switched from hyper-v to wsl
  
  - Windows Version: Win 10 PRO 10.0.19041 Build 19041
  - Docker Desktop Version: 2.3.3.2(46784) Edge Version
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: This is on a home Desktop
  - WSL Image: ubuntu

### Steps to reproduce the behavior

  1. Create a simple typescript express app.
  2. Setup npm start script: "nodemon --inspect=0.0.0.0:9229 src/server/app.ts"
  3. Setup nodemon.json in root:
```json
{
  "env": {"NODE_ENV":"development"},
  "execMap": {"ts": "node --require ts-node/register"},
  "ext": "ts",
  "ignore": ["src/**/*.spec.ts", ".git", ".node_modules/**/node_modules"],
  "restartable":"rs",
  "verbose": true,
  "watch": ["src/"]
}
```
  4. create docker compose that mounts the local files into the docker container
```yaml
Specifics for the file:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    ports:
    - "8000:8000"
    - "9229:9229"
    volumes:
    - /app/node_modules
    - ./api:/app
```
5. add the DockerFile:
```
FROM node:12.16.3-alpine
WORKDIR '/app'
COPY ./package*.json ./
# Add build tools for bcrypt and remove after, caching here
RUN apk --no-cache --virtual build-dependencies add \
    python \
    make \
    g++ \
    && npm install \
    && apk del build-dependencies
COPY . .
EXPOSE 8000
CMD ["npm", "run","start"]
```
 6. On startup nodemon startup:
```
> nodemon --inspect=0.0.0.0:9229 src/server/app.ts
[nodemon] 2.0.3
[nodemon] reading config ./nodemon.json
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 18 to restart
[nodemon] ignoring: src/**/*.spec.ts .git .node_modules/**/node_modules
[nodemon] watching path(s): src/**/*
[nodemon] watching extensions: ts
[nodemon] starting `node --require ts-node/register --inspect=0.0.0.0:9229 src/server/app.ts`
[nodemon] spawning
[nodemon] child pid: 30
Debugger listening on ws://0.0.0.0:9229/3686bcf5-56d5-49a8-bde9-0cf0a7d8bb0f
For help, see: https://nodejs.org/en/docs/inspector
[nodemon] watching 224 files
2020-07-21T18:38:39.178Z debug: Env Variable: development
2020-07-21T18:38:42.194Z debug: Magic happens on port: 8000
```
7. Change a ts file in the app, nothing is triggered.

**Comment by stephen-turner** [comment]
Thanks for the report. If you store your files in the Windows filesystem but run docker in WSL 2, then unfortunately this is expected. File change notifications are not sent from Windows to WSL 2, so we can't observe them. This is out of our control, as we do not manage the file sharing between Windows and WSL 2. This is why we recommend keeping your files in the WSL 2 filesystem instead.
https://docs.docker.com/docker-for-windows/wsl/

**Comment by blankstar85** [comment]
@stephen-turner The only downside i guess to using phpstorm (mainly use the webstorm part of it), it doesn't have the remote tools like vscode. Thanks for the input and fast reponse. 
I greatly appreciate it.
