### ISSUE TITLE
Windows 10 Pro - Docker does not start

### ISSUE THREAD

**Issue by carmelr** [docker/for-win#776]
### Expected behavior
Expects Docker to start service

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
A diagnostic was uploaded with id: 31D0B42E-F52C-4AFA-B65F-710C68CC0375/2017-05-30_08-59-49

Windows 10 Pro
Processor: Intel(R) Core(TM) i7-6700K CPU @4.00GHz 4.00GHz
Installed memory: 16GB
System type: 64-bit Operating System, x64-based processor
Workgroup: WORKGROUP
Windows is activated.

### Steps to reproduce the behavior

  1. Install Docker (stable) for Windows
  2. After successful installation, Docker attempts to start
![2017-05-30_0907](https://cloud.githubusercontent.com/assets/22432155/26571754/8eceafda-4517-11e7-8f8b-d8f38b264b7e.png)
[log.txt](https://github.com/docker/for-win/files/1037487/log.txt)
[DebugInfo-2017-05-30_08-59-49.txt](https://github.com/docker/for-win/files/1037491/DebugInfo-2017-05-30_08-59-49.txt)

Thanks
Carmelo

**Comment by jasonbivins** [comment]
Hi Carmelo, thanks for posting.

Can you check to see that the MobyLinuxVM shows in Hyper-v manager, and that it can be started?  

I'm seeing this in the logs right before the timeouts:  VM MobyLinuxVM is stopped

Thanks,
Jason

**Comment by doublnt** [comment]
After Changing the setting below ,I solved my problem.
![](https://ws4.sinaimg.cn/large/006tNc79gy1fhembugy48j30ek0dq0t9.jpg)
