### ISSUE TITLE
Kubernetes context not set in WSL

### ISSUE THREAD

**Issue by binman-docker** [docker/for-win#7764]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
When I enable Kubernetes on Docker Desktop for Windows, I expect that kubectl inside WSL will be configured to be able to connect to that local cluster.

### Actual behavior
Docker Desktop writes the ~/.kube/config file in Windows, but not inside the WSL "machine". 

Assuming the user hasn't enabled the option for Windows containers, chances are they want to use WSL to interact with Docker and Kubernetes, so the configuration should be written inside WSL as well. Or at least the user should be warned to copy the config from Windows into WSL.

### Information

  - Windows Version: 1909 18363.959
  - Docker Desktop Version: Edge 2.3.3.2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Nope

### Steps to reproduce the behavior

  1. Install WSL (not sure if this applies to WSL2)
  2. Install Docker Desktop for Windows
  3. Enable Kubernetes in the settings menu
  4. Run "kubectl config get-contexts" inside a WSL shell and see that the "docker-desktop" context is not there.

(I hit this by blowing away my ~/.kube/config file for unrelated reasons. Reinstalling kubernetes and even Docker Desktop did not fix it; turns out I must have manually copied the config sometime in the past and forgot all about it.)

**Comment by binman-docker** [comment]
Related: https://github.com/docker/for-win/issues/2737#issuecomment-456886948

**Comment by stephen-turner** [comment]
Thanks, Brett. @simonferquel Do we already have an internal ticket for this?

**Comment by simonferquel** [comment]
Hi @binman-docker, unfortunately, we don't support integration with WSL 1. However you can probably workaround the issue by making your ~/.kube/config file inside wsl a symlink to the windows config file.

**Comment by stephen-turner** [comment]
Ah, sorry, I didn't read the ticket carefully enough and didn't realise it was a WSL 1 issue. You're right, WSL 1 is not recommended.

**Comment by binman-docker** [comment]
No worries, I'll upgrade to WSL2 eventually and see if it works there. Hopefully this helps folks on WSL1 if they find this ticket.
