### ISSUE TITLE
pulling not working

### ISSUE THREAD

**Issue by BhanuPrakashMuppuri** [docker/for-win#777]
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 06:14:34 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 06:14:34 2016
 OS/Arch:      linux/amd64

**pulling not working, diagnostic id is 6154FDFE-C80C-4202-A787-0E2C30F0F0F5/2017-05-30_14-05-43**

I'm trying to run 

> docker run hello-world
It's saying 
Unable to find image 'hello-world:latest' locally
Pulling repository docker.io/library/hello-world

But nothing is showing up after this.

**Comment by friism** [comment]
Can you please upgrade to a more recent Docker version?

**Comment by BhanuPrakashMuppuri** [comment]
@friism Thanks for the help, that worked. Hence closing the issue.
