### ISSUE TITLE
Docker error during connect ... connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

### ISSUE THREAD

**Issue by koksin** [docker/for-win#7780]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 255E6AB1-D9B5-417F-A765-DA811A2AE424/20200723033025

### Expected behavior
`docker build -t docker101tutorial . `  should completed succesfully.

### Actual behavior
```
D:\Workspace\docker\getting-started>docker build -t docker101tutorial .
error during connect: Post https://192.168.99.100:2376/v1.40/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=x2weg2spd3mwpjs5722b5xdlj&shmsize=0&t=docker101tutorial&target=&ulimits=null&version=1: dial tcp 192.168.99.100:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```
### Information

  - Windows Version: Windows 10 Pro Version 2004 (OS Build 19041.388)
  - Docker Desktop Version:  2.3.0.3 (45519)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No.  

### Steps to reproduce the behavior

  1.  Follow the learn tutorial from Docker desktop menu.

**Comment by sdronava** [comment]
See the same behavior as well.
