### ISSUE TITLE
Docker Desktop doesn't start after Windows 10 update to relese 2004 20170

### ISSUE THREAD

**Issue by PavelSosin-320** [docker/for-win#7781]
- [ X] I have tried with the latest version of my channel (Stable or Edge)
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID: 1695A9B2-5AAE-4023-953F-F08D7698FC5A/20200723044143

### Expected behavior
Docker Desktop starts

### Actual behavior
Crash and termination of the startup sequence

### Information

  - Windows Version: see log
  - Docker Desktop Version:  2.3.3.1
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No, Dockers uses WSL 2

### Steps to reproduce the behavior

  1. Restart Docker
  2. ...
It looks like an issue related to the instability of the recent WSL 2 update:
- Process tree tends to expose the inconsistency in some scenario
- File access via \\WSL$ tends to be broken

**Comment by PavelSosin-320** [comment]
I see in the log that Docker tries to restart WSL distro from inside the Linux VM. When I tried to do it manually I found that it is not possible: WSL creates 4 /init processes, reboot does nothing, kill signal is sent to one certain /init process? which one?  I'm not sure that MS proprietary /init processes SIGKILL correctly. Kill /init PID 1 is not propagated to other /init's brothers.
It looks like distro is containing tp run until wsl --terminate distro is issued. Then, after re-entering distro everything is dead - MS propriety /init doesn't start services. /etc/init.d is empty. Dockerd can be restarted as dockerd.exe via WSL2 interop but the log will be very different from the produced by Docker Desktop.

**Comment by licanhua** [comment]
If \\wsl$ is broken, try `dmesg |grep 9p` to see if [9p](https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#cannot-access-wsl-files-from-windows) has problem.

**Comment by PavelSosin-320** [comment]
1. After insider release upgrade to build20180, I get the same installation issue as with the previous build 
Docker installer is not able to recognize the WSL 2 feature status due to DISM "catastrophic error". But the workaround exists: if the installer will check  feature statuses specifically **dism /online /get-featureinfo /featurename=Microsoft-Windows-Subsystem-Linux**
DISM will return the correct answer -see attached picture. 
![DismWorkaroundForDockerInstaller](https://user-images.githubusercontent.com/54495912/89426769-29a9dc80-d743-11ea-92ad-362d0ab40cee.png)

Microsoft is fighting with this DISM issue already 2 years. I suppose the Docker Installer correction will be more successful.
2. Incompatible change in the build 20180 - there is no \\\wsl$ anymore! Use \\wsl\../. or Linux in the File Explorer. Use \\wsl\Centos7 in the Command prompt and PS.

**Comment by licanhua** [comment]
>  there is no \\\\wsl$ anymore! 

The official name is renamed from \\\\wsl$ to \\\\wsl, but \\\\wsl$ is still supported. If you see any problem, please create a issue on WSL

**Comment by PavelSosin-320** [comment]
@licanhua  Thanks for your advice! It will be nice to investigate this issue further but since this issue prevents Docker desktop to be installed/reinstalled its impossible to extract any logs from non-registered and not running wsl distro: p9 is not running because the distro doesn't run.
WSL2 allows import of distro from the tarball using wsl.exe and if import works it proves that lxss service is enabled.
The consistency of Windows\WinSxS folder and the correctness of Dism libraries prove nothing.
