### ISSUE TITLE
multiple crash with startup

### ISSUE THREAD

**Issue by ravi-prakashkolkata** [docker/for-win#7783]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by princewillzz** [comment]
I am having same problem with docker version-2.3.0.3(docker desktop). It starts very slow but once it starts up running everything becomes normal.
