### ISSUE TITLE
After upgrade to version 23 - unable to start docker desktop

### ISSUE THREAD

**Issue by Shazam14** [docker/for-win#7790]
- [ ] I have tried with the latest version of my channel (Stable or Edge) 
      tried latest version Stable 

  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
Diagnostics Bundle: C:\Users\GINNA2~1\AppData\Local\Temp\0D7BDEF9-FA6E-4A89-9F43-4700D5776D6E\20200723142321.zip
Diagnostics ID:     0D7BDEF9-FA6E-4A89-9F43-4700D5776D6E/20200723142321 (uploaded)

### Information

  - Windows Version: WINDOWS 10
  - Docker Desktop Version: 23
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: 
---VIRTUALISED WINDOWS

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
Sorry, Docker Desktop is not supported in a nested virtualisation environment. It might work or it might not, but it depends on the outer hypervisor which we can't control.
