### ISSUE TITLE
Docker CE 2.3.2 Installation failure

### ISSUE THREAD

**Issue by PavelSosin-320** [docker/for-win#7792]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Installation of the offered Docker release 2.3.2 finished and docker started
### Actual behavior
Installation failed
### Information

  - Windows Version: Windows 10 pro 2004 build 20175
  - Docker Desktop Version: CE 2.3.2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Download iCE 2.3.2 installer
  2. ...Run installation ...
The Windows update had its own problems related to the WSL Feature enablement and access.
WSL is not an optional feature anymore and enabled by default. No check is needed at so early stage!
WSL installation and WSL version management are moved to the wsl utility itself: wsl install, wsl import, wsl set-version,....
Any WSL2 distro is accepted automatically!
All TCP networking is routed via WSL switch as a bridge.
TCP Servers must listen host 0.0.0.0 - all interfaces or user-defined interfaces.

**Comment by PavelSosin-320** [comment]
Please, use DISM for feature check very specifically! To check WSL use:
_Dism /online /Get-FeatureInfo /FeatureName:Microsoft-Windows-Subsystem-Linux_
DISM is so fragile that any corrupted feature XML in Windows WinSxS may cause "catastrophic failure" and make whole Windows unusable.

**Comment by stephen-turner** [comment]
There's a bug in the latest Windows Insiders build that stops Docker Desktop from working. See #7808.

**Comment by metcalfc** [comment]
This WSL2 bug https://github.com/microsoft/WSL/issues/5648 does effect Docker, it is not an issue with Docker. We are hopeful for a fix soon. Right now Windows 20175 and 20180 have this issue. You can disable the WSL2 backend in your Docker settings for now. You won't find docker in your WSL2 path anymore but you can work around this temporarily with:

```
alias docker=docker.exe
```
Docker on the Windows side (powershell, cmd, etc) will behave normally.
