### ISSUE TITLE
Docker hangs when running or building anything, including hello-world

### ISSUE THREAD

**Issue by bryngl** [docker/for-win#7798]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: E6068697-1EC6-4FEC-B411-C28CF224A243/20200724020134

### Expected behavior
When I run `docker run hello-world` I expect it to download and run the container.
### Actual behavior
It hangs after printing "Unable to find image 'hello-world:latest' locally"
### Information

  - Windows Version: 2004 (Build 20175.1000)
  - Docker Desktop Version: 2.3.0.3 (45519)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Open Ubuntu 20.04 for Windows (using WSL 2)
  2. Run `docker run hello-world`
  3. It will fail to proceed after printing "Unable to find image 'hello-world:latest' locally"

**Comment by bryngl** [comment]
Downgraded Windows version to 2004 (Build 20170.1000) and it works on that version.

**Comment by stephen-turner** [comment]
Probably the same as #7808.

**Comment by metcalfc** [comment]
This WSL2 bug https://github.com/microsoft/WSL/issues/5648 does effect Docker, it is not an issue with Docker. We are hopeful for a fix soon. Right now Windows 20175 and 20180 have this issue. You can disable the WSL2 backend in your Docker settings for now. You won't find docker in your WSL2 path anymore but you can work around this temporarily with:

```
alias docker=docker.exe
```
Docker on the Windows side (powershell, cmd, etc) will behave normally.
