### ISSUE TITLE
Shared Drives not applying

### ISSUE THREAD

**Issue by MadLittleMods** [docker/for-win#78]
### Expected behavior

Entering correct credentials in the Windows Security dialog after sharing a drive will successfully share the drive with containers

### Actual behavior

When [sharing a drive](https://docs.docker.com/docker-for-windows/#/shared-drives), entering correct credentials re-opens the Windows Security dialog with no perceivable action taken.

### Information

 - Windows 10 Pro with Anniversary update
 - Hyper-V enabled
 - Admin user (verified credentials with `runas /user:MLM cmd` snippet)
 - Docker for Windows 1.12.0-stable (build: 5968) 9cd1dc2

 - Some info on mounting volumes: http://docker-saigon.github.io/post/Docker-Beta/#mounting-volumes:ebf9573d6838c40027746e9d7482622a

It looks like action might be taken and the drive is shared but it is unclear from the UI. Here is a snippet of the diagnostic log

```
[20:43:50.458][Auth           ][Info   ] Storing credentials: mlm:***
[20:43:50.468][NamedPipeClient][Info   ] Sending TryShare(C, mlm:***)...
[20:43:50.470][NamedPipeServer][Info   ] TryShare(C, mlm:***)
[20:43:50.491][Cmd            ][Info   ] Share name        C
[20:43:50.494][Cmd            ][Info   ] Path              C:\
[20:43:50.496][Cmd            ][Info   ] Remark            
[20:43:50.498][Cmd            ][Info   ] Maximum users     No limit
[20:43:50.500][Cmd            ][Info   ] Users             
[20:43:50.502][Cmd            ][Info   ] Caching           Caching disabled
[20:43:50.504][Cmd            ][Info   ] Permission        some-pc\MLM, FULL
[20:43:50.506][Cmd            ][Info   ] 
[20:43:50.508][Cmd            ][Info   ] The command completed successfully.
[20:43:50.511][Cmd            ][Info   ] 
[20:43:50.513][SambaShare     ][Info   ] "C" is shared
[20:43:50.515][SambaShare     ][Info   ] Challenging credentials with host
```

### Steps to reproduce the behavior

  1. Open the Docker for Windows Settings
  2. Go to the "Shared Drives" tab
  3. Check the "C" drive and Press "Apply"
  5. Enter the credentials for your admin account in the Windows Security dialog and press "OK"
![](http://i.imgur.com/UB7l8o6.png)
  6. Note the Windows Security dialog popping up again. Entering in credentials again just pops it again.
  7. If you just exit the Windows Security dialog, the "C" drive isn't checked
![](http://i.imgur.com/I9cJhMc.png)

---

It looks like the Hyper-V driver machines can't mount volumes so I was looking into this option, https://github.com/docker/docker/issues/22981#issuecomment-221637488

 - Just noticed https://forums.docker.com/t/volume-mounts-in-windows-does-not-work/10693
 - https://github.com/docker/for-win/issues/77#issuecomment-246893368

**Comment by dgageot** [comment]
Hi @MadLittleMods, thanks for the detailed report! Could you give a try to the Beta channel instead of the Stable channel? It contains multiple fixes to the file sharing.

**Comment by MadLittleMods** [comment]
@dgageot Same issue with Docker 1.12.1-beta25 (build:6833) 158f2ee

**Comment by friism** [comment]
@MadLittleMods could you please upload a diagnostic dump (it's in the Docker tray icon menu) so we can get more info about your system?

**Comment by MadLittleMods** [comment]
Sorry @friism, I moved on to Docker Toolbox and VirtualBox driver. I would need to reinstall Docker for Windows and do the Hyper-V dance again.

**Comment by dgageot** [comment]
@MadLittleMods I'm afraid I will have to close this issue as "Could not reproduce" then. Next version of Docker for Windows will have an improved file sharing that should solve similar issues. Feel free to reopen this ticket if you come back to using Docker for Windows!

**Comment by markusschaber** [comment]
I also have a domain account, same symptoms (Windows 10). So maybe the problem is domain account vs local account?
