### ISSUE TITLE
unable to start docker on win 10 pro

### ISSUE THREAD

**Issue by hellorajen** [docker/for-win#781]
A diagnostic was uploaded with id: 38303015-59E9-4369-AB7C-B9D8FD0F3B35/2017-05-31_10-27-09
[log.txt](https://github.com/docker/for-win/files/1041853/log.txt)

**Comment by jasonbivins** [comment]
Hi @hellorajen 

Can you provide a bit more information about the environment or machine you're using?  
I see the below error in the logs -  Is MobyLinuxVM visible in the  Hyper-V Manager

'MobyLinuxVM' failed to start. (Virtual machine ID FC2AC888-6ED3-458C-8685-F63A4433947E)
Not enough memory in the system to start the virtual machine MobyLinuxVM with ram size 2048 megabytes.
