### ISSUE TITLE
Problem updating WSL with wsl_update_x64.msi

### ISSUE THREAD

**Issue by cristianopcortez** [docker/for-win#7812]
After update my Windows Home to build 19041 and install the Docker Desktop, on running the WSL with wsl_update_x64.msi (downloaded at https://docs.microsoft.com/pt-br/windows/wsl/wsl2-kernel) I receive the message: 

This update only applies to machines with the Windows Subsystem for Linux

![image](https://user-images.githubusercontent.com/8460181/88418070-61b33600-cdb9-11ea-86b2-b11d0ef77603.png)

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 56639BBF-5F0E-40BD-BF3E-DFE6B2C31EE9/20200724164057

### Expected behavior
Docker desktop installed

### Actual behavior
Ask to update WSL 2

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by chiptus** [comment]
you need build 2004

**Comment by stephen-turner** [comment]
Build 19041 is 2004. But it doesn't look like this issue has anything to do with Docker Desktop. It seems to be a Windows issue.

**Comment by cristianopcortez** [comment]
I think maybe because Windows is Home edition... Maybe doesn't work in that version anyway...

**Comment by stephen-turner** [comment]
WSL 2 and Docker Desktop do work on Windows 10 Home 2004.

**Comment by licanhua** [comment]
Can you do `dir %SystemRoot%\system32\lxss\tools\`? If it doesn't exist, then you didn't enable Windows Subsystem for Linux. So please follow this:
https://github.com/microsoft/WSL/wiki/Ship-WSL-2-Linux-Kernel#pre-check-step

**Comment by cristianopcortez** [comment]
> Can you do `dir %SystemRoot%\system32\lxss\tools\`? If it doesn't exist, then you didn't enable Windows Subsystem for Linux. So please follow this:
> https://github.com/microsoft/WSL/wiki/Ship-WSL-2-Linux-Kernel#pre-check-step

Hi licanhua !

After enabling and following the pre-check-step, restarting, running the update using PowerShell with administrative mode it have worked ! I have follow the answer at https://github.com/microsoft/WSL/issues/5035#issuecomment-649770848

Thanks for all the help !

Cristiano
