### ISSUE TITLE
the edge version of docker for desktop is not working properly

### ISSUE THREAD

**Issue by saimanojsuper** [docker/for-win#7816]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
No information in the ticket, closing.
