### ISSUE TITLE
docker start mongodb /tmp/mongodb-27017.sock Operation not permitted

### ISSUE THREAD

**Issue by FsouzaMarcell** [docker/for-win#7820]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by narwy** [comment]
This isn't a issue with the windows client this is down to your container and the startup of mongodb. Please seek support from mongodb.
