### ISSUE TITLE
Path error (Windows, same as #6797). Unable to test 'solution' since Edge version crashes.

### ISSUE THREAD

**Issue by JoanEliot** [docker/for-win#7825]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
ROR: for xxxx_db_1  Cannot create container for service db: status code not OK but 500:     ˙˙˙˙          System        ClassNameMessageDataInnerExceptionHelpURLStackTraceStringRemoteStackTraceStringRemoteStackIndexExceptionMeWatsonBuckets   ParamName  System.Collections.IDictionarySystem.Excepti   System.ArgumentException    The path is not of a legal form.
### Expected behavior
Run containers. Not to crash.

### Actual behavior
On the stable version I repeatedly had the "The path is not of a legal form." error covered in #6797 both with compose and in Docker Desktop, when trying to add/change file sharing folders. After switching from stable to edge 2.3.3.2 per the implied recommendation in 6707 I get the same error in compose, though the message is formatted differently. (And now it beeps!) Plus now Docker Desktop crashes when I edit folders in file sharing. A screenshot would show an empty white window. 

This is just for your info. Have sunk too much time into this already, so am departing Docker. 

### Information

  - Windows Version: 10 Pro 1909
  - Docker Desktop Version: 2.3.3.2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
Thanks. If it still occurs in compose after our fix, it might be a different bug, but it would best be filed in docker/compose repo. It would need a repro case too.
