### ISSUE TITLE
D4W does not start on Win 10

### ISSUE THREAD

**Issue by monubamb** [docker/for-win#783]
### Expected behavior
I installed latest DFW stable version and expect it to start normally. 

### Actual behavior
DFW does not start. I get tons of errors. This is the latest one. I think it has to do with docker not being able to run on named pipe. When I change it to TCP from UI it does work
error during connect: Get http://127.0.0.1:2375/v1.27/containers/json: dial tcp 127.0.0.1:2375: connectex: No connection could be made because the target machine actively refused it.

   at Docker.Backend.DockerDaemonChecker.Check(Func`1 isDae
[log1.txt](https://github.com/docker/for-win/files/1043737/log1.txt)
monProcessStillRunning)
   at Docker.Backend.ContainerEngine.Windows.SwitchProxy(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by friism** [comment]
@monubamb can you please run diagnostics and post the id like the instructions tell you to do?

Also please check whether the `DOCKER_HOST` environment variable is set. If it is, unset it.

**Comment by monubamb** [comment]
Thanks, I have run the diagnostics and uploaded it.. here is the ID - A diagnostic was uploaded with id: 03B85C15-C9F6-4C55-A1EE-4523DE753E84/2017-06-01_08-09-54

Also where can I find DOCKER_HOST variable on my machine..?

**Comment by jasonbivins** [comment]
@monubamb 

You can find the environment variable by running this in powershell  replace the <> with your host name.
docker-machine env --shell powershell <Host name>

This doc will show you how to unset it:
https://docs.docker.com/machine/get-started/#unset-environment-variables-in-the-current-shell

**Comment by friism** [comment]
@monubamb in PowerShell, you can see your environment variables with this command: `Get-ChildItem Env:`. The commands mentioned by @jasonbivins are related to docker-machine. The important thing to find out is whether you have left-over environment variables from previously using docker-machine.

**Comment by monubamb** [comment]
Yes, I do see it ..
DOCKER_HOST :2375...

What's the command to unset it in windows easily?

**Comment by friism** [comment]
https://technet.microsoft.com/en-us/library/ff730964.aspx#ECE

**Comment by monubamb** [comment]
No luck.. Used [Environment]::SetEnvironmentVariable("DOCKER_HOST",$null,"Process") to unset it..
it removed the system variable..
Ran Docker client again same error.. 

Doing 
[Environment]::SetEnvironmentVariable("DOCKER_HOST",$null,"Machine ") had no effect..

Attached diagnostic ID - 03B85C15-C9F6-4C55-A1EE-4523DE753E84/2017-06-01_10-42-11

Am I better off trying the 17.05-ce build?

**Comment by friism** [comment]
How are you interacting with Docker? Are you using the Docker CLI (eg. `docker ps`)?

**Comment by monubamb** [comment]
I am just trying to start Docker for Windows Client and it errors out after trying to start.

**Comment by monubamb** [comment]
Installed the latest D4W - 17.05-ce build with same issues :(

03B85C15-C9F6-4C55-A1EE-4523DE753E84/2017-06-01_11-05-20

This is really bogging me down right now...

**Comment by monubamb** [comment]
Another diagnostic log - 03B85C15-C9F6-4C55-A1EE-4523DE753E84/2017-06-01_11-22-50

FYI
When I CHECK THE EXPOSE DAEMON on TCP://localhost:2375 WITHOUT TLS it works..

**Comment by jasonbivins** [comment]
Have you made any changes to the .json config file?  Either directly or through here?

![image](https://cloud.githubusercontent.com/assets/28021664/26696625/3269e332-46dd-11e7-8a39-5221877611ba.png)

**Comment by monubamb** [comment]
Thanks Jason for your help. Issue is resolved. I restarted the machine after unsetting DOCKER_HOST.
Appreciate your help!

**Comment by jasonbivins** [comment]
Hi @monubamb   I'm glad it's taken care of!

Please let me know if you run into any more problems, or if you have any questions.  Do you mind if I go ahead and close this issue?

Thanks!
Jason
