### ISSUE TITLE
docker-for-desktop on Windows WSL2 is crashing

### ISSUE THREAD

**Issue by mdekoster** [docker/for-win#7835]
[x ] I have tried with the latest version of my channel (Stable or Edge)
  [x ] I have uploaded Diagnostics
  - Diagnostics ID: 
                Stable version: A4F0C4D9-1FC7-422B-B4F8-782DE8295A4D/20200727051318
                Edge version:   A4F0C4D9-1FC7-422B-B4F8-782DE8295A4D/20200727061310

### Expected behavior
A running docker engine in WSL2

### Actual behavior
The docker-for-desktop crashes on startup.

### Information
  - Windows Version: 
     Edition: Windows 10 Pro Insider Preview
     Version: 2004
     Installed on: 25-‎7-‎2020
     OS Build: 20175.1000
  - Docker Desktop Version:
     Version: 2.3.0.3 (45519) Channel: stable
     Version: 2.3.3.2 (46784) Channe: Edge
     
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
     No

**Comment by stephen-turner** [comment]
@mdekoster Can you try with another version of Windows? There's a bug in the latest Insiders build that stops Docker Desktop from working. See #7808.

**Comment by metcalfc** [comment]
This WSL2 bug https://github.com/microsoft/WSL/issues/5648 does effect Docker, it is not an issue with Docker. We are hopeful for a fix soon. Right now Windows 20175 and 20180 have this issue. You can disable the WSL2 backend in your Docker settings for now. You won't find docker in your WSL2 path anymore but you can work around this temporarily with:

```
alias docker=docker.exe
```
Docker on the Windows side (powershell, cmd, etc) will behave normally.
