### ISSUE TITLE
Cannot pull images on Windows 10

### ISSUE THREAD

**Issue by dde2801** [docker/for-win#784]
### Expected behavior
Image pulled

### Actual behavior
pull fails after downloading with the following error:
failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage C:\ProgramData\Docker\windowsfilter\96e8a425274f1398e15a3c6924b30cbc2147cc187e2082a6d419ad0806ea1493\UtilityVM: The media is write protected.

Whatever image it is, the pull fails the same way.

### Information
  - Diagnostic ID: 2785AC75-1CFF-45E5-B414-8C7B451FCF51/2017-06-01_14-58-22
  - a reproducible case if this is a bug, Dockerfiles FTW
error occurs simply using this command: docker pull microsoft/nanoserver

  - host distribution and version (Windows version, build number, etc)
Edition: Windows 10 Pro 
Version: 1703
OS Build: 15063.296

### Steps to reproduce the behavior

 1. docker pull microsoft/nanoserver
=>
Using default tag: latest
latest: Pulling from microsoft/nanoserver
bce2fbc256ea: Extracting [==================================================>] 252.7 MB/252.7 MB
4a8c367fd46d: Download complete
failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage C:\ProgramData\Docker\windowsfilter\96e8a425274f1398e15a3c6924b30cbc2147cc187e2082a6d419ad0806ea1493\UtilityVM: The media is write protected.

**Comment by friism** [comment]
>  The media is write protected.

Is this some special type of disk or filesystem?

**Comment by jasonbivins** [comment]
Hi, are you running Powershell as an admin?

Are you able to view or modify files here: C:\ProgramData\Docker\windowsfilter

**Comment by dde2801** [comment]
Yes I am able to modify the files.
I found the issue. My PC has bitlocker and bitlocker apparently prevents to overwrite docker files.
I had to change a key in the registry as explained here: https://github.com/Microsoft/Virtualization-Documentation/issues/530 and here Microsoft/Virtualization-Documentation#355.

Thanks for your help.
