### ISSUE TITLE
Cannot reduce disk image max size

### ISSUE THREAD

**Issue by alandsidel** [docker/for-win#7840]
https://github.com/docker/for-win/issues/4809

Still an issue.  Bot auto-closed it.

**Comment by stephen-turner** [comment]
@alandsidel Which version of Docker Desktop are you using? Does it increase successfully but not decrease, or can you do neither? We believed we'd fixed this in #5881, but maybe we missed something.

**Comment by stephen-turner** [comment]
I just tested this in the latest stable release (2.3.0.3), and I couldn't reproduce the problem.
