### ISSUE TITLE
Docker Desktop wont fully close on "Quit" and leaves "vmmem" process running?

### ISSUE THREAD

**Issue by Andy2244** [docker/for-win#7846]
- [x] I have tried with the latest version of channel Edge
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
If i select `Quit Docker Desktop` and i only the default Docker-Desktop/Data pseudo distos installed/running, i expect that not only Docker Desktop closes, but all related WSL2 instances and resources/memory as well.

### Actual behavior
Leaves the WSL2 "vmmem" process running, with all its memory, needing to manually shutdown wsl2 via command-line (`wsl --shutdown`).

### Information
  - Windows Version: 20175
  - Docker Desktop Version: 2.3.3.2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior
  1. install Docker-Desktop and use WSL2 mode
  2. "Quit Docker Desktop" via tray
  3. check taskmanager for "vmmem" process and memory consumption

**Comment by Tacfarinas** [comment]
The process gets closed for me a minute  after.
