### ISSUE TITLE
cli commands pull/build getting stuck on auth with WSL2/docker-desktop

### ISSUE THREAD

**Issue by patricknazar** [docker/for-win#7851]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: CD7A79EC-80D6-4C8F-83B0-969B51F3B378/20200728071905

### Expected behavior

Doesn't get stuck.

### Actual behavior

Get's stuck.

### Information

  - Windows Version: Windows 10 2004 20175.1000
  - Docker Desktop Version: 2.3.3.2 (46784) / Edge
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No? WSL2 with docker-desktop integration

### Steps to reproduce the behavior
I can't reproduce but I can describe:

- `docker -D pull` or `docker -D build` hangs. Shows nothing that hints at the problem, just gets stuck.
- `docker-compose --verbose build x` gets stuck on `docker.auth.resolve_authconfig: Using credentials store "desktop.exe"
docker.auth._resolve_authconfig_credstore: Looking for auth entry for 'https://index.docker.io/v1/'`

I thought I found a solution, I mentioned at [docker-compose build hangs](https://github.com/docker/compose/issues/4396#issuecomment-664285144) and mentioned at [Unable to pull images with WSL2 engine
](https://github.com/docker/for-win/issues/6837#issuecomment-664810718) but not it was too good to be true. sgtoj on the second issue [had a hanging problem](https://github.com/docker/for-win/issues/6837#issuecomment-662975520) I've tried signing in/out on docker-desktop, reinstalling, resetting to factory settings etc, nothing is working.

- `docker-compose --verbose pull x` where x is a service that has a `image: xx` property, Gets stuck in an infinite loop:

```
docker.auth.get_config_header: Looking for auth config
docker.auth.resolve_authconfig: Using credentials store "desktop.exe"
docker.auth._resolve_authconfig_credstore: Looking for auth entry for 'https://index.docker.io/v1/'
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
...
```

**Comment by stephen-turner** [comment]
There's a bug in the latest Windows Insiders build that stops Docker Desktop from working. See #7808.

**Comment by metcalfc** [comment]
This WSL2 bug https://github.com/microsoft/WSL/issues/5648 does effect Docker, it is not an issue with Docker. We are hopeful for a fix soon. Right now Windows 20175 and 20180 have this issue. You can disable the WSL2 backend in your Docker settings for now. You won't find docker in your WSL2 path anymore but you can work around this temporarily with:

```
alias docker=docker.exe
```
Docker on the Windows side (powershell, cmd, etc) will behave normally.

**Comment by patricknazar** [comment]
I've just been deleting `~/.docker/config.json`

**Comment by ducminhquan** [comment]
> I've just been deleting `~/.docker/config.json`

Removing `~/.docker/config.json` seems to solve the issue, but it is re-created after restarting Docker or rebooting Windows.

**Comment by patricknazar** [comment]
> Removing `~/.docker/config.json` seems to solve the issue, but it is re-created after restarting Docker or rebooting Windows.

Yeah, so I put the rm command in .bashrc, a hack, but it's working out for now
