### ISSUE TITLE
Docker is not running (stuck in "starting")

### ISSUE THREAD

**Issue by annakampvr** [docker/for-win#7855]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by victor-pogor** [comment]
Same problem. Diagnosis ID: `AFBBE1A8-D74E-4007-B40B-D2C6C7351730/20200728153241`

I clicked `Reset to factory defaults` and the problem disappeared.
