### ISSUE TITLE
Error response from daemon: hns failed with error : Access is denied.

### ISSUE THREAD

**Issue by masoudshiri** [docker/for-win#7856]
I got " Error response from daemon: hns failed with error : Access is denied. " when i want to create a network by this cmd: 

docker network create --driver=transparent   --gateway=175.15.10.124  --subnet=175.15.10.0/24 mynetwork

docker 19.0.3
windows server 2016

**Comment by stephen-turner** [comment]
This doesn't look like a bug in Docker Desktop, but in the upstream engine. Could you please file the bug in the moby/moby project instead? (Sorry, I would move the bug if I could, but it's not possible because the engine is not part of the docker org).
