### ISSUE TITLE
Windows engine 17.06.0-rc1-ce-win13 has corrupted container console output using linux client

### ISSUE THREAD

**Issue by wjrogers** [docker/for-win#786]
### Expected behavior

I am using Docker for Windows Community Edition with the linux client running in Ubuntu on Windows (aka the Windows Subsystem for Linux). In the previous release of Docker for Windows (17.0.5c-win11), I got this output:
```
$ docker run -p 11300:11300 -ti bevand10/alpine-beanstalk
PID   USER     TIME   COMMAND
    1 root       0:00 {run.sh} /bin/sh /run.sh -V
    8 root       0:00 /opt/beanstalk/beanstalkd -V
    9 root       0:00 ps 8
[INFO] Waiting for SIGTERM
```

### Actual behavior

In the new release of Docker for Windows (17.06.0-rc1-ce-win13), I get this output:
```
$ docker run -p 11300:11300 -ti bevand10/alpine-beanstalk
PID   USER     TIME   COMMAND
                                 1 root       0:00 {run.sh} /bin/sh /run.sh
                                                                               8 root       0:00 /opt/beanstalk/beanstalkd
      9 root       0:00 ps 8
                            [INFO] Waiting for SIGTERM
```

### Information

  - Diagnostic ID DF161252-7B4A-402A-B28E-723975E21ADA/2017-06-01_15-36-07
  - Version 17.06.0-rc1-ce-win13 (12433)
  - Linux client version `17.03.1~ce-0~ubuntu-xenial`

**Comment by jasonbivins** [comment]
Hi @wjrogers   I'll submit this as a bug/enhancement request and will link this issue to it.

**Comment by sgammill** [comment]
I get this exact same console output problem when I'm using the Windows Docker executables in C:\Program Files\Docker\Docker\resources\bin\ to attach to a container terminal running in the moby vm.  This only started happening in 17.06.0-rc1-ce-win13 (12433).  It did not happen in 17.05 or previous.

This release is pretty unusable.  We need Stable, Edge, and Test branches for Docker for Windows.

**Comment by langxiong** [comment]
I got the same problem. 

```bash
I have no name!@74e2be398149:/usr/src/myapp$
                                             I have no name!@74e2be398149:/usr/src/myapp$
                                                                                          I have no name!@74e2be398149:/usr/src/myapp$
               I have no name!@74e2be398149:/usr/src/myapp$
```

**Comment by hustlahusky** [comment]
I have the same issue after today update up to 17.06.0-ce-rc1, build 7f8486a

```
PS W:\zk\net> docker-compose exec nginx bash
root@27cc3c218c56:/# ls
                        bin   dev  home  lib64  mnt  proc  run   srv  tmp  var
                                                                              boot  etc  lib     medi
a       opt  root  sbin  sys  usr
                                 root@27cc3c218c56:/#
```

**Comment by wjrogers** [comment]
Thanks, @jasonbivins. This seems like a bug to me, not an enhancement? It's a regression vs previous releases, and it affects the Windows console client, too (thanks, other commenters; hadn't even tried that because I assumed it was a platform line ending mismatch problem).

**Comment by jasonbivins** [comment]
Hi @wjrogers    This has been submitted as a bug and Dev is actively working on it now -  I don't have a timeline for the fix yet though.

Thanks!
Jason

**Comment by stealthybox** [comment]
workaround for the moment is to `reset` the terminal.

**Comment by sgammill** [comment]
@jasonbivins 
Can you the location of a 17.05 installer?  I need to get back to where I was before I got updated.  Thanks.

**Comment by jasonbivins** [comment]
Hi @sgammill   Do you still have a copy in your Downloads folder?  The official consensus here is to use  the stable channel build temporarily until this has been resolved with an updated edge build.  If for some reason you can't use 17.03 please let me know and I'll request a 17.05 link to be created for you.

**Comment by sgammill** [comment]
@jasonbivins I don't have the old installer anymore.  If you could make a 17.05 installer available for me, I would really appreciate it.

**Comment by jasonbivins** [comment]
https://download.docker.com/win/edge/12053/InstallDocker.msi

Please let me know if you have any problems with it.

**Comment by g0t4** [comment]
This messes up scrolling too, if I have a lot of console output, the output cuts off past the height of my screen.

**Comment by sgammill** [comment]
@jasonbivins got it, works great. thank you!

**Comment by pmsousa** [comment]
I have the exact same issue; it started with **17.06.0-ce-rc1** but upgrading today for **17.06.0-ce-rc2** and the problem persists.

I'm in the middle of preparing several containers for a large deployment and this makes it impossible to test command execution interactively!!!

PS: Thanks @stealthybox for the `reset` tip!

**Comment by friism** [comment]
@pmsousa are you using compose?

**Comment by mogzol** [comment]
I can also confirm that this is still a problem in 17.06.0-ce-rc2.

It seems to be an issue with the interactive psuedo-TTY. If I run `docker-compose exec` with the `-T` argument to disable the psuedo-TTY then the output looks normal. The output also looks normal when using just the plain `docker exec` command, unless I specifically use an interactive psuedo-TTY with the `-ti` argument (just using `-t` looks fine).

**Comment by friism** [comment]
Thanks - this will be addressed further in RC3

**Comment by pmsousa** [comment]
@friism I'm using both `compose `and `docker -it`. `docker -it` to run the container interactively and execute commands like "apt-get install" or services configurations, then transpose those instructions to Dockerfiles of several containers that are part of a service launched by `compose`.

**Comment by rquintino** [comment]
same here, thanks @pmsousa for the link! using reset for now, much better
nasty little issue
Docker version 17.06.0-ce-rc1, build 7f8486a

**Comment by langxiong** [comment]
same here, using `reset` for now

```shell
Version 17.06.0-rc2-ce-win14 (12510)
Channel: edge
e406757
```

**Comment by pmsousa** [comment]
Problem solved.
Server Version: **17.06.0-ce-rc4**
