### ISSUE TITLE
MY MFC application not working in docker windows container

### ISSUE THREAD

**Issue by Manish428** [docker/for-win#7862]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version: Windows 10.0.18363.836
  - Docker Desktop Version:19.03.5, build 633a0ea
  - Visual studio used: 2017
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No its my laptop

### Steps to reproduce the behavior

Dockerfile:
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-20200714-windowsservercore-1909
USER containerAdministrator

ADD HelloDocker.exe /
ADD AccessDatabaseEngine_X64.exe /
ADD vcredist_x64_VS2017.exe /
ADD jdk1.8.0_144 /jdk1.8.0_144
ADD scs_install.properties /
ADD SCSSetup_Cloud.exe /
ADD SCS-20201.lic /
ADD jdk1.8.0_144/jre/bin/server/jvm.dll /windows/system32
ADD rtools_setup_x64.exe /
ADD LogMonitor.exe "C:\LogMonitor\"
ADD LogMonitorConfig.json "C:\LogMonitor\"

RUN  cmd  $env:path += "C:\jdk1.8.0_144\jre\bin\server;"
RUN  cmd  $env:path += "C:\jdk1.8.0_144\jdk\bin;"
ENV JAVA_HOME C:\\jdk1.8.0_144

RUN cmd ["c:\\SCSSetup.exe","-f","c:\\scs_install.properties"]
EXPOSE 8181

=========================
Our product is MFC application, so I am trying docker windows container.

SCSSetup.exe is our product installer, which I am trying to install in docker container.
During installation, it will copy an exe which is a MFC based application which starts a jetty server with port 8181.

Installation was successful, all dll files got copied and it has all dependent mfc libraries.
After installation, it has to create registry entries, which also gets entered correctly, which I verified.

But still when I start  my exe to start jetty server, it doesn't do any thing.. 
Not getting any idea what is missing which it needs.
Tried with logmonitor
Got only line:
[LOGMONITOR] INFO: Entrypoint processs exit code: -1073741515

I am not able to figure out what I am missing and whether it will work in windows container or not.

**Comment by erikrenberg** [comment]
The error code you get -1073741515 means STATUS_DLL_NOT_FOUND error (Exit code 0xC0000135). I.e most likely a DLL that your app requires isn't available in the container.

We had a similar issue, and after some trial and error we solved our issue as follows:

1. Attached to the running docker container interactively. 
2. Ran Dependencies (https://github.com/lucasg/Dependencies) there on our app to list all dependencies.  It will list missing DLLs. In our case many DLLs were listed as missing so we couldn't be sure if all really were needed, so:
3. Ran Dependencies on the app when run on the host computer.
4. Did a text diff of the two dependency lists.

=> We narrowed down to just a few DLLs. (In our case it was opengl32.dll and glu32.dll in the windows/system32 folder that were not available in the container)

Our solution/workaround then was to copy these DLLs into the container, and then our app started.
