### ISSUE TITLE
Docker build hangs after update to 2.3.0.4 (Windows, WSL2)

### ISSUE THREAD

**Issue by DutchKevv** [docker/for-win#7863]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker build works normally
### Actual behavior
It just hangs, also tried with docker-compose build. Same result.
Running containers works just fine.

**UPDATE**
it seems suddenly docker needs sudo ONLY for building, running works just fine without.

Let me know if you need any details. 

Thanks

**Comment by stephen-turner** [comment]
Are you on the latest Windows Insiders build? If so, this is a Windows bug, see #7808.

**Comment by DutchKevv** [comment]
@stephen-turner indeed on insider channel. I found the fix on your link. Thanks!

This can be closed I guess :)
