### ISSUE TITLE
Installation for 2.3.0.4 stuck on create docker-users group

### ISSUE THREAD

**Issue by fractos** [docker/for-win#7865]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Upgrade to 2.3.0.4 succeeds

### Actual behavior
Sitting there spinning with the following log:

![image](https://user-images.githubusercontent.com/657772/88680140-10bc7e00-d0e8-11ea-8355-5013d5f0f9a7.png)

### Information

  - Windows Version: 10 Pro
  - Docker Desktop Version: 2.3.0.4
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Prompted to install 2.3.0.4
  2. clicked Install
  3. allowed action when administrator permission was requested

**Comment by stephen-turner** [comment]
Which build of Windows? If it's the latest Windows Insider, 20175, it is a known bug in Windows.

**Comment by fractos** [comment]
Tracked down and killed Docker Desktop tasks. Re-ran Docker Installation (since Docker app had been removed). It crashes on startup as it gets a null reference when dealing with settings. Diagnostics report (hopefully) uploaded but no visual feedback on that received. Quit. Re-ran Docker Installation. Crashed again. Reset to factory defaults. Previous version of Docker was then started. Received prompt to update to 2.3.0.4. That crashes in the same way as original issue, above.

**Comment by fractos** [comment]
@stephen-turner Straight Windows 10 Pro, normal release channel. OS Build 19041.388

**Comment by fractos** [comment]
(The previous version I had an installation for was 2.1.0.5, by the way)

**Comment by naxvog** [comment]
Ran into the same issue on the same Win 10 Pro 19041.388 build. Forcefully closed the installation and tried to reinstall 2.3.0.3 (45519) which also hung at the same `Deploying component: Create docker-users group` step.

**Comment by fractos** [comment]
@naxvog interesting, i'll try that later today

**Comment by fractos** [comment]
@naxvog Yes, a restart has allowed the upgrade installation to work correctly.

**Comment by hsimah** [comment]
> Which build of Windows? If it's the latest Windows Insider, 20175, it is a known bug in Windows.

do you have any further info on this? Currently tools are completely down because we can't get docker installed on our insider builds.

**Comment by stephen-turner** [comment]
For the problems on Windows Insider builds, see microsoft/WSL#5648. Microsoft say on that ticket that a fix is incoming, but you'll have to ask them about timescale not us.

**Comment by hsimah** [comment]
> For the problems on Windows Insider builds, see [microsoft/WSL#5648](https://github.com/microsoft/WSL/issues/5648). Microsoft say on that ticket that a fix is incoming, but you'll have to ask them about timescale not us.

Thanks, plenty of work arounds on that thread.
