### ISSUE TITLE
Postgres Anonymizer won't start in Docker Desktop

### ISSUE THREAD

**Issue by patrickchan88** [docker/for-win#7869]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: AFFC5127-5BED-429A-8180-7A50624EE777/20200728192540

### Expected behavior
postgres db with Anonymizer should be running and able to connect via SQL client

### Actual behavior
cannot connect using SQL client (pgAdmin)

### Information

  - Windows Version: Windows 10 Enterprise
  - Docker Desktop Version: 2.2.0.5(43884)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
Do other containers work?

**Comment by patrickchan88** [comment]
Yes. Plain old Postgres works fine for me.

**Comment by patrickchan88** [comment]
I tried running Postgres only (no issue). Postgres + Anonymizer or just
Anonymizer by itself will not start successfully.

**Comment by stephen-turner** [comment]
In that case it doesn't sound like a Docker bug but something in the way the container is built or configured.
