### ISSUE TITLE
Issues running IIS website through docker with volumes mapped to host

### ISSUE THREAD

**Issue by gregpakes** [docker/for-win#787]
### Setup

I am using the microsoft/iis base image and am running a website through IIS.  The source of the website is on the host machine (it is a development environment, so this makes sense) enabled through the VOLUME command in a docker-compose file.

The issue is that I intermittently get 500 errors when requesting images (not pages) the first time.  Subsequent loads are fine.  The error is:

>  Exception information:
>  Exception type: ConfigurationErrorsException
>  Exception message: An error occurred loading a configuration file: Failed to start monitoring changes to 'c:\src\Website\system\images\16\web.config'.

There is no web.config in that directory.

This issue does not occur in a normal environment.  We have this installed on 100's of sites and development environments and have never had this issue.  But it happens on 100% of the docker environments.

The docker-compose file maps the container folder c:\src to a host directory with the source files in.

**Comment by jasonbivins** [comment]
Hi @gregpakes can you please provide more information?

-  Diagnostic ID from "Diagnose & Feedback" in the menu.
- host distribution and version (Windows version, build number, etc)
- would it be possible to get a copy of your docker-compose file you're using?


Thanks!

**Comment by gregpakes** [comment]
@jasonbivins 

Diagnostic ID: 
Windows 10 Creators (1703 15053.296)
I'm not sure how much use the compose file would be.  It references private registries etc.

I can email it potentially.

**Comment by richardgavel** [comment]
I wonder if the mechanism that monitors web.config within IIS for changes has trouble getting thru the symbolic link that represents the attached volume. Out of curiousity, how come the web site files are on a separate volume? Standard practice in a container would have the web site files within the container.

**Comment by gregpakes** [comment]
@richardgavel We do this because it is our development environment.  The code is over 2GB, so its not practical to do it any other way as far as I know.

**Comment by jasonbivins** [comment]
hi @gregpakes 
You mentioned that the error is looking for a web.config file -  Do you get this error from the same directory every time?  Do you only see this on new image pulls? 

You mentioned that this is running through an IIS server - it sounds like the web.config file is missing from c:\src\Website\system\images\16\    but that it's getting created after IIS calls for it and doesn't see it. Could you remove the web.config file from one of the directories that works, and see if you get an error when you pull from it again?

**Comment by gregpakes** [comment]
Hi @jasonbivins 

**Do you get this error from the same directory every time?**
It is from directories where images are pulled from.

**Do you only see this on new image pulls?**
No - It happens mainly when new containers are created.

**do you have any settings that require default documents?**
This is not related.

** It sounds like the web.config file is missing from c:\src\Website\system\images\16\ but that it's getting created after IIS calls for it and doesn't see it. Could you remove the web.config file from one of the directories that works, and see if you get an error when you pull from it again?**
I don't think this is related.  .NET will always look for a web.config file as nested configs are supported.  No, a config file is not created.

**Comment by ckasabula** [comment]
Same setup. Same issue. @gregpakes Were you able to resolve this of find some work-around? Thanks.

**Comment by ckasabula** [comment]
Giving full control to Everyone on the source folder worked for me as a work-around.
