### ISSUE TITLE
HttpBadResponseException when using "bip" configuration option

### ISSUE THREAD

**Issue by MartinKuhne** [docker/for-win#7878]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker starts

### Actual behavior
Docker does not start

### Information
Added the following to daemon.json
  "bip": "10.200.0.1/24",
  "default-address-pools":[
    {"base":"10.201.0.0/16","size":24},
    {"base":"10.202.0.0/16","size":24}
  ]

It is reproducible
I have used this on Linux, successfully (we have a conflict with an internal network on the default bridge IP)
Did the problem appear with an update? Not known, we recently switched to docker in Windows mode
Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

Docker Desktop Version

Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:43:18 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:57:30 2020
  OS/Arch:          windows/amd64
  Experimental:     false

Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 16
 Server Version: 19.03.12
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 19041 (19041.1.amd64fre.vb_release.191206-1406)
 Operating System: Windows 10 Enterprise Version 2004 (OS Build 19041.388)
 OSType: windows
 Architecture: x86_64
 CPUs: 16
 Total Memory: 63.7GiB
 Name: MNBX-Kuhne
 ID: E34A:4Q45:SFGA:SBOL:KKUE:75FD:VAH6:D6PH:FZRT:UJOS:HJBR:3RG4
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 30
  System Time: 2020-07-29T10:26:45.2643066+02:00
  EventsListeners: 2
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

### Steps to reproduce the behavior
Added the following to daemon.json
  "bip": "10.200.0.1/24",
  "default-address-pools":[
    {"base":"10.201.0.0/16","size":24},
    {"base":"10.202.0.0/16","size":24}
  ]
Restart Docker

**Comment by ebriney** [comment]
Hi @MartinKuhne, that's an upstream issue in the windows daemon.
Can you check in https://github.com/moby/moby/issues if it's not already reported and file an issue there please.
