### ISSUE TITLE
Docker malware --> Yes or Not ??

### ISSUE THREAD

**Issue by OnlyHardOfficial** [docker/for-win#7881]
I have the latest Version of Docker Docker Desktop2.3.0.4 (latest build) here: 

![image](https://user-images.githubusercontent.com/19652056/88777732-76a81480-d17f-11ea-90ec-a6dcd0763622.png)

 Actual behavior

-Detalhes de Relatório-
Data do Evento de Proteção: 29/07/20
Hora do Evento de Proteção: 09:33
Ficheiro de Registo: 2aad82bc-d176-11ea-987c-2c56dc481612.json

-Informação de Software-
Versão: 4.1.2.73
Versão dos Componentes: 1.0.979
Versão do Pacote de Atualização: 1.0.27621
Licença: Versão de Avaliação Gratuita

-Informação do Sistema-
SO: Windows 10 (Build 19041.421)
CPU: x64
Sistema de Ficheiros: NTFS
Utilizador: System

-Detalhes do Website Bloqueado-
Website Malicioso: 1
C:\Program Files\Docker\Docker\resources\vpnkit.exe, Bloqueado, -1, -1, 0.0.0

-Dados do Website-
Categoria: Cavalo de Troia
Domínio: fedora-epel.koyanet.lv
Endereço IP: 89.111.47.130
Porta: 443
Tipo: A sair
Ficheiro: C:\Program Files\Docker\Docker\resources\vpnkit.exe

Please, help us understand the problem.  For instance:
  - I have installed CentOS 7 from: https://hub.docker.com/_/centos --> Version Centos7 amd64 bit
  

  - Windows Version:
  - Docker Desktop Version: Windows 10 Pro N
  

Steps to reproduce the behavior

During the installation this message appeared to me! I wonder if this will be normal behavior, or if it is something abnormal that I should be careful about?.

**Comment by OnlyHardOfficial** [comment]
Steps to reproduce the behavior

 Version Centos7 amd64 bit
  
-->
  - Windows Version:
  - Docker Desktop Version: Windows 10 Pro N
  

Steps to reproduce the behavior

**Comment by stephen-turner** [comment]
I don't understand what the fedora-epel.koyanet.lv is here, that's nothing to do with us. It looks like your malware detection program is confused.

**Comment by OnlyHardOfficial** [comment]
Thanks in advance, and for the quick response.

I also asked myself the same question, but I still researched it online, which after all is trusted link. is from a repo from Fedora
As shown in the link below:
https://www.google.com/search?source=hp&ei=RrYhX_aWEo6sUs_XjPAM&q=http%3A%2F%2Ffedora-epel.koyanet.lv%2F&oq=http%3A%2F%2Ffedora-epel.koyanet.lv%2F&gs_lcp=CgZwc3ktYWIQA1CQBliQBmDdCGgBcAB4AIABYIgBYJIBATGYAQCgAQKgAQGqAQdnd3Mtd2l6sAEA&sclient=psy-ab&ved=0ahUKEwj20ai8gvPqAhUOlhQKHc8rA84Q4dUDCAc&uact=5

Please close this topic
