### ISSUE TITLE
Localhost sent an invalid response in Google Chrome

### ISSUE THREAD

**Issue by loordbarringtn** [docker/for-win#7888]
Hello!

This happens with any working container: An error in Google Chrome:

> This site can’t provide a secure connectionlocalhost sent an invalid response.
Try running Windows Network Diagnostics.
ERR_SSL_PROTOCOL_ERROR

One thing only helps - clearing each time Google Chrome browser cache. But it is not a solution - isn't?

In the same time - no problems on Mozilla and Opera browsers...

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
This doesn't seem like a Docker bug, but something in the way your containers or browser are configured.
