### ISSUE TITLE
Docker Upgrade does not restart all containers

### ISSUE THREAD

**Issue by genifycom** [docker/for-win#789]
### Expected behavior
After upgrade, ALL containers get restarted

### Actual behavior
Only containers in the current daemon get started

### Information
I had mssql running in a linux containers and also two windows containers running websites.
After yesterdays (June 1 st) urgrade, Docker restarted but only the Windows containers restarted. The linux mssql was not.

### Steps to reproduce the behavior

Run containers in both Windows and linux.
Run a Docker upgrade.

**Comment by jasonbivins** [comment]
Hi @genifycom   can you please provide more information on this one?

 - Diagnostic ID from "Diagnose & Feedback" in the menu.

- host distribution and version (Windows version, build number, etc)

Thanks!

**Comment by jasonbivins** [comment]
Hi @genifycom     What build were you upgrading to when you saw this?  Stable or Edge?
