### ISSUE TITLE
memory usage above 3.5GB when using WSL2 + Linux Containers

### ISSUE THREAD

**Issue by ZeroIsALoop** [docker/for-win#7895]
Windows 10 Pro Machine w/ 24GB RAM. Docker vmmem process is consistently above 3.5GB. When I run the exact same images directly on a rPi debian distro, the entire OS + dockers containers + everything else installed on the rPi image is smaller than 3.5GB. It used to not be like this, but I am not sure which version of Docker for windows introduced this.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 11C06AF2-0C40-4E71-B92F-E64601035458/20200730023650

### Expected behavior
Docker for Windows does not consume 3.5GB of memory just for vmmem process.

### Actual behavior
Docker for Windows does consume 3.5GB of memory just for vmmem process.

### Information

  - Windows Version: WIndows 10 Pro 10.0.19041 N/A Build 19041 Quad-Code 3.6MHz, 24,527 MB, 1GB SSD
  - Docker Desktop Version: 2.3.4.0 (46980) Edge
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Running directly on a Dell desktop machine (no VM).

### Steps to reproduce the behavior

  1. Just running the Docker For Windows application
  2. 6 containers: NodeRed, DockerMon, Portainer, HomeAssistant, Mosquitto, Organizr

**Comment by stephen-turner** [comment]
Docker is not in control of the amount of memory used by the vmmem process (it's a Windows process not ours). But we do document at the bottom of https://docs.docker.com/docker-for-windows/wsl/ how to limit the memory used by WSL 2.
