### ISSUE TITLE
Latest update fails with WSL 2

### ISSUE THREAD

**Issue by gbtec-ext-fernandoquiroga** [docker/for-win#7896]
Yesterday I installed the latest version of Docker Desktop for Windows, since this update Docker is unable to start with WSL 2 because it is trying to look for files in the wrong path as it is shown in the logs below. The host subfolder under /mnt does not exists, the correct path is /mnt/c/Program Files:

`WSL distro stopped while waiting for Lifecycle server.
  >Stdout:

  >Stderr:
2020/07/30 06:25:30 resolving **/mnt/host/c/**Program Files/Docker/Docker/resources/wsl/docker-wsl-cli.iso...
Error: mounting wslCLIDest: stat **/mnt/host/c/**Program Files/Docker/Docker/resources/wsl/docker-wsl-cli.iso: no such file or directory
2020/07/30 06:25:30 stat /mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-wsl-cli.iso: no such file or directory
mounting wslCLIDest
main.doRun
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:224
main.run.func1
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:83
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:762
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:852
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).Execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:800
main.main
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357`

**Comment by erikhakansson** [comment]
I got this too, 

* Docker Desktop 2.3.0.4 (46911)
* Windows 10 Build 20180

**Comment by gbtec-ext-fernandoquiroga** [comment]
In my case is the same Docker Desktop version, but Windows 10 Builld 2004
