### ISSUE TITLE
Cannot pull from Docker Hub while Cisco Anyconnect VPN is active

### ISSUE THREAD

**Issue by DiJu519** [docker/for-win#79]
### Expected behavior
I'd be able to pull from Docker Hub

### Actual behavior
$ docker build .
Sending build context to Docker daemon 56.21 MB
Step 1 : FROM jenkins:1.642.4
Pulling repository docker.io/library/jenkins
Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/jenkins/images. You may want to check your internet connection or if you are behind a proxy.

### Information

  - 7AA5A5C2-9D5A-45A1-B8A9-D6839E9D8A7C/2016-09-13_23-22-37

### Steps to reproduce the behavior

  1. Connect to Cisco Anyconnect VPN
  2. Attempt Docker Pull

**Comment by dgageot** [comment]
Hi @DiJu519 it looks like you are still using `beta21`. Please update to Beta26 because it contains lots of fixes to the networking.

**Comment by dgageot** [comment]
Hi @DiJu519 Did you manage to fix your issue with a more recent version?

**Comment by DiJu519** [comment]
Hey @dgageot sorry for the late reply.

I did! I'm able to pull from docker hub (docker pull hello-world) and, at least hit my private repository(complains about unauthorized creds, need to figure out where those go).

Thank you.
