### ISSUE TITLE
Docker fails to start on Windows

### ISSUE THREAD

**Issue by roytsang** [docker/for-win#790]
### Expected behavior
Docker start when log in windows

### Actual behavior
Docker crash on startup

### Information

  - Diagnostic ID: 379DF66E-7892-499B-95EA-057AE9C3735F/2017-06-03_12-25-08
  - Docker Version: 17.03.1-ce-win12 (12058)
  - OS: Windows 10 Pro
  - Edition: Professional
  - Build: 14393

Docker crash on windows start every times with an error prompt:
```
The process cannot access the file 'C:\Windows\TEMP\gelymzaa.qbn' because it is being used by another process.
```

However, as check from resource monitor, only docker.exe is accessing 'C:\Windows\TEMP\gelymzaa.qbn'.

After the crash, the docker is able to start after a manually restart.  

### Steps to reproduce the behavior

  1. Install docker on windows and configure it to start when log in
  2. Every times windows boot up, the docker will try to start and finally crash
  3. Open Docker Settings, manually clicking "Restart Docker..." can start the docker

**Comment by jasonbivins** [comment]
Hi @roytsang 
Have you tried reinstalling docker to see if that resolves it?

**Comment by roytsang** [comment]
I have tried reinstalling docker and cannot resolves.
Also I have just reset the pc a few day ago, and the problem exist both before and after I reset the pc.

**Comment by jasonbivins** [comment]
@roytsang 

Try uninstalling docker, deleting that .qbn file and then reinstalling.  It sounds like we're looking for a config file where it shouldn't be

**Comment by roytsang** [comment]
It seems work fine. Thanks for your help.
