### ISSUE TITLE
Container won't build on 2016, but builds on windows 10.

### ISSUE THREAD

**Issue by gregpakes** [docker/for-win#791]
I have created a relatively simple dockerfile, which works fine on Windows 10 (hyper-v), but fails to build on windows 2016.

The error is when I attempt to delete a directory.  On Windows 10 it removes the folder fine, on Windows 2016, I get the following error:

> Remove-Item : Cannot remove item C:\xxxx\xxxx: There are no more files.

The command that fails is:

> RUN Remove-Item $env:root_path -recurse -force

I have spent a long time looking into this and I really don't think it's a general powershell issue.  I think it is something about docker on windows 2016 causing this issue.  The error "there are no more files", seems to be very rare.  Google barely returns anything for it.  The issue also exists if I try and use RMDIR directly rather than Remove-Item.

The dockerfile in questions is below:

```
FROM microsoft/iis

LABEL maintainer "Greg Pakes"

SHELL ["powershell", "-command"]

# Windows Features
RUN  Enable-WindowsOptionalFeature -FeatureName "IIS-WebServerRole" -Online -All -NoRestart; \
	 Enable-WindowsOptionalFeature -FeatureName "IIS-ISAPIExtensions" -Online -All -NoRestart; \
	 Enable-WindowsOptionalFeature -FeatureName "IIS-ASP" -Online -All -NoRestart; \
	 Enable-WindowsOptionalFeature -FeatureName "IIS-HttpCompressionStatic" -Online -All -NoRestart; \
	 Enable-WindowsOptionalFeature -FeatureName "IIS-HttpCompressionDynamic" -Online -All -NoRestart; \
	 Enable-WindowsOptionalFeature -FeatureName "IIS-DefaultDocument" -Online -All -NoRestart; \
	 Enable-WindowsOptionalFeature -FeatureName "IIS-HttpErrors" -Online -All -NoRestart; \
	 Enable-WindowsOptionalFeature -FeatureName "IIS-HttpLogging" -Online -All -NoRestart; \
	 Enable-WindowsOptionalFeature -FeatureName "IIS-ASPNET45" -Online -All -NoRestart; \
	 Enable-WindowsOptionalFeature -FeatureName "IIS-ApplicationInit" -Online -All -NoRestart; \
	 Enable-WindowsOptionalFeature -FeatureName "IIS-WebSockets" -Online -All -NoRestart; \
	 Enable-WindowsOptionalFeature -FeatureName "IIS-WebServerManagementTools" -Online -All -NoRestart;



ENV ROOT_PATH 'c:\DummyPath'
ENV SITE_NAME 'Site'

# Remove the default website
RUN Remove-Website -Name 'Default Web Site';	

# Root Application Creation
RUN Write-Host "Creating the root application"; \
	$rootApplicationPath = Join-Path $env:Root_Path 'Site\Root'; \
	Write-Host "Using path [$rootApplicationPath]"; \
	if (!(Test-Path $rootApplicationPath)){ New-Item -Path $rootApplicationPath -ItemType Directory -Force | Out-Null }; \
	Write-Host "Creating Application Pool"; \
	$MainApplicationPool = New-WebAppPool -Name $env:SITE_NAME -Force; \
	$MainApplicationPool.managedPipelineMode = 'Integrated'; \
	$MainApplicationPool.processModel.maxProcesses = 1; \
    $MainApplicationPool.enable32BitAppOnWin64 = 'true'; \
    $MainApplicationPool.managedRuntimeVersion = 'v4.0'; \
    $MainApplicationPool | Set-Item; \
	Write-Host "Creating Website"; \
	$RootWebsite = New-Website -Name $env:Site_Name -PhysicalPath $rootApplicationPath -ApplicationPool $env:SITE_NAME; \
	Write-Host "Done";

# Main Application Creation
RUN Write-Host "Creating the [main] sub application"; \
	$mainApplicationPath = Join-Path $env:Root_Path 'Site\Web'; \
	if (!(Test-Path $mainApplicationPath)){ New-Item -Path $mainApplicationPath -ItemType Directory -Force | Out-Null }; \
	$MainApplication = New-WebApplication -Name Main -ApplicationPool $env:SITE_NAME -PhysicalPath $mainApplicationPath -Site $env:SITE_NAME; \
	Write-Host "Done";

# Legacy Application Creation
RUN Write-Host "Creating the [legacy] sub application"; \
	$legacyApplicationPath = Join-Path $env:Root_Path 'Site\Legacy'; \
	if (!(Test-Path $legacyApplicationPath)){ New-Item -Path $legacyApplicationPath -ItemType Directory -Force | Out-Null }; \
	$LegacyApplication = New-WebApplication -Name Legacy -ApplicationPool $env:SITE_NAME -PhysicalPath $legacyApplicationPath -Site $env:SITE_NAME; \
	Write-Host "Done";

# Legacy Rest Api Creation
RUN Write-Host "Creating the [legacy rest api] sub application"; \
	$legacyRestApiApplicationPath = Join-Path $env:Root_Path 'Site\legacyApi'; \
	if (!(Test-Path $legacyRestApiApplicationPath)){ New-Item -Path $legacyRestApiApplicationPath -ItemType Directory -Force | Out-Null }; \
	$legacyRestApiApplication = New-WebApplication -Name Api -ApplicationPool $env:SITE_NAME -PhysicalPath $legacyRestApiApplicationPath -Site $env:SITE_NAME\Legacy; \
	Write-Host "Done";

# Files directory
RUN Write-Host "Creating the files virtual directory"; \
	$filesDirectoryPath = Join-Path $env:ROOT_PATH "Files"; \
	if (!(Test-Path $filesDirectoryPath)){ New-Item -Path $filesDirectoryPath -ItemType Directory -Force | Out-Null }; \
	$filesVirtualDirectory = New-WebVirtualDirectory -Name files -PhysicalPath $filesDirectoryPath -Site $env:SITE_NAME;

# Configure IIS
RUN Write-Host "Configuring IIS"; \
	Set-WebConfigurationProperty -PSPath MACHINE/WEBROOT/APPHOST -Location $env:SITE_NAME -Filter system.webServer/asp -Name enableParentPaths -Value $true; \
    Set-WebConfigurationProperty -PSPath MACHINE/WEBROOT/APPHOST -Location $env:SITE_NAME -Filter system.webServer/asp/limits -Name maxRequestEntityAllowed -Value 204857600; \
    Set-WebConfigurationProperty -PSPath MACHINE/WEBROOT/APPHOST -Location $env:SITE_NAME -Filter system.webServer/asp/limits -Name bufferingLimit -Value 2073741824; \
    Set-WebConfigurationProperty -PSPath MACHINE/WEBROOT/APPHOST -Location $env:SITE_NAME -Filter system.webServer/asp/limits -Name scriptTimeout -Value 00:02:30; \
    Set-WebConfigurationProperty -PSPath MACHINE/WEBROOT/APPHOST -Location $env:SITE_NAME -Filter system.webServer/asp/cache -Name scriptFileCacheSize -Value 25; \
    Set-WebConfigurationProperty -PSPath MACHINE/WEBROOT/APPHOST -Location $env:SITE_NAME -Filter system.webServer/asp -Name logErrorRequests -Value $true; \
    Set-WebConfigurationProperty -PSPath MACHINE/WEBROOT/APPHOST -Location $env:SITE_NAME -Filter system.webServer/asp -Name errorsToNTLog -Value $true; \
    Set-WebConfigurationProperty -PSPath MACHINE/WEBROOT/APPHOST -Location $env:SITE_NAME -Filter system.webServer/asp -Name scriptErrorSentToBrowser -Value $true; \
    Set-WebConfigurationProperty -PSPath MACHINE/WEBROOT/APPHOST -Location $env:SITE_NAME -Filter system.webServer/httperrors -Name errorMode -Value 'Detailed'; \
    Remove-WebConfigurationProperty -PSPath MACHINE/WEBROOT/APPHOST -Location $env:SITE_NAME -Filter system.webServer/defaultDocument -name files; \
    Add-WebConfigurationProperty -PSPath MACHINE/WEBROOT/APPHOST -Location $env:SITE_NAME -Filter system.webServer/defaultDocument -name files -value @{value='index.asp'}; \
	Write-Host "Done";


# Delete all the folders - this is required as we are mounting the dev environment in.
# TODO: Can't get this to work on windows 2016
RUN Remove-Item $env:root_path -recurse -force
```

**Comment by friism** [comment]
On WS2016, can you try building with `--isolation=hyperv`. This issue is probably better on the `moby/moby` repo.

cc @jhowardmsft

**Comment by gregpakes** [comment]
@friism 

I get the same error when specifying the `--isolation=hyperv`

Shall I move this to moby?

**Comment by friism** [comment]
Yes - if you can, please also provide a simpler test-case that reproduces the problem reliably.

**Comment by richardgavel** [comment]
Does $env:root_path point to a directory on the host machine mounted into the Docker container?

**Comment by gregpakes** [comment]
@richardgavel At this point, there is no mapping to host folders.  The error is literally happening during a docker build.

**Comment by snorrk** [comment]
I got the same issue when deleting a folder that *was* mounted as a volume.

- docker run -d --name $containerName  --volume c:\shared:c:\shared
- docker exec -it $containerName cmd
- Copy some files to c:\shared
- docker commit $containerName "$containerName-image"
- docker run -d --name "$containerName-b" (no volume mount)
- docker exec -it "$containerName-b" cmd
- Remove-Item -Path c:\shared

Results in "Cannot remove item C:\shared: There are no more files."

**Comment by gregpakes** [comment]
This issue is completely blocking me.  I have given up on "dockerizing" my application due to this issue.

**Comment by richardgavel** [comment]
@gregpakes Where is c:\DummyPath?

**Comment by gregpakes** [comment]
@richardgavel 

It is in the container - the folder is created in the container.

**Comment by stephanwehr** [comment]
@gregpakes Came here because I had exactly the same issue...

With your Dockerfile I was able to reproduce the behavior:
> There are no more files.

**The Fix**
Here is how to fix it:
```
RUN ForEach($dir in (Get-ChildItem $env:root_path -Recurse)) { New-Item -Path $($dir.fullname) -Name file -ItemType File -Force | Out-Null }; \
  Remove-Item $env:root_path -recurse -force;
```
Now the Docker image builds successfully.
So, something funky is going on...

**However**
In your case it would not even make much sense to delete "c:\DummyPath" at the end.
The only thing it will do is to create a new image layer and your container size stays exactly the same.
The directory "c:\DummyPath" would still be present in the previous image layer.

**Docker Best Practices**
You should create and delete files before the **RUN** _instruction_ ends.
Invoking the **RUN** command will create another container image layer containing all the content produced by the given _instruction_.
It can help to reduce the number of _instructions_ in the Dockerfile and combine as many steps as possible into one **RUN** command. Create all necessary files and folders in one go and cleanup before the _instruction_ ends.

Error appears using this images (01 Jan 2018):
- microsoft/nanoserver:latest
- microsoft/iis:lastest

My Docker version:
```
PS C:\> Get-Package -Name Docker -ProviderName DockerMsftProvider

Name                           Version          Source                           ProviderName
----                           -------          ------                           ------------
docker                         17.06.2-ee-6     Docker                           DockerMsftProvider
```
On Windows Server 2016 (AWS):
```
PS C:\> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      14393  0
```

**Comment by JohannesDrexler** [comment]
Had the same issue. 
A little edit i had to make: `Get-ChildItem $env:root_path -Recurse` -> `Get-ChildItem $env:root_path -Recurse -Directory`

**Comment by jhowardmsft** [comment]
@gregpakes For the original issue, I just tried this on Windows Server 2016 1709 build (aka RS3/Windows Build 16299) running latest binaries from https://master.dockerproject.org and could not repro this.  You hit it on 14393 (aka RS1). Can you confirm if you are still hitting it using latest docker binaries, even if on RS1 - it's possible it's a platform bug that was fixed in RS3.

(Note for 1709, I had to change the FROM line to `FROM microsoft/iis:windowsservercore-1709`)

**Comment by dazinator** [comment]
I just hit this whilst applying powershell dsc.

./setup.ps1 

```
Configuration WebsiteInstance
{
    Import-DscResource -ModuleName PSDscResources
    Import-DscResource -ModuleName xWebAdministration
    Import-DscResource -ModuleName cNtfsAccessControl   
   
    node localhost
    {              
        File WebsiteDir
        {
            Ensure = "Present"
            Type = "Directory"
            DestinationPath = "C:/inetpub/wwwroot"            
        }
   }

WebsiteInstance
Start-DscConfiguration -Path .\WebsiteInstance -Wait -verbose -Force
```

dockerfile:

```
# escape=`
FROM microsoft/aspnet

ADD ./setup.ps1  /setup.ps1 
RUN powershell -NoProfile -File C:\setup.ps1

EXPOSE 80 4022 4023

```

output of docker build - shows error when the dsc is applied:

>
[[File]WebsiteDir] There are no more files.
There are no more files.
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : Windows System Error 18
    + PSComputerName        : localhost

**Comment by waynesi** [comment]
I'm still experiencing this issue. Use the microsoft/windowsservercore:latest on Windows Server 2016 Standard 1607 with docker 18.06.0-ce build 0ffa825.

**Comment by jhowardmsft** [comment]
See https://github.com/moby/moby/issues/33532#issuecomment-412629536
