### ISSUE TITLE
Kubernets Cluster stuck on "Starting" and settings screen frozen

### ISSUE THREAD

**Issue by Marios85** [docker/for-win#7915]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: DC6589FB-E42D-4650-820C-3519CAF46B77/20200731091551

### Expected behavior
Kubernetes cluster should be running and the settings screen should be accessible.

### Actual behavior
Kubernetes

s Cluster stuck on "Starting" and settings screen frozen (greyed out with loading icon)

### Information
  - Windows Version: Windows 10 Home - Version 2004
  - Docker Desktop Version: 2.3.0.3
  - Running locally on desktop

Also when running the command "kubectl cluster-info dump" results in the following error message: Unable to connect to the server: dial tcp: lookup kubernetes.docker.internal: no such host

However Kubernetes system containers seem to be running. 

### Steps to reproduce the behavior
1. Install Docker Desktop version 2.3.0.3
2. Go to settings and check "enable Kubernetes" and "show system containers".
3. Click Apply.

[log (2).TXT](https://github.com/docker/for-win/files/5006244/log.2.TXT)

**Comment by jfelixdev** [comment]
Having this same issue! Tried both stable and edge.
Once I enable Kubernetes in settings, I get an infinite "Starting..." indicator. Restarting computer has no effect. Resetting Kubernetes cluster has no effect. Not sure what to do, devops isn't really my field of expertise...

Windows 10 Home - Version 2004
Docker 2.3.4.0
Diagnostics ID: F910D4DF-81B3-4DB0-B1A0-FEFF3C702A46/20200807235606

![Annotation 2020-08-07 170302](https://user-images.githubusercontent.com/13112048/89697188-e7fa6c80-d8cf-11ea-960d-76fcbee10723.png)

**Comment by kiranbhalerao123** [comment]
@jfelixdev did you find any solution for this? I'm having same issue.

**Comment by jfelixdev** [comment]
> @jfelixdev did you find any solution for this? I'm having same issue.

I have not.

**Comment by Nish17g** [comment]
It appears many are facing this issues .Has there been any solution to this ?
