### ISSUE TITLE
System.InvalidOperationException: Failed to deploy distro docker-desktop to stdout: Error: 0xffffffff Windows 10 version 2004

### ISSUE THREAD

**Issue by gadros** [docker/for-win#7919]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by gadros** [comment]
Diagnostics ID: 8DE40E34-BDE4-4C90-8CBE-4DD4C0849F27/20200731124730.
this crash is after several uninstalls and installs. disabling most of Hyper-v services (following different suggestions...).
lastly i've configured the system to use wsl version 1 and when installing docker desktop unchecked the wsl2 check-box (i.e.: use version 1). still same miserable results.

i suffered (suffer?) from the same issue as reported in https://github.com/docker/for-win/issues/7208# (diagnostics id: 759D0CB8-4722-49F0-A635-EA83A7868FDD/20200612114453).
others also.
how does one bump up votes?

**Comment by ngd929** [comment]
Not sure if you've had this resolved yet, but here's what worked for me after following these steps:

(from #7208)

    Uninstall Docker and WSL 2 kernel.
    Go to the Control Panel -> Programs -> Turn Windows features on or off
    Uncheck the following: Containers, Hyper-V, Windows Subsystem for Linux
    Restart the system
    Install Docker without the WSL2 enabled/checked in the first screen
    Go to the Control Panel -> Programs -> Turn Windows features on or off
    Turn on/check the Windows Subsystem for Linux
    Restart the system.
    Do not install the WSL2 Kernel when reinstalling Docker.﻿﻿

I was not able to launch the Ubuntu WSL initially (got the same error messages in the first post), I then ran "**wsl --update**" and was able to launch the Ubuntu WSL and got Docker started running again.

My system now has wsl kernel 4.19.128 and Build 20201.rs_prerelease.200822-1922, and the default wsl version is now version 2.

**Comment by PawelSpoon** [comment]
for me that happened after pc restart. so i do believe the port 53 is again used by somebody and i need to kill that one first.
any chance to make the port 53 configurable ?
