### ISSUE TITLE
Docker hv-sock proxy (vsudd) is not reachable

### ISSUE THREAD

**Issue by hijarian** [docker/for-win#792]
### Expected behavior
Docker is starting.

### Actual behavior
Error message "Docker hv-sock proxy (vsudd) is not reachable" like in the screenshot below:
![default](https://cloud.githubusercontent.com/assets/967464/26787454/b6ab05d0-4a12-11e7-9656-cc2d5d3a8bb2.png)

### Information

Diagnostics ID:
9FAB8623-EF72-48E3-9C0D-3089A5926704/2017-06-05_17-11-46

Windows 10 Pro.

Docker Version 17.03.1-ce-win12 (12058)
Channel: stable
d1db126

**I have installed Docker and was using it without any problem before. A couple of days ago my motherboard died and I replaced it together with the CPU, GPU and RAM with new hardware, keeping the OS intact. After the switch, Docker stopped working.**
I have already tried to uninstall Docker, disable Hyper-V, reboot, install Docker, enable Hyper-V. Same error.

### Steps to reproduce the behavior

Trying to start Docker manually or even just to start the Windows because Docker is auto-starting reproduces the bug.

**Comment by spewu** [comment]
I got the same problem suddenly - but only with Linux containers.

I tried switching to Windows containers, and then back to Linux containers - and now it works again

**Comment by whitecolor** [comment]
When I start window currenlty get this error:

```
Docker hv-sock proxy (vsudd) is not reachable
   at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```
Uploaded report ID:
7D3B6C3A-9617-4CD7-8513-C98A06C313AE/2017-06-11_16-49-49

This is log at the moment:
https://gist.github.com/whitecolor/8338c53aad3ace98bf6742cdb47e08e7

After manual restart (in Reset menu) it usually starts normally, (sometimes has to try to restart multiple times), if it doesn't work have to do reset to factory defaults (after this done during some time docker has no problems a restart, etc).

**Comment by whitecolor** [comment]
I had really disappointing experience with Docker for windows recently for dev workflow, it never starts with windows - always some erros, and often need to reset to defaults (make all tunings and download all the images) to make it start ever again.

**Comment by baobiao** [comment]
Same stack trace also happening to me. Build **17.06.0-ce** dated **Fri Jun 23 21:30:30 2017**.

**Comment by ctmcisco** [comment]
For anyone following this ticket:

Try the following:

1. Switch or stay on Windows Containers.
2. Disable the "Start when Windows starts" setting.


![image](https://user-images.githubusercontent.com/14852041/37053107-e9a96bd8-2140-11e8-9bdf-b264980b6127.png)

3. Exit Docker application
4. restart docker services via PowerShell

get-service *docker* | Restart-Service -Force -Verbose

5. Launch Docker , Run as Admin
6. Swtich to Linux Containers.

TEST:

Reboot Windows 10
Launch Docker 
Does it work?

You can also parse the docker log in PowerShell for troubleshooting:

cat C:\Users\USERPROFILE\AppData\Local\Docker\log.txt -tail 10 -wait
