### ISSUE TITLE
Pull image via API: connection canceled

### ISSUE THREAD

**Issue by nlaplante** [docker/for-win#793]
### Expected behavior
Images pulled from remote repositories via API can be pulled successfully

### Actual behavior
Pull process starts and then ends unexpectedly with a "Connection canceled..." entry in the logs.

### Information

  - Diagnostic ID : E3704B94-0711-4BA2-96DB-C8A01CAD033B/2017-06-05_13-50-48
  - Docker 17.03.1-ce
  - Windows 10 Pro version 1703 build 15063.332
  - Image can be pulled via CLI

### Steps to reproduce the behavior

1. Call POST /images/create?fromImage=REPO_URL/IMAGE_NAME&tag=TAG_NAME
2. wait for pull to complete
3. Connection canceled....

**Comment by jasonbivins** [comment]
Hi @nlaplante   We're actually seeing the same thing pulling from Docker repos right now - can you try again later and let me know if you're able to pull images?

**Comment by nlaplante** [comment]
It's been doing this since starting in working on an app which pulls images from AWS ECR repositories. I've been working on this for the past 3 weeks and I could never ever pull an image via the API. CLI works everytime. I'm not pulling from the Docker repositories.

**Comment by arasheedu** [comment]
I tried this on latest daemon that I built myself and it is pulling fine.

My POST request was to "http://localhost:2375/v1.27/images/create?fromImage=microsoft/nanoserver:latest"

Below docker version info from docker -H 127.0.0.1:2375 version
==========================================

Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-dev
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   36db52a70
 Built:        06/07/2017 21:00:38
 OS/Arch:      windows/amd64
 Experimental: false

**Comment by nlaplante** [comment]
I've done more tests with this and most of the time it fails. Out of around 25 tries, I could pull the image 3 times.

```Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

*Note that I'm using Hyper-V containers*.

**Comment by nlaplante** [comment]
BTW, image pulling via the API using the exact same code works fine on Fedora Linux.
