### ISSUE TITLE
MobyLinuxVM fails to start

### ISSUE THREAD

**Issue by paxtaru** [docker/for-win#794]
### Expected behavior
Docker should start properly.

### Actual behavior
Docker startup fails 

### Information
Diagnostic ID : 21428929-D1E3-49B7-8ACE-C495747E5929/2017-06-05_16-38-41
Version: Docker CE 17.03.1-ce-win12 stable release.
OS version: Windows 10 Enterprise 64-bit

The specific error in the log file:
[16:30:32.843][Notifications  ][Error  ] Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID E2B4DEA4-1300-43B4-9D49-BBCC2DEEC5ED)

'MobyLinuxVM' failed to start worker process: Windows cannot verify the digital signature for this file. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source. (0xC0000428). (Virtual machine ID E2B4DEA4-1300-43B4-9D49-BBCC2DEEC5ED)
at Start-MobyLinuxVM, <No file>: line 287
at <ScriptBlock>, <No file>: line 382

### Steps to reproduce the behavior
I first installed the Edge channel install but I was unable to start it up and the docker icon would not even show up.  Uninstalled the Edge version and installed the stable channel instead.  Now the icon shows but it appears to be failing when attempting to load the MobyLinux virtual machine in Hyper-V.

**Comment by wikrie** [comment]
looks like the same in #748

**Comment by paxtaru** [comment]
Possibly, although in #748 the stopping points do not appear to be the same.  Based on the error message, I tried starting Docker with device signature verification turned off, but I'm still getting the same error.

**Comment by jasonbivins** [comment]
Hi @paxtaru    Do you have UAC enabled?

Do you get the same errors if you manually recreate the MobyLinuxVM?
powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -destroy
powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -create

**Comment by paxtaru** [comment]
UAC is enabled by corporate policy.  I can disable it temporarily just for development purposes but it will get changed back.  I just re-installed the stable release again to make sure everything's as clean as I can make them...

I do not get the same errors if I manually recreate the MobyLinuxVM with the commands you provided.  Here's the output (side note: running PowerShell in Administrator mode):
```
PS C:\WINDOWS\system32> powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1
" -destroy
Script started at 08:55:06.275
Module loaded at 08:55:08.837
VM MobyLinuxVM does not exist
Destroying Switch DockerNAT...
Removing VM MobyLinuxVM...
Delete VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx

PS C:\WINDOWS\system32> cd 'C:\Program Files\Docker\Docker\resources\'

PS C:\Program Files\Docker\Docker\resources> powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\re
sources\MobyLinux.ps1" -create
Script started at 08:55:42.956
Module loaded at 08:55:45.050
Using existing Switch: DockerNAT
Using existing Switch IP address
Creating VM MobyLinuxVM...
Setting CPUs to 2 and Memory to 2048 MB
Creating dynamic VHD: C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
Attach VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
Connect Internal Switch DockerNAT
Attach DVD .\mobylinux.iso
Disabled Guest Service Interface
Enabled Heartbeat
Disabled Key-Value Pair Exchange
Enabled Shutdown
Enabled Time Synchronization
Disabled VSS
VM created.
```

**Comment by wittyameta** [comment]
@paxtaru Could you figure this out? I'm facing the same issue.

**Comment by paxtaru** [comment]
@wittyameta I was not able to figure out how to make it work properly.  With the project I had to do I just switched everything to a Linux system, then my development box to a MacOS laptop.  You can try the steps above to get MobyLinuxVM mounted and see if you can start Docker after that, but I've read articles about how you'd still lose your dev environment after a reboot...
A coworker of mine used an earlier version of Docker which worked OK, but you will have to get VirtualBox set up locally and configured to run properly.  I didn't go down that path, though.

**Comment by wittyameta** [comment]
@paxtaru I guess I would just rollback my Windows version :-/

**Comment by paxtaru** [comment]
@wittyameta sorry about that, hope the official development team can get this fixed up soon.

**Comment by TommyWu1618** [comment]
I have this error message as well :( . I've tried on all the stable and edge builds last few weeks for Docker Community Edition with no luck. 
I am on Windows 10 Pro version 1703.

**Comment by toddysm** [comment]
Are you guys running any anti-virus or other anti-malware software? Here is an article that talks about that: https://social.technet.microsoft.com/Forums/windows/en-US/2df51b2d-18d3-463e-8fe5-3517bfb2950f/vm-failed-to-start-worker-process-the-process-terminated-unexpectedly?forum=win10itprovirt

I started seeing the same issues after installing SentinelOne agent. Waiting for them to reply right now with a fix.

**Comment by wittyameta** [comment]
@toddysm I'm getting a different error message than in the link you posted.

**Comment by toddysm** [comment]
@wittyameta it would be helpful to post the error you are getting

**Comment by paxtaru** [comment]
@toddysm sorry for the super delayed response to your previous post.  I am running Symantec anti-virus on my old Windows laptop, and we can't un-install it due to work policies.  Still hoping to see a fix here, one of my coworkers is having the same issue.

**Comment by toddysm** [comment]
@paxtaru Are you able to use any VM created on Hyper-V at all? In general, this is an issue between the anti-virus and Hyper-V - nothing to do with Docker. The suggestion is to add certain executables to the exception list on the anti-virus (of course if you are allowed to do even that by your IT people ;)). Here an article from MSFT describing what should be on the exception list:

https://social.technet.microsoft.com/wiki/contents/articles/2179.hyper-v-anti-virus-exclusions-for-hyper-v-hosts.aspx

I would try with Vmms.exe and Vmwp.exe first.

**Comment by wittyameta** [comment]
@toddysm I'm gettting "Windows cannot verify the digital signature for this file" error.
The error mentioned on https://social.technet.microsoft.com/Forums/windows/en-US/2df51b2d-18d3-463e-8fe5-3517bfb2950f/vm-failed-to-start-worker-process-the-process-terminated-unexpectedly?forum=win10itprovirt is a bit different.

I do have Symantec anti-virus, but it is my work laptop and I can't change the exception list.

However, I'm not getting the error on older windows 10 version (even with anti-virus installed).

**Comment by toddysm** [comment]
@wittyameta This error started showing up for me after I upgraded to Windows 10 Creator's Update because Microsoft added some additional security features. Please check whether you have the Creator's Update on the machine that you see the error. 

If you don't have enough permissions to modify the exception list, your best bet would be to work with your IT department. Hopefully, anti-virus vendors and Microsoft will come up to an agreement soon and will start fixing this issue.

**Comment by wittyameta** [comment]
Yeah, it's the Creator's Update. I guess I'll wait for Microsoft to fix this.
Thanks.

**Comment by Hiroyuki-Nagata** [comment]
I'm unexpectedly experiencing this issue.  
From command line, I could destroy/create MobyLinux. But, I couldn't start Hyper-V VM.

**Comment by ericzhill** [comment]
If you're running CarbonBlack, add a specific allow rule for the following file:

C:\Windows\System32\vmwp.exe

**Comment by 141801** [comment]
I cannnot create vm using the command as follows , appreciate for help

PS C:\Program Files\Docker\Docker\resources> powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -create
Script started at 11:40:58.885
Module loaded at 11:41:01.094
Using existing Switch: DockerNAT
Using existing Switch IP address
Creating VM MobyLinuxVM...
powershell : Hyper-V\New-VM : 操作に失敗しました。
発生場所 行:1 文字:1
+ powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Doc ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Hyper-V\New-VM : 操作に失敗しました。:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

発生場所 C:\Program Files\Docker\Docker\resources\MobyLinux.ps1:187 文字:15
+         $vm = Hyper-V\New-VM -Name $VmName -Generation 2 -NoVHD
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-VM], VirtualizationException
    + FullyQualifiedErrorId : Unspecified,Microsoft.HyperV.PowerShell.Commands.NewVM

**Comment by elimn** [comment]
I had the same problem, but none of the above solutions worked for me. I tried tons of variations on them, running various steps as an admin, rebooting in between, uninstalling and reinstalling Hyper-V. Here's what finally worked:

1. Open Hyper-V Manager
2. Click Hyper-V Settings
3. Under Server: Virtual Hard Disks click "Browse", and select an appropriate folder
4. Under Server: Virtual Machines click "Browse", and select an appropriate folder
5. Click Apply, then retry running Docker.

The problem was that ages ago I had setup Hyper-V to use a custom folder for its files. Some time during the intervening years I had delete those folders, as I stopped using Hyper-V. Thus, I was getting the exact same error message as everyone else, but for a different reason.

**Comment by schwinbp** [comment]
I am still having this issue. Nothing in the above responses has resolved it.

When I run this ...
powershell -ExecutionPolicy ByPass -File .\MobyLinux.ps1 -IsoFile .\docker-for-win.iso -Create

 It fails on this line...
Hyper-V\New-VM -Name 'MobyLinuxVM' -Generation 2 -NoVHD -Force

And I am getting this error...
powershell : Hyper-V\New-VM : Failed to create a new virtual machine.
At line:1 char:1
+ powershell -ExecutionPolicy ByPass -File .\MobyLinux.ps1 -IsoFile .\d ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Hyper-V\New-VM ...irtual machine.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
'MobyLinuxVM' failed to realize. (Virtual machine ID 87517683-5C0B-41FF-AA74-E9EE951E820A)
Failed to access configuration store: A virtual disk support provider for the specified file was not found. 
(0xC03A0014).
At C:\Program Files\Docker\Docker\resources\MobyLinux.ps1:191 char:15
+         $vm = Hyper-V\New-VM -Name $VmName -Generation 2 -NoVHD
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-VM], VirtualizationException
    + FullyQualifiedErrorId : OperationFailed,Microsoft.HyperV.PowerShell.Commands.NewVM

Any other ideas I can try?

**Comment by icewhite** [comment]
I had the same issue and it turned out that my user wasn't a Hyper-V administrator. 

I followed [this](https://www.prolved.com/solved-required-permission/) guide to apply the permission, and after a restart, docker worked fine.
