### ISSUE TITLE
Docker instance in WSL2 terminal is not working properly.

### ISSUE THREAD

**Issue by mariofsalles** [docker/for-win#7945]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
That instance of docker has been loaded regardless of used terminal.
### Actual behavior
It hasn't worked properly in WSL2 terminal.
### Information

  - Windows Version: 
![image](https://user-images.githubusercontent.com/44972017/89179144-0c301380-d587-11ea-95f3-551b49c471ec.png)
  - Docker Desktop Version:
![image](https://user-images.githubusercontent.com/44972017/89179195-2833b500-d587-11ea-9994-b586ac95845b.png)
  - Distro information:
![image](https://user-images.githubusercontent.com/44972017/89179678-1acafa80-d588-11ea-9e6f-5607416ca9d0.png)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No, I am not

### Steps to reproduce the behavior

Given I was using WSL2 terminal.
When I was requesting the instance of an image. 
Then the image is not downloaded from the dockerhub.
![image](https://user-images.githubusercontent.com/44972017/89178624-efdfa700-d585-11ea-936e-3cda6d9a291e.png)
But if I have used the Powershell terminal 
And repeated the same command
Then the instance is performed normally.
![image](https://user-images.githubusercontent.com/44972017/89178881-7dbb9200-d586-11ea-8ad6-56bd95d38615.png)

**Comment by stephen-turner** [comment]
There is a Windows bug on the latest Insider builds, see microsoft/WSL#5648.

**Comment by mariofsalles** [comment]
> This is a Windows bug on the latest Insider builds, see [microsoft/WSL#5648](https://github.com/microsoft/WSL/issues/5648).
Thank @stephen-turner, the problem was provisionally fixed using the alias suggested in issue microsoft/WSL#5648.
