### ISSUE TITLE
Docker daemon failed to start on Windows 10 Pro

### ISSUE THREAD

**Issue by kemot90** [docker/for-win#7947]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E4ECEAC3-75E5-4CB6-8C63-697389A77EF1/20200803134953

### Expected behavior

Left-down corner indicates that Docker is running

### Actual behavior

Left-down corner indicates that Docker failed to start

System.TimeoutException:
Timed out waiting for the lifecycle-server to start.
This may be the result of a slow environment or there may be a real problem.
This timeout can be increased by editing settings.json, value 'lifecycleTimeoutSeconds'.
This file is usually in C:\Users\(your username)\AppData\Roaming\Docker
   w Docker.ApiServices.LifecycleClient.<WaitForServerUpAsync>d__8.MoveNext() w C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\LifecycleClient.cs:wiersz 86
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w Docker.Engines.LinuxHyperVEngine.<DoStartAsync>d__12.MoveNext() w C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\LinuxHyperVEngine.cs:wiersz 63
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() w C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:wiersz 29
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() w C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:wiersz 67
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() w C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:wiersz 92

### Information

  - Windows Version: Windows 10 Pro 
  - Docker Desktop Version: 2.3.0.4
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. Run Docker Desktop
  2. After 20-30 min left-down corner indicates that Docker failed to start

**Comment by abhinavssingh** [comment]
Hi @kemot90 

Could you please check Docker Desktop and Server service are running from Services?

**Comment by kemot90** [comment]
> 
> Could you please check Docker Desktop and Server service are running from Services?

Yes, I did that before creating this issue. I also try restart this services.
