### ISSUE TITLE
error during connect

### ISSUE THREAD

**Issue by mudimath** [docker/for-win#795]
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
[log.51.txt](https://github.com/docker/for-win/files/1054496/log.51.txt)

  2. ...

**Comment by jasonbivins** [comment]
Hi @mudimath 

Can you please provide a bit more information?

- Where are you seeing this error?
- Diagnostic ID from "Diagnose & Feedback" in the menu.
- host distribution and version (Windows version, build number, etc)
- Docker version


Thanks,
Jason
