### ISSUE TITLE
Docker not working in Windows 10 - Getting crashed frequently

### ISSUE THREAD

**Issue by haripriyanharry** [docker/for-win#7952]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by abhinavssingh** [comment]
Hi,

Please open issues with some details as your not providing any details, just submitting with pre formatted text. Before submitting any issue please click on Preview tab then submit.
