### ISSUE TITLE
Docker not working in windows 10

### ISSUE THREAD

**Issue by haripriyanharry** [docker/for-win#7953]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by abhinavssingh** [comment]
Hi, 

You may follow [here](http://www.abhinavksingh.in/2020/08/how-to-install-docker-desktop-2304-on.html) for your installation query.
