### ISSUE TITLE
Certain containers fail to start - "Error response from daemon: bad file descriptor: unknown"

### ISSUE THREAD

**Issue by ropnop** [docker/for-win#7959]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `DB081EB7-E720-4F94-AD97-81F2CE7D041F/20200804174313`

### Expected behavior
The container should start with the provided entry point

### Actual behavior
Certain containers just fail to start. With no output. With debug on, an error is shown. Most notably, anything from the CentOS 6 family:

```
C:\> docker -D run --rm -it --entrypoint=/bin/bash centos:6
time="2020-08-04T12:39:38-05:00" level=debug msg="Error resize: Error response from daemon: bad file descriptor: unknown\r"
   time="2020-08-04T12:39:38-05:00" level=debug msg="[hijack] End of stdout"
time="2020-08-04T12:39:38-05:00" level=debug msg="Error resize: Error response from daemon: Container 13b4569ea3ab96872282c0df362e5deae170f0bfb219e38aab01eedd4b23de63 is not running\r"
```

### Information

  - Windows Version: **Windows 10 20H2 (19042.388)**
  - Docker Desktop Version: **2.3.0.4 (46911)**
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: **No**

### Steps to reproduce the behavior

Anything based on CentOS:6 causes this error. This reliably fails on my machine: `docker -D run --rm -it --entrypoint=/bin/bash centos:6`

```
C:\> docker -D run --rm -it --entrypoint=/bin/bash centos:6
time="2020-08-04T12:39:38-05:00" level=debug msg="Error resize: Error response from daemon: bad file descriptor: unknown\r"
   time="2020-08-04T12:39:38-05:00" level=debug msg="[hijack] End of stdout"
time="2020-08-04T12:39:38-05:00" level=debug msg="Error resize: Error response from daemon: Container 13b4569ea3ab96872282c0df362e5deae170f0bfb219e38aab01eedd4b23de63 is not running\r"
```

**Comment by stephen-turner** [comment]
Interesting, I'm seeing this too on Windows but not on Mac.

I think this is a bug in the upstream engine, not in Docker Desktop, so I wonder if you could open your issue in https://github.com/moby/moby instead? Apologies, I would move the issue myself, but it's not possible because the destination is not part of the docker org.
