### ISSUE TITLE
Cannot start docker due to nat (?)

### ISSUE THREAD

**Issue by Tsukrov** [docker/for-win#796]
### Expected behavior
docker run -it microsoft/nanoserver should start
### Actual behavior
Got the following error from the very first run:

C:\Program Files\Docker\docker.exe: Error response from daemon: container 95f7eaf633c17a634a7135b0c3552241cf8226c37bc7d85f16519c07adc41e77 encountered an error during CreateContainer: failure in a Windows system call: Element not found. (0x490) extra info: {"SystemType":"Container","Name":"95f7eaf633c17a634a7135b0c3552241cf8226c37bc7d85f16519c07adc41e77","Owner":"docker","IsDummy":false,"VolumePath":"\\\\?\\Volume{0ac9e503-477b-11e7-90ec-a85be1d5a902}","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\docker\\windowsfilter\\95f7eaf633c17a634a7135b0c3552241cf8226c37bc7d85f16519c07adc41e77","Layers":[{"ID":"563e3b37-dbce-54f9-b0ea-bb53efcde461","Path":"C:\\ProgramData\\docker\\windowsfilter\\56b921069583dc3ff635d16f3373715e18b4f58f2ad7ec0a3acecef30247a53e"},{"ID":"29033d89-929b-5577-ad11-c57004cb0d4a","Path":"C:\\ProgramData\\docker\\windowsfilter\\a7ed67f28f41a7d6bdead98bdbbcc5ddf8a891061d245e43becee332bf5f3194"}],"HostName":"95f7eaf633c1","MappedDirectories":[],"HvPartition":false,"EndpointList":["e9bf2cd2-01dd-4a93-ae24-6ae658f0b371"],"Servicing":false,"AllowUnqualifiedDNSQuery":true}.

### Information

Debug-ContainerHost gives me the following problem:
Specified Network Gateway IP for NAT network is assigned to Host vNIC 48ms
The gateway of default nat is 0.0.0.0

Should it be 172.19.160.0/20 or something like that?

docker works fine with a transparent network.

### Steps to reproduce the behavior

  1. Installed docker
  2. ...

**Comment by Tsukrov** [comment]
https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-networking#hns-requires-that-ipv6-is-enabled-on-container-host-machines

IPv6 must be enabled on the server.
👎 was not the most informative message.

**Comment by friism** [comment]
cc @dineshgovindasamy

**Comment by Tsukrov** [comment]
That was a very unobvious issue.

Debug-ContainerHost ignores the issue also.

Anyway, good luck keeping the proj running!
