### ISSUE TITLE
[wsl2] docker build and pull hang as normal user, work with sudo

### ISSUE THREAD

**Issue by bartmeuris** [docker/for-win#7972]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F2B1E505-1EEF-472B-835D-D6C3F51B4EC1/20200805140738

### Expected behavior

Pulling and building a docker image as a normal user from a WSL2 distro should work.

### Actual behavior

The docker command hangs completely when executing the following commands as the default user from a WSL2 shell:

* `docker build -t myimage:latest .`
* `docker pull ubuntu:20.04`

Pulling any image actually fails, this is just an example.

When I use `strace`, the line it hangs on is `futex(0x12a5568, FUTEX_WAIT_PRIVATE, 0, NULL` when pulling, and when building, it keeps looping on a `futex(0x558472c4cea8, FUTEX_WAIT_PRIVATE, 0, NULL) = 0` call.

After some testing, I figured out that, surprisingly, running these docker commands with elevated permissions using `sudo`, did work however, which was especially puzzling because these commands work perfectly without `sudo`:

* `docker ps`
* `docker images`
* `docker run --rm -ti --entrypoint /bin/bash ubuntu:18.04`

This ruled out permission problems with the docker socket, which I before had verified to be correct. Note that the `ubuntu:18.04` image was already present, but attempting to run non-existing images also fails.

### Information

  - Windows Version: 10 Professional
  - Docker Desktop Version: 2.3.4.0 (46980)
  - From WSL2 distro (tested both Ubuntu 18.04 and 20.04)
  - Using Docker WSL2 backend

### Steps to reproduce the behavior

* run `docker pull ubuntu:18.04` as a normal user from a WSL2 console.

**Comment by stephen-turner** [comment]
Thanks for the report. This is a Windows bug, see microsoft/WSL#5648.
