### ISSUE TITLE
Error fail run images windows 10

### ISSUE THREAD

**Issue by thallesdaniell** [docker/for-win#7977]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version: 2.3.4.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. start docker desktop
  2. run docker-compose up -d --build

**Comment by robertowm** [comment]
Similar issue here. After reset to factory defaults, I tested pulling a new image and it didn't work too. It may be related to Windows update, it was working before it.

- Windows Version: Build 20185.rs_prerelease.200731-1415

- Docker Desktop Version: 2.3.4.0

- Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

**Comment by thallesdaniell** [comment]
Running in windows 10. After uploading the version and activating the integration with WSL, it seems to have stabilized.

**Comment by thallesdaniell** [comment]
I modified the memory allocation and received another similar error

**Comment by stephen-turner** [comment]
@robertowm I suspect your issue is microsoft/WSL#5648. Please try again with the latest Insiders build, 20190.
