### ISSUE TITLE
Docker is not working on window 10 pro

### ISSUE THREAD

**Issue by amitjagtap21** [docker/for-win#7979]
Version: 2.3.0.4 (46911)
Channel: stable
Sha1: d4f5fcf98140180eeef00e02c1c8bb0ad69e35d3
Started on: 2020/08/06 09:55:53.532
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro 64 bit (8GM RAM)
Edition: Professional
Id: 1909
Build: 18363
BuildLabName: 18362.1.amd64fre.19h1_release.190318-1202
virtulization : enable

when i run command - docker ps gives me following error

error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

when i run docker run -d -p 80:80 docker/getting-started give me following error

docker: Error response from daemon: open \\.\pipe\docker_engine_linux: The system cannot find the file specified.
See 'docker run --help'

it will crash sometime
[a.txt](https://github.com/docker/for-win/files/5032802/a.txt)

**Comment by alexjbuck** [comment]
### Expected behavior
Able to run docker commands

### Actual behavior
```
PS C:\> docker ps
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

PS C:\> docker run -d -p 80:80 docker/getting-started
docker: error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/create: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
See 'docker run --help'.
```

### Information
Windows Version: Windows 10 Education
Docker Desktop Version: 2.3.0.4 (46911)
Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No
Diagnostic ID: 4E04F6CD-2713-4EB3-B903-A9F65ACB046C/20200817011152

### Steps to reproduce the behavior
Run any docker command, for example: 

> ```
> docker image ls
> docker ps
> docker run <imageName>
> ```
