### ISSUE TITLE
"dm.basesize" config change causes Docker engine to fail starting

### ISSUE THREAD

**Issue by klauern** [docker/for-win#798]
### Expected behavior

When adding the `"dm.basesize=50G"` to the configuration file, I expect to be able to increase the size of the image size capability. 

### Actual behavior

It fails to start entirely.

```
Error response from daemon: Bad response from Docker engine

   at Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.

    AFF5F204-9E7F-4E34-843A-499460C2F473/2017-06-06_16-21-42

Config file:

```json
{
  "registry-mirrors": [],
  "insecure-registries": [],
  "storage-opts": [
    "dm.basesize=50G"
  ],
  "debug": true,
  "experimental": true
}
```

### Steps to reproduce the behavior

 Change the Daemon to use "Advanced" settings, and add `"dm.basesize=50G"` to the configuration.

**Comment by jasonbivins** [comment]
Hi @klauern could you try removing the s after storage-opt like this?
"storage-opt": [
    "dm.basesize=50G"
  ],

**Comment by klauern** [comment]
Ah, I didn't see that.  I did change it, and it doesn't crash, but I don't think the option is actually working.  I still get this error trying to build an Oracle-based image:

```
C:\Users\klauer\dev\oracle-docker\OracleDatabase\dockerfiles\12.2.0.1 [master ≡ +4 ~3 -0 !]
λ  docker build -f .\Dockerfile.ee -t oracle/database:12.2.0.1-ee .
Sending build context to Docker daemon  3.454GB
Step 1/16 : FROM oraclelinux:7-slim
 ---> f005b5220b05
Step 2/16 : MAINTAINER Gerald Venzl <gerald.venzl@oracle.com>
 ---> Using cache
 ---> 0509f173d17f
Step 3/16 : ENV ORACLE_BASE /opt/oracle ORACLE_HOME /opt/oracle/product/12.2.0.1/dbhome_1 INSTALL_FILE_1 "linuxx64_12201_database.zip" INSTALL_RSP "db_inst.rsp" CONFIG_RSP "dbca.rsp.tmpl" PWD_FILE "setPassword.sh" PERL_INSTALL_FILE "installPerl.sh" RUN_FILE "runOracle.sh" START_FILE "startDB.sh" CREATE_DB_FILE "createDB.sh" SETUP_LINUX_FILE "setupLinuxEnv.sh" CHECK_SPACE_FILE "checkSpace.sh" CHECK_DB_FILE "checkDBStatus.sh" INSTALL_DB_BINARIES_FILE "installDBBinaries.sh"
 ---> Using cache
 ---> 01538dae1864
Step 4/16 : ENV INSTALL_DIR $ORACLE_BASE/install PATH $ORACLE_HOME/bin:$ORACLE_HOME/OPatch/:/usr/sbin:$PATH LD_LIBRARY_PATH $ORACLE_HOME/lib:/usr/lib CLASSPATH $ORACLE_HOME/jlib:$ORACLE_HOME/rdbms/jlib
 ---> Using cache
 ---> 87630258dd3a
Step 5/16 : COPY $INSTALL_FILE_1 $INSTALL_RSP $PERL_INSTALL_FILE $SETUP_LINUX_FILE $CHECK_SPACE_FILE $INSTALL_DB_BINARIES_FILE $INSTALL_DIR/
 ---> Using cache
 ---> 63c86d72cb14
Step 6/16 : COPY $RUN_FILE $START_FILE $CREATE_DB_FILE $CONFIG_RSP $PWD_FILE $CHECK_DB_FILE $ORACLE_BASE/
 ---> Using cache
 ---> 277cd4b02515
Step 7/16 : RUN chmod ug+x $INSTALL_DIR/*.sh &&     sync &&     $INSTALL_DIR/$CHECK_SPACE_FILE &&     $INSTALL_DIR/$SETUP_LINUX_FILE
 ---> Running in a8bd47dc513b
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
checkSpace.sh: ERROR - There is not enough space available in the docker container.
checkSpace.sh: The container needs at least 15 GB available.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
The command '/bin/sh -c chmod ug+x $INSTALL_DIR/*.sh &&     sync &&     $INSTALL_DIR/$CHECK_SPACE_FILE &&     $INSTALL_DIR/$SETUP_LINUX_FILE' returned a non-zero code: 1
```

**Comment by klauern** [comment]
Also, I looked and it seems that Windows Docker uses `overlay2` for the storage driver, so I attempted to change to `devicemapper` so this option would do something.  Unfortunately, it generated an error:

AFF5F204-9E7F-4E34-843A-499460C2F473/2017-06-07_17-09-04

with this file:

```json
{
  "registry-mirrors": [],
  "insecure-registries": [],
  "storage-driver": "devicemapper",
  "storage-opt": [
    "dm.basesize=50G"
  ],
  "debug": true,
  "experimental": true
}
```

**Comment by klauern** [comment]
Should I file the last comment as a separate issue?  I feel like I'm discovering that `devicemapper` is not an officially supported driver in Windows, which makes the `dm.basesize` option moot.

**Comment by jasonbivins** [comment]
hi @klauern 

Can you please submit that last comment as a seperate issue along with a diagnostic ID  ?

**Comment by jasonbivins** [comment]
@klauern 
 
I wasn't able to reproduce your first issue on the latest build, but I can reproduce the error with the Devicemapper commands added.  I'll let you know what I find out.

**Comment by klauern** [comment]
I'm running on Windows 10:

```ps1
C:\Users\klauer
λ  docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 42
Server Version: 17.06.0-ce-rc2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 3addd840653146c90a254301d6c3a663c7fd6429
runc version: 992a5be178a62e026f4069f443c6164912adbf09
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.30-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: moby
ID: NJBW:I3YI:X4UV:AMNJ:PVV6:UF5Y:DFVK:OT5O:H3FR:MU5U:IJXA:7W25
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 30
 Goroutines: 52
 System Time: 2017-06-14T01:31:10.7518223Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by klauern** [comment]
I was able to get things working with what I think is an undocumented flag (that, or I'm just having a hard time finding it):

```json
{
  "registry-mirrors": [],
  "insecure-registries": [],
  "debug": true,
  "storage-opt": [
    "size=50G"
  ],
  "experimental": true
}
```

Note, this isn't using DeviceMapper, so the various `dm-*` flags won't apply.  However, I found this setting in a forum post somewhere (can't find it atm) instead of on the storage docs.

**Comment by egaga** [comment]
<img width="310" alt="screen shot 2017-10-09 at 13 05 34" src="https://user-images.githubusercontent.com/138295/31333391-95dc288c-acf2-11e7-9d44-f7589e247f54.png">

The Docker for Mac application prevents me to use `storage-opt` json field. Instead `storage-opts` is accepted but then the Docker does not start and get similar error message with the following:

```
$ docker info
Error response from daemon: Bad response from Docker engine
```

**Comment by jeremycornett** [comment]
I am seeing this as well with docker-ce latest.

**Comment by StWitte** [comment]
Same problem for me. I cannot find a way to configure the increased default size. I have the same error as egaga that the docker settings dialog says: "storage-opt" Invalid option.

I'm on Docker Community Edition on Windows 10 pro Version 18.03.1-ce-win65 (17513) Channel: stable 93354b3

There is also the 'storage_opt' option in compose v2 but not in v3. Didn't get this to work either.

**Comment by robertoandrade** [comment]
Apprently this is document as an option for the `windowsfilter` storage driver: https://docs.docker.com/edge/engine/reference/commandline/dockerd/#windowsfilter-options
