### ISSUE TITLE
Dashboard does not show running containers 

### ISSUE THREAD

**Issue by jkears** [docker/for-win#7989]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version: Version	10.0.18363 Build 18363

  - Docker Desktop Version: 19.03.12, build 48a66213fe
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: virtualized

### Steps to reproduce the behavior

  1. Deployed Docker Compose
  2. Services start up
  3. Right-Click Docker View Dashboard

 
![image](https://user-images.githubusercontent.com/1290937/89578833-caaa9d00-d800-11ea-8792-dd8683a2ca20.png)

Run docker ps and can see all running services... and am able to access them 

![image](https://user-images.githubusercontent.com/1290937/89578888-e01fc700-d800-11ea-9800-888dbcef9f3a.png)

**Comment by stephen-turner** [comment]
Hmmm, I'm trying to think why that could be. Are these containers running in a different docker context? The dashboard is not context aware at the moment.

Also Kubernetes system containers are not shown.
