### ISSUE TITLE
Docker hangs on build or pull

### ISSUE THREAD

**Issue by fabienheureux** [docker/for-win#7990]
- [x] I have tried with the latest version of my channel (Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: EAD47D03-1A5F-4127-91DB-89AD8A7C42CC/20200807082237

### Expected behavior
Be able to pull images from docker hub OR build local docker images

### Actual behavior
The docker cli hangs on the first line of logs...and nothing happens, even after more than an hour. 

### Information
  - Windows Version: 2004, build 20185.1000
  - Docker Desktop Version: 2.3.4.0 (46980), edge
  - I am using WSL 2

### Steps to reproduce the behavior
Clean docker with no running containers 
1. `docker system prune`
Then run a non-locally existing remote container 
2. `docker run hello-world`
3. nothing happens...docker cli is stuck on the first line of logs, saying it's pulling the image. 

### Workaround
I found a workaround, that is to remove `~/.docker/config.json` file, and just re-run the command. 
But once in a while (like, after every reboot), the problem is happening again.

**Comment by ArthurJam** [comment]
Diagnostics id : A7C77B7B-5902-4102-883F-48D39E442649/20200807095834

I have a similar behaviour.
When I execute (in a wsl shell) a docker pull / docker login or docker logout : i dont have any return.
If I try it on WindowsPowershell, the cmd succeded.

**Comment by fabienheureux** [comment]
> 
> 
> Diagnostics id : A7C77B7B-5902-4102-883F-48D39E442649/20200807095834
> 
> I have a similar behaviour.
> When I execute (in a wsl shell) a docker pull / docker login or docker logout : i dont have any return.
> If I try it on WindowsPowershell, the cmd succeded.

Did you try removing `~/.docker/config.json` file ?

**Comment by stephen-turner** [comment]
This is a Windows bug in the latest Insider builds, see microsoft/WSL#5648.

**Comment by ArthurJam** [comment]
Yes, i try to remove config.json and its fixes it for now.
I will see at the next reboot if the problem is fixed.
