### ISSUE TITLE
Docker desktop missing "Resources -> Memory" settings for linux containers on Windows Home (WSL2)

### ISSUE THREAD

**Issue by jobesu14** [docker/for-win#7991]
Hello,

Docker Desktop on Windows Home with WSL2 backend doesn't show the "Resources" settings.
In my case, I need to allow Docker to allocate 8GB of Memory for the container.

Why this option is not available on Docker Desktop Windows Home ? Is it because it is not relevant (WSL2 will take care of dynamically allocating the required memory)?
My tests seems to indicate that it is not the case as the task inside the container crashes because of "Not enough memory".

Is there a way to set the max memory allocation somewhere else than from the Docker Desktop settings UI?

Thanks

**Comment by stephen-turner** [comment]
You're correct, WSL 2 manages the memory. See the bottom of our documentation at https://docs.docker.com/docker-for-windows/wsl/ for a link to how to configure it.
