### ISSUE TITLE
Docker Desktop fails run Linux Containers

### ISSUE THREAD

**Issue by yashmatkov** [docker/for-win#7996]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 173C613D-8CFE-4772-95F2-A96DC0E98AED/20200718122318

### Expected behavior
Docker runs Linux Containers
### Actual behavior
Docker runs Windows Containers but fails to run Linux containers. 
When I am trying to switch to Linux containers, I am getting the following errors:
![Docker](https://user-images.githubusercontent.com/33263995/89671753-8925fa80-d8b1-11ea-8c7f-20bdda3a402f.png)
![Docker1](https://user-images.githubusercontent.com/33263995/89671846-ad81d700-d8b1-11ea-8a3f-66f7db711196.png)

I tried to choose "Reset to factory defaults" but nothing happens.

I installed WSL but getting the following error there:
![mkdocs](https://user-images.githubusercontent.com/33263995/89672817-4a913f80-d8b3-11ea-85f2-ead87e1b5e01.png)
I cannot install WSL2 due to my Windows version.

### Information

  - Windows Version: 1909 (OS Build 18363.900)
  - Docker Desktop Version: 2.3.0.4(46911) - I tried older versions, same issue
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by kencochrane** [comment]
@satanyasha I noticed this question wasn't answered.  _"Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:"_ You are using this on a windows laptop, right?

**Comment by kencochrane** [comment]
@nebuk89 Here is the issue I was talking with you about earlier today.

**Comment by satanyasha** [comment]
@kencochrane Yes, let me add this information.

**Comment by yashmatkov** [comment]
The issue was resolved by running the following command in Powershell (as admin): 
Set-ProcessMitigation -Name VMCompute.exe -disable CFG
