### ISSUE TITLE
Error Starting a Dev-Mode Container - Getting started

### ISSUE THREAD

**Issue by kayzweller** [docker/for-win#7998]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 8D896C8E-C202-4933-B37E-28EF1E426B5D/20200808021713

### Expected behavior
Complete the getting started tutorial, step 6 (Starting a Dev-Mode Container).

### Actual behavior
After run this command `**docker run -dp 3000:3000 -w /app -v $(pwd):/app node:12-alpine sh -c "yarn install && yarn run dev"**` try using both Cmd and Powershell, I got this error message :
![_problem](https://user-images.githubusercontent.com/33682907/89700742-df02ad00-d95a-11ea-95b2-5c9fc3c2eccf.png)

### Information

  - Windows Version: **Windows 10 version 1909 (Build OS 18363.959)**
  - Docker Desktop Version: **2.3.0.4 (46911) Stable**
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: **_No_**

### Steps to reproduce the behavior

Here the docker file:
![_docker](https://user-images.githubusercontent.com/33682907/89700800-7bc54a80-d95b-11ea-99d4-a92f79ae2e5c.png)

  1. I open my cmd to follow along with the tutorial
  2. I run command **`docker run -dp 3000:3000 -w /app -v $(pwd):/app node:12-alpine sh -c "yarn install && yarn run dev"`**
  3. It's get me this error result:
```
docker: Error response from daemon: create $(pwd): "$(pwd)" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
```
  4. I try open Powershell, and it's give me this result:
```
docker: invalid reference format.
See 'docker run --help'.
```
  5. Before I run this command, I already make sure that `getting-started` is not running, by checking it using command: `docker ps`

**Comment by kayzweller** [comment]
I inspect the command that I input I forget to add " in `... "$(pwd):/app"`
I try to run this command again:
`docker run -dp 3000:3000 -w /app -v "$(pwd):/app" node:12-alpine sh -c "yarn install && yarn run dev"`
but the problem still persist, and resulting same Error response as above.

**Comment by kayzweller** [comment]
I got the solution, I use this command:
`docker run -dp 3000:3000 -w /app -v "${pwd}:/app" node:12-alpine sh -c "yarn install && yarn run dev"`

**Comment by kayzweller** [comment]
I find solution to this, I run this command:
`docker run -dp 3000:3000 -w /app -v "${db}:/app" node:12-alpine sh -c "yarn install && yarn run dev"`

I still don't know why, but this code cannot run:
`docker run -dp 3000:3000 -w /app -v "${pwd}:/app" node:12-alpine sh -c "yarn install && yarn run dev"`

**Comment by kayzweller** [comment]
when running this command:
`docker run -dp 3000:3000 -w /app -v "${pwd}:/app" node:12-alpine sh -c "yarn install && yarn run dev"`

it's resulting this error:
![__error 2](https://user-images.githubusercontent.com/33682907/89703701-475f8780-d977-11ea-90d8-c8e98e53f77f.png)

**Comment by Boubari97** [comment]
> I find another problem to this, I run this command:
> `docker run -dp 3000:3000 -w /app -v "${db}:/app" node:12-alpine sh -c "yarn install && yarn run dev"`
> it resulting this:
> ![__error 2](https://user-images.githubusercontent.com/33682907/89703621-87723a80-d976-11ea-86b7-51896bb90e6c.png)
> but the container always force stopped, and I doesn't have enough time to call the log using `docker ps` and the `docker logs -f <container-id>`
> 
> then, when I tried running this command:
> `docker run -dp 3000:3000 -w /app -v "${pwd}:/app" node:12-alpine sh -c "yarn install && yarn run dev"`
> it's resulting this error:
> ![__error 2](https://user-images.githubusercontent.com/33682907/89703701-475f8780-d977-11ea-90d8-c8e98e53f77f.png)

Try to change **$(pwd)** to **%cd%**
For exapmle: **docker run -dp 3000:3000 -w /app -v "%cd%:/app" node:12-alpine sh -c "yarn install && yarn run dev"**
It helps me.
