### ISSUE TITLE
Problem with docker compose an firewall\proxy

### ISSUE THREAD

**Issue by randomxxxx** [docker/for-win#80]
Hi all,

We are trying to get docker and docker compose working in our corporate environment. We have already made changes to allow images to be pulled and certain keyserver sites to be accessible. The issue we are having now is while Docker is building the image trying to access the internet - our network guy said that "my machine is still attempting to make the connection through the firewall and not the proxy". I have added our proxy information to Docker for Windows (which is what allowed images to be pulled).

Below is a capture for a docker-compose run. It fails trying to connect to github. Any help would be appreciated!

D:\Projects\docker\enterprise.docker-compose.logging>docker-compose -p SCELK -f docker-compose-full.yml up -d
Building elasticsearch
Step 1 : FROM java:8-jre
---> 042c17968c65
Step 2 : ENV HTTP_PROXY WSPROXY.STATIONCASINOS.NET:8080
---> Using cache
---> 05f3c5994436
Step 3 : ENV HTTPS_PROXY WSPROXY.STATIONCASINOS.NET:8080
---> Using cache
---> 5115ff55f41b
Step 4 : ENV GOSU_VERSION 1.7
---> Using cache
---> 8b425faf7fc3
Step 5 : RUN set -x && wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture)" && wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture).asc" && export GNUPGHOME="$(mktemp -d)" && gpg --keyserver hkp://hkps.pool.sks-keyservers.net:80 --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 && gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu && rm -r "$GNUPGHOME" /usr/local/bin/gosu.asc && chmod +x /usr/local/bin/gosu && gosu nobody true
---> Running in f4c0dc3b5d8d
+ dpkg --print-architecture
+ wget -O /usr/local/bin/gosu https://github.com/tianon/gosu/releases/download/1.7/gosu-amd64
--2016-09-13 20:04:23-- https://github.com/tianon/gosu/releases/download/1.7/gosu-amd64
Resolving github.com (github.com)... 192.30.253.112
Connecting to github.com (github.com)|192.30.253.112|:443... failed: Connection refused.
ERROR: Service 'elasticsearch' failed to build: The command '/bin/sh -c set -x && wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture)" && wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture).asc" && export GNUPGHOME="$(mktemp -d)" && gpg --keyserver hkp://hkps.pool.sks-keyservers.net:80 --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 && gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu && rm -r "$GNUPGHOME" /usr/local/bin/gosu.asc && chmod +x /usr/local/bin/gosu && gosu nobody true' returned a non-zero code: 4

D:\Projects\docker\enterprise.docker-compose.logging>

Also I ran a separate docker build . and it fails on the same spot (not unexpectedly of course). I also uploaded a diagnostic: D72C48A6-52BE-4CB7-9BB9-BE6F019495D2/2016-09-13_17-19-31.

**Comment by dgageot** [comment]
@randomxxxx Did you get the chance to test a more recent version? Given this is an old issue not reported by anyone else, I am inclined to close this issue in a couple of days unless there's more feedback. Thanks a lot for your help!
