### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by llmsjraj** [docker/for-win#8002]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker should be installed.
### Actual behavior
![image](https://user-images.githubusercontent.com/22942645/89706917-9ad9d180-d987-11ea-8333-f37231dd4d53.png)

![image](https://user-images.githubusercontent.com/22942645/89707179-70891380-d989-11ea-8774-36bdf6cc52b1.png)

### Information

  - Windows Version: Windows 10 Pro insider Preview (Build 20185.rs_prerealese200731-1415)
  - Docker Desktop Version: 2.3.0.4
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

Installing Docker 2.3.0.4 in Windows 10 Pro insider Preview (Build 20185.rs_prerealese200731-1415)  and getting the above error. Additionally, I have wsl2 enabled and it is working fine. 

Docker 2.3.0.2 was working fine but I have updated my windows version and I got the docker update notification. I have proceeded with the docker update and it failed.

Then, I have restarted the system and the docker was not there in my system.

Then, I have tried to install the docker versions 2.3.0.4, 2.3.0.3, and 2.3.0.2 but getting the same error.

These are the attached logs
[Docker_logs.zip](https://github.com/docker/for-win/files/5045031/Docker_logs.zip)

There is any workaround to get this installed.

**Comment by stephen-turner** [comment]
This is a Windows bug in the latest Insider builds, see microsoft/WSL#5648
