### ISSUE TITLE
Image2Docker Dockerfile build fails 

### ISSUE THREAD

**Issue by igorguga** [docker/for-win#801]
### Expected behavior
Build the image from a Dockerfile generated by Image2Docker from a MVC .net 4.5 application running on a Windows 2012 R2.

### Actual behavior
Build fails in the step where windows features have been enabled.

### Information

**This is the docker file:**
```
# escape=`
FROM microsoft/aspnet:3.5-windowsservercore-10.0.14393.1066
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# disable DNS cache so container addresses always fetched from Docker
RUN Set-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters' -Name ServerPriorityTimeLimit -Value 0 -Type DWord

RUN Remove-Website 'Default Web Site';

RUN Enable-WindowsOptionalFeature -Online -FeatureName IIS-ApplicationDevelopment,IIS-ASPNET45,IIS-BasicAuthentication,IIS-CertProvider,IIS-ClientCertificateMappingAuthentication,IIS-CommonHttpFeatures,IIS-CustomLogging,IIS-DefaultDocument,IIS-DigestAuthentication,IIS-DirectoryBrowsing,IIS-FTPExtensibility,IIS-FTPServer,IIS-FTPSvc,IIS-HealthAndDiagnostics,IIS-HostableWebCore,IIS-HttpCompressionDynamic,IIS-HttpCompressionStatic,IIS-HttpErrors,IIS-HttpLogging,IIS-HttpRedirect,IIS-HttpTracing,IIS-IISCertificateMappingAuthentication,IIS-IPSecurity,IIS-ISAPIExtensions,IIS-ISAPIFilter,IIS-LegacySnapIn,IIS-LoggingLibraries,IIS-Metabase,IIS-NetFxExtensibility,IIS-NetFxExtensibility45,IIS-ODBCLogging,IIS-Performance,IIS-RequestFiltering,IIS-RequestMonitor,IIS-Security,IIS-StaticContent,IIS-URLAuthorization,IIS-WebServer,IIS-WebServerRole,IIS-WebSockets,IIS-WindowsAuthentication,IIS-WMICompatibility,NetFx4Extended-ASPNET45

# Set up website: ControleFinanceiro-Dev
RUN New-Item -Path 'C:\inetpub\ControleFinanceiro-Dev' -Type Directory -Force; 

RUN New-Website -Name 'ControleFinanceiro-Dev' -PhysicalPath 'C:\inetpub\ControleFinanceiro-Dev' -Port 1010 -Force; 

EXPOSE 1010

COPY ["ControleFinanceiro-Dev", "/inetpub/ControleFinanceiro-Dev"]

RUN $path='C:\inetpub\ControleFinanceiro-Dev'; `
    $acl = Get-Acl $path; `
    $newOwner = [System.Security.Principal.NTAccount]('BUILTIN\IIS_IUSRS'); `
    $acl.SetOwner($newOwner); `
    dir -r $path | Set-Acl -aclobject  $acl

```

**The build fails in the command:** 
`RUN Enable-WindowsOptionalFeature -Online -FeatureName IIS-ApplicationDevelopment,IIS-ASPNET45,IIS-BasicAuthentication,IIS-CertProvider,IIS-ClientCertificateMappingAuthentication,IIS-CommonHttpFeatures,IIS-CustomLogging,IIS-DefaultDocument,IIS-DigestAuthentication,IIS-DirectoryBrowsing,IIS-FTPExtensibility,IIS-FTPServer,IIS-FTPSvc,IIS-HealthAndDiagnostics,IIS-HostableWebCore,IIS-HttpCompressionDynamic,IIS-HttpCompressionStatic,IIS-HttpErrors,IIS-HttpLogging,IIS-HttpRedirect,IIS-HttpTracing,IIS-IISCertificateMappingAuthentication,IIS-IPSecurity,IIS-ISAPIExtensions,IIS-ISAPIFilter,IIS-LegacySnapIn,IIS-LoggingLibraries,IIS-Metabase,IIS-NetFxExtensibility,IIS-NetFxExtensibility45,IIS-ODBCLogging,IIS-Performance,IIS-RequestFiltering,IIS-RequestMonitor,IIS-Security,IIS-StaticContent,IIS-URLAuthorization,IIS-WebServer,IIS-WebServerRole,IIS-WebSockets,IIS-WindowsAuthentication,IIS-WMICompatibility,NetFx4Extended-ASPNET45`

The only information outputed is:  _returned a non-zero code: 1_

I ran the command:
`docker build -t i2d2/controlefinanceiro-dev .`

I'm using Docker for Windows:
`Docker version 17.03.1-ce, build c6d412e`

In a Windows 10 machine:
`version 1607 (OS Build 14393.693)`

**Comment by friism** [comment]
cc @sixeyed
