### ISSUE TITLE
Docker pull <image> does not work

### ISSUE THREAD

**Issue by mdekoster** [docker/for-win#8019]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A4F0C4D9-1FC7-422B-B4F8-782DE8295A4D/20200810131927

### Expected behavior
On WSL2

```
> docker pull alpine
Using default tag: latest

```
Expecting to start downloading the image layers.

### Actual behavior

Nothing happens. The client seems to hang. 

### Information

  - Windows Version: 
     Edition         Windows 10 Pro Insider Preview
     Version        2004
     Installed on ‎9-‎8-‎2020 
     OS build      20185.1000
     Experience  Windows Feature Experience Pack 120.19801.0.0

  - Docker Desktop Version:
     2.3.0.4 (46911)

  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
This is a bug in Windows is the latest Insiders builds, see microsoft/WSL#5648.
