### ISSUE TITLE
Insecure-registry settings not recognized when using Windows Docker Daemon "...server gave HTTP response to HTTPS client"

### ISSUE THREAD

**Issue by daileyo** [docker/for-win#802]
### Expected behavior
When using Windows Containers, private registries, and the corresponding insecure-registry settings, it seems the daemon should use HTTP rather than HTTPS.

### Actual behavior
It seems that the Windows Daemon is still trying to authenticate using HTTPS:

```
docker login <server>
Error response from daemon: Get https://<server>/v2/: http: server gave HTTP response to HTTPS client
```
This only seems to happen when using the Windows Containers.  When using Linux Containers, the insecure registry settings seem to work as expected.

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
```
2EDFC3D1-A096-4398-8124-9A3AD4C2F254/2017-06-07_17-51-11
```

  - a reproducible case if this is a bug, Dockerfiles FTW
```
not applicable
```
  - page URL if this is a docs issue or the name of a man page
```
not applicable
```
  - host distribution and version (Windows version, build number, etc)
Windows 10 Pro Build 15063.rs2_release.170317-1834
  - Docker version informatoin
```
$ docker version
Client:
 Version:      17.05.0-ce-rc1
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 20:55:05 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.05.0-ce-rc1
 API version:  1.29 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 20:55:05 2017
 OS/Arch:      windows/amd64
 Experimental: fals
```
### Steps to reproduce the behavior

  1. From Docker right-click context menu, Choose "**Switch to Linux Containers**", if it is not already selected.
  2. From Docker right-click context menu, select "**Settings**"
  3. Click "Daemon"
  4. Under "**Insecure registries**", enter a private registry that can be connected to. (**NOTE:**  _The purpose of these first few steps is to validate that the private registry is accessible._)  I will use the name **_artifactory_** to represent the private registry name.
  5. Click "**Apply**"
  6. Once docker has restarted, open a command console and login to the insecure registry.

![image](https://user-images.githubusercontent.com/14967070/27232713-f049135c-526b-11e7-9466-c1edb4b9d024.png)

**NOTE: **  server name and ports have been changed, however, the above example is the configuration I use in these steps. 
```
$docker login artifactory
Username:<username>
Password:<password>
Login Succeeded
$
```
  7.  Close the Settings window.
  8.  From Docker right-click context menu, select "**Switch to Windows Containers**."
  9.  From Docker right-click context menu, select "**Settings**."
  10. Click "Daemon"
  11.  Under "**Insecure registries**, enter a private registry that can be connected to.  (**NOTE:**  _Use the same one that was previously validated in steps 1 through 6._)  **_artifactory_** in this example.

![image](https://user-images.githubusercontent.com/14967070/27233050-0830d314-526d-11e7-965b-1a45b70c3f00.png)

  12.  Click "**Apply**."
  13.  Once Docker has restarted, go to the command console (or open new one if the previous one was closed) and login to the insecure registry.
```
$docker login artifactory
Username (<previous one optionally defaulted>):
Password:<password>
Error response from daemon: Get https://artifactory/v2/: http: server gave HTTP response to HTTPS client
$
```

 ## Other information
  - Artifactory (v5.1.3) is being used as the registry in my specific case.  
  - Anonymous access is enabled for the repository.  
  - Pull requests also fail with the same error, but again, only when using Windows Daemon.
  - The same issue occurs when using Powershell to try and connect to the insecure private registry.
   
settings.json file included below.  
[settings-using-running-linux-containers.json.txt](https://github.com/docker/for-win/files/1081283/settings-using-running-linux-containers.json.txt)
[settings.json-using-windows-containers.json.txt](https://github.com/docker/for-win/files/1081284/settings.json-using-windows-containers.json.txt)

The specific areas that I edited before attaching were:
  - subnet
  - servername/port information

**Comment by jasonbivins** [comment]
Hi @daileyo   Can you  post the contents of your config file ? Cover or replace any private data or repos please.

![image](https://user-images.githubusercontent.com/28021664/27208077-7aaaeda0-5211-11e7-9334-cdaa6bef3720.png)

**Comment by daileyo** [comment]
Thanks for the reply @jasonbivins.  I have updated my original post with screen captures as well as the settings.json file.

**Comment by lifeRockss** [comment]
Is there a solution for this? I am facing same issue with  17.09.1-ce on mac.
Have added the insecure entires from UI Docker-->Preferences-->Daemon->Insecure registries
and restarted docker.

but docker info show empty value for Insecure Registries:

**Comment by jasonbivins** [comment]
@lifeRockss 
Can you try to add the settings manually to the daemon.json file to see if the changes stick?
https://docs.docker.com/registry/insecure/

**Comment by jasonbivins** [comment]
@daileyo
Does exposing the Daemon without TLS help?

![image](https://user-images.githubusercontent.com/28021664/34140100-6df24eec-e446-11e7-8f07-6a8e8bee04fd.png)

**Comment by lifeRockss** [comment]
@jasonbivins thanks for your reply but no luck. The entry was already there in ~/Library/Containers/com.docker.docker/Data/database/com.docker.driver.amd64-linux/etc/docker/daemon.json 
as 

`{
  "debug" : true,
  "insecure-registries" : ["nexus.bla.bla.net:80"],
  "experimental" : true
}`

but docker info give
Name: moby
ID: REML:UV22:NZDH:SGPJ:STRK:OE2Z:FFNI:MBCV:YD4T:AQ5U:75M7:X552
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 29
 System Time: 2017-12-19T09:03:19.766203454Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
Live Restore Enabled: true

tried with Live Restore Enabled: false too

**Comment by lifeRockss** [comment]
well strange enough, after playing a bit with it and trying to add few more properties, it worked...strange bit is after removing all those values it still works :-)
the last prop I remember adding was `"disable-legacy-registry": true`
Now its back to `{ "debug" : true, "insecure-registries" : ["nexus.bla.bla.net:80"], "experimental" : true }` and still works. may be few restarts did the work.

**Comment by daileyo** [comment]
In my case, it was a problem specific to the Edge release.  I haven't been able to reproduce the issue in CE edition.  I'll see if the problem still persists in either.
