### ISSUE TITLE
Error response from daemon: open \\.\pipe\docker_engine_linux: The system cannot find the file specified

### ISSUE THREAD

**Issue by Daggy1234** [docker/for-win#8028]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C2A98F22-D776-49B5-BF5C-5F2E5D48909F/20200811112537

### Expected behaviour

So docker was running normally however after I restarted my computer docker should have started and run normally

### Actual behaviour

`docker: Error response from daemon: open \\.\pipe\docker_engine_linux: The system cannot find the file specified.`

No matter what command I run I get this error

### Information

  - Windows Version: Win10 home 2004
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Virtualized windows locally

- The completely new problem never happened before
- I do not know whether it is reproducible

### Steps to reproduce the behaviour

Nothing just restarted despite not even using docker previously.

**Comment by Daggy1234** [comment]
![image](https://user-images.githubusercontent.com/60603110/89892868-f65cc700-dbf4-11ea-955d-75b777428a74.png)

**Comment by mh9** [comment]
I also am also running windows 10 home 20.04. When I ran in PowerShell the command:
 `docker version `
I got exactly the same error you report. I upgraded PowerShell from https://github.com/PowerShell/PowerShell/releases
using  **PowerShell-7.0.3-win-x64.msi**
Then the command `docker version` worked as expected.

**Comment by Daggy1234** [comment]
Oh that worked not to mention even a simple reinstall of docker fornwin did it.
