### ISSUE TITLE
Files and sockets from /mnt/wsl/docker-desktop disappear

### ISSUE THREAD

**Issue by mbirtwell** [docker/for-win#8032]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 904FDB89-83C0-4F44-80D1-389C02E25580/20200811164232

### Actual behavior
When using docker desktop sometimes I get errors like:
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 227, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python2.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("dial unix /mnt/wsl/docker-desktop/shared-sockets/guest-services/docker.sock: connect: no such file or directory")

When I do so I find that the directories:
/mnt/wsl/docker-desktop/shared-sockets/guest-services/
/mnt/wsl/docker-desktop/shared-sockets/host-services/
/mnt/wsl/docker-desktop/cli-tools/
Have all become empty. Which prevents me from using Docker Desktop any more from WSL2. Restarting Docker Desktop restores them and I can continue for a bit. I don't know what I do that triggers this but it seems to be quite common. 

When those directories are empty my WSL2 distro is missing all the docker-desktop related mounts.

Restarting Docker Desktop fixes it.

I had a look inside wsl -d docker-desktop and when it's broken all of the similar mounts disappear from here also.

### Information

  - Windows Version: 2004 19041.488
  - Docker Desktop Version: 2.3.0.4
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
@simonferquel Is this the same cause as #7836?

**Comment by mbirtwell** [comment]
I tried running the bash code from #7836 and that didn't reproduce it for me although I see a lot of the same symptoms. And I had started to suspect that the trigger was when my build scripts stop or remove containers, which seems consistent with what's being discussed there. However trying to isolate those operation hasn't allowed me to reproduce it yet.

**Comment by stephen-turner** [comment]
@mbirtwell It happens if you mount /mnt/wsl/ or one of its ancestors with -v, and then delete the container. Does that correspond to your case?

**Comment by mbirtwell** [comment]
Yes, there's a build script mounting / in to a container. Presumably this is to do with umount event propagation and could be worked around with the appropriate application of mount --make-rprivate. We've got some of that in the code already if I get a chance I might see if I can apply it in this case.

**Comment by stephen-turner** [comment]
OK, thanks. In that case it's definitely the same issue as #7836. I'll close this issue as a dupe.
