### ISSUE TITLE
Failed to start Docker

### ISSUE THREAD

**Issue by yalishizhude** [docker/for-win#804]
### Information

  - Diagnostic ID: 797C29C3-A20F-4DA2-8FA5-FEE36CB18913/2017-06-08_22-24-48
![image](https://user-images.githubusercontent.com/3870098/26934858-17076bee-4c9d-11e7-99bd-83397d6bd9a3.png)

  - host distribution and version Windows 10

### Steps to reproduce the behavior

  1. Click the link "Docker for Windows"
  2. Start failed

**Comment by jasonbivins** [comment]
hi @yalishizhude   Can you please provide a screenshot of the error you see when it fails?  

What version of Docker for Windows are you running?

**Comment by yalishizhude** [comment]
![image](https://user-images.githubusercontent.com/3870098/26981775-bff197e0-4d68-11e7-9729-eb2f866f7088.png)
I clicked OK..
![image](https://user-images.githubusercontent.com/3870098/26981822-e54544d8-4d68-11e7-8cbf-04db014dfc3f.png)
![image](https://user-images.githubusercontent.com/3870098/26981852-f6688b76-4d68-11e7-8e47-93dedbe54a75.png)

**Comment by yalishizhude** [comment]
I followed the instructions, but it didn't work

**Comment by jasonbivins** [comment]
H @yalishizhude 

Were you able to manually enable hyper-v , or did you get an error there too?

**Comment by yalishizhude** [comment]
That's the problem~
I enabled hyper-v service,but it stopped when I reboot.

**Comment by yalishizhude** [comment]
I'm afraid that I have to  reinstall system...

**Comment by jasonbivins** [comment]
Hi @yalishizhude 

It does sound like Hyper-v isn't working right.  Please let me know if you still have troubles after you are able to get it enabled.

**Comment by yalishizhude** [comment]
I can't enable hyper-v
so I have to reinstall windows10....
The docker works now~
I remember I stop hyper-v service in order to install virtual-box
I can't start the service after that...

**Comment by wikrie** [comment]
to start stop hyper V you can use the following command into a admin box

bcdedit /set hypervisorlaunchtype off => after reboot you can use VirtualBox

bcdedit /set hypervisorlaunchtype auto => after reboot you can use Hyper-V
