### ISSUE TITLE
Unable to create listening socket in WSL2 after Docker Desktop starts automatically

### ISSUE THREAD

**Issue by chewi** [docker/for-win#8041]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: C3504DD0-9E2A-430D-A975-FBED287A4EAB/20200812094545

### Expected behavior
When starting Docker Desktop automatically, I should be able to create other listening sockets within WSL2.

### Actual behavior
Attempting to create any listening socket in WSL2 after Docker Desktop has started automatically almost always results in the socket not actually working. It doesn't matter what program it is, it even affects the humble netcat, e.g. `nc -l 8889`. The program itself doesn't seem to notice but this gets repeatedly shown in `dmesg`:
```
init: (121) ERROR: StartHostListener:356: write failed 32
```
The problem doesn't go away until I shut down WSL and start it up again. If I don't have Docker Desktop start automatically then this never happens.

### Information
It is very reproducible but doesn't happen every single time.

I have always seen this problem since first trying WSL2 in early June, shortly after it became generally available.

  - Windows Version: 10 Enterprise 2004 19041.329
  - Docker Desktop Version: 2.3.0.4 (46911)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No, bare metal laptop.

### Steps to reproduce the behavior
  1. Set Docker Desktop to start "when you log in" through the settings.
  2. Shut down and power on. Don't restart/reboot!
  3. Log in.
  4. Enter WSL2.
  5. Run: `nc -l 8889`
  6. In PowerShell, run: `curl http://localhost:8889`
  7. It will fail to connect within a few seconds (successful connection will "hang" but show output in `nc`).
  8. Run `dmesg` and check for the above error message.

**Comment by simonferquel** [comment]
I'll try to reproduce it tomorrow, thanks

**Comment by simonferquel** [comment]
I can't reproduce the issue. The StartHostListener seem to indicate that WSL failed to open the listener on the Windows side (maybe there is already a listener on that port on the Windows side), but it should not be a problem if the client is running within wsl as well.

Per any chance, can you check that nothing else is listening on port 8889 (both on the Linux and Windows side) ?

**Comment by chewi** [comment]
It happens with any port and that's not the one I normally use. I did think it was strange that I couldn't find any other reports of this anywhere and surely something this bad would be fixed quickly. The only unusual thing I've done that is set up a `portproxy` rule so that I can reach WSL remotely.

```
netsh interface portproxy add v4tov4 listenport=8389 listenaddress=0.0.0.0 connectport=3390 connectaddress=127.0.0.1
```

The port numbers cannot match because otherwise the proxy connects to itself! I'll see what happens if I remove this.

**Comment by chewi** [comment]
Apologies, my test case was inaccurate. You're right, connecting within WSL does work. It also only seems to happen following a shut down rather than a restart. That may be why few have seen this. I always shut down at the end of the end of the day but I gather that's less popular these days. I tried removing the `portproxy` rule but it didn't help. I've now updated the original post.

**Comment by mateka** [comment]
I have not added portproxy or anything with netsh and have the same problem (on Docker Desktop stable and Windows 20H2 v. 19042.450). NodePort or LoadBalancer Kubernetes services will not expose port without setting port forwarding (kubectl port-forward).

**Comment by chewi** [comment]
Just to be absolutely sure this is the same issue, can you please confirm that you see the same error in `dmesg` and the problem goes away if you disable autostart? After struggling to find other reports, it's surprising to finally see one!

**Comment by mateka** [comment]
Yes, when I have disabled autostart and restarted my PC, there are no more problems in dmesg output. But my kubernetes service is still not working.

**Comment by chewi** [comment]
I've switched to using a Ubuntu-installed Docker. I'll close this.
