### ISSUE TITLE
Issue in docker while starting up

### ISSUE THREAD

**Issue by prabhat2020** [docker/for-win#8064]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by hirsche** [comment]
See #8049

**Comment by hirsche** [comment]
See #8049

**Comment by prabhat2020** [comment]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by prabhat2020** [comment]
Closing the issue
