### ISSUE TITLE
"Swarms" and "Repositories" context menu items in docker system tray are stuck on "loading..."

### ISSUE THREAD

**Issue by oncicaradupopovici** [docker/for-win#807]
### Expected behavior
I want to be able to access my Swarms and Repositories from the docker tray context menu.
### Actual behavior
"Swarms" and "Repositories" context menu items in docker system tray are stuck on "loading..."
### Information

  - Diagnostic ID:  
    7F8F1B0A-5A61-4507-9B2C-DAC80F3718D7/2017-06-09_10-26-04
  - host distribution and version:
    Windows 10 Enterprise, Version 1703, OS Build 15063.332

### Steps to reproduce the behavior
  1. Right click the docker system tray
  2. Hover "Swarms" or "Repositories" context menu items

![docker](https://user-images.githubusercontent.com/4567203/26965917-9669bf82-4d00-11e7-8c2d-b6a76417e8ce.png)

**Comment by oncicaradupopovici** [comment]
The problem was in my  docker environment variables. 
I have reset those with:
docker-machine env -u

**Comment by friism** [comment]
We should look into this cc @ebriney @simonferquel
