### ISSUE TITLE
Workaround for Windows crashes on first run.

### ISSUE THREAD

**Issue by jgwinner** [docker/for-win#8079]
### Workaround for the many issues with Docker starting.

I have a feeling, since there are so many bug reports and few comments that this is a "not on my machine" problem.

In part, that's true, but you know what they say about s#it rolling downhill.

In particular, this seems to be a problem with WSLX (WSL2 usually) on Windows, as it generates the same error. I have a work around!

But first, the format as requested / statement of the problem:

  - [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 6ED30E02-E031-40CF-A4CF-9EA8924CAEFD/20200719233329

### Expected behavior  

That 64G of RAM with 55G of RAM 'available' would be enough to run Docker on my first download.

### Actual behavior

Crashes with an "Out of Memory" error. 

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible? Yes
  - Is the problem new? Yes. Everything is new.
  - Did the problem appear with an update? Can't update, won't run.
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.
  - Windows Version: Windows 10 Pro for Workstations (dual core motherboard). Version	10.0.19041 Build 19041
  - Docker Desktop Version: latest stable, downloaded 2020 07 / 19. Can't get into it to see what version, download page doesn't indicate.
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No. 

### Steps to reproduce the behavior

  1. Download the most recent Stable version as of 2020 07 / 19
  2. Reboot the PC.
  3. Docker crashes when logging into the desktop.
  4. Docker crashes when resetting to factory defaults.

There were no dockerfiles, I never had a chance to even go through the startup screens.

Nothing was running at the time. 

I have 64GB of system RAM

### Workaround

I recently started loading WSL and found a bug with it as well.

While installing WSL, I ran into this:
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x8007000e
Error: 0x8007000e Not enough memory resources are available to complete this operation.

Press any key to continue...

```

In researching this, I found no solutions, but I DID find a work around.

Create a file in %USERPROFILE% with memory overrides. 

(usually c:\Users\Name)

```
cd %USERPROFILE%
copy con: .wslconfig
[wsl2]
memory=4GB
processors=2
^z
1 file copied

```
You can change the amount of RAM or processors to fit. Note that it is "dot wslconfig" ... instead of having a file attribute, I guess they are following the first period is hidden stuff. 

Then, restart the Docker install (or install WSL2 per the directions for that).

Docker then works fine!

So, it could be viewed as an underlying issue, but honestly, just saying "out of RAM" doesn't help, because it's obvious were were not. 

### Desired behaviour / Docker fix:

The fix for Docker should be to report "_while installing WSL, the following error occured: Error: 0x8007000e Not enough memory resources are available to complete this operation._" which would have prompted me to investigate that. Instead, I kept searching 0x8007000e and Docker, and got nowhere.

s#it rolls downhill!

        == John ==

**Comment by stephen-turner** [comment]
Thanks for the comments, @jgwinner.

We do document how to reduce the memory usage (or actually, we point to a Microsoft document) at the bottom of https://docs.docker.com/docker-for-windows/wsl/. Maybe it needs to be more prominent though.

Unfortunately we don't have any control over the text of the error message, it's a Windows message not ours.

**Comment by jgwinner** [comment]
You're welcome.

The error explanation is the Windows message, yes, but what you don't do is explain where the error came from. This is the critical fix.

If the error message had said **while installing WSL, ...** then I think the fix would have been more clear.

This is what I'm asking for :) 

        == John ==

**Comment by stephen-turner** [comment]
Yes, that's fair, thanks for the feedback.
