### ISSUE TITLE
WARNING: Error loading config file:.docker\config.json - EOF

### ISSUE THREAD

**Issue by sirio3mil** [docker/for-win#808]
After this command on Powershell 

PS C:\Users> docker stop $(docker ps -a -q)
WARNING: Error loading config file:C:\Users\.docker\config.json - EOF

Command executes correctly

F3A26979-4B94-4C86-A28E-C5DDE9C56888/2017-06-09_11-36-23

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jasonbivins** [comment]
Hi @sirio3mil 

What version of Docker for Win are you running?  I can run this command successfully in the latest Edge build.

**Comment by sirio3mil** [comment]
Version 17.06.0-rc2-ce-win14 (12510)
Channel: edge
e406757

**Comment by sirio3mil** [comment]
I just check that config.json is an empty file, delete?

**Comment by oncicaradupopovici** [comment]
Same version.
Same problem.
Also config.json is empty.

**Comment by oncicaradupopovici** [comment]
Also if I remove the config.json docker creates an emty config again

**Comment by JonasGroeger** [comment]
I deleted the empty file `~/.docker/config.json` and the warning is gone.

**Comment by oncicaradupopovici** [comment]
And if you restart the daemon?

**Comment by malawto** [comment]
Running Version 17.06.0-rc2-ce-win14 (12510) as well and had the same issue.   

./docker/config.json was empty, but I think had a wrong EOF char perhaps.  At any rate, deleting it and restarting the daemon fixed the warning message.

**Comment by jasonbivins** [comment]
You should be able to edit or disable the config.json file directly through the GUI. It sounds like there may have been an extra } or ' in the config file. 

![image](https://user-images.githubusercontent.com/28021664/27037445-fd25243a-4f55-11e7-955b-fa3a97ee69a5.png)

**Comment by whitecolor** [comment]
I didn't touch this config in any way. But got this error.

**Comment by kostapsimoulis** [comment]
The issue is that sometimes this file is completely empty. If you delete it, you will get rid of the warning, but if you restart your pc or docker it recreates the empty file you will have the same issue again. It is very annoying.. In my case, I manually edited the file and I added the following text inside and it seems to be working now:

`` {"credsStore":"wincred"}``

**Comment by janhartigan** [comment]
Also you can put `{}` in there and it goes away.

**Comment by YEslahi** [comment]
in ubuntu 18.04, this solved my problem:

sudo chown $USER:docker ~/.docker
sudo chown $USER:docker ~/.docker/config.json
sudo chmod g+rw ~/.docker/config.json

and for sure $USER is ur username! :D

**Comment by jaymoj** [comment]
In my case I'd to enter something to overcome the EOF issue. As suggested by docker settings I added:
`{
  "debug" : "false",
  "experimental" : "disabled"
}`
I do not have the warning showed up again.
Note: I made debug false and experimental disabled as I am not interested in that at this time.

**Comment by PaulObalonye** [comment]
hey guys , i need help , am tryingt o push my image to my docker hub..

ubuntu@ip-172-31-46-165:~$ clear
ubuntu@ip-172-31-46-165:~$ docker push awsdocker
The push refers to repository [docker.io/library/awsdocker]
d6f5889c8a4b: Preparing
5eaeb0d8d830: Preparing
04aebfb4ce61: Preparing
16542a8fc3be: Preparing
6597da2e2e52: Preparing
977183d4e999: Waiting
c8be1b8f4d60: Waiting
denied: requested access to the resource is denied
ubuntu@ip-172-31-46-165:~$
