### ISSUE TITLE
High utilization of "WMI Provider Host" process

### ISSUE THREAD

**Issue by jewfro-cuban** [docker/for-win#809]
### Expected behavior
Less utilization of WMI Provider Host process (?)

### Actual behavior
WMI Provider Host Process is taking 10-13 % of cpu utilization constantly with docker for windows running in the background.
No containers running.

### Information
Traced the blame on docker by just exiting from docker for windows and tracking the utilization of the cpu. Without docker running WMI Provider Host process does not consume cpu.

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
508F5DB4-2347-4CBD-A0D5-DC18E65443BD/2017-06-10_08-59-20

  - a reproducible case if this is a bug, Dockerfiles FTW
  Restart windows and just run docker for windows

  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)
     version 1511 (OS build 10586.916)

### Steps to reproduce the behavior

  1. Restart windows
  2. Run Docker for windows
  3. Check WMI Provider Host utilization
  4. Exit Docker for windows
  5. Check WMI Provider Host utilization again

**Comment by jasonbivins** [comment]
Hi @jewfro-cuban   what version of Docker for Win are you running?   I can't reproduce this on the latest edge build.

What environment are you running in, a VM or bare metal?  Can you open Hyper-v manager to see what the resource utilization looks like?

**Comment by jewfro-cuban** [comment]
I used:

Version 17.03.1-ce-win12 (12058)
Channel: stable
d1db126

Switched now to:

Version 17.06.0-rc2-ce-win14 (12510)
Channel: edge
e406757

Same behavior.

Docker for windows is installed on bare metal running windows 10.
When I open Hyper-v manager I see a single line under Virtual Machines:

Name: MobyLinuxVM
State: Running
CPU usage: 0%
Assigned Memory: 3584MB
..
Configuration: 7.0

**Comment by jewfro-cuban** [comment]
It seems that there were many hyper-v virtual switch managers created (Dummy) by docker.
Once removing them the issue is gone with cpu usage dropping to 1.5-2%.

**Comment by fabioformosa** [comment]
@jewfro-cuban  How did you remove dummy switch managers created by docker?

**Comment by nicolas-tg-ch** [comment]
To disable the dummy switch managers created by docker, open the network adapter config on windows (system control / change adapter options - i'm not sure about the translation in english). In my case, i had there over 60 (!) elements "vEthernet (standard switch) Hyper-V Virtual Ethernet Adapter". As soon as disabling them one by one, the cpu load of the WMI Provider Host dropped down to 0-5%.

**Comment by fabioformosa** [comment]
Ok thank you, the windows path to change it is: 
`"settings" -> "network" -> "status" -> "change adapter options"`
I have 2 adapter for hyper-V. I'll try to disable them and I'll report here my feedback. I want to test also if containers can access to internet.

**Comment by nicolas-tg-ch** [comment]
It should be considered to investigate by the docker developers why there are so many dummy switch managers created (and also how to get rid of them, deleting is greyed out even as admin). Since last week, there popped up a new one which i needed to disable as well.
