### ISSUE TITLE
Wordpress asks for FTP credentials

### ISSUE THREAD

**Issue by rafalborowski** [docker/for-win#811]
I wanted to switch from WAMP to Docker for WP theme and plugin development. The problem I have seems to be with permissions I believe? Which is wired, because I can upload/delete media files, just not themes and plugins.  I know that it's possible to do by putting them directly in the folder via mounted volume, but many parts of WP - especially plugins - relies on the upload functionality as a core function.

Any help would be greatly appreciated. Hope you can help or I will have to get back to WAMP :(

### Expected behavior

I would like to upload/delete themes and plugins from within WordPress.

### Actual behavior

Every time I want to make any change to plugins or themes WordPress asks for FTP credentials.

### Information

  - Diagnostic ID: 6F280582-FB47-4D19-94F8-47AC53FB5703/2017-06-11_19-20-39
  - I am using this: [docker_composer.yml](https://gist.github.com/rafalborowski/6322fabc7d82c483e052e51c8bb02b26)
  - Windows 10 Pro, Version 1703, Build 15063.332

**Comment by cedrox** [comment]
Hello, 
I am facing the same issue...
Nobody ?

**Comment by rafalborowski** [comment]
Personally I just gave up and went back to WAMP. After last update (well.. it was like half a year ago so... not the last but...) it's really nice and most of the problems are gone. Even switching versions is easier so...
