### ISSUE TITLE
Not able to run docker on Win10 Pro

### ISSUE THREAD

**Issue by bsn1980in** [docker/for-win#8120]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version: Win10 Pro
  - Docker Desktop Version:  19.03.12
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Cloud Server

Command prompt errors:

C:\Users\bsn1980in>docker version
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:43:18 2020
 OS/Arch:           windows/amd64
 Experimental:      false
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

C:\Users\bsn1980in>docker run hello-world
docker: error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/create: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
See 'docker run --help'.

C:\Users\bsn1980in>

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by pythonpythonxyj** [comment]
Have you solved it ? I have the same question!

**Comment by bsn1980in** [comment]
No. Not yet.
