### ISSUE TITLE
After enabling kubernetes settings page has forever loading circle on it

### ISSUE THREAD

**Issue by XandrKhv** [docker/for-win#8133]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B61704C1-FDD7-4C5E-B46C-F9FDCEAA3203/20200819063827

### Expected behavior

I can change my settings.

### Actual behavior

I cannot change my settings after starting Kubernetes.
Kubernetes launches endlessly (starting).

### Information

  - Windows Version: 1909 (18363.1016)
  - Docker Desktop Version: 2.3.0.4 (46911)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. Install Docker Desktop
  2. Enable Kubernetes

**Comment by ggranum** [comment]
I've rolled back to 2.3.03 from 2.3.05. Both have this issue on Mac. 

If you 'restart' there will be a short moment where you can navigate in the preferences and turn off Kubernetes. Of course, I'd prefer Kubernetes actually start again, but 2020 has apparently taken that away, too.
