### ISSUE TITLE
Docker Desktop for Windows is able to pull image from private Container Registry even if the password is expired

### ISSUE THREAD

**Issue by v1r7u** [docker/for-win#8135]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 964B6985-BD62-4720-9A7A-951A34CC94CF/20200819141709

### Expected behavior

If the password is expired, `docker pull` returns `401` even if it has a cached username/password pair. 

### Actual behavior

`docker login` returns 401, while `docker pull` is able to get images using previously cached credentials.

### Information

  - Windows Version: Win 10 Pro, version 2004, OS build: `19041.450`
  - Docker Desktop Version: 2.3.0.4 (46911)

### Details

I work with a private image-registry owned by a third-party supplier. The supplier gave me a temporary username/password pair, which I used with `docker login registry-address.com`. After that, I was able to pull images from the registry.

After a while, my password was _expired_. If I try to use it with the same registry in `docker login registry-address.com`, the registry responds with `401 Unauthorized` exception. But **I'm still able to pull images** from the same registry with plain `docker pull ...` commands, which uses previously cached credentials.

Unfortunately, I can not find any information over the Internet which explains how this case is possible. Is it because of the way how supplier's Container Registry handles `auth` and `pull` requests? Or are there any tricks on Docker Desktop for Windows side?

**Comment by stephen-turner** [comment]
I think this must be an issue with how the registry is handling authorization. It's up to the registry to control which images you have access to, whatever API requests any client sends it.
