### ISSUE TITLE
Docker Crash Report How to Fix?

### ISSUE THREAD

**Issue by ehtasham-azhar** [docker/for-win#8136]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by zero-8** [comment]
i have the same problem , i used git clone then i accidentally deleted the folder, tried uninstall and install but i wont work anymore also i am using windows 10 pro now
