### ISSUE TITLE
docker logs command with "follow" flag does not stream logs

### ISSUE THREAD

**Issue by JeanRev** [docker/for-win#814]
### Expected behavior
The ```docker logs``` command should stream logs continuously when the "follow" flag is set.

### Actual behavior
```docker logs --follow``` does not stream the process outputs as expected. Instead, it seems to hang until the container is stopped, and will then output the whole log history at once.

### Information

  - Diagnostic ID: E9E5-49B8-99EB-15F8905F821C/2017-06-12_16-42-01
  - Reproducible case:
A batch script (```time.bat```) that continuously output the current time every few seconds:
```bat
@echo off

:Start
echo %TIME%

ping 127.0.0.1 -n 5 > nul

GOTO Start
```

And this Dockerfile:
```Dockerfile
# escape=`
FROM microsoft/nanoserver:10.0.14393.1198

COPY time.bat C:\

CMD C:\time.bat
```
- host distribution and version: Observed with edge (17.06.0-rc2-ce-win14) and stable channels, on Win 10 Pro (1607, 14393.1198).

### Steps to reproduce the behavior

1. Build the corresponding Docker image: ```docker build -t test_logs .``` 
2. Start a new container from this image: ```docker run --name test_logs_container test_logs```
3. Stream the container logs: ```docker logs --follow test_logs_container```

**Comment by JeanRev** [comment]
I can reproduce the issue on Windows 2016 Server as well.

Any idea on this?

**Comment by friism** [comment]
@jena it's a known problem: https://github.com/moby/moby/issues/30046

I'll close this issue you can track progress on the other issue.
