### ISSUE TITLE
Problem with docker build on Windows 10

### ISSUE THREAD

**Issue by matheusAMDS** [docker/for-win#8140]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 02B091F6-B522-4E09-AD6C-1620ECE27923/20200819181945

### Expected behavior
  Build an especific image
### Actual behavior
  Running into this error: 
```error
Get https://registry-1.docker.io/v2/library/python/manifests/alpine: Get https://auth.docker.io/token? 
scope=repository%3Alibrary%2Fpython%3Apull&service=registry.docker.io: dial tcp: lookup auth.docker.io on 192.168.65.1:53: no such host
```
### Information
  - Windows Version: Windows 10 Pro 1903
  - Docker Desktop Version: 2.3.0.4
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. I just download the Docker Desktop for the first time and tried out the tutorial it provides and another one from youtube that do basically the same thing.
  2. When doing 'docker build -t docker101tutorial .' it gives me: 
```error
Sending build context to Docker daemon  10.21MB
Step 1/21 : FROM python:alpine AS base
Get https://registry-1.docker.io/v2/library/python/manifests/alpine: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fpython%3Apull&service=registry.docker.io: dial tcp: lookup auth.docker.io on 192.168.65.1:53: no such host
```

**Comment by talesdsp** [comment]
how you fixed it?

**Comment by matheusAMDS** [comment]
In my case i've gone to the hosts file and added: 192.168.65.1:53 auth.docker.io
