### ISSUE TITLE
Docker fails to start both Linux & Windows containers

### ISSUE THREAD

**Issue by brandonh-msft** [docker/for-win#816]
### Expected behavior
Docker starts
### Actual behavior
Docker fails to start both Linux and Windows containers
### Information
  - Diagnostic ID from "Diagnose & Feedback" in the menu.
Windows Diag Id: `0715a5f7-75ce-4910-8377-c22910190aa7`
Linux Diag Id: `a8d00a7b-47ea-4345-bad1-41abf1085da7`
  - host distribution and version (Windows version, build number, etc)
17.03.1-ce-win12 (12058) on Windows 10.16193.1001
- hardware
Surface Book i7/16gb
### Steps to reproduce the behavior

  1. Install Docker for Windows
  2. Reboot (so Docker auto-starts)
  3. Boom.

**Comment by brandonh-msft** [comment]
I've no idea why, but a recent reboot of my machine for other reason has both Linux and Windows containers via DfW working without issue.

¯\_(ツ)_/¯

**Comment by brandonh-msft** [comment]
and this morning it's back.
```
[08:15:17.212][NamedPipeServer][Error  ] Unable to execute Start: Docker hv-sock proxy (vsudd) is not reachable    at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

**Comment by jasonbivins** [comment]
Hi @brandonh-msft 
Do you normally see this error after you've been idle for a while, or when the machine is coming back from sleep mode?

**Comment by brandonh-msft** [comment]
Really any time docker starts up. So, might be after I exit, might be after a reboot, etc.

Incidentally, this was sent my way: https://www.windowspro.de/wolfgang-sommergut/docker-container-windows-10-installieren
In the article the user describes having to run Docker as an Administrator and Switch to Windows Containers at least one time in order for it to work fine from there on out. I did this advice and haven't had any problems after a reboot, Linux or Otherwise.

Seems like there is some Hyper-V configuration that needs to take place upon installation of Docker that is only done at launch time right now, but requires elevation so can't be done if you run as anything other than Admin.

**Comment by cn00** [comment]
My docker always run well. But one day I try `switch to Windows container`, then I cannot `switch to Linux container` for ever, even I reinstalled docker. Docker said "Hardware assisted virtualization and data execution protection must be enabled in the BIOS". Anyone got the same problem?

**Comment by jasonbivins** [comment]
@brandonh-msft    Thanks for sharing that article!  Did you  have to disable, or uninstall Hyper-v before doing the manual Hyper-V setup portion?

**Comment by jasonbivins** [comment]
Hi @cn00 Can you please open a new issue along with your diagnostic ID  ?

**Comment by cn00** [comment]
Thanks, I uninstalled Hyper-v and reinstall docker, and docker auto installed Hyper-v. Then, all things goes well.

**Comment by brandonh-msft** [comment]
@jasonbivins no. But it does appear as though it's not a universal fix. I still get errors when Docker starts occasionally, but not as chronic. ¯\_(ツ)_/¯
