### ISSUE TITLE
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

### ISSUE THREAD

**Issue by chiqui3d** [docker/for-win#8164]
## Description of the issue
Suddenly it has stopped working docker in WSL2 in the last edge version

### Diagnostics ID
```
6C7BA352-5B51-4745-99F2-143F2348A5BC/20200820234153
```
**Output of `docker-compose version`**
```
nerja@DESKTOP-A55E18M:~/crm$ docker-compose -v
docker-compose version 1.26.2, build eefe0d31
```

**Output of `docker version`**
```
nerja@DESKTOP-A55E18M:~/crm$ docker -v
Docker version 19.03.13-beta2, build ff3fbc9d55
```

## Steps to reproduce the issue
```
nerja@DESKTOP-A55E18M:~/crm$ sudo docker-compose restart
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.


nerja@DESKTOP-A55E18M:~/crm$ docker-compose restart
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```

## Additional information

Windows 10 Pro 19042.450

**Comment by colonelsammy** [comment]
+1.

Failed after upgrade to 2.3.5.

Reverted to stable (2.3.0.4) and that's ok after a reboot.

Windows 10 Pro 19041.450

**Comment by chiqui3d** [comment]
Hey @colonelsammy , 

I want to revert as you have done, for that I have gone to the penultimate version in this link https://docs.docker.com/docker-for-windows/edge-release-notes/

It won't let me install since I have a more recent version, so I have to uninstall docker-win, my question is if by uninstalling I don't **lose the current containers**? or is there another way to revert?

**Comment by samuk190** [comment]
i have a bug where after starting my docker compose, my docker simply stop working on wsl, and If you see the previous logs, it seems docker doesnt run directly on wsl2, but instead on windows, strangely! I messed with mounts by changing $env: in powershell now I dont know how to undo it

**Comment by simonferquel** [comment]
Thanks for reporting the issue, we are aware of the issue, and working on a fix. I'll have a private build in an hour or so.

**Comment by simonferquel** [comment]
Can you check if this private build: https://desktop-stage.docker.com/win/edge/47392/Docker%20Desktop%20Installer.exe fixes the issue ?

**Comment by kyanet** [comment]
Thanks!
Though I had the same issue, the private build woks fine!

**Comment by lazybean** [comment]
> Can you check if this private build: https://desktop-stage.docker.com/win/edge/47392/Docker%20Desktop%20Installer.exe fixes the issue ?

It does fixes it for me! Thanks a lot!

**Comment by kyanet** [comment]
Sorry, but I'm still facing the wired path issue.
when I run wsl2 the CWD is ```/tmp/docker-desktop/shadowing-mounts/95836c5ee1789e58e9f81441b9888b55e6cd4df01c860829d065fbe4bdef0ba3/tmp/docker-desktop/shadowing-mounts/a077f914501ff153be706b0abb691024ed020adf7825f5111cbf258046343d91/tmp/docker-desktop/shadowing-mounts/9d412a19b652d2ce33e90c89de10a50f5a899bfe364b3f74bfa47799cddb106f/tmp/docker-desktop/shadowing-mounts/71329c4cc6e32171553fa81d044eb31d1a3aac52ba9376c4a99f4505c494cf5b/tmp/docker-desktop/shadowing-mounts/85e12080a6809a9097c13fd439cb6159634c7eb5f65933d4c037d61ac62a9f78/tmp/docker-desktop/shadowing-mounts/72d20e1a6c77033943f202de3825fcc9c4de72d5e78f447ead3ea7d8928d5b51/tmp/docker-desktop/shadowing-mounts/eee9ca25a5ed53f3856c97b7381e8fe4cd1e1387c81eb78aa16cb0457017c259/mnt/c/```

I'm not sure this is related to this issue.

**Comment by simonferquel** [comment]
the CWD thing seem to be a bug in wslpath. It is partly related but we can't really do a thing about it for now.
cc @benhillis, I noticed that when windows drives are mounted on different mountpoints (such as when doing `mount --rbind /mnt /somewhere`), wslpath picks up a wrong mount point to answer to queries such as `wslpath c:\\Users`. It seems to impact the working directory picked up when running `wsl.exe` without arguments as well.

**Comment by uncodable** [comment]
Constantly getting this now also:
![image](https://user-images.githubusercontent.com/32820112/91065036-e9de6280-e627-11ea-8b1f-88974bbad52e.png)

And:
```
Traceback (most recent call last):
  File "site-packages\docker\utils\build.py", line 96, in create_archive
OSError: [Errno 22] Invalid argument: '\\\\?\\C:\\Users\\Nick\\Desktop\\GitHub\\mvp\\mvp\\backend\\vendor\\bin\\carbon'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 72, in main
  File "compose\cli\main.py", line 128, in perform_command
  File "compose\cli\main.py", line 1078, in up
  File "compose\cli\main.py", line 1074, in up
  File "compose\project.py", line 548, in up
  File "compose\service.py", line 367, in ensure_image_exists
  File "compose\service.py", line 1106, in build
  File "site-packages\docker\api\build.py", line 160, in build
  File "site-packages\docker\utils\build.py", line 31, in tar
  File "site-packages\docker\utils\build.py", line 100, in create_archive
OSError: Can not read file in context: \\?\C:\Users\Nick\Desktop\GitHub\mvp\mvp\backend\vendor\bin\carbon
[38084] Failed to execute script docker-compose
```

Seem to be constant file sharing issues, this is only on the latest version + the private build above also, if I revert it works fine. Seems to be when it's mounted. 

WSL keeps shitting itself and disconnecting from these 2 versions? It's not liking mounts at all for some weird reason and randomly dropping off still?

Checked with 2 other dev machines also, we've had to roll back. No issues on actual Ubuntu machines, just seems somethings going on with WSL and Docker on windows..

**Comment by benoitscherrer** [comment]
> Can you check if this private build: https://desktop-stage.docker.com/win/edge/47392/Docker%20Desktop%20Installer.exe fixes the issue ?

uninstall previous version, tried it, but did not fix it for me
```
docker

Usage:  docker [OPTIONS] COMMAND
[...]
```

but 
```
docker images
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

(Windows 10 PRO Version 10.0.19041 Build 19041)

**Comment by benoitscherrer** [comment]
wtf, uninstalling that special build, reinstalling 2.3.4.0, having errors at startup of Docker Windows, accepting to reset to default, not working, desinstalling again, rebooting, reinstalling 2.3.4.0, and nothing working
```
 docker

The command 'docker' could not be found in this WSL 2 distro.
We recommend to activate the WSL integration in Docker Desktop settings.

See https://docs.docker.com/docker-for-windows/wsl/ for details.
```
(obviously have WSL integration ON)

**Comment by uncodable** [comment]
![image](https://user-images.githubusercontent.com/32820112/91219787-1f13af00-e713-11ea-9c29-ab2a47ac43a1.png)

New version release.

**Comment by simonferquel** [comment]
Indeed version 2.3.5.1 contains the patch fixing this issue.

**Comment by uncodable** [comment]
Latest version I'm still hitting this issue again, 🤔 - https://github.com/docker/for-win/issues/8164#issuecomment-679204006

**Comment by davclark** [comment]
@uncodable you can't easily mount Windows paths if you're launching from WSL 2. Hopefully this is now stable and will soon be documented!

There are tricks that I've used to mount windows paths from WSL 2, but I don't think they are necessarily going to work long-term, so I won't recommend them here (even though I've come up with at least one of them).

**Comment by uncodable** [comment]
@davclark these are volumes mounted from docked-compose. It's only been affected in these latest releases.

**Comment by PavelSosin-320** [comment]
To use socket end-point the only common path for all WSL distros is /mnt/wsl and any fs inode which can be shared has to be under this path. Unfortunately, WSL allows breaking such sharing by changing mnt root in the wsl.config from / to /host or /windows , etc. Access to such inode can be not allowed if users of both processes, daemon, and client don't belong to the docker group. 
The "native" docker running in Linux delegates creation of docker socket to the systemd unit which creates it in the /run/docker **during the boot sequence and any process can find it there.**
To use TCP end-point 2 distros has to share Windows host localhost because all ports of all distros are published on the Hosts Eth0, there is no bridge adapter in WSL2, unlike classic Hyper-V virtual switches. Every distro The host's IP is known for all distros via /etc/hosts as host.docker.internal, i.e. -host tcp://host.docker.internal:2375 is always valid until there is another TCP server running in any distro binds the same port but in this case, the error should occur when binding.
By default Docker desktop daemon listens to npipe end-point docker-engine. It looks like only Linux which has PipeFS in its kernel can share docker_engine **fifo using its path**. It assumes that but unfortunately, the same path doesn't mean the same iNode in 2 different filesystems unless the corresponding iNode is created under /mnt/wsl/...distro/run with right timing!

**Comment by uncodable** [comment]
Something funky still going on, just attempted to build inside WSL2 (ubuntu latest ditro):
```
nick@DESKTOP-JSB0V3F:/mnt/c/Users/Nick/desktop/github/mvp/mvp$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
nick@DESKTOP-JSB0V3F:/mnt/c/Users/Nick/desktop/github/mvp/mvp$ docker-compose up --build
Removing network mvp_app
Creating network "mvp_app" with driver "bridge"
Building backend
```

Hangs on the building of a container within Ubuntu 😕

**Comment by chiqui3d** [comment]
I just updated to version 2.3.6, and now I get a new error. So I'm going back to the version 2.3.4

I put the error in case it helps:


```sh
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1252, in request
  File "http/client.py", line 1298, in _send_request
  File "http/client.py", line 1247, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 966, in send
  File "docker/transport/unixconn.py", line 43, in connect
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 727, in urlopen
  File "urllib3/util/retry.py", line 403, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1252, in request
  File "http/client.py", line 1298, in _send_request
  File "http/client.py", line 1247, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 966, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 205, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 228, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 120, in perform_command
  File "compose/cli/command.py", line 69, in project_from_options
  File "compose/cli/command.py", line 132, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 188, in __init__
  File "docker/api/client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))
[318] Failed to execute script docker-compose
```

**Comment by reifnotreef** [comment]
Had this issue come up this morning, tried restarting Docker to no avail.  

Somehow the toggle for enabled integration in my Ubuntu WSL2 install was turned off, turning it on and Apply&Restart fixed it.
