### ISSUE TITLE
WSL2 has been ported to Windows 10 1903 and 1909. Enable WSL2 on Docker for windows on those versions

### ISSUE THREAD

**Issue by rodrigo-a-moreno** [docker/for-win#8180]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
I should be able to enable WSL 2 if WSL 2 is installed no matter what version of windows I have.
Check https://ubuntu.com//blog/ubuntu-on-wsl-2-backported-to-windows-10-1909-extending-reach
### Actual behavior
WSL 2 is only enable if Win10 Build 19018+ is installed
### Information

  - Windows Version: Win 10 1903
  - Docker Desktop Version: 2.3.0.4
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Open Docker desktop
  2. General
  3. Notice WSL 2 is disabled

**Comment by rodrigo-a-moreno** [comment]
Confirmed. This is on edge. Thanks

**Comment by rodrigo-a-moreno** [comment]
![image](https://user-images.githubusercontent.com/371290/91058343-53de1400-e5f6-11ea-9d90-297e894a0c41.png)

**Comment by thexpand** [comment]
When can we expect this on the stable channel as well?
