### ISSUE TITLE
WSL initial location is broken after starting docker edge

### ISSUE THREAD

**Issue by IanAWP** [docker/for-win#8186]
- [x] I have tried with the latest version of my channel (Stable or Edge)

### Expected behavior
WSL terminal session should start under %USERPROFILE% (C:\Users\<YourUsername>)  as mentioned here
https://docs.microsoft.com/en-us/windows/terminal/troubleshooting
### Actual behavior
![image](https://user-images.githubusercontent.com/10508645/90952570-a0630b80-e49f-11ea-807e-1139f4ab704b.png)
prompt now starts at 
```/tmp/docker-desktop/shadowing-mounts/1395f5ef29700963d92c2092b3ed74e6f9d42f15d6501f60c2423bd233c63a97/tmp/docker-desktop/shadowing-mounts/cc1cb8ff0d282b2343b9175918f54490754723e9a511ab820a30f6a612df3183/tmp/docker-desktop/shadowing-mounts/dc44998e89b2e3825b9a7852f8576cf0986f72c6541e84a4fbd317894604172a/tmp/docker-desktop/shadowing-mounts/ffb9bf47bb62e4894a62027db8b2efccd9137da24f1b7a9647dba738398011cd/tmp/docker-desktop/shadowing-mounts/008c6f016bb4c2a02a178cbc4c213e8b604beeb6c69cb62116f0350eab853f44/tmp/docker-desktop/shadowing-mounts/dd640510471715b6a7ccd083f8beb3bef9ed4cd15aaa40046da3d63db42fed19/tmp/docker-desktop/shadowing-mounts/b720499e4ca8d802603663dae14d15458a80cc5e51e3a21efd96f86359e4873a/tmp/docker-desktop/shadowing-mounts/3480ce5d3cdb7e4e4c2801dfde82344649e5597e06d0903e7fbfd0a07296ca13/tmp/docker-desktop/shadowing-mounts/1bb3f2c81deced53b43d9bc5c0b82a8c1d63b7f0c2924598b4b6f5a2a84ab4d1/tmp/docker-desktop/shadowing-mounts/19201276b821f2cb01d0ae0ae4576d9ed1cbe26eb4dbdcb7daff6939665a2347/tmp/docker-desktop/shadowing-mounts/618ed086f95fcef675a2666faa0df151d64f0e0b3332160e1ae245f8876521a6/mnt/c/Users/```
### Information

 Windows 10, 1909 Build 18363.1049
Docker Desktop 2.3.5.0 (47357), Engine 19.03.13-beta2

### Steps to reproduce the behavior

Upgraded an Ubuntu 18.04 image from WSL 1. I also restarted WSL after encountering https://github.com/docker/for-win/issues/8182, which may or may not be relevant
connections via windows terminal work properly until docker WSL backend starts, after which further terminal sessions have the above default path.
restarting WSL clears this until docker WSL backend is started again. 

**More context**
Not sure if this is relevant, This issue and 8182 did not occur on Ubuntu 20.04 (installed after upgrading docker and WSL) until after
a) installing vscode server
b) building a few images

**Comment by scoutme** [comment]
+1 : Simply restarting Docker with wsl2 integration break the location (even without restarting vscode server).
So:

- wsl restart ==> proper location
- subsequent docker desktop restart ==> broken terminal location

**Comment by SoerenHa** [comment]
Uninstalling the Docker Extension in WSL solved that problem for me

**Comment by affinityDrops** [comment]
The _verbose_ starting location at least has a (not quite satifactory) workaround that uses `startingDirectory` property of Terminal.
But there is another one annoying, `wslpath` is also affected.

**Comment by IanAWP** [comment]
Fixed for me in edge 2.3.6.1
