### ISSUE TITLE
Docker Desktop fails with starting

### ISSUE THREAD

**Issue by vikMAKS** [docker/for-win#8192]
- [Yes ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Docker Desktop starts
### Actual behavior
Is not oppening
### Information

  - Windows Version: 2004
  - Docker Desktop Version: 19.03.12
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  I did not do anything.Just tried to start the app

**Comment by MerlinSzymanski** [comment]
Hey,
I had the same problem, but realized, that Docker Desktop runs on my machine without popping up a window.
You can right-click on the icon (see screenshot) and pick "Dashboard".

I hope it helps

![docker](https://user-images.githubusercontent.com/45922464/91230075-2cd52e80-e72b-11ea-9fb6-134e5f3be951.png)

**Comment by vikMAKS** [comment]
Thanks.It works and I realized that the window should not pop up
