### ISSUE TITLE
Docker Compose does not work in WSL 2

### ISSUE THREAD

**Issue by ablekh** [docker/for-win#8195]
While `docker` command works fine, my attempts to run `docker-compose` command in WSL 2 (Ubuntu 20.04) fail with the following message.

```
The command 'docker-compose' could not be found in this WSL 2 distro.
We recommend to activate the WSL integration in Docker Desktop settings.

See https://docs.docker.com/docker-for-windows/wsl/ for details.
```

_Docker Desktop (DD) integration with WSL 2 **is enabled** in the DD dashboard_, hence my surprise.
Operating system: Windows 10 version 2004. Installing Docker Compose in WSL 2 directly did not help either.

**Comment by tenacioustechie** [comment]
I have the same issue. Were you able to work out the issue @ablekh ?
