### ISSUE TITLE
The new Docker-for-windows can't start

### ISSUE THREAD

**Issue by PavelSosin-320** [docker/for-win#8201]
- [ X] I have tried with the latest version of my channel (Stable or Edge)
  - [ N] I have uploaded Diagnostics
  - Diagnostics ID: Docker desktop diagnostics fails silently if docker can't start

### Expected behavior
Docker desktop starts

### Actual behavior
Fails to start: Docker start failure
### Information

  - Windows Version: Windows 10 2.0.0.4 latest update
  - Docker Desktop Version: 2.3.5.0 CE
Docker desktop distro uses Linux kernel  4.19.121-microsoft-standard
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Update Docker desktop to the latest release
  2. Wait until start or crash

Docker produces err log files containing the same message: 
Get "http://localhost/v1.24/containers/json?all=1": open \\.\pipe\docker_engine: The system cannot find the file specified.
Docker Docker-desktop distro dmesg finds in the log:
1.default automatic helper assignment has been turned off for security reasons and CT-based  firewall rule not found. Use the
2. iptables CT target to attach helpers instead. Is it supported by Microsoft kernel?
3. cgroup: runc (5881) created nested cgroup for controller "memory" which has incomplete hierarchy support. Nested cgroups may change behavior in the future.
. [51234.591234] cgroup: "memory" requires setting use_hierarchy to 1 on the root - It is not supported by Microsoft kernel for sure.
4. Init: (33) ERROR: CreateProcessEntryCommon:601: execvpe /windir/wsl/docker-desktop/docker-desktop-proxy
[51239.032634]  failed 2 - windir is only a placeholder. The actual mount point in your distro is /mnt/host: root = /mnt/host. The actual path to the docker proxy is /docker-desktop-proxy
5. init: (1) ERROR: ConfigApplyWindowsLibPath:2109: open /etc/ld.so.conf.d/ld.wsl.conf entire Microsoft init.d is problematic and etc/ld.so.conf.d is problematic in the many distros.

**Comment by PavelSosin-320** [comment]
The same error  \.\pipe\docker_engine: The system cannot find the file specified. I get when trying to use docker CLI 
Fortunately, the named pipe issue is not new and some solutions have been proposed: [named pipes issue](https://dille.name/blog/2017/11/29/using-the-docker-named-pipe-as-a-non-admin-for-windowscontainers/)
The WSL distro integration may add more complexity - the dockerd and docker CLI processes may be started by different users. I'm wondering what is semantics of sharing connection between Docker daemon user, Windows user and another distro user?

**Comment by PavelSosin-320** [comment]
Dockerd starts successfully when I run dockerd.exe manually and listens to //.npipe/docker_engine as I see it in the log - see attachment.
![dockerdStartError](https://user-images.githubusercontent.com/54495912/91269103-312b3700-e77f-11ea-9337-9c68a81724be.png) but then processes running in the Windows, like VPNKit tries to use this named pipe. Maybe, it is OK for docker CLI which looks at docker host definition but all other Windows stuff tends to fail including troubleshooting even when docker runs. Even when Windows's exe is invoked from WSL it doesn't run like a regular WSL Linux process and has to use an undocumented interop socket.
Named pipes over the network is fancy but not so reliable way to remote server IPC because they depend on the network layer anyway. Some people found it disappointing [Cross host named pipes](https://stackoverflow.com/questions/6120124/how-to-use-named-pipes-over-network).

**Comment by PavelSosin-320** [comment]
According to Docker Desktop proposal [DockerDesktop interoperatebility](https://docs.microsoft.com/en-us/virtualization/community/team-blog/2017/20171208-wsl-interoperability-with-docker) I should see npiperelay in C:\Program Files\Docker\Docker\resources and socat in /usr/bin at another side. But I see nothing.
npiperelay and socat uses stdio for communication but there is no real stdio pipe in WSL without interop socket.
Also Docker desktop distro has to be started with -u root option to be able to create npipe or use runuser or unshare for environment isolation.

**Comment by PavelSosin-320** [comment]
Also, Docker Desktop upgrade doesn't help but something new I see related purely to WSL. Docker desktop Distro doesn't appear in any WSL distros list. I experience this problem after the May Windows update. Since the CentOS7 distro I never succeeded to install any Distro, even from Microsoft Store. The root FS is not created properly in the right folder unless it is copied and registered manually. I did it for CentOS8.1 and it works now. It looks like the Powershell Cmdlet which is used in the standard installations is broken since the may update. I found that the more reliable way to install distro with blank Microsoft kernel root FS and then import Distro tar. In such a way it is possible to start the daemon and guest processes one-by-one and eliminate timing issues. It allows me to move my distro to another, faster drive with more space. From this drive my docker CEdaemon starts about 10 times faster than DockerDesktop daemon. If I will find the Docker distro rootFS image I can put it into right place manually.

**Comment by PavelSosin-320** [comment]
See installation log:
[install-log.txt](https://github.com/docker/for-win/files/5168103/install-log.txt)
Please, pay attention on the error related to CentOS8. Its installation also fails and distro can't start and is not accessible.
CentOS 8.1 I installed manually

**Comment by bascisco** [comment]
Hello Installed Docker for Windows 2.3.0.4 on Windows 10 1909 running as VM on VMworkstation. 
I get the next issue doing the simple helllo-world test.
PS C:\WINDOWS\system32> docker run hello-world
docker: error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/create: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
See 'docker run --help'.

Brgds,

Bas.

**Comment by PavelSosin-320** [comment]
[log.txt](https://github.com/docker/for-win/files/5199947/log.txt)

The recent 2.3.6.2 doesn't start too. When I look at the startup log I see at line 256 direct rc.init invocation in inside Docker's distro. On other hand, I checked a long time ago that the docker daemon is actually started when I run it manually. 
THE entire WSL distro initialization is not so clean and synchronization of starting processes in Linux using InitRC is not so simple. Running VPNKit diagnostics ( line 255 ) in parallel with the starting of Docker daemon (line 227 ) using Init.RC looks risky.
More than 20 secs may require to start daemon and load containers. I don't see any regular message that the daemon started to listen to the socket or pipe.

**Comment by bascisco** [comment]
Update, as I run Windows 10 64 Pro in a VM (VM workstation), I discovered that I had to enable for the VM the Virutalization Engine. Virtualize Intel VT-x/APT or AMD-V/RVI.  That allowed Docker for WIndows to start.  I haven't tried but  without the option you need to use then likely 
the DFW  Windows Home edition.

**Comment by FabelVlad** [comment]
have the same problem
