### ISSUE TITLE
Docker not running in default WSL2 distro: Ubuntu 20.04

### ISSUE THREAD

**Issue by ad-on-is** [docker/for-win#8208]
I have 2 WSL2 distros. Ubuntu 20.04, which is my daily driver, and Kali, which I occassionally use to test stuff.
Today I updated Windows 10 20197 and Docker 2.3.5.0, and since then Docker stopped working on my Ubuntu 20.04 distro.

I've noticed, that Docker Desktop takes a very long time to start. It used to start within seconds, now it takes minutes.

Also, when opening a WSL-distro, I get the following message:
`An error occurred mounting one of your file systems. Please run 'dmesg' for more details. `

Logs: https://pastebin.com/jrVEsd7E

Ubuntu 20.04
```
docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

Kali
```
add@ADISDELL:~$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

Docker is enabled for both distros.

![image](https://user-images.githubusercontent.com/9553253/91060088-d254a900-e62a-11ea-9991-a1c0585104ac.png)

## Update
I just downloaded and imported a fresh Ubuntu 20.04 from here: https://cloud-images.ubuntu.com/releases/focal/release/ and Docker works fine, but I'm still curious why it's not working on my existing Ubuntu 20.04, which I installed from the Microsoft Store.

**Comment by grthr** [comment]
Seems like I have the same issue here. I do not have additional WSL distros.
![image](https://user-images.githubusercontent.com/5175544/91063564-74c25b80-e62e-11ea-9f0d-c1461dbc1330.png)

**Comment by grthr** [comment]
Might be duplicate of #8207

**Comment by ad-on-is** [comment]
I just downloaded and imported a fresh Ubuntu 20.04 from here: https://cloud-images.ubuntu.com/releases/focal/release/ and Docker works fine.

**Comment by grthr** [comment]
Yes, it is from the MS-Store. But I didn't try a fresh Ubuntu. Instead, I downgraded to Docker Desktop Stable (2.3.0.4) which is working fine

**Comment by ad-on-is** [comment]
I can confirm, It works with 2.3.0.4
