### ISSUE TITLE
Edge channel: Docker Desktop Dashboard consumes 25% of 8-core CPUs in the Logs window 

### ISSUE THREAD

**Issue by speller** [docker/for-win#8216]
EDGE Channel: When a container has a long list of logs, opening these logs in the Dashboard causes 25% CPU load on the 8 cores system.

  - Diagnostics ID: B65D90E2-8303-4D75-A198-A74C007C521B/20200825015611

### Expected behavior
No additional CPU consume on the Logs window without any relation to the size of the logs.

### Actual behavior
As many logs appear as slower, CPU-consuming, and freezing the UI become.

  - Windows Version: Windows 10 2004
  - Docker Desktop Version: 2.3.5.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

**Comment by speller** [comment]
![image](https://user-images.githubusercontent.com/1829515/91114443-e2b86280-e6c2-11ea-8309-dc6195d034e2.png)

**Comment by stephen-turner** [comment]
Thanks for the report, @speller, I've raised an internal ticket for us to look at this.

**Comment by djs55** [comment]
We've made some performance improvements to the logs tab in Docker Desktop Edge 2.3.7.0: https://docs.docker.com/docker-for-windows/edge-release-notes/#docker-desktop-community-2370 . Let us know what you think. I'll close this ticket but feel free to comment here if you feel it's not been fixed and we'll re-open.

Thanks again for your report!
