### ISSUE TITLE
Docker Desktop faile first run

### ISSUE THREAD

**Issue by whoprod** [docker/for-win#8222]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 62D115FF-7BA1-41D5-80FC-D0AAF418CF02/20200825130331

### Information

  - Windows Version: Windows 10
  - Docker Desktop Version: 2.3.0.4
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

**Comment by sleeyax** [comment]
/remove-lifecycle stale

I'm also having this issue. It never works on the first run and always requires a restart of docker in order to work.
