### ISSUE TITLE
Unable to start Docker daemon after uninstall and reinstall

### ISSUE THREAD

**Issue by tienchienchen** [docker/for-win#823]
### Expected behavior
expecting to start docker daemon
### Actual behavior
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The object already exists.

   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
A diagnostic was uploaded with id: 
0FEC2FFE-5C56-48FE-A34F-7E3A67338F4E/2017-06-14_13-14-46
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior
1)uninstall Docker from Windows 10
2) remove docker share drive c:
3) reinstall docker  for windows 10

**Comment by jasonbivins** [comment]
Hi @tienchienchen 
What version of Docker are you installing?

Can you share more information, or screenshots for step #2 ? Can you explain how you're removing the share?
