### ISSUE TITLE
First Install Docker Tutorial Fails to Start Container

### ISSUE THREAD

**Issue by DanJ210** [docker/for-win#8237]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 2125B433-F12F-4FB9-A1C8-126161D8D6DC/20200826233704

### Expected behavior
Using Docker desktop for the first time and going through the tutorial which gave an error and I don't know how to restart it after the windows was closed when I reported an error. Clicking next first clone the repository, then build the project all succeeded with warnings about Windows containers. Running the next command to start the container on port 80 would start the container.
### Actual behavior
Running the command to start the container on port 80 failed. I can't see the error message anymore because reporting shut down the tutorial and I don't see how to restart it.
### Information

  - Windows Version: 10 Pro 2004 19041.450
  - Docker Desktop Version: 2.3.0.4 (46911)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: I'm just on Windows 10 with virtualization enabled.

### Steps to reproduce the behavior

  1. Just install Docker and open it for the first time.
  2. Run each command.
  3. Command fails when starting the container on port 80.

**Comment by mjruttenberg** [comment]
When you say "failed", what do you mean?
When I run `docker run -d -p 80:80 \ --name docker-tutorial docker101tutorial` I get `The container name "/docker-tutorial" is already in use by container "<long hex address>". You have to remove (or rename) that container to be able to reuse that name.`
![image](https://user-images.githubusercontent.com/6740173/91841201-d6e01980-ec49-11ea-8316-8aaac8e343e0.png)

**Comment by DanJ210** [comment]
It just says failed. I can try again to see if I missed something.

I reported a problem and it sent me here. How do we get someone who uses Docker to be able to do this?
