### ISSUE TITLE
Docker 17.03.1 won't start on Windows 10 Enterprise

### ISSUE THREAD

**Issue by brandonoakley** [docker/for-win#824]
### Expected behavior
Expect Docker to startup when Windows boots up.

### Actual behavior
Docker doesn't start. Logs seem to show It hanging on "[HyperV         ][Info   ] Creating Switch: DockerNAT..."
[See attached log](https://github.com/docker/for-win/files/1076342/log.txt)

Even after uninstall and reinstall Docker doesn't startup and hangs on "Creating Switch: DockerNAT...".

### Information
  - Diagnostic ID: DE9C1816-D2F7-4751-9680-2D2BF2D7C16E/2017-06-14_20-31-02
  - Host: Windows 10 Enterprise Version 1607 Build 14393.1198

**Comment by jasonbivins** [comment]
hi @brandonoakley 
Try these steps - they seem to have helped in a few cases. It seems that the Hyper-V and the Container windows feature have some extra steps to run on installation that need elevated privileges.
1. Uninstall Docker, Hyper-V, and if installed - the containers feature.  Then reboot.
2.  Either through the control panel, or running powershell as an admin, enable Hyper-V
          Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All
3 .Reboot, then enable the containers feature either through the control panel or through an elevated 
    powershell prompt
       Enable-WindowsOptionalFeature -Online -FeatureName Containers -All
4.  Install Docker

Please let me know if that helps

**Comment by brandonoakley** [comment]
After doing all the above as an admin via powershell (as admin) looks like my issue is resolved. Thanks
