### ISSUE TITLE
Cant login and so I cant pull any image

### ISSUE THREAD

**Issue by K2ouMais** [docker/for-win#8244]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
9D7CDE45-52E3-4545-B519-3354AE41D897/20200827174529

### Expected behavior
I was expecting to pull an ubuntu image. Also the GUI is saying I am logged in, but I cant login with the CLI.

### Actual behavior
I am getting an error when trying to pull any image.

Error response from daemon: Get https://registry-1.docker.io/v2/library/ubuntu/manifests/latest: Get https://auth.docker.io/token?account=johnnybigodes&scope=repository%3Alibrary%2Fubuntu%3Apull&service=registry.docker.io: unexpected EOF

docker: Error response from daemon: Get https://registry-1.docker.io/v2/docker/getting-started/manifests/latest: Get https://auth.docker.io/token?account=johnnybigodes&scope=repository%3Adocker%2Fgetting-started%3Apull&service=registry.docker.io: unexpected EOF.

Error response from daemon: Get https://registry-1.docker.io/v2/library/hello-world/manifests/latest: Get https://auth.docker.io/token?account=johnnybigodes&scope=repository%3Alibrary%2Fhello-world%3Apull&service=registry.docker.io: unexpected EOF

<b>While trying to login:</b>
Authenticating with existing credentials...
Login did not succeed, error: Error response from daemon: Get https://registry-1.docker.io/v2/: Get https://auth.docker.io/token?account=johnnybigodes&client_id=docker&offline_token=true&service=registry.docker.io: unexpected EOF
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username (johnnybigodes): johnnybigodes
Password:
Error response from daemon: Get https://registry-1.docker.io/v2/: Get https://auth.docker.io/token?account=johnnybigodes&client_id=docker&offline_token=true&service=registry.docker.io: unexpected EOF

**I can login on the page, but not on CLI.**

### Information
  - Is it reproducible?
Everytime I try to pull an image.

  - Is the problem new?
Yes. I could work with it the last few days.

  - Windows Version: 
Windows 10 Pro

  - Docker Desktop Version:
Docker version 19.03.12, build 48a66213fe

  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
No

I am not behind a proxy, so that shouldnt be a problem.

### Steps to reproduce the behavior

  1. docker pull ubuntu
  2. docker pull hello-world

**Comment by ToxicToast** [comment]
I have the same Problem.

**Comment by K2ouMais** [comment]
> I have the same Problem.
> Docker Dashboard and on the Homepage works fine, only CLI seems to be broken

Is there a chance that you are also in Germany and using a Fritzbox as a router?

**Comment by ToxicToast** [comment]
> > I have the same Problem.
> > Docker Dashboard and on the Homepage works fine, only CLI seems to be broken
> 
> Is there a chance that you are also in Germany and using a Fritzbox as a router?
> 
> If that is the case I can assure you the Fritzbox is the problem.
> 
> AVM Routers fu**** big this time. The Fritzbox Firmware is blocking everything on AWS.
> 
> Go to your Fritzbox to Inhalt and after that to Fritzbox Support... Turn of Hardwarebeschleunigung and everything should work again.

yep that was it for me
