### ISSUE TITLE
Consensus container enabled: No   ,  Consensus container: absent

### ISSUE THREAD

**Issue by temos61** [docker/for-win#8246]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by temos61** [comment]
![Annotation 2020-08-28 014251](https://user-images.githubusercontent.com/66748752/91514008-fd1e5600-e8e5-11ea-83ac-ba38d3a8cb9f.jpg)

**Comment by degogarn** [comment]
I have the same running docker desktop

**Comment by temos61** [comment]
Ok

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by elizabethmunisi** [comment]
> 
> 
> ![Annotation 2020-08-28 014251](https://user-images.githubusercontent.com/66748752/91514008-fd1e5600-e8e5-11ea-83ac-ba38d3a8cb9f.jpg)

I have the same issue in my PI Network Node
![PI NODE TROUBLESHOOTING](https://user-images.githubusercontent.com/68707011/92301518-2b96d380-ef6d-11ea-8200-6c2abebba32c.gif)

**Comment by temos61** [comment]
so our node not working or what

**Comment by maheshc276** [comment]
Its not working.

**Comment by temos61** [comment]
why

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Devkeezhara** [comment]
![Untitled](https://user-images.githubusercontent.com/54124591/93026277-97cca380-f60d-11ea-8bf8-24242851ed66.png)
Same here and 
![Untitled](https://user-images.githubusercontent.com/54124591/93026317-d7938b00-f60d-11ea-8a5e-6d56ea3ae0d6.png)

**Comment by pawankulaura** [comment]
Below video on link is answer to all of your questions.
https://www.youtube.com/watch?v=QBDQeNVRNak
