### ISSUE TITLE
system_service_exception when try to build Boost C++ Libraries in Windows Container with process isolation

### ISSUE THREAD

**Issue by KHeresy** [docker/for-win#8248]
- [-] I have tried with the latest version of my channel (Stable)
  - [-] I have uploaded Diagnostics
  - Diagnostics ID: C70CCF7B-B2B0-4ADD-8190-A69A6B0288D5/20200828060834

### Expected behavior
Use Docker to build Boost C++ Libraries in Windows Container successfully.

### Actual behavior
When try to build Boost C++ Libraries in Windows Container with process isolation make host system BSOD.
The error: system_service_exception

### Information
  - Reproducible
  - Windows Version: Windows 10 2004 19041.450
  - Docker Desktop Version: 2.3.0.4
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
  1. Build a Docker image `builder` with the following Dockerfile
      ```
      # escape=`
      
      # Use the latest Windows Server Core image with .NET Framework 4.8.
      FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-2004
      
      # Restore the default Windows shell for correct batch processing.
      SHELL ["cmd", "/S", "/C"]
      
      # Download the Build Tools 2019 bootstrapper.
      ADD https://aka.ms/vs/16/release/vs_buildtools.exe C:\TEMP\vs_buildtools.exe
      ADD https://aka.ms/vs/16/release/channel C:\TEMP\VisualStudio.chman

      # Install Build Tools excluding workloads and components with known issues.
      RUN C:\TEMP\vs_buildtools.exe --quiet --wait --norestart --nocache `
          --channelUri C:\TEMP\VisualStudio.chman `
          --installChannelUri C:\TEMP\VisualStudio.chman `
          --installPath C:\BuildTools `
          --add Microsoft.VisualStudio.Workload.VCTools `
          --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
          --add Microsoft.VisualStudio.Component.VC.ATLMFC `
          --add Microsoft.VisualStudio.Component.Windows10SDK.18362

      # clean download files
      RUN del C:\TEMP\* /q
      
      # Start developer command prompt with any other commands specified.
      ENTRYPOINT c:\BuildTools\VC\Auxiliary\Build\vcvars64.bat && 
      ```

  2. Run the follow command in PowerShell (Require install 7-Zip to extract the .7z file)
      ```
      mkdir test
      cd test
      Invoke-Webrequest -Uri https://dl.bintray.com/boostorg/release/1.74.0/source/boost_1_74_0.7z -OutFile boost.7z
      & 'C:\Program Files\7-Zip\7z.exe' x boost.7z -y -oboost

      $mapping = (Get-Location).path + "\boost\boost_1_74_0:c:\code"
      docker run --rm -v $mapping -w "c:\code" --isolation process builder .\bootstrap.bat
      docker run --rm -v $mapping -w "c:\code" --isolation process builder .\b2 --toolset=msvc address-model=64 --stagedir=lib64 -j 12
      ```

3. Windows crash with a BSOD screen when building Boost.
    The error: system_service_exception

There is no problem If
- build without Docker
- use `--isolation hyperv`

**Comment by dmitriyse** [comment]
The same problem with my 600+ CSharp projects solution.
Looks like it's regression since 1909.
Windows 1909 - Works
Windows 2004 - BSOD
Windows 2009 - BSOD

**Comment by dmitriyse** [comment]
There is also no problem if the sources are copied inside the container filesystem. 
Reproduced only when sources are located at bind mounts.

**Comment by dmitriyse** [comment]
Tested Windows 21h1 insider (20231). And my project was compiled successfully without BSOD.
I even managed to get Windows 2009 (20h2) to work by replacing bindflt.sys with insider version (20231)

**Comment by KHeresy** [comment]
It looks that the problem not happen again after recently Windows and (or) Docker update.
