### ISSUE TITLE
I didn't see the "Advanced" and "Shared Drive" tab in Setting-Resources

### ISSUE THREAD

**Issue by vantrong1985** [docker/for-win#8258]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 9DB6F0F4-0506-4916-B46A-7D77485655D3/20200829021101

**Comment by stephen-turner** [comment]
You get different settings options depending whether you are using Windows containers, Linux containers with Hyper-V, or Linux containers with WSL 2. The documentation makes it clear which options pages you should expect in each case.
