### ISSUE TITLE
Unable to Start Docker

### ISSUE THREAD

**Issue by Arun89-28** [docker/for-win#826]
### Expected behavior

Start & Run Docker

### Actual behavior

Docker failes with error:
Docker hv-sock proxy (vsudd) is not reachable

### Information

Diagnostic ID:
A46B7C44-1089-4FB1-94DF-174B5086ECD8/2017-06-15_01-59-13

**Comment by jasonbivins** [comment]
HI @Arun89-28 
What version of Windows are you running on?
Is Windows running on a host, or a VM  ?

**Comment by Arun89-28** [comment]
Hi Jasonbivins,

My problem is fixed after doing windows update..
Thanks.
