### ISSUE TITLE
Docker Desktop does not run on Windows 10 Home 2004

### ISSUE THREAD

**Issue by ratio999** [docker/for-win#8271]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version: 10 home 2004, build 19041.450 
  - Docker Desktop Version: stable, the latest version
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no, it's being runned on the orignal windows os.

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
Insufficient information to triage this ticket: closing.
