### ISSUE TITLE
File changes not being detected with volumes

### ISSUE THREAD

**Issue by confusingbits** [docker/for-win#8276]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Using volumes, file watchers should detect file changes. This enables live development tooling common in web development.
### Actual behavior
The changes are no detected on windows, Manual restarts/rebuilds are required.

Possibly related to https://github.com/docker/for-win/issues/5530
### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

Windows 10 Pro Build 19042.487
Docker for Desktop 2.3.0.4 (46911)
Install is on native OS, Machine is a native machine. I use docker to virtualize environments for development

This is a long standing issue I've had for the better part of a year. I don't know that it ever was working, I only recently started working with docker on windows with this type of workflow. It works fine on my mac. 

The issue linked above said they needed new reproducible issues, so that what this is.
### Steps to reproduce the behavior

  1. clone: https://github.com/confusingbits/confusingbits.github.io
  2. change to gh-paged branch, docker-compose up the project.
     Dockerfile and docker-compose.yml are located here in the root
  3. Go to the served port to see the website locally.
  4. Make changes either to the Elm files or the markdown files in blog.
  5. Notice no rebuild is detected, website does not update with changes.

I've experience similar issues with other web projects like Nextjs and Yesod.

**Comment by michael-scheurer** [comment]
We are facing the same issue here.

**Comment by michael-scheurer** [comment]
In my case I solved the problem by **deactivating WSL 2** based engine.
Settings => General => "Use the WSL 2 based engine" => deactivate => Apply & Restart.

**Comment by stephen-turner** [comment]
If you are using WSL 2 but keeping your files in the Windows filesystem, this is expected because of the way that Microsoft have implemented WSL 2. We have documented it on our WSL 2 page https://docs.docker.com/docker-for-windows/wsl/ and recommend keeping your files in the WSL 2 filesystem instead.

**Comment by confusingbits** [comment]
Thanks @stephen-turner nice to know I'm not going mad. 😄
