### ISSUE TITLE
container can ping but not curl or wget (no internet)

### ISSUE THREAD

**Issue by Hish15** [docker/for-win#8284]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 0951261A-004C-4C91-854E-2391D26DAC88/20200831114634

### Expected behavior

```
docker run -it mcr.microsoft.com/windows/servercore:ltsc2019 powershell wget -o file github.com
```
This is supposed to download a file within the container and exit.

### Actual behavior
```
wget : Unable to connect to the remote server
At line:1 char:1
+ wget -o file github.com
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], We
   bException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

### Information
After configuring the proxy I can pull images.

On linux container every thing works just fine.
On windows container :

    - Ping : Does work when I'm using the office VPN only
    - powershell curl : Not working
    - powershell wget : Not working 

 - Windows Version: 1903
 - Docker Desktop Version: Docker version 19.03.12, build 48a66213fe

**Comment by Hish15** [comment]
```
docker run -d --rm -p 80:80 --name web mcr.microsoft.com/windows/servercore/iis:windowsservercore-1903
```
Works just fine : I can access the docker using a web browser at the address localhost.

**Comment by stephen-turner** [comment]
This looks very much like it is being blocked by something in your corporate network.

**Comment by Hish15** [comment]
@stephen-turner, it does.. 
Sadly my knowledge on the topics does not allow my to understand what, and who to bypass it.
Since it's working just fine for linux containers, there is hope.

**Comment by Hish15** [comment]
@stephen-turner, can you redirect me to some ressource to troubleshoot my settings.

**Comment by Hish15** [comment]
In my case the problem was McAfee not supporting `Endpoint Security 10.x (Windows)`.

Here's [an article on the behavior](https://ryanhayes.net/how-to-run-docker-windows-containers-with-mcafee-endpoint-security/)

**Comment by stephen-turner** [comment]
Glad you solved it and thanks for the update
