### ISSUE TITLE
Docker randomly doesn't publish port

### ISSUE THREAD

**Issue by mgorsk1** [docker/for-win#8319]
When I try to deploy any container and bind port to 9200, it's not published and viewable in Chrome or even in nestat. There are also other ports that are not working and it doesn't matter if I use docker-compose or docker run - the behavior is the same.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Any port number above 1000 I choose is published ok and service is accessible from within Chrome on Windows.

### Actual behavior

Port 9200 doesn't work, 9400 or 9700 does. There are no any other apps running. netstat -ltup doesn't list any app listening on 9200 port.

```
➜  log sudo netstat -ltup
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
```

### Information

* It's reproducible for me (see steps below)
* It's new but in the sense that I am new to the WSL 2 Docker Engine
* It appeared first time I approached Docker on WSL 2
* Windows Version: Windows 10 Pro 2004
* Docker Desktop version: 2.3.0.4 (46911) stable
* I am running bare metal Windows Pro that came along with my laptop

### Steps to reproduce the behavior

  1. docker run -it --rm -d -p 9200:80 --name web nginx
  2. sudo nestat -ltup

**Comment by simonferquel** [comment]
This might be because of Windows port reservation blocking docker to listen on 9200. Can you run `netsh int ipv4 show excludedportrange protocol=tc` ?

**Comment by mgorsk1** [comment]
Thanks for the reply @simonferquel , this is the output:

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\gorsk> netsh int ipv4 show excludedportrange protocol=tcnetsh int ipv4 show excludedportrange protocol=tc^C
PS C:\Users\gorsk> netsh int ipv4 show excludedportrange protocol=tc

Protocol tcp Port Exclusion Ranges

Start Port    End Port
----------    --------
      5357        5357
      6536        6635
      6636        6735
      6736        6835
      6953        7052
      7169        7268
      7269        7368
      7369        7468
      7469        7568
      7953        8052
      8053        8152
      8160        8259
      8260        8359
     50000       50059     *

* - Administered port exclusions.
```

**Comment by mgorsk1** [comment]
in fact today it seems that the issue no longer persists. assuming that it's related to the thing you mentioned I guess solution from here would work https://github.com/docker/for-win/issues/3171

**Comment by simonferquel** [comment]
Most likely yes

**Comment by mgorsk1** [comment]
ok, thanks for pointing me in the right direction, much appreciated !
