### ISSUE TITLE
 encountered an error during Pause: failure in a Windows system call: The request is not supported. (0x32)" 

### ISSUE THREAD

**Issue by bunny28may1988** [docker/for-win#832]
### Expected behavior
When i try to pause a container from my host, Error response from daemon: Cannot pause container 484b3e461d62db04d5f9875e4225ff1e8041c3e32ab0696eaff389697da349aa: container 484b3e461d62db04d5f9875e4225ff1e8041c3e32ab0696eaff389697da349aa encountered an error during Pause: failure in a Windows system call: The request is not supported. (0x32)

### Actual behavior
When i try to pause a container from my host, Error response from daemon: Cannot pause container 484b3e461d62db04d5f9875e4225ff1e8041c3e32ab0696eaff389697da349aa: container 484b3e461d62db04d5f9875e4225ff1e8041c3e32ab0696eaff389697da349aa encountered an error during Pause: failure in a Windows system call: The request is not supported. (0x32)
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...docker pause container
  2. ...

**Comment by MikhailTymchukDX** [comment]
I'm running docker on Windows 10, thus using Hyper-V isolation:
```
> docker version
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:48:20 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 23:03:03 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

Documentation states, that "On Windows, only Hyper-V containers can be paused.": https://docs.docker.com/engine/reference/commandline/pause/

However, when I try to pause a container, the following error occurs:
```
> docker pause 9511
Error response from daemon: Cannot pause container 9511660e526b437962a9a50504845d1d78262317a98f254ffc7475d2fb50c834: con
tainer 9511660e526b437962a9a50504845d1d78262317a98f254ffc7475d2fb50c834 encountered an error during Pause: failure in a
Windows system call: The request is not supported. (0x32)
```

Does it mean a bug or documentation inconsistency?

**Comment by VojtechFried** [comment]
Same problem here.

**Comment by desmondkung** [comment]
Same issue on Docker EE 17.06.2-ee-14, build 6345dd7
