### ISSUE TITLE
Docker 2.3.0.4 crashes on WIndows 10 1909 as VMWorkstation VM.

### ISSUE THREAD

**Issue by bascisco** [docker/for-win#8334]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 1052D4B8-3B4E-421B-B48B-DE9E8985747A/20200903160619

### Expected behavior

Expecting Docker to run out of the box

### Actual behavior

Crashes at start up

### Information

  - Windows Version: Windows 10 1909 (latest updates)
  - Docker Desktop Version: 2.3.0.4
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: yes
Windows 10 1909 in VMworkstation. Other apps run like SecureCRT ect run fine. 
[log.txt](https://github.com/docker/for-win/files/5169842/log.txt)
[install-log.txt](https://github.com/docker/for-win/files/5169843/install-log.txt)
[log.2.txt](https://github.com/docker/for-win/files/5169844/log.2.txt)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by bascisco** [comment]
another crash report: 1052D4B8-3B4E-421B-B48B-DE9E8985747A/20200904071821

**Comment by stephen-turner** [comment]
Docker Desktop is not support in a virtualised environment. It might work or it might not, but it's outside our control, it depends whether the outer hypervisor supports nested virtualisation.

**Comment by bascisco** [comment]
Hello Stephen, thank you for looking into this.  One thing I found is that for the VM you indeed need to enable Virtualized Intel VT-x/EPT or AMD-v/RVI. Which I didn't have before I installed docker for Windows on that Windows 10 VM.. After enabling this I got finally Docker For Windows running. Brgds, Bas.

**Comment by stephen-turner** [comment]
Good, thanks for the feedback.
