### ISSUE TITLE
Switching to Linux Containers fails

### ISSUE THREAD

**Issue by schmik** [docker/for-win#8339]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: B24501B2-F317-4D7A-87D0-441FCD9F0125/20200904065735

### Expected behavior

DD set to Windows containers. Switching to Linux containers... Supposed to work.

### Actual behavior

Switching from Windows to Linux containers does not work, msg: "An error occured".

Msg-Text: [docker_desktop-error-20200904-01.txt](https://github.com/docker/for-win/files/5173236/docker_desktop-error-20200904-01.txt)

### Information

  - Windows Version: 20H2 (Build 19042.487) with WSL2 and 20200810 build of Ubuntu 20.04 LTS
  - Docker Desktop Version: 2.3.0.4 (46911) 
    - channel: stable
    - Engine: 19.03.12
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No.

### Steps to reproduce the behavior

  1. Start Docker Desktop (Windows Container as default)
  2. Try switch to Linux containers via tray menu.
  3. Fail :-(

**Comment by schmik** [comment]
I am not sure whether https://github.com/microsoft/WSL/issues/4929 is related in any way. WSL2/Ubuntu fails as reported over there and has been working before. I am not able to reboot right now, but will try the workarounds mentioned in WSL-issues and report again.

**Comment by schmik** [comment]
More to tell:

- Windows, fresh reboot
- Fire up (ubuntu in) WSL2 myself (via Windows Terminal)
- Start Docker Desktop (is set to Windows Containers)
- Switch to Linux Containers: WORKING.

- Windows, fresh reboot
- ~~Fire up (ubuntu in) WSL2 myself (via Windows Terminal)~~
- Start Docker Desktop (is set to Windows Containers)
- Switch to Linux Containers: **NOT** WORKING.

So it looks like: If WSL2 has not been initialized/brought up before, DD fails to bring it up itself. HOwever, if WSL2 is already initialized, everything works as expected.

**Comment by StefanScherer** [comment]
The 0xffffffff error looks like a WSL 2 error. The logs show `Failed to deploy distro`, this is when we run `wsl --import docker-desktop ... --version 2`

**Comment by schmik** [comment]
> The 0xffffffff error looks like a WSL 2 error. The logs show `Failed to deploy distro`, this is when we run `wsl --import docker-desktop ... --version 2`

Sorry, I did not read the diagnostics before submitting. But yes, this 0xffffffff error is exactly what WSL2 is telling me when I try to start WSL2 myself after Docker Desktop failed to switch.

On the other hand, if I do "open" WSL2 before starting Docker Desktop, your `wsl --import docker-desktop ... --version 2` seems to work. I agree that it looks like problem is more on WSL2-side than yours (import only working if some magic happened beforehand).

@StefanScherer Would you advise to close this issue?

**Comment by StefanScherer** [comment]
I wonder why Docker Desktop always wants to import the docker-desktop distro after your fresh reboot. It doesn't do that if the distro already exists. 🤔
