### ISSUE TITLE
Docker Edge for Win10 hangs on upgrade.

### ISSUE THREAD

**Issue by postwait** [docker/for-win#834]
### Always hangs at "Stopping VM"

Left it for 24 hours (twice).  Leaves docker inoperable post task ending.  Downloading a fresh install and installing it (which requires a reboot) "fixes" the issue.  Except twice now (with two different versions) this has happened.  And the required reboot makes the workaround a bit useless.

### Information

  - Docker will not launch now until reboot.
  - Windows 10 Pro 10.0.15063 Build 15063
  - Surface Pro 4
  - Current docker version is as follows.
```
 Version:      17.06.0-ce-rc2
 API version:  1.30
 Go version:   go1.8.1
 Git commit:   402dd4a
 Built:        Wed Jun  7 10:01:32 2017
 OS/Arch:      windows/amd64
```
### Steps to reproduce the behavior

  1. install docker
  2. run any docker container
  3. wait for upgrade to be available.
  4. perform upgrade when prompted.

**Comment by jasonbivins** [comment]
Hi @postwait 
We just released an update today, can you check to see if you get the same error?

When it hangs like that, can you open  Hyper-V manager to see if the MobyLinuxVM is actually still running?

**Comment by postwait** [comment]
Last time... Moby was still running. Manually stopping it didn't unstick the upgrade. I'll try an upgrade later.

**Comment by jasonbivins** [comment]
Hi @postwait   Have you gotten a chance to try the latest version?  We released an update on the Edge channel today.

**Comment by postwait** [comment]
This all works for me now.  Latest windows, latest Docker ce
