### ISSUE TITLE
Cannot start docker daemon/ui on Win 10 Pro

### ISSUE THREAD

**Issue by gabrielschmith** [docker/for-win#835]
### Expected behavior
Docker should start

### Actual behavior
Object reference not set to an instance of an object.

![image](https://user-images.githubusercontent.com/10456683/27310463-cfb47466-5530-11e7-9114-b5baf44924e7.png)

### Information
> Version: 17.03.1-ce-win12 (12058)
> Channel: stable
> Sha1: d1db12684b33b778cfc3012e92959e50eb486fcd
> Started on: 2017/06/19 20:36:27.744
> Resources: C:\Program Files\Docker\Docker\Resources
> OS: Windows 10 Pro
> Edition: Professional
> Id: 1703
> Build: 15063
> BuildLabName: 15063.0.amd64fre.rs2_release.170317-1834
> File: C:\Users\gabrielschmith\AppData\Local\Docker\log.txt
> CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
> You can send feedback, including this log file, at https://github.com/docker/for-win/issues
> [20:36:27.853][GUI            ][Info   ] Starting...
> [20:36:28.188][GUI            ][Error  ] Referência de objeto não definida para uma instância de um objeto.
> [20:36:31.905][ErrorReportWindow][Info   ] Open logs

**Comment by jasonbivins** [comment]
Hi @gabrielschmith 
Can you share the diagnostic ID that you received in the error window?

**Comment by gabrielschmith** [comment]
Hi @jasonbivins
Where I can get this diagnostic ID?

**Comment by gabrielschmith** [comment]
Hi @jasonbivins
Apparently the version 17.06.0-ce-win18 (12627), Channel: stable d9b6651, solved the problem.

**Comment by jasonbivins** [comment]
Hi @gabrielschmith   Thanks for letting me know.  I'll go ahead and close this issue then, but please let me know if it pops back up
