### ISSUE TITLE
Docker Desktop crash on windows startup - restart normally works

### ISSUE THREAD

**Issue by allanbarklie** [docker/for-win#8359]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
80BF7F34-05E5-4A73-8CBA-640A107F6666/20200904085401
80BF7F34-05E5-4A73-8CBA-640A107F6666/20200906155642

### Expected behavior
No error on startup

### Actual behavior
Quickly after logging in on a fresh boot Docker desktop reports a crash and generates a report

### Information

Problem is new - I have been using varous versions for a long time.
Has happened twice on first boot of the day - it has been ok on restart.

Crash reports uploaded see ID above.

  - Windows Version: 10.0.19041 Build 19041
  - Docker Desktop Version: 2.3.0.4
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: directly on a dell laptop

### Steps to reproduce the behavior
Have docker desktop set to start automatically.
Have a wsl2 distro set as default.
Turn on PC for first time in the day.

**Comment by dmascord** [comment]
Hi guys,

I am having the same issue, 09EB5211-0048-40F4-8C92-CC00BF0B361B/20200907233708 sent through.

Cheers,

Damien
