### ISSUE TITLE
dynamic memory

### ISSUE THREAD

**Issue by netw0rm** [docker/for-win#836]
how can i use the  dynamic memory  on hyperv.

**Comment by friism** [comment]
You can change the setting in hyper-v manager, but it's not supported and the setting change will go away if Docker for Windows is reset or re-installed. 

cc @rn

**Comment by rn** [comment]
this is a dup of several others, including https://github.com/docker/for-win/issues/521

**Comment by bericoberin** [comment]
NOTE: Docker automatically restarts if you change that setting now....

**Comment by jasonbivins** [comment]
this is a dupe issue - closing
