### ISSUE TITLE
Failed to set version to docker-desktop: exit code: -1

### ISSUE THREAD

**Issue by bms-hub** [docker/for-win#8360]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:A691A747-CD4D-444B-B9C8-CA9CA6275F7C/20200906161141

### Expected behavior
The Docker should start
### Actual behavior
The Docker is unable to start
### Information

Docker Version: 2.3.0.4 (46911)
Channel: stable
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 2004
Build: 19041

### Steps to reproduce the behavior

  1. Open Docker Desktop
  2. ...

**Comment by bms-hub** [comment]
It finally worked.

1- I disabled WSL on Windows Features;

2- I restarted the computer;

3- I started Docker only with Hyper-V, so Docker Desktop worked;  :D

4- I closed the Docker Desktop;

5- Activate WSL again;

6- I restarted the computer to install WSL again;

7- Now the Docker starts normally.

**Comment by solxnp** [comment]
> It finally worked.
> 
> 1- I disabled WSL on Windows Features;
> 
> 2- I restarted the computer;
> 
> 3- I started Docker only with Hyper-V, so Docker Desktop worked; :D
> 
> 4- I closed the Docker Desktop;
> 
> 5- Activate WSL again;
> 
> 6- I restarted the computer to install WSL again;
> 
> 7- Now the Docker starts normally.

Thank you very much, follow your way, now it can be used normally
