### ISSUE TITLE
 Virtual Machine Management Service failed to start the virtual machine 'DockerDesktopVM'

### ISSUE THREAD

**Issue by mandalkaushikPFG** [docker/for-win#8369]
We're closing this issue because it doesn't contain enough information for us to investigate the problem.
If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-windows/troubleshoot?

_Originally posted by @docker-desktop-robot in https://github.com/docker/for-win/issues/8340#issuecomment-687543769_

**Comment by mandalkaushikPFG** [comment]
Hi Team,
I can only perform diagnostics only when the Docker is up and running. I brought this before the community because the application is itself not starting.
Please see the issue I am facing here:
![Docker Issue](https://user-images.githubusercontent.com/63035819/92359988-bad8ee00-f109-11ea-98b8-3aa953ed1755.jpg)

Furthermore, I am also attaching logs file for reference.
[log[1].txt](https://github.com/docker/for-win/files/5181645/log.1.txt)

Please help me out here and let me know if anything else is required.

**Comment by stephen-turner** [comment]
The message says that the Docker VM couldn't start because Hyper-V is not running. Have you enabled all the prerequisites? Can you start other Hyper-V VMs?

**Comment by mandalkaushikPFG** [comment]
Can you share some documentation for that @stephen-turner ?

**Comment by stephen-turner** [comment]
See System Requirements at https://docs.docker.com/docker-for-windows/install/

**Comment by mandalkaushikPFG** [comment]
@stephen-turner,
I can to know that nested virtualization is the issue in my case since I am trying to access Docker from a VDI.
Can you help in this regards?

**Comment by stephen-turner** [comment]
I can give advice but unfortunately it's not under our control. It depends whether Hyper-V can run in the VM. You may be able to configure the outer hypervisor to permit nested virtualisation, but we have no control over that from inside the VM. If you can get Hyper-V running, the rest will probably work although we don't officially support this scenario.
