### ISSUE TITLE
Docker daemon port 2376 not working

### ISSUE THREAD

**Issue by whgibbo** [docker/for-win#837]
### Expected behavior
Recently made the jump from **Docker Toolbox** to **Docker For Windows**, the build system that I used is Gradle and makes use of the Gradle plugin called [gradle-docker-plugin](https://github.com/bmuschko/gradle-docker-plugin).  After the switch it failed to build.

### Actual behavior
Daemon is not configured for TLS on port 2376

### Information
I've raised an issue also with gradle-docker-plugin [here](https://github.com/bmuschko/gradle-docker-plugin/issues/394)

### Steps to reproduce the behavior

  1. https://127.0.0.1:2376/v1.20/version  returns an error
  2. http://127.0.0.1:2376/v1.20/version  returns information once the option **Expose daemon on tcp://localhost:2375** without TLS is enabled.

**Comment by friism** [comment]
As mentioned, listening on 2376 is not very secure which is why it's not enabled by default. The opt-in behavior was adopted to mitigate the security problem.
