### ISSUE TITLE
docker utilizes only one processor group

### ISSUE THREAD

**Issue by sebhaub** [docker/for-win#838]
I just asked this question at https://github.com/moby/moby/issues/33743 but this seems to be the wrong place, so i repost this issue here. 

**Description**

When using docker for windows server on a machine with multiple processor groups - for example by using more than one physical processor - docker only utilizes one of them.

For instance on a machine with 2 Intel Xeon Processors (each with 20 logical cores) docker info only shows a total of 20 cores. 
This is even worse on a intel xeon phi with 256 logical cores where only 64 are detected. 

**Steps to reproduce the issue:**
run docker for windows server on a machine with multiple processor groups

**Describe the results you received:**
only one processor group is detected

**Describe the results you expected:**
all processor groups are detected and can be used

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ee-3
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 19:31:22 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ee-3
 API version:  1.27 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 19:31:22 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
docker info
 Containers: 17
   Running: 0
   Paused: 0
   Stopped: 17
 Images: 2
 Server Version: 17.03.1-ee-3
 Storage Driver: windowsfilter
 Windows:
  Logging Driver: json-file
 Plugins:
   Volume: local
   Network: l2bridge l2tunnel nat null overlay transparent
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 14393 (14393.1066.amd64fre.rs1_release_sec.170327-1835)
 Operating System: Windows Server 2016 Standard
 OSType: windows
 Architecture: x86_64
 CPUs: 20
 Total Memory: 191.9 GiB

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical machine

**Comment by jasonbivins** [comment]
Hi @sebhaub 
can you send me the output of the systeminfo command on that machine?  I'm trying to reproduce this, but haven't been able to so far.  I'd like to try and replicate your setup.  I have noticed that systeminfo counts processors, whereas docker info counts CPU's

**Comment by sebhaub** [comment]
Hi @jasonbivins 
thanks for your response. Here is the output (stripped down to the relevant parts)

````
OS Name:                   Microsoft Windows Server 2016 Standard
OS Version:                10.0.14393 N/A Build 14393
OS Manufacturer:           Microsoft Corporation
System Manufacturer:       HP
System Model:              ProLiant BL460c Gen9
System Type:               x64-based PC
Processor(s):              2 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 79 Stepping 1 GenuineIntel ~1198 Mhz
                           [02]: Intel64 Family 6 Model 79 Stepping 1 GenuineIntel ~1198 Mhz
BIOS Version:              HP I36, 05.05.2016
Total Physical Memory:     196.478 MB
Available Physical Memory: 189.091 MB
Virtual Memory: Max Size:  401.278 MB
Virtual Memory: Available: 390.218 MB
Virtual Memory: In Use:    11.060 MB
````

using the `GetLogicalProcessorInformationEx` Windows API Method (https://msdn.microsoft.com/de-de/library/windows/desktop/dd405488(v=vs.85).aspx) it can be seen that we have 2 Numa Nodes / 2 Processor Groups on this machine, each with 10 physical und 20 logical cores.

looking forward to your reply :-)

**Comment by friism** [comment]
@sebhaub can you change the settings for the Moby VM in Hyper-V manager?

Also, do you need more than 20 CPUs when using Docker for Windows?

**Comment by sebhaub** [comment]
@friism 
when using hyper-v isolation it is possible to use all available logical cores. anyway, I would like to use _process_ isolation mode to minimize resource overhead and optimize speed. maybe I pointed to the wrong direction by posting this issue at the moby repository initially. the issue is related to isolation mode "process".

and yes, I do need more than 20 cores... imagine a build-server with multiple concurrent runners or other heavily parallelized applications.

**Comment by friism** [comment]
Oh, I'm sorry - then the issue is correctly placed on moby/moby. You should re-open and ping `jhowardmsft` and `darrenstahlmsft`.

Please accept my apologies.

**Comment by sebhaub** [comment]
@friism : no problem at all :-) Hopefully the issue is placed correctly now 
I close this one (hopefully permanently) :-)

discussion continues [here](https://github.com/moby/moby/issues/33743)
