### ISSUE TITLE
NFS does not work on WLS but used to work on Hyper-V (MobyLinux)

### ISSUE THREAD

**Issue by Herrick19** [docker/for-win#8382]
Hi,

Before I updated to windows 10 (2004), I was using docker-compose to mount  a NFS drive using this:

version: '3.7'
services:
  php-fpm:
    image: ezmax.docker.php-fpm:latest
    container_name: php-fpm
    volumes:
      - internal.ca-central-1:/content/assets/
volumes:
  internal.ca-central-1:
    driver_opts:
      type: "nfs"
      o: "addr=10.1.19.96,nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2"
      evice: ":/docker/ezmax.docker.content.documentation.public/assets/"

It always worked like a charm.

When I updated to windows 2004, Docker suggested I switch to WSL (Windows Subsystem for Linux) which I did. It then asked by to install a KB to update the Linux and everything worked well. I have about 40 containers and they all work perfectly except those that have a NFS mount.

When I try to launch the docker-compose, I get these errors:

Creating php-fpm ... error

ERROR: for php-fpm  Cannot start service php-fpm: error while mounting volume '/var/lib/docker/volumes/documentation-internal_internal.ca-central-1/_data': failed to mount local volume: mount :/docker/ezmax.docker.content.documentation.public/assets/:/var/lib/docker/volumes/documentation-internal_internal.ca-central-1/_data, data: addr=10.1.19.96,nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2: invalid argument

ERROR: for php-fpm  Cannot start service php-fpm: error while mounting volume '/var/lib/docker/volumes/documentation-internal_internal.ca-central-1/_data': failed to mount local volume: mount :/docker/ezmax.docker.content.documentation.public/assets/:/var/lib/docker/volumes/documentation-internal_internal.ca-central-1/_data, data: addr=10.1.19.96,nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2: invalid argument
ERROR: Encountered errors while bringing up the project.

I've searched the web, docker forums and google but couldn't find anyone talking about NFS on WSL so I don't even know if it's possible or not to run NFS on WSL.

Could you clarify if:
1- NFS is supported on WSL ?
2- If so, am I facing a bug or a configuration problem.

I can send logs or more details if it can help.

Thanks in advance

**Comment by stephen-turner** [comment]
I'm not sure. Do the NFS mounts work in plain WSL 2 outside the context of a container?
