### ISSUE TITLE
Docker issue on switching to Windows Mode

### ISSUE THREAD

**Issue by Shiva145** [docker/for-win#8385]
I am trying to switch docker to windows. I am experiencing the below error.

I tried reinstall and install it again. Also ran in admin mode still same error. Pleas advise

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Shiva145** [comment]
Diagnostic Id  = 9F7D78FD-97B1-4A0D-8661-7C48E460ABD3/20200908025713

**Comment by jimbo8098** [comment]
What was the expected and actual behavior? I've had some issues in the past switching to windows containers (which I assume is what you mean here) but usually there is a specific message shown. In my case it referred to Windows Feaures.
