### ISSUE TITLE
Stock Windows 2019 and new Docker install won't start.

### ISSUE THREAD

**Issue by bsbaixo** [docker/for-win#8395]
Hi,
Total Docker Noob here. I have created an EC2 server on AWS (Windows 2019). Installed Docker Desktop. Docker tries to start, occasionally I can get to the docker Dashboard if I click fast enough. It always ends in an error.

Thanks,
Brian

  - [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
It should start
### Actual behavior
It tries to start but always ends in an error. Some files can't be found.
### Information

  - Windows Version: 2019 (AWS EC2)
  - Docker Desktop Version: Newest stable
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: AWS EC2

### Steps to reproduce the behavior

  1. Create AWS EC2 instance (Windows 2019)
  2. Do updates
  3. Install Docker Desktop
  4. Start Docker.
  5. Crash

**Comment by bsbaixo** [comment]
So, after reviewing more docs, I guess I kept seeing what Docker does run on and nothing that states what it doesn't run on. I am trying this on Windows 2019 server. I guess that won't work?
I'm no programmer but that seems like a pretty easy add to the installer to check? idk
Brian

**Comment by stephen-turner** [comment]
Unfortunately Docker Desktop is not supported in a virtualised environment. It might work or it might not, but it's out of our control as it depends whether the outer hypervisor supports nested virtualisation.

**Comment by bsbaixo** [comment]
ok,

thanks for your time,
Brian
