### ISSUE TITLE
Windows 10 slow ring (beta), 20H2 (19042.508) issues with Docker WSL2

### ISSUE THREAD

**Issue by OzKron** [docker/for-win#8404]
- [x] I have tried with the latest version of my channel (Both **stalbe** and **Edge**)
- [x] I have uploaded Diagnostics

  - Diagnostics ID: AFE27455-5407-4D65-A449-1D29447359D2/20200909070146

### Expected behavior
Docker should start running and the daemon should run, using WSL2

### Actual behavior
The docker daeomon crash with error 

[Engines           ][Error  ] Start failed with Failed to deploy distro docker-desktop to C:\Users\user\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: The remote procedure call failed.

I can reproducde it every time
Tried mulitple times to install/uninstall docker descktop + reboot to the machine
Never had this issue before, only after updating to latest windows 10 slow ring (beta) version, before (also using windows 10 beta/slow ring) all went and worked fine

Windows version is 20H2 (19042.508)
Dokcer version is 2.3.0.4 (46911)
Running on my desktop, not a cloud/vmware

Steps to reproduce the behavior
  1. install lastest windows 10 slow ring beta 64bit
  2. Make sure you have WSL2 enables
  3. run Docker, should crash at start

**Comment by StefanScherer** [comment]
Thanks for the report. I have a 20H2 machine and could start Docker Desktop 2.3.0.4.
It looks like you have the problem we also saw from time to time in our CI: https://github.com/microsoft/WSL/issues/4998 and it more looks like a misbehavior of WSL 2 itself.

**Comment by OzKron** [comment]
Sorry, tried and still same issues, also I hadn't this one before the new windows 10 update (and seem like many open bugs on it since yesterday)

**Comment by OzKron** [comment]
Also, it isn't just 20H2, it is the latest one, patched from yesterday
(or today morning)

**Comment by StefanScherer** [comment]
OK, well the machine I'm testing on also has the September updates 19042.508 🤔

**Comment by OzKron** [comment]
Yep, I also tried all the things you told me in the link + doing  restart-service *docker* from a powershell
Nada 👎

**Comment by Wiciaki** [comment]
I can also confirm that starting with this build, I can no longer launch Docker (same error message)
Definitely looks like a faulty Windows update and not an error on the Docker end.
I've tried some other WSL features like starting a distro and everything else seems to look fine

**Comment by OzKron** [comment]
I agree, but still an updated needed, I can't revert my windows, and need Docker to work :( 
Probably just a missing or changed RPC function or a like

**Comment by chadbrewbaker** [comment]
In addition to the Docker crash, My Ubuntu 20.04 LTS WSL2 (which lives on D: not C:), is also hosed this morning giving:
"The remote procedure call failed.
Press any key to continue..." 

Sigh. This is after several WSL2 image corruptions last weekend.  Going to have to start a cron job that backs them up to zipfiles each night.

**Comment by flashflexpro** [comment]
Yeah, Windows 10 Pro OS build 19042.508 broke WSL, PS :   

C:\WINDOWS\system32> wsl
The remote procedure call failed.

**Comment by dutsik** [comment]
I think it relates to KB4571756 update. when i uninstalled it, wsl and docker seemed to work as before.

**Comment by OzKron** [comment]
Yep, seem an issue with KB4571756 , hope Docker team will fix it up so all will work fine, even when it is installed

**Comment by Hazmi35** [comment]
Same issues here, Hyper-V VMs also can't start normally, `vmwp.exe` seems to be broken as I see from Event Viewer it crashed every I start a Hyper-V VMs or starting WSL2
![image](https://user-images.githubusercontent.com/32807631/92664374-023fc400-f32e-11ea-9de2-00506ea2d9c9.png)

**Comment by domanskyi** [comment]
With Docker Edge version all seems fine

**Comment by pelagaggi** [comment]
> hat starting with this build,

I have the same issue. I am unable to downgrade my windows, would anyone know a workaround for 20H2 (OS Build 19042.1789).

**Comment by Hazmi35** [comment]
> > hat starting with this build,
> 
> I have the same issue. I am unable to downgrade my windows.
> Would anyone know a workaround for 20H2 (OS Build 19042.1789) ?

Have you tried updating? if updating doesn't work for you try this https://github.com/microsoft/WSL/issues/5880#issuecomment-691367294
