### ISSUE TITLE
Problem while starting docker

### ISSUE THREAD

**Issue by EnigmaAS** [docker/for-win#8410]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: EEFE1987-3622-4B88-AF3A-0A6C14F2AE81/20200909111155

### Expected behavior
Working docker.

### Actual behavior
Not working docker. Not even imager, nor containers available.

### Information

  - Windows Version: 10 -> fresh install of 2004.
  - Docker Desktop Version: 2.3.0.4
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Freshly switched from Hyper-V to WSL and BOOM !!!

### Steps to reproduce the behavior

  1. update windows 10.
  2. docker started to notice that WSL is available - asked for the usage -> I allowed.
  3. install the wsl from officials.
  4. Run docker -> boom !!!

**Comment by JMackCo** [comment]
https://github.com/docker/for-win/issues/8426
