### ISSUE TITLE
Distro broken

### ISSUE THREAD

**Issue by succeedmr123** [docker/for-win#8411]
It simply crashes, with this log detail in the window:

WSL distro stopped while waiting for Lifecycle server.
  >Stdout:
⇨ http server started on /run/guest-services/wsl2-bootstrap-expose-ports.sock
⇨ http server started on /run/guest-services/wsl-cross-distro.sock
execing /sbin/init
  >Stderr:
2020/09/09 10:59:30 resolving /mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-wsl-cli.iso...
2020/09/09 10:59:31 already in cache!
2020/09/09 10:59:32 resolving /mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-for-wsl.iso...
2020/09/09 10:59:32 already in cache!
2020/09/09 10:59:34 resolving /mnt/host/c/Program Files/Docker/Docker/resources/docker.iso...
2020/09/09 10:59:34 already in cache!
time="2020-09-09T10:59:35Z" level=info msg="dialing Unix domain socket /run/guest-services/wsl2-expose-ports.sock for data connection"
time="2020-09-09T10:59:35Z" level=info msg="unable to connect data on Unix domain socket /run/guest-services/wsl2-expose-ports.sock: dial unix /run/guest-services/wsl2-expose-ports.sock: connect: no such file or directory. Is the server restarting? Will retry in 1s."
Error: input/output error
2020/09/09 10:59:36 input/output error

  - [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [X ] I have uploaded Diagnostics
  - Diagnostics ID:

82441F76-0F18-4453-9B59-2DD029B1C8AB/20200909105955

### Expected behavior
To function.
### Actual behavior
Distro crashes. is broken.
### Information
It crash after trying to start up

  - Windows Version: v1909, +WSL2 backport patch
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
No, not virtual, "on metal"

### Steps to reproduce the behavior

No need, it just crashes.
  1. ...
  2. ...

**Comment by jakebrinkmann** [comment]
Same. A crash report has been uploaded with diagnostic id: 
`0569C610-C1CC-403E-9248-D57E4C7722B6/20200909230734`

**Comment by scrhall** [comment]
Same, Docker failed to start 
E9AAE698-9739-4557-B1A2-4892248CF9E5/20200914111601

**Comment by aljiru** [comment]
Same here. Crash report
9591055E-0380-4267-A0AA-513B939EE729/20200929072505

I'm considering reseting to factory defaults to see if it works.
