### ISSUE TITLE
System.InvalidOperationException: Failed to deploy distro docker-desktop to C:\Users\HP\AppData\Local\Docker\wsl\distro: exit code: -1  stdout: Element not found.

### ISSUE THREAD

**Issue by akolchin** [docker/for-win#8416]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 1FA98D0A-ECCF-4A27-906C-46CBB477D20B/20200909151054

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by JMackCo** [comment]
I have had this issue now for three days. With 3 complete OS fresh installs.

**Comment by JMackCo** [comment]
https://github.com/docker/for-win/issues/8426

**Comment by eacevedof** [comment]
same issue here
