### ISSUE TITLE
Docker for Windows 17.03.1-ce ignores Registry Mirrors setting

### ISSUE THREAD

**Issue by stefan-schilling** [docker/for-win#842]
### Description

We have a company private Docker Repo (Nexus3), which shall act as a local Docker cache (+ company internal Docker images repo).
It works smoothly using
docker pull maven-repository3.company:5000/wasa-epa:6.4.11

Now, I don't want people to always type in the repository address, since it is error prone compared to set it up once.
Therefore, I added a "registry-mirrors" and "insecure-registries" (it uses a self-signed certificate) configuration option using Docker - Settings - Daemon.
Sadly, I get the following output:

C:\Users\stsc>docker pull wasa-eap:6.4.11-0
Error response from daemon: repository wasa-eap not found: does not exist or no pull access

C:\Users\stsc>

I have not been able to convince Docker of printing the URLs being used.

### Expected behavior

1. Image is pulled from the private repository since the private repository's url is provided as a registry-mirror
2. docker provides the URLs used for pulling (requires providing --verbose flag - I know, this is a different story)

### Actual behavior
Image cannot be pulled from private repository when omiting the private repository's url

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ensure, pulling from private repository works using docker pull COMPANY_REPO/image
  2. add registry-mirrors setting using Docker - Settings - Daemon (add insecure-registries setting, if need due to a self-signed certificate)
  3. try to pull another image from the same private repository using docker pull image

**Output of docker version:**

Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true

**Output of docker info:**

Containers: 8
 Running: 0
 Paused: 0
 Stopped: 8
Images: 242
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 168
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.27-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.837 GiB
Name: moby
ID: OKZB:JBCD:BX55:D3LZ:Q4KT:CYSU:OGSA:7N5Q:YRS3:JI5C:UT7C:GKY7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 22
 System Time: 2017-06-21T09:40:07.6902799Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 maven-repository3.company:5000
 127.0.0.0/8
Registry Mirrors:
 maven-repository3.company

Docker runs on a German-speaking Windows 10 pro, installed on the machine's hardware (no VM).

**Comment by jasonbivins** [comment]
Hi @stefan-schilling 
Can you please share a screenshot, or copy/paste the text you have in the Daemon settings?

**Comment by stefan-schilling** [comment]
Hi,
sure, here you go:

![docker-settings1](https://user-images.githubusercontent.com/27948730/27676394-05e5733a-5cae-11e7-973f-e2494fce3b60.PNG)

**Comment by Hanfrey** [comment]
We have exactly the same problem, also with a german windows 10 pro. (except that we dont use insecure registries).

**Comment by awpya** [comment]
Same problem with Version 17.06.0-ce-win19 (12801) and registry mirror.  But it could be fixed by adding protocol to server:port. In our case https://

**Comment by stefan-schilling** [comment]
I just tried it by adding the protocol to both settings (Registries mirrors and Insecure registries). No change here, Docker still finds the images when providing the repository's address upon the pull call only.

Note: I updated Docker to version 17.06.0-ce-win19 (12801) before trying.

**Comment by lucastheisen** [comment]
I have the same problem, but with one difference...  The `Registry Mirrors` section is not present in my output from `docker info` even though it is configured in the _Settings... -> Daemon_ tab:
```
PS C:\Temp> docker info
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 728
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 6homqqhyx9o44ui1o3iam7bs1
 Is Manager: true
 ClusterID: ozjtp1c0pbp6survvupdki4fi
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 192.168.65.2
 Manager Addresses:
  192.168.65.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.31-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: moby
ID: J3M7:ZYBD:MEAD:DTOG:BLZL:3UZ5:NFNW:E4G2:HZ6O:TNKV:XAVK:IPEH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 30
 Goroutines: 134
 System Time: 2017-07-18T11:02:12.8293233Z
 EventsListeners: 0
Http Proxy: myproxy.my.domain:80
Https Proxy: myproxy.my.domain:80
No Proxy: my.domain,localhost,127.0.0.1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 myregistry.my.domain:8200
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by ebriney** [comment]
@lucastheisen, did you try
```
{
  "registry-mirrors": [
    "http://myregistry.my.domain:8200"
  ],
  "insecure-registries": [
    "http://myregistry.my.domain:8200"
  ],
  "debug": true,
  "experimental": true
}
```

it should work and listed in `docker info`

**Comment by lucastheisen** [comment]
@ebriney , adding the scheme to the `host:port` made it show up in `docker info`, but I don't think they are actually getting used.  My real problem is that our corporate VPN causes downloads of large external files to hang intermittently.  So using the internal mirror should alleviate that issue.  However, the issue persists...  Is there a way to see what url a `docker run` is using to fetch an image?  Also, if the scheme is supposed to be present in these config values, then we should probably change the `eg: mysite.com:88` text in the dialog box...

**Comment by ebriney** [comment]
@lucastheisen : unfortunately, it is not in the daemon log, this must be in your registry mirror log though if you have access to it

**Comment by lucastheisen** [comment]
@ebriney, when I use the mirror _explicitly_ (`docker pull myregistry.my.domain:8200/alpine`), it works without issue...  So I doubt the error is on the mirrors log.  It just seems like my docker daemon is ignoring the setting, and attempting to go directly to dockerhub...

**Comment by Tzrlk** [comment]
@lucastheisen: Seems to be fixed in `17.06.1-ce-rc1` at least. The `https://` prefix is necessary, but as soon as I added that and restarted the daemon, pull started connecting to the mirror as expected.

**Comment by lucastheisen** [comment]
@Tzrlk , i just got the update to `17.07.0-ce-rc1` and can confirm that when using `http://` in the docker registry settings it appears to have resolved my issue.  Thank you.

**Comment by vtintillier** [comment]
I confirm that by adding https://, it now works, both on 17.05 and 17.06. Would be nice to update the placeholder string.

**Comment by stefan-schilling** [comment]
I tried it just now, but isn't working for me. Currently, my problem is as follows:
The mirror registry is located at https://maven-repository3.kaufland/nexus.

Setting 
https://maven-repository3.kaufland:443 as Registry mirror makes it show up using docker info.
But setting the correct address (I tried both)
a. https://maven-repository3.kaufland/nexus
b. https://maven-repository3.kaufland/nexus/
makes the setting disappear from docker info. Is there any trick how to set the correct URL including a context root? It cannot be that surprising, even the docker registry is located at https://index.docker.io/v1/...

Once this gets fixed, I will try again.

Thanks a lot.
Stefan

**Comment by Tzrlk** [comment]
Not sure how true this still stands, but you need to serve the repository
from the context root. Docker has some silly restrictions on repository
urls because of how they get referenced in tags.
Having something at https://maven-repository3.kaufland/nexus would require
any images to be tagged
"maven-repository3.kaufland/nexus/reponame/imagename:imagetag", which
wouldn't get interpreted properly. When it's running on the root of a
subdomain, you get
"docker.maven-repository3.kaufland/reponame/imagename:imagetag" or on a
port: "maven-repository3.kaufland:6555/reponame/imagename/imagetag" etc.
etc.

**Comment by willemsrb** [comment]
I'm having the same issue; what i can see from the logs in Nexus is that the 'mirror'-pull results in an http 401 (unauthorized) and that the docker client then tries the central docker hub. When i do an explicit pull from the mirror i see the same 401 result in the log, but it followed by an authorized attempt. Can it be can that the mirror-functionality doesn't take the login crendetials into account or something like that?

**Comment by stefan-schilling** [comment]
@Tzrlk : Thanks for your response. Trouble is: I cannot change the address, i.e. I cannot change the installation to be on the root path.
I find this being a bug, since it can handle contexts other than root for e.g. the default repo @https://index.docker.io/v1/

**Comment by Tzrlk** [comment]
That one appears to be a special case as it's expecting to encounter a repo
version after the context root. It would be much better if the target
repository was not included in the tag, and instead you specify a
repository when pushing, and have a list of repositories for fetching from.

**Comment by mkarg** [comment]
/remove-lifecycle stale

In out environment (Docker 17.06.2-ee-7 + Nexus OSS 3.10.0-04) the mirror is correctly listed by `docker system info`, and explicitly using its URL when pulling also is working, but when omitting the explicit URL at `docker pull` it will not getting use -- it simply bypasses the mirror and tries to use docker hub instead. :-(

**Comment by m451** [comment]
Any information on this topic? This is preventing any meaningfull use in any bigger company since policies do not allow to pull from docker.io directly and firewalls will usually block this. 
Using a workaround such as specifing the internal repo in every single image makes the Dockerfiles no longer environment indenpendent.

We're having this issue with Docker for Windows 18.03.1-ce and ` docker info ` does correctly list the Registry Mirror. Also explicity using the internal repo  when specifying the image e.g. `myrepo/debian:stable` works just fine.

It's just that when NOT explicitly specifying the Registry Mirror is never used.

**Comment by wysockip** [comment]
I have the same, docker unix 18.03.1 i have mirror repo (internal one) and no proxy (so machine can't reach the internet) and i got information that:
Error response from daemon: Get https://index.docker.io/v1/search?q=ubuntu&n=25: dial tcp getsockopt: connection refused

What i expect is to get a list from my mirror repository (which is a proxy for docker hub) and not docker trying to get docker hub directly.

Any info when we could expect a fix for that ?

**Comment by ducttapecoder-vt** [comment]
I can confirm this works correctly with Docker Desktop 2.0.0.2 (18.09.01) on Win 10 and Docker 18.09.03 on WS2019, although I am not using nexus or authentication.
