### ISSUE TITLE
 stdout: The remote procedure call failed Failed to deploy distro docker-desktop distro: exit code: -1

### ISSUE THREAD

**Issue by JMackCo** [docker/for-win#8426]
https://hub.docker.com/editions/community/docker-ce-desktop-windows -->
  - [Y ] I have tried with the latest version of my channel (Stable or Edge)
  - [Y ] I have uploaded Diagnostics
  - Diagnostics ID: 995D2FF2-54FB-47D2-905E-EA7DC4C7A4CE/20200910120013
Complete fresh OS install. Update to insider version. Only tried to install Docker Desktop and/or Ubuntu: same remote procedure error.

Followed procedure first thing after New OS install.  https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by JMackCo** [comment]
This has to be related to same issue: Installing, this may take a few minutes... Got this while trying to install the distro
WslRegisterDistribution failed with error: 0x800706be
Error: 0x800706be The remote procedure call failed.

Press any key to continue...

**Comment by JMackCo** [comment]
Testing Solution now.
I had to manually create the file: daemon.json and folders ProgramData/Docker/config    Place the file there: Here is what I pasted in that file: 
I had to manually create the file: daemon.json and folders ProgramData/Docker/config    Place the file there: Here is what I pasted in that file: 

{
    "authorization-plugins": [],
    "dns": [],
    "dns-opts": [],
    "dns-search": [],
    "exec-opts": [],
    "experimental": false,
    "storage-driver": "",
    "storage-opts": [],
    "labels": [],
    "log-driver": "",
    "mtu": 0,
    "pidfile": "",
    "graph": "",
    "cluster-store": "",
    "cluster-advertise": "",
    "max-concurrent-downloads": 3,
    "max-concurrent-uploads": 5,
    "shutdown-timeout": 15,
    "debug": true,
    "hosts": [],
    "log-level": "",
    "tlsverify": true,
    "tlscacert": "",
    "tlscert": "",
    "tlskey": "",
    "swarm-default-advertise-addr": "",
    "group": "",
    "default-ulimits": {},
    "bridge": "",
    "fixed-cidr": "",
    "raw-logs": false,
    "registry-mirrors": [],
    "insecure-registries": [],
    "disable-legacy-registry": false
}

**Comment by JMackCo** [comment]
SOLVED: I hope: After completing the above procedure. I did get it running. Then I got an error from Docker. Restarted docker.. So far all is good... I have restarted my computer twice and it seems to working correct.

**Comment by MHacker9404** [comment]
spotted this: [Windows 10 2004 KB4571756 breaks Windows Subsystem for Linux 2](https://www.bleepingcomputer.com/news/microsoft/windows-10-2004-kb4571756-breaks-windows-subsystem-for-linux-2/)
