### ISSUE TITLE
"Parameter Is Incorrect" while creating L2Bridge

### ISSUE THREAD

**Issue by jimbo8098** [docker/for-win#8427]
I was asked to raise an issue here regarding an issue I experienced while creating an l2bridge network on Windows 10 Business build 10.0.19041. I experienced the same issue creating transparent networks too.

### Expected behavior
When running:

```
docker network create -d l2bridge --subnet 10.0.2.0/24 --gateway 10.0.2.1 -o com.docker.network.windowsshim.dnsservers="8.8.8.8" l2bridge
```

I receive the ID of the new network and to find it when I run `docker network ls`
### Actual behavior
When running:

```
docker network create -d l2bridge --subnet 10.0.2.0/24 --gateway 10.0.2.1 -o com.docker.network.windowsshim.dnsservers="8.8.8.8" l2bridge
```

I receive an error stating:

```
Error response from daemon: failed during hnsCallRawResponse: hnsCall failed in Win32: The parameter is incorrect. (0x57)
```
### Information
I am able to reproduce this issue on my Windows 10 Business (Build 10.0.19041) laptop but I am unable to reproduce the same on a server running Windows Server 2019 (Build 10.0.17763) with GUI. The server runs on a Hyper-V instance whereas on the laptop I am running docker on the host hardware. One potential solution in the meantime may, therefore, be to do this through a Windows Server 2019 VM on the laptop which presumably should provide the same results but I don't believe this is expected behavior based on the articles I've found.

**Comment by jimbo8098** [comment]
This does also seem to be quite a common issue on Windows implementations:

https://github.com/moby/moby/issues/40621

**Comment by stephen-turner** [comment]
Thanks for the report, @jimbo8098, but if it's an hnsCall error, it can't be in the Docker Desktop code, it must be in moby/moby. I'm not sure why the original reporter directed you here. I'll reply on the original ticket.
