### ISSUE TITLE
Docker installation on windows - getting error while switching to Linux Container

### ISSUE THREAD

**Issue by MonikaAsawa** [docker/for-win#8430]
I have installed Docker Desktop on windows. Windows container works fine but when I Switch to Linux Containers, I am getting below error.

Host : Windows Server 2019

Docker Desktop Version: 2.3.0.4 (46911)

C:\Users\******\AppData\Roaming\Docker\gateway_forwards.json; pcap_snaplen = 128
**[14:41:24.625]**[VpnKit            ][Error  ] vpnkit.exe**: While watching **C:\Users\******\AppData\Roaming\Docker\gateway_forwards.json**:** ENOENT
[14:41:24.625][VpnKit            ][Error  ] vpnkit.exe: Failed to read gateway forwards from C:\Users\********\AppData\Roaming\Docker\gateway_forwards.json**: reading C:\Users\******\AppData\Roaming\Docker\### **gateway_forwards.json: No such file or directory**.

'DockerDesktopVM' Microsoft VmBus (Instance ID D41A1870-3740-41CE-A1EE-4522AB82F991): Failed to initialize with error 'The system cannot find the path specified.' (0x80070003). (Virtual machine ID 9324C3F0-B408-4F8F-9E9B-9620EEB1CB28)

**Comment by JMackCo** [comment]
https://github.com/docker/for-win/issues/8426
