### ISSUE TITLE
iptables unknown option --dport WSL2

### ISSUE THREAD

**Issue by csigueros** [docker/for-win#8432]
I want to create a docker container and expose a port using SCTP. 

When I run the command: 

docker run --name sgc2 -p 22100:22100/sctp sgc2:0.1

I get the following error:

docker run --name sgc2 -p 22100:22100/sctp sgc2:0.1
docker: Error response from daemon: driver failed programming external connectivity on endpoint sgc2 (70bdabc832a3bfd0572846cbb4d4ee3958b7bdf45bfa515654a58ea1f5ce5c9e):  (iptables failed: iptables --wait -t nat -A DOCKER -p sctp -d 0/0 --dport 22100 -j DNAT --to-destination 172.17.0.2:22100 ! -i docker0: iptables v1.8.3 (legacy): unknown option "--dport"
Try `iptables -h' or 'iptables --help' for more information.
 (exit status 2)).
ERRO[0000] error waiting for container: context canceled

The problem appears only when I use sctp protocol, it works fine if I use tcp.

  - Windows Version: 2004 (19041.508)
  - Docker Desktop Version: 2.3.0.4 (46911)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No. 

I have tried the same docker image on a linux host with iptables 1.6.1 and it works fine. Anyway, the iptables version is not the one installed in my WSL2 (ubuntu 20) which is 1.8.4.

**Comment by PavelSosin-320** [comment]
This is a very common issue! iptables cli is replaced with nft in the most Linux distro. It returns a warning and exit code 4 saying that legacy IP tables found and CNI stops after it. This issue is already reported to the CNI team directly and they are searching for a solution by my knowledge.

**Comment by csigueros** [comment]
Thanks a lot for your answer.

In the meantime, in case it helps to somebody else, I'm using --publish-all in my container as a workaround.
