### ISSUE TITLE
Crash on Windows10 20211

### ISSUE THREAD

**Issue by joesdu** [docker/for-win#8437]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 8AA59E2A-BBFD-4C7F-88A5-7626E5DD9B16/20200911033830

### Information
Start failed with Failed to set version to docker-desktop: exit code: -1
 stdout: ?zǐz?(u1Y%?0
 
 
 
 stderr: 
   在 Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) 位置 C:\workspaces\edge-2.3.6.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:行号 142
   在 Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() 位置 C:\workspaces\edge-2.3.6.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:行号 82
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__25.MoveNext() 位置 C:\workspaces\edge-2.3.6.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:行号 99
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() 位置 C:\workspaces\edge-2.3.6.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:行号 29
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() 位置 C:\workspaces\edge-2.3.6.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:行号 67
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() 位置 C:\workspaces\edge-2.3.6.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:行号 92
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() 位置 C:\workspaces\edge-2.3.6.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:行号 69
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Docker.Engines.Engines.<StartAsync>d__23.MoveNext() 位置 C:\workspaces\edge-2.3.6.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:行号 108)
-->
  - Windows Version: Windows10 20211
  - Docker Desktop Version: 2.3.6.2 (47842)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Fuzl** [comment]
Same problem here. I cannot manage to successfully run Docker Desktop with Linux containers on WSL2. It works with Windows containers, not with Linux.
Windows Insider Preview Build 20211.rs_prerelease.200904-1619
Docker Desktop Edge 2.3.6.2

Context :
I came to the insider preview in order to setup the NVIDIA CUDA drivers for WSL2 : https://docs.nvidia.com/cuda/wsl-user-guide/index.html

I have tried so many solutions its hard to keep track of all combination but :
- remove wsl, switch to Windows container or to Hyper-V, add wsl and try to switch back to WSL2 with Linux
- remove the latest windows security patch (KB4576477)
- Steps provided in #6868 
- kill dockerd
- manually update the Linux kernel for WSL2

None of those worked...
Any hints please ?
Thanks !

**Comment by dalexhd** [comment]
See #8449

**Comment by aaronlphillips** [comment]
I was able to fix this by running `wsl --update` from PowerShell (as admin, followed by `wsl --shutdown` to force a restart).

**Comment by joesdu** [comment]
看起来是Windows的bug,先关闭这个issue.
