### ISSUE TITLE
DNS Conflict Causing Docker Desktop to Crash

### ISSUE THREAD

**Issue by delta1186** [docker/for-win#8445]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 37422F1B-A83A-4036-947B-350BA0953B77/20200911234932

### Expected behavior
Docker Desktop should start
### Actual behavior
Desktop Desktop crashing when starting up

  - Windows Version: Windows 10 Enterprise 2004
  - Docker Desktop Version: 2.3.0.4
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
 I am running a php development tool called valet (for windows) and I am think it is related to this tool.  It is running Nginx and Acrylic DNS.  If I stop those services, then Docker Desktop will startup, but then when I restart valet I can not longer browse my local development .test domains locally.

Here is a bug report I submitted for that tool.  Not certain who is not playing nice. 
https://github.com/cretueusebiu/valet-windows/issues/143

**Comment by delta1186** [comment]
I went ahead and installed Edge version just be sure this issue has not already been fixed.  Still crashes on startup.  New Diag ID 37422F1B-A83A-4036-947B-350BA0953B77/20200912000955

**Comment by ptournet** [comment]
Docker and Acrylic are both competing to use port 53 (DNS)... Depending on which runs first the other one can't run properly (or even crashes) ! The only solution I'm seeing would be to use a docker based DNS proxy instead of Acrylic to be able to use valet and docker at the same time... I'm gonna look into it as it bothers me a lot too !

**Comment by delta1186** [comment]
@ptournet so I did a thing. https://hub.docker.com/r/hickskp/docker-dns
More to come hopefully soon!
