### ISSUE TITLE
After windows update / docker update mounted volume files from docker-compose.yml are empty...

### ISSUE THREAD

**Issue by LiamTrioTech** [docker/for-win#8447]
### Expected behavior
When needing to update windows or docker the volume mapped files should not be erased.

Not sure how to reproduce, anyone else had this issue?
Have seen this happen on two different computers at work.

### Information
  - Windows Version: Windows 10 2004 19041.508
  - Docker Desktop Version: 2.3.6.2 (47842) edge.
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
  1. Windows update + docker update?
  2. None of my containers would start properly due to volume mapped files being empty.

**Comment by karasq** [comment]
Probably same issue here https://github.com/docker/for-win/issues/8439

**Comment by LiamTrioTech** [comment]
Sounds the same yes, is this fixed as that ticket #8439 is closed I see the comment from Simon.
@simonferquel ```All right, we fixed the problem for directories on 2.3.6.2 but there is still an issue with single-file mounts. Fix is in the works.
```

**Comment by simonferquel** [comment]
Indeed, sorry about the mess we've done lately with bind mounts on Edge. We basically reworked it from the ground up.
