### ISSUE TITLE
"Failed to deploy distro docker-desktop to xxx exit code: -1  stdout: Element not found."

### ISSUE THREAD

**Issue by yooakim** [docker/for-win#8452]
- [x] I have tried with the latest version of my channel (Stable)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 95F47DB1-E316-42C3-8105-AA385655DF2B/20200912104805

### Expected behavior

Docker desktop should start

### Actual behavior

The following error message:

     Failed to deploy distro docker-desktop to C:\Users\xxxx\AppData\Local\Docker\wsl\distro: exit code: -1 stdout: Element not found.

### Information
  - Is it reproducible? - Yes
  - Is the problem new? - Yes
  - Did the problem appear with an update? _I don't know. I may be a Linux Kernel update via Windows update_

  - Windows Version: Version 20H2 (19042.508)
  - Docker Desktop Version: 2.3.0.4
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Start Docker Desktop

<img width="515" alt="Screenshot 2020-09-12 125834" src="https://user-images.githubusercontent.com/862546/92994115-b93b6b80-f4f7-11ea-9192-74868dc967f8.png">

**Comment by Nikhil-Mahapatra** [comment]
I am also getting the same after my Windows 10 update:

Information

    Is it reproducible? - Yes

    Is the problem new? - Yes

    Did the problem appear with an update? I don't know. I may be a Linux Kernel update via Windows update

    Windows Version: Version 20H2 (19042.508)

    Docker Desktop Version: 2.3.0.4

    Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No


![image](https://user-images.githubusercontent.com/64895246/93016512-6ccb5b00-f5df-11ea-8467-25c30c8cb90e.png)

**Comment by mojo333** [comment]
Same issue:

```
Is it reproducible? - Yes

Is the problem new? - Yes

Did the problem appear with an update? I don't know. 

Windows Version: Version 2004 (19041.508)

Docker Desktop Version: 2.3.0.5

Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

```
![image](https://user-images.githubusercontent.com/10668864/93329329-f4e67600-f814-11ea-991f-d5996705b17b.png)

**Comment by stephen-turner** [comment]
I think this is a WSL bug, https://github.com/microsoft/WSL/issues/5880.
