### ISSUE TITLE
Issue mounting shared drives

### ISSUE THREAD

**Issue by nesixugija** [docker/for-win#847]
### Expected behavior
Any drive is shared

### Actual behavior
Drives are not shared

### Information
- Docker Versions: 17.06.0-ce-rc2/4
- OS: Windows 10 Pro

### Steps to reproduce the behavior
  1. In Docker for Windows settings, drives _C_, _D_ & _E_ are marked as shared;
  2. Connect a not empty USB pendrive, which will be mounted under _E:/_;
  3. Run a container mounting the drive an extern volume with the command `docker run -d --name test -v E:/:/opt:ro ubuntu`
  4. Get into the running container _test_ with `docker exec -it test /bin/bash`
  5. In /opt/ you won't find the content of the pendrive;
  6. In Docker for Windows settings, all drives are still checked.

**Comment by nesixugija** [comment]
Easy, quick and dirty fix:
1. Go to Docker for Windows -> Settings -> Shared Drives, uncheck all available drives and click _Apply_;
2. Check all drives again and click _Apply_.

Now volumes will be mounted into any container, until the next reboot/logout.

**Comment by jasonbivins** [comment]
Hi @nesixugija 
Is the USB drive connected already when you share the E: drive through the GUI?

**Comment by nesixugija** [comment]
Hi @jasonbivins 
The usb pen is already connected, otherwise Docker for Windows doesn't show the E: drive in `Shared Drives` under `Settings`. 

However, the fix that I proposed in post #2 doesn't work always.
