### ISSUE TITLE
Docker Desktop startup failure on win10 after successful install

### ISSUE THREAD

**Issue by BobBalaban** [docker/for-win#8472]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BA6EA30C-AE12-4B9A-85ED-A87C4BC824CD/20200914115747

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by onionhammer** [comment]
Same here D1A49495-A208-4093-92CD-C1D7F306E398/20200914134357

**Comment by dalexhd** [comment]
See #8449
