### ISSUE TITLE
Docker/Docker-Machine Paradox (Windows BSOD)

### ISSUE THREAD

**Issue by NonCreature0714** [docker/for-win#848]
### Expected behavior 
Docker for Windows required Hyper-V enabled in BIOS.

However, following these [Docker Docs](https://docs.docker.com/get-started/part4/#set-up-your-swarm) instructions, and running these Docker Machine Commands should work.
    `$ docker-machine create --driver virtualbox myvm1`
    `$ docker-machine create --driver virtualbox myvm2`

### Actual behavior
Docker-Machine will not start VM with virtualbox
    ` PS C:\Users\<me>> docker-machine create --driver virtualbox myvm4`
      `Running pre-create checks...`
      `Error with pre-create check: "This computer is running Hyper-V. VirtualBox wo
Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)"`

BSOD (Blue Screen of Death) when attempting to start a virtual machine via VirtualBox.

### Information

  - Diagnostic ID for docker machine failure: D993D792-C1C1-4ED3-8740-F2138D4A9D79/2017-06-23_14-19-46
  - [Docker Docs Refenence](https://docs.docker.com/get-started/part4/#set-up-your-swarm)
  - host distribution and version (Windows version, build number, etc):
    - Windows 10 Enterprise
    - 

Docker-CE (Windows Edition) on Windows 10 requires that Hyper-V is enabled in BIOS (and again via Control Panel). 

Virtualbox, which Docker-Machine uses, crashes Windows per a [long-time, known bug running VirtualBox with Hyper-V enabled](https://www.virtualbox.org/ticket/16801).

This means if Docker-CE (Windows Edition for Windows 10) is running, then Docker-Machine cannot run because VirtualBox is a blocker, because of the inability to run with Hyper-V; and vice-versa. So if one is running, the other cannot, yet they should be able to run together.

I have not tested Docker-EE.

I believe this issue is related to:
 - [Failed to create windows vm with docker-machine](https://github.com/docker/machine/issues/4135)
 - [Blue screen windows 10](https://github.com/docker/machine/issues/4086)
 - [Failed to create windows vm with docker-machine](https://github.com/docker/machine/issues/4044)
 - [Cannot create docker VM on Ubuntu 16.4 in Oracle VM VirtualBox on Windows 7 Enterprise machine with virtuaization turned on](https://github.com/docker/machine/issues/3901)
 - This related to being able to follows Docker Docs,[ I have filed an issue there](https://github.com/docker/docker.github.io/issues/3694)
 - I have also created a [Docker Machine issue](https://github.com/docker/machine/issues/4151)

docker -v: Docker version 17.03.1-ce, build c6d412e
docker-machine -v: docker-machine.exe version 0.10.0, build 76ed2a6

I have filed a separate [Documentation Issue](https://github.com/docker/docker.github.io/issues/3694) to update the Docker Docs.

### Steps to reproduce the behavior

  1. run `docker-machine create --driver virtualbox myvm1` on a Windows 10 Machine with Hyper-V enabled
  2. it will not work

**Comment by friism** [comment]
You have to use the hyper-v driver - this is detailed in the doc:

    docker-machine create -d hyperv --hyperv-virtual-switch "myswitch" myvm1

![image](https://user-images.githubusercontent.com/126104/27497205-43e88fa4-580e-11e7-945e-1588f3728535.png)

**Comment by NonCreature0714** [comment]
@friism Updating issue and I go, cautiously, so I don't BSOD in the middle of updating. `docker-machine create -d hyperv --hyperv-virtual-switch "myswitch" myvm3` must be run as administrator (at least in PowerShell).

**Comment by NonCreature0714** [comment]
@friism I'm having trouble reproducing the bug, I've crashed my Windows computer 3 times now when trying to run Virtualbox (and Docker together with virtualbox), with no success, but now it's working perfectly. I'll close this, and my other bugs, if I can't reproduce in 24 hours.

**Comment by NonCreature0714** [comment]
@friism (apologies for copy/paste, but I thought you should know... ) the Hyper-V instructions work.

The best I can tell right now is that there was some conflict with running Vagrant and docker-machine in proximity on the same machine. Vagrant absolutely causes BSOD because of a bug in VirtualBox. And it's possible that when I ran docker-machine afterwards there was still some unresolved issue. I'm currently working to reproduce. Either way, this looks very much like an edge case.

I'm strongly advocating for Docker to internal operations/dev/IT clients, while at the same time as learning SaltStack (which uses Vagrant for tutorials). So I'm realizing now this isn't as clear cut as I thought it was. This was particularly frustrating, because I wasn't able to complete a Docker demo to my internal clients because of crashes.

**Comment by NonCreature0714** [comment]
I'm closing this ticket as un-reproducible. It appears it has something more to do with Vagrant.
