### ISSUE TITLE
Docker doesn't start after updating to v2.3.0.5

### ISSUE THREAD

**Issue by xon88** [docker/for-win#8487]
- [ x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x ] I have uploaded Diagnostics
  - Diagnostics ID: 56A53A51-FDBF-4E0B-A14B-27977C70E1E5/20200915144120

### Expected behavior
Docker starts

### Actual behavior
Failed to start (error message in diagnostics)

### Information
System.Threading.Tasks.TaskCanceledException:
Cancellation token triggered before we finished reading from the stream.

  - Windows Version: Windows 10 Enterprise
  - Docker Desktop Version: 2.3.0.5
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

Update to v2.3.0.5 and start docker for windows

**Comment by GRMorgan** [comment]
I'm getting similar behaviour. Docker Linux engine starts but the windows engine always fails to get going
