### ISSUE TITLE
Unable to use WSL2 based engine on Windows 1909

### ISSUE THREAD

**Issue by HanKruiger** [docker/for-win#8489]
- [x] I have tried with the latest version of my channel (Stable or ~~Edge~~)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 79738B68-B834-464A-9EAB-85199985461D/20200915145852

Since my Windows build supports WSL2 now, I am surprised that Docker Desktop doesn't work with it.

### Expected behavior
I can use the WSL 2 based engine.

### Actual behavior
I am unable to use the WSL 2 based engine (Tickbox in Settings -> General is greyed out).

### Information
Since some time, Windows versions 1903 and 1909 support WSL2 as well (see https://devblogs.microsoft.com/commandline/wsl-2-support-is-coming-to-windows-10-versions-1903-and-1909/).

The message I get in my Ubuntu distro in WSL2 when running `docker` is:
```
The command 'docker' could not be found in this WSL 2 distro.
We recommend to activate the WSL integration in Docker Desktop settings.

See https://docs.docker.com/docker-for-windows/wsl/ for details.
```
but as mentioned above, I am unable to activate the integration in the settings.

### Steps to reproduce the behavior
1. Have Windows with OS build 18363.1082
2. Enable WSL2 and verify that it works
3. Install Docker Desktop 2.3.0.5

Cheers!

**Comment by stephen-turner** [comment]
It works in Edge, it's not yet released in Stable.
