### ISSUE TITLE
how to increase diskspace for all container ?

### ISSUE THREAD

**Issue by RogerYaozhenyu** [docker/for-win#849]
### Expected behavior
To increase diskspace more than 30 or 40G .
### Actual behavior
it look like the size of a continer is fixed 10G 
### Information

 win 10 .
 Version 17.03.1-ce-win12 (12058)

### Steps to reproduce the behavior

  1.  To Download some big files when the size if more than 10G ,it is going to fail to download.

**Comment by jasonbivins** [comment]
Hi @RogerYaozhenyu 

Were you downloading Linux or Windows containers ?
What error are you seeing when the downloads drop?
Is this over a wired or wireless connection?

**Comment by RogerYaozhenyu** [comment]
hi, yes, i work under win10 docker environment.  i make built some images by myself. after then , i try to build a windriver linux platform project  and when i finished. i try to commit .. it 's failed .  pls see the detailed as below:  so i guess , may be the container is reach the max limited size? so i want to know how 
to increase the size of one container  or all continers for windowns docker. thanks .

docker commit 21fa3f99a4c9  wrlinux8_wb:1.3
Error response from daemon: Error processing tar file(exit status 1): write /home/build/t1042/bitbake_build/downloads/git2/windshare.windriver.com.remote.php.gitsmart.WRLinux-8-Core.kernel-4.1.x-LB13_8.0_RCPL0018/objects/pack/pack-966930d583f7f0ada2f46617862f728e3b42a309.pack: no space left on device

**Comment by ebriney** [comment]
Hi, as I know there is no limit on container size but on windows the vm hd has a fixed size of 60G.
Unfortunately for now we cannot change it in the UI, it is hardcoded.
You can change it in the script and reset to default, it should work.
`C:\Program Files\Docker\Docker\resources\MobyLinux.ps1` line 86

**Comment by RogerYaozhenyu** [comment]
hi, you mean 60G is a fixed size for the windows vm to run docker, right?  so if i want to commit my conainer successed , maybe i can rmi all of other images to save more space for  this work .right?

**Comment by jasonbivins** [comment]
Hi @RogerYaozhenyu   Yes you'll need to restart the engine after making the change.   Change 60 to the size you'd like.

# Hard coded for now
$global:VhdSize = 60*1024*1024*1024

The change will be reverted during upgrades or reinstalls, so you'll want to keep an eye on that.

**Comment by RogerYaozhenyu** [comment]
thanks for your support and help.

**Comment by marcramser** [comment]
I dont see why this issue was closed. In my opinion it is wrong that one can select more than 60GB of disk image size in the GUI settings without getting a warning.
