### ISSUE TITLE
cannot opening the homepage on 192.168.99.100[port number]

### ISSUE THREAD

**Issue by purveshgosai14** [docker/for-win#85]
### Expected behavior
If I write 192.168.99.100[port number], it will open my home page but
### Actual behavior
my docker is already connected with database but now if I open http://192.168.99.100[port number], nothing is opening. The expected output is home page.

![screenshot 3](https://cloud.githubusercontent.com/assets/3169430/18579034/17ec500e-7bc1-11e6-9f94-4847a5013ccd.png)
![screenshot 4](https://cloud.githubusercontent.com/assets/3169430/18579035/17ec8d12-7bc1-11e6-9719-73507a1f1378.png)
![screenshot 5](https://cloud.githubusercontent.com/assets/3169430/18579036/17f075e4-7bc1-11e6-9edd-a77ea53789ba.png)
![screenshot 6](https://cloud.githubusercontent.com/assets/3169430/18579037/17f0b37e-7bc1-11e6-938f-fd00988d7de7.png)

### Information
Docker is running properly and database is also connected to docker files. But now I'm trying to open http:192.168.99.100: , nothing is opening.
  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by friism** [comment]
@purveshgosai14 are you using Docker for Windows? In that case, container ports are exposed on `localhost`, and you shouldn't use `docker-machine` for local provisioning.

**Comment by purveshgosai14** [comment]
@friism I'm using Docker tool box.

**Comment by friism** [comment]
@purveshgosai14 ok, closing this issue, please re-open in the toolbox issue tracker: https://github.com/docker/toolbox/
