### ISSUE TITLE
docker failed to start after update + reboot

### ISSUE THREAD

**Issue by VladimirButorin** [docker/for-win#8500]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 36936945-D19B-4966-ADBD-F139C5C478C7/20200916052633

### Expected behavior
docker works
### Actual behavior
docker failed to start

### Information

  - Windows Version: win 10 ent
  - Docker Desktop Version: 2.3.05 (48029) stable
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. Update docker to 2.3.05 (48029) stable
  2. Restart PC

**Comment by robertkirkham88** [comment]
I am having the same issue after the latest update. Still have to uninstall KB4571756 (wusa /uninstall /kb:4571756)

Failed to deploy distro docker-desktop to C:\Users\rsk15\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: The remote procedure call failed.

**Comment by VladimirButorin** [comment]
Hi all
root cause of issue that after windows update (and yes  docker update in paralel) wsl stoped working.
on wsl thread (https://github.com/microsoft/WSL/issues/4929) the proposal was disable Hyper-V.
after that docker works as expected.

Thank you.

**Comment by stephen-turner** [comment]
I think this is probably https://github.com/microsoft/WSL/issues/5880

**Comment by VladimirButorin** [comment]
Hi Stephen,
I had another error. It was something like stdout error -1 0xffffffff
Not really sure what it can mean :)

**Comment by stephen-turner** [comment]
I think it's all part of the same issue, you will see several related ones at https://github.com/microsoft/WSL/issues?q=is%3Aissue+is%3Aopen+KB4571756

**Comment by VladimirButorin** [comment]
yeah seems you right. I found same error inside...
