### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by nicktar** [docker/for-win#8506]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3CF39628-15A3-46E5-8CFD-E8398CE62ED1/20200916061544

### Expected behavior
Docker starts up

### Actual behavior
After updating to the latest version, docker crashes on startup, reporting this error

### Information

  - Windows Version: see crash report
  - Docker Desktop Version: see crash report
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by PavelSosin-320** [comment]
This issue lasts already half of the year! Will it be solved sometime in the future? During this period I switched to vanilla Docker and Podman.
The line listening on unix:\\\\.\\pipe\\dockerVpnkitData for data connection says "I know that my kernel supports FifoFS but the Kernel provided to Docker by Microsoft doesn't have it or I can't find it. Everybody can check it using wsl -d docker-desktop -u root mount | column -t.
