### ISSUE TITLE
Windows 10 Quick Start and Virtual Machines

### ISSUE THREAD

**Issue by Grauenwolf** [docker/for-win#851]
The Windows 10 Quick Start guide needs to warn you that Docker for Windows doesn't work inside a virtual machine.

**Comment by jasonbivins** [comment]
Hi @Grauenwolf 
Can you please provide more information, or a screenshot of the error you're seeing?

**Comment by Grauenwolf** [comment]
C:\Source>docker run -it microsoft/nanoserver cmd
docker: Error response from daemon: container e31cc45f5d4849055ff13566014c696cad5a5effc9702622c3524b43b3f9ea01 encountered an error during CreateContainer: failure in a Windows system call: No hypervisor is present on this system. (0xc0351000) extra info: {"SystemType":"Container","Name":"e31cc45f5d4849055ff13566014c696cad5a5effc9702622c3524b43b3f9ea01","Owner":"docker","IsDummy":false,"IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\ProgramData\Docker\windowsfilter\e31cc45f5d4849055ff13566014c696cad5a5effc9702622c3524b43b3f9ea01","Layers":[{"ID":"b43f5bf9-40d3-5fed-881c-105d1b4496cd","Path":"C:\ProgramData\Docker\windowsfilter\6214d91103e6aaf1ae8fca1a7312fa6939d1c0de4e13c19ead8915ccdf25745b"},{"ID":"eca436c3-1750-5858-ba86-380cd21bf844","Path":"C:\ProgramData\Docker\windowsfilter\8992d70442bb7e2c539993fd319fb91bfe0f20ed6a063fad9ab90a83882ebaff"}],"HostName":"e31cc45f5d48","MappedDirectories":[],"SandboxPath":"C:\ProgramData\Docker\windowsfilter","HvPartition":true,"EndpointList":["e18c867d-844c-47e1-aa0c-fc7f045062ea"],"HvRuntime":{"ImagePath":"C:\ProgramData\Docker\windowsfilter\6214d91103e6aaf1ae8fca1a7312fa6939d1c0de4e13c19ead8915ccdf25745b\UtilityVM"},"Servicing":false,"AllowUnqualifiedDNSQuery":true}.

**Comment by jasonbivins** [comment]
@Grauenwolf , it looks like Hyper-V was missed during the install. Can you please run the Debug-ContainerHost script located here and share the results?
https://github.com/Microsoft/Virtualization-Documentation/tree/live/windows-server-container-tools/Debug-ContainerHost

**Comment by Grauenwolf** [comment]
Sorry, I already burned down that virtual machine. 

Hyper-V was installed on the guest OS, but was available on the base OS (which was Windows XP) . 


---
Jonathan Allen
Scholars of Alcala
619-933-8527

**Comment by rn** [comment]
There is a note in the Docker for Windows troubleshoot: https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-for-windows-in-nested-virtualization-scenarios

This is primarily targeted at running Linux Containers on Windows but also applies to Hyper-V backed windows containers on Windows 10

**Comment by jasonbivins** [comment]
Hi @Grauenwolf 
I'll go ahead and close this issue - but please let me know if you run into any problems
