### ISSUE TITLE
Docker Crash on Startup

### ISSUE THREAD

**Issue by pvanbell** [docker/for-win#8514]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Docker starts up and is running

### Actual behavior

Get crash screen

### Information

  - Windows Version: Winb 10
  - Docker Desktop Version: 2.2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. ...
[DockerCrashLog.txt](https://github.com/docker/for-win/files/5232013/DockerCrashLog.txt)
![DockerCrash](https://user-images.githubusercontent.com/68553213/93335073-ec317800-f7f3-11ea-9df5-7a051e1b1a81.jpg)

  2. ...

**Comment by PavelSosin-320** [comment]
I occasionally checked the old Docker Desktop installation on another machine, Windows Home which I made for the fan, to check the possibility to use Windows Home and it works!!!
Docker Desktop version .3.0.3
Linux Kernel version 4.19.04
The current Kernel  version is 4.19.128
This old version had no VPN support as I can remember.
lsof in the old version shows Pipe sockets opened by the container engine. I never saw how Docker opened Pipes more.
