### ISSUE TITLE
Memory issues after upgrading to 2.3.0.5

### ISSUE THREAD

**Issue by marbletravis** [docker/for-win#8519]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 925EAB38-D059-4D58-A682-2AE984314570/20200916162830

### Expected behavior
Memory recycling
### Actual behavior
Over memory usage.
### Information
I understand there are issues with WSL2 and memory, I have read various posts on the issue, however prior to 2.3.0.5 I limited the memory in WSL2 via the .wslconfig and had no issues. 

After the upgrade, even expanding the .wslconfig results in out of memory errors in docker container. Once memory usage takes off, I can't open wsl2, and the docker application becomes slow and non-responsive.

Rolling docker back to 2.3.0.4 appears to solve the issue.

Things I have tried:
 * Uninstalling Docker
 * Rebuilding containers
 * Expanding memory via .wslconfig
 * Going back to 2.3.0.4, which appears to solve the issue.

Container exhibiting issue:
 * mcr.microsoft.com/mssql/server:2017-CU19-ubuntu-16.04  

  - Windows Version: 10.0.19041 Build 19041
  - Docker Desktop Version: 2.3.0.5
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

Setup: Windows 10 WSL2, Alpine WSL
  1. Run Docker
  2. Start MSSQL container
  3. After a little bit if use, memory usage consumes all allocated then you run into memory issues.

**Comment by cortex93** [comment]
I have created an issue #8521 that's seems related to yours.

**Comment by vtrusevich-incomm** [comment]
I am having the same issue with memory leaking on MacOS.
