### ISSUE TITLE
can't start

### ISSUE THREAD

**Issue by yidashi** [docker/for-win#853]
Version: 17.03.1-ce-win5 (10743)
Channel: stable
Sha1: b18e2a50ccf296bcd637b330c0ca9faaab9d790c
Started on: 2017/06/27 16:52:12.030
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1703
Build: 15063
BuildLabName: 15063.0.amd64fre.rs2_release.170317-1834
File: C:\Users\Administrator\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[16:52:12.291][GUI            ][Info   ] Starting...
[16:52:12.712][GUI            ][Error  ] 未将对象引用设置到对象的实例。

**Comment by jasonbivins** [comment]
Hi @yidashi   Can you please upload the diagnostic logs through the GUI and post the ID?  You can do this by right-clicking the Whale icon, then choosing diagnose and feedback.
