### ISSUE TITLE
WSL 2 installed but Docker open to enable WSL greyed out

### ISSUE THREAD

**Issue by fnord123** [docker/for-win#8549]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 73BD468A-7FAD-4DCD-BA38-C143039AD4E7/20200917180850

### Expected behavior

WSL option in settings available

### Actual behavior

WSL option remains greyed out

### Information

  - Windows Version: Windows 10 Pro 1909 (OS Build 18363.1082)
  - Docker Desktop Version: 2.3.0.5
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No, bare metal

### Steps to reproduce the behavior

wsl_update_x64.msi is installed.

Following are run from within Windows Terminal running Ubuntu 20.04:
`~$ wsl.exe -l -v`
`NAME      STATE           VERSION`
`* Ubuntu    Running         2`
`~$ docker`
    
    The command 'docker' could not be found in this WSL 2 distro.
    We recommend to activate the WSL integration in Docker Desktop settings.
    
    See https://docs.docker.com/docker-for-windows/wsl/ for details.
    
    dputzolu@Lenovo:~$

**Comment by StefanScherer** [comment]
Hello @fnord123 
Thanks for the report. I see that you aim for WSL 2 integration which is good. Currently the support for the WSL 2 backport in Windows 10 1903 / 1909 is only available in the Edge release of Docker Desktop. It hasn't landed in the Stable release, but it's planned for the next the next Stable release 2.4.x.

**Comment by fnord123** [comment]
Thanks for the information!

https://docs.docker.com/docker-for-windows/wsl/ seems pretty confusing then, as the prerequisite section says "Install Windows 10, version 1903 or higher." which is followed with "Download Docker Desktop Stable 2.3.0.2 or a later release."

Perhaps I missed something?  Seems like a doc (web page) bug if not.

**Comment by StefanScherer** [comment]
Thanks @fnord123 for the feedback.
Ouch, indeed, we recently merged a PR to change 2004 to 1903, but overlooked the rest. We'll fix the docs.

**Comment by stephen-turner** [comment]
Documentation fixed, closing this ticket.
