### ISSUE TITLE
IP.output: could not determine link-layer address for local network (0.0.0.0/0) ip 172.18.0.2

### ISSUE THREAD

**Issue by hellogrumble** [docker/for-win#8550]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:  3DE5EA2F-7825-43C8-8B27-C5000C58DEF9/20200917181600

### Expected behavior
A simple webapi container calling an external  MSSQL database, running within a Linux Container using WSL2 in Docker Desktop for Windows 10 should return result set to controller.

### Actual behavior

Accessing the api via http://localhost://[port]/api/[Controller]/[id] results in browser showing perpectual "Waiting for localhost" and never displays data from the call to the external database.  The log shows a UDP connection to the SQLSERVER and after 3 minutes, the call times out and then produces "IP.output: could not determine link-layer address for local network (0.0.0.0/0) ip 172.18.0.2" in the Docker log.

### Information
  - Windows Version:  Windows 10 PRO - 10.0.19041 Build 19041
  - Docker Desktop Version: 2.3.0.5
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
   Running WSL2 with Ubuntu 20.04LTS on a Microsoft Surface laptop.

### Steps to reproduce the behavior

1.  Follow these steps:  https://docs.microsoft.com/en-us/windows/wsl/install-win10
2.  Install Docker Desktop 2.3.0.5 and ensure WSL2 is enabled and Ubuntu is selected if it's not the default WSL2 
3.  Using Visual Studio 2019, build simple webapi that calls an external database on the same network and Add Container Orchestration Support to build the docker-compose and DockerFile.
4.  Run docker-compose from within Visual Studio 2019
5.  Using a browser, access the api on localhost like http://localhost://[port]/api/[Controller]/[id]

When I run this same project on a Windows 10 HOME machine using 19041, and following the same installation workflow I did on the PRO machine,  it works as expected with no errors in the docker logs and data is returned in the browser as expected.  When I switch to Windows Containers in Docker Desktop on the PRO machine, everything also works as well, but I need to run Linux Containers in Docker Desktop.

# Update

"This now seems isolated to an incompatibility between our Windows Server/SQLServer versions and Docker.  The event viewer on the server is showing the following when I attempt connections from a Linux container.

Certificate for local system with Thumbprint [thumprint] is about to expire or already expired.

A fatal alert was generated and sent to the remote endpoint. This may result in termination of the connection. The TLS protocol defined fatal error code is 40. The Windows SChannel error state is 1205.

An TLS 1.2 connection request was received from a remote client application, but none of the cipher suites supported by the client application are supported by the server. The SSL connection request has failed."

Although TLS1.2 is enabled on the server, and even when I disable tls in the docker engine,  I'm still getting these errors. Strangely, everything works when I switch to Windows Containers.

**Comment by stephen-turner** [comment]
It appears that the problem may be in the container, not in Docker Desktop.
