### ISSUE TITLE
Docker desktop 2.3.0.5 breaks docker build in jenkins unable to create context store

### ISSUE THREAD

**Issue by atishukla** [docker/for-win#8551]
Running jenkins build with docker container fails after upgrading to ver: 2.3.0.5

Jenkins version: **Jenkins 2.232**
Docker pipeline version: **1.24**

docker version:

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:43:18 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

docker build should work like in previous version

### Actual behavior

Error  while running build

`unable to create context store: mkdir /root/.docker/contexts: file exists`

### Information

  - Windows Version: 
```
OS Name: Microsoft Windows 10 Home Single Language
OS Version: Version: 2004 10.0.19041 N/A Build 19041
```
  - Docker Desktop Version: 2.3.0.4
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: WSL 2 Ubuntu 20.04

### Steps to reproduce the behavior

  1. Install docker desktop on windows and configure to use it with Ubuntu 20.04
  2. Use the docker compose file above to bring up the jenkins container
  3. Install docker pipeline plugin to use docker container for build
  4. Run a sample pipeline script

example:

```
#!groovy

node() {
	stage ('Checkout') {
	    deleteDir()       
	    checkout scm
	}


	stage ('Executing build') {
		docker.image('python:3.6').inside() {
		    sh 'pip install -r requirements.txt'
		    sh 'python --version'
		}
	}
}
```
**Reverting to previous version 2.3.0.4 fixes the issue for me**

**Comment by atishukla** [comment]
@stephen-turner - Thanks for looking into this. Yes uninstalling and installing the version 2.3.0.4 fix the problem for me , if this is what you mean.

**Comment by stephen-turner** [comment]
It wasn't actually what I meant. There is an option in the settings to use the old CLI on 2.3.0.5. But maybe it's too late now if you've already reverted to 2.3.0.4.

**Comment by atishukla** [comment]
I am sorry I wasn't using docker desktop until very recently after the microsoft upgrade.

**Comment by bestbeforetoday** [comment]
I saw a similar issue today with Docker Desktop 2.3.0.5 (on MacOS). Disabling the _Enable cloud experience_ option in the Command Line preferences solved it for me.

**Comment by stephen-turner** [comment]
Thanks for that information, @bestbeforetoday.

**Comment by stephen-turner** [comment]
Thanks for that information, @bestbeforetoday. Do you have the exact repro steps and error message for your case?

**Comment by bestbeforetoday** [comment]
I was just getting back to this to give you a script and some docker files to reproduce this problem, but it seems to have been solved (for me on MacOS at least) when I picked up version 2.4.0.0. (The gRPC file sharing in that version breaks other things for me, but that's another issue!)

**Comment by stephen-turner** [comment]
Good, thanks for the update. I'll close this ticket then.
