### ISSUE TITLE
KB4571756 crash docker service in windows 10

### ISSUE THREAD

**Issue by abe25masahito** [docker/for-win#8553]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
run docker service normally.

### Actual behavior
dump crash report.

### Information

  - Windows Version: windows 10 ( build 19042.508 )
  - Docker Desktop Version: 2.3.0.5
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. install KB4571756 in windows 10 ( build 19042.508 )
  2. run docker service

crash report is 2194CC22-A24C-4EF5-8332-1E75A6A89C27/20200918010718

**Comment by stephen-turner** [comment]
We haven't had any other reports of this. However, if it's broken due to a Windows update, you should report it to Microsoft.

**Comment by ingogriebsch** [comment]
I filed issue #8559 this morning. I found this issue a little bit later. Uninstalling KB4571756 solved my issue. Means, @abe25masahito is not alone.

**Comment by stephen-turner** [comment]
Thanks for the report, @ingogriebsch, I'll reopen the ticket.

**Comment by stephen-turner** [comment]
I think this is a WSL bug, https://github.com/microsoft/WSL/issues/5880.
