### ISSUE TITLE
Docker crashes on recent cummulative update for windows 2004, WSL2 not working properly 

### ISSUE THREAD

**Issue by noiissyboy** [docker/for-win#8557]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
You didn't specify exactly which update you had used, but I suspect this is a WSL bug, https://github.com/microsoft/WSL/issues/5880.
