### ISSUE TITLE
Docker Desktop on Windows 10 cannot be started because of a TimeoutException 'Timed out while wait for Docker service to be ready'

### ISSUE THREAD

**Issue by ingogriebsch** [docker/for-win#8559]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 80796CFA-1578-4AC1-9E2B-1D0E02960DDC/20200918061736

### Expected behavior
I can start Docker Desktop

### Actual behavior
Docker Desktop is not starting

### Information

  - Windows Version: Windows 10 Pro Version 2004 (Build 19041.508)
  - Docker Desktop Version: 2.3.0.5 (48029) stable, Engine 19.03.12
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. I startup the OS
  2. I log in
  3. Docker Desktop is starting automatically
  4. Windows reports that Docker Desktop is starting
  5. It takes minutes til Docker Desktop crashes with the information that a timout occurred while waiting for Docker Services.

**Comment by ingogriebsch** [comment]
After searching further through the internet and the issues here I stumbled about #8553. Uninstalling the KB, Docker-Desktop is starting up again. Nevertheless it would be really nice if you could have a look at the diagnostics data I uploaded because this is not the first time such thing happened (at least on my system). One week ago I had the same problem and needed to uninstall KB4566782 to get it working again.

**Comment by stephen-turner** [comment]
I think this is a WSL bug, https://github.com/microsoft/WSL/issues/5880.
