### ISSUE TITLE
Unexpected disconnect during download (Windows)

### ISSUE THREAD

**Issue by InteXX** [docker/for-win#856]
### Expected behavior
I should be able to `docker pull` a base image successfully.

### Actual behavior
Instead, I get disconnected mid-download with the message:
> http2: server sent GOAWAY and closed the connection; LastStreamID=11, ErrCode=NO_ERROR, debug="graceful shutdown"

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
    N/A
  - a reproducible case if this is a bug, Dockerfiles FTW
    N/A
  - page URL if this is a docs issue or the name of a man page
    N/A
  - host distribution and version (Windows version, build number, etc)
    Windows Server 2016 Hyper-V, fully patched
  - ISP bandwidth cap
    1Mbps down, 320Kbps up

### Steps to reproduce the behavior

  1. Issue the command `docker pull microsoft/windowsservercore`
  2. Wait for the eventual disconnection, at unknown progress percentage
  3. Note that network transfer speed during the download is extremely erratic

**Comment by jasonbivins** [comment]
Hi @InteXX 
What kind of environment are you running Server 2016 in - AWS, Azure - bare metal?

You mention that your bandwidth is capped at 1mbps ?  At that speed it should take about 4-5 hours to pull that image.

**Comment by InteXX** [comment]
Actually, more like twelve  ;-)

![image](https://user-images.githubusercontent.com/10966749/27659453-f828c69c-5bff-11e7-92cc-d4240357d5dc.png)

I've learned patience and humility by enduring under this limited bandwidth, but then again I've always been able to rely on download servers maintaining the connections.

I'm running the Hyper-V host on a Dell T110 here under my desk.

**Comment by InteXX** [comment]
I've been able to successfully `docker pull` the image on a 4Mbps network. It appears the download server is rejecting the slower 1Mbps speed (incorrectly, IMO).

Slower connection speeds shouldn't be made to be an issue. The user should be able to download across dial-up, if he's willing to endure the longer wait times.

**Comment by friism** [comment]
@InteXX are you only seeing this when pulling the windows base images, or also when pulling Linux images or non-base windows images?

**Comment by InteXX** [comment]
@friism Can you recommend a couple I might try?

**Comment by jasonbivins** [comment]
Hi @InteXX 
Try,  Ubuntu, AlpineLinux or Nginx 
Make sure you switch to linux containers in the GUI first.

**Comment by InteXX** [comment]
@jasonbivins — I was about to try, but then I found [this](https://redmondmag.com/articles/2017/04/20/windows-server-2016-getting-linux-containers.aspx). It seems that Linux containers aren't yet supported on Server 2016. (And this is Hyper-V, so there is no GUI.)

I think we've hit a dead-end on this one. Unless you've some further ideas?

**Comment by jasonbivins** [comment]
Hi @InteXX 

That's correct, since this is server 2016 you'll need to use Windows containers.

**Comment by InteXX** [comment]
@jasonbivins — Why did you close this? It's still an unresolved problem. I've seen others discussing it as well. The server shouldn't be disconnecting those with low-bandwidth connections.
