### ISSUE TITLE
Can't use journald despite it is list as logs plugin

### ISSUE THREAD

**Issue by lmussier** [docker/for-win#8562]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: CAF39F71-7659-48FC-83FE-784CC1CFCBE6/20200918093546

### Expected behavior
journald driver can be used

### Actual behavior
lmussier@box:~/workspace/build-em$ docker run hello-world --log-driver journald
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
0e03bdcc26d7: Pull complete
Digest: sha256:4cf9c47f86df71d48364001ede3a4fcd85ae80ce02ebad74156906caff5378bc
Status: Downloaded newer image for hello-world:latest
docker: Error response from daemon: failed to initialize logging driver: journald is not enabled on this host.
ERRO[0003] error waiting for container: context canceled

### Information
  - Windows Version: 2004
  - Docker Desktop Version: 2.3.0.5 (48029)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 26
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: journald
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.128-microsoft-standard
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 12.32GiB
 Name: docker-desktop
 ID: RANA:EYEO:Z2MT:EWPR:EEKM:UZJA:E4LI:WQBI:JJES:ABAB:W2IC:DMPT
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 40
  Goroutines: 51
  System Time: 2020-09-18T09:22:30.2196701Z
  EventsListeners: 3
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

### Steps to reproduce the behavior

docker run hello-world --log-driver journald

**Comment by stephen-turner** [comment]
All the log drivers are included as plugins in the upstream engine, but that doesn't mean they all work on Windows.

**Comment by lmussier** [comment]
Ok I see, is there any where we can see what is usable on windows ?
Because https://docs.docker.com/config/containers/logging/configure/ is pretty missleading to me :s

Thanks.

**Comment by stephen-turner** [comment]
Hmmm, that's a good question, but I don't know of anywhere that's written down. ☹️
