### ISSUE TITLE
Can't log into my docker hub account

### ISSUE THREAD

**Issue by othiagosouto** [docker/for-win#8566]
I don't know if this is the correct channel to report this issue but I'm trying this since i'm not being able to find the correct channel or some e-mail that I can contact docker team.

### Expected behavior
Login as expected

### Actual behavior
<img width="616" alt="image" src="https://user-images.githubusercontent.com/5900020/93606917-08254d00-f99f-11ea-95f0-c238e904bacc.png">

<img width="464" alt="image" src="https://user-images.githubusercontent.com/5900020/93606876-fb085e00-f99e-11ea-9823-964ab4d132b8.png">

### Information
I was trying to rename my user name on Docker Hub and the documentation told me that I should  [deactivate](https://hub.docker.com/settings/deactivate)  my account and wait for some email from dockerhub telling me that I can create another account using my e-mail... 

I never received that email and still facing that issues (presented on screenshots).
Does someone have any idea how I can solve this or the right channel for that?

Thanks!

**Comment by stephen-turner** [comment]
You can use https://hub.docker.com/support/contact/

**Comment by othiagosouto** [comment]
@stephen-turner thank you!
