### ISSUE TITLE
Docker Desktop fails to install/run with WSL2

### ISSUE THREAD

**Issue by dbgurevich2017** [docker/for-win#8573]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

0. Start with Windows 10 1903, 18362.2082
1. Start here: https://docs.docker.com/docker-for-windows/wsl/
2. Then go here: https://docs.microsoft.com/en-us/windows/wsl/install-win10 and install WSL2

Then try to install Docker Desktop in (https://docs.docker.com/docker-for-windows/wsl/) step 3 "From the Docker menu, select Settings > General."

"Use the WSL2 based engine" is disabled (greyed out) - Installation does not work.

**Comment by stephen-turner** [comment]
1903 support is only in Edge at the moment, not Stable.
