### ISSUE TITLE
WSL2 Screen black flickering on mouse cruse 

### ISSUE THREAD

**Issue by LiranETN** [docker/for-win#8577]
- [V] I have tried with the latest version of my channel (**Stable** or Edge)
  - [V] I have uploaded Diagnostics
  - Diagnostics ID: 0C00C2F5-53A9-4E82-85F6-DA8EB32902DD/20200919081943

### Expected behavior
work with Docker 
### Actual behavior
After installing WSL2 - Issues with screen --> turn black and flickers 
### Information

  - Windows Version: 2004 19041.508
  - Docker Desktop Version: 19.03.12, build 48a66213fe
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No. on my local laptop

### Steps to reproduce the behavior

I couldn't reproduced the same problem on my other Lenovo laptop so it seems to be something with specific Lenovo models as I found online reference to the same problem with other models.

Details:
After using Docker for a few hours or when waking up from sleep the screen starts blinking black and after few times keeps on black screen until restart and disable feature - **Windows Subsystem for Linux**

See video1 sample - [LINK](https://drive.google.com/file/d/1-t9HYzxwHebuZkc51MkWgqW6o2p420Sq/view?usp=sharing)
See video2 sample - [LINK](https://drive.google.com/file/d/1vKyDkdwNVu3225ezuezOm7B8r3TZRRN3/view?usp=sharing)

This issue happens only on my Lenovo IdeaPad S145-15IIL  (not appears on my other Lenovo U430p model)
I found another reference online for my problem here - 
https://answers.microsoft.com/tr-tr/windows/forum/all/wsl2-windows-10-pro-screen-blinking-problem/335a4dc9-4e46-4c74-bf96-3a4941da6197

I did the following:
1. reset my windows OS with clean iso
2. update all drivers and bios firmware
3. contacted Lenovo support and they replaced motherboard and screen

**Comment by stephen-turner** [comment]
This doesn't seem to have anything to do with Docker. It seems to be a Lenovo problem, or possibly WSL 2.
