### ISSUE TITLE
Can not start docker

### ISSUE THREAD

**Issue by ScottYang1982** [docker/for-win#8578]
diagnostic ID: 007FFCE6-E89E-48C2-BA2B-5FD8EA802CC9/20200919101707

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 007FFCE6-E89E-48C2-BA2B-5FD8EA802CC9/20200919101707

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by navarq** [comment]
on command line or command prompt try going to:

```
"C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" gather upload
```
