### ISSUE TITLE
 WSL 2 option  is greyead out even wsl is configured.

### ISSUE THREAD

**Issue by AlekseiKhatkevich** [docker/for-win#8582]
Hi
'Use the WSL 2 based engine (requires Win 10 build 19018+)' option in Docker windows is greyed out even wsl-2 is installed and Ubuntu and Alpine are running .

```
PS C:\Users\hardcase1\PycharmProjects\series> wsl -l -v
  NAME            STATE           VERSION
* Alpine          Stopped         2
  Ubuntu-20.04    Running         2
PS C:\Users\hardcase1\PycharmProjects\series>
```
![Снимок](https://user-images.githubusercontent.com/47420076/93672361-f208b100-fab2-11ea-90a5-fce06ec48acc.PNG)

is it a bug or i need to do anything else to activate it?

ALPINE:
```
hardcase:/mnt/c/Users/hardcase1$ cd PycharmProjects/series
hardcase:/mnt/c/Users/hardcase1/PycharmProjects/series$ docker-compose up -d

The command 'docker-compose' could not be found in this WSL 2 distro.
We recommend to activate the WSL integration in Docker Desktop settings.

See https://docs.docker.com/docker-for-windows/wsl/ for details.

hardcase:/mnt/c/Users/hardcase1/PycharmProjects/series$

```

Thanks

**Comment by simonferquel** [comment]
Hi, can you send a diagnostic file ?

**Comment by AlekseiKhatkevich** [comment]
Thank you for answering this.
Diagnostics Id is `EF7C2D4B-96F6-416F-9A

file links here:

[log.txt](https://github.com/docker/for-win/files/5254716/log.txt)
AC-A3032A8ACADC/20200921100807`

**Comment by simonferquel** [comment]
From the logs, I see that you have the wsl2 backport on windows 10 18362. Current stable version (2.3.0.5) does not support it yet. You can either wait for the next stable build, or switch now to our Edge channel which already supports it.

**Comment by AlekseiKhatkevich** [comment]
Solution helped, thanks.
