### ISSUE TITLE
Updater expands variables in the PATH environment variable

### ISSUE THREAD

**Issue by brunoyb** [docker/for-win#859]
I believe this could be happening when executing the installer also, but I didn't test with the installer, just with the self-update feature.

If before executing the update you had your PATH set to, for example:

```
%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files\Docker\Docker\Resources\bin;
```

it will become:

```
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Docker\Docker\Resources\bin;
```

after the update is done.

I just updated to the version posted below and experienced this issue. I actually have to update my PATH environment variable every time Docker releases an update. I use `%APPDATA%` in one of my paths, which is user dependant, so when it is expanded it becomes `C:\Users\<username>\AppData\Roaming` setting it to the current user which is not what I intended.

If you need more information, just tell me and I will try to provide it. Thanks!

Version 17.06.0-ce-win17 (12626)
Channel: edge
4bb7a7d

**Comment by ebriney** [comment]
It'll be fixed for next update

**Comment by nlaplante** [comment]
Just updated to new version and now the `docker` command is not found:

```
PS C:\Users\Nicolas> docker
docker : The term 'docker' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ docker
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (docker:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by ebriney** [comment]
@nlaplante : Strange, is `C:\Program Files\Docker\Docker\Resources\bin` in your system path ?

**Comment by brunoyb** [comment]
Hi! I just updated to the new edge version (details below). The changelog stated this was fixed, but the problem still persists. My PATH was changed to have all variables expanded just like the example I gave in the original report.

Version 17.06.1-ce-rc1-win20 (12818)
Channel: edge
28a0bb2

**Comment by brunoyb** [comment]
I just found out that `%APPDATA%` actually doesn't really work for what I was trying to do (not on the system environment anyway). But the bug report is still valid as the standard Windows 10 environment Path usually comes defined with `%SystemRoot%` in it, and after installing/updating Docker it becomes `C:\Windows`.

Thanks for your attention!

**Comment by brunoyb** [comment]
I just updated to the new version and it seems to be fixed on this last update. Thanks!

Version 17.07.0-ce-rc1-win21 (12927)
Channel: edge
76a8c4b
