### ISSUE TITLE
Unable to run hello-world on clean install.

### ISSUE THREAD

**Issue by glennsills** [docker/for-win#86]
### Expected behavior
PS C:\Users\glenn> docker run hello-world
results in hello-world image being pulled from docker.io

### Actual behavior
Program errors out with message:

C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/hello-world/images. You may want to check your internet connection or if you are behind a
proxy..

### Information
I ran the invoke-webrequest in the same powershell window and got the output below so I'm pretty sure my networking is OK.

`PS C:\Users\glenn> invoke-webrequest https://index.docker.io/v1/repositories/library/hello-world/images

StatusCode        : 200
StatusDescription : OK
Content           : [{"checksum": "", "id": "b1f526347a08c63813c014adf34170c03b99029bd3e5c80ac9e3f6ed8de3758e"},
                    {"checksum": "", "id": "70caadc460d7a99f861c2e6021547352da7fdb130bf0c3bde288cfa1c32944c4"},
                    {"checksum": ""...
RawContent        : HTTP/1.1 200 OK
                    Transfer-Encoding: chunked
                    Vary: Cookie
                    X-Docker-Endpoints: registry-1.docker.io
                    X-Frame-Options: SAMEORIGIN
                    Strict-Transport-Security: max-age=31536000
                    Content-Type: application...
Forms             : {}
Headers           : {[Transfer-Encoding, chunked], [Vary, Cookie], [X-Docker-Endpoints, registry-1.docker.io],
                    [X-Frame-Options, SAMEORIGIN]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 1932`

  - Diagnostic ID from "Diagnose & Feedback" in the menu.

9E735BCE-AA9B-412C-AAAE-7377A938C801/2016-09-16_07-38-06

  - a reproducible case if this is a bug, Dockerfiles FTW

NA

  - page URL if this is a docs issue or the name of a man page

NA

  - host distribution and version (Windows version, build number, etc)

Windows 10 Professional, 
Version: 1607
Build: 14393.187

### Steps to reproduce the behavior

  1. docker run hello-world
  2. ...

**Comment by dgageot** [comment]
@glennsills Thanks for the bug report. This is a known bug in version `1.12.0`. Please update to `1.12.1`

**Comment by dgageot** [comment]
Hi @glennsills Did version `1.12.1` fix the issue for you?

**Comment by glennsills** [comment]
@dgageot 

Yes, thanks.

**Comment by dgageot** [comment]
Thanks @glennsills closing the issue then!
