### ISSUE TITLE
Docker not starting after updating Windows 10 Pro with KB4571756 

### ISSUE THREAD

**Issue by Tzeny** [docker/for-win#8603]
- [x] I have tried with the latest version of my channel (Stable or ~~Edge~~)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B563EA59-E970-4C62-8F86-D38B61BF0F1D/20200921130852

### Expected behavior
I expected Docker to start.

### Actual behavior
Docker shows an error message when the system starts, and the icon is stuck in the 'Starting...' phase.

### Information

  - Windows Version: Windows 10 Pro 2004 19041.508 Windows Feature Experience Pack 120.2212.31.0
  - Docker Desktop Version: 2.3.0.5
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No
  - The problem appeared after updating Windows with KB4571756 

### Steps to reproduce the behavior

  1. Update Windows to KB4571756 
  2. Attempt to start docker

**Comment by stephen-turner** [comment]
This is a Windows bug, https://github.com/microsoft/WSL/issues/5880
