### ISSUE TITLE
Docker Desktop WSL2 backend service doesn't work with nushell as default shell

### ISSUE THREAD

**Issue by str4d** [docker/for-win#8619]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: FC91040D-7E8A-48E4-B26C-B78E23C8FD7D/20200922110519

### Expected behavior

`docker ps` command works in Ubuntu WSL2.

### Actual behavior

`docker ps` reports that WSL2 is not set up correctly. The Docker Desktop log file prints the following line every few seconds:
```
[TIMESTAMP][WslIntegrationAgent-Ubuntu][Info   ] TIMESTAMP unable to create ~/.docker/run directory: exit status 1
```

### Information
  - Windows Version: 2004, build 19041.508
  - Docker Desktop Version: Latest (installed today)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Install https://www.nushell.sh/ and configure it as the default Ubuntu shell.
  2. Install Docker Desktop with the WSL2 backend.
  3. Confirm that `docker ps` works in Powershell.
  4. Attempt to run `docker ps` in Ubuntu WSL2.

### Other details

Before discovering the log lines, I tried running the command in [this post](https://github.com/docker/for-win/issues/5096#issuecomment-572730439):
```
sudo /mnt/wsl/docker-desktop/docker-desktop-proxy --distro-name Ubuntu --docker-desktop-root /mnt/wsl/docker-desktop
```
which reported that the `docker` group was missing. I created it with `sudo addgroup docker` followed by `sudo adduser USERNAME docker`, and then after running the command again, I was able to run `sudo docker ps`.

After Ctrl+C-ing the `docker-desktop-proxy` process, now any `docker` command reports:
```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
````
instead of the previous "set up WSL2" message. I can't figure out what global config was set by `docker-desktop-proxy` that is causing this persistence.

**Comment by simonferquel** [comment]
Hi, thanks for the report. I'll have a quicklook today.

**Comment by simonferquel** [comment]
Reproduced, working on a fix.
