### ISSUE TITLE
New docker version randomly disconnects from -it session

### ISSUE THREAD

**Issue by MichaelLogutov** [docker/for-win#862]
### Expected behavior
Docker -it session should stay active indefinitely

### Actual behavior
Short after successfully entering an interactive session docker randomly terminates the session without any errors or messages.

### Information
Diagnostic ID: D396C6BD-E52B-406B-8BA1-4EF87E0F68C8/2017-06-29_10-58-03
**It started today after update to the recent version.**

### Steps to reproduce the behavior
1. do `docker run -d -p 80:80 --name test microsoft/aspnet:4.6.2-windowsservercore-10.0.14393.1358`
2. then `docker exec -it test powershell`
3. do some commands (like `ls; cd \inetpub\logs; ls`)
4. after a while the session will terminate and you'll be back to original powershell session

**Comment by cgudrian** [comment]
I have the same problem. On my system (DD17E15B-5BBA-4721-B020-8313A4BE1671/2017-07-07_11-13-47) the following steps suffice to reproduce the problem:
1. start `docker run -it alpine`
1. press the keys `A` and `B` simultaneously
1. the session no longer accepts key strokes and can only be terminated by `CTRL+C`

**Comment by cgudrian** [comment]
The Docker client running on the Windows Subsystem for Linux connected via TCP to the Windows Docker host does not exhibit this behavior. It seems to be an issue with the Docker client for Windows only.

**Comment by cgudrian** [comment]
I just upgraded to the Windows 10 Fall Creators Update which obviously solves this issue.

**Comment by kjdyck** [comment]
I still see this on Windows 10 Enterprise with 17.09.1-ce-win42 (14687). Pressing two keys simultaneously either detaches or freezes interactive sessions.
