### ISSUE TITLE
Switching to Windows Containers Crashes Docker Desktop

### ISSUE THREAD

**Issue by cgayers** [docker/for-win#8634]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: FD8194B1-6538-4868-9B46-2E0E72EA9ECE/20200923134038

### Expected behavior
Select 'Switch to Windows Containers' and successfully switch

### Actual behavior
Select 'Switch to Windows Containers' and an error occurs. Attempted a reset to factory defaults, but this did not help.

### Information

  - Windows Version: Microsoft Windows [Version 10.0.19041.388]
  - Docker Desktop Version: 2.3.0.5 (48029)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Start Docker Desktop
  2. Click 'Switch to Windows Containers'

Crash Report: FD8194B1-6538-4868-9B46-2E0E72EA9ECE/20200923133701

**Comment by PranjalGohain** [comment]
I have the same issue
