### ISSUE TITLE
Quiesce the "Hyper-V feature is not enabled" prompt on every login

### ISSUE THREAD

**Issue by jstangroome** [docker/for-win#864]
I have installed Docker for Windows 17.06 CE on a machine with both Windows 10 (Build 16199.1000) and Virtualbox 5.1.13.

Now, each time I login to Windows I am presented with a dialog titled "Docker for Windows" and with the message "Hyper-V feature is not enabled. Do you want to enable it for Docker to be able to work properly? Your computer will restart automatically. Note: VirtualBox will no longer work.". The only options are "Ok" or "Cancel".

I intend to use the Docker Client on Windows to manage the Docker daemon on remote systems and in custom virtual machines that are unrelated to the boot2docker VM included with Docker for Windows. As such I have no intention of enabling Hyper-V but I am prompted to enable Hyper-V on every login.

It seems installing Docker for Windows is the supported and recommended way to obtain the Docker Client. I could not find a way to install the client without the server/daemon components.

### Expected behavior
The prompt to enable Hyper-V should offer a "No, don't ask me again" option.

### Actual behavior
I have to click "Cancel" on the popup on every login.

**Comment by friism** [comment]
I recommend just getting the `docker.exe` binary from here: https://download.docker.com/win/static/stable/x86_64/

Unzip and put it somewhere in your path.

Let us know if that doesn't work.

**Comment by jstangroome** [comment]
Hi @friism 

Thanks for the tip. I used to obtain v1.13 and earlier via a similar approach, ie I went to https://github.com/docker/docker/releases (which is now https://github.com/moby/moby/releases) and downloaded the Windows 64-bit archive. This works.

However, the GitHub Releases for the current versions now just link to the Docker Store at https://store.docker.com/search?type=edition&offering=community and explicitly note that the old packages won't be updated. The Store does not appear to list a Client-only option.

Where is the URL you shared (https://download.docker.com/win/static/stable/x86_64/) documented?

Perhaps instead of being able to silence the "Enable Hyper-V" popup, the documentation for installing Docker just needs to be updated with where to find the latest Client for Windows.

**Comment by friism** [comment]
> Where is the URL you shared documented?

It's not documented because it's not officially supported. We're making it available as a courtesy for users with specialized setups like your.

Another alternative for you would be to install Docker Toolbox for Windows: https://docs.docker.com/toolbox/overview/#whats-in-the-box

**Comment by jstangroome** [comment]
I considered the Docker Toolbox but the documentation I read gave the impression it was being phased out.

To clarify, the Docker Client on Windows is only officially supported if the Docker Client is used to manage the Docker Daemon in the boot2docker VM on the same machine? Using the `docker --host` parameter is unsupported?

Thank you for your patience.

**Comment by friism** [comment]
We'll keep shipping Docker Toolbox as new versions of Docker shows up.

Docker for Windows is meant as a full Docker development environment for building and running Docker containers. It relies on Hyper-V and if you install it, it will continue to bug you about enabling Hyper-V if that's not working.

**Comment by jstangroome** [comment]
I found myself avoiding Toolbox because the documentation for Toolbox begins with the large print warning:

>**Legacy desktop solution.** Docker Toolbox is for older Mac and Windows systems that do not meet the requirements of Docker for Mac and Docker for Windows. We recommend updating to the newer applications, if possible.

And it appears in the sidebar navigation tree as "Docker Toolbox (legacy)".

This gave me the distinct impression that it would not keep shipping for newer Docker versions. Perhaps this messaging could be updated to clarify that it is still the supported method for installing the Docker Client going forward.
