### ISSUE TITLE
Mounted volume not accessible after a while 

### ISSUE THREAD

**Issue by infa-daliu** [docker/for-win#8643]
- [x] I have tried with the latest version of my channel (Stable)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 70D94F7B-8110-41E3-B002-BFE97CF6983B/20200924013736

### Expected behavior
Mounts: 
/VAR/ACTIVEVOS/TOMCAT_AI : /host_mnt/c/src/myspace/deployments/dist/tomcat

When the container started,  /VAR/ACTIVEVOS/TOMCAT_AI is accessible and should to be accessible until container is stopped. 

### Actual behavior
When the container started,  /VAR/ACTIVEVOS/TOMCAT_AI is accessible, in a few minutes /VAR/ACTIVEVOS/TOMCAT_AI became NOT accessible anymore. Any command on the directory will just hang.  

![image](https://user-images.githubusercontent.com/50430568/94092991-184b8b00-fdea-11ea-8a46-71c13efc977f.png)

### Information
  - Is it reproducible? Yes, with the docker file and docker-compose. 
  - Is the problem new?  Yes
  - Did the problem appear with an update?  After 2.3.0.3
  - Windows Version: Win 10, 1909 Build 18363.1016
  - Docker Desktop Version: 2.3.0.5 (48029)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: NO

### Steps to reproduce the behavior

  1. Not consistent.  The same process encounters the problem 4 out of 5 runs. Sometime it passes.

**Comment by stephen-turner** [comment]
Thanks for the report. @djs55 PTAL.
