### ISSUE TITLE
Issue WSL 2 usage still requires Win 10 Build 19018+

### ISSUE THREAD

**Issue by ykursav** [docker/for-win#8660]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
As WSL2 backported to win 10 build 18362 and 18363. It should be enabled to use docker desktop WSL in those builds.

### Actual behavior
WSL2 option grayed in settings.

### Information

  - Windows Version: Windwos 10 18363.1082
  - Docker Desktop Version: 2.3.0.5
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No virtualization

### Steps to reproduce the behavior

  1.  Right click docker icon from tray and select settings.
  2. In general tab, you can see WSL2 option grayed out.

Screenshot:
![image](https://user-images.githubusercontent.com/13722374/94249296-fa804200-ff1f-11ea-9bcb-cee8c23485a5.png)

**Comment by simonferquel** [comment]
Stable version does not currently support WSL 2 backport. Next build will work though. If you are in a rush, you can move to the Edge channel, which already supports it.
