### ISSUE TITLE
Docker Dashboard does not display containers which have been started before Dashboard start

### ISSUE THREAD

**Issue by gjamnitz** [docker/for-win#8661]
In Docker Desktop release 2.3.0.5 (Windows) Docker Dashboard only displays running containers which have been started after Docker Dashboard started (and even not all of them). If I restart Docker Dashboard after I started several containers, it just displays "No containers running".
In addition to that I'd like to mention that Docker Dashboard is continuously and intentionally losing its functionality , e.g. in previous releases it displayed stopped containers, and it was very useful functionality to check & start them. Now it has been removed from the last releases.

**Comment by stephen-turner** [comment]
I believe both of these are working correctly in the latest Edge release. You can try that release, or wait until next week when we will have a new Stable release.
