### ISSUE TITLE
Dashboard not opening on doubleclick

### ISSUE THREAD

**Issue by 888iee** [docker/for-win#8665]
- [x] I have tried with the latest version of my channel -> Stable
  - [ ] I have uploaded Diagnostics

### Expected behavior
When I doubleclick Docker Desktop shortcut I expect it to open the Dashboard.

### Actual behavior
It probably checks if docker is running and if not it's starting it but not showing anything except the tray icon

### Information
  - Windows Version: Version 2004 (Build 19041.508)
  - Docker Desktop Version: 19.03.12, build 48a66213fe

I think this is more of a feature request instead of a bug.
I know that I can open the dashboard with rightclicking the tray icon and navigating to dashboard, but what is the shortcuts purpose in the first place, when docker runs on startup.

-- Greetings 888iee

**Comment by stephen-turner** [comment]
Already fixed in the latest Edge release.
