### ISSUE TITLE
Docker Desktop doesn't support enabling WSL 2 as backend

### ISSUE THREAD

**Issue by Ferido07** [docker/for-win#8666]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: A4909E7C-BE10-4E3D-BCA6-3A023B529ED8/20200926123349

### Expected behavior
The option "Use the WSL 2 based engine (requires Win 10 build 19018+)" in settings enabled so it can be checked.
### Actual behavior
The option "Use the WSL 2 based engine (requires Win 10 build 19018+)" is not enabled and cannot be checked.
### Information

  - Windows Version: Version 1903 (OS Build 18362.1082)
  - Docker Desktop Version: 2.3.0.5(48029) stable
  - Its running on Windows 10 Pro on a Dell Inspiron PC with WSL version 2 enabled and Ubuntu 20.04 installed

### Steps to reproduce the behavior
1. Had a docker version 2.2.x.x
2. Enabled WSL for windows
3. Installed Ubuntu 20.04
4. Installed "WSL2 Linux kernel update package for x64 machines"
5. Set the default version to WSL 2 for Ubuntu 20.04  using (wsl --set-version Ubuntu-20.04 2)
6. Set the default version to WSL for all new installation using  (wsl --set-default-version 2)
7. Uninstalled previous version and installed Docker Desktop Version: 2.3.0.5(48029) stable
8. Uninstalled and re-installed again, purged data, reset to factory default and it still didn't work

### More info
Running `wsl -l -v` gives
>  NAME            STATE           VERSION
> Ubuntu-20.04    Running         2

**Comment by anveo** [comment]
I ran into this as well. Switching to the edge version fixed the problem for me.

**Comment by Ferido07** [comment]
Thanks @anveo it worked for me as well. Now my docker version is 2.3.7.0
948173) edge for anyone else who wants to know which version worked for me.
