### ISSUE TITLE
Windows containers are not supported by your Windows version. Check documentation for minimum requirements

### ISSUE THREAD

**Issue by yonnywei** [docker/for-win#8679]
install successful，but can not run client application！
![image](https://user-images.githubusercontent.com/17950252/94383920-f6e4f900-0173-11eb-9722-19b7741ccdaa.png)
![image](https://user-images.githubusercontent.com/17950252/94383940-05cbab80-0174-11eb-9146-55be275cba7d.png)

**Comment by stephen-turner** [comment]
I can't understand which version of Windows this is as I don't read Chinese, but the error message seems clear.
