### ISSUE TITLE
Ingress network does not publish port

### ISSUE THREAD

**Issue by Zordaxy** [docker/for-win#8694]
### Information
I'm working on Windows server Version 1809 (OS Build 17763.1457) running in VM.
Installed latest docker as for yesterday.

### Steps to reproduce the behavior
Trying to launch IIS container in ingress network:
docker service create --name=s1 --publish target=80, published:60820 web_1 powershell -command {echo sleep; sleep 360000;}
service is launched, but I don't have access to it like:
curl 10.1.8.80:60820
10.1.8.80 - my host IP
60820 - published port.

It doesn't work with custom overlay network either.

It works with mode=host. But in this case I don't get routing mesh load balancing.

Windows Server 2019 should have routing mesh. But I can't access any service other then with "mode=host".

### Expected behavior
Should get response like:
PS C:\Users\...\> curl 172.20.111.24:80

StatusCode        : 200
StatusDescription : OK
Content           : Hello!
                    <p>Service 2</p>
RawContent        : HTTP/1.1 200 OK
                    Accept-Ranges: bytes
                    Content-Length: 24
                    Content-Type: text/html
                    Date: Mon, 28 Sep 2020 20:29:14 GMT
                    ETag: "033f1bfd095d61:0"
                    Last-Modified: Mon, 28 Sep 2020 19:51:26 GMT
                    Server:...
Forms             : {}
Headers           : {[Accept-Ranges, bytes], [Content-Length, 24], [Content-Type, text/html], [Date, Mon, 28 Sep 2020 20:29:14
                    GMT]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : System.__ComObject
RawContentLength  : 24

Ingress network details:
PS C:\Users\avovchuk\Desktop\nginx> docker network inspect ingress
[
    {
        "Name": "ingress",
        "Id": "ltg7ztkk57vvov1a1ekpg425b",
        "Created": "2020-09-28T13:02:07.201867-07:00",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.0.0/24",
                    "Gateway": "10.0.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": true,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "768e103d8c8c14eae05aa1f175472b2f9b510571eb739404093573b3bcd5f423": {
                "Name": "s5.1.s851zpeax97y48pyigp8wdmbh",
                "EndpointID": "1b8e84bc8b9f156f2acf853faa90cb4b63a3edff4715fe04d0e4f31e6138961e",
                "MacAddress": "00:15:5d:c8:14:c2",
                "IPv4Address": "10.0.0.6/24",
                "IPv6Address": ""
            },
            "ingress-sbox": {
                "Name": "ingress-endpoint",
                "EndpointID": "fcfac16fa1b5bb4dadc4bc4503ba226fe20d3374971b6db9b562ec9ec98d3023",
                "MacAddress": "00:15:5d:c8:1e:cc",
                "IPv4Address": "10.0.0.2/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4096",
            "com.docker.network.windowsshim.hnsid": "F018BF03-D32D-4F96-91AF-B6440B6AD30A"
        },
        "Labels": {},
        "Peers": [
            {
                "Name": "c6160dcd9069",
                "IP": "10.1.8.80"
            }
        ]
    }
]

### Actual behavior
Get:
curl : Unable to connect to the remote server
At line:1 char:1
+ curl 10.1.8.80:60858
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by s13n4** [comment]
Actually, we are facing the same issue.
We have ingress network created on top of Win 2019 1776.1397 and there is no issue.
When you install KB4570333 or latest one (KB4577069) and you try to docker service create you will not be able to connect to this service by calling it directly (the node specific ip).
If you uninstall secruity updates and system reverts to 1397 it starts working again.

**Comment by Zordaxy** [comment]
It looks like the same issue as https://github.com/moby/moby/issues/40998#issuecomment-658473481
Regression in Windows Server 2019 since April-May.
