### ISSUE TITLE
Docker Desktop doesn't start anymore even after a factory reset and full re-install. The error remains and has something todo with WSL2 provisioning

### ISSUE THREAD

**Issue by michael-nischt** [docker/for-win#8696]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 8379D94F-275B-439B-8F42-91562A238B1D/20200929065452

### Information

  - Windows Version: Windows 10 Pro - build: 19041.450
  - Docker Desktop Version: latest stable
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by quanwei1829** [comment]
win10 内部版本号太低，我遇到的也是这个问题 ，把win10更新到最新版本号就可以了

**Comment by michael-nischt** [comment]
For some reason Windows 10 PRO decided to deactivate Hyper-V with an update. Re-enabling it solved the issue. 

Maybe a warning it isn't active would help others affected?
