### ISSUE TITLE
Windows shared drives auth/permission issue

### ISSUE THREAD

**Issue by jneale** [docker/for-win#870]
### Expected behavior
From Settings > Shared Drives select the drive to share, hit apply and providing correct windows credentials updates the settings so the drive is shared.

### Actual behavior
Credentials are accepted but Docker refreshes with all Shared Drives being reset/unchecked.

### Information

  - Diagnostic ID: B99E99F3-B235-496C-A0AB-BAB2626B73A2/2017-06-29_20-56-17
  - Windows 10 Pro 64-bit

### Steps to reproduce the behavior

  1. From Settings > Shared Drives select the drive to share.
  2. Hit Apply.
  3. Provide user/pass.
  4. Drive is not shared - checkbox is now unchecked.
 
  * Credentials can be proven to be correct by providing an invalid credential to which Docker shows an error not shown with correct credentials.

### Workaround

   1. Exit Docker.
   2. Start -> Docker for Windows -> Right click -> Run as Administrator
   3. Update Shared Drive settings.
   4. Exit Docker and restart (non-admin mode)

**Comment by Angelinsky7** [comment]
Hi,
The workaround is not working anymore on the latest version :
Version 17.06.0-ce-win18 (12627)
Channel: stable
d9b6651

**Comment by jneale** [comment]
I'm also using that version. I had previously changed memory allocation but left it alone after factory reset so that could well have something to do with it.

**Comment by wiktor-k** [comment]
I've also observed that changing memory messes up sharing in a very weird way and I've set up Docker stable and edge 10 times already and fortunately stumbled upon this workaround that works... until my containers do not need more memory that is.

**Comment by Dargmuesli** [comment]
For me the workaround does *not* work with the latest update (19) :/

**Comment by wiktor-k** [comment]
The "workaround" that I've successfully used this time was migration back to Docker Toolbox (yes, the one with VirtualBox). Shared drives just work. Adjusting memory and CPU work. The docker daemon there looks like a newer version too. The only downside is having to use docker machine but that's hardly a problem when the alternative doesn't have volumes working.

**Comment by Dargmuesli** [comment]
Try the newest Edge build. Version 17.06.1-ce-rc1-win20 (12818). The issue is fixed for me there.

**Comment by wiktor-k** [comment]
Thanks for the heads up @Dargmuesli but I'm going to wait until Docker for Windows "stabilizes" a little bit. That's not the only issue I had with Docker for Windows. For me even the "stable" release seems like a "beta" at most.

**Comment by Angelinsky7** [comment]
It seems that if i change either the cpu or the ram setting the volume sharing does not work anymore.
but with a fresh install without touching those settings. i can use the sharing....

Version 17.06.0-ce-win19 (12801)
Channel: stable
c98c1c2

**Comment by wiktor-k** [comment]
@Angelinsky7 did you try the Edge build as mentioned by @Dargmuesli [here](https://github.com/docker/for-win/issues/870#issuecomment-317880633)?

**Comment by Angelinsky7** [comment]
@wiktor-k not yet... i need to try

**Comment by bsienn** [comment]
this is really stupid. I'm still having this issue with latest setup

**Comment by CaliRobC** [comment]
Same problem though was working on hyper-v.  Reseting to factory defaults got me unstuck on this.
