### ISSUE TITLE
Unable to setup the WSL 2 integration with docker

### ISSUE THREAD

**Issue by seroche** [docker/for-win#8706]
Hi guys,

I have been trying to setup docker to use WSL2 for quite some times now... 
I installed / re-installed everything several times starting with WSL2 and ending with docker desktop (to respect the order of installation).

 WSL2 setup is working since I can access/use my Ubuntu 20.04 distribution running on top of WSL2

  - [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: FE261AF2-7A6F-4B31-B0D3-A64B184493B7/20200929131230

### Expected behavior
- When starting Docker, the WSL2 integration option should be available. Currently it's grayed out.
- I should see two Docker distributions (docker-desktop-data & docker-desktop) when I run `wsl -l -v`

### Actual behavior
- No distribution is created
- Integration to WSL2 option is grayed out

### Information
  - Windows Version: 1909 build 18363.1082
  - Docker Desktop Version: latest stable 2.3.0.5
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: NO

### Steps to reproduce the behavior
  1. Install WSL2
  2. Install Docker Deskop Stable

**Comment by stephen-turner** [comment]
WSL 2 support for Windows 1903 and 1909 is currently only in the Edge release, it hasn't reached Stable yet.
