### ISSUE TITLE
Docker fails to start after update on 2020-09-30 (today)

### ISSUE THREAD

**Issue by nxproject** [docker/for-win#8724]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 774C841A-7691-4C5A-A2BA-6B592B33E691/20200930155422

### Expected behavior
Docker to start up when computer is started

### Actual behavior
Docker stays in loading state

### Information

  - Windows Version: Windows 10 Pro 1909
  - Docker Desktop Version: - Cannot get to Docker
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by DaleyKD** [comment]
I can try to add a little more information to this ticket if it's anything like my issue.

I'll assume this is for 2.4.0.0 (48506).  No matter what we do, docker refuses to start.  I've tried to uninstall it and do a fresh install, trying both 2.4.0.0 and 2.3.0.5 with upgrade to 2.4.0.0.  You can't get Reset to Defaults to do anything in 2.4.0.0.  You can't run diags.

I'm running Windows 10 2004.

I hope we can get some traction on this ASAP.

**Comment by thiago-trybe** [comment]
up

**Comment by bedla** [comment]
same here, I am getting just error dialog with

```
System.NullReferenceException:
Odkaz na objekt není nastaven na instanci objektu.
   v Docker.Engines.IsoConfig.Meta(Object value) v C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\IsoConfig.cs:řádek 146
   v Docker.Engines.IsoConfig.GenerateConfig(Settings settings) v C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\IsoConfig.cs:řádek 82
   v Docker.Engines.IsoConfig.WriteJson(Settings settings) v C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\IsoConfig.cs:řádek 47
   v Docker.Engines.WSL2.WSL2Configurator.PrepareConfiguration(Settings settings) v C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Configurator.cs:řádek 19
   v Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__25.MoveNext() v C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:řádek 106
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() v C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:řádek 29
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() v C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:řádek 67
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   v Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() v C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:řádek 92
```

**Comment by nxproject** [comment]
What I did:

Opened TROUBLESHOOT page

Reset to factory defaults

Waited for five minutes while it reset WHICH NEVER COMPLETED

Restarted computer

Opened SETTINGS page

Disabled WSL2

Applied and restarted

FYI: Not sure if 5 through 7 are needed, but I rather be operational than have other issues.

**Comment by nxproject** [comment]
Follow up:

I had a chance to test the process and these are the steps that solved my issue:

1) Opened TROUBLESHOOT page

2) Reset to factory defaults

3) Waited for five minutes while it reset WHICH NEVER COMPLETED

4) Restarted computer

Enabling the WSL2 based engine seems to work fine.

**Comment by stephen-turner** [comment]
Thanks, we'll have a look.

**Comment by simonferquel** [comment]
@nxproject from your logs, it seems that you got in a state where WSL2 itself was malfunctioning:
```
[08:24:44.767][WslKeepAlive      ][Warning] stopped unexpectedly. stdout:
The Windows Subsystem for Linux instance has terminated.
```
Then every wsl operation done by docker desktop (and probably, at this time any wsl command you would try to run yourself) failed with:
```
[08:25:01.013][LinuxWSL2Engine   ][Info   ] The operation timed out because a response was not received from the virtual machine or container.
```

We have seen this before when a process listen on port 53 on the windows host (this actually happens when running Windows containers) and it is a known issue from Microsoft.

**Comment by simonferquel** [comment]
@bedla there is a bug in our http proxy parsing. There is a workaround for that though:
- edit your settings file at `C:\Users\<username>\AppData\Roaming\Docker\settings.json`
- change "overrideProxyExclude" from null to `""`
- save and restart Docker Desktop

**Comment by nxproject** [comment]
simon:  All I can tell you is the sequence of what I did:

1) Installed the update that displays the images as well as the containers *great addition)

2) Rest of the day, I had no issues

3) Shutdown for the day

4) Started next day and Docker would not start

I have been using Win 10 Docker support for a while now, and until this update, no issues whatsoever.  My work with Docker is via Docker.Dotnet 3.125.2, except for when I had to inspect images, which I have been doing with the Docker CLI.  I do not use WSL2 directly.

**Comment by nxproject** [comment]
simon:  It was already "".  This is what probably happened when I used the troubleshoot page in the Docker Desktop and did Reset to factory defaults.  After that things started properly.

**Comment by major-mayer** [comment]
FYI: Resetting all docker containers/ images to factory defaults also did the trick for me.
I reinstalled Docker for Windows too, but i dont know if this was nessecary.

I mean it's okay, but keep in mind that this will delete all your containers and whatsover

**Comment by bedla** [comment]
> @bedla there is a bug in our http proxy parsing. There is a workaround for that though:
> 
> * edit your settings file at `C:\Users\<username>\AppData\Roaming\Docker\settings.json`
> * change "overrideProxyExclude" from null to `""`
> * save and restart Docker Desktop

@simonferquel I can confirm workaround is correct, thx

**Comment by nxproject** [comment]
All:  One FYI item.  It seems that if CPU intensive work happens while Docker is trying to start, the process fails and never completes the startup process.  I can duplicate but since the Docker Desktop is not available, I do not have a way to run diagnostics.  If the computer is restarted and Docker allowed to startup, everything is back to normal. 

If you have any ideas on  how I can get some information for you, let me know.  The only thing that I can tell you is that once it fails, the process is dead, 0% CPU utilization.

**Comment by simonferquel** [comment]
@nxproject we keep logs from previous docker-desktop launches. So next time it happens, you can restart your computer and send a diagnostic from there.

**Comment by simonferquel** [comment]
Also, when you get into this state, can you try to run your own WSL2 distro ? (there is a high chance it fails, which would confirm a bug from WSL or Windows itself)

**Comment by nxproject** [comment]
Simon:  In regards to you two comments:

1) Logs - I need to know how to get the logs before I attempt to get the process to fail at startup, as I need to keep working and for that I need a running Docker, so I cannot be down for long.

2) WSL2 - I need to know what commands to be run where, as I have no clue of that which thou speaketh.
