### ISSUE TITLE
I WAS ABLE TO GET DOCKER TO RUN AGAIN!!

### ISSUE THREAD

**Issue by nxproject** [docker/for-win#8725]
What I did:

1) Opened TROUBLESHOOT page

2) Reset to factory defaults

3) Waited for five minutes while it reset WHICH NEVER COMPLETED

4) Restarted computer

5) Opened SETTINGS page

6) Disabled WSL2

7) Applied and restarted

FYI:  Not sure if 5 through 7 are needed, but I rather be operational than have other issues.

**Comment by stephen-turner** [comment]
Thanks @nxproject, could you please add this comment to your previous ticket, #8724, in case it helps someone. Thanks.
