### ISSUE TITLE
Docker will not start after update 

### ISSUE THREAD

**Issue by Ray-E-Artz** [docker/for-win#8727]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Ray-E-Artz** [comment]
Diagnostics id 83AF5B05-4180-4450-95AF-4BC9E241B594/20200930184914

**Comment by garzawebdesign** [comment]
I had a similar issue less than an hour ago after updating to the latest version of Docker.  Please note: I'm using Docker in a WSL2 environment. During troubleshooting, I found that Docker was no longer integrated with Ubuntu (Settings>Resources>WSL Integration).  I turned on Ubuntu and rebooted my PC.  It then started to work.  I hope this works for you.

**Comment by SAnDAnGE** [comment]
Diagnostic ID: 752F9AED-59C3-41FC-A665-07F195D48822/20201001052334
@garzawebdesign Unable to apply and restart docker.

**Comment by stephen-turner** [comment]
Possibly a dupe of #8724.

**Comment by SAnDAnGE** [comment]
For me docker starts, while the error message is displayed:
```
❯ docker ps -a
WARNING: unable to unmarshal config file C:\Users\<User>\.docker\config.json: invalid character '\x00' looking for beginning of value
WARNING: Error loading config file: C:\Users\<User>\.docker\config.json: invalid character '\x00' looking for beginning of value
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

**Comment by simonferquel** [comment]
@Ray-E-Artz it seems that docker started but the integration with wsl failed because of docker cli settings file loading.
Can you try removing ~/.docker/config.json (within the wsl file system) ?

**Comment by garzawebdesign** [comment]
@SAnDAnGE for clarification, I was getting a "Failed to start: Unable to listen on required ports, localhost port 8037 is in use" error.  I'm running DDEV on Docker in WSL2.  It seems the Docker update itself turned off WSL integration (in my case Ubuntu) which, once re-enabled, fixed the post-update problems for me.

**Comment by Ray-E-Artz** [comment]
Actually, what finally worked for me (after several times
uninstalling, re-installing, etc.)  was deleting the (corrupted) file
<user>\.docker\config.json.  (All this was after a docker upgrade; docker
had been working for me before then.)  This was on Windows 10.
