### ISSUE TITLE
docker cp does not work correctly from container to host

### ISSUE THREAD

**Issue by vikalyan** [docker/for-win#873]
### Expected behavior

Based on the docker cp documentation here: [docker cp docs](https://docs.docker.com/engine/reference/commandline/cp/#extended-description).

to copy the contents of an existing directory in the container to an existing directory on the host, I am supposed to do something like:-

```docker cp CONTAINER:<DirectoryPath>\. <HostPath>```

In order to copy the directory itself, I just do:

```docker cp CONTAINER:<DirectoryPath> <HostPath>```

As an example:-

```docker cp mycontainer:c:\foo\. d:\bar```

should copy the contents of c:\foo in the container into the host path at d:\bar.

### Actual behavior

Command fails with ```GetFileAttributesEx \\?\Volume{GUID}\foo\.: The file name, directory name, or volume name label syntax is incorrect.``` error.

### Information

Windows Server 2016 datacenter.
Docker version 17.03.1-ee-3, build 3fcee33

Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 9
Server Version: 17.03.1-ee-3
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1358.amd64fre.rs1_release.170602-2252)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 31.91 GiB
Name: vikalyan-hp
ID: MSUS:RBBE:S7DG:GJRX:KQ5U:B7QM:OANM:BWBC:UOOY:6B3A:RA6O:GEDP
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 18
 System Time: 2017-06-29T22:54:49.1175456-07:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by vikalyan** [comment]
@jhowardmsft

**Comment by jhowardmsft** [comment]
Remove the trailing . on the container path in the cp command:

```
Microsoft Windows [Version 10.0.17663.1044]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\>mkdir \containerpath
Microsoft Windows [Version 10.0.17663.1044]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\>mkdir containerpath

C:\>cd containerpath

C:\containerpath>copy \License.txt
        1 file(s) copied.

C:\containerpath>copy \windows\System32\ntasn1.dll
        1 file(s) copied.

C:\containerpath>dir
 Volume in drive C has no label.
 Volume Serial Number is D422-C545

 Directory of C:\containerpath

05/14/2018  03:47 PM    <DIR>          .
05/14/2018  03:47 PM    <DIR>          ..
05/03/2018  05:05 AM             1,894 License.txt
05/03/2018  03:31 AM           215,792 ntasn1.dll
               2 File(s)        217,686 bytes
               2 Dir(s)  21,290,213,376 bytes free

C:\containerpath>exit
k
C:\Users\Administrator>docker ps -a
CONTAINER ID        IMAGE                         COMMAND             CREATED             STATUS                     PORTS               NAMES
c4fb60dccf80        microsoft/windowsservercore   "cmd"               22 seconds ago      Exited (0) 4 seconds ago                       happy_rosalind

C:\Users\Administrator>mkdir c:\hostpath

C:\Users\Administrator>docker cp c4fb60:c:\containerpath\. c:\hostpath
Error response from daemon: GetFileAttributesEx \\?\Volume{6c7696cf-57c8-11e8-976a-90472fd7e367}\containerpath\.: The filename, directory name, or volume label syntax is incorrect.

C:\Users\Administrator>docker cp c4fb60:c:\containerpath\ c:\hostpath

C:\Users\Administrator>dir c:\hostpath
 Volume in drive C has no label.
 Volume Serial Number is DCF9-371B

 Directory of c:\hostpath

05/14/2018  03:48 PM    <DIR>          .
05/14/2018  03:48 PM    <DIR>          ..
05/14/2018  03:47 PM    <DIR>          containerpath
               0 File(s)              0 bytes
               3 Dir(s)  99,495,567,360 bytes free

C:\Users\Administrator>dir c:\hostpath\containerpath
 Volume in drive C has no label.
 Volume Serial Number is DCF9-371B

 Directory of c:\hostpath\containerpath

05/14/2018  03:47 PM    <DIR>          .
05/14/2018  03:47 PM    <DIR>          ..
05/03/2018  05:05 AM             1,894 License.txt
05/03/2018  03:31 AM           215,792 ntasn1.dll
               2 File(s)        217,686 bytes
               2 Dir(s)  99,495,567,360 bytes free

C:\Users\Administrator>
```

**Comment by vikalyan** [comment]
@jhowardmsft - According to https://docs.docker.com/engine/reference/commandline/cp/#extended-description that's not the right scenario. Using `.` at the end implies that the contents of `C:\containerpath` should be copied into the folder `C:\hostpath`. Removing `.` does not conform to the Docker client documentation.

**Comment by jhowardmsft** [comment]
Can you open this upstream in moby/moby - that would be where it would need to be fixed if the workaround I gave above isn't good enough for your needs.
