### ISSUE TITLE
Docker Backend not starting after Upgrade to 2.4.0.0

### ISSUE THREAD

**Issue by dannygroebner** [docker/for-win#8737]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 93D65670-D9FF-40B0-A211-B470A00F6446/20201001060640

### Expected behavior

Docker Backend starts and is ready to launch containers after a while

### Actual behavior

Docker stays in "is starting" Mode and never get ready.

### Information

  - Windows Version: Windows 10 1009 (Build: 18363.1082)
  - Docker Desktop Version: 2.4.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. Start Docker Desktop
  2. Never gets ready

**Comment by kCzene** [comment]
In Hyper-V manager the DockerDesktop virtual machine dissapeared after the install :(

**Comment by dannygroebner** [comment]
I activated WSL 2 at the request dialog after the Update of Docker for Windows. So i think it shouln't use Hyper-V anymore

**Comment by pbois34** [comment]
As kCzene said, in Hyper-V manager the DockerDesktop virtual machine has disappeared too on my computer but not the disk. How do I recreate the virtual machine from Disk  ?

**Comment by kCzene** [comment]
I backup the vm-data folder content and uninstall Docker Dektop 2.4 and reinstall 2.3.x and after the install completed the new Docker Desktop started. After when started succesfully stop the docker desktop. Copy backedup vm-data folder content back to original place and start docker desktop.
This workaround helped to me.

**Comment by simonferquel** [comment]
@dannygroebner I saw from the logs that you are missing a piece of the WSL 2 installation: the Linux Kernel update package which must be downloaded from https://aka.ms/wsl2kernel
