### ISSUE TITLE
Docker windows not starting after update to 2.4.0

### ISSUE THREAD

**Issue by pbois34** [docker/for-win#8738]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 87A7C079-028B-49A4-B680-1E524F5DF0D7/20201001065216

### Expected behavior
Docker should be running
### Actual behavior
Docker not starting
### Information

  - Windows Version: Windows 10 Pro 1809 17763.864
  - Docker Desktop Version: 2.4.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: NO

### Steps to reproduce the behavior

  1. Update Docker windows to version 2.4.0

**Comment by pbois34** [comment]
As someone  said, in Hyper-V manager the DockerDesktop virtual machine has disappeared too on my computer but not the disk. How do I recreate the virtual machine from Disk  ?

**Comment by simonferquel** [comment]
@pbois34: there is a bug in our http proxy parsing. There is a workaround for that though:

edit your settings file at C:\Users\<username>\AppData\Roaming\Docker\settings.json
change "overrideProxyExclude" from null to ""
save and restart Docker Desktop

**Comment by pbois34** [comment]
Thanks for the answer but I read it a bit late !!! meantime I unistalled docker 2.4.0, downloaded 2.4.0 and reinstalled 2.4.0. It worked but  I lost all data as reinstall created a new disk. Fortunately I had a backup of disk DockerDesktop.vhdx and I restored it. Now it works and I have all my containers.

**Comment by pbois34** [comment]
Closed

**Comment by mxr576** [comment]
I am having the same issue on MacOS Catalina after the update, settings.json has `""` instead `null`. Any suggestion?
