### ISSUE TITLE
Docker fail to start : The process cannot access the file

### ISSUE THREAD

**Issue by minkbear** [docker/for-win#874]
### Expected behavior
Dockers Starts

### Actual behavior
Doxker failed to start

### Information

  - Diagnostic ID : 2C49BCDE-B804-423F-8D70-EE5ED1423490/2017-06-30_12-53-36
  - Docker Version: Version 17.06.0-ce-win18 (12627) Channel: stable d9b6651
  - OS: Windows 10 Pro X64
  - Error Message:

> The process cannot access the file 'C:\WINDOWS\TEMP\4jn5acch.zlb' because it is being used by another process.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
>    at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
>    at Docker.Backend.MobyCommand.RunDocker(String arguments, IDictionary`2 envVariables, String stdin, Int32 timeoutMs, String cidFile)
>    at Docker.Backend.MobyCommand.Run(String commandLine, IDictionary`2 envVariables, Boolean load, String stdin, Int32 timeoutMs)
>    at Docker.Backend.SambaShare.MountInMoby(String mount, String drive, Credential cred, CredentialInfo credInfo, String options, String ip)
>    at Docker.Backend.SambaShare.MountInMoby(String drive, Credential credential, Settings settings)
>    at Docker.Backend.SambaShare.Mount(String drive, Credential credential, Settings settings)
>    at Docker.Backend.BackendServer.<Run>b__5_11(Object[] args)
>    at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

### Steps to reproduce the behavior

  1. Upgrade Docker to 17.06.0-ce-win18 (12627)

**Comment by minkbear** [comment]
When I quit the program and start again. It works fine.

**Comment by jasonbivins** [comment]
Hi @minkbear 
There's an occasional  conflict with that file when Docker starts up.  It has been reported as a bug, but I don't have a specific date for a fix yet.  Restarting Docker seems to be the best workaround at the moment.

Do you mind if I go ahead and close this one out?

**Comment by minkbear** [comment]
@jasonbivins 
Thanks for yours info.
no problem, sure.
