### ISSUE TITLE
Can't run docker client from CMD after update to 2.4.0

### ISSUE THREAD

**Issue by madalinignisca** [docker/for-win#8743]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
When opening CMD or Powershell and running `docker ps` I should see running containers.

### Actual behavior
Actual output:
```
docker: The term 'docker' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

### Information
Seems that on 2.4.0 update, the path to binaries to run from CLI docker, docker-compose etc. has been wiped out.

Running Docker on WSL2, updated from previous stable version.

**Comment by madalinignisca** [comment]
Did the update on my personal desktop as well, but all works fine after.
I can see in the system's path that both 2 expected locations are there.
On the work laptop are not. I can add them manually.
Note, I do not have anything special running on both machines (Edge, VSCode with remote containers, no 3rd party antivirus).

**Comment by mat007** [comment]
@madalinignisca do you have anything outstanding in any of the `%LOCALAPPDATA%\Docker\install-log.*.txt` files dated from around the time you performed the update? I’m not expecting any error otherwise I think the installer would just have failed, but who knows.

Can you upload diagnostics (Run Diagnostics button in the Troubleshoot window)? Thanks!

**Comment by madalinignisca** [comment]
I've checked all logs from 1st of the month, when I did the upgrade. Absolutely nothing in them suggesting of anything failed.

Diagnostic ID: 1AE2FD09-0195-4823-B8B8-59DA7B60950A/20201015090617

Might not be relevant now, as I manually added them back by copying identical path values from my personal laptop.
