### ISSUE TITLE
Unable to run Docker for Windows on Windows 10 Ent

### ISSUE THREAD

**Issue by plussystemtecnologia** [docker/for-win#8747]
I was using docker windows normally on my computer, the system requested an update to version 3.4.0 of the docker, when performing the update I can no longer use the docker, a message appears saying:
An error occurred
Hardware assisted virtualization and data execution protection must be enabled in the BIOS. See https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization.

Since everything was working in the previous stable version.

What do I do to solve the problem?

Anderson Lerry - PlusSystem Tecnology in Systems

**Comment by mat007** [comment]
@plussystemtecnologia is this with the WSL 2 or the Hyper-V backend?

**Comment by mat007** [comment]
@plussystemtecnologia can manually run this command to create and upload diagnostics, please?
```
PS> &'C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe' gather -upload
```
Thanks!

**Comment by vimiso2** [comment]
i have this problem too. With previously version of Docker works fine...

**Comment by mat007** [comment]
@vimiso2 can you run the above command to upload some diagnostics and post back the ID, please?

**Comment by plussystemtecnologia** [comment]
is this with the WSL 2 or the Hyper-V backend?

-> WSL2

can manually run this command to create and upload diagnostics, please?

-> 267A6C7C-2AD7-410C-9A0E-875225E1CC73/20201005092540

Thanks!

**Comment by vimiso2** [comment]
Hi i have the same problem i attach the diagnose zip file.
Thank you
[20201005151055.zip](https://github.com/docker/for-win/files/5328232/20201005151055.zip)

**Comment by mat007** [comment]
@plussystemtecnologia @vimiso2 were you both running the WSL 2 backend before updating?
Is WSL 2 working properly outside of Docker Desktop?
Have you tried switching to the Hyper-V backend? Does it fail the same check as well?

**Comment by mat007** [comment]
This might prove relevant: https://www.reddit.com/r/bashonubuntuonwindows/comments/ekjdf5/please_enable_the_virtual_machine_platform/

**Comment by mat007** [comment]
Can you try the following?
- `bcdedit /set hypervisorlaunchtype auto`
- reboot
- start Docker Desktop

**Comment by plussystemtecnologia** [comment]
Thanks! Issue resolved!
