### ISSUE TITLE
Docker does not start up anymore

### ISSUE THREAD

**Issue by MCStreetguy** [docker/for-win#875]
### Expected behavior

Docker should start up.

### Actual behavior

Docker throws the following error while starting and stops the starting process immediately:
>**An error occurred**
>Hardware assisted virtualization and data execution protection must be enabled in the BIOS.

### Information
Hyper-V is enabled on my system. Within the error message there is [this link](https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization-must-be-enabled) for troubleshooting but Virtualization is enabled which can be seen here: [Screenshot](http://prntscr.com/fpwr0t).
There are no options like those named in the error message within my BIOS.
I already tried several reboots and reinstalled Docker but no success by now.

  - I cannot provide a diagnostic ID since docker does not start up.
  - host distribution and version: Microsoft Windows 10 Pro (10.0.14393 Build 14393)

(*Windows installed the new Creators Update yesterday evening, maybe there is some relation.*)

### Steps to reproduce the behavior

  1. Start Docker for Windows CE

**Comment by jasonbivins** [comment]
Hi @MCStreetguy 
Can you run the Debug-ContainerHost script located here and share the results?

https://github.com/Microsoft/Virtualization-Documentation/tree/live/windows-server-container-tools/Debug-ContainerHost

**Comment by MCStreetguy** [comment]
I can do so but the error seems to be solved. I found out that the Creators Update failed to install and after fixing this the error within Docker was gone. I think some components were damaged due to the failed update and therefore didn't worked as Docker expected.
