### ISSUE TITLE
Proxy bypass isn't working anymore since 2.4.0.0

### ISSUE THREAD

**Issue by trickreich** [docker/for-win#8750]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: not able to run

### Expected behavior

Everything was working as expected in version before.
We have a custom registry in our network and pulling image from there.

### Actual behavior

Looks like proxy bypass isn't working anymore.

### Information

```
net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**Comment by simonferquel** [comment]
The issue has been fixed in Edge release 2.4.2.0, thank you for reporting it.
