### ISSUE TITLE
[Mac] Docker Desktop Community 2.4 NOT WORK MySQL!

### ISSUE THREAD

**Issue by drandin** [docker/for-win#8753]
MySQL 5.7 and MySQL 8 databases stopped working. The problem with the file access tables.

**Comment by Ayzrian** [comment]
I have encountered the same problem on Windows, after installing an update to WSL 2.
Here are logs from the container. 

> mysql          | 2020-10-01T21:17:35.069176Z 0 [ERROR] [MY-010119] [Server] Aborting
mysql          | mysqld: [Warning] World-writable config file '/etc/mysql/my.cnf' is ignored.
mysql          | mysqld: Error on realpath() on '/var/lib/mysql-files' (Error 2 - No such file or directory)
mysql          | 2020-10-01T21:18:01.337173Z 0 [ERROR] [MY-010095] [Server] Failed to access directory for --secure-file-priv. Please make sure that directory exists and is accessible by MySQL Server. Supplied value : /var/lib/mysql-files
mysql          | 2020-10-01T21:18:01.337210Z 0 [ERROR] [MY-010119] [Server] Aborting
