### ISSUE TITLE
Docker Desktop failed to initialise

### ISSUE THREAD

**Issue by sandman153** [docker/for-win#8757]
- [1] I have tried with the latest version of my channel (Stable)
  - [1 ] I have uploaded Diagnostics
  - Diagnostics ID: BB7A9052-52FD-47FF-A192-0461DB01791B/20201001205706

### Expected behavior
Can't open docker desktop GUI when I start docker

### Actual behavior

I get an error when I start docker
System.NullReferenceException:
Object reference not set to an instance of an object.
   at Docker.Core.Cli.CliOptionsLoader.Get() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.Core\cli\CliOptionsLoader.cs:line 33
   at Docker.Program.Run(IReadOnlyCollection`1 args) in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Program.cs:line 327

![image](https://user-images.githubusercontent.com/26595971/94863251-7f69df00-047d-11eb-8e5d-3ce311fe354c.png)

### Information

  - Windows Version: Windows 10 Professional
  - Docker Desktop Version: 2.4
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. Start Docker Desktop and I get the error

**Comment by MrPostie** [comment]
Got the same issue, started yesterday. Got the question from Docker to use WSL 2, it would leave my current images alone. The Yes or Ok button was default so I pressed it. After that, I got the error. Did a Windows update, followed [Windows Subsystem for Linux Installation Guide for Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10) but no solution. Tried to install Docker for Windows but it says I have the latest version

**Comment by oleh-kazban-gl** [comment]
The same issue.

**Comment by simonferquel** [comment]
@sandman, can you send me your ~/.docker/config.json file so that I can see where the parser fails ? (if you remove it and restart docker desktop, it should recreate a valid one itself and startup correctly - but please send me a copy :)).

**Comment by oleh-kazban-gl** [comment]
Interesting - uninstalled it, removed .docker folder, installed again - it works.
@simonferquel my .docker/config.json was full of "-", no other entries.

**Comment by MrPostie** [comment]
Removing the config.json and starting Docker worked for me too

**Comment by jjneuha** [comment]
Same issue here. Went with the default to enable WSL 2. After a reboot, I started getting the message.

**Comment by mrobinet** [comment]
I also ran into this, but nuking everything and reinstalling appears to have fixed it.

**Comment by MorrisonCole** [comment]
Note that there is a `.docker` folder on both Windows & your WSL image. For me, it was failing on the Windows one and removing that fixed it. In my case, it was unnecessary to remove any other folders.

**Comment by wtichy** [comment]
same  issue

**Comment by wtichy** [comment]
why

**Comment by CyberAP** [comment]
That happened to me after I upgraded my WSL1 distro to WSL2, and also upgraded Docker to the latest version. Deleting `%UserProfile%/.docker` fixed the issue for me.

**Comment by sandman153** [comment]
Deleting the `%UserProfile%/.docker` fixed it for me as well. Thanks for all your comments and help
