### ISSUE TITLE
Cannot start container in 17.06.0-ce with automatic DNS Server

### ISSUE THREAD

**Issue by crowne** [docker/for-win#876]
### Expected behavior
Expect sysout to console

### Actual behavior
docker -l debug run hello-world
Hangs

### Information

  - Diagnostic ID : 693C7F84-3C44-42BB-AAEF-4FCE76281427/2017-06-30_11-02-55
  - Dockerfiles : default hello-world
  - 17.06.0-ce on Windows 10.0.15063 Build 15063

### Steps to reproduce the behavior

  1. upgrade to 17.06.0-ce-win18 (12627) on Stable channel
  2. docker -l debug run hello-world ... hangs
  3. Change DNS from Automatic to fixed 8.8.8.8
  4. docker -l debug run hello-world ... runs

**Comment by jasonbivins** [comment]
Hi @crowne 
I do see in the log where the connection is failing when you use the Automatic DNS resolution, looking for these addresses - 
10.144.160.8
10.144.200.8
10.208.2.195
10.208.2.182
search za.sbicdirectory.com

Can you try the Edge channel to see if you still see this issue?

**Comment by jamesmbourne** [comment]
I was unable to pull images from the hub due to this, but switching DNS (Docker Tray icon | Settings | Network | DNS Server) to fixed and then back to automatic seems to have resolved it.

**Comment by crowne** [comment]
I installed the edge channel, and then needed to pull some images.
The default network setting was automatic, and the pull timed out.
I changed to 8.8.8.8 and completed the pulls, this is a separate problem which I have noticed before.

I switched back to automatic and was able to run hello-world, this was at home without a proxy.

I will try at the office tomorrow from behind the proxy and I'll let you know.

**Comment by crowne** [comment]
From behind the proxy on Automatic DNS "docker run hello-world" was just hanging.
I changed to 8.8.8.8 then it worked, and after changing back to automatic it continued to work.

**Comment by crowne** [comment]
Last night I upgraded to 17.07.0-ce-rc1-win21 (12927) on Edge channel, and this no longer seems to be an issue even with the Docker DNS server set to automatic, my images start running without hanging.

**Comment by crowne** [comment]
I spoke too soon, this morning my images won't start, they just hang.
I have a chicken and egg situation

My proxy settings are pointing to localhost:3128 which is a cntlm server running as a docker image.
However this image wont start while the proxy cannot be reached,
so I need to change my proxy settings to websenseproxy.corporate.com:8080

Then I can start the cntlm image, and then I can change my proxy settings back to localhost:3128.

So I would say that the problem is that images cannot be started when the proxy server is unavailable,
even although the image is cached locally, even if the image is as simple as the hello-world example image,
which I tested too.

**Comment by crowne** [comment]
This is still a problem on Docker version 17.07.0-ce-rc3, build 665d244, with network DNS set to automatic and OS proxy enabled and directed to an NTLM proxy.

**Comment by chrsoo** [comment]
Hi, are you able to configure the proxy settings for the docker client? This does not work at all for me and it seems as-if the command line client completely ignores the HTTP_PROXY and HTTPS_PROXY, cf #1057.

Note that I also opened #1064 to address the larger issue of support for NTLM proxies on Windows.

Also note that the Docker demon seems to be able to use NTLM or it is actually respecting the globally set HTTP_PROXY and HTTPS_PROXY settings, not sure which. (This I deduce from the fact that Docker manages to request a Diagnostic ID from Docker.)
