### ISSUE TITLE
Nat driver not locatable. Nat networks broken.

### ISSUE THREAD

**Issue by ColinSuess** [docker/for-win#8764]
- [X] I have tried with the latest version of my channel (Stable)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 9EA4B64E-7F81-4C6F-BE8B-0DBDF22F2D6A/20201002040833

### Expected behavior
Docker for Windows on Windows 10 Pro can create new networks that use the "nat" driver.

### Actual behavior
Docker for Windows is unable to locate the "nat" driver.
Output from an elevated PowerShell prompt:

PS C:\PlayFabVMAgent> docker network create playfab2 --driver nat
Error response from daemon: plugin "nat" not found

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible? Yes on both Home edition and Pro edition (using their respective versions)
  - Is the problem new? This is my first time trying Docker.
  - Did the problem appear with an update? This is my first time trying Docker.

  - Windows Version: 10.0.19041 x64
  - Docker Desktop Version: I couldn't find a Help or About in the Desktop app, but it's whatever was hosted on 10/1/2020.

output from "docker version"
Client: Docker Engine - Community
 Cloud integration  0.1.18
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:00:27 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior
         1. Do a fresh install of Docker for Windows
         2. Run docker network ls -- no default nat network is created
         3. Attempt to create a nat network (see above for the commandline)
         4. For the use case, follow these steps: https://github.com/PlayFab/gsdkSamples/blob/master/UnityMirror/README.md

**Comment by stephen-turner** [comment]
We don't have the nat driver in Docker Desktop. Why were you expecting it to be present? Have we documented it somewhere?
