### ISSUE TITLE
AzureAD shared folder issues (passwordless login)

### ISSUE THREAD

**Issue by prasoc** [docker/for-win#877]
### Expected behavior

I am running Docker for Windows and logging in with AzureAD. Trying to enable my C drive to be shared between the Moby Linux VM and Windows.

Program is expecting me to use my domain account password to log in.

### Actual behavior

I am unable to log in to enable the shared drive, as my domain is entirely passwordless. I log into my machine with a PIN which I cannot enter into the login form, to authenticate myself.

### Information

Would be great if we could also use our Windows 10 PIN to authenticate.

Windows 10 Enterprise (build 14393.1358)

**Comment by jasonbivins** [comment]
Hi @prasoc 
Do you have a local user configured on your machine ? The account you use does not have to be your own, just an account that has rights to the C$ share.

**Comment by prasoc** [comment]
Thanks @jasonbivins that seems to work, in Windows 10 it's difficult making a purely local account but running "control userpasswords2" allows you to create a local account with administrative permissions.
