### ISSUE TITLE
Windows hosts file new lines broken

### ISSUE THREAD

**Issue by kozlicki** [docker/for-win#8773]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Windows hosts file without, additional new line characters

### Actual behavior
Windows hosts file with duplicated 0x0D 0x0D 0x0A combinations for new line

### Information

  - Windows Version: Windows 10 Enterprise
  - Docker Desktop Version: 2.3.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Set up windows hosts file with default content with new lines as 0x0D 0x0A
  2. Restart your computer and check hosts file - it should be updated with proper ip addresses for host.docker.internal, gateway.docker.internal and kubernetes.docker.internal and BOM should be added to the file
  3. Restart computer again and check hosts file - all CRLF (0x0D 0x0A) combinations should be replaced with 0x0D 0x0D 0x0A
  4. Restart computer again and check hosts file - all 0x0D 0x0D 0x0A combinations should be doubled
  5. Every next restart should double the 0x0D 0x0D 0x0A combinations

**Comment by mrshanahan** [comment]
My organization is seeing this happen as well. At least, several developers have reported hosts files hundreds of MB in size that are almost entirely blank lines - maybe 10-15 lines with content, and hundreds of millions of blank lines.  Here is a (lightly redacted) hosts file displaying the issue on a much smaller scale - on the order of hundreds of KB:
[bad_hosts.txt](https://github.com/docker/for-win/files/5502056/bad_hosts.txt)
