### ISSUE TITLE
Not live updating on code changes, plus slower than pre-update.

### ISSUE THREAD

**Issue by caedmonm** [docker/for-win#8774]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 237C1A21-A9AE-4109-9326-764C71B62C69/20201002123324

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
If you are running on the WSL 2 engine but keeping the files in the Windows filesystem not the Linux filesystem, this is expected behaviour, it's just how Windows works. See https://docs.docker.com/docker-for-windows/wsl/. This is why we recommend keeping the files in the Linux filesystem.
