### ISSUE TITLE
Failed to Deploy distro docker Desktop

### ISSUE THREAD

**Issue by jatscorpio** [docker/for-win#8779]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 634E11C9-B07B-4B31-978E-7B4A471034F3/20201002135920

### Information

  - Windows Version: Windows 10
  - Docker Desktop Version: 2.4.0.0 (48506)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by cworreschk** [comment]
I had the same problem. It seems that something is wrong with the WSL 2 support. Because when I disabled this option, Docker started normally.
