### ISSUE TITLE
Requires log out

### ISSUE THREAD

**Issue by mikefonted** [docker/for-win#878]
### Expected behavior
When I click on "Docker For Windows", docker should start.

### Actual behavior
A notification popup appears saying:
Docker for Windows - Requires log out
You need to log out of Windows
Then your "docker-users" membership will be taken into account
Docker.DockerForWindows.Settings

![docker-error](https://user-images.githubusercontent.com/6642583/27736281-d555bd8c-5da3-11e7-8919-aeb6b9f31880.png)

### Information
docker version 17.06.0-ce, build 02c1d87
docker-compose version 1.14.0, build c7bdf9e3
docker-machine version 0.12.0, build 45c69ad
Microsoft Windows 10 Pro (10.0.15063 N/D Build 15063)

### Attempts
~~Windows log out and log in~~
Uninstall and reinstall Docker for Windows
Check if my user is included in docker-users group

**Comment by adi8i** [comment]
I seen the notification too, after the first install, but everything went ok after PC restart.

**Comment by mikefonted** [comment]
Sorry for the late response, it happened at work on Friday afternoon and reported quickly. Yes, @adi8i, luckily today is working after restarting. However, I just realized I did not log out from Windows, just locked my account (⊞Win+L). So, I will close the issue and apologize for the inconvenience.

**Comment by janvanveldhuizen** [comment]
I want to automate the installation. How can I avoid this reboot?
