### ISSUE TITLE
 failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount587080174/Dockerfile: no such file or directory

### ISSUE THREAD

**Issue by SHAMBHU1995** [docker/for-win#8781]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by brotherspenti** [comment]
your docker file name should be "Dockerfile", i also faced same issue struggled lot of time, my file was as "dockerfile" so renamed it to "Dockerfile", then issue got resolved.

**Comment by dstowe** [comment]
I had this problem with the tutorial, I was running downloaded files from desktop. I moved the files to c: drive and all is well!

**Comment by maritamayman** [comment]
Hi!
Make sure your dockerfile has the same name as the one shown in your terminal, example:

failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount320670870/Dockerfile: no such file or directory

In this case, your dockerfile´s name should be DockerFile

The dockerfile needs no extension, in Windows, you can create it with notepad++ and save it as "all types (*.*)"

You can try typing the full path of your dockerfile:

docker build -t X:X O:\Users\yyy\XX

**Comment by BhadraJayakumarSandhya** [comment]
tried all these and still not working

=> [internal] load .dockerignore                                                                                  0.1s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load build definition from Dockerfile                                                               0.1s
 => => transferring dockerfile: 2B                                                                                 0.0s
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount466100014/Dockerfile: no such file or directory

any ideas how to resolve this?

**Comment by jbvazquez** [comment]
> your docker file name should be "Dockerfile", i also faced same issue struggled lot of time, my file was as "dockerfile" so renamed it to "Dockerfile", then issue got resolved.

Thank's it solved my issue

**Comment by Frozendan1** [comment]
> Hi!
> Make sure your dockerfile has the same name as the one shown in your terminal, example:
> 
> failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount320670870/Dockerfile: no such file or directory
> 
> In this case, your dockerfile´s name should be DockerFile
> 
> The dockerfile needs no extension, in Windows, you can create it with notepad++ and save it as "all types (_._)"
> 
> You can try typing the full path of your dockerfile:
> 
> docker build -t X:X O:\Users\yyy\XX

^^ Thanks for this. I realized my unzip program put the code extract in downloads\app\app and my Docker file referenced \app as the directory (hence getting the failed to read message).  Upon correcting it, everything is working.

**Comment by 1nnikan1** [comment]
how to create a Dockerfile

**Comment by fanpero87** [comment]
> your docker file name should be "Dockerfile", i also faced same issue struggled lot of time, my file was as "dockerfile" so renamed it to "Dockerfile", then issue got resolved.

Hello,
I'm sorry to ask but where is that Dockerfile located? 
I just installed the Mac Desktop version and have the same problem.
Thanks.

**Comment by fanpero87** [comment]
Hello,
I keep reading that we should rename the Dockerfile but I honestly don't know what file is that or where to find it. A little help is much appreciated.

This is the error:
`fanpero@Amis-MacBook-Pro Docker % docker build --tag hello-world .
[+] Building 0.0s (2/2) FINISHED                                                                          
 => [internal] load build definition from Dockerfile                                                 0.0s
 => => transferring dockerfile: 2B                                                                   0.0s
 => [internal] load .dockerignore                                                                    0.0s
 => => transferring context: 2B                                                                      0.0s
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount813481497/Dockerfile: no such file or directory
fanpero@Amis-MacBook-Pro Docker % `

Thanks.

**Comment by Frozendan1** [comment]
If you're following along in the Getting Started instructional tutorial, you should have downloaded the app. There should be an app directory. For me, I just unzipped the file into my downloads folder. Go to your code editor (I'm using Visual Code) and open the app directory. You should see the Dockerfile just under the app folder. If you don't see a Dockerfile, you're instructed to create one.

**Comment by Bijan-mp** [comment]
I just logged in to Docker app and the problem solved !!

**Comment by Rushanf** [comment]
Filename must be "Dockerfile" and file type must be "File"

**Comment by nainesh72** [comment]
> > your docker file name should be "Dockerfile", i also faced same issue struggled lot of time, my file was as "dockerfile" so renamed it to "Dockerfile", then issue got resolved.
> 
> Thank's it solved my issue

Thanks you are 100 sure i change mu file name DockerFile to Dockerfile it working

**Comment by niyankhadka** [comment]
Problem was similar to me.... i tried same thing which was mentioned above. I tried changing file name and checked whether there was any extension or not. Here is the first error to me where screenshot is attached below from vscode : 
![vscodescreenshot](https://user-images.githubusercontent.com/24240246/103098246-2e0f5d00-4632-11eb-8ff8-e545b0840f0c.PNG)

Then after wards, i stopped building from vscode and opened terminal and same build code works for me. Screenshot is attached below: 

![powershellscreenshot](https://user-images.githubusercontent.com/24240246/103098283-51d2a300-4632-11eb-8222-43a6cd637405.PNG)

I think, this might help some people who are stuck with this one. This is how i solved my problem in Windows 10.

**Comment by josephhailu** [comment]
try 
docker build -t getting-started ./app

**Comment by bakhalea** [comment]
I faced below error:
![image](https://user-images.githubusercontent.com/25849657/104530359-a5486900-55c0-11eb-8903-cf2f636bf684.png)
![image](https://user-images.githubusercontent.com/25849657/104530388-b42f1b80-55c0-11eb-9491-a8636cfd2308.png)

**Comment by ileuskov** [comment]
I had the same problem and this is my solution to it:
I had the app in `Portfolio/Docker/techworld-js-docker-demo-app/app`. The source code of the app was in the `app`. So I was trying so build my app from there and had this problem

After I moved one folder back to the main folder of the app `techworld-js-docker-demo-app` and run `docker build -t my-app:1.0`  everything worked out fine! 

I should also say that `techworld-js-docker-demo-app` is exactly where my Dockerfile was. So the problem for me was that I was trying to build an app from the src folder where there was no Dockerfile instead of running it from the folder where it was

**Comment by narendrasingh86** [comment]
> tried all these and still not working
> 
> => [internal] load .dockerignore 0.1s
> => => transferring context: 2B 0.0s
> => [internal] load build definition from Dockerfile 0.1s
> => => transferring dockerfile: 2B 0.0s
> failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount466100014/Dockerfile: no such file or directory
> 
> any ideas how to resolve this?

Please ensure you are in the correct directory where your Dockerfile is present.

**Comment by narendrasingh86** [comment]
Please ensure you are in the correct directory where your Dockerfile is present.

**Comment by vadimzozulya** [comment]
I have `DOCKERFILE` file, and after the recent update of the docker desktop `docker build .` command started failing with the same error.
Adding `-f` : `docker build -f .\DOCKERFILE .` solved the issue for me.

**Comment by bxj121** [comment]
> I have `DOCKERFILE` file, and after the recent update of the docker desktop `docker build .` command started failing with the same error.
> Adding `-f` : `docker build -f .\DOCKERFILE .` solved the issue for me.

This worked for me . Thanks

**Comment by doskeko** [comment]
> Problem was similar to me.... i tried same thing which was mentioned above. I tried changing file name and checked whether there was any extension or not. Here is the first error to me where screenshot is attached below from vscode :
> ![vscodescreenshot](https://user-images.githubusercontent.com/24240246/103098246-2e0f5d00-4632-11eb-8ff8-e545b0840f0c.PNG)
> 
> Then after wards, i stopped building from vscode and opened terminal and same build code works for me. Screenshot is attached below:
> 
> ![powershellscreenshot](https://user-images.githubusercontent.com/24240246/103098283-51d2a300-4632-11eb-8222-43a6cd637405.PNG)
> 
> I think, this might help some people who are stuck with this one. This is how i solved my problem in Windows 10.

Thanks bro! It worked for me this way too. I'm using Mac BigSur, in VsCode I was getting the same issue, in Mac shell it worked fine.

**Comment by iblezya** [comment]
> I have `DOCKERFILE` file, and after the recent update of the docker desktop `docker build .` command started failing with the same error.
> Adding `-f` : `docker build -f .\DOCKERFILE .` solved the issue for me.

I had this problem in WSL. Thanks worked for me.

**Comment by 1Mark** [comment]
Make sure that the Dockerfile is in the same directory that you run `docker build -t tagName .`
My issue is that I accidentally had put it inside the src folder. Instead your project should look something like this
![image](https://user-images.githubusercontent.com/15360245/108630718-20bdf580-745e-11eb-90ff-97c41234b753.png)

**Comment by LarrySul** [comment]
@1Mark thank you solved for me . It means you have to be in the root directory where you have the Dockerfile . Sweet

**Comment by aloyst** [comment]
Sounds really silly, but I was also experiencing this issue and the above was not resolving. 
Turns out it was my fault, make sure you don't make the same mistake I was and not having my terminal in the correct directory in the first place: 
C:\Users\xxx\Documents### \app 
Soon as I entered this directory, and followed the other steps posted above to resolve filename/extension issues etc. the build ran successfully.

**Comment by fsteig2002** [comment]
Please ensure you are in the correct directory where your Dockerfile is present.

**Comment by ashibindal22** [comment]
> Sounds really silly, but I was also experiencing this issue and the above was not resolving.
> Turns out it was my fault, make sure you don't make the same mistake I was and not having my terminal in the correct directory in the first place:
> `C:\Users\xxx\Documents### \app `
> Soon as I entered this directory, and followed the other steps posted above to resolve filename/extension issues etc. the build ran successfully.

Thank you!  i made the same silly mistake
