### ISSUE TITLE
Docker Doesn't Start: Failed to create or configure Hyper-V VM: Sequence contains no elements..

### ISSUE THREAD

**Issue by davidcn91** [docker/for-win#8782]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 5BD7BD1A-428B-4546-BF78-E96D5BDE9E9D/20201002154717

### Expected behavior
Docker starts

### Actual behavior
Docker does not start and gives error "Failed to create or configure Hyper-V VM: Sequence contains no elements.."

![image](https://user-images.githubusercontent.com/20193699/94943881-645f9500-04a6-11eb-8927-4ff091923f57.png)

### Information
<!--
 Problem seemed to start after a Windows update
  - Windows Version: Windows 10 Version 1809
  - Docker Desktop Version: 2.4.0.0 (48506)

### Steps to reproduce the behavior
1. Start Docker Desktop

**Comment by stephen-turner** [comment]
Did you follow the troubleshooting link?

**Comment by davidcn91** [comment]
Yes, I've tried everything under the Virtualization section of the troubleshooting page, turned Hyper-V on and off and restarted but still seeing the same issue.  Virtualization is enabled under Task Manager

**Comment by davidcn91** [comment]
Was able to fix this by switching to WSL 2, not sure what the issue with Hyper-V is
