### ISSUE TITLE
Docker Desktop just hangs indefinitely if I use a custom compiled kernel

### ISSUE THREAD

**Issue by wanfuse123** [docker/for-win#8784]
[How to Build WSL2 Linux Kernel with Both NVIDIA and ISCSI and NFS.docx](https://github.com/docker/for-win/files/5319519/How.to.Build.WSL2.Linux.Kernel.with.Both.NVIDIA.and.ISCSI.and.NFS.docx)

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by wanfuse123** [comment]
4CDD3BA5-A32F-4128-9561-6ADD93D1A1FD/20201002173402

**Comment by stephen-turner** [comment]
Sorry, we can't help with cases where people compile their own kernels, anything could be wrong with it.
