### ISSUE TITLE
Unable to run some containers with Docker desktop 2.4.0 + WSL2 + Ubuntu 20.04

### ISSUE THREAD

**Issue by osharper** [docker/for-win#8786]
- [x] I have tried with the latest version of my channel (**Stable** or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A4E6052C-D6A7-4055-8590-6E9FB305A106/20201002185255

### Expected behavior
```docker run -itd --name mongodb mongo:2.6```
should launch a mongo db 2.6 container when WSL engine is on

### Actual behavior
command results in instant `Exited (139)` container status without any log output from container. With Hyper-V or on other Linux machine it works just fine. Mongo images around 2.x version shows same behavior. Latest mongo image runs just fine. Probably some other images affected.

### Information
  - Windows Version: 20H2 19042.541
  - Docker Desktop Version: 2.4.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
  1. Turn on WSL 2 based engine
  2. Run `docker run -itd --name mongodb mongo:2.6`

**Comment by stephen-turner** [comment]
This sounds more like a bug in the old versions of Mongo than a bug in Docker Desktop. Do these old versions of Mongo work in WSL 2 not in a container?
