### ISSUE TITLE
Error response from daemon while logged in

### ISSUE THREAD

**Issue by adi8i** [docker/for-win#879]
### Expected behavior
Download and Create the container

### Actual behavior
The following error is threw: 
` Error response from daemon: Get https://registry-1.docker.io/v2/ ANY REPO NAME /manifests/latest: unauthorized: incorrect username or password.`

### Information

  - Diagnostic ID: 59812C74-D306-48C7-B112-3314641F393C/2017-06-30_18-52-41

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

### Steps to reproduce the behavior

  1. Log in using Docker ID
  2. Create a container using docker cli

I signed out and everything went fine.

**Comment by jasonbivins** [comment]
Hi @adi8i 

We did have a temporary outage - are you still seeing this error?

**Comment by Titerote** [comment]
I am experiencing the same problem since I updated my docker yesterday to 17.06.0-ce, build 02c1d87

**Comment by adi8i** [comment]
Hi,

Yes, the error is still there.

I didn't specified that I use Kitematic, if this could affect in any way...
If I hit `new -> create` it works, I successfully created mariadb container, instead if I open `docker cli` from kitematic and I run a command like `docker run --name myadmin -d --link mariadb:db phpmyadmin/phpmyadmin`, while I am logged in. I get that error.

Also, I am talking about docker sign in, `right click on docker icon -> sign in`, I am telling this because kitematic have a login button too, that one don't affect at all.

**Comment by MikeGlue** [comment]
Encountering this same issue trying to pull Windows containers. Using the following Docker build: 17.11.0-ce-win40 (14328)

If I sign out of Docker via right-click on Docker icon all is fine.

**Comment by Ohmen** [comment]
This bug still persists in

```Client:
 Version:       18.01.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    03596f5
 Built: Wed Jan 10 20:05:55 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.01.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   03596f5
  Built:        Wed Jan 10 20:13:12 2018
  OS/Arch:      linux/amd64
  Experimental: true
```
## Steps to reproduce
1. Login to the docker hub via the UI
2. `docker pull hello-world`

## Additional info
* When I run docker login after logging myself in via the UI i get my mail address as username
* When I run `docker login` on the CLI everything works. Even the UI recognizes my loggin.
