### ISSUE TITLE
F56436C0-B587-44DD-9B3D-E439C1C3FE7F/20201003125117

### ISSUE THREAD

**Issue by mmirac** [docker/for-win#8797]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by PavelSosin-320** [comment]
Finally starts successfully with:
Windows version: 2004 **build 20221**.1000 (dev preview) and Docker CE version  **2.4.1.0 edge**.
Host tcp://0.0.0.0:2375 explicitly added to the daemon config file 
Docker context tcp://localhost:2375 created and used for convenience.
Windows upgrade issue: touched by the upgrade folders are marked as read-only including ProgramData.
