### ISSUE TITLE
An error occurred while checking for update

### ISSUE THREAD

**Issue by NicolasMontoya** [docker/for-win#8798]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: EDA88537-9DD6-4110-BAC2-9FD6ACE54AC2/20201003142536

### Expected behavior
Doesn't show this warning

### Actual behavior
Help please. Error occurred when machine is started

![image](https://user-images.githubusercontent.com/11598353/94994047-ba8e1000-055a-11eb-8c25-c898148fcf3e.png)

### Information

  - Windows Version: 2004
  - Docker Desktop Version: 2.4.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Is Windows WSL 2 Docker Desktop

### Steps to reproduce the behavior

![image](https://user-images.githubusercontent.com/11598353/94994109-3a1bdf00-055b-11eb-94f0-b82f9552cc16.png)

**Comment by 29axe** [comment]
Same here.

Windows 10: 2004
Docker Desktop for Windows 2.4.0.0 (48506) - stable
Diagnostics ID: 68BE2CFC-E722-4DB3-A60A-18B08E0E23EC/20201009080927

Docker updated itself yesterday. I got these notifications this morning.
