### ISSUE TITLE
Docker says that virtualization must be turned on when it is turned on

### ISSUE THREAD

**Issue by FedericoCaldas** [docker/for-win#881]
### Expected behavior
When I run Docker, it should start
### Actual behavior
Docker displays an error message: Hardware assisted virtualization and data execution protection must be enabled in the BIOS. See https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization-must-be-enabled
### Information

  - Diagnostic ID:C59B26C5-50F2-4C05-A74D-FE2159E16259/2017-06-30_16-37-18
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc) Windows 10 Pro
Intel Core 3 Duo / 3.0 Gb
Virtualization is enabled on the computer

### Steps to reproduce the behavior

  1. Launch Docker for Windows as Administrator
  2. ...

**Comment by MCStreetguy** [comment]
I got the same issue some days ago. For me there was an error during an Windows update that caused Docker to fail on start. So I would check if there are any update fails and redo those updates if possible.

**Comment by jasonbivins** [comment]
Hi @FedericoCaldas - please run Windows updates and let me know if that solves it.  You can also try this Debug script to help pinpoint the issue

https://github.com/Microsoft/Virtualization-Documentation/tree/live/windows-server-container-tools/Debug-ContainerHost

**Comment by ClemSam256** [comment]
hi I am new in Github. Bu I face a similar issue like FredericoCaldas. I never had Docker correctly started. Each time I log in my sW10 ession or restart I have after a while, an error notification :
![docker_hyper-v enabled for windows-1](https://user-images.githubusercontent.com/30449102/28596569-857bd04e-7199-11e7-85a3-e4f8593c5001.PNG)
and when I verify the version I get the following:

![docker_version](https://user-images.githubusercontent.com/30449102/28596598-b3db5edc-7199-11e7-90b6-b50c29ad5ecb.PNG)
what need to be done to solve this issue, please? I can't progress on learning Docker currently.
Thanks

**Comment by ClemSam256** [comment]
in fact when I run Install Docker for Windows as described at https://docs.docker.com/docker-for-windows/install/#install-docker-for-windows, I never reach the steps:

2- You will be asked to authorize Docker.app with your system password during the install process. Privileged access is needed to install networking components, links to the Docker apps, and manage the Hyper-V VMs.

3 -Click Finish on the setup complete dialog to launch Docker.
Probably the error occurs before.

**Comment by ClemSam256** [comment]
I uninstall, then reinstall Docker. The log file for installation is attached. It seems the installation was successful.
But Docker doesn't start.
[install-log.txt](https://github.com/docker/for-win/files/1185703/install-log.txt)
Is there something wrong in the installation stages?

**Comment by ClemSam256** [comment]
here is the log file when Docker starts:
[log.9.txt](https://github.com/docker/for-win/files/1327129/log.9.txt)
