### ISSUE TITLE
WSL distro stops every time I restart my computer

### ISSUE THREAD

**Issue by Thiamath** [docker/for-win#8818]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID:
48B94D69-7EB9-4C21-9038-FD05DC831947/20201004225545

### Expected behavior
Docker starts correctly every time I start my PC.

### Actual behavior
Every time I start my computer, Docker shows up with the error that the distro stopped.
Restarting Docker Desktop makes it work fine again but it's annoying, it should work from the very beginning.

### Information

  - Windows Version: 10.0.19041 Build 19041
  - Docker Desktop Version: v19.03.13
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Nope

### Steps to reproduce the behavior

  1. Restart the computer.

**Comment by simonferquel** [comment]
Hi, can you try to access \\wsl$\docker-desktop-data\isocache and remove all files from there ?

**Comment by Thiamath** [comment]
It worked! Thank you!
