### ISSUE TITLE
Docker Engine quits with error when host drive is full

### ISSUE THREAD

**Issue by klieth** [docker/for-win#8824]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
The running Docker container should return ENOSPC or similar, and neither Docker Engine nor the container should quit.

### Actual behavior
The Docker engine quit with a generic "Bus Error" message, terminating all active containers, and was unable to restart due to the disk being full.

### Information

  - Windows Version: 10.0.19041
  - Docker Desktop Version: v19.03.13
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior
  1. Fill host disk
  2. Try to write a file in a docker container. In my case, I was compiling a project inside a container and gcc failed to write the output file to disk. gcc showed an Input/Output error, and then the next line printed "Bus Error", and then the container quit and I was back at a host shell prompt.

**Comment by klieth** [comment]
I do not have a diagnostics file, because the Docker Desktop application was unable to collect diagnostics because the Docker Engine was not running.

**Comment by stephen-turner** [comment]
Sorry, this is a Won't Fix. The behaviour is not perfect but it's (hopefully!) a rare case.
