### ISSUE TITLE
Unable to start Docker Desktop after version upgrade to 2.4.0.0

### ISSUE THREAD

**Issue by KrisGerhard** [docker/for-win#8828]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: AF4129C9-1BAC-4CE9-9817-5CE7787D7E8A/20201005081013

### Information

  - Windows Version: 10
  - Docker Desktop Version: 2.4.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by KrisGerhard** [comment]
Upgrading to Docker Deskto 2.4.1.0 (Edge release) fixed the problem.

**Comment by hakuno** [comment]
Confusing...

I used the edge release... I got buggy.

I came back to the stable... I got buggy last week after update.
