### ISSUE TITLE
Docker cannot run container, returns socket error 99

### ISSUE THREAD

**Issue by soren37** [docker/for-win#8838]
- [! ] I have tried with the latest version of my channel (Stable or Edge)
  - [! ] I have uploaded Diagnostics
  - Diagnostics ID: A43B9842-D35C-4DAB-9E09-532A49F414E6/20201005151717

### Expected behavior
After running, I should have a container that I can then perform my work in.

### Actual behavior
After running, the container is made but cannot function, and the logs consistently show socket error, error number 99
### Information

After successfully building my image from a dockerfile, I am trying to make the container so that I can begin the work I need. The run command does make the container, but then the container fails to start and returns "socket.error: [Errno 99] Cannot assign requested address". The steps I use are as follows after navigating to the correct directory.

```docker build . -t image_name```

```docker run --publish 8000:8888 --detach --name container_name image_name```

I have ensured that my drive has enough memory, and confirmed that ports 8000 and 8888 are both available. I have also tried this with port 8080 and the same issue arises. I have also tried mapping to the IP address (--publish 127.0.0.1:8000:8888) which also hasn't worked. I have also tried using the ```docker create``` and ```docker run``` commands, but these return the same issue.

  - Windows Version: 10 Home Edition, v 2004 build 19041.508
  - Docker Desktop Version: 2.4.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Not as far as I can tell.

### Steps to reproduce the behavior

  1. Build your image from the dockerfile
  2. Run the container from the image
  3. The container will be made but cannot run.

I have attached the container logs as well as the dockerfile to this post. Thank you in advance!
[Dockerfile.txt](https://github.com/docker/for-win/files/5328323/Dockerfile.txt)
[socket_error_log.txt](https://github.com/docker/for-win/files/5328316/socket_error_log.txt)

**Comment by stephen-turner** [comment]
Do other containers work? It sounds like there might be something wrong with the container itself.

**Comment by soren37** [comment]
I can try another container, I'm running into issues now with getting Docker to start. I'll try using the getting started container that Docker has on start up.

**Comment by soren37** [comment]
I was able to get Docker to start now, and just ran through the "getting-started" container that they provide. I was able to build the dockerfile that they provided and run the container from port 80 to port 80 as per the command line. Seeing as ports 80 and 80 worked, I'll try that for my own environment and see if that helps at all.
