### ISSUE TITLE
Cannot run postgres docker with volume mounting option

### ISSUE THREAD

**Issue by prem911** [docker/for-win#884]
### Expected behavior
Docker run for postgres should mount the volume and run the db
### Actual behavior
Postgres reports fatal error and stops.
### Information
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true

Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 3
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.31-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: moby
ID: ERVA:QGGA:BSGW:G2Y4:MOIU:SUPM:JBRW:6MKC:GG5J:4RBG:36YG:6M57
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 28
 System Time: 2017-07-02T05:00:41.2890515Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

### Steps to reproduce the behavior
Steps to reproduce the issue:

Run postgres:9.4 image when mounting the following volume: c:/temp/postgresql:/var/lib/postgresql/data
Describe the results you received:
Postgres will not start and the following errors will be printed to console:

HINT:  The server must be started by the user that owns the data directory.
FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
Describe the results you expected:
Postgres should start and mount the correct windows directory as a data volume

**Comment by Dargmuesli** [comment]
Same problem as #445? This will take a long time to fix, it's a permissions issue. A workaround is to store posters data in a Docker volume and make regular backups.
