### ISSUE TITLE
Execute docker run hello-world, but nothing happened on Windows 10 pro

### ISSUE THREAD

**Issue by brianling** [docker/for-win#886]
### Expected behavior
    Hello from Docker.
    This message shows that your installation appears to be working correctly.

### Actual behavior
   Nothing Happened

### Information
  - Diagnostic ID：A4159AB1-796D-4160-9C92-092E012AA780/2017-07-02_22-53-24

**Comment by jasonbivins** [comment]
Hi @brianling  According to the logs - the Docker daemon service can't start, but I'm still looking into the reason.  Can you try to manually restart the Docker service - and run hello-world again?

**Comment by brianling** [comment]
Hi @jasonbivins  thd Docker is fine now, I do not why, but it's running now. Maybe just like you said the Docker daemon service can't start at that time
Thanks for your response

**Comment by jasonbivins** [comment]
Hi @brianling 
I'll go ahead and close this one - please let me know if it happens again.
You might also want to run Windows updates and make sure you have the latest language packs - the logs had a few strange characters and it mixed between languages.

**Comment by brianling** [comment]
OK~Thank you so much
