### ISSUE TITLE
WSL-2 - make the second install dialog more intuitive/automatic

### ISSUE THREAD

**Issue by rmorrise** [docker/for-win#8865]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

After I choose to switch to WSL, it should stop docker, install WSL, and restart docker using WSL. I should not be prompted a second time, and I should not have to do any installation steps manually.

### Actual behavior

After a windows update, Docker Desktop gave me the option to switch to WSL 2. I opted in, and it presented me a dialog with the following information:

```
WSL 2 is not installed

Install WSL using this PowerShell script (in an administrative PowerShell) and restart your computer before using Docker Desktop:

Enable-WindowsOptionalFeature -Online -FeatureName $("VirtualMachinePlatform", "Microsoft-Windows-Subsystem-Linux")
                              [Use Hyper-V] [Stop Docker]
```

After thinking about it for 5 or 10 minutes, I think that I'm supposed to copy the script to the clipboard, click "Stop Docker", and run the script as instructed. I'm not sure if Docker will be running after that's done; I'm assuming I'll have to restart my PC or restart docker manually.

### Information

Please get rid of this additional dialog and run the powershell script automatically. If a restart is needed, the install wizard should handle the restart after a prompt to the user.

I initially couldn't understand the options "Use Hyper-V" and "Stop Docker".

I eventually figured out, after staring at it for a few minutes, that it's giving me the option to cancel the install and go back to the previous setup (Hyper-V), and that "Stop Docker", which I initially thought was going to cancel the operation, is actually the button to click if I want to go forward with the install.

I've already chosen to use WSL instead of Hyper-V. As a windows user, it's normal for existing copies of the software to be stopped and restarted as part of the install process.

- If Docker Desktop needs to be halted to install this tool, please just do it. It's OK to tell me about it first if Docker is currently running.
- If a powershell script needs to run to install this tool, please do it automatically without prompting. It's not OK for a windows install wizard to prompt me with a shell script that I should copy and run manually.
- The option names "Use Hyper-V" and "Stop Docker" are unclear based on the dialog contents

  - Windows Version: 10 enterprise 1909
  - Docker Desktop Version: 
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. After being prompted by Docker Desktop, choose to use WSL for Docker Desktop

**Comment by rmorrise** [comment]
Addendum: I got another dialog after the restart, saying that you can't do this with a PowerShell script anymore.

You now need to download and run a separate MSI file to install the WSL2 kernel:
https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel

Please make docker desktop do that automatically.

**Comment by stephen-turner** [comment]
Thanks for the feedback. We need to think about this a bit more. I see your points, but we also have lots of users who don't want us messing with Windows system settings. And also the WSL 2 installation procedure has changed several times, and we're expecting it to change again (the wsl2-kernel thing is expected to be temporary), so we would be chasing a moving target.
