### ISSUE TITLE
Docker failed to initialize

### ISSUE THREAD

**Issue by ductruong1991** [docker/for-win#8868]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...
![2020-10-07_08-04-18](https://user-images.githubusercontent.com/12962645/95275810-bb34e800-0873-11eb-8018-8f3141c44d94.png)

**Comment by simonferquel** [comment]
This is a known issue that we fixed internally. Workaround is removing ~/.docker/config.json. Sorry about that!
