### ISSUE TITLE
Enhance the Installer to have an option NOT to install the daemon (and Hyper-V)

### ISSUE THREAD

**Issue by ProfDrYoMan** [docker/for-win#8872]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
There should be an option to NOT install the docker daemon (and Hyper-V) if only the CLI tools are needed (and allowed).

### Actual behavior
Installation for docker on windows always installs the daemon and also installs Hyper-V (if WSL is not installed).

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

Run the installer. There are no options to NOT install the daemon.

**Comment by stephen-turner** [comment]
Thanks for the feedback. We have no plans to do this at the moment, but we accept feature requests in the docker/roadmap repo.
