### ISSUE TITLE
Please check this

### ISSUE THREAD

**Issue by asher8554** [docker/for-win#8876]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...
![image](https://user-images.githubusercontent.com/10725048/95320486-7e4d0d80-08d4-11eb-92a4-f0a19fdf7c6c.png)

**Comment by simonferquel** [comment]
This is a known issue, and a fix is inbound.
In the meantime, the workaround is to remove ~/.docker/config.json and restart Docker Desktop.
