### ISSUE TITLE
Minimize window button overlaps <dockerhubID> button

### ISSUE THREAD

**Issue by baalaan** [docker/for-win#8877]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Minimize button should NOT overlap the _dockerhubid_ button when resizing the Docker Desktop window.
### Actual behavior
UI issue: Minimize button overlaps _dockerhubid_ button when Docker Desktop window is resized to it's minimum size.
### Information
  - Is it reproducible?
Yes
  - Is the problem new?
Not sure. I was not able to find any report about this.
  - Did the problem appear with an update?
Yes
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.
-->
  - Windows Version: version 2004 - OS Build 19041.508
  - Docker Desktop Version: 2.4.0.0 (48506) stable OR Docker Desktop version 2.4.1.0 (48583) edge
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
Upgrade to the latest Docker Desktop version 2.4.0.0 (48506) stable OR Docker Desktop version 2.4.1.0 (48583) edge.
Open the main Docker Desktop window and resize the window.
Bring the size of the window to it's minimum possible size.
Observe the "minimize" button overlaps the <dockerhubid> button.

I have 2 PCs running Windows 10 version 2004 - OS Build 19041.508 and I was able to notice this behaviour after I upgraded from Docker Desktop version 2.3.0.4 (46911) to version 2.4.0.0 (48506) and beyond (edge).
Both PCs have the resolution set to 1920x1080 and Scaling is set to 100% (Recommended).

I have attached 2 screenshots captured before and after the upgrade from 2.3.0.4 to 2.4.0.0 stable/2.4.1.0 edge.

![Minimze button overlap - version 2 4 0 0 (48506)](https://user-images.githubusercontent.com/65601275/95322433-26e37900-08a5-11eb-9c9a-ae88e9daa710.jpg)
![Minimize button OK version 2 3 0 4 (46911)](https://user-images.githubusercontent.com/65601275/95322437-2814a600-08a5-11eb-8e86-ef9cc8e63129.png)

**Comment by baalaan** [comment]
I have removed Docker Desktop from my PC and used Revo Uninstaller to clean any leftover registries or files and reinstalled Docker Desktop version 2.4.0.0 (48506) from scratch and it does the same thing.

**Comment by stephen-turner** [comment]
Interesting, it doesn't do that for me, but maybe it's because my name is shorter.

**Comment by baalaan** [comment]
Is it shorter than 11 characters? 🤔

**Comment by stephen-turner** [comment]
This is weird, I tried with a 15 character username and it still didn't overlap.

**Comment by stephen-turner** [comment]
But I've opened an internal ticket.

**Comment by baalaan** [comment]
If I can help, let me know.
