### ISSUE TITLE
Docker Desktop is not starting on windows 10 pro

### ISSUE THREAD

**Issue by jobairkhan** [docker/for-win#8879]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 50514EBB-A9D4-47B3-A4EE-D5015CCD14E2/20201007123827

### Expected behavior
Docker swarm should start
### Actual behavior
Loading icon is showing for more than an hour
### Information

  - Windows Version: 10 professional
  - Docker Desktop Version: 2.3.0.5 and 2.4.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. I upgraded Docker Desktop
  2. It asked me to install WSL2
  3. After installing WSL2 I restart the docker and it never restarted

I have tried to uninstall and install back again using the installer and chocolatey. This is the diagnose id `50514EBB-A9D4-47B3-A4EE-D5015CCD14E2/20201007123827`, at this point, I installed 2.3.0.5 by chocolatey command. then restarted the machine and then start the docker. waiting for an hour still loading
![image](https://user-images.githubusercontent.com/7473194/95333536-cf450d80-08a4-11eb-8f84-1c01002fc26e.png)

**Comment by JoeT531** [comment]
Same issue
