### ISSUE TITLE
Can we expect docker-ee release scheduled for June 2017?

### ISSUE THREAD

**Issue by rfay** [docker/for-win#888]
### Expected behavior

According to the [docker-ee release schedule](https://docs.docker.com/engine/installation/#time-based-release-schedule) there was to have been a release in June, 2017 (quarterly). Can we expect an update? 

I have a Windows app that needs some later features (works on current stable Windows docker-ce) but need to test it on Appveyor.com, which provides only docker-ee current (17.03)

### Actual behavior

No release yet.

**Comment by friism** [comment]
I cannot give you a date for 17.06 EE yet, but CE 17.06 builds are available (these are not publicly available).

I would suspect that you can switch in your own Docker version at that start of the appveyour job:

```
Stop-Service docker
Remove-Item -Force -Recurse $env:ProgramFiles\docker
Invoke-WebRequest -Uri "https://download.docker.com/win/static/test/x86_64/docker-17.06.0-ce.zip" -OutFile "docker.zip"
Expand-Archive -Path "docker.zip" -DestinationPath $env:ProgramFiles -Force
Remove-Item docker.zip

Start-Service docker
```

Please post if this doesn't get you un-stuck.

**Comment by rfay** [comment]
Yeah, my experience is that installing docker-ce requires a reboot, don't think that works out with appveyor, but will try this.

Note the typo in your reply that "CE 7.06 builds are not publicly available" where you meant "EE".

**Comment by friism** [comment]
If another version of Docker is installed and the relevant Windows features are present, no reboot is required.

**Comment by rfay** [comment]
You're amazing @friism - that did in fact work. Wow, thanks, that's a big step forward. 

I still have a mounting problem, may I ask you how to get past it? It seems perhaps c: is not shared for volume mounting:

```
docker run -it -v /c/gopath:/junk busybox ls /junk
docker: Error response from daemon: invalid bind mount spec "/c/gopath:/junk": invalid volume specification: '\c\gopath:\junk'.
```

I've tried a pile of different variants for the windows side of the mount spec, including c:/gopath and //c/gopath and //c:/gopath - there have obviously been shifts in this area in the past. But if it's just that appveyor doesn't have C: shared, then I just need the command-line way to do that.

**Comment by friism** [comment]
You probably cannot run Linux containers (busybox) on AppVeyor WS2016 instances. Not that there's anything with appveyour, but for Linux containers, consider Travis or Circle CI.

**Comment by rfay** [comment]
Again, thanks for he help.

Whoa! Amazing. They run fine on Windows 10 Pro with docker-ce. 

The simple thing going on here (at this point) is that we use a golang build container for consistent builds. The container works fine. The mount gives screwy messages.

**Comment by friism** [comment]
Yes, that's because "Docker for Windows" (what you install on Windows 10) has two modes: Linux (default) and Windows.

Appveyour runs the raw Docker daemon on Windows Server 2016 which currently only supports Windows containers.

**Comment by rfay** [comment]
But... didn't we just install docker-ce there instead using your technique? Or was that just the client?

I would be happy to use circleci, which is what we use for everything... except we don't have the ability to test on windows that way. Appveyor here is in fact an add-on o our circleci testing mechanism.

Such a pleasure to get answers from you so freely, thanks!

**Comment by friism** [comment]
> But... didn't we just install docker-ce there instead using your technique? Or was that just the client?

No, you updated the raw Windows Docker daemon from version 17.03 to 17.06

**Comment by rfay** [comment]
And there are no other images in Appveyor's catalog that will support any recent docker, if I'm not mistaken. It looks like Windows Server 2012 R2 is the server for all others, and that can't run any recent docker-ce at all if I'm not mistaken.
