### ISSUE TITLE
Possible incompatibility with kb4023057 

### ISSUE THREAD

**Issue by philipwolfe** [docker/for-win#8882]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
65A025C5-5696-41D8-9AE9-9BC58EB7709D/20201007131937
### Expected behavior
Docker Desktop would not crash during startup.

### Actual behavior
I just installed kb4023057 on Windows 10 1909 and Docker Desktop crashes.

### Information

  - Windows Version: Windows 10 1909
  - Docker Desktop Version: 2.4.0.0 (48506)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
Occurs during startup.

**Comment by simonferquel** [comment]
Indeed Windows Daemon fails to start on `[WindowsDaemon     ][Error  ] fatal: failed to start daemon: error while opening volume store metadata database: timeout`
This is a "docker daemon" issue, can you submit this to https://www.github.com/moby/moby ?

**Comment by philipwolfe** [comment]
Will do.
