### ISSUE TITLE
kcore very large display 127TB

### ISSUE THREAD

**Issue by nKsnC** [docker/for-win#8894]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:B079825D-FE0E-42F1-ADAB-E6401E295A7A/20201008035218

### Information

  - Windows Version:Windows 10 2004 19041.508
  - Docker Desktop Version:2.4.0.0(48506)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: NO

My system disk is going to be full, so I plan to transfer other disk. Then I find `C:\Users\Shinelon\AppData\Local\Docker\wsl\data` veay large(13.7GB).  

I know from related information that this is `docker-desktop-data`.Then I try delete my images,container. All the things I can delete with commands(eg. docker images `docker image prune -a`).But this space will not be reduced at all.  

Then I know can access it.`\\wsl$\docker-desktop-data`.Find this file,`\\wsl$\docker-desktop-data\proc\kcore` is 13.7GB.  
This file seems to be related to memory.(By the way,at first I want to solve the docker memory usage problem...)  

![image](https://user-images.githubusercontent.com/47666274/95414519-aa15d500-0960-11eb-9477-6e557f29ebc2.png)

Finally I use `Troubleshoot-Clean/Purge data` make space decrease( 895MB).But this file is still the same as before.

So,Is this a display problem?But before it did take up a lot of space.  What should I do with this file?

Sorry for my bad English.

**Comment by stephen-turner** [comment]
Thank you for the report, @nKsnC, your English is clear.

It's normal that /proc/kcore is very large. It's not a real file, it just represents memory that the system can use. These links might help:
https://support.microfocus.com/kb/doc.php?id=7004153
https://stackoverflow.com/questions/21170795/proc-kcore-file-is-huge
