### ISSUE TITLE
Docker Engine Service (dockerd) occupying port 53

### ISSUE THREAD

**Issue by Pytal** [docker/for-win#8896]
I believe the issue of `dockerd` occupying port 53 has been causing numerous issues including preventing WSL from starting and preventing Docker Desktop itself from running.

I'm unsure what the complexity of the potential solution is although I think this issue is a high priority and should be fixed ASAP!

**Comment by stephen-turner** [comment]
@Pytal Can you give more details? We're not aware of any general problem and we have hundreds of thousands of people successfully using Docker Desktop with WSL 2. Please provide symptoms, repro steps and a diagnostics id or error message.

**Comment by Pytal** [comment]
@stephen-turner I've done some more testing and it seems that there is a sporadic correlation between port 53 being occupied by `dockerd` and the startup issues of WSL and Docker Desktop.

I'll close this for the time being as the issue is not reliably repoducible.

**Comment by stephen-turner** [comment]
OK, thanks. Please do let us know if you find a reproducible case.
