### ISSUE TITLE
docker-machine commands not working as documented

### ISSUE THREAD

**Issue by glennsills** [docker/for-win#89]
### Expected behavior
docker-machine active should display default
docker-machine ls should display list of all docker machines
docker-machine ip default should list the  IP information for the default machine

### Actual behavior
docker-machine active displays "No active host found"
docker-machine ip returns 'Error: No machine name(s) specified and no "default" machine exists.'
docker-machine ls returns the header for the output but nothing else

### Information

Docker seems to be running fine; i.e. I can run hello-world or nginx.  I can see the MobyLinuxVM running in the Hyper-V Manager.

  - Diagnostic ID from "Diagnose & Feedback" in the menu.

9E735BCE-AA9B-412C-AAAE-7377A938C801/2016-09-17_09-18-28

  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)
Edition: Windows 10 Pro
Version: 1607
Build: 14393.187
System Type: 64-bit operating system

### Steps to reproduce the behavior

  1. Run docker-machine command

**Comment by friism** [comment]
Docker for Windows is not designed to be used with, or managed by, `docker-machine`. Details in the [docs](https://docs.docker.com/docker-for-windows/#/what-to-know-before-you-install) and on the [forums](https://forums.docker.com/t/isnt-the-mobylinuxvm-the-default-docker-machine/17043/2).
