### ISSUE TITLE
Docker fails most days when booting up PC

### ISSUE THREAD

**Issue by bobbyAtSperry** [docker/for-win#890]
### Expected behavior
Docker used to start up when the PC Booted

### Actual behavior
For the last week or so it crashes during startup or sometimes locks. When it crashes I can usually get it going by doing a restart of docker. When it locks I have to reboot the PC.

### Information

  - Diagnostic ID: 99F6F2FF-975D-4447-B0AF-705648049B94/2017-07-04_08-03-28

**Comment by colthreepv** [comment]
Quote on this one, it just gets stuck when booting.

Killing the services and restarting it fixes it, using last Edge

**Comment by bobbyAtSperry** [comment]
OK, that works when it gets stuck. Would still prefer it not getting stuck or crashing in the first place!

**Comment by jasonbivins** [comment]
@colthreepv @bobbyAtSperry 
If you disable auto-start, and start Docker manually or by using the desktop icon, do you still get the same crash when Docker starts?

**Comment by bobbyAtSperry** [comment]
@jasonbivins I believe it will work fine if I do that. It always works fine 2nd time around after the crash. I get the impression it is clashing with something else starting up in windows.

**Comment by colthreepv** [comment]
@jasonbivins I tried today and works flawlessly disabling automatic service start.

The desktop app recognizes the service down, starts it and does not get stuck

**Comment by jasonbivins** [comment]
@colthreepv 
I tested as well using Delayed Start for the service in windows, and see the same thing.

I'll go ahead and enter an enhancement request for this

**Comment by jasonbivins** [comment]
@colthreepv  Did you get a prompt from Docker to start the service after you disabled it?

I've got mine set on Delayed start, and after 3 reboots so far I havent had any prompts or issues

![image](https://user-images.githubusercontent.com/28021664/28132930-51f5cf50-670c-11e7-9962-785f384416d5.png)
