### ISSUE TITLE
Computer loses Internet Connection when I start Docker Desktop 

### ISSUE THREAD

**Issue by M4verick-44** [docker/for-win#8901]
Every time I try to start Docker Desktop (Stable Version for Windows), my computer can't connect to the internet e.g. via Browser. I run the Desktop Docker as an Admin (normally I run everything as non Admin) but when the Desktop Docker respectively the Hyper V-Manager starts, I can't load any Page anymore and i can't connect to the Docker Hub or anything. Since I'm quite new to the whole Docker thematic, I'm not sure if it is just a simple configuration/installation problem or if the problem is somewhere else. 
When I try the troubleshooting for the network my computer can not detect the error, and the cable connection (Computer is via Lan connected), seems also to be fine. 
If I close Docker immediately I get the connection sometimes back, but normally I need to restart before my Browser finds a connection to the internet again. 
Maybe someone had a similar problem or know an obvious reason for this behavior?

**Comment by stephen-turner** [comment]
That is very odd. No, sorry, I've never heard of this problem before. :-(

**Comment by M4verick-44** [comment]
The problem was with the configuration with my admin account (its job related), the account had limited access to the internet because of company restrictions, that caused the connection fail.

**Comment by stephen-turner** [comment]
Glad you found the cause, thanks for the update.
