### ISSUE TITLE
Docker Desktop very unstable

### ISSUE THREAD

**Issue by StevenDeRoover** [docker/for-win#8902]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Use docker as yould would normally use docker

### Actual behavior
Docker fails to start WSL2, gets stuck in "starting", and when eventually (after killing - quitting will not work - and restarting, rebooting, uninstalling, reinstalling, uninstalling Hyper-V, uninstalling IIS) when you get it to start, invoking a docker build would not succeed, as the build never finishes, and docker desktop has become unresponsive.
Resetting, removing data, etc does not help at all.
It is impossible to do anything with this docker desktop.
Weirdly, on another desktop, it runs smoothly.

  - Windows Version: Windows 10 Pro 10.0.19041 Build 19041
  - Docker Desktop Version: 2.4.0.0 (48506)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

**Comment by nielsarts** [comment]
#8904

**Comment by LasseGravesen** [comment]
I'm also seeing this.
Windows Version: Windows 10 Pro, Version 1909 (OS Build 18363.1082)
Docker Desktop Version: 2.4.0.0 (48506)
Are you running inside a virtualized Windows, e.g. on a cloud server or on a mac VM?: No.

**Comment by StevenDeRoover** [comment]
I managed to find the culprit on my machine.  Are you by any change running trendmicro as antivirus? 
I uninstalled it on my machine, and that resolved everything.

**Comment by LasseGravesen** [comment]
I am running Trend Micro, but I can't uninstall it. I'll check it out. Thanks for the tip.

**Comment by LasseGravesen** [comment]
I downgraded to version 2.3.0.5 and now Docker runs without issue.

**Comment by nielsarts** [comment]
> I downgraded to version 2.3.0.5 and now Docker runs without issue.

How did you downgrade? Did you just deleted it from your control panel in windows and installed the 2.3.0.5 version?

**Comment by LasseGravesen** [comment]
> 
> 
> > I downgraded to version 2.3.0.5 and now Docker runs without issue.
> 
> How did you downgrade? Did you just deleted it from your control panel in windows and installed the 2.3.0.5 version?

Uninstalled Docker 2.4.0.0 and downloaded 2.3.0.5 from here:
https://docs.docker.com/docker-for-windows/release-notes/#docker-desktop-community-2305

**Comment by rob-dotmatics** [comment]
I'm also running Trend Micro (and unable to disable it) and found 2.4.0.0 unusable. I have reverted to 2.3.0.5 and all is well. Where do we go from here?

**Comment by StevenDeRoover** [comment]
The question is: should docker be updated in order to resolve this, or TrendMicro?

**Comment by maartenbergmans** [comment]
I also had the same issue with Trend Micro. After uninstalling trend micro it was back ok. It was the Dutch version of trend micro. Maybe it is related to that, since I see that the examples above are also using the Dutch version of trend micro.

**Comment by davidspiess** [comment]
Same here, every version after 2.3.0.5 is not usable with TrendMicro installed.
