### ISSUE TITLE
Docker won't start or when it's finally running it crashes

### ISSUE THREAD

**Issue by nielsarts** [docker/for-win#8904]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 
0CA5F53F-8279-4FB0-A729-1FF58A1AA1FB/20201008120345
0CA5F53F-8279-4FB0-A729-1FF58A1AA1FB/20201008123019

### Expected behavior
Running Docker-compose or whatever like you expect to behave

### Actual behavior
Docker crashes if it's even able to get started on my Windows machine. this issue start to appear sinds update to v2.4.0.0 Tried to install the edge version but still having the same problem.

Already tried to reinstall docker on my windows machine.

### Information

  - Windows Version: Windows 10 Pro 2004 19041.546
  - Docker Desktop Version:  2.4.1.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Windows/WSL 2

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by nielsarts** [comment]
![image](https://user-images.githubusercontent.com/31060548/95458029-f3225500-0971-11eb-829e-8b0ee2a51b2a.png)

**Comment by nielsarts** [comment]
![image](https://user-images.githubusercontent.com/31060548/95462127-62e70e80-0977-11eb-8970-1ed97df53c64.png)
Second time it keeps hanging

**Comment by nielsarts** [comment]
turned on manual dns configuration to 8.8.8.8 and turned on integration with additional distros (Ubuntu-20.04). 

runned docker-compose up -d this seems to be working

**Comment by Brixomatic** [comment]
Same here. 
Docker Desktop 2.4.0.0 (48506) 
Docker Engine: 19.03.13
Channel: stable

Startup will not finish.
Tried reset to factory defaults, did not work
Tried uninstall, delete all docker folders, reboot, reinstall: Did not work.

Tried the same with Edge channel: 
got an Docker Engine (WSL2) - stopped  error.

However, wsl --list -v tells me:
  NAME                   STATE           VERSION
* Ubuntu                 Running         2
  docker-desktop         Stopped         2
  docker-desktop-data    Running         2

So obviously Ubuntu can run, docker cannot for an unknown reason.

Is there any solution or any proposed downgrade?

**Comment by nielsarts** [comment]
Mine just stopped running again.... It was working for a few minutes and then suddenly it didn't respond any more.

Everything was working fine, but ever sinds the update it doing this.  

Couldn't find a solution to downgrade (that was my first thought too)

**Comment by Brixomatic** [comment]
Tried uninstalling and installing [Docker Desktop 2.3.0.5](https://docs.docker.com/docker-for-windows/release-notes/#docker-desktop-community-2305), hoping a downgrade will do it.

Result:
```console
WSL distro stopped while waiting for Lifecycle server.
  >Stdout:

  >Stderr:
2020/10/09 09:34:51 resolving /mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-wsl-cli.iso...
2020/10/09 09:34:51 copying...
Error: mounting wslCLIDest: open /mnt/host/wsl/docker-desktop-data/isocache/5cc11eb7823cdf65a765a85ee739bad975041d3503ebb9746a5e417d0af9e2d3.iso: input/output error
2020/10/09 09:34:51 open /mnt/host/wsl/docker-desktop-data/isocache/5cc11eb7823cdf65a765a85ee739bad975041d3503ebb9746a5e417d0af9e2d3.iso: input/output error
mounting wslCLIDest
main.doRun
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:224
main.run.func1
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:83
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:762
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:852
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).Execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:800
main.main
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
```

Crash report diagnostic ID: 738B8CB0-FA72-4421-AB67-43ABBFB68811/20201009093459

WSL2/Ubuntu can run on my PC, alas my corporate client firewall blocks nslookup requests on WSL2.
That didn't stop Docker/WSL2 from working earlier.

**Comment by Brixomatic** [comment]
I noticed that I could start Docker Desktop 2.3.0.5 by this procedure:
1. Switch Docker Desktop to use the HyperV backend: Docker complains you need to re-enable HyperV.
1. re-enable HyperV on Windows
1. restart computer
1. Switch Docker Desktoo to use the WSL2 HyperV backend: Docker asks whether to enable Integration with default distros
1. enable Integration with default distros, check "Ubuntu"
1. restart Docker Desktop

After that I could "docker run hello-world" successfully.
