### ISSUE TITLE
System.InvalidOperationException: Failed to deploy distro docker-desktop to C:\Users\sahkapoo\AppData\Local\Docker\wsl\distro: exit code: -1  stdout: There are no more endpoints available from the endpoint mapper.

### ISSUE THREAD

**Issue by Skaps95** [docker/for-win#8906]
- [Yes ] I have tried with the latest version of my channel (Stable or Edge)
  - [ Yes ] I have uploaded Diagnostics
  - Diagnostics ID: ED12E19B-6532-4D8E-9B2D-CB3AF11DB880/20201008123114

### Expected behavior
Docker should run Linux / windows container successfully on Azure VM (with Hyper - V enabled)
### Actual behavior
Docker throws error System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\sahkapoo\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: There are no more endpoints available from the endpoint mapper. 

### Information

  - Windows Version: Windows 10 Pro  
  - Docker Desktop Version: 2.4.0.0 (48506)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Yes, Azure Windows VM with Hyper Machine enabled. 

### Steps to reproduce the behavior

  1. ... Installed Docker Desktop
  2. ... Start docker by double clicking the icon, "Linus Container is starting" and it crashed with the error message.

**Comment by eacevedof** [comment]
same here :( 

![](https://trello-attachments.s3.amazonaws.com/5c0935ef647dd339b9e7f791/5fb6c6e7f6acb866447cd6f9/9c0b1ca1eee435d42c2b7f4605ce0950/image.png)

**Comment by Rammstein78dev** [comment]
I have the same issue and don't know how to solve it, can you please help ?
![Docker_issue](https://user-images.githubusercontent.com/73776705/106614286-6d9f6200-656b-11eb-9de2-c34a2516398d.PNG)

**Comment by sebukoleth** [comment]
Ditto. Does it have something to do with Internet Connection Sharing or Host Network Service, since it started immediately after both were disabled?

**Comment by Skaps95** [comment]
Sorry everyone for posting this late.

I got docker to work on the machine by going into Docker Settings, then disabling WSL2 Backend and restarting docker. 

Hope this helps.

**Comment by eacevedof** [comment]
> Sorry everyone for posting this late.
> 
> I got docker to work on the machine by going into Docker Settings, then disabling WSL2 Backend and restarting docker.
> 
> Hope this helps.

I have tried your approach (before I post here) n times and it didn't work :(.  I think this has relation with some problem with Hiper-V
