### ISSUE TITLE
The process cannot access the file 'ext4.vhdx'

### ISSUE THREAD

**Issue by upsampled** [docker/for-win#8917]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F265A55D-6432-490B-838A-CC53AC1C9FC7/20201008201753

### Expected behavior
Docker to run normally and when experiencing an error, restart 
### Actual behavior
Docker crashes and is unable to restart
### Information
 Most concrete error message is seen when Docker tries and fails to restart:
```
System.IO.IOException:
The process cannot access the file 'ext4.vhdx' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
```
Using Resource Monitor I can see that there is a `vmwp.exe` process using the file (redacted Handle Names):
```
Image	PID	Type	Handle Name
vmwp.exe	8380	File	...\AppData\Local\Docker\wsl\data\ext4.vhdx
vmwp.exe	8380	File	...\AppData\Local\Docker\wsl\distro\ext4.vhdx
vmwp.exe	8380	File ...\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\ext4.vhdx
```

* the problem is intermittent. I mainly use Docker with Visual Studio Code, so i just notice I/O errors (save to disk takes two tries on occation) then the crash
* The problem appears to be new and possibly correlated with the newer Windows insider releases

  - Windows Version: 
```
❯ [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      20226  0
```
  - Docker Desktop Version:
```
❯ docker version
Client: Docker Engine - Community
 Cloud integration  0.1.18
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:00:27 2020
 OS/Arch:           windows/amd64
 Experimental:      false
```
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
run visual studio code for 30 minutes.

**Comment by upsampled** [comment]
Forcing the vmqp.exe to stop with an `End Process` appears to allow docker to restart; however, the I/O errors and crashing are still seen.

**Comment by stephen-turner** [comment]
Thanks for the report. If it's only seen on a Windows Insiders build, you need to report it to Microsoft, not us.

**Comment by upsampled** [comment]
Just going to follow up here for others:
This seems to be a known performance issue and is noted in the following Docker article:
https://docs.docker.com/docker-for-windows/wsl/#develop-with-docker-and-wsl-2
The work around is to:
* move the files onto the WSL partition (typical place would be `~/` in the wsl shell), 
* open VS Code in WSL mode, 
* open the WSL directory containing the code 
* finally open the dev container like you normally would.

**Comment by tgalery** [comment]
Hi @upsampled I'm having this issue as well with inside preview 21301. Any pointers on how to fix things ?

**Comment by upsampled** [comment]
@tgalery did you perform the steps I mentioned? Basically you want to keep all disk access on the WSL partition.

**Comment by tgalery** [comment]
hum .... I have a `code` folder that lives in another ssd, and have it symlinked to my home in the wsl partition and use vscode as instructed in the guide. I'm getting this error when I start windows and docker desktop starts running in the background. Once I'm within ubuntu, it's all good.

**Comment by XedinUnknown** [comment]
Same thing here. Win10, WSL2, Ubuntu 20. Cannot start Docker. Same error. Insider build.

I didn't quite understand what to do exactly. The files are on the WSL partition, and I usually edit them with PHPStorm in Windows.

**Comment by XedinUnknown** [comment]
My files live entirely in WSL. The folder where they live is being mounted into Windows by the native Windows/WSL mechanism. What am I doing wrong? 🤔

**Comment by tgalery** [comment]
In my case, the files exist in the windows partition that gets mounted to home, but I get the error at start up, not when I'm running docker. So I disabled docker from running at startup on windows, but I'm able to run containers from within wsl.

**Comment by dominikcebula** [comment]
I was able to solve `The process cannot access the file 'ext4.vhdx' because it is being used by another process` when `ext4.vhdx` is locked by `vmwp.exe` using the following `Dismount-VHD` cmdlet:
https://docs.microsoft.com/en-us/powershell/module/hyper-v/dismount-vhd

Here is what I did step by step:
1. Frist, make sure that Docker Desktop and WSL are shutdown:
a) Right-click on Docker Desktop Tray Icon and click `Quit Docker Desktop`
b) Wait for Docker desktop to shutdown
c) open the command line and type `wsl --shutdown`

2. Now, you can use the `Dismount-VHD` cmdlet:
a) open PowerShell
b) go to `C:\Users\YourUsername\AppData\Local\docker\wsl`
c) Type `Dismount-VHD -Path .\data\ext4.vhdx`
d) Type `Dismount-VHD -Path .\distro\ext4.vhdx`
