### ISSUE TITLE
Impossible to add registries in %USERPROFILE%\.docker\config.json

### ISSUE THREAD

**Issue by mabead** [docker/for-win#892]
### Expected behavior

It should be possible to configure external registries in %USERPROFILE%\.docker\config.json.

### Actual behavior

If we modify the file, whenever docker for windows starts, it overwrites config.json and loses our changes.

### Information

Docker version:
```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

### Steps to reproduce the behavior

  1. Stop docker for windows 
  2. Edit the file %USERPROFILE%\.docker\config.json by adding a new server in the 'auths' section. Ex: 
```
{"auths":{ "https://my.registry.com": { "auth": "my_key=", "email": "my@email.com" }},"credsStore":"wincred"}
```
3. Start docker for windows
4. Look at %USERPROFILE%\.docker\config.json. The file is back to the default content:
```
{"auths":{},"credsStore":"wincred"}
```

**Comment by jasonbivins** [comment]
Hi @mabead   I can reproduce this on my machine as well - I'll go ahead and write it up as a bug

**Comment by mabead** [comment]
@jasonbivins Sorry for the late response. If I look at this [documentation](https://docs.docker.com/engine/reference/commandline/dockerd/#linux-configuration-file) for the format of daemon.json, I don't see anything related to secured registries. (I see options for insecure registries and registry mirrors). 

Can you give an example of what you want me to add in daemon.json?

**Comment by jasonbivins** [comment]
Hi @mabead 
You can actually make the change in the GUI under the Daemon settings - Just add the registry information there in that screen and it will add it to the daemon.json file

**Comment by mabead** [comment]
Here's why I did:

- added `mysite.com:88` in the list of "Insecure Registries" in the Daemon seetings in the GUI.
- apply and wait for docker to be restarted
- opened C:\ProgramData\docker\config\daemon.json
- **Result**: The file only contains this:
```
{}
```
- close gui & open gui
- Go in the Daemon section
- look at the Daemon settings. It still contains mysite.com:88
- Click on `Advanced`. This gives me the option to edit a config file in the gui. Here is what I have:
```
{
  "registry-mirrors": [],
  "insecure-registries": [
    "mysite.com:88"
  ],
  "debug": true,
  "experimental": true
}
```
- Apply changes.
- Wait for docker to restart
- Look at `%programdata%\docker\config\daemon.json`. It still only contains this.
```
{}
```

**Comment by friism** [comment]
@mabead the content of the `%programdata%\docker\config\daemon.json` file is immaterial, at least as long as you're running Docker Linux containers. When you change this in the GUI, the settings are propagated to the host that runs the Docker Engine and your containers.

After you added the registry in the GUI, can you not pull and push from the insecure registry?

**Comment by mabead** [comment]
@friism Maybe it's me that is confused but I don't want to modify the `daemon.json` file. I want to modify the `%USERPROFILE%\.docker\config.json`. My final goal is to add registry credentials in config.json like this:

```
{"auths":{ "https://my.registry.com": { "auth": "my_key=", "email": "my@email.com" }},"credsStore":"wincred"}
```

My goal is **not** to configure an insecure registry. My goal is to save credentials for a secure registry.

As I understand it, the daemon.json does not make it possible to enter registry credentials. This has to be done in config.json.

Can you confirm if I am getting something wrong?

Note that I am running Docker Linux containers.

**Comment by friism** [comment]
@mabead ah, sorry. If you shell out and run `docker login` is that also removed if Docker for Windows is stopped and started?

**Comment by mabead** [comment]
@friism Here's what I did:
- docker login
- My config.json contains the following:
```
{
	"auths": {
		"docker.landr.com": {}
	},
	"credsStore": "wincred"
}
```
- stopped docker
- started docker
- I looked at config.json and it was still containing this:
```
{
	"auths": {
		"docker.landr.com": {}
	},
	"credsStore": "wincred"
}
```

**Comment by friism** [comment]
ok, so that solved the problem? Idk how else (than by running `docker login -p <pw> -u <user>`) you'd get your password stored in the Windows credstore

**Comment by mabead** [comment]
@friism This solved my problem indeed. Note that it was a little difficult since we have a V1 registry which is not supported by default with docker 17.06. I had to modify the daemon.json to say `"disable-legacy-registry":false`.

Even though my need to modify config.json is gone thanks to `docker login`, it is still impossible to modify config.json. This may cause problem to someone else for a different reason. 

Note that in my organization, most devs (in fact, everyone except me) that tried to upgrade to 17.06, rolled back to an older version when they saw that they were not able to modify config.json. That's the recipe that they are used to follow to configure the credentials for our registry.

**Comment by friism** [comment]
We're addressing that problem as part of the fix for this: https://github.com/docker/for-win/issues/867

**Comment by mabead** [comment]
Stale issue... closing.
