### ISSUE TITLE
92378ED3-410A-4AE9-9225-36199F0DD67E/20201009220316

### ISSUE THREAD

**Issue by NaveenVanam** [docker/for-win#8937]
Hi,

I am seeing Failed to create or configure Hyper-V VM: Sequence contains no elements issue while trying to launch docker desktop on my machine and uploading the data to troubel shoot on this. Please find the diagnostics id below

Failed to create or configure Hyper-V VM: Sequence contains no elements

92378ED3-410A-4AE9-9225-36199F0DD67E/20201009220316

  - [ ] I have tried with the latest version of my channel (Stable or Edge) --Stable
  - [ ] I have uploaded Diagnostics...Yes 
  - Diagnostics ID:92378ED3-410A-4AE9-9225-36199F0DD67E/20201009220316

### Information

  - Windows Version: Windows 10 Pro
  - Docker Desktop Version: 2.4.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Windows machine

### Steps to reproduce the behavior

  1. after installing the docker on windows desktop 
  2. while trying to launch the docker we can see this issue

**Comment by chinkung** [comment]
I also got the same issue
Diagnostics ID: 2BA004B0-91D4-4F5D-B9FB-71C26AAC9EFC/20201020164449
