### ISSUE TITLE
Docker on windows fails to pull linux images behind proxy

### ISSUE THREAD

**Issue by sami-alajrami** [docker/for-win#894]
### Expected behavior
docker pull should be able to pull linux images.
### Actual behavior
the pull command starts downloading image layers and then hangs forever without completion.
### Information
Docker for windows pulls windows images fine when in the windows containers mode. When switching to linux containers and running an image pull command, the download starts and hangs forever.  The corporation proxy is configured and works well when in the windows containers mode. Connecting to a non-corporate network without a proxy works well in both linux and windows containers modes. I have tried to set the `--max-concurrent-downloads` to 1 as suggested in [#22445](https://github.com/moby/moby/pull/22445), #580 and [here](https://docs.docker.com/engine/reference/commandline/pull/#concurrent-downloads). But it did not work as this option is not supported by windows [as shown here](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/configure-docker-daemon).
  - Diagnostic ID : 4D08818A-545E-40A2-B75A-6C92FB4B7BBC/2017-07-05_11-40-23
  - host distribution and version: Windows 10 Enterprise 

### Steps to reproduce the behavior

  1. Install Docker for windows 17.06.0-ce on windows 10 Enterprise
  2. Configure the proxy settings in Docker settings.
  3. Run a pull command to pull a linux image e.g.,  `docker pull nginx`

**Comment by jasonbivins** [comment]
Hi @sami-alajrami 
Can you try to pull a Linux image using CMD instead of powershell?  I've had similar issues, and I noticed that I get different behavior between PS and CMD

**Comment by sami-alajrami** [comment]
Hi @jasonbivins .. both CMD and PS give the same result in my case

**Comment by lucaghersi** [comment]
I have the same exact issue here. If I switch back to Windows container everything works.

**Comment by sami-alajrami** [comment]
@lucaghersi try setting the proxy as:  http://username:password@proxy.example.com

**Comment by tallaxes** [comment]
You can set max-concurrent-downloads on Docker for Windows. In configuration Daemon section switch to advanced and add `"max-concurrent-downloads": 1` to the JSON structure. Seems to fix the issue for me.

**Comment by var23rav** [comment]
You can set the proxy in docker using the Docker GUI -> Settings . 
![docker](https://user-images.githubusercontent.com/7958115/34986942-7adabb80-fadf-11e7-9821-ec59b7ca3392.JPG)

**Comment by btrepp** [comment]
This still occurs.
Windows containers pull down fine and use the proxy.
Linux containers appear to ignore that and timeout (ironically I can see docker hitting up the registry contanstly in the background, so it understands the setting, just doesn't use it on docker pull)

 Trying to set max-concurrent-downloads via the GUI has a red message "Invalid Option", and doesnt let you save/apply the json

**Comment by JonasBean** [comment]
Is there anything new to this problem? Been trying for 2 days to pull with linux containers but no luck. With windows container activated it pulls just fine but with linux containers I get the error:

dial tcp *proxyadress*:8080: getsockopt: no route to host

**Comment by Makoehle** [comment]
- When pulling Windows images it pulls fine. There is no network tab present. 
- When switching to Linux it fails with: `Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)` Network tab is present.

I don't know if network tab may indicate something I just mention it because it differs.

**Comment by martin-br** [comment]
I have the exact same behavior. I also tried max-concurrent-downloads parameter without any changes.
Pulling windows image is working while pulling linux image is failing. I am also working behind a corporate proxy.

**Comment by philippseith** [comment]
Same behavior here. cntlm is not logging any request while trying to pull a linux container (but for windows containers, it does).

**Comment by LorenzoCC** [comment]
No luck either with the newest Edge version 18.06.1-ce-win74 (19508) on Windows 10 version 1803.

Here's a relevant [link](https://mandie.net/2017/12/10/docker-for-windows-behind-a-corporate-web-proxy-tips-and-tricks/), but it does not work for me. It seems that in current versions the proxy is set automatically to the Hyper-V Ethernet adapter (called "DockerNAT" on my system, not "DummyDesperatePoitras" in the article), whose address is set in Settings->Network->Internal Virtual Switch.

**Comment by philippseith** [comment]
I changed the docker proxy settings from http://127.0.0.1:3128 to http://docker.for.win.localhost:3128.
That did the trick.

**Comment by jaslinfernando** [comment]
> I changed the docker proxy settings from http://127.0.0.1:3128 to http://docker.for.win.localhost:3128.
> That did the trick.

awesome bro., this work for me when I work in windows and switch to Linux container with a proxy. The proxy that remain it was http://10.0.75.0:3128 and whit that trick of from http://127.0.0.1:3128 to http://docker.for.win.localhost:3128 resolved my problem.

**Comment by galaxy79** [comment]
@jaslinfernando can you tell where exactly you made the change? is modified the proxies and it didnt work for me ? Also i see some article talking about the change in config.json file under .docker folder

**Comment by jaslinfernando** [comment]
@galaxy79 The change it was done in the settings of my docker GUI in windows. Right side on the the task bar from the docker icon. I Choose Settings and  tab Proxies. Then I change the input of Web Server(HTTP) to value "http://docker.for.win.localhost:3128". Before you must be in mode Linux Container bro. If you do in config.json file under docker folder do not work at least for me. :)

**Comment by ZenwalkerD** [comment]
> 
> 
> I changed the docker proxy settings from http://127.0.0.1:3128 to http://docker.for.win.localhost:3128.
> That did the trick.

That did the trick here. Win 10 + Docker + Linux container ==> behind corporate proxy
