### ISSUE TITLE
Attached connection is dropped on `~/`

### ISSUE THREAD

**Issue by PiotrZabowka** [docker/for-win#895]
### Expected behavior
Sending `~/` or multiple characters at once to an attached container won't drop session.

### Actual behavior
When I type `~/` or multiple characters at once in a quick succession to an attached container console it drops session.

### Information
  - A diagnostic was uploaded with id: 83FF2A67-5CB4-4591-8D0E-E1021E3FAEE4/2017-07-05_12-20-12
  - Microsoft Windows 10 Pro - v 10.0.15063 
  - Docker: Version 17.06.0-ce-win18 (12627) Channel: stable d9b6651

### Steps to reproduce the behavior

  1. Attach to any container `docker attach <container>`
  2. Type `~/` 
  3. Connection is dropped

**Comment by ymor** [comment]
Having the same issue, its driving me insane with my fat fingers :)
