### ISSUE TITLE
[docker-compose]cannot start service: error while creating mount source path - permission denied

### ISSUE THREAD

**Issue by uday31in** [docker/for-win#897]
### Expected behavior

Run Docker-compose from visual studio and debug app.

### Actual behavior

Failing to build project with Docker compose fao

### Information

```
PS C:\git\azuredctspv2> docker-compose -f "C:\git\azuredctspv2\docker-compose.yml" -f "C:\git\azuredctspv2\docker-compose.override.yml" -f "C:\git\azuredctspv2\obj\Docker\docker-compose.vs.debug.g.yml" config
services:
  azuredctsp:
    build:
      args:
        source: obj/Docker/empty/
      context: C:\git\azuredctspv2\azuredctsp
      dockerfile: Dockerfile
    entrypoint: tail -f /dev/null
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DOTNET_USE_POLLING_FILE_WATCHER: '1'
      NUGET_FALLBACK_PACKAGES: /root/.nuget/fallbackpackages
    image: azuredctsp:dev
    labels:
      com.microsoft.visualstudio.debuggee.arguments: ' --additionalProbingPath /root/.nuget/fallbackpackages  bin/Debug/netcoreapp1.1/azuredctsp.dll'
      com.microsoft.visualstudio.debuggee.killprogram: /bin/bash -c "if PID=$(pidof
        -x dotnet); then kill $PID; fi"
      com.microsoft.visualstudio.debuggee.program: dotnet
      com.microsoft.visualstudio.debuggee.workingdirectory: /app
    ports:
    - 80/tcp
    volumes:
    - C:\git\azuredctspv2\azuredctsp:/app:rw
    - C:\Users\udpandya\vsdbg:/remote_debugger:ro
    - C:\Users\udpandya\.nuget\packages:/root/.nuget/fallbackpackages:ro
    - C:\Users\udpandya\.nuget\packages:/root/.nuget/packages:ro
version: '3.0'
```

```
PS C:\git\azuredctspv2> docker-compose -f "C:\git\azuredctspv2\docker-compose.yml" -f "C:\git\azuredctspv2\docker-compose.override.yml" -f "C:\git\azuredctspv2\obj\Docker\docker-compose.vs.debug.g.yml" up
Removing azuredctspv2_azuredctsp_1
Recreating ba6a68db9dd6_ba6a68db9dd6_azuredctspv2_azuredctsp_1 ...
Recreating ba6a68db9dd6_ba6a68db9dd6_azuredctspv2_azuredctsp_1 ... error

ERROR: for ba6a68db9dd6_ba6a68db9dd6_azuredctspv2_azuredctsp_1  Cannot start service azuredctsp: error while creating mount source path '/C/Users/udpandya/.nuget/packages': mkdir /C/Users/udpandya/.nuget: permission denied

ERROR: for azuredctsp  Cannot start service azuredctsp: error while creating mount source path '/C/Users/udpandya/.nuget/packages': mkdir /C/Users/udpandya/.nuget: permission denied
ERROR: Encountered errors while bringing up the project.
```
### Steps to reproduce the behavior

  1. Create Visual Studio Project with docker support
  2. Run the project

**Comment by ljt91** [comment]
Stumbled across this issue as well.

I was using a Service Account (docker) for the Shared Drives (C:\) in Docker for Windows.

That account unfortunately didn't have sufficient permissions to access the required directories (C:\Users\*username*\vsdbg / C:\Users\*username*\.nuget) on my primary user account (even though it was part of the administrators group) which I run Visual Studio in.

To fix this, I added the Service Account (docker) onto the folders above and provided full read/write which then allowed the build to successfully complete.

Hope this help.

Lyon

**Comment by SychevIgor** [comment]
still actual for vs2017 and Version 17.09.0-ce-win32 (13529)

**Comment by jonscheiding** [comment]
I've encountered this issue as well.

- Docker version: **17.12.0-ce-win47 (15139)** / **9c692cd**
- Windows 10 version: **1703 (OS Build 15063.786)**
- VS version N/A
- Diagnostic ID: **65AB8B82-7541-43EF-9450-F716122AD897/2018-01-30_10-55-25**

I have changed my Docker settings to use a service account user (`docker`) for file sharing instead of my domain account.  Now, when I run `docker-compose up` and there is bind mounting involved, I get an error like the OP's:

```
Starting proj_srv_1 ... error

ERROR: for proj_srv_1  Cannot start service srv: error while creating mount source path '/host_mnt/c/Users/me/Documents/proj': mkdir /host_mnt/c/Users/me/Documents/proj: permission denied

ERROR: for srv  Cannot start service srv: error while creating mount source path '/host_mnt/c/Users/me/Documents/proj': mkdir /host_mnt/c/Users/me/Documents/proj: permission denied
```

If I explicitly add my `docker` user with Full Control over all directories in that path, it works.  This is weird to me because `docker` is a member of the local Administrators group, which has Full Control already.  Why would adding the user directly make a difference?

**Comment by stroebele** [comment]
@ljt91 Had to add C:\Users\username\source, to the list folders that needed permissions but that did the trick!

**Comment by ljt91** [comment]
+1 - Encountered this issue with Microsoft Account, created a Local Service Account (Docker) and assigned it permissions to my .nuget and vsdbg directories to resolve this issue.

**Comment by JorgeBusinessInsights** [comment]
@ljt91 what do you mean by Service account (docker)?

**Comment by ljt91** [comment]
@JorgeBusinessInsights creating a local windows user account.

**Comment by rcmorano** [comment]
I couldn't find a "docker" user, but a "docker-users" group. I've added full permissions for it, but nothing changed.

I'm using this PowerShell snippet to do it (replace '_DOCKER_VOLUMES_PATH_' with your involved path):

```
$Acl = Get-Acl "_DOCKER_VOLUMES_PATH_"
$Ar = New-Object system.security.accesscontrol.filesystemaccessrule("docker-users","FullControl","Allow")
$Acl.SetAccessRule($Ar)
Set-Acl "_DOCKER_VOLUMES_PATH_" $Acl
```

I've also "grepped" (by eye, thru the output of this [1] command) the account that 'docker' service is running under and it seem it's "LocalSystem", not "docker", so in my case, it's supposed to have permissions also...

BTW, I'm trying to create some volumes under a "Program Files" subdirectory; dunno if there is a special case for this one...

[1] Look for "StartName" in 'docker' service when executing this:
```
Get-WmiObject win32_service | format-list *
```

**Comment by rcmorano** [comment]
I found a workaround for my case.

Here you have some more info of my scenario:

* I'm referencing relative paths in docker-compose.yml (in e.g.: _./data:/data_)
* I was able to workaround the problem by manually creating every volume 'docker-compose' wasn't able to 'mkdir' (_./data/var/log_, _./data/usr/local/xxx_...)

**Comment by bytedaddy** [comment]
Docker Factory Reset did it for me on WIndows

**Comment by pustun** [comment]
I had the same issue, turned out to be it was becaused I had changed my domain password couple days before. I pressed restart and docker at startup asked my new password. now it works fine.

**Comment by cernhofer** [comment]
I also had this issue- was able to solve it by restarting docker and resetting the shared drive credentials.
