### ISSUE TITLE
After update to 2.4.0.0 mount /mnt/wsl/docker-desktop-data/data/docker is missing

### ISSUE THREAD

**Issue by jeroenvanderschoot** [docker/for-win#8977]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Installing Docker Desktop with WSL2 backend mounts /mnt/wsl/docker-desktop-data/data/docker
### Actual behavior
Mount is missing after upgrade from 2.3.x to 2.4.0.0.

### Information
  - Windows Version: Windows 10 2004
  - Docker Desktop Version: 2.4.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
1. Install Ubuntu 2004
2. Install Docker Desktop 2.4.0.0
3. Open WSL prompt
4. See that `ls /mnt/wsl/docker-desktop-data/data/docker` is empty

**Comment by jeroenvanderschoot** [comment]
Is there any way to get these mounts back?
Or are they located in a different place?

**Comment by jeroenvanderschoot** [comment]
Anybody?

**Comment by jjensen** [comment]
I am missing the content of /mnt/wsl/docker-desktop-data/data, too. It would be very nice to have it back.

**Comment by fermancz** [comment]
Same problem with newest versions. I had to downgrade back to **_Docker Desktop 2.3.0.5_**. After downgrade the content of the directory /mnt/wsl/docker-desktop-data/data is back.

**Comment by dcrouch79** [comment]
A total hack but you can manually re-mount the missing docker folder using the `\\wls$` windows share:

```
# create missing docker sub-folder
sudo mkdir /mnt/wsl/docker-desktop-data/data/docker

# mount as readonly with 755 permissions
sudo mount -t drvfs '\\wsl$\docker-desktop-data\version-pack-data\community\docker' /mnt/wsl/docker-desktop-data/data/docker -o ro,umask=022
```
