### ISSUE TITLE
UPDATE: Docker Desktop 3.1.0 (on Windows 10) randomly loses images, containers, settings, and "about" info (happened on v2.4.0 previously)

### ISSUE THREAD

**Issue by jnjkcole** [docker/for-win#8981]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A0668A74-EB29-4DD9-9CE1-E59073A6C759/20201002224117
  - Diagnostics ID: A0668A74-EB29-4DD9-9CE1-E59073A6C759/20201004015445

### Expected behavior
- Docker Desktop does not lose its mind.

### Actual behavior
- On system bootup, Docker Desktop starts normally, containers are listed and can be started
- After a period of runtime, Docker Desktop loses knowledge of containers, images, settings, and "about" info
- This occurs after an undetermined period of time (hours?), but certainly one or more times in a work day.
- Restarting Docker Desktop does not fix the issue. A full system restart is required to fix the issue.

### Information

  - Windows Version: Windows 10  [Version 10.0.17763.1457]
  - Docker Desktop Version: 2.4.0.0 Stable
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

  - The problem isn't specifically "reproducible" by performing any specific action other than waiting for it to recur.
  - The problem is new within the last couple or few weeks. I think it may have occurred with an update to 2.4.0.0, but I cannot be certain of that.

### Steps to reproduce the behavior

  1. Startup my Windows system and wait for Docker Desktop to run
  2. Start one of my containers
  3. Wait a while to lose connection to the container

### Screen captures

![docker desktop issues blurred](https://user-images.githubusercontent.com/34521276/95741114-b4371c80-0c5b-11eb-8eb5-977ceb12298c.jpg)

**Comment by stephen-turner** [comment]
Thanks for the report, @jnjkcole. That's very weird. Do the command line commands still work, e.g. `docker container ls` or `docker image ls`?

**Comment by jnjkcole** [comment]
> Thanks for the report, @jnjkcole. That's very weird. Do the command line commands still work, e.g. `docker container ls` or `docker image ls`?

No. Once Docker Desktop loses its mind, then no commands work. Additionally, if I opened a CLI window to the container, it just becomes unresponsive.

**Comment by AlexHorlenko** [comment]
Have same behaviour.
Docker version 2.4.0.0 (48506)
```
>docker info
Client:
 Debug Mode: false

Server:
ERROR: Cannot connect to the Docker daemon at npipe:////./pipe/docker_engine. Is the docker daemon running?
errors pretty printing info
```
From DockerService windows events - only info messages present about starting and stopping service and about PowerEvent handling. From what I saw - seems like docker is loosing connect to pipe in 100% when my laptop goes into sleep or hibernate, but can't claim that it does not happens without such events.

**Comment by stephen-turner** [comment]
OK, thanks, we'll have a look. @AlexHorlenko do you have a diagnostics id please?

**Comment by AlexHorlenko** [comment]
sorry, no. I moved back to 2.3.0.4 that I had installer locally, I will recreate the issue on weekend and send the diagnostics id

**Comment by rob-dotmatics** [comment]
This issue is a better description of my own ticket, except for me the run time before crashing could be measured in seconds rather than hours (https://github.com/docker/for-win/issues/9122 - see linked diagnostics ids).
I have had to revert to 2.3.0.5, which works perfectly. We really need to understand what is causing this issue, since it has caused loss of work (and time) and I can't ask developers to never upgrade Docker again.

**Comment by rob-dotmatics** [comment]
This ticket https://github.com/docker/for-win/issues/8902 references Trend Micro, which I am running and am unable to disable due to corporate policy.

**Comment by jnjkcole** [comment]
Whelp. The issue is back again. It resolved pretty much on its own (?) maybe one of the minor v2.x minor version updates. 

I worked without issue from Nov 2020 to Jan 2021. After upgrading to v3.x the issue has reappeared. As before, restarting Docker isn't sufficient. If I reboot my entire Windows workstation, then I'll have access to my linux image for a few minutes ... I can launch VSCode on my workstation, attach it to my image, start to do some coding, then the terminal dumps and nothing short of a full workstation reboot gets me back to my docker container.

I'm on version 3.1.0 (51484).

![docker2](https://user-images.githubusercontent.com/34521276/107591217-256de880-6bd8-11eb-80ff-4b477291bc6d.jpg)
![docker1](https://user-images.githubusercontent.com/34521276/107591220-26067f00-6bd8-11eb-9313-9673fa7ac8c3.jpg)

**Comment by stephen-turner** [comment]
@jnjkcole Do you have any corporate software security running in your environment? It could be that it is blocking the connection between the front end and the back end.

**Comment by jnjkcole** [comment]
> @jnjkcole Do you have any corporate software security running in your environment? It could be that it is blocking the connection between the front end and the back end.

We do. We're using Trend Micro, which I see might be an issue based on other posts. I do not have the ability to change that installation. I'm not sure what happened from late October when I first reported this issue to late January when it reappeared that allowed me to work with Docker uninterrupted.

I'll be contacting the internal team responsible for desktop security to see if there are options for a workaround or a change to configuration. We're a big Docker shop, so I have to imagine that they've seen this before which I would have thought would translate into a configuration that allows Docker to run.

**Comment by stephen-turner** [comment]
It would be interesting to know whether they've changed the Trend Micro configuration recently.

**Comment by jnjkcole** [comment]
> It would be interesting to know whether they've changed the Trend Micro configuration recently.

agreed

**Comment by rob-dotmatics** [comment]
When we had the same issue with 2.4.x and 2.5.x we raised a support ticket with Trend Micro and were told there was no issue. I have not tried to upgrade Docker recently, and based on the above this sounds like it would be foolish.

**Comment by jnjkcole** [comment]
NEW INFO: Today, I changed the file sharing rights from the sub-directory for my repo code to the entire C:\ volume. After many hours, I am still working. This seems like an interesting development.

![docker4](https://user-images.githubusercontent.com/34521276/107696149-96b4a680-6c7f-11eb-8c0b-67ec102fdbd6.jpg)

**Comment by stephen-turner** [comment]
I agree it seems interesting, but I can't explain it. Surely sharing more could only be worse?

**Comment by jnjkcole** [comment]
UPDATE: I left my computer running overnight. This morning, my container is still running and accessible.

The sharing setting had previously been set to my code subdirectory ('c:\git', for example). and had worked fine for months. The reason I changed this setting to "C:\" during this troubleshooting effort was an entry on the support team's page that said, 
>Important Installation Notes for <_mycompany_> Uses:
>* For Windows installation, ensure that the docker engine file sharing configuration is set to allow access to the whole 'c:\' drive

Without deeper digging, I would **guess** that there might be a connection between my company's default image, _maybe_ AV (??), and the Docker sharing setting.

I'll run with this config and see what happens.

**Comment by stephen-turner** [comment]
That's very interesting. It sounds like they've encountered this before and have discovered how to fix it. I wonder whether they know what the reason is that it works.
