### ISSUE TITLE
TLS handshake timeout after upgrading from 2.3.0.3 to 2.4.0.0

### ISSUE THREAD

**Issue by thenyak** [docker/for-win#8982]
### Expected behavior
docker login succeeds

### Actual behavior
docker login <host>
Authenticating with existing credentials...
Login did not succeed, error: Error response from deamon: Get https://host/v2/: net/http: TLS handshake timeout

### Information
  - Did the problem appear with an update? Yes, after upgrading from 2.3.0.3 to 2.4.0.0
  - Windows Version: Windows 10 Enterprise 1809 17763.1457
  - Docker Desktop Version: 2.4.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No
  - Note this error is happening for an internal Artifactory registry which uses a wildcard certificate
  - Per documentation (https://docs.docker.com/docker-for-windows/#adding-tls-certificates) "Docker Desktop creates a certificate bundle of all user-trusted CAs based on the Windows certificate store, and appends it to Moby trusted certificates. Therefore, if an enterprise SSL certificate is trusted by the user on the host, it is trusted by Docker Desktop". Seems to have been true with 2.3.0.3 but something changed in later releases.

### Steps to reproduce the behavior
  1. Install 2.4.0.0
  2. After installation attempt to login to internal registry over https

### Attempts to resolve the issue
  1. Install latest Edge release (2.4.1.0) - same behavior
  2. Reviewed https://docs.docker.com/docker-for-windows/#adding-tls-certificates. It refers to https://docs.docker.com/docker-for-windows/faqs/#how-do-i-add-custom-ca-certificates which refers back https://docs.docker.com/docker-for-windows/#adding-tls-certificates (documentation is circular and doesn't provide specifics for adding a custom CA certificate).
  3. Based on documentation for client certs, created C:\Users\username\\.docker\certs.d\host
  4. Added CA crt file to C:\Users\username\\.docker\certs.d\host
  5. Restarted Docker Desktop
  6. docker login host - same error
  7. Reverted back to 2.3.0.3 I am able to successfully login and pull from the internal registry.
  8. docker login host
      Authenticating with existing credentials...
      Login Succeeded

**Comment by stephen-turner** [comment]
Thanks for the report, @thenyak. Please upload diagnostics from 2.4 and paste the ID here. Also, could you expand on the steps to reproduce with the exact command you used? Thanks.
