### ISSUE TITLE
Docker for Windows unable to access shared drive path

### ISSUE THREAD

**Issue by ToddEng** [docker/for-win#899]
### Information

  - C2BB8407-D623-4810-A5CF-6A6AA06C97A9/2017-07-05_08-53-50

  - Version 17.06.0-ce-win18 (12627)
Channel: stable
d9b6651

### Steps to reproduce the behavior

  1. Shared C drive
  2. Created container with the following command docker run -d --name lubrizol -v c:\lookout\opt1\lookoutsiem\configs:/conf lookoutsiem
  3. The follow error shows in the log and container exits right away.

[09:19:17.068][ApiProxy       ][Info   ] Rewrote mount c:\lookout\opt1\lookoutsiem\configs:/conf (volumeDriver=) to /c/lookout/opt1/lookoutsiem/configs:/conf
[09:19:17.084][ApiProxy       ][Info   ] Failed to read proxies/http from snaphshot p9p.MessageRerror{Ename:"No such file or directory"}

**Comment by kallie-b** [comment]
@ToddEng Can you provide more details as to your host configuration? Is your host part of a corporate network? What are the proxy settings for your host/network? Is your host running over a VPN?

**Comment by ToddEng** [comment]
I’m no longer having the shared drive problem. I’m not able to have my docker linux vm get an address from dhcp. Can you help with that?

**Comment by kallie-b** [comment]
@ToddEng -- Sure, I can help out with that. 

Can you provide some details on the errors/symptoms you're getting? What are the repro steps for this?

Also, it would still be good to understand your host configuration, including any proxy/VPN settings.

**Comment by ToddEng** [comment]
I am running Docker for Windows 10 using the Linux container and I have the vm connect to the external switch in Hyper-V manager. I have the default subnet address and mask in the Docker settings.
