### ISSUE TITLE
Docker Unable to Start

### ISSUE THREAD

**Issue by rn44** [docker/for-win#8994]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Shashank-KP** [comment]
Try This:
_cd "C:\Program Files\Docker\Docker"_
**./DockerCli.exe -SwitchDaemon**
