### ISSUE TITLE
Inconsistent file counts using PHP via Docker Desktop on WSL2

### ISSUE THREAD

**Issue by themizzi** [docker/for-win#8997]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E92C0EAB-8494-4665-BCAE-571376715391/20201013021123

### Expected behavior

File counts from `scandir` and `RecursiveDirectoryIterator` do not diverge.

### Actual behavior

File counts diverge between `scandir` and `RecursiveDirectoryIterator`.

### Information
  - Windows Version: 10 (2004)
  - Docker Desktop Version: 2.4.0.0 (48506)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Running locally on my desktop.

### Steps to reproduce the behavior

Must be using the **WSL2** engine!

Please see this repository for a full reproduction:

https://github.com/themizzi/wsl2-php-recursive-directory-iterator-bug

**Comment by simonferquel** [comment]
Hi,
Are you hosting the files within your WSL2 distro or on the Windows file system ?

**Comment by themizzi** [comment]
I am hosting this on the Windows file system because as a developer working on PHP with IntelliJ products it is not optimal to access the WSL2 filesystem over a network share in their software. It may be a tradeoff I have to sacrifice now or I need to use the Hyper V backend which has its own file performance issues. There is a bug tracking with WSL that `lseek` is not working properly against v9fs (https://github.com/microsoft/WSL/issues/5074) that PHP has responded as being the issue, but that issue is closed. I fear I am in a position where nobody really cares about this but myself right now. Does not appear that this is particularly an issue with Docker for Desktop itself though and at least there is still some remediation by using the Hyper V backend.

**Comment by simonferquel** [comment]
Actually file system performance with files hosted on Windows is worse with WSL2 backend than with Hyper-V, So you should really put your files within the WSL2 distro and make IntelliJ access them from `\\wsl\Ubuntu\...`.

Note that since latest version, you can mount files living in a WSL distro from a Windows executable, with mount expressions such as `docker run -v \\wsl\Ubuntu\sources:/sources ...`

**Comment by bezdutchek** [comment]
@themizzi did u manage to fix it?

**Comment by bezdutchek** [comment]
@themizzi I don't know your use case of RecursiveDirectoryIterator but here's what helped me ... simply I started having this issue after running PHP app on Windows machine under WSL2 but the code it was running was completely copied from my previous Linux distro. One of my composer dependencies was using the RecursiveDirectoryIterator.

I don't know why and how but it all suddenly started working when I deleted vendor folder and ran `composer install` again under WSL2
