### ISSUE TITLE
Docker fails to start with error: Docker hv-sock proxy (vsudd) is not reachable

### ISSUE THREAD

**Issue by RealGandy** [docker/for-win#900]
### Expected behavior
Docker should start

### Actual behavior
Docker fails to start with error: Docker hv-sock proxy (vsudd) is not reachable

### Information

Diagnostic ID: D15420F9-3B32-4CA5-B828-D30A4313B54B/2017-07-05_15-10-32

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

Windows 10 Pro 15063.
This occurred after the latest Microsoft updates, installing the 'Creator Edition'

### Steps to reproduce the behaviour

**Comment by whitecolor** [comment]
Every time I start windows I have this error and before docker is trying to start for a few minutes
A diagnostic was uploaded with id: D449E0EB-BA21-4703-BB58-FECB9D4ED103/2017-07-06_15-19-34

After I do `restart docker`, and it usually starts ok (it takes too a few minutes) - quite long actually. But at least it works.

**Comment by jasonbivins** [comment]
Hi @RealGandy 
It looks like there was a problem with DNS during the install, or the network adapter isn't getting created properly.
Can you run this Debug script and share the results?  
https://github.com/Microsoft/Virtualization-Documentation/tree/live/windows-server-container-tools/Debug-ContainerHost

**Comment by jasonbivins** [comment]
@whitecolor 
If you turn off the Auto start function, and start Docker manually - do you get the same error?

**Comment by whitecolor** [comment]
Switched if off, will check next time I reset my PC.

**Comment by RealGandy** [comment]
@jasonbivins After the next reboot and manually starting docker it started running.

Output of the script attached.
[Debug.output.txt](https://github.com/docker/for-win/files/1133190/Debug.output.txt)

**Comment by jasonbivins** [comment]
@RealGandy - it looks like the virtual switch is either just slow to respond - or has some stale data.

The easiest way to solve this might just be to set Docker to use a fixed DNS address using the Network option in the GUI, or just toggle from auto to fixed - this will also trigger it to refresh the virtual adapter.   If that doesn't work - there are some great troubleshooting tips for refreshing stale data here: https://docs.docker.com/docker-for-windows/troubleshoot/#networking-issues

![image](https://user-images.githubusercontent.com/28021664/27999502-e547b994-64eb-11e7-94e0-6deeffe9ce0a.png)




  Below is what I see in the log you shared:

> [-] At least one NAT, Transparent, or L2Bridge Network exists 242ms
   Expected {0} to be greater than {0}
   206:       $totalnets | Should BeGreaterThan 0
   at <ScriptBlock>, C:\Users\Gary\Downloads\Debug-ContainerHost.ps1: line 206
 [-] NAT Network's vSwitch is internal 233ms
   Expected: {Internal}
   But was:  {}
   211:       $switchType | Should Be "Internal"
   at <ScriptBlock>, C:\Users\Gary\Downloads\Debug-ContainerHost.ps1: line 211
 [+] A Windows NAT is configured if a Docker NAT network exists 1.92s
 [-] Specified Network Gateway IP for NAT network is assigned to Host vNIC 261ms
   Expected: value to not be empty
   225:       $natGatewayIP | Should Not BeNullOrEmpty
   at <ScriptBlock>, C:\Users\Gary\Downloads\Debug-ContainerHost.ps1: line 225
 [-] NAT Network's internal prefix does not overlap with external IP' 137ms
   Expected {0} to be greater than {0}
   252:         $hostips.Count | Should BeGreaterThan 0
   at <ScriptBlock>, C:\Users\Gary\Downloads\Debug-ContainerHost.ps1: line 252

>

**Comment by whitecolor** [comment]
With autostart disabled and DNS fixed still started with 3rd try. It took about 6-7 minuts. Please analyze the log:

https://gist.github.com/whitecolor/8fd2100df1c77de2dd4f04e849303c54

**Comment by awidjaja** [comment]
I encountered the same issue: 
https://github.com/docker/for-win/issues/1119

please help.

**Comment by ctmcisco** [comment]
For anyone following this ticket:

Try the following:

1. Switch or stay on Windows Containers.
2. Disable the "Start when Windows starts" setting.


![image](https://user-images.githubusercontent.com/14852041/37053107-e9a96bd8-2140-11e8-9bdf-b264980b6127.png)

3. Exit Docker application
4. restart docker services via PowerShell

get-service *docker* | Restart-Service -Force -Verbose

5. Launch Docker , Run as Admin
6. Swtich to Linux Containers.

TEST:

Reboot Windows 10
Launch Docker 
Does it work?

You can also parse the docker log in PowerShell for troubleshooting:

cat C:\Users\USERPROFILE\AppData\Local\Docker\log.txt -tail 10 -wait
