### ISSUE TITLE
docker error

### ISSUE THREAD

**Issue by Salexber** [docker/for-win#9020]
- [+] I have tried with the latest version of my channel (Stable or Edge)
  - [+] I have uploaded Diagnostics
  - Diagnostics ID:56FCD3CB-A9A0-411F-8AA6-48E0E76790F9/20201013180340

### Information

  - Windows Version: 10
  - Docker Desktop Version: 2.4.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...
System.NullReferenceException:
Ссылка на объект не указывает на экземпляр объекта.
   в Docker.Core.Cli.CliOptionsLoader.Get() в C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.Core\cli\CliOptionsLoader.cs:строка 33
   в Docker.Program.Run(IReadOnlyCollection`1 args) в C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Program.cs:строка 327

**Comment by CyberAP** [comment]
Updating to the latest version of Docker froze my system so I had to hard reboot. After reboot Docker failed to load and I uninstalled it. With a new install I get exactly the same error. I tried resetting setting to factory defaults and that didn't help.
