### ISSUE TITLE
Docker timed out waiting for the lifecycle-server to start

### ISSUE THREAD

**Issue by Shimogawa** [docker/for-win#9024]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F03BAD7D-12A6-49F2-95E1-1B37AC6FF0E3/20201014020022

### Expected behavior

Docker starts normally.

### Actual behavior

```
System.TimeoutException:
Timed out waiting for the lifecycle-server to start.
This may be the result of a slow environment or there may be a real problem.
```

### Information

  - Windows Version: Windows 10 Enterprise Version 1809 Build 17763
  - Docker Desktop Version: 2.4.0.0 (48506)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

I have also set the `lifecycleTimeoutSeconds` in `settings.json` to 30 minutes and it still crashes. I don't think it's just because my computer is slow. I have an Intel i5-8350U CPU and 16 GB memory.

**Comment by Shimogawa** [comment]
Solved by installing docker desktop version 2.2.0.5 stable.

**Comment by anandps** [comment]
@Shimogawa when did you upgrade to new version? 2.4.0.0 got released in 2020-09-30
https://docs.docker.com/docker-for-windows/release-notes/#docker-desktop-community-2400

For me, i upgraded to this version a couple of weeks back & suddenly got this problem when i rebooted my system yesterday. I dint remember giving consent to upgrade anything in docker desktop yesterday.

Following options din't work out for me:
1. Re-installing Docker Desktop 2.4.0.0 
2. Re-installing Hyper-V 
3. Re-installing Network card -> hyper-v virtual ethernet adapter 
4. Downgrading to 2.3.0.5 & 2.3.0.4

So i had to downgrade to next immediate version 2.2.0.5 to bring up the docker.

Its co-incident that I too happen to have a same windows version & build
Windows Version: Windows 10 Enterprise Version 1809 Build 17763
Maybe this windows version is affected?

**Comment by mchangor** [comment]
Hi, I have **Docker Desktop 2.4.0.0 on Windows 10 Enterprise version 1809 build 17763** and I started facing the same issue yesterday. Docker desktop tries to start and eventually timeouts.
I have tried 
1. Reinstalling Docker desktop
2. downgrading to 2.3.4.0
3. Reset to factory settings
None of these worked. I have uploaded crash reports too.

**Comment by Shimogawa** [comment]
> @Shimogawa when did you upgrade to new version? 2.4.0.0 got released in 2020-09-30
> https://docs.docker.com/docker-for-windows/release-notes/#docker-desktop-community-2400

@anandps I actually upgraded it yesterday. But I have the same problem with an older version (maybe 2.3) starting yesterday before my upgrade (because of this issue I tried to upgrade Docker).

**Comment by mchangor** [comment]
@anandps @Shimogawa I have not upgraded Windows or Docker desktop for at least a week. But I started having the issues yesterday. Thanks for mentioning version 2.2.0.5, it worked for me too.
