### ISSUE TITLE
Docker does not share a disk

### ISSUE THREAD

**Issue by vertisan** [docker/for-win#903]
### Expected behavior
Mount D:\ for Docker volumes access

### Actual behavior
Despite having a password-protected account, I'm prompted for a password and the sharing is unsuccessful.

### Information

  - Diagnostic ID: `08454F8A-6209-4758-8D74-D61F4F5B717/2017-07-07_08-48-27`
  - OS: `Windows 10 PRO, Docker 17.06.0-ce-win18 (12627)`

### Steps to reproduce the behavior

  1. Tick drive on `Shared Drives` in Docker settings or use command `docker run --rm d:/:data alpine ls /data`

**Comment by megusta420** [comment]
You may try to add new Docker user to Windows and add it to Admin group, it helped me (googled solution for same issue). Also you have to check Docker network created in your Windows network connections and remove service for printers, after that add it again. Sorry can not google concrete links now (driving) but you can google it yourself. At first start from adding new user (this have to resolve your issue).

**Comment by Dargmuesli** [comment]
Try the newest Edge build. Version 17.06.1-ce-rc1-win20 (12818). The issue is fixed for me there.
