### ISSUE TITLE
I no longer can use the primary tool that makes Windows useful... WSL is broken

### ISSUE THREAD

**Issue by fmotta** [docker/for-win#9043]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
WSL installed from MS Store to be undamaged
### Actual behavior
WSL installed frmo MS Store wont run. Hangs
### Information

  - Windows Version:
Win 10 (current patch)
  - Docker Desktop Version:
Current Windows version just installed)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
No native on Xeon

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
Sorry, but if you are having trouble installing WSL 2, you need to go to Microsoft not us.

**Comment by fmotta** [comment]
I am sorry...
A working program stopped working because I installed yours and the problem is the damaged program?

Would you fault a dog when you kick it too?

**Comment by fmotta** [comment]
How do I reopen this case as all I got was assertion of blame of the victim?

**Comment by stephen-turner** [comment]
Sorry, I misunderstood your description. You didn't say that installing Docker broke WSL 2, so I thought that you just couldn't install WSL 2.

I will reopen the ticket. To investigate it, we need: (1) reproduction steps, (2) the exact symptoms that you saw (e.g. the exact error message) and a (3) diagnostics ID.

**Comment by fmotta** [comment]
As in the original post which was clear on the fact that WSL worked and the did not work after installing Docker for Windows *also* states... to reproduce one need:

1) Install WSL from Microsoft store and get it **useful**
2) Install Docker for windows and make it **useless**
