### ISSUE TITLE
Docker Desktop Community 2.3.7.0 download link is invalid

### ISSUE THREAD

**Issue by MasaoBlue** [docker/for-win#9053]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Click the Download link under Docker Desktop Community 2.3.7.0 to download the installer
https://docs.docker.com/docker-for-windows/edge-release-notes/#docker-desktop-community-2370

### Actual behavior
I'm using a Chrome browser.
When I click the link, the page changes and the following error is displayed(partially masked):

```
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
  <Key>win/edge/48572/Docker Desktop Installer.exe</Key>
  <RequestId>3C87EEXXXXXXXXXX</RequestId>
  <HostId>oo14RyNYBQz1kwLSTg1MegerJjkPM4eFL96I9WVHZhwS8yXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX</HostId>
</Error>
```

**Comment by stephen-turner** [comment]
Hmmm, you're right, the build number should be 48173, I don't know how that happened. I'll fix it. But I'm interested to learn why you want to download an old version not the latest version.

**Comment by MasaoBlue** [comment]
@stephen-turner 
Thank you for your support!
I am developing on a Docker container using VSCode, and when I start the node.js process, I have a problem that the CPU becomes about 100%.
After reading the #6947 , I thought that changing the version of Docker for Windows might solve the problem, so I wanted to try it.
