### ISSUE TITLE
docker-machine - "remote error: tls: bad certificate" after 4 minutes and 30 seconds of system idle

### ISSUE THREAD

**Issue by kukjevov** [docker/for-win#906]
### Expected behavior
new machine created with docker-machine should work indefinitely, not only 4 minutes and 30 seconds.

### Actual behavior
Currently when i create new docker machine using `docker-machine create -d hyperv --hyperv-virtual-switch "DockerVMSwitch" vm` it creates fully working machine that can be connected and working but only for 4 minutes and 30 seconds. After this time i got error anytime i try to communicate with this machine 

>Unable to query docker version: Get https://192.168.1.156:2376/v1.15/version: remote error: tls: bad certificate

`docker-machine ls` after creating machine returns 
>NAME   ACTIVE   DRIVER   STATE     URL                        SWARM   DOCKER        ERRORS
>vm     -        hyperv   Running   tcp://192.168.1.156:2376           v17.06.0-ce

after 4 minutes and 30 seconds it returns
>NAME   ACTIVE   DRIVER   STATE     URL                        SWARM   DOCKER    ERRORS
>vm     -        hyperv   Running   tcp://192.168.1.156:2376           Unknown   Unable to query docker version: Get https://192.168.1.156:2376/v1.15/version: remote error: tls: bad certificate

I reinstalled windows 10 with latest image downloaded from Microsoft also downloaded latest stable Docker for Windows. 

Before reinstallation it was working without any problem, now it is not working longer than 4 min 30 sec, if i restart machine it starts using `docker-machine restart vm` it starts working again for some time. 

System was idle i did not do anything except spamming `docker-machine ls` because i wanted to know when it stops working. 

This makes docker-machine useless. 

I wanted to run docker-machine because i need to access Docker API from docker container. Using default docker machine can be accessed only using tcp://localhost:2375 but i cant access it from inside container. Is it possible to use default api using non localhost address? 

Thank you for your help

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu. 839B53E4-479B-4478-AF55-FD3F5FF26ED7/2017-07-09_17-23-24
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. Install latest Windows10 Version 1703 (Creators Update)
  2. Install Docker For Windows, latest version
  3. run `docker-machine create -d hyperv vm`
  4. wait 5 minutes
  5. run `docker-machine ls`

**Comment by jasonbivins** [comment]
Hi @kukjevov   What type of environment are you running Windows in - a VM, bare metal?
Can you create VM's using Hyper-V manager,

You mention that communication drops after a few minutes of being idle ?  Can you setup a constant ping to the VM created by docker-machine to see if it starts dropping packets at that point as well?

**Comment by kukjevov** [comment]
I can, what exactly do you want to ping? I mean what adress? When i was trying it i was calling `docker-machine ls`  every 5 seconds after start of machine until i got this error. I started timer right away and stoped it when i first got error.

**Comment by jasonbivins** [comment]
@kukjevov   Please ping the VM or the host from inside the VM - we're really just trying to see if there are a few dropped packets and it drops the connection, or if there is a complete disconnect

**Comment by kukjevov** [comment]
Well it decided to not cooperate with me this time :D. I had problem to make it going for 3 days and now when i want to test it and reproduce bug for you it is working. I will give it a try tomorrow. 

I started new machine and let it ping going for 10 minutes. Then i stopped ping and it is 20 minutes later and it is still working. I will let you know tomorrow.

Thanks for your time anyway :).

**Comment by kukjevov** [comment]
Hmm interesting thing, since i have created docker machine with this command `docker-machine create -d hyperv --hyperv-virtual-switch "DockerVMSwitch" --hyperv-cpu-count 2 --hyperv-memory 2000 --engine-env DOCKER_TLS=no vm` and disabled TLS and created second machine with TLS enabled it is working. Cant explain. It is very weird i hope i will be able to simulate problem again. Because it was quite annoying.

Thank you for now.

**Comment by jasonbivins** [comment]
Hi @kukjevov   Linking it to the DockerVMSwitch is most likely helping out in this case, but the TLS issue is puzzling. Please let me know how it goes

**Comment by kukjevov** [comment]
I am closing this since i had not this problem again for a while, if it happens i will create a new issue.

Thank you
