### ISSUE TITLE
docker with wsl2 backend only works inside wsl, not in cmd or powershell

### ISSUE THREAD

**Issue by OmegaRogue** [docker/for-win#9063]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3BEB17A9-65FB-494F-821E-F78241CF2C57/20201015103422

### Expected behavior
`docker ps` runs without errors in wsl2 ubuntu, powershell and cmd

### Actual behavior
`docker ps` runs without errors in wsl2 ubuntu, but in powershell and cmd it returns the error
```
unable to resolve docker endpoint: open C:\Users\OmegaRogue\.docker\machine\machines\default\ca.pem: The system cannot find the path specified.
```

### Information

  - Windows Version: 20H2 
  - OS build: 19042.572
  - Experience: Windows Feature Experience Pack 120.2212.31.0

  - Docker Desktop Version: 2.4.1.0 (48583) edge
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. open cmd
  2. run `docker ps`

**Comment by stephen-turner** [comment]
@simonferquel Any ideas about this one?

**Comment by OmegaRogue** [comment]
I've tried solutions from other similar issues, but nothing worked

**Comment by simonferquel** [comment]
It seems that you have your environment variables poluted by Docker Machine. Can you try to unset all `DOCKER_*` env variables ?

**Comment by OmegaRogue** [comment]
it works after removing the env variables in cmd, it doesnt work if i do it from the ui

```batch
SET DOCKER_CERT_PATH=
SET DOCKER_HOST=
SET DOCKER_MACHINE_NAME=
SET DOCKER_TLS_VERIFY=
```

**Comment by OmegaRogue** [comment]
but that is only for the current commandline session, how do I permanently unset it?

**Comment by simonferquel** [comment]
They are probably set in your machine-wide or user-wide env variable store. 
You can find (and edit) them in Windows System properties (just search for "Env" in Windows search, you should be able to access those settings).
