### ISSUE TITLE
Unable to Run Docker on 8 different VMs

### ISSUE THREAD

**Issue by TenZeroZero** [docker/for-win#9089]
I have been trying for the past 2 weeks to get Docker running on a Window VM and to my EXTREMELY DISAPPOINTMENT it hasn't worked . . . . POINTLESS USE OF MY TIME

- I have created a whooping 8 Win10 VMs all ended to be destroyed due to corruption when trying to fix this rubbish application
- Those VMs were located on different clouds, even on a Laptop  
- The errors are the same that every single person has logged in these pages since 2018, so you have plenty to go through
- Yes I've also followed all the pointless suggestions posted in each thread since 2018: None worked
- I managed only once to get it worked on a Windows 10 Home (did just for fun) . . . but Linux containers did not got installed and Windows containers often refused to start
- When restarting a working VM , Docker re-displayed errors and no effort worked to fix it has worked

ADDITIONAL NOTE: Linux Docked works in the same VM cluster so it isn't the Hyper-V  as some suggested due to "BIOS" issues

Information

Windows Version: just used latest iso from Windows aka latest Win10 Pro image
Docker Desktop Version: latest from your website
Are you running inside a virtualized Windows e.g. on a cloud server or on a  Win VM: tried both
Steps to reproduce: errors cannot be reproduced because every time the error had different output but you have PLENTY of screenshots posted in the past 36 months from users, those did not change . . . but I will indulge you with some . . .

NOTE 1: I will not suggest both my organisation and anyone to use this pointless app until it is fixed . . . you'll only waste your time to get it working

NOTE 2: No, I will not spin up another VM to get the logs . . . annoyed enough by this nonsense. Yes. I am very upset!

Will be there a fix?
...
...
![image](https://user-images.githubusercontent.com/56144220/96273029-29458180-0fcf-11eb-959f-b744b46ff10a.png)

![image](https://user-images.githubusercontent.com/56144220/96273114-44b08c80-0fcf-11eb-8015-2065d7c545ed.png)

![image](https://user-images.githubusercontent.com/56144220/96273164-51cd7b80-0fcf-11eb-94be-1f3097e7e604.png)

**Comment by stephen-turner** [comment]
Sorry, but Docker Desktop is not supported inside a VM. This is documented in the "What to know before you install" section of the docs: https://docs.docker.com/docker-for-windows/install/#what-to-know-before-you-install . We too would love to make it work but unfortunately it's out of our control: the issue is whether Hyper-V will run inside the VM, which depends on the outer hypervisor.

**Comment by TenZeroZero** [comment]
So if Docker for Win does work only on my PHYSICAL laptop fine . . . . mmmm I guess the 200 plus developers connected to VMs will not be "that" happy with the my reply . . . well it is what it is!

So, if that is the case I should also suggest to make it CLEAR on the download page that it works only on a PHYSICAL MACHINE not virtual.

Thank you for your reply . . . Please close the ticket, I would do the same on my "system".
