### ISSUE TITLE
Docker won't start on Windows 10 - Provider is not capable of the attempted operation

### ISSUE THREAD

**Issue by cbeech1980** [docker/for-win#91]
All,

Fresh install of Docker for Windows on Windows 10 and am having problems starting Docker. Have submitted crash report > CF8EB4B4-0807-4953-85BD-E3C31FBFD4E6/2016-09-18_14-32-51.

The exception thrown is below;

> The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The operation on computer 'CHRISBEECH' failed: Provider is not capable of the attempted operation 
>    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
>    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
>    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
>    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
>    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
>    at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
>    at Docker.Core.PowerShell.Output(String script)
>    at Docker.Backend.Processes.DataKit.<Start>b__3_0()
>    at Docker.Backend.Processes.ExternalProcess.StartProcess(String fileName, Func`1 arguments)
>    at Docker.Backend.Processes.ExternalProcess.Start(Func`1 arguments)
>    at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
>    at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
>    at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
>    at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

I have attached the log file from docker also.

Any help would be greatly appreciated as I sacrificed by working docker-toolbox configuration to move to the new Windows version!

Thanks,

Chris

[log.txt](https://github.com/docker/for-win/files/478891/log.txt)

**Comment by rneugeba** [comment]
@cbeech1980 it looks like you might still have VMware running on your system and I'm pretty sure vmware fusion and Hyper-v don't play well together

**Comment by cbeech1980** [comment]
I have VMware Workstation 10 installed on my machine - although it's not running. Are you recommending I need to uninstall this application in order to get Docker for Windows working?

**Comment by rneugeba** [comment]
I honestly don't know, but none of the Hyper-V commands in our debug log
seem to work, although the Hyper-v feature is installed, but does not seem
to work.

There are various VMware related processes running on your machine and
Hyper-V does not play nice with other virtualisation applications like
VMware or VirtualBox (or the other way round)

**Comment by rneugeba** [comment]
if you could try un-installing VMware and try installing Docker again, that would be great. Otherwise, I'm inclined to close this issue as VMware and Hyper-V can't be used together. There seem to be various guides on the web that show how one can switch between them, but, I don't know how reliable they are.

**Comment by dgageot** [comment]
Closing the issue since VMware and Hyper-V can't be used together and there's nothing we can do about it.
