### ISSUE TITLE
how to install ?

### ISSUE THREAD

**Issue by aksbaran** [docker/for-win#9106]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by aksbaran** [comment]
DCBC09D2-7ABE-4BA4-BE6E-059A9CD53D8C/20201017183841

**Comment by aadithya96** [comment]
Not sure if this is the right place to ask for installation help seeing that you don't have any errors during installation.
Have a loot at https://docs.docker.com/docker-for-windows/install/
