### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by kunalchamoli** [docker/for-win#9108]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by kunalchamoli** [comment]
BCE2852E-5551-42A0-B0F5-641133BAB8DA/20201017215014

**Comment by aadithya96** [comment]
Not sure if this is the right place to ask for installation help seeing that you don't have any errors during installation and also your issue does not have any useful info whatsoever

Have a loot at https://docs.docker.com/docker-for-windows/install/
