### ISSUE TITLE
Project folder deleted after restart

### ISSUE THREAD

**Issue by favianca** [docker/for-win#9116]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
04CD0DFA-90C6-40C6-A760-F27AA5D07AB3/20201018144157
### Actual behavior
Docker clears my project folder on restart. 
![image](https://user-images.githubusercontent.com/50097936/96371497-2774ed00-118c-11eb-85a9-a32da909980b.png)
In the /apps/commercial folder I was running a project on docker before my computer restarted and the folder is now empty. This has happened twice already.
### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. Run project's docker
  2. Restart computer/stop the container

**Comment by stephen-turner** [comment]
@favianca Thanks for the report, we'll take a look. Assigning to @simonferquel.

**Comment by simonferquel** [comment]
It is not docker desktop. You seem to create your projects within `/mnt/wsl`. This is backed by a tmpfs filesystem (not a persistent one), primarly used to echange things from one WSL distro to the other.

You should put your source code in your distro file system (I usually put my source code in `/home/simon/projects/<project-name>`).
