### ISSUE TITLE
Docker complains about virtualization and network on VMWare laptop

### ISSUE THREAD

**Issue by TimoRiikonen** [docker/for-win#912]
### Expected behavior
Docker runs helloworld application.

### Error message on DOS prompt with Admin rights
C:\Windows\system32>docker run helloworld
docker: error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.30/containers/create: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

### Error message when starting Docker UI with Admin rights
Hardware assisted virtualization and data execution protection must be enabled in the BIOS. See https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization-must-be-enabled

### Error messages in Event Viewer
- 'MobyLinuxVM' failed to start. (Virtual machine ID ...)
- Internal miniport create failed, name = '...', friendly name = 'vEthernet (DummyDesperatePoitras)', MAC = 'DYNAMIC': One or more arguments are invalid (0x80070057).
- Failed while adding virtual Ethernet switch connections.
- The virtualization infrastructure driver (VID) is not running.
- Virtual machine 'MobyLinuxVM' could not be started because the hypervisor is not running (Virtual machine ID ...). The following actions may help you resolve the problem: 1) Verify that the processor of the physical computer has a supported version of hardware-assisted virtualization. 2) Verify that hardware-assisted virtualization and hardware-assisted data execution protection are enabled in the BIOS of the physical computer.  (If you edit the BIOS to enable either setting, you must turn off the power to the physical computer and then turn it back on.  Resetting the physical computer is not sufficient.) 3) If you have made changes to the Boot Configuration Data store, review these changes to ensure that the hypervisor is configured to launch automatically. 
- Miniport Hyper-V Virtual Switch Extension Adapter, {...}, had event 76
- The Docker for Windows Service service terminated unexpectedly.  It has done this 3 time(s).

### Docker debug info
- The server does not support multichannel. Server name: \....11. Guidance: The client attempted to use SMB Multichannel, but an administrator has disabled multichannel support on the server. This may also be a non-Microsoft file server that does not support multichannel or has multichannel disabled. You can enable SMB Multichannel on the server using this Windows PowerShell cmdlet: Set-SmbServerConfiguration -EnableMultiChannel:$true. This event does not apply to the multichannel settings of SMB client, which are controlled by the Set-SmbClientConfiguration Windows PowerShell cmdlet. Enabling or disabling client multichannel support does not affect server multichannel support.     
NOTE: This might be from somewhere else than Docker.
- Switch port created, switch name = '...', switch friendly name = 'DockerNAT', port name = '...', port friendly name='DockerNAT'.
- Ethernet switch port connected (switch name = '...', port name = '...', adapter GUID = '{...}').
- Vmsmp service is in registry, but hns service is not in there.
- Get-VMSwitch : Hyper-V was unable to find a virtual switch with name "nat".
- Get-VMSwitch command returns with no info on manual execution.
- [Fail] Windows version should be greater or equal than 14393
- [Fail] nat switch type is
- WinNat.txt file looks fine to me

### Information
- Bare metal
- Windows 10 Enterprise, 64 bits, probably up-to-date. 
- Hyper-V-VMMS version number 10.0.10586.0

### Steps to reproduce the behavior
1. Install VMWare
2. Reboot
3. Run VMWare (no issues)
4. Stop four VMWare services and disable automated startup (in case this would help)
5. Install Docker Stable version.
6. Try running helloworld - gives the same error.
7. Check from Task Manager --> Performance --> CPU --> Virtualization. Answer = Enabled.
8. Install Docker Edge version.
9. Check version. Same as with Stable version?
C:\Windows\system32>docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64
10. Shut down and start Docker for Windows Service to know if it is stable or not. It is not: crashes on the way down. No errors on coming up and appears to be running.
11. Run all commands in https://docs.microsoft.com/fi-fi/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v . It seemed to me that the environment was fine even before these commands, but at least no errors in there.
12. Reboot
13. Try running helloworld again. Still not working.
14. C:\Windows\system32>docker network ls
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.30/networks: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
15. Network is working fine, so I expect the daemon is not running.

### Next - not done yet
- Checking BIOS. Looks like the password has changed and I need to ask for the new password.

**Comment by jasonbivins** [comment]
Hi @TimoRiikonen 
What type of environment are you running Windows on - VM, Bare metal?

Can you post a Diagnostic ID next time you see that error ?

**Comment by friism** [comment]
@TimoRiikonen Docker for Windows relies on Hyper-V which may or may not work nested inside VMWare, nor side-by-side with VMWare.

**Comment by TimoRiikonen** [comment]
Environment: Bare metal
Diagnostic ID: Where do I get one? There is none in Docker helloworld or in Docker UI.
Some debug info added. Strangest complaint was about my Windows version being too old.
