### ISSUE TITLE
Unstable after 2.3 -> 2.4 upgrade

### ISSUE THREAD

**Issue by rob-dotmatics** [docker/for-win#9122]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 29BA6326-E43A-48D1-9AD1-CDD50D4A67E0/20201019132222 and 29BA6326-E43A-48D1-9AD1-CDD50D4A67E0/20201019174501

### Expected behavior
Docker Hyper-V backend starts
Container starts

### Actual behavior
Backend either appears to start (but is unresponsive)
-or- fails to start with timeout error
-or- starts successfully, but terminates unexpectedly after a few minutes

### Information

  - Windows Version: 10 (1909)
  - Docker Desktop Version: 2.4.0.0 and 2.4.2.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No
Containers were working fine before upgrade to 2.4.

### Steps to reproduce the behavior
Start Docker Desktop.
Backend may or not start.
If it does start, run 'docker image list' or 'docker container list'
These hangs for a while and then show i/o timeout error.

**Comment by rob-dotmatics** [comment]
I tried to add another Diagnostic Id following a time when I had a container running but it (and the whole docker backend) suddenly stopped - but the Diagnostics tool never completed.

**Comment by rob-dotmatics** [comment]
I should mention that I am running Trend Micro (as per https://github.com/docker/for-win/issues/8902) and am unable to disable it due to corporate policy. Docker Desktop 2.3.0.5 worked fine, but I am unable to use 2.4.0.0 or 2.4.2.0-edge.

**Comment by csk-bsi** [comment]
I encounter the same issue, version 2.3.05 works perfectly, version => 2.4.0 crashes.
Simmiliar setup with Trend Micro Antivirus and Windows 10 WLS 2.  
Any idea how to debug so we would be able to open a Trend Micro issue?
