### ISSUE TITLE
Failed to deploy distro docker-desktop

### ISSUE THREAD

**Issue by Brijwizards** [docker/for-win#9131]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version: Windows 10 Enterprise
  - Docker Desktop Version: 2.4.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Downloaded the docker from https://docs.docker.com/docker-for-windows/install/
  2. Installed it, 
 3.  Restarted the machine. Docker tries to start but failed. See attachment.
![DockerError](https://user-images.githubusercontent.com/35049436/96531021-94948b00-123d-11eb-9157-3efcaac904c6.PNG)

**Comment by Brijwizards** [comment]
[DockerError.txt](https://github.com/docker/for-win/files/5405173/DockerError.txt)

Attaching the log file

**Comment by ashokgop** [comment]
I have reported the same issue under #9153
