### ISSUE TITLE
0833B0FB-2E99-4C86-A0BB-9433AB722923/20201020020458

### ISSUE THREAD

**Issue by asevans48** [docker/for-win#9136]
Issue restarting docker. Unknown Issue.

Attempts to solve:

- Purge data
- Reset to factory defaults

Using:

- WSL [required]

Error:

WSL distro stopped while waiting for Lifecycle server.
  >Stdout:

  >Stderr:
2020/10/20 02:04:04 resolving /mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-wsl-cli.iso...
2020/10/20 02:04:04 already in cache!
2020/10/20 02:04:04 resolving /mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-for-wsl.iso...
2020/10/20 02:04:04 copying...
Error: rootfs mountIso baseImage: open /mnt/host/wsl/docker-desktop-data/isocache/49d4cfcc3952f7d8a77ca1f08bb34c579185893cf5cc3a900cf575c4591dde94.iso: input/output error
2020/10/20 02:04:04 open /mnt/host/wsl/docker-desktop-data/isocache/49d4cfcc3952f7d8a77ca1f08bb34c579185893cf5cc3a900cf575c4591dde94.iso: input/output error
rootfs mountIso baseImage
main.setupRootFS
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:306
main.doRun
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:231
main.run.func1
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:85
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:838
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:943
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).Execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:883
main.main
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:27
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1373

**Comment by greggameplayer** [comment]
I have the same problem 😑
