### ISSUE TITLE
Please help - new to this - VSCode runs, Docker Installed, Docker Desktop says -> you must be in the "docker-users" group

### ISSUE THREAD

**Issue by Edward-Staley** [docker/for-win#9137]
Please help - I am new to this and am messing things up

I ask someone to please help me get straightened out and show me how I should have done things 
Docker - Docker Desktop
Java
Python
and whatever else I should have
correctly installed and useable under VSCode

I also want to install WSL Linux on my Windows 10 laptop 
I have installed Remote WSL but am lost

Under VSCode I installed Docker and Docker Desktop however when I try to start Desktop is says
"You are not allowed to use docker. You must be in the "docker-users" group

I would appreciate someone giving me a helping hand and either calling me and talking me throught
my problems so I can learn how to do things properly
-or- doing a remote and slowly finding and fixing my problems and helping me understand what 
I have done wrong - please
my direct cell is 678.444.9896
Ed Staley

This is the log.txt from my failing Docker Desktop
Version: 2.4.0.0 (48506)
Channel: stable
Sha1: b18c8c862baf6c395898f15dd01857d96ddca564
Started on: 2020/10/20 00:00:47.010
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Home
Edition: Core
Id: 2004
Build: 19041
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\Users\MTMIBM\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[00:00:47.090][GUI               ][Info   ] Starting...
[00:00:47.105][ComponentVersions ][Info   ] Edition community
[00:00:47.108][ComponentVersions ][Info   ] Edition community
[00:00:47.320][GUI               ][Error  ] Access denied to Docker. Exiting.

Thanks - I feel stuppppppid, for asking for a helping hand please

**Comment by StefanScherer** [comment]
Hi,

It seems that your Windows user account isn‘t in the local group `docker-users`. 
After installation of Docker Desktop you need to logout to make this happen. 

https://docs.docker.com/docker-for-windows/install/

There also is a situation

> 5. If your admin account is different to your user account, you must add the user to the docker-users group. Run Computer Management as an administrator and navigate to  Local Users and Groups > Groups > docker-users. Right-click to add the user to the group. Log out and log back in for the changes to take effect.

**Comment by Edward-Staley** [comment]
Thanks for replying
The 1st thing I tried to do was to run Computer Management, but there is NO Local Users and I could not figure iut what I had to do
Because all this is new to me, I admit I am confused 

Sent from Yahoo Mail on Android 
 
  On Tue, Oct 20, 2020 at 1:13 AM, Stefan Scherer<notifications@github.com> wrote:   


Hi,

It seems that your Windows user account isn‘t in the local group docker-users.
After installation of Docker Desktop you need to logout to make this happen.

https://docs.docker.com/docker-for-windows/install/

There also is a situation

   
   - If your admin account is different to your user account, you must add the user to the docker-users group. Run Computer Management as an administrator and navigate to Local Users and Groups > Groups > docker-users. Right-click to add the user to the group. Log out and log back in for the changes to take effect.

**Comment by Edward-Staley** [comment]
I figured out that I not only had to enable Hyper-V but also get into BIOS and enable virtualizationAmazing, I managed to get that done and created a sign under Docket - I hope I am doing this correctly
Thanks
now that it seems to be working - also WSL appears to be working
At this point - I am tired and confused so I have no idea if all is ok or what to do next
thanks for your kind reply I  would appreciate your helping me again to get started correctlyEd Staley678.444.9896

    On Tuesday, October 20, 2020, 01:20:09 AM EDT, edward staley <edwstaley@yahoo.com> wrote:  
 
 Thanks for replying
The 1st thing I tried to do was to run Computer Management, but there is NO Local Users and I could not figure iut what I had to do
Because all this is new to me, I admit I am confused 

Sent from Yahoo Mail on Android 
 
  On Tue, Oct 20, 2020 at 1:13 AM, Stefan Scherer<notifications@github.com> wrote:   


Hi,

It seems that your Windows user account isn‘t in the local group docker-users.
After installation of Docker Desktop you need to logout to make this happen.

https://docs.docker.com/docker-for-windows/install/

There also is a situation

   
   - If your admin account is different to your user account, you must add the user to the docker-users group. Run Computer Management as an administrator and navigate to Local Users and Groups > Groups > docker-users. Right-click to add the user to the group. Log out and log back in for the changes to take effect.

**Comment by Almenon** [comment]
I logged out and I still got this error. Luckily https://github.com/docker/for-win/issues/868 had a workaround.
