### ISSUE TITLE
Unable to create a shared drive "D"

### ISSUE THREAD

**Issue by terrygarbie** [docker/for-win#914]
### Expected behavior
Shared drive "D" should be created after,
(1) Go to Setting -> Shared Drives, select Drive "D",
(2) Press "Apply" button

### Actual behavior
Shared drive "D" cannot be created after,
(1) Go to Setting -> Shared Drives, select Drive "D",
(2) Press "Apply" button
(3) Pop-up for password
(4) Nothing happens

### Information
A diagnostic was uploaded with id: AE84C9EF-CCE6-47D8-B562-DB96E5E90A52/2017-07-12_13-43-29
OS information: Windows 10 Pro, version 1703, OS build 15063.483

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

**Comment by YangAidi** [comment]
How did you deal with this issue?

**Comment by terrycmchan** [comment]
I just run Docker as administrator.
