### ISSUE TITLE
volume mount: file invisible or permission problem

### ISSUE THREAD

**Issue by jdevoo** [docker/for-win#915]
### Expected behavior

I am launching 2 containers to prepare a small peer-to-peer environment.
For discovery purposes, I need to share one config file with both once their access details are collected. I prepare that file from two running containers with a couple of exec commands. Once assembled, I copy that file at Windows 10 host level to the separate mounted peer directories.

I should be able to run 2 containers with the config file. I can successfully (ie IPC works) run each container using

`docker run -d --rm -v .:/root --name peer2 ethereum/client-go:alpine --nodiscover --networkid 11 --rpc --identity peer2`

### Actual behaviour (edited)

When I then run each container with the above relative path volume mount, the the container does not see the file I copied over. When I use a full path specification, it cannot create the IPC socket under /root/.ethereum (a subdirectory) but can see the config file from within the container.

`docker run -d --rm -v /c/Users/username/playground/p2p/shared/peer1:/root --name peer1 ethereum/client-go:alpine --nodiscover --networkid 11 --rpc --identity peer1`

My understanding was I should use full path specifications to be able to share files both ways between host and container. That shared folder would have also enough permissions to e.g. use IPC.

### Information

  - Windows 10.0.15063
  - Docker 17.06.0-ce
  - C drive shared
  - I can see folder content mounted normally unlike mentioned in other issues

Any ideas? Pointers welcome. TIA.

**Comment by friism** [comment]
The bind-mounted volumes are implemented with SMB/CIFS so if you're trying to use Unix Domain Sockets or other Unix-specific filesystem features over those volumes it's unlikely to work.

Can you use a named volume instead? https://docs.docker.com/engine/tutorials/dockervolumes/#data-volumes

**Comment by jdevoo** [comment]
When I start the two containers using a relative path, the IPC file is created and the daemons work. Communication is between peers/containers only. Only when I use an absolute path to the same location, I get the following error

`Fatal: Error starting protocol stack: listen unix /root/.ethereum/geth.ipc: bind: operation not permitted`
