### ISSUE TITLE
[Edge Channel] Dashboard window is not resizeable and too large

### ISSUE THREAD

**Issue by speller** [docker/for-win#9157]
v 2.4.2.0 (48975)

The dashboard window is too large and cannot be resized down, only slightly up to the full screen or maximized. On the screenshot below, that's the minimum size I can set but it fills almost the whole desktop:

![image](https://user-images.githubusercontent.com/1829515/96652154-4c768500-1371-11eb-84cf-cfdb278ac75b.png)

I'm running Windows 10 x64 on a 4K screen.

**Comment by gwideman** [comment]
I agree with speller. The dashboard window is painfully ridiculously large, and can't be sized smaller, so far as I can see. If it's not bad enough that it uses a huge amount of pointless whitespace between and around items, it then has huge unoccupied space beyond that.  For the info it shows, it could be about 400 x 200 or smaller, but instead its smallest size is something like 1280 x 720.  As a panel that you might want open to monitor what Docker is doing, it's pretty much useless unless you have an entire separate monitor to put it on.
