### ISSUE TITLE
Unable to set the CPU and memory on Windows 10 Home with WSL 2

### ISSUE THREAD

**Issue by laurence-lin** [docker/for-win#9162]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
I'd just installed WSL 2 and Docker for Windows Stable on my Windows 10 Home. By the instructions, I learned that in order to set CPU and memories for the docker, I need windows Pro or Docker with WSL 2. However, since my docker run fine with `docker run hello-world` and` wsl -l -v` works fine for WSL 2

### Actual behavior
When I open the docker desktop I see that "Use the WSL 2 based engine" is selected by default, however in resources page I couldn't set the CPU and memory or any advanced settings.

### Information

  - Windows Version: 10
  - Docker Desktop Version: 19.03.13
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Windows 10 home

### Steps to reproduce the behavior

  1. Open the docker desktop
  2. Go to the settings, and Resources page

**Comment by stephen-turner** [comment]
This is expected because in the case of WSL 2 the CPU and memory are controlled by Windows not by us. The documentation explains how to set them: see https://docs.docker.com/docker-for-windows/wsl/
