### ISSUE TITLE
docker pull - unexpected EOF  - Docker with WSL 2 Engine

### ISSUE THREAD

**Issue by ANorwoodD** [docker/for-win#9164]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 33AF02BD-D9AB-4B84-9872-10C4742EB0E3/20201021095625

Similar to issue #6837 and #6192 (but I'm not based in Germany) - I switched this morning from Hyper-V backend to WSL 2, but I am unable to pull any images. We have our own repository which doesn't work, but running docker run hello-world also doesn't work.

Using the Hyper-V backend works without issue

### Actual behavior
`PS C:\Users\anorwood> docker run hello-world

Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/library/hello-world/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fhello-world%3Apull&service=registry.docker.io: unexpected EOF.

See 'docker run --help'.`

### Information

  - Windows Version: Version 2004 (Build 19041)
  - Docker Desktop Version: 2.4.0.0 (48506)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: N

### Steps to reproduce the behavior

  1. Enable WSL2 in Docker
  2. In Powershell, run 'docker run hello-world'

**Comment by phalix** [comment]
I have the same issue. On windows home, this makes docker unusable, since windows home does not support hyper-v

**Comment by phalix** [comment]
I have the same issue.
