### ISSUE TITLE
Cannot create container for service X: image with reference Y was found but does not match the specified OS platform: wanted: windows, actual: linux

### ISSUE THREAD

**Issue by cronventis** [docker/for-win#9166]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

I'm having a docker-compose file (v2.4) that I start with --compatibility up.
In it I have a mix of Windows and Linux Containers.
Each has specified the platform via: platform: linux/platform: windows. I'm running on Windows Containers.
After installing Docker Desktop Community 2.4.2.0, I suddenly get the error "Cannot create container for service X: image with reference Y was found but does not match the specified OS platform: wanted: windows, actual: linux"
After going back to Docker Desktop Community 2.4.1.0, everything is working normal.

**Comment by stephen-turner** [comment]
@cronventis Thanks for the report. I believe this is a bug in the new beta Engine, which we have included for the first time in 2.4.2.0. It seems very similar to moby/moby#41552, so let's take the discussion there.
