### ISSUE TITLE
How can I connect to container use Powershell rather than CMD?

### ISSUE THREAD

**Issue by GF-Huang** [docker/for-win#9167]
![image](https://user-images.githubusercontent.com/4510984/96720456-5df57680-13dd-11eb-91ba-9da841e265a4.png)

**Comment by ANorwoodD** [comment]
You can open a powershell window and type:

`docker exec -it InfluxDB_Old sh`

That assumes you're using sh rather than bash or otherwise. You can replace sh with the appropriate one.

**Comment by stephen-turner** [comment]
Of course once you're inside the container, it's a Linux shell not PowerShell or cmd, so I'm not sure how much difference it makes which Windows shell you use.
