### ISSUE TITLE
Docker failed

### ISSUE THREAD

**Issue by Tesold** [docker/for-win#9188]
- Diagnostics ID: 2798B491-45B7-469D-A8E0-1D281FF86452/20201022142451

### Information

  - Windows Version: 10
  - Docker Desktop Version: 2.4.2.0

System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\Администратор\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: B:070=> 

 stderr: 
   в Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) в C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:строка 146
   в Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__17.MoveNext() в C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:строка 169

**Comment by coolxxy** [comment]
In my case, the same problem looks like happened after windows installed update package KB4579311 and KB4578968.
