### ISSUE TITLE
Docker no longer on windows PATH variable after upgrade to Version 17.06.0-ce-win19 

### ISSUE THREAD

**Issue by renamed** [docker/for-win#919]
### Expected behavior
When I enter "docker stop MY_CONTAINER"  on Windows CMD docker should stop "MY_CONTAINER".

### Actual behavior

The message _'docker' is not recognized as an internal or external command, operable program or batch file_ is display.

### Information

  - That happens after updating to version 17.06.0-ce-win19 

### Steps to reproduce the behavior

  1. Update Docker to version 17.06.0-ce-win19 
  2. Start docker
  3. Open a CMD and write any _docker_ command

**Comment by renamed** [comment]
A diagnostic was uploaded with id: 18339EA4-EB3D-4AA4-B7B2-B5E840240AFF/2017-07-13_14-44-21

**Comment by renamed** [comment]
I noticed the PATH was right on the Windows environment variables so I just restarted my computer and it worked.

**Comment by cbeier** [comment]
Yes, a restart of windows solves the problem.

**Comment by mohdamir** [comment]
I have moved the docker bin path to last in PATH environment variable and this worked for me.

**Comment by joseph-kaainoa** [comment]
After updating to 17.09.1-ce-win42 (14687) on Win10 pro, I had the same "command not recognized" problem.  The docker path was listed first in the environment variable list (which it had not been previously), so I moved it down the list and it worked for me as well.

**Comment by mduqueoviedo** [comment]
Strangely, @joseph-kaainoa solution worked.

**Comment by toyg** [comment]
The solution of moving the path down the list works simply because it triggers re-evaluation of %PATH% across Windows when you click OK. You can set it back up as first and it will still work.

**Comment by MohammadHeydari** [comment]
mine doesn't work at all, when i type `docker --version` command in cmd it doesn't recognize it at all

**Comment by azstate** [comment]
same here. After restart suddenly docker commands stopped working. Working on Azure VM

**Comment by akshaybabloo** [comment]
You don't have to restart, just type in - `refreshenv` in CMD or PowerShell. It should work.

**Comment by dance2die** [comment]
@akshaybabloo `refreshenv` worked like a charm. Thanks Akshay 👍

**Comment by aa-dxp168** [comment]
refreshenv didn't work, until I restarted windows...

**Comment by FrikkinLazer** [comment]
I am pretty sure refreshenv only exists if you have chocholatey installed.
