### ISSUE TITLE
Docker desktop fail to start after Windows 10 Subsystem for Linux Update 4.19.128

### ISSUE THREAD

**Issue by diego2265** [docker/for-win#9198]
- [x] I have tried with the latest version of my channel (Stable)

  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 322D4C6D-38C2-4526-B9DF-3EA81BE9CA8C/20201023062603

### Expected behavior
Docker starts on latest Windows 10 Pro
### Actual behavior
Docker Starts but then stops
### Information

  - Windows Version: Windows 10 Pro Version 2004 (19401.572)
  - Docker Desktop Version: Stable 2.4.0.0 (48506)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Docker image on Win 10 Hyper-V

### Steps to reproduce the behavior

  1. Install docker
  2. Install Windows 10 Subsystem for Linux Update 4.19.128
  3. Reboot: docker fails to start: HttpOS Client: Exception:Cancellation token triggered before we finished reading from the stream.

**Comment by joamla96** [comment]
Hello, can confirm similar issue, also W10 Pro, just after an update.
Build 10.0.18363

Diagnostic ID: `54661F76-C4DF-4D1E-9E96-5F8B24A1B5A6/20201023082107`
