### ISSUE TITLE
Installed today's new version of Docker and now Powershell and bash do not see it.

### ISSUE THREAD

**Issue by RelativeRon** [docker/for-win#920]
### Expected behavior
Docker works in Powershell or Windows bash

### Actual behavior
Although the Docker icon appears in the task bar, and the Docker GUI windows say Docker is running, in Powershell and windows bash, entering "docker -v" gives the response: 
bash: docker: command not found
PS: docker : The term 'docker' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ docker -v
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (docker:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

### Information
Today I allowed the automatic update to Version 17.06.0-ce-win19 (12801)
Channel: stable
c98c1c2

Restarting docker does not help.

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
373FBC67-7F5E-45FD-BB37-ECDF30FFD5C6/2017-07-13_16-19-22

  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)
 Version 17.06.0-ce-win19 (12801)
Channel: stable
c98c1c2
Windows 10 Pro
### Steps to reproduce the behavior
  1. ...Start docker
  2. ...Try to use ps or bash on it.

**Comment by RelativeRon** [comment]
Well, I restarted my machine and now... docker works fine.
I'm relatively new to docker so maybe it is standard operating procedure to restart the computer after installing a docker upgrade.
Lesson learned.

**Comment by jasonbivins** [comment]
Hi @RelativeRon 
occasionally during my testing  i've seen Docker leave behind a ghost process after the upgrade. It was probably a conflicting Docker process that was cleared by the restart, although restarting the Docker service in the Windows GUI would have probably done the same thing.

I'll go ahead and close this, let me know if you have the problem again.

**Comment by Flyingmana** [comment]
had the same after a fresh install, needed one reboot to make the cmd available on powershell.
Maybe the restart step should be enforced always after install, and not only if hyper-v needs to get enabled. Should I open a new ticket for this, or is this similar enough to the here described problem?

**Comment by tostt** [comment]
I had same the same problem with a fresh install today (17.12.0-ce-win47). Rebooting did unlock the command.

**Comment by MohammadHeydari** [comment]
mine doesn't work at all, when i type `docker --version` command in cmd it doesn't recognize it at all

**Comment by IssacKramer** [comment]
fore me docker --version and other commands are working.
But, dockerd - the service/daemon is NOT recognizable : 
"dockerd --unregister-service" Not working!
Anyone?

**Comment by SA-khan** [comment]
> for me docker --version and other commands are working.
> But, dockerd - the service/daemon is NOT recognizable :
> "dockerd --unregister-service" Not working!
> Anyone?

Same issue with me :@

**Comment by andzejsw** [comment]
I just reopened powershell
