### ISSUE TITLE
Error while creating mount source path

### ISSUE THREAD

**Issue by 4nti-7rust** [docker/for-win#9204]
- [x] I have tried with the latest version of my channel (Stable or Edge)
 - [x] I have uploaded Diagnostics : I have probably some proxy issues... I can manual upload it if I find the way to do it.

### Expected behavior
Should be able to attach volume point to a folder on host

### Actual behavior
`docker: Error response from daemon: error while creating mount source path '/host_mnt/c/VirtPart/Drive.D': mkdir /host_mnt/c/VirtPart: operation not permitted.`

### Information
  - Is it reproducible?
Yes.

  - Is the problem new?
It seems similar to #5516, but as @stephen-turner pointed out, it had "file exists" instead of "operation not permitted".

  - Did the problem appear with an update?
I don't know, never tried it before.

  - A reproducible case if this is a bug, 
See Actual behavior.

  - Windows Version:
`10.0.1.17763`

  - Docker Desktop Version:
`2.4.0.0 (48506)`

  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
No.

### Steps to reproduce the behavior
 1. `docker run -v "/D/":"/data" hello-world` 

Same for  `-v "D:/":"/data"`, `-v "D:":"/data"`,  `-v "/d/":"/data"` in case you are wondering if it's a syntax issue.

**Comment by stephen-turner** [comment]
Thanks for the report. I don't think it's the same as #5516 because that had "file exists" instead of "operation not permitted".

**Comment by 4nti-7rust** [comment]
True, I have updated my ticket, thanks.
