### ISSUE TITLE
Unstable WSL backend

### ISSUE THREAD

**Issue by ninadbstack** [docker/for-win#9206]
- [x] I have tried with the latest version of my channel (Stable or Edge) (2.4.0.0)
  - [ ] I have uploaded Diagnostics (No because It never fully crashes or generates a diagnostic ID)
  - Diagnostics ID: Log file is attached

### Expected behaviour
Docker daemon starts every time with wsl2 backend while cold start.

### Actual behaviour
Docker daemon does not start intermittently.  It does not detect a crash or an exception and so no dialogue ever pops up from which I can upload diagnostic report.

### Information

1. Is it reproducible?
    It is intermittent problem. 
2. Is the problem new?
    Not sure, we have tried from Docker desktop 2.3.0.4 and 2.4.0.0, both versions have this issue.

This is intermittent issue and I did not see any specific wsl crashing events in event viewer ( if there is something specific to look for let me know. 
   I do know that Docker Desktop for window is not officially supported on virtualized windows yet but still would like to know if anything can be helpful.
   The issue log line is 
`[04:19:42.177][WslKeepAlive      ][Warning] stopped unexpectedly. stdout:
The Windows Subsystem for Linux instance has terminated.

stderr:`

  - Windows Version: Windows 10-19041
  - Docker Desktop Version: 2.3.0.4/2.4.0.0 with WSL2 backend
  - Are you running inside a virtualized Windows: Yes 

### Steps to reproduce the behaviour
Just run daemon starting multiple times, it happens a few times. 

Log file:
[log.txt](https://github.com/docker/for-win/files/5429705/log_fail4.txt)

**Comment by stephen-turner** [comment]
Thanks for the report. I guess my first question is whether WSL 2 crashes sometimes anyway even without Docker Desktop.

**Comment by ninadbstack** [comment]
@stephen-turner Thanks for replying! I haven't used it separately specifically. I will try to load some distro on it and test it.
