### ISSUE TITLE
docker cp - from container to host produces invalid tar archive

### ISSUE THREAD

**Issue by tejksat** [docker/for-win#923]
### Expected behavior

`docker cp CONTAINER:SRC_PATH - > output.tar` produces valid `output.tar` archive that contains `src_path` resource.

### Actual behavior

`docker cp CONTAINER:SRC_PATH - > output.tar` produces invalid `output.tar` archive that cannot be used later on.

### Information

  - Diagnostic ID: `CC2580BB-1386-40E4-9B0F-7FC3F441B1A7/2017-07-15_00-14-35`.
  - host distribution and version: `Windows 10 Pro, Version 1607 (OS Build 14393.1480)`

### Steps to reproduce the behavior

  1. Open Windows PowerShell
  2. Create a container and copy a file from it piping output in a file:
```
PS C:\Users\Username> docker create stefanscherer/python-windows:nano
cd5b78525898fd7a8c47a333c2f6d5073ee439b3bd8e3437bc58dc11ffb45f18
PS C:\Users\Username> docker cp cd5b78525898fd7a8c47a333c2f6d5073ee439b3bd8e3437bc58dc11ffb45f18:C:\License.txt - > License.tar
```
   3. Try to extract the archive or open it: neither Linux `tar` nor Windows 7-Zip works. 7-Zip test ends with the error:
```
Can not open the file as [tar] archive
Is not archive
```

**Comment by friism** [comment]
This is a known defect in PowerShell: https://github.com/PowerShell/PowerShell/issues/1908

Can you just use the `DEST_PATH` mode?

```
docker cp CONTAINER:SRC_PATH DEST_PATH
```

**Comment by tejksat** [comment]
@friism I thought the problem lied deeper in Docker Engine but this is fine for me, thank you!

**Comment by tejksat** [comment]
`docker cp CONTAINER:SRC_PATH - > output.tar` works well and produces a valid archive when executing in Windows Comand Prompt (cmd.exe) instead of PowerShell.
