### ISSUE TITLE
Docker upgrade creates shortcut link on desktop

### ISSUE THREAD

**Issue by matthias-b** [docker/for-win#925]
### Expected behavior
Upgrading docker does not modify existing shortcuts or menus.

### Actual behavior
A desktop icon is created without permission.

### Information
New version (don't know old version): Version 17.06.0-ce-win19 (12801)
Diagnostic ID: 014E5B4F-5D49-4CC6-8B60-A1EF8EB896A8/2017-07-16_09-23-11
Windows 10 Enterprise version 1607 build 14393.1358

### Steps to reproduce the behavior

  1. Have a version installed.
  2. Agree to a prompted upgrade

**Comment by jasonbivins** [comment]
Hi @matthias-b 
I entered this in as an enhancement request for you - do you mind if I go ahead and close this issue?

**Comment by matthias-b** [comment]
Yeah, sure.
