### ISSUE TITLE
Can't exec into Docker containers

### ISSUE THREAD

**Issue by cwcoffman** [docker/for-win#926]
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. Start an ubuntu container, using the latest release - "docker container run --rm -itd --name ubuntu --net TestNet ubuntu:16.04"

  2. Attempt to exec into shell - "docker exec ubuntu bash"

Hangs indefinitely.  Certain commands (like ping) work OK, but many do not.  On the redis image, for example the 'redis-cli' command hangs just as bash does above.

Have tried several things, including uninstalling Docker for Windows and running the script from Docker to remove all files (https://success.docker.com/KBase/How_to_completely_remove_Docker).  Nothing so far.

**Comment by friism** [comment]
What version of Docker are you using? Please post output of `docker version`

**Comment by cwcoffman** [comment]
> docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true

**Comment by friism** [comment]
When you're starting your container you're not passing a command to run. I don't know exactly what state that leaves it in. This works for me: 

```
docker container run --rm -itd --name ubuntu ubuntu:16.04 sleep 100000
docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
ecf3e8a38996        ubuntu:16.04        "sleep 100000"      4 seconds ago       Up 3 seconds                            ubuntu
docker exec -ti ec bash
root@ecf3e8a38996:/# exit
exit
```

Also, when starting the container with `-d` you probably shouldn't pass `-it` too (since you won't be needed the interactive session then).

What are you trying to do overall?

**Comment by cwcoffman** [comment]
So, quick correction.  This happens in a couple different situations.  If I simply try to run an ubuntu container, in an interactive session with the following command (for example), it hangs:

docker run -it ubuntu bash

To your question, I want to be able to do a couple things:
1) Run an ubuntu container, as needed, to allow a linux environment for development on my Windows laptop. 

2) Be able to initiate a terminal session on a running container (in a daemon), so that I can manage/develop on that environment.  Including being able to view the directory tree, and run commands.  

Thanks, and let me know if you have questions.

**Comment by friism** [comment]
What shell are you using? If PowerShell ISE, then please use a different shell

**Comment by cwcoffman** [comment]
That was it!  Thank you so much!

As an FYI, I was using the PowerShell ISE because I downloaded the PowerShell tab completion (https://docs.docker.com/docker-for-windows/#set-up-tab-completion-in-powershell) and it seemed to only work in PowerShell ISE!  I'll dive deeper into how to properly use that in all PowerShell sessions and avoid the ISE terminal.

Thanks so much!  Love the easy fixes.
