### ISSUE TITLE
error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/create: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

### ISSUE THREAD

**Issue by vishal2bSDE** [docker/for-win#9264]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by skapper1988** [comment]
Facing similar issue after installing Docker on windows 10 Enterprise by following official site https://docs.docker.com/docker-for-windows/install/


ERROR:
C:\WINDOWS\system32>docker run -d -p 80:80 docker/getting-started
docker: error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/create: open //./pipe/docker_engine: The system cannot find the file specified. 
In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
See 'docker run --help'.

**Comment by jorgedjn58** [comment]
I was having similiar issue showing this log:

$ docker run busybox
docker: error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/create: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
See 'docker run --help'.

I was able to make it work after updating the WSL2 Linux Kernel, check below link 

https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel
