### ISSUE TITLE
Docker on windows crashes on startup with "Docker command did not complete within the allowed timeout"

### ISSUE THREAD

**Issue by minkbear** [docker/for-win#927]
### Expected behavior

Docker start up with no error.

### Actual behavior

Update to version 17.06.0-ce-win19 (12801), Channel: stable, c98c1c2 . Fixed for #818 and #874 When restart my computer, I face the problem that docker start up then show error `Docker command did not complete within the allowed timeout`
But shut down docker and start again, It works fine.

**Diagnostic ID**

2C49BCDE-B804-423F-8D70-EE5ED1423490/2017-07-17_13-13-00

**Output of docker version:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of docker info:**

```
Containers: 7                                                                 
 Running: 0                                                                   
 Paused: 0                                                                    
 Stopped: 7                                                                   
Images: 201                                                                   
Server Version: 17.06.0-ce                                                    
Storage Driver: overlay2                                                      
 Backing Filesystem: extfs                                                    
 Supports d_type: true                                                        
 Native Overlay Diff: true                                                    
Logging Driver: json-file                                                     
Cgroup Driver: cgroupfs                                                       
Plugins:                                                                      
 Volume: local                                                                
 Network: bridge host ipvlan macvlan null overlay                             
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive                                                               
Runtimes: runc                                                                
Default Runtime: runc                                                         
Init Binary: docker-init                                                      
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a                  
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4                        
init version: 949e6fa                                                         
Security Options:                                                             
 seccomp                                                                      
  Profile: default                                                            
Kernel Version: 4.9.36-moby                                                   
Operating System: Alpine Linux v3.5                                           
OSType: linux                                                                 
Architecture: x86_64                                                          
CPUs: 2                                                                       
Total Memory: 1.934GiB                                                        
Name: moby                                                                    
ID: NW75:2J27:FCGP:RLEH:G6JN:7VMN:CGTS:OK5H:LHXK:DGJY:DKZZ:ZTI4               
Docker Root Dir: /var/lib/docker                                              
Debug Mode (client): false                                                    
Debug Mode (server): true                                                     
 File Descriptors: 15                                                         
 Goroutines: 25                                                               
 System Time: 2017-07-17T06:20:37.2486796Z                                    
 EventsListeners: 0                                                           
Registry: https://index.docker.io/v1/                                         
Experimental: true                                                            
Insecure Registries:                                                          
 127.0.0.0/8                                                                  
Live Restore Enabled: false             
```

**Comment by kevinkuszyk** [comment]
Same here.  Diagnostic id: B2C6AEC0-EB42-4E28-9E47-5A33122A7059/2017-07-19_08-38-13

**Comment by valeriano-manassero** [comment]
Same here. Diagnostic id: 293A0B6E-066E-4604-982E-7D4C90AB0F8A/2017-07-21_08-07-01

**Comment by georlav** [comment]
Diagnostic id: 95310B22-DC33-4D40-B5BA-5A931B91A2C9/2017-07-21_10-16-03
Diagnostic id: 95310B22-DC33-4D40-B5BA-5A931B91A2C9/2017-07-21_10-17-26

**Comment by rblenkinsopp** [comment]
This is consistently happening for me as well, tested stable and edge. Diagnostics ID for last (edge) crash:
`9C822351-CCEA-48DE-A9C2-21CFF7ACC238/2017-07-22_09-59-08`

**Comment by gauravraosahab** [comment]
I have to reset to factory defaults every time i start up docker on windows otherwise I get response

Error response from daemon: Bad response from Docker engine

Error response from daemon: Get https://********.dkr.ecr.us-east-2.amazonaws.com/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by Eikc** [comment]
I have the same issue, i can either reset to factory settings or restart my computer also works (i don't understand why that actually works)..

**Comment by rikkit** [comment]
I have the same issue - for me the fastet fix is to go to the advanced tab in settings, move the memory amount allocated by 1 notch and restart.

**Comment by johnwchadwick** [comment]
This also happens to me, with seemingly increasing occurrences by the day. It happens every time I boot up and usually the second or third time I try to start Docker too. However, I've found that simply restarting Docker entirely will eventually solve the problem.

```
Docker command did not complete within the allowed timeout. Output: 
   at Docker.Backend.MobyCommand.RunDocker(String arguments, IDictionary`2 envVariables, String stdin, Int32 timeoutMs, String cidFile)
   at Docker.Backend.MobyCommand.Run(String commandLine, IDictionary`2 envVariables, Boolean load, String stdin, Int32 timeoutMs)
   at Docker.Backend.SambaShare.MountInMoby(String mount, String drive, Credential cred, CredentialInfo credInfo, String options, String ip)
   at Docker.Backend.SambaShare.MountInMoby(String drive, Credential credential, Settings settings)
   at Docker.Backend.SambaShare.Mount(String drive, Credential credential, Settings settings)
   at Docker.Backend.BackendServer.<Run>b__5_11(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

This is really a pain. Docker for Windows appears to be closed source, which means that I can't look into this issue myself (well, without getting my hands dirty, anyways.) I hope that someone at Docker is at least paying attention.

Oh well. Fired off a diagnostic report. `AA403479-03D1-4583-B64C-C176AE53E06D/2017-08-03_06-31-04`

**Comment by bsobotta** [comment]
The same happens for me and all the people I know that are using Docker for Windows. It's a real pain to shut down docker manually after startup and restart it again.

We keep sending crash reports, just as an example, diagnostic id:
709E5840-67D0-49FD-9B6A-DDD4E8F47B11/2017-08-04_09-27-12

**Comment by rikkit** [comment]
What version of Windows is everyone on? I'm on 16232.1000, current slow ring build. I did notice this only started happening to me after I upgraded a couple of weeks ago - though that could be a coincidence

**Comment by bsobotta** [comment]
I'm on 17.06.0-ce-win19 (12801)

**Comment by rikkit** [comment]
@bsobotta Windows version, not Docker for Windows version 😃 .

**Comment by johnwchadwick** [comment]
I'm on Windows 10 Pro version 1703, build 15063.483. I switched to Docker Edge and haven't seen the issue yet, so I'm kind of curious to see if maybe that improves things.

**Comment by gauravraosahab** [comment]
I am on Windows 10 latest, and docker 17.

I have reverted back to 16, and it seems to be working fine.

Another issue was docker login was not working on very 17.

On Aug 4, 2017 6:55 AM, "John Chadwick" <notifications@github.com> wrote:

I'm on Windows 10 Pro version 1703, build 15063.483. I switched to Docker
Edge and haven't seen the issue yet, so I'm kind of curious to see if maybe
that improves things.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/docker/for-win/issues/927#issuecomment-320208961>, or mute
the thread

**Comment by bsobotta** [comment]
@rikkit Ah sorry, missed that word :D

I'm on Windows 10 Enterprise 1607

**Comment by rikkit** [comment]
@johnwchadwick any other issues on Docker Edge? I was planning to downgrade Docker a few versions but upgrade would be preferable

@bsobotta no worries, seems Windows version doesn't correlate with the issue anyway!

**Comment by johnwchadwick** [comment]
Not so far. It's running my big ol' compose setup just fine. That being said, I can't say for sure that it solved the issue, I'll need to wait a week or so to be totally sure.

**Comment by ItsReddi** [comment]
17.06.0-ce-win19 (12801) - c98c1c2

**Comment by jchv** [comment]
I can confirm that this is still not fixed in any edge or stable version. I actually don't have a machine this doesn't happen on so I'd be shocked if the problem was being able to reproduce this; at this point I just think it's a matter of waiting for some kind of acknowledgement from Docker's end.

This is pretty painful though. It also makes it so Docker never properly shuts down, so you have to kill it to retry. After waiting several minutes for it to fail in the first place.

**Comment by rblenkinsopp** [comment]
Likewise, I have tested edge and stable and and still running into this on all machines, It's becoming really quite tiresome restarting it each time.

**Comment by jchv** [comment]
It seems like there are multiple intertwined issues here, so it's kind of hard to tell who's suffering from which affliction. I guess the stack traces will probably differ.

However... if you do cold boots a lot, you should try [disabling Fast Startup](https://github.com/docker/for-win/issues/941#issuecomment-324535767). As best as I can tell, this seems to have solved my issue. I will give it more time, but it went from failing to startup almost every day to working two days in a row, so I'm hopeful.

**Comment by jeffbarnes769** [comment]
Docker has started consistently after disabling fast startup, and a windows 10 memory leak is also less of an issue.  Check out https://github.com/docker/for-win/issues/941 to see if it can help here as well

**Comment by brunolm** [comment]
This happens way too often, the way I found to get it working again was to:

- Disable Hyper-V
- Restart computer
- Enable Hyper-V
- Restart computer

But to do that everyday is really annoying.

**Comment by brunolm** [comment]
The firewall did not solve the issue. But I started to be able to go in `Settings > Restart docker...` (after it failed) and it could restart successfully. Not sure if just a coincidence or not.

**Comment by danieljarlevang** [comment]
I have this issue on Windows 10 Enterprise 1703 build 15063.674. Closing the Docker app (sometimes a force quit is required), restarting the service (com.docker.service), and then opening Docker again solves it for me.

**Comment by gmanolache** [comment]
I have the same issue at windows startup with docker CE 17.09.0-ce-win33 stable for Windows 10 Pro.
Restarting docker solves it.

**Comment by Srokap** [comment]
Same here. Restarting docker from settings helps every time, no need to change anything about Hyper-V or restart it.

**Comment by johnrom** [comment]
This happens every weekday on my desktop at work, and just happened on my laptop at home. Simply opening settings and "Restart Docker" fixes every time. I believe exiting Docker before shutting down will prevent it from happening on boot-up, though maybe that was just a coincidence. It could be that something isn't disposing properly on shutdown.

**Comment by gmanolache** [comment]
Still need to restart daily.

**Comment by mdavis6890** [comment]
me too
