### ISSUE TITLE
Docker Windows Ports are not available: unable to list exposed ports

### ISSUE THREAD

**Issue by sreaswar** [docker/for-win#9273]
- [X]  I have tried with the latest version of my channel (Stable or Edge)

  - [X ] I have uploaded Diagnostics
  - Diagnostics ID: 6D3FCDA1-C2B1-4EDB-9D5A-5044BC2198A0/20201027234950

### Expected behavior

docker-compose up -d  (yml file with multiple services)
All containers(services) are started normally

### Actual behavior
Some of the services fail with the following error -

ERROR: for jaeger  Cannot start service jaeger: Ports are not available: unable to list exposed ports: Get "http://unix/forwards/list": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

Note: Redis service in the same yml file starts successfully

Addtional info:
netstat -a -n -o | findstr "6832 6831" returns nothing (no other process is using these ports)
Docker running in Hyper V mode with Linux containers enabled.

### Information

  - Windows Version:
Windows 10 (Version 1909 OS Build 18363.1139
  - Docker Desktop Version:
2.4.0.0(48506) Channel stable
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
No
### Steps to reproduce the behavior
<!--
A reproducible case, Dockerfiles with reproduction inside is best.
(docker yml file snippet)
services:
redis:
    image: redis
    container_name: verbund-api-redis
    ports:
      - "6379:6379" 
jaeger:
    image: jaegertracing/all-in-one:1.13
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"

**Comment by sreaswar** [comment]
Steps to reproduce the behavior (sample yml file)
services:
  redis:
    image: redis
    container_name: verbund-api-redis
    ports:
      - "6379:6379"
  jaeger:
    image: jaegertracing/all-in-one:1.13
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"

docker-compose up -d

**Comment by olaven** [comment]
Experiencing similar issue on MacOS

docker-compose: 
```yml

version: "3"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://database/api-db
      - DATABASE_USER=$DATABASE_USERNAME
      - DATABASE_PASSWORD=$DATABASE_PASSWORD

  database:
    image: postgres
    environment:
      - POSTGRES_USER=$DATABASE_USERNAME
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - PGDATABASE=api-db
```

Error: 
```
ERROR: for <FOLDER-NAME>_api_1  Cannot start service api: Ports are not available: unable to list exposed ports: Get http://unix/forwards/list: dial unix docker-api.sock: connect: connection rCreating <FOLDER-NAME>_database_1 ... error

ERROR: for <FOLDER-NAME>_database_1  Cannot start service database: Ports are not available: unable to list exposed ports: Get http://unix/forwards/list: dial unix docker-api.sock: connect: connection refused

ERROR: for api  Cannot start service api: Ports are not available: unable to list exposed ports: Get http://unix/forwards/list: dial unix docker-api.sock: connect: connection refused

ERROR: for database  Cannot start service database: Ports are not available: unable to list exposed ports: Get http://unix/forwards/list: dial unix docker-api.sock: connect: connection refused
ERROR: Encountered errors while bringing up the project.
```

**Comment by pocso** [comment]
Any proceedings?

**Comment by cdalexndr** [comment]
Encountered this issue when a container was timing out http requests.
While recreating container, I got the `Ports are not available` error after a long wait (timeout?).
At the same time, the docker UI app is sluggish and eventually hangs.
"About" window doesn't show any fields (all blank).
Issuing a docker restart hangs with tray icon animating as restarting (I guess same wait for port to timeout).
Seems the whole docker is bugged.

After restart seems to work fine.

Docker for win 3.1.0 (51484)
