### ISSUE TITLE
MobyLinuxVM stops responding

### ISSUE THREAD

**Issue by ATGardner** [docker/for-win#928]
After a short while running in Windows (~1-2 hours), docker commands stop responding, and just hang. Trying to restart docker gives me 
```
Unable to stop: Couldn't stop VM MobyLinuxVM
at Fatal, <No file>: line 376
at Stop-VM-Force, <No file>: line 372
at Stop-MobyLinuxVM, <No file>: line 302
at <ScriptBlock>, <No file>: line 383
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 177
   at Docker.Backend.ContainerEngine.Linux.DoStop() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 280
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 169
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
```

If I try to manually shutdown the MobyLinuxVM, it fails as well. Tryikng to restart my computer also fails, presumably because it can't shutdown the VM properly. I have to reset using the hardware button.
It happens repeatedly during my workday.

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
70F95772-E4B6-4FB2-A1CE-2C084C3E7B66/2017-07-17_10-58-22

  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)
Microsoft Windows [Version 10.0.16241.1001]
Docker version 17.06.0-ce, build 02c1d87
docker-machine version 0.12.0, build 45c69ad

**Comment by dsmaher** [comment]
I have this issue as well (the timing is a bit longer for me, but it may just depend on how much you use Docker, and not the actual time).  FYI Windows `16241` is the latest Windows Insider build, and I also am on the same build.  I'm assuming that the Insider build changed something that is causing Moby to fail.

**Comment by ATGardner** [comment]
I also assumed the inside build is messing up something with the hyper-v. But I am also certain the previous insider builder had the same issue. After yesterday's update I was hoping the problem would go away, but since it didn't, I opened this issue.

**Comment by strattas** [comment]
Same here and also on Build 16241

**Comment by roja45** [comment]
Same here running on the latest windows slow ring build: 16232.

Is it possible to restart hyper-v without hard resetting the machine?  Not really a problem to restart docker every now again, but it's quite annoying having to reopen 50 windows and tabs after a full reset.

**Comment by jasonbivins** [comment]
We're looking into why the MobyLinuxVM hangs - but it is possible to to use Process explorer to end the VM's process.
This isn't specific to Docker - but this should help:  https://community.spiceworks.com/how_to/528-killing-ending-a-hyper-v-virtual-machine-that-is-stuck

**Comment by roja45** [comment]
Anyone had any luck following those steps, it doesn't seem to work for me?  
I can find the process but I get access denied when I try to kill it.  I'm running the process explorer as admin, and I can kill other processes without any problem.

**Comment by ATGardner** [comment]
Yeah, I tried that workaround yesterday at work, and it didn't help with anything. Still have to restart my computer every time.

**Comment by roja45** [comment]
If it helps, I uninstalled docker this morning, reinstalled and setup all the environments again.  Vm size much smaller and all generally a bit more snappy now, but still froze after a couple of hours.  Hard reset only way out.

**Comment by roja45** [comment]
I updated windows to the latest insider build 16251 and the docker containers have been running without problem now for 2 days.

**Comment by strattas** [comment]
@roja45 
Yep here too!

**Comment by ATGardner** [comment]
My computer updated before the weekend, and since then docker seems to be running well. Hopefully this bug is behind us.

**Comment by awidjaja** [comment]
Same issue with stable build on Windows 10 version 1703
https://github.com/docker/for-win/issues/1119
