### ISSUE TITLE
Cannot build due to file is blocked by process error

### ISSUE THREAD

**Issue by frabla** [docker/for-win#929]
### Expected behavior
Build the Helloworldapp

### Actual behavior
After extraction of the last file the process aborts with the message:
failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage C:\ProgramData\Docker\windowsfilter\ff6c3daaf8215ad11d75d4afe1b045b9cdb4
e6def9346de644700f9d321164a4\UtilityVM: The process cannot access the file because it is being used by another process.

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. create directory due to example
  2. Follow instruction on: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-containers
[log.6.txt](https://github.com/docker/for-win/files/1152269/log.6.txt)
[log.txt](https://github.com/docker/for-win/files/1152268/log.txt)

**Comment by StruninIhor** [comment]
I have the same issue on windows server 2016 VM when I was trying to use `docker load < image.tar`. Docker was installed on windows server using following instructions - https://docs.docker.com/install/windows/docker-ee/
