### ISSUE TITLE
Windows volumes unmounting periodically 

### ISSUE THREAD

**Issue by torleif** [docker/for-win#93]
### Expected behavior

After a docker volume has been mounted, it persists

### Actual behavior

After a few minutes, the volume will silently fail and stop giving access to the mounted file:

```
# cd /var/www
# ls
reading directory .: Host is down
```

### Information

Operating System: Windows 10
Docker Image: https://github.com/sminnee/docker-silverstripe-lamp
Docker folder path: //c/Users/<username>/website:/var/www
The following mounted information:
```
        "Mounts": [
            {
                "Source": "/c/Users/torleifw/op",
                "Destination": "/var/www",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
```

### Steps to reproduce the behavior

  1. Create a docker with a windows volume mounted 
  2. after 5-10 minutes the volume will be unmounted, and cannot be re-mounted

**Comment by dgageot** [comment]
Hi @torleif thank you for the report. Can you tell us which version of Docker for Windows you are using. Also, it would be helpful if you could share a log file when the issue occurs again.

**Comment by torleif** [comment]
I'm currently using 1.12.1-stable.

It didn't seem to happen after I updated from the previous stable version. 

I had a look at the log file, it seems there's nothing but apache output.

**Comment by rneugeba** [comment]
Thanks for getting back to us. I'm closing this issue as you don't seem to be able to reproduce it anymore. Should this happen again, please upload the diagnostics and let us know the ID it provides.
Thanks
