### ISSUE TITLE
Docker mounting host file as a data volume no longer works

### ISSUE THREAD

**Issue by RobertBoothby** [docker/for-win#930]
### Expected behavior
Per the [documentation](https://docs.docker.com/engine/tutorials/dockervolumes/#mount-a-host-file-as-a-data-volume) I expect to be able to mount a single host file to my docker image. This did work on previous versions.
### Actual behavior
When I try to mount the host file it mounts it as an empty directory if the file does not exist in the image. This is happening to me and my colleagues running Docker for Windows, not for my colleagues running Docker for Linux and Mac.
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
8C7ABEFB-E678-403F-AAC1-20921A20F512/2017-07-17_11-45-02
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
[documentation](https://docs.docker.com/engine/tutorials/dockervolumes/#mount-a-host-file-as-a-data-volume)
  - host distribution and version (Windows version, build number, etc)
OS Name	Microsoft Windows 10 Pro
Version	10.0.15063 Build 15063

### Steps to reproduce the behavior

  1. Create a temporary text file in the local host system (e.g. tmp.txt) with some content.
  2. Run a temporary bash image using "docker run --rm -it -v .\tmp.txt:/tmp.txt bash bash" launching the image's bash.
  3. Run "ls -altr" within the image and see that tmp.txt has been created as an empty directory and not the local file.

**Comment by jasonbivins** [comment]
Hi @RobertBoothby   It looks like there's a syntax issue in the path you're using.
I can reproduce the issue using your command - but using this one it seems to work without issue.  Let me know if you have issues with it

docker run --rm -ti -v c:/Users/desktop.ini:/foo alpine sh

**Comment by jamieshiz** [comment]
@jasonbivins - I am having a similar issue using docker-compose. See issue here: https://github.com/docker/compose/issues/5037

**Comment by RobertBoothby** [comment]
Thanks Jason. Sorry about the delay in replying. That gives us a work-around but it does highlight a change in behaviour and a divergence from the documentation referenced.

> On Windows, mount directories using:

>docker run -v c:\<path>:c:\<container path>
