### ISSUE TITLE
fail to push image to private registry 

### ISSUE THREAD

**Issue by RogerYaozhenyu** [docker/for-win#931]
### Expected behavior
docker push image to private registry successful
### Actual behavior
failed.

### Information
$ docker push 10.5.128.78:5000/netconf
The push refers to a repository [10.5.128.78:5000/netconf]
Get https://10.5.128.78:5000/v2/: http: server gave HTTP response to HTTPS client
 

### Steps to reproduce the behavior

1.install docker registry on ubuntu 14.04 . and   succed to saw {} whiel excuted http://127.0.0.1:5000/v2
2. win10 machine .run docker push image ip:5000/imagename.

**Comment by friism** [comment]
Suggestions here: https://github.com/docker/distribution/issues/1874#issuecomment-237194314

**Comment by riezebosch** [comment]
On docker-for-windows you have to edit this information in the settings GUI.

![settings](https://user-images.githubusercontent.com/1427334/28560964-d67b2bde-711c-11e7-9432-e89f2a855e22.PNG)
![registries](https://user-images.githubusercontent.com/1427334/28560979-deba2f3e-711c-11e7-90a9-42e4a37cc048.PNG)

**Comment by Davidrjx** [comment]
i was faced with same issue only but push action in debian and error with "****/v1/_ping: Forbidden port"
