### ISSUE TITLE
Docker for windows fails after upgrade to Windows version 1703

### ISSUE THREAD

**Issue by wittyameta** [docker/for-win#932]
### Expected behavior
Docker should start on windows 10, version 1703

### Actual behavior
Unable to start with this error: 'MobyLinuxVM' failed to start worker process: Windows cannot verify the digital signature for this file. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source. (0xC0000428). (Virtual machine ID F76E314E-7281-49C2-A190-3A3E1C207ED8)
at Start-MobyLinuxVM, <No file>: line 291

### Information

  - Diagnostic ID: 5BAF9C53-DCFD-4DDC-BFC4-E82E5839E57F/2017-07-18_14-31-41
  - - host distribution and version: Windows 10 Enterprise; Version 1703; OS build: 15063.0

### Steps to reproduce the behavior

  1. Update windows 10 to version 1703.
  2. Try to start docker - doesn't start
  3. Rollback to previous version of windows 10, and docker starts again!

**Comment by brandonoakley** [comment]
Having same issue even after disabling Hyper-V, uninstalling Docker, reboot, reinstall Hyper-V, reboot, install Docker, and reboot.

**Comment by jasonbivins** [comment]
Hi @wittyameta 
Can you check to make sure the Containers feature is enabled in Windows, it looks like it's disabled according to the debug logs.   In an elevated powershell prompt:  Enable-WindowsOptionalFeature -Online -FeatureName Containers -All

**Comment by wittyameta** [comment]
@jasonbivins Tried, but still getting the same error.

**Comment by jasonbivins** [comment]
Hi @wittyameta 
It looks like you're on the edge build - can you try updating to the latest one ?  We did have some issues with Windows smartscreen interfering last week.

**Comment by wittyameta** [comment]
Hi @jasonbivins 
I'm getting the error with stable version as well

**Comment by jasonbivins** [comment]
@wittyameta   Can you please reboot if you haven't already - then try the latest Edge build here:  https://docs.docker.com/docker-for-windows/install/#download-docker-for-windows 

Make sure you're installing this version
![image](https://user-images.githubusercontent.com/28021664/28326412-b4e5351e-6bae-11e7-8d03-a9f5db5e3bf1.png)

**Comment by wittyameta** [comment]
@jasonbivins Same error :(

**Comment by wittyameta** [comment]
Any update on this? I don't want to rollback my Windows version.

**Comment by wittyameta** [comment]
I had to finally rollback to previous Windows version :/

**Comment by vaibhav-gawali** [comment]
Same error for me too :(
Same issue for both stable and edge builds. Any updates?

**Comment by ericzhill** [comment]
Had the same problem here and it seems to be related to CarbonBlack.  I added a specific allow rule for the following executable and Docker started up on the first try:

C:\Windows\System32\vmwp.exe

**Comment by zsims** [comment]
Any update on this? I had no luck adding exceptions for `C:\Windows\System32\vmwp.exe` to the virus scanner.
