### ISSUE TITLE
Can't start kubernetes

### ISSUE THREAD

**Issue by peter-jerry-ye** [docker/for-win#9324]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 7FBE6D48-34BA-48DC-B18A-B6A24A286650/20201101054128

### Expected behavior
Kubernetes starts
### Actual behavior
Kubernetes indicates 'starting' forever
### Information

  - Windows Version: 10.0.19041.0
  - Docker Desktop Version: 2.4.2.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: WSL2

```
zihang@LAPTOP-3D0U3OTG:~$ tail /mnt/c/Users/Jerry\ Ye/AppData/Local/Docker/log.txt
[13:40:36.920][ApiProxy          ][Info   ] msg="cannot get lease for master node: an error on the server (\"\") has prevented the request from succeeding (get leases.coordination.k8s.io docker-desktop)"
[13:40:36.920][GoBackendProcess  ][Info   ] msg="external: POST /events 200 \"Go-http-client/1.1\" \"\""
[13:40:46.927][ApiProxy          ][Info   ] msg="cannot get lease for master node: an error on the server (\"\") has prevented the request from succeeding (get leases.coordination.k8s.io docker-desktop)"
[13:40:46.928][GoBackendProcess  ][Info   ] msg="external: POST /events 200 \"Go-http-client/1.1\" \"\""
[13:40:56.921][ApiProxy          ][Info   ] msg="cannot get lease for master node: an error on the server (\"\") has prevented the request from succeeding (get leases.coordination.k8s.io docker-desktop)"
[13:40:56.921][GoBackendProcess  ][Info   ] msg="external: POST /events 200 \"Go-http-client/1.1\" \"\""
[13:41:06.927][ApiProxy          ][Info   ] msg="cannot get lease for master node: an error on the server (\"\") has prevented the request from succeeding (get leases.coordination.k8s.io docker-desktop)"
[13:41:06.927][GoBackendProcess  ][Info   ] msg="external: POST /events 200 \"Go-http-client/1.1\" \"\""
[13:41:16.931][ApiProxy          ][Info   ] msg="cannot get lease for master node: an error on the server (\"\") has prevented the request from succeeding (get leases.coordination.k8s.io docker-desktop)"
[13:41:16.932][GoBackendProcess  ][Info   ] msg="external: POST /events 200 \"Go-http-client/1.1\" \"\""
```
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by chris-gillatt** [comment]
I resolved this problem for Mac by:

- Stop docker client
- delete the following directory `~/Library/Group Containers/group.com.docker/pki`
- Start docker client (and give it a decent time to start, say 5 mins or so)

Not sure what the equivalent Windows directory is but it could be worth looking one in the tree somewhere named `pki`

**Comment by peter-jerry-ye** [comment]
> 
> 
> I resolved this problem for Mac by:
> 
>     * Stop docker client
> 
>     * delete the following directory `~/Library/Group Containers/group.com.docker/pki`
> 
>     * Start docker client (and give it a decent time to start, say 5 mins or so)
> 
> 
> Not sure what the equivalent Windows directory is but it could be worth looking it in the tree somewhere named `pki`

I've deleted the pki directory but it didn't solve the problem.

**Comment by CFR0901** [comment]
> Not sure what the equivalent Windows directory is but it could be worth looking it in the tree somewhere named `pki`

In Windows the directory can be found in `C:\Users\<USER>\AppData\Local\Docker`.

**Comment by kkzz8888** [comment]
same issue here on macOS BigSur docker version 3.0.2 (latest), caused by a power outage in my case... deleting pki directory does fix the issue but it destroys the entire k8s stack, please fix.

**Comment by gyangupta07** [comment]
> > I resolved this problem for Mac by:
> > ```
> > * Stop docker client
> > 
> > * delete the following directory `~/Library/Group Containers/group.com.docker/pki`
> > 
> > * Start docker client (and give it a decent time to start, say 5 mins or so)
> > ```
> > 
> > 
> > Not sure what the equivalent Windows directory is but it could be worth looking it in the tree somewhere named `pki`
> 
> I've deleted the pki directory but it didn't solve the problem.



Hi,
How did you resolve this issue..I am struggling with the same.

**Comment by gyangupta07** [comment]
Can someone help please how was is solved on windows for Docker desktop

**Comment by CFR0901** [comment]
I have installed version 2.3.0.5 and it runs fine so far. Not sure if and when I will try a newer version again.

**Comment by iximiuz** [comment]
Removing `~/Library/Group Containers/group.com.docker/pki` didn't help. Resetting to factory defaults did help.

**Comment by dodysw** [comment]
Thank you for this, deleting `~/Library/Group Containers/group.com.docker/pki` worked for me. Still have no idea what the issue was.

**Comment by benbendemo** [comment]
I am running into same issue.
`cannot get lease for master node: an error on the server ("") has prevented the request from succeeding (get leases.coordination.k8s.io docker-desktop)`

**Comment by pjhavariotis** [comment]
I'm getting the following error (FRESH INSTALLATION)
```
[15:30:34.577][ApiProxy          ][Info   ] msg="cannot get lease for master node: an error on the server (\"\") has prevented the request from succeeding (get leases.coordination.k8s.io docker-desktop)"
[15:30:34.577][GoBackendProcess  ][Info   ] msg="external: POST /events 200 \"DockerDesktopGo\" \"\""

```

**Comment by derekrprice** [comment]
I am getting the same error as @pjhavariotis on Windows 10 Enterprise version 20H2 build 19042.867
I have tried deleting the pki directory from both C:\ProgramData\Docker and ~\AppData\Docker.  I have tried resetting k8s via the Docker Desktop control panel and I have performed a complete re-install of Docker Desktop.  The problem is still happening.

I've uploaded diagnostics to 5A2A9E35-82DA-42A6-8BC0-34F1D0B3A8AB/20210407144349

**Comment by derekrprice** [comment]
Updating to Windows build 19042.906 and restarting yet again has fixed the problem for me.

**Comment by jmmc-tools** [comment]
In Docker for Mac solve my problem removing ~/Library/Group Containers/group.com.docker/pki... I analyze the problem via:

```
pred='process matches ".*(ocker|vpnkit).*"
  || (process in {"taskgated-helper", "launchservicesd", "kernel"} && eventMessage contains[c] "docker")'

/usr/bin/log stream --style syslog --level=debug --color=always --predicate "$pred"
```

And I seen the message: 
`cannot get lease for master node: an error on the server ("") has prevented the request from succeeding (get leases.coordination.k8s.io docker-desktop)`

Another advices could have helped to solve this issue for me, I recreated /etc/hots with localhost entries (not fount before)... I suggest to see this another post to learn how to fix docker problems: 
https://github.com/docker/for-mac/issues/3327

**Comment by peZhmanParsaee** [comment]
I have installed these versions:
- Windows 10 v20H2 (Build 19042.928)
- Docker Desktop 3.2.2 (61853)

And I have this error log:
`
[ApiProxy          ][Info   ] msg="cannot get lease for master node: an error on the server ("") has prevented the request from succeeding (get leases.coordination.k8s.io docker-desktop)"
[GoBackendProcess  ][Info   ] msg="external: POST /events 200 "DockerDesktopGo" """
`

I deleted pki directory from this address: 
`C:\Users\[USER]\AppData\Local\Docker`

And then restart docker desktop, and reset kubernetes but the above error still remains

**Comment by SquaredLoops** [comment]
I had the exact same issue, I found that when I right-clicked on the Docker taskbar item (by the clock) it had an "Update and Restart" option. I did that, it downloaded an update and then everything worked when Docker came back online (give it 5 mins to start).

Working versions:
- Windows 10 v20H2 (Build 19042.928)
- Docker Desktop 3.3.1 (63152)
