### ISSUE TITLE
Pulling an image fails: "failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer C:\ProgramData\Docker\windowsfilter\557b978aea6f6608c6b334edcb23a9432d2ad7dbb44c9084fd9bdb80fccd3006: The parameter is incorrect."

### ISSUE THREAD

**Issue by felixkasza** [docker/for-win#933]
Pulling an image microsoft/nanoserver fails.

### Expected behavior

> docker pull microsoft/nanoserver

Image arrives.

### Actual behavior

> docker pull microsoft/nanoserver
Using default tag: latest
latest: Pulling from microsoft/nanoserver
bce2fbc256ea: Extracting [==================================================>]  252.7MB/252.7MB
baa0507b781f: Download complete
failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer C:\ProgramData\Docker\windowsfilter\557b978aea6f6608c6b334edcb23a9432d2ad7dbb44c9084fd9bdb80fccd3006: The parameter is incorrect.

Obviously, no image arrives.

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
    9F25684D-38CA-4D87-B4CE-33331E84B6D0/2017-07-18_23-12-56

  - a reproducible case if this is a bug, Dockerfiles FTW
    Repros abound. Just google for the error message. But I'm happy to help -- up to and including sending you an image of a machine showing the problem.

  - page URL if this is a docs issue or the name of a man page
    N/A

  - host distribution and version (Windows version, build number, etc)
    Default Isolation: hyperv
    Kernel Version: 10.0 15063 (15063.0.amd64fre.rs2_release.170317-1834)
    Operating System: Windows 10 Enterprise
    OSType: windows
    Architecture: x86_64

### Steps to reproduce the behavior

  1. docker pull microsoft/nanoserver
  2. wait. downloads happen, extract happens, boom.

Thanks for looking into this!

**Comment by marraim** [comment]
same problem

failed to register layer: re-exec error: exit status 1: output: Failed to OpenForBackup failed in Win32: open \\?\C:\Pro
gramData\Docker\windowsfilter\5f242122647f5a5a5c4361f5026a2f709f08ddd7638205158770da0e8abac0f9\usr\share\terminfo\e\eter
m: File esistente. (0x1f) \\?\C:\ProgramData\Docker\windowsfilter\5f242122647f5a5a5c4361f5026a2f709f08ddd7638205158770da
0e8abac0f9\usr\share\terminfo\e\eterm

**Comment by jasonbivins** [comment]
Hi @felixkasza 
It looks like there is a problem with either the containers feature, or Hyper-V - can you run the debugcontainer.ps1 script from this page and share the results?

https://github.com/Microsoft/Virtualization-Documentation/tree/live/windows-server-container-tools/Debug-ContainerHost

**Comment by jasonbivins** [comment]
@marraim can you post a diagnostic ID please, and a screenshot of the error you're seeing if you can.

**Comment by felixkasza** [comment]
Never mind. I gave up on Docker and went back to full-blown VMs.

**Comment by wave31** [comment]
You have selected Windows Containers at the time of setup rather than Linux Containers so only Windows-based images will run. To resolve this, right-click the tray icon and select 'Switch to Linux Containers' and it will start working.
https://stackoverflow.com/a/49657088/4258588

**Comment by felixkasza** [comment]
@wave31 -- Thanks, I think I'll try this. I confess I will be very surprised if this really was the reason for the failure, because in a million years I wouldn't expect MS to ship "microsoft/nanoserver" as anything but a windows-based image. 

Oh, and the error message? I have read hex error codes off a KIM-1's 7-segment-display back in 1977, and in the 41 years I have dabbled in low-level code I have seen a lot of crappy error messages. But as God is my witness, ~I thought turkeys could fly~ I have never seen anything as useless as 

> failed  to register layer: re-exec error: exit status 1: output: ProcessBaseLayer 
> C:\ProgramData\Docker\windowsfilter\557b978aea6f6608c6b334edcb23a9432d2ad7dbb44c9084fd9bdb80fccd3006: The parameter is incorrect.

Anyway, thanks for letting me (us) know about this!

**Comment by Shashank231190** [comment]
Well, was working on it and it seems like error message was returned in my case,  while vmcompute.dll was try to create VHDX  file to use it as an image in windows and not sure why.

Error message mentioned below:

PS C:\> docker pull microsoft/iis
Using default tag: latest
latest: Pulling from microsoft/iis
3889bb8d808b: Extracting [==================================================>]   4.07GB/4.07GB
ba2bcc6237ee: Download complete
5d8270d059d7: Download complete
741a27b074e9: Download complete
3fcc0eba7925: Download complete
failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage \\?\C:\ProgramData\docker\windowsfilter\15b9c33299194768feaa63b88a2ef02ac2214ffeb860f2f44175b3fa25fa08b9\UtilityVM: The parameter is incorrect.

**Comment by aminm1364** [comment]
> You have selected Windows Containers at the time of setup rather than Linux Containers so only Windows-based images will run. To resolve this, right-click the tray icon and select 'Switch to Linux Containers' and it will start working.
> https://stackoverflow.com/a/49657088/4258588

Thanks for the suggestion.
However, I solved my issue by changing the Linux container to the Windows container on my docker.

**Comment by Antronin** [comment]
For me this is still an issue:
`PS C:\WINDOWS\system32> docker pull nanoserver/iis
Using default tag: latest
latest: Pulling from nanoserver/iis
bce2fbc256ea: Extracting [==================================================>]  252.7MB/252.7MB
e7a598ed389e: Download complete
330fc9a0a84f: Download complete
8accfc5d2068: Download complete
ce0579b0380c: Download complete
363f5ae71fe9: Download complete
bdadd5a88cb5: Download complete
73f9c45f3462: Download complete
failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer \\?\C:\ProgramData\Docker\windowsfilter\60ffe5729894329a0e53cd97b4ce80af4459d95efc06f5edb37044d249dda4e2: The parameter is incorrect.`

I switched my Docker Destop to use Windows Containers. Still once the Download of the layer are finished, at the end of the first layers extract I got this error, all the time.

I'm on Windows 10, Diagnostic ID is: 0FDAFCEF-27E8-4C7A-B0ED-1613BA01A5F0/20200120142208
I'm unable to use almost any Windows image:

`PS C:\WINDOWS\system32> docker pull microsoft/iis
Using default tag: latest
latest: Pulling from microsoft/iis
3889bb8d808b: Extracting [==================================================>]   4.07GB/4.07GB
31f9df80631e: Download complete
26c58eaecc60: Download complete
1eea0c95c6fc: Download complete
5c630eb846f0: Download complete
failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer \\?\C:\ProgramData\Docker\windowsfilter\a5ea703cb7da8015bd69cefef038402b29c0c9bdd75b5e36cafc25d7836ea172: The parameter is incorrect.`

**Comment by ads90** [comment]
nothing worked for me until i use bash command
