### ISSUE TITLE
face hello cam

### ISSUE THREAD

**Issue by KevinChi01** [docker/for-win#9341]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by KevinChi01** [comment]
"C:\Users\Kevin\HP scan KJC01\HP’s Spectre X360 13\.vs"
"C:\Users\Kevin\HP scan KJC01\HP’s Spectre X360 13\en-US"
"C:\Users\Kevin\HP scan KJC01\HP’s Spectre X360 13\FaceDriver"
"C:\Users\Kevin\HP scan KJC01\HP’s Spectre X360 13\SurfacePro_Win10_150723_0"
"C:\Users\Kevin\HP scan KJC01\HP’s Spectre X360 13\51F39552-1075-4199-B513-0C10EA185DB0.DAT"
"C:\Users\Kevin\HP scan KJC01\HP’s Spectre X360 13\face rec10.txt"
"C:\Users\Kevin\HP scan KJC01\HP’s Spectre X360 13\FaceBootstrapAdapter.dll"
"C:\Users\Kevin\HP scan KJC01\HP’s Spectre X360 13\FaceFodUninstaller.exe"
"C:\Users\Kevin\HP scan KJC01\HP’s Spectre X360 13\FaceMF.Provider.dll"
"C:\Users\Kevin\HP scan KJC01\HP’s Spectre X360 13\helloface (1) (2020_08_13 21_04_34 UTC).dll"
"C:\Users\Kevin\HP scan KJC01\HP’s Spectre X360 13\helloface (2020_08_13 21_04_34 UTC).dll"
"C:\Users\Kevin\HP scan KJC01\HP’s Spectre X360 13\NUIVoiceWBSAdapters.dll"
"C:\Users\Kevin\HP scan KJC01\HP’s Spectre X360 13\sp110352.exe"
"C:\Users\Kevin\HP scan KJC01\HP’s Spectre X360 13\SurfaceCameraWindowsHello (2020_08_13 21_04_34 UTC).inf"
"C:\Users\Kevin\HP scan KJC01\HP’s Spectre X360 13\surfacecamerawindowshello.cat"
"C:\Users\Kevin\HP scan KJC01\HP’s Spectre X360 13\SurfaceCameraWindowsHello.inf"
"C:\Users\Kevin\HP scan KJC01\HP’s Spectre X360 13\SurfacePro_Win10_18362_20.081.13957.0.msi"
"C:\Users\Kevin\HP scan KJC01\HP’s Spectre X360 13\winbiosensoradapter.dll"
"C:\Users\Kevin\HP scan KJC01\HP’s Spectre X360 13\winbiostorageadapter.dll"
"C:\Users\Kevin\HP scan KJC01\HP’s Spectre X360 13\winbiovsmstorageadapter.dll"
"C:\Users\Kevin\HP scan KJC01\HP’s Spectre X360 13\winHellodownload (2020_08_13 21_04_34 UTC).cab"

**Comment by stephen-turner** [comment]
Doesn't appear to have anything to do with Docker Desktop, closing.
