### ISSUE TITLE
2.5.0.0 version of Docker, crashed crashed with new update

### ISSUE THREAD

**Issue by supriya-kotturu** [docker/for-win#9343]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 27DF325F-945D-42C8-8E1B-4A81D794B6A3/20201102180440

### Expected behavior
Docker should start on system restart after updating the docker version

### Actual behavior
Docker crashed and isnt running on start with an I/O error
WSL distro stopped while waiting for Lifecycle server.
  >Stdout:
⇨ http server started on /run/guest-services/wsl2-bootstrap-expose-ports.sock
⇨ http server started on /run/guest-services/wsl-cross-distro.sock
execing /sbin/init
getting children of 39
  >Stderr:
2020/11/02 18:04:38 resolving /mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-wsl-cli.iso...
2020/11/02 18:04:38 already in cache!
2020/11/02 18:04:38 resolving /mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-for-wsl.iso...
2020/11/02 18:04:38 already in cache!
time="2020-11-02T18:04:38Z" level=info msg="docker.tar is present in the cache"
time="2020-11-02T18:04:38Z" level=info msg="dialing Unix domain socket /run/guest-services/wsl2-expose-ports.sock for data connection"
time="2020-11-02T18:04:38Z" level=info msg="unable to connect data on Unix domain socket /run/guest-services/wsl2-expose-ports.sock: dial unix /run/guest-services/wsl2-expose-ports.sock: connect: no such file or directory. Is the server restarting? Will retry in 1s."
Error: input/output error
2020/11/02 18:04:38 input/output error

### Information

  - Windows Version: 10
        Edition: Windows 10 Home Single Language
        Version : 20H2
        OS build: 19042.610
        Experience: Windows Feature Experience Pack 120.2212.31.0

  - Docker Desktop Version: 2.5.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. update docker to the latest version
  2. docker should be registred in the start apps 
  3. restart the computer

**Comment by bugraderre** [comment]
I found a fix for it. Do the following:

1. The Docker error dialog pops up.
1. Click "Reset to factory defaults".

This will erase your pre-existing containers and images, but Docker will start up again.

**Comment by petersgiles** [comment]
> I found a fix for it. Do the following:
> 
> 1. The Docker error dialog pops up.
> 2. Click "Reset to factory defaults".
> 
> This will erase your pre-existing containers and images, but Docker will start up again.

This does not work for me.

- Clicked "Reset to factory defaults".
- I have restarted my machine.
- Uninstalled/Reinstalled Docker.

All to no avail.

**Comment by johan974** [comment]
Same here. Whatever I try, I cannot get Docker working again ... ;-(
