### ISSUE TITLE
Welcome window is too tall for my laptop screen

### ISSUE THREAD

**Issue by doxxx** [docker/for-win#935]
### Expected behavior

The Welcome window can be fully displayed.

### Actual behavior

The top and bottom of the Welcome window are cut off, mostly the titlebar and window controls at the top, making it difficult to interact with.

### Information

Docker:
Version 17.06.0-ce-win19 (12801)
Channel: stable
c98c1c2

OS:
Windows 10. Screen resolution is 1920x1080.

### Steps to reproduce the behavior

Start up Docker for the first time since a reboot.

**Comment by jasonbivins** [comment]
Hi @doxxx 

I can reproduce this, I'll go ahead and enter a bug report for it.  Do you mind if I go ahead and close this issue?

**Comment by doxxx** [comment]
Sure.

**Comment by jasonbivins** [comment]
@doxxx   do you happen to have a screenshot, or can you send me one next time you see this?

**Comment by doxxx** [comment]
It looks like I only get the Welcome window after an upgrade or fresh install?

**Comment by jasonbivins** [comment]
![image](https://user-images.githubusercontent.com/28021664/28487828-02f486d6-6e68-11e7-810d-aac989973667.png)

**Comment by MrChriZ** [comment]
Any update for this bug?  It's kind of annoying!
