### ISSUE TITLE
Proxy settings does not disable

### ISSUE THREAD

**Issue by GF-Huang** [docker/for-win#9357]
What the fuxk it still try to connect to the proxy???? I had apply and restart.

![image](https://user-images.githubusercontent.com/4510984/97987106-b4b77300-1e15-11eb-9254-e1d052b0884b.png)

### Information

  - Windows Version:

![image](https://user-images.githubusercontent.com/4510984/97987209-ddd80380-1e15-11eb-9760-bf942f32564b.png)

  - Docker Desktop Version:

![image](https://user-images.githubusercontent.com/4510984/97987146-c39e2580-1e15-11eb-89ed-8e6d0d47ccc4.png)

  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

No, desktop for windows linux container.

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by GF-Huang** [comment]
The stupid update waste my time.

**Comment by r-izumida** [comment]
I have the same problem.
You can disable it by turning on the toggle switch and emptying the proxy server settings. Apparently the toggle switch isn't working.

**Comment by stephen-turner** [comment]
This is fixed in the latest release, 3.1.0.
