### ISSUE TITLE
Docker keeps on crashing on my Windows client since this morning... If I am not mistaken, Docker update happen yesterday...  

### ISSUE THREAD

**Issue by cbezenco** [docker/for-win#9359]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by derekm** [comment]
Same here. Upgraded yesterday, Docker now won't start.

**Comment by zebak007** [comment]
Did a remove, reboot and reinstall and works back now...

**Comment by derekm** [comment]
@zebak007 -- A shutdown and reboot fixed it for me... I had already done a restart, but it was due to a crash rather than a successful shutdown. *shrugs*
