### ISSUE TITLE
Unable to create

### ISSUE THREAD

**Issue by cynion23** [docker/for-win#936]
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Invalid class "win32_operatingsystem"
at New-Switch, <No file>: line 118
at <ScriptBlock>, <No file>: line 385
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

**Comment by jasonbivins** [comment]
Hi @cynion23 
What version of Windows are you running Docker on?

**Comment by cynion23** [comment]
Windows 10 enterprise

**Comment by jasonbivins** [comment]
@cynion23   apologies, I should have been more specific - are you running Windows in 32bit or 64bit mode?  
Can  you post a diagnostic ID as well? You should have gotten one when you saw the error.

**Comment by cynion23** [comment]
I lost the first diagnostic ID when sending the crash report but here is a new one, OS is 64bit

9E3ABEE5-A11C-4F73-ACC6-5B165E0C1469/2017-07-19_15-36-29

**Comment by jasonbivins** [comment]
Hi @cynion23 It's failing when it creates the internal vswitch that we used.  Can you run this command manually and we'll see if we can get a more useful error?

New-VMSwitch -Name "DockerNAT" -SwitchType Internal

**Comment by Molson01** [comment]
I have been having the same issues so I tried the vm switch command (and verified it was created) but I'm still getting the same error (I think).  After each change I stop the Docker service and the Docker application before trying again.

> Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Inconsistent parameters PolicyStore PersistentStore and Dhcp Enabled
> 
> 
>    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
>    at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
>    at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
>    at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

**Comment by RebeccaOxfordUni** [comment]
I got the same error when Hyper-V was trying to create the VM on a Win10 64bit PC.  Rebuilding the WMI repository solved the problem.

**Comment by cmosguy** [comment]
@RebeccaOxfordUni i just hit this issue again and again.  What do you mean by 

> Rebuilding the WMI repository solved the problem.

I am have to keep restarting docker everytime this happens after I reboot my Windows 10 system.

**Comment by RebeccaOxfordUni** [comment]
I think I followed these instructions:

https://blogs.technet.microsoft.com/askperf/2014/08/08/wmi-repository-corruption-or-not/

Hope this solves your errors.

**Comment by jasonbivins** [comment]
Closing this - KB for this error is underway
resolution can be found here: https://blogs.technet.microsoft.com/askperf/2014/08/11/wmi-missing-or-failing-wmi-providers-or-invalid-wmi-class/
