### ISSUE TITLE
Updated to 2.5 and crashed with WSL2 during launch

### ISSUE THREAD

**Issue by nanke2yimeng** [docker/for-win#9361]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 07C37E76-96A9-4689-9C5F-35C9A27E0B0C/20201103141248

### Expected behavior
Normally start the docker desktop

### Actual behavior
Crashed with error: WSL distro stopped while waiting for Lifecycle server.

### Information

  - Windows Version: 1909 (Build 18363)
  - Docker Desktop Version: 2.5.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Update from version 2.4 to version 2.5 
  2. Finish update, crashed during the first launch
  4. Reset factory setting -> crashed
  3. Restart -> crashed

**Comment by x2decay** [comment]
I have the same issue
