### ISSUE TITLE
Official Centos6.10 Interactive Terminal Not Working WSL2

### ISSUE THREAD

**Issue by bubundas17** [docker/for-win#9362]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C362DFDC-ABD8-4D49-9689-39AEF1C60188/20201103152411

### Expected behavior
`docker run -it centos:centos6.10 bash`
It should bring up a interactive bash shell inside the centos 6.10 container.
### Actual behavior
`docker run -it centos:centos6.10 bash`
Nothing is coming up.
![image](https://user-images.githubusercontent.com/26280146/98005844-8470d400-1e17-11eb-9422-c9c0c71683af.png)
### Information

Hi, 
I am trying to open a interactive shell inside official centos6.10 image. 
But for some reason, it didn't worked on my windows 10 machine.

I am currently using WSL2 based docker engine because it allows me to directly call docker from VS Code Running in Remote WSL mode.

All other images working as it should. But don't know why centos6.10 image giving this problem.

I have also tried switching to Hyper-V Based engine, and in that case, it worked just fine.

Sorry I do not have any other PC except this to check if the problem persist on that machine as well.

  - Windows Version:  Latest
  - Docker Desktop Version: Latest
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: NO

### Steps to reproduce the behavior

  1. Make Sure Docker is running with WSL 2 based engine.
  2. run `docker run -it centos:centos6.10 bash`
  3. And see what happens. If the bug exist in WSL2 the output should look like:
![image](https://user-images.githubusercontent.com/26280146/98007331-44aaec00-1e19-11eb-81f9-0cb9809bcead.png)
And also as you can see, Centos 7 image is working just fine.

**Comment by stephen-turner** [comment]
Thanks for the report, @bubundas17. I think this is probably this WSL issue: microsoft/WSL#4964. Could you try the workaround at https://github.com/microsoft/WSL/issues/4694#issuecomment-556095344 ?

**Comment by bubundas17** [comment]
@stephen-turner Yes it totally solved the problem!
Now, Centos 6 is working just fine.

Thanks for helping!

**Comment by stephen-turner** [comment]
Great, thanks for letting us know!
