### ISSUE TITLE
WSL distro stopped while waiting for Lifecycle server.

### ISSUE THREAD

**Issue by afonsoft** [docker/for-win#9363]
7BC53A6E-C3BB-425A-8AFC-B6CF00D258EC/20201103155918

WSL distro stopped while waiting for Lifecycle server.
  >Stdout:

  >Stderr:
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:838
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:943
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).Execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:883
main.main
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:28
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374
rootfs mountiso version-pack
main.setupRootFS
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:353
main.doRun
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:231
main.run.func1
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:86
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:838
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:943
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).Execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:883
main.main
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:28
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374

[log.txt](https://github.com/docker/for-win/files/5482519/log.txt)

**Comment by afonsoft** [comment]
[20201103171751.zip](https://github.com/docker/for-win/files/5483014/20201103171751.zip)

Version: 2.5.0.0 (49427)
Channel: stable
Sha1: 5c95a8b8cd4946c973adf2fb8aafb4d11fe81849
Started on: 2020/11/03 14:16:21.342
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 2009
Build: 19042
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406

**Comment by idevmans** [comment]
For me work if you remove (manual created file) .wslconfig in your home windows dir `%UserProfile%`
