### ISSUE TITLE
Quitting Docker for Windows will mess with mounted VHDX-files

### ISSUE THREAD

**Issue by ad-on-is** [docker/for-win#9364]
## Steps to reproduce,

**1. Start Docker for Windows**

**2. Attach and mount a VHDX to WSL**

```powershell
Mount-VHD -Path "D:\path\to\data.vhdx" #attach VHD
wsl --mount \\.\PHYSICALDRIVE5 -p 5 #mount VHD partition to WSL
```
Partition successfully mounted and accessible under `/mnt/wsl/PHYSICALDRIVE5/` showing `lost+found` and other directories

**3. Stop Docker for Windows**

**4. Folder `/mnt/wsl/PHYSICALDRIVE5/`** still exists, but all subfolders like `lost+found` are gone, which indicates that it has been unmounted.

## System
Windows 20246
Docker 2.5.0.0 (49427)

**Comment by stephen-turner** [comment]
@ad-on-is I think this is explained by https://github.com/docker/for-win/issues/9116#issuecomment-712115097

**Comment by ad-on-is** [comment]
@stephen-turner aah, I see.. but I still don't get, why the folder gets unmounted when quitting Docker. In that case, I'd expect that all mnt/wsl/docker-* folders get unmounted, but everything else should stay untouched.

**Comment by stephen-turner** [comment]
I'm not 100% sure of the lifecycle, but maybe that's when the last active distro goes away so WSL cleans up?

**Comment by ad-on-is** [comment]
Hmmm... that can't be the case, since I have Ubuntu running all the time in Windows Terminal.

**Comment by stephen-turner** [comment]
Hmmm, @simonferquel do you have an explanation?

**Comment by simonferquel** [comment]
No, I'll need to play a little bit with mounts on my insider machine

**Comment by simonferquel** [comment]
I reproduced and identified the root cause.
The partition is mounted with shared propagation into /mnt/wsl/something. On stopping docker desktop, we try to be a good citizen and cleanly unmount everything that is part of our Linuxkit distro environment (and as we mount /mnt/wsl in recursive mount, that means that we unmount /mnt/wsl/PHYSICALDRIVE1p1). As propagation is shared, the unmount is propagated to all other distros.

I'll see what happens if we don't cleanly unmount before shutting down our distro.

**Comment by ad-on-is** [comment]
Glad to hear, that it's reproducible. Now that we can moun't VHD files into WSL, it's much more of a secure way to have sensitive data (like project files) on a separate mount, in case a distro fails or whatever. And this issue really disturbs the workflow, especially when the linux-user-home-folder is within that mount.

**Comment by simonferquel** [comment]
I'll have a private build later today that you can play with.
It is a shame that the feature did not exist previously, we would have leveraged that instead of creating the `docker-desktop-data` data keeping distro

**Comment by ad-on-is** [comment]
Sure, I'm gladly willing to test. Is there anything else I should watch out for, just to make sure everything behaves as expected?

>> It is a shame that the feature did not exist previously

Yeah, I agree on that. It should've been introduced since the beginning, but it is how it is.

**Comment by simonferquel** [comment]
Things to test thourougly:
- Do bind mounts behave correctly (And if using containers with auto-restart, do they restore correctly)
- Looking at the evolution of /proc/self/mountinfo when restarting docker-desktop multiple times (making sure things don't get messier and messier)

**Comment by simonferquel** [comment]
(we'll do it on our side, but if you want to have a look at it, it would help :))
