### ISSUE TITLE
Docker 2.5.0 - Failed to deploy distro docker-desktop to C:\Users\Administrator\AppData\Local\Docker\wsl\distro: exit code: -1

### ISSUE THREAD

**Issue by jefflks** [docker/for-win#9368]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ Yes ] I have uploaded Diagnostics
  - Diagnostics ID:B1199D0D-CC59-4CE3-8505-DA912C0C5CD7/20201103185426

### Information

  - Windows Version: Windows 10 Pro Version 1909 (OS Build 18363.1139)
  - Docker Desktop Version: Docker Desktop 2.5.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Install Docker Desktop 2.5.0 on Windows 10 Pro Version 1909 (OS Build 18363.1139)
  2. ...

**Comment by nconder** [comment]
Im having the exact same issue and I tried "Rest to factory default".

**Comment by jefflks** [comment]
> /lifecycle frozen
