### ISSUE TITLE
docker desktop wsl distro stopped

### ISSUE THREAD

**Issue by zhangmx** [docker/for-win#9385]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: forget it....

### Expected behavior

Do update.
Run docker normally.

### Actual behavior

After update, docker could not run.

### Information

  - Windows Version: Win10 professional
  - Docker Desktop Version: 2.5.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

with WSL 2. Ubuntu 20.04

### Steps to reproduce the behavior

  1. follow the update notice do update. 
  2. after update finished. it show 'docker desktop wsl distro stopped'. and then goto this issue page.

---

I try restart my computer OR follow the tips reset docker. That all not work.

Fortunately I got an old version 2.3 ‘Docher Desktop Installer.exe' file. Uninstall 2.5, then 2.3 run normally.

Why docker home page or here not support history release version download?

**Comment by STaRDoGG** [comment]
Amazing post ....
