### ISSUE TITLE
Docker Desktop WSL distro stopped

### ISSUE THREAD

**Issue by adthonb** [docker/for-win#9388]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A38049F0-E73E-4D5E-8F1A-34756F5B3803/20201104115612

### Expected behavior
Docker Desktop starts up
### Actual behavior
Docker Desktop crashes when trying to start up
### Information
  - Windows Version: 10.0.19041 Build 19041
  - Docker Desktop Version: 2.5.0.0 (49427)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Yes, WSL2

### Steps to reproduce the behavior
  1. Update Docker Desktop to the latest stable.
  2. Reboot Windows
  3. Docker Desktop starting and crashed

**Comment by xe-nvdk** [comment]
Same scenario, same results.

**Comment by xe-nvdk** [comment]
```
WSL distro stopped while waiting for Lifecycle server.
  >Stdout:

  >Stderr:
2020/11/04 15:38:22 resolving /mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-wsl-cli.iso...
Error: mounting wslCLIDest: stat /mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-wsl-cli.iso: no such file or directory
2020/11/04 15:38:22 stat /mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-wsl-cli.iso: no such file or directory
mounting wslCLIDest
main.doRun
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:226
main.run.func1
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:86
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:838
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:943
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).Execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:883
main.main
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:28
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374
```
63E3046E-C601-4B64-B199-CB6313FE607F/20201104153825

**Comment by cimchd** [comment]
Same problem here with wsl2 distro. After update to 2.5.0.0 and a windows reboot Docker Desktop started but did not succeed. After deinstallation and reinstall it worked until the next windows reboot.

**Comment by borysl** [comment]
I've got the same problem
diagnostic id is 47808FB1-FE71-4DFF-BC36-FCEC7102A07D/20201222074503
