### ISSUE TITLE
Upgrading Docker for Windows removes Docker info from Windows registry

### ISSUE THREAD

**Issue by sgreenmsft** [docker/for-win#939]
Installing Docker for Windows using InstallDocker.msi places information in the Windows registry under HKLM\SOFTWARE\Docker Inc.\Docker.

Unfortunately, when a new version of Docker for Windows is released and the upgrade installation is run, that information is removed from the registry.

Steps to Reproduce:
1) Install an old version of Docker for Windows (for example: https://download.docker.com/win/stable/12627/InstallDocker.msi)
2) Using regedit, confirm that the installation placed information in the registry under HKLM\SOFTWARE\Docker Inc.\Docker.
3) Now launch Docker for Windows. It will tell you that a new version is available.  Click through this UI to upgrade Docker for Windows.
4) Using regedit, confirm that the upgrade removed the information from the registry under HKLM\SOFTWARE\Docker Inc.\Docker.

This impacts applications that rely on this information in the Windows registry.

**Comment by friism** [comment]
The presence or non-presence of keys in the Windows registry is not a public interface of Docker, so apps shouldn't rely on it.

Do you have more details on what app fails? The best way to check whether Docker is running on a Windows system is checking for presence of the `docker_engine` named pipe.

**Comment by sgreenmsft** [comment]
Visual Studio 2017 (version 15.3) takes a dependency on this registry information to determine whether Docker for Windows is installed.

**Comment by friism** [comment]
@sgreenmsft ok, understood - @ebriney did we make a change for this? If so, can we still maintain that reg key for backwards compat?

**Comment by ebriney** [comment]
I didn't know about that but with the new installer this has been moved in
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Docker for Windows`

I can add it on the old place to fix this issue or you can also rely on the new key, WDYT?

**Comment by sgreenmsft** [comment]
@ebriney - Shipped versions of Visual Studio 2017 rely on the values in HKLM\SOFTWARE\Docker Inc.\Docker.  To ensure the best experience for our customers, our preference would be for Docker installer to continue to leave the registry keys in that location.

**Comment by friism** [comment]
@sgreenmsft we'll release a patch that fixes this

**Comment by sgreenmsft** [comment]
Thank you. Much appreciated.
