### ISSUE TITLE
No puede iniciar docker

### ISSUE THREAD

**Issue by bytewareteam** [docker/for-win#9390]
Hace unos pocos días, docker me informó de una actualización, después de actualizar funcionó bien, sin embargo luego de reiniciar el equipo, docker no pudo iniciar. Pensé que era un error al momento de instalar la actualización por lo que procedí a desinstalar docker, descargarlo e instalarlo nuevamente, y al abrir la aplicación salió este error

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3B5B64C2-DCCA-425B-8642-DE31B6C6802F/20201104155547

### Expected behavior
Solo quiero ejecutar docker en windows, es mi equipo de desarrollo corporativo.

### Actual behavior
Al iniciar docker surge un error 

```
Failed to deploy distro docker-desktop to C:\Users\PC\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Error en la ejecución de servidor
```

### Information

  - Windows Version: 10 Pro
  - Docker Desktop Version: Docker Desktop Stable
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

**Comment by MiguelangelMo** [comment]
Tengo el mismo error, y aun no he conseguido la solucionarlo, si consigues alguna pista me avisas por favor. Ocurrió similar me pidió actualización y al actualizarme me sale lo siguiente error.
System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\usuario\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Error en la ejecución de servidor
