### ISSUE TITLE
This is still an issue, please reopen

### ISSUE THREAD

**Issue by RlingWork** [docker/for-win#9395]
Closed issues are locked after 30 days of inactivity.
This helps our team focus on active issues.

If you have found a problem that seems similar to this, please open a new issue.

Send feedback to Docker Community Slack channels #docker-for-mac or #docker-for-windows.
/lifecycle locked

_Originally posted by @docker-desktop-robot in https://github.com/docker/for-win/issues/4656#issuecomment-656453345_

**Comment by stephen-turner** [comment]
What is still an issue? #4656? The original reporter closed that ticket over a year ago.

**Comment by RlingWork** [comment]
Hi Stephen

Yes, issue #4656 is still an issue ☹

Every time I try to update docker, the process fails (mostly complaining that docker is running – which it has to for the installation to run!) and docker is uninstalled. I have to download and reinstall docker every time there is an update.

/Rling

Fra: Stephen Turner <notifications@github.com>
Sendt: 5. november 2020 11:06
Til: docker/for-win <for-win@noreply.github.com>
Cc: Erling Otto <eot@idconnect.dk>; Author <author@noreply.github.com>
Emne: Re: [docker/for-win] This is still an issue, please reopen (#9395)


What is still an issue? #4656<https://github.com/docker/for-win/issues/4656>? The original reporter closed that ticket over a year ago.

**Comment by stephen-turner** [comment]
Thanks. I'll leave this ticket open, but we are in the middle of rewriting our update code, so hopefully the problem will go away at that point.

**Comment by RlingWork** [comment]
Thanks Stephen 😊 Looking forward to your update (y)

/Rling

Fra: Stephen Turner <notifications@github.com>
Sendt: 6. november 2020 11:15
Til: docker/for-win <for-win@noreply.github.com>
Cc: Erling Otto <eot@idconnect.dk>; Author <author@noreply.github.com>
Emne: Re: [docker/for-win] This is still an issue, please reopen (#9395)


Thanks. I'll leave this ticket open, but we are in the middle of rewriting our update code, so hopefully the problem will go away at that point.
