### ISSUE TITLE
Container stops working after 30 minutes

### ISSUE THREAD

**Issue by muminasaad** [docker/for-win#9399]
I am deploying docker on one of my clients environment over Windows Server 2019.
Enabled virtualization, containers and HyperV for switch creation.
But the docker container stops working after 30 minutes even without any load or work on it.

I am using Docker EE 19.03.12 on the server.

and I have these following errors:
---------------------------------------------------------------------------------------
Version=1
EventType=BEX64
EventTime=132490313781397181
ReportType=2
Consent=1
UploadTime=132490396010675088
ReportStatus=4198
ReportIdentifier=ad74ca0d-a88d-43e9-b178-723ef6b7f1f4
IntegratorReportIdentifier=8a0f6f46-05b8-46ab-bbe2-a0f7ea506e97
Wow64Host=34404
NsAppName=vmcompute.exe
OriginalFilename=vmcompute.exe
AppSessionGuid=00001a0c-0000-0011-36ed-24d938b3d601
TargetAppId=W:0000f519feec486de87ed73cb92d3cac802400000000!00001518f3cb2bbfa20037f5ff83815550c940363377!vmcompute.exe
TargetAppVer=2028//12//10:17:56:36!3362bd!vmcompute.exe
BootId=4294967295
TargetAsId=2082
IsFatal=1
EtwNonCollectReason=1
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=vmcompute.exe
Sig[1].Name=Application Version
Sig[1].Value=10.0.17763.1217
Sig[2].Name=Application Timestamp
Sig[2].Value=6edea054
Sig[3].Name=Fault Module Name
Sig[3].Value=ntdll.dll
Sig[4].Name=Fault Module Version
Sig[4].Value=10.0.17763.1192
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=5854f5da
Sig[6].Name=Exception Offset
Sig[6].Value=00000000000a4740
Sig[7].Name=Exception Code
Sig[7].Value=c0000409
Sig[8].Name=Exception Data
Sig[8].Value=000000000000000a
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.17763.2.0.0.272.7
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=803d
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=803d51a048d13ed597ff94fe6ba3464e
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=803d
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=803d51a048d13ed597ff94fe6ba3464e
UI[2]=C:\Windows\system32\vmcompute.exe
UI[5]=Check online for a solution (recommended)
UI[6]=Check for a solution later (recommended)
UI[7]=Close
UI[8]=Hyper-V Host Compute Service stopped working and was closed
UI[9]=A problem caused the application to stop working correctly. Windows will notify you if a solution is available.
UI[10]=&Close
LoadedModule[0]=C:\Windows\system32\vmcompute.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\System32\KERNEL32.DLL
LoadedModule[3]=C:\Windows\System32\KERNELBASE.dll
LoadedModule[4]=C:\Windows\System32\ucrtbase.dll
LoadedModule[5]=C:\Windows\System32\advapi32.dll
LoadedModule[6]=C:\Windows\System32\msvcrt.dll
LoadedModule[7]=C:\Windows\System32\sechost.dll
LoadedModule[8]=C:\Windows\System32\RPCRT4.dll
LoadedModule[9]=C:\Windows\System32\combase.dll
LoadedModule[10]=C:\Windows\System32\bcryptPrimitives.dll
LoadedModule[11]=C:\Windows\System32\shcore.dll
LoadedModule[12]=C:\Windows\System32\CRYPT32.dll
LoadedModule[13]=C:\Windows\SYSTEM32\ntmarta.dll
LoadedModule[14]=C:\Windows\system32\vmsif.dll
LoadedModule[15]=C:\Windows\System32\MSASN1.dll
LoadedModule[16]=C:\Windows\system32\NetSetupApi.dll
LoadedModule[17]=C:\Windows\system32\HvSocket.dll
LoadedModule[18]=C:\Windows\System32\OLEAUT32.dll
LoadedModule[19]=C:\Windows\system32\wevtapi.dll
LoadedModule[20]=C:\Windows\System32\cfgmgr32.dll
LoadedModule[21]=C:\Windows\System32\msvcp_win.dll
LoadedModule[22]=C:\Windows\System32\bcrypt.dll
LoadedModule[23]=C:\Windows\system32\DEVOBJ.dll
LoadedModule[24]=C:\Windows\System32\WS2_32.dll
LoadedModule[25]=C:\Windows\system32\fwpuclnt.dll
LoadedModule[26]=C:\Windows\system32\IPHLPAPI.DLL
LoadedModule[27]=C:\Windows\system32\MPR.dll
LoadedModule[28]=C:\Windows\system32\XmlLite.dll
LoadedModule[29]=C:\Windows\system32\USERENV.dll
LoadedModule[30]=C:\Windows\system32\FLTLIB.DLL
LoadedModule[31]=C:\Windows\System32\profapi.dll
LoadedModule[32]=C:\Windows\system32\CRYPTBASE.DLL
LoadedModule[33]=C:\Windows\System32\kernel.appcore.dll
LoadedModule[34]=C:\Windows\system32\vid.dll
LoadedModule[35]=C:\Windows\system32\CCGLaunchPad.dll
LoadedModule[36]=C:\Windows\system32\SspiCli.dll
LoadedModule[37]=C:\Windows\system32\vmprox.dll
LoadedModule[38]=C:\Windows\system32\vmwpctrl.dll
LoadedModule[39]=C:\Windows\system32\container.dll
LoadedModule[40]=C:\Windows\System32\NSI.dll
LoadedModule[41]=C:\Windows\System32\clbcatq.dll
LoadedModule[42]=C:\Windows\System32\hnsproxy.dll
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=17763
OsInfo[3].Key=ubr
OsInfo[3].Value=1217
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=1033
OsInfo[7].Key=geoid
OsInfo[7].Value=244
OsInfo[8].Key=sku
OsInfo[8].Value=7
OsInfo[9].Key=domain
OsInfo[9].Value=1
OsInfo[10].Key=prodsuite
OsInfo[10].Value=272
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=3
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=95650
OsInfo[15].Key=osinsty
OsInfo[15].Value=2
OsInfo[16].Key=iever
OsInfo[16].Value=11.1217.17763.0-11.0.190
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=32768
OsInfo[19].Key=svolsz
OsInfo[19].Value=99
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=180914
OsInfo[22].Key=bldtm
OsInfo[22].Value=1434
OsInfo[23].Key=bldbrch
OsInfo[23].Value=rs5_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.17763.1217.amd64fre.rs5_release.180914-1434
OsInfo[30].Key=buildflightid
OsInfo[31].Key=edition
OsInfo[31].Value=ServerStandard
OsInfo[32].Key=ring
OsInfo[32].Value=Retail
OsInfo[33].Key=expid
OsInfo[34].Key=containerid
OsInfo[35].Key=containertype
OsInfo[36].Key=edu
OsInfo[36].Value=0
File[0].CabName=WERInternalMetadata.xml
File[0].Path=WERF3A6.tmp.WERInternalMetadata.xml
File[0].Flags=327683
File[0].Type=5
File[0].Original.Path=\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF3A6.tmp.WERInternalMetadata.xml
FriendlyEventName=Stopped working
ConsentKey=BEX64
AppName=Hyper-V Host Compute Service
AppPath=C:\Windows\system32\vmcompute.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=CCBBCA4BB59120521077C6C4E7F2E863
MetadataHash=1635700556
---------------------------------------------------------------------------------------
Faulting application name: vmcompute.exe, version: 10.0.17763.1217, time stamp: 0x6edea054
Faulting module name: ntdll.dll, version: 10.0.17763.1192, time stamp: 0x5854f5da
Exception code: 0xc0000409
Fault offset: 0x00000000000a4740
Faulting process id: 0x1e14
Faulting application start time: 0x01d6b3499cb81ed0
Faulting application path: C:\Windows\system32\vmcompute.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 12963604-73ef-4026-8f0e-94592af87b28
Faulting package full name: 
Faulting package-relative application ID: 
---------------------------------------------------------------------------------------
failed wait [error=hcsshim::Process::waitBackground 86c67fae917246296fb63bbc2f39fba682ec1fac4cc2a29f6766e2cbb70bfe98:7884: lost communication with compute service traceID=127239cae9dca6cb6afe7aad2c302399 spanID=dc7f26fd89344c91]
---------------------------------------------------------------------------------------
Wait() failed (container may have been killed) [module=libcontainerd namespace=moby container=86c67fae917246296fb63bbc2f39fba682ec1fac4cc2a29f6766e2cbb70bfe98 process=init error=process 7884 in container 86c67fae917246296fb63bbc2f39fba682ec1fac4cc2a29f6766e2cbb70bfe98 encountered an error during hcsshim::Process::waitBackground: lost communication with compute service]
---------------------------------------------------------------------------------------
unable to get exit code for process [namespace=moby container=86c67fae917246296fb63bbc2f39fba682ec1fac4cc2a29f6766e2cbb70bfe98 process=init module=libcontainerd error=process 7884 in container 86c67fae917246296fb63bbc2f39fba682ec1fac4cc2a29f6766e2cbb70bfe98 encountered an error during hcsshim::Process::waitBackground: lost communication with compute service]
---------------------------------------------------------------------------------------
failed to shutdown container, and subsequent terminate also failed [namespace=moby error=container 86c67fae917246296fb63bbc2f39fba682ec1fac4cc2a29f6766e2cbb70bfe98 encountered an error during hcsshim::System::Terminate: failure in a Windows system call: The remote procedure call failed and did not execute. (0x6bf) module=libcontainerd container=86c67fae917246296fb63bbc2f39fba682ec1fac4cc2a29f6766e2cbb70bfe98]
---------------------------------------------------------------------------------------
failed to shutdown container [module=libcontainerd namespace=moby container=86c67fae917246296fb63bbc2f39fba682ec1fac4cc2a29f6766e2cbb70bfe98 process=init error=container 86c67fae917246296fb63bbc2f39fba682ec1fac4cc2a29f6766e2cbb70bfe98 encountered an error during hcsshim::System::Shutdown: failure in a Windows system call: The remote procedure call failed and did not execute. (0x6bf): subsequent terminate failed container 86c67fae917246296fb63bbc2f39fba682ec1fac4cc2a29f6766e2cbb70bfe98 encountered an error during hcsshim::System::Terminate: failure in a Windows system call: The remote procedure call failed and did not execute. (0x6bf)]
---------------------------------------------------------------------------------------
sending event [module=libcontainerd namespace=moby container=86c67fae917246296fb63bbc2f39fba682ec1fac4cc2a29f6766e2cbb70bfe98 event=exit event-info={86c67fae917246296fb63bbc2f39fba682ec1fac4cc2a29f6766e2cbb70bfe98 init 7884 4294967295 2020-11-05 00:29:38.6217772 -0800 PST m=+33566.461613101 false failed to shutdown container: container 86c67fae917246296fb63bbc2f39fba682ec1fac4cc2a29f6766e2cbb70bfe98 encountered an error during hcsshim::System::Shutdown: failure in a Windows system call: The remote procedure call failed and did not execute. (0x6bf): subsequent terminate failed container 86c67fae917246296fb63bbc2f39fba682ec1fac4cc2a29f6766e2cbb70bfe98 encountered an error during hcsshim::System::Terminate: failure in a Windows system call: The remote procedure call failed and did not execute. (0x6bf)}]

**Comment by muminasaad** [comment]
I think this is related to #5770

**Comment by mjkkirschner** [comment]
@muminasaad I am seeing similar events with a similar setup - the container crashes for me around the 25 minute mark. Running a nested virtualization scenario.

I see logs like:
```
failed wait [spanID=d79fa21a480010a2 traceID=2e0be980e555be75d9d0d820545d0e90 error=hcsshim::Process::waitBackground 5a2df603f45804a35cdcccf72bffd0d75735fd2ca1555698b1306a75a9275b5d:1776: lost communication with compute service]
```

were you able to resolve this?

**Comment by muminasaad** [comment]
@mjkkirschner  
Sadly no, i am still working on it, I think it is related to VMSphere. compatibility issue.

**Comment by mjkkirschner** [comment]
I can’t confirm 100% but it’s looking promising after updating VMware tools from 11.0.5 to 11.0.6.

**Comment by muminasaad** [comment]
@mjkkirschner  
I agree, but sadly I was disappointed of docker support and compatibility with windows server 
it feels they support windows 10 more that windows server
