### ISSUE TITLE
Error response from daemon: Get https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp 127.0.0.1:8080: connect: connection refused

### ISSUE THREAD

**Issue by sdaaish** [docker/for-win#9400]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker pull should result in pulling an image from dockerhub. It should not use a proxy when the checkbox for proxy is not enabled, ie not set to "Manual proxy configuration"

### Actual behavior
docker pull results in `Error response from daemon: Get https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp 127.0.0.1:8080: connect: connection refused` when I try to pull an image.

### Information
After upgrade to version 2.5.0.0.49427 of Docker Desktop, Docker version 19.03.13, I get the message `Error response from daemon: Get https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp 127.0.0.1:8080: connect: connection refused` when I try to pull an image.

The error message indicates that there is a problem with a proxy on localhost. The settings for proxy is to *not* use a proxy, ie the checkbox for _Manual proxy_ is not checked. Docker still uses a proxy when it's not supposed to.

This is behind a corporate network that uses a *transparent* proxy but *also* have an explicit proxy. The OS and applications don't have to use a proxy and Docker is expected to work the same way. But it sets the proxy setting to localhost which is not working.

As a comparison a browser that has no proxy explicitly set works just fine. And so did docker before the upgrade.

By actually changing the proxy-setting for *Manual proxy* to the correct address for the corporate explicit proxy, docker starts working again.

### Steps to reproduce the behavior
- Upgrade Docker desktop, clear out image for docker-desktop and docker-desktop-data in WSL.
- Leave settings for proxy in docker as default, manual is not enabled.
- Try to pull an image.

### Solution
Set a proxy explicitly in docker and `docker pull` starts working.

### The real problem
The real problem here is when you **can** connect to _registry-1.docker.io_ **both** with and without a proxy in the browser, docker sets an incorrect proxy and don't use the correct values from eg WPAD or the system ( no proxy).

So there is something fishy with the proxysetting mechanism in docker desktop.

The error message is also confusing, what host is actually `localhost` when you run docker in Windows with WSL and have Hyper-V installed? If it is Windows, then it is docker that runs the proxy and why would it do that? And why does it fail then?

**Comment by AmirShitrit** [comment]
Which proxy did you end up setting explicitly?

**Comment by sdaaish** [comment]
I didn't setup a proxy since I don't need one. It seems that if I add a proxy in the settings and  then disable the setting it's still there. The trick is to enable proxy, add anything as proxy end then remove it again before disabling it again.

I have not verified this but could possibly try to do this sometime. I was just glad I resolved the issue and wanted to put this info here to make it a searchable solution.

**Comment by sdaaish** [comment]
So I had some time over and tried this out. `dk` is just an alias for `docker`

If I add a proxy without port, and do a docker pull, I get
```
dk pull mcr.microsoft.com/powershell
Using default tag: latest
Error response from daemon: Get https://mcr.microsoft.com/v2/: unexpected EOF
```
This is supposed to fail since I don't have the right port.

If I add a proxy with the correct port I get this.
```
 dk pull mcr.microsoft.com/powershell
Using default tag: latest
Error response from daemon: Get https://mcr.microsoft.com/v2/: Found
```
If I leave the text in the proxy settings and disable it I get the same message.

If I use curl with the same proxy settings (redacted), just to test that the proxy works, I get
```
$ env https_proxy="http://proxy.example.com:8080" curl "https://mcr.microsoft.com/v2/"
curl: (56) Received HTTP code 302 from proxy after CONNECT
```

If I enable proxy again in docker, remove all text and disable it I get this:
```
dk pull mcr.microsoft.com/powershell
Using default tag: latest
latest: Pulling from powershell
Digest: sha256:e5fd412f741be3eaab244635f73bbec9b44f4546f3182b4cc5fa9dc90360b1b8
Status: Image is up to date for mcr.microsoft.com/powershell:latest
mcr.microsoft.com/powershell:latest
```
I add the text `proxy.example.com:8080` or `http://proxy.example.com:8080` in docker to get the message above. 
If I add `"http://proxy.example.com:8080"` with the quotes I get:
```
dk pull mcr.microsoft.com/powershell
Using default tag: latest
Error response from daemon: Get https://mcr.microsoft.com/v2/: proxyconnect tcp: dial tcp: lookup "http: no such host
```

So I don't think the proxy settings works at all. At least for me on Windows 10.

To replicate this you should enable the proxy setting, add random stuff that definitely won't work, and then disable the proxy (leave the text). The settings will still be used.

**Comment by AmirShitrit** [comment]
I had to reinstall Docker Desktop :-( but at least it works now.

**Comment by sztan** [comment]
"By actually changing the proxy-setting for _Manual proxy_ to the correct address for the corporate explicit proxy, docker starts working again."

Indeed I too had to enable a proxy to none (leave the fields empty) to make i t work again (because I switched from work to home context and didn't want to use my VPN)

It seems that docker had kept my last used proxy configuration from the system...

**Comment by fc-smohr** [comment]
same problem for me, with empty fields and active proxy its working now, thanks @sztan

**Comment by cyberpunk2020s** [comment]
The same thing happened to me. 
I was wondering if it was my proxy server's setting since the URL promoted in the console was similar to my proxy server.
Just go to Settings - > Resources -> Proxies to enable Manual proxy configuration and empty the (Secure) Web Server.
It works finally.
Appreciate for ur share!
