### ISSUE TITLE
Windows alert links to unhelpful page

### ISSUE THREAD

**Issue by jkellyinsf** [docker/for-win#9406]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

I'm running Windows 10, IntelliJ, and WSL2.  During an Intellij build this message pops up:

![image](https://user-images.githubusercontent.com/2245532/98260452-330c3600-1f38-11eb-8cb3-30fbbcafa9b0.png)

I don't know what file it's referring to or what it means to "share" it.  But I click on the message for more details.

### Expected behavior

I expect to go to a page that gives more context around the error message, including what "sharing" means, how to figure out what file caused the message, and whether I should care.

### Actual behavior

The [page that comes up](https://docs.docker.com/docker-for-windows/wsl/#develop-with-docker-and-wsl-2) gives only some general info about how to launch VSCode from WSL.

### Information

  - Windows Version: 10
  - Docker Desktop Version: 2.4.0.0 (48506)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

**Comment by brunorafaeI** [comment]
this message refers to the volume you specified when starting your container, it is the normal message by windows, take at look in https://docs.microsoft.com/en-us/windows/wsl/compare-versions

`We recommend that you have your code in your default Linux distribution for the best development experience using Docker and WSL 2`

**Comment by stephen-turner** [comment]
The "Best Practices" section at the top of that page is supposed to explain the message.
