### ISSUE TITLE
Colored tray icon windows based on container statuses

### ISSUE THREAD

**Issue by jansor** [docker/for-win#9412]
Hi, this is only suggestion/ idea.

I think it would be easy and interesting to see a colored whale icon in the tray.
example:
- Green icon: When all Containers are up and running
- Orange icon: When some containers are not started 
- Red Icon: When container is down, but following the config it should start always.
- White Icon: When no containers are configured, or no config is found/set

This could be very easy and useful to see information like this.
Maybe other people can add suggestion or upvote this for implementation.

**Comment by stephen-turner** [comment]
Thanks for the idea. We do already use colour on the whale icon: red means that the docker engine failed to run or stopped unexpectedly. I think we'd prefer to keep colour for system status rather than container status (stopped containers is not an error state).
