### ISSUE TITLE
Live reload not working due to file changes not being detected.

### ISSUE THREAD

**Issue by DMoreira97** [docker/for-win#9426]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 28D41B5F-0BE2-4D32-85B9-2446F3B37962/20201106174956

### Expected behavior
The expected behavior would be to change a file and see the terminal (powershell) restart the container with the new changes made.

### Actual behavior
Independently of the file I change the terminal does not show any sign of recognizing these changes. But if I restart the container in the docker desktop GUI it does assume the new changes.

### Information
- This problem exists since the beginning of the instalation.

  - Windows Version: Windows 10 Home (OS Build 19041.572)
  - Docker Desktop Version: 2.5.0.0 (49427) stable
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Just follow these steps: https://docs.docker.com/docker-for-windows/install/ , on Windows 10 Home edition.

**Comment by stephen-turner** [comment]
Are you keeping your files in the Windows filesystem or the Linux filesystem? If the former, then this is expected. See https://docs.docker.com/docker-for-windows/wsl/

**Comment by DMoreira97** [comment]
Thank you for the fast reply @stephen-turner . I'm keeping the source code in the Windows file system. I really need live reload to work on this project so how do I change my source code to the Linux filesystem? As I'm in windows and only have a Ubuntu terminal I know I can clone the code there but then I wouldn't be able to edit it in VS code, right?

**Comment by DMoreira97** [comment]
Ok I can still open VS Code having the repository cloned in Ubuntu, which really surprises me. And live reload already is working 😄  But I use Gitkraken and I'm now wondering if it's possible to open the repository in Ubuntu with the Gitkraken in Windows...

**Comment by DMoreira97** [comment]
Well once I enabled filesharing on the folder explorer it was possible to open the repository from Gitkraken. So everything is working fine now.

**Comment by stephen-turner** [comment]
Great, glad you figured it out.
