### ISSUE TITLE
Docker times out trying to start lifecycle-server after update to 2.4.2-Edge

### ISSUE THREAD

**Issue by rishu73** [docker/for-win#9427]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 311B3CF9-CF91-4245-80C6-18BFBDCBF9D4/20201106195727

### Expected behavior
Docker should start - it did prior to updating.
### Actual behavior
Docker stays in "Starting" state then times out after 10 minutes
### Information
  - Is it reproducible?
On my system, yes.
  - Is the problem new?
Stable 2.3.0.5 did not have this issue. Updating to Stable 2.4.0, Stable 2.5.0 and Edge 2.4.2 does
  - Did the problem appear with an update?
Yes
  - Windows Version:
Windows 10 Version 2004 (OS Build 19041.450)
  - Docker Desktop Version:
Edge 2.4.2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
No

Attached diagnostics from command-line and log of recent run.
[log.txt](https://github.com/docker/for-win/files/5503282/log.txt)
[20201106195727.zip](https://github.com/docker/for-win/files/5503268/20201106195727.zip)

### Steps to reproduce the behavior
Start Docker for Windows. Wait.

**Comment by Kryptoxic** [comment]
Same issue here. Attached my logfiles and also following the issue

[log.txt](https://github.com/docker/for-win/files/5506866/log.txt)
[20201108165856.zip](https://github.com/docker/for-win/files/5506869/20201108165856.zip)
