### ISSUE TITLE
Failed to deploy distro docker-desktop to C:\Users\username\AppData\Local\Docker\wsl\distro: exit code: -1  stdout: Access is denied.

### ISSUE THREAD

**Issue by Omzig** [docker/for-win#9429]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 064184D4-671F-4FAC-A556-CE62AAAF10E3/20201106222836

### Expected behavior
no errors when switching to linux containers

### Actual behavior
System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\username\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Access is denied.

[16:28:36.350][Engines           ][Error  ] Start failed with Failed to deploy distro docker-desktop to C:\Users\username\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Access is denied.

### Information

  - Windows Version: Windows 10 version 1909 (OS build 18363.1139)
  - Docker Desktop Version: 2.5.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: laptop

### Steps to reproduce the behavior

  1. install docker
  2. uninstall docker
  3. install docker
  4. docker will not start with linux containers, it will start with windows containers
  5. testing wsl, ubuntu works

**Comment by JohnKberg** [comment]
Have exactly the same problem. Feels like docker desktop is launched with wrong user account or something..
