### ISSUE TITLE
Docker fails to start on W10

### ISSUE THREAD

**Issue by nickybu** [docker/for-win#943]
### Expected behavior
Commands such as 'docker version', 'docker info' to work as normal, outputting the usual information.

### Actual behavior
'docker version'  outputs the following:

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.30/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

'docker info' outputs the following:
```
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.30/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

### Information

  - Diagnostic ID: DD4F172A-D2E6-418F-9DB5-43B8E95BD7A4/2017-07-20_18-12-03

OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.14393 N/A Build 14393
Network Card(s):           4 NIC(s) Installed.
                           [01]: Intel(R) Dual Band Wireless-AC 8260
                                 Connection Name: Wi-Fi
                                 Status:          Media disconnected
                           [03]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [04]: Check Point Virtual Network Adapter For Endpoint VPN Client
                                 Connection Name: Ethernet 2
                                 Status:          Media disconnected
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

### Steps to reproduce the behavior

  1. Install Docker
  2. Run any command

### What I've done

So Docker has been working fine for the past two weeks, however decided to break this morning. When my computer booted Docker spent a couple of minutes saying 'Docker is starting' and never actually started. It would crash and tell me to reset to factory default settings - which I did but it didn't make a difference. I uninstalled and re-installed Docker a few times, cleaned up my Hyper-V adapters and tried resetting and repairing Docker. 

I've just got started out with Docker so I'm not sure if I'm missing anything, however I can't seem to figure out the problem. During the past hour, Docker has actually not crashed, and instead allows me to navigate the settings and says 'Failed to start'. This error dialogue is displayed:

> Docker daemon failed with message:
> Error starting daemon: Error initializing network controller: Error creating default network: HNS failed with error : {Object Exists} An attempt was made to create an object and the object name already existed. 
> 
> 
>    at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings)
>    at Docker.Backend.ContainerEngine.Windows.Start(Settings settings)
>    at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
>    at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

I've attached the logs if anyone wants to take a look.

![capture](https://user-images.githubusercontent.com/7209407/28428144-af3bee70-6d78-11e7-91cd-120eba96fab8.PNG)

[log.txt](https://github.com/docker/for-win/files/1162983/log.txt)

**Comment by CRISLEV** [comment]
I had the same problem and solve it...
1. Go to C:\ and search for "com.docker.service"... I found that in C:\Program Files\Docker\Docker
2. Open CMD as administrator C:\Program Files\Docker\Docker
3. Stop service with the command "net stop com.docker.service", that will show the next message:
```
The Docker for Windows Service service is stopping.
A system error has occurred.

System error 1067 has occurred.

The process terminated unexpectedly.

The Docker for Windows Service service was stopped successfully.
```

4. Restart service with the command "net start com.docker.service", that will show the next message:
```
The Docker for Windows Service service is starting.
The Docker for Windows Service service was started successfully.
```

![image](https://user-images.githubusercontent.com/22825989/28475779-e0017344-6e0a-11e7-85d0-c149ef557db4.png)

**Comment by nickybu** [comment]
Thanks for the reply @CRISLEV, however it didn't make a difference. I got the same output in command prompt but the Docker application remained in its starting state.

**Comment by mbunge** [comment]
Got this issues on each startup :(

**Comment by jasonbivins** [comment]
@nickybu   Does docker fail when Window starts up, or do you start it up manually?
Next time you see that, can you check to see if the Docker for Windows service is running?

![image](https://user-images.githubusercontent.com/28021664/28579577-0976e006-712b-11e7-9f47-ba5abb4b7382.png)

**Comment by nickybu** [comment]
The Docker for WIndows service is indeed running, however the application is still starting up.

<img width="425" alt="capture" src="https://user-images.githubusercontent.com/7209407/28610059-4b2401ac-71e7-11e7-90d9-4b812c464b4d.PNG">

**Comment by Matthol** [comment]
I'm having exactly the same problem. Latest updated Win 10 Professional, Hyper-V installed and working. New install of Docker, click the Docker shortcut on the desktop with "Run as Administrator" and keep getting the failures in the tool. Rebooting, restarting the service, resetting don't work. Basically just broken out of the box on a vanilla install. I don't have any more time to struggle with it. Uninstalling

**Comment by nickybu** [comment]
Same situation. Already wasted way too many hours trying to figure it out and solve the problem but to no avail. Stopped using Docker for the time being.

**Comment by jeefo12** [comment]
Had the same problem. Close the docker entirely then go to C:\ProgramData\Docker and delete the network directory. Start the docker again and it should be fine.

**Comment by nickybu** [comment]
Just tried that and it still remain's stuck on 'Docker is starting....'.

**Comment by dardelean** [comment]
Same issue.

**Comment by vishalm** [comment]
I am unable to start docker

Error response from daemon: open \\.\pipe\docker_engine_windows: The system cannot find the file specified.

   at Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\DockerDaemonChecker.cs:line 63
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 218
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 93
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 46
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 144

**Comment by OSHI7** [comment]
I am having this identical problem.

**Comment by rn** [comment]
Closing this issue as the original issue is over a year old. If you still have the issue, please upload diagnostics and open a new issue with the ID.

@vishalm @OSHI7 your issues are very different. Could you open a new issue with a diagnostics ID. Without it we are not able to help. Thanks

**Comment by rn** [comment]
@paslandau on the systray menu, there is a whale icon, rightclick and select  "Diagnose and Feedback" and follow the instructions

**Comment by vishalm** [comment]
Guys there is update for win10 team
Talk to you network admin if you are in Corp
