### ISSUE TITLE
Docker Desktop WSL Distro stopped work after Update

### ISSUE THREAD

**Issue by Richsan** [docker/for-win#9433]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker WSL distro works normally as before after update
### Actual behavior
Docker crashes on startup with Docker Desktop WSL Distro stopped error after last update 
### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
No.

### Steps to reproduce the behavior

  1. ...
  2. ...

error:

WSL distro stopped while waiting for Lifecycle server.
  >Stdout:
⇨ http server started on /run/guest-services/wsl2-bootstrap-expose-ports.sock
⇨ http server started on /run/guest-services/wsl-cross-distro.sock
execing /sbin/init
getting children of 37
  >Stderr:
2020/11/07 14:54:51 resolving /mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-wsl-cli.iso...
2020/11/07 14:54:51 already in cache!
2020/11/07 14:54:51 resolving /mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-for-wsl.iso...
2020/11/07 14:54:51 already in cache!
time="2020-11-07T14:54:51Z" level=info msg="docker.tar is present in the cache"
time="2020-11-07T14:54:51Z" level=info msg="dialing Unix domain socket /run/guest-services/wsl2-expose-ports.sock for data connection"
time="2020-11-07T14:54:51Z" level=info msg="unable to connect data on Unix domain socket /run/guest-services/wsl2-expose-ports.sock: dial unix /run/guest-services/wsl2-expose-ports.sock: connect: no such file or directory. Is the server restarting? Will retry in 1s."
Error: input/output error
2020/11/07 14:54:51 input/output error

**Comment by alex-ip** [comment]
I have an issue which is probably related. After 2.5.0.1, my WIndows Docker Desktop seems to be running fine, but nothing works in my WSL2 Ubuntu. For example:

$ docker ps
-bash: /usr/bin/docker: Input/output error

**Comment by vinay1sonu** [comment]
I also did that uninstall and reinstall process but nothing happens.

**Comment by CanburakTumer** [comment]
Today I had the same issue which is in the https://github.com/docker/for-win/issues/9433#issuecomment-725046127 any docker comment was resulting in `-bash: /usr/bin/docker: Input/output error`

- I tried restarting the Docker, did not work.
- I collected and uploaded Diagnostics, with ID 8D99FD3E-1548-4B68-962F-41671DD0CD7E/20201122130426
- Then I tried `Clean / Purge Data` from Docker Desktop's Troubleshoot menu and isue resolved for me.

**Comment by xmaop** [comment]
> Today I had the same issue which is in the [#9433 (comment)](https://github.com/docker/for-win/issues/9433#issuecomment-725046127) any docker comment was resulting in `-bash: /usr/bin/docker: Input/output error`
> 
> * I tried restarting the Docker, did not work.
> * I collected and uploaded Diagnostics, with ID 8D99FD3E-1548-4B68-962F-41671DD0CD7E/20201122130426
> * Then I tried `Clean / Purge Data` from Docker Desktop's Troubleshoot menu and isue resolved for me.

It works for me, Thanks a lot @CanburakTumer.

**Comment by kim4848** [comment]
> Today I had the same issue which is in the [#9433 (comment)](https://github.com/docker/for-win/issues/9433#issuecomment-725046127) any docker comment was resulting in `-bash: /usr/bin/docker: Input/output error`
> 
> * I tried restarting the Docker, did not work.
> * I collected and uploaded Diagnostics, with ID 8D99FD3E-1548-4B68-962F-41671DD0CD7E/20201122130426
> * Then I tried `Clean / Purge Data` from Docker Desktop's Troubleshoot menu and isue resolved for me.

Thanks  @CanburakTumer

**Comment by hlynur102** [comment]
> Today I had the same issue which is in the [#9433 (comment)](https://github.com/docker/for-win/issues/9433#issuecomment-725046127) any docker comment was resulting in `-bash: /usr/bin/docker: Input/output error`
> 
> * I tried restarting the Docker, did not work.
> * I collected and uploaded Diagnostics, with ID 8D99FD3E-1548-4B68-962F-41671DD0CD7E/20201122130426
> * Then I tried `Clean / Purge Data` from Docker Desktop's Troubleshoot menu and isue resolved for me.

Same issue here after updating to 3.1.0 (51484). Purging WSL2 dataset helped.
Thanks @CanburakTumer

**Comment by Richsan** [comment]
I´ve solved uninstalling and installing docker before Canburak comming with the solution.
I forget to close and update this , so I´m doing it right now.
Thanks to all the answers!
