### ISSUE TITLE
Docker Desktop starts forever

### ISSUE THREAD

**Issue by Beutelwolf** [docker/for-win#9446]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 
C1C3179C-1CBA-4D77-B819-9E853AE0037C/20201109132834
### Actual behavior
Docker desktop does not start with activated WSL2 support. The task tray icon is running until it runs into timeout. 
### Information

  - Windows Version: Windows 10 Enterprise 1909 (Build 18363.1139)
  - Docker Desktop Version: 2.5.0.0 (49427)
  - WSL2

**Comment by taylorbartley** [comment]
I've been having similar startup issues, sometimes needing several reboots to achieve Docker launch. 

System:
Windows 10 Enterprise 1803 (17134.1365)
Docker Desktop Version: 2.5.0.0 (49427)

**Comment by taylorbartley** [comment]
Bump
