### ISSUE TITLE
Unable to access docker settings

### ISSUE THREAD

**Issue by amosyuen** [docker/for-win#945]
### Expected behavior
Right clicking the docker icon has a menu item to access settings.

### Actual behavior
Right clicking the docker icon only has one item "About Docker"

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
C48E9F1F-2475-40ED-9C2C-39633F2143B7/2017-07-20_23-01-19

  - host distribution and version (Windows version, build number, etc)
Version 1703 (OS Build 15063.483)

### Steps to reproduce the behavior

  1. Install docker
  2. Start docker
  3. Right click docker icon in taskbar

**Comment by amosyuen** [comment]
It brings up the first run UI the first time I install and run, and through that I can access the settings, but afterwards I am unable to access the UI. I have to uninstall and reinstall every time I need to change settings.

**Comment by amosyuen** [comment]
I was able to fix this by uninstalling docker, then deleting all the docker files:
* User Home .docker folder
* User AppData local and roaming docker folders
* Program Files/ Docker
* Registry (searched for keys with docker)

**Comment by jasonbivins** [comment]
HI @amosyuen 
Are you still having to reinstall to change settings?  If not, may I go ahead close this?
