### ISSUE TITLE
Cant't start Docker Desktop

### ISSUE THREAD

**Issue by ricardorosso** [docker/for-win#9453]
I downloaded and installed Docker Desktop for Windows.  But after finishing the installation I can't start it.  Same error message appears (see below).
It is in a Windows 10 Pro
Any suggestion?
Thanks and regards
RR

An error ocurred

System.InvalidOperationException:
job failed with message: No pudo iniciarse 'DockerDesktopVM'. (Id. de máquina virtual ECE8505F-6F5F-487D-B93C-ACDA8D4B6656)

El servicio Administración de máquinas virtuales no pudo iniciar la máquina virtual 'DockerDesktopVM' porque uno de los componentes de Hyper-V no se está ejecutando (identificador de máquina virtual ECE8505F-6F5F-487D-B93C-ACDA8D4B6656).
   en Docker.Backend.HyperVInfrastructure.HandleUpdatedJob(CIMConcreteJob updatedJob) en C:\workspaces\stable-2.5.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV\HyperVInfrastructure.cs:línea 762
   en Docker.Backend.HyperVInfrastructure.<HandleMaybeAsyncJob>d__38.MoveNext() en C:\workspaces\stable-2.5.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV\HyperVInfrastructure.cs:línea 696
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en Docker.Backend.HyperVInfrastructure.<StartVMAsync>d__30.MoveNext() en C:\workspaces\stable-2.5.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV\HyperVInfrastructure.cs:línea 544
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Docker.Backend.HyperV.<StartAsync>d__7.MoveNext() en C:\workspaces\stable-2.5.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV\HyperV.cs:línea 101
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Docker.Backend.HttpAPI.HyperVController.<StartAsync>d__8.MoveNext() en C:\workspaces\stable-2.5.x\src\github.com\docker\pinata\win\src\Docker.Backend\HttpAPI\HyperVController.cs:línea 44
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()

**Comment by adi-mohan** [comment]
If at all you are using Windows version 2004, then try with updating Windows to 20H2 version.

**Comment by ricardorosso** [comment]
Hi Adi.
Thanls for your answer.  No, I'm not using Windows 2004.  I'm using Windows 2010 Pro
Regards
RR

**Comment by zhangmx** [comment]
@ricardorosso I think @adi-mohan said 'Windows 2004' means version of windows 10 . The newest windows 10 version is '20H2', and you can try check update of your OS.

**Comment by ricardorosso** [comment]
OK, thanks for clarifying zhangmx
I'll try to get a newer version
RR
