### ISSUE TITLE
Docker-desktop 2.5.0.0 still requires Server Service (LanmanServer)

### ISSUE THREAD

**Issue by sanori** [docker/for-win#9456]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker desktop for Windows running when boot or double clicking "Docker Desktop" icon

### Actual behavior
The docker icons is appeared on the windows tray. But, it disappears after 2~3 seconds.
The docker-desktop does not start.

### Information

  - Windows Version: Windows 10 Enterprise with Version 2004 update
  - Docker Desktop Version: community 2.5.0.0(49427)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No
  - My company recommends to stop LanmanServer service for security reason.

### Steps to reproduce the behavior

  1. Reboot my computer
  2. docker desktop asks if I start the docker desktop
  3. Choose 'Start'
  4. docker-desktop stops

### Workaround
  1. Run 'services.msc'
  2. Start 'Server' service
  3. Start Docker Desktop. Then the docker daemon starts.

  - Although I set the 'Server' service set to start automatically,
     the security agents changes it to 'Not used' after a few minutes.

**Comment by stephen-turner** [comment]
Yes, it is a requirement. This is expected.

**Comment by stephen-turner** [comment]
Yes, it is a requirement. This is expected.
