### ISSUE TITLE
V 2.5.0.1 downgrades kubernetes

### ISSUE THREAD

**Issue by JukkaKeisala** [docker/for-win#9458]
After installing new docker for windows v2.5.0.1, it downgraded kubernetes from 1.19.3 to 1.16.6-beta.0. This can be seen using  

kubectl get nodes

Docker settings show, however, version 1.19.3. Which one is correct?

**Comment by stephen-turner** [comment]
Thanks for the report @JukkaKeisala, but I can't reproduce this. For me `kubectl get nodes` shows v1.19.2. What does `kubectl version` report for you? I think it should be 1.19.3 for the client and 1.19.2 for the server.

**Comment by JukkaKeisala** [comment]
`kubectl version` shows 1.19.3 for both client and server.

**Comment by JukkaKeisala** [comment]
Uninstalled whole thing and reinstalled. Now kubernetes version 1.19.3 is there using kubectl get nodes. Hopefully things will work out without reinstallation.
