### ISSUE TITLE
How to mount container data with docker-compose in 3.X?

### ISSUE THREAD

**Issue by klammbueddel** [docker/for-win#9461]
Dear community, 

In 2.3.0.4 I could find all container logs in `/mnt/wsl/docker-desktop-data/data/docker/containers`

The data folder is empty in 2.5.0.1. Do I need to enable this feature? Or did it move to another location?

Thanks for your help

### Expected behavior
Container logs should be stored in `/mnt/wsl/docker-desktop-data/data/docker/containers`
### Actual behavior
`/mnt/wsl/docker-desktop-data/data` folder is empty
### Information
  - Windows Version: 20H2
  - Docker Desktop Version: 2.5.0.1
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

**Comment by drkn** [comment]
Same here. I've been searching for the solution for days now... The only working solution is to downgrade to 2.3.0.5

**Comment by klammbueddel** [comment]
@drkn: Thank you for me not beeing the only one having this issue. My local ELK setup is gone with this. The logs are still not available in 3.0.0. For me this is kind of a blocker, rolling back to 2.3.

If there are any updates on this I would be very happy.

**Comment by klammbueddel** [comment]
https://forums.docker.com/t/the-location-of-images-in-docker-for-windows/19647/4 shows how to access the container data by running `docker run -it --privileged --pid=host debian nsenter -t 1 -m -u -i sh`. But how can I mount these via docker-compose in 3.X.X?

In 2.3.0.5 this was possible:
```
services:
    filebeat:
      volumes:
        - /mnt/wsl/docker-desktop-data/data/docker/containers:/var/lib/docker/containers:ro
```

Any help is appreciated.

**Comment by klammbueddel** [comment]
Found a solution in #8977
