### ISSUE TITLE
Docker fails to start after auto-update

### ISSUE THREAD

**Issue by vmato** [docker/for-win#9464]
Docker fails to start after auto-update

  - [ v ] I have tried with the latest version of my channel (Stable or Edge)
  - [ v ] I have uploaded Diagnostics
  - Diagnostics ID: 8D1CB7CA-4154-40A6-B4A1-343F481B3C61/20201111004202

### Information

  - Windows Version: Windows 10 20H2
  - Docker Desktop Version: 2.5.0.49950
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

`WSL distro stopped while waiting for Lifecycle server.
  >Stdout:

  >Stderr:
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:838
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:943
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).Execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:883
main.main
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:28
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374
rootfs mountiso version-pack
main.setupRootFS
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:353
main.doRun
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:231
main.run.func1
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:86
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:838
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:943
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).Execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:883
main.main
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:28
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374`

**Comment by romeroej2** [comment]
Exact same issue.

**Comment by alinuxsa** [comment]
same issue 🤣

**Comment by alinuxsa** [comment]
I tired disable wsl2 backend, docker is running

![](https://s3.ax1x.com/2021/01/13/stElin.jpg)

**Comment by rickyheijnen** [comment]
I tried again upgrading 2.5.0 to 3.2.2 this time. But still the same problem. Why isn't this solved already? How can I help to get this issue solved?
