### ISSUE TITLE
Docker startup fails

### ISSUE THREAD

**Issue by sudhirtumati** [docker/for-win#947]
### Expected behavior
Docker starts successfully
### Actual behavior
Docker statup fails with an error
### Information
FC811971-D853-43BD-A32F-C845AF0B711C/2017-07-21_21-57-02

### Steps to reproduce the behavior

  1. Click on 'Docker for Windows' shortcut available in Start menu

**Comment by jasonbivins** [comment]
Hi @sudhirtumati 
Do you get this error when windows starts, or only when double clicking the Docker for Windows shortcut?
Can you check to see if the Docker for Windows service is running?

**Comment by sudhirtumati** [comment]
I get this error when I launch Docker for Windows, not during windows startup

**Comment by sudhirtumati** [comment]
With latest insider preview build 16251, this issue seems resolved. Docker for Windows starts without any error after update. Will continue to use it for next few days and report if any issues were found.

**Comment by sudhirtumati** [comment]
Was able to use docker on latest insider preview build 16251 without any issues.
