### ISSUE TITLE
Windows 10 v20H2 won't boot after installing docker

### ISSUE THREAD

**Issue by DarkJester** [docker/for-win#9477]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Windows boots to login
### Actual behavior
Windows reboots several times before launching recovery options.
### Information

  - Windows Version: Windows 10 v20H2
  - Docker Desktop Version: Docker 2.5.0.1
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: NO

### Steps to reproduce the behavior

  1. install docker desktop on windows 10 v20h2.
  2. reboot.

**Comment by sakesun** [comment]
Got same problem here

**Comment by sakesun** [comment]
In my case, I enter Safe-mode (without network adapter), then remove all network adapter except wifi & ethernet.
Now my machine is back.
