### ISSUE TITLE
Docker desktop and proxy :  proxyconnect tcp: dial tcp ... connect: connection refused     despite settings seems correct

### ISSUE THREAD

**Issue by semangard** [docker/for-win#9478]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 63623751-D614-473D-8BB0-06A45735F74E/20201112041051

### Expected behavior
Be able to run docker run hello-world

### Actual behavior
docker run hello-world
Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp 129.195.0.195:8080: connect: connection refused.

### Information
  - Windows Version: Windows 10 Entreprise
  - Docker Desktop Version: 2.5.0.0 (49427)
  - I do NOT use the WSL 2 based engine
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. I set both manual proxy settings :
          HTTP ->    http://user:password@proxy.mycompany.ch:8080
          HTTPS ->  http://user:password@proxy.mycompany.ch:8080
  2. When I run :  docker run hello-world
  3. I got the error : docker: Error response from daemon: Get https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp 129.195.0.195:8080: connect: connection refused.

Please note that:   
a) ping -a 129.195.0.195    matches with   proxy.mycompany.ch 
b) my proxy settings might be correct because I used them for other tools

**Comment by semangard** [comment]
Still have the issue after having upgraded to 2.5.0.1 (49550)

Diagnostics ID: 63623751-D614-473D-8BB0-06A45735F74E/20201112060311

**Comment by semangard** [comment]
Please note that this seems to work when I do not work remotely => no direct access VPN automatically activated.

**Comment by jeanphilippegoldman** [comment]
Hi semangard,
according to the IP of your proxy, we are in the same company (hug). I'm facing the same pbs and others... Can we get in touch ? my email address is public in my github profile. thanks in advance
