### ISSUE TITLE
Hangs at Docker is starting after changing graph setting

### ISSUE THREAD

**Issue by timbarclay** [docker/for-win#948]
### Expected behavior
Docker should start up.

### Actual behavior
Docker is stuck perpetually says "Docker is starting". Running any command from the cli returns:

    Error response from daemon: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.

### Information

I used the Advanced window of the Daemon tab in the Docker for Windows settings app to add a "graph" setting to try and move the container/image location to a different disk drive based on [this page](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/configure-docker-daemon) e.g.:

    {
        "graph": "e:\\dev\\docker\\graph"
    }

When I clicked the button to save, Docker restarted and has been stuck in the "Docker is starting" state since then.

Ending the task and restarting doesn't help and neither does restarting the computer.

  - Diagnostic ID: 9AA50957-CF21-45F0-B682-AF8B06E3BA15/2017-07-21_15-11-50
  - log file: [log.txt](https://github.com/docker/for-win/files/1165787/log.txt)

### Steps to reproduce the behavior

  1. Go to Daemon tab and click Advanced
  2. Add a new line with a "graph" setting
  3. Click save

**Comment by timbarclay** [comment]
I've just found [this issue](https://github.com/docker/for-win/issues/473) which contains a solution:

- Open C:\Users\<user>\AppData\Roaming\Docker\settings.json
- find "DaemonOptionsV2" and remove the setting I had added

After ending the task and restarting, it's working. I think the problem was that the settings editor in the Docker for Windows app didn't need to have backslashes escaped like the actual file does.

**Comment by jasonbivins** [comment]
Hi @timbarclay   I just tested this on the latest edge version, and it seems to be working.  Are you using Docker in Windows container mode, or Linux mode?  If you're in Linux mode, check the Shared drives tab and make sure E: is shared out.

![image](https://user-images.githubusercontent.com/28021664/28677557-cd8e73aa-72bb-11e7-8d3d-3128379ca139.png)

**Comment by jasonbivins** [comment]
Hi @timbarclay   After further testing, I found that it crashes if you add a second layer to the folder - 
"graph": "C:\\bucket" worked just fine for me, but "graph": "C:\\bucket\\test"  or "graph": "C:\\bucket\test"
both crash Docker.  I'll write it up as a bug, and put together a quick KB for it.
In the meantime - it should work fine if you can use E:\\Dev for your volume

**Comment by amymc** [comment]
Hi @jasonbivins,

I'm having a similar problem. When I change the advanced settings and restart, it hangs. My new config looks like this:

`{
  "bip": "172.18.0.1/16"
}`

I have tried editing the daemon.json via the command line instead, as outlined [here](https://github.com/docker/for-mac/issues/218#issuecomment-266566971), but it still hangs when restarting. 

Any ideas how to get around this?

Thanks

**Comment by jasonbivins** [comment]
Hi @amymc 

It looks like you're trying to accomplish something a little different, but getting the same results.
Is this a Win or a Mac issue?

Can you open up a new issue, along wiht a diagnostic ID, so we can track this a little better?

**Comment by amymc** [comment]
Hi @jasonbivins, 

It was a Mac issue but I got around it by installing the Edge version of the Docker app instead. 

Thanks
