### ISSUE TITLE
Windows Docker Desktop Kubernetes hung in "Starting"

### ISSUE THREAD

**Issue by smeruva1** [docker/for-win#9484]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E6361EE4-CEFD-4620-8B9C-DB5AABF9A691/20201112130313

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. Open Docker desktop settings
  2. Click Enable Kubernetes

**Comment by smeruva1** [comment]
[20201112130313.zip](https://github.com/docker/for-win/files/5530749/20201112130313.zip)

**Comment by FastStonewkx** [comment]
same question.
![image](https://user-images.githubusercontent.com/36177654/99138224-196e9b00-266a-11eb-8749-82273942a7bb.png)

I update docker desktop client.

last version, k8s is ok
I can't upload Diagnostics

**Comment by FastStonewkx** [comment]
[Uploading 20201114030728.zip…]()

**Comment by whgibbo** [comment]
I recently upgraded from version 2.x to 3.0.4 (51218).  Did they by uninstalling previous version first, then installing the latest.
Which now uses WSL2 by default.  

Docker engine is reporting as working.  But get the same issue when enable Kubernetes, whilst this is enabling.. Docker commands are not responding, then that there is no response to docker ps.

@smeruva1  did you ever resolve this ?

**Comment by whgibbo** [comment]
Just try to switching of the WSL2 option, at which point it restarts and just hangs :(  
Any thoughts ?
