### ISSUE TITLE
Docker refuses to work: various issues

### ISSUE THREAD

**Issue by DaleyKD** [docker/for-win#9487]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: ACEB1576-2BEC-41C9-B81F-38F00642D372/20201112174516

### Expected behavior
It'd be awfully nice if I could actually use Docker.

### Actual behavior
- Sometimes, I get i/o timeout. It happens when I try to do `docker ps` or any type of docker-compose command. If docker successfully starts up on reboot, it might appear to work for a couple minutes, then it just gives up, and I start getting i/o timeouts.
- Right now, Docker Desktop shows that it's running, however the Hyper-V is Stopped.
- When things feel like we're having a good day (it's been a while), we might be able to use docker-compose for a while to build or pull, but then it just gives up and I can't seem to get it to work right again.
- As I type this, I told Docker to Restart... it's stuck. This is a common occurrence.

### Information

  - Windows Version: Windows 10 Enterprise 20H2
  - Docker Desktop Version: 2.4.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

I have been fighting Docker for **months**. The last stable use of Docker was a certain build of 2.3.0.5 that I can't find anymore. Ever since 2.4.0.0, life has been horrific.

I did a Windows restore yesterday, wiping my C drive and starting fresh. I have tried 2.5.0.1 and 2.4.0.0. Both refuse to work in either WSL2 or Hyper-V. (_I am trying Linux containers only_.)

I was unable to get you the logs I really wanted to show you because the `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" gather -upload` froze up at something about `mutagenGatherer` and then `"Getting Linux Diagnostics via a unix socket: \\\\.\\pipe\\dockerDiagnosticd" type=unixsock`. I had to uninstall 2.5.0.1 at that point.

### Steps to reproduce the behavior

  1. Install Docker.
  2. Try to use Docker.

**Comment by hodgef** [comment]
Docker versions past 2.3.0.4 or so are broken. Many of my colleagues are reporting issues when you upgrade to newer versions.
Your best bet for now is to downgrade until Docker gets its act together. Here's the build I'm using:

https://docs.docker.com/docker-for-windows/release-notes/#docker-desktop-community-2304

Regards,
Francisco Hodge

**Comment by DaleyKD** [comment]
@hodgef : I'm glad to hear someone concurs.  I **swear** there were two builds of 2.3.0.5. I can't prove it. But the first build was glorious. The second build and forward has just ruined everything for me.

The reason I swear this is because 2.3.0.5 was the first version that did something differently with the volume mounts. I know I was running that version without any issues, and then was prompted with an update that said it was 2.3.0.5.

Oh well.

As of today, I'm running 2.5.0.1 with SOME hassle, but not so bad, **as long as I keep my antivirus turned off**.  This is not acceptable, but it is what it is.

**Comment by Riff451** [comment]
Same issues. I'm using 2.5.0.1 but on my work laptop I cannot turn off the antivirus. I'd say 8/9 times out of 10 docker doesn't start. And as you've experienced, once it starts it then works for awhile and all of sudden gets stuck. Then the dice roll starts again trying to restart it.

**Comment by DaleyKD** [comment]
@Riff451 : I tried adding some directory exclusions, but that doesn't seem to suffice.  I know docker has a single page describing the ONE directory to exclude (I did so), and I added a few more, but it's not enough.

Here's to hoping keeping antivirus off today will keep things going smoothly.

**Comment by DaleyKD** [comment]
I'm scared to jinx it... as long as I keep TrendMicro disabled (I have to exit the agent), Docker 2.5.0.1 has been awesome, and Visual Studio 2019 has integrated with it faster than EVER.

I would LOVE for someone from Docker to chime in and tell me the **real** exclusions list.  I have added the following, but it doesn't seem to work enough to prevent the issues:
![image](https://user-images.githubusercontent.com/7206282/99556115-c016ac80-2986-11eb-8950-f21465373c75.png)
