### ISSUE TITLE
Throw an error if mounting a volume not enabled in Shared Drives

### ISSUE THREAD

**Issue by dkarlovi** [docker/for-win#95]
### Expected behavior
If the drive the folder being shared is not enabled in Shared Drives setting, it should throw an error.

    C:\Users\$me\test>docker run -v c:/Users/$me/test:/data -ti --rm alpine ls /data
    docker: c:\ drive is not enabled in "Shared Drives" setting, quitting.
    
    C:\Users\$me\test>

### Actual behavior
It fails silently. I've just tested it, you can specify whatever you like as local path and it will fail silently for everything unless you did everything right (when it works)

    C:\Users\$me\test>docker run -v c:/Users/$me/test:/data -ti --rm alpine ls /data
    
    C:\Users\$me\test>

### Information

  - ID 345C21F2-80E1-4357-AAA2-11339E7B952C/2016-09-20_21-17-52
  - Windows 10 Pro
  - Docker 1.12.1 stable Win

### Steps to reproduce the behavior

As seen above: provide anything as local volume and it fails without error.

**Comment by friism** [comment]
@dkarlovi thanks for reporting, we've been wanting to do this for a while and the feature will hopefully ship next week

**Comment by dkarlovi** [comment]
@friism thanks, looking forward to it. :+1:

**Comment by dgageot** [comment]
@dkarlovi Beta27 was released today with hardened file sharing feature and the kind of error message that you asked for. Could you take a look and close this issue if it is fixed? Thanks a lot!

**Comment by rneugeba** [comment]
closing this as fixed. Please re-open if there still is an issue
