### ISSUE TITLE
Data loss caused by .aws and .azure folder manipulation in WSL home directory with Cloud Experience

### ISSUE THREAD

**Issue by oliversalzburg** [docker/for-win#9503]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
I don't expect any of this to happen at all.

### Actual behavior
Whenever I restart Docker for Desktop, `.aws` and `.azure` in my WSL home directory get symlinked to folders with the same name on the Windows side (`/mnt/c/Users/oliver/.aws` for example).

When I initially observed this, the folders on the Windows side did not exist and my AWS configuration on the WSL side and Windows side was destroyed.

Upon recreating the configuration and restarting Docker for Desktop, my configuration was moved to the Windows side and the symlink was created yet again.

However, only part of my configuration was copied this time, as there were pre-existing files on the Windows side that were not overridden. Instead those files were again destroyed.

### Information

  - Windows Version: 10 19042.572
  - Docker Desktop Version: 2.5.0.1
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

It seems like this is related to the **Cloud Experience** experimental feature. Disabling that feature also disabled the problematic behavior.

### Steps to reproduce the behavior

  1. Create a WSL2 distribution using Ubuntu 20.04
  2. Enable WSL integration for the distribution in Docker for Desktop and enable the "Cloud Experience" experimental feature.
  3. The symlinks should now exist in your home directory in WSL and should be recreated with the problematic behavior as described.

**Comment by stephen-turner** [comment]
Thanks for the report, @oliversalzburg. Assign to @simonferquel.

**Comment by simonferquel** [comment]
From re-re-re-reading the code, I can't find a way of having a data-loss. The only thing that can occur is if your WSL ~/.aws or ~/.azure was a symlink, it would be retargetted to the windows ~/.aws or ~/.azure (without removing anything from the previous tartget of the link).

Here is the actual Go Code of this with added comments
``` Go
func linkHomeSubdirToWindows(windowsDir string) error {
	if err := os.MkdirAll(syncHomeSubdir, 0755); err != nil { // this creates the Windows side dir if it does not exsit yet
		return err
	}

	linkPath := filepath.Join(homedir.Get(), filepath.Base(syncHomeSubdir)) // linkPath is the path we want to create the symlink at
	s, err := os.Lstat(linkPath)
	if os.IsNotExist(err) {
		return os.Symlink(syncHomeSubdir, linkPath) // if there is nothing there, we create the symlink
	}
	if err != nil {
		return err
	}

	if (s.Mode() & os.ModeSymlink) == 0 {
		return errors.Errorf("%s already exists and is not a symlink", linkPath) // if there was something there which is not a symlink: we fail to avoid data loss
	}

	dest, err := os.Readlink(linkPath)
	if err != nil {
		return err
	}
	if dest == syncHomeSubdir { // if the link is actually pointing to the windows dir, noop
		return nil
	}

	// retarget
	if err := os.Remove(linkPath); err != nil { // this case is only for an existing symlink pointing as something that seems wrong
// we retarget as this happen whenever you change your automount root in your WSL distro
		return err
	}
	return os.Symlink(syncHomeSubdir, linkPath)
}
```

**Comment by oliversalzburg** [comment]
I wish I could tell what exactly is the root cause here, but I believe the entire approach is problematic. You can't just mess with my folders/files that contain credentials and cloud configuration.

I just checked my other workstation and found the experimental feature also enabled. No idea why I ever enabled that. Was this enabled in some update?

I also checked if there was any data loss due to this and there is.

I had a `config` file at `~/.aws/config`. That file is now gone. Instead `~/.aws` is symlinked to my Windows side and contains the `config` file from my Windows side. My WSL config is lost.

Additionally, my credentials from the folder are also lost. Only my Windows-side credentials are kept intact.

**Comment by oliversalzburg** [comment]
What might be tripping up your code is that my existing `.aws` is a symlink to different location inside WSL where I keep my credentials/configuration safe. Which is also what saved my from having a complete nightmare over this.

**Comment by stephen-turner** [comment]
Ah yes, so it's exactly the case Simon mentioned: "The only thing that can occur is if your WSL ~/.aws or ~/.azure was a symlink, it would be retargetted to the windows ~/.aws or ~/.azure". We'll discuss again how to handle this case.

**Comment by oliversalzburg** [comment]
True, the files are still left intact in their original location. The unexpected retargeting creates the impression of data loss only.

However, because Docker keeps destroying my original symlinks, it seems like I'm unable to keep my distinct configurations while this feature is enabled.

I also confirmed by myself that the feature is apparently enabled by default in the latest release.

**Comment by oliversalzburg** [comment]
Seems to me like this keeps happening even with the Cloud Experience disabled.

Some hint on how to prevent this behavior from happening would be greatly appreciated at this point in time.

**Comment by simonferquel** [comment]
Best way to avoid this behavior, is to replace the symlink with a copy of your aws / azure credentials (the syncer only replace ~/.aws / ~/.azure if they are symlinks, to handle things like changing your WSL automount root.

**Comment by oliversalzburg** [comment]
I have an existing automated setup for my environments that links my credentials from a defined location into my home directories. Managing the same through file copies would be a far worse solution than just reverting this behavior constantly. I was hoping Docker could be instructed to just quit it.

Thanks for the suggestion though.

What do you mean in regards to the automount root? I don't see any benefit in having Docker mess with my AWS configuration to be honest.

**Comment by oliversalzburg** [comment]
I can see this is pointless
