### ISSUE TITLE
Update from 2.5.0.0 to 2.5.0.1 fails. Docker won't start now.

### ISSUE THREAD

**Issue by mbomb007** [docker/for-win#9504]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3D942787-7E1B-4C2F-AE61-A5EE23B2F6CA/20201113161222

### Expected behavior

Update successful. Docker starts.

### Actual behavior

Update downloads, then it says a process is running that must be terminated: "System (critical process)".
The process cannot be terminated, clicking "kill" does nothing.
Restarting computer doesn't help.
Docker is no longer able to start. "Timed out waiting for the lifecycle-server to start."

### Information

  - Windows Version: 2004 (19041)
  - Docker Desktop Version: 2.5.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No
  - I am using Hyper-V backend.

It is reproducible, happening every time.

**Comment by mbomb007** [comment]
I fully uninstalled my existing installation, then installed 2.5.0.1, and it worked.

**Comment by Stephan-Ghequiere** [comment]
I am experiencing exactly the same problem.

**Comment by mbomb007** [comment]
Update: Re-installing Docker worked for the install, but none of my traefik containers will start up anymore...

They all fail with `command traefik error: failed to decode configuration from flags: field not found, node: c`

**Comment by ronchittaro** [comment]
Same here. Had to uninstall Docker and re-install. Still doesn't work.

WSL distro stopped while waiting for Lifecycle server.
  >Stdout:

  >Stderr:
2020/11/16 21:03:46 resolving /mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-wsl-cli.iso...
2020/11/16 21:03:46 copying...
Error: mounting wslCLIDest: open /mnt/host/wsl/docker-desktop-data/isocache/0ea3c56a55c0811b3e8178a5f9a50c958fee246975b500238e7bf867a364f433.iso: input/output error
2020/11/16 21:03:46 open /mnt/host/wsl/docker-desktop-data/isocache/0ea3c56a55c0811b3e8178a5f9a50c958fee246975b500238e7bf867a364f433.iso: input/output error
mounting wslCLIDest
main.doRun
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:226
main.run.func1
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:86
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:838
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:943
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).Execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:883
main.main
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:28
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374

**Comment by ronchittaro** [comment]
Uninstalled, went back to 2.5.0, still doesn't work.

WSL distro stopped while waiting for Lifecycle server.
  >Stdout:

  >Stderr:
2020/11/16 21:23:01 resolving /mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-wsl-cli.iso...
2020/11/16 21:23:01 copying...
Error: mounting wslCLIDest: open /mnt/host/wsl/docker-desktop-data/isocache/5cdd043f982dc6abb5b859b064a0463be77d88dd3ebe619ad28c5c191ad720b2.iso: input/output error
2020/11/16 21:23:01 open /mnt/host/wsl/docker-desktop-data/isocache/5cdd043f982dc6abb5b859b064a0463be77d88dd3ebe619ad28c5c191ad720b2.iso: input/output error
mounting wslCLIDest
main.doRun
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:226
main.run.func1
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:86
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:838
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:943
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).Execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:883
main.main
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:28
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374

**Comment by ultrono** [comment]
Ran into the same issues. After a few restarts I got Docker Desktop 2.5.0.0 working again. I'd recommend avoiding 2.5.0.1 completely if upgrading as there's clearly an issue.

**Comment by ronchittaro** [comment]
Been trying 2.5.0.0 with no luck. Upgrade to 2.5.0.1 seems to have broken something that even an uninstall can't fix.

**Comment by Furze** [comment]
Hi, I also have this issue. 

I am using Docker 2.5.0.0 on Windows 10, Version 1809 Build 17763.1577
And have the identical issues to the above.. 

Docker will not start anymore.
Doing an check for updates finds a update to Docker 2.5.0.1.

This fails asking me to kill System (critical), which it cannot do and rebooting doesn't fix.

I have noticed that when it tries to update the title bar says Installing Docker Desktop 2.5.0.0 (49427) which I would expect to be 2.5.0.1. 

I have also tried uninstalling and reinstalling but that hasn't solved this issue.

**Comment by responsiveuk** [comment]
Same problem with Update.
This fails asking me to kill System (critical), which it cannot do and rebooting doesn't fix.
Windows 10 
All containers missing when try to start docker.
How annoying.

**Comment by mbomb007** [comment]
@responsiveuk Uninstall Docker, then re-install the new version, and it should work. However, your containers will be gone.

I haven't done this before, but you could try saving your images: https://stackoverflow.com/questions/42250222/where-is-docker-image-location-in-windows-10

**Comment by mbomb007** [comment]
@responsiveuk Actually, here's a better reference: https://docs.docker.com/docker-for-windows/install/#save-and-restore-data

**Comment by ultrono** [comment]
Ha, an update to `v3.0.00` has just popped up. I'm really dubious about updating after this `2.5.0.1` saga :) Anyone tried this? 🙂

**Comment by mbomb007** [comment]
> Ha, an update to `v3.0.00` has just popped up. I'm really dubious about updating after this `2.5.0.1` saga :) Anyone tried this? 🙂
> 
> EDIT: not looking great: #9755, #9753

I'm going to avoid that version like the plague for a bit, I think. The changelog states that the new version will automatically download updates from now on. I'm not going to go for that until I'm sure I have the option not to actually install them.

**Comment by mbomb007** [comment]
Also, they got rid of the stable channel, and everyone gets the unstable releases now.

> Now that updates are so small we are able to download them in the background, and only require a restart to start using the new version. 
>
> At the same time, we are removing the Stable and Edge channels, and moving to a single, cumulative release stream for all users.

https://www.docker.com/blog/docker-desktop-3-0-0-smaller-faster-releases/

**Comment by bbezanson** [comment]
I couldn't uninstall 2.5.0.1 with the security lock-downs on our work Windows laptops. So on startup, I would get a failure message from 2.5.0.1. I saw 3.0.0 was available yesterday and installed it and it works. So it is much better from a usability perspective than 2.5.0.1. I couldn't seem to downgrade to 2.4.x either.

On a side note, you can join the Docker Development Early Access program starting yesterday. I will use that for personal use to install and test Docker on my Mac mini M1 system.

**Comment by Yogurt4** [comment]
#metoo  :(

exit code 2
   at CommunityInstaller.InstallWorkflow.<>c__DisplayClass25_0.<HandlePrePackagedExeAsync>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<HandlePrePackagedExeAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()

The previous Docker update had also cost me 2 days to fix.

**Comment by Logiqx** [comment]
> Uninstalled, went back to 2.5.0, still doesn't work.
> 
> WSL distro stopped while waiting for Lifecycle server.
> 
> > Stderr:
> > 2020/11/16 21:23:01 resolving /mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-wsl-cli.iso...
> > 2020/11/16 21:23:01 copying...
> > Error: mounting wslCLIDest: open /mnt/host/wsl/docker-desktop-data/isocache/5cdd043f982dc6abb5b859b064a0463be77d88dd3ebe619ad28c5c191ad720b2.iso: input/output error
> > 2020/11/16 21:23:01 open /mnt/host/wsl/docker-desktop-data/isocache/5cdd043f982dc6abb5b859b064a0463be77d88dd3ebe619ad28c5c191ad720b2.iso: input/output error
> > ...

I had a similar problem after upgrading from 2.3.0.4 to 3.1.0 but ultimately found a fix in https://github.com/docker/for-win/issues/8748

It appears the files in \\wsl$\docker-desktop-data\isocache were corrupted. After deleting the isocache files, Docker re-created them and started working again.

**Comment by sabeDev** [comment]
I also had this issued found it is indeed the underlying VM; however, this gets stuck in a shutting down scenario. I have experienced this in the past, one solution is to open task manager and kill the 'Virtual Machine Worker Process' this stops the VM, refresh and it should proceed (I had to do this twice).
