### ISSUE TITLE
Kubernetes fails to start after update docker desktop

### ISSUE THREAD

**Issue by FastStonewkx** [docker/for-win#9509]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 0F2A2189-7DB2-415D-AD26-5B162A2700F7/20201114030728

### Information

  - Windows Version: win10 19042
  - Docker Desktop Version: 2.5.0.1(49550)
    Engine:19.03.13
    Notary: 0.6.1
    Compose: 1. 27.4
    Credential Helper: 0.6.3
    Kubernetes: v1.19. 3
    Snyk:V1.424.4
  - I'm running the docker desktop on my pc
### Steps to reproduce the behavior

 1. after update the newer docker desktop client.
 2. I used to download the k8s-for-docker-desktop ,but it don't work this time.
and kubernate always can't running by now.

**Comment by FastStonewkx** [comment]
![image](https://user-images.githubusercontent.com/36177654/99138799-5472cd80-266e-11eb-923c-ab41a19ccd81.png)

**Comment by easyTree** [comment]
Exactly the same problem and versions here. I left the room with the whole environment set up - came back it had rebooted to install 20H2 and kubernetes is dead. Project progress === 0

**Comment by easyTree** [comment]
Also, this is not restricted to the WSL2 backend. If I switch to Hyper-V backend, the VM starts up but k8s doesn't ever complete starting.

**Comment by ronchittaro** [comment]
Same problem here with WSL2. Daemon has been trying to start for 10 hours now. Doesn't even error out. Tried uninstalling and re-installing...didn't help. Even went back to 2.5.0 and that has the same problem now .

**Comment by easyTree** [comment]
** 'Fixed' **

OK, I checked the logs, the current being C:\Users\<username>\AppData\Local\Docker\log.txt and discovered a message and there were <many> entries:
`* [<timestamp>][ApiProxy          ][Warning] msg="Error while setting up kubernetes: cannot expose the external port: listen tcp 127.0.0.1:6443: bind: An attempt was made to access a socket in a way forbidden by its access permissions.. Retrying in 1s".`

Over the past couple of weeks I've seen VSCode disconnecting from WSL2 every few minutes for whatever reason - perhaps this is related? Some network-configuration issue?

Anyhoo, rebooting appears to have cured the problem.

**Comment by ronchittaro** [comment]
> ** 'Fixed' **
> 
> OK, I checked the logs, the current being C:\Users\<username>\AppData\Local\Docker\log.txt and discovered a message and there were <many> entries:
> `* [<timestamp>][ApiProxy ][Warning] msg="Error while setting up kubernetes: cannot expose the external port: listen tcp 127.0.0.1:6443: bind: An attempt was made to access a socket in a way forbidden by its access permissions.. Retrying in 1s".`
> 
> Over the past couple of weeks I've seen VSCode disconnecting from WSL2 every few minutes for whatever reason - perhaps this is related? Some network-configuration issue?
> 
> Anyhoo, rebooting appears to have cured the problem.

Reboot didn't help for me. VS code isn't even in picture now. Docker Daemon can't even start anymore.

**Comment by FastStonewkx** [comment]
I use the Uninstall Tool  delete all about docker desktop.(clean totally)
And reinstall it.
now the kubernetes runing in almost 3 minus later.

![image](https://user-images.githubusercontent.com/36177654/99420067-bf0a5e80-2937-11eb-8a4f-667215649fb8.png)

**Comment by FastStonewkx** [comment]
By the way, I use the [k8s-for-docker-desktop](https://github.com/AliyunContainerService/k8s-for-docker-desktop) to help start  kubernetes. 

and this is the tool[uninstall tool](https://crystalidea.com/uninstall-tool)
