### ISSUE TITLE
Docker crash report

### ISSUE THREAD

**Issue by MerdyNumber1** [docker/for-win#9513]
![image](https://user-images.githubusercontent.com/50208720/99183091-89545280-274a-11eb-9a0c-02bddb5c3bf1.png)
My system:
Windows 10 - WSL 2
AMD Ryzen 5 2600

**Comment by erikdao** [comment]
@MerdyNumber1 Have you found any solution for this problem? I have the same problem and my system is similar to yours.

**Comment by MerdyNumber1** [comment]
@erikdao I don't remember exactly, but I kind of rebooted the pc, or reinstalled docker
