### ISSUE TITLE
How to roolback the last update of docker for win ?

### ISSUE THREAD

**Issue by MikhaelGerbet** [docker/for-win#952]
I have the last version of docker for win 17.06.0-ce-win. But now, she don't works on my W10 (#951) . How "downgrad" to the old version ? Where is the releases list to download ? 

thank you for your help

**Comment by riezebosch** [comment]
Maybe this one: https://download.docker.com/win/stable/12627/InstallDocker.msi

**Comment by MikhaelGerbet** [comment]
ok thank you
