### ISSUE TITLE
Docker fails to mount 'd:' drive

### ISSUE THREAD

**Issue by logesh14** [docker/for-win#9534]
- [x] I have tried with the latest version of my channel (Stable)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
 AE895202-288E-4BB4-86C3-4CABE71D706F/20201117072745

### Expected behavior

I'm trying to build bunch of cpp files from windows container.Below is the command I've tried.

docker run -t --name=build_container_1 -v D:\build\:D:\build local-server-build/windows/servercore-2004 cmd /c D:\build\data\build.bat 

### Actual behavior

Docker fails to mount  'd:' drive inside container. My scripts have hard-coded drive letter i.e ('d:' drive). Below is the error thrown by docker.

> docker: Error response from daemon: container 848fdf11ef5785b324f2d0f9c74eb3240f3c40b67cffa32f9d9f7a2bafeaa8f4 encountered an error during hcsshim::System::Start: failure in a Windows system call: The virtual machine or container exited unexpectedly. (0xc0370106)

### Information

Is there any limitations in mounting drives other than 'c:' ? because when i tried to share 'd:\build' from host to container as 'c:\build' worked fine.

example:

docker run -it -v D:\build\:d:\build  local-server-build/windows/servercore-2004 

Below is the docker info:
```
Client:
 Debug Mode: false
 Plugins:
  scan: Docker Scan (Docker Inc., v0.3.4)

Server:
 Containers: 42
  Running: 0
  Paused: 0
  Stopped: 42
 Images: 11
 Server Version: 19.03.13
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 19041 (19041.1.amd64fre.vb_release.191206-1406)
 Operating System: Windows 10 Pro Version 2004 (OS Build 19041.630)
 OSType: windows
 Architecture: x86_64
 CPUs: 40
 Total Memory: 31.63GiB
 Name: integ-exe7
 ID: E6MH:CYFC:HJXP:Q3YG:TEK5:PNZU:EVZX:TQ22:3V3Y:FSGJ:E6GL:AFVA
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
 test:5000
 test2:5000
test3:5000
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

  - Windows Version: Windows 10 professional  2004
  - Docker Desktop Version: 2.5.0.1 (49550)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

Any help is appreciated

**Comment by stephen-turner** [comment]
If you are getting an hcsshim error, the bug must be in the upstream engine code. So could you please file your ticket in the moby/moby project? Sorry, I would just move it if I could, but I can't because it's in a different GitHub org, not part of docker.

**Comment by logesh14** [comment]
Thanks @stephen-turner , i'll file the same in **moby/moby** project.
