### ISSUE TITLE
Docker VM using a LOT of memory

### ISSUE THREAD

**Issue by cloudybyte** [docker/for-win#9538]
- [ `yes` ] I have tried with the latest version of my channel (Stable ~or Edge~)
  - [ `no` ] I have uploaded Diagnostics
  - Diagnostics ID: -/-

### Expected behavior
Docker using just a reasonable amount of ram

### Actual behavior
Docker using as much as 11gb of ram instead of using at most 4gb or so. PC is becoming really really unresponsive.

### Information
  - Windows Version: 20H2     Build 19042.572
  - Docker Desktop Version: v19.03.13 (Docker Engine)
  - Native Win 10 Pro
  - 16gb total ram (maybe it uses as much as it gets)
### Steps to reproduce the behavior
I don't know how to reproduce, happed randomly. I am using the same docker image for a week for developing and it randomly happened last time I compiled to only put in some debug statements... [Dockerfile](https://github.com/cloudybyte/helium/blob/dev/Dockerfile)

**Comment by stephen-turner** [comment]
If you are using the Hyper-V backend, this is settable in the settings. If you are using WSL 2, then Windows is in charge of memory management but you can configure it in your .wslconfig file. Unless you're claiming that it's not obeying values set in the settings?

**Comment by cloudybyte** [comment]
it actually wasn't...
I now fixed this by specifying a lower amount. Don't have any idea why this happens, just wanted to report it.

**Comment by stephen-turner** [comment]
Great, thanks for reporting back, I'll close the ticket.
