### ISSUE TITLE
Cannot start or stop existing containers with custom compose filename in Docker Desktop (since v2.5)

### ISSUE THREAD

**Issue by chludwig** [docker/for-win#9539]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: I guess no diagnostics file needed. Error seems to be obvious.

### Expected behavior
Be able to start or stop existing containers (build with e.g. `docker-compose -f "my-compose-file.yaml" up -d`) in Docker Desktop by clicking the START or STOP button of the container group. This was possible in Docker Desktop v2.4

### Actual behavior
I get an error message after clicking, telling me that the docker compose file was not found.
> Cannot start Docker Compose application. Reason: Command failed: docker-compose --project-directory "my-project" up -d Can't find suitable configuration file in this directory or any parent. Are you in the right directory? Supported filenames: docker-compose.yml, docker-compose.yaml

It seems like Docker Desktop 'forgets' the `-f` option to use a different docker-compose file.  
We where not facing this problem in older versions of Docker Desktop. 

### Information
  - Windows Version: Windows 10 (2004)
  - Docker Desktop Version: 2.5.0.1
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
1. Create a new project or use an existing project where all containers are deleted
2. Rename your docker compose file to `dc.yaml`
3. Build and start the containers by executing `docker-compose -f dc.yaml up -d`
4. Klick the STOP button of the created container group in Docker Desktop

**Comment by k3vur** [comment]
also happens on macOS (11.0.1 Big Sur)

**Comment by jussico** [comment]
Still happening in 3.3.2 (63878) 
And if there is another 'docker-compose.yml' (i.e. the default name in default place)  in the path where the command is run, then Docker Desktop tries to use that. So it's really kind of messed up.
(also note: when running / stopping only from commandline there is no problem.)

**Comment by Bith76** [comment]
It is still happening in v3.4.0 on windows.
![image](https://user-images.githubusercontent.com/2178380/123057819-7d2f2280-d408-11eb-9a1f-a8e3a8894a52.png)

**Comment by xshapira** [comment]
Same here on macOS Big Sur 11.4
