### ISSUE TITLE
LCOW - Linux containers on Windows (Hyper-V) docker builds broken

### ISSUE THREAD

**Issue by MythreyaK** [docker/for-win#9541]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 29EA61E7-1AC4-4FAE-B694-6C88C82080D8/20201117185507

### Expected behavior
Docker builds my image

### Actual behavior
Error during second state of any Dockerfile build

```
The command '/bin/sh -c apt update -y' returned a non-zero code: 4294967295: failed to shutdown container: container ae415998d2351e3f6c5a7d0c933cb6f55b2a8ce63e67ac19daf39a1f9b801c49 encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The virtual machine or container with the specified identifier is not running. (0xc0370110): subsequent terminate failed container ae415998d2351e3f6c5a7d0c933cb6f55b2a8ce63e67ac19daf39a1f9b801c49 encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The virtual machine or container with the specified identifier is not running. (0xc0370110)
```

Line breaks inserted:
```
The command '/bin/sh -c apt update -y' returned a non-zero code: 
4294967295: failed to shutdown container: container <long hash> encountered an error during 
hcsshim::System::waitBackground: failure in a Windows system call: The virtual machine or container with the 
specified identifier is not running. 
(0xc0370110): subsequent terminate failed container <long hash>encountered an error during 
hcsshim::System::waitBackground: failure in a Windows system call: The virtual machine or container with the 
specified identifier is not running. (0xc0370110)
```

### Information

  - Windows Version: 19041.630
  - Docker Desktop Version: 2.4.2.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

```
FROM ubuntu:latest as build-tools

RUN apt update -y

FROM build-tools as runner

RUN echo "Oh hey there" && echo "Build complete" >> /done
```
  0. Disable WSL2 backend and switch to 'Windows Containers' mode
  1. Use this dockerfile, and try to buid the image using `LCOW` (Linux containers on windows using Hyper-V isolation)
  2. Try to build the image using `docker build -t test --isolation hyperv .` or `docker build -t nginx-test --platform linux .` or `docker build -t test .`.
  3. It should error out in the second build step.

**Comment by stephen-turner** [comment]
Thanks for the report, @MythreyaK. If you are getting an hcsshim error, the bug is in the upstream Engine code (https://github.com/moby/moby) rather than in Docker Desktop code itself. So I would suggest opening a bug report in moby/moby except that LCOW was only ever an experimental feature and is now deprecated (see https://github.com/docker/cli/blob/master/docs/deprecated.md#linux-containers-on-windows-lcow-experimental), so I don't think it is likely to get fixed. Both Microsoft's attention and ours has turned to WSL 2, which we would recommend instead. Sorry, I realise that doesn't solve your immediate problem, but that's the situation.

**Comment by MythreyaK** [comment]
Please don't apologize, I'm better informed now, I couldn't find any info while looking for this error, so I thought I'd ask. 
Thanks for letting me know. Given LCOW is deprecated, would you suggest I move this big report there, or leave it be? I find LCOW really useful since I can use both Linux and windows containers at the same time, and I feel it's snappier instead of a big fat VM running most of the time. 

Thank you for your time, and pointing me to the right resources!

**Comment by stephen-turner** [comment]
To be honest, I don't think it will get any attention if you do move it.

WSL 2 also doesn't involve a big fat VM, and is much faster as long as you keep your files in the Linux filesystem not the Windows filesystem. Granted you do still have to choose between Linux and Windows container modes: we have a roadmap item for that (docker/roadmap#79) but we haven't scheduled it yet.

**Comment by MythreyaK** [comment]
Thanks for the info!
