### ISSUE TITLE
Docker desktop click pull on remote repo nothing happen

### ISSUE THREAD

**Issue by dtometzki** [docker/for-win#9543]
Hello together,

i have Windows 10 Version 1909 Build 18363.1082 with Docker Desktop stable 2.5.0.1. 

I can see my remote image's on docker hub but when i click "Pull" (blue button) nothing happend. No download starts. In %Appdata log.txt no information.

How i can resolve the issue ?

Best regards
Damian

**Comment by stephen-turner** [comment]
What happens if you type a `docker pull` command from the command line?

**Comment by scottah** [comment]
I experienced this today. Running the docker pull command on the CLI worked with no issue, and it then appeared in my local Image list within the Docker Desktop app.

**Comment by AndreaBorgia-Abo** [comment]
Ah, my usual luck... same here!
