### ISSUE TITLE
Docker Desktop Community 2.4.2.0, Can not login with valid credentials (behind corporate proxy), returning "Unknown Error""

### ISSUE THREAD

**Issue by Shohjahon** [docker/for-win#9547]
- [ ✅] I have tried with the latest version of my channel (Edge)
  - [ ✅] I have uploaded Diagnostics
  - Diagnostics ID: 276EC25F-161F-41F0-970B-884C57FC0F17/20201118051351

### Expected behavior
I work behind corporate proxy, when I enter my login credentials in Docker Desktop login window, it should validate and authenticate me
### Actual behavior
However, it is rejecting me with "Unknown Error" without any explanation, I had tried with proxy settings, but again failed
![photo_2020-11-18_10-23-29](https://user-images.githubusercontent.com/16575814/99487421-20f2b480-2988-11eb-9e76-e7abc6fce548.jpg)

### Information
  - Windows Version: Windows 10 Enterprise Edition
  - Docker Desktop Version: Docker Desktop Community 2.4.2.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: I installed Docker desktop on main operating system.

**Comment by costalfy** [comment]
same issue with docker desktop 2.5.0.0 (49427) on windows 10 (1909)

**Comment by zappacor** [comment]
facing same issue, any debug or troubleshoot that could be done?

**Comment by nicolastorgato** [comment]
Same here...what to do?

**Comment by Xibal-UPS** [comment]
I am also encountering this issue.  Docker login works fine from powershell, but fails with unknown error when I try in the dashboard.

**Comment by ravibabu2010** [comment]
I am also facing the same issue with Windows 10 Pro, Docker Desktop Version: 3.2.2, running on a laptop with Hyper-V enabled.
![image](https://user-images.githubusercontent.com/5599968/113342866-a43bf380-92f4-11eb-93a7-7b3f5b47be4e.png)

**Comment by pavangeeber** [comment]
same issue on both my PCs. Little help?

**Comment by Shohjahon** [comment]
Issue was resolved in newer versions of docker desktop, if someone have been facing with this problem on windows machine, i recommend to install and configure wsl.

**Comment by NormanEdance** [comment]
> 28th October 2021. Docker version 20.10.8, build 3967b7d, Windows 10 fully updated Issue remains. Using px proxy, https://github.com/genotrance/px to authenticate to corporate proxy.
> 
> Command line docker login works fine. Everything else works OK

Same here.
