### ISSUE TITLE
Docker for Windows fails to start

### ISSUE THREAD

**Issue by Mattacks** [docker/for-win#955]
### Expected behavior
Docker for Windows starts

### Actual behavior
Fails as per attached diagnostic

### Information
Diagnostic ID 50F30D90-3254-4B10-9945-B3B45C54E13F/2017-07-26_11-14-27
OS Name	Microsoft Windows Server 2016 Datacenter
Version	10.0.14393 Build 14393
Processor	Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz, 2394 Mhz, 2 Core(s), 2 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. 090006, 23/05/2012
SMBIOS Version	2.3
BIOS Mode	Legacy

### Steps to reproduce the behavior
1 Download 'Edge (Windows Server 2016)' from here
https://store.docker.com/editions/community/docker-ce-desktop-windows
2 Follow the instructions

**Comment by jasonbivins** [comment]
Hi @Mattacks   Judging from the log, you're using Azure to run the server ?

Try our Docker for Azure page, this might get you better results. There is a link here to a CE version of Docker deployment template
https://docs.docker.com/docker-for-azure/#quickstart

**Comment by Mattacks** [comment]
It turned out it was because VM-within-VM wasn't enabled.
But Docker, as usual, didn't tell me what was wrong - it just left me guessing.

And there I was, thinking that computers were there to automate things.
