### ISSUE TITLE
[WSL2 + Docker] IP beetwen containers dont work

### ISSUE THREAD

**Issue by brtsos** [docker/for-win#9551]
Hi! I love Docker, but I use windows (WSL2 - ubunto 20.04) now and I can't use more containers efficiently.

I have 2 containers:

1 - with my web app

2 - with Cypress to end to end testing

The issue is in Cypress I have to set web url from first container. On windows is it localhost. I tried use IP (172.21.0.2:8000) but this don't work. Ths solution work on linux. That means that use more containers on windows makes no sense. How can I set it? Thaks for any solution.

**Comment by simonferquel** [comment]
Have you tried "host.docker.internal:8000" ?

**Comment by simonferquel** [comment]
Also, if both containers are attached to the same network, you can probably use `http:<container name>:8000`

**Comment by brtsos** [comment]
@simonferquel  it works! Thanks!
