### ISSUE TITLE
Feature Request: CLI Quit for Docker Desktop

### ISSUE THREAD

**Issue by gledis69** [docker/for-win#9555]
Currently 'Quit'-ing Docker Desktop is only done through UI. 
It be great for some niche uses of Docker to allow a CLI command like maybe `docker quit` to access that very same functionality.
Specifically, I wrote some PowerShell scripts to abstract most docker functionalities, but simulating the Quit functionality is troublesome and ugly.
I assume you guys already have some function like that, and would just need to expose that to the CLI.

**Comment by stephen-turner** [comment]
Thanks for the feedback, @gledis69. We get a few requests for similar features, so I've just made an item for it in our public roadmap, and I'm going to dupe this ticket up against that one (docker/roadmap#172). Please vote on it with a :+1:.
