### ISSUE TITLE
Select location of Hyper-V VMs used by Docker for Windows

### ISSUE THREAD

**Issue by rdeterre** [docker/for-win#9557]
Hi,

I would like to have Docker for Windows use a different hard drive than the system disk on my computer. I have set `"data-root"` and `"exec-root"` in my docker daemon configuration to the new hard drive, but when docker runs, I see in the resource monitor that the most accessed file is still under "C:\ProgramData\Microsoft\Windows\Hyper-V\Container Utility VM".

I modified the default folder for "Virtual Hard Disks" and "Virtual Machines" under "Hyper-V Settings" in the "Hyper-V Manager", but this did not make any difference.

I also tried forcing the isolation to either "hyperv" or "process" in the Docker daemon configuration, but the result was the same:

    "exec-opts": ["isolation=hyperv"]

Is it possible for me to specify where the "Container Utility VM"s should be ?

Thanks

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A519414A-2ACD-4E78-822B-13079C44A7A4/20201118173737

### Expected behavior

After changing `"data-root"` and `"exec-root"` in the Docker daemon configuration, Docker should use files under these directories when running.

### Actual behavior

Docker uses mostly files under "C:\ProgramData\Microsoft\Windows\Hyper-V\Container Utility VM"

### Information

  - Windows Version: 10.0.18363
  - Docker Desktop Version: Docker engine v19.03.13
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Use the following JSON docker daemon configuration file:
      ```
      {
        "registry-mirrors": [],
        "insecure-registries": [],
        "debug": false,
        "experimental": false,
        "data-root": "d:\\docker",
        "exec-root": "d:\\docker-exec"
      }
      ```
  2. Run docker images
  3. Open the Resource Monitor then go to the "Disk" tab. Under "Disk Activity", notice that the most written to/read from file is under "C:\ProgramData\Microsoft\Windows\Hyper-V\Container Utility VM"

**Comment by stephen-turner** [comment]
@rdeterre Unfortunately I don't know the answer to your question, but I believe that it's not in Docker Desktop code but in the engine (https://github.com/moby/moby) which is just an upstream to us. So could I ask you to file your ticket in moby/moby instead? Apologies, I would just move it, but it's not possible because the engine is not even part of the docker org.
