### ISSUE TITLE
Not enough memory to start Docker

### ISSUE THREAD

**Issue by GiuseppePegasus** [docker/for-win#956]
### Expected behavior
Docker starts successfully

### Actual behavior
Docker start with the message: 
Not enough memory to start Docker
You are trying to start Docker but don't have enough memory. Free some memory or change your settings.

### Information
Intel core i5 64bit - Win 10 Enterprise - 8Gb Ram
Docker memory: 5888Mb
Diagnostic ID: 225F2574-D50B-4B61-893E-44519C27455B/2017-07-26_15-06-54
 

### Steps to reproduce the behavior

  1. start Docker from win menu

**Comment by jasonbivins** [comment]
Hi @GiuseppePegasus 
You'll need to free up memory, or reduce the amount of memory available to Docker.  If you allocate more memory than what is currently available, it will give you that warning.
If you right click the Docker icon - go to Settings then Advanced.  There are two slider bars there - one for CPU and one for memory.

![image](https://user-images.githubusercontent.com/28021664/28631611-d4f9bf20-71fb-11e7-9647-178663ffe36e.png)

**Comment by ashoknallasivam** [comment]
It works. Thanks @jasonbivins

**Comment by shahriarhossain** [comment]
@jasonbivins : While trying to switch back to linux container I am also getting the same "NOT ENOUGH MEMORY" issue. But the settings page does not show me any ADVANCED tab.
![image](https://user-images.githubusercontent.com/6463320/46573793-f158dc00-c9bb-11e8-88bf-005f981b23c4.png)

**Comment by hazimt** [comment]
Just so others don't suffer the same way.  You need to click on the windows try:
![image](https://user-images.githubusercontent.com/37422657/50317909-f41f8500-0472-11e9-9ee9-03d58f553c35.png)

**Comment by hazimt** [comment]
Just so others don't suffer the same way. You need to click on the windows try:  

![image](https://user-images.githubusercontent.com/37422657/50317946-2e892200-0473-11e9-9513-90a76bc7bf50.png)

**Comment by lubnahassan** [comment]
I don't have an advanced tab.

**Comment by Hamzaalam** [comment]
> I don't have an advanced tab.
check-in the resources tab, you will see the advance settings
