### ISSUE TITLE
"500 Server Error: Internal Server Error" randomly after a while

### ISSUE THREAD

**Issue by hakuno** [docker/for-win#9561]
Hey!

Everytime I update the Docker For Windows I get some bad surprise.

The beta channel is buggy. And I guess some bug came to the stable channel recently.

The last message error after I updated:

```
Traceback (most recent call last):
  File "site-packages\docker\api\client.py", line 259, in _raise_for_status
  File "site-packages\requests\models.py", line 941, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localnpipe/version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\docker\api\client.py", line 205, in _retrieve_server_version
  File "site-packages\docker\api\daemon.py", line 181, in version
  File "site-packages\docker\api\client.py", line 265, in _result
  File "site-packages\docker\api\client.py", line 261, in _raise_for_status
  File "site-packages\docker\errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'i/o timeout'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 67, in main
  File "compose\cli\main.py", line 123, in perform_command
  File "compose\cli\command.py", line 69, in project_from_options
  File "compose\cli\command.py", line 132, in get_project
  File "compose\cli\docker_client.py", line 43, in get_client
  File "compose\cli\docker_client.py", line 170, in docker_client
  File "site-packages\docker\api\client.py", line 188, in __init__
  File "site-packages\docker\api\client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: 500 Server Error: Internal Server Error ("b'i/o timeout'")
[32872] Failed to execute script docker-compose
```

The version is `2.4.0.0` from `2020-09-28`. Channel: stable.

BTW can I downgrade? 😢

**Comment by mat007** [comment]
I’ve move this issue back to docker/for-win as after taking a first look we’re thinking it’s a bug with Docker Desktop.

@Chisonm @remif25 @besiwims you’re saying you are facing the same error but the error message looks very different from everyone else, could you open a separate issue please (unless I’m missing something)?

**Comment by blazestudios23** [comment]
I resolved this by unchecking the WSL checkbox in docker desktop. Docker 2.5 has issues with WSL for some reason.

**Comment by getvivekjoshi** [comment]
docker-compose.yaml version: '3.8' to version: "3.8"  add double quotes to version solved my issue

**Comment by playport-csparks** [comment]
@getvivekjoshi  This fixed my issue and you're getting absolutely not enough recognition. I am on mac OS Catalina and Docker wouldn't build my stack. This fixed the error I was getting.

**Comment by VKVSH** [comment]
Fixing docker-compose.yaml to use double quotes instead of single quotes did the trick
Not sure from where the issue crept it though since the YAML file had not changed THOUGH I did do some docker version change over the last couple of days

**Comment by aimeehg** [comment]
@getvivekjoshi thank you, this already fixed the issue. I'm on Windows 10

**Comment by Dan1ve** [comment]
I had the same problem today (WIndows 10, Docker with latest version).
I tried to use double quotes for the `version` parameter, but it didn't work immediately.
Then I closed Powershell, opened the docker settings and assigned more resources (RAM, disk space) to Docker.

Then I opened PowerShell again, and now it's working 🎉

**Comment by tim-blackmore** [comment]
Same problem. Double quotes in my docker-compose.yaml file solved the problem. Thanks @getvivekjoshi

For clairty. I change line 1 from 
`version: '3.7'`
to
`version: "3.7"`

**Comment by squall2229** [comment]
@tim-blackmore That helped, thank you!

**Comment by helro154** [comment]
so I have the newest version of the docker and it DOES have the "" but it still doesnt work.

**Comment by helmidridi** [comment]
I'm  facing the same issue changing ""  still doesnt work.

**Comment by chagai95** [comment]
I just did not start docker that was my issue...

**Comment by maxiride** [comment]
```
Docker version 20.10.5, build 55c4c88
docker-compose version 1.28.5, build c4eb3a1f
```
The double quotes solution didn't work for me, neither did adding more resources to the Docker engine.

The issue presents itself randomly, after few hours to few days I come back to see all running container stopped and unable to restart them with "docker-compose up -d". Every time I have to restart the Docker engine to make it work again only to fail not long after.

**Comment by hlakioui** [comment]
> 
> 
> Go to Docker Preferences, then select "Reset to factory defaults".
> Solved the problem for me.

thanks it's work for me

**Comment by tomasforsman** [comment]
For me the issue was that I used the wrong WSL distro as default.
List your wsl distros, check what the default is and that it's using version 2
wsl.exe -l -v
wsl.exe --set-version (distro name) 2
wsl.exe --set-default-version 2
wsl --set-default <distro name>
(eg. wsl --set-default docker-desktop)

Now you should be able to run 'docker-compose up' or 'docker compose up'

**Comment by hamiderremli** [comment]
I had the same error (I'm on docker version 20.10.6). 
Went to Docker Preferences, then select "Reset to factory defaults", restart and it works fine
Thanks to @arthurpietruch above

**Comment by a0m0rajab** [comment]
I had the same error, the problem was because the Docker image was not running. wiaiting it to run solved the issue.

**Comment by sevencai** [comment]
Restarting docker works for me.

**Comment by imhimanshujain** [comment]
I got the same issue after installing the docker. (when i tried to use docker-compose build) after I skipped the tutorial it started working.

**Comment by ShinyCoconut** [comment]
> For me the issue was that I used the wrong WSL distro as default.
> List your wsl distros, check what the default is and that it's using version 2
> wsl.exe -l -v
> wsl.exe --set-version (distro name) 2
> wsl.exe --set-default-version 2
> wsl --set-default
> (eg. wsl --set-default docker-desktop)
> 
> Now you should be able to run 'docker-compose up' or 'docker compose up'

wsl --set-default docker-desktop did the trick for me. Thanks.
