### ISSUE TITLE
Docker for Windows is missing commands like pull and push

### ISSUE THREAD

**Issue by thelinuxlich** [docker/for-win#9578]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Docker CLI has push and pull commands

### Actual behavior

When using Docker for Windows Edge 2.5.1.0 I don't have the common commands docker push and docker pull inside my WSL 2 distro (Ubuntu)

### Information

  - Windows Version: 10
  - Docker Desktop Version: 2.5.1.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ebriney** [comment]
Hi @thelinuxlich, you just have to open the settings from the tray and go in Resources -> WSL Integration section.
There you can choose in which distro you want to use docker.
