### ISSUE TITLE
Cannot login to Azure Container Registry

### ISSUE THREAD

**Issue by SteveALee** [docker/for-win#958]
### Expected behaviour

`docker login -u <user> -p <pwd> odacitest.azurecr.io`

should log me into the registry
 
### Actual behavior

` Get https://odacitest.azurecr.io/v2/: dial tcp: lookup odacitest.azurecr.io on [::1]:53: read udp [::1]:58645->[::1]:53: read: connection refused`

### Information

Latest Docker for windows installed. Deamon exposed on localhost.
Latest Docker Ubuntu client installed on Bash for Ubuntu on Windows (WSL) and DOCKER_HOST set
Azure Container registry created via CLI and admin user enabled (credentials used to login in)
Azure region is Europe West

### Steps to reproduce the behavior

Install Docker for windows
Install latest WSL
Install Docker for Ubuntu client
set DOCKER_HOST
test docker commands and build
Install Azure CLI
create a ACR - `az acr create --resource-group <yourResourceGroup> --name <yourACRname> --sku Basic --admin-enabled true`
Attmept to login to ACR as above

**Comment by SteveALee** [comment]
I get exactly the same response when running the login from the windows cmd shell.

Perhaps an ACR issue? Though it is supported in Europe West.

**Comment by SteveALee** [comment]
I created another ACR in azure portal using East US and basic (preview) but get the same error.

**Comment by SteveALee** [comment]
The problem required switching to the fixed DNS server of 8.8.8.8.  
I eventually found a reference to this

**Comment by markharrisonuk** [comment]
I have this issue if I have it switched to be using Linux containers
if I switch to Windows Containers - the login to ACR works. 
![docker](https://user-images.githubusercontent.com/5177824/29222196-6f48c4c6-7eb9-11e7-845e-27f7e193ed1d.png)

**Comment by AceHack** [comment]
@SteveALee what do you mean?  I'm on a corporate laptop and getting this error.

PS C:\WINDOWS\system32> docker login xxx.azurecr.io -u "spid" -p "spkey"
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get https://xxx.azurecr.io/v2/: unauthorized: authentication required

**Comment by SteveALee** [comment]
@AceHack what do you mean "what do I mean"? :) Seriously I thought there were enough details there. What is unclear?

**Comment by AceHack** [comment]
@SteveALee thanks for the response.  I got it worked out.  It was unrelated to changing my DNS to 8.8.8.8.  Thanks.

**Comment by jivorra** [comment]
@AceHack how did you solve the error? Because I am getting the same error in a corporate laptop.

**Comment by kostyanius** [comment]
still facing with this issue second day in a row!

**Comment by PriyankaGupta05** [comment]
Still facing the same issue , any help please.
My ACR and AKS are on same Azure Directory with same subscription.
