### ISSUE TITLE
Docker Desktop : Failed to set version to docker-desktop: exit code: -1

### ISSUE THREAD

**Issue by tech-vin** [docker/for-win#9586]
I am trying to start the docker desktop on my windows 10 pro (OS Builds 19041.630 and 19042.630). Every time the docker icon turns red & shows An error occurred Failed to set version to docker-desktop: exit code: -1. It was working fine earlier.
I have tried a few things to fix the issue:

- uninstalled docker desktop
- deselected [hyper-v & windows subsystem for linux] from windows features.
- restart & then installed the latest version of docker desktop
- checked windows subsystem for Linux from windows features.
- restarted & tried to start the docker, still, the same issue appeared.
- Additional information
- crash report was uploaded a month ago.
- wsl 2 is installed & set to default

PS C:\WINDOWS\system32> wsl --set-default-version 2
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
PS C:\WINDOWS\system32>

PS C:\WINDOWS\system32> wsl --list --verbose
  NAME              STATE           VERSION
  docker-desktop    Stopped         2
  PS C:\WINDOWS\system32>

Please help me to fix this problem, thanks.

**Comment by taisbak** [comment]
I think I have the same issue on a virgin Windows 10.
I downloaded and installed the latest Docker Desktop and followed instructions to update WSL.

I get this error on startup:

> System.InvalidOperationException:
> Failed to set version to docker-desktop: exit code: -1
>  stdout: The attempted operation is not supported for the type of object referenced.
> 
> 
>  stderr: 
>    at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\stable-2.5.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 146
>    at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\stable-2.5.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 82
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__25.MoveNext() in C:\workspaces\stable-2.5.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 99
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.5.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.5.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.5.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92

A crash report has been uploaded with diagnostic id: 
94C19741-9058-4290-A433-6A5F7D13274C/20201204085436

**Comment by Kingkon963** [comment]
I'm also facing the same issue.

**Comment by Kingkon963** [comment]
I just solved my issue by resetting Winsock (Windows Socket) Settings.

`netsh winsock reset `

**Comment by taisbak** [comment]
> I just solved my issue by resetting Winsock (Windows Socket) Settings.
> 
> `netsh winsock reset `

Great - it worked for me as well.
Thank you.

**Comment by rener172846** [comment]
It works for me too. Thanks

> I just solved my issue by resetting Winsock (Windows Socket) Settings.
> 
> `netsh winsock reset `

It works for me too, thanks @Kingkon963

**Comment by lzhp** [comment]
> I just solved my issue by resetting Winsock (Windows Socket) Settings.
> 
> `netsh winsock reset `

work for me too
thank you

**Comment by sivaramam** [comment]
> I just solved my issue by resetting Winsock (Windows Socket) Settings.
> 
> `netsh winsock reset `

It worked for me too. Thanks a lot.

**Comment by hammadsajid786** [comment]
`netsh winsock reset`

run this command via Command prompt/power Shell (As an Administrator)
It worked for me.

Docker Desktop Version : 4
WinVer: Windows 10 1907
