### ISSUE TITLE
docker rm $(docker ps -a -q) does not work under windows.

### ISSUE THREAD

**Issue by hantsy** [docker/for-win#9597]
Upgrade to the latest edge, it does not work as before.
```bash
docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.2
 Version:           20.10.0-rc1
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        5cc2396
 Built:             Tue Nov 17 22:49:28 2020
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0-rc1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       131bf7e
  Built:            Tue Nov 17 22:52:57 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.4.1
  GitCommit:        c623d1b36f09f8ef6536a057bd658b3aa8632828
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

When ran the following command, 

```bash
# docker ps -aq
7d7a7cb035b9
650b8d2fade8
cf5a5123ae05
f42abe7e56e2
63da7d1f9160

# docker rm $(docker ps -a -q)
unknown shorthand flag: 'a' in -a
See 'docker rm --help'.
````

**Comment by stephen-turner** [comment]
Thank you for the report, @hantsy, but I can't reproduce the problem. The command works fine for me under 2.5.1.0, removing all my stopped containers.

**Comment by hantsy** [comment]
Also encountered similar weird problems before using the Docker shipped tool to upgrade. 

Every time I reinstalled the Docker from a fresh copy, most of the time the problem is resolved.

I reinstalled the Docker today, I found interesting things.

1. In the PowerShell terminal, it worked.
2. in the CMD, got error like before, it did not work.

**Comment by stephen-turner** [comment]
Ah, I was trying in PowerShell not cmd, which is what we always recommend for docker commands.

I'm not too familiar with cmd syntax, but are you sure the $(...) syntax even works in cmd? Isn't it just a PowerShell thing? I just tried with the previous Edge, 2.4.2.0, and got the same error message. So I'm not sure this ever worked.

**Comment by hantsy** [comment]
Most of the time, I used  pw, but I still use CMD temporarily(it is quickly).
OK, I will keep using Powershell for docker commands. Thanks.
