### ISSUE TITLE
Proxy information (HTTP_PROXY, HTTPS_PROXY) are not available at build time

### ISSUE THREAD

**Issue by aerialls** [docker/for-win#96]
### Expected behavior

After setting the proxy settings, the HTTP_PROXY, HTTPS_PROXY headers should be visible when building containers.
### Actual behavior

HTTP_PROXY, HTTPS_PROXY are not available at build time.
### Information
- The diagnostic ID is 61C12625-59B8-4A08-B1C8-A025F055BCA9/2016-09-22_19-14-37
- I'm using Windows 10 Enterprise 1607
- I'm using Docker 1.12.1-beta26 (build 7018)
### Steps to reproduce the behavior
1. Add proxy settings for HTTP and HTTPS inside Docker for Windows
2. Create a Dockerfile like this one
   
   > FROM debian:jessie
   > RUN apt-get update
3. Build this docker with docker build
4. The docker fails without internet access

The docker has the following ENV variables:

> HOSTNAME=841c675d30f6
> HOME=/root
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> PWD=/

The excepted behavior is to have HTTP_PROXY, HTTPS_proxy, http_proxy, https_proxy and no_proxy headers inside the build container.

Thanks!

**Comment by dgageot** [comment]
ping @justincormack @dave-tucker do we have a plan in docker/docker to fix that issue?

**Comment by friism** [comment]
@aerialls You can use `--build-arg` to do this: https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables---build-arg

It's possible that Docker for Windows should do this automatically. Wdyf @simonferquel @jeanlaurent @dgageot ?

**Comment by dave-tucker** [comment]
@friism see docker/docker#30588

**Comment by aerialls** [comment]
We're currently using `--build-arg` but this involves duplicating proxy information.

👍 for docker/docker#30588.

**Comment by jasonbivins** [comment]
closing  - the enhancement request has been completed and is integrated
