### ISSUE TITLE
docker will not start

### ISSUE THREAD

**Issue by castlegrpsf** [docker/for-win#960]
### Information

  - Diagnostic ID 6336A315-6D8F-4AD8-AF87-19D6BB14071E/2017-07-29_13-39-32
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - windows-10   Microsoft Windows [Version 10.0.15063]

Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.30/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

### Steps to reproduce the behavior

  1. ... Double click on Docker Icon
![starterror](https://user-images.githubusercontent.com/30556010/28747105-3b43d05c-7465-11e7-9e3a-05c45d9f2c1c.jpg)

  2. ...

**Comment by jasonbivins** [comment]
Hi @castlegrpsf   According to the logs, it's creating the MobyLinuxVM - but it can't start it.

Let's create it manually to see if we get a more specific error: 
```  powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -create ```

**Comment by castlegrpsf** [comment]
here is the result
PS C:\WINDOWS\system32>  powershell -ExecutionPolicy Bypass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -create
Script started at 12:33:04.407
Module loaded at 12:33:08.449
Creating Switch: DockerNAT...
Switch created.
Set IP address on switch
powershell : ISO file at .\mobylinux.iso does not exist
At line:1 char:2
+  powershell -ExecutionPolicy Bypass -File "C:\Program Files\Docker\Do ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ISO file at .\m... does not exist:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
At C:\Program Files\Docker\Docker\resources\MobyLinux.ps1:376 char:5
+     throw "$args"
+     ~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (ISO file at .\m... does not e 
   xist:String) [], RuntimeException
    + FullyQualifiedErrorId : ISO file at .\mobylinux.iso does not exist
 

PS C:\WINDOWS\system32> 


Steve Fischerwww.castle-llc.com 
IMPORTANT: The information (including attachments) in this electronic mail message is sender's business Confidential. It is intended solely for the addressee(s). Access to this Internet electronic mail message by anyone else is unauthorized. If you are not the intended recipient, any disclosure, copying, distribution or any action taken or omitted to be taken in reliance on it is prohibited and may be unlawful. If you have received this communication in error please call (203) 258-6148 and delete all copies from your system.  Although steps have been taken to ensure this electronic message and attachments are free from any virus, you are advised to ensure they are actually virus free.
   


On Tuesday, August 8, 2017, 12:18:45 PM EDT, Jason Bivins <notifications@github.com> wrote:


Hi @castlegrpsf According to the logs, it's creating the MobyLinuxVM - but it can't start it.

Let's create it manually to see if we get a more specific error:
powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -create

**Comment by Get-Kraken** [comment]
Any progress on a fix for this?
