### ISSUE TITLE
Automatic issue lifecycle is closing valid issues.

### ISSUE THREAD

**Issue by fartwhif** [docker/for-win#9605]
I know this isn't a forum but there IS no forum.

  you guys (whoever is or isn't calling the shots) are putting WAAAAAY too much faith in reporting of issues.

https://github.com/docker/for-win/issues/4754

this is totally an issue and I laugh every time I wonder how often people run into it and just don't tell you guys so your hyper-automated issue system destroys any possible additional awareness.  You're wasting a lot of peoples' time and energy.  

Both issues constitute a proverbial puddle of puke in your lobby people are slipping on, and it stinks.

take it or leave it, ban me, i don't care

**Comment by stephen-turner** [comment]
Yes, we're aware that there are real issues we haven't fixed. That's inevitable when we have several million users all using the software in different ways in different environments. We have to prioritise the most common issues.
