### ISSUE TITLE
On Docker Desktop Startup, error "Failed to deploy distro docker-desktop to .... exit code stdout: Access is denied WSL2

### ISSUE THREAD

**Issue by melaniejones731** [docker/for-win#9608]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 0DEBCC32-C608-439A-9605-818DD5522169/20201123223310

### Expected behavior
Per these instructions, starting docker desktop should sucessfully start docker desktop: https://docs.docker.com/docker-for-windows/wsl/

### Actual behavior
Docker Desktop encounters an error on start due to access denied error.

### Information

  - Windows Version: Version 2004(OS Build 19041.264)
  - Docker Desktop Version: 2.5.0.1
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. I followed the instructions here in order: https://code.visualstudio.com/blogs/2020/03/02/docker-in-wsl2
  2. Then I followed the instructions here: https://docs.docker.com/docker-for-windows/wsl/
  3. when starting docker desktop, the application immediately fails with the specified error.

Interestingly, when I click on Resources, WSL Integration I expect to see an ubuntu option, but instead I see:

WSL Integration
Configure which WSL 2 distros you want to access Docker from

Enable integration with my default WSL distro

You don't have any WSL 2 distro. Please convert a WSL 1 distro to WSL 2, or install a new distro and it will appear here.

![image](https://user-images.githubusercontent.com/28410534/100131714-a58a7a80-2e41-11eb-83d3-612b78715ff9.png)

However, in ubuntu it shows that it is already set to wsl 2:

 wsl.exe --set-version ubuntu 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
The distribution is already the requested version.

### Additional information
my environment includes McAfee Endpoint Protection, VPN (Pulse Secure, ZScaler)

**Comment by melaniejones731** [comment]
additional debugging steps:

- verified nothing else was listening on port 53
- disabled windows features containers, hyperv, wsl, then re-enabled. (https://github.com/docker/for-win/issues/8204)

**Comment by melaniejones731** [comment]
tried this solution "restart LxssManager" but it did not help.
https://github.com/docker/for-win/issues/9549

**Comment by strarsis** [comment]
Found a fix for me that involves (re)moving `/wsl/docker*`) folders: https://github.com/docker/for-win/issues/9802#issuecomment-775863258

**Comment by stephenconnolly** [comment]
I'm having exactly the same issue as @melaniejones731, @strarsis  solution did not work for me.

**Comment by strarsis** [comment]
@stephenconnolly: What is in the Docker logfile? Have you purged and reinstalled Docker for Desktop and it still logs attempts to mount directories in that logfile?

**Comment by stephenconnolly** [comment]
@strarsis , I haven't purged Docker Desktop, I've uninstalled/reinstalled many times. Details of the log files below:

> Version: 3.1.0 (51484)
> Sha1: 04f280b1648e29845ae5734cfcc14796c92f3de2
> Started on: 2021/02/15 07:36:21.018
> Resources: C:\Program Files\Docker\Docker\resources
> OS: Windows 10 Enterprise
> Edition: Enterprise
> Id: 2009
> Build: 19042
> BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
> File: C:\Users\XXXXXXXXXXXX\AppData\Local\Docker\log.txt
> CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
> You can send feedback, including this log file, at https://github.com/docker/for-win/issues
> [07:36:21.096][GUI               ][Info   ] Starting...
> [07:36:21.134][ComponentVersions ][Info   ] Edition community
> [07:36:21.149][ComponentVersions ][Info   ] Edition community
> [07:36:21.196][LoggingMessageHandler][Info   ] [cde81b03] <GoBackendClient start> GET http://localhost/ping
> [07:36:21.218][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
> [07:36:21.519][AppMigrator       ][Info   ] Current version: 6. Latest version: 6
> [07:36:21.535][LoggingMessageHandler][Info   ] [f890291b] <GoBackendClient start> GET http://localhost/ping
> [07:36:21.535][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
> [07:36:21.551][GoBackendProcess  ][Info   ] Starting C:\Program Files\Docker\Docker\resources\com.docker.backend.exe -addr unix:\\.\pipe\dockerBackendApiServer
> [07:36:21.566][GoBackendProcess  ][Info   ] Started
> [07:36:21.566][TrackingSettings  ][Info   ] Crash report and usage statistics are enabled
> [07:36:21.566][SegmentApi        ][Info   ] Usage statistic: Identify
> [07:36:21.849][LoggingMessageHandler][Info   ] [56de29e5] <GoBackendClient start> GET http://localhost/ping
> [07:36:21.849][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
> [07:36:22.152][LoggingMessageHandler][Info   ] [fe514853] <GoBackendClient start> GET http://localhost/ping
> [07:36:22.152][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
> [07:36:22.454][LoggingMessageHandler][Info   ] [6e0b9418] <GoBackendClient start> GET http://localhost/ping
> [07:36:22.454][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
> [07:36:22.755][LoggingMessageHandler][Info   ] [0e2a98d8] <GoBackendClient start> GET http://localhost/ping
> [07:36:22.755][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
> [07:36:23.071][LoggingMessageHandler][Info   ] [8f93e07b] <GoBackendClient start> GET http://localhost/ping
> [07:36:23.071][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
> [07:36:23.372][LoggingMessageHandler][Info   ] [44fd9fe2] <GoBackendClient start> GET http://localhost/ping
> [07:36:23.372][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
> [07:36:23.673][LoggingMessageHandler][Info   ] [dd77ebcf] <GoBackendClient start> GET http://localhost/ping
> [07:36:23.673][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
> [07:36:23.974][LoggingMessageHandler][Info   ] [46d098eb] <GoBackendClient start> GET http://localhost/ping
> [07:36:23.974][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
> [07:36:24.275][LoggingMessageHandler][Info   ] [f89fbbe8] <GoBackendClient start> GET http://localhost/ping
> [07:36:24.275][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
> [07:36:24.577][LoggingMessageHandler][Info   ] [d7d9a0e8] <GoBackendClient start> GET http://localhost/ping
> [07:36:24.577][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
> [07:36:24.878][LoggingMessageHandler][Info   ] [e88ee5cf] <GoBackendClient start> GET http://localhost/ping
> [07:36:24.878][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
> [07:36:25.179][LoggingMessageHandler][Info   ] [e20af27b] <GoBackendClient start> GET http://localhost/ping
> [07:36:25.179][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
> [07:36:25.480][LoggingMessageHandler][Info   ] [d40ee0d3] <GoBackendClient start> GET http://localhost/ping
> [07:36:25.480][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
> [07:36:25.781][LoggingMessageHandler][Info   ] [8f2b1b72] <GoBackendClient start> GET http://localhost/ping
> [07:36:25.781][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
> [07:36:26.081][LoggingMessageHandler][Info   ] [dd40dbeb] <GoBackendClient start> GET http://localhost/ping
> [07:36:26.081][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
> [07:36:26.254][GoBackendProcess  ][Info   ] msg="starting backend server"
> [07:36:26.254][GoBackendProcess  ][Info   ] msg="started port-forwarding control server on \\\\.\\pipe\\dockerVpnKitControl"
> [07:36:26.254][GoBackendProcess  ][Info   ] msg="listening on unix:\\\\.\\pipe\\dockerVpnkitData for data connection"
> [07:36:26.254][GoBackendProcess  ][Error  ] msg="unable to query WslEngineEnabled state after 0s. Last error was Get \"http://unix/settings\": open \\\\.\\pipe\\dockerWebApiServer: The system cannot find the file specified."
> [07:36:26.254][GoBackendProcess  ][Info   ] msg="adding routes for /docker.tar"
> [07:36:26.254][GoBackendProcess  ][Info   ] msg="adding routes for /docker.tar"
> [07:36:26.254][GoBackendProcess  ][Info   ] msg="adding routes for /kube-images.tar"
> [07:36:26.254][GoBackendProcess  ][Info   ] msg="adding routes for /kube-images.tar"
> [07:36:26.254][GoBackendProcess  ][Info   ] msg="adding routes for /services.tar -> C:\\Program Files\\Docker\\Docker\\resources\\services.tar"
> [07:36:26.254][GoBackendProcess  ][Info   ] msg="adding routes for /services.tar -> C:\\Program Files\\Docker\\Docker\\resources\\services.tar"
> [07:36:26.255][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerVpnKitControl
> [07:36:26.255][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\docker_cli
> [07:36:26.255][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServerForGuest
> [07:36:26.255][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServer
> [07:36:26.387][LoggingMessageHandler][Info   ] [6f96de13] <GoBackendClient start> GET http://localhost/ping
> [07:36:26.402][GoBackendProcess  ][Info   ] msg="external: GET /ping 200 \"DockerDesktopCSharp\" \"\""
> [07:36:26.404][LoggingMessageHandler][Info   ] [6f96de13] <GoBackendClient end> GET http://localhost/ping -> 200 OK (took 25ms)
> [07:36:26.420][GoBackendClient   ][Info   ] backend API ready
> [07:36:26.420][LoggingMessageHandler][Info   ] [51afaa61] <GoBackendClient start> GET http://localhost/features
> [07:36:26.421][GoBackendProcess  ][Info   ] msg="external: GET /features 200 \"DockerDesktopCSharp\" \"\""
> [07:36:26.423][LoggingMessageHandler][Info   ] [51afaa61] <GoBackendClient end> GET http://localhost/features -> 200 OK (took 3ms)
> [07:36:26.495][SegmentApi        ][Info   ] Usage statistic: appLaunched
> [07:36:26.501][SegmentApi        ][Info   ] Usage statistic: heartbeat
> [07:36:26.840][LoggingMessageHandler][Info   ] [a06421ac] <BackendAPIClient start> GET http://backend/version
> [07:36:26.846][LoggingMessageHandler][Info   ] [a06421ac] <BackendAPIClient end> GET http://backend/version -> 200 OK (took 5ms)
> [07:36:26.852][LoggingMessageHandler][Info   ] [1978a2fa] <BackendAPIClient start> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx
> [07:36:26.857][LoggingMessageHandler][Info   ] [1978a2fa] <BackendAPIClient end> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx -> 200 OK (took 4ms)
> [07:36:26.862][LoggingMessageHandler][Info   ] [9431ab2d] <BackendAPIClient start> POST http://backend/migrate/app
> [07:36:26.864][LoggingMessageHandler][Info   ] [9431ab2d] <BackendAPIClient end> POST http://backend/migrate/app -> 204 NoContent (took 2ms)
> [07:36:27.901][LoggingMessageHandler][Info   ] [63f5e347] <Server start> GET http://unix/settings
> [07:36:28.016][LoggingMessageHandler][Info   ] [63f5e347] <Server end> GET http://unix/settings -> 200 OK (took 112ms)
> [07:36:28.039][DockerHub         ][Info   ] Login successfull
> [07:36:28.039][LoggingMessageHandler][Info   ] [f97146cf] <GoBackendClient start> POST http://localhost/hub-login
> [07:36:28.076][GoBackendProcess  ][Info   ] msg="NewSharer: WSL2 engine is enabled so no file sharer is required."
> [07:36:28.610][GoBackendProcess  ][Info   ] msg="user is part of free plan"
> [07:36:28.610][GoBackendProcess  ][Info   ] msg="entitlement: {PlanName:free Desktop:{Enabled:false}}"
> [07:36:28.610][GoBackendProcess  ][Info   ] msg="external: POST /hub-login 200 \"DockerDesktopCSharp\" \"\""
> [07:36:28.610][GoBackendProcess  ][Info   ] msg="enabling filesystem caching"
> [07:36:28.610][GoBackendProcess  ][Info   ] msg="filesystem exports are:  (2)"
> [07:36:28.612][GoBackendProcess  ][Info   ] msg="volume control server listening on \\\\.\\pipe\\dockerVolume"
> [07:36:28.613][LoggingMessageHandler][Info   ] [f97146cf] <GoBackendClient end> POST http://localhost/hub-login -> 200 OK (took 569ms)
> [07:36:28.614][GoBackendProcess  ][Info   ] msg="filesystem server listening on 00000000-0000-0000-0000-000000000000:00001003-facb-11e6-bd58-64006a7986d3"
> [07:36:28.614][GoBackendProcess  ][Info   ] msg="file ownership will be determined by the calling user (\"fake owner\" mode)"
> [07:36:28.614][GoBackendProcess  ][Info   ] msg="using mfsymlinks"
> [07:36:28.755][Updater           ][Info   ] Launcher process exited with 4294967295
> [07:36:28.770][Engines           ][Debug  ] Starting
> [07:36:28.770][LoggingMessageHandler][Info   ] [ecf2cde7] <BackendAPIClient start> POST http://backend/versionpack/enable
> [07:36:28.802][LoggingMessageHandler][Info   ] [ecf2cde7] <BackendAPIClient end> POST http://backend/versionpack/enable -> 204 NoContent (took 22ms)
> [07:36:28.802][LoggingMessageHandler][Info   ] [5ba48456] <BackendAPIClient start> POST http://backend/cloudcli/toggle
> [07:36:28.802][LoggingMessageHandler][Info   ] [5ba48456] <BackendAPIClient end> POST http://backend/cloudcli/toggle -> 204 NoContent (took 8ms)
> [07:36:28.817][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.StartTransition to state change sink
> [07:36:28.817][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.StartTransition sent to state change sink
> [07:36:28.817][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.StartTransition from LinuxWSL2
> [07:36:28.833][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"starting","Mode":"linux","date":1613374588}
> [07:36:28.833][SystrayNotifications][Info   ] Docker is starting
> [07:36:28.839][LinuxWSL2Engine   ][Info   ] Terminating lingering processes and wsl distros and patching host file
> [07:36:28.839][LoggingMessageHandler][Info   ] [d986c3d6] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
> [07:36:28.940][LoggingMessageHandler][Info   ] [d986c3d6] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 100ms)
> [07:36:29.156][WSL2Provisioning  ][Info   ] Checking docker-desktop
> [07:36:29.156][WSL2Provisioning  ][Info   ] deploying WSL distro docker-desktop to C:\Users\XXXXXXXXXXXX\AppData\Local\Docker\wsl\distro
> [07:36:29.203][WSL2Provisioning  ][Error  ] Failed to deploy distro docker-desktop to C:\Users\XXXXXXXXXXXX\AppData\Local\Docker\wsl\distro: exit code: -1
>  stdout: Access is denied.
> 
> 
>  stderr: 
> [07:36:29.203][LinuxWSL2Engine   ][Info   ] Stopping windows side processes
> [07:36:29.341][LinuxWSL2Engine   ][Info   ] Stopping engine
> [07:36:29.388][LoggingMessageHandler][Info   ] [a499ca28] <BackendAPIClient start> POST http://backend/windowsfeatures/check
> [07:36:29.588][LoggingMessageHandler][Info   ] [a499ca28] <BackendAPIClient end> POST http://backend/windowsfeatures/check -> 200 OK (took 196ms)
> [07:36:29.858][LinuxWSL2Engine   ][Info   ] Terminating lingering processes and wsl distros and patching host file
> [07:36:29.858][LoggingMessageHandler][Info   ] [27b3a1c5] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
> [07:36:29.904][WSL2Provisioning  ][Info   ] Checking docker-desktop
> [07:36:29.904][WSL2Provisioning  ][Info   ] deploying WSL distro docker-desktop to C:\Users\XXXXXXXXXXXX\AppData\Local\Docker\wsl\distro
> [07:36:29.904][LoggingMessageHandler][Info   ] [27b3a1c5] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 59ms)
> [07:36:30.005][WSL2Provisioning  ][Error  ] Failed to deploy distro docker-desktop to C:\Users\XXXXXXXXXXXX\AppData\Local\Docker\wsl\distro: exit code: -1
>  stdout: Access is denied.
> 
> 
>  stderr: 
> [07:36:30.005][LinuxWSL2Engine   ][Info   ] Stopping windows side processes
> [07:36:30.058][LinuxWSL2Engine   ][Info   ] Stopping engine
> [07:36:30.089][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.FailedToStartState to state change sink
> [07:36:30.089][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.FailedToStartState sent to state change sink
> [07:36:30.089][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.FailedToStartState from LinuxWSL2
> [07:36:30.089][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"failed to start","Mode":"linux","date":1613374590}
> [07:36:30.136][SystrayNotifications][Error  ] System.InvalidOperationException: Failed to deploy distro docker-desktop to C:\Users\XXXXXXXXXXXX\AppData\Local\Docker\wsl\distro: exit code: -1
>  stdout: Access is denied.
> 
> 
>  stderr: 
>    at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 146
>    at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__17.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 169
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 78
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__25.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 99
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
> [07:36:30.143][GUI               ][Info   ] Sending Bugsnag report 43231b38-ee83-4aeb-b469-cb00f196a4d9...
> [07:36:30.158][Updater           ][Info   ] Launcher process exited with 4294967295
> [07:36:30.221][GUI               ][Info   ] Bugsnag report 43231b38-ee83-4aeb-b469-cb00f196a4d9 sent
> [07:36:30.221][SegmentApi        ][Info   ] Usage statistic: eventCrash
> [07:36:30.221][Diagnostics       ][Warning] Starting to gather diagnostics as User : 'C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe' gather.
> [07:36:30.472][GoBackendProcess  ][Info   ] msg="external: GET /diagnostics/goroutines 200 \"Go-http-client/1.1\" \"\""
> [07:36:30.473][GoBackendProcess  ][Info   ] msg="external: GET /events 200 \"DockerDesktopGo\" \"\""
> [07:36:30.474][GoBackendProcess  ][Info   ] msg="external: GET /forwards/list 200 \"Go-http-client/1.1\" \"\""
> [07:36:30.481][GoBackendProcess  ][Info   ] msg="external: GET /ping 200 \"DockerDesktopGo\" \"\""
> [07:36:30.503][Engines           ][Error  ] Start failed with Failed to deploy distro docker-desktop to C:\Users\XXXXXXXXXXXX\AppData\Local\Docker\wsl\distro: exit code: -1
>  stdout: Access is denied.
> 
> 
>  stderr: 
>    at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 146
>    at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__17.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 169
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 78
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__25.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 99
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 69
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Docker.Engines.Engines.<StartAsync>d__21.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:line 102)
> [07:37:02.080][ErrorReportWindow ][Info   ] Open logs

**Comment by Arvi89** [comment]
I had this issue and fixed it, maybe that will help:
https://github.com/docker/for-win/issues/9972#issuecomment-782975365
