### ISSUE TITLE
Docker times out on start: _Failed to connect to the database open \\.\pipe\dockerDataBase_

### ISSUE THREAD

**Issue by soletan** [docker/for-win#962]
### Expected behavior

Docker should start on log in.

### Actual behavior

Docker fails to start on log in having some time out issue.

### Information

_This issue is tightly bound to #957. I can't tell whether it's a duplicate or not. Maybe the logging issue given here isn't even related to the timeout. I have sent crash report on the latter using included reporter._

My docker is having issues to start on log in today after having issues with mutual access on shared resources before as documented in #957. This time log is fed with the following error message quite frequently (10 times a second) and infinitely. 

```
[10:39:29.143][ApiProxy       ][Info   ] Failed to connect to the database open \\.\pipe\dockerDataBase: Das System kann die angegebene Datei nicht finden.
```

`Das System kann die angegebene Datei nicht finden.` is German for `File not found.`

This logging started prior to crash reporter popping up and continued afterwards. I checked log file folder while crash reporter was collecting data and today's log file was 400 KByte in size, already.

The previous logfile did look like the one reported in #957. It was created 90 minutes ago. Back then I was logged in with a second account while the first one was still logged in but suspended due to Win10 Pro limitations. Docker was having timeout issues on logging into second account as well.

But 20 minutes before I have logged out of both accounts and have logged into one of the two, only. Docker was having timeout issue again, this time logging error given above.

Is it actually required to log such severe issues this often? Why isn't there any limit on frequency and maximum number of retries? That's quite usual with services, isn't it?

**Comment by soletan** [comment]
UPDATE: I thought I was quitting docker before writing this post but it's still running. So I tried to quit again to stop docker writing log files. That's very annoying.

Systray is still indicating running docker, context menu was popping up, but clicking Quit Docker didn't result in popup closing again. It's kept open by now.

![grafik](https://user-images.githubusercontent.com/48088/28770583-fad7c0a6-75df-11e7-9df0-36442b6478ad.png)

And the log file grew from 400 KByte to 2.700 KByte in the meanwhile. Log message hasn't changed since then.

**Comment by fabiogusmao** [comment]
I solved this by adding an exception for Docker for Windows in the Windows Firewall.

**Comment by soletan** [comment]
Well, sounds like a short-term workaround. I'd rather have a solution ;)
