### ISSUE TITLE
Cannot get Docker Desktop to Start

### ISSUE THREAD

**Issue by aselva-eb** [docker/for-win#9627]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [- ] I have uploaded Diagnostics
  - Diagnostics ID: 
A889E80A-A149-4AA0-9C72-F0B14822B0AC/20201126134503 and 
A889E80A-A149-4AA0-9C72-F0B14822B0AC/20201126135618

### Expected behavior

Docker Desktop to start

### Actual behavior

Docker Desktop tries to start, but instead hangs forever.

### Information

  - Windows Version: 10.0.19041
  - Docker Desktop Version: 19.03.13
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Start Docker Desktop
 
I've tried everything found in resolved issues (Switching Daemon, Try to kick off in Power Shell, etc.) with no luck.

**Comment by johan974** [comment]
Same with me here. On win10 the new version 27-11-2020 (2.5.1 or so) is starting ... and haging ;-( I even could not shut it down ... it got angry on me with a red icon ...
