### ISSUE TITLE
Docker error  after update

### ISSUE THREAD

**Issue by ingussmits** [docker/for-win#963]
### Expected behavior
Satar ASP.NET core app in debug mode. 
### Actual behavior
I have created simple visual studio ASP.NET core project with Docker tools support. Before update to version Version 17.06.1-ce-rc1-win20 (12818) it was working fine. Now each time I try to start project in debug mode I have an eror: 
 for dockercompose2192750661_amdb_1  Cannot start service amdb: error while creating mount source path '/C/Users/[user_name]/clrdbg': mkdir /C/Users/[user_name] : permission denied
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu: 97E441FD-5C66-411C-B0F5-F81A510062EB/2017-07-31_15-22-26
 
**Docker file:**
FROM microsoft/aspnetcore:1.1
ARG source
WORKDIR /app
EXPOSE 80
COPY ${source:-obj/Docker/publish} .
ENTRYPOINT ["dotnet", "lib.dll"]

**Docker-compose.vs.debug.yml**
version: '2'

services:
  amdb:
    image: amdb:dev
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    volumes:
      - ./PROJECT:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"

**Comment by jasonbivins** [comment]
Hi @ingussmits 
It looks like your shared drive settings might have gotten dropped in the update - can you check to see if you still have the C: drive shared out?

![image](https://user-images.githubusercontent.com/28021664/28787267-b0c3ed8c-75e9-11e7-81ab-030f481c5dd5.png)

**Comment by ebriney** [comment]
If it don't work, can you please gives a correct compose file (without indentation) as it's yaml and also put a minimal source code to compile that reproduce the issue.

**Comment by ingussmits** [comment]
Shared drive settings is ok: 
![image](https://user-images.githubusercontent.com/3070325/28819474-ffb10362-76b6-11e7-8e78-a58af9725203.png)
I have created a simple Visual Studio project where the same error occurs. The project has all docker files: [WebApplication2.zip](https://github.com/docker/for-win/files/1190163/WebApplication2.zip)

**Comment by louisleong** [comment]
I'm having the exact same issue too
