### ISSUE TITLE
Docker will not start on Windows 10

### ISSUE THREAD

**Issue by ronchittaro** [docker/for-win#9630]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

Diagnostic gathering step never completes. See stack trace below.

### Expected behavior
Daemon should start

### Actual behavior
Daemon does not start

### Information

  - Windows Version: Windows 10 Enterprise
                                  Version 2004
                                  OS build: 19041.630
                                   Windows Feature Experience Pack 120.2212.31.0
  - Docker Desktop Version:
2.5.0.1/2.5.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
No

### Steps to reproduce the behavior

  1. Just install docker, agent won't start.
  2. ...

**Comment by olhao** [comment]
I have the same issue. My diagnostic ID A0C65486-59CE-4AAA-AE97-C814B5792CE5/20201126215935
`$ docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.2
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:00:27 2020
 OS/Arch:           windows/amd64
 Experimental:      false
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
`
Have tried the workaround which had not helped:
`cd "C:\Program Files\Docker\Docker"
./DockerCli.exe -SwitchDaemon`

**Comment by johan974** [comment]
Same issue here. After installing 2.5.0.1 I waited for 10 minutes ... then I get a Docker failed to install. With a red icon. Restarting not possible. Grrr. Updating with a freshly downloaded version is not possible, because Docker is already up to date. So I have no development environment anymore ...

**Comment by gabrielgarciagava** [comment]
@olhao 
I tried a lot of things, but the only thing that really fixed to me was:
- Close Docker on your taskbar
- Open task manager. Kill docker.service (only thing that was still there for me)
- Open PowerShell
Then run:
- cd "C:\Program Files\Docker\Docker"
- ./DockerCli.exe -SwitchDaemon (which did not work for you)
- ./Docker Desktop.exe
After starting through PowerShell, it will ask you to give escalated privilege to start the docker contianers. After that it started instantly to me.
