### ISSUE TITLE
Docker Desktop starting issue

### ISSUE THREAD

**Issue by Nagaraju0669** [docker/for-win#9639]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by johan974** [comment]
Docker version 2.5.0.1 doesn't work on my windows 10 pro. The hyper-v version first keeps on starting ... and finally says it fails. I tried many many solutions ... only removing docker from my PC and re-installing helped for a few restarts. Then the process starts again ... hanging ... failing ... Re-installing ...
