### ISSUE TITLE
97525D85-35A0-4BE9-BAFD-889EAB371B09/20201128110910

### ISSUE THREAD

**Issue by coleanthony** [docker/for-win#9640]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by johan974** [comment]
What's the problem you are facing?
