### ISSUE TITLE
Installation incorrectly rewrites punycode in hosts

### ISSUE THREAD

**Issue by Peter92** [docker/for-win#9642]
### Expected behavior

Hosts file is left the same as it was before, but with the new Docker mappings

### Actual behavior

Mappings to punycode URLs are incorrectly rewritten, with a single dash instead of double dashes.

### Information

I had set up a mapping to [localghost](https://twitter.com/rfreebern/status/1214560971185778693) months ago, and installed Docker a few days ago. Docker rewrote `xn--9q8h` to `xn-9q8h` as it edited the hosts file.

This had a knock on effect with the Python socket module, rendering certain modules such as Flask and Django completely unusable.

  - Windows Version: 10 
  - Docker Desktop Version: 2.5.0.1
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

1. Set a mapping to "127.0.0.1 xn--9q8h" in hosts file
2. Install Docker
3. Hosts file now has "127.0.0.1 xn-9q8h"

**Comment by stephen-turner** [comment]
@Peter92 Thanks for the report, and apologies for the bug. That should certainly not happen. We will fix it.

**Comment by StefanScherer** [comment]
@Peter92 I tried to reproduce the problem, I added some host names with double dashes into  the  hosts file. Then I installed version 3.0.0 and 2.5.0.1, and after starting Docker Desktop the host names were still correct with two  dashes.

```
PS C:\Windows\system32> cat  C:\windows\system32\drivers\etc\hosts
# Copyright (c) 1993-2009 Microsoft Corp.
#
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
#
# This file contains the mappings of IP addresses to host names. Each
# entry should be kept on an individual line. The IP address should
# be placed in the first column followed by the corresponding host name.
# The IP address and the host name should be separated by at least one
# space.
#
# Additionally, comments (such as these) may be inserted on individual
# lines or following the machine name denoted by a '#' symbol.
#
# For example:
#
#      102.54.94.97     rhino.acme.com          # source server
#       38.25.63.10     x.acme.com              # x client host

# localhost name resolution is handled within DNS itself.
#       127.0.0.1       localhost
#       ::1             localhost
127.0.0.1 xn--9q8h
127.0.0.1 foo--bar


# Added by Docker Desktop
172.16.208.149 host.docker.internal
172.16.208.149 gateway.docker.internal
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
```

Do you still encounter this problem or can we close this ticket now?

**Comment by StefanScherer** [comment]
Closing this now, but feel free to add comments or reopen it if you  still see this problem.
