### ISSUE TITLE
Docker Desktop dies and will not restart

### ISSUE THREAD

**Issue by timarrowsmith** [docker/for-win#9643]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 19137552-2F3D-40D7-984B-10D04E58B50D/20201129064022

### Expected behavior
Container continues to run

### Actual behavior
The container "times out" and stops responding to certain kinds of input.  I am unable to get status for containers and any docker commands never return.  I assume this means the docker server is no longer responding.

### Information
This is reproducible by simply waiting.
I have had this problem from the beginning of installation on my computer.  I have reinstalled 3 times and the problem has not gone away.  I am new to Docker so I don't have any history to compare with (and I suspect I am somehow unwittingly to blame).

  - Windows Version: 10 pro
  - Docker Desktop Version: 
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

WSL2 is installed and works fine when the system is working properly.

This happens with any container, including the getting started tutorial.
![Screenshot 2020-11-29 014054](https://user-images.githubusercontent.com/13699372/100535395-8e071500-31e6-11eb-99da-5c15dcfcf5f3.jpg)

**Comment by Leontking** [comment]
I have the same error I made a new issue about this

**Comment by Leontking** [comment]
I Got A link For Docker Toolbox release if works please reply

**Comment by Leontking** [comment]
https://github.com/docker/toolbox/releases/

**Comment by johan974** [comment]
@Leontking - Windows 10 home has no Hyper-V possibility. That's why I had to switch to Windows 10 pro. You can upgrade for about 40. This post is about Windows 10 pro Hyper-v. That is really something different. 
MAYBE (I am not sure) Docker for Windows WSL2 runs on Windows 10 home. Please check.

**Comment by herrSimple** [comment]
@johan974 - It is possible to enable Hyper-V on Win 10 Home. I have been able to enable Hyper-V on Home, and I have WSL2 and Docker Desktop all running without issue on my Win 10 Home (build 19042). Although the process to enable it is a little more convoluted than it is for Win 10 Pro.

**Comment by timarrowsmith** [comment]
I definitely have Windows 10 Pro.  Under Windows Services I see 10 HyperV related services - only 2 of them are running.  Not sure which ones need to be running.  I expected the Install process to adjust that correctly.  Things work fine for a while - no issues.  It's just the time-out that is the problem.  Perhaps someone will understand the second to last line of the diagnostics file, which says "/sysrq failed: Post \"http://unix/sysrq\": open \\\\.\\pipe\\dockerDiagnosticd: The system cannot find the file specified." type=unixsock"

**Comment by timarrowsmith** [comment]
Suddenly Docker just started working fine.  My best guess is it has to do with the quality of the images I am working with.  Before I was using one that was erroring constantly.  Now they all work fine and Docker is not dying.  That's a coincidence hard to ignore.  I don't understand how that would make the daemon not able to restart but... it's another clue.

**Comment by Leontking** [comment]
Just Disable Hyper -v Hyper Visor Or completeu

**Comment by timarrowsmith** [comment]
I spoke too soon - it died again and the restart failed.  Disabled Hyper-V Hyper Visor as suggested and seeing how it goes...
