### ISSUE TITLE
How to change 250G disk size limit. Where is it configured/defined ?

### ISSUE THREAD

**Issue by greg-infa** [docker/for-win#9672]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Clear explanation/documentation where the 250G disk size limit is configured.
### Actual behavior
I can see there is a limit of 250G for overall disk size for all images and containers, but I cannot find any information how to change it, and where is it configured.
### Information

  - Windows Version: 10 Enterprise 1909
  - Docker Desktop Version:
Client: Docker Engine - Community
 Version:           20.10.0-rc1
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        5cc2396
 Built:             Tue Nov 17 22:49:28 2020
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true
Server: Docker Engine - Community
 Engine:
  Version:          20.10.0-rc1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       131bf7e
  Built:            Tue Nov 17 22:52:57 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.4.1
  GitCommit:        c623d1b36f09f8ef6536a057bd658b3aa8632828
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1.  No need to reproduce. I just need an information, which should be, but is not documented.

**Comment by stephen-turner** [comment]
I'm not sure whether I've understood your question but let me try answering it. If you're using the Hyper-V back end, the disk size is set in the settings. It should allow you to use however much space you have available. Do you only have 250GB free space maybe?

**Comment by greg-infa** [comment]
Let mi clarify. I'm using WSL 2 backend (I don't see any sliders with disk size, or any other, in GUI Settings. I've seen some screenshots in documentation(s), for example here https://docs.docker.com/docker-for-windows, but it does not appear in my docker settings.). I have enough free disk space, more than 500G.
When I run `df -h` in any container, I see:
```
Filesystem      Size  Used Avail Use% Mounted on
overlay         251G  146G   93G  62% /
```
I tried to increase the ext4.vhdx storage in WSL2, and in diskpart it shows 272G, for both `...AppData\Local\Docker\wsl\data\ext4.vhdx` and `...AppData\Local\Docker\wsl\distro\ext4.vhdx`:
```
DISKPART> detail vdisk
Device type ID: 0 (Unknown)
Vendor ID: {00000000-0000-0000-0000-000000000000} (Unknown)
State: Added
Virtual size:  272 GB
Physical size:  174 GB
Filename: C:\Users\xyz\AppData\Local\Docker\wsl\data\ext4.vhdx
```
However, this WSL2 vdisk change does not affect the size of space available in Docker (after few restarts of Docker and Windows, of course). Either this 251G is hardcoded in the Docker software (it would be weird), or there is some configuration entry that could be changed somewhere. 

The questions are:
- is there any configuration entry responsible for this 251G size limit ?
- where it is, and how to change it effectively ?

**Comment by stephen-turner** [comment]
In the case of WSL 2, this is managed by Windows not us. But our documentation points to this page from Microsoft: https://docs.microsoft.com/en-us/windows/wsl/compare-versions#expanding-the-size-of-your-wsl-2-virtual-hard-disk

**Comment by greg-infa** [comment]
That's what I did, according to this Microsoft documentation (diskpart, etc.), but the problem is that it does not change the available size in Docker. 
In details, I changed the following `vdisk`s according to this Microsoft documentation:
`C:\Users\xyz\AppData\Local\Docker\wsl\data\ext4.vhdx`
`C:\Users\xyz\AppData\Local\Docker\wsl\distro\ext4.vhdx`
both with `DISKPART> expand vdisk maximum=278528`
When I look at them with `diskpart`, I see that they have 272G.
```
DISKPART> select vdisk file="C:\Users\gswietli\AppData\Local\Docker\wsl\data\ext4.vhdx"

DiskPart successfully selected the virtual disk file.

DISKPART> detail vdisk

Device type ID: 0 (Unknown)
Vendor ID: {00000000-0000-0000-0000-000000000000} (Unknown)
State: Added
Virtual size:  272 GB
Physical size:  174 GB
Filename: C:\Users\gswietli\AppData\Local\Docker\wsl\data\ext4.vhdx
Is Child: No
Parent Filename:
Associated disk#: Not found.

DISKPART> select vdisk file="C:\Users\xyz\AppData\Local\Docker\wsl\distro\ext4.vhdx"

DiskPart successfully selected the virtual disk file.

DISKPART> detail vdisk

Device type ID: 0 (Unknown)
Vendor ID: {00000000-0000-0000-0000-000000000000} (Unknown)
State: Added
Virtual size:  272 GB
Physical size:  111 MB
Filename: C:\Users\xyz\AppData\Local\Docker\wsl\distro\ext4.vhdx
Is Child: No
Parent Filename:
Associated disk#: Not found.
```
The problem is that there is still only 251G available in Docker. 
```
C:\>docker exec -it -u root oracle-xe df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         251G  146G   93G  62% /
tmpfs            64M     0   64M   0% /dev
tmpfs            25G     0   25G   0% /sys/fs/cgroup
shm              64M     0   64M   0% /dev/shm
/dev/sdd        251G  146G   93G  62% /etc/hosts
tmpfs            25G     0   25G   0% /proc/acpi
tmpfs            25G     0   25G   0% /sys/firmware

C:\>docker exec -it -u root edcas-ssh df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         251G  146G   93G  62% /
tmpfs            64M     0   64M   0% /dev
tmpfs            25G     0   25G   0% /sys/fs/cgroup
shm              64M     0   64M   0% /dev/shm
/dev/sdd        251G  146G   93G  62% /etc/hosts
tmpfs            25G     0   25G   0% /proc/acpi
tmpfs            25G     0   25G   0% /sys/firmware
```
So I guess, something needs to be done in Docker, but what ?

**Comment by stephen-turner** [comment]
Hmmm, I'm not sure what else to suggest. I don't think we have any limit or configuration in Docker for this. Let me ask around.

**Comment by simonferquel** [comment]
The problem here is that you resized the virtual disk, but the ext4 partition on it is still 256 GB.
To do that, within wsl, you need to:
- run `sudo lsblk` to identify which Linux device is associated with the virtual disk:
```
❯ sudo lsblk
NAME  MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0   7:0    0 352.7M  1 loop /mnt/wsl/docker-desktop/cli-tools
loop1   7:1    0 304.5M  1 loop
sda     8:0    0   272G  0 disk
sdb     8:16   0   256G  0 disk /mnt/wsl/docker-desktop/docker-desktop-proxy
sdc     8:32   0   256G  0 disk /mnt/wsl/docker-desktop-data/isocache
sdd     8:48   0   256G  0 disk /
```
(in this example, it would be /dev/sda)
- run parted to manipulate the partitions on this device: `sudo parted /dev/sda`
parted has a "resizepart" command that allows you to increase the size of the partition.

**Comment by greg-infa** [comment]
I installed Docker just with pure WSL, without any Linux distributions installed, so it didn't use any linux distro partitions.

In Settings -> Resources, I have "Enable integration with my default WSL distro" unchecked. 
I guess, that you are assuming to use `lsblk` and `parted` on an "integrated linux distribibution" ?

I installed Ubuntu distro afterwards (and only to try to resolve this size problem), but I'm not sure if it would work like this. What I see is just confusing, and trying to use parted in several ways didn't help at all.

Isn't it possible to tell Docker about available disk space directly ?

**Comment by simonferquel** [comment]
Something to note here, is that all WSL2 distros run within the same utility VM, so you can totally use lsbk/parted/fdisk or whatever tool you may be familiar with from Ubuntu to manipulate the docker-desktop disks and paritions. 
So yes, you need to install ubuntu (and make sure it runs in WSL version 2 and not 1), and use the method I described above.

**Comment by greg-infa** [comment]
Thanks a lot ! 
It worked for me. Now I see all the space assigned to vdisk is available in Docker containers.
`parted` or any other re-partitioning in Ubuntu was not necessary here (the space was already allocated to partition in Ubuntu), but `resize2fs` was needed to make it working (in fact it is described in MS documentation, but easy to overlook).
One important thing is: Linux distro have to be installed on WSL 2, and integration with this distro have to be switched on in Docker.
