### ISSUE TITLE
Docker volumes not consistent with host

### ISSUE THREAD

**Issue by samcro1967** [docker/for-win#9674]
- [ X] I have tried with the latest version of my channel (Stable)
  - [X ] I have uploaded Diagnostics
  - Diagnostics ID:  E11EDD8D-D93C-4967-B16C-0526D2A0406D/20201201210848

### Expected behavior
Mount a volume to a container and it sees the same files as the host.

### Actual behavior
Volume mounted to a container sees some of the files, but not all of them.  The files it does see have different last modified dates in some cases.  Touching it on the container is not reflected in the host.  Touching it on the host is also not reflected in the container.

### Information

  - Windows Version: 10.0.19042.630
  - WSL:  Linux version 4.19.128-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020
  - Ubuntu 20.04.1 LTS
  - Docker Desktop Version:  19.03.13, build 4484c46d9d
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:  Inside WSL2 Ubuntu 20.04

### Steps to reproduce the behavior

  1. docker create --name=app1 -e PUID=1000 -e PGID=1000 -e UMASK=000 -v /mnt/c/Users/user1/Documents/Docker/app1:/config
  2. .docker exec -it app1 bash
  3.  cd /config
  4.  ls -al shows missing files and the wrong last modified dates for files as compared to ls -al of /mnt/c/Users/user1/Documents/Docker/app1 from Ubunut and Windows Explorer.  Dates and file between Ubuntu and Widows match.

**Comment by stephen-turner** [comment]
This is explained at https://docs.docker.com/docker-for-windows/wsl/

**Comment by samcro1967** [comment]
Thanks for the reply.  I reviewed the link prior to logging the issues and it is how my environment is setup.  In my original post above I mentioned that I am already mounting the volume via wsl.  It does say to mount via ~/ versus /mnt/c for better performance, but I do not see any reference to a known consistency issues if you use /mnt/c.  Can you confirm it is also a known issues that using /mnt/c causes consistency issues as well as performance issues?

**Comment by stephen-turner** [comment]
Sorry, I should have given a longer answer. There shouldn't be a consistency problem for a new container, so I suspected your problem was this one "Linux containers only receive file change events (“inotify events”) if the original files are stored in the Linux filesystem."

In any case, we do not manage the file sharing in the WSL 2 case, it's wholly managed by Windows.

**Comment by samcro1967** [comment]
Ok.  I think what you are saying is that a container being hosted by WSL will not see any file updates to files in /mnt after the container is created.  I can confirm that is not the case.  It is just sporadic.  Some file updates are seen and others are not.  It is not isolated to any particular container either.  I see it across numerous containers and it is usually the same files missing from multiple containers.

I can also confirm removing a container and re-adding it does not cause it to see the missing files.  Guessing this is a caching issue somewhere I have yet figured out how to flush before recreating the container.

**Comment by WagnerSilveira** [comment]
I have witnessed the same problem here, sometimes files binds correctly with host's file, sometimes not.
it started happening after 2.5.0 release.
I do not use wsl2 for docker containers.
