### ISSUE TITLE
Kitematic fails to start on windows 7

### ISSUE THREAD

**Issue by sarveshkaushal** [docker/for-win#97]
### Actual behavior- Kitematic fails with following error-'we 're sorry! There seems to have been an unexpected error with Kitematic.
 Error: connect ENOENT //./pipe/docker_engine
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...Install docker-toolbox on Windows 7. 
  2. ...Launch Kitematic by double clicking on Kitematic icon in desktop.
![image](https://cloud.githubusercontent.com/assets/19580065/18773203/b82f5328-8101-11e6-9e84-c218e28349b0.png)

**Comment by friism** [comment]
Thanks for reporting - this tracker is for issues with Docker for Windows, so I recommend re-opening on either the [Toolbox](https://github.com/docker/toolbox/) or [Kitematic](https://github.com/docker/kitematic) issue trackers.
