### ISSUE TITLE
Switch to OS container is grayed out from Docker Desktop!!!

### ISSUE THREAD

**Issue by yeasin90** [docker/for-win#9701]
Hi,
I am trying **Switch to Linux container..**, but it's grayed out : 
![container-swich-grayed-out](https://user-images.githubusercontent.com/8789577/101260826-c665a080-375c-11eb-8e3f-206106721541.jpg)

Can someone help please?

### Expected behavior
I am using Windows and Docker Desktop as per pre-requisite. Or am I missing something?

### Information

  - Windows Version: **Windows 10 Home 64-bit build 19042**
  - Docker Desktop Version: **2.5.3 (50261)**
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: **Running at my Windows 10 laptop**

**Comment by StefanScherer** [comment]
You cannot switch to Windows Containers, even if you try to edit the `settings.json` ;-)
Docker Desktop on Windows 10 Home is only able to run Linux Containers with the WSL 2 backend, that's why the menu item is grayed out.
