### ISSUE TITLE
Docker hv-sock proxy (vsudd) is not reachable

### ISSUE THREAD

**Issue by WillNye** [docker/for-win#971]
### Expected behavior
Docker starts
### Actual behavior
Docker crashes
### Information
Build Info:
Version: 17.06.0-ce-win19 (12801)
Channel: stable
Sha1: c98c1c25e05a39ca8ef5394baa1d68f92f8e5008
Started on: 2017/08/02 14:18:13.527
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1703
Build: 15063 & 14393
BuildLabName: 15063.0.amd64fre.rs2_release.170317-1834

#### Diagnostic Id: 007C72D5-6F84-43FE-A1E6-0A19FDB3EF88/2017-08-02_14-18-20

  I have been running Docker without issue since 6/27 in a swarm on 3 different physical hosts until 8/1 when each system crashed with the following error:

```
Docker hv-sock proxy (vsudd) is not reachable
   at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```
I was able to get our one system that runs Windows Server 2016 working after some updates but the 2 running Windows 10 will not come back up. 

Things I've tried in various order:

1. DNS Flush
2. Update Windows 
3. Update Docker
4. Disabled Docker experimental features
5. Disable Hyper-V and let Docker re-enable it
6. Hyper-V back to factory settings
7. Turned off auto start for Docker (verifying it ran as admin)
8. Uninstall/ Reinstall Docker

Issues I've referenced:
#271 #447 #568 #606 #614 #904 #970 

Note:
I've always ran Docker For Windows as Admin so I didn't add it in things I've tried

### Steps to reproduce the behavior
Install Docker on Windows 10? 

## EDIT:
Our Boot2Docker instance on Windows Server 2016 is running but it appears to be having issues. I was just going to throw an ubuntu instance on the other 2 machines and add them to the swarm but the vm hangs when I try to get the join token.

**Comment by ResourceHog** [comment]
I too have the same exact error.

**Comment by rni-iwanaga** [comment]
i have the same error.

B6814FCC-9424-4777-97A5-ABB1D3D197E9/2017-08-03_16-32-15

**Comment by jasonbivins** [comment]
@WillNye 
Can you check to see if the Docker for Windows service is running?  It doesn't seem to be up and connected from what I see in the logs.

**Comment by jasonbivins** [comment]
@rni-iwanaga   You're getting the same error - can you try to restart the Docker for Windows service as well?  You can also try stopping the service - setting it to manual and then restarting.  Docker will pop up and ask you to start when windows starts.

**Comment by WillNye** [comment]
@jasonbivins 

I think it may have not come back up after one of the times I ran the logs
I did start the service on a different machine that is experiencing the same issue as the server (we've since moved the docker nodes to an Ubuntu VM) where it hangs when waiting for SSH to be available. 

## Diagnostic ID: 1C3AC770-FD9B-45A2-8F1F-AB9907B8F4D5/2017-08-03_11-28-47

**Comment by Reppinger** [comment]
I am getting this also. In my case I'm running Windows 10 Pro in a Parallels VM. I allowed Docker to turn on Hyper-V. Docker Service is running.

**Comment by rni-iwanaga** [comment]
@jasonbivins 
I tried to restart the service. B6814FCC-9424-4777-97A5-ABB1D3D197E9/2017-08-09_11-38-14
Manual starts and On/Off Hyper-v didn't work also. (I got the same error)

**Comment by sryabkov** [comment]
A variation of what @Reppinger did, worked for me too (I didn't do anything with the proxy settings). I have the same setup: Windows 10 (1703) Pro in a Parallels 12 VM. The original problem started happening after I switched from Windows to Linux containers.

**Comment by kai2nenobu** [comment]
I experienced the same error, but I recovered as below (like [@spewu in #792](https://github.com/docker/for-win/issues/792#issuecomment-307387823)).

1. `Switch to Windows container...` from system tray
2. Restart my machine
3. Docker (for Windows containers) starts automatically with no errors
4. `Switch to Linux containers...` from system tray

After this procedure, docker has worked as expected.

Information

```
Version: 17.06.0-ce-win19 (12801)
Channel: stable
Sha1: c98c1c25e05a39ca8ef5394baa1d68f92f8e5008
Started on: 2017/08/10 22:36:50.684
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1703
Build: 15063
BuildLabName: 15063.0.amd64fre.rs2_release.170317-1834
```

**Comment by qianxinfeng** [comment]
1.Switch to Windows container, it is ok!
2.Switch to Linux containers, I got same error

**Comment by xtophs** [comment]
Switching to Windows containers, then back to Linux containers. 
Things start working without a reboot in between.

**Comment by alphen** [comment]
Experienced the same error, managed to got it running again after the following steps;
* Close the 2 Docker services; "Docker for windows" and "Docker.Service".
* Run Docker for Windows as administrator.

**Comment by awidjaja** [comment]
I have the same issue
https://github.com/docker/for-win/issues/1119

please help

**Comment by tsasioglu** [comment]
Restarting the Docker for Windows service fixed the issue for me.

**Comment by ierturk** [comment]
I got the same issue for a while. It seems to be related with `Git for Windows` on my `Windows 10 x64` system. When I removed `GFW`, `Docker for Windows` runs as expected. So I tried to install `GFW` separately from `Windows` environment (`Git` commands only available from `Git Bash` but not `Windows CMD` or `PowerShell`), again `DFW` is OK.

So I think there is a conflict between `DFW` and `GFW` environments. I hope `DFW` keep work as is. Hope this helps.

**Comment by tranquyetdev** [comment]
After try many solutions above, Docker still did not run on my Window 10 Pro lastest version. I decide to remove Docker for window Stable version, and then install Edge version,  => restart machine => Run Docker by Administrator =? It works now. Awesome :))

**Comment by dschulten** [comment]
I could not find a way to solve this so far. My Windows Version according to systeminfo in cmd is:
```
Betriebssystemname:                            Microsoft Windows 10 Pro
Betriebssystemversion:                         10.0.16299 Nicht zutreffend Build 16299
```
Restarting the Docker for Windows service did not help.
Installing the edge version 0.18.2 did not help.
Removing the git folder from PATH did not help either (git no longer found in cmd).

**Comment by arthurdn** [comment]
**Removing or changing** of priority for third party software with **high CPU consumption** fixed everything.

**Comment by ctmcisco** [comment]
For anyone following this ticket:

Try the following:

1. Switch or stay on Windows Containers.
2. Disable the "Start when Windows starts" setting.


![image](https://user-images.githubusercontent.com/14852041/37053107-e9a96bd8-2140-11e8-9bdf-b264980b6127.png)

3. Exit Docker application
4. restart docker services via PowerShell

get-service *docker* | Restart-Service -Force -Verbose

5. Launch Docker , Run as Admin
6. Swtich to Linux Containers.

TEST:

Reboot Windows 10
Launch Docker 
Does it work?

You can also parse the docker log in PowerShell for troubleshooting:

cat C:\Users\USERPROFILE\AppData\Local\Docker\log.txt -tail 10 -wait

**Comment by csaladenes** [comment]
Run as admin fixed it.

**Comment by veeshall** [comment]
Installed the Edge Version (instead of Stable Version) - and its working fine now
