### ISSUE TITLE
Suddenly container couldn't connect 192.168.1.17 LAN

### ISSUE THREAD

**Issue by chuoke** [docker/for-win#9716]
I use this docker on my computer for development for half a year. Everything is ok until this morning. When I start coding and  I can't connect to an outside MySQL server, which IP is 192.168.1.17 in a LAN. I turn to the container's CLI try to ping the IP, and it no response. But in my host machine, I can use a tool to connect the MySQL server and normal working. 

### Expected behavior
Can connect to the server located 192.168.1.***.

I want to know why or what can't make this error? It better that there is a solution to solve it.

### Actual behavior
Can't connect to the server located 192.168.1.***.

### Information 
  - Windows Version: Windows 10 1909
  - Docker Desktop Version: 2.5.01

**Comment by MarkusRodler** [comment]
@chuoke did you find a solution? I seems that I have the same problem.
I am using Docker for Windows 3.0.4 with the WSL2 integration and I have an server inside my LAN (192.168.1.11) that is hosting MySql on port 3306.
I noticed today that I'm not able to connect to my server inside the docker container. So i tried a few things:
- telnet 192.168.1.11 inside the docker container times out...
- telnet 192.168.1.11 inside my Debian works as expected
- MySql Workbench in Windows is able to connect to the server

I'm no expert in configuring networking but maybe it is something with iptables?

**Comment by chuoke** [comment]
@MarkusRodler not really.  I reinstalled docker after I tried restart docker and recreate network

**Comment by MarkusRodler** [comment]
Does a docker reinstall work?
I tried it from my work-pc (similiar setup) and there it works without problems...
