### ISSUE TITLE
VSCode reopen in container: Docker returned an error make sure the docker daemon is running 

### ISSUE THREAD

**Issue by ioanna-tsak** [docker/for-win#9721]
I want to open a project that I have been working before on, in VScode with a remote container. So I try to `reopen in container`. 
### Expected behavior
- The project opens in the remote container

### Actual Behavior
- I get the error:
```Docker returned an error. Make sure the docker daemon is running```
    and in the terminal log I get this message:
```spawn C:\Users\...\AppData\Local\Programs\Microsoft VS Code\docker ENOENT```

### Information
-  Windows Version: 10
- Docker Desktop: 2.5.0.1 (latest update installed 07/12/20)
- Problem started after 3/12/20
- The problem existed both before and after the last update

**Comment by stephen-turner** [comment]
This sounds like a bug with the Visual Studio plugin, not a Docker Desktop bug. The plugin should make sure that docker is running before trying to send commands to it.
