### ISSUE TITLE
Docker stuck on everything I do. Stuck on starting..., stuck on uninstalling... stuck stuck stuck

### ISSUE THREAD

**Issue by Vardan92** [docker/for-win#9726]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Vardan92** [comment]
Tried deleting everything and reinstalling (barely). Still same issue. Version is up to date. And it was working fine yesterday. Now randomly just not working

**Comment by javaddd** [comment]
Menu -> Troubleshoot -> clear/purge data may help.
