### ISSUE TITLE
Option “-Include” fails while creating an archieve

### ISSUE THREAD

**Issue by alexia19apl** [docker/for-win#9749]
**OS**
Windows 2016 Datacenter Edition
**Powershell version**
5.1

**Case**
Fetching some files and folder from a directory and afterward create an archive to be later used.
First Script search the required folders, files and exclude a few via "-Exclude" option, this scripts works flawlessly, see code below:

    enter code here
    $CompressConfig = @{
      Path = Get-ChildItem -Path "F:\Artifact_Handover\Extracted_Handover_Files\FinalFolder\" -Exclude @("folder3", "file7","file8")
      DestinationPath = "F:\Artifact_Handover\Extracted_Handover_Files\MyArchieve.zip"
      CompressionLevel = "Optimal"
    }
    Compress-Archive @CompressConfig -Force

Second Script is very similar because also search the required folders, files and include a few via "-Include" option, this fails, see code below:

    $CompressConfig = @{
      Path = Get-ChildItem -Path "F:\Artifact_Handover\Extracted_Handover_Files\FinalFolder\" -Include @("folder1", "file1","file2")
      DestinationPath = "F:\Artifact_Handover\Extracted_Handover_Files\MyArchieve.zip"
      CompressionLevel = "Optimal"
    }
    Compress-Archive @CompressConfig -Force

If we search the official Powershell help can be seen that syntax is exactly the same for both cases "-Exclude" and "-Include"
Get-ChildItem [[-Path] <System.String[]>] [[-Filter] <System.String>] [-Attributes {Archive | Compressed | Device | Directory | Encrypted | Hidden | IntegrityStream |
    Normal | NoScrubData | NotContentIndexed | Offline | ReadOnly | ReparsePoint | SparseFile | System | Temporary}] [-Depth <System.UInt32>] [-Directory] [**-Exclude**
    <System.String[]>] [-File] [-Force] [-Hidden] [**-Include** <System.String[]>] [-Name] [-ReadOnly] [-Recurse] [-System] [-UseTransaction] [<CommonParameters>]

What am I missing here? thanks in advance community.

**Comment by stephen-turner** [comment]
I think you posted this in the wrong place. I'm not sure where it should go, but it doesn't seem to have anything to do with Docker Desktop.
