### ISSUE TITLE
System.InvalidOperationException:

### ISSUE THREAD

**Issue by roma9016** [docker/for-win#9753]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 09AACE44-FECB-4113-B073-5E3F3D3E513A/20201210121818

### Expected behavior
Docker is running
### Actual behavior
Docker is starting ... and it remains in that mode 

### Information

  - Windows Version: Windows 10 Pro: 1909: compilation:18363.1256
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
no

### Steps to reproduce the behavior

  1. ...
[20201210121818.zip](https://github.com/docker/for-win/files/5672817/20201210121818.zip)

  2. ...

**Comment by morphine00** [comment]
Can't start Docker after an upgrade to 3.0.0 (50684) either from the previous stable version.

- Windows 10 v2004, build 19041.685.
- Using Hyper-V backend.
- WSL2 is enabled but Docker isn't using it.
- Kubernetes not enabled.

Diagnostics: [20201210155802.zip](https://github.com/docker/for-win/files/5674108/20201210155802.zip)

**Comment by morphine00** [comment]
Additional information: when uninstalling 3.0.0 in an attempt to downgrade, the uninstaller got stuck at "Removing VM and images."

**Comment by morphine00** [comment]
Okay, got it to work.

Solution: **uninstall Docker completely and install it again.**

Warning: **All your containers will be deleted when you uninstall and will need to be rebuilt**

**Comment by Jossec101** [comment]
I confirm @morphine00, I had to uninstall and then install it again, *sigh*.

**Comment by adnoh** [comment]
any chance to backup the local volumes first? my moby vm is starting if I start it manually with hyper-v - but docker itself is not (so i can't run a ssh container). I can't just nuke the volumes :(
