### ISSUE TITLE
Docker Issues

### ISSUE THREAD

**Issue by PeterKoppelman** [docker/for-win#9756]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by PeterKoppelman** [comment]
Something went wrong when I upgraded to the newest release.

**Comment by tiborvass** [comment]
You are most likely hitting #9755 but since you didn't provide any actionable information or diagnostic ID, I'm closing the issue. Feel free to add more details and it may then be reopened.
