### ISSUE TITLE
Docker Install Failure on Windows

### ISSUE THREAD

**Issue by witchpiggie** [docker/for-win#9758]
### Expected behavior
Docker Updates

### Actual behavior
Docker Uninstalls, then fails to install

### Information
This has happened every time I've tried to upgrade docker on windows. I see at least one previously closed issue with this exact error.

Windows 10 x64

```
The process cannot access the file 'C:\Program Files\Docker\Docker' because it is being used by another process.
   at CommunityInstaller.FileSystem.<Delete>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.UninstallWorkflow.<ProcessAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<PerformUninstall>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<UninstallAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()

```
### Steps to reproduce the behavior
Install old version of Docker. Run upgrade when prompted.

**Comment by NateThompson114** [comment]
Yeah... not working for me, I can install none of the other versions...

Unpacking failed: The requested operation cannot be performed on a file with a user-mapped section open.

   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()

**Comment by NateThompson114** [comment]
Couldn't install any version, seemed to be a locked file, restarted my computer after docker uninstalled itself and installed 3 again and it worked, really should add version naming to docker desktop installs lol.

**Comment by sdktr** [comment]
I've the same issue with 3.0.4

**Comment by sdktr** [comment]
Workaround I used to get a working docker-desktop is using [chocolatey](https://chocolatey.org/packages/docker-desktop) based installer.

`choco install docker-desktop --upgrade --force`

**Comment by markdbuck** [comment]
choco install resulted in same error as using the Docker installer. did you do something else differently @sdktr?

```
Installing docker-desktop...
[14:07:27.269] [InstallWorkflow] Installation failed
Exception type: System.Exception, Exception message: Failed to register product: The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE)), StackTrace:
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
ERROR: Running ["C:\Users\MarkBuck\AppData\Local\Temp\chocolatey\docker-desktop\3.2.1\Docker Desktop Installer.exe" install --quiet ] was not successful. Exit code was '1'. See log for possible error messages.
  docker-desktop may be able to be automatically uninstalled.
The install of docker-desktop was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\docker-desktop\tools\chocolateyinstall.ps1'.
 See log for details.
```

**Comment by earthengine** [comment]
@markdbuck Same problem, same trial. same result.

**Comment by GLaveli** [comment]
@markdbuck Same problem here.

**Comment by earthengine** [comment]
I end up reinstalling Windows 10 20H2, and install docker from scratch. This worked. But I don't think everyone can afford it.

**Comment by uded** [comment]
Definitely not a solution, as it would take ages for me to reinstall Windows and all software that goes along with my desktop. 

Any other ideas?

**Comment by markdbuck** [comment]
I have gone back to version 2.5 which installs fine. You may have to manually remove registry entries to get this to work. See [https://github.com/docker/for-win/issues/1371](this)

**Comment by uded** [comment]
That link take me to no result. Still stuck :-(

**Comment by markdbuck** [comment]
Sorry about the broken link. I went back to version 2.5.0 but had to remove the Docker Desktop entry from the registry after the failed v 3.x install before it would allow me to install 2.5.0. This image shows what the registry entry looks like for me with 2.5.0, presumably yours will reflect the failure of 3.x install.
![image](https://user-images.githubusercontent.com/490972/111145430-9e0cef80-855e-11eb-856e-d5105a43c03a.png)

**Comment by uded** [comment]
Unfortunately, that has no effect on me. I used CCLeaner to clean up the registry, so even before your update, I had no such entry anymore. Still, no luck.

**Comment by markdbuck** [comment]
@uded , sorry, I did not have any issues installing version 2.5.0

**Comment by Seriels** [comment]
I also encountered this problem 

Version: 3.2.2 (61853)
Sha1: fbc469ea20765e26b178d7dd99adb671611f3c42
Started on: 2021/03/19 11:09:42.498
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro for Workstations
Edition: ProfessionalWorkstation
Id: 2009
Build: 19042
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\Users\seriels\AppData\Local\Docker\install-log.txt
CommandLine: "C:\Program Files\Docker\Docker\InstallerCli.exe" -i
You can send feedback, including this log file, at https://github.com/docker/for-win/issues

error 

[11:11:24.611][InstallWorkflow] Installation failed
Exception type: System.Exception, Exception message: Failed to register product: 检索 COM 类工厂中 CLSID 为 {1ECCA34C-E88A-44E3-8D6A-8921BDE9E452} 的组件失败，原因是出现以下错误: 80080005 服务器运行失败 (异常来自 HRESULT:0x80080005 (CO_E_SERVER_EXEC_FAILURE))。, StackTrace:
   在 CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

I don't know what to do with it      TAT TAT TAT

**Comment by elkaz** [comment]
Receiving the same error on Windows 10.

Docker Desktop uninstalled itself, and when attempting to re-install it failed.
Tried the Chocolatey workaround but this also failed.

**Comment by uded** [comment]
This issue is ongoing for a lot of folks as I can see around the net. Waiting for a fix hopefully...

**Comment by jlhaugen** [comment]
Currently happening to me as well. the worst part is that failed installation doesn't clean its self up.

**Comment by uded** [comment]
I think (almost I am not certain) I cleaned up everything -- all folder and registry. Still, it doesn't seem to fix the issue. And I am still puzzled when it comes to figuring out the root cause of this problem...

**Comment by markdbuck** [comment]
@uded what happens when you try to reinstall the older 2.5 version which doesn't have this issue?

**Comment by uded** [comment]
Halts and stalls completely, nothing happens for over an hour. Then I usually kill the install process and clean up manually all the files created in the meantime.

**Comment by elkaz** [comment]
The install finally worked for me. Graceful restarts didn't resolve the issue, but after a forced restart of my machine the install worked successfully.

**Comment by uded** [comment]
I will try to fully restart my Windows machine. Might get interesting :-)

**Comment by sdktr** [comment]
Same problem present on my system, while upgrading to 3.2.2 with Chocolatey

> 2021-03-29 23:03:22,444 10776 [INFO ] - VERBOSE: Installation failed
2021-03-29 23:03:22,446 10776 [INFO ] - VERBOSE: Failed to register product: The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE))
2021-03-29 23:03:22,452 10776 [INFO ] - VERBOSE:    at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
2021-03-29 23:03:22,457 10776 [INFO ] - VERBOSE: --- End of stack trace from previous location where exception was thrown ---
2021-03-29 23:03:22,461 10776 [INFO ] - VERBOSE:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-03-29 23:03:22,464 10776 [INFO ] - VERBOSE:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-03-29 23:03:22,472 10776 [INFO ] - VERBOSE:    at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
2021-03-29 23:03:22,500 10776 [ERROR] - [23:00:11.174] [UninstallWorkflow] Failed to unregister
2021-03-29 23:03:22,513 10776 [ERROR] - Exception type: System.Runtime.InteropServices.COMException, Exception message: The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE)), StackTrace:
2021-03-29 23:03:22,521 10776 [ERROR] -    at WindowsBits.IBackgroundCopyJob.Cancel()
2021-03-29 23:03:22,527 10776 [ERROR] -    at CommunityInstaller.UninstallWorkflow.<ProcessAsync>d__14.MoveNext()
2021-03-29 23:03:22,533 10776 [ERROR] - [23:03:17.516] [InstallWorkflow] Installation failed
2021-03-29 23:03:22,540 10776 [ERROR] - Exception type: System.Exception, Exception message: Failed to register product: The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE)), StackTrace:
2021-03-29 23:03:22,546 10776 [ERROR] -    at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
2021-03-29 23:03:22,552 10776 [ERROR] - --- End of stack trace from previous location where exception was thrown ---
2021-03-29 23:03:22,556 10776 [ERROR] -    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-03-29 23:03:22,565 10776 [ERROR] -    at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
2021-03-29 23:03:22,572 10776 [ERROR] -    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-03-29 23:03:22,577 10776 [DEBUG] - Command ["C:\Users\sdekooter_prox1\AppData\Local\Temp\chocolatey\docker-desktop\3.2.2\Docker Desktop Installer.exe" install --quiet ] exited with '1'.
2021-03-29 23:03:22,642 10776 [ERROR] - ERROR: Running ["C:\Users\sdekooter_prox1\AppData\Local\Temp\chocolatey\docker-desktop\3.2.2\Docker Desktop Installer.exe" install --quiet ] was not successful. Exit code was '1'. See log for possible error messages.
2021-03-29 23:03:22,653 10776 [DEBUG] - Built-in PowerShell host called with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\docker-desktop\tools\chocolateyinstall.ps1' -installArguments '' -packageParameters '''] exited with '1'.
2021-03-29 23:03:22,657 10776 [DEBUG] - Calling command ['"C:\windows\System32\shutdown.exe" /a']
2021-03-29 23:03:22,779 10776 [DEBUG] - Command ['"C:\windows\System32\shutdown.exe" /a'] exited with '1116'
2021-03-29 23:03:22,897 10776 [INFO ] -   docker-desktop may be able to be automatically uninstalled.

**Comment by jaytaph** [comment]
same here...

**Comment by ractyfree** [comment]
+

> I will try to fully restart my Windows machine. Might get interesting :-)
> 
> Update: full restart, cache clean up, etc. -- still failing, same error:
> 
> ```
> Component CommunityInstaller.EnableFeaturesAction failed: Not found 
>    w CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
> --- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
>    w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    w CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
> ```
> 
> Update2: So the problem will happen if one will install the WSL2 components/extension/etc. during the install process. Skipping them and the installer will not fail. But, at least for me, docker won't work as well as a result.
> 
> WSL2 was already present on my Windows, and it seems to be running correctly as well:
> 
> ```
> PS C:\Users\uded> wsl --list --verbose
>   NAME                   STATE           VERSION
> * Ubuntu                 Stopped         1
>   docker-desktop         Running         2
>   docker-desktop-data    Stopped         2
> ```
> 
> Docker service is reportedly running, but not usable. Also, the Docker desktop app is showing a never-ending "Starting". I am uncertain if there are any logs I can grab for this.
> 
> ```
> PS C:\Users\uded> docker run --name XXXX XXXXX/XXXXX
> docker: Error response from daemon: open \\.\pipe\docker_engine_linux: The system cannot find the file specified.
> See 'docker run --help'.
> ```

The exact same log and situation happened on fresh docker installation after the wsl2 installation. Resolved via unchecking 'Install required WSL2 comp...'.
Windows 10 Home single language(RU)
2004 X64

**Comment by ractyfree** [comment]
> docker: Error response from daemon: open \\.\pipe\docker_engine_linux: The system cannot find the file specified.
> See 'docker run --help'.

And
`docker: Error response from daemon: open \\.\pipe\docker_engine_linux: The system cannot find the file specified.
See 'docker run --help'.`
Was solved to me either randomly(I hadn't gotten it), or because in services I made Docker Service to run no 'automatically', but 'automatically(delayed)'

**Comment by iguissouma** [comment]
Receiving the same error on Windows 10.

Docker Desktop uninstalled itself, and when attempting to re-install it failed.
Tried the Chocolatey workaround but this also failed.
Tried the "power" workaround but this also failed..
Tried to instal wsl and set version to 2.
After many restart it still failing...

**Comment by iguissouma** [comment]
What worked for me is adding this key with regedit on
"HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control"
ServicesPipeTimeout=dword:0000ea60

**Comment by markdbuck** [comment]
@iguissouma there are multiple errors mentioned in this thread. Which were you having? Handle is invalid?

**Comment by iguissouma** [comment]
@markdbuck I got an error like  that says the intalation failed because the the service didn't start in time.
I got a stack trace containing this:
`communityinstaller.installworkflow.<dohandled4wpackageasync>d__29.movenext()`

**Comment by markdbuck** [comment]
@iguissouma thanks for the clarification.

**Comment by indoben** [comment]
Have been running into the `Failed to finish background job: The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE))` error as well since the release of the first 3.0 version. We've been stuck on 2.5.0.1. Really hope someone figures this out soon.

**Comment by owhcom** [comment]
i pretty tried every 3.x version and they all failed, went back to 2.5 and it installed no issues

**Comment by uded** [comment]
I can be mistaken (so, please correct if that is the case) but version 2.x had no WSL2 support and, as a result, was less performant and efficient.

**Comment by indoben** [comment]
@uded That's kinda true, I attempt the install for 3.0+ and it failed as mentioned above, but when I rolled it back to 2.5.0.1 i was able to enable WSL for that version. It works but the builds are SLOW.

**Comment by jochenw** [comment]
Just today, from the 3.3.1 installer:

Failed to finish background job: The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE))
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()

The worst thing: My system is now in an undefined state.

- If I rerun the installer, it claims, that 3.3.1 is already installed.
- If I do a manual cleanup of the registry, and a restart, then I get the same result.
- The directory c:\Program Files\Docker is completely empty.
- For the same reason, I can't use "Add or Remove Programs" to deinstall Docker. (It would use "c:\Program Files\Docker\Docker\Docker Desktop Installer.exe"
- Deinstalling fails, too:

c:\Users\jwi\Downloads>".\Docker Desktop Installer 3.3.1.exe" uninstall

        c:\Users\jwi\Downloads>[17:37:32.216] [ManifestAndExistingInstallationLoader] No install path specified, looking for default 
        installation registry key
        [17:37:32.218] [Program] Existing installation found: version=63152, displayVersion=3.3.1, basePath=C:\Program 
        Files\Docker\Docker, channelUrl=https://desktop.docker.com/win/stable/amd64/appcast.xml
        Failed to track the uninstall started event

A Window opens, but never appears to do anything, and doesn't terminate.

**Comment by indoben** [comment]
@jochenw So this happened to me as well. I normally clear out the 2 dir in Program Data and the one in Program Files. I then use the Control Panel > Programs and Features to remove the failed Docker entry. Then a new install should work. Hope it works for you, it worked for me twice last week.

**Comment by ZergD** [comment]
> Receiving the same error on Windows 10.
> 
> Docker Desktop uninstalled itself, and when attempting to re-install it failed.
> Tried the Chocolatey workaround but this also failed.
> Tried the "power" workaround but this also failed..
> Tried to instal wsl and set version to 2.
> After many restart it still failing...

Same here. Exactly the same happened on my side...

**Comment by AndiHamolli** [comment]
Any updates? I have tried 3.3.1, 3.3.0, a recent 2.6 and i got the exact same error in all of them.
I really don't know what to do.
![image](https://user-images.githubusercontent.com/17026910/116399009-babc6880-a828-11eb-82f7-db43fea883dd.png)

**Comment by uded** [comment]
You can go back to Hyper-V and 2.x architecture, but the performance difference with WSL2 is significant as I could observe before.

I think we still need to wait for the fix, as this ticket was assigned to 3.2.2 version and it has 18 tickets still open...

**Comment by 89z** [comment]
https://github.com/docker/for-mac/issues/5605

https://github.com/docker/for-win/issues/9758
https://github.com/docker/for-win/issues/9780

**Comment by 89z** [comment]
https://github.com/docker/for-win/issues/6091

https://github.com/docker/for-win/issues/9758

**Comment by 89z** [comment]
https://github.com/docker/for-win/issues/11133

https://github.com/docker/for-win/issues/9758
https://github.com/docker/for-win/issues/9780

**Comment by 89z** [comment]
To anyone getting this error:

~~~
Component CommunityInstaller.EnableFeaturesAction failed
~~~

The fix for me was enabling this service:

~~~
Windows Modules Installer
~~~

Note I used a tool [1] to do this, but I think you can also just use the normal Service App.

1. https://github.com/WereDev/Wu10Man

**Comment by uded** [comment]
Checked on my end and still same result.

**Comment by jackkelly-bayliss** [comment]
> To anyone getting this error:
> 
> ```
> Component CommunityInstaller.EnableFeaturesAction failed
> ```
> 
> The fix for me was enabling this service:
> 
> ```
> Windows Modules Installer
> ```
> 
> Note I used a tool [1] to do this, but I think you can also just use the normal Services App.
> 
> 1. https://github.com/WereDev/Wu10Man

Still the same result unfortunately :(

**Comment by markdbuck** [comment]
I was finally able to upgrade to 3.4.0, no more "failed to register invalid handle".

**Comment by indoben** [comment]
> I was finally able to upgrade to 3.4.0, no more "failed to register invalid handle".

Can confirm, all the "handle" related install/upgrade errors that I was seeing have disappeared with the 3.5.2 version that I installed today.

**Comment by leggant** [comment]
tried installing for the first time on my PC this morning, so that I can start learning Docker and this is what I get........
Does anyone understand this error(s) and how to fix the issue?
```
Unpacking failed: Data Error
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
```

**Comment by mpindado** [comment]
I have been suffering all possible random problems described here with a corporate laptop and none of the solutions worked for me:
- Sometimes installer does not start and get a dll problem in the event viewer. 
- Sometimes the program installs but does not start with the dll problem event.
- Sometimes I receive the CommunityInstaller.InstallWorkflow.d__29.MoveNext()

Finally I have just make it work by executing the installer in Compatibility mode (windows 8) and starting also in compatibility mode.

I think all of these problems are related to antivirus SW in corporate laptops with older windows kernels (Mine is 1909).

**Comment by YAOHAO9** [comment]
Remove all docker folder (C:\Program Files、C:\ProgramData、C:\Users\xxx\.docker) and reinstall，you will success。

**Comment by Shiva-K-7** [comment]
I had a similar issue, I removed all the docker related files from previous installation on c:users/user_name/app/local. It worked for me, it may be helpful

**Comment by SubratKumarGupta** [comment]
installing wsl separately with "wsl --install" and then installing docker  by using the desktop installer with the option install wsl 2 unchecked worked for me 
https://docs.microsoft.com/en-us/windows/wsl/install

**Comment by AbubakarShf** [comment]
> Yeah... not working for me, I can install none of the other versions...
> 
> Unpacking failed: The requested operation cannot be performed on a file with a user-mapped section open.
> 
> at CommunityInstaller.InstallWorkflow.d__29.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at CommunityInstaller.InstallWorkflow.d__23.MoveNext()
> 
> **UPDATE:** Seemed to be a locked file, restarted my computer after docker uninstalled itself and installed 3 again and it worked, really should add version naming to docker desktop installs lol.

I was installing the latest version of docker and getting the same error. When I install dockor 3.5.1(older version) then my issue is fixed.

**Comment by cre8design** [comment]
Had a similiar issue. In my case it was just a broken download which i could fix by just downloading the executable again.

**Comment by GarnetSunset** [comment]
Having this issue again as of today, through chocolatey and through the downloaded latest.

**Comment by ammwinchande** [comment]
Had a similar issue. I resolved the issue by completely removing old Docker Desktop which you should check it's removal from the installation path - on Windows `C:\Program Files\Docker`, if it exists remove the directory I used **Revo Uninstaller** for this.

Then, reinstall the Docker Desktop. I hope this will resolve your issue.

**Comment by pratik2630** [comment]
I've deleted ``C:\Program Files\Docker`` manually. But now when i try to install docker desktop from installer it shows that it was installed but not actually installing it. Also, it's not even creating C:\Program Files\Docker folder . What should i do. I stuck with this from last 2-3 hrs and tried every possible thing i can  do

**Comment by ammwinchande** [comment]
Okay, I think you shouldn't have removed it manually. Please create it, then Install Revo Uninstaller Pro as trial and right click on that `C:\Program Files\Docker` folder and choose uninstall with Revo, and choose the clean everything option. After it has completed then Install Docker Desktop

**Comment by sebastianlasaj** [comment]
I've tried every method mentioned in this topic, and none of them worked for me.

`Start-Process '.\Docker Desktop Installer.exe' -Wait install                                                                                                                                                                            -------------------------------------------------------------------------------->8                                                                                                                                                                                  Version: 4.9.0 (80466)                                                                                                                                                                                                                                              Sha1:                                                                                                                                                                                                                                                               Started on: 2022.06.03 10:49:00.261                                                                                                                                                                                                                                 Resources: C:\Users\seba\Downloads\resources                                                                                                                                                                                                                        OS: Windows 10 Pro                                                                                                                                                                                                                                                  Edition: Professional                                                                                                                                                                                                                                               Id: 2009                                                                                                                                                                                                                                                            Build: 19044                                                                                                                                                                                                                                                        BuildLabName: 19041.1.amd64fre.vb_release.191206-1406                                                                                                                                                                                                               File: C:\ProgramData\DockerDesktop\install-log-admin.txt                                                                                                                                                                                                            CommandLine: "C:\Users\seba\Downloads\Docker Desktop Installer.exe" install                                                                                                                                                                                         You can send feedback, including this log file, at https://github.com/docker/for-win/issues                                                                                                                                                                         [2022-06-03T10:49:02.181119300Z][ManifestAndExistingInstallationLoader][Info   ] No install path specified, looking for default installation registry key                                                                                                           [2022-06-03T10:49:02.191274100Z][Installer         ][Info   ] No installation found                                                                                                                                                                                 [2022-06-03T10:49:02.659488300Z][InstallWorkflow   ][Info   ] Cancel pending background download                                                                                                                                                                    [2022-06-03T10:49:02.664510300Z][BackgroundTransfer][Info   ] Cancel current background transfer job                                                                                                                                                                [2022-06-03T10:49:06.911484700Z][InstallWorkflow   ][Info   ] Using package: res:DockerDesktop                                                                                                                                                                      [2022-06-03T10:49:06.987137100Z][InstallWorkflow   ][Info   ] Downloading                                                                                                                                                                                           [2022-06-03T10:49:10.930892700Z][InstallWorkflow   ][Info   ] Extracting manifest                                                                                                                                                                                   [2022-06-03T10:49:11.493876100Z][InstallWorkflow   ][Info   ] Manifest found: version=80466, displayVersion=4.9.0, channelUrl=https://desktop.docker.com/win/main/amd64/appcast.xml                                                                                 [2022-06-03T10:49:11.493876100Z][InstallWorkflow   ][Info   ] Checking prerequisites                                                                                                                                                                                [2022-06-03T10:49:11.533876600Z][InstallWorkflow   ][Info   ] Selected backend mode: wsl-2                                                                                                                                                                          [2022-06-03T10:49:11.534877400Z][InstallWorkflow   ][Info   ] Unpacking artifacts                                                                                                                                                                                   [2022-06-03T10:49:12.373875200Z][Installer         ][Warning] Failed to track the installer started event                                                                                                                                                           [2022-06-03T10:51:20.038075800Z][InstallWorkflow   ][Info   ] Deploying component CommunityInstaller.CreateGroupAction                                                                                                                                              [2022-06-03T10:51:24.694429900Z][InstallWorkflow   ][Info   ] Deploying component CommunityInstaller.AddToGroupAction                                                                                                                                               [2022-06-03T10:51:29.249500200Z][InstallWorkflow   ][Info   ] Deploying component CommunityInstaller.EnableFeaturesAction                                                                                                                                           [2022-06-03T10:51:29.269514500Z][InstallWorkflow-EnableFeaturesAction][Info   ] Required features: VirtualMachinePlatform, Microsoft-Windows-Subsystem-Linux                                                                                                        [2022-06-03T10:51:29.487769500Z][InstallWorkflow   ][Error  ] Installation failed System.Exception: Component CommunityInstaller.EnableFeaturesAction failed:  ---> System.Runtime.InteropServices.COMException                                                        w System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)                                                                                                                                                             w System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()                                                                                                                                                                                w System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()                                                                                                                                                                                                           w System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()                                                                                                                                                                                                 w System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()                                                                                                                                                                                                       w System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)                                                                                                                                                                                                         w CommunityInstaller.EnableFeaturesAction.GetFeaturesToEnable()                                                                                                                                                                                                     w CommunityInstaller.EnableFeaturesAction.<DoAsync>d__45.MoveNext()                                                                                                                                                                                              --- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---                                                                                                                                                                                        w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()                                                                                                                                                                                                    w CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()                                                                                                                                                                                      --- Koniec śladu stosu wyjątków wewnętrznych ---                                                                                                                                                                                                                    w CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()                                                                                                                                                                                   --- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---                                                                                                                                                                                        w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()                                                                                                                                                                                                    w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)                                                                                                                                                                    w CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()                                                                                                                                                                                            [2022-06-03T10:51:29.490768100Z][InstallWorkflow   ][Info   ] Rollbacking component CommunityInstaller.AddToGroupAction                                                                                                                                             [2022-06-03T10:51:29.491767800Z][InstallWorkflow   ][Info   ] Rollbacking component CommunityInstaller.CreateGroupAction[2022-06-03T10:51:29.491767800Z][InstallWorkflow   ][Info   ] Rollbacking component CommunityInstaller.UnpackArtifactsStep                  [2022-06-03T10:51:29.506769200Z][FileSystem        ][Info   ] Deleting C:\Program Files\Docker\Docker                                                                                                                                                               [2022-06-03T10:51:29.855769800Z][FileSystem        ][Info   ] Deleted C:\Program Files\Docker\Docker successfully                                                                                                                                                   [2022-06-03T10:51:29.855769800Z][InstallWorkflow   ][Info   ] Rollbacking component CommunityInstaller.ExtractManifestStep                                                                                                                                          [2022-06-03T10:51:29.857775500Z][InstallWorkflow   ][Info   ] Rollbacking component CommunityInstaller.DownloadStep   `

Any ideas?

**Comment by RorisangSitoboli** [comment]
> I had a similar issue, I removed all the docker related files from previous installation on c:users/user_name/app/local. It worked for me, it may be helpful

I also removed all the Docker and Docker Desktop folders from the C:. You need to enable 'hidden files' to see the AppData folder. 

No luck.

**Comment by smartwombat** [comment]
Similar issue for 4.10.0 for me.
Deleted all Docker folders, removed Docker entries from Registry, Rebooted.
Failed again with same error.
![image](https://user-images.githubusercontent.com/8438931/178489176-e998c4ca-702e-4bcb-a3dd-cbc6ad7ef296.png)

**Comment by cplummer-linq** [comment]
This worked for me from an Administrator command prompt. 

Reference: https://github.com/docker/for-win/issues/12080#issuecomment-915619000

```
CD C:\Windows\System32\WBEM
dir /b *.mof *.mfl | findstr /v /i uninstall > moflist.txt & for /F %s in (moflist.txt) do mofcomp %s
```
