### ISSUE TITLE
3.0.0 delta update failed

### ISSUE THREAD

**Issue by itotakayuki-cr** [docker/for-win#9759]
1. Tried delta update to 3.0.0 from previous version
1. Update failed and previous version was uninstalled.
1. Had to download full package of 3.0.0.
![Installing Docker Desktop 3 0 0 (50684) 2020_12_11 13_03_47](https://user-images.githubusercontent.com/68282588/101862177-1f965f80-3bb5-11eb-9546-8e235b585e9a.png)

WIndows 10 Enterprise x64 1909 Japanese

**Comment by stephen-turner** [comment]
@itotakayuki-cr Which version were you on previously? And can you please upload diagnostics and paste the diagnostics id here so that we can look at the install logs?

**Comment by itotakayuki-cr** [comment]
> @itotakayuki-cr Which version were you on previously? 

2.5.0.1.

> And can you please upload diagnostics and paste the diagnostics id here so that we can look at the install logs?

Uploaded when I created this issue, but failed to retain the diag ID.
Any way to find the ID?

**Comment by stephen-turner** [comment]
If you were on 2.5.0.1, I'm not sure what you mean by "Tried delta update to 3.0.0 from previous version". There is no delta update from 2.5.0.1 to 3.0.0, only a complete installer.
