### ISSUE TITLE
Docker starting issue

### ISSUE THREAD

**Issue by shaik-hasan** [docker/for-win#9760]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by shaik-hasan** [comment]
The expected behavior is the docker need to start without any issues.

**Comment by tiborvass** [comment]
Sorry that docker did not start without any issues. Unfortunately there's not much we can do to help with this little information. My only vague guess right now is that you may be hitting #9755 which now has a workaround. Hope this helps. Closing this now but if you're still hitting your issue, try providing more information please.
