### ISSUE TITLE
Docker crash within a Win10 VM under Parallels

### ISSUE THREAD

**Issue by doozie** [docker/for-win#9768]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
Docker Desktop is not supported in a VM. Sometimes it works, sometimes it doesn't, but it's out of our control: it depends whether the outer hypervisor can run Hyper-V successfully.
