### ISSUE TITLE
docker failed to install

### ISSUE THREAD

**Issue by kona86** [docker/for-win#9769]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Expected docker to install.
### Actual behavior
![Docker installer failed to install](https://user-images.githubusercontent.com/54602526/101893882-48aaf600-3b9d-11eb-8c59-1ec79217d01b.PNG)

### Information

  - Windows Version:  Windows 10 Pro
  - Docker Desktop Version: 3.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:No

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jriley555** [comment]
![Capture](https://user-images.githubusercontent.com/1423314/101965278-b2e18c00-3bd9-11eb-8d5e-a5a3d2d8cbbf.JPG)


-  Windows Version: Windows 10 Pro
-  Docker Desktop Version: 3.0.0
-  Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:No

**Comment by kona86** [comment]
If you still this problem, please try the folowing:
- ydownload Windows 10 Update Assistant through the official Microsoft Windows 10 website
- reinstall docker
- reinstall WSL kernel only when prompt by docker.
