### ISSUE TITLE
Docker hangs when running containers

### ISSUE THREAD

**Issue by kondokuro** [docker/for-win#977]
After getting a newly installation of Windows 10, I installed docker and whenever I attempt to run a container docker just hangs, no messages are shown and I wait for minutes, it just remains unresponsive.

I have run the same command on a different machine and it is working normally. (unless I leave it overnight, not the current case)

I have attempted to use dockerfiles and lastly using straight forward run ready made images with one command like hostname nothing works.

### Expected behavior

Docker runs normally

### Actual behavior

Docker hangs

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
CF948FF3-0298-49B4-9918-31FACBEF2AFF/2017-08-03_15-47-28

  - host distribution and version (Windows version, build number, etc)
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.14393 N/A Build 14393
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 79 Stepping 1 GenuineIntel ~3501 Mhz
Total Physical Memory:     32,662 MB
Available Physical Memory: 29,291 MB
Virtual Memory: Max Size:  37,526 MB
Virtual Memory: Available: 34,208 MB
Virtual Memory: In Use:    3,318 MB
Hotfix(s):                 2 Hotfix(s) Installed.
                           [01]: KB3186568
                           [02]: KB3176495
Network Card(s):           2 NIC(s) Installed.
                           [01]: Intel(R) Ethernet Connection (2) I218-LM
                                 [01]: 10.136.12.15
                                 [02]: fe80::1403:313e:bbf7:71f2
                           [02]: Hyper-V Virtual Ethernet Adapter
                                 [01]: 172.28.112.1
                                 [02]: fe80::ec67:20e1:2874:5a05
Hyper-V Requirements:      A hypervisor has been detected. 

### Steps to reproduce the behavior

  1. On an up to date fresh installation of Windows 10, install docker
  2. Once Docker has started, switch to windows host
  3. Once Docker has switch, open a terminal
  4. On the terminal, type "docker run microsoft/nanoserver hostname"
  5. Notice that after the image was downloaded Docker remains unresponsive

**Comment by jasonbivins** [comment]
Hi @kondokuro 
I noticed this above:  OS Version: 10.0.14393 N/A Build 14393.   You might want to run Windows updates to make sure you have  KB3192366 KB3194496

I've had similar issues before where a command would hang in PS but not in CMD - can you see if that's the case for you?

**Comment by kondokuro** [comment]
Getting the updates.

**Comment by kondokuro** [comment]
All updates are in and its working
