### ISSUE TITLE
"Invalid standard handle identifier" since 3.0.0 update

### ISSUE THREAD

**Issue by mleguevel** [docker/for-win#9770]
Hello,

I upgraded to the version 3.0.0 today and since the upgrade, docker commands all end with an error.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F280684A-3B48-49F9-B15D-2F448E4187FD/20201211104027

### Expected behavior

Being able to use the `docker` command on windows without having an error

### Actual behavior

Any command on windows ends up with the following error:

```
panic: Invalid standard handle identifier: 4294967286

goroutine 1 [running]:
github.com/docker/cli/vendor/github.com/Azure/go-ansiterm/winterm.GetStdFile(0xfffffff6, 0xc0000547f8, 0x2b0)
        /go/src/github.com/docker/cli/vendor/github.com/Azure/go-ansiterm/winterm/ansi.go:173 +0x1f3
github.com/docker/cli/vendor/github.com/moby/term/windows.NewAnsiReader(0xfffffff6, 0xc00000000f, 0x20d46c0)
        /go/src/github.com/docker/cli/vendor/github.com/moby/term/windows/ansi_reader.go:34 +0x36
github.com/docker/cli/vendor/github.com/moby/term.StdStreams(0xc0003d3790, 0xc0004c3eb8, 0x1, 0x1, 0x0, 0x0)
        /go/src/github.com/docker/cli/vendor/github.com/moby/term/term_windows.go:75 +0x1eb
github.com/docker/cli/cli/command.NewDockerCli(0x0, 0x0, 0x0, 0x19b926c, 0x1b4f0a0, 0xc00020de90)
        /go/src/github.com/docker/cli/cli/command/cli.go:473 +0x1a7
main.main()
        /go/src/github.com/docker/cli/cmd/docker/docker.go:291 +0x4b
```

### Information
I've tested it with `docker run`, `docker exec` and  `docker logs`. Actually, just running the `docker` command alone gives the same result. I tried running the commands from mobaxterm, windows cmd and powershell and I have the same error on each of those.

I tried reinstalling docker desktop and running the last two options in the "Troubleshooting" menu (`Clean / Purge data` and `Reset to factory defaults`) with no luck.

Running services from `docker-compose` works fine though.

I tried looking at the code but I'm not a go developer, so take it with a grain of salt:

From the stack trace, it seems that [syscall.STD_INPUT_HANDLE](https://github.com/docker/cli/blame/42d4489992dfe2d756863bad2056f90d66e01661/vendor/github.com/Azure/go-ansiterm/winterm/ansi.go#L166) is compared to [windows.STD_INPUT_HANDLE](https://github.com/moby/term/blame/master/term_windows.go#L74) and that they do not have the same value? From the go documentation, `windows.STD_INPUT_HANDLE` seems to be `-10 & (1<<32 - 1)` = `4294967286` which matches the handle identifier that's displayed in the error message.

  - Windows Version: Windows 10 1809 17763.1577
  - Docker Desktop Version: 3.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

I have no idea because it might be related to my windows installation. But on my machine, reproducing it consists in running any docker command.

**Comment by stephen-turner** [comment]
Hmmm, that's very odd. It sounds like the sort of bug that would be widespread, but we haven't had any other reports. I'm going to ask the team that writes the CLI (which is just an upstream to us) if they have any ideas.

**Comment by iamrearwindow** [comment]
Same deal for me. Docker desktop upgraded to 3.0.0 on Windows 10 on 11-dec.
All CLI docker commands return - panic: Invalid standard handle identifier: 4294967286.

**Comment by ScotHillier** [comment]
I have the same problem.
panic: Invalid standard handle identifier: 4294967286

**Comment by ScotHillier** [comment]
I have it working, but I have no idea what the magic was. Here's what I did:

1. Upgraded Visual Studio 2019 to the latest version

2. Disabled the legacy console because I got an error when trying to reset to factory settings
    Open cmd.exe.
    Right click title bar -> Properties -> Uncheck Use legacy console.
    Click OK.

3. Reset to factory Settings

**Comment by anishjain94** [comment]
**This worked for me**. 
Disabled the legacy console because I got an error when trying to reset to factory settings
Open cmd.exe.
Right click title bar -> Properties -> Uncheck Use legacy console.
Click OK.

**Comment by saiyamarlon** [comment]
thank you, for the data

**Comment by mleguevel** [comment]
> 
> 
> **This worked for me**.
> Disabled the legacy console because I got an error when trying to reset to factory settings
> Open cmd.exe.
> Right click title bar -> Properties -> Uncheck Use legacy console.
> Click OK.

Yep, it does the trick for me as well. Thanks @ScotHillier 

@stephen-turner I don't know if you want to keep this issue open?

**Comment by stephen-turner** [comment]
Good detection work, @ScotHillier, thank you. It's easy to reproduce by switching to legacy console.

I'll leave this ticket open and discuss with the CLI team whether it's fixable.

**Comment by stephen-turner** [comment]
Good news, the CLI team have found the cause and believe they can fix it.

(I don't have a date yet: with the holiday season there probably won't be another release this year, so in the mean time please continue to use the workaround of turning off legacy mode in the console).

**Comment by TomTurkington** [comment]
I'm having this problem and though switching to non-Legacy works, it is not an option as that causes other problems.  I see where stephen-turner indicates they i.d.'d the problem and were working on a fix but no update since then, and then the 'robot' decided this should be closed.   It would be really nice if there was some way to mark this thread 'in progress' if indeed they are working on a fix so that the 'robot' doesn't close it until it is truly fixed.   I just upgraded docker to latest/greatest and still am having the same problem.

**Comment by d-sphinx** [comment]
Still not fixed?

**Comment by TomTurkington** [comment]
That is correct, Rashid; I'm forced to turn off "Use Legacy Console" on Windows 10 to be able to use Docker containers - get the "Invalid standard handle identifier" error if I don't.  Unfortunately I have another app that I need that requires the Legacy Console, so they have become mutually exclusive.  I'm totally current on Win10 and updated Docker Desktop yesterday before commenting.

Tom Turkington
(206) 352-8202
***@***.***
