### ISSUE TITLE
Docker desktop shows no container running.

### ISSUE THREAD

**Issue by saikiranreddy28-123** [docker/for-win#9777]
Docker desktop shows no container running, even when a container is running on the docker quickstart terminal and the docker desktop shows no local images or containers even when I have container and images on my local machine. I tried restarting the docker and my windows machine multiple times but the problem still exists.

**Comment by tiborvass** [comment]
Please follow the issue template for reporting issues: https://raw.githubusercontent.com/docker/for-win/master/.github/ISSUE_TEMPLATE.md
