### ISSUE TITLE
Cannot update Docker Desktop from 2.5.3 (50261)

### ISSUE THREAD

**Issue by sirlatrom** [docker/for-win#9779]
- [ ] I have tried with the latest version of my channel (Stable or Edge) - I haven't, as the bug is that I cannot update
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 9BD96051-68F2-47F9-8B92-CB5F4F855A56/20201212112911

### Expected behavior

Docker Desktop should update to the latest version, or indicate there is no newer version.

### Actual behavior

A notification like in #9100 that plainly says "Cannot update".

### Information

  - Windows Version: Windows 10 Pro, 20H2, 19042.685, Windows Feature Experience Pack 120.2212.551.0
  - Docker Desktop Version: 2.5.3 (50261)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No, directly on laptop

### Steps to reproduce the behavior

  1. Right-click Docker Desktop system tray icon
  2. Choose "Check for Updates"

**Comment by stephen-turner** [comment]
Thanks for the report. The URL that's supposed to contain the information about the latest version is 403 Forbidden. We'll fix it.

**Comment by StefanScherer** [comment]
Thanks @sirlatrom 
Indeed the underlying appcast.xml gave a 403 HTTP response. We've fixed the permission issue and now you should be able to update to 3.0.0 on Windows and 3.0.1 on Mac.
