### ISSUE TITLE
Docker Desktop 3.0.0, Installation Failed (After update and also downloaded install)

### ISSUE THREAD

**Issue by Jooppie** [docker/for-win#9780]
Component CommunityInstaller.EnableFeaturesAction failed: Kan bestand of assembly System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 of een van de afhankelijkheden hiervan niet laden. Er wordt verwacht dat de module een assembly-manifest zou bevatten.
   bij CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()

**Comment by Jooppie** [comment]
Tried reinstall 2.4 version: Also Error now:

Kan bestand of assembly System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 of een van de afhankelijkheden hiervan niet laden. Er wordt verwacht dat de module een assembly-manifest zou bevatten.
   bij CommunityInstaller.EnableFeaturesAction.DoAsync(CancellationToken cancelToken)
   bij CommunityInstaller.InstallWorkflow.<HandleD4WPackageAsync>d__32.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__27.MoveNext()

**Comment by Martyrer** [comment]
Same happened for me, exactly same error, 2.5.0.1 can't be installed back as well... 

`
Edition	Windows 10 Pro
Version	20H2
Installed on	‎28/‎05/‎2020
OS build	19042.610
Experience	Windows Feature Experience Pack 120.2212.31.0
`

**Comment by Martyrer** [comment]
upd. I was able to install v3.0.0 after removing docker related folders
```
C:\Program Files\Docker
C:\Users\<UserProfile>\AppData\Local\Docker
C:\Users\<UserProfile>\AppData\Roaming\Docker
C:\Users\<UserProfile>\AppData\Roaming\Docker Desktop
```

after  successful installation, folders related to the `AppData` have been moved back overriding existing files (just to restore the settings)

**Comment by nphmuller** [comment]
Facing the same issue.  Sadly @Martyrer 's workaround didn't work for me.

Here is my latest `install-log` file:
```
Started on: 2020/12/13 23:46:38.482
File: C:\Users\mulle\AppData\Local\Docker\install-log.txt
CommandLine: "C:\Users\mulle\AppData\Local\Temp\MicrosoftEdgeDownloads\24422bdd-2e36-4ce7-8625-97c11b01ab55\Docker Desktop Installer.exe" "install" -package "res:DockerDesktop" --relaunch-as-admin
[23:46:38.482][ManifestAndExistingInstallationLoader] No install path specified, looking for default installation registry key
[23:46:38.482][Program] No installation found
[23:46:38.633][InstallWorkflow] Using package: res:DockerDesktop
[23:46:38.648][InstallWorkflow] Downloading
[23:46:40.891][InstallWorkflow] Extracting manifest
[23:46:41.285][InstallWorkflow] Manifest found: version=50684, displayVersion=3.0.0, channelUrl=https://desktop.docker.com/win/stable/appcast.xml
[23:46:41.287][InstallWorkflow] Checking prerequisites
[23:46:41.330][InstallWorkflow] Unpacking artifacts
[23:48:39.787][InstallWorkflow] Deploying component CommunityInstaller.CreateGroupAction
[23:48:44.401][InstallWorkflow] Deploying component CommunityInstaller.AddToGroupAction
[23:48:48.946][InstallWorkflow] Deploying component CommunityInstaller.EnableFeaturesAction
[23:48:49.036][InstallWorkflow] Installation failed
Exception type: System.Exception, Exception message: Component CommunityInstaller.EnableFeaturesAction failed: Not found , StackTrace:
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
[23:48:49.039][InstallWorkflow] Rollbacking component CommunityInstaller.AddToGroupAction
[23:48:49.041][InstallWorkflow] Rollbacking component CommunityInstaller.CreateGroupAction
[23:48:49.042][InstallWorkflow] Rollbacking component CommunityInstaller.UnpackArtifactsStep
[23:48:49.049][FileSystem] Deleting C:\Program Files\Docker\Docker
[23:48:49.295][FileSystem] Deleted C:\Program Files\Docker\Docker successfully
[23:48:49.296][InstallWorkflow] Rollbacking component CommunityInstaller.ExtractManifestStep
[23:48:49.297][InstallWorkflow] Rollbacking component CommunityInstaller.DownloadStep

```

**Comment by Jooppie** [comment]
> upd. I was able to install v3.0.0 after removing docker related folders
> 
> ```
> C:\Program Files\Docker
> C:\Users\<UserProfile>\AppData\Local\Docker
> C:\Users\<UserProfile>\AppData\Roaming\Docker
> C:\Users\<UserProfile>\AppData\Roaming\Docker Desktop
> ```
> 
> after successful installation, folders related to the `AppData` have been moved back overriding existing files (just to restore the settings)

Tried this, but does not work for me.

**Comment by dmg-hamann** [comment]
Same issue here but deleting the folders and trying to reinstall does not work. I can't install older versions (2.5.0 or 2.4.0) aswell.

**Comment by dmg-hamann** [comment]
I was able to reinstall it by doing the following steps.

Delete all folders mentioned in the post below

> > upd. I was able to install v3.0.0 after removing docker related folders
> > ```
> > C:\Program Files\Docker
> > C:\Users\<UserProfile>\AppData\Local\Docker
> > C:\Users\<UserProfile>\AppData\Roaming\Docker
> > C:\Users\<UserProfile>\AppData\Roaming\Docker Desktop
> > ```
> > 
> > 
> > after successful installation, folders related to the `AppData` have been moved back overriding existing files (just to restore the settings)
> 
> Tried this, but does not work for me.

When running the installation wizard unmark all options (Enable hyper v, use wsl, add shortcut).

That did the trick for me. 

Afterwards I needed to unregister my old dockder-desktop distro and restart docker-desktop. Now it is back up and running.

**Comment by syeats** [comment]
> I was able to reinstall it by doing the following steps.
> 
> Delete all folders mentioned in the post below
> 
> > > upd. I was able to install v3.0.0 after removing docker related folders
> > > ```
> > > C:\Program Files\Docker
> > > C:\Users\<UserProfile>\AppData\Local\Docker
> > > C:\Users\<UserProfile>\AppData\Roaming\Docker
> > > C:\Users\<UserProfile>\AppData\Roaming\Docker Desktop
> > > ```
> > > 
> > > 
> > > after successful installation, folders related to the `AppData` have been moved back overriding existing files (just to restore the settings)
> > 
> > 
> > Tried this, but does not work for me.
> 
> When running the installation wizard unmark all options (Enable hyper v, use wsl, add shortcut).
> 
> That did the trick for me.
> 
> Afterwards I needed to unregister my old dockder-desktop distro and restart docker-desktop. Now it is back up and running.

This also just fixed it for me for 3.2.2, many thanks!

**Comment by fjfuente77** [comment]
Same error in 3.3.0... please fixed

**Comment by risto-trajanov** [comment]
> > I was able to reinstall it by doing the following steps.
> > Delete all folders mentioned in the post below
> > > > upd. I was able to install v3.0.0 after removing docker related folders
> > > > ```
> > > > C:\Program Files\Docker
> > > > C:\Users\<UserProfile>\AppData\Local\Docker
> > > > C:\Users\<UserProfile>\AppData\Roaming\Docker
> > > > C:\Users\<UserProfile>\AppData\Roaming\Docker Desktop
> > > > ```
> > > > 
> > > > 
> > > > after successful installation, folders related to the `AppData` have been moved back overriding existing files (just to restore the settings)
> > > 
> > > 
> > > Tried this, but does not work for me.
> > 
> > 
> > When running the installation wizard unmark all options (Enable hyper v, use wsl, add shortcut).
> > That did the trick for me.
> > Afterwards I needed to unregister my old dockder-desktop distro and restart docker-desktop. Now it is back up and running.
> 
> This also just fixed it for me for 3.2.2, many thanks! (note: have to run DD as Admin)

Also works for 3.3.3 (Deleted the files, and unchecked every box in the beginning of the wizard.)

**Comment by 89z** [comment]
https://github.com/docker/for-mac/issues/5605
https://github.com/docker/for-win/issues/9758

https://github.com/docker/for-win/issues/9780

**Comment by 89z** [comment]
To anyone getting this error:

~~~
Component CommunityInstaller.EnableFeaturesAction failed
~~~

The fix for me was enabling this service:

~~~
Windows Modules Installer
~~~

Note I used a tool [1] to do this, but I think you can also just use the normal Service App.

1. https://github.com/WereDev/Wu10Man

**Comment by swatoff** [comment]
Same problem at 3.5.2.
This sollution worked

> > > I was able to reinstall it by doing the following steps.
> > > Delete all folders mentioned in the post below
> > > > > upd. I was able to install v3.0.0 after removing docker related folders
> > > > > ```
> > > > > C:\Program Files\Docker
> > > > > C:\Users\<UserProfile>\AppData\Local\Docker
> > > > > C:\Users\<UserProfile>\AppData\Roaming\Docker
> > > > > C:\Users\<UserProfile>\AppData\Roaming\Docker Desktop
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > after successful installation, folders related to the `AppData` have been moved back overriding existing files (just to restore the settings)
> > > > 
> > > > 
> > > > Tried this, but does not work for me.
> > > 
> > > 
> > > When running the installation wizard unmark all options (Enable hyper v, use wsl, add shortcut).
> > > That did the trick for me.
> > > Afterwards I needed to unregister my old dockder-desktop distro and restart docker-desktop. Now it is back up and running.
> > 
> > 
> > This also just fixed it for me for 3.2.2, many thanks! (note: have to run DD as Admin)
> 
> Also works for 3.3.3 (Deleted the files, and unchecked every box in the beginning of the wizard.)

**Comment by DiegoRicardoValdiviaArreola** [comment]
Same problem at 3.5.2

As @dmg-hamann stated I disabled the "install windows components for wsl2" option and that worked for me. 
I forgot that I already have wsl installed.

*The wizard just showed me two options: 
- install windows components for wsl2
- Create shortcut

**Comment by yagmurerdem** [comment]
> 3.5.2'de aynı sorun
> 
> As @ dmg-hamann belirtti ben "wsl2 için pencereleri bileşenleri yüklemek" seçeneğini devre dışı ve bu benim için çalıştı.
> Zaten wsl'nin kurulu olduğunu unutmuşum.
> 
> *Sihirbaz bana iki seçenek gösterdi:
> 
> * wsl2 için Windows bileşenlerini yükleyin
> * Kısayol oluştur

 

thanks it worked for 3.6.0

**Comment by felipecastrosales** [comment]
Even with all the suggestions, the error remains. 
I **can't** believe I was idle for 2 days trying to resolve this problem for **nothing**. 
Windows is horrible.

**Comment by heinerb** [comment]
> > > Same problem at 3.5.2. This sollution worked
> > > > > > I was able to reinstall it by doing the following steps.
> > > > > > Delete all folders mentioned in the post below
> > > > > > > > upd. I was able to install v3.0.0 after removing docker related folders
> > > > > > > > ```
> > > > > > > > C:\Program Files\Docker
> > > > > > > > C:\Users\<UserProfile>\AppData\Local\Docker
> > > > > > > > C:\Users\<UserProfile>\AppData\Roaming\Docker
> > > > > > > > C:\Users\<UserProfile>\AppData\Roaming\Docker Desktop
> > > > > > > > ```
> > > > > > > > 
> > > > > > > > 
> > > > > > > >     
> > > > > > > >       
> > > > > > > >     
> > > > > > > > 
> > > > > > > >       
> > > > > > > >     
> > > > > > > > 
> > > > > > > >     
> > > > > > > >   
> > > > > > > > after successful installation, folders related to the `AppData` have been moved back overriding existing files (just to restore the settings)
> > > > > > > 
> > > > > > > 
> > > > > > > Tried this, but does not work for me.
> > > > > > 
> > > > > > 
> > > > > > When running the installation wizard unmark all options (Enable hyper v, use wsl, add shortcut).
> > > > > > That did the trick for me.
> > > > > > Afterwards I needed to unregister my old dockder-desktop distro and restart docker-desktop. Now it is back up and running.
> > > > > 
> > > > > 
> > > > > This also just fixed it for me for 3.2.2, many thanks! (note: have to run DD as Admin)
> > > > 
> > > > 
> > > > Also works for 3.3.3 (Deleted the files, and unchecked every box in the beginning of the wizard.)
> > 
> > 
> > This solution worked for me; Docker Desktop 4.1.1.
> 
> The solution didn't work for me in Docker Desktop 4.1.1. Then I tried it again only this time in ran installer as an administrator and **it **worked****
Component CommunityInstaller.EnableFeaturesAction failed: 
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__24.MoveNext()

**Comment by gohawks3** [comment]
I had to clean up those folders as previously listed and uncheck "install components for wsl" and "add to desktop" to finally succeed.

**Comment by vasanthagutha** [comment]
Having the same problem when reinstalling docker. Tried all the above methods. Trying to install 4.9.0 version.

Component CommunityInstaller.EnableFeaturesAction failed:
at CommunityInstaller.InstallWorkflow.d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at CommunityInstaller.InstallWorkflow.d__24.MoveNext()

**Comment by vasanthagutha** [comment]
Thank you @mholttech. Were you able to switch to the windows container successfully after you installed it? May I know which version you have installed and also please let me know whether I need to run the commands that you have provided one after the other or all at once?

I got fed up with the new version installation. So I installed the old version of docker 2.4.0.0 successfully after I unchecked the 
"Install required windows components for WSL2".  But I could not able to switch to the windows container. Showing below error message. 

Microsoft.Management.Infrastructure.CimException:
Invalid class 
   at Microsoft.Management.Infrastructure.Internal.Operations.CimSyncEnumeratorBase`1.MoveNext()
   at SimCim.Core.SimCimScope.<EnumerateInstances>d__10`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Docker.Backend.Features.Installer.GetFeatureInfoMaps(Feature[] features) in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.Backend\Features\Installer.cs:line 46
   at Docker.Backend.Features.Installer.GetFeatureReport(Feature[] features) in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.Backend\Features\Installer.cs:line 32
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()

**Comment by mholttech** [comment]
@vasanthagutha  Not quite sure what you mean by "Windows Containers". After doing the steps that I mentioned I was able to reinstall the latest docker desktop version with the WSL2 option enabled. This was very important to me because I heavily use WSL2. I only use Linux based containers and not Windows based containers in my development.

**Comment by vasanthagutha** [comment]
Thanks, @mholttech. please let me know whether I need to run the commands that you have provided one after the other or all at once?

**Comment by mholttech** [comment]
@vasanthagutha When I ran it I copy/pasted the entire block of commands.... how you do it yourself is up to you

**Comment by vasanthagutha** [comment]
@mholttech Thank you!
