### ISSUE TITLE
Windows 10 Pro. I am facing this issue and i have to quite the docker 

### ISSUE THREAD

**Issue by kirumadke** [docker/for-win#9782]
5B355108-6AF2-418B-A909-C8E6133F8E7D/20201212140347!--
Please, check https://docs.docker.com/docker-for-windows/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

Issues unrelated to Docker Desktop will be closed.  In particular, see
  - https://github.com/moby/moby/issues for Docker daemon, e.g. running on Windows Server with Docker EE
  - https://github.com/docker/compose/issues for docker-compose
  - https://github.com/docker/machine/issues for docker-machine
  - https://github.com/docker/docker.github.io/issues for the documentation
-->

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by kirumadke** [comment]
[log.txt](https://github.com/docker/for-win/files/5683268/log.txt)

**Comment by tiborvass** [comment]
Please describe what your issue is, and upload a valid diagnostics ID.
