### ISSUE TITLE
APT Updates run issue

### ISSUE THREAD

**Issue by satkavali** [docker/for-win#9785]
Hi,

When I try to build a docker image the below step gives the error.

 **RUN apt-get update**

 > [2/5] RUN apt-get update:
#5 0.481 Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
#5 0.599 Get:2 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
#5 1.433 Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
#5 1.776 Get:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
#5 2.051 Get:5 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
#5 2.064 Get:6 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
#5 2.440 Get:7 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
#5 25.24 Get:8 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
#5 28.28 Reading package lists...
#5 28.79 E: Release file for http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease is not valid yet (invalid for another 6h 26min 32s). Updates for this repository will not be applied.
#5 28.79 E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease is not valid yet (invalid for another 6h 27min 14s). Updates for this repository will not be applied.
#5 28.79 E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease is not valid yet (invalid for another 6h 28min 12s). Updates for this repository will not be applied.
------
failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c apt-get update]: runc did not terminate sucessfully

**Comment by tiborvass** [comment]
Most likely a time drift or time zone issue. If you restarted your computer and are still hitting this, send a diagnostics ID.
