### ISSUE TITLE
i have the latest docker 3.0 yet docker is nor recognized in ubuntu

### ISSUE THREAD

**Issue by niforatg** [docker/for-win#9786]
when i try to execute a docker command in ubuntu, i get the following error:

The command 'docker' could not be found in this WSL 2 distro.
We recommend to activate the WSL integration in Docker Desktop settings.

The WSL Integration option is grayed out in docker settings. is this a bug? how can i get it to work?

**Comment by b-hayes** [comment]
Docker 3.0 is completly broken I have to re-install docker and rebuild all my containers every day.

**Comment by cprivite** [comment]
I'm seeing this though it's manifesting slightly differently. Using docker 3.0.0 on 20H2 windows but the WSL integration straight up isn't even shown in the resources menu in the docker preferences.

PS C:\Users\cprivite> wsl.exe -l -v
  NAME      STATE           VERSION
* Ubuntu    Running         2

cprivite@workstation:/mnt/c/Users/cprivite$ docker

The command 'docker' could not be found in this WSL 2 distro.
We recommend to activate the WSL integration in Docker Desktop settings.

See https://docs.docker.com/docker-for-windows/wsl/ for details.

![image](https://user-images.githubusercontent.com/23177737/103550827-170d0e00-4e6f-11eb-8d36-5798d04d8046.png)

**Comment by cprivite** [comment]
Hey @niforatg see if you're in windows container mode accidentally. That was the cause of my issue.
