### ISSUE TITLE
Unable to login to share C:\

### ISSUE THREAD

**Issue by Mobjo** [docker/for-win#979]
![docker file sharing](https://user-images.githubusercontent.com/18304798/28960811-4a3c916c-7900-11e7-9696-91dbc8f87a2e.JPG)
### Expected behavior
Should have granted me access with my Windows 10 User account

### Actual behavior
Does not grant me access
### Information
I've tried both my windows and docker account

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jasonbivins** [comment]
Hi @Mobjo   Do you have the Docker icon in the systray?  Try manually sharing your drive to Docker
![image](https://user-images.githubusercontent.com/28021664/29032775-b93bd05c-7b60-11e7-8cc4-18137b92ab90.png)

**Comment by Mobjo** [comment]
Hi 
I got it. But I cannot share it manually that's the problem. The new fix I tried works. I installed docker tools and disabled Hyper-V.
