### ISSUE TITLE
Pulling failed with "The parameter is incorrect" message of official image

### ISSUE THREAD

**Issue by varosi** [docker/for-win#980]
### Expected behavior
To pull correctly any Windows image in Windows docker mode.

### Actual behavior
```PS C:\Users\varosi> docker pull microsoft/nanoserver
Using default tag: latest
latest: Pulling from microsoft/nanoserver
bce2fbc256ea: Extracting [==================================================>]  252.7MB/252.7MB
baa0507b781f: Download complete
failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer C:\ProgramData\Docker\windowsfilter\6ae
bc4a64c86f31cef64f93c1c0331f08aaf7141abcc9114f28de4cd0961f207: The parameter is incorrect.```

### Information

```A diagnostic was uploaded with id: 9E5C898E-E6B6-45AB-BE3F-1DB4D8A9AE16/2017-08-04_16-22-24```

on Windows 10 Creators Update
Windows Defender is OFF

### Steps to reproduce the behavior

  1. docker pull microsoft/nanoserver

**Comment by jasonbivins** [comment]
Hi @varosi    According to the error - it looks like there's a problem with WMI.  Try adding the WMI Windows Installer Provider component to Windows.  This component can be installed through "Add/Remove Windows Components"... look for the "Management and Monitoring Tools" group

Here's the error you're getting when the Download fails:

``` [16:17:05.462][WindowsDaemon  ][Error  ] Event filter with query "SELECT * FROM __InstanceOperationEvent WITHIN 10 WHERE (TargetInstance ISA 'Msvm_ExternalEthernetPort') OR (TargetInstance ISA 'Msvm_VmLANEndpoint') OR (TargetInstance ISA 'Msvm_SyntheticEthernetPort') OR (TargetInstance ISA 'Msvm_ComputerSystem') OR (TargetInstance ISA 'Msvm_VLANEndpointSettingData')" could not be reactivated in namespace "//./root/virtualization" because of error 0x80041010. Events cannot be delivered through this filter until the problem is corrected. ```

**Comment by varosi** [comment]
I don't find such component in Windows components on Windows 10 Creators update. 
Following: https://docs.servicenow.com/bundle/istanbul-it-operations-management/page/administer/orchestration-activities/task/t_EnableWMIWindowsInstallProvider.html

There is no such a component. Is there a programatic way to install it?

**Comment by varosi** [comment]
I have Windows 10 Pro licensed Windows. Is WMI Installer provider only for pre-10 versions?

**Comment by jasonbivins** [comment]
Hi @varosi    Try the [WMI diagnosis tool](https://technet.microsoft.com/en-us/library/ff404265.aspx) from Microsoft

Is the microsoft/nanoserver image the only one you're having troubles with?  You can try removing it, then repulling it.
```docker image rm -f microsoft/nanoserver```

**Comment by varosi** [comment]
Pulling still doesn't work with the same error. 
I have log file from WMIDiag too.

I'm attaching my log:
[WMIDIAG-V2.2_WIN8.1_.CLI.RTM.64_VASSILK-PC_2017.09.18_18.03.06.LOG.zip](https://github.com/docker/for-win/files/1311181/WMIDIAG-V2.2_WIN8.1_.CLI.RTM.64_VASSILK-PC_2017.09.18_18.03.06.LOG.zip)

**Comment by varosi** [comment]
After latest update of Docker for Windows, we still cannot use it for CI/CD in our company, because of the problem.
Here it is diagnostic info:
9E5C898E-E6B6-45AB-BE3F-1DB4D8A9AE16/2017-11-10_15-27-58

**Comment by jasonbivins** [comment]
Hi @varosi   According to the logs, the Docker for Windows service can't start due to your event monitoring setup.  Do you use Splunk, or anything similar?
`[15:27:52.811][WindowsDaemon  ][Error  ] Event filter with query "SELECT * FROM __InstanceOperationEvent WITHIN 10 WHERE (TargetInstance ISA 'Msvm_ExternalEthernetPort') OR (TargetInstance ISA 'Msvm_VmLANEndpoint') OR (TargetInstance ISA 'Msvm_SyntheticEthernetPort') OR (TargetInstance ISA 'Msvm_ComputerSystem') OR (TargetInstance ISA 'Msvm_VLANEndpointSettingData')" could not be reactivated in namespace "//./root/virtualization" because of error 0x80041010. Events cannot be delivered through this filter until the problem is corrected.
`

**Comment by varosi** [comment]
Hello!

No, I didn't know there is such a tool.
What can I do to fix the situation?

Best regards,
Vasil

2017-12-13 19:16 GMT+02:00 Jason Bivins <notifications@github.com>:

**Comment by jasonbivins** [comment]
If you have it installed - try disabling the Intel(R) PROSet Monitoring Service
https://social.technet.microsoft.com/Forums/en-US/f6710985-54bf-4b99-a8b0-cf9e440e6502/wmi-errors-clogging-event-viewer-errors-every-11-seconds?forum=w81previtpro

If that doesnt help, then there's an issue with WMI in Windows
https://www.virtuallyboring.com/microsoft-wmi-invalid-class-error-0x80041010/

**Comment by varosi** [comment]
Hello!

Disabling "Intel(R) PROSet Monitoring Service" doesn't helped.
Following second page doesn't helped either.

Diagnostic gave me those errors:

42895 19:18:37 (1) !! ERROR: WMI CONNECTION errors occured for the
following namespaces: .................................................. 1
ERROR(S)!
42896 19:18:37 (0) ** - Root/nap, 0x8004100E - (WBEM_E_INVALID_NAMESPACE)
Namespace specified cannot be found.
42897 19:18:37 (0) **
42898 19:18:37 (1) !! ERROR: WMI GET operation errors reported:
...........................................................................
3 ERROR(S)!
42899 19:18:37 (0) ** - Root/CIMV2, Win32_FloppyDrive, 0x80041002 -
(WBEM_E_NOT_FOUND) Object cannot be found.
42900 19:18:37 (0) **   MOF Registration: 'WMI information not available
(This could be the case for an external application or a third party WMI
provider)'
42901 19:18:37 (0) ** - Root/CIMV2, Win32_FloppyController, 0x80041002 -
(WBEM_E_NOT_FOUND) Object cannot be found.
42902 19:18:37 (0) **   MOF Registration: 'WMI information not available
(This could be the case for an external application or a third party WMI
provider)'
42903 19:18:37 (0) ** - Root/WMI, Thread, 0x80041002 - (WBEM_E_NOT_FOUND)
Object cannot be found.
42904 19:18:37 (0) **   MOF Registration: 'WMI information not available
(This could be the case for an external application or a third party WMI
provider)'

42928 19:18:37 (0) ** 1 error(s) 0x8004100E - (WBEM_E_INVALID_NAMESPACE)
Namespace specified cannot be found
42929 19:18:37 (0) **
42930 19:18:37 (0) ** 3 error(s) 0x80041002 - (WBEM_E_NOT_FOUND) Object
cannot be found
42931 19:18:37 (0) ** => This error is typically a WMI error. This WMI
error is due to:
42932 19:18:37 (0) **    - a missing WMI class definition or object.
42933 19:18:37 (0) **      (See any GET, ENUMERATION, EXECQUERY and GET
VALUE operation failures).
42934 19:18:37 (0) **      You can correct the missing class definitions by:
42935 19:18:37 (0) **      - Manually recompiling the MOF file(s) with the
'MOFCOMP <FileName.MOF>' command.
42936 19:18:37 (0) **      Note: You can build a list of classes in
relation with their WMI provider and MOF file with WMIDiag.
42937 19:18:37 (0) **            (This list can be built on a similar and
working WMI Windows installation)
42938 19:18:37 (0) **            The following command line must be used:
42939 19:18:37 (0) **            i.e. 'WMIDiag CorrelateClassAndProvider'
42940 19:18:37 (0) **    - a WMI repository corruption.
42941 19:18:37 (0) **      In such a case, you must rerun WMIDiag with
'WriteInRepository' parameter
42942 19:18:37 (0) **      to validate the WMI repository operations.
42943 19:18:37 (0) **    Note: ENSURE you are an administrator with FULL
access to WMI EVERY namespaces of the computer before
42944 19:18:37 (0) **          executing the WriteInRepository command. To
write temporary data from the Root namespace, use:
42945 19:18:37 (0) **          i.e. 'WMIDiag WriteInRepository=Root'
42946 19:18:37 (0) **    - If the WriteInRepository command fails, while
being an Administrator with ALL accesses to ALL namespaces
42947 19:18:37 (0) **      the WMI repository must be reconstructed.
42948 19:18:37 (0) **    Note: The WMI repository reconstruction requires
to locate all MOF files needed to rebuild the repository,
42949 19:18:37 (0) **          otherwise some applications may fail after
the reconstruction.
42950 19:18:37 (0) **          This can be achieved with the following
command:
42951 19:18:37 (0) **          i.e. 'WMIDiag ShowMOFErrors'
42952 19:18:37 (0) **    Note: The repository reconstruction must be a LAST
RESORT solution and ONLY after executing
42953 19:18:37 (0) **          ALL fixes previously mentioned.

How could I fix those errors? I have done already those instructions
without success.

It's very strange, why this diagnostic tells me:
42814 19:18:37 (0) ** Windows 8.1 - No Service Pack - 64-bit (15063) - User
'VASSILK-PC\VAROSI' on computer 'VASSILK-PC'.

When my Windows is actually updated to Windows 10.

Best regards,
Vassil

2017-12-19 6:35 GMT+02:00 Jason Bivins <notifications@github.com>:

**Comment by jasonbivins** [comment]
@varosi  Do you know if this Windows install was upgraded from 8.1 or if it was installed as Windows 10?

It does look like the WMI portion got missed, or something happened during the upgrade

**Comment by varosi** [comment]
It is upgrade from 8.1 to 10.

**Comment by jasonbivins** [comment]
@varosi   At this point, it if were my machine I would wipe and then reinstall with a fresh Windows 10 image and try from there, but if that's not an option then these are the best instructions for troubleshooting and resolving WMI issues that i've found  https://www.virtuallyboring.com/microsoft-wmi-invalid-class-error-0x80041010/

In some cases I've been lucky and had random things like this solved by manually running Windows updates.

**Comment by varosi** [comment]
Thanks!

**Comment by varosi** [comment]
Last link doesn't help either. Thanks! I hope in some time I could reinstall my workstation.
