### ISSUE TITLE
COPY failed: stat /var/lib/docker/tmp/docker-builder976733460/myfile.txt: no such file or directory

### ISSUE THREAD

**Issue by matanshukry** [docker/for-win#9801]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Copy succeed and copying the relevant files

### Actual behavior
An error occurs, probably due to paths

### Information
  - Is it reproducible? Yes
  - Is the problem new? Sort of. I found old issues, but they were all closed.
  - Did the problem appear with an update? nope.
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.

  - Windows Version: Windows 10 Version 2004 (Build 19041.685)
  - Docker Desktop Version: 3.0.0 (Accoring to windows "Add or Remove Programs")
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Nope, just windows

- Attempt #1
```
FROM debian:10
COPY D:\dev\tc\server\bin\myfile.txt /srv/myfile.txt
```
Error:
`COPY failed: stat /var/lib/docker/tmp/docker-builder206362662/D:devtcserverbinmyfile.txt: no such file or directory`

- Attempt #2
```
FROM debian:10
COPY D:\\dev\\tc\\server\\bin\\myfile.txt /srv/myfile.txt
```
Error:
`COPY failed: stat /var/lib/docker/tmp/docker-builder264901818/D:\dev\tc\server\bin\myfile.txt: no such file or directory`

- Attempt #3
```
FROM debian:10
COPY /d/dev/tc/server/bin/myfile.txt /srv/myfile.txt
```
Error:
`COPY failed: stat /var/lib/docker/tmp/docker-builder374821074/d/dev/tc/server/bin/myfile.txt: no such file or directory`

- Attempt #4
```
FROM debian:10
WORKDIR /d/dev/tc/server/bin
COPY myfile.txt /srv/myfile.txt
```
Error:
`COPY failed: stat /var/lib/docker/tmp/docker-builder477794586/myfile.txt: no such file or directory`

- Attempt #5
```
FROM debian:10
WORKDIR D:\dev\tc\server\bin
COPY myfile.txt /srv/myfile.txt
```
Error: 
`COPY failed: stat /var/lib/docker/tmp/docker-builder328543707/myfile.txt: no such file or directory`

To be clear, the file do exist:
```
$ ll /d/dev/tc/server/bin/myfile.txt
-rw-r--r-- 1 matan 197609 4 Dec 14 14:25 /d/dev/tc/server/bin/myfile.txt
```

p.s.
I'm using "Git Bash" from https://git-scm.com/downloads

**Comment by tiborvass** [comment]
When you use `FROM debian`, it's going to use a linux image, so linux paths are expected not Windows paths.
Assuming `pwd` returns `/d/dev/tc/server/bin` you can change `D:\dev\tc\server\bin\myfile.txt` to `myfile.txt`. And WORKDIR is the working directory you want inside the container, not outside. Please read https://docs.docker.com/engine/reference/builder/ for further help.

**Comment by matanshukry** [comment]
@tiborvass Did you look at all the attempts? from some reason that didn't work either. Look at attempt #5.

**Comment by tiborvass** [comment]
@matanshukry what is your `pwd` saying?

**Comment by matanshukry** [comment]
`/d/dev/tc/kube/world/docker`
