### ISSUE TITLE
WSL integration with distro Alpine unexpectedly stopped with exit code 1

### ISSUE THREAD

**Issue by cdalexndr** [docker/for-win#9802]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E631F14E-8B3C-46B7-82F8-B975F82EAAD7/20201214125959

### Expected behavior
No error

### Actual behavior
![docker_err](https://user-images.githubusercontent.com/22418250/102083998-1ad3e480-3e1d-11eb-95e2-dc8f16a5bfed.png)

### Information

  - Windows Version: 2004 ( 19041.685)
  - Docker Desktop Version: 3.0.0 (50684)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

Using Alpine WSL with WSL2 engine enabled: https://www.microsoft.com/en-in/p/alpine-wsl/9p804crf0395

Besides this error, everything seems to work fine. Why is this error shown?

### Steps to reproduce the behavior

  1. Start docker
  2. While starting, error is shown

**Comment by Renrhaf** [comment]
I had same issue, restarted docker from factory settings and restarted computer. Seems to work properly again but I lost all my containers.

**Comment by letsjustfixit** [comment]
I get the same with debian:
![kép](https://user-images.githubusercontent.com/9042757/102091258-e3663780-3e1e-11eb-87d3-01ba3f49417d.png)

**Comment by simonferquel** [comment]
@cdalexndr to make docker desktop work with alpine, you need to install glibc (we have some internal tests using https://github.com/sgerrand/alpine-pkg-glibc successfully).
@letsjustfixit, it must be a different issue. Can you send a diagnostic file ?

**Comment by cdalexndr** [comment]
@simonferquel please assist on how to install pkg-glibc.
Alpine distribution is downloaded from Windows store.

**Comment by simonferquel** [comment]
Installation instructions are right on the github page readme: https://github.com/sgerrand/alpine-pkg-glibc#installing

**Comment by cdalexndr** [comment]
Yes, but for linux, and my host is windows. If I run them inside a docker container it will only be applied to that container.
Do I need to modify WSL Alpine distribution to include the glibc?

**Comment by simonferquel** [comment]
You just need to run this from your alpine distro (with `wsl.exe -d alpine`)

**Comment by cdalexndr** [comment]
Indeed, after running `wsl.exe -d alpine --user root` and installing glibc, the error is gone.

**Comment by willyjchen** [comment]
I had the same issue with Ubuntu distro.

Docker Desktop Windows: 3.0.0 (50684)
Windows 10 20H2

**Comment by mwoodpatrick** [comment]
I have the same issue on Ubuntu under WSL-2 after doing the latest Ubuntu updates prior to that it was working, After the update I started getting "WSL integration with distro Ubuntu unexpectedly stopped with exit code 1. Do you want to restart it?" I tried restarting docker desktop, rebooting my PC and resetting docker desktop but to no avail. Anyone know what error 1 is or any suggestions about the best way to debug this.? I reported this in
https://github.com/docker/for-win/issues/9972

**Comment by pyhedgehog** [comment]
Workaround:
```
ln -s lib /lib64
ln -s ld-musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2
```
NB: May badly affect other executables.

**Comment by strarsis** [comment]
So here is how I solved it for WSL 2 Ubuntu 20 (same error, different distribution):
In the WSL 2 system, move everything docker related in `/wsl/` (`/wsl/docker*/`) to some other directory (I don't like deleting stuff, you can always clean it up later). Then I reinstalled Docker for Desktop, re-enabled WSL 2 support for the Ubuntu distribution and it worked afterwards. The full reinstallation of Docker for Desktop wasn't probably the fix but rather removing the `/wsl/docker*` files in the affected distrubtion system.

**Comment by acschm1d** [comment]
I just had the same issue with the **Debian** distro on Win 2004 with Docker Desktop 3.2.2

Restarted the distro by opening PowerShell as an admin and restarting it by typing

`wsl.exe -t <DistroName>`

In my case `<DistroName>` was `Debian`

After that i restarted Docker Desktop and the error no longer appeared.

**Comment by nathanblair** [comment]
Docker for windows needs to expressly support `musl` and there needs to be a proper solution that does not involve "install `glibc` on this system that was explicitly made to not rely on `glibc`".

`glibc` is not static-linking friendly. GNU Licensing is not compatible with all software. There are a plethora of reasons why developers should not be shoehorned into `glibc`.

**Comment by R-Rudolf** [comment]
I had a similar issue (WSL integration stopped with exit code -1), there the issue was a wrong default user in /etc/wsl.conf.
See: https://github.com/docker/for-win/issues/11726
