### ISSUE TITLE
When on Windows, follow Windows standards.

### ISSUE THREAD

**Issue by MicahZoltu** [docker/for-win#981]
### Expected behavior
Config is stored in `%APPDATA%/<vendor>` and large user-specific data files are stored in `%LOCALAPPDATA%/<vendor>`.

### Actual behavior
Config is stored in `%USERPROFILE%/.docker`.

### Information
`%USERPROFILE%` should only contain documents the user has explicitly created/saved to disk (e.g., via a save dialog).  Files automatically generated by an application (such as config/settings) should _NOT_ be stored in `%USERPROFILE%`.  This is not meant to be a dumping ground for any files an application wants, that is what `%APPDATA%/<vendor>` is for.  Docker's `config.json` should be stored in ``%APPDATA%/docker/config.json`.

I know that it is not uncommon for apps ported from Linux to follow the legacy Linux pattern of dumping everything in $HOME but even on Linux there is now a standard for _not_ dumping everything in $HOME.  On top of that, the dot prefixed folder name does _not_ hide a folder on Windows and it can lead to problems since Windows explorer won't let you name a folder starting with a `.`, so if the folder is ever renamed the user must drop to a shell prompt to rename it back.

Please respect the target OS patterns and practices and move Docker's config location to `%APPDATA%/docker`.

**Comment by jasonbivins** [comment]
Hi @MicahZoltu   I added this as an enhancement request for you - to be considered for a future version.  
Thanks for your feedback!

**Comment by MicahZoltu** [comment]
@jasonbivins Curious, is it possible for me to track/watch/monitor the status of the request, or is it in an internal tracking system not exposed to the general public?

**Comment by friism** [comment]
@MicahZoltu I agree with your standpoint that the current approach is not idiomatic to Windows. The problem is that this location has now become established and is assumed by assorted other tools that is not under Docker's control (eg. tools from Google Cloud, etc.). For that reason I'm not sure we'll be able to change this.

**Comment by MicahZoltu** [comment]
I agree/acknowledge that migration is hard, especially when third party tools directly access your tool's configuration files.

My recommendation would be to start out by exposing a registry key that indicates where configuration is stored, and at the same time deprecate (but don't move) the hard-coded location.  Give third party tools time to update to get the configuration directory from the registry, then in a future version actually change location.

An alternative migration path would be to maintain the configuration file in two locations for some amount of time (using the one most recently touched in the case of conflict) and give tools time to switch locations.  Eventually stop replicating to the legacy location.

While it would be great if Docker stopped cluttering my `%USERPROFILE%` directory today, I recognize that migrations are hard and take time.  However, I would advise against indefinitely being a bad Windows citizen because its hard.
