### ISSUE TITLE
Issue with Docker on Windows Home Single Language

### ISSUE THREAD

**Issue by viniciusantonioli** [docker/for-win#9822]
- [ T ] I have tried with the latest version of my channel (Stable or Edge)
  - [ T ] I have uploaded Diagnostics
  - Diagnostics ID: C9E6FFF6-0DFB-4E64-8D3A-1533B5E8318F/20201215145142

### Information

  - Windows Version: Windows 10 Home Single Language v20H2 build 19042.685
  - Docker Desktop Version: 3.0.0 (50684)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

**Comment by tiborvass** [comment]
Please describe your issue and send a complete Diagnostics.
