### ISSUE TITLE
Docker Desktop WSL distro stopped

### ISSUE THREAD

**Issue by drodriguez78** [docker/for-win#9829]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: DDD2E598-4344-47D8-B22A-4D6A72669247/20201216132742

### Information

  - Windows Version: Windows 10
  - Docker Desktop Version: 3.0.0 (50684)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: NO

### Steps to reproduce the behavior

WSL distro stopped while waiting for Lifecycle server.
  >Stdout:
⇨ http server started on /run/guest-services/wsl2-bootstrap-expose-ports.sock
⇨ http server started on /run/guest-services/wsl-cross-distro.sock
execing /sbin/init
  >Stderr:
2020/12/16 13:27:37 resolving /mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-wsl-cli.iso...
2020/12/16 13:27:37 already in cache!
2020/12/16 13:27:38 resolving /mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-for-wsl.iso...
2020/12/16 13:27:38 already in cache!
time="2020-12-16T13:27:38Z" level=info msg="docker.tar is present in the cache"
2020/12/16 13:27:38 Restoring existing exposed ports from the host
time="2020-12-16T13:27:38Z" level=info msg="dialing Unix domain socket /run/guest-services/wsl2-expose-ports.sock for data connection"
time="2020-12-16T13:27:38Z" level=info msg="unable to connect data on Unix domain socket /run/guest-services/wsl2-expose-ports.sock: dial unix /run/guest-services/wsl2-expose-ports.sock: connect: no such file or directory. Is the server restarting? Will retry in 1s."
Error: input/output error
2020/12/16 13:27:38 input/output error

**Comment by theBigGavin** [comment]
try `wsl --update`, maybe can fix
