### ISSUE TITLE
Docker unable to start Windows 10

### ISSUE THREAD

**Issue by themura** [docker/for-win#983]
### Expected behavior
Docker able to start

### Actual behavior
Docker Unable to start

### Information

Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID 95E93956-B089-4F79-A0F2-D8733DA77762)
at Start-MobyLinuxVM, <No file>: line 292
at <ScriptBlock>, <No file>: line 387
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 246
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 123
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

### Steps to reproduce the behavior

  1. Try to start Docker

[log.txt](https://github.com/docker/for-win/files/1203939/log.txt)

**Comment by jasonbivins** [comment]
Hi @themura   You're using a newer version here - has it ever worked for you?

Can you try to restart the Docker for Windows service, then start Docker again?

**Comment by themura** [comment]
First install on this system, I did the stable release first and tried the edge, but had the same issue on both builds.

I manually stopped and started the Docker service, appear to be having the same issue. New log attached.

[log.txt](https://github.com/docker/for-win/files/1206867/log.txt)

**Comment by jasonbivins** [comment]
The MobyLinuxVM isn't able to start - 
Try creating it manually to see if we get a more specific error:
``` powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -destroy
powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -create  ```

**Comment by themura** [comment]
Thanks for your help, Jason. I tried running those commands and this is the error I'm getting:

`PS C:\WINDOWS\system32> powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1
" -destroy
Script started at 23:01:43.913
Module loaded at 23:01:46.693
VM MobyLinuxVM does not exist
Destroying Switch DockerNAT...
Removing VM MobyLinuxVM...
Delete VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
PS C:\WINDOWS\system32> powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1
" -create
Script started at 23:01:55.999
Module loaded at 23:01:58.764
Creating Switch: DockerNAT...
Switch created.
Set IP address on switch
ISO file at .\mobylinux.iso does not exist
At C:\Program Files\Docker\Docker\resources\MobyLinux.ps1:377 char:5
+     throw "$args"
+     ~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (ISO file at .\m... does not exist:String) [], RuntimeException
    + FullyQualifiedErrorId : ISO file at .\mobylinux.iso does not exist`

**Comment by themura** [comment]
Just interesting note on this. I switched to Windows containers and docker is able to start/run now. Not sure why Linux containers aren't working still.

**Comment by arvanoid** [comment]
Same happened to me.  Linux containers fail with ErrorActionPreference

**Comment by Ndaginada** [comment]
You should choose Switch to Windows containers
