### ISSUE TITLE
#7941 Regression

### ISSUE THREAD

**Issue by ntripp13** [docker/for-win#9832]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Log files are silent and stored on startup update check

### Actual behavior
Log file is force opened due to filepath being incomplete when username contains spaces. EX: "User Alpha" -> "C://Users/User"

### Information
  - Windows Version: 10.0.19041 Build 19041
  - Docker Desktop Version: 3.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
  1. Startup PC with Docker auto-launch
  2. See file

**Comment by stephen-turner** [comment]
@ntripp13 Which version did you upgrade from? The bug was finally fixed in 2.5.0.0, but it's the version you upgrade from that matters, so if you upgrade from (for example) 2.4.0.0 to 3.0.0, you will see it one last time.

**Comment by ntripp13** [comment]
I actually had a decent amount of time where I wasn't getting the issue,
but it popped up again a week or so ago and has persisted since.

**Comment by stephen-turner** [comment]
Sorry, I wasn't clear. If you upgrade from 2.4, the bad file is created and needs to be deleted. If you upgrade from 2.5 or 3.0, the file should not be created.

**Comment by ntripp13** [comment]
When I created the issue, I genuinely thought I had already deleted the file after an update and had not experienced the error until posting. That said, I deleted it again, and it seems to be gone for good. Thanks for the assistance!

**Comment by stephen-turner** [comment]
Great, thanks for the update.
