### ISSUE TITLE
4888BC8A-84BA-4319-AA44-093558564001/20201217101315

### ISSUE THREAD

**Issue by MarceloMsan** [docker/for-win#9839]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by tiborvass** [comment]
Please provide steps to reproduce.
