### ISSUE TITLE
Files missing in container (but working on Mac/Linux)

### ISSUE THREAD

**Issue by QAnders** [docker/for-win#984]
### Expected behavior
I have run the same container on Linux and my colleague has it running on Mac without any problems and Web GUI for the product IBM DataPower works fine.

### Actual behavior
When I pulled it to my Windows I get a strange error where one (or possibly more) .js files are missing for the Web GUI. Using the browser's Inspect I can see that a number of files are present but the page crashes because of a missing .js file. I've reached out to IBM who says this is isolated to Windows only, which is my experience as well as the same works fine on Linux/Mac.

### Information

  - EA8688AE-46D9-4BEF-AC19-3C9A89D9A7CE/2017-08-07_08-52-57
  - https://hub.docker.com/r/ibmcom/datapower/
  - Win10 64-bit 1703 build 15063.483

### Steps to reproduce the behavior

  1. docker pull 
  2. ibmcom/datapower:latest
  3. docker run -it -v -e DATAPOWER_ACCEPT_LICENSE=true -e DATAPOWER_INTERACTIVE=true -p 9090:9090 -p 9022:22 --name idgb76 ibmcom/datapower:latest
  4. https://localhost:9090/ login with admin/admin to "Blueprint console". A JavaScript error can be seen in Browser Console for missing .js file.

**Comment by QAnders** [comment]
Seems issue #969 might be related (or similar)

**Comment by friism** [comment]
It doesn't look like the command you posted is complete - what's the `-v`?

**Comment by jasonbivins** [comment]
Hi @QAnders   I can pull the image - but can't run your command.  Can you double check it please?

**Comment by QAnders** [comment]
Sorry, copy n' paste mess up...

docker run -it -v D:/Docker/IDGMountPoint/idgb76/config:/drouter/config -v D:/Docker/IDGMountPoint/idgb76/local:/drouter/local -e DATAPOWER_ACCEPT_LICENSE=true -e DATAPOWER_INTERACTIVE=true -p 9090:9090 -p 9022:22 -p 5554:5554 -p 5550:5550 -p 8000-8010:8000-8010 --name idgb76 ibmcom/datapower:latest

This is the complete cmd with my -v mounts.

**Comment by jasonbivins** [comment]
Hi @QAnders   I was able to run your command on my Windows machine - and noticed that I get a pop-up from the Windows firewall during the build - can you temporarily disable the Windows firewall and try again?  Please re-post another Diagnostic ID afterwards

**Comment by QAnders** [comment]
Still the same I am afraid: 
`20170807T160606.844Z [0x80e00002][http][error] httpserv(webgui-webserv): tid(1056): 'webgui:/js/dojo/dgrid/util/tou
ch.js' - file not found`

New diag id: EA8688AE-46D9-4BEF-AC19-3C9A89D9A7CE/2017-08-07_18-06-58

**Comment by QAnders** [comment]
Seems to be something to do with a touch screen and that the file is actually missing from the container!
