### ISSUE TITLE
The stewardess can not use it on windows, what should I do?

### ISSUE THREAD

**Issue by witthawat0122zxc** [docker/for-win#9840]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by witthawat0122zxc** [comment]
The stewardess can not use it on windows, what should I do?

**Comment by witthawat0122zxc** [comment]
Docker does not work on windows, what can i do?

**Comment by xiaohuifirst** [comment]
me too...

**Comment by tiborvass** [comment]
What you can do is follow the issue template, provide an explanation of what exactly you did, what's not working and send a diagnostics ID. The more information the better. With no information, there's not much we can do to help.
