### ISSUE TITLE
Windows containers default "nat" network broken. No Internet for Windows containers.

### ISSUE THREAD

**Issue by darkvertex** [docker/for-win#9847]
- [X] I have tried with the latest version of my channel (Stable)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID:
5AD1B97B-12F9-4F95-90CE-6C522D4C69B7/20201217183648

### Expected vs Actual Behavior

I seem to have a problem with the default networking of containers in WINDOWS mode. They do not appear to have internet access by default. In Linux container mode, it's fine.

A simple dns lookup like:
```
> docker run --rm mcr.microsoft.com/windows/servercore:ltsc2019 powershell nslookup google.com
*** Request to UnKnown timed-out
DNS request timed out.
    timeout was 2 seconds.
Server:  UnKnown
Address:  172.24.32.1

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
```
It fails and times out. Passing `--dns=8.8.8.8` to force a DNS server fails as well. The networking is borked.

When I list my networks it looks like this:

```
> docker network list
NETWORK ID     NAME                            DRIVER    SCOPE
2ec01d094d80   Default Switch                  ics       local
3eb870794fe2   Fortinet Ethernet VPN (IPSec)   ics       local
1f0533d71e0a   Fortinet Ethernet VPN (SSL)     ics       local
5051a5434c14   WSL                             ics       local
c3c939d5f2d5   Wi-Fi                           ics       local
b2bb79e6bb96   nat                             nat       local
e51ef490b457   none                            null      local
```
(My "Wi-Fi" network is the one that has Internet access.)

If I run passing `--network="Wi-Fi"`, it works...
```
> docker run --rm --network="Wi-Fi" mcr.microsoft.com/windows/servercore:ltsc2019 powershell nslookup google.com
Non-authoritative answer:
Server:  UnKnown
Address:  192.168.86.1

Name:    google.com
Addresses:  2607:f8b0:4020:807::200e
          172.217.13.110
```

Using WSL2, my Ubuntu has no problem reaching the internet, and again, neither do Linux containers. **Only Windows containers seem to have trouble.** (Also my VPN was off, for the record.)

I have tried:
- uninstalling, reinstalling Docker Desktop
- uninstalling the Hyper-V "feature" on Windows and enabling it again.
- uninstalling the Hyper-V "feature", uninstalling all "vEthernet" devices from Device Manager, and enabling Hyper-V again.
- stopping Docker, deleting all "vEthernet" devices, enabling it again.
- tried setting DNS IPs in the daemon.json, did nothing.
- tried disabling Windows Firewall specifically on all vEthernet network adapters, did nothing.

I'm out of ideas.

### Information

It seemed to be after a recent update that my Windows container networking stopped working.

  - Windows Version: Win10 Pro (10.0.19042 Build 19042)
  - Docker Desktop Version: 3.0.0 (50684 with Engine 20.10.0)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: _No. This is a laptop from 2018._

**Comment by duha5h** [comment]
Did you solve this issue?? 
I faced it too, and cannot resolve it until now.

**Comment by darkvertex** [comment]
> Did you solve this issue??

I did not. 😞 I still have to add `--network="Wi-Fi"` to every Windows container `docker run` call.

**Comment by duha5h** [comment]
> > Did you solve this issue??
> 
> I did not. 😞 I still have to add `--network="Wi-Fi"` to every Windows container `docker run` call.

Thank you for your reply.

I have one more question, I used **docker compose,** how can I add `--network="Wi-Fi"` to it?

**Comment by darkvertex** [comment]
> I have one more question, I used **docker compose,** how can I add `--network="Wi-Fi"` to it?

I haven't confirmed but in theory something like this might work:

```yaml
version: "3.5"
services:
  proxy:
    image: hello-world
    ports:
      - "80:80"
    networks:
      - mywifi

networks:
  mywifi:
    name: "Wi-Fi"
```
In theory when docker-compose is asked to use a network, it checks if it exists and it creates it if not, but if it exists it uses it as-is, so I'd assume one can trick it to use the Wifi network this way. 🤷‍♂️

**Comment by duha5h** [comment]
> I haven't confirmed but in theory something like this might work:
> 
> ```yaml
> version: "3.5"
> services:
>   proxy:
>     image: hello-world
>     ports:
>       - "80:80"
>     networks:
>       - mywifi
> 
> networks:
>   mywifi:
>     name: "Wi-Fi"
> ```
> 
> In theory when docker-compose is asked to use a network, it checks if it exists and it creates it if not, but if it exists it uses it as-is, so I'd assume one can trick it to use the Wifi network this way. 🤷‍♂️

Thank you. it didn't work for me. Also, I try using `docker run` but it didn't work. 
I think I have this issue because of [McAfee](https://ryanhayes.net/how-to-run-docker-windows-containers-with-mcafee-endpoint-security/)

**Comment by darkvertex** [comment]
This is still an issue. 😞

/remove-lifecycle stale
/lifecycle frozen

**Comment by TrevorT** [comment]
Apparently, by default, Docker tries to use the "NetIPInterface' with the lowest InterfaceMetric.
To check, in Powershell: 
`Get-NetIPInterface -AddressFamily IPv4 | Sort-Object -Property InterfaceMetric -Descending`
Then, to set InterfaceMetric of your preferred item (Wi-Fi in this case) so that one Docker will use it:
`Set-NetIPInterface -InterfaceAlias 'Wi-Fi' -InterfaceMetric 2`

(the last argument (2) can be replaced by any InterfaceMetric value lower than that of all other items (or perhaps, all other Enabled items, not sure))

**Comment by darkvertex** [comment]
I think something happened and it sorted itself with recent updates. I can no longer reproduce the issue. 🤷‍♂️

Hopefully it's solved for you too @duha5h
