### ISSUE TITLE
Unexpected disconnect during download (Windows)

### ISSUE THREAD

**Issue by InteXX** [docker/for-win#985]
This issue was closed unexpectedly, apparently without resolution of the original problem:

https://github.com/docker/for-win/issues/856

Has the download disconnection problem been fixed?

**Comment by jasonbivins** [comment]
Hi @InteXX ,
Are you behind any proxies in your network, or any hardware firewalls ?
I dug into this a bit more, and we can't find any disconnects or timeout in the downloaders - but we are working on integrating a cache feature that will hopefully help with this.  It should be released soon, but I don't have a specific timeframe yet. 
One thing that might help, is a new daemon config option called Max-Concurrent-Downloads.   I tested it on my machine and it seemed to speed up the pulls considerably.  Check here for an explanation of how to set options for the [Daemon](:https://docs.docker.com/engine/reference/commandline/dockerd/#windows-configuration-file)
Find your config file - and add this line, then Restart Docker  ``` , "max-concurrent-downloads": 3 ```

**Comment by InteXX** [comment]
@jasonbivins — No proxy, hardware firewall. I'll try again with the config file option, but I notice you mention that it's new.

I'm currently at `17.03.1-ee-3, build 3fcee33`; do I need to upgrade to gain access to the feature?

**Comment by jasonbivins** [comment]
The latest EE version is Docker EE 17.03.2-ee5 so an upgrade couldn't hurt -but it's safe to try making this config change either way.  You can try this as well, since you're working with extreme bandwidth issues 

``` , "max-concurrent-downloads": 3```
