### ISSUE TITLE
Cannot Pull Windows Docker Images from WSL 2

### ISSUE THREAD

**Issue by wtchappell** [docker/for-win#9851]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 403FDAA4-2BA3-4C7B-A222-488FE2BB9CFF/20201218041947

### Expected behavior
From within an integrated WSL 2 instance, I can pull and run Windows Docker images.

### Actual behavior
Error response from daemon: Get https://docker-registry.a-company.com/v2/: dial tcp: lookup docker-registry.a-company.com on 192.168.65.1:53: read udp 192.168.65.3:57019->192.168.65.1:53: i/o timeout

### Information

  - Windows Version: Windows 10 Pro 20H2 / 19042.685
  - Docker Desktop Version: 3.0.0 (50684)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No.

### Steps to reproduce the behavior

  1. Try to pull Windows docker images from a WSL 2 instance.
  2. Observe failures.

#### What have you tried
- [x] Setting Docker Desktop's DNS settings to `8.8.8.8`
- [x] Setting WSL 2 instance's resolv.conf to `nameserver 8.8.8.8`
- [x] Adding docker registry IP directly to Windows hosts file.
- [x] Adding docker registry IP directly to Linux hosts file.
- [x] Multiple restarts
- [x] Swapping between Windows and Linux mode
- [x] Waiting for months, upgrading Docker Desktop

**Comment by jareqpl** [comment]
I am having exactly the same issue. I wonder if anyone succesfully ran docker with windows containers from docker in WSL.
It works only when accessed from windows.

**Comment by jareqpl** [comment]
But, pulling linux images works fine. It fails to pull any image after i switch to windows containers.

**Comment by wtchappell** [comment]
@jareqpl I can confirm I've seen that behavior as well; pulling Linux images doesn't seem to trigger this failure mode, but pulling a Windows image does.

I've just been working around this by switching over to Powershell to interact with Docker, but it does mean I have to do a lot of manual work and can't rely on my company's WSL2 scripts that expect to be called from within WSL2 instead of native Windows.

**Comment by iHarshalAgarwal** [comment]
Pulling Linux image doesn't work for me

**Comment by iHarshalAgarwal** [comment]
Restore to default worked for me

**Comment by jareqpl** [comment]
I've reinstalled windows completly and this issue still occurs.

**Comment by berengamble** [comment]
I've also uninstalled everything (including WSL2) and reinstalled everything. Tried adding `"dns": [ "8.8.8.8" ] to the docker engine config. No joy.

**Comment by wtchappell** [comment]
I also still have this problem on a fresh installation, and have completely given up on WSL/Docker integration on WSL2.

**Comment by wtchappell** [comment]
Is there any advice on this at all? Definitely feels like we're shouting into the void here.
