### ISSUE TITLE
denied: requested access to the resource is denied

### ISSUE THREAD

**Issue by sanjeethflautist** [docker/for-win#9857]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:9F2E9E2C-25B5-473E-A1C1-D82357ED454B/20201218122109

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by sacof** [comment]
I'm having the same problem. Any help?
