### ISSUE TITLE
Can't uninstall Docker Desktop

### ISSUE THREAD

**Issue by kayest** [docker/for-win#9865]
I can't uninstall or install Docker Desktop 3.0.0. When trying to launch Docker Desktop on my Windows 10 Pro PC, I get "Docker Desktop has stopped working". I tried to uninstall it, but exited out of the uninstall program after 40 minutes of seeing this:

Docker Desktop 3.0.0
Uninstalling...
Removing VM and images

I couldn't try In-App Diagnostics since Docker Desktop won't launch. 

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics - I could not upload Diagnostics
  - Diagnostics ID:

### Expected behavior
Uninstall Docker Desktop so I can start over with a fresh installation.

### Actual behavior
Gets stuck on Uninstall process. 

Also, when I abandon the uninstallation process and try to install the latest version using "Docker Desktop Installer.exe", this happens:
1. Do you want to allow this app to make changes to your device?
2. Click Yes
2. Downloading package
3. Existing installation is up to date
4. Close installation modal
5. Navigate to Start > Docker. Docker Desktop is not listed.
6. Reboot. Still no Docker Desktop.
7. Check Program Files > Docker. Nothing in the folder except for "Docker Desktop Installer.exe".

I then try to Uninstall:
1. Apps & features
2. Click on "Docker Desktop", which shows nothing for amount of storage used. The "Modify" button is also disabled.
3. Click "Uninstall".
4. "This app and its related info will be uninstalled".
5. Click "Uninstall" button.
6. Do you want to allow this app to make changes to your device?
7. Click Yes
8. Uninstall modal (Uninstalling Docker Desktop 3.0.0 (50684) appears with "Docker Desktop 3.0.0" at top and "Uninstalling..." underneath. Nothing else appears in the modal. 
9. After 10 minutes, I clicked the x to close the modal.

### Information

  - Windows Version:
  - Docker Desktop Version: 3.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Go to "Apps & Features"
  2. Select Docker Desktop 3.0.0
  3. Click "Uninstall" ("Modify" button is disabled)

**Comment by Xenador77** [comment]
Same problem, tried deleting all docker files, going through regedit, powershell scripts, chocolatey, removing WSL etc..

**Comment by alex73630** [comment]
I have a similar situation.

Docker refused to update from 3.0.0 to 3.0.x, I've tried multiple solutions to no avail (including some from #7489), the installer/updater seems to always hang after finding the installation folder as highlighted in all my install logs :
`[10:30:23.405][Program] Existing installation found: version=50684, displayVersion=3.0.0, basePath=C:\Program Files\Docker\Docker, channelUrl=https://desktop.docker.com/win/stable/appcast.xml`

I tried to do a Factory reset then disable Hyper-V then after a restart, disabled the Docker service and uninstall the app without success.

The Windows Event Observer also logs an Application Error which strangely is linked to the d3d9.dll (DirectX 9 lib ?!)
Here is the entry (in French): 
```
Nom de l’application défaillante Docker Desktop Installer.exe, version : 3.0.0.50684, horodatage : 0xaa4640dc
Nom du module défaillant : d3d9.dll, version : 10.0.19041.662, horodatage : 0x4653c355
Code d’exception : 0xc0000005
Décalage d’erreur : 0x000000000000a22b
ID du processus défaillant : 0x5f4
Heure de début de l’application défaillante : 0x01d6ea57c9e831b2
Chemin d’accès de l’application défaillante : C:\Users\Alexandre\AppData\Local\Temp\jcmgk5ke.gok\Docker Desktop Installer.exe
Chemin d’accès du module défaillant: C:\WINDOWS\SYSTEM32\d3d9.dll
ID de rapport : 5f4f7e25-7f75-43df-b74c-cfcb26bcf9a4
Nom complet du package défaillant : 
ID de l’application relative au package défaillant : 
```

I'll do some research to see if there is actually an issue with DirectX 9 and give an update later today.

**Comment by alex73630** [comment]
UPDATE !
So after a small Googling session, I found this issue #2906

Someone explained that he tried to close any apps that could use DirectX, and may cause issue.
Apparently MSI Afterburner (with the RivaTuner overlay?) hooking into the DirectX lib is causing a crash on the installer (which never happened to me before this).

The solution is to close any app that can hook to the DirectX lib (fps overlay, debuggers, screen capture softwares) before doing a Docker Desktop update/install/uninstall.
