### ISSUE TITLE
B08B8D32-F621-484B-AD2D-FCE662672AFF/20201220001716

### ISSUE THREAD

**Issue by songjianxing** [docker/for-win#9869]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by tiborvass** [comment]
Please provide more information: what's the issue you're seeing, and what steps did you do, etc.
