### ISSUE TITLE
w

### ISSUE THREAD

**Issue by wff0** [docker/for-win#9874]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by tiborvass** [comment]
Please provide more details: what are the steps to reproduce your issue? Please send a Diagnostics ID.
詳細を教えてください: 問題を再現するための手順を教えてください。診断IDを送信してください。(deepl.com)

**Comment by stephen-turner** [comment]
No info provided, closing.
