### ISSUE TITLE
la máquina virtual o el contenedor con el identificador especificado no se está ejecutando. (0xc0370110)

### ISSUE THREAD

**Issue by josealexander123** [docker/for-win#9885]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by josealexander123** [comment]
A2BCD834-2E03-4723-A661-29DA80989E08/20201221063226

**Comment by paulens12** [comment]
I don't think anyone speaks your language here. If you want help, you'll have to describe your problem in English.
