### ISSUE TITLE
Security policies problems with current Proxy mechanism

### ISSUE THREAD

**Issue by faustool** [docker/for-win#99]
I am aware of the existing mechanism to setup corporate proxy in Docker for Windows settings UI. And I also know how to put my user and password in the URL:

user:pass@proxyhost:port

However, what my corporation (like many others I suppose) doesn't approve is the use of plain text passwords.

Please consider a more secure way to set this up.

**Comment by rneugeba** [comment]
@faustool thanks for the feedback. We are indeed looking at improved proxy support, but we don't have ETA for this yet

**Comment by jasonbivins** [comment]
entered this in as an enhancement request  #7423
