### ISSUE TITLE
Docker CLI intermittently (likely network issue) hangs for approx. 45 seconds after every command

### ISSUE THREAD

**Issue by markoueis** [docker/for-win#9904]
Everyone once in a while docker desktop gets into a state where the CLI hangs after any and every command. The solutions we've found for this in the past is to sometimes restart the machine or sometimes start to play with network things (like disable network and reenable) and that sometimes kicks it back into gear and thing start working again.

I'm on latest stable: 3.0.0 (50684)

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
  - F4D29FA0-6778-40B8-B312-BADEA278BB3B/20201223160010

### Expected behavior
For CLI to work without hanging

### Actual behavior
Hanging - see gif:

![dockerclihangs](https://user-images.githubusercontent.com/23063832/103016225-bfd27980-450f-11eb-9647-75c110968d1e.gif)

### Information

  - Windows Version: Windows 10 2004
  - Docker Desktop Version: 3.0.0 (50684)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
No, this is on a laptop

### Steps to reproduce the behavior
See gif. I suspect this might have something to do with either sleep/hibernation or some networking thing

**Comment by stephen-turner** [comment]
Do you have any corporate security software that could be inserting itself on the network path? I remember a previous similar report which was caused by misconfigured McAfee software.
