### ISSUE TITLE
Docker Desktop install fails start on windows 10 

### ISSUE THREAD

**Issue by ChinaVolvocars** [docker/for-win#9912]
Caption              : Microsoft Windows 10 专业版
Manufacturer         : Microsoft Corporation
OSArchitecture       : 64 位
Version              : 10.0.18363

发送请求时出错。
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 CommunityInstaller.DownloadStep.<DoAsync>d__39.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()

**Comment by NUNIDEcainiao** [comment]
my error is
Component CommunityInstaller.AutoStartAction failed: 尝试执行未经授权的操作。
   在 CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
