### ISSUE TITLE
Cannot create VSS snapshot inside docker container

### ISSUE THREAD

**Issue by mappu** [docker/for-win#992]
### Expected behavior

```
C:\HOST>docker exec --rm -it microsoft/windowsservercore:latest
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\GUEST>vssadmin create shadow /for=C:
vssadmin 1.1 - Volume Shadow Copy Service administrative command-line tool
(C) Copyright 2001-2013 Microsoft Corp.

Successfully added the shadow copy storage association
```

### Actual behavior

```
C:\HOST>docker exec --rm -it microsoft/windowsservercore:latest
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\GUEST>vssadmin create shadow /for=C:
vssadmin 1.1 - Volume Shadow Copy Service administrative command-line tool
(C) Copyright 2001-2013 Microsoft Corp.

Error: The shadow copy provider had an unexpected error while trying to process
the specified command.
```

### Information

Host is Windows 10 15063
Docker for Windows 17.06.0-ce-win19 (12801)

### Steps to reproduce the behavior

(as above)

I wonder if this is
- a limitation of Docker, or
- a limitation of the containerisation systems on Windows, or
- if it's simply because it's also not possible in my host OS (the `create shadow` subcommand on `vssadmin` only works on Windows Server, not windows desktop).

Apologies if this is the wrong repository or if it should be reported to some microsoft issue tracker instead,

**Comment by friism** [comment]
What's your use case for this? Ideally you'd just use `docker commit` to save the state of a Docker container, but that's not implemented on Windows yet.

**Comment by mappu** [comment]
My use case is: to containerize some windows software that uses VSS snapshots.

**Comment by jasonbivins** [comment]
Hi @mappu   I tested with a couple of different microsoft images - and they all give the same error, but the rest of the VSS commands seem to be working.   There are errors in the Application event logs - so I'll dig into those and get back to you if I find anything useful
