### ISSUE TITLE
can't change image location and Hyper-v manager doesn't show MobyLinuxVM

### ISSUE THREAD

**Issue by ElBoshy** [docker/for-win#9926]
- [ Stable] I have tried with the latest version of my channel (Stable or Edge)
  - [No ] I have uploaded Diagnostics

### Expected behavior
change image location  using data-root or show MobyLinuxVM in Hyper-V Manager
### Actual behavior
crash when using data-root attribute and when use Hyper-V Manager no VMs listed and docker work correctly but i have problem with changing image location
### Information

  - Windows Version: Microsoft Windows 10 Pro Build Number : 19042
  - Docker Desktop Version: 20.10.0, build 7287ab3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. install docker latest version
  2. open hyper-v manager to show the list of VMs which is running 
  3. nothing listed
![Untitled](https://user-images.githubusercontent.com/11808812/103160927-78840b80-47e3-11eb-9704-c7a6d4c15e56.png)

**Comment by stephen-turner** [comment]
Are you in fact using the Hyper-V backend or the WSL 2 backend? If you are using the Hyper-V backend, then you should see a VM in there. So I suspect you're using WSL 2.

**Comment by ElBoshy** [comment]
thanks for your reply but how to know if i am use hyper-v backend or wsl 2 backed and how to switch from wsl to hyper-v

**Comment by stephen-turner** [comment]
In the Settings, on the General tab.

**Comment by ElBoshy** [comment]
yes , now it worked

**Comment by stephen-turner** [comment]
Great, thanks for letting us know.
