### ISSUE TITLE
Issues when trying to share C drive

### ISSUE THREAD

**Issue by pepijnijben** [docker/for-win#993]
### Expected behavior
Sharing my C drive
### Actual behavior
Not sharing my C drive, and no errors come up what so ever. It just refreshes to when the C box was unticked.
### Information

  - Diagnostic ID: FF1F1D82-4E38-4B16-BFC9-43B0A8795D43/2017-08-10_15-35-13
  - Windows 10 Education, Version 1703, OS Build 15063.540

### Steps to reproduce the behavior

  1. ... Tick box to share C drive
  2. ... Click apply
  3. ... Enter credentials

**Comment by fabiogusmao** [comment]
Hi @pepijnijben try looking at your log file and see if it is the same as #989 or #941

**Comment by jasonbivins** [comment]
Hi @pepijnijben   It does look like you're seeing a similar issue with the Docker daemon not running, but I'm also seeing some access denied errors.  Are you connected to your Domain when you try to share the drives?

**Comment by kapilsdv** [comment]
Hi @fabiogusmao  @jasonbivins , #995 #993 looks similar and in my case (my comment on #995) has no resemblance with  #989 or #941
