### ISSUE TITLE
Docker Desktop crashes on startup

### ISSUE THREAD

**Issue by Quozzo** [docker/for-win#9930]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker Desktop is able to start

### Actual behavior
Docker Desktop crashes on startup.

### Information

  - Windows Version: Windows 10 Pro
  - Docker Desktop Version: Latest
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
1. Installed on Windows 10 Pro before WSL2 was an option, so Hyper-V was used.
2. When Windows was patched to allow WSL2 I upgraded Windows, but didn't alter any settings in Docker.
3. Only a few days ago I enabled the option to allow Docker to use WSL2 which caused it to restart.
4. It restarted, and promptly crashed. I've been unable to restart it since.
5. Uninstalling doesn't work as it crashes before it can uninstall and Reinstalling doesn't work as it's on the latest patch already.

**Comment by Quozzo** [comment]
I fixed the issue. At least for me. I noticed in VSCode that WSL2 was an option, and enabled, but there was no default distro, presumably because there was no distro at all. So I clicked the link and followed the instructions to install a distro from here:

https://docs.microsoft.com/en-us/windows/wsl/install-manual

Now Docker Desktop is able to start.

**Comment by stephen-turner** [comment]
Great, I'll close the ticket.
