### ISSUE TITLE
Docker system info - reports incorrect figures

### ISSUE THREAD

**Issue by eliassal** [docker/for-win#9931]
- [ X] I have tried with the latest version of my channel (Stable or Edge)
  - [X ] I have uploaded Diagnostics
  - Diagnostics ID: 4D36D48D-A561-465F-BE67-71230B5093B1/20201227165155

### Expected behavior
Get right number of containers running /stopped when issuing 
docker system info --format ‘Number of containers running is: {{.ContainersRunning}}’
### Actual behavior
Issuing
 docker ps
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES

issuing
docker system info --format ‘Number of containers running is: {{.ContainersRunning}}’
Number of containers running is: 18
### Information

  - Windows Version: win 10 2004 Build 19041.685
  - Docker Desktop Version:  Docker version 20.10.0, build 7287ab3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: NO

### Steps to reproduce the behavior

  1. Issue the command 
  2. docker system info --format ‘Number of containers running is: {{.ContainersRunning}}’
  3. 
![dockerSysInfos](https://user-images.githubusercontent.com/8447864/103175850-76ff2580-486d-11eb-86ac-2714cd4dcfa5.jpg)

**Comment by stephen-turner** [comment]
Do you have Kubernetes system containers? If so there are not shown by docker ps by default. There is a checkbox in the Desktop settings to include them in the docker ps output.

**Comment by eliassal** [comment]
Thanks, correct, I checked it and now I can see the right figures. However, in Docker desktop interface, I stop all pods/vms but it restarts again and again. How can I stop them definitely? Thanks again

**Comment by stephen-turner** [comment]
Right, because Kubernetes is self-healing. The easiest way is just to turn off Kubernetes in the Docker Desktop settings.
