### ISSUE TITLE
After Blue Screen of Death on WinNat, Docker never worked again,

### ISSUE THREAD

**Issue by cdonke** [docker/for-win#994]
### Expected behavior

Docker to Start

### Actual behavior
`Object reference not set to an instance of an object.
   at Docker.Backend.Processes.WindowsDockerDaemon.StopLogging() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 82
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 77
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 46
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145`

### Information

PS C:\windows\system32> Get-Service com.docker.service

Status   Name               DisplayName
------   ----               -----------
Running  com.docker.service Docker for Windows Service

PS C:\windows\system32> Get-Service winnat

Status   Name               DisplayName
------   ----               -----------
Stopped  winnat             Windows NAT Driver

PS C:\windows\system32> Start-Service winnat
Start-Service : Service "Windows NAT Driver (winnat)" cannot be started due to the following error: Cannot start
service winnat on computer '.'.
At line:1 char:1
+ Start-Service winnat
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
   ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand`

PS C:\windows\system32> get-netnat | Remove-NetNat

Confirm
Are you sure you want to perform this action?
Performing operation Delete on Target H71370b20-d958-4573-a51b-88e2358400f9 PolicyStore Local
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): y
Remove-NetNat : The requested operation is not supported.
At line:1 char:14
+ get-netnat | Remove-NetNat
+              ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (MSFT_NetNat (In...2358400f9;0...):root/StandardCimv2/MSFT_NetNat) [Re
   move-NetNat], CimException
    + FullyQualifiedErrorId : Windows System Error 50,Remove-NetNat

PS C:\windows\system32> cd C:\ProgramData\Docker\config\
PS C:\ProgramData\Docker\config> gc .\daemon.json
gc : Access to the path 'C:\ProgramData\Docker\config\daemon.json' is denied.
At line:1 char:1
+ gc .\daemon.json
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (C:\ProgramData\Docker\config\daemon.json:String) [Get-Content], Unaut
   horizedAccessException
    + FullyQualifiedErrorId : GetContentReaderUnauthorizedAccessError,Microsoft.PowerShell.Commands.GetContentCommand

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
7BB6222A-10AE-4F24-B2E9-6ADBB0477AB2/2017-08-10_20-56-42

  - host distribution and version (Windows version, build number, etc)

PS C:\windows\system32> docker version
Client:
 Version:      17.07.0-ce-rc1
 API version:  1.31
 Go version:   go1.8.3
 Git commit:   8c4be39
 Built:        Wed Jul 26 05:19:44 2017
 OS/Arch:      windows/amd64
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.31/version: open //./pipe/docker_engine: The system c
annot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to
 connect. This error may also indicate that the docker daemon is not running.`

### Steps to reproduce the behavior
1 - Had a BSoD on winnat
2 - After that, couldn't add/remote NetNet
3 - Docker service changes ownership of daemon.json, so it get access denied.

4 - running "dockerd --debug --data-root SOMEOTHERPATH" works
5 - without the --debug, it fails trying to create HNS.

6 - Tried uninstalling and installing Hyper-V, Containners, Docker for Windows Stable and Edge.

Nothing works...

[service.5.txt](https://github.com/docker/for-win/files/1216665/service.5.txt)
[service.6.txt](https://github.com/docker/for-win/files/1216666/service.6.txt)
[service.7.txt](https://github.com/docker/for-win/files/1216663/service.7.txt)
[service.8.txt](https://github.com/docker/for-win/files/1216662/service.8.txt)
[service.txt](https://github.com/docker/for-win/files/1216664/service.txt)
[service.4.txt](https://github.com/docker/for-win/files/1216667/service.4.txt)

**Comment by pradley** [comment]
Im having this exact problem
