### ISSUE TITLE
WSL integration with distro Ubuntu unexpectedly stopped with exit code 1.

### ISSUE THREAD

**Issue by mwoodpatrick** [docker/for-win#9972]
I am running latest docker desktop on windows 10 pro (Build 19042) with WSL2 and Ubuntu 20.04.1 distribution and it was working fine but today I started getting "WSL integration with distro Ubuntu unexpectedly stopped with exit code 1. Do you want to restart it?" I tried restarting docker desktop, rebooting my PC and resetting docker desktop but to no avail. Anyone know what error 1 is or any suggestions about the best way to debug this.?

Diagnostics uploaded with id:

BB627E01-A658-447E-8046-C1F13A8C3150/20201231014758

**Comment by rfay** [comment]
I can't get Docker going at all any more after this failure.

**Comment by mwoodpatrick** [comment]
I am seeing the same problem with Docker desktop 3.0.4

**Comment by voipAsteriskGuy** [comment]
Hi i had the same issue when updated docker desktop with wsl2 backed has a work around i did the following steps:

1.- In docker desktop settings i enabled again the "enabled integration with other distros" 
2.- Apply and restart the changes then stop Docker desktop.
3.- Enter to Settings -> Apps and search for ubuntu
4.- Click on Ubuntu and advanced settings
5.- Select repair 
6.- Restart the computer
7.- After computer starts enter to the ubuntu wsl via console or terminal
8.- start docker desktop
9.- try docker ps or docker-compose to check if the error was resolved.
I see this issue happening on a computer with latest Ubuntu but not happening on Ubuntu 18.04

Hope this help!

**Comment by Grimm-Child** [comment]
I'm having the same problem with WSL2 and Ubuntu, Ubuntu-16, Ubuntu-18, and Ubuntu-20. I've uninstalled, re-imstalled, restarted Docker, reset Docker, repaired Docker and Ubuntu(s), purged all Docker tmp, cache, and config files, and nothing has worked.

**Comment by finngl** [comment]
Same problem here.

**Comment by strarsis** [comment]
+1, same issue suddenly occured. Maybe some networking thing?

**Comment by ljr95** [comment]
Hello
I had the same problem, to solve it I did the WSL Ubuntu updates (sudo apt update && sudo apt upgrade -y) and restarted Windows.
Hope this works for you.

**Comment by binaryfiddle** [comment]
@ljr95  Tried doing  

> Hello
> I had the same problem, to solve it I did the WSL Ubuntu updates (sudo apt update && sudo apt upgrade -y) and restarted Windows.
> Hope this works for you.

The Above solution did not work, still facing the same docker issue

**Comment by ljr95** [comment]
> @ljr95 Tried doing
> 
> > Hello
> > I had the same problem, to solve it I did the WSL Ubuntu updates (sudo apt update && sudo apt upgrade -y) and restarted Windows.
> > Hope this works for you.
> 
> The Above solution did not work, still facing the same docker issue

Sorry if it doesn't work.
I had also purged the Docker cache, in the Docker application -> Troubleshoot -> Clean / Purge data then restart the Windows.
You should try.

Have you checked to see if you have any Windows updates to do?

**Comment by Arvi89** [comment]
Same here, I've re-installed docker windows, updated my Ubuntu, still doesn't work :(

**Comment by Arvi89** [comment]
Oh, I've just found a solution for my problem:
I had a specific config in /etc/wsl.conf
nameserver 1.1.1.1
I emptied the file, restarted wsl (wsl --shutdown from powershell) and now it works.

**Comment by binaryfiddle** [comment]
@Arvi89 there is no such file in my etc folder

**Comment by todpale** [comment]
I've got the same problem. My solution is: 
1) close Docker Desktop
2) restart Ubuntu through services.msc or this command (you can put in bat):
`net stop LxssManager && net start LxssManager`

You also may to check if your distro is enabled in Docker settings (General tab and Resources tab -> WSL Integration). I don't know why but it switches off sometimes.

**Comment by gperezivo** [comment]
> I've got the same problem. My solution is:
> 
> 1. close Docker Desktop
> 2. restart Ubuntu through services.msc or this command (you can put in bat):
>    `net stop LxssManager && net start LxssManager`
> 3. start Docker again
> 
> You also may check if your distro is enabled in Docker settings (General tab and Resources tab -> WSL Integration). I don't know why but it switches off sometimes.

Works for me! Thanks!

**Comment by NewNeonNeo** [comment]
This fixed it for me. https://github.com/docker/for-win/issues/7039#issue-630069905

**Comment by Noext** [comment]
> Oh, I've just found a solution for my problem:
> I had a specific config in /etc/wsl.conf
> nameserver 1.1.1.1
> I emptied the file, restarted wsl (wsl --shutdown from powershell) and now it works.

very thanks, it seems that changing the nameserver in wsl broke the docker integration....

**Comment by jhonnymakis** [comment]
> > I've got the same problem. My solution is:
> > 
> > 1. close Docker Desktop
> > 2. restart Ubuntu through services.msc or this command (you can put in bat):
> >    `net stop LxssManager && net start LxssManager`
> > 3. start Docker again
> > 
> > You also may check if your distro is enabled in Docker settings (General tab and Resources tab -> WSL Integration). I don't know why but it switches off sometimes.
> 
> Works for me!

Works for me!
Thanks!

**Comment by mikelor** [comment]
@gperezivo's fix of

> Check if your distro is enabled in Docker settings (General tab and Resources tab -> WSL Integration).
Worked for me. Restarted Docker and everything worked fine. No need for the other commands.
Running Ubuntu.

**Comment by mhawila** [comment]
> You also may check if your distro is enabled in Docker settings (General tab and Resources tab -> WSL Integration). I don't know why but it switches off sometimes.

Yep this did it for me.

**Comment by rudiantotiofan** [comment]
> I've got the same problem. My solution is:
> 
> 1. close Docker Desktop
> 2. restart Ubuntu through services.msc or this command (you can put in bat):
>    `net stop LxssManager && net start LxssManager`
> 3. start Docker again
> 
> You also may check if your distro is enabled in Docker settings (General tab and Resources tab -> WSL Integration). I don't know why but it switches off sometimes.

Thanks ! this work for me

**Comment by R-Rudolf** [comment]
I had a similar issue (WSL integration stopped with exit code -1), there the issue was a wrong default user in /etc/wsl.conf.
See: https://github.com/docker/for-win/issues/11726

**Comment by sharmashobhit** [comment]
If you're okay with losing the data, you can try:

powershell: 
```
wsl --unregister docker-desktop
wsl --unregister docker-desktop-data
```

**Comment by daephx** [comment]
All the above solutions don't seem to help suppress the `exit 1` notification toast error. 
It would just keep providing the popup to restart no matter how many times I clicked it or reinstalled.

I've bounced between that and docker commands just not even being recognized:
> The command 'docker' could not be found in this WSL 2 distro
> We recommend to activate the WSL integration in Docker Desktop settings.

I have integration for the particular distro enabled and it's also the default.
[Rudolf's workaround](https://github.com/docker/for-win/issues/11726#issuecomment-884292879) has been the only thing that has gotten WSL to successfully create containers but it requires opening second console to connect to docker.

**Comment by jlethuau** [comment]
> I've got the same problem. My solution is:
> 
> 1. close Docker Desktop
> 2. restart Ubuntu through services.msc or this command (you can put in bat):
>    `net stop LxssManager && net start LxssManager`
> 3. start Docker again
> 
> You also may check if your distro is enabled in Docker settings (General tab and Resources tab -> WSL Integration). I don't know why but it switches off sometimes.

This solution worked perfectly for me too! Thanks

**Comment by dee-kryvenko** [comment]
Additionally to deleting folders and restarting LxssManager which didn't help, this worked for me:

```
wsl --unregister docker-desktop
wsl --unregister docker-desktop-data
```

**Comment by Edmartt** [comment]
> 
> 
> I had this problem too. The solutions above did not help me, but I found another fix:
> 
>     1. Right click the docker icon in the bottom right of the taskbar (it might be in the hidden icons tray)
> 
>     2. Click troubleshoot
> 
>     3. Clean/Purge Data
> 
>     4. Select all 3 and click delete
> 
>     5. Restart docker

The only solution working. :)

**Comment by imannms** [comment]
This happened after I updated Docker Desktop to a newer version. That's why I rarely update something if it's not broken. After I updated, instead of getting better, it became a headache. From now on, I won't be updating Docker or any other software again if it is not broken.

**Comment by clockwiser** [comment]
> > Hello
> > I had the same problem, to solve it I did the WSL Ubuntu updates (sudo apt update && sudo apt upgrade -y) and restarted Windows.
> > Hope this works for you.
> 
> This solutioin work for me, thk! I am in Windows 10 Home with docker desktop v4.0.0 (67817) and Engine: 20.10.8

Thanks. Only this solution worked.

**Comment by Vloupmon** [comment]
> Oh, I've just found a solution for my problem: I had a specific config in /etc/wsl.conf nameserver 1.1.1.1 I emptied the file, restarted wsl (wsl --shutdown from powershell) and now it works.

If somebody got here from having the same problem on **Debian**, in my case the fix was the same expect the nameserver is set up in `/etc/resolv.conf`. Just delete the file, restart Docker Desktop and it should good (with the nameserver set to the correct IP).

**Comment by dajtxx** [comment]
> Hello I had the same problem, to solve it I did the WSL Ubuntu updates (sudo apt update && sudo apt upgrade -y) and restarted Windows. Hope this works for you.

Seems weird, but docker desktop stopped working today and this fixed it.

**Comment by thias2021** [comment]
I got this error as well, and for me this was the chronology of events: 

1. I installed and set-up both Docker Desktop and Ubuntu 20.04 LTS on Windows 10 - it was working perfectly (WSL2)
2. I [changed the default WSL distro to Ubuntu](https://stackoverflow.com/questions/44049070/bash-on-ubuntu-on-windows-not-starting/46147036) so I could run some automated tasks with windows task scheduler
3. In the first moment, **_without restarting the PC_**, Ubuntu and Docker were running fine (Ubuntu as default distro for WSL)
4. After I restarted the PC, Docker started showing this error: "WSL integration with distro Ubuntu unexpectedly stopped with exit code 1"
5. I came back and made "docker-desktop" the default wsl 2 distro again, and......
6. Restarting the PC, everything was back to normal

**_So, based in my experience, it seems that Docker integration with Ubuntu cannot start when the default wsl distro is set to Ubuntu (or maybe anything other than "docker-desktop")_**

I saw that some users here made it work by doing:
```
wsl --unregister docker-desktop
wsl --unregister docker-desktop-data
```

It could be something related to that, as this seems to be unregistering the two distro options we have for WSL related to docker...

**Comment by zorzysty** [comment]
None of the suggestions mentioned above worked for me. And I've tried them all.

Turns out I had a pretty strange case: my `~/.docker/config.json` file was read-only. Making it writable fixed the issue.

**Comment by clockwiser** [comment]
> None of the suggestions mentioned above worked for me. And I've tried them all.
> 
> Turns out I had a pretty strange case: my `~/.docker/config.json` file was read-only. Making it writable fixed the issue.

Better try the update version on another machine first, then update the working machine. Last time after update, the docker on my machine stopped working, that was a horrible disaster.

**Comment by Jdban** [comment]
> Turns out I had a pretty strange case: my `~/.docker/config.json` file was read-only. Making it writable fixed the issue.

How did you figure that out? Are there logs somewhere?

**Comment by zorzysty** [comment]
> > Turns out I had a pretty strange case: my `~/.docker/config.json` file was read-only. Making it writable fixed the issue.
> 
> How did you figure that out? Are there logs somewhere?

There are some logs, but nothing in there pointed me to that. I actually had to recreate my whole environment on a new distro and one of the steps required to configure my project at work was to edit an entry in `~/.docker/config.json`. The thing is that every time Docker Desktop starts, it overwrites this entry with "desktop.exe". Making it read-only prevented that and worked fine until Docker Desktop started again. But this time instead of overwriting this file, it simply crashed saying `WSL integration with distro Ubuntu unexpectedly stopped with exit code 1.` Initially I failed to see the connection because it was running fine for few days straight and crashed only after the next system reboot. When recreating the environment I was restarting Docker Desktop after every single step to make sure it's still working and that's how I caught it.

**Comment by ivictbor** [comment]
> None of the suggestions mentioned above worked for me. And I've tried them all.
> 
> Turns out I had a pretty strange case: my `~/.docker/config.json` file was read-only. Making it writable fixed the issue.

Thanks, you saved my day! I changed laptop and copied some folders from WSL home folder on old PC, one of them was `.docker` and somehow all copied folders got root:root, so this command fixed the issue:

```
sudo chown -R $USER:$USER ~/.
```

PS: In my case I made it for all files in homedir.

The most disappointing thing that the Docker desktop dialog with error does not show a reason or at least clue where to get it (how to open some log, or run command in terminal to see stderr...). Just exit code 1. So people have to waste time guessing and searching for others help. And some cases might be very very rare like mine.

**Comment by khuyennguyen7007** [comment]
I have faced the problem `WSL integration with distro Ubuntu unexpectedly stopped with exit code 1. Do you want to restart it?` everytime I update the Docker Desktop for Windows. And I have no idea about this.
None of the suggestions mentioned above worked for me and `~/.docker/config.json` is writable on my machine. So I have fixed with these steps:
1. Quit the Docker Desktop.
2. Restart the WSL by the command `wsl --shutdown`.
3. Open the WSL again via Windows Terminal or Start -> Ubuntu xxx or something like this.
4. Open the Docker Desktop again.

It works like a charm. 
P/s: I think we should stop updating the app or the app should have a better error message.

**Comment by nwallis** [comment]
Same here, makes me wonder why I am even trying to get Docker to run properly on windows considering I need to move my containers to ubuntu anyway.  I might just install docker under ubuntu and take it from there....

**Comment by MeltpoolMartin** [comment]
I followed this thread since months, because I've suffered the same mentioned problems with the exception `WSL integration with distro Ubuntu unexpectedly stopped with exit code 1. Do you want to restart it?` over and over again.
I tried all the already mentioned workarounds like manually restarting with `wsl --shutdown` or wiping out the volumes. I did even completely reset my Ubuntu distro to start from scratch, which also only worked once.
But after all I found another way to overcome this annoying problem. The change that did the trick, is that I had two containers deployed on the "WSL side" with the restart policy `always.` 
I mean technically it's using the same docker daemon like the "Windows side", the difference is, that I had also the bind mounts pointing to an Ubuntu path. Removing those containers and redeploy them with `powershell` or `git bash` with a bind mount towards a real windows path did the trick for me.

**Comment by donmatis** [comment]
I had the same issue but my WSL home folder was copied from another WSL, in this case i had to make sure `~/.docker` folder had the correct owner. After that a restart on docker desktop and worked fine.

**Comment by joshkreud** [comment]
I could narrow down the Crash to the docker-compose `restart: always` flag. 
When I have a running compose stack with `restart: always`, it crashes on launch. 
Any other restart policy or just stopping the stack, seems to fix the crash.

**Comment by ClassicDarkChocolate** [comment]
I have this issue after upgrading my Docker Desktop to 4.8.2. This is because docker fails to start containers in wsl (this bug only occurs at windows startup).

I find that if I replace path `.` with `$(pwd)` in my compose file, the issue is gone.

**Comment by shucknite** [comment]
> If you're okay with losing the data, you can try:
> 
> powershell:
> 
> ```
> wsl --unregister docker-desktop
> wsl --unregister docker-desktop-data
> ```

it did not work
