### ISSUE TITLE
Unable to pull image

### ISSUE THREAD

**Issue by iHarshalAgarwal** [docker/for-win#9978]
I am trying to run a basic command - docker pull hello-world

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 9A4CEDFA-576E-4780-BAAE-380E31DA8ED4/20210101112454

### Expected behavior
Pull image successfully

### Actual behavior
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp: lookup https on "some_ip": no such host

### Information

  - Windows Version: Windows 10 Pro 1803
  - Docker Desktop Version: 3.0.0 (50684)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Windows Using Hyper-V

### Steps to reproduce the behavior

  1. Try to pull any Docker image

**Comment by jareqpl** [comment]
Possibly linked with: https://github.com/docker/for-win/issues/9851

**Comment by iHarshalAgarwal** [comment]
I restored to default and everything is working fine now

**Comment by stephen-turner** [comment]
Good, thanks for the update.

**Comment by jareqpl** [comment]
@iHarshalAgarwal  Have you had any custom settings in your configuration set ? If yes, do you recall what they were ?
I have data-root set on my windows machines. Maybe this is what triggers this issue. However i can't have docker data on system drive.

**Comment by iHarshalAgarwal** [comment]
@jareqpl , I faced the issue after updating to the latest version. And I had only proxy settings in my Docker desktop and the some basics like:
debug: true
experimental: false

However, I noticed a new setting after reset. May be you can try adding the below setting to your daemon.json
"features": {
    "buildkit": true
 }

**Comment by kenneho** [comment]
> I restored to default and everything is working fine now

This resolved my issue too.
