### ISSUE TITLE
DNS issues with stock Windows 10 Docker CE Install

### ISSUE THREAD

**Issue by GregoryPerry706** [docker/for-win#998]
C:\Users\gp>docker pull hello-world
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:47088->[::1]:53: read: connection refused

A diagnostic was uploaded with id: 37AE76EE-758B-4F1E-82E7-52109FCB7809/2017-08-11_15-09-34

Fully patched Windows 10 Professional with Hyper-V enabled

Version 17.06.0-ce-win19 (12801)
Channel: stable
c98c1c2

**Comment by lostllama** [comment]
Gregory, what did you do to resolve this?

**Comment by GregoryPerry706** [comment]
Installed Docker CE on a Linux host.
