### ISSUE TITLE
macos virtual box host, win10 ent 20h2: Failed to start the virtual machine 'DockerDesktopVM' because one of the Hyper-V components is not running

### ISSUE THREAD

**Issue by cristhiancastro** [docker/for-win#9989]
macosx high sierra
virtual box 6
windows 10 ent 20h2

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
Docker Desktop is not supported inside a VM, because Hyper-V may not be able to start. This is out of our control: it depends on whether the outer hypervisor allows Hyper-V to run.
